### ISSUE TITLE
Consumables - Have the ability to checkin user from 

### ISSUE THREAD

**Issue by maorweissSV** [grokability/snipe-it#10014]
**Server (please complete the following information):**

- Snipe-IT Version: V5.1.8
- OS: Ubuntu 20.04.3 LTS
- Web Server: nginx/1.18.0
- PHP Version : PHP 7.4.22

**Is your feature request related to a problem? Please describe.**
Yup. I want to assign and unassign my consumables to the users.
I.e: If I want to mark who uses our HDMI cables, and how many cables we have in the warehouse, so I'll create an HDMI cable item on the 'Consumables' section, with the total and minimum QTY, and will assign them to users (per item) as well. Just as I'm using a license with a number of seats!

**Describe the solution you'd like**
This is an example of an accessory that I've assigned users to:
![image](https://user-images.githubusercontent.com/83959332/131502986-8e681130-1dd3-4593-b0c1-c1945ebb712e.png)
![image](https://user-images.githubusercontent.com/83959332/131503100-a460a365-f575-4ca3-a763-b3db05d5d461.png)

And this is the situation that I have with the lack of the check-in action on the consumable item:
![image](https://user-images.githubusercontent.com/83959332/131503342-799a38bf-9475-43e9-bb2e-a6cf13d68dc8.png)
![image](https://user-images.githubusercontent.com/83959332/131503395-bf233695-b8a7-48d2-b448-a3eab4e3cbe9.png)

I cannot unassign users from the HDMI cables and as well I cannot manage my consumables...

**Additional context**
All I'm asking is the ability to check-in consumables, just as I can do with accessories and licenses.

**Comment by tsdigital** [comment]
I would consider an HDMI cable an accessory. Maybe my terminology is different, but a consumable to me would be paper, ink, batteries, etc.

**Comment by snipe** [comment]
@tsdigital you are correct. A consumable is meant to be… well, consumed. And HDMI cable isn’t going to be consumed, like printer ink, etc, so should be an accessory.
