### ISSUE TITLE
Archived Assets Showing Under Locations/'Print All Assigned' Feature

### ISSUE THREAD

**Issue by kennj3** [grokability/snipe-it#10015]
**Server (please complete the following information):**
Snipe-IT Version: v5.1.8
OS: Windows Server 2016
Web Server: IIS 10.0
PHP Version 7.4.0

**Is your feature request related to a problem? Please describe.**
When a user goes to Locations and selects a location, current assets are viewed correctly in the list (i.e. no Archived assets).  When you select the 'Print All Assigned' on the right-hand side of the page, a hand-receipt is displayed, but it then shows current and Archived assets under the Assets list.  In my mind, you would not sign for equipment that is Archived, such as it being lost, damaged, no longer in inventory, etc...  Also, I do not select the box under Settings 'Show archived assets in the "all assets" listing'.

**Describe the solution you'd like**
I would like to see as default, or a selectable option, to exclude Archived assets.  This would match the current assets list on the previous Locations page.

**Describe alternatives you've considered**
No alternatives are currently available.

**Additional context**
I have confirmed this issue to be the case on the demo and development sites as well as some of my internal Snipe-IT sites. I used the location Juvenalhaven as an example on your demo site.
https://demo.snipeitapp.com/locations/5 (Juvenalhaven Location page)
https://demo.snipeitapp.com/locations/5/printallassigned (Print All Assets page)

![Junvenhal Location](https://user-images.githubusercontent.com/62330950/131507661-68ce2b5f-56e3-4fde-aad6-ac2b1417245a.png)
![Print All Assets](https://user-images.githubusercontent.com/62330950/131507688-35694347-5c36-4e0d-add3-107a3eaeaa93.png)

**Comment by snipe** [comment]
In your Admin Settings > General, do you have this checkbox checked or unchecked?

<img width="536" alt="Screen Shot 2021-09-10 at 7 22 49 PM" src="https://user-images.githubusercontent.com/197404/132933366-ab5ff505-d5c9-4ac4-bdc4-b3aec4b043a4.png">

**Comment by kennj3** [comment]
That box is unchecked.  The asset count is correct (absent Archived) when that box is unchecked on the Locations page, but displays all assets ever assigned to a location, including Archived, when using the 'Print All Assigned' option.  I confirmed this is still the case in version 5.2 on the demo and develop sites.

**Comment by snipe** [comment]
@kennj3 thanks for the additional info.

@inietov - can you take a look on Monday?

**Comment by kennj3** [comment]
Works great.  Thank you!  Amazing as always.
