### ISSUE TITLE
LDAP TLS error when NOT using TLS

### ISSUE THREAD

**Issue by FerdiKubus** [grokability/snipe-it#10036]
I recently migrated my Snipe-IT installation to be able to setup the site correctly with HTTPS and logins for all users.
Before migrating I ran in a XAMPP install and had everything working.

Now live I'm running a Ubuntu server installed troug install.sh and imported database and images from backup.
Apache 2.4.41 
Snipe-IT versionv5.1.8 build 6257 
PHP Version7.4.23Laravel Version6.20.29PHP 7.4

In my LDAP config I now have 2 fields I did not have before
- LDAP Client-Side TLS key
- LDAP Client-Side TLS Certificate

I do not use TLS in my LDAP installation so I left these blank.

I then tested my LDAP connection:
![image](https://user-images.githubusercontent.com/89971298/131815208-4583d9de-16d6-410b-b249-4770d858ddd8.png)

And after that I tested the login:
![image](https://user-images.githubusercontent.com/89971298/131815326-db470721-9442-491d-94c7-66e25aa4e609.png)

when saving it get an error:

```
/var/www/snipeit/app/Models/Setting.php
    public static function get_client_side_key_path()
    {
        return storage_path().'/ldap_client_tls.key';
    }
 
    public function update_client_side_cert_files()
    {
        /**
         * I'm not sure if it makes sense to have a cert but no key
         * nor vice versa, but for now I'm just leaving it like this.
         *
         * Also, we could easily set this up with an event handler and
         * self::saved() or something like that but there's literally only
         * one place where we will do that, so I'll just explicitly call
         * this method at that spot instead. It'll be easier to debug and understand.
         */
        if($this->ldap_client_tls_cert) {
            file_put_contents(self::get_client_side_cert_path(), $this->ldap_client_tls_cert);
        } else {
            unlink(self::get_client_side_cert_path());
        }
 
        if($this->ldap_client_tls_key) {
            file_put_contents(self::get_client_side_key_path(), $this->ldap_client_tls_key);
        } else {
            unlink(self::get_client_side_key_path());
        }
    }
 
 
}
 
Arguments
"unlink(/var/www/snipeit/storage/ldap_client_tls.cert): No such file or directory"

```

I tried creating blank files, that enables me to save but when I try to sync users I run into the same problem because the files are deleted after saving my LDAP configuration

**Comment by FerdiKubus** [comment]
I found out that filling in something, doesn't have to be correct information in both TLS fields and than saving enables me to save the correct LDAP and now sync is also working

**Comment by uberbrady** [comment]
That's a clever workaround, and I'm sorry you had to deal with this. If you pull the latest from master you should see that this is now fixed.
