### ISSUE TITLE
Report a bug - accessory checkout issue - v4.94

### ISSUE THREAD

**Issue by conan522** [grokability/snipe-it#10049]
Report a bug - accessory checkout issue - v4.94

When I did a checkout for a accessory. Somehow page stuck, so I submit the "Checkout" button several times. Then I found this accessory has checkout several times, even total qty is only 1. So now the "Avail" became a "-9", it is not reasonable. Could be a bug of system.

**Comment by conan522** [comment]
Just confirmed v5.1.6 has the same bug.

**Comment by snipe** [comment]
You have to complete the bug report template, otherwise we do not have enough information to help you. Please file a new bug report and complete all of the questions in the template.
