### ISSUE TITLE
Unable to change status while checkout an asset 

### ISSUE THREAD

**Issue by Fuochizio** [grokability/snipe-it#10040]
- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

There is a problem when I try to do a checkout operation.
It happens in checkout for user, asset and location.

Is **not possible to change** the status of the asset during the checkout operation. The only way is to change modifying if using **edit** mode (but is not an efficient way to work).

**Steps to reproduce the behavior:**
1. Go to 'List Asset'
2. Click on 'Checkout'
3. Click on 'Status'
4. See error (only one status is showed)

**Expected behavior:**
I have to see all the Status Labels (created and native)

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.8 - build 6227 (master)
 - OS: Windows 10
 

![image](https://user-images.githubusercontent.com/89995003/131881298-6482fcd9-2de8-4a0a-9d92-d6f7cb0b615b.png)

**Comment by snipe** [comment]
I don’t think this is a bug. The only statuses we allow on checkout are ones that are set as deployable. Can you show me a screenshot of your status labels page?

**Comment by Fuochizio** [comment]
Thank you.
Sure, here there screenshot.

![image](https://user-images.githubusercontent.com/89995003/131966033-e3225f38-d960-4332-b68f-0a9506602dc7.png)

I tried setting the status I created (**busy**) from Undeployable to Deployable and now it works. Could be introduces the features that allows to set different status, or only Deployable?

**Comment by snipe** [comment]
I'm not sure the question to be honest. You can set as many status labels as you like. The status type (deployable, archived, etc) are important for the business logic.
