### ISSUE TITLE
Develop server https://develop.snipeitapp.com Not working

### ISSUE THREAD

**Issue by diegogarciadev** [grokability/snipe-it#10044]
Hello,

https://develop.snipeitapp.com is not working anymore? There are no data on the page and no menus available...

new v6 version is available at https://demo-v6.snipeitapp.com but I don't have the api key to make tests with the API.

Regards.

**Comment by Robert-Azelis** [comment]
I think, it is security issue (reason) - available backdoor to get admin permision for manage admin account. Overnight database should be recovery from backup.

**Comment by NorthstarIT** [comment]
It's also affecting the demo server as well

**Comment by diegogarciadev** [comment]
Today is not working again...

**Comment by snipe** [comment]
> I think, it is security issue (reason) - available backdoor to get admin permission for manage admin account.

We provide an admin login specifically so people can explore the superadmin functionality. 

This is working as far as I can see.

<img width="1393" alt="Screen Shot 2021-09-10 at 7 03 05 PM" src="https://user-images.githubusercontent.com/197404/132932718-6b4f886c-c2b6-4771-83b1-2249db383c29.png">
