### ISSUE TITLE
Add support for Heroku

### ISSUE THREAD

**Issue by jasonspriggs** [grokability/snipe-it#10062]
### Snipe-IT Version

5.1.8

### Operating System

Heroku

### Web Server

Apache

### PHP Version

7.4

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

This feature request is to help add an additional method for deploying Snipe-IT to Heroku's Platform as a Service setup.

### Describe the solution you'd like A clear and concise description of what you want to happen.

I would like to have a Deploy to Heroku button added to the application's README file that allows me to fill in environment variables and have a working copy of Snipe-IT up and running as quickly as possible.

### Additional context Add any other context or screenshots about the feature request here.

Pull request to follow! Just opening this GH Issue to follow PR practices. Please let me know if you'd like additional details and where. Thanks!

**Comment by snipe** [comment]
Merged into develop :)
