### ISSUE TITLE
SAML & LDAP issues. 

### ISSUE THREAD

**Issue by ignBiometrical** [grokability/snipe-it#10076]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

LDAP: When I was working with LDAP, I started to run into some issues. After getting the Bind DN, Login DN, etc. I started to hit some roadblocks. With the configuration of our LDAP, the CN is Firstname Lastname, whereas the username is uid. This had become apparent, as we needed to use the CN for authentication but still set the uid as username, we realized that without redoing the entire LDAP and any apps using it, we would need to rework the code. I have been trying for the last few hours to configure the app to use UID for the username when syncing, but CN for authentication. As well, once the users had gotten synced, no user was accessible due to all the password hashes being the same. This was causing inaccessibility.

SAML: Onto SAML, for SAML we are using Keycloak (An SSO Software), this is not at all the fault of the devs who have been extremely helpful, however, Keycloak uses clients for separating apps under the same realm, SAML was not sending a client. This is not a top priority, however it would be nice if it would be able to have a Client passed when using SAML in order to support Keycloak. 

### Reproduction steps

1. Enable LDAP, configure and confirm initial success.
2. Attempt to sync the users. 
3. Once they have been synced, enter the database and look at the hashes for all LDAP users, for me, these showed the same for all. This caused not being able to log in as anyone from LDAP.
...

### Expected behavior

The expected behavior would have been being able to configure, sync, and go, however most likely, this is a misconfiguration on my end and not the fault of Devs. I am open to suggestions and more. 

### Snipe-IT Version

v5.2.0 build 6339 (g14a8baeca)

### Operating System

Ubuntu 20.04.3

### Web Server

Apache

### PHP Version

7.4

### Operating System

Windows

### Browser

Google Chrome

### Version

93

### Additional context

It was installed with the install.sh.

**Comment by snipe** [comment]
@ignBiometrical Is this still an issue? I know there was some discussion in Discord.

**Comment by sokeada** [comment]
> @ignBiometrical Is this still an issue? I know there was some discussion in Discord.

I faced with LDAP sync issue after upgraded to 5.2.0 with php8, while it was 5.1.8 with php7.4, I can sync with LDAP normally.

**Comment by ignBiometrical** [comment]
> @ignBiometrical Is this still an issue? I know there was some discussion in Discord.

The issue has been fixed, thank you for the additional help.
