### ISSUE TITLE
Snipeit faulty mobile view

### ISSUE THREAD

**Issue by nubpro** [grokability/snipe-it#10089]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

![image](https://user-images.githubusercontent.com/762914/133653762-8fdbf60d-400b-4b66-ae7d-2aa559d59a5a.png)
As you can see, the top menu and the asset search field seems to be misaligned

![image](https://user-images.githubusercontent.com/762914/133653897-3c7aa310-925c-43dd-ac4a-a90c10ceca8a.png)
On the second picture, this is the all assets viewed on a mobile screen. The categories and status is misaligned and whereas the three actions buttons is missing a slight gap between the rows (nit).

![image](https://user-images.githubusercontent.com/762914/133654591-8935e69e-f42a-4860-96e0-29c5e2e42b48.png)
There's an opportunity to align these better as well

### Reproduction steps

View the all asset page on a mobile. I'm using iPhone X as an example

### Expected behavior

They should look and feel mobile friendly.

### Snipe-IT Version

5.2.0

### Operating System

Ubuntu

### Web Server

Nginx

### PHP Version

7 I think, Im using docker

**Comment by snipe** [comment]
@Godmartinz can you peep this when you get a moment?

**Comment by Godmartinz** [comment]
On it

**Comment by snipe** [comment]
The tricksy part here is that these styles are largely handled via the bootstrap tables library. If it helps, expense a license for Sizzy so you can easily test mobile locally. We may have to do some funky stuff in the `@media` section in `overrides.less`, where we only affect small screens. Ping me on slack if you need help.

**Comment by Godmartinz** [comment]
Ill try and keep an open dialogue of my progress, first update! I have a solution in place for the top menu misalignment. now when going to a mobile version the top menu will become the first option in the Nav list. 
![image](https://user-images.githubusercontent.com/47435081/133669256-a6cbc792-2b14-430c-a766-86ae04a529cd.png)

**Comment by Godmartinz** [comment]
I think for the table spacing I'm going to have to do some "child's play"

**Comment by Godmartinz** [comment]
Progress! Now..just need to get the status spiffy.
![image](https://user-images.githubusercontent.com/47435081/133675327-2c162b8a-9c5a-45f5-9fcb-d1d64f24f7fb.png)

**Comment by Godmartinz** [comment]
![image](https://user-images.githubusercontent.com/47435081/133680364-09b99c49-7266-4618-a55d-490db99c15a9.png)

Hmmm I can get the status row changes to reflect in the browser dev tools..but they aren't sticking when I load them in the `Override.less`

**Comment by snipe** [comment]
Did you run `npm run develop`? Remember that .less files only actually get used when the assets (JS/CSS) are compiled.

**Comment by Godmartinz** [comment]
oh yea constantly running that command. I think I'm targeting the element incorrectly. trying something new rn

**Comment by Godmartinz** [comment]
just to clarify the top menu adjustment and all the table alignments are working except for the device img and status rows.

**Comment by francogp** [comment]
This is related to https://github.com/snipe/snipe-it/issues/9935

**Comment by nubpro** [comment]
On a unrelated note, I think while working on this, this poses an opportunity to clean up the UI for the mobile view. One example is by removing apparent column titles such as Device Image, Checkin/checkout and Actions. Perhaps merging checkin and the actions button into a single row. What do you think?

**Comment by ccj9874** [comment]
My instance looks like this too on mobile.
