### ISSUE TITLE
Purchase price not saved correctly

### ISSUE THREAD

**Issue by opus-nbonenberger** [grokability/snipe-it#10088]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

There is something messed up with the thousands separator and decimal symbol in this case (German style of writing prices) when saving purchase prices in an asset.

### Reproduction steps

I have set localization to 

- German
- Default currency: EUR 1.234,56

1. When creating an asset and entering a purchase price of e.g. 27,83 it's saved and the asset overview displays EUR 2.783,00. 
2. When editing the asset again, the field "purchase price" also contains 2.783,00 and not 27,83. 
3. When saving the asset again without change, the asset overview displays a purchase price of EUR 2,78

### Expected behavior

Correct, not changing prices.

### Snipe-IT Version

5.2.0

### Operating System

Ubuntu Server 20.04 LTS

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

macOS Big Sur

### Browser

Google Chrome

### Version

93

**Comment by 2ndSysAdmin** [comment]
Same problem on our side, we are currently gathering all informations about our hardware and it is pretty annoying when the price is constantly changing like opus-nbo explained.
