### ISSUE TITLE
Import csv Internal Server Error

### ISSUE THREAD

**Issue by LTGroot** [grokability/snipe-it#10085]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

Freshly installed server on Ubuntu 20.04, trying to import Data with CSV file but it gets Error

### Reproduction steps

1. Installed Server
2. configured .env
3. finished all installation
4. tried upload CSV file with data
5. error (inspecting browser gives: internal server error 500; debug gives: no backup requested via importer)
...

### Expected behavior

able to upload big data

### Screenshots

![Uploading Screenshot asdasdasdasd132530.png…]()

### Snipe-IT Version

5.2.0

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4

### Operating System

Windows, ChromeBook

### Browser

chrome, edge 

### Version

chrome 93.0.4577.63

### Error messages

```shell
Browser Console:
all.js?id=f08c9424b41ed7189b22:1 POST http://192.168.1.100/api/v1/imports/process/2 500 (Internal Server Error)
(anonymous) @ all.js?id=f08c9424b41ed7189b22:1
o @ all.js?id=f08c9424b41ed7189b22:1
(anonymous) @ all.js?id=f08c9424b41ed7189b22:1
F @ all.js?id=f08c9424b41ed7189b22:1
n @ all.js?id=f08c9424b41ed7189b22:1
H @ all.js?id=f08c9424b41ed7189b22:1
H.<computed> @ all.js?id=f08c9424b41ed7189b22:1
postSave @ all.js?id=f08c9424b41ed7189b22:1
i @ all.js?id=f08c9424b41ed7189b22:1
e @ all.js?id=f08c9424b41ed7189b22:1

Debug Message:

[13:15:07] LOG.debug: Backup manually requested via importer
```

### Additional context

Ubuntu 20.04 Fresh install
Web Server Apache

i used to install Snipe it documentation and guide from this [Link](https://blog.masteringmdm.com/snipe-it-installation-on-ubuntu-server/)

Along the way, i tried to make a mail server but I made it default values in the .env file but debug still gives an error that cant reach my mail.domain.com mail server

![Uploading Screenshot 2021-09-15 132417.png…]()

**Comment by snipe** [comment]
Per the issue template, we need to know what's in the application error log.

**Comment by LTGroot** [comment]
> plication error log
access.log

> 192.168.1.105 - - [15/Sep/2021:16:37:45 +0400] "GET / HTTP/1.1" 200 51950 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:46 +0400] "GET /css/dist/skins/skin-blue.css?id=2da78d31ca46509e2927 HTTP/1.1" 200 1303 "http://192.168.1.100/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:46 +0400] "GET /css/dist/bootstrap-table.css?id=d729a1e2e97f290cc4e2 HTTP/1.1" 200 2536 "http://192.168.1.100/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:46 +0400] "GET /js/respond.js HTTP/1.1" 304 179 "http://192.168.1.100/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:46 +0400] "GET /js/html5shiv.js HTTP/1.1" 200 1700 "http://192.168.1.100/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:46 +0400] "GET /css/dist/all.css?id=37fdc8fe39054cbd2ad1 HTTP/1.1" 200 65612 "http://192.168.1.100/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:47 +0400] "GET /js/dist/all.js?id=f08c9424b41ed7189b22 HTTP/1.1" 200 318400 "http://192.168.1.100/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:47 +0400] "GET /js/dist/bootstrap-table.js?id=a17945119a381c758e1f HTTP/1.1" 200 415754 "http://192.168.1.100/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:49 +0400] "GET /js/pGenerator.jquery.js HTTP/1.1" 200 1641 "http://192.168.1.100/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:49 +0400] "GET /css/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 182 "http://192.168.1.100/css/dist/all.css?id=37fdc8fe39054cbd2ad1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:52 +0400] "GET /import HTTP/1.1" 200 45588 "http://192.168.1.100/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:54 +0400] "GET /import HTTP/1.1" 200 45642 "http://192.168.1.100/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:55 +0400] "GET /api/v1/fields HTTP/1.1" 200 1474 "http://192.168.1.100/import" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:37:55 +0400] "GET /api/v1/imports HTTP/1.1" 200 4635 "http://192.168.1.100/import" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:38:03 +0400] "POST /api/v1/imports/process/3 HTTP/1.1" 500 1274 "http://192.168.1.100/import" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"
192.168.1.105 - - [15/Sep/2021:16:38:04 +0400] "GET /_debugbar/open?op=get&id=X1f6c9d34c5098e071f49f1ffa0adc114 HTTP/1.1" 200 112817 "http://192.168.1.100/import" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84"

snipeIT.error.log is empty can`t get him work if you can help i`ll get all info :(

**Comment by rahulrana-XOM** [comment]
Hi @LTGroot did you fix this?
