### ISSUE TITLE
All Logins Broken - LDAP and Local

### ISSUE THREAD

**Issue by ASNIT** [grokability/snipe-it#10091]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Recently updated Snipe-IT from 4.7.7 to 5.2.0 now all users are unable to log into the Snipe-IT console. LDAP error shows in the Debug log even after running artisan snipeit:ldap-disable command and using a local account.

Users already logged in are able to navigate and do actions. Once logged out they can not log back in.

### Reproduction steps

1. Load up URL
2. Put Local User Credentials In
3. Get LDAP Error
...

### Expected behavior

Expected to log in with Local user account or LDAP accounts neither work.

### Screenshots

![image](https://user-images.githubusercontent.com/80910623/133665497-70855a5c-0866-4350-95e8-80e2185f45e1.png)

### Snipe-IT Version

v5.2.0

### Operating System

Ubuntu 18.04.2

### Web Server

Apache/2.4.29 (Ubuntu)

### PHP Version

7.2.24-0ubuntu0.18.04.9

### Operating System

Any

### Browser

Google Chrome, Edge & Firefox

### Error messages

```shell
var/www/snipe-it/app/Services/LdapAd.php
    {
        if ($this->ldapSettings['ad_append_domain']) { //if you're using 'userprincipalname', don't check the ad_append_domain checkbox
            $login_username = $username . '@' . $this->ldapSettings['ad_domain']; // I feel like could can be solved with the 'suffix' feature? Then this would be easier.
        } else {
            $login_username = $username;
        }
 
        if ($this->ldapConfig['username'] && $this->ldapConfig['password']) {
            $bind_as_user = false;
        } else {
            $bind_as_user = true;
        }
 
        if (($this->ldap) && ($this->ldap->auth()->attempt($login_username, $password, $bind_as_user) === false)) {
            throw new Exception('Unable to validate user credentials!');
        }    
 
        // Should we sync the logged in user
        Log::debug('Attempting to find user in LDAP directory');
        $record = $this->ldap->search()->findBy($this->ldapSettings['ldap_username_field'], $username);
 
        if($record) {
            if ($this->isLdapSync($record)) {
                $this->syncUserLdapLogin($record, $password);
            }
        }
        else {
            throw new Exception('Unable to find user in LDAP directory!');
        }
 
        $user = User::where('username', $username)
                ->whereNull('deleted_at')->where('ldap_import', '=', 1)
                ->where('activated', '=', '1')->first();
        /* Above, I could've just done ->firstOrFail() which would've been cleaner, but it would've been miserable to
           troubleshoot if it ever came up (giving a really generic and untraceable error message)
```

### Additional context

This is an upgrade. Install was a git install and git was the upgrade method.

**Comment by snipe** [comment]
Can you try using the create admin console command to create a new user that’s definitely not in ldap, and then disable ldap through the GUI?

**Comment by uberbrady** [comment]
Adjust your filter to only pick actual users, if you can. What type of ldap server is this? Often you can go with (objectClass=inetOrgPerson)

Also try and clear your caches.

**Comment by snipe** [comment]
When he says clear caches, he means run the command line stuff here: https://snipe-it.readme.io/docs/common-issues

We have seen this before, and we’re not sure why it happens, but running these commands often helps.

**Comment by ASNIT** [comment]
I had run the clear cache script previously but it errored our requiring elevated privileges to run, specifically the php artisan cache:clear portion. Running this time with elevated privileges seems to have helped the issue logging in with Active Directory accounts. I did create a secondary local admin who is able to log in as well as the original local admin.

However now I can not turn LDAP sync back on. When checking the LDAP enabled option and saving the debugger gives me a database query exception.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ldap_phone_field' in 'field list' (SQL: update `settings` set `ldap_enabled` = 1, `ldap_phone_field` = ?, `ldap_jobtitle` = ?, `ldap_country` = ?, `ldap_dept` = ?, `ldap_client_tls_cert` = ?, `ldap_client_tls_key` = ?, `settings`.`updated_at` = 2021-09-16 15:23:14 where `id` = 1)


![image](https://user-images.githubusercontent.com/80910623/133672818-81eb56a1-518e-4011-a705-88f5d0133351.png)

![image](https://user-images.githubusercontent.com/80910623/133673224-2ea7c030-13ac-4cc3-8f28-eef034432464.png)

**Comment by snipe** [comment]
Have you run migrations?

**Comment by ASNIT** [comment]
I don't believe so?

**Comment by snipe** [comment]
Whenever you upgrade, you always want to run migrations. Try `php artisan migrate` and paste in what results.

**Comment by ASNIT** [comment]
Migrating: 2020_10_22_233743_move_accessory_checkout_note_to_join_table
Migrated:  2020_10_22_233743_move_accessory_checkout_note_to_join_table (0.01 seconds)
Migrating: 2020_10_23_161736_fix_zero_values_for_locations
Migrated:  2020_10_23_161736_fix_zero_values_for_locations (0.01 seconds)
Migrating: 2020_11_18_214827_widen_license_serial_field
Migrated:  2020_11_18_214827_widen_license_serial_field (0.26 seconds)
Migrating: 2020_12_14_233815_add_digit_separator_to_settings
Migrated:  2020_12_14_233815_add_digit_separator_to_settings (0.14 seconds)
Migrating: 2020_12_18_090026_swap_target_type_index_order
Migrated:  2020_12_18_090026_swap_target_type_index_order (0.25 seconds)
Migrating: 2020_12_21_153235_update_min_password
Migrated:  2020_12_21_153235_update_min_password (0 seconds)
Migrating: 2020_12_21_210105_fix_bad_ldap_server_url_for_v5
Migrated:  2020_12_21_210105_fix_bad_ldap_server_url_for_v5 (0 seconds)
Migrating: 2021_02_05_172502_add_provider_to_oauth_table
Migrated:  2021_02_05_172502_add_provider_to_oauth_table (0.2 seconds)
Migrating: 2021_03_18_184102_adds_several_ldap_fields
Migrated:  2021_03_18_184102_adds_several_ldap_fields (0.13 seconds)
Migrating: 2021_04_07_001811_add_ldap_dept
Migrated:  2021_04_07_001811_add_ldap_dept (0.13 seconds)
Migrating: 2021_04_14_180125_add_ids_to_tables
Migrated:  2021_04_14_180125_add_ids_to_tables (0.14 seconds)
Migrating: 2021_06_07_155421_add_serial_number_indexes
Migrated:  2021_06_07_155421_add_serial_number_indexes (0.1 seconds)
Migrating: 2021_06_07_155436_add_company_id_indexes
Migrated:  2021_06_07_155436_add_company_id_indexes (0.79 seconds)
Migrating: 2021_07_28_031345_add_client_side_l_d_a_p_cert_to_settings
Migrated:  2021_07_28_031345_add_client_side_l_d_a_p_cert_to_settings (0.22 seconds)
Migrating: 2021_07_28_040554_add_client_side_l_d_a_p_key_to_settings
Migrated:  2021_07_28_040554_add_client_side_l_d_a_p_key_to_settings (0.25 seconds)
Migrating: 2021_08_11_005206_add_depreciation_minimum_value
Migrated:  2021_08_11_005206_add_depreciation_minimum_value (0.13 seconds)
Migrating: 2021_08_24_124354_make_ldap_client_certs_nullable
Migrated:  2021_08_24_124354_make_ldap_client_certs_nullable (0.01 seconds)

**Comment by snipe** [comment]
Excellent. Thats what I want to see. Now can you save your settings?

**Comment by ASNIT** [comment]
Success: Settings updated successfully. Looks like that solved it. 

In the future should we follow the "After Pulling the New Version Files" instructions under the Upgrading Manually section?

**Comment by snipe** [comment]
Any time you upgrade, you always want to run migrations. They are what’s used to keep the DB schema up to date with the code. The upgrade.php script (which you can use with a manual install or git, it just won’t pull new source files - it will do everything else tho - running migrations, clearing app caches, etc.) I definitely suggest switching to a git install if you can, but upgrade.php should be able to handle a lot of the dumb commands you need to run when upgrading.

**Comment by ASNIT** [comment]
We are using a git install and we updated using git, but I'll remember to run the manual clean up commands next time.

Thanks for the assistance you can close this issue.

**Comment by snipe** [comment]
If you’re using a git install, your life will be a lot easier if you just run upgrade.php. It was designed for git installs in mind, and it just automates a lot of the maintenance tasks that have to happen to ensure a clean upgrade so that you don’t have to remember to. 

So glad you’re sorted now :)
