### ISSUE TITLE
php not found, composer failed, tried to use install.sh script.

### ISSUE THREAD

**Issue by novarlynx** [grokability/snipe-it#10105]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Trying to use snipe-it for the first time and i've spent 9 hours trying to get it to work in an existing VM with no success. Decided to spin up a new VM and give the install.sh script a try. Looks like PHP didn't even install, and it caused the script to fail at composer.

### Reproduction steps

Install CentOS.
Set static IP.
Log in as root.
Follow instructions for install.sh

### Expected behavior

It's supposed to work!!

### Snipe-IT Version

Whatever version the install.sh installs.

### Operating System

centos-release-7-4.1708.el7.centos.x86_64

### Web Server

apache

### PHP Version

7.1

### Additional context

This is a fresh installation, trying to use it for the first time.
Method = install.sh

Here's a dump from my console. After the script failed I ran some commands to check what was installed, discovered nothing related to PHP is present at all.

`
[root@snipe-it ~]# wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
--2021-09-20 22:55:03--  https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133,                            ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 371 [text/plain]
Saving to: ‘install.sh’

100%[============================================================================>] 371         --.-K/s   in 0s

2021-09-20 22:55:04 (13.8 MB/s) - ‘install.sh’ saved [371/371]

[root@snipe-it ~]# chmod 744 install.sh
[root@snipe-it ~]# ./install.sh
--2021-09-20 22:55:11--  https://raw.githubusercontent.com/snipe/snipe-it/master/snipeit.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133,                            ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25136 (25K) [text/plain]
Saving to: ‘snipeit.sh’

100%[============================================================================>] 25,136      --.-K/s   in 0.02s

2021-09-20 22:55:11 (1.18 MB/s) - ‘snipeit.sh’ saved [25136/25136]

       _____       _                  __________
      / ___/____  (_)___  ___        /  _/_  __/
      \__ \/ __ \/ / __ \/ _ \______ / /  / /
     ___/ / / / / / /_/ /  __/_____// /  / /
    /____/_/ /_/_/ .___/\___/     /___/ /_/
                /_/

  Welcome to Snipe-IT Inventory Installer for CentOS, Fedora, Debian and Ubuntu!

  The installer has detected centos version 7.
  Q. What is the FQDN of your server? (snipe-it): 192.168.1.220
     Setting to 192.168.1.220

  Q. Do you want to automatically create the database user password? (y/n) y

* Adding IUS, epel-release and MariaDB repositories.
* Installing Apache httpd, PHP, MariaDB and other requirements.
  * Installing httpd
  * Installing mariadb-server
  * Installing git
  * unzip already installed
  * Installing php71u
  * Installing php71u-mysqlnd
  * Installing php71u-bcmath
  * Installing php71u-cli
  * Installing php71u-common
  * Installing php71u-embedded
  * Installing php71u-gd
  * Installing php71u-mbstring
  * Installing php71u-mcrypt
  * Installing php71u-ldap
  * Installing php71u-json
  * Installing php71u-simplexml
  * Installing php71u-process
* Configuring Apache.
* Setting up hosts file.
* Setting MariaDB to start on boot and starting MariaDB.
* Securing MariaDB.

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none):
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MariaDB
root user without the proper authorisation.

Set root password? [Y/n] y
New password:
Re-enter new password:
Password updated successfully!
Reloading privilege tables..
 ... Success!

By default, a MariaDB installation has an anonymous user, allowing anyone
to log into MariaDB without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

Remove anonymous users? [Y/n] y
 ... Success!

Normally, root should only be allowed to connect from 'localhost'.  This
ensures that someone cannot guess at the root password from the network.

Disallow root login remotely? [Y/n] y
 ... Success!

By default, MariaDB comes with a database named 'test' that anyone can
access.  This is also intended only for testing, and should be removed
before moving into a production environment.

Remove test database and access to it? [Y/n] y
 - Dropping test database...
 ... Success!
 - Removing privileges on test database...
 ... Success!

Reloading the privilege tables will ensure that all changes made so far
will take effect immediately.

Reload privilege tables now? [Y/n] y
 ... Success!

Cleaning up...

All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure.

Thanks for using MariaDB!
* Creating Snipe-IT user.
* Creating MariaDB Database/User.
* Please Input your MariaDB root password:
Enter password:
* Cloning Snipe-IT from github to the web directory.
* Configuring .env file.
* Installing composer.
-bash: php: command not found
-bash: php: command not found
ERROR: Invalid composer installer signature
rm: cannot remove ‘composer-setup.php’: No such file or directory
[root@snipe-it ~]#
[root@snipe-it ~]#
[root@snipe-it ~]#
[root@snipe-it conf.d]# yum list installed | grep php
[root@snipe-it conf.d]# yum list installed | grep -i php
[root@snipe-it conf.d]# yum list installed | grep -i httpd
httpd.x86_64                          2.4.6-97.el7.centos              @updates
httpd-tools.x86_64                    2.4.6-97.el7.centos              @updates
[root@snipe-it conf.d]# yum list installed | grep -i mariadb
mariadb.x86_64                        1:5.5.68-1.el7                   @base
mariadb-libs.x86_64                   1:5.5.68-1.el7                   @base
mariadb-server.x86_64                 1:5.5.68-1.el7                   @base
[root@snipe-it conf.d]#
`

**Comment by LTGroot** [comment]
maybe try to play with docker installation? it is more fast and easy
