### ISSUE TITLE
Bulk assign of licenses

### ISSUE THREAD

**Issue by cloggg** [grokability/snipe-it#10131]
### Snipe-IT Version

v5.1.8 - build 6257

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.3

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Buying a pack of  licenses (let's say dor 20 seats) requires checkout procedure for each seat.
This is annoying.
Would be much better if the system offers 'bulk license checkout', especially if all the licenses arre assigned to the same asset / user

### Describe the solution you'd like A clear and concise description of what you want to happen.

- Click on a license pack
- Click on Bulk Assign button
- System displays CheckOut form
- Options: 
- - Checkout to : (Asset / User)
- - New record: Number Of LIcenses to Checkout (numeric) and Asset/User (from dropdown menu) [It is possible to assing many licenses to the same assets or users)
- - notes
* Additional realtime validation for quantity of remaining licenses would be nice

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

I was assigning a license to each sit one by one. 90 times ;)

**Comment by snipe** [comment]
This is available via cli. https://snipe-it.readme.io/docs/bulk-license-checkoutcheckin

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/bulk-license-checkoutcheckin">Bulk License Checkout/Checkin</a></strong></div><div>If you need to check out a particular license to all users (for example an Office 365 license, which every user in your organization should theoretically have) or bulk checkin a license from all users (for example if you stopped using G-Suite), there is a console command to let you do that: and The ...</div></blockquote>

**Comment by wbrhenry** [comment]
I wanted to follow up on this request. I see that the CLI can do all users, but is it possible to do a specific list of users? For example i am just getting started with the software and I am adding in my licenses. I have about 100 users and some software may be in use by 40 of them. Is there anything for this?

**Comment by Gobel25** [comment]
Would it be possible to add to the CLI to bulk assign to all assets? For example, we have a limited amount of anti-virus licenses which we want as default on all machines. It would be great to be able to assign this to multiple machines, and not one at a time :)

**Comment by SanWach** [comment]
How come something so trivial has not been implemented yet?

**Comment by snipe** [comment]
@SanWach if it were in fact trivial, it would have been implemented already. Please see the licenses epic before talking about how trivial things are.

**Comment by alcyonshipping** [comment]
> I wanted to follow up on this request. I see that the CLI can do all users, but is it possible to do a specific list of users? For example i am just getting started with the software and I am adding in my licenses. I have about 100 users and some software may be in use by 40 of them. Is there anything for this?

I second this. In our case we want to distribute 55 licenses to specific assets. It would be good if we could, for example, run a search, check the assets that we want to assign the license to and click "Check out" instead of having to do it 55 times (or tamper with the database).
