### ISSUE TITLE
get user profile image from Active Directory(ldap)

### ISSUE THREAD

**Issue by imRezaAlie** [grokability/snipe-it#10160]
Hi Dears,
how can i get user profile image from Active Directory(ldap)?

regards,

_Originally posted by @imRezaAlie in https://github.com/snipe/snipe-it/discussions/10143_

**Comment by snipe** [comment]
That’s not possible at this time.

**Comment by imRezaAlie** [comment]
Hi Dear @snipe ,
 i can retrieve  user thumbnailPhoto from LDAP:
steps 1:
   add new column ( `ldap_avatar`) and fillable in related Model
step 2 : 
   create new command  => LdapAvatar:sync
and write this code:
`
public function handle()
{
    ini_set('max_execution_time', 60000);
    ini_set('memory_limit', '5000M');
    $ldapPort = Setting::getSettings()->ldapPort;
    $ldapHost = Setting::getSettings()->ldapPort;
    $ldapUserName = Setting::getSettings()->ldap_uname;
    $ldapPassword = '*************';
    $ldapBaseDn = Setting::getSettings()->ldap_basedn;
    $users = User::all();
    $connection = @ldap_connect($ldapHost, $ldapPort);
    ldap_set_option($connection, LDAP_OPT_REFERRALS, 0);
    ldap_set_option($connection, LDAP_OPT_PROTOCOL_VERSION, 3);
    ldap_set_option($connection, LDAP_OPT_NETWORK_TIMEOUT, 20);
    ldap_set_option($connection, LDAP_OPT_SIZELIMIT, -1);

    ldap_bind($connection, $ldapUserName, $ldapPassword);
    if (!$connection) {
        \Log::debug('Could not connect to LDAP server at ' . $ldapHost . '. Please check your LDAP server name and port number in your settings.');
    }
    foreach ($users as $user) {
        $search_filter = '(&(mail=' . $user->email . '))';
        $attributes = array();
        $attributes[] = 'thumbnailPhoto';
        $search_results = @ldap_search($connection, $ldapBaseDn, $search_filter, $attributes);
        $entries = ldap_get_entries($connection, $search_results);
        if ($entries['count'] > 0) {
            if (isset($entries[0]['thumbnailphoto'][0])) {
                $img = base64_encode($entries[0]['thumbnailphoto'][0]);
                User::findOrFail($user->id)->update(['ldap_avatar' => $img]);
            }
        }

    }
    ldap_close($connection);

`


step 3 :
   add this line in related Blade
`
    <img src="data:image/jpeg;base64,<?php echo base64_encode($ldap_avatar); ?>"/>
`

**Comment by SonGokussj4** [comment]
Hi. I see this as closed. Was this resolved for the newest version? [Gitea just released](https://github.com/go-gitea/gitea/pull/16851) a version that reads `thumbnailPhoto` and it's working well.
