### ISSUE TITLE
CSS displaying font color differently on mobile (white text on white background)

### ISSUE THREAD

**Issue by aranar-pro** [grokability/snipe-it#10191]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Side by side comparison of Desktop Browser to Mobile (safari) showing different font color for "dropdown-menu" items (Create New).  Tested in versions 5.1.8 (Windows/IIS) and 6.0 (Demo site).
Desktop: .skin-blue .main-header .navbar .dropdown-menu li {color: #333} from all.css (dark text on white background)
Mobile: .skin-blue .main-header .navbar .nav > li > a : {color: #fff} from skin-blue.css (White Text on White background)

### Reproduction steps

1.  Open https://develop.snipeitapp.com on Mobile (Safari iOS, Crome for iOS)
2.  Click "Create New" drop down menu.
3.  Text appears white on a white background.

### Expected behavior

Text in dropdown-menu should be black on a white background similar to desktop site.

### Screenshots

Mobile: ![IMG_1897](https://user-images.githubusercontent.com/484742/136992777-e39a5675-29eb-456c-b774-0ee4c59e1768.PNG)
Desktop:
<img width="1399" alt="Screen Shot 2021-10-12 at 12 19 01 PM" src="https://user-images.githubusercontent.com/484742/136993193-ecb3584a-ac2e-44bd-84c4-8ca8d057498d.png">

### Snipe-IT Version

5.1.8 & 6

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4

### Operating System

MacOS

### Browser

Safari

### Version

14

### Device

iPhoneXS

### Operating System

14.8

### Browser

Chrome (iOS) , Safari (iOS) 

### Version

94.04606.76, 14.8

### Error messages

```shell
In Desktop Browser, Demo site (v6) produces following errors:

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (ekko-lightbox.js.map, line 0)
```

### Additional context

Demo site v6 (confirmed on personal site 5.1.8 IIS, PHP 7.4)

**Comment by Godmartinz** [comment]
#10728
