### ISSUE TITLE
Can't download a File which is attached to a asset

### ISSUE THREAD

**Issue by MuratKurnaz** [grokability/snipe-it#10200]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi everyone,

my Name is Murat and I deal with snipe as a working student at my job. My Problem is simple and short. Clicking on a Asset in Snipe-IT opens a new Site only for this particular Asset. With all information this asset can provide. This informations are provided by 7 tabs. Details, license, components, assets, maintenance, history, files.

The tab "files" is there to upload files, belonging to that asset. So i started uploading the receipts of each assets in this tab. But when i try to download one of these files again, i get this error message:

File private_uploads/assets/[name of the pdf file].pdf not found on server

But not every asset has got this problem. Only by some. 

Thank you in advance

### Reproduction steps

1. Click on a asset and open the tab "Files"
2. Upload a pdf file
3. Download this file
...

### Expected behavior

The behavior i expect is, that i can simple download the pdf file

### Screenshots

![Bildschirmfoto 2021-10-15 um 17 16 23](https://user-images.githubusercontent.com/77493758/137511658-b473a10e-2af8-4f8a-acd3-17f08528db2d.png)

### Snipe-IT Version

v5.1.8 build 6148 (g3ca3de9e4)

### Operating System

cant tell

### Web Server

cant tell

### PHP Version

7.2.24-0ubuntu0.18.04.7

**Comment by Relix360** [comment]
Have you check if those file are actually on the server?

**Comment by MuratKurnaz** [comment]
I mean,

it doesn't make sense, that those files are not on the server. I uploaded them to the respective asset and because of that, snipe-it offers a download button, for those files. 

How can i check, if those files are on the servers or not? I am only using snipe-it at work. 

I can't be the only one with this problem.

**Comment by Relix360** [comment]
@MuratKurnaz If u have access to the server u need go to the web directory and then to the path show on the error. 
If those files are not there, someone delete it

**Comment by MuratKurnaz** [comment]
My Problem got solved. One of our developer, who start up Snipe-IT on one of our servers, forgot to make the server persistence. 

Thank you for your help.

**Comment by snipe** [comment]
Great, glad to hear you're sorted :)
