### ISSUE TITLE
Any Update over general settings won't save (After Upgrade)

### ISSUE THREAD

**Issue by nextorete** [grokability/snipe-it#10219]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

It can not modify the auto-increment number, after saving stills same.

### Reproduction steps

1. Open admin console
2. Clic Asset Tag
3. Modify any check or field.
4. Save
5. It doesn´t change at all.

### Expected behavior

Expecting save any change.

### Screenshots

![imagen](https://user-images.githubusercontent.com/93088355/138600607-d6edba10-d6ee-49f3-aeaf-97fa60a09ce0.png)

### Snipe-IT Version

Version v5.3.0 - build 6470

### Operating System

Centos

### Web Server

Apache

### PHP Version

7.3

**Comment by snipe** [comment]
Are you still seeing this issue on the latest version?

**Comment by nextorete** [comment]
> Are you still seeing this issue on the latest version?

After Upgrading to 5.4.1 Works Fine.  Solved !!

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
