### ISSUE TITLE
artisan route:cache Unable to prepare route [api/v1] for serialization. Uses Closure.

### ISSUE THREAD

**Issue by wenjy** [grokability/snipe-it#10224]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Unable to prepare route [api/v1] for serialization. Uses Closure.

### Reproduction steps

1. composer install --no-dev
2. php artisan optimize

### Expected behavior

successfully

### Snipe-IT Version

5.3.0

### Operating System

Centos7

### Web Server

nginx

### PHP Version

7.4.24

**Comment by snipe** [comment]
You don't need to cache the routes. You can skip `php artisan optimize` for now

**Comment by wenjy** [comment]
OK Thanks

**Comment by snipe** [comment]
Reopening this, since it *is* a legitimate bug, just not one that breaks anything.

**Comment by inietov** [comment]
I'm sorry, I think this can't be fixed without rewriting all of our existing routes. The Laravel documentation warns that this is not possible with routes using closures https://laravel.com/docs/6.x/deployment#optimizing-route-loading:
![image](https://user-images.githubusercontent.com/653557/138943472-6a04a898-a831-40df-aa69-2cf549091a69.png)

which we use extensively. So, unfortunately, I don't think we can address this issue in short term...

<blockquote><img src="/img/favicon/favicon.ico" width="48" align="right"><div><strong><a href="https://laravel.com/docs/6.x/deployment#optimizing-route-loading">Deployment - Laravel - The PHP Framework For Web Artisans</a></strong></div></blockquote>

**Comment by snipe** [comment]
FYI, this is related to https://github.com/snipe/snipe-it/pull/11595, where we had done a lot of fixes. In Laravel 8, the closure isn't the issue anymore, but rather duplicate names for routes.
