### ISSUE TITLE
Since upgrading to v5.3 can't upload pictures within an asset

### ISSUE THREAD

**Issue by tamfadmin** [grokability/snipe-it#10229]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Since upgrading to version 5.3, I cannot upload pictures within an asset.  Whenever I click on upload, load a picture, the picture attaches but there's not picture.  I have refreshed the screen, cleared the cache and tried a different browser.

When you view the Recent Activity, it shows that the action occurred even though it doesn't work.

If I select to Edit an asset, I can upload the picture.

### Reproduction steps

1.  Cleared cache in Edge and Chrome.
2.  Tried uploading the pictures again.
3.  Tried uploading pictures to a different asset.
...

### Expected behavior

The image that I select to upload should upload and then be displayed.

### Screenshots

![snipeit1](https://user-images.githubusercontent.com/25690788/138876635-aae6a82e-1971-4543-8b7d-7d689435dae0.jpg)

![snipeit2](https://user-images.githubusercontent.com/25690788/138876657-d0ce41b2-5e33-4cdf-8975-fe6b6431d156.jpg)

![snipeit3](https://user-images.githubusercontent.com/25690788/138876673-bb7827b1-fabc-4647-9803-cfac8f3cec29.jpg)

![snipeit4](https://user-images.githubusercontent.com/25690788/138876687-e3a74789-5430-4d78-b76d-5aff80023dc8.jpg)

![snipeit5](https://user-images.githubusercontent.com/25690788/138876730-ba155f1e-2076-4988-87fc-c53c23fae4d9.jpg)

### Snipe-IT Version

5.3

### Operating System

Windows Server 2019 Standard

### Web Server

IIS

### PHP Version

7.4.13

### Operating System

Windows 10

### Browser

Edge, Chrome

### Version

Edge - Version 95.0.1020.30 (Official build) (64-bit); Chrome Version 95.0.4638.54 (Official Build) (64-bit)

### Error messages

```shell
There aren't any error messages.
It functions as though the action works as you will see in the screen shots.
```

**Comment by craigj1222** [comment]
You can go to the "Files" tab and you should see your uploaded image(s).

**Comment by tamfadmin** [comment]
Hi,

Thanks for the response.  From within the Files tab, I can see the documents I've uploaded.

However, since upgrading to v5.3, whenever I upload an image of the asset that I'm creating, it goes through the process of showing that it was successful, but the image never shows up.

Instead, the image doesn't appear even after refreshing, clearing the cache, trying different browsers, etc.


***@***.***


Thanks again,
Cameshia

**Comment by tamfadmin** [comment]
This is what I should see after uploading an image for the asset.
Thanks.
![snipeit53](https://user-images.githubusercontent.com/25690788/138943742-abd41e1e-1e73-42c5-a7fc-e3c98508565c.jpg)

**Comment by snipe** [comment]
Hi @cdcs68 - the image in your last screenshot wouldn't be one that shows up from using the "upload files" function. It can be a bit confusing, but when you create/edit an asset, on THAT screen you have the option to upload *one* image. Its sort of the "this is what the product look like" image. Uploaded files can be anything - xml files, license files, etc. So you'd never see something you uploaded via Upload Files in that right-hand rail.

**Comment by tamfadmin** [comment]
Ok, thanks.
