### ISSUE TITLE
[Docker] supervisor-exit-event-listener exits with status 127, "not expected"

### ISSUE THREAD

**Issue by kamakazikamikaze** [grokability/snipe-it#10231]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Using Docker image with tag v5.3.0, starting the container results in the supervisord eventlistener "[exit_on_any_fatal](https://github.com/snipe/snipe-it/blob/83200d3cbd5917ea1c2b6dbc6f154491282eb43d/docker/supervisord.conf#L25)" to immediately fail, regardless if all other services are running properly. This does not cause the container to exit immediately.

The message: `INFO exited: exit_on_any_fatal (exit status 127; not expected)`

It appears that the issue is python(2) not being available in the Ubuntu image. The [script](https://github.com/snipe/snipe-it/blob/83200d3cbd5917ea1c2b6dbc6f154491282eb43d/docker/supervisor-exit-event-listener#L1) is run directly and tries to invoke `python`, which does not exist. `python3`, however, does, and changing `#!/usr/bin/env python` to `#!/usr/bin/env python3` appears to fix the issue.

### Reproduction steps

1. `docker pull snipe/snipe-it:v5.3.0`
2. Assuming environment is not already set up (MySQL, mail, etc.), set up services as necessary
3. `docker run ...`
...

### Expected behavior

`exit_on_any_fatal` should not exit immediately. A successful launch would show:
`INFO success: exit_on_any_fatal entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)`

### Snipe-IT Version

5.3.0

### Operating System

Ubuntu

### Web Server

apache

### PHP Version

7.x

### Additional context

Docker, fresh install.

**Comment by uberbrady** [comment]
I'm going to see if I can reproduce this, and then see if the suggested fix seems to fix it.

**Comment by Wouter0100** [comment]
I had the same issue. The following Dockerfile fixes it.

```
FROM snipe/snipe-it:v5.3.0

RUN sed -i -e "s/python/python3/" /usr/bin/supervisor-exit-event-listener
```

**Comment by snipe** [comment]
@Wouter0100 thanks so much for the update!
