### ISSUE TITLE
Asset CSV Import

### ISSUE THREAD

**Issue by bobiobobhead** [grokability/snipe-it#10230]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am unable to import assets using the CSV template, the error is Asset "": The model id field is required. The asset tag field is required.

I have tested this just using the template CSV and 1 of the example lines, not edited any of the headers and when I try to import it still shows this message.  I have an asset tag number in the CSV and all headers are mapped on the import, using assets as the import type, not really sure how to proceed with this.

### Reproduction steps

1.import template CSV file
2.Run the import
3. see the error
...

### Expected behavior

 expected asset import

### Screenshots

![image](https://user-images.githubusercontent.com/79217617/138896849-1d1adf7d-b832-424b-88e2-743e065fcbb8.png)

![image](https://user-images.githubusercontent.com/79217617/138896932-4c07cc53-05d4-4878-aae1-e9821cc9793a.png)

![image](https://user-images.githubusercontent.com/79217617/138897399-4a32c0e0-4866-4494-a4c9-1660e686b080.png)

### Snipe-IT Version

v5.3.0 build 6470 (gf87ffb84d)

### Operating System

ubuntu 20.04.1

### Web Server

Apache

### PHP Version

7.2.34-24

**Comment by skooota** [comment]
Please let me know if you find the solution to this bug. 

edit: For me I went back to my "list all" assets and everything i was trying to import was there. So it seems like its importing properly but then reporting that error for no reason?

**Comment by inietov** [comment]
I've just tried this and I couldn't reproduce the issue. The import works well with the example file in the docs: https://snipe-it.readme.io/docs/importing

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing">Importing Assets and More</a></strong></div><div>There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...</div></blockquote>

**Comment by sylvank** [comment]
Hi, new to Snipe, just finished my first import from an old Filemaker system.

Open your .csv in a text editor and check that you don't have any empty rows that look like:
,,,,,,,,,,

That may be what the script is stumbling on.

Beyond that, make sure every entry has a model number, even if you have to enter "Unknown".

**Comment by snipe** [comment]
> Beyond that, make sure every entry has a model number

Model number is not required, and isn't the same as model ID. Model ID is the unique identifier of the asset model.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
