### ISSUE TITLE
User Account administration

### ISSUE THREAD

**Issue by Dexebal** [grokability/snipe-it#10267]
### Snipe-IT Version

v5.3.0 build 6470

### Operating System

Debian 9

### Web Server

Apache

### PHP Version

7.4.24

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

- User was created without a password, email address

- It was assigned to the user equipment

- Then I want to give the user access to his account

A button "Send access data" is missing.

When I press "reset Password" the username is not mentioned.

### Describe the solution you'd like A clear and concise description of what you want to happen.

A Button " Send User Access Data" or "Send User and Password" if only Email Address registered.

**Comment by snipe** [comment]
If there is no email address, we have no way to email a user their credentials or a password reset link.
