### ISSUE TITLE
D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

### ISSUE THREAD

**Issue by Cjfrancisco2022** [grokability/snipe-it#10263]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I experienced an error when I checked the snipe that I installed on the shared server, can anyone help me with this error?
I'm the first-timer to install on the shared server.

### Reproduction steps

1. Checked the .env file
2.
3.
...

### Expected behavior

I want to see the setup page since I already installed this appsthis app

### Screenshots

![image](https://user-images.githubusercontent.com/93236329/140005607-00619bdd-a872-4ef7-9850-9ff8f6930cae.png)

### Snipe-IT Version

latest version

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

Php 7.3

### Operating System

Ubuntu

### Browser

Google

### Version

latest

### Device

Iphone

### Operating System

latest

### Browser

Safari

### Version

latest

**Comment by Kreidos** [comment]
Juat as the message says, your web server has something like `/var/www/html/snipeit` set as its HTML root. It should be the `var/www/html/snipeit/public` folder.

**Comment by Cjfrancisco2022** [comment]
Thank you for the helps and information but I just want to inform you that I'm currently using the shared server and I already put the snipeit folder to the root directory it looks like this.

![image](https://user-images.githubusercontent.com/93236329/141028981-2fb09a58-054c-4a59-988c-51051b1c8985.png)

**Comment by Kreidos** [comment]
If you open that `snipeit` folder, you'll see the `snipeit/public` folder I described. **that folder** needs to be your Document Root. I don't have familiarity with shared hosting; I assume that's cpanel you're using, you might want to try googling how to change your document root in cpanel, or reach out to your hosting provider for assistance.

**Comment by Cjfrancisco2022** [comment]
I understand, It's already here in Document Root. I think there is an issue with our current shared hosting, the provider inform us that we have limited access regarding the root access since we are in shared hosting. thank you sir for your efforts.

**Comment by Cjfrancisco2022** [comment]
I tried also on my own VPS no problem was encountered, but this our company shared server has an issue.

**Comment by TechBreakHelp** [comment]
If you have access to `.htaccess` file in the `public_html`, you can edit it. Otherwise you can modify webserver configuration (apache,nginx) and use a third domain level (snipeit.mydomain.com) which redirects to that folder. Look for these configurations.

**Comment by Cjfrancisco2022** [comment]
> If you have access to `.htaccess` file in the `public_html`, you can edit it. Otherwise you can modify webserver configuration (apache,nginx) and use a third domain level (snipeit.mydomain.com) which redirects to that folder. Look for these configurations.

Thank you @TechBreakHelp I will do that if possible what code or command input on the htaccess?

**Comment by TechBreakHelp** [comment]
I'm not an expert, but this should do his job `DirectoryIndex /var/www/public_html/snipeit/public`

⚠ Warning: This line will over write your current default website. So with yourdomain.com you will see Snipe-IT **only**, no other services. Indeed, is it common to edit the apache config in order to use a third domani snipe.yourdomain.com and keep yourdomain.com as it is.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by Chamira-Lakmal** [comment]
Hi um stuck with installing snipe-it in cpanel
