### ISSUE TITLE
/admin/hardware/table.current_value missing ? 

### ISSUE THREAD

**Issue by fbouchard2** [grokability/snipe-it#10261]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello! 
after updating to the new version - it appears one of the language keys is missing. 
in the file 
resources/views/hardware/views.blade.php - line 493 :       {{ trans('admin/hardware/table.current_value') }}
and the 
/resources/lang/whatever/admin/hardware/table.php does not contain a key for views.blade.php
![image](https://user-images.githubusercontent.com/58992990/139909534-60bd3e60-5234-41ca-9b29-0912e02fa6d8.png)

### Reproduction steps

1. open page on hardware view, left you  will see the header for current_value

### Expected behavior

Row title to show up 

### Screenshots

![image](https://user-images.githubusercontent.com/58992990/139909619-5447f004-62a0-41c1-b2d4-c65e81a192ee.png)

### Snipe-IT Version

5.3

### Operating System

debian

### Web Server

apache

### PHP Version

7.4.3

**Comment by steveelwood** [comment]
We're seeing the same thing in our environment.

v5.3.0 - build 6470 (master)
OS: Oracle Linux
Web: Apache
PHP: 7.2.34

**Comment by boring10** [comment]
This field appears to be for the depreciated value. We just noticed this today on one of our assets we added a depreciation to. 

Hosted version
v5.3.1 - build 6490 (master)

![Screenshot from 2021-11-11 06-56-33](https://user-images.githubusercontent.com/35600612/141294070-ef53a054-6a4a-44ef-99a8-20004edd5998.png)

**Comment by Solverz-0** [comment]
Same issue here since upgrading to 5.3.1

**Comment by nuraeil** [comment]
This issue was fixed with #10303 

But it is not yet released as as new version.
