### ISSUE TITLE
PDF export also exports actions, no way to remove

### ISSUE THREAD

**Issue by athompsoncmc** [grokability/snipe-it#10268]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When pressing "export data" and selecting "pdf", a table export is produced, and actions are visible on the table. It didn't do this pre version 5.3 I believe, and there is no way to remove them as you can't remove the column in the UI.

### Reproduction steps

1. Go to any menu with items
2. Click export data
3. Click pdf

### Expected behavior

The pdf export is not expected to export actions

### Screenshots

![image](https://user-images.githubusercontent.com/79665233/140320179-2c5d9edc-0168-4c32-80cd-0be59cfc5a05.png)

### Snipe-IT Version

5.3.1

### Operating System

Windows Server 2019 Standard

### Web Server

IIS

### PHP Version

7.4.13

### Operating System

Windows 10 Education N

### Browser

Google Chrome

### Version

95.0.4638.69

**Comment by snipe** [comment]
On what page are you seeing this?

**Comment by athompsoncmc** [comment]
Hi, thanks for your reply. This seems to happen on any page where the user can use the "export data" button (hardware, users, etc).
![image](https://user-images.githubusercontent.com/79665233/159348122-9b484be0-6c78-461f-8541-192137a33a60.png)
It creates a column with the "action" which didn't happen before, so I'm not sure if this change was intended. Especially with pdfs where it's not intended to be seen.

Example on an excel spreadsheet:
![image](https://user-images.githubusercontent.com/79665233/159348512-ac5cd5fa-df02-4764-89f2-bf57d9f2a80d.png)
Example on a pdf spreadsheet:
![image](https://user-images.githubusercontent.com/79665233/159348589-0b53414f-ead1-4a3a-b0b2-fea1261b727a.png)

**Comment by snipe** [comment]
So, we actually account for that, so the only thing I'm thinking is maybe the library we use changed something.

For example, in the licenses index blade, we have:

```html
 <table
              data-columns="{{ \App\Presenters\LicensePresenter::dataTableLayout() }}"
              data-cookie-id-table="licensesTable"
              data-pagination="true"
              data-search="true"
              data-side-pagination="server"
              data-show-columns="true"
              data-show-export="true"
              data-show-footer="true"
              data-show-refresh="true"
              data-sort-order="asc"
              data-sort-name="name"
              id="licensesTable"
              class="table table-striped snipe-table"
              data-url="{{ route('api.licenses.index') }}"
              data-export-options='{
            "fileName": "export-licenses-{{ date('Y-m-d') }}",
            "ignoreColumn": ["actions","image","change","checkbox","checkincheckout","icon"]
            }'>
          </table>
```

which *should* be 1) specifying the name of the file that gets generated and 2) tells the export which files to ignore. Neither of these seem to be respected anymore... 

https://bootstrap-table.com/docs/extensions/export/#exportoptions

🤔🧐

**Comment by uberbrady** [comment]
> So, we actually account for that, so the only thing I'm thinking is maybe the library we use changed something.
> 
> For example, in the licenses index blade, we have:
> 
> ```
>  <table
>               data-columns="{{ \App\Presenters\LicensePresenter::dataTableLayout() }}"
>               data-cookie-id-table="licensesTable"
>               data-pagination="true"
>               data-search="true"
>               data-side-pagination="server"
>               data-show-columns="true"
>               data-show-export="true"
>               data-show-footer="true"
>               data-show-refresh="true"
>               data-sort-order="asc"
>               data-sort-name="name"
>               id="licensesTable"
>               class="table table-striped snipe-table"
>               data-url="{{ route('api.licenses.index') }}"
>               data-export-options='{
>             "fileName": "export-licenses-{{ date('Y-m-d') }}",
>             "ignoreColumn": ["actions","image","change","checkbox","checkincheckout","icon"]
>             }'>
>           </table>
> ```
> 
> which _should_ be 1) specifying the name of the file that gets generated and 2) tells the export which files to ignore. Neither of these seem to be respected anymore...
> 
> https://bootstrap-table.com/docs/extensions/export/#exportoptions
> 
> 🤔🧐

I think I might have a theory here - remember that we *manually* create the bootstrapTable() using JS in the bootstrap partial blade. In that blade, when it's creating the table in javascript, it says this:

```js
            exportOptions: {
                htmlContent: true,
            },
```

Which means it's ignoring whatever we've set in the `data-export-options` attribute. We might be able to *query* the `data-exports-options` attribute and set `htmlContent: true` and then use that as the 'real' `exportOptions` - which gives us the best of both worlds.

If I'm correct, then that means that the download filename will always be something generic, *NOT* what we set in the `data-export-options` HTML attribute. And, lo and behold, I just exported a PDF and its name is: `tableExport.pdf`


<blockquote><div><strong><a href="https://bootstrap-table.com/docs/extensions/export/#exportoptions">Table Export · Bootstrap Table</a></strong></div><div>Table Export extension of Bootstrap Table.</div></blockquote>

**Comment by snipe** [comment]
Why would this suddenly *stop* working through. We've used those data attributes forever.

**Comment by uberbrady** [comment]
maybe related to when I yanked that initial `bootstrapTable('destroy')` bit? Or maybe BS table changed how it works to be more 'correct' - and we were relying on a bug or side-effect...

**Comment by snipe** [comment]
(And by "suddenly" I mean late last year)

I'd also like to make that landscape, but that's a different issue.

**Comment by uberbrady** [comment]
(and to your point - that bootstrapTable('destroy') bit is only used on Develop, not on Master :/ - so it's not that.)

**Comment by uberbrady** [comment]
Yup, it's definitely that. When I remove that set of attributes, the export has the appropriate name and skips the appropriate columns. Let me see if I can do a sorta merge thing here and squoosh the two together.

**Comment by snipe** [comment]
This is fixed on master
