### ISSUE TITLE
Make an Uploaded File a Device Image

### ISSUE THREAD

**Issue by craigj1222** [grokability/snipe-it#10271]
### Snipe-IT Version

5.2.0

### Operating System

Windows

### Web Server

Snipe-IT Hosted

### PHP Version

Snipe-IT Hosted

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

From the "Files" tab, I'm currently unable to select one of the existing images as a "Device Image."

### Describe the solution you'd like A clear and concise description of what you want to happen.

For applicable file types (.jpg, jpeg, .gif, etc.), create an action next to the filename in the "Files" tab to make one of those images the "Device Image."

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

These are two separate processes now, so you have to upload the device image separately from files.

### Additional context Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/93218692/140339586-f88ff8bc-8227-44f1-a9bb-5399cb95489c.png)

**Comment by snipe** [comment]
This does not really seem worth dev resources for. Just upload the file as a device image.

**Comment by craigj1222** [comment]
> This does not really seem worth dev resources for. Just upload the file as a device image.

Why would you not want to link two processes that are needlessly separated now?  You've got customers that are uploading images already through files since you can't upload more than one any other way (at least until the API file upload is done #9767) and they have to upload the same picture again?  A recent example besides us would be  #10229. 

I figured it would be a small dev effort to add a file action to link an existing image to the device image section.  If it's not worth your time, then it's not worth my money.

**Comment by snipe** [comment]
They are not needlessly separated. Uploaded files are private files and under permissions/auth control. The uploaded image is publicly browsable. They serve two different purposes. (Uploaded files can be license files, contract agreements, etc so it's important that they are protected, as they sometimes have confidential information in them.)

It would require us duplicating the image file into the public directory. If it should be the image file, just let it be the image file. 

> If it's not worth your time, then it's not worth my money.

Uh, okay? Instead of making assumptions about how easy something is, you could open a pull request or at least ask for more information as to why we feel this way. We don't make these judgements without reasons. When only two people are asking for something (versus lots and lots of people asking for many other things), you can see how we wouldn't make this a top priority.

If you are a customer, and you really don't think that that we're worth $40/month because of this one missing "feature", that would be a weird hill to die on given everything else we provide. If you're not a customer, then your money is irrelevant anyway.

**Comment by craigj1222** [comment]
> They are not needlessly separated. Uploaded files are private files and under permissions/auth control. The uploaded image is publicly browsable. They serve two different purposes. (Uploaded files can be license files, contract agreements, etc so it's important that they are protected, as they sometimes have confidential information in them.)
> 
> It would require us duplicating the image file into the public directory. If it should be the image file, just let it be the image file.
> 
> > If it's not worth your time, then it's not worth my money.
> 
> Uh, okay? Instead of making assumptions about how easy something is, you could open a pull request or at least ask for more information as to why we feel this way. We don't make these judgements without reasons.

I apologize for my tone, but if you had explained it that way in your initial response, I wouldn't have even pushed back. I'm a new hosted customer and new to Github in general, so I thought a feature request was the right way to ask.

**Comment by snipe** [comment]
@craigj1222 For hosted (and support) customers, the best avenue is sending a feature request to support@snipeitapp.com. It then gets added as a feature request in our internal systems and prioritized based on available time, number of people asking for it, whether it's a good fit, and potential negative impacts on testing and other users and customers. We deal with (literally) thousands of feature requests here, and unfortunately our free users are often not as nice as our customers, so it can get hard to get to everything here.

**Comment by craigj1222** [comment]
@snipe I appreciate that info.

I don't pretend to understand the workload you guys have (especially w/ open source + hosted) and have enjoyed the platform a lot so far.  Its filling a unique need for our business and the couple of questions I asked through ticketing have been answered immediately by Osei.  Again, I'm sorry for the tone in my initial response and I promise not to bombard you or the team w/ unnecessary feature requests.

**Comment by snipe** [comment]
I appreciate your understanding. Don't sweat it :) My apologies on sounding a bit distant and clinical, it's just a volume thing. I always do care about use-cases and pain points. They help form the product as it grows and they are invaluable. 

And welcome aboard :)
