### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by J1MP123** [grokability/snipe-it#10287]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Good morning you amazing people! After I could not resolve an issue with https://github.com/snipe/snipe-it/issues/10232 I decided to completely reinstall my raspberry pi and give it a go for the official installer.

This is the log from installer - https://pastebin.com/G5E48hAV (from start to finish)

Once I open http://raspberrypi it transfers to http://raspberrypi/setup but it gives me an HTTP error 500:

I'm now fully dedicating all my free time to get this software running because I'm a bit stubborn like this (close to 3 weeks now). 

Should I type anything else in this section? What is the FQDN of your server? (raspberry pi): I just want to run this software at home for training purposes. Maybe it's something with my Raspberry Pi?

Hope you can give me some advice, what am I missing now... it's probably one of the small annoying things i'm missing and I will be like DOHHH at the end.

### Reproduction steps

1. Reinstalled My pi 3B+
2. Run script from snipe it website
3. https://pastebin.com/G5E48hAV (full log)
...

### Expected behavior

Easy installation..

### Screenshots

![errpr](https://user-images.githubusercontent.com/93220034/140915190-415145f8-5e9f-4eff-bfd3-ee64567ee5c3.jpg)

### Snipe-IT Version

latest

### Operating System

Raspbian GNU/Linux 10 (buster) (debian base)

### Web Server

Apache/2.4.38 (Raspbian)

### PHP Version

7.3.29-1~deb10u1

**Comment by J1MP123** [comment]
`[Tue Nov 09 11:11:03.311820 2021] [php7:error] [pid 22451] [client 172.16.0.108:51838] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 133, Array)\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/var/www/html/s...', '9999999999N;', 2)\n#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/var/www/html/s...', '9999999999N;', true)\n#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put('snipeit_app_set...', NULL, 0)\n#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\F in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133
[Tue Nov 09 11:11:03.324234 2021] [php7:error] [pid 22451] [client 172.16.0.108:51838] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 133, Array)\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/var/www/html/s...', '9999999999N;', 2)\n#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/var/www/html/s...', '9999999999N;', true)\n#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put('snipeit_app_set...', NULL, 0)\n#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\F in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133
[Tue Nov 09 14:40:01.144422 2021] [php7:error] [pid 22450] [client 172.16.0.108:51932] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 133, Array)\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/var/www/html/s...', '9999999999N;', 2)\n#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/var/www/html/s...', '9999999999N;', true)\n#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put('snipeit_app_set...', NULL, 0)\n#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\F in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133
[Tue Nov 09 14:40:01.156542 2021] [php7:error] [pid 22450] [client 172.16.0.108:51932] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 133, Array)\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/var/www/html/s...', '9999999999N;', 2)\n#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/var/www/html/s...', '9999999999N;', true)\n#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put('snipeit_app_set...', NULL, 0)\n#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\F in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133
[Tue Nov 09 20:42:15.865579 2021] [php7:error] [pid 22453] [client 172.16.0.108:63077] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 133, Array)\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/var/www/html/s...', '9999999999N;', 2)\n#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/var/www/html/s...', '9999999999N;', true)\n#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put('snipeit_app_set...', NULL, 0)\n#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\F in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133
[Tue Nov 09 20:42:15.872894 2021] [php7:error] [pid 22453] [client 172.16.0.108:63077] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 133, Array)\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/var/www/html/s...', '9999999999N;', 2)\n#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/var/www/html/s...', '9999999999N;', true)\n#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put('snipeit_app_set...', NULL, 0)\n#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\F in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133
` var/log/apache2/error.log

**Comment by TechBreakHelp** [comment]
> failed to open stream: Permission denied in 

[Check for permission](https://snipe-it.readme.io/docs/configuration#required-set-directory-permissions). Remind that your apache server could use a different user, in most cases it uses `www-data`. Check /var/www/html/snipeit/vendor, and its subfolders, permissions and owner using `cd /var/www/html/snipeit/vendor` and then launch `ll`

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
