### ISSUE TITLE
Accessories endpoints 404

### ISSUE THREAD

**Issue by RyanMayo** [grokability/snipe-it#10294]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In our local installation of SnipeIT v v5.1.8 build 6227

attempting to check in an item (that I know is there & have manually checked in/out using the web interface):
```
// endpoint /api/v1/accessories/1/checkin returns:

{
    "status": "error",
    "messages": "The accessory [:id] does not exist.",
    "payload": null
}
```

### Reproduction steps

1. send GET req to `/api/v1/accessories/1` 
2. receive `{ "id": 1,  ...rest-of-data }`
3. send POST req to `endpoint /api/v1/accessories/1/checkin`
4. receive `{
    "status": "error",
    "messages": "The accessory [:id] does not exist.",
    "payload": null
}`

### Expected behavior

I don't know because the reference accessories endpoints are broken too.

When attempting to test api usage via the reference page (https://snipe-it.readme.io/reference/accessories) no matter which 'accessories' endpoint I test, I always get a "404 endpoint not found."

### Screenshots

![example1](https://user-images.githubusercontent.com/13143004/141181570-9441a406-ea05-46b7-b6a6-65934da07f19.JPG)

### Snipe-IT Version

v5.1.8 build 6227

### Operating System

CentOS Linux

### Web Server

Apache

### PHP Version

7.4.2

### Operating System

Windows

### Browser

Chrome

### Version

95.0.4638.69 

### Additional context

I don't have installation/maintenance info for the installation, I'm just attempting to reach the api

**Comment by snipe** [comment]
That's not a 404, that's a 200 saying the accessory doesn't exist. 

Per the docs, the ID number you need to pass is the ID of the *relationship*

"This is the ID of the accessory+user relationships in the accessories_users table"

**Comment by RyanMayo** [comment]
Thanks!  

Also: where in the api would I find the accessories_users table id?  I checked GET /accessories, GET /accessories/1, and GET /users/1/accessories & am not seeing anything like that.

I DID notice this in the object returned by GET /accessories/1 
`"available_actions": {
        "checkout": true,
        "checkin": false,
        "update": true,
        "delete": true
      },`  seems to imply that I can't check this item in?   is this a problem &/or something that can be changed in admin controls?

**Comment by RyanMayo** [comment]
Follow up:  I found out that endpoint /api/v1/accessories/1/checkedout exposes the accessory/user relationship id as key "assigned_pivot_id".  as far as I can tell this is the only place it is exposed at, so I think I can work w/ this.

it would be more ideal if this was also exposed at endpoint /api/v1/users/412/accessories, but here we are.

Thank you @snipe for helping me out w/ this.
