### ISSUE TITLE
Default Values do not allow Checkbox/Radio Buttons

### ISSUE THREAD

**Issue by ShaunNeighbourSwale** [grokability/snipe-it#10299]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Default Values do not allow Checkbox/Radio Buttons

![image](https://user-images.githubusercontent.com/51878759/141289883-14198954-ef7c-4ec7-bb27-7fe8cc2d1861.png)

### Reproduction steps

1. Create field with Form Element of either Checkbox or Radio Buttons
2. Add to fieldset
3. Create new asset model
4. Attempt to populate default values
...

### Expected behavior

To be able to pre-populate default values.

### Screenshots

![image](https://user-images.githubusercontent.com/51878759/141290196-dcd55251-4477-4bfa-b70b-dfcd1e3201b7.png)

### Snipe-IT Version

5.3.1

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

Latest as of Tuesday........

### Operating System

Windows

### Browser

Google Chrome

### Version

95.0.4638.69

**Comment by austin-robertazza** [comment]
Also experiencing this behavior in latest build. Would really like to be able to set defaults for some of our asset models with these data types. Being forced to use text boxes now, which introduces user error when filling out assets.

**Comment by snipe** [comment]
@inietov can you take a stab at this when you get a moment?
