### ISSUE TITLE
Change /Users endpoint to show deleted users with "deleted_at" field.

### ISSUE THREAD

**Issue by Midnex** [grokability/snipe-it#10290]
### Snipe-IT Version

5.1.8

### Operating System

PopOS!

### Web Server

Apache

### PHP Version

7.4.16

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

No

### Describe the solution you'd like A clear and concise description of what you want to happen.

/User endpoints return all users except deleted users,There is a date flag used to filter these "deleted_at", but never returns with a value if a user has been deleted.

I would like to use the /Users endpoint return all users, so we may filter by "deleted_at" if we need only active users.

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Alternative would be to add an endpoint for deleted users, but I feel that having to merry this with /Users endpoint would be annoying, and more work than just filtering by "deleted_at" being Null.

### Additional context Add any other context or screenshots about the feature request here.

Not sure if assets work the same way, but this could be extended to them as well.

**Comment by snipe** [comment]
You can use `/api/v1/users?deleted=true` for only deleted users, same as the web UI uses

**Comment by snipe** [comment]
(Or use `/api/v1/users?all=true` for all, including deleted)

**Comment by Midnex** [comment]
Thanks, I did not know about that option.

**Comment by snipe** [comment]
It's [in the API documentation](https://snipe-it.readme.io/reference/users), all the way at the bottom of the available options.

<img width="585" alt="Screen Shot 2021-11-10 at 4 04 49 PM" src="https://user-images.githubusercontent.com/197404/141213117-305131d8-751a-443a-bef9-2a24bf7eff02.png">
