### ISSUE TITLE
SAML not working with Google Workspace

### ISSUE THREAD

**Issue by localzuk** [grokability/snipe-it#10307]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

SAML auth is not working. Whichever method I try to sign in via SAML (IdP initiated or by clicking the Login with SAML link) I receive the error:

`There was a problem while trying to log you in, please try again.`

### Reproduction steps

1. Set up a SAML app in Google Workspace, download metadata file
2. Upload metadata file into Snipe-IT
3. Enter Entity ID, ACS and SLS URLs into Google SAML app
4. Enable the SAML app for the relevant users
5. Ensure users are already in Snipe-IT (in my case, synced via LDAP)
6. Try to log in to Snipe-IT with SAML - either via the waffle in Google or via the Login via SAML link on the Snipe-IT login form
7. Receive the error "There was a problem while trying to log you in, please try again."
...

### Expected behavior

Should authenticate the user and log them in to Snipe-IT

### Screenshots

![image](https://user-images.githubusercontent.com/998988/141446256-a61b3487-927f-4e59-8c5b-020a5ac8abc9.png)

### Snipe-IT Version

5.3.1

### Operating System

Debian

### Web Server

Apache2

### PHP Version

7.3.31

### Error messages

```shell
[2021-11-11 16:04:09] production.ERROR: SAML Response not found, Only supported HTTP_POST Binding {"exception":"[object] (OneLogin\\Saml2\\Error(code: 8): SAML Response not found, Only supported HTTP_POST Binding at /var/www/snipe-it/vendor/onelogin/php-saml/src/Saml2/Auth.php:257)
[stacktrace]
#0 /var/www/snipe-it/app/Http/Controllers/Auth/SamlController.php(100): OneLogin\\Saml2\\Auth->processResponse()
#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Auth\\SamlController->acs(Object(Illuminate\\Http\\Request))
#2 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('acs', Array)
#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\SamlController), 'acs')
#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#5 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#6 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 /var/www/snipe-it/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#11 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#12 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#13 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#14 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#15 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/snipe-it/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\PreventBackHistory->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/snipe-it/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\SecurityHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/snipe-it/app/Http/Middleware/CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForDebug->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/snipe-it/app/Http/Middleware/CheckForSetup.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForSetup->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/snipe-it/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/snipe-it/app/Http/Middleware/NoSessionStore.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\NoSessionStore->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/snipe-it/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#42 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#43 /var/www/snipe-it/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#44 {main}
```

**Comment by uberbrady** [comment]
It generally "just works" for most SAML providers - but we've definitely seen some complications when running against Shibboleth. Thank you for the error messages, those are usually pretty damning, although not so much in this case :(

**Comment by localzuk** [comment]
Are there any other debugging tools I can use to gather more data? Very aware that a single stack trace isn't much to go on, so would like to be able to gather more info.

In the meantime, I'm going to read up on SAML, fire up a dev environment and see what I can find.

**Comment by localzuk** [comment]
OK, so I have now switched to AzureAD... The instructions in the documentation are a little sparse to say the least.

However, I have got it all set up, and can see a SAMLResponse from Azure in Chrome -> F12 -> Network. It shows it auth'd OK, everything looks fine. No errors in laravel.log. But I still see "There was a problem while trying to log you in, please try again." on the login page. I can see in the claims username is showing the right thing as well, having trimmed the domain part off the upn.

So I'm now at a total loss.

**Comment by uberbrady** [comment]
If username is showing the right thing - and that user exists in your Snipe-IT installation - it _should_ log you in if all of the appropriate certificates check out. You might get more verbose debugging information if you set `APP_DEBUG=true` in your `.env` file - but only if your installation is *not* available to the public - that debugging mode **can** disclose private information you might not want disclosed. You can also try setting `APP_LOG_LEVEL=debug` in your `.env` which is a little safer and more verbose.

Generally the biggest problem with SAML happens when people don't create a Snipe-IT user that corresponds to the user who is logging in via SAML. If there's no user, there's no one to log in 'to'. Either that, or they don't have the usernames lined up - e.g. the users in their Snipe-IT instance have usernames of just 'username' but SAML is trying to log in users as 'username@domain' - and those won't match.

**Comment by localzuk** [comment]
Thanks @uberbrady, however we have APP_DEBUG=true enabled already.

We also definitely have the username we're testing pre-populated in Snipe-IT (brought in via LDAP sync, and can log in with username/password just fine).

With the SAMLResponse - it is returning "NameID" in email form, but then there is an Attribute/Claim with name "Username" with AttributeValue which matches the username. To test, I have changed the username field in LDAP to mail instead of samaccountname. Which has got it all working. However, ideally I'd like it to be just the username, not the email. Is there a way to get Snipe-IT to use the mentioned Username field instead of the NameId?

**Comment by localzuk** [comment]
OK, so even though I didn't managed to get this working with Google, I have it working exactly as I want now with Azure AD (which I have set up as an OAuth client of our Google setup anyway, so end result is the same).

I think a couple of things need adding to the documentation.

First, the "Sign on URL" is now mandatory in Azure, and this is just your host for Snipe-IT. In my case this is the same as the Entity-ID.

Second, there needs to be a reminder to add allowed users to the SAML app in Azure AD to allow sign in.

Finally, in Snipe-IT, for clarity's sake, the "Attribute Mapping - Username" field needs to be set to "Username" if you don't use full email addresses as usernames (this bit isn't very clear on the documentation at the moment).

**Comment by uberbrady** [comment]
I'm glad you got it working! Our documentation has a "suggest changes" feature - could you put in your suggested changes their and then I can go accept them?

**Comment by localzuk** [comment]
Sure, will do.

**Comment by localzuk** [comment]
Suggested edits made.

I'm going to take a look at the Google side of things this weekend, see if I can get it working in my dev environment.

**Comment by maltestarostik-mobimeo** [comment]
Unfortunately, Google doesn't provide a Username attribute or anything that can be configured to the same effect.
Would be great if Snipe-IT had an option to strip the domain off the SAML provided NameID as this is a common case.
We don't like to go with username = email address in Snipe-IT as we get the plain names from LDAP and also the CSV import generates such names.

**Comment by uberbrady** [comment]
Yeah, Google seems to really insist on its NameId's being full email addresses, and while it has a very nice "additional attributes" picker, none of those attributes look like 'short usernames' (which, if memory serves, is 'uid' in Google-land).

What we've usually seen in Google scenarios (we use this ourselves, in fact), is to set `mail` as the "Username Field" - then Google SSO works just fine.

Of course, that doesn't help with your already existing users - but there's an artisan command to merge them over from the shortname-username-ones to the email-address-looking-ones - `php artisan snipeit:merge-users`.
