### ISSUE TITLE
CLI Importer requires "Serial" instead of the documented "Serial Number"

### ISSUE THREAD

**Issue by localzuk** [grokability/snipe-it#10301]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When importing a csv file of assets from the CLI, if you use the heading as documented [here](https://snipe-it.readme.io/docs/importing), it won't import the serial numbers.

Changing to just "Serial" fixes the issue.

This has been reported before, several years ago but nothing was done about it and the issue was closed as stale.

https://github.com/snipe/snipe-it/issues/5108

### Reproduction steps

1. Create csv file per the specs in the documentation
2. Import it using the CLI importer
3. Look at the serial numbers on the app.
...

### Expected behavior

Should import the serial numbers

### Snipe-IT Version

5.3.1

### Operating System

Debian

### Web Server

Apache2

### PHP Version

7.3.31

**Comment by Solverz-0** [comment]
The documentation is incorrect. The documentation states the field should be "Serial Numbers" when it fact it should be "Serial" using the CLI importer anyway, have not tested using the Web GUI importer.

**Comment by localzuk** [comment]
This has been closed, but the sample assets csv downloadable from the documentation still has the wrong column heading? It still says Serial number, not just serial.
