### ISSUE TITLE
localization issues

### ISSUE THREAD

**Issue by geor444** [grokability/snipe-it#10314]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have set the Russian localization in the settings as shown in the photo, but the site is still in English.
How do I localize it to my language ?

### Reproduction steps

1.
2.
3.
...

### Expected behavior

-

### Screenshots

![image](https://user-images.githubusercontent.com/67157811/141797454-214336eb-8d70-495b-b95c-bce797789e15.png)

### Snipe-IT Version

5.3.1

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8

### Operating System

Ubuntu

**Comment by nuraeil** [comment]
Some strings are not yet in the localization format. 

I had opened an issue for this for the German language (#10242) and briefly discussed it with Snipe over Discord.

I am currently working on putting the English strings into the localizable format with my PR #10264

This PR is against the development branch, targeting version 6.

It just takes a lot of time to go through all the files and find those strings.

**Comment by geor444** [comment]
> Некоторые строки еще не в формате локализации.
> 
> Я открыл для этого проблему для немецкого языка ( [# 10242](https://github.com/snipe/snipe-it/issues/10242) ) и кратко обсудил ее с Snipe через Discord.
> 
> В настоящее время я работаю над переводом английских строк в локализуемый формат с моим PR [# 10264.](https://github.com/snipe/snipe-it/pull/10264)
> 
> Этот PR направлен против ветки разработки, ориентированной на версию 6.
> 
> Просто нужно много времени, чтобы просмотреть все файлы и найти эти строки.

So if I install Russian localization, it won't work?

**Comment by nuraeil** [comment]
> > Некоторые строки еще не в формате локализации.
> > Я открыл для этого проблему для немецкого языка ( [# 10242](https://github.com/snipe/snipe-it/issues/10242) ) и кратко обсудил ее с Snipe через Discord.
> > В настоящее время я работаю над переводом английских строк в локализуемый формат с моим PR [# 10264.](https://github.com/snipe/snipe-it/pull/10264)
> > Этот PR направлен против ветки разработки, ориентированной на версию 6.
> > Просто нужно много времени, чтобы просмотреть все файлы и найти эти строки.
> 
> So if I install Russian localization, it won't work?

Some strings will not be in Russian and some will. The page you are showing above has no translation strings in place.

This is a snippet of the localization.blade.php:

```php
{{-- Page title --}}
@section('title')
    Update Localization Settings
    @parent
@stop
```

The Update Localization Settings has to be replaced with the correct reference to the key inside the language folder, which also has to be created.

This is what the PR is for and after the PR is merged and v6 is released, those translation strings can be translated into the specific language through the Crowdin platform.

I hope that I was able to clear that up.

In general, the selected language will work but some strings might not be translated as they are hard-coded into the source code in English.

**Comment by geor444** [comment]
> > > Некоторые строки еще не в формате локализации. 
> > > Я открыл для этого проблему для немецкого языка ( [# 10242](https://github.com/snipe/snipe-it/issues/10242) ) и кратко обсудил ее с Снайпом через Discord. 
> > > В настоящее время я работаю над переводом английских строк в локализуемый формат с моим PR [# 10264.](https://github.com/snipe/snipe-it/pull/10264) 
> > > Этот PR направлен против ветки разработки, ориентированной на версию 6. 
> > > Просто нужно много времени, чтобы просмотреть все файлы и найти эти строки.
> > 
> > 
> > Значит, если я поставлю русскую локализацию, не получится?
> 
> Некоторые строки не будут на русском языке, а некоторые будут. На странице, которую вы показываете выше, нет строк перевода.
> 
> Это фрагмент файла localization.blade.php:
> 
> ```
> {{- Заголовок страницы -}}
> @ section ( 'title' )
>      Обновить  настройки локализации 
>     @parent
> @останавливаться
> ```
> 
> Обновить параметры локализации необходимо заменить правильной ссылкой на ключ внутри языковой папки, которую также необходимо создать.
> 
> Это то, для чего нужен PR, и после того, как PR объединен и выпущен v6, эти строки перевода могут быть переведены на конкретный язык через платформу Crowdin.
> 
> Я надеюсь, что мне удалось это прояснить.
> 
> Как правило, выбранный язык будет работать, но некоторые строки могут не быть переведены, поскольку они жестко закодированы в исходном коде на английском языке.

Is there any documentation on how to do this

**Comment by nuraeil** [comment]
> > > > Некоторые строки еще не в формате локализации.
> > > > Я открыл для этого проблему для немецкого языка ( [# 10242](https://github.com/snipe/snipe-it/issues/10242) ) и кратко обсудил ее с Снайпом через Discord.
> > > > В настоящее время я работаю над переводом английских строк в локализуемый формат с моим PR [# 10264.](https://github.com/snipe/snipe-it/pull/10264)
> > > > Этот PR направлен против ветки разработки, ориентированной на версию 6.
> > > > Просто нужно много времени, чтобы просмотреть все файлы и найти эти строки.
> > > 
> > > 
> > > Значит, если я поставлю русскую локализацию, не получится?
> > 
> > 
> > Некоторые строки не будут на русском языке, а некоторые будут. На странице, которую вы показываете выше, нет строк перевода.
> > Это фрагмент файла localization.blade.php:
> > ```
> > {{- Заголовок страницы -}}
> > @ section ( 'title' )
> >      Обновить  настройки локализации 
> >     @parent
> > @останавливаться
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Обновить параметры локализации необходимо заменить правильной ссылкой на ключ внутри языковой папки, которую также необходимо создать.
> > Это то, для чего нужен PR, и после того, как PR объединен и выпущен v6, эти строки перевода могут быть переведены на конкретный язык через платформу Crowdin.
> > Я надеюсь, что мне удалось это прояснить.
> > Как правило, выбранный язык будет работать, но некоторые строки могут не быть переведены, поскольку они жестко закодированы в исходном коде на английском языке.
> 
> Is there any documentation on how to do this

Documentation for what exactly? Translating those strings?  That is documented here: https://snipe-it.readme.io/docs/translations

Or do you the programmatical style of localization that I mentioned above?

Example:

```php
{{-- Page title --}}
@section('title')
    Update Localization Settings
    @parent
@stop
´´´




<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/translations">Translations</a></strong></div><div>Traduci! 翻訳！Oversette! Traduire! 번역하기! แปล! ¡Traducir! Przetłumacz! Übersetzen!</div></blockquote>
