### ISSUE TITLE
User without Delete permission can still bulk delete asset models

### ISSUE THREAD

**Issue by ccj9874** [grokability/snipe-it#10321]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

A user on my instance of SnipeIT is able to bulk delete Asset Models despite not being given permission to delete Asset Models. I checked the permissions of the group they are in, as well as the individual permissions of the user and both had Deny on the option to delete Asset Models. However, I am able to successfully delete Asset Models using the Bulk Delete option despite not having permission to delete them.

### Reproduction steps

1. Select x number of asset models
2. Select Bulk Delete
3. Click Go
4. Delete

### Expected behavior

The user should not be able to delete Asset Models using any methods.

### Snipe-IT Version

v5.3.0 - build 6470

### Operating System

Debian 10

### Web Server

Apache

### PHP Version

7.4

### Operating System

Windows 10

### Browser

Brave (Chromium)

### Version

Chromium 95

### Additional context

Installed with install.sh
The installation has been working great for a few weeks but I just noticed this today.

**Comment by snipe** [comment]
I believe this has been fixed in later versions of Snipe-IT.
