### ISSUE TITLE
New user can't login

### ISSUE THREAD

**Issue by TL-Arwen** [grokability/snipe-it#10332]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have my server setup with ldap sync. Had a user login. It creates a user, but still can't login. Edit the user, select Login enabled, save it. Have the user login. Fails. Check the setting, and the check box disappears. Looked through issues 1721 and 6480. Neither of these helped me fix the issue. Seems like it's only one user so far.

### Reproduction steps

1.Logging in using domain user and password

### Expected behavior

Should log in. 

### Snipe-IT Version

5.3.1

### Operating System

docker on ubuntu

### Web Server

apache 

### PHP Version

7.4.3

**Comment by TL-Arwen** [comment]
Posting logs. Looks like it's  changing the status of the user at login

10.28.0.251 - - [19/Nov/2021:18:45:23 +0000] "GET /users/4 HTTP/1.1" 200 29076 "http://assets.molienergy.com:8082/users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
10.28.0.251 - - [19/Nov/2021:18:45:24 +0000] "GET /api/v1/hardware?assigned_to=4&assigned_type=App%5CModels%5CUser&search=&sort=name&order=asc&offset=0&limit=20 HTTP/1.1" 200 1139 "http://assets.molienergy.com:8082/users/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
10.28.0.251 - - [19/Nov/2021:18:45:24 +0000] "GET /api/v1/reports/activity?target_id=4&target_type=user&search=&order=desc&offset=0&limit=20 HTTP/1.1" 200 1153 "http://assets.molienergy.com:8082/users/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
10.28.0.251 - - [19/Nov/2021:18:45:27 +0000] "GET /users/4/edit HTTP/1.1" 200 31873 "http://assets.molienergy.com:8082/users/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
10.28.0.251 - - [19/Nov/2021:18:45:27 +0000] "GET /css/dist/blue.png HTTP/1.1" 304 180 "http://assets.molienergy.com:8082/css/dist/all.css?id=d428302ff341ffec8b1b" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
10.28.0.251 - - [19/Nov/2021:18:45:31 +0000] "POST /users/4 HTTP/1.1" 302 1999 "http://assets.molienergy.com:8082/users/4/edit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
10.28.0.251 - - [19/Nov/2021:18:45:31 +0000] "GET /users HTTP/1.1" 200 25984 "http://assets.molienergy.com:8082/users/4/edit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
10.28.0.251 - - [19/Nov/2021:18:45:32 +0000] "GET /api/v1/users?deleted=false&company_id=&search=&order=asc&offset=0&limit=200 HTTP/1.1" 200 94120 "http://assets.molienergy.com:8082/users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
10.28.0.252 - - [19/Nov/2021:18:46:08 +0000] "GET / HTTP/1.1" 302 2008 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53"
10.28.0.252 - - [19/Nov/2021:18:46:08 +0000] "GET /login HTTP/1.1" 200 2865 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53"
10.28.0.252 - - [19/Nov/2021:18:46:08 +0000] "GET /css/dist/all.css?id=d428302ff341ffec8b1b HTTP/1.1" 200 65614 "http://assets.molienergy.com:8082/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53"
10.28.0.252 - - [19/Nov/2021:18:46:08 +0000] "GET /js/dist/all.js?id=5999105216485cd776ad HTTP/1.1" 200 318535 "http://assets.molienergy.com:8082/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53"
10.28.0.252 - - [19/Nov/2021:18:46:08 +0000] "GET /css/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 182 "http://assets.molienergy.com:8082/css/dist/all.css?id=d428302ff341ffec8b1b" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53"
10.28.0.252 - - [19/Nov/2021:18:46:08 +0000] "GET /css/dist/blue.png HTTP/1.1" 304 180 "http://assets.molienergy.com:8082/css/dist/all.css?id=d428302ff341ffec8b1b" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53"
10.28.0.252 - - [19/Nov/2021:18:46:16 +0000] "POST /login HTTP/1.1" 302 2002 "http://assets.molienergy.com:8082/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53"
10.28.0.252 - - [19/Nov/2021:18:46:16 +0000] "GET /login HTTP/1.1" 200 2990 "http://assets.molienergy.com:8082/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53"
10.28.0.251 - - [19/Nov/2021:18:46:23 +0000] "-" 408 0 "-" "-"

**Comment by snipe** [comment]
Are you still having this issue? Anything in your app logs that might shed some light?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
