### ISSUE TITLE
Exporting "MS-Excel-files" does not work properly on macOS

### ISSUE THREAD

**Issue by niklasskoldmark** [grokability/snipe-it#10331]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When opening the exported file I get the message:
"""
The file format and extension of ’tableExport.xls’ don’t match.
The file could be corrupted or unsafe.
Unless you trust its source, don’t open it.
Do you want to open it anyway?
[Yes | No]
"""
When editing and trying to save the file, Excel wants to save it as a "Web Page" (.htm)

### Reproduction steps

1. Click Assets/All Deployed
2. Click on the "Export" dropdown and select "MS-Excel"
3. Double click the downloaded file

### Expected behavior

The same behavior as when I open other Excel files

### Screenshots

![Screenshot 2021-11-18 at 22 00 20](https://user-images.githubusercontent.com/1642592/142498412-476a6f54-a54f-451c-981d-e96c17491a08.png)

### Snipe-IT Version

v5.3.2 - build 6508 (master)

### Operating System

Unknown (Hosted by Snipe-IT)

### Web Server

Unknown (Hosted by Snipe-IT)

### PHP Version

7.3.23

### Operating System

macOS Monterey 12.0.1 (21A559)

### Browser

Safari

### Version

15.1 (17612.2.9.1.20)

### Error messages

```shell
I can not turn on debug mode since the tenant is hosted by Snipe-IT
The error is reproducible on the demo (https://demo.snipeitapp.com/hardware?status=Deployed)
```

### Additional context

I currently run "Microsoft® Excel for Mac Version 16.55 (21111400)" (the latest version), but it is like this on older versions of Excel and macOS as well, I've had my colleagues test it on their systems.

**Comment by uberbrady** [comment]
I was just able to replicate this. I should note that I was able to open the file and displayed correctly once I clicked 'yes' to open the file anyway. Since this XLS file is generated by a third-party package, I'm not sure how we'd go about fixing it. But I can definitely replicate it.

**Comment by uberbrady** [comment]
I figured since the '.xls' file is just a bunch of XML, that renaming it to '.xlsx' might work - but that just made it worse; then Excel flat-out refused to open the file at all.

**Comment by KeenRivals** [comment]
This behavior is something I've seen in a few "export to excel" things. It's taking the table's html and dumping it with an .xls extension. I'm guessing for legacy reasons, Excel accepts this but complains about it. If you rename that "xls" to html you can open it up in your browser. If you try that with a real XLS file you get binary data. To get rid of the warning you might have to find something that dumps a true Excel file.

The CSV export via this screen is a little weird too. It includes a lot of html.

**Comment by sylvank** [comment]
For anyone looking up this error: this was apparently known, and the modern Excel (Open XML) XLSX export appears to address it. https://github.com/grokability/snipe-it/issues/11378
