### ISSUE TITLE
Error: ldap_search(): Partial search results returned: Sizelimit exceeded

### ISSUE THREAD

**Issue by sen-IT** [grokability/snipe-it#10341]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to do an LDAP sync, I'm getting below error:
"Error: ldap_search(): Partial search results returned: Sizelimit exceeded"

This is a new install on ubuntu 20.04.3 server LAMP stack, with MySQL. Is 1000 users is the maximum limit on LDAP sync? I tried changing the Base Bind DN in LDAP Settings to a smaller OU and it seems to be working fine, but we actually have more than 1000 users that need to be synced.  Tried adding multiple locations for smaller OUs with smaller number of users (under 1000) and tried syncing the locations via 'People' menu, still comes up with same error.

Tried changing the IMPORT_MEMORY_LIMIT in .env to 3000M from 500M and still doesn't seems to be fixing it.

Thanks

### Reproduction steps

1. LDAP sync 'People' menu by choosing location
2.
3.
...

### Expected behavior

Sync users from specified OU mention in the 'Location' 

### Screenshots

![image](https://user-images.githubusercontent.com/94816445/142797216-40101c91-f7e1-45da-985e-eb68474af229.png)

### Snipe-IT Version

v5.3.2

### Operating System

Ubuntu 20.04.3 server

### Web Server

Apache

### PHP Version

7.4.3

### Additional context

Fresh install

**Comment by localzuk** [comment]
The limit is set by your LDAP server - you'll need to look at documentation for your particular LDAP server to adjust it. For example, Active Directory's MaxPageSize policy setting - https://docs.microsoft.com/en-US/troubleshoot/windows-server/identity/domain-controller-returns-500-values-ldap-response

<blockquote><img src="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" width="48" align="right"><div><strong><a href="https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/domain-controller-returns-500-values-ldap-response">DC returns only 5000 values in LDAP response - Windows Server</a></strong></div><div>Provides a solution to an issue where the Windows Server 2008 R2 or newer domain controller only returns 5000 values for an LDAP response.</div></blockquote>

**Comment by sen-IT** [comment]
Thanks Tony, I've updated the MaxPageSize policy to 5000. We only have 2289 objects under the OU/sub OUs in base bind DN. I'm still getting the same error unfortunately. Is there any where else to check?
Thanks

**Comment by ParadoxGuitarist** [comment]
I know this might be a bit stale, but I ran into this on the web interface as well. 

For v.6.0.5 the variable for the memory is `LDAP_MEM_LIM` 

I noticed that I wasn't getting the same `Error: ldap_search(): Partial search results returned: Sizelimit exceeded` while running the ldap sync from the artisan on the cli, which led me to the right ENV for setting the memory limit. 

After setting that ENV to a higher value, I stopped getting the error on the web front end. 

Not sure if y'all want to leave this open to fix the front end error message to better match the underlying issue, or just mark it resolved. 

Thanks for all you do!

**Comment by uberbrady** [comment]
I'm _used_ to seeing the `Sizelimit exceeded` message when there's some kind of LDAP-paging problem. Snipe-IT uses standard LDAP paging to iterate through LDAP server results, grabbing 500 entries at a time. We've seen people sync 30,000 or more users this way. Some directory servers might not want to do that paging, though? AD usually does it fine, but some of the major directory service providers actually won't do paging until you explicitly enable it by talking to their support. Most just do regular paging just fine, though.

I've definitely seen problems with the memory limit before, but that usually says something about "Cannot allocate xyz bytes" and then it crashes :(

**Comment by ParadoxGuitarist** [comment]
Yep, I got the `Cannot allocate xyz bytes`  while running `php artisan snipeit:ldap-sync --location_id=1` which lead me down the path to finding the correct ENV. I after setting it, I stopped getting `Error: ldap_search(): Partial search results returned: Sizelimit exceeded` on the frontend. Just imported 52,000 accounts. 

Technically the memory size limit was exceeded so it only had partial results and failed, so in that sense, the error still kinda makes sense. :)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by mranonyms022** [comment]
I am getting the same issue and I have  tried everything that is suggested above.
