### ISSUE TITLE
all created fields and columns are not showing in the user login dashboard 

### ISSUE THREAD

**Issue by dastagir-ali** [grokability/snipe-it#10340]
### Snipe-IT Version

v5.1.6 build 6109 

### Operating System

ubuntu 20.04

### Web Server

NA

### PHP Version

7.2.24-0ubuntu0.18.04.7

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

In admin login I am able to see all the fields in the columns in assigned list main page. but user login  Only few columns are showing main page. Please help on this

### Describe the solution you'd like A clear and concise description of what you want to happen.

how to set that user permission for vies all assigned assets with all fields what we created

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.
![image](https://user-images.githubusercontent.com/94737491/142720076-4d1ec888-fdeb-44ce-934c-84fdff504476.png)

_No response_

**Comment by ccj9874** [comment]
You probably have to change the permissions for the user(s) to View for the Custom Fields category
