### ISSUE TITLE
API error "Unauthorized or unauthenticated."

### ISSUE THREAD

**Issue by Isotop7** [grokability/snipe-it#10351]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm trying to query the API of our Snipe-IT instance for several days now but I cant get it to work.
My user has admin permissions and I created a token.
When I try to query the API via curl or powershell, I always get `{"error":"Unauthorized or unauthenticated."}`.

I already decreased to API lifetime to 2 years as mentioned in other posts. I also get no errors in the php or apache log.

### Reproduction steps

1. Create a user with admin permissions
2. Create a token
3. Try to query api endpoint

### Expected behavior

Get returned values of API call

### Snipe-IT Version

5.3.1

### Operating System

Ubuntu Server 20.04

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows 11

### Error messages

```shell
$ php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by xam-ps** [comment]
Did you try to get the api working with postman as described here?
https://snipe-it.readme.io/reference/testing-in-postman

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/testing-in-postman">Testing in Postman</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>

**Comment by snipe** [comment]
Please post the curl command

**Comment by MascHman** [comment]
Hey, I've found a solution which to my knowledge is not mentioned in any thread:

I had the same Issues, then upgraded to latest release, merged all changes from .env.example to my (3 years old) .env file and lowered the API_TOKEN_EXPIRATION_YEARS . Still nothing. After checking all dependencies there was only one thing left: The Apache Config. It seems I was preventing the loading of internal .htaccess file by using the alternate apache config provided in the install docs [https://snipe-it.readme.io/docs/linuxosx].

So going back to the default apache config was my fix:
```
<VirtualHost *:80>
    <Directory /var/www/html/public>
        Allow From All
        AllowOverride All
        Options -Indexes
    </Directory>

    DocumentRoot /var/www/html/public
    ServerName www.yourserver.com
    # Other directives here
</VirtualHost>
```

**Comment by Isotop7** [comment]
> Hey, I've found a solution which to my knowledge is not mentioned in any thread:
> 
> I had the same Issues, then upgraded to latest release, merged all changes from .env.example to my (3 years old) .env file and lowered the API_TOKEN_EXPIRATION_YEARS . Still nothing. After checking all dependencies there was only one thing left: The Apache Config. It seems I was preventing the loading of internal .htaccess file by using the alternate apache config provided in the install docs [https://snipe-it.readme.io/docs/linuxosx].
> 
> So going back to the default apache config was my fix:
> 
> ```
> <VirtualHost *:80>
>     <Directory /var/www/html/public>
>         Allow From All
>         AllowOverride All
>         Options -Indexes
>     </Directory>
> 
>     DocumentRoot /var/www/html/public
>     ServerName www.yourserver.com
>     # Other directives here
> </VirtualHost>
> ```

Thank you! That really worked. Updating `AllowOverride None` to `AllowOverride All` seems to fix the API errors.
