### ISSUE TITLE
Adding 'Title' to Custom report

### ISSUE THREAD

**Issue by Mynty100** [grokability/snipe-it#10362]
### Snipe-IT Version

5.3.3

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Adding 'Title' to custom reports
This required as we use this field for the users home group.

### Describe the solution you'd like A clear and concise description of what you want to happen.

To add a tick box to the custom report section to include Checked Out To Fields: 'Title'

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Using phpmyadmin to run a custom sql line to pull the info I require.
Please see attached photo for example. Thank you in advance for this request.

### Additional context Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/34461276/143532866-a13cc03a-19fc-4a9e-921c-a67682ddbd38.png)

**Comment by Mynty100** [comment]
Ahoy there. Just wondering if this is something that can be done in a future release?
Would make my life so much easier. Ty in advance.

**Comment by snipe** [comment]
@inietov nice low hanging fruit for you here - can you handle this and PR against both develop and master? TY!
