### ISSUE TITLE
Snipe-IT has a wrong total purchase cost when reaches million

### ISSUE THREAD

**Issue by bagz0506** [grokability/snipe-it#10365]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have added some assets that reach already million in total and it gives me a wrong total of the purchase.

![image](https://user-images.githubusercontent.com/95093625/143604605-c9f18330-d903-40df-a760-32df65a9ab7a.png)

### Reproduction steps

1. Go to All Asset list
2. Scroll down to the total purchase cost
3. Sees that it give me a wrong total value
...

### Expected behavior

Should give me the total cost of all assets

### Screenshots

![image](https://user-images.githubusercontent.com/95093625/143605102-0e150f52-1a05-48ec-8cab-066213554857.png)

### Snipe-IT Version

v5.3.2

### Operating System

Win Server 2016

### Web Server

IIS

### PHP Version

Php 8.1

### Operating System

Win 10 Pro

### Browser

Chrome

### Version

Version 96.0.4664.45 (Official Build) (64-bit)

### Device

Samsung A21

### Operating System

Android 8

### Browser

Chrome

### Version

Version 96.0.4664.45

**Comment by aranar-pro** [comment]
Can confirm and submitted a PR.  Issue was with parsing row values with multiple commas (e.g. 1,040,000).  This was already working in period separated values (1.040.000,00).  Added /g option to accommodate multiple commas.
