### ISSUE TITLE
Only Super User can accept assets

### ISSUE THREAD

**Issue by rawlo91** [grokability/snipe-it#10364]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Befeore a write this i haved Snipe Version v4.8.0 then i was update demo to Version v5.3.3 to see if the bug gone but didn't.  

OK

Bug:
When i checkin a asset and i get a email is ok. Then when i checkout this same asset to me (normal user) i have a email with link to accept this asset, when i go to link address i have a info first 'does_not_exist' 	=> 'Nabytek/zasób nie istnieje.', after when i click on teh button i have  'insufficient_permissions'. 

Photo:
![image](https://user-images.githubusercontent.com/61781556/143597251-6e7244bf-d350-4e3b-82d5-eba550a093d7.png)
![image](https://user-images.githubusercontent.com/61781556/143597372-be44edc4-4631-42d7-9cb6-bb7d6a831d47.png)

When i go to Global User "Mode" and click on this same link to accept assets.
![image](https://user-images.githubusercontent.com/61781556/143592273-55ae9020-a114-41cb-adaa-da523e443a44.png)

What am I doing wrong?

### Reproduction steps

1. Checkin assets - mail ok
2. Checkout this same assets - mail with link to accept assets
3. Info Error: 'does_not_exist' -> click button accept/decline -> Error: insufficient_permissions
4. Change permissions to Global User
5.  I can accept or decline
...

### Expected behavior

I want to normal user will can accept or decline assets.

### Snipe-IT Version

v5.3.3

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows 10

### Browser

Chrome

**Comment by rawlo91** [comment]
Halo?

**Comment by rawlo91** [comment]
@inietov do you know what is going an here?

**Comment by inietov** [comment]
Let me see if I can reproduce this in my installation, and I let you know what I find.

**Comment by rawlo91** [comment]
@inietov do you have something?

**Comment by inietov** [comment]
Im really sorry, not yet. Gonna check this out today. I remember something similar happening.

**Comment by snipe** [comment]
I don't even know what a global user is? Do you mean super user?

**Comment by rawlo91** [comment]
@snipe yes Global: Super User

**Comment by rawlo91** [comment]
@snipe @inietov  I release that not every users have this bug. When i add a new user he do not have this problem. That way i delete and add every users with this bug and is working now.
