### ISSUE TITLE
Missing Translation of Admin Dashboard

### ISSUE THREAD

**Issue by MalteKiefer** [grokability/snipe-it#10369]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The admin dashboard contains only strings that cannot be translated

### Reproduction steps

1. Login
2. Click on the gears in the right top corner

https://github.com/snipe/snipe-it/blob/a5793531988d4078389eb50a8e43573dc62297ae/resources/views/settings/index.blade.php#L56

### Expected behavior

Please add all strings to Crowdin that they are translatable.

### Screenshots

![image](https://user-images.githubusercontent.com/59220985/143864922-f3534d7e-8a96-4791-b1ef-988cd70cc14e.png)

### Snipe-IT Version

v5.3.3 build 6517 (g4afd598df)

### Operating System

Debian

### Web Server

Apache

### PHP Version

7.4.26

**Comment by MalteKiefer** [comment]
@snipe any updates to this here?

**Comment by nuraeil** [comment]
> @snipe any updates to this here?

See #10264 

Still WIP as it is a lot of work.
