### ISSUE TITLE
Provide ability to CONSUMABLES and ACCESSORY quantities 

### ISSUE THREAD

**Issue by jcookatlas** [grokability/snipe-it#10378]
### Snipe-IT Version

v5.3.3 build 6517 (g4afd598df)

### Operating System

Ubuntu Server 20.04

### Web Server

Apache2

### PHP Version

7.4.3

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

At current, it **IS NOT** possible to adjust On-Hand quantities of accessories nor consumables in a truly accountable manner.  Yes, you can go through the 'Create New' workflow for both item types but that just adds another line to the underlying table.  We, the USERS and LOVERS of Snipe-IT **NEED**:
1) Transactional (Cumulative) Accessory and Consumables On-Hand quantity adjustment/update -> IE: Going through the 'Create New' workflow and "cloning" the item information (eg name, model number,  item number, etc) SHOULD result in a GLOBAL and CUMULATIVE update of the On-Hand quantity for that item.  It currently does not.
2) On-The-Fly adjustment/update of On-Hand quantity for both accessory and consumables items.

In the screen shot below, BOTH items are the same Black Ink Toner - with the exact same model and item numbers...
But, instead of having 35, I have one listing of 10 and one listing of 25...

![Capture](https://user-images.githubusercontent.com/95373373/144287691-6d47c313-7c61-4d18-b1a7-264e7e388654.JPG)

### Describe the solution you'd like A clear and concise description of what you want to happen.

See Problem Description

**Comment by metalolf** [comment]
I got through the installation process and filled the system with some sample data, I immediately stumbled over the same issue. 
Without such feature, acceptance of my colleagues and employees will go down to /dev/null 🤷‍♂️

I hope this will be implemented very quickly, because it doesn't seem to be such an big enhancement. ❤

**Comment by pablocta** [comment]
Hola. Tengo el mismo problema. No se puede actualizar el stock de consumibles, en caso de que tenga un nuevo ingreso del mismo consumible, por ejemplo tonner

**Comment by snipe** [comment]
Closing as duplicate of #5881
