### ISSUE TITLE
How to show active consumble list in Consumeble page 

### ISSUE THREAD

**Issue by ShriakntPilaware** [grokability/snipe-it#10411]
### Snipe-IT Version

Version v5.2.0 - build 6339 (master)

### Operating System

Windows Server 2016

### Web Server

IIS

### PHP Version

7.4.13

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

How to show active consumable list on the Consumable
As per the screenshot we just want to showcase the active consumable item list so users can essay issue the Item 
![Consumables](https://user-images.githubusercontent.com/87973455/145553616-610d8472-cd3c-4dd1-9597-586b7b3c1dd9.png)

### Describe the solution you'd like A clear and concise description of what you want to happen.

Only see active item stock consumable

**Comment by ShriakntPilaware** [comment]
Please reply me

**Comment by snipe** [comment]
Active consumables will be the ones that have a clickable checkout button. There is no way to filter them out in a single view.

**Comment by ShriakntPilaware** [comment]
> Active consumables will be the ones that have a clickable checkout button. There is no way to filter them out in a single view.

Can  we showcase the active list on the top and nonactive after that
