### ISSUE TITLE
Grid keeps search results in memory

### ISSUE THREAD

**Issue by herman-aka-wouter** [grokability/snipe-it#10428]
### Snipe-IT Version

v5.3.0 build 6470 (gf87ffb84d)

### Operating System

Docker Image (ubuntu)

### Web Server

Build-In Docker (apache I guess)

### PHP Version

7.4.3

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

All the grids have a exelent search function. which is great. 

But when you leave the page of the users for example. go back to the user page, the search result is beeing kept.  also when you reload the page.
Which is, in sometimes nice, but in most of the times its really annoying.  that you first have to clear the seach bar

### Describe the solution you'd like A clear and concise description of what you want to happen.

Stop keeping the search bar filled when you go back to a page. always show the full unfiltered grid

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Optional: A setting (on/off) which allows the user to define if the search results must be hold when you go back, or reload the page

**Comment by snipe** [comment]
That's behaving as expected, and also why we have the search box highlighted bright yellow when there is text in it - to make it more obvious.
