### ISSUE TITLE
LDAP Group support

### ISSUE THREAD

**Issue by laec27** [grokability/snipe-it#10430]
### Snipe-IT Version

v6-pre-alpha build 6506 (ge75a5f13e)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

It is impractical to do not have the power to use group functionality in consideration of LDAP.

### Describe the solution you'd like A clear and concise description of what you want to happen.

The implementation of LDAP Group support in the existing functionalities.

**Comment by adagioajanes** [comment]
I think this is a great idea. Having the ability to synchronize groups would make user management and classification 100x easier. Especially since, I have several license subscriptions that are tied to groups.

**Comment by taeys** [comment]
I'd like that feature too. We use LDAP Groups for all of our tools, only SnipeIT does not support that feature.

**Comment by taeys** [comment]
we also would love this feature since we controll all of our stuff with ldap groups.

**Comment by benwa** [comment]
This looks to be a duplicate of #8356 and #4877

**Comment by snipe** [comment]
Duplicate of #4877
