### ISSUE TITLE
Slack Settings not saving

### ISSUE THREAD

**Issue by exula** [grokability/snipe-it#10438]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When inputting slack settings, and confirming that the Test runs hitting save does not actually save the Setting in the Databsae.

### Reproduction steps

1. Input all of your Slack Settings
2. Confirm that the test runs
3. Hit that save button with great strength
4. Look at the database and realise that the slack_endpoint, slack_channel and slack_botname variables are still set to NULL

### Expected behavior

It's expected that the slack settings actually save.

### Snipe-IT Version

v5.3.5 build 6558 (gc988d8427)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

**Comment by snipe** [comment]
Thanks for the fix!
