### ISSUE TITLE
Could you please provide a OVF image of Snipe-it ?

### ISSUE THREAD

**Issue by ibou95** [grokability/snipe-it#10440]
### Snipe-IT Version

5.3.5

### Operating System

Linux or windows

### Web Server

Apache or ISS 

### PHP Version

Last

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Could you please provide an OVF file that we could import in our environment ?
Or the commands to run to install on a brand new Redhat.
Tried my best but can't get it working.

### Describe the solution you'd like A clear and concise description of what you want to happen.

Could you please provide an OVF file that we could import in our environment ?
Or the commands to run to install on a brand new Redhat.
Tried my best but can't get it working.

**Comment by snipe** [comment]
I'd accept a PR for this if someone wanted to come up with one, but we already provide support for Windows, Linux, MacOS, Docker, Heroku, ssh installs, cPanel, etc, so I don't think this is a high priority on our end. 

What are the issues you're having on RedHat?
