### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by litems** [grokability/snipe-it#10442]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

after upgrade i no longer can use snipe-it, getting error 500

### Reproduction steps

1.??
2.??
3.??
...

### Expected behavior

after upgrade getting the error 500 

### Screenshots

![image](https://user-images.githubusercontent.com/23707548/146376014-7e976eb9-ec08-418d-9ddc-7092d58cab60.png)

### Snipe-IT Version

lates

### Operating System

ubuntu 18.04

### Web Server

apache

### PHP Version

7.2.14

### Browser

chrome

### Error messages

```shell
error 500
```

### Additional context

/var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php
        return ! ($expires && Carbon::now()->getTimestamp() > $expires);
    }
 
    /**
     * Get the URL to a named route.
     *
     * @param  string  $name
     * @param  mixed  $parameters
     * @param  bool  $absolute
     * @return string
     *
     * @throws \Symfony\Component\Routing\Exception\RouteNotFoundException
     */
    public function route($name, $parameters = [], $absolute = true)
    {
        if (! is_null($route = $this->routes->getByName($name))) {
            return $this->toRoute($route, $parameters, $absolute);
        }
 
        throw new RouteNotFoundException("Route [{$name}] not defined.");
    }
 
    /**
     * Get the URL for a given route instance.
     *
     * @param  \Illuminate\Routing\Route  $route
     * @param  mixed  $parameters
     * @param  bool  $absolute
     * @return string
     *
     * @throws \Illuminate\Routing\Exceptions\UrlGenerationException
     */
    public function toRoute($route, $parameters, $absolute)
    {
        return $this->routeUrl()->to(

**Comment by snipe** [comment]
According to your screenshot, that is happening on the accept asset page.Are you seeing it elsewhere? Did you clear your settings? How did you upgrade? What version did you upgrade from and to? (Lates is not an appropriate answer here.) Literally any additional info would be very helpful, since the demo (which is the exact same code as is on master) is working as far as I know.

**Comment by litems** [comment]
Hello ,

Thanks for the respond,

I used command git pull and then php upgrade.php.
if i remember correctly my version was 4.5.

**Comment by se4598** [comment]
I had the same error message and it solved after upgrading composer (which was locally phar file in my case) to the 2er-Branch (was on latest 1 version)
``` php composer.phar self-update --2```
and then running upgrade.php again

**Comment by litems** [comment]
Hello,

Thanks again for the support, it helped me to restore my snipe it  app.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
