### ISSUE TITLE
Bulk Checkin for Assets

### ISSUE THREAD

**Issue by adagioajanes** [grokability/snipe-it#10454]
### Snipe-IT Version

5.3.5

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.26

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Sometimes, I just need to take a box of assets that have been returned to me, and check them in really quick. Currently, though, I have no way to complete the check in process in bulk. I have to open each asset and mark it as checked back in, rather than just check them in all quickly in a row (similar to the bulk audit process).

### Describe the solution you'd like A clear and concise description of what you want to happen.

I would like a screen similar to the bulk audit screen, that allows me to check in assets to a location quickly and easily. This would allow a user to type in an asset tag, press enter, and have that asset checked in. This specific functionality of typing the asset tag and hitting enter would also give the feature the ability to work with barcode scanners.

### Additional context Add any other context or screenshots about the feature request here.

Already have a pull request going with the feature about 75% complete. Submitting that very soon.

**Comment by kaylahynes** [comment]
Reopening this feature request, would it be possible to add a "change asset status" dropdown to the bulk check-in menu?

**Comment by snipe** [comment]
Please create this as a new issue, as this particular issue has already been resolved.
