### ISSUE TITLE
Query to join licenses and seats

### ISSUE THREAD

**Issue by JasonLoCascio-Personal** [grokability/snipe-it#10457]
### Snipe-IT Version

v5.2.0 build 6339 (g14a8baeca)

### Operating System

Debian 11.00

### Web Server

Apache

### PHP Version

7.4

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Just want to be able to run a report that lists licenses and seats they are assigned to

### Describe the solution you'd like A clear and concise description of what you want to happen.

We're using licenses to store Mobile numbers on a contract. Each llicense seat is assigned to a user.

Is it possible to get a single report showing license (mobile no,) and user that is assigned to (seat) ?

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Quite happy to run an SQL query and get a CSV

**Comment by snipe** [comment]
You can just make a GET request to the license seats endpoint. `/api/v1/licenses/{id}/seats`

```
✨snipe@chodeblossom✨ snipe-it  (master) $ php artisan route:list | grep seats
|        | GET|HEAD      | api/v1/licenses/{license}/seats                       | api.licenses.seats.index                | App\Http\Controllers\Api\LicenseSeatsController@index                      | auth:api,api,throttle:300,1                          |
|        | GET|HEAD      | api/v1/licenses/{license}/seats/{seat}                | api.licenses.seats.show                 | App\Http\Controllers\Api\LicenseSeatsController@show                       | auth:api,api,throttle:300,1                          |
|        | PUT|PATCH     | api/v1/licenses/{license}/seats/{seat}                | api.licenses.seats.update               | App\Http\Controllers\Api\LicenseSeatsController@update                     | auth:api,api,throttle:300,1
```
