### ISSUE TITLE
Group management - Pull down menu issue.

### ISSUE THREAD

**Issue by Dennis-MSI** [grokability/snipe-it#10461]
### Debug mode

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi Admins, Developers.

We tried searching for the group "UK - Users" created in our Asset (Snipe-it) system under "Group management" but we cannot find it.
We can only find it when searching for it in the Search bar.
We also saw that when i change the Row lines from 20 to 10, we cannot set it back to 20.

Snipe it is allready on the latest version (v5.3.6) and Ubuntu also. (20.04.3)

also cleared all cache in Snipe-it and did a reboot, and cleared all cookies in the web browser.

I've reproduced the issue in the Snipeit test system and got the same error there.

**"adagioajanes" from Discord is aware of this issue.**

Command that we've executed:
composer dump-autoload; php artisan cache:clear; php artisan config:clear; php artisan route:clear; php artisan debugbar:clear; php artisan event:clear; php artisan view:clear; php artisan optimize:clear; php artisan clear-compiled"

### Reproduction steps

1. Create more then 10 groups in "group management" under "settings".
2. Use the pull down menu to select 10.
3. Now you cannot select 20 again and you will have to search for the created group mannualy.

### Expected behavior

I want all groups visible for the view selecting you select.

### Screenshots

![image](https://user-images.githubusercontent.com/96120758/147049593-1e3edb3e-d1cc-4551-892a-a7014e19312e.png)

### Snipe-IT Version

v5.3.6 build 6567

### Operating System

20.04.3

### Web Server

IIS

### PHP Version

7.4.3

**Comment by adagioajanes** [comment]
Found the issue. The total number of groups was not being passed to the `transformDatatables` method, nor was it being accepted by the `transformGroups` method. I will submit this PR.
