### ISSUE TITLE
Increase size of supplier address field

### ISSUE THREAD

**Issue by savornicesei** [grokability/snipe-it#10469]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Supplier address field is limited to 50 characters which is insufficient in some cases.

### Reproduction steps

1. Add or update a [real supplier](https://www.senetic.ro/site/contact/)
2. Click save
3. Validation error " The address may not be greater than 50 characters." is displayed

### Expected behavior

Supplier data is saved

### Screenshots

![image](https://user-images.githubusercontent.com/917232/147500715-460793d9-5f4b-4f28-8b8b-c1ade7c71aad.png)

### Snipe-IT Version

v5.3.6 - build 6567 (master)

### Operating System

openSUSE Tumbleweed

### Web Server

Apache 2.4.46 (Bitnami LAMPP 7.4.15)

### PHP Version

7.4.15  (Bitnami LAMPP 7.4.15)

### Operating System

openSUSE Tumbleweed

### Browser

Firefox

### Version

95.0.1

**Comment by yosiasz** [comment]
Just move camera to the next field
![image](https://user-images.githubusercontent.com/900951/147505160-d2e63dfe-f77b-4d7e-8a78-ac61a74100b9.png)
