### ISSUE TITLE
Importing Assets Should Auto Generate Asset Tags (when configured)

### ISSUE THREAD

**Issue by adagioajanes** [grokability/snipe-it#10474]
### Snipe-IT Version

5.3.6

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.26

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Today, I was assisting an admin with importing assets, when we ran into an issue.

`The asset tag field is required.`

Because this was going to be a brand new asset management system (not replacing an existing one with pre-assigned tag numbers), the admin did not have an asset tag field setup.

Unfamiliar with the intricacies of the import process, I suggested that we utilize the 'Generate auto-incrementing asset IDs' feature, to allow Snipe IT to generate the asset tags for us. However, this did not resolve the issue.

Ultimately, to resolve the issue, we edited the file to have asset tags already set for each asset. This allowed the import process to proceed.

### Describe the solution you'd like A clear and concise description of what you want to happen.

If the admin setting for `Generate auto-incrementing asset IDs` is turned on, and the import does not have `Update Existing Values`, then importing assets without an asset tag should automatically generate new asset tags.

This feature could also be implemented with an import option to allow auto generated asset tags on the import (when the global setting is also turned on).

Requiring an asset tag be pre-populated when an admin has already turned on `Generate auto-incrementing asset IDs` is confusing and can lead to unnecessary frustration when trying to setup a brand new asset management system.

![image](https://user-images.githubusercontent.com/38761237/147787604-b8559ec9-a719-40aa-b709-b7b7e12855d6.png)

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

If this was done by design, then I am guessing (but please correct me) that this was done to either...
1. Prevent users from accidently importing their existing assets without their existing tags. This could lead to an issue where the assets could possibly have to be completely deleted and reimported to correct the tags.

     **and/or**

2. Prevent users from trying to re-import assets that they have already imported. This could lead to duplicate assets.

I think these considerations are important. But I think that these considerations should be in the documentation, rather than limiting the software to prevent these issues.

### Additional context Add any other context or screenshots about the feature request here.

I am not writing this feature request as a hard and fast, "This must be implemented to fix importing." This is more of me just sharing my experience with the feature, and how I approached it from an outside perspective. :)

**Comment by Wgs18820** [comment]
On my new install of Version v5.3.6 - build 6567 (master) @adagioajanes was expeditious & concise on identifying the area of concern.   He's a valuable asset to all.

**Comment by inietov** [comment]
Already fixed in https://github.com/snipe/snipe-it/commit/5f93d7b3be76aa44fe9e1ff181ba48253e07072b
