### ISSUE TITLE
[Feature Request] Expose Asset QR codes or labels in API

### ISSUE THREAD

**Issue by dsneath** [grokability/snipe-it#10499]
### Snipe-IT Version

5.3.2 - build 6508 (master)

### Operating System

Windows

### Web Server

Hosted

### PHP Version

Hosted

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

When pulling asset details via the API, I would like the ability to obtain the QR code associated with the asset so it can be integrated into reports printed from other systems.

For example, our on/off-boarding software is currently integrated to allow us to automatically generate a report of assets assigned to a user when they are terminated. Inclusion of the QR codes would allow I.T. staff to quickly learn the details of each asset while keeping the printed report more concise (rather than printing all of the details directly on the report).

Currently, this can only be accomplished by passing the asset's URL (HTTP://baseurl/hardware/id) to a 3rd-party API to generate the code. This feels unnecessary given that Snipe-IT already generates them for labels and GUI use.

### Describe the solution you'd like A clear and concise description of what you want to happen.

Expose a qr_code query parameter on /hardware in the API which would return a jpeg or png formatted QR code that could be used in integrations with other systems.

**Comment by snipe** [comment]
This is on master now
