### ISSUE TITLE
[Issue\Feature request] | Control login enable\disable option for users

### ISSUE THREAD

**Issue by avielc** [grokability/snipe-it#10493]
### Snipe-IT Version

v5.3.6 

### Operating System

Centos

### Web Server

Nginx

### PHP Version

5.7.4

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

This is an issue as well as a feature request

Currently by syncing LDAP\AD all users who are active will be able to login. 
I would like to flag them all as disabled to login (my idea of Inventory means, having an automated list of employees from AD that can have  computers assigned to them, without them having any access to this system. 

Any simple method to turn off login to everyone? (instead of editing each employee?) 

Thanks

### Describe the solution you'd like A clear and concise description of what you want to happen.

I can think of a few solutions here:
- An LDAP flag to disable login to all members
- Ability to bulk edit all added users and disable their access
- add such function to groups and add it to there

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Alternative can be - disable all users by default (simply because if you are manually adding new employees you may want to control who has access by default
Default group assignment to new users that get synced automatically

**Comment by mohankumar11** [comment]
Hi @snipe, I want to Bulk Edit on "Login Enabled" flag to on and off. Is this feature available?

TIA

**Comment by snipe** [comment]
I believe this was already implemented.
