### ISSUE TITLE
LDAP Sync Fails With Google Secure LDAP

### ISSUE THREAD

**Issue by bahhhhh** [grokability/snipe-it#10506]
### Debug mode

- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Snipe-IT environment:
- [Docker](https://snipe-it.readme.io/docs/docker)
- Host OS: Ubuntu 20.04.3 LTS

I followed [these instructions](https://snipe-it.readme.io/docs/hosted-ldap-providers#google-secure-ldap-service) to configure Google Secure LDAP, but LDAP synchronization fails with this error:
```
Connection to LDAP server ldaps://ldap.google.com failed. Verify that the LDAP hostname is entered correctly and that it can be reached from this web server. Server Responded with error: Can't contact LDAP server
```

### Reproduction steps

1. Follow [these instructions](https://snipe-it.readme.io/docs/hosted-ldap-providers#google-secure-ldap-service) to configure Google Secure LDAP
2. Test LDAP synchronization

### Expected behavior

LDAP sync should be successful

### Screenshots

![snipeit](https://user-images.githubusercontent.com/4534172/149359418-8ddd61ad-2bef-46d5-95de-0c20bd9cb294.png)

### Snipe-IT Version

5.3.7

### Operating System

Docker

### Web Server

Docker

### PHP Version

Docker

### Error messages

```shell
[10:19:09] LOG.info: Preparing to test LDAP user login
[10:19:09] LOG.debug: LDAP ERROR: Can't contact LDAP server
[10:19:09] LOG.debug: Connection to LDAP server ldaps://ldap.google.com failed. Please check your LDAP settings and try again. Server Responded with error: Can't contact LDAP server
```

**Comment by bvelastegui** [comment]
My solution:

- Check "This is an Active Directory server"
- Put your domain in "Active Directory domain"
- Use ldap:// in "LDAP Server"
- Check use TLS
- Check LDAP SSL ceritificate validation
- Save and test connection

Important: to log in you only have to enter the user omitting @yourdomain.com

**Comment by bahhhhh** [comment]
@bvelastegui Wow, that worked! 🎉  Thank you!

**Comment by Mistic92** [comment]
I have the same issue on v6.0.0-RC-1 - build 6592 (develop) but using settings recommended by @bvelastegui are not working.

**Comment by snipe** [comment]
@Mistic92 can you open a v6 ticket for this please?

**Comment by uberbrady** [comment]
(Also, make *sure* to mention that this is on Docker)

**Comment by ddqq1** [comment]
I'm having the same issue. 

System Information
Snipe-IT version v5.3.8 build 6619 (g1ef336a08)
Software License [AGPL3]
PHP Version 7.4.27
Laravel Version 6.20.29

I tried what @bvelastegui said and it doesn't make a difference. Any suggestions?

**Comment by snipe** [comment]
@ddqq1 please open a new ticket for this
