### ISSUE TITLE
confusing/duplidate environment variables

### ISSUE THREAD

**Issue by kale1d0code** [grokability/snipe-it#10505]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

environment variables listed under https://snipe-it.readme.io/docs/configuration
are different to https://snipe-it.readme.io/docs/docker
not sure which variable names are the correct ones to use

### Reproduction steps

1.
2.
3.
...

### Expected behavior

there to be one set of variables

### Snipe-IT Version

v5.3.6 - build 6567

### Operating System

alpine?

### Web Server

traefik

### PHP Version

7.4.3

**Comment by ccj9874** [comment]
Use the environment variables that come pre-filled in the .env file when you pull the latest version from Github. If anything, the .env on the Docker page is much more out of date than the Configuration page, so use that one.

**Comment by snipe** [comment]
We'll update the docs.
