### ISSUE TITLE
[Feature Request] HTML files in uploads

### ISSUE THREAD

**Issue by ZorbaHerbalist** [grokability/snipe-it#10513]
### Snipe-IT Version

all

### Operating System

all

### Web Server

all

### PHP Version

all

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Is it possible to add the option of uploading HTML files? We use HWINFO and AIDA64 to generate reports on hardware, being able to include them in SnipeIT would be very helpful. 

### Describe the solution you'd like A clear and concise description of what you want to happen.

Allow the attachment of HTML files in uploads

**Comment by snipe** [comment]
Unfortunately, allowing HTML uploads would introduce security issues :( If someone uploaded a malicious HTML file that contained Javascript, for example, it would leave the system open to session hijacking, and all kinds of other potential abuses.

Best way is to zip them and upload the zip. :(

**Comment by ZorbaHerbalist** [comment]
It is possible to force a download of a file instead of displaying it in the browser?

**Comment by snipe** [comment]
Yes, but zipping is your best option. I do not want to try to have to navigate browser plugins that could potentially override that behavior.
