### ISSUE TITLE
New Require SAML setting prevents API authentication

### ISSUE THREAD

**Issue by adagioajanes** [grokability/snipe-it#10517]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

PR #10449 allows for a configurable environment variable to control authentication. When this setting is enabled, all authentication is required to go through SAML. This improperly includes API connections as well.

### Reproduction steps

1. Setup an instance of the latest development branch
2. Setup SAML
3. Turn on the new `REQUIRE_SAML` environment variable
4. Attempt to use the API and be redirected to the configured SAML endpoint

### Expected behavior

API authentication should still work, even if SAML is required via the environment variable.

### Available workaround

Disable the `REQUIRE_SAML` environment variable. This will allow API authentication to function again.

### Screenshots

This is a screenshot from Postman attempting to make a simple /hardware API call. It is redirecting to the configured SAML login...

![image](https://user-images.githubusercontent.com/38761237/149565624-8ec951f5-89ba-452d-be8f-d17dbf3d937c.png)

### Snipe-IT Version

v6-RC1

### Operating System

Windows

### Web Server

PHPStorm Built In Webserver

### PHP Version

7.4

### Operating System

Windows

### Browser

Postman

### Version

9.8.3

**Comment by adagioajanes** [comment]
Because I wrote the PR, I will work on this issue. :)

**Comment by snipe** [comment]
I'm not sure that's correct though. They API authenticates through passport, not through the normal login controller, and I cannot reproduce this on my end locally.

**Comment by snipe** [comment]
(Usually when we see the login screen HTML in an API response, it's because the [API request headers](https://snipe-it.readme.io/reference/authenticating-with-the-api) are missing or incorrect.)

**Comment by snipe** [comment]
Nevermind that last comment, I see from the HTML it's a MS SAML endpoint, not our login screen.

Still, Passport should bypass the normal login controller, so I'm not sure why you'd be seeing that.

**Comment by adagioajanes** [comment]
> Nevermind that last comment, I see from the HTML it's a MS SAML endpoint, not our login screen.
> 
> Still, Passport should bypass the normal login controller, so I'm not sure why you'd be seeing that.

That being said, I think _you_ are still correct. What I am getting when I turn off the flag is the Snipe IT login screen. If that is expected with a bad API auth configuration, then I think it is not broken. (I wasn't looking closely enough at the second response. Just that it was a different response.)

**Comment by adagioajanes** [comment]
@snipe False alarm. You are correct. Sorry about that.

**Comment by snipe** [comment]
Well, I think you might be right, I just don't see how. Passport bypasses all of the login controller stuff, so your changes from that PR shouldn't matter - UNLESS that request was going to try to send you to our login screen and then redirects the page to the MS SAML screen.
