### ISSUE TITLE
Restore People via API

### ISSUE THREAD

**Issue by mitchellkellett** [grokability/snipe-it#10524]
### Snipe-IT Version

v5.3.7 - build 6587

### Operating System

Docker

### Web Server

Docker

### PHP Version

Docker

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Currently, we delete users from Snipe-IT when they are deactivated in our Identity Management product. We want to be able to programmatically reactivate them if they become active again. At the moment we have to programmatically output a file of users that we need to manually restore via the UI.

### Describe the solution you'd like A clear and concise description of what you want to happen.

Restore option for People via the API.

**Comment by snipe** [comment]
This is already in the upcoming v6: https://github.com/snipe/snipe-it/blob/develop/app/Http/Controllers/Api/UsersController.php#L534
