### ISSUE TITLE
How to install Snipe It in SiteGround?

### ISSUE THREAD

**Issue by David9999434** [grokability/snipe-it#10531]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi there, I am completely new to web design and all. I don't code. I started with WordPress and loved it, I basically use themes for my sites. today I found snipe it and wanted to host it on siteground. I don't have any idea where to start from. I have downloaded snipe it files and that's about it. tried uploading it inside the public file in my file manager of siteground, I don't know what to do and how to begin. somebody, please help me.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

wanted to see it running on my domain

### Snipe-IT Version

5.3.7

### Operating System

windows

### Web Server

Siteground

### PHP Version

7.3.33

### Operating System

windows

### Browser

chrome

### Version

5.3.7

**Comment by ccj9874** [comment]
SnipeIT isn't meant to be a plugin for a Wordpress website, you need to host it on a web server and then forward it to your domain from there. Unless I misunderstand what SiteGround is, its not meant for hosting something like SnipeIT.

**Comment by David9999434** [comment]
Thanks . I know it has nothing to do with WordPress , i just wanted to host it in siteground

**Comment by snipe** [comment]
This is kind of outside the scope of support here. I’d ask siteground how to make a subdomain and install Snipe-IT there.
