### ISSUE TITLE
Adldap\Adldap not found on V6 RC1

### ISSUE THREAD

**Issue by jouwdan** [grokability/snipe-it#10532]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgrading to V6 RC1, I cannot run the artisan migration / config clear, getting the below error

C:\inetpub\wwwroot\snipe-it>php artisan cache:clear

   Error

  Class 'Adldap\Adldap' not found

  at C:\inetpub\wwwroot\snipe-it\app\Services\LdapAd.php:99
     95▕             sets up an 'account_suffix' of '@'.$this->ldapSettings['ad_domain'] *IF* the user has
     96▕             $this->ldapSettings['ad_append_domain'] enabled.
     97▕             That code in ldapLogin gets simplified, in exchange for putting all the weirdness here only.
     98▕             */
  ➜  99▕             $this->ldap = new Adldap();
    100▕             $this->ldap->addProvider($this->ldapConfig);
    101▕             return true;
    102▕         }
    103▕         return false;

  1   C:\inetpub\wwwroot\snipe-it\app\Services\LdapAd.php:107
      App\Services\LdapAd::init()

  2   [internal]:0
      App\Services\LdapAd::__construct()

### Reproduction steps

1. Upgrade to V6 RC1, installing composer requisites and running dump-autoload
2. Try to run artisan migrate - above error occurs.
3. Try to run artisan cache:clear - above error occurs.

### Expected behavior

clear cache

### Screenshots

![image](https://user-images.githubusercontent.com/76656637/150107695-59f5c590-52d7-4455-84a5-2dd2badd30d5.png)

### Snipe-IT Version

6.0.0 RC1

### Operating System

Windows Server 2016

### Web Server

IIS

### PHP Version

7.4.27

**Comment by uberbrady** [comment]
v6 actually *removes* AdLdap - intentionally. If you run `composer install` does that message go away? If not, then one of the other caches might be getting in your way.

**Comment by jouwdan** [comment]
Looks like when I disable LDAP, run the artisan migration, then re-enable, all works fine. closing.

**Comment by uberbrady** [comment]
Thanks for reporting back! Very much appreciated. I’d still be curious to know why you ran into that error in the first place, but we’ll see if other people report it as well.
