### ISSUE TITLE
[Feature request] Store Software/Drivers and Updates for assets

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#10548]
### Snipe-IT Version

v5.3.5 - build 6558

### Operating System

Windows

### Web Server

IIS

### PHP Version

6

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I need to be able to store all software, drivers and updates that are on each computer asset. This information would be added and read via the API so when computers reboot they auto report into the API as to all software, drivers and updates they have installed.

I could then run reports on which computers have a particular version of software or an update or automate a warning if a bit of software shows up. etc.

### Describe the solution you'd like A clear and concise description of what you want to happen.

For each computer asset to be able to store software name, version number and manufacture as well as driver names and version numbers and update names/numbers.

For the API to provide an ability to write software, drivers and update information back to the database

for the API to provide ability to read software, drivers and updates for a given asset

for the API to provide ability to read what assets have  given software/driver/update name or version

The WGUI could also have a tab for each of the three categories to see the software/drivers/updates listed and added/deleted manually.

**Comment by snipe** [comment]
What you’re looking for is an agent, which we don’t have. The API can store whatever you need it to (drivers are just software), but we don’t currently have any agent.

**Comment by ghost** [comment]
I am not looking for an Agent I am essentially looking for a table of information rather than just a plain field. A screen on the WGUI to show all software installed with a software name column, manufacture column and version column then for the API to support writing and reading this information. We already have our own agent.
