### ISSUE TITLE
Docker build not working on docker desktop - Windows 

### ISSUE THREAD

**Issue by dheechu** [grokability/snipe-it#10547]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Cannot build docker image using "docker build command"

Command used : docker build .

Issue Faced : 
 > [stage-0  5/31] RUN pecl install mcrypt-1.0.3:
#8 5.100 WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
#8 5.769 Could not download from "https://pecl.php.net/get/mcrypt-1.0.3.tgz", cannot download "pecl/mcrypt" (Connection to `ssl://pecl.php.net:443' failed: )
#8 5.770 Error: cannot download "pecl/mcrypt"
#8 5.770 Download failed
#8 5.770 install failed

**after adding pecl channel-update pecl.php.net**

=> CACHED [stage-0  4/32] RUN php go-pear.phar                                                                    0.0s
 => CACHED [stage-0  5/32] RUN pecl channel-update pecl.php.net                                                    0.0s
 => ERROR [stage-0  6/32] RUN pecl install mcrypt-1.0.3                                                            1.9s
------
 > [stage-0  6/32] RUN pecl install mcrypt-1.0.3:
#9 1.864 No releases available for package "pecl.php.net/mcrypt"
#9 1.864 install failed
------
executor failed running [/bin/sh -c pecl install mcrypt-1.0.3]: exit code: 1

Can you please help me on this?

### Reproduction steps

1. Install Docker version 20.10.11, build dea9396 in Windows 10 
2. Pull master branch code of snipe-it from github
3. try building using "docker build ."

### Expected behavior

I should be able to build the docker image of snipeit

### Snipe-IT Version

v5.3.7

### Operating System

Windows 10

### Web Server

Apache as in dockerfile

### PHP Version

7.4 as in dockerfile

### Operating System

Windows 10

### Error messages

```shell
Cannot build docker image using "docker build command"

Command used : docker build .

Issue Faced : 
 > [stage-0  5/31] RUN pecl install mcrypt-1.0.3:
#8 5.100 WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
#8 5.769 Could not download from "https://pecl.php.net/get/mcrypt-1.0.3.tgz", cannot download "pecl/mcrypt" (Connection to `ssl://pecl.php.net:443' failed: )
#8 5.770 Error: cannot download "pecl/mcrypt"
#8 5.770 Download failed
#8 5.770 install failed

**after adding pecl channel-update pecl.php.net**

=> CACHED [stage-0  4/32] RUN php go-pear.phar                                                                    0.0s
 => CACHED [stage-0  5/32] RUN pecl channel-update pecl.php.net                                                    0.0s
 => ERROR [stage-0  6/32] RUN pecl install mcrypt-1.0.3                                                            1.9s
------
 > [stage-0  6/32] RUN pecl install mcrypt-1.0.3:
#9 1.864 No releases available for package "pecl.php.net/mcrypt"
#9 1.864 install failed
------
executor failed running [/bin/sh -c pecl install mcrypt-1.0.3]: exit code: 1
```

**Comment by dheechu** [comment]
Can some please help, i am blocked on this point and couldn't continue

**Comment by uberbrady** [comment]
Unfortunately I'm on a Mac, but I just did a `docker build` and it seemed to work fine?

Why do you need to do a build anyways, can't you just pull the image(s) from Dockerhub?

It looks like you're having some kind of SSL error, where you can't, for some reason, connect to PECL to grab the mcrypt extension?

The output when I just did my build was this:

```
 => [stage-0  5/31] RUN pecl install mcrypt-1.0.3                                                                                                                                                                               6.3s
 => [stage-0  6/31] RUN bash -c "echo extension=/usr/lib/php/20190902/mcrypt.so > /etc/php/7.4/mods-available/mcrypt.ini"                                                                                                       0.3s
 => [stage-0  7/31] RUN phpenmod mcrypt                                                                                                                                                                                         0.3s
```

**Comment by dheechu** [comment]
Incase if i am going to customize the application, I would need to use docker build for development purposes

Anyway, it is working on my another laptop, could be due to firewall or forcepoint. Thanks
