### ISSUE TITLE
Serial Number Required Field

### ISSUE THREAD

**Issue by fentmturner** [grokability/snipe-it#10542]
### Snipe-IT Version

v5.3.7 build 6587

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.27

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Is there a way to make the serial number a required field on everything? Even if it is a toggle option
We rely on serial numbers heavily along with asset tags and would like them both to be required fields to prevent a mishap where one of the techs does not add a serial number. 

### Describe the solution you'd like A clear and concise description of what you want to happen.

Ability to make serial number a required field

**Comment by Xiayu8** [comment]
hey there,

i am not sure if this is the "correct" way to do it, but if you have access to the code you could add a 'required'-tag to the serial.

Assets:
Edit the file Asset.php (snipeit/app/models/Asset.php)
modify line 113 so it looks like this " 'serial' => 'unique_serial|nullable|required', "

Components:
Edit the file Component.php (snipeit/app/models/Component.php)
add after line 39 " 'serial' => 'required', "

After saving the changes and reloading the page you will see the yellow "required indicator" at the serial field and you have to enter a value (while creating new Assets/Components).
