### ISSUE TITLE
/hardware/:id/checkin API reference omits some parameters

### ISSUE THREAD

**Issue by JonathonReinhart** [grokability/snipe-it#10551]
### Describe the bug

The API docs for [`/hardware/:id/checkin`](https://snipe-it.readme.io/reference/hardware-checkin) do *not* mention the following parameters:
- `name`
- `status_id`
- `checkin_at` ([new](https://github.com/snipe/snipe-it/issues/10552))

However, from looking at the code, they both appear to be supported.

See [`Api/AssetsController.checkin()`](https://github.com/snipe/snipe-it/blob/v5.3.7/app/Http/Controllers/Api/AssetsController.php#L833-L835):

```php
        if ($request->filled('name')) {
            $asset->name = $request->input('name');
        }
```

See [`Api/AssetsController.checkin()`](https://github.com/snipe/snipe-it/blob/v5.3.7/app/Http/Controllers/Api/AssetsController.php#L843-L845):

```php
        if ($request->has('status_id')) {
            $asset->status_id =  $request->input('status_id');
        }
```

### Snipe-IT Version

v5.0.x - v5.3.7

**Comment by JonathonReinhart** [comment]
@snipe I can't find where the API docs are maintained (in ~~code~~ git). Can you point me to where I would make a revision?

**Comment by snipe** [comment]
Updated, thank you!

![655223_thank-you-high-five-scott-disick-hand-hug-bruce-jenner](https://user-images.githubusercontent.com/197404/159305018-2c03ffa0-4726-4503-8e04-b147221f8093.gif)
