### ISSUE TITLE
Manager field is not filled

### ISSUE THREAD

**Issue by mexx3001** [grokability/snipe-it#10565]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When importing users from the Active Directory, some attributes are set, but the manager is not stored for any user, although it is stored in the Active Directory for the users.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Is there a possibility to fill this field somewhere or that the manager of the user is automatically included in an LDAP sync.
I have already tried everything possible but have not yet come to any result.

### Snipe-IT Version

5.2.0 (Live environment) and 6.0.0-RC1 (Test environment)

### Operating System

Windows Server 2019 Standard

### Web Server

IIS

### PHP Version

7.4.15 (Live Environment) and 8.0.15 (Test Environment)

### Operating System

Windows

### Browser

Chrome, Firefox, Edge,

### Additional context

Is this a fresh install or an upgrade?
Both fresh installation

What OS and web server you're running Snipe-IT on
Windows Server 2019 Standard, IIS

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Installation

Include what you've done so far in the installation, and if you got any error messages along the way.
No errors during installation and also not during operation

Indicate whether or not you've manually edited any data directly in the database
No

**Comment by wewhite** [comment]
I have run into this problem. 
Straight from google: **_AD Manager Attribute_**

> The Manager attribute is a pointer to the actual content of the manager's user record. To be able to access the data associated with the manager DN, code must be written to look up user information, and also to look up the manager DN data. This also depends upon the Principal privileges within the Active Directory.

In the code App\Console\Commands\LdapSync.php, the manager attribute is text parsed from the manager DN result, which is incorrect. After getting the manager attribute, another ldap lookup should happen using the manager DN result as the base. Then can parse the username to look up and link the manager.

Code from v6.0.9
```php
                  if($item['manager'] != null) {
                    //Captures only the Canonical Name
                    $item['manager'] = ltrim($item['manager'], "CN=");
                    $item['manager'] = substr($item['manager'],0, strpos($item['manager'], ','));
                    $ldap_manager = User::where('username', $item['manager'])->first();
                    if ( $ldap_manager && isset($ldap_manager->id) ) {
                        $user->manager_id = $ldap_manager->id;
                    }
                }```

**Comment by wewhite** [comment]
Similar issue #11086

**Comment by snipe** [comment]
@Godmartinz can you take a look?

**Comment by wewhite** [comment]
This code fixes the problem:
```php
                if($item['manager'] != null) {

                    // Get the LDAP Manager
                    $ldap_manager = Ldap::findLdapUsers($item['manager'], -1, $this->option('filter'));
                    LOG::debug('LDAP Manager count: '.$ldap_manager["count"]);

                    if($ldap_manager["count"] > 0) {
                        
                        // Get the Managers username
                        $ldapManagerUsername = $ldap_manager[0][$ldap_result_username][0];
                        LOG::debug('LDAP Manager USERNAME: '.$ldapManagerUsername);

                        // Get User from LDAP Manager User name.
                        $ldap_manager = User::where('username', $ldapManagerUsername)->first();

                        if ( $ldap_manager && isset($ldap_manager->id) ) {

                            // Link the users manager_id to the manager id.
                             $user->manager_id = $ldap_manager->id;
                        }
                    }
                }

**Comment by snipe** [comment]
@wewhite can you put together a PR with this fix so we can test?

**Comment by wewhite** [comment]
> @wewhite can you put together a PR with this fix so we can test?

Yes, I need to re-setup my dev environment, will be a couple of days.
