### ISSUE TITLE
UI/UX - Add link back to Asset after creation

### ISSUE THREAD

**Issue by MWR-Napavine** [grokability/snipe-it#10561]
### Snipe-IT Version

5.3.2

### Operating System

Hosted

### Web Server

Hosted

### PHP Version

7.3.23

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

When creating a new asset, it returns you to the previous search results with a "Success: Asset created successfully." box on the top of the page. There is not easy way to get back to that asset if there is more to edit on that asset.

### Describe the solution you'd like A clear and concise description of what you want to happen.

Please include the Asset barcode and a link back to the asset that was just created.

**Comment by snipe** [comment]
Hey there - that’s actually in the works for the upcoming v6. It should be out soon :)

**Comment by MWR-Napavine** [comment]
Okay. Thanks!
