### ISSUE TITLE
php artisan key:generate ErrorException  

### ISSUE THREAD

**Issue by MatthijsHoekstra** [grokability/snipe-it#10572]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Key cannot be generated gives error  ErrorException  : Undefined index: scheme. 

Please advice on how to continue.

### Reproduction steps

1. Follow tutorial

### Expected behavior

App Key being generated

### Screenshots

![image](https://user-images.githubusercontent.com/22255583/151415898-78a62ba8-751a-4fab-8562-3876e18913eb.png)

### Snipe-IT Version

newest

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Error messages

```shell
ErrorException  : Undefined index: scheme

  at /var/www/snipe-it/app/Providers/AppServiceProvider.php:50
    46|
    47|         // TODO - isn't it somehow 'gauche' to check the environment directly; shouldn't we be using config() somehow?
    48|         if ( ! env('APP_ALLOW_INSECURE_HOSTS')) {  // unless you set APP_ALLOW_INSECURE_HOSTS, you should PROHIBIT forging domain parts of URL via Host: headers
    49|             $url_parts = parse_url(config('app.url'));
  > 50|             $root_url = $url_parts['scheme'].'://'.$url_parts['host'].( isset($url_parts['port']) ? ':'.$url_parts['port'] : '');
    51|             \URL::forceRootUrl($root_url);
    52|         }
    53|
    54|         Schema::defaultStringLength(191);

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()
      /var/www/snipe-it/app/Providers/AppServiceProvider.php:50

  2   App\Providers\AppServiceProvider::boot()
      /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
```

### Additional context

Fresh install following manual; https://www.vultr.com/es/docs/how-to-install-snipe-it-on-ubuntu-20-04

**Comment by uberbrady** [comment]
Thanks! We're working on this now.

**Comment by uberbrady** [comment]
@MatthijsHoekstra do you have your `APP_URL` set in your `.env`?

**Comment by MatthijsHoekstra** [comment]
@uberbrady I did set it yes! Without www. , http:// - https://

**Comment by uberbrady** [comment]
Thanks for answering! for `APP_URL`, we are expecting a FQDN (Fully Qualified Domain Name) - so it should include http:// or https:// and a hostname, an optional port (if needed), and a subdirectory path (if you have it hosted funny in some kind of subdirectory). If you have those things it *ought* to work........I just pushed a fix (and @snipe merged) to master that might help?

**Comment by snipe** [comment]
@MatthijsHoekstra I'm not sure if you mean you set it without `www` but *with* `http://` or `https://`, but this is how it's [documented](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings). 

<img width="797" alt="Screen Shot 2022-01-27 at 11 54 24 AM" src="https://user-images.githubusercontent.com/197404/151433712-f7e646f8-abfa-4de0-9f4c-b36aa82f8dfc.png">

**Comment by MatthijsHoekstra** [comment]
That might explain my problem. I did it without http(s). Thanks for the flexibility will come back to you to confirm it is working.

**Comment by snipe** [comment]
Excellent - please do let us know!

**Comment by MatthijsHoekstra** [comment]
Now it works. Pulled the repository again and added the `http://domain.com` at `APP_URL`
