### ISSUE TITLE
Installer does not work on CentOS 7 as root or as sudo user

### ISSUE THREAD

**Issue by tomck** [grokability/snipe-it#10581]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When the [installer](https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh )gets to the composer install section, it fails. I tested this in CentOS 7 after running yum update as the [root user](https://pastebin.com/JigBaJbU) and as a [new user](https://pastebin.com/2DKb487t), snipeitapp (which appears to be created by the installer as well, I did not realize this, but I had a snapshot from before I ran the installer so it was as if it had never happened).  As this is listed as a [valid install option](https://snipe-it.readme.io/docs/downloading#3-download-the-installer), and a lot simpler because I broke the install (it can't properly upgrade) when I tried doing it manually, and Snipey said to file a bug instead of just making it worse when I first installed about 2 years ago, this time I am trying to make a new VM and do it right.

This does not seem to be listed on the common issues page and I cannot enable debug mode as this is not properly "installed" yet.

```
* Creating Snipe-IT user.
* Creating MariaDB Database/User.
* Please Input your MariaDB root password:
Enter password:
* Cloning Snipe-IT from github to the web directory.
* Configuring .env file.
* Installing composer.
-bash: php: command not found
-bash: php: command not found
ERROR: Invalid composer installer signature
rm: cannot remove ‘composer-setup.php’: No such file or directory
```

### Reproduction steps

1. Do install of minimal centos 7 in XenServer from CentOS-7-x86_64-Minimal-1908.iso
2. Login and run `yum update` so you have the latest packages, also install wget via yum install wget
3. Execute the installer script as listed on Installation -> Downloading -> 3. Download the Installer
4. ???
5. Do not profit

### Expected behavior

Installer should either finish without error or find a way to trap the error and explain what can be done to resolve it in some fashion instead of dumping the user to the command line.

### Snipe-IT Version

5.3.6

### Operating System

CentOS 7

### Web Server

Apache

### PHP Version

none (php command not found, installer APPEARS to install php71u but does not seem to add it to PATH)

### Operating System

Windows 10 LTSC

### Browser

Mozilla Firefox

### Version

96.0.3

### Additional context

Fresh install, fresh CentOS 7 OS, install.sh

**Comment by snipe** [comment]
This is the first we’re hearing about this. We’ll look into it. Can anyone else confirm?

I don’t think we’ve made a lot of changes to the installer, since although it’s technically a supported installation method, it’s hard to test on our end (at least in an automated way), I’d be curious to see if other folks are having this problem too.

I’d also be curious as to how you “broke the installer” when you tried to do it manually.

**Comment by tomck** [comment]
I installed composer as root, I tried to git update and wiped out my install, somehow I got most of the data back because my backup that I had was too old, and now if I try to update I get a bunch of 500 errors. It's a hodge-podge that I somehow got working but shouldn't have. The bug seems to really be that it's not detecting that php didn't actually install and is still going forward, not anything with composer.  I am now trying to get Rocky Linux instead of CentOS since it seems this is the way of the future.

**Comment by snipe** [comment]
Running the Snipe-IT upgrade script shouldn’t wipe out an install. It doesn’t try to delete any files, upgrade PHP versions, etc. My guess here is that your install is fine, you just need to fix the permissions. It doesn’t address the installer issue you initially reported, but there’s nothing a git update or our upgrader should do to wipe anything out. It doesn’t delete data, etc.

**Comment by tomck** [comment]
Sorry, I'm migrating from an OpenVZ server to a XenCenter server and I am just trying to do it correctly, this time I will try on Rocky. The OpenVZ one that I broke was because I misunderstood git clean and it deleted the env file.  I still have the history lines from when I did it.  It said I couldn't pull the new files because of changes I had somehow made to Bug_report.md and Feature_request.md and I tried pulling the originals.  The data lost was all images I had uploaded of companies and asset models, none of the database.

```
   94  yum purge php71*
   95  yum remove php71u-*
   96  yum install php72u
   97  yum install php72u-bcmath php72u-cli php72u-embedded php72u-gd php72u-json php72u-ldap php72u-mbstring php72u-mcrypt php72u-mysqlnd php72u-pdo php72u-process php72u-xml
   98  yum search php72u
   99  sudo -u snipeitapp php upgrade.php
  100  ll
  101  chown -R snipeitapp:apache
  102  chown -R snipeitapp:apache *
  103  ll
  104  sudo -u snipeitapp php upgrade.php
  105  git
  106  git checkout v4.9.2
  107  git checkout ./.github/ISSUE_TEMPLATE/Bug_report.md
  108  git checkout v4.9.2
  109  git commit -m "f this"
  110  git stash
  111  git checkout ./.github/ISSUE_TEMPLATE/Bug_report.md
  112  git clean -dfx
  113  git status
  114  ls
  115  nano upgrade.php
  116  git checkout -- .github/ISSUE_TEMPLATE/Bug_report.md
  117  git checkout -- .github/ISSUE_TEMPLATE/Feature_request.md
  118  git status
  119  sudo -u snipeitapp git status
  120  nano .env
  121  sudo -u snipeitapp php upgrade.php
  122  chown -R snipeitapp:apache *
  123  sudo -u snipeitapp php upgrade.php
```

**Comment by tomck** [comment]
One issue is [snipeit.sh line 729](https://github.com/snipe/snipe-it/blob/215beb9d8a6123471f9f7979939eff0cfef06990/snipeit.sh#L729), which references a site that is now gone. Correcting it involves changing the repo to ius.io and updating PHP lines from php71u to php74. This does seem to let the installer finish installing, but I still do not have the system running as the virtualhost is not working correctly, despite httpd -S showing the correct entries. I want to submit a patch but since I do not have it working completely I feel like I may have to abandon the installer method entirely.

Sidenote, CentOS 6 is now completely unsupported so the iuscommunity lines for it are not fixable and I think it should be removed from the snipeit.sh installer entirely.

**Comment by nesretep** [comment]
You should consider targeting a version of CentOS/RHEL newer than v7 also.  CentOS Stream 8/RHEL 8 has already been out for 2 1/2 years.

**Comment by fangme** [comment]
Installing using the install script (retrieved via wget), or the installer (via the git clone), results in the error:

Unsupported CentOS version. Version found: 8.5

Running Oracle Linux (which is just compiled from RHEL), but it is using the "unbreakable" kernel, not the stock RHEL kernel.  I have yet to even find a list of "supported" linux versions/distributions.  While I know it isn't feasible to test under all of the various permutations - seems odd it can't mention specific versions.  Yes, it Requires Centos 6 or Ubuntu 14 or greater.  I've got 8.5 RHEL/CentOS/OL...

I am running the installer as root.  I've found the /etc/os-release file, and it's contents are:
NAME="Oracle Linux Server"
VERSION="8.5"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

So - how does one go about getting it to install on an 8.5 release?

<blockquote><img src="/i/basecamp/UL_penguin_Ologoonfront_CMYK_FY20-white.png" width="48" align="right"><div><strong><a href="https://linux.oracle.com/">Unbreakable Linux Network (ULN):  Login</a></strong></div></blockquote>
<blockquote><img src="images/favicon.ico" width="48" align="right"><div><strong><a href="https://bugzilla.oracle.com/">Bugzilla Main Page</a></strong></div></blockquote>
