### ISSUE TITLE
error The latest version is v5.3.7

### ISSUE THREAD

**Issue by manojmj94** [grokability/snipe-it#10582]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

error 1
STEP 2: Backing up database:
--------------------------------------------------------

-- Starting backup...

   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Spatie\DbDumper\DbDumper::setDbName() must be of the type string, null given, called in /var/www/html/snipe-it/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 38

  at /var/www/html/snipe-it/vendor/spatie/db-dumper/src/DbDumper.php:67
    63|      * @param string $dbName
    64|      *
    65|      * @return $this
    66|      */
  > 67|     public function setDbName(string $dbName)
    68|     {
    69|         $this->dbName = $dbName;
    70|
    71|         return $this;

  Exception trace:

  1   Spatie\DbDumper\DbDumper::setDbName()
      /var/www/html/snipe-it/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php:38

  2   Spatie\Backup\Tasks\Backup\DbDumperFactory::createFromConnection("mysql")
      /var/www/html/snipe-it/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php:30

  Please use the argument -v to see more details.

error 2
Step 7: Migrating database:
--------------------------------------------------------

   Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = ? and table_name = migrations and table_type = 'BASE TABLE')

  at /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)")
      /var/www/html/snipe-it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18

  2   Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
      /var/www/html/snipe-it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43

  Please use the argument -v to see more details.

### Reproduction steps

i have run php upgarde.php

### Expected behavior

We are currently using v4.6.4. The latest version is v5.3.7.

### Snipe-IT Version

5.3

### Operating System

centos

### Web Server

Apache/2.4.6 

### PHP Version

7.2

### Operating System

cent os

### Browser

chrome

### Version

f

### Device

ff

### Operating System

f

### Browser

f

### Error messages

```shell
d
```

### Additional context

need help

**Comment by manojmj94** [comment]
pls help am trapped

**Comment by snipe** [comment]
An immediate comment seconds after opening a GH issue at 1:30 AM on a Sunday morning isn’t a great way to get help. We know you need help, else you wouldn’t have opened an issue. 

> Access denied for user ''@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = ? and table_name = migrations and table_type = 'BASE TABLE')

This means the database settings in your .env are not correct and the script cannot connect to the database to run migrations. This has been discussed hundreds of times within the GH issues. 

The latest version of Snipe-IT is 5.3.8,  not 5.3.7,  by the way.

**Comment by manojmj94** [comment]
Sir pls let me know what i have to do on this am little bit new

**Comment by snipe** [comment]
I am not a sir, so let’s start there.

I’m not sure what other information you need, since you’ve not given me a lot to work with. The database settings in your .env are not correct, so the script cannot connect to the database. Fix that and you’ll probably be fine.

**Comment by snipe** [comment]
Any progress?

**Comment by manojmj94** [comment]
am getting 500 server error

#8 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#9 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#10 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array, true)
#11 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve('App\\\\Http\\\\Middle...', Array)
#12 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#13 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(209): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#14 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(183): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#15 /var/www/html/snipe-it/public/index.php(63): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#16 {main}
"}

**Comment by manojmj94** [comment]
pls help

**Comment by manojmj94** [comment]
#8 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#9 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#10 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array, true)
#11 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve('App\\\\Http\\\\Middle...', Array)
#12 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#13 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(209): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#14 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(183): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#15 /var/www/html/snipe-it/public/index.php(63): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#16 {main}
"}

**Comment by snipe** [comment]
I'd need a *full* stack trace - this doesn't give me any useful information.

**Comment by manojmj94** [comment]
pls let me know how to take that

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by manojmj94** [comment]
![image](https://user-images.githubusercontent.com/98686618/152056425-1f1f933a-dcd7-4e8d-a6bf-5d87ae8752b2.png)

**Comment by manojmj94** [comment]
any luck?

**Comment by snipe** [comment]
That is not a full stack trace - that is a screenshot of part of a stack trace.

This issue has been [covered many times in previous issues](https://github.com/snipe/snipe-it/search?q=only+supported+ciphers&type=issues) and [is covered in the documentation](https://snipe-it.readme.io/docs/installation-issues#on-composer-install-the-only-supported-ciphers-are-aes-128-cbc-and-aes-256-cbc-with-the-correct-key-lengths). It is generally considered good etiquette to read the documentation and search for your issue in the repo so as not to re-invent the wheel and/or waste people's time. 

Make sure to check your APP_KEY in your .env. It should look something like this:

`APP_KEY=base64:hTUIUh9CP6dQx+6EjSlfWTgbaMaaRvlpEwk45vp+xmk=`

**Comment by manojmj94** [comment]
--
   UnexpectedValueException  : The stream or file "/var/www/html/snipe-it/storag                                                                                                             e/logs/laravel.log" could not be opened in append mode: failed to open stream: P                                                                                                             ermission denied

  at /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHan                                                                                                             dler.php:111
    107|             restore_error_handler();
    108|             if (!is_resource($this->stream)) {
    109|                 $this->stream = null;
    110|
  > 111|                 throw new \UnexpectedValueException(sprintf('The stream                                                                                                              or file "%s" could not be opened in append mode: '.$this->errorMessage, $this->                                                                                                             url));
    112|             }
    113|         }
    114|
    115|         if ($this->useLocking) {

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/Abstract                                                                                                             ProcessingHandler.php:42

  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php:317

**Comment by manojmj94** [comment]
can help on this pls

**Comment by manojmj94** [comment]
hi any one pls help on update i revert back to old.pls let me know the proper step on installation.

**Comment by manojmj94** [comment]
or share a good old chat ,v4.6.4. The latest version is v5.3.7.

**Comment by manojmj94** [comment]
hi anyone pls

**Comment by uberbrady** [comment]
https://snipe-it.readme.io/docs/debugging-permissions

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/debugging-permissions">Debugging Server Permissions</a></strong></div><div>One of the most common issues folks newer to running web servers run into is how to manage the Linux/Windows/etc owners and groups of the Snipe-IT filesystem. As we mention many times in the installation documentation, nothing in Snipe-IT should be run as or owned by root. Running composer as root, ...</div></blockquote>

**Comment by JonathonReinhart** [comment]
@snipe Your patience is incredible :grinning:

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
