### ISSUE TITLE
IP Address Management feature

### ISSUE THREAD

**Issue by jonnythelarge** [grokability/snipe-it#10589]
### Snipe-IT Version

 Version v5.3.7 - build 6587 (master) - Hosted

### Operating System

Windows

### Web Server

Hosted

### PHP Version

Hosted

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Not related to a problem.

### Describe the solution you'd like A clear and concise description of what you want to happen.

Currently using license section of Snipe IT for IP address management to track our Subnet usage across our internal infrastructure. It would be very benficial to have an IP address Tracker/managmenet section

Subnet
Mask
Gateway
CIDR
IP addresses in use maybe even ability to add hosts to fixed IP addresses 

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Using the license section to facilitate temporarily 

### Additional context Add any other context or screenshots about the feature request here.

Thank you so much for your ongoing support.

**Comment by Elma-mc-Bong** [comment]
I think you are looking for [Netbox](https://github.com/netbox-community/netbox).

**Comment by JonathonReinhart** [comment]
I second the Netbox suggestion. It is everything you want and then some.

Snipe-IT is an asset tracker, which is related but has very different goals. Snipe-IT will never be an IPAM, and Netbox will never be an asset tracker. The key is effectively using them in tandem, which I am looking to improve. (Specifically, I would like custom asset tracker links in NetBox based on the asset tag field, but you can always just drop a link in the notes section.)

**Comment by Elma-mc-Bong** [comment]
You are right the key is a link between the two systems. Netbox have the option to define custom links.

![image](https://user-images.githubusercontent.com/11978923/152479899-11fbfb26-d628-43a4-9841-3612c358191e.png)

https://demo.netbox.dev/static/docs/customization/custom-links/

<blockquote><div><strong><a href="https://demo.netbox.dev/static/docs/customization/custom-links/">Custom Links - NetBox Documentation</a></strong></div></blockquote>

**Comment by JonathonReinhart** [comment]
@Elma-mc-Bong Thanks, I guess I forgot that existed and never went about configuring it! I can't wait to try this out.

**Comment by JonathonReinhart** [comment]
@Elma-mc-Bong This works so well! Thanks for the tip!

For anyone who stumbles across this, here's how I configured the custom link:
- **Content type:** `DCIM > device`
- **Name:** `Device: Asset Tracker`
- **Link Text**: `{% if obj.asset_tag %}View in Asset Tracker{% endif %}`
- **Link URL**: `https://assets.example.com/hardware/bytag?assetTag={{ obj.asset_tag }}`
