### ISSUE TITLE
Option to choose company when creating an asset is greyed out

### ISSUE THREAD

**Issue by gurpal-rattu** [grokability/snipe-it#10603]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to create a new asset, accessory, etc. the company line is greyed out. When the asset is created it's being added to our default company and there doesn't seem to be any way to change that.

### Reproduction steps

1. Select Create New > Asset

### Expected behavior

To be able to choose whichever company I'd like my inventory to be under.

### Screenshots

![Screenshot 2022-02-02 100206](https://user-images.githubusercontent.com/98908174/152211359-a9753e93-106c-4ffd-80d3-ea4338ca23ed.png)

### Snipe-IT Version

5.3.7

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

2.7.4

### Operating System

Windows 10

### Browser

Chrome

### Version

97

**Comment by snipe** [comment]
If company is greyed out, the currently logged in user does not have permission to change something’s company.

https://github.com/snipe/snipe-it/blob/8add47739e7f6a13ba1ee6c37a3d55cb688bacce/resources/views/partials/forms/edit/company.blade.php#L1-L11

**Comment by gurpal-rattu** [comment]
Thanks, I'll look into setting up the permissions properly.

**Comment by gurpal-rattu** [comment]
Even after enabling the permissions for my admin account I'm still unable to import accessories from a csv file. It seems like the admin permissions, even when saved, aren't actually registering and I need a superadmin account to be able to set the permissions. 

After looking at your documentation I don't see any way to create a superadmin, so how do I go about doing that?

**Comment by snipe** [comment]
You shouldn't need to be an admin to import. I don't really know what "unable to import" means. Are you seeing an error, what's actually happening when you try? Also, you have your PHP version listed as 2.7.4, which I'm pretty sure isn't correct, since that's from the late 1990s 😁  I assume you mean 7.4.2?

**Comment by gurpal-rattu** [comment]
You're correct, 7.4, not 2.7.4. Well, when I run the importer tool it says that the import was successful. However, when I go to check our list of accessories I don't see the devices that were in my csv file.

![image](https://user-images.githubusercontent.com/98908174/152436263-8b3974b8-c504-48ec-beed-54388375c124.png)

I'm not really sure what I need to do to make my items populate besides adding everything manually, one by one.

**Comment by snipe** [comment]
Okay, so not a permissions issue then. If it were a permissions issue, you'd see a forbidden error, and it wouldn't let you even upload the file, let alone try to import it.

Unfortunately, I don't really know how to troubleshoot this, since there are no actual errors.

**Comment by gurpal-rattu** [comment]
Was able to get a super admin account created using the command line tool.
