### ISSUE TITLE
READ Only access doesn`t display all assets for users

### ISSUE THREAD

**Issue by rvidhy** [grokability/snipe-it#10608]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Whilst creating a read only group and when users are assigned to read only  group the user is not able to see any assets unless granted super user access.

### Reproduction steps

1.creating a read only group
2. Assigning read only permissions
3. User not able to see assets
...

### Expected behavior

User is supposed to visualise the assets while read only or view access given to the user.

### Snipe-IT Version

 Version v5.2.0 - build 6339 (master)

### Operating System

Windows server

### Web Server

Xaampp

### PHP Version

7.4.23

### Operating System

Windows

### Browser

Google chrome

**Comment by snipe** [comment]
> Whilst creating a read only group

I'm not sure exactly what this means. Also please clarify if you have Full Company Support enabled and whether or not your read-only user is assigned to any companies.

**Comment by rvidhy** [comment]
[image: image.png]



After creating a read only group with just view permissions given to that
group and when users are added to that group they are not able to view any
assets.

[image: image.png]

SUper user permissions can view the assets
[image: image.png]

But when read only user is assigned no assets are visible to that user.

[image: image.png]

**Comment by rvidhy** [comment]
After creating a read only group with just view permissions given to that group and when users are added to that group they are not able to view any assets.
![image](https://user-images.githubusercontent.com/83179963/152478087-06b19ec8-749a-4db1-a5aa-4d2e9aeeca9e.png)

SUper user permissions can view the assets
![image](https://user-images.githubusercontent.com/83179963/152478125-7f8b8161-118f-4b2f-92f0-59a27ec8c067.png)
![image](https://user-images.githubusercontent.com/83179963/152478147-29d9ba37-b394-4945-8736-071e7d2be6c0.png)

But when read only user is assigned no assets are visible to that user.
![image](https://user-images.githubusercontent.com/83179963/152478156-7f0a2a43-c062-4cd4-ad19-8328faaa75e2.png)

**Comment by snipe** [comment]
Only superusers can see the dashboard at all, so I'm not even sure how that screen would be loading for you with that user.

**Comment by snipe** [comment]
Or at they admins? Do you have Full Multiple Company Support enabled in settings? If so, admins are constrained by those companies.
