### ISSUE TITLE
Add custom fields to manufacture? 📱⌨🖥

### ISSUE THREAD

**Issue by onthecouch** [grokability/snipe-it#10612]
### Snipe-IT Version

5.3.8

### Operating System

Windows

### Web Server

IIS

### PHP Version

 7.4.27

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

hi, I just discovered this programs and its awesome. One thing that "kinda" bother me is, can you add custom fields in manufacture pages?
say, I have Brand A monitors asset, on the other hand I have Brand A handphone asset. 

### Describe the solution you'd like A clear and concise description of what you want to happen.

So instead create new manufactures for separate asset from same brands, how about add new custom fields in there? More like type fields in manufactures. I know its kinda complicated to make that, but that's just my idea, pardon if this already asked before

**Comment by ccj9874** [comment]
What would be an example of this? I'm trying to understand what the difference between manufacturer and brand is. I do Manufacturer (company) -> model line/name -> model number -> Category
Example: Dell OptiPlex 7010, Desktop category

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
