### ISSUE TITLE
6.0 R2 - Class 'Adldap\Adldap' not found

### ISSUE THREAD

**Issue by flawzies** [grokability/snipe-it#10615]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Trying to Sync LDAP users.

Error
Class 'Adldap\Adldap' not found
http://*.com/users/ldap

App\Services\LdapAd::init
C:\inetpub\wwwroot\Snipe-IT\app\Services\LdapAd.php:100

### Reproduction steps

1. Sync LDAP users
2. 500 Server Error

### Expected behavior

Fetching users

### Snipe-IT Version

6.0 R2

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.13

### Error messages

```shell
if ($this->ldap) {

            return true;

        }


        parent::init();

        if($this->isLdapEnabled()) {

            if($this->ldapSettings['is_ad'] == 0 ) { //only for NON-AD setups!

                $this->ldapConfig['account_prefix'] = $this->ldapSettings['ldap_auth_filter_query'];

                $this->ldapConfig['account_suffix'] = ','.$this->ldapConfig['base_dn'];

            } /*

            To the point mentioned in ldapLogin(), we might want to add an 'else' clause here that

            sets up an 'account_suffix' of '@'.$this->ldapSettings['ad_domain'] *IF* the user has

            $this->ldapSettings['ad_append_domain'] enabled.

            That code in ldapLogin gets simplified, in exchange for putting all the weirdness here only.

            */

            $this->ldap = new Adldap();

            $this->ldap->addProvider($this->ldapConfig);

            return true;

        }

        return false;

    }

 

    public function __construct() {

        $this->init();

    }

 

        /**

     * Create a user if they successfully login to the LDAP server.

     *

     * @author Wes Hulette <jwhulette@gmail.com>

     *
```

**Comment by uberbrady** [comment]
v6 no longer uses AdLdap2 - you should be able to do `composer install` - does the problem then go away? Might need to clear some caches too.

**Comment by flawzies** [comment]
Composer runs fine. Wherafter I clear cache I keep getting

php artisan config:clear
`  Class 'Adldap\Adldap' not found

  at C:\inetpub\wwwroot\Snipe-IT\app\Services\LdapAd.php:100
     96▕             sets up an 'account_suffix' of '@'.$this->ldapSettings['ad_domain'] *IF* the user has
     97▕             $this->ldapSettings['ad_append_domain'] enabled.
     98▕             That code in ldapLogin gets simplified, in exchange for putting all the weirdness here only.
     99▕             */
  ➜ 100▕             $this->ldap = new Adldap();
    101▕             $this->ldap->addProvider($this->ldapConfig);
    102▕             return true;
    103▕         }
    104▕         return false;

  1   C:\inetpub\wwwroot\Snipe-IT\app\Services\LdapAd.php:108
      App\Services\LdapAd::init()

  2   [internal]:0
      App\Services\LdapAd::__construct()
`

**Comment by snipe** [comment]
Try `composer dump-autoload` as well

**Comment by flawzies** [comment]
> Try `composer dump-autoload` as well

Thanks. Sadly, it didn't help. I'll try a fresh install.
