### ISSUE TITLE
The DELETE method is not supported for this route. Supported methods: GET, HEAD.

### ISSUE THREAD

**Issue by King-GO** [grokability/snipe-it#10619]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

after php upgrade.php (5.3.7 to 5.3.8) and get the 'Whoops, looks like something went wrong' (I've done so many times to upgrade the system (...>5.3.1>5.3.2>5.3.3>5.3.4>5.3.5>5.3.6>5.3.7), but this is my first time to encounter)
xampp 7.3.12
php version 7.3.2

try to debug mode, and get
```
Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
The DELETE method is not supported for this route. Supported methods: GET, HEAD.
```
```
Application frames (6) All frames (36)
25
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\PreventBackHistory.php23
23
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\SecurityHeaders.php26
19
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\CheckForDebug.php25
17
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\CheckForSetup.php26
7
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\NoSessionStore.php27
0
Illuminate\Foundation\Http\Kernel handle
…\public\index.php58
```
try 
`php artisan optimize:clear`
and 
`php artisan route:clear`

Object not found! (URL reindirect to ../login)

### Reproduction steps

php upgrade.php

### Expected behavior

Successfully upgraded as usual.

### Snipe-IT Version

5.3.7

### Operating System

Windows

### Web Server

XAMPP

### PHP Version

7.3.2

**Comment by King-GO** [comment]
[found the solution](https://github.com/snipe/snipe-it/issues/10577#issuecomment-1030695051)

**Comment by uberbrady** [comment]
Ah, excellent - we have another fix coming up soon that will allow you to retain the 'secure hosts' setting, so long as your `APP_URL` in your `.env` is correct - keep an eye out for that.
