### ISSUE TITLE
v6.0.0-RC-1 - Checkin/checkout APIs broken

### ISSUE THREAD

**Issue by JonathonReinhart** [grokability/snipe-it#10614]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

See https://github.com/snipe/snipe-it/commit/14ac7a21819af1184dd73535d3fe648d7daeb7be#r66065159

### Reproduction steps

POST to `/api/v1/hardware/1/checkout`

405 Method Not Allowed

### Expected behavior

Not 405

### Snipe-IT Version

v6.0.0-RC-2-20-gb06642269

### Operating System

Docker

### Web Server

Apache (docker)

### PHP Version

7.4 (docker)

Discovered while working on #10552

**Comment by inietov** [comment]
Thanks for the report @JonathonReinhart 
I looked at the routes on this file and no other route looks wrong that I can identified. Gonna keep looking trough other route files in the system, but if you find something else that looks funny or plainly doesn't work we would be grateful if you also open an issue. Thank you!!!
