### ISSUE TITLE
Inconsistencies between checkout/checkin dates on asset history and activity log

### ISSUE THREAD

**Issue by JonathonReinhart** [grokability/snipe-it#10627]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

There are two closely-related problems here:
1. The dates shown for checkin/checkout differ between the **asset history** (`/hardware/123#history`) and the **activity report** (`/reports/activity`)
  - The **asset history** always shows the actual timestamp of the checkin/checkout, regardless of what was entered in the form. Whereas the **activity report** shows the user-provided date....
2. The **activity report** only shows user-provided *checkout* dates, but not user-provided *checkin* dates.

### Reproduction steps

1. Checkout an asset.
  - Date: `2019-06-01`
  - Comment: `Checkout with old date (2019-06-01)`
2. Checkin the asset
  - Date: `2019-06-02`
  - Comment: `Checkout with old date (2019-06-02)`
3. Observe asset history and see problem (1)
4. Observe activity report and see problem (2)

### Expected behavior

I would expect that the date entered by the user would be used, everywhere.

### Screenshots

Problem (1) -- Custom dates are not shown:  
![image](https://user-images.githubusercontent.com/1916566/152911721-949cec84-81f6-4b0a-adc5-d97a1b9f0703.png)

Problem (2) -- Custom date is shown, but only for checkout:  
![image](https://user-images.githubusercontent.com/1916566/152911771-bcf4f5ac-965a-41fa-a88c-0514630a9bb3.png)

### Snipe-IT Version

v6.0.0-RC2

### Operating System

Docker

### Web Server

Apache (docker)

### PHP Version

7.4 (docker)

### Additional context

Related comment where I first found this: https://github.com/snipe/snipe-it/issues/10552#issuecomment-1030744148

Related comment where @snipe was reviewing @inietov's PR: https://github.com/snipe/snipe-it/pull/6733#issuecomment-472702853

**Comment by JonathonReinhart** [comment]
Confirmed on v5.3.8 (via `snipe/snipe-it:v5.3.8` docker image) as well:

![image](https://user-images.githubusercontent.com/1916566/152913920-f321191f-187b-4ef7-b653-e8a551469f01.png)

![image](https://user-images.githubusercontent.com/1916566/152913966-a89c9ff9-cdb8-415d-aa5a-8b9a4a5a9177.png)

**Comment by snipe** [comment]
I feel like this has been addressed several times before, so I don’t know why we’re seeing this.

See:
https://github.com/snipe/snipe-it/commit/e621eaf456e311087d156bb0d10bb649e1453ea5
https://github.com/snipe/snipe-it/commit/ea1d7a42e2621837ad60ea31c499f3d46b5c99a4
https://github.com/snipe/snipe-it/pull/6733

**Comment by snipe** [comment]
@inietov - I know I’ve put a lot on your plate this week, but if you can look into this when you get a second. I’ve created a Shortcut for this (sc-18690)
