### ISSUE TITLE
Checkin API indicates success when it actually fails

### ISSUE THREAD

**Issue by JonathonReinhart** [grokability/snipe-it#10629]
### Describe the bug

A POST to `/api/v1/hardware/3/checkin` with invalid parameters returns this incorrect/inconsistent result (with status 200, unfortunately):
```json
{"status":"success","messages":"Asset was not checked in, please try again","payload":{"asset":"TEST-00003"}}
```

And the asset is not checked in (as confirmed via the web UI).

Not only is it not using HTTP return codes semantically (this [should return](https://stackoverflow.com/q/6123425) `400 Bad Request` or `422 Unprocessable Entity`), but it erroneously says "success" when it in fact failed.

Without parsing the human-readable `messages` field, this is indistinguishable from a successful result:
```json
{"status":"success","messages":"Asset checked in successfully.","payload":{"asset":"TEST-00003"}}
```

FWIW, it does that with an:
- Invalid `status_id`
- Invalid `location_id`

### Reproduction steps

1. POST to `/api/v1/hardware/{id}/checkin` with a `status_id` or `location_id` that does not correspond to a registered status or location.

### Expected behavior

Similar to https://github.com/snipe/snipe-it/issues/6633#issuecomment-1030574860, I would expect this to return a non-200 HTTP result code.

Barring that, I would expect:
```json
{"status": "error", ...}
```
e.g.
```json
{"status":"error","messages":"Asset was not checked in, please try again","payload":{"asset":"TEST-00003"}}
```

### Snipe-IT Version

v5.3.8

### Operating System

Docker

### Web Server

Apache (docker)

### PHP Version

7.4 (docker)

### Additional context

https://github.com/snipe/snipe-it/blob/v5.3.8/app/Http/Controllers/Api/AssetsController.php#L869

**Comment by JonathonReinhart** [comment]
I think this is the fix:
```diff
diff --git a/app/Http/Controllers/Api/AssetsController.php b/app/Http/Controllers/Api/AssetsController.php
index 80a9109ba..1478cce95 100644
--- a/app/Http/Controllers/Api/AssetsController.php
+++ b/app/Http/Controllers/Api/AssetsController.php
@@ -866,7 +866,7 @@ class AssetsController extends Controller
             return response()->json(Helper::formatStandardApiResponse('success', ['asset'=> e($asset->asset_tag)], trans('admin/hardware/message.checkin.success')));
         }
 
-        return response()->json(Helper::formatStandardApiResponse('success', ['asset'=> e($asset->asset_tag)], trans('admin/hardware/message.checkin.error')));
+        return response()->json(Helper::formatStandardApiResponse('error', ['asset'=> e($asset->asset_tag)], trans('admin/hardware/message.checkin.error')));
     }
 
 
```

**Comment by snipe** [comment]
Yeah that’s clearly a typo, since we use a `message.checkin.error` translation string. Can you open a PR? If not, no worries, we can handle it.

**Comment by JonathonReinhart** [comment]
> Can you open a PR?

Yes. Are you planning to continue maintaining 5.3.x for a while and put out any more 5.3.x releases with small bufixes / security updates?

Either way, I can base the fix on `v5.3.8` and then you'll be able to easily merge it into whichever branches you feel appropriate. Just let me know which branch(es) to target.

It looks like `master` is only a few commits ahead of `v5.3.8` so that seems to be appropriate for a bugfix target. I can send a second PR into `develop` if you'd like.

Finally, how would you feel about combining this PR with this other fairly trivial fix: https://github.com/snipe/snipe-it/issues/10552#issuecomment-1020423064

**Comment by snipe** [comment]
> Yes. Are you planning to continue maintaining 5.3.x for a while and put out any more 5.3.x releases with small bufixes / security updates?

That’s the plan, yeah. Small backports that don’t take a lot of time, and any major security issues that get discovered. 

Whatever version we land on in the 5.x strain, we’ll provide security updates for, but generally speaking would only be doing small bugfixes on. 

That said, fix it in one and we’ll fix it in both, either via merge, conflict resolution, or manual patch - on whatever branch you apply a PR to. 

We should probably be using a `422` (I think? Unprocessable entity?) in cases where the JSON you sent us was legitimately bad, at the request formatting level, not the data submission level - but that may be something we need to address only in v6 via the error handler.

**Comment by snipe** [comment]
> Finally, how would you feel about combining this PR with this other fairly trivial fix: https://github.com/snipe/snipe-it/issues/10552#issuecomment-1020423064

I’d prefer them to stay separate. Logging is tricksy business - but that’s not a hill I’m dying on.

**Comment by JonathonReinhart** [comment]
Okay, opened #10630, based on and targeting current `master`.
