### ISSUE TITLE
Serial Numbers Uniqueness

### ISSUE THREAD

**Issue by aledr** [grokability/snipe-it#10633]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The option "Settings -> General Settings -> Use Unique Serial Numbers" is not obeyed.

You can check on [Demo](https://demo.snipeitapp.com/components) and [Develop](https://develop.snipeitapp.com/components) that I inserted duplicated serial numbers.

Thanks.

### Reproduction steps

1 -  "Settings -> General Settings -> Use Unique Serial Numbers".
2 - Insert a duplicated Serial Number.

### Expected behavior

Unique Serial Numbers and prevent to insert duplicated ones.

### Snipe-IT Version

Master and Develop Branch

### Operating System

Demo Env

### Web Server

Demo Env

### PHP Version

Demo Env

**Comment by inietov** [comment]
I'm in the demo and I can't reproduce.
![image](https://user-images.githubusercontent.com/653557/153958147-30cdb9b5-6865-456f-a554-377444eeb286.png)

Also tested on my local instance and I got nothing, sorry :(. Any more details that you can share so I can test?

**Comment by aledr** [comment]
Please, check the Components page.
I need to track every single instance of a component (memory, power supply, adapter cards, ...).

![image](https://user-images.githubusercontent.com/47945/155649460-5fb1b940-e2ad-41af-b557-e200bea27143.png)

**Comment by snipe** [comment]
The serial uniqueness constraint does not cover components, only assets. “ Checking this box will enforce a uniqueness constraint on asset serials”

**Comment by aledr** [comment]
Thanks for the explanation.
