### ISSUE TITLE
Linear Depreciation Calculation

### ISSUE THREAD

**Issue by kelsen** [grokability/snipe-it#10639]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I believe that the linear depreciation calculation is not corret, at least from what I've read about here on Brazil.
There is a law here that says a computador depreciate 20% per year and has 5 years life-time.
So the months configured on depreciation should be taken account on the calculation.

### Reproduction steps

1. Create a 60 months depreciation on configuration menu.
2. Apply that depreciation to an asset model.
3. Create an asset and configure purchase date as 11/30/2019, purchased by $17.375,78.

### Expected behavior

Considering that today is 02/08/2022 which gives 27 months from puchase date.

The depreciation calc should be:
`R$17.375,78 - 20% / 5 (60 months) = R$2.780,1248/year = R$231,6770/month * 27 months = R$6.255,279`

But it's being calculated as follow:
`R$17.375,78 x 20% = R$3.475,156/year = R$289,5963/month * 27 months = R$7.819,101`

Perhaps this law does not apply to every country, but anyway, that months field on depreciation configuration shouldn't meant to be used by the calculation? 
So you could at least add an option to consider this months on calculation?

### Snipe-IT Version

v5.3.6 - build 6567 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.2.17

**Comment by snipe** [comment]
@Godmartinz want to take a look at this one?

**Comment by Godmartinz** [comment]
Will do!

**Comment by Godmartinz** [comment]
https://github.com/snipe/snipe-it/pull/10670

**Comment by snipe** [comment]
This is now on develop.

**Comment by uberbrady** [comment]
We had to back this out, as the math doesn't match what other countries are expecting for depreciation. If this algorithm is genuinely different, we would have to create it instead as a 'depreciation type' - but by my math, it's not quite right.

If we take the purchase cost as: $17,375.78 (please pardon my American punctuation!), the OP states that the per-year depreciation is: $2,780.1248 - but if you divide the purchase cost by the depreciation amount, you get: 6.25 years - which is not 60 months (5 years).

So I do not believe that math was correct in the first place. And if it is, we would need, instead, to create a new depreciation type to model it, I believe.
