### ISSUE TITLE
LDAP not sync to Snipe IT

### ISSUE THREAD

**Issue by junedtamboli** [grokability/snipe-it#10649]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello Team,

New created users are not syncing through LDAP to snipe IT.

Request you to please help on this issue if anyone is aware.

![Snipe IT LDAP](https://user-images.githubusercontent.com/51117404/153387472-8c8cabe8-a69e-4a51-bb4d-02cc690d0a62.PNG)

### Reproduction steps

1.Rejoined system in to domain.
2.
3.
...

### Expected behavior

New Created user not sync automatically.

### Snipe-IT Version

Version v5.1.8 - build 6227 (master)

### Operating System

Windows Server 2016 Standard

### Web Server

WAMP Server 3.1.7

### PHP Version

NA

### Operating System

Windows 10

### Browser

Firefox

### Version

97

### Error messages

```shell
While searching for new user throwing error No matching records found.
```

### Additional context

NA

**Comment by snipe** [comment]
We'd need a little more to work with than that. "LDAP not working" is not really a bug report. Tell us what you tried, what results you had from trying, any errors you ran into, what your settings look like, etc. 

![helpme-helpyou](https://user-images.githubusercontent.com/197404/153489233-517746c4-0591-41e5-adbb-05c1ce51241b.gif)

**Comment by flawzies** [comment]
The system won't automatically fetch new users from AD. You have to either sync them manually by using the "LDAP Sync" function on the user page. Or you could set up a scheduled task to run whenever you want.
`php artisan snipeit:ldap-sync {--location=} {--location_id=} {--summary}
`
https://snipe-it.readme.io/docs/ldap-sync

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/ldap-sync">LDAP Sync</a></strong></div><div>You can set up a cron to automatically sync LDAP users using the following: location and location_id are optional. So for example, if you know the location_id of the location you're trying to add the users to, you could use: Or if you know the name of the location, you could use: See the full docume...</div></blockquote>

**Comment by junedtamboli** [comment]
Hi Snipe/Snipe-It,

When we create a new User on AD, it's not sync with LDAP on snipe IT.
Please find attached snapshot and please let me know what need to be check
on snipe-it.

Thanks
Juned Tamboli
+918329725925

**Comment by snipe** [comment]
There was nothing attached. What happens when you try to sync? DIs there anything in your error logs?

**Comment by junedtamboli** [comment]
Hi,

Please find attachment again I have added.
Can we have a remote session to check this issue.

Thanks & Regards
Juned Tamboli

**Comment by junedtamboli** [comment]
Hi,

I have checked on this URL https://snipe-it.readme.io/docs/ldap-sync-login.
I am not able to Test LDAP. Please find the attached error.

Thank you
Juned Tamboli

**Comment by junedtamboli** [comment]
Hello Team,

Can you please look into this issue & help to resolve.

Thanks
Juned Tamboli

**Comment by flawzies** [comment]
> Hello Team, Can you please look into this issue & help to resolve. Thanks Juned Tamboli

Once again you're not attaching anything to GitHub when you're attaching something in your email client.

- LDAP Integration [X]
- Active Directory [X] This is an Active Directory server.
- Active Directory domain [ad-server.contoso.com]
- LDAP Server [ldap://ad-server.contoso.com]
- LDAP Bind Username [contoso\username]
- LDAP Bind Password [password]
- Base Bind DN [OU=GROUP,DC=contoso,DC=com] - Optional.
- LDAP Filter [(&(objectCategory=person)(objectClass=user)(!(objectClass=inetOrgPerson))(!(title=Resource))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))] - This is opional. Excludes users with resource in the title. Create your own LDAP Query using Active Directory Admin Center, for example.

Make sure you save your settings **before** you Test LDAP Synchronization.
If this does not work. The LDAP Binding account does not have read permissions. 
Or you are unable to reach the domain controller.

**Comment by junedtamboli** [comment]
![LDAP Test Error](https://user-images.githubusercontent.com/51117404/153637258-122832c0-b158-4277-add8-b96bbd66415c.PNG)


Please find attached error.

**Comment by junedtamboli** [comment]
Error Attached on Github also

**Comment by flawzies** [comment]
> ![LDAP Test Error](https://user-images.githubusercontent.com/51117404/153637258-122832c0-b158-4277-add8-b96bbd66415c.PNG)
> 
> Please find attached error.

![image](https://user-images.githubusercontent.com/76649917/153638526-2e020678-14d3-453e-8c5e-23a5a74e0a6c.png)

Does the **SYNC** function work? You're testing the **login** function itself. That's not entirely relevant to just syncing your user catalogue. Step one is to make LDAP find users correctly. Then you need to setup the correct auth methods in order to make the actual login work.

**Comment by avielc** [comment]
@junedtamboli - I'll just chime in here. 
I've set it up from scratch first time, and it was a very smooth process to get this AD set up working. 
Unless something in your settings is very wrong it won't work. 
So I suggest help @snipe help you by providing more information, what did you input in your AD settings, (you can remove or make a gibberish of anything confidential) but without that basic info, no one can help you or compare any settings to yours.

**Comment by junedtamboli** [comment]
Hi,

1.I have reset Password for LDAP account & create a new user on AD.
2.User is sync automatically.
3.But now when I create a user on AD  & search for new user. Its not sync.

Please let me know what steps should I take for Troubleshooting.

**Comment by avielc** [comment]
@junedtamboli - when you push the "LDAP SYNC" button in the UI, does the user get synced in? 
If it does, then it means you need to set up a sync schedule, I just did a cron job for that to sync every few minutes

**Comment by junedtamboli** [comment]
I Have scheduled on Asset Tracker but still it is not working

**Comment by avielc** [comment]
Never thought you can sync assets from ldap
Only users

**Comment by junedtamboli** [comment]
Hi,

I am not syncing Assets.
I am syncing users only.

**Comment by avielc** [comment]
> I Have scheduled on Asset Tracker but still it is not working

I understood you scheduled Assets. 
in any case, if your ldap settings are working, and if you press the LDAP SYNC button on the people page. 
then simply running 
`php artisan snipeit:ldap-sync --summary > /dev/null` - (you might need to fix path and such) but if this works through command line, then just cron it, and it'll work.

**Comment by junedtamboli** [comment]
Hi,

I run this command from exact location, command completed successfully.
But when I try to search user on Snipe IT, user not sync.

As per my troubleshooting, I am facing an issue with particular OU
Please advice if you can help on this.

**Comment by snipe** [comment]
Hi there - Pretty sure this has been working for a long time now, sorry for not closing this sooner. I'm going to close this. Please feel free to open a new issue if you're still having trouble.
