### ISSUE TITLE
Error displaying employee code

### ISSUE THREAD

**Issue by ShinChill** [grokability/snipe-it#10659]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Unable to display employee code item name

### Reproduction steps

1.  Version v6.0.0-RC2 - build 6627 (develop) 

### Expected behavior

This is a common display error, I went to snipeIT's demo page, still the same

### Screenshots

![image](https://user-images.githubusercontent.com/87417467/153539480-98641dac-6b65-41ba-bd44-490e1c3c534a.png)

### Snipe-IT Version

 Version v6.0.0-RC2 - build 6627 (develop)

### Operating System

Centos

### Web Server

Apache

### PHP Version

7.4

### Operating System

Windows 10

### Browser

Google Chrome

**Comment by snipe** [comment]
> Unable to display employee code item name

Can you clarify? I don't understand what an "employee code item name" is here.

**Comment by snipe** [comment]
Ah, you mean the translation string for Employee number.

**Comment by huynhvinh12** [comment]
> Ah, you mean the translation string for Employee number.

Yup , It doesn't show Employee No.
