### ISSUE TITLE
Column not found: 1054 Unknown column '' in 'where clause' at /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18

### ISSUE THREAD

**Issue by aminoacidity** [grokability/snipe-it#10658]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Post upgrade to 5.3.8 the asset list page does not show any records. Dashboard asset list count is non zero.

### Reproduction steps

1. Updated to 5.3.8 from 5.3.7
2. Clear browser cache
3. Navigate to asset in after log in.
...

### Expected behavior

Show all assets in the asset list page.

### Screenshots

![dashboard](https://user-images.githubusercontent.com/55798550/153538384-02855fd2-ce7d-43ad-a205-e09aeef090fe.jpg)
![assetlist](https://user-images.githubusercontent.com/55798550/153538386-2404edc8-5336-4bb8-9707-5312c98245f8.jpg)

### Snipe-IT Version

5.3.8

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows 11

### Browser

Chrome

### Version

98

### Error messages

```shell
[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' at /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79)
[stacktrace]
#0 /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(79): PDO->prepare()
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(331): Doctrine\\DBAL\\Driver\\PDOConnection->prepare()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\\Database\\Connection->select()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2147): Illuminate\\Database\\Query\\Builder->runSelect()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2619): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2148): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2546): Illuminate\\Database\\Query\\Builder->get()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2474): Illuminate\\Database\\Query\\Builder->aggregate()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1385): Illuminate\\Database\\Query\\Builder->count()
#12 /var/www/snipeit/app/Http/Controllers/Api/AssetsController.php(190): Illuminate\\Database\\Eloquent\\Builder->__call()
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\AssetsController->index()
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#23 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#24 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#28 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#30 /var/www/snipeit/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\PreventBackHistory->handle()
#32 /var/www/snipeit/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\SecurityHeaders->handle()
#34 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /var/www/snipeit/app/Http/Middleware/CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForDebug->handle()
#38 /var/www/snipeit/app/Http/Middleware/CheckForSetup.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForSetup->handle()
#40 /var/www/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#42 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#44 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#46 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#48 /var/www/snipeit/app/Http/Middleware/NoSessionStore.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\NoSessionStore->handle()
#50 /var/www/snipeit/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle()
#52 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#54 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#55 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle()
#56 {main}
"}
[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' at /var/www/
```

**Comment by uberbrady** [comment]
This may sound like a long shot, but what's your `APP_URL`? Does it match the URL as displayed in the URL bar in your browser, exactly? And/or what happens when you set `APP_ALLOW_INSECURE_HOSTS` to `true`?

The reason I ask is because the only real big thing that changed between those two versions is that, which is an annoying change we had to make for security reasons...

**Comment by snipe** [comment]
Try upgrading to latest on master. I believe this was fixed already.

**Comment by aminoacidity** [comment]
Performed upgrade to latest version 5.3.10 build 6684. Still empty.

> This may sound like a long shot, but what's your `APP_URL`? Does it match the URL as displayed in the URL bar in your browser, exactly? And/or what happens when you set `APP_ALLOW_INSECURE_HOSTS` to `true`?
> 
> The reason I ask is because the only real big thing that changed between those two versions is that, which is an annoying change we had to make for security reasons...

App URL is null and I set the APP_ALLOW_INSECURE_HOSTS to true. it still did not work.

**Comment by aminoacidity** [comment]
`[2022-02-22 12:57:10] production.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select count(*) as aggregate from `assets` where `` = ? and `assets`.`deleted_at` is null) {"userId":345,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select count(*) as aggregate from `assets` where `` = ? and `assets`.`deleted_at` is null) at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669) `


Error is more specific now

**Comment by snipe** [comment]
Missing columns almost always means you need to run migrations.

**Comment by aminoacidity** [comment]
> Missing columns almost always means you need to run migrations.
```
snipeit@SCN01:/var/www/snipeit$ php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Nothing to migrate.
```

**Comment by cykole** [comment]
Hi there, got the exact same issue & error as @aminoacidity. Also upgraded to latest release and migration was telling me nothing to migrate. Hoping for an advice

**Comment by aminoacidity** [comment]
@cykole Had rolled back using my vm snapshot. Today tried again and same as you it shows nothing to migrate but keeps throwing the same error.

**Comment by aminoacidity** [comment]
Performed a query dump but outputting the query before being prepared in vendor/laravel/framework/src/Illuminate/Database/Connection.php and got this. The where portion is missing a column name. Not sure where it's originating from though.

select count(*) as aggregate from `assets` where `` = ? and `assets`.`deleted_at` is null,

**Comment by snipe** [comment]
If you're still on v5, I'd suggest you try upgrading to v6.

**Comment by aminoacidity** [comment]
On Version v6.0.1 - build 7750 (master)

also reran

php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Nothing to migrate.

**Comment by snipe** [comment]
There would definitely have been migrations from v5 to v6.

**Comment by aminoacidity** [comment]
Sorry,  I was not clear about it. I ran the php upgrade.php and there were migrations which ran successfully. 
The common issues area suggested I rerun the artisan migrate in case there were missed on migrations which I did and the output above is from that particular run.

**Comment by snipe** [comment]
Did you see any other errors when you ran the upgrader?

**Comment by snipe** [comment]
> App URL is null and I set the APP_ALLOW_INSECURE_HOSTS to true. it still did not work.

You fixed this, right? APP_URL cannot be null, [it should match the url you access the site from](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings).


<img width="812" alt="Screen Shot 2022-05-18 at 3 46 02 AM" src="https://user-images.githubusercontent.com/197404/169021638-1cdf812d-f7a3-468b-ad77-c78400a6b4ac.png">

**Comment by aminoacidity** [comment]
> > App URL is null and I set the APP_ALLOW_INSECURE_HOSTS to true. it still did not work.
> 
> You fixed this, right? APP_URL cannot be null, [it should match the url you access the site from](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings).
> 
> <img alt="Screen Shot 2022-05-18 at 3 46 02 AM" width="812" src="https://user-images.githubusercontent.com/197404/169021638-1cdf812d-f7a3-468b-ad77-c78400a6b4ac.png">

Hi,
Yes both APP_URL and APP_ALLOW_INSECURE_HOSTS settings are present. From where I have reached in debugging this situation it does seems like some portion of the migration did not run through and the prepare statement fails to add the column name and therefore ends with the `` in there where query. Is there any way I can create a fresh DB for 6.0.1 and then compare the two DBs for differences?

**Comment by aminoacidity** [comment]
Would also like to add that I am actually able to list licenses, bulk export all the assets etc. Seems to only show nothing and throws the error in the listing page.

**Comment by snipe** [comment]
Present and correct are not necessarily the same. Can you show me what your APP_URL is?

**Comment by aminoacidity** [comment]
APP_URL=http://192.168.188.92
APP_TIMEZONE='Asia/Singapore'
APP_LOCALE=en
MAX_RESULTS=500
APP_ALLOW_INSECURE_HOSTS=true

**Comment by aminoacidity** [comment]
![image](https://user-images.githubusercontent.com/55798550/169244600-998aa5a5-1424-40e1-8630-9d28568d0ef1.png)
![image](https://user-images.githubusercontent.com/55798550/169244672-ef68e005-190e-46c1-a5c5-53514b559428.png)
![image](https://user-images.githubusercontent.com/55798550/169244808-c4af161f-18c5-4143-bbe1-98a0819beeb5.png)

Have created a fresh installation with database temp and did a compare between my production snipeit db and the temp ones to see if there are differences. There are in 3 tables if that helps identify the issue.

**Comment by aminoacidity** [comment]
Figured it. Turns out the a particular custom field existed in custom_fields table that did not make it into assets table for some reason. Deleting that row from the custom_fields table fixed the issue and I could get listing.
