### ISSUE TITLE
ca-certificates verfication failed

### ISSUE THREAD

**Issue by mayesd** [grokability/snipe-it#10651]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am still trying to install on Unbuntu and get the error  unable to access 'https://github.com/snipe/snipe-it/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

Can anyone help?

### Reproduction steps

1. sudo git clone https://github.com/snipe/snipe-it .
2.
3.
...

### Expected behavior

To be able to download Snipe-IT into Unbuntu

### Snipe-IT Version

NA

### Operating System

Unbuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Unbuntu

**Comment by flawzies** [comment]
This is not tied to Snipe-it. Any git clone should give you the same issue. Google is your friend here :)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
