### ISSUE TITLE
500 Server Error while viewing assets

### ISSUE THREAD

**Issue by MattyHumphrey** [grokability/snipe-it#10650]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I try to view certain assets I get a server error 500. Once this happens there is no way to view the asset infomration. 
The only way I have found to get around this issue is copy the asset infomation and recreate it. 

### Reproduction steps

1.Search for an asset (this does not happen on every asset only certain ones) 
2.When the asset details is expected to open an error message appears saying server error 500.
3.
...

### Expected behavior

Asset to open as expected.

### Snipe-IT Version

v5.3.7

### Operating System

Windows server 2019

### Web Server

IIS

### PHP Version

7.4.20

### Operating System

Windows 10 

### Browser

Google Chrome

### Version

98.0.4758.82

### Error messages

```shell
Illuminate \ View \ ViewException (E_ERROR)
Call to a member function present() on null (View: D:\SnipeITSource\resources\views\hardware\view.blade.php)
Previous exceptions
Call to a member function present() on null (0)

Environment & details:
GET Data empty
POST Data empty
Files empty
Cookies
assetMaintenancesTable_bs_table_cardView	
"false"
assetHistory_bs_table_cardView	
"false"
assetsTable_bs_table_cardView	
"false"
assetFileHistory_bs_table_cardView	
"false"
usersTable_bs_table_pageNumber	
"1"
dashActivityReport_bs_table_cardView	
"false"
dashCategorySummary_bs_table_cardView	
"false"
assetsListingTable_bs_table_cardView	
"false"
asssetModelsTable_bs_table_cardView	
"false"
asssetModelsTable_bs_table_columns	
"["id","name","image","model_number","assets_count","eol","fieldset","actions"]"
asssetModelsTable_bs_table_pageNumber	
"1"
usersTable_bs_table_cardView	
"false"
asssetModelsTable_bs_table_pageList	
"1000"
categoryTable_bs_table_cardView	
"false"
categoryTable_bs_table_pageList	
"100"
categoryTable_bs_table_pageNumber	
"1"
asssetModelsTable_bs_table_sortName	
"assets_count"
asssetModelsTable_bs_table_sortOrder	
"desc"
assetsListingTable_bs_table_sortName	
"status_label"
assetsListingTable_bs_table_sortOrder	
"desc"
manufacturersTable_bs_table_cardView	
"false"
manufacturersTable_bs_table_pageNumber	
"1"
customFieldsetsTable_bs_table_cardView	
"false"
customFieldsTable_bs_table_cardView	
"false"
statuslabelsTable_bs_table_cardView	
"false"
usersTable_bs_table_searchText	
""
_ga	
"GA1.1.1049489137.1643013485"
_ga_9XKJTGM7MK	
"GS1.1.1643211221.4.0.1643211221.0"
assetsListingTable_bs_table_pageNumber	
"1"
locationTable_bs_table_cardView	
"false"
locationTable_bs_table_pageNumber	
"1"
locationTable_bs_table_searchText	
"asart"
manufacturersTable_bs_table_searchText	
"acer"
asssetModelsTable_bs_table_searchText	
"CSC 11821"
snipeit_session	
"MIieNCLRxsvlF2y5uBvRfHD6Gz494f6drzUD1Eqi"
assetsListingTable_bs_table_searchText	
"CSC18778"
laravel_token	
"eyJpdiI6IjJhODZvQ1wvRmxUY3I4R29CdnFxRWVBPT0iLCJ2YWx1ZSI6ImRWTEc4cW5jRlNWZEtKUDFxdTFwTlFHaUVMdStMRUlcLzNWTlNubmpNaU5OdDd6S1RPXC9RR1JZNG96MTZWbE9zb0RUcTlVbytua3cz ▶"
XSRF-TOKEN	
"eyJpdiI6InNHRnB6RTlJMkVrU2hueEZLeTAzQlE9PSIsInZhbHVlIjoiUFNnSW5oa0FOYk5XZkh1TCtyQ20ranBJamFpdHJrbDJ6TGJsSTlkdFRaWFVQM2VEN0xCMjA3clhRTEhuZGNhY2dhUlRJUW9vUzNZbk5M ▶"
Session empty
Server/Request Data
_FCGI_X_PIPE_	
"\\.\pipe\IISFCGI-89eb5a19-be8b-4b1e-bd28-0634292fd070"
PHPRC	
"D:\PHP\"
PHP_FCGI_MAX_REQUESTS	
"10000"
ALLUSERSPROFILE	
"C:\ProgramData"
APPDATA	
"C:\Windows\system32\config\systemprofile\AppData\Roaming"
APP_POOL_CONFIG	
"C:\inetpub\temp\apppools\SnipeIT\SnipeIT.config"
APP_POOL_ID	
"SnipeIT"
CommonProgramFiles	
"C:\Program Files\Common Files"
CommonProgramFiles(x86)	
"C:\Program Files (x86)\Common Files"
CommonProgramW6432	
"C:\Program Files\Common Files"
COMPUTERNAME	
"BEAMS02"
ComSpec	
"C:\Windows\system32\cmd.exe"
DriverData	
"C:\Windows\System32\Drivers\DriverData"
LOCALAPPDATA	
"C:\Windows\system32\config\systemprofile\AppData\Local"
NUMBER_OF_PROCESSORS	
"2"
OPENSSL_CONF	
"D:\PHP\extras\ssl\openssl.cnf"
OS	
"Windows_NT"
Path	
"C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft\Web  ▶"
PATHEXT	
".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
PROCESSOR_ARCHITECTURE	
"AMD64"
PROCESSOR_IDENTIFIER	
"Intel64 Family 15 Model 6 Stepping 1, GenuineIntel"
PROCESSOR_LEVEL	
"15"
PROCESSOR_REVISION	
"0601"
ProgramData	
"C:\ProgramData"
ProgramFiles	
"C:\Program Files"
ProgramFiles(x86)	
"C:\Program Files (x86)"
ProgramW6432	
"C:\Program Files"
PSModulePath	
"C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules"
PUBLIC	
"C:\Users\Public"
SystemDrive	
"C:"
SystemRoot	
"C:\Windows"
TEMP	
"C:\Windows\TEMP"
TMP	
"C:\Windows\TEMP"
USERDOMAIN	
"SUNDERLAND"
USERNAME	
"BEAMS02$"
USERPROFILE	
"C:\Windows\system32\config\systemprofile"
windir	
"C:\Windows"
ORIG_PATH_INFO	
"/index.php"
URL	
"/index.php"
SERVER_SOFTWARE	
"Microsoft-IIS/10.0"
SERVER_PROTOCOL	
"HTTP/1.1"
SERVER_PORT_SECURE	
"1"
SERVER_PORT	
"443"
SERVER_NAME	
"ams.educationpartnershipne.ac.uk"
SCRIPT_NAME	
"/index.php"
SCRIPT_FILENAME	
"D:\SnipeITSource\public\index.php"
REQUEST_URI	
"/hardware/2470"
REQUEST_METHOD	
"GET"
REMOTE_USER	
""
REMOTE_PORT	
"54809"
REMOTE_HOST	
"10.101.134.15"
REMOTE_ADDR	
"10.101.134.15"
QUERY_STRING	
""
PATH_TRANSLATED	
"D:\SnipeITSource\public\index.php"
LOGON_USER	
""
LOCAL_ADDR	
"10.101.110.41"
INSTANCE_META_PATH	
"/LM/W3SVC/2"
INSTANCE_NAME	
"SNIPEIT"
INSTANCE_ID	
"2"
HTTPS_SERVER_SUBJECT	
"C=GB, S=Sunderland, L=Sunderland, O=City of Sunderland College, OU=IT Services, CN=*.educationpartnershipne.ac.uk"
HTTPS_SERVER_ISSUER	
"C=BM, O=QuoVadis Limited, CN=QuoVadis Global SSL ICA G3"
HTTPS_SECRETKEYSIZE	
"4096"
HTTPS_KEYSIZE	
"256"
HTTPS	
"on"
GATEWAY_INTERFACE	
"CGI/1.1"
DOCUMENT_ROOT	
"D:\SnipeITSource\public"
CONTENT_TYPE	
""
CONTENT_LENGTH	
"0"
CERT_SUBJECT	
""
CERT_SERIALNUMBER	
""
CERT_ISSUER	
""
CERT_FLAGS	
""
CERT_COOKIE	
""
AUTH_USER	
""
AUTH_PASSWORD	
""
AUTH_TYPE	
""
APPL_PHYSICAL_PATH	
"D:\SnipeITSource\public\"
APPL_MD_PATH	
"/LM/W3SVC/2/ROOT"
IIS_UrlRewriteModule	
"7,1,1993,2351"
UNENCODED_URL	
"/hardware/2470"
IIS_WasUrlRewritten	
"1"
HTTP_X_ORIGINAL_URL	
"/hardware/2470"
HTTP_SEC_FETCH_DEST	
"document"
HTTP_SEC_FETCH_USER	
"?1"
HTTP_SEC_FETCH_MODE	
"navigate"
HTTP_SEC_FETCH_SITE	
"same-origin"
HTTP_UPGRADE_INSECURE_REQUESTS	
"1"
HTTP_SEC_CH_UA_PLATFORM	
""Windows""
HTTP_SEC_CH_UA_MOBILE	
"?0"
HTTP_SEC_CH_UA	
"" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98""
HTTP_USER_AGENT	
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36"
HTTP_REFERER	
"https://ams.educationpartnershipne.ac.uk/hardware"
HTTP_HOST	
"ams.educationpartnershipne.ac.uk"
HTTP_COOKIE	
"assetMaintenancesTable.bs.table.cardView=false; assetHistory.bs.table.cardView=false; assetsTable.bs.table.cardView=false; assetFileHistory.bs.table.cardView=fa ▶"
HTTP_ACCEPT_LANGUAGE	
"en-US,en;q=0.9"
HTTP_ACCEPT_ENCODING	
"gzip, deflate, br"
HTTP_ACCEPT	
"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
HTTP_CONTENT_LENGTH	
"0"
HTTP_CONNECTION	
"close"
FCGI_ROLE	
"RESPONDER"
PHP_SELF	
"/index.php"
REQUEST_TIME_FLOAT	
1644494624.0368
REQUEST_TIME	
1644494624
APP_ENV	
"production"
APP_DEBUG	
"true"
APP_KEY	
"base64:e34K8BOGm+nEzS2z32hR73+Q8Qm/1EbAmf6R+8X9L64="
APP_URL	
"https://ams.educationpartnershipne.ac.uk"
APP_TIMEZONE	
"UTC"
APP_LOCALE	
"en"
MAX_RESULTS	
"500"
PRIVATE_FILESYSTEM_DISK	
"local"
PUBLIC_FILESYSTEM_DISK	
"local_public"
DB_CONNECTION	
"mysql"
DB_HOST	
"127.0.0.1"
DB_DATABASE	
"SnipeIT"
DB_USERNAME	
"SnipeIT"
DB_PASSWORD	
"EpN3AM5DbU5eR"
DB_PREFIX	
"null"
DB_DUMP_PATH	
"D:\MariaDB\bin"
DB_CHARSET	
"utf8mb4"
DB_COLLATION	
"utf8mb4_unicode_ci"
DB_SSL	
"false"
DB_SSL_IS_PAAS	
"false"
DB_SSL_KEY_PATH	
"null"
DB_SSL_CERT_PATH	
"null"
DB_SSL_CA_PATH	
"null"
DB_SSL_CIPHER	
"null"
MAIL_DRIVER	
"smtp"
MAIL_HOST	
"smtp.office365.com"
MAIL_PORT	
"587"
MAIL_USERNAME	
"AMS@educationpartnershipne.ac.uk"
MAIL_PASSWORD	
"Snipe-IT01!"
MAIL_ENCRYPTION	
"TLS"
MAIL_FROM_ADDR	
"AMS@educationpartnershipne.ac.uk"
MAIL_FROM_NAME	
"EPNE Asset Management"
MAIL_REPLYTO_ADDR	
"AMS@educationpartnershipne.ac.uk"
MAIL_REPLYTO_NAME	
"EPNE Asset Management"
MAIL_AUTO_EMBED_METHOD	
"attachment"
IMAGE_LIB	
"gd"
MAIL_BACKUP_NOTIFICATION_DRIVER	
"null"
MAIL_BACKUP_NOTIFICATION_ADDRESS	
"null"
BACKUP_ENV	
"true"
SESSION_LIFETIME	
"30"
EXPIRE_ON_CLOSE	
"true"
ENCRYPT	
"false"
COOKIE_NAME	
"snipeit_session"
COOKIE_DOMAIN	
"null"
SECURE_COOKIES	
"false"
API_TOKEN_EXPIRATION_YEARS	
"15"
APP_TRUSTED_PROXIES	
"192.168.1.1,10.0.0.1"
ALLOW_IFRAMING	
"false"
REFERRER_POLICY	
"same-origin"
ENABLE_CSP	
"false"
CORS_ALLOWED_ORIGINS	
"null"
ENABLE_HSTS	
"false"
CACHE_DRIVER	
"file"
SESSION_DRIVER	
"file"
QUEUE_DRIVER	
"sync"
CACHE_PREFIX	
"snipeit"
REDIS_HOST	
"null"
REDIS_PASSWORD	
"null"
REDIS_PORT	
"null"
MEMCACHED_HOST	
"null"
MEMCACHED_PORT	
"null"
PUBLIC_AWS_SECRET_ACCESS_KEY	
"null"
PUBLIC_AWS_ACCESS_KEY_ID	
"null"
PUBLIC_AWS_DEFAULT_REGION	
"null"
PUBLIC_AWS_BUCKET	
"null"
PUBLIC_AWS_URL	
"null"
PUBLIC_AWS_BUCKET_ROOT	
"null"
PRIVATE_AWS_ACCESS_KEY_ID	
"null"
PRIVATE_AWS_SECRET_ACCESS_KEY	
"null"
PRIVATE_AWS_DEFAULT_REGION	
"null"
PRIVATE_AWS_BUCKET	
"null"
PRIVATE_AWS_URL	
"null"
PRIVATE_AWS_BUCKET_ROOT	
"null"
LOGIN_MAX_ATTEMPTS	
"5"
LOGIN_LOCKOUT_DURATION	
"60"
RESET_PASSWORD_LINK_EXPIRES	
"900"
APP_LOG	
"single"
APP_LOG_MAX_FILES	
"10"
APP_LOCKED	
"false"
APP_CIPHER	
"AES-256-CBC"
APP_FORCE_TLS	
"false"
GOOGLE_MAPS_API	
""
LDAP_MEM_LIM	
"500M"
LDAP_TIME_LIM	
"600"
IMPORT_TIME_LIMIT	
"600"
IMPORT_MEMORY_LIMIT	
"500M"
REPORT_TIME_LIMIT	
"12000"
Environment Variables
APP_ENV	
"production"
APP_DEBUG	
"true"
APP_KEY	
"base64:e34K8BOGm+nEzS2z32hR73+Q8Qm/1EbAmf6R+8X9L64="
APP_URL	
"https://ams.educationpartnershipne.ac.uk"
APP_TIMEZONE	
"UTC"
APP_LOCALE	
"en"
MAX_RESULTS	
"500"
PRIVATE_FILESYSTEM_DISK	
"local"
PUBLIC_FILESYSTEM_DISK	
"local_public"
DB_CONNECTION	
"mysql"
DB_HOST	
"127.0.0.1"
DB_DATABASE	
"SnipeIT"
DB_USERNAME	
"SnipeIT"
DB_PASSWORD	
"EpN3AM5DbU5eR"
DB_PREFIX	
"null"
DB_DUMP_PATH	
"D:\MariaDB\bin"
DB_CHARSET	
"utf8mb4"
DB_COLLATION	
"utf8mb4_unicode_ci"
DB_SSL	
"false"
DB_SSL_IS_PAAS	
"false"
DB_SSL_KEY_PATH	
"null"
DB_SSL_CERT_PATH	
"null"
DB_SSL_CA_PATH	
"null"
DB_SSL_CIPHER	
"null"
MAIL_DRIVER	
"smtp"
MAIL_HOST	
"smtp.office365.com"
MAIL_PORT	
"587"
MAIL_USERNAME	
"AMS@educationpartnershipne.ac.uk"
MAIL_PASSWORD	
"Snipe-IT01!"
MAIL_ENCRYPTION	
"TLS"
MAIL_FROM_ADDR	
"AMS@educationpartnershipne.ac.uk"
MAIL_FROM_NAME	
"EPNE Asset Management"
MAIL_REPLYTO_ADDR	
"AMS@educationpartnershipne.ac.uk"
MAIL_REPLYTO_NAME	
"EPNE Asset Management"
MAIL_AUTO_EMBED_METHOD	
"attachment"
IMAGE_LIB	
"gd"
MAIL_BACKUP_NOTIFICATION_DRIVER	
"null"
MAIL_BACKUP_NOTIFICATION_ADDRESS	
"null"
BACKUP_ENV	
"true"
SESSION_LIFETIME	
"30"
EXPIRE_ON_CLOSE	
"true"
ENCRYPT	
"false"
COOKIE_NAME	
"snipeit_session"
COOKIE_DOMAIN	
"null"
SECURE_COOKIES	
"false"
API_TOKEN_EXPIRATION_YEARS	
"15"
APP_TRUSTED_PROXIES	
"192.168.1.1,10.0.0.1"
ALLOW_IFRAMING	
"false"
REFERRER_POLICY	
"same-origin"
ENABLE_CSP	
"false"
CORS_ALLOWED_ORIGINS	
"null"
ENABLE_HSTS	
"false"
CACHE_DRIVER	
"file"
SESSION_DRIVER	
"file"
QUEUE_DRIVER	
"sync"
CACHE_PREFIX	
"snipeit"
REDIS_HOST	
"null"
REDIS_PASSWORD	
"null"
REDIS_PORT	
"null"
MEMCACHED_HOST	
"null"
MEMCACHED_PORT	
"null"
PUBLIC_AWS_SECRET_ACCESS_KEY	
"null"
PUBLIC_AWS_ACCESS_KEY_ID	
"null"
PUBLIC_AWS_DEFAULT_REGION	
"null"
PUBLIC_AWS_BUCKET	
"null"
PUBLIC_AWS_URL	
"null"
PUBLIC_AWS_BUCKET_ROOT	
"null"
PRIVATE_AWS_ACCESS_KEY_ID	
"null"
PRIVATE_AWS_SECRET_ACCESS_KEY	
"null"
PRIVATE_AWS_DEFAULT_REGION	
"null"
PRIVATE_AWS_BUCKET	
"null"
PRIVATE_AWS_URL	
"null"
PRIVATE_AWS_BUCKET_ROOT	
"null"
LOGIN_MAX_ATTEMPTS	
"5"
LOGIN_LOCKOUT_DURATION	
"60"
RESET_PASSWORD_LINK_EXPIRES	
"900"
```

**Comment by snipe** [comment]
Can you tell me anything more about how this data get into the database? This is usually a data issue. A full stack trace would be really helpful here.

**Comment by MattyHumphrey** [comment]
We put all the data in from an import.

**Comment by MattyHumphrey** [comment]
[previous exception] [object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function present() on null at D:\\SnipeITSource
\\storage\\framework\\views\\20d7ec86a97f89a2a9df2d9b635c270abcc2fe02.php:301)
[stacktrace]
#0 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php(43): include()
#1 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#2 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(143): Illuminate\\View\\Engines\\CompilerEngine->get()
#3 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(126): Illuminate\\View\\View->getContents()
#4 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(91): Illuminate\\View\\View->renderContents()
#5 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php(42): Illuminate\\View\\View->render()
#6 D:\\SnipeITSource\\vendor\\symfony\\http-foundation\\Response.php(205): Illuminate\\Http\\Response->setContent()
#7 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(749): Symfony\\Component\\HttpFoundation\\Response->__construct()
#8 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(721): Illuminate\\Routing\\Router::toResponse()
#9 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(681): Illuminate\\Routing\\Router->prepareResponse()
#10 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{
closure}()
#12 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#13 D:\\SnipeITSource\\app\\Http\\Middleware\\AssetCountForSidebar.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\AssetCountForSidebar->handle()
#15 D:\\SnipeITSource\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closur
e}()
#16 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#17 D:\\SnipeITSource\\app\\Http\\Middleware\\CheckForTwoFactor.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForTwoFactor->handle()
#19 D:\\SnipeITSource\\app\\Http\\Middleware\\CheckLocale.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckLocale->handle()
#21 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illumina
te\\Pipeline\\{closure}()
#22 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(
)
#23 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illumin
ate\\Pipeline\\{closure}()
#24 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle
()
#25 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipelin
e\\{closure}()
#26 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#27 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#29 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#30 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute()
#31 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#32 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#33 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http
\\{closure}()
#34 D:\\SnipeITSource\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}
()
#35 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#36 D:\\SnipeITSource\\app\\Http\\Middleware\\PreventBackHistory.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\PreventBackHistory->handle()
#38 D:\\SnipeITSource\\app\\Http\\Middleware\\SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\SecurityHeaders->handle()
#40 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illumi
nate\\Pipeline\\{closure}()
#41 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handl
e()
#42 D:\\SnipeITSource\\app\\Http\\Middleware\\CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForDebug->handle()
#44 D:\\SnipeITSource\\app\\Http\\Middleware\\CheckForSetup.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForSetup->handle()
#46 D:\\SnipeITSource\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#48 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\P
ipeline\\{closure}()
#49 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#50 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline
\\{closure}()
#51 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#52 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->
Illuminate\\Pipeline\\{closure}()
#53 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode-
>handle()
#54 D:\\SnipeITSource\\app\\Http\\Middleware\\NoSessionStore.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\NoSessionStore->handle()
#56 D:\\SnipeITSource\\vendor\\barryvdh\\laravel-cors\\src\\HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle()
#58 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#60 D:\\SnipeITSource\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRout
er()
#61 D:\\SnipeITSource\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle()
#62 {main}
"}

**Comment by snipe** [comment]
What's on line 301 of `D:\SnipeITSource
\storage\framework\views\20d7ec86a97f89a2a9df2d9b635c270abcc2fe02.php`?

**Comment by MattyHumphrey** [comment]
<?php echo e(\App\Helpers\Helper::getFormattedDateObject($audit_log->created_at, 'date', false)); ?> (by <?php echo e(link_to_route('users.show', $audit_log->user->present()->fullname(), [$audit_log->user->id])); ?>)

**Comment by MattyHumphrey** [comment]
" <?php echo e(\App\Helpers\Helper::getFormattedDateObject($audit_log->created_at, 'date', false)); ?> (by <?php echo e(link_to_route('users.show', $audit_log->user->present()->fullname(), [$audit_log->user->id])); ?>)"

**Comment by MattyHumphrey** [comment]
<?php echo e(\App\Helpers\Helper::getFormattedDateObject($audit_log->created_at, 'date', false)); ?> (by <?php echo e(link_to_route('users.show', $audit_log->user->present()->fullname(), [$audit_log->user->id])); ?>)

**Comment by snipe** [comment]
Update to latest on master. That means the user that did the auditing was deleted.
