### ISSUE TITLE
It'd be nice to email a user a list of all their assigned items (assets, licenses, accessories, etc.) via the user page.

### ISSUE THREAD

**Issue by tfremlev** [grokability/snipe-it#10667]
### Snipe-IT Version

5.1.5

### Operating System

Windows

### Web Server

MariaDB

### PHP Version

Docker

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Not a problem.

### Describe the solution you'd like A clear and concise description of what you want to happen.

I can refer to #4727 as this request has already been made, but was marked as stale and closed.
It's still a very nice feature to have.
Currently, the assigned assets must be printed (to pdf or physically on paper) and then e-mailed or handed to, to the respective user.
Add a feature to "send asset list to user" under "people".
An e-mail is already registrered to the user, so that's already taken care of.
I assume all that needs to be added, is some sort of service, where a sender-e-mail has to be accepted to be sent from (if for example it's a coorporate) or maybe an e-mail for this specific purpose could be used.

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Manual labour. Print to pdf and send from e-mail.

**Comment by bryceprutsos** [comment]
+1 for this

**Comment by mikeroq** [comment]
Just wanted to let you know this is now a feature!
![image](https://user-images.githubusercontent.com/55674383/178838839-6d50ce29-ce3a-4ee5-bcdd-d61bf5cdcfed.png)

https://demo.snipeitapp.com/users/1


<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/users/1">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by Techellan** [comment]
Hello everyone.
The content of the report created via the "Email List of All Assigned" option does not match the content of the report created via the "Print All Assigned" option. The report sent by email, among other things, does not contain a column with the serial number of the Asset.
Is it a feature or a bug?
Is there a configuration option to add items to the email report?
