### ISSUE TITLE
Upgrading with php upgrade.php - not working

### ISSUE THREAD

**Issue by Jurgens92** [grokability/snipe-it#10677]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,

I tried upgrading from v5.3.10 build 6684 to Latest V6 with Upgrade.php
Ubuntu Server 20.04

below is the console output

### Reproduction steps

snipe@snipe-it:/var/www/snipe-it$ php upgrade.php
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- check your PHP version and extension requirements
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (7.4.3) is at least 7.2.5 - continuing...
FYI: The php.ini used by this PHP is: /etc/php/7.4/cli/php.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

--
   UnexpectedValueException  : The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142|             restore_error_handler();
    143|             if (!is_resource($stream)) {
    144|                 $this->stream = null;
    145|
  > 146|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    147|             }
    148|             stream_set_chunk_size($stream, $this->streamChunkSize);
    149|             $this->stream = $stream;
    150|         }

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:48

  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php:327

  Please use the argument -v to see more details.

--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

--
   UnexpectedValueException  : The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142|             restore_error_handler();
    143|             if (!is_resource($stream)) {
    144|                 $this->stream = null;
    145|
  > 146|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    147|             }
    148|             stream_set_chunk_size($stream, $this->streamChunkSize);
    149|             $this->stream = $stream;
    150|         }

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:48

  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php:327

  Please use the argument -v to see more details.

--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
error: cannot open .git/FETCH_HEAD: Permission denied
fatal: Unable to create '/var/www/snipe-it/.git/index.lock': Permission denied
error: cannot open .git/FETCH_HEAD: Permission denied
-- -- --
--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ No bootsrap/cache/services.php, so nothing to delete.
√ No bootstrap/cache/config.php, so nothing to delete.

--
   UnexpectedValueException  : The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142|             restore_error_handler();
    143|             if (!is_resource($stream)) {
    144|                 $this->stream = null;
    145|
  > 146|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    147|             }
    148|             stream_set_chunk_size($stream, $this->streamChunkSize);
    149|             $this->stream = $stream;
    150|         }

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:48

  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php:327

  Please use the argument -v to see more details.
--
   UnexpectedValueException  : The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142|             restore_error_handler();
    143|             if (!is_resource($stream)) {
    144|                 $this->stream = null;
    145|
  > 146|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    147|             }
    148|             stream_set_chunk_size($stream, $this->streamChunkSize);
    149|             $this->stream = $stream;
    150|         }

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:48

  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php:327

  Please use the argument -v to see more details.
--
   UnexpectedValueException  : The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142|             restore_error_handler();
    143|             if (!is_resource($stream)) {
    144|                 $this->stream = null;
    145|
  > 146|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    147|             }
    148|             stream_set_chunk_size($stream, $this->streamChunkSize);
    149|             $this->stream = $stream;
    150|         }

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:48

  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php:327

  Please use the argument -v to see more details.
--
   UnexpectedValueException  : The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142|             restore_error_handler();
    143|             if (!is_resource($stream)) {
    144|                 $this->stream = null;
    145|
  > 146|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    147|             }
    148|             stream_set_chunk_size($stream, $this->streamChunkSize);
    149|             $this->stream = $stream;
    150|         }

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:48

  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php:327

  Please use the argument -v to see more details.

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
69 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Generated optimized autoload files containing 6148 classes

--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

   UnexpectedValueException  : The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142|             restore_error_handler();
    143|             if (!is_resource($stream)) {
    144|                 $this->stream = null;
    145|
  > 146|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    147|             }
    148|             stream_set_chunk_size($stream, $this->streamChunkSize);
    149|             $this->stream = $stream;
    150|         }

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:48

  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php:327

  Please use the argument -v to see more details.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

--
   UnexpectedValueException  : The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142|             restore_error_handler();
    143|             if (!is_resource($stream)) {
    144|                 $this->stream = null;
    145|
  > 146|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    147|             }
    148|             stream_set_chunk_size($stream, $this->streamChunkSize);
    149|             $this->stream = $stream;
    150|         }

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:48

  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php:327

  Please use the argument -v to see more details.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!
--------------------------------------------------------

snipe@snipe-it:/var/www/snipe-it$

### Expected behavior

Upgrade states successful but its still on the same version

### Snipe-IT Version

v5.3.10 build 6684

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Chrome

### Version

98.0.4758.82

**Comment by aranar-pro** [comment]
Looks like one or two permissions issues.  I think one is listed here: [Permission-issues](https://snipe-it.readme.io/docs/installation-issues#permission-issues) in the docs.  The other might be a user mismatch running git.  If you did sudo pull and are trying to update (which does a pull) as a user, you might see that.  Make sure your user can run git in the repo.  There are a few suggestions for that git permission error here: https://stackoverflow.com/questions/13195814/trying-to-git-pull-with-error-cannot-open-git-fetch-head-permission-denied. Hope this helps.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
