### ISSUE TITLE
Barcodes created with "Generate Labels" button are not readable with border

### ISSUE THREAD

**Issue by MWR-Napavine** [grokability/snipe-it#10678]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Within each asset page, there is a button to generate a label. Pressing this button will create a label based on the "Barcodes" and "Labels" settings.

Using the "Generate Label" button on the asset page does generate a printable label, but it is not readable with some barcode scanners. I believe this is due to the border put around the label, which interferes with the barcode from being read. Here is an example image that does not read:

![Barcode with Border](https://user-images.githubusercontent.com/48335860/154145878-b1272fbe-19f5-49aa-a9e8-a8d17137d7d4.PNG)

This seems to be reproduceable no matter which barcode type. I tested with 1D C39 and C128, Also with 2D QR Codes.

### Reproduction steps

1. Create an asset
2. Configure your Barcode and Label settings
3. Generate a code.
4. Attempt to read the code with a compatible barcode scanner.

### Expected behavior

I would expect that the labels would have options to include how much spacing around the barcode itself from the label border... or an option to not have a border at all.

### Snipe-IT Version

5.3.2

### Operating System

Hosted

### Web Server

Hosted

### PHP Version

7.3.23

### Operating System

Windows 10

### Browser

Google Chrome

### Version

98

**Comment by localzuk** [comment]
The margins around the contents of a label are determined by your settings in the Label Settings page, and the border is only shown onscreen, the border does not get printed.

**Comment by MWR-Napavine** [comment]
This is resolved.

On an earlier version of Snipe-IT (v5.3.something), I did try and print the label and it did print the border... But I just tried it again with the fresh v6.0.0... and it is working as intended. Thank you.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
