### ISSUE TITLE
Can't use uid as username in LDAP Configuration

### ISSUE THREAD

**Issue by haiz85** [grokability/snipe-it#10673]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I've been doing work around how to make uid work as username but everthing i tried different configuration on username file always coming back with error

### Reproduction steps

1. uid
2. uid=
3. uid=*
4. uid=samaccountname

### Expected behavior

Login username suppose to use username instead of full User Name itself

### Screenshots

Full LDAP Config
![snipe-ldap](https://user-images.githubusercontent.com/26559076/153971382-9208b7df-71e9-4a67-bf5f-5f9c99673de9.jpg)
Using CN for Login Test
![snipeit-cn](https://user-images.githubusercontent.com/26559076/153972470-624b4f30-c0a8-410f-bf00-000c53dfc53b.jpg)
Using UID for Login Test
![snipeit-uid](https://user-images.githubusercontent.com/26559076/153972477-515ce000-6998-478b-9505-60f119179870.jpg)

### Snipe-IT Version

5.3.10

### Operating System

docker

### Web Server

Apache??

### PHP Version

7.4

### Operating System

Windows 10

### Browser

Google Chrome

### Version

98

**Comment by uberbrady** [comment]
Based on your Filter setting, it looks like you're using Active Directory - but based on some of the other settings, it doesn't seem that way. What directory service are you using?

Just FYI you should absolutely be able to use `uid` as username **if** your directory actually supports binding that way.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
