### ISSUE TITLE
Please add RFID solutions

### ISSUE THREAD

**Issue by shortbus** [grokability/snipe-it#10684]
### Snipe-IT Version

5.3.10

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.0

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

RFID scanner and RFID tag integration

### Describe the solution you'd like A clear and concise description of what you want to happen.

I would like to use RFID tags to find inventory. The labels are great for telling what it is, but not WHERE it is.

**Comment by snipe** [comment]
I'm not sure what you mean by adding an RFID solution. Snipe-IT already works with NFC/RFID tags, depending on how you implement the data on those tags.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
