### ISSUE TITLE
Call to undefined method Auth::routes()

### ISSUE THREAD

**Issue by marchpr** [grokability/snipe-it#10696]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm getting a http 500 error. on the main page.

### Reproduction steps

1. Load page in browser.

### Expected behavior

Snipe-IT login page displays.

### Snipe-IT Version

5.3.10

### Operating System

Debian 11

### Web Server

Apache 2.4.52

### PHP Version

7.4.25

### Operating System

Windows 10

### Browser

Chrome

### Version

98

### Error messages

```shell
[2022-02-17 13:34:33] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Auth::routes() in /www/sites/snipeit/htdocs/snipeit/routes/web.php:469
Stack trace:
#0 /www/sites/snipeit/htdocs/snipeit/app/Providers/RouteServiceProvider.php(67): require()
#1 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(414): App\Providers\RouteServiceProvider->App\Providers\{closure}()
#2 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(374): Illuminate\Routing\Router->loadRoutes()
#3 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Routing\Router->group()
#4 /www/sites/snipeit/htdocs/snipeit/app/Providers/RouteServiceProvider.php(68): Illuminate\Support\Facades\Facade::__callStatic()
#5 /www/sites/snipeit/htdocs/snipeit/app/Providers/RouteServiceProvider.php(40): App\Providers\RouteServiceProvider->mapWebRoutes()
#6 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\RouteServiceProvider->map()
#7 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#9 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#10 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call()
#11 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(87): Illuminate\Container\Container->call()
#12 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(36): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 /www/sites/snipeit/htdocs/snipeit/app/Providers/RouteServiceProvider.php(28): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot()
#14 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\RouteServiceProvider->boot()
#15 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#17 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#18 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call()
#19 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Container\Container->call()
#20 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(839): Illuminate\Foundation\Application->bootProvider()
#21 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#22 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): array_walk()
#23 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#24 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#25 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\Foundation\Application->bootstrapWith()
#26 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Foundation\Http\Kernel->bootstrap()
#27 /www/sites/snipeit/htdocs/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#28 /www/sites/snipeit/htdocs/snipeit/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle()
#29 {main}
```

### Additional context

Fresh manual git clone install of Snipe-IT 5.3.10 on a Debian 11 box with Apache 2.4.52. I installed mariadb server, created a user and a database for Snipe-IT per documentation but otherwise I haven't touched the database. The only error I got was on the "composer install --no-dev --prefer-source" step which was this "Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping."

**Comment by snipe** [comment]
I don't have any idea why you'd be seeing that. The demos (and production customer instances) use the same code as what's in this repo and they seem to be fine. Did you run `php composer install`? Was this an upgrade?

**Comment by marchpr** [comment]
This was not an upgrade. I did run php compose install --no-dev --prefer-source

**Comment by snipe** [comment]
I still have no idea why you'd be seeing that. `Auth::routes()` is as old as time within this system. Can you try upgrading?

**Comment by marchpr** [comment]
I ran "php upgrade.php". I'm still getting the same Auth::routes() error. Here is the output from the upgrade command:
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER! 
--------------------------------------------------------

This script will attempt to: 

- check your PHP version and extension requirements 
- do a git pull to bring you to the latest version 
- run composer install to get your vendors up to date 
- run migrations to get your schema up to date 
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements: 
--------------------------------------------------------

Current PHP version: (7.4.25) is at least 7.2.5 - continuing... 
FYI: The php.ini used by this PHP is: /etc/php/7.4/cli/php.ini

Checking Required PHP extensions... 

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database: 
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Determining files to backup...
Zipping 50 files and directories...
Created zip containing 50 files and directories. Size is 27.31 KB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!


--------------------------------------------------------
STEP 3: Putting application into maintenance mode: 
--------------------------------------------------------

-- Application is now in maintenance mode.

--------------------------------------------------------
STEP 4: Pulling latest from Git (2 branch): 
--------------------------------------------------------

Git is installed. 
error: pathspec '2' did not match any file(s) known to git
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
-- No local changes to save
-- -- Already up to date.

--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ No bootsrap/cache/services.php, so nothing to delete.
√ No bootstrap/cache/config.php, so nothing to delete.

-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

√ Local composer.phar detected, so we'll use that.

-- Updating local composer.phar

You are already using the latest available Composer version 2.2.9 (stable channel).


Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
66 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Generated optimized autoload files containing 6033 classes

--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use 
your upgraded Snipe-IT!
--------------------------------------------------------

**Comment by marchpr** [comment]
When I run "php artisan serve" and then load the page from localhost:8000 I get the Snipe-IT Pre-Flight page. I'm guessing that suggests a problem with my Apache config.

**Comment by marchpr** [comment]
I think I've found the problem: a php_autoprepend_file that was interfering with Snipe-IT.
Apparently fixed by adding 2 lines to my Snipe-IT .htaccess file:

php_value auto_prepend_file none
php_value auto_append_file none

Good Lord, that was harder than it should have been.

**Comment by marchpr** [comment]
It looks like add the lines to .htaccess fixed the problem without interfering with the other domains running on the server. Closing issue.
