### ISSUE TITLE
Problems with CSV Import

### ISSUE THREAD

**Issue by taeys** [grokability/snipe-it#10709]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

So we've got a brand new SnipeIT instance, nothing there yet. And I wanted to test out the CSV Import to see if it does create all missing fields as promised. And when I tried I just got the error "error". Nothing more. Find attached the header of my CSV. Did I do anything wrong?
[snipeitheader.csv](https://github.com/snipe/snipe-it/files/8115316/snipeitheader.csv)
.

### Reproduction steps

1. Create CSV
2. Go To Import and Import it
3. Select Process and Press Import
4. Error
...

### Expected behavior

It works

### Snipe-IT Version

5.3.8

### Operating System

Ubuntu 18.04

### Web Server

Apache

### PHP Version

7.4.3

### Error messages

```shell
Airbus Inventarnummer: validation.import_field_empty
```

**Comment by taeys** [comment]
It works now.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)

**Comment by milinpatel16** [comment]
> works

Hi Taesy,
How did you resolve this issue?

**Comment by santhosh-velumani** [comment]
May I know the solution? I am getting the same error. Same situation for me, fresh installation and trying to import one .csv

**Comment by taeys** [comment]
You have to create the custom fields you are using first. I thought the import would also do this for me, but sadly it won't. So if you are using a custom field, let's say called "VLAN" in you CSV then you have to create the customfield "VLAN" in snipeit first.
