### ISSUE TITLE
API 401 Unauthorized (64bit php)

### ISSUE THREAD

**Issue by halvaldr** [grokability/snipe-it#10707]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hey,
I tried to find my issue in other topics, and I found something similar, but not quite, so please sorry if this is a duplication of an existing issue.

- Two weeks ago, 2022/02/02-10 I've installed a test node for Snipe-IT, full system details below. I've configured HTTP only, `.env` file set up accordingly, with no DNS records, bare IP address. On this system we did some testing, including API tests. Everythig went smoothly.
- On friday 2022/02/19 I've changed setup of the apache server to make the service accessible via DNS, so apache conf and .env file configuration, with `php artisan cache:clear` and `php artisan config:clear`. At this moment I tried to do basic smoke test without API test. Site worked ok
- Today, 2022/02/21 my colleague informed me API isn't working and throwing `"error": "Unauthorized or unauthenticated."`

There were multiple things I tried before writing this report, including checking the parameter `API_TOKEN_EXPIRATION_YEARS=15`, as hinted in [Common Issues](https://snipe-it.readme.io/docs/common-issues). I also checked the apache conf has `AllowOverride All` set, again no luck.
Bit frustrated, I tried to switch to nginx, I did that, in not so many words, with the same result (401 on API calls)

Then I've looked at server configuration
os version: `CentOS 7.4`
php: `php.x86_64    7.4.28-1.el7.remi    @remi-php74`
httpd/apache: `Apache/2.4.6 (CentOS)`
application version: `Snipe-IT v5.3.8`
No red flags here. I've confirmed PHP is 64bit (to avoid problems with token expiration reported year ago) with int size evaluation. At this moment I had no clue what is happening.

Then I tried to set `API_TOKEN_EXPIRATION_YEARS=10`, generate new API token and with the new token the API calls came through.

So, at this moment I have two tokens
1) Expiring 2037-02-21 10:08:38 that returns 401
2) Expiring 2032-02-21 12:50:57 that works fine

Do we have any clue why this is happening? For me the strangest thing is it worked just a week ago before changing domain name from IP to DNS

Thanks

### Reproduction steps

1. On Centos 7.4, apache 2.4.6. with php.x86_64 7.4 generate token with expiration in 15 years
2. Send a API request
3. ???
4. NOT profit
...

### Expected behavior

Valid authentication via token with expiration set in default .env

### Snipe-IT Version

v5.3.8

### Operating System

CentOS 7.4

### Web Server

Apache/2.4.6

### PHP Version

php.x86_64 7.4.28@remi-php74

**Comment by yosiasz** [comment]
The DNS change was obviously external to snipeit and no changes were made to the .env file along with the dns changes?

**Comment by halvaldr** [comment]
> The DNS change was obviously external to snipeit and no changes were made to the .env file along with the dns changes?

Thanks for pointing this out, but I reflected the DNS name to both apache and .env conf files, I see I didn't describe this properly in the first post.

**Comment by yosiasz** [comment]
i would guess it might be because of that change that the original token is not working. Maybe the token is generated using some pieces of data from the .env file also? just a wild guess.

**Comment by halvaldr** [comment]
Oh, believe me, I am deep in the "give me your wild guess" territory too :)

The not-working token expiring on 2037-02-21 was created after all the necessary changes (dns, apache, .env) were made, only difference between two tokens is the first was created with .env set to 15yrs and the second with .env set to 10 "immediately" after with no other change in configuration.

**Comment by uberbrady** [comment]
Hrm. Well this *still* feels like a Y2038 problem to me, especially considering the dates you listed above. But the Y2038 issue is supposed to trigger in mid-January 2038, not in 2037, at all. So that's confusing, and *maybe* that's a red herring.

I would try `API_TOKEN_EXPIRATION_YEARS=14` and various other values to see if we have one particular duration in years that *does* work, and one that *doesn't*. If so, then it's definitely _some_ kind of date-math thing...

You may also want to 1000% confirm that the PHP your *web server* is using is really 64-bit. First, make sure your system is in 'develop' mode - `APP_ENV=local` or `APP_ENV=develop`. Then, go to Settings, and click the 'PHP System Info' pane, and see what you see.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
