### ISSUE TITLE
Little graphical "glitches"

### ISSUE THREAD

**Issue by Xiayu8** [grokability/snipe-it#10708]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hey there,

i am pretty new to coding but i am tinkering around for quite some time with this project.
Because i want to contribute something to this really great project (even its something very small... as i said my skills are not great at all) i opened this "bug" report.

The Manufacturers column/row height is smaller than the rest on the asset view page, so it gets a little graphical "glitch". (see the added screenshot)
v6.0.0 RC3(v5.3.10) view.blade.php line 313`<ul class="list-unstyled" style="line-height: 25px;">`
All other line heights are not specified.

((v6.0.0 RC3) view.blade.php line 126`<i class="fa fa-hdd" aria-hidden="true"></i>`
all other symbols got the fa-2x "attribute" so the hdd symbol appears to small)

If this way to contribute is not desired, i am sorry and please remove this issue or tell me to remove it myself.
(thought this is a too minor issue to create a merge request. Also i am a little bit afraid of doing something wrong while pulling/pushing/merging)

### Reproduction steps

1.no reproduction needed
2.
3.
...

### Expected behavior

line height should be the same as the rest.

### Screenshots

<img width="272" alt="Screenshot" src="https://user-images.githubusercontent.com/96250874/155013185-57826138-f304-41e5-98e4-e6fc479f7424.PNG">

### Snipe-IT Version

5.3.10 (v6.0.0 RC3)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Firefox

### Version

97

**Comment by insert-waffle** [comment]
will be fixed in next merge from dev to main. thanks for the report! :)
