### ISSUE TITLE
Permissions Error

### ISSUE THREAD

**Issue by MattyHumphrey** [grokability/snipe-it#10701]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have a custom group created to allow people to edit everything but not create or delete assets, models, location etc. This has worked perfectly fine until about a week ago. This could coincide with the last update I performed. 

Now when using these permissions, I select the location drop down and the model drop down list and nothing appears. With super admin permissions this works fine. I have tried changing the permissions and found when I allow the ability to create an asset this works again but I do not what people to have that ability.

### Reproduction steps

1.Edit an asset
2.Click the locations or Model drop down list
3.
...

### Expected behavior

A list of all the current locations or models should appear. 

### Snipe-IT Version

  Version v5.3.10 - build 6684 (master)

### Operating System

Winsows Server 2019

### Web Server

IIS

### PHP Version

7.4.20

### Operating System

Windows 10

### Browser

Chrome

### Version

98.0.4758.82

### Error messages

```shell
This action is unauthorized.
D:\SnipeITSource\vendor\laravel\framework\src\Illuminate\Auth\Access\Response.php#119
Illuminate\Auth\Access\AuthorizationException

public function authorize()
    {
        if ($this->denied()) {
            throw (new AuthorizationException($this->message(), $this->code()))
                        ->setResponse($this);
        }

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

**Comment by MattyHumphrey** [comment]
This is also the same for models.

**Comment by MattyHumphrey** [comment]
I have ran a PHP.upgrade.php to be on the latest release.

**Comment by athompsoncmc** [comment]
I'm having this issue as well. I had a non-admin user try to check something out to a location, nothing appeared in the drop down (user and asset checkout work).  I had to give their permissions group create/delete access as well, but originally they didn't have create/delete access
![bug1](https://user-images.githubusercontent.com/79665233/156243793-322c1387-2614-4093-813a-df989b50935f.PNG)
.

**Comment by athompsoncmc** [comment]
for clarity, I'm on v5.4.0 - build 6685 (master)

**Comment by snipe** [comment]
This is fixed on master and develop
