### ISSUE TITLE
Unable to login in 6.0-RC3

### ISSUE THREAD

**Issue by andreaci** [grokability/snipe-it#10710]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Using docker container, this error pops up:

UnexpectedValueException
The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

### Reproduction steps

1. run a container with

docker run -d -p 49080:80 --name="SnipeIT" --env-file=/var/lib/docker/volumes/snipe-it/_data/.env --mount source=snipe-it,dst=/var/lib/snipeit snipe/snipe-it:v6.0.0-RC-3

2. logout if already logged in
3. try accessing the webpage

### Expected behavior

it should work

### Snipe-IT Version

6.0-RC3

### Operating System

Centos

### Web Server

Docker container

### PHP Version

Docker container

**Comment by Yann-J** [comment]
Same here... Weird because logging into the container, I can see this directory does give ownership (and write permissions) to the `docker` user which I suppose is running all the processes (?):

```
root@snipe-snipeit-7f9898c97c-9ctdr:/var/www/html/storage/logs# ls -la
total 16
drwxr-xr-x 1 docker root 4096 Oct 19 00:25 .
drwxr-xr-x 1 docker root 4096 Oct 19 00:27 ..
-rwxr-xr-x 1 docker root   14 Oct 19 00:24 .gitignore
```

**Comment by andreaci** [comment]
> Same here... Weird because logging into the container, I can see this directory does give ownership (and write permissions) to the `docker` user which I suppose is running all the processes (?):
> 
> ```
> root@snipe-snipeit-7f9898c97c-9ctdr:/var/www/html/storage/logs# ls -la
> total 16
> drwxr-xr-x 1 docker root 4096 Oct 19 00:25 .
> drwxr-xr-x 1 docker root 4096 Oct 19 00:27 ..
> -rwxr-xr-x 1 docker root   14 Oct 19 00:24 .gitignore
> ```

I also tried to map that file from the server, but the error is still there

**Comment by aa-matthias** [comment]
same here - for now i docker exec -it /bin/bash into the container, delete the existing file and it works (until i restart the container)

**Comment by uberbrady** [comment]
So you're deleting the `.gitignore` file, and that's working for you folks? That's pretty weird; that file doesn't actually do anything except try and prevent `git` from yanking the directory (since it's empty, and `git` doesn't deal with empty directories).

**Comment by snipe** [comment]
Agreed - that makes zero sense. Plus we haven’t even changed any of those gitignore files in ages. They exist in v5 as well.

**Comment by aa-matthias** [comment]
For me there is a laravel.log file already owned by root:root when i startup a 6.0.0-RC-4 docker dontainer via docker compose

```bash
Digest: sha256:9267dfd4bb514e0d1bcfb9ad0af653f875047f43f5399da9d02ce2c9bece1542
Status: Downloaded newer image for snipe/snipe-it:v6.0.0-RC-4
docker.io/snipe/snipe-it:v6.0.0-RC-4
user@host:/srv/snipe-it$ sudo docker compose up -d
[+] Running 3/3
 ⠿ Network snipe-it_default       Created                                                                                                                                                                     0.1s
 ⠿ Container snipe-mysql          Started                                                                                                                                                                     1.2s
 ⠿ Container snipe-it-snipe-it-1  Started                                                                                                                                                                     1.1s
user@host:/srv/snipe-it$ sudo docker exec -it snipe-it-snipe-it-1 /bin/bash
root@250e8d865fba:/var/www/html# cat storage/logs/
.gitignore   laravel.log
root@250e8d865fba:/var/www/html# ls -la storage/logs/laravel.log
-rw-r--r-- 1 root root 18600 Mar  9 12:50 storage/logs/laravel.log
```

when deleting the file it get's recreated with different rights:

```bash
root@250e8d865fba:/var/www/html# rm storage/logs/laravel.log
root@250e8d865fba:/var/www/html# ls -la storage/logs/laravel.log
-rw-r--r-- 1 docker staff 59 Mar  9 12:54 storage/logs/laravel.log
```

**Comment by andreaci** [comment]
It seems solved in RC4 (at least for me)

**Comment by snipe** [comment]
Mystery.... We didn't change any of that stuff in RC4. 

![DerpPug](https://user-images.githubusercontent.com/197404/159283833-4ef8bc7d-f2e1-476e-b47e-b5f1447fe284.gif)

Oh well, since it seems to have resolved itself, I'll close this for now.

**Comment by DominikRoB** [comment]
Sorry that I'm digging this out again, but I have the exact same behavior.
It seems like the root user writes a log file right after starting the container and thus becomes the owner of the file?

Here is the log that is being written - maybe it helps to clear this issue once and for all:
[laravellog.txt](https://github.com/snipe/snipe-it/files/14347615/laravellog.txt)

FYIW: Whatever causes this error message, does not affect the preflight at all. After a quick chown docker... The site runs normally, with all checkmarks (except e-mail, we don't use these currently).
