### ISSUE TITLE
Mobile App Connects but doesn't show any Assets

### ISSUE THREAD

**Issue by lcasesupreme** [grokability/snipe-it#10715]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We have Snipe It running on premise and have been able to make changes without issue on desktop machines. When we try to access the site though the mobile app Asset Manager no assets are displayed. We are using Android devices and have a VPN connection coming back to the on premise server but whenever we search for an asset we get a red OK message displayed. I have updated the app to the latest version as of 5 minutes ago but that didn't seem to help. 

### Reproduction steps

1. Open Application
2. Search for Code 
3. Error displayed
...

### Expected behavior

Asset should be displayed

### Snipe-IT Version

Most Recent

### Operating System

Android

### Web Server

Apache

### PHP Version

7.4.3

**Comment by snipe** [comment]
We do not have a mobile app.

**Comment by lcasesupreme** [comment]
We were told to create an issue here per Diego.

Diego García DEV <info@diegogarciadev.es>
Fri, Feb 18, 4:54 AM (4 days ago)
to me

Please open ancissue on github, I will try to help you

Regards.

Diego García DEV

**Comment by snipe** [comment]
We do not support the mobile app and have no knowledge of how it works, so I'm not sure why he'd tell you that. We can't support something if we don't have oversight on the source code. :(

**Comment by lcasesupreme** [comment]
Ok thank you for the quick replies!

**Comment by snipe** [comment]
(If he chimes in here, I'll re-open the ticket for discussion though - I know people do use that app, it's just that we can't legally endorse it since we don't know what's in it.)

**Comment by diegogarciadev** [comment]
Hello I'm the developer of the android app. The app is just an interface to the API, no data stored locally, I only redirect the request to the API.

I think this issue is installation related instead of app problem. I usually help users to solve the issue. I have a repo to manage al request regarding to my app an also for their problems.

I will try to help @lcasesupreme, thanks anyway @snipe 

Regards!
