### ISSUE TITLE
Importing asset list via CSV avoids MAC verification

### ISSUE THREAD

**Issue by dfitelw** [grokability/snipe-it#10716]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When importing a CSV of assets that include MAC address field, you can bypass the MAC address format verification, requiring manual correction later.

### Reproduction steps

1. Create requisite category, supplier, manufacturer, and asset model.
2. While creating asset model select the custom fieldset "Asset with MAC address"
3. Create spreadsheet with assets, for the MAC address column do not follow the standard format Aa:Bb:Cc:11:22:33, just put in AaBbCc112233.
4. Upload the CSV and check the assets that were uploaded, the MAC address will require being corrected to the proper format above.

### Expected behavior

Either/or

1. Reject the CSV for improper format of MAC address
2. Correct the formatting to be Aa:Bb:Cc:11:22:33

### Screenshots

![image](https://user-images.githubusercontent.com/100156751/155231595-349806ab-d5e2-4658-aff2-fec31622d64e.png)
![image](https://user-images.githubusercontent.com/100156751/155231626-9aef6e60-ac76-4888-a2c6-807b32084188.png)

### Snipe-IT Version

5.3.5 - build 6558

### Operating System

Debian 5.10.92-1

### Web Server

Apache2

### PHP Version

7.4

### Operating System

Windows 10

### Browser

Brave

### Version

1.35.103

**Comment by ccj9874** [comment]
I had the same thing happen to me. I'm not sure if its an actual issue or if the importer isn't intended to validate the contents of the fields based on the parameters you set up in the interface.

**Comment by dfitelw** [comment]
Yeah I absolutely concede that the importer has enough highlighted warnings that it is very "basic" in it's function. I'd almost think the MAC address field should really be what is "fixing" this especially since it's very specific about the input it'll accept. AaBbCc-112233 is rejected and Aa-Bb-Cc-11-22-33 is rejected; yet both are very common formats for MAC address display.

**Comment by snipe** [comment]
The importer does validate content, as those things are validated at the model level.

**Comment by inietov** [comment]
Version 5.4.1 does validate the MAC address. I used the same you have in your example and the importer shows the error.

![image](https://user-images.githubusercontent.com/653557/159819697-b2d9b64d-c848-43e6-b17e-1526b5af8a55.png)

Can you pull the latest from master and test if works for you know?

**Comment by inietov** [comment]
Gonna 'stale-boting' for a moment, and say that I couldn't reproduce the error and didn't hear back in a while, so I'm going to close this. Beep, boop.
