### ISSUE TITLE
inconsistent tag style -- V5.4.0 instead of v5.4.0

### ISSUE THREAD

**Issue by vapier** [grokability/snipe-it#10738]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

looks like tag `V5.4.0` was just pushed, but (almost) all the other tags use `v`.  can it stay consistent ?  should be easy to rename the tag.

### Reproduction steps

`git fetch`

### Expected behavior

should be `v5.4.0` not `V5.4.0`

### Snipe-IT Version

-

### Operating System

-

### Web Server

-

### PHP Version

-

**Comment by snipe** [comment]
It normally is consistent. Autocorrect decided to capitalize it. Check our extensive release history.

**Comment by vapier** [comment]
no idea what you're trying to say.  but it looks like you fixed the mistake and pushed the correct `v5.4.0` tag now.

**Comment by snipe** [comment]
> no idea what you're trying to say. but it looks like you fixed the mistake and pushed the correct v5.4.0 tag now.

Not sure what’s unclear here. Autocorrect (specifically first character in a sentence capitalization trait) capitalized the v. It’s not standard for us to use a capital v, but it happened this time by accident. We have a long history of consistency, and this was just a mistake.
