### ISSUE TITLE
Docker - K8s - fails to run for more than a few seconds (no useful error message)

### ISSUE THREAD

**Issue by mattseymour** [grokability/snipe-it#10732]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When running the snipeit 5.3.10 release in kubernetes the pod fails to stay running exiting with a "Fatal error". The logs for this fatal error do not seem to be present making debugging and diagnosing the issue difficult. Turning debug on/off seems to make no difference to the output of the log as the sever will not stay running.

```
│ app-snipeit 2022-02-24 13:30:33,371 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run a │
│ app-snipeit 2022-02-24 13:30:33,377 INFO supervisord started with pid 1                                                                                                       │
│ app-snipeit 2022-02-24 13:30:34,380 INFO spawned: 'exit_on_any_fatal' with pid 43                                                                                             │
│ app-snipeit 2022-02-24 13:30:34,383 INFO spawned: 'apache' with pid 44                                                                                                        │
│ app-snipeit 2022-02-24 13:30:34,470 INFO spawned: 'run_schedule' with pid 45                                                                                                  │
│ app-snipeit 2022-02-24 13:30:35,472 INFO success: exit_on_any_fatal entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                             │
│ app-snipeit 2022-02-24 13:30:35,473 INFO success: apache entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                        │
│ app-snipeit 2022-02-24 13:30:35,473 INFO success: run_schedule entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                  │
│ app-snipeit AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.31.0.20. Set the 'ServerName' directive globally to suppress th 
app-snipeit 2022-02-24 13:30:48,770 INFO waiting for exit_on_any_fatal, apache, run_schedule to die                                                                           │
│ app-snipeit 2022-02-24 13:30:49,771 INFO stopped: run_schedule (terminated by SIGTERM) 
```

### Reproduction steps

1. Run helm chart t3/snipeit
2. Look at logs

### Expected behavior

Snipeit throws an error to the status of the app failing.

### Snipe-IT Version

5.3.10

### Operating System

Snipeit Docker image

### Web Server

Apache

### PHP Version

Dockerized PHP version

### Additional context

Trying to install snipe it on a k8s cluster. The database is accessible as tables / migrations are run.

**Comment by mattseymour** [comment]
Sorry going to close the issue but found the problem in my instance.

My issue was the generated app_key was for some reason not valid. I have subsuqently regenerated the key and the application now runs in a stable maner.

Is there a link to how app_keys can be generated outside of the docker/ php environment? Or a spec on length and complexity?

**Comment by yosiasz** [comment]
```php artisan key:generate```
