### ISSUE TITLE
Snipe-IT webinterface not accessable from Windows system

### ISSUE THREAD

**Issue by Augustronic** [grokability/snipe-it#10742]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Snipe-IT webinterface is not accessable from a Windows system.
From a Linux system it's working fine using Firefox.

### Reproduction steps

1. Open Browser on Windows
2. Enter snipe-it address
3.
...

### Expected behavior

Webinterface opens

### Screenshots

![Screenshot 2022-02-25 190648](https://user-images.githubusercontent.com/21057489/155765448-2d53b866-96c1-42dd-a678-09fb1736a87c.png)

### Snipe-IT Version

v5.4.0 build 6685 (dfbff274839) 

### Operating System

CentOS Linux 7.9.2009

### Web Server

Apache

### PHP Version

7.4.28

### Operating System

Windows

### Browser

Firefox

### Version

97.0.1 (64-Bit)

### Error messages

```shell
Demo works


storage/logs/laravel.log

[2022-02-25 00:00:11] production.ERROR: Failed to authenticate on SMTP server with username "snipe-it@aixsponza.com" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535 Incorrect authentication data
". Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535 Incorrect authentication data
". {"exception":"[object] (Swift_TransportException(code: 0): Failed to authenticate on SMTP server with username \"snipe-it@aixsponza.com\" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code \"535\", with message \"535 Incorrect authentication data
\". Authenticator PLAIN returned Expected response code 235 but got code \"535\", with message \"535 Incorrect authentication data
\". at /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:191)
[stacktrace]
#0 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo()
#1 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand()
#2 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(488): Swift_Mailer->send()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(261): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(65): Illuminate\\Mail\\Mailer->send()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\\Notifications\\Channels\\MailChannel->send()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109): Illuminate\\Notifications\\NotificationSender->withLocale()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send()
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Notifications\\ChannelManager->send()
#13 /var/www/snipeit/app/Console/Commands/SendExpirationAlerts.php(65): Illuminate\\Support\\Facades\\Facade::__callStatic()
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\SendExpirationAlerts->handle()
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#20 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#22 /var/www/snipeit/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run()
#23 /var/www/snipeit/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand()
#24 /var/www/snipeit/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun()
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#27 /var/www/snipeit/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#28 {main}
"} 


php -m

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
readline
Reflection
session
SimpleXML
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]
```

### Additional context

This is an upgrade.
I had upgraded PHP to version 8.1 and later downgraded to version 7.4 as I had issues with the Snipe-IT upgrade and thought I can fix it this way.

**Comment by snipe** [comment]
I don’t speak German - can you translate that screenshot for me?

**Comment by Augustronic** [comment]
Address not found

The browser could not find the host server for the given address.

        Please check the address for typing errors, such as ww.example.com instead of www.example.com.
        If you also cannot access another website, please check the data or WLAN connection.

**Comment by snipe** [comment]
Thank you - that definitely seems more like a networking or server issue, and not related to the code or the upgrade itself. Are you sure the web server is running? Anything change with DNS?

**Comment by albinbatman** [comment]
Hi @Augustronic,

Can you run the following command (in PowerShell) and copy paste the contents that are outputted to us?

```powershell
Get-NetTCPConnection -LocalPort 80 | Select -Property LocalAddress, LocalPort, State | fl
Get-NetTCPConnection -LocalPort 443 | Select -Property LocalAddress, LocalPort, State | fl
Resolve-DnsName <domain to snipe-it> | fl
````

An example of the outputs would look like this:

```
PS C:\WINDOWS\system32> Get-NetTCPConnection -LocalPort 80 | Select -Property LocalAddress, LocalPort, State | fl
LocalAddress : 0.0.0.0
LocalPort    : 80
State        : Listen

PS C:\WINDOWS\system32> Resolve-DnsName butler.dev | fl
Name       : butler.dev
Type       : A
TTL        : 0
DataLength : 4
Section    : Answer
IPAddress  : 127.0.0.1
```

edit: Please clarify if the Windows system is serving the Snipe-IT instance or if it is a Linux system. I have made the assumption that you are hosting the Snipe-IT instance on a Windows machine.

**Comment by Augustronic** [comment]
Hello albinbatman,

the Sipe-IT server is a Linux system.
I am trying to access it from a Windows system without success.
Accessing the server from a Linux system is working.

I will be able to check your commands as soon, as I am back in the office, as VPN only acceps IP addresses.

Have a nice day!
Achim

**Comment by Augustronic** [comment]
This is the output from a local windows machine:

PS C:\Users\aatie> Get-NetTCPConnection -LocalPort 80 | Select -Property LocalAddress, LocalPort, State | fl
Get-NetTCPConnection : No MSFT_NetTCPConnection objects found with property 'LocalPort' equal to '80'.  Verify the
value of the property and retry.
At line:1 char:1
+ Get-NetTCPConnection -LocalPort 80 | Select -Property LocalAddress, L ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (80:UInt16) [Get-NetTCPConnection], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_LocalPort,Get-NetTCPConnection

PS C:\Users\aatie> Get-NetTCPConnection -LocalPort 443 | Select -Property LocalAddress, LocalPort, State | fl
Get-NetTCPConnection : No MSFT_NetTCPConnection objects found with property 'LocalPort' equal to '443'.  Verify the
value of the property and retry.
At line:1 char:1
+ Get-NetTCPConnection -LocalPort 443 | Select -Property LocalAddress,  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (443:UInt16) [Get-NetTCPConnection], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_LocalPort,Get-NetTCPConnection

PS C:\Users\aatie> Resolve-DnsName snipe-it.aixsponza.local | fl
Resolve-DnsName : snipe-it.aixsponza.local : DNS name does not exist
At line:1 char:1
+ Resolve-DnsName snipe-it.aixsponza.local | fl
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (snipe-it.aixsponza.local:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

**Comment by Augustronic** [comment]
I found the source of the issue.
A firewall update changed some configuration how to handle the DNS servers.
However, Linux clients weren't affected.

Thank you for your helping commands!
