### ISSUE TITLE
Expand predefined kits to support any product

### ISSUE THREAD

**Issue by dfitelw** [grokability/snipe-it#10752]
### Snipe-IT Version

v5.3.5 - build 6558

### Operating System

Debian 11

### Web Server

Apache2

### PHP Version

7.4

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Predefined kits only allow for physical assets to be added and no other items. 

### Describe the solution you'd like A clear and concise description of what you want to happen.

Allow for assets, consumables, licensing, etc. to be added to kits. We deploy IP phones that require a license to be used by an end user, so a phone and license will ALWAYS be assigned together.

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

We've considered migrating all licensing, consumables, etc. to normal assets to expand on some of these features.

**Comment by snipe** [comment]
This is already on the roadmap, and there are existing tickets for this.
