### ISSUE TITLE
Create API Key

### ISSUE THREAD

**Issue by bunzladi** [grokability/snipe-it#10760]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I cannot create a personal API key. 
It shows the Server Error.

### Reproduction steps

This happened after I updated the PHP to 8.0 and after the PHP update I updated the program to 5.4. 

![image](https://user-images.githubusercontent.com/92428604/156377260-2bf22e22-64ec-4864-a07a-f632b50e42ef.png)
![image](https://user-images.githubusercontent.com/92428604/156377278-b5e92598-e41c-46d5-89b4-96b1de7de678.png)

### Expected behavior

I don't know :(

### Snipe-IT Version

5.4.0

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.0.0

### Operating System

Windows Server

### Browser

MS Edge

### Error messages

```shell
[2022-03-02 14:06:04] production.ERROR: It was not possible to parse your key, reason:  {"userId":682,"exception":"[object] (Lcobucci\\JWT\\Signer\\InvalidKeyProvided(code: 0): It was not possible to parse your key, reason:  at C:\\inetpub\\wwwroot\\snipe-it\\vendor\\lcobucci\\jwt\\src\\Signer\\InvalidKeyProvided.php:17)
```

**Comment by yosiasz** [comment]
5.x is still on php 7.x

**Comment by bunzladi** [comment]
> 5.x is still on php 7.x

Ok thanks, I thought you can use 7.4 and higher versions

**Comment by yosiasz** [comment]
![Screenshot_20220302-083925_Chrome](https://user-images.githubusercontent.com/900951/156407064-90c6f2a7-19d6-4807-b0da-af9fe9697a1c.jpg)

**Comment by bunzladi** [comment]
Thanks
