### ISSUE TITLE
MISSING PHP EXTENSION: ldap

### ISSUE THREAD

**Issue by davecowley** [grokability/snipe-it#10778]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Trying to upgrade to the latest version from 5.3.7 on ubuntu and it keeps saying the ldap extension is missing.  im not using ldap and the install guide said its not needed if not in use.

i dont mind installing it but the documentation wont load for me to install it and I avent found the right thing on google.  can you assist me please?

### Reproduction steps

1.
2.
3.
...
php upgrade.php

### Expected behavior

upgrade to start

### Snipe-IT Version

5.3.7

### Operating System

ubuntu

### Web Server

apache

### PHP Version

7.2.34-28

### Operating System

w10

### Browser

chrome

### Version

99

### Error messages

```shell
- zip
- Zend OPcache
--------------------- !! ERROR !! ----------------------
✘ MISSING PHP EXTENSION: ldap
------------------------- :( ---------------------------
ABORTING THE INSTALLER
Please install the extensions above and re-run this script.
```

### Additional context

upgrade
install.sh

**Comment by uberbrady** [comment]
On v6 it’s definitely not required. On v5.x I _tried_ to make it not required - so if you don’t use it, you don’t need to install it. But I suspect I wasn’t thorough enough, and might have missed the installer part. If you edit the installer to remove the ldap requirement, and try to re-run the install - do you end up with a working installation? If so, I’d love to take a PR that removes that requirement if we don’t absolutely have to have it.

**Comment by davecowley** [comment]
Morning, 
sorry the late reply, only just back in the office.  would you be able to tell me how to modify the installer?  do you mean the upgrade.php file?

**Comment by davecowley** [comment]
i figured it out but it still isnt liking it.

--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- check your PHP version and extension requirements
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (7.2.34-28+ubuntu18.04.1+deb.sury.org+1) is at least 7.2.5 - continuing...
FYI: The php.ini used by this PHP is: /etc/php/7.2/cli/php.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

-- Starting backup...
Backup failed because: mkdir(): Permission denied.


--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

-- Failed to enter maintenance mode.
file_put_contents(/var/www/snipeit/storage/framework/down): failed to open stream: Permission denied

--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
error: cannot open .git/FETCH_HEAD: Permission denied
fatal: Unable to create '/var/www/snipeit/.git/index.lock': Permission denied
fatal: Unable to create '/var/www/snipeit/.git/index.lock': Permission denied
Cannot save the current index state
error: cannot open .git/FETCH_HEAD: Permission denied
-- -- --
--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ No bootsrap/cache/services.php, so nothing to delete.
√ No bootstrap/cache/config.php, so nothing to delete.

-- Configuration cache cleared!
-- Failed to clear cache. Make sure you have the appropriate permissions.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.


> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
69 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Generated optimized autoload files containing 6050 classes

--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is already up.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!

**Comment by snipe** [comment]
> file_put_contents(/var/www/snipeit/storage/framework/down): failed to open stream: Permission denied

This means your storage directory (and subdirs, likely) are not writable. You'll need to fix that before you can go any further, as the Snipe-IT system uses the storage directory for caching, logging, etc.

**Comment by davecowley** [comment]
Thanks, for anyone who finds this, the fix is here https://snipe-it.readme.io/docs/debugging-permissions

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/debugging-permissions">Debugging Server Permissions</a></strong></div><div>One of the most common issues folks newer to running web servers run into is how to manage the Linux/Windows/etc owners and groups of the Snipe-IT filesystem. As we mention many times in the installation documentation, nothing in Snipe-IT should be run as or owned by root. Running composer as root, ...</div></blockquote>
