### ISSUE TITLE
*Feature Request* Add hyperlinked file paths as custom field

### ISSUE THREAD

**Issue by Oddalmighty** [grokability/snipe-it#10780]
### Snipe-IT Version

5.4.1

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.11

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

My agency keeps all equipment purchase documents (purchase orders, invoices, packing slips, etc.) in a folder on an on-premise server. We have 5000+ devices (including archived) in our Snipe-IT database. Ideally, we'd like to be able to access the purchase documents from within an asset page in Snipe-IT. It is very time consuming adding the individual documents to each asset and takes up a lot of space since some assets share the same documents. Also, when adding documents, the file names change (adding "hardware" and dashes) which is a bit of a peeve, so to make it easier to read we've added the name of the document to the notes when adding. It just takes too long.

### Describe the solution you'd like A clear and concise description of what you want to happen.

The best solution for us would be to allow hyperlinked file paths as a custom field. We could just add the direct file path for the purchase documents on our server, and then clicking on them would open the folder in File Explorer. I'm not sure if that's doable or not. It would also be helpful if the file names didn't change when we add documents to assets. Because of our file naming conventions, it's just harder to read and figure out which document is which. That way if we did just continue to add the documents, we wouldn't have to add one at a time to correct the names.

**Comment by snipe** [comment]
> It would also be helpful if the file names didn't change when we add documents to assets. Because of our file naming conventions, it's just harder to read and figure out which document is which. That way if we did just continue to add the documents, we wouldn't have to add one at a time to correct the names.

The problem is that we don't want people overwrite an existing file of the same name, which is why we generate unique ones.

**Comment by snipe** [comment]
You should already be able link files by using the URL format and starting the custom field's value with `file://`
