### ISSUE TITLE
Serial exported via Excel Export looses least significant digits on big serials

### ISSUE THREAD

**Issue by mindcreations** [grokability/snipe-it#10791]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When exporting assets with the Excel Export function the field Serial is exported as a number.
If you have a big number as a serial for an asset, it will be an issue in Excel.

When you open the produced file, Excel will display it in scientific notation.
When you try to convert it to a text field to see the actual serial, the least significant digits are converted to zeros.

**Workaround**
Export as CSV and import it into Excel by using the Data Import function by specifying TEXT in the Excel wizard.

### Reproduction steps

1. Create an asset on Snipe-IT with a serial like 8939010102358478435
2. Export the assets in Excel format
3. Open the file from Excel and convert the Serial column to a text field

### Expected behavior

Export the Serial as text instead of a number

### Snipe-IT Version

v5.3.10 build 6684 (g05c081977)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

**Comment by snipe** [comment]
We can't really control how Excel handles your data. Your workaround is the solution, unfortunately.

**Comment by mindcreations** [comment]
> We can't really control how Excel handles your data. Your workaround is the solution, unfortunately.

Can't you set a datatype for the Serial field when exporting to Excel that is not generic but rather "Text"?
This way Excel does not have to guess what kind of data is in the cells.

**Comment by snipe** [comment]
The JS library we use doesn’t support that, as far as I know.
