### ISSUE TITLE
Add user to a group with the API

### ISSUE THREAD

**Issue by mahlquistj** [grokability/snipe-it#10792]
### Snipe-IT Version

v5.3.8

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.28

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

It's a bit frustrating that when creating a user through the API, you can't assign them to any groups - The user will then, from my understanding, have a basic set of permissions, instead of the permission i have defined in my "Users" group, which is applied to normal users.

### Describe the solution you'd like A clear and concise description of what you want to happen.

I would like one of two things (Maybe even both?):

**1. Adding the user to a group when creating or updating:**
When calling the endpoint `POST: /api/v1/users` there could be a "Groups" option in the json that you're sending.

You could then call the `POST: /api/v1/users` endpoint and add `"group_id": <group-id>` to the request body in order to add the created user to a group.

The same goes for the `PUT: /api/v1/users/<user-id>` endpoint

**2. Being able to create a group and add members to it**
This solution would require an endpoint just for groups. For example (List all groups) `GET: /api/v1/groups` - Which would return groups somewhat like this:
`{"total": 1, "rows": [{"name": <group-name>, "permissions": <group-permissions>, "id": <group-id>}]`

Then you could have another endpoint on `/api/v1/groups/addMember` (or alike) where you would send a user-id in the body like so `{"user-id": <user-id>}` which would add the user-id to the group.

### Additional context Add any other context or screenshots about the feature request here.

First of all - Thank you for an amazing hardware-management system :heart:

At our company we use snipe alot, and have automated a lot of our systems, and would therefore like to automate snipe as well. We are currently working on automating all of our user-creation, which includes snipe - This is what made me think of the feature, since i don't want to add every single user to a group, when i know which groups will fit when adding the user via. the api.

I hope you understand the request.

Thank you for your time!

**Comment by snipe** [comment]
This *should* already be possible: 

https://github.com/snipe/snipe-it/blob/3e2fe1048076eb0c768a5e529a074d3adbafd611/app/Http/Controllers/Api/UsersController.php#L296-L301

**Comment by mahlquistj** [comment]
I thank you alot - That works!

**Comment by mahlquistj** [comment]
@snipe I'm not sure if i'm just blind - May i suggest that this gets updated in the api-reference?

I can't suggest edits on the api-reference, only the documentation itself :smile:

**Comment by snipe** [comment]
You can propose changes to the documentation by using the "suggest edits" link on the documentation page

**Comment by mahlquistj** [comment]
The "suggest edits" button appears on the Documentation pages, but **not** on the API-Reference?

**Comment by snipe** [comment]
Refresh my memory - how are you posting those groups? I'll update the docs.

**Comment by mahlquistj** [comment]
I am using the `POST: /api/v1/users` endpoint.

In the data, additional to whats already in the docs, i add a `"group_id": <group-id>` to my data.

This makes the created user a member of the group specified.

And thank you!

**Comment by snipe** [comment]
But if you need to add more than one group to a user, are you putting that in an array, or...?

**Comment by snipe** [comment]
Hm, also, that code doesn't look like it's looking for `group_id`.

```php
if ($request->filled('groups')) { 
```

implies it's looking for a field named `groups`

**Comment by mahlquistj** [comment]
I'm very sorry - I wrote that in a hurry, and thought i had all the details on top of my mind.

I'm using `"groups": <group_id>` to add a user to a single group when calling `POST /users`.

In order to add multiple groups to the user, an array can be used like so (adds the user to groups with id's 1 and 2):
`"groups": [1,2]`

**Comment by snipe** [comment]
Perfect, thanks! I've updated the documentation. (Sorry for having to ask you how it works lol - it's been a while since I touched that part of the code, and I'm currently traveling.) 

https://snipe-it.readme.io/reference/users-2

<img width="639" alt="Screen Shot 2022-03-17 at 12 25 10 PM" src="https://user-images.githubusercontent.com/197404/158807976-9e4a5aa1-74ca-4207-b063-365955bea23d.png">


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/users-2">/users</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>

**Comment by bzeus** [comment]
@snipe is this related/the same to a new request that I got?  (FD49037)
