### ISSUE TITLE
Error when upgrading to 6.0.0-RC-4

### ISSUE THREAD

**Issue by Joly0** [grokability/snipe-it#10800]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

![image](https://user-images.githubusercontent.com/13993216/157233952-a3c5994b-78fc-4767-b127-e67b77e41c90.png)
![image](https://user-images.githubusercontent.com/13993216/157234941-196311ad-fb3d-4521-97aa-27000c974eff.png)

Upgrade from 5.4.1 errors with the message seen in the screenshot.

APP_URL is in the normal fqdn format "https://snipeit.local.de" (not the actual domain name) and it worked for all previous upgrades

### Reproduction steps

1. Setup Snipe-IT using the mater branch
2. Try to upgrade to rc-4 using the php upgrade.php command
3. Fails
...

### Expected behavior

The upgrade should go through and i should be able to access the snipe-it page afterwards

### Screenshots

![image](https://user-images.githubusercontent.com/13993216/157235320-f0cdbd3f-63d6-421b-998b-94654e205692.png)

### Snipe-IT Version

6.0.0-RC-4

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4

**Comment by snipe** [comment]
I can't reproduce this - I assume you ran `composer install`?

**Comment by Joly0** [comment]
I have before and it worked with 5.4.1 no problem, when doing this after ugprading to 6.0.0-RC-4 i get this error
![image](https://user-images.githubusercontent.com/13993216/157236337-daf6ee13-32f6-47ae-9714-1b1fc7aa8c38.png)

**Comment by snipe** [comment]
When you type `php --version` in your terminal, what do you see? (The web server version and the cli version of PHP are not always the same.)

**Comment by Joly0** [comment]
![image](https://user-images.githubusercontent.com/13993216/157236611-5bcc200d-e140-4b7a-bb68-64ad0e9b2f5e.png)

**Comment by Joly0** [comment]
Afaik 7.4.1 is still supported, v6 only dropped support for 7.3

**Comment by snipe** [comment]
What version of composer are you using?

**Comment by Joly0** [comment]
![image](https://user-images.githubusercontent.com/13993216/157237005-964f3f41-17d4-4010-a049-acae16a1149a.png)

**Comment by Joly0** [comment]
Should i update?

**Comment by snipe** [comment]
I think you need to upgrade composer

**Comment by Joly0** [comment]
Wow, insane. Never have i thought it would be caused by an old composer version. Thanks for the great and quick support :D

**Comment by snipe** [comment]
No problem :) Glad you're sorted!
