### ISSUE TITLE
No email notification for requestable assets - unsure if this is a bug

### ISSUE THREAD

**Issue by deadtom76** [grokability/snipe-it#10808]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When a user requests an asset, we get no notification of any kind. The only way to know if assets have been requested, is to periodically go to Assets>Requested, and see if anything is in there.

Email notifications are working for everything else in Snipe-IT.

Is this by design, or have I misconfigured something?

### Reproduction steps

1. Log in.
2. Go to "Requestable".
3. Request an asset.

### Expected behavior

I would expect some sort of notification that a user has requested an asset.

### Snipe-IT Version

v5.4.1 build 6746 (g3e22dce11)

### Operating System

Debian 10

### Web Server

Apache2

### PHP Version

7.4.27

### Operating System

Windows 10

### Browser

Firefox

### Version

98

### Error messages

```shell
No errors in browser, or browser console, with DEBUG turned on.
No stracktrace.
Not reproducible in the demo, as no email functionality is available.
The only log in storage/logs is laravel.log, and there is no output to this log when requesting an asset.

Output of php -m:
[PHP Modules]
apc
apcu
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
imap
intl
json
ldap
libsmbclient
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
readline
redis
Reflection
session
shmop
SimpleXML
smbclient
snmp
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

Fresh install a month ago, upgraded this morning. This functionality was not there in the previous version either.
Web server is Apache2 on Debian 10.
Git install.

**Comment by JackPo** [comment]
Did this get resolved?  Can't seem to find the settings in which an email is defined, and we right now are getting it from our default email in the config file.

**Comment by snipe** [comment]
We were never able to reproduce this issue. 

https://github.com/snipe/snipe-it/commits/master/app/Notifications/RequestAssetNotification.php

Just tested locally, and I see: 

<img width="862" alt="Screen Shot 2022-08-29 at 2 00 39 PM" src="https://user-images.githubusercontent.com/197404/187298092-72d983e8-8fdb-4490-b10e-69e0c0f4895b.png">


<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">History for app/Notifications/RequestAssetNotification.php - snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - History for app/Notifications/RequestAssetNotification.php - snipe/snipe-it</div></blockquote>

**Comment by deadtom76** [comment]
> Did this get resolved? Can't seem to find the settings in which an email is defined, and we right now are getting it from our default email in the config file.

I still don't receive an email for requested items, and I don't see anywhere to configure it to send or not send them. I ended up creating a python script to watch the activity via the API, and send out an email when it sees an item requested.

**Comment by brianhoganm** [comment]
Did you make sure the email notification is checked under the category? In
other words the MacBook model category email needs to be enabled in order
to receive notifications.

**Comment by deadtom76** [comment]
> Did you make sure the email notification is checked under the category? In other words the MacBook model category email needs to be enabled in order to receive notifications.

These are the options I have, everything is checked.
![2022-08-29 15_43_00-Window](https://user-images.githubusercontent.com/9619788/187304572-c90a7394-7a08-4579-adca-56d7a7bddd79.png)

**Comment by snipe** [comment]
There isn't an option to send or not send them - they just get sent automatically. 

https://github.com/snipe/snipe-it/blob/cca531f8cae327323c237a1b3fff72f9f6bb7222/app/Http/Controllers/ViewAssetsController.php#L114-L118

https://github.com/snipe/snipe-it/blob/e94b5ac435c67c8f52f383597924eb3204b453a7/app/Notifications/RequestAssetNotification.php#L98-L121

**Comment by deadtom76** [comment]
> There isn't an option to send or not send them - they just get sent automatically.

I suspected that's how it's supposed to work, but it doesn't for me. All other email notifications are being sent fine, and I'm unable to see any indication in any logs as to why these particular notifications aren't sending.

Since creating this report, I have upgraded to v6.0.8 - build 8409, and PHP version 7.4.30. The problem persists. I'm at a loss.

Edit: I may not be looking in all the right logs either. PHP, Apache and laravel logs show nothing when someone requests an asset.

**Comment by snipe** [comment]
Unfortunately, I am too. That notification system hasn't changed much in many versions.

**Comment by snipe** [comment]
Just to rule out the obvious - you DO have an alert email set in your Admin settings > Notifications, and Email Alerts Enabled checked, yes? And you do not have `APP_LOCKED` set to true (or perhaps set at all) in your .env, correct?

<img width="938" alt="Screen Shot 2022-08-29 at 2 53 48 PM" src="https://user-images.githubusercontent.com/197404/187305834-f8c293f3-3e6a-4d29-8d77-fde9b48ca7cf.png">

**Comment by snipe** [comment]
> Edit: I may not be looking in all the right logs either. PHP, Apache and laravel logs show nothing when someone requests an asset.

We don't always log an event if things are working as expected. The `laravel.log` would be where to look to see if something errored though.

**Comment by snipe** [comment]
(And I assume you checked SPAM folders, etc.)

**Comment by deadtom76** [comment]
> Just to rule out the obvious - you DO have an alert email set in your Admin settings > Notifications, and Email Alerts Enabled checked, yes? And you do not have `APP_LOCKED` set to true (or perhaps set at all) in your .env, correct?

Correct. 


![notifications](https://user-images.githubusercontent.com/9619788/187307194-b26067c2-60de-4dfe-9ce2-5442ed43d647.png)
![app_locked](https://user-images.githubusercontent.com/9619788/187307204-c382110f-ab89-4466-b721-9e6ddd183443.png)

**Comment by snipe** [comment]
If you set your mail driver in your env to `log` and tail the log file while requesting an asset, what happens?

**Comment by deadtom76** [comment]
> If you set your mail driver in your env to `log` and tail the log file while requesting an asset, what happens?

Not a thing. Nothing at all appears in laravel.log, or in the apache error log.

Just to be sure, after making the change in .env, I restarted Apache and php.

**Comment by deadtom76** [comment]
I appreciate you taking these steps with me. The work-around I have going is doing the trick, so this isn't anything critical for me. All other emails are being sent, and arriving where they're supposed to, without issue.

It is a real head scratcher though.

**Comment by snipe** [comment]
It certainly is a head scratcher. 

FYI, for these steps, I'm mostly only interested in the laravel.log - apache and PHP logs generally wouldn't apply unless you're getting a PHP level crash that the logger in the app can't even see. 

Can you walk me through how the user is requesting an item? `/account/requestable-assets`, or some other place I'm not remembering?

**Comment by deadtom76** [comment]
Users are logging in, mousing over the little computer icon on the left-hand side, and then clicking on "Requestable". From there, selecting "Request" next to the items they want.

**Comment by snipe** [comment]
That's how I'm testing it too :(

**Comment by deadtom76** [comment]
Should I be seeing an alert in the top menu as well? Nothing pops up there either, when something is requested.

**Comment by snipe** [comment]
No, top menu is just for inventory volume alerts, IIRC

**Comment by deadtom76** [comment]
Is it possible to increase the log verbosity?

**Comment by snipe** [comment]
Yeah, you can set `LOG_LEVEL=debug` in your env, but if we're not outputting any debug info there (which we're not, according to that code), it may not be very useful.

**Comment by deadtom76** [comment]
Yeah, nothing. Tried it with the mail driver set to log, and to sendmail.
 I am running old stable Debian (10), so it's possible that an upgrade to 11 might resolve it. It's on my to-do list sometime in the next month or two. I can report back then. 

Aside from that, I have no idea what else to look at.

**Comment by snipe** [comment]
I can't see why a Debian upgrade would cause this issue here and not elsewhere in other notifications in the system though. They all use the same general methods.

**Comment by inietov** [comment]
Yeah, I can't reproduce this either. :(
If OP finds more details in their logs, or someone else in the thread can reproduce and contribute more details, feel tree to reopen this.
