### ISSUE TITLE
API Call for Label not showing correct label

### ISSUE THREAD

**Issue by sh-hilden** [grokability/snipe-it#10819]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If I call the API for a label at http://domain.test/hardware/123/label I got multiple labels without any barcode and QR-Code

### Reproduction steps

1. Call the API at http://domain.test/hardware/123/label 

### Expected behavior

Single label API Call

### Screenshots

![grafik](https://user-images.githubusercontent.com/34846956/158229786-73432dc3-4a30-4eb0-8e05-d08ffc917640.png)

### Snipe-IT Version

v5.4.1 build 6746 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.2.24-0ubuntu0.18.04.11

**Comment by snipe** [comment]
I'm not able to reproduce this.

<img width="616" alt="Screen Shot 2022-03-21 at 1 48 23 PM" src="https://user-images.githubusercontent.com/197404/159274715-d394fd6d-0b8f-471d-8352-ed174a73796a.png">

> If I call the API for a label at http://domain.test/hardware/123/label I got multiple labels without any barcode and QR-Code

That URL doesn't look like an API call, so I'm not really sure what you're doing here or how to reproduce it.

**Comment by snipe** [comment]
If I type that URL directly into the browser, I can reproduce this, but when would you do that?

**Comment by snipe** [comment]
This isn't a bug, exactly, from what I can tell, since the url isn't expecting a hardware ID number (so I don't even know how you'd get to this page), but I have a fix on develop.

**Comment by snipe** [comment]
This isn't a bug, exactly, from what I can tell, since the url isn't expecting a hardware ID number (so I don't even know how you'd get to this page), but I have a fix on develop.
