### ISSUE TITLE
upgrade to 5.4.1 failed - [Fruitcake\Cors\HandleCors] does not exist.

### ISSUE THREAD

**Issue by King-GO** [grokability/snipe-it#10815]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Debug mode:
Illuminate \ Contracts \ Container \ BindingResolutionException
Target class [Fruitcake\Cors\HandleCors] does not exist.
Previous exceptions
Class Fruitcake\Cors\HandleCors does not exist (-1)

0 
Illuminate\Foundation\Http\Kernel terminate
…\public\index.php63

9
Illuminate\Contracts\Container\BindingResolutionException 
…\vendor\laravel\framework\src\Illuminate\Container\Container.php805
8
ReflectionException 
…\vendor\laravel\framework\src\Illuminate\Container\Container.php803
7
ReflectionClass __construct
…\vendor\laravel\framework\src\Illuminate\Container\Container.php803
6
Illuminate\Container\Container build
…\vendor\laravel\framework\src\Illuminate\Container\Container.php681
5
Illuminate\Container\Container resolve
…\vendor\laravel\framework\src\Illuminate\Foundation\Application.php785
4
Illuminate\Foundation\Application resolve
…\vendor\laravel\framework\src\Illuminate\Container\Container.php629
3
Illuminate\Container\Container make
…\vendor\laravel\framework\src\Illuminate\Foundation\Application.php770
2
Illuminate\Foundation\Application make
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php209
1
Illuminate\Foundation\Http\Kernel terminateMiddleware
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php183
0
Illuminate\Foundation\Http\Kernel terminate
…\public\index.php63

### Reproduction steps

1. 5.3.10 > php upgrade.php 
in step 6 (need to didscard changes)
```
- Syncing filp/whoops (2.13.0) into cache

    0 [>---------------------------]    0 [>---------------------------]    0 [>---------------------------]    barryvdh/laravel-cors has modified files:
```
[RuntimeException]
 Source directory C:\xampp\htdocs\snipe-it\vendor\symfony\polyfill-php80 has unpushed changes on the current branch:

2. 500 | Server Error

3. Try php upgrade.php again, 
In step 3, 
```
In ClassLoader.php line 478:

include(C:\xampp\htdocs\snipe-it\vendor\composer/../barryvdh/laravel-cors/src/ServiceProvider.php): failed to open stream: No such file or directory
```

4. still 500 | Server Error
...

### Expected behavior

as usual, upgrade successfully 

### Snipe-IT Version

5.3.10

### Operating System

Windows

### Web Server

XAMPP

### PHP Version

7.4.12

**Comment by King-GO** [comment]
try composer install, composer version 2.0.11

`[RuntimeException]
Source directory C:\xampp\htdocs\snipe-it\vendor\symfony\polyfill-php80 has unpushed changes on the current branch:`

**Comment by King-GO** [comment]
Solve the problem using the "[Moving Snipe-IT](https://snipe-it.readme.io/docs/moving-snipe-it)" approach.

**Comment by uberbrady** [comment]
Cool, are you saying that you were able to solve the problem by using that approach? If so, that’s great! Please close the issue.

If you’re still having trouble with that, please do say so and we’ll try and help get you across the finish line.

**Comment by geoffbernard-bw** [comment]
I'm running into the same issue on Ubuntu 20.04 using git upgrade.
Upgrading from 5.3.10 -> 5.4.1

**php upgrade.php**
```
 - Syncing filp/whoops (2.13.0) into cache
    0 [>---------------------------]    0 [>---------------------------]    0 [>---------------------------]    barryvdh/laravel-cors has modified files:
    M .gitignore
    M .travis.yml
    M LICENSE
    M changelog.md
    M composer.json
    M config/cors.php
    M phpunit.php
    M phpunit.xml
    M readme.md
    M src/HandleCors.php
    8 more files modified, choose "v" to view the full list
    Discard changes [y,n,v,d,?]?

Answering "n" gives this:
 [RuntimeException]
  Update aborted
```

 **composer install --no-dev -prefer-source**
```
 - Syncing filp/whoops (2.13.0) into cache
    barryvdh/laravel-cors has modified files:
    M .gitignore
    M .travis.yml
    M LICENSE
    M changelog.md
    M composer.json
    M config/cors.php
    M phpunit.php
    M phpunit.xml
    M readme.md
    M src/HandleCors.php
    8 more files modified, choose "v" to view the full list
    Discard changes [y,n,v,d,?]? n


  [RuntimeException]
  Update aborted
```

Not sure what I'm missing but I would rather not have to move & reinstall. Any help would be appreciated.

**Comment by snipe** [comment]
Just run the `composer install` manually and answer `n`. If it gets stuck when you re-run it, try it again and answer `y`. I've seen this a few times when I KNOW I didn't change the vendor files.

**Comment by uberbrady** [comment]
I think this is some super-weird cr/nl thing, maybe? (windows vs. unix linefeed issue) 

No one regularly edits their vendor files so I seriously doubt that multiple people have done that.

I agree with @snipe that if you run it by hand, and answer appropriately, you should be in good shape. I can't figure out *why* it's assuming there's some kind of git status in your vendors directory though.

I would probably say that you can blow out your `./vendors` directory (recursive delete), and re-run `composer install` - **AFTER HAVING RUN A BACKUP OF COURSE!!!**

But this _feels_  like a line-endings issue on a non-line-ending-sensitive filesystem (macOS and Windows come to mind)?

Super-weird though. Shouldn't happen.

**Comment by geoffbernard-bw** [comment]
@uberbrady That did the trick. 
```
cd /var/www/snipeit/vendor
rm -fr *
php upgrade.php
```
Step 6 (Updating composer dependencies) showed a bunch of syncing then installing packages. Once done, everything is working again. 
Thanks so much for the quick response & resolution!
