### ISSUE TITLE
Unaccepted Assets

### ISSUE THREAD

**Issue by bunzladi** [grokability/snipe-it#10810]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello people
When I press unaccepted assets in my Snipe IT, I get the 500 | Server Error. 
It is the V6.0.0-RC-4

### Reproduction steps

1.Go to Reports
2.Click on unaccepted Assets

### Expected behavior

It should list the unaccepted Assets. 

### Screenshots

![image](https://user-images.githubusercontent.com/92428604/157640451-7e962536-ebc4-4903-805d-4503c138c69c.png)
![image](https://user-images.githubusercontent.com/92428604/157640512-6eebe4ef-01a2-4df1-8607-63a98c37946c.png)

### Snipe-IT Version

v6.0.0-RC-4 build 6754 (gafd83311a)

### Operating System

Windows Server

### Web Server

IIS

### PHP Version

7.4.13

### Operating System

Windows 10

### Browser

MS Edge

**Comment by inietov** [comment]
It's because of windows >:(...

Nah, just kidding. I think I have a little idea of what can be happening, but I would love to see an error log to confirm my thought.

**Comment by bunzladi** [comment]
Here I hope this fits:
0 C:\\inetpub\\wwwroot\\snipe-dev\
esources\\views/reports/unaccepted_assets.blade.php(74): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php(107): require('C:\\\\inetpub\\\\wwwr...')
#2 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#3 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#4 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\livewire\\livewire\\src\\ComponentConcerns\\RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#5 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\CompilerEngine.php(61): Livewire\\CompilerEngineForIgnition->evaluatePath()
#6 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\facade\\ignition\\src\\Views\\Engines\\CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get()
#7 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\livewire\\livewire\\src\\ComponentConcerns\\RendersLivewireComponents.php(35): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()
#8 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(139): Livewire\\CompilerEngineForIgnition->get()
#9 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(122): Illuminate\\View\\View->getContents()
#10 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(91): Illuminate\\View\\View->renderContents()
#11 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php(69): Illuminate\\View\\View->render()
#12 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php(35): Illuminate\\Http\\Response->setContent()
#13 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(820): Illuminate\\Http\\Response->__construct()
#14 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(789): Illuminate\\Routing\\Router::toResponse()
#15 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(721): Illuminate\\Routing\\Router->prepareResponse()
#16 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#17 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#19 C:\\inetpub\\wwwroot\\snipe-dev\\app\\Http\\Middleware\\AssetCountForSidebar.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\AssetCountForSidebar->handle()
#21 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#23 C:\\inetpub\\wwwroot\\snipe-dev\\app\\Http\\Middleware\\CheckForTwoFactor.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckForTwoFactor->handle()
#25 C:\\inetpub\\wwwroot\\snipe-dev\\app\\Http\\Middleware\\CheckLocale.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckLocale->handle()
#27 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#29 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#31 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#33 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#35 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#36 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRoute()
#37 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#38 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#39 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#40 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\livewire\\livewire\\src\\DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Livewire\\DisableBrowserCache->handle()
#42 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#44 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#46 C:\\inetpub\\wwwroot\\snipe-dev\\app\\Http\\Middleware\\PreventBackHistory.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\PreventBackHistory->handle()
#48 C:\\inetpub\\wwwroot\\snipe-dev\\app\\Http\\Middleware\\SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\SecurityHeaders->handle()
#50 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#52 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#53 C:\\inetpub\\wwwroot\\snipe-dev\\app\\Http\\Middleware\\CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckForDebug->handle()
#55 C:\\inetpub\\wwwroot\\snipe-dev\\app\\Http\\Middleware\\CheckForSetup.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckForSetup->handle()
#57 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#59 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#61 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#63 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#64 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#66 C:\\inetpub\\wwwroot\\snipe-dev\\app\\Http\\Middleware\\NoSessionStore.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\NoSessionStore->handle()
#68 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#70 C:\\inetpub\\wwwroot\\snipe-dev\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#71 C:\\inetpub\\wwwroot\\snipe-dev\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#72 {main}

**Comment by inietov** [comment]
Oh, not what i thought... maybe try running 'composer install'?

**Comment by bunzladi** [comment]
Did it, but it comes back exactly the same error.

**Comment by dampfklon** [comment]
I missed one variable rename when working on the report. I just opened a PR which should fix the error.

**Comment by bunzladi** [comment]
Ok, thank you. I will close this Issue now.
