### ISSUE TITLE
Error when printing user->"Print all assigned" (v6.0.0-RC-4 - build 6754)

### ISSUE THREAD

**Issue by guiluxdj** [grokability/snipe-it#10826]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Error when printing user->assets assigned

### Reproduction steps

1. go to View User
2. Click button "Print all assigned"
3.
...

### Expected behavior

syntax error, unexpected 'general' (T_STRING), expecting ')'

### Screenshots

![image](https://user-images.githubusercontent.com/26114260/158610569-ea07fc41-aa56-4eb0-b1cd-da0d87c78de7.png)

![image](https://user-images.githubusercontent.com/26114260/158610376-b04ce7d0-fb13-44d4-a1f9-73e5253457f7.png)

### Snipe-IT Version

v6.0.0-RC-4 - build 6754

### Operating System

Windows and Ubuntu

### Web Server

Apache

### PHP Version

7.4.14

### Operating System

Windows

**Comment by snipe** [comment]
Thanks for the bug report! This is fixed on `develop` now :)
