### ISSUE TITLE
Unable to add maintenance without global super user permission

### ISSUE THREAD

**Issue by palmeraeasd** [grokability/snipe-it#10835]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Users assigned with group permissions are unable to add asset maintenance unless the group is set to global super user.

### Reproduction steps

1. Assign user to permission group with anything other than global super user
2. user is unable to add a maintenance item to an asset. Gets the sad panda page.

### Expected behavior

User should be able to add a maintenance item if they are given full permissions under 'asset'

### Snipe-IT Version

v5.4.0 - build 6685

### Operating System

Ubuntu 20.04 Server

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

MacOS

### Browser

Chrome

**Comment by snipe** [comment]
Please try upgrading. I believe this has already been fixed.
