### ISSUE TITLE
Option to hide cost from end-user

### ISSUE THREAD

**Issue by michaelredus** [grokability/snipe-it#10837]
### Snipe-IT Version

5.4.0

### Operating System

Server 2019

### Web Server

IIS 10

### PHP Version

7.4.13

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

We would like to be able to hide purchase costs from normal users.

### Describe the solution you'd like A clear and concise description of what you want to happen.

This could be added as a permission option, similarly to the "View License Keys" permission. For our application, we'd even be okay with a toggle in settings to hide it globally for everyone except super users.

**Comment by carsonh4te** [comment]
+1 id love to see this become a feature, there's an option "View purchase-cost column" but with it disabled I was still able to see purchase costs as a normal user

**Comment by BirkirMBL** [comment]
+1 For this feature :) 
The current setting only applies if the item is checked out to the user

**Comment by coopikoop** [comment]
+1 for this

**Comment by mauro-miatello** [comment]
I've seen the option "View Purchase-Cost Column", 
I'll do some tests but it seems to DON'T satisfy the request, right? 
I've created a group and even if the option is deny the users can see it
it would also be useful to have a sales price field

**Comment by hegdemaahi24** [comment]
@snipe when we expect this option to be removed. We dont like users view the Price of any assets as it should be confidential. After we have upgraded to a latest the price is visible to all users. Please give a option to remove the purchase cost to field on View Assigned Asset Page

**Comment by snipe** [comment]
This has been implemented already, quite some time ago. 2022, in fact. #12242

<img width="1072" alt="Screenshot 2024-05-06 at 6 15 08 PM" src="https://github.com/snipe/snipe-it/assets/197404/36218cb0-99fe-45d4-8af6-a76aa5e2921b">

**Comment by AbdallaHelix** [comment]
> This has been implemented already, quite some time ago. 2022, in fact. #12242
> 

@snipe this doesnt work for me. I changed the permissions of the user to deny view purchase cost but when logging with the user i still see the purchase cost. any idea why?

**Comment by snipe** [comment]
Check that the user is not part of an additional permission group that overrides that setting.

**Comment by Breezelaters** [comment]
This doesn't work for me either. I started fresh with a new user and new group to test preventing viewing purchase-cost columns, but the prices remain visible.

**Comment by snipe** [comment]
@Breezelaters Cannot reproduce this. Provide more info and screenshots please.

<img width="1497" alt="Screenshot 2024-09-02 at 8 18 51 PM" src="https://github.com/user-attachments/assets/1c83517b-2ab4-4163-ad70-2df75e36fa00">

**Comment by Breezelaters** [comment]
Sure thing. Here I am logged in as my limited test user and looking at the all assets list.

![image](https://github.com/user-attachments/assets/4bc80f3e-0b23-434b-9df8-fdc5b2cb8103)

**Comment by snipe** [comment]
@Breezelaters  that permission is under "Self". If you have access to *manage assets* via the assets section, you'll be able to see the price. The "Self" permission relates to the Account > View Assets page (assets assigned to you), not assets overall.

**Comment by Breezelaters** [comment]
My use case is to allow a client technical user to view all of their company assets, but not view purchase prices (my cost). Sounds like this is not supported yet?

**Comment by AbdallaHelix** [comment]
I agree with @Breezelaters . The specific need to hide cost is from our internal end-users or if we need to give access to an external user to view our assets and licenses without being able to see the cost. My use case is that i would like all my end users to view all the licenses inventory that is not assigned to them without the ability to see the cost. As i understood from @snipe that the current availble use case to hide the cost is only for the assigned assets to the end user which really doesnt help much.@snipe is there any workaround for my use case?

**Comment by Breezelaters** [comment]
I would love to see this as a future feature / feature request. Any chance to reopen this?
