### ISSUE TITLE
Upgrading to RC error

### ISSUE THREAD

**Issue by Mikmokster** [grokability/snipe-it#10839]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I get this error after upgrading from master to develop (RC)

In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() mus
  t be of the type string, null given, called in C:\xampp\htdocs\AMS\vendor\l
  aravel\framework\src\Illuminate\Foundation\Bootstrap\SetRequestForConsole.p
  hp on line 32

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Upgrade

### Snipe-IT Version

v6.0.0-RC-5

### Operating System

Windows

### Web Server

XAMPP

### PHP Version

7.4

### Error messages

```shell
In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() mus
  t be of the type string, null given, called in C:\xampp\htdocs\AMS\vendor\l
  aravel\framework\src\Illuminate\Foundation\Bootstrap\SetRequestForConsole.p
  hp on line 32
```

### Additional context

Upgrade

**Comment by snipe** [comment]
I haven't been able to reproduce this anywhere :( Is there any other info you can provide? Where exactly are you seeing this? Command line or in the browser? Is it possible your cli and your web server are running different versions of PHP? (It does happen sometimes, tho less common in XAMPP I think)

**Comment by hphit** [comment]
In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in /var/www/snipe-it/vendor/laravel/framework/src/Illu
  minate/Foundation/Bootstrap/SetRequestForConsole.php on line 32

**Comment by snipe** [comment]
Are you able to upgrade to the latest release?

**Comment by uberbrady** [comment]
Hrm, are you 100% sure you're using PHP 7.4 ? I don't remember when exactly errors about null instead of string came around, but I think that's in much later versions of PHP, like 8.2 or 8.1 or so?

Can you run `composer install` and do you get anything better when you do that?

**Comment by hphit** [comment]
> Are you able to upgrade to the latest release?

not yet, i'm having this issues:
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- check your PHP version and extension requirements
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (7.4.29) is at least 7.4.0 - continuing...
FYI: The php.ini used by this PHP is: /etc/php/7.4/cli/php.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ sodium is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

--
In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in /var/www/snipe-it/vendor/laravel/framework/src/Il
  luminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32




--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

--
In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in /var/www/snipe-it/vendor/laravel/framework/src/Il
  luminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32



--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 17 (delta 5), reused 13 (delta 4), pack-reused 0
Unpacking objects: 100% (17/17), done.
From https://github.com/snipe/snipe-it
   a050be873..1c32dcae9  master     -> origin/master
   a050be873..1c32dcae9  develop    -> origin/develop
 * [new branch]          snyk-fix-a992b5202c0c6f1bc0166bb6963a1648 -> origin/snyk-fix-a992b5202c0c6f1bc0166bb6963a1648
Already on 'master'
-- Saved working directory and index state WIP on master: a050be873 Merge pull request #11080 from snipe/fixes/remove_sr_only_for_backup_file
-- M    public/uploads/barcodes/invalid_barcode.gif
M       storage/private_uploads/signatures/.gitkeep
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
-- Updating a050be873..1c32dcae9
Fast-forward
 app/Console/Commands/LdapSync.php          | 6 ++++--
 app/Console/Commands/ResetDemoSettings.php | 1 +
 2 files changed, 5 insertions(+), 2 deletions(-)

--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ No bootstrap/cache/services.php, so nothing to delete.
√ No bootstrap/cache/config.php, so nothing to delete.

--
In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in /var/www/snipe-it/vendor/laravel/framework/src/Il
  luminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32


--
In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in /var/www/snipe-it/vendor/laravel/framework/src/Il
  luminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32


--
In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in /var/www/snipe-it/vendor/laravel/framework/src/Il
  luminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32


--
In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in /var/www/snipe-it/vendor/laravel/framework/src/Il
  luminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32



--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.

Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
Generating optimized autoload files

In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() mus
  t be of the type string, null given, called in /var/www/snipe-it/vendor/lar
  avel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php
   on line 32




In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() mus
  t be of the type string, null given, called in /var/www/snipe-it/vendor/lar
  avel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php
   on line 32


--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------


In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in /var/www/snipe-it/vendor/laravel/framework/src/Il
  luminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32



--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

--
In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in /var/www/snipe-it/vendor/laravel/framework/src/Il
  luminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32



---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!
--------------------------------------------------------


<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">GitHub - snipe/snipe-it: A free open source IT asset/license management system</a></strong></div><div>A free open source IT asset/license management system - GitHub - snipe/snipe-it: A free open source IT asset/license management system</div></blockquote>

**Comment by hphit** [comment]
> 

when i do it, i have this:
 composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 32 installs, 0 updates, 0 removals
As there is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' or '7z' (21.01+) may remediate them.
  - Installing fakerphp/faker (v1.19.0): Extracting archive
  - Installing php-webdriver/webdriver (1.12.0): Extracting archive
  - Installing laravel/dusk (v6.22.1): Extracting archive
  - Installing hamcrest/hamcrest-php (v2.0.1): Extracting archive
  - Installing mockery/mockery (1.5.0): Extracting archive
  - Installing symfony/yaml (v5.4.3): Extracting archive
  - Installing n98/junit-xml (1.1.0): Extracting archive
  - Installing overtrue/phplint (3.0.6): Extracting archive
  - Installing phpunit/php-token-stream (3.1.3): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (2.3.4): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.5): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.15): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.11.0): Extracting archive
  - Installing phpunit/phpunit (9.5.18): Extracting archive
  - Installing symfony/dom-crawler (v4.4.39): Extracting archive
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in /var/www/snipe-it/vendor/laravel/framework/src/Il
  luminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by snipe** [comment]
What do you have in your .env for APP_URL?

**Comment by hphit** [comment]
> What do you have in your .env for APP_URL?

if you mean from the file app.php is from config
'url' =>  env('APP_URL', 'http://localhost'),

**Comment by snipe** [comment]
No, in your .env file

**Comment by hphit** [comment]
> No, in your .env file

where is it?

**Comment by snipe** [comment]
In your snipe-it directory.

**Comment by snipe** [comment]
`/var/www/snipe-it/.env`

**Comment by hphit** [comment]
APP_URL=null

**Comment by hphit** [comment]
> `/var/www/snipe-it/.env`

i put APP_URL=localhost
and no more issues, thanks a lot.
![image](https://user-images.githubusercontent.com/72673604/168494213-4c5951c7-6e54-4111-a9cd-be3ad1d56eff.png)

**Comment by snipe** [comment]
Per the docs, you want to use the domain and protocol, so `http://localhost` or `https://localhost` if you are running over SSL

**Comment by metacraft-hq** [comment]
APP_URL=http://localhost:8000
Solved the issue

**Comment by jcnengel** [comment]
Then it might make sense to adjust the .env.example accordingly as it currently specifies APP_URL=null by default.

**Comment by snipe** [comment]
@jcnengal - it’s set to null on purpose, so that you know to update it. local host will not work for every setup, and there’s no way for us to know what your URL is. The upgrade.php script tries to check your URL for you to make sure that it’s not null, but at the end of the day it’s your job to read the config docs. APP_URL has always been required.
