### ISSUE TITLE
Missleading documentation informations

### ISSUE THREAD

**Issue by MaKaNu** [grokability/snipe-it#10834]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The [Import Assets](https://snipe-it.readme.io/docs/importing#common-fields)  Page states that the field Item Name is not required. This seems logically false and also results in an error message while importing. Maybe I totally misunderstand the column "required".

### Reproduction steps

1. create csv-file with at least one entry. I did it with License type
2. fill the License information but do not enter an "Item Name"
3. try to import the file: `> php artisan snipeit:import ~/test.csv --item-type License`
4. add now an "Item Name"
5. try again: `> php artisan snipeit:import ~/test.csv --item-type License`

### Expected behavior

The documentation should state "Item Name" as required or describe better what the "required" term describes.

### Snipe-IT Version

5.3.8

### Operating System

debian

### Web Server

Apache2

### PHP Version

7.4.28

**Comment by snipe** [comment]
It's required for all things except assets.

**Comment by MaKaNu** [comment]
Does it makes sense to extand the documentation at that point?

Example:

Instead of 

**Common Fields**

|Field | Example Data | Required | Notes
-- | -- | -- | --
|Item Name | Karen 2015 | No |  

Something like this:

**Common Fields**

|Field | Example Data | Required | Notes
-- | -- | -- | --
|Item Name | Karen 2015 | No(assets)/Yes(others) |
