### ISSUE TITLE
LDAP Sync Fails With Google Secure LDAP 

### ISSUE THREAD

**Issue by jacobgude** [grokability/snipe-it#10836]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Unable to configure Google secure ldap. Followed all of the instructions and get the following error message.

 Connection to LDAP server ldaps://ldap.google.com failed. Verify that the LDAP hostname is entered correctly and that it can be reached from this web server. Server Responded with error: Can't contact LDAP serve

### Reproduction steps

1. Followed steps to enable Google LDAP with no luck.
2.
3.
...

### Expected behavior

Access Google LDAP

### Snipe-IT Version

Version v5.3.1 - build 6490 (master)

### Operating System

Docker 

### Web Server

Apache

### PHP Version

7.4

### Operating System

Mac

### Browser

Chrome, Safari 

### Version

Latest

**Comment by uberbrady** [comment]
Hrm. I wonder if there are some OpenSSL libs that we're missing in our Docker setup. I bet so.

**Comment by sneak-it** [comment]
Same issue here, not on Docker, but Debian 11 Bullseye. Stable version 5.4.1 and v6.0.0-RC-5. Tried suggested workarounds in #10506 with no luck.

**Comment by CodeNameTheOnlyOne** [comment]
another one with an issue here.
v5.4.3 build 6812 on AlmaLinux release 8.5 (Arctic Sphynx)
not running in docker.
tried workarounds in #10506 with no change.

after running a packet capture i am seeing a unknown ca issue

TLSv1.3 Record Layer: Alert (Level: Fatal, Description: Unknown CA)

**Comment by sneak-it** [comment]
Seems like this issue has been resolved as of release v6.0.2
