### ISSUE TITLE
How to turn off the redirection of APP_URL

### ISSUE THREAD

**Issue by LJGxuyaohui** [grokability/snipe-it#10854]
### Snipe-IT Version

v5.4.1 build 6746 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

How to turn off the redirection of APP_URL, for example, I set the APP_URL as local 127.0.0.1:8080, and it will automatically jump to this address when accessing the LAN, resulting in inaccessibility. If I change it to the IP of the server, I can access it, but I If the port is forwarded by other software in the intranet, for example: example.com to access, he will still jump to the IP of the local area network. I don't know what I'm talking about is a bit complicated. In fact, I just want to turn off the redirection of APP_URL, use the LAN IP to access in the local area network, and use the domain name to access in the external network, without forcibly redirecting the URL. Thanks for answering.

### Describe the solution you'd like A clear and concise description of what you want to happen.

How to turn off the redirection of APP_URL

**Comment by snipe** [comment]
That’s not possible in Snipe-IT.

**Comment by uberbrady** [comment]
You can *try* to set: `APP_ALLOW_INSECURE_HOSTS` to `true` in your `.env` - I'm not sure how well that will work, but it's worth a shot.

**Comment by LJGxuyaohui** [comment]
> You can _try_ to set: `APP_ALLOW_INSECURE_HOSTS` to `true` in your `.env` - I'm not sure how well that will work, but it's worth a shot.

It seems to be ok, but suddenly I can't preview the picture, including the QR code and avatar
