### ISSUE TITLE
Create Asset error 500

### ISSUE THREAD

**Issue by andreaci** [grokability/snipe-it#10860]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When creating a new issue in v6, an error 500 is generated. The asset is actually saved in database.

```
[17:01:59] LOG.error: ErrorException: Undefined index: next_audit_date in /var/www/html/app/Observer...
ERRORLOG[17:01:59] LOG.error: Undefined index: next_audit_date {"userId":1,"exception":{}}
```

### Reproduction steps

1. Create new asset
2. Fill this fields only

![2022-03-23_17-05-42](https://user-images.githubusercontent.com/8290389/159744360-a79b3a21-3654-4ded-a082-81543d0a1efc.png)

3. Exception is generated
![2022-03-23_17-07-10](https://user-images.githubusercontent.com/8290389/159744419-5dbec2cc-336b-4873-86b6-d9dbe9edceaa.png)

4. 

### Expected behavior

Nice "saved" message :) 

### Snipe-IT Version

6.0-RC*

### Operating System

Docker

### Web Server

Docker

### PHP Version

Docker container

**Comment by guiluxdj** [comment]
+1 Found same bug ;-)

**Comment by andreaci** [comment]
> 

I created a pull release yesterday for this
