### ISSUE TITLE
Nothing listed under Recent Activity or Asset Categories

### ISSUE THREAD

**Issue by asaivan** [grokability/snipe-it#10872]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Nothing listed under Recent Activity or Asset Categories

### Reproduction steps

1. Open Dashboard of SnipeIT (v. 5.4.1)
2. Proceed to not see anything listed under Recent Activity or Asset Categories
3. Be sad
...

### Expected behavior

Activity listed under Recent Activity or Categories listed under Asset Categories

### Screenshots

![Screenshot 2022-03-26 132926](https://user-images.githubusercontent.com/658532/160255979-9911b5e0-361f-4cfe-8f22-7dab5f10b078.jpg)

### Snipe-IT Version

5.4.1

### Operating System

CentOS 7

### Web Server

Apache 2.4.6

### PHP Version

7.4

### Operating System

Windows

### Browser

99.0.4844.82 (Official Build) (64-bit)

### Version

Chrome

### Error messages

```shell
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLTableElement.<anonymous> ((index):944:35)
    at Function.each (all.js?id=1b9488168279292af5c4:1:96477)
    at C.fn.init.each (all.js?id=1b9488168279292af5c4:1:94957)
    at HTMLDocument.<anonymous> ((index):943:53)
    at u (all.js?id=1b9488168279292af5c4:1:123398)
    at c (all.js?id=1b9488168279292af5c4:1:123700)
```

**Comment by jaloney** [comment]
I have same issue. How is this fixed?

**Comment by asaivan** [comment]
I just "git fetch" and "git merge" the commit hash, and it fixed the issue.  Didn't seem to be a big commit so hasn't broken anything else so far.
