### ISSUE TITLE
v6 RC6 all lists empty (even in snipeit demo environment)

### ISSUE THREAD

**Issue by rytispublic** [grokability/snipe-it#10881]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

All lists in snipeit demo environment are empty.
For example:
https://develop.snipeitapp.com/hardware

Browser - Microsoft Edge 99.0.1150.55

### Reproduction steps

Check https://develop.snipeitapp.com

### Expected behavior

Lists should contain data :-)

### Snipe-IT Version

6 RC6

### Operating System

Linux

### Web Server

Apache

### PHP Version

-

**Comment by snipe** [comment]
Should be all set on develop now. Was an auto-merge gone weird.

**Comment by snipe** [comment]
I tagged a new RC for you
