### ISSUE TITLE
There are no assets in the manufacturers section

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#10886]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello. There are no assets in the manufacturers section. For example, there are asset models from the HP manufacturer, but if you look through the "manufacturer" section, these assets are not displayed.

### Reproduction steps

1.Manufacturers section
2.I choose the manufacturer of existing asset models
3.I choose the manufacturer of existing asset models

### Expected behavior

Assets should be displayed through the manufacturers section

### Screenshots

![31-1](https://user-images.githubusercontent.com/48224568/160991713-4d0056b8-97ec-4e23-949e-b51b6a158067.jpg)
![31-2](https://user-images.githubusercontent.com/48224568/160991725-ca8c074e-73a0-4653-976c-e5d497cb76c1.jpg)

### Snipe-IT Version

5.4.1

### Operating System

CentOS

### Web Server

Apache

### PHP Version

7.4.16

### Operating System

Windows 10

### Browser

Google Chrome, MS Edge...

### Version

last

**Comment by snipe** [comment]
I can’t reproduce this on the demo. https://demo.snipeitapp.com/manufacturers/1 - is there anything in your browser console? Tried pulling latest from master? 

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/manufacturers/1">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by UserGoodtm** [comment]
Thanks. Yes, the php command upgrade.php helped. Now the assets in the manufacturer section are displayed
