### ISSUE TITLE
Not able to connect to database 

### ISSUE THREAD

**Issue by ayush-9600** [grokability/snipe-it#10908]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The pre flight page is coming, but its saying the database is not connected. I have checked the port and all in .env file still the issue persists.
![WhatsApp Image 2022-04-06 at 11 56 41](https://user-images.githubusercontent.com/72152950/161909448-d3fd9667-f1e5-4d76-bb3e-1ee3e7180875.jpeg)
![WhatsApp Image 2022-04-06 at 11 58 03](https://user-images.githubusercontent.com/72152950/161909633-bdf5384a-ab42-4be0-be63-296d7682421c.jpeg)

### Reproduction steps

1.install snipe-it 
2.go to the server ip 
3.
...

### Expected behavior

I expected the database to be connected 

### Screenshots

![WhatsApp Image 2022-04-06 at 11 58 03](https://user-images.githubusercontent.com/72152950/161909673-2e60e3e5-afd1-4bd2-a6c9-c154b9f146fb.jpeg)
![WhatsApp Image 2022-04-06 at 11 56 41](https://user-images.githubusercontent.com/72152950/161909686-3da0e696-4fa2-4186-a521-c2928eae6b94.jpeg)

### Snipe-IT Version

6.0

### Operating System

ubuntu

### Web Server

Apache

### PHP Version

7.5

### Operating System

ubuntu

### Browser

google chrome

### Version

99

**Comment by snipe** [comment]
I’m not sure how to assist further on this. You’ll have to make sure the user+password is setup and correct in your MySQL database. That’s not something we have any control over. (I assume this is being used for testing purposes, as v6 is only an RC now.)

We haven’t changed that QuickStart in v6, so the connection checking is still the same. It simply tries to connect using whatever info you’ve given it in the .env.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
