### ISSUE TITLE
Docker: PHP-Redis extension is missing

### ISSUE THREAD

**Issue by asassoye** [grokability/snipe-it#10910]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

When i configure Redis in the configuration, i have this error: ` LogicException Please make sure the PHP Redis extension is installed and enabled.` with the https://hub.docker.com/r/snipe/snipe-it docker image with tag v5.4.1 (and also alpine version) 

When i install the php-redis package on the container everything works fine and the sessions and cache are stored in Redis. 

### Reproduction steps

Config:
```
CACHE_DRIVER: "redis"
SESSION_DRIVER: "redis"
REDIS_HOST: "my-redis-fqdm"
REDIS_PORT: "6379"
```

### Expected behavior

Snipe-it is using Redis for cache and for sessions

### Screenshots

![image](https://user-images.githubusercontent.com/22005211/162003591-31c1e9b4-5b17-4ea1-b7fd-4bacc4c99ffc.png)

### Snipe-IT Version

v5.4.1

### Operating System

Docker

### Web Server

Docker (Apache)

### PHP Version

7.4.3

**Comment by stavros-k** [comment]
It isn't installed on this version, it should have been added on v6, but I just checked composer file on master and it isn't there..
Relevant discussion:
https://github.com/snipe/snipe-it/discussions/10869

**Comment by snipe** [comment]
We’d happily take a PR for this. Redis is not commonly used with Snipe-IT, so I’m not exactly shocked it wasn’t added to the docker image. There are not many use cases I can think of that would require Redis here.

**Comment by stavros-k** [comment]
Well it was there.
Added here https://github.com/snipe/snipe-it/pull/4146
But removed here https://github.com/snipe/snipe-it/pull/7975

**Comment by snipe** [comment]
Again, we'd welcome a PR for it.

**Comment by denzfarid** [comment]
@snipe 
please review my pull request
thank you very much 😊🙏

---
@asassoye @stavros-k 
while waiting, you can create a new dockerfile like this

For alpine image ```Dockerfile.alpine```
```Dockerfile
FROM snipe/snipe-it:latest-alpine
RUN apk add --no-cache \
    php7-redis
```

this for ubuntu ```Dockerfile```

```Dockerfile
FROM snipe/snipe-it:latest
RUN apt-get update -qqy \
 && apt-get install -qqy --no-install-recommends \
php7.4-redis
```

**Comment by denzfarid** [comment]
@stavros-k @asassoye 
you can use develop branch or develop-alpin to prove this, currently I'm using develop-alpine with redis driver

![image](https://user-images.githubusercontent.com/1294403/172083356-63204654-b999-4da8-b7e0-ac236d74605f.png)

this redis keys
![image](https://user-images.githubusercontent.com/1294403/172083525-df9442fc-5c53-4b61-80f1-312983000dbb.png)
