### ISSUE TITLE
Employee name in "all assets" listing

### ISSUE THREAD

**Issue by guiluxdj** [grokability/snipe-it#10916]
### Snipe-IT Version

6.0.0-RC-5 - build 6772

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

Php 8

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Hi,
It's possible to add a "employee name or user name" column to asset to find out to whom the asset has been allocated?

### Describe the solution you'd like A clear and concise description of what you want to happen.

![image](https://user-images.githubusercontent.com/26114260/162220222-3bfdef9f-adb9-4513-abc6-7cb9f028c84d.png)

**Comment by snipe** [comment]
Both of the fields already exist. "Name" for full employee name, "Username" for username. 

<img width="1083" alt="Screen Shot 2022-04-07 at 3 25 43 PM" src="https://user-images.githubusercontent.com/197404/162222318-027f3d94-01f7-48be-9cd5-b4a5d9e2574f.png">

https://develop.snipeitapp.com/users

<blockquote><img src="https://develop.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://develop.snipeitapp.com/users">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by snipe** [comment]
I apologize for prematurely closing this ticket - there wasn't a lot of detail given, and I can't tell the context here because the screenshot is in French, and I don't speak French.

**Comment by guiluxdj** [comment]
Hi Snipe,
Sorry, it's in the ASSET interface, not users ;-)

**Comment by guiluxdj** [comment]
sorry my screenshot was not very clear

**Comment by snipe** [comment]
This context I'm not sure makes sense TBH - assets can be checked out to users, other assets or locations, so if your org uses Snipe-IT to only ever check out to locations, there wouldn't be a username or employee number. That's why we use the more generic "Checked out to" phrasing

**Comment by snipe** [comment]
(In other words, it could be confusing for an admin who never ever checks things out to users to have user-centric columns like username, employee number, etc.)

**Comment by guiluxdj** [comment]
Thank you, I saw "Checked out to ", that's what I was actually looking for ;-) but with the French translation, the term didn't speak to me. I made a new translation in crowdin, please review it because 'extrait vers' is really bad.
![image](https://user-images.githubusercontent.com/26114260/162382577-ee123cc0-0919-42c1-99b3-81ca12eea695.png)
