### ISSUE TITLE
Customize footer content

### ISSUE THREAD

**Issue by tent1234** [grokability/snipe-it#10921]
### Snipe-IT Version

5.1.8

### Operating System

7.6

### Web Server

2.4.6

### PHP Version

7.3.29

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

[](https://fanyi.baidu.com/translate?aldtype=16047&query=&keyfrom=baidu&smartresult=dict&lang=en2zh###)[](javascript:void(0);)
Customize the content in the lower left corner of the page. The default is“[Snipe-IT](https://snipeitapp.com/) is open source software, made with love by [@snipeitapp](https://twitter.com/snipeitapp).”

### Describe the solution you'd like A clear and concise description of what you want to happen.

[](https://fanyi.baidu.com/translate?aldtype=16047&query=&keyfrom=baidu&smartresult=dict&lang=en2zh###)[](javascript:void(0);)[](https://fanyi.baidu.com/translate?aldtype=16047&query=&keyfrom=baidu&smartresult=dict&lang=en2zh###)[](javascript:void(0);)
Custom display footer content

**Comment by snipe** [comment]
Please post GH issues in English.
