### ISSUE TITLE
WebP graphics don't always work.

### ISSUE THREAD

**Issue by CMCLAuto** [grokability/snipe-it#10934]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Images in the .webp format are listed as supported and do work some of the time, but largely don't display.

### Reproduction steps

1. Create a new asset model, upload a .webp image for it.
2. View the main asset list, image does not load.
3. View individual asset records, image does not load.

### Expected behavior

The .webp formatted images would display on all pages like they do initially on the Create Asset Model page. Other image formats like .JPG and .PNG are fine though.

### Screenshots

Creating an asset model on the Demo server (.webp file uploaded and showing correctly):
![Create Asset Model](https://user-images.githubusercontent.com/27863261/163021979-696cfe16-944f-49b5-85ba-c1d8cd97f307.PNG)

Viewing the Asset list on the Demo server (the Thunderbolt Dock at the bottom of the list, no image showing):
![Asset Model List](https://user-images.githubusercontent.com/27863261/163022152-185efff9-f04f-47ac-be40-c61d6feb1ca4.PNG)

Viewing the individual asset on the Demo server (asset KKT00018763, no image showing):
![Asset](https://user-images.githubusercontent.com/27863261/163022269-5586bdfe-f4e4-4581-be69-60e1191207ee.PNG)

### Snipe-IT Version

5.4.2

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

7.4

### Operating System

Windows 10

### Browser

Firefox, Chrome

### Version

99

### Additional context

Our server is an upgrade, thought this problem is reproducible on the demo server too. You can view the asset and model number I created and tested with there if they've not been erased. Model is the Dell Thunderbolt Dock WD19TBS, individual asset number is KKT00018763.

**Comment by snipe** [comment]
WebP support is browser-specific, so I'm not sure how we'd be doing anything specifically to monkey with that. (Also, just don't use WebP - they are problematic and often don't load in various email clients.)

**Comment by CMCLAuto** [comment]
Yeah, I don't much care for .webp either. I wouldn't use them at all except a lot of manufacturers are releasing product images in the format these days. Maybe I can just convert them. Thanks for looking!

**Comment by snipe** [comment]
I'll still definitely take a look - if they load in the browser on one page, they *should* load normally for any other places the images load in the same browser. 

But generally we do recommend against them because they're kind of unreliable - it's unfortunate, since I know a lot of product images are distributed in that format, but (for example) we just had to troubleshoot an issue with webp images not showing up in (what I presumed to be) Outlook, but they did show up for me (who uses Airmail.) As soon as the user switched to jpg, their email images loaded. :-/

**Comment by snipe** [comment]
What's weirder here is that I can't reproduce this locally. 

<img width="1622" alt="Screen Shot 2022-04-12 at 9 32 36 PM" src="https://user-images.githubusercontent.com/197404/163048784-d1929227-ef6c-42a1-acb6-65ffa30f716f.png">

<img width="1620" alt="Screen Shot 2022-04-12 at 9 33 43 PM" src="https://user-images.githubusercontent.com/197404/163048992-641dff12-4c5f-48ea-95d6-bbb47926bbde.png">

<img width="1623" alt="Screen Shot 2022-04-12 at 9 33 56 PM" src="https://user-images.githubusercontent.com/197404/163049023-0d012db1-a41d-4747-bd05-69b3a5b43276.png">

Is it possible it doesn't happen on smaller images that don't get resized? 

I downloaded the image from https://www.gstatic.com/webp/gallery/1.webp for my local tests and can't reproduce it. 


<blockquote></blockquote>

**Comment by CMCLAuto** [comment]
Oh yeah, maybe! The promotional images do usually have really high resolutions for what they are. The image I used was the 504x350 pixel _dell-docking-station-wd19tbs-campaign-hero-504x350-ng.webp_ from Dell's [product page](https://www.dell.com/en-us/work/shop/dell-thunderbolt-dock-wd19tbs/apd/210-azbi/pc-accessories) for the WD19TBS (the first picture in their carousel).

**Comment by CMCLAuto** [comment]
Well, maybe not. I just tried that 1.webp mountain valley shot on the demo server and it disappeared again.
![Asset Creation](https://user-images.githubusercontent.com/27863261/163180190-705455dd-92c9-42c3-8a26-e82a849bedb6.PNG)
![Asset Models](https://user-images.githubusercontent.com/27863261/163180207-d1fbfd8a-5e07-410c-948f-4dd5c6ee5db1.PNG)

It's really weird!

**Comment by snipe** [comment]
Well, shit. 

I can reproduce this on the demo, but not locally. 

I'm off today, but will take a look a little further tomorrow.

**Comment by CMCLAuto** [comment]
No rush! I'm glad it's not just me, it was really starting to sound like a personal bug.

**Comment by snipe** [comment]
Possibly some progress - when I set APP_LOCKED=true in my env, I can reproduce the issue, so it seems like this might only affect the demo? (That env var is only used to limit what people can do on the demo, since people are generally awful and we don't want them uploading bad things or changing the site name to something like "I hacked you hahaha".)

**Comment by snipe** [comment]
Interestingly, I can't upload png files or anything else when the app is locked. I might have done that by design, to prevent people from uploading porn.

**Comment by CMCLAuto** [comment]
Oh, I hadn't considered it being some sort of security setting. Our local server has APP_LOCKED=False in our .ENV, are there other security settings we might have restricting image types?

**Comment by snipe** [comment]
I don't think so? I'm not sure - there seems to be a pattern, I'm just still trying to figure it out. I don't think it's related to the actual image format tho. Hang tight.

**Comment by snipe** [comment]
I haven't forgotten about this issue - still just sorta stuck on where to look. :(

**Comment by Delta5** [comment]
I saw this issue recently on our install and resolved it by adding the MIME type in IIS for webp: https://www.itnota.com/serving-webp-image-iis/

Have you checked that @CMCLAuto?

<blockquote><img src="https://asset.itnota.com/wp-content/uploads/WebP-IIS-Success.png" width="48" align="right"><div><img src="https://asset.itnota.com/wp-content/themes/kinneloa/images/favicon.ico" height="14"> IT Nota</div><div><strong><a href="https://www.itnota.com/serving-webp-image-iis/">How to Serve WebP Image on IIS | IT Nota</a></strong></div><div>Step by step instruction to configure IIS Server to serve WebP file format (screenshots provided).</div></blockquote>

**Comment by snipe** [comment]
Ah, nice, @Delta5 - thanks for that fix!

**Comment by snipe** [comment]
I've added this to the documentation :)
https://snipe-it.readme.io/docs/windowsiis#serving-webp-images-on-iis 

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/windowsiis#serving-webp-images-on-iis">Windows/IIS</a></strong></div><div>Extract Snipe-IT to C:\inetpub\wwwroot\snipe-it (folder name can be changed but we will reference it as is shown here)Run IIS ManagerRight Click Sites and Add Website (See settings below)Click OK Your site will now appear in the list. IIS may not enable the DELETE, PUT, or PATCH verb by default. The...</div></blockquote>

**Comment by CMCLAuto** [comment]
Yep, that did it! Thanks for the help folks. Sorry I didn't close the topic sooner, the github notification emails just get lost in the shuffle.

**Comment by snipe** [comment]
Of course, no worries. Glad to hear the fix worked for you!
