### ISSUE TITLE
LDAP issue

### ISSUE THREAD

**Issue by kkolisjwd** [grokability/snipe-it#10930]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Connection to LDAP server ldap://jwddcpd02.quantaservices.local:389 failed. Verify that the LDAP hostname is entered correctly and that it can be reached from this web server. Server Responded with error: Invalid credentials

### Reproduction steps

1. Used different accounts
2.
3.
...

### Expected behavior

LDAP connection successful

### Screenshots

![image](https://user-images.githubusercontent.com/103441875/162776925-464a6e99-9e21-426e-b3aa-04231560bd8d.png)
![image](https://user-images.githubusercontent.com/103441875/162776987-e2772037-6508-4549-ab3d-f963e6d505a7.png)

### Snipe-IT Version

5.4.1

### Operating System

WINDOWS

### Web Server

IIS

### PHP Version

8.0.17

### Error messages

```shell
PS C:\inetpub\wwwroot\snipe-it> php -m
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_gd2.dll' (tried: C:\PHP\ext\php_gd2.dll (The specified module could not be found), C:\PHP\ext\php_php_gd2.dll.dll (The specified module could not be found)) in Unknown on line 0
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

### Additional context

Fresh install.
Server 2019
Manual install

**Comment by dwildey** [comment]
@snipe 

I upgraded to PHP 8.0 had similar problems with AD Sync.  From my debugging, it appears that the "ldap_control_paged_result" has been removed from ver 8.0 and deprecated in 7.4.   See-> https://www.php.net/manual/en/function.ldap-control-paged-result.php

For now, I am going to downgrade PHP.    Maybe at some point, logic can be put in to detect which version of PHP is installed to make the correct call.

<blockquote><img src="https://www.php.net/favicon.ico" width="48" align="right"><div><strong><a href="https://www.php.net/manual/en/function.ldap-control-paged-result.php">PHP: ldap_control_paged_result - Manual</a></strong></div></blockquote>

**Comment by snipe** [comment]
Snipe-IT v5 does not support PHP8 (per the requirements documentation) and the LDAP functionality was completely rewritten for the upcoming v6 (which does support PHP8.)
