### ISSUE TITLE
2 factor Authentication

### ISSUE THREAD

**Issue by okkhalid** [grokability/snipe-it#10949]
### Snipe-IT Version

5.4.3

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

5.4

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

how to change the label on Google Authenticator. when we add it, it shows: Snipe-IT (my site name).

How I can Add my Full Site name on Google Authenticator instead of Snipe-IT.

https://ibb.co/rFTLy4X

### Describe the solution you'd like A clear and concise description of what you want to happen.

how to change the title.

**Comment by T3chGuy77** [comment]
Not sure why you'd want this feature and this would not be a priority. I'm just happy it has 2FA. You could dig through the 2FA code and it's more than likely in the code.

**Comment by snipe** [comment]
You should be able to change that within your 2FA provider. For example, when you scan the initial QR code for Authy, you can change the name to whatever you want as you're adding it.
