### ISSUE TITLE
pdf upload such as invoice

### ISSUE THREAD

**Issue by okkhalid** [grokability/snipe-it#10947]
### Snipe-IT Version

5.4.3

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

No,

Is that possible to upload pdf invoice to the asset. as we need to upload each asset we record the pdf invoice?
I see we can only upload images, but that would be difficult, we like to attach pdf invoice.

### Describe the solution you'd like A clear and concise description of what you want to happen.

looking to upload the asset invoice in pdf

**Comment by snipe** [comment]
PDFs are already allowed. Go to the Files tab and click on the "Upload" icon in the right side.

<img width="1651" alt="Screen Shot 2022-04-17 at 4 25 34 PM" src="https://user-images.githubusercontent.com/197404/163721305-11a98938-7994-4a95-9dfe-e7f927735333.png">

<img width="680" alt="Screen Shot 2022-04-17 at 4 23 35 PM" src="https://user-images.githubusercontent.com/197404/163721088-cc29d156-6cfe-43eb-9243-9270f2a36c3b.png">

<img width="638" alt="Screen Shot 2022-04-17 at 4 25 10 PM" src="https://user-images.githubusercontent.com/197404/163721303-8755c59a-974c-4988-82db-4f9b4506eec2.png">
