### ISSUE TITLE
Inspite of Snipeit Webserver GUI getting code when trying to access server. 

### ISSUE THREAD

**Issue by samuelsugur** [grokability/snipe-it#10951]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have setup snipe it setup, hving php v7.4 and after accessing the webpage, the server doesnt show GUI but instead shows code - 

### Reproduction steps

1.
2.
3.
...

### Expected behavior

GET GUI but showing code register the Auto Loader 

### Screenshots

![16502961193727313788137136461071](https://user-images.githubusercontent.com/28801347/163832740-3f497fb4-6f0e-4657-9225-71ce5a83c277.jpg)

### Snipe-IT Version

NA

### Operating System

Centos 7

### Web Server

Apache

### PHP Version

7.4

### Browser

elinks tool

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/installation-issues#loading-the-snipe-it-app-shows-php-code-in-the-browser
