### ISSUE TITLE
Message blade defaults to "Snipe-IT" instead of site name

### ISSUE THREAD

**Issue by boring10** [grokability/snipe-it#10953]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If "Show images in emails" is not checked under General Settings then the only name that will appear in the emails for the brand will be "Snipe-IT".

Shouldn't it also check if there is a site name and use that as the default, if it exists, before defaulting to "Snipe-IT"?

Both HTML and markdown seem to be configured the same way <https://github.com/snipe/snipe-it/blob/9a0219eff72a8786eff8d2f9dc78b0b990ad1e63/resources/views/vendor/mail/html/message.blade.php>

### Reproduction steps

1. Uncheck "Show images in emails"
2. Ensure that there is a Site Name under Branding
3. Select any branding type (ideally text would work)
4. Send email alert/message
...

### Expected behavior

Default to the site name in the email instead of "Snipe-IT", if it exists, when the "Show images in emails" is unchecked specifically.

### Screenshots

<img width="442" alt="snipeit-message" src="https://user-images.githubusercontent.com/35600612/163887461-6f4f37a6-b958-4a66-95e3-cb428c98e8dd.png">

### Snipe-IT Version

5.4.3

### Operating System

N/A

### Web Server

N/A

### PHP Version

7.4.28

### Operating System

N/A

### Browser

N/A

### Version

N/A

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Version

N/A

**Comment by snipe** [comment]
I believe this has already been fixed. Closing this issue now :)
