### ISSUE TITLE
all custom fields are displayed asset index page

### ISSUE THREAD

**Issue by veenone** [grokability/snipe-it#10959]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have multiple custom fields (almost 100 in total) with multiple models for my assets which exponentially growing the number of displayed column in the index page. this makes the user interface too overwhelmed with the number of growing column. it is difficult to go to the buttons (checkout, copy, edit, clone) as scrolling to the right with to be done every time.

### Reproduction steps

1. store multiple assets with different models & different numbers of custom fields
2. go to asset index page
3. check the displayed column

### Expected behavior

I think it would be great if these custom fields are not displayed by default. only the mandatory ones to be displayed. so they can still be available in the columns dropdown, but unchecked. this way it will be easier to manage the assets

### Screenshots

the number of column doesn't fit the screen
![image](https://user-images.githubusercontent.com/3839381/164219720-3c778253-6e18-4abe-9b99-5099f4510426.png)

need a little bit of time to scroll to the end of the column to get the checkout buttons
![image](https://user-images.githubusercontent.com/3839381/164219920-ebe622f9-1326-4cbf-acde-1c936910a608.png)
![image](https://user-images.githubusercontent.com/3839381/164219984-734bd62b-f170-48cb-8f5d-8d68c695d0f9.png)

### Snipe-IT Version

5.4.1 / 6.0.0-RC-5 

### Operating System

Windows

### Web Server

Apache & IIS

### PHP Version

7.4.2.1 & 7.4.27

### Operating System

Windows

### Browser

Chrome, Edge

### Version

100

**Comment by veenone** [comment]
I've found the solution and has implemented it in pr #10968

**Comment by snipe** [comment]
This is by design. Once you deselect them once, they will not appear visible by default again.
