### ISSUE TITLE
Slow Loading of all pages

### ISSUE THREAD

**Issue by waterweasel4** [grokability/snipe-it#10958]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Snipe IT (version v5.4.1 - build 6746 (master)) is installed on a t3a.small (2 VPCUs, 2GB of Memory, plenty of free disk space, RHEL 8.5 with all patches, NGINX with php-fpm, Aurora MySQL Serverless) but each page regardless of the number of content loads slowly (approximately 4-6 seconds per page).

We have narrowed it down a bit.  For example, running phpinfo() on a page, it loads instantly.  Viewing a static HTML/TXT page, it loads instantly.  Running a connection to the MySQL database but not querying any data, the connection takes 4-6 seconds).  This leads us to believe it's the database.  Is there any kind of tuning that can be on the database side?  We've even set the database temporarily to localhost rather than using RDS (took a dump of the RDS database and put it on localhost) and the same issues persist.

Turning on debug mode makes no difference in the site speed.   This kind of feels like a database issue given the steps we have tried but we're open to suggestions. 

### Reproduction steps

1.  Open Snipe-IT
2. Load any of the pages, even those pages without any data in the database
3. The connection takes approximately 4-6 seconds to load from the database
...

### Expected behavior

The expected behavior is quicker queries from the database.

### Snipe-IT Version

v5.4.1

### Operating System

RHEL

### Web Server

Nginx

### PHP Version

7.2.24

### Error messages

```shell
1. With debug on, there are no errors on the page.  Console (where ourUrl is the actual FQDN):


WARNING:
jQuery.Deferred exception: JSON.parse: unexpected character at line 1 column 1 of the JSON data each@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:96477
each@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:94957
@https://ourURL/:969:53
u@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:123398
EVdn/</Deferred/then/s/</c<@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:123700
setTimeout handler*EVdn/</Deferred/then/s/<@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:123909
l@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:121690
fireWith@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:122434
fire@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:122470
l@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:121690
fireWith@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:122434
ready@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:125404
U@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:125184
EventListener.handleEvent*EVdn/<@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:125553
EVdn/<@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:93619
EVdn@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:93732
i@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:112
HijD@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:182855
i@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:112
z0aP@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:439018
i@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:112
0@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:19551
i@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:112
@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:905
@https://ourURL/js/dist/all.js?id=1b9488168279292af5c4:1:914


ERROR:
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    <anonymous> https://ourUrl/:970
    each https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    each https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    <anonymous> https://ourUrl/:969
    u https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    c https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    setTimeout handler*EVdn/</Deferred/then/s/< https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    l https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    fireWith https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    fire https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    l https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    fireWith https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    ready https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    U https://ourUrljs/dist/all.js?id=1b9488168279292af5c4:1
    EVdn https://ourUrljs/dist/all.js?id=1b9488168279292af5c4:1
    EVdn https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    EVdn https://ourUrljs/dist/all.js?id=1b9488168279292af5c4:1
    i https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    HijD https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    i https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    z0aP https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    i https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    0 https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    i https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    <anonymous> https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1
    <anonymous> https://ourUrl/js/dist/all.js?id=1b9488168279292af5c4:1

The error cannot be reproduced on the demo site mentioned.

There are no logs in storage/logs

NGINX and server logs have no relevant data in the access or error logs.

The site is front-ended by an ELB on AWS if that matters at all?

Enabled modules in PHP are below:
[PHP Modules]
bcmath
bz2
calendar
cgi-fcgi
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]
```

### Additional context

1. Upgrade from the previous install
2. RHEL 8.5
3. install.sh was the method used to install Snipe-IT initially
4. See above.  No error messages even with debug turned on
5. No data was manually edited in the database

**Comment by uberbrady** [comment]
It should run perfectly fine on Aurora, but it sounds like you're now running the database locally as well. My initial guess is that maybe there's some kind of DNS thing happening - like reverse DNS isn't resolving a name somewhere, or something like that? I'm just clutching at straws here.

**Comment by waterweasel4** [comment]
Yeah, RDNS should be fine at least when I do the lookup.  I thought about that too.  I still want to blame the database if there's any kind of tuning we can do on it but I'm honestly not sure what else to look at.

**Comment by waterweasel4** [comment]
Just to follow up, this is 100% an RDS issue.  I fixed some permissions and moved the database to localhost on the server itself and ran the following:

```
php artisan config:clear
php artisan config:cache
```

I think the issue was partially permissions and partially the RDS issue.
