### ISSUE TITLE
D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: SQLSTATE[HY000] [1045] Access denied for user 'snipe-it2020'@'localhost' (using password: YES) (SQL: select 2 + 2)

### ISSUE THREAD

**Issue by escheffler2022** [grokability/snipe-it#10963]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Version of Snipe-IT you're running. 5.4.2
What OS and web server you're running Snipe-IT on: Windows Server 2019 Datacenter
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT Install
If you're getting an error in your browser, include that error. D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: SQLSTATE[HY000] [1045] Access denied for user 'snipe-it2020'@'localhost' (using password: YES) (SQL: select 2 + 2)
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Snipe-IT Pre-Flight
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console. N/A
Confirm whether the error is reproduceable [on the demo](https://snipeitapp.com/demo).
Include any additional information you can find in storage/logs and your webserver's logs. 
Include what you've done so far in the installation, and if you got any error messages along the way. [2022-04-15 17:45:02] production.ERROR: PDOException: SQLSTATE[HY000] [1045] 
Access denied for user 'snipe-it2022'@'localhost' (using password: YES) in 
C:\inetpub\wwwroot\snipe-it2022\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:39
Indicate whether or not you've manually edited any data directly in the database

### Reproduction steps

1. Access the Snipe-IT Pre-Flight page.
2. Validation stops at database
3. 
...

### Expected behavior

Trying to get to the Next: Create Database Tables

### Screenshots

![Snipe-IT Pre-Flight](https://user-images.githubusercontent.com/103442947/164484109-c9d61f24-41bb-417f-82b0-982e7a77e6a6.png)

### Snipe-IT Version

5.4.2

### Operating System

Windows Server 2019 Datacenter

### Web Server

IIS

### PHP Version

1.5.0

**Comment by snipe** [comment]
That seems pretty straightforward. Your database credentials are not correct.

**Comment by escheffler2022** [comment]
The credentials are correct, I have no issues accessing the database via the MariaDB session.

**Comment by taeys** [comment]
got the same issue now, after simply switching the server to a different IP address in the same subnet, eg. from 192.168.3.45 to 192.168.3.179 or something. no other edits have been made. we even went so far as to drop the database, delete the user, create a new database and a new user (but with the same credentials as in the .env). as @escheffler2022 points out our login to the database via the db session works, so there is nothing wrong with the credentials, yet we get this error.

**Comment by jon-kelley-oit** [comment]
I have the same issue. Cloned the repo, database is on the same machine, verified the password by copying and pasting from the .env file and works fine in the CLI.

**Comment by snipe** [comment]
If there was something wrong with the database connection capabilities within Snipe-IT, nobody's Snipe-IT would work though. I'd check your database user permissions (localhost vs 127.0.0.1, etc)

**Comment by jon-kelley-oit** [comment]
Database and .env file are set to use localhost. The following command also works as expected.

 mysql --host=localhost -u snipe_user -p snipeit -e "select 2+2"

**Comment by Schnax** [comment]
same issue here

**Comment by snipe** [comment]
Again, not really sure what to tell you here. We didn't change anything with respect to database connections, and if there was something broken within the system, literally nobody's Snipe-IT installs would work (including our thousands of customers.) You can possibly try `DB_HOST=127.0.0.1` instead of `DB_HOST=localhost`, but nothing we did on our end would matter there - it would have to be that something changed on the DB end of things.

**Comment by kengwall-ffld** [comment]
try `php artisan db` and check the output.  Look at the password that is being used.  It may be shorter than the actual password.  It appears that if the password is longer than 8 characters, it gets truncated to 8 characters.  Once I shortened the password in mariadb, it suddenly worked.  Make sure you actually shorten the password in the .env file as well, in case the bug gets fixed and it suddenly starts using the whole password.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by DrewRubin** [comment]
Hey for anyone finding this via google who is using a containerized environment: make certain that you are creating your secrets with echo **-n** 'secret'

Most applications do ignore the newlines, so you may have never had this problem with other applications.

**Comment by toddjacobs** [comment]
Your password likely has a "#" symbol contained in it, at least that was the issue I experienced.

This issue was identified in a forum post around the same time this one was made.

**Comment by Igel18** [comment]
Had the same issue running snipe it in a docker container. 
"D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: SQLSTATE[HY000] [2002] Connection refused (SQL: select 2 + 2)"
The reason for this was that the container had not the user rights to write files in this folder. 
I hope this helps someone.

**Comment by myaswanth03** [comment]
D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: SQLSTATE[HY000] [1045] Access denied for user 'snipe'@'172.19.0.3' (using password: YES) (SQL: select 2 + 2)

where we change ip?, I am not creating any .env file

![image](https://github.com/snipe/snipe-it/assets/92320746/7164eea9-f6f5-45ba-8464-eb62616674ec)

**Comment by levelsw** [comment]
> try `php artisan db` and check the output. Look at the password that is being used. It may be shorter than the actual password. It appears that if the password is longer than 8 characters, it gets truncated to 8 characters. Once I shortened the password in mariadb, it suddenly worked. Make sure you actually shorten the password in the .env file as well, in case the bug gets fixed and it suddenly starts using the whole password.

truncating the password to 8 characters fixed it for me

**Comment by wecovb** [comment]
Late to the party, I know. Had the same issue now. So I enclosed the password in single quotes in the .env file. That did the trick. Seems an issue with how Laravel deals with special characters. Hope this helps someone.

**Comment by Brooklyn-Mark** [comment]
Hopefully this saves someone else in this situation some time...

+1 for the Laraval MariaDB PW issue. I had set a strong password for my MariaDB/MYSQL Snipe-IT Database, which included special characters. I was running Snipe-IT in a linuxserver.io docker container fine for over a year and it randomly started giving me the 500 error after the last update. Logs (and loading the page in incognito) showed it had trouble logging into the database. 

I tried a bunch of things, which didn't work, but seems I could log into the database using the USER/PW in Adminer so I knew settings were right. I decided to try @toddjacobs solution and remove the special characters (still using more than 8 tho) and boom immediate login.

Hope this helps. Gonna just keep this special character free though as don't need hardened mysql database PW I realized.

**Comment by ariafshin** [comment]
I had the same issue i was confused because i did the installation same as the document that they provide only change i made as their document noted was changing my password, i randomly suspect to the .env file, database username and database name both were snipeit by changing either the database name or the username to something unique problem solved.

**Comment by prussell69** [comment]
I'm still having the same issue. I've tried to shorten my password < 8 chars. putting a single quote around my passwords, no special chars. Everytime I get the same error. If I run "docker compose exec app php artisan key:generate --show", I get a different result. Am I supposed to? 
What should I try next?
