### ISSUE TITLE
The home page displays a blank page

### ISSUE THREAD

**Issue by taotao-s** [grokability/snipe-it#10965]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I want to update 4.6.5 to 5.4.3，
Manual upgrade according to manual as "https://snipe-it.readme.io/docs/upgrading".
but home page displays a blank page and Unable to clear cache normally.
I don't know how to solve it.
thanks!

### Reproduction steps

1.download snipe 5.4.3
2.Rename snipe it directory
3.copy over the old .env and your OAuth keys in storage, as well as any files or folders in your public/uploads directory and your storage/private_uploads directory.
4.php composer.phar install --no-dev --prefer-source
   php composer.phar dump-autoload
   Clean the cache but is failed.
5.reboot IIS

### Expected behavior

How to solve this fault？

### Screenshots

![qinli](https://user-images.githubusercontent.com/104197188/164678438-27e35993-5b9e-4342-b002-5bf572db9024.png)
![2](https://user-images.githubusercontent.com/104197188/164678469-59abbc4a-adc6-4c55-aa48-df723d4e194d.png)

### Snipe-IT Version

5.4.3

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.2.11

### Operating System

Windows

### Browser

edge google

### Additional context

Is this a  upgrade,  manual upgrade

**Comment by snipe** [comment]
As indicated by the error in your screenshot, there is something invalid in your .env file.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
