### ISSUE TITLE
The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

### ISSUE THREAD

**Issue by CeamGhdMfrj** [grokability/snipe-it#10962]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When i start snipeit as an docker Container, I get the Error 
   UnexpectedValueException  : The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied
I'm using Docker version 20.10.14, build a224086

The Docker-compose i use is: 

version: '3'

services:
  snipeit:
    image: snipe/snipe-it:v5.4.3
    container_name: snipeit
    ports:
    - 8000:80
    env_file:
    - snipeit.env
    networks:
    - snipeit-backend
    volumes:
    - ./logs:/var/www/html/storage/logs

  redis:
    image: redis:latest
    networks:
    - snipeit-backend

networks:
  snipeit-backend: {}

The env File is not necessary. The same error happens without it. 

### Reproduction steps

1. docker compose up 
2.
3.
...

### Expected behavior

Not to get this error and to startup

### Snipe-IT Version

snipe/snipe-it:v5.4.3

### Operating System

Almalinux 8.5 64 Bit

### Web Server

the default from the container

### PHP Version

the default from the container

**Comment by snipe** [comment]
Have you tried changing the permission so that it is writable?

**Comment by CeamGhdMfrj** [comment]
Yes is tried that. The funny thing is, there are error messages in the file about the name being wrong.

**Comment by CeamGhdMfrj** [comment]
I also tried different versions of the snipeit container. Same issue.

**Comment by helinbei** [comment]
我也是这样，求解

**Comment by snipe** [comment]
@CeamGhdMfrj 

> The funny thing is, there are error messages in the file about the name being wrong.

Can you elaborate?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by jhgehrs** [comment]
I have this issue, so please re-open this issue. anyone who can help me?
