### ISSUE TITLE
New LDAP Users cannot login 

### ISSUE THREAD

**Issue by red2936** [grokability/snipe-it#10976]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

New LDAP synchronized users cannot sign in or existing LDAP users with recently changed passwords cannot sign in with their new passwords. LDAP sync works with no errors. 

### Reproduction steps

1. Configure LDAP Sync for Active Directory
2. Sync accounts
3. Try Login with LDAP account
...

### Expected behavior

Users should be able to login with AD username and password.

### Screenshots

![image](https://user-images.githubusercontent.com/8863518/165364488-c92db439-99d6-4e5d-aa3f-b8b075c832c0.png)
![image](https://user-images.githubusercontent.com/8863518/165364568-6f5dc6be-100f-45cf-9841-52491dcb0280.png)
![image](https://user-images.githubusercontent.com/8863518/165364640-1ae62deb-3cb9-4b25-a969-09d913554b13.png)

### Snipe-IT Version

5.4.3

### Operating System

Ubuntu 18.04

### Web Server

Apache

### PHP Version

7.4.29

### Operating System

Windows 11

### Browser

Edge and Google Chrome

### Error messages

```shell
[DEBUGLOG]
[12:06:36] LOG.debug: Preparing to test LDAP login
[12:06:36] LOG.debug: Connection failed

[From Browser]
POST https://snipeit.my.domain/api/v1/settings/ldaptestlogin 400 (Bad Request)
send @ all.js?id=1b9488168279292af5c4:1
ajax @ all.js?id=1b9488168279292af5c4:1
(anonymous) @ ldap:1215
dispatch @ all.js?id=1b9488168279292af5c4:1
m.handle @ all.js?id=1b9488168279292af5c4:1
all.js?id=1b9488168279292af5c4:1 

[No errors webserver log for this time]

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

LDAP integration has worked in the past. No changes to LDAP configuration. Followed docs related to LDAP setup for AD. AD is at a 2012 R2 functional level. Server was created on Dec 11, 2018, using git. Server is updated using the upgrade.php. Note: removed my domain url from logs and replaced it with my.domain

**Comment by uberbrady** [comment]
What's your LDAP filter set to?

**Comment by snipe** [comment]
Also have you tried upgrading to v6?

**Comment by red2936** [comment]
I'm happy to say that upgrading to 6.0.1 fixes my issue. Thank you.

**Comment by snipe** [comment]
Excellent, thanks for following up!
