### ISSUE TITLE
Unable to get the login attempts details if the user have check the remember me option in browser.

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#10974]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Don't know whether it's a bug or a feature. What I am facing is I am unable to track the login attempts. as I have created two accounts of my junior officers to maintain the Inventory System, but they have checked the "Remember me" option in their browser while entering the credential for the first time. Now my system isn't giving me any clue when they logged in except for that first login attempt. 

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Don't know whether it's a bug or a feature. What I am facing is I am unable to track the login attempts. as I have created two accounts of my junior officers to maintain the Inventory System, but they have checked the "Remember me" option in their browser while entering the credential for the first time. Now my system isn't giving me any clue when they logged in except for that first login attempt.

### Snipe-IT Version

v5.3.10 build 6684 (g05c081977)

### Operating System

Windows 10

### Web Server

Xampp

### PHP Version

7.4.27

### Operating System

Windows

**Comment by ghost** [comment]
I wish there will be an option in the setting and security tab, that if the user is inactive for a certain period of time the system log out the user. or if the user closes the page of the inventory system the system automatically logs out the user.  by this, we can resolve the issue of not being able to track the user login attempts. if he isn't logging out of the system after using the system.

**Comment by snipe** [comment]
@umaaarfaaarooq that would be in the .env file. https://snipe-it.readme.io/docs/configuration#optional-session-settings

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#optional-session-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required. Don't be intimidated by the length of this page. The configurati...</div></blockquote>

**Comment by ghost** [comment]
Thank you. The issue is resolved now.
