### ISSUE TITLE
Amazon SES data is not set correctly in .env and also not used correctly in config/services.php

### ISSUE THREAD

**Issue by chrisweirich** [grokability/snipe-it#10983]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If the Amazon SES driver is used for sending mails, not all data can be stored in .env or are not accepted correctly in config/services.php.

.env
```
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=ses
MAIL_HOST=email-smtp.us-west-2.amazonaws.com
MAIL_PORT=587
MAIL_USERNAME=YOURUSERNAME
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=you@example.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=you@example.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'
```

config/services.php
```
    'ses' => [
        'key'    => env('SES_KEY'),
        'secret' => env('SES_SECRET'),
        'region' => 'us-east-1',
    ],

```
### Reproduction steps

1. Change driver to 'ses'

### Expected behavior

Amazon SES should work

### Snipe-IT Version

v6.0.0-RC-7

### Operating System

Debian

### Web Server

nginx

### PHP Version

8.0.18

**Comment by chrisweirich** [comment]
I've created a pull request to solve this problem: [https://github.com/snipe/snipe-it/pull/10982](url)

**Comment by snipe** [comment]
We use SES on the hosted platform, so it does work, just not the way later versions of Laravel expect it to work

**Comment by chrisweirich** [comment]
If I see it correctly, Laravel 8 is used after all. In this there is the following instruction: https://laravel.com/docs/8.x/mail#ses-driver

In this guide you can choose the region, otherwise the IAM user would have to be created in us-east-1. But in the current config you can not overwrite the region. 

I understand that in Laravel 6 it was implemented in a different way, but I assumed that SnipeIT v6 would go back to the default of Laravel. If that is not the case, feel free to consider this issue resolved.

<blockquote><img src="https://laravel.com/img/og-image.jpg" width="48" align="right"><div><strong><a href="https://laravel.com/">Laravel - The PHP Framework For Web Artisans</a></strong></div><div>Laravel is a PHP web application framework with expressive, elegant syntax. We’ve already laid the foundation — freeing you to create without sweating the small things.</div></blockquote>

**Comment by chrisweirich** [comment]
Thank you for merging my PR #10982
