### ISSUE TITLE
Unable to logout with Google SAML

### ISSUE THREAD

**Issue by rafiron** [grokability/snipe-it#10980]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Google SAML, doesn't seem to provide an option to add SLS URL and it doesn't seem to support SLO. When the setting `SAML Single Log Out` is disabled and with `SAML Force Login` enabled, the user isn't able to log out.
On clicking on the logout button, there is a quick redirection to Google that happens and the user comes back on the same page but without getting logged out.

### Reproduction steps

Here are the steps which I followed when trying the Google SAML integration
1. Integrate Google SAML with SAML SLO setting disabled and save it
2. Enable SAML Force Login
3. Enable SAML Single Log Out -> User is not able to Logout 
4. Disable SAML Single Log Out -> User is still not able to Logout (tried creating a new Login session using in cognito mode but the same issue is present there as well)
...

### Expected behavior

Users should be able to successfully log out when they choose 'Logout' option from the website.

### Snipe-IT Version

v5.4.3 - build 6812

### Operating System

(hosted SnipeIT)

### Web Server

(hosted SnipeIT)

### PHP Version

(hosted SnipeIT)

**Comment by boring10** [comment]
Same here on the same version/build. I have 2FA enabled for both Google and Snipe-IT on our instance. The Snipe-IT 2FA gets ignored after an initial login/logout, the next "login" doesn't perform the 2FA like I would expect it to on the Snipe-IT side.

**Comment by rafiron** [comment]
Anybody else facing this problem ?

**Comment by rafiron** [comment]
Thanks @johnson-yi for the quick turnaround
