### ISSUE TITLE
CSV Template Files Won't Download

### ISSUE THREAD

**Issue by mpermann** [grokability/snipe-it#10997]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to download csv samples from [this](https://snipe-it.readme.io/docs/importing) page the templates will not display or download. It just redirects to the main  [webpage](https://www.snipeitapp.com). Are the csv template files available anywhere else that I can download copies of them?

### Reproduction steps

1. Go to https://snipe-it.readme.io/docs/importing and try and click on one of the sample csv files to download it and the page will redirect to the main webpage. 
2.
3.
...

### Expected behavior

Template csv file downloads.

### Snipe-IT Version

5.4.3

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

### Browser

Safari, Chrome, Firefox

### Version

Latest versions

**Comment by snipe** [comment]
Thanks for the heads up - you should have them locally in your snipe-it codebase in the `sample_cvs` directory

**Comment by jerm** [comment]
This has been corrected. Thanks again for the heads up!

**Comment by mpermann** [comment]
The [sample components](https://snipeitapp.com/assets/downloads/sample-components.csv) csv file 404 errors when trying to download it. All the other ones works fine. You might want to verify that one is working as well.

**Comment by jerm** [comment]
> The [sample components](https://snipeitapp.com/assets/downloads/sample-components.csv) csv file 404 errors when trying to download it. All the other ones works fine. You might want to verify that one is working as well.

Ooh thanks!. Different issue. Fixed!
