### ISSUE TITLE
remove composer.lock from repository

### ISSUE THREAD

**Issue by ikcalB** [grokability/snipe-it#11006]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

While installing from git repo, as per https://snipe-it.readme.io/docs/installation :

When installing dependencies using composer, it complains about:
`Your lock file does not contain a compatible set of packages. Please run composer update.` 

seems like composer.lock should be removed from the repo

### Reproduction steps

1. follow https://snipe-it.readme.io/docs/installation until installing dependencies
2. run `php composer.phar install --no-dev --prefer-source`

### Expected behavior

don't fail on install - there should be no .lock file in the repo

### Snipe-IT Version

git-master

### Operating System

CentOS7

### Web Server

apache

### PHP Version

7.4

**Comment by Exordian** [comment]
deletion of the lock file might lead to different dependencies when running "composer install" on different nodes with the same git revision. hence, it shouldn't be removed.

**Comment by snipe** [comment]
Agreed - we generate the composer.lock and commit it to make sure we're pinning you to the specific versions we have tested. Removing that and running `composer update` on your own is risky business.

**Comment by ikcalB** [comment]
@snipe that sounds reasonable.
