### ISSUE TITLE
Snipeit tries to access DB with wrong user

### ISSUE THREAD

**Issue by taeys** [grokability/snipe-it#11009]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I changed the IP address of my server from e.g. 192.168.52.4 to 192.168.52.5. It is still the same subnet. After that I got to the preflight page getting the follwing error: 

  | D'oh! Looks like we can't connect to your database. Please update your database settings in your  .env file. Your database says: SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'10.20.111.178' (using password: YES) (SQL: select 2 + 2)
-- | --

The problem is, that is not even the user I named in the .env file. That user is called snipeituser.
The Database is also set up with that user and remote connecting to the database with that user from the snipeit server also works. 

I don't quite get what this error could mean.

### Reproduction steps

1. change ip from server
2. access the URL
3.
...

### Expected behavior

Snipeit connects with the right user to the database as it previously did.

### Screenshots

![Auswahl_178](https://user-images.githubusercontent.com/100196129/166636397-67040e28-1a62-4683-8eac-ee9e183e3445.png)

### Snipe-IT Version

5.4.1

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

**Comment by lucasff** [comment]
clean your caches.
