### ISSUE TITLE
Custom field values containing " or another special character are not set as default in asset

### ISSUE THREAD

**Issue by opus-nbonenberger** [grokability/snipe-it#11014]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When creating a custom field with style 'checkbox' and the values contain special characters (" in my case), if i define one of these values as default in an asset model, it will not be selected as default when creating a new asset.

### Reproduction steps

1.  create custom field DROPDOWN style and add values with " or another special character
2. create an asset model, check default values and check the created vaule
3. create an asset from that asset model and see if the default value is checked
...

### Expected behavior

The default value should be set, regardless of charachters

### Snipe-IT Version

v5.4.4 - build 6829 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

macOS

### Browser

Chrome

### Version

101.0.4951.41

**Comment by snipe** [comment]
I have a PR against develop on this - just awaiting testing and approval.

**Comment by opus-nbonenberger** [comment]
Thanks @snipe
