### ISSUE TITLE
SQL Help - I'm not smart enough

### ISSUE THREAD

**Issue by darmarsh** [grokability/snipe-it#11010]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

My query:
`SELECT u.id, `u`.`last_name` AS `last_name`
,`u`.`first_name` AS `first_name`
,`a`.`asset_tag` AS `asset_tag`
FROM (`assets` `a` 
join `users` `u` on(`a`.`assigned_to` = `u`.`id`)) 
ORDER BY u.id`

a subset of the results shows a user with ID 71 as having asset IDs 2001164 and 2002009. However this user does not have the assetTag reported in this subset but rather location (with locationId of 71) has this assetId checked out to it.

![Capture](https://user-images.githubusercontent.com/104910209/166691755-02145cb2-3929-4415-a82d-a060b5f2ed98.PNG)

would someone with more SQL skill than I, help me adjust the sql above to only include a match of user IDs with assets and exclude any location IDs?

I'm using [this tool](https://drawsql.app/templates/snipe-it) to discover Snipe-IT table relationships

Thank you in advance.
Darin

### Reproduction steps

1.When I run specified query I get users and locations where those IDs match on the table join specified in query.

### Expected behavior

I only want users to be returned by the query not locatoins

### Snipe-IT Version

v4.9.2 build 4352 (gec723a3da)

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

7.3.18

**Comment by uberbrady** [comment]
I think you want something like:

Instead of: `on(a.assigned_to=u.id))`

More like: `on(a.assigned_to = u.id AND a.assigned_type='App\\Models\\User')`
