### ISSUE TITLE
[Feature Request]: Hour granularity on checkout

### ISSUE THREAD

**Issue by bdowney4** [grokability/snipe-it#11028]
### Is your feature request related to a problem? Please describe.

We recently began using Snipe IT at our university are thrilled thus far! However there is one missing feature that still requires us to use an alternative solution for equipment rental and that is the lack of hourly checkouts. For example, say there is a class at 9:00am using a projector cart, and they return it at 11:30am when the class over. Then at 1pm, a new user reserves the unit for their class, and returns it at 4pm. With the current version of Snipe IT, checkouts are only doable on a day by day basis.

### Describe the solution you'd like

The ability to checkout equipment on a half-hourly basis. Thank you for your time and consideration.

### Additional context

<img width="1314" alt="Screen Shot 2022-05-06 at 11 21 54 AM" src="https://user-images.githubusercontent.com/47223376/167163089-4e703a4c-7190-4a05-b9b3-21f5ad1f7f25.png">

**Comment by snipe** [comment]
If you clear the prepopulated date from the checkout date field, it will use the current date and time.

https://demo.snipeitapp.com/hardware/3#history

<img width="1562" alt="Screen Shot 2022-05-06 at 8 27 49 AM" src="https://user-images.githubusercontent.com/197404/167164068-6c962604-3724-4b52-9827-007bfe115378.png">



<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/3#history">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by bdowney4** [comment]
Perhaps I didn't describe it well enough. Essentially what this thread is about: https://github.com/snipe/snipe-it/issues/5081#issuecomment-1081033383

**Comment by snipe** [comment]
If that's what you're asking for, what makes this request different than that one?

**Comment by bdowney4** [comment]
It's not different, sorry for the redundancy. My colleague sent it to me. I'll close this accordingly. Thanks for the swift response.

**Comment by snipe** [comment]
You can always subscribe to that issue so you'll get notified of any updates that happen :)
