### ISSUE TITLE
[Feature Request]: Add bulk edit button for categories (and other views where multi selection is active)

### ISSUE THREAD

**Issue by Prodeguerriero** [grokability/snipe-it#11026]
### Is your feature request related to a problem? Please describe.

Sometimes I need to tidy up the database, due to poor import or changes in the way we handle things.

Bulk editing assets comes in handy, but the option is not always available to me. For example, if I navigate to a category, and want to bulk edit some or all items, I have the option to select multiple assets with the checkboxes, but the "Bulk edit" button at the top is not available, unlike when looking at the `/hardware` view.

This also happens when looking at locations, and I am pretty sure it happens somewhere else as well.

### Describe the solution you'd like

Everywhere the multi select feature is available, bulk options should also be available. 

### Describe alternatives you've considered

A more powerful way of filtering assets in `/hardware` would also do the trick, but adding the "bulk edit" button everywhere seems an easier solution.

### Additional context

An example of where the button could go, if looking at assets checked out to a location:

<img width="313" alt="Screen Shot 2022-05-06 at 11 46 36" src="https://user-images.githubusercontent.com/15149858/167108769-a06d3e74-bf99-42eb-81fa-55a07ede429f.png">

Thanks!

**Comment by snipe** [comment]
That's a great suggestion. It's been on my list, but there were some UI challenges I needed to think through. I have a PR waiting for review for this feature now. https://github.com/snipe/snipe-it/pull/11027

**Comment by snipe** [comment]
This is now on the develop branch and will be in the v6 release.

**Comment by Tritton74** [comment]
> This is now on the develop branch and will be in the v6 release.

Hello, I'm on v6.0.10 and Bulk edit isn't available.
Are you late? When will it be available?

Thx

**Comment by snipe** [comment]
@Tritton74 It’s definitely there - you can see for yourself on the demo. Perhaps you’re looking for a different bulk edit or an edit on a different page, but you should probably open a new issue for that, since this one is resolved.
