### ISSUE TITLE
favicon and touchicon are force loaded over http

### ISSUE THREAD

**Issue by opus-nbonenberger** [grokability/snipe-it#11021]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I use SSL with Snipe-IT and I have set a custom favicon for it. When loading the page, I can't see the favicon. A closer look in the source (Dev Tools in Google Chrome) reveals that these icons are loaded with http:// instead of https://.

### Reproduction steps

1. Set custom favicon
2. Access site over https
3. favicon is not displayed (in Chrome) due to mixed content because it's loaded with http://

### Expected behavior

Favicon should be loaded corrseponding to the type of request (http:// or https://)

### Snipe-IT Version

v5.4.4 - build 6829 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

macOS

### Browser

Chrome

### Version

101.0.4951.41

**Comment by snipe** [comment]
It's not tho - in the rendered HTML, you will see:

```html
      <link rel="apple-touch-icon" href="/img/logo.png">
      <link rel="apple-touch-startup-image" href="/img/logo.png">
      <link rel="shortcut icon" type="image/ico" href="/favicon.ico ">
```

which takes on whatever protocol your site uses.

**Comment by opus-nbonenberger** [comment]
Not here, i have absolute URLs in the source, including http://

**Comment by snipe** [comment]
What do you have as your APP_URL in your .env?

**Comment by opus-nbonenberger** [comment]
I am terribly sorry, there was http:// set. I have changed it to https://. Without protocol it did not work. Maybe you can adjust this setting to not use this protocol if specified but instead use the actually used protocol when accessing the site.

**Comment by snipe** [comment]
It's [documented](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings) that the protocol is required in the APP_URL. 

<img width="815" alt="Screen Shot 2022-05-06 at 12 49 19 AM" src="https://user-images.githubusercontent.com/197404/167090157-a2715c29-69ca-4594-b235-fc1197660546.png">


It's not possible to change that behavior, since some people run behind proxy servers and that can cause different problems.
