### ISSUE TITLE
SMTP and Mailgun

### ISSUE THREAD

**Issue by nedram1** [grokability/snipe-it#11029]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I did a quick search of recent issues about this, but didn't see anything. So apologies if this post ends up redundant. 

I'm trying to setup SMTP using my Mailgun account.

Below is my Outbound email config with un/pw and email domain removed. 

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=myusername
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=assets@mydomain.com
MAIL_FROM_NAME=Assets
MAIL_REPLYTO_ADDR=assets@mydomain.com
MAIL_REPLYTO_NAME=Assets
MAIL_AUTO_EMBED_METHOD='attachment'

I have DNS and whatnot already setup with Mailgun and have other devices sending out emails with no issues.

When I try to send a test email I get the error "Mail could not be sent No additional error message provided. Check your mail settings and app log"

I checked app/storage/logs/larcel.txt and don't have any entries related to SMTP. 

### Reproduction steps

1.Log into SnipeIT
2.Settings
3.General Settings
4.Click Send Test Mail
...

### Expected behavior

Mail to be sent. :)

### Screenshots

![image](https://user-images.githubusercontent.com/105072571/167181732-98c01cf2-e04f-4a4c-89aa-8957fdac71be.png)

### Snipe-IT Version

v5.1.5 build 6055

### Operating System

Windows Server 2012 R2

### Web Server

IIS

### PHP Version

7.4.13 

### Operating System

Windows

### Browser

Firefox

### Version

100

**Comment by snipe** [comment]
IIRC - if you're using mailgun, [you have to do things differently](https://laravel.com/docs/6.x/mail#driver-prerequisites)...

Add the following to your .env, and change the `MAIL_DRIVER` from `smtp` to `mailgun`
```
MAILGUN_DOMAIN='yourdomain'
MAILGUN_SECRET='yoursecret'
```

**Comment by nedram1** [comment]
Thanks. That info helped me solve my issue!

**Comment by snipe** [comment]
Great! (We should really document that better in our own docs but it doesn’t come up much.)

**Comment by jakenology** [comment]
I also had this issue, it would be beneficial to add it to the docs I think. I also had SSL instead of TLS so I changed that quick, but after creating an API key (the secret), and adding those two lines to my file, it worked! Thank you guys!!! Also running on PHP 8 on Ubuntu in AWS.
