### ISSUE TITLE
Snipe-it in cPanel

### ISSUE THREAD

**Issue by Chamira-Lakmal** [grokability/snipe-it#11030]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,

I have install snipe IT app cPanel shared host. Could you tell me how can I fix this below issue or error message?

D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

### Reproduction steps

nothing to say

### Expected behavior

can't access

### Snipe-IT Version

v5.4.4

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4

### Browser

Google

### Error messages

```shell
D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.
```

**Comment by Chamira-Lakmal** [comment]
my issue was this. 
I have install snipe IT app cPanel shared host. Could you tell me how can I fix this below issue or error message?

D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

I think It's not a bug

**Comment by snipe** [comment]
It's a configuration issue. You should be able to set your DocumentRoot in cPanel. 
https://support.cpanel.net/hc/en-us/articles/360051373774-How-to-change-the-document-root-for-a-cPanel-account

<blockquote><div><strong><a href="https://support.cpanel.net/hc/en-us/articles/360051373774-How-to-change-the-document-root-for-a-cPanel-account">Security check</a></strong></div></blockquote>

**Comment by Chamira-Lakmal** [comment]
Oh! Thanks. let me check

**Comment by Chamira-Lakmal** [comment]
Another Error!
Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by Chamira-Lakmal** [comment]
I'm trying to change using "vim"

But problem is below
-- INSERT -- W10: Warning: Changing a readonly file

How to Edit read-only file

**Comment by snipe** [comment]
Unfortunately, you'd have to ask your hosting provider. I don't have any way to know how they have things set up on their servers. :(

**Comment by kalpeshboghara** [comment]
Any document for install/upgrade into Cpanel?
