### ISSUE TITLE
404 Error on CSV Import

### ISSUE THREAD

**Issue by IanSimon82** [grokability/snipe-it#11043]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I import a CSV file I get a 404 Sad Panda Error. 

It was working fine until I made a few changes in the back end: 
Changed APPURL from my ip address 172.26.1.51 to http://172.26.1.51 (I switched this back and forth to try to fix the issue later)
Deleted all of my previous CSV files in the importer, I had had a lot in there. 
Updated SnipeIT to 5.4.4
Updated PHP to 7.4 (I did this later to try to get things to work again) 

### Reproduction steps

1. Go to Import
2. Upload a CSV
3. Click Process
4. Click Import
5. View the 404 error
...

### Expected behavior

The assets would be imported and I would be redirected to a page with a summary of the import. 

### Snipe-IT Version

5.4.4 (occurs on the last 3 releases as well)

### Operating System

Windows Server 2016

### Web Server

IIS

### PHP Version

7.4

### Operating System

Windows 21H2

### Browser

Chrome

### Version

101

### Error messages

```shell
Throw NotFoundHTTPEXception

Not repro'd in demo

No error in larvel.log

No error in web server logs 

php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
imap
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
pdo_sqlsrv
Phar
readline
Reflection
session
SimpleXML
SPL
sqlsrv
standard
tidy
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

### Additional context

Upgrade
Windows 2016 IIS
Manual
No errors with installation  - has worked for 6 months with no issues
I have manually edited data in the database. I tried to see if I could fix this by deleting the imports from the DB directly then reuploading and still got the same error.

**Comment by snipe** [comment]
I'm not able to reproduce this issue.
