### ISSUE TITLE
Server 500 error when downloading files after upgrade to 5.4.3

### ISSUE THREAD

**Issue by mdugdale** [grokability/snipe-it#11044]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgrading to Snipe-it version 5.4.3, I get a 500 server error when trying to download a previously uploaded file, or when trying to edit an existing asset and saving. I downgraded back to version 5.4.1, and downloads work and assets can be edited.

### Reproduction steps

1. Go to Licenses
2. Find a license that has a file uploaded
3. Go to "File uploads" tab and click the download button on a file
4. A 500 server error appears

### Expected behavior

1. Go to Licenses
2. Find a license that has a file uploaded
3. Go to "File uploads" tab and click the download button on a file
4. The file downloads

### Screenshots

![167465089-a296e05f-27ec-4fa2-845a-d66ab71a49b8](https://user-images.githubusercontent.com/6598874/167663324-451b3618-eab7-4bff-a09c-dacb4dd00fb8.JPG)

### Snipe-IT Version

5.4.3

### Operating System

Ubuntu 16.04

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Mac OS

### Browser

Safari

### Version

15.4

### Error messages

```shell
500 | Server Error
```

### Additional context

Upgrade from 5.4.1 to 5.4.3. Running Snipe-it in docker on Ubuntu 16.04

**Comment by snipe** [comment]
We’d need to know what’s in your app logs in order to help, per the [Getting Help documentation](https://snipe-it.readme.io/docs/getting-help).

**Comment by mdugdale** [comment]
I didn't see any relevant logs so I upgraded back to 5.4.3, and then 5.4.4 to try to get some, and it was somehow working without the 500 error. sorry for false alarm, closing

**Comment by snipe** [comment]
Thanks for the update! Glad you're sorted :)
