### ISSUE TITLE
Snipeit automatically revokes Bulk Move of Users

### ISSUE THREAD

**Issue by taeys** [grokability/snipe-it#11042]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have synced my Users with our LDAP. After that I began adding several Locations. I quickly realized, that Users needed their own Location, so besides offices, I added the Location "Users".
Then I proceeed to people, checked all users, chose Bulk Edit and changed the Location of all users to "Users". After a while though, I noticed that all users where once again in the first office Location I created. I proceeded to repeat the bulk edit, but the result was the same. Even though at first all users were correctly displayed in the Users location, after a while they were not anymore.

### Reproduction steps

1. Bulk move users to one Location
2. Snipeit will move them back
3.
...

### Expected behavior

All users stay in the "Users" Location

### Snipe-IT Version

5.4.1

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

**Comment by snipe** [comment]
This sounds like the LDAP sync is what's resetting the locations. We have nothing that runs in the background that would change that data otherwise.

**Comment by uberbrady** [comment]
Agreed, that's what I would figure too. If you go into your 'locations' section, and then go to edit the location that everyone is getting moved to, do you have an OU configured in there? If you do, any user in that OU will get moved to that location on the next sync. Your best bet will, instead, be to remove that OU from that location, and instead set the Base DN in your LDAP settings to your base. Then, when you sync, they'll all be set to no location, which you can then update. The users should not get moved after a subsequent sync.

**Comment by taeys** [comment]
I don't do the LDAP Sync after I moved everyone. I added LDAP, synced my users, created Locations, saw that everyone sat in one office (the first one I created), and created a Location called User. Then I bulk moved everyone there and after 5 minutes everyone is back in the office. And I don't have an OU configured in the Location.

**Comment by snipe** [comment]
Hi there - Pretty sure this has been working for a long time now, sorry for not closing this sooner. I'm going to close this. Please feel free to open a new issue if you're still having trouble.
