### ISSUE TITLE
Error 500 when checking out an asset or adding custom logos

### ISSUE THREAD

**Issue by NZRobC** [grokability/snipe-it#11049]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

when trying to check out an asset the below sql error is produced. Note this is a new server and backup had been restored from the old server which was running an older version of Snipeit
A similar issue is produced when trying to add logos

"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'action_date' in 'field list' (SQL: insert into `action_logs` (`item_type`, `item_id`, `user_id`, `target_type`, `target_id`, `location_id`, `note`, `action_date`, `action_type`, `company_id`, `updated_at`, `created_at`) values (App\Models\Asset, 6, 1, App\Models\User, 8, ?, , 2022-05-11 11:11:01, checkout, 12, 2022-05-11 11:11:01, 2022-05-11 11:11:01))

### Reproduction steps

1.Click on Assets
2.Chose assets and checkout
3.Select user and click checkout
...

### Expected behavior

expected behavior is for asset to be checked out

### Snipe-IT Version

5.4.4

### Operating System

Alamalinux 8.5

### Web Server

Apache

### PHP Version

7.4.29

### Operating System

Windows

### Browser

Firefox

### Version

99.0.1

### Error messages

```shell
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'action_date' in 'field list' (SQL: insert into `action_logs` (`item_type`, `item_id`, `user_id`, `target_type`, `target_id`, `location_id`, `note`, `action_date`, `action_type`, `company_id`, `updated_at`, `created_at`) values (App\Models\Asset, 6, 1, App\Models\User, 8, ?, , 2022-05-11 11:11:01, checkout, 12, 2022-05-11 11:11:01, 2022-05-11 11:11:01))

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

fresh install and backup restored from old server
running on AlamaLinux 8.5
installed from Git
[laravel.log](https://github.com/snipe/snipe-it/files/8665521/laravel.log)

**Comment by snipe** [comment]
Whenever you see a "Column not found" error, that means that either database migrations were not run on an upgrade, or they failed somewhere along the way. Please[ try running migrations manually](https://snipe-it.readme.io/docs/common-issues#column-not-found) and post the output.

**Comment by NZRobC** [comment]
Thanks this has resolved the issue.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
