### ISSUE TITLE
Snipe-IT was working and looked correct, now it shows just the site content and not the GUI anymore.

### ISSUE THREAD

**Issue by escheffler2022** [grokability/snipe-it#11045]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Snipe-IT was working and looked correct, now it shows just the site content and not the GUI anymore.  It lists out the contents of each page instead of the nice dashboards, etc.

### Reproduction steps

1.Click on link, does not have the usual Snipe-IT login box.
2.
3.
...

### Expected behavior

Clicking on the link should bring up the usual Snipe-IT login window.  Once I login, it just shows all the content instead of the dashboards.

### Screenshots

![image](https://user-images.githubusercontent.com/103442947/167681832-1b10cae2-632c-4c60-abee-65a266b90cc0.png)
![image](https://user-images.githubusercontent.com/103442947/167682978-ec300bcd-7e77-4f21-9aec-60a13e976c9a.png)

### Snipe-IT Version

5.4.2

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.11

**Comment by snipe** [comment]
My guess would be that your CSS and JS paths are not correct. What's your APP_URL in your .env?

**Comment by escheffler2022** [comment]
APP_URL=https://10.10.2.8/login?nosaml
I added the no SAML since Azure login keeps trying to come up and we don't even have it setup in Azure for SSO.

**Comment by snipe** [comment]
That would not work though - it should be just the base url. It definitely has some sort of SAML configured, it it wouldn’t know to look for an Azure SSO (versus some other SSO provider). You should recheck your SAML settings.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by escheffler2022** [comment]
APP_URL=https://10.10.2.8/login?nosaml

(Azure AD is trying to do SSO and we don’t want to use it right now, that is why I have the nosaml)  I don’t know why the Azure SSO is coming up when it is not even setup for it currently.
Thanks!

Erin T. Scheffler

MAP Health Management®, LLC
Main: 855-627-1010
1114 Lost Creek Blvd. | Suite 270 | Austin, TX 78746
This message may be protected under the Federal regulations governing Confidentiality of Alcohol and Drug Abuse Patient Records, 42 C.F.R. Part 2, and the Health Insurance Portability and Accountability Act of 1996 ("HIPAA"), 45 C.F.R. Pts. 160 & 164 and cannot be disclosed without written consent unless otherwise provided for in the regulations. The Federal rules prohibit any further disclosure of this information unless a written consent is obtained from the person to whom it pertains. The Federal rules restrict any use of this information to criminally investigate or prosecute any alcohol or drug abuse patient. If you are not the intended recipient, please contact the sender by reply e-mail or the phone numbers provided and destroy all copies of the original message.
