### ISSUE TITLE
[Feature Request]: Display or give option to add the column to display the filesize of files attached to an object

### ISSUE THREAD

**Issue by derdeagle** [grokability/snipe-it#11052]
### Is your feature request related to a problem? Please describe.

I'd like to be able to see the filesize of files attached to an object like asset, license etc.
This is nothing important but just informative.

Also a summary line would be great to see that all attached files to this object are x MB of size.

### Solution 1

Automatically display (defined as standard) a colum in the files tab of an object which shows the human-readable filesize.

### Solution 2

Add the possibility to add the column which shows the filesize of an attached file.

**Comment by snipe** [comment]
Please don't assign tasks to me.

**Comment by derdeagle** [comment]
@snipe That was not my intention, sorry for that, and to be honest I was quite surprised when I noticed that you were automatically assigned. I thought it was part of the process.

Thanks for handling the FR so fast!
