### ISSUE TITLE
6.0.0 generated backup time stamp show wrong time -2 hours

### ISSUE THREAD

**Issue by SilentDon** [grokability/snipe-it#11069]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When i generate an backup zip, that is show wrong timestamp, anyway 2M not enough for me to upload how can I change that?

### Reproduction steps

1.
2.
3.
...

### Expected behavior

show correct time stamp

### Snipe-IT Version

6.0 

### Operating System

linux

### Web Server

apache2

### PHP Version

7.4

**Comment by snipe** [comment]
You'd need to check your server time. We don't do anything to timestamps. Also if you need more than 2MB, you'll need to check your PHP settings. https://www.drupal.org/docs/7/managing-site-performance-and-scalability/increase-upload-size-in-your-phpini

<blockquote><div>Drupal.org</div><div><strong><a href="https://www.drupal.org/docs/7/managing-site-performance-and-scalability/increase-upload-size-in-your-phpini">Increase upload size in your php.ini</a></strong></div><div>Note 1: The file php.ini is not part of Drupal. It is a part of the PHP configuration. To locate it, look up your PHP configuration. If you're on shared hosting, you may not have access to it. Note 2: Increasing PHP upload size is different from increasing PHP memory limit. You can learn how to increase memory limit here. Drupal's limits on upload file size are determined by your server's PHP settings (as well as Drupal 6's specified settings that can be set at Admin > Site Configuration > File Upload). The default values for PHP will restrict you to a maximum 2 MB upload file size.</div></blockquote>

**Comment by SilentDon** [comment]
sorry but i checked, really show wrong time only the backup generated file timestamp show 12 AM

Köszönettel:

Szalay Zoltán
IT operation
[innodox-email]
INNODOX Technologies Zrt.
1123 Budapest, Nagyenyed utca 8-14.
telefon: +36 1 870 0223 | fax: +36 1 870 0225
mobil: +36 30 898 6547
email: ***@***.******@***.***>
INNODOX.COM<http://innodox.com/>

Az Innodox a Printsoft-Hungary új, nemzetközi  márkaneve. | Innodox is the new, international brand of Printsoft-Hungary.
