### ISSUE TITLE
6.0.0 attempted login cant show more the logged in events

### ISSUE THREAD

**Issue by SilentDon** [grokability/snipe-it#11068]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

after update to 6.0.0 from 5.4.4   6.0.0 attemted login cant show more the logged in events

### Reproduction steps

1.
2.
3.
...

### Expected behavior

show logged in users

### Snipe-IT Version

6.0 

### Operating System

linux

### Web Server

apache2

### PHP Version

7.4

**Comment by snipe** [comment]
I don't know what this means. Can you provide screenshots or any additional information please?

**Comment by SilentDon** [comment]
***@***.***

Köszönettel:

Szalay Zoltán
IT operation
[innodox-email]
INNODOX Technologies Zrt.
1123 Budapest, Nagyenyed utca 8-14.
telefon: +36 1 870 0223 | fax: +36 1 870 0225
mobil: +36 30 898 6547
email: ***@***.******@***.***>
INNODOX.COM<http://innodox.com/>

Az Innodox a Printsoft-Hungary új, nemzetközi  márkaneve. | Innodox is the new, international brand of Printsoft-Hungary.

**Comment by snipe** [comment]
?

**Comment by snipe** [comment]
If there was supposed to be an attachment, Github doesn't support emailed attachments - you'll have to use the web UI on Github for that

**Comment by SilentDon** [comment]
that is what i see after update, before that it was full of row

Köszönettel:

Szalay Zoltán
IT operation
[innodox-email]
INNODOX Technologies Zrt.
1123 Budapest, Nagyenyed utca 8-14.
telefon: +36 1 870 0223 | fax: +36 1 870 0225
mobil: +36 30 898 6547
email: ***@***.******@***.***>
INNODOX.COM<http://innodox.com/>

Az Innodox a Printsoft-Hungary új, nemzetközi  márkaneve. | Innodox is the new, international brand of Printsoft-Hungary.

**Comment by SilentDon** [comment]
[](url
![login](https://user-images.githubusercontent.com/105525375/168401818-0252e5eb-6d1b-4da5-bd6a-119c858a1822.jpg)
)

**Comment by snipe** [comment]
Thanks for the heads up - This is fixed on master

**Comment by SilentDon** [comment]
thx closeable then

Köszönettel:

Szalay Zoltán
IT operation
[innodox-email]
INNODOX Technologies Zrt.
1123 Budapest, Nagyenyed utca 8-14.
telefon: +36 1 870 0223 | fax: +36 1 870 0225
mobil: +36 30 898 6547
email: ***@***.******@***.***>
INNODOX.COM<http://innodox.com/>

Az Innodox a Printsoft-Hungary új, nemzetközi  márkaneve. | Innodox is the new, international brand of Printsoft-Hungary.

**Comment by SilentDon** [comment]
I uploaded

Köszönettel:

Szalay Zoltán
IT operation
[innodox-email]
INNODOX Technologies Zrt.
1123 Budapest, Nagyenyed utca 8-14.
telefon: +36 1 870 0223 | fax: +36 1 870 0225
mobil: +36 30 898 6547
email: ***@***.******@***.***>
INNODOX.COM<http://innodox.com/>

Az Innodox a Printsoft-Hungary új, nemzetközi  márkaneve. | Innodox is the new, international brand of Printsoft-Hungary.
