### ISSUE TITLE
Can't Update v6.0.0-RC-8

### ISSUE THREAD

**Issue by ShinChill** [grokability/snipe-it#11060]
### Is your feature request related to a problem? Please describe.

i am using Version v6.0.0-RC2 - build 6627 , but can't update to v6.0.0-RC-8

### Describe the solution you'd like

Skipping user check as it is not supported on Windows or Posix is not installed on this server.
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- check your PHP version and extension requirements
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (7.4.27) is at least 7.4.0 - continuing...
FYI: The php.ini used by this PHP is: /etc/php.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ sodium is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit_db...
Determining files to backup...
Zipping 196 files and directories...
Created zip containing 196 files and directories. Size is 7.62 MB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!

--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.

--------------------------------------------------------
STEP 4: Pulling latest from Git (develop branch):
--------------------------------------------------------

Git is installed.
Already on 'develop'
warning: CRLF will be replaced by LF in .github/ISSUE_TEMPLATE/feature_request.yml.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in app.json.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in heroku/startup.php.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in .github/ISSUE_TEMPLATE/feature_request.yml.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in app.json.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in heroku/startup.php.
The file will have its original line endings in your working directory.
error: Your local changes to the following files would be overwritten by merge:
        .github/ISSUE_TEMPLATE/feature_request.yml
Please, commit your changes or stash them before you can merge.
Aborting
-- Saved working directory and index state WIP on develop: 99541f0 Fixed string
HEAD is now at 99541f0 Fixed string
-- M    .github/ISSUE_TEMPLATE/feature_request.yml
M       app.json
M       heroku/startup.php
Your branch is behind 'origin/develop' by 476 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
-- Updating 99541f0..ef1eb15

--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ Deleting bootstrap/cache/services.php. It is no longer used.
√ No bootstrap/cache/config.php, so nothing to delete.

-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
83 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
Generated optimized autoload files containing 8043 classes

composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!
--------------------------------------------------------

**Comment by snipe** [comment]
So, we're seeing this intermittently in the Docker develop build too, but we haven't been able to reproduce it, and I don't have any explanation for that, since I'm sure you didn't change that `feature_request.yml` file, and Dockerhub certainly didn't, and the commits to that file are no different than any other commit. I am pretty baffled as to what's happening here and what's so special about that particular file that it always seems to be the one that's getting hitched up lately - not to mention that the upgrade script already *does* a git stash locally before it tries to do a git pull. If you do a `git stash` and then re-run the upgrade.php, does that make a difference?

**Comment by snipe** [comment]
We've just done the formal v6 release and docker builds are all passing now - can you give that a shot?
