### ISSUE TITLE
v6 - Upload backup button remains disabled

### ISSUE THREAD

**Issue by SilentDon** [grokability/snipe-it#11074]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When i click and choose zip file to upload the system dont do anything. If i generate backup.zip file the reated tim show 2hours less then the current time. everywhere is right the time showing, just in the backup section not!

### Reproduction steps

1.
2.
3.
...

### Expected behavior

uploading zip file

### Snipe-IT Version

6.0 

### Operating System

linux

### Web Server

apache2

### PHP Version

7.4.3

**Comment by snipe** [comment]
Can we get some additional information here? What's in your error logs?

**Comment by SilentDon** [comment]
Very intresting, because. the log file is contain nothing about this. I mean I deleted the log file and tried to select and upload an zip backup, but the webpage do nothing when i had choosen.. and the log file stayed empty

**Comment by snipe** [comment]
Enable debug mode and show me the stack trace

**Comment by SilentDon** [comment]
Köszönettel:

Szalay Zoltán
IT operation
[innodox-email]
INNODOX Technologies Zrt.
1123 Budapest, Nagyenyed utca 8-14.
telefon: +36 1 870 0223 | fax: +36 1 870 0225
mobil: +36 30 898 6547
email: ***@***.******@***.***>
INNODOX.COM<http://innodox.com/>

Az Innodox a Printsoft-Hungary új, nemzetközi  márkaneve. | Innodox is the new, international brand of Printsoft-Hungary.

**Comment by snipe** [comment]
If you're trying to attach a file, Github doesn't support that via email replies.

**Comment by SilentDon** [comment]
[](url
![Képernyőkép 2022-05-14 183251](https://user-images.githubusercontent.com/105525375/168440694-a5c449c3-a6da-465e-b796-57c212b4f0ee.png)
)

**Comment by snipe** [comment]
I need a stack trace, not a screenshot of the debugger.

**Comment by SilentDon** [comment]
sorry, im not sure what is that, or where can i find that?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by SilentDon** [comment]
that is in laravel.log

[2022-05-14 18:29:43] production.DEBUG: Trying to create a new OneLogin_Saml2_Auth object
[2022-05-14 18:29:43] production.ERROR: Trying OneLogin_Saml2_Auth failed. Setting SAML enabled to false. OneLogin_Saml2_Auth error message is: Invalid array settings: invalid_syntax
[2022-05-14 18:29:44] production.DEBUG: Trying to create a new OneLogin_Saml2_Auth object
[2022-05-14 18:29:44] production.ERROR: Trying OneLogin_Saml2_Auth failed. Setting SAML enabled to false. OneLogin_Saml2_Auth error message is: Invalid array settings: invalid_syntax
[2022-05-14 18:29:44] production.DEBUG: Attempting to login via SAML
[2022-05-14 18:29:44] production.WARNING: SAML page requested, but SAML does not seem to enabled.
[2022-05-14 18:29:44] production.WARNING: Something else went wrong while trying to login as SAML user
[2022-05-14 18:29:53] production.DEBUG: Trying to create a new OneLogin_Saml2_Auth object
[2022-05-14 18:29:53] production.ERROR: Trying OneLogin_Saml2_Auth failed. Setting SAML enabled to false. OneLogin_Saml2_Auth error message is: Invalid array settings: invalid_syntax
[2022-05-14 18:29:53] production.DEBUG: LDAP is enabled.
[2022-05-14 18:29:53] production.DEBUG: Attempting to log user in by LDAP authentication.
[2022-05-14 18:29:53] production.DEBUG: Binding user to LDAP.
[2022-05-14 18:29:53] production.DEBUG: Filter query: (&(cn=*)(uid=samaccountnameszalay_zoltan))
[2022-05-14 18:29:53] production.DEBUG: LDAP user szalay_zoltan not found in LDAP or could not bind
[2022-05-14 18:29:53] production.DEBUG: There was an error authenticating the LDAP user: Could not find user in LDAP directory
[2022-05-14 18:29:53] production.DEBUG: Authenticating user against database.

**Comment by SilentDon** [comment]
Thatis what i found


admin/backups
status_code
200
status_text
OK
format
html
content_type
text/html; charset=UTF-8
request_query
[]
request_request
[]
request_headers
array:9 [▼
  "host" => array:1 [▶]
  "connection" => array:1 [▶]
  "upgrade-insecure-requests" => array:1 [▶]
  "user-agent" => array:1 [▶]
  "accept" => array:1 [▶]
  "referer" => array:1 [▶]
  "accept-encoding" => array:1 [▶]
  "accept-language" => array:1 [▶]
  "cookie" => array:1 [▶]
]
request_server
array:34 [▼
  "REDIRECT_STATUS" => "200"
  "HTTP_HOST" => "192.168.1.31"
  "HTTP_CONNECTION" => "keep-alive"
  "HTTP_UPGRADE_INSECURE_REQUESTS" => "1"
  "HTTP_USER_AGENT" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36 Edg/101.0.1210.39"
  "HTTP_ACCEPT" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
  "HTTP_REFERER" => http://192.168.1.31/admin
  "HTTP_ACCEPT_ENCODING" => "gzip, deflate"
  "HTTP_ACCEPT_LANGUAGE" => "hu,en;q=0.9,en-GB;q=0.8,en-US;q=0.7"
  "HTTP_COOKIE" => "system-backups.bs.table.cardView=false; loginReport.bs.table.cardView=false; system-backups.bs.table.sortName=modified_display; system-backups.bs.table.sortOrder=desc; groupsTable.bs.table.cardView=false; dashActivityReport.bs.table.cardView=false; dashLocationSummary.bs.table.cardView=false; dashCategorySummary.bs.table.cardView=false; usersTable.bs.table.cardView=false; accessoriesTable.bs.table.cardView=false; consumablesTable.bs.table.cardView=false; componentsTable.bs.table.cardView=false; kitsTable.bs.table.cardView=false; licensesTable.bs.table.cardView=false; usersTable.bs.table.pageNumber=1; usersTable.bs.table.pageList=100; usersTable.bs.table.searchText=; assetsListingTable.bs.table.cardView=false; assetsListingTable.bs.table.sortName=asset_tag; assetsListingTable.bs.table.sortOrder=desc; assetsListingTable.bs.table.pageNumber=4; accessoriesTable.bs.table.columns=%5B%22image%22%2C%22name%22%2C%22category%22%2C%22model_number%22%2C%22location%22%2C%22qty%22%2C%22min_qty%22%2C%22remaining_qty%22%2C%22change%22%2C%22actions%22%5D; consumablesTable.bs.table.columns=%5B%22name%22%2C%22image%22%2C%22category%22%2C%22qty%22%2C%22remaining%22%2C%22min_amt%22%2C%22location%22%2C%22purchase_date%22%2C%22change%22%2C%22actions%22%5D; assetsListingTable.bs.table.columns=%5B%22name%22%2C%22image%22%2C%22asset_tag%22%2C%22serial%22%2C%22model%22%2C%22category%22%2C%22status_label%22%2C%22assigned_to%22%2C%22location%22%2C%22custom_fields._snipeit_hostname_3%22%2C%22custom_fields._snipeit_ssd_4%22%2C%22custom_fields._snipeit_memory_5%22%2C%22actions%22%5D; snipeit_session=BvaWumYNXafxnZUPP3sbGAbmXmEknA3F2kGS772t; laravel_token=eyJpdiI6IldEZ3hmN1BBSUx4NVFERURIU0NvS2c9PSIsInZhbHVlIjoiYkhQMDB5N0YrOEE5REd4TzUzUXJXeHQyZEtrOUNoK2I1OWRXNkZpYkZWd1Y3ejBybGdzNHBEcmY5LzZ1NkwyWjQzV2ZFZC9iQWZzNUlwMnJOMkVZejRrTzlCM0pzTGNtUzY1RE5iaktNaVNaWC9JKzZsdy9TTytRSlFIU0p6VUo3cUJsV291TGxUOU1uSGYrNCtDVm0wYUh5bUV1RjVQWTkwandVQ0lCOVhnUWdLZ2tjSzFPWVFyM0VVYjBLdHFyODlyVzdEZ2thYVIzcmNqK1QycEJCUUM4UlYreXgvdGFlanU1Qmt5ZVhXc25MSHA5WEpBRHpNQXErTUhZM2N6TWpJNlFZVTltQ1k4c1RFQm1SSVpvcEJ6Y0J1aEl0RzhUK2hPL1NtazFWRGs1QzV0UjJ0SDZwTyszZzhha1ZhN2oiLCJtYWMiOiJiY2VhMTZiOGY1NjRhZGU5OWVmNjI0MWVmMjIwNTFmNWI5MWNlMTZjMjJjYWI1YzMxNTNhZjZiMTc4NmMxMDljIiwidGFnIjoiIn0%3D; XSRF-TOKEN=eyJpdiI6IldaKzZXdkJiVzlxb0ZaaHlPcjJNMnc9PSIsInZhbHVlIjoiREdWaVNRQVIzb3VkMEdpV1EyS2FNa3JhaEltNXdiSTZJWUhwZlZNeThPZGZUWDVnSDZTMlliaWR2NS90SDdCU25NWU9sOWNOTUJBQjJITVVQUEdOU1c3Mko4WG43bzFoTUtTR083aHJjZFZGK3YyVlo1NUIxNmhVbWd2cVVuVHEiLCJtYWMiOiIzZmY2ZTc3NDJhMTA3NDE0ODc0NWY0NGU1MWExNTk3MTIxZTBjZGEzOWRlNzU1NTc2Y2UyNTcxMjhhMmJkYjM4IiwidGFnIjoiIn0%3D ◀system-backups.bs.table.cardView=false; loginReport.bs.table.cardView=false; system-backups.bs.table.sortName=modified_display; system-backups.bs.table.sortOrde ▶"
  "PATH" => "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
  "SERVER_SIGNATURE" => "<address>Apache/2.4.41 (Ubuntu) Server at 192.168.1.31 Port 80</address>\n"
  "SERVER_SOFTWARE" => "Apache/2.4.41 (Ubuntu)"
  "SERVER_NAME" => "192.168.1.31"
  "SERVER_ADDR" => "192.168.1.31"
  "SERVER_PORT" => "80"
  "REMOTE_ADDR" => "192.168.1.16"
  "DOCUMENT_ROOT" => "/var/www/snipe-it/public"
  "REQUEST_SCHEME" => "http"
  "CONTEXT_PREFIX" => ""
  "CONTEXT_DOCUMENT_ROOT" => "/var/www/snipe-it/public"
  "SERVER_ADMIN" => "[no address given]"
  "SCRIPT_FILENAME" => "/var/www/snipe-it/public/index.php"
  "REMOTE_PORT" => "59548"
  "REDIRECT_URL" => "/admin/backups"
  "GATEWAY_INTERFACE" => "CGI/1.1"
  "SERVER_PROTOCOL" => "HTTP/1.1"
  "REQUEST_METHOD" => "GET"
  "QUERY_STRING" => ""
  "REQUEST_URI" => "/admin/backups"
  "SCRIPT_NAME" => "/index.php"
  "PHP_SELF" => "/index.php"
  "REQUEST_TIME_FLOAT" => 1652546883.079
  "REQUEST_TIME" => 1652546883
]
request_cookies
array:27 [▼
  "system-backups_bs_table_cardView" => null
  "loginReport_bs_table_cardView" => null
  "system-backups_bs_table_sortName" => null
  "system-backups_bs_table_sortOrder" => null
  "groupsTable_bs_table_cardView" => null
  "dashActivityReport_bs_table_cardView" => null
  "dashLocationSummary_bs_table_cardView" => null
  "dashCategorySummary_bs_table_cardView" => null
  "usersTable_bs_table_cardView" => null
  "accessoriesTable_bs_table_cardView" => null
  "consumablesTable_bs_table_cardView" => null
  "componentsTable_bs_table_cardView" => null
  "kitsTable_bs_table_cardView" => null
  "licensesTable_bs_table_cardView" => null
  "usersTable_bs_table_pageNumber" => null
  "usersTable_bs_table_pageList" => null
  "usersTable_bs_table_searchText" => null
  "assetsListingTable_bs_table_cardView" => null
  "assetsListingTable_bs_table_sortName" => null
  "assetsListingTable_bs_table_sortOrder" => null
  "assetsListingTable_bs_table_pageNumber" => null
  "accessoriesTable_bs_table_columns" => null
  "consumablesTable_bs_table_columns" => null
  "assetsListingTable_bs_table_columns" => null
  "snipeit_session" => null
  "laravel_token" => "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE1LCJjc3JmIjoiT2RnRW1kdEQwWkdyamxuQ2R0MzZCWGlZeGhVdDZvZkJSQ1lPV0J0OCIsImV4cGlyeSI6MTY1MzI2Njg3OX0.06YZkf2tI5jlsbLrllxDk8iODMvHyLvI6XTSN7EJB_4 ◀eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE1LCJjc3JmIjoiT2RnRW1kdEQwWkdyamxuQ2R0MzZCWGlZeGhVdDZvZkJSQ1lPV0J0OCIsImV4cGlyeSI6MTY1MzI2Njg3OX0.06YZkf2tI5jlsbL ▶"
  "XSRF-TOKEN" => "OdgEmdtD0ZGrjlnCdt36BXiYxhUt6ofBRCYOWBt8"
]
response_headers
array:8 [▼
  "content-type" => array:1 [▶]
  "cache-control" => array:1 [▶]
 "date" => array:1 [▶]
  "x-clockwork-id" => array:1 [▶]
  "x-clockwork-version" => array:1 [▶]
  "x-clockwork-path" => array:1 [▶]
  "set-cookie" => array:2 [▶]
  "Set-Cookie" => array:2 [▶]
]
session_attributes
array:8 [▼
  "_token" => "OdgEmdtD0ZGrjlnCdt36BXiYxhUt6ofBRCYOWBt8"
  "url" => []
  "_previous" => array:1 [▶]
  "_flash" => array:2 [▶]
  "backUrl" => http://192.168.1.31/login
  "menu_state" => "closed"
  "login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d" => 15
  "PHPDEBUGBAR_STACK_DATA" => []
]


Köszönettel:

Szalay Zoltán
IT operation
[innodox-email]
INNODOX Technologies Zrt.
1123 Budapest, Nagyenyed utca 8-14.
telefon: +36 1 870 0223 | fax: +36 1 870 0225
mobil: +36 30 898 6547
email: ***@***.******@***.***>
INNODOX.COM<http://innodox.com/>

Az Innodox a Printsoft-Hungary új, nemzetközi  márkaneve. | Innodox is the new, international brand of Printsoft-Hungary.

**Comment by snipe** [comment]
This is a lot of noise around what could have been stated very clearly. "When I try to upload a file to restore from, the button is not clickable."

Please try to be precise with your bug reports. I've just wasted a lot of time trying to figure out what was going on.

We're looking into the submit button issue.

**Comment by SilentDon** [comment]
thank you, and please forgive me about this! I try to write more lightly!  So I have two problem!

The upload button doesnt work in upload buckup! Or I cant decide choosed zip file or not, because happen nothing…

problem 2.:  When I generate an backup zip file the time is wrong. show less 2 hours!


Thank you so much again….

**Comment by snipe** [comment]
We do not modify timestamps on files created. Check your server timezone.

**Comment by SilentDon** [comment]
Everywhere is ok the timestamp only in backup not correct, but no matters I can live with this, and we can manually restore the system also by phpmyadmin… Jud annyoing me the problem, because I cant solve….

**Comment by snipe** [comment]
Fixed in #11080

**Comment by snipe** [comment]
The backup uses the file system created time, not the database time. Again, check your server's time.
