### ISSUE TITLE
v6 backup restore button doesn't work

### ISSUE THREAD

**Issue by SilentDon** [grokability/snipe-it#11081]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I tried to restore, from backup page by yellow restore button, I get 500 internal error message

### Reproduction steps

1.
2.
3.
...

### Expected behavior

restore from zip

### Snipe-IT Version

v6

### Operating System

linux

### Web Server

apache2

### PHP Version

7.4.3

**Comment by snipe** [comment]
Please do not create duplicate issues.

**Comment by SilentDon** [comment]
Ok Sorry ! I wont!

Köszönettel:

Szalay Zoltán
IT operation
[innodox-email]
INNODOX Technologies Zrt.
1123 Budapest, Nagyenyed utca 8-14.
telefon: +36 1 870 0223 | fax: +36 1 870 0225
mobil: +36 30 898 6547
email: ***@***.******@***.***>
INNODOX.COM<http://innodox.com/>

Az Innodox a Printsoft-Hungary új, nemzetközi  márkaneve. | Innodox is the new, international brand of Printsoft-Hungary.
