### ISSUE TITLE
During asset creation default values for a model's custom field doesn't update when changing to a different model

### ISSUE THREAD

**Issue by rafiron** [grokability/snipe-it#11098]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

To properly group the assets I've created asset models as well. For each of these models, I've added some custom properties like RAM, Storage Size, etc. with their own defaults so that I don't need to manually change when creating the assets.

However, in the asset creation flow when changing the asset model from A->B, these defaults don't get modified as they should. Instead, the values being presented are the ones of Asset model A despite changing it to B. Only when I start the flow again for asset creation and then select model B in the first go itself, then only the correct default values are being populated. 

### Reproduction steps

1. Create 2 asset models A and B each with a custom field X having default values XA and XB.
2. Open the asset creation flow and choose Model A. It will showcase X's value as XA.
3. Click on the 'x' button to change the Model from A -> B. The value that is shown for X is still XA instead of XB.
...

### Expected behavior

Custom fields and their defaults should be updated once the model is changed.

### Snipe-IT Version

5.4.4

### Operating System

Hosted SnipeIT

### Web Server

-

### PHP Version

-

**Comment by snipe** [comment]
@rafiron v6 just dropped over the weekend. Do you want to be upgraded? If so, shoot us an email with your subdomain to support@snipeitapp.com. I know we changed some things between versions.

**Comment by rafiron** [comment]
Sure @snipe. I'll get my current setup upgraded and get back on whether it's happening for the newer version or not.

**Comment by rafiron** [comment]
@snipe the same issue is present in v6 as well.

**Comment by snipe** [comment]
Do you have special characters in your default values? Quote marks, etc?

**Comment by rafiron** [comment]
Apart from whitespace, I am not using any special characters. The values are being populated however on changing the models they stay the same and don't get updated. That's the issue. 
Only when I go back to the asset creation flow and select the new model, then the values are being shown correctly.
