### ISSUE TITLE
v6 - Backup created_at time is incorrect

### ISSUE THREAD

**Issue by tanjiunnyann** [grokability/snipe-it#11096]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I've using v5.4.4 has no issues with the following, but once upgrade to v6.0.0, then I've noticed the below:

1. I've configure TimeZone = 'Asia/Kuala_Lumpur' in .env file. The backup file name's appears correctly but in the Snipe-IT Backup display page showing the wrong Time Zone.
2. No matter how many times log in to the Snipe-IT, the Login Attemps always empty and not been recorded as shown in the picture.
![Bug-Backup](https://user-images.githubusercontent.com/100458087/168527336-bfc4b06a-2afc-4c53-8a64-2bcda03bab3e.png)
![Bug-LoginAttepts](https://user-images.githubusercontent.com/100458087/168527340-2b0b5825-cbc1-406c-abf9-3b10d0715ef5.png)

### Reproduction steps

Bug for Backup Time Zone
1. Configure .env file APP_TIMEZONE='Asia/Kuala_Lumpur'
2. Generate Backup in Backup page

Bug for Login Attempts
1. Login any user to Snipe-IT
2. Browse the "Login Attempts", it shows empty.

### Expected behavior

Backup Time Zone:

The "Created" date time in Backup page must follow what I've set in the .env file APP_TIMEZONE value.

Login Attempts:

Any user login must shows in this page.

### Snipe-IT Version

v6.0.0

### Operating System

Windows Server 2016

### Web Server

IIS

### PHP Version

7.4.29 VC15 x64 Non Thread Safe (2022-Apr-14 21:34:21)

### Operating System

Windows 10 Pro

### Browser

Chrome / Edge / Mozilla

### Version

101

**Comment by JoatWiPete** [comment]
Same issue by me.
The system time is correct.
The backup filename is named correctly.
The created date is incorrect. 
<details>
  <summary>Screenshots</summary>

```
pete@snipe-it:/var/www/snipe-it/storage/app/backups$ ls
env-backups            snipe-it-2022-05-16-09-20-08.zip  snipe-it-2022-05-16-09-20-44.zip  snipe-it-2022-05-16-09-33-29.zip
```
![image](https://user-images.githubusercontent.com/35880595/168605173-c064427d-25dd-4030-8727-da80783493c5.png)
```
pete@snipe-it:/var/www/snipe-it$ timedatectl
               Local time: Mon 2022-05-16 09:25:10 EDT
           Universal time: Mon 2022-05-16 13:25:10 UTC
                 RTC time: Mon 2022-05-16 13:25:10
                Time zone: America/New_York (EDT, -0400)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
```
APP_TIMEZONE='America/New_York'
```
![image](https://user-images.githubusercontent.com/35880595/168604046-57ba7659-f6e1-4a8d-9b2a-f216c1206f34.png)
</details>

**Comment by kcoyo** [comment]
+1 for Bug for Login Attempts. Upgraded to the latest v6.0.0, and the Login Attempts page is blank. The odd thing is it works on the Demo Pages (demo.snipeitapp.com and develop.snipeitapp.com).

**Comment by snipe** [comment]
@kcoyo that issue was already fixed - please pull from master.

**Comment by kcoyo** [comment]
Sweet, thanks for the fast reply @snipe!

**Comment by tanjiunnyann** [comment]
> @kcoyo that issue was already fixed - please pull from master.

May I know where to get the fixed login attempts?

**Comment by uberbrady** [comment]
It looks like the way the system works is it looks at the `APP_TIMEZONE` when it saves times to the database. So if you change that `.env` var, then any time that the system saves it tries to save relative to that timezone.

However, the backup system's "storage" is just a set of files that live in the filesystem. So the times for those files are *always* going to be relative to what the server's timezone is. If you want to make the timezones show up differently, you'd probably have to modify the server's timezone to match what you expect - then the timestamps on those files (at least going forward?) _should_ match.

**Comment by JoatWiPete** [comment]
@uberbrady As I showed in my comment above, both my APP_TIMEZONE and system time are set to the same timezone.

**Comment by tanjiunnyann** [comment]
> It looks like the way the system works is it looks at the `APP_TIMEZONE` when it saves times to the database. So if you change that `.env` var, then any time that the system saves it tries to save relative to that timezone.
> 
> However, the backup system's "storage" is just a set of files that live in the filesystem. So the times for those files are _always_ going to be relative to what the server's timezone is. If you want to make the timezones show up differently, you'd probably have to modify the server's timezone to match what you expect - then the timestamps on those files (at least going forward?) _should_ match.

v5.4.4 doesn't have such issues.

**Comment by snipe** [comment]
Not a lot has changed in that controller since v5.4.4 tho

**Comment by snipe** [comment]
@inietov can you take a look at this?

**Comment by JoatWiPete** [comment]
Can confirm it is resolved. It is much appreciated. Thank you.
