### ISSUE TITLE
Customfields with checkbox can't be detected from the asset response in the API

### ISSUE THREAD

**Issue by 0xpr03** [grokability/snipe-it#11092]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When requesting an asset via the API with a checkbox type, you won't be able to detect which kind of customfield it is.

### Reproduction steps

1. Create a checkbox custom field
2. Create a text custom field
3. Fill both and request the data via the API
4. Try to distinguish which kind of information is valid

### Expected behavior

The `element` is reported or `field_format` is indicating that you're looking at something that expects specific values. Currently you will have to request all custom fields (no ID is reported, get API requires an ID) and then find out which has the same name, then derive which kind of custom field it actually is.

### Screenshots

API response for an asset
![image](https://user-images.githubusercontent.com/1280209/168491423-13c053f1-0f30-45d8-ad83-de1834fd68cc.png)
Definition in the UI
![image](https://user-images.githubusercontent.com/1280209/168491463-e67de64e-a0e7-4098-b9ad-53264a7a90ca.png)

### Snipe-IT Version

5.4.3

### Operating System

Debian

### Web Server

Apache

### PHP Version

7.4

**Comment by snipe** [comment]
I know we've done some work on the checkboxes since v5.3 - can you try upgrading to v6 and see if this is still happening?

**Comment by 0xpr03** [comment]
Nope, v6.0.2 is the same.
![image](https://user-images.githubusercontent.com/1280209/172864667-8919a2eb-1d8c-4566-946d-f2d61e94b5ef.png)
