### ISSUE TITLE
Git Pull is resulting in error 500

### ISSUE THREAD

**Issue by LSNIGHTSHOT** [grokability/snipe-it#11097]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Running git pull results in an error 500 on the website.

### Reproduction steps

1. Open terminal in project root folder
2. Type git pull and press enter
3. Broken Site.

### Expected behavior

Working site

### Snipe-IT Version

5.4.4

### Operating System

Windows Server 2022

### Web Server

IIS

### PHP Version

7.4.19

### Operating System

Windows

### Browser

Chrome / Edge

### Version

101.0.1210.47 

### Additional context

Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/dbal 3.3.2 -> satisfiable by doctrine/dbal[3.3.2].
    - doctrine/dbal 3.3.2 requires composer-runtime-api ^2 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

In ProviderRepository.php line 208:

  Class 'Barryvdh\DomPDF\ServiceProvider' not found

**Comment by jeffmcm64** [comment]
Same here.

**Comment by snipe** [comment]
Please try upgrading your version of composer.

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#use-composer-2

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues#use-composer-2">Common Issues</a></strong></div><div>These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin. Or to run them as a one-liner all at once: These commands clear out cached service files that help speed up modern PHP applications but can a...</div></blockquote>

**Comment by LSNIGHTSHOT** [comment]
This fixed it for me!

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
