### ISSUE TITLE
Error running any command using the artisan file

### ISSUE THREAD

**Issue by r-hardiman** [grokability/snipe-it#11102]
### Debug mode

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to upgrade an existing installation or create a new installation of SnipeIt I get the following error message:

```
In Request.php line 334:

  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in **InstallationDir**\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\SetRequestForConsole.php on line 32
```

I also get the error whenever I run "Composer Update" or "composer install --no-dev --prefer-source". After looking into this a little it happens whenever a command is run that utilises the artisan file.

### Reproduction steps

1. Git Pull the repo
2. "composer install --no-dev --prefer-source"
3. Error happens

### Expected behavior

Be able to run artisan commands with no error message.

### Screenshots

![image](https://user-images.githubusercontent.com/73717574/168596551-161834d1-059e-4e07-ab08-929f743a294e.png)

### Snipe-IT Version

6.0.0

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

7.4.29

**Comment by r-hardiman** [comment]
I ended up reverting my changes to go back to version 5.4 and started off by updating Composer before upgrading Snipe-It and I didn't get this error the second time round, not sure if updating composer first fixed the issue or was a coincidence but I am going to close the issue as I can no longer replicate it.

**Comment by bj-k** [comment]
I still get the same issue with a clean installation of tag v6.0.1. 
Any workaround with going back to version v5.4.4, running php composer.phar install --no-dev --prefer-source and then upgrading to v6.0.1 didn't change anything. But I always used the latest Composer version.

> php composer.phar diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 2.3.5
PHP version: 7.4.6
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
cURL version: 7.66.0 libz 1.2.11 ssl OpenSSL/1.1.1d-fips
zip: extension present, unzip present, 7-Zip not available

**Comment by MattyHumphrey** [comment]
I also experianced this problem while upgrading in a test enviroment. Windows Server 2019 IIS

**Comment by MattyHumphrey** [comment]
@bj-k  In your env file make sure App URL is not set to null

**Comment by snipe** [comment]
Not sure - that's not a super helpful error message (not your fault, that's the framework's fault.)

What's your APP_URL in your .env?

**Comment by bj-k** [comment]
Thanks for your answers. 
The APP_URL was actually set to null at that point. I migrated the .env file from an older version which apparently didn't require to set it.

I stayed at version 5 for now but I try to to test it next week.

**Comment by bj-k** [comment]
Must indeed have been the APP_URL=null.
The update to both v6.0.1 and v6.0.2 works now.

Thanks for your help.
