### ISSUE TITLE
Error: Class "Laravel\Dusk\DuskServiceProvider" not found after upgrading from v.5.4.4 to v6.0.0

### ISSUE THREAD

**Issue by nathanrsafti** [grokability/snipe-it#11109]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Error upon upgrading to Snipe-IT v6.0.0 via upgrade.php, I now get this error. I have attempted following standard troubleshooting steps after the update:
1. Deleting files within `bootstrap/cache`
2. Running `composer dump-autoload`. 
3.  `git reset --hard origin/master`, thinking it might have been an inconsistency between my install and the latest release.

### Reproduction steps

1. Run php upgrade.php
2.
3.
...

### Expected behavior

That Snipe-IT would load normally.

### Screenshots

![image](https://user-images.githubusercontent.com/100974873/168655517-bf1fdb6a-f969-4fe4-8330-c93209cd2448.png)
![image](https://user-images.githubusercontent.com/100974873/168655600-871d70fd-4578-4bf0-9298-b4f1943741c9.png)

### Snipe-IT Version

v6.0.0

### Operating System

Windows Server 2022

### Web Server

IIS

### PHP Version

8.0.19

### Error messages

```shell
<!--
Error: Class &quot;Laravel\Dusk\DuskServiceProvider&quot; not found in file D:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Application.php on line 745

#0 D:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(679): Illuminate\Foundation\Application-&gt;resolveProvider()
#1 D:\Snipe-IT\app\Providers\AppServiceProvider.php(82): Illuminate\Foundation\Application-&gt;register()
#2 D:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(682): App\Providers\AppServiceProvider-&gt;register()
#3 D:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php(75): Illuminate\Foundation\Application-&gt;register()
#4 D:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(659): Illuminate\Foundation\ProviderRepository-&gt;load()
#5 D:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\RegisterProviders.php(17): Illuminate\Foundation\Application-&gt;registerConfiguredProviders()
#6 D:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(237): Illuminate\Foundation\Bootstrap\RegisterProviders-&gt;bootstrap()
#7 D:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(153): Illuminate\Foundation\Application-&gt;bootstrapWith()
#8 D:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(137): Illuminate\Foundation\Http\Kernel-&gt;bootstrap()
#9 D:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter()
#10 D:\Snipe-IT\public\index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle()
#11 {main}
-->
```

**Comment by snipe** [comment]
What's your APP_ENV set to? It will only try to include that service provider if your APP_ENV is set to local or develop. If you're using local or develop, you should make sure to run composer install without the `--no-dev` flag.

**Comment by nathanrsafti** [comment]
It was set to local, I had switched it to local earlier because the debugging mode complained about it. On to work on the next error. Thanks!
