### ISSUE TITLE
Unaccepted Assets Report fails to load upon upgrading to 6.0 or 6.1

### ISSUE THREAD

**Issue by brichardson-insync** [grokability/snipe-it#11118]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Upgrade ran fine but now we cannot open our "unaccepted assets" report it gives a error

### Reproduction steps

1.Took Snapshot of VM 
2.Upgraded via php upgrade
3.open unaccepted assets in multiple browsers/incognito etc - fails to load
...

### Expected behavior

Unaccepted assets report should show.

### Snipe-IT Version

6.01

### Operating System

Debian

### Web Server

Apache

### PHP Version

7.4.29

### Operating System

Windows 11

### Browser

Chrome

### Error messages

```shell
https://flareapp.io/share/x7X6YJVm#F76

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by snipe** [comment]
Those aren't really error messages though. What's in your stack trace? Try latest on  master.

**Comment by snipe** [comment]
Any luck?

**Comment by brichardson-insync** [comment]
Hi,

No I've not yet been able to try the latest. What can I do to get you the stack trace

**Comment by brichardson-insync** [comment]
After upgrading to 6.0.2 it's now working as expected.
