### ISSUE TITLE
Incorrect dashboard link (Asset Locations)

### ISSUE THREAD

**Issue by Erica-Lachowitz** [grokability/snipe-it#11112]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Incorrect data-formatter defined for the location of the dashLocationSummary causes links to point to categories and not locations. Corrected the issue by setting: data-formatter="locationsLinkFormatter"

See screenshot (line 304 in dashboard.blade.php)

### Reproduction steps

1. Click on location from the Assets Location dashboard
2. Generate error pointer to Categories

### Expected behavior

Open up a list view of Asset Locations per selection.

### Screenshots

![image](https://user-images.githubusercontent.com/76656758/168699089-fd912639-3451-40f5-bff5-78f074fe510a.png)

### Snipe-IT Version

6.0

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.29

**Comment by snipe** [comment]
Thanks! Fixed on master now :)
