### ISSUE TITLE
Restore from ZIP Backup gives us an Error

### ISSUE THREAD

**Issue by rp-asilva** [grokability/snipe-it#11121]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi all, thank you for your help here

Basically, when we perform a backup following this guide -- https://snipe-it.readme.io/docs/backups

And we try to restore this backup following this guide -- https://snipe-it.readme.io/docs/restore-from-backup-file

It gives us the following error

```
root@bacc06c2c884:/# /usr/bin/php7 /var/www/html/artisan snipeit:restore /config/storage/app/backups/snipe-it_`date --date="yesterday" +%Y-%m-%d`.zip -v
Current working directory is: /

 Are you sure you wish to restore from the given backup file? This can lead to MASSIVE DATA LOSS! (yes/no) [no]:
 > yes

Found a sql file!



   ErrorException  : fopen(storage/oauth-private.key): failed to open stream: No such file or directory

  at /var/www/html/app/Console/Commands/RestoreFromBackup.php:275
    271|         foreach($interesting_files AS $pretty_file_name => $file_details) {
    272|             $ugly_file_name = $za->statIndex($file_details['index'])['name'];
    273|             $fp = $za->getStream($ugly_file_name);
    274|             //$this->info("Weird problem, here are file details? ".print_r($file_details,true));
  > 275|             $migrated_file = fopen($file_details['dest']."/".basename($pretty_file_name),"w");
    276|             while(($buffer = fgets($fp))!== false) {
    277|                 fwrite($migrated_file,$buffer);
    278|             }
    279|             fclose($migrated_file);

  Exception trace:

  1   fopen()
      /var/www/html/app/Console/Commands/RestoreFromBackup.php:275

  2   App\Console\Commands\RestoreFromBackup::handle()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36

  3   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php:37

  4   Illuminate\Container\Util::unwrapIfClosure()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93

  5   Illuminate\Container\BoundMethod::callBoundMethod()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37

  6   Illuminate\Container\BoundMethod::call()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:590

  7   Illuminate\Container\Container::call()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:134

  8   Illuminate\Console\Command::execute()
      /var/www/html/vendor/symfony/console/Command/Command.php:255

  9   Symfony\Component\Console\Command\Command::run()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:121

  10  Illuminate\Console\Command::run()
      /var/www/html/vendor/symfony/console/Application.php:1009

  11  Symfony\Component\Console\Application::doRunCommand()
      /var/www/html/vendor/symfony/console/Application.php:273

  12  Symfony\Component\Console\Application::doRun()
      /var/www/html/vendor/symfony/console/Application.php:149

  13  Symfony\Component\Console\Application::run()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php:93

  14  Illuminate\Console\Application::run()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:131

  15  Illuminate\Foundation\Console\Kernel::handle()
      /var/www/html/artisan:35
```

### Reproduction steps

1. Perform the ZIP Backup
2. Restore the ZIP Backup
...

### Expected behavior

The backup is properly restored

### Snipe-IT Version

 Version v5.4.3 - build 6812 (master)

### Operating System

Centos, but running SnipeIT inside a Docker Container

### Web Server

None

### PHP Version

None

### Additional context

We installed SnipeIT using the Docker Version

We are trying to restore the backup in a new Docker Container in another machine

**Comment by snipe** [comment]
Do you actually have a `storage/oauth-private.key` in that zip?

**Comment by rp-asilva** [comment]
Yes, inside the backup we have the key, this is the path when we unzip the file -- snipe-it-backup\var\www\html\storage\oauth-private.key

**Comment by snipe** [comment]
The restore tool is a new feature and is still experimental. I'll have @uberbrady have a look tomorrow when he's online.

**Comment by rp-asilva** [comment]
Great, many thanks for your help!

**Comment by uberbrady** [comment]
If your Snipe-IT install lives in: `/var/www/html/` you should probably try to run the command from there - you might get better results - the `./storage` subdirectory it's looking for should already be there.

**Comment by rp-asilva** [comment]
Hi Uberbrady! Sorry for the late reply here,

Finally, today I was able to try your fix....

It worked as expected, I ran the restore command from the `/var/www/html/` folder and it was restored successfully, many thanks! 

And great job to all the team for creating this awesome app, it is very useful for tracking all the IT stuff

**Comment by uberbrady** [comment]
So glad you got it going!
