### ISSUE TITLE
LDAP Connects, No users appear after import

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#11131]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

LDAP connection works during testing and syncs. However, users are not appearing in under People 

### Reproduction steps

1. Sync using LDAP
2. click People to view system users
3.
...

### Expected behavior

LDAP imports users and they appear under People

### Snipe-IT Version

6.0.1

### Operating System

server 2012 r2

### Web Server

WAMP 3.2.6

### PHP Version

7.4.26

### Operating System

win 11

### Browser

Chrome

### Version

Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by uberbrady** [comment]
I'll probably need to see logs. Also, on the dashboard, does it say '0 people' or is there an actual list?

Do you see anything in the Web Developers console, any errors?

**Comment by jmartins1** [comment]
I think I’ll just wait for another version and try again. It’s an odd issue. I’ve installed it exactly the same way multiple times on a couple of computers. On my 2012 R2,  the users sync but don’t appear (it does give me a quality on the dashboard). On my Windows 11 computer it works fine. Please close the ticket for now.

 

Joe
