### ISSUE TITLE
500 Error creating new asset - full new install

### ISSUE THREAD

**Issue by stf675** [grokability/snipe-it#11132]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When try to create new asset model getting 500 Error

### Reproduction steps

1. Go Asset Models
2. Click Create New
3.
...

### Expected behavior

not error 500 I assume

### Snipe-IT Version

6.01

### Operating System

Rocky Linux 8.5

### Web Server

Apache

### PHP Version

8.0.19

### Operating System

Rocky Linux 8.5

### Browser

n/a

### Version

n/a

### Device

n/a

### Operating System

m/a

### Browser

n/a

### Version

n/a

### Error messages

```shell
The /var/www/html/snipe/bootstrap/cache directory must be present and writable. (View: /var/www/html/snipe/resources/views/models/edit.blade.php)

The /var/www/html/snipe/bootstrap/cache directory must be present and writable. (View: /var/www/html/snipe/resources/views/models/edit.blade.php)
/var/www/html/snipe/vendor/livewire/livewire/src/LivewireComponentsFinder.php#59
Facade\Ignition\Exceptions\ViewException

The /var/www/html/snipe/bootstrap/cache directory must be present and writable.
/var/www/html/snipe/vendor/livewire/livewire/src/LivewireComponentsFinder.php#59
```

### Additional context

directories listing

drwxr-xr-x. 12 root root   4096 May 17 14:26 **src**

drwxr-xr-x. 2 root root   64 May 17 14:27 **cache**

**Comment by snipe** [comment]
> The /var/www/html/snipe/bootstrap/cache directory must be present and writable.

That directory must be present and writable. It's sort of telling you what's wrong right on the tin.

**Comment by snipe** [comment]
(Your web server is likely not running as root, it's running as `www-data`, or something else, so it won't be able to create directories within the cache dir and other dirs. Also, you should never run websites with files owned by root, ever.)

**Comment by stf675** [comment]
it runs as 'apache'  (after being installed under root) I changed directory to be writable but getting same error. Setup did not indicated any permission errors.

I can create anything except asset model

Also, not sure if that same thing, when I go to create asset and click new next to model - I am getting proper screen (as I expect it)

**Comment by snipe** [comment]
Are you sure that's actually the error that's being generated? Are you in debug mode so you see the stack trace on the screen? Are you running SELinux?

**Comment by snipe** [comment]
(You should still definitely not have root own any of the files or directories tho)

**Comment by snipe** [comment]
Do you have custom fields enabled? If so, can you expand the "DB column name" column on your custom fields view and show me a screenshot?

**Comment by stf675** [comment]
is that something I see when debug is enabled? or it is a setting somewhere?  

thanks

**Comment by stf675** [comment]
installing from scratch using
https://computingforgeeks.com/install-snipe-it-asset-management-on-centos-8-linux/
and
https://snipe-it.readme.io/docs/debugging-permissions

fixed that issue.


<blockquote><div><strong><a href="https://computingforgeeks.com/install-snipe-it-asset-management-on-centos-8-linux/">Attention Required! | Cloudflare</a></strong></div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/debugging-permissions">Debugging Server Permissions</a></strong></div><div>One of the most common issues folks newer to running web servers run into is how to manage the Linux/Windows/etc owners and groups of the Snipe-IT filesystem. As we mention many times in the installation documentation, nothing in Snipe-IT should be run as or owned by root. Running composer as root, ...</div></blockquote>
