### ISSUE TITLE
Asset-Label QR-Code not working for newly created Assets since upgrading to 6.0.1

### ISSUE THREAD

**Issue by AccelerentIT** [grokability/snipe-it#11145]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After updating to 6.0.1 the QR-Code on Labels are not working for newly created assets.
Old assets for which we allready generated the Labels are working fine.

![image](https://user-images.githubusercontent.com/92804981/169010269-25e0572f-4ff5-4473-8962-25a652e51bfa.png)

`Error
Call to undefined function Com\Tecnick\Barcode\imagecreate()`

It looks like it wants to access the QR-Code via IP, which of course wont work because of SSL Error. Maybe that has something to do with the error?

`https://10.65.113.238/hardware/874/qr_code` for example.

APP_URL is set to the public domain. 

### Reproduction steps

1. Create new Asset
2. Click "Generate Label'
3.  Label loads but with broken QR-Code
...

### Expected behavior

QR-Code on Label is visible.

### Snipe-IT Version

v6.0.1

### Operating System

Ubuntu 20.04.4

### Web Server

Apache

### PHP Version

8.0

### Error messages

```shell
Error
Call to undefined function Com\Tecnick\Barcode\imagecreate()
https://10.65.113.238/hardware/874/qr_code
```

**Comment by snipe** [comment]
I can't reproduce this on the demo.

**Comment by AccelerentIT** [comment]
I forgot to install php8.0-gd after upgrading PHP. It's working fine now.
Thanks :)

**Comment by snipe** [comment]
Great, thanks for the follow up!
