### ISSUE TITLE
Dark Mode Skins - Licence detail tab white background

### ISSUE THREAD

**Issue by CrtiUser** [grokability/snipe-it#11146]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When applying dark mode skins in 6.0.1 the background of the license detail tab is white always and font is light gray.
This is nearly unreadable.
All other license tab backgrounds are dark. This problem applies to all dark skins.

### Reproduction steps

1. Apply a dark skin
2. Click on licenses
3. Select a license
4. Detail background color is white, all other tabs are dark.
5. Found no fix to switch background to dark on details.

### Expected behavior

Detail background color should also be dark.

### Snipe-IT Version

6.0.1

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4

**Comment by snipe** [comment]
@Godmartinz you want to take a stab at this too, since you're poking around in skins today?

**Comment by Godmartinz** [comment]
taking a look 👀

**Comment by snipe** [comment]
This is now on master
