### ISSUE TITLE
API GET accessories 404

### ISSUE THREAD

**Issue by FukjemiCZ** [grokability/snipe-it#11141]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug
 
Hi, after upgrade to ver 6.0.1 not working API request in my Snippe-it environment. 
`$response = Invoke-WebRequest -Uri 'https://develop.snipeitapp.com/api/v1/accessories?limit=50&offset=0&search=null&order_number=null&sort=created_at&order=desc&expand=false' -Method GET -Headers $headers`

### Reproduction steps

I read documentation and simulate the same error in demo
1.I trying demo in api documentacion https://snipe-it.readme.io/reference/accessories 

### Expected behavior

I would expect not to receive a 404 error.
Maybe I would expect current documentation.

### Snipe-IT Version

6.0.1

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8

**Comment by snipe** [comment]
Fixed on master and develop - thanks for the heads up :)
