### ISSUE TITLE
Server 500 Error

### ISSUE THREAD

**Issue by dborko95** [grokability/snipe-it#11155]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Server 500 Error

PHP Fatal Error: Uncaught Error: Class 'Log' not found in /var/www/html/snipe-it/app/Exceptions/Handler.php:44\nStack trace:\n

#0 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(165): App\\Exceptions\\Handler->report()\n
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(207): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n
#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n
#3 {main}\n  thrown in /var/www/html/snipe-it/app/Exceptions/Handler.php on line 44

### Reproduction steps

1. restarting apache2
2. try to access the web page
3. get server 500 error
4. check /var/log/apache2/error.log
...

### Expected behavior

expecting the web page to load normally

### Snipe-IT Version

6.0.1

### Operating System

Ubuntu

### Web Server

Apache 2.4

### PHP Version

I tried with 7.4/8.0

### Operating System

Windows

### Browser

Google Chrome and FF

### Error messages

```shell
PHP Fatal Error: Uncaught Error: Class 'Log' not found in /var/www/html/snipe-it/app/Exceptions/Handler.php:44\nStack trace:\n

#0 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(165): App\\Exceptions\\Handler->report()\n
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(207): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n
#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n
#3 {main}\n  thrown in /var/www/html/snipe-it/app/Exceptions/Handler.php on line 44
```

### Additional context

I tried upgrading from our 5.0.2 but ran into issues so I exported the folder completely and followed the guide on converting to using git for future upgrades and have been stuck with 500 error since.

For reference my composer is version 2.2 if it helps as well. I got less errors after moving to composer 2.2 from 2.0

I have checked my .env file as many forms have mentioned and tried adding single quotes in some areas that I thought may be tripping it up but still no positive results...

below is my .env file and my .env file with single quotes added - this is my .env from my 5.0.2 which was working before upgrade attempt. I have a snapshot to roll back to at any time if needed but snipe it is currently down trying to upgrade to 6.0.1

#Created By Snipe-it Installer
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=true
APP_KEY=base64:4dXXXXXXXXXXXX9KuNARe8V8w=
APP_URL=http://equipment.my-domain.com:444
APP_TIMEZONE=America/Toronto
APP_LOCALE=en
MAX_RESULTS=500

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipe_user
DB_PASSWORD=XXXXXXX
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_IS_PAAS=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.my-domain.com
MAIL_PORT=25
#MAIL_USERNAME=''
#MAIL_PASSWORD=''
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=equipment@my-domain.com
MAIL_FROM_NAME=Equipment
MAIL_REPLYTO_ADDR=helpdesk@my-domain.com
MAIL_REPLYTO_NAME=Equipment
MAIL_BACKUP_NOTIFICATION_ADDRESS=you@example.com

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false

# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false
REFERRER_POLICY=same-origin
ENABLE_CSP=false
CORS_ALLOWED_ORIGINS=null
ENABLE_HSTS=false

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHE_PREFIX=snipeit

# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT=null

# --------------------------------------------
# OPTIONAL: MEMCACHED SETTINGS
# --------------------------------------------
MEMCACHED_HOST=null
MEMCACHED_PORT=null

# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null

# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOG_MAX_FILES=10
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_CIPHER='AES-256-CBC'
#GOOGLE_MAPS_API=
BACKUP_ENV=true
LDAP_MEM_LIM=500M
LDAP_TIME_LIM=600

#Created By Snipe-it Installer
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=true
APP_KEY='base64:4dXXXXXXXXXXXXXXXXXXXXXRe8V8w='
APP_URL='http://equipment.my-domain.com:444'
APP_TIMEZONE='America/Toronto'
APP_LOCALE=en
MAX_RESULTS=500

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME='snipe_user'
DB_PASSWORD='XXXXXXXXX'
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET='utf8mb4'
DB_COLLATION='utf8mb4_unicode_ci'

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_IS_PAAS=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST='smtp.my-domain.com'
MAIL_PORT=25
#MAIL_USERNAME=''
#MAIL_PASSWORD=''
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR='equipment@my-domain.com'
MAIL_FROM_NAME=Equipment
MAIL_REPLYTO_ADDR='helpdesk@my-domain.com'
MAIL_REPLYTO_NAME=Equipment
MAIL_BACKUP_NOTIFICATION_ADDRESS='you@example.com'

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME='snipeit_session'
COOKIE_DOMAIN=null
SECURE_COOKIES=false

# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
APP_TRUSTED_PROXIES='192.168.1.1,10.0.0.1'
ALLOW_IFRAMING=false
REFERRER_POLICY='same-origin'
ENABLE_CSP=false
CORS_ALLOWED_ORIGINS=null
ENABLE_HSTS=false

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHE_PREFIX=snipeit

# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT=null

# --------------------------------------------
# OPTIONAL: MEMCACHED SETTINGS
# --------------------------------------------
MEMCACHED_HOST=null
MEMCACHED_PORT=null

# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null

# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOG_MAX_FILES=10
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_CIPHER='AES-256-CBC'
GOOGLE_MAPS_API=''
BACKUP_ENV=true
LDAP_MEM_LIM=500M
LDAP_TIME_LIM=600

**Comment by snipe** [comment]
Can you check and make sure your `storage` directory and all subdirectories are writable by the user the web server runs as?

**Comment by dborko95** [comment]
I checked all subfolders/files are owned by snipeitapp:www-data

**Comment by snipe** [comment]
Are they writable though?

**Comment by dborko95** [comment]
all directories under snipe-it/storage are drwxr-xr-x

**Comment by snipe** [comment]
What happens when you run `composer dump-autoload`?

**Comment by snipe** [comment]
And did you follow the directions in the docs? https://snipe-it.readme.io/docs/installation-issues#fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by dborko95** [comment]
yeah, I made sure there was no extra spaces on the end of each line in the .env, cleared files in bootstrap/cache/ ran composer dump-autoload

this is hosted on a VM in house so it's not on AWS but I checked to make sure there was no aws.php file as well just in case.

**Comment by dborko95** [comment]
`snipeitapp@cicvglpip1:/var/www/html/snipe-it$ cat .env
#Created By Snipe-it Installer
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=true
APP_KEY=base64:4dCXXXXXXXXXXXXXXXXXXXXXXXXXXXXXe8V8w=
APP_URL=http://equipment.example.com:444
APP_TIMEZONE=America/Toronto
APP_LOCALE=en
MAX_RESULTS=500
# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipe_user
DB_PASSWORD=XXXXXXXXXXXXX
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci
# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_IS_PAAS=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.example.com
MAIL_PORT=25
#MAIL_USERNAME=
#MAIL_PASSWORD=
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=equipment@example.com
MAIL_FROM_NAME=Equipment
MAIL_REPLYTO_ADDR=helpdesk@example.com
MAIL_REPLYTO_NAME=Equipment
MAIL_BACKUP_NOTIFICATION_ADDRESS=you@example.com
# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd
# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false
# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false
REFERRER_POLICY=same-origin
ENABLE_CSP=false
CORS_ALLOWED_ORIGINS=null
ENABLE_HSTS=false
# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHE_PREFIX=snipeit
# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT=null
# --------------------------------------------
# OPTIONAL: MEMCACHED SETTINGS
# --------------------------------------------
MEMCACHED_HOST=null
MEMCACHED_PORT=null
# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null
# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60
# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOG_MAX_FILES=10
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_CIPHER='AES-256-CBC'
#GOOGLE_MAPS_API=
BACKUP_ENV=true
LDAP_MEM_LIM=500M
LDAP_TIME_LIM=600`

**Comment by dborko95** [comment]
> What happens when you run `composer dump-autoload`?

Generating optimized autoload files
Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: maatwebsite/excel
Discovered Package: mediconesystems/livewire-datatables
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
Generated optimized autoload files containing 8572 classes

**Comment by dborko95** [comment]
[snipe-env.txt](https://github.com/snipe/snipe-it/files/8720625/snipe-env.txt)

Attaching the .env file so you can see how it is exactly in my server instead of gits formatting

it's saved as .env on the actual server this was just me extracting / altering sensitive info

**Comment by snipe** [comment]
Try putting `APP_TIMEZONE=America/Toronto` in quotes, as `APP_TIMEZONE="America/Toronto"`

**Comment by snipe** [comment]
Also if your DB password has weird characters in it, enclose that in quotes too

**Comment by snipe** [comment]
And 

```
MAIL_FROM_ADDR="equipment@example.com"
MAIL_FROM_NAME="Equipment"
MAIL_REPLYTO_ADDR="helpdesk@example.com"
MAIL_REPLYTO_NAME="Equipment"
```

**Comment by dborko95** [comment]
we're back online!

1. Adding the double quotes around our .env configs including anything involving our hyphenated domain got me to a point I could see the debugging page and no longer just a server 500 page

2. The debug page stated it could not write to laravel.log, which did not exist so;
                 -  I created a blank file called laravel.log
                 -  chowned to snipeitapp:www-data
                 -  chmoded 0765 ./laraval.log
                 -  restarted apache

3. got past that laravel error and got a new error under framework/sessions/ that it could not write to awreoghaeorihgao....
                 - I created a blank file called whatever it was looking for
                 - chowned to snipeitapp:www-data
                 - chmoded 0765 the random character file name
                 - restarted apache

4. still got the above error even though all folders under and including /storage were drwxr-xr-x 
                 - after clearing cache and dumping autoload
                 - chmod -R 775 storage/
                 - restart apache
                 
5. I was finally able to login again! Once I could get in, almost everything was fine except for opening user profiles but that was an easy fix since it told me to migrate the database
                 - php artisan migrate
                 - Y

6. once I migrated the database everything worked like normal again.

Thanks for your help Snipe! and hopefully this helps some other people if they get stuck

**Comment by dborko95** [comment]
[snipe-env-working.txt](https://github.com/snipe/snipe-it/files/8732176/snipe-env-working.txt)

for anyone wanting to see my .env that is working please feel free to see attached.

**Comment by snipe** [comment]
Glad you're sorted :)
