### ISSUE TITLE
Error 500 because assets and licenses uploaded files not found after upgrade to v6

### ISSUE THREAD

**Issue by eduardokvb** [grokability/snipe-it#11150]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

APP_DEBUG=true helped me find out that v6 expected an uploaded file to be at storage/private_uploads/assets , whereas in my v5 install (v5.0.8, it seems) had the files in storage/private_uploads/.

The solution was to move all hardware-* files into the assets subdirectory.
The same happens for license-* files, that have to be moved to the licenses subdirectory.
I tried my best to find any note about this before making this report, so it might be useful to someone else.

Thanks!

### Reproduction steps

1. Try to access any inventory record that had uploaded files on v5.x

### Expected behavior

1. Inventory record is listed normally, without error 500, if a migration script moves the files.
2. To complement, the system should still allow access to the inventory record but inform the name of the file that was not found, perhaps pointing to a help link that would state this common issue.

### Snipe-IT Version

6.0.0

### Operating System

Debian 11.3

### Web Server

Apache

### PHP Version

7.4

**Comment by snipe** [comment]
We haven't changed any file paths for private uploads in v6. 

https://github.com/snipe/snipe-it/blob/v5.4.4/app/Http/Controllers/Assets/AssetFilesController.php#L52

(From v5.4.4)

**Comment by snipe** [comment]
Same for v5.0.8. 

https://github.com/snipe/snipe-it/blob/02fef7049f09db1f95b5a0cfbb5e63c5985811a5/app/Http/Controllers/Assets/AssetFilesController.php#L40

**Comment by eduardokvb** [comment]
Very interesting @snipe, because I know, for sure, I was accessing the given inventory record before the upgrade, and didn't get a 500, so maybe that is actually the difference, not path-related. That is, perhaps v5 didn't generate 500 when uploaded files were not found.
This issue could be coming from an even older upgrade then, since I have the old VM's disk and see the files were uploaded in 2017.
Anyway, hopefully this is useful as reference for someone else experiencing this, feel free to close this item, but preventing the 500 might be nice.
Thank you for your time and knowledge!

**Comment by dsferruzza** [comment]
Hi!

Actually I'm getting a similar error when accessing the `/hardware/ID` page:

```
ErrorException
filesize(): stat failed for /home/bas/xxx/storage/private_uploads/assets/hardware-187-aVc4IyO1-xxx.pdf (View: /home/bas/xxx/resources/views/hardware/view.blade.php) 
```

My instance is configured to use S3 storage.
I realized that these lines might not work when using S3 storage: https://github.com/snipe/snipe-it/blob/v6.0.1/resources/views/hardware/view.blade.php#L1163-L1164
They were introduced in 3a31104b5c661e3d8cd2d1a88164fad536772831.

If I change them to the following, it works:

```php
<td data-value="{{ Storage::size('private_uploads/assets/'.$file->filename) }}">
    {{ Helper::formatFilesizeUnits(Storage::size('private_uploads/assets/'.$file->filename)) }}
```

@snipe Does this make sense?

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe-it/view.blade.php at v6.0.1 · snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe-it/view.blade.php at v6.0.1 · snipe/snipe-it</div></blockquote>

**Comment by minkbear** [comment]
@snipe @dsferruzza I run snipe it (v6.0.5 build 8230 (g393c32558)) and configured S3 Storage as well and got the same error below

`[previous exception] [object] (ErrorException(code: 0): filesize(): stat failed for /home/bas/xxx/storage/private_uploads/assets/hardware-479-sZqUdLpd-a-00346-huawei-notebook-matebook-14.pdf at /home/bas/xxx/storage/framework/views/53454a1234c8a9018de9055fa245028686578fab.php:1281)`
