### ISSUE TITLE
Specific Assets not Displaying

### ISSUE THREAD

**Issue by RussellLeVasseur** [grokability/snipe-it#11168]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Assets are not displaying that should be.

### Reproduction steps

1. Search for a specific asset. Results show 3 results, but only two are displayed.

### Expected behavior

All assets should display.

### Screenshots

![image](https://user-images.githubusercontent.com/58618324/169368852-93245b53-85ac-4dd6-bedc-dda4854d001d.png)

### Snipe-IT Version

v6.0.1

### Operating System

Ubuntu 20.04 and 22.04 (tested on both)

### Web Server

Apache and Nginx (tested on both)

### PHP Version

7.4 and 8.1 (tested on both)

### Operating System

Windows 11

### Browser

Firefox and Chrome (tested on both)

### Version

latest

### Error messages

```shell
No errors with Debug enabled
```

### Additional context

This was on an old install. I confirmed the same issue on v5 as well.

**Comment by RussellLeVasseur** [comment]
It looks like this may have been caused by a malformed Model? By changing models and changing it back, i got it to appear. Still a weird bug. The model has been in use for more than 6 months now. Unfortunately, I am not able to find any logs to find the source of the issue.

**Comment by snipe** [comment]
Hm, without any additional info, it would be hard to try to get to the bottom of this. If you see it happen again, please do let us know though.
