### ISSUE TITLE
Barcodes Missing in 6.0.1

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#11166]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Barcodes not appearing on individual asset pages nor when attempting to generate labels.

Example url for asset:
http://arpsinv1/hardware/131

Example url for barcode image:
http://arpsinv1//hardware/131/qr_code 

The barcode image address is not complete.

Verified that barcodes exist in: C:\wamp\www\snipe-it\public\uploads\barcodes

Confirmed the correct format for the APP_URL in the .ENV file.

### Reproduction steps

1. View and asset or
2. Attempt to generate labels
3.
...

### Expected behavior

Labels and asset page would include the image of the barcode.

### Screenshots

![a](https://user-images.githubusercontent.com/31219479/169360887-34f0ae1b-4cb1-4f30-8e43-85391655c7db.jpg)
![b](https://user-images.githubusercontent.com/31219479/169360888-cad4de67-8470-41b0-8cff-88bf65d1363a.jpg)

### Snipe-IT Version

6.0.1

### Operating System

2012R2

### Web Server

WAMP 3.2.6

### PHP Version

7.4.26

### Operating System

Win 11

### Browser

Chrome tried Firefox

### Version

Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by snipe** [comment]
This is not reproducible on the demo. What do you have set for your APP_URL? Looks like you might have a trailing slash?

**Comment by jmartins1** [comment]
![2022-05-19_11-33-39](https://user-images.githubusercontent.com/31219479/169362515-1cded63c-1f31-4505-9b02-1b816b5d0ac2.jpg)


All the barcode URLs end in: /qr_code

**Comment by jmartins1** [comment]
Please close.

Run:
php artisan config:clear
php artisan config:cache

Cleared the acne right up :)


![acne](https://user-images.githubusercontent.com/31219479/169363957-e1a6ecbf-66ce-4f8c-98c9-4f3b66e4f45f.jpg)

**Comment by alejandrasotos** [comment]
gracias, resolvio mi problema <3
