### ISSUE TITLE
Low Inventory Report include stock exceeding minimum quantity

### ISSUE THREAD

**Issue by c1thunder** [grokability/snipe-it#11162]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I noticed after the upgrade, the low inventory report also included exceeding the minimum quantity for both pop-up and email notification alert

![image](https://user-images.githubusercontent.com/20919681/169189950-2fdb3409-b916-4fb2-be43-c8da9137c914.png)

![image](https://user-images.githubusercontent.com/20919681/169189799-a1703506-ecaf-4ef2-bcd6-60207c54f0e6.png)

### Reproduction steps

1. Create a consumables item
2. Set a minimum quantity
3.  Set the stock above the minimum quantity
4. The system will prompting the low inventory

### Expected behavior

Alert showing all the item in consumables

### Snipe-IT Version

6.0.1

### Operating System

Windows Server 2012

### Web Server

IIS

### PHP Version

7.4

**Comment by inietov** [comment]
I think it's working as expected. In Settings > Notifications, there is an option to set the threshold of the notification that controls when the notifications shows up:

![image](https://user-images.githubusercontent.com/653557/172503806-f9976514-bb25-4234-ada3-812a7a439dcc.png)

If you find that it's actually correct, please close this issue.
