### ISSUE TITLE
Skins are broken (?)

### ISSUE THREAD

**Issue by Xiayu8** [grokability/snipe-it#11164]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Today i merged recent commits and now most of the text is greyed out. (everything which is a link/clickable)
The text is hard to read.
I am using black skin.

This behavior is reproducible with your demo website.

i've changed it back to yesterdays state.

### Reproduction steps

1.log in to demo website
2.change skin to black or green
3.every clickable/link text is greyed out or green
...

### Expected behavior

black text

### Screenshots

![black](https://user-images.githubusercontent.com/96250874/169234509-48bd040b-46a6-43b5-841b-9474019c9e47.PNG)
![green](https://user-images.githubusercontent.com/96250874/169234526-0ea36170-026c-478a-939b-fd5a96b31543.PNG)

### Snipe-IT Version

v6.0.1

### Operating System

ubuntu 20.04

### Web Server

apache

### PHP Version

7.4.3

**Comment by snipe** [comment]
@Godmartinz Can you take a look please

**Comment by snipe** [comment]
I don't think that's broken - it's behaving as expected. Perhaps you disagree with the choice of colors used, but it's doing what it's supposed to. You can always override the CSS in the Branding section of the admin.
