### ISSUE TITLE
[Feature Request]: Custom Fields for Other Items

### ISSUE THREAD

**Issue by mpermann** [grokability/snipe-it#11165]
### Is your feature request related to a problem? Please describe.

Is there any chance of bringing the concept of "custom fields" and "field sets" to other items like Accessories, Components, Consumables, Licenses, and People? 

### Describe the solution you'd like

The existing solution you're using for Assets could be utilized and extended to other types as well.

**Comment by snipe** [comment]
Duplicate of #4261

**Comment by mpermann** [comment]
Sorry for the duplicate feature request. Clearly I need to work on my GitHub searching skills. It looks like many other folks are interested in this as well. Hopefully it's something you all consider adding at some point in the future. Cheers!

**Comment by snipe** [comment]
No worries - it/s definitely on the roademap now that v6 is out :)
