### ISSUE TITLE
Activity Log / History not logging (sometimes)

### ISSUE THREAD

**Issue by Xiayu8** [grokability/snipe-it#11174]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am sorry, if this is again expected behavior.

Today i was recognizing some strange behavior on my local copy of SnipeIT.
I tried it on your demo website and i cant figure it out why it is behaving like this.
Some Assets log their changes and others dont.

### Reproduction steps

(On your Demo Website)
1.view the Asset 813315198, edit the serial number and save it. changes are logged correctly.
2.clone this asset, checkout to the same person, edit the serial again. changes are not logged.
3.create new asset, edit serial, changes are not logged.
...

### Expected behavior

changes shuold be logged

### Snipe-IT Version

v6.0.2

### Operating System

ubuntu 20.04

### Web Server

apache

### PHP Version

7.4.3

**Comment by RussellLeVasseur** [comment]
I was just about to open a case for this. I am seeing the same as well when updating assets via the API. Last updates are showing May 15. The assets are showing Last Updated correctly:
![image](https://user-images.githubusercontent.com/58618324/169528237-4643688a-50c5-4a5a-ae75-3b60f148cdb6.png)
SnipeIT v 6.0.1
Ubuntu Server 22.04
PHP 7.4.3
MariaDB 10.6.7
Dashboard Activity Log:
![image](https://user-images.githubusercontent.com/58618324/169527629-5889cd18-be0b-495b-b54d-5c8210d18d98.png)

**Comment by Midnex** [comment]
Having the same issue, I checked out two monitors to a user, and updated info on 3 new laptops, the update for the 3 laptops are not showing. Also on 6.0.1

**Comment by RussellLeVasseur** [comment]
Still occurring on 6.0.2.

Check-Ins and Check-Outs for users and licenses show in activity, but no Asset updates are showing.

**Comment by Xiayu8** [comment]
yep, still not working.
went back to v5.4.4

**Comment by snipe** [comment]
This fix should now be on master.
