### ISSUE TITLE
Accepted EULA with Cyrillic characters looks wrong

### ISSUE THREAD

**Issue by romannazarenko** [grokability/snipe-it#11175]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If EULA or asset name has cyrillic characters, Accepted EULA.pdf contains ???? instead of text:

### Reproduction steps

1. checkout asset
2. accept eula
3. download accepted-eula-.pdf

### Expected behavior

printable accepted EULA with Cyrillic characters

### Screenshots

![Capture](https://user-images.githubusercontent.com/25567563/169541764-030c04a6-998b-4c96-88f8-d83006d4c6cd.PNG)

### Snipe-IT Version

v6.0.1 build 7750 (gb2e7572fe)

### Operating System

Cent OS 7

### Web Server

Apache

### PHP Version

7.4.19

**Comment by snipe** [comment]
Thanks for reporting this - can you give me some sample text I can test this with?

**Comment by romannazarenko** [comment]
Thanks @snipe 
Some generic russian text below:

съешь ещё этих мягких французских булок, да выпей чаю

Открытое акционерное общество  (сокращенное наименование - ОАО  именуемое в дальнейшем «Арендодатель», в лице Генерального директорадействующего на основании Устава, с одной стороны, и Федеральное государственное унитарное предприятие (сокращенное наименование ФГУП именуемое в дальнейшем «Арендатор», в лице Директора  действующего на основании Устава, с другой стороны, совместно именуемые «Стороны», составили настоящий Акт  о нижеследующим:
1. Настоящий Акт приема-передачи удостоверяет то, ОАО передало, а ФГУП приняло в соответствии с условиями договорав количестве и комплекте, согласно Приложения № 1 к указанному Договору (далее – «Объекты»).

**Comment by Godmartinz** [comment]
https://github.com/dompdf/dompdf/issues/1656 seems to be that dompdf just doesn't come with the font. (relatively simple solution in the attached thread)

**Comment by snipe** [comment]
So, that shouldn't matter tho - otherwise we'd have to include every imaginable font.

**Comment by friendwnt** [comment]
![image](https://github.com/snipe/snipe-it/assets/170397597/1159796e-c354-4dda-acfc-56cc0df8c5a3)
Is there any solution to not displaying Chinese characters?
