### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by okkhalid** [grokability/snipe-it#11173]
### Is your feature request related to a problem? Please describe.

no, how we can get the acceptance link so we can ask the staff to sign in in front of us before we give out the device to the them.

now we have activated the signature in the settings, also we enabled the acceptance requirement at the category level  as advised in the guide, but the problem is the email with the link is sent to the person who is assigned to him and we need to ask them to forward the link to us, as all our users can not login to the system also we want the to sign front of us before we give out the asset.
Is that possible that we get a copy of that email that has the link so staff can sign?

### Describe the solution you'd like

get a copy of the email of the signature requirement

**Comment by okkhalid** [comment]
Hi any way for us to get copy, as all users in our company do not have login permission. so we can open the link to make the sign. 

thanks,

**Comment by okkhalid** [comment]
seems the user must login in order to accept. is that possible that we can avoid that, we still need their signature, but we do not want them to login to the system. is that possible.

**Comment by snipe** [comment]
Duplicate of #9653
