### ISSUE TITLE
[Feature Request]: Feature listed on roadmap but cant figure out if it implemented

### ISSUE THREAD

**Issue by stf675** [grokability/snipe-it#11170]
### Is your feature request related to a problem? Please describe.

Brand new deployment of v6.01

Due to license complexities, ability to add custom fields to "Licenses" is very important, borderline required.

From v6 roadmap at https://grokstar.dev/news/snipeit-releases/2021/07/snipe-it-v6-roadmap/

in FEATURE HIGHLIGHTS section, one libe reads...

` Custom fields for more models (people, **licences,** etc)`

I am not able to find how to use it.

### Describe the solution you'd like

as described in Roadmap's Feature Highlights,

ability to add custom fields to licenses

### Additional context

With various licensing types, at least we need to be able to address....

Subscription based or Perpetual

With Support that allowed version upgrade

per cpu / per core

applied to Virtual or Physical deployment (example qty 1 license allow one physical or two (or more) virtual)

Per Device, or per user

**Comment by snipe** [comment]
Wr didn't manage to get it into tis release, but hopefully soon. Follow this thread for updates. #11169
