### ISSUE TITLE
Opening select input no longer focuses live search

### ISSUE THREAD

**Issue by poandlsl** [grokability/snipe-it#11177]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When clicking a select input to open it, the live search text field is not focused, and requires an additional click in order to type-to-search.  This was the behavior in 5.4.3, but is no longer the case since upgrading to 6.0.1.

### Reproduction steps

1. Navigate to a page with a select input (e.g. /hardware/maintenance/create)
2. Click a select input (e.g the _Asset Tag_ field)
3. Attempt to type to search
4. Observe text field is not focused
...

### Expected behavior

1. Navigate to a page with a select input
2. Click a select input
3. Type to search
4. Search results should be returned

### Snipe-IT Version

6.0.1

### Operating System

CentOS 7

### Web Server

Apache 2.4

### PHP Version

7.4.28

### Operating System

Ubuntu 20.04

### Browser

Firefox

### Version

100

### Additional context

This issue is present after an upgrade from 5.4.3 to 6.0.1 using the `php ./upgrade.php` method.

**Comment by uberbrady** [comment]
This is fixed on master - as soon as we tag a new release, this fix will be included.
