### ISSUE TITLE
snipe:ldap-sync command returns Exit Code 1 instead of 0

### ISSUE THREAD

**Issue by exula** [grokability/snipe-it#11181]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Ever since the 6.0 upgrade, our nightly ldap-sync cron job has been returning as 1 exit code instead of 0

```run-parts: /etc/cron.daily/snipeitsyncldap exited with return code 1```

When running the **snipeit:ldap-sync** artisan command 1 is returned as the exit code instead of 0
When running with any of the --summary options 0 is returned.

This doesn't actually seem to be a LDAP issue at all. If I comment out line# 307

`return $summary;`

I get the right return code and life is groovy.

I'm not 100% sure why the command would have a return statement as Laravel console commands don't normally have a return value?

I know you have all been fighting some LDAP gremlins, I would normally PR this one, but I don't exactly know the consequences of that return statement. 

If I had to guess I would say that the behavior of the handle() function changed in the Laravel upgrade to 8.*

### Reproduction steps

1. ```php artisan snipeit:ldap-sync ; echo $```   <-- Should echo 1
2. Comment out line number 307 in **app/Console/Commands/LdapSync.php**
3. ```php artisan snipeit:ldap-sync ; echo $?``` <-- Should echo 0 now
...

### Expected behavior

Expected behaviour is a 0 return code (Command Successful)

### Snipe-IT Version

v6.0.1 build 7750 (gb2e7572fe)

### Operating System

ubuntu

### Web Server

Apache 

### PHP Version

7.4.3

### Error messages

```shell
No Error messages, the LDAP sync works perfectly.
```

**Comment by exula** [comment]
I just did a grep through the entire code base and it looks like there is no place that wants that specific return statement, the LDAPImportController is expecting the json return to the Artisan::output();
So it looks like it would be fine to remove that return statement in the ldap-sync command.

But, with the complexities of the LDAP system, there's no WAY I want to touch that with a 10ft pole. :no_good:

**Comment by snipe** [comment]
@uberbrady do the changes we pushed tonight affect this issue?

**Comment by uberbrady** [comment]
> @uberbrady do the changes we pushed tonight affect this issue?

No, I don't _think_ so, it shouldn't.

Having just emerged from having dug through the belly of the beast @exula - I'm 100% with you, I don't want to touch it either! But I suspect it's probably a pretty safe bet to remove. I'll play around with it and see if I can be sure.

**Comment by AlexanderWPapyrus** [comment]
Hi,
we also need now to click the sync button in the GUI. Had a Chronjpb before
`# snipeit ldap sync
0 * * * *       root    (cd /var/www/snipeit; php artisan snipeit:ldap-sync)
`

I noticed the issue after upgrading to php 7.4  (as we should for futureversions ;) (cli 8)
![image](https://user-images.githubusercontent.com/80526133/178457477-2b10c4ad-2d03-44ad-acdd-98092d6f758c.png)

```
root@XXXX:/var/log#   php --version
PHP 8.0.14 (cli) (built: Dec 20 2021 21:22:38) ( NTS )
```
![image](https://user-images.githubusercontent.com/80526133/178459554-63a0e8ff-f0f1-454a-8c28-e3a7aa1356a0.png)


I think I traced the issue back to: 
https://www.php.net/manual/en/function.ldap-control-paged-result.php
![image](https://user-images.githubusercontent.com/80526133/178457734-7a6664a4-1248-4f4d-b284-0e5749635a95.png)

> This function has been DEPRECATED as of PHP 7.4.0, and REMOVED as of PHP 8.0.0. 

@exula This might be the reason for the different return code. Which PHP CLI version do you have?

@snipe & @uberbrady ~~Are there already plans to update this code?~~ Sorry just realized it's already gone in the latest release.

 My colleges kept synching with location, which messed up the whole database. 
I had to remove this drop down div to prevent them to do so 🤣

![image](https://user-images.githubusercontent.com/80526133/178460499-f954bf2b-89fb-4361-ad63-babefe9a2409.png)

![image](https://user-images.githubusercontent.com/80526133/178460129-9309331c-2c60-474e-be66-7d230c83ef7e.png)



<blockquote><img src="https://www.php.net/favicon.ico?v=2" width="48" align="right"><div><strong><a href="https://www.php.net/manual/en/function.ldap-control-paged-result.php">PHP: ldap_control_paged_result - Manual</a></strong></div></blockquote>

**Comment by eickeh** [comment]
There's a workaround if you append the `--summary` flag. This somehow does what one expects and returns 0 if everything is fine.

**Comment by snipe** [comment]
This issue is pretty old - I'm going to close it for now, as LDAP has changed a lot in the past few years.
