### ISSUE TITLE
Missing Custom Fields

### ISSUE THREAD

**Issue by nstoupis** [grokability/snipe-it#11188]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When you go to create a new Asset, there are some custom fields missing and nothing has been changed for months on our site for macom.snipe-it.io  

The OS, Condition, Device Type, and Domain listboxes do not show up when creating a new Asset. I can see the "Computers" Fieldset listed. When I edit the Custom Field, it shows OS, List Box, various Field Values, and then Format is set to ANY and nothign in the Help Text field. 

### Reproduction steps

1. I tried logging in and fields missing. 
2. Co-worker tried logging in and seeing same issue. 
3.
...

### Expected behavior

Expected fields to show up when creating a new asset. They were there a few months ago and no one on our support team has gone in to change anything. 

### Screenshots

![Capture](https://user-images.githubusercontent.com/106166598/170061359-db86006c-7fd8-48ef-9211-f76ee343e136.JPG)

### Snipe-IT Version

5.4.4 Build 6829

### Operating System

Windows

### Web Server

NA

### PHP Version

NA

### Operating System

Windows 10

### Browser

Google Chrome

### Version

101.0.4951.67 (Official Build) (64-bit)

### Device

NA

### Operating System

NA

### Browser

NA

### Version

NA

### Error messages

```shell
No error messages
```

### Additional context

We have website we go to so no install or upgrade

**Comment by snipe** [comment]
There’s nothing we have done in the software that would remove custom fields. From where are they missing? The custom fields page or when you’re trying to create or edit an asset?

**Comment by nstoupis** [comment]
When we try to create a new asset, it does not show the custom fields. They are OS, Condition, Device Type, and Domain. These are all list boxes. When I go and look at the custom fields themselves, they are showing and assigned to the Computers field set. I can see the custom fields when looking at older assets. Just not showing for new ones we create.

**Comment by snipe** [comment]
I'd need more info here - anything in your browser console? Error logs?

**Comment by nstoupis** [comment]
Nothing comes up as far as an error. I can’t even delete the custom fields and add them back in to see if they come back in when creating a new asset.

***@***.***

When I look at an old asset, I can see the 4 fields. So it has to be something when creating a new asset, that it’s not adding these fields to the custom template.

***@***.***

**Comment by nstoupis** [comment]
Hello. We figured it out. So there were some models populated that were not part of the Computers field set. So when you chose the model, it would not bring up the 4 custom fields. I circled below some models not part of Computers field set. I can just fix it on my end. Sorry for the confusion.

***@***.***

From: Nicholas Stoupis
Sent: Wednesday, June 1, 2022 10:19 AM
To: snipe/snipe-it ***@***.***>; snipe/snipe-it ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [snipe/snipe-it] Missing Custom Fields (Issue #11188)

Nothing comes up as far as an error. I can’t even delete the custom fields and add them back in to see if they come back in when creating a new asset.

***@***.***

When I look at an old asset, I can see the 4 fields. So it has to be something when creating a new asset, that it’s not adding these fields to the custom template.

***@***.***

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)

**Comment by nstoupis** [comment]
When you try to create a New Asset.

***@***.***

Even though they are all part of the Computers fieldset

***@***.***
