### ISSUE TITLE
Unable to Edit Asset Models

### ISSUE THREAD

**Issue by Jarli01** [grokability/snipe-it#11187]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Running Snipe-IT 6.0.1 I'm unable to edit any asset model, when attempting to edit any asset model I receive an 500 error code. 

### Reproduction steps

1. Click onto any asset model
2. Click Edit
3. See error code 500
...

### Expected behavior

The ability to edit and update asset models. 

### Screenshots

![HcIuUBWWaR](https://user-images.githubusercontent.com/14837699/170038743-0af9521e-3494-43e4-a840-17d6d9bce3bc.png)
![msedge_Vl9FSO1OWB](https://user-images.githubusercontent.com/14837699/170036867-54c96713-d38d-471a-8dc0-16b57010b6de.png)
![msedge_Gc8JRwfw1H](https://user-images.githubusercontent.com/14837699/170036880-6503d62d-fad6-471c-9dea-0dffc671878b.png)
![image](https://user-images.githubusercontent.com/14837699/170037874-cda88e9d-f9f9-4ae9-927f-d51225c7dd3f.png)

### Snipe-IT Version

6.0.1

### Operating System

Ubuntu 20.10 Groovy

### Web Server

Apache

### PHP Version

7.4.9

### Operating System

Windows 10

### Browser

Edge

### Version

101.0.1210.47

### Error messages

```shell
Exception
The /var/www/html/snipeit/bootstrap/cache directory must be present and writable. (View: /var/www/html/snipeit/resources/views/models/edit.blade.php)

I'm assuming that the permissions are screwed-up, see screenshots above. 

Thanks
```

**Comment by snipe** [comment]
It's telling you what's wrong. The /var/www/html/snipeit/bootstrap/cache directory must be present and writable. If you make that directory writable, you should be fine.

**Comment by Jarli01** [comment]
Thanks for confirming, set the permissions to /var/www/html/snipeit/bootstrap/cache to 775 and that sorted it out.
