### ISSUE TITLE
Missing all images and QR codes

### ISSUE THREAD

**Issue by zoyi81** [grokability/snipe-it#11186]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello, 
The pictures and codes are not loaded because error 404 in browser editor.
The link is wrong and i would like toask for help to edit it:
wrong URL
http://IP/hardware/APP_URL/hardware/1/qr_code

The correct would be:
http://IP/hardware/1/qr_code

### Reproduction steps

1. clean install
2.
3.

### Expected behavior

all images are missing

### Screenshots

![image](https://user-images.githubusercontent.com/106153923/170019267-35f69700-b4a2-4d70-8b99-b3612ad412c5.png)

### Snipe-IT Version

v6.0.1 build 7750 (gb2e7572fe)

### Operating System

Ubuntu 20.04.4 LTS

### Web Server

apache2

### PHP Version

7.4.3

### Browser

google, edge, firefox, safari

**Comment by snipe** [comment]
What's your APP_URL? This is almost always due to an incorrect APP_URL.

**Comment by zoyi81** [comment]
APP_URL=snipeit.companyname.local

**Comment by zoyi81** [comment]
https://github.com/snipe/snipe-it/issues/8924
sorry it was easy but somehow it not worked i had.
 php artisan config:clear
after that needed some
 php artisan view:clear

**Comment by zoyi81** [comment]
the solution was: APP_URL=snipeit.companyname.local
change to APP_URL=http://localipaddress and after that
php artisan config:clear
after that needed some
php artisan view:clear
