### ISSUE TITLE
File Uploads, don't show in Target in Activity Report

### ISSUE THREAD

**Issue by Midnex** [grokability/snipe-it#11193]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When user A uploads a file to user B under People the activity report does not show a target, even thought it is directly uploaded to user B

### Reproduction steps

1. Upload a file to another user, or yourself
2. Check Activity Report to see if Target is listed
3.
...

### Expected behavior

Target should be listed as it directly affects a User or Asset. Note I have not tried this with an asset.

### Screenshots

Note 1/2 show no user listed.
![image](https://user-images.githubusercontent.com/702330/170131538-31eb2d2a-c73f-4bf2-885a-fce870c32ce3.png)

### Snipe-IT Version

v6.0.1 build 7750

### Operating System

PopOS! 21.04 Linux 5.15-11-760512511-generic x86_64

### Web Server

2.4.46 (Ubuntu)

### PHP Version

7.4.16

### Error messages

```shell
None are presented, confirmed working in demo.
```

### Additional context

Not a fresh install

**Comment by inietov** [comment]
Please checkout the
