### ISSUE TITLE
livewire.js gives 404 error when using a RewriteBase in .htaccess

### ISSUE THREAD

**Issue by bobeagan** [grokability/snipe-it#11195]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When loading any page, the console provides 
> GET https://example.com/vendor/livewire/livewire.js?id=c69d0f2801c01fcf8166 net::ERR_ABORTED 404

However, the Snipe IT installation is at `https://example.com/inventory/` so the subdirectory is lost when attempting to get the livewire JS file.

### Reproduction steps

1. Use a RewriteBase to install to a subdirectory
2. Access any page
3. View error in conosle

### Expected behavior

Not sure what I should be seeing when this works but in theory the lack of a 404 in the console would be expected behavior here.

### Snipe-IT Version

v6.0.2 build 7880 (g43c5b412c)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

**Comment by uberbrady** [comment]
Right, so you're saying everything basically works - (specifically, try and check out the "model-level custom field default values" feature which uses Livewire). But you're still getting that 404.

I did recently change some stuff so that we 'publish' the Livewire JS files, but that could possibly mess up subdirectory access. I'll try and check it out.

**Comment by uberbrady** [comment]
I don't know how technical you are but I'm wondering if this would help - https://laravel-livewire.com/docs/2.x/installation#configuring-the-asset-base-url

Specifically, try this:
 - take a backup! Just in case we mess something up.
 - Run `php artisan livewire:publish --config` - which should create a `config/livewire.php` file.
 - Edit the `asset_url` in that config file to match up with what you're expecting. (Maybe: `/inventory` ?)
 
If that works and the 404 goes away, then this might be something that we have to build in to the app (I'm far more inclined to pull this configuration data from the `APP_URL` rather than make a user enter it twice, but, we'll see).

<blockquote><img src="https://laravel-livewire.com/img/twitter.png" width="48" align="right"><div><img src="/favicon.ico" height="14"> Laravel</div><div><strong><a href="https://laravel-livewire.com/docs/2.x/installation">Installation | Laravel</a></strong></div><div>A full-stack framework for Laravel that takes the pain out of building dynamic UIs.</div></blockquote>

**Comment by bobeagan** [comment]
That did appear to solve the 404 issue. Network tab confirms the request is serving properly as a 200 now.

**Comment by snipe** [comment]
@uberbrady Users should not be publishing their own vendor files tho, no?

This seems like something we should have included in https://github.com/snipe/snipe-it/tree/master/config, replacing things as needed. 

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe-it/config at master · snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe-it/config at master · snipe/snipe-it</div></blockquote>

**Comment by snipe** [comment]
@bobeagan thanks for confirming the fix. Can you show me what your config looks like? We'll publish these as part of core shortly.

**Comment by bobeagan** [comment]
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Class Namespace
    |--------------------------------------------------------------------------
    |
    | This value sets the root namespace for Livewire component classes in
    | your application. This value affects component auto-discovery and
    | any Livewire file helper commands, like `artisan make:livewire`.
    |
    | After changing this item, run: `php artisan livewire:discover`.
    |
    */

    'class_namespace' => 'App\\Http\\Livewire',

    /*
    |--------------------------------------------------------------------------
    | View Path
    |--------------------------------------------------------------------------
    |
    | This value sets the path for Livewire component views. This affects
    | file manipulation helper commands like `artisan make:livewire`.
    |
    */

    'view_path' => resource_path('views/livewire'),

    /*
    |--------------------------------------------------------------------------
    | Layout
    |--------------------------------------------------------------------------
    | The default layout view that will be used when rendering a component via
    | Route::get('/some-endpoint', SomeComponent::class);. In this case the
    | the view returned by SomeComponent will be wrapped in "layouts.app"
    |
    */

    'layout' => 'layouts.app',

    /*
    |--------------------------------------------------------------------------
    | Livewire Assets URL
    |--------------------------------------------------------------------------
    |
    | This value sets the path to Livewire JavaScript assets, for cases where
    | your app's domain root is not the correct path. By default, Livewire
    | will load its JavaScript assets from the app's "relative root".
    |
    | Examples: "/assets", "myurl.com/app".
    |
    */

    'asset_url' => '/inventory',

    /*
    |--------------------------------------------------------------------------
    | Livewire App URL
    |--------------------------------------------------------------------------
    |
    | This value should be used if livewire assets are served from CDN.
    | Livewire will communicate with an app through this url.
    |
    | Examples: "https://my-app.com", "myurl.com/app".
    |
    */

    'app_url' => null,

    /*
    |--------------------------------------------------------------------------
    | Livewire Endpoint Middleware Group
    |--------------------------------------------------------------------------
    |
    | This value sets the middleware group that will be applied to the main
    | Livewire "message" endpoint (the endpoint that gets hit everytime
    | a Livewire component updates). It is set to "web" by default.
    |
    */

    'middleware_group' => 'web',

    /*
    |--------------------------------------------------------------------------
    | Livewire Temporary File Uploads Endpoint Configuration
    |--------------------------------------------------------------------------
    |
    | Livewire handles file uploads by storing uploads in a temporary directory
    | before the file is validated and stored permanently. All file uploads
    | are directed to a global endpoint for temporary storage. The config
    | items below are used for customizing the way the endpoint works.
    |
    */

    'temporary_file_upload' => [
        'disk' => null,        // Example: 'local', 's3'              Default: 'default'
        'rules' => null,       // Example: ['file', 'mimes:png,jpg']  Default: ['required', 'file', 'max:12288'] (12MB)
        'directory' => null,   // Example: 'tmp'                      Default  'livewire-tmp'
        'middleware' => null,  // Example: 'throttle:5,1'             Default: 'throttle:60,1'
        'preview_mimes' => [   // Supported file types for temporary pre-signed file URLs.
            'png', 'gif', 'bmp', 'svg', 'wav', 'mp4',
            'mov', 'avi', 'wmv', 'mp3', 'm4a',
            'jpg', 'jpeg', 'mpga', 'webp', 'wma',
        ],
        'max_upload_time' => 5, // Max duration (in minutes) before an upload gets invalidated.
    ],

    /*
    |--------------------------------------------------------------------------
    | Manifest File Path
    |--------------------------------------------------------------------------
    |
    | This value sets the path to the Livewire manifest file.
    | The default should work for most cases (which is
    | "<app_root>/bootstrap/cache/livewire-components.php"), but for specific
    | cases like when hosting on Laravel Vapor, it could be set to a different value.
    |
    | Example: for Laravel Vapor, it would be "/tmp/storage/bootstrap/cache/livewire-components.php".
    |
    */

    'manifest_path' => null,

    /*
    |--------------------------------------------------------------------------
    | Back Button Cache
    |--------------------------------------------------------------------------
    |
    | This value determines whether the back button cache will be used on pages
    | that contain Livewire. By disabling back button cache, it ensures that
    | the back button shows the correct state of components, instead of
    | potentially stale, cached data.
    |
    | Setting it to "false" (default) will disable back button cache.
    |
    */

    'back_button_cache' => false,

    /*
    |--------------------------------------------------------------------------
    | Render On Redirect
    |--------------------------------------------------------------------------
    |
    | This value determines whether Livewire will render before it's redirected
    | or not. Setting it to "false" (default) will mean the render method is
    | skipped when redirecting. And "true" will mean the render method is
    | run before redirecting. Browsers bfcache can store a potentially
    | stale view if render is skipped on redirect.
    |
    */

    'render_on_redirect' => false,

];
```

**Comment by uberbrady** [comment]
I think I'd like to resolve the `asset_url` via a PHP `parse_url()` on the `APP_URL` and grabbing out the `path` part. I wouldn't want users to muck around in config files (ever), and I don't want them to have two environment variables to have to twiddle when there could be just one. But that's my take. Happy to discuss.

**Comment by snipe** [comment]
I think we should be able to just re-use the APP_URL var - same one we use in the app.php config

**Comment by snipe** [comment]
I’ll put up a PR :)

**Comment by snipe** [comment]
@uberbrady this is what I meant - https://github.com/snipe/snipe-it/pull/11202

**Comment by snipe** [comment]
Can anyone confirm whether or not this solved the issue?

**Comment by bobeagan** [comment]
Reverted my manual conrfig, cleared cache to confirm the console error returned, pulled latest master and cleared cache again, confirmed that the console error is gone. 👍

**Comment by snipe** [comment]
Awesome, thanks for the update :)
