### ISSUE TITLE
Restoring a backup is not possible.

### ISSUE THREAD

**Issue by Schnax** [grokability/snipe-it#11214]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Restoring a backup via webinterface (/admin/backups) fails. 
When trying to resore a backup (i have made 13 Backups) it fails with the error

`Error
Undefined constant 'STDIN'
http://192.168.98.21/admin/backups/restore/snipe-it-2022-05-16-14-30-51.zip`

no backup can be resored. but i can create backups.

### Reproduction steps

1. My installation is pretty fresh.
2. create a backup
3. try to restore it
4. every backup fails with the error 

### Expected behavior

the backup should be easily restored with no error. 

### Screenshots

![image](https://user-images.githubusercontent.com/32633892/170668979-f348d028-1445-47c4-bfc6-9f363314486b.png)

### Snipe-IT Version

v6.0.0 build 6860 (g722e88a47)

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Edge (Chromium)

### Version

101.0.1210.47

### Error messages

```shell
https://flareapp.io/share/W7zVRMp7#F19
```

### Additional context

manual and fresh install.

Thanks for any help :)

**Comment by xxgohxx** [comment]
I faced the same issue also. My version is v6.0.1 - build 7750

**Comment by snipe** [comment]
IIRC this was fixed already on master.

**Comment by Schnax** [comment]
Yeah, it is fixed but your awnser did not really helped me.

**Comment by snipe** [comment]
> Yeah, it is fixed but your awnser did not really helped me.

Not exactly sure what you were looking for. It was an issue in some environments, we updated the code to work better on more systems.

**Comment by Schnax** [comment]
Tanks for your help
