### ISSUE TITLE
Symfony\Component\HttpFoundation\Request::create() must be of the type string

### ISSUE THREAD

**Issue by benetaptech** [grokability/snipe-it#11213]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In Request.php line 334:
                                                                                                                                       
  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, called in 
  vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32 

### Reproduction steps

1.composer install
2. composer update
3.php artisan key:generate

### Expected behavior

![图片](https://user-images.githubusercontent.com/45444301/170608746-5d8d636a-6734-4dd0-83a1-1253e02f7c63.png)

### Snipe-IT Version

master 6

### Operating System

Centos7.9

### Web Server

apache

### PHP Version

PHP 7.4.29

**Comment by mountnco** [comment]
I am also receiving this error in a fresh build. It appears at the end of the composer install and when trying to generate 

`In Request.php line 334:
                                                                                                                       
  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, cal  
  led in C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\SetRequestForConsole.php on  
   line 32                                                                                                             
                                                                                                                       

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

`php artisan key:generate --force 

In Request.php line 334:
                                                                                                                       
  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given, cal  
  led in C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\SetRequestForConsole.php on  
   line 32                `

**Comment by SourSpoon** [comment]
I had this issue, but have managed to resolve it.

Complete your .env file and ensure that it is saved. APP_URL in particular.

EDIT:

Looks like its covered in https://github.com/snipe/snipe-it/issues/10839 as well

**Comment by snipe** [comment]
IIRC, you have to upgrade to composer 2.

**Comment by benetaptech** [comment]
OK, Thanks

**Comment by metacraft-hq** [comment]
APP_URL=http://localhost:8000 
Solves the error.

**Comment by mountnco** [comment]
> APP_URL=http://localhost:8000 Solves the error.

Setting app URL worked for me. Thanks.

**Comment by jsy-lkt** [comment]
![image](https://user-images.githubusercontent.com/130950463/232412744-d873ff4e-aa99-47cd-8b16-4f031c0a5c2b.png)

**Comment by jsy-lkt** [comment]
Why is this

**Comment by mdshamsfiroz** [comment]
> I had this issue, but have managed to resolve it.
> 
> Complete your .env file and ensure that it is saved. APP_URL in particular.
> 
> EDIT:
> 
> Looks like its covered in #10839 as well
Thanks It Works
