### ISSUE TITLE
HTTP Error 500 after Upgrade with command php upgrade.php

### ISSUE THREAD

**Issue by 2022michael** [grokability/snipe-it#11229]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, 

I used the command php upgrade.php to upgrade snipe-it. Now i receive an HTTP Error 500 if i opening the website. I habe no idea how to solve it.

Install log:
Skipping user check as it is not supported on Windows or Posix is not installed on this server. 
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER! 
--------------------------------------------------------

This script will attempt to: 

- validate some very basic .env file settings 
- check your PHP version and extension requirements 
- check directory permissions 
- do a git pull to bring you to the latest version 
- run composer install to get your vendors up to date 
- run migrations to get your schema up to date 
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking .env file: 
- Your .env is located at C:\inetpub\wwwroot\snipe-it/.env 
--------------------------------------------------------

√ Your APP_KEY is not blank. 
√ Your APP_URL is not null or blank. It is set to https://EU1RAPW270.ad.eu.rf-group.org
√ Your APP_URL is set to https://EU1RAPW270.ad.eu.rf-group.org and starts with the protocol (https:// or http://)
√ Your APP_URL (https://EU1RAPW270.ad.eu.rf-group.org) does not have a trailing slash.

--------------------------------------------------------
STEP 2: Checking PHP requirements: 
--------------------------------------------------------

Current PHP version: (8.0.19) is at least 7.4.0 - continuing... 
FYI: The php.ini used by this PHP is: C:\PHP\php.ini

Checking Required PHP extensions... 

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ sodium is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 3: Checking directory permissions: 
--------------------------------------------------------

√ C:\inetpub\wwwroot\snipe-it/bootstrap/cache is writable 
√ C:\inetpub\wwwroot\snipe-it/storage is writable 
√ C:\inetpub\wwwroot\snipe-it/storage/logs is writable 
√ C:\inetpub\wwwroot\snipe-it/storage/logs/laravel.log is writable 
√ C:\inetpub\wwwroot\snipe-it/storage/framework is writable 
√ C:\inetpub\wwwroot\snipe-it/storage/framework/cache is writable 
√ C:\inetpub\wwwroot\snipe-it/storage/framework/sessions is writable 
√ C:\inetpub\wwwroot\snipe-it/storage/framework/views is writable 
√ C:\inetpub\wwwroot\snipe-it/storage/app is writable 
√ C:\inetpub\wwwroot\snipe-it/storage/app/backups is writable 
√ C:\inetpub\wwwroot\snipe-it/storage/app/backup-temp is writable 
√ C:\inetpub\wwwroot\snipe-it/storage/private_uploads is writable 
√ C:\inetpub\wwwroot\snipe-it/public/uploads is writable 

--------------------------------------------------------
STEP 4: Backing up database: 
--------------------------------------------------------

-- 

--------------------------------------------------------
STEP 5: Putting application into maintenance mode: 
--------------------------------------------------------

-- 
--------------------------------------------------------
STEP 6: Pulling latest from Git (master branch): 
--------------------------------------------------------

Git is installed. 
-- No local changes to save
-- Your branch is up to date with 'origin/master'.
-- Already up to date.

--------------------------------------------------------
STEP 7: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ No bootstrap/cache/services.php, so nothing to delete.
√ No bootstrap/cache/config.php, so nothing to delete.
√ No vendor/symfony/translation/TranslatorInterface.php, so nothing to delete.

-- -- -- -- 
--------------------------------------------------------
STEP 8: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- Running the app in production mode.
-- We couldn't find a local composer.phar. No worries, trying globally.
Since you are running composer globally, we won't try to update it for you.
If you run into issues with this step, try running `composer self-update` 
before running this updater again

Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run ".\vendor\bin\upgrade-carbon" to get help in updating carbon and other frameworks and libraries that depend on it.

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge(javiereguiluz/easyslugger: Array)
#1 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array('array_merge', Array)
#2 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages(Object(Composer\DependencyResolver\Pool), Array, Array, 'javiereguiluz/e...')
#3 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php(742): Composer\DependencyResolver\Solver->selectAndInstall(1, Array, Array, Object(Composer\DependencyResolver\GenericRule))
#4 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat(Array)
#5 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php(475): Composer\DependencyResolver\Solver->solve(Object(Composer\DependencyResolver\Request), false)
#6 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php(229): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array)
#7 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#8 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php(258): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php(104): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer(61): Composer\Console\Application->run()
#15 C:\ProgramData\ComposerSetup\bin\composer.phar(24): require('phar://C:/Progr...')
#16 {main}
  thrown in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php on line 84
--------------------------------------------------------
STEP 9: Migrating database:
--------------------------------------------------------

--------------------------------------------------------
STEP 10: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
STEP 11: Taking application out of maintenance mode:
--------------------------------------------------------

-- 
---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use 
your upgraded Snipe-IT!
--------------------------------------------------------

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Snipe-IT should work again.

### Snipe-IT Version

Old 4.7.6 / New

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.0.19

### Operating System

Windows

### Browser

Edge, Internet Explorer

**Comment by john159753** [comment]
Seeing something similar, this appears over and over in the laravel.log 

`[2022-06-01 11:49:53] production.ERROR: Uncaught ReflectionException: Class view does not exist in C:\inetpub\wwwroot\assetmanager\vendor\laravel\framework\src\Illuminate\Container\Container.php:803
Stack trace:
#0 C:\inetpub\wwwroot\assetmanager\vendor\laravel\framework\src\Illuminate\Container\Container.php(803): ReflectionClass->__construct('view')
#1 C:\inetpub\wwwroot\assetmanager\vendor\laravel\framework\src\Illuminate\Container\Container.php(681): Illuminate\Container\Container->build('view')
#2 C:\inetpub\wwwroot\assetmanager\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(785): Illuminate\Container\Container->resolve('view', Array, true)
#3 C:\inetpub\wwwroot\assetmanager\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Foundation\Application->resolve('view', Array)
#4 C:\inetpub\wwwroot\assetmanager\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(770): Illuminate\Container\Container->make('view', Array)
#5 C:\inetpub\wwwroot\assetmanager\vendor\laravel\framework\src\Ill {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught ReflectionException: Class view does not exist in C:\\inetpub\\wwwroot\\assetmanager\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:803
Stack trace:
#0 C:\\inetpub\\wwwroot\\assetmanager\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(803): ReflectionClass->__construct('view')
#1 C:\\inetpub\\wwwroot\\assetmanager\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(681): Illuminate\\Container\\Container->build('view')
#2 C:\\inetpub\\wwwroot\\assetmanager\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(785): Illuminate\\Container\\Container->resolve('view', Array, true)
#3 C:\\inetpub\\wwwroot\\assetmanager\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(629): Illuminate\\Foundation\\Application->resolve('view', Array)
#4 C:\\inetpub\\wwwroot\\assetmanager\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(770): Illuminate\\Container\\Container->make('view', Array)
#5 C:\\inetpub\\wwwroot\\assetmanager\\vendor\\laravel\\framework\\src\\Ill at C:\\inetpub\\wwwroot\\assetmanager\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:805)
[stacktrace]
#0 {main}
"} 
`

Still looking, will add anything i find.

**Comment by snipe** [comment]
@2022michael Sounds like you need to upgrade composer. Per your script output:

"Since you are running composer globally, we won't try to update it for you.
If you run into issues with this step, try running composer self-update
before running this updater again"

@john159753 I'd need to see the output of your upgrade script.

**Comment by john159753** [comment]
Hi @snipe!

I think you hit the nail on the head, I've ignored that warning for a few upgrades now and have avoided issue until now 😅

I ran the self-update, it went through and updated a lot, and now I'm back in business!

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
