### ISSUE TITLE
I can't create a New Model

### ISSUE THREAD

**Issue by robertojhd** [grokability/snipe-it#11223]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I click on New Model, I receive a 500 error 

### Reproduction steps

1.Click on Settings
2.Click on Asset Models
3.Click on New Model
...

### Expected behavior

It should show the new model form page.

### Screenshots

<img width="253" alt="Screenshot 2022-05-30 at 11 03 00" src="https://user-images.githubusercontent.com/106526706/170969848-f97fc1c3-7b44-47e4-8e02-63e33e691c55.png">
<img width="443" alt="Screenshot 2022-05-30 at 11 03 06" src="https://user-images.githubusercontent.com/106526706/170969883-523b501e-5ebe-4ee5-b53c-d309ee31e9ab.png">

### Snipe-IT Version

6.0.2 - build 7880

### Operating System

Ubuntu Server

### Web Server

Apache2

### PHP Version

8.1.2

### Operating System

macOS

### Browser

Safari and Firefox

### Version

Last on both

### Error messages

```shell
500
SERVER ERROR
```

**Comment by hdering** [comment]
Maybe this will help you? https://github.com/snipe/snipe-it/issues/11203#issuecomment-1141960864

Enable debug https://snipe-it.readme.io/docs/getting-help and check the logs.


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by Squidjigg** [comment]
@robertojhd see if the following works for you, it did for our instance
https://github.com/snipe/snipe-it/issues/11203#issuecomment-1144351568

**Comment by snipe** [comment]
Please always remember to include error logs, especially if you're seeing a 500 error. There is almost no way for us to figure out what might be wrong without stack traces from the logs. https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
