### ISSUE TITLE
 snipeit.sh screws up many things without warning htat its even going to do it.

### ISSUE THREAD

**Issue by davidbuzz** [grokability/snipe-it#11221]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

issues:   *no warnings*
1 - I didn't expect it to install a bunch of random php packages... it gave me php8 on a box that i was deliberately using php7.4 on.  
2 - It messed with the apache configuratino files, trying to make a vhost when i already had one.
3 - it tried to reset the root password on my myssql/maria instance. 
4 - it made changes to my .env file
5 - it created a /var/www/html folder, when i didn't want or need one.
6 - it made a 'snipeit' user without consent or notice.
7 - it pulled a randome versiion of composer from the internet when i already had a good,recent, working one in my path.
8- it created a 'snipeit' database when i alreadty had a database setup by a different name and screwed the permissinos of my existing one.
now i have to line-by-line figure out what it did and revert it all manually, this will take hrs.

### Reproduction steps

1. you've does a git pull from 6.0.1 to 6.0.2 and cleared all the caches and whatnot, and it still won't run, so u decide that ./install.sh  might be a good way to figure out what new dependancy it needs that you don't have.
2.  it fetches a massive snipeit.sh from the internet with no warning, and no error checking, and no checking of gthe existing state of the install , which just stomps all over your files on your computer.
3.
...

### Expected behavior

install.sh / snipeit.sh should NOT change *anything* without at least telling you that it's going to ignore everthing u already have setup, and make assumptions that its a vanilla VM  etc. 

### Snipe-IT Version

6.0.2

### Operating System

ubuntu

### Web Server

apache

### PHP Version

7.4

### Operating System

ubuntu

**Comment by snipe** [comment]
You're literally running a shell script as root - of course it's going to install "a bunch of random php packages". Those packages are required for Snipe-IT to run. 

This isn't a bug - this is working as designed. Don't use that method to install unless you're prepared for the consequences. We tell you [in the documentation](https://snipe-it.readme.io/docs/downloading#3-download-the-installer) that it should only be used on servers with nothing else running on them.

<img width="810" alt="Screen Shot 2022-06-06 at 9 47 14 AM" src="https://user-images.githubusercontent.com/197404/172207023-6b653f8a-e37b-4dde-b3bb-4a36ab57c7e6.png">

Next time try using the recommended method first.
