### ISSUE TITLE
LDAP users cannot login after upgrade from 5.1.7 to 6.0.2

### ISSUE THREAD

**Issue by MarkSchuurmansMansveld** [grokability/snipe-it#11239]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We are in the process of migrating our Snipe-IT to another machine. 
Installed RockyLinux, and after that Snipe-it.
Restored backup of production to test machine, replaced original .env inplace to ensure it works.

Login in with admin account works,
LDAP settings identical to production. 
Test LDAP sync button works
Test LDAP does not.
Error message
ldap_search(): Search: Bad search filter (for an admin user with guaranteed working credentials

Debug logging 👍 
![image](https://user-images.githubusercontent.com/38859535/171632018-4e73c5e1-9156-423d-ae0e-e8b4ec14ba81.png)

![image](https://user-images.githubusercontent.com/38859535/171632223-d8fecc4e-bf17-4097-8a39-366cf7c0e877.png)

One thing I noticed is that the option **Append domain name** is not available anymore in v6.0.2.
That option saved me in the past.
![image](https://user-images.githubusercontent.com/38859535/171632506-3ad6543b-e70f-4893-b6c3-f98d49524ea6.png)

### Reproduction steps

1.Install new/clean Snipe-it version
2.Keep .env file
3.Restore backup file from version 5.1.7 (from within user interface
4.Place original .env back
...

### Expected behavior

LDAP login for users was working in version 5.1.7
It is not working anymore in V6.0.2

### Snipe-IT Version

6.0.2

### Operating System

Rocky Linux 8.6

### Web Server

Apache

### PHP Version

8.1.6

### Operating System

windows

### Browser

chrome

### Version

102

### Error messages

```shell
[2022-06-02 14:36:37] production.DEBUG: Preparing to test LDAP connection
[2022-06-02 14:36:37] production.DEBUG: attempting to bind to LDAP for LDAP test
[2022-06-02 14:36:37] production.DEBUG: did the search run? I guess so if you got here!
[2022-06-02 14:36:37] production.DEBUG: okay, at least one more page to go!!!
[2022-06-02 14:36:37] production.DEBUG: Total count is: 10
[2022-06-02 14:36:46] production.DEBUG: Preparing to test LDAP login
[2022-06-02 14:36:46] production.DEBUG: Attempting to bind to LDAP for LDAP test
[2022-06-02 14:36:46] production.DEBUG: Filter query: ((uid=sAMAccountNamemark.schuurmans))
[2022-06-02 14:36:46] production.DEBUG: LDAP login failed
[2022-06-02 14:36:59] production.DEBUG: Preparing to test LDAP login
[2022-06-02 14:36:59] production.DEBUG: Attempting to bind to LDAP for LDAP test
[2022-06-02 14:36:59] production.DEBUG: Filter query: ((uid=sAMAccountNamemantest))
[2022-06-02 14:36:59] production.DEBUG: Status of binding user: mantest@xxxxxx to directory: (directly!) FAILURE
[2022-06-02 14:36:59] production.DEBUG: Status of binding Admin user: mantest@xxxxx to directory instead: FAILURE
[2022-06-02 14:37:08] production.DEBUG: Preparing to test LDAP login
[2022-06-02 14:37:08] production.DEBUG: Attempting to bind to LDAP for LDAP test
[2022-06-02 14:37:08] production.DEBUG: Filter query: ((uid=sAMAccountNamemantest))
[2022-06-02 14:37:08] production.DEBUG: Status of binding user: mantest@xxxxx to directory: (directly!) FAILURE
[2022-06-02 14:37:08] production.DEBUG: Status of binding Admin user: mantest@xxxxx to directory instead: FAILURE
[2022-06-02 14:37:43] production.DEBUG: Preparing to test LDAP login
[2022-06-02 14:37:43] production.DEBUG: Attempting to bind to LDAP for LDAP test
[2022-06-02 14:37:43] production.DEBUG: Filter query: ((uid=sAMAccountNamemantest))
[2022-06-02 14:37:43] production.DEBUG: Status of binding user: mantest@xxxxx to directory: (directly!) FAILURE
[2022-06-02 14:37:43] production.DEBUG: Status of binding Admin user: mantest@xxxxx to directory instead: FAILURE
[2022-06-02 14:41:03] production.DEBUG: Preparing to test LDAP login
[2022-06-02 14:41:03] production.DEBUG: Attempting to bind to LDAP for LDAP test
[2022-06-02 14:41:03] production.DEBUG: Filter query: ((uid=sAMAccountNamemark.schuurmans))
[2022-06-02 14:41:03] production.DEBUG: LDAP login failed
[2022-06-02 14:41:27] production.DEBUG: Preparing to test LDAP login
[2022-06-02 14:41:27] production.DEBUG: Attempting to bind to LDAP for LDAP test
[2022-06-02 14:41:27] production.DEBUG: Filter query: ((uid=sAMAccountNamemantest))
[2022-06-02 14:41:27] production.DEBUG: Status of binding user: mantest@xxxxx to directory: (directly!) FAILURE
[2022-06-02 14:41:27] production.DEBUG: Status of binding Admin user: mantest@xxxxx to directory instead: FAILURE
[2022-06-02 14:43:27] production.DEBUG: Preparing to test LDAP login
[2022-06-02 14:43:27] production.DEBUG: Attempting to bind to LDAP for LDAP test
[2022-06-02 14:43:27] production.DEBUG: Filter query: ((uid=sAMAccountNamemark.schuurmans))
[2022-06-02 14:43:27] production.DEBUG: Status of binding user: mark.schuurmans@xxxxx to directory: (directly!) FAILURE
[2022-06-02 14:43:27] production.DEBUG: Status of binding Admin user: mark.schuurmans@xxxxx to directory instead: FAILURE
[2022-06-02 14:43:41] production.DEBUG: Preparing to test LDAP login
[2022-06-02 14:43:42] production.DEBUG: Attempting to bind to LDAP for LDAP test
[2022-06-02 14:43:42] production.DEBUG: Filter query: ((uid=sAMAccountNamemark.schuurmans))
[2022-06-02 14:43:42] production.DEBUG: LDAP login failed

php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

fresh install, then restore of production
Installation method : git clone
no changes in database

**Comment by deuba-it** [comment]
Hello,
we have the same issue that the ldap users cant login after upgrade from 5.4.3
thx

**Comment by IvanROU** [comment]
Hello,
We have the same issue that the ldap users cant login after upgrade from 5.4.3 to 6.0.2.

The sync test goes well.

With filter (&(objectClass=person)) we get "bad filter" error

With filter &(objectClass=person) we get an error:
  "Login failed. username did not successfully bind to LDAP."

In laravel.log : 
[2022-06-03 12:28:31] production.DEBUG: Preparing to test LDAP login
[2022-06-03 12:28:31] production.DEBUG: Attempting to bind to LDAP for LDAP test
[2022-06-03 12:28:31] production.DEBUG: Filter query: (&(objectClass=person)(!(userAccountControl=514))(uid=username))
[2022-06-03 12:28:31] production.DEBUG: Status of binding user: username@domain.local to directory: (directly!) FAILURE
[2022-06-03 12:28:31] production.DEBUG: Status of binding Admin user: username@domain.local to directory instead: FAILURE

Everything worked fine before the update.

UPD: 
"Requête d'authentification LDAP: uid=" parameter has been changed 
"Requête d'authentification LDAP: samaccountname=" after that the sync and login worked.

**Comment by triple-HA** [comment]
Hi,
I have the same issue #11222 
Any soluthin fot that?

**Comment by lcmv** [comment]
@MarkSchuurmansMansveld : i change this field bellow and it is worked well now.
![Capture](https://user-images.githubusercontent.com/59467389/172124424-9a5a0d55-af6c-4c69-93cd-38322c306a72.PNG)

**Comment by deuba-it** [comment]
On our settings the "samaccountname=" was set before but didn´t work as well.
But what i am read over is that in the laravel logs, the ldap binding took the user domain suffix from the main setting "Email Domain".
Domain is domain.local in ldap bind was using domain.com for example, mabye it could help

**Comment by IvanROU** [comment]
> On our settings the "samaccountname=" was set before but didn´t work as well. But what i am read over is that in the laravel logs, the ldap binding took the user domain suffix from the main setting "Email Domain". Domain is domain.local in ldap bind was using domain.com for example, mabye it could help

I noticed that "SamAccountName" does not work for me, but "samaccountname" is quite functional.

**Comment by triple-HA** [comment]
I've create a new test user, sync that with Snipe-IT and test it with "samaccountname" but still... LDAP synchronization works but still user can't login in.
![screencapture-it-am-fraikingroup-admin-ldap-2022-06-06-13_27_43](https://user-images.githubusercontent.com/83789864/172153089-f0ea6e99-beda-49ae-aa7d-ad80d1171b20.png)

**Comment by MarkSchuurmansMansveld** [comment]
All suggestions above did not work for me.
The error messages are still the same.  ldap_search(): Search: Bad search filter

**Comment by Froschmedia** [comment]
@MarkSchuurmansMansveld 
Look at your logs, on the bind values something is wrong. uid=sAMAccountNamemark.schuurmans Login Name is direct After the User binding

**Comment by uberbrady** [comment]
Also, what's your LDAP Filter set to? Those are parsed a little more strictly now. Specifically, `(` and `)` at the beginning and end might mess things up. I'm hoping to push a fix that will ignore those soon, but for now that may help.

**Comment by MarkSchuurmansMansveld** [comment]
This does make some sensev as the logs give double (.

LDAP Filter is empty. If I change it to the suggested value but without (, the LDAP test does not work anymore.
If I fill in the suggested value (which would seem to me be the default), IT WORKS (for now).
Here is the setup which seems to work
![image](https://user-images.githubusercontent.com/38859535/172307015-ef1958b4-1477-4a7e-8ff2-9b617a5f70c7.png)

Note the the LDAP filter is actually filled in, instead of snipeit displaying the default value.
Some more testing is necessary. Will keep you updated.

**Comment by MrHackino** [comment]
Same issue after update and cookie expiration. My instance is locked. Is it possible to drop a patch soon please?
I use Linuxserver.io container and cannot access php artisan to create a local account.
For the conf I'm using a LDAP server
My LDAP Filter is objectclass=inetorgperson

**Comment by MarkSchuurmansMansveld** [comment]
> This does make some sensev as the logs give double (.
> 
> LDAP Filter is empty. If I change it to the suggested value but without (, the LDAP test does not work anymore. If I fill in the suggested value (which would seem to me be the default), IT WORKS (for now). Here is the setup which seems to work ![image](https://user-images.githubusercontent.com/38859535/172307015-ef1958b4-1477-4a7e-8ff2-9b617a5f70c7.png)
> 
> Note the the LDAP filter is actually filled in, instead of snipeit displaying the default value. Some more testing is necessary. Will keep you updated.

This fix is working for me. I have no further issues with the 6.0.2.
Thanks for all the support.

**Comment by MrHackino** [comment]
Is it possible to reset a user password from DB to connect again? If yes, could someone provide me with the SQL request please?

**Comment by snipe** [comment]
> Is it possible to reset a user password from DB to connect again? If yes, could someone provide me with the SQL request please?

Passwords are hashed in the database, so there wouldn't be a way to retrieve or reset a user's password via SQL. If you cannot reset their password because they are managed via LDAP, you should be able to change that in the user edit options (at least under bulk edit)

<img width="811" alt="Screen Shot 2022-06-08 at 4 36 25 AM" src="https://user-images.githubusercontent.com/197404/172607117-458aa831-bb03-4c8e-9dab-d6b7d5601042.png">

**Comment by MrHackino** [comment]
> > Is it possible to reset a user password from DB to connect again? If yes, could someone provide me with the SQL request please?
> 
> Passwords are hashed in the database, so there wouldn't be a way to retrieve or reset a user's password via SQL. If you cannot reset their password because they are managed via LDAP, you should be able to change that in the user edit options (at least under bulk edit)
> 
> <img alt="Screen Shot 2022-06-08 at 4 36 25 AM" width="811" src="https://user-images.githubusercontent.com/197404/172607117-458aa831-bb03-4c8e-9dab-d6b7d5601042.png">

Thank you for your reply sadly I cannot access anymore to my interface, I'm locked outside of the WUI.

**Comment by snipe** [comment]
@m-menant I believe this is just a configuration issue not something requiring a patch. If you're locked out, you can use the rescue utility to create a new admin so you can reconfigure your LDAP settings: https://snipe-it.readme.io/docs/create-an-admin

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/create-an-admin">Create an Admin</a></strong></div><div>Since v3.0, we've added the rescue utility to add an admin user via the command line. This can be helpful if you've managed to lock yourself out of your installation (for example if you can't remember your password and never set the system up to send email.) So for example, if you wanted to add a ne...</div></blockquote>

**Comment by MrHackino** [comment]
> @m-menant I believe this is just a configuration issue not something requiring a patch. If you're locked out, you can use the rescue utility to create a new admin so you can reconfigure your LDAP settings: https://snipe-it.readme.io/docs/create-an-admin
> 
> > <img alt="" width="48" src="/favicon.ico">Snipe-IT Documentation**[Create an Admin](https://snipe-it.readme.io/docs/create-an-admin)**Since v3.0, we've added the rescue utility to add an admin user via the command line. This can be helpful if you've managed to lock yourself out of your installation (for example if you can't remember your password and never set the system up to send email.) So for example, if you wanted to add a ne...

Second case I'm facing, I'm using your solution but packaged by linuxserver.io and when I try to invoke php artisan it doesn't work. I might better try to restore it from backup. It was working fine before v6.0. This is an extract of my LDAP configuration for debugging purposes.

```
LDAP Filter: objectclass=inetorgperson
Username field: uid
Last name: sn
LDAP First Name: givenname
LDAP Authentification query: uid=
```
I also have an error message like specified in this issue from laravel.log

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/create-an-admin">Create an Admin</a></strong></div><div>Since v3.0, we've added the rescue utility to add an admin user via the command line. This can be helpful if you've managed to lock yourself out of your installation (for example if you can't remember your password and never set the system up to send email.) So for example, if you wanted to add a ne...</div></blockquote>

**Comment by JonWVBFL** [comment]
For my setup, I had to correct 2 of the LDAP fields.

LDAP Authentication query
OLD was  `uid=samaccountname`
NEW is now `sAMAccountname=`

Then my LDAP Filter
OLD was `(memberOf=CN=....(etc)`
NEW is now `&(memberOf=CN=....(etc)`

With these two tweaks LDAP authentication worked again

**Comment by snipe** [comment]
That's always been documented tho...
https://snipe-it.readme.io/docs/ldap-sync-login

<img width="793" alt="Screen Shot 2022-06-09 at 1 03 36 PM" src="https://user-images.githubusercontent.com/197404/172934412-1ab108b3-d3bb-4acd-b1d9-17cfb431b78d.png">


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/ldap-sync-login">LDAP Sync & Login</a></strong></div><div>For example, if your manually created or CSV imported usernames look like jane.smith (with an email value of jane.smith@yourdomain.com), you should confirm that the directory service you're syncing to uses jane.smith as a username value, OR update the usernames of your users to be consistent with wh...</div></blockquote>

(Thank you for providing an update!)

**Comment by SonGokussj4** [comment]
> For my setup, I had to correct 2 of the LDAP fields.
> 
> LDAP Authentication query OLD was `uid=samaccountname` NEW is now `sAMAccountname=`
> 
> Then my LDAP Filter OLD was `(memberOf=CN=....(etc)` NEW is now `&(memberOf=CN=....(etc)`
> 
> With these two tweaks LDAP authentication worked again

Resolved for me by changing `LDAP Authentication query`
from: `uid=samaccountname`
to: `sAMAccountname=`

Thank you!
