### ISSUE TITLE
Custom field textbox, numeric does not get validated when adding default values on the model

### ISSUE THREAD

**Issue by derdeagle** [grokability/snipe-it#11230]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I created a new custom field with Form Element "TextBox" and Format "NUMERIC" and added it to a field set. This fieldset is set on a device model. If the checkbox "Add default values" is checked and a default value of this numeric field of "asdf" is set it will save without an error being shown.

### Reproduction steps

1. create custom field with Form Element "TextBox" and Format "NUMERIC"
2. add created custom field to a field set
3. set field set on a model
4. check checkbox "Add default values"
5. define default value of "asdf" (something non-numerical)
6. save model

### Expected behavior

I expect an error to be shown, i.e. the field to be validated according to the settings of the custom field.

### Snipe-IT Version

6.0.2

### Operating System

Docker image (Ubuntu 20.04.4 LTS)

### Web Server

Apache2 2.4.41

### PHP Version

7.4.3

### Operating System

Arch

### Browser

Brave

### Version

1.39.111

**Comment by inietov** [comment]
This got somehow left alive. Closing!
