### ISSUE TITLE
skewed layout on create depreciation

### ISSUE THREAD

**Issue by veenone** [grokability/snipe-it#11232]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

in create depreciation view, the layout is skewed and not properly set.
the position minimum value for depreciation input is not aligned.
additionally footer (with save button) also not properly set

### Reproduction steps

1. go to settings
2. select depreciation
3. select new depreciation
...

### Expected behavior

layout configured as other create pages

### Screenshots

![create_depreciation](https://user-images.githubusercontent.com/3839381/171465796-d9c1707a-dc88-46e0-bfad-f3fe62f73dd3.PNG)

### Snipe-IT Version

6.0.2

### Operating System

WIndows

### Web Server

Apache

### PHP Version

7.4.27

### Operating System

WIndows

### Browser

Chrome, Edge

**Comment by snipe** [comment]
Looks like that screenshot didn't upload properly - can you try again?

**Comment by snipe** [comment]
Never mind- I can reproduce on my end :)

**Comment by veenone** [comment]
I made the fix already and will make the PR :)

**Comment by snipe** [comment]
Ack, sorry - I didn't see your PR before I made my own :(
