### ISSUE TITLE
[Feature Request]: Address 2 in Locations column

### ISSUE THREAD

**Issue by SonGokussj4** [grokability/snipe-it#11255]
### Is your feature request related to a problem? Please describe.

Missing option from Column in Locations to show Address 2 field

### Describe the solution you'd like

I would like to turn on Address 2. There is only Address for now.

### Describe alternatives you've considered

Creating a custom field and showing that. But if I have data in Address 2, I would like to have it listed as a column in Locations list.

**Comment by snipe** [comment]
What screen are you looking for this in, exactly? Locations listing, assets, etc?

**Comment by SonGokussj4** [comment]
As I wrote: in Locations. `Settings -> Locations` 
You can see this in the [demo app](https://demo.snipeitapp.com/locations) too. If you press `columns` to select columns to display, `Address 2` is not there.

**Comment by snipe** [comment]
I don't need to look at the demo - I was asking what you specifically wanted. You said "Locations", which could refer to the locations fields in assets, accessories, etc. Gotta be specific to be terrific. 

That seems like a pretty straightforward request. I'm sure we can make that happen for you.
