### ISSUE TITLE
Cannot update to 6.0.2

### ISSUE THREAD

**Issue by patwia** [grokability/snipe-it#11266]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I cannot update Snipe-IT to newest version, I think it's because the permissions but all the permissions looks good.

Last time when I did it the same way it was working just fine...

I believe that I provided enough info to solve my issue.

### Reproduction steps

1. Login to server as admin
2. cd /var/www/snipe-it
3. sudo -u www-data php upgrade.php
4. something is happening but I have few errors with permisions

### Expected behavior

Normal update, just as I did it last time.

### Snipe-IT Version

v5.3.7 - build 6587 (master)

### Operating System

Ubuntu

### Web Server

Apache 2

### PHP Version

7.4.9

### Error messages

```shell
Git is installed.
error: cannot lock ref 'refs/remotes/origin/features/add_force_saml_to_master': Unable to create '/var/www/snipe-it/.git/refs/remotes/origin/features/add_force_saml_to_master.lock': Permission denied
From https://github.com/snipe/snipe-it

error: cannot lock ref 'refs/remotes/origin/features/more_normal_consumables_api': Unable to create '/var/www/snipe-it/.git/refs/remotes/origin/features/more_normal_consumables_api.lock': Permission denied
 ! [new branch]          features/more_normal_consumables_api -> origin/features/more_normal_consumables_api  (unable to update local ref)
error: cannot lock ref 'refs/remotes/origin/features/nicer_ui_for_groups': Unable to create '/var/www/snipe-it/.git/refs/remotes/origin/features/nicer_ui_for_groups.lock': Permission denied
 ! [new branch]          features/nicer_ui_for_groups -> origin/features/nicer_ui_for_groups  (unable to update local ref)
error: cannot lock ref 'refs/remotes/origin/features/suggest_updating_global_composer': Unable to create '/var/www/snipe-it/.git/refs/remotes/origin/features/suggest_updating_global_composer.lock': Permission denied
 ! [new branch]          features/suggest_updating_global_composer -> origin/features/suggest_updating_global_composer  (unable to update local ref)
error: cannot lock ref 'refs/remotes/origin/fixes/add_additional_curreny_formats_and_split_api_results': Unable to create '/var/www/snipe-it/.git/refs/remotes/origin/fixes/add_additional_curreny_formats_and_split_api_results.lock': Permission denied
 ! [new branch]          fixes/add_additional_curreny_formats_and_split_api_results -> origin/fixes/add_additional_curreny_formats_and_split_api_results  (unable to update local ref)
error: cannot lock ref 'refs/remotes/origin/fixes/added_gitkeep_to_eula_pdfs': Unable to create '/var/www/snipe-it/.git/refs/remotes/origin/fixes/added_gitkeep_to_eula_pdfs.lock': Permission denied
```

### Additional context

And here's output of ls -la in /var/www/snipe-it
xxxx@xxxx:/var/www/snipe-it$ ls -la
total 1756
drwxrwxr-x 18 www-data www-data   4096 Jun  7 08:22 .
drwxr-xr-x  4 root     root       4096 Aug  3  2021 ..
-rw-rw-r--  1 www-data www-data  68136 Jun  7 08:22 .all-contributorsrc
drwxrwxr-x  4 www-data www-data   4096 Aug  3  2021 ansible
drwxrwxr-x 18 www-data www-data   4096 Aug  3  2021 app
-rw-rw-r--  1 www-data www-data   5764 Jun  7 08:22 app.json
-rw-rw-r--  1 www-data www-data   1646 Jun  7 08:22 artisan
drwxrwxr-x  3 www-data www-data   4096 Jun  7 08:22 bootstrap
-rw-rw-r--  1 www-data www-data   9210 Jun  7 08:22 c3.php
-rw-rw-r--  1 www-data www-data    373 Jun  7 08:22 codeception.yml
-rw-rw-r--  1 www-data www-data   3228 Jun  7 08:22 CODE_OF_CONDUCT.md
-rw-rw-r--  1 www-data www-data   3261 Jun  7 08:22 composer.json
-rw-rw-r--  1 www-data www-data 427795 Jun  7 08:22 composer.lock
drwxrwxr-x  2 www-data www-data   4096 Jun  7 08:22 config
-rw-rw-r--  1 www-data www-data      0 Jun  7 08:22 _config.yml
-rw-rw-r--  1 www-data www-data    317 Jun  7 08:22 CONTRIBUTING.md
-rw-rw-r--  1 www-data www-data    214 Jun  7 08:22 crowdin.yml
drwxrwxr-x  5 www-data www-data   4096 Jun  7 08:22 database
drwxrwxr-x  2 www-data www-data   4096 Jun  7 08:22 docker
-rw-rw-r--  1 www-data www-data    707 Jun  7 08:22 docker-compose.yml
-rw-rw-r--  1 www-data www-data   4312 Jun  7 08:22 Dockerfile
-rw-rw-r--  1 www-data www-data   2490 Jun  7 08:22 Dockerfile.alpine
-rw-rw-r--  1 www-data www-data   3602 Jun  7 08:22 Dockerfile.fpm-alpine
-rw-rw-r--  1 www-data www-data    156 Jun  7 08:22 .dockerignore
-rwxrwxr-x  1 www-data www-data   4161 Oct 14  2021 .env
-rw-rw-r--  1 www-data www-data   4367 Jun  7 08:22 .env.docker
-rw-rw-r--  1 www-data www-data   4047 Jun  7 08:22 .env.example
-rw-rw-r--  1 www-data www-data   1889 Jun  7 08:22 .env.testing
-rw-rw-r--  1 www-data www-data   1819 Jun  7 08:22 .env.testing-ci
-rw-rw-r--  1 www-data www-data    536 Jun  7 08:22 .env.tests
-rw-rw-r--  1 www-data www-data    491 Jun  7 08:22 .env.unit-tests
drwxrwxr-x  8 www-data www-data   4096 Jun  7 08:33 .git
-rwxrwxr-x  1 www-data www-data     53 Aug  3  2021 .gitattributes
drwxrwxr-x  4 www-data www-data   4096 Jun  7 08:22 .github
-rwxrwxr-x  1 www-data www-data   1266 Oct  5  2021 .gitignore
drwxrwxr-x  2 www-data www-data   4096 Jun  7 08:22 heroku
-rw-rw-r--  1 www-data www-data    446 Jun  7 08:22 .htaccess
-rw-rw-r--  1 www-data www-data    956 Jun  7 08:22 index.html
-rwxrwxr-x  1 www-data www-data    371 Aug  3  2021 install.sh
-rwxrwxr-x  1 www-data www-data  34519 Aug  3  2021 LICENSE
-rw-rw-r--  1 www-data www-data      9 Jun  7 08:22 .nvmrc
-rw-rw-r--  1 www-data www-data   1996 Jun  7 08:22 package.json
-rw-rw-r--  1 www-data www-data 901534 Jun  7 08:22 package-lock.json
-rw-rw-r--  1 www-data www-data   2376 Jun  7 08:22 phpmd.xml
-rw-rw-r--  1 www-data www-data   1097 Jun  7 08:22 phpunit.xml
-rw-rw-r--  1 www-data www-data     57 Jun  7 08:22 Procfile
drwxrwxr-x  6 www-data www-data   4096 Jun  7 08:22 public
-rw-rw-r--  1 www-data www-data  67754 Jun  7 08:22 README.md
drwxrwxr-x  6 www-data www-data   4096 Aug  3  2021 resources
drwxrwxr-x  3 www-data www-data   4096 Jun  7 08:22 routes
drwxrwxr-x  2 www-data www-data   4096 Jun  7 08:22 sample_csvs
-rw-rw-r--  1 www-data www-data   1083 Jun  7 08:22 SECURITY.md
-rw-rw-r--  1 www-data www-data    567 Jun  7 08:22 server.php
-rwxrwxr-x  1 www-data www-data  26289 Dec 21 11:52 snipeit.sh
drwxr-xr-x  7 www-data www-data   4096 Aug  3  2021 storage
drwxrwxr-x 10 www-data www-data   4096 Jun  7 08:22 tests
-rw-rw-r--  1 www-data www-data   9657 Jun  7 08:22 upgrade.php
-rw-rw-r--  1 www-data www-data   4586 Jun  7 08:22 Vagrantfile
drwxrwxr-x 66 www-data www-data   4096 Aug  3  2021 vendor
-rw-rw-r--  1 www-data www-data   7565 Jun  7 08:22 webpack.mix.js

**Comment by snipe** [comment]
Those errors definitely look like permissions issues, but it looks related to your `.git` directory, not the individual Snipe-IT files/folders.

**Comment by patwia** [comment]
So, what do You suggest? As You can see my www-data user has 775 permissions to .git. Honestly I don't know what's going on.

**Comment by snipe** [comment]
> drwxrwxr-x 8 www-data www-data 4096 Jun 7 08:33 .git

Are you running the upgrader as `www-data`, or some other user that may not have write permissions to that directory?

**Comment by patwia** [comment]
I am running upgrader as www-data in root Snipe-IT folder using sudo -u www-data php upgrade.php in /var/www/snipe-it so it should work. Last time I had no problems.

**Comment by snipe** [comment]
I'd check and see if you have SELinux installed. https://snipe-it.readme.io/docs/linuxosx#notes-on-selinux

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/linuxosx#notes-on-selinux">Linux/OSX</a></strong></div><div>Setting up a web server can sound daunting for folks who don't normally do that kind of thing. This guide will help you walk through the configuration for Apache or Nginx on Linux and OSX. The most common setup for Snipe-IT on a linux server is to use Apache, so if you're not sure what to pick, Apac...</div></blockquote>

**Comment by patwia** [comment]
Hi @snipe , my Snipe-IT is running on Ubuntu 20.10 with no SELinux. Honestly I didn't have time to investigate it further, but I saw another issue raised with the same problem. I will check that issue and see if something's gonna help me.

**Comment by patwia** [comment]
Hi, following this issue https://github.com/snipe/snipe-it/issues/11385 (upgrading composer and creating token on GH) I have managed to update to 6.0.5 but there are still some errors:

   ErrorException

  file_put_contents(/var/www/snipe-it/public/vendor/livewire/livewire.js): failed to open stream: Permission denied

  at vendor/league/flysystem/src/Adapter/Local.php:199
    195▕      */
    196▕     public function update($path, $contents, Config $config)
    197▕     {
    198▕         $location = $this->applyPathPrefix($path);
  ➜ 199▕         $size = file_put_contents($location, $contents, $this->writeFlags);
    200▕
    201▕         if ($size === false) {
    202▕             return false;
    203▕         }

      +21 vendor frames
  22  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

Permissions for /public:
drwxrwxr-x  7 www-data www-data    4096 Jun 28 19:29 public

Of course I was running upgrader as www-data

What should I do about it? Website seems to work fine.

**Comment by snipe** [comment]
If permission is denied, it's a permissions issue. Make sure the `public/vendor/livewire` exists and is writable.

**Comment by patwia** [comment]
Hi,

So, public/vendor/livewire was owned by root, I have changed the ownership to www-data and re-run upgrader.

Everything seems to be fine now, no errors output during upgrade, version 6.0.5.

Thanks for your time and help, I think we can close the issue.

**Comment by snipe** [comment]
Glad you're sorted :)
