### ISSUE TITLE
Icons for encrypted fields are missing

### ISSUE THREAD

**Issue by FritzBlaskowsky** [grokability/snipe-it#11267]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Icons for encrypted fields are missing in asset table header.

### Reproduction steps

1. Add encrypted field to asset

### Expected behavior

The icons in the table header should be displayed.

### Screenshots

Chrome:
![Chrome](https://user-images.githubusercontent.com/27015666/172343479-9966f24a-f59f-4252-8c25-965d62b94367.png)

Firefox:
![Firefox](https://user-images.githubusercontent.com/27015666/172343504-9d73acce-8a3c-4749-b94b-522024bdceb4.png)

### Snipe-IT Version

 v6.0.2 build 7880

### Operating System

Docker

### Web Server

Docker

### PHP Version

7.4.3 

### Additional context

Same behavior in web demo

**Comment by snipe** [comment]
Can you reproduce this on the demo?

**Comment by FritzBlaskowsky** [comment]
Yes, it's the same on the demo.

**Comment by snipe** [comment]
I'm not seeing that on the demo.

<img width="1570" alt="Screen Shot 2022-06-08 at 4 43 44 AM" src="https://user-images.githubusercontent.com/197404/172608237-0dc8cedd-9e2b-40d3-a9cf-ed98c656bc61.png">

**Comment by FritzBlaskowsky** [comment]
Strange. This is how it looks for me on the demo:

![demo](https://user-images.githubusercontent.com/27015666/172619294-daf00a3e-4c03-43a4-aff7-f43cf52dd5cb.png)

**Comment by snipe** [comment]
What browser are you using? You omitted that field in your initial bug report.

**Comment by snipe** [comment]
(Also are there any errors in your browser console?)

**Comment by FritzBlaskowsky** [comment]
I tried Chrome 102 and Firefox 101. The behavior is a bit different between Chrome and Firefox. You can see that on the screenshots I initially attached.

**Comment by FritzBlaskowsky** [comment]
The browser console (Firefox) shows two warnings:

![console](https://user-images.githubusercontent.com/27015666/172621972-0243bfcf-5c90-4485-b3a1-c1da0108f989.png)

**Comment by snipe** [comment]
Hm, I am able to reproduce this in Chrome, but not sure what's happening here. We do handle the icons differently in the table headers than we do elsewhere - and they do seem to be loading on the asset detail page 

<img width="811" alt="Screen Shot 2022-06-08 at 6 04 48 AM" src="https://user-images.githubusercontent.com/197404/172623702-e79152f6-19b2-4095-a060-6731613b58d1.png">

@Godmartinz can you peep this when you get a moment? We handle those table headers in the asset presenter, and it calls back to some funky stuff in the less files.

**Comment by snipe** [comment]
I believe this has been fixed already now (in https://github.com/snipe/snipe-it/pull/11479). 

<img width="1486" alt="Screen Shot 2022-07-15 at 5 59 32 PM" src="https://user-images.githubusercontent.com/197404/179328145-840c9c32-559a-444c-bb4f-3b3f0bb819be.png">
