### ISSUE TITLE
Wrong user's surname and lastname after login.

### ISSUE THREAD

**Issue by schnudd31do3** [grokability/snipe-it#11268]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

On the login of the user, the user's surname and lastname is overwritten with the surname and lastname of a definite different user. After LDAP-syncing (via admin), all user's names are correct again.

### Reproduction steps

1. User login
2. Edit profile: Find wrong surename / lastname
3. Correct surename / lastname
4. Logout
5. User login: Wrong surename / lastname again

### Expected behavior

The surename / lastname must not change

### Snipe-IT Version

6.0.2

### Operating System

Debian

### Web Server

apache2

### PHP Version

7.4

**Comment by snipe** [comment]
If you have LDAP syncing on login, LDAP will always overwrite what's in the database.

**Comment by schnudd31do3** [comment]
When **I** loged-in, I have this view:
![image](https://user-images.githubusercontent.com/72391822/172470718-8b18b096-9924-4b12-80f2-2b257c01deca.png)
 **My name is NOT Michael XXXX**.

**EACH** user see the **same name "Michael XXX"** after login. As loged-in **EACH user expect to see HIS name**.

**Comment by snipe** [comment]
There's nothing in our system that would be changing that though. Where would we even be getting that information from? There must be something configured in your LDAP that is mapping to the wrong field.  Obviously the user should see their own name when they login, but Snipe-IT only knows what you tell it.

**Comment by schnudd31do3** [comment]
I can not agree because of my observations. First, after LDAP-Sync all is OK. As admin I can see the right assignment of user name to account.  During I am loged-in as admin I can observe that a user's account name is changing on his login to the name "Michael XXX". Therefore I think something goes wrong by displaying while the database is keeping consistent.

BTW. In one of the earlier versions this bug was not there.

**Comment by snipe** [comment]
If you grep through the code, there is no reference anywhere to the name Michael, so it's got to be coming from something within your directory. You can perhaps try clearing the app caches? `php artisan cache:clear; php artisan view:clear`.

**Comment by schnudd31do3** [comment]
I have this: "Could not open input file: artisan"

**Comment by snipe** [comment]
You have to run artisan commands from the base directory that Snipe-IT is installed from.

**Comment by schnudd31do3** [comment]
The commands worked, but I have still the same issue.

**Comment by schnudd31do3** [comment]
I beleve you "...there is no reference anywhere to the name Michael..."
"Michael XXX" is one of our employees. This information only can come from the database

**Comment by snipe** [comment]
When @uberbrady comes online, he may have more suggestions

**Comment by schnudd31do3** [comment]
![image](https://user-images.githubusercontent.com/72391822/172618304-57860790-0908-4013-902f-1e698d1de2a5.png)
Here you can see, yellow marked names are exchanged by SnipeIT on login. My feeling is, that the LDAP-information is correctly submitted, otherwise users couldn't login. After successfull log-in, SnipeIT replaces the name with a wrong one.

**Comment by snipe** [comment]
You can see where that login + user save happens here tho:

https://github.com/snipe/snipe-it/blob/8b6e8692150675618d04aa327b48b7b221250483/app/Http/Controllers/Auth/LoginController.php#L163-L206

It's using what LDAP is returning. 

Can you set your `LOG_LEVEL=debug` in your `.env` so we can maybe see more output?

**Comment by schnudd31do3** [comment]
Successfully LDAP sync:
![image](https://user-images.githubusercontent.com/72391822/172622697-be13b526-f9a3-4c5b-a064-67b85f7e2357.png)
![image](https://user-images.githubusercontent.com/72391822/172622799-1a56cc12-d450-4bc4-98cc-2f2f7c78be63.png)

**Comment by schnudd31do3** [comment]
I set "Can you set your LOG_LEVEL=debug in your .env so we can maybe see more output?" as requested. What would you like to see?

In the ".env.testing" I found "APP_LOG=single" and "APP_LOG_LEVEL=debug" and I also added them to the .env file

**Comment by schnudd31do3** [comment]
I mean, from the user's point of view, it is inexplicable that after logging in, a name other than his own appears. He can supposedly correct his name in his personal area, but after his next login he sees a wrong name again. Users think they are changing someone else's account instead of their own account. From a user's point of view, this is clearly wrong.

We have received many complaints from our users about this. So I'm asking you to acknowledge this as a bug and fix it. I am happy to support you with tests during the implementation.

**Comment by snipe** [comment]
@schnudd31do3 Of course, but that it's only happening to you folks makes it pretty difficult to debug. 

What's the out in your application log when you login and see this behavior?

**Comment by uberbrady** [comment]
Another question - what is your LDAP Filter setting set to? It strikes me that something might a little funny in there and might be allowing a looser match - even though the original LDAP Bind works and is quite a bit stricter.

**Comment by schnudd31do3** [comment]
LDAP configuration:
![image](https://user-images.githubusercontent.com/72391822/172994373-b7a01df0-d1db-4514-bce3-441668a5c158.png)
![image](https://user-images.githubusercontent.com/72391822/172994681-d7882704-0212-4f84-be32-371d566a21dd.png)
Empty fields are not displayed

**Comment by schnudd31do3** [comment]
Communicatio log of one user-login and then user-logoff in debug-mode
![image](https://user-images.githubusercontent.com/72391822/172995489-7f5cba73-3b5b-4341-858c-9bfa2444468d.png)

**Comment by schnudd31do3** [comment]
Today I made a sync-test with changed LDAP filter and reverted to its original value. After that a LDAP synchronisation failed and as user I  could not login. I had to restore the whole VM.

**Comment by schnudd31do3** [comment]
Hello uberbrady,

any hints for me?

**Comment by uberbrady** [comment]
You're doing an 'OR' query - that's the `|` symbol - so it's probably just grabbing the first user who matches - which must be Michael XXX.

You can maybe try changing your LDAP filter to `&(|(l=something1)(l=something2)(l=something3))` - presuming I balanced the parentheses right. Or, if you can try to pull off a branch, I should have a possible fix up shortly?

**Comment by schnudd31do3** [comment]
The 'OR' is OK because it selects accounts from our two company headquarters. A shortly fix is very welcome.

**Comment by schnudd31do3** [comment]
The 'OR' is because filtering for our two headquarters.

With the suggested paranthese:
![image](https://user-images.githubusercontent.com/72391822/173498672-53cc178b-e91b-4549-b4a9-76d69101dce6.png)
I got successfully LDAP-syncing but no user-login is possible:
![image](https://user-images.githubusercontent.com/72391822/173498767-55c7d5f0-475c-43cd-a0a8-c8b561ab5a52.png)

**Comment by schnudd31do3** [comment]
"Or, if you can try to pull off a branch, I should have a possible fix up shortly?" Im am inexperienced in doing that. Also, I'm not familiar with the SnipeIT code. Could you do it for me?

**Comment by uberbrady** [comment]
No, it'd have to be something you do yourself.

Glad you got the Sync going, now let's see if we can get Auth working.

For your LDAP Auth query, that should probably be `sAMAccountName=`

Give that a shot and see if you can get logins working?

**Comment by schnudd31do3** [comment]
To keep in mind, login was never unsuccessful, but the displaying of the user's name is wrong.

When following your hints for filtering "You can maybe try changing your LDAP filter to &(|(l=something1)(l=something2)(l=something3))", login was not longer possible. So I revert it back to our setting where login is succesful.

"For your LDAP Auth query, that should probably be sAMAccountName=" I changed it as suggested, but the user's name is still wrong displayed.

**Comment by schnudd31do3** [comment]
Any news for me?
Today I updated SnipeIT but the issue is still there.

**Comment by schnudd31do3** [comment]
I have now installed phpmyadmin and observed that when a user logs in, their first name, last name and email address are changed in the database. Only the username remains unchanged. After an LDAP synchronization, first name, last name and email address match the user name again.

**Comment by schnudd31do3** [comment]
Alright guys, I've now found out for myself what caused it. My LDAP-settings was not correct.

From a properly programmed application, I could have expected that configuration errors would not cause data corruption in a database. Appropriate precautions to protect the data in the database are clearly missing here.

Additional, the debug information is too less to really get hints whats giong wrong.

**Comment by ZebboKlaufix** [comment]
@schnudd31do3 I ran into the exact same problem. Is it possible for you to give a bit more detailed version of your solution? Thx

**Comment by schnudd31do3** [comment]
![image](https://user-images.githubusercontent.com/72391822/214574705-c3d64643-c497-4706-9d2d-113998066d89.png)

**Comment by WGS-Adam** [comment]
Encasing the ldap filter with &( ) fixed this issue for me, I was also using an OR query.

**Comment by jamboNum5** [comment]
> You're doing an 'OR' query - that's the `|` symbol - so it's probably just grabbing the first user who matches - which must be Michael XXX.
> 
> You can maybe try changing your LDAP filter to `&(|(l=something1)(l=something2)(l=something3))` - presuming I balanced the parentheses right. Or, if you can try to pull off a branch, I should have a possible fix up shortly?

Thanks for this advice, this has also fixed my issue. Had the same LDAP filter for years and it wasn't a problem until the system was upgraded, was a little confusing.

**Comment by CHARANTEJAH1290** [comment]
Hi @schnudd31do3 and @seal61 
i am facing the same issue, but  in my case the user's name and mail id was changing to some random person once the login 
i used edit it in my admin's account but if the user logs in the data of the user's name and email used to change 

i hope this filter  &(|(l=something1)(l=something2)(l=something3)) from @uberbrady works

**Comment by jamessut1** [comment]
Had the same issue, but wrapping the LDAP filter in `&()` worked for me!
