### ISSUE TITLE
QR Codes Not Generating

### ISSUE THREAD

**Issue by iamjustingraves** [grokability/snipe-it#11277]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

QR codes not generating because the path is incorrect. I'm running 6.0.2. The image path to a QR is https:/server.domain.org//hardware/3278/qr_code. The path is adding an extra "/". Removing the extra "/" show the QR but not the entire label.

This is what shows
![image](https://user-images.githubusercontent.com/86367850/172608142-a8899d45-e98d-43c5-a859-66e66840412e.png)

### Reproduction steps

1. Generate Label
2.
3.
...

### Expected behavior

Generate a QR label to print

### Screenshots

![image](https://user-images.githubusercontent.com/86367850/172608157-bfe39f62-edfc-46a9-8de9-5461561c63cb.png)

### Snipe-IT Version

6.0.2

### Operating System

Windows Server 2016

### Web Server

IIS

### PHP Version

8

**Comment by snipe** [comment]
What is your APP_URL?

**Comment by iamjustingraves** [comment]
APP_URL corresponds to the server https://inventory.domain.org

**Comment by snipe** [comment]
I was asking for the specific APP_URL. Nine times out of ten when we see qr code issues, it's either an APP_URL issue or a permissions issue. 

Please try to open the QR code in a new tab and tell me what happens in your browser console and also anything that shows up in your app logs.

**Comment by iamjustingraves** [comment]
Upgrading to 6.0.4 has solved the problem

**Comment by iamjustingraves** [comment]
No problem. Opening in a new tab gives a 404. The following URL shows in the address bar https://inventory.aaa9.org//hardware/3278/qr_code<https://inventory.aaa9.org/hardware/3278/qr_code>

The APP_URL I have set is https://inventory.aaa9.org/

Justin Graves | IT Manager and HIPAA Security Officer | Area Agency on Aging Region 9, Inc.
710 Wheeling Ave Cambridge, Ohio 43725
Phone: 740.435.4930 |Fax: 740.432.2843 | ***@***.*** <https://www.linkedin.com/in/iamjustingraves/>
E-mail: ***@***.******@***.***> | Secure E-Mail: Send a Secure Message<https://web1.zixmail.net/s/e?b=aaa9&m>
***@***.***[CCSA-Badge][CSCS-Badge][CHP-Badge]
