### ISSUE TITLE
SAML login with AzureAD not working for 2FA/FIDO users

### ISSUE THREAD

**Issue by ThisDevDane** [grokability/snipe-it#11287]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have setup SAML to AzureAD and I can login when using an incognito window just fine, but if I login from my normal browser I get the following error:
`
AADSTS75011: Authentication method 'MultiFactor, Fido' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'. Contact the Snipeit application owner.
`

### Reproduction steps

1. Having logged into a AzureAD/MS account beforehand with 2FA/FIDO on a browser that hasn't logged into SnipeIT
2. Go the SnipeIT
3. Get redirected to error page

### Expected behavior

Getting logged in using pre-existing SSO session

### Screenshots

![image](https://user-images.githubusercontent.com/1834353/172927312-a6df61e9-9334-4975-9555-769129e80ce6.png)

### Snipe-IT Version

6.0.2

### Operating System

Linux (Kubernetes)

### Web Server

Nginx

### PHP Version

7.4.2

### Operating System

Windows

### Browser

Chrome

### Version

Version 102.0.5005.63 (Official Build) (64-bit)

**Comment by uberbrady** [comment]
You can certainly try this: https://snipe-it.readme.io/docs/saml#additional-azure-ad-troubleshooting which might help? I'm not sure; I haven't seen this one before :/

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/saml#additional-azure-ad-troubleshooting">SAML</a></strong></div><div>Configuration guidelines for SAML Single-Sign On (SSO) support</div></blockquote>

**Comment by ThisDevDane** [comment]
@uberbrady That actually fixes this as well! But the entry says "Azure AD x509 Error with **Microsoft Edge**" and I'm using chrome so perhaps the mention of Edge should be removed?

**Comment by uberbrady** [comment]
Yeah, I can make it handle both cases I think.

**Comment by uberbrady** [comment]
Okay, I've added your case and made it no longer specific to Edge, as Chrome is affected, and other browsers might be too. I'll mark this as resolved since it looks like it handled your issue.
