### ISSUE TITLE
Pre-Flight Step.

### ISSUE THREAD

**Issue by metacraft-hq** [grokability/snipe-it#11284]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Followed every step to set up and install snipe-it on Windows 11 XAMPP
When launch to start Pre-Flight I get:
```
This site can’t be reachedCheck if there is a typo in snipe-it.local.
If spelling is correct, [try running Windows Network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN
```

Also when i tried viewing mySql (localhost:8000/phpmyadmin) this too was broken (which i assume was the edits suggested in the documentation)

### Reproduction steps

Here is my documented steps in hopes to not have missed a step:

`mkdir inetpub\wwwroot\`

`cd C:\inetpub\wwwroot\`

```shell
$ git clone https://github.com/snipe/snipe-it snipe-it
Cloning into 'snipe-it'...
remote: Enumerating objects: 128794, done.
remote: Counting objects: 100% (1867/1867), done.
remote: Compressing objects: 100% (972/972), done.
remote: Total 128794 (delta 961), reused 1735 (delta 894), pack-reused 126927
Receiving objects: 100% (128794/128794), 140.81 MiB | 2.37 MiB/s, done.
Resolving deltas: 100% (83148/83148), done.
Updating files: 100% (6534/6534), done.
```
set up .env
https://snipe-it.readme.io/docs/configuration

```
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=ChangeMe
APP_URL=http://snipe-it.local:8000
APP_TIMEZONE='UTC'
APP_LOCALE=en
MAX_RESULTS=500

//and mail smtp settings
```

`cd C:\inetpub\wwwroot\snipe-it`

`composer install --no-dev --prefer-source`

`php artisan key:generate`

Prep XAMPP set up:
https://snipe-it.readme.io/docs/xampp

`C:\xampp\apache\conf\extra\httpd-vhosts.conf` 

INSERTED:

```

# VirtualHost for SNIPE-IT.LOCAL

<VirtualHost snipe-it.local:80>
  DocumentRoot "C:\xampp\htdocs\snipe-it\public"
  ServerAdmin snipe-it.local
  <Directory "C:\xampp\htdocs\snipe-it">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
  </Directory>
  
    #
    # ScriptAlias: This controls which directories contain server scripts. 
    # ScriptAliases are essentially the same as Aliases, except that
    # documents in the target directory are treated as applications and
    # run by the server when requested rather than as documents sent to the
    # client.  The same rules about trailing "/" apply to ScriptAlias
    # directives as to Alias.
    #
    # We have to use this script alias for Snipe-IT because 
    # XAMPP has a built-in URL for /licenses.
    # See https://github.com/snipe/snipe-it/issues/4031 for more info
    ScriptAlias /licenses/ "C:\xampp\htdocs\snipe-it\public"
    
</VirtualHost>
```
`C:\Windows\System32\drivers\etc.`

Edit your hosts file, adding our localhost for snipe-it.local:

```Text

# localhost name resolution is handled within DNS itself.
#   127.0.0.1       localhost
#   ::1             localhost
127.0.0.1   snipe-it.local
```

To remove this built-in XAMPP alias, edit your httpd-xampp.conf in your XAMPP config and delete lines below:
REMOVED THIS:
```Text
Alias /licenses "C:/xampp/licenses/"
    <Directory "C:/xampp/licenses">
        Options +Indexes
        <IfModule autoindex_color_module>
            DirectoryIndexTextColor  "#000000"
            DirectoryIndexBGColor "#f8e8a0"
            DirectoryIndexLinkColor "#bb3902"
            DirectoryIndexVLinkColor "#bb3902"
            DirectoryIndexALinkColor "#bb3902"
        </IfModule>
        Require local
        ErrorDocument 403 /error/XAMPP_FORBIDDEN.html.var
   </Directory>

    Alias /phpmyadmin "C:/xampp/phpMyAdmin/"
    <Directory "C:/xampp/phpMyAdmin">
        AllowOverride AuthConfig
        Require local
        ErrorDocument 403 /error/XAMPP_FORBIDDEN.html.var
    </Directory>
```
RAN THIS:

```
composer dump-autoload; php artisan cache:clear; php artisan config:clear; php artisan route:clear; php artisan debugbar:clear; php artisan event:clear; php artisan view:clear; php artisan optimize:clear; php artisan clear-compiled


Package manifest generated successfully.
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
Copied Directory [\vendor\livewire\livewire\dist] To [\public\vendor\livewire]
Publishing complete.
Generated optimized autoload files containing 8573 classes
Application cache cleared!
Configuration cache cleared!
Route cache cleared!
Debugbar Storage cleared!
Cached events cleared!
Compiled views cleared!
Cached events cleared!
Compiled views cleared!
Application cache cleared!
Route cache cleared!
Configuration cache cleared!
Compiled services and packages files removed!
Caches cleared successfully!
Compiled services and packages files removed!

```
`composer -v`
```
Composer version 2.3.7 2022-06-06 16:43:28
```
`composer check-platform-reqs`
```
Checking platform requirements for packages in the vendor dir
ext-openssl          8.0.17    success
ext-pcre             8.0.17    success
ext-pdo              8.0.17    success
ext-simplexml        8.0.17    success
ext-sodium           8.0.17    success
ext-tokenizer        8.0.17    success
ext-xml              8.0.17    success
ext-xmlreader        8.0.17    success
ext-xmlwriter        8.0.17    success
ext-zip              1.19.5    success
ext-zlib             8.0.17    success
lib-pcre             10.35     success
php                  8.0.17    success
```

https://snipe-it.readme.io/docs/pre-flight-setup

`php artisan serve`

### Expected behavior

Was hoping to see the pre-flght screen?

### Snipe-IT Version

https://snipe-it.readme.io/docs/pre-flight-setup

### Operating System

Windows 11

### Web Server

Apache 2.4.53, 

### PHP Version

PHP 8.0.19, phpMyAdmin 5.2.0, OpenSSL 1.1.1, XAMPP Control Panel 3.2.4, 

### Operating System

Windows 11 21H2 (OS Build 22000.675)

### Browser

Chrome

### Version

Version 102.0.5005.63 (Official Build) (64-bit)

**Comment by snipe** [comment]
Huge kudos, you've done everything right here. This definitely looks like a DNS/networking issue, not a Snipe-IT issue, but you've done a great job troubleshooting and documenting everything you did, and we deeply appreciate that. 

> localhost:8000/phpmyadmin

We don't provide phpMyAdmin, so unless you installed that yourself, I'd sort of expect that.

When you try to access the snipe-it install page, do you see anything in your web server logs, or your application logs? That will at least help us understand whether or not the network is even letting connections through. If we see nothing there, it's not even touching the application layer, so we know to focus on networking.

**Comment by mikeroq** [comment]
Are you still having issues @AiFxApp?

I'm slightly confused as it looks like you are using XAMPP but your web root is in `inetpub/wwwroot` which is for IIS?

Your DocumentRoot says `C:\xampp\htdocs\snipe-it\public`

Also the VirtualHost says port 80 and your APP_URL is 8000.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
