### ISSUE TITLE
500 Server Error When Assigning New Asset on Create Asset Page

### ISSUE THREAD

**Issue by mmaxwell5** [grokability/snipe-it#11292]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When assigning a new asset to a user, asset or location in the Create Asset page, I get a 500 Server Error.  The Asset gets created and assigned to the correct user, asset or location.  The email notification is also send.  If I create an asset without assigning it to anything, I don't get an error.  I also dont get an error assigning assets after they have been initially created.  

### Reproduction steps

1.Create new asset
2.Assign asset in Create Asset page 
3.
...

### Expected behavior

Go back to Hardware page 

### Screenshots

![Screenshot 2022-06-09 212803](https://user-images.githubusercontent.com/16730904/172978226-379a1bca-676c-4737-b2ea-7448f28cb489.png)
![Screenshot 2022-06-09 212904](https://user-images.githubusercontent.com/16730904/172978300-c2376a54-ac33-45ad-bea3-87f419211b2f.png)

### Snipe-IT Version

v6.0.2 build 7961 (g5bc5e9f10)

### Operating System

Ubuntu 

### Web Server

Apache

### PHP Version

8.1.2

### Error messages

```shell
ErrorException
Undefined array key "checkout_counter"
https://srvusams01/hardware


https://flareapp.io/share/47qd3eEP#F73
```

**Comment by inietov** [comment]
My bad! Sorry, this is already fixed in https://github.com/snipe/snipe-it/commit/f8718ffc1e5c82bad33b36c09529db9b75f90a4c. Pull latest from master and you should be good to go my friend.
