### ISSUE TITLE
[Feature Request]: File permissions/ownership fix

### ISSUE THREAD

**Issue by diplatis** [grokability/snipe-it#11294]
### Is your feature request related to a problem? Please describe.

After multiple upgrades the file permissions and ownership has been mixed up under document root.

### Describe the solution you'd like

A shell script checking current permissions and ownership of all files and folders under document root and fix them accordingly.

### Describe alternatives you've considered

A webpage in Snipe IT indicating the wrong permissions/ownership and suggesting the according actions to the admin.

**Comment by snipe** [comment]
It is outside the scope of this application to make sure your server permissions are correct. It's well documented, and the upgrade script tries very hard to help you identify problem areas.
