### ISSUE TITLE
Bulk Edit inaccessible in 6.0.4

### ISSUE THREAD

**Issue by SonGokussj4** [grokability/snipe-it#11308]
### Debug mode

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After updating to 6.0.4, when I click on one or more rows in Assets, People, ... The `Go` button for `Bulk Edit` will not activate and it's still in it's disabled mode.

I've tried that even on demo.snipeitapp, the same behavior.

### Reproduction steps

Assets -> select row -> `Go` button still disabled

### Expected behavior

Assets -> select row -> `Go` button activates, like in versions before

### Screenshots

![image](https://user-images.githubusercontent.com/13331858/173635729-e79dc44d-cf8e-4b5e-a6c5-245e5a33d120.png)

### Snipe-IT Version

6.0.4

### Operating System

Linux

### Web Server

Docker

### PHP Version

Docker

**Comment by snipe** [comment]
I'm not able to reproduce this locally or on the demo. Am I missing something?


https://user-images.githubusercontent.com/197404/173641323-1f6fcc4c-770b-40ee-a3c5-da0f284a200a.mov

**Comment by SonGokussj4** [comment]
Okay, I was speeding from work so I didn't have a time to test it more. 

It's on the Deployed submenu.
And secondly, on Settings -> Asset Models I can't click on a row, I have to click on the checkbox.

![SnipeitDeployedAssetsBug](https://user-images.githubusercontent.com/13331858/173663458-d5d3f2d7-afdd-454a-ad46-35f4cee033ed.gif)

**Comment by snipe** [comment]
Unfortunately, people keep deleting things from the demo, so this is tough to reproduce - I'm guessing in this context, Deployed is a custom status label, not really a "state". Let me play around a little more locally and see if I can reproduce.

**Comment by snipe** [comment]
AHH - I see it now. That UI is actually using the /statuslabels/x/ UI, not the assets UI. Hang tight.

**Comment by snipe** [comment]
Fixed on master now
