### ISSUE TITLE
Documentation on how to create a policy to limit a user to specific location

### ISSUE THREAD

**Issue by avielc** [grokability/snipe-it#11321]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I tried to understand from the documentation on how to create a user limitation to a specific location
so that those who need to view assests that belong to a specific location can be limited to that.

but Couldn't figure it out.

### Reproduction steps

https://snipe-it.readme.io/docs/user-permissions

### Expected behavior

Finding how to provide access to specific location and only assests. 

Thanks

### Snipe-IT Version

latest

### Operating System

Centos

### Web Server

Nginx

### PHP Version

7.4

**Comment by snipe** [comment]
You can currently only do that by company via full multiple company support. https://snipe-it.readme.io/docs/general-settings#full-multiple-companies-support

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/general-settings#full-multiple-companies-support">General Settings</a></strong></div><div>The General Settings panel allows you to configure aspects of your install such as Full Company Support, whether or not to require physical (digital) signatures on assets, and so on. Snipe-IT offers a sort of multi-tenancy within the application, which allows super-admins to restrict the assets non-...</div></blockquote>

**Comment by avielc** [comment]
Thanks!
Wouldn't it be possible to acheive using the snipepolicy.php files?

**Comment by avielc** [comment]
@snipe - sorry for the ping mate, but it looks like the multi-company feature isn't working well. 
(I'd prefer not to share a screenshot. 
Here is what I did:
- I created a local account in snipe, 
- Adjusted its location\company to the one I want to restrict it to. 
- Gave it permissions to view assests (placed a deny on admin\global admin etc. ) 
I logged in using a different browser - still can see all assests and users. 

Any ideas?

**Comment by snipe** [comment]
We haven't changed anything in company support in some time. You have Full Multiple Company Support enabled in your admin settings?

**Comment by avielc** [comment]
Yes of course, 
Added the check and pressed save. Do I need to restart Snipe?

**Comment by avielc** [comment]
Sorry! Let me correct that. 
I am checking the box. 
but after I go back to check again, it looks like the checkbox doesn't catch. 
(Updated today to the latest 6.0.4 and had some issues with installing Sodium. but managed to get it eventually

**Comment by avielc** [comment]
``
![image](https://user-images.githubusercontent.com/13572969/173871076-0060cc3e-17cd-43e7-8581-96bd0b857a64.png)
Also, the GUI seems a little off..

**Comment by snipe** [comment]
I'm not able to reproduce the company permissions issue on the demo, are you?

**Comment by avielc** [comment]
What do you mean by Demo? 
Can I clear cache or something to try again?

**Comment by snipe** [comment]
https://demo.snipeitapp.com

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by avielc** [comment]
Unable to login there currently, 
I'll try again in a minute and see if I can get it working there.

**Comment by avielc** [comment]
admin / password  - do not work to login to the demo 🤔

**Comment by snipe** [comment]
People change it sometimes via the API - I'm reseeding it now.

**Comment by avielc** [comment]
Just tested on demo - it worked there. 
I also tried to clear cache through the snipe-it user 
received: `Failed to clear cache. Make sure you have the appropriate permissions.` 
cleared via root - and it cleared. 
Checked snipe - option is now marked
checked the test account - it works. 
Thanks mate! sorry for the lengthy troubleshooting here.

**Comment by snipe** [comment]
Sounds like you probably need to fix your permissions. You shouldn't need to run anything as root for Snipe-IT.

Glad you're sorted, but take the time when you can to fix those permissions, else you might end up with some wonky stuff.

**Comment by avielc** [comment]
I always have a chmod 775 for the snipe user to run before upgrading and such, but for some reason it didn't help this time. 
I assume there are some caching files written somewhere (need to find the location to figure it out) 
for now, it's a really minor issue, I'll set it on low priority as it barely happens) :)
Thanks again man! really appreciate it!

**Comment by snipe** [comment]
Not a man, but you're welcome 😜

**Comment by avielc** [comment]
greatly appreiciate your help milady :) (Hope i got it right this time)

**Comment by snipe** [comment]
![curtsy-alice](https://user-images.githubusercontent.com/197404/173874421-57b6f46c-c9b2-435d-b6da-514ae4d1a7bd.gif)

😀 😆
