### ISSUE TITLE
Unable to make an API request on assetlist since V6.0.2 Upgrade

### ISSUE THREAD

**Issue by hixair** [grokability/snipe-it#11349]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

One of our automation scenarios is not able to make requests on and api endpoint that used to work. The scenario seems to have broken since v6.xxx upgrade.
Our instance is hosted by Snipe-IT.

### Reproduction steps

1. When trying to GET `https://mycompany.snipe-it.io/api/v1/statuslabels/12/assetlist?limit=500`
2. I receive a 404 : 

```

{
	"status": "error",
	"message": "404 endpoint not found. Please check the API reference at https:\/\/snipe-it.readme.io\/reference to find a valid API endpoint.",
	"payload": null
}
```

4. Other requests, on `/hardware` for example, work.

### Expected behavior

We used to be able to list assets associated to a status label.

### Snipe-IT Version

6.02

### Operating System

Hosted by Snipe

### Web Server

Hosted by Snipe

### PHP Version

Hosted by Snipe

**Comment by mikeroq** [comment]
Looks like this is where/when the endpoint got changed in api.php:
https://github.com/snipe/snipe-it/commit/14ac7a21819af1184dd73535d3fe648d7daeb7be

**Comment by snipe** [comment]
@Godmartinz can you peep this when you get a moment - might have just been a weird merge

**Comment by Godmartinz** [comment]
on it

**Comment by snipe** [comment]
That's always been a sort of weak replacement for the hardware listing API tho. 

`/api/v1/hardware?status_id=x` 

should give you what you want, no?

**Comment by snipe** [comment]
(That's the API call we use when showing you the assets listing within a status label, a la `/hardware?status_id=1`)

**Comment by hixair** [comment]
The endpoint you recommended worked fine with us, thanks ! 
You can close the issue as far as we are concerned as there's no lack of feature in this new version after all.
