### ISSUE TITLE
[Feature Request]: Datasheet field for Asset-Models

### ISSUE THREAD

**Issue by phil-flip** [grokability/snipe-it#11345]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

It would be awesome to have a field, where it's possible to upload files to an Asset-Model, like a Datasheet or other relevant Documentation about this model.

### Describe alternatives you've considered

A file upload as a custom field would also be nice, so it doesn't have to be necessarily a Datasheet field.
That way, it would be possible to also use file uploads in an Asset directly.

**Comment by phil-flip** [comment]
Ok, i clearly haven't worked long enough with the system. Because I just discovered, you can add files to the assets, which is amazing. But I still want to have the same with the Models, if possible ^^

**Comment by snipe** [comment]
This is a feature already under development.

**Comment by phil-flip** [comment]
Alrighty
