### ISSUE TITLE
"Reports" feature are not accessible by users that is a member of a group with "Admin" permission

### ISSUE THREAD

**Issue by vrymel** [grokability/snipe-it#11347]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

"Reports" feature are not accessible by users that is a member of a group with "Admin" permission.

This behavior seems to be expected based on the Gate definition. However, I'm wondering if this is the desired functionality or a bug. Would be happy to open a PR if this is indeed a bug.
<img width="454" alt="image" src="https://user-images.githubusercontent.com/2844464/174529161-5fa0fb2c-a2ba-4e29-bf97-ebce84203269.png">

### Reproduction steps

1. create a group with "Admin" permission
2. assign a user to the created group
3. login to Snipe-IT using user
...

### Expected behavior

"Reports" should be visible in the sidebar. 

### Screenshots

![CleanShot 2022-06-20 at 13 06 11@2x](https://user-images.githubusercontent.com/2844464/174529035-66159deb-8957-4a9b-abcc-09c160b04113.jpg)

### Snipe-IT Version

6.0.2

### Operating System

Mac

### Web Server

Nginx

### PHP Version

8.0.19

**Comment by snipe** [comment]
If you grant them reports permission, can they see it?

**Comment by vrymel** [comment]
Yes @snipe , with reports permission given they are able to see.

**Comment by snipe** [comment]
Then this isn’t a bug. It’s working as designed.

**Comment by vrymel** [comment]
Oh okay but what's the reasoning behind that? Just curious. Admin should access to all right?

**Comment by snipe** [comment]
Admin is just a shortcut to "this user can admin all of the asset models, categories, etc" - super admins are the only ones granted access to everything.
