### ISSUE TITLE
People not showing any records after upgrade to v6.0.4

### ISSUE THREAD

**Issue by FG-Lars** [grokability/snipe-it#11353]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Dashboard shows 334 people, but when viewing the list it says "No matching records found".

Problem occurred after upgrade to v6.0.4 from v4.x.x (git pull).

Both local Snipe-IT users and LDAP users are missing from the list.

### Reproduction steps

1. Open dashboard
2. Look at number of people
3. View list

### Expected behavior

Expecting to see a list of our users.

### Snipe-IT Version

6.0.4 - build 8050 (master)

### Operating System

Debian

### Web Server

Apache/2.4.53

### PHP Version

7.4.28

### Operating System

Windows 10

### Browser

Chrome

### Version

102.0.5005.115

**Comment by SonGokussj4** [comment]
Is it possible you have an "invisible" filter in the "Search" dropdown on the right? This happened to me last week. I opened categories and there was nothing. And because "Search" is saving the state it kept displaying nothing. When I click the `X (clear search)` button, it shows all right.

**Comment by FG-Lars** [comment]
Unfortunately no. I tried the X now with no luck. 

Worked fine before update, but not after.

**Comment by snipe** [comment]
Did you actually run the upgrade script? I'd bet if you do, migrations will run and everything will work fine.

**Comment by FG-Lars** [comment]
RTFM... embarrassing.

In my defence, it is my first run-in with git. I thought the upgrade proccess was just a simple git pull, but I noticed now that you need a few more commands.

Thanks @snipe you can archive this under the resolved easy category.

**Comment by snipe** [comment]
Heh, no worries :) I’m glad you’re sorted.
