### ISSUE TITLE
[Feature Request]: SAML Session Verification

### ISSUE THREAD

**Issue by gruselhaus** [grokability/snipe-it#11366]
### Is your feature request related to a problem? Please describe.

My organization uses Keycloak for SSO Auth. Unfortunately Snipe-IT does not check the validity of a session or provide an endpoint to terminate the session from the IAM system. How does the logic work? As soon as the session expires within Snipe-IT, a new one is requested from the Idp or is SAML within Snipe-IT only used for "login"?

### Describe the solution you'd like

It would be great if there was an endpoint with which to terminate user sessions.

### Additional context

We have Snipe-IT v6.0.4 and Keycloak 18.0.1 in use.

**Comment by uberbrady** [comment]
We **do** have SAML Single Logout Service (SLO/SLS) - does that not do what you need? We do require that you use the "HTTP Redirect" binding, not HTTP Post - but that's an underlying limitation of the SAML library that we use, so I can't imagine us changing that in the near future.

**Comment by gruselhaus** [comment]
We need the functionality to revoke a session from the IdPs' side. I searched a bit on the web. onelogin/php-saml should be able to do the trick.

**Comment by snipe** [comment]
> onelogin/php-saml should be able to do the trick.

That's the SAML library we already use.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
