### ISSUE TITLE
[Feature Request]: automatically resync users with LDAP via API

### ISSUE THREAD

**Issue by kamsobe** [grokability/snipe-it#11368]
### Is your feature request related to a problem? Please describe.

I'm hoping I'm wrong, but all I can find on syncing between SnipeIT and LDAP that **isn't** manually clicking a button in the admin console, is this reference page on using php and artisan on the server itself: https://snipe-it.readme.io/docs/ldap-sync

We're using a hosted server, so from what I understand the above is inaccessible to us right? If so, and if there is no way to currently re-sync users between SnipeIT and LDAP via the API, I'm very surprised.

I've looked at snipe-it.readme.io/reference and can't find anything like the above.

### Describe the solution you'd like

Ability to sync SnipeIT with an integrated LDAP server via the API.

### Describe alternatives you've considered

Self-hosting...

### Additional context

I did not setup the initial account and plan for hosting, but I was passed the project to continue working on.

**Comment by snipe** [comment]
Most folks just set it up to [run on a cron](https://snipe-it.readme.io/docs/ldap-sync) or use [SCIM](https://snipe-it.readme.io/docs/scim). Are those not options for you?

**Comment by uberbrady** [comment]
If you're hosted with us, you can reach out to support@snipeitapp.com and ask for a schedule and we'll cron it for you. Standard hosting is up to 4 times per day, you pick the hour, we pick the minute (to help distribute load). If you need more often than that (or more specific), you'd need to bump up to our next tier of hosting.

But as for hitting an API to force a sync to fire, we don't have that at this time. You might be able to do a `POST` to the right endpoint with the right cookies to do it - but I haven't seen that done before. Still, it's probably possible.

We also have the very early stages of SCIM started, but I haven't seen that working correctly in production yet :/ . Definitely still needs some work.

**Comment by kamsobe** [comment]
@uberbrady phew, that's certainly better than nothing. Thank you very much for that info, I will likely reach out to support to request a cron to be setup.

**Comment by snipe** [comment]
Since it looks like this is going to support, I'm going to close this issue :) We're happy to take care of you through the support channels, @kamsobe
