### ISSUE TITLE
Can not "add default values" in "Fieldset" for "Asset Models"

### ISSUE THREAD

**Issue by LimitlessSlonly** [grokability/snipe-it#11373]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If i click on "Add default values" nothing happens
![image](https://user-images.githubusercontent.com/80404831/175326725-c78c0232-101f-4d47-8dcb-0990e111d082.png)
Error is this one
![image](https://user-images.githubusercontent.com/80404831/175326919-742f45b1-080c-476f-97b1-2b019e1f863c.png)

### Reproduction steps

1.create fieldsets and fields
2.create asset model
3.add fieldset to asset model
4.try to add default values
5.doesnt work :)
...

### Expected behavior

should work ;)
should be able to add default values to fieldset in asset model

### Snipe-IT Version

6.0.5

### Operating System

Windows Server 2019 1809 (build 17763.2928)

### Web Server

ISS

### PHP Version

7.4 32bit

### Operating System

windows 10 21H1

### Browser

Google Chrome 102.0.5005.63  and edge 102.0.1245.39 

### Version

64bit version is in name

### Error messages

```shell
bug doesnt show in logs
```

### Additional context

i think we had to major update 2 weeks ago and now i found out. i upgrade to 6.0.5 but bug still present.
no infos in debug mode :/ 
![image](https://user-images.githubusercontent.com/80404831/175330690-a44f5bdf-1854-4fd2-b532-08483c2156bf.png)

**Comment by inietov** [comment]
That's... weird... just yesterday I was working with the default values and everything looks correct. You have all your dependencies installed? https://snipe-it.readme.io/docs/install-dependencies

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/install-dependencies">Install Dependencies</a></strong></div><div>Composer is a package manager for PHP that allows us to manage the dependencies for the various vendor packages we utilize in Snipe-IT. Vendor packages are PHP libraries that someone else wrote, and that we use in Snipe-IT to help make it awesome. These are not the same thing as the system requireme...</div></blockquote>

**Comment by snipe** [comment]
I'm not able to reproduce this.

**Comment by snipe** [comment]
Can you reproduce this on the demo at all? https://demo.snipeitapp.com

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by ad0mw** [comment]
I am also experiencing the issue.

I was running v6.0.0-RC-7 to test some features out and then ran the upgrade script to the latest version v6.0.8. Since then I cannot add default values into each field set. 

Chrome console shows this:

**Mixed Content: The page at 'https://mydomain.com/models/create' was loaded over HTTPS, but requested an insecure script 'http://mydomain.com/vendor/livewire/livewire.js?id=c69d0f2801c01fcf8166'. This request has been blocked; the content must be served over HTTPS.**

and when the checkbox is clicked it produces the following

**create:904 Uncaught ReferenceError: Livewire is not defined
    at HTMLInputElement.<anonymous> (create:904:13)
    at HTMLInputElement.dispatch (all.js?id=065a8f4827b94b2f743fa1598ff2f196:1:43421)
    at m.handle (all.js?id=065a8f4827b94b2f743fa1598ff2f196:1:41416)
    at Object.trigger (all.js?id=065a8f4827b94b2f743fa1598ff2f196:1:71941)
    at HTMLInputElement.<anonymous> (all.js?id=065a8f4827b94b2f743fa1598ff2f196:1:72537)
    at Function.each (all.js?id=065a8f4827b94b2f743fa1598ff2f196:1:2978)
    at x.fn.init.each (all.js?id=065a8f4827b94b2f743fa1598ff2f196:1:1457)
    at x.fn.init.trigger (all.js?id=065a8f4827b94b2f743fa1598ff2f196:1:72512)
    at C (all.js?id=065a8f4827b94b2f743fa1598ff2f196:1:553354)
    at y (all.js?id=065a8f4827b94b2f743fa1598ff2f196:1:552527)**

Mine is self hosted running on Ubuntu 21.10 and PHP 8.0.8

If anyone has any idea on how to fix. I would be gratefully appreciated.

Thanks

**Comment by snipe** [comment]
@ad0mw what's your `APP_URL` in your `.env`?

**Comment by ad0mw** [comment]
@snipe that was it :)
It was set to http instead of https.

I didn't think to check that. Everything is now working for me. Cheers for your help.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
