### ISSUE TITLE
Unable to upload asset images to snipe

### ISSUE THREAD

**Issue by anh1989** [grokability/snipe-it#11371]
### Is your feature request related to a problem? Please describe.

I get 500 error when uploading pictures

### Describe the solution you'd like

Held

**Comment by snipe** [comment]
Please complete the questions in the issue template that you deleted. What version of snipe-it are you using? What version of php? What’s in your error logs when you try to upload an image? What are your permissions on those upload directories?

**Comment by anh1989** [comment]
i am using snipe 6.0.5 and pho 7.4.30

**Comment by anh1989** [comment]
![image](https://user-images.githubusercontent.com/108050291/175233927-7b532509-0a27-4961-a0d9-abc1ee6f0df3.png)

**Comment by anh1989** [comment]
![image](https://user-images.githubusercontent.com/108050291/175234052-17d96e7b-e44a-41ae-a24e-dff320415c3d.png)

**Comment by snipe** [comment]
Thank you for the clarification. Screenshots of a 500 error don’t help much. Please answer the other questions I asked.

**Comment by anh1989** [comment]
Snipe-IT Version
6.0.5

Operating System
Server 2016

Web Server
IIS

PHP Version
7.4.30

Operating System
W10

Browser
Chrome- all

Version
No response

Device
No response

Operating System
No response

Browser
No response

Version
No response

Error messages
[laravel.log](https://github.com/snipe/snipe-it/files/8972381/laravel.log)

**Comment by snipe** [comment]
```
[2022-06-23 07:02:30] production.INFO: File name will be: asset-image-FxFZh7ghiA.jpg  
[2022-06-23 07:02:30] production.DEBUG: File extension is: jpg  
[2022-06-23 07:02:30] production.DEBUG: Not an SVG or webp - resize  
[2022-06-23 07:02:30] production.DEBUG: Trying to upload to: assets/asset-image-FxFZh7ghiA.jpg  
[2022-06-23 07:02:30] production.ERROR: Intervention\Image\Exception\NotReadableException: Image source not readable
```

The image source isn't readable for some reason. Does this happen with every uploaded image or a specific image?

**Comment by anh1989** [comment]
I don't get what you mean

**Comment by anh1989** [comment]
Please guide me how to fix it

**Comment by snipe** [comment]
Does this happen with every uploaded image or a specific image?

**Comment by anh1989** [comment]
Every image uploaded is like that.

**Comment by snipe** [comment]
Okay, my guess here is that it's got to be permissions issue, an extension issue, or all of your images are weird. Not sure which yet, since that error message isn't that helpful. (That's not your fault, it just is.)

If you save and then upload this image, do you see the same behavior? Also do you see this system wide (i.e. uploading images to categories, companies, etc?)

![1626975758180](https://user-images.githubusercontent.com/197404/176573269-05fd5e08-df5c-4d0f-a4b0-54f7454efb3d.jpeg)

**Comment by anh1989** [comment]
I tried uploading your image, but still get error 500

**Comment by snipe** [comment]
Which image library are you using, GD or Imagemagick?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by christophe-enerdo** [comment]
I know this ticket is closed, but I had the same issue and found the solution.
Apparently you have to enable the php extension exif  in your php.ini

After that I was able to upload images.
