### ISSUE TITLE
[Feature Request]: Upgrade MS-Excel to XLSX

### ISSUE THREAD

**Issue by benwa** [grokability/snipe-it#11378]
### Is your feature request related to a problem? Please describe.

The .xls format stopped being the default for Excel in Office 2007. We get this cool message every time we open an .xls generated from Snipe-IT
![image](https://user-images.githubusercontent.com/1351571/175363058-9a7450c5-c372-4da1-851b-a9f3c64851ea.png)

### Describe the solution you'd like

I'd like for the default MS-Excel format to be .xlsx. This can be configurable so users who still want an .xls can get it.
It would also be cool if the data within the Excel file are set as a table, which allows for filtering and sorting.

### Describe alternatives you've considered

It can stay as is, and then I convert the file to .xlsx, remove compatibility mode, and format as a table.

**Comment by snipe** [comment]
This is on develop now

**Comment by benwa** [comment]
Holy guacamole that was quick! 🥑

**Comment by snipe** [comment]
We aim to please :)
