### ISSUE TITLE
Dashboard Asset Count

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#11381]
### Is your feature request related to a problem? Please describe.

Please consider modifying the dashboard asset count to indicate non-archived items. The count currently includes all inventory assets however, archived items aren't actually part of the inventory. 

Another approach might be to add a checkbox to allow archived items to count towards the total asset numbers.

### Describe the solution you'd like

1. Only count non-archived items as part of the asset inventory totals.

2. Possibly provide a checkbox to allow an archived item(s) to count towards asset inventory totals.

![2022-06-23_13-27-53](https://user-images.githubusercontent.com/31219479/175381654-17eb0f81-b234-4e62-9aeb-e748b8e4391c.jpg)

**Comment by jmartins1** [comment]
![2022-06-23_13-27-53](https://user-images.githubusercontent.com/31219479/175381511-47f12528-9dcf-44de-a384-38962812bb65.jpg)

**Comment by snipe** [comment]
> Another approach might be to add a checkbox to allow archived items to count towards the total asset numbers.

That already exists in admin settings. I think that if that box is checked, we should pull them from all counts (unless you're specifically looking at archived assets)

**Comment by jmartins1** [comment]
I see that option. However, whether it’s checked or not the total asset count does not change on the dashboard. It only control whether it appears in the ALL Assets report. 

 

 

In other words

 

If I have: 

50 items archived 

50 items available

 

The total is 100

 

If I check the box the report shows 100 items

 

If I uncheck the box the report shows 50 items

 

However, the dashboard total remains at 100 regardless.

**Comment by snipe** [comment]
Yes, I am aware. I am agreeing with you.

> I think that if that box is checked, we should pull them from all counts (unless you're specifically looking at archived assets)

**Comment by jmartins1** [comment]
Thank you, J guess I missed the context.

**Comment by jmartins1** [comment]
I believe I am most interested in arhived items. I’m not sure where/how else this might apply. Unless of course, there’d be some way to identiry to status label as active inventory (count) vs. Inactive (don’t count)

**Comment by snipe** [comment]
If I am understanding you correctly, you want archived items not to be counted in overall counts of things if that checkbox is set to ignore them. If that's the case, I am agreeing with you.

**Comment by jmartins1** [comment]
Agreed. One step further might be helpful.

If you create a Status Label, for example STAGING. It would be nice to be able to set the items beneith that lable as counted or not counted towards the overall inventory count.

As I'm sure you are aware. A stagged item would be pending use and might not actually be ready for issue.

**Comment by snipe** [comment]
I don't think that's necessary for the dashboard, since there is already a graph on that page of assets by status label.

**Comment by jmartins1** [comment]
How would non-archived items not appear in the dashboard count?

**Comment by snipe** [comment]
I don't understand that sentence.

**Comment by jmartins1** [comment]
We agree that archived items should not appear in the dashboard total
![2022-06-23_13-27-53](https://user-images.githubusercontent.com/31219479/175387500-1561caf1-8257-4f9c-9a55-dcf4ae76ed85.jpg)
.

What about if I create a new label "STAGGED" and also do not what those items to count to the inventory total until I'm ready?

**Comment by snipe** [comment]
I don't know what STAGGED means, but there is already a count of assets by the status label on the dashboard in the graph. Adding different states of things would clutter the dashboard up a lot I'd think.

**Comment by snipe** [comment]
I'll consider how we might solve this issue, but the dashboard graph should show you that count already, and mousing over the sidenav shows you counts of things by status label as well, so it just seems like extra clutter.

**Comment by jmartins1** [comment]
:) 

Archive is a status label.

Stagged is just a status label (I added it). Would it be possible to add a checkbox on the status label page to tell SnipeIT count items assigned to that label as active/inactive inventory? Active by default, i.e. counted vs not counted.

**Comment by jmartins1** [comment]
In either case, thank you for your considersation.

**Comment by snipe** [comment]
If enough other people would find it useful, maybe - but these are non-trivial scopes to add to a lot of places (and it could add a LOT of confusion for people who don't realize that box is checked on the status label), so if there isn't enough interest in the feature, I'm not sure we'd move forward with it.

**Comment by snipe** [comment]
The asset counts now respect the "show archived assets in list" setting.
