### ISSUE TITLE
[Feature Request]: Custom field for Maintenance Tab

### ISSUE THREAD

**Issue by c1thunder** [grokability/snipe-it#11395]
### Is your feature request related to a problem? Please describe.

I do not know if this request is feasible or not. We are using the maintenance tab for our NCD for ISO audit.  Last week, an auditor pointed out that the tab is quite useful, but we cannot trace wether the asset is claimed under warranty or we buying parts from our vendor. So it will be nice if we can add a field saying "warranty claimed" or "Parts bought from vendor" kind of thing. If we can add a custom field same like we do to the asset, it will be more appreciated

### Describe the solution you'd like

Custom field in maintenance tab

![image](https://user-images.githubusercontent.com/20919681/175845926-6e81cac1-c815-47ed-b5f6-02201588518c.png)

**Comment by mtettke123** [comment]
would be such a great feature...

**Comment by snipe** [comment]
Duplicate of #4261
