### ISSUE TITLE
Check Browser Compatibility for Signature Pad / Add Approval Queue - Was: Empty Signature at Asset Acceptance

### ISSUE THREAD

**Issue by yusuf-basith** [grokability/snipe-it#11393]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

There is no check in place to confirm that the user has actually signed in the Asset Acceptance form.
When the user leaves the signature part completely empty and accepts the EULA, it accepts without any error.

Normally, it should show an error message stating that the signature is missing.

### Reproduction steps

1. Create an Asset Category with "Require users to confirm acceptance of assets in this category" check box enabled.
2. On the General Settings page, make sure that "Require Signature" option is Yes
3. Check out an asset to any user and check the user's mail for the link to accept the asset.
4. Accept the Terms and click Submit without signing.
...

### Expected behavior

Normally an error message should appear asking the user to sign.

### Snipe-IT Version

6.0.4

### Operating System

Windows

### Web Server

WAMP Server

### PHP Version

7.4.26

### Operating System

Windows

### Browser

Google Chrome

### Version

102

**Comment by snipe** [comment]
<img width="1662" alt="Screen Shot 2022-06-29 at 4 54 48 AM" src="https://user-images.githubusercontent.com/197404/176430475-b579d4d0-fb0c-4f42-8fc9-81135d9b47a3.png">

I'm not able to reproduce this...

**Comment by snipe** [comment]
We're discussing the possibility of adding an approval workflow for signatures. I'm not sure how popular it would be, since that's extra work for admins to do, but I think it would handle this. As it stands now, I can't reproduce this, but if I put so much as a dot on the signature pad, it bypasses the alert box I showed in the screenshot above. Also, someone could write nonsense, potentially even swear words, draw poop emojis, etc and that would still not really be a signature. 

It would be a lot of work for a scenario I don't imagine happens all that often, but we're kicking around some ideas on our end.

**Comment by yusuf-basith** [comment]
I checked with the User about how he was able to skip the signature part.
He has used an outdated browser (Internet Explorer). I don't understand why people are still using it.

I told him to use a modern browser. Is it possible to add a small script that checks the Browser for compatible versions and displays a non-intrusive alert to the user telling them to use a compatible one?

Adding an approval workflow is really a good idea. I hope it will be an optional feature so that we can enable it only for critical things.

In my case, the signature is very important as it is a legal requirement to get a physical signature from the user when handing over YubiKeys to them. We are doing it on paper. I was trying to make it digital as we implemented Snipe-IT recently in our company. But in the Pilot Case, we had one without any signature. We also have several waiting for acceptance. The reminder mail feature is a life-saver for me.

**Comment by snipe** [comment]
Oh dear lord - yeah, our support for IE is basically non-existent, and I kinda don't see that changing any time soon (well, at all, really.) MS themselves don't even support it anymore. 

> Is it possible to add a small script that checks the Browser for compatible versions and displays a non-intrusive alert to the user telling them to use a compatible one?

We could try, but legit I don't have an old enough/un-updated machine to test that on. I haven't even seen IE in years and years.

> Adding an approval workflow is really a good idea. I hope it will be an optional feature so that we can enable it only for critical things.

Oh yes, it would definitely be optional. We try very hard not to mess with people's existing workflows, and that would definitely be a giant pain in the ass for people who don't have legal requirements.

**Comment by yusuf-basith** [comment]
Can I close this ticket as the issue has moved away from the topic I opened it for?
Or shall I leave it open as a reminder for the browser version checking?

**Comment by snipe** [comment]
We can leave it open for now - I'll change the title to be more relevant.

**Comment by snipe** [comment]
Quick question - if I put something up on master or develop, do you have a relationship with this user that you could have them test a browser sniff? I completely understand if you don't - in a lot of places that would be weird - but if you can (or if you have access to a machine that has IE), it would at least let me implement this first thing to prevent legal issues for you.

**Comment by yusuf-basith** [comment]
Yes. I can run some tests.
We still have some users who keep IE for some legacy applications.

**Comment by snipe** [comment]
Okay, that's excellent news. Let me see what I can whip together for you.

**Comment by snipe** [comment]
Can you ask your user what version of IE they're using?

**Comment by mikeroq** [comment]
Just to chime in, in addition maybe the AcceptanceController should check if the signature is empty as well? Since it looks like it's only being validated client side. Since client side validation can fail / is trivial to bypass. 

For sure people need to stop using outdated browsers!

Just my 2 cents.

**Comment by snipe** [comment]
@mikeroq It kind of can't. It uses HTML canvas, so the image gets saved as-is, and we don't know what's on it.

**Comment by yusuf-basith** [comment]
In my case, there was no signature file at all.
Since he was using an outdated browser, he couldn't draw the signature.
![image](https://user-images.githubusercontent.com/106800919/176819143-fafd6417-7220-45cc-95b1-2845e3b8970c.png)

**Comment by snipe** [comment]
Huh. Okay, then yeah, we CAN implement that pretty easily, and I can disable JS to test it.

**Comment by yusuf-basith** [comment]
FYI, The user is using the IE version 11.1790.17763.0

**Comment by snipe** [comment]
Thanks @yusuf-basith - I have a PR open right now to solve this. Are you able to pull from develop and test?

**Comment by snipe** [comment]
Actually, I meant test the PR - I'll merge it into develop now.

**Comment by snipe** [comment]
It's on develop now - I might just merge it to master ahead of your testing (if you're able to) just because it seems non-destructive.

**Comment by snipe** [comment]
On master now. I'll create a new issue for the queuing discussion.

**Comment by snipe** [comment]
Linking issue to the queuing discussion: https://github.com/snipe/snipe-it/issues/11441
