### ISSUE TITLE
Database connection [Mariadb] not configured

### ISSUE THREAD

**Issue by wikilike7** [grokability/snipe-it#11396]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I try to install Snipe-IT on Rocky Linux 8, the program prompts **Database connection [Mariadb] not configured.**

The laravel log lists at below:

[2022-06-27 12:41:10] production.ERROR: Database connection [Mariadb] not configured. {"exception":"[object] (InvalidArgumentException(code: 0): Database connection [Mariadb] not configured. at /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:161)
[stacktrace]
#0 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(124): Illuminate\\Database\\DatabaseManager->configuration()
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(95): Illuminate\\Database\\DatabaseManager->makeConnection()
#2 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Facades/Schema.php(49): Illuminate\\Database\\DatabaseManager->connection()
#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\\Support\\Facades\\Schema::getFacadeAccessor()
#4 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#5 /var/www/html/snipe-it/app/Providers/AppServiceProvider.php(59): Illuminate\\Support\\Facades\\Facade::__callStatic()
#6 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\AppServiceProvider->boot()
#7 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#11 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\\Container\\Container->call()
#12 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\\Foundation\\Application->bootProvider()
#13 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#14 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk()
#15 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#16 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#17 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith()
#18 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#19 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#20 /var/www/html/snipe-it/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#21 {main}
"} 

### Reproduction steps

1.  restart the httpd service
2. 
3.
4.
...

### Expected behavior

Database can connected to php

### Snipe-IT Version

6.0.2

### Operating System

Rocky Linux 8

### Web Server

Apache

### PHP Version

7.4.30

**Comment by wikilike7** [comment]
The env settings:

![image](https://user-images.githubusercontent.com/3377226/175864225-ad89cf4b-4941-4007-80f7-0afc55c9e29c.png)

![image](https://user-images.githubusercontent.com/3377226/175864295-8a91e507-1a8f-479a-b245-5bfd949da35a.png)

**Comment by snipe** [comment]
Use `mysql` for that value, not `Mariadb`, per [the configuration documentation](https://snipe-it.readme.io/docs/configuration#required-database-settings). They are effectively the same thing, and there is no `Mariadb` option configured in `config/database.php`.

**Comment by wikilike7** [comment]
> Use `mysql` for that value, not `Mariadb`, per [the configuration documentation](https://snipe-it.readme.io/docs/configuration#required-database-settings). They are effectively the same thing, and there is no `Mariadb` option configured in `config/database.php`.

Thank you so much!

You saved my life.

**Comment by snipe** [comment]
Happy to help!
