### ISSUE TITLE
LDAP users not showing up in "People"

### ISSUE THREAD

**Issue by deadtom76** [grokability/snipe-it#11406]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Upgraded to version 6.0.5 today. Since the upgrade, I can't get any results in the "People" tab.

LDAP sync is running perfectly. When doing a manual sync, all of my users show up. Everyone is able to log in without issue. I can click on people's names in the activity log, and bring up their records. The main page also shows 87 users in the system, at the top of the page.

However, when clicking on the "People" tab, on the left, I get "No matching records found".

No errors in the browser, or in any Apache or PHP logs.

### Reproduction steps

1. Sync LDAP
2. Click on "People" tab

### Expected behavior

Should see a list of all of my users.

### Screenshots

![Screenshot 2022-06-27 at 17-13-24 Update LDAP_AD Settings MPL Asset Management](https://user-images.githubusercontent.com/9619788/176052104-2b267de2-1151-4861-97d3-7a5a43352a3c.png)
![Screenshot 2022-06-27 at 17-14-33 Current Users MPL Asset Management](https://user-images.githubusercontent.com/9619788/176052169-11413d88-edb4-4918-8a29-f00b6f79cade.png)

### Snipe-IT Version

6.0.5

### Operating System

Debian 10

### Web Server

Apache2

### PHP Version

7.4.30

### Operating System

Windows 10

### Browser

Firefox

### Version

101.0.1

### Error messages

```shell
No error messages.
```

**Comment by snipe** [comment]
Did you check the app log? Did you run migrations? When you upgraded, what method did you use, and what was the output?

**Comment by Codewow** [comment]
Run the upgrade command. There is likely a missing column in your database table (or many) from the new updates.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by sylphaxiom** [comment]
I am actually running into this exact same issue in version 6.0.9. I just ran a 'php upgrade.php'. The users populate when checking the SQL database directly, however the page itself does not pop up. I need to manually add a non-LDAP user, but I cannot since my users don't show up on the page.

**Comment by snipe** [comment]
Hi there - this issue is closed and doesn't seem directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)

You probably want to check permissions. If you’re still having trouble, open a new issue within the full output of your upgrade script console.

**Comment by deadtom76** [comment]
> I am actually running into this exact same issue in version 6.0.9. I just ran a 'php upgrade.php'. The users populate when checking the SQL database directly, however the page itself does not pop up. I need to manually add a non-LDAP user, but I cannot since my users don't show up on the page.

What fixed it for me, was that I'd somehow left out the "php artisan migrate" command. Ran that, and everything showed up as it should. I apologize for forgetting to drop in here and update.
