### ISSUE TITLE
[Feature Request]: Hide Default Location field after check out when viewing asset

### ISSUE THREAD

**Issue by MFKDGAF** [grokability/snipe-it#11409]
### Is your feature request related to a problem? Please describe.

After an asset is checked out, and you are veiwing that asset, you are able to see the Location field and the Default location field of the asset which confusses people. It also has part to do with #2196

### Describe the solution you'd like

Once an asset is checked out and you are viewing the asset, the Default Location field should be hidden from view so only the Location field is shown. Then after the asset has been checked in and you are viewing the asset, the Defualt Location field should be visable again (in which the Location field hidden again).

**Comment by snipe** [comment]
> After an asset is checked out, and you are veiwing that asset, you are able to see the Location field and the Default location field of the asset which confusses people.

This is not something we're going to entertain. The default location and the location are not the same, and while it may be confusing to you, it's an important part of workflows for others.
