### ISSUE TITLE
Constrain assets by department

### ISSUE THREAD

**Issue by nbrgit** [grokability/snipe-it#11421]
### Is your feature request related to a problem? Please describe.

I just ran into the problem that we would like to manage assets across departments. Unfortunately this is currently not possible

### Describe the solution you'd like

We have an IT department: which, as you know it, takes care of laptops, printers, PCs, etc.
Colleagues from the company can also request these devices.

Now we would like to create a new department that has almost admin rights. But can only manage their own assets for the same company.

It could look something like this:

Company
 - Department 1
    - DP1 assets
 - Department 2
    - DP2 assets

So that each department is responsible for its own assets and can ONLY manage them.
At the same time, you could also determine which assets are actually visible in the company, similar to the Request asset function.

I think, this Function could be very helpful

**Comment by snipe** [comment]
This is not something we're considering at this time, as we already constrain by Company when using Full Multiple Company support, and this would create quite a lot of additional complexity.
