### ISSUE TITLE
Cannot delete backups in 6.0.5

### ISSUE THREAD

**Issue by CrtiUser** [grokability/snipe-it#11420]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When opening the backups the links at the trashcan are gone.
Only the restore icon has a working link.

Bug or feature?

### Reproduction steps

1. Open Backups
2. All trashcan symbols have no link and are marked as unselectable
3. Newly made backups can't also be deleted via GUI
...

### Expected behavior

Trashcan icon should start deletion of selected backup.

### Snipe-IT Version

6.0.5

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.0.4

### Operating System

Windows 10

### Browser

Edge

**Comment by snipe** [comment]
Add `ALLOW_BACKUP_DELETE=true` to your .env file.
