### ISSUE TITLE
No signature detected error when accepting assets

### ISSUE THREAD

**Issue by xpfgsyb** [grokability/snipe-it#11443]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If the option _Require Signature_ in the general settings is disabled, a user can't accept an asset because of the error message " Error No signature detected. If you are using an older browser, please use a more modern browser to complete your asset acceptance." As the signature field isn't shown to the user because of the disabled option, the user is not able to accept an asset.

If I enable the require signature option, a signature field is shown and after drawing something into it I am able to accept the asset. So I guess it's just a missing or wrong "If" somewhere in the code during acceptance.

This is also reproducible in your demo instance and seems to be a new error since 6.0.6.

### Reproduction steps

1. Disable the option Require Signature in general settings
2. Create an asset in a category that requires acceptance
3. Check out an asset to an user
4. User tries to accept the asset and get the error message as cited above

### Expected behavior

User can accept an asset without signature

### Screenshots

![Screenshot 2022-07-01 at 13 00 29](https://user-images.githubusercontent.com/24813122/176882166-29be1c80-4618-451e-997f-0e50c8af96e6.png)

### Snipe-IT Version

6.0.6

### Operating System

Debian 10.12

### Web Server

Apache

### PHP Version

7.4.30

**Comment by mikeroq** [comment]
Oops that was changed last night. The blade checks the setting to show the field or not, but the controller is not checking the setting. @snipe

**Comment by snipe** [comment]
This is fixed on master now
