### ISSUE TITLE
Inventory Report: "e" at the end of Helpdesk-Email address if user language is set to "German"

### ISSUE THREAD

**Issue by yetanothersys-admin** [grokability/snipe-it#11464]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Inventory reports to users have an "e" at the end of the email if user language is "German".

### Reproduction steps

1. Set a users language to "German" on the user itself
2. Click the newly added "Email List of All Assigned" Button on the overview of said user
3. Check the email that got sent by Snipe-IT

### Expected behavior

That it has the right Helpdesk email address at the end...

### Screenshots

User language:
![image](https://user-images.githubusercontent.com/87183256/177302787-58fc93ed-c008-4a01-b8b4-ca3a792d0bf5.png)

E-Mail if the user's language is set to "English (for us, we tried UK)":
![image](https://user-images.githubusercontent.com/87183256/177302919-12d830c5-057f-401a-9f2d-2cf3a814ed7c.png)

E-Mail if the user's language is set to "German":
![image](https://user-images.githubusercontent.com/87183256/177303014-bb29da69-086d-4ca9-9ae5-15ec6ebd54de.png)

### Snipe-IT Version

6.0.6 - build 8300 (master)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.6

### Additional context

Is this a fresh install or an upgrade? - Upgraded to 6.0.6 on our test and production servers for this new feature (very cool btw 😄)

Indicate whether or not you've manually edited any data directly in the database: Just added the new features to the .env file, but edited nothing else

Probably just a small mistake that just happened somehow and didn't get noticed 😅 We just wouldn't want our (german) users to send a reply to a nonexistant email when we do our yearly check if everything is assigned right to the users... 😆

**Comment by snipe** [comment]
This should be fixed on develop and master
