### ISSUE TITLE
6.0.7 upgrade - SQLSTATE[42000] - Syntax error or access violation, Row size too large

### ISSUE THREAD

**Issue by tbasten** [grokability/snipe-it#11468]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When upgrading (installation is done via git) for 6.0.5 to 6.0.7 when running php upgrade.php, I receive the following.

Migrating: 2022_03_04_080836_add_remote_to_user

   Illuminate\Database\QueryException 

```
  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs (SQL: alter table `users` add `remote` tinyint(1) null default '0')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }
```

### Reproduction steps

1. Switched to the snipe-it user account (sudo su snipeitapp)
2. cd /var/www/snipeit
3. php upgrade.php

### Expected behavior

Upgrade to complete without errors

### Screenshots

Full upgrade log here - https://pastebin.com/rdn4ZwBY

### Snipe-IT Version

6.0.7

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

PHP 7.4.3

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/installation-issues#sqlstate42000-syntax-error-or-access-violation-1118-row-size-too-large

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#sqlstate42000-syntax-error-or-access-violation-1118-row-size-too-large">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>
