### ISSUE TITLE
Missing SQLite database for testing purposes

### ISSUE THREAD

**Issue by chartjes** [grokability/snipe-it#11461]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm trying to get the test suite running and I notice that the `phpunit.xml` file points to a `database.sqlite` file. Is there a tool included here that can generate that file?

### Reproduction steps

1. Install all the development dependencies using `composer install --dev`
2. Run the tests using `vendor/bin/phpunit`
3. Observe that the test suite generates multiple errors about `database.sqlite` not existing

### Expected behavior

The `database.sqlite` file exists already in the repo or a tool is provided that can create one.mas

### Snipe-IT Version

master branch in repo

### Operating System

macos 12.4

### Web Server

none

### PHP Version

PHP 8.1.7

**Comment by mikeroq** [comment]
On mac/linux you can just create a file there with touch:
```touch database/database.sqlite```
In the root directory of snipe-it. 

I was going though this last night, trying to get all the tests working on my machine.

**Comment by chartjes** [comment]
That fixes one problem but it doesn't address the issue of there being no data for the tests. I had been talking with @snipe about doing some paid work to get the test suite running for this project.

**Comment by mikeroq** [comment]
I personally switched to another mysql database for testing. Ran migrations against the env 
```php artisan migrate --env=testing-ci```
You can also seed it. But even after that I still had some issues.

**Comment by snipe** [comment]
Yeah, I think we don't use the sqlite for testing anymore. I generally use my local SQL for local tests and we use the `testing-ci` for CI server tests.

(Sorry for the delay, it's been a helluva week already.)

**Comment by snipe** [comment]
(But it's in `database/database.sqlite`)
