### ISSUE TITLE
snipeit data backup failed

### ISSUE THREAD

**Issue by anh1989** [grokability/snipe-it#11463]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

--help

### Reproduction steps

1. Backup
2.
3.
...

### Expected behavior

backup erro

### Screenshots

![image](https://user-images.githubusercontent.com/108050291/177281934-03f7697d-aa4b-4e33-9d6c-9203c1c9e5ad.png)

### Snipe-IT Version

6.0.6

### Operating System

windown server 2016

### Web Server

iis 10

### PHP Version

7.4.30

**Comment by snipe** [comment]
What’s in your error logs when you run the backup via command line?

**Comment by anh1989** [comment]
[Uploading laravel.log…]()
[Uploading laravel.log…]()

**Comment by anh1989** [comment]
[laravel.log](https://github.com/snipe/snipe-it/files/9044733/laravel.log)

**Comment by mikeroq** [comment]
Big file. Seeing this for one:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.created_by' in 'field list' (SQL: select `users`.`activated`, `users`.`created_by`, `users`.`address`, `users`.`avatar`, `users`.`city`, `users`.`company_id`, `users`.`country`, `users`.`created_at`, `users`.`deleted_at`, `users`.`department_id`, `users`.`email`, `users`.`employee_num`, `users`.`first_name`, `users`.`id`, `users`.`jobtitle`, `users`.`last_login`, `users`.`last_name`, `users`.`locale`, `users`.`location_id`, `users`.`manager_id`, `users`.`notes`, `users`.`permissions`, `users`.`phone`, `users`.`state`, `users`.`two_factor_enrolled`, `users`.`two_factor_optin`, `users`.`updated_at`, `users`.`username`, `users`.`zip`, `users`.`remote`, `users`.`ldap_import`, (select count(*) from `assets` where `users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\User) as `assets_count`, (select count(*) from `licenses` inner join `license_seats` on `licenses`.`id` = `license_seats`.`license_id` where `users`.`id` = `license_seats`.`assigned_to` and `licenses`.`deleted_at` is null) as `licenses_count`, (select count(*) from `accessories` inner join `accessories_users` on `accessories`.`id` = `accessories_users`.`accessory_id` where `users`.`id` = `accessories_users`.`assigned_to`) as `accessories_count`, (select count(*) from `consumables` inner join `consumables_users` on `consumables`.`id` = `consumables_users`.`consumable_id` where `users`.`id` = `consumables_users`.`assigned_to`) as `consumables_count` from `users` where `users`.`deleted_at` is null order by `first_name` asc limit 20 offset 0) in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:712
```
Of course that was on 07/02.

**Comment by mikeroq** [comment]
Could you delete the laravel.log, run the backup again via command line, and upload the new laravel.log?

**Comment by mikeroq** [comment]
> Big file. Seeing this for one:
> 
> ```
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.created_by' in 'field list' (SQL: select `users`.`activated`, `users`.`created_by`, `users`.`address`, `users`.`avatar`, `users`.`city`, `users`.`company_id`, `users`.`country`, `users`.`created_at`, `users`.`deleted_at`, `users`.`department_id`, `users`.`email`, `users`.`employee_num`, `users`.`first_name`, `users`.`id`, `users`.`jobtitle`, `users`.`last_login`, `users`.`last_name`, `users`.`locale`, `users`.`location_id`, `users`.`manager_id`, `users`.`notes`, `users`.`permissions`, `users`.`phone`, `users`.`state`, `users`.`two_factor_enrolled`, `users`.`two_factor_optin`, `users`.`updated_at`, `users`.`username`, `users`.`zip`, `users`.`remote`, `users`.`ldap_import`, (select count(*) from `assets` where `users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\User) as `assets_count`, (select count(*) from `licenses` inner join `license_seats` on `licenses`.`id` = `license_seats`.`license_id` where `users`.`id` = `license_seats`.`assigned_to` and `licenses`.`deleted_at` is null) as `licenses_count`, (select count(*) from `accessories` inner join `accessories_users` on `accessories`.`id` = `accessories_users`.`accessory_id` where `users`.`id` = `accessories_users`.`assigned_to`) as `accessories_count`, (select count(*) from `consumables` inner join `consumables_users` on `consumables`.`id` = `consumables_users`.`consumable_id` where `users`.`id` = `consumables_users`.`assigned_to`) as `consumables_count` from `users` where `users`.`deleted_at` is null order by `first_name` asc limit 20 offset 0) in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:712
> ```

Of course this was on 07-02-2022.

**Comment by mikeroq** [comment]
Ok I see you are on Windows, in your app.env what is `DB_DUMP_PATH=` set to?

See in the documentation about the note for that setting and Windows:
https://snipe-it.readme.io/docs/configuration#required-database-settings 

I want to assume that is correct since your screenshot doesn't say the executable wasn't found.

**Comment by anh1989** [comment]
> I want to assume that is correct since your screenshot doesn't say the executable wasn't found.

I tried, but still can't backup

**Comment by mikeroq** [comment]
> > I want to assume that is correct since your screenshot doesn't say the executable wasn't found.
> 
> I tried, but still can't backup

Can you empty the laravel.log and run the backup again? Then upload the much shorter log file.
Thanks

**Comment by mikeroq** [comment]
> > I want to assume that is correct since your screenshot doesn't say the executable wasn't found.
> 
> I tried, but still can't backup

What's the value of DB_DUMP_PATH?

**Comment by anh1989** [comment]
> > > I want to assume that is correct since your screenshot doesn't say the executable wasn't found.
> > 
> > 
> > I tried, but still can't backup
> 
> What's the value of DB_DUMP_PATH?

![image](https://user-images.githubusercontent.com/108050291/177453968-650e37fe-39a3-4aca-93c5-c320384e96b8.png)

**Comment by snipe** [comment]
Does mysqldump actually live there?

**Comment by anh1989** [comment]
![image](https://user-images.githubusercontent.com/108050291/177455077-bf0d6041-dd58-4a4f-80a6-41564daac87d.png)

It's always here

**Comment by mikeroq** [comment]
Try manually running a dump:

Something like:
`mysqldump -u your_mysql_user -p snipe_data_base_name > c:\path\to\somewhere\to\save\it`
It will prompt for your DB user's password.

**Comment by anh1989** [comment]
[mysqllog.txt](https://github.com/snipe/snipe-it/files/9051148/mysqllog.txt)

**Comment by snipe** [comment]
Ack! Don't upload that! That's your data! I deleted your post - you should never upload schema with data in it to a public GH repo. 

But it at least looks like that dump worked.

**Comment by mikeroq** [comment]
I was trying to replicate last night on Windows. Interestingly enough using a normal windows path (not in 8.3), and even with a space in the directory, the `backup:run` still ran and dumped my DB without issue. 

I was trying to follow the docs where they mention the 8.3 format, and all the other IIS steps.
