### ISSUE TITLE
Assets do not show up inlists after upgrade

### ISSUE THREAD

**Issue by denisimmoos** [grokability/snipe-it#11474]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi there

We tried to upgrade from snipe-it 5.3.3 to 5.4.4 or 6.0.7 in docker and after this we don't see our assets in lists anymore.
The following error appears when analyzing it:

message: “SQLSTATE[42S22]: Column not found: 1054 Unknown column ‘’ in ‘where clause’ (SQL: select count(*) as aggregate from `assets` where `` = ? and `` = ? and `` = ? and `` = ? and `` = ? and `` = ? and `assets`.`deleted_at` is null)”

How can this be fixed ?

### Reproduction steps

Update to another version of snipeit.

### Expected behavior

To see the columns

### Snipe-IT Version

5.4.4

### Operating System

Docker

### Web Server

apache

### PHP Version

7.4.3

### Operating System

Ubuntu

### Browser

All

### Error messages

```shell
message: “SQLSTATE[42S22]: Column not found: 1054 Unknown column ‘’ in ‘where clause’ (SQL: select count(*) as aggregate from `assets` where `` = ? and `` = ? and `` = ? and `` = ? and `` = ? and `` = ? and `assets`.`deleted_at` is null)”
```

**Comment by mikeroq** [comment]
Hi,
What process did you follow to upgrade?

**Comment by denisimmoos** [comment]
Hi
Thank you for the reply.

We used the standard documentation of snipe-it
https://snipe-it.readme.io/docs/upgrading

And we went first directly to the latest version and then we tried going the version by version approach. 





<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div>Always backup your database and configuration files before upgrading. We try very hard to make sure that all database changes are non-destructive, but you should always backup beforehand anyway. You will never regret backing up your database. You may regret not doing so, so it’s just better to get i...</div></blockquote>

**Comment by snipe** [comment]
Do you have any custom fields set up? If so, can you show me a screenshot of that page?

**Comment by denisimmoos** [comment]
here a cvs as example data
`
Company,"Asset Name","Asset Tag",Model,"Model No.",Category,Manufacturer,Serial,Purchased,Cost,EOL,"Order Number",Supplier,Location,Address,Address,City,State,Country,Zip,"Default Location",Address,Address,City,State,Country,Zip,"Checked Out",Type,Username,"Employee No.",Manager,Department,Status,Warranty,"Warranty Expires",Value,Diff,"Fully Depreciated","Checkout Date","Expected Checkin Date","Created at","Updated at","Last Audit","Next Audit Date",Notes,"WIFI MAC Address",Memory,"Disk Storage",CPU,"Model Identifier",Year,"Screen size"
"One Inside Macedonia DOOEL",CD2RJ1HDFVH5,MK-297,"MacBook Pro (Retina, 13-inch, Late 2012)",,Laptop,Apple,C02RJ1HDFVH5,"2022-07-07 00:00:00","83,714.00",,,iStyle,"One Inside Macedonia DOOEL (Skopje)","St. Rajko Zhinzifov, N. 18/1-4 ",,Skopje,"North Macedonia",MK,1000,"One Inside Macedonia DOOEL (Skopje)","St. Rajko Zhinzifov, N. 18/1-4 ",,Skopje,"North Macedonia",MK,1000,,,,,,,"Assigned (deployable)",,,"83,714.00",0.00,,,,"2022-07-07 08:23:48","2022-07-21 13:15:25",,,,,,,,,"128 GB",,,2013,"13"""
"One Inside Macedonia DOOEL",C02R4940FVH5,MK-298,"MacBook Pro (Retina, 13-inch, Late 2012)",,Laptop,Apple,C02R5940FVH5,"2022-07-07 00:00:00","83,714.00",,,iStyle,"One Inside Macedonia DOOEL (Skopje)","St. Rajko Zhinzifov, N. 18/1-4 ",,Skopje,"North Macedonia",MK,1000,"One Inside Macedonia DOOEL (Skopje)","St. Rajko Zhinzifov, N. 18/1-4 ",,Skopje,"North Macedonia",MK,1000,,,,,,,"Assigned (deployable)",,,"83,714.00",0.00,,,,"2022-07-07 08:23:48","2022-07-21 13:14:52",,,,,,,,,"128 GB",,,2013,"13"""

`

<img width="1021" alt="Screen Shot 2022-07-21 at 13 18 40" src="https://user-images.githubusercontent.com/13764632/180202090-debe4396-2551-4f45-afc5-72cef6084316.png">

**Comment by denisimmoos** [comment]
And here a screenshot when I use categorie 15 = Laptop

<img width="1521" alt="Screen Shot 2022-07-21 at 13 24 35" src="https://user-images.githubusercontent.com/13764632/180202424-6b646d4f-bd8b-4c5d-865a-5d2d7603b869.png">

**Comment by denisimmoos** [comment]
I could also provide you with a dbdump but for this I need a secure channel, because we have sensitive data in our license management.

**Comment by snipe** [comment]
Hey there - just trying to clean up some old issues. Are you still having this problem after latest updates?

**Comment by ywiltjer** [comment]
We had this issues.
When adding a custom field with a character not able a in a mysql column name.
It would save a record of the field in 'custom_fields'
But will fail to add a column to  'assets' and a while save a NULL in 'custom_fields.db_column'. 

We fixed it by removing custom fields with a NULL for any fieldsets. followed by manual removing the rows from the database.

**Comment by snipe** [comment]
@ywiltjer In what version? We addressed that issue long ago in this code entere it first tries to use the "smarter" UTF-8 library extension, but falls back down to the simpler one if the library extension isn't enabled:

https://github.com/snipe/snipe-it/blob/9c608dd6ff0e02ff5cca3b2921a9a57aacefd2f6/app/Models/CustomField.php#L349-L361

**Comment by ywiltjer** [comment]
We where using 5.1.7 at the time.
Just update to to 6.1.2. having database migration issues had to set the ROW_FORMAT to DYNAMIC for settings, users and assets. 
Adding custom fields now works with both safe and unsafe characters. 
Guessing someone ignored a error message as the new field show up nicely on the page and is selectade in a costum field set. And it was bad luck the first broken one was with a unsafe character. making me suspect that at first.

**Comment by snipe** [comment]
Thanks for the follow up, @ywiltjer - glad to hear it was fixed in later versions. I'll close this one for now. <3
