### ISSUE TITLE
After Upgrade we got databse 

### ISSUE THREAD

**Issue by avritteam** [grokability/snipe-it#11486]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After running php upgrade.php
we unable to get login page 

### Reproduction steps

1.
2.
3.
...

### Expected behavior

need to get login page and old data

### Screenshots

![image](https://user-images.githubusercontent.com/109067382/178221511-4d46b5d6-d93c-44d4-a619-1bcd7265e8ad.png)

### Snipe-IT Version

5

### Operating System

windows 2008

### Web Server

apache

### PHP Version

 7.4.12

**Comment by avritteam** [comment]
After rename database from snipeit to forge , i can able login and access old data. But unable to view , Create user.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.created_by' in 'field list' (SQL: select `users`.`activated`, `users`.`created_by`, `users`.`address`, `users`.`avatar`, `users`.`city`, `users`.`company_id`, `users`.`country`, `users`.`created_at`, `users`.`deleted_at`, `users`.`department_id`, `users`.`email`, `users`.`employee_num`, `users`.`first_name`, `users`.`id`, `users`.`jobtitle`, `users`.`last_login`, `users`.`last_name`, `users`.`locale`, `users`.`location_id`, `users`.`manager_id`, `users`.`notes`, `users`.`permissions`, `users`.`phone`, `users`.`state`, `users`.`two_factor_enrolled`, `users`.`two_factor_optin`, `users`.`updated_at`, `users`.`username`, `users`.`zip`, `users`.`remote`, `users`.`ldap_import`, (select count(*) from `assets` where `users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\User) as `assets_count`, (select count(*) from `licenses` inner join `license_seats` on `licenses`.`id` = `license_seats`.`license_id` where `users`.`id` = `license_seats`.`assigned_to` and `licenses`.`deleted_at` is null) as `licenses_count`, (select count(*) from `accessories` inner join `accessories_users` on `accessories`.`id` = `accessories_users`.`accessory_id` where `users`.`id` = `accessories_users`.`assigned_to`) as `accessories_count`, (select count(*) from `consumables` inner join `consumables_users` on `consumables`.`id` = `consumables_users`.`consumable_id` where `users`.`id` = `consumables_users`.`assigned_to`) as `consumables_count` from `users` where `users`.`deleted_at` is null order by `first_name` asc limit 20 offset 0)
C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Connection.php#712
Illuminate\Database\QueryException
array:60 [▼
  0 => array:6 [▶]
  1 => array:6 [▶]
  2 => array:6 [▶]
  3 => array:6 [▶]
  4 => array:6 [▶]
  5 => array:6 [▶]
  6 => array:6 [▶]
  7 => array:6 [▶]
  8 => array:6 [▶]
  9 => array:6 [▶]
  10 => array:6 [▶]
  11 => array:6 [▶]
  12 => array:6 [▶]
  13 => array:6 [▶]
  14 => array:6 [▶]
  15 => array:6 [▶]
  16 => array:6 [▶]
  17 => array:6 [▶]
  18 => array:6 [▶]
  19 => array:6 [▶]
  20 => array:6 [▶]
  21 => array:6 [▶]
  22 => array:6 [▶]
  23 => array:6 [▶]
  24 => array:6 [▶]
  25 => array:6 [▶]
  26 => array:6 [▶]
  27 => array:6 [▶]
  28 => array:6 [▶]
  29 => array:6 [▶]
  30 => array:6 [▶]
  31 => array:6 [▶]
  32 => array:6 [▶]
  33 => array:6 [▶]
  34 => array:6 [▶]
  35 => array:6 [▶]
  36 => array:6 [▶]
  37 => array:6 [▶]
  38 => array:6 [▶]
  39 => array:6 [▶]
  40 => array:6 [▶]
  41 => array:6 [▶]
  42 => array:6 [▶]
  43 => array:6 [▶]
  44 => array:6 [▶]
  45 => array:6 [▶]
  46 => array:6 [▶]
  47 => array:6 [▶]
  48 => array:6 [▶]
  49 => array:6 [▶]
  50 => array:6 [▶]
  51 => array:6 [▶]
  52 => array:6 [▶]
  53 => array:6 [▶]
  54 => array:6 [▶]
  55 => array:6 [▶]
  56 => array:6 [▶]
  57 => array:6 [▶]
  58 => array:6 [▶]
  59 => array:6 [▶]
]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.created_by' in 'field list'
C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Connection.php#368
PDOException
array:62 [▼
  0 => array:6 [▶]
  1 => array:6 [▶]
  2 => array:6 [▶]
  3 => array:6 [▶]
  4 => array:6 [▶]
  5 => array:6 [▶]
  6 => array:6 [▶]
  7 => array:6 [▶]
  8 => array:6 [▶]
  9 => array:6 [▶]
  10 => array:6 [▶]
  11 => array:6 [▶]
  12 => array:6 [▶]
  13 => array:6 [▶]
  14 => array:6 [▶]
  15 => array:6 [▶]
  16 => array:6 [▶]
  17 => array:6 [▶]
  18 => array:6 [▶]
  19 => array:6 [▶]
  20 => array:6 [▶]
  21 => array:6 [▶]
  22 => array:6 [▶]
  23 => array:6 [▶]
  24 => array:6 [▶]
  25 => array:6 [▶]
  26 => array:6 [▶]
  27 => array:6 [▶]
  28 => array:6 [▶]
  29 => array:6 [▶]
  30 => array:6 [▶]
  31 => array:6 [▶]
  32 => array:6 [▶]
  33 => array:6 [▶]
  34 => array:6 [▶]
  35 => array:6 [▶]
  36 => array:6 [▶]
  37 => array:6 [▶]
  38 => array:6 [▶]
  39 => array:6 [▶]
  40 => array:6 [▶]
  41 => array:6 [▶]
  42 => array:6 [▶]
  43 => array:6 [▶]
  44 => array:6 [▶]
  45 => array:6 [▶]
  46 => array:6 [▶]
  47 => array:6 [▶]
  48 => array:6 [▶]
  49 => array:6 [▶]
  50 => array:6 [▶]
  51 => array:6 [▶]
  52 => array:6 [▶]
  53 => array:6 [▶]
  54 => array:6 [▶]
  55 => array:6 [▶]
  56 => array:6 [▶]
  57 => array:6 [▶]
  58 => array:6 [▶]
  59 => array:6 [▶]
  60 => array:6 [▶]
  61 => array:6 [▶]
]

**Comment by avritteam** [comment]
after running php artisan migrate , able to view user list.

**Comment by avritteam** [comment]
After updating it seems Database was changed form "snipeit" to "forge". is this normal

**Comment by snipe** [comment]
We don't make any changes to your .env file

**Comment by Nerdy-Technician** [comment]
The database wont automatically change names as @snipe said the .env values we set never change they may add functions like say imgur api use but that would be a change we most likely would need to make due to to env corruption my only thought is you didn't know you your DB name was forge.

Hope this helps @avritteam

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
