### ISSUE TITLE
Print All Assigned Showing Broken Image when there is no signature

### ISSUE THREAD

**Issue by yusuf-basith** [grokability/snipe-it#11487]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When you click on the button Print All Assigned from any user page, you get a page with all the assets and other items assigned in that user's name.
On that page, the last column is the Signature Column.
When there is a signature for an asset, the signature is displayed properly.
When there is no signature, instead of a blank cell, a broken image is displayed.

### Reproduction steps

1. Select a User.
2. Check out one asset with a signature.
3. Check out another asset without a signature.
4. Now go to the User display page and click on the "Print All Assigned" button.
5. The asset having a signature will display the signature.
6. For the Asset without a signature, instead of a blank cell, a broken image is dispalyed.
<img width="565" alt="Screenshot 2022-07-11 173600" src="https://user-images.githubusercontent.com/106800919/178263059-2ef992e4-c950-416c-aa26-f3bff333e4d1.png">

### Expected behavior

The signature cell should be blank.

### Snipe-IT Version

6.0.6

### Operating System

WAMP

### Web Server

Apache

### PHP Version

7.4.26

### Operating System

Windows

### Browser

Google Chrome

### Version

103.0.5060.114

### Additional context

The if condition at line 89 of the file print.blade.php should be updated to check and display the signature only if there is a signature.

I tried to modify from 
`@if ($asset->assetlog->first())`
to
`@if ($asset->assetlog->first()->accept_signature)`
in my development environment and it is working.
But more tests may be needed.

**Comment by mikeroq** [comment]
Feel free to open a PR!

**Comment by snipe** [comment]
I think this was already fixed on master?

**Comment by mikeroq** [comment]
> I think this was already fixed on master?

Seems fixed from this PR #10941 

Looks like this overwrote it:
https://github.com/snipe/snipe-it/commit/caef98d36d55800a3b3070bfd00327caec5c9999#diff-9fa9e752938729b3e59debf58447773eeb6a9b90824184752a95dda672c5bc58L89

I could be wrong!

**Comment by yusuf-basith** [comment]
I upgraded to 6.0.7 just now.
The issue is fixed.
So I am closing this issue.

**Comment by manubiasasaja-dot** [comment]
> ### Debug mode
> * [x]  I have enabled debug mode[x]  I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
> 
> ### Describe the bug
> When you click on the button Print All Assigned from any user page, you get a page with all the assets and other items assigned in that user's name. On that page, the last column is the Signature Column. When there is a signature for an asset, the signature is displayed properly. When there is no signature, instead of a blank cell, a broken image is displayed.
> 
> ### Reproduction steps
> 1. Select a User.
> 2. Check out one asset with a signature.
> 3. Check out another asset without a signature.
> 4. Now go to the User display page and click on the "Print All Assigned" button.
> 5. The asset having a signature will display the signature.
> 6. For the Asset without a signature, instead of a blank cell, a broken image is dispalyed.
> 
> <img alt="Screenshot 2022-07-11 173600" width="565" src="https://user-images.githubusercontent.com/106800919/178263059-2ef992e4-c950-416c-aa26-f3bff333e4d1.png">
> 
> ### Expected behavior
> The signature cell should be blank.
> 
> ### Screenshots
> _No response_
> 
> ### Snipe-IT Version
> 6.0.6
> 
> ### Operating System
> WAMP
> 
> ### Web Server
> Apache
> 
> ### PHP Version
> 7.4.26
> 
> ### Operating System
> Windows
> 
> ### Browser
> Google Chrome
> 
> ### Version
> 103.0.5060.114
> 
> ### Device
> _No response_
> 
> ### Operating System
> _No response_
> 
> ### Browser
> _No response_
> 
> ### Version
> _No response_
> 
> ### Error messages
> _No response_
> 
> ### Additional context
> The if condition at line 89 of the file print.blade.php should be updated to check and display the signature only if there is a signature.
> 
> I tried to modify from `@if ($asset->assetlog->first())` to `@if ($asset->assetlog->first()->accept_signature)` in my development environment and it is working. But more tests may be needed.

Hi Yusuf can i get your modified code for Print All Assigned reporting
