### ISSUE TITLE
Argument #1 ($uri) must be of type string, null given, called in vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol   e.php on line 32                                                                                                                                                            

### ISSUE THREAD

**Issue by Beerlesklopfer** [grokability/snipe-it#11498]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In Request.php line 334: 

Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /usr/share/Snipe-IT/snipe-it-6.0.7/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol
  e.php on line 32

### Reproduction steps

 #>getfacl $PWD 
 owner: www-data
 group: www-data
 user::rwx
 group::r-x
 other::r-x

for CMD in "composer.phar dump-autoload" "artisan cache:clear" "artisan config:clear" "artisan route:clear" "artisan debugbar:clear" "artisan event:clear" "artisan view:clear" "artisan optimize:clear" "artisan clear-compiled"; do sudo -u www-data php8.1 $CMD; done 

results to:

[sudo] password for system:
Generating optimized autoload files
Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /usr/share/Snipe-IT/snipe-it-6.0.7/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol
  e.php on line 32

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /usr/share/Snipe-IT/snipe-it-6.0.7/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol
  e.php on line 32

In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /usr/share/Snipe-IT/snipe-it-6.0.7/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol
  e.php on line 32

In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /usr/share/Snipe-IT/snipe-it-6.0.7/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol
  e.php on line 32

In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /usr/share/Snipe-IT/snipe-it-6.0.7/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol
  e.php on line 32

In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /usr/share/Snipe-IT/snipe-it-6.0.7/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol
  e.php on line 32

In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /usr/share/Snipe-IT/snipe-it-6.0.7/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol
  e.php on line 32

In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /usr/share/Snipe-IT/snipe-it-6.0.7/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol
  e.php on line 32

In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /usr/share/Snipe-IT/snipe-it-6.0.7/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsol
  e.php on line 32

### Expected behavior

no errors / success

### Snipe-IT Version

6.07

### Operating System

Debian 11
 ./composer.phar check-platform-reqs
 Checking platform requirements for packages in the vendor dir
 composer-runtime-api 2.2.2     success
 ext-bcmath           8.1.8     success
 ext-ctype            *         success provided by symfony/polyfill-ctype
 ext-curl             8.1.8     success
 ext-date             8.1.8     success
 ext-dom              20031129  success
 ext-fileinfo         8.1.8     success
 ext-filter           8.1.8     success
 ext-gd               8.1.8     success
 ext-hash             8.1.8     success
 ext-iconv            *         success provided by symfony/polyfill-iconv
 ext-json             8.1.8     success
 ext-libxml           8.1.8     success
 ext-mbstring         *         success provided by symfony/polyfill-mbstring
 ext-openssl          8.1.8     success
 ext-pcre             8.1.8     success
 ext-pdo              8.1.8     success
 ext-phar             8.1.8     success
 ext-simplexml        8.1.8     success
 ext-sodium           8.1.8     success
 ext-tokenizer        8.1.8     success
 ext-xml              8.1.8     success
 ext-xmlreader        8.1.8     success
 ext-xmlwriter        8.1.8     success
 ext-zip              1.19.5    success
 ext-zlib             8.1.8     success
 lib-pcre             10.39     success 
php                  8.1.8     success

### Web Server

nginx version: nginx/1.18.0 built with OpenSSL 1.1.1n  

### PHP Version

PHP 8.1.8 (cli) (built: Jul 11 2022 08:55:24) (NTS)

**Comment by mikeroq** [comment]
Check your `APP_URL` In the .env file. It's probably null. Your app url should start with http:// or https://. No ending slash.

If your host is "localhost" do `http://localhost` for example.

**Comment by Beerlesklopfer** [comment]
Thank you that solved the problem. Maybe it is worth to hint it at [Common Issues](https://snipe-it.readme.io/docs/common-issues) I ran in that problem due an update.

**Comment by snipe** [comment]
If you use the recommended upgrade.php script, it already checks for a null app_url

**Comment by code-Brian** [comment]
Thanks so much. I totally forgot to change the `APP_URL` in my .env file.  This fixed it for me!
