### ISSUE TITLE
"Accepted EULA" pdf download not working

### ISSUE THREAD

**Issue by winkelement** [grokability/snipe-it#11496]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to download the pdf file for an accepted EULA (download button at `/hardware/xx#history`) i get an error 

> File private_uploads/assets/accepted-eula-YYYY-MM-DD-xx-xx-xx.pdf not found on server

at page `/hardware/xx/showfile/yyy`

The file does in fact exist on the server but is located at `private_uploads/eula-pdfs/accepted-eula-YYYY-MM-DD-xx-xx-xx.pdf`

### Reproduction steps

1. Set up EULA acceptance requirement
2. Check out an asset (id=xx)
3. Accept EULA
4. Go to `/hardware/xx#history`
5. Click on the download button for accepted EULA (enable in view if not visible)

### Expected behavior

The pdf file should be retrieved from path `private_uploads/eula-pdfs/accepted-eula-YYYY-MM-DD-xx-xx-xx.pdf` and download correctly.

### Screenshots

<img width="701" alt="Screenshot 2022-07-12 at 12 15 04" src="https://user-images.githubusercontent.com/3525191/178471228-b3cb7d07-014e-469b-8711-403fe701f6b2.png">
<img width="788" alt="Screenshot 2022-07-12 at 12 37 00" src="https://user-images.githubusercontent.com/3525191/178471702-f7226a1e-434e-4c20-aad3-5238b345b436.png">

### Snipe-IT Version

v6.0.7 build 8351 (gacc2e12f1)

### Operating System

Docker

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

MacOS

### Browser

Chrome

### Additional context

Installation from latest Docker Image

**Comment by mikeroq** [comment]
Hmm this is interesting. On the history tab the download button should have a URL like this:

https://snipe-dev.vmgr/stored-eula-file/accepted-eula-2022-07-11-07-29-08.pdf

and not the /hardware/xx/showfile/xx

![image](https://user-images.githubusercontent.com/55674383/178486522-639c8680-75fc-442e-949c-5b035d66f9a2.png)

**Comment by winkelement** [comment]
That's strange... are you on 6.0.7 @mikeroq?
This is what is looks for me:
<img width="1283" alt="Screenshot 2022-07-12 at 14 38 42" src="https://user-images.githubusercontent.com/3525191/178529682-24864c13-62b4-4244-b852-79e10ffbf44e.png">
To be sure i shut down the docker container, deleted it, deleted the image, pulled a new image and rebuilt the container: same result.

**Comment by mikeroq** [comment]
Yea I checked two of my dev environments on v6.0.7. Both on develop though.

**Comment by winkelement** [comment]
I just pulled the `snipe/snipe-it:develop` container but no luck 😕 
I'm confused how something persisting in the database can be the cause... Maybe i'm missing something trivial in that case i apologise in advance 😄

**Comment by mikeroq** [comment]
What language is your snipe in? It looks like German but I don't want to assume!

**Comment by winkelement** [comment]
Yes German indeed though i already set it to english (uk) and cleared all caches but no luck.

**Comment by snipe** [comment]
Language wouldn't matter here I don't think. I'm not able to reproduce this locally. @mikeroq looks like he's dealing with assets, not licenses, if that matters

**Comment by mikeroq** [comment]
> Language wouldn't matter here I don't think. I'm not able to reproduce this locally. @mikeroq looks like he's dealing with assets, not licenses, if that matters

It just looked odd to me that the action type in the table was in German. I had never looked at any of the other languages before. When I switch mine over to German the action types stay in English.

**Comment by mikeroq** [comment]
@winkelement can you check in the database and see what's in the action_logs table?
For instance id 3 is an acceptance: 
![image](https://user-images.githubusercontent.com/55674383/178562424-1f337366-d33a-46b5-8cc4-083aca1826f2.png)

**Comment by winkelement** [comment]
Looks ok for me... This table has also has a `stored_eula` column which is all NULL maybe that's a clue? 
<img width="1278" alt="Bildschirmfoto 2022-07-12 um 23 27 05" src="https://user-images.githubusercontent.com/3525191/178598558-a9f68ae1-2ec7-4d48-ae90-43c770322e45.png">

**Comment by mikeroq** [comment]
> Looks ok for me... This table has also has a `stored_eula` column which is all NULL maybe that's a clue? 


Ok what about looking in devtools at the API request for the history table. Example result:
![image](https://user-images.githubusercontent.com/55674383/178599329-f678620d-d53b-432a-a243-321be5b1950b.png)

**Comment by mikeroq** [comment]
> This table has also has a `stored_eula` column which is all NULL maybe that's a clue?

If your EULA is empty then that should be null.

**Comment by mikeroq** [comment]
I was able to reproduce this. I set `APP_LOCALE=de` and this caused the action type to be translated. Causing the comparison to be false since it was checking the english word `accepted` to it's translation.

I'm not sure why it wasn't translated when I changed my language.

**Comment by hallarks54** [comment]
I don't see anything like this at all, I noticed it here, how can I open it, I haven't seen it in a source or in a demo.

**Comment by hallarks54** [comment]
I don't see anything like this at all, I noticed it here, how can I open it, I haven't seen it in a source or in a demo.

**Comment by winkelement** [comment]
Thank you it works now! 👍🏽 😃
