### ISSUE TITLE
Delete license file upload UI format/object instead of filename

### ISSUE THREAD

**Issue by boring10** [grokability/snipe-it#11507]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When deleting an uploaded file to a license it displays an object instead of just the filename
![Screenshot from 2022-07-14 06-27-20](https://user-images.githubusercontent.com/35600612/178963618-dcf04d7c-2936-4936-9ccb-aa624a3a5178.png)
.

### Reproduction steps

1. Upload a file to a license
2. Delete the uploaded file from a license

### Expected behavior

Display just the filename and not the object for the file

### Snipe-IT Version

v6.0.6 build 8300 (gdf1e2687d)

### Operating System

N/A

### Web Server

N/A

### PHP Version

7.4.29

### Operating System

Ubuntu

### Browser

Chrome

### Version

103.0.5060.114

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Version

N/A

**Comment by mikeroq** [comment]
I fixed that in #11484 :)

**Comment by boring10** [comment]
@mikeroq Awesome, thanks!
