### ISSUE TITLE
[Feature Request]: User doesn't show fullname in output section

### ISSUE THREAD

**Issue by hallarks54** [grokability/snipe-it#11503]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/46216566/178729044-fbb3dae9-37d3-46e7-8c63-a42f0e4bb78b.png)

### Describe the solution you'd like

User doesn't show fullname in output section

**Comment by mikeroq** [comment]
This is turkish right? I think I see the problem:
`'assigned_to'           => 'Bana Atanmış',` is missing `:name`

**Comment by hallarks54** [comment]
Yes, it's Turkish, but it's the same when you translate it into English.

```
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ trans('general.assigned_to', ['name' => $show_user->present()->fullName()]) }}</title>
    <style>
        body {
            font-family: "Arial, Helvetica", sans-serif;
        }
        table.inventory {
            border: solid #000;
            border-width: 1px 1px 1px 1px;
            width: 100%;
        }

        @page {
            size: A4;
        }
        table.inventory th, table.inventory td {
            border: solid #000;
            border-width: 0 1px 1px 0;
            padding: 3px;
            font-size: 12px;
        }

        .print-logo {
            max-height: 40px;
        }

    </style>
</head>
<body>

@if ($snipeSettings->logo_print_assets=='1')
    @if ($snipeSettings->brand == '3')

        <h2>
            @if ($snipeSettings->logo!='')
                <img class="print-logo" src="{{ url('/') }}/uploads/{{ $snipeSettings->logo }}">
            @endif
            {{ $snipeSettings->site_name }}
        </h2>
    @elseif ($snipeSettings->brand == '2')
        @if ($snipeSettings->logo!='')
            <img class="print-logo" src="{{ url('/') }}/uploads/{{ $snipeSettings->logo }}">
        @endif
    @else
        <h2>{{ $snipeSettings->site_name }}</h2>
    @endif
@endif

<h2>{{ trans('general.assigned_to', ['name' => $show_user->present()->fullName()]) }}</h4>

    @if ($assets->count() > 0)
        @php
            $counter = 1;
        @endphp
```

I couldn't see the error, as I said, I made the English default, but the situation is still the same.

**Comment by mikeroq** [comment]
It works properly in english, I only see a couple more languages that are missing the :name placeholder. 
![image](https://user-images.githubusercontent.com/55674383/178749355-9a540fbc-2bcf-41cc-afe3-aa5bf15c6ec2.png)

**Comment by mikeroq** [comment]
What version are you on?

**Comment by hallarks54** [comment]
I'm really stupid, problem solved, I just adI'm really stupid, problem solved, I just added "assigned_to" => :name to lang/en/general.php file. thank you very muchded "assigned_to" => :name to lang/en/general.php file. thank you very much

**Comment by mikeroq** [comment]
Someone will still need to fix the translations that are missing the `:name` in them. Thanks for catching it!
