### ISSUE TITLE
Categories not showing when creating/adding assets

### ISSUE THREAD

**Issue by JLoCascio** [grokability/snipe-it#11513]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I try to edit or create an asset, there is no mechanism to select or change the category.

Bulk importing successfully creates the categories I want.

I have tried manually creating categories but still have no ability to edit or create assets with them.

### Reproduction steps

1.Create 2 asset categories (by import is OK)
2.Import or create an asset
3.Cannot assign category.
...

### Expected behavior

category drop down should  be visible with available categories

### Screenshots

![image](https://user-images.githubusercontent.com/100676700/179258344-381e18dd-ad0f-4ab5-890d-6ddbc69e75a5.png)

### Snipe-IT Version

  Version v6.0.7 - build 8351 (master) 

### Operating System

Ubuntu Server

### Web Server

Laravel/Forge

### PHP Version

8.1

**Comment by snipe** [comment]
Categories are assigned at the model level, not asset level.
