### ISSUE TITLE
Disallow purging of deleted records

### ISSUE THREAD

**Issue by danielnovello-pf** [grokability/snipe-it#11527]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Although I agree with this change [https://github.com/snipe/snipe-it/pull/11388](https://github.com/snipe/snipe-it/pull/11388)
The problem I have is that we are hosted and cannot make changes to our `.env` file.
Is it possible for someone to enable this again for us?

### Reproduction steps

1. Clicked purge
2. Was met with `Error Purging deleted data has been disabled in the .env file. Contact support or your systems administrator.`
3. Created this request
...

### Expected behavior

The deleted records to be purged (for super admins)

### Screenshots

![Screen Shot 2022-07-18 at 1 27 48 PM](https://user-images.githubusercontent.com/85574596/179611545-b33f6049-c1f1-4cde-b272-e1a17a8abc2c.png)

### Snipe-IT Version

v6.0.7 build 8351 (gacc2e12f1)

### Operating System

Hosted

### Web Server

Hosted

### PHP Version

7.4.30

### Operating System

Hosted

### Browser

Various

### Additional context

This is a request, not a complaint

**Comment by snipe** [comment]
@danielnovello-pf - you can send us a request at support@snipeitapp.com and we'll get that turned on for you ASAP. (Remember to let us know your hosted url in the support ticket.)

**Comment by ghost** [comment]
Hi, I am facing the same issue. 

Snipe-IT version: v6.0.10
build: 8610 (g22710afee)
Software License: [AGPL3](https://www.gnu.org/licenses/agpl-3.0.en.html)
PHP Version: 8.0.0
Laravel Version: 8.83.23

**Comment by itsupport-s2i** [comment]
same issue

**Comment by fmotzet** [comment]
I also had this Problem. You have to add:
ALLOW_DATA_PURGE=true
in your env file.
