### ISSUE TITLE
Dashboard "Asset by Status" chart missing "Deployed" meta status

### ISSUE THREAD

**Issue by ShaunNeighbourSwale** [grokability/snipe-it#11521]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

All "Deployed" assets are shown on dashboard "Asset by Status" chart under "Ready to Deploy".

"Assets" list shows these correctly under the "Deployed" status.

### Reproduction steps

1. Create Asset
2. Deploy Asset
3. Look at Dashboard
...

### Expected behavior

Deployed assets to be shown under "Asset by Status" separated from "Ready to Deploy" assets.

### Screenshots

![image](https://user-images.githubusercontent.com/51878759/179469977-8b286a4d-780e-4094-bb66-acd1596603de.png)
![image](https://user-images.githubusercontent.com/51878759/179470026-a5356abe-a0ee-4c89-a8ed-93190696af09.png)

### Snipe-IT Version

6.0.7

### Operating System

Hosted

### Web Server

Hosted

### PHP Version

Hosted

### Operating System

Windows

### Browser

Google Chrome

### Version

103.0.5060.114 (Official Build) (64-bit)

**Comment by snipe** [comment]
The pie chart only represents your individual status labels, it's not broken down by status meta.

**Comment by ShaunNeighbourSwale** [comment]
But it's your states meta?  I'm not reporting that a custom state isn't showing in the dashboard.

1. We add/import an asset.
2. We deploy the asset.
3. The asset automatically enters the "deployed" meta status.
4. This change is reflected in the assets list.
5. This change is not reflected on the dashboard.

If there was consistency in what data is shown, then I would understand, but there isn't, implying that the dashboard chart is not functioning as it should.

**Comment by snipe** [comment]
It's working as expected. The pie chart reflects only your status *labels*, not the meta status. The side nav shows you the breakdown by meta (in addition to your own status labels)

**Comment by ShaunNeighbourSwale** [comment]
Hi

This may be working as you expect, but not as I, or any of my colleagues expect.

This was discussed with your own support team, who escalated this issue to your developers, as they also agreed that this is not as they expected.

Please take a step back, and look at the usefulness of this chart - Does it show an accurate representation of the data.  Does it directly contradict totals shown in another part of your system?

Please reopen this case until you have had sufficient time to consider this different perspective to your own.

**Comment by snipe** [comment]
> This was discussed with your own support team, who escalated this issue to your developers, as they also agreed that this is not as they expected.

Actually, we didn't say that. We said it was working as expected and is not on the short term roadmap. (Helpdesk ticket 29106.) 

It's already open as a feature request in our internal feature/bug ticketing system.

**Comment by snipe** [comment]
(You have to realize that any time we make changes like this for one user, it often profoundly affects users who use it differently. Every time we grant one wish, we upset countless other people who have different workflows, etc.)

**Comment by ShaunNeighbourSwale** [comment]
I completely understand that - But in this instance, I cannot fathom why anyone would want incorrect data shown.

Regarding the ticket;

"Hi Shaun,

I understand the confusion regarding Status Labels, as the term Ready-to-Deploy in this context means "All Assets readily deployable including those currently checked-out to a User "Deployed" or Checked-in and "Deployable".   "Ready-to-Deploy" is a label for for the "Deployable" state; i.e. asset checked out, ready to deploy immediately after being checked back in are considered "Ready-to-Deploy."
​
You shouldn't have to do anything manually when checking out if you are using the default status labels. Deployed is a magical status type that happens when an asset has a status label that is “deployable” and is also checked out. Read a more about how this here: https://snipe-it.readme.io/docs/overview#section-status-labels.
​
So if you check out a "Ready to Deploy" asset, you should see the status change to Ready to Deploy > Deployed > target (user, or asset, or location). And the dashboard graphic should reflect that.
​
​Are you finding that's not the case?


Sincerely,

Victoria Pak
Chief Operations Officer
Grokability, Inc."

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/overview#section-status-labels">Overview</a></strong></div><div>When your Snipe-IT installation is first set up, it can be a little overwhelming to figure out where to get started. The first place to start is usually your Admin Settings. We go through each of the specific admin options one by one in the Admin Settings section of this documentation, but that's wh...</div></blockquote>

**Comment by snipe** [comment]
> Hi Shaun,
> 
> I spoke to our lead developer, and she told me that it actually is working as designed, meaning, the pie chart only looks at the status labels, and not at the meta status.
>
> There is consideration to develop changes to the chart in the future, but unfortunately, it is not on the short term roadmap.
> 
> I'm sorry that we could not be more helpful in this matter.
>
> Sincerely,
> 
> 
> Birgit Zeus
> QA Engineer
> Grokability, Inc.

Regardless, it's open as a ticket on our internal feature/bug tracker, so there's no need to leave it open here.

**Comment by ShaunNeighbourSwale** [comment]
Indeed - Your COO escalated this to your dev team, and that appeared to end the conversation.

I'm glad it's now on your internal roadmap - And that information has now been shared with a customer who raised the issue, and was basically told "tough luck".

You have a great product, and we're happy to continue paying for it.  But this could have been handled better.  The response to the case should have been "This is now on our internal roadmap" rather than the reply I got, which was in contrast to the previous message from your COO, who acknowledged that there was an expectation for consistency between the dashboard and other parts of your system.

I hope this is something you will consider for future requests.

**Comment by snipe** [comment]
I appreciate your candid feedback.

Saying no - or at least *not now* - is part of our job. My COO escalated that to me (the lead dev and CEO). We discussed it, and I decided it was not on the short term roadmap, which is why you got the reply you got from Birgit. "Not on the short term roadmap" means just that. It means we're not saying *no*, but it's not a priority right this second because we have other things that are higher priority that we need to get done. Anything that isn't on the *short term roadmap* gets entered into our internal feature request/bug system so that as we complete certain tasks, we can re-evaluate priorities, the direction we want the product to go, etc. It doesn't mean "tough luck", it means "not now."

**Comment by ShaunNeighbourSwale** [comment]
Thanks - It's the only kind of feedback I give :P 

And I am aware that you are the top banana - Having this level of communication is rare and appreciated.

However........  As top banana, if your response is "It's working as expected." that doesn't leave much room for interpretation.  I may only be one customer, but I think I put forward a strong case, and this seemed to just be disregarded as a non-issue.

I do understand that you have other priorities.  There are other issues still outstanding that I have raised that I would rather take priority over this.  I do not expect every niggle I have to be bumped to the top of the queue just because I took the time to raise the issue.  But....  We are using the system (fairly heavily I think), and when I, or one of my team find something that either isn't quite right, or could be improved, we don't just raise a ticket for the sake of it.

I wrote and deleted a long spiel about customer service, but it's veering away from the issue.  This wasn't a great customer service experience, and I hope you'll take that as constructive criticism rather than any kind of personal attack.  I am not placing 100% of the blame on you, as I clearly saw more negatives in some of the replies than were intended.

Regards

Shaun

**Comment by ShaunNeighbourSwale** [comment]
![image](https://user-images.githubusercontent.com/51878759/193193237-f755758c-ce61-40df-9c56-9b76d1524491.png)
Thank you!

**Comment by csilva-bppw** [comment]
Hi there, 
Sorry for re-opening this ticket, it may only be a mistake, but.

I would wish to see the same chart as shown above by [ShaunNeighbourSwale](https://github.com/ShaunNeighbourSwale) but somehow, I can't see any difference between the assets that are **Ready to Deploy** and the ones that are **Deployed**, so I know what my "stock" is in a glance. 

I don't know if it is some setting that I'm missing.

**Comment by thetechjester** [comment]
My team would also love this as well. I'd love to know how @ShaunNeighbourSwale was able to achieve the chart shown above on our dashboard. 

Please, if there are any FAQs or Docs I'm missing to configure this option I would gladly read them all. Anything I can do to get this implemented for our setup, I will definitely do.

**Comment by jcejka11** [comment]
I'm honestly baffled by the ongoing dialogue between Snipe-IT and its users regarding this issue.

Labeling the current behavior as "working as expected" reflects a misunderstanding of practical IT asset management workflows. If your expectations are based on this implementation, then they're misaligned with how inventory systems are actually used in operational environments.

In most organizations, especially at the director, COO, or CTO level, asset dashboards are a critical first glance into system health and resource readiness. The current behavior of the “Assets by Status” widget showing Ready to Deploy assets—without accounting for deployed assets that still hold the Ready to Deploy status due to metadata or lifecycle state discrepancies—creates a misleading picture. It implies that a pool of assets is available when, in fact, many of them may already be in use.

So while it may be "working as expected" from a developer’s standpoint, that expectation is flawed. This behavior should never have been coded this way, as it fundamentally misrepresents data and fails to support accurate, real-world decision-making.

Now, addressing the broader concern: what exactly does "short-term roadmap" mean in this context? It's been over two years since this issue was first raised, and this dashboard still misrepresents asset status in a way that no IT professional would find acceptable or useful. A pie chart that consistently produces misleading results is not a minor UI issue—it actively undermines trust in the system’s reporting.

This needs to be treated as a product flaw, not a feature working as intended.

**Comment by snipe** [comment]
@TheTechJester In `Admin Settings > General`, select "Status label type":

<img width="934" alt="Image" src="https://github.com/user-attachments/assets/dcb1892d-f839-45ad-8d3c-7554a1d8187a" />

**Comment by thetechjester** [comment]
Thank you! @snipe  I had a duuuuuh moment but finally figured it out and was even able to help someone else along the way. Yay! 😁
I don't really understand why so many get sooo angry. (well perception anyway) I've received nothing but respectful and helpful feedback. I guess you get out what you put in maybe?

**Comment by snipe** [comment]
> and was even able to help someone else along the way. Yay! 

Yay! Love to hear that! (Also I need to update the docs with newer screenshots - some stuff has definitely been added since the last time we edited them.)

> I guess you get out what you put in maybe?

Exactly this. You’ve always been very polite and respectful here. Not sure why some people can’t connect those dots. 🤷‍♀️
