### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by BrendaDominguez13** [grokability/snipe-it#11525]
### Is your feature request related to a problem? Please describe.

unable to allocate products per batch in consumables

### Describe the solution you'd like

It should be possible to enter the amount to be assigned as in the components
![image](https://user-images.githubusercontent.com/109363263/179541402-5a7e0cc9-c767-48f7-be64-997c9ae3afd3.png)

**Comment by snipe** [comment]
Duplicate of #1046

**Comment by andrewlcbhs** [comment]
@snipe #1046 has been closed since 2018. Is the development team working on adding the ability to checkout a batch of consumables at once?

**Comment by snipe** [comment]
There are several PRs open to address this.
