### ISSUE TITLE
Can't view signed EULA as PDF

### ISSUE THREAD

**Issue by hallarks54** [grokability/snipe-it#11524]
### Is your feature request related to a problem? Please describe.

Hello there,

I can't view the signed EULA as PDF, the download button doesn't show up no matter what I do

I don't know where I am missing a mistake, I checked the demo, everything is the same and there is no such thing in the demo.

#10737 but it's here

thanks for your support

System:

Windows Server 2016

Snipe IT Version v6.0.7 - build 8351 (master)

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/46216566/179507824-ef06173e-91b7-454a-a31f-290e2798bb00.png)

**Comment by snipe** [comment]
The download button would appear in the asset's history, not in the overall listing.

**Comment by StephenTrap** [comment]
I found where the accepted eula pdfs are stored!!! You can cross reference the history on any item that you require users to accept and find the signed pdf in the /storage/private_uploads/eula-pdfs directory for that same date/time they accepted it. Hope that makes sense. We have some items that are Licenses that we have people sign agreements for (custom eula) and knowing where the pdfs are stored was a big deal for us. Maybe it will help some others too. It would be nice if it was also in the web ui, but I'll take it for now. At least I can forward the signed agreement to HR now.

**Comment by snipe** [comment]
They *are* in the web UI, under the asset's history, as I mentioned before.

**Comment by StephenTrap** [comment]
I apologize. I meant viewing accepted EULA PDFs that are required for checked out licenses. I see the PDF download button for assets. Sorry for the confusion.

**Comment by snipe** [comment]
Ah, got it :) We'll make sure to add that to the licenses UI as well

**Comment by StephenTrap** [comment]
Excellent!!

**Comment by rasari03** [comment]
![image](https://github.com/snipe/snipe-it/assets/58033299/ed600016-7ea3-4593-a4d3-ac44a521044a)
I can't seem to see the Download Button /option for the EULA PDF under Asset's History. I have confirmed the PDF is in the /storage/private_uploads/eula-pdfs directory.

**Comment by Moldisocks** [comment]
@rasari03 you just have to add the column

**Comment by rasari03** [comment]
> @rasari03 you just have to add the column

@Moldisocks , thank  you ! adding column under  Individual Asset History tab and now I can download the signed PDF EULA.

**Comment by rasari03** [comment]
LDAP username and password is not saving.

**Comment by snipe** [comment]
@rasari03 

> LDAP username and password is not saving.

That's quite unrelated to this thread. Please create a new issue instead of posting unrelated questions/problems to an existing thread.
