### ISSUE TITLE
REDIS Config documentation missing

### ISSUE THREAD

**Issue by chevdor** [grokability/snipe-it#11529]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The doc mentions the following regarding REDIS:
```
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT=null
```

...letting assuming that having those set will allow using REDIS which is NOT the case.
This is however not the case unless you add:
```
CACHE_DRIVER "redis"
```

This last ENV should be added to the doc.

### Reproduction steps

trivial, see above

### Expected behavior

Using the doc allows using REDIS.

### Screenshots

Not required.

### Snipe-IT Version

latest

### Operating System

K8S

### Web Server

Docker image

### PHP Version

Docker image

### Operating System

Docker image

### Browser

Brave

### Version

...

### Device

irrelevant

### Operating System

irrelevant

### Browser

irrelevant

### Version

irrelevant

### Error messages

```shell
Redis would not be put at work otherwise
```

### Additional context

I have not enabled debug mode as it was not required but you force me checking the box...

**Comment by snipe** [comment]
`CACHE_DRIVER "redis"`would not be a valid env  entry. `CACHE_DRIVER="redis"` would be. `CACHE_DRIVER` is already documented, and are standard Laravel configurations.

**Comment by snipe** [comment]
<img width="861" alt="View_Asset_1293554656____Snipe-IT_Demo_Test" src="https://user-images.githubusercontent.com/197404/179632122-7eb5dc0d-eb76-4b98-a29f-711464c12ed9.png">

<img width="858" alt="View_Asset_1293554656____Snipe-IT_Demo_Test-2" src="https://user-images.githubusercontent.com/197404/179632198-2eac85c1-877f-4a8b-b7ae-d87ddadef43f.png">
