### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by eadamson-13** [grokability/snipe-it#11538]
### Is your feature request related to a problem? Please describe.

I have two different groups, group 1 and group 2, I want group 1 to have access to assets a,b,and c but want group 2 to have access to a,b,c,d and e. I know I could make them companies instead of groups to restrict access to certain assets but then I would have to make the same asset models for company 1 and company 2 and the same assets a,b,and c for both companies

### Describe the solution you'd like

I would like to be able to restrict groups to certain categories/asset models/assets without having to separate them by company because then you have to duplicate categories/asset models/assets that belong to more than one company

### Describe alternatives you've considered

I know I could make them companies instead of groups to restrict access to certain assets but then I would have to make the same asset models for company 1 and company 2 and the same assets a,b,and c for both companies

**Comment by Isotop7** [comment]
Please update the title of the feature request with a short description to identify it.

**Comment by snipe** [comment]
This feature is not on the short term roadmap.
