### ISSUE TITLE
Blank selector in Green (Dark mode) theme

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#11549]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In theme green (Dark mode) slector of display colum i blank
![2022-07-22_15h01_30](https://user-images.githubusercontent.com/56491438/180445769-2b0e8513-b359-45a1-b5ef-4ade74e1d6f6.png)

### Reproduction steps

1. Set theme Green (Dark mode)
2. Go to all assets
3. Click on "columns option" 
![2022-07-22_15h10_40](https://user-images.githubusercontent.com/56491438/180446038-70a673c8-bc95-4c0a-8c99-bb25ea4a3924.png)

...

### Expected behavior

Change font color to white in this option or change bg color to white

### Snipe-IT Version

6.0.8

### Operating System

Debian, Docker

### Web Server

Docker

### PHP Version

Docker

### Operating System

Windows

### Browser

Edge

### Version

103

**Comment by snipe** [comment]
It's not actually blank, it's white on white. @Godmartinz can you handle this please?

**Comment by snipe** [comment]
This is fixed on master and develop now.
