### ISSUE TITLE
[Feature Request]: LDAP Users Login

### ISSUE THREAD

**Issue by hpcked3** [grokability/snipe-it#11545]
### Is your feature request related to a problem? Please describe.

LDAP synced useres cant log in with there E-Mail address and confuse them if we tell them to use there account name.
Its hard to use for them and a solution would help a lot.

### Describe the solution you'd like

Would be great to have a switch/field for allowing logins with there E-Mail instead of there username.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by snipe** [comment]
Folks can login using either, as long as they have a matching user. The username field in LDAP settings is specifically meant for this.
