### ISSUE TITLE
Error 405 when checking out accessories, consumables and components

### ISSUE THREAD

**Issue by Isotop7** [grokability/snipe-it#11540]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to check out a accessory to a user, I get a error 405 with the message "Method not allowed".
This happens on my instance with version 6.0.7 and also on the test backend from the API Explorer:

[API Explorer](https://snipe-it.readme.io/reference/accessoriesidcheckedout-1)

### Reproduction steps

1. Get valid user id
2. Get valid accessory od
3. Post to `api/v1/accessories/{id}/checkout` with the actual id and payload `payload = {"assigned_to": 5}`

### Expected behavior

Accessory should be checked out to user with id 5.

### Screenshots

![image](https://user-images.githubusercontent.com/8883656/180041485-3f45f8e7-c2bb-498d-9581-2b990163ab83.png)

### Snipe-IT Version

6.0.7

### Operating System

Ubuntu 20.04.4

### Web Server

Apache + Nginx Proxy

### PHP Version

8.x

**Comment by SChimera** [comment]
This issue is also present on my instance and on the API reference page.

**Comment by SChimera** [comment]
> 

When sending as GET instead of POST I get 200 success.

![image](https://user-images.githubusercontent.com/3224322/180046299-44a19a2b-2a96-43fe-a477-b46891529774.png)

**Comment by Isotop7** [comment]
Is the accessory assigned afterwards? If yes, the documentation has to be adjusted.

**Comment by snipe** [comment]
A GET request should never ever change the state of an object

**Comment by Isotop7** [comment]
This problem seems to also occur on `Consumables` and `Components`. I didn't test these on my instances, but I get 405s using the API Reference and Snipe-IT backend and in the `api.php` these methods also are `GET`s.

**Comment by Isotop7** [comment]
Components and Accessories are fixed in #11541 and merged into develop but I think that the consumables are still missing the `checkin` POST call.

https://github.com/snipe/snipe-it/blob/develop/routes/api.php#L295

Or are these one-time-elements that are not checked in again? This seems to be true as there is no `ConsumablesCheckinController` in `app/Http/Controllers/Consumables`.

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe-it/api.php at develop · snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe-it/api.php at develop · snipe/snipe-it</div></blockquote>
