### ISSUE TITLE
Blank Page after Setup

### ISSUE THREAD

**Issue by rayciancorotan** [grokability/snipe-it#11543]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After installation, I have completed the pre-flight page and set it up. After I back up the server, I rebooted and try to login. It only shows white page. No error whatsoever.

### Reproduction steps

After installation, I have completed the pre-flight page and set it up. After I back up the server, I rebooted and try to login. It only shows white page. No error whatsoever.

### Expected behavior

I should login and go to dashboard as I did after I setup the preflight and I shutdown the VM and back it up. 

### Screenshots

![SnipeIT](https://user-images.githubusercontent.com/61309350/180119907-53195b7e-e2f8-4905-989a-6d63efd674b5.PNG)

### Snipe-IT Version

6.0.7

### Operating System

Centos 7

### Web Server

NGINX

### PHP Version

7.4.30

### Error messages

```shell
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
sockets
sodium
SPL
sqlite3
standard
tokenizer
zlib
```

### Additional context

- Is this a fresh install or an upgrade?

Brand new fresh install.

- Version of Snipe-IT you're running

6.0.7

- Version of PHP you're running

v7.4.30

- Version of MySQL/MariaDB you're running

mysql  Ver 15.1 Distrib 5.5.68-MariaDB

- What OS and web server you're running Snipe-IT on

CentOS Linux release 7.9.2009

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

manual installation. https://www.vultr.com/docs/how-to-install-snipe-it-on-centos-7/

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

Debug turned on, no error reported.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

I believe I set up it correctly, whether nginx or apache. Still same, stuck on white screen when logging in.

- If a stacktrace is provided in the error, include that too.

I don't know this.

- Any errors that appear in your browser's error console.

Console is open, no errors reported.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.

Naturally, no.

- Include any additional information you can find in storage/logs and your webserver's logs.

storage/logs contains nothing.

- Include what you've done so far in the installation, and if you got any error messages along the way.

Described above.

- Indicate whether or not you've manually edited any data directly in the database

No, I have not modified the database at all.

Many thanks for any assistance you can provide.

**Comment by snipe** [comment]
This seems like maybe a server config issue? Perhaps PHP isn't running?

**Comment by rayciancorotan** [comment]
Hello, I believe I fixed this by running php artisan config:clear. Thank you!
