### ISSUE TITLE
[Feature Request]: Add multiple companies to a single user

### ISSUE THREAD

**Issue by danifg92** [grokability/snipe-it#11559]
### Is your feature request related to a problem? Please describe.

We are a company that consists of different smaller companies scattered through different locations. Some of those locations are nearby and there is just one Tech Support team that gives support to multiple companies. We would like for them to be able to manage their own assets.

We have Multiple Company Support Enabled but there is no way to add more than one company to a single user so that it is able to manage the assets from multiple companies using the same account.

### Describe the solution you'd like

We would like the possibility to add multiple companies to a single user, so that it is able to manage the assets of 2+ different companies using the same account.

**Comment by noque-lind** [comment]
I agree, we miss this functionality too.

**Comment by olekrause** [comment]
Same here, this would be a great feature!
For extra convenience, it'd be great if you could choose, whether you'd like to view assets from a single company, or all the companies you're currently assigned to.

**Comment by Xiayu8** [comment]
Same here. Would be really great for us.

**Comment by kryptonit1** [comment]
This would be really useful

**Comment by shinduke** [comment]
+1
This would allow us to use the company permissions feature. Atm we can´t activate it.

**Comment by snipe** [comment]
Duplicate of #8477
