### ISSUE TITLE
Unable to get SAML to work with Google Workspace.

### ISSUE THREAD

**Issue by drj-io** [grokability/snipe-it#11558]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm unable to get SAML to work with Snipe and Google Workspace. 

### Reproduction steps

Add the SAML app to Snipe according to instruction here: https://snipe-it.readme.io/docs/saml

### Expected behavior

Integration should work. We get 
Error: app_not_configured_for_user

### Screenshots

![image](https://user-images.githubusercontent.com/444485/180877396-e7195be3-046f-4c76-a385-cd3ee6d789fb.png)

![image](https://user-images.githubusercontent.com/444485/180877883-862a3909-2767-4454-842c-609ecf387a62.png)

![image](https://user-images.githubusercontent.com/444485/180877965-4d5e3242-732b-4d5f-97a0-dd83cecb7268.png)

![image](https://user-images.githubusercontent.com/444485/180878789-86b71ecf-f6e1-4528-b740-84ec5556229f.png)

### Snipe-IT Version

Hosted version 6.0.8 Build 8409 (master) 

### Operating System

Hosted by Snipe

### Web Server

Hosted by Snipe

### PHP Version

Hosted by snipe

### Error messages

```shell
Error: app_not_configured_for_user
```

### Additional context

Is there something that we need to add for Attribute mappings? If so I didn't see that in the documentation. Thank you!

**Comment by snipe** [comment]
That sounds like a setting issue on the Google side. @uberbrady can you confirm?

**Comment by drj-io** [comment]
Thanks, it seems to me like a possible mapping issue.  The user's username & email match in Snipe.  And the instructions for Snipe's Google Workspace configuration specify that no mappings are needed.  I'm wondering if a mapping on Google's side needs to be set up to match what Snipe is sending.  

The's are the docs we're referencing: https://snipe-it.readme.io/docs/saml

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/saml">SAML</a></strong></div><div>Configuration guidelines for SAML Single-Sign On (SSO) support</div></blockquote>

**Comment by drj-io** [comment]
One thing of note: Attribute Mapping on the Snipe side is set to blank.  The field comment says "NameID will be used if attribute mapping is unspecified or invalid." 

Is NameID the correct attribute that should be mapped? Shouldn't this be an email attribute?  

Per docs: Google only will allow you to authenticate via full email address, not "short usernames".

**Comment by uberbrady** [comment]
`app_not_configured_for_user` I believe means you didn't enable the App (on the google side) for all of your users.

Check out https://snipe-it.readme.io/docs/saml#google-as-saml-identity-provider and look for the part that says "Then, make sure to enable your Google SAML App for all users in your organization" - there's a button you can click that will enable the 'app' for all users in your Google organization.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/saml#google-as-saml-identity-provider">SAML</a></strong></div><div>Configuration guidelines for SAML Single-Sign On (SSO) support</div></blockquote>

**Comment by drj-io** [comment]
The app is configured and enabled as the screenshots show. 

Today I'm getting a 500 error from Google. 

![image](https://user-images.githubusercontent.com/444485/181011292-7933744b-7cc1-43a3-b4cc-8fbbf1697bb5.png)

Progress?

**Comment by drj-io** [comment]
I would love to confirm with someone the SAML attribute mapping and configuration settings on the Google side.  

The docs specify that no attribute mapping is needed in Google: 
![image](https://user-images.githubusercontent.com/444485/181046493-fb7ba2a5-0929-4c96-8965-520a0147cf98.png)

Here are the service provider settings once again in google: 
![image](https://user-images.githubusercontent.com/444485/181046762-d378cbc7-896b-42ee-be19-d9b3811bb571.png)

Here are the settings in snipe: 
![image](https://user-images.githubusercontent.com/444485/181047484-ae66d414-3e56-45b0-b482-935762394fae.png)

I've gone over the instructions several times to confirm, though it seems some of the information has changed since it was written on the Google side. I would love to confirm the settings from someone that has this working with the hosted Snipe capability.

Thanks for looking!

**Comment by alanivey** [comment]
Encountered the same problem. I tried attribute matching but that didn't seem to make a difference.

Snipe-IT:
<img width="768" alt="Screen Shot 2022-09-07 at 9 35 41 AM" src="https://user-images.githubusercontent.com/715868/188892099-3266d137-a0b8-4932-b7ea-36ea105fa91e.png">

Google:
<img width="1125" alt="Screen Shot 2022-09-07 at 9 36 00 AM" src="https://user-images.githubusercontent.com/715868/188892114-8a171246-0337-4d0e-a4cb-dada3239fca9.png">

**Comment by drj-io** [comment]
@alanivey We actually got this working. Our Attribute Mapping field is blank and there are no fields mapped in the GW configuration.

Best of luck!

**Comment by alanivey** [comment]
@drj-io that's encouraging to hear. I've tried with and without the mapping, and I just removed it now again based on your reply. What ended up being the solution for you? Does it just take a while for Google to enable the app for everyone?

**Comment by drj-io** [comment]
@alanivey docs say up to 24 hours, though it seemed like it too longer for us. I was not the one that finished the integration, so that's all the info I have. 

I'm going to go ahead and close this issue given that our case is fixed.  Cheers!

**Comment by oussjarrousse** [comment]
I am having exactly the same issue... I will wait for another 24h and try again...

**Comment by oussjarrousse** [comment]
@alanivey was the issue resolved for you? could you share any insights into this issue? or do you recommend that we just wait? 
Thanks

**Comment by oussjarrousse** [comment]
I think I know what the issue is/was...
SAML won't work for users created on SnipeIT if the users didn't login using the username and password first.
In other words... login for the first time with username and password, the next times, use SAML.

**Comment by chndler** [comment]
@oussjarrousse that's not the case, at least not for my users. Our profile data is synced from LDAP and their first login is done using SAML.

I think there's an additional step with Google now. My SAML configuration was working fine until the 6.1.0 update, though it could just be coincidence since the the change needs to be made in the Google Workspace admin settings.

You need to change the "Name ID format" field from "UNSPECIFIED" to "EMAIL". I also suggested this as an edit in the Snipe-IT SAML docs including this additional step. Hope this helps. 
<img width="1171" alt="Screenshot 2023-04-16 at 12 02 55 PM" src="https://user-images.githubusercontent.com/5118514/232336079-0138a98b-0dbc-4450-a6ca-c4fa00eb2518.png">

**Comment by LoZio** [comment]
> I think I know what the issue is/was... SAML won't work for users created on SnipeIT if the users didn't login using the username and password first. In other words... login for the first time with username and password, the next times, use SAML.

@oussjarrousse thank you!!!!
It was several days I was trying every possible configuration and blamed it on something related to Google. Then I logged in with the password, user is local to Snipe-It, and it worked perfect! So definitely you need a user/password login for local users before using them with SAML
