### ISSUE TITLE
[Feature Request]: Accessory Replenish option

### ISSUE THREAD

**Issue by Robbindj** [grokability/snipe-it#11563]
### Is your feature request related to a problem? Please describe.

Not related to a problem, simply a Quality of Life feature request that, from the looks of it, is already being added for Consumables and Components on the development branch and it would be a shame if accesories was missed out.

Had a look through the issues and requests and couldn't find a request for adding this to accessories.

### Describe the solution you'd like

Similar as in [Pull request #11518](https://github.com/snipe/snipe-it/pull/11518#issue-1307157629)
Add a replenish option with similar functionality for the accesories.

### Describe alternatives you've considered

I've considered adding multiple of the same items to keep a record that way, but it just becomes clunky when assigning equipment out.
It also requires me to remove the "min quantity" once we have replenished the item by a new item or continually adding on to the notes of an existing item to keep a record/history when it was purchased and its cost.

**Comment by snipe** [comment]
Closing this as a duplicate. It’s being worked on, as you yourself observed.
