### ISSUE TITLE
Can't access from hostname

### ISSUE THREAD

**Issue by CuongGiap** [grokability/snipe-it#11574]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi ,

I already completed the setup snipe-it, but can not connect from the hostname, it only works with IP or http://IP
I'm a newbie, please help me what did I wrong ?
<img width="932" alt="Screen Shot 2022-07-28 at 1 26 48 PM" src="https://user-images.githubusercontent.com/110154150/181435852-ca2ca92b-de5c-4e1d-bb05-a3e01cdbae4b.png">

### Reproduction steps

1.
2.
3.
...
<img width="839" alt="image" src="https://user-images.githubusercontent.com/110154150/181436484-a81896b0-3c81-4c5c-9129-e1cc84b7bb21.png">

### Expected behavior

please help
<img width="839" alt="image" src="https://user-images.githubusercontent.com/110154150/181436484-a81896b0-3c81-4c5c-9129-e1cc84b7bb21.png">

### Snipe-IT Version

v6.0.8 build 8409

### Operating System

CentOS7

### Web Server

Apache

### PHP Version

8.0.21

**Comment by keroleskhalil2025** [comment]
Hi 
Make sure that you use the hostname in .env in **APP_URL=** . 
If you already tried this , probably it is DNS issue 
try to add the hostname to /etc/hosts file and check again

**Comment by Nerdy-Technician** [comment]
Could you supply your `/etc/apache/sites-available/snipeit.conf` 

please, comment out any sensitive information,

make sure you have also enabled the site using `sudo a2ensite snipeit.conf`,

ensure all of your php modules are enabled and configured in `php.ini`,

```
<VirtualHost *:80>
  <Directory /var/www/snipe-it/public>
      Allow From All
      AllowOverride All
      Options -Indexes
  </Directory>

  ServerName example.domain.com
  DocumentRoot /var/www/snipe-it/public
</VirtualHost>
```

**Comment by CuongGiap** [comment]
> a2ensite

Currently I'm setting APP_URL=http://myIP. If I set APP_URL=http://hostname , I can't access via both IP or hostname

**Comment by CuongGiap** [comment]
> Hi Make sure that you use the hostname in .env in **APP_URL=** . If you already tried this , probably it is DNS issue try to add the hostname to /etc/hosts file and check again

Currently I'm setting APP_URL=http://myip/. If I set APP_URL=http://hostname/ , I can't access via both IP or hostname

**Comment by CuongGiap** [comment]
> Could you supply your `/etc/apache/sites-available/snipeit.conf`
> 
> please, comment out any sensitive information,
> 
> make sure you have also enabled the site using `sudo a2ensite snipeit.conf`,
> 
> ensure all of your php modules are enabled and configured in `php.ini`,
> 
> ```
> <VirtualHost *:80>
>   <Directory /var/www/snipe-it/public>
>       Allow From All
>       AllowOverride All
>       Options -Indexes
>   </Directory>
> 
>   ServerName example.domain.com
>   DocumentRoot /var/www/snipe-it/public
> </VirtualHost>
> ```
here is my apache configuration : /etc/httpd/conf.d/snipeit.conf
"
<VirtualHost *:80>
        ServerName www.asset.test.com
        ServerAlias asset.test.com
        DocumentRoot /var/www/snipe-it/public
 <Directory /var/www/snipe-it/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>

"
sure that all php modules are enabled

Thanks

**Comment by keroleskhalil2025** [comment]
> > Hi Make sure that you use the hostname in .env in **APP_URL=** . If you already tried this , probably it is DNS issue try to add the hostname to /etc/hosts file and check again
> 
> Currently I'm setting APP_URL=http://myip/. If I set APP_URL=http://hostname/ , I can't access via both IP or hostname

Then probably it is dns issue, make sure you have A record for your hostname in your DNS server or add it to the server hosts file

**Comment by CuongGiap** [comment]
> > > Hi Make sure that you use the hostname in .env in **APP_URL=** . If you already tried this , probably it is DNS issue try to add the hostname to /etc/hosts file and check again
> > 
> > 
> > Currently I'm setting APP_URL=http://myip/. If I set APP_URL=http://hostname/ , I can't access via both IP or hostname
> 
> Then probably it is dns issue, make sure you have A record for your hostname in your DNS server or add it to the server hosts file

Exactly, I miss DNS for localhost. It worked after adding local dns /etc/hosts 

Thank you
