### ISSUE TITLE
Image doesn't appear

### ISSUE THREAD

**Issue by aisyahkarina** [grokability/snipe-it#11577]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

<img width="248" alt="29 07 2022_14 02 36_REC" src="https://user-images.githubusercontent.com/89247987/181693232-9ef2b4b8-4702-42f6-bd3e-6e1412d4e733.png">

It says the image failed to load

### Reproduction steps

Please help

### Expected behavior

I thought we simply had to upload the files

### Snipe-IT Version

v6.0.8

### Operating System

Windows

### Web Server

Apache

### PHP Version

7.4

**Comment by snipe** [comment]
My guess would be that your `APP_URL` is misconfigured in your `.env` file. [Per the documentation](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings), the APP_URL should be the complete URL to your Snipe-IT installation, *including* the `http://` (or `https://` if you're running over TLS.)

<img width="795" alt="Screen Shot 2022-07-28 at 11 35 47 PM" src="https://user-images.githubusercontent.com/197404/181698021-de470225-4865-4786-bd48-9a9cdf2399d2.png">

**Comment by aisyahkarina** [comment]
Thank you! I got it. I changed it to: APP_URL=http://localhost

**Comment by aisyahkarina** [comment]
Do you know how to let other staff see the website?

**Comment by aisyahkarina** [comment]
Do they have to create an account?

**Comment by aisyahkarina** [comment]
And can we access this on other laptops?

**Comment by snipe** [comment]
You'd need to create accounts for them and give them the login, or set up something like SAML or LDAP auth to hook into your existing directory. As for whether folks can access it on other laptops, most likely not, unless you have a static IP or DNS name that you can assign to the server it's running on. Really depends on how your network is set up, which is unfortunately outside the scope of Snipe-IT itself.
