### ISSUE TITLE
ldap sync error

### ISSUE THREAD

**Issue by SilentDon** [grokability/snipe-it#11571]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I click onldap sync button the system is not syncing more the user password. stay the old password!

### Reproduction steps

1.
2.
3.
...

### Expected behavior

after ldap sync the system handle the correct actual password...

### Snipe-IT Version

6.0.8

### Operating System

linux

### Web Server

apache2

### PHP Version

7.4.3

**Comment by snipe** [comment]
Do you have password syncing enabled in your LDAP settings? (It really shouldn't need to sync passwords anymore, since we validate the password directly against the LDAP server.)

**Comment by SilentDon** [comment]
yes i ticked! but stay the old password. nothing refresh please check it and fix this in the code

**Comment by snipe** [comment]
This is not a bug and is not under consideration at this time. 

The syncing of passwords would only happen when the user successfully logs into Snipe-IT via LDAP. We do not have a way to get a user's password from LDAP though LDAP user syncing. When a user logs in, if they successfully auth against your LDAP system, AND if that box is checked, we save the password they entered to login (hash, of course).
