### ISSUE TITLE
[Feature Request]: Trim all input

### ISSUE THREAD

**Issue by mattcarras** [grokability/snipe-it#11589]
### Is your feature request related to a problem? Please describe.

Currently the system accepts extraneous spaces at the beginning and end of most input. However, visually the extraneous spaces aren't easily visible. This may introduce problems with fields that require uniqueness, such as location and company names. 

Note right now the GUI does appear to validate for spaces at the end of a unique field, but not the beginning. Not sure if this is a bug. Either way it will still not actually remove the extraneous spaces if the validation passes.

### Describe the solution you'd like

At the very least, fields that must be unique should always be trimmed on both sides. Ideally, all input fields would be trimmed, including on import.

**Comment by snipe** [comment]
This is working as intended though. If you wanted/needed an extra space at the beginning and we stripped that out, that would be us messing with your data, which we try hard not to do. :(

**Comment by mattcarras** [comment]
Maybe all input is going overboard. I still think there should be an option to trim names and unique fields like serial no., but I'm fine with working around it. Closing request.
