### ISSUE TITLE
Question Department group acces for manager

### ISSUE THREAD

**Issue by alainseys** [grokability/snipe-it#11582]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello ,

Since there is no option to ask a question i have picked bug repport sorry for this.
i was wondering if the following is possible.

In snipeIT there is the possibility to create departments (See settings > Departments) , where you can assign a manager to a derpartment. Is it possible to give the manager of the derpartment acces to snipeIT and that they only can see the departments assets.

### Reproduction steps

Login snipe it with a user that is member of a department

DEPARTMENT name: deparment test
"department test" has 2 users mij user account and a additonal user.

if i login in with my account i am abble to see all the assets but no abbility to view only the department

### Expected behavior

See the departments users andon only those assets

### Snipe-IT Version

5.4.4

### Operating System

Debian 10

### Web Server

Apache

### PHP Version

7.4.30

### Operating System

Windows 10

### Browser

Google

### Version

103.0

**Comment by snipe** [comment]
That's not available at this time.
