### ISSUE TITLE
Server 500 error when trying to edit or create Asset Models

### ISSUE THREAD

**Issue by alexleturgeon** [grokability/snipe-it#11581]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Whenever trying to edit or create an Asset model we get a Server 500 error. I assume it's going to be permissions somewhere, but I can't figure out where.

### Reproduction steps

1.Try to create or edit an Asset through the Web Interface
2.Error shows
3.
...

### Expected behavior

The Asset creation or edit screen shows instead of the error

### Snipe-IT Version

v6.0.7 build 8351 (gacc2e12f1)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2

### Browser

Edge

### Version

103.0.1264.62

### Additional context

This is a migration to a fresh install as the previous version broke following an upgrade.

**Comment by snipe** [comment]
> Error messages
> No response

We need logs to help you. Please see the support documentation to find out how we can better help you.
https://snipe-it.readme.io/docs/getting-help



<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by alexleturgeon** [comment]
Ah, Thank you. Now that it is showing what the error is I have managed to resolve the issue. Many Thanks for your help. Alex
