### ISSUE TITLE
Unable to create or change a table without a primary key

### ISSUE THREAD

**Issue by darkpixel** [grokability/snipe-it#11591]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

This occurs on a new install with a freshly created database.

```
Migration table created successfully.
Migrating: 2012_12_06_225921_migration_cartalyst_sentry_install_users
Migrated:  2012_12_06_225921_migration_cartalyst_sentry_install_users (56.67ms)
Migrating: 2012_12_06_225929_migration_cartalyst_sentry_install_groups
Migrated:  2012_12_06_225929_migration_cartalyst_sentry_install_groups (9.00ms)
Migrating: 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 3750 Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting. (SQL: create table `users_groups` (`user_id` int unsigned not null, `group_id` int unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

      +9 vendor frames 
  10  database/migrations/2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot.php:39
      Illuminate\Support\Facades\Facade::__callStatic()

      +22 vendor frames 
  33  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
Configuration cache cleared!
Configuration cache cleared!
Configuration cached successfully!
```

### Reproduction steps

Spin up a MySQL server, create a new user and database.
Launch the latest snip-it alpine image.

### Expected behavior

Migrations complete successfully.

### Snipe-IT Version

latest-alpine

### Operating System

Linux

### Web Server

Nginx

### PHP Version

Whatever's baked into the docker image

### Operating System

Linux

### Browser

Chrome

### Version

103

**Comment by uberbrady** [comment]
Hrm. Well, you can certainly try to downgrade your MySQL version to a previous one, or maybe unset the `sql_require_primary_key` MySQL system variable?

Another option we have is adding a primary key to that table, but I imagine there are quite a few tables that might look like that.

**Comment by mikeroq** [comment]
Hmm looks like this is off by default?
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_require_primary_key

Also been around since 2018 apparently. 

Looks like you are using a docker image? What image are you using?

<blockquote><img src="https://labs.mysql.com/common/themes/sakila/favicon.ico" width="48" align="right"><div><strong><a href="https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_require_primary_key">MySQL :: MySQL 8.0 Reference Manual :: 5.1.8 Server System Variables</a></strong></div></blockquote>

**Comment by darkpixel** [comment]
It's a managed MySQL instance from DigitalOcean.
There is no way to use an older version of MySQL and there doesn't appear to be an option to set unset sql_require_primary_key as they don't show anything about it being set:

![Screenshot from 2022-08-01 14-10-24](https://user-images.githubusercontent.com/158380/182247256-28ad774b-6205-4833-b1fb-da63c6115761.png)

**Comment by darkpixel** [comment]
> Looks like you are using a docker image? What image are you using?

```image: snipe/snipe-it:latest-alpine```

I pulled it about 15 minutes before submitting the bug report, so it's whatever version was available about 2 hours ago.

**Comment by mikeroq** [comment]
> It's a managed MySQL instance from DigitalOcean. There is no way to use an older version of MySQL and there doesn't appear to be an option to set unset sql_require_primary_key as they don't show anything about it being set:

Looks like you can use the DO API to change that:
https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_patch_config

From:
https://www.digitalocean.com/community/questions/how-to-disable-sql_require_primary_key-in-digital-ocean-manged-database-for-mysql



<blockquote><img src="https://assets.digitalocean.com/articles/pdocs/docs-banner.png" width="48" align="right"><div>DigitalOcean</div><div><strong><a href="https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_patch_config">DigitalOcean API Docs | DigitalOcean Documentation</a></strong></div><div>Programmatically manage Droplets and other DigitalOcean resources using conventional HTTP requests. All of the functionality in the DigitalOcean Control Panel is also available through the API.</div></blockquote>
<blockquote><img src="https://www.digitalocean.com/_next/static/media/social-share-default.e8530e9e.jpeg" width="48" align="right"><div><strong><a href="https://www.digitalocean.com/community/questions/how-to-disable-sql_require_primary_key-in-digital-ocean-manged-database-for-mysql">How to disable SQL_REQUIRE_PRIMARY_KEY in digital ocean manged database for mysql?  | DigitalOcean</a></strong></div><div>How to disable SQL_REQUIRE_PRIMARY_KEY in digital ocean manged database for mysql globaly? </div></blockquote>

**Comment by darkpixel** [comment]
About time DigitalOcean added that. :)

That fixed it.
