### ISSUE TITLE
[Feature Request]: Initial history clear

### ISSUE THREAD

**Issue by nastybutler** [grokability/snipe-it#11592]
### Is your feature request related to a problem? Please describe.

Using several spreadsheets worth of assets, there has been some overlap and some imports to fix erroneous data.  Now that the database is looking good, my boss doesn't like the many, many imports in the history and wants me to clean it up.  The only thing I can think of is to export the assets with every bit of information available to then re-import after clearing the database.  Backups backups backups before doing ANY such thing.

Is this the best way to do so?  And is there a way to export more than 500 records at a time?  

### Describe the solution you'd like

A way to export all data, without checkin and checkout data to then reimport cleanly.  It's a one off, we would never need to do this again, but I can understand my boss's take.  It looks ugly with all the various imports to clean up the data.

### Describe alternatives you've considered

Going out behind the building and shooting myself for suggesting Snipe-IT?  Just kidding, they freaking love it already, just my boss is fairly anal about these things.

### Additional context

Big thanks! This is the second place of employment where I have been able to move them from Excel to Snipe-IT!

**Comment by ccj9874** [comment]
You can export asset information using the custom report and select all the fields you would want (this will export all of your assets), then delete all the assets and use the purge function to wipe deleted files and possibly the history? I can't verify that the purge deletes the history and I'm not going to test it on mine haha. You'll have to enable the purge option in the .env

**Comment by nastybutler** [comment]
OK, if anyone stumbles on this thread and wants to do the same thing I was hoping to do, just access the database and truncate the action_logs table.  It leaves all assets intact, who its assigned to - it just clears the item history. 

Confirmed everything is working as intended afterward.  Make sure you backup before you do it, because that's just good sense!
