### ISSUE TITLE
Sort by number 

### ISSUE THREAD

**Issue by karoliskralis** [grokability/snipe-it#11634]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

when i want to sort assets with my custom field with format Numeric, it doesnt sort from largest to smallest, it  sort from 9-1 but if exist number 10,11,12, it sort in front of  number 1,  

### Reproduction steps

1.Asset model
2. Sort by Custom field
3.
...

### Expected behavior

Sorting the  count number from largest to smallest

### Screenshots

![custom_field](https://user-images.githubusercontent.com/105273892/183571791-a6fc80ef-308a-4101-b2aa-c9142df26d49.PNG)

### Snipe-IT Version

6.09

### Operating System

Ubuntu

### Web Server

Apache 

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Google Chrome

### Version

103

**Comment by snipe** [comment]
This is an open ask and we have internal tickets around it. Unfortunately, it's a little harder than it seems. :(

**Comment by karoliskralis** [comment]
ok, thanks for reply, i try to import with number 01,02,03,... but it doesnt apply it, but when i edit 1 by 1 but number 01,02, ... it sorts OK.

**Comment by SufiSR** [comment]
I have the same problem - I had implemented a custom fieldset PC specification including a benchmark for CPUs (as we have AMD and Intel) for comparison :/ Hope you'll find a way to sort this out!

**Comment by BarisKaragoz** [comment]
Any update on this issue?

**Comment by koelle25** [comment]
That would be such an awesome feature!

In my case I would want to be able to:
1. Sort CPUs/GPUs by their performance
2. Sort network devices by their number of interfaces

Here is an example for 2) how it is looking currently:
![Custom Field Definition](https://github.com/user-attachments/assets/cde5355c-c903-4ee1-acd0-9a7184adb287)
![Column (incorrectly) sorted by the custom field](https://github.com/user-attachments/assets/628306e6-ed3a-4d81-aebc-294acf4df807)
