### ISSUE TITLE
Import CSV unable to delete

### ISSUE THREAD

**Issue by Nitz992** [grokability/snipe-it#11637]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We can able to import csv but we cannot able to delete it. its giving red solid box only no any error message. Browser throw 405:
Failed to load resource: the server responded with a status of 405 ()
DELETE https://assets.elite-co.com/api/v1/imports/4 405
Following verbs added in Handler mapping.
GET,HEAD,POST,DELETE,PUT,PATCH

In db we can able to see the records of import file. Uploaded Files are getting stored in MyProject\storage\private_uploads\imports

### Reproduction steps

I don't have any idea for to reproduce it. 

### Expected behavior

...

### Screenshots

![image](https://user-images.githubusercontent.com/97659510/183639147-cc02bcd7-db5a-4bb2-8903-8b9b975e9112.png)
![image](https://user-images.githubusercontent.com/97659510/183642496-4232217d-3f6e-4418-b617-092e70d14859.png)

https://user-images.githubusercontent.com/97659510/183642623-fd87bcab-bae0-4d1e-8e38-42d445b94c5e.mp4

### Snipe-IT Version

 Version v6.0.8 - build 8409 (master)

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.30

### Operating System

Windows

### Browser

Google Chrome

### Version

104.0.5112.81 (Official Build) (64-bit)

### Error messages

```shell
I didn't find error message in this regards.
```

### Additional context

1. Windows 2019 IIS.
2. MySql 
3. No manually edit in db
4. at the time of 1st setup mixed content message in browser (https://abc.xyz.com) .env APP_URL: https://abc.xyz.com APP_FORCE_TLS= TRUE but i was getting error of URL mismatched. 
5. App_URL removed from .env and kept blank with force_tls=false
6. IIS binding locally
7. setup completed
8. after that added https://abc.xyz.com

**Comment by snipe** [comment]
Was it literally set as `APP_FORCE_TLS= TRUE` (with a space) or `APP_FORCE_TLS=TRUE`?

**Comment by Nitz992** [comment]
@snipe i rechecked the parameters its without space. Following parameters:

 ![image](https://user-images.githubusercontent.com/97659510/184062990-7d0a26c6-8280-474e-b5f3-464a98afc726.jpeg)

**Comment by snipe** [comment]
You definitely don't want any blanks in there - if you don't intend to use a value, use `null`, for example, `GOOGLE_MAPS_API=null`

**Comment by Nitz992** [comment]
@snipe i remove the blanks and use value as `null`
clear the project cached by following command in project dir but still same issue
php artisan cache:clear
php artisan config:clear


![image](https://user-images.githubusercontent.com/97659510/184067184-5eefc6c7-087b-4503-b5b8-950419ac19aa.png)
