### ISSUE TITLE
404 not found on Apache 2

### ISSUE THREAD

**Issue by aisyahkarina** [grokability/snipe-it#11633]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

![photo_2022-08-09_08-34-56](https://user-images.githubusercontent.com/89247987/183537647-30318757-b786-4485-b5f6-005690546692.jpg)

Only the homepage works, but when i click other buttons, this error pops up. How do i fix this? Please help. Thank you

### Reproduction steps

I click on the buttons

### Expected behavior

I will be redirected to other features of the site

### Snipe-IT Version

v6.0.8

### Operating System

Windows

### Web Server

Apache

### PHP Version

7.4

**Comment by snipe** [comment]
My guess would be that your document root or htaccess is wrong. You must set the DOCUMENT_ROOT to the public directory in your apache configuration. If that's already set, you can try taking the htaccess from this PR: https://github.com/snipe/snipe-it/pull/11072

**Comment by aisyahkarina** [comment]
Sorry, I dont understand how to do that

**Comment by jjmpsp** [comment]
Is apache configured with AllowOverride rules?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
