### ISSUE TITLE
Uncaught ErrorException after fresh docker setup

### ISSUE THREAD

**Issue by eliteaz** [grokability/snipe-it#11644]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After fully successful docker-compose setup
Apache error log throws such an php error
`[Tue Aug 09 12:55:47.304955 2022] [php7:error] [pid 29] [client 10.89.2.8:43946] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents()\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\\Cache\\FileStore->put()\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\\Cache\\FileStore->forever()\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): Illuminate\\Cache\\Repository->forever()\n#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheMana in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 187
`

### Reproduction steps

1.  Tried to 'chmod 777 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php'
```
ls -la /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/
total 84
drwxrwxrwx    1 apache   apache        4096 Aug  9 10:45 .
drwxrwxrwx    1 apache   apache        4096 Aug  9 10:45 ..
-rw-r--r--    1 apache   apache        1409 Aug  9 10:45 Cache.php
-rwxrwxrwx    1 apache   apache       18379 Aug  9 10:45 Filesystem.php
-rw-r--r--    1 apache   apache       22661 Aug  9 10:45 FilesystemAdapter.php
-rw-r--r--    1 apache   apache       10242 Aug  9 10:45 FilesystemManager.php
-rw-r--r--    1 apache   apache        1746 Aug  9 10:45 FilesystemServiceProvider.php
-rw-r--r--    1 apache   apache        1075 Aug  9 10:45 LICENSE.md
-rw-r--r--    1 apache   apache        3807 Aug  9 10:45 LockableFile.php
-rw-r--r--    1 apache   apache        1746 Aug  9 10:45 composer.json
```

### Expected behavior

hope not to get apache 500 error

### Snipe-IT Version

latest

### Operating System

host CentOS Stream 9, container Alpine Linux v3.14

### Web Server

Apache

### PHP Version

PHP 7.4.26

**Comment by snipe** [comment]
That looks like a permissions issue - can you help, @uberbrady?

**Comment by uberbrady** [comment]
You can certainly try and twiddle the perms on `/var/www/html/storage/framework/cache/` - that seems to be the directory with the wonky perms. If you find a config that works for you, please let us know and maybe we can tweak the `Dockerfile.alpine` file - though, ideally, we'd love it if you could give us a PR with your recommended fix. But, if for whatever reason you can't, I'd be happy to listen to your permissions tweaks that worked for you, and make sure those get reflected in either the Dockerfile or in the docker-compose file - either way.

**Comment by eliteaz** [comment]
thanks @uberbrady 
seems this helped 
`chmod 757 /var/www/html/storage/framework/cache/cf -R`
but why `/var/www/html/storage/framework/cache/cf/` directory and subdirectories is under root **owner** and **group** ?
```
ls -la /var/www/html/storage/framework/cache/cf/
total 12
drwxr-xrwx    3 root     root          4096 Aug  9 10:46 .
drwxr-xr-x    1 apache   apache        4096 Aug  9 10:46 ..
drwxr-xrwx    2 root     root          4096 Aug 11 08:03 90
```
which service is responsible for `cache` directory creation ?
