### ISSUE TITLE
Config mail office 365 not worked 

### ISSUE THREAD

**Issue by Lahm290396** [grokability/snipe-it#11643]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Email not send and don't show error in log file

![image](https://user-images.githubusercontent.com/106590294/183819484-766099ad-2882-44c2-93e3-839740dfc4a1.png)

### Reproduction steps
![image](https://user-images.githubusercontent.com/106590294/183819509-b5db0d74-ab63-400d-bf29-9a9959e824b5.png)

### Expected behavior

I want to send email via office 365 successfully on snipeit

### Screenshots
![image](https://user-images.githubusercontent.com/106590294/183819519-d31f4f46-e79e-480b-ba02-4b1c1fb5cb06.png)
![image](https://user-images.githubusercontent.com/106590294/183819536-a3e76819-a19d-485c-abf0-b40197fab7b7.png)
![image](https://user-images.githubusercontent.com/106590294/183819551-b3971bbf-3833-4dac-ab76-6ae629a01101.png)
![image](https://user-images.githubusercontent.com/106590294/183819560-127130ac-9329-4382-b381-c2d325b5457a.png)
![image](https://user-images.githubusercontent.com/106590294/183819566-6d97b1ec-655c-4875-bbe2-8ea9b91036fd.png)

### Snipe-IT Version

v6.0.9 build 8515 (g51f729872)

### Operating System

Ubuntu 20.04

### Web Server

Apache2

### PHP Version

7.4.3

### Operating System

Windows 10 Pro

### Browser

Google Chrome

### Version

Version 104.0.5112.81 (Official Build) (64-bit)

### Error messages

```shell
No anything log show
```

**Comment by Saad-Samba** [comment]
+1

**Comment by Lahm290396** [comment]
> +1

What +1??

**Comment by Asyraf777** [comment]
Hi,

last time i got this issue, the issue is because office 365, you need to go to your 

office.com-->you account-->view account-->Security info-->add sign in method-->add methods--app password-->create

then copy the password and paste it in the .env config.

![image](https://user-images.githubusercontent.com/36369195/184050648-a63c1d04-e3eb-484a-9dc4-9cc9904e6e41.png)

then save and restart

hope this help

**Comment by Lahm290396** [comment]
> Hi,
> 
> last time i got this issue, the issue is because office 365, you need to go to your
> 
> office.com-->you account-->view account-->Security info-->add sign in method-->add methods--app password-->create
> 
> then copy the password and paste it in the .env config.
> 
> ![image](https://user-images.githubusercontent.com/36369195/184050648-a63c1d04-e3eb-484a-9dc4-9cc9904e6e41.png)
> 
> then save and restart
> 
> hope this help

Hi. Thank you for supporting.
I do it, but not function "app password" in "add sign in method"
![image](https://user-images.githubusercontent.com/106590294/184053401-f9071838-d067-4194-8e7e-2e59bda4b37b.png)

**Comment by Asyraf777** [comment]
HI,

Can try to follow this issue here

https://support.microsoft.com/en-us/account-billing/manage-app-passwords-for-two-step-verification-d6dc8c6d-4bf7-4851-ad95-6d07799387e9



<blockquote><div><strong><a href="https://support.microsoft.com/en-us/account-billing/manage-app-passwords-for-two-step-verification-d6dc8c6d-4bf7-4851-ad95-6d07799387e9">Manage app passwords for two-step verification</a></strong></div></blockquote>

**Comment by Lahm290396** [comment]
> HI,
> 
> Can try to follow this issue here
> 
> https://support.microsoft.com/en-us/account-billing/manage-app-passwords-for-two-step-verification-d6dc8c6d-4bf7-4851-ad95-6d07799387e9
> 
> > **[Manage app passwords for two-step verification](https://support.microsoft.com/en-us/account-billing/manage-app-passwords-for-two-step-verification-d6dc8c6d-4bf7-4851-ad95-6d07799387e9)**

I try to it, but i don't seen anything app password, i just seen authenticator app. I'm using Microsoft 365 account my company

<blockquote><div><strong><a href="https://support.microsoft.com/en-us/account-billing/manage-app-passwords-for-two-step-verification-d6dc8c6d-4bf7-4851-ad95-6d07799387e9">Manage app passwords for two-step verification</a></strong></div></blockquote>

**Comment by Asyraf777** [comment]
you need to check the admin configuration

https://www.codetwo.com/admins-blog/cannot-create-app-password-office-365/

<blockquote><img src="https://www.codetwo.com/admins-blog/wp-content/uploads/2020/12/Cannot-create-app-password-in-Office-365_OG.png" width="48" align="right"><div>Microsoft 365 & Exchange Admin's Blog</div><div><strong><a href="https://www.codetwo.com/admins-blog/cannot-create-app-password-office-365/">Troubleshooting: Cannot create app password in Office 365</a></strong></div><div>If users cannot create app passwords in Microsoft 365 (Office 365) after enabling MFA, this article shows how to fix this issue.</div></blockquote>

**Comment by Lahm290396** [comment]
> you need to check the admin configuration
> 
> https://www.codetwo.com/admins-blog/cannot-create-app-password-office-365/
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/ebaa70ce5489ceefc3cfb34aeb5ec1d62fb820624601ae38a165c6aa8153c691/68747470733a2f2f7777772e636f646574776f2e636f6d2f61646d696e732d626c6f672f77702d636f6e74656e742f75706c6f6164732f323032302f31322f43616e6e6f742d6372656174652d6170702d70617373776f72642d696e2d4f66666963652d3336355f4f472e706e67">Microsoft 365 & Exchange Admin's Blog**[Troubleshooting: Cannot create app password in Office 365](https://www.codetwo.com/admins-blog/cannot-create-app-password-office-365/)**If users cannot create app passwords in Microsoft 365 (Office 365) after enabling MFA, this article shows how to fix this issue.

Hi, thank you for supporting. I created app password and pass to configuration .env, but its not activities, no error in log file lavarel. The request still appear "error 500 Internal Server"
![image](https://user-images.githubusercontent.com/106590294/184076775-c29681e1-d76f-4e28-b33d-33ce7245fbc1.png)

![image](https://user-images.githubusercontent.com/106590294/184076801-617c874e-38ac-4099-add2-6a08c2b52029.png)
![image](https://user-images.githubusercontent.com/106590294/184076966-6040c671-9860-4f7f-b6f7-690ceb0375bd.png)



<blockquote><img src="https://www.codetwo.com/admins-blog/wp-content/uploads/2020/12/Cannot-create-app-password-in-Office-365_OG.png" width="48" align="right"><div>Microsoft 365 & Exchange Admin's Blog</div><div><strong><a href="https://www.codetwo.com/admins-blog/cannot-create-app-password-office-365/">Troubleshooting: Cannot create app password in Office 365</a></strong></div><div>If users cannot create app passwords in Microsoft 365 (Office 365) after enabling MFA, this article shows how to fix this issue.</div></blockquote>

**Comment by Asyraf777** [comment]
here is my config,

![image](https://user-images.githubusercontent.com/36369195/184085347-aa8fc8ec-7ecd-4591-b229-84f0ffc0f071.png)

**Comment by Lahm290396** [comment]
> here is my config,
> 
> ![image](https://user-images.githubusercontent.com/36369195/184085347-aa8fc8ec-7ecd-4591-b229-84f0ffc0f071.png)

hi, please show your config again and don't show password email. I want to seen some characters, such as ''. Please.

**Comment by Asyraf777** [comment]
Hi,

kindly refer this

![image](https://user-images.githubusercontent.com/36369195/184265764-36186b01-8be9-45c9-b6eb-6bee7c375fcf.png)

**Comment by Lahm290396** [comment]
> Hi,
> 
> kindly refer this
> 
> ![image](https://user-images.githubusercontent.com/36369195/184265764-36186b01-8be9-45c9-b6eb-6bee7c375fcf.png)

hello morrning
I was config below but its not work, i change from mail office 365 to gmail, and i also use app password for email, so sad its not work

**Comment by Asyraf777** [comment]
you should check the encryption type as well for your organization

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by tleshotho** [comment]
Hi, I am having the same issue where if I configure using a Microsoft 365 account, it won't send emails, I can only use Gmail because I can create app passwords but involving a third party email service is a problem, has this issue been resolved or are there any steps to get it right?
