### ISSUE TITLE
User Permissions[Feature Request]: Scope user/asset visibility by location

### ISSUE THREAD

**Issue by brianhoganm** [grokability/snipe-it#11654]
### Is your feature request related to a problem? Please describe.

Yes. I am unable to follow the article (link below)

I have tried creating the _FlorbPolicy_ example and I am not understanding this at all.  

I want allow users to view assets only in their location. I was hopeful that by following your example, I would be able to accomplish this by using locations.

https://snipe-it.readme.io/docs/user-permissions 

Can someone tell me if this is even possible?

### Describe the solution you'd like

I would like to see a more detailed article with an easier example.

https://snipe-it.readme.io/docs/user-permissions

### Describe alternatives you've considered

The way I could accomplish this is by create like 30+ companies and assigning the asset to the companies and all of the users.

Ideally, it would be a great feature to add in Snipe-IT version 7 , but if I can edit code now, that would be great!

If this feature on the roadmap?

**Comment by snipe** [comment]
Policies aren't really the way you'll need to go here - this is far more complicated and would require something more like the scoping we use for `Companyable`.

**Comment by brianhoganm** [comment]
Thanks for letting me know.
