### ISSUE TITLE
Cannot change next auto increment

### ISSUE THREAD

**Issue by BasO12** [grokability/snipe-it#11657]
### Debug mode

- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
- [X] I have enabled debug mode

### Describe the bug

I can no longer change the next auto increment (whenever I hit save it will just go back to the value it already was), and whenever I create an asset it will use a tag that's already in use.

### Reproduction steps

1.Go to settings/asset tags
2.change the next auto increment
3.hit save
4.check the page again to see if your changes actually have been saved
...

### Expected behavior

The value of the auto increment to change

### Snipe-IT Version

6.0.9

### Operating System

Debian 10

### Web Server

Apache

### PHP Version

7.4.30

### Operating System

Windows

### Browser

Chrome

### Version

104.0.5112.81

**Comment by inietov** [comment]
I can't reproduce in my local instance, and checking at the code I don't see anything that could cause the behavior you are seeing. Can you maybe give us more details? How your other settings look, if you made some kind of reordering that cause you the need to edit the nex auto increment number?

**Comment by BasO12** [comment]
Here's the settings page for my auto incrementing assets:
![Screenshot 2022-08-25 083507](https://user-images.githubusercontent.com/94169344/186592347-54ad9b5f-524a-40dd-812b-1b0379aa1acc.png)


And here is the code for asset tag page:
[asset_tags.blade.php.txt](https://github.com/snipe/snipe-it/files/9422067/asset_tags.blade.php.txt)

I would like to add that in the database it does correctly display the next auto increment, however this does not translate to the app itself because every new asset we create starts with 19613

**Comment by BasO12** [comment]
Some additional info that might be helpful
![Screenshot 2022-08-25 100759](https://user-images.githubusercontent.com/94169344/186611139-c7d5400d-bed9-4180-9d58-50f30f41525d.png)
:

**Comment by sembeek** [comment]
I'm having the same problem, it appeared right after the upgrade to 6.0.9, 6.0.10 did not fix this issue for me.

**Comment by BasO12** [comment]
I seem to have found the source of the issue.
Somehow the folder /snipe-it/storage/framework/cache/cf had the owner and group set to root, I changed it back to the user that we use for snipe and after a reboot the asset increment worked as expected (I checked the file contents, and found a file that contains "cached" settings for the auto increment).
