### ISSUE TITLE
Not loading logo and QR code

### ISSUE THREAD

**Issue by harisankar9692** [grokability/snipe-it#11674]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Not able to load the logo, QR code, and Bar code as well, did not find anything in debug mode

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Logo should load in login screen and barcode and QR code should appear

### Snipe-IT Version

6.0.9

### Operating System

Windows 10 x64 21H2

### Web Server

IIS

### PHP Version

7.4.30

### Operating System

Windows 10 x64 21H2

### Browser

Brave

### Version

1.42.88

### Error messages

```shell
not getting error
```

**Comment by harisankar9692** [comment]
Please help me

**Comment by yusuf-basith** [comment]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/106800919/184678168-ab529d1f-a384-43b1-9f79-a89d04b17699.png">
Hello,
Please make sure that your APP_URL value in the env file is http://183.83.180.214:99

**Comment by harisankar9692** [comment]
Thank you first of all. But still issues with QR and Bar code

**Comment by yusuf-basith** [comment]
Please try the steps described here https://snipe-it.readme.io/docs/barcodes#changing-your-url

What is the cause of this problem? An upgrade, migration from a different location, etc...

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/barcodes#changing-your-url">Barcodes</a></strong></div><div>Snipe-IT supports both QR codes and 1D barcode formats. QR codes, when scanned on a mobile device using a QR scanner app, will open the asset details page of the asset whose QR code was scanned. You can select between a few different 1D barcode formats, however barcode generation will fail if your a...</div></blockquote>

**Comment by snipe** [comment]
My guess would be that your `APP_URL` is misconfigured in your `.env` file. [Per the documentation](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings), the APP_URL should be the complete URL to your Snipe-IT installation, *including* the `http://` (or `https://` if you're running over TLS.)

<img width="795" alt="Screen Shot 2022-07-28 at 11 35 47 PM" src="https://user-images.githubusercontent.com/197404/181698021-de470225-4865-4786-bd48-9a9cdf2399d2.png">

**Comment by harisankar9692** [comment]
Still not accessible,
![image](https://user-images.githubusercontent.com/61540761/184683082-ff691a3c-c13c-4ea8-b388-259875afe9d9.png)
![image](https://user-images.githubusercontent.com/61540761/184683117-916357d0-8309-4f29-9b8f-88f4cc95d7fa.png)
APP_URL=http://localhost:89/

**Comment by yusuf-basith** [comment]
Now the logo appears on the login screen.
Can you check the source URL of the QR code image?

**Comment by harisankar9692** [comment]
<img src="http://localhost:89//hardware/91/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;" alt="QR code for  (KHG-IT-000091) - Blaze 4">

**Comment by harisankar9692** [comment]
img src="http://localhost:89//hardware/91/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;" alt="QR code for  (KHG-IT-000091) - Blaze 4"

**Comment by yusuf-basith** [comment]
Please remove the last slash "/" from the APP_URL in the ENV file.

Make it like APP_URL=http://localhost:89

**Comment by harisankar9692** [comment]
Thank You!! @yusuf-basith

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
