### ISSUE TITLE
"People" page shows No Records Found 

### ISSUE THREAD

**Issue by sylphaxiom** [grokability/snipe-it#11678]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I attempt to view the "people" page, no records are found. I know they are still there since you can still view the data in the database directly from the server, and the people who have devices checked out still show up, and the dashboard shows the user count. However it's just the User's page where no users show up. I have the same issue with the Groups page too. During investigation, it looks like there may have been an issue when I last upgraded the app to 6.0.9 as there was an error when migrating the database. 
![image](https://user-images.githubusercontent.com/35042829/184691867-459920df-3340-4b6c-b756-4b9720fa8314.png)

### Reproduction steps

1. Login
2. Click "People"
3.
...

### Expected behavior

I should expect to see the user list populated, but I don't.

### Screenshots

![image](https://user-images.githubusercontent.com/35042829/184692014-4c9f72ac-7cb4-43e7-8c82-bc5f8aaaf664.png)
![image](https://user-images.githubusercontent.com/35042829/184692108-643d2452-4a43-4579-b613-883216e60443.png)
![image](https://user-images.githubusercontent.com/35042829/184692684-ed2ae60e-4eb4-46cd-bc06-142146f5953f.png)
![image](https://user-images.githubusercontent.com/35042829/184693511-35d45c93-9cd6-425b-82a8-955eeb9eac02.png)
![image](https://user-images.githubusercontent.com/35042829/184693849-b9300067-2f6c-4dcd-a199-dca5a7a61df1.png)

### Snipe-IT Version

6.0.9

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows 10

### Browser

Edge

### Version

Current

**Comment by snipe** [comment]
This is covered in the docs https://snipe-it.readme.io/docs/installation-issues#sqlstate42000-syntax-error-or-access-violation-1118-row-size-too-large

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#sqlstate42000-syntax-error-or-access-violation-1118-row-size-too-large">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by sylphaxiom** [comment]
Thank you. My apologies for missing this in the article.

**Comment by snipe** [comment]
No worries :)
