### ISSUE TITLE
Can't disable Snipe-IT talking to Gravatar

### ISSUE THREAD

**Issue by CrtiUser** [grokability/snipe-it#11677]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Snipe-IT is fetching Avatar from Gravatar.

I followed the steps described in https://github.com/snipe/snipe-it/issues/9352 
but my installation still fetches Gravatar icons.

I blocked Gravatar and can see that there are requests for user icons.

### Reproduction steps

1. Set load_remote = 0 in .env
2. Updated database -> UPDATE settings SET load_remote=0;
3. Cleared config cache, restarted server
...

### Expected behavior

Snipe-IT should stop loading data/files from outside sources.

### Snipe-IT Version

6.0.9

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Edge

**Comment by snipe** [comment]
The code literally checks for that setting though:

```php
    public function gravatar()
    {
        if ($this->avatar) {
            return Storage::disk('public')->url('avatars/'.e($this->avatar));
        }

        if (Setting::getSettings()->load_remote == '1') {
            if ($this->model->gravatar != '') {
                $gravatar = md5(strtolower(trim($this->model->gravatar)));

                return '//gravatar.com/avatar/'.$gravatar;
            } elseif ($this->email != '') {
                $gravatar = md5(strtolower(trim($this->email)));

                return '//gravatar.com/avatar/'.$gravatar;
            }
        }

        // Set a fun, gender-neutral default icon
        return url('/').'/img/default-sm.png';
    }
```

I cannot reproduce this locally. Please make sure that `load_remote=0` in your `settings` table and re-run:

```
php artisan config:clear
php artisan cache:clear
```

**Comment by snipe** [comment]
Side question: why do you need/want to block gravatar?

**Comment by CrtiUser** [comment]
Hi, sorry, was busy ...
I want to block gravatar because I'n not sure which information out of my database will be shared with gravatar. I noticed that some user icons are loaded from Gravatar (I'm not familiar with the function) and was afraid if there is a kind of "dataleak".

I've set the table value and also in the .env but I still see communication from my client to gravatar in the firewall.
