### ISSUE TITLE
[Feature Request]: Lock the header row 

### ISSUE THREAD

**Issue by tjeyamd** [grokability/snipe-it#11670]
### Is your feature request related to a problem? Please describe.

Hello. The header row disappears when you scroll down the page to view more rows. If you have a lot of columns you have to go all the way up to the header, move to the right column then move down to the right row. 

### Describe the solution you'd like

Solution would be to lock the top header row so that it is available on the top as you scroll down the page to view more rows. 

 

### Describe alternatives you've considered

To build on the feature request would be the ability to lock a column like "Name" so that it is available on the left as you scroll right to view more columns just so that you don't need to keep track of the row as you scroll further left.

**Comment by brokensyntax** [comment]
I would love this feature. Not sure if its a CSS3 or HTML5 thing, but locking the table as an iFrame and making the columns interactively draggable from the header I think would achieve this. Maybe not the best way?
WebUI folk far more skilled than me out there will know 😁

**Comment by yusuf-basith** [comment]
There is already [PR#11318](https://github.com/snipe/snipe-it/pull/11318) in progress.

**Comment by snipe** [comment]
It cannot be merged as is. There is a bug in the library.
