### ISSUE TITLE
Backup Restore: Too Many Arguments, Expected Arguments "Command".

### ISSUE THREAD

**Issue by BobDobbs4242** [grokability/snipe-it#11687]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to use 

`php artisan snipeit:restore /temp/snipe-it-insertdate.zip`

I get the error:

**Too many arguments, expected arguments "command".**

the file exists, its got read/write permission for root and I am logged in as root. 

I have also tried extracting and importing the sql file, which comes up with the same result.

### Reproduction steps

1.  Run above command
2. get the same result every time

### Expected behavior

That it will import the database.

### Screenshots

No Screenshots

### Snipe-IT Version

5.1.5 build 6029

### Operating System

Linux (using the ISO)

### Web Server

Apache

### PHP Version

7.3

### Operating System

WIndows 10

### Browser

Chrome

### Version

Latest

### Additional context

Fresh install, Snipe-IT Iso from the website.

**Comment by snipe** [comment]
> Snipe-IT Version - 5.1.5 build 6029

That version is very old. Please try upgrading.
