### ISSUE TITLE
Unable to encode attribute [header_row] for model ... to JSON: Malformed UTF-8 characters, possibly incorrectly encoded.

### ISSUE THREAD

**Issue by KiYiul** [grokability/snipe-it#11684]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

# Environment 
 v6.0.9 - build 8515 (master)

# laravel.log log
[2022-08-16 14:17:11] production.ERROR: Illuminate\Database\Eloquent\JsonEncodingException: Unable to encode attribute [header_row] for model [App\Models\Import] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded. in /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/JsonEncodingException.php:47
Stack trace:
#0 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1168): Illuminate\Database\Eloquent\JsonEncodingException::forAttribute()
#1 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(935): Illuminate\Database\Eloquent\Model->castAttributeAsJson()
#2 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2041): Illuminate\Database\Eloquent\Model->setAttribute()
#3 /data/apps/snipe-it/app/Http/Controllers/Api/ImportController.php(67): Illuminate\Database\Eloquent\Model->__set()
#4 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Api\ImportController->store()
#5 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#6 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch()
#7 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#8 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Route->run()
#9 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

### Reproduction steps

1. import csv file to using Import menu
2. import process bar color turn orange to red. and I can found some bug log in laravel.log file.

### Expected behavior

I want to import the csv file include UTF-8 character

### Snipe-IT Version

6.0.9

### Operating System

RockyOS 8.6

### Web Server

Apache

### PHP Version

8.1.7

### Operating System

Windows 10

### Browser

Google Chrome

### Version

104.0.5112.81

### Error messages

```shell
# laravel.log log
[2022-08-16 14:17:11] production.ERROR: Illuminate\Database\Eloquent\JsonEncodingException: Unable to encode attribute [header_row] for model [App\Models\Import] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded. in /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/JsonEncodingException.php:47
Stack trace:
#0 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1168): Illuminate\Database\Eloquent\JsonEncodingException::forAttribute()
#1 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(935): Illuminate\Database\Eloquent\Model->castAttributeAsJson()
#2 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2041): Illuminate\Database\Eloquent\Model->setAttribute()
#3 /data/apps/snipe-it/app/Http/Controllers/Api/ImportController.php(67): Illuminate\Database\Eloquent\Model->__set()
#4 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Api\ImportController->store()
#5 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#6 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch()
#7 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#8 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Route->run()
#9 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /data/apps/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
```

**Comment by KiYiul** [comment]
I used below 3 row csv file to import asset.

___

```
ID,Company,Asset Name,Asset Tag,Model,Model No.,Category,Manufacturer,Serial,Purchased,Cost,EOL,Order Number,Supplier,Location,Address,Address,City,State,Country,Zip,Default Location,Address,Address,City,State,Country,Zip,Checked Out,Type,Username,Employee No.,Manager,Department,Title,Status,Warranty,Warranty Expires,Value,Diff,Fully Depreciated,Checkout Date,Expected Checkin Date,Created At,Updated at,Deleted,Last Audit,Next Audit Date,Notes,URL,OS,DBMS,WEB,WAS,App,IoT,URL,서비스_중분류,서비스_소분류,서비스_설명,Hostname,IP_외부,IP_내부,중요도평가_기밀성,중요도평가_무결성,중요도평가_가용성,중요도평가_등급,설치위치,서버_Type,서버_Model,OS_Version,OS_담당부서,OS_담당자,OS_관리자,DBMS_Version,DBMS_담당부서,DBMS_담당자,DBMS_관리자,WEB/WAS_Version,WEB/WAS_담당부서,WEB/WAS_담당자,WEB/WAS_관리자,EQSTVM_설치여부,EQSTVM_Hostname,EQSTVM_설치IP,EQSTVM_추가모듈설치필요사항,EQSTVM_추가자산식별대상,ISMS인증 대상여부,백신_설치여부,백신_제품명
3,OK쉴더스,O가드,O가드_0610,Server Infra,,Server Infra,,,,,,,,,,,,,,,,,,,,,,,,,,,,,운영중 (deployable),,,,0,,,,2022-08-12 19:35,2022-08-12 21:44,,,,,-,,,,,,,O가드 DDNS 서비스,O가드 DDNS 서비스,O가드1 DDNS 서비스 02,-,1.1.1.1,,3,3,3,가,Microsoft Azure,Cloud IaaS,,2012,IT인프라팀,OOO,OOO,,,,,,,,,,,,,,O,O,TrendMicro Deep Security
4,OK쉴더스,O가드,O가드_0661,Server Infra,,Server Infra,,,,,,,,,,,,,,,,,,,,,,,,,,,,,운영중 (deployable),,,,0,,,,2022-08-12 21:11,2022-08-12 21:27,,,,,-,Windows,MSSQL,,,,,,통합 O가드 서비스,통합 O가드 서비스,통합O가드 Web DB_Active,WebDB(.86)_WIN2012VM64,1.1.1.1,,3,3,3,가,OODC,On-premise VM,,2012,OOO팀,OOO,OOO,2012,OOO개발팀,OOO,OOO,,,,,,,,,,O,O,AhnLab V3.Net
,OK쉴더스,공통 인프라(OOO),공통 인프라(OOO)_1,Server Infra,,Server Infra,,,,,,,,,,,,,,,,,,,,,,,,,,,,,운영중 (deployable),,,,,,,,,,,,,,,Linux,-,-,-,,,,인증-대내서비스,대내,"OOO 운영 DB, DB암호화",-,61.97.12.23,-,3,3,3,가,DDC,VM,,,OOO담당,OOO,OOO,-,-,-,-,-,-,-,-,설치 완료,hostname,1.1.1.1,,"Oracle, Tomcat 신규 식별",O,O,
```

**Comment by KiYiul** [comment]
Hello, @inietov 
May I know how to flow that issue currently?

**Comment by snipe** [comment]
IIRC, we have a fix for this out on develop. (The character/json encoding - we can't really fix bad data - there are two Address Columns, etc)
