### ISSUE TITLE
[Feature Request]: MAC address field

### ISSUE THREAD

**Issue by jeonghanlee** [grokability/snipe-it#11693]
### Is your feature request related to a problem? Please describe.

We use a typical scanner to enter the MAC addresses of each network device through a web interface. The MAC field of each Asset forces to use strictly `AA:AA:AA:AA:AA:AA` form. Some device doesn't have that format, for example, AAAAAAAAAAAA, through their barcode. We have to modify its mac address manually.

### Describe the solution you'd like

It could be really good and efficient to enable and disable that MAC address strick check rule through a web interface.

**Comment by jeonghanlee** [comment]
Oh, we found the option to disable this feature. Thanks!

**Comment by cTurtle98** [comment]
where is the option to disable requiring the colons? I cant find it

**Comment by jeonghanlee** [comment]
> where is the option to disable requiring the colons? I cant find it

One should select "Format" as "ANY"

![Screenshot 2023-08-03 at 12 21 48 PM](https://github.com/snipe/snipe-it/assets/4479385/ce327b18-3865-49d2-8d32-8bf2c697712e)

**Comment by snipe** [comment]
Or update the regex
