### ISSUE TITLE
Admin ->General settings --  Error: Please check the form below for errors

### ISSUE THREAD

**Issue by aachandler-wcu** [grokability/snipe-it#11696]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to enable "Full Multiple Companies Support" and save the general settings in the admin panel I get an error at the top of the page that reads "Error: Please check the form below for errors" but there is no highlighting on the form like other forms where there are required fields. I have also added junk content to every text box and checked all boxed to get around the issue, but it persists.

I first noticed the issue when I was on version 4.9.4 (2020 build) so I upgraded via git and the error persists after a successful update to version 6.0.9

### Reproduction steps

1. Navigate to the admin panel and general settings
2. check the "Full Multiple Companies Support" checkbox
3. click the save button

### Expected behavior

"Full Multiple Companies Support" is enabled for the site

### Screenshots

![image](https://user-images.githubusercontent.com/91217808/185270939-b678c41c-7322-416f-bca7-fe52633e5e20.png)
![image](https://user-images.githubusercontent.com/91217808/185271012-6a21c210-6b32-4cf8-a5ad-f2f5c71051ab.png)

### Snipe-IT Version

v6.0.9 build 8515 

### Operating System

RHEL 7

### Web Server

apache

### PHP Version

7.4.30

### Error messages

```shell
No errors listed in browser console (chrome or firefox).
Not able to recreate in demo.
No errors related to anything other upgrade in storage/logs (upgrade errors are resolved).
php modules installed:
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

The error was present on the fresh install and persists after an upgrade.
Original install was done with install.sh on a RHEL 7 server.
The data on the server originally came from a Snipe-IT 3.x server using the backup tool, and was uploaded to the fresh install after the new server was configured. All other features seem to work without issues. I can add assets, users, and companies as well as change user permissions and check in and out assets without issue.

I have attempted changes suggested in issue number #8531 from 2020 (change CORS_ALLOWED_ORIGINS to "*" and creating a simlink between storage and uploads) but did not have any success.

If there are logs outside of storage/logs/laravel.log or /var/log/httpd/error_log that I can enable please let me know and I can provide them.

**Comment by snipe** [comment]
This usually happens because of something else in the settings that should have been updated long ago but didn't. I'd start by checking your password length in the Security settings. It should be set to at least 8, IIRC.

**Comment by aachandler-wcu** [comment]
Ok so I just checked and it is set to 8, I went to change it to 10 and actually got the same error as described previously. 
![image](https://user-images.githubusercontent.com/91217808/185469252-8b2fa5d1-d815-4e47-921d-cd34615c5218.png)

**Comment by snipe** [comment]
Go through each of the settings page, changing nothing, and saving - see if a form entry gets highlighted on one of them. (This is a validation error, I'm just not sure where)

**Comment by aachandler-wcu** [comment]
Oh fantastic that did it! In location, the currency field was not filled in (says it was defaulted to USD), but once I put in USD manually it saved. It looks like all settings are saving now.
Thanks so much!

**Comment by snipe** [comment]
Excellent - glad you're sorted :)
