### ISSUE TITLE
Admin options disappear

### ISSUE THREAD

**Issue by boring10** [grokability/snipe-it#11711]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Admin options disappear between a width of 768 and 991.

### Reproduction steps

1. Adjust the width of the page between 768 and 991

### Expected behavior

Show admin options

### Screenshots

![Peek 2022-08-21 08-48](https://user-images.githubusercontent.com/35600612/185791774-827f3da5-6cf0-4958-869a-5e97d94ceea4.gif)

### Snipe-IT Version

v6.0.9 build 8515 (g51f729872) 

### Operating System

Ubuntu Server 22.04

### Web Server

Apache

### PHP Version

8.1.2 

### Operating System

POP_OS!

### Browser

Firefox

### Version

103.0 (64-bit)

**Comment by Godmartinz** [comment]
I'm looking into this.
