### ISSUE TITLE
500 Server Error when opening specific assets

### ISSUE THREAD

**Issue by tamfadmin** [grokability/snipe-it#11722]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Whenever I am opening a certain assets, I receive a 500 server error.

### Reproduction steps

1.  Tried to open three other assets that was created at that time.  Experienced the same problem.
2.  Have opened other assets from that time and was able to do so without any problems.  Some of them have attached files.

### Expected behavior

Expect to be able to open the asset.  Then expect to be able to open the attached (files)...technically we would be downloading versus opening.

If there is going to be an issue with opening this asset because of the attached file issue, it would be great just to be able to open the asset.  We can live without the attachment.

### Screenshots

[asset-error.pdf](https://github.com/snipe/snipe-it/files/9417224/asset-error.pdf)

### Snipe-IT Version

6.09

### Operating System

Windows Server 2019 Standard

### Web Server

MySQL 5.5

### PHP Version

7.4.13

### Operating System

Windows Server 2019 Standard

### Browser

Microsoft Edge and Google Chrome

### Version

Version 104.0.1293.63 (Official build) (64-bit) and Version 104.0.5112.102 (Official Build) (64-bit)

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Version

N/A

### Error messages

```shell
INFORMATION FROM THE EDGE BROWSER:

APP_DEBUG is set to true while APP_ENV is not local

This could make your application vulnerable to remote execution. Read more about Ignition security.

C:\inetpub\wwwroot\snipeit\
ErrorException
filesize(): stat failed for C:\inetpub\wwwroot\snipeit\storage\private_uploads/assets/hardware-731-L4qfOba2-24portmoduleformdfpdf.pdf (View: C:\inetpub\wwwroot\snipeit\resources\views\hardware\view.blade.php)
http://assetmgmt.txamfoundation.com/hardware/731


**********************************************************************
Used the SnipeIT demo website to add and retrieve an asset, uploaded a file and not having any problems.  Then again, I'm not having problems with this for the majority of our assets on our website.

***********************************************************************
STACK TRACE INFORMATION IS BELOW:

Collapse vendor frames
76
C:\inetpub\wwwroot\snipeit\resources\views/hardware/view.blade.php
Illuminate\Foundation\Bootstrap\HandleExceptions
:1187

1 unknown frame
74
C:\inetpub\wwwroot\snipeit\resources\views/hardware/view.blade.php
:1187
73
Illuminate\Filesystem\Filesystem
:107
72
Illuminate\Filesystem\Filesystem
:108
71
Illuminate\View\Engines\PhpEngine
:58
70
Livewire\CompilerEngineForIgnition
:69
69
Illuminate\View\Engines\CompilerEngine
:61
68
Facade\Ignition\Views\Engines\CompilerEngine
:37
67
Livewire\CompilerEngineForIgnition
:35
66
Illuminate\View\View
:139
65
Illuminate\View\View
:122
64
Illuminate\View\View
:91
63
Illuminate\Http\Response
:69
62
Illuminate\Http\Response
:35
61
Illuminate\Routing\Router
:820
60
Illuminate\Routing\Router
:789
59
Illuminate\Routing\Router
:721
58
Illuminate\Pipeline\Pipeline
:128
57
Illuminate\Auth\Middleware\Authenticate
:44
56
Illuminate\Pipeline\Pipeline
:167
55
App\Http\Middleware\AssetCountForSidebar
:55
54
Illuminate\Pipeline\Pipeline
:167
53
Laravel\Passport\Http\Middleware\CreateFreshApiToken
:50
52
Illuminate\Pipeline\Pipeline
:167
51
App\Http\Middleware\CheckForTwoFactor
:59
50
Illuminate\Pipeline\Pipeline
:167
49
App\Http\Middleware\CheckUserIsActivated
:47
48
Illuminate\Pipeline\Pipeline
:167
47
App\Http\Middleware\CheckLocale
:37
46
Illuminate\Pipeline\Pipeline
:167
45
Illuminate\Foundation\Http\Middleware\VerifyCsrfToken
:78
44
Illuminate\Pipeline\Pipeline
:167
43
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse
:37
42
Illuminate\Pipeline\Pipeline
:167
41
Illuminate\Cookie\Middleware\EncryptCookies
:67
40
Illuminate\Pipeline\Pipeline
:167
39
Illuminate\Pipeline\Pipeline
:103
38
Illuminate\Routing\Router
:723
37
Illuminate\Routing\Router
:698
36
Illuminate\Routing\Router
:662
35
Illuminate\Routing\Router
:651
34
Illuminate\Foundation\Http\Kernel
:167
33
Illuminate\Pipeline\Pipeline
:128
32
Livewire\DisableBrowserCache
:19
31
Illuminate\Pipeline\Pipeline
:167
30
Barryvdh\Debugbar\Middleware\InjectDebugbar
:66
29
Illuminate\Pipeline\Pipeline
:167
28
Fruitcake\Cors\HandleCors
:38
27
Illuminate\Pipeline\Pipeline
:167
26
App\Http\Middleware\PreventBackHistory
:23
25
Illuminate\Pipeline\Pipeline
:167
24
App\Http\Middleware\SecurityHeaders
:26
23
Illuminate\Pipeline\Pipeline
:167
22
Illuminate\Foundation\Http\Middleware\TransformsRequest
:21
21
Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull
:31
20
Illuminate\Pipeline\Pipeline
:167
19
App\Http\Middleware\CheckForDebug
:25
18
Illuminate\Pipeline\Pipeline
:167
17
App\Http\Middleware\CheckForSetup
:25
16
Illuminate\Pipeline\Pipeline
:167
15
Fideloper\Proxy\TrustProxies
:57
14
Illuminate\Pipeline\Pipeline
:167
13
Illuminate\View\Middleware\ShareErrorsFromSession
:49
12
Illuminate\Pipeline\Pipeline
:167
11
Illuminate\Session\Middleware\StartSession
:121
10
Illuminate\Session\Middleware\StartSession
:64
9
Illuminate\Pipeline\Pipeline
:167
8
Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance
:86
7
Illuminate\Pipeline\Pipeline
:167
6
App\Http\Middleware\NoSessionStore
:28
5
Illuminate\Pipeline\Pipeline
:167
4
Illuminate\Pipeline\Pipeline
:103
3
Illuminate\Foundation\Http\Kernel
:142
2
Illuminate\Foundation\Http\Kernel
:111
1
:52
Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
C:\inetpub\wwwroot\snipeit\resources\views/hardware/view.blade.php:1187































                                        <tbody>


                                        @foreach ($asset->uploads as $file)

                                            <tr>

                                                <td><i class="{{ Helper::filetype_icon($file->filename) }} icon-med" aria-hidden="true"></i></td>

                                                <td>

                                                    @if ( Helper::checkUploadIsImage($file->get_src('assets')))

                                                        <a href="{{ route('show/assetfile', ['assetId' => $asset->id, 'fileId' =>$file->id]) }}" data-toggle="lightbox" data-type="image" data-title="{{ $file->filename }}" data-footer="{{ Helper::getFo

                                                            <img src="{{ route('show/assetfile', ['assetId' => $asset->id, 'fileId' =>$file->id]) }}" style="max-width: 50px;">

                                                        </a>

                                                    @endif

                                                </td>

                                                <td>

                                                    {{ $file->filename }}

                                                </td>

                                                <td data-value="{{ filesize(storage_path('private_uploads/assets/').$file->filename) }}">

                                                    {{ Helper::formatFilesizeUnits(filesize(storage_path('private_uploads/assets/').$file->filename)) }}

                                                </td>

                                                <td>

                                                    @if ($file->note)

                                                        {{ $file->note }}

                                                    @endif

                                                </td>

                                                <td>

                                                    @if ($file->filename)

                                                        <a href="{{ route('show/assetfile', [$asset->id, $file->id]) }}" class="btn btn-default">

                                                            <i class="fas fa-download" aria-hidden="true"></i>

                                                        </a>

                                                    @endif

                                                </td>

                                                <td>
```

### Additional context

The problem occurred before upgrading and we were on version 6.02.  Decided to go ahead and upgrade and the same problem exists.  We are now on version 6.09.

I followed the directory both that's in the browser error and note that the file that I'm trying to retrieved does not exist in the folder:  hardware-695-rlD25CIS-hp5406switchespdf.pdf).  I also not the subsequent folder does not exist:  c:\interpub\wwwroot\snipeit\resources\views\HARDWARE.  I am not sure why.

**Comment by snipe** [comment]
`c:\interpub\wwwroot\snipeit\resources\views\HARDWARE` isn't a valid directory, so I wouldn't expect to see it there. Do you know why the PDF file doesn't exist?

**Comment by snipe** [comment]
(`c:\interpub\wwwroot\snipeit\resources\views\hardware` is a valid directory, lowercase, though on windows that shouldn't matter)

**Comment by tamfadmin** [comment]
Hi,

I appreciate the quick response.

I do not know why the files for these four assets are not present.

Thanks,
Cameshia

Cameshia Cargle
Senior Systems Administrator

TEXAS A&M FOUNDATION
401 George Bush Drive
College Station, TX 77840
979.845.7906
"Where passion finds purpose" | txamfoundation.com<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.txamfoundation.com%2F%3Futm_source%3Demail-signature%26utm_campaign%3Dtamf-staff-email-signature%26utm_medium%3Demail&data=04%7C01%7Cccargle%40txamfoundation.com%7C2425439be5d04dffa07208d9f6deb40a%7C7b770f8e0b124bc2a6bf1b8d8ea5d18a%7C1%7C0%7C637812258645308759%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fkLjF90ZntKEWs2EnSuRiHBr3lv%2BAqgamEF4PeWCGic%3D&reserved=0>

**Comment by tamfadmin** [comment]
Hi,

Thanks for the quick response.

I should have made it clear that I used uppercase to point out the folder that is missing.  I do not have a hardware folder.

Cameshia

Cameshia Cargle
Senior Systems Administrator

TEXAS A&M FOUNDATION
401 George Bush Drive
College Station, TX 77840
979.845.7906
"Where passion finds purpose" | txamfoundation.com<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.txamfoundation.com%2F%3Futm_source%3Demail-signature%26utm_campaign%3Dtamf-staff-email-signature%26utm_medium%3Demail&data=04%7C01%7Cccargle%40txamfoundation.com%7C2425439be5d04dffa07208d9f6deb40a%7C7b770f8e0b124bc2a6bf1b8d8ea5d18a%7C1%7C0%7C637812258645308759%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fkLjF90ZntKEWs2EnSuRiHBr3lv%2BAqgamEF4PeWCGic%3D&reserved=0>

**Comment by snipe** [comment]
If that directory doesn't exist, I'm not sure how any of your asset pages are loading at all TBH. That `c:\interpub\wwwroot\snipeit\resources\views\hardware` directory is where all of the assets pages live. 🤔

**Comment by tamfadmin** [comment]
Thanks again for the response.

I need to look at everything again. I think I’ve gotten my folders confused.

I’ll be sure to include additional screen shots in my next response.

Cameshia

**Comment by tamfadmin** [comment]
Hi,

Let's start again.  I am not missing the hardware folder.  I somehow was looking in the wrong place for it.  See the screenshot for us to refer to.
[hardware-folder.pdf](https://github.com/snipe/snipe-it/files/9428102/hardware-folder.pdf)

Now I'm going to double check something else.

Thanks,
Cameshia

**Comment by snipe** [comment]
Excellent - thanks for that sanity check :)

If you upgrade to latest. I made a change so that if the uploaded file cannot be found, it shouldn't crash anymore. (I still don't know why the file isn't where it's supposed to be, but at least the page won't crash anymore.)

**Comment by tamfadmin** [comment]
Ok I have my stuff together now.
What is missing are the files named that start with the word hardware... for the assets I cannot open.  
[missing-attachments.pdf](https://github.com/snipe/snipe-it/files/9428135/missing-attachments.pdf)
[attachment-error.pdf](https://github.com/snipe/snipe-it/files/9428141/attachment-error.pdf)
I do not know why they are missing.  For certain, there are four assets that are missing the files.  I have not deleted anything.
I'm sure we cannot recover these files; however, I need what I need to do so I can open these assets.
Thanks,
Cameshia

**Comment by snipe** [comment]
As I mentioned, if you upgrade to latest, you should be able to open those assets now.

**Comment by tamfadmin** [comment]
I upgraded and everything is working properly now.

Thanks a million!!!!!!!

**Comment by tamfadmin** [comment]
You are welcome for the sanity check.   I'm getting over covid and at times find myself easily turned around on things.

That worked!

.Thanks, a million for your help!

Cameshia

Cameshia Cargle
Senior Systems Administrator

TEXAS A&M FOUNDATION
401 George Bush Drive
College Station, TX 77840
979.845.7906
"Where passion finds purpose" | txamfoundation.com<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.txamfoundation.com%2F%3Futm_source%3Demail-signature%26utm_campaign%3Dtamf-staff-email-signature%26utm_medium%3Demail&data=04%7C01%7Cccargle%40txamfoundation.com%7C2425439be5d04dffa07208d9f6deb40a%7C7b770f8e0b124bc2a6bf1b8d8ea5d18a%7C1%7C0%7C637812258645308759%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fkLjF90ZntKEWs2EnSuRiHBr3lv%2BAqgamEF4PeWCGic%3D&reserved=0>
