### ISSUE TITLE
How to make the pagination to get more than 500 results via API in appscript

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#11739]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

Would you like help to efficiently paginate to get 500+ results via API using Offset and Limit?

### Reproduction steps

1.
2.
3.
...

### Expected behavior

I would like all hardware via API in Google Sheets.

### Snipe-IT Version

v6.0.8 build 8409

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.30

### Additional context

if (total > 200){
 var limit = 200
 var offset = (limit-limit%200)/200+1
 var off = 0
  for (var j=0; j<offset+1; j++) {
    //run again with the limit so Google actually returns all the results.
    var url = serverURL + 'api/v1/models?&sort=category&order=asc&offset=' + off + '&limit=' + limit
    var response = JSON.parse(UrlFetchApp.fetch(url, options));
    var rows = response.rows
    off = off+200

  
    if (j==offset){
      limit = total%200
    }
    for (var i=0; i<limit; i++){
     var row = rows[i]
     models.push(row.name)

     //Logger.log(row.name)
     var lastRow = ss.getLastRow()+1;

    //ss.getRange(lastRow,1).setValue(row.id)
    ss.getRange(lastRow,1).setValue(row.name)
    ss.getRange(lastRow,2).setValue(row.manufacturer.name)
    ss.getRange(lastRow,3).setValue(row.model_number)
    ss.getRange(lastRow,4).setValue(row.category.name)
  }
}
}
else
{
//run again with the limit so Google actually returns all the results.
  var url = serverURL + 'api/v1/models?&sort=name&order=asc&limit=' + total
  var response = JSON.parse(UrlFetchApp.fetch(url, options));
  var rows = response.rows

  for (var i=0; i<total; i++){
    var row = rows[i]
    models.push(row.name)
    //Logger.log(row.name)
    var lastRow = ss.getLastRow()+1;
    //ss.getRange(lastRow,1).setValue(row.id)
    ss.getRange(lastRow,1).setValue(row.name)
    ss.getRange(lastRow,2).setValue(row.manufacturer.name)
    ss.getRange(lastRow,3).setValue(row.model_number)
    ss.getRange(lastRow,4).setValue(row.category.name)
  }  
}
}

**Comment by snipe** [comment]
Set `MAX_RESULTS=1000` (or whatever number you want), [per the docs](https://snipe-it.readme.io/docs/configuration). We don't recommend setting this higher than 1000 though, as it tends to slow the page down as it tries to jam all of those rows into the DOM.
