### ISSUE TITLE
SQL Schema missing

### ISSUE THREAD

**Issue by tmbutterworth** [grokability/snipe-it#11733]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am trying to install and configure SNIPE IT but I am unable to locate the SQL Schema for MariaDB. 

### Reproduction steps

1. Download SNIPE IT Source Code.
2. Create database
3.
...

### Expected behavior

Expect to have a .sql schema file to populate the data base after creation.

### Snipe-IT Version

6.0.9

### Operating System

Debian 11

### Web Server

Apache

### PHP Version

7.4+76

### Operating System

Debian 11

### Browser

Google Chrome

### Version

104.0.5112.101

**Comment by snipe** [comment]
Per the documentation, the DB schema gets created by running `php artisan migrate`. There is no schema file.
