### ISSUE TITLE
Uploaded files size on hardware page is incorrect when using S3-like to get/store the files

### ISSUE THREAD

**Issue by dsferruzza** [grokability/snipe-it#11742]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

My instance of Snipe-IT is hosted on [Clever Cloud](https://www.clever-cloud.com) and I use their [Ceph-based S3 Object Storage](https://www.clever-cloud.com/fr/cellar-s3-hosting/) to store uploads.
Storing and reading files works well.

Since Snipe-IT `6.0.1` (or `6.0.0`, I'm not sure) was released, I noticed that the `/hardware/:id` page was crashing (500 error) for hardware that had at least 1 uploaded file.
I found the issue and tested a patch on my instance successfully.
Basically: it works when using `Storage::size()` instead of `filesize()` because it follows Laravel's FS configuration instead of just trying to read a path on the local FS.
I found a related issue (#11150) and described my solution in a comment (https://github.com/snipe/snipe-it/issues/11150#issuecomment-1134650509) but as the issue was closed I suspect it was not read.
This issue was confirmed by @minkbear.

Since `6.0.10`, this issue does not crash the page anymore (since `@` was added in front of the call to `filesize()`), but the file size is still not correct.

### Reproduction steps

1. Configure a Snipe-IT instance ≥ `6.0.1` with S3 storage
2. Create a hardware and store a file
3. Go to the hardware page and the files tab, and check the displayed file size

### Expected behavior

I expect the file size to be correct, as shown in the following screenshots.

### Screenshots

With `6.0.10`:

![image](https://user-images.githubusercontent.com/1931963/186872584-605f44ee-1fdb-40b5-98a6-d3d163f049f2.png)

File size is incorrect.

---

With patched `6.0.10` (same data/config):

![image](https://user-images.githubusercontent.com/1931963/186872955-6733c433-f2d8-4033-bcf3-f3e479534a8f.png)

File size is correct.

### Snipe-IT Version

6.0.10

### Operating System

Linux (whatever Clever Cloud is using, I think it is Exherbo)

### Web Server

Apache

### PHP Version

8.0.21

**Comment by snipe** [comment]
Thanks for this report - sounds like you've already sussed out the fix - we'd happily take a PR for this.
