### ISSUE TITLE
DB Connection Error - WAMP Server

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#11745]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After adding the following entry to the .ENV file, running php artisan migrate produces the following error
![Entry](https://user-images.githubusercontent.com/31219479/186954780-94dc1381-e4ed-4a43-8fa5-454d64d4fcf1.jpg)
.
![error](https://user-images.githubusercontent.com/31219479/186954907-d1d4ed12-f166-4e8a-bc56-7a798cf902e3.jpg)

When entry is removed and php artisan migrate is ran again issue is not present.

### Reproduction steps

After adding the following entry to the .ENV file, running php artisan migrate produces the following error
![Entry](https://user-images.githubusercontent.com/31219479/186954780-94dc1381-e4ed-4a43-8fa5-454d64d4fcf1.jpg)
.
![error](https://user-images.githubusercontent.com/31219479/186954907-d1d4ed12-f166-4e8a-bc56-7a798cf902e3.jpg)

When entry is removed and php artisan migrate is ran again issue is not present.

### Expected behavior

DB_Port=3309 entry does not produce error when entered into .ENV file

### Snipe-IT Version

3.0.10

### Operating System

Server 2019

### Web Server

WAMP 3.2.6

### PHP Version

7.4.26

**Comment by snipe** [comment]
So you got everything working then? What's the specific issue?

**Comment by jmartins1** [comment]
Yes, I got it working. I had to comment out "DB_PORT=3309"

**Comment by jmartins1** [comment]
Yes, I got it working. I had to comment out "DB_PORT=3309"

**Comment by snipe** [comment]
You shouldn't have to comment it out, just change it to what it should be (`3306` is standard)
