### ISSUE TITLE
i have installed snipe it on ubuntu 22 LTS after all configurations the pre flight page comes blank

### ISSUE THREAD

**Issue by arjunks94** [grokability/snipe-it#11761]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

i have installed snipe it on Ubuntu 22.04.1 LTS after all configurations the pre flight page comes blank

### Reproduction steps

1.Start the URL
2.Showing correct URL on page but page comes blank
3.http://localhost
...

### Expected behavior

it should bring pre flight page for setup

### Screenshots

![Screenshot from 2022-08-30 13-55-05](https://user-images.githubusercontent.com/84993460/187419164-2c7515d8-01a0-42af-b9b0-3f1869532727.png)

### Snipe-IT Version

6.0.10

### Operating System

Ubuntu 22.04.1 LTS

### Web Server

Apache

### PHP Version

PHP 8.1.2

### Operating System

Ubuntu 22.04.1 LTS

### Browser

Mozilla Firefox

### Version

104.0

**Comment by Virtute90** [comment]
check the log with first step https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by arjunks94** [comment]
I have enabled debug mode and their is no files generated in Log folder
and as per consol view on browser its like the following i will attach screenshot

GEThttp://www.snipeit-srv.com/setup
[HTTP/1.0 500 Internal Server Error 63ms]
![Screenshot from 2022-08-30 18-53-28](https://user-images.githubusercontent.com/84993460/187484017-e52be594-ec7e-4aaf-8349-ce3ce5d19a18.png)

This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.

**Comment by snipe** [comment]
Hi - sorry you're having trouble. As mentioned in the Issue Template, we need a stack trace and browser console errors in order to help you. 

You can either provide the contents of your `storage/logs/laravel.log` (please do not attach files, just paste in the log lines that occur when you trigger the error, you can turn `APP_DEBUG=true` and then trigger the error and show us what's on the screen, or you can tail the log file. More information is available [in the documentation](https://snipe-it.readme.io/docs/getting-help).

https://snipe-it.readme.io/docs/getting-help
https://snipe-it.readme.io/docs/advanced-debugging

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/advanced-debugging">Advanced Debugging</a></strong></div><div>Snipe-IT ships with the Laravel Debugbar, an amazing piece of software that lets you introspect much further into the framework and application to troubleshoot issues that may be a little harder to track down. To enable the debugbar, set the following in your .env file, and clear your config cache: ...</div></blockquote>

**Comment by Virtute90** [comment]
Could it be an apache configuration problem? Can you copy the contents of the default.conf file?

**Comment by arjunks94** [comment]
@Virtute90 


-------
<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost

	DocumentRoot "/var/www/html/snipeit/public"
	DirectoryIndex index.php index.html
	# php_value include_path "/var/www/html/include"
	<Directory "/var/www/html">
		Options All +MultiViews -ExecCGI -Indexes
		<IfModule mod_dav.c>
			DAV Off
		</IfModule>
		AllowOverride All
	</Directory>
	LogLevel warn
	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

**Comment by arjunks94** [comment]
@snipe 

ErrorException
file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): Failed to open stream: Permission denied 

Log 


2022-08-30 12:54:25] production.ERROR: ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): Failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents()
#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\Filesystem\Filesystem->put()
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\Cache\FileStore->put()
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\Cache\FileStore->forever()
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): Illuminate\Cache\Repository->forever()
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\Cache\Repository->rememberForever()
#7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Cache\CacheManager->__call()
#8 /var/www/html/snipeit/app/Models/Setting.php(108): Illuminate\Support\Facades\Facade::__callStatic()
#9 /var/www/html/snipeit/app/Http/Middleware/CheckLocale.php(21): App\Models\Setting::getSettings()
#10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckLocale->handle()
#11 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#13 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

**Comment by Virtute90** [comment]
> @snipe
> 
> ErrorException file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): Failed to open stream: Permission denied
> 
> Log
> 
> 2022-08-30 12:54:25] production.ERROR: ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): Failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187 Stack trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() #1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents() #2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\Filesystem\Filesystem->put() #3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\Cache\FileStore->put() #4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\Cache\FileStore->forever() #5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): Illuminate\Cache\Repository->forever() #6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\Cache\Repository->rememberForever() #7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Cache\CacheManager->__call() #8 /var/www/html/snipeit/app/Models/Setting.php(108): Illuminate\Support\Facades\Facade::__callStatic() #9 /var/www/html/snipeit/app/Http/Middleware/CheckLocale.php(21): App\Models\Setting::getSettings() #10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckLocale->handle() #11 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}() #12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #13 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}()

you should check the permissions of this folder

`/var/www/html/snipeit/storage/framework/cache/`

the apache configuration seems correct

this page should help you: https://snipe-it.readme.io/docs/debugging-permissions

**Comment by arjunks94** [comment]
I have made the permission according to the installation manual

**Comment by arjunks94** [comment]
@Virtute90 it worked now i got the preflight page thank you for the support
