### ISSUE TITLE
Changing the Domain

### ISSUE THREAD

**Issue by HodyMoin** [grokability/snipe-it#11775]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I wanted to change the domain for my SnipeIT.
I'm running on linux.
I changed the profile in nginx.
I changed the .env file.

Once that was done, I updated the permission, and ran sudo php artisan cache:clear

However, Once I logged into the AMS, not of my assets where there. and when I force SSL in Nginx Proxy Manager. the browser shows too many redirects.

### Reproduction steps

changed the profile in nginx.
changed the .env file.

### Expected behavior

to load the website correctly.

### Snipe-IT Version

v6.0.9 build 8587 (gcca531f8c)

### Operating System

Ubuntu

### Web Server

Nginx

### PHP Version

8.1.9

### Operating System

Windows

### Browser

Chrome

**Comment by n3s0** [comment]
Might be useful to provide more data about the issue you're having. 

Logs and screenshots would be useful, steps you took to perform the URL change, etc.
