### ISSUE TITLE
[Feature Request]:  Bulk Delete Users

### ISSUE THREAD

**Issue by XPGCaboose** [grokability/snipe-it#11793]
### Is your feature request related to a problem? Please describe.

When I imported my students, I didn't know I could set the username so it created usernames based on my admin settings. I later found that I could add the username field to my import file. I did that and imported the student.csv back into snipe making sure to select the update button howerver, it created all new users. There is no way to bulk select and delete users that I can find. I have to manually delete one at a time.

### Describe the solution you'd like

I would love to be able to use the bulk edit to delete the 1300 duplicated users.

### Additional context

Ubuntu 20.04.5 LTS
Snipe Version v6.0.10 - build 8610 (master)

**Comment by inietov** [comment]
Hello there!!

You can go to the 'People' screen:
![image](https://user-images.githubusercontent.com/653557/188934551-12b205a1-0d34-433c-b21d-39184257c992.png)

Select the users you want to delete and make sure to select the `Bulk Checkin Items for Users` option on the up left menu, then click on the go button to get into this screen:
![image](https://user-images.githubusercontent.com/653557/188935422-0d8e0956-4b8e-4118-bafb-20eb6311b6c7.png)

Where all the selected users are shown and you can click the checkbox marked as "Also soft-delete these users....". 

I hope it's helpful for your use case!! Have a good day

**Comment by XPGCaboose** [comment]
AMAZING. That is what I was looking for. Never thought to check the bulk check in.
