### ISSUE TITLE
Google Workspace LDAP Sync

### ISSUE THREAD

**Issue by MatthiasKloepperQC** [grokability/snipe-it#11804]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

LDAP Synchronization with Google Workspace secured LDAP Server does not work anymore. It did work for a couple of month now but we discovered the error early this week.

Upon using the `Test LDAP Synchronization` button from the /admin/ldap page it show the `Testing LDAP Connection, Binding & Query ...` message for some seconds and then switches to the error message `Could not bind to LDAP: Can't contact LDAP server`.

Accessing the Google LDAP server via e.g. "LDAP Browser" using the same setting and certificates work without any issue.

### Reproduction steps

- Go to /admin/ldap
- Use the test function

### Expected behavior

Syncing from Google Workspace LDAP should work again ;-)

### Screenshots

![image](https://user-images.githubusercontent.com/15989529/189347291-230bf4df-0bb5-44aa-875d-9e94406d7744.png)
![image](https://user-images.githubusercontent.com/15989529/189347419-523134cd-b9ca-467f-b682-71380f8aa70b.png)
![image](https://user-images.githubusercontent.com/15989529/189347483-0257ec08-5d1a-4e85-a51f-0ce130b39518.png)

### Snipe-IT Version

v6.0.8 - build 8409 (master)

### Operating System

unknown

### Web Server

unknown

### PHP Version

unknwon

### Operating System

Windows 11 Pro

### Browser

Microsoft Edge Chromium

### Version

104.0.1293.54

### Additional context

This is an instance hosted by Snipe-IT (quantco.snipe-it.io).

**Comment by DmACKGL** [comment]
Check `Use TLS` and try again.

**Comment by MatthiasKloepperQC** [comment]
Thanks for the proposal. TLS should be unneccessary when using an "ldaps"-Connection.
Testing while `Use TLS` is active changes the error message to `500 Server Error. Please check your server logs for more information.` Checking the logs is impossible for me, since our instance is hosted by Snipe-IT.
I also tried to change the protocol to "ldap" instead of "ldaps" while having TLS activated. Same error message.

**Comment by uberbrady** [comment]
Oh, if you're hosted by us - you should absolutely reach out to support@snipeitapp.com and we can check the logs, and do some command-line troubleshooting to help.

**Comment by uberbrady** [comment]
(Also we have plenty of customers who do use the Google LDAP setup, including us ourselves - so it definitely *does* work).

**Comment by MatthiasKloepperQC** [comment]
I know that it should work, it has done so for quite some time. But I have no clue why it broke now. I'll reach out to supprt via mail then. Thanks a lot!

**Comment by TimetravelerDD** [comment]
@MatthiasKloepperQC : may I ask what was the issue? I am running into the same problem
