### ISSUE TITLE
Delete Assigned Asset or License 

### ISSUE THREAD

**Issue by Raffudeen** [grokability/snipe-it#11818]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, 

Please advise if have idea about how can i delete an asset or license when it is assigned to the user or asset ?

When i try to delete attached notification shows.
![Snipe it](https://user-images.githubusercontent.com/70876850/190073927-71633a3b-524a-4013-ab31-3034e07c865e.png)

### Reproduction steps

1. Nothing Done
2.
3.
...

### Expected behavior

![Snipe it](https://user-images.githubusercontent.com/70876850/190084741-3d99fee9-543f-4edc-8f26-f4ffb98c14c7.png)

### Snipe-IT Version

v4.9.4 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

v7.2.24

**Comment by Codewow** [comment]
The error message tells you what you need to do. 😄 "Check in the license first, then try deleting it"

The same is required for all other managed items.

**Comment by Raffudeen** [comment]
> The error message tells you what you need to do. 😄 "Check in the license first, then try deleting it"
> 
> The same is required for all other managed items.

wow what a great solution :( ....  Kindly do read the my query properly before a causal reply...

"I need to know.. you have any idea that how can I DELETE the License by being assigned to the user or an asset"

**Comment by snipe** [comment]
"you have any idea that how can I DELETE the License by being assigned to the user or an asset"

This is not a clear question. If you need to check in a license seat, go to the license, go to seats, find the one that's checked out and check it in.

If I'm missing the question, please try to rephrase it in a way that is clearer.

**Comment by snipe** [comment]
(Also you're running  a very old version of Snipe-IT that we don't really formally support anymore. I'd suggest upgrading.)

**Comment by Raffudeen** [comment]
Mr. Snipe,

For example assume that i have a "Microsoft office" license about 500 Qty and which are already assigned to the computers.

Now it is quite hard to check in all licenses one by one and delete the license. That's why I'm asking you is there any chance to delete the whole Microsoft license which would automatically pull the licenses from the assigned computers.

**Comment by Raffudeen** [comment]
Is there any solution that you can provide for the above mentioned issue ?? @snipe

**Comment by snipe** [comment]
I am not a Mr.

As mentioned elsewhere, you would use the command line script to checkin the license seats than delete. 
 
https://snipe-it.readme.io/docs/bulk-license-checkoutcheckin

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/bulk-license-checkoutcheckin">Bulk License Checkout/Checkin</a></strong></div><div>If you need to check out a particular license to all users (for example an Office 365 license, which every user in your organization should theoretically have) or bulk checkin a license from all users (for example if you stopped using G-Suite), there is a console command to let you do that:Textsnipe...</div></blockquote>
