### ISSUE TITLE
Error 500 occurs->Create asset

### ISSUE THREAD

**Issue by arunbrajendran1985** [grokability/snipe-it#11815]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Iam getting Error 500 while creating new asset
This was working fine before
How ever Iam able to update the assets with out errors

Please help me to resolve this issue

### Reproduction steps

1.Login into localhost
2. create a new asset
3. save
...

### Expected behavior

Should be able to create an asset

### Screenshots

![image](https://user-images.githubusercontent.com/113465661/189974634-794a7a44-14af-404d-b35e-228e4acfffa1.png)

![image](https://user-images.githubusercontent.com/113465661/189974963-d1a0a4b3-7633-48cb-8e2f-e23162dcc0e0.png)

### Snipe-IT Version

snipe-i-6.0.10

### Operating System

Windows

### Web Server

Apache

### PHP Version

PHP 8.1.6

### Operating System

Windows 

### Browser

Firefox

### Version

104.0.2 (64-bit

### Error messages

```shell
[2022-09-02 09:19:15] production.ERROR: Your APP_URL in your .env is misconfigured - it is: localhost. Many things will work strangely unless you fix it.
```

**Comment by snipe** [comment]
The error is telling you what’s wrong , no? What’s your `APP_URL` set to?

**Comment by snipe** [comment]
My guess would be that your `APP_URL` is misconfigured in your `.env` file. [Per the documentation](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings), the APP_URL should be the complete URL to your Snipe-IT installation, *including* the `http://` (or `https://` if you're running over TLS.)

<img width="795" alt="Screen Shot 2022-07-28 at 11 35 47 PM" src="https://user-images.githubusercontent.com/197404/181698021-de470225-4865-4786-bd48-9a9cdf2399d2.png">

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by arunbrajendran1985** [comment]
Thanks
Issue got fixed :)
