### ISSUE TITLE
QNAP NAS - Autostart not turned on

### ISSUE THREAD

**Issue by Daalexx** [grokability/snipe-it#11828]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

This is not really a bug.
However, I am running SnipeIT in Container Station on my QNAP NAS, it seems like autostart is not turned on for these Containers though. (SnipeIT + MySQL). 
Can someone explain to me how I can turn autostart on?

Also, does someone know by accident how to properly back the data for my SnipeIT platform up, so that it can easily be recovered and setup again, should my NAS fail?

Thanks a lot!

### Reproduction steps

--

### Expected behavior

Once the NAS restarts/shuts down, the containers should automatically restart

### Snipe-IT Version

latest

### Operating System

QTS

### Web Server

?

### PHP Version

?

**Comment by n3s0** [comment]
Based on some quick googling it looks like this is a feature available in the GUI and can be modified after the fact on the container object.

https://forum.qnap.com/viewtopic.php?t=154400

You could try backing up to another volume on the NAS and have that volume synced to dropbox or something. Depends on what data you're expecting to keep.
