### ISSUE TITLE
LDAP Sync not working - issues with login

### ISSUE THREAD

**Issue by gustavof** [grokability/snipe-it#11833]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi! 

We recently updated our installation of Snipe-it to version 6;  we have recently noticed that LDAP Sync is not working, and new workers to our organization are not being added to Snipe-it.  When I try pressing the "Sync" button in /users/ldap it runs for a while, then goes to a 500 - Internal Server Error.  The laravel log when that happens says the following:

[2022-09-15 15:29:15] development.DEBUG: Total count is: 56000  
[2022-09-15 15:29:15] development.DEBUG: did the search run? I guess so if you got here!  
[2022-09-15 15:29:15] development.DEBUG: okay, at least one more page to go!!!  
[2022-09-15 15:29:15] development.DEBUG: Total count is: 56070  
[2022-09-15 15:29:15] development.DEBUG: That location is invalid or a location was not provided, so no location will be assigned by default.  

In addition to this, when using this old filter that used to work in version 5, the "Test LDAP Login" feature fails, and when I press "Test LDAP" using my credentials, it says:
 ldap_search(): Partial search results returned: Sizelimit exceeded

I have tried using the filters suggested here:
https://snipe-it.readme.io/docs/ldap-sync-login

If I use the filter:
&(cn=*)
When I press "Test LDAP Synchronization" it returns random objects together with people, however "Test LDAP Login" works well and new people can log in  to the app.

If I use the filter suggested for AD enabled users: 
&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
or a variation: 
&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(showInAddressBook=*)
When I press "Test LDAP Synchronization" it returns only people, however "Test LDAP Login" works well and new people can log in  to the app.

In both cases, however, LDAP Sync does not seem to work, returning even more results than with our old filter, and a similar error message of "That location is invalid or a location was not provided, so no location will be assigned by default. "

I have tried reviewing the LDAP settings as well as the ones in the .env file as much as possible, and I'm afraid I'm out of options and ideas.  Any help will be greatly appreciated. 

Thank you!
G

### Reproduction steps

1. Clicking on the "sync" button, or running "php artisan snipeit:ldap-sync" or Waiting for PowerShell Script to run overnight
2. Waiting for sync to complete
3. Checking for users that exist in Active Directory
...

### Expected behavior

Users that exist in Active Directory are imported into Snipe-it

### Snipe-IT Version

6.05

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.26

### Operating System

Windows 10

### Browser

Microsoft Edge

### Version

 105.0.1343.33

### Error messages

```shell
[2022-09-15 15:29:15] development.DEBUG: did the search run? I guess so if you got here!  
[2022-09-15 15:29:15] development.DEBUG: okay, at least one more page to go!!!  
[2022-09-15 15:29:15] development.DEBUG: Total count is: 56070  
[2022-09-15 15:29:15] development.DEBUG: That location is invalid or a location was not provided, so no location will be assigned by default.  

Also:
LDAP login failed  

And 500 error on backend interface
```

### Additional context

This is on a somewhat recent upgrade from Snipe-it 5.x to 6.x

**Comment by gustavof** [comment]
Hi there!  I'm still waiting for any help or insight you guys could offer.  Please let me know if you need any more info.  TIA.

**Comment by dangngoctrung1806** [comment]
Me too, i using snipe v6.10, php v8.0.2

**Comment by mattgann** [comment]
Same issues for me also after upgrade
v6.0.10 
My Developement server that wasnt upgraded yet, still works fine

**Comment by snipe** [comment]
I know for sure that LDAP does work - there might be a setting that needs tweaking, but it definitely works. @uberbrady can you take a peek at this and help them get sorted?

**Comment by mattgann** [comment]
Same issue here
v6.0.10 
no issue with test server that is not upgraded

**Comment by gustavof** [comment]
If it does, it seems like there is a difference in how the settings are handled between versions 5 and 6.  Let me know if you need me to send you a screenshot of our settings via private message.

**Comment by snipe** [comment]
That's definitely true - but we've tried to make the LDAP settings page show as many settings conflicts as we can.

**Comment by gustavof** [comment]
Yeah, I went through it multiple times; it did help me catch that I wasn't running the PHP extension for LDAP.  But I am now, and the issue persists.

**Comment by snipe** [comment]
Extension-level stuff is a little harder, unfortunately. For some extensions, the app itself cannot load, so it's hard to put an interstitial in place, using the framework, when the framework itself can't load. It's why the upgrade script is in raw php, not framework. That script will work if you have PHP installed - it will then try and tell you whatever else is missing.

**Comment by dangngoctrung1806** [comment]
> Extension-level stuff is a little harder, unfortunately. For some extensions, the app itself cannot load, so it's hard to put an interstitial in place, using the framework, when the framework itself can't load. It's why the upgrade script is in raw php, not framework. That script will work if you have PHP installed - it will then try and tell you whatever else is missing.

Hi, Please inform to me version of snipeit, php ton run ldap.

**Comment by gustavof** [comment]
Snipe, the people who took care of the upgrade did run php upgrade.php, as instructed in the documentation.  When I started looking into the problem, the extension was disabled in IIS, where we have snipe-it running.

**Comment by snipe** [comment]
@gustavof it also gets a little tricky because if you don’t intend to use LDAP, we don’t want to require it. (Lots of people use Snipe-IT and either use only local users, SAML or SCIM, so LDAP shouldn’t always be required.) IIRC we used to check for the LDAP extension if and only if you were trying to do an LDAP task. We should probably put that check back in place.

**Comment by mattgann** [comment]
v6.0.10 - Windows IIS - PHP 7.4.3
I also didnt have Ldap enabled then I enabled it and still get
 "Could not bind to LDAP: Can't contact LDAP server"
 5.3.10 with the same ldap settings
 Still says
  Successfully connected to LDAP server.
 Successfully bound to LDAP server.

**Comment by gustavof** [comment]
@Mattgann, have you considered changing your filter?  Have you tried this one:
&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))

What makes the problem I'm experiencing extra hard is that we DO pass the tests, "Test LDAP Synchronization" as well as "Test LDAP Login", but the app is still not getting new users from AD.

**Comment by mattgann** [comment]
The suggested filter still resulted in
"Could not bind to LDAP: Can't contact LDAP server"
My tests do not pass in 6.0.10
5.3.10 still works
I am lost

**Comment by gustavof** [comment]
I think I have managed to narrow down the problem a bit; looking at the logs, and the Database, users **are** being imported when I use the filter suggested in the LDAP configuration page of Snipe-it for AD enabled users, but the script is timing out because there are too many users being imported, most of which are not a category that we want; we are a university and we want only staff in snipe-it, not students - there are so many students imported by the Sync, that the job times out after 2 hours.

The previous filter we were using that worked on Snipe-it 5 uses "(memberOf=" multiple times, instead of "sAMAccountType=".  That old filter passes the LDAP Synchronization test, but doesn't allow new people to log in; it says "sizelimit exceeded".

@mattgann, it sounds like something in the connection settings for you; maybe the domain or LDAP server address?

**Comment by mattgann** [comment]
Since this was a "php upgrade.php" and the working clone of the prior version has no issues, I am not sure where to look other than the GUI ldap section in the admin settings. Everything I see is identical.

**Comment by mattgann** [comment]
What logs could I look at that might help me figure this out for ldap?

**Comment by Speed1** [comment]
Hi,

I have the same problem since upgrading from 5.4 to 6.0.11.

My LDAP Filter query:```memberof:1.2.840.113556.1.4.1941:=<groupDN>```
Error Test LDAP Login: ```ldap_search(): Search: Bad search filter```
User error on login: ```Error The username or password is incorrect.```

When I replace the LDAP Filter query with the suggested one ```&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))``` everything works as expected.

Let me know if you need further info

**Comment by snipe** [comment]
Hi there - Pretty sure this has been working for a long time now, sorry for not closing this sooner. I'm going to close this. Please feel free to open a new issue if you're still having trouble.
