### ISSUE TITLE
SMTP Mail Error 

### ISSUE THREAD

**Issue by MattyHumphrey** [grokability/snipe-it#11859]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

SMTP emailing no longer working. Chekin / Checkout emails no longer sending to users. When I go to send a test email that errors as well. 

### Reproduction steps

1.Settings
2.General Settings
3.Send Test Mail
4. Mail could not be sent.
No additional error message provided. Check your mail settings and your app log.
5. With Debug enabled I receive the following warning. LOG.warning: Since league/commonmark 2.2.0: Calling "convertToHtml()" on a League\CommonMark\MarkdownConverter class is deprecated, use "convert()" instead. in D:\SnipeITSource\vendor\symfony\deprecation-contracts\function.php on line 25
6. Wen I check the function.php on line 25 I see the following. @trigger_error(($package || $version ? "Since $package $version: " : '').($args ? vsprintf($message, $args) : $message), \E_USER_DEPRECATED);
...

### Expected behavior

Email to send. 

### Snipe-IT Version

v6.0.10

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

8.0.19

### Operating System

Windows 

### Browser

Chrome

### Version

105.0.5195.127

### Error messages

```shell
LOG.warning: Since league/commonmark 2.2.0: Calling "convertToHtml()" on a League\CommonMark\MarkdownConverter class is deprecated, use "convert()" instead. in D:\SnipeITSource\vendor\symfony\deprecation-contracts\function.php on line 25

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
fileinfo
filter
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
soap
sodium
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

**Comment by daxgravic** [comment]
I'm seeing this same error with a new Snipe-IT install on Ubuntu 20.04.  Everything else is working.

**Comment by snipe** [comment]
@daxgravic It's definitely a configuration or network issue on your end. We haven't made any changes to the email system in many years.

(Also probably next time open a new issue instead of replying to a closed issue, since it gives you the opportunity to provide more info.)

**Comment by daxgravic** [comment]
Sorry, didn't see that this was closed.

**Comment by snipe** [comment]
No worries - it's just that since it's a reply and not a new issue, we don't know anything about your system/OS/etc, so it makes it a lot harder to help.

**Comment by MattyHumphrey** [comment]
My apologies for creating this ticket. After I created this, I found something else within debug that mentioned unable to communicate with outlook at which point I know it was something on our side that I had not yet found.

**Comment by snipe** [comment]
It's all good :)

**Comment by gabe0424** [comment]
Hi. do we have a resolution for this? I am also experiencing inability to send from outlook. Much appreciated.
