### ISSUE TITLE
User Details are getting mixed up

### ISSUE THREAD

**Issue by A-Kasper** [grokability/snipe-it#11863]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We use the LDAP-Sync for our user directory.
LDAP Sync works. All users are updated correct. 
Now I have two Users, who get the Name and Mail adress of another user (the same userdetails in both cases) 

Example:
user a: 
- Name Steffi Meier
- Email Steffi.Meiser@company.com
- Username: meier

user b: 
- Name Boris Schneider
- Email Boris.Schneider@company.com
- Username: schneider

user c: 
- Name Heiko Schmidt
- Email Heiko.Schmidt@company.com
- Username: schmidt

This is what is in Snipe-IT db after LDAP Sync.

When User a and/or user b login the user Directory in Snipe-IT changes to

user a: 
- Name Heiko Schmidt
- Email Heiko.Schmidt@company.com
- Username: meier

user b: 
- Name Heiko Schmidt
- Email Heiko.Schmidt@company.com
- Username: schneider

user c: 
- Name Heiko Schmidt
- Email Heiko.Schmidt@company.com
- Username: schmidt

This effects only the user details.  Username stays correct. Assets etc. are still at the correct username.

If I user ldap sync again the database is correct again. But just until the user logs in.

### Reproduction steps

1. LDAP Sync --> User directory is okay
2. user login of affected user --> Userdetails changes to userdetails of another user
3. LDAP Sync --> User details are correct again
...

### Expected behavior

see above

### Snipe-IT Version

6.09 and 6.0.10 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.0

### Additional context

The instance of Snipe-IT is running for a while without these Problems. It seems the problems came with update to V6+

Please let me know if you need more information and how i can get them.

**Comment by uberbrady** [comment]
I suspect your LDAP Filter has an 'or' query in it, and that's confusing the system when it tries to grab user details. What are your LDAP settings? (Feel free to redact out anything that's private).

**Comment by A-Kasper** [comment]
Hi, 
the LDAP Query works. After Sync everything is fine. 
The Problem comes when the user logs in. 
The Query is:
|(&(objectCategory=user)(memberOf=cn=snipeit-user,ou=Security Groups,ou=mybusiness,dc=XXXXX,dc=local))(&(objectCategory=user)(memberOf=cn=IKT,ou=Security Groups,ou=mybusiness,dc=XXXXX,dc=local))

So yes.. there is an OR

**Comment by A-Kasper** [comment]
Additional Info:
The query worked until upgrade to 6.x
It's a new issue

**Comment by A-Kasper** [comment]
I changed the LDAP to use a query without OR (removed the second Security Group). The problem is gone with this config. So your intention was good. The issue is related to OR in the LDAP query.
