### ISSUE TITLE
Mail notifications will not work

### ISSUE THREAD

**Issue by daxgravic** [grokability/snipe-it#11862]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Cannot get outgoing mail notifications to work.

### Reproduction steps

1. Configure .env file:
MAIL_DRIVER=smtp
MAIL_HOST=smtp.dreamhost.com
MAIL_PORT=465
MAIL_USERNAME=inventory@[company domain]
MAIL_PASSWORD=[sync'd with domain account]
MAIL_ENCRYPTION=ssl (I've also tried 'tls' as both are supported by the mail host)
MAIL_FROM_ADDR=inventory@[company domain]
MAIL_FROM_NAME='Company Inventory'
MAIL_REPLYTO_ADDR=inventory@[company domain]
MAIL_REPLYTO_NAME='Company Inventory'
MAIL_AUTO_EMBED_METHOD='attachment'
2. 
3.Send Test Mail from General Setting
4. Get this error --> Mail could not be sent.
No additional error message provided. Check your mail settings and your app log.
5. With Debug enabled I receive the following warning. LOG.warning: Since league/commonmark 2.2.0: Calling "convertToHtml()" on a League\CommonMark\MarkdownConverter class is deprecated, use "convert()" instead. in D:\SnipeITSource\vendor\symfony\deprecation-contracts\function.php on line 25

### Expected behavior

Mail is sent

### Snipe-IT Version

v6.0.10 build 8610 (g22710afee) 

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

### Error messages

```shell
LOG.warning: Since league/commonmark 2.2.0: Calling "convertToHtml()" on a League\CommonMark\MarkdownConverter class is deprecated, use "convert()" instead. in D:\SnipeITSource\vendor\symfony\deprecation-contracts\function.php on line 25
```

### Additional context

This is a fresh install of Snipe-IT.  I used the install.sh and have imported .csv files to initialize the database.  I have not manually modified any DB data. I'm only updating the .env file and the mail settings seem correct based on the documentation.  I know the email settings are correct as I have used them in other servers to send notifications.

**Comment by daxgravic** [comment]
I don't see any errors in the debugger of anything failing with the mailtest.

**Comment by snipe** [comment]
That warning is just a warning, so I don't think that's related. Is it possible Dreamhost has a config we're missing here? (I use Dreamhost as well, and I can't think of one, but maybe?)

**Comment by snipe** [comment]
(Also is it possible the notifications are being directed to a SPAM folder?)

**Comment by daxgravic** [comment]
Maybe but I get this error next to the 'Send Test' button on the General Settings page -->  "Mail could not be sent.  No additional error message provided. Check your mail settings and your app log"

**Comment by snipe** [comment]
That is profoundly not helpful (the error message, not you), but when we fall back to that, it's literally because we can't tell what's not working. There are a bunch of exceptions that we can catch and then deliver a sane, readable error message - but if you're seeing that, it's more like "shit's busted, we have no idea why". Can you reach out to DH and see if there's anything useful in the mail logs?

**Comment by daxgravic** [comment]
That's exactly what I said about that error message.  Yes, I'll see if DH can help here.

**Comment by snipe** [comment]
Yeah, we're not giving that vague error to be jerks. It's because the system literally isn't getting anything useful back from the mail server to tell you what's wrong. We always try to be specific with error messages, but when it falls through every other check we can do, we resort to  ¯\_(ツ)_/¯ because we don't have any other info to offer. :(

**Comment by daxgravic** [comment]
Well that was it; the DH settings that is.  Somehow the DH account got switched to a forward only account that didn't allow login.  It was *not* like that when I initially set it up.  Sorry for the false alarm.  I'm really liking Snipe-IT and I appreciate the quick response to my "issue".  Thanks.

**Comment by snipe** [comment]
No worries :) I'm glad you got it sorted!
