### ISSUE TITLE
cannot delete the purchase date

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#11866]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I can't delete the asset purchase date. For example, I do not need this information or I do not know the date of purchase of the asset, and I need to delete this data.. But I can't do it. In previous versions, I could delete the purchase date.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

I would like to be able to delete the purchase date.

### Snipe-IT Version

6.0.10

### Operating System

CentOS

### Web Server

Apache

### PHP Version

7.4.29

### Operating System

Windows 10

### Browser

Google Chrome, MS Edge...

### Version

last

**Comment by UserGoodtm** [comment]
I saw in another topic that perhaps this behavior is due to a "feature", and this is not a "bug" .. but it's one thing to enter the date manually or from the calendar, and another thing is to completely delete this date. I agree that the date can be selected from the calendar, and not entered manually .. but the ability to both set and delete the purchase date should be available.

**Comment by snipe** [comment]
This is fixed on master IIRC

**Comment by snipe** [comment]
https://github.com/snipe/snipe-it/pull/11877
