### ISSUE TITLE
Clear Email Queues

### ISSUE THREAD

**Issue by brianhoganm** [grokability/snipe-it#11883]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,
How do I clear the email queues? Is there a a command to clear out any scheduled tasks or emails that are being sent.

I tried using the **php artisan queue:clear** but that didn't work. 

Thanks.

### Reproduction steps

1. Tried using the **php artisan queue:clear** but that didn't work. 
2.
3.
...

### Expected behavior

None

### Snipe-IT Version

6.10

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4

**Comment by snipe** [comment]
Not really - you’d have to handle that on your outbound mail server’s end. We don’t use queues so there’s nothing on our end to clear.

**Comment by brianhoganm** [comment]
hmmm...so it looks like it's a Gmail thing. So it's going to continue to send emails no matter what. I stopped the emails in the .env file of SNIPE but the _SMTP_ Gmail for outgoing mail will queue and try again every 10 minutes until it succeeds. Interesting.
Thanks.
