### ISSUE TITLE
index.php = Autoload ?

### ISSUE THREAD

**Issue by FredrikHj** [grokability/snipe-it#11884]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi

We have begun using the software a few days ago, our own hosting. I have tried IIS and now Xampp, we cannot run docker becasue we have Hyper-V VM and the docker needs Hyper-V. In IIS and Xamp the Snipe-IT as I understand will autoload without any more typing in the address bar than the ip and port nr?

But it will not autoload so I need to typing the path incl the index.php but the design will not load if I do so. What is fault?  

However I do not know if my faul is a bug or my own problem or yours bit if yes I will enable the debug mode!

Best regards Fredrik

### Reproduction steps

I have follow the instruction. It should be enoth?

### Expected behavior

The Snipe-IT should be autoloaded as I understand it?

### Snipe-IT Version

6.0.10

### Operating System

Windows Server 2022 (VM)

### Web Server

Apache / ISS

### PHP Version

8,1.6

### Operating System

Windows 11, 64-bit

### Browser

Chrome

### Version

22000.978

### Error messages

```shell
No messages!
```

### Additional context

Fresh install!

**Comment by snipe** [comment]
Not sure what you mean by it won’t autoload. Can you be more specific? It shouldn’t matter what Hyper-V (or OS) you’re using.

**Comment by FredrikHj** [comment]
Thank you for your quick reply :)

Autoload equal to just typing: snipe-it.local or in my case the: ipaddress:portnr if add the path to and index.php I am getting the site but non css is loaded. If I am looking in the .env file and the  APP_URL='http://172.29.7.131:801'.

Strange it is now showing something. but the css still not loading, look at the attached image!
![2022-09-29 08_05_43-Översikt __ Snipe-IT](https://user-images.githubusercontent.com/43028745/192952217-4b8ce434-f525-41ee-b48a-64f21878f5a7.png)

**Comment by snipe** [comment]
That's not autoloading. (Autoloading has a specific meaning in PHP code.)

That just looks like the CSS/Javascript isn't loading. This usually means the APP_URL in the .env isn't correct, but you'd want to check your browser console for specific errors.

**Comment by FredrikHj** [comment]
Ok ;)

I have another problem now my fault. We have not config the mail and I have any password so I am lock out from snipe-i. I found this `[solver!](https://snipe-it.readme.io/docs/create-an-admin)`. I am using it but gets this fault, see image!

![2022-09-29 10_39_16-172 29 7 131 - Fjärrskrivbordsanslutning](https://user-images.githubusercontent.com/43028745/192983684-d0c7a3c5-1c39-4bf8-8260-e559438c7bde.png)

**Comment by snipe** [comment]
Can you show me your .env file, (obscuring any sensitive data like passwords)?

**Comment by FredrikHj** [comment]
That password is just a test one. Bellow is my config in the .env file:
`
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=[Hidden]
APP_URL='http://172.29.7.131'
APP_TIMEZONE='Europe/Stockholm'
APP_LOCALE=	sv-SE
MAX_RESULTS=500

# --------------------------------------------
# REQUIRED: UPLOADED FILE STORAGE SETTINGS
# --------------------------------------------
PRIVATE_FILESYSTEM_DISK=local
PUBLIC_FILESYSTEM_DISK=local_public

#PRIVATE_FILESYSTEM_DISK=s3_private
#PUBLIC_FILESYSTEM_DISK=s3_public

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=sniper-it
DB_USERNAME=sniperit_Admin
DB_PASSWORD=[Hidden]
DB_PREFIX=null
DB_DUMP_PATH='C:\xampp\mysql'
DB_CHARSET=utf8
DB_COLLATION=utf8_swedish_ci

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_IS_PAAS=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=email-smtp.us-west-2.amazonaws.com
MAIL_PORT=587
MAIL_USERNAME=YOURUSERNAME
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=you@example.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=you@example.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd


# --------------------------------------------
# OPTIONAL: BACKUP SETTINGS
# --------------------------------------------
MAIL_BACKUP_NOTIFICATION_DRIVER=null
MAIL_BACKUP_NOTIFICATION_ADDRESS=null
BACKUP_ENV=true
ALLOW_BACKUP_DELETE=false
ALLOW_DATA_PURGE=false

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_DRIVER=file
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false
API_TOKEN_EXPIRATION_YEARS=15

# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false
REFERRER_POLICY=same-origin
ENABLE_CSP=false
CORS_ALLOWED_ORIGINS=null
ENABLE_HSTS=false

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
QUEUE_DRIVER=sync
CACHE_PREFIX=snipeit

# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT=null

# --------------------------------------------
# OPTIONAL: MEMCACHED SETTINGS
# --------------------------------------------
MEMCACHED_HOST=null
MEMCACHED_PORT=null

# --------------------------------------------
# OPTIONAL: PUBLIC S3 Settings
# --------------------------------------------
PUBLIC_AWS_SECRET_ACCESS_KEY=null
PUBLIC_AWS_ACCESS_KEY_ID=null
PUBLIC_AWS_DEFAULT_REGION=null
PUBLIC_AWS_BUCKET=null
PUBLIC_AWS_URL=null
PUBLIC_AWS_BUCKET_ROOT=null

# --------------------------------------------
# OPTIONAL: PRIVATE S3 Settings
# --------------------------------------------
PRIVATE_AWS_ACCESS_KEY_ID=null
PRIVATE_AWS_SECRET_ACCESS_KEY=null
PRIVATE_AWS_DEFAULT_REGION=null
PRIVATE_AWS_BUCKET=null
PRIVATE_AWS_URL=null
PRIVATE_AWS_BUCKET_ROOT=null

# --------------------------------------------
# OPTIONAL: AWS Settings
# --------------------------------------------
AWS_ACCESS_KEY_ID=null
AWS_SECRET_ACCESS_KEY=null
AWS_DEFAULT_REGION=null

# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60

# --------------------------------------------
# OPTIONAL: FORGOTTEN PASSWORD SETTINGS
# --------------------------------------------
RESET_PASSWORD_LINK_EXPIRES=15
PASSWORD_CONFIRM_TIMEOUT=10800
PASSWORD_RESET_MAX_ATTEMPTS_PER_MIN=50

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
LOG_CHANNEL=single
LOG_MAX_DAYS=10
APP_LOCKED=false
APP_CIPHER=AES-256-CBC
APP_FORCE_TLS=false
APP_ALLOW_INSECURE_HOSTS=false
GOOGLE_MAPS_API=
LDAP_MEM_LIM=500M
LDAP_TIME_LIM=600
IMPORT_TIME_LIMIT=600
IMPORT_MEMORY_LIMIT=500M
REPORT_TIME_LIMIT=12000
REQUIRE_SAML=false
API_THROTTLE_PER_MINUTE=120
`

**Comment by snipe** [comment]
Do you actually have the [pdo](http://php.net/manual/en/pdo.installation.php) and [MySQLi](http://php.net/manual/en/mysqli.installation.php) extensions installed and enabled in your PHP install?

**Comment by FredrikHj** [comment]
Is not it default?
I will check.

**Comment by FredrikHj** [comment]
I have enable it. It works now :)

Thank you//
Best regards Fredrik

**Comment by FredrikHj** [comment]
We do I have other problem as well. The dashboard is not loaded correctly on another computer the dashboard is as the background at the right side.

**Comment by snipe** [comment]
I'm not sure what you mean - can you clarify?

**Comment by FredrikHj** [comment]
Hi

The above problem was solved. Today I got problem with xampp and the MariaDB server and I waass forced to start over with the snipe-it. I will start with MSSQL Server but get these in the Pre-Flight -->
"
Database 
Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (SQL: select 2 + 2)
"

Do I need something more in the .env file since the server sesams to need more security configuration?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
