### ISSUE TITLE
Not redirected to APP_URL but to non-HTTPS internal IP.

### ISSUE THREAD

**Issue by MaerlantGit** [grokability/snipe-it#11898]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I use a reverse proxy to access Snipe-IT. Everything works, except after I press the login button, I get redirected to the local IP of the Snipe-IT server.

The APP_URL variable is set to the URL of the server (not the IP). All other pages work perfectly.
I have enabled debugging but that doesn't change anything, as I don't see an error page.

The real weird thing is: It redirects me to to the HTTP IP adress, not the HTTPS IP adress (when I manually surf to the HTTPS IP address I get auto redirected to the APP_URL). 

But as the webserver is not serving the website over HTTP port 80, the browser times out.

### Reproduction steps

1. Go to login page via APP_URL
2. Fill username & password, click login
3. Wait a few seconds, get redirected to internal IP. Pages times out.
...

### Expected behavior

After succesful login, get redirected to APP_URL

### Snipe-IT Version

6.0.10

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Chrome

### Version

105

### Error messages

```shell
No errors, no logs.
```

**Comment by samotelf** [comment]
Hello. 
Did you take a look at https://snipe-it.readme.io/docs/reverse-proxies maybe it could help.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/reverse-proxies">Reverse Proxies</a></strong></div><div>If you wish to use a Reverse Proxy in front of your web server, you'll need to take a few extra steps to make it work. A typical Reverse Proxy scenario looks like this: Internet Reverse Proxy Server (Public &amp; Private IPs) Web Server (Private IPs) The Reverse Proxy Server is functioning as a reve...</div></blockquote>

**Comment by popcomputer** [comment]
I got this problem too when I use on sub-directory (https://domain/snipeit) when I click login button the browser redirect to main domain.
Please help for fix this.
