### ISSUE TITLE
Passwordless Azure AD Accounts Unable to Sign in via SSO

### ISSUE THREAD

**Issue by andrewlcbhs** [grokability/snipe-it#11914]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If an end user has an valid session where they authenticated their browser to a Microsoft service using "Passwordless Authentication" via Microsoft Authenticator and they attempt to SSO into Snipe It they are presented with the following error and are blocked from signing in.

`Request Id: Redacted
Correlation Id: Redacted
Timestamp: 2022-10-04T14:28:33Z
Message: AADSTS75011: Authentication method 'X509, MultiFactor' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'. Contact the Snipe IT application owner.`

If they open an incognito window and sign into a Microsoft service, portal.office.com, or go directly to Snipe IT (which sends them to a Microsoft login) and sign in using their email and password they can access Snipe IT and future SSO attempts work as intended while in the incognito window.

### Reproduction steps

1. Sign into Office 365 using passwordless auth via Microsoft Authenticator
2. Go to https://myinstance.snipe-it.io

### Expected behavior

SSO auth to seamlessly sign in user

### Screenshots

![Screen Shot 2022-10-04 at 9 46 05 AM](https://user-images.githubusercontent.com/51755172/193850843-88c0ca67-3ab8-4b05-86ad-a82c02d34d2e.png)

### Snipe-IT Version

v6.0.8 build 8409 (gff5d64fcb)

### Operating System

Hosted snipe-it.io deployment

### Web Server

Hosted snipe-it.io deployment

### PHP Version

7.4.30

**Comment by kevingoad-arcfield** [comment]
From: https://snipe-it.readme.io/docs/saml


Additional Azure AD Troubleshooting
Azure AD x509 Error
If you see an error like:

Sorry, but we're having trouble signing you in.

AADSTS75011: Authentication method 'X509, MultiFactor' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'. Contact the Snipe-IT application owner.

or

Sorry, but we're having trouble signing you in.

AADSTS75011: Authentication method 'Multifactor, Fido' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'. Contact the Snipe-IT application owner.

Add security.requestedAuthnContext=false to the "SAML Custom Settings" text box near the bottom of the SAML settings page. This should resolve the error.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/saml">SAML</a></strong></div><div>Configuration guidelines for SAML Single-Sign On (SSO) support</div></blockquote>

**Comment by andrewlcbhs** [comment]
This has fixed the error

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RobFullerGBHS** [comment]
Thanks this helped me.
