### ISSUE TITLE
LDAP sync disables user login for active users (and vice versa)

### ISSUE THREAD

**Issue by Robbindj** [grokability/snipe-it#11922]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Active/Enabled users in AD are marked as disabled from Login when doing an LDAP Sync.
After fixing the Admin accounts in the database directory to mark as Active it looks like all users are marked as not active.
While the few disabled accounts in AD are now marked as enabled.

We've always done an LDAP sync on the first workday of the month and the middle without issue for the last couple of years.
Only recent change was the removal of the old PHP folder, none of the dependancies in it were used by the new install, path variables and configurations had been adjusted about 7 months ago, restoring the folder also does not affect the LDAP sync.

**Workaround:**
Manually enter database and update Active column for relevant active accounts after LDAP update disables admin account.

**LDAP Config**
No LDAP sync errors and configuration has not been changed recently.
LDAP details appear to come in correctly.
Testing LDAP login works as well.
SAML works flawlessly when account is enabled as well.

### Reproduction steps

1. Perform LDAP Sync
2. After about 30 seconds or so get kicked back to login screen.
3. Unable to log back in, user not found in database (Debug Result)
4. Go to Database to find admin user in users, activated is set to 0
5. Set value back to 1, login and SAML working again
6. Go to people, notice all Active AD users are set to disabled, all disabled accounts on AD are set to login
...

### Expected behavior

Retain ability to login for all enabled AD accounts after performing LDAP sync, and for Disabled accounts to not remain active.

### Snipe-IT Version

6.0.10 - build 8610 (master)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.7

### Operating System

windows

### Browser

all

### Error messages

```shell
User not found in database
Not reproducable on Demo

php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
fileinfo
filter
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
soap
sodium
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib
```

### Additional context

Not a fresh install, several years old at this point, Attempted upgrade to see if this fixed the issue, however issue remains with LDAP sync disabling Active users.

**Comment by StefanoTmb** [comment]
Hi have the same problem.
All users I have are imported by ldap, when I have to resync to import new users, a few user had the abilty to login loose that permission.
This is annoyng for me as I have to reconfigure these users manually one by one

**Comment by 00shorty** [comment]
me too. Users get randomly the flag that the login is not enabled.
- removing the LDAP Active Flag setting did the trick for us

**Comment by uberbrady** [comment]
Agreed, whatever you've set as the 'active flag' is likely wrong. What that flags means is: "Look for the users. If they have _this specific attribute_ set to 'true' or '1' or 'yes' or 'enabled', then mark them as able-to-login. If they have _this specific attribute_ set to 'false' or '0' or 'blank' or _nonexistent_ - then mark them as not-able-to-login."

**Comment by xinput** [comment]
have the same issue:

we have this attribute in the AD:
![Screenshot 2023-06-21 073257](https://github.com/snipe/snipe-it/assets/11652924/25d70c24-1148-40f4-9599-820fea7d82f9)

Enabled users have this attribute set to true, disabled have this set to false.

when configuring this in LDAP Settings the expected behaviour according to the description would be that enabled users are able to login and disabled not:
![Screenshot 2023-06-21 073302](https://github.com/snipe/snipe-it/assets/11652924/3bf97420-d720-4ea7-aaeb-67d582b0334f)

Unfortunatelty thsi does not work as enabled users are not able to login anymore. 
Removing the setting in LDAP settings does not restore the ability to login again and I was in need to do it manually

**Comment by Robbindj** [comment]
Only just had time to look at this again and turns out this was caused by stuff on our end.
And it's pretty much like what @uberbrady said.

Multiple issues collaborated, but the key to take away was just leave it blank in favour of UAC.

Though I did make sure that $enabled_accounts in LdapSync.php matched with out expectations and it does.
