### ISSUE TITLE
[Feature Request]: Change name from "Delete" to "Archive" when first time change user status.

### ISSUE THREAD

**Issue by ByJacob** [grokability/snipe-it#11946]
### Is your feature request related to a problem? Please describe.

The current deletion of a user has two stages: disabling it and pernamental deletion. It is misleading to call the first stage "Delete", where in fact the user is only archived.

### Describe the solution you'd like

Change the name of the action for the first stage of 'disabling users' to "Archiving"

### Describe alternatives you've considered

You can also call this stage "Blocking" the user, but I do not know if this is a good name.

### Additional context

User settings:
![image](https://user-images.githubusercontent.com/23155811/194849661-e85062b6-cb1a-4e70-85f0-cc1d34a8444d.png)

User list:
![image](https://user-images.githubusercontent.com/23155811/194849827-e24ed653-07fb-4dbe-b261-c8853f44a8be.png)

**Comment by snipe** [comment]
This is not something we will implement. We already soft-delete users (as you’ll see if you go to the deleted users page). We use soft deletes throughout the system as we make very clear through our docs. We don’t have a concept of archived users.

**Comment by ByJacob** [comment]
I found the [documentation](https://snipe-it.readme.io/docs/purging-soft-deletes) you are talking about. However, in that case, the button should be labeled "Soft-Delete", because just "Delete" for someone who has not read the documentation (let's not kid ourselves, who reads the documentation ?) can mean permanemnte deletion. The definition of the word itself means erase: https://www.dictionary.com/browse/delete. The current name does not clearly indicate the action performed when the button is clicked.

<blockquote><img src="https://www.dictionary.com/assets/dictionary-social-logo-93d290770ddf5b8c309b6e5ce9dcaac9.png" width="48" align="right"><div><img src="https://www.dictionary.com/assets/favicon-dcom-d73532382d3943b0fef5b78554e2ee9a.png" height="14"> www.dictionary.com</div><div><strong><a href="https://www.dictionary.com/browse/delete">Definition of delete | Dictionary.com</a></strong></div><div>Delete definition, to strike out or remove (something written or printed); cancel; erase; expunge. See more.</div></blockquote>
