### ISSUE TITLE
[Feature Request]: Add Serial Number search in addition to Asset Tag

### ISSUE THREAD

**Issue by el-capitano** [grokability/snipe-it#11967]
### Is your feature request related to a problem? Please describe.

Sometimes you need to search by Serial Number instead of Asset tag, the top search field only returns asset with asset tag and not with serial number

### Describe the solution you'd like

I've already modified the code to search also for Serial number, but maybe this feature will become available in future versions as well

### Describe alternatives you've considered

In AssetsController.php

```
public function getAssetByTag(Request $request)
    {
        $topsearch = ($request->get('topsearch') == 'true');

        if (! $asset = Asset::where('asset_tag', '=', $request->get('assetTag'))->orWhere('serial', '=', $request->get('assetTag'))->first()) {
            return redirect()->route('hardware.index')->with('error', trans('admin/hardware/message.does_not_exist'));
        }
        $this->authorize('view', $asset);

        return redirect()->route('hardware.show', $asset->id)->with('topsearch', $topsearch);
    }

```

**Comment by jayavman** [comment]
Why dont you use the second search field? the top asset search is for assets. the second search field is for everything else
<img width="437" alt="Screen Shot 2022-10-14 at 9 46 11 am" src="https://user-images.githubusercontent.com/114973646/195724349-3a3473c2-45ca-45a7-b41f-3e14ff82cb3f.png">

**Comment by snipe** [comment]
s/assets/asset_tag

**Comment by MWR-Napavine** [comment]
The workaround is to use the second search field. Go to "All Assets" and then use the internal search field, and you'll find your serial number. 

The reason it might be nice to have a matching result appear in the general Search is that sometimes you come across an asset in the field without it's asset tag, but you do have a scannable serial number. Most other Asset Tracking programs allow you to do a search for either, so it's quick to find items. Since Snipe doesn't do this, it's a couple clicks more.

I'm all for having this as a feature. Even if it's an option you can enable in the settings: "Allow Search to match Asset ID or Serial Number."

**Comment by jayavman** [comment]
> The workaround is to use the second search field. Go to "All Assets" and then use the internal search field, and you'll find your serial number.
> 
> The reason it might be nice to have a matching result appear in the general Search is that sometimes you come across an asset in the field without it's asset tag, but you do have a scannable serial number. Most other Asset Tracking programs allow you to do a search for either, so it's quick to find items. Since Snipe doesn't do this, it's a couple clicks more.
> 
> I'm all for having this as a feature. Even if it's an option you can enable in the settings: "Allow Search to match Asset ID or Serial Number."

Isn't this exactly what i just said?

**Comment by el-capitano** [comment]
I know about 2nd search field, but sometimes you're not browsing the All Assets page so you may want to quickly scan a product and it happens that you scanned the serial number, in this case you will have to re-scan again inside the All Assets when the page shows you an error that product doesn't exist. If it can be implemented in future versions, this will make it easier

**Comment by snipe** [comment]
This has been discussed extensively here in other tickets. It's not currently on the short term roadmap at this time.
