### ISSUE TITLE
Bk Up error

### ISSUE THREAD

**Issue by GKTT** [grokability/snipe-it#11970]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

 when i try to back up i get this error message 👍 

 Error: Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified. . #0 C:\xampp\htdocs\snipe-it\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 C:\xampp\htdocs\snipe-it\vendor\spatie\db-dumper\src\Databases\MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'C:\\xampp\\htdocs

### Reproduction steps

1.i pressed generate backup and received the error
2.
3.
...

### Expected behavior

a back up was to be generated of the assets in the data base

### Screenshots

![image](https://user-images.githubusercontent.com/115736083/195674762-a83878a2-9c31-40dd-8630-82aa89cd4c29.png)
![bkup error](https://user-images.githubusercontent.com/115736083/195674998-2b637083-d08f-4561-a34e-6495cfb2682e.PNG)

### Snipe-IT Version

Snipe-IT versionv5.1.5 build 6029 (gb8c356443)Software LicenseAGPL3

### Operating System

windows 10

### Web Server

Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.29

### PHP Version

PHP version: 7.4.29

### Browser

Chrome

**Comment by jayavman** [comment]
In the meantime, Just take a SQL Download (in phpadmin) and if you have cpanel just a full website backup.
