### ISSUE TITLE
Company support

### ISSUE THREAD

**Issue by eliecerserna** [grokability/snipe-it#11994]
### Is your feature request related to a problem? Please describe.

Does anyone know how I can give permissions to a user so that they only see the devices of one company?

I have the inventory of two different companies, I want to be able to create a user for each company and that he only sees the devices that belong to his company, I have played with the permissions but the two users continue to see all the devices.

### Describe the solution you'd like

I want to be able to assign permissions by company not that all users can see everything

**Comment by snipe** [comment]
I believe what you're looking for is Full Multiple Company Support:
https://snipe-it.readme.io/docs/general-settings#full-multiple-companies-support

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/general-settings#full-multiple-companies-support">General Settings</a></strong></div><div>The General Settings panel allows you to configure aspects of your install such as Full Company Support, whether or not to require physical (digital) signatures on assets, and so on. Snipe-IT offers a sort of multi-tenancy within the application, which allows super-admins to restrict the assets non-...</div></blockquote>
