### ISSUE TITLE
Trying to upload .csv and error with artisan

### ISSUE THREAD

**Issue by itsupport-Stuart** [grokability/snipe-it#12003]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,

I'm trying to upload a asset file into our snipeit, but I'm receiving the following error:

`Could not open input file: artisan`

Any idea why this happen?

### Reproduction steps

1. Verified installation of composer
2. Verified I can access to my server.
3.
...

### Expected behavior

After typing the command `php artisan snipeit:import /home/ubuntu/upload1.csv` I receive the error "Could not open input file: artisan.

### Snipe-IT Version

 Version v6.0.11 - build 8758 (master) 

### Operating System

ubuntu server 22.04

### Web Server

Apache

### PHP Version

PHP 8.1.11

**Comment by snipe** [comment]
If I had to guess, you're probably trying to run the artisan command from somewhere other than your Snipe-IT webroot. Artisan will only work from the Snipe-IT directory.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
