### ISSUE TITLE
Landing page is not working

### ISSUE THREAD

**Issue by cookierun22** [grokability/snipe-it#12007]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,

I am facing this issue where when I log into the system, the landing page become empty.

![image](https://user-images.githubusercontent.com/115517803/197086151-affc3654-2fcf-43a7-85d9-aee2cc4bc8f0.png)

### Reproduction steps

1. Run the command php upgrade.php
2. Restart the apache server
3. Try to login into the system
4. Key in the username and password
5. The landing page is empty
...

### Expected behavior

The system supposedly shows the dashboard.

### Screenshots

![image](https://user-images.githubusercontent.com/115517803/197086386-f82743cc-5f5c-4cba-bbcb-edb66dd9ebd1.png)

### Snipe-IT Version

v6.0.10

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.10

**Comment by snipe** [comment]
Without additional error logs, I'm not sure how we would help you with this.
