### ISSUE TITLE
Images don't appear on "check-in" mails; only on "check-out"

### ISSUE THREAD

**Issue by KCarette82** [grokability/snipe-it#12002]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I do a "check-out", the end user receives an e-mail with the picture of the asset.
On a "check-in" for the same asset, the e-mail lacks the picture and a red cross is displayed

### Reproduction steps

Check-out & check-in

### Expected behavior

Images should be visible in all e-mails

### Screenshots

![image](https://user-images.githubusercontent.com/106228119/196972253-151fcaa0-2d48-4049-9f31-8a8daa0b2806.png)

![image](https://user-images.githubusercontent.com/106228119/196972387-b3f6fae5-064e-4914-a5bb-e6bcc0e0c383.png)

### Snipe-IT Version

6.0.12

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

**Comment by brianhoganm** [comment]
I also get this as well.

**Comment by bancom22** [comment]
I also get this as well.

**Comment by snipe** [comment]
This has already been fixed. Please update to latest on master.
