### ISSUE TITLE
Can not connect to REMOTE mySQL Database

### ISSUE THREAD

**Issue by jcookatlas** [grokability/snipe-it#12010]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When attempting 'basic' install - except using REMOTE mySQL server (installed mysql-client vs. mysql-server) the compose build works and I can get to the pre-flight check page... On Pre-Flight I receive an error stating "SQLSTATE[HY000] [1045] Access denied for user 'snipe_it_user'@'XX.XX.XX.XX' (using password: YES) (SQL: select 2 + 2)'.

From the mysql cli on the snipe-it application server, I can successfully log into the remote mysql server as 'snipe_it_user'@'XX.XX.XX.XX' AND when executing SHOW GRANTS in mysql CLI, the server responds: GRANT ALL PRIVILEGES ON `snipe_it`.* TO `snipe_it_user`@`XX.XX.XX.XX` WITH GRANT OPTION (using the same credentials that are in .env).

UFW is inactive on BOTH snipe-it application server and mysql server (for testing purposes in an isolated environment)

- Tailing larvel logs reveals nothing.
- Console reveals nothing

Pre-Flight Error Message:

![pre-flight error](https://user-images.githubusercontent.com/95373373/197236891-1434a1c5-6a44-4d71-aa70-24b5814a568d.jpg)

mySQL CLI Responce:

![mysql show grants from snipe-it vm](https://user-images.githubusercontent.com/95373373/197236948-d235b063-ebdb-4d42-9d8a-70910fd05cfa.jpg)

### Reproduction steps

1. Tried install again
2.
3.
...

### Expected behavior

Should connect to REMOTE (same sub-net) mysql server.

### Snipe-IT Version

As GIT cloned 21-OCT-2022

### Operating System

Ubunt 20.0.4

### Web Server

Apache2

### PHP Version

7.4.3

### Operating System

Windows 11

### Browser

Firefox

### Error messages

```shell
php -m:
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

Fresh install

**Comment by jcookatlas** [comment]
Please dis-regard... I'm a dummy...

I have special characters in the password and had not encapsulated them properly in quotations in the .env configuration file.

Turns out that non-quotation encapsulated special characters NeVeR EvEr pass through properly...

Sorry for the inconvenience.  Please disregard.

**Comment by snipe** [comment]
Glad you're sorted :)
