### ISSUE TITLE
[Feature Request]: Custom Fields in poeple - please :)

### ISSUE THREAD

**Issue by ArekOlejniczak** [grokability/snipe-it#12022]
### Is your feature request related to a problem? Please describe.

I need add some custom fields to 'poeple', or posibility change name of existing fields?

### Describe the solution you'd like

Add some custom fields to people

### Additional context

I have to add additional information, e.g. identification number (e.g. in Poland it is PESEL) and this is classified data.

**Comment by brianhoganm** [comment]
Would love this feature! We have over 20 thousand students and being able to add additional fields would be very beneficial.

**Comment by snipe** [comment]
This is actually a duplicate of #4261
