### ISSUE TITLE
"405 Method Not Allowed" when trying to restore an asset that has been deleted

### ISSUE THREAD

**Issue by smoon53** [grokability/snipe-it#12023]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am trying to restore an asset that has been deleted and I keep getting the following error:

Oops! An Error Occurred
The server returned a "405 Method Not Allowed".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Everything else in my SNIPE-IT environment works flawlessly, so I am not sure what the issue is. I am not a programmer, so a lot of what is in the debug mode doesn't make sense to me. Thanks for any help you can provide! 

### Reproduction steps

1. Delete Asset
2. Attempt to restore Asset
3. Error
...

### Expected behavior

Expected behavior is for asset to be restored. 

### Snipe-IT Version

v6.0.1 build 7863 (g90a4ce572)

### Operating System

Ubuntu 20.04.5 LTS

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows 10

### Browser

Microsoft Edge

### Version

106.0.1370.52 (Official build) (64-bit)

### Error messages

```shell
I see this in Stack trace under the Debug section

Since symfony/http-foundation 5.2: The "HEADER_X_FORWARDED_ALL" constant is deprecated, use either "HEADER_X_FORWARDED_FOR | HEADER_X_FORWARDED_HOST | HEADER_X_FORWARDED_PORT | HEADER_X_FORWARDED_PROTO" or "HEADER_X_FORWARDED_AWS_ELB" or "HEADER_X_FORWARDED_TRAEFIK" constants instead. in /var/www/snipeit/vendor/symfony/deprecation-contracts/function.php on line 25
```

**Comment by smoon53** [comment]
Also, I get this error under Exceptions when debugging (hope this helps): 

The POST method is not supported for this route. Supported methods: GET, HEAD.
/var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php#117
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
     */
    protected function methodNotAllowed(array $others, $method)
    {
        throw new MethodNotAllowedHttpException(
            $others,
            sprintf(
                'The %s method is not supported for this route. Supported methods: %s.',

**Comment by snipe** [comment]
I'd probably try upgrading. 6.0.1 was a while ago, and lots of things have been fixed since then.

**Comment by smoon53** [comment]
I ended up making a backup last night and doing a fresh install. Everything is working as intended now! Thanks for the advice!

**Comment by smoon53** [comment]
I ended up making a backup last night and doing a fresh install. Everything is working as intended now! Thanks for the advice!

**Comment by Qazcvbnm** [comment]
https://demo.snipeitapp.com/models/19/restore

Oops! An Error Occurred
The server returned a "405 Method Not Allowed".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.


<blockquote><div><strong><a href="https://demo.snipeitapp.com/models/19/restore">An Error Occurred: Method Not Allowed</a></strong></div></blockquote>

**Comment by SFazeem** [comment]
same issue occuring - what is the manual fix without rebuild fresh one ?.
