### ISSUE TITLE
Maximum Upload Size for Backup 

### ISSUE THREAD

**Issue by cookierun22** [grokability/snipe-it#12034]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The original maximum file upload for backups is only 2M.
However, I have changed the maximum size to 8M in php.ini file.
So, I was able to upload the backup file as per screenshots.
![image](https://user-images.githubusercontent.com/115517803/197924261-b5a6d7a6-e0db-4f60-a853-390a4722c1e3.png)

But when I try to restore, there is an error as below.
![image](https://user-images.githubusercontent.com/115517803/197924353-8bd70106-92a0-47b2-ab6e-003dfe6be9d4.png)

### Reproduction steps

1. Change the maximum file upload for backups in php.ini
2. Able to upload more than 2M file.
3. But when try to restore, server error 500 happen.
...

### Expected behavior

The backup file should be able to restore

### Snipe-IT Version

v6.0.10

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.10

**Comment by snipe** [comment]
What is the specific error in the logs?

**Comment by snipe** [comment]
There are generally three values you want to change in your .ini file:

```
upload_max_filesize = 264M
post_max_size = 264M
memory_limit = 264M
```

**Comment by jdkmzhn** [comment]
Is 246M the highest possible value? If i have 1000 Assets with Attachements (pdfs) it will not reach out

**Comment by MaKaNu** [comment]
What about Docker setups? Can this be exposed via `.env`?

**Comment by derekschartung** [comment]
> What about Docker setups? Can this be exposed via `.env`?

Same question. We are trying to restore to a fresh docker env. Getting a filesize error since our backup is 9MB.

**Comment by MaKaNu** [comment]
@derekschartung I realized, that I needed to migrate manually. It is a bit tricky since the locations are a bit different to standalone installation, but here the short version: 

- extract the backup.zip.
- Search the Volume for the data locations
- parse the dump into the database container

**Comment by derekschartung** [comment]
> @derekschartung I realized, that I needed to migrate manually. It is a bit tricky since the locations are a bit different to standalone installation, but here the short version:
> 
> * extract the backup.zip.
> * Search the Volume for the data locations
> * parse the dump into the database container

Thanks for update. I added a env variable for PHP upload limit and that worked for us. 
PHP_UPLOAD_LIMIT=50

**Comment by MaKaNu** [comment]
> Thanks for update. I added a env variable for PHP upload limit and that worked for us.
PHP_UPLOAD_LIMIT=50

To the docker compose of the application container?
