### ISSUE TITLE
Custom field checkboxes not holding value

### ISSUE THREAD

**Issue by mrdanleey** [grokability/snipe-it#12046]
I have a problem now with my custom Checkbox field and the following values:

BIOS wachtwoord ingesteld
Computernaam ingesteld
Image geïnstalleerd op de laptop
BIOS-update geïnstalleerd

I can check every checkbox and the changes are saved in de database but not returned (no checkmarks) when I edit the asset.
I found this change and tried what is does if I revert it in my installation of Snipe-IT. After the reverse I see the checkmarks. So
this is a bug from a bugfix i guess?

I'm using the newest version of Snipe-IT (6.0.12), PHP 8.1.12, Laravel 8.83.25)
Tried other PHP-versions also.

_Originally posted by @mrdanleey in https://github.com/snipe/snipe-it/pull/11925#issuecomment-1297214639_

**Comment by snipe** [comment]
@mrdanleey We have an issue template for a reason. Please use it next time. You literally had to delete the template that we provide that gives us the information we need to help you. 

@inietov - I believe you last worked on this - can you take a look?
