### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by dataprotechgroup** [grokability/snipe-it#12051]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am getting a few “500 Server Errors” when I try certain things example is if I go to settings > asset models when I then click “create new” I get the 500 error. 

### Reproduction steps

settings > asset models > create new

### Expected behavior

Not showing 500 error.

### Snipe-IT Version

v6.0.10

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

PHP 7.4.3

### Browser

Google Chrome

**Comment by zaincassim** [comment]
I have this issue as well, but I'm running v6.0.12 on a Windows Server with PHP 8.1

**Comment by xinput** [comment]
did you check if bootstrap/cache directory is writeable by the apache/IIS user? 

so ideally your permissions must be 755 with owner snipeit:apache .

Same aplies to Windows
directory must be writeable by ISUSR 

also check to clear your application cache with php artisan cache:clear

**Comment by zaincassim** [comment]
@xinput Thank you! It was the permissions in my case!

**Comment by snipe** [comment]
If you run `php upgrade.php` it will usually try to troubleshoot these types of problems.
