### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Bilal4Tech** [grokability/snipe-it#12052]
### Is your feature request related to a problem? Please describe.

If this feature is already available, I haven't found it. 

Snipe is quite new to me and I haven't found a way to disable customer e-mail notification of check-in and check-out assets. I wish to disable this because I want to repair our database without mass spamming the entire company, many of them haven ot been assigned assets or have been assigned wrong ones, so to prevent confusion I wish to disable it temporarily. 

Is there any way to already realize this? Through a work around perhaps?

### Describe the solution you'd like

A checkbox of sorts which disables check-out and check-in e-mail notification to customer.

**Comment by snipe** [comment]
This is based on category level settings:  

<img width="993" alt="Screen Shot 2022-11-02 at 2 44 55 PM" src="https://user-images.githubusercontent.com/197404/199608503-6e5b136d-1246-4d7f-8672-7ccb31c221ae.png">
