### ISSUE TITLE
[Feature Request]: Custom Profile Label, EULA and Warranty Expired Date

### ISSUE THREAD

**Issue by x3inspire** [grokability/snipe-it#12061]
### Is your feature request related to a problem? Please describe.

**Custom Profile Label**
Current label available is only one label, some asset required different size for label and need to adjust the size following the asset name leght etc.

**Custom Profile EULA**
Also only available as default EULA, for new EULA we have to write it ourself.

**Warranty Expired Date**
Right now no option for select warranty expired date, what we have is only warranty in "Month"

### Describe the solution you'd like

**Custom Profile Label**
If we can create profile label, we just can select which profile label before generate the asset.

**Custom Profile EULA**
If we can create profile for EULA, we just can select which profile EULA for each asset before check out to user/location.

**Warranty Expired Date**
Add warranty expired date option (with calendar function) in asset detail or during create new asset.

**Comment by snipe** [comment]
These are three different, unrelated issues. Please create different issues for each request.
