### ISSUE TITLE
Mail-Template missing translation strings

### ISSUE THREAD

**Issue by magiausde** [grokability/snipe-it#12064]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When sending an user his checked out items, it will always show "Inventory Report" as the Title.
The footer always states "All rights reserved." - Regardless of the language.
It seems the translation string is missing.

### Reproduction steps

1. Use a non-english language
2. Send an user his checked out items

### Expected behavior

The mail title should be translated
The footer should be translated

### Snipe-IT Version

v6.0.12

### Operating System

Debian

### Web Server

Apache

### PHP Version

8.0

**Comment by snipe** [comment]
This had been merged to develop
