### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by aleksorlov** [grokability/snipe-it#12074]
### Is your feature request related to a problem? Please describe.

Creating new Status Labels using type  "Deployable: These assets can be checked out. Once they are assigned, they will assume a meta status of  Deployed." Doesn't show in "List all"

### Describe the solution you'd like

When creating new naming conventions under status labels specifically for a Deployable status. Can it be seen in list all?

### Describe alternatives you've considered

Having it available at the side nav is okay i guess. Just a little unintuitive to leave List all to find a deployable asset

**Comment by aleksorlov** [comment]
It was an upload issue not a snipe-IT issue. Thank you for all the wonderful work on the platform

**Comment by snipe** [comment]
Glad you got it sorted!
