### ISSUE TITLE
[Feature Request]: Google sign-in option

### ISSUE THREAD

**Issue by nikomatjasic** [grokability/snipe-it#12076]
### Is your feature request related to a problem? Please describe.

Option for users to log in with a Google account.

### Describe the solution you'd like

Implement 3rd service login on a project.

### Describe alternatives you've considered

Develop laravel/socialite login structure.

### Additional context

Add variables in the .env file:
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT='http://127.0.0.1:8000/auth/google/callback'

Images with the example of the steps:

<img width="394" alt="logIn" src="https://user-images.githubusercontent.com/70574708/200564304-5e2a06b8-b7cb-4351-b367-621ba97161de.png">
<img width="468" alt="selectAccount" src="https://user-images.githubusercontent.com/70574708/200564300-7fa58dd6-a0c7-4458-9fd0-3bd1273f4b40.png">

<img width="1316" alt="loggedIn" src="https://user-images.githubusercontent.com/70574708/200564280-4e03dfad-919e-482f-846a-59bd2008af5a.png">

**Comment by nikomatjasic** [comment]
Here is the PR -> https://github.com/snipe/snipe-it/pull/12077

**Comment by snipe** [comment]
This was added a few months ago
