### ISSUE TITLE
[Feature Request]: Upload Files tab accès in Users table

### ISSUE THREAD

**Issue by Tritton74** [grokability/snipe-it#12086]
### Is your feature request related to a problem? Please describe.

Hello, I regularly upload user documents (IT Charter, contract, etc.)

And i can't see quickly which user i have forgot

### Describe the solution you'd like

 I would like to be able to display the number of uploaded files in the user table (just as the number of assets can be displayed).

And when i will click in the number, i will be redirect to the Uploaded files page of the user.
![Example](https://user-images.githubusercontent.com/79106616/200873393-bec1d6d1-d609-4da3-bbbd-f069c8b48331.png)

### Additional context

Thanks so much for your soft, i Love it !

**Comment by Tritton74** [comment]
up ? @snipe

**Comment by snipe** [comment]
This isn't really as easy as it sounds, since uploads are held only in the action log, and that query gets very difficult to search/sort on, since it's through a pivot table, files may have been deleted, etc. I don't see this on the short term roadmap, unfortunately.
