### ISSUE TITLE
Error 500 after user login

### ISSUE THREAD

**Issue by karoliskralis** [grokability/snipe-it#12111]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

user request the page snipeit/account/view-assets

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Fix

### Screenshots

![image](https://user-images.githubusercontent.com/105273892/201868113-dec5ca9d-3486-48d9-b99a-ba8ab0c80ba2.png)

### Snipe-IT Version

6.0.13

### Operating System

Ubuntu

### Web Server

apache

### PHP Version

PHP 7.4.3

### Operating System

Windows

### Browser

Google Chrome

**Comment by karoliskralis** [comment]
![image](https://user-images.githubusercontent.com/105273892/201873167-80b26a93-f248-4d46-b767-26acb3187209.png)

**Comment by sikuminalex-eng** [comment]
Hi,
I hvae same problem.
After trying several times, I found that an error occurs if I do not grant superuser or admin privileges.

**Comment by karoliskralis** [comment]
hi i repair it, 
in this file app/Http/Controllers/DashboardController.php
edit this from return redirect()->intended('account/view-assets');
to this
return redirect()->intended('hardware');
and all will be fine

**Comment by sikuminalex-eng** [comment]
thank you so much!
i tried to change the code like that,and my problem also solved!

**Comment by hareminc** [comment]
hi guys. We have the same problem. I attempted to change the code but received the same error. The "view assets" error persists. Please, guys, help.

**Comment by snipe** [comment]
This is already fixed on master and develop.

**Comment by Pkumar22in** [comment]
Will it get fixed with an upgrade if I run?

**Comment by snipe** [comment]
Yes
