### ISSUE TITLE
[Feature Request]: UI/UX - Add link back to Asset after (update|checkin|checkout|whatever)

### ISSUE THREAD

**Issue by MWR-Napavine** [grokability/snipe-it#12138]
### Is your feature request related to a problem? Please describe.

There are times where I need to reassign an asset, or go back to an asset after an edit for whatever reason. Currently I have to re-type the Asset Tag back in to get back to its' page.

### Describe the solution you'd like

It would be very easy to just have a link to the asset right in the green "Success" header after any asset update, checking or checkout.

### Additional context

For example. I would update the following line:

> Success: Asset checked in successfully.

so that it would now say this, with a link back to the asset:

> Success: Asset (**101234**) checked in successfully.

![image](https://user-images.githubusercontent.com/48335860/202518967-929b70f2-bb4d-4ac5-a518-cd6b878c20f3.png)

Do this for ALL of the different prompts, so that it is easy to jump back to the asset just updated, edited, checked in, or checked out.

**Comment by Oddalmighty** [comment]
I second this feature. It becomes time consuming when I have several devices that need to be checked in and then reassigned. I have to keep typing the asset number in after each 'action'.

**Comment by snipe** [comment]
It's not actually that easy though - we would have to update hundreds of translation strings to include the url parameter for the link, change all of the skins to reflect the link color, etc. 

It's a good idea (and is on the roadmap, though solved slightly differently), but it's not actually "easy".

**Comment by MWR-Napavine** [comment]
My apologies for my assumption that it would be easy to implement.

I am glad to hear this is on the roadmap. I look forward to it.

**Comment by MWR-Napavine** [comment]
Just checking in on this; Looks like the new behavior for Checkin/Checkout brings you back to the Asset in question... which is excellent and satisfies my request. Thus, I'm closing this as resolved.

Thanks everyone.
