### ISSUE TITLE
Problem about status logic

### ISSUE THREAD

**Issue by BlueNoob** [grokability/snipe-it#12136]
### Describe the bug

# Problem about status logic
### 
From what I understood, `Ready to deploy` should means it can be deployed to employee, so I think there is some mistake in your logic.
When an asset was assigned to an employee, the label should ba `assigned` .
Even there is no need to exist two labels as below, 

![](https://i.imgur.com/UI0f8eh.png)

### Expected behavior

![](https://i.imgur.com/UI0f8eh.png)

**Comment by snipe** [comment]
The logic works as intended and described. https://snipe-it.readme.io/docs/overview#status-labels

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/overview#status-labels">Overview</a></strong></div><div>When your Snipe-IT installation is first set up, it can be a little overwhelming to figure out where to get started. The first place to start is usually your Admin Settings. We go through each of the specific admin options one by one in the Admin Settings section of this documentation, but that's wh...</div></blockquote>

**Comment by BlueNoob** [comment]
> The logic works as intended and described. https://snipe-it.readme.io/docs/overview#status-labels
> 
> > <img alt="" width="48" src="/favicon.ico">Snipe-IT Documentation**[Overview](https://snipe-it.readme.io/docs/overview#status-labels)**When your Snipe-IT installation is first set up, it can be a little overwhelming to figure out where to get started. The first place to start is usually your Admin Settings. We go through each of the specific admin options one by one in the Admin Settings section of this documentation, but that's wh...

Yes, I know, but I think it's not good enough.
After deployed, you cannot filter with those `Deployed` in your system at present.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/overview#status-labels">Overview</a></strong></div><div>When your Snipe-IT installation is first set up, it can be a little overwhelming to figure out where to get started. The first place to start is usually your Admin Settings. We go through each of the specific admin options one by one in the Admin Settings section of this documentation, but that's wh...</div></blockquote>

**Comment by BlueNoob** [comment]
And pending is more like a `process label`, not a `status label`.

**Comment by BlueNoob** [comment]
I'm sorry but I have different understatning with you about the label. 
## Process Label (logical):
`Deployed` means already `Assigned` to someone
`Pending`
`none lablel`

## Status Label (physical):
`deployable` means `healthy`
`bad`
`lost`
`achieved`

## Defects Now
In the system now, you cannot filter those are `deployable` and `not deployed`
