### ISSUE TITLE
Checkbox values with spaces do not stay checked when editing

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#12137]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Custom field checkbox values that contain spaces always default to unchecked when editing an asset. This can be easily reproduced on the current demo.

Any checkbox values that do not contain spaces will still work correctly when mixed with values that do contain spaces (IE, they stay checked).

### Reproduction steps

1. Create a new custom field containing a checkbox value that has at least one space in it.
2. Assign the custom field to a model.
3. Create a new asset with the model containing the checkbox custom field, checking one of the values that contains a space.
4. Edit the newly created asset, observing the value changes back to being unchecked.
...

### Expected behavior

Checkbox values with spaces should behave the same as checkbox values without spaces.

### Snipe-IT Version

6.0.13

### Operating System

Whatever the demo uses

### Web Server

Whatever the demo uses

### PHP Version

Whatever the demo uses

### Additional context

This may have been introduced in a recent update; I don't remember encountering the issue before October or so.

Edit: Could not reproduce on my test docker instance running v6.0.8 (build 8409).

**Comment by snipe** [comment]
@inietov i thought we had already fixed this - can you take a look?

**Comment by ghost** [comment]
> @inietov i thought we had already fixed this - can you take a look?

I confirmed it today on the demo and our snipe-it.io hosted instance before submitting the report. I just updated a snipeit:develop docker instance with v6.0.13 (build 8923) and it's happening there too. But it's not happening on an older docker instance still running v6.0.8 (build 8409), so I suspect it's a regression.

Edit: Looks like it may have been #11710. I think the brackets define a set and it's splitting on a space. Either `preg_split(', |,')` or `preg_split(',\s?')` should work.
