### ISSUE TITLE
Asset Acceptance Notification - Says invalid date value next to date

### ISSUE THREAD

**Issue by jairzee-trio** [grokability/snipe-it#12144]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi Guys, 

Thanks for fixing the Checkin email image issue!

I've just noticed another weird one, on the asset acceptance email, next to the 'Accepted' date, I am getting a message next to the date that says '(Invalid date value.)' even though it is correct

I'm wondering if it is because I am UK-based?

Screenshot below:

![Screenshot 2022-11-18 at 11 33 14](https://user-images.githubusercontent.com/117661671/202696708-72bdf76b-85bb-4d39-81fc-5b3f64c3c249.png)

Is this another bug or is there something I need to do on my end?

Thanks,

Jordan

### Reproduction steps

1. Enable user acceptance digital signature
2. Check device out to user
3. Accept and sign the acceptance email
4. User Acceptance notification email is then sent - which contains the invalid date message

### Expected behavior

Just to display the date and not have '(Invalid date value.)' next to it

### Screenshots

![Screenshot 2022-11-18 at 11 33 14](https://user-images.githubusercontent.com/117661671/202697106-f329ee29-e578-483f-bb50-c0deb551adbc.png)

### Snipe-IT Version

v6.0.13 build 8923 (g30f4af3ac)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.12

**Comment by snipe** [comment]
That sounds like it’s a different issue? Can you create a new GH issue here with that and we’ll get it handled.

It definitely shouldn’t be because you’re UK based. Time stamps are stored in the DB as YYYY-MM-DD regardless of how you choose to output them on screen or in email, so something funny might be happening here.

**Comment by jairzee-trio** [comment]
I have already raised this as a new git hub issue 😊  - this thread is a new issue

Thanks!

Jordan

**Comment by Godmartinz** [comment]
I don't see this occurring anymore. Is this still an issue for you @jairzee-trio ?
