### ISSUE TITLE
Remove / clear Expected Checkin Date

### ISSUE THREAD

**Issue by wijjsm** [grokability/snipe-it#12150]
### Is your feature request related to a problem? Please describe.

Cannot clear/remove Expected Checkin Date on an Asset.

### Describe the solution you'd like

Ability to clear/remove Expected Checkin Date on an Asset

### Describe alternatives you've considered

Keep moving the Expected Checkin Date forward

**Comment by BlueNoob** [comment]
What confuse you?

**Comment by wijjsm** [comment]
I can't remove an Expected Checkin Date for an asset: 

![image](https://user-images.githubusercontent.com/89761467/203166278-b800399b-442f-409a-821e-38be3880e63a.png)

**Comment by snipe** [comment]
Please fill in the rest of the questions we ask in the issue template. I can't tell what version you're running, by which method you are trying to remove the date, etc.

**Comment by snipe** [comment]
If you're using a modern version of Snipe-IT, you just click in the date field and select the "clear" option.

<img width="433" alt="Asset_Update____Snipe-IT_Demo-2" src="https://user-images.githubusercontent.com/197404/203373355-b12ee8cd-428d-4152-a27b-1c8f76f1e155.png">
