### ISSUE TITLE
[Feature Request]: Asset age calculation

### ISSUE THREAD

**Issue by PandiarajanSelvaraj** [grokability/snipe-it#12163]
### Is your feature request related to a problem? Please describe.

Hi Team,

I am new to snipe-it. I am looking for a feature, that to display the current aging of the asset.

Is there any way to get this in asset.

Snipe-IT version-v6.0.13 build 8923 
PHP Version - 7.4.33
Laravel Version - 8.83.26
DB - MariaDB 

Kindly let me know if need any other details.

### Describe the solution you'd like

Example: A column that shows the age of the laptop by calculating purchase date minus current date is equal to age.
Purchase date = 25/06/2020
Current date = today (ie 23/11/2022)
Age = 2yr 4m 29days

**Comment by PandiarajanSelvaraj** [comment]
Hi,

Any help or update on this?

**Comment by nikomatjasic** [comment]
Hi, @PandiarajanSelvaraj  on which page are you talking? On the asset edit page, under the purchase date? Please let me know.
<img width="883" alt="Screenshot 2022-11-24 at 10 11 44" src="https://user-images.githubusercontent.com/70574708/203743688-8efb29c2-f38f-47c4-aa7d-2fc39951d9a2.png">

**Comment by PandiarajanSelvaraj** [comment]
Hi @nikomatjasic,

Thanks for the reply. I am looking a hidden field that calculate the age from given purchase date in asset.

**Comment by nikomatjasic** [comment]
Sorry, can you please provide any page or example, where the hidden field/field would fit in? Thanks.

**Comment by PandiarajanSelvaraj** [comment]
@nikomatjasic , In asset create page we will provide purchase date right. if then the snipe-it have to calculate the age by system current date. below is the example. 

Example: A column that shows the age of the laptop by calculating purchase date minus current date is equal to age.
Purchase date = 25/06/2020
Server Current date = today (ie 24/11/2022)
Age = 2yr 4m 30days (this should be display in the added column)
<img width="910" alt="Screenshot 2022-09-28 133130" src="https://user-images.githubusercontent.com/118899534/203749331-09f4bae2-ca3a-4d3c-b926-cadab483b0ed.png">

**Comment by PandiarajanSelvaraj** [comment]
As same as like, how we give purchase date and warranty months system showing warranty expires.

<img width="292" alt="Screenshot 2022-09-28 133130" src="https://user-images.githubusercontent.com/118899534/203750327-25b82495-54a4-44f8-b8f9-016a2d5276b2.png">

**Comment by PandiarajanSelvaraj** [comment]
@snipe Can you please help on this..

**Comment by Godmartinz** [comment]
I've just added a PR to add the requested changes @PandiarajanSelvaraj. Thanks for the suggestions 🙂

**Comment by Godmartinz** [comment]
I'm going to close this for now, but do reopen if you have any other concerns.

**Comment by PandiarajanSelvaraj** [comment]
Hi @Godmartinz ,

Thanks for the update and changes done.

Kindly let me know how can I get this feature in my existing setup. I have to do any changes in the configuration ?

**Comment by snipe** [comment]
@PandiarajanSelvaraj it is not possible yet, as we're still working through some small issues. 

@Godmartinz PRs tagged with issues will automatically close when they get merged into master. Please try not to close them prematurely before they're merged. (I did ask for changes on that PR, so this issue is not technically resolved yet.)

**Comment by snipe** [comment]
@PandiarajanSelvaraj if you upgrade your Snipe-IT instance, you should see these changes now.

**Comment by PandiarajanSelvaraj** [comment]
Thank u @snipe and team. Now I am getting this option.
