### ISSUE TITLE
Cannot export User employee no. in asset report

### ISSUE THREAD

**Issue by mmg7aac** [grokability/snipe-it#12174]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I just upgrade from v5.4.3 to v6.0.13, and find following Custom Asset Report cannot generate the employee No. field. 

Tried to enable the debug mode, but no log shown in /storage/logs/laravel.log

Checked People settings, the employee No. could be shown

### Reproduction steps

1.Reports -> Custom Asset Report
2. Select 'Add a Bom to this CSV 
3.Generate
...

### Expected behavior

User employee No. information could be generated as it is in preview version V5.4.3

### Snipe-IT Version

6.0.13

### Operating System

Centos

### Web Server

Nginx

### PHP Version

7.4

### Operating System

Windows

### Browser

Chrome/Firefox

**Comment by mmg7aac** [comment]
1. upgrade the docker with snipe-it 6.0.13， linked with original external mysql hosted in docker
2. After launch the service, and try to generate the asset report in the UI, all column information is good, only employee no. is leavin blank
3. Fall back the docker image to 5.4.3, problem disappeared


1. Also ground up a new docker instance with freash new schema in MYSQl
2. Input demo user/asset/assignment record, and try to export from the report, the employee number is also missing in the output

**Comment by snipe** [comment]
This was already fixed in https://github.com/snipe/snipe-it/pull/12134
