### ISSUE TITLE
[Feature Request]:  Add OTP Based 2FA and Support for Firebase

### ISSUE THREAD

**Issue by SubhanRaj** [grokability/snipe-it#12186]
### Is your feature request related to a problem? Please describe.

The Existing 2FA includes using Google Authenticator, which is good but having an option for receiving an OTP by email or phone number would also be better for basic 2FA and then the user can also enable the Google Authenticator if they need that.
Also, it would be better if there were support for google's Firebase's BASS support.

### Describe the solution you'd like

For the 2FA over Email via OTP we can use [PHPMailer](https://github.com/PHPMailer/PHPMailer) or [Laravel's Inbuilt Mail Functionality ](https://laravel.com/docs/9.x/mail), and for mobile-based OTP there is a free tier in Google Firebase which can do the same as mentioned [here on firebase's documentation](https://firebase.google.com/docs/auth/web/phone-auth).

By using firebase, the app can be more portable and easy to set up and use for both individual users and organizations as the need for local setup servers will not be required anymore.

### Describe alternatives you've considered

Nothing.

**Comment by snipe** [comment]
Current 2FA supports Authy and other standard TOTP apps. SMS and email is less secure, so I'm disinclined to consider this option.

**Comment by SubhanRaj** [comment]
Well, SMS and email can be considered Less secure in comparison to Google Authenticator, but they are easy to use and also If someone doesn't want to have setup Google 2FA, it can be an option to use Email or SMS-based 2FA as an option which can be user configurable.

**Comment by snipe** [comment]
Right, but we already support easy to set up, more secure alternatives. Authy is free. Google auth is free. Lots of TOTP apps are free, and all are more secure than email or SMS.
