### ISSUE TITLE
Double horizontal scrollbars

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#12196]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When viewing a list of objects that requires a horizontal scrollbar to view all the columns, two scrollbars can sometimes be added, with the second scrollbar being seemingly superfluous (moves the entire table to the left). This is most evident with asset lists except for the main asset list view. The easiest way to reproduce this is to resize the browser window's width small enough that the scrollbar appears, but not small enough to change Snipe-It to mobile template.

This only affects some, but not all lists. Some of the lists which don't seem to be affected: the main asset list, People, Predefined Kits, Consumables. Other lists of assets, like viewing those assigned to a user, do seem to be affected.

This affects the current demo.

### Reproduction steps

1. In the current demo, select Accessories.
2. Resize the browser window's width small enough to cause a scrollbar to appear.
3. Observe that two scrollbars appear.
...

### Expected behavior

The lists should have consistent viewing controls, if possible.

### Screenshots

![image](https://user-images.githubusercontent.com/102685457/204912633-69c13b5c-8f87-4c27-a17b-f733e582b6ff.png)

### Snipe-IT Version

6.0.13

### Operating System

Whatever the demo uses

### Web Server

Whatever the demo uses

### PHP Version

Whatever the demo uses

### Browser

Google Chrome

### Version

108.0.5359.71

**Comment by brianhoganm** [comment]
LOL - I just discovered this as well.

**Comment by snipe** [comment]
IIRC, one is a page scrollbar, the other is the standard table scrollbar.
