### ISSUE TITLE
Regarding Using Snipe IT in Linux Machine

### ISSUE THREAD

**Issue by manish-q** [grokability/snipe-it#12200]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

earlier i was using the snipe it int local machine ( via localhost ) with Xamp Server and it was workig fine
now we want to deploy it on our server , and we created the server of Ubuntu,CentOS, and even in AWS also  but we are still not able to launch the snipe it . ALl steps had been perfomed ditoo and mentioend everywhere but everytime we are facing some kind of issue 

Please Help , This is Urgent  for us 
we had tried every command mentioned  in below link and everywhere and every command worked properly
https://www.hostnextra.com/kb/install-snipe-it-on-ubuntu-20-04/

![snipeit](https://user-images.githubusercontent.com/71642976/204987427-af168ad4-3762-4df8-8326-553d8eed259b.jpg)

<img width="651" alt="image" src="https://user-images.githubusercontent.com/71642976/204987364-1d70761a-0dcf-40e6-b404-5936737af379.png">

### Reproduction steps

1. in stagging mode 
2.
3.
...

### Expected behavior

Server 500 Error now 

### Snipe-IT Version

 git clone https://github.com/snipe/snipe-it snipe-it

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4

### Operating System

Windows

### Browser

Google Chrome

**Comment by snipe** [comment]
I'd need to see the app log to see what errors are being triggered with that 500.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
