### ISSUE TITLE
[Feature Request]: PHP8 in Docker images

### ISSUE THREAD

**Issue by misilot** [grokability/snipe-it#12202]
### Is your feature request related to a problem? Please describe.

End of Life of PHP7

### Describe the solution you'd like

The two Dockerfiles

https://github.com/snipe/snipe-it/blob/master/Dockerfile#L17-L26 and https://github.com/snipe/snipe-it/blob/master/Dockerfile.alpine#L5-L31 and https://github.com/snipe/snipe-it/blob/master/Dockerfile.fpm-alpine#L3 all use PHP 7.4. With the release notes that support for only PHP8 coming these should probably be updated.

Don't know if it would be worth upgrading the Dockerfile to be ubuntu22 as well, and the Alpine one to be a newer version of 3.14 or even 3.17 but it would require testing.

**Comment by snipe** [comment]
@uberbrady want to take a stab at this?

**Comment by snipe** [comment]
This will be handled in Snipe-IT v7 (coming very soon)
