### ISSUE TITLE
[Feature Request]: Include accessories in predefined kit

### ISSUE THREAD

**Issue by priggad** [grokability/snipe-it#12213]
### Is your feature request related to a problem? Please describe.

Our new starters are assigned multiple items, some of which we have defined as assets and others we have defined as accessories. Predefined kits currently only support including assets.

### Describe the solution you'd like

When creating a predefined kit it would be useful to be able to include accessories, not just assets.

**Comment by snipe** [comment]
We will add accessories back to kits when we can. Kits are fundamentally not working the way we want, so we had to pull that for now.
