### ISSUE TITLE
Browser update broke Label Spacings

### ISSUE THREAD

**Issue by xinput** [grokability/snipe-it#12211]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

with yesterdays update of Chrome & Edge our Labels seems to be a bit off while they were working great the past months.

There is a small spacing added between the values and the 2d Barcode as you can see in the picture below.
![Screenshot 2022-12-07 at 08 46 35](https://user-images.githubusercontent.com/11652924/206120105-d9e3590e-2e54-4215-868a-8bfa5b6f593d.png)

this causes also an additional Page which is added and the 2D Barcode get's very thin. I'm not sure if this is an issue which can be eliminated on the server site by adding custom CSS in snipe etc.

This issue was existing for a long time now in Firefox, but now it's also the same for Chrome and edge.

In Safari it does not work at all as it adds some weird margins which expands the label up to 7 pages. Did not find a way to disable them.

Any help would be appreciated.
Thanks.

### Reproduction steps

1. Update to newest Edge / Chrome version
2. Generate Label
3. 
...

### Expected behavior

Label should not have a spacing between printed values and 2D Barcode

### Snipe-IT Version

6.0.12

### Operating System

Rocky Linux 8

### Web Server

nginx

### PHP Version

8.0.23

### Operating System

MacOS / Windows

### Browser

Chrome, Edge, Safari, Firefox

**Comment by snipe** [comment]
@Godmartinz can you take a look? Thnx!
