### ISSUE TITLE
Username,employee No,Manager,Department,Title missing form custom report.

### ISSUE THREAD

**Issue by balakrishna9aws** [grokability/snipe-it#12227]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

while generating a custom report from snipeIT  v6.0.13 ( recently upgraded) , the username, employee no, manager and department columns show nothing.
![image](https://user-images.githubusercontent.com/107479917/206409631-1af2aa65-e8d4-46f4-a125-7c46f6822acd.png)

### Reproduction steps

1.  Generate a custom asset report and include the username, employee no, manager and department columns
2.
3.
...

### Expected behavior

username ,employee number is missing from custom report.

### Screenshots

generated report.
![image](https://user-images.githubusercontent.com/107479917/206409911-28b655b7-9050-40f1-966c-c4d520179e13.png)
![image](https://user-images.githubusercontent.com/107479917/206410073-a9abc183-661f-4527-9f15-c6d6ae7309f9.png)

### Snipe-IT Version

6.0.13

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.0

### Operating System

windows 10

**Comment by snipe** [comment]
This is fixed in the latest release.
