### ISSUE TITLE
6.0.14 Change in results when searching by Tag via api

### ISSUE THREAD

**Issue by cslob** [grokability/snipe-it#12236]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In previous version, when making an API call to https://develop.snipeitapp.com/api/v1/hardware/bytag/{asset_tag}, it would return just the result. Now in 6.0.14, I am getting an array of rows[number]data. This has been the behavior previously when just doing a general search.

### Reproduction steps

1. Make an API call bytag
2. Get an array

### Expected behavior

The fields for the asset should just be displayed, not it an array.

### Snipe-IT Version

6.0.14

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

**Comment by cslob** [comment]
After going back to version 6.0.12 I can confirm that if an API call is made https://develop.snipeitapp.com/api/v1/hardware/bytag/%asset_tag% that it only outputs the data and it isn't in an array.

<blockquote><div><strong><a href="https://develop.snipeitapp.com/api/v1/hardware/bytag/%asset_tag%">400 Bad Request</a></strong></div></blockquote>

**Comment by hennedo** [comment]
Can confirm, this breaks our hardware scanners too. As I don't see this in the changelog, I wonder if this is an intended change and I should update our scanner app to the new API format or if this is unintended, then I would revert back to 6.0.12 and wait for a fix.

**Comment by cslob** [comment]
@hennendo My guess is perhaps it had something to do with [this](https://github.com/snipe/snipe-it/pull/12118) change in 6.0.14, but it's only a guess.

**Comment by snipe** [comment]
@cslob - I don't think that change would have caused this. If you don't pass those particular fields that we added as parameters, it won't use them in the query.

**Comment by snipe** [comment]
I think I see the problem here. In the old version we're using `transformAsset()` and in the latest we're using `transformAssets()` (plural).

We can't use `transformAsset()` there with the deleted flag, since there could be more than one deleted asset with the same asset tag, so we have to return a collection, not a single asset.

I think I have a way to handle both scenarios. Give me a moment.

**Comment by snipe** [comment]
PR is up, just waiting review: https://github.com/snipe/snipe-it/pull/12327

**Comment by snipe** [comment]
Merged to master
