### ISSUE TITLE
Serial Number not importing from CSV

### ISSUE THREAD

**Issue by shinduke** [grokability/snipe-it#12249]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, i´m tring ro imoprt our assets.
Everything works fine but not the Serialnumbers.
I tried for the column name Serials, serials, serial numbers
Running on Windows server 2019
Version v6.0.11 build 8758 (g61fa0bda4)

This is my import line

Item Name,Company,Location,Category,Username,Model Name,Manufacturer,Serial Number,Status,Image,Checkout Type

I saw some people having the same issue but th fix doesn´t work for me

### Reproduction steps

1. Upload CSV
2. Import
3. 
...

### Expected behavior

Importing ans updating or setting Serial number entries

### Screenshots

![image](https://user-images.githubusercontent.com/36949743/207612079-04192c9b-9f82-437d-bc64-458f64d7a13b.png)

### Snipe-IT Version

v6.0.11 build 8758 (g61fa0bda4)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.2

**Comment by shinduke** [comment]
Maybe i have a false understanding for the entry "Serial". I changed the entry of our Service Tags of the Machienes to Model Number and the entry was set imidiatly.
Can it be that Serial is only used by licences?
But Ok, for me the issue is solved.

**Comment by viclou** [comment]
You need to use exactly, Serial Number, as your header

**Comment by kenchan0130** [comment]
If we set the CSV header name to "Serial Number", it imports as expected.
However, if we map CSV columns with other header names to "Serial Number", it does not work as expected.

I have created [PR](https://github.com/snipe/snipe-it/pull/12617) to correct this issue.
