### ISSUE TITLE
default .env file not in use after restoring from Server A to Server B

### ISSUE THREAD

**Issue by davecowley** [grokability/snipe-it#12244]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi

I have just tried to modify my .env file for some changes, restarted apache and cleared the cache as per the common faults and nothing has changed.

I have added the smtp settings and then gone in to general settings to run a test.  when i run the test it fails and indicates that the username is incorrect. I have checked the logs and is showing the error as below.

The site was initially running an install inventory2.domain.com as I took a backup from inventory1.domain.com and restored it on the backup page (great feature) and it appeared to just work.

the site loads fine and everything seems to be working fine.  its just the email issue.

any ideas?  when i look in /var/www/snipe using ls -a there are a few .env files but none match.

### Reproduction steps

1.
2.
3.
...
.

### Expected behavior

emails to work once the smtp settings have been applied

### Screenshots

![mstsc_gTbL4Iw9Fo](https://user-images.githubusercontent.com/89160018/207270459-5db1adeb-8553-45d3-9671-fee621a1d3af.png)

### Snipe-IT Version

6.0.12

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.2-1

### Error messages

```shell
[2022-10-20 09:36:43] production.ERROR: Your APP_URL in your .env is misconfigured - it is: inventory2.domain.com. Many things will work strangely unless you fix it.
[2022-10-20 09:36:44] production.ERROR: Your APP_URL in your .env is misconfigured - it is: inventory2.domain.com. Many things will work strangely unless you fix it.
[2022-10-20 09:38:10] production.ERROR: Your APP_URL in your .env is misconfigured - it is: inventory2.domain.com. Many things will work strangely unless you fix it.
[2022-10-20 09:41:13] production.ERROR: Your APP_URL in your .env is misconfigured - it is: inventory2.domain.com. Many things will work strangely unless you fix it.
[2022-10-20 09:41:13] production.ERROR: Your APP_URL in your .env is misconfigured - it is: inventory2.domain.com. Many things will work strangely unless you fix it.
[2022-10-20 09:41:13] production.ERROR: Your APP_URL in your .env is misconfigured - it is: inventory2.domain.com. Many things will work strangely unless you fix it.
[2022-10-20 09:41:18] production.ERROR: Your APP_URL in your .env is misconfigured - it is: inventory2.domain.com. Many things will work strangely unless you fix it.
[2022-10-20 09:41:19] production.ERROR: Swift_TransportException: Failed to authenticate on SMTP server with username "YOURUSERNAME" using 2 possible authenticators. Authenticator LOGIN returned Expected respon>
". Authenticator PLAIN returned Expected response code 235 but got code "530", with message "530 Must issue a STARTTLS command first
". in /var/www/snipe-it/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:191
```

### Additional context

was a fresh install to restore backup.

**Comment by snipe** [comment]
You do seem to have a `.env` file in that screenshot. The logs are telling you what's wrong. Your APP_URL is misconfigured. Per the docs, you need to include `http://` or `https://` in your APP_URL value.

**Comment by davecowley** [comment]
it already has the https in it. My .env file does not seem to be controlling the site.  I have checked all the .env files and none seem to match.  it is bizarre.

Plus email still doesnt work even though its configured below.  when the test email button is pressed it errors and states unable to send email as blablah.domain.com

as a test I changed the email address and then cleared cache and it did not reflect the change.  This makes me think its referencing a different .env file?

`# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:a/vEcMk8otbxS6nxxxxxMz/N2opzbUKsB1JU=
APP_URL=https://inventory.domain.com
APP_TIMEZONE='Europe/London'
APP_LOCALE=en
MAX_RESULTS=500

# --------------------------------------------
# REQUIRED: UPLOADED FILE STORAGE SETTINGS
# --------------------------------------------
PRIVATE_FILESYSTEM_DISK=local
PUBLIC_FILESYSTEM_DISK=local_public

#PRIVATE_FILESYSTEM_DISK=s3_private
#PUBLIC_FILESYSTEM_DISK=s3_public


# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=snipe_it
DB_USERNAME=xxxdmin
DB_PASSWORD=xxxxxxx
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_IS_PAAS=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=email-smtp.eu-west-2.amazonaws.com
MAIL_PORT=587
MAIL_USERNAME=AKIAxxxxxxx7QIPUZ2
MAIL_PASSWORD=BKcabMQLz1VR/dxxxxxxxxxx9385FTs3FCKvMeZrUp0Nw
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=inventory.domain.com`

**Comment by davecowley** [comment]
fixed it

MAIL_FROM_ADDR=inventory.domain.com

needed an @ not a . in the mail from address
