### ISSUE TITLE
Quotes in Custom Field regex are being HTML-escaped

### ISSUE THREAD

**Issue by koelle25** [grokability/snipe-it#12252]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When using quotation marks in the regular expression of a custom field they are being HTML-escaped before being stored in the database.

Use case: I wanted to create a custom field for the display size of my assets (e.g. `15.6"` for a notebook).

### Reproduction steps

1. Create a new _Custom Field_
2. Set the **Format** to `CUSTOM REGEX`
3. use e.g. `regex:/"text'/`
4. Save and see in the list the saved value of `regex:/&quot;text&#039;/`
5. Can also be seen in the database: `SELECT format FROM custom_fields WHERE name = "Quotes in Regex";`
6. Create new _Fieldset_ containing this Custom Field
7. Create new _Asset Model_ using this Fieldset
8. Try to create an _Asset_ based on this Model with the Custom Field value `"text'`
  => ERROR "_The [...] format is invalid._"
9. Use literal value `&quot;text&#039;` instead
  => SUCCESS

### Expected behavior

Any character can be used literally in a regular expression.

### Screenshots

![Custom Field creation](https://user-images.githubusercontent.com/915514/207859117-25ab1425-d929-406c-b16c-2f178999ad79.png)
![Custom Field list](https://user-images.githubusercontent.com/915514/207859122-61a3a1c2-046e-4bd3-91c9-7a7b77f39f3d.png)
![Error when creating/modifying asset with this custom field](https://user-images.githubusercontent.com/915514/207859721-f994b260-731b-4151-abc7-2cfa096dd8a5.png)

### Snipe-IT Version

6.0.14

### Operating System

CentOS

### Web Server

Apache

### PHP Version

7.4

### Additional context

Fresh install on Docker (using `snipe/snipe-it:v6.0.14`).

**Comment by snipe** [comment]
If we do not escape them, we leave ourselves open to XSS attacks, so I'm not exactly sure what the solve is here? Un-escape them on the way back in maybe. @inietov can you take a look?
