### ISSUE TITLE
[Feature Request]: Add mm units for labels

### ISSUE THREAD

**Issue by iangozer** [grokability/snipe-it#12258]
### Is your feature request related to a problem? Please describe.

Is there a reason for not adding millimeter option to the label settings?
My only guess was that if measurements were used in lots of places, it would be a big job, but I didn't see anywhere else.

### Describe the solution you'd like

Select box for Inches / Millimeters in either label setting page or Localization.
Small first step in making labels easier to use.

**Comment by snipe** [comment]
We already have a PR that would address this - we're reviewing it now

**Comment by budinero** [comment]
Hello! This is a closed issue, but I can't find any option to select  Inches / Millimeters in configuration. Where can I find it?
