### ISSUE TITLE
List all Assets comes up empty

### ISSUE THREAD

**Issue by jarrodCoombes** [grokability/snipe-it#12257]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I try to list all assets, or use any screen that creates a list of assets, the list is empty, stating "No matching records found" 

Looking at the the dev tools in the browser I am seeing:

```
Request URL: https://assets.domain.tld/api/v1/hardware?status=&order_number=&company_id=&status_id=&search=&sort=name&order=asc&offset=0&limit=20
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 10.x.x.x:443
Referrer Policy: same-origin
```

And in the laravel.log file I am seeing:

```
[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368)
```

This was working one day, and not the next, with no major changes on the server side of thing, and two assets were manually added between this working and not. Bringing up individual assets works fine, and most other functions seem to be unaffected.

EDIT: More detailed line from `laraval.log`

```
[2022-12-16 09:45:15] production.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select count(*) as aggregate from `assets` where `` = ? and `assets`.`deleted_at` is null) {"userId":5,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select count(*) as aggregate from `assets` where `` = ? and `assets`.`deleted_at` is null) at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
```

### Reproduction steps

1. Click "Assets" and then select "List all"

### Expected behavior

It should list all the assets.

### Screenshots

![image](https://user-images.githubusercontent.com/58901318/208155373-bf028e34-8ed8-4c26-8136-c2fdf821c50e.png)

### Snipe-IT Version

6.0.14

### Operating System

Ubuntu 20.04.5 Completely up to date

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

MacOS

### Browser

Chrome 

### Version

108

**Comment by snipe** [comment]
If I had to guess, somewhere in your `action_logs`, table you have a  `target_type` that is blank on a checkout. Can you review that?

**Comment by snipe** [comment]
(Or check your custom fields page, expose the "DB Column" column from the UI and see if there are any warnings there)

**Comment by jarrodCoombes** [comment]
Aha, adding the column definitely helped. I see this:

```
_snipeit_caltronics_tag_11
 WARNING. This field is in the custom fields table as but should be _snipeit_caltronics_tag_11.
```

No idea why this suddenly happened. What's the best way to fix this?

**Comment by snipe** [comment]
@jarrodCoombes Sounds like you have access to the database directly? I can give you a SQL command to run that should fix it, or you can try (after a backup!) running `php artisan snipeit:regenerate-fieldnames`

**Comment by snipe** [comment]
Huh, that is weird. Now that I'm looking at it, I'm not sure why you'd see an error there, since they *appear* to be the same - the one it's expecting and the one we see.... This is usually a weird mismatch in Unicode libraries.

```
 @if ($field->convertUnicodeDbSlug()!=$field->db_column)
     <br><i class="fas fa-exclamation-triangle text-danger"></i>
     {!! trans('admin/custom_fields/general.db_convert_warning',['db_column' => $field->db_column, 'expected' => $field->convertUnicodeDbSlug()]) !!}
@endif
```

That blade code is invoking:

```php
/**
     * Convert non-UTF-8 or weirdly encoded text into something that
     * won't break the database.
     *
     * @author [A. Gianotto] [<snipe@snipe.net>]
     * @since [v3.4]
     * @return string
     */
    public function convertUnicodeDbSlug($original = null)
    {
        $name = $original ? $original : $this->name;
        $id = $this->id ? $this->id : 'xx';

        if (! function_exists('transliterator_transliterate')) {
            $long_slug = '_snipeit_'.str_slug(mb_convert_encoding(trim($name),"UTF-8"), '_');
        } else {
            $long_slug = '_snipeit_'.Utf8Slugger::slugify($name, '_');
        }

        return substr($long_slug, 0, 50).'_'.$id;
    }
```

So this would typically happen when what it's expecting from a UTF/Unicode translation isn't matching. But your two values look the same... Can you confirm in the `custom_fields.db_column` field, your custom field db column name is *exactly* the same (no trailing spaces, etc) as the one you created on the assets table?

**Comment by jarrodCoombes** [comment]
Well it looks like it's in the custom fields table as blank (ie " ") but should be `_snipeit_caltronics_tag_11` so I am thinking it's a unicode issue.

So it sounds like the fix would be simple change the column title in the fields table (though I have no idea how to do that from the SQL side of things). I will try the artisan command you recommended this morning and report back.

This might make it a little more clear:
```
_snipeit_caltronics_tag_11
 WARNING. This field is in the custom fields table as <blankSpace> but should be _snipeit_caltronics_tag_11.
```

**Comment by jarrodCoombes** [comment]
I ran `php artisan snipeit:regenerate-fieldnames` and got this (I added the <blankSpace> tag to make it more obvious there was a space there):


```
Caltronics Tag (11) column should be _snipeit_caltronics_tag_11
-- ✘ Field mismatch: Caltronics Tag value should be _snipeit_caltronics_tag_11 but is <blankSpace> in the custom_fields table
-- ✘ WARNING: There is no field on the assets table ending in  11. This may require more in-depth investigation and may mean the schema was altered manually.
```

What is concerning to me is that this issue just randomly popped up, no major changes were made on our end, as near as I can tell it was triggered by manually adding two, unrelated to this custom field, assets. Makes me wonder if there is any other data that has gone missing in the databases.

**Comment by snipe** [comment]
I can tell you that it wouldn't be on our end. We're super cautious about data destruction, and our commits are all public. We use soft-deletes, and the only time we'd drop a column is if you specifically delete it - and you can't even do that if it's associated to a fieldset. I'm curious about what happened here, but since it's on your box, I don't have a lot to work with. Maybe check your server access logs to see what requests were made recently? I'm definitely not ruling out a bug, but the only place we drop those columns is in the `boot()` method in the `CustomField.php` model file:

```php
return Schema::table(self::$table_name, function ($table) use ($custom_field) {
     $table->dropColumn($custom_field->db_column);
});
```

here:

https://github.com/snipe/snipe-it/blob/cc40ecaa44926e4f2368e9fe129ca62218f77daf/app/Models/CustomField.php#L112-L167

This is, of course, always harder when I can't see the data.

My guess is maybe you don't have *any* transliteration libraries installed? Is it possible that there was an automatic server package upgrade that happened?

**Comment by snipe** [comment]
If you have mysql access via command line, you can run `UPDATE custom_fields SET db_column = '_snipeit_caltronics_tag_11' WHERE id='11';` to correct the value of `db_column`.

**Comment by jarrodCoombes** [comment]
> I can tell you that it wouldn't be on our end.

Right, yes, I didn't mean this was a mistake or anything on your end, more a general concern about not knowing what happened to cause it.

>My guess is maybe you don't have any transliteration libraries installed? 

Not that I am aware of. This is a *very* vanilla install of Ubuntu Server with no customizations and the only application on it is Snipe, and I am the only admin who has access to it to install anything.

>Is it possible that there was an automatic server package upgrade that happened?

Only thing that gets installed automatically are the OS security updates, all other updates are manual. Not sure I did any recently either, but I don't know. 

>I'm curious about what happened here, but since it's on your box, I don't have a lot to work with.

Understandable, but I am also very happy to post and logs you need, though I may need some direction on how to get what you need.

**Comment by jarrodCoombes** [comment]
> UPDATE custom_fields SET db_column = '_snipeit_caltronics_tag_11' WHERE id='11';

Took me a minute to remember how to get into the DB and what not.

```
MariaDB [snipeit_data]> UPDATE custom_fields SET db_column = '_snipeit_caltronics_tag_11' WHERE id='11';

Query OK, 0 rows affected (0.001 sec)
Rows matched: 1  Changed: 0  Warnings: 0
```

What strikes me as kinda odd here is that specifically states that nothing was changed, yet the issue was clearly fixed after the command was run.


I did look into the access logs, but there was nothing of note there, but that may also come from the fact that I am not sure exactly when this issue cropped up. As much as I hate to do it, but for now I am going to consider this a fluke and move on. If it happens again, I can definitely do some more forensic digging to work it out.

**Comment by snipe** [comment]
Knowing you're the only admin with access to the box certainly helps. What's more odd is that the `convertUnicodeDbSlug()` method, in your case, shouldn't really have to do a lot of heavy lifting. That method exists for non-ASCII languages mostly (Cyrillic, etc) where the field name itself might not be compatible with some versions of SQL, so we UTF-8 it, so it doesn't break your database.

You can see those conversion tests here, for context:

https://github.com/snipe/snipe-it/blob/master/tests/Unit/CustomFieldTest.php

But it certainly looks like your field name is in English, so in the `convertUnicodeDbSlug()`, it should just return the name, slugified.


<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe-it/CustomFieldTest.php at master · snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe-it/CustomFieldTest.php at master · snipe/snipe-it</div></blockquote>

**Comment by snipe** [comment]
> As much as I hate to do it, but for now I am going to consider this a fluke and move on. If it happens again, I can definitely do some more forensic digging to work it out.

Computers, man... Terrible idea.

I sort of agree here. I don't see any smoking guns, and while I'm loathe to just shrug and walk away, I don't think there's a ton  we can collectively do to sort it out. Def reach out here or on MacAdmins (I'm @snipe there, as you know) if you run into this issue again. It's an odd one, and I'm trying not to obsess (as I am want to do.)
