### ISSUE TITLE
Large Brazilian Portuguese translation block on crowdin for approval

### ISSUE THREAD

**Issue by decioesilva** [grokability/snipe-it#12262]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Please check a large block of Brazilian Portuguese translation suggestions on crowdin, I saw that there are several translations awaiting approval, I revised over 1000 entries and phrases There are many translation errors that have been corrected. I make myself available to be one of the curators of the Portuguese translation. I left a message on crowdin. Thanks.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Translation reflecting Brazilian Portuguese correctly

### Snipe-IT Version

6.0.14

### Operating System

All

### Web Server

All

### PHP Version

All

**Comment by snipe** [comment]
I've promoted you to proofreader for pt-BR. Thanks for your time on this. <3

**Comment by decioesilva** [comment]
Great, I'll do my best \o/
