### ISSUE TITLE
PHP commands shown after upgrade from Ubuntu 20.04 to 22.04

### ISSUE THREAD

**Issue by sstrasserJember** [grokability/snipe-it#12270]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After we upgraded our Ubuntu 20.04 server to 22.04 yesterday, I get this output when I try to access the web page:

`<?php

use Illuminate\Contracts\Http\Kernel;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Check If The Application Is Under Maintenance
|--------------------------------------------------------------------------
|
| If the application is in maintenance / demo mode via the "down" command
| we will load this file so that any pre-rendered content can be shown
| instead of starting the framework, which could cause an exception.
|
*/

if (file_exists(__DIR__.'/../storage/framework/maintenance.php')) {
    require __DIR__.'/../storage/framework/maintenance.php';
}

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| this application. We just need to utilize it! We'll simply require it
| into the script here so we don't need to manually load our classes.
|
*/

require __DIR__.'/../vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request using
| the application's HTTP kernel. Then, we will send the response back
| to this client's browser, allowing them to enjoy our application.
|
*/

$app = require_once __DIR__.'/../bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$response = tap($kernel->handle(
    $request = Request::capture()
))->send();

$kernel->terminate($request, $response);`

### Reproduction steps

1. Install Snipe 6 to Ubuntu 20.04 (PHP 8.1.2)
2. Upgrade to Ubuntu 22.04

### Expected behavior

Seeing the login page of Snipe

### Snipe-IT Version

6.14

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.2

### Operating System

Win 10

### Browser

Opera, Firefox, Edge

### Error messages

```shell
/
```

### Additional context

Nothing else. No error. The Apache log shows nothing.
We haven't changed the .env in any way before the upgrade.

I already tried "php upgrade.php" and ran the composer troubleshooting commands from the Common Issues page. Even after that and restarting the Apache service, no change in behaviour.

When trying to run the given commands in an interactive PHP shell, I get the error
`php > $kernel = $app->make(Kernel::class);
PHP Warning:  Uncaught ReflectionException: Class "Kernel" does not exist in /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:877
Stack trace:
#0 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(877): ReflectionClass->__construct()
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build()
#2 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Container\Container->resolve()
#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve()
#4 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Container\Container->make()
#5 php shell code(1): Illuminate\Foundation\Application->make()
#6 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [Kernel] does not exist. in /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:879
Stack trace:
#0 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build()
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Container\Container->resolve()
#2 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve()
#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Container\Container->make()
#4 php shell code(1): Illuminate\Foundation\Application->make()
#5 {main}
  thrown in /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 879`

**Comment by sstrasserJember** [comment]
Push.
Sadly, this is still relevant :(

**Comment by snipe** [comment]
This is a server config issue, not an app issue. 

https://snipe-it.readme.io/docs/installation-issues#loading-the-snipe-it-app-shows-php-code-in-the-browser

This always means that PHP is either not installed, or is not enabled in your Apache/Nginx/IIS/etc web server.

PHP has two different parts - php-cli and the module itself, which means it's possible to have PHP work via command line and still not have it enabled as the web server module.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#loading-the-snipe-it-app-shows-php-code-in-the-browser">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by sstrasserJember** [comment]
Damnit! It would have been so easy! 
Thanks, PHP was installed but the upgrade deactivated the module in Apache.

For documentation purposes, this command fixed it:
`sudo a2enmod php8.1 &&
sudo systemctl restart apache2`
