### ISSUE TITLE
[Feature Request]: Custom Views in Certain Areas

### ISSUE THREAD

**Issue by bslatyer** [grokability/snipe-it#12287]
### Is your feature request related to a problem? Please describe.

We're looking at implementing license management in Snipe-IT. However, it's a bit difficult at the moment as we want to be able to see what each company has in their possession.

Currently, we're having to enable the "Company" column each time a user wants it. This isn't ideal as we would like the ability to save Custom Views for certain areas and not fear losing our columns.

### Describe the solution you'd like

We would like to see the ability to save Custom Views when looking at specific areas such as licenses or assets without having to set it up each time

**Comment by ccj9874** [comment]
I support this request. It would be great to set the default column views for the All Assets page for all of my users or for specific User Groups. There are many columns that my company does not use, so if our page were to be accessed by more than just our IT department it would be difficult to deploy

**Comment by snipe** [comment]
As mentioned, the views are stored via browser cookie in each section already.

**Comment by bslatyer** [comment]
Hey @snipe,

I understand that - however if the user has cleared their cookies, used a new device or never saves their cookies - they wouldn't be able to use the same views as before.

Cookies aren't the best way to store things nowadays unless it's for tracking or analytics.

Can this feature be implemented for say per-user logins or an org-wide view?

**Comment by ccj9874** [comment]
I agree, its great that the cookies store it and they have worked fantastic for me in the past. But if there are 50+ new users that we want to begin accessing the website, it may be difficult to get everyone set up with the correct column views without additional help, especially if they are not very tech-literate. If there were a default view that you could configure, these 50+ new users would not have to configure their views when they first sign in. I think this feature is less for admins or regular users of Snipe but more for other end users.

**Comment by devvonmonahan** [comment]
Support here also.
I'd love for a default view you could set on first logon for each user and from there it can be changed as per each users requirements if they need it.
Storing this against the account if easy/possible to implement would be ideal at least in my use-case.

**Comment by bslatyer** [comment]
Hey @snipe,

Any chance of an update on this happening?

Thanks,

Braeden

**Comment by snipe** [comment]
@bslatyer it's not currently on the short-term roadmap at this time.

**Comment by bslatyer** [comment]
Hey @snipe,

No worries - thanks for that update!
