### ISSUE TITLE
Unable to sync ldap users after upgrade to v6.0.14 build 9038 (g163b3f6c0) 

### ISSUE THREAD

**Issue by bklier-mpl** [grokability/snipe-it#12288]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgrading our installation to v6.0.14 build 9038 (g163b3f6c0) using `php upgrade.php` we're not able to sync our ldap users any more.

### Reproduction steps

1. run "php upgrade.php" as snipeit user to upgrade the system to  v6.0.14 build 9038 (g163b3f6c0)
2. try to sync ldap users using the web interface or cli

### Expected behavior

Users getting synced to LDAP

### Screenshots

Error when trying ldap sync from web interface:
![image](https://user-images.githubusercontent.com/46226866/210047607-0c4ac4e5-7235-4916-b086-01d5a349b839.png)

Error when trying ldap sync from cli:
```
php artisan snipeit:ldap-sync

   ErrorException 

  Trying to get property 'permissions' of non-object

  at app/Console/Commands/LdapSync.php:227
    223▕ 
    224▕                 if($ldap_default_group != null) {
    225▕ 
    226▕                     $default = Group::select()->where('id', $ldap_default_group)->first();
  ➜ 227▕                     $user->permissions = $default->permissions;
    228▕ 
    229▕                 }
    230▕ 
    231▕                 if($item['manager'] != null) {

  1   app/Console/Commands/LdapSync.php:227
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()

      +13 vendor frames 
  15  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
```

### Snipe-IT Version

v6.0.14 build 9038 (g163b3f6c0) 

### Operating System

Debian 11.6

### Web Server

nginx/1.22.1

### PHP Version

7.4.33 

### Error messages

```shell
From storage/logs/laravel.log

[2022-12-30 08:56:34] production.ERROR: Trying to get property 'permissions' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'permissions' of non-object at /usr/share/nginx/snipe-it/app/Console/Commands/LdapSync.php:227)
[stacktrace]
#0 /usr/share/nginx/snipe-it/app/Console/Commands/LdapSync.php(227): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /usr/share/nginx/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\LdapSync->handle()
#2 /usr/share/nginx/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /usr/share/nginx/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /usr/share/nginx/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /usr/share/nginx/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#6 /usr/share/nginx/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#7 /usr/share/nginx/snipe-it/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#8 /usr/share/nginx/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#9 /usr/share/nginx/snipe-it/vendor/symfony/console/Application.php(1024): Illuminate\\Console\\Command->run()
#10 /usr/share/nginx/snipe-it/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#11 /usr/share/nginx/snipe-it/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#12 /usr/share/nginx/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#13 /usr/share/nginx/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#14 /usr/share/nginx/snipe-it/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#15 {main}
"} 

php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by AnatoleF** [comment]
Just ran into this problem as well and after some digging, looks like in the latest commit to LdapSync.php they added the ability to have a default group. But if you do not have a default group it will error. I went to Admin > LDAP  and set a value for  "Default Permissions Group" and saved it.
![image](https://user-images.githubusercontent.com/86417997/210413332-66558122-dac2-4fda-bbea-7d61934a3cf5.png)

Note that once you save the field becomes empty, at least it did for me, I assume this is a bug. But I went back and tried the LDAP Sync again and it worked.

Looks like they need to add a catch for this when no default is selected or let the user know a default is required if this is by design.

Hope this helps.

**Comment by snipe** [comment]
@uberbrady can you handle this on Monday please?

**Comment by uberbrady** [comment]
This looks like maybe a default permissions group was set for LDAP users, then maybe that group was deleted? Could something like that have happened?

If so, then setting it back to blank and saving your settings would work around the issue. Or potentially changing the default permission group to another one which does exist might also do it?

**Comment by uberbrady** [comment]
OK, I was able to replicate this by deliberately setting a weird ldap default group in the database directly.
