### ISSUE TITLE
500 out of blue, with no changes made to system

### ISSUE THREAD

**Issue by AlexTryHarder** [grokability/snipe-it#12295]
### Debug mode

- [X] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

ErrorException
`fwrite(): Write of 2105 bytes failed with errno=22 Invalid argument`

When running: 
```
composer dump-autoload; php artisan cache:clear; php artisan config:clear; php artisan route:clear; php artisan debugbar:clear; php artisan event:clear; php artisan view:clear; php artisan optimize:clear; php artisan clear-compiled


   ErrorException

  fwrite(): Write of 2288 bytes failed with errno=22 Invalid argument

  at C:\inetpub\wwwroot\snipeIT\snipe-it\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:178
    174▕      * @phpstan-param FormattedRecord $record
    175▕      */
    176▕     protected function streamWrite($stream, array $record): void
    177▕     {
  ➜ 178▕         fwrite($stream, (string) $record['formatted']);
    179▕     }
    180▕
    181▕     private function customErrorHandler(int $code, string $msg): bool
    182▕     {

  1   C:\inetpub\wwwroot\snipeIT\snipe-it\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:178
      fwrite()

  2   C:\inetpub\wwwroot\snipeIT\snipe-it\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:162
      Monolog\Handler\StreamHandler::streamWrite()
```

### Reproduction steps

1.Hard to tell, it just stoped working without any changes made to this os
2.
3.
...

### Expected behavior

No error

### Screenshots

![image](https://user-images.githubusercontent.com/14946862/210380810-a2321c17-87a5-4ab0-aae9-232eb6f585fe.png)

### Snipe-IT Version

v6.0.14

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.0.26

**Comment by snipe** [comment]
My guess here would be a permissions issue. What are the permissions of your storage directory and storage/logs and storage/logs/laravel.log? We haven't changed anything with the logging recently. Did you try running `composer --install --no-dev`

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
