### ISSUE TITLE
Official Docker Preflight infinite loop Create User

### ISSUE THREAD

**Issue by nelsonov** [grokability/snipe-it#12294]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After a first time install and startup per directions for the official Docker image, I get an infinite loop at the Create Admin User stage.  Every time I submit, I get bounced back to the same Create Admin User page.  All the form items are filled out with the previous values except for the password fields.  I have tried every type of password imaginable and never see any errors related to passwords.

### Reproduction steps

1.  Create my_env_file per instructions for SSL Disabled
2.  Start docker mysql image per instructions
3.  Start docker snipe-it image per instructions
4.  Get app key
5.  Edit my_env_file to contain app key
6.  Stop snipeit container
7.   rm snipeit container
8.   Start snipeit container
9.   Go to http://mysecreturl.com:8001
10.  Pass all configuration tests
11.  Create Database Tables
12.  Create Admin User
...

### Expected behavior

Move on to Finished for setup

### Snipe-IT Version

Docker image latest (2022-12-21T01:31:47.397790656Z)

### Operating System

Debian 11

### Web Server

docker image

### PHP Version

docker image

### Operating System

Windows 11

### Browser

Chrome

### Version

108.0.5359.125 (Official Build) (64-bit)

### Error messages

```shell
Debugging is turned on.  No error messages in browser
```

**Comment by nelsonov** [comment]
I have also completely removed the images, containers, volumes, etc for both the mysql and snipe-it and started with a fresh install following the instructions and ended up with the same result.

**Comment by nelsonov** [comment]
This turns out to be a PEBKAC error. On my monitor I could not see the red box around the currency form and since the USD happens to be the right choice for me and it was already in the form, I didn't figure out that I actually needed to put something in there.

Just by chance I tried it at work and my work monitor I saw the red box.

Sorry to have opened the issue.

**Comment by snipe** [comment]
No problem! Thanks for the follow up :)
