### ISSUE TITLE
Error 500 when setting up via Docker

### ISSUE THREAD

**Issue by huntson** [grokability/snipe-it#12299]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After installing a Snipe-IT docker and a mariaDB docker, I am getting 500 server error after hitting the Next: Create Database Tables

### Reproduction steps

1.I followed the steps here: [https://mariushosting.com/how-to-install-snipe-it-on-your-synology-nas/](https://mariushosting.com/how-to-install-snipe-it-on-your-synology-nas/)
2.I clicked Next: Create Database
3.The 504 error mentioned in the mariushosting page shows up.  Refreshing generates a 500 error.  I am stuck at http://192.168.1.11:1339/setup/migrate?

### Expected behavior

The next step should show up

### Screenshots

Let me know what I can do to gather more info or get to the next step please.

### Snipe-IT Version

No clue but I pulled the latest

### Operating System

Linux

### Web Server

Nginx

### PHP Version

No clue but I pulled the latest

**Comment by snipe** [comment]
I'd need logs to be able to help here. https://snipe-it.readme.io/docs/getting-help 

"No clue but I pulled the latest" isn't even helpful, really. From where did you pull? Github? Dockerhub? Which branch? When did you pull? Help us to help you.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by huntson** [comment]
Yeah that was lazy of me.  My apologies.  I pulled the latest from Docker however I do not know how to check.  If there is a command i can run, I'll let you know the result.

That being said, as soon as I restarted after enabling the debug I was able to pass the config check and move on to create the admin user.  

I have included the logging here for reference.  I didn't notice anything before I enabled debugging and then of course, when I did, it all worked.

Logs:

[http://gofile.me/6rZyd/bjUHXQcxC](http://gofile.me/6rZyd/bjUHXQcxC)

<blockquote><img src="data:image/x-icon;base64,AAABAAIAEBAAAAAAAABoBQAAJgAAACAgAAAAAAAAqAgAAI4FAAAoAAAAEAAAACAAAAABAAgAAAAAAEABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wCdmJcAzszLALaysQDn5eUA2tnYAMK/vgCppaQA9PPzAO3s7ADU0tEAyMbFALy5uADh4N8AsK2sAPv6+gCtqagA9/f3ANfV1QDGwsEA3t3cALm2tQDRz84Av7y7AMvIyADv7u4A6+rqAKunpgDp5+cA5ePjALSwrwD8/PwAt7SzAN3b2gDGxMMAqKOjALKurQDg3t4A09DPAMTBwADQzcwAzMrJAM7KygDKxsUA/v7+APb29gDu7e0ArqqpAOzr6wDm5OQAure2ALu4twDAvbwAwb69AMnHxgDf3t0A29nZAMbDwgDT0dAA0s/PAMrIxwDQzs0Az83NAOzr6gCxrawA6OfnANrY2ADDv74A19bVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEAAQEBAQEBAQEBAQEBAQEBAAEBAQEBAQEBAQEBAQEBAQABAQEgPEIBAQEBAQEBAQEAAS0BAT5BLgEBAQEBAS0BACIfMwoBMDgvKgEDDiMEHQAUGhcNGyQ9MjMBGAg9MToAEEA2Nhk/B0U1AQcCBQErACccKBolLjchDxMfNjQ+LABEEh4DBgEvCyY7Qy05DBIAKRYRFQEBAQEBAQEBAQEBAC1CCQEBAQEBAQEBAQEBAQABAQEBAQEBAQEBAQEBAQEAAQEBAQEBAQEBAQEBAQEBAAEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAAD//wAAKAAAACAAAABAAAAAAQAIAAAAAACABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AmJOSAMzJyQCyrq4A5eTkAKWhnwDY19YAwLy7APLy8gDs6+sAq6inALm1tADFw8IA397dANLQ0AD5+fkAn5uZAKmkowD29vUA6ejnANza2gCvq6oAtbKxALy5uADJxsUA1tPSANDMywD8/PwAm5aVAKKenADi4eEAwsC/APDv7wCdmJcA7u3tAPj39wD09PQAp6KhAOfm5QCqpqUArampANrZ2AC4s7IAure2AL66ugDQzs0AxcHAAPv6+gDx8fAAoJybAKOfngDq6ekA4eDfALGtrADe3NwAs7CvAM7NzAD08/IA1tTUAM7LywDHw8MA/v7+AP39/QCalZQA7ezsAOvq6gCwrKsAtLGwALazsgC3tLMA2djXANfW1QC/u7kAwb28ANPR0QDRz88AxMLBAM3KygDIxcQA+/v7APr6+QD4+PgAoJuaAPX19QChnZsAo56dAKSgngDy8PAApqGgAKejogCppaQA6OfnAKunpgDm5eQArqqpAOXj4wDj4uEAsa6tAOLg4ACzr64A393cANvZ2QC8uLcAvbq5ANXT0wDDwMAAxsTDAMvJyADJx8YA9/f3APb29gD29fUAoZybAKGdnAD08/MAop2cAPPz8gCinp0A8/LyAKOfnQCkn54A8fDwAKSgnwCloaAApqKhAOvr6gCopKMAqaWjAOrp6ACqpaQA6ejoAKumpQDp5+cAqqamAKyopwDn5eUAramoAK+rqwDj4eEAsq+uAN/e3gDe3dwAtbGwALezsgDZ19cA2NbWALy5uQDT0dAAwL28AM7MywDFwsIAzcrJAMjFxQDKxsUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQABAQEBAQEBATGUR3ABAQEBAQEBAQEBAQEBAQEBAQEBAAEBAQEBAQEBTAJVjCUBAQEBAQEBAQEBAQEBAQEBAQEAAQEBAQEBAQEjNyxxOQEBAQEBAQEBAQEBAQEBAQEBAQABAQlchXMBAQEBgVlEHAE+cG8+AT4TcD4BUDRcUgEBAD5qXVd7XQ1SAQGIf1pcAXAWZBABJGJDMB9keB4WFQEAGnSEaJMocpcBAZlZfE4BVF0WEAEkXzYOW32XGYBXOgArKAUBAWMoKCUcQ1+JRD5uiTYQASRDBCwzlgEBklYbAJVPAQEBATZ9IV5xAxlWQlCJNhABJDaHh1sjAQFviUoAPgEBUSdNEocQT3FcixEuHClDUgEkNiiEC3oBAVKKCAABCmtkf3tWLlBfX1BwgkV3QyhzARBfQzgGZQEBFH09AFh/M3l/RGkBjTIgAQFofY4XfGohOyZGSHhiH15GU2AAmn2PD4M+AQEsQCoBAUsdGIlDRTNWdDw+mVZxcnKVAQBJX1IBAX5nGQc7bgEBJWmRSDUQaW1mPwEBYZhsjj4BAC9bKnVBLCItAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAgVZ2KFoehkIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQABjZWQDGsKAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAEBAT4BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAP////8=" width="48" align="right"><div><strong><a href="http://gofile.me/6rZyd/bjUHXQcxC">Connecting...</a></strong></div></blockquote>

**Comment by snipe** [comment]
That link is showing an SSL error, and I'm not gonna click on insecure links from sources I don't know ;-)

You can just paste them in here though.

**Comment by cfenell** [comment]
I can confirm that this behaviour still exists in the latest Docker images. 
/var/www/html/storage/logs/laravel.log becomes owned by root and unwritable. My workaround was:
* start over with a fresh mysql container and storage volumes
* restart the SnipeIt container and connect to it before trying to log in
    docker exec -it snipeit bash
    #chmod 777 /var/www/html/storage/logs
    #hmod 777 /var/www/html/storage/framework/cache

This allows me to test Snipe-It but I would not recommend it for a production server

**Comment by tomse** [comment]
I can confirm it is still an issue.
Install ubuntu 22.04 LTS from scratch, install docker using docker.com's guide

follow the guide here https://snipe-it.readme.io/docs/docker  using :latest as of current day.
using with ssl part and copying keys into the docker the suggested way in the documentation (docker cp)

rather than permitting everything like mentioned above, changing owner was enough for me
 
docker exec -it snipeit bash
chown -R docker /var/www/html/storage/logs
chown -R docker /var/www/html/storage/framework/cache

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/docker">Docker</a></strong></div><div>Note very loudly that additional Docker options should be set in the env file, and they require a full container rebuild!</div></blockquote>

**Comment by shanold** [comment]
Same issue still live 2/12/24 pulled from dockerhub  :latest tag Work around above got me going 
"ubuntu server 22.04" using docker run.

**Comment by uberbrady** [comment]
I'm not really sure what's going on here - we have lots of stuff in our main `Dockerfile` that handles permissions stuff - namely here: 
```
RUN \
        rm -r "/var/www/html/storage/private_uploads" && ln -fs "/var/lib/snipeit/data/private_uploads" "/var/www/html/storage/private_uploads" \
      && rm -rf "/var/www/html/public/uploads" && ln -fs "/var/lib/snipeit/data/uploads" "/var/www/html/public/uploads" \
      && rm -r "/var/www/html/storage/app/backups" && ln -fs "/var/lib/snipeit/dumps" "/var/www/html/storage/app/backups" \
      && mkdir -p "/var/lib/snipeit/keys" && ln -fs "/var/lib/snipeit/keys/oauth-private.key" "/var/www/html/storage/oauth-private.key" \
      && ln -fs "/var/lib/snipeit/keys/oauth-public.key" "/var/www/html/storage/oauth-public.key" \
      && ln -fs "/var/lib/snipeit/keys/ldap_client_tls.cert" "/var/www/html/storage/ldap_client_tls.cert" \
      && ln -fs "/var/lib/snipeit/keys/ldap_client_tls.key" "/var/www/html/storage/ldap_client_tls.key" \
      && chown docker "/var/lib/snipeit/keys/" \
      && chown -h docker "/var/www/html/storage/" \
      && chmod +x /var/www/html/artisan \
      && echo "Finished setting up application in /var/www/html"
```

And then everything runs as the `docker` user - and you can see there that we are `chown`'ing and `chmod`'ing and it _should_ just generally work. If I could understand a little better _what_ the workaround was that seemed to 'fix' the problem, I might better be able to improve our Docker implementation. But generally, it does seem to work OK for most users. There are definitely improvements that can be made, of course.

If someone wanted to put up a PR that improved things, I'd be happy to take a look and probably accept it.

**Comment by tomse** [comment]
@uberbrady  
this fixed it for me
```
docker exec -it snipeit bash
chown -R docker /var/www/html/storage/logs
chown -R docker /var/www/html/storage/framework/cache
```

so, try and add the 2 chown lines to the Dockerfile.

uhmm.. I may try and make a pull request (PR?) - I'd love to help, but this is new territory for me - a little bit of guidance could be useful for me.

**Comment by y0d4a** [comment]
hm, i got same issue and i cannot do chown on docker user, because i have only root on this box, so all is on the root user

**Comment by ThePes76** [comment]
> [@uberbrady](https://github.com/uberbrady) this fixed it for me
> 
> ```
> docker exec -it snipeit bash
> chown -R docker /var/www/html/storage/logs
> chown -R docker /var/www/html/storage/framework/cache
> ```
> 
> so, try and add the 2 chown lines to the Dockerfile.
> 
> uhmm.. I may try and make a pull request (PR?) - I'd love to help, but this is new territory for me - a little bit of guidance could be useful for me.

I'm trying to solve with your suggestions, but I've 2 problems...
1) in my docker "storage/*" is under /defauts/storage, I've nothing under var/www/htlm
2) no user docker exists, only root...

thank for help
I'm using Docker with Portainer, and I pull [linuxserver/snipe-it:latest] last update 7 days ago.
