### ISSUE TITLE
[Feature Request]: Barcode for consumables

### ISSUE THREAD

**Issue by seemedFilm** [grokability/snipe-it#12319]
### Is your feature request related to a problem? Please describe.

As assets can have barcodes, I would like to have them for consumables.

### Describe the solution you'd like

I would like to have a barcode / QR code for consumables. Similiar request as two previous feature requests

### Additional context

Im running:
Snipe-IT version
v6.0.14 build 9038 (g163b3f6c0)
Software License
[AGPL3](https://www.gnu.org/licenses/agpl-3.0.en.html)
PHP Version
8.1.7-1ubuntu3.1
Laravel Version
8.83.22

**Comment by snipe** [comment]
Duplicate of #3957
