### ISSUE TITLE
[Feature Request]: Username in the "Checked Out To" column.

### ISSUE THREAD

**Issue by KornDevbr** [grokability/snipe-it#12322]
### Is your feature request related to a problem? Please describe.

Hi. When I open the "Assets list" there is no username inside the "Checked Out To" column. I see it only in the format: "John Snow". Is there a way to show "Checked Out To" in the next format: "John Snow (nickname)"?

### Describe the solution you'd like

When I open the "Asset list" I want to have the possibility to see a username of a user or to configure a custom column with it.

**Comment by Godmartinz** [comment]
closing this issue for now.
