### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by julian-piehl** [grokability/snipe-it#12321]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

For the changes in locations, the translations are missing.
https://github.com/snipe/snipe-it/commit/e670ffe34905d5a0634ee17114ca17f7e17777f1#diff-66f172ea24faa0e9945758ee534fee1a1dc02d071614cfe3665a287d1b476434
- assigned_assets
- current_location

I wanted to add them for my language in Crowdin, but I can't see them there.

### Reproduction steps

---

### Expected behavior

---

### Screenshots

![image](https://user-images.githubusercontent.com/32363424/211307171-b0a96ed4-59da-4fac-a817-d6e1113fbf10.png)
![image](https://user-images.githubusercontent.com/32363424/211307217-e0b84a38-4664-4b23-98b9-71e3ef27b212.png)

### Snipe-IT Version

Newest

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.0

**Comment by snipe** [comment]
We just hadn't updated all of the files in CrowdIn yet. They should be up now.

**Comment by julian-piehl** [comment]
Oh, oke. Thought they should update automatically :D

It's working now 👍

**Comment by snipe** [comment]
FYI I just added a handful more of the newer strings as well
