### ISSUE TITLE
Signature is missing into Version v6.0.14 - build 9161

### ISSUE THREAD

**Issue by TrainAs** [grokability/snipe-it#12338]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Box of Require users to confirm acceptance of assets in this category is already ticked. 
However, the signature section and EULA section is still missing when into checkout page such as https://demo.snipeitapp.com/ page. 

### Reproduction steps

1.Tick the box of Require users to confirm acceptance of assets in this category is ticked under specific category page.
2.Go to specific category's assets to check out
3.No signature popup 
...

### Expected behavior

Suppose signature should be pop up before user to check out such as https://snipe-it.readme.io/docs/requiring-acceptance

### Snipe-IT Version

v6.0.14 - build 9161

### Operating System

Ubuntu 20.04

### Web Server

Apahce

### PHP Version

7.4.3

**Comment by snipe** [comment]
> No signature popup

There was never a signature popup. If a sig is required, the user gets an email that prompts them to sign.

**Comment by TrainAs** [comment]
thanks snipe. 
It means that check out button just one click button , and cannot force someone to sign back and return face to face. Am i correct?
