### ISSUE TITLE
Margin error on labels

### ISSUE THREAD

**Issue by julian-piehl** [grokability/snipe-it#12332]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Don't know if it was a mistake, but the margin changes in this commit causing the barcode to inside the texts.
https://github.com/snipe/snipe-it/commit/301c4fda6e81eecbe4abb9c0f89b28662fa05b1f

### Reproduction steps

---

### Expected behavior

---

### Screenshots

![image](https://user-images.githubusercontent.com/32363424/211582306-4593aeec-f3b5-4959-a639-4a42d40bb238.png)

### Snipe-IT Version

6.0.14

### Operating System

Linux

### Web Server

Apache

### PHP Version

8.0

**Comment by timothevs** [comment]
We are facing this issue as well. Thanks for looking into it.

For the time being, we have inserted an override into the custom CSS. Hopefully, this gets fixed in a later release. Version 6.1 did not fix it BTW.

**Comment by Godmartinz** [comment]
If this is an issue still for anyone else:
May I recommend using the Custom CSS available in Settings->Branding?
There is a text area you can apply values that would work best for you:

![image](https://github.com/snipe/snipe-it/assets/47435081/cdbc03de-3859-4532-967a-d03d72e6c248)

Copy & Paste this into Custom CSS to adjust the value for the Y axis of the barcode (Default settings reflected below):
```
img.barcode {
        margin-top:-7px;
    }
```

If you would like to adjust your QR code ​(​Default settings reflected below):
```
img.qr_img {

    width: 120.79%;
    height: 120.79%;
    margin-top: -6.9%;
    margin-left: -6.9%;
    padding-bottom: .04in;
}
```

I hope adjusting these to your liking will solve your issue.
