### ISSUE TITLE
Could not bind to LDAP: Can't contact LDAP server - Google Workspace - Turnkey

### ISSUE THREAD

**Issue by ZacMussatt** [grokability/snipe-it#12346]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am having a heck of a time getting LDAPS to connect and be able to do a test synchronization.  I have followed the snipe-it documentation in reference to google workspace.  I have therefore created my certificates and user ID, and entered those into the configuration.  Despite this, I'm really not getting test synchronization to work.  One strange thing is that I did get it to work, briefly for a few synchronizations. I didn't like the data that it was pulling, so I started by using a different LDAP filter.  After changing this, I'm no longer able to get it to sync.
I've gone and reinstalled the whole VM fresh and I've regenerated my application credentials with Google.
I am able to connect to my workspace ldap by using LDP.exe in windows using the same cert/key and user/pass.  I'm able to see my ldap entries just fine with this method.

My current settings:
```
LDAP Integration:  Checked LDAP enabled
LDAP Password Sync: not checked
Active Directory: Not checked
AD Domain: Empty.
LDAP Client-Side TLS key:  My Key, starts and ends with Private Key entries  (Meaning -----BEGIN PRIVATE KEY----- and -----END PRIVATE KEY-----)
LDAP Client-Side TLS Certificate: My cert, starts and ends with Certificate entries
Ldap Server: ldaps://ldap.google.com
Use TLS : Not checked
LDAP SSL certificate validation: not checked
LDAP Bind Username:  Generated Username from google
LDAP Bind Password: Generated Pass from google
Base Bind DN:  DC=mydomain,dc=com
LDAP Filter: &(cn=*)
Username Field: mail
Last Name: sn
LDAP First Name: givenname
LDAP Authentication query: uid=
LDAP Version: 3
LDAP Active Flag: <Empty>
LDAP Employee Number: employeeNumber
LDAP Department: departmentNumber
LDAP Manager: <Empty>
LDAP Email: mail
LDAP Telephone Number: telephoneNumber
LDAP Job Title: <Empty>
LDAP Country: <Empty>



```

### Reproduction steps

1. Installed Snipe via Turnkey linux
2. Set up Google LDAP App
3. Filled LDAP settings as above
4. Test LDAP Synchronization via button: Could not bind to LDAP: Can't contact LDAP server
...

### Expected behavior

I'm expecting it to give a preview of the items and fields that it pulls from LDAP.

### Snipe-IT Version

v6.0.13

### Operating System

Debian

### Web Server

Apache

### PHP Version

7.4.33

### Error messages

```shell
[19:40:13] LOG.debug: Preparing to test LDAP connection
DEBUGLOG[19:40:13] LOG.debug: attempting to bind to LDAP for LDAP test
DEBUGLOG[19:40:13] LOG.debug: Bind failed
DEBUGLOG[19:40:13] LOG.debug: Exception was: Could not bind to LDAP: Can't contact LDAP server
```

### Additional context

Fresh install from turnkey Linux

As noted above, I was able to get this working for a moment, then it totally stopped.  Since then I've reloaded and regenerated my keys.

**Comment by uberbrady** [comment]
I don't really know anything about 'turnkey linux' - but you might get some interesting responses if you try `php artisan ldap:troubleshoot --ldap-search` - but do note that the paths that you get back from that that refer to your client-side TLS certificates need to be replaced with absolute paths - e.g., instead of "./foo/bar/baz" you should put "/home/mything/snipeit/foo/bar/baz/"

I suspect we're dealing with an openssl issue of some sort; where it doesn't have the stuff it needs to do client-side TLS certs.

**Comment by ZacMussatt** [comment]
Huh, I legitimately thought that it was a desirable and supported method for installing Snipe.  https://www.turnkeylinux.org/snipe-it
But now that I look, it's indeed not in the documentation. 
I guess I just didn't want to deal with setting up the environment.
However, I digress and return to the issue at hand:
That command yields some interesting info:
```
LDAPTLS_CERT=storage/ldap_client_tls.cert \
LDAPTLS_KEY=storage/ldap_client_tls.key \
ldapsearch \
-H ldaps://ldap.google.com \
-x \
-b 'dc=mydomain,dc=com' \
-D 'CORRECTBINDUSER \
-w 'CORRECTBINDPASSWORD' \
'(&(cn=*))' \
-v
```
Now, the interesting thing to me, is the ldap_client_tls.cert and .key  I have looked at those, and they do not match my current certificate and key from Google Workspace.  Are we saying that they should?  


<blockquote><img src="https://www.turnkeylinux.org/favicon.ico" width="48" align="right"><div><strong><a href="https://www.turnkeylinux.org/snipe-it">Snipe IT | TurnKey GNU/Linux</a></strong></div><div>Snipe IT provides a powerful, user friendly asset management system, which your team will love to use. It was designed to enable IT departments big or small to track who has what hardware, when it was purchased, which software licenses apply to it and what accessories are available, and so on.</div></blockquote>

**Comment by ZacMussatt** [comment]
Updating the certificate didn't result in things working.  
Also, if I run just: php artisan ldap:troubleshoot
I get ERROR: DNS lookup of host: ldap.google.com has failed. ABORTING.
But DNS is working at least in terms of ping and NSLOOKUP.  
I'm going to go through and do a ground up install and see if things are different.

**Comment by ZacMussatt** [comment]
I reinstalled onto a new system:  Ubuntu 22.04, used the install.sh, read the full set up documents.... Wouldn't you know it worked the first try.

**Comment by uberbrady** [comment]
Awesome! Glad you got it up and running :)
