### ISSUE TITLE
Emails for checking in/out not being sent, every other type of email works. 

### ISSUE THREAD

**Issue by FrostedFlamesTips** [grokability/snipe-it#12344]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

My project was running perfectly fine, it still does. However, it no longer sends email notifications when I check anything in/out. It was working just fine yesterday, then without me changing anything, it stopped. All other types of emails get sent, I tried the test email and sending credentials to new users and both worked flawlessly. 

It cannot possibly be an issue with the email as all other types of emails get sent. I get no errors with the debugger whatsoever. I even tried a brand new project on another pc with a completely different operating system (windows), and still I'm facing the same issue. I'm only posting this to see if anyone else is facing  the same problem. 

### Reproduction steps

1.Checkoput an Asset
2. Assign it to a user who has an email and put in an expected check in date
3. Set status to "Ready to deploy"
4. Click "checkout"
5. Receive message: "Success: Asset checked out successfully."
6. No email to the assigned user gets sent but everything else goes as planned
7. The same thing happens when you check something in.

### Expected behavior

The assigned user should receive an email that they have checked out an item.

### Snipe-IT Version

6.0.14 build 9038 (g163b3f6c0)

### Operating System

Windows, and Macos (Locally hosted using XAMPP)

### Web Server

Apache

### PHP Version

8.0.11 on windows and 8.2.1 on Macos

### Operating System

Windows and Macos

### Browser

Chrome

**Comment by AkimoA** [comment]
the category which includes the asset has the "send emails to user  at check  in/out" box ticked as well ?

**Comment by FrostedFlamesTips** [comment]
@AkimoA I was not aware there was such a check box ... .  Thank you so much! You're an absolute legend!

**Comment by AkimoA** [comment]
glad i could help , maybe u could close this issue then ;)
