### ISSUE TITLE
Why is label size altered when changing label spacing

### ISSUE THREAD

**Issue by iangozer** [grokability/snipe-it#12348]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am working on some improvements to the label creation / layout, I notice that when you set values for label spacing it decreases the value for label dimension.
I am working on the assumption the label width should always be the width of the label on the sheet and the spacing should be the space between each label.
So, if I set label width to 3" and horizontal spacing to 0.5" the value returned by $settings->labels_width is 2.5"
I'm sure this is done for a reason, but I just can't see what it is, I am guessing this is why so many people get stuck with labels not printing as expected.

Is this the expected behaviour?
Is there a reason this behaviour couldn't be changed?

### Reproduction steps

1. Change label spacing
2. Label size returned to frontend it changed
3.
...

### Expected behavior

Label size should be label size and not affected by the spacing.

### Snipe-IT Version

6

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7

**Comment by iangozer** [comment]
@snipe @Godmartinz

**Comment by iangozer** [comment]
Anyone?

**Comment by snipe** [comment]
We haven't had time to look at this yet. Please be patient - and in the future, please provide more information. Snipe-IT version 6 doesn't give us a lot to work with (as we have had 14 releases since 6.0.0 and are about to release v6.1). PHP 7 doesn't either. Specific point releases and hashes (when available) will help narrow things down.

**Comment by iangozer** [comment]
It is not an issue with my setup, it is a question about the code. 
I have now found where this is being done.
I just can't tell why and if we can remove it, as it doesn't seem to be logical.

snipe-it/resources/views/hardware/labels.blade.php

```
$settings->labels_width = $settings->labels_width - $settings->labels_display_sgutter;
$settings->labels_height = $settings->labels_height - $settings->labels_display_bgutter;
```

**Comment by Godmartinz** [comment]
I just wanted to point out that we have added an alternative label engine since this post and that it should solve your issues. Im closing this for now.
