### ISSUE TITLE
Deleting imported files visually drops first element in table

### ISSUE THREAD

**Issue by itakestime** [grokability/snipe-it#12340]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Attempting to delete an imported file will cause the file to be deleted in the backend, but the frontend shows that the first row in the table has been removed. 

Refreshing the page restores the first item in the row and no longer lists the file that was requested to be deleted.

### Reproduction steps

1. Import several files
2. Go to the 'Imports' page and click the 'delete' button for an entry
3. Observe that the top entry in the table is removed instead of the entry that was requested to be deleted.
4. Refresh the page and observe that the entry requested to be deleted is missing from the list, and the top entry has been restored.

### Expected behavior

The file requested to be deleted is removed from the list in the UI instead of the first entry in the row.

### Screenshots

![Peek 2023-01-12 12-17](https://user-images.githubusercontent.com/16022371/211938706-21e2424c-0883-4eaa-a33d-2a1bc0fdf482.gif)

### Snipe-IT Version

v6.0.14 - build 9161 

### Operating System

Ubuntu 20.04

### Web Server

Nginx

### PHP Version

7.4

### Operating System

Ubuntu

### Browser

Google Chrome

### Version

107

**Comment by snipe** [comment]
Thanks for this (and TY for the excellent bug report)! I'm not sure how I ever noticed that, but we'll definitely take a look.
