### ISSUE TITLE
[Feature Request]: Add sort function on column "groups" and "2fa active" in users view

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#12356]
### Is your feature request related to a problem? Please describe.

You can't sort for the column "groups" in the users view.
![image](https://user-images.githubusercontent.com/112496896/212637226-081e798e-3a86-4903-a98b-f882fea614d7.png)

You can't sort for the column "2fa active" in the users view.
![image](https://user-images.githubusercontent.com/112496896/212637857-c04d14ff-31e0-4448-beff-6a9c4a0afd4c.png)

### Describe the solution you'd like

A sort function like all the other columns have.
![image](https://user-images.githubusercontent.com/112496896/212638073-aeeada71-55af-4df0-b797-5df46f9e08ba.png)

### Additional context

Or is there a reason, that you can't sort for these columns?

**Comment by snipe** [comment]
Sorting by group can get a little confusing, since a user could belong to multiple groups - so which are we ordering by? The 2FA sort is easily fixed though - I'll have a patch out shortly.

**Comment by floschoepfer** [comment]
> Sorting by group can get a little confusing, since a user could belong to multiple groups - so which are we ordering by?

Never thought about that... You could sort for the group IDs, for example, if the user is in two groups, he's only sorted by the first group (the group with the lower ID).
I came up with this issue, because I wanted to sort for the groups to find out, which users are in no group.
But I see your point, and I'm totally fine, if there's no sort on the groups column.
