### ISSUE TITLE
[Feature Request]: Upload user photos via REST API

### ISSUE THREAD

**Issue by ShaunNeighbourSwale** [grokability/snipe-it#12350]
### Is your feature request related to a problem? Please describe.

Similar to https://github.com/snipe/snipe-it/issues/9413 I would appreciate the ability to upload user photos via the REST API.

### Describe the solution you'd like

/user/[user_id]/image (GET -> List uploaded files for user)
/user/[user_id]/image (POST -> upload new image)
/user/[user_id]/image/[image_id] (GET download image)
/user/[user_id]/image/[image_id] (DELETE image)

**Comment by snipe** [comment]
> /user/[user_id]/image (GET -> List uploaded files for user)

That kinda doesn't make sense though? Not all upload files would be an image, and not all have an ID. There is only one user avatar image provided (and that's on the user object itself, so it's already available there.

**Comment by snipe** [comment]
(Additionally, you can already upload files via the API)

```
|        | GET|HEAD      | api/v1/users/{user}                                      | api.users.show                          | App\Http\Controllers\Api\UsersController@show                                       | Illuminate\Auth\Middleware\Authenticate:api                       |
|        | PUT|PATCH     | api/v1/users/{user}                                      | api.users.update                        | App\Http\Controllers\Api\UsersController@update                                     | Illuminate\Auth\Middleware\Authenticate:api                       |
|        | DELETE        | api/v1/users/{user}                                      | api.users.destroy                       | App\Http\Controllers\Api\UsersController@destroy                                    | Illuminate\Auth\Middleware\Authenticate:api                       |
|        | GET|HEAD      | api/v1/users/{user}/accessories                          | api.users.accessorieslist               | App\Http\Controllers\Api\UsersController@accessories                                | Illuminate\Auth\Middleware\Authenticate:api                       |
|        | GET|HEAD      | api/v1/users/{user}/assets                               | api.users.assetlist                     | App\Http\Controllers\Api\UsersController@assets                                     | Illuminate\Auth\Middleware\Authenticate:api                       |
|        | POST          | api/v1/users/{user}/email                                | api.users.email_assets                  | App\Http\Controllers\Api\UsersController@emailAssetList                             | Illuminate\Auth\Middleware\Authenticate:api                       |
|        | GET|HEAD      | api/v1/users/{user}/licenses                             | api.users.licenselist                   | App\Http\Controllers\Api\UsersController@licenses                                   | Illuminate\Auth\Middleware\Authenticate:api                       |
|        | POST          | api/v1/users/{user}/restore                              | api.users.restore                       | App\Http\Controllers\Api\UsersController@restore                                    | Illuminate\Auth\Middleware\Authenticate:api                       |
|        | POST          | api/v1/users/{user}/upload                               | api.users.uploads                       | App\Http\Controllers\Api\UsersController@postUpload                                 | Illuminate\Auth\Middleware\Authenticate:api
```

**Comment by ShaunNeighbourSwale** [comment]
Thanks!  I'll give it a go!

**Comment by ShaunNeighbourSwale** [comment]
Can't see any documentation for this at https://snipe-it.readme.io/reference/users-2

Do you have an example command that I can use? 

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/users-2">/users</a></strong></div><div>Create a new user</div></blockquote>

**Comment by HendrikClijstersMosa** [comment]
I have dug around the Snipe-It source code (V6.014). The route api/v1/users/{user}/upload exists. However, the function it points to (postUpload) doesn't exist. So I don't think this works. This might still be WIP?

![api php](https://user-images.githubusercontent.com/99736791/213190204-0a2711f3-d6f2-4ec1-bcf2-aa061c5747c4.jpg)
![UsersController](https://user-images.githubusercontent.com/99736791/213190250-1a50e1f3-1006-4fe2-b4e0-4a0f69e42f9c.jpg)

**Comment by ShaunNeighbourSwale** [comment]
Thank you for checking!

**Comment by HendrikClijstersMosa** [comment]
I have found it is still possible to upload an image using the API. This because snipe-it has an option to add an avatar-image to a user. Do keep in mind that you can only upload 1 image to a user in this way. Uploading a new image will simply overwrite the previous one.  In Python it will look something like this:
```Py
import requests, base64

# Convert image you want to add as banner into base64.
with open("python.png", "rb") as image_file: 
    encoded_string = base64.b64encode(image_file.read())
    decoded_string = encoded_string.decode('utf-8')

# API to a certain user.
url = f"http://ADD_SERVER_HERE/api/v1/users/5001"

# Header to access API.
headers = {
        "accept": "application/json",
        "Authorization": "Bearer ADD_KEY_HERE",
        "content-type": "application/json"
    }

# What we want to add/change about the user.
# first_name, last_name and username appear to be mandatory.
payload = {
    "first_name": "Hendrik",
    "last_name": "Clijsters - TestAPI",
    "username": "hendrik.clijsters testAPI",
    "image": f"data:image/png;name=python.png;base64,{decoded_string}"
}

# Do a PUT request to change an existing user. 
# If the user does not yet exist, use a POST request instead.
response = requests.put(url, json=payload, headers=headers)
```

If you want to download an avatar of a user. You can get the URL of this avatar as follows:
```Py
response = requests.get(url, headers=headers)
print(response.json()["avatar"])
```
The avatar will also show up on the user-tab in snipe-it. 
![snipe-it_image](https://user-images.githubusercontent.com/99736791/213194453-102ab557-ae8f-4654-8de0-94e0987c63da.jpg)

Avatars are documented in the [asset part of the readme](https://snipe-it.readme.io/reference/hardware-update) (look for image). So if you are more familiar with other programming languages you can make your own examples there.

**Comment by ShaunNeighbourSwale** [comment]
I'll give that a go tomorrow - Thank you again!

**Comment by ShaunNeighbourSwale** [comment]
[HendrikClijstersMosa](https://github.com/HendrikClijstersMosa) That works perfectly!  Thank you!
