### ISSUE TITLE
Bug With Passwords Including Ampersands?

### ISSUE THREAD

**Issue by corydlamb** [grokability/snipe-it#12362]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello, loving Snipe thus far, however. I believe I may have accidentally found a bug involving passwords with ampersands and the auto generated email sent to users with credentials. I sent a user this automated email and the part of the password with the & also had amp; appended after the & (So, for example, instead of the password being "d57*J08]& 'amp;' Sajb9VI" it was "d57*J08]&Sajb9VI"). I'm assuming this may be an issue with the HTML used in email? Or would it be something on my end?

### Reproduction steps

1. Create user with password including a & character.
2. Send user credential email.
3. Observe "amp;" getting appended after the &.

### Expected behavior

Expected Password without the "amp;" as removing that portion of text fixes the issue.

### Screenshots

![pass test](https://user-images.githubusercontent.com/97770090/213031988-391d0367-c539-4358-a294-ff51d7011811.png)

### Snipe-IT Version

v6.0.14 build 9038

### Operating System

Turnkey Linux

### Web Server

Apache 2.4.38

### PHP Version

8.1.11

### Operating System

Windows

### Browser

Google Chrome

### Version

109.0.5414.74 (64 bit)

**Comment by corydlamb** [comment]
Hey, found a fix for this, going to see about submitting a pull request.

**Comment by uberbrady** [comment]
That'd be awesome, thank you!

**Comment by corydlamb** [comment]
Created a pull request at https://github.com/snipe/snipe-it/pull/12363 let me know if I need to add anything. Nothing major so idk if you need me to do all of the stuff but if it must be done I'd be glad to :D @uberbrady

**Comment by snipe** [comment]
Merged, ty!
