### ISSUE TITLE
stuck at step 12 Install Dependencies

### ISSUE THREAD

**Issue by Rockstarhs** [grokability/snipe-it#12368]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

  The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: failed
   to open stream: Permission denied

step 12 found here https://gist.github.com/bengriffithsaudio/f2d6d0e7ecf3493c053e6866095e0a77#1-launching-an-ec2-instance

### Reproduction steps

NA
2.
3.
...

### Expected behavior

Wait patiently for composer to download the dependencies into the cache and subsequently install them.

13 Generate App Key
$ sudo php artisan key:generate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

### Snipe-IT Version

https://gist.github.com/bengriffithsaudio/f2d6d0e7ecf3493c053e6866095e0a77#1-launching-an-ec2-instance

### Operating System

ubuntu

### Web Server

Apache

### PHP Version

na

### Error messages

```shell
The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: failed
   to open stream: Permission denied
```

### Additional context

https://gist.github.com/bengriffithsaudio/f2d6d0e7ecf3493c053e6866095e0a77#1-launching-an-ec2-instance

**Comment by itakestime** [comment]
Sounds like you need to grant permissions to `/var/www/snipe-it/storage/logs/laravel.log` so that it can be written?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
