### ISSUE TITLE
EOL not sortable

### ISSUE THREAD

**Issue by najirod** [grokability/snipe-it#12372]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

EOL column in Assets preview is not sortable in any way.
Tried every date format
demo.snipeitapp.com has the same issue

### Reproduction steps

1. Assets
2. EOL column
3.
...

### Expected behavior

sort by date like purchase cost column

### Screenshots

![Screenshot_2022-12-14_at_12 59 39](https://user-images.githubusercontent.com/100681846/213376563-2f481ccb-8337-435e-97e2-cd74955e8e0f.png)

### Snipe-IT Version

 v6.0.14

### Operating System

Ubuntu 

### Web Server

Apache

### PHP Version

8.1.2

**Comment by floschoepfer** [comment]
I guess, this is not a bug, but rather a feature request?
What do you think @snipe ?

**Comment by corydlamb** [comment]
Seems fairly straight forward. Going to see about doing a pull request for this :)

**Comment by corydlamb** [comment]
Not as straightforward as I thought lol, sorry!

**Comment by snipe** [comment]
Heh, it almost never is. :D If it were super-simple, we'd typically have already done it.

**Comment by snipe** [comment]
@najirod We've got a PR up now - https://github.com/snipe/snipe-it/pull/12393 - but I'll need to test it a lot more and it still requires review from my team before I can merge.

**Comment by snipe** [comment]
This is on master now

**Comment by najirod** [comment]
@snipe Thank you and your team very much it works great! ☺️
