### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by conan522** [grokability/snipe-it#12371]
### Is your feature request related to a problem? Please describe.

Can you add a computer status view feature, such as online, offline?

### Describe the solution you'd like

Use ping computer hostname test to monitoring computer status. Additional feature, if computer is in use status and offline over like 1 week, will get notification from system.

**Comment by snipe** [comment]
That's a bit outside the scope of what we do here. You'd be better off writing some sort of monitoring pilling system that integrates with the Snipe-IT API and update a custom field on result
