### ISSUE TITLE
Login with mail

### ISSUE THREAD

**Issue by shinduke** [grokability/snipe-it#12383]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

we have set up Snipe-IT and could make some tests. Now we have configures SAML and LDAP sync.
LDAP sync is working fine and the useres are created but now we are facing the problem, that if a user tries to login with his mail we get the error since the username is not the mail adress in Snipe-IT. 
We don´t really know where exaclty we have to make the change and also how to change all of the entries that are already in the DB.
Debug tells me that the username could not be found in the database.
I searched ylready many sites for this but couldn´t find a solution that maches for this.

Any help yould be awesome.

### Reproduction steps

1. Login via SAML
2. Enter credentials
3.
...

### Expected behavior

Login via SAML and SSO

### Snipe-IT Version

v6.0.11 build 8758 (g61fa0bda4)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.2

**Comment by snipe** [comment]
You'd just want to make the username the existing email address. https://snipe-it.readme.io/docs/ldap-sync-login

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/ldap-sync-login">LDAP Sync & Login</a></strong></div><div>For example, if your manually created or CSV imported usernames look like jane.smith (with an email value of jane.smith@yourdomain.com), you should confirm that the directory service you're syncing to uses jane.smith as a username value, OR update the usernames of your users to be consistent with wh...</div></blockquote>
