### ISSUE TITLE
Custom Fields are not listing in Coloumns list

### ISSUE THREAD

**Issue by ozererturul** [grokability/snipe-it#12395]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I created Custom Field and add it to Fieldset bu can't list this Custom Field in Columns list. It is a clean ubuntu 22.04 and snipe-it installation. In a lab environment it was working but as I remember php version was 7.4

System Information
Snipe-IT versionv6.0.14 build 9236 (g05a3f20d5)
Software License [AGPL3](https://www.gnu.org/licenses/agpl-3.0.en.html)
PHP Version8.1.2-1ubuntu2.9Laravel Version8.83.27

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Want to see Custom Fields in column list 

### Screenshots

![columns](https://user-images.githubusercontent.com/123366461/214040422-6dc99e13-4a8c-4df6-b932-ab14e1e72308.JPG)
![CustomField](https://user-images.githubusercontent.com/123366461/214040426-2dd5bd5f-b2cd-46e8-9959-77733f689f31.JPG)
![CustomFieldSet](https://user-images.githubusercontent.com/123366461/214040428-ec186671-43a8-4614-a71c-931d8830f29c.JPG)

### Snipe-IT Version

6.0.14

### Operating System

ubuntu 22.04

### Web Server

apache2

### PHP Version

8.1

### Browser

Chrome

**Comment by snipe** [comment]
Did you associate the fieldset to any models? They won't show unless they belong to at least one model.
