### ISSUE TITLE
Data loading issue with nginx

### ISSUE THREAD

**Issue by zeemalik2008** [grokability/snipe-it#12412]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Data loading issue when enable nginx proxy, working ok on local host and local IP.

### Reproduction steps

1.
![Screenshot 2023-01-25 at 2 44 15 PM](https://user-images.githubusercontent.com/62511135/214532872-426351a0-88a3-430c-a8c4-bd5cc40f1ac7.png)

2.
3.
...

### Expected behavior

when move to https web page and java loading perfect but my saved data not showing .

### Screenshots

![Screenshot 2023-01-25 at 2 44 05 PM](https://user-images.githubusercontent.com/62511135/214531986-3527ad06-4e9d-4d29-b5d0-b6d6f4f2e80c.png)
![Screenshot 2023-01-25 at 2 44 15 PM](https://user-images.githubusercontent.com/62511135/214532001-a4cd9296-8451-4dc3-839f-991606321948.png)

### Snipe-IT Version

Version v6.0.14 - build 9161 (master)

### Operating System

Ubuntu 20.04

### Web Server

apache

### PHP Version

PHP 7.4.3-4ubuntu2.17

### Operating System

MAC OS Catalina 

### Browser

Chrome, Safari

### Version

Catalina 10.15.7

**Comment by n3s0** [comment]
Are there any errors in inspector or the Nginx error/access logs?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
