### ISSUE TITLE
[Feature Request]: Don't allow duplicate users

### ISSUE THREAD

**Issue by eugene-bce** [grokability/snipe-it#12428]
### Is your feature request related to a problem? Please describe.

When I import users via CSV, it will create duplicate users with the same username. 

### Describe the solution you'd like

The username should be a unique field. If a duplicate is found, either skip or update (or give an option)

**Comment by snipe** [comment]
That is disallowed at the model level, so I'm not sure why you'd be seeing that.

**Comment by snipe** [comment]
I haven't been able to reproduce this.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
