### ISSUE TITLE
[Feature Request]: assets depreciation 

### ISSUE THREAD

**Issue by okkhalid** [grokability/snipe-it#12426]
### Is your feature request related to a problem? Please describe.

Is there any way to create asset depreciation? that can calculate based on the tax formula and could create the depreciation for the assets? and show the end date. and show the balance ... etc. 

### Describe the solution you'd like

create an assets depreciation table for the assets.

**Comment by Godmartinz** [comment]
HI @okkhalid, Are you asking for a way to add a custom formula for a depreciation model? If so, we currently don't offer that. Or are you referring to some universal tax formula? if so please share that formula with us.

**Comment by okkhalid** [comment]
Hi, I think I'm ok with the depreciation that already comes with: straight-line depreciation method is great. thank you

**Comment by Godmartinz** [comment]
Glad to hear you found what you were looking for! I will be closing this ticket then.
