### ISSUE TITLE
Display bug with username in asset listings 

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#12430]
### Debug mode

- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When you export the asset list, the username somehow gets displayed three times in the web interface and is displayed two times in the export file. When you refresh the web interface (or click the refresh button), the duplicated username disappears.
I guess it's related to the feature request #12322 and pull request #12324

Normal:
![image](https://user-images.githubusercontent.com/112496896/215435342-fffe8014-2f60-45a0-993b-863666ef0f06.png)

After you export to a file:
![image](https://user-images.githubusercontent.com/112496896/215435467-2df532a2-021c-429d-af41-eec453a4cf09.png)

In the exported file:
![image](https://user-images.githubusercontent.com/112496896/215435624-31083250-0bb3-4be9-8edf-82b3b3ffa814.png)

### Reproduction steps

1. Open assets list
2. Export current view to a file (like ms-excel)
3. Username is displayed multiple times

### Expected behavior

The username should only be displayed once.

### Screenshots

(see bug description)

### Snipe-IT Version

6.0.14

### Operating System

demo.snipeitapp.com

### Web Server

demo.snipeitapp.com

### PHP Version

8.0.25

### Operating System

Windows 10

### Browser

Microsoft Edge for Business

### Version

108.0.1462.54

**Comment by snipe** [comment]
Fixed in #12439
