### ISSUE TITLE
Accepted Assets PDF - Images not found

### ISSUE THREAD

**Issue by aj-bayanat** [grokability/snipe-it#12434]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,
I am running the official docker image.

When the EULA pdf is generated, the header Image and the signature both show as "Image not found.." Eben though the signature can be seen and clicked on from the Webpage. 
Since I am running the docker image, there are no logs in laravel.log as the file does not exist. 
Even if I create the log file with correct permissions, nothing seems to be written to it. Snipe-IT also tells me there are no permission issues with this file if I run upgrade.php
There are no browser errors either. If there is some other way of getting logs please let me know and I will try it out. 

### Reproduction steps

1. Checkout an asset
2. User accepts and signs it
3. Download EULA pdf from the asset/history page

### Expected behavior

The EULA pdf should have the header image and signature image embedded in it properly without showing an error saying image not found. 

### Screenshots

![image](https://user-images.githubusercontent.com/95169174/215708565-ee37f19e-52fc-4381-99d0-428b00b03b3a.png)

![image](https://user-images.githubusercontent.com/95169174/215708665-f1f6642e-8769-4f7e-b0cf-6a92b61bafb0.png)

![image](https://user-images.githubusercontent.com/95169174/215708742-6860eb53-7b79-4ac7-8308-5411c752feeb.png)

### Snipe-IT Version

v6.0.14 build 9236 (g05a3f20d5)

### Operating System

TrueNAS Scale

### Web Server

Apache

### PHP Version

7.4.3-4

### Additional context

Just to add some info, I moved snipe-it from a manual install on centos stream to docker. Re-created and restored db on mariadb also running in a different docker container.

**Comment by aj-bayanat** [comment]
Hi, Would there be any way of gathering more information about the issue on my end so that I can help you find whats causing this issue ?

**Comment by newburns** [comment]
This is also happening on my system with the official Docker. I am running a standard MySQL database though. Not included in the docker-compose yml file.
Please let me know what I can do to get the logs you are looking for. I can "docker exec -it" but I don't know what logs I need

**Comment by aj-bayanat** [comment]
I also am using a standalone database. MariaDB in my case.

**Comment by aj-bayanat** [comment]
Hi, any updates on this issue? We are still having it after updating to the latest docker image.
Digest:31bfb386afd3
v6.0.14 - build 9715 (master)

**Comment by aj-bayanat** [comment]
I have migrated back to a custom install and the issue is not there anymore. This confirms its only a issue in docker.

**Comment by m4us1ne** [comment]
it looks like a permission error on the files, after some digging i got this error ( i had to enable show_warnings in the dompdf settings)
`root@snipe-7d55698865-tslpn:/var/www/html/public/uploads# ls -l /var/www/html/public/uploads/setting-logo-yQ3ZZX8hpo.svg
-rw-r--r--. 1 docker root 10437 May 16 14:34 /var/www/html/public/uploads/setting-logo-yQ3ZZX8hpo.svg
`
`root@snipe-7d55698865-tslpn:/var/www/html/public/uploads# ls -l /var/www/html/storage/private_uploads/signatures/siglog-d00b081d-d20c-47d9-8596-25d949690e76-2023-06-06-021143.png-rw-r--r--. 1 docker staff 14372 Jun  6 12:11 /var/www/html/storage/private_uploads/signatures/siglog-d00b081d-d20c-47d9-8596-25d949690e76-2023-06-06-021143.png`

`Exception
Error loading /var/www/html/public/uploads/setting-logo-yQ3ZZX8hpo.svg: Permission denied. The file could not be found under the paths specified by Options::chroot. /var/www/html/public/uploads/setting-logo-yQ3ZZX8hpo.svg Error loading /var/www/html/storage/private_uploads/signatures/siglog-d00b081d-d20c-47d9-8596-25d949690e76-2023-06-06-021143.png: Permission denied. The file could not be found under the paths specified by Options::chroot. /var/www/html/storage/private_uploads/signatures/siglog-d00b081d-d20c-47d9-8596-25d949690e76-2023-06-06-021143.png
`
https://flareapp.io/share/OmVjxlxm

<blockquote><div><img src="https://flareapp.io/favicon-16x16.png" height="14"> Flare</div><div><strong><a href="https://flareapp.io/share/OmVjxlxm">Laravel error tracking – Flare</a></strong></div><div>Error loading /var/www/html/public/uploads/setting-logo-yQ3ZZX8hpo.svg: Permission denied. The file could not be found under the paths specified by Options::chroot. 
 /var/www/html/public/uploads/setting-logo-yQ3ZZX8hpo.svg
Error loading /var/www/html/storage/private_uploads/signatures/siglog-d00b081d-d20c-47d9-8596-25d949690e76-2023-06-06-021143.png: Permission denied. The file could not be found under the paths specified by Options::chroot. 
 /var/www/html/storage/private_uploads/signatures/siglog-d00b081d-d20c-47d9-8596-25d949690e76-2023-06-06-021143.png
 - The error occurred at https://inventory-test.synyx.cloud/account/accept/287</div></blockquote>

**Comment by m4us1ne** [comment]
setting [this line ](https://github.com/snipe/snipe-it/blob/fc5b02e3929ce0fa7be837be03bdfff5202b8621/config/dompdf.php#LL78C30-L78C39) to `"chroot" => "/",`
"fixes" it. i'm not really familiar with php so i am still trying to find out to what  `base_path()`  evaluates inside the container compared to a vm based deployment

EDIT:
my theory is that the problem is the symlink inside of the container.  the vm based deployments does not make use of of  symlinks, but the Dockerfile creates symlinks for  various things including public and private uploads
