### ISSUE TITLE
Cannot Create New License

### ISSUE THREAD

**Issue by xgc-it** [grokability/snipe-it#12448]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I want to add new license

### Reproduction steps

1. click to create new license
2. filled in all the information (all fields)
3. done more then 10 times 
...

### Expected behavior

after filling up all the fields > tap on save to save information but it return blank page 

### Screenshots

![image](https://user-images.githubusercontent.com/53569707/216240900-b41aebc1-3720-427b-9f8f-f1dd2445579c.png)

### Snipe-IT Version

v6.0.12 - build 8824 (master)

### Operating System

Windows

### Web Server

Apache (XAMPP)

### PHP Version

8.1.10

### Operating System

Windows

### Browser

Firefox

### Version

109.0

### Error messages

```shell
its not saving data and returning back to blank page (screenshot attached above)
```

### Additional context

please support to fix this issue , rest everything works fine

**Comment by snipe** [comment]
Without error logs, I couldn't really tell you what's going on here. 

Please provide us with the information requested at the Getting Help documentation: 
https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
