### ISSUE TITLE
LDAP Sync - manager field is missing for some user

### ISSUE THREAD

**Issue by shinduke** [grokability/snipe-it#12440]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Manager field is empty for some users. Some Users has all entries

AD has been checked and the manager field is filled for every user

### Reproduction steps

1. LDAP sync Settings set
![image](https://user-images.githubusercontent.com/36949743/216016313-b07163af-5a6e-4941-8d55-a760ad65846d.png)
2. LDAP Sync
3. Sync complete
...

### Expected behavior

LDAP sync is syncing the settings for all users

### Screenshots

![image](https://user-images.githubusercontent.com/36949743/216017029-bc355b9d-6a86-4c64-87af-b5d325495843.png)
![image](https://user-images.githubusercontent.com/36949743/216017254-bfd6f95e-f970-4e87-9473-48bb6a4717cf.png)

### Snipe-IT Version

v6.0.11 build 8758 (g61fa0bda4)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.2

**Comment by mgrigioni** [comment]
manager is not registered  in your system, that's why it's not showing.
maybe this manager is not under your base bind dn.

I have some cases here, where manager is from another OU that i do not control and will not show in, as it's not in my snipe instance

**Comment by shinduke** [comment]
Epic....thank you. 
The fact that we are still in the implementation phase of snipe-it and only one part of our company is synced has caused this issue.
