### ISSUE TITLE
[Feature Request]: Qty field when checking out accessories.

### ISSUE THREAD

**Issue by a8bit** [grokability/snipe-it#12453]
### Is your feature request related to a problem? Please describe.

I usually allocate two monitors to a user or asset (sometimes 4 if they are also having two monitors at home. I'm currently checking out two-four times. if there was a qty field it could be done as a single operation. 

### Describe the solution you'd like

A Qty: field on the accessory checkout page. 

### Describe alternatives you've considered

At the moment I just check out the same accessory multiple times. It works, it's just laborious

**Comment by snipe** [comment]
This was implemented quite a while ago
