### ISSUE TITLE
[Feature Request]: Appending Username Checkout Column

### ISSUE THREAD

**Issue by brianhoganm** [grokability/snipe-it#12469]
### Is your feature request related to a problem? Please describe.

No. I would like **NOT** to have the username appended next to the full name of the person in the **Checkout To** column. This makes the Checkout column really long (especially for long usernames) OR...can we have the option to enable or disable this?  I was looking at the demo and not sure if this feature is going to be added soon or not.
 
![IMAGE](https://user-images.githubusercontent.com/109772627/217105405-a74066c1-b607-430c-bb95-d8a3d60c9e5e.JPG)

### Describe the solution you'd like

Please remove or have the option to turn off the username in the checkout column.

**Comment by floschoepfer** [comment]
We need this kind of information. But I totally agree with you, that this column can become very large when you have long usernames.
I guess, the best solution would be to create a setting, where you can activate or deactivate it.

**Comment by brianhoganm** [comment]
That would be great if we had an option to enable/disable this. I also have
lots of custom fields for my assets and I am always having to turn off the
custom fields by unchecking the columns. This is also frustrating. I only
have to do this if I clear my cache. Otherwise, it's not too bad.  I try to
keep my table nice and clean looking by always having the Check
in, Duplicate, Edit and the Delete buttons show on my screen. I know it's
not always practical for everyone, especially those who have small screens.

If you get a chance, can you all please take a look at my suggestion for
CUSTOM FIELDS? (I know that is not everyone's favorite subject! :) I would
like to disable the custom fields from appearing in the assets list table
automatically. Right now, I am constantly having to turn off these custom
fields on the table view so I can view the Check In, Duplicate, Edit and
the Delete button. So can we allow users to turn on and off custom
fields by checking a box. (Please see link below). I honestly think a lot
of people would like this feature. We have lots of custom fields that are
important but we DON'T need them all enabled on the assets table view by
default. What do you think?? Most of us will open the asset and view the
custom fields that way.  Please give us the option to turn these on or off.

https://files.kusdportal.com/drive/s/DrzTEr4fMhMQ3iBNjFWl9LaW26nkBk

Thank you,
Brian

**Comment by brianhoganm** [comment]
I figured it out. I did not realize that I can turn off my custom fields from automatically appearing in my asset table view. I just put **false** instead of true. I am so exited that I was able to do this. You guys, it was such as pain to always have to scroll to the right to view all of my custom fields or turn them off. I know I will have to change this to false every time I update - but I don't mind at all. I also went ahead and customized the default fields like enabling the Company to be visible at all times.

![False](https://user-images.githubusercontent.com/109772627/218199869-3b5b9179-c874-4c2d-b031-506ba158f065.JPG)

**Comment by snipe** [comment]
@brianhoganm I have a PR almost ready to go that makes this a customizable option (the username appending, not the column selectors)

You've also been around here for a while, so you can see that opening an issue with "No. I would like NOT to have" is kinda crap. 

I knew when I answered a different user's request by adding that that I'd piss off some other people. That's kinda how open source works, unfortunately. You do a Good Thing for one user and it always turns into a Bad Thing for someone else. And then you have to make a setting, and that also sucks.

**Comment by brianhoganm** [comment]
@snipe I apologies for my wording. I do not usually talk like like that.  I am sorry. I responded to the question No to **_Is your feature request related to a **problem**? Please describe._** because it wasn't a problem. It was more of a feature request/ or suggestion that I wanted to put out there. Since you are currently viewing this thread - I just wanted say thank you for all you do with improving and making SNIPE-IT. SNIPE-IT has helped me everyday with managing all of my assets. Yourself and your contributors do a fantastic job and I totally understand that you can't please everyone. I am always looking forward to your latest snipe-IT releases. Thank you. Brian

**Comment by snipe** [comment]
All good, @brianhoganm - I'll have the setting PR up before Monday. (It's a little tricky because we do the append via javascript, but we're getting the data from the API, and it's kinda gross to mix front-end and back-end, so a little harder than it seems. But we've got you.)
