### ISSUE TITLE
User unable to view their own history without global access to reports

### ISSUE THREAD

**Issue by RichScar** [grokability/snipe-it#12461]
### Debug mode

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Users with no permission to view reports cannot see their own asset history. When enabling the reports permission, they gain access to all reports across the site. Is there any inbetween

### Reproduction steps

1. Turn off group permission for 'Reports: View' to Deny
2. Add user to this group (and only this group)
3. Sign in as user

### Expected behavior

Some access to history involving themself, but no access to audit reports, deprecation reports, etc.

### Snipe-IT Version

Version v4.8.0 - build 4186

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.2.24-0ubuntu0.18.04.16

### Operating System

Windows

### Browser

MS Edge Chromium

### Version

Version 109.0.1518.61

### Additional context

Apologies if this question has been asked already, or if there is this functionality in a newer version!
Thanks

**Comment by snipe** [comment]
You're running a version that is many years old and is not maintained anymore. I'd suggest upgrading your Snipe-IT to latest.
