### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by reyunj** [grokability/snipe-it#12479]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When the user requested an asset server error will display.

### Reproduction steps

1.login user
2. go to requested button
3. an error will pop up.
...

### Expected behavior

even refresh the browser still 500 error display

### Snipe-IT Version

v6.0.14 build 9038

### Operating System

windows

### Web Server

Xampp

### PHP Version

8.0.25

### Operating System

windows

**Comment by inietov** [comment]
@reyunj Hello there!! You have any log to attach that could help us look into this issue?

**Comment by reyunj** [comment]
where to check the log files ?

**Comment by reyunj** [comment]
![Screenshot 2023-02-08 090444](https://user-images.githubusercontent.com/108446595/217402418-34fc79b0-acdc-44ae-99e1-d429302588d6.jpg)

**Comment by reyunj** [comment]
![image](https://user-images.githubusercontent.com/108446595/217404390-aa34660e-c179-48ef-bf51-45ce194ee2c2.png)

**Comment by reyunj** [comment]
![image](https://user-images.githubusercontent.com/108446595/217404427-8c1ff487-61fc-46ea-9a17-d70999d9ef6f.png)

**Comment by snipe** [comment]
Looks like your SMTP credentials are wrong. It's trying to send an email and it cannot. Check your email credentials in your .env.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
