### ISSUE TITLE
Microsoft SQL Server Support [Feature Request]:  

### ISSUE THREAD

**Issue by kheshwar-work** [grokability/snipe-it#12472]
### Is your feature request related to a problem? Please describe.

I would like to manage all my databases in Microsoft SQL rather than individual databases of mariaDB and MySql.

### Describe the solution you'd like

Would it be possible to have the application able to use Microsoft SQL server as a database server?

**Comment by snipe** [comment]
Unfortunately, that's not something we can support at this time.

**Comment by israelrbb** [comment]
I was able to get this going on Microsoft sql server 2019
