### ISSUE TITLE
Pre-Flight Database Error

### ISSUE THREAD

**Issue by larrygyamfi** [grokability/snipe-it#12487]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Im in the process of configuring SnipeIT. Im getting an error on the pre-flight page relating to the database configurations: 
"D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: could not find driver (SQL: select 2 + 2)". Ive tested my credentials using the MariaDB command prompt and i'm able to sign in correctly.

### Reproduction steps

1. Changing the password in for the DB_user and updating env file
2. Recreating the snipeit table and user
3. Resetting site in IIS

### Expected behavior

Ideally, the error should go away in the pre-flight check and i can continue to create the database tables step.

### Screenshots

![image](https://user-images.githubusercontent.com/53521137/217641528-1c2ccbb1-71b3-436b-aed5-bdc9297c0d78.png)

### Snipe-IT Version

v6.0.13

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

8.0.27

### Additional context

This is a fresh install
Im running this on Windows server 2019, IIS
I installed by using GIT
Followed the directions from site and  youtube video (https://www.youtube.com/watch?v=aZhYVksU0J0&t=522s). Did not receive any errors until i reached the pre-flight.

**Comment by marcusmoore** [comment]
Hi @larrygyamfi

It sounds like you might be missing the PDO extension mentioned in [requirements](https://snipe-it.readme.io/docs/requirements). Can you verify that you have that installed?

**Comment by larrygyamfi** [comment]
Yep, i was missing those add-ins. That did it, thank you!
