### ISSUE TITLE
Post /users to update user

### ISSUE THREAD

**Issue by eugene-bce** [grokability/snipe-it#12504]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am wanting to be able to use the /users endpoint to sync with a user management system.

Ideally, I would like to be able to post the same username and have it update any fields.

1st API Post:
Username: joeblogs
Title: Year 4

2nd API Post:
Username: joeblogs
Title: Year 5

Currently, it appears I need to know the ID of the user to be able to update details.

### Reproduction steps

1st API Post:
Username: joeblogs
Title: Year 4

2nd API Post:
Username: joeblogs
Title: Year 5

{"status":"error","messages":{"username":["The username must be unique."

### Expected behavior

Be able to update users without knowing their ID.

### Snipe-IT Version

  Version v6.0.14 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.2

**Comment by snipe** [comment]
You want a PATCH, not a POST. POST will try to create a new user.

https://snipe-it.readme.io/reference/users-3

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/users-3">/users/:id</a></strong></div><div>Partially update a user, passing only the fields you want to modify</div></blockquote>
