### ISSUE TITLE
500 | Server error after backup restored

### ISSUE THREAD

**Issue by ShamindraAd** [grokability/snipe-it#12500]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After I restore my snipe-it backup file from older version to new version.
following error occurs.

500 | Server error

### Reproduction steps

1.n
2.
3.
...

### Expected behavior

Need to run Snipe-it properly

### Snipe-IT Version

snipe-it-6.0.14

### Operating System

Windows

### Web Server

IIS

### PHP Version

php-8.1.13-nts

### Additional context

This is fresh install and backup is from older version[2023-02-10 12:22:48] production.ERROR: Your APP_URL in your .env is misconfigured - it is: cloud.avarna.com. Many things will work strangely unless you fix it.  
[2023-02-10 12:22:48] production.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'components_assets.note' in 'field list' in C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:368
Stack trace:
#0 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(368): PDO->prepare()
#1 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#3 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(376): Illuminate\Database\Connection->run()
#4 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2414): Illuminate\Database\Connection->select()
#5 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2402): Illuminate\Database\Query\Builder->runSelect()
#6 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2936): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2403): Illuminate\Database\Query\Builder->onceWithColumns()
#8 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(625): Illuminate\Database\Query\Builder->get()
#9 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsToMany.php(807): Illuminate\Database\Eloquent\Builder->getModels()
#10 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsToMany.php(786): Illuminate\Database\Eloquent\Relations\BelongsToMany->get()
#11 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(553): Illuminate\Database\Eloquent\Relations\BelongsToMany->getResults()
#12 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(491): Illuminate\Database\Eloquent\Model->getRelationshipFromMethod()
#13 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(440): Illuminate\Database\Eloquent\Model->getRelationValue()
#14 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2029): Illuminate\Database\Eloquent\Model->getAttribute()
#15 C:\inetpub\wwwroot\Snipe-it\app\Models\Component.php(193): Illuminate\Database\Eloquent\Model->__get()
#16 C:\inetpub\wwwroot\Snipe-it\app\Models\Component.php(209): App\Models\Component->numCheckedOut()
#17 C:\inetpub\wwwroot\Snipe-it\app\Helpers\Helper.php(672): App\Models\Component->numRemaining()
#18 C:\inetpub\wwwroot\Snipe-it\storage\framework\views\47f07d25582bffce73eb879c696d0ad7d55bfc34.php(266): App\Helpers\Helper::checkLowInventory()
#19 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(107): require('...')
#20 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#21 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#22 C:\inetpub\wwwroot\Snipe-it\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(69): Illuminate\View\Engines\PhpEngine->evaluatePath()
#23 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(61): Livewire\CompilerEngineForIgnition->evaluatePath()
#24 C:\inetpub\wwwroot\Snipe-it\vendor\facade\ignition\src\Views\Engines\CompilerEngine.php(37): Illuminate\View\Engines\CompilerEngine->get()
#25 C:\inetpub\wwwroot\Snipe-it\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(35): Facade\Ignition\Views\Engines\CompilerEngine->get()
#26 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(139): Livewire\CompilerEngineForIgnition->get()
#27 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(122): Illuminate\View\View->getContents()
#28 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#29 C:\inetpub\wwwroot\Snipe-it\storage\framework\views\d0a5c1b5ebece2013fb38d8360be3f52f4cd308c.php(477): Illuminate\View\View->render()
#30 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(107): require('...')
#31 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#32 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#33 C:\inetpub\wwwroot\Snipe-it\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(69): Illuminate\View\Engines\PhpEngine->evaluatePath()
#34 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(61): Livewire\CompilerEngineForIgnition->evaluatePath()
#35 C:\inetpub\wwwroot\Snipe-it\vendor\facade\ignition\src\Views\Engines\CompilerEngine.php(37): Illuminate\View\Engines\CompilerEngine->get()
#36 C:\inetpub\wwwroot\Snipe-it\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(35): Facade\Ignition\Views\Engines\CompilerEngine->get()
#37 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(139): Livewire\CompilerEngineForIgnition->get()
#38 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(122): Illuminate\View\View->getContents()
#39 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#40 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Http\Response.php(69): Illuminate\View\View->render()
#41 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Http\Response.php(35): Illuminate\Http\Response->setContent()
#42 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(820): Illuminate\Http\Response->__construct()
#43 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(789): Illuminate\Routing\Router::toResponse()
#44 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(721): Illuminate\Routing\Router->prepareResponse()
#45 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#46 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle()
#48 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle()
#50 C:\inetpub\wwwroot\Snipe-it\app\Http\Middleware\AssetCountForSidebar.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\AssetCountForSidebar->handle()
#52 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#54 C:\inetpub\wwwroot\Snipe-it\app\Http\Middleware\CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle()
#56 C:\inetpub\wwwroot\Snipe-it\app\Http\Middleware\CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckUserIsActivated->handle()
#58 C:\inetpub\wwwroot\Snipe-it\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckLocale->handle()
#60 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#62 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#64 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#65 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#66 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(723): Illuminate\Pipeline\Pipeline->then()
#68 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(698): Illuminate\Routing\Router->runRouteWithinStack()
#69 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router->runRoute()
#70 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(651): Illuminate\Routing\Router->dispatchToRoute()
#71 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch()
#72 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#73 C:\inetpub\wwwroot\Snipe-it\vendor\livewire\livewire\src\DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#74 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Livewire\DisableBrowserCache->handle()
#75 C:\inetpub\wwwroot\Snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#76 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#77 C:\inetpub\wwwroot\Snipe-it\vendor\fruitcake\laravel-cors\src\HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#78 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#79 C:\inetpub\wwwroot\Snipe-it\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#80 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle()
#81 C:\inetpub\wwwroot\Snipe-it\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#82 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle()
#83 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#84 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#85 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#86 C:\inetpub\wwwroot\Snipe-it\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#87 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle()
#88 C:\inetpub\wwwroot\Snipe-it\app\Http\Middleware\CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#89 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle()
#90 C:\inetpub\wwwroot\Snipe-it\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#91 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#92 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#93 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#94 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#95 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#96 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#97 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#98 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#99 C:\inetpub\wwwroot\Snipe-it\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#100 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle()
#101 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#102 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#103 C:\inetpub\wwwroot\Snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#104 C:\inetpub\wwwroot\Snipe-it\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#105 {main}

**Comment by snipe** [comment]
> This is fresh install and backup is from older version[2023-02-10 12:22:48] production.ERROR: Your APP_URL in your .env is misconfigured - it is: cloud.avarna.com

You should definitely fix this, per the warning. 

The 500 is coming from a missing column. You likely need to run database migrations: `php artisan migrate`
