### ISSUE TITLE
v6.0.14 - Asset Checkout via API removes asset name if one is not provided

### ISSUE THREAD

**Issue by ntbutler-nbcs** [grokability/snipe-it#12503]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Previously, when checking out an asset via the /api/v1/hardware/<id>/checkout endpoint, we would provide "checkout_to_type" = "user", "assigned_user" = <user_id>, and expected_checkin = <date>.
Since upgrading to 6.0.14 at the end of last week, we noticed that assets that are checked out via this same API process have had the asset name removed.

I noticed a commit [181f96a] on app/Models/Asset.php which was designed to allow users to set a blank asset name on checkout. However, if the name parameter isn't sent at all, it is still resulting in the name value being wiped.

### Reproduction steps

1. Set up an asset with a device name
2. Check out an asset via the /api/v1/assets/<ID>/checkout endpoint - do not add a "name" attribute to the POST request
3. Check the asset in Snipe-IT - name will be removed

### Expected behavior

The name should only be reset if a blank name is specified in the API request

### Snipe-IT Version

6.0.14

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1

**Comment by marcusmoore** [comment]
Thanks for reporting this @ntbutler-nbcs. I'll be checking it out and will hopefully have a fix soon.

**Comment by snipe** [comment]
This is merged to master
