### ISSUE TITLE
LDAP Issue Correction (Admin Error, NOT a bug)

### ISSUE THREAD

**Issue by tzielinskiaptn** [grokability/snipe-it#12501]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I originally setup my LDAP sync with my AD, I used the mail field for my Username field, which created user objects with their email addresses as the usernames.

When I run an LDAP sync, I noticed that the passwords were not being updated for the users.

After some reading I realized that I should have used samaccountname instead of mail for the username field.

So I made that change, and ran an LDAP sync which generated new users with the samaccountnames as usernames, and also assigned correct passwords.

My issue is that all my assets are currently assigned to the email user objects. I also have a couple of local accounts I created manually with email address usernames that I can't change the passwords on with the admin console because of the LDAP sync.

So I am looking for some guidance on the simplest way to get my assets re-assigned to the samaccount name user objects (Is there a bulk tool I can use somewhere in the GUI, or a script I could run) and then I'll purge the duplicate accounts and make sure I assign the correct memberships and groups to the new objects before I delete anything.

### Reproduction steps

1. N/A
2.
3.
...

### Expected behavior

This doesn't apply either, the system behaves as expected, it was my error.

### Snipe-IT Version

6.0.13

### Operating System

Windows Server 2022

### Web Server

IIS

### PHP Version

7.4.33

### Operating System

Win 11

### Browser

Edge

**Comment by Godmartinz** [comment]
Hi @tzielinskiaptn,
We do have a command line utility that I think may help you mentioned in the [documentation](https://snipe-it.readme.io/docs/merging-users)

Let me know if this helps 🙂

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
