### ISSUE TITLE
[Feature Request]: Clone Accessories

### ISSUE THREAD

**Issue by clpStephen** [grokability/snipe-it#12512]
### Is your feature request related to a problem? Please describe.

I can't find an option to clone accessories. This would bne useful as I see that Snipe is reluctant to add "Check Out to Location" as a feature. For example, I have an HDMI to Mini Display adapter that I am going to put into a vide editing bay at my company. It's there semi-permanently. I have another one in my Tech room. They were bought on the same receipt which I attach to the item. Simpyl checking it out to that location would be covenient but in the absence of that feature being able to dupe the item and change the location is the best workaround.

### Describe the solution you'd like

Make Accessories and probably everything else cloneable.

### Describe alternatives you've considered

I initially thought that checking them out to a location would be a simple solution but I snipe's responses to previous requests for this so I'm abandoning that tact. Sorry if this was also already requested.

**Comment by clpStephen** [comment]
Another solution might be the ability to have separate lines for quantities so that I can assign different locations to each quantity. For instance, 5 assigned to Studio 1, 7 to Studio 3, etc.

**Comment by akemidx** [comment]
completed in https://github.com/snipe/snipe-it/pull/12680
