### ISSUE TITLE
Location API - Country, State and Currency being ignored.

### ISSUE THREAD

**Issue by ShaunNeighbourSwale** [grokability/snipe-it#12528]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Following the documentation from https://snipe-it.readme.io/reference/locations-2 I can create locations.  However, the Country, State and Currency fields are ignored.

I've used the exact values already set on existing locations.  The API responds with a status 200/success.

### Reproduction steps

1. Lookup existing location using the API
2. Use API reported values to create a new location using the same country and currency values
3. Lookup new location in API - country, state and currency values are missing.
...

### Expected behavior

For these values to be set during creation.

### Snipe-IT Version

6.0.11

### Operating System

Hosted

### Web Server

Hosted

### PHP Version

Hosted

**Comment by itakestime** [comment]
I would suggest you upgrade to a newer version if you could.
Testing on the API docs page you linked to, I have managed to fill in all the fields and it has accepted & stored the data so doesn't appear to be an issue on v6.0.14

**Comment by ShaunNeighbourSwale** [comment]
> I would suggest you upgrade to a newer version if you could. Testing on the API docs page you linked to, I have managed to fill in all the fields and it has accepted & stored the data so doesn't appear to be an issue on v6.0.14

Same issue after upgrading to 6.0.14

Would you be able to share the value you used?  I'm wondering if it's validating these fields, but is only allowing for US values......

**Comment by ShaunNeighbourSwale** [comment]
PEBKAC - Was using "Currency" instead of "currency"

**Comment by itakestime** [comment]
Easy fix :wink: 
We all do it haha
