### ISSUE TITLE
[Feature Request]: Get version programmatically

### ISSUE THREAD

**Issue by AndrewSav** [grokability/snipe-it#12532]
### Is your feature request related to a problem? Please describe.

I would like to be able to keep track of the currently installed snipe-it version programmatically. I have an utility that I've written that notifies me when any of the web application I'm running has a newer version available (e.g. from github or docker hub). It does this by querying the particular application's API. Most software provide an API to get the currently running version. Some software return the version in a response header.

I was not able to find a way to get this information from snipe-it (short of simulating a user login and then parsing HTML page).

### Describe the solution you'd like

Either:

- provide an API that returns current version; or
- return current version in each response header, for example in the [Server header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server)
- other means suitable for programmatic use

### Describe alternatives you've considered

Simulate user logging in using http requests and then parse html to get the version from the footer.

**Comment by MoralCode** [comment]
this might also be useful for various API wrappers to do version/feature detection to tell their users things like "hey this api feature you are trying to use doesnt exist in this version, update your snipe-it"

could be useful and potentially doable either by adding a `meta` or `version` attribute to each response (in addition to count and data) or with a new `/version` endpoint
