### ISSUE TITLE
Expected Checkin Date on Asset Checkout throws an error in Docker image

### ISSUE THREAD

**Issue by newburns** [grokability/snipe-it#12531]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am using the snipe/snipe-it Docker
When checking out an asset, if I put the expected checkin date, an error is given
` Error Asset was not checked out, please try again{"expected_checkin":["The expected checkin must be a valid date in YYYY-MM-DD format"]}`

### Reproduction steps

1. Checkout a Ready to Deploy Asset
2. Add expected checkin date
3. Press Checkout to complete checkout
...

### Expected behavior

Checkout process should continue with a successful message and emails sent

### Screenshots

![image](https://user-images.githubusercontent.com/5234107/219482772-0d410416-89e3-4c3b-bd3a-896c004ff4d1.png)

### Snipe-IT Version

6.0.14 - Build 9236

### Operating System

Debian 11 - Docker

### Web Server

Apache?

### PHP Version

PHP Version 7.4.3-4ubuntu2.17  |  Laravel Version 8.83.22

### Operating System

Windows

### Browser

Edge

### Error messages

```shell
Error is reproduced in the demo at snipeitapp.com/demo
```

**Comment by snipe** [comment]
Fixed on master
