### ISSUE TITLE
Ability to add New User without login ability NOR the need for login credentials

### ISSUE THREAD

**Issue by code-goat** [grokability/snipe-it#12534]
### Is your feature request related to a problem? Please describe.

My problem revolves around the situation when I'm checking out/in assets during our large inter-organizational events where we have many temporary users; none of whom will ever need to login to our asset server. As the feature stands currently. I can add a new user while checking out any particular asset, BUT I'm required to submit a password and username for that new user. I cannot add new users that don't have login ability from this menu. Perhaps there is a setting or workaround for this that I haven't found yet.

### Describe the solution you'd like

I would like to be able to add a new user without login capabilities from an asset page while "checking out/in". I DO NOT need certain users to have a username or password or login function, etc.

### Describe alternatives you've considered

I have been able to add a list of users from a CSV file through the import that don't require a login, password, or username. However, I need this ability to add users without credentials to be accessible on-the-fly while scanning barcoded assets out/in.

**Comment by aquadiode** [comment]
Which version of Snipe-IT are you using?  Username would be required but login enabled (checkbox) I'm pretty sure was added in new user modal popup in V6.0.0 #10421.  You can generate a random password and uncheck the login enabled box so the user will be valid but not be able to login.

**Comment by snipe** [comment]
Disabling login is already built in, as @aquadiode mentioned, but username is always required, and I don't see that changing any time soon. That said, you can just randomly generate them if the user is never going to login
