### ISSUE TITLE
Setup page redirected to Localhost

### ISSUE THREAD

**Issue by sangdrax8** [grokability/snipe-it#12546]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

While trying to test on a VirtualBox VM on my own machine, I keep getting redirected to localhost/setup, which causes the request to fail to even go to my test VM.  I have seen this reported before, but others have noted that they didn't set the APP_URL, or that they had an .htaccess file edit, or even that mod-rewrite wasn't enabled.  I have checked all these things and they seem to be working to me.

### Reproduction steps

1. Clone snipe-it to /var/www/html/snipe-it
2. Configure .env
3. Setup Database
4. Setup Apache 
5. Access Website, get redirected to localhost/setup
...

### Expected behavior

Reach the setup page.

### Snipe-IT Version

latest

### Operating System

Ubuntu 20LTS

### Web Server

Apache2

### PHP Version

7.4

### Operating System

Ubuntu

### Browser

Chrome

### Version

20LTS

### Error messages

```shell
I do not get any logs in the debug log, I presume because the redirect sends my request away from the VM and therefore doesn't generate any logs.
```

### Additional context

I am trying to access the host via an RFC IP, however I have tested by setting a hosts file on my client to "snipe.testing" and changing my APP_URL to this as well (as well as apache server name).  In both cases, I clearly reach the server, and then get re-written to localhost/setup which then fails.

**Comment by snipe** [comment]
What do you have set as your `APP_URL`?

**Comment by sangdrax8** [comment]
I have tried a few settings:

1. Setting app_url to the IP address I will be using with http://192.168.56.XX 
2. Setting app_url based on the hostname of the box with http://assets.  I then set my client hosts file to provide the "assets" host with the IP address of my test VM.
3. Setting app_url to a random name for testing with: http://snipe.example.  I then set my client hosts f ile to provide the "snipe.exmaple" with the IP address of the server.

In know apache finds the virtual host because in both cases with the host in the hosts file, I can use the IP address and reach the VM, but I get the default apache page as this doesn't match the snipe virtual host.  Once I use the name, I end up getting redirected to the localhost/setup which is where I get stuck.

**Comment by sangdrax8** [comment]
Well, I have come back to this to see if I could help run it down.  I noticed there was an ansible folder in the repo, and a play expected to be run by vagrant there.  I had to make some modifications to make this fully run, but once I got it working it ends up doing the same thing I have been seeing with the ansible role I was working on.  The setup redirects back to localhost/setup which then prevents further setup.

I'll keep looking around, but any assistance on where to look would be appreciated.  Not sure how this URL gets changed.

**Comment by sangdrax8** [comment]
I think I have found my issue.  It seems the .env file was copied, but the permissions were not set on it.  Therefore this file contained all the correct settings, but was not being used.  I am going to fix this in my ansible and rebuild from scratch, but I fully expect this to be confirmed fully working now.

**Comment by snipe** [comment]
Awesome, thanks for the update!
