### ISSUE TITLE
Cloning a model blanks fieldset of new model

### ISSUE THREAD

**Issue by sjwk** [grokability/snipe-it#12548]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When cloning a model that has a fieldset attached, the new model has 'No custom fields' as fieldset.

### Reproduction steps

1. Create model with fieldset
2. Clone model to new model

### Expected behavior

A cloned model type to have the same fieldset as the model it was cloned from

### Snipe-IT Version

6.0.14 (latest tag on docker hub)

### Operating System

Docker on Ubuntu 22.04

### Web Server

from docker container

### PHP Version

from docker container

### Additional context

Installed from docker container.
Pretty vanilla so far, just setting up custom fields and models before populating with any data.

**Comment by inietov** [comment]
@sjwk Hello there! The fieldset does not get assigned automatically but user can select one from the `Fieldset` select list. I can see how one could expect that the field got filled automatically. Just FYI as a workaround.
