### ISSUE TITLE
Unable to import `Purchase Date` field

### ISSUE THREAD

**Issue by ptitiano** [grokability/snipe-it#12559]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am transitioning our Asset Management to Snipe-IT from another solution, so I am using the CSV import functionality to populate the Snipe-IT database with our data.
Everything works great, except with one field, the standard `Purchase Date` field.
The CSV importer keeps reporting this error: `Asset "": The purchase date must be a valid date in YYYY-MM-DD format` whatever I tried.

This is the most simple CSV file I am trying to import (I tried with different others also):
[sample_purchase_date_test_file.csv](https://github.com/snipe/snipe-it/files/10823363/sample_purchase_date_test_file.csv)
```
Category,Manufacturer,Asset Tag,Model name,Purchase Year,Purchase Date
Laptops,Lenovo,BL-10001,Thinkpad L540,2013,2013-11-01
```

I captured the 2 screenshots provided below. You may observe that the `Purchase Date` field is correctly found in the first capture.

### Reproduction steps

1. Go to the `Import` page
2. Click on `Select File...`
3. Select the file attached in this ticket (`sample_purchase_date_test_file.csv`)
4. Once the file is important, click on the `blue button` next to the file name
5. Select `Assets` as `Import Type`
6. Check `Update Existing Values?:` (the asset already exists in my case)
7. Click on the `Import` button
8. The error message is returned.

### Expected behavior

I would expect the `Purchase Date` field to be updated without error, since the format is valid.

### Screenshots

![screenshot_1_csv_import](https://user-images.githubusercontent.com/2389086/221162761-9d1f26a2-bf9a-403a-a45e-65fed16d184b.png)
![screenshot_2_csv_import_error](https://user-images.githubusercontent.com/2389086/221162813-bd73950d-322f-4ba5-a804-2c432c658fce.png)

### Snipe-IT Version

v6.0.14 build 9236 (g05a3f20d5) (hosted)

### Operating System

Not Applicable (hosted)

### Web Server

Not Applicable (hosted)

### PHP Version

8.0.27

### Operating System

MacOS

### Browser

Google Chrome

### Version

109.0.5414.119 (Build officiel) (x86_64)

### Device

Not Applicable

### Operating System

Not Applicable

### Browser

Not Applicable

### Version

Not Applicable

**Comment by Codymullis** [comment]
We also ran into this same issue yesterday.  We tried to proceed with an import without uploading the Purchase Date and then also found if we checkout an asset to someone in the import then it blanks the Asset Name field.   Only assets with names are the ones not assigned to someone in the csv.  So there is a lot of issue with the import function currently.

**Comment by ptitiano** [comment]
Thanks for quickly fixing this bug! 👍
