### ISSUE TITLE
Installation results in Error 500

### ISSUE THREAD

**Issue by TimoReinhardt** [grokability/snipe-it#12568]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Fresh Install on RasperryPi 4 with 4GB running Raspbian 11

I've tried to install SnipeIT multiple times with the installer, every time on a fresh installation of the OS.
It either results in Error 500 or the blank php-code shown in the browser.

### Reproduction steps

1. Download and execute the installer (Via the command provided in the documentation)
2. Enter the informations requested by the installer
3. open localhost/ and get Error 500

### Expected behavior

I've expected that the pre-Flight Setup shows up

### Snipe-IT Version

latest

### Operating System

Raspberrian 11

### Web Server

Apache2

### PHP Version

I don't know, what the installer tries to install

**Comment by ccj9874** [comment]
You should be able to enable debug in the .env file and get more info on the error

**Comment by TimoReinhardt** [comment]
Thanks. I already solved it.
