### ISSUE TITLE
'Dashboard' navigation menu not active

### ISSUE THREAD

**Issue by sdk1-kod** [grokability/snipe-it#12571]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The 'Dashboard' link on the left side navigation menu breaks/deactivates when page is small.
-normally 'Dashboard' or all other links are active when hovering over with cursor. This is not the case for the 'Dashboard' link on the left navigation menu.

### Reproduction steps

1. Login, and maximize the home page.
- noticed how hovering over the 'Dashboard' navigation menu on the left. The cursors change and you are able to click on the 'Dashboard' menu link itself.

2. Now, restore down / unmaximize the page and resize it to something smaller.
- notice how the cursor is no longer activated by hovering over the 'Dashboard' navigation menu and you are no longer able to click on the 'Dashboard' link itself.

### Expected behavior

The 'Dashboard' navigation menu link works no matter the page size.

### Screenshots

![maximized](https://user-images.githubusercontent.com/96728533/221651026-bd06c7a6-2039-43e0-b451-fb16a1ebc580.png)
![smaller_page_size](https://user-images.githubusercontent.com/96728533/221651042-53884297-64f6-4ca8-99b3-f7cc19ca1eab.png)

### Snipe-IT Version

v6.0.14 build 9038 (g163b3f6c0)

### Operating System

Linux 5.19.17-Unraid x86_64

### Web Server

Apache

### PHP Version

8.1.16

### Operating System

Windwos 10/11

### Browser

Chrome

### Version

110.0.5481.177

### Error messages

```shell
n/a
```

### Additional context

noticed this while moving page from a portrait mode screen, to a non portrait mode screen. 
After moving the window from one screen to another the problem would go away once page was fully maximized.

**Comment by snipe** [comment]
I can't reproduce this, but we'll have @Godmartinz take a look when he gets a chance. (In the meantime, you can click on the  logo at the top to get back to the dashboard)

**Comment by sdk1-kod** [comment]
> I can't reproduce this, but we'll have @Godmartinz take a look when he gets a chance. (In the meantime, you can click on the logo at the top to get back to the dashboard)

yes, the logo works as intended. if you can't reproduce this by resizing the page try going a bit more narrow on the page size.
I can reproduce this on multiple machines, and different users as well.

**Comment by sdk1-kod** [comment]
I was also able to reproduce it on your demo site
different browser as well.
![demosite1](https://user-images.githubusercontent.com/96728533/221689139-71222cdb-d2bc-4757-bfcf-8521d967c63c.png)
![demosite2](https://user-images.githubusercontent.com/96728533/221689147-1e996bf6-4a26-4778-9dde-90a68a0c17af.png)

**Comment by hjertis** [comment]
I was able to reproduce it as well on my installation.

It seems the header tag resizes and covers up the Dashboard link.

**Comment by Godmartinz** [comment]
thanks for bringing this to our attention. I can reproduce it too. I'm going to get a fix out asap.

**Comment by sdk1-kod** [comment]
> thanks for bringing this to our attention. I can reproduce it too. I'm going to get a fix out asap.

Awesome, thank you!
