### ISSUE TITLE
Create New User - Error in Start Date - The Start Date must be a valid date 

### ISSUE THREAD

**Issue by beemestd** [grokability/snipe-it#12594]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

While we are trying to create a new user details and click the Start Date, and click save , it prompt this error message: "The start date must be a valid date in YYYY-MM-DD format" 

### Reproduction steps

1. Create a new user 
2. Fill in the details.
3.Click the start date 
4. Click Save
5. Error message pop up: The start date must be a valid date in YYYY-MM-DD format.

### Expected behavior

As expected like in Demo portal, can add user with start date details.

### Screenshots

![Screenshot 2023-03-02](https://user-images.githubusercontent.com/26455335/222345325-c4c8da74-d7f2-4414-adee-91dc2a5ed2ca.png)

### Snipe-IT Version

6.0.14

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.33

### Additional context

This is upgraded from V 5.0.12
Windows Server 2019
Upgrade using php upgrade.php

**Comment by snipe** [comment]
This is already fixed on master.

**Comment by beemestd** [comment]
Hi Snipe, 
Thanks, it works now.. just realized the activity report date become today's date , do i need to open a new ticket?
![Screenshot 2023-03-03](https://user-images.githubusercontent.com/26455335/222662424-bd7fe7bf-05ac-43cc-a60f-5dc78beca87b.png)
