### ISSUE TITLE
Unable to check-in licenses via web UI, can do via API

### ISSUE THREAD

**Issue by bmacphail** [grokability/snipe-it#12609]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We updated Snipe from an older v4-era version a few days ago, with upgrade.php. Things were working fine post-upgrade until today, when we found that we were suddenly unable to check-in license seats via the Web UI. When we try, we get a generic error:

<img width="667" alt="Screenshot 2023-03-03 at 2 35 54 PM" src="https://user-images.githubusercontent.com/12399661/222844632-7d0b7f11-6c9d-4fdc-8c68-b345c05d05a5.png">

Checking *out* license seats works fine. Checking *in* license seats via the API works fine. It's only when checking *in* license seats *via the Web UI* that we get this error.

### Reproduction steps

1. Check out a license seat to a user.
2. Try to check in that same license seat.
3. Get the error message in the image above.
...

### Expected behavior

Usually, a green "check-in successful" will appear in place of the error.

### Screenshots

See above.

### Snipe-IT Version

6.0.14, just updated as of posting

### Operating System

Debian

### Web Server

Apache

### PHP Version

7.4.33

### Operating System

macOS

### Browser

Chrome, Safari, Firefox

### Version

n/a

### Error messages

```shell
We have debug turned on, but not getting any useful error messages in the web interface. 

No errors in the browser console.

No errors found in Apache's log. Nothing in Laravel's log. 

Here's our output from php -m:

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

### Additional context

During the upgrade, we did have to follow the steps mentioned in this issue to convert the row format to dynamic in a few of our tables: https://github.com/snipe/snipe-it/issues/8971

We also had to update Debian, Composer, php, and Apache during our upgrade.

**Comment by inietov** [comment]
Thanks for your report, this issue was already fixed in https://github.com/snipe/snipe-it/pull/12602. Sorry for the inconveniences!

**Comment by bmacphail** [comment]
Thank you!!
