### ISSUE TITLE
[Feature Request]: Add current date to user print all assigned view

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#12607]
### Is your feature request related to a problem? Please describe.

Currently, the print page when you click the `Print All Assigned` Button on the user view don't give any hint on when this print was generated.
I would like to see, when I printed this view.

### Describe the solution you'd like

I use the print view to export a PDF document of all assigned items of the user to have a "physical" copy of this state, when the user leaves the company. But when I export multiple views of this user (like one today and another tomorrow), I can not see, which one was created first (except from the file date attribute).

I would like to have the date stamp on two things:
1. On the page title → so my printed PDFs have a different file name with a date stamp, since a print to PDF uses the page title as the default file name.
2. On the page itself → so besides the file name, there is an "unchangeable" text in the document itself that indicates, when this document was created.

### Additional context

Current page title (without date indicator):
![image](https://user-images.githubusercontent.com/112496896/222730106-26fc8b72-ed8e-4dc1-a9a3-7ddb2ce90312.png)

Suggestion for the date stamp on the page itself:
![image](https://user-images.githubusercontent.com/112496896/222730732-337f6474-2a3e-45bb-93cb-16c3b3d65087.png)

**Comment by snipe** [comment]
This is typically a printer setting, not so much a Snipe-IT setting, where you can have your printer print the current date in the printout. I suppose we could add a "Printed date" to the page itself, but it could end up being inaccurate. If you click on "print all assigned" and then leave work for the day, the one we come up with won't be accurate anymore (since it will have been from the day before), while the one your printer generates will be more accurate.

**Comment by akemidx** [comment]
Hi, that is that a live Acrobat key?

**Comment by floschoepfer** [comment]
> Hi, that is that a live Acrobat key?

No, it's from the [live demo](https://demo.snipeitapp.com)

**Comment by floschoepfer** [comment]
> If you click on "print all assigned" and then leave work for the day, the one we come up with won't be accurate anymore (since it will have been from the day before)

I see what you mean, but I think about it as a "generated at" date and not a "printed at" date. Because when we take your example, the date would be accurate because the view was generated the day before and because of that the date would be correct. Because if we would like check-in an asset later that day, the print view would not be updated and the checked-in asset would still be listed so the date, when this view was created would be the correct date, because this view represents the state of this specific date and time. And if you would recreate the print view, the checked-in asset would not be listed and a new date would be generated. Do you understand what I mean?

**Comment by akemidx** [comment]
I understand the difference we are going for. The form is the source of truth for the day it was generated, no matter what day it actually gets printed out.

Apologies for having this elsewhere, but this has been opened today in #12636
