### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by kkailll** [grokability/snipe-it#12614]
### Is your feature request related to a problem? Please describe.

1、Send notification emails when users change assets, allowing administrators to quickly confirm changed items
2、When creating an asset, the historical record can display the custom field (cost unit) at the time of creation

### Describe the solution you'd like

1、Quick confirmation of change information
2、Quick confirmation of original cost unit

### Describe alternatives you've considered

none

**Comment by snipe** [comment]
Not sure what you mean by "change assets"? An asset would have to be checked in and a new one checked out, and we already send emails on those if the category setting is set to do so.

**Comment by kkailll** [comment]
Refers to every asset update, I hope the administrator can be notified by letter to facilitate confirmation

**Comment by snipe** [comment]
Asset update, or checkin and checkout? We already have checkin and checkout emails.

**Comment by kkailll** [comment]
Asset update, for example, because the client’s business transaction equipment is sold to other companies, at this time there will be a change in the cost unit of the custom field, but this change does not pass through checkout or checkin

**Comment by snipe** [comment]
This is planned for v7 as we redo the notification systems.
