### ISSUE TITLE
Activity Report recorded incorrectly

### ISSUE THREAD

**Issue by beemestd** [grokability/snipe-it#12615]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgraded to v.6, the activity report display the record incorrectly. 
![Screenshot 2023-03-06 113636](https://user-images.githubusercontent.com/26455335/223014272-8eafe7c0-8c0f-4519-9f79-cc4217c81776.png)

### Reproduction steps

1. Upgraded from v.5 to V.6 
2. Do php upgrade.php 

### Expected behavior

The Activity Report should replicated from the older version. 

### Snipe-IT Version

6.0.14

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.33

**Comment by Godmartinz** [comment]
May I ask you to elaborate on what it is you are showing us in this picture? It looks like a bunch of updates but its supposed to be...what? I'm not sure whats incorrect with the information given.

**Comment by beemestd** [comment]
From V5.0.12 the last activity report is 111 pages. 
![v5012_activity_report_1](https://user-images.githubusercontent.com/26455335/223309548-4bcad61d-ede2-4810-8dff-8fb64f03a1e1.png)

after upgraded to V6.0.14 the activity report has additional 10 pages which is display like this: 
![v6014_activity_report_1](https://user-images.githubusercontent.com/26455335/223309557-89c163d6-c17d-449f-a3a5-45cc3d06d8e0.png)
the additional 10 pages will display same timing and same date..

**Comment by snipe** [comment]
The activity report works as expected in 6.0.14 as far as I know. It's possible we corrected something since then which makes it look broken, but without specific info as to what might be missing, I'm not sure where to take this.

**Comment by beemestd** [comment]
Is there any way to delete the additional 10 pages?

**Comment by snipe** [comment]
There shouldn't be anything to delete - that's your actual history - you want to keep that.

**Comment by yusuf-basith** [comment]
I also faced the same issue.
After digging a bit deeper I found that during the time of upgrade, a huge number (based on the number of assets) of Activity is recorded.
After checking the changed column, I understood that the Asset EOL Date field has been recalculated and this has triggered the activity report.
