### ISSUE TITLE
Dashboard Categories Counts do not reflect Archived Assets (Count does not go down on dashboard) 

### ISSUE THREAD

**Issue by Mulder0571** [grokability/snipe-it#12635]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When archiving an asset (Mobile Devices is the one I am working with) They do remove them from the asset category, and when you click the link to drill down to the asset category it shows the correct number; however, the dashboard "Asset Categories" never reflects the new number minus the archived assets.  The screen shots tell the story.  

### Reproduction steps

1. We start with (1044) total and (232) in the Mobile Device Category: 
2. I archive two Mobile Devices, It adjust the number for the overall Total on the top left box on the dashboard to (1042), but not the Asset Category on the dashboard as it is still showing (232),
3.  BUT when  I click the Asset Category link the number is correct~shows the number minus the archived assets (230).  ...
4. I have refreshed the page, 
logged in and back out
have waited overnight for this to update and still no good.  
The box for "show archived assets..." on the general settings page is not checked.  

### Expected behavior

When I archive an asset, It should remove the 'number' from every total, not just when you drill down into the category.  

### Screenshots

![image](https://user-images.githubusercontent.com/127343954/223825852-ba8562d4-a297-4f7f-9c98-c55ae47b330f.png)

### Snipe-IT Version

 Version v6.0.11 - build 8758

### Operating System

MacOS and Windows

### Web Server

IIS

### PHP Version

Unknown

### Operating System

Windows, MacOS

### Browser

Google, Safari

**Comment by snipe** [comment]
I can confirm this behavior - looking into it now. Thanks for the heads up!

**Comment by snipe** [comment]
PR is up, just needs approval

**Comment by Mulder0571** [comment]
Thank you! You all are quick :)
________________________________
