### ISSUE TITLE
Incorrect language switching

### ISSUE THREAD

**Issue by MikServ** [grokability/snipe-it#12655]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Incorrect switching language.

### Reproduction steps

We have CentOS 9, Apache v.  2.4.53, Snipe-IT v. 6.0.14 wich was intalled with script.
After that i switched language in env file and in users profile from English to Russian. I noticed the following error:
On the main page sections of Assets,  Accessories, License and Consumable display correctly in Russian, but if i want to create Categories in section "Type of Categories" I see that the specified categories are not translated into Russian.

### Expected behavior

What i should do to fix that proplem?

### Screenshots

![Screenshot_20230312_133619](https://user-images.githubusercontent.com/125991883/224539400-6454533b-b6cd-42d6-ad59-3e6c5faf6507.jpg)
![Screenshot_20230312_133640](https://user-images.githubusercontent.com/125991883/224539408-77d6272d-e9fc-418e-8000-9e1f5fe5f2b7.jpg)
![Screenshot_20230312_133647](https://user-images.githubusercontent.com/125991883/224539413-9ca0c5ce-7d88-4cf1-bb06-92f2de9d5bdf.jpg)

### Snipe-IT Version

6.0.14

### Operating System

CentOS

### Web Server

Apache

### PHP Version

8.0.20

**Comment by Godmartinz** [comment]
Thanks @MikServ, good catch! I've submitted a PR to get the localization corrected for you.

**Comment by MikServ** [comment]
@Godmartinz Thanks for answers. How can i track fixes?

**Comment by Godmartinz** [comment]
There is a link above my last comment to the fix, should be merged into develop shortly. Check back here soon.

**Comment by MikServ** [comment]
@Godmartinz Thank you, i`ll follow.
