### ISSUE TITLE
Unable to add dates to an “Employee” profile

### ISSUE THREAD

**Issue by bslatyer** [grokability/snipe-it#12676]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When attempting to add an end or start date to an employee profile in Snipe - it will error out saying that the date isn’t valid.

### Reproduction steps

1. Select / Enter a date in the start or end date of an employee with the format YYYY-MM-DD
2. Attempt to save the item
3. Unable to save due to the dates being invalid

### Expected behavior

The date entered or picked should be valid as it’s in the correct format YYYY-MM-DD

### Snipe-IT Version

6.0.14

### Operating System

Hosted by Snipe-IT

### Web Server

Hosted by Snipe-IT

### PHP Version

Hosted by Snipe-IT

### Operating System

macOS 13.2.1

### Browser

Safari, Edge and Arc

### Version

16.x and 111.x

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Version

N/A

**Comment by snipe** [comment]
Please update to latest on master. This issue was fixed already.
