### ISSUE TITLE
Deleted Assets still listed in Asset Manufacturers 

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#12698]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Deleted Assets still show listed in Manufacturer list and manufacturer cannot be deleted because it still has assets in them. (even though already deleted)

### Reproduction steps

1. Delete Asset from Asset List
2. Go to Asset Manufacturers
3. Still lists I have 25 of these assets
![Screenshot 2023-03-21 at 12 14 07 pm](https://user-images.githubusercontent.com/114973646/226497711-ff0ead6c-4315-4cf9-98e9-d6248f792aca.png)
4. Click on Asset
5. Shows I have no assets from that Manufacturer
![Screenshot 2023-03-21 at 12 15 07 pm](https://user-images.githubusercontent.com/114973646/226497777-7990858c-c5c3-45e9-a117-4da1dd2acb50.png)

### Expected behavior

Should not list as any assets in the Manufacturer after deleting all assets relating to it.
Should be able to delete the Manufacturer.

### Snipe-IT Version

 v6.0.14 build 9715 (g8b70a7f21) 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.16

**Comment by jayavman** [comment]
For sure something is going on when editing assets and the Manufacturers list gets updated with numbers of assets relating to that Manufacturer.
Works perfectly fine with Consumables but Assets are not working with correct quantities.

**Comment by marcusmoore** [comment]
Hi @jayavman.

I'm having trouble replicating the issue you're describing. Using the build you referenced (specifically this commit e66b19a) I was able to create an asset for a manufacturer, delete the asset, see the asset count reflected correctly, and finally delete the manufacturer. I'm using a minimally seeded database so there might be an edge case I'm not seeing on my side. Are the steps you're taking what I went through in this attached video but with a different outcome?

https://user-images.githubusercontent.com/1141514/226751741-be3df6da-02e6-4aae-8e1d-40ef889ca1da.mp4

Let me know any other info you have that might be helpful about your environment and I'll be happy to help debug.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
