### ISSUE TITLE
login_common_disabled

### ISSUE THREAD

**Issue by sOUTHX1337** [grokability/snipe-it#12711]
### Debug mode

- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

While opening the site i get the error "403 Forbidden." 

debug shows "LOG.debug: login_common_disabled is set to 1 - return a 4032

site works as it should while user is still logged in, new login not possible

### Reproduction steps

1. Open site
2.
3.
...

### Expected behavior

i should be able to login

### Snipe-IT Version

6.0.14

### Operating System

Debian

### Web Server

Apache

### PHP Version

8.2

**Comment by snipe** [comment]
You'll want to uncheck the box in `/admin/security`

<img width="660" alt="Screenshot 2023-03-24 at 6 47 36 AM" src="https://user-images.githubusercontent.com/197404/227538497-d1cf464e-8431-4a09-8962-781a1a5aa128.png">

**Comment by sOUTHX1337** [comment]
any way to do this without web ui access?
