### ISSUE TITLE
Cannot find where data is coming from in checkout email

### ISSUE THREAD

**Issue by koltzc** [grokability/snipe-it#12712]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We have upgraded Snipe-It from major versions originally running I believe v4 to now v6. In the email received to the person who checked out an item from the asset portal, we have a strange message listed under "Please read the terms of use below". I cannot find where this data is pulling from in the settings area or the database. What Table/Field (currently running v6) is this data being pulled from so I can delete it?

### Reproduction steps

Not reproducible, just looking for help.

### Expected behavior

To be able to receive emails without the terms of use message. I could edit the email template but then I would have an issue pulling updates from Github.

### Screenshots

![image](https://user-images.githubusercontent.com/15916302/226960794-54b5ccfc-0cdf-4990-895c-e5f4543f3355.png)

### Snipe-IT Version

6.0.14

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

PHP 8.1

**Comment by snipe** [comment]
That shows up if you have the Require Acceptance disabled, but there is a EULA assigned either at the Admin Settings level or the Category level.
