### ISSUE TITLE
[Feature Request]: Align Export headers and Import Fields

### ISSUE THREAD

**Issue by aurora-sevi** [grokability/snipe-it#12731]
### Is your feature request related to a problem? Please describe.

I frequently export reports for our locations in SnipeIT, adjust information in the CSV and then re-import updating existing values. This works a good portion of the time but a lot of the export field names don't align to the same name in the import fields. 

### Describe the solution you'd like

Match Import fields to the list of fields under Custom Asset report to minimize manual field assignment and decrease friction of export and import operations.

**Comment by snipe** [comment]
The importer we just merged on master should handle this for you.

**Comment by snipe** [comment]
(Side question tho - why would one do this? Not a critique, just curious)

**Comment by aurora-sevi** [comment]
> 

Lol it's a long mess of acquiring another company, going full remote, then returning to office for most. To be fair there's additional server access I'm still requesting internally.

**Comment by snipe** [comment]
Oof, yeah, we've seen that before :( Sorry for the mess you're in. 

If you pull from master it should make a lot of that mapping easier. We've been busting our bums to make that experience better.
