### ISSUE TITLE
[QUESTION]: Is there a release coming this year?

### ISSUE THREAD

**Issue by back-2-95** [grokability/snipe-it#12738]
### Is your feature request related to a problem? Please describe.

Last release is from December last year.

### Describe the solution you'd like

To have a new release.

**Comment by snipe** [comment]
We push code all the time, literally every week. If you're up to date on master, you've already got several releases worth of changes already. We'll be pushing 6.1.0-pre this week, which will just be a pre-release for 6.1.0 while we finish the final QA for that release. We were holding off on releasing until we had a few of the bigger things handled (which have been on `master` for a week or so.) Those are out now, so we're just doing final QA passes.

As I've mentioned in our discord, 6.1.0 will likely be the last of the v6 line (there might be a few small point releases after, but hopefully not many), and then we turn our attention to v7, which will require a minimum of PHP8.
