### ISSUE TITLE
license check-out/check-in notes not viewable

### ISSUE THREAD

**Issue by stan0t** [grokability/snipe-it#12740]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The notes set while checking out or in a license-seat is nowhere viewable. 
There is no column settable for "notes"

only found it in the activity report so far and that is very impractical

### Reproduction steps

1. check-out a license seat
2. take notes in the notes field
3. notes are not viewable in the license itself or within the user
...

### Expected behavior

Notes taken while check-out should be viewable somewhere obvious

### Snipe-IT Version

Version v6.0.14 - build 9038

### Operating System

CentOS 7

### Web Server

Apache/2.4.6

### PHP Version

PHP 8.0.25

**Comment by snipe** [comment]
Checkout notes are visible in the license/user history:

<img width="1656" alt="Screenshot 2023-03-28 at 4 38 50 AM" src="https://user-images.githubusercontent.com/197404/228224586-a63e1932-8b56-4c3b-b0de-1efd6f49485d.png">
<img width="1653" alt="Screenshot 2023-03-28 at 4 39 00 AM" src="https://user-images.githubusercontent.com/197404/228224596-195e5b73-1a8c-4699-975b-3987a580a384.png">

**Comment by stan0t** [comment]
thanks for the fast response.
i can see the notes in the license history but i cant set a column for notes in the user history as it seems

**Comment by snipe** [comment]
No worries - do you have the notes column visible in the history tab? 

<img width="824" alt="View_User_Snipe_E__Head____Snipe-IT_Demo" src="https://user-images.githubusercontent.com/197404/228237083-555d57df-0e85-4676-9c43-da0e9695d502.png">

**Comment by stan0t** [comment]
unfortunately not

![Bildschirm­foto 2023-03-28 um 14 49 21](https://user-images.githubusercontent.com/61594368/228241285-3e921a98-9de9-4017-8602-33f96a2bfb1e.png)

**Comment by snipe** [comment]
Can you pull latest from master? I know you're on 6.0.14, but we've pushed out a lot of changes since then and it's possible that you're on a slightly older version.

**Comment by stan0t** [comment]
I will try this at the end of the week in our maintenance window and report back to you

**Comment by stan0t** [comment]
the column is now visible as intended. thanks for your help
