### ISSUE TITLE
Wrong url/encoding at Requestable Assets 

### ISSUE THREAD

**Issue by urbaned121** [grokability/snipe-it#12742]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Wrong URL to the model page from Requestable Assets  -> Asset Models Tab

### Reproduction steps

1. open Requestable Assets 
2.-> Asset Models Tab
3. Click on a model to view it.
as a result we have a https://mydomain.eu%27/models/'.3)%20%7D%7D instead of https://mydomain.eu/models/3
Viewing mydomain.com/hardware and clicking on the model, shows the correct link (https://mydomain.eu/models/3) 
I discovered the issue on 6.0.14 version and after upgrading docker image to the latest (v6.1.0-pre - build 10030) problem still exists

### Expected behavior

Viewing the model from Requestable Assets should generate the correct link to the model page

### Screenshots

![Screenshot 2023-03-28 at 14 47 00](https://user-images.githubusercontent.com/31166488/228240684-8a1171de-4e9a-4a49-b5c2-17f0a1f7b60a.png)
![Screenshot 2023-03-28 at 14 47 37](https://user-images.githubusercontent.com/31166488/228261104-95f204aa-78e3-4863-af4a-f1ac80fdec31.png)

### Snipe-IT Version

v6.1.0-pre - build 10030 and 

### Operating System

Docker

### Web Server

Apache

### PHP Version

7.4.3-4ubuntu2.18

### Operating System

MacOS

### Browser

Chrome, Safari

### Version

Latest

**Comment by snipe** [comment]
I'd suggest upgrading. I can't reproduce this locally or on the demo, so I'd imagine this has already been fixed.

**Comment by urbaned121** [comment]
@snipe Thanks for quick response, 
I forgot to check on the demo.. 
as I mentioned, I discovered it when my version was 6.0.14, meantime Ive upgraded to the latest docker image v6.1.0-pre - build 10030 and it still generates the wrong URLs

The model with ticked "Users may request this model" a few minutes ago:
 mydomain.eu%27/models/'.2)%20%7D%7D

**Comment by snipe** [comment]
Latest docker should definitely not be 6.0.10 - do you maybe mean 6.1.0?

**Comment by urbaned121** [comment]
and issue exist at demo site, checked
![Screenshot 2023-03-28 at 16 12 20](https://user-images.githubusercontent.com/31166488/228266435-48d22f58-584b-436b-b123-df1867b023eb.png)

**Comment by snipe** [comment]
Ugh, never mind. I can't read lol sorry.

Hm, okay, I'll have someone take a look at this. Your APP_URL is `https://mydomain` with no trailing slashes, etc, right?

**Comment by snipe** [comment]
Yep - I can reproduce this. We'll have a fix out shortly.

**Comment by snipe** [comment]
The fix is on master now - thanks for the heads up!

**Comment by urbaned121** [comment]
yep, its works now. Thanks!
