### ISSUE TITLE
Barcode obscuring text on square labels.

### ISSUE THREAD

**Issue by mikeatals** [grokability/snipe-it#12755]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I bought some 2" x 2" labels and the QR code fills the whole label space obscuring the text.  Looks like the QR is sized based on 100% of the label height 

### Reproduction steps

1. set label size to 2x2
2. print a label
3. label will be 100% QR code and text is over the QR code.
...

### Expected behavior

Some control on the barcode size.

### Screenshots

![image](https://user-images.githubusercontent.com/115121266/228402901-90a1e6d0-3fec-434d-8294-60fe079bcbe2.png)

### Snipe-IT Version

v6.0.10 build 8673 (gc6cbf3712)

### Operating System

Ububtu

### Web Server

Apache

### PHP Version

7.4.3-4ubuntu2.18

**Comment by Godmartinz** [comment]
If this is an issue still for anyone else:
May I recommend using the Custom CSS available in Settings->Branding?
There is a text area you can apply values that would work best for you:

![image](https://github.com/snipe/snipe-it/assets/47435081/cdbc03de-3859-4532-967a-d03d72e6c248)

Copy & Paste this into Custom CSS to adjust the value for the Y axis of the barcode (Default settings reflected below):
```
img.barcode {
        margin-top:-7px;
    }
```

If you would like to adjust your QR code ​(​Default settings reflected below):
```
img.qr_img {

    width: 120.79%;
    height: 120.79%;
    margin-top: -6.9%;
    margin-left: -6.9%;
    padding-bottom: .04in;
}
```

I hope adjusting these to your liking will solve your issue.
