### ISSUE TITLE
Missing property in API reference

### ISSUE THREAD

**Issue by NorskNoobing** [grokability/snipe-it#12777]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The API reference for POST on the locations endpoint is missing the `city` property in the documentation.
https://snipe-it.readme.io/reference/locations-2

I've tested that the endpoint actually supports the `city` property, and it does.
![image](https://user-images.githubusercontent.com/39239702/229457962-9fd654fd-0169-46fd-9c20-f7f771fca4dc.png)

### Reproduction steps

https://snipe-it.readme.io/reference/locations-2
![image](https://user-images.githubusercontent.com/39239702/229458568-0024c288-b23f-40e6-a61d-677338a4138f.png)

### Expected behavior

The `city` property should be in the property-list of the payload, which it currently isn't:
![image](https://user-images.githubusercontent.com/39239702/229458759-49d80220-9aaa-4c50-a0e7-a5dbcb7a9bf2.png)

### Snipe-IT Version

N/A

### Operating System

N/A

### Web Server

N/A

### PHP Version

N/A

**Comment by NorskNoobing** [comment]
Note that this is in the v6.0.14 API reference

**Comment by snipe** [comment]
Added, thanks for the heads up!
