### ISSUE TITLE
Create elements even if no stock

### ISSUE THREAD

**Issue by victor-cereijo-idf** [grokability/snipe-it#12778]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

You can manually go to the object (tested n accesories: /accessories/*id*/checkout), and then create an object even if that object has no stock available.

### Reproduction steps

1. go to /accessories/*id*/checkout, normally going back in the browser.
2. create the object, tested on accesories and probably the same applies for every other object.
3. object is created succesfully even if there is no stock.
4. listed as negative stock with a red warning.

### Expected behavior

Checkout page shound't allow the success/creation if there is no stock available with a warning explaining something like "there is no stock for more checkouts"

### Snipe-IT Version

6.0.14

### Operating System

Ubuntu 22.04

### Web Server

LAMP

### PHP Version

8.1

### Operating System

Windows

### Browser

Chrome

**Comment by Godmartinz** [comment]
Licenses and Components don't appear to allow this to happen. The above PRs should solve this issue. 🤞
