### ISSUE TITLE
APP_URL not respected for some Links

### ISSUE THREAD

**Issue by christianhauff** [grokability/snipe-it#12772]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Some URL-Paths don't seem to respect the APP_URL-Config when using a subpath. I am running a docker-setup, in front of the docker-container is an nginx which handles https. I am using a subpath for snipe-it as i have serveral applications on that server, all running in docker-containers behind that nginx. I know from the [documentation](https://snipe-it.readme.io/docs/subdirectories) that this is not the best decision, but necessary in my case.

I have set the APP_URL correctly, I have modified the .htaccess and I have checked my nginx-configuration, everything according to the documentation. 90% of snipe-it are running absolutely fine, but in some places, internal links are broken, see the reproduction steps below.

I dug into the source code a bit. It seems like when building some links, the configuration is used, i am taking `app/Http/Controllers/ReportsController.php` L. 854 as an example here:

```php
$row[] = config('app.url').'/hardware/'.$asset->id ;
```

But there are other places (the one from the reproduction steps) where the function `url('/')` is used, like in `resources/views/statuslabels/index.blade.php` L. 109, it says:

```php
return '<a href="{{ url('/') }}/hardware/?status_id=' + row.id + '"> ' + row.name + '</a>';
```
 which seems to ignore the set subpath. Am I wrong there or is the APP_URL-configuration not consistently used?

### Reproduction steps

1. Run Snipe-IT as a docker-container with an Nginx-Proxy on a subpath (e.g. /snipeit/)
2. Go to Settings -> Status Labels
3. Click on the Edit-Symbol behind a status-Label -> Works
4. Click on the name of a Status-Label itself -> URL is shown correct at first (https://domain.tld/snipeit/hardware...), but there is a 302-redirect to the url without the subpath (https://domain.tld/hardware) which doesn't exist

### Expected behavior

Snipe-IT should build all internal links including the configured subpath from APP_URL

### Snipe-IT Version

v6.1.0-pre build 10030 (gdcbd216e2) 

### Operating System

Ubuntu / Docker

### Web Server

Docker

### PHP Version

7.4.3-4ubuntu2.18 

### Operating System

Arch Linux, Windows

### Browser

Firefox

### Version

111.0

**Comment by snipe** [comment]
I have a PR up for this, but we're trying to determine if this will negatively impact folks who `APP_ALLOW_INSECURE_HOSTS` hosts enabled, for example in situations where they access the URL differently when on their internal network vs from the outside world.

**Comment by snipe** [comment]
It's on develop now, if you're in a position where you can test that
