### ISSUE TITLE
UI bug - EOL field in "Create asset model" too small

### ISSUE THREAD

**Issue by wamazeka** [grokability/snipe-it#12776]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Field EOL in "Create Asset Model" is too small in normal browser scale with pinned left menu. So, digits not displayed, when entered.
Problem already in dev DEMO build on demo.snipeitapp.com (v6.1.0-pre - build 10030 (master)
Worked on different Windows, Macos browser's in my stable build also 

So, need to edit width of this element in style files

### Reproduction steps

1. Disable auto hiding left app menu by pressing sandwich button
2. Browser scale(zoom) is disabled or above 100%
3. Open page "Create Asset Model"
4. Try to enter digits in field EOL and view digits

### Expected behavior

Expect to see digits in Field EOL 

### Screenshots

Here we see, that in field from editor were entered digits "12", but don't display.
Remind, left menu is fixed.

<img width="1210" alt="Снимок экрана 2023-04-02 в 22 41 23" src="https://user-images.githubusercontent.com/7118706/229372356-1c6ce85c-70be-4f7e-8182-df7481cc4e14.png">

And in next image I manually edit "width" of element and now I can see digits

<img width="1218" alt="Снимок экрана 2023-04-02 в 22 42 46" src="https://user-images.githubusercontent.com/7118706/229372408-be3435e1-b885-4278-9b8a-1545fb46fbac.png">

### Snipe-IT Version

6.1.0-pre - build 10030,

### Operating System

Linux

### Web Server

all

### PHP Version

all

### Operating System

Macos, Windows

### Browser

Google Chrome, Safari, Firefox

### Version

Newest

**Comment by snipe** [comment]
Are you on a particularly small screen? It shows up pretty normally on my 16" M1 MBP.

<img width="1634" alt="Screenshot 2023-04-05 at 3 51 35 PM" src="https://user-images.githubusercontent.com/197404/230229010-398d46b2-24cc-47d1-bd92-08dc856acd45.png">

**Comment by wamazeka** [comment]
I work on MacBook 13" with native resolution
But problem was also on mobile version, and I thought it was easy to fix
Thank's for fast solution!
