### ISSUE TITLE
QR-Code not created correctly

### ISSUE THREAD

**Issue by 00shorty** [grokability/snipe-it#12785]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Creating a QR-Code only creates an qr-code that is not working. Seems that it is not including the url to the site.
![image](https://user-images.githubusercontent.com/81369868/230097051-4267541e-109d-4526-a1d8-29a92a6e61dc.png)

### Reproduction steps

1. Select the asset

### Expected behavior

The URL should be included in the QR-Code

### Screenshots

![image](https://user-images.githubusercontent.com/81369868/230097164-d47f5376-521d-45a7-a608-021841c5d4e6.png)
![image](https://user-images.githubusercontent.com/81369868/230097208-ce5a9946-2685-4fc5-8bfa-bdfa44b15bca.png)

### Snipe-IT Version

6.0.7- build 8351

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows 10

### Browser

Google Chrome

### Version

111.5

**Comment by snipe** [comment]
What's your APP_URL set to?

**Comment by 00shorty** [comment]
one of my colleagues forget to clear the config cache and delete existing qr-code pictures.
Now it looks like it is working.
