### ISSUE TITLE
Depreciation Calculation not working as expected

### ISSUE THREAD

**Issue by jzdeb** [grokability/snipe-it#12788]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Depreciation is not calculating properly for assets.

### Reproduction steps

1. Create a Depreciation Method
2. Apply to a Model
3. Values do not make sense

### Expected behavior

Example:
Purchase Date: 2019-07-02
Purchase Cost: 1804.46
Depreciation method: 60 months, minimum value of $120.

There should be 14 months left for the device before it hits the value of $120 but is showing a current value of $1551.79.

The current value should be 1804.46/60 * 14 = $421.04

### Screenshots

![image](https://user-images.githubusercontent.com/73870574/230160360-9f83d1d3-4aae-43e0-b86a-fcc719f31426.png)
![image](https://user-images.githubusercontent.com/73870574/230160459-1f319bea-6b3c-4dea-acd0-d1371200f1f1.png)

### Snipe-IT Version

v6.0.11 - build 8758 (master)

### Operating System

snipe-it.io Cloud

### Web Server

snipe-it.io Cloud

### PHP Version

snipe-it.io Cloud

### Operating System

Windows

### Browser

Microsoft Edge

**Comment by Godmartinz** [comment]
Hi @jzdeb, Try upgrading your version of SnipeIT and see if that fixes the problem, as I do recall a depreciation fix being applied after your current version. Let me know if that doesn't solve your problem.

Thanks 🙂

**Comment by jzdeb** [comment]
Hi @Godmartinz I'm on the paid hosted version of Snipe-IT, I can't find a way to force my instance to upgrade. Any ideas?

**Comment by Godmartinz** [comment]
ah ok, we can handle that for you then. I'd recommend going through our [customer support](http://support.snipeitapp.com/) where you can share your email or slug with us there and we will update that for you quickly 👍

**Comment by jzdeb** [comment]
Thank you, support was able to update my instance and it is indeed resolved.
