### ISSUE TITLE
[Feature Request]: Allow components to be mapped to a supplier #7795

### ISSUE THREAD

**Issue by rkthamizhan** [grokability/snipe-it#12784]
### Is your feature request related to a problem? Please describe.

  SnipeIT Version v6.0.14 - build 9236 (master) 

### Describe the solution you'd like

Allow components to be mapped to a supplier #7795

### Describe alternatives you've considered

Allow components to be mapped to a supplier #7795

### Additional context

Allow components to be mapped to a supplier #7795

**Comment by rkthamizhan** [comment]
Can not Map the supplier information on the components page

**Comment by rkthamizhan** [comment]
we are in v6.1.0 build 10161 (ga8ca3ad2a) but still we can't see the supplier mapped on the component tab,Snipe IT please enable this function or give some work arround

**Comment by snipe** [comment]
@rkthamizhan Yes, because that feature hasn't been built yet, which is why this issue is still open.

**Comment by snipe** [comment]
Duplicate of #7795
