### ISSUE TITLE
Custom Fields No Show into Assets and Models

### ISSUE THREAD

**Issue by caribehost** [grokability/snipe-it#12786]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

It does not show the data added in the custom fields in any of the model views and assets model

### Reproduction steps

1. Create the custom fields
2. Add them to a custom field group
3. Assign them to a asset model
4. Fill in the info for each custom field
5. Try to view the info on models and asset

### Expected behavior

information should be displayed

### Screenshots

![Update-Asset-Model-IT-Management-](https://user-images.githubusercontent.com/31072919/230144801-c565f9ad-f3e0-4596-a1bd-f470601222e6.png)
![ASUS-ExpertBook-P2451FA-P2451FA-IT-Management](https://user-images.githubusercontent.com/31072919/230144942-9f1c4713-9acc-4794-b9c7-d72e7a07bc00.png)
![View-Asset-00025-IT-Management](https://user-images.githubusercontent.com/31072919/230145079-f2e0a029-bf41-473c-a26f-97a5876b048b.png)

### Snipe-IT Version

v6.1.0-pre - build 10030 (master)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.17

### Operating System

Windows

### Browser

Brave

### Version

Versión 1.49.132 Chromium: 111.0.5563.147 (Build oficial) (64 bits)

### Additional context

Plesk GitHub Deploy (Master)

**Comment by snipe** [comment]
Can you reproduce this on the demo? https://demo.snipeitapp.com - I can't reproduce it there.

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
