### ISSUE TITLE
The asset location is being deleted

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#12809]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Good afternoon. I see this error (bug or feature) on all versions of the service and it has not been fixed yet. The problem is the following - when checking an asset, I choose its location. If you edit something in the asset after that, then its location will be deleted. The asset will be without a location. It will not be possible to find this asset in the location, since it will not be in this location. This is easily verified in the demo version of the service.

### Reproduction steps

1. Make a checkin from of the assigned asset (release the asset from the user), choosing a location for an asset
2. I edit some asset property (for example, order number)
3. This is enough for the asset location to be deleted
...

### Expected behavior

The asset must be located in the place where it was distributed in the "check in asset" process

### Screenshots

![1](https://user-images.githubusercontent.com/48224568/230730123-a566ac6a-d202-412c-b24a-ab3fe63b096e.jpg)
![2](https://user-images.githubusercontent.com/48224568/230730117-e3aef981-ffef-47cc-8632-4a17aa1e36d8.jpg)
![3](https://user-images.githubusercontent.com/48224568/230730119-738d1079-2f24-4d02-8c6a-64f8dda9d416.jpg)
![Delete Order Number](https://user-images.githubusercontent.com/48224568/230730122-a708d606-7a12-4457-a417-c93c5e8922d9.jpg)
![4](https://user-images.githubusercontent.com/48224568/230730120-2b1db0ec-d062-4da9-9888-c1b17c13d020.jpg)
![5](https://user-images.githubusercontent.com/48224568/230730121-2ccdc898-191e-40b1-bac1-5a137daf66c5.jpg)

### Snipe-IT Version

v6.1.0 (and all previous)

### Operating System

official demo site

### Web Server

official demo site

### PHP Version

official demo site

**Comment by snipe** [comment]
> and it has not been fixed yet

First we're hearing about it. We'll take a look.

**Comment by brianhoganm** [comment]
Hi,
I tested this on mine and my _location_ did **not** delete after checking in and editing the asset.  I am running v6.0.14 - build 9038 (master). Could it just be in version 6.1? I haven't updated mine yet as I am keeping a close eye on any potential issues with 6.1. I am very exited to update to version 6.1 in June once school is let out. Thanks! :)

**Comment by UserGoodtm** [comment]
> Hi, I tested this on mine and my _location_ did **not** delete after checking in and editing the asset. I am running v6.0.14 - build 9038 (master). Could it just be in version 6.1? I haven't updated mine yet as I am keeping a close eye on any potential issues with 6.1. I am very exited to update to version 6.1 in June once school is let out. Thanks! :)

An asset can have two locations - Default Location and Location. The default location is edited by the asset, and the location is assigned from the user (the user to whom the asset belongs). These two locations may be different. The default location is not affected by this problem. It is not deleted. And if the asset has only a location (without a default location), then it is deleted. I'm not making it up, it's very easy to repeat in the official demo site. While this "problem" exists, I use the default location out of necessity - when I need to place an asset in the right place, and for it to be there - during the Checkin Asset operation, I assign it the default location. In this case, the number of actions increases.. I need to assign a default location in the asset, and only then perform the Checkin Asset operation. When I need to assign an asset to a user, I do a Checkout Asset operation, after which I have to delete the default location of the asset, since it may not match the user's location.

**Comment by snipe** [comment]
> When I need to assign an asset to a user, I do a Checkout Asset operation, after which I have to delete the default location of the asset, since it may not match the user's location.

The default asset location should not need to match the user's location - that's the entire point. The default location is where it lives when it's not assigned, which gets superseded when the asset is assigned to someone.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
