### ISSUE TITLE
app_url doubled leads to 404 error on every link

### ISSUE THREAD

**Issue by veenone** [grokability/snipe-it#12808]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

after commit 161999fbca0d1fc19c314ba1c1e0cb0d0cf92dc3 (Fixed #12772 - use the APP_URL config more consistently),
all links on the app_url are doubled 

should I change something in the .env or somewhere?

6.1.0-pre was ok since it's before the commit mentioned above

### Reproduction steps

1. open all assets / accessories / consumables / else
2. select 1 of the item
3. 404 error

### Expected behavior

open link according to app_url  (i.e: localhost/hardware/37 instead of localhost/localhost/hardware/37)

### Screenshots

![image](https://user-images.githubusercontent.com/3839381/230701747-9235bd09-7f0c-4bfe-84d8-fa7da6131898.png)

![image](https://user-images.githubusercontent.com/3839381/230701783-b94375ea-106d-46c0-a287-6266823b36a4.png)

### Snipe-IT Version

6.1.0

### Operating System

Windows

### Web Server

Apache

### PHP Version

7.4.27

### Operating System

Windows

### Browser

Chrome, Edge

**Comment by snipe** [comment]
What's your APP_URL in your env?

**Comment by veenone** [comment]
hi @snipe, nevermind. 
I decided to do a clean rebuild on my dev environment and it seems the problem's gone.
not sure what was the cause though
