### ISSUE TITLE
Dropdown Menu's non functional

### ISSUE THREAD

**Issue by Myr4nium** [grokability/snipe-it#12829]
### Debug mode

- [X] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Drop-down menus are continuously loading and returning no results. It's only started to happen within recent weeks, but I can't see anyone else reporting it, so am unsure if its the version or something specific to me. 
Both my instances started doing it at the same time. Both run off different SQL Servers.

![audit problem](https://user-images.githubusercontent.com/130683957/231812778-34d92927-fa49-4466-b791-14e70107c1b0.jpg)

### Reproduction steps

1. Go to the Quick Audit page
2. Use the location drop-down menu
3.
...

### Expected behavior

Drop-down menu shows the results it specifies. I.e. my assets, my users or my locations.

### Snipe-IT Version

6.1.0 - build10161 (master)

### Operating System

Unraid

### Web Server

Apache

### PHP Version

8.1.17

### Operating System

Windows

### Browser

Chrome and Opera GX

### Version

Latest for both, updated while troubleshooting.

### Additional context

Tried a fresh install, but got the same errors. Now at a loss

**Comment by snipe** [comment]
> Both my instances started doing it at the same time. Both run off different SQL Servers.

Unfortunately, that doesn't help much if we don't know if they're both updated around the same time, what the browser errors and app logs might indicate, etc. Did you run migrations? Have you tried updating them to latest? I can't reproduce this on the demo or develop demo, so I'm not sure where else to point you.

**Comment by snipe** [comment]
Might possibly be related to this: https://github.com/snipe/snipe-it/pull/12467

Is this happening to all dropdown or just some? Do you have full company support turned on?

**Comment by chndler** [comment]
I'm experiencing the same issue. Full Multiple Companies Support is turned off in my case.

**Comment by snipe** [comment]
Unfortunately, I haven't been able to reproduce this anywhere, so I'm not really sure where to go next for this.

**Comment by snipe** [comment]
Anything in your app logs or browser console that might be useful?

**Comment by chndler** [comment]
@snipe just checked the browser console and saw mixed content errors. Checked my .env file and realized our APP_URL was still http not https 🤦‍♂️ changed to https, reloaded the .env file, and all is good now! Sorry for not checking the browser console in the first place. Thanks for everything!

**Comment by snipe** [comment]
@chndler Ah, glad you're sorted! (I'm honestly a little surprised a lot more stuff wasn't breaking for you at that point! We rely pretty heavily on that APP_URL to load images, JS, etc.)

**Comment by chndler** [comment]
I have Apache configured to upgrade requests to https so I'm guessing that sorted most things out? But I agree I'm surprised myself!

**Comment by Myr4nium** [comment]
Hi. I checked my APP_URL too after seeing that. Problem solved. Haha

Sorry for wasting your time @snipe
and thanks for working that out @chndler

**Comment by stephecannon** [comment]
I had this same issue as well. I am using HAProxy in front of SnipeIT, so I assumed that the APP_ENV variable should be http (because from SnipeIT's perspective it is serving the web requests between the reverse proxy and itself using http). I am terminating the ssl session at HAProxy. 

However, after changing the APP_ENV variable to "https://MY_URL.com" issues went away. 

Thanks team.

**Comment by Alex9001** [comment]
> I had this same issue as well. I am using HAProxy in front of SnipeIT, so I assumed that the APP_ENV variable should be http (because from SnipeIT's perspective it is serving the web requests between the reverse proxy and itself using http). I am terminating the ssl session at HAProxy.
> 
> However, after changing the APP_ENV variable to "https://MY_URL.com" issues went away.
> 
> Thanks team.

Thanks for your comment. I did the opposite and set it to http://MYURL.COM , and now my dropdowns and companies are showing. 

This was with CADDY proxy within opnsense

**Comment by Excalibur025** [comment]
My team reported the same issue. Modifying the .env file fixed the UI menu rendering but broke SAML, locking out anyone without a password login enabled account. Be careful making this change blindly. Currently investigating a workaround.

**Comment by teezyyoxo** [comment]
> I had this same issue as well. I am using HAProxy in front of SnipeIT, so I assumed that the APP_ENV variable should be http (because from SnipeIT's perspective it is serving the web requests between the reverse proxy and itself using http). I am terminating the ssl session at HAProxy.
> 
> However, after changing the APP_ENV variable to "https://MY_URL.com" issues went away.
> 
> Thanks team.

Yep – we are not using HAProxy but did move to SSL and I never updated APP_URL in the .env file. Was driving me crazy for WEEKS. Updated http to https and it immediately worked (after a page refresh, of course). 
Appreciate all the insights here, thanks everyone and @snipe for hooking me up on the Discord!
