### ISSUE TITLE
Translation of English to Dutch not always correct

### ISSUE THREAD

**Issue by insert-waffle** [grokability/snipe-it#12837]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Title explains all. The word "activa" and "asset" are mixed in use. These can be generalized to "asset" since this will be clearer than "activa."

### Reproduction steps

Not necessary.

### Expected behavior

N.a.

### Snipe-IT Version

V6.1.0 build 10161

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

**Comment by insert-waffle** [comment]
@snipe you can assign me to this one - I am actively checking the translations in my fork.

**Comment by snipe** [comment]
Hi there - you can make updates to the translations using the CrownIn platform: https://crowdin.com/project/snipe-it/nl

If you'd like to be marked as a proofreader as well, let me know what your name is on CrowdIn and I'll mark you as a translator and proofreader. Thanks!

<blockquote><img src="https://crowdin.com/favicon.ico" width="48" align="right"><div><strong><a href="https://crowdin.com/project/snipe-it/nl">Translating Snipe-IT Asset Management to Dutch language - Crowdin</a></strong></div><div>Snipe-IT Asset Management Dutch translation. Help us translate Snipe-IT Asset Management and bring it to the world!</div></blockquote>

**Comment by insert-waffle** [comment]
Hi @snipe , wasnt aware of that, so sorry! My username on Crowdin is jensm04.
I'll be happy to proof read Dutch.
