### ISSUE TITLE
SnipeIT Restore Issue

### ISSUE THREAD

**Issue by NihirT** [grokability/snipe-it#12835]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have SnipeIT version 6.0.14 and MariaDB 10.8.
While restoring backup it is showing error message like :
"mysql tool at: 'C:\\PROGRA~1\\MariaDB 10.0\\bin/mysql' does not exist, cannot restore. Please edit DB_DUMP_PATH in your .env to point to a directory that contains the mysqldump and mysql binary"
DB Dump path in .env file is as below
DB_DUMP_PATH='C:\PROGRA~1\MARIAD~1.8\bin'

Please let us know if this version is compatible or not, 
Kindly share the link to get latest compatible version for SnipeIT and MariaDB .

We get link to download MariaDB where MariaDB 10.0 is not available for download
https://mariadb.org/download/?t=mariadb&p=mariadb&r=11.1.0&os=windows&cpu=x86_64&pkg=msi&m=aliyun

### Reproduction steps

1. Restore Backup
2. MYSQL
3. PHP

### Expected behavior

Restoring not happen

### Snipe-IT Version

6.0.14

### Operating System

Windows 10

### Web Server

IIS 10.0.19041.1

### PHP Version

7.4.33

### Error messages

```shell
mysql tool at: 'C:\\PROGRA~1\\MariaDB 10.0\\bin/mysql' does not exist, cannot restore. Please edit DB_DUMP_PATH in your .env to point to a directory that contains the mysqldump and mysql binary
```

### Additional context

I have SnipeIT version 6.0.14 and MariaDB 10.8.
While restoring backup it is showing error message like :
"mysql tool at: 'C:\\PROGRA~1\\MariaDB 10.0\\bin/mysql' does not exist, cannot restore. Please edit DB_DUMP_PATH in your .env to point to a directory that contains the mysqldump and mysql binary"
DB Dump path in .env file is as below
DB_DUMP_PATH='C:\PROGRA~1\MARIAD~1.8\bin'

Please let us know if this version is compatible or not, 
Kindly share the link to get latest compatible version for SnipeIT and MariaDB .

We get link to download MariaDB where MariaDB 10.0 is not available for download
https://mariadb.org/download/?t=mariadb&p=mariadb&r=11.1.0&os=windows&cpu=x86_64&pkg=msi&m=aliyun

**Comment by snipe** [comment]
What is your `DB_DUMP_PATH` set to in your `.env`?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
