### ISSUE TITLE
Similar with case #12594 Error in Start Date - The Start Date must be a valid date

### ISSUE THREAD

**Issue by beemestd** [grokability/snipe-it#12850]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgraded from  V 5.0.12 to V 6.0.14 using php upgrade.php, it works well, only have an issue with checking in the license
<img width="230" alt="image" src="https://user-images.githubusercontent.com/26455335/232370299-443c9eeb-9d7b-4f57-ac9a-7ac169d48a5e.png">

Then I did php upgrade.php again, now the version is Version v6.1.0 - build 10161 (master)

Now, when I added new user and click the start date 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/26455335/232370715-2d1b227e-ac78-4633-95ab-38d66daa310a.png">
it prompted this error message again. 

### Reproduction steps

Create a new user
Fill in the details.
3.Click the start date
Click Save
Error message pop up: The start date must be a valid date in YYYY-MM-DD format.

### Expected behavior

As expected like in Demo portal, can add user with start date details.

### Snipe-IT Version

Version v6.1.0 - build 10161 (master)

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.33

**Comment by Godmartinz** [comment]
We are aware of this issue and we have patched it for now. Please pull down the latest version for the fix.

**Comment by beemestd** [comment]
Got it.. thank you..
