### ISSUE TITLE
Bug: Bulk Edit people button text

### ISSUE THREAD

**Issue by kbrown900** [grokability/snipe-it#12858]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Simple bug, but on the "Bulk Edit" for people, the update button says "button.update" instead of something like "Update". 

### Reproduction steps

1. Select multiple users
2. Click "Bulk Edit" Go button
3. Scroll to bottom of page

### Expected behavior

See something similar to other Bulk Edit pages saying "Save" or "Update". 

### Screenshots

![Snipe-IT Bulk Edit bug](https://user-images.githubusercontent.com/74275228/232575509-25bc0b33-8491-4d4f-94a9-f45875c8f316.png)

### Snipe-IT Version

v6.1.0 build 10161 (ga8ca3ad2a) 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.11 

### Operating System

Windows

### Browser

Firefox

**Comment by snipe** [comment]
This is already fixed on master and develop.
