### ISSUE TITLE
[Feature Request]: Adding multiple fieldsets to an asset model

### ISSUE THREAD

**Issue by mthriemer** [grokability/snipe-it#12851]
### Is your feature request related to a problem? Please describe.

When I create a new asset model I want to assign different custom fields. Since many models are different in their specs - you can't hardly compare a phone with a laptop - it is necessary to have different fieldsets where sometime the same custom fields are needed.

### Describe the solution you'd like

For me it would make more sense to have fieldsets where I put all custom fields from a specific topic (e.g. fieldset network with fields mac address, ip address or net mask) or (fieldset leasing with fields contract number, leasing costs or contract expiration). And then assign all fieldset "modules" to the asset model.

### Describe alternatives you've considered

Creating a new fieldset and adding all necessary custom fields to it which are needed for the specific asset model

**Comment by Godmartinz** [comment]
This is possible already. If you go to Settings->Custom Fields you will see you are able to create  [Custom Fieldsets](https://snipe-it.readme.io/docs/custom-fields) where you can make specific bundles that you can attach to your Asset Models.

**Comment by snipe** [comment]
For added context here, models can only have one fieldset, BUT fields can be included in many fieldsets, so you get the best of all worlds. We made a (short) video to explain that relationship in a bit more detail: https://snipe-it.readme.io/docs/custom-fields

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/custom-fields">Custom Fields</a></strong></div><div>Custom fields and fieldsets are available in Snipe-IT versions 2.1.0-pre and later.Custom fields allow you to track additional information about your assets that the default asset attributes don't cover.Check out the short video tutorial below for a full walkthrough: Think of custom fieldsets as col...</div></blockquote>

**Comment by mthriemer** [comment]
Hey, the Feature Request was more like: to get the ability to add more than 1 fieldset to models.
