### ISSUE TITLE
Cannot select a User, Asset or Location when checking out (or in) an asset

### ISSUE THREAD

**Issue by epederson** [grokability/snipe-it#12865]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When clicking on the Select User (or Asset/Location) dropdown box when checking out an asset, I cannot see the list of Users (or Assets/Locations) to choose from. Instead, there is a spinning circle that never stops spinning.

### Reproduction steps

1. Search for asset
2. Click Checkout (or Checkin)
3. Click Select User (or Asset/Location)
...

### Expected behavior

When clicking on the Select User (or Asset/Location) dropdown box when checking out an asset, I should see a list of Users (or Assets/Locations) to choose from.

### Screenshots

![2023_04_18_13_22_56_Checkout_Asset_Eastbrook_Asset_Management](https://user-images.githubusercontent.com/27121229/232870268-13796434-6874-4138-9343-8c1dff6f2956.png)
![2023_04_18_13_23_17_Checkout_Asset_Eastbrook_Asset_Management](https://user-images.githubusercontent.com/27121229/232870270-846988bb-09ec-411c-854c-600ece076754.png)
![2023_04_18_13_23_35_Checkout_Asset_Eastbrook_Asset_Management](https://user-images.githubusercontent.com/27121229/232870271-2e738030-8d6a-4094-8a77-d5662894ee53.png)

### Snipe-IT Version

Version v6.1.0 - build 10161 (master)

### Operating System

Ubuntu 20.04.6 LTS

### Web Server

Apache/2.4.41

### PHP Version

7.4.3

### Operating System

Windows 11

### Browser

Google Chrome

### Version

112.0.5615.121

### Device

Pixel 6 Pro

### Operating System

Andriod 13, with April 5 2023 security update

### Browser

Google Chrome

### Version

112,0,5615.48

### Error messages

```shell
*******From Google Chrome Console*******
all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1 Mixed Content: The page at 'https://assets.eastbrook.church/hardware/637/checkout' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://assets.eastbrook.church/api/v1/users/selectlist?page=1'. This request has been blocked; the content must be served over HTTPS.
send @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
ajax @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
transport @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
o @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
e.define.i.query @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
(anonymous) @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
e.define.i.invoke @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
e.define.i.trigger @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
e.define.r.trigger @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
e.define.r.open @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
e.define.r.toggleDropdown @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
(anonymous) @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
e.define.i.invoke @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
e.define.i.trigger @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
(anonymous) @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
dispatch @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1
m.handle @ all.js?id=abb8cd9afe481e321ed279c6a2dfed3d:1




******From Firefox Console********
XHRGET
https://assets.eastbrook.church/api/v1/locations/selectlist?page=1
[HTTP/1.1 401 Unauthorized 160ms]

	
GET
	https://assets.eastbrook.church/api/v1/locations/selectlist?page=1
Status
401
Unauthorized
VersionHTTP/1.1
Transferred884 B (44 B size)
Referrer Policysame-origin
Request PriorityHighest

    	
    Cache-Control
    	max-age=0, must-revalidate, no-cache, no-store, private
    Connection
    	Keep-Alive
    Content-Length
    	44
    Content-Type
    	application/json
    Date
    	Tue, 18 Apr 2023 18:53:02 GMT
    Expires
    	Sun, 02 Jan 1990 00:00:00 GMT
    Feature-Policy
    	accelerometer 'none';autoplay 'none';camera 'none';display-capture 'none';document-domain 'none';encrypted-media 'none';fullscreen 'none';geolocation 'none';sync-xhr 'none';usb 'none';xr-spatial-tracking 'none'
    Keep-Alive
    	timeout=5, max=100
    Pragma
    	no-cache
    Referrer-Policy
    	same-origin
    Server
    	Apache/2.4.41 (Ubuntu)
    Set-Cookie
    	snipeit_session=4drIOwp9XrenfNTX6ZzwOCeNEkCdemrBAYYx0Mfl; expires=Thu, 27-Apr-2023 02:53:02 GMT; Max-Age=720000; path=/; httponly
    Vary
    	Origin
    X-Content-Type-Options
    	nosniff
    X-Frame-Options
    	DENY
    X-XSS-Protection
    	1; mode=block
    	
    Accept
    	application/json, text/javascript, */*; q=0.01
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    DNT
    	1
    Host
    	assets.eastbrook.church
    Origin
    	https://assets.eastbrook.church
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
    X-CSRF-TOKEN
    	3MootYFhJJ4EpgE5Kt09gDPsn5dFJEH9R2jBiMXq
    X-Requested-With
    	XMLHttpRequest
```

### Additional context

- This is an upgrade.
- Webserver = Ubuntu 20.04.6 LTS
- Upgrade method = sudo -u snipeitapp php /var/www/html/snipeit/upgrade.php 
- I've turned on debugging mode, but received no errors. I saw an error when in Google Chrome's console and in Firefox's console - I have included those errors above. I tried to restore from a database backup - that did not help. I ran "sudo php artisan migrate" but there was "Nothing to migrate."
- I have NOT manually edited any data directly in the database

This happened immediately after upgrading to Version v6.1.0 - build 10161 (master). It happens when using the Chrome Browser on Windows 11 and Android 13. A similar thing happens in FireFox.

**Comment by snipe** [comment]
This looks a duplicate of #12829 - please check your `APP_URL` in your `.env` and make sure it matches the URL in your browser bar. (http vs https, no trailing slash, etc)

**Comment by epederson** [comment]
That did the trick...thanks so much! I searched for similar issues but didn't see #12829 ...again thanks a ton!

**Comment by snipe** [comment]
Great, glad you're sorted!
