### ISSUE TITLE
Managed Location - User (People)

### ISSUE THREAD

**Issue by mgtzg** [grokability/snipe-it#12872]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, can some one explain this option under People(user) Managed Location.

Its empty in all of my Users, what this option does ?

How to "turn it on" ?

My SnipeIT version is v6.0.14 - build 9236 (master)

Thnx in advance.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Managed location - expected option for user is to manage/view assets in designated location

### Screenshots

![image](https://user-images.githubusercontent.com/131240575/232994640-4b71a4be-7f41-40fd-8ee9-8fdca69fa026.png)

### Snipe-IT Version

v6.0.14 - build 9236 (master)

### Operating System

Windows server 2019

### Web Server

IIS

### PHP Version

8.10

### Operating System

Windows

### Browser

Edge

### Version

111.0.1661.54

### Error messages

```shell
I dont have errors
```

### Additional context

Fresh install
Windows server 2019 IIS
Github install

**Comment by hjertis** [comment]
Settings - Locations - Edit Location

There you can assign a manager to a location. 
What it does, I have no idea. But now you have an assigned manager to a location.

**Comment by mgtzg** [comment]
That's it, thnx !
I guess if u assign user to location, he/she can only see assets from that location.

**Comment by emreiyioz** [comment]
> That's it, thnx ! I guess if u assign user to location, he/she can only see assets from that location.

I did assign location managers to related locations and gave some permissions to them but still when they login to SnipeIT they only can see their own assets.

**Comment by snipe** [comment]
> What it does, I have no idea. But now you have an assigned manager to a location.

@hjertis Right now it just lets admins see who is managing the location, nothing more. There are no special permissions that being a location manager provides. It's possible as we build out the notifications system for v7 that they will optionally be notified of checkin/checkout activity for locations they manage.

> I guess if u assign user to location, he/she can only see assets from that location.

@mgtzg That's not correct. 

> I did assign location managers to related locations and gave some permissions to them but still when they login to SnipeIT they only can see their own assets.

@emreiyioz  That means they don't have permission to view assets, accessories, etc.

**Comment by leminhhieu2110** [comment]
i think "Location manager" can be useful when you checkout acceptance assets to these locations, the manager then will receive noti to accept or decline these assets.

**Comment by mgtzg** [comment]
Thank You !

    On Tuesday, September 26, 2023 at 12:48:11 PM GMT+2, leminhhieu2110 ***@***.***> wrote:  
 
 


i think "Location manager" can be useful when you checkout acceptance assets to these locations, the manager then will receive noti to accept or decline these assets.
