### ISSUE TITLE
Unable to merge two users together

### ISSUE THREAD

**Issue by devvonmonahan** [grokability/snipe-it#12884]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to merge two users together, the submit button is greyed out - screenshot below.

If I inspect the page and change the button status from "disabled" to "enabled" - it will enable the button and allow me to click it.
I can then merge the users and all the assets etc... will be merged along with it.

Is there perhaps a check to make sure that you've selected a user and somewhere in the code in the background, it's not enabling the button if you have one of the radio buttons selected?

### Reproduction steps

1. Go to the people tab on the left side
2. Select two users, then click on the dropdown and click merge users
3. Click on your "master" user - the submit button will still be greyed out
...

### Expected behavior

The submit button should not be greyed out

### Screenshots

![image](https://user-images.githubusercontent.com/102929115/233351492-f28bbb93-fef3-408b-923e-6a9f02c436de.png)

### Snipe-IT Version

6.10

### Operating System

Windows 10

### Web Server

Apache

### PHP Version

PHP 8.0.28

### Operating System

Windows 10

### Browser

Edge

### Version

112.0.1722.48

### Error messages

```shell
I cannot see any error messages in the logs but happy to be directed or asked to check something in particular in case I missed it.
```

### Additional context

Fresh install for testing

**Comment by snipe** [comment]
Did you pull from latest? I can't reproduce this anymore.

**Comment by devvonmonahan** [comment]
I am now on  Version v6.1.0 - build 10161 and it's working fine.

Thank you.

**Comment by shinduke** [comment]
![image](https://user-images.githubusercontent.com/36949743/233988936-dac6b11e-1381-411e-9618-ed7007742f9d.png)

Nope. I have downloaded the files from the homepage and have done the upgrade steps like described on the website.
```
composer install --no-dev --prefer-source
composer dump-autoload
php artisan migrate
php artisan config:clear
php artisan config:cache
```
Still not able to merge.

**Comment by shinduke** [comment]
Forget it. I´m an boon :D
I have downloaded the files on the weebsite but not the newest from github.
Works like a charm ....
