### ISSUE TITLE
[Feature Request]: Key to be retrieved from a Secret in Kubernetes

### ISSUE THREAD

**Issue by GeiserX** [grokability/snipe-it#12883]
### Is your feature request related to a problem? Please describe.

Currently, the option to deploy SnipeIT involves writing the key to a file in a git repository (if you want to have all your helm charts fully reproducible in case of an emergency)

### Describe the solution you'd like

I'd like the app to pick the secret from a Kubernetes secret, which can be then be used in conjunction with ExternalSecretOperator so passwords remain secure.

### Describe alternatives you've considered

Currently I'm hosting it in a git private submodule, but this is far from ideal. The config is spread out, it's less secure, and almost all modern software uses Secrets to import this config onto pods.

**Comment by snipe** [comment]
I wouldn't kick this out of bed if someone wanted to come up with a PR for it, but we don't use Kubernetes/Helm charts here, so I don't really know how to solve this problem in a way that won't break things for everyone else.

**Comment by GeiserX** [comment]
I'll close it in favor of https://github.com/t3n/helm-charts/issues/186 
This could be done easily
