### ISSUE TITLE
dropdown boxes not loading after pull to latest release on master

### ISSUE THREAD

**Issue by chydeRPSD** [grokability/snipe-it#12889]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

when checking out an asset, user/asset/location fields fail to load, simply displaying a constant circle.  It doesn't matter if text is entered or not.

### Reproduction steps

1. upgrade to v6.1.0 - build 10161 (master)
2. try to checkout item
3.
...

### Expected behavior

prior to upgrade, system had always displayed user/location/etc. information as expected

### Screenshots

![snipeit never loads](https://user-images.githubusercontent.com/131461709/233645993-f567fd39-cbe9-4956-9f12-c768afaa348e.png)
![snipe it error](https://user-images.githubusercontent.com/131461709/233645997-69b5e408-c729-44e8-8b38-6cc505fdda0a.png)

### Snipe-IT Version

v6.1.0 - build 10161 (master)

### Operating System

Ubuntu

### Web Server

Apache 

### PHP Version

PHP 8.1.2-1ubuntu2.11 

### Operating System

Windows 10/11

### Browser

Google Chrome/Firefox

### Version

various, most recent version

### Additional context

existing, longstanding install.  issue occurred after upgrading for the first time in two weeks (since late march 2023)

**Comment by chydeRPSD** [comment]
Issue appears to occur in other areas as well where the dropdown box is supposed to pull from database list....

**Comment by snipe** [comment]
Duplicate of #12829 - (TLDR; check your APP_URL)
