### ISSUE TITLE
Icon on History tab in Asset view is not displayed

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#12881]
### Debug mode

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

On the History tab in the Asset view, the Icons are not displayed.
On every other History view (or where these Icons are displayed), it works normal.

### Reproduction steps

Open History tab in Asset View. Also works on the live-demo (demo.snipeitapp.com)

### Expected behavior

The Icons should be shown.

### Screenshots

Screenshot from demo.snipeitapp.com
![image](https://user-images.githubusercontent.com/112496896/233267643-1d08df77-8824-42f2-ab81-ba9e246920cd.png)

### Snipe-IT Version

v6.1.0 build 10161 (ga8ca3ad2a)

### Operating System

demo.snipeitapp.com

### Web Server

demo.snipeitapp.com

### PHP Version

8.0.28

### Operating System

Windows 10

### Browser

Microsoft Edge for Business

### Version

110.0.1587.63

**Comment by snipe** [comment]
I'm not sure what you'd be expecting to see there though - we wouldn't use the asset icon, since you're looking at an asset's history already, so you already know it's an asset.
