### ISSUE TITLE
Can't create assets in 6.1.0

### ISSUE THREAD

**Issue by alexanderd24** [grokability/snipe-it#12882]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgrading to 6.1.0 everything seems to be ok, but as it turned out now, we can't create new assets.
At the attempt to create new asset all selectable elements in the GUI are endlessly loading:
![image](https://user-images.githubusercontent.com/91595340/233288489-f314b07c-cc67-4edf-b5d1-50e767b89428.png)
In the log (`storage/logs/laravel.log`) I can see nothing unusual.

Some observations:
If I'm running the `composer self-update --2`, I'm getting error:
![image](https://user-images.githubusercontent.com/91595340/233290162-b22b88cb-760c-4a12-bbf9-9dac0012b6d3.png)

If I'm running the `composer check-platform-reqs`, I'm getting error:
![image](https://user-images.githubusercontent.com/91595340/233290643-274cc419-b106-4a76-8c62-3d9d2724c7cb.png)

Is it relevant for the problem? How can I solve this?

### Reproduction steps

1. Log in to th Snipe-IT
2. Try to create new asset

### Expected behavior

Successful creation of the new asset

### Snipe-IT Version

v6.1.0 - build 10161

### Operating System

Ubuntu 20.04.6 LTS

### Web Server

apache2

### PHP Version

7.4(8.2)

### Operating System

Ubuntu 20.04

### Browser

Firefox

### Version

112.0.1

### Additional context

I've noticed that php installed globally was version 7.4 (in the composer I've upgraded it to 8.0). I've upgraded system php to 8.2. And after that everything got broken. Now while issuing `php upgrade.php` I've started to get this:

```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - nette/schema is locked to version v1.2.2 and an update of this package was not requested.
    - nette/schema v1.2.2 requires php >=7.1 <8.2 -> your php version (8.2.5) does not satisfy that requirement.
  Problem 2
    - nette/utils is locked to version v3.2.7 and an update of this package was not requested.
    - nette/utils v3.2.7 requires php >=7.2 <8.2 -> your php version (8.2.5) does not satisfy that requirement.
  Problem 3
    - phpspec/prophecy is locked to version v1.15.0 and an update of this package was not requested.
    - phpspec/prophecy v1.15.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.5) does not satisfy that requirement.
  Problem 4
    - nette/schema v1.2.2 requires php >=7.1 <8.2 -> your php version (8.2.5) does not satisfy that requirement.
    - league/config v1.1.1 requires nette/schema ^1.2 -> satisfiable by nette/schema[v1.2.2].
    - league/config is locked to version v1.1.1 and an update of this package was not requested.

```

And in the frontend I see this:

`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.2". `

How can I fix this?

**Comment by miklosania** [comment]
I ran into the same issue after upgrading to 6.1.0 via upgrade.php (Running on PHP 7.4.3, Ubuntu 20.04.6 LTS, Chrome)
The upgrade process went smoothly, no errors.
After the upgrade, I notice the endless loading of certain GUI elements.
I also noticed that on the Import and Backup pages, the clickable icons doesn't work at all.
![image](https://user-images.githubusercontent.com/89782874/233327476-b05ea9a1-92a7-4d2a-8a4d-8bd1138a7773.png)

I also noticed that we have 6 undeployable assets but when I open the page, none of them showing up (No matching records found)

**Comment by LemonFridge** [comment]
We have the same exact issue on a fresh install on version 6.10

**Comment by admino-alpaczino** [comment]
Hi,
We have the same problem in the company. Have you tried to upgrade php to version 8 before installing SniepIT version 6.1.0?

**Comment by miklosania** [comment]
> Hi, We have the same problem in the company. Have you tried to upgrade php to version 8 before installing SniepIT version 6.1.0?

Is php 8.0 required for SnipeIT 6.1.0? The relase page says that it'll be required in the future versions. We are currently on PHP 7.4.3)

**Comment by admino-alpaczino** [comment]
> > Hi, We have the same problem in the company. Have you tried to upgrade php to version 8 before installing SniepIT version 6.1.0?
> 
> Is php 8.0 required for SnipeIT 6.1.0? The relase page says that it'll be required in the future versions. We are currently on PHP 7.4.3)

Right, snipe version 6.1.0 doesn't need php version 8 yet

**Comment by snipe** [comment]
Duplicate of https://github.com/snipe/snipe-it/issues/12829
