### ISSUE TITLE
[Feature Request]: LDAP Settings - Location field for user

### ISSUE THREAD

**Issue by emreiyioz** [grokability/snipe-it#12896]
### Is your feature request related to a problem? Please describe.

It would be very good to sync users' **location** information from Active Directory.

### Describe the solution you'd like

Currently when sync, all users' location becomes the location what choosen by default. It can be synced with "physicalDeliveryOfficeName" or "st" attributes (or better if we can choose whatever we want)

**Comment by snipe** [comment]
Duplicate of #12817
