### ISSUE TITLE
Users Receiving Checkin Emails Though They Are Disabled In Settings

### ISSUE THREAD

**Issue by BPNetAdmin** [grokability/snipe-it#12890]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

New install and setup on IIS (Windows Server 2022).
I have unchecked options to send checkin emails to users on the Category settings, as well as unchecking the Require Signature option in General Settings, however, users are still getting emails each time an asset is assigned to them, but only if the asset is a member of certain categories (other categories are not getting emails).

### Reproduction steps

1. Assign an asset to a user from one of troubled categories
2. Checkin Email sent and received by user
3.
...

### Expected behavior

If checkbox cleared, no checkin emails should be sent, and all categories should turn same results if configured the same.

### Screenshots

![image](https://user-images.githubusercontent.com/131488649/233721249-8583a77e-dc49-4705-8aae-8bdda66c063b.png)

### Snipe-IT Version

v6.1.0 Build 10161

### Operating System

Windows Server 2022

### Web Server

IIS

### PHP Version

PHP 8.1.18

### Operating System

Windows 10 Enterprise

### Browser

Firefox

### Version

112.0.1

**Comment by mw-christensen** [comment]
Something similar has been happening to us ever since we upgraded to the latest version of SnipeIT a few days ago. Admins are now getting daily "Expected asset checkin report" emails. 

Admins are getting the digest email as well individual emails for things that are checked out (but no longer deployable). No other employees seem to be getting these emails even though they have similarly checked out (and non-deployable) items. 

Perhaps this is expected behavior but it was not happening before the upgrade and I have no idea how to turn it on or off or why only admins would be notified.

**Comment by marcusmoore** [comment]
Thank you both for reporting. I confirmed @BPNetAdmin's issue and began working on a fix.

@mw-christensen I'll check out what you're reporting as well.

**Comment by BPNetAdmin** [comment]
@marcusmoore if you need me to send additional info or screen shares, just let me know.

I greatly appreciate your efforts so far.

BPNetAdmin

**Comment by snipe** [comment]
@mw-christensen to my knowledge, we haven't changed anything about that part. It's possible someone on your team added an address to the alerts email (`Admin > Notifications`), but we haven't touched that behavior in quite some time.

This also seems kinda unrelated to the OP's issue. 

@BPNetAdmin can you show me (obfuscated, obviously) a example email that's new and problematic?

@marcusmoore and I have been working on this together, but Snipe-IT itself has a buttload of different config options and use cases, so it would help a lot. If you could also confirm for me whether or not you have "Require signature" in your `Admin > General` settings, that would help a ton.

**Comment by BPNetAdmin** [comment]
@snipe, I can verify that I have "Require signature" disabled in my general settings as this was one of my initial troubleshooting steps (sorry if I didn't lay that out a little better in the original post).

Also, I wouldn't necessary say that the emails are problematic, we just haven't trained users on the process yet which is why we had them disabled, so it is causing a little bit of a stir at the organization so i would definitely prefer a way to have them temporarily disabled.

It is emailing the following:
![image](https://user-images.githubusercontent.com/131488649/235675386-19a5c386-bd92-45ac-b6bf-d90ab6fc4366.png)

Followed by the EULA that I created in the Category settings.

**Comment by marcusmoore** [comment]
@BPNetAdmin a temporary fix would be to clear the category EULAs. It's not explained to users but right now there is logic (a bug?) that checks to see if the category's EULA is populated and sends the user an email even when "Require users to confirm acceptance of assets in this category" and "Send email to user on checkin/checkout." are unchecked.

This workflow will probably change in the future and at least display some text explaining that behavior if it sticks around.

**Comment by BPNetAdmin** [comment]
@marcusmoore , thank you so much! I can absolutely use this workaround and this explains why it is only certain categories experiencing this behavior.

This will work for my needs, and then I can just add the EULA back in once the user training is complete and they are watching for the documentation.

Thank you so much, great support and great response!

**Comment by BPNetAdmin** [comment]
@marcusmoore, I am marking as closed as this solves my issue
