### ISSUE TITLE
Assets with cyrillic in name aren't searchable after update to 6.1.0

### ISSUE THREAD

**Issue by VoyNaLunu** [grokability/snipe-it#12898]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Can't search for assets using cyrillic letters after updating from 6.0.14 to 6.1.0

### Reproduction steps

1. Use v6.0.14
2. Search for asset with cyrillic letters in its name and it's able to find it
3. Update to v6.1.0
4. Search for asset with cyrillic letters in its name and it's no longer able to find it

### Expected behavior

Assets with cyrillic letters in its name are searchable

### Screenshots

v6.0.14
![image](https://user-images.githubusercontent.com/93346826/234001816-a372fb86-f45f-41b1-bbaa-8f023a7ca951.png)

v6.1.0
![image](https://user-images.githubusercontent.com/93346826/234002363-36dadd67-a759-4822-88d8-c9a68f13a010.png)

https://snipeitapp.com/demo
![image](https://user-images.githubusercontent.com/93346826/234005591-acc4d2b3-a92f-4a7f-9b9f-da08669a6885.png)

### Snipe-IT Version

v6.1.0

### Operating System

Debian 11

### Web Server

docker

### PHP Version

docker

### Operating System

Linux Mint 21

### Browser

Firefox

### Version

112.0.1

### Error messages

```shell
LOG.error: PDOException: SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'like' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:373

LOG.error: SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'like' (SQL: select count(*) as aggregate from `assets` inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` and `status_alias`.`archived` = 0 left join `users` as `assets_users` on `assets_users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\User left join `locations` as `assets_locations` on `assets_locations`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\Location left join `assets` as `assigned_assets` on `assigned_assets`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\Asset where (`assets`.`name` LIKE %Смартфон% or `assets`.`asset_tag` LIKE %Смартфон% or `assets`.`serial` LIKE %Смартфон% or `assets`.`order_number` LIKE %Смартфон% or `assets`.`purchase_cost` LIKE %Смартфон% or `assets`.`notes` LIKE %Смартфон% or `assets`.`purchase_date` LIKE %Смартфон% or `assets`.`expected_checkin` LIKE %Смартфон% or `assets`.`next_audit_date` LIKE %Смартфон% or `assets`.`last_audit_date` LIKE %Смартфон% or `assets`.`asset_eol_date` LIKE %Смартфон% or `assets`.`_snipeit_mac_adres_1` LIKE %Смартфон% or `assets`.`_snipeit_processor_2` LIKE %Смартфон% or `assets`.`_snipeit_operativnaya_pamyat_gb_3` LIKE %Смартфон% or `assets`.`_snipeit_xranilishhe_gb_4` LIKE %Смартфон% or `assets`.`_snipeit_videokarta_5` LIKE %Смартфон% or `assets`.`_snipeit_videovxody_6` LIKE %Смартфон% or `assets`.`_snipeit_razresenie_ekrana_7` LIKE %Смартфон% or `assets`.`_snipeit_castota_hz_8` LIKE %Смартфон% or `assets`.`_snipeit_imei_9` LIKE %Смартфон% or `assets`.`_snipeit_tip_videokarty_10` LIKE %Смартфон% or `assets`.`_snipeit_tip_xranilishha_11` LIKE %Смартфон% or `assets`.`_snipeit_tip_batareek_12` LIKE %Смартфон% or `assets`.`_snipeit_tip_besprovodnogo_podklyuceniya_13` LIKE %Смартфон% or `assets`.`_snipeit_kolicestvo_knopok_14` LIKE %Смартфон% or `assets`.`_snipeit_vyxodnaya_moshhnost_15` LIKE %Смартфон% or `assets`.`_snipeit_porty_dlya_zaryadki_16` LIKE %Смартфон% or `assets`.`_snipeit_diagonal_dyuim_17` LIKE %Смартфон% or `assets`.`_snipeit_versiya_bluetooth_18` LIKE %Смартфон% or `assets`.`_snipeit_podderzka_versii_wifi_19` LIKE %Смартфон% or `assets`.`_snipeit_maksimalnaya_skorost_24_ggc_wifi_mbitsek_20` LIKE %Смартфон% or `assets`.`_snipeit_maksimalnaya_skorost_5_ggc_wifi_mbitsek_21` LIKE %Смартфон% or `assets`.`_snipeit_maksimalnaya_skorost_6_ggc_wifi_mbitsek_22` LIKE %Смартфон% or `assets`.`_snipeit_setevaya_pecatskanirovanie_23` LIKE %Смартфон% or `assets`.`_snipeit_est_mikrofon_24` LIKE %Смартфон% or `assets`.`_snipeit_ostoedinyaemyi_audio_kabel_25` LIKE %Смартфон% or `assets`.`_snipeit_tip_operativnoi_pamyati_26` LIKE %Смартфон% or `assets`.`_snipeit_blok_pitaniya_27` LIKE %Смартфон% or `assets`.`_snipeit_yomkost_batarei_mwh_28` LIKE %Смартфон% or `assets`.`_snipeit_dlina_kabelya_m_29` LIKE %Смартфон% or `assets`.`_snipeit_kolicestvo_rozetok_30` LIKE %Смартфон% or `assets`.`_snipeit_maksimalnyi_tok_nagruzki_a_31` LIKE %Смартфон% or `assets`.`_snipeit_maksimalnaya_moshhnost_podklyucennoi_nagr_32` LIKE %Смартфон% or `assets`.`_snipeit_tip_podklyuceniya_audio_33` LIKE %Смартфон% or `assets`.`_snipeit_porty_i_ix_kolicestvo_34` LIKE %Смартфон% or `assets`.`_snipeit_podklyucenie_k_ustroistvu_35` LIKE %Смартфон% or `assets`.`_snipeit_razresenie_video_36` LIKE %Смартфон% or `assets`.`_snipeit_skorost_cteniyazapisi_mbs_37` LIKE %Смартфон% or `assets`.`_snipeit_kolicestvo_portov_10_mbitsek_38` LIKE %Смартфон% or `assets`.`_snipeit_kolicestvo_portov_100_mbitsek_39` LIKE %Смартфон% or `assets`.`_snipeit_kolicestvo_portov_1_gbitsek_40` LIKE %Смартфон% or `assets`.`_snipeit_upravlyaemyi_41` LIKE %Смартфон% or exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE %Смартфон% and `status_labels`.`deleted_at` is null) or exists (select * from `suppliers` where `assets`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE %Смартфон% and `suppliers`.`deleted_at` is null) or exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE %Смартфон%) or exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE %Смартфон% and `locations`.`deleted_at` is null) or exists (select * from `locations` where `assets`.`location_id` = `locations`.`id` and `locations`.`name` LIKE %Смартфон% and `locations`.`deleted_at` is null) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and (`models`.`name` LIKE %Смартфон% or `models`.`model_number` LIKE %Смартфон% or `models`.`eol` LIKE %Смартфон%)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and `categories`.`name` LIKE %Смартфон% and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and `manufacturers`.`name` LIKE %Смартфон% and `manufacturers`.`deleted_at` is null)) or `assets_users`.`first_name` LIKE %Смартфон% or `assets_users`.`last_name` LIKE %Смартфон% or `assets_users`.`username` LIKE %Смартфон% or CONCAT(assets_users.first_name," ",assets_users.last_name) LIKE %Смартфон% or `assets_locations`.`name` LIKE %Смартфон% or `assigned_assets`.`name` LIKE %Смартфон%) and `assets`.`deleted_at` is null) {"userId":1,"exception":{"errorInfo":["HY000",1271,"Illegal mix of collations for operation 'like'"]}}

works fine on the demo: https://snipeitapp.com/demo
```

### Additional context

Running on Debian 11 inside Docker using official latest image snipe/snipe-it and mysql:5.6

**Comment by snipe** [comment]
Thanks for the error messages - that helps! 

We haven't changed any collations in Snipe-IT. We've seen this once or twice before though, usually from much older systems that have then upgraded to a later (more strict) version of MySQL. Our default *now* is `utf8mb4_unicode_ci`. Laravel and MySQL had different defaults a while ago, so it's possible you need to change your collation type.

**Comment by VoyNaLunu** [comment]
I started with docker images of snipe/snipe-it:v6.0.14 and mysql:5.6 and haven't changed anything manually in laravel or database, also didn't update or downgrade mysql or snipe-it(until now).
And now that i remember i also wasn't able to search with cyrillic letters for anything other than assets and people on v6.0.14, so i downgraded to check and i get the same error in accessories, consumables, licenses or components on v.6.0.14:
<code> LOG.error: PDOException: SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'like' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:373 </code>

<code> LOG.error: SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'like' (SQL: select count(*) as aggregate from `accessories` where (`accessories`.`name` LIKE %Кабель% or `accessories`.`model_number` LIKE %Кабель% or `accessories`.`order_number` LIKE %Кабель% or `accessories`.`purchase_date` LIKE %Кабель% or `accessories`.`notes` LIKE %Кабель% or exists (select * from `categories` where `accessories`.`category_id` = `categories`.`id` and `categories`.`name` LIKE %Кабель% and `category_type` = accessory and `categories`.`deleted_at` is null) or exists (select * from `companies` where `accessories`.`company_id` = `companies`.`id` and `companies`.`name` LIKE %Кабель%) or exists (select * from `manufacturers` where `accessories`.`manufacturer_id` = `manufacturers`.`id` and `manufacturers`.`name` LIKE %Кабель% and `manufacturers`.`deleted_at` is null) or exists (select * from `suppliers` where `accessories`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE %Кабель% and `suppliers`.`deleted_at` is null) or exists (select * from `locations` where `accessories`.`location_id` = `locations`.`id` and `locations`.`name` LIKE %Кабель% and `locations`.`deleted_at` is null)) and `accessories`.`deleted_at` is null) {"userId":1,"exception":{"errorInfo":["HY000",1271,"Illegal mix of collations for operation 'like'"]}} </code>

i'll look into changing  collation type

**Comment by VoyNaLunu** [comment]
so i checked default charset and collation for snipeit database and this is what i got:

<code>mysql> SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
    -> FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'snipeit';
+----------------------------+------------------------+
| DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME |
+----------------------------+------------------------+
| latin1                     | latin1_swedish_ci      |
+----------------------------+------------------------+
</code>

I'm not good with databases and especially character encoding but i assume this being <code>latin1</code> and <code>latin1_swedish_ci</code> instead of <code>utf8mb4</code> and <code>utf8mb4_unicode_ci</code> is the issue?

**Comment by VoyNaLunu** [comment]
v6.0.14
Assets (searchable):
<code>
mysql> Select Column_name 'Column', Character_set_name 'Charset', collation_name 'Collation' FROM information_schema.columns where table_schema = 'snipeit' and table_name ='assets';
+-------------------------------------------------------+---------+--------------------+
| Column                                                | Charset | Collation          |
+-------------------------------------------------------+---------+--------------------+
| id                                                    | NULL    | NULL               |
| name                                                  | utf8mb4 | utf8mb4_unicode_ci |
| asset_tag                                             | utf8mb4 | utf8mb4_unicode_ci |
| model_id                                              | NULL    | NULL               |
| serial                                                | utf8mb4 | utf8mb4_unicode_ci |
| purchase_date                                         | NULL    | NULL               |
| asset_eol_date                                        | NULL    | NULL               |
| purchase_cost                                         | NULL    | NULL               |
| order_number                                          | utf8mb4 | utf8mb4_unicode_ci |
| assigned_to                                           | NULL    | NULL               |
| notes                                                 | utf8mb4 | utf8mb4_unicode_ci |
| image                                                 | utf8mb4 | utf8mb4_unicode_ci |
| user_id                                               | NULL    | NULL               |
| created_at                                            | NULL    | NULL               |
| updated_at                                            | NULL    | NULL               |
| physical                                              | NULL    | NULL               |
| deleted_at                                            | NULL    | NULL               |
| status_id                                             | NULL    | NULL               |
| archived                                              | NULL    | NULL               |
| warranty_months                                       | NULL    | NULL               |
| depreciate                                            | NULL    | NULL               |
| supplier_id                                           | NULL    | NULL               |
| requestable                                           | NULL    | NULL               |
| rtd_location_id                                       | NULL    | NULL               |
| _snipeit_mac_adres_1                                  | utf8mb4 | utf8mb4_unicode_ci |
| accepted                                              | utf8mb4 | utf8mb4_unicode_ci |
| last_checkout                                         | NULL    | NULL               |
| expected_checkin                                      | NULL    | NULL               |
| company_id                                            | NULL    | NULL               |
| assigned_type                                         | utf8mb4 | utf8mb4_unicode_ci |
| last_audit_date                                       | NULL    | NULL               |
| next_audit_date                                       | NULL    | NULL               |
| location_id                                           | NULL    | NULL               |
| checkin_counter                                       | NULL    | NULL               |
| checkout_counter                                      | NULL    | NULL               |
| requests_counter                                      | NULL    | NULL               |
| byod                                                  | NULL    | NULL               |
| _snipeit_processor_2                                  | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_operativnaya_pamyat_gb_3                     | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_xranilishhe_gb_4                             | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_videokarta_5                                 | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_videovxody_6                                 | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_razresenie_ekrana_7                          | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_castota_hz_8                                 | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_imei_9                                       | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_tip_videokarty_10                            | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_tip_xranilishha_11                           | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_tip_batareek_12                              | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_tip_besprovodnogo_podklyuceniya_13           | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_kolicestvo_knopok_14                         | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_vyxodnaya_moshhnost_15                       | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_porty_dlya_zaryadki_16                       | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_diagonal_dyuim_17                            | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_versiya_bluetooth_18                         | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_podderzka_versii_wifi_19                     | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_maksimalnaya_skorost_24_ggc_wifi_mbitsek_20  | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_maksimalnaya_skorost_5_ggc_wifi_mbitsek_21   | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_maksimalnaya_skorost_6_ggc_wifi_mbitsek_22   | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_setevaya_pecatskanirovanie_23                | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_est_mikrofon_24                              | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_ostoedinyaemyi_audio_kabel_25                | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_tip_operativnoi_pamyati_26                   | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_blok_pitaniya_27                             | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_yomkost_batarei_mwh_28                       | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_dlina_kabelya_m_29                           | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_kolicestvo_rozetok_30                        | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_maksimalnyi_tok_nagruzki_a_31                | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_maksimalnaya_moshhnost_podklyucennoi_nagr_32 | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_tip_podklyuceniya_audio_33                   | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_porty_i_ix_kolicestvo_34                     | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_podklyucenie_k_ustroistvu_35                 | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_razresenie_video_36                          | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_skorost_cteniyazapisi_mbs_37                 | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_kolicestvo_portov_10_mbitsek_38              | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_kolicestvo_portov_100_mbitsek_39             | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_kolicestvo_portov_1_gbitsek_40               | utf8mb4 | utf8mb4_unicode_ci |
| _snipeit_upravlyaemyi_41                              | utf8mb4 | utf8mb4_unicode_ci |
+-------------------------------------------------------+---------+--------------------+
</code>

Accessories (not searchable):
<code>
mysql> Select Column_name 'Column', Character_set_name 'Charset', collation_name 'Collation' FROM information_schema.columns where table_schema = 'snipeit' and table_name ='accessories';
+-----------------+---------+--------------------+
| Column          | Charset | Collation          |
+-----------------+---------+--------------------+
| id              | NULL    | NULL               |
| name            | utf8mb4 | utf8mb4_unicode_ci |
| category_id     | NULL    | NULL               |
| user_id         | NULL    | NULL               |
| qty             | NULL    | NULL               |
| requestable     | NULL    | NULL               |
| created_at      | NULL    | NULL               |
| updated_at      | NULL    | NULL               |
| deleted_at      | NULL    | NULL               |
| location_id     | NULL    | NULL               |
| purchase_date   | NULL    | NULL               |
| purchase_cost   | NULL    | NULL               |
| order_number    | utf8mb4 | utf8mb4_unicode_ci |
| company_id      | NULL    | NULL               |
| min_amt         | NULL    | NULL               |
| manufacturer_id | NULL    | NULL               |
| model_number    | utf8mb4 | utf8mb4_unicode_ci |
| image           | utf8mb4 | utf8mb4_unicode_ci |
| supplier_id     | NULL    | NULL               |
| notes           | utf8mb4 | utf8mb4_unicode_ci |
+-----------------+---------+--------------------+
</code>

snipeit database variables:
<code>
mysql> show variables;
...
| character_set_client                                   | latin1                                                                                                                                                                                                                                                                                                                                           |
| character_set_connection                               | latin1                                                                                                                                                                                                                                                                                                                                           |
| character_set_database                                 | latin1                                                                                                                                                                                                                                                                                                                                           |
| character_set_filesystem                               | binary                                                                                                                                                                                                                                                                                                                                           |
| character_set_results                                  | latin1                                                                                                                                                                                                                                                                                                                                           |
| character_set_server                                   | latin1                                                                                                                                                                                                                                                                                                                                           |
| character_set_system                                   | utf8                                                                                                                                                                                                                                                                                                                                             |
| character_sets_dir                                     | /usr/share/mysql/charsets/                                                                                                                                                                                                                                                                                                                       |
| collation_connection                                   | latin1_swedish_ci                                                                                                                                                                                                                                                                                                                                |
| collation_database                                     | latin1_swedish_ci                                                                                                                                                                                                                                                                                                                                |
| collation_server                                       | latin1_swedish_ci                                                                                                                                                                  
...
</code>

default charset and collation:
<code>
mysql> SELECT * FROM INFORMATION_SCHEMA.SCHEMATA;
+--------------+--------------------+----------------------------+------------------------+----------+
| CATALOG_NAME | SCHEMA_NAME        | DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME | SQL_PATH |
+--------------+--------------------+----------------------------+------------------------+----------+
| def          | information_schema | utf8                       | utf8_general_ci        | NULL     |
| def          | mysql              | latin1                     | latin1_swedish_ci      | NULL     |
| def          | performance_schema | utf8                       | utf8_general_ci        | NULL     |
| def          | snipeit            | latin1                     | latin1_swedish_ci      | NULL     |
+--------------+--------------------+----------------------------+------------------------+----------+
</code>

I tried changing default charset and collation:
<code>
ALTER DATABASE snipeit CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
</code>

and changing accessories charset and collation:
<code>
ALTER TABLE accessories CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
</code>

but neither helped, im not sure where to go from here
I didn't modify charset and collation in laravel, mysql or .env, i modified ru translation files for better consistency in translation but i don't think that could cause it, can't think of anything else i could've done to cause this issue

**Comment by VoyNaLunu** [comment]
added  to .env:
<code> DB_CHARSET=utf8mb4 </code>
<code> DB_COLLATION=utf8mb4_unicode_ci </code>
and to docker-compose.yml:
<code>command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake'] </code>
<code>
mysql> show variables like 'character%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
mysql> show variables like 'collation%';
+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8mb4_unicode_ci |
| collation_database   | utf8mb4_unicode_ci |
| collation_server     | utf8mb4_unicode_ci |
+----------------------+--------------------+
</code>

didn't help

**Comment by VoyNaLunu** [comment]
Found the cause of the problem
set up a local copy of my snipeit instance and after updating mysql from 5.6 to 5.7 im finally able to search cyrillic words anywhere
update: updated mysql to 5.7 on production server and it also works!
update 2: updated from v6.0.14 to latest and it still works!
