### ISSUE TITLE
Overlapping elements in label layout (hosted)

### ISSUE THREAD

**Issue by davisrael** [grokability/snipe-it#12897]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Scaling for the label elements seems to have changed. QR-code and 2D barcode are overlapping, now.

### Reproduction steps

1. Open an asset view or asset listing
2. Select 'generate label'
3.
...

### Expected behavior

label elements don't overlap

### Screenshots

![Labels 2023-04-24 13-13-45](https://user-images.githubusercontent.com/131668339/233980745-2be3e9af-aebc-4bac-aeac-13685407f645.png)

### Snipe-IT Version

v6.1.0 - build 10161 (hosted)

### Operating System

hosted

### Web Server

hosted

### PHP Version

hosted

### Operating System

MacOS Monterey

### Browser

Google Chrome

### Version

112.0.5615.121 (Official Build) (x86_64)

**Comment by neXtorhxs** [comment]
Hi!. I had the same issue. Solved it by changing label spacing in label settings. Hope this helps. Greetings.

**Comment by Godmartinz** [comment]
If this is an issue still for anyone else:
May I recommend using the Custom CSS available in Settings->Branding?
There is a text area you can apply values that would work best for you:

![image](https://github.com/snipe/snipe-it/assets/47435081/cdbc03de-3859-4532-967a-d03d72e6c248)

Copy & Paste this into Custom CSS to adjust the value for the Y axis of the barcode (Default settings reflected below):
```
img.barcode {
        margin-top:-7px;
    }
```

If you would like to adjust your QR code ​(​Default settings reflected below):
```
img.qr_img {

    width: 120.79%;
    height: 120.79%;
    margin-top: -6.9%;
    margin-left: -6.9%;
    padding-bottom: .04in;
}
```

I hope adjusting these to your liking will solve your issue.
