### ISSUE TITLE
[Feature Request]: Option to remove unused Status labels

### ISSUE THREAD

**Issue by 00shorty** [grokability/snipe-it#12908]
### Is your feature request related to a problem? Please describe.

If you accidentally have created some labels that are not correct or not longer in use, there is no option to delete them.

### Describe the solution you'd like

It would be nice to have a option menu point to manage status labels

### Describe alternatives you've considered

A guide in documention to delete them manually from database.

**Comment by snipe** [comment]
If a status label isn’t currently in use, you can just use the delete button in the status labels listing page, same as you can with everything else.

**Comment by Vitalmeid** [comment]
Hi snipe,

Reopening this topic with a new question, is it possible to delete or hide some native status label, for example i would like to remove the following status: Un-deployable, Archived, Deployed ( i prefer to use the status in Use), BYOD, Requestable.

Thanks
