### ISSUE TITLE
cant edit asset, compare import files

### ISSUE THREAD

**Issue by chydeRPSD** [grokability/snipe-it#12909]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Clicking Import, field matching OR
settings/asset models/update
yields a server error 500 page.

### Reproduction steps

1. click on Import/"Field matching button"
2.OR
3.Settings/Asset Models/Update

### Expected behavior

expected to display field matching OR allow edit/update of asset model.

### Screenshots

![error2](https://user-images.githubusercontent.com/131461709/234291037-e9f218bc-846f-4a48-aeff-f85837917d53.png)
![edit asset](https://user-images.githubusercontent.com/131461709/234291043-193e8efa-ecbd-41ab-9365-882d29bf481b.png)
![field matching](https://user-images.githubusercontent.com/131461709/234291045-3fae4543-6223-4811-93fc-467dfc792382.png)
![server error snipe it](https://user-images.githubusercontent.com/131461709/234291046-3a2e2853-ea12-4e9f-9484-1b5f1e55b5b5.png)

### Snipe-IT Version

v6.1.0 - build 10161 (master)

### Operating System

Ubuntu 22.0.4

### Web Server

Apache

### PHP Version

PHP 8.1.2-1ubuntu2.11 

### Operating System

Windows 10

### Browser

Google Chrome

### Version

latest

**Comment by chydeRPSD** [comment]
debug mode yields the following:
/var/www/html/snipeit/
Exception
The /var/www/html/snipeit/bootstrap/cache directory must be present and writable. (View: /var/www/html/snipeit/resources/views/models/edit.blade.php)
https://snipe-it.rpsd.org/models/4/edit

  protected function write(array $manifest)

    {

        if (! is_writable(dirname($this->manifestPath))) {

            throw new Exception('The '.dirname($this->manifestPath).' directory must be present and writable.');

        }

**Comment by chydeRPSD** [comment]
![image](https://user-images.githubusercontent.com/131461709/234588798-b0e5f9de-6301-48b0-8c8e-04d6a45ee842.png)

**Comment by chydeRPSD** [comment]
![image](https://user-images.githubusercontent.com/131461709/234588971-6b26a874-7fc0-4e04-8021-7632daaaed7e.png)

**Comment by chydeRPSD** [comment]
running 
sudo chmod -R 777 bootstrap/cache/
resolved the issue, though i am curious as to why this issue would pop up to begin with...........

**Comment by snipe** [comment]
A new file was created within the `storage/cache` directory for those two sections and with your previous directory permissions, the system user was unable to create new files within that directory. 

Glad you're sorted though!
