### ISSUE TITLE
Components Error

### ISSUE THREAD

**Issue by eibarra466996** [grokability/snipe-it#12902]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

in the component section when I add 1, it is not possible to assign it. even though the system says there is 1 left.
I have to add 2 components to assign 1

### Reproduction steps

1. components section
2.Create New
3.Quantity "1"
4. Min QTY "0"
5.Save
6. Checkout
### 7. **Error Not enough components remaining: 1 remaining, 1 requested**
...

### Expected behavior

it should assign the only component you add.

### Screenshots

![image](https://user-images.githubusercontent.com/131706912/234086654-a9fa35ef-6cdb-44a5-a974-57e1cc4872ff.png)

![image](https://user-images.githubusercontent.com/131706912/234086723-97e25b83-bb4b-4afa-b8b1-3902b8016217.png)

### Snipe-IT Version

6.1.0

### Operating System

Windows

### Web Server

Apache

### PHP Version

5.2.0

### Operating System

Windows

### Browser

Chrome

**Comment by snipe** [comment]
I'm not able to reproduce this. 

<img width="1412" alt="Screenshot 2023-04-24 at 11 55 55 AM" src="https://user-images.githubusercontent.com/197404/234089999-f413544a-cf13-42fd-961d-a51be627b0c0.png">

Can you reproduce this on the public demo?

**Comment by eibarra466996** [comment]
In the Demo version, the problem did not appear.... 
Is the demo version in the most recent April 7? In the previous version that I had installed, these errors did not appear, could I do something wrong in my update?

![image](https://user-images.githubusercontent.com/131706912/234091856-0cef60ab-3984-40d8-96ee-f495fbb7a8a4.png)

**Comment by snipe** [comment]
Demo version is latest on master.

**Comment by JenswBE** [comment]
@eibarra466996 did you find a solution? Facing the same issue with a new component I just created:
![image](https://user-images.githubusercontent.com/6514515/235064443-586dc84b-4fbc-4afb-8c74-21430bece507.png)

- Docker image: `linuxserver/snipe-it:latest`
- Snipe-IT version: `v6.1.0` (not sure what was the initial version I started with, I believe v5.x)
- Server OS: Linux
- Web server: Nginx
- PHP version: 8.1.18
- Browser: Firefox 112.0.2

Checking out 1 item works, but checking out the second (or both at once) doesn't:
![image](https://user-images.githubusercontent.com/6514515/235065560-334f0566-d2bf-4b2e-bb0b-874a23e5c948.png)
![image](https://user-images.githubusercontent.com/6514515/235065628-dc83a2aa-7a74-46b4-92d9-708f93b57130.png)

**Comment by eibarra466996** [comment]
@JenswBE I'm still looking for a solution (I mounted the previous version of my database and it works without a problem) 
I think I'll wait for the new test version to see if the error is fixed. I couldn't get a solution from @snipe  because it doesn't fail in its demo version...

**Comment by snipe** [comment]
The linuxserver distro is not ours, and we don't have any control over how often it's updated, etc. If you use our docker image from latest, this should be working. https://snipe-it.readme.io/docs/docker

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/docker">Docker</a></strong></div><div>Note very loudly that additional Docker options should be set in the env file, and they require a restart!</div></blockquote>
