### ISSUE TITLE
Cannot edit asset models

### ISSUE THREAD

**Issue by MattyGroch** [grokability/snipe-it#12911]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have created an asset model and when I try to edit the existing model (through <baseURL>/models/1/edit), I am met with a 500 Server Error.

### Reproduction steps

1. Navigate to the asset models page (/models)
2. Click the edit button on an existing model

### Expected behavior

I would expect the asset edit page to load.

### Snipe-IT Version

6.1.0

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.2

### Operating System

macOS Ventura 13.2.1

### Browser

Google Chrome

### Version

111.0.5563.146

### Error messages

```shell
Exception
The /var/www/snipe-it/bootstrap/cache directory must be present and writable. (View: /var/www/snipe-it/resources/views/models/edit.blade.php)
=======================
php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

This is a brand-new installation. I have configured LDAP and SAML and nothing else. I only started to add asset models just now.

The install is running in AWS on an EC2 instance.

**Comment by snipe** [comment]
`The /var/www/snipe-it/bootstrap/cache directory must be present and writable` is the answer. Correct the permissions on that directory and you should be all set.
`

**Comment by 4kmartin** [comment]
@snipe you moved my ticket here i have verified all files and permissions are correct. this did not work

see screen shot:
![image](https://user-images.githubusercontent.com/46980246/234676092-9a6b0dea-b6d5-4589-b89c-093a9f258b78.png)

**Comment by 4kmartin** [comment]
for those interested and maybe landing here the solution that worked for me is #12313
