### ISSUE TITLE
Can not duplicate license

### ISSUE THREAD

**Issue by CrtiUser** [grokability/snipe-it#12918]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When editing a license there seems to be an error with the right hand shown option for dublicating the license.
In my German localization there is a button saying "Lizenz duplizieren" (duplicate license).

The dupication does not work, with the error message "Der Standort ist nicht vorhanden" (location does not exist)
This might be due to the fact that the called URL is "http://MYHOST/locations/634/clone"

### Reproduction steps

1. Edit license
2. Click on the right hand side on "Clone"
...

### Expected behavior

License editor should open with a cloned license

### Snipe-IT Version

6.1.0

### Operating System

Ubuntu 22.04  lTS

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Edge

**Comment by CrtiUser** [comment]
Additonally I'm noticed that these "button" for the actions only appear in the license menu. In the Asset menu is still the pulldown menu for the actions visible. Is this configurable?

**Comment by snipe** [comment]
This should be fixed now - thanks for the heads up. 

The button view is coming to assets soon.
