### ISSUE TITLE
[Feature Request]: Add Locations or Company to low inventory alerts

### ISSUE THREAD

**Issue by shinduke** [grokability/snipe-it#12920]
### Is your feature request related to a problem? Please describe.

Atm we get just one email when something is on low inventory but there is no information in which location. In this case it´s time consuming to check if the own location has low inventory.
Since we have many different locations and some managers who managing the orders for the locations it would be nice when the information at where the inventory is getting low would be delivered with the message.
The information where the accessories, consumables and components are stocked, are also set up. So there must be an entry somwhere.
![image](https://user-images.githubusercontent.com/36949743/234576410-2005edfc-34a3-43a7-a041-111fda18c0a5.png)

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/36949743/234577071-16a99687-2a6d-469c-9a90-9a491433e8a2.png)

The Items which are mentioned in the email have all an id which is bound in the database to a location
![image](https://user-images.githubusercontent.com/36949743/234578581-d60d1695-3524-4093-bd99-a3614ef83231.png)

Somehow it should be possible to create a way to get the location names with the location_id which is bound to the item_id

**Comment by brianhoganm** [comment]
I like this feature request. I keep forgetting to put this request in. In our situation, our secretary gets the email of the low inventory report and because the inventory report is somewhat generic (from all locations) our secretary doesn't know which item is coming from. Would love to see this added to version 7.

**Comment by shinduke** [comment]
I was able to add the location in the view.blade.php to have a way to see the location after the click on the link in the mail so you dont have to search it. But i´m struggeling to add this information somehow into the mail
![image](https://user-images.githubusercontent.com/36949743/234831370-b7148f89-bd4f-49a9-a33c-35eb7897eb15.png)

**Comment by brianhoganm** [comment]
> I was able to add the location in the view.blade.php to have a way to see the location after the click on the link in the mail so you dont have to search it. But i´m struggeling to add this information somehow into the mail ![image](https://user-images.githubusercontent.com/36949743/234831370-b7148f89-bd4f-49a9-a33c-35eb7897eb15.png)

I like this idea. My only thing is that our secretary does not have access to our Snipe-IT. They only receive just the email notification. Yea, I am not sure on how to edit the actual email notification. Not sure what file that would be. I would almost think it's a table layout in the email with a column that you can just add. It would be nice down the road if there was a email template that we can add custom fields. Thanks!!

**Comment by shinduke** [comment]
![image](https://user-images.githubusercontent.com/36949743/234869868-5b2a8a11-a387-4bd2-9abd-4e2df3ce2e79.png)

Create the column is not the problem :) The column i have already created.
The problem is the correct entry to grab the informations. I have set right now a placeholder with the "Type" informations but my PHP knowledge is not that good to figure out which database table is beeing used here or where the data for the other colums is comming from.

**Comment by shinduke** [comment]
Is there maybe any information from the Snipe Team to somehow realise this?
We have the problem, that 4 responsible people hav to check every information in this to check if their location is involved

**Comment by shinduke** [comment]
I was able to realise this by myself...
Here are the changes that has to be made (i´m on windows so it can be, that you have to look for the exact location of the files). This is how my code looks like:

In C:\inetpub\wwwroot\snipe-it\resources\views\notifications\markdown\report-low-inventory.blade.php

![image](https://github.com/snipe/snipe-it/assets/36949743/5045498f-03dd-42c4-9abd-87c928e1b54b)

And in C:\inetpub\wwwroot\snipe-it\app\Helpers\Helper.php i have changed the function "checkLowInventory"

![image](https://github.com/snipe/snipe-it/assets/36949743/4787858e-71da-4f66-a318-208eb323e794)
![image](https://github.com/snipe/snipe-it/assets/36949743/a74dbf1c-3155-4414-8a19-861ee493082f)
![image](https://github.com/snipe/snipe-it/assets/36949743/1721dda3-076d-4af9-9e34-e9fe633c9fa4)

This is my result and it works. Would be glad to see this in an update so i don´t have to do it manually

![image](https://github.com/snipe/snipe-it/assets/36949743/8d1d1299-3433-4ba9-9fe5-622e771914d5)

**Comment by shinduke** [comment]
Ticket can be closed 👯

**Comment by brianhoganm** [comment]
Thank @shinduke for taking the time to figure this one out. Very much appreciated. For me, I decided to include Company and Location.
