### ISSUE TITLE
Error setting/changing a Person's Start Date

### ISSUE THREAD

**Issue by pherzing** [grokability/snipe-it#12924]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When creating or editing a Person (People) record, after selecting a Start Date and Saving, we are told "The start date must be a valid date in YYYY-MM-DD format", but the date appears to be correctly formatted (and was generated by the date picker).

### Reproduction steps

1. People >
2. Select a person
3. Expand "Optional Information:
4. Click the calendar icon next to the Start Date field
5. Select a date
6. Click the Save button
7. Field is highlighted with the noted error, and an error bar appears at the top of the screen ("Error: Please check the form below for errors".
...

### Expected behavior

The selected date should permit the form to save.

### Screenshots

![image](https://user-images.githubusercontent.com/12956715/234645643-2d687fd3-1ba9-4a95-983e-39f2a61aa661.png)

### Snipe-IT Version

6.1.0

### Operating System

Ubuntu

### Web Server

apache2

### PHP Version

7.4.33

### Operating System

MacOS 13.3.1

### Browser

Safari

### Version

16.4

### Error messages

```shell
Browser console is free of errors. The demo-mode instance does NOT appear to exhibit this behavior. (We couldn't test editing of an existing user due to demo mode restrictions, but we were able to create a new user, and set a start date on that user, without errors.
```

### Additional context

This is a long-running production server that has been upgraded numerous times to stay current with the Stable channel.

**Comment by snipe** [comment]
Can you reproduce this on the demo? I believe this is already fixed on master and develop in #12857.

**Comment by pherzing** [comment]
Thank you for your reply!

No, as noted in the writeup, I was NOT able to reproduce it in the demo. I can’t do a perfect test there (can’t edit an existing user), but the use-case of creating a new user fails on my production system but succeeds on the demo, so it’s very possible it’s addressed. If so, I apologize for the duplicate.

Paul Herzing

**Comment by snipe** [comment]
No problem - you should be able to run the `update.php` script and grab the latest off of master (assuming you have a git install)

**Comment by pherzing** [comment]
Confirmed: Problem is fixed after upgrade.php. Thanks again!

Paul Herzing

**Comment by ziagol** [comment]
Hello
I run upgrade.php but the date problem is not solved, can you please help me

**Comment by cuneytali** [comment]
Same problem on my copy. Is there any solution idea?
