### ISSUE TITLE
v6.1.0 - Asset Import – no Notes

### ISSUE THREAD

**Issue by mirktmirkt** [grokability/snipe-it#12938]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

I have just updated to Version v6.1.0 - build 10161 (master) and noticed that Notes are not being imported.. Notes are shown in a preview but are not imported..

### Reproduction steps

1. Selecting CSV
For example:
Full Name,Email,Username,item Name,Category,Model name,Manufacturer,Model Number,Serial number,Asset Tag,Location,Notes,Purchase Date,Purchase Cost,Company,Status,Warranty,Supplier
John Smith,,jsmith,,"Nubook","Apple MacBook Pro M1 13.3""",Apple,,ITxxxxx,21549,,"NB12 13"" with macOS OS Apple MacBook Pro M1 13.3"", + NATEC UTL-1449 and externtal station Raidsonic ICY BOX IB-DK2501-TB3",2021-02-10,916.05,,"Ready to Deploy",60,"AB ""Tratatai"

2. Looking into preview – everything seems ok, notes are displayed
3. Viewing imported Asset – no Notes information

### Expected behavior

Notes information is imported

### Screenshots

![import_preview](https://user-images.githubusercontent.com/4037577/234888302-33f135b9-f475-4ea2-8726-4b286b0c6a48.png)

![imported_item_view](https://user-images.githubusercontent.com/4037577/234888460-93bd8390-8296-41ef-aae8-1625a11c5093.png)

### Snipe-IT Version

Version v6.1.0 - build 10161 (master)

### Operating System

snipe Docker image

### Web Server

snipe Docker image

### PHP Version

snipe Docker image

**Comment by snipe** [comment]
This was fixed in #12975
