### ISSUE TITLE
Warranty URL is a mandatory field

### ISSUE THREAD

**Issue by qay21** [grokability/snipe-it#12946]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When updating an existing Manufacturer, it is not possible to save the data without providing a warranty lookup URL.

### Reproduction steps

1. Go to manufacturers and edit one
2. Add an image using the Select File button
3. Click the Save button

At this point, a message is displayed on top of the form :
>  Error: Please check the form below for errors 

An other error is displayed inside the form, just under the "Warranty Lookup URL" field description :
> The warranty lookup url must start with one of the following: http://, https://, afp://, facetime://, file://, irc://.

### Expected behavior

Some manufacturers don't provide a dedicated warranty lookup URL, this field should not be mandatory.

If this field is meant to be mandatory, then it should be marked as such, with the orange marker on the right of mandatory fields (for manufacturers, only the "Name" field is marked this way)

### Screenshots

![capture](https://user-images.githubusercontent.com/87803479/235138063-96be2e9c-997a-4e60-a0f6-475142a05234.png)

### Snipe-IT Version

v6.1.0

### Operating System

Docker

### Web Server

Docker

### PHP Version

Docker

### Operating System

Debian

### Browser

Firefox

### Version

102.10.0esr

### Additional context

This is a recent install (2 weeks old) using docker compose and the official SnipeIT image, unmodified.

The app is working mighty fine appart from this behaviour, which probably appeared with version 6.1.0.

**Comment by qay21** [comment]
I'm unfamiliar with SnipeIT's code, but I suspect the problem might originate from here :
https://github.com/snipe/snipe-it/blob/e250d4c884a294e9cd56ceea244f49588a6b00f4/app/Models/Manufacturer.php#L28

In this line, the `nullable` keyword doesn't seem to be included in the defined rule, with a split comma and quotes separating it.

**Comment by BBYStudios** [comment]
+1 
I just finished installing Snipe-IT on Ubuntu and found this to be a problem as well.

**Comment by qay21** [comment]
A tip : the URL is not format checked, so you can simply set "https://" in the field and the error goes away

**Comment by snipe** [comment]
I'm kinda not sure why this would be happening though - in the validation, it's marked as `nullable`

**Comment by snipe** [comment]
Sorry about that - I found the issue - fixed on develop and master now
