### ISSUE TITLE
When I clone assets, the images will be lost. But some assets share the same image, they are the same item.

### ISSUE THREAD

**Issue by yanchenur** [grokability/snipe-it#12944]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I clone assets, the images will be lost. But some assets share the same image, they are the same item.

### Reproduction steps

1. Clone assets
2.Save
3.
...

### Expected behavior

Some assets share the same image, they are the same item.When I clone assets,it's shoud be Inherit the original image.

### Snipe-IT Version

6.1.0

### Operating System

windows

### Web Server

iis

### PHP Version

8.1

### Operating System

windows

### Browser

Google Chrome

**Comment by nsty** [comment]
You can just insert the image that all assets share into the model. Unless you override it for an asset individually, it will not be deleted anymore on cloning.

**Comment by yanchenur** [comment]
> You can just insert the image that all assets share into the model. Unless you override it for an asset individually, it will not be deleted anymore on cloning.

Thanks ,I got it now~
