### ISSUE TITLE
[Feature Request]: Clone Locations

### ISSUE THREAD

**Issue by mirso1703** [grokability/snipe-it#12949]
### Is your feature request related to a problem? Please describe.

Currently when creating locations we don't have option to import from csv just them.

### Describe the solution you'd like

Have same as assets, option to clone a location and rename it something else.

Example of a name:

Parent location - Locker 1 to be able to clone this and the other with same parameters has name Parent Location - Locker 2

**Comment by snipe** [comment]
This was already added in https://github.com/snipe/snipe-it/pull/12593

<img width="832" alt="Locations____Snipe-IT_Demo" src="https://github.com/snipe/snipe-it/assets/197404/5842bdde-c042-4092-8468-6cf52728d782">

Please update to latest.
