### ISSUE TITLE
Error 500 for initial load, refresh the page and it works normally

### ISSUE THREAD

**Issue by nathanrsafti** [grokability/snipe-it#12962]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have a very strange issue that cropped up since updating to Snipe-IT 6.1.0 and PHP 8.2.5. When I load Snipe-IT initially there is an error 500 that comes up. However upon refreshing the page it works as expected for the remainder of the session. If I stop using the site for 5-10 minutes, I run into the same error once again, and a refresh fixes it again. 

My first thought was that it might be a caching error, so I went through the steps on the common issues page to clear the caches and files, still get the same issue as before.

We have multiple websites on the same host utilizing the same PHP 8.2.5 instance for various reasons and none of them exhibit the same issue. 

I didn't see any recent warnings or errors when I enabled debugging on the Snipe-IT instance. 

### Reproduction steps

1. Wait 5-10 minutes before accessing Snipe-IT
2. Visit the website
3. See the error 500 webpage

### Expected behavior

Website loads up without showing error 500 first. 

### Snipe-IT Version

6.1.0

### Operating System

Windows Server 2022

### Web Server

IIS

### PHP Version

8.2.5

### Error messages

```shell
No errors with debug mode or browser error console.

Not reproducible in the demo.

php -m output:
[PHP Modules]
apcu
bcmath
calendar
Core
ctype
curl
date
dom
fileinfo
filter
gd
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_sqlsrv
pgsql
Phar
random
readline
Reflection
session
SimpleXML
sodium
SPL
sqlsrv
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

This is a github install, we use upgrade.php to install updates.

**Comment by marcusmoore** [comment]
Hi @nathanrsafti, I see you're using PHP 8.2.5. We've noticed some issues with 8.2 and intended to restrict composer from installing on that version until they were addressed but failed to do so (a PR to add the restriction is open now #12964).

Sorry for the bad news 😕

**Comment by nathanrsafti** [comment]
Hi @marcusmoore , thanks for the information. That's unfortunate to hear. Are there any plans for Snipe-IT to support PHP 8.2 instances in the future, perhaps with v7?

**Comment by marcusmoore** [comment]
@nathanrsafti yeah, as of right now the plan is for v7 to support PHP 8.2.

**Comment by nathanrsafti** [comment]
@marcusmoore I see. Thank you!

**Comment by marcusmoore** [comment]
I'm going to close this but please ping me if you downgrade and see the same issue.
