### ISSUE TITLE
Configure relay email server

### ISSUE THREAD

**Issue by PDiogoVS** [grokability/snipe-it#12960]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I try to configure mail settings to use realy mail server (no authentication). You have any documentation how i can do it?

### Reproduction steps

.

### Expected behavior

.

### Snipe-IT Version

6.1.0

### Operating System

Ubuntu 20.04

### Web Server

Apache/2.4.41 (Ubuntu)

### PHP Version

7.4.3-4ubuntu2.18

**Comment by snipe** [comment]
You probably shouldn't be using an open relay - that's never a good idea. You can try using `mail` in your mail driver setting in your .env to use php to send the mail instead.
