### ISSUE TITLE
If you add notes to your own account then user is logged out and cannot log back in

### ISSUE THREAD

**Issue by keenanmccrary** [grokability/snipe-it#12971]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When entering a note into on your own user and clicking saving you are immediately logged out and cannot log back in.  Another user had to go into my user profile and recheck box "User can login".

### Reproduction steps

1.Lookup your user account in People section
2.Edit your user account
3.Add a note
4.Click Save
5.Instantly logged out and cannot log back in
...

### Expected behavior

1.Lookup your user account in People section
2.Edit your user account
3.Add a note
4.Click Save
5.Notes are saved and user is still logged in

### Snipe-IT Version

Version v6.1.0 - build 10161 (master)

### Operating System

hosted by Snipe

### Web Server

hosted by Snipe

### PHP Version

hosted by Snipe

**Comment by marcusmoore** [comment]
Hi @keenanmccrary, this was fixed recently (#12887). I just updated your hosted app to the latest version. Can you please let me know if it fixed your issue?

**Comment by keenanmccrary** [comment]
@marcusmoore Updating to latest version fixed issue, thank you!
