### ISSUE TITLE
"Checkin deadline approaching" emails get sent out for checked out item even though notifications are turned off

### ISSUE THREAD

**Issue by mw-christensen** [grokability/snipe-it#12988]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When an admin checks out an item, the admin will get daily emails saying "checkin deadline approaching". I have checked email logs and verified that only users with the "admin" role are getting these emails for assets that have been checked out to that admin. 

I suppose that this could be intended behavior but the timeline of events leads me to believe that this is a bug introduced in the latest version of SnipeIT. If this is expected behavior, why are emails only going out to admins, and how can I stop emails from going out for checked out items?

(Note: Assets in question are archived and no longer deployable)

Thanks!

Timeline:
2023-03-15 - Asset checked out to me (an admin)
2023-04-03 - SnipeIT marks the item in history as "expected_checkin:  2023-03-22 00:00:00"
2023-04-24 - Updated SnipeIT to version v6.1.0 - build 10161 (master)
2023-04-24 - Received the fist email for "checkin deadline approaching"
2023-04-24 - Today - Receive an email every day for "checkin deadline approaching"
2023-04-30ish - Uncheck the "Email Alerts Enabled" setting in admin>notifications - This makes no difference in email behavior for this issue.
2023-05-05ish - Play around with the "Expiring Alerts Threshold (in days) setting" to see if this is related. Apparently not. I set the days to as high as 999 and as low as 0. Checkin emails are still being sent.

![image](https://github.com/snipe/snipe-it/assets/103672717/9a5dfe5b-c66c-4a81-a0b8-aa316e98f6d8)
![image](https://github.com/snipe/snipe-it/assets/103672717/a8b273c5-0ca8-43b4-b0dd-b936002a2733)

### Reproduction steps

1. Have an admin check out an asset and not check it in.
2. Wait an undetermined (?) amount of days.
3. Receive emails saying "checkin deadline approaching"

### Expected behavior

1. Admins should have the ability to turn email notifications on or off for groups or users.
2. Assets that are archived should not have emails sent out for "checkin deadline approaching"

### Screenshots

Showing that the user is an admin:
![image](https://github.com/snipe/snipe-it/assets/103672717/a29a8246-ae88-4290-975d-a3c6dd5d920e)

Here is the asset history:
![image](https://github.com/snipe/snipe-it/assets/103672717/091902a2-6db3-4e98-8d86-a5e8a01028f6)

Here are the daily emails I am getting:
![image](https://github.com/snipe/snipe-it/assets/103672717/be5ee567-2e4f-45cb-a0de-1087c7e5c0cd)

### Snipe-IT Version

6.1.0 - build 10161 (master) 

### Operating System

Docker (Ubuntu)

### Web Server

Uncertain

### PHP Version

Uncertain

### Operating System

Windows 11

### Browser

Google Chrome

**Comment by snipe** [comment]
Are you using the scheduler, or do you have your crons/scheduled tasks set up individually?

**Comment by mw-christensen** [comment]
Thanks for the quick reply. I have not setup anything individually. (I didn't setup anything manually so I would assume that whatever is happening is because it is the default).

**Comment by snipe** [comment]
Well those alerts are being triggered by something, and that would be a cron (linux) or a scheduled task (windows).

**Comment by mw-christensen** [comment]
I setup everything with Docker. I am not really sure how I could check the cron jobs. Are you saying that turning these notifications on or off is something that cannot be done in the GUI? I will try to figure out how I can see what cron jobs are set.

Any idea why this only started happening after I upgraded to the latest version of SnipeIT? Thanks!

**Comment by marcusmoore** [comment]
Hi @mw-christensen, some details on the scheduled tasks: the emails are being fired from the `SendExpectedCheckinAlerts` command which is in the [scheduler](https://github.com/snipe/snipe-it/blob/1c1f3dc42c63e20b7e429e3169be5d192017238c/app/Console/Kernel.php#L23) as `snipeit:expected-checkin` and fires daily. The docker configuration is [set up](https://github.com/snipe/snipe-it/blob/e59ec8b27fb1b060efd556b25caf41f0a2067413/docker/supervisord.conf#L16-L15) to run scheduled tasks.

A few questions that will help with troubleshooting...

When did you update to 6.1.0? 

> 2023-04-03 - SnipeIT marks the item in history as "expected_checkin: 2023-03-22 00:00:00" 

Was the update around that point? Can you provide a screenshot of the entry in the activity log please?

> Assets in question are archived and no longer deployable

When were the assets archived? Are they archived while still being assigned to admins?

**Comment by mw-christensen** [comment]
Thanks for your response.

> 2023-04-24 - Updated SnipeIT to version v6.1.0 - build 10161 (master)

Here is the item history for the past year.
![image](https://github.com/snipe/snipe-it/assets/103672717/f8d5da50-711b-44bf-95b3-0768b686c309)

The day after my last post I went in and edited the item so it was deployable again, I then went ahead and checked it in. Then I edited it again to its previous state where it was not deployable. After I did this I stopped getting the notifications.

I think notifications are working as intended; the things that are not working as I would expect are

- I would think there would be a way I could just turn notifications on or off. This does not seem to be the case for me.
- I would expect that if an item is not deployable, the it would either 1) Be checked in automatically or 2) Have the ability to still be checked in or 3) Have notifications turned off as it can no longer be checked in.

It is very possible that I just don't understand how Requestable and checked in items are actually supposed to work. I really like the concept but I don't understand the implementation in SnipeIT.

**Comment by marcusmoore** [comment]
Thanks for re-answering my question you had already provided info for 😅 

> I would think there would be a way I could just turn notifications on or off. This does not seem to be the case for me.

Agreed. We plan on revamping the notification system to allow users to opt in and out of specific or all notifications.

> I would expect that if an item is not deployable, the it would either 1) Be checked in automatically or 2) Have the ability to still be checked in or 3) Have notifications turned off as it can no longer be checked in.

Automatically checking in the asset might make sense but would be confusing in the current version of the user interface in addition to breaking some user's workflows. I like the idea of keeping the ability to check in the asset but not being able to check it out again. Doing that would handle your third point as well.

We'll keep this in mind and appreciate the feedback 😄

**Comment by mw-christensen** [comment]
Thanks for taking the time to respond and keep up the great work! I have been using SnipeIT for nearly 10 years and LOVE it!
