### ISSUE TITLE
Unable to select user for checkout

### ISSUE THREAD

**Issue by merentitis** [grokability/snipe-it#13012]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Dropdown user list not showing up when trying to checkout any item

### Reproduction steps

1. Selecting an item or accessory for checkout
2. Trying to select a user
3. Spinning wheel showing up instead of user list
4
...
![Screenshot 2023-05-11 at 3 17 34 PM](https://github.com/snipe/snipe-it/assets/8666116/ce11a717-90e3-4ff9-baaa-45cabc74e399)

### Expected behavior

Expected behavior is to see a list of users

### Snipe-IT Version

6.1.0, 6.1.1-pre

### Operating System

Debian Docker

### Web Server

Apache (docker)

### PHP Version

PHP 8.1.2-1ubuntu2.11 (latest docker)

### Error messages

```shell
No errors show up in my browser
No laravel.log available in /var/www/html/storage/logs/
```

### Additional context

I upgraded from 6.0.14.
Until 6.0.14, there was no such issue.
Not sure if it is relevant, but LDAP sync is working fine.

**Comment by merentitis** [comment]
Issue occurs only while using apache reverse proxy
apache config:
```
        RequestHeader set X-Forwarded-Proto "https"
        ProxyPass / http://docker0.local:8100/
        ProxyPassReverse / http://docker0.local:8100/
```
my_env_file related settings:
```
APP_URL=http://snipeit.local
SECURE_COOKIES=true
```

**Comment by marcusmoore** [comment]
Hi @merentitis, I'm not sure what changed after 6.0.14 but to start, can you verify your `.env` file has the entry for `APP_TRUSTED_PROXIES` set correctly for your environment? [Docs](https://snipe-it.readme.io/docs/reverse-proxies#snipe-it-configurations) for reference.

**Comment by merentitis** [comment]
Hello.
`APP_TRUSTED_PROXIES` is set correctly and unchanged
In my browser inspector I get: 
`Blocked loading mixed active content “http://snipeit.local/api/v1/users/selectlist?page=1”`

**Comment by marcusmoore** [comment]
Hm...there were changes over a year ago that may have affected this but I can't think of anything that changed from v6.0.14 to current.

One thine I noticed is that your `APP_URL` is `http`. Can you change that to `https` and see if that fixes your issue?

**Comment by merentitis** [comment]
Of course!
mixed content warnings should have ringed a bell to me!

Thank you!

**Comment by marcusmoore** [comment]
🎉
