### ISSUE TITLE
On csv Impor Assets don't checkout

### ISSUE THREAD

**Issue by fmotzet** [grokability/snipe-it#13014]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Expected Behavior:

If a status label is left blank and a username is provided, the asset will automatically be checked out to that user.

Actual Behavior:

Status Label is set to pending and asset is not checkout to any user.

This behavior occurs with the provided demo csv. So i think i must have something setup wrong, but I can't find my error

### Reproduction steps

1. using /import upload the demo csv from https://snipeitapp.com/assets/downloads/sample-assets.csv
2. press import

### Expected behavior

If a status label is left blank and a username is provided, the asset will automatically be checked out to that user.

### Screenshots

![Screenshot 2023-05-11 182449](https://github.com/snipe/snipe-it/assets/106673224/20fede4b-e4f3-4922-bb1a-537a3651e19a)

### Snipe-IT Version

v6.1.1-pre build 10534 (g609b1646e)  (docker)

### Operating System

ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.11 

### Additional context

running in docker container

**Comment by ry-oct** [comment]
+1

Additionally checkout to location isn't working for me either. Same version on Windows server.

**Comment by BobHughes00** [comment]
I am also seeing this behavior. No combination of Username full name and status seems to assign imported assets to a user. If left blank always goes to pending.

**Comment by Alexie7777** [comment]
+1
spend an hour to tweak this feature.

**Comment by marcusmoore** [comment]
This should be fixed in #13038 (ignore the PR names mentioning locations, it actually fixes two things).

The fix is in the `develop` branch but hasn't been merged to master or included in release yet though.
