### ISSUE TITLE
Missing localized string

### ISSUE THREAD

**Issue by qay21** [grokability/snipe-it#13022]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When checking out an asset, the webhook data includes hardcoded english text instead of localized string. This is due to a missing localized string here : https://github.com/snipe/snipe-it/blob/b1fda46e113ec90a93676538753b8eec5ceb8d0d/app/Notifications/CheckoutAssetNotification.php#L110

Whereas the checkin notification is defined using a localized entry : https://github.com/snipe/snipe-it/blob/b1fda46e113ec90a93676538753b8eec5ceb8d0d/app/Notifications/CheckinAssetNotification.php#L76

### Reproduction steps

1. Configure some kind of webhook/slack notification
2. Set the app locale to anything other than english (eg. French)
3. Checkout an available asset, then check it back in
4. This should generate 2 notifications, the checkout containing literally `Asset Checked Out` while the checkin is properly translated

### Expected behavior

All notifications should use localized text as much as possible

### Snipe-IT Version

v6.1.1-pre - build 10534 (master)

### Operating System

Ubuntu

### Web Server

Dockerized

### PHP Version

Dockerized

**Comment by Godmartinz** [comment]
thanks for pointing this out! I've added a localization for this string.
