### ISSUE TITLE
Error Insufficient permissions! - Accept asset

### ISSUE THREAD

**Issue by beemestd** [grokability/snipe-it#13030]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

One user can't accept asset
<img width="929" alt="image" src="https://github.com/snipe/snipe-it/assets/26455335/d527100c-9119-4baf-86f6-8b6cf5f40475">

### Reproduction steps

1. User login to the portal
<img width="530" alt="image" src="https://github.com/snipe/snipe-it/assets/26455335/7c5bba7a-08c3-44be-9f88-af4ed590df17">

3. Display Error 403, then I click return to dashboard, it goes to the next page

4. Then I can see the asset
<img width="337" alt="image" src="https://github.com/snipe/snipe-it/assets/26455335/f91f2f44-05ef-4f2a-9b28-dffedf21a538">

5. Once I click Accept button, it shows error Insufficient permission
...
<img width="929" alt="image" src="https://github.com/snipe/snipe-it/assets/26455335/d527100c-9119-4baf-86f6-8b6cf5f40475">

### Expected behavior

Everybody that can login should be able to click accepting the assets.

### Screenshots

<img width="929" alt="image" src="https://github.com/snipe/snipe-it/assets/26455335/d527100c-9119-4baf-86f6-8b6cf5f40475">

### Snipe-IT Version

Version v6.1.0 - build 10161 (master)

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.33

### Browser

Chrome

**Comment by Tharrington86** [comment]
I too am experiencing this issue. It seems very random at this point. I would like to add that as a Super User I can change the users permission level from standard to super, have them log in, and the asset is then listed and able to be accepted. If I then revert their permission level to standard, the asset is no longer listed on their dashboard.

**Comment by marcusmoore** [comment]
Hi there @beemestd. You're saying the user sees the 403 message as soon as they log in right? Can you tell me what permissions this user has?

Hi @Tharrington86. When you say it's random do you mean it sporadically happens or is it consistent? Can you be more specific when you say the user has standard permissions? Do you mean it's `Inherit` for everything?

**Comment by Tharrington86** [comment]
@marcusmoore out of my 60ish users, 3 have experienced this issue. One of them, I was able to delete and then re-create their account to resolve the issue, but that did not work on the other 2

I am sorry for not elaborating on how we defied a "Standard User". Essentially they have permission to view everything and checkout items designated for self-checkout. 

I am running  Version v6.0.10 - build 8610 (master) currently via IIS.

**Comment by marcusmoore** [comment]
@Tharrington86 interesting that re-creating one of the users solved the issue for them. Is there anything in the logs regarding authentication for the users that are experiencing this?

What is the page that the users are attempting to go to that displays the 403 before having to click the `return to dashboard` link?

@beemestd feel free to drop any additional information you have as well.

**Comment by beemestd** [comment]
@marcusmoore , the user has **user** permission. I did as per @Tharrington86 idea, I set this user as Super Admin, and it can show the Accept Form 
<img width="722" alt="image" src="https://github.com/snipe/snipe-it/assets/26455335/76a80156-91a3-4fac-ad6e-bdeb4d1c1a25">
Once I set the user back as an **user** the 403 error did not show, but still show the insufficient permission.

**Comment by Tharrington86** [comment]
@marcusmoore Upon closer inspection my issue is slightly different than the OP.

From my view (Super User) I can see that the assest has been assigned to the user.
![adminViewOfUserAssets](https://github.com/snipe/snipe-it/assets/75510358/682b3c9a-5f4f-49a8-9bff-778934acde70)

From his view, no assest is present.
![userViewOfAssets](https://github.com/snipe/snipe-it/assets/75510358/0e3a1e11-cf73-4077-b06b-5028430961f5)

In the "accept assets" page, only the accept/decline button is present. If the button is clicked, the following is displayed. A 403 error is never encountered.
![insufficientPermissions](https://github.com/snipe/snipe-it/assets/75510358/954060da-0f45-4e59-abca-86a2200b07b2)

If I make him a super user, then the asset is listed for him and it can be accepted. After removing the super user permission from him, he can no longer see his assets.

I will have to get back to you about the logs. We have maintenance occuring today so I cannot RDP on the retrieve them.

**Comment by Tharrington86** [comment]
@marcusmoore @beemestd Interestingly enough, I cloned the user (using a variation of the username) , deleted the original, and was able to logon to the cloned account and accept the first assigned asset but additional assets just populated the accept/decline button (no asset name or other information) and the insufficient privilege message returned.

**Comment by marcusmoore** [comment]
@beemestd and @Tharrington86 can you let me know if you have Full Multiple Companies Support enabled please?

---

>I cloned the user (using a variation of the username) , deleted the original, and was able to logon to the cloned account and accept the first assigned asset 

@Tharrington86 do you mean the cloned user was able to accept the asset that was checked out to the original user?

**Comment by beemestd** [comment]
@marcusmoore Yes, I saw the Full Multiple Companies Support ticked. After I untick then the "user" can accept. thank you

**Comment by Tharrington86** [comment]
> @beemestd and @Tharrington86 can you let me know if you have Full Multiple Companies Support enabled please?
> 
> > I cloned the user (using a variation of the username) , deleted the original, and was able to logon to the cloned account and accept the first assigned asset
> 
> @Tharrington86 do you mean the cloned user was able to accept the asset that was checked out to the original user?

@marcusmoore No, I checked in the asset, then checked it out to the cloned account. They were able to then log in and accept the asset. Interestingly enough, I too had Full Multiple Company Support selected. I deselected it, and the issue was resolved for the remaining employee that was having an issue. We are utilizing SnipeIT to support sister companies but were very through when entering assets to ensure they were assigned to the proper company and then assigned to an employee of that company but maybe there is a bug hiding somewhere?

**Comment by marcusmoore** [comment]
@Tharrington86 thanks for the thorough update. It's possible there is a bug in here somewhere. Is it possible that user was accidentally put in the wrong company originally?

In either case, it seems like there can be better UX around this.

**Comment by Tharrington86** [comment]
@marcusmoore When I was adding employees and assets, I was doing them by company. The employees/assets that experienced problems were from the first company. I hadn't actually created the other companies yet, so I don't see how that could have happened.

**Comment by marcusmoore** [comment]
@Tharrington86 interesting....Thank you for the details.

There are some known "quirks" with the current implementation full multiple company support that we plan on ironing out soon. I'll keep this conversation in mind as we work through the refactors/improvements.
