### ISSUE TITLE
Following auto upgrade, drop down fields are no longer populated

### ISSUE THREAD

**Issue by jcookatlas** [grokability/snipe-it#13059]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Following auto-upgrade via php upgrade.php to v6.1.1-pre - build 10653 (master), drop down list in the CREATE NEW ASSET no longer function.  This includes ALL drop down fields Company, Model, Location, and Supplier.

No debug messages or exceptions.

Larvel log shows ' Socialite' not found errors.

Base OS is fully patched Ubnt 20.04.6.

DBase is mySQL on separate server.

Platform has been ROCK SOLID for months...  the auto upgrade introduced the issues.

What additional info can I provide to assist in troubleshooting efforts?

[sniper.atlasnet.cloud-1684512967548.log](https://github.com/snipe/snipe-it/files/11518685/sniper.atlasnet.cloud-1684512967548.log)

### Reproduction steps

1. Create a new asset.
2. Attempt to set value of Company, Model, Location, or Supplier drop-down form elements
3.
4.
...

### Expected behavior

Drop down form fields should auto-populate with all possible selections

### Screenshots

![Screenshot 2023-05-19 120730](https://github.com/snipe/snipe-it/assets/95373373/e7d4aa5b-04cc-4895-a042-e56fb41e3d83)
![Screenshot 2023-05-19 120823](https://github.com/snipe/snipe-it/assets/95373373/fff8366c-a4ff-404d-9c12-39bf62709c93)
![Screenshot 2023-05-19 120857](https://github.com/snipe/snipe-it/assets/95373373/1f2ee583-9c36-4ff0-8e96-3d7b15bdae41)
![Screenshot 2023-05-19 121003](https://github.com/snipe/snipe-it/assets/95373373/2a28f427-0793-497b-a32c-5b118e8c1ee7)

### Snipe-IT Version

v6.1.1-pre - build 10653 (master)

### Operating System

fully patched Ubnt 20.04.6.

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Edge, Chrome, Firefox

**Comment by ComputerBeforeSunset** [comment]
I am also having the same issue. Running Windows server with PHP 8.1.9.

**Comment by marcusmoore** [comment]
It seems like the upgrade script might not have run successfully since a dependency (Laravel Socialite) didn't get installed via composer.

Can you run `composer install --no-dev` and see if you get a positive outcome?

**Comment by freddie554** [comment]
I am also experiencing this same issue.

Has been going on for about a week.

we had our snipe instance to be updated with latest update but switched to master so that it would downgrade the version but error persisted.

saw the above comment and ran `composer install --no-dev` but still getting same error.

**Comment by freddie554** [comment]
also ran the different commands in the "do this if weird errors happen" section on the common issues page

**Comment by marcusmoore** [comment]
Hi @freddie554, what was the output after running `composer install`?

**Comment by freddie554** [comment]
```
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: maatwebsite/excel
Discovered Package: mediconesystems/livewire-datatables
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
84 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by freddie554** [comment]
unfortunately I deleted the POD on OpenShift after originally running that command so I just ran it again to give you some data but I cannot confirm if it is the same as before or not

**Comment by marcusmoore** [comment]
@jcookatlas I missed the link to your log file originally.

@jcookatlas and @freddie554 Does your `APP_URL` in your `.env` start with `http://` by any chance? Can you change it to `https://` and see if that helps?

@ComputerBeforeSunset can you provide a bit more info? Are you serving the app over `https` but your env has `http`? Do you also see the socialite error in your logs? Did this all start after running the update script? etc

**Comment by freddie554** [comment]
wow.....that worked. LOL! 

Thank you!! 

We wondered if we should do that too and just didn't.

**Comment by jcookatlas** [comment]
I've been dealing with some CONT-OPS issues over the course of the last several days and am currently away from a priv-access workstation.  I'll attempt those suggestions when I get back to my office.

**Comment by marcusmoore** [comment]
@freddie554 good to hear!

@jcookatlas I'm going to close this for now but please ping me if the `APP_URL` change doesn't work. I'll re-open it and we can continue working through it.

**Comment by jcookatlas** [comment]
@marcusmoore - Thank you for your help, I apologize for the delay in my response - my organization suffered an untimely and tragic loss in the C-Suite over the weekend that needed my immediate attention and I have been tied up in and with council for the past two days...

Now that I am back at a priv-access workstation in our DC and actually have the ability to 'see' everything;  I'm think the issue was created internally by a helpdesk tech who recursively CHMOD'd the entire SNIPE-IT directory to 0755.  Once the permissions were reset per [https://snipe-it.readme.io/docs/configuration](url), the application cache was cleared/re-formed , and browser caches were cleared - everything appears to be back to normal operations.

If anything else pops up, I'll poke the ticket again.

Thanks again for your help.
