### ISSUE TITLE
Importing Issue

### ISSUE THREAD

**Issue by AdilSayeed** [grokability/snipe-it#13066]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

I am trying to upload csv files but it does not work. I even tried the sample files from snipe it to check if the problem is with the csv but its not.

Any help would be appreaciated.

Thank you,
Adil

### Reproduction steps

1.Downloading the sample file
2.Adding to snipe IT
3.Trying to Import
...

### Expected behavior

Should import successfully

### Screenshots

<img width="922" alt="Screenshot 2023-05-22 184120" src="https://github.com/snipe/snipe-it/assets/134318498/63083a63-7e4d-4396-80d0-cfa14e048a03">

### Snipe-IT Version

v4

### Operating System

Ubuntu

### Web Server

Nginx

### PHP Version

8.1.12

### Operating System

Windows

**Comment by VinnyPolar** [comment]
Have you found any solutions?

**Comment by snipe** [comment]
@VinnyPolar the OP is using Snipe-IT v4, which is - quite literally several *years* old. (And also doesn't work with PHP8, so this is a malformed issue report in the first place.)

If you're having issues using modern Snipe-IT, please open a new issue.
