### ISSUE TITLE
[Feature Request]: Asset by Status Pie Chart to show correct listing

### ISSUE THREAD

**Issue by richylyq** [grokability/snipe-it#13063]
### Is your feature request related to a problem? Please describe.

Currently what is shown on the pie chart for asset by status is All Ready to Deploy, even if they are already deployed. 
![image](https://github.com/snipe/snipe-it/assets/37892224/c8364ba2-0313-4dbd-956b-56a7d02848d6)

### Describe the solution you'd like

Pie chart for Assets by Status should be separated across 
1. Deployed
2. Ready to Deploy
3. Archived 
for a better overview of all assets

**Comment by Tharrington86** [comment]
I agree that it would be nice to have the deployed assets displayed in the pie chart as their own wedge.

**Comment by snipe** [comment]
This was addressed in #11893

**Comment by richylyq** [comment]
Thanks @snipe for the update; much appreciated!
