### ISSUE TITLE
404 Not Found on Initial setup browsing to /public

### ISSUE THREAD

**Issue by ClickLeft** [grokability/snipe-it#13072]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hitting an error page when attempting initial setup:

404
Not Found
The resource requested could not be found on this server!

### Reproduction steps

1. Clean installation
2. Visit http://inventory.example.com/public
3. 404 Not Found Page appears. URL in browser shows: https://inventory.example.com/setup

### Expected behavior

Expected to see initial Pre-Flight Setup.

### Snipe-IT Version

6.1.0

### Operating System

Windows

### Web Server

Litespeed

### PHP Version

8.1

### Operating System

Windows 10

### Browser

Google Chrome, Edge, Brave

### Error messages

```shell
$ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
enchant
exif
fileinfo
filter
ftp
gd
gettext
hash
i360
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
tidy
tokenizer
xml
xmlreader
xmlwriter
xsl
zip
zlib
```

### Additional context

Fresh manual install

**Comment by marcusmoore** [comment]
Hi @ClickLeft [this section](https://snipe-it.readme.io/docs/installation-issues#the-requested-url-setup-was-not-found-on-this-server) of the docs may help. Let me know if it does 😄

**Comment by ClickLeft** [comment]
> Hi @ClickLeft [this section](https://snipe-it.readme.io/docs/installation-issues#the-requested-url-setup-was-not-found-on-this-server) of the docs may help. Let me know if it does 😄

Thanks! I did look this over several times. Adding garbage to the existing .htaccess file does nothing, but I created a test file:

`RewriteRule ^test.html$ test.php [L]`

And it works as anticipated. It seems there's something in the included .htaccess the sever doesn't like.

**Comment by marcusmoore** [comment]
Interesting...I'm honestly not too familiar with configuring apache so I'm not sure what could be causing that but I'm glad it worked 😄
