### ISSUE TITLE
Unable to Load Proper page of Snipe-IT Pre-Flight

### ISSUE THREAD

**Issue by Bigbird2773** [grokability/snipe-it#13081]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Pre-flight won't load properly.

### Reproduction steps

1.
2.
3.
...
![Error](https://github.com/snipe/snipe-it/assets/132983624/4cf17b3f-1fe8-4476-a27c-43072efdb93b)

### Expected behavior

aa

### Screenshots

![Error](https://github.com/snipe/snipe-it/assets/132983624/fc45f142-f3e0-4526-9d70-91a504926f23)

### Snipe-IT Version

Snipe 6.1.0

### Operating System

Windows

### Web Server

IIS

### PHP Version

PHP-7.4.29

### Operating System

Windows

### Browser

Google Chorme

### Error messages

```shell
Unable to Load Proper page of Snipe-IT Pre-Flight
```

**Comment by marcusmoore** [comment]
Hi @Bigbird2773,

It looks like assets aren't loading. What is being displayed in the browser's console?

**Comment by Bigbird2773** [comment]
Thanks @marcusmoore.

After Installation of Common HTTP Features in IIS the problem is solved.
