### ISSUE TITLE
it's ask for vendor folder

### ISSUE THREAD

**Issue by banana-it** [grokability/snipe-it#13086]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

* Setting permissions.
* Running composer.
-* This can take 5 minutes or more. Tail /var/log/snipeit-install.log for more full command output.
/
chgrp: cannot access '/var/www/html/snipeit/vendor': No such file or directory
* Generating the application key.
* Artisan Migrate.

### Reproduction steps

1. wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
2. chmod 744 install.sh
3. ./install.sh

### Expected behavior

* Setting permissions.
* Running composer.
-* This can take 5 minutes or more. Tail /var/log/snipeit-install.log for more full command output.
/
chgrp: cannot access '/var/www/html/snipeit/vendor': No such file or directory
* Generating the application key.
* Artisan Migrate.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/124012600/a7884a07-d1d4-4a44-b1ab-0a2ac3a5dac9)

### Snipe-IT Version

6.1.0

### Operating System

ubantu 22.04

### Web Server

Apache

### PHP Version

8.1

**Comment by marcusmoore** [comment]
Hi @banana-it, I see `adduser: The user 'snipeitapp' already exists.` in your screenshot. Did you run this script multiple times or create that user manually?

**Comment by marcusmoore** [comment]
I'm going to close this for now but ping me if you need more help 😄

**Comment by oxblixxx** [comment]
> I'm going to close this for now but ping me if you need more help 😄

I have the same issue while running this.  I had to manually create the vendor folder and some subfolders that it prompted, but then it keeps prompting "a folder doesn't exist and can't create one" . 
![Screenshot_2023-11-09_03_05_34](https://github.com/snipe/snipe-it/assets/97739416/d0524a70-c1ee-40e9-b2ee-4153c8921d01)

**Comment by marcusmoore** [comment]
Hi @oxblixxx, please create a new [bug report issue](https://github.com/snipe/snipe-it/issues/new?assignees=&labels=&projects=&template=bug_report.yml) with the details about your app version and environment? That way I'm more informed and can hopefully provide help.

Tag me with @marcusmoore so I get pinged in the new issue 😄
