### ISSUE TITLE
Assets I am importing via CSV are not being checked out to a user

### ISSUE THREAD

**Issue by tylermfontenot** [grokability/snipe-it#13091]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am importing assets via the web GUI and when I finish the import the asset is not associated with the user I assigned. I have checked the previous topics on this but they all seem to be years old and since then the CSV template has changed and it currently does not even offer a "checked out to" field. I have double and triple checked that the data is valid and have followed all import guidelines but no matter how I try the asset I import will not be assigned to the user. 

### Reproduction steps

1. Create asset CSV using the template from Snipe-IT documentation
2. Import CSV using Web GUI
3. Check the asset page to ensure it uploaded correctly
...

### Expected behavior

After importing the asset CSV it should list the asset and show that the asset is checked out to the assigned user.

### Screenshots

![import results](https://github.com/snipe/snipe-it/assets/132280170/3c796050-21c7-4f8d-b62b-4eade092a442)
![sample csv](https://github.com/snipe/snipe-it/assets/132280170/929249d4-aa87-4b7c-95f6-fc565c866fd7)

### Snipe-IT Version

6.1.1

### Operating System

AlmaLinux 9

### Web Server

Apache

### PHP Version

8.3

### Operating System

CentOS

### Browser

Firefox

### Additional context

Fresh install

**Comment by SilentGoldfish** [comment]
Hi There,

I am also having the same issue running Version v6.1.1-pre. 

Server OS: Ubuntu 22.04.2 LTS

PHP: 8.1.2

As per the [document](https://snipe-it.readme.io/docs/importing), I have left the 'status' field empty, entered a full name and entered a username still the same outcome. Tested on both GUI and CLI, asset import completes without issues however still sitting in 'Ready to Deploy' status.

In the CSV I also tried adding the Checkout Type field with the 'user' data to force it however the same outcome.

**Comment by EddyBoi479** [comment]
Hello,

Same issue here, version v6.1.1-pre

Status left empty, included full name, username, even tried email and checkout type.

Users connected via LDAP if that is important.
FYI, sample document for assets is wrong, it includes a header for notes, not 'asset notes'.

**Comment by SilentGoldfish** [comment]
H

> Hi There,
> 
> I am also having the same issue running Version v6.1.1-pre.
> 
> Server OS: Ubuntu 22.04.2 LTS
> 
> PHP: 8.1.2
> 
> As per the [document](https://snipe-it.readme.io/docs/importing), I have left the 'status' field empty, entered a full name and entered a username still the same outcome. Tested on both GUI and CLI, asset import completes without issues however still sitting in 'Ready to Deploy' status.
> 
> In the CSV I also tried adding the Checkout Type field with the 'user' data to force it however the same outcome.

Hi,

My issue is now resolved with the stable v6.1.1 release

Cheers

**Comment by marcusmoore** [comment]
Hi there! @SilentGoldfish is right...this should be fixed in the latest release. Please ping me if that is not the case and we can troubleshoot the issue 😄
