### ISSUE TITLE
'selectlists' URLs return 401 "Unauthorized or unauthenticated"

### ISSUE THREAD

**Issue by marknijboer** [grokability/snipe-it#13102]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When logged in as a superadmin I cannot retrieve the lists for the selectbox elements: All 'selectlists' URLs return a 401 "Unauthorized or unauthenticated" in SnipeIT v6.1.0. Downgrading to 6.0.14 fixes this issue.

### Reproduction steps

1. Startup a SnipeIT container with tag `v6.1.0`.
2. Go to the edit user page for a user
3. Click advanced
4. Try changing e.g. the location for a user. The select box will remain empty and a 401 will appear in the network console of your browser

### Expected behavior

The selectbox content should have been shown in the selectbox, as it does in 6.0.14.

### Snipe-IT Version

6.1.0

### Operating System

Docker on Ubuntu

### Web Server

Apache2 (build-in in SnipeIT docker image)

### PHP Version

Default for SnipeIT docker image

### Error messages

```shell
There is no error message in the logs or in stderr, other than a 401 response: "Unauthorized or unauthenticated" in the failed response
```

### Additional context

I am running SnipeIT in Docker. the setup was migrated from a few versions back, but all migrations ran fine. All else seem to work well, except for this issue, which we only noticed a few weeks after upgrading to 6.1.0.

We have been testing with editing the permissions for the users, adding them to a permission group, overriding the admin rights with dedicated rights per user, but nothing fixed it or changed the behavior. 

Downgrading to 6.0.14 fixed the issue for us.

**Comment by marcusmoore** [comment]
@marknijboer I'll look into this. It shouldn't matter since you're a superadmin but do you have Full Company scoping enabled?

**Comment by marcusmoore** [comment]
Sorry, `scoping` is the technical term. `Full Multiple Companies Support` is the setting (`/admin/settings`) I'm talking about.

**Comment by marcusmoore** [comment]
Typing out loud using Location on the user page: If the [`$this->authorize('view.selectlists');`](https://github.com/snipe/snipe-it/blob/64256351d86773b97aec4688853a6cc7feb040d4/app/Http/Controllers/Api/LocationsController.php#L255) call fails, which can be manually triggered by returning false from the [`before`](https://github.com/snipe/snipe-it/blob/23a1b2d60ae6e536924c0773278b5768c4e0a414/app/Providers/AuthServiceProvider.php#L101-L105) and [`view.selectlists`](https://github.com/snipe/snipe-it/blob/23a1b2d60ae6e536924c0773278b5768c4e0a414/app/Providers/AuthServiceProvider.php#L206-L223) sections in `AuthServiceProvider` the network request will fail with a 403 and not a 401.

Since getting a 401 means the user cannot be authenticated and I'm not having this issue as a superadmin using Valet. Did our docker configuration change apache's configuration? 🤔

**Comment by marcusmoore** [comment]
@marknijboer could you do me a favor and inspect the failed request in the console. Is `X-Csrf-Token` included in the request's headers?

**Comment by Dad-Ju** [comment]
@marcusmoore 
we do have the same issue but with a 403! could you assist us with that? no normal User can edit its Location.
#13269

**Comment by marcusmoore** [comment]
@Dad-Ju we chatted in the issue but for anyone else that is curious: it should be fixed with #13310.

@marknijboer I hope your issue is solved as well. I'm going to close this but feel free to ping me here if it should be re-opened.

**Comment by marknijboer** [comment]
@marcusmoore 
I'm sorry for not following up on my issue before. Unfortunately the problem was still bugging me up until the latest version. I just found out that the issue was due to a configuration error on my end. On HTTP the application worked fine, but on HTTPS it did not. I found this out a few days ago which lead me into debugging what could make that happen.

It appears that none of the necessary cookies were sent to the backend at all on HTTPS. The `APP_URL` setting was misconfigured on my side to the non-https version instead of using https: `http://<domain>` instead of `https://<domain>`, while the app was only accessed via HTTPS. The whole application worked, except for the selectlist-endpoints. Changing this protocol for the `APP_URL` fixed the error.

Again, I'm sorry for not being cooperative before, but let me post my solution here for your knowledge or anyone else who has the same problem.

**Comment by marcusmoore** [comment]
@marknijboer no problem! Glad you got it working 😄

**Comment by awnz** [comment]
Thanks for posting your solution @marknijboer! APP_URL in .env was what it was for me too.

**Comment by awnz** [comment]
@marcusmoore could checking APP_URL perhaps be added to the list of things to check over in the installation troubleshooting section at https://snipe-it.readme.io/docs/installation-issues?

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by snipe** [comment]
@awnz It already tries to warn you in the app logs, and the quickstart and upgrader also try to warn you.
