### ISSUE TITLE
[Feature Request]: user self - audit feature

### ISSUE THREAD

**Issue by BlackRen771103** [grokability/snipe-it#13106]
### Is your feature request related to a problem? Please describe.

we want to make use audit their assigned devices, etc by login Snipe-it OR email but for now seems can not achieve this.

### Describe the solution you'd like

now snipe-it have user permission settings，but if i try to assigned audit to user，they will have full audit access for all the audit devices ，if they can only see their own would be great

**Comment by snipe** [comment]
This is already under development

**Comment by BlackRen771103** [comment]
wow , that would be great ,is there any online date or plan?
