### ISSUE TITLE
Updating from 6.0.14 to 6.1.0 caused null columns in action_log table

### ISSUE THREAD

**Issue by dritter9** [grokability/snipe-it#13116]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Updating snipe-it from 6.0.14 to 6.1.0 will null out following columns in action_log table:
- user_id
- target_id
- target_type
- company_id
- action_id
Also timestamps updated_at, created_at and action_date will be set to now

### Reproduction steps

1. Changed Docker Image Tag from v6.0.14 to 6.10
2. Container re-create

I've also tried the following:

1. Checked the migrations shown by 'php artisan migrate'
2. Stopped docker container with v6.0.14
3. Dumped MySQL database
4. Uppgraded docker image tag from v6.0.14 to 6.10
5. Dropped database and restored it from dump (action_log is now complete / expected behaviour)
6. Running 'php artisan migrate' now will set columns to null/now

### Expected behavior

Columns are not null/now

### Screenshots

Running php artisan migrate in v6.1.0
![image](https://github.com/snipe/snipe-it/assets/60943273/c34cc108-6f08-4379-a302-98fb25eef7a3)

Action log view at dashboard
![image](https://github.com/snipe/snipe-it/assets/60943273/426db420-6e37-4d13-b2de-527b57ae6717)

action_log table
![image](https://github.com/snipe/snipe-it/assets/60943273/349989da-29aa-4753-be6c-1f3adac3e1c4)

Docker stdout
![image](https://github.com/snipe/snipe-it/assets/60943273/8b6047cf-7f44-4d2c-8e8a-1ad95b820ab3)

### Snipe-IT Version

v6.1.0 build 10161 (ga8ca3ad2a)

### Operating System

Docker

### Web Server

Docker (Apache2)

### PHP Version

7.4.3-4ubuntu2.18

**Comment by snipe** [comment]
There's nothing in those migrations that would null out those fields that I am aware of. (You can look at them yourself.)

@marcusmoore Any ideas?

**Comment by marcusmoore** [comment]
Hi @dritter9 

Do all of the rows have the columns you indicated nulled out? There is a [migration](https://github.com/snipe/snipe-it/blob/1b9c3c93ad48606e60b6fa4e31cc7b139b96476a/database/migrations/2023_01_21_225350_add_eol_date_on_assets_table.php) that updates assets by adding an EOL date which causes new entries in the log to be added but they are appended to the asset's history:
<img width="873" alt="Updated history" src="https://github.com/snipe/snipe-it/assets/1141514/f1a72b0c-fc26-49e2-9f83-7b37d9b1a36f">
> (This asset is from the app's seeders and not real data)

Can you confirm sorting the table by `created_at` or `id` shows you the expected data? 

Also, you mention `action_id` as a column that was nulled out. Was that a mistake? The column doesn't exist on the table.

**Comment by dritter9** [comment]
Hi @marcusmoore 

Thank you for this helpful hint. You're right, not every row is "nulled" out. Since the migration calculates the date foreach asset by it's model and then performs an update on the asset, this event is logged in `action_logs` table. Because this is performed by system, it don't shows an admin in the log.

Sorry it's my fault for not looking at the last page from log :(
Everything is and was fine, issue can be closed

**Comment by marcusmoore** [comment]
No worries! Glad to hear everything is good 👍🏾 😄
