### ISSUE TITLE
[Feature Request]: Adding other warranty checker links

### ISSUE THREAD

**Issue by yetanothersys-admin** [grokability/snipe-it#13117]
### Is your feature request related to a problem? Please describe.

No, not related to a problem.
Our company just noticed the support of Apple products having the "Apple" icon that goes to the warranty check site

### Describe the solution you'd like

Support for other manufacturers like HP, Dell and other well known ones maybe when people would need it for manufacturer XYZ.

### Additional context

A co-worker noticed the small Apple icon appearing in the asset view of an iPhone and was positively surprised that a feature like that was made to keep track of the warranty.
Another co-worker pointed out that it hasn't been implemented for other manufacturers as it seems...
I looked up warranty check issues and I've read this one https://github.com/snipe/snipe-it/issues/7326 - we were happy to see other people also mention that they would like support for that... but since it has been closed I don't think this will be implemented for other manufacturers?

**Comment by snipe** [comment]
This was already addressed in #12932. If you update to latest on master, you should see the dynamic link format.

**Comment by yetanothersys-admin** [comment]
Ah - didn't see that, thanks!
