### ISSUE TITLE
Unable to checkout single component

### ISSUE THREAD

**Issue by KMTMark** [grokability/snipe-it#13112]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

**Using hosted Snipe-IT so can't actually enable Debug mode!**

Unable to checkout components to asset - Gives an error that it wouldn't leave enough components remaining even when that field for  Min. Qty. of this component is unset (blank).

This has worked in the past as I have dozens of HDD checked out to various servers, so possibly introduced with 6.1.0?

### Reproduction steps

1. Create a component, enter 1 for quantity and leave Min. Qty. box blank 
2. Attempt to checkout that component to an asset
3. Receive above mentioned error!
...

### Expected behavior

The component should be checked out to the server

### Snipe-IT Version

6.1.0

### Operating System

Cloud Hosted

### Web Server

Cloud Hosted

### PHP Version

Cloud Hosted

### Operating System

Mac

### Browser

Chrome

### Version

114

### Error messages

```shell
Error Not enough components remaining: 1 remaining, 1 requested

Not reproducible on the demo instance
```

### Additional context

Our Snipe-IT installation is hosted via Grokability.

I tested both trying to checkout a newly created component to an asset and an existing one - neither worked, giving the error above.

This DID however work on the demo instance (6.1.1pre)

**Comment by Godmartinz** [comment]
Hi @KMTMark please email [support@snipeitapp.com](mailto:support@snipeitapp.com) and mention your hosted URL in the email. I think a quick update to your instance will solve your issue.
