### ISSUE TITLE
[Feature Request]: Features needed

### ISSUE THREAD

**Issue by ahmed26399** [grokability/snipe-it#13121]
### Is your feature request related to a problem? Please describe.

Hello,
I am doing a comparative study about open source assets management system.I am very interested in your system. I have some requested features, I would like to know if they are present in SNIPE-IT:

### Describe the solution you'd like

In software and license management features, I want to know if your system ensures those functionalities:
1 Check compliance - licenses acquired vs licenses consumed
2 Manage licensing modes by configurable rules
3 Manage activation keys and track usage
4 Produce customizable reports (via query)
5 Manage licensing automatically
6 Manage license decommissioning automatically
Furthermore, I would like to know if your system ensures those functions.
7 Asset financial data referencing
8 Maintenance contract management features
9 Desktop Inventory Agents Included
10 Server inventory agents included
11 Interconnection to existing inventory agents
12 Stock management
13 Loan management
14 Massive export of TXT/ PDF/ XML/FTPS data
15 Filtered Data Exports
16 Creation, customization of dashboards

Thanks in advance

**Comment by snipe** [comment]
We do not have most of these features, unfortunately

**Comment by ahmed26399** [comment]
Hello again,
I want to know if I can order a paid custom development from the team? I want to know also the custom functionality can be reversed in Open source ?
thanks in advance
