### ISSUE TITLE
Snipe-IT 6.1.0 on XAMPP license page error

### ISSUE THREAD

**Issue by alokkmohan** [grokability/snipe-it#13128]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

when i click on http://localhost/licenses/ the index page is opened , Please help 
![screencapture-localhost-licenses-2023-06-07-13_42_07](https://github.com/snipe/snipe-it/assets/97098372/dd760d04-328f-4bcd-afca-320967229026)

### Reproduction steps

when i click on http://localhost/licenses/ the index page is opened , Please help 
![screencapture-localhost-licenses-2023-06-07-13_42_07](https://github.com/snipe/snipe-it/assets/97098372/dd760d04-328f-4bcd-afca-320967229026)

### Expected behavior

Open license page

### Snipe-IT Version

Local hosy

### Operating System

Windows 

### Web Server

Apache

### PHP Version

8

### Error messages

```shell
[Wed Jun 07 12:31:16.661316 2023] [ssl:warn] [pid 12384:tid 340] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jun 07 12:31:16.697060 2023] [mpm_winnt:notice] [pid 12384:tid 340] AH00354: Child: Starting 150 worker threads.
```

**Comment by Tharrington86** [comment]
@alokkmohan Did you follow the steps to remove the built in alias for `/licences`? [This link](https://snipe-it.readme.io/docs/xampp) should help you.

**Comment by alokkmohan** [comment]
Thanks . Now working
