### ISSUE TITLE
[Feature Request]: Edit dashboard view

### ISSUE THREAD

**Issue by GuyAzulay13** [grokability/snipe-it#13120]
### Is your feature request related to a problem? Please describe.

Not a problem

### Describe the solution you'd like

I'd like it if it would be possible to edit the dashboard (looked for similar requests and didn't find a relevant solution)
is there a way to view the dashboard as "like" finance view? as in numbers, sums, costs etc.

**Comment by snipe** [comment]
Duplicate of #7297
