### ISSUE TITLE
[Feature Request]: Update to Laravel 10

### ISSUE THREAD

**Issue by fredlahde** [grokability/snipe-it#13125]
### Is your feature request related to a problem? Please describe.

Laravel 8 is EOL since July 26th, 2022 and only got security fixes until January 24th, 2023.

When I read the composer.lock, Snipe-IT still uses Laravel 8. 

This poses a potential security risk based on the lack of security updates

### Describe the solution you'd like

Update Snipe-IT to use Laravel 10. This relaese will get security updates until Feburary 4th, 2023

### Describe alternatives you've considered

It'd be also possible to move to Laravel 9, which will get security updates until February 6th, 2024

**Comment by snipe** [comment]
This is already planned for v7.
