### ISSUE TITLE
Activity Report Changed report

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13137]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

![Screenshot 2023-06-08 at 11 10 53 am](https://github.com/snipe/snipe-it/assets/114973646/953697bd-42c6-485f-8c9e-6d066c5356da)

Activity Now showing up like this with _snipeit_ instead of the naming conventions

### Reproduction steps

1.Home Screen
2.Click on Recent Activity  
3. Click on View All
4. In Changed Area, Layouts now different as per picture

### Expected behavior

Should be Naming Conventions of Things changed

### Snipe-IT Version

v6.1.1-pre build 10727 (gf1b4bba3a) 

### Operating System

Ubuntu

### Web Server

apache

### PHP Version

8.1.19

**Comment by snipe** [comment]
I don't really understand what's different based on the screenshots. Can you clarify?

**Comment by jayavman** [comment]
hi @snipe 

Instead of _snipe_it_Mac_address - Shouldn't it just be Mac Address
_snipe_it_Ip_address - Shouldn't it be just Ip Address
_snipe_it_Asset_Condition - Shouldn't it just be Asset Condition 
and so on?

**Comment by snipe** [comment]
We track the field names and their changes, so no, this is behaving as expected
