### ISSUE TITLE
[Feature Request]: Requestable Products

### ISSUE THREAD

**Issue by gokbuluterdogan** [grokability/snipe-it#13132]
### Is your feature request related to a problem? Please describe.

We have to reject the products because some of our users have requested them.

### Describe the solution you'd like

Adding a reject button for the requested products.

**Comment by sweetkid169** [comment]
I would like to expand upon this, and ask it be possible to make accessories and consumables requestable also. Along with the OP item.

**Comment by snipe** [comment]
You can use the "cancel" button in `/hardware/requested`

<img width="452" alt="Screenshot 2023-09-15 at 4 03 24 PM" src="https://github.com/snipe/snipe-it/assets/197404/532020fd-abd4-4475-b2c0-4804f38513d2">
