### ISSUE TITLE
[Feature Request]: Initiate LDAP Sync through API or based on schedule 

### ISSUE THREAD

**Issue by oferzern** [grokability/snipe-it#13133]
### Is your feature request related to a problem? Please describe.

Not related to product problem

### Describe the solution you'd like

Today, LDAP Sync can only be initiated manually, and we're working to fully automate our user creation across all platforms to minimize manual work.

The best option is to make the LDAP sync automatically based on the schedule we can set.

The other option I've been thinking about is to add an API endpoint to allow us to initiate the LDAP sync with an API call (and then I'll add this call to our automation flow).

**Comment by uberbrady** [comment]
You *can* run the LDAP sync periodically, using Cron (on Unix) or using Windows Task Scheduler.

You need to run `php artisan snipeit:ldap-sync` - and then that should do what you want. (There are some command-line options, but if you want to just replicate an LDAP sync button-push, this will do it.)

**Comment by oferzern** [comment]
Thanks @uberbrady 
Is it also supported with the hosted site? Or only on self hosting?

**Comment by uberbrady** [comment]
Yes, it supported on the hosted site. We try very hard to make it so that there's never anything you can only do on self-hosting, but not with our hosted service. With standard hosting, you can sync up to 4 times a day. You can get more details from support@snipeitapp.com

**Comment by oferzern** [comment]
Thanks!
