### ISSUE TITLE
Random hangs

### ISSUE THREAD

**Issue by Sc00by121** [grokability/snipe-it#13146]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We have been using Snipe for around a 6months mostly on version 6.0.14.  I upgraded to 6.1.0 where our problem still persists

Ever since install we are finding that while fast and responsive the site will randomly hang at any point whether it's at the login page or within Snipe.  It can hang for 15-20 seconds then continue on as normal, never gives an error or times out, it'll always display the page.  It will do this around once every 5-10minutes.  All other times its fast and responsive

I've enabled debug mode and this shows the page execution time being high but I can't work out how to then drill down to the actual problem.  It feels like a config issue.  We're using IIS and Mysql.  Mysql is on a different server but on the same physical network.  We have around 10 other websites that run off the same IIS server and Mysql and none of these have any issues.

### Reproduction steps

1.  Use the site as normal.  Nothing specific triggers it so unable to pin point an actual 

### Expected behavior

Fast and responsive without random 15+second hangs

### Snipe-IT Version

6.1.0

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.0

### Operating System

Windows

### Browser

Chrome

### Version

114

**Comment by uberbrady** [comment]
Do you have anything that is 'health-checking' the server? I'm wondering if those lags are somehow because it's trying to do session clean-up and there are a lot of them, because you're doing some kind of high-frequency health-check that creates a session (and, thus, a session-file). Just one weird theory to start to check on.

**Comment by Sc00by121** [comment]
Nothing at all.  Been trying to trace this down and can't get to the bottom of it.  There are 11 other websites that are hosted on the same server, majority linking to the same MySQL server and they are operating fine.

What I'm not sure about is the debug mode in snipe.  With this enabled I can see the execution time being high when it hangs but I'm struggling to then dig through all of the debug tabs to pin point why

**Comment by uberbrady** [comment]
Check your sessions directory - `storage/framework/sessions` - are there a ton of files in there?

**Comment by Sc00by121** [comment]
8 files in there at the moment. Oldest being first thing yesterday morning. On loading snipe just now it hung simply launching the base url. One of the session files updated when it finally loaded

**Comment by devvonmonahan** [comment]
Open up developer tools & go to the network tab ([here's a write-up for chrome](https://developer.chrome.com/docs/devtools/network/))\
Then keep using Snipe-IT until it freezes, take note/save the results. Do it again until it happens next time - I wonder if you'll be able to find any similarities between the two occurrences or if there will be something obvious sticking out?

**Comment by snipe** [comment]
Also tail the application and PHP logs while the freezing is happening. It could be trying to write a bunch of log/error lines in for some reason and that could be slowing things down.

Are you the only one using the system primarily or are there others as well?

**Comment by eddriesen** [comment]
Hi I'm in pretty much the same boat. Will do an extensive search and report back asap.

**Comment by Sc00by121** [comment]
Sorry for long delay in replying.  Around 8 of us using the system but generally just one at a time.  No issues in any logs that I can see

Glad to see someone else having similar issue.  We're still suffering with it.

**Comment by snipe** [comment]
I still don’t really have an answer for you here. We host thousands of Snipe-IT instances and haven’t run into this (unless someone has LDAP login set up and there’s some weird DNS mangling that causes a delay). If I can’t reproduce it, I can’t fix it :(

**Comment by eddriesen** [comment]
I'm looking toward the gravatar thumb.
Working with the developer network pane open, I notice that the gravatar icon sometimes takes _**very**_ long to load! (http://gravatar.com/avatar/46df2d541d6f125a585b563bcdf7555a) , it states "ns_binding_aborted" . however. While testing, the problem kinda resolved itself?? (browser says "cached")

I've fiddled to much in firefox' about:config to come with a definite fix (https_only stuff, etc...), but I keep looking out when it reappears. Also snipe-it is internally dockerised and accessed over **http**.

So a lot and nothing. I might be barking up the wrong tree since I can't re-enable the timeouts. 

@snipe, thanks for saying hi! When I can reproduce it failing & working, I will come up with a definitive report.

**Comment by bootsie123** [comment]
I'm running into the same issue as well on a fresh install (v6.1.2). It was fine in my testing but for some reason I'm experiencing this after deploying it to a VPS in Linode. Anyone make any progress on trying to determine the core issue?

**Comment by Sc00by121** [comment]
We're still having issues and just persevering.  It seems, to me anyway, a difficult one to pin point as it's so often random

**Comment by snipe** [comment]
In your `settings` table, what do you have as a value for `load_remote`?

**Comment by bootsie123** [comment]
When you say the `settings` table, are you talking about the `.env` file?

**Comment by snipe** [comment]
No, the settings database table

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
