### ISSUE TITLE
PHP session cleanup

### ISSUE THREAD

**Issue by 3apa3a-b-ta3e** [grokability/snipe-it#13150]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After installing Snipe-IT using official docker image I found that after several days my K8s cluster monitoring started to complain about free inode on Snipe-IT's Persistent Volume where PHP sessions are stored. I connected to pod and executed
`find storage/framework/sessions/ -type f | wc -l`
that gave me a huge number like **100k** or even more.
After more digging I saw there a sessions files with deploy creation date which leads me to conclusion that something is broken in (Laravel?) Garbage Collector mechanism.

### Reproduction steps

1. Deploy the service to K8s cluster using Heml chart from https://github.com/t3n/helm-charts
2. Wait for several days
3. `storage/framework/sessions/` is overflowing with session files
4. App is showing 500 error

### Expected behavior

Default Garbage Collector mechanism flush older session after configured timeout

### Snipe-IT Version

6.1.0

### Operating System

Ubuntu 20.04.5 LTS

### Web Server

Apache

### PHP Version

7.4.3-4ubuntu2.18

**Comment by uberbrady** [comment]
So we have a health-check endpoint that we made specifically for Kubernetes users (who seem to very aggressively health-check us) - `/health` - which should still show you whether or not the app is up, but without creating a bunch of unused sessions. Can you give that a shot?

**Comment by 3apa3a-b-ta3e** [comment]
Yep, seems like you're right and that was it.
Lemme observe my installation for a few hours so I could say for sure.

**Comment by 3apa3a-b-ta3e** [comment]
Yep, thank you so much for pointing me to the right direction!
