### ISSUE TITLE
mysqldump: Couldn't execute 'FLUSH TABLES WITH READ LOCK'

### ISSUE THREAD

**Issue by 3apa3a-b-ta3e** [grokability/snipe-it#13155]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm not sure is it a Bug Report or Feature Request, because I already know the reason of this error and also can offer some workaround.

So our system is using **Amazon RDS** as a database for Snipe-IT, everything is good there except we cannot backup the Snipe-IT installation using build-in backup page — attempt to Generate Backup is showing us an error:

`Error Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Couldn't execute 'FLUSH TABLES WITH READ LOCK': Access denied for user 'snipe_it'@'%'`

which is not a big surprise since [Amazon RDS master user doesn't have **SUPER** privileges](https://repost.aws/knowledge-center/mysqldump-error-rds-mysql-mariadb).

Would it be somehow possible to remove `--master-data` option from the list of **mysqldump** parameters or it's absolutely required there?
Or make it optional.

### Reproduction steps

1. Connect Snipe-IT with Amazon RDS MariaDB.
2. Open `/admin/backups` page
3. Press **Generate Backup** button

### Expected behavior

Backup file is prepared and downloaded

### Snipe-IT Version

6.1.0

### Operating System

Ubuntu 20.04.5 LTS

### Web Server

Apache

### PHP Version

7.4.3-4ubuntu2.18

**Comment by marcusmoore** [comment]
Hi @3apa3a-b-ta3e,

I think removing the `--master-data` flag would have to happen in the upstream packages ([spatie/laravel-backup](https://github.com/spatie/laravel-backup) and/or the underlying [spatie/db-dumper](https://github.com/spatie/db-dumper)) but even if it was included there I don't think it is something we can easily utilize since the page you linked says 

> To resolve this error, remove the --master-data option. When you remove this option, you aren't given an exact log position in the mysqldump. To work around this issue, either take the mysqldump when your application is stopped, or take the mysqldump from an Amazon RDS read replica.

I take that to mean we would need to make sure the application is not writing anything to the database while the backup is being run which is tricky. Unfortunately, it's much easier to let mysqldump handle that for us.

**Comment by 3apa3a-b-ta3e** [comment]
Would it be possible to optionally exclude database from build-in web interface backup (since we handle those db backups from AWS side anyway), only leaving plain files?

**Comment by marcusmoore** [comment]
@3apa3a-b-ta3e I think you can get backups working by not using the master user (the [AWS docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.MasterAccounts.html) recommend against using the master user directly in applications) and instead creating/using another database user that has permission to lock the tables.

Unfortunately, we don't have any current plans to allow backups to exclude the app's database. I think it's best to have the backup include everything needed to do a restore and not have to worry about the database and assets being backed up at different times and thus being potentially out of sync.
