### ISSUE TITLE
[Update Custom Field via APIN Snipe IT]: 

### ISSUE THREAD

**Issue by SmileyWP** [grokability/snipe-it#13162]
### Is your feature request related to a problem? Please describe.

I want to update or delete a unique field value via API, the program runs without error, but the value is still not entered into the database

### Describe the solution you'd like

I am attaching the code, does anyone see the error in it?

import requests
import json

def update_asset(serial_number, amount):
    url = 'http://snipe-it-domain.com/api/v1/hardware'
    api_token = 'your-api-token'

    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {api_token}'
    }

    # Először lekérjük az eszközt a sorozatszám alapján
    params = {'search': serial_number}
    response = requests.get(url, headers=headers, params=params)
    data = response.json()

    # Ellenőrizzük, hogy találtunk-e eszközt
    if response.status_code != 200 or data['total'] == 0:
        print(f"Nem található eszköz a(z) {serial_number} sorozatszámmal.")
        return

    # Frissítjük a számlázandó összeget az eszközön
    asset_id = data['rows'][0]['id']
    payload = {
        'custom_fields': {
            'Bruttó számlázandó összeg': {
                'value': str(amount)
            }
        }
    }
    update_url = f"{url}/{asset_id}"
    update_response = requests.patch(update_url, headers=headers, data=json.dumps(payload))

    if update_response.status_code == 200:
        print(f"A(z) {serial_number} sorozatszámú eszköz számlázandó összege frissítve lett.")
    else:
        print(f"Hiba történt a(z) {serial_number} sorozatszámú eszköz számlázandó összegének frissítése közben.")

# Felhasználó által bekért adatok
serial_number = input("Kérem adja meg az eszköz sorozatszámát: ")
amount = input("Kérem adja meg a számlázandó összeget: ")

# Hívjuk meg a függvényt a megadott adatokkal
update_asset(serial_number, amount)

**Comment by snipe** [comment]
You need the db field name, not the name itself. https://snipe-it.readme.io/reference/hardware-update

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/hardware-update">/hardware/:id</a></strong></div><div>Updates a specific asset</div></blockquote>
