### ISSUE TITLE
Signature doesn't show up in History

### ISSUE THREAD

**Issue by nandorusrin** [grokability/snipe-it#13188]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I accept asset with signature but the Signature don't show up in History.

### Reproduction steps

1. Accept Asset with signature
2. Go to Asset History in Asset Details>History
3. Signature doesn't show up in history for checkout

### Expected behavior

1. Accept Asset with signature
2. Go to Asset History in Asset Details>History
3. Signature show up in history for checkout

### Snipe-IT Version

v6.1.1-pre build 10653 (g11cd875c6)

### Operating System

Windows

### Web Server

Apache

### PHP Version

7.4.33

**Comment by snipe** [comment]
I'm unable to reproduce this locally or on the demo.

<img width="1701" alt="Screenshot 2023-07-06 at 11 36 40 AM" src="https://github.com/snipe/snipe-it/assets/197404/7b728685-7caf-4d71-9498-75059f8e365a">
<img width="1196" alt="Screenshot 2023-07-06 at 11 36 50 AM" src="https://github.com/snipe/snipe-it/assets/197404/a1c0eeaa-acdf-472f-a471-ea3be9e2689f">
