### ISSUE TITLE
[Feature Request]: Indonesian Language

### ISSUE THREAD

**Issue by dimaszulfa** [grokability/snipe-it#13180]
### Is your feature request related to a problem? Please describe.

I want the snipe it application to have an Indonesian language feature to make it easier to operate

### Describe the solution you'd like

language change feature

**Comment by jayavman** [comment]
<img width="1218" alt="Screenshot 2023-06-26 at 10 52 18 am" src="https://github.com/snipe/snipe-it/assets/114973646/21d8ccc3-584b-420b-baa4-e8eac81ad039">
