### ISSUE TITLE
HTTP/500 errors after upgrade to v6.1.1

### ISSUE THREAD

**Issue by vapier** [grokability/snipe-it#13187]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

after running `php upgrade.php v6.1.1`, browsing any page hits http/500 errors.  running `php upgrade.php v6.1.0` and everything works.

### Reproduction steps

1. `php upgrade v6.1.0` -> works
2. `php upgrade v6.1.1` -> visit website and fails
3. `php upgrade 11cd875c6d70569538883e00caa681686ac91b77` -> works
4. `php upgrade 3fb51880375a54d1b6baacece70baff584810da2` -> fails

### Expected behavior

no crashes please

### Snipe-IT Version

v6.1.1

### Operating System

Debian 12 (bookworm)

### Web Server

Apache 2.4.57-2

### PHP Version

8.2.5-2

### Error messages

```shell
Error thrown with message "Class "Laravel\Socialite\SocialiteServiceProvider" not found"

Stacktrace:
#9 Error in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208
#8 Illuminate\Foundation\ProviderRepository:createProvider in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:144
#7 Illuminate\Foundation\ProviderRepository:compileManifest in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:61
#6 Illuminate\Foundation\ProviderRepository:load in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:659
#5 Illuminate\Foundation\Application:registerConfiguredProviders in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:17
#4 Illuminate\Foundation\Bootstrap\RegisterProviders:bootstrap in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:237
#3 Illuminate\Foundation\Application:bootstrapWith in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:153
#2 Illuminate\Foundation\Http\Kernel:bootstrap in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:137
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/snipe-it/public/index.php:51
```

### Additional context

this install has been running for a few years and upgrading as new releases come out

**Comment by snipe** [comment]
Per our official docs, Snipe-IT v6.x.x does not and will not work with php 8.2. You’ll want to downgrade to 8.1. 

The upcoming v7 of Snipe-IT will fully support 8.2.

**Comment by vapier** [comment]
if you don't want to support 8.2 with current releases, that's fine, but "just downgrade PHP" is not realistic. that's not how Linux distros work.

6.1.0 is working with 8.2 already, at least for my usage, so I'll just stick with that.
