### ISSUE TITLE
Problem when sorting by model number

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#13199]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Good afternoon. When sorting by model number, all data disappears from view. This is not a problem with my installation, as it is reproduced on your demo site.

### Reproduction steps

1. Opening the manufacturer
2. I put the display of the model number (if disabled for viewing)
3. I click sort by model number
4. All displayed data disappears

### Expected behavior

Sorting should work

### Screenshots

![1](https://github.com/snipe/snipe-it/assets/48224568/5c7564a1-1ca5-44fc-a3b9-56650f551dec)
![2](https://github.com/snipe/snipe-it/assets/48224568/f74799cd-b4e8-480d-93eb-00d95d3f9e87)
![3](https://github.com/snipe/snipe-it/assets/48224568/39caf2bb-1288-4505-8069-68b8789edbf0)

### Snipe-IT Version

6.1.1

### Operating System

Official demo site

### Web Server

Official demo site

### PHP Version

8.0.28

### Browser

All

### Version

Last

### Additional context

Official demo site.
Just today I ran into a problem on my installation, version 6.1.0. I decided to check on the official demo site. There is a similar problem on the official demo site with version 6.1.1.

**Comment by snipe** [comment]
This has been resolved on master
