### ISSUE TITLE
Bulk Checkin from Deleting User doesn't show what was checkedin

### ISSUE THREAD

**Issue by kbrown900** [grokability/snipe-it#13195]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When deleting a user and using bulk checkin/delete user it checks in the items, but the recent activity log doesn't show the accurate information. The correct history does show within the deleted users history however. 

### Reproduction steps

1. Select User
2. Select "Checkin All/Delete user"
3. Select "Soft Delete User"
4. Select "Ready to Deploy" Status
5. Click Submit
...

### Expected behavior

View recent activity with the type and item listed for the bulk checkin.

### Screenshots

![bulk checkin for delete user issue](https://github.com/snipe/snipe-it/assets/74275228/c332894b-4097-44a2-b2b3-af4f8d5e1777)

### Snipe-IT Version

v6.1.1 - build 10847 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.11 

### Operating System

Windows 11

### Browser

Firefox

### Version

114.0.1 (64-bit)

### Additional context

Upgraded to v6.1.1 - build 10847 (master) yesterday, deleted user today. Not sure if related.

**Comment by snipe** [comment]
@inietov can you please take a look at this on Monday? Thanks!

**Comment by inietov** [comment]
I made `Checkin All / Delete User` for a lot of users and couldn't reproduce this issue. I'm thinking a data issue maybe?
