### ISSUE TITLE
[Feature Request]: Asset list

### ISSUE THREAD

**Issue by marcinBB8** [grokability/snipe-it#13209]
### Is your feature request related to a problem? Please describe.

Prloblem with fast editing Assets due to having to scroll horizontally to the last column to take Action.

### Describe the solution you'd like

Change (or set as an otion in config menu) location of Action column as a first one or to show it always on left and scroll only other colums.

**Comment by snipe** [comment]
You can click on the asset name or tag and get to a screen where you can edit.

**Comment by marcinBB8** [comment]
But only one, I'm writing about chose fiew of assets and edit them
