### ISSUE TITLE
[Feature Request]: Fieldset for category

### ISSUE THREAD

**Issue by marcinBB8** [grokability/snipe-it#13203]
### Is your feature request related to a problem? Please describe.

models in the same cattegory need same feldsets, that will by the same for all assets in that model

### Describe the solution you'd like

Add separate fielsets for category

**Comment by snipe** [comment]
This is not really on the long term roadmap, though it has been discussed in the past. Bulk editing models should allow you to quickly edit the fieldsets associated with a model
