### ISSUE TITLE
[Feature Request] Multiple Sets of fields

### ISSUE THREAD

**Issue by marcinBB8** [grokability/snipe-it#13202]
### Is your feature request related to a problem? Please describe.

It would be nice to add more than one set of fields to the model/type of asset.
Now I must create separate sets for every model and more of the fields is the same or similar. 
Problem apears when I must modyfy such subset of fields.

### Describe the solution you'd like

If there would be option to add more fieldsets, then i could grup fields, and modyfy them along all models.

**Comment by snipe** [comment]
That's unlikely to happen, but more recent versions of Snipe-IT make it easier to quickly add multiple fields to new/existing fieldsets.
