### ISSUE TITLE
License Management doesn`t Work

### ISSUE THREAD

**Issue by ElHeckos** [grokability/snipe-it#13204]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We updated our Snipe IT Windows Server to Version v6.1.1 build 10847 (g2ac4449ea)

Now we have a Problem with our licenses. 
We are unable to  edit, check out or add new licenses.

In previous versions it works without any problems. 
we don't get any error messages although we have switched on the debug mode.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Ø

### Screenshots

Ø

### Snipe-IT Version

v6.1.1 build 10847 (g2ac4449ea)

### Operating System

Windows 10

### Web Server

Apache

### PHP Version

8.1.17

### Operating System

Windows 10

### Browser

all

### Version

Ø

### Device

Ø

### Operating System

Ø

### Browser

Ø

### Version

Ø

### Error messages

```shell
none
```

### Additional context

Upgrade

**Comment by matt-jan** [comment]
Same here. Until I upgraded to the latest Version v6.1.1 - build 10847, I could manage licenses. Now I can't even create a new one and all I get is error 500

**Comment by ElHeckos** [comment]
Yes, we cannot create new ones

when signing in or out, we don't get an error message, the page just reloads and is in the same view

**Comment by marcusmoore** [comment]
Hello! Let's see if we can figure out what is going on.

@ElHeckos When you say you're not getting error messages do you mean in the UI? Can you please check to see if the browser or application has any relevant logs?

@matt-jan can you let me know what is in the application's logs? Are you running Windows as well?

Application logs will be in the `storage/logs/` directory. It's probably called `laravel.log`.

**Comment by ElHeckos** [comment]
Hey, we looked in Laravel ourselves and didn't find anything, here's the redacted log

in debug mode nothing can be found in the browser

[laravel.log](https://github.com/snipe/snipe-it/files/11872861/laravel.log)

many thanks for the help

**Comment by marcusmoore** [comment]
Thanks for sharing your log @ElHeckos. I noticed a lot of `unexpected token` in there and it looks like it is originating in a view. Can you run `php artisan view:clear` and see if that helps?

**Comment by matt-jan** [comment]
@marcusmoore I updated snipeit today and my laravel log is from 5th June so there's nothing there. I also noticed that I get 500 error when I try to open "People" tab as well as "Consumables", "Reports" and "Requestable". 
And my instance is docker one with Ubuntu 20.04

**Comment by marcusmoore** [comment]
@matt-jan 500 hm...errors should dump the stack trace to the application log but since you're using docker it's possible it is not configured to do that or doesn't have permission to write to the file. What is `LOG_CHANNEL` in your env set to? Are you using the official docker image?

**Comment by ElHeckos** [comment]
@marcusmoore 
Unfortunately, clearing the cache and view didn't help.

I ran php upgrade.php again, attached is the current log.

Unfortunately without success

[laravel.log](https://github.com/snipe/snipe-it/files/11873421/laravel.log)

**Comment by marcusmoore** [comment]
@ElHeckos can you provide the output of the upgrade script? It seems like it might be failing at some point.

**Comment by ElHeckos** [comment]
@marcusmoore 
Attached is the log from the php upgrade.php script
[snipeit Updatelog.txt](https://github.com/snipe/snipe-it/files/11878579/snipeit.Updatelog.txt)

**Comment by marcusmoore** [comment]
@ElHeckos hm...nothing really stands out in your upgrade output. I noticed this:

```
Package operations: 0 installs, 0 updates, 68 removals
```

Did you go from having your `APP_ENV` set to something other than `production` to `APP_ENV=production`? It doesn't really matter because in either case, subsequent runs of the upgrade script would make sure the correct dependencies were installed and shouldn't be causing any issues...

This could be a permissions issue. Maybe the storage directory isn't writable so new cached views and logs aren't appearing...

Can you double-check permissions? If you're running IIS on Windows 10 then [this docs page](https://snipe-it.readme.io/docs/windowsiis) should be helpful.

**Comment by ElHeckos** [comment]
ok, hmm...
We have adjusted the right one again. No change in error

we switched to windows because there were errors from the composer in debian.

maybe we'll change again and maybe continue with the composer mistakes :-D

what would be the best system for snipe in your opinion

**Comment by marcusmoore** [comment]
> We have adjusted the right one again

What do you mean here?

---

I'm bias because I prefer and have more experience hosting on unix based systems but we do support Windows. I'm curious what errors you experienced with composer in Debian?

**Comment by ElHeckos** [comment]
@marcusmoore 
We adjusted the right one more time

we're going to recreate the error today with debian and post it again

**Comment by ElHeckos** [comment]
hey @marcusmoore 

we have now again set up a test environment with Debian 11 and the following problem.

the authorizations for the user www-data are set, so we don't understand why there shouldn't be any access

[Snipe Debian 11.txt](https://github.com/snipe/snipe-it/files/11892808/Snipe.Debian.11.txt)

**Comment by marcusmoore** [comment]
@ElHeckos it looks like that log shows permission errors. You'll need to fix those before updating:

```
The following directories/files do not seem writable:
Backup failed because: mkdir(): Permission denied.
file_put_contents(/var/www/html/snipe-it/storage/framework/down): Failed to open stream: Permission denied
fatal: detected dubious ownership in repository at '/var/www/html/snipe-it'

etc
```

**Comment by ElHeckos** [comment]
Hm...

but we don't know why that is.
the user www-data has all rights and we have already tried it via root. still doesn't work

**Comment by snipe** [comment]
This isn't a bug with licenses as far as I can tell (and we didn't really change much in licenses recently anyway.)

According to your upgrade log, you didn't have git installed, so you'd have to have moved the files over manually. 

```
[previous exception] [object] (ParseError(code: 0): syntax error, unexpected token \";\", expecting \"]\" at C:\\xampp\\htdocs\\snipe-it\\app\\Models\\AssetMaintenance.php:82)
```

Can you show me what's on line 82 of `C:\\xampp\\htdocs\\snipe-it\\app\\Models\\AssetMaintenance.php:82`? That shouldn't affect licenses, but it certainly shouldn't be there.

**Comment by ElHeckos** [comment]
we have stored our own types of maintenance

```
public static function getImprovementOptions()
    {
        return [
            trans('Dell Hardware Tausch') => trans('Dell Hardware Tausch'),
            trans('Dell Geräte Tausch')      => trans('Dell Geräte Tausch'),
            trans('DigiDok Hardware')     => trans('DigiDok Hardware'),
            trans('DigiDok Software')     => trans('DigiDok Software'),
			trans('DD Fahrzeugausbau')      => trans('DD Fahrzeugausbau'),
            trans('DigiDok Sonstiges')     => trans('DigiDok Sonstiges'), 
            trans('IT Hardware')      => trans('IT Hardware'),
            trans('IT Software')     => trans('IT Software'),
			trans('IT Sonstiges')     => trans('IT Sonstiges'),
        ];
    }
```

**Comment by ElHeckos** [comment]
Hey @snipe 

we have installed git and performed the update again no change of the licenses possible.

[Neues Textdokument (6).txt](https://github.com/snipe/snipe-it/files/11905965/Neues.Textdokument.6.txt)

**Comment by snipe** [comment]
Still seeing a fatal error in there.

```
--------------------------------------------------------
STEP 6: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```

You can try resolving that this way:
https://komodor.com/blog/solving-fatal-not-a-git-repository-error/


<blockquote><img src="https://komodor.com/wp-content/uploads/2021/06/solving-fatal-not-a-git-repository.png" width="48" align="right"><div><img src="https://komodor.com/wp-content/uploads/2021/05/favicon.png" height="14"> Komodor</div><div><strong><a href="https://komodor.com/blog/solving-fatal-not-a-git-repository-error/">Solving “Fatal: Not A Git Repository” (Or Any Of The Parent Directories) Error Komodor</a></strong></div><div>The error fatal: not a git repository (or any of the parent directories): .git, states that you tried to execute a repository-specific command, outside of the Git repository. Fortunately, even if it is a very common problem, it is also very easy to solve.</div></blockquote>

**Comment by snipe** [comment]
What this usually means is that while git is installed, the Snipe-IT directory wasn't installed via git, so it cannot do git things within that directory. If you did a manual install of Snipe-IT but then installed git afterwards, it's not going to recognize Snipe-IT as a git repo. We have instructions on switching to a real git install here: https://snipe-it.readme.io/docs/switching-to-a-git-install

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/switching-to-a-git-install">Switching to a Git Install</a></strong></div><div>As we mention (several times) throughout the documentation, installing via Git is our recommended way of installing Snipe-IT and keeping it up to date. If you installed manually (downloading a tarball or .zip file from Github), you can still switch to a Git install with just a little work. Doing so ...</div></blockquote>

**Comment by ElHeckos** [comment]
@snipe 
very good
Many thanks now the installation or the update is running.

Unfortunately, the error remains that licenses cannot be edited in or out

here is the output from the installation again
[snipeit Updatelog.txt](https://github.com/snipe/snipe-it/files/11907699/snipeit.Updatelog.txt)

**Comment by snipe** [comment]
Nothing stands out in the upgrade. What's the 500 error in your app logs. (Please just tail the logs and paste the error here, I don't need to download files each time.)

**Comment by ElHeckos** [comment]
we never had a 500 error.

here are the errors from apache


```
[Thu Jun 29 17:12:12.201464 2023] [core:warn] [pid 7948:tid 400] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Jun 29 17:12:12.357715 2023] [mpm_winnt:notice] [pid 7948:tid 400] AH00455: Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.1.17 configured -- resuming normal operations
[Thu Jun 29 17:12:12.357715 2023] [mpm_winnt:notice] [pid 7948:tid 400] AH00456: Apache Lounge VS16 Server built: Mar  7 2023 13:21:03
[Thu Jun 29 17:12:12.357715 2023] [core:notice] [pid 7948:tid 400] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Thu Jun 29 17:12:12.357715 2023] [mpm_winnt:notice] [pid 7948:tid 400] AH00418: Parent: Created child process 404
[Thu Jun 29 17:12:13.404796 2023] [mpm_winnt:notice] [pid 404:tid 432] AH00354: Child: Starting 150 worker threads.
[Thu Jun 29 17:12:33.863567 2023] [authz_core:error] [pid 404:tid 1848] [client User IP:62944] AH01630: client denied by server configuration: C:/xampp/licenses/, referer: http://url.de/
[Thu Jun 29 17:12:52.584673 2023] [authz_core:error] [pid 404:tid 1852] [client User IP:62946] AH01630: client denied by server configuration: C:/xampp/licenses/172, referer: http://url.de/licenses
[Thu Jun 29 17:12:59.601839 2023] [authz_core:error] [pid 404:tid 1848] [client User IP:62947] AH01630: client denied by server configuration: C:/xampp/licenses/983, referer: http://url.de/licenses/172
[Thu Jun 29 17:13:02.942101 2023] [authz_core:error] [pid 404:tid 1836] [client User IP:62949] AH01630: client denied by server configuration: C:/xampp/licenses/983, referer: http://url.de/licenses/983/checkin
[Thu Jun 29 17:22:23.092097 2023] [authz_core:error] [pid 404:tid 1844] [client User IP:63053] AH01630: client denied by server configuration: C:/xampp/licenses/, referer: http://url.de/hardware
[Thu Jun 29 17:23:09.170198 2023] [core:warn] [pid 7328:tid 404] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Jun 29 17:23:09.279580 2023] [mpm_winnt:notice] [pid 7328:tid 404] AH00455: Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.1.17 configured -- resuming normal operations
[Thu Jun 29 17:23:09.279580 2023] [mpm_winnt:notice] [pid 7328:tid 404] AH00456: Apache Lounge VS16 Server built: Mar  7 2023 13:21:03
[Thu Jun 29 17:23:09.279580 2023] [core:notice] [pid 7328:tid 404] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Thu Jun 29 17:23:09.279580 2023] [mpm_winnt:notice] [pid 7328:tid 404] AH00418: Parent: Created child process 10200
[Thu Jun 29 17:23:10.326447 2023] [mpm_winnt:notice] [pid 10200:tid 416] AH00354: Child: Starting 150 worker threads.
[Thu Jun 29 17:23:11.013998 2023] [authz_core:error] [pid 10200:tid 1856] [client User IP:63064] AH01630: client denied by server configuration: C:/xampp/licenses/, referer: http://url.de/hardware
[Thu Jun 29 17:23:32.808842 2023] [authz_core:error] [pid 10200:tid 1856] [client User IP:63068] AH01630: client denied by server configuration: C:/xampp/licenses/172, referer: http://url.de/licenses
[Thu Jun 29 17:23:39.437099 2023] [authz_core:error] [pid 10200:tid 1848] [client User IP:63069] AH01630: client denied by server configuration: C:/xampp/licenses/983, referer: http://url.de/licenses/172
[Thu Jun 29 17:23:42.954942 2023] [authz_core:error] [pid 10200:tid 1856] [client User IP:63072] AH01630: client denied by server configuration: C:/xampp/licenses/983, referer: http://url.de/licenses/983/checkin
[Thu Jun 29 17:23:47.541288 2023] [authz_core:error] [pid 10200:tid 1856] [client User IP:63072] AH01630: client denied by server configuration: C:/xampp/licenses/983, referer: http://url.de/licenses/983/checkin
[Thu Jun 29 17:27:33.020812 2023] [authz_core:error] [pid 10200:tid 1820] [client User IP:63144] AH01630: client denied by server configuration: C:/xampp/licenses/, referer: http://url.de/
[Thu Jun 29 17:27:52.715444 2023] [authz_core:error] [pid 10200:tid 1840] [client User IP:63147] AH01630: client denied by server configuration: C:/xampp/licenses/172, referer: http://url.de/licenses
[Thu Jun 29 17:28:02.554557 2023] [authz_core:error] [pid 10200:tid 1820] [client User IP:63149] AH01630: client denied by server configuration: C:/xampp/licenses/983, referer: http://url.de/licenses/172
[Thu Jun 29 17:28:06.476548 2023] [authz_core:error] [pid 10200:tid 1840] [client User IP:63151] AH01630: client denied by server configuration: C:/xampp/licenses/983, referer: http://url.de/licenses/983/checkin
[Thu Jun 29 17:28:12.195692 2023] [authz_core:error] [pid 10200:tid 1820] [client User IP:63149] AH01630: client denied by server configuration: C:/xampp/licenses/983, referer: http://url.de/licenses/983/checkin
```

**Comment by snipe** [comment]
I'm not really sure what "We are unable to edit, check out or add new licenses." means then. What exactly is happening when you try?

**Comment by ElHeckos** [comment]
the page when output is reloaded and has the same view,
it is also not possible to edit an existing license, for example adding notes.
this is only for the licenses. example with the devices everything works as usual

**Comment by snipe** [comment]
@ElHeckos We're still unable to reproduce this locally or on the demo. Can you set your app into debug mode, and show me the info it reports back in the debugger, specifically the Session tab, under "Errors"?

https://snipe-it.readme.io/docs/advanced-debugging


<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/advanced-debugging">Advanced Debugging</a></strong></div><div>Snipe-IT ships with the Laravel Debugbar, an amazing piece of software that lets you introspect much further into the framework and application to troubleshoot issues that may be a little harder to track down.To enable the debugbar, set the following in your .env file, and clear your config cache:Te...</div></blockquote>

**Comment by ElHeckos** [comment]
we could solve the problem, I'll post instructions for that in the next few days if anyone has the same problem.  However, we switched to Debian 12 for performance reasons and were able to solve our composer problems there as well.



Many thanks for the support and above all for the wonderful program

**Comment by snipe** [comment]
So glad to hear you're sorted! I'll close this issue since your problem is resolved, but definitely feel free to add additional context to help other folks.
