### ISSUE TITLE
Custom field from user's list

### ISSUE THREAD

**Issue by bilias** [grokability/snipe-it#13221]
### Is your feature request related to a problem? Please describe.

In our university we would like to start using Snipe-IT for our inventory.

This is a problem we have, there might be a solution which I'm not aware off.

Example:
Let's say we buy a laptop (asset) from a program we run. The laptop "belongs" to a professor (user). He is in charge of the laptop. However the laptop is assigned and eventually checked out to a student.

Both the professor should be able to see all his program's assets, as well as the student should see that the specific laptop is assigned to him.

Is this possible in any way apart from messing with locations?

### Describe the solution you'd like

One way would be to create a custom field from pre-exists field values, like users' table in order to create the link between asset (user in charge / user checked out)

Somehow link the user's profile to that info.

**Comment by snipe** [comment]
There isn't currently a way to do that, but linked lists on assets has been something we've been toying with for a while. (It gets a little difficult with editing the fields though -ID 2 for example for a list of users would be pretty different than ID 2 for Departments, so if someone were to change the field type (from list of existing users from the users table to departments, for example), it could pretty profoundly change the reliability of the data.

**Comment by bilias** [comment]
Thanks for the reply.
