### ISSUE TITLE
Truncation of Large IDP Metadata in SAML IdP Metadata-field

### ISSUE THREAD

**Issue by hogemo** [grokability/snipe-it#13226]
### Debug mode

- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm encountering an issue with the SAML IdP Metadata-field when handling large IDP metadata files. Despite the metadata file from our IDP provider being valid, it's getting truncated to around 65,000 characters when I attempt to insert it into the SAML IdP Metadata-field. This behavior persists regardless of whether I directly paste the XML data or insert the URL linking to it. This truncation causes information loss and hinders proper function.

Possible solutions would be to increase the character limit of the SAML IdP Metadata-field.

Any assistance or suggestions on how to handle large IDP metadata files without truncation would be greatly appreciated. 
Thank you for your time and attention.

### Reproduction steps

1. Paste or insert URL to IDP metadata
2. Save (everything look good - green success message)
3. Looking back into the metadata text-field it is truncated, and when pressing save again, it is not possible because the xml is corrupt.
...

### Expected behavior

No truncating

### Snipe-IT Version

v6.1.1-pre - build 10653 (master)

### Operating System

Debian 11

### Web Server

Apache

### PHP Version

7.4.30

### Error messages

```shell
Below the metadata-field it says "The Metadata format is invalid." No error message found in debugger, nor in laravel.log.
```

**Comment by uberbrady** [comment]
I suspect the right solution here is to change to a larger TEXT blob format, probably with a migration.

**Comment by uberbrady** [comment]
`MEDIUMTEXT` ought to do it - that'll let you store up to 16MB of IdP metadata. If you want more than that, you're gonna have a bad time.

**Comment by hogemo** [comment]
> `MEDIUMTEXT` ought to do it - that'll let you store up to 16MB of IdP metadata. If you want more than that, you're gonna have a bad time.

Hmm okay, how would i do that? In the db?

**Comment by snipe** [comment]
@paegelow give me a few - I'll add a migration and then you can run the upgrade.

**Comment by snipe** [comment]
You should be able to run the upgrade script now and the field should be changed to a MEDIUMTEXT field

**Comment by hogemo** [comment]
> You should be able to run the upgrade script now and the field should be changed to a MEDIUMTEXT field

It worked! Really appreciate it!
