### ISSUE TITLE
Just updated with git pull and now the web page isn't working.....

### ISSUE THREAD

**Issue by cgibbsaces** [grokability/snipe-it#13239]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Just updated with git pull and now the web page isn't working.....

### Reproduction steps

1. Update
2. Then reboot
3. The page now just says "This page isn't working right now"
...

### Expected behavior

To be able to access the webpage

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/123769832/8aae246d-62e8-429a-b50f-8a34b5689314)

### Snipe-IT Version

Would love to tell you

### Operating System

Linux Ubuntu 20.04.2 LTS

### Web Server

Apache

### PHP Version

8

**Comment by snipe** [comment]
I'd need to know the details of the 500 error from your app logs and php logs

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
