### ISSUE TITLE
Pre-Flight Step 'Create Admin User' Loop

### ISSUE THREAD

**Issue by SunniTheSA** [grokability/snipe-it#13238]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Previous steps in Pre-Flight have completed successfully, but I have been unable to get past the "Create Admin User" page. Every time I complete the form and press "Next: Save User" the page simply refreshes, blanking all of the form responses with the exception of email address. There is no error generated in the debug bar/laravel error log, php www-error.log, or httpd log. The users table of mysql db is still empty. No email is generated with credentials.

### Reproduction steps

1. Complete installation and Pre-Flight steps 1 and 2
2. Completely fill out new Admin User form, populating all fields except "Prefix (Optional)"
3. Click "Next: Save User"

### Expected behavior

New admin user added to Users table, email with credentials sent, and progression in browser past Pre-Flight page to a log-in page for Snipe-IT; else errors showing why create user failed.

### Screenshots

![CompletedForm](https://github.com/snipe/snipe-it/assets/138145705/28a3399b-d5ac-49bb-8d0a-fdaf14ade473)
![CreateAdminUser](https://github.com/snipe/snipe-it/assets/138145705/038195af-c084-450c-9985-d452c4dfb8c2)
![NoDebugLog](https://github.com/snipe/snipe-it/assets/138145705/9b951ca6-a4c3-49f7-ada6-9062476fd43f)

### Snipe-IT Version

v6.1.1-pre

### Operating System

 Red Hat Enterprise Linux 8.8 (Ootpa)

### Web Server

 Apache/2.4.37 (Red Hat Enterprise Linux)

### PHP Version

PHP 8.0.27

### Operating System

Windows 11

### Browser

Google Chrome, Microsoft Edge, Mozilla Firefox

### Version

Chrome=114.0.5735.134 , Edge=114.0.1823.58, Firefox=112.0.2

### Device

n/a

### Operating System

n/a

### Browser

n/a

### Version

n/a

### Error messages

```shell
No errors generated, so there are no logs, stacktraces, or browser errors to paste.
Demo does not include Pre-Flight pages, so I am unable to reproduce in demo.
php -m results:

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib
[Zend Modules]
Zend OPcache
```

### Additional context

This is a fresh install. The server was spun up for this purpose and was given a clean RHEL8 image. After STiG checks, the installation was done following the Linux instructions in the docs and using the git clone method.

I am admittedly new to all of this, so the errors have unfortunately been many. Most were simple fixes (like correcting proxy settings, SELinux complications, double-checking permission issues, etc) and have been resolved.

I was getting a duplicate table error when trying to complete Pre-Flight step 2, so I did manually drop all tables. Re-running the migration after that went smoothly, no errors. Other than that, I have not manually edited any database data.

This installation/server is on an internal DoD network and will be used to manage DoD assets. An alias record has been added to DNS so users do not need to navigate to the hostname, the .conf file contains the ServerAlias, and the .env file App_Url uses the alias address. Firewall rules were added to allow the Snipe-IT server to communicate with the mail server. I am currently using my own navy.mil email as the app email for testing; I will most likely have to request an account and wait for it to be created to assign one to the app specifically.

This error occurs in all of my browsers, and in the same way. The only field that is not wiped clean is the email address, which populates with the app email address (my navy.mil). Because I am using my email as the app email, I wasn't sure if this was because it was retaining the previous entry or auto-populating with the app email address, so I tried account creation using my personal gmail instead. The page still refreshes and wipes the form, and the app email is still the one shown in the email box.

Please let me know if there is any further information I can provide, and thanks in advance for the help!

**Comment by Tapiiri** [comment]
Same issue here. For me, I tweaked the Heroku setup to get Snipe-IT to build up, but my otherwise easy sailing halts on this step, similarly as described above.

**Comment by snipe** [comment]
My guess here is that the form isn't seeing what it considers a valid CSRF token due to some system or network configuration, which is why you're not getting any useful error message. What do you have for your `COOKIE_DOMAIN` in your env?

**Comment by SunniTheSA** [comment]
These are the contents of the Session Settings section of .env:
# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_DRIVER=file
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=true
ENCRYPT=true
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=[set to the same domain as the server is hosted on]
SECURE_COOKIES=false
API_TOKEN_EXPIRATION_YEARS=15

Initially I also had another internal domain listed there, but I removed it in case it was causing the problem. Cleared all caches and restarted httpd, then re-tried. The screen took a tad longer to refresh this time, but ultimately ended with the same result. Can you make any recommendations? Thanks for your help!

**Comment by snipe** [comment]
For `COOKIE_DOMAIN`, you have JUST the domain name, not a full URL right?

**Comment by SunniTheSA** [comment]
Correct. Only the third-level, second-level, and top domain are there. (Ex: xxx.xxx.mil)

**Comment by snipe** [comment]
Damn, I was hoping that would be our smoking gun. Can you turn on debug mode and in your debugger at the bottom, click on the SESSION tab and see if there's anything in the ERRORS section?

**Comment by SunniTheSA** [comment]
This is new, I think. It does say the session has expired. Is there a way to flush or reset the sessions?
![SessionError](https://github.com/snipe/snipe-it/assets/138145705/03267f1f-0c3f-4947-8602-815a3e580bb8)

ETA: on the right it says #2 user. The dropdown also has a #1 user (stacked), with the same time stamp. Same error, same token. Don't know if that's helpful.

**Comment by Tapiiri** [comment]
Yippee, for me, deleting an extra slash from the end of `COOKIE_DOMAIN` (and making the value be solely `subdomain.domain.root_domain` solved the issue - thank you! :)

**Comment by SunniTheSA** [comment]
So...tried a simple page refresh and it worked! I think maybe removing the other domain may have worked after all, just needed the refresh to grab a new token. I'm calling this done! Thanks, @snipe for your help! I'm definitely looking forward to using this application!

**Comment by snipe** [comment]
Sweet! Glad you're sorted!
