### ISSUE TITLE
[Feature Request]: Scheduled Maintenance of Assets 

### ISSUE THREAD

**Issue by ASWCCyberGroup** [grokability/snipe-it#13236]
### Is your feature request related to a problem? Please describe.

We have just started to use Snipe and its a fantastic asset management tool. With a number of assets requiring regular scheduled maintenance, it would be hugely beneficial if a feature was available to configure assets with a maintenance schedule such as weekly AV updates or monthly health checks etc. 

### Describe the solution you'd like

Asset 1 maintenance due on 30/06/2023 and reoccurs every week. Dashboard to suggest maintenance due or not carried out. Not having to manually input regular maintenance tasks each time. 

### Describe alternatives you've considered

we tried to use the Audit feature for this.

**Comment by fivelook** [comment]
Sería muy beneficioso que Snipe IT permitiera al administrador programar los mantenimientos asignando tareas al equipo de soporte técnico. Además, sería ideal que se envíe una notificación por correo electrónico al técnico cuando se le asigne un tipo de mantenimiento específico y que también se envíe una notificación cuando la tarea haya sido completada.

Además de lo anterior, sería conveniente que el administrador tenga la opción de seleccionar a una segunda persona con acceso para asignar tareas. Esto permitiría distribuir la carga de trabajo y garantizar una mayor eficiencia en la gestión de los mantenimientos.

**Comment by ASWCCyberGroup** [comment]
bump.

**Comment by rroethof** [comment]
+1 for this

**Comment by 02ms05** [comment]
+1

**Comment by snipe** [comment]
Duplicate of #6479
