### ISSUE TITLE
[Feature Request]: Disable modules on frontend

### ISSUE THREAD

**Issue by webysther** [grokability/snipe-it#13241]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Disable on frontend modules

### Describe alternatives you've considered

I'm using sub_filter on nginx to get this done.

### Additional context

![image](https://github.com/snipe/snipe-it/assets/750007/a37bae3a-6774-4291-b0f9-3aca4fe20f45)

**Comment by snipe** [comment]
That's not currently on the short term roadmap.
