### ISSUE TITLE
Photos uploaded to the wrong folder

### ISSUE THREAD

**Issue by chuatzeyee** [grokability/snipe-it#13242]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Photos uploaded to /public/uploads/ instead of /public_html/uploads/, hence, photos are not loading on web page. Host (hostinger) doesn't allow change of DocumentRoot to /public/, hence, added route to /public_html/ in AppServiceProvider.php (/app/Providers/). 

![pic01](https://github.com/snipe/snipe-it/assets/114549385/be65c939-7e0f-4ae8-a1dd-190cb6e0a876)
![pic02](https://github.com/snipe/snipe-it/assets/114549385/4314918e-02f4-4263-828f-931dd8c01d6f)
![pic03](https://github.com/snipe/snipe-it/assets/114549385/a516d193-6f9f-4438-87a9-ede4b9778a94)

### Reproduction steps

1. Add re-route /public/ to /public_html/ in AppServiceProvider.php
2. Photos in CMS uploaded to /public/uploads/ still, not /public_html/uploads/.

### Expected behavior

Photos uploaded to /public/uploads/ instead of /public_html/uploads/, hence, photos are not loading on web page. Host (hostinger) doesn't allow change of DocumentRoot to /public/, hence, added route to /public_html/ in AppServiceProvider.php (/app/Providers/). 

### Snipe-IT Version

v6.1.1 build 10847 (g2ac4449ea)

### Operating System

CloudLinux

### Web Server

Apache

### PHP Version

8.1.18

**Comment by snipe** [comment]
Snipe-IT requires the public directory to be `public`, not `public_html`.

**Comment by chuatzeyee** [comment]
> Snipe-IT requires the public directory to be `public`, not `public_html`.

I understand that, but my host doesn't allow the remapping of DocumentRoot to public. Could I work around that?

**Comment by snipe** [comment]
You'd have to set up a symlink from public_html to public. It's not possible to easily change the document root in Snipe-IT.
