### ISSUE TITLE
Mobile Friendly View - View Asset tabs don't work

### ISSUE THREAD

**Issue by ccalby** [grokability/snipe-it#13243]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When using a mobile device, the sub tabs on a view asset page don't load/aren't clickable.

### Reproduction steps

1. Login using a mobile device to use mobile-friendly Snipe-IT.
2. Open an asset.
3. Attempt to click asset sub-tabs (i.e maintainences, etc.)
4. Sub tab doesn't open/load. Remains on the info tab.
sub-tabs

### Expected behavior

Tabs should be navigatable.

### Snipe-IT Version

6.1.1

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1

### Device

Android

### Browser

Brave, Safari, Chrome

**Comment by snipe** [comment]
This was fixed in https://github.com/snipe/snipe-it/pull/13077
