### ISSUE TITLE
PHP Fatal error: Class 'Illuminate\Foundation\Application' not found

### ISSUE THREAD

**Issue by BR99999** [grokability/snipe-it#13249]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

PHP Fatal error: Class 'Illuminate\Foundation\Application' not found while executing php artisan generate:key

### Reproduction steps

1. execute php artisan generate:key
2.
3.
...

### Expected behavior

lunch the app

### Snipe-IT Version

6.0.14

### Operating System

Windows

### Web Server

apache

### PHP Version

V4.2.4

**Comment by snipe** [comment]
What did you do so far? Do you really mean you're running PHP 4.2.4? (I can't imagine that's true, as that version is over a decade old.) 

Please clarify what you've done in the process so far, what your actual PHP version is, and whether this is a fresh install or an upgrade.

Also, please show the output of running:

```
composer dump-autoload
composer install
```

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
