### ISSUE TITLE
Backup: Spatie\DbDumper\DbDumper::setPort(): Argument #1 ($port) must be of type int, string given

### ISSUE THREAD

**Issue by Utility9298** [grokability/snipe-it#13250]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to create a backup via web browser (url/admin/backups) I'll receive this error message:

Spatie\DbDumper\DbDumper::setPort(): Argument #1 ($port) must be of type int, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 56

Do I need to set this variable ($port) in .env file? I couldn't find it in the documentation tough. Calling the DBDumper via cli produces the same error message.

### Reproduction steps

1. Open Snipe-It via web browser
2. Go to Admin / Backup
3. Create Backup

### Expected behavior

Backup gets created

### Screenshots

![snipe_it_backup_error](https://github.com/snipe/snipe-it/assets/87972749/2b2b985b-e04c-41a1-b340-fbe4cedcdbf3)

### Snipe-IT Version

v6.1.1 build 10847 (g2ac4449ea)

### Operating System

Docker

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.11

### Operating System

Windows

### Browser

Chrome, Firefox

### Error messages

```shell
TypeError
Spatie\DbDumper\DbDumper::setPort(): Argument #1 ($port) must be of type int, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 56

Stack trace
        $this->host = $host;

        return $this;

    }

 

    public function getHost(): string

    {

        return $this->host;

    }

 

    /**

     * @param int $port

     *

     * @return $this

     */

    public function setPort(int $port)

    {

        $this->port = $port;

 

        return $this;

    }

 

    /**

     * @param string $socket

     *

     * @return $this

     */

    public function setSocket(string $socket)

    {

        $this->socket = $socket;
```

### Additional context

Fresh install

Using Docker image with connection to mysql-container

So far I created some assets and users, everything worked fine.

**Comment by nlcsdev** [comment]
Perhaps this may be of interest https://github.com/snipe/snipe-it/issues/7353#issuecomment-690116809

**Comment by Utility9298** [comment]
Thank you very much!
Adding MYSQL_PORT_3306_TCP_PORT=3306 to my .env and now it works fine.

**Comment by ygurdag** [comment]
> Thank you very much!
> Adding MYSQL_PORT_3306_TCP_PORT=3306 to my .env and now it works fine.

That works great! Thanks from Turkey
