### ISSUE TITLE
Update to 6.1.2 from 6.1.1 Issue

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#13263]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When attempting to upgrade to 6.1.2 I receive the attached error after running:  composer install --no-dev --prefer-source

What I have tried. This was to correct the previous/first error (Attached)
1.  Ran, Composer Self-Update to update Composer
2. Ensured that Sodium was not commented in PHP.ini

It appears that the PHP version is too high?

### Reproduction steps

1. Run: composer install --no-dev --prefer-source
2.
3.
...

### Expected behavior

composer install --no-dev --prefer-source to run without error.

### Screenshots

![1](https://github.com/snipe/snipe-it/assets/31219479/b6a834e2-3228-465d-b4f9-0034831da7a0)
![2](https://github.com/snipe/snipe-it/assets/31219479/68f5e9d9-9fdf-43ff-bd18-a7a74111157c)
![3](https://github.com/snipe/snipe-it/assets/31219479/bc971840-2760-4136-ae40-df9fc54ae28f)

### Snipe-IT Version

6.1.1

### Operating System

Server 2022

### Web Server

WAMP 3.3.1

### PHP Version

8.1.0

### Operating System

Windows 11

### Error messages

```shell
Attached
```

**Comment by marcusmoore** [comment]
Hi there @jmartins1

Hm....I see your first and third screenshots reference PHP 8.1.0 but your second references 8.2.5. 8.2.5 is not supported right now so you should continue to use 8.1.0. 

On the second run did you do something that triggered 8.2.5 to be used? I'm not familiar with WAMP but maybe updating or restarting the software changed the version somehow?

Can you make sure the output of `php --ini` includes the expected `C: \wamp \bin\php\php8.1.0\php.ini`?

**Comment by jmartins1** [comment]
Thanks Marcus. Found the error. So WAMP does not require a PHP environmental path. It actually throws a warning if you do. Unfortunately, without an entry PHP won't work. Thinking it'd be a good time to add an entry for 8.2.5; so now i had 8.25 and 8.1.0 listed (I had older versions listed. It didn't cause any issues) . Well apparently, when you run a PHP command it will use the environmental path with the latest version listed, which was 8.2.5 even though I was running 8.1.0. 

I corrected the enviromental path by removing 8.2.5 and left 8.1.0. That appears to have fixed the issue.

![error](https://github.com/snipe/snipe-it/assets/31219479/87738cec-2d49-4a07-8a67-23bc51c1a9f8)

**Comment by jmartins1** [comment]
Please close this request.

 

 

Jose Martins, M.Ed., MCSA, MCP/ IT Systems Administrator
***@***.*** ***@***.***> 
P 720.242.6225

Aspen Ridge Preparatory School
705 Austin Ave. Erie, CO 80516
www.aspenridgeprepschool.org





Statement of Confidentiality

The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by marcusmoore** [comment]
Hi @jmartins1, this issue is closed but is still viewable so anyone else that has a similar issue might get pointed in the right direction when they're searching for help.
