### ISSUE TITLE
Error Showing Requested Assets

### ISSUE THREAD

**Issue by brianhoganm** [grokability/snipe-it#13276]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I click on Requested I get a 500 Error message. I enabled the debug mode and I get the following message:

Attempt to read property "id" on null (View: C:\inetpub\wwwroot\SNIPEIT\resources\views\hardware\requested.blade.php)

I am not sure what is going on. Everything was working fine before I updated to version 6.1.2. 

### Reproduction steps

1. Click **Assets**
2. Click **Requested**
3. 
...

### Expected behavior

When clicking **Requested**, I should be able to view items that have been requested by users. 

I was looking foward to the new feature that @inietov put together. 
Cancel requested assets without checkin/out [ch-17606] by @inietov in https://github.com/snipe/snipe-it/pull/13219 

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/109772627/0ac9f3c0-d4aa-48c2-80fc-ae115f446c7f)

### Snipe-IT Version

6.1.2

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.0.24

### Error messages

```shell
@else

                                    (deleted user)

                                @endif

                            </td>

                            <td>{{ App\Helpers\Helper::getFormattedDateObject($request->created_at, 'datetime', false) }}</td>

                            <td>

                                {{ Form::open([

                                    'method' => 'POST',

                                    'route' => ['account/request-item', $request->itemType(), $request->requestable->id, true, $request->requestingUser()->id],

                                    ]) }}

                                    <button class="btn btn-warning btn-sm" data-tooltip="true" title="{{ trans('general.cancel_request') }}">{{ trans('button.cancel') }}</button>

                                {{ Form::close() }}

                            </td>

                            <td>

                                @if ($request->itemType() == "asset")

                                    @if ($request->requestable->assigned_to=='')

                                        <a href="{{ config('app.url') }}/hardware/{{ $request->requestable->id }}/checkout" class="btn btn-sm bg-maroon" data-tooltip="true" title="{{ trans('general.checkout_user_tooltip') }}">{{ trans('general.checko

                                        @else

                                        <a href="{{ config('app.url') }}/hardware/{{ $request->requestable->id }}/checkin" class="btn btn-sm bg-purple" data-tooltip="true" title="{{ trans('general.checkin_toolip') }}">{{ trans('general.checkin') }}</

                                    @endif


                                @endif

                            </td>



                    </tr>

                    @endif

                    @endforeach

                </tbody>

            </table>

        </div>
```

**Comment by inietov** [comment]
I think I know what happened, please check the PR I linked recently to this convo.

Thanks for your report!!

**Comment by brianhoganm** [comment]
> I think I know what happened, please check the PR I linked recently to this convo.
> 
> Thanks for your report!!

Thank you for the quick prompt. I went ahead and made the modifications to the two files and this did not work. Not sure if there is something else going on. Thanks.  For now, I copied the original code from 6.1 and it works now.

**Comment by brianhoganm** [comment]
Hi,
I would like to re-open this again. I am still getting the 500 error message. I know that @inietov said that you fixed the code, but I am still getting the 500 error message. Is anyone else getting this error message. Luckily, I have the original file before you made this change and that works just fine. I really would like to get this resolved because when I update SnipeIT to the latest version it overwrites the original code. I always have to replace the new **requested.blade.php** file with an older version. I am afraid that at some point, I won't be able to use the old one when we move to SnipeIT version 7. Thanks.

**Comment by ndizzlecfizzle** [comment]
This is also happening to my installation

**Comment by ndizzlecfizzle** [comment]
@brianhoganm I was able to fix this by doing the following...

The fix: I loaded the database in Sequel Pro and navigated to the `checkout_requests` field. i deleted all the entries in there (there were only a few), and after deleting those entries I was able to reload the requested page and use it normally. Happy to walk you through it more in depth if you are still having these issues.

**Comment by x249918904** [comment]
> 我能够通过执行以下操作来解决这个问题......
> 
> 解决方法：我在 Sequel Pro 中加载了数据库并导航到该字段。我删除了那里的所有条目（只有几个），删除这些条目后，我能够重新加载请求的页面并正常使用它。如果您仍然遇到这些问题，很乐意引导您更深入地了解它。`checkout_requests`

Hi，这个具体是如何操作呢，我遇到了相同的问题，但是一直未能解决，希望得到你的帮助，谢谢

**Comment by brianhoganm** [comment]
> > 我能够通过执行以下操作来解决这个问题......
> > 解决方法：我在 Sequel Pro 中加载了数据库并导航到该字段。我删除了那里的所有条目（只有几个），删除这些条目后，我能够重新加载请求的页面并正常使用它。如果您仍然遇到这些问题，很乐意引导您更深入地了解它。`checkout_requests`
> 
> Hi，这个具体是如何操作呢，我遇到了相同的问题，但是一直未能解决，希望得到你的帮助，谢谢

Hi Thank you for sharing. I just tested this out and it works!

**Comment by caodongxu588** [comment]
> @brianhoganm I was able to fix this by doing the following...
> 
> The fix: I loaded the database in Sequel Pro and navigated to the `checkout_requests` field. i deleted all the entries in there (there were only a few), and after deleting those entries I was able to reload the requested page and use it normally. Happy to walk you through it more in depth if you are still having these issues.

how to do this ？

**Comment by ndizzlecfizzle** [comment]
> > @brianhoganm I was able to fix this by doing the following...
> > The fix: I loaded the database in Sequel Pro and navigated to the `checkout_requests` field. i deleted all the entries in there (there were only a few), and after deleting those entries I was able to reload the requested page and use it normally. Happy to walk you through it more in depth if you are still having these issues.
> 
> how to do this ？

you need to download an app that can read your sql database. I used sequel pro which is a macOS app.

use the credentials for the sql database to login through the app and then find the checkout_requests section. delete any entries inside there and then reboot your snipeit instance. you should be all set after that.
