### ISSUE TITLE
[Feature Request]: Add History in Company and Location

### ISSUE THREAD

**Issue by nandorusrin** [grokability/snipe-it#13284]
### Is your feature request related to a problem? Please describe.

Yes. In real world, people need to know the item that goes in/out from a company to company or location to location or even from department to department inside a company.

### Describe the solution you'd like

I need history of assets checkin/checkout in company. I need to track item that goes in/out from a company to another company or from one location to another location or the item is being deleted.

**Comment by snipe** [comment]
That's tracked at the asset level, in Asset History.
