### ISSUE TITLE
DropDown Field for Location in HTTPS

### ISSUE THREAD

**Issue by JHLBB** [grokability/snipe-it#13289]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello.

With last few versions, there is a bug, when using https.  On edit asset page, for dropdown menu for "default location". It doesn't list possible locations, it just shows wait circle, so it's not possible to choose location.

![image](https://github.com/snipe/snipe-it/assets/139242223/ec9e4dda-50fc-466f-a5a0-e0b7f2da0288)

If using HTTP for connection, it works.

Last known version that works (at least to my knowledge) in https is  Version v6.0.14 - build 9715 (master)

### Reproduction steps

1. Use newer than Version v6.0.14 - build 9715 (master)
2. Use HTTPS for connection
3. Edit Asset and open dropdown menu for "Default Location"
...

### Expected behavior

Expected to be able to choose location from dropdown menu.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/139242223/0a91906a-c401-4038-95af-fc1874e74e60)

### Snipe-IT Version

Version v6.1.2 - build 10938

### Operating System

Windows Server 2016

### Web Server

Apache 2.4.57

### PHP Version

8.1.20

### Operating System

Windows Server 2016

### Browser

Edge, Chrome, FireFox

### Version

Edge 114.0.1823.67, Firefox 114.0.2

### Additional context

Observed bug on installed version after upgrade. Also did fresh install from github for test and migrated data. That is when I observed that it works over HTTP.

**Comment by jayavman** [comment]
maybe  change APP_URL in .env to https after starting to use SSL

**Comment by inietov** [comment]
@JHLBB  You happen to have any error log there? I can't reproduce this in my end. A little more details would be amazing.

**Comment by JHLBB** [comment]
Thanks @jayavman for the tip, that did the trick, it works now. 👍 

@inietov Yea did check storage/logs after entering debug mode for error logs, but nothing was being generated, so... 

Thanks everybody for quick help.
