### ISSUE TITLE
"No Records Found" Error in Snipe-IT when Switching between Single and Multi-Page Licenses

### ISSUE THREAD

**Issue by freddy2726** [grokability/snipe-it#13298]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I discovered a bug in Snipe-IT where an error message stating "No Records Found" is displayed when switching from a multi-page license to a single-page license. This issue occurs when navigating to the second page of the multi-page license and then opening a single-page license. However, when returning to the first page of the multi-page license, the information is displayed correctly.

### Reproduction steps

1. Open Snipe-IT and navigate to the licenses section.
2. Open a license with multiple pages.
3. Go to the second page of the license.
4. Open a license with only one page.
5. Encounter the "No Records Found" error message.
6. Return to the multi-page license, go back to the first page, and observe the correct display of information.

### Expected behavior

When opening a new License it should always be opened at the first page.

### Snipe-IT Version

v6.1.1 - build 10847 (master) 

### Operating System

Debian

### Web Server

Apache

### PHP Version

7.4.33 

### Operating System

Windows

### Browser

Firefox

### Version

115.0.1 (64-Bit)

**Comment by snipe** [comment]
I'm not sure there's a straightforward solve here. We use cookies (possibly soon local storage) to "remember" what fields you have shown/hidden, sorting, searches, and what page you're on. If we reset this per license (which would be the only way I can see to handle that), you'd have to re-do all of your show/hides on every single license.

**Comment by freddy2726** [comment]
So basically we just have to live with it? In my oppinion it doesnt make much sense to save on which page you where...

**Comment by snipe** [comment]
We're exploring possible solutions here, but remembering the page number is part of the table library, not something we deliberately do. Remembering the page number isn't something we're specifically doing, it's just part of the package.

It does make sense in several use cases though - for example, you search on something in the listing, you get some results, edit that item, and then need to go back to the results to make edits to other (similar) items, you'd not want to have to page through all of the results again.
