### ISSUE TITLE
How to Bulk Update Manufacturer Asset now?

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13305]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I remember you use to be able to move bulk assets from Manufacturer to another one, I'm not seeing this option anymore. Have I lost the Plot?
<img width="906" alt="Screenshot 2023-07-13 at 2 40 38 pm" src="https://github.com/snipe/snipe-it/assets/114973646/1910d5bc-39b1-457d-8f5f-961983984388">

### Reproduction steps

Assets
List All
Select group of assets 
Edit assets
Move to a different Manufacturer

### Expected behavior

Have a manufacturer option change field

### Snipe-IT Version

 v6.1.2 build 10938 (g32747cafd) 

### Operating System

ubuntu

### Web Server

apache

### PHP Version

 8.1.20

**Comment by snipe** [comment]
You’d want to find the appropriate asset *models* and bulk edit those. The assets that use that model will be updated to reflect the new manufacturer.

https://demo.snipeitapp.com/models/

![IMG_0646](https://github.com/snipe/snipe-it/assets/197404/0b0f20ea-1f3a-44dc-9639-72cd78d823f9)


<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/models/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
