### ISSUE TITLE
Assets declined by user remain assigned

### ISSUE THREAD

**Issue by carlospeya** [grokability/snipe-it#13317]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I activate the option for users to accept or reject the assets or accessories assigned by the administrator.

The problems I have are 2:

1.- Even if the user rejects the assignment of the asset, it is still assigned with the rejected status in the history.

2.- The user signs the request but rejects it, the signature is not shown in the user's history. The signature is only shown when you accept the assets or accessories.

### Reproduction steps

1. I assign the asset

2. the user rejected

3. the asset is assigned to him

4. sign the rejection but the signature does not appear

### Expected behavior

I assign the asset

the user rejects and places his signature

the asset or accessory is not assigned to you, it remains in stock

in the user's history your application appears rejected and with the signature

### Snipe-IT Version

6.1.2

### Operating System

Windows

### Web Server

Apache

### PHP Version

8

**Comment by snipe** [comment]
Okay, but what's the intended outcome here? If I have assigned an asset to someone, they have possession of it. If declining it puts it back in stock, where is that asset now? Still with them, presumably. This doesn't seem like the right solution.

**Comment by carlospeya** [comment]
Hello. Maybe I didn't explain it well, sorry. I go again.

For example, I assign an asset to a user in snipe but the user still does not have the asset, he goes to the office to pick up the asset but it turns out that it was not what he expected or it is not useful to him and he rejects the asset, shouldn't that rejected asset be back in stock?
Despite rejecting an asset, it still appears assigned to me.

![image](https://github.com/snipe/snipe-it/assets/101022801/c99e940e-2576-456e-8593-fc6b0023fd35)

![image](https://github.com/snipe/snipe-it/assets/101022801/10337829-64c6-44bc-9ad3-4779dafcd2e4)

Additionally, the signature in active rejected I don't see it in the user history.
