### ISSUE TITLE
When upgrading from 6.0.14 to 6.1.2 Asset Locations are wiped. Restoring from backup does not bring them back.

### ISSUE THREAD

**Issue by donvenco** [grokability/snipe-it#13314]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I attempted to update Snipe-IT from the current version 6.0.12 to 6.1.2 using php upgrade.php and can confirm that I am able to successfully upgrade without error msgs.
The problem I am having is that the activity is altered and hundreds of assets appear as if they were modified with the same time stamp as the upgrade. So then I attempted to restore from a backup but in that case, all my Asset Locations are gone and any devices checked out to locations. However, the timestamp activity for the assets is restored and looks right.

I attempted to do the manual upgrade by renaming the folder and downloading but the result is still the same.

Any help would be appreciated.
<img width="1287" alt="image" src="https://github.com/snipe/snipe-it/assets/121128369/95080b06-ebfd-41ac-a370-89e1c2dd2c38">

<img width="1695" alt="image" src="https://github.com/snipe/snipe-it/assets/121128369/2fd6e265-a0b1-4c60-9c02-540fab91048d">

### Reproduction steps

1.use php upgrade.php command to upgrade
2. sign in to snipe it after the update
3.
...

### Expected behavior

The expected behavior is to have to not have altered data or missing data in Asset Locations.

### Snipe-IT Version

Version v6.0.14 - build 9038

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.13

### Operating System

Windows

### Browser

Chrome

### Version

114.0.5735.199

**Comment by snipe** [comment]
There’s nothing data-destructive in that upgrade, so I’m honestly not sure what would be happening. If you restored, the data is still there. Why you can’t see it is the bigger question.

**Comment by donvenco** [comment]
That is correct. The data is still there just not letting me see it. Perhaps it has something to do with my DB user account. Not enough privileges. What should be the permissions for the account and what would be the easiest way to grant them?

**Comment by snipe** [comment]
What's in your app error logs and browser console? (We do ask those questions in the form for a reason.)

**Comment by donvenco** [comment]
I just made an attempt to re
store again and have captured the logs in the attached file.
[laravel_production.ERRO.txt](https://github.com/snipe/snipe-it/files/12083878/laravel_production.ERRO.txt)
Not sure what I am looking for in the browser.
<img width="1909" alt="image" src="https://github.com/snipe/snipe-it/assets/121128369/204e539e-fd82-4b92-b801-c98b00990ed5">

**Comment by donvenco** [comment]
Just to be clear here. Immediately after the update, the Locations segment appears. The issue is with the alternated time stamp under Recent Activity indicating **asset_eol_date** change. The time stamp matches the one from the update and that is the reason why I am restoring. When I restore the Asset Locations is missing. According to the logs the column PHONE is missing in the location table.
Here are the logs immediately after the upgrade to 6.1.2.
[laravel_after upgrade.log](https://github.com/snipe/snipe-it/files/12089090/laravel_after.upgrade.log)
I also copied part of the logs during the upgrade where during the database migration there is an entry - Migrating: 2023_07_06_092507_add_phone_fax_to_locations
[During Upgrade.txt](https://github.com/snipe/snipe-it/files/12089153/During.Upgrade.txt)

<img width="980" alt="image" src="https://github.com/snipe/snipe-it/assets/121128369/e9753d93-6120-45a1-b1c7-c9114678a5f0">

I guess the updated Recent Activity is not really an issue since it seems like it only indicates to update the EOL date but in fact the date remains the same. However, that threw me off, to begin with.

**Comment by Mason-Ma-11417066** [comment]
I had the same problem.

**Comment by snipe** [comment]
@donvenco that update log doesn't seem complete - can you include the whole thing?

If you do a `composer install --no-dev`, what's the output?

**Comment by donvenco** [comment]
@snipe here is the complete thing:
[upgrade.txt](https://github.com/snipe/snipe-it/files/12099049/upgrade.txt)
Here is the output of the command: composer install --no-dev
[runing composer.txt](https://github.com/snipe/snipe-it/files/12099084/runing.composer.txt)
And here is the laravel log:
[laravel.log](https://github.com/snipe/snipe-it/files/12099063/laravel.log)

Thank you for willing to look in to this! Appriciate it.

**Comment by snipe** [comment]
Hi @donvenco - are you still having issues? Was wondering if any headway was made?

**Comment by donvenco** [comment]
Feel free to archive this. I am all set at this time.

**Comment by snipe** [comment]
Thanks for letting us know :)
