### ISSUE TITLE
[Feature Request]: Agent installer for new registers

### ISSUE THREAD

**Issue by Ordnasil** [grokability/snipe-it#13320]
### Is your feature request related to a problem? Please describe.

Greetings Snipe-it

Got an inquiry for you.
I've just installed SNIPE-IT all right and it works fine so far. Now. I do require the following:

I need, if possible, an agent installer to lift all the asset's specs into the web, instead of loading the user's hardware data manually. Just like I used to do with fusioninventory in GLPI.
e.g:
   Install SNIPE-IT agent on User1 notebook, and get all his/her hardware info into SNIPE-IT

Any suggestion is more than welcome.

Best regards,
Lisandro Delfino.

### Describe the solution you'd like

Local agent installer walkthrough (isntallation, configuration)

**Comment by snipe** [comment]
Hi @Ordnasil - we have a list of agents and integrations that work with Snipe-IT here. https://github.com/snipe/snipe-it#libraries-modules--related-projects

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">GitHub - snipe/snipe-it: A free open source IT asset/license management system</a></strong></div><div>A free open source IT asset/license management system - GitHub - snipe/snipe-it: A free open source IT asset/license management system</div></blockquote>

**Comment by Ordnasil** [comment]
Hey @snipe 
Jeez. Thanks for your reply.
Imma try out this Marksman agent installer, and see how it goes.

Thanks again!
I'm pretty sure I'll be bothering you again haha


Best regards!

**Comment by snipe** [comment]
I'm sure :)
