### ISSUE TITLE
Error Location not Show in after Update to 6.1 from 6.0 

### ISSUE THREAD

**Issue by wirawibowo** [grokability/snipe-it#13324]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

No Location Data on Drop down when create new Location

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Please Help me out

### Screenshots

<img width="479" alt="image" src="https://github.com/snipe/snipe-it/assets/139742141/5581a59a-16ac-436d-a432-5b8c23d13595">

<img width="912" alt="image" src="https://github.com/snipe/snipe-it/assets/139742141/5576654c-027f-4bd6-b129-13916890fb8a">

<img width="896" alt="image" src="https://github.com/snipe/snipe-it/assets/139742141/635dbdaa-7c22-476c-befc-ae03ceeee8f2">

### Snipe-IT Version

6.1.2

### Operating System

Centos 7

### Web Server

Apache

### PHP Version

8.1

### Browser

Chrome, Firefox, Opera

### Additional context

upgrade

**Comment by snipe** [comment]
I'm not able to reproduce this anywhere. Do you have any weird characters in your location names?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by wirawibowo** [comment]
> I'm not able to reproduce this anywhere. Do you have any weird characters in your location names?

im sorry for late respon,, no i dont have or use weird symbol or character on location name, now i rollback to 6.0 again
