### ISSUE TITLE
[Feature Request]: Request to edit inventory form

### ISSUE THREAD

**Issue by melihertasss** [grokability/snipe-it#13338]
### Is your feature request related to a problem? Please describe.

no problem with development

### Describe the solution you'd like

I want to update the inventory list that I have assigned to a person in the program and change the list I have printed.

**Comment by snipe** [comment]
Which "page" are you referring to? The asset detail view? The "print all assigned"? I can't tell what the question/request is.

**Comment by melihertasss** [comment]
I'm talking about the page that appears when I say print all the assets assigned to the person.

**Comment by snipe** [comment]
That's not currently possible without editing the files directly. What changes did you want to make?

**Comment by melihertasss** [comment]
I want to change the overall design. I want to add my company's logo and change the general design.

**Comment by snipe** [comment]
You'd need to change that in the code itself then.

**Comment by snipe** [comment]
Logo is already available on that form though.

https://github.com/snipe/snipe-it/blob/74a5bcd490a0690d4ee04c1e7b599c380d9b7904/resources/views/users/print.blade.php#L34-L50

To use the logo, click the "use in print" checkbox on your Admin Settings > Branding page.

<img width="525" alt="Update_Branding_Settings____Snipe-IT_Demo" src="https://github.com/snipe/snipe-it/assets/197404/5ce93b68-6bad-477e-9ef3-e90e489554b3">

**Comment by melihertasss** [comment]
I thought I could fix this if I changed it through a sketch. But as far as I understand, it will be necessary to change the code to do this. thx
