### ISSUE TITLE
Upload of lic files not possible

### ISSUE THREAD

**Issue by 00shorty** [grokability/snipe-it#13337]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

like mentioned here in this [bug report](https://github.com/snipe/snipe-it/issues/6099) we're also not able to upload *.lic files to snipe-IT.
We still getting the following error:
![image](https://github.com/snipe/snipe-it/assets/81369868/88708ba1-8d5f-4f1b-a577-046599423055)
File type extension is: *.lic
mime-type: application/octet-stream

### Reproduction steps

tried to upload file
- pdf worked fine
- lic file not

### Expected behavior

upload should be successful

### Snipe-IT Version

6.1.0 - build 10161

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.21

**Comment by snipe** [comment]
That's not likely going to be possible, as the mime type for a .lic is `application/octet-stream`, which is classified as an "[unknown binary file](https://docs.oracle.com/en/cloud/paas/integration-cloud/rest-adapter/support-application-octet-stream-mime-attachment-binary-payloads.html#GUID-6FE1B456-7E4D-45C0-B274-F791AA524144)" mime type, which would allow completely arbitrary file uploads, and we wouldn't ever permit that, lest a bad actor ends up making you (or us) host malware. You can zip the file and it should accept that file upload.

**Comment by 00shorty** [comment]
I see, thank you for your clearification
