### ISSUE TITLE
Unable to upgrade to the latest version

### ISSUE THREAD

**Issue by cookierun22** [grokability/snipe-it#13348]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am trying to update to the latest version 6.1.2, but failed.
Below is the shown error:
![image](https://github.com/snipe/snipe-it/assets/115517803/5d9bef40-2830-4444-b1de-8a9ee3eb6158)

### Reproduction steps

1. run php upgrade.php
2.
3.
...

### Expected behavior

The version should be upgraded to 6.1.2

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/115517803/870fdd34-6371-4c0b-a026-98875c26f9a1)

### Snipe-IT Version

v6.0.14

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.10

### Operating System

Ubuntu

### Browser

Google Chrome/Edge

**Comment by snipe** [comment]
It's showing your command-line PHP version as 8.2.2. We do not yet support PHP 8.2.x. Check that your cli version and your web version of PHP are the same.

**Comment by cookierun22** [comment]
I already enable the PHP to run in the lower version, so the system is able to be upgraded.

**Comment by snipe** [comment]
Clearly you didn’t though. Remember that command-line PHP and web server PHP can (and often are) different versions. The composer error you’re seeing is because your command line PHP is set to 8.2.2. You’ll need to downgrade that.
