### ISSUE TITLE
Unable to upload file in accessories when upgrade to version 6.1.2

### ISSUE THREAD

**Issue by cookierun22** [grokability/snipe-it#13356]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Unable to upload file to accessories when upgrade to version 6.1.2. It shows Server error 500. When enable the debug mode it shows error as per screenshot

### Reproduction steps

1. Go to the accessories
2. Try to upload file
3.
...

### Expected behavior

The file should be able to upload

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/115517803/fc2aa50c-bed4-4877-91dc-02c35439caf2)

### Snipe-IT Version

v6.1.2 build 10938 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.10

### Operating System

Ubuntu

### Browser

Google Chrome/Edge

**Comment by cookierun22** [comment]
public function has($path)

    {

        $location = $this->applyPathPrefix($path);


        return file_exists($location);

    }


    /**

     * @inheritdoc

     */

    public function write($path, $contents, Config $config)

    {

        $location = $this->applyPathPrefix($path);

        $this->ensureDirectory(dirname($location));

 

        if (($size = file_put_contents($location, $contents, $this->writeFlags)) === false) {

            return false;

        }

 

        $type = 'file';

        $result = compact('contents', 'type', 'size', 'path');

 

        if ($visibility = $config->get('visibility')) {

            $result['visibility'] = $visibility;

            $this->setVisibility($path, $visibility);

        }

 

        return $result;

    }

 

    /**

**Comment by snipe** [comment]
This is a permissions issue, as the error states. Check the permissions on that folder and any sub folders and make sure they are writable by the web server.
