### ISSUE TITLE
Import Users - Employee Number Will Not Import

### ISSUE THREAD

**Issue by silo84gr** [grokability/snipe-it#13350]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have imported users using LDAP sync. I am using a csv to import the user's employee number. The csv sheet only contains the username, first name, last name, and employee number. 

When I import the sheet, I check the box "update existing values." I confirm the import data is correct and import the sheet. However, the Employee Number is never updated.

For testing, I confirmed other fields like, "Location," "Email," "Department" can export and are visible when the import is complete. So the values do update for the LDAP-synced users.

Does anyone know a fix to ensure Employee Number gets imported?

### Reproduction steps

1. Import csv sheet that contains "Employee Number" "First Name" "Last Name" "Username" Fields
2. Once imported, Employee Number is never imported
3.
4.
...

### Expected behavior

I expect the Employee Number get updated once the import is complete.

### Snipe-IT Version

6.1.2

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1

**Comment by snipe** [comment]
This was fixed last week in https://github.com/snipe/snipe-it/pull/13318 - please update to latest on master.
