### ISSUE TITLE
Browser displays PHP Version Error after upgrade from v3-v4

### ISSUE THREAD

**Issue by daydone** [grokability/snipe-it#13353]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I get the below error after upgrading despite being up to date and in version of what the application requires.
"Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.2"

CLI Data

$ composer check-platform-reqs
Checking platform requirements for packages in the vendor dir
composer-runtime-api 2.2.2      success
ext-bcmath           8.2.8      success
ext-ctype            *          success provided by symfony/polyfill-ctype
ext-curl             8.2.8      success
ext-date             8.2.8      success
ext-dom              20031129   success
ext-fileinfo         8.2.8      success
ext-filter           8.2.8      success
ext-gd               8.2.8      success
ext-hash             8.2.8      success
ext-iconv            *          success provided by symfony/polyfill-iconv
ext-json             8.2.8      success
ext-libxml           8.2.8      success
ext-mbstring         *          success provided by symfony/polyfill-mbstring
ext-openssl          8.2.8      success
ext-pcre             8.2.8      success
ext-pdo              8.2.8      success
ext-phar             8.2.8      success
ext-simplexml        8.2.8      success
ext-sodium           8.2.8      success
ext-tokenizer        8.2.8      success
ext-xml              8.2.8      success
ext-xmlreader        8.2.8      success
ext-xmlwriter        8.2.8      success
ext-zip              1.21.1     success
ext-zlib             8.2.8      success
php                  8.2.8      success
php-64bit            8.2.8      success
$ php -v
PHP 8.2.8 (cli) (built: Jul  8 2023 07:10:21) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.8, Copyright (c), by Zend Technologies

### Reproduction steps

1.Start with v3.
2.Follow the installation guide. (including installing and upgrading to requirements for V4)
3.Error shows on browser

### Expected behavior

I expected the upgrade to work with the PHP version and extensions required.

### Snipe-IT Version

v4

### Operating System

Ubuntu

### Web Server

Apache2

### PHP Version

8.2.8

### Error messages

```shell
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.2".
```

**Comment by snipe** [comment]
Snipe-IT v4 has been deprecated for several years, and even if it weren't, it would definitely not run on PHP 8.2.x. Current Snipe-IT doesn't even run on PHP 8.2.x. You'll have to downgrade your version of PHP and then upgrade.
