### ISSUE TITLE
From restore backup to generate backup have different size and checkout device a bit slow

### ISSUE THREAD

**Issue by beemestd** [grokability/snipe-it#13364]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In windows environment the backup size is 19.5MB , after I migrate to Linux environment, after I restore back and generate the backup, the size become 11.89MB. 

Another issue is while in Windows environment with 512MB memory, when we checkout the device, it will loading a bit slow..once we migrate to Linux environment with 1GB memory, when we checkout the device it will take sometimes around 1minute. 

I am newbie with linux stuff, so I'm not sure what went wrong.

### Reproduction steps

1. Create Backup from Windows Environment. Total size is 19.5MB
2. Migrate to Linux Ubuntu Environment 
3. Restore the backup 
4. Generate Backup, the size become 11.89 MB
...
<img width="616" alt="image" src="https://github.com/snipe/snipe-it/assets/26455335/9b3131b2-74ce-484e-a9a6-2485fd3633e5">

### Expected behavior

I expect the restore size and generate backup  with no new update will be the same size. 
For the checkout , the speed can be increase.

### Snipe-IT Version

6.1.2

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.0

**Comment by snipe** [comment]
So, 1 minute is definitely way too long. Usually when we see behavior like this it's due to notifications - it's trying to send an email or a slack notification and there is latency there. 

As for the backup size difference, without introspecting into the backup itself, it's hard to say. Certain configurations will (wrongly) try to backup more than they're supposed to (application files, etc).

**Comment by beemestd** [comment]
Thanks @snipe , just wondering is the latency issue related with AWS site (I'm hosting in lightsail not EC2)?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
