### ISSUE TITLE
PHP8.2: Using ${var} in strings is deprecated / Argument must be type of array

### ISSUE THREAD

**Issue by schnudd31do3** [grokability/snipe-it#13369]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The result of "php artisan package:discover --ansi" is:

1. Error
"Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/snipeit/vendor/facade/ignition/src/SolutionProviders/**MergeConflictSolutionProvider.php:52**"

'$branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";'
should be
'$branch = "'".trim(shell_exec("cd {$directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";'

2. Error
"Argument 1 ($lastErrors) must be of type array, bool given", called /var/www/html/snipeit/vendor/nesbot/carbon/src/Carbon/Traits/**Creator.php on line 98**"

private static function setLastErrors(array $lastErrors)
should be
private static function setLastErrors($lastErrors)

### Reproduction steps

To use Snipeit with bookworm (php8.2.7) I called composer install with ignore-platform-reqs, otherwise I am not able to proceed. I know, that snipeit is released for 8.1.

1. git clone
2. Run "composer install --no-dev --prefer-source --ignore-platform-reqs"
3. Analyzing the errors from "php artisan package:discover --ansi" as a part of the composer install
4. Patching both php files mentioned above
5. Run again "composer install --no-dev --prefer-source --ignore-platform-reqs"
6. All is fine: "Package manifest generated successfully."

### Expected behavior

No errors during installation

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/72391822/657d9e5c-758d-40c0-9727-16fcc754d388)

### Snipe-IT Version

Version v6.1.2 - build 10938 (master)
Edit: Version v6.2.0 - build 11566 (master), too

### Operating System

Debian bookworm / 12

### Web Server

apache2

### PHP Version

8.2.7

### Operating System

Windos

### Browser

Chrome

### Version

115.0.5790.110

**Comment by marcusmoore** [comment]
Hi there @schnudd31do3,

Unfortunately, like you mentioned, snipe-it isn't fully supported on PHP 8.2 yet but will be in the next major release, v7.

**Comment by schnudd31do3** [comment]
But these two small changes make snipe-it compatible with php 8.2 now and not just in version 7 of snipe-it. So people could switch to the current Debian 12 today and wouldn't have to wait for version 7.

**Comment by snipe** [comment]
It doesn’t, tho. 

These two “small” changes are at the framework level, so we can’t change them. You’re welcome to - it’s open source, after all, but we specifically state we don’t work with PHP 8.2. If you want to FAFO, by all means, do so, but don’t come crying to us when stuff acts weird.

We have a late Sept goal for Snipe-IT v7, which will support PHP 8.2. Hopefully you can be patient and hold on for that.

**Comment by schnudd31do3** [comment]
My solution has only patch level which could bridge the time until September. 

I can live well with my patched version until September. Perhaps other users too.

**Comment by snipe** [comment]
I cannot stress enough how much I recommend against “patching” the framework level files. You do you, for sure. It’s open source. You have enough rope to hang yourself with. But when stuff goes weird, don’t expect us to know how to help you, since you changed the innards of the framework. I would recommend anyone else reading this not to take this approach. Our ability to support you ends when you start messing with files directly.

**Comment by schnudd31do3** [comment]
I agree with you 100% regarding patches.

Let's take a quick look at the details of the changes to assess the actual risk.

The first of the two changes relates to the "array" type. In the previous version of snipe-it, the "array" type was missing at this exact location. Because of my change, it is exactly as you have already released it.

The second change is a correction of the syntax of variables and not a functional change in the software.

In my opinion, the sentence is pure scaremongering: "I would recommend anyone else reading this not to take this approach.". I see no real reason for this. These changes are basically just a syntax fix.

You understood it wrong: "Our ability to support you ends when you start messing with files directly." I wasn't asking for support, just suggesting changes to how the current version of snipe-it works with php8.2.

**Comment by marcusmoore** [comment]
I believe snipe's point is that the files you patched live in the `vendor` directory which means the changes will be overwritten the next time `composer install` is run.

In addition, those two libraries aren't the only dependencies that currently have issues running PHP 8.2 so you'd probably run into more files you would have to patch as you use the app. In v7 we will be updating those dependencies so 8.2 will be fully supported.

**Comment by schnudd31do3** [comment]
@marcusmoore Thanks :-)

**Comment by schnudd31do3** [comment]
The error is still there in the current  "Version v6.2.0 - build 11566 (master)"
I applied my patch to the latest version in order th get it installed and running.

**Comment by snipe** [comment]
The error is still there because the v6 line of Snipe-IT is not compatible with PHP 8.2, per the requirements documentation.
