### ISSUE TITLE
Can not make api calls using javascript

### ISSUE THREAD

**Issue by PMHL97** [grokability/snipe-it#13360]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The javascript format from snipe it website works on its own, but when I replaced it with my company's URL and token(works in postman), it always return:TypeError: fetch failed
    cause: Error: unable to verify the first certificate
Can someone help me here? Thanks a lot

### Reproduction steps

1.copy the javascript to fetch assets bytag
2.Replace with your own URL and token
3. Node runing this JS file

### Expected behavior

supposed to fetch my company's assets bytag

### Snipe-IT Version

idk where to find it, only have url and token

### Operating System

windows

### Web Server

idk

### PHP Version

idk

### Error messages

```shell
error TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: getaddrinfo ENOTFOUND itaa.mcentireproduce.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
```

**Comment by PMHL97** [comment]
If you can help me I'll give you 10 programs stars

**Comment by marcusmoore** [comment]
Hi @MinghowYooo,

It looks like you have a certificate error of some sort. Browsing [this StackOverflow thread](https://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs) can provide some insight and, potentially unsafe, solutions.

**Comment by marcusmoore** [comment]
I'm going to close this since it isn't an issue with snipe-it. Feel free to ask more questions here. I can't promise I can provide answers but maybe I can point you in the right direction.

(I assigned myself just so I'll get tagged in the future)
