### ISSUE TITLE
Login form not working with Firefox password manager

### ISSUE THREAD

**Issue by jpdigital** [grokability/snipe-it#13365]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Firefox does not recognize the user field, and does enter the stored use name.

Firefox Mobile is not able to insert the stored password into the password field. 

This is a *BIG* usuability issue for us. Please use standard input fields so that the browser's passord managers can recongnize the input fieldsd and work as intended. 

### Reproduction steps

1. Store the credentials for Snipe IT in the password manager of Firefox
2. Log out 
3. Try to log in. Firefox does not suggest credentials when entering the cursor into the user field, only after entering the username and moving to the password field. On Firefox mobile, after selecting the correct account, the password is not inserted into the password field.

### Expected behavior

In step 3: The username and password fields are automatically filled out by Firefox if Firefox has stored credentials for the Snipe IT instance.

### Snipe-IT Version

6.1.2

### Operating System

Linux (Debian)

### Web Server

Apache

### PHP Version

7.4.33

### Operating System

Arch Linux

### Browser

Firefox

### Version

115

### Device

Xiomi 

### Operating System

Android

### Browser

Firefox

### Version

115

### Error messages

```shell
none
```

**Comment by marcusmoore** [comment]
Ah that is frustrating. I'll take a look and see if we can improve this.

**Comment by snipe** [comment]
We are already using standard login elements.

```html
<div class="form-group">
    <label for="username"><i class="fas fa-user" aria-hidden="true"></i> Username</label>
    <input class="form-control" placeholder="Username" name="username" type="text" id="username" autocomplete="off" autofocus>
    
</div>
<div class="form-group">
    <label for="password"><i class="fa fa-key" aria-hidden="true"></i> Password</label>
    <input class="form-control" placeholder="Password" name="password" type="password" id="password" autocomplete="off">
    
</div>
<div class="form-group">
    <label class="form-control">
        <input name="remember" type="checkbox" value="1"> Remember Me
    </label>
</div>
```

I suppose we could remove the `autocomplete="off"` aspect, but we had added that for security reasons way back when (and [many browsers don't respect it anyway](https://caniuse.com/input-autocomplete-onoff).)
