### ISSUE TITLE
Deployed assets not displaying

### ISSUE THREAD

**Issue by Edd1306** [grokability/snipe-it#13370]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Trying to get property 'months' of non-object
C:\inetpub\wwwroot\snipe-it\app\Models\Depreciable.php#77
ErrorException
            return null;
        }

        if ($months_passed >= $this->get_depreciation()->months){
            //if there is a floor use it
            if(!$this->get_depreciation()->depreciation_min == null) {

array:55 [▼
  0 => array:5 [▶]
  1 => array:5 [▶]
  2 => array:5 [▶]
  3 => array:5 [▶]
  4 => array:5 [▶]
  5 => array:5 [▶]
  6 => array:5 [▶]
  7 => array:5 [▶]
  8 => array:5 [▶]
  9 => array:5 [▶]
  10 => array:5 [▶]
  11 => array:5 [▶]
  12 => array:5 [▶]
  13 => array:5 [▶]
  14 => array:5 [▶]
  15 => array:5 [▶]
  16 => array:5 [▶]
  17 => array:5 [▶]
  18 => array:5 [▶]
  19 => array:5 [▶]
  20 => array:5 [▶]
  21 => array:5 [▶]
  22 => array:5 [▶]
  23 => array:5 [▶]
  24 => array:5 [▶]
  25 => array:5 [▶]
  26 => array:5 [▶]
  27 => array:5 [▶]
  28 => array:5 [▶]
  29 => array:5 [▶]
  30 => array:5 [▶]
  31 => array:5 [▶]
  32 => array:5 [▶]
  33 => array:5 [▶]
  34 => array:5 [▶]
  35 => array:5 [▶]
  36 => array:5 [▶]
  37 => array:5 [▶]
  38 => array:5 [▶]
  39 => array:5 [▶]
  40 => array:5 [▶]
  41 => array:5 [▶]
  42 => array:5 [▶]
  43 => array:5 [▶]
  44 => array:5 [▶]
  45 => array:5 [▶]
  46 => array:5 [▶]
  47 => array:5 [▶]
  48 => array:5 [▶]
  49 => array:5 [▶]
  50 => array:5 [▶]
  51 => array:5 [▶]
  52 => array:5 [▶]
  53 => array:5 [▶]
  54 => array:5 [▶]
]

### Reproduction steps

1.upgraded to v6.1.2
2. had issues with folder permissions on windows, but seemed to fix those
3.Now, on dashboard can't display all assets.
...

### Expected behavior

I have global user rights  but can't seem to see assets, only if I type in a specific asset tag number the asset uis displayed

### Screenshots

<img width="914" alt="image" src="https://github.com/snipe/snipe-it/assets/140625084/9e32de01-506d-458d-92f4-3f8a8df6e4ee">

<img width="907" alt="image" src="https://github.com/snipe/snipe-it/assets/140625084/c52d29db-c7be-420e-9e97-2cd5c194e7d8">

### Snipe-IT Version

6.1.2

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.30

### Operating System

windows

### Browser

Edge

### Version

Version 115.0.1901.183 (Official build) (64-bit)

### Error messages

```shell
No error on browser
```

### Additional context

upgrade in place

**Comment by marcusmoore** [comment]
Hi @Edd1306,

This should be fixed in #13346 and is due to be released in 6.1.3. Are you able to drop that code change into your app and see if it works?

**Comment by Edd1306** [comment]
Hi @marcusmoore Thanks is seems to fix the issue.
We will update to V6.1.3 . after release date.
Cheers

**Comment by marcusmoore** [comment]
Glad to hear it! 😄
