### ISSUE TITLE
LDAP sync error

### ISSUE THREAD

**Issue by TDCC-T** [grokability/snipe-it#13372]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The LDAP synchronization encountered an error while executing the command "**php artisan snipeit:ldap-sync**". 

Error message: 

`"production.ERROR: Attempt to read property 'id' on null {"userId":77,"exception":"[object] (ErrorException(code: 0): Attempt to read property 'id' on null at /data/snipe-it_p/app/Console/Commands/LdapSync.php:246)"`

This error is consistent with the 500 error encountered when performing the LDAP synchronization without selecting a location on the web interface.

### Reproduction steps

Execute the command: "php artisan snipeit:ldap-sync".  

or

Click on LDAP sync on web, but don't select a location.

### Expected behavior

Ldap sync  success.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/24242596/06d9dd24-4081-4af3-8bf8-a3c8cbc0a743)

### Snipe-IT Version

v6.1.2 build 10938 (g32747cafd)

### Operating System

CentOS 7

### Web Server

Nginx

### PHP Version

8.0.29

**Comment by 02ms05** [comment]
+1
I am having the exact same problem

**Comment by mihaiolimpiu** [comment]
Hi, we have the same sync issue, the problem is that if the code breaks if a location is null.
Attached the solution to fix the issue in code by our software engineer.

[LdapSync_new.zip](https://github.com/snipe/snipe-it/files/12239515/LdapSync_new.zip)

![LDAP sync FIX](https://github.com/snipe/snipe-it/assets/45386430/5ffe67c5-df90-44e6-a08b-3bde46f8ac3f)

**Comment by mihaiolimpiu** [comment]
Above fix is not working properly. Will look into it.

Edit: The posted fix by user @uberbrady is correct and proper.

We can close this if commit goes trough. https://github.com/snipe/snipe-it/pull/13397

**Comment by lerroot** [comment]
Same issue- 

Snipe-IT version
v6.1.2 build 10938 (g32747cafd)
Software License
[AGPL3](https://www.gnu.org/licenses/agpl-3.0.en.html)
PHP Version
8.1.2-1ubuntu2.13
Laravel Version
8.83.22

Is there a timeline for a fix for this issue?  I attempted to revert to an older container (version 5.4.1.6746) using same database, but it breaks LDAP integration (tests fail).  Is there a container version that works?  Is there some ldap-related db issue when reverting to an older container with the db used for a newer version?

**Comment by lerroot** [comment]
What version of snipeIT will this fix be incorporated into?
