### ISSUE TITLE
Component checkout via API returns error

### ISSUE THREAD

**Issue by Ebbenstein** [grokability/snipe-it#13376]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to assign a component to an asset via the API it returns an error: "The asset id field is required."

This happens when using the API explorer, as well as on my own Snipe-it web.

Se screenshot for details.

### Reproduction steps

1. Used the explorer to search for component ID
2. Used the explorer to search for Asset ID
3. Clicked "Try it"
...

### Expected behavior

Assign the component to the asset

### Screenshots

![Unavngivet](https://github.com/snipe/snipe-it/assets/140736825/49be1beb-8fc5-4ec7-b126-12614b0dd099)

### Snipe-IT Version

v6.1.2 build 10938 (g32747cafd)

### Operating System

Hosted by You

### Web Server

Hosted by You

### PHP Version

8.0.28

**Comment by Godmartinz** [comment]
@Ebbenstein A solution has been merged into develop, should be merged into main soon. 🙂
