### ISSUE TITLE
500 Server error when try to uplaod logo from "Branding"

### ISSUE THREAD

**Issue by sarahYB** [grokability/snipe-it#13388]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am trying to upload a logo but got 500 server error.
  

### Reproduction steps

1. Navigation to Branding.
2. In "Web Branding Type", I selected "Logo + Text".
3. In "Logo", I uploaded my logo.
4. In the bottom of the page, I clicked "Save".

### Expected behavior

The logo should uploaded successfully.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/141055329/329f5c71-a0a3-4bd2-bfbb-6052c9bc69af)

### Snipe-IT Version

v6.1.2 build 10938 (g32747cafd)

### Operating System

redhat 8

### Web Server

Nginx

### PHP Version

8.1.21

**Comment by snipe** [comment]
I’d need app logs to be able to diagnose this further, but this feels like a permissions issue to me. Check that the `public/uploads` and all subdirectories are writable by the web server.

**Comment by sarahYB** [comment]
Permissions of /public/uploads directory:
![image](https://github.com/snipe/snipe-it/assets/141055329/625130dd-0024-43db-8de3-12891c75b353)

**Comment by snipe** [comment]
Can you please show me your app logs when the 500 error is triggered.

**Comment by sarahYB** [comment]
You mean nginx logs?

**Comment by snipe** [comment]
App logs. https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs

`storage/logs/laravel.log`

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by sarahYB** [comment]
Here it is:
![image](https://github.com/snipe/snipe-it/assets/141055329/1bd407d6-2899-4436-9365-d0694fe7d813)

**Comment by sarahYB** [comment]
All errors related to email configuration. Nothing about logo uplaod.
![image](https://github.com/snipe/snipe-it/assets/141055329/a9accaf9-0d70-472c-b33d-3b800faf4e38)

**Comment by sarahYB** [comment]
Hi,

Permissions are good, and there is no logs related to logo upload.

What do you think the problem is?

**Comment by snipe** [comment]
That error log looks related to your email configuration, not related to images.

**Comment by sarahYB** [comment]
Yes, no logs related to images and logo update which is weird.
I am able to upload the logo and see it. But when I save it, I get 500 error on the UI.

**Comment by snipe** [comment]
Without anything in the logs, I can't really debug this further, and I cannot reproduce it locally. :-/

Can I see the fill display of `ls -al public/uploads`?

**Comment by sarahYB** [comment]
Here it is:
![image](https://github.com/snipe/snipe-it/assets/141055329/371ad707-8049-4fb0-a149-35cc8fdbc6d1)

**Comment by snipe** [comment]
That logo size seems... really huge? Can you try resizing it down?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
