### ISSUE TITLE
User first name, last name, and email address get overwritten on LDAP login with data from first LDAP user found

### ISSUE THREAD

**Issue by varyfirst** [grokability/snipe-it#13385]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When logging in as a user from LDAP my data (i.e. first name, last name, and email address) gets overwritten with the data from the first LDAP user found.

I verifed by removing the first found LDAP user from the filter and now I get the data from the other first user.

While being logged in I synced LDAP and the user data is correct again for everybody that logged in.

The username itself is not altered at any time (at least from what I have seen until now) so there is no wrong data in any relation but it is shown wrongly. After manually syncing LDAP the values are correct again.

### Reproduction steps

1. setup LDAP connection and make sure at least two users are being synced
2. login with the second LDAP user
3. the current user data now gets overwritten with the one from the first LDAP user
4. manually sync LDAP
5. the current user data now gets filled with the LDAP values

### Expected behavior

The current user data is filled with the correct values from LDAP on login and not just from the first LDAP user found.

### Snipe-IT Version

6.1.2

### Operating System

Debian

### Web Server

nginx

### PHP Version

8.0.9

### Operating System

Arch Linux

### Browser

Brave

### Version

1.52.130 Chromium: 114.0.5735.198 (Official Build) (64-bit)

### Device

-

### Browser

-

### Version

-

### Error messages

```shell
Unfortunately there is no error log about that at all. Nothing to see in the logs.


$ php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
pspell
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```
```


### Additional context

- upgrade
- installation method: git checkout the revision and `php upgrade.php`
- no error messages displayed / known
- no manual editing in the database

**Comment by uberbrady** [comment]
This can sometimes be an issue with a complex LDAP filter that uses an OR clause (with a `|`). What's your LDAP filter configured to?

**Comment by varyfirst** [comment]
@uberbrady We have the following LDAP filter configured.

`|(uid=user1)(uid=user2)(uid=user3)`

`user1` etc. are of course real user names in our setup.

**Comment by uberbrady** [comment]
Hrm. You might want to try something like: `&(|(uid=user1)(uid=user2)(uid=user3))` - when it assembles together the final filiter that should end up probably getting you something closer to what you'd want.

**Comment by varyfirst** [comment]
Whelp, yes, thanks. Now I get logged in with the correct name displayed.
Could you please tell me why this is the case and why it "[...] can sometimes be an issue [...]"?

**Comment by uberbrady** [comment]
The filter and the user authentication query and the username you're trying to log in as all get concatenated together.

So if you're logging in as 'user3' the concatenated filter will be something like: 

`(&(|(uid=user1)(uid=user2)(uid=user3))(uid=user3))` - logging you in as user3.

**Comment by varyfirst** [comment]
Got it, thank you for explaining.
