### ISSUE TITLE
Search strange behavior

### ISSUE THREAD

**Issue by shinduke** [grokability/snipe-it#13380]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Searching in a selected Status is not working like expected. 
If i select the status "In Stock" and then search for Docking Stations i get every dockingstation and not only that one which have the "In Stock" status
![image](https://github.com/snipe/snipe-it/assets/36949743/366e8ed3-d206-4807-83e4-4dc6c819cf57)

### Reproduction steps

1. Create i.e. Status "In Stock"
2. Select in the Navbar the created Status
![image](https://github.com/snipe/snipe-it/assets/36949743/c4b0080b-155d-444d-b954-020b8f4a1bad)
3. Search for any Asset Category

### Expected behavior

See results only of the searched category in the selected Status

### Snipe-IT Version

v6.1.1 - build 10847 

### Operating System

WIndows

### Web Server

IIS

### PHP Version

8.2

**Comment by snipe** [comment]
This was fixed a few weeks ago - please update to latest on master.
