### ISSUE TITLE
Server in Down state after upgrade

### ISSUE THREAD

**Issue by daydone** [grokability/snipe-it#13393]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I followed the "Upgrading via Git" Guide to the letter and now my browser displays the below despite application being in a live state. I checked that my backup .env file is the same after the upgrade and they are the  same. I have restarted apache and run composer update and composer check-platform-reqs. None of the "common issues" seem to mention this error.
# composer check-platform-reqs
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Checking platform requirements for packages in the vendor dir
composer-runtime-api 2.2.2      success
ext-bcmath           8.1.21     success
ext-ctype            *          success provided by symfony/polyfill-ctype
ext-curl             8.1.21     success
ext-date             8.1.21     success
ext-dom              20031129   success
ext-fileinfo         8.1.21     success
ext-filter           8.1.21     success
ext-gd               8.1.21     success
ext-hash             8.1.21     success
ext-iconv            *          success provided by symfony/polyfill-iconv
ext-json             8.1.21     success
ext-libxml           8.1.21     success
ext-mbstring         *          success provided by symfony/polyfill-mbstring
ext-openssl          8.1.21     success
ext-pcre             8.1.21     success
ext-pdo              8.1.21     success
ext-phar             8.1.21     success
ext-simplexml        8.1.21     success
ext-sodium           8.1.21     success
ext-tokenizer        8.1.21     success
ext-xml              8.1.21     success
ext-xmlreader        8.1.21     success
ext-xmlwriter        8.1.21     success
ext-zip              1.19.5     success
ext-zlib             8.1.21     success
php                  8.1.21     success
php-64bit            8.1.21     success

# php artisan up
Application is now live.

### Reproduction steps

1.Follow "Upgrading via Git" Guide to the letter 

### Expected behavior

Upgraded Application Login Prompt on Browser

### Screenshots

![Snipe IT](https://github.com/snipe/snipe-it/assets/44883786/cb747cfa-cfe1-432e-80cb-9be587c69e2f)

### Snipe-IT Version

latest

### Operating System

Ubuntu 

### Web Server

apache2

### PHP Version

8.1.21

### Operating System

Windows

### Browser

Google Chrome

### Version

10

**Comment by snipe** [comment]
So you’re seeing the code on the browser screen? That would only happen if Apache isn’t configured correctly. Are you using mod_php or php-fpm?

**Comment by snipe** [comment]
Are you still having trouble with this? If the issue has been resolved, please remember to close the issue.
