### ISSUE TITLE
[Feature Request]: Custom Field - Form Element Checkbox (only 1 option)

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13390]
### Is your feature request related to a problem? Please describe.

Request for an Option when selecting Element (CheckBox) to Only be able to select One option. Currently if you have Checkbox and multiple options users can select more than one option.

We should have an option for both. either More than 1 option or only 1 option

![Screenshot 2023-08-01 at 1 33 07 pm](https://github.com/snipe/snipe-it/assets/114973646/80dac834-c479-476e-a43b-d131b1a8e50f)

![Screenshot 2023-08-01 at 1 36 34 pm](https://github.com/snipe/snipe-it/assets/114973646/541bf383-9667-4fcc-89da-49e25f90e47f)

### Describe the solution you'd like

As above

**Comment by inietov** [comment]
Maybe what you want is to use radiobuttons? you can have multiple options, but only select one.

**Comment by jayavman** [comment]
nice. I'll use radio buttons instead. thanks!
