### ISSUE TITLE
[Feature Request]: Search Mask and auto mac formatting

### ISSUE THREAD

**Issue by cTurtle98** [grokability/snipe-it#13401]
### Is your feature request related to a problem? Please describe.

I have many devices with barcodes on them for mac addresses where the barcode data doesn't contain the colons. its just the hex.
when I scan this barcode to create an asset I have to add the colons manually.
if I use this barcode for search I have to add the colons manually.
I also have some devices where the barcode includes dashes instead of colons.

also some of my devices have dashes in the serial numbers in the text but when you scan the barcode there are no dashes.

### Describe the solution you'd like

make it possible to add characters that are masked from search so they can be just there for readability formatting.

make it so the mac address field type accepts input as unformatted and automatically adds the colons or converts dashes to colons 

### Describe alternatives you've considered

currently I standardize all the snipe-it fields to be whatever is in the barcode except for mac because i'm using the built in mac format and that requires the colons to be added.

### Additional context

brother printer mac address stickers have dashes in delineation

dell mac address stickers dont have any formatting. just hex.

**Comment by snipe** [comment]
This is a pretty specific use case and I think it would likely break things for other people in unexpected ways. I'd probably suggest just getting rid of the old built-in mac address and just creating a new mac address field that doesn't have the regex (meaning it's just a text field) instead.
