### ISSUE TITLE
Mailgun EU does not seem to work and test system just fails to report error.

### ISSUE THREAD

**Issue by barkermn01** [grokability/snipe-it#13417]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Mailgun when using the EU server does not seem to work and there is no error output.

### Reproduction steps

1. create an EU Mailgun domain.
2. generate a secret key for said domain
3. update `.env` to have `MAIL_DRIVER=mailgun`, add 
```
MAILGUN_DOMAIN='ob.fusca.ted'
MAILGUN_SECRET='obfuscated'
MAILGUN_ENDPOINT='api.eu.mailgun.net'
```
4. use setup and click `Send Test` button for `Email`

### Expected behavior

Mail to send or at least give an error.

### Screenshots

** Removed to hide email address **

### Snipe-IT Version

v6.1.2

### Operating System

Ubuntu

### Web Server

Nginx

### PHP Version

7.4.33

### Operating System

Windows

### Browser

Edge

### Version

115

### Error messages

```shell
undefined
```

### Additional context

i think this is because i guessed / assumed that the option would be MAILGUN_ENDPOINT to configure this and based my information from https://github.com/snipe/snipe-it/issues/11029 and linked Laravel documentation of https://laravel.com/docs/6.x/mail#driver-prerequisites

**Comment by snipe** [comment]
This is now fixed on master
