### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by voklav** [grokability/snipe-it#13413]
### Is your feature request related to a problem? Please describe.

Hello,
I think it will be good for everyone if, in the warranty field, you can choose which date it is until, and not just save how many months are left.

### Describe the solution you'd like

Whether it will be from a calendar-type drop-down menu, or whether it will be able to be written in a text field.

### Describe alternatives you've considered

In fact, I do not want to replace the existing model, but to enrich it.

### Additional context

I had to bring in about 50 dell machines.
When I check how long their warranty is:
example: Expiration date
03 MAR 2024
And an unpleasant calculation begins...

**Comment by snipe** [comment]
You would use EOL date for that
