### ISSUE TITLE
Not receiving email notification upon asset request

### ISSUE THREAD

**Issue by cjmodi306** [grokability/snipe-it#13427]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello, I am an admin user of SNIPE-IT at our company and would like to receive email notification if someone requests any of the assets. I have activated alert notification from "Notification" settings, however, do not receive any when someone does request one. Could you please help me with the issue? Thanks.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

I would like to receive email notification when someone requests an asset.

### Snipe-IT Version

6.1.1

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.21

**Comment by snipe** [comment]
Without logs or anything else, I'm not sure how I can troubleshoot this. Is the mail being sent and not received? Have you checked your SPAM folder? Anything in your app logs?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
