### ISSUE TITLE
[Feature Request]:Assistance Required for Modifying /hardware/bulkcheckout Page

### ISSUE THREAD

**Issue by mannou** [grokability/snipe-it#13420]
### Is your feature request related to a problem? Please describe.

Hello Snipe-IT Team,

I hope this message finds you well. I've been using Snipe-IT and I'm looking to customize the /hardware/bulkcheckout page to add some additional functionality. I would greatly appreciate your guidance and expertise in achieving these modifications.

Here are the changes I'm looking to implement:

Adding a User Password Field:
I would like to include an additional field on the bulk checkout page where the user can input their password. This is intended to enhance security and ensure authorized access when checking out assets.

Including Time Alongside Date for Reservation and Return:
Currently, the date selection is available for reservation and return. However, I'm interested in enhancing this by including both the date and time for more precise tracking. This will help improve accuracy in managing asset reservations and returns.

I understand that modifying code involves a certain level of technical understanding, and I'm eager to learn and implement these changes under your guidance. Could you please provide me with the steps or code adjustments needed to achieve these goals?

### Describe the solution you'd like

Your assistance would be immensely valuable to me, and I'm excited to contribute these enhancements to the Snipe-IT platform.

Thank you in advance for your time and support. I look forward to hearing from you and appreciate any insights you can provide.

**Comment by snipe** [comment]
> I would like to include an additional field on the bulk checkout page where the user can input their password. This is intended to enhance security and ensure authorized access when checking out assets.

This would be a pretty big change to functionality. The security aspect should be handled via user/permission groups, not at this level, so I'm not sure we would take this PR if you were to create it. What additional security would it provide?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
