### ISSUE TITLE
Leading and trailing spaces in fields are not trimmed

### ISSUE THREAD

**Issue by gettalong** [grokability/snipe-it#13429]
### Debug mode

- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Leading and trailing whitespace in text fields are not automatically trimmed. For example, if the asset tag has a leading or trailing whitespace, entering just the text in the asset tag search field yields no result.

### Reproduction steps

1. Create a new asset and add a leading and trailing space to the asset tag.
2. Try searching for the asset via the asset tag text (without the spaces)
3. There is no result.
4. Edit the asset and you will find that the leading and trailing spaces are still there.

### Expected behavior

Leading and trailing spaces should automatically be trimmed.

### Snipe-IT Version

6.1.2

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

**Comment by snipe** [comment]
That's expected behavior. If we were to automatically trim, it could potentially break workflows for other people.

**Comment by gettalong** [comment]
So you are saying we are in an [XKCD situation](https://xkcd.com/1172/) here?

I fully understand that you don't want to break existing workflows but this is a *very* unusual behavior. And it allows for easily introducing mistakes into the asset database.

I'm not familiar with the code base but would you be able to point out the places where changes would be needed to implement trimming of input fields? Then we could possibly implement the changes ourselves.

**Comment by axkibe** [comment]
> That's expected behavior. If we were to automatically trim, it could potentially break workflows for other people.

Not asking for automatic trimming, asking for the asset input form to deny adding an asset if there is a leading or trailing space in the asset tag (just as it does e.g. with IP adresses or MACs). Leading/trailing spaces can easily happen here due to copy/paste operations and can be a nasty source of errors.
