### ISSUE TITLE
[Feature Request]: Location based work 

### ISSUE THREAD

**Issue by melihertasss** [grokability/snipe-it#13440]
### Is your feature request related to a problem? Please describe.

No, it seems like there is a feature that I want, but I couldn't find it.

### Describe the solution you'd like

I keep records of multiple locations here. But I don't want the staff at location A to interfere with location B or even see their records. I want to give separate authorization to users for each location. Honestly, I searched but couldn't find it. I look forward to your support in this matter.

**Comment by melihertasss** [comment]
@snipe

**Comment by Godmartinz** [comment]
Hello @melihertasss I'm sure you can achieve this with company scoping and setting permission groups for users. I would take a [look here to get started](https://snipe-it.readme.io/docs/getting-started#making-assets-available-to-only-certain-people)

**Comment by melihertasss** [comment]
Hi, I am doing this from locations. But I saw that when I changed my different position to different company. This is enough for me. thanks
