### ISSUE TITLE
 Asset Maintenance Report - Empty Warranty Field

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13444]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

 Asset Maintenance Report -
Field Warranty - If have no warranty or information. It says "trueFalseformatter"

![Screenshot 2023-08-14 at 2 48 29 pm](https://github.com/snipe/snipe-it/assets/114973646/f2b8e953-a36d-4ce8-b8b8-ae447e17a9eb)

### Reproduction steps

1. Asset Maintenance report
2.Field under warranty
3.
...

### Expected behavior

Blanked out field if no warranty information provided.

### Snipe-IT Version

v6.1.2 build 10938 (g32747cafd) 

### Operating System

ubuntu

### Web Server

apache

### PHP Version

 8.1.22

**Comment by snipe** [comment]
Hm, I'm not able to reproduce this... 
<img width="1645" alt="Screenshot 2023-08-14 at 12 56 48 PM" src="https://github.com/snipe/snipe-it/assets/197404/884cff01-c066-4fc0-82f3-fbd607e534d3">

Is there anything in your browser console?

The `trueFalseFormatter` *is* something we use for boolean fields to be able to display a checkbox or an X, but I'm not sure why you're seeing what you're seeing.

**Comment by snipe** [comment]
Ah, sorry, I was looking in the wrong place. I can reproduce it locally. I'll have a fix out shortly.

**Comment by snipe** [comment]
This fix is on master now - thanks for the heads up!
