### ISSUE TITLE
Amazon AWS RDS SSL Connection does not work.

### ISSUE THREAD

**Issue by barkermn01** [grokability/snipe-it#13441]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

So this issue is a continuation of https://github.com/snipe/snipe-it/issues/6611 

Just a quick rundown of the problem, When using Amazon RDS server via SSL mode Snipe-It does not work it gives and SQL Error `SQLSTATE[HY000] [2002]`

as per the last message i have verified and just to be safe run that chmod command provided by @HinchK 

> chmod 400 /var/www/pma/certs/AmazonRootCA1.pem

Please note this Certificate works fine in PHPMyAdmin using MySQLi Connector, Output to confirm permissions are correct:
```shell
-r-------- 1 www-data www-data 1188 Oct 31  2022 /var/www/pma/certs/AmazonRootCA1.pem
```

The error i get with debug mode turned on now that there is a working setup from me not using SSL
```shell
Illuminate\Database\QueryException
SQLSTATE[HY000] [2002] (SQL: select * from `users` where `id` = 1 and `users`.`deleted_at` is null limit 1)
```

The Error logs in the MariaDB Server are:
```shell
2023-08-11 22:39:39 10838746 [Warning] Aborted connection 10838746 to db: 'unconnected' user: 'unauthenticated' host: '10.1.28.252' (This connection closed normally without authentication)
2023-08-11 22:39:39 10838747 [Warning] Aborted connection 10838747 to db: 'unconnected' user: 'unauthenticated' host: '10.1.28.252' (This connection closed normally without authentication)
2023-08-11 22:39:39 10838748 [Warning] Aborted connection 10838748 to db: 'unconnected' user: 'unauthenticated' host: '10.1.28.252' (This connection closed normally without authentication)
```

That IP Address is the address of my connecting server so it appears that for some reason when `DB_SSL` is enabled in the `.env` the DB_DATABASE and `DB_USERNAME` are ignored?

### Reproduction steps

1. Setup an EC2 with WebServer and PHP (I'm using nginx and PHP-FPM)
2. Setup an AWS RDS (MariaDB)
3. Setup Snipe it to connect to DB using SSL via the `.env` file
...

### Expected behavior

Snipe-It work as normal other than using an SSL Encrypted communication to the Database Server

### Screenshots

as per the last message i have verified and just to be safe run that chmod command provided by @HinchK 

> chmod 400 /var/www/pma/certs/AmazonRootCA1.pem

Please note this Certificate works fine in PHPMyAdmin using MySQLi Connector, Output to confirm permissions are correct:
```shell
-r-------- 1 www-data www-data 1188 Oct 31  2022 /var/www/pma/certs/AmazonRootCA1.pem
```

### Snipe-IT Version

v6.1.2

### Operating System

Ubuntu

### Web Server

Nginx

### PHP Version

7.4.33

### Error messages

```shell
Illuminate\Database\QueryException
SQLSTATE[HY000] [2002] (SQL: select * from `users` where `id` = 1 and `users`.`deleted_at` is null limit 1)
```

The Error logs in the MariaDB Server are:
```shell
2023-08-11 22:39:39 10838746 [Warning] Aborted connection 10838746 to db: 'unconnected' user: 'unauthenticated' host: '10.1.28.252' (This connection closed normally without authentication)
2023-08-11 22:39:39 10838747 [Warning] Aborted connection 10838747 to db: 'unconnected' user: 'unauthenticated' host: '10.1.28.252' (This connection closed normally without authentication)
2023-08-11 22:39:39 10838748 [Warning] Aborted connection 10838748 to db: 'unconnected' user: 'unauthenticated' host: '10.1.28.252' (This connection closed normally without authentication)
```

### Additional context

That IP Address is the address of my connecting server so it appears that for some reason when `DB_SSL` is enabled in the `.env` the `DB_DATABASE` and `DB_USERNAME` possibly the `DB_PASSWORD` are ignored.

**Comment by snipe** [comment]
@uberbrady can you please take a look?

@barkermn01 - HinchK is not really involved in this project anymore, so it would be best to not tag him into issues moving forward. No need to clog up his inbox.

**Comment by uberbrady** [comment]
In your `.env` you will want at least the following env vars settings - 

`DB_SSL` - `true`
`DB_SSL_IS_PAAS` - should also be set to `true`
`DB_SSL_CA_PATH` - should point to your CA cert
`DB_HOST` - should point to your AWS RDS endpoint for your DB instance
`DB_USERNAME` - username
`DB_PASSWORD` - password

If you've got all of those set, it *should* work.

If not, you should play around with the mysql command-line tool and see if you can get connected that way - with the appropriate command-line options. If you *can't* get that to work, then Snipe-IT will definitely not work either.

Please give some of that a whirl and let us know where you net out.

**Comment by snipe** [comment]
(Also, for clarification, those env vars should be followed by an `=` not a dash, with no spaces in between.)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by barkermn01** [comment]
could you possibly include that in the documentation? https://snipe-it.readme.io/docs/configuration there is no mention of SSL Database connection besides the example of not using it, there is also no information about PAAS when required or not. hell even a comment in the .env file would better than what you have now which is nothing even though it's a requirement of GDPR to have encryption during transit of data.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.Don't be intimidated by the length of this page. The configuratio...</div></blockquote>
