### ISSUE TITLE
Display Issue Creating New Fieldset With Single Quote

### ISSUE THREAD

**Issue by tglassburn** [grokability/snipe-it#13450]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When creating a new fieldset, if I put something with a single quote, it displays incorrectly after it's been created.

Instead of test' it will show test&#039;

What I used:
![test](https://github.com/snipe/snipe-it/assets/142260542/446d9b2c-f526-4121-aa6b-5ba911288932)

Result:
![result](https://github.com/snipe/snipe-it/assets/142260542/90af4afd-5d8a-45bb-a3fb-16ac20e00bc8)

### Reproduction steps

1. Create new custom field
2. Put a single quote in name
3. Watch output when created, it will replace single quote with &#039;
...

### Expected behavior

Should just have a single quote

### Snipe-IT Version

6.1.2

### Operating System

Linux

### Web Server

Apache

### PHP Version

8.2

**Comment by snipe** [comment]
This is now fixed on master
