### ISSUE TITLE
I edited a category and nothing shows up

### ISSUE THREAD

**Issue by ecord17** [grokability/snipe-it#13452]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I was editing a category and when I finished, nothing is showing up when I select it. I ran a report to see if I can figure out what happened. I look at the report and all the fields seem to be filled with the correct information.  I can now only view the asset if I search for it by asset number. I have attached a screen shot of the error.  Is there a way to just locate the error to correct it?

### Reproduction steps

1. From the report I ran, I went into each category and made sure all information has been inputted. 
2. I reloaded the page and still not showing it. 
3.
...

### Expected behavior

Every other category works as expected except for 1 category which is called Laptop. 

### Screenshots

![error](https://github.com/snipe/snipe-it/assets/124282480/ebd76369-70df-46cc-a612-e4a5c69f19e1)

### Snipe-IT Version

v4.6.7 build 3944 (g8f6ea84fc)

### Operating System

windows

### Web Server

IIS

### PHP Version

7.2.24-0ubuntu0.18.04.15

### Operating System

windows

### Browser

chrome

### Operating System

windows

**Comment by ecord17** [comment]
There is a typo***** I went into each asset and made sure that all fields were filled. Out of all the categories, only 1 is not showing up. *******

**Comment by snipe** [comment]
@ecord17 what's in your app logs? https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by ecord17** [comment]
I do not see anything that says storage/logs. This is what I see:   
![log directory](https://github.com/snipe/snipe-it/assets/124282480/a1c13533-2b77-4366-a064-ec78289ef6a0)

**Comment by snipe** [comment]
You're in the wrong directory. `storage/logs/laravel.log` is within your Snipe-IT directory

**Comment by ecord17** [comment]
[SnipeIT storage log - 2023.08.15.txt](https://github.com/snipe/snipe-it/files/12360446/SnipeIT.storage.log.-.2023.08.15.txt)

Here is the storage logs

**Comment by ecord17** [comment]
![exception](https://github.com/snipe/snipe-it/assets/124282480/4988c891-67ec-438d-9aa2-f840d52def2e)
Here is the pic of the exception when I try to query the category.

**Comment by ecord17** [comment]
Any idea?

**Comment by inietov** [comment]
@ecord17 As it is an older version the first thing crossing my mind is that you can try making a backup and then updating to a recent version. I'm not able to reproduce the issue in my local instance so maybe is a bug that's already fixed.

**Comment by ecord17** [comment]
oh ok. I will back it up and try what you suggested.  Where can I locate the most recent version of it so that I can update it?

**Comment by inietov** [comment]
Most recent version is here in this repository, latest stable is the `master` branch. You also can use the 'upgrade.php' script as stated in the documentation. https://snipe-it.readme.io/docs/upgrading

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div>🚧If you run into any issues upgrading...Please check the Common Issues &gt; Installation/Upgrading Issues section which provides solutions for commonly encountered installation / upgrading problems.📘Note:When available, please use the more detailed upgrade instructions for specific versions, avail...</div></blockquote>

**Comment by ecord17** [comment]
I started reading the upgrade process. I did notice that the easiest and safest way to upgrade would be using Git.  I do have a question on that particular process. When you go step by step so that you can update using Git, it asked you to run the command php upgrade.php.  When I do that, it warns me to not run composer as SU.  So how do I run it without using it as SU?

**Comment by ecord17** [comment]
Let me explain that I did not set this up. This was done many years before me and now I am just trying to get it to work and updated.

**Comment by snipe** [comment]
> When I do that, it warns me to not run composer as SU. So how do I run it without using it as SU?

You'd want to run it as whatever user owns those files, which is hopefully not root. If you do an `ls -al` in the Snipe-IT project directory, what do you see?

(If they are owned by root, you can see [this article](https://snipe.net/2017/11/15/so-you-ran-composer-as-root/) to fix it.)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by ecord17** [comment]
thank you for the information. I will try to do the update based on the article that you gave me.
