### ISSUE TITLE
[Feature Request]: v6.1.2 update about

### ISSUE THREAD

**Issue by melihertasss** [grokability/snipe-it#13459]
### Is your feature request related to a problem? Please describe.

I'm sure there is, but I couldn't find it.

### Describe the solution you'd like

Hello, I am using v6.1.0 as snipe-it version. But I want to export it to v6.1.2. I tried several methods and failed. The resources on the internet are very limited, is there a documentation on how to do this?

**Comment by snipe** [comment]
>  But I want to export it to v6.1.2. 

I don't really understand the question. Why would you export it (and what does that mean) versus just upgrading it to 6.1.2?

**Comment by melihertasss** [comment]
By transferring, I mean updating, actually, I guess I couldn't express myself. Obviously I want to update to version 1.6.2

**Comment by snipe** [comment]
> I tried several methods and failed. 

Some more specifics about what you tried and what the outcome and output was would be helpful in troubleshooting this for you.

> The resources on the internet are very limited, is there a documentation on how to do this?

https://snipe-it.readme.io/docs/upgrading

Additionally, please don't remove the fields from the existing template. Information like what version of PHP you're running, whether it's a git install or not, etc are very helpful to us when we're trying to help people. 



<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div>🚧If you run into any issues upgrading...Please check the Common Issues &gt; Installation/Upgrading Issues section which provides solutions for commonly encountered installation / upgrading problems.📘Note:When available, please use the more detailed upgrade instructions for specific versions, avail...</div></blockquote>

**Comment by melihertasss** [comment]
When I want to update via git, when I check with git --version, I see the version that git is installed on, but when I run the php upgrade.php command, it does not update.

**Comment by snipe** [comment]
> it does not update.

Can you be more specific? What output are you seeing?

You should just be able to run `php upgrade.php` and it will do a lot of the work for you.

**Comment by melihertasss** [comment]
Snipe-IT version
v6.1.0 build 10161 (ga8ca3ad2a) architecture. I want to update this to v6.1.2. After running the php upgrade.php command, it seems that there is no problem as follows, but the version I am using does not go up. In the document you sent, it says that it will be enough for me to do this. Or I didn't understand.

![resim](https://github.com/snipe/snipe-it/assets/139988606/64b73891-1df6-426a-9aec-192ed7948e8a)

**Comment by snipe** [comment]
Please show the entire output of running the upgrade

**Comment by melihertasss** [comment]
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- validate some very basic .env file settings
- check your PHP version and extension requirements
- check directory permissions
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking .env file:
- Your .env is located at /var/www/snipe-it/.env
--------------------------------------------------------

√ Your APP_KEY is not blank.
√ Your APP_URL is not null or blank. It is set to http://10.59.100.99
√ Your APP_URL is set to http://10.59.100.99 and starts with the protocol (https:// or http://)
√ Your APP_URL (http://10.59.100.99) does not have a trailing slash.

--------------------------------------------------------
STEP 2: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (8.1.2-1ubuntu2.13) is at least 7.4.0 - continuing...
FYI: The php.ini used by this PHP is: /etc/php/8.1/cli/php.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ sodium is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 3: Checking directory permissions:
--------------------------------------------------------

√ /var/www/snipe-it/bootstrap/cache is writable
√ /var/www/snipe-it/storage is writable
√ /var/www/snipe-it/storage/logs is writable
√ /var/www/snipe-it/storage/logs/laravel.log is writable
√ /var/www/snipe-it/storage/framework is writable
√ /var/www/snipe-it/storage/framework/cache is writable
√ /var/www/snipe-it/storage/framework/sessions is writable
√ /var/www/snipe-it/storage/framework/views is writable
√ /var/www/snipe-it/storage/app is writable
√ /var/www/snipe-it/storage/app/backups is writable
√ /var/www/snipe-it/storage/app/backup-temp is writable
√ /var/www/snipe-it/storage/private_uploads is writable
√ /var/www/snipe-it/public/uploads is writable

--------------------------------------------------------
STEP 4: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Determining files to backup...
Zipping 193 files and directories...
Created zip containing 193 files and directories. Size is 2.54 MB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!


--------------------------------------------------------
STEP 5: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.

--------------------------------------------------------
STEP 6: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
fatal: detected dubious ownership in repository at '/var/www/snipe-it'
To add an exception for this directory, call:

        git config --global --add safe.directory /var/www/snipe-it
fatal: detected dubious ownership in repository at '/var/www/snipe-it'
To add an exception for this directory, call:

        git config --global --add safe.directory /var/www/snipe-it
fatal: detected dubious ownership in repository at '/var/www/snipe-it'
To add an exception for this directory, call:

        git config --global --add safe.directory /var/www/snipe-it
fatal: detected dubious ownership in repository at '/var/www/snipe-it'
To add an exception for this directory, call:

        git config --global --add safe.directory /var/www/snipe-it
-- -- --
--------------------------------------------------------
STEP 7: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ Deleting bootstrap/cache/services.php. It is no longer used.
√ No bootstrap/cache/config.php, so nothing to delete.
√ No vendor/symfony/translation/TranslatorInterface.php, so nothing to delete.

-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
STEP 8: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- Running the app in production mode.
-- We couldn't find a local composer.phar. No worries, trying globally.
Since you are running composer globally, we won't try to update it for you.
If you run into issues with this step, try running `composer self-update`
before running this updater again

Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package fruitcake/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
84 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
Generating optimized autoload files
Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: maatwebsite/excel
Discovered Package: mediconesystems/livewire-datatables
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
Generated optimized autoload files containing 8824 classes

Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: maatwebsite/excel
Discovered Package: mediconesystems/livewire-datatables
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
--------------------------------------------------------
STEP 9: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
STEP 10: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
STEP 11: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!
--------------------------------------------------------

user@dsu59env01:/var/www/snipe-it$

**Comment by snipe** [comment]
Step 6 in the output is telling you what's wrong. Get that sorted and then try running the upgrader again and it should work

**Comment by melihertasss** [comment]
Hello,

First of all, thank you for your support. Thanks to your answers, I reached the end and managed to upgrade to version 6.1.

git config --global --add safe.directory /var/www/snipe-it


after running the command

php. I ran the upgrade.php command and the problem went away.

thx

**Comment by rkthamizhan** [comment]
STEP 6: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
Already on 'master'
error: unable to unlink old 'public/uploads/barcodes/invalid_barcode.gif': Permi                                                                                                             ssion denied
error: unable to unlink old 'storage/private_uploads/signatures/.gitkeep': Permi                                                                                                             ssion denied
fatal: Could not reset index file to revision 'HEAD'.
error: The following untracked working tree files would be overwritten by merge:
        .github/workflows/tests.yml
        app/Http/Controllers/Api/LabelsController.php
        app/Http/Controllers/LabelsController.php
        app/Http/Livewire/CategoryEditForm.php
        app/Http/Transformers/LabelsTransformer.php
        app/Models/Labels/DefaultLabel.php
        app/Models/Labels/Field.php
        app/Models/Labels/FieldOption.php
        app/Models/Labels/Label.php
        app/Models/Labels/RectangleSheet.php
        app/Models/Labels/Sheet.php
        app/Models/Labels/Sheets/Avery/L7162.php
        app/Models/Labels/Sheets/Avery/L7162_A.php
        app/Models/Labels/Sheets/Avery/L7162_B.php
        app/Models/Labels/Sheets/Avery/L7163.php
        app/Models/Labels/Sheets/Avery/L7163_A.php
        app/Models/Labels/Sheets/Avery/_5267.php
        app/Models/Labels/Sheets/Avery/_5267_A.php
        app/Models/Labels/Sheets/Avery/_5520.php
        app/Models/Labels/Sheets/Avery/_5520_A.php
        app/Models/Labels/Tapes/Brother/TZe_12mm.php
        app/Models/Labels/Tapes/Brother/TZe_12mm_A.php
        app/Models/Labels/Tapes/Brother/TZe_24mm.php
        app/Models/Labels/Tapes/Brother/TZe_24mm_A.php
        app/Models/Labels/Tapes/Dymo/LabelWriter.php
        app/Models/Labels/Tapes/Dymo/LabelWriter_30252.php
        app/Presenters/LabelPresenter.php
        app/View/Label.php
        database/migrations/2022_10_25_215520_add_label2_settings.php
        database/migrations/2023_08_13_172600_add_email_to_companies.php
        database/migrations/2023_08_21_064609_add_name_ordering_to_settings.php
        public/js/dist/all-defer.js
        resources/lang/en/admin/labels/message.php
        resources/lang/en/admin/labels/table.php
        resources/views/livewire/category-edit-form.blade.php
        resources/views/models/custom_fields_form_bulk_edit.blade.php
        resources/views/partials/label2-field-definitions.blade.php
        resources/views/partials/label2-preview.blade.php
        tests/Feature/Api/Users/UpdateUserApiTest.php
        tests/Feature/Livewire/CategoryEditFormTest.php
        tests/Feature/Reports/CustomReportTest.php
Please move or remove them before you merge.
Aborting
-- Saved working directory and index state WIP on master: c52a1f94d Merge remote                                                                                                             -tracking branch 'origin/develop'
-- M    public/uploads/barcodes/invalid_barcode.gif
M       storage/private_uploads/signatures/.gitkeep
Your branch is behind 'origin/master' by 539 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
-- Updating c52a1f94d..8384786e8

**Comment by snipe** [comment]
Hi there - this issue is closed and doesn't seem directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
