### ISSUE TITLE
Cant clone accessories

### ISSUE THREAD

**Issue by Anagastes** [grokability/snipe-it#13464]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I can only clone accessories as admin, as normal user with full access in this category it does not work.

### Reproduction steps

1. Create an new group with full access to accesoires
2. Create a user without any permissions and add him to this new group.
![grafik](https://github.com/snipe/snipe-it/assets/17494592/a7689ca3-cec1-4651-8156-d67933c85826)
3. Login as user and try to clone an accessore

### Expected behavior

Can clone accessories with full access.

### Screenshots

![grafik](https://github.com/snipe/snipe-it/assets/17494592/95e2cb52-2345-4fe1-b369-6cd05b58c4fc)

### Snipe-IT Version

8.83.22

### Operating System

Debian GNU/Linux 12 (bookworm)

### Web Server

Apache

### PHP Version

8.1.21 

### Operating System

Arch Linux

### Browser

All Browsers (Chrome, Brave, Vvaldi, Firefox...)

### Version

Firefox 116.0 (64-Bit)

### Error messages

```shell
[PHP Modules]
apcu
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
json
ldap
libxml
mbstring
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

fresh install
install.sh was used

**Comment by snipe** [comment]
This is fixed on develop via #13470
