### ISSUE TITLE
Question - How to Change FQDN

### ISSUE THREAD

**Issue by felicemassaro** [grokability/snipe-it#13462]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Sorry for my ignorance. I did try to found out from the documentation but I did not found anything about this.
Where do you change the FQDN  given during the setup?

Thanks

### Reproduction steps

none

### Expected behavior

none

### Snipe-IT Version

6.1.2

### Operating System

Ubuntu

### Web Server

Apache2

### PHP Version

8.1.2-1ubuntu2.13

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuration#required-basic-app-settings

The setting you want is APP_URL in your .env config 

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#required-basic-app-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.Don't be intimidated by the length of this page. The configuratio...</div></blockquote>
