### ISSUE TITLE
TCPDF ERROR: Error in 1D barcode string - Labelling

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13472]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

TCPDF ERROR: Error in 1D barcode string

### Reproduction steps

1. Upgraded
2. turned on New Label Engine
video shows errors

### Expected behavior

errors in vid

### Screenshots

https://github.com/snipe/snipe-it/assets/114973646/c558c39b-194c-4f29-9263-ac8d747a6ec9

### Snipe-IT Version

 v6.1.2 build 10938 (g32747cafd) 

### Operating System

ubuntu

### Web Server

apache

### PHP Version

 8.1.22

**Comment by snipe** [comment]
We're still actively patching the new label system. Please stick with the classic version for now.

**Comment by jayavman** [comment]
no worries

**Comment by snipe** [comment]
I can't reproduce this one btw :(

**Comment by snipe** [comment]
Are you sure your asset tags are compatible with the different types of 1D barcodes? Certain 1D barcodes require certain character lengths, no special characters, etc - so it wouldn't be super surprising if the template you're trying out uses a 1D barcode that doesn't jibe with the allowable format per the 1D barcode specs.

**Comment by jayavman** [comment]
<img width="1215" alt="Screenshot 2023-08-16 at 11 42 26 am" src="https://github.com/snipe/snipe-it/assets/114973646/8a276698-7097-4c32-83e8-74562b76abb7">

**Comment by snipe** [comment]
Seems like it's only happening with labels that have 1D barcodes enabled. I can't tell from your screenshot whether you have any asset tags with non-alphanumeric data in them, but C138 only allows alphanumeric. https://en.wikipedia.org/wiki/Code_128 

<blockquote><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/GS1-128_product_barcode.jpg/640px-GS1-128_product_barcode.jpg" width="48" align="right"><div><strong><a href="https://en.wikipedia.org/wiki/Code_128">Code 128 - Wikipedia</a></strong></div></blockquote>

**Comment by jayavman** [comment]
that would be the problem. All our assets have # in front of them

eg #AST202010

**Comment by snipe** [comment]
You'd need to pick a different 1D barcode format then I think, since it goes against the spec.
