### ISSUE TITLE
LDAP Sync fails when location is not set

### ISSUE THREAD

**Issue by winkelement** [grokability/snipe-it#13478]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to sync with LDAP without setting a location the Application crashes.
When selecting a location LDAP sync is successful.

### Reproduction steps

1. Set up LDAP Sync
2. Got to [snip.it]/users/ldap 
3. Synchronize without selecting a location from the dropdown

### Expected behavior

LDAP sync should be successful. Location should be empty.

### Snipe-IT Version

v6.1.2 build 10938 (g32747cafd)

### Operating System

Docker

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.13

### Operating System

MacOS

### Browser

Chrome

### Error messages

```shell
[15:42:20] LOG.debug: LDAP search executed successfully.
[15:42:20] LOG.debug: okay, at least one more page to go!!!
[15:42:20] LOG.debug: Total count is: 64
[15:42:20] LOG.debug: That location is invalid or a location was not provided, so no location will be assigned by default.
[15:42:20] LOG.error: ErrorException: Attempt to read property "id" on null in /var/www/html/app/Console/Commands/LdapSync.php:246
[15:42:20] LOG.error: Attempt to read property "id" on null {"userId":1,"exception":{}}
```

**Comment by winkelement** [comment]
Ok i tried the latest development version (v6.1.2 build 10938 (g32747cafd)) which i think contains https://github.com/snipe/snipe-it/pull/13397.
Result: No error when syncing without location set but now the location for ALL users get deleted 😕

**Comment by uberbrady** [comment]
That's fixed if you pull the latest from master.

**Comment by winkelement** [comment]
@uberbrady You mean "sync without location error" is fixed or "all locations get deleted" is fixed?

**Comment by uberbrady** [comment]
Do you have a "LDAP Location" Attribute set? If you do and the value of that is blank, it will (rightfully) unset your location.

**Comment by winkelement** [comment]
No "LDAP Loacation" is not set.
![Bildschirmfoto 2023-08-16 um 17 31 52](https://github.com/snipe/snipe-it/assets/3525191/9b689a81-986c-4223-bb7b-9b377cc4e066)

**Comment by winkelement** [comment]
I'm just a bit confused as this used to work before: 
* When selecting no location, newly imported users would have empty location. Existing users were not affected
* When selecting a location new imported users get that location assigned. Existing users were not affected.

**Comment by winkelement** [comment]
I think it is related to https://github.com/snipe/snipe-it/issues/13373 so i'll wait for https://github.com/snipe/snipe-it/pull/13391 and see if it fixes this.

**Comment by winkelement** [comment]
It does! Great i'm closing this issue then.

**Comment by snipe** [comment]
Awesome, thanks for letting us know it worked!
