### ISSUE TITLE
Check-In and Check-Out not sending mails but mailtest successfull

### ISSUE THREAD

**Issue by HtHNightwolf** [grokability/snipe-it#13486]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I check in or check out devices that have the checkbox enabled to send mails to the user, it simply does not do that. No mails seem to go out.
The mail self-test button in the settings returns success (green). Sadly I can not choose to which address the testmail goes, it can only send to the from-address.

### Reproduction steps

1. Install Snipe-IT
2. Configure a device category to recieve mails when checked it/out
3. Configure and test SMTP setting of Snipe-IT
4. Check out a device that should send a mail
5. User recieves no mail
...

### Expected behavior

User revieces a mail when checking in/out devices that have the checkbox set.

### Snipe-IT Version

newest

### Operating System

Windows Server 2016

### Web Server

Apache

### PHP Version

8.2.4

**Comment by snipe** [comment]
That functionality does actually work, but I should mention that you're using PHP 8.2.x, which Snipe-IT v6.x does not work with, per our requirements documentation. I'd need your error & app logs to help further, but TBH, I'm not even sure how it's working at all given you're on PHP 8.2.x.

**Comment by HtHNightwolf** [comment]
Hmh, my question was 2 weeks old. 
By now I have long fixed the issue by reading myself into the options even deeper and we have already set up all components with quite a bit of troubleshooting. Even inserted two dozen models, 15 manufacturers and created 204 assets already. Employees are getting mails with device acceptance links, SSL certificate is working. All within our PHP version.

As a result of me setting it up twice now, I can tell that Snipe-IT has some serious how-to issues. Especially regardibng Windows + Apache.

But at least it works. Pretty good even ... well at least after you understand things that the HowTo assumes you already know instead of explaining it ... grml
