### ISSUE TITLE
[Feature Request]: Suppliers page url is not displayed

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#13487]
### Is your feature request related to a problem? Please describe.

On the Suppliers page, the column "URL" is not displayed, even though, the field is set in the entry.

https://demo.snipeitapp.com/suppliers

![image](https://github.com/snipe/snipe-it/assets/112496896/b4122e66-4d40-437c-9b7c-b213277da248)
![image](https://github.com/snipe/snipe-it/assets/112496896/502133a8-9a87-4dd6-8b83-953c75daf4cf)

### Describe the solution you'd like

The URL should be displayed, like on the manufacturer page.

https://demo.snipeitapp.com/manufacturers

![image](https://github.com/snipe/snipe-it/assets/112496896/96518e6c-3166-466a-9029-86c0d6608260)

**Comment by floschoepfer** [comment]
Woa, that was fast!💪🏼

**Comment by snipe** [comment]
![ArrowWOevenLooking,](https://github.com/snipe/snipe-it/assets/197404/b90ad3df-8f08-4262-ae9d-aa172ce01577)
