### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by thasleemnazeer** [grokability/snipe-it#13493]
### Is your feature request related to a problem? Please describe.

I need to limit editing for the serial number, manufacturer, and model of assets. All other fields should be open for editing. Asset creation and deletion are restricted. However, our site engineers need permission to update asset details, excluding the manufacturer, model, and serial number.

### Describe the solution you'd like

Introduce the capability to customize asset field editing permissions. For instance, users should be able to edit all fields except for manufacturer, model, and serial number. This functionality would enhance control and data accuracy in asset management.

**Comment by snipe** [comment]
This is not on the short term roadmap.
