### ISSUE TITLE
[Feature Request]: Bulk Audit Scan Qr Code

### ISSUE THREAD

**Issue by hakihosting** [grokability/snipe-it#13505]
### Is your feature request related to a problem? Please describe.

When we do Bulk Audit scan is it possible to Scan the QR code generated by the labels.

### Describe the solution you'd like

I think it can be a good feature to do more and fast audi , just scan Qr code

**Comment by snipe** [comment]
Bulk auditing currently used the 1D barcode (for a barcode scanner), not QR or other 2D barcodes. https://demo.snipeitapp.com/hardware/bulkaudit 

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/bulkaudit">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
