### ISSUE TITLE
[Feature Request]: Quick Scan Checkin in by Asset Name

### ISSUE THREAD

**Issue by hakihosting** [grokability/snipe-it#13503]
### Is your feature request related to a problem? Please describe.

Hello , 
Is it possible to implement in the Quick Scan Checkin by Asset Name and not the Asset TAG ?

### Describe the solution you'd like

Possibility to check in by Asset name

**Comment by snipe** [comment]
Asset names are not required to be unique, so this would not be something on our short term roadmap.
