### ISSUE TITLE
[Feature Request]: Update Asset Model to have Financial INFO

### ISSUE THREAD

**Issue by hakihosting** [grokability/snipe-it#13504]
### Is your feature request related to a problem? Please describe.

When we create an Asset model is not possible to set info like : 

Order Related Information
Optional Information

### Describe the solution you'd like

If it s possible to have when we create a model to have the fields : 

Order Number
Purchase Date
EOL Date
Supplier
Purchase Cost

**Comment by snipe** [comment]
That’s not possible at this time. Order info is often not associated with a particular model, since it’s very common to get different assets from different sources. Those are set at the asset level.

**Comment by hakihosting** [comment]
I understand your reasoning but when we place orders with our suppliers. For example, we buy 100 laptops at the same price if we have to modify each asset to fill in the financial information, I don't find that practical.

Perhaps another solution would be to implement a Supplier purchase section and from there create a link from the asset to the supplier purchase.
