### ISSUE TITLE
Email Alerts for Expiring License do not work

### ISSUE THREAD

**Issue by tiennv3011** [grokability/snipe-it#13512]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello friends, my problem is, i can send email test but alert email for ExpiringLicense  do not work, I haven't received any emails about license expiration.

### Reproduction steps

1. admin setting
2. Notification 
3. Notification 
...

### Expected behavior

send alerts to specified email

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/142978084/6a1ac3f6-8c99-4d8d-85e9-99a4fc3fd71c)
![image](https://github.com/snipe/snipe-it/assets/142978084/c3ee0187-caf5-4bc7-a3ae-cc8b571bb84e)
![image](https://github.com/snipe/snipe-it/assets/142978084/632a72a5-2a5e-44dc-976b-d5348630ad2d)
![image](https://github.com/snipe/snipe-it/assets/142978084/92564b8e-0436-4329-bd66-720e8c680cdf)
![image](https://github.com/snipe/snipe-it/assets/142978084/f4e3b81a-7af3-4817-b6d8-a65bda009b26)

### Snipe-IT Version

v6.1.2

### Operating System

Windows server 2019

### Web Server

IIS

### PHP Version

8.0.29

### Operating System

Windows 10

### Browser

Chrome

**Comment by snipe** [comment]
They definitely work - we send out thousands of those emails a week. Did you set up the cron job to actually send the emails?

**Comment by tiennv3011** [comment]
> They definitely work - we send out thousands of those emails a week. Did you set up the cron job to actually send the emails?

Thank you for responding. Where do I need to set up cron job? Thanks you

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuring-alerts-backups

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuring-alerts-backups">Configuring Alerts & Backups</a></strong></div><div>Starting from Snipe-IT v3.0, all automated tasks are handled via the scheduler. To set a cron job to run every minute to ping the scheduler:Shell * /path/to/php /path/to/artisan schedule:run &gt;&gt; /dev/null 2&gt;&amp;1 The scheduler already knows how often it should trigger the individual tasks, ...</div></blockquote>

**Comment by tiennv3011** [comment]
> https://snipe-it.readme.io/docs/configuring-alerts-backups
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/28eaa7188a7b94b78b85ae21df3fa2c990ab7a61a734948cd65b8137092e2c72/68747470733a2f2f736e6970652d69742e726561646d652e696f2f66617669636f6e2e69636f">Snipe-IT Documentation**[Configuring Alerts & Backups](https://snipe-it.readme.io/docs/configuring-alerts-backups)**Starting from Snipe-IT v3.0, all automated tasks are handled via the scheduler. To set a cron job to run every minute to ping the scheduler:Shell * /path/to/php /path/to/artisan schedule:run >> /dev/null 2>&1 The scheduler already knows how often it should trigger the individual tasks, ...

I have successfully accomplished it, thank you very much !

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuring-alerts-backups">Configuring Alerts & Backups</a></strong></div><div>Starting from Snipe-IT v3.0, all automated tasks are handled via the scheduler. To set a cron job to run every minute to ping the scheduler:Shell * /path/to/php /path/to/artisan schedule:run &gt;&gt; /dev/null 2&gt;&amp;1 The scheduler already knows how often it should trigger the individual tasks, ...</div></blockquote>
