### ISSUE TITLE
SQLSTATE[42000] with install and french language

### ISSUE THREAD

**Issue by SignauxGirod** [grokability/snipe-it#13510]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Error on Create Database Tables

Cause by " ' " not escape

### Reproduction steps

1. Have set language of system to french
2. Fresh install of Snipe-It

### Expected behavior

A workaround to finish install (modify code to escape character on query ?) 

### Snipe-IT Version

6.1.2

### Operating System

Linuxmint

### Web Server

Apache

### PHP Version

8.1

### Error messages

```shell
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'actif=name;Série =serial;Modèle=model.name;'' at line 1 (SQL: alter table `settings` add `label2_enable` tinyint(1) not null default '0', add `label2_template` varchar(191) null default 'DefaultLabel', add `label2_title` varchar(191) null, add `label2_asset_logo` tinyint(1) not null default '0', add `label2_1d_type` varchar(191) not null default 'default', add `label2_2d_type` varchar(191) not null default 'default', add `label2_2d_target` varchar(191) not null default 'hardware_id', add `label2_fields` varchar(191) not null default 'Nom de l'actif=name;Série =serial;Modèle=model.name;')`
```

**Comment by snipe** [comment]
I’m not sure how French would matter here. The table and column names are in english. Can you provide any additional info?

**Comment by SignauxGirod** [comment]
If you check error message : `check the manual that corresponds to your MySQL server version for the right syntax to use near 'actif=name;`, you can see that the problem is the " ' " character in "Nom de l'actif" on the query.

If i understand the query, it's a default value translate not a column name.

**Comment by snipe** [comment]
I saw the message, but I don’t know where `actif=name` would be coming from. We can handle accents, apostrophes etc in field values, but there isn’t really a case I can think of where the column names would be defined by user input.

**Comment by SignauxGirod** [comment]
I don't know how to help you much more.

I saw in the Stack that query data seems to be build here :

`public function up()

    {

        Schema::table('settings', function (Blueprint $table) {

            $table->boolean('label2_enable')->default(false);

            $table->string('label2_template')->nullable()->default('DefaultLabel');

            $table->string('label2_title')->nullable()->default(null);

            $table->boolean('label2_asset_logo')->default(false);

            $table->string('label2_1d_type')->default('default');

            $table->string('label2_2d_type')->default('default');

            $table->string('label2_2d_target')->default('hardware_id');

            $table->string('label2_fields')->default(

                trans('admin/hardware/form.name').'=name;'.

                trans('admin/hardware/form.serial').'=serial;'.

                trans('admin/hardware/form.model').'=model.name;'

            );

        });

    }`

it's in 2022_10_25_215520_add_label2_settings.php

**Comment by snipe** [comment]
Ahh - that actually helps a LOT, ty. I’ll get this sorted for you today.

**Comment by SignauxGirod** [comment]
Thank you ! :)

**Comment by snipe** [comment]
Fix is on master now - let me know how you make out

**Comment by SignauxGirod** [comment]
Thank's, i try it and come back for the result :)

**Comment by SignauxGirod** [comment]
it's working like a charm !

thank you

**Comment by snipe** [comment]
Excellent! Glad you’re sorted. Sorry for the trouble!
