### ISSUE TITLE
Select File... button size (File upload modal window)

### ISSUE THREAD

**Issue by MaksaUniver** [grokability/snipe-it#13521]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

It's quite simple. When screen is wider than 992px, Select File... button is fixed to 25% width from total width of modal window. That by itself is not a issue with English translation, but it is when translated text is longer. You can see it on first screenshot. Second screenshot is when screen width is less than 992px. Button takes the full width and the issue is no longer present.

### Reproduction steps

1. Open File Upload modal window with screen wider than 992px,
2. Open browser's developer tools and find the button text
3. Change text to something way longer (20+ characters)

### Expected behavior

Button size should auto resize based on the width of the text.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/96291111/03b12e7e-8433-4ba4-9999-b83e9d8e230e)
![image](https://github.com/snipe/snipe-it/assets/96291111/8143fdb5-3fea-4fd0-86ed-ddffcc05d1bd)

### Snipe-IT Version

6.1.2

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Edge

### Version

116

**Comment by snipe** [comment]
I'm not really sure what the solution is here, since it's not really possible (or at least not straightforward) to dynamically change button width based on the amount of text inside it. We can dynamically resize the button based on the screen width, but it looks pretty weird in shorter languages having a gigantic button with only a little text on it.

**Comment by MaksaUniver** [comment]
I've experimented with different classes, and I believe the perfect one is **col-md-12**. Button size itself will be as wide as text, and maximum width will be full modal window width.

![image](https://github.com/snipe/snipe-it/assets/96291111/7daa60be-5153-4776-9b49-e2090412ace8)

**Comment by snipe** [comment]
I'm aware of what `col-md-12` does, but that changes the layout, and on smaller text options, it means that the layout will be inconsistent. Once you select a file (or several), the space to the right is used to display the filenames of what you selected. Pushing content down in modals after they have loaded can create weird behavior, especially on mobile.

**Comment by MaksaUniver** [comment]
I'm sure you are more aware of issues with layout, but I don't see the problem when all divs are set with **col-md-12**. Whatever the decision is, you can close this issue as I won't bother you with it anymore. Cheers!

![image](https://github.com/snipe/snipe-it/assets/96291111/5cc1322e-6d52-4a91-ac79-f1db7de0636d)

**Comment by snipe** [comment]
This fix is on master now
