### ISSUE TITLE
Fail to upload image on acessory menu

### ISSUE THREAD

**Issue by Morg-sys** [grokability/snipe-it#13524]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, 

I have a problem when I upload image on acessory menu , I have eror 500. 
Nothing on access.log. 

I add in .env file then restart apache service. 
# --------------------------------------------
# REQUIRED: UPLOADED FILE STORAGE SETTINGS
# --------------------------------------------
PRIVATE_FILESYSTEM_DISK=local
PUBLIC_FILESYSTEM_DISK=local_public

No sucess. 

Can you help me please ? 

Thanks for all

### Reproduction steps

1. I create a new acessory
2. I complete all filed 
3. I upload image
...

### Expected behavior

When I finalized the process the new accesory must display in acessory menu. 

### Snipe-IT Version

5.4.1

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.0.3

### Browser

Google chrome

**Comment by snipe** [comment]
You'd have to upgrade your version of Snipe-IT. We're not supporting v5.x anymore, as we're about to release v7.

**Comment by Morg-sys** [comment]
Thanks for your answer, For this upgrade, It's better to upgrade toward minor version or it's possible to upgrade about v5 to v7 ?
