### ISSUE TITLE
Custom Asset Report does not correct report EOL date

### ISSUE THREAD

**Issue by godnroc** [grokability/snipe-it#13531]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Custom asset reports always report EOL date as calculated using the Purchase Date and EOL Rate.

### Reproduction steps

1. Create a new asset with a model that has an EOL rate OR select an existing asset that has a model with an EOL rate
2. Set the assets EOL date to anything besides what would have been calculated and save the asset.
3. Generate a new custom asset report with the EOL listed.
4. Verify the data provided for the asset does not match what was set in step 2.

### Expected behavior

The Custom Asset Report should retrieve the data from the EOL Date field.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/2201722/690c2bc9-df7a-48d2-9d48-970327229e72)
![image](https://github.com/snipe/snipe-it/assets/2201722/3d9224e2-a2b6-4cd2-856a-9bf31a3d82ee)

### Snipe-IT Version

6.1.2

### Operating System

Hosted

### Web Server

Hosted

### PHP Version

8.1.21

### Operating System

Windows

### Browser

Edge

### Version

116.0.1938.54

### Additional context

Snipe-IT running through paid hosted service.

**Comment by Zack01235** [comment]
I am also getting inaccuracies with my custom report pulls.

**Comment by snipe** [comment]
> I am also getting inaccuracies with my custom report pulls.

@Zack01235 the exact same issue or something else? A little more detail would be helpful here.
