### ISSUE TITLE
LDAP Passwords aren't Syncing

### ISSUE THREAD

**Issue by Tyree** [grokability/snipe-it#13532]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have LDAP working and it will sync users from the LDAP server, but if passwords change for a user already synced to Snipe-It, the password does not update in Snipe-It.
I'm having to use my old LDAP password to log in to Snipe-It. Synced LDAP users several times, password does not update.

### Reproduction steps

1. Sync LDAP users
2. Change LDAP user password
3. Sync LDAP users
4. Attempt log in to Snipe-It with new password - Doesn't work.
5. Use old password, works.

### Expected behavior

Usernames and Passwords should stay in sync with LDAP

### Snipe-IT Version

v6.1.2 build 10938 (g32747cafd)

### Operating System

unRAID 6.12

### Web Server

Docker

### PHP Version

8.1.22

**Comment by snipe** [comment]
LDAP Password syncing doesn't work that way. It only syncs on successful LDAP login. So a user enters their LDAP login, successfully authenticates with the LDAP server via Snipe-IT, and the password gets synced. Snipe-IT has no way of retrieving LDAP passwords from your directory, so there's no other way to do it.

**Comment by Tyree** [comment]
So how do you update the password on Snipe-It? If I go to edit user, it says it's handled by LDAP. So I'm just stuck with the old password? Have to delete the user and re-sync? Then everything checked out to that user gets reset, right? 
I get that there's no way for Snipe-It to get the password from LDAP, but there has to be some way to update the password.
On login, does Snipe not reauthenticate with the LDAP server? Shouldn't the old password be kicked back as wrong and then when the user puts in the correct password, authenticated by LDAP, then that password is updated in Snipe?

**Comment by uberbrady** [comment]
I suspect your LDAP authentication setup isn't working. Syncing works, and your LDAP auth setup *used* to work, in the past. So when users successfully logged in in the past, and you had 'password syncing' enabled, the password saved to Snipe-IT. But now, when their LDAP password has changed, and they try to log in, and your LDAP auth query no longer works, it fails back down to the saved password.

You could test by creating a new user in your directory, doing an LDAP sync, and then trying to authenticate with said user. I suspect it will just not work, period.

**Comment by Tyree** [comment]
I created two new users that had never logged in (I had to run LDAP sync for them to show up in the People list). I just logged in with one of them and I got in fine. LDAP connect/auth seems to be working as far as I can tell. It just keeps wanting me to sign in with my old password, though.

**Comment by Tyree** [comment]
So maybe signing in with a new user gave it a kick. For giggles, I went to log in with my new password and it worked for the first time. Went back and tried my old password and it errored as expected.
Seems like it's working now...
