### ISSUE TITLE
User search gives results from other company

### ISSUE THREAD

**Issue by PatrickSmits** [grokability/snipe-it#13540]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When a user from a company opens the 'People' page, it only display's the people of his own company.
Hoewever, when you do a search for a user and this matches an username in another company, the result also displays these users.
When you click on an user from another company, an error paged is being displayed :

403 Forbidden.
Sad panda. You are not authorized to do the thing. Maybe [return to the dashboard](https://assets.samhosting.nl/), or contact your administrator.

### Reproduction steps

1. Go to People
2. Do a search for a part of a username which matches users from multiple companies
3.
...

### Expected behavior

The expected behavior is that the results only displays users from the same company, not from other companies. 

### Snipe-IT Version

v6.1.2 build 10938 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2

### Operating System

Windows

**Comment by marcusmoore** [comment]
Thank you for reporting this @PatrickSmits. I just opened a PR that fixes the issue.

**Comment by PatrickSmits** [comment]
Hello Marcus, 

Thank you for your quick response and the opened PR.

**Comment by marcusmoore** [comment]
Hi @PatrickSmits, the PR has been merged to master and will be included in the next release (or is available now if you're using the master branch).
