### ISSUE TITLE
Test LDAP Synchronization returns users but Test LDAP Login fails to bind

### ISSUE THREAD

**Issue by oalhambra** [grokability/snipe-it#13554]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm trying to connect snipe-it to an LDAP server hosted on a 389-Directory server. I have successfully managed to get the users with the Test LDAP Sync button. However, I cannot get it to work with the Test LDAP Login.
I have been doing some debugging and it seems the ldap bind is successfull, but the ldap search returns no entries (to clarify, ldap search is successful, but returns 0 entries)
I have tried using the filter query in the 389-Directory server and I get results there.

See screenshots for details on my configuration

### Reproduction steps

1. Configure LDAP
2.
3.
...

### Expected behavior

Test Ldap Login success

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/9163615/1cf78726-3c76-44c9-b422-5ba3004deec4)
![image](https://github.com/snipe/snipe-it/assets/9163615/369a0e30-31cc-4e55-a43c-d48d475a2a78)
![image](https://github.com/snipe/snipe-it/assets/9163615/409c2f61-feb7-4257-81d9-558f3fc99ef3)

### Snipe-IT Version

v6.1.2 - build 10938 (master)

### Operating System

Docker on SLES 15

### Web Server

Apache/2.4.52 (Ubuntu)

### PHP Version

8.1.2-1ubuntu2.14

### Operating System

Windows

### Browser

Google Chrome

### Version

116.0.5845.111

**Comment by oalhambra** [comment]
Nevermind, the LDAP was misconfigured, I have managed to login

**Comment by zhouxinjx** [comment]
I encountered the same problem, how did you solve it? @oalhambra

**Comment by oalhambra** [comment]
In my case, the LDAP was misconfigured.
When doing the LDAP sync, Snipe-IT uses the LDAP Bind username and password defined in the configuration, which you would expect to be the administrator user configured for the LDAP.
When doing the LDAP login, Snipe-IT makes an ldapsearch for the user with the credentials set in the form.
My problem was the users I had configured in the LDAP were missing permissions to see themselves in the tree, so performing an LDAP search was returning as successfull, but empty.

Hope it helps

**Comment by gokuking** [comment]
> In my case, the LDAP was misconfigured. When doing the LDAP sync, Snipe-IT uses the LDAP Bind username and password defined in the configuration, which you would expect to be the administrator user configured for the LDAP. When doing the LDAP login, Snipe-IT makes an ldapsearch for the user with the credentials set in the form. My problem was the users I had configured in the LDAP were missing permissions to see themselves in the tree, so performing an LDAP search was returning as successfull, but empty.
> 
> Hope it helps

Would you mind explaining how exactly am I supposed to do that? Adding permissions to see themselves? Is that something I'm supposed to to from AD side or from SNIPE IT?
