### ISSUE TITLE
[Feature Request]: Subcategory Field 

### ISSUE THREAD

**Issue by amannb** [grokability/snipe-it#13553]
### Is your feature request related to a problem? Please describe.

In the categories field, can we have an option for a subcategory for a product. For instance, you can have tablet as a main category and under it you can have subcategory of Android or IOS. In our organization, we have classification for the IT equipment which is classified as Standard or executive. 

### Describe the solution you'd like

Include an item for subcategory in the settings to create subcategory and link it to category.

**Comment by snipe** [comment]
That introduces a lot of additional complexity (layers of nesting, recursive queries, etc.) I don't see that not he short term roadmap.
