### ISSUE TITLE
[Feature Request]: View PDF files inside browser instead of downloading

### ISSUE THREAD

**Issue by themegabyte** [grokability/snipe-it#13562]
### Is your feature request related to a problem? Please describe.

No its not. PDF files can be downloaded perfectly. However it will be convenient to have this feature.

### Describe the solution you'd like

Similar to images, if there is a possibility of either viewing a PDF file in the same tab or a new one, would be a perfect solution.

### Describe alternatives you've considered

None right now. I can only download and then view it.

### Additional context

if I have to view I have to redownload a file which causes unessary downloading.
Similar to: #7055

**Comment by snipe** [comment]
We used to have them display online and people complained about that.
