### ISSUE TITLE
Uh oh!Snipe-IT thinks your URL is /setup, but your real URL is http://ip/setup Please update your APP_URL settings in your .env file

### ISSUE THREAD

**Issue by dst0007** [grokability/snipe-it#13568]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Pre-Flight Check

URL |   | Uh oh! Snipe-IT thinks your URL is /setup, but your real URL is http://10.41.23.60/setup Please update your APP_URL settings in your .env file

### Reproduction steps

1.Pre-Flight Check
2.URL |   | Uh oh! Snipe-IT thinks your URL is /setup, but your real URL is http://10.41.23.60/setup Please update your APP_URL settings in your .env file
3.
...

### Expected behavior

Pre-Flight Check

URL |   | Uh oh! Snipe-IT thinks your URL is /setup, but your real URL is http://10.41.23.60/setup Please update your APP_URL settings in your .env file

### Screenshots

![1693967000688](https://github.com/snipe/snipe-it/assets/143789004/6f6c8b48-59fb-4141-b6a8-e18888bd26d9)

### Snipe-IT Version

6.1.2

### Operating System

Centos7.9

### Web Server

Nginx 1.22.1

### PHP Version

8.1

**Comment by dst0007** [comment]
APP_URL=10.41.23.60

![1693967162448](https://github.com/snipe/snipe-it/assets/143789004/fd5956b7-00aa-440e-9fd0-4509cbb141d7)

**Comment by dst0007** [comment]
access http://10.41.23.60/ become http://10.41.23.60/10.41.23.60/setup

**Comment by snipe** [comment]
What's your APP_URL set to in your .env?

**Comment by dst0007** [comment]
APP_URL change to http://10.41.23.60 ，It's normal now
![image](https://github.com/snipe/snipe-it/assets/143789004/9caeaf3c-db79-4c5b-a14e-c40343473f3f)

**Comment by dst0007** [comment]
But moving on to the next step is not enough，Error creating database table ，500 SERVER ERROR
![image](https://github.com/snipe/snipe-it/assets/143789004/f8cd6a69-6983-4010-bfdf-de681b0f9cf6)

**Comment by dst0007** [comment]
![image](https://github.com/snipe/snipe-it/assets/143789004/57a86908-ba2c-4f83-8065-05a0f39348b7)
But when I entered the database, I saw that the database tables had already been created

**Comment by abhishekbaranawals** [comment]
> What's your APP_URL set to in your .env?

hi i download a project from snipit after setup its working fine but when i deploy on server its automatically to redirect to setup url  same code working on local please suggest

**Comment by snipe** [comment]
@abhishekbaranawals did you update the url in your env to the new server url?

**Comment by snipe** [comment]
@dst0007 What is in your app logs? I’d need to know what the error message is for the 500 error.

**Comment by dst0007** [comment]
＂GET /setup/migrate? HTTP/1.1＂ 500 6628 ＂http://10.41.23.60/setup＂ ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36＂

**Comment by lautito1** [comment]
That's the snipe acces.log, do you have the error.log file?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help 

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by ernestomarrero8** [comment]
> ＂GET /setup/migrate? HTTP/1.1＂ 500 6628 ＂[http://10.41.23.60/setup＂](http://10.41.23.60/setup%EF%BC%82) ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36＂

Did you fix this? @dst0007 i have the same issue

![image](https://github.com/snipe/snipe-it/assets/86329091/91f2a132-494c-4fbf-bacd-33f6e0dafb5b)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
