### ISSUE TITLE
after upgrade Ubuntu to 22.04 snipeIT won´t connect to DB Mysql

### ISSUE THREAD

**Issue by vtecaraujo** [grokability/snipe-it#13582]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After performing a Ubuntu upgrade to 22.04, upgrade appeared to go well. But I get the SNIPE-IT PRE FLIGHT page with a database error COULD NOT FIND DRIVER (SQL: select 2 + 2).

### Reproduction steps

1.
2.
3.
...

### Expected behavior

PHP |   | Yay!                          You're running PHP version 7.4.33. (7.2.5 or greater is required.)
URL |   | That URL looks right! Good job!
Database |   | D'oh! Looks like we can't connect to your database. Please update your database settings in your  .env file. Your database says: could not find driver (SQL: select 2 + 2)
Config File |   | Sweet. It doesn't look like your .env  file is exposed to the outside world. (You should double check this in a  browser though. You don't ever want anyone able to see that file. Ever.  Ever ever.) Click here to check now (This should return a file not found or forbidden error.)
Environment |   | Your app is set to production mode. Rock on!
File Owner |   | Your app files are owned by www-data. That doesn't look like a default root/admin account. Nice!
Permissions |   | Yippee! Your app storage directory seems writable.
Debug |   | Awesomesauce. Debug is either turned off, or you're  running this in a non-production environment. (Don't forget to turn it  off when you're ready to go live.)
Image Library |   | The GD library isn't installed. While this won't  prevent the system from working, you won't be able to generate labels or  upload images.

### Snipe-IT Version

5.2.0 build 6339

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.33

### Operating System

ubuntu

### Browser

Firefox

### Error messages

Database |   | D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: could not find driver (SQL: select 2 + 2)
```


### Additional context

_No response_

**Comment by uberbrady** [comment]
Maybe you're missing the php-mysql extension? The 'missing driver' notice definitely sounds like something along those lines.

**Comment by snipe** [comment]
@vtecaraujo Any updates?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
