### ISSUE TITLE
[Feature Request]: Bulk remove default location from users

### ISSUE THREAD

**Issue by thechenderson** [grokability/snipe-it#13599]
### Is your feature request related to a problem? Please describe.

I have around 100 users in Snipe and they have all been assigned a default location, however I since realised that by adding a default location, when I assign assets to them, the location of the asset is automatically set to the users default location and there is no easy way of changing it. 

### Describe the solution you'd like

I would like for the bulk edit option for users to be able to not only change the users location in bulk but also remove the users location, as in have the "x" in the selection box to remove the entry entirely.

### Describe alternatives you've considered

Manually going through every user and removing their location data.

**Comment by snipe** [comment]
This feature already exists, no?

<img width="706" alt="Screenshot 2023-09-14 at 10 57 36 PM" src="https://github.com/snipe/snipe-it/assets/197404/9ede7596-3618-4d8f-ba73-038da8e9dfa3">

**Comment by thechenderson** [comment]
Apologies, I've just realised that this is an existing feature and that I've not updated to the lastest version, thanks for getting back to me so quickly!

**Comment by snipe** [comment]
Thanks for the update. My favorite features to build are ones that already exist :D
