### ISSUE TITLE
Unable to Delete Models in Model Area

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13592]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If a model has no assets attached to it and you go into the model. You cannot delete the model, the only way to delete the model is to go back to the main model page and click on Delete. (refer to video)

### Reproduction steps

1.settings
2.models
3.go to model
4. delete model with no asset (brings up no response)
5. go back to model listing page and you can delete model from there
...

https://github.com/snipe/snipe-it/assets/114973646/84882d34-0522-4ca3-b355-3a1d5d856cbb

### Expected behavior

Be able to delete model from the model page.

### Snipe-IT Version

v6.2.0-pre build 11391 (g319cb2305)

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.1.22

**Comment by snipe** [comment]
This is on develop now
