### ISSUE TITLE
Unable to Remove Manufacturer

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13591]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Unable to remove Manufacturer even though no assets or models relating to the manufacturer. (refer to video)

### Reproduction steps

1.Settings
2.Manufacturer
3.Select Manufacturer
4. Grey out delete button on manufacturer

...

https://github.com/snipe/snipe-it/assets/114973646/0c00a2a5-cebe-4e82-b415-4aeb64d13e8f

### Expected behavior

be able to delete Manufacturers not paired to any models.

### Snipe-IT Version

 v6.2.0-pre build 11391 (g319cb2305) 

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.1.22

**Comment by inietov** [comment]
Can you delete it from `http(s)//snipe-it_URL/manufacturers` page?

![image](https://github.com/snipe/snipe-it/assets/653557/c54c77f5-ba36-4c9f-8af9-7c69d7916b94)

**Comment by jayavman** [comment]
> Can you delete it from `http(s)//snipe-it_URL/manufacturers` page?
> 
> ![image](https://user-images.githubusercontent.com/653557/267490591-c54c77f5-ba36-4c9f-8af9-7c69d7916b94.png)

Yes you can. 
Exact same issue with Model also.

**Comment by inietov** [comment]
That button is for bulk delete assets that come from that manufacturer. As no asset is selected in the list (because no asset associated to that manufacturer exist to begin) then the `go` button is not activated.

**Comment by jayavman** [comment]
So maybe it should be under the actions tab then. Otherwise in the direct Manufacturer item you cannot delete it from that page. (unlike Models)
<img width="440" alt="Screenshot 2023-09-13 at 9 45 46 am" src="https://github.com/snipe/snipe-it/assets/114973646/bb9d197f-1363-471b-b2d8-c38b7e57b8ae">
