### ISSUE TITLE
[Feature Request]: Оповещение об истекших лицензиях

### ISSUE THREAD

**Issue by volkodub** [grokability/snipe-it#13598]
### Is your feature request related to a problem? Please describe.

nginx version: nginx/1.18.0
PHP 7.4.3-4ubuntu2.19
SnipeIt  v6.2.0-pre - build 11391
не приходят оповещения о истекающих лицензиях. Что нужно настроить в cron? 

### Describe the solution you'd like

Нужно получать информацию о истекающих лицензиях на почту.

**Comment by volkodub** [comment]
![image](https://github.com/snipe/snipe-it/assets/142312446/1a218c26-007a-49c6-afb4-95f2841279aa)

**Comment by volkodub** [comment]
![image](https://github.com/snipe/snipe-it/assets/142312446/73352236-e7b7-4a26-a0fe-4df407d4fffe)

**Comment by UserGoodtm** [comment]
It seems to me that incorrect mail data is being entered. You may need to use a password not from the mail web interface, but created separately for the application (check the Yandex settings)

**Comment by volkodub** [comment]
Почта работает, Отправляются данные пользователей на почту,  и тд.

**Comment by volkodub** [comment]
* * * * * /path/to/php /path/to/artisan schedule:run >> /dev/null 2>&1 добавил вот эту команду в крон как указанно в мануале. но она не отрабатывает.

**Comment by UserGoodtm** [comment]
And in the license section, the required license has an expiration date (expiration date, expires)? For example, I used the built-in functionality, but I didn't touch the cron, and everything works for me

**Comment by UserGoodtm** [comment]
Just now I noticed that you have a prе version (not stable). Perhaps there really are flaws in it. In this case, you will probably have to wait for the response of the official product support.

**Comment by snipe** [comment]
@volkodub please post in English in the future. We don't speak Russian here, and it doesn't seem fair that we have to run everything through a translator to give you free help.

When you run `php artisan snipeit:expiring-alerts` from the Snipe-IT project root via command line, does anything pop up in your error logs? Are there actually any things that are expiring? I've tested this on master and it's working as expected.
