### ISSUE TITLE
500 on Signature/Acceptance

### ISSUE THREAD

**Issue by warrentahum-IT** [grokability/snipe-it#13593]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Everytime I sign or accept the asset it will give me a server error 500.  

### Reproduction steps

1.
2.
3.
...

### Expected behavior

I am expecting a notification that is accepted and it will go back to my account or dashboard 

### Snipe-IT Version

6.2

### Operating System

Windows

### Web Server

Apache

### PHP Version

8.1

### Operating System

Windows

### Browser

Chrome

**Comment by snipe** [comment]
We'd need to know what the specific error is in order to troubleshoot this. https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by snipe** [comment]
Any luck getting those logs?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by warrentahum-IT** [comment]
***@***.***

I get this error if I will try to upload an image or signature.

Best Regards,

Warren Tahum / Data and IT Support

Melbourne Phone: 03 9038 8267
Melbourne Office: Level 1, 689 Burke Road, Camberwell VIC 3124
Phil Phone: 0918 286 1382
Phil Office: Unit 17 Level 2 Ameluz Building, Sto. Entierro Street, Angeles City 2009
Web:  www.levera.com.au<http://www.levera.com.au/>

Share ***@***.***?anonymous&ep=pcard> link with someone who needs to be less busy and tell them to book a call with our Business Growth Specialist!

 [A picture containing font, graphics, design  Description automatically generated] [linkedin_003] <https://www.linkedin.com/company/linkwealthadvisersupport/?viewAsMember=true>  [facebook_003] <https://www.facebook.com/linkwealthadvisersupport>

DISCLAIMER: This email, including any attachments, may contain information that is confidential, commercially sensitive and may be subject to legal privilege. If you are not the intended recipient you must not read, use, disseminate, distribute or copy any part of this email, disclose its contents to any other party, or take any action in reliance on it. If you have received this email in error, please contact the sender immediately and delete this email. Warren Tahum and Levera Solutions Pty Ltd ABN 25 648 288 724 do not warrant that this email or any attachments are free from viruses or other defects. Please ensure that you check for viruses and defects prior to opening any attachments.
