### ISSUE TITLE
Sorting by age does not work properly

### ISSUE THREAD

**Issue by qay21** [grokability/snipe-it#13609]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Sorting assets by age is not giving accurate results. Asset order in the list is changed, but apparently not by age.

### Reproduction steps

1. Go to https://demo.snipeitapp.com/hardware
2. If not already displayed, add the "Age" column to the view
3. Click on the "Age" column to cycle between sorting modes (oldest first / youngest first)

### Expected behavior

When sorting on the age, we should get an orderer list of assets based on their calculated age.

### Screenshots

![capture](https://github.com/snipe/snipe-it/assets/87803479/b129971f-e238-4de5-88fc-b44950a1816c)

### Snipe-IT Version

Live demo

### Operating System

Live demo

### Web Server

Live demo

### PHP Version

Live demo

### Additional context

I first saw this problem on my company's production instance of SnipeIT, which is running Version v6.1.1 - build 10847 (master), dockerized.

I double-checked with the official live demo provided by SnipeIT, running an undisclosed version.

**Comment by snipe** [comment]
If I recall, that field isn't supposed to be sortable, since it's a calculated field.
