### ISSUE TITLE
Form not refreshing

### ISSUE THREAD

**Issue by seronet** [grokability/snipe-it#13607]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Unfortunately, no data comes when company and similar menus are selected.

### Reproduction steps

1.Create Asset

### Expected behavior

Form refresh

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/141667112/78f24741-f1c5-44ab-bec7-25932e7c61f6)

### Snipe-IT Version

6.1.2

### Operating System

Cpanel

### Web Server

Cpanel

### PHP Version

7.4

**Comment by snipe** [comment]
Please provide us with any available errors in your browser console and app logs. https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by seronet** [comment]
> Please provide us with any available errors in your browser console and app logs. https://snipe-it.readme.io/docs/getting-help
> 

Thank you for your answer. I did the installation with Softaculous on Cpanel. I don't see any error logs. No error is returned in Cpanel. I reinstalled from scratch twice and it didn't work. The same happens on the import screen. When I select delete it doesn't delete. There seems to be a renewal problem in general. I tried it with a different browser and it gave the same result.

![image](https://github.com/snipe/snipe-it/assets/141667112/13880151-335e-48cd-8f56-40a4d8cb3e61)
Edit: Chrome Console Error.
<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by seronet** [comment]
Ahh, I think the problem is caused by the firewall :)

I didn't see the problems when I used a different connection.

Thx.
