### ISSUE TITLE
Cannot receive email notification after Checkin and Checkout Assets 

### ISSUE THREAD

**Issue by amenavadei** [grokability/snipe-it#13614]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I check both the Boxes in the category Section, In the General settings my email domain is: "gmail.com"..
I went to the Assets table grid, did a  check-out and check-in, and then checked my email, I didn't receive any notification either 

Please need help on this since this is the only issue I got and its a  priority issues

<img width="380" alt="image" src="https://github.com/snipe/snipe-it/assets/12438524/0447a920-e516-43b1-8be6-869e3fdb4a79">

I am using PHP - v8.0.25
composer: 2.5.8
snipe-it : 6.1.0

### Reproduction steps

1.
2.
3.
...

### Expected behavior

When I hit the check-out and check-in button, I should expect to receive an email 

### Snipe-IT Version

6.1.0

### Operating System

windows 

### Web Server

Apache

### PHP Version

8.0.25

### Operating System

windows

### Browser

chrome

### Version

117.0.59

**Comment by snipe** [comment]
Can you receive other emails from the system? Did you check your SPAM folder? Is there anything in your app logs?

Our email works as expected, so it would have to be something in your configuration.

**Comment by amenavadei** [comment]
Hi
Thanks for replying  to my message

I didn't receive email from snipe-it , checked on spam folder didn't
received it

I have updated the received email in .env file

I don't know where else to check, which folder to check the app logs? And
where else to configure ?

Looking forward to hearing from you

Thanks
Amena

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by amenavadei** [comment]
Hi

I have set the App debug to true
please can you check on what I did on outgoing mail server settings on my .envi file if its correct 

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=amenavadei@gmail.com
MAIL_PASSWORD=test
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=amenavadei@gmail.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=you@example.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'

**Comment by amenavadei** [comment]
I checked on the storage/logs/laravel
Do i have to put my gmail password or the password I used to login on snipe-it?
after test the check-in and check-out I got this error ..Please help

`[2023-09-17 08:15:10] production.ERROR: Exception caught during checkin notification: Failed to authenticate on SMTP server with username "amenavadei@gmail.com" using 3 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials b11-20020a170902a9cb00b001bafd5cf769sm6243962plr.2 - gsmtp
". Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials b11-20020a170902a9cb00b001bafd5cf769sm6243962plr.2 - gsmtp
". Authenticator XOAUTH2 returned Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials b11-20020a170902a9cb00b001bafd5cf769sm6243962plr.2 - gsmtp`

**Comment by maxdesu** [comment]
> I checked on the storage/logs/laravel Do i have to put my gmail password or the password I used to login on snipe-it? after test the check-in and check-out I got this error ..Please help
> 
> `[2023-09-17 08:15:10] production.ERROR: Exception caught during checkin notification: Failed to authenticate on SMTP server with username "amenavadei@gmail.com" using 3 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials b11-20020a170902a9cb00b001bafd5cf769sm6243962plr.2 - gsmtp ". Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials b11-20020a170902a9cb00b001bafd5cf769sm6243962plr.2 - gsmtp ". Authenticator XOAUTH2 returned Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials b11-20020a170902a9cb00b001bafd5cf769sm6243962plr.2 - gsmtp`

Are you using 2-Step verification? 

If yes, trying create App passwords from Google security portal and try again. 

Go to Google Account -> Security -> 2-Step Verification -> App passwords -> put Name whatever you want and copy password that generated fill at MAIL_PASSWORD=" on .env file. Please fill that part **without** space.

After that clear php cache and send email test again on snipe-IT's settings.
