### ISSUE TITLE
Favicon not following Brand Icon Fav at Login Page

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13628]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Snipe-IT login Page, shows the Snipe-IT logo, Once logged in it then goes to the Favicon which is in the branding settings.

### Reproduction steps

1.Login Page for snipe-it (wrong favicon)
2. Once logged in, Correct favicon from branding is correct)
3.
...

### Expected behavior

Favicon Branding should follow also in login page.

### Snipe-IT Version

 v6.2.0-pre build 11531 (g20da6cccb) 

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.1.22

**Comment by snipe** [comment]
The code on both templates is the same:

### Login

``` 
<link rel="shortcut icon" type="image/ico" href="{{ ($snipeSettings) && ($snipeSettings->favicon!='') ?  Storage::disk('public')->url('').e($snipeSettings->favicon) : 'favicon.ico' }} ">
```

### Default

```
 <link rel="shortcut icon" type="image/ico" href="{{ ($snipeSettings) && ($snipeSettings->favicon!='') ?  Storage::disk('public')->url(e($snipeSettings->favicon)) : config('app.url').'/favicon.ico' }} ">
```

Can you look at the generated HTML code on both logged in and non-logged in and tell me if you see a difference?

Browsers do cache favicons sort of randomly and unpredictably.

**Comment by jayavman** [comment]
Login page :
<img width="308" alt="Screenshot 2023-09-19 at 5 35 21 pm" src="https://github.com/snipe/snipe-it/assets/114973646/3dabd23d-5aba-45c5-b255-11c9e2f9548d">

after login page, Main page
<img width="301" alt="Screenshot 2023-09-19 at 5 34 48 pm" src="https://github.com/snipe/snipe-it/assets/114973646/e412d3d6-0a06-4fe0-b7ff-1dfa2379a25f">

**Comment by snipe** [comment]
No idea why you'd be seeing different results there. I can't think of anything special we're doing there.
