### ISSUE TITLE
QR code is not showing

### ISSUE THREAD

**Issue by AlphonesDamonlette** [grokability/snipe-it#13620]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

QR code is not showing 

<img src="http:3.108.164.157//hardware/77/qr_code" class="qr_img">

### Reproduction steps

1.<img src="http:3.108.164.157//hardware/77/qr_code" class="qr_img">
2.
3.
...

### Expected behavior

<img src="http:3.108.164.157//hardware/77/qr_code" class="qr_img">

### Screenshots

<img src="http:3.108.164.157//hardware/77/qr_code" class="qr_img">

### Snipe-IT Version

v6.0.1 - build 7750 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

5.2.1 

### Error messages

```shell
<img src="http:3.108.164.157//hardware/77/qr_code" class="qr_img">
```

**Comment by snipe** [comment]
The APP_URL is misconfigured. You're missing the `//` in the `http://` and it looks like you have a trailing slash. 

It should be:

`APP_URL='http://3.108.164.157'`

[Per the documentation](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings), the APP_URL should be the complete URL to your Snipe-IT installation, *including* the `http://` (or `https://` if you're running over TLS.)

<img width="795" alt="Screen Shot 2022-07-28 at 11 35 47 PM" src="https://user-images.githubusercontent.com/197404/181698021-de470225-4865-4786-bd48-9a9cdf2399d2.png">

**Comment by AlphonesDamonlette** [comment]
@snipe Cool! Thanks Works Fine now

**Comment by snipe** [comment]
Glad you're sorted :)
