### ISSUE TITLE
While configuring outgoing mail setting application goes black no responce 

### ISSUE THREAD

**Issue by AlphonesDamonlette** [grokability/snipe-it#13636]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=it@doamin.com
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=TSL
MAIL_FROM_ADDR=it@domain.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=it@domain.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'

I have configured this setting after the configuration the application is blank(Nothing)

### Reproduction steps

1.MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=it@doamin.com
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=TSL
MAIL_FROM_ADDR=it@domain.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=it@domain.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'
2.
3.
...

### Expected behavior

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=it@doamin.com
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=TSL
MAIL_FROM_ADDR=it@domain.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=it@domain.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'

### Snipe-IT Version

v6.0.1 - build 7750 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

5.2.1

**Comment by snipe** [comment]
`MAIL_ENCRYPTION=TSL`

TSL isn't a thing. I think you want:

`MAIL_ENCRYPTION=tls`

**Comment by AlphonesDamonlette** [comment]
After making changes to the env file, the application goes blank. Reverting the changes fixes the issue.

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=it@doamin.com
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=it@domain.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=it@domain.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'

**Comment by snipe** [comment]
Sounds like you're sorted then. I'll close this issue for now.

**Comment by AlphonesDamonlette** [comment]
Sorry, I still cannot configure outgoing email. The application crashes once I config the outgoing email settings.

**Comment by snipe** [comment]
Without app log information as to what's causing it to crash, we won't be able to help.

**Comment by AlphonesDamonlette** [comment]
Cool. the issue is sorted
