### ISSUE TITLE
artisan requires key to generate a key catch-22

### ISSUE THREAD

**Issue by vladimir-krstulja-ipf** [grokability/snipe-it#13630]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

It appears that the `php artisan key:generate` step of the installation process already requires a valid key in `APP_KEY` var of the `.env` file, otherwise it throws errors. This, or the documentation is lacking an additional step that needs to be performed prior to generating the key this way.

### Reproduction steps

With `APP_KEY=null`, the error given is:
```
  Illuminate\Encryption\MissingAppKeyException 

  No application encryption key has been specified.

  at vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:101
     97▕     protected function key(array $config)
     98▕     {
     99▕         return tap($config['key'], function ($key) {
    100▕             if (empty($key)) {
  ➜ 101▕                 throw new MissingAppKeyException;
    102▕             }
    103▕         });
    104▕     }
    105▕ }

  • Your app key is missing:  
    https://laravel.com/docs/master/installation#configuration

      +32 vendor frames 
  33  resources/macros/macros.php:25
      Illuminate\Support\Facades\Facade::__callStatic()

  34  app/Providers/MacroServiceProvider.php:18
      require_once("/opt/ipf-snipe-it/resources/macros/macros.php")
```

With `APP_KEY=ChangeMe`, the error is:
```
 RuntimeException 

  Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm.

  at vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:55
     51▕ 
     52▕         if (! static::supported($key, $cipher)) {
     53▕             $ciphers = implode(', ', array_keys(self::$supportedCiphers));
     54▕ 
  ➜  55▕             throw new RuntimeException("Unsupported cipher or incorrect key length. Supported ciphers are: {$ciphers}.");
     56▕         }
     57▕ 
     58▕         $this->key = $key;
     59▕         $this->cipher = $cipher;

      +29 vendor frames 
  30  resources/macros/macros.php:25
      Illuminate\Support\Facades\Facade::__callStatic()

  31  app/Providers/MacroServiceProvider.php:18
      require_once("/opt/ipf-snipe-it/resources/macros/macros.php")
```

With `APP_KEY` set to a value like the output of `base64:$(head -c 32 /dev/urandom | base64)`, it complains the app is already in production and asks for confirmation to continue, but actually does the job after this confirmation.

### Expected behavior

`php artisan key:generate` should generate a valid `APP_KEY` regardless of its current contents.

### Snipe-IT Version

6.1.2

### Operating System

Debian 11 (Bullseye)

### Web Server

nginx

### PHP Version

7.4

**Comment by snipe** [comment]
We've seen that a few times, and we're never really sure why it only happens *sometimes*. You can use any example key, `base64:hTUIUh9CP6dQx+6EjSlfWTgbaMaaRvlpEwk45vp+xmk=` for example, in your .env to get you started, then run `php artisan key:generate` to generate a new, unique, secret one for your actual application.
