### ISSUE TITLE
Updating custom fields results in no change or error

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [grokability/snipe-it#13637]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to PATCH custom fields on an asset an error is thrown.

It should be noted that if I change the custom field options in my request, the API call will work. The custom fields won't be updated (because the names are wrong) but the API call will be successful. 

### Reproduction steps

1. Create a custom field. In my case, a MAC address field
2. Assign the custom field to a field set
3. Assign the field set to assets
4. Attempt to patch a value to the custom field of an asset by using the DB field name in the request
5. Get an error
...

### Expected behavior

The custom field to be updated

### Screenshots

Powershell snipit of the body being made:
![image](https://github.com/snipe/snipe-it/assets/53045430/f15c14d3-fc72-498a-8489-a6b6d12ecf02)

The output of said snipit:
![image](https://github.com/snipe/snipe-it/assets/53045430/4ef1caa3-30ae-42a1-b1fe-6d6db722d4c6)

The DB values for the custom fields:
![image](https://github.com/snipe/snipe-it/assets/53045430/52d27daf-2f5f-4aea-a4e7-06153e7a850e)

### Snipe-IT Version

v6.2.0-pre - build 11531 (master)

### Operating System

Ubuntu

### Web Server

Whatever the installer uses

### PHP Version

8

### Operating System

Windows

**Comment by snipe** [comment]
I'm not able to reproduce this via cURL, so my guess would be that it's something funny with your code. 


### cURL:

```curl
curl --location --request PATCH 'https://snipe-it.local:8890/api/v1/hardware/1' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <MY-BEARER-TOKEN>' \
--header 'Cookie: snipeit_v6-dev_local=y283SdCiqSGcnt777bpReWs32DP0XEQhkqtU2pHO' \
--data-urlencode 'supplier_id=2' \
--data-urlencode '_snipeit_ram_3=test'
```

### Powershell:

```Powershell
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Content-Type", "application/x-www-form-urlencoded")
$headers.Add("Accept", "application/json")
$headers.Add("Authorization", "Bearer <MY-BEARER-TOKEN>")
$headers.Add("Cookie", "snipeit_v6-dev_local=y283SdCiqSGcnt777bpReWs32DP0XEQhkqtU2pHO")

$body = "supplier_id=2&_snipeit_ram_3=test"

$response = Invoke-RestMethod 'https://snipe-it.local:8890/api/v1/hardware/1' -Method 'PATCH' -Headers $headers -Body $body
$response | ConvertTo-Json
```

**Comment by Mailstorm-ctrl** [comment]
That's weird. If I copy what you have and substitute my values...I still can't do anything. Copying your PowerShell results in an invalid json body error:

```
$headers = @{}
$headers.Add("Content-Type", "application/x-www-form-urlencoded")
$headers.Add("accept", "application/json")
$headers.Add("Authorization", "Bearer $($api_token)")

$api_body = "_snipeit_ethernet_mac_address_1=00-00-00-00-00-00&_snipeit_wlan_mac_address_4=00-00-00-00-00-00"
Invoke-RestMethod -Uri "$($snipeit_baseurl)$($api_baseurl)$($hardware_api_url)/$($asset_object.id)" -Method PATCH -Headers $headers -ContentType 'application/json' -Body $api_body

>>> Invoke-RestMethod : {"status":"error","messages":"Invalid JSON","payload":null}
```

Then Curl:

```
curl --location --request PATCH 'http://FQDN/api/v1/hardware/byserial/<serialnum>' --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'Authorization: Bearer <TOKEN>' --data-urlencode 'status_id=2' --data-urlencode '_snipeit_ethernet_mac_address_1=00-00-00-00-00-00' --data-urlencode '_snipeit_wlan_mac_address_4=00-00-00-00-00-00'

>>> {"status":"error","messages":"Method not allowed","payload":null}
```

**Comment by Mailstorm-ctrl** [comment]
So the issue wasn't with my codejust how snipe it validates MAC addresses. 00-00-00-00-00-00 is not valid. Neither is 0000000000000. So I just had to do an inline string replacement to make sure my mac matches what snipe it is expecting.

It would be nice if multiple MAC formats were accepted though.

**Comment by snipe** [comment]
MAC address is just a regex. Change the regex to meet your needs (through the UI, not the code) and you should be golden
