### ISSUE TITLE
[Feature Request]: Changing URLs

### ISSUE THREAD

**Issue by riobijoy** [grokability/snipe-it#13633]
### Is your feature request related to a problem? Please describe.

Using the latest version of Snipeit,Now i want to change the browser access url,Say right now when i type in browser http://ABC it opens just i want to change it to http://xyz,How to do that

### Describe the solution you'd like

change the url

### Describe alternatives you've considered

NO

### Additional context

Using the latest version of Snipeit,Now i want to change the browser access url,Say right now when i type in browser http://ABC it opens just i want to change it to http://xyz,How to do that

**Comment by snipe** [comment]
Literally just change it in your .env - it's well documented. https://snipe-it.readme.io/docs/configuration#required-basic-app-settings

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#required-basic-app-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.Don't be intimidated by the length of this page. The configuratio...</div></blockquote>

**Comment by riobijoy** [comment]
> Literally just change it in your .env - it's well documented. https://snipe-it.readme.io/docs/configuration#required-basic-app-settings
> 
> <blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#required-basic-app-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.Don't be intimidated by the length of this page. The configuratio...</div></blockquote>

I have changed it in .env file,but after that when i put a new url in browser,page not work correctly.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#required-basic-app-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.Don't be intimidated by the length of this page. The configuratio...</div></blockquote>
