### ISSUE TITLE
Pre-flight check confuses ownership with running-as

### ISSUE THREAD

**Issue by vladimir-krstulja-ipf** [grokability/snipe-it#13631]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

During the pre-flight check, it checks file ownership, but that's an inadequate test. Files can be owned by `root` with PHP running as an unprivileged user (having proper permissions to access files in the manner they should be accessed (read-only application code and config, read-write upload/cache dirs, ...), which is a valid environment within principle of least privilege. File ownership should not be checked, but instead UID of the PHP process, for example.

### Reproduction steps

1. Install the application files as root
2. Complete the installation steps (install, dependencies, configuration, web-server context, ...)
3. Set up the PHP pool to run as unprivileged user (eg. `www-data` on Debian)
4. Continue with pre-flight check at your designated Snipe-IT URL

### Expected behavior

Should not complain that root _owns_ the files. 

### Snipe-IT Version

6.1.2

### Operating System

Debian 11

### Web Server

nginx

### PHP Version

7.4

**Comment by snipe** [comment]
Files owned by root can cause issues with future upgrades, which is why we check for that. You're welcome to continue the installation as your setup is arranged, but it's not what we recommend, which is why we warn against it.
