### ISSUE TITLE
Delete assets (Bulk Delation

### ISSUE THREAD

**Issue by riobijoy** [grokability/snipe-it#13645]
### Is your feature request related to a problem? Please describe.

How to bulk delete all assets as i have wrongly uploaded it

### Describe the solution you'd like

Bul delation

**Comment by snipe** [comment]
You can use the bulk delete option in the assets listing menu

<img width="1699" alt="Screenshot 2023-09-25 at 11 30 57 AM" src="https://github.com/snipe/snipe-it/assets/197404/bfcc6d62-04fb-424f-9919-8efbbec5320b">
