### ISSUE TITLE
Unaccepted Assets shows assets checkout out to Locations as Users

### ISSUE THREAD

**Issue by tomfortmuller** [grokability/snipe-it#13643]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When viewing the Unaccepted Assets report, when an asset is checked out to a location and the location id matches the user id, the user is displayed instead of the location.

### Reproduction steps

1. Identify or create a user with a particular ID.
2. Identify or create a location with the same ID.
3. Check out an asset to the location.
4. View the unaccepted assets report.

### Expected behavior

Since the asset is checked out to a location, it should not appear in the unaccepted asset report.

#### Unaccepted Assets Report
![image](https://github.com/snipe/snipe-it/assets/10818823/28bf2620-325f-4845-b2c1-bb2e1a745c90)

#### Asset View page
![image](https://github.com/snipe/snipe-it/assets/10818823/e38ab9d6-ed70-49df-ad71-89757c9d3710)

#### Database Records
![image](https://github.com/snipe/snipe-it/assets/10818823/1e50244a-781f-4ccf-a5f5-f0cf74877b48)

### Snipe-IT Version

6.1.2

### Operating System

Ubuntu

### Web Server

Nginx

### PHP Version

8.1

**Comment by tomfortmuller** [comment]
`checkout_acceptances` needs a polymorphic relationship for assigned_to.

**Comment by snipe** [comment]
AFAIK, this was already fixed. Upgrade to master.
