### ISSUE TITLE
Dashboard un-clickable when header overflows

### ISSUE THREAD

**Issue by jarrydstan** [grokability/snipe-it#13641]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When the window is small enough that the header stacks on top, the dashboard is unable to be clicked

### Reproduction steps

1. login to snipe
2. open another page other than dashboard
3. resize window to the point that the logo/name of the website stacks on top of the top navigation
4. Unable to click on dashboard link
...

### Expected behavior

When the window resizes, you should still be able to navigate to the dashboard

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/65701829/607a42ed-f009-421f-9b3b-621a9b561243)

### Snipe-IT Version

latest v6.2.0-pre build 11531

### Operating System

Debian 11

### Web Server

Apache2

### PHP Version

7.4.33

### Operating System

Windows 10

### Browser

Chrome

### Version

116.0.5845.188

### Error messages

```shell
Confirmed same issue happening on demo
```

**Comment by snipe** [comment]
Clicking on the logo will bring you back to the dashboard

**Comment by snipe** [comment]
@Godmartinz I re-opened the SC on this: https://app.shortcut.com/grokability/story/9955/cannot-click-on-dashboard-icon-anymore

<blockquote><div><strong><a href="https://app.shortcut.com/grokability/story/9955/cannot-click-on-dashboard-icon-anymore">Shortcut</a></strong></div></blockquote>
