### ISSUE TITLE
After new install and restore data from backup getting error 500 when trying to create new category

### ISSUE THREAD

**Issue by syunnectari** [grokability/snipe-it#13651]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

New installation of newer version and restore data from old version.
Looks ok, only when try to create new category get this 500 error

Exception
The /var/www/html/snipe/bootstrap/cache directory must be present and writable. (View: /var/www/html/snipe/resources/views/categories/edit.blade.php)

### Reproduction steps

1. Go to Categories
2. Click on Create New
3.
...

### Expected behavior

Expect create new category page

### Snipe-IT Version

v6.2.0-pre - build 11531 (master)

### Operating System

Cent OS 9 Stream

### Web Server

Apache

### PHP Version

8.1.14

### Error messages

```shell
Exception
The /var/www/html/snipe/bootstrap/cache directory must be present and writable. (View: /var/www/html/snipe/resources/views/categories/edit.blade.php)

Livewire\LivewireComponentsFinder::write
vendor/livewire/livewire/src/LivewireComponentsFinder.php:59































    public function build()

    {

        $this->manifest = $this->getClassNames()

            ->mapWithKeys(function ($class) {

                return [$class::getName() => $class];

            })->toArray();

 

        $this->write($this->manifest);

 

        return $this;

    }

 

    protected function write(array $manifest)

    {

        if (! is_writable(dirname($this->manifestPath))) {

            throw new Exception('The '.dirname($this->manifestPath).' directory must be present and writable.');

        }

 

        $this->files->put($this->manifestPath, '<?php return '.var_export($manifest, true).';', true);

    }

 

    public function getClassNames()

    {

        if (! $this->files->exists($this->path)) {

            return collect();

        }

 

        return collect($this->files->allFiles($this->path))

            ->map(function (SplFileInfo $file) {

                return app()->getNamespace().

                    str($file->getPathname())
```

**Comment by snipe** [comment]
> The /var/www/html/snipe/bootstrap/cache directory must be present and writable

Permissions issue. The error is telling you what's wrong.

**Comment by syunnectari** [comment]
cache folder has apache:apache owner and 775 permissions

**Comment by snipe** [comment]
Are the dirs above it writable? What is the sticky bit on those parent dirs? Are you running SE Linux?

It's absolutely still a permissions problem.

**Comment by syunnectari** [comment]
Disabling SELinux helped. Thank you
