### ISSUE TITLE
All custom fields values show "encrypted" in history when they are not

### ISSUE THREAD

**Issue by squintfox** [grokability/snipe-it#13658]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgrading from 6.1.2 to 6.2.0, all existing history entries that show custom fields do not show the actual values anymore, they just say the word "encrypted" for both pre and post values.  Any new changes to a custom field, do the same.  The custom fields were not created as encrypted and the values display correctly in the info page and list views.  This happens in the demo, so I used that to reproduce.

### Reproduction steps

1. Go to Asset# 1376559076 in demo.snipeitapp.com.
2. Edit Asset
3. Change the value of "CPU"
4. Save
5. Go to History
6. See log entry and values of _snipeit_cpu_4 are shown as encrypted.

### Expected behavior

Original and new values should be shown in cleartext

### Screenshots

![Screenshot 2023-09-26 152429](https://github.com/snipe/snipe-it/assets/55590532/49233174-7922-4edd-973b-7d82d942de37)

![Screenshot 2023-09-26 152501](https://github.com/snipe/snipe-it/assets/55590532/e3802425-24b1-4f4c-85e1-cc2eedf786e4)

### Snipe-IT Version

6.2.0

### Operating System

Unknown

### Web Server

Unknown

### PHP Version

8.1.21

**Comment by TonyTheDarkLord** [comment]
Same here! 😕

![image](https://github.com/snipe/snipe-it/assets/7749082/9e933a24-9d3a-4c19-afeb-ad7ba7086c6a)

**Comment by snipe** [comment]
Thanks for reporting this - I'm looking at it now. Good news is that the data itself is intact - we're just displaying it incorrectly. I should have a fix out for you shortly.

**Comment by snipe** [comment]
Okay, I think I've got this sorted. PR incoming.

<img width="281" alt="Screenshot 2023-09-28 at 2 32 14 AM" src="https://github.com/snipe/snipe-it/assets/197404/e0de59f3-0fe7-402e-9f9b-e1b349f4b17d">

**Comment by squintfox** [comment]
@snipe I pulled the new version and it's working great.  Thank you so much.

**Comment by snipe** [comment]
@squintfox no problem - sorry for the glitch!

**Comment by TonyTheDarkLord** [comment]
Thanks a lot!
