### ISSUE TITLE
[Feature Request]: [Actions] column to be first one

### ISSUE THREAD

**Issue by marcinBB8** [grokability/snipe-it#13654]
### Is your feature request related to a problem? Please describe.

Veru long time taking editing many positions in table.

### Describe the solution you'd like

Please make [Actions] column first one on all list views.

### Describe alternatives you've considered

Eventualy make an option to chose colums order

**Comment by jayavman** [comment]
have you tried the latest update? You can now arrange the columns by dragging them.

May want to update to  #13613
v6.2.0-pre build 11531 (g20da6cccb)

**Comment by snipe** [comment]
That's not currently on the short term roadmap. You can always hide columns to make the UI more compact.
