### ISSUE TITLE
Requestable items

### ISSUE THREAD

**Issue by soren33322** [grokability/snipe-it#13660]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I make a requestable item, it should only be allowed to request that item when it's free.
Right now, if the item is deployed to a user, other people can still request.

Another thing is, when I checkin a item the user still see the cancel button.

### Reproduction steps

1. First request an item as a user
2. As an admin go to requested tab under assets
3. checkout the item
4. Go to the user
5. Checkin the item again
...

### Expected behavior

1. problem: When the user is requesting a item, the item should not be able to be requested from other people before the request either is canceled by the admin or the item has been checked in again.

2. problem: When the item is checked in again, the cancel button from the user should be a Request button again, and not a cancel button as shown in the picture.
![request1](https://github.com/snipe/snipe-it/assets/42936505/ccd0b4f6-8ee1-4f46-9b8e-a8978eb01f38)

### Snipe-IT Version

v6.2.0-pre - build 11391

### Operating System

ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1

### Operating System

ubuntu 22.04

### Browser

Chrome, Firefox

### Version

117.0.5938.88, 118.0

**Comment by snipe** [comment]
> When I make a requestable item, it should only be allowed to request that item when it's free. Right now, if the item is deployed to a user, other people can still request.

That's intended behavior. If I need a test machine, even if it's already checked out, I want that request logged so that when it frees up, I can be assigned that item next.

**Comment by soren33322** [comment]
Hi,

Alright. But when I check in the item again, it does not reset the cancel button from the users perspective.
