### ISSUE TITLE
Snipe Installer fails on Debian 12

### ISSUE THREAD

**Issue by alfrede** [grokability/snipe-it#13669]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When i want to install Snipe IT on a fresh Debian 12 Server it won´t install.
The following text will be displayed: 
The installer has detected Debian version 12 codename bookworm.
Unsupported Debian version. Version found: 12

### Reproduction steps

1. Install a new Debian 12
2. Git clone snipe-it
3. wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
4. chmod 744 install.sh
5. ./install.sh

### Expected behavior

The Installation will be executed.

### Screenshots

![snipe-debian12](https://github.com/snipe/snipe-it/assets/1897882/c423b023-08b9-4111-b2c4-84726bc0cac5)

### Snipe-IT Version

6.2 (git)

### Operating System

Debian 12

### Web Server

Apache

### PHP Version

8.2

### Error messages

```shell
The installer has detected Debian version 12 codename bookworm.
Unsupported Debian version. Version found: 12
```

**Comment by snipe** [comment]
Snipr-IT is knotty compatible with PHP 8.2 yet

**Comment by alfrede** [comment]
@snipe thanks for your information, i will try to install php8.1 and will give a feedback.

**Comment by alfrede** [comment]
Okay it takes a little bit longer but now i have a fresh Snipe 6.2. I removed php8.2 and looked for those php8.1 modules: 

libapache2-mod-php php php-common php-xml php-gd php8.1-opcache php-mbstring php-tokenizer php-json php-bcmath php-zip php-bz2 php-pdo php-calendar php-ctype php-exif php-ffi php-fileinfo php-ftp php-mysqli php-phar php-posix php-readline php-shmob php-sockets php-sysvmsg php-sysvmsg php-sysvsem php-ldap

Thanks for your help.
