### ISSUE TITLE
[Feature Request]: Change Statut Meta data 

### ISSUE THREAD

**Issue by hakihosting** [grokability/snipe-it#13666]
### Is your feature request related to a problem? Please describe.

I find that the meta data status is misinterpreted.
When you have an asset, it is in stock => green ball 
When you assign the asset to a user, the status remains in stock and next to it is marked deployed => this is confusing I think the status should go and leave the meta data. 

### Describe the solution you'd like

I find that the meta data status is misinterpreted.
When you have an asset, it is in stock => green ball 
When you assign the asset to a user, the status remains in stock and next to it is marked deployed => this is confusing I think the status should go and leave the meta data.

**Comment by snipe** [comment]
This has been discussed at length. Not on the short term roadmap, I'm afraid.
