### ISSUE TITLE
[Feature Request]: Automatically add colon on MAC Address custom field.

### ISSUE THREAD

**Issue by soren33322** [grokability/snipe-it#13661]
### Is your feature request related to a problem? Please describe.

Automatically add colon on MAC address (Custom Fields)
![mac](https://github.com/snipe/snipe-it/assets/42936505/89f3f814-6d5a-4de9-810a-7503788f2527)

### Describe the solution you'd like

This makes it easy when you are scanning or just typing in the MAC address of a device.

This feature makes typing or scanning the mac address easier, because it automatically insert the colon even if you scan or typing.
If you accidentally typing a colon it just delete itself, so no worries there.

The code in the screenshot has inserted in the **custom_fields_form.blade.php** under resources -> views -> models

**Comment by snipe** [comment]
This isn't really a feature request or a bug. If you'd like to open a PR for this, please feel free.
