### ISSUE TITLE
Pound symbol in MySQL password causes SQLSTATE[HY000] [1045]

### ISSUE THREAD

**Issue by toddjacobs** [grokability/snipe-it#13676]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If the db password used contains the "#" symbol, a SQLSTATE[HY000] [1045] is encountered.

### Reproduction steps

1. Include a "#" in the MySQL user's password
2.
3.
...

### Expected behavior

Expect to be able to use a full range of characters in a password.

### Snipe-IT Version

6.2.0

### Operating System

Ubuntu 22.04.3

### Web Server

NGINX

### PHP Version

8.1.3

**Comment by snipe** [comment]
Are you enclosing the password in single quotes on your .env?

https://snipe-it.readme.io/docs/installation-issues#fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist

https://snipe-it.readme.io/docs/configuration#your-environmental-config-file

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
