### ISSUE TITLE
Error 500 - Server Error

### ISSUE THREAD

**Issue by luismigliaris1** [grokability/snipe-it#13675]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When selecting the import type in SnipeIT, a screen with error 500 - Server Error is displayed. Below is the result from Debug Mode:

https://flareapp.io/share/q5Yzo9om

### Reproduction steps

1. Attempt to elevate permissions using the command `chmod -R 755 /var/www/snipe-it/bootstrap/cache`;
2. Restart Apache Server;
3. Reboot Ubuntu Server;
4. Change .env file;
...

### Expected behavior

I hope to manage the importing tool.

### Snipe-IT Version

v6.2.0-pre build 11391 (g319cb2305)

### Operating System

Ubuntu SERVER

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.14

**Comment by snipe** [comment]
Are you running SELinux? What happens if you (temporarily) elevate the storage dir and all subdirectories to 777?

```
chmod -R 777 /var/www/snipe-it/storage
chmod -R 777 /var/www/snipe-it/bootstrap
```

**Comment by luismigliaris1** [comment]
I was running SELinux, then i disabled and gave the permissions you mencioned. No effects.

**Comment by luismigliaris1** [comment]
Sorry, i also eleveted the folders you mencioned to 777.

**Comment by whdan600** [comment]
@luismigliaris1 I had the same error a couple of minutes ago, the rows i had in the csv file didnt have as many fields as the csv header, i guess there is no exception handling for this kind of issue thats why it throws an error 500

**Comment by luismigliaris1** [comment]
@whdan600 thank you so much! still cant believe that was the error... i'm glad it worked.
