### ISSUE TITLE
SnipeIT Importing

### ISSUE THREAD

**Issue by luismigliaris1** [grokability/snipe-it#13673]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm trying to import Users and Assets into Snipe-IT. Every time I attempt to import, an error regarding nonexistent fields is displayed for all types of import (Users, Assets, etc). The .csv file template was taken from the official website documentation.

Here is an exemple: 

![error](https://github.com/snipe/snipe-it/assets/70668985/557f7037-8027-45b9-add8-5c219b9224a9)

I'm also sending the template i'm using for users. 
[sample-users (1).csv](https://github.com/snipe/snipe-it/files/12750415/sample-users.1.csv)

### Reproduction steps

1. I tried to perform the importation in different browsers;
2. I attempted to use different templates;
3. I tried to create the templates manually;
4. APACHE restarted;
5. Ubuntu Server restarted;

### Expected behavior

I hope to be able to carry out the importation.

### Screenshots

![error](https://github.com/snipe/snipe-it/assets/70668985/4b3feb21-3073-4903-a104-6ecdb6cb2396)

### Snipe-IT Version

v6.2.0-pre build 11391 (g319cb2305)

### Operating System

Ubuntu SERVER

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.14

### Operating System

Windows 11

### Browser

Brave/Chrome

**Comment by snipe** [comment]
Did you map the first name and last name in the drop-downs?

**Comment by luismigliaris1** [comment]
It worked, thanks.
