### ISSUE TITLE
Generate Backup Error 500 Server Error

### ISSUE THREAD

**Issue by agongpor** [grokability/snipe-it#13686]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I click Generate Backup it goes to new page 500 SERVER ERROR 

### Reproduction steps

1. Click Generate Backup
2.
3.
...

### Expected behavior

Backup created

### Screenshots

TypeError
Spatie\DbDumper\DbDumper::setPort(): Argument #1 ($port) must be of type int, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 56

![image](https://github.com/snipe/snipe-it/assets/31266351/86c05630-1b88-44e5-8516-4995c3137790)

### Snipe-IT Version

v6.2.0 build 11566 (g5a5b07f5a)

### Operating System

Windows 10

### Web Server

Docker

### PHP Version

8.1.2-1ubuntu2.14

### Operating System

Windows 10

### Browser

Chrome

### Version

Version 117.0.5938.92 (Official Build) (64-bit)

### Error messages

```shell
TypeError
Spatie\DbDumper\DbDumper::setPort(): Argument #1 ($port) must be of type int, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 56
```

**Comment by snipe** [comment]
IIRC this was already fixed in https://github.com/snipe/snipe-it/pull/13538. Please upgrade.

**Comment by agongpor** [comment]
Thank you so much @snipe
