### ISSUE TITLE
Snipe-IT App cannot handle /ht/{asset_tag} 2D barcodes, only /hardware/{id} barcodes

### ISSUE THREAD

**Issue by TeknikalDomain** [grokability/snipe-it#13698]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When scanning in data matrix 2D barcodes via the mobile app, setting the 2D barcode target setting to `/ht/{asset_tag}` means that the generated barcodes cannot be scanned by the mobile app, as it will complain "Asset not found" when attempting to search via that URL.

### Reproduction steps

1. Create an asset (ex. tag, `TDA00005`)
2. Set barcode and label settings to new label engine, using a template that supports 2D barcodes, and set 2D barcode target to `/ht/{asset_tag}`
3. Generate label for an asset, and attempt to check in or check out by scanning that barcode in-app. It will fill in the entire URL (ex. `http://example.com/ht/TDA00005`).
5. Press search, and receive an "Asset not found" error.

--- 

It seems that this is specific to the new label engine, as the old one doesn't have any option to specify the barcode target.

If you want to reproduce my exact environment, I'm using the Avery 5520A template, title "TekDmn," Use Asset Logo unchecked, 1D type is C128, 2D type is DATAMATRIX, target is `/ht/{asset_tag}`.

### Expected behavior

The app should be able to scan 2D barcodes whether or not they use the `/hardware/{id}` or `/ht/{asset_tag}` scheme.

### Snipe-IT Version

v6.2.0 build 11566 (g5a5b07f5a)

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

v6.2.0 build 11566 (g5a5b07f5a)

### Device

Samsung Galaxy S22 Ultra

### Operating System

Android 13

### Browser

Snipe-IT Assets Management application

### Version

0.7.5-SnipeIT

**Comment by snipe** [comment]
> via the mobile app

We don't have a mobile app so I cannot speak to what it does or does not do.
