### ISSUE TITLE
List of users not generating when checking out asset

### ISSUE THREAD

**Issue by krosseyed** [grokability/snipe-it#13692]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I cannot seem to figure out why my users are not being listed when checking out an asset. It looks like there is just a 'spinning circle' when entering names and it does not give me a selection to choose from.

### Reproduction steps

When checking out hardware, select 'User' and type in a known/uploaded user. It does not list users when typing in letter by letter.

### Expected behavior

I should have a list of users when typing in a name, and whittles down to who I am selecting. It does not show anything.

### Screenshots

<img width="680" alt="Screenshot 2023-10-02 at 1 40 28 PM" src="https://github.com/snipe/snipe-it/assets/6548354/a39dfd8f-c8a2-48fc-98be-2fc79d65496e">

### Snipe-IT Version

6.2.1

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1

### Operating System

Windows

### Browser

Chrome

### Version

117

### Error messages

```shell
[2023-09-30 15:54:35] production.ERROR: Error: Class "Laravel\Socialite\SocialiteServiceProvider" not found in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest()
#2 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(659): Illuminate\\Foundation\\ProviderRepository->load()
#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /var/www/snipe-it/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"}
```

### Additional context

I ran into this after updating from 6.0.14 -> 6.2.0 -> 6.2.1. Not sure where in the process it broke, but it was working on 6.0.14 and I had to hard reset git to update past it.

**Comment by inietov** [comment]
You are seeing an error with some vendor packages. What happens when you run `composer install` on the root of the project?

**Comment by krosseyed** [comment]
It does not do much unfortunately, still the same issue.

Here is the output of running composer install:

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package fruitcake/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: maatwebsite/excel
Discovered Package: mediconesystems/livewire-datatables
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: nunomaduro/phpinsights
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
136 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

```

**Comment by snipe** [comment]
Anything in your browser console? This is usually an APP_URL config issue or a permissions issue.

**Comment by krosseyed** [comment]
Its a pleasure to work with you on this @snipe! I appreciate your time and the project!

Opening up the console, I can see the following every time I click on the user field

`all.js?id=8b6d5790410cef7c138c7807516eb0b0:1 Mixed Content: The page at 'https://<MYDOMAIN>/hardware/122/checkout' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://<MYDOMAIN>/api/v1/users/selectlist?page=1'. This request has been blocked; the content must be served over HTTPS.`

I double checked my .env file and there it was! My appurl was set to http, instead of https.

Thank you for your help on this subtle config bug that I brought upon myself! Everything works as expected after making the change in my .env file.

**Comment by snipe** [comment]
Awesome! So glad you're sorted :) 

![ArrowWOevenLooking,](https://github.com/snipe/snipe-it/assets/197404/c6f0df04-4c47-437a-9e6e-fb2c8573c4e4)

The APP_URL thing comes up a lot, and we keep trying to find a way to surface it better for users, but it's just kinda tricky, since some people use proxies, unusual TLS termination, etc.
