### ISSUE TITLE
SESSION_DRIVER=cookie breaks the application

### ISSUE THREAD

**Issue by vladimir-krstulja-ipf** [grokability/snipe-it#13701]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If the `SESSION_DRIVER` env is set to `cookie`, two things (that were tested here) stop working:
1. Pre-flight check cannot create the first user
2. Cannot login

In both cases, the pages just reload, with no error or message logged: not in the page, nor the JS console, nor the laravel log.

### Reproduction steps

1. configure SESSION_DRIVER=cookie
2. recache the config (ie. `php artisan config:cache`)
3. clear all cookies, go to your Snipe-IT application and try to login

Alternatively during the Pre-flight check:
3. Run through the pre-flight check and try to create the first admin user

### Expected behavior

Login working normally; pre-flight check creating the first user.

### Snipe-IT Version

6.1.2

### Operating System

Debian 11 (Bullseye)

### Web Server

nginx

### PHP Version

7.4

### Additional context

Installation from git, running natively on the server, not in a docker container.

**Comment by snipe** [comment]
I'd probably check that your `COOKIE_DOMAIN` and `SECURE_COOKIES` settings are correct for your application. We have not made any changes to cookie storage in some time.

**Comment by snipe** [comment]
(Also make sure there are no weird characters in your passwords in that file, etc. Trailing spaces and unenclosed characters can cause things to break in weird ways)

**Comment by vladimir-krstulja-ipf** [comment]
The `COOKIE_DOMAIN` and `SECURE_COOKIES` I checked, and they're both as they should be (correct domain, https only, proper public CA TLS cert (LetsEncrypt)). I'm also assuming that if those were incorrect, not even the `file` based session would work? The app is still setting cookies.

I'm sorry, I failed to mention in the report that when the session driver is set to `file`, the application works normally.

**Comment by MasterCakeX5** [comment]
I have a similar issue.
when changing from "file" to "cookie" a login is not possible anymore When trying to login the page simply refreshes.
Different browsers, private mode, clearing cookies, nothing makes a difference.

No SSL enabled on the server, no special other settings.

this works:
 `SESSION_DRIVER=file
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
PASSPORT_COOKIE_NAME='snipeit_passport_token'
COOKIE_DOMAIN=ime.fraunhofer.de
SECURE_COOKIES=false
API_TOKEN_EXPIRATION_YEARS=15
BS_TABLE_STORAGE=cookieStorage
BS_TABLE_DEEPLINK=true`

this doesnt work (even when putting in correct domain):
`SESSION_DRIVER=cookie
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
PASSPORT_COOKIE_NAME='snipeit_passport_token'
COOKIE_DOMAIN=NULL
SECURE_COOKIES=false
API_TOKEN_EXPIRATION_YEARS=15
BS_TABLE_STORAGE=cookieStorage
BS_TABLE_DEEPLINK=true`

I also ran the troubleshooting commands, no change.

**Comment by MasterCakeX5** [comment]
I have a similar issue.
when changing from "file" to "cookie" a login is not possible anymore. 
When trying to login it is not possible and the page simply refreshes. This is for either manual and ldap users.
Different browsers, private mode, clearing cookies, nothing makes a difference.

No SSL enabled on the server, no special other settings.

this works:
 `SESSION_DRIVER=file
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
PASSPORT_COOKIE_NAME='snipeit_passport_token'
COOKIE_DOMAIN=NULL
SECURE_COOKIES=false
API_TOKEN_EXPIRATION_YEARS=15
BS_TABLE_STORAGE=cookieStorage
BS_TABLE_DEEPLINK=true`

this doesnt work (even when putting in correct domain):
`SESSION_DRIVER=cookie
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
PASSPORT_COOKIE_NAME='snipeit_passport_token'
COOKIE_DOMAIN=NULL
SECURE_COOKIES=false
API_TOKEN_EXPIRATION_YEARS=15
BS_TABLE_STORAGE=cookieStorage
BS_TABLE_DEEPLINK=true`

I also ran the troubleshooting commands, no change.
