### ISSUE TITLE
Change HaidiSQL port 3306 to 3307 or 3308

### ISSUE THREAD

**Issue by riobijoy** [grokability/snipe-it#13702]
### Is your feature request related to a problem? Please describe.

I want to change port from 3306 to 3307 or 8,What is the process,Currently configured in IIS

### Describe the solution you'd like

I want to change port from 3306 to 3307 or 8,What is the process,Currently configured in IIS

### Describe alternatives you've considered

I want to change port from 3306 to 3307 or 8,What is the process,Currently configured in IIS

### Additional context

I want to change port from 3306 to 3307 or 8,What is the process,Currently configured in IIS

**Comment by snipe** [comment]
I cannot promise that Snipe-IT is compatible with HeidiSQL, as it's not an officially supported database engine, but you'd want to add `DB_PORT` to your `.env` file under the database section. https://snipe-it.readme.io/docs/configuration#required-database-settings

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#required-database-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.Don't be intimidated by the length of this page. The configuratio...</div></blockquote>
