### ISSUE TITLE
Error 500: creating categories and asset models page

### ISSUE THREAD

**Issue by cjhudlin** [grokability/snipe-it#13714]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

hello,
i have a completely clean install and i have reinstalled the OS and application multiple times, but now i am at a loss as to what is the problem here..
I receive this Error 500 window when clicking either create asset model or create category. the issue seems to be the same as a lot of other users: Exception
The /var/www/html/snipeit/bootstrap/cache directory must be present and writable.

i have check the permissions of the cache file:
drwxrwxr-x.  2 snipeitapp apache   46 Oct  5 17:23 cache

and during install, it is also noted that the cache directory IS wirtable. i am also able to create directories and files under the cache folder 

thank you for the help

### Reproduction steps

1. install snipeIT via the "wget" command in the instructions document and go to relevant web pages
2.
3.
...

### Expected behavior

for the application to work as intended

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/10757247/6af9457e-4dbb-4b81-a7e2-17dee58648a3)

![image](https://github.com/snipe/snipe-it/assets/10757247/2193897b-ba37-40a4-85eb-fc5c0d58b7a3)

![image](https://github.com/snipe/snipe-it/assets/10757247/9d9cbdb5-c40a-4401-8f3e-05ae91dae118)

### Snipe-IT Version

v6.2.1 build 11625

### Operating System

centOS stream 8 (vmware)

### Web Server

apache

### PHP Version

7.4.33

**Comment by snipe** [comment]
If that's what the error is, it's still unable to write to the `bootstrap` and `bootstrap/cache` directory (and any subdirectories). maybe check and see if you have SELinux enabled. https://snipe-it.readme.io/docs/linuxosx#notes-on-selinux

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/linuxosx#notes-on-selinux">Linux/OSX</a></strong></div><div>Setting up a web server can sound daunting for folks who don't normally do that kind of thing. This guide will help you walk through the configuration for Apache or Nginx on Linux and OSX.Using ApacheThe most common setup for Snipe-IT on a linux server is to use Apache, so if you're not sure what to...</div></blockquote>

**Comment by cjhudlin** [comment]
thank you for your reply. it seems i have it enabled:

![image](https://github.com/snipe/snipe-it/assets/10757247/8041a35b-5988-4b01-9b73-71b431a0f644)

**Comment by cjhudlin** [comment]
it seems i have resolved the issue by running:

semanage fcontext -a -t httpd_sys_rw_content_t "/srv/snipeit/storage(/.*)?"
semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/html/snipeit/bootstrap/cache(/.*)?"
restorecon -RF /srv/snipeit/storage
restorecon -RF /var/www/html/snipeit/bootstrap/cache

as root :)

Thank you!

**Comment by snipe** [comment]
Glad you're sorted :)
