### ISSUE TITLE
Bulk Upload with Incorrect Format in Custom Field

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13721]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

You can still bulk Upload an incorrect format field if you have a different format. eg. IPV4

### Reproduction steps

1. Custom Field 
2. Add custom field, change format
3. Mass upload, Will still upload data and ignore format
4. When you next make changes on the asset, that specific asset will error until you make an update on the field with the problem.
(Shouldn't even get to that stage, Should be errored at bulk upload stage)
...

### Expected behavior

We only noticed this issue because now if we want to relocate asset from one location to another. We cannot because a Custom Field has the wrong information in and IPV4 format.

So when we uploaded a year ago, In the IPV4 format we uploaded the word "No Entry" Which we have also selected as must be unique. So now unless we manually go into each asset we cant relocate the asset using the "Bulk Edit" relocation way.

Maybe an error on when you do a bulk upload without complying to the correct format requirements. Also if a field is currently filled incorrectly, data is removed.

### Snipe-IT Version

 v6.2.2 build 11714 (ga95fae0e9) 

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.1.22

**Comment by snipe** [comment]
Can you not update the custom field value of the selected items in the bulk asset edit?

**Comment by jayavman** [comment]
Absolutely. I've fixed it this time. Just would be great to have error messages. I love a good error message to keep me in check.

**Comment by snipe** [comment]
Well, I’m just not sure where that error message would even go. If you change the custom field type, are we meant to walk through every single value in your custom fields (potentially 100k or more) to make sure they all validate with your new field type? I’m just not sure what would work practically speaking.

**Comment by jayavman** [comment]
I'm guessing that when you import the database, and you select a custom field set and you go to click upload. If the custom field set has a wrong value set it would come back with an error on the import page. Just like it does right now if you put incorrect characters in say , Asset name fields

**Comment by snipe** [comment]
There are't incorrect characters for asset name fields though. We let you put in whatever you want, or nothing at all. 

Just to clarify, this is bulk edit, or import? The naming of this issue is confusing, so I'd like to clarify.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
