### ISSUE TITLE
Not able to upgrade snipe-it v6.0.1 to 6.2.2

### ISSUE THREAD

**Issue by AlphonesDamonlette** [grokability/snipe-it#13736]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I tried to upgrade my snipe-it version 6.0.1 using PHP upgrade.php but getting errors.

### Reproduction steps

1.ubuntu@http3:/var/www/html/snipe-it$ 
2.php upgrade.php
3.
...

### Expected behavior

/var/www/html/snipe-it$ php upgrade.php

--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER! 
--------------------------------------------------------

This script will attempt to: 

- check your PHP version and extension requirements 
- do a git pull to bring you to the latest version 
- run composer install to get your vendors up to date 
- run migrations to get your schema up to date 
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements: 
--------------------------------------------------------

Current PHP version: (8.1.2-1ubuntu2.14) is at least 7.4.0 - continuing... 
FYI: The php.ini used by this PHP is: /etc/php/8.1/cli/php.ini

Checking Required PHP extensions... 

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ sodium is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database: 
--------------------------------------------------------

-- Starting backup...
Backup failed because: mkdir(): Permission denied.

--------------------------------------------------------
STEP 3: Putting application into maintenance mode: 
--------------------------------------------------------

-- Failed to enter maintenance mode.
file_put_contents(/var/www/html/snipe-it/storage/framework/down): Failed to open stream: Permission denied

--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch): 
--------------------------------------------------------

Git is installed. 
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- -- -- 
--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ Deleting bootstrap/cache/services.php. It is no longer used.
√ No bootstrap/cache/config.php, so nothing to delete.

-- Configuration cache cleared!
-- Failed to clear cache. Make sure you have the appropriate permissions.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.

In Filesystem.php line 886:
                                                                                                           
  fopen(/var/www/html/snipe-it/vendor/composer/ClassLoader.php): Failed to open stream: Permission denied  
                                                                                                           

dump-autoload [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--apcu-prefix APCU-PREFIX] [--dry-run] [--dev] [--no-dev] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--strict-psr]

Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package fruitcake/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files

In Filesystem.php line 886:
                                                                                                           
  fopen(/var/www/html/snipe-it/vendor/composer/ClassLoader.php): Failed to open stream: Permission denied  
                                                                                                           

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

Generating optimized autoload files

--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is already up.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use 
your upgraded Snipe-IT!
--------------------------------------------------------

### Snipe-IT Version

v6.0.1 - build 7750 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

PHP 8.1.2-1ubuntu2.14 (cli)

### Error messages

```shell
/var/www/html/snipe-it$ php upgrade.php
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER! 
--------------------------------------------------------

This script will attempt to: 

- check your PHP version and extension requirements 
- do a git pull to bring you to the latest version 
- run composer install to get your vendors up to date 
- run migrations to get your schema up to date 
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements: 
--------------------------------------------------------

Current PHP version: (8.1.2-1ubuntu2.14) is at least 7.4.0 - continuing... 
FYI: The php.ini used by this PHP is: /etc/php/8.1/cli/php.ini

Checking Required PHP extensions... 

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ sodium is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database: 
--------------------------------------------------------

-- Starting backup...
Backup failed because: mkdir(): Permission denied.


--------------------------------------------------------
STEP 3: Putting application into maintenance mode: 
--------------------------------------------------------

-- Failed to enter maintenance mode.
file_put_contents(/var/www/html/snipe-it/storage/framework/down): Failed to open stream: Permission denied

--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch): 
--------------------------------------------------------

Git is installed. 
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- -- -- 
--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ Deleting bootstrap/cache/services.php. It is no longer used.
√ No bootstrap/cache/config.php, so nothing to delete.

-- Configuration cache cleared!
-- Failed to clear cache. Make sure you have the appropriate permissions.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.


In Filesystem.php line 886:
                                                                                                           
  fopen(/var/www/html/snipe-it/vendor/composer/ClassLoader.php): Failed to open stream: Permission denied  
                                                                                                           

dump-autoload [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--apcu-prefix APCU-PREFIX] [--dry-run] [--dev] [--no-dev] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--strict-psr]

Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package fruitcake/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files

In Filesystem.php line 886:
                                                                                                           
  fopen(/var/www/html/snipe-it/vendor/composer/ClassLoader.php): Failed to open stream: Permission denied  
                                                                                                           

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

Generating optimized autoload files

--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is already up.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use 
your upgraded Snipe-IT!
--------------------------------------------------------
```

**Comment by AlphonesDamonlette** [comment]
Need some help?

**Comment by AlphonesDamonlette** [comment]
Can anyone help me with this issue?

**Comment by snipe** [comment]
Based on those errors, you have a permissions issue. Check the permissions on the application directory and make sure they are writable by the user you're trying to upgrade as.

**Comment by AlphonesDamonlette** [comment]
I have changed the permission and it worked. But still, the snipe version is 6.0.1 

ubuntu@http3:/var/www/html/snipe-it$ php upgrade.php
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER! 
--------------------------------------------------------

This script will attempt to: 

- check your PHP version and extension requirements 
- do a git pull to bring you to the latest version 
- run composer install to get your vendors up to date 
- run migrations to get your schema up to date 
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements: 
--------------------------------------------------------

Current PHP version: (8.1.2-1ubuntu2.14) is at least 7.4.0 - continuing... 
FYI: The php.ini used by this PHP is: /etc/php/8.1/cli/php.ini

Checking Required PHP extensions... 

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ sodium is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database: 
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Determining files to backup...
Zipping 360 files and directories...
Created zip containing 360 files and directories. Size is 12.62 MB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!


--------------------------------------------------------
STEP 3: Putting application into maintenance mode: 
--------------------------------------------------------

-- Application is now in maintenance mode.

--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch): 
--------------------------------------------------------

Git is installed. 
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- -- -- 
--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ Deleting bootstrap/cache/services.php. It is no longer used.
√ No bootstrap/cache/config.php, so nothing to delete.

-- Configuration cache cleared!
-- Failed to clear cache. Make sure you have the appropriate permissions.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package fruitcake/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
85 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: maatwebsite/excel
Discovered Package: mediconesystems/livewire-datatables
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
Generated optimized autoload files containing 8809 classes

Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: maatwebsite/excel
Discovered Package: mediconesystems/livewire-datatables
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use 
your upgraded Snipe-IT!
--------------------------------------------------------

**Comment by snipe** [comment]
```
Git is installed.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```

The version is not updating because you're not using a git install. You'd have to update the files manually, or switch to a git install (recommended.)

- https://komodor.com/blog/solving-fatal-not-a-git-repository-error/
- https://snipe-it.readme.io/docs/switching-to-a-git-install


<blockquote><img src="https://komodor.com/wp-content/uploads/2021/06/solving-fatal-not-a-git-repository.png" width="48" align="right"><div><img src="https://komodor.com/wp-content/uploads/2021/05/favicon.png" height="14"> Komodor</div><div><strong><a href="https://komodor.com/blog/solving-fatal-not-a-git-repository-error/">Solving “Fatal: Not A Git Repository” (Or Any Of The Parent Directories) Error</a></strong></div><div>The error ‘fatal: not a git repository’ occurs when you try to run a Git command but are not inside a Git repository. Here are some reasons why this error might occur: you are in the wrong working directory, you mistyped the path to the repo, or you didn't initialize the Git repository.</div></blockquote>
<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/switching-to-a-git-install">Switching to a Git Install</a></strong></div><div>As we mention (several times) throughout the documentation, installing via Git is our recommended way of installing Snipe-IT and keeping it up to date. If you installed manually (downloading a tarball or .zip file from Github), you can still switch to a Git install with just a little work. Doing so ...</div></blockquote>
