### ISSUE TITLE
Unable to delete company with https redirect on

### ISSUE THREAD

**Issue by thenebular** [grokability/snipe-it#13735]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

With force ssl redirect enabled in .htaccess I am unable to delete any companies I have entered. I will get a warning saying that the information I'm about to submit is insecure and if I click send anyway it just takes me to the details page of the company and doesn't delete the company. If I disable redirect it will still warn about it being insecure, but it will delete the company. However all navigation after that will be over http instead of https. The links for the delete buttons begin with http.

### Reproduction steps

1. enable force SSL redirect in .htaccess
2. attempt to delete a company
3.
...

### Expected behavior

I expected the company selected to be deleted and for navigation to remain in https.

### Snipe-IT Version

v6.2.2 build 11714 (ga95fae0e9)

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.14

### Operating System

Windows

### Browser

Edge, Chrome, Firefox

### Version

Edge: 117.0.2045.60, Chrome: 117.0.5938.150, Firefox: 115.2.1esr

### Additional context

This is a fresh install of Ubuntu and Snipe-IT. Sniple-IT was installed using install.sh.
Apache was configured to use SSL with Snipe-IT, .htaccess was modified to force SSL redirect.
LDAP sync and SAML with azure have been configured. 
Entering and attempting to delete a company was the first thing I tried to do outside of SSL and user administration.

**Comment by snipe** [comment]
What's your APP_URL set to?

**Comment by thenebular** [comment]
APP_URL was set to http. I completely missed that. Thank you very much.
