### ISSUE TITLE
When deleteting categories page redirect me to localhost/localhost/categories/2

### ISSUE THREAD

**Issue by AnrichOdendaal** [grokability/snipe-it#13741]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,

When i want to delete categories and click yes it redirects me to localhost/localhost/categories/2

When i create my categories i can see on phpmyadmin that they are created bur on my snipe-it dashboard its not there.

Please can you assist

### Reproduction steps

1. Go to categories 
2. Click on Delete 
3. Confirm yes
4. Page gets redirected
5.
6.
...

### Expected behavior

It should delete the categories

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/147715372/707188aa-5bfa-43b9-a685-9fae482adc78)

### Snipe-IT Version

6.1.2

### Operating System

Windows

### Web Server

Apache

### PHP Version

8.0.28

**Comment by snipe** [comment]
My guess would be that your `APP_URL` is misconfigured in your `.env` file. [Per the documentation](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings), the APP_URL should be the complete URL to your Snipe-IT installation, *including* the `http://` (or `https://` if you're running over TLS.)

<img width="795" alt="Screen Shot 2022-07-28 at 11 35 47 PM" src="https://user-images.githubusercontent.com/197404/181698021-de470225-4865-4786-bd48-9a9cdf2399d2.png">

**Comment by AnrichOdendaal** [comment]
Thanks Snipe problem solved

**Comment by snipe** [comment]
Excellent - glad you're sorted!
