### ISSUE TITLE
New label engine, Title does not work on all models 

### ISSUE THREAD

**Issue by kevinc4499** [grokability/snipe-it#13768]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

#12050 
On the new label engine, using the Title field results in inconsistent application in the label. To further detail, it seems that all assets under a model do not include the title and other models have no issue with having the title in the asset label. i.e. Dell laptop with 32 gigs of RAM SKU all have this lack of Title, Dell laptop with 16 gigs of RAM SKU all do not have this issue. 

### Reproduction steps

1. Enter something for Title property under TZE_24mm_A
2. Generate label for asset
3. Some labels under certain models never have the Title field 
...

### Expected behavior

Title should be shown for any generated asset

### Screenshots

<img width="199" alt="glitch 3" src="https://github.com/snipe/snipe-it/assets/148479591/c274556f-d5df-465a-90ca-85e8bc44ac5c">
<img width="259" alt="glitch2" src="https://github.com/snipe/snipe-it/assets/148479591/272f8103-f7c4-4fda-b126-43bc60d9fb8a">

### Snipe-IT Version

v6.2.0-pre - build 11391

### Operating System

Rocky Linux 9.2

### Web Server

httpd (Apache)

### PHP Version

8.1.23

**Comment by enkidu** [comment]
Hey,
I've found this as well. Reason of this behaviour is simple, lies in App/View/Label.php:
` 
if ($asset->company && !empty($settings->label2_title)) {
    $title = str_replace('{COMPANY}', $asset->company->name, $settings->label2_title);
    $settings->qr_text;
    $assetData->put('title', $title);
}
`
if asset has no Company set, no title will be printed. For quick and dirty fix I've added:
`
else if (!empty($settings->label2_title)) {
    $settings->qr_text;
    $assetData->put('title', $settings->label2_title);
}
`
but it may require more logic to be embedded, so I will make no pull request for this. Also, I made some custom labels but need to dive deeper in math behind them

**Comment by jhd-old** [comment]
Unfortunately, we have the same problem. We do not use the Company field. However, we would still like to be able to assign a title.

**Comment by marcusmoore** [comment]
Thanks for reporting and thanks for diving in @enkidu.

I'll have a fix PR'd shortly.

**Comment by marcusmoore** [comment]
PR is up to fix this: #14307
