### ISSUE TITLE
Your app key has changed! Could not decrypt LDAP password using your current app key, so LDAP authentication has been disabled. Login with a local account, update the LDAP password and re-enable it in Admin > Settings.

### ISSUE THREAD

**Issue by marukofj** [grokability/snipe-it#13767]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Your app key has changed! Could not decrypt LDAP password using your current app key, so LDAP authentication has been disabled. Login with a local account, update the LDAP password and re-enable it in Admin > Settings.

### Reproduction steps

1.
![image](https://github.com/snipe/snipe-it/assets/106718791/34ffad68-7ba0-4b41-a848-286151424b7c)

2.
![image](https://github.com/snipe/snipe-it/assets/106718791/7975d2b5-f30d-4b62-9b30-65b313055926)

3.
...

### Expected behavior

repair

### Snipe-IT Version

6.2.3

### Operating System

ubuntu22.04

### Web Server

nginx

### PHP Version

8.1.2

**Comment by snipe** [comment]
It's telling you what's wrong. Your app key changed and it cannot decrypt the LDAP password. You'll need to either find your old app key, or just re-enter your LDAP password it gets encrypted with the new key.

**Comment by marukofj** [comment]
我没输入密码，已经解决了这个问题

**Comment by IvanROU** [comment]
> It's telling you what's wrong. Your app key changed and it cannot decrypt the LDAP password. You'll need to either find your old app key, or just re-enter your LDAP password it gets encrypted with the new key.

where to look for this key if the database was installed on a new server?
