### ISSUE TITLE
[Feature Request]: Add changes in asset information notes to notes section so they are easier to read

### ISSUE THREAD

**Issue by timb2** [grokability/snipe-it#13771]
### Is your feature request related to a problem? Please describe.

Notes added in to the asset information page get added to the changed section is history. Can these be copied to the notes section in history as well? 

<img width="502" alt="Screenshot 2023-10-19 at 10 30 37 AM" src="https://github.com/snipe/snipe-it/assets/18133103/9ef0a1a4-fb25-4f44-806f-45a5119b2f21">

### Describe the solution you'd like

have the updated notes shown in the notes section of asset history

### Describe alternatives you've considered

change the name of the top notes label to check in/check out notes so it's easier to distinguish between the two

**Comment by snipe** [comment]
That's not what that's for though. A checkout/checkin action already has its own ability to add notes.

<img width="1606" alt="Screenshot 2023-10-26 at 3 02 55 PM" src="https://github.com/snipe/snipe-it/assets/197404/7c0e730f-cd4b-47fb-bf95-5643a47b0deb">
