### ISSUE TITLE
Missing checkout mail via API

### ISSUE THREAD

**Issue by SeizeOx** [grokability/snipe-it#13782]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hey Guys,

i am currently making my first steps using api to checkout an Accessory. The checkout works but no checkoutmail is sent to the user. Same for Consumables. Using the manual checkout both mails will be sent

### Reproduction steps

Using the normal code on the API help documents

### Expected behavior

I expectet that the mail will be sent 

### Snipe-IT Version

 v6.2.3

### Operating System

Windows

### Web Server

Apache

### PHP Version

no clue

**Comment by snipe** [comment]
Are you still seeing this issue?

@marcusmoore - can you take a look when you have a moment?

**Comment by marcusmoore** [comment]
@snipe will do.

**Comment by marcusmoore** [comment]
This is handled in the two PRs linked above. Thanks for reporting @SeizeOx 😄
