### ISSUE TITLE
500 Server Error on Image Upload

### ISSUE THREAD

**Issue by iamjustingraves** [grokability/snipe-it#13785]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When creating a new accessory and uploading an image for it, once clicking save, Snipe immediately errors to 500 server error. The image loads prior to clicking save. 

Saving the accessory without an image is successful. Going back and adding an image later also gives the 500 server error

![image](https://github.com/snipe/snipe-it/assets/86367850/cd1a4d42-ac36-4e6b-8de7-99a1714ece4f)

### Reproduction steps

1. Add new accessory
2. Upload image file
3. Click Save
...

### Expected behavior

When adding an accessory, it's expected to allow an image upload and then a successful save.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/86367850/2d05e4d1-a5ef-42e8-a754-365159b28cc4)

### Snipe-IT Version

5.2.3

### Operating System

Windows Server 2016

### Web Server

IIS

### PHP Version

8.1.5

### Operating System

Windows 11

### Browser

Edge

**Comment by snipe** [comment]
Without app/server logs, I'm not sure how you think we can help you. Please provide them and we'll try our best. This is most likely a permissions issue, but without error logs, it's impossible to say.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
