### ISSUE TITLE
[Feature Request]: change column name of files tab

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#13780]
### Is your feature request related to a problem? Please describe.

Since you implemented an additional option to preview an uploaded file rather than just the option to download it, maybe it makes sense to rename the column "Download" to something like "File options" ? Or what do you think?
![image](https://github.com/snipe/snipe-it/assets/112496896/ce07d2af-5a8a-409a-8774-09a1f9586d0b)

### Describe the solution you'd like

Described above

### Additional context

Feature was added in #13566 by @snipe

**Comment by snipe** [comment]
I don't think that's necessary (and wouldn't always make sense, if the file cannot be previewed. Either option will let you download the file, either by forced download or by using "Save as" in the browser. The proposed phrasing would only make it more confusing I think.
