### ISSUE TITLE
Image not uploading to s3

### ISSUE THREAD

**Issue by Ashu7950** [grokability/snipe-it#13790]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Facing "currently unable to handle this request.HTTP ERROR 502"
 when i try to upload data with images.
And
I am running snipeit as Apprunner service and using mariadb RDS as database(made sure both are in same vpc) and s3 bucket to store the asset images (have created public and private buckets with necessary permissions)

### Reproduction steps

facing this issue when i try to create a company and 
try uploading an image 

### Expected behavior

when i upload any image i want it to be stored in s3.

### Screenshots

<img width="1214" alt="image" src="https://github.com/snipe/snipe-it/assets/135582247/0bc69a40-64c6-4f9f-94d4-f8b45fd11514">
here are the logs

![image](https://github.com/snipe/snipe-it/assets/135582247/7c6e0d71-a58f-41e9-bcc9-948a3213feba)

### Snipe-IT Version

6.1.2

### Operating System

Ubuntu

### Web Server

aws 

### PHP Version

8.1.22

**Comment by snipe** [comment]
502 is a gateway timeout tho - you sure you have your buckets configured correctly?

**Comment by Ashu7950** [comment]
these are the configuration that i have set and I am sure they are correct.
Also set  FILESYSTEM_DISK=s3
<img width="236" alt="image" src="https://github.com/snipe/snipe-it/assets/135582247/62d218ef-0ad6-42d2-b2cb-b1d6748952c4">

**Comment by snipe** [comment]
Maybe check your security groups in AWS, firewalls, etc? 502 means our software is timing out trying to talk to S3.

**Comment by Ashu7950** [comment]
Yeah I tried by allowing all inbound and outbound traffic,but still the issue persists.

**Comment by snipe** [comment]
Also I'm not sure what that screenshot is meant to be? We don't have those variables in the env config.

```
# --------------------------------------------
# PUBLIC S3 Settings
# --------------------------------------------
PUBLIC_AWS_SECRET_ACCESS_KEY='XXXXYYYYZZZZ'
PUBLIC_AWS_ACCESS_KEY_ID='111122223333'
PUBLIC_AWS_DEFAULT_REGION='us-west-2'
PUBLIC_AWS_BUCKET=snipe-flysystem-public-test
PUBLIC_AWS_URL='https://snipe-flysystem-public-test.s3-us-west-2.amazonaws.com'

# --------------------------------------------
# PRIVATE S3 Settings
# --------------------------------------------
PRIVATE_AWS_SECRET_ACCESS_KEY='stuff'
PRIVATE_AWS_ACCESS_KEY_ID='111122223333'
PRIVATE_AWS_DEFAULT_REGION='us-west-2'
PRIVATE_AWS_BUCKET=snipe-flysystem-private-test

```

**Comment by snipe** [comment]
> Yeah I tried by allowing all inbound and outbound traffic,but still the issue persists.

And yet, it's a 502. Something is causing the connection not to work between your Snipe-IT instance and S3.

**Comment by Ashu7950** [comment]
These are the variables that I am using in my config

APP_ENV=production
APP_DEBUG=true
APP_KEY=base64:3ilviXqB9u6DX1NRcyWGJ+sjySF+H18CPDGb3+IVwMQ=
APP_URL=xxx
APP_TIMEZONE='UTC'
APP_LOCALE=en
MAX_RESULTS=500

PRIVATE_FILESYSTEM_DISK=s3_private
PUBLIC_FILESYSTEM_DISK=s3_public

DB_CONNECTION=mysql
DB_HOST=xxxxx
DB_DATABASE=mariadb
DB_USERNAME=username
DB_PASSWORD=ppppp
DB_PREFIX=snipeit
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

IMAGE_LIB=gd


FILESYSTEM_DISK=s3

PUBLIC_AWS_SECRET_ACCESS_KEY=xxxxxxxxx
PUBLIC_AWS_ACCESS_KEY_ID=yyyyyyyy
PUBLIC_AWS_DEFAULT_REGION=us-east-1
PUBLIC_AWS_BUCKET=snipeit-public
PUBLIC_AWS_URL=zzzz
PUBLIC_AWS_BUCKET_ROOT=null

PRIVATE_AWS_ACCESS_KEY_ID=yyyyyyy
PRIVATE_AWS_SECRET_ACCESS_KEY=xxxxxxx
PRIVATE_AWS_DEFAULT_REGION=us-east-1
PRIVATE_AWS_BUCKET=snipeit-private
PRIVATE_AWS_URL=null
PRIVATE_AWS_BUCKET_ROOT=null

**Comment by jerm** [comment]
I can't reproduce this. Stood up a brand new setup, filled-out those fields with proper values, and I'm able to upload files just fine, that snipe-it is then able to access.

Couple of ideas:
1) can you try this using the aws cli, using those credentials, from that server, and see what happens?
2) sniff your network using ngrep, or similar, on the server, searching for outbound connections, and see what URLs you're trying to access? @snipe is absolutely correct: Timeout errors speak to a network issue -- either a bad name sending you to an address that doesn't respond, or some other kind of jank.  IS your APP_URL correct?

Also, what environment are you running in?  How permissive are the network rules _really_?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
