### ISSUE TITLE
[Feature Request]: 可以将LDAP用户名设置为邮箱吗 这要改成什么字段Can LDAP usernames be set as email addresses? What field should this be changed to?

### ISSUE THREAD

**Issue by marukofj** [grokability/snipe-it#13792]
### Is your feature request related to a problem? Please describe.

Can LDAP usernames be set as email addresses? What field should this be changed to?

### Describe the solution you'd like

Email addresses can be used as usernames for logging in.

**Comment by snipe** [comment]
Yes, we generally recommend making the username the email address. https://snipe-it.readme.io/docs/ldap-sync-login

<img width="819" alt="Screenshot 2023-10-25 at 9 09 58 PM" src="https://github.com/snipe/snipe-it/assets/197404/5775fdf5-28c0-4515-a0b8-4330aae53804">


<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/ldap-sync-login">LDAP Sync & Login</a></strong></div><div>🚧WARNING ABOUT USERNAMES &amp; SYNCINGSnipe-IT considers the username of a user to be the unique identifier when syncing with LDAP/AD. If you manually created some users, or imported them via CSV, using a non-email address style username, you are likely to create duplicate users when you subsequent...</div></blockquote>
