### ISSUE TITLE
[Feature Request]: Custom fields required

### ISSUE THREAD

**Issue by tiennv3011** [grokability/snipe-it#13791]
### Is your feature request related to a problem? Please describe.

Hi,

I want the custom field information to be required for data entry when displayed. What should I do to make sure the information is mandatory to save? Thanks

### Describe the solution you'd like

![image](https://github.com/snipe/snipe-it/assets/142978084/1d51c4c4-4b23-41f0-859f-36a4be58f397)

**Comment by snipe** [comment]
You can control required-ness in the custom fieldset -> fields interface.


https://github.com/snipe/snipe-it/assets/197404/e5522a7c-3021-4621-b387-fb16bd42bfb4

**Comment by tiennv3011** [comment]
> You can control required-ness in the custom fieldset -> fields interface.
> 
> 
> https://github.com/snipe/snipe-it/assets/197404/e5522a7c-3021-4621-b387-fb16bd42bfb4
> 
> 

many thanks !!
