### ISSUE TITLE
[Feature Request]: Domain White Label for Hosted Instances

### ISSUE THREAD

**Issue by nam2long** [grokability/snipe-it#13804]
### Is your feature request related to a problem? Please describe.

Domain White Label for Hosted Instances (WebsiteName.com v.s current WebsitName.snipeit.io)

### Describe the solution you'd like

Domain White Label for Hosted Instances (WebsiteName.com v.s current WebsitName.snipeit.io)

### Additional context

CNAME Record option with custom script on your site to generate a lets encrypt on behalf of the white label domain and the subdomain all in one cert or at least cert uploading

**Comment by snipe** [comment]
Hi @nam2long - that’s already an option. You can reach out to support@snipeitapp.com and request the custom domain/subdomain for your hosted account. You will need to have your CNAME in place before we can do that, but once you have, it’s a very quick process.
