### ISSUE TITLE
Unable to Check-out assets in Snipe

### ISSUE THREAD

**Issue by jorgechinchill** [grokability/snipe-it#13807]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, We are currently having an issue checking out assets in Snipe, and I have a feeling that this is due to an update on the way Snipe works, so I would really appreciate any feedback or clarification on this. 

We have multiple assets that have a specific Company on them, and when trying to check them out to a user, we get the error: 
` Error Checkout target company and asset company do not match
`

Can you help us understand why this is happening and how we can resolve it? 

I saw an option in the General setting for "Full Multiple Companies support," but I'm unsure if disabling it will resolve the issue. 

### Reproduction steps

1. Have a an assets assigned to a different company
2. Checkout asset to a user

### Expected behavior

We were able to check out any asset to any user in the past. 

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/139795812/78d2483b-b79f-45f3-9220-e3bd7e51228a)

![image](https://github.com/snipe/snipe-it/assets/139795812/b845e2a0-97e7-4282-948a-dea788182458)

### Snipe-IT Version

v6.2.3 build 11759

### Operating System

Unsure

### Web Server

Unsure

### PHP Version

8.1.23

### Operating System

Windows

### Browser

Google Chrome

### Version

Chrome 118 on Windows 11

### Error messages

```shell
Error Checkout target company and asset company do not match
```

**Comment by snipe** [comment]
This is sort of expected behavior, as the company the user belongs to and the company the asset belongs to do not match, and you have full multiple company support enabled. Full multiple company support specific silos by company, so if you don't need that functionality, unchecking that box should resolve your issue.

**Comment by jorgechinchill** [comment]
I understand. Thank you for providing clarification!
