### ISSUE TITLE
[SOLVED] 500 Error when saving any asset

### ISSUE THREAD

**Issue by kwoodVisions** [grokability/snipe-it#13843]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Saving any asset displays a server 500 error.  With DEBUG turned on, the error is:

Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'eol_explicit' in 'field list' (SQL: update `assets` set `requestable` = 0, `location_id` = 1, `eol_explicit` = 0, `assets`.`updated_at` = 2023-11-06 15:04:56 where `id` = 54)
https://snipeit/hardware/54

Ran the "Migrations" from the page but it failed.

### Reproduction steps

Save any asset.
Get 500 error.

### Expected behavior

Save the asset

### Screenshots

![Screenshot_857](https://github.com/snipe/snipe-it/assets/38136107/98448b87-04ed-48b7-b2b4-18fb345afcd9)
![Screenshot_856](https://github.com/snipe/snipe-it/assets/38136107/9fcef21b-961a-4531-9735-ddd57a77b65e)

### Snipe-IT Version

6.2.3

### Operating System

ubuntu 22.04

### Web Server

apache2

### PHP Version

7.4.33

### Operating System

windows

### Browser

chrome, firefox

### Error messages

```shell
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'eol_explicit' in 'field list' (SQL: update `assets` set `requestable` = 0, `location_id` = 1, `eol_explicit` = 0, `assets`.`updated_at` = 2023-11-06 15:04:56 where `id` = 54)
https://snipeit/hardware/54



A column was not found
You might have forgotten to run your migrations. You can run your migrations using php artisan migrate.

Pressing the button below will try to run your migrations.

Something went wrong when executing the solution. Please try refreshing the page and try again.
```

**Comment by kwoodVisions** [comment]
Link to Stacktrace:

https://flareapp.io/share/87nKLed5

<blockquote><div><img src="https://flareapp.io/favicon-16x16.png" height="14"> Flare</div><div>SQLSTATE[42S22]: Column not found: 1054 Unknown column 'eol_explicit' in 'field list' (SQL: update `assets` set `requestable` = 0, `location_id` = 1, `eol_explicit` = 0, `assets`.`updated_at` = 2023-11-06 15:04:56 where `id` = 54) - The error occurred at https://snipeit/hardware/54</div></blockquote>

**Comment by inietov** [comment]
Maybe you can try looking if you have any pending migration?

**Comment by kwoodVisions** [comment]
> Maybe you can try looking if you have any pending migration?

How would I go about checking for that?  I ran the "Run Migrations" on the debug page and that failed.

**Comment by inietov** [comment]
If you have access to the server where Snipe-IT is installed you can run the migrations by hand: `php artisan migrate` we also have an upgrade script, because when upgrading manually is common to forget running the migrations. When you need to upgrade you can run `php upgrade.php`  and it takes care of everything.

**Comment by kwoodVisions** [comment]
This is what I got when I ran it:
```

Migrating: 2023_07_13_052204_denormalized_eol_and_add_column_for_explicit_date_to_assets

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs (SQL: alter table `assets` add `eol_explicit` tinyint(1) not null default '0' after `asset_eol_date`)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

      +9 vendor frames
  10  database/migrations/2023_07_13_052204_denormalized_eol_and_add_column_for_explicit_date_to_assets.php:24
      Illuminate\Support\Facades\Facade::__callStatic()

      +22 vendor frames
  33  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

```

**Comment by kwoodVisions** [comment]
Also, I do run php upgrade.php to upgrade the software.

**Comment by kwoodVisions** [comment]
[SOLVED]

I was able to solve the issue.  The row size being too large can be fixed by altering the table in mariadb via command line and setting the table to dynamic.  Once that's done, I just re-ran the php upgrade.php to get everything and now it's working.
