### ISSUE TITLE
Can not Upgrade version from v6.1.2 to v6.2.3

### ISSUE THREAD

**Issue by tiennv3011** [grokability/snipe-it#13849]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Can not Upgrade version from v6.1.2 to v6.2.3

### Reproduction steps

1. use php upgrade.php
2.
3.
...

### Expected behavior

upgrade to  v6.2.3

### Screenshots

STEP 1: Checking .env file:
- Your .env is located at C:\inetpub\wwwroot\Snipe-IT/.env
--------------------------------------------------------

√ Your APP_KEY is not blank.
√ Your APP_URL is not null or blank. It is set to http://10.0.23.100
√ Your APP_URL is set to http://10.0.23.100 and starts with the protocol (https:// or http://)
√ Your APP_URL (http://10.0.23.100) does not have a trailing slash.

--------------------------------------------------------
STEP 2: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (8.0.29) is at least 7.4.0 - continuing...
FYI: The php.ini used by this PHP is: C:\PHP\php.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ sodium is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 3: Checking directory permissions:
--------------------------------------------------------

√ C:\inetpub\wwwroot\Snipe-IT/bootstrap/cache is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage/logs is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage/logs/laravel.log is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage/framework is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage/framework/cache is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage/framework/sessions is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage/framework/views is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage/app is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage/app/backups is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage/app/backup-temp is writable
√ C:\inetpub\wwwroot\Snipe-IT/storage/private_uploads is writable
√ C:\inetpub\wwwroot\Snipe-IT/public/uploads is writable

--------------------------------------------------------
STEP 4: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Determining files to backup...
Zipping 65 files and directories...
Created zip containing 65 files and directories. Size is 435.89 KB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!

--------------------------------------------------------
STEP 5: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.

--------------------------------------------------------
STEP 6: Pulling latest from Git (master branch):
--------------------------------------------------------

'git' is not recognized as an internal or external command,
operable program or batch file.
Git is NOT installed. You can still use this upgrade script to run common
migration commands, but you will have to manually download the updated files.

Please note that this script will not download the latest Snipe-IT
files for you unless you have git installed.
It simply runs the standard composer, artisan, and migration
commands needed to finalize the upgrade after.

--------------------------------------------------------
STEP 7: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ Deleting bootstrap/cache/services.php. It is no longer used.
√ No bootstrap/cache/config.php, so nothing to delete.
√ No vendor/symfony/translation/TranslatorInterface.php, so nothing to delete.

-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
STEP 8: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- Running the app in production mode.
-- We couldn't find a local composer.phar. No worries, trying globally.
Since you are running composer globally, we won't try to update it for you.
If you run into issues with this step, try running `composer self-update`
before running this updater again

Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package fruitcake/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
85 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
Generating optimized autoload files
Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: maatwebsite/excel
Discovered Package: mediconesystems/livewire-datatables
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Copied Directory [\vendor\livewire\livewire\dist] To [\public\vendor\livewire]
Publishing complete.
Generated optimized autoload files containing 8890 classes

Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: maatwebsite/excel
Discovered Package: mediconesystems/livewire-datatables
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Copied Directory [\vendor\livewire\livewire\dist] To [\public\vendor\livewire]
Publishing complete.
--------------------------------------------------------
STEP 9: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
STEP 10: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
STEP 11: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!
--------------------------------------------------------

### Snipe-IT Version

6.1.2

### Operating System

Windows server 2019

### Web Server

IIS

### PHP Version

8.0.29

### Operating System

Windows 10

### Browser

Chrome

**Comment by snipe** [comment]
If you [don't have a git install](https://snipe-it.readme.io/docs/switching-to-a-git-install), you will have to update the files yourself. See Step 6.
