### ISSUE TITLE
[Feature Request] Resurrect issue - Bulk checkout of ACCESSORIES (previously #7351)

### ISSUE THREAD

**Issue by accltrainer** [grokability/snipe-it#13869]
### Is your feature request related to a problem? Please describe.

Bulk Checkout ACCESSORIES

This feature request was marked as closed/stale, but it has comments up to last week, and I have the same interest. I am asking to resurrect this request, since it has sustained interest. Thanks.

See the thread here: https://github.com/snipe/snipe-it/issues/7351

### Describe the solution you'd like

See https://github.com/snipe/snipe-it/issues/7351

### Describe alternatives you've considered

See https://github.com/snipe/snipe-it/issues/7351

### Additional context

This thread has comments from 2019-2023, and has multiple associated requests. It is NOT solved, because only bulk checkout of assets is possible. This is NOT the same as bulk checkout of *accessories*. Thank you! I appreciate the product :)

**Comment by snipe** [comment]
Re-opened the other one for more context
