### ISSUE TITLE
Question about abandoned packages

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#13867]
### Is your feature request related to a problem? Please describe.

I just updated my Snipe-IT with the built-in upgrade.php script and in Step 8 "Updating composer dependencies", some Packages said, they are abandoned:
![image](https://github.com/snipe/snipe-it/assets/112496896/9613173d-86dd-4e11-94c7-626aa855cfba)

Do I have to do anything, or can I just ignore these messages? Should these packages be replaced?

### Describe the solution you'd like

see above :)

**Comment by snipe** [comment]
Sorry for the delay - yes, you can ignore those.

**Comment by floschoepfer** [comment]
No problem, thanks for the answer!👍🏼
