### ISSUE TITLE
Password reset not finding usernames

### ISSUE THREAD

**Issue by athompsoncmc** [grokability/snipe-it#13862]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When requesting a password reset, and entering a valid and active username, the password reset email does not send. All other emails send properly.
When enabling debug, the error says it cannot find that username. I've tested it with multiple valid users.

### Reproduction steps

1. Submit username on password reset screen
2. Email does not send

### Expected behavior

Password reset email sends

### Screenshots

![smtpsettings](https://github.com/snipe/snipe-it/assets/79665233/0d9310e8-fc44-4a9d-9847-f8f4f0ac0a3a)
![testuser1](https://github.com/snipe/snipe-it/assets/79665233/1f6ce9bd-2972-46c7-8014-1e98487ddb2a)
![testuser2](https://github.com/snipe/snipe-it/assets/79665233/0b579891-c5ce-4e8a-b9d7-71a16920cc05)

### Snipe-IT Version

v6.2.3 build 11759 (g8c4bf74f9)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.24

### Operating System

Windows

### Browser

Google Chrome

### Version

119.0.6045.123

### Error messages

```shell
[08:25:39] LOG.info: Password reset attempt: User matching username testuser NOT FOUND or user is inactive

C:\inetpub\wwwroot\CMCSnipeIT>php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
imap
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
sodium
SPL
standard
tidy
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

**Comment by snipe** [comment]
There's not really much for me to work with here. The forgotten password stuff hasn't been giving anyone else any issues (and also hasn't been changed in ages).
