### ISSUE TITLE
Import File Not Working

### ISSUE THREAD

**Issue by thehamzajunaid** [grokability/snipe-it#13860]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I uploaded an asset in the form of CSV using the "Select File". When I proceed to import the asset under the "Map User Import Fields" I am getting this error,
"Your file import is complete, but we did receive an error. This is usually caused by third-party API throttling from a notification webhook (such as Slack) and would not have interfered with the import itself, but you should confirm this"

### Reproduction steps

1. Select a CSV to import

2. Click the blue button 
![image](https://github.com/snipe/snipe-it/assets/74147991/86d767f4-6eb6-44a9-90f5-ce5fe483569f)

3. Click the import button at the end of the dropdown.
![image](https://github.com/snipe/snipe-it/assets/74147991/efc652a5-44a3-4fad-8d33-bae5d096d942)

### Expected behavior

The asset (User in my case) gets created successfully.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/74147991/189e9eff-7f59-4990-ac44-f6a408e9a1e4)

### Snipe-IT Version

v6.2.3 build 11759 (g8c4bf74f9)

### Operating System

Ubuntu

### Web Server

Nginx

### PHP Version

8.1.2

**Comment by inietov** [comment]
This can be caused by a number of reasons, thats why the kinda unclear error message, we are going to need some logs to better assist you.

**Comment by thehamzajunaid** [comment]
Can you please tell me the procedure step by step for how can I see the logs? 
One more thing is that on the browser I was getting this error after I clicked the "Import" button that I mentioned above,
![image](https://github.com/snipe/snipe-it/assets/74147991/da2ed69a-c89e-43e1-9e9d-476c31aa534c)

**Comment by inietov** [comment]
You can find the error log inside your Snipe-IT directory installation in `storage/logs/laravel.log`.

**Comment by thehamzajunaid** [comment]
These are the logs in the laravel.log file that you mentioned,
![snipeiterrorlog1](https://github.com/snipe/snipe-it/assets/74147991/61923002-e392-41cb-8564-d825fcb29492)
![snipeiterrorlog2](https://github.com/snipe/snipe-it/assets/74147991/7973b112-3996-4a55-9bbb-dd8920de4b3b)

**Comment by inietov** [comment]
Thanks for your response, I'm unable to reproduce that error tho... I think it fails because there is an issue when the importer tries to find the manager you are trying to import for that user. It will help me to debug this issue to know the data you're trying to import, I know that can be worrisome to you, but maybe you can pass it to me just the headers without actual data, or with false data or something...

**Comment by thehamzajunaid** [comment]
Hi inietov, I used the "sample users import csv" format provided at https://snipe-it.readme.io/docs/importing. I see there is no manager field in here. 
![snipe_it_issue](https://github.com/snipe/snipe-it/assets/74147991/c81f97b0-7454-4a00-912e-4438d7201fa8)
Here is the format that I am using (the data is dummy tho). 

I have also tried adding "Manager" field and in the import dropdown I set it to type Username but the error still remains. I would really appreciate if you can help me out what else I can try.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing">Importing Assets and More</a></strong></div><div>There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...</div></blockquote>

**Comment by inietov** [comment]
I was using the same and no error arose... maybe you are in a slightly not-up-to-date version?

**Comment by thehamzajunaid** [comment]
This is the version of my Snipe-IT. 
![snipe_it_issue_version](https://github.com/snipe/snipe-it/assets/74147991/4331e6b1-907c-4cab-b177-d29caa4286aa)

Let me know if there is a new release after that as I saw the documentation and it lists v6.2.3 as the latest which is the same as mine. 

Thankyou for mentioning the other issue. I am following for more updates on that.

**Comment by snipe** [comment]
I believe if you pull from latest, this might be fixed.
