### ISSUE TITLE
[Feature Request]: Check out an asset to multiple users

### ISSUE THREAD

**Issue by humperdink** [grokability/snipe-it#13875]
### Is your feature request related to a problem? Please describe.

No option to check out an asset to multiple users at one time.
For example we have encrypted USB drives that we check out to individual users but some are used by multiple people.

### Describe the solution you'd like

Not sure what the best way to go about this would be. Additional selection in the checkout page? [User, Asset, Location, Users]? or just set it to [User(s), Asset, Location]? Perhaps even an option tied to asset custom fields and fieldsets.

### Describe alternatives you've considered

Creating a duplicate entry for the specified assets and checking them out individually. This can get messy though for obvious reasons.
Adding the secondary user(s) to the notes section

**Comment by snipe** [comment]
That's definitely not on the roadmap. The level of complexity it would introduce to the database schema for a very unusual use-case wouldn't be something we're considering at this time, not to mention it defeats the purpose of accountability for the thing you're tracking.
