### ISSUE TITLE
LDAP Bind not working with OpenLDAP.

### ISSUE THREAD

**Issue by rajkhowaabhijit** [grokability/snipe-it#13883]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,

I have installed Snipe-IT on Ubuntu 22.04.3 LTS. LDAP sync is working flawlessly, but users are not getting bind and cannot log in. While testing a user credentials it says "User didn't bind successfully"

Users are getting synced.

![image](https://github.com/snipe/snipe-it/assets/150221651/3d7a8296-7a6f-4950-8e4f-54403cbb0b78)

Login is not working
![image](https://github.com/snipe/snipe-it/assets/150221651/76f57aa4-91f9-49c4-a4a9-5c96dab714a5)

### Reproduction steps

1. Settings->LDAP
2. Enter LDAP server details
3. Test LDAP Synchronization
4. Test Login
...

### Expected behavior

LDAP should work and user should be able to login

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/150221651/eb27d9e8-b19c-40e8-9815-abb10b669fac)

### Snipe-IT Version

Version v6.2.3 - build 11936 (master)  

### Operating System

VERSION="22.04.3 LTS (Jammy Jellyfish)"

### Web Server

Apache

### PHP Version

8.1.2

**Comment by Galaxy102** [comment]
Did you save your LDAP settings before testing user authentication (as stated in your second screenshot above the input fields)?

**Comment by rajkhowaabhijit** [comment]
> Did you save your LDAP settings before testing user authentication (as stated in your second screenshot above the input fields)?

Yes the settings have been saved. Tried with multiple user accounts, none of them are working.

**Comment by panzli** [comment]
I think this could be the same issue like in https://github.com/snipe/snipe-it/issues/13845 .

**Comment by rajkhowaabhijit** [comment]
> I think this could be the same issue like in #13845 .

Yes sounds similar to this. I believe than rolling back to the last build so do the trick.

**Comment by snipe** [comment]
Duplicate of https://github.com/snipe/snipe-it/issues/13845
