### ISSUE TITLE
Transfer Assets from user to user

### ISSUE THREAD

**Issue by abdou84** [grokability/snipe-it#13897]
### Is your feature request related to a problem? Please describe.

[Transfer Assets from user to user

### Describe the solution you'd like

Awesome tools, it would be great to simplify administration if you can implement transfer assets instead of just Check-in/Checkout.
for example if an employee is leaving the company and another one is taking he's place, for handover and pass to him all the assets, it would be better if we just transfer all the assets from one user to another user instead of check-in all the assets and then go select all this assets one by one and check them out for new employee.

**Comment by snipe** [comment]
This is a more unusual workflow than we're familiar with. Generally speaking, assets have to be imaged, etc so you wouldn't just hand them to another person.

**Comment by snipe** [comment]
Duplicate of #5834 and #8280
