### ISSUE TITLE
LDAP (MS AD) username change not syncing

### ISSUE THREAD

**Issue by MaksaUniver** [grokability/snipe-it#13894]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When we change username/sAMaccountName/userPrincipalName in MS AD and sync users in our Snipe-IT instance, Snipe-IT creates new user with new username, and old Snipe-IT account stays active.

Snipe-IT username is bound/linked to sAMaccountName in AD.

### Reproduction steps

1. Change sAMaccountName in MS AD
2. Sync changes in Snipe-IT instance
3. New user is created
...

### Expected behavior

We expect old account to synchronize username value with the new one.

### Snipe-IT Version

6.1.2

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

**Comment by snipe** [comment]
> Snipe-IT creates new user with new username, and old Snipe-IT account stays active.

Usernames are unique in Snipe-IT, so it couldn't create a user with the same username. My guess is that your mapping is off.

**Comment by MaksaUniver** [comment]
> > Snipe-IT creates new user with new username, and old Snipe-IT account stays active.
> 
> Usernames are unique in Snipe-IT, so it couldn't create a user with the same username. My guess is that your mapping is off.

Snipe-IT creates NEW user with NEW username. I would like if Snipe-IT could update it based on the change from AD.

**Comment by snipe** [comment]
Again, I think your mapping is off. If the username matches, Snipe-IT *cannot* create a new user from that, since usernames are unique. If your mapping is correct and the usernames match, Snipe-IT will update the user record for the username.

**Comment by uberbrady** [comment]
"Username" is the primary identifier for users in Snipe-IT. There isn't any way of changing a username using LDAP, there's no way to say "username 'blahblahblah' should change to 'bleepblorpbloop' ".

If you're changing something - say, moving from `sAMAccountName` to `userPrincipalName`, for instance - it's best to change it directly in the database, then run an LDAP sync.

The only system that allows for usernames to change is SCIM (at least, within Azure AD it's possible. Other IdP's might not be able to do it).

If you *did* end up duplicating users, you can use the user-merge script (which will only merge from shortnames to longnames (see: `php artisan snipeit:merge-users`), or you can use the 'merge users' functionality (by hand-selecting pairs of users at a time, then merging them) to merge them back together.

**Comment by MaksaUniver** [comment]
> Again, I think your mapping is off. If the username matches, Snipe-IT _cannot_ create a new user from that, since usernames are unique. If your mapping is correct and the usernames match, Snipe-IT will update the user record for the username.

These are our LDAP configurations, which we did not change since implementation:
![image](https://github.com/snipe/snipe-it/assets/96291111/a3ce94f3-001e-4edc-9a75-6acdd49116a5)
If you think they are wrong, please let me know.

> There isn't any way of changing a username using LDAP, there's no way to say "username 'blahblahblah' should change to 'bleepblorpbloop' ".

If that's the case, than why this says when we try to edit user in Snipe-IT:
![image](https://github.com/snipe/snipe-it/assets/96291111/7908a6a7-c24f-4e47-a698-52e469651f4a)

> If you're changing something - say, moving from `sAMAccountName` to `userPrincipalName`, for instance - it's best to change it directly in the database, then run an LDAP sync.

We are not trying to change parametar `sAMAccountName` to `userPrincipalName`, instead we changed the value of `sAMAccountName` parameter. E.g. original.username -> new.username (in MS AD).

Here, I've done just that for testing. I've created new user named **Test user** with username **original.username** and successfully synced with Snipe-IT:
![image](https://github.com/snipe/snipe-it/assets/96291111/ca2caf6c-21f4-41fd-88b9-3d783c27699d)

Next, I've changed value of **sAMAccountName** parameter to **new.username** and again run synchronization in Snipe-IT. Final result is that now we have two users with different usernames **in Snipe-IT**:
![image](https://github.com/snipe/snipe-it/assets/96291111/1d031827-dd8b-4967-ad06-db5cf93b75ca)

And here's the **NEW** user:
![image](https://github.com/snipe/snipe-it/assets/96291111/0741c92f-445d-4fcb-a34b-6e73df74233d)

I hope that it is now more clear what our issue is. If this is intended functionality, I appologize.

**Comment by uberbrady** [comment]
I mean "intended functionality" isn't what I would say - your use-case is real, and it makes sense. I would want things to work the exact way that you want them to work. What you're asking for isn't terrible or anything, it makes sense.

It's just (near-) impossible to implement via the LDAP protocol. You need to have an 'invariant' to be able to say user 'abc' is now user 'xyz' - and not all LDAP providers have that. (Active Directory *does* if memory serves, but other providers may not, or if they do, the parameter they use as the 'invariant' is going to be completely different from what AD does).

**Comment by MaksaUniver** [comment]
All I wanted to know was, is it a bug or expected behavior. Generally, we deal with these issues by merging two users, but it would be nice if we wouldn't need to.

At least, give us option to change Snipe-IT username from within GUI, if that's possible.

**Comment by uberbrady** [comment]
You can do a bulk edit on users to mark them as 'not managed by LDAP' which will allow you to change their usernames. It's a fair request to ask to be able to edit usernames, even if they are LDAP-managed - I'll think about that one.
