### ISSUE TITLE
Typo in API docs

### ISSUE THREAD

**Issue by pieterhouwen** [grokability/snipe-it#13902]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In the documentation for the /categories api the "category name" value is wrongly labeled "Model name"

![image](https://github.com/snipe/snipe-it/assets/10866686/dadd9cf0-04fa-4d85-b52a-c7102450f9f3)

### Reproduction steps

https://snipe-it.readme.io/reference/categories-2

### Expected behavior

https://snipe-it.readme.io/reference/categories-2

### Snipe-IT Version

NA

### Operating System

NA

### Web Server

NA

### PHP Version

NA

**Comment by snipe** [comment]
Fixed, thanks :)
