### ISSUE TITLE
Docker - No 1D barcode shown with new label "Tapes\Dymo\LabelWriter_30252"

### ISSUE THREAD

**Issue by coach1988** [grokability/snipe-it#13906]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The 1D barcode is not shown for the label template "Tapes\Dymo\LabelWriter_30252" in our setup, even though it does work with e.g. the "DefaultLabel" (old engine) and "Tapes\Brother\TZe_12mm_A".

I did try to clear the label cache, the "php artisan config clear" (probably unrelated) and different combinations of settings regarding this (different defaults, different code types, shorter/different content for the field, etc.), all with the same result; The "laravel.log" does not indicate any issues.

I don't want to rule out that this might be a permission issue (I've chown'd the docker volumes, just in case), but as other codes are working as expected as far as I can tell, I don't think it is.

It does feel like this one https://github.com/snipe/snipe-it/issues/13768 , especially as I had different outcomes with the labels depending on whether company logos were set/accessible or not.

PS: There were also references to a missing "/var/lib/snipeit/data/uploads/companies/company-image-test.png", which I've overcome by copying the existing company picture next to it with that target name, stacktrace for **this** behavior is attached, as it got logged.
[company-image-test.txt](https://github.com/snipe/snipe-it/files/13419928/company-image-test.txt)

### Reproduction steps

Docker stack info:

`
version: "3"

services:
  app:
    container_name: snipe-it-app  
    image: snipe/snipe-it:v6-latest
    environment:
      - MYSQL_ROOT_PASSWORD=<PWD>
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=<PWD>
      - MYSQL_PORT_3306_TCP_ADDR=db
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MAIL_PORT=25
      - MAIL_HOST=srv-usaa-mta01.<DOMAIN>
      - MAIL_DRIVER=smtp
      - MAIL_AUTO_EMBED=True
      - MAIL_AUTO_EMBED_METHOD=base64
      - MAIL_ENV_ENCRYPTION=null      
      - MAIL_ENV_FROM_ADDR=noreply@<DOMAIN>
      - MAIL_ENV_FROM_NAME='<COMPANY> Asset Management'
      - MAIL_REPLYTO_ADDR=it-support@<DOMAIN>
      - MAIL_REPLYTO_NAME='the IT Support'
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_KEY=base64:<KEY>
      - APP_URL=https://assets.<DOMAIN>
      - APP_TIMEZONE=US/Eastern
      - APP_LOCALE=en
      - APP_FORCE_TLS=true
      - APP_ALLOW_INSECURE_HOSTS=true
      - PHP_UPLOAD_LIMIT=100
      - TRUSTED_PROXIES=10.16.16.3
      - ALLOW_DATA_PURGE=true
    volumes:
      - /app/docker-volumes/snipe-it/app/config:/config
      - /app/docker-volumes/snipe-it/app/snipeit:/var/lib/snipeit
      - /app/docker-volumes/snipe-it/app/logs:/var/www/html/storage/logs
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app
      - db
    ports:
      - 8082:80

  db:
    container_name: snipe-it-db 
    image: mysql/mysql-server:5.6
    environment:  
      - MYSQL_ROOT_PASSWORD=<PWD>
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=<PWD>
    volumes:
      - /app/docker-volumes/snipe-it/db/mysql:/var/lib/mysql
    networks:
      - db

networks:
  app:
  db:

`

The container is running behind a haProxy for SSL termination.

### Expected behavior

The barcode is shown on the bottom of the label.

### Screenshots

EDIT: For some reason the upload of the pictures doesn't want to work:-/ But the area where the barcode should be is just blank

EDIT2: Okay, worked around it, just remove the suffix, those are PNG's
[label ok.png.txt](https://github.com/snipe/snipe-it/files/13420054/label.ok.png.txt)
[label not ok.png.txt](https://github.com/snipe/snipe-it/files/13420060/label.not.ok.png.txt)

### Snipe-IT Version

v6.2.1 build 11625 (gc45ede2d1)

### Operating System

Official docker image

### Web Server

-

### PHP Version

8.1.2-1ubuntu2.14

### Operating System

Windows

### Browser

Firefox + Edge

### Version

121.0a1

### Device

Untested

### Operating System

-

### Browser

-

### Version

-

### Error messages

```shell
None
```

### Additional context

-

**Comment by snipe** [comment]
Fixed in https://github.com/snipe/snipe-it/pull/14056
