### ISSUE TITLE
[Feature Request]: upgrade the primary key to UUID

### ISSUE THREAD

**Issue by fzhan** [grokability/snipe-it#13919]
### Is your feature request related to a problem? Please describe.

We are trying to integrate multiple systems into one data hub, one of the key features is every record (of asset) is UUIDed, would be great for snipeit to adopt the uuid feature. This way it can easily be the single point do truth.

### Describe the solution you'd like

A few updates to the model and migration will sustain such changes.

**Comment by uberbrady** [comment]
That's a bit of a big lift for us to do - but I think you might be able to achieve much of what you want by using UUID's as your asset tags - we have plenty of affordances for accessing assets via asset tag, and those are basically unconstrained strings. Would that serve for your use case?

**Comment by fzhan** [comment]
> That's a bit of a big lift for us to do - but I think you might be able to achieve much of what you want by using UUID's as your asset tags - we have plenty of affordances for accessing assets via asset tag, and those are basically unconstrained strings. Would that serve for your use case?

Thanks for your reply.

I’ve done some research and decided to fork the repository, will make changes from there to sustain our case.

thanks again, for the wonderful product.
