### ISSUE TITLE
Installation script breaks the app when using whitespaces

### ISSUE THREAD

**Issue by VewDev** [grokability/snipe-it#13917]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If you add a whitespace to a field while running the install.sh script, the app starts with a blank page.

When using the install.sh script to deploy the application, you are prompted to input some information that will be saved to the .env file.

The problem comes when you add a whitespace in your input, since it will be directly saved into the .env file, and won't be able to read afterwards.

Happened to me in the email settings, when trying to set "CompanyName SnipeIT" as the mailer name.

Could theoretically happen with the password as well, but users are much less likely to have a whitespace in their password.

I was able to troubleshoot somewhat easily since the error was clearly described in the apache php logs.

### Reproduction steps

1. Download and execute the install.sh bash script
2. When prompted for the mailer name, input "CompanyName SnipeIT" (no ")
3. Try to run the application setup page

### Expected behavior

Properly save the input to the env file.

### Snipe-IT Version

v6.2.3 - latest at the moment

### Operating System

Ubuntu 22.01

### Web Server

Apache

### PHP Version

8

**Comment by snipe** [comment]
Closing this, as I explained the situation in the other issue.
