### ISSUE TITLE
[Feature Request]: Health Status API Endpoint Documentation

### ISSUE THREAD

**Issue by Redtigercod4** [grokability/snipe-it#13921]
### Is your feature request related to a problem? Please describe.

I have been configuring SnipeIT to be utilised in the cloud and as part of that we required an endpoint to perform a health check on. 

I did managed to find one that was implemented in an old Pull Request after digging through this Github Repository  but having it documented within the API Documentation should make it easier for any other people experiencing the same issue I did.

### Describe the solution you'd like

I am more than happy to update the API Reference documentation for it but I am unable to find it within this repository. 

Could I get a pointer to location of the appropriate file? If this is not possible, could I get the endpoint ``` /health ``` added with included response schema.
```
{
  "status" : "$ExampleValue"
}
```

**Comment by snipe** [comment]
The health check was resolved in https://github.com/snipe/snipe-it/pull/8978. 

It wouldn't be in the API docs, since everything within the API docs requires a bearer token, while the health check specifically does not. The health check endpoint doesn't come up often at all - literally this issue is the second time in 10 years it's been mentioned, but I can certainly add it to the docs.

**Comment by snipe** [comment]
Added to the docs. https://snipe-it.readme.io/docs/health-check-url

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/health-check-url">Health Check URL</a></strong></div><div>If you need to use an endpoint for health check monitoring, you can use https://your-snipe-it/health. This endpoint does not store sessions and does not hit the database.You can see more about how this works here: https://github.com/snipe/snipe-it/pull/8978</div></blockquote>

**Comment by Redtigercod4** [comment]
@snipe Thank you!
