### ISSUE TITLE
[Feature Request]: Allow Admins to change users groups

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13920]
### Is your feature request related to a problem? Please describe.

Currently you need to be a Super Admin to change a users group

### Describe the solution you'd like

Allow admin's to change a users group

**Comment by snipe** [comment]
The issue here is that it opens the door to privilege escalation. If I'm an admin, I can escalate my own (or another) to superuser, even though my admin account was specifically not given superadmin permissions.

**Comment by jayavman** [comment]
@snipe Can't you give access to admins to only approve lower tiers?
Meaning they only have approval for things lower than the tier they have?
