### ISSUE TITLE
Skiping Pre-Flight setup in web page[Feature Request]: 

### ISSUE THREAD

**Issue by davidmkrtchian** [grokability/snipe-it#13939]
### Is your feature request related to a problem? Please describe.

Is it possible to skip the pre-flight setup after configuring Snipe-IT?

### Describe the solution you'd like

 I don't want to perform the setup manually on the web page. 
 That's why I'm asking if there's a way to create the database table and the admin user using environment variables in config files

**Comment by snipe** [comment]
You'd need to manually create an admin and a settings record in the database. There's no other way to skip past it.

**Comment by StarlessNights** [comment]
It would also help out when spinning up transient snipe-it containers for testing integrations. I.e. I would just like to have a fresh API ready to accept requests with some preshared user.

Restoring an SQL dump is an adequate workaround though. There doesn't appear to be such SQL files laying around the repository, so I guess I'll just export my own.
