### ISSUE TITLE
Snipe-IT behind Nginx Proxy Manager not working

### ISSUE THREAD

**Issue by PrieserMax** [grokability/snipe-it#13951]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I set up Snipe-IT via Docker-Compose.
Changed the APP_URL to my domain (https://sipeit.domain.tld)
I get the error I mentioned below
I don't know how to pass it correctly
If I enable debug and proceed I get the following error:
![error3](https://github.com/snipe/snipe-it/assets/96659068/fa1fb2ab-41a9-41ee-b545-5eeec9e255bc)
If I disable debug mode I get a "server | 500 error"

### Reproduction steps

1. Install Snipe-IT in docker-compose
2. Add it to Nginx Proxy Manager with custom config (proxy_set_header X-Forwarded-Proto $scheme;)
3.
...

### Expected behavior

Working flawlessly to set up

### Snipe-IT Version

Latest

### Operating System

Ubuntu Server

### Web Server

Docker Image

### PHP Version

Docker Image

### Operating System

Windows 11

### Browser

Firefox

### Error messages

```shell
URL
Uh oh! Snipe-IT thinks your URL is https://snipeit.domain.tld/setup, but your real URL is https://snipeit.domain.tld:80/setup Please update your APP_URL settings in your .env file
```

### Additional context
![Error](https://github.com/snipe/snipe-it/assets/96659068/d7e8cf4d-4282-4aa9-81fd-338db93551cc)

_No response_

**Comment by snipe** [comment]
I don't think those two problems are related - it looks like a migration failed somewhere along the line. Can you show me the contents of your `migrations` table?

**Comment by PrieserMax** [comment]
That is the content of my migrations table:
MariaDB [snipeit]> Select * from migrations;
+----+-------------------------------------------------------------------------+-------+
| id | migration                                                               | batch |
+----+-------------------------------------------------------------------------+-------+
|  1 | 2012_12_06_225921_migration_cartalyst_sentry_install_users              |     1 |
|  2 | 2012_12_06_225929_migration_cartalyst_sentry_install_groups             |     1 |
|  3 | 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot |     1 |
|  4 | 2012_12_06_225988_migration_cartalyst_sentry_install_throttle           |     1 |
|  5 | 2013_03_23_193214_update_users_table                                    |     1 |
|  6 | 2013_11_13_075318_create_models_table                                   |     1 |
|  7 | 2013_11_13_075335_create_categories_table                               |     1 |
|  8 | 2013_11_13_075347_create_manufacturers_table                            |     1 |
|  9 | 2013_11_15_015858_add_user_id_to_categories                             |     1 |
| 10 | 2013_11_15_112701_add_user_id_to_manufacturers                          |     1 |
| 11 | 2013_11_15_190327_create_assets_table                                   |     1 |
| 12 | 2013_11_15_190357_create_temp_licenses_table                            |     1 |
| 13 | 2013_11_15_201848_add_license_name_to_licenses                          |     1 |
| 14 | 2013_11_16_040323_create_depreciations_table                            |     1 |
| 15 | 2013_11_16_042851_add_depreciation_id_to_models                         |     1 |
| 16 | 2013_11_16_084923_add_user_id_to_models                                 |     1 |
| 17 | 2013_11_16_103258_create_locations_table                                |     1 |
| 18 | 2013_11_16_103336_add_location_id_to_assets                             |     1 |
| 19 | 2013_11_16_103407_add_checkedout_to_to_assets                           |     1 |
| 20 | 2013_11_16_103425_create_history_table                                  |     1 |
| 21 | 2013_11_17_054359_drop_licenses_table                                   |     1 |
| 22 | 2013_11_17_054526_add_physical_to_assets                                |     1 |
| 23 | 2013_11_17_055126_create_settings_table                                 |     1 |
| 24 | 2013_11_17_062634_add_license_to_assets                                 |     1 |
| 25 | 2013_11_18_134332_add_contacts_to_users                                 |     1 |
| 26 | 2013_11_18_142847_add_info_to_locations                                 |     1 |
| 27 | 2013_11_18_152942_remove_location_id_from_asset                         |     1 |
| 28 | 2013_11_18_164423_set_nullvalues_for_user                               |     1 |
| 29 | 2013_11_19_013337_create_asset_logs_table                               |     1 |
| 30 | 2013_11_19_061409_edit_added_on_asset_logs_table                        |     1 |
| 31 | 2013_11_19_062250_edit_location_id_asset_logs_table                     |     1 |
| 32 | 2013_11_20_055822_add_soft_delete_on_assets                             |     1 |
| 33 | 2013_11_20_121404_add_soft_delete_on_locations                          |     1 |
| 34 | 2013_11_20_123137_add_soft_delete_on_manufacturers                      |     1 |
| 35 | 2013_11_20_123725_add_soft_delete_on_categories                         |     1 |
| 36 | 2013_11_20_130248_create_status_labels                                  |     1 |
| 37 | 2013_11_20_130830_add_status_id_on_assets_table                         |     1 |
| 38 | 2013_11_20_131544_add_status_type_on_status_labels                      |     1 |
| 39 | 2013_11_20_134103_add_archived_to_assets                                |     1 |
| 40 | 2013_11_21_002321_add_uploads_table                                     |     1 |
| 41 | 2013_11_21_024531_remove_deployable_boolean_from_status_labels          |     1 |
| 42 | 2013_11_22_075308_add_option_label_to_settings_table                    |     1 |
| 43 | 2013_11_22_213400_edits_to_settings_table                               |     1 |
| 44 | 2013_11_25_013244_recreate_licenses_table                               |     1 |
| 45 | 2013_11_25_031458_create_license_seats_table                            |     1 |
| 46 | 2013_11_25_032022_add_type_to_actionlog_table                           |     1 |
| 47 | 2013_11_25_033008_delete_bad_licenses_table                             |     1 |
| 48 | 2013_11_25_033131_create_new_licenses_table                             |     1 |
| 49 | 2013_11_25_033534_add_licensed_to_licenses_table                        |     1 |
| 50 | 2013_11_25_101308_add_warrantee_to_assets_table                         |     1 |
| 51 | 2013_11_25_104343_alter_warranty_column_on_assets                       |     1 |
| 52 | 2013_11_25_150450_drop_parent_from_categories                           |     1 |
| 53 | 2013_11_25_151920_add_depreciate_to_assets                              |     1 |
| 54 | 2013_11_25_152903_add_depreciate_to_licenses_table                      |     1 |
| 55 | 2013_11_26_211820_drop_license_from_assets_table                        |     1 |
| 56 | 2013_11_27_062510_add_note_to_asset_logs_table                          |     1 |
| 57 | 2013_12_01_113426_add_filename_to_asset_log                             |     1 |
| 58 | 2013_12_06_094618_add_nullable_to_licenses_table                        |     1 |
| 59 | 2013_12_10_084038_add_eol_on_models_table                               |     1 |
| 60 | 2013_12_12_055218_add_manager_to_users_table                            |     1 |
| 61 | 2014_01_28_031200_add_qr_code_to_settings_table                         |     1 |
| 62 | 2014_02_13_183016_add_qr_text_to_settings_table                         |     1 |
| 63 | 2014_05_24_093839_alter_default_license_depreciation_id                 |     1 |
| 64 | 2014_05_27_231658_alter_default_values_licenses                         |     1 |
| 65 | 2014_06_19_191508_add_asset_name_to_settings                            |     1 |
| 66 | 2014_06_20_004847_make_asset_log_checkedout_to_nullable                 |     1 |
| 67 | 2014_06_20_005050_make_asset_log_purchasedate_to_nullable               |     1 |
| 68 | 2014_06_24_003011_add_suppliers                                         |     1 |
| 69 | 2014_06_24_010742_add_supplier_id_to_asset                              |     1 |
| 70 | 2014_06_24_012839_add_zip_to_supplier                                   |     1 |
| 71 | 2014_06_24_033908_add_url_to_supplier                                   |     1 |
| 72 | 2014_07_08_054116_add_employee_id_to_users                              |     1 |
| 73 | 2014_07_09_134316_add_requestable_to_assets                             |     1 |
| 74 | 2014_07_17_085822_add_asset_to_software                                 |     1 |
| 75 | 2014_07_17_161625_make_asset_id_in_logs_nullable                        |     1 |
| 76 | 2014_08_12_053504_alpha_0_4_2_release                                   |     1 |
| 77 | 2014_08_17_083523_make_location_id_nullable                             |     1 |
| 78 | 2014_10_16_200626_add_rtd_location_to_assets                            |     1 |
| 79 | 2014_10_24_000417_alter_supplier_state_to_32                            |     1 |
| 80 | 2014_10_24_015641_add_display_checkout_date                             |     1 |
| 81 | 2014_10_28_222654_add_avatar_field_to_users_table                       |     1 |
| 82 | 2014_10_29_045924_add_image_field_to_models_table                       |     1 |
| 83 | 2014_11_01_214955_add_eol_display_to_settings                           |     1 |
| 84 | 2014_11_04_231416_update_group_field_for_reporting                      |     1 |
| 85 | 2014_11_05_212408_add_fields_to_licenses                                |     1 |
| 86 | 2014_11_07_021042_add_image_to_supplier                                 |     1 |
| 87 | 2014_11_20_203007_add_username_to_user                                  |     1 |
| 88 | 2014_11_20_223947_add_auto_to_settings                                  |     1 |
| 89 | 2014_11_20_224421_add_prefix_to_settings                                |     1 |
| 90 | 2014_11_21_104401_change_licence_type                                   |     1 |
| 91 | 2014_12_09_082500_add_fields_maintained_term_to_licenses                |     1 |
| 92 | 2015_02_04_155757_increase_user_field_lengths                           |     1 |
| 93 | 2015_02_07_013537_add_soft_deleted_to_log                               |     1 |
| 94 | 2015_02_10_040958_fix_bad_assigned_to_ids                               |     1 |
| 95 | 2015_02_10_053310_migrate_data_to_new_statuses                          |     1 |
| 96 | 2015_02_11_044104_migrate_make_license_assigned_null                    |     1 |
| 97 | 2015_02_11_104406_migrate_create_requests_table                         |     1 |
+----+-------------------------------------------------------------------------+-------+

**Comment by snipe** [comment]
Try running:

```
insert into migrations (migration, batch) values ('2015_02_12_001312_add_mac_address_to_asset', 2);
```

and then run migrations again.

**Comment by PrieserMax** [comment]
Thank you very much, It is working now!

Do I have to mind that error with the reverse proxy? I found in some other issues, that this might cause a problem with loading assets.

Greetings from Germany
Max
