### ISSUE TITLE
[Feature Request]: Automatically delete people

### ISSUE THREAD

**Issue by soren33322** [grokability/snipe-it#13969]
### Is your feature request related to a problem? Please describe.

No issues, only an idea for a new feature.

### Describe the solution you'd like

I would like to have users with an End Date being automatically deleted from the peoples section and moved to the deleted users section.

### Describe alternatives you've considered

No alternatives.

**Comment by snipe** [comment]
That's not really feasible, since once they are terminated (their contract ends, etc) we don't know what happens to the things they were assigned. Human intervention still has to happen to deal with the assets they had checked out to them, and that workflow will vary by organization.
