### ISSUE TITLE
Asset Import fails after 600 seconds

### ISSUE THREAD

**Issue by SageDearborn** [grokability/snipe-it#13962]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Attempting to run 
`php artisan snipeit:import /tmp/devices.csv`

results in a timeout after 600 seconds . This means the importer chokes on very large imports. In this case it errored out after import 38977 items.

### Reproduction steps

1. Generate a csv with LOT of assets to import, >40,000
2. Navigate to /var/www/snipe-it (or the snipe-it install directory
3. run `php artisan snipeit:import /tmp/devices.csv`
4. Wait 10 minutes
5. Error message

### Expected behavior

The database connection should stay open long enough for the import to complete.

### Snipe-IT Version

v6.2.3 - build 11936 (master

### Operating System

Ubuntu 22.04 LTS

### Web Server

Apache

### PHP Version

8.1

### Error messages

```shell
php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Stacktrace is below:**

user@host:/var/www/snipe-it$ php artisan snipeit:import /tmp/devices.csv 
======= Importing Items from /tmp/devices.csv =========
 38977/87487 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  44%PHP Fatal error:  Maximum execution time of 600 seconds exceeded in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 375

   UnexpectedValueException 

  The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: Symfony\Component\ErrorHandler\Error\FatalError: Maximum execution time of 600 seconds exceeded in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:375
Stack trace:
#0 {main}

  at vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142▕             restore_error_handler();
    143▕             if (!is_resource($stream)) {
    144▕                 $this->stream = null;
    145▕ 
  ➜ 146▕                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url) . Utils::getRecordMessageForException($record));
    147▕             }
    148▕             stream_set_chunk_size($stream, $this->streamChunkSize);
    149▕             $this->stream = $stream;
    150▕         }

      +7 vendor frames 
  8   app/Exceptions/Handler.php:48
      Illuminate\Support\Facades\Facade::__callStatic()

      +3 vendor frames 
  12  [internal]:0
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleShutdown()

   Whoops\Exception\ErrorException 

  Maximum execution time of 600 seconds exceeded

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:375
    371▕             $this->bindValues($statement, $this->prepareBindings($bindings));
    372▕ 
    373▕             $statement->execute();
    374▕ 
  ➜ 375▕             return $statement->fetchAll();
    376▕         });
    377▕     }
    378▕ 
    379▕     /**

      +1 vendor frames 
  2   [internal]:0
      Whoops\Run::handleShutdown()
```

### Additional context

Is this a fresh install or an upgrade? **Yes, brand new install**
What method you used to install Snipe-IT?  **manual install**
Include what you've done so far in the installation, and if you got any error messages along the way. **Functional install, no issues until now. Imported a bunch of pre-requisites for the device import, such as locations, models, manufacturers, etc, all of which had no issues.**
Indicate whether or not you've manually edited any data directly in the database. **No**

Add any other context about the problem here: **Workaround exists, break import into smaller chunks.**

**Comment by jayavman** [comment]
2 options.

1. Extend your Apache Timeout Settings
2. Break up your importing. Less assets per csv.

**Comment by snipe** [comment]
You can increase your `max_execution_time` in your php.ini to increase the amount of time a process can run. Or, as @jayavman said, you can break your import into smaller files.
