### ISSUE TITLE
LDAP Sync Failing via Command Line: Undefined variable $search_base

### ISSUE THREAD

**Issue by eduder** [grokability/snipe-it#13961]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Recently did a fresh install of Snipe-IT on an Ubuntu 22.04 host, and imported the backup data from my previous install which had been running in Docker. We are syncing with LDAP against AD. The web interface tests show the connection is fine and valid users are displayed in the test preview. I can manually import new users from AD if I trigger the LDAP sync via the web interface, however the command line LDAP sync trigger has no output, even with --summary. With `php artisan snipeit:ldap-sync --json_summary` I get the following output: `php artisan snipeit:ldap-sync --json_summary
{"error":true,"error_message":"Undefined variable $search_base","summary":[]}`

### Reproduction steps

1. Via command line in the Snipe-IT project directory, run `php artisan snipeit:ldap-sync`
2. Observe no output. Check the user list and see that no changes have been made.
3.
...

### Expected behavior

Upon running `php artisan snipeit:ldap-sync`, an LDAP sync should happen against AD and bring in users/changes.

### Snipe-IT Version

v6.2.3 build 11936 (gb47e734b3)

### Operating System

Ubuntu 22.04.3

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.14

### Operating System

macOS

### Browser

Chrome

### Version

119

### Additional context

Installation was a manual install. We were previously running under Docker.

**Comment by snipe** [comment]
Please check the error logs and give us a complete stack trace

**Comment by eduder** [comment]
The laravel.log has nothing new since 11-14 which were from when I was setting it up and didn't have permissions configured properly. There's nothing new in the log since then. I have debug mode turned on and did the artisan clear command per https://snipe-it.readme.io/docs/getting-help however I am not sure what steps to do next to get a stack trace. Nothing new shows up in laravel.log after running the ldap-sync command with debug enabled.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by Erica-Lachowitz** [comment]
@eduder This is a quick/dirty fix to get you caught up until an official fix is in place (just be sure to pass the --base_dn via your cli script).

Open: \app\Console\Commands\LdapSync.php
Goto: line 86
Add: $search_base = $this->option('base_dn');

![image](https://github.com/snipe/snipe-it/assets/76656758/1eaf7e33-4bb3-4ba3-a25b-b9bb89828b54)

**Comment by Erica-Lachowitz** [comment]
@eduder This is a quick/dirty fix to get you caught up until an official fix is in place (just be sure to pass the --base_dn via your cli script).

Open: \app\Console\Commands\LdapSync.php
Goto: line 86
Add: $search_base = $this->option('base_dn');

![image](https://github.com/snipe/snipe-it/assets/76656758/ab1b1c96-1137-4a5f-922e-2a02799d1142)

**Comment by eduder** [comment]
Thank you @Erica-Lachowitz , this workaround has resolved the issue for us

**Comment by Erica-Lachowitz** [comment]
Almost there... (just 2 more small things)

1. Looks like there's a typo on line 69 (it just needs the underscore removed from ldap_base_dn)

2. **$this->option('base_dn')** never gets called when nested inside the elseif statement when location_id is undefined in the command. In the meantime, I broke out the nested statement so the parameter supplied base_dn can be applied to the class.

@eduder Stay with your modified revision, unless you have applied the latest merge to your codebase. If you have already applied the update, follow the below steps until fixed:

![image](https://github.com/snipe/snipe-it/assets/76656758/680affd7-97ae-40b9-98bf-15663f16c108)

**Comment by fug4zi** [comment]
Working Version can be found here:

https://github.com/snipe/snipe-it/blob/master/app/Console/Commands/LdapSync.php

Thanks @Erica-Lachowitz had the same issue today.

**Comment by snipe** [comment]
Thanks for the feedback. Next time, a PR would have been a bit more useful, I think.

**Comment by snipe** [comment]
@fug4zi AFAIK, this was already fixed. Upgrade to master and let me know how you make out.
