### ISSUE TITLE
Wrong attribute in table licenses / Serial instead of Product Key

### ISSUE THREAD

**Issue by MindofCode** [grokability/snipe-it#13977]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When selecting a users licenses, the table does show "Serial" instead of "Product Key" in the header.
Nevertheless the shown info is the correct "Product Key".
The Column Selector under licenses also shows "Serial" instead of "Product Key"

Can me seen in  Version v6.2.3 - build 11759 (master)
and Version v6.2.4-pre - build 12090 (master)

### Reproduction steps

1.Select a user
2.Select "Licenses"
3.Header shows "Serial" with correct "Product Key" information
...

### Expected behavior

Should read "Product Key" and "Product Key" should be present in column selector

### Snipe-IT Version

Version v6.2.3 - build 11759 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4

### Operating System

Ubuntu

### Browser

Firefox

### Version

120

**Comment by Godmartinz** [comment]
This is on the Main/Master branch now.
