### ISSUE TITLE
unable to checkout asset if target user is in different company

### ISSUE THREAD

**Issue by deeitdee** [grokability/snipe-it#13984]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We have created the asset in example ABCD company and we create the user in EFGH company. but now are unable to checkout asset to the user. we are facing below error. 
Error Checkout target company and asset company do not match 

### Reproduction steps

1.  can we checkout asset of any target user. doesn't matter of company or location of the asset and target. 
2.
3.
...

### Expected behavior

We have created the asset in example ABCD company and we create the user in EFGH company. but now are unable to checkout asset to the user. we are facing below error. 
Error Checkout target company and asset company do not match 

### Snipe-IT Version

 Version v6.2.3 - build 11759 (master)

### Operating System

Windows

### Web Server

IIS

### PHP Version

11759

### Operating System

Windows

### Browser

Google Chrome

### Operating System

Win 11 Pro

**Comment by Godmartinz** [comment]
This is intended behavior if you have Full Multiple Companies Support selected.

<img width="700" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/e194e6ec-ed15-42c4-a99a-f7df027c7b50">

It can be disabled in **General Settings** if this is not how you intend to manage your assets. I hope this helps.

**Comment by deeitdee** [comment]
> This is intended behavior if you have Full Multiple Companies Support selected.
> <img alt="image" width="700" src="https://private-user-images.githubusercontent.com/47435081/287798018-e194e6ec-ed15-42c4-a99a-f7df027c7b50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTE0MzcsIm5iZiI6MTcwMTc1MTEzNywicGF0aCI6Ii80NzQzNTA4MS8yODc3OTgwMTgtZTE5NGU2ZWMtZWQxNS00MmM0LWE5OWEtZjdkZjAyN2M3YjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA0Mzg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNWQ0MWIxNWRjNTM0NmEyYWRmODA3NTJkNDE2YzgzOTU0MDE0NjM0ZmI1YmFiYjRhOGZhYmQ1ODA5MzQ5MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6rCXAMz6cezGUi6ueVjbLnfgxOe70nfXO1b3TF7s2y8">
> 
> It can be disabled in **General Settings** if this is not how you intend to manage your assets. I hope this helps.

yes, it's done. thanks for your support.
