### ISSUE TITLE
ARM64 Images for 6.2.2/6.2.3/latest not available on Dockerhub

### ISSUE THREAD

**Issue by eifelmicha** [grokability/snipe-it#13988]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

On https://hub.docker.com/r/snipe/snipe-it/tags i can't find the arm64 images for the both latest versions. Browsing the Tag in Github this lead me to an failing CI Job: https://github.com/snipe/snipe-it/actions/runs/6538311044/job/17753964820

### Reproduction steps

`docker pull snipe/snipe-it:v6.2.3` on an Hetzner CAX instance

### Expected behavior

`docker pull snipe/snipe-it:v6.2.3` succeeds

### Snipe-IT Version

6.2.2

### Operating System

Docker

### Web Server

Docker

### PHP Version

Docker

**Comment by snipe** [comment]
@uberbrady can you look into this please?

**Comment by snipe** [comment]
This should be fixed for future builds.
