### ISSUE TITLE
[Feature Request]: Model for accessories

### ISSUE THREAD

**Issue by qay21** [grokability/snipe-it#14009]
### Is your feature request related to a problem? Please describe.

Nowadays, entries  in the "accessories" tab are somewhat confused. They does not really represent a type of object, but does not really represent a given stack of a specific type of object either. To be clear :
* A "type of object" is the idea of an object, the representation of its characteristics, eg "Logitech M705 Marathon" is a concept, a type of mouse.
* A "stack of objects" is a specific amount of objects of a given type, bought sometime ago and stored somewhere, eg "the handful of M705 stored in the entrance closet" is a stack.

Right now, when browsing existing accessories fields, we can see the inconsistency in what accessories are supposed to represent :

* Company : applies to a stack
* Name : applies either to a type or a stack
* Category : applies to a type
* Provider : applies to a stack (you could purchase the same object from various stores)
* Manufacturer : applies to a type
* Location : applies to a stack (you could have the same type of object stored in two different offices)
* Model n° : applies to a type, this data is most likely provided by the manufacturer
* Order number : applies to a stack, or even to a sub-stack (you could pass a new order to replenish the M705 stock while still storing them in the entrance closet)
* Purchase date : applies to a stack, or even a sub-stack (see Order number)
* Purchase price : applies to a stack, or even a sub-stack (see Order number)
* Quantity : applies to a stack. Some of it is still in stock, some of it is already checked out to peoples
* Min quantity : applies to a stack
* Notes : applies either to a type or a stack
* Image : applies to a type

This confusion is somewhat annoying. Consider the following scenario : **We are running low on M705 in the entrance closet**

Several new hired workers are expected in January, and we do not have enough mouses for everyone. It's time to pass a new order. Since M705 are doing a great job and are still available online, we want to order the same model. In that case :
* Should we add the newly ordered amount to the existing stack ? This will make order number, purchase date and purchase cost inconsistent. Plus, the supplier might even not be the same.
* Let's instead create a new "stack" : order number, purchase date and cost and supplier are now consistent. However, we now have two different stacks of the same type in the same entrance closet, making min quantity a bit messy to set up. Plus, it forces us to duplicate accessory name, manufacturer, model no and image, with the associated risk of inconsistency.

### Describe the solution you'd like

Some improvements could be made :

**Accessory model**
Firstly, an "accessory model" (similar to asset model, albeit simpler) could be used to ensure model's data are consistent over multiple stacks of object : accessory name, category, manufacturer, model number, image and maybe some notes are not expected to change.

**Order vs stack**
Secondly, it might be a good idea (but probably more complex) to differentiate the "order" concept from the "stack" concept, such as follow :
* A stack is just a certain amount of a certain model, stored in a certain place (and it might have a minimum quantity defined, helping us remind that we need to have some readily available). Inside of this pile, objects of various ages can coexist : the older ones are probably already checked out, the newer ones are probably still available. And maybe, one or two old ones are back in the pile due to their user having retired lately. Being able to distinguish new and old objects of the same type in the same pile is not relevant : if it is of any use to us, we should probably use assets and collect/assign serial numbers and asset tags instead. A stack is therefore mainly an "operational" concern : we need to have *some* stuff available, and to know how much of it is left.
* An order is the adding of new objects of a given model to a specific stack. It has a supplier (which might not be the same as the last order of the same model), a purchase date and cost, a quantity, and maybe some kind of warranty information (this is probably too context-specific to be a new field, and can probably be hinted using the notes). An order is therefore mainly an "accounting" concern : we can track prices of given models/suppliers over time, link orders to an accounting software using the order number, etc

### Describe alternatives you've considered

In order to have the same level of details, the alternative with existing tools is to create a new accessory entry for each order of a given model. This makes the min quantity field pretty much useless, as it will always be 0, and it forces us to sum all available accessory entries for a given model and a given location using external means (eg. monitoring software using the API and some notification engine).

This is really error prone and confusing : as time is passing, a company like mine will end up having half a dozen of entries for the [M705/entrance closet] duo (and the same for all other accessories), making the interface quite messy.

### Additional context

As a note, I am using SnipeIT for around a year now, in order to manage hardware checkouts for a 250 workers software company on 4 different offices. The above feedback and suggestion are drawn from this experience. The "assets" feature of the tool is really unobtrusive and a pleasure to work with, while the "accessories" feature is still giving us a hard time.

To be honest, we even considered scrapping the feature entirely, and manage our accessories by creating SN-less assets instead. We ended up not doing this, and are still using accessories but with a single stack for each model. This gets us a cleaner interface, consistent quantity and min quantity. However, in the process, we obviously completely abandoned cost/order and location tracking. This is the best we come up with lately.

**Comment by snipe** [comment]
Thanks for your feedback. We've been discussing this internally for some time already and have been waiting for v7 to make big moves on it. 

In the meantime, if the accessories, etc categorization doesn't make sense, we suggest you use assets instead.

**Comment by qay21** [comment]
Good to know, thank your for your answer ! We'll carry on with simplified accessories for now, and will wait for some news around v7.
