### ISSUE TITLE
Snipe-IT Assist management ( Version update)

### ISSUE THREAD

**Issue by rkhnania** [grokability/snipe-it#14004]
### Is your feature request related to a problem? Please describe.

I'm running old version Snipe-IT | v4.6.6 build 3926 (g1a10aa0dd) i would like to update to the latest version 

### Describe the solution you'd like

By updating to the latest version and creating a test environment, you can ensure that your system is up-to-date and thoroughly tested. This will help you avoid any potential issues and improve your overall productivity. So, let's take the next step and upgrade your system today!

**Comment by snipe** [comment]
I'm not sure what the ask is here exactly? We have docs on upgrading. https://snipe-it.readme.io/docs/upgrading

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div>🚧If you run into any issues upgrading...Please check the Common Issues &gt; Installation/Upgrading Issues section which provides solutions for commonly encountered installation / upgrading problems.📘Note:When available, please use the more detailed upgrade instructions for specific versions, avail...</div></blockquote>
