### ISSUE TITLE
[Feature Request]: Checkout asset to multiple assets

### ISSUE THREAD

**Issue by pieterhouwen** [grokability/snipe-it#14035]
### Is your feature request related to a problem? Please describe.

I want to start using Snipe-IT for managing both soft-assets and hard-assets in multiple corporate environments. For this I would use a hierarchy of assets like so:

Server1 (hard-asset)
- Operating system: Ubuntu (soft-asset)
- - Ubuntu license: gpl - GNU General Public License (license)
- Webserver: Nginx (soft-asset)
- - Nginx license: 2-clause BSD license (license)
- Database server: PostgreSQL
- - PostgreSQL license: PostgreSQL License (license)

The issue that I would run into is that the soft-assets can only be checked out to a single other asset, which would mean that I would have to create an Ubuntu asset for each server that it's running on. 

### Describe the solution you'd like

The checkout to asset field should be multi-select instead of single select

### Describe alternatives you've considered

At the moment there are 2 things that I can imagine doing in the way that the system is currently designed:

### Solution 1:
Create the soft-assets all as licenses and assign those to the relevant hard-assets.

Problem 1:
Ubuntu itself isn't a license.

Problem 2:
For different software assets I want to have different custom fields which only work on asset models

### Solution 2:
Create seperate soft-assets as asset models

Problem 1:
You can't assign multiple asset models to an asset

**Comment by snipe** [comment]
> which would mean that I would have to create an Ubuntu asset for each server that it's running on

You would use licenses for software, and then check those license seats out to each asset

**Comment by pieterhouwen** [comment]
But can you link a license to a license?

**Comment by pieterhouwen** [comment]
@snipe How would you then f.e. note what license Nginx or any other open-source project is?
