### ISSUE TITLE
Consumables come up unknown

### ISSUE THREAD

**Issue by TotiTolvukall** [grokability/snipe-it#14032]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have registered a consumable - toner - 4 cartridges of a specific product number.

I made sure ONE cartridge is the trigger for "almost running out".

Snipeit shows this cartridge to be running out.

Still four left.

Clicking the cartridge in the notification brings up a page of "No matching records found"

That's a bit... awkward.

### Reproduction steps

1. register consumable with 4 left
2. have system tell you you're almost out of consumables (still 4 left !!! )
3. click consumable and have the system tell you "record not found"
... have a real fund WTF feeling.

### Expected behavior

No alert
But If alert, then bloody record found.
Man, don't lose records like that!

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/51100612/525ac83b-8175-4f3f-aa88-827ad66c757a)
![image](https://github.com/snipe/snipe-it/assets/51100612/d665a518-d373-4201-b605-9bf0350259fb)

### Snipe-IT Version

6.1.2 10938

### Operating System

Windows Server 2022

### Web Server

IIS

### PHP Version

not sure. 8 point something

### Operating System

Windows

### Browser

Edge

### Version

latest

**Comment by snipe** [comment]
```
No alert
But If alert, then bloody record found.
Man, don't lose records like that!
```

Records are  never lost, but you haven't answered the other questions we ask. "8 point something" is not a valid PHP version, you haven't given us any info on anything that might be in your browser's console or your app logs. Can you reproduce it on the demo? I'm unable to reproduce this locally or on the demo.

Does it happen with just that one consumable? What's the specific error message you're seeing from the system? Does it only happen when you click on it in the alert link in the header? Give us *something* to work with ffs.

If you're going to throw attitude, at least give us what we need to reluctantly help you. Also, you should really update. v6.1.x is old.

https://snipe-it.readme.io/docs/getting-help
https://snipe-it.readme.io/docs/advanced-debugging

**Comment by TotiTolvukall** [comment]
Sorry, bugreports should not be filed after midnight and after a couple of beers.

The PHP version is 8.2.9 and it happens with all the consumables I registered at the time (all my toner units)

I will update. Thanks, I'll close this for now.

**Comment by snipe** [comment]
It's all good - happens to the best of us. I will warn you tho that you may have some trouble with PHP 8.2, as we don't support it yet. (We will in v7, slated to come out in just a few weeks, but it's a bit difficult to release a major version when everyone's away on holiday.)

If you can give me errors or messages from the browser console or app logs, we can probably figure out what's happening though.
