### ISSUE TITLE
No recent alpine release images

### ISSUE THREAD

**Issue by sopidos** [grokability/snipe-it#14044]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Have been running the alpine based docker images, eg. [snipe/snipe-it:v6.2.0-alpine](https://hub.docker.com/layers/snipe/snipe-it/v6.2.0-alpine/images/sha256-e3c2c5672def50ac9140f50d7457e710b8829ae85f1af51a1e3a293187a64a52?context=explore) and [snipe/snipe-it:v6.2.1-alpine](https://hub.docker.com/layers/snipe/snipe-it/v6.2.1-alpine/images/sha256-62abd9ec6ca3f4f1be62e8b98e4a054503dc0ba406265419e62086d64eb0faac?context=explore), however the last couple of releases have had no alpine based images.
Opening this as a bug report as I have not seen any mentions of it going away in the release notes, and it looks like the builds [are failing](https://github.com/snipe/snipe-it/actions/runs/6538311044). 

But also, somewhat asking if alpine builds are less supported, and as such if I should be migrating to the "regular" image? Would migration to eg. `snipe/snipe-it:v6.2.3` be a drop-in replacement from a previous alpine image? or are any manual action required? I don't see anything in the [docs](https://snipe-it.readme.io/docs/docker) mentioned around this.

### Reproduction steps

Look for alpine release images

### Expected behavior

Alpine release images available

### Snipe-IT Version

6.2.3

### Operating System

linux

### Web Server

na - docker

### PHP Version

na - docker

**Comment by snipe** [comment]
This should be fixed now and future alpine builds should run successfully.
