### ISSUE TITLE
Asset becomes unrequestable after updating it via powershell

### ISSUE THREAD

**Issue by Kamala-Koala** [grokability/snipe-it#14054]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After updating an asset through PowerShell, it becomes 'unrequestable' and gives an error 500 when clicking it. Screenshots are below.

![image](https://github.com/snipe/snipe-it/assets/112828255/f571c220-18d0-4b32-9d5c-af9bea9944b0)
![image](https://github.com/snipe/snipe-it/assets/112828255/46db62e4-b9f0-4eee-b652-c77208d40ee3)
![image](https://github.com/snipe/snipe-it/assets/112828255/7d4fb5b5-a111-4a4e-8586-2ba8d798cb69)
![image](https://github.com/snipe/snipe-it/assets/112828255/417e6fcf-9a6d-456b-8857-266f75162d3f)

### Reproduction steps

1.Have asset that is able to be opened and checked out
2. run update on it through PS
3. asset cannot be clicked on or checked out or updated
4. clone asset in order to get a working version again
...

### Expected behavior

the asset will be able to update with the information given in the PS command. this does work most of the time but every now and again ill get an asset that breaks like this

### Snipe-IT Version

v6.2.3 - build 11936 (master)

### Operating System

Oracle Linux Server 9.2"

### Web Server

Apache

### PHP Version

 PHP 8.0.30 

### Operating System

Windows 11

### Browser

Edge

### Version

Version 120.0.2210.61 (Official build) 

### Error messages

```shell
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'assets.' in 'where clause' (SQL: select * from `assets` where `assets`.`` = 286 limit 1) (View: /var/www/snipe-it/resources/views/hardware/view.blade.php)
```

**Comment by snipe** [comment]
That generally happens when you haven't specified what type of entity the item is checked out to.  It's trying to do a join against a table (`users`, `locations`, `assets`, etc) but it doesn't know which one, since you didn't tell it.

**Comment by snipe** [comment]
https://snipe-it.readme.io/reference/hardware-checkout

Note that `checkout_to_type` is required.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/hardware-checkout">/hardware/:id/checkout</a></strong></div><div>Checkout an asset to a user, location or another asset</div></blockquote>

**Comment by snipe** [comment]
Can you share your Powershell code (with tokens, etc obfuscated)? The checkout method *should* prevent you from checking an asset out an asset without the `checkout_to_type` field.
