### ISSUE TITLE
Admin permission can't see all Asset

### ISSUE THREAD

**Issue by tiennv3011** [grokability/snipe-it#14065]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

My admin account cannot see the entire list of assets

### Reproduction steps

1.
2.
3.
...

### Expected behavior

The admin privilege allows access to view the entire list of current assets.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/142978084/16a5edd4-33f0-4ca5-a028-ca1415a304ef)

### Snipe-IT Version

v6.1.2

### Operating System

Windows server 2019

### Web Server

IIS

### PHP Version

8.0.29

**Comment by snipe** [comment]
I'd guess (but cannot tell from your screenshots) that you have full multiple company support turned on and those assets are in different companies. That or some of them are archived.

Also I don't know what's going on in your screenshots, but `General.assetss` as a translation string doesn't show up anywhere when I grep the code.

**Comment by tiennv3011** [comment]
> I'd guess (but cannot tell from your screenshots) that you have full multiple company support turned on and those assets are in different companies. That or some of them are archived.
> 
> Also I don't know what's going on in your screenshots, but `General.assetss` as a translation string doesn't show up anywhere when I grep the code.

Exactly, multiple company support turned off and admin user can see all asset, many thank for your support @snipe 
`General.assetss`  is custom translation of my language 👍

**Comment by snipe** [comment]
> General.assetss is custom translation of my language 

Looks like a typo tho? The string doesn't seem to be translated properly.
