### ISSUE TITLE
Add "License" to category types in API documentation

### ISSUE THREAD

**Issue by pieterhouwen** [grokability/snipe-it#14069]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The API reference docs state that a category can only have 4 types: asset, accessory, consumable, component
In the web interface however you can also choose "License" as category type.

![image](https://github.com/snipe/snipe-it/assets/10866686/15513e05-0e26-4fc0-90c1-58ec8c0df2bc)
![image](https://github.com/snipe/snipe-it/assets/10866686/1df680a5-a938-445c-b5d5-44f0562f838d)

### Reproduction steps

N/A

### Expected behavior

N/A

### Snipe-IT Version

Latest

### Operating System

any

### Web Server

any

### PHP Version

any

**Comment by snipe** [comment]
Updated, thanks!
