### ISSUE TITLE
fwrite()  return error "errno=22 Invalid argument"

### ISSUE THREAD

**Issue by jeffjoseph** [grokability/snipe-it#14071]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have tried generate and restore backup . But everytime I try to restore the backup file it Returns with this error. And before try to restore it is clearing the tables in the dataabase. I had checked the data base too

### Reproduction steps

1.Generate Backup
2.Restore Backup

### Expected behavior

Restoring the backup

### Snipe-IT Version

6.2.3

### Operating System

windows server 2012 standard

### Web Server

IIS 8

### PHP Version

PHP 7.4.3  nts

### Error messages

```shell
$sql_contents = $za->getStream($sql_stat['name']);

        if ($sql_contents === false) {

            $stdout = fgets($pipes[1]);

            $this->info($stdout);

            $stderr = fgets($pipes[2]);

            $this->info($stderr);

 

            return false;

        }

        $bytes_read = 0;

 

        try {

            while (($buffer = fgets($sql_contents, self::$buffer_size)) !== false) {

                $bytes_read += strlen($buffer);

                // \Log::debug("Buffer is: '$buffer'");

                    $bytes_written = fwrite($pipes[0], $buffer);

 

                if ($bytes_written === false) {

                    throw new Exception("Unable to write to pipe");

                }

            }

        } catch (\Exception $e) {

            \Log::error("Error during restore!!!! ".$e->getMessage());

            $err_out = fgets($pipes[1]);

            $err_err = fgets($pipes[2]);

            \Log::error("Error OUTPUT: ".$err_out);

            $this->info($err_out);

            \Log::error("Error ERROR : ".$err_err);

            $this->error($err_err);

            throw $e;

        }
```

**Comment by jeffjoseph** [comment]
I don't know if you needed anymore details. If needed please comment

**Comment by jeffjoseph** [comment]
i tried to run restore script using artisan

> php artisan snipeit:restore \path to the backup file

but when i run the script  I get this error 

 ```
'C:\Program' is not recognized as an internal or external command, 

ErrorException 
fwrite(): write of 78 bytes failed with errno=22 Invalid argument
at C:\inetpub\wwwroot\snipe-it\app\Console\Commands\RestoreFromBackup.php:257
   253▕         try {
   254▕             while (($buffer = fgets($sql_contents, self::$buffer_size)) !== false) {
   255▕                 $bytes_read += strlen($buffer);
   256▕                 // \Log::debug("Buffer is: '$buffer'");
 ➜ 257▕                     $bytes_written = fwrite($pipes[0], $buffer);
   258▕
   259▕                 if ($bytes_written === false) {
   260▕                     throw new Exception("Unable to write to pipe");
   261▕                 }
                }
1   C:\inetpub\wwwroot\snipe-it\app\Console\Commands\RestoreFromBackup.php:257
     fwrite()
2   C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
     App\Console\Commands\RestoreFromBackup::handle() 

```
have you noticed the the part where it's saying 

> 'C:\Program' is not recognized as an internal or external command,

I dont know if I am wrong,I guess there is missing quotes in path specification to db or somewhere else I don't know where it is. Can you just double check the ps script.
And I am  also guessing that when restore button  in web console try to run this script  it's also getting the same error .

this is my .env vaiable for db

> DB_DUMP_PATH='C:\Program Files\MariaDB 10.4\bin' 

NB:all this are my assumptions.

**Comment by snipe** [comment]
Per https://snipe-it.readme.io/docs/configuration#required-database-settings

<img width="809" alt="Screenshot 2023-12-24 at 1 40 47 PM" src="https://github.com/snipe/snipe-it/assets/197404/b4b09d9f-c08d-42dd-b959-109ea55b49d0">

I'm guessing it's the lack of double slashes and incorrect pathname.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#required-database-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.Don't be intimidated by the length of this page. The configuratio...</div></blockquote>

**Comment by jeffjoseph** [comment]
Thanks, It got resolved.
