### ISSUE TITLE
Can't access laravel logs

### ISSUE THREAD

**Issue by jeffjoseph** [grokability/snipe-it#14080]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have tried` php artisan log:clear` but it showed an error saying 
 

> There are no commands defined in the "log" namespace.

 after that it shows the logs in scrambled way looks like chinese characters

### Reproduction steps

1.run "php artisan log:clear" from the directory of snipe it

### Expected behavior

need to see laravel logs 

### scrambled laravel logs 
![Screenshot (3)](https://github.com/snipe/snipe-it/assets/42379369/0b571ab8-5d1e-4bd8-b6fc-995fa0f0fa3b)
### error in powershell
![Screenshot 2023-12-29 103804](https://github.com/snipe/snipe-it/assets/42379369/3c850564-30ea-441d-b1a2-be09dad2e70c)

### Snipe-IT Version

v6.2.3

### Operating System

windows server 2012 standard

### Web Server

iis 8

### PHP Version

7.4.3

**Comment by jeffjoseph** [comment]
Please help me ,is there any way to undo this.

**Comment by marcusmoore** [comment]
Hi @jeffjoseph,

Are you able to log into the application ok? If you don't need those logs (if you're not looking for something specific) you can delete that file (`laravel.log`) and it will be recreated when Laravel logs a new entry.

Why it is logging in a different language is an interesting issue though. I would try to delete the log and then do an action that will generate log entries and see if they are in the language you expect. Visiting the dashboard should generate entries if you're in debug mode. You can follow the steps in at the top of this [page](https://snipe-it.readme.io/docs/advanced-debugging) to turn debug mode on. Remember to carefully follow the steps for turning it back off after you're done.

`php artisan log:clear` isn't a valid command so the error you're getting makes sense.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
