### ISSUE TITLE
Users with asset view & checkout permissions can also edit the asset-name while checking the asset out

### ISSUE THREAD

**Issue by chrisgassen** [grokability/snipe-it#14086]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Users with only the following permissions:
- asset view
- asset checkout

can also change the name of the asset while checking the asset out.

I don't think this is intended behaviour.

### Reproduction steps

1. create new testgroup with only asset view & checkout permission
2. assign this testgroup to an existing user
3. checkout an asset and while doing so changing the asset name

### Expected behavior

asset name can't be changed, as there are no edit permissions

### Snipe-IT Version

v6.2.4-pre 

### Operating System

Debian 12

### Web Server

Apache 4.57

### PHP Version

8.1.27

**Comment by Godmartinz** [comment]
So this actually is expected behavior. The Asset name can be edited to whatever is best practice. For example it could be named Cubicle 1, Room 221, or Remote Bob. It can be used for better clarity where it is. The editing of the name is built into the checkout feature

**Comment by chrisgassen** [comment]
hmm ok I can see the reasoning. I would rather like to be able to change notes or the location, but I guess that's too much work.

"solution" for me now is to only give checkout permissions to some certain people, who know to not change asset names.

**Comment by snipe** [comment]
Checkout notes already exist, but they are intended as a note for the checkout action itself, not to update the asset. Those notes all show up in the asset's history to tell a more complete story of the lifecycle of the item. Locations are inherited from the user/location it's being checked out to.
