### ISSUE TITLE
All Seat IDs are 0 when click on Department

### ISSUE THREAD

**Issue by Chrismucer** [grokability/snipe-it#14081]
### Debug mode

- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug
All Seat IDs are 0 when click on **Department**.
If the license ID is 0, press **Checkout** and after assigning it press **Checkin**, it will show the error **Error: License not found**.
The license IDs are displayed again if you click on **ID**. Now clicking on **Checkin** does not show the error.

### Reproduction steps

1. Access on an individual license.
2. Click on **Department**.
3. All Seat IDs are **0**.

### Expected behavior

That the Seat IDs show correctly.

### Screenshots

![snipeit_license](https://github.com/snipe/snipe-it/assets/42436300/4cf2c953-f801-47a8-a326-9c1de787d761)
![snipeit_license_02](https://github.com/snipe/snipe-it/assets/42436300/5f532576-358c-4e88-a703-04f024f74b48)

### Snipe-IT Version

v6.2.4-pre - build 12090 (master)

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

v8.1.2-1ubuntu2.14

**Comment by snipe** [comment]
I'm still not sure how to get to this screen. Departments aren't associated with licenses, so where are you clicking to get to a department link in Step 2?

<img width="862" alt="View_License_-_Acrobat____Snipe-IT_Demo" src="https://github.com/snipe/snipe-it/assets/197404/6ff6e571-02e6-490c-bddc-a488c59be3df">

<img width="862" alt="View_License_-_Acrobat____Snipe-IT_Demo-3" src="https://github.com/snipe/snipe-it/assets/197404/54c044fa-ec16-45e5-941b-2a1041281774">
