### ISSUE TITLE
New Superadmin cannot see any assets

### ISSUE THREAD

**Issue by Pcole1963** [grokability/snipe-it#14085]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Small org.  I setup the hosted site and added my tech as a Superadmin.  He has all permissions granted, but when he logs in, can only see his own assets and cannot manage the system.

### Reproduction steps

1. User logs in.  Does not see any left-hand menu items.
2. Only sees his own assets
3.
...

### Expected behavior

User is SuperAdmin, should see all menu options.

### Snipe-IT Version

v6.2.3 build 11936 (gb47e734b3) 

### Operating System

n/a

### Web Server

n/a

### PHP Version

8.1.23 

### Operating System

Windows 10

### Browser

Edge, Mozilla

**Comment by snipe** [comment]
I haven't heard of this before, and cannot reproduce it. Are you sure you don't have two different users for your tech, one with superadmin and one without?

**Comment by Pcole1963** [comment]
No, there is only one Person record for him.  I'm thinking of deleting it and creating a new account.

**Comment by snipe** [comment]
I guess you can try that. If they are set as superuser, you don't need to grant additional permissions. (Also keep in mind that there are group based permissions and individual permissions. One might be overwriting the other if he belongs to a permissions group, so that's something to check.)

**Comment by Pcole1963** [comment]
I had to delete the user account and him back into the system.  The new account worked fine.

**Comment by snipe** [comment]
Glad you're sorted.
