### ISSUE TITLE
Remove "manufacturer_id" requirement in API docs

### ISSUE THREAD

**Issue by pieterhouwen** [grokability/snipe-it#14082]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The page at https://snipe-it.readme.io/reference/models-1 states that the manufacturer_id parameter is required but this is not the case when using the "Try it!" functionality and when creating a new asset model in the web GUI.

### Reproduction steps

NA

### Expected behavior

"manufacturer_id" should not be designated as a required field in the API docs.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/10866686/3765e4fc-2a03-42be-b6b6-990aa5c579c4)

### Snipe-IT Version

NA

### Operating System

NA

### Web Server

NA

### PHP Version

NA

**Comment by snipe** [comment]
Updated, thanks!
