### ISSUE TITLE
[Feature Request]: Allow Normalising Custom Fields with Regex

### ISSUE THREAD

**Issue by MCterra10** [grokability/snipe-it#14111]
### Is your feature request related to a problem? Please describe.

I'm using snipe-it to manage assets for a telecommunications business, which means we are scanning in and out large volumes of assets, specifically IP phones. To speed things up, we scan the MAC addresses off of barcodes on the boxes of devices. However, most of these MACs are provided in purely numerical form, without the colons to space them out. This means I can't use the builtin MAC field because it won't parse without me manually adding in the colons.

### Describe the solution you'd like

I'd like the ability to use capture groups in regex to normalise several different accepted data formats into something consistent.
Alternatively, modifying the built in MAC field type to normalise purely numerical MACs would work fine too.

### Describe alternatives you've considered

Right now the only solution is to use an ANY custom field, or a match only regex to parse the MACs, but this makes them useless for searching because they can be in any format.

**Comment by NPGH0** [comment]
Hi,

you can create your own MAC-Address field and use RegEx as wished.
on this site you can build your required regex for your case: https://regexr.com/
there are even predefined patterns for using.
Here for example is a regex which accepts "-" and ":" for example: https://regexr.com/33k7t


feel free to try it out and see whats fits best for you.


<blockquote><div><strong><a href="https://regexr.com/">Just a moment...</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://regexr.com/33k7t">Just a moment...</a></strong></div></blockquote>

**Comment by snipe** [comment]
As @NPGH0 said, you can use your own regex. The MAC address regex is just an example, but any valid regex will work for custom fields.

**Comment by MCterra10** [comment]
@snipe thanks for your response, but I think you have misunderstood the request I am making.
I am looking for the ability to use the replacement function in regex, for example to add colons in to a MAC automatically that is provided without them.
I am aware that I can create a regex simply to match different MAC formats, but that's not what I want to achieve.
