### ISSUE TITLE
Cannot add, delete, edit Licenses

### ISSUE THREAD

**Issue by langjino** [grokability/snipe-it#14117]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I cannot add, delete, edit Licenses, I have import sample csv, but still not edit Liciense

### Reproduction steps

1. Xammp server
2. Window Server 2012
3. Snipe-IT 6.23
...

### Expected behavior

Add, Edit, Delete

### Screenshots

![screenshot_1704879422](https://github.com/snipe/snipe-it/assets/139469476/38c59bf1-de74-4408-ae3e-6b5b5bb5547f)

### Snipe-IT Version

6.2.3

### Operating System

Windows

### Web Server

Apache

### PHP Version

8.1

### Operating System

Windows

### Browser

Chrome

### Version

93

### Error messages

```shell
Nothing Error messages
```

### Additional context

Nothing Error messages

**Comment by langjino** [comment]
Open Snipe-IT
Go to licenses
Add new license
fill in the 3 requested fields
Press save
page reloads, without any problem, error message.
in larafel.log tere is noting, empty

**Comment by snipe** [comment]
Please provide us with the information requested at the Getting Help documentation: 
https://snipe-it.readme.io/docs/getting-help

If you're getting a 500 error, it will likely be in the app log

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
