### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipe_it_data.cache' doesn't exist

### ISSUE THREAD

**Issue by chris-pryazhentsev** [grokability/snipe-it#14141]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When creating a new install of Snipe-IT with CACHE_DRIVER set to database, the cache DB table is not created, even after running `php artisan migrate --force`. 

Right now my environment is I have 1 instance of Snipe IT running in AWS ECS with a MySQL RDS instance for a database, all other tables were successfully created outside of 

### Reproduction steps

1.Create new instance in docker
2. Set CACHE_DRIVER to database
3. cache table will not be created

### Expected behavior

Cache table is created when CACHE_DRIVER is set to `database`

### Snipe-IT Version

Master

### Operating System

Linux

### Web Server

Apache

### PHP Version

8.1.26

### Operating System

Windows 11

### Browser

Google Chrome

### Version

120.0.6099.224

### Error messages

```shell
SQLSTATE[42S02]: Base table or view not found: 1146 Table '[database name redacted].cache' doesn't exist (SQL: select * from `cache` where `key` = snipeit[email address redacted]|172.16.158.150 limit 1)
```

**Comment by snipe** [comment]
Try running `php artisan cache:table` and then `php artisan migrate`
