### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by kuratlielia** [grokability/snipe-it#14150]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I can't import CSV files.

I tried to import the example files from...

- https://snipe-it.readme.io/docs/importing

...over the GUI and CLI and both didn't work.

On the GUI I got an upload error and over the CLI I got the following Error:

`Error: Item:  failed validation: {"Asset \"\"":{"model_id":["The model id field is required."]}}`

### Reproduction steps

1. Download Example CSV
2. Upload over the CLI with php artisan snipeit:import

### Expected behavior

Import without errors.

### Snipe-IT Version

v6.2.4

### Operating System

Windows Server 2022

### Web Server

IIS

### PHP Version

8.0.30

### Error messages

```shell
Error: Item:  failed validation: {"Asset \"\"":{"model_id":["The model id field is required."]}}
```

### Additional context

Everything else is working fine but the import isn't working.

I tried it with different files even with exports I created in the application.

**Comment by marcusmoore** [comment]
Thanks for reporting this @kuratlielia. It looks like the model number column, at least for assets, in the sample sheet is stored in scientific notion.

![model number in importer](https://github.com/snipe/snipe-it/assets/1141514/85fc9124-7458-46de-9047-7ec6aa989354)

![model number column in excel](https://github.com/snipe/snipe-it/assets/1141514/947923fd-b473-45e9-975d-60f549a3b9df)

This is a mistake on our part. We'll get those updated.

**Comment by marcusmoore** [comment]
@kuratlielia actually we may have experienced the same thing...did you modify the sample file in Excel (or another tool) and have the formatting update to scientific notation by any chance? The file from the docs has the model number formatted correctly (6377018600094472) but I opened it in Excel, deleted most of the rows, saved, and imported that file. After saving Excel changed the format for the column to the `6.37702E+15` in the screenshot above.

**Comment by kuratlielia** [comment]
@marcusmoore I didn't open the sample file or edited it in any way. I just tried it with the default values. Do you think I have an error in my configuration inside the application? Or with the bindings of the values? Because it should work with the sample file without changing it.

**Comment by marcusmoore** [comment]
@kuratlielia Hm...I'm not sure to be honest. I downloaded the sample csv, uploaded it untouched, and ran an import just fine. I also tried via the cli without error.

When you upload the file do you see the full model number like this:
![with valid model number](https://github.com/snipe/snipe-it/assets/1141514/d84eab4d-f27a-43af-afcb-91f109524430)

Or do you see it like this?
![with invalid model number](https://github.com/snipe/snipe-it/assets/1141514/e9ca1a69-60b9-44e1-a67b-b16088fcd7bf)

**Comment by kuratlielia** [comment]
@marcusmoore I don't see it at all because I can't upload the files. As seen in the Screenshot below:

![grafik](https://github.com/snipe/snipe-it/assets/82137127/c98d00af-3e24-4739-a4d1-7a7179d4d160)

It is really strange because I use the default sample file. I also checked it in Notepad an it looks like this:

![grafik](https://github.com/snipe/snipe-it/assets/82137127/7bdd7a8a-dca5-4855-8f6a-e8dc49e5b2d5)

I don't see any empty rows or double column names.

**Comment by marcusmoore** [comment]
@kuratlielia ah sorry I saw the error message `Error: Item:  failed validation: {"Asset \"\"":{"model_id":["The model id field is required."]}}` and missed the `On the GUI I got an upload error and over the CLI I got the following Error:` above it.

Is this isolated to the importer? Are you able to upload files elsewhere successfully (like attaching uploads to an asset)? Has this worked for you previously and started failing recently?

**Comment by kuratlielia** [comment]
@marcusmoore If I try to upload for example a picture to one of the Assets I get the following Error:

![grafik](https://github.com/snipe/snipe-it/assets/82137127/2cf2882a-b376-4753-b774-dbbe56ab765b)

It is a fresh install and the upload functionality has never worked before.

I also gave the webserver the writing rights for the folders.
Is there maybe another Folder that the webserver needs access to?

**Comment by marcusmoore** [comment]
@kuratlielia what's your `upload_tmp_dir` set to? (You can go to `{app_url}/admin/phpinfo` and find it on that page.)

**Comment by kuratlielia** [comment]
@marcusmoore it has no value.

![grafik](https://github.com/snipe/snipe-it/assets/82137127/3326f085-e1c2-47e2-b527-9fcc2e70e3e9)

I will try to fix it.

**Comment by kuratlielia** [comment]
@marcusmoore I set the upload dir manually to the default Windows temp folder and gave the IIS user full control permissions. (As seen in the screenshot below) The user already had the permissions before.

![grafik](https://github.com/snipe/snipe-it/assets/82137127/8424e6ab-9df0-4e9e-9631-a4853f6694bd)

And now every upload works.
Thank you for being so helpful!
