### ISSUE TITLE
Expected checkin notification

### ISSUE THREAD

**Issue by DasRedy** [grokability/snipe-it#14156]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hey guys,

i got a question about the expected checkin notification for users that got assigned assets.
Currently a user that got assigned an asset gets notifications starting maybe about a week before due date everyday at midnight. Also, for every asset assigned, there is an own e-mail send.
So if a user has 4 assets assigned to them, a week before they are expected to return that asset, they get 4 e-mails every day, which is a bit much.

is it possible to bundle these e-mails into one and maybe only send an e-mail a day or two before the expected checkin date?

Cheers,

### Reproduction steps

1.
2.
3.

### Expected behavior

Bundle expected checkin e-mails for users into one mail and send it one day before due date.

### Snipe-IT Version

6.2.4

### Operating System

Ubuntu 20.4.6

### Web Server

Apache

### PHP Version

7.4.3

**Comment by snipe** [comment]
Rolling up notifications has been requested before and is on the list for after v7 is released.
