### ISSUE TITLE
[Feature Request]: Create tabs for the custom fields

### ISSUE THREAD

**Issue by ChrisWinkel** [grokability/snipe-it#14168]
### Is your feature request related to a problem? Please describe.

Now if you have a lot of custom fields the page is very long

### Describe the solution you'd like

create different tab for custom fields.

**Comment by snipe** [comment]
I'm not sure how tabs would help - you'd just have a shorter page with a ton of tabs, which would clutter up the UI and make it difficult to use on mobile.
