### ISSUE TITLE
Preflight setup not loading

### ISSUE THREAD

**Issue by BillBBBB** [grokability/snipe-it#14169]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm probably missing something, but I have a manual install on windows server 2019 built out for this with mariaDB and IIS.
After finishing the base install, I go to the webpage Https://myurl/server.php it redirects to https://myurl/setup/ 
Then I get a 404. 

I looked around in the source zip and the tar.gz and neither has a folder for setup. Did I somehow miss part of the install that builds that out?  

### Reproduction steps

1.Followed manual install guide
2.tried to load webpage
3.get redirected to non-existent setup dir. 
...

### Expected behavior

I would expect the preflight page to load here. 

### Snipe-IT Version

6.2.3

### Operating System

windows

### Web Server

IIS

### PHP Version

8.1.27

### Operating System

windows

### Browser

edge and chrome

### Version

na

### Device

na

### Operating System

na

### Browser

na

### Version

na

**Comment by snipe** [comment]
> After finishing the base install, I go to the webpage https://myurl/server.php

You wouldn't go to server.php for any reason. You'd to go https://myurl/. The redirect to setup is expected, however something in your IIS config seems to be ignoring the web.config information we provide.

**Comment by BillBBBB** [comment]
I think I see what I did. Out of pure habit I mapped the site to 
C:\inetpub\wwwroot\snipe-it\
not
C:\inetpub\wwwroot\snipe-it\public\

**Comment by snipe** [comment]
That would do it, yeah

**Comment by BillBBBB** [comment]
I'm all set! Thanks for being awesome!
