### ISSUE TITLE
[Feature Request]:  More options for groups / like department based rights

### ISSUE THREAD

**Issue by ChrisWinkel** [grokability/snipe-it#14167]
### Is your feature request related to a problem? Please describe.

Now you have 3 types of groups, A user , A admin and a super admin.

Like to see more option in the groups so that a manager only see his users based on his department

### Describe the solution you'd like

The problem with that is, a users has a manager, now the manager whats to see only the users / assets where he is manager of.

**Comment by snipe** [comment]
Duplicate of #13174
