### ISSUE TITLE
Broken pluralization in localization strings for trans_choice() when using en-US, pt-PT, etc (dashed directory names)

### ISSUE THREAD

**Issue by snipe** [grokability/snipe-it#14173]
The issue: Because Symfony apparently doesn't support the `en-US` (dashed) format of language files (it wants `en_US` for some unbeknownst reason) - and we just did a whole bunch of migrations and other crap to get us to the RFC compliant `en-US` format, we're ending up with `trans_choice()` options always defaulting to the singular. For example, 

`'warn'  => 'You are about to update the properties of the following model:|You are about to edit the properties of the following :model_count models:',`

*should* show us the second string after the pipe if there is more than one of the thing.

In other words, if we pass `1` to the `trans_choice('blah.warn)` localization invocation, I'd expect to see:

`You are about to update the properties of the following model:`

but if we pass `5` to the `trans_choice('blah.warn)` localization, I'd expect to see:

`You are about to edit the properties of the following :model_count models:` (assuming we also passed in `model_count`, of course.)

However it is always defaulting back to the singular version. If I manually change my locale in my profile's `locale` field to `en_US` (underscored), it works correctly - however if I change it to `pt_PT`, the rest of the site defaults back to English since `pt_PT` doesn't exist in the `resources/lang` directory, `pt-PT` does. Laravel handles the ***string that needs to be pluralized/not pluralized depending on the count passed to the string***, but Symfony handles the _**determination of which of those strings to use**_, and they're both looking for differently named language directories. 

This absolutely sucks, and had we known Symfony was going to be so dumb about this, we would have just picked the original `en_US` format when we made all of those language directory changes and database migrations. 

While we could consider doing some `str_replace()` shenanigans to convert those pluralized choice strings on the fly, the underscore style directories don't exist in Laravel/Snipe-IT, which means those pluralized strings will fall back to English every time if we do that.

Right now, we're still not sure how we want to handle this. We have a few options and they're all pretty terrible. Still working on it, but since Shortcut is currently bugging out and not letting me make an internal ticket, I'm putting it here.

I'm desperately hoping I missed somewhere that Symfony fixed this and made it into an overridable setting, but so far, my searches have come up empty. 

### Related Links:

- https://github.com/laravel/framework/issues/23226
- https://github.com/symfony/symfony/issues/19353
- https://github.com/laravel/framework/pull/23227 <-- this PR would have fixed it, but it was closed, unmerged.
- https://gist.github.com/ThePeterMick/b1ecaca960296479844fd3fc49e51cf2 <-- proposed gist workaround

**Comment by uberbrady** [comment]
I have a terrible, terrible solution that I've cobbled together, but I'm going to try and get it to a place where it's less unpleasant to use. But worst-case scenario we can search-and-replace all of the `trans_choice()` calls and change them to `bradys_choice()` (name is currently under review for this function...).

**Comment by uberbrady** [comment]
I am at least *hoping* I can try to extend the default `Translator` and then load that up in the AppServiceProvider maybe to 'swap out' the default translator for our own. That way we can keep the code the same, possibly rip out this new code I just wrote, as well as we can extend the changes I've made if we find any other places where things might be broken.

**Comment by hasan-ozbey** [comment]
I recently ran into the same hyphen-vs_underscore locale issue in my own Laravel project. I don't know Snipe-IT's internals but here's the quick fix that worked for me:

1. Keep `locale` and `fallback_locale` in `config/app.php` as BCP 47 tags (`en-US`, `pt-BR`, etc.).
2. Rename the folders in `/lang` to use the ISO 15897 format (`en_US`, `pt_BR`, …).
3. Add a small decorator to normalize the locale in the `Translator` class:

```php
public function register(): void
{
    $this->app->extend(
        \Illuminate\Contracts\Translation\Translator::class,
        function (\Illuminate\Contracts\Translation\Translator $translator) {
            $translator->setLocale(
                str_replace('-', '_', $translator->getLocale())
            );
            $translator->setFallback(
                str_replace('-', '_', $translator->getFallback())
            );

            return $translator;
        }
    );
}
```

I'm sharing this here because I spent quite a bit of time researching the issue and eventually ended up on this page. Hope this helps someone out there!
