### ISSUE TITLE
Cant upgrade to 6.3.0 ldap is missing

### ISSUE THREAD

**Issue by Zrki85** [grokability/snipe-it#14184]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello, when i want to upgrade to 6.3.0 i have msg  MISSING PHP EXTENSION: ldap but i dont use ldap

### Reproduction steps

1.  php upgrade.php
2.
3.
...

### Expected behavior

I need to upgrade to 6.3.0

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/139642383/fac50eed-f207-4100-99fc-8b4b6daf5861)

### Snipe-IT Version

6.2.3

### Operating System

Linux

### Web Server

Apache

### PHP Version

8.1

**Comment by snipe** [comment]
Install the LDAP extension, as the script suggests.
