### ISSUE TITLE
remote scripts feature has been removed / snipe slow when not connected to the internet

### ISSUE THREAD

**Issue by tomse** [grokability/snipe-it#14185]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

https://snipe-it.readme.io/docs/general-settings#remote-scripts
Remote scripts are not to be found in general page as stated in the documentation.

Snipe is slow finalizing loading when there is no internet connection. visible pointers are gravatar image.
and after timeout it refreshes the screen, so if you've scrolled down to edit something the screen refreshes and has jumped to the top of the page.

I can't say if missing internet also affects lookup of "Company" "Model" "default location" when using the pulldown menu.

### Reproduction steps

1. install snipe using docker on ubuntu 2204 lts
2. remove the internet connection
3. navigate 
4. check the loading image of the browser, make note of how it jumps if you scroll down before the browser animation for "loading page" stops
5. check gravatar icon - even though it's not configured.

Secondary
1. create a company, a location, and a model
2. create a new asset 
3. use the pull down menu for company.
4. watch it "load" forever

Going to the chosen menu items from the side panel displays a listing of companies, locations and models respectively.

### Expected behavior

fast response

loading of company, model, location should list contents

### Snipe-IT Version

6.3.0

### Operating System

ubuntu 2204

### Web Server

official docker image 

### PHP Version

official docker image

### Operating System

Win 10 22h2

### Browser

edge

### Version

119

**Comment by tomse** [comment]
After turning off debugging, models, company and locations are now loaded, populating the pull down menus..

Though loading animation in browser tab is till running "long" time after page load finishes, and eventually a broken image is shown to the left of the name in top right corner, instead of gravatar (or expected no image).

And there is a reference in the manual to a function that doesn't show in the generals tab - settings.

**Comment by snipe** [comment]
Gravitar would be the only thing we reach out to the outside world for.

**Comment by tomse** [comment]
sounds like you've made some changes recently to not have remote scripts supplied by cdn - this was an issue in earlier versions.

the screen still jumps (scrolls) to the top when the loading reaches it's timeout. would be nice to have a setting where it doesn't try and lookup gravatar, with all the small inconveniences that comes with that on a closed network.

**Comment by snipe** [comment]
We haven’t made any changes to loading outside scripts in many years. If you flip the `load_remote` flag on the `settings` table, it should prevent the script from trying to reach out to Gravatar.com. https://github.com/snipe/snipe-it/blob/86c625ed8f5956c8ee75b54578965083742548f1/app/Presenters/UserPresenter.php#L413

**Comment by tomse** [comment]
thank you, that did the trick
