### ISSUE TITLE
[Feature Request]: limit access to assets

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#14204]
### Is your feature request related to a problem? Please describe.

Generally, you can track different types of assets with Snipe-IT: cars, furniture, IT equipment, etc. You can create different locations for these assets, but you can't limit admin access to specific location or asset category. For example, company has 3 sites and 6 managers. Every manager is responsible only for his site (location) and only for specific assets (eg., one IT and one company fleet manager per site). IT manager shouldn't see fleet or be able to check-in/check-out/edit anything other than IT. Fleet manager shouldn't be able to access and manage IT equipment.

### Describe the solution you'd like

In user group permission table you can select to which locations and asset categories users have access.
Categories should have hierarchy. This way you could differentiate assets by the type.

### Describe alternatives you've considered

Currently, you need to enable Full Multiple companies support and use it as a workaround. But this way you only have two options: differentiate by site location (SITE1, SITE2, etc.) or asset type (IT, FLEET, FURNITURE). Another option- run separate Snipe-IT copies for different types of assets.

**Comment by snipe** [comment]
This has been brought up several times already. Please thumbs-up the existing issues instead of adding another one.
