### ISSUE TITLE
Can't Upgrade and Getting 500 Error 

### ISSUE THREAD

**Issue by brianhoganm** [grokability/snipe-it#14200]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am so dissapointed. Everything was WORKING AMAMZING until I upgraded to version 6.3. When I go to checkin/ or checked out deviced to people, I get a 500 error message. I can't upgrade either. I get a message there as well in GIT. I tried clearing cache and going through the recomedned commands and I tried changing the PHP verion and still nothing. I feel I like I lost functionality of SNIPEIT. I even ran git fetch --all and did a get reset as well. 

![image](https://github.com/snipe/snipe-it/assets/109772627/5b85304e-ff27-49ed-b750-f6e1d5142609)

![image](https://github.com/snipe/snipe-it/assets/109772627/71949a28-d9d3-4159-a6d5-2a22352a0fdd)

### Reproduction steps

1. Checking in
2. Checking out
3. Error 500
...

### Expected behavior

Should work. 

### Snipe-IT Version

6.3

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.22

**Comment by snipe** [comment]
We’ll get you back up and running. We added something in v6.30 that will hopefully make future upgrades easier, but we might have caused a glitch for certain use cases. Can your system talk to the outside world? (I’d think so, since composer install would require that.) @jerm - can you dig around and see what’s up?

**Comment by jerm** [comment]
Interesting.. i can't reproduce this, but i'll add some more error output and checks to hopefully give a better sense of what's going on going forward

IN THE MEAN TIME..... can you step through these commands for me? Hopefully this will help us narrow it down:

first off, please make sure you can hit this URL in your browser on that machine: https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json

If that works, let's do:

```
php -a

$remote_requirements_file = "https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json";

$raw_contents=file_get_contents($remote_requirements_file);

var_dump($raw_contents);

$upgrade_requirements=json_decode($raw_contents, true);

var_dump($upgrade_requirements);

```

Paste the output here and let's see what's going on.

**Comment by jerm** [comment]
actually, i may have found the issue, apparently file_get_contents doesn't _necessarily_ work with URLs...

can you look in your php configs for allow_url_fopen ?

an easy way would be `sudo grep -r allow_url_fopen /etc/php*`

betting your server has this set to `Off` or `0`. If you're able, change it to `On` or `1` and try the script again

In the meantime, I'll look for a workaround, as we can't reliably have everyone change this setting.

**Comment by jerm** [comment]
@brianhoganm 

I've put up a pr to fix the issue and at https://github.com/snipe/snipe-it/pull/14236.

If you don't want to wait, try fetching -a and checking-out `jerm/upgrade-script-enhancements` and giving it another go. That branch _only_ has my fixes to upgrade.php vs master

**Comment by jerm** [comment]
@brianhoganm did this work for you?

**Comment by jerm** [comment]
it's on master now, so no special branching needed

**Comment by jerm** [comment]
you'll need to pull down the latest source before you run it.

It seems like you hit the same problem as this person: https://github.com/snipe/snipe-it/issues/14224

And this fix worked for them.

I'm going to close this issue now, since the fix is out. Feel free to re-open if it doesn't work for you.

**Comment by brianhoganm** [comment]
Hello, I still get the same error. I don't know what to do. 

![image](https://github.com/snipe/snipe-it/assets/109772627/7cfc5559-b0ea-4945-9261-c59633d085b4)

I even copied the .upgrade_requirements.json and the new upgrade.php file from the master and pasted into my SNIPEIT folder and still nothing.

**Comment by jerm** [comment]
The second image you added up there is a separate and different issue... it would be better if you added new information to the conversation, or even opened a new issue, rather then editing history by updating the original request

That being said, this looks like you're missing DB columns and need to run `php artisan migrate`

**Comment by brianhoganm** [comment]
> The second image you added up there is a separate and different issue... it would be better if you added new information to the conversation, or even opened a new issue, rather then editing history by updating the original request
> 
> That being said, this looks like you're missing DB columns and need to run `php artisan migrate`

thanks. for now we decided give snipeit a break and just use google sheets. we just cant get it to work. we kind of gave up. but thanks for all of your help.
