### ISSUE TITLE
The requested URL was not found on this server after update to 6.3.0

### ISSUE THREAD

**Issue by Zrki85** [grokability/snipe-it#14212]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, when i updated to 6.3.0 now i have this error - The requested URL was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

### Reproduction steps

 The requested URL was not found on this server.

### Expected behavior

 The requested URL was not found on this server.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/139642383/30c97aab-d117-413b-93b5-c161d4c0dcc1)
![image](https://github.com/snipe/snipe-it/assets/139642383/1c8ec394-a2ad-455d-b9cd-3483b6cc7d86)

### Snipe-IT Version

6.3.0

### Operating System

Shared Hosting

### Web Server

Apache

### PHP Version

8.1

**Comment by Zrki85** [comment]
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Needed for https://letsencrypt.org/ certificates.
    RewriteRule ^\.well-known/acme-challenge/ - [L]

    # Uncomment these two lines to force SSL redirect in Apache
    # RewriteCond %{HTTPS} off
    # RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]



    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Security Headers
    # Header set Strict-Transport-Security "max-age=2592000" env=HTTPS
    # Header set X-XSS-Protection "1; mode=block"
    # Header set X-Content-Type-Options nosniff
    # Header set X-Permitted-Cross-Domain-Policies "master-only"

</IfModule>
Options -Indexes

# DENY ACCESS TO IIS CONFIG FILE

# Apache 2.2+
<IfModule !authz_core_module>
	<Files "web.config">
	    Order allow,deny
    	Deny from all
    </Files>
</IfModule>

# Apache 2.4+
<IfModule authz_core_module>
	<Files "web.config">
      Require all denied
    </Files>
</IfModule>

**Comment by Zrki85** [comment]
Problem was in .htaccess. Solved now. Tnx

**Comment by itdivtieclo** [comment]
Hello..I was wondering what specific fix you made in here?I also have the same issue like you.. I am in he middle of setting up now and stumbled on the same error on "http://localhost/setup"...

Also which .htaccess file did you modify ? Is it on inside the "public" folder or outside ?

**Comment by itdivtieclo** [comment]
Content of .htaccess in public folder

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Needed for https://letsencrypt.org/ certificates.
    RewriteRule ^\.well-known/acme-challenge/ - [L]

    # Uncomment these two lines to force SSL redirect in Apache
    # RewriteCond %{HTTPS} off
    # RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]



    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Security Headers
    # Header set Strict-Transport-Security "max-age=2592000" env=HTTPS
    # Header set X-XSS-Protection "1; mode=block"
    # Header set X-Content-Type-Options nosniff
    # Header set X-Permitted-Cross-Domain-Policies "master-only"

</IfModule>
Options -Indexes

# DENY ACCESS TO IIS CONFIG FILE

# Apache 2.2+
<IfModule !authz_core_module>
	<Files "web.config">
	    Order allow,deny
    	Deny from all
    </Files>
</IfModule>

# Apache 2.4+
<IfModule authz_core_module>
	<Files "web.config">
      Require all denied
    </Files>
</IfModule>
