### ISSUE TITLE
LDAPSettings array 'ldap_emp_num' twice

### ISSUE THREAD

**Issue by mueneee** [grokability/snipe-it#14211]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In the function getLdapSettings() in the Setting.php, the array **$ldapSettings** contains the element _ldap_emp_num_ twice.

### Reproduction steps

Check the array **$ldapSettings** in the function getLdapSettings() in the file Setting.php.

### Expected behavior

The element _ldap_emp_num_ should only occur once.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/139874621/45a115fd-c362-45a7-9de2-c5191b2118d6)

### Snipe-IT Version

6.3.0

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.0.23

**Comment by snipe** [comment]
Thanks for reporting!
