### ISSUE TITLE
Upgrade.php not working on 8.1.27 

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#14224]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, Is 8.1.27 Approved for upgrade?

    "DOC1": "This file is meant to be pulled from the current HEAD of the desired branch, NOT referenced locally",
    "DOC2": "In other words, what you see locally are the requirements for your _current_ install",
    "DOC3": "Please don't rely on these versions for planning upgrades unless you've fetched the most recent version",
    "DOC4": "You should really just ignore it and run upgrade.php. Really",
    "php_min_version": "7.4.0",
    "php_max_major_minor": "8.1",
    "php_max_wontwork": "8.2.0",
    "current_snipeit_version": "6.3"

### Reproduction steps

1. When using upgrade.php , we failed to retrieve remote requirements 

### Expected behavior

shouldn't fail upgrade on 8.1.27

### Snipe-IT Version

 v6.3.0 build 12490 (g9136415bb) 

### Operating System

AlmaLinux v9.3.0

### Web Server

2.4.58

### PHP Version

8.1.27

**Comment by jerm** [comment]
Yes, 8.1.27 is it's allowed. The naming of the parameters is terrible, but 8.2 is too new, but 8.1.* is fine.

What is the error you're receiving when you try to use upgrade.php?

**Comment by jayavman** [comment]
$ php upgrade.php

ERROR: Failed to retrieve remote requirements from https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json
Exiting.

--
First time this has ever happened.

**Comment by jerm** [comment]
Interesting.. i can't reproduce this, but we had someone else have a similar issue

can you step through these commands for me? Hopefully this will help us narrow it down:

first off, please make sure you can hit this URL in your browser on that machine: 

https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json

If that fails, what error are you getting?

If that works, let's do:

```

php -a

$remote_requirements_file = "https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json";

$raw_contents=file_get_contents($remote_requirements_file);

var_dump($raw_contents);

$upgrade_requirements=json_decode($raw_contents, true);

var_dump($upgrade_requirements);

```

Paste the output here and let's see what's going on.

**Comment by jayavman** [comment]
php > $remote_requirements_file = "https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json";
php > 
php > $raw_contents=file_get_contents($remote_requirements_file);
php > 
php > var_dump($raw_contents);
bool(false)
php > 
php > $upgrade_requirements=json_decode($raw_contents, true);
php > 
php > var_dump($upgrade_requirements);
NULL

**Comment by jayavman** [comment]
dont think its on my side of the issue. 

Sure nothing wrong with this commit? 
https://github.com/snipe/snipe-it/pull/14128

As it worked perfectly for a long time before this.

**Comment by jerm** [comment]
Well yes, I'm sure has to do with that. The question is _why_.  The logic is very simple -- get the most current upgrade requirements instead of having them hard-coded... otherwise someone running php7.4 could download source code that only works with php8.1, and then their installation is broken unil they upgrade php. 

The idea here is that it'll tell you whether the next release is (in)compatible _before_ you pull the newest source.

Anyway, it seems like fetching https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json isn't returning anything for some reason. Can you curl this from that server and see what it returns?

**Comment by jerm** [comment]
actually, i may have found the issue, apparently file_get_contents doesn't _necessarily_ work with URLs...

can you look in your php configs for allow_url_fopen ?

an easy way would be `sudo grep -r allow_url_fopen /etc/php*`

betting your server has this set to `Off` or `0`. If you're able, change it to `On` or `1` and try the script again

In the meantime, I'll look for a workaround, as we can't reliably have everyone change this setting.

**Comment by jerm** [comment]
@jayavman 

I've put up a pr to fix the issue and at https://github.com/snipe/snipe-it/pull/14236.

If you don't want to wait, try fetching -a and checking-out `jerm/upgrade-script-enhancements` and giving it another go. That branch _only_ has my fixes to upgrade.php vs master

**Comment by jerm** [comment]
@jayavman did this work for you?

**Comment by jayavman** [comment]
I was waiting for it to go to Master, What do i type to try your one?

**Comment by jerm** [comment]
@jayavman it's on master now :)

**Comment by jayavman** [comment]
asset]$ php upgrade.php

ERROR: Failed to retrieve remote requirements from https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json
Exiting.

Nope , still not working

**Comment by jerm** [comment]
that doesn't look like you have the most current version

pull down the latest changes from master

**Comment by jayavman** [comment]
how do i do this apart from tying php upgrade.php

**Comment by jerm** [comment]
`git fetch -a ; git pull` should do it

**Comment by jayavman** [comment]
git fetch -a ; git pull
remote: Enumerating objects: 792, done.
remote: Counting objects: 100% (787/787), done.
remote: Compressing objects: 100% (327/327), done.
remote: Total 792 (delta 543), reused 656 (delta 460), pack-reused 5
Receiving objects: 100% (792/792), 2.77 MiB | 20.29 MiB/s, done.
Resolving deltas: 100% (543/543), completed with 29 local objects.
From https://github.com/snipe/snipe-it
   86c625ed8..e2c3386c3  master     -> origin/master
   3da787663..a866d6b16  develop    -> origin/develop
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
Updating 86c625ed8..e2c3386c3
error: Your local changes to the following files would be overwritten by merge:
        resources/views/layouts/default.blade.php
Please commit your changes or stash them before you merge.
Aborting

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">GitHub - snipe/snipe-it: A free open source IT asset/license management system</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by snipe** [comment]
If you `git stash` before that pull, what’s the output? It seems to think you’ve edited the default layout blade

**Comment by jayavman** [comment]
git stash
Saved working directory and index state WIP on master: 86c625ed8 Merge remote-tracking branch 'origin/develop'

**Comment by jayavman** [comment]
> If you `git stash` before that pull, what’s the output? It seems to think you’ve edited the default layout blade

very likely as i added some stuff to the footer.

**Comment by jerm** [comment]
now you should be able to pull and run the update.

AFTER the upgrade, you can run `git stash pop` to restore your changes. You do run the risk of a conflict if we've edited the same areas of the file, which you'll need to resolve.

**Comment by jayavman** [comment]
php upgrade.php

ERROR: Failed to retrieve remote requirements from https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json
Exiting.

still same issue

**Comment by jayavman** [comment]
i ran git fetch -a ; git pull again and then php update and it worked :> 

 Snipe-IT version:
v6.3.0 build 12490 (g9136415bb) 

thanks all

**Comment by jerm** [comment]
great!! glad to hear it 😃

thanks for working through it with us. I previously had no idea about that php.ini setting 😅.  Now it's way more portable and flexible.

**Comment by colly72** [comment]
I'm getting this issue too.  I'm on v6.4.2.  How can I resolve it?

**Comment by jerm** [comment]
Can you tell us more about your setup and the exact error output?

**Comment by colly72** [comment]
I'm on Windows Server 2019, using IIS, PHP 8.1.28.  The  full error is:

```
ERROR: Failed to retrieve remote requirements from https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json

We suggest correcting this, but if you can't,  please verify that your requirements conform to those at that url.

 -- DANGER -- DO AT YOUR OWN RISK --
      IF YOU ARE SURE, re-run this script with --skip-php-compatibility-checks to skip this check.
 -- DANGER -- THIS COULD BREAK YOUR INSTALLATIONExiting.
```

**Comment by psmalley-ati** [comment]
I'm having the same problem in v6.4.2 - build 13487 (master) running on Windows Server 2022 with PHP v7.49.29.0

```
D:\Snipe-IT>php upgrade.php
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- validate some very basic .env file settings
- check your PHP version and extension requirements
- check directory permissions
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings


ERROR: Failed to retrieve remote requirements from https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json

We suggest correcting this, but if you can't,  please verify that your requirements conform to those at that url.

 -- DANGER -- DO AT YOUR OWN RISK --
      IF YOU ARE SURE, re-run this script with --skip-php-compatibility-checks to skip this check.
 -- DANGER -- THIS COULD BREAK YOUR INSTALLATIONExiting.


D:\Snipe-IT>
```

**Comment by jerm** [comment]
@psmalley-ati 

This means that your machine got no result when trying to get upgrade info from  https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json

1) is your machine able to reach that url?  if not, you're going to have a bad time all around. try it in a browser?

if that works, run php -a (or php.exe -a? not sure about windows php repl)
```
$Url="https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $Url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$output = curl_exec($ch);
curl_close($ch);
print($output);
```

if you can get the page output (a few lines of json) in a browser _on that server_ but not in that blurb, something is wonky with your php/curl setup.

do you have php curl libraries installed? If not, you _should_ get a different error, but here we are.
