### ISSUE TITLE
[Feature Request]: Add hardware requirements/recommendations to documentation

### ISSUE THREAD

**Issue by pieterhouwen** [grokability/snipe-it#14238]
### Is your feature request related to a problem? Please describe.

The documentation at https://snipe-it.readme.io/docs/requirements does not list recommended hardware specs.

### Describe the solution you'd like

I understand that a big part of stating how much CPU, RAM and Storage you would need to run a Snipe-IT instance yourself is dependent on the use-case, server load etc. However it would be helpful if some ballpark figures could be given:

1 - 25 active users: 1Ghz, 4GB RAM, 20GB Storage
25 - 50 ...
50 - 100 ...
etc

Doesn't need to follow the numbers that I stated but a certain range would be helpful

**Comment by snipe** [comment]
There isn't really a way to know. The software itself can be run on a raspberry pi - it doesn't require a lot. Active users, etc don't matter nearly as much as associated asset, license, etc relationships and how much the activity log has to store. It really depends on everyone's situation and use cases.
