### ISSUE TITLE
Importing Failure

### ISSUE THREAD

**Issue by MattyHumphrey** [grokability/snipe-it#14232]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to import an picture into any existing or any new asset model it fails to import.

### Reproduction steps

1.Open Any Asset Model
2.Click Edit or New
3.Click Select File
4.Select a picture to upload.
5.Snipe accepts that the photo size and format is accepticable.
5.Click Save
6.The image failed to upload.
...

### Expected behavior

Photo should save to that asset model.

### Snipe-IT Version

v6.3.0 - build 12490

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

8.0.19

### Operating System

Windows 11

### Browser

Google Chrome

### Version

121.0.6167.140

### Additional context

No error messages appear within debug. Issues is not present within demo. 
IUSER has full control on Pulic\Upload
Last sucesful upload was 19th January 2024 although we do not try this daily to know what day it stoped working.

**Comment by MattyHumphrey** [comment]
After further investigation this is not just asset models but anything that you can add photos to including compaies and manufactures.

**Comment by snipe** [comment]
If it's not happening on the demo, this would have to be some sort of permissions error or misconfiguration on the server. What's the specific response from the server? Does it look like it uploaded but it didn't? Does the file actually exist on the web server's file system? What types of images are you uploading?

**Comment by MattyHumphrey** [comment]
It looks like it will import fine but then errors after you click upload. It does not give a error message other than the image failed to upload. I tried removing the permissions on IUSR for the public / uploads folder and then reapplying but no change. 

I have tried JPG, JFIF, PNG & GIF.
![Screenshot 2024-02-09 130948](https://github.com/snipe/snipe-it/assets/54706615/7de7e024-7768-4b27-ba1e-c298457220e2)
![Screenshot 2024-02-09 131008](https://github.com/snipe/snipe-it/assets/54706615/c62c70d3-40f6-4b2f-a058-19d62a8e4f43)

**Comment by MattyHumphrey** [comment]
This also fails if I try this directly from the server using the main super administrator account.

**Comment by MattyHumphrey** [comment]
To update further on this I can also not import CSV files for assets either.

**Comment by MattyHumphrey** [comment]
$this->methodNotAllowed($methods, $request->method());

    }

 

    /**

     * Throw a method not allowed HTTP exception.

     *

     * @param  array  $others

     * @param  string  $method

     * @return void

     *

     * @throws \Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException

     */

    protected function methodNotAllowed(array $others, $method)

    {

        throw new MethodNotAllowedHttpException(

            $others,

            sprintf(

                'The %s method is not supported for this route. Supported methods: %s.',

                $method,

                implode(', ', $others)

            )

        );

    }

**Comment by MattyHumphrey** [comment]
After looking
