### ISSUE TITLE
Users receiving email notifications even though they are disabled in settings

### ISSUE THREAD

**Issue by milosdelsystems** [grokability/snipe-it#14237]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm running snipeit on latest version (v6.3.0). 
I have unchecked options to send checkin/checkout emails to users in the Category settings, however, users are still getting emails each time an accessory is checked out or checked in to them, this is happening only for accessories, but not for assets.
This didn't happen in 2-3 versions prior to latest. Also this is only happening when: Require users to confirm acceptance of assets in this category is turned on in Accessory Category Settings

### Reproduction steps

1. checkin/checkout e-mail notifications are turned off in item category settings
2. checkout accessory to a user
3. user recieves e-mail, even though it shouldn't
...

### Expected behavior

1. checkin/checkout e-mail notifications are turned off in item category settings
2. checkout accessory to a user
3. user doesn't receive e-mail

### Snipe-IT Version

v6.3.0

### Operating System

linux debian 11

### Web Server

nginx

### PHP Version

v8.1.2

**Comment by snipe** [comment]
> Also this is only happening when: Require users to confirm acceptance of assets in this category is turned on in Accessory Category Settings

That is expected behavior. The method through which the user accepts the item is via the email, so an email must be sent if you have this option enabled on the category. There is no other method through which users can accept assets.

**Comment by milosdelsystems** [comment]
Yes and that's ok, but what I want is to not send email to user when i checkin accessory from them.
This works on assets but doesn't work on accessories

**Comment by snipe** [comment]
Please show me a screenshot of your category edit page for an example category where this is happening

**Comment by milosdelsystems** [comment]
<img width="718" alt="backpack2" src="https://github.com/snipe/snipe-it/assets/159525821/898d1f52-9334-4953-b26c-7bb7657d1832">

This is for accessories category, and emails are sent to users even though that option is turned off

**Comment by milosdelsystems** [comment]
<img width="740" alt="laptop" src="https://github.com/snipe/snipe-it/assets/159525821/68f03dc0-944a-409d-9f88-4eb44966fb24">

This is for assets category, and email is not sent when I checkin asset from user

**Comment by snipe** [comment]
As I mentioned, you have "Require users to confirm acceptance" checked. That will always generate an email on checkout.

**Comment by marcusmoore** [comment]
> This is for accessories category, and emails are sent to users even though that option is turned off

@milosdelsystems you're saying check in emails are sent for accessories (but not assets) even though the option is unchecked right?

I'll check this out.

**Comment by milosdelsystems** [comment]
@marcusmoore Yes that's correct, only for accessories.
I have the option 'send email to user on check-in' turned off for both assets and accessories (as shown in the screenshots above). However, users still receive emails when I check in accessories for them, and they don't receive emails for asset check-ins.

**Comment by marcusmoore** [comment]
Thanks for reporting this @milosdelsystems.

I have a PR up with a fix here #14256. You can keep an eye on when it is merged.

**Comment by marcusmoore** [comment]
PR is merged. Gonna close this.
