### ISSUE TITLE
[Feature Request]: Add option to deactivate expected checkin notifications for users (not for admins) in general settings

### ISSUE THREAD

**Issue by Support-AEI** [grokability/snipe-it#14230]
### Is your feature request related to a problem? Please describe.

As far as I understand, SnipeIT always sends out E-Mails to the Admin and User affected when the check-in of an asset is expected or overdue. This is something we especially do not want in our environment.

The current installed version of SnipeIT is 6.2.3.

### Describe the solution you'd like

I would like to be able to decide if the user should be notified by checking or unchecking a checkbox in the general settings.
I built this in our test environment without translations and manually created the column in the settings table.
If you wish, I can provide you with my code.

**Comment by snipe** [comment]
You would just configure your cron/scheduled tasks accordingly, and leave that one out. https://snipe-it.readme.io/docs/configuring-alerts-backups

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuring-alerts-backups">Configuring Alerts & Backups</a></strong></div><div>Starting from Snipe-IT v3.0, all automated tasks are handled via the scheduler. To set a cron job to run every minute to ping the scheduler:Shell * /path/to/php /path/to/artisan schedule:run &gt;&gt; /dev/null 2&gt;&amp;1 The scheduler already knows how often it should trigger the individual tasks, ...</div></blockquote>

**Comment by Support-AEI** [comment]
Thanks for the quick answer, but when I deactivate that cronjob, neither the Administrator nor the User gets an email that an asset is about to expire. However, the Admin should still get an E-Mail; I only want to deactivate the E-Mail for the user with that setting.

**Comment by linkos76** [comment]
Hi, I had the same problem and found a solution after finding this thread.

Edit the file `app/Console/Commands/SendExpectedCheckinAlerts.php` and comment or delete the lines **54-59**:
```php
            if ($asset->assignedTo && (isset($asset->assignedTo->email)) && ($asset->assignedTo->email!='') && $asset->checkedOutToUser()) {
                $this->info('Sending User ExpectedCheckinNotification to: '.$asset->assignedTo->email);
                $asset->assignedTo->notify((new ExpectedCheckinNotification($asset)));
            }
        }
``` 

This disables the loop sending out notifications to users.
