### ISSUE TITLE
Error unable to load display data

### ISSUE THREAD

**Issue by hotrungtin** [grokability/snipe-it#14258]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

"Hello everyone!

I am currently experiencing an issue with the Snipe-IT application. The problem occurs when I select a category; the webpage takes a significant amount of time to load, yet it doesn't display the list for me to choose from. The server's CPU and RAM are well-configured, ruling out server configuration issues. Could you please provide guidance on resolving this issue? I appreciate your assistance greatly.

Thank you very much!"

![screenshot_1707845235](https://github.com/snipe/snipe-it/assets/159102241/7879db2c-1572-46fc-86a1-fd43951cd334)

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Bug

### Screenshots

![screenshot_1707845235](https://github.com/snipe/snipe-it/assets/159102241/e6a5d5f2-97e2-4a78-ae8a-756657e084f6)

### Snipe-IT Version

v6.2.2 build 11714 (ga95fae0e9)

### Operating System

Ubuntu 20.04 LTS

### Web Server

Apache

### PHP Version

7.4.33

### Operating System

Win 10

### Browser

Chorme

### Version

121

**Comment by snipe** [comment]
We'd need to see what's in your browser's console and app error logs.

**Comment by hotrungtin** [comment]
Hi everybody!
Where do I see app error logs? While the system still works, it only has slow data loading in the drop-down list.
Can anyone guide me on how to proceed and what data to provide?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by hotrungtin** [comment]
Hi everybody!
I have made instructions and exported the logs, thanks for everyone to take a look. I'm wondering if it could be because I upgraded to SSL Let's Encrypt?

Step 2: Enable your browser's error console : ![error1](https://github.com/snipe/snipe-it/assets/159102241/d818166a-98a4-4333-8378-886f1deec768)

Step 3: Check your app and server logs File log: [laravel.log.docx](https://github.com/snipe/snipe-it/files/14346135/laravel.log.docx)

**Comment by hotrungtin** [comment]
Hi everybody!
I turned off the ssl certificate and everything worked normally again
Can anyone explain it to me?
![image](https://github.com/snipe/snipe-it/assets/159102241/0993cb32-8843-4e45-a0a7-0cfa4403068a)

**Comment by snipe** [comment]
We use Let's Encrypt (and are a sponsor of them) for the hosted product, so LE definitely shouldn't be the issue. Can you confirm that your APP_URL is using https?

**Comment by hotrungtin** [comment]
Thank you everyone for your help.
  I summarize the cause of my error as follows:
- I did not adjust the APP_URL to use https which resulted in the data not being able to be loaded
Handle:
- I have adjusted the APP_URL and updated the SSL again

**Comment by snipe** [comment]
Does that mean your issue is resolved?

**Comment by hotrungtin** [comment]
My problem has been resolved. I thank everyone who supported me!
