### ISSUE TITLE
Deploy to Heroku button doesn't work

### ISSUE THREAD

**Issue by lewisstancer** [grokability/snipe-it#14266]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When deploying to Heroku using the button from the GitHub README, the following error is shown

![image](https://github.com/snipe/snipe-it/assets/54379286/39618388-e1ac-4613-a24d-14eb2090c804)

### Reproduction steps

1. Click deploy to heroku
2. Fill out required fields
3. Click Deploy app
4. Error is shown within a few seconds

### Expected behavior

App should deploy to heroku

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/54379286/022849e2-526d-4f79-86bb-89fc3079bd69)

### Snipe-IT Version

Heroku

### Operating System

Heroku

### Web Server

Heroku

### PHP Version

Heroku

**Comment by snipe** [comment]
I'm not super shocked by that, as that button was added back before Heroku took away their free tier. Not sure how it works these days.

**Comment by lewisstancer** [comment]
I don't know how these buttons are made but should just be a case of changing the dyno tier? Happy to pay for whatever needs to be integrated for the simplicity of pushing to Heroku.

Might be worth having an option without a mysql database and then adding the necessary environment variables to the deployment as I would probably use my own sql server anyway

**Comment by snipe** [comment]
I honestly haven't used Heroku in a million years, so I have no idea how those buttons are made or if there's something else that needs to be done to get them to work on the dyno tier tbh. If you can figure it out, I'd be happy to look at a PR tho.

> Might be worth having an option without a mysql database and then adding the necessary environment variables to the deployment as I would probably use my own sql server anyway

You can use sqlite if you want to, but without any kind of database, you're never going to be able to get through the QuickStart.
