### ISSUE TITLE
CSV Importing Blank Into Assets

### ISSUE THREAD

**Issue by lpegios3** [grokability/snipe-it#14273]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi team,

I am currently facing an issue when attempting to import assets to our instance of Snipe-IT.

When I try to import an asset from a CSV file, Snipe-IT recognises all the Import Fields, but when selecting the Import button, it returns the message "Success: Your file has been imported", but the asset from the CSV does not appear in the asset list. I've attached some screenshots, I want to import the device labelled "NB-03".

In addition, if I select another category to import, such as Consumables instead of Assets, it imported to the Consumable category just fine, it appears to only be an error when importing to the Asset category. 

I am running this in docker on an Ubuntu Server 22.04 VM. The logs don't get created either, the folder is completely blank apart from a .gitignore file.

Any assistance would be appreciated. Thanks.

### Reproduction steps

1. Create CSV file with the assets I wanted to add to the Asset list in Snipe-IT by following the documentation.
2. Goto Import on the web portal and upload the CSV file.
3. Upload works fine, check the Map Import Fields, it all matches.
4. Select Import.
5. Asset from CSV does not get imported even though a Success message appears.

### Expected behavior

Expected the asset entered from the CSV to import into the Snipe-IT DB and appear on the webpage.

### Screenshots

![Snipe-IT import page](https://github.com/snipe/snipe-it/assets/43634613/2b9f2547-b3d0-4bf4-bb36-168942399e3a)
![Snipe-IT asset page - nothing imported](https://github.com/snipe/snipe-it/assets/43634613/de7ad47a-27d6-4c17-8514-bdff8ebd8670)

### Snipe-IT Version

v6.2.4-pre build 12343 (gb23ce6cfc)

### Operating System

Ubuntu 22.04.3 LTS

### Web Server

Apache I believe (whatever is used in the docker image)

### PHP Version

8.1.26

### Browser

Firefox

### Error messages

```shell
Unless I'm just unaware of where the logs or error messages are, I cannot view any errors. 

And import is disabled on the demo.
```

### Additional context

- Fresh install of Ubuntu on a VM.
- Snipe-IT is being run in Docker and was launched with docker-compose using the .env.docker file grabbed from the github repository.
- No other issues, everything has been smooth so far.
- Haven't edited any database information but logged into the database to see if the asset was imported and it was not.

**Comment by snipe** [comment]
> Unless I'm just unaware of where the logs or error messages are, I cannot view any errors. 
https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by lpegios3** [comment]
Hi,

As mentioned the log folders are completely blank (see attached screenshot). I was referring to not viewing any errors after enabling APP_DEBUG on the web page.

I've had set up the logs in a separate volume instead.

Thanks!

![Snipe-IT logs](https://github.com/snipe/snipe-it/assets/43634613/d9d65ddf-b2bb-454a-aa62-b2b8a40354fa)

**Comment by lpegios3** [comment]
Hi everyone,

I did not realise that the Asset Tag had to be a unique value.

After updating the Asset Tag in the CSV to another value it imported just fine.

Please disregard. Thanks.
