### ISSUE TITLE
Icons missing from manufacturers tab

### ISSUE THREAD

**Issue by misilot** [grokability/snipe-it#14282]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If you go to https://demo.snipeitapp.com/manufacturers you see there are icons for the different Manufacturers. 

How do you get these for older sites that have had manufacturers there for many versions, before they were added into the code?

### Reproduction steps

1. Have old version  of Snipe-IT with Dell, HP, Lenovo, Apple, etc already exsiting
2. Go to the Manufacturers list, and see that the known metadata like support url, icon, etc... do not show up and you have to add them by hand. 
3.
...

### Expected behavior

Populate existing records with updated data if null?

### Snipe-IT Version

6.3.1

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8

**Comment by snipe** [comment]
Logos for manufacturers have been available for 6+ years (#4320). There is no metadata version of this, you'd have to edit them manually and upload an image.

**Comment by misilot** [comment]
So _should_ they have shown up automatically with logos? I know we haven't had Snipe-IT that long? Just trying to figure out what we might have done. Thanks!
