### ISSUE TITLE
Can´t upload pictures for Assets/Models with docker-compose

### ISSUE THREAD

**Issue by marcwbbstr** [grokability/snipe-it#14287]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Today, i updated SnipeIT from Version v6.3.0 to Version v6.3.1 - build 12672 (master).

As soon as i try to upload a image im getting a 500 - Server Error.  Without the debug mode i cannot see any entrys in the laravel.log, access.log or the error.log 

### Reproduction steps

1. Select a Asset or Model
2. Try to upload an image

### Expected behavior

Image should be visible in the Asset/Model

### Snipe-IT Version

v6.3.1 - build 12672 (master)

### Operating System

snipe/snipe-it:v6.3.1-alpine

### Web Server

Apache 

### PHP Version

8.1.26

### Operating System

Windows

### Browser

Brave

### Version

v1.62.165 (Feb 14, 2024)

### Error messages

```shell
https://flareapp.io/share/J7ox8oZ5

Output from php -m:

/var/www/html # php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
gd
hash
iconv
igbinary
json
ldap
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
redis
Reflection
session
SimpleXML
sockets
sodium
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zend_test
zip
zlib

[Zend Modules]
```

**Comment by abinpbiju** [comment]
@marcwbbstr 
If you are running the latest Docker Container
We need to add/install this module first inside the container (I am using Portainer to run commands inside the container)
The command is `apk add --upgrade php81-exif`

After that, Uncomment these two lines under `/etc/php81/php.ini`

- extension=mbstring 
- extension=exif
this should fix your issue

**Comment by marcwbbstr** [comment]
> @marcwbbstr If you are running the latest Docker Container We need to add/install this module first inside the container (I am using Portainer to run commands inside the container) The command is `apk add --upgrade php81-exif`
> 
> After that, Uncomment these two lines under `/etc/php81/php.ini`
> 
> * extension=mbstring
> * extension=exif
>   this should fix your issue

Thanks! Solution helped me. After the steps above just restart docker and everything seems to work fine.
