### ISSUE TITLE
Cannot Upload Images

### ISSUE THREAD

**Issue by abinpbiju** [grokability/snipe-it#14292]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am running SnipeIT on a Docker Container, When uploading images anywhere it's throwing an error 
Reading Exif data is not supported by this PHP installation

### Reproduction steps

1. Try uploading an Image to Manufacturer Logo 
2.
3.
...

### Expected behavior

Should upload without any issues

### Snipe-IT Version

6.3.1

### Operating System

Ubuntu

### Web Server

NGINX

### PHP Version

8.1

**Comment by snipe** [comment]
Which docker are you using?
