### ISSUE TITLE
API - Data couldn’t be read because it isn’t in correct format

### ISSUE THREAD

**Issue by connordexter** [grokability/snipe-it#14294]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Using the api to connect an IOS App (Snipy Assets) but on this install/database I get the error message saying data isn’t in correct format. I can connect and see assets on another installation, aswell as on this install via web UI. 

### Reproduction steps

1.
2.
3.
...

### Expected behavior

I have tested this by restoring a backup from another snipeit install and I can access the API on this installation, which makes me think there’s some missing or invalid data

### Snipe-IT Version

6.31

### Operating System

Debian

### Web Server

Apache

### PHP Version

7.4.33

**Comment by snipe** [comment]
We don't know anything about the iOS app, so you might need to take it up with the developers there.
