### ISSUE TITLE
Does PHP version still need to be below 8.1.2?

### ISSUE THREAD

**Issue by CMCLAuto** [grokability/snipe-it#14305]
### Is your feature request related to a problem? Please describe.

The server [installation documentation](https://snipe-it.readme.io/docs/requirements) requires that PHP should be below v8.1.2.

### Describe the solution you'd like

Meanwhile the upcoming Snipe-IT v7 upgrade will require PHP to be at least v8.1, so I'm wondering if I need to hunt down an old PHP v8.1.0 installer.

### Describe alternatives you've considered

Is the documentation up to date?

### Additional context

When upgrading from Snipe-IT v6.3.0 to version v6.3.1 I did notice the upgrade script is merely checking to see if PHP is below v8.2.0, so I'm pretty sure someone will tell me 8.1._anything_ is fine and I'm just being paranoid. Which would be just fine! I just really don't want to install something the documentation says not to on the off chance it hoses everything.

**Comment by snipe** [comment]
IIRC, anything 8.1.x should be okay for current and next versions. Current doesn't work on 8.2 because of dependencies.

**Comment by CMCLAuto** [comment]
Ok, cool! I'll grab the current v8.1.27 and see how it goes. Thanks!

**Comment by CMCLAuto** [comment]
Well, v8.1.27 works apart from the _/admin/backups_ page suddenly throwing 500 errors, but a quick search indicates that's a config problem on our end. Just have to figure out which one.
