### ISSUE TITLE
[Feature Request]: Add license groups to collect several licenses for one main topic

### ISSUE THREAD

**Issue by henriklue** [grokability/snipe-it#14310]
### Is your feature request related to a problem? Please describe.

When I want to add a lincense with more than 1 seat, for example 10 seats, i dont have the opportunity to add the keys to a specific seat. This would help to clean up licenses in the system

### Describe the solution you'd like

A License "group" of some kind, Windows 10 License - Seat 1 : Key 1 ; Seat 2 : Key 2 ; ....

**Comment by snipe** [comment]
Duplicate of https://github.com/snipe/snipe-it/issues/13946
