### ISSUE TITLE
Pre-flight setup page not loading

### ISSUE THREAD

**Issue by NickNck** [grokability/snipe-it#14326]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi all,

I am getting problems to load the pre-flight setup page after trying to install the latest version of snipeit from scratch after downloading from the "releases" section. I am using WAMP to host it on windows 10. It is using apache 2.4 and PHP 8.1.27. After following the steps to setup everything, I am not able to load the pre-flight page because it keeps jumping to the "localhost/setup" URL. I have double checked all requirements by enabling the required php extensions, and i even ran the php requirment check from the common issues page and everything was successful. I have even double checked the mapping of the APP URL in the .env file and it is pointing correctly to http://localhost/snipeit/public" path. But still it keeps jumping to the localhost/setup link and fails to load anything. The App key was also generated successfully. I have read others getting similar issue but their comments are not helpful in solving this. I really appreciate the help from anyone.

### Reproduction steps

1. Download latest release
2. Install wamp and composer
3. Download requirements via composer
4. Configure .env file and map the correct URL 
5. Proceed to path defined in URL
...

### Expected behavior

I expect the preflight page to load but it doesnt and it keeps landing to localhost/setup

I would assume probably it should land on something like http://localhost/snipeit/public/setup

I have tried the link http://localhost/snipeit/public/setup to see what will happen but i get the 500 server error.

### Snipe-IT Version

6.3.1

### Operating System

Windows 10

### Web Server

Apache 2.4

### PHP Version

8.1.27

### Operating System

Windows 10

### Browser

Google

### Additional context

This is a fresh install from the latest release section and copied to wamp www root folder

**Comment by snipe** [comment]
> I have even double checked the mapping of the APP URL in the .env file and it is pointing correctly to http://localhost/snipeit/public" path

My guess would be that your `APP_URL` is misconfigured in your `.env` file. [Per the documentation](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings), the APP_URL should be the complete URL to your Snipe-IT installation, *including* the `http://` (or `https://` if you're running over TLS.)

<img width="795" alt="Screen Shot 2022-07-28 at 11 35 47 PM" src="https://user-images.githubusercontent.com/197404/181698021-de470225-4865-4786-bd48-9a9cdf2399d2.png">

**Comment by NickNck** [comment]
The app URL in the env file seems to be correct as its http://localhost/snipeit/public

Its running locally on one windows 10 machine, so there is no ssl

**Comment by NickNck** [comment]
Managed to solve the issue. Turns out it was something silly due to windows view settings. Apparently my windows view setting has been showing the targeted filetype ".env" as the filename this whole time! And it was still in the .example format and my windows view settings was not configured to show the file type.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
