### ISSUE TITLE
[Feature Request]: Requestable Assets select Date/Time Range at Request

### ISSUE THREAD

**Issue by RoadrunnerBF** [grokability/snipe-it#14338]
### Is your feature request related to a problem? Please describe.

Hello together - at the moment - when a user requests a Asset you cannot set a TimeRange - only a Administrator can adjust the Time and Date and deploy it to user. We always must contact the user to know the TimeRange ..

### Describe the solution you'd like

At the Request Site - after clicking Request - a new Site appears with Date/Time Fields for exact planning from Asset.

**Comment by Akhun-Delar** [comment]
https://github.com/snipe/snipe-it/issues/5081

**Comment by snipe** [comment]
Duplicate of https://github.com/snipe/snipe-it/issues/5081
