### ISSUE TITLE
Instructions on how to perform full recovery of backup.

### ISSUE THREAD

**Issue by J1MP123** [grokability/snipe-it#14353]
### Is your feature request related to a problem? Please describe.

Hello does anyone have STEP by STEP guide on how to restore a backup from a .zip file backup? Managed to make one before SSD died completely. I don't have configuration files but only .zip which was downloaded at the last minute. Tried to recover the backup in a fresh build of snipe but failed via 500 error Snipe WIKI is not helpful as well. Any help would be appreciated. Thanks.

### Describe the solution you'd like

I would like this guide- https://snipe-it.readme.io/docs/backups to be updated for hobbyists. To simply understand how to recover a backup Without any config file backed up (only zip available from the last backup). Snipe is being cryptic in Reddit posts saying you need to disable bits of config or code but nobody mentions where the code can be located or steps to be taken, this is critical in my opinion. This would help many people. (not everyone is a networking genius and working on these systems daily I find this software cool and I like to use it. Really need some help and would appreciate any info .) 

### Describe alternatives you've considered

Tried to check all sources such as Youtube, Reddit, and GitHub still failed with error 500.

### Additional context

Please help me, and tell me step-by-step recovery options as I'm starting to give up. I know it's my bad that I did not make a full image backup.. but I thought zip would help and be enough just in case..I

**Comment by snipe** [comment]
>  I don't have configuration files but only .zip which was downloaded at the last minute.

This was a zip generated by Snipe-IT, or a zip of the entire application code?

> Tried to recover the backup in a fresh build of snipe but failed via 500 error

You'd need to tell us what the 500 error actually is. https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by J1MP123** [comment]
Hello Snipe, thanks for reading this.

1. I got a zip file from backup i made in snipe IT, exported to desktop and put on usb. next day drive was not booting so could not get any more information from it. 
2. built a new image and imported backup .zip file
![image](https://github.com/snipe/snipe-it/assets/93220034/2edffc0e-4434-4a8e-b384-88f4c1f83e78)

![image](https://github.com/snipe/snipe-it/assets/93220034/ff485e3f-edf7-4fdc-9bb0-15e2cb154582)


Found a lavrel.log
[lavrel.log](https://github.com/snipe/snipe-it/files/14466683/lavrel.log)

The log does not look good, it was so long I had to upload the file itself rather than snippet or pastebin.. too large.

Any chance of me recovering my asset backups? :(

**Comment by J1MP123** [comment]
> > I don't have configuration files but only .zip which was downloaded at the last minute.
> 
> This was a zip generated by Snipe-IT, or a zip of the entire application code?
> 
> > Tried to recover the backup in a fresh build of snipe but failed via 500 error
> 
> You'd need to tell us what the 500 error actually is. https://snipe-it.readme.io/docs/getting-help
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/f5ec2eb7e2274ad22d196821472e0438dcbd923f06ab2d8cbeb0ae2113c74df8/68747470733a2f2f736e6970652d69742e726561646d652e696f2f66617669636f6e2e69636f">Snipe-IT Documentation**[Getting Help](https://snipe-it.readme.io/docs/getting-help)**If you're having trouble setting up Snipe-IT, don't worry!

Any advice? :(

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by J1MP123** [comment]
BUMP please

**Comment by snipe** [comment]
> Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.users' doesn't exist (SQL: select * from `users` where `id` = 1 and `users`.`deleted_at` is null limit 1) in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:712


Your database doesn't have the tables it's supposed to have. Check the zip, make sure the sql file is in there, and import it manually if you have to.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
