### ISSUE TITLE
Ability to send emails without authentication

### ISSUE THREAD

**Issue by dmitrygribenchuk** [grokability/snipe-it#14358]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello. I try to configure mail notifications via google-relay. It not use login/password. 

My configuration is:
        MAIL_HOST=smtp-relay.gmail.com
        MAIL_PORT=25
        MAIL_ENCRYPTION=tls

But it's doesn't work. Is it possible to provide an option to use this way?

### Reproduction steps

1. Configure mail settings
2. Send test mail
3. See an error

### Expected behavior

Ability to send messages without login/password if it is acceptable by smtp

### Snipe-IT Version

6.3.1

### Operating System

Debian

### Web Server

apache

### PHP Version

8.1.2

### Operating System

Ubuntu

### Browser

Firefox

### Version

125.0a1

### Error messages

```shell
`message	'Failed to authenticate on SMTP server with username "${MAIL_ENV_USERNAME}" using 3 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. For more information, go to\r\n535 5.7.8 https://support.google.com/mail/?p=BadCredentials fj10-20020a05600c0c8a00b00412730977dasm213358wmb.30 - gsmtp\r\n". Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. For more information, go to\r\n535 5.7.8 https://support.google.com/mail/?p=BadCredentials fj10-20020a05600c0c8a00b00412730977dasm213358wmb.30 - gsmtp\r\n". Authenticator XOAUTH2 returned Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. For more information, go to\r\n535 5.7.8 https://support.google.com/mail/?p=BadCredentials fj10-20020a05600c0c8a00b00412730977dasm213358wmb.30 - gsmtp\r\n".'`
```

**Comment by marcusmoore** [comment]
Did you follow the steps [here](https://snipe-it.readme.io/docs/configuration#section-using-gmail) and allow less secure apps? Some extra details in [this section](https://snipe-it.readme.io/docs/common-issues#unable-to-send-email-using-gmail) might be helpful as well.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
