### ISSUE TITLE
User broken after upgrade to Git

### ISSUE THREAD

**Issue by rosematcha** [grokability/snipe-it#14363]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After a Git upgrade, my admin user cannot log in because of an SQL error.

### Reproduction steps

1. Install and setup a local Snipe-IT server on Windows IIS.
2. Upgrade that setup to one based on Git.
3. Log in with an administrator account.

### Expected behavior

I expected to be able to log in to Snipe-IT with my administrator account.

### Screenshots

![snipe](https://github.com/snipe/snipe-it/assets/120700018/895127f6-0963-4e50-89a0-997f6e3adaed)

### Snipe-IT Version

6.3.1

### Operating System

Windows Server

### Web Server

IIS 10

### PHP Version

8.1

### Operating System

Windows 10

### Browser

Firefox

### Version

123

### Error messages

```shell
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'min_amt' in 'where clause' (SQL: select * from `licenses` where `min_amt` > 0 and `licenses`.`deleted_at` is null) (View: C:\inetpub\wwwroot\snipeit\resources\views\layouts\default.blade.php)
```

### Additional context

I've run a Snipe-IT installation on an IIS server for my organization for about a year now, and I wanted to upgrade it to a Git one so I could keep up-to-date. I followed Snipe's provided guide and it seems to be working fine for most users. However, whenever I try to log in to my admin account, I receive the above SQL error message seemingly about a missing column. I do not receive this message on my original install, and no other user receives this message. I reverted back to my backup install and it seems to now be working fine, but I'd like to eventually upgrade to a Git install. Please let me know if there's any additional info I need to provide, and thanks for your help!

**Comment by snipe** [comment]
Sounds like you didn't run migrations. https://snipe-it.readme.io/docs/common-issues#column-not-found

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues#column-not-found">Common Issues</a></strong></div><div>🚧Problem Installing/Upgrading?We've moved the the most common installation/upgrade issues to their own page. If you're having an issue installing or upgrading Snipe-IT, please check the Installation/Upgrading Issues page before opening a ticket on Github.Quick Tip: Handy Commands👍Many issues can b...</div></blockquote>
