### ISSUE TITLE
Mixed Content: The page was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint. This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by mladenrusev** [grokability/snipe-it#14368]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have encountered the problem in the title, when try to open any drop-down option, in the GUI it shows infinity loading and nothing in drop down.

This happenes after my Let's Encrypt Certificate expired, and even when i renew it, it still shows this error. Apparently some values/urls were changed somewhere permanently.

I have tried fixes from #10179  #7592 in .env file but they dont work for me.

### Reproduction steps

1. Everytime when try to open any drop-downs it shows this errors in console
2.
3.
...

### Expected behavior

Drop down to load properly.

### Screenshots

![Untitled](https://github.com/snipe/snipe-it/assets/162339218/46a90fd7-bd78-4ccf-a8ef-3255d70eeb90)

### Snipe-IT Version

 Version v6.3.1 - build 12672 (master)

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.27

**Comment by snipe** [comment]
My guess would be that your `APP_URL` is misconfigured in your `.env` file. [Per the documentation](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings), the APP_URL should be the complete URL to your Snipe-IT installation, *including* the `http://` (or `https://` if you're running over TLS.)

<img width="795" alt="Screen Shot 2022-07-28 at 11 35 47 PM" src="https://user-images.githubusercontent.com/197404/181698021-de470225-4865-4786-bd48-9a9cdf2399d2.png">

**Comment by mladenrusev** [comment]
@snipe its not this also. It is set properly, with https and no trailing slash. I read every line in .env file and try every possible option with no luck...

**Comment by snipe** [comment]
We only use the APP_URL to determine what your URL is - nothing in the code has changed as it relates to URLs. Only thing I can think of is if you're running your Snipe-IT through a proxy or something. It's very clearly trying to serve non-SSL urls to you, and we do not hardcode non-SSL (or SSL for that matter) anywhere in the code, since we have no way of knowing whether a user will be running this over TLS.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
