### ISSUE TITLE
Unable to install the latest version on Ubuntu server 22.04 LTS

### ISSUE THREAD

**Issue by Jeromeose** [grokability/snipe-it#14386]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

installation is blocked

### Reproduction steps

1. sudo ./install.sh

### Expected behavior

here is the log

Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
When working with _public_ GitHub repositories only, head here to retrieve a token:
https://github.com/settings/tokens/new?scopes=&description=Composer+on+snipeAT+2024-03-07+1614
This token will have read-only permission for public information only.
When you need to access _private_ GitHub repositories as well, go to:
https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+snipeAT+2024-03-07+1614
Note that such tokens have broad read/write permissions on your behalf, even if not needed by Composer.
Tokens will be stored in plain text in "/home/snipeitapp/.config/composer/auth.json" for future use by Composer.
For additional information, check https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth
Token (hidden):

### Snipe-IT Version

Latest

### Operating System

Ubuntu Server

### Web Server

Your's

### PHP Version

Your's

**Comment by snipe** [comment]
Did you actually create those tokens?

**Comment by Jeromeose** [comment]
Hi, I have already installed Snipe-IT on several occasions, and I do not recall having to create tokens. I simply ran the install.sh script. Is it necessary to create tokens beforehand?

**Comment by snipe** [comment]
The install will pull from github, so you'll need to set up those tokens. Once they're set up on that server, you shouldn't have to create them again on that server.

**Comment by Jeromeose** [comment]
Can you provide me with the documentation page that describes how to do it?

**Comment by Jeromeose** [comment]
finaly i used this guide to install > https://www.rosehosting.com/blog/how-to-install-snipe-it-on-ubuntu-22-04/

<blockquote><img src="https://www.rosehosting.com/blog/wp-content/uploads/2023/10/how-to-install-snipe-it-on-ubuntu-22-04.webp" width="48" align="right"><div>RoseHosting</div><div><strong><a href="https://www.rosehosting.com/blog/how-to-install-snipe-it-on-ubuntu-22-04/">How to Install Snipe-IT on Ubuntu 22.04</a></strong></div><div>Master the installation of Snipe-IT on Ubuntu 22.04 with our guide. Simplify your IT asset management and boost productivity today!</div></blockquote>

**Comment by solange07** [comment]
Same issue Rocky 9, php v 8.2
