### ISSUE TITLE
[Feature Request]: Webhook and/or teams integration

### ISSUE THREAD

**Issue by MtSeymourTech** [grokability/snipe-it#14384]
### Is your feature request related to a problem? Please describe.

The only problem is that we have migrated from slack to teams. our company has left slack behind and it is not used at all anymore.

### Describe the solution you'd like

There is a slack integration in snipeit, but or company migrated away from slack and is now using strictly teams. I considered integration with our old slack channel and then sending out webhooks or some other way to get messages from slack to our teams IT channel, but I thought I'd ask here first if maybe im missing something about snipe-it where these features are already integrated and im just missing them?  Times have changed and slack is no longer the only way to notify. I think it might be ideal if webhooks were supported.

Either way, the software is excellent, and while we need a full time asset management manager, our IT team gets good use out of this software whenever we do use it! Thank you very much for all the hard work that has been put into this project!

### Describe alternatives you've considered

going from current snipeit slack integration ->webhook or other hack to teams channel. Not ideal. 

### Additional context

Snipe-IT versionv5.3.8 build 6619 (g1ef336a08)Software License[AGPL3](https://www.gnu.org/licenses/agpl-3.0.en.html)
PHP Version7.4.3-4ubuntu2.19Laravel Version6.20.29

**Comment by snipe** [comment]
This was introduced a while back. Upgrade your version of Snipe-IT to take advantage of the new features.

**Comment by MtSeymourTech** [comment]
excellent! thank you!
