### ISSUE TITLE
[Feature Request]:  Turkish character error when i type something /var/www/html/resources/views/users/ print.blade.php file.

### ISSUE THREAD

**Issue by mdedeoglu2** [grokability/snipe-it#14383]
### Is your feature request related to a problem? Please describe.

**/var/www/html/resources/views/users/ print.blade.php

I want to add Turkish text into it. When I add corrupt characters appear. It does not support Turkish language. How can I add text in Turkish language to this file? (Characters like şğiö appear corrupted.)**

### Describe the solution you'd like

/var/www/html/resources/views/users/ print.blade.php

I want to add Turkish text into it. When I add corrupt characters appear. It does not support Turkish language. How can I add text in Turkish language to this file? (Characters like şğiö appear corrupted.)

### Describe alternatives you've considered

/var/www/html/resources/views/users/ print.blade.php

I want to add Turkish text into it. When I add corrupt characters appear. It does not support Turkish language. How can I add text in Turkish language to this file? (Characters like şğiö appear corrupted.)
![bozuk karakterler](https://github.com/snipe/snipe-it/assets/162312737/dda53661-a11a-497c-a134-5cb1fbe00a5b)

**Comment by snipe** [comment]
We use translations in all of our emails, so if the regular translated text that comes with Snipe-IT that's translated into Turkish comes out normally, I'd think it might be something with how you're handling the file.

**Comment by mdedeoglu2** [comment]
I open the print.blade.php file with winscp and add text to it.

**Comment by snipe** [comment]
I'm unable to reproduce this locally.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
