### ISSUE TITLE
Label-Generator ignores CSS

### ISSUE THREAD

**Issue by MaOIT** [grokability/snipe-it#14382]
### Debug mode

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We previously used to format our Asset-Labels using CSS.
We then jumped to 6.3.2 and Labels are shown as PDF.

It seems the PDF-Generator ignores the CSS, so that our Labels are "broken".
With the new Label-Generator i am also unable to get the label anywhere close to what we need.

Our Labels are for 24mm-Brother-Tape.
We had QR-Code, Logo and ID.

![Labe before Update](https://github.com/snipe/snipe-it/assets/153716095/b1f092dc-3b37-4831-b1e3-dfa5c39dd8ce)

### Reproduction steps

1. Use CSS-code to format Labels in a version prior to label-generator-makeover
2. Generate a Label
3. Fancy!
4. Update to 6.3.2
5. Generate a Label
6. No formatting visible, Labels looks not as expected

### Expected behavior

Label-Generator (in setting old) should generate the Labels using CSS

### Snipe-IT Version

6.3.2

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Error messages

```shell
No Error-Message.
```

### Additional context

Upgraded

**Comment by snipe** [comment]
Already resolved on master.
