### ISSUE TITLE
Horizontal scrollbar does not scale correctly with window size

### ISSUE THREAD

**Issue by thetredev** [grokability/snipe-it#14399]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The horizontal scrollbar is fixed at a certain position and only shows up as soon as I scroll down to the end of the table view where it's programmatically located.

### Reproduction steps

1. Open a new browser window
2. Make the browser window much smaller, to say 1/3rd or 1/4th of your screen's width, and half of your screen's height (almost mobile-ish)
3. Navigate to your SnipeIT instance and login
4. Navigate to any table view, for example `/reports/activity`
5. Check for the horizontal scrollbar at the bottom (nothing's there)
6. Scroll all the way down to the vertical end of the table view (horizontal scrollbar is visible now)

### Expected behavior

The horizontal scrollbar should scale with window size. Meaning, it should not be fixed at a certain position, but _always_ be visible at the bottom of the browser window.

### Snipe-IT Version

v6.3.2

### Operating System

Debian host with Docker image from Docker Hub

### Web Server

NGINX

### PHP Version

8.1.2-1ubuntu2.14

### Operating System

Windows 10

### Browser

Google Chrome

### Version

122.0.6261.96

### Additional context

I think it's a UI oversight, but I'm not sure if fixing the issue is trivial, because the horizontal scrollbar of the table views are _inside_ the table, and don't come from the browser itself.

Google for example uses the browser's horizontal scrollbar and therefore scales it correctly according to its window size:
1. Make the browser window size the same as from step 2 of "Reproduction steps"
2. Navigate to https://google.com
3. Search for "test" or anything else really
4. Check the horizontal scrollbar at the bottom (it's visible because it's independent of the website content itself)

I doubt that changing the scrollbar to become the browser's own scrollbar should be used. That's probably a design decision you'd have to make on your end. On the other hand, the vertical scrollbar _is_ the one the browser provides, so there's that.

**Comment by snipe** [comment]
I don't think there's much we can do about that - I think it's a limitation of the JS library we use.

**Comment by thetredev** [comment]
Ah that makes sense. Feel free to close the issue should that be the case.

**Comment by snipe** [comment]
I honestly do wish we could fix this. I know it's not a Big Deal, but it's not as good of a user experience as we'd like. Our hands are just tied :(

**Comment by thetredev** [comment]
All good. Thanks for the info! Closing the issue.
