### ISSUE TITLE
[Feature Request]: demo password

### ISSUE THREAD

**Issue by mauro-miatello** [grokability/snipe-it#14405]
### Is your feature request related to a problem? Please describe.

hi, the last releases of chrome has started to alert users if they use a password found in a data breach
the demo password is password, so every time a user load a page a popup appears
![image](https://github.com/snipe/snipe-it/assets/11910225/b0f07bdf-2154-4411-800c-3fea58104616)

### Describe the solution you'd like

change the password in the demo installation

**Comment by snipe** [comment]
You can just disable it for the demo. https://www.reddit.com/r/chrome/comments/1avxxzh/comment/kregoim/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by snipe** [comment]
(I agree it's super annoying though, but we'd have to change the password in 100 places. This is really a chrome issue, not an us issue, and local development is a pain with it as well.)

**Comment by mauro-miatello** [comment]
understood, I supposed it was a easy change to do in the demo environment

**Comment by snipe** [comment]
I personally hate that they inflicted this without warning. I don't use Chrome very often, mostly when I need a fresh session when toggling between browsers to check permission changes on users, etc and it was making me bonkers. I don't want to disable it on every website I visit in Chrome, but the "every page load" thing is super obnoxious. They really should have an "ignore for this website" built into that nag screen.
