### ISSUE TITLE
Send Expiring Alert Email to defined assets' owners separately.

### ISSUE THREAD

**Issue by SuiMengwei** [grokability/snipe-it#14408]
### Is your feature request related to a problem? Please describe.

We deployed Snipe-it on the windows server, the current version is v4.9.2 - build 4352 (master), we updated all hardware assets and software licenses into snipe-it, and we have four teams are responsible for all items in snipe-it. For example, the user's laptop asset is managed by helpdesk team, the vmware license is managed by server team, we request if it is possible that helpdesk team will receive the expiring alert email for the laptop assets but not server team, server team will only receive the alert mail for vmware license expiring alert.

### Describe the solution you'd like

We request if it is possible that helpdesk team will receive the expiring alert email for the laptop assets but not server team, server team will only receive the alert mail for vmware license expiring alert.

**Comment by snipe** [comment]
> the current version is v4.9.2

Your version is 6+ years old. Please update and re-ask.
