### ISSUE TITLE
Country Drop Down - No Values

### ISSUE THREAD

**Issue by PP-JN-RL** [grokability/snipe-it#14418]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The drop down to select countries has no values on any page after updating MySQL to version 8.0
![image](https://github.com/snipe/snipe-it/assets/52716446/1c332a7b-b3fc-4e4d-a5e4-efdb772513b3)

### Reproduction steps

1. Add new supplier
2. Select country drop down

### Expected behavior

It should return a list of countries.

### Snipe-IT Version

v6.3.3 build 12903 (g0f63fa23e)

### Operating System

Rocky Linux 9 ( Docker)

### Web Server

Apache (Docker)

### PHP Version

8.1.2-1ubuntu2.14

**Comment by DTPhilEng** [comment]
I have the same issue. Can you please let me know what the fix is for this?

**Comment by snipe** [comment]
Please update to latest on master.
