### ISSUE TITLE
Replace "dev-master" for "arietimmerman/laravel-scim-server" package

### ISSUE THREAD

**Issue by jedi0606** [grokability/snipe-it#14419]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The project's composer.json specifies a dependency on arietimmerman/laravel-scim-server using dev-master. Relying on dev-master can lead to instability due to the dynamic nature of the master branch, potentially introducing untested changes and compatibility issues.

### Reproduction steps

1. Clone the repository.
2. Run composer install to install dependencies.
3. Notice the dependency resolution for arietimmerman/laravel-scim-server is pegged to dev-master.

### Expected behavior

Dependencies should be locked to specific, tagged versions to ensure stability and predictability. For instance, instead of dev-master, using a version constraint like ^0.6.7 (or the latest stable release) would be more appropriate. This ensures that all users of the library are working with a tested and stable version of the code, reducing the likelihood of encountering unexpected bugs or incompatibilities.

### Snipe-IT Version

6.3.1

### Operating System

Windows

### Web Server

Apache

### PHP Version

8.1

**Comment by uberbrady** [comment]
We are pointing to 'dev-master' on *our* fork of that package, which is under our control. I'd much rather use the upstream fork directly (and if we did do that, we'd definitely pick a fixed version for it), but we have some logging stuff that we need that they don't offer.
