### ISSUE TITLE
Can't Bulk delete location

### ISSUE THREAD

**Issue by laovong** [grokability/snipe-it#14428]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug
Hi Snipe-IT team,
I try to delete locations imported by sample-assets.csv file but not working.
After click Delete, message show as below and location still appear on Locations page:
"Warning: general.bulk.partial_success"

### Reproduction steps

1. Settings -> Locations
2. Select all locations (unselect my 2 locations) -> Bulk delete -> Go
3. View and confirm location to delete -> Delete
4. Auto go back to Locations page and show "Warning: general.bulk.partial_success" error, locations not deleted.

### Expected behavior

Selected locations should be delete.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/24601611/e8cddd30-8941-4586-a025-887aca538800)
![image](https://github.com/snipe/snipe-it/assets/24601611/cd1a4e51-7750-4a59-8abb-0e72612200a2)
![image](https://github.com/snipe/snipe-it/assets/24601611/47754974-9b48-478b-bc7b-552115d6ed64)

### Snipe-IT Version

v6.3.3 build 12903 (g0f63fa23e)

### Operating System

7.4.3-4ubuntu2.20

### Web Server

nginx version: nginx/1.18.0 (Ubuntu)

### PHP Version

PPHP 7.4.3-4ubuntu2.20 (cli) (built: Feb 21 2024 13:54:34) ( NTS )

### Operating System

macOS Ventura 13.5.2

### Browser

Google Chrome 122.0.6261.129, Firefox 123.0.1 

### Error messages

```shell

```

### Additional context

- Fresh install
- Install method: Git clone

**Comment by Godmartinz** [comment]
@laovong Good catch! I appreciate you bringing this to our attention. I've pushed a fix for this. It should be applied in our next release. Thank you 🙂
