### ISSUE TITLE
Snipe IT URL NOT Working

### ISSUE THREAD

**Issue by subait92** [grokability/snipe-it#14429]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Snipe it setup was successfully configured on my Ubuntu server.However, the URL is not working.It only works with local IP addresses or 120.0.1.1.I tried changing it to snipeit.example.com.It’s not working.Please let me know what’s wrong with my setup.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

![Screenshot from 2024-03-14 13-21-24](https://github.com/snipe/snipe-it/assets/159072609/fbe99142-28fa-493a-9bbb-a1c479b728af)
![Screenshot from 2024-03-14 13-18-45](https://github.com/snipe/snipe-it/assets/159072609/383895c4-d1bf-4659-abe1-e16206d62c12)

### Snipe-IT Version

6.3.3

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2

**Comment by laovong** [comment]
https use port 443, on your configure is 80

**Comment by subait92** [comment]
I tried both 443 and 80 ports.But it isn't working and is using http/https.But there's no improvement.

**Comment by mcaser** [comment]
I have similar issue. I setup following the instructions from the manual, but after configurations I opened the www.mydomain.com or IP, I got this , can anyone help?
![d8a101b9e3f5752ee7e1445153d894d](https://github.com/snipe/snipe-it/assets/29187748/131721b8-e7d9-48d7-a147-394b3d1bf4ae)

**Comment by laovong** [comment]
@mcaser  Please refer this https://github.com/snipe/snipe-it/issues/12270

**Comment by laovong** [comment]
@subait92 If you want access Snipe IT from external, you need public it through your firewall,...
If you want access Snipe IT from internal using url, you need modify host file to mapping domain with Ubuntu server IP address.

**Comment by mauro-miatello** [comment]
doesn't work is a no meaning message, post a screenshot

**Comment by mcaser** [comment]
> @mcaser Please refer this #12270

Got u, checking and trying,
Thank u

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
