### ISSUE TITLE
Created Categories are not shown to be selected while creating asset model

### ISSUE THREAD

**Issue by skygunner** [grokability/snipe-it#14422]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After installation and created a handful of 20 categories, I went to create asset models.
But while choosing category for the asset model, I can not see thos categories just created. 

### Reproduction steps

1. docker installation
2. create some random categories
3. create asset model, try to select the categories just created
...

### Expected behavior

created categories should be shown and selecctable

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/84759/5cc6a6dd-627f-42b7-824d-31777c480acc)

![image](https://github.com/snipe/snipe-it/assets/84759/458b2054-692c-48c7-a9c0-92dac9f2b31a)

### Snipe-IT Version

 v6.3.3 - build 12903 (master)

### Operating System

docker Linux 6.1.74-Unraid

### Web Server

Nginx 1.22.1

### PHP Version

8.1.22

### Operating System

Windows 10

### Browser

Chrome 122.0.6261

**Comment by snipe** [comment]
Are you sure the categories you created are asset categories? Can you reproduce this on the demo? The screenshot is kind of helpful, but I have no way of knowing which of those categories you were trying to select on the new asset model.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by xklusiv** [comment]
<img width="753" alt="Screenshot 2024-04-30 at 15 38 54" src="https://github.com/snipe/snipe-it/assets/32897876/eff02eaa-6f3d-4a05-ab7e-a79d2aada33a">
Issue happens that drop down is empty

**Comment by snipe** [comment]
@xklusiv without error logs, we’re not going to be able to help you. Check that your APP_URL is correct and report back with browser and app logs.

**Comment by xklusiv** [comment]
Alright let me check thanks
