### ISSUE TITLE
Snipe-It doesn't update the User in an Asset when I change it in excel and then Import it 

### ISSUE THREAD

**Issue by Zlain8** [grokability/snipe-it#14425]
### Debug mode

- [X] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

So, I've discovered a bug or maybe it's working as intended but what happens is that I use Snipe-It in my company and I use it to storage Assets like Laptops, Monitors etc... I put everything on an Excel and then I import it to Snipe-It, the problem is that when I deploy an Asset to a User and then later change the User of that Asset in Excel, I import it to Snipe-It but it doesn't change the User so it maintains the same User even if it's changed in Excel, is there a way to fix this or am I doing something wrong?

### Reproduction steps

1. Create Excel with Assets attributed to Users
2. Import to Snipe-It
3. Update the Excel changing the Users of certain Assets
4. Import to Snipe-It Again
5. See that Users didn't change

### Expected behavior

I would expect it to change the User of that Asset and not stay the same.

### Snipe-IT Version

v6.0.10

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows 11

### Browser

Brave

**Comment by marcusmoore** [comment]
Hi @Zlain8, which field(s) are you using for the user? Username, First/Last, or Email? Maybe a combination?

**Comment by Zlain8** [comment]
> Hi @Zlain8, which field(s) are you using for the user? Username, First/Last, or Email? Maybe a combination?

Hi, thank you for your fast response, I am using only username.

**Comment by marcusmoore** [comment]
@Zlain8 do you have the `Update Existing Values` checkbox checked?

![Update Existing Fields checkbox](https://github.com/snipe/snipe-it/assets/1141514/85866215-a5de-45a3-a76d-5679ce6fa230)

**Comment by Zlain8** [comment]
Yes I do, I allways do that, can it have to do with Snipe-It not being on the most recent version?

**Comment by marcusmoore** [comment]
@Zlain8 ah I totally missed the version number you're on. That is most likely the case. There have been a lot of improvements to the importer since v6.0.10 and if you update to the latest version you should be able to re-assign assets by username.

I'm going to close this but please ping me if you still have issues after updating.
