### ISSUE TITLE
Import issue, user, department and company

### ISSUE THREAD

**Issue by Omidoshegy** [grokability/snipe-it#14420]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We have Snipe-IT Version v6.3.2 - build 12834 (master). When we import users and departments, the company table is not updated. This means that when I log in as a regular user in another company, I do not see my departments even though we have specified the company for the users we import in the import.csv. This worked in older version before (V6.2.3), but with the latest update, this problem has occurred.

### Reproduction steps

1.Tried new install on virtual server Version v6.3.3. Same behavior 
2. I have tried checking the box to update existing with no luck.
3. I tried to only import department and company. But it said missing id.
...

### Expected behavior

Connecting department too Company through CSV import

### Snipe-IT Version

Version v6.3.2 - build 12834 (master).

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

Latest

<img width="530" alt="Skärmbild 2024-03-12 182954" src="https://github.com/snipe/snipe-it/assets/99632806/49b25175-4084-492d-b7c0-b08ea7b87d82">
[test_import.csv](https://github.com/snipe/snipe-it/files/14576462/test_import.csv)

**Comment by huifsa** [comment]
I have a similar issue but with the "Department" field. I did a fresh import of users that included first name, last name, email, full name, location, telephone number, title, employeeid, company, department, and manager first name and last name.

All the fields except department were updated for the users unless the department already existed. The departments were however created. I tried running the import again and selecting "update existing values" and the department still won't get added.

I am using the docker container and am on version 6.3.3 - build 12903

**Comment by huifsa** [comment]
Well I think I figured the cause of my issue. When I imported the users, it set the start and end date to negative values.
![image](https://github.com/snipe/snipe-it/assets/164399707/d663a00b-9cd3-42f0-bf97-210f968f003a)

After editing some users and clearing that out, I re-ran the import, and the department listed in the import was updated for the modified users. 

I then tried running a new import with the start date and end date included but blank (the fields in the import were ""), and the values were still negative.

Finally, I updated the start date to be when the user account was created in yyyy-MM-dd format, and set the end date to 2034-03-24 and re-ran the import with the updated dates. When I did that, all the departments populated as expected.

**Comment by snipe** [comment]
Hi [Omidoshegy](https://github.com/Omidoshegy) - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
