### ISSUE TITLE
[Feature Request]: Be able to preconfigure SAML/LDAP/extra configs directy from .env file

### ISSUE THREAD

**Issue by luciano-buono** [grokability/snipe-it#14434]
### Is your feature request related to a problem? Please describe.

It would be helpful to be able to completly configure SnipeIT directly from `.env` file, instead of having to configure via GUI settings like LDAP/SAML, or also PreFlight configs like creation of 1st user

### Describe the solution you'd like

Add more settings to .env file that allow to preconfigure SnipeIT from sracth more easily:

LDAP_XX variables
SAML_XX variables
INITIAL_USER variables
...

**Comment by snipe** [comment]
I'm not really sure what problem this solves though? Seems like it would be quite a lot of extra code for a narrow use case.

**Comment by luciano-buono** [comment]
It would allow a completly configuration using code and not Clickops.
In case you want to documentate and replicate someone else settings, it can be done easily instead of looking at the GUI

**Comment by snipe** [comment]
Most people don't want that though, and it would make it much harder for us to support our hosted customers and self-hosted people who don't have access to the env file for internal reasons.
