### ISSUE TITLE
Missing snipeit/vendor while installing via script

### ISSUE THREAD

**Issue by thatradacat** [grokability/snipe-it#14448]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, 
While installing snipe-it last week everything went fine. No errors during installation.
Now i'm trying to install snipe-it for production and snipeit.sh is failing on chgrp /var/www/html/snipeit/vendor
Could it be possible that the vendor directory got removed from the repository? (While looking through the master branch i couldn't find it.) My test installation from last week does have the directory.

### Reproduction steps

1. Install snipeit via the install.sh
2. go through the installer until "Running composer"

### Expected behavior

I expected composer to run normally and finish setting up my SMTP server and the rest of the installation.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/155555043/3199fbe0-3839-4ac6-80e4-01fa45657fe6)

### Snipe-IT Version

6.3.3

### Operating System

RHEL 8.7

### Web Server

Apache

### PHP Version

7.4

### Error messages

```shell
Debug not available considering its during installation
```

### Additional context

Its a fresh install using the install.sh method

**Comment by snipe** [comment]
The vendor directory isn’t stored in the repo, it gets created/populated by composer

**Comment by thatradacat** [comment]
> The vendor directory isn’t stored in the repo, it gets created/populated by composer

Ah okay, any idea on what the fix could be? Im not at all familiar with composer so im at a loss :sweat_smile:

**Comment by thatradacat** [comment]
Fixed! Something with my PHP configuration was somehow messed up.
