### ISSUE TITLE
Snipe IT cannot Import data "Asset" 

### ISSUE THREAD

**Issue by ITTGNH** [grokability/snipe-it#14452]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I press button import data and received message "Your file import is complete, but we did receive an error. This is usually caused by third-party API throttling from a notification webhook (such as Slack) and would not have interfered with the import itself, but you should confirm this." I don't know how to fix this problem

### Reproduction steps

1. 
2.
3.
...

### Expected behavior

I cleared history and cached in Chrome

### Screenshots

![H1](https://github.com/snipe/snipe-it/assets/163986401/83160240-98d1-4ae2-b187-020e2e3dedc9)

### Snipe-IT Version

v6.1.0 build 10161

### Operating System

Windows Server 2012

### Web Server

IIS

### PHP Version

7.4.29

### Operating System

Windows Server 2012

**Comment by laovong** [comment]
@ITTGNH update your Snipe-IT app to lastest version to fix this.
