### ISSUE TITLE
[Feature Request]: .AVIF support

### ISSUE THREAD

**Issue by it-native** [grokability/snipe-it#14460]
### Is your feature request related to a problem? Please describe.

As a user I want to add pictures of asset models. A lot of pictures of products are nowadays in AVIF file format

### Describe the solution you'd like

therefore it would be nice to be able to use and upload those images to Snipe-IT.

**Comment by snipe** [comment]
Can you upload or link to an example file we can test with?

**Comment by it-native** [comment]
Hey! Sure:
The error is: "The image must be a file of type: png, gif, jpg, jpeg, svg, bmp, svg+xml, webp."
Example: https://christiedigital.imgix.net/globalassets/.catalog/products/cinema/rgbe-projectors/2310/cp2310-rgbe-front-high-angle.jpg?auto=format,compress

**Comment by snipe** [comment]
That's a jpg tho
