### ISSUE TITLE
Getting 500 error when uploading image to S3

### ISSUE THREAD

**Issue by garylparas** [grokability/snipe-it#14479]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,
I'm getting this error when I create a manufacturer with an image or upload a branding logo.
I am sure that the AWS IAM Keys that I'm using are valid and have permission because I was able to put an image using aws cli `aws s3 cp filename s3://bucket-name`.

```
Aws\S3\Exception\S3Exception
Error executing "PutObject" on "https://bucket-name.s3.amazonaws.com/manufacturers/manufacturer-image--d2BNQBPFRb.png"; AWS HTTP error: Client error: `PUT https://bucket-name.s3.amazonaws.com/manufacturers/manufacturer-image--d2BNQBPFRb.png` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>HJWQG3 (truncated...) AccessDenied (client): Access Denied
```

Here are my env variables related to S3.
```
# --------------------------------------------
# REQUIRED: UPLOADED FILE STORAGE SETTINGS
# --------------------------------------------
PRIVATE_FILESYSTEM_DISK=s3_private
PUBLIC_FILESYSTEM_DISK=s3_public

# --------------------------------------------
# OPTIONAL: AWS Settings
# --------------------------------------------
AWS_ACCESS_KEY_ID=11111111111
AWS_SECRET_ACCESS_KEY=1a1a1a1a1a1a1a1a1a1a1a1a1a
AWS_DEFAULT_REGION=us-east-1

# --------------------------------------------
# OPTIONAL: PUBLIC S3 Settings
# --------------------------------------------
PUBLIC_AWS_SECRET_ACCESS_KEY=1a1a1a1a1a1a1a1a1a1a1a1a1a
PUBLIC_AWS_ACCESS_KEY_ID=11111111111
PUBLIC_AWS_DEFAULT_REGION='us-east-1'
PUBLIC_AWS_BUCKET=bucket-name
PUBLIC_AWS_URL='https://bucket-name.s3.amazonaws.com'
PUBLIC_AWS_BUCKET_ROOT=null

# --------------------------------------------
# OPTIONAL: PRIVATE S3 Settings
# --------------------------------------------
PRIVATE_AWS_ACCESS_KEY_ID=11111111111
PRIVATE_AWS_SECRET_ACCESS_KEY=1a1a1a1a1a1a1a1a1a1a1a1a1a
PRIVATE_AWS_DEFAULT_REGION='us-east-1'
PRIVATE_AWS_BUCKET=bucket-name
PRIVATE_AWS_URL='https://bucket-name.s3.amazonaws.com'
PRIVATE_AWS_BUCKET_ROOT=null
```

In the AWS_URL, I tried several formats such as:
https://bucket-name.s3.amazonaws.com
https://bucket-name.s3-us-east-1.amazonaws.com
https://bucket-name.s3.us-east-1.amazonaws.com
https://s3.us-east-1.amazonaws.com/bucket-name
https://s3.us-east-1.amazonaws.com

I appreciate your help. Thank you

### Reproduction steps

1. Upload an image like a logo for a branding
2.
3.
...

### Expected behavior

Able to upload the image to S3 bucket

### Snipe-IT Version

v6.3.3 build 12903 (g0f63fa23e)

### Operating System

Docker Alpine

### Web Server

Apache

### PHP Version

8.1.27

### Operating System

Windows

### Browser

Firefox

### Version

124.0 (32-bit)

### Error messages

```shell
Aws\S3\Exception\S3Exception
Error executing "PutObject" on "https://bucket-name.s3.amazonaws.com/manufacturers/manufacturer-image--d2BNQBPFRb.png"; AWS HTTP error: Client error: `PUT https://bucket-name.s3.amazonaws.com/manufacturers/manufacturer-image--d2BNQBPFRb.png` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>HJWQG3 (truncated...) AccessDenied (client): Access Denied
```

**Comment by snipe** [comment]
I'm unable to reproduce this locally using our own S3 test bucket. Does the `manufacturers` directory exist in your bucket?

**Comment by snipe** [comment]
![Uploading Cursor_and_Asset_Manufacturers____Snipe-IT_Demo_and_snipe-it_–__env.png…]()

**Comment by snipe** [comment]
<img width="489" alt="Cursor_and_Asset_Manufacturers____Snipe-IT_Demo_and_snipe-it_–__env" src="https://github.com/snipe/snipe-it/assets/197404/e88e0257-435d-44f4-b971-c68375cf87a2">

**Comment by snipe** [comment]
<img width="375" alt="Cursor_and_Asset_Manufacturers____Snipe-IT_Demo_and_snipe-it_–__env-2" src="https://github.com/snipe/snipe-it/assets/197404/1d72e3b9-ad62-4cb0-9488-61dab2446d3f">

**Comment by garylparas** [comment]
> I'm unable to reproduce this locally using our own S3 test bucket. Does the `manufacturers` directory exist in your bucket?

I also tried creating the directory in the bucket but still the same.
We end up using EFS for storage. This can be closed.
