### ISSUE TITLE
[Feature Request]: Assign Assets, Accessories etc. on Users

### ISSUE THREAD

**Issue by Roman-Frick** [grokability/snipe-it#14477]
### Is your feature request related to a problem? Please describe.

It's a new feature.

### Describe the solution you'd like

It would be great if we could assign assets, accessories etc. when having a user open. This helps if we need to assign multiple items of different kinds to a user. Idealy it should be able to use a barcode scanner to scan the QR code on an item.

It could look like having a button "assign item" on the user page which opens a new window with fields like "kind of item" where to select if it's an asset, accessories etc., the item itself and all the other fields which would be on the assign page of the item itself. The user should be auto populated since we're opening it from a specific user page. 

Also there should be a button for using a barcode scanner, which lets us scan the barcode/QR code of multiple items without needing to click the button again.
For example: I click the scan button and scan a code of an asset and 2 accessories and all 3 items should be read in and listed with all the necessary fields to fill out.

### Additional context

In general it would be great to impelement barcode/qr code reading. Like for searching by scanning a code without it opening a separat browser tab.

**Comment by snipe** [comment]
This feature has already been requested and is in the pipeline. (I'm sorry, I can't recall what issue ID it is.)
