### ISSUE TITLE
MAC Address import

### ISSUE THREAD

**Issue by Fnltx** [grokability/snipe-it#14478]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello.
I have a problem similar to #11429

I'm trying to import data with this CSV structure:

Company,IP Management,Network Asset Type,Model,Model No.,Serial,Asset Tag,Stack,Mac import
Company1,192.168.1.1,Access Switch,C9200L,48T-4X,JAE23xxxxx,441,Yes,A0:B4:xx:xy:yx:yy

I'm able to import all except MAC address and the info if the switch is stackable.

I tried also to update the data using the mac format "AA-BB-CC-DD-EE-FF" but it doesn't work.

If I use the note field, it works. 

Side question: how can I set a radio button importing data? I have two possibility: Yes or No. If I import "Yes" the choice is not set.

### Reproduction steps

Import a CSV
Map the MAC Address Field
Import

Look at imported Asset -> Missing MAC Address + stackable

### Expected behavior

I would expect that the Imported Asset's MAC Address field should contain the MAC Address from the CSV Import

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/145357875/e6ffd46b-77d9-42cf-a286-f04e75c431a0)
![image](https://github.com/snipe/snipe-it/assets/145357875/93d4fc81-3245-4e4f-9538-54eb9c425cb7)

### Snipe-IT Version

Version v6.2.3 - build 11759

### Operating System

Windows

### Web Server

IIS

### PHP Version

php-8.2.10

### Operating System

Windows

### Browser

Edge

### Error messages

```shell
No error messages
```

**Comment by DrekiDegga** [comment]
I'm not able to duplicate this. I was just able to import assets with MAC addresses. 

Does the custom field you setup"MAC Address 1" use the builtin MAC Format? The MAC address custom field in CustomFieldFactory.php uses "regex:/^([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}$/"  So it shouldn't be a validation issue.


This worked, I setup a custom field named "MAC Address 1", like yours:
![image](https://github.com/snipe/snipe-it/assets/47491036/10c9887b-68c9-4e1f-87be-b5879ff9d2ad)
![image](https://github.com/snipe/snipe-it/assets/47491036/68d5358f-9422-4af3-82f3-faa39f89d2a7)

I'm not sure what could be going wrong for you.

**Comment by Fnltx** [comment]
Hello @DrekiDegga 
Thanks for your attempt. The field configuration is this:
![image](https://github.com/snipe/snipe-it/assets/145357875/b01c19fa-2acb-4429-9201-06317fdc7513)

If I copy and paste the value directly editing the form, it works
![image](https://github.com/snipe/snipe-it/assets/145357875/c5470a67-0376-4f8f-9feb-a71e395c73ce)

I have the same problem importing radio button info.

I tried with Chrome instead of edge but I still have the same behavior.

Is there a way to see detailed log of the import to understand exactly why Snipe-IT doesn't like that value?

**Comment by Fnltx** [comment]
I wrongly closed the issue. Reopen.

**Comment by DrekiDegga** [comment]
I'm still not able to duplicate the issue except, as @mikeroq suggested in #11429, if the model doesn't already exist, the asset gets imported without any custom values.

Are you sure that the model name AND model number match a model that already exist and has those custom fields assigned?

Otherwise I'm stumped. Sorry I can't be of more help.

**Comment by Fnltx** [comment]
Just to confirm: yes, the model and model number exist and if I import something in a custom field that permit a textual input, it works. 
![image](https://github.com/snipe/snipe-it/assets/145357875/416cac61-53b4-4c2f-bfe7-e90bb0b5fa07)

The problem is only on MAC/ANY field format. I have an old installation that I use for testing (v5.3.1) and there I have no problem with these two fields. 

Thanks anyway @DrekiDegga

**Comment by DrekiDegga** [comment]
I'll just note i'm using Debian LAMP server to host my test environment, not IIS. If that helps anyone narrow down the problem.

**Comment by Fnltx** [comment]
Hello. After a while I tried again with the same CSVs and now the import is working. I don't know why.
