### ISSUE TITLE
Default Status Labels are not remove from side nav when remove it from status label settings

### ISSUE THREAD

**Issue by Kanishka-Deshan** [grokability/snipe-it#14484]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have made few more custom status labels apart from default status labels such as All Deployed, All Pending. Also i have change (Edited) All pending Name to "Not Assigned", But it didn't synced with Side Nav. Also i removed All Pending label from settings. Still it showing on Side Nav

### Reproduction steps

1. Go to status label settings
2. Remove or edit existing default label
...

### Expected behavior

When status labels are edit from settings (Existing Labels) side nav should synced with it

### Screenshots

![Screenshot 2024-03-25 204640](https://github.com/snipe/snipe-it/assets/112304579/f2fbcd33-8703-46e4-803a-1e935848f3f0)

### Snipe-IT Version

v6.3.3 build 12903 (g0f63fa23e)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.14

### Operating System

Ubuntu

### Browser

Google Chrome, Firefox

**Comment by snipe** [comment]
Some of those cannot be removed, since they refer to the meta status, not the label itself. This is working as intended.
