### ISSUE TITLE
Unable to restore model

### ISSUE THREAD

**Issue by raczekm** [grokability/snipe-it#14482]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Error 405 after clicking "restore model" on deleted model's page. 

### Reproduction steps

1. Create model
2. Delete
3. Try to restore.

### Expected behavior

The server returned a "405 Method Not Allowed".

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/12084010/31ca0805-f3ed-4798-b1b6-3e8faf484029)

### Snipe-IT Version

v6.3.0 - build 12490 (master

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.14

**Comment by raczekm** [comment]
It a problem that a GET was used instead of a POST. (Just testes with POST and it's work) so only HTML needs to be updated.

**Comment by snipe** [comment]
I'm unable to reproduce this on the demo.

**Comment by raczekm** [comment]
I've tried sec ago on demo page.

https://demo.snipeitapp.com/models/22 (deleted)


![image](https://github.com/snipe/snipe-it/assets/12084010/7b3b08af-0f03-4ce0-b81d-60966281696b)

After "restore model" click:

![image](https://github.com/snipe/snipe-it/assets/12084010/202fdaf0-49b9-4294-b1ec-2189ccb5f976)


I was able to restore from list but not directly from details page.

**Comment by snipe** [comment]
Ah, so you're only seeing this on the model details page. You can restore from the list view, no?
