### ISSUE TITLE
Too few arguments to function Spatie\DbDumper\DbDumper::setDumpBinaryPath()

### ISSUE THREAD

**Issue by KyryuMaka** [grokability/snipe-it#14493]
### Debug mode

- [X] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I importing csv, when pressing import, it stuck at processing...
When i open debug mode, i see the bug "Too few arguments to function Spatie\DbDumper\DbDumper::setDumpBinaryPath()"

### Reproduction steps

1. Import type Asset
2. Press Import
...

### Expected behavior

Too few arguments to function Spatie\DbDumper\DbDumper::setDumpBinaryPath(), 0 passed in cpanel/public_html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 121 and exactly 1 expected
cpanel/public_html/vendor/spatie/db-dumper/src/DbDumper.php#151
ArgumentCountError
        return $this;
    }

    public function setDumpBinaryPath(string $dumpBinaryPath)
    {
        if ($dumpBinaryPath !== '' && substr($dumpBinaryPath, -1) !== '/') {
            $dumpBinaryPath .= '/';

### Snipe-IT Version

6.0.13

### Operating System

windows

### Web Server

Cpanel

### PHP Version

8.1

**Comment by snipe** [comment]
What do you have in your env for your DB_DUMP_PATH?

**Comment by KyryuMaka** [comment]
> What do you have in your env for your DB_DUMP_PATH?

Well, i set it NULL, could you recomend where the path i can set to it ?
