### ISSUE TITLE
/reports/activity search?

### ISSUE THREAD

**Issue by snipe** [grokability/snipe-it#14495]
### Discussed in https://github.com/snipe/snipe-it/discussions/14480

<div type='discussions-op-text'>

<sup>Originally posted by **ShaunNeighbourSwale** March 25, 2024</sup>
Hi All

I'm looking at grabbing a filtered activity report.  Ideally I'd like to exclude one particular admin from the results.

https://snipe-it.readme.io/reference/reportsactivity says that a search term can be specified.  Any idea of allowed search string formats?

If it's no possible to exclude an admin, I could merge reports for every other admin.  Any idea which search term would specify an admin?

Thanks!</div>

**Comment by snipe** [comment]
The bigger issue here is that we're not set up (yet) to allow you to *exclude* things from searches - and more importantly, however we decide to do that, we can't change it down the line, so it has to be really well thought out and as future-proof as we can make it. The search currently works the same as the other searches within the system, where it will just take a string and try to match it via a `LIKE` query across multiple columns/tables. 

For now, I can add `user_id` as a specifiable field - would that work for you for the time being?

**Comment by snipe** [comment]
> 👋 Thanks for opening your first issue here! 

lol go home welcome-bot - you're drunk.

**Comment by snipe** [comment]
ping @ShaunNeighbourSwale for discussion

**Comment by snipe** [comment]
Like, I can do a quick fix for you for this, something like `except_admin=1`, but I want to make sure the *shape* of this API change actually makes sense for when people want to exclude other things. This is something we've been discussing internally for quite some time - a more boolean way to interact with the API. This does get into sticky territory where we end up writing a SQL parser, but I think it's worth considering. We just need to figure out how exactly we want to handle it, and perhaps more importantly, how people can use it within the tables themselves, which only pass a `search` variable.

**Comment by ShaunNeighbourSwale** [comment]
user_id would get me out of a huge hole!

**Comment by ShaunNeighbourSwale** [comment]
> Like, I can do a quick fix for you for this, something like `except_admin=1`, but I want to make sure the _shape_ of this API change actually makes sense for when people want to exclude other things. This is something we've been discussing internally for quite some time - a more boolean way to interact with the API. This does get into sticky territory where we end up writing a SQL parser, but I think it's worth considering. We just need to figure out how exactly we want to handle it, and perhaps more importantly, how people can use it within the tables themselves, which only pass a `search` variable.

That makes sense - I'm happy to run multiple searches for each individual admin for the time being if that works for you, and helps others.  I doubt many people are in my exact scenario, where a script is responsible for the majority of the activity, and management want a report on all activity excluding ShaunBot.

**Comment by snipe** [comment]
You'd probably be surprised - we've seen alllll kinds of implementations here! Adding `user_id` is trivial and I can ship that today, so let's at least start with that. Then as the discussion goes on internally, we can see how we want to more organically exclude results, allow arrays of things, etc.

**Comment by ShaunNeighbourSwale** [comment]
Thank you!

**Comment by snipe** [comment]
This is now on master - give it a go :)

**Comment by ShaunNeighbourSwale** [comment]
That works!  Thank you!
