### ISSUE TITLE
LDAP Location Sync assigning wrong location

### ISSUE THREAD

**Issue by Support-AEI** [grokability/snipe-it#14506]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We currently use the location attribute in the LDAP Sync for the user's office. In some special cases, a user doesn't have an office assigned to them in the LDAP. In this case, after executing the LDAP Sync, the user in Snipe-IT gets an office number assigned anyway. We suspect it is the office number of the user that was synced previously.

### Reproduction steps

1. Configure LDAP Sync with the location attribute
2. Create a user in LDAP with a location and one without a location
3. Execute the LDAP Sync
4. The user with a location in the LDAP should have the correct one, but the user with no location in the LDAP also has one.

### Expected behavior

The user's location should be empty.

### Snipe-IT Version

v6.3.2 - build 12834 (develop) - Issue persists on newer versions

### Operating System

Debian 12.5 (bookworm)

### Web Server

Apache

### PHP Version

 8.2.7

**Comment by perkaby** [comment]
I can confirm that we are having the same issue when using the LDAP location field. Users with nothing set in the locations field in LDAP will be assigned the same location as the last user that had the field set.

Example:
User 1, No location in LDAP, no location set in Snipe-IT
User 2, Location set in LDAP, Location set correctly in Snipe-IT
User 3, No location in LDAP, Location set to same location as User 2 in Snipe-IT
User 4, No location in LDAP, Location set to same location as User 2 in Snipe-IT
User 5, No location in LDAP, Location set to same location as User 2 in Snipe-IT
User 6, Location set in LDAP, Location set correctly in Snipe-IT.
User 7, Location set in LDAP, Location set to same location as User 6 in Snipe-IT
etc....

Snipe-IT version: v6.3.0 - build 12490 (master) (Oficiall docker image)
