### ISSUE TITLE
The translations are not displaying on the dashboard.

### ISSUE THREAD

**Issue by qhaita** [grokability/snipe-it#14504]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I switch the language to Vietnamese, the characters in the boxes representing the total counts such as 'assets, consumables, components, people' no longer appear.

### Reproduction steps

1. Install SnipeIT v6.3.3
2. Change the default language to Vietnamese.
3. Switch the language in the profile to Vietnamese.
...

### Expected behavior

The characters will appear as the default language.
![image](https://github.com/snipe/snipe-it/assets/106749491/672caeef-5379-4eb7-a540-5cb1978a4a0a)

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/106749491/ed2131bf-b735-4dff-a47a-d4732bb8c428)

### Snipe-IT Version

6.3.3

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.29

### Operating System

Windows

### Browser

Google Chrome, Firefox, Edge

**Comment by snipe** [comment]
I cannot replicate this.

<img width="1580" alt="Screenshot 2024-03-27 at 6 28 46 PM" src="https://github.com/snipe/snipe-it/assets/197404/ca3c1474-a192-4cd7-8622-063a0b8f03d8">

**Comment by qhaita** [comment]
Hi @snipe,
After performing a reinstallation on Ubuntu 22.04.4 with PHP 8.1, the error mentioned above no longer appears. Thank you for your assistance.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
