### ISSUE TITLE
Error on Database Backup Phase During Upgrade to Latest Snipe-IT Version on CentOS Stream 9

### ISSUE THREAD

**Issue by it-blr** [grokability/snipe-it#14501]
### Debug mode

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

## Issue Overview
While upgrading Snipe-IT from version 6.3.0 to the latest stable release on a CentOS Stream release 9 environment, I encountered an error during the database backup phase, which prevented the upgrade process from proceeding.

## Error Details
The process halted with the following error message:

In ProviderRepository.php line 208:
Class "Mediconesystems\LivewireDatatables\LivewireDatatablesServiceProvider" not found
Something went wrong with your backup. Aborting!

This error was also reflected in the `laravel.log`:

[2024-03-26 21:52:02] production.ERROR: Class "Mediconesystems\LivewireDatatables\LivewireDatatablesServiceProvider" not found {"exception":"[object] (Error(code: 0): Class "Mediconesystems\LivewireDatatables\LivewireDatatablesServiceProvider" not found at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208) ...

### Reproduction steps

1. Initiate upgrade from Snipe-IT version 6.3.0 to the latest stable version.
2. Error occurs during the database backup phase.

### Expected behavior

The expected behavior was a smooth upgrade process without interruptions. Specifically, the database backup step should have completed successfully, allowing the upgrade to continue to the next phases without any errors. 

### Snipe-IT Version

6.3.0 

### Operating System

CentOS Stream 9

### Web Server

Apache

### PHP Version

PHP version 8.0.30

### Operating System

Windows

### Browser

Google Chrome

### Version

123.0.6312.59

### Error messages

```shell
tail -f laravel.log
#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\\Foundation\\ProviderRepository->createProvider()
#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest()
#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(659): Illuminate\\Foundation\\ProviderRepository->load()
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /var/www/html/snipeit/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"}
```

**Comment by snipe** [comment]
Comment out the lines (temporarily) in upgrade.php that tries to do the backup and run the upgrade again.

**Comment by snipe** [comment]
(You may need to `git stash` and `git pull` before running the upgrade again)

**Comment by it-blr** [comment]
@snipe : Thank you for your suggestion regarding the upgrade issue, to temporarily bypass the database backup step during the upgrade process. Here's a brief overview of the steps that helped resolve the issue.

Attempted to bypass the database backup issue as suggested.
Encountered permission errors with Git and Composer.
Corrected file permissions and ownership in the Snipe-IT directory.
Ran composer update as a regular user to update dependencies without root privileges.
Resolved permission issues and completed the upgrade.
The application is now upgraded and running smoothly. Your advice was very helpful in pointing me in the right direction!
