### ISSUE TITLE
Unable to send emails - "Mail could not be sent."

### ISSUE THREAD

**Issue by Nerph** [grokability/snipe-it#14522]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm unable to get Snipe-IT to send emails. I get the following error:

```
Mail could not be sent.
No additional error message provided. Check your mail settings and your app log.
```

below are the .env settings with sensitive info redacted:

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USERNAME=apikey
MAIL_PASSWORD=[redacted]
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=[redacted]@gmail.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=[redacted]@gmail.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'
```

### Reproduction steps

1. Go to Admin > General Settings.
2. Click on the 'Send Test' button for Test Mail.
3. Error occurs.

### Expected behavior

An email should be sent to the MAIL_REPLYTO_ADDR

### Snipe-IT Version

6.3.3

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows 11

### Browser

Mozilla Firefox

### Version

124.0.1

### Error messages

```shell
Weirdly enough, laravel.log is empty although I'm certain I chown'd the folders and chmod, etc

I checked apaches error.log and it contains this:

PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl' (tried: /usr/lib/php/20190902/openssl (/usr/lib/php/20190902/openssl: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/openssl.so (/usr/lib/php/20190902/openssl.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  Module 'sockets' already loaded in Unknown on line 0

php -m output:

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

This is a fresh install, running on ubuntu 20.04.
I did a manual installation, following a vultr guide.
I received no error messages along the way (I never tested the mail during initial config though).
I have not manually edited any data directly in the database.

I've been to https://github.com/thilinadias/thilinadias/discussions/1#discussion-5964598 and followed these steps, without success.

**Comment by Nerph** [comment]
I'm investigating if the VPS I'm running this on is blocking emails being sent via port 25/587, etc. I've contacted their support, because I've noticed when debugging that it looks like the email is being created by Snipe-IT ("Mail" tab in the debugging) but just not being able to be sent.

**Comment by snipe** [comment]
Good thinking!

**Comment by Nerph** [comment]
Yeah, so it seems my smtp settings were somewhat incorrect, and I've managed to get everything working. My apologies for wasting everyone's time with this, lol :/

**Comment by snipe** [comment]
Ah, glad you're sorted!
