### ISSUE TITLE
v6.3.3 build -Default label not showing Tag Column

### ISSUE THREAD

**Issue by rkthamizhan** [grokability/snipe-it#14521]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Default label not showing Tag Colum

### Reproduction steps

1.Default label not showing Tag Colum
2.
3.
...

### Expected behavior

Default label not showing Tag Colum

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/114354388/faebce92-ff7d-4bca-b634-91c693af425f)

![image](https://github.com/snipe/snipe-it/assets/114354388/32874caa-2927-4e67-abb0-b6c2803a8321)

### Snipe-IT Version

v6.3.3 build 13056 (gb34156ca2)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

v6.3.3 build 13056 (gb34156ca2)

### Operating System

Windows

### Browser

Edge

**Comment by snipe** [comment]
Please run the upgrader again - we pushed out some small fixes to labels today.

**Comment by rkthamizhan** [comment]
after upgrade, still same
![image](https://github.com/snipe/snipe-it/assets/114354388/73c90ce7-1174-4de8-9124-0dbabd8d5fe2)

**Comment by rkthamizhan** [comment]
after upgrade, still same. tag column not visible in the label.

**Comment by snipe** [comment]
It's working on the demo - https://demo.snipeitapp.com/admin/labels - have you tried re-saving your settings?

<img width="1276" alt="Screenshot 2024-03-29 at 11 07 49 AM" src="https://github.com/snipe/snipe-it/assets/197404/788491a3-a76e-41ea-832d-6c9f890dcc64">
<img width="1062" alt="Screenshot 2024-03-29 at 11 07 56 AM" src="https://github.com/snipe/snipe-it/assets/197404/2ce27f0e-44d2-4d7d-95ea-b2c3e83233f9">




<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/admin/labels">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by rkthamizhan** [comment]
I tried many settings, and i noticed tag column printed miss aligned. 
![image](https://github.com/snipe/snipe-it/assets/114354388/ce9e4114-ebf3-4259-b74a-bbfd1a644390)
 ![image](https://github.com/snipe/snipe-it/assets/114354388/be635bea-94af-4655-8f53-e97a60c84592)
 ![image](https://github.com/snipe/snipe-it/assets/114354388/3686c8fe-4150-4f6f-857b-ed6f7140e6b5)
![image](https://github.com/snipe/snipe-it/assets/114354388/bb0ab2d8-f8b1-4f5e-b00f-bd94bbe76208)

**Comment by rkthamizhan** [comment]
Thanks, its working now.
![image](https://github.com/snipe/snipe-it/assets/114354388/f05fb3a3-6c0b-4557-8b03-07ddfe077463)

**Comment by rkthamizhan** [comment]
Thanks, its working now.
