### ISSUE TITLE
Missing Notes in Asset Checkin Process

### ISSUE THREAD

**Issue by afontalv** [grokability/snipe-it#14548]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have encountered a bug within the Snipe-IT asset management system that involves the "Checkin" functionality for assets. Specifically, the issue occurs when adding a note to an asset during its checkin process.

### Reproduction steps

1. Navigate to the asset checkin screen (e.g., https://demo.snipeitapp.com/hardware/3/checkin).
2. In the "Notes" field, enter any text as a note.
3. Click the "Checkin" button to complete the checkin process.
4. Navigate back to the asset's detail page to view the checkin information.

### Expected behavior

The note entered during the checkin process should be visible on the asset's detail page under the checkin information section.

### Snipe-IT Version

v5.4.1 build 6746 (g3e22dce11)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Browser

Google Chrome

### Additional context

I have tested this bug in the demo version offered by SnipeIT and was able to reproduce it,

**Comment by snipe** [comment]
This is expected behavior. The checkin note gets added to the asset history, not the overall details page. https://demo.snipeitapp.com/hardware/3#history

**Comment by afontalv** [comment]
Ah, I see. Thank you for your time, attention and for the clarification. Also, a HUGE thank you for this wonderful product you guys have developed :) It has enriched the lives of our IT team.
