### ISSUE TITLE
"Assigned to" in label not working

### ISSUE THREAD

**Issue by Roman-Frick** [grokability/snipe-it#14541]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When selecting the assigned to field to show on the labels, it is showing in the preview but not the actual label generated for an asset.

It is a recreation of the bug report #14328 since it was closed but the bug still exists

### Reproduction steps

1. Select new label engine
2. Create a new field and select assigned to as datafield
3. Generate label for an asset which is assigned to someone

### Expected behavior

To show all the selected fields on the label

### Snipe-IT Version

v6.3.4

### Operating System

Docker

### Web Server

nginx

### PHP Version

8.1.2-1ubuntu2.14

**Comment by snipe** [comment]
I'm not able to reproduce this. 

<img width="386" alt="Screenshot 2024-04-03 at 2 16 10 PM" src="https://github.com/snipe/snipe-it/assets/197404/3f6409fd-d8f8-442a-8ecc-5572970d080f">

**Comment by Roman-Frick** [comment]
Well, on demo.snipeitapp.com it is very reproducible. The preview shows the assigned to correctly as posted in your picture, but when creating an acutal label, it is empty and thus not showing.
<img width="1120" alt="image" src="https://github.com/snipe/snipe-it/assets/117271747/54503e54-87d7-4877-9636-2911139717cb">
<img width="190" alt="image" src="https://github.com/snipe/snipe-it/assets/117271747/6bdcd491-4de6-443d-9ed3-a409a1887d0c">

**Comment by shanold** [comment]
Exact same Issue Preview shows perfectly the Real labels do not show anything for the assigned-to tag, 
 snipe it 6.3.4- build 13139 (master)

**Comment by VinnyPolar** [comment]
Is there any way for me to change what is generated in the qr code? I would like to put either the serial or the name of the asset in the qr code, so I can do mass check out by scanning the qr codes glued to the assets

**Comment by qhaita** [comment]
Hi @Roman-Frick ,
I also encountered a similar situation like you, and I successfully fixed it by following these steps:

Navigate to the path **.../resources/views/partials**
Edit the file **label2-field-definitions.blade.php**
At line 315, change the value of **"assignedTo"** to **"assignedto.fullname"**

Hope this helps you!

**Comment by Roman-Frick** [comment]
@qhaita Awesome, that works, thank you.
@snipe could you implement this fix please.

**Comment by shanold** [comment]
> Hi @Roman-Frick , I also encountered a similar situation like you, and I successfully fixed it by following these steps:
> 
> Navigate to the path **.../resources/views/partials** Edit the file **label2-field-definitions.blade.php** At line 315, change the value of **"assignedTo"** to **"assignedto.fullname"**
> 
> Hope this helps you!

Like this?
 <option value="assignedto.fullname">{{trans('admin/hardware/table.assigned_to')}}</option>

I ask because it didn't work for me :( Does it matter that my users were imported from LDAP?

**Comment by shanold** [comment]
@Roman-Frick Worked for me also!! <3

**Comment by snipe** [comment]
@Roman-Frick we're a little backed up - would potentially take a PR tho

**Comment by marcusmoore** [comment]
Thanks for digging into this @qhaita 😄 

That change works for displaying assigned users but not assigned locations or assets. I'll work on a fix for both of those and PR shortly.

**Comment by snipe** [comment]
@marcusmoore I'm not sure why this would work on the demo in the preview but not on the actual labels tho.

**Comment by marcusmoore** [comment]
I’m not looking at the code right now but I think we (I?) manually set the assignedTo relationship in for the preview but that isn’t working when actually queried. I started to dig in and should have a fix soon.

**Comment by marcusmoore** [comment]
This is handled in #14581.

Closing but please re-open if #14581 doesn't actually fix the issue for you 😄
