### ISSUE TITLE
[Feature Request]: Filter Reports Better

### ISSUE THREAD

**Issue by HarleyIT** [grokability/snipe-it#14555]
### Is your feature request related to a problem? Please describe.

When I am doing reports inside of Snipe-IT, I have to export to Excel in order to filter out certain types and objects.  Example, I search for all comptuers in a department and I want to filter out the retired systems.  Currently I can not do that.  This would make life so much easier.

### Describe the solution you'd like

Would like to see the ability to filter out certain objects when running reports instead of exporting to excel and then filtering.

### Describe alternatives you've considered

There is no alternative solution I can think of.

**Comment by Godmartinz** [comment]
do you currently have the `Archived Assets` box checked in General Settings? 
<img width="1294" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/e8913771-624f-47ec-9312-fb7c510d7d03">

**Comment by snipe** [comment]
Because you didn't actually tell us what report you're trying to run, or any of the available filters you have, this is a pretty tough one for us to help with. I'm closing this, with all due respect, and ask that you actually look at the issue templates if you wish to re-open.
