### ISSUE TITLE
ImageMagick module (and presumably gd) not pre-installed on snipe/snipe-it official Docker

### ISSUE THREAD

**Issue by mattv8** [grokability/snipe-it#14562]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Fresh docker image snipe/snipe-it not getting imagemagick (and presumably gd although I haven't explicity tested that).

### Reproduction steps

1. Fresh docker pull
2. Specify IMAGE_LIB=imagick in my .env
3. In Snipe-IT, I browse to Settings > Branding and attempt to upload logo PNG
4. Click "save".
5. Server will throw a 500 error.

### Expected behavior

I would expect that the snipe/snipe-it Dockerfile would come pre-pachaged with Imagemagick or gd so it's ready to go out of the box. 

### Screenshots

<img width="602" alt="Screenshot 2024-04-05 104840" src="https://github.com/snipe/snipe-it/assets/9312603/2f94a77c-e5bf-42c0-99fa-f6a6f86db9ce">

### Snipe-IT Version

v6.3.4 - build 13139

### Operating System

snipe/snipe-it Docker image

### Web Server

Apache2

### PHP Version

PHP 8.1.2-1ubuntu2.14

### Error messages

```shell
Intervention\Image\Exception\NotSupportedException: ImageMagick module not available with this PHP installation.
```

### Additional context

This is a fresh Docker pull of snipe/snipe-it.

I am able to fix the issue by SSH'ing into the docker image with `docker exec -it {docker_image_name} /bin/bash` and running the following commands:
```
apt update
apt install php-imagick -y
service apache2 restart
```

The issue with the above fix is that it will not persist between Docker pulls.

**Comment by uberbrady** [comment]
The whole point of docker is that it should be a runnable instance, with some choices made for you. One of those choices we made is to use 'gd' instead of imagick. Do you have a use-case for why you prefer imagemagick? Is it better or different in some way (I honestly don't know, they're interchangeable to the best of my understanding).

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
