### ISSUE TITLE
Error when trying to create new app_key

### ISSUE THREAD

**Issue by miracuruzrh** [grokability/snipe-it#14563]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to generate a new app_key, like suggested in the .env.docker file, with command: `docker compose run --rm snipeit bash` an error occures. Error message: "[FATAL tini (7)] exec bash failed: No such file or directory".

Log:
```bash
docker compose run --rm snipeit bash
WARN[0000] /root/snipe-it/docker-compose.yml: `version` is obsolete
[+] Creating 2/2
 ✔ Container snipe-it-redis-1    Created                                                                          16.0s
 ✔ Container snipe-it-mariadb-1  Created                                                                          16.0s
[+] Running 2/2
 ✔ Container snipe-it-redis-1    Started                                                                           0.2s
 ✔ Container snipe-it-mariadb-1  Started                                                                           0.2s
 ```

### Reproduction steps

1. Pull git repository
2. Edit .env.docker file
3. run command `docker compose run --rm snipeit bash`

### Expected behavior

The command should not run into error.

### Snipe-IT Version

6.3.4

### Operating System

debian 12

### Web Server

Apache (in docker)

### PHP Version

8.3

### Error messages

```shell
[FATAL tini (7)] exec bash failed: No such file or directory
```

### Additional context

Very fresh install. Just configured the .env.docker file and then executed the command described above to generate a new app_key for the configuration file.

**Comment by matreicht** [comment]
Hi,
Yes indeed the documentation mentions that command but the snipeit container in my experience does not have bash correct me if im wrong, but the php artisan and composer commands can be executed via the docker exec command like so: docker exec <container_name_or_id> php artisan key:generate --show

If you happen to be able to get the containers up and running please hit me with a message, because i've been struggling myself, for me it's the database root and snipeit user password, whatever i supply access is denied.

**Comment by jerm** [comment]
@miracuruzrh The answer that @matreicht is correct -- bash isn't installed by default in the container, but you can run the necessary commands w/o using bash

eg:
```
docker exec -it snipeit php artisan key:generate
```
Should do the job for you.


If you really want bash, you can install it via

```
docker exec -it snipeit apk add bash
```

Then try bash again and it should work.
