### ISSUE TITLE
[MULTICOMPANY LOGIC] Moving assets through companies brings chaos.

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#14569]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

While Snipe-IT has no means to isolate admins to their departments (people, assets, accessories, etc.) many users use "Companies" as a workaround. Superadmin can move assets from one company to another through checkout button. Company, asset is assigned to, doesn't change in the process and moved asset becomes invisible to the person it was assigned to. It would be nice, if company information changed automagically to the new company/no company when checkout is done by superadmin.

Currently asset has to be checked-in from the user (1), manually assigned new company and location through asset edit (2), checked-out to user in new company(3). Everything could be done in 1 step instead of 3 and without manual editing.

### Reproduction steps

1. Create company1 and assign user1 to it.
2. Create company2
3. Create asset1 and assign to company2
4. With superadmin check-out asset1 to self. After that assign asset to user1 in company1. Asset1 remains assigned to company2 - user1 will not see any assets checked-out to him and this asset won't be visible for company2 admins.

### Expected behavior

Company asset is assigned to, should change when asset is moved to another company. Another option - don't allow asset checkouts to himself (or locations without company) by superadmins because it brings chaos.

### Snipe-IT Version

v6.3.4 - build 13139 (master)

### Operating System

Ubuntu Server 22.04

### Web Server

Apache

### PHP Version

PHP 8.1.27

**Comment by snipe** [comment]
> Company asset is assigned to, should change when asset is moved to another company. 

That would create more chaos across the boards.

> Another option - don't allow asset checkouts to himself (or locations without company) by superadmins because it brings chaos.

That's more of an administrative control. 

There are a ton of use cases where the asset should stay at the company but the user of a different company should have access to it. I generally recommend not using full company support if your workflow is like that, and if it is like that, make sure you don't edit companies that way.
