### ISSUE TITLE
[Feature Request]: locations bound to companies

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#14570]
### Is your feature request related to a problem? Please describe.

Currently locations aren't attached to companies, so full location list is visible for all companies. What's even worse - admins can't see number of assets assigned to that location by admins of other Companies. Worst - admin who haven't assigned any assets to that location, is allowed delete that location. :)

### Describe the solution you'd like

Best solution - locations can be assigned to company when created. This way location list would only be visible for the admins of the company, locations were created for.

### Describe alternatives you've considered

Temporary acceptable solution - Snipe-IT checks for assigned assets globally and disables deleting of location if any asset is assigned to that location by any admin from any company. (Currently check is run only on the company of connected admin.)

**Comment by snipe** [comment]
Duplicate of #12935, #10212, #7131. The issue has always been how this will negatively impact the users who are used to the way it currently works. There is a discussion PR here: https://github.com/snipe/snipe-it/pull/12577
