### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by maxtimbo** [grokability/snipe-it#14571]
### Is your feature request related to a problem? Please describe.

I don't mean to stir the pot on an old request:

https://github.com/snipe/snipe-it/issues/6928

But I just wanted to put my +1 to this feature request. I understand it may be a difficult issue to solve.

### Describe the solution you'd like

Much like bulk edit, but bulk checkout to user, asset, or (most importantly) location

### Describe alternatives you've considered

A whole bunch of clicking... Is there a way to manipulate the db via cli? That would also solve my issue.

**Comment by snipe** [comment]
Add your +1 there, please do not create new issues when open ones already exist.
