### ISSUE TITLE
Snipe-IT page loading problem

### ISSUE THREAD

**Issue by IvanROU** [grokability/snipe-it#14575]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After moving a virtual machine to another virtualization server, the first page load takes a very long time (965ms). 
Then the remaining switching between tabs and pages proceeds quickly (74.75ms). 
But if you leave the page for a minute or two, everything starts all over again. 
I tried to return the computer to the previous server, the situation did not change. 
At first I thought that the problem was in the database, but as it turned out, that was not the problem.

### Reproduction steps

1. Shut down the server Snipe-It
2. Move server to another ESX
3. Run down the server and open Snipe-It page

...

### Expected behavior

Previously, the loading speed of the first page was the same as the rest

### Snipe-IT Version

6.3.4

### Operating System

Debian 12

### Web Server

Apache

### PHP Version

8.1.27

### Operating System

Windows 11

### Browser

Chrome, Edge, Vivaldi, Firefox

### Version

123.0.6312,  123.0.2420, 6.5.3206 , 124.0.2

### Additional context

Last update to v.6.3.4 April 03, 2024
Initial version installed using install.sh in Mars 2021 on Debian 11 with php7, then in January 2024 the operating system and PHP were updated to Debian 12 and PHP 8.1.
Before moving the virtual machine to another server VMWare, everything worked great.

**Comment by mamdouh-abdulghaffar** [comment]
Hello, I have a similar issue to yours, after uploading the data to DB tables, I found out that going from tab to tab takes around 60 second
