### ISSUE TITLE
Custom fields cannot add to the users

### ISSUE THREAD

**Issue by Kanishka-Deshan** [grokability/snipe-it#14574]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm not able to add custom fields to users and I'm not sure whether it is possible to do so. Because I have few extra fields to the users such as personal email, Official Email, User Level, Level 2 Manager name like wise. While i was searching through the documentation i was able to we can add customer fields to assets, Can we do the same to users?

### Reproduction steps

1. Go to users (People)
2. Cannot create new users with custom field

### Expected behavior

Add custom fileds to users

### Snipe-IT Version

v6.3.4 build 13139 (g6f9ba6ede)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.27

### Operating System

Windows

### Browser

Google Chrome, Firefox

**Comment by mauro-miatello** [comment]
custom fields are only for assets

**Comment by snipe** [comment]
Duplicate of #4261
