### ISSUE TITLE
[Feature Request]: Endpoint for Overdue checked out assets

### ISSUE THREAD

**Issue by Thomas-CPOC** [grokability/snipe-it#14580]
### Is your feature request related to a problem? Please describe.

Not related to a problem.

### Describe the solution you'd like

I would like there to be an endpoint for gathering a list of checked out assets that are overdue their expected check in date. There is currently an endpoint for overdue audits. However, I would like these assets to be removed from the list automatically once checked in. Currently, to remove them from the overdue audit list there is still an extra manual step.

### Describe alternatives you've considered

Considered using the audit option in snipe but I'd rather not add an additional manual step in our process.

### Additional context

Building out our own automation here to send out email notifications on overdue assets. However, dealing with multiple client assets, I need to customize these emails with different company branding. Currently there is no function in Snipe to customize the email notification so I am using that email as a trigger on our service account to run a power automate flow that parses out the assets, does a lookup against our list of users and company IDs, and branches out to send the email notifications from there with client company logos, asset info, and other data from additional sources like fedex return label info that we have previously sent to return equipment.

**Comment by meowserkat** [comment]
I like this idea, or have on the admin dashboard one of the boxes "assets due for checkin" with the number

**Comment by snipe** [comment]
You should just be able to use `?status=Deployed` on that audit listing endpoint.

**Comment by snipe** [comment]
I think this should be covered in #14655

**Comment by Thomas-CPOC** [comment]
Perfect. Thank you!
