### ISSUE TITLE
Asset Tag Field Missing from Default Label after Updating to v6.3.4

### ISSUE THREAD

**Issue by al-dubois** [grokability/snipe-it#14585]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Following the recent update to version 6.3.4, I've noticed that the default label template no longer includes the TAG field when printing.

In the settings, I observed that the TAG column for the default tag is marked as inactive (X'd out). However, I distinctly remember that in version 6.3.2, the TAG field was included in the default label and would still print the asset tag.

I attempted to manually add the TAG field in the field definitions section, but unfortunately, it didn't work.

What steps can I take to enable the asset tag field in the default label template? Any assistance would be greatly appreciated !

### Reproduction steps

1.Default label not printing asset tag
2.
3.
...

### Expected behavior

I expect the label to include the asset tag field, as it did in v6.3.2 or earlier versions.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/166629352/154e670c-61e7-4d72-afb9-3018249ac210)

Prior to v6.3.4 label
![v6 3 3](https://github.com/snipe/snipe-it/assets/166629352/b561f273-49e4-4402-bbb7-1052de43fbad)

Same asset on v6.3.4
![image](https://github.com/snipe/snipe-it/assets/166629352/7b97dc44-ac9a-4ece-acf9-2e28019040e7)

### Snipe-IT Version

v6.3.4 - build 13139 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

v6.3.4 - build 13139 (master)

**Comment by nhimc0n** [comment]
i has same problems. Please help fix it in next update. Thanks!

**Comment by qhaita** [comment]
Hi @marcusmoore , can you help to check this issue ?

- Create field definition with datasource "Asset Tag"
![image](https://github.com/snipe/snipe-it/assets/106749491/056e5e39-16bc-4141-bc1c-ee4d289b978a)

- The label not show Asset Tag
![image](https://github.com/snipe/snipe-it/assets/106749491/286b19b9-4d72-4356-8d56-134efe5068df)

**Comment by marcusmoore** [comment]
@alduboishc @qhaita 

This should be fixed in #14632 but in the meantime: try to pick something else in the list (like Asset Name), then re-select Asset Tag, then Save. I think that will fix the issue for you.

**Comment by qhaita** [comment]
> @alduboishc @qhaita
> 
> This should be fixed in #14632 but in the meantime: try to pick something else in the list (like Asset Name), then re-select Asset Tag, then Save. I think that will fix the issue for you.

It works ! Thanks for your help 👍

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
