### ISSUE TITLE
The label fields only shows one option even though two options have been assigned

### ISSUE THREAD

**Issue by qhaita** [grokability/snipe-it#14589]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have assigned two options in one field, however, the label only displays one option. For example, I want to display both options: CPU and RAM. However, the label only displays the CPU option.

### Reproduction steps

1. Create custom fields include: CPU, RAM
2. Create 2 options in 1 field
3. Display label
...

### Expected behavior

Display multiple options in one field.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/106749491/3b84524e-96cd-4d95-8bc6-19cecce0afa1)
![image](https://github.com/snipe/snipe-it/assets/106749491/8b25ed22-7154-4a5d-a938-220b6a41baf5)

### Snipe-IT Version

6.3.4

### Operating System

Ubuntu 22.04.4

### Web Server

Nginx

### PHP Version

8.1.2

**Comment by marcusmoore** [comment]
Yup...I see that too. Thanks for reporting @qhaita. I'll work on a fix.

**Comment by qhaita** [comment]
Hi @marcusmoore ,
It worked, thank you for fixing it so quickly.
