### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by koustavshee** [grokability/snipe-it#14599]
### Is your feature request related to a problem? Please describe.

there is no options to add custom field upload files in the asset category

### Describe the solution you'd like

there should be options to add cutom fields to upload other files in the asset category like other custom field

### Describe alternatives you've considered

there is no alternative available in your piece of code other than uploading them in a google drive and linking them via shareable url

### Additional context

actually i am using SNIPE-IT for keeping track of lab equipments so it will be very much better have all document together like the calibration cirtificate, purchase order etc.

**Comment by snipe** [comment]
I don't really understand the ask. You can upload files to models and assets already, you don't need a custom field for that.

**Comment by koustavshee** [comment]
Yes there is a field for uploading files which are only in JPEG, webp,png, gif and svg which doesn't suffice. I have other documents like purchase oder copy and other related documents .I want upload those files in the same and want them to be separated thats why i need custom fields

**Comment by snipe** [comment]
@koustavshee that's not true though. You can upload  png, gif, jpg, jpeg, doc, docx, pdf, xls, xlsx, txt, lic, xml, zip, rtf and rar. 

<img width="721" alt="Macbook_Pro_13____5345031975426626_____Snipe-IT_Demo_and_Apple_Manufacturer____Snipe-IT_Demo_and_Start_Page" src="https://github.com/snipe/snipe-it/assets/197404/0c032430-077d-493f-8517-216233dd0c5c">
<img width="719" alt="View_Asset_884968171____Snipe-IT_Demo_and__👾-github___Snipe-IT_Community_-_Discord_and_Apple_Manufacturer____Snipe-IT_Demo" src="https://github.com/snipe/snipe-it/assets/197404/5d080b71-5761-491e-b570-30c2862327b7">
<img width="1440" alt="Screenshot 2024-04-22 at 12 28 30 PM" src="https://github.com/snipe/snipe-it/assets/197404/c65c0485-5e10-42a0-bc86-5c298d2fc8da">

**Comment by koustavshee** [comment]
1. see i have different files for an asset i want the save them separately is it possible with this?  other than rar...And i'm sorry didn't clicked that button there

**Comment by snipe** [comment]
> see i have different files for an asset i want the save them separately

Yes, of course, just select multiple from the file selector. 


https://github.com/snipe/snipe-it/assets/197404/6af5b38d-21dd-4beb-8257-494b58c9e775

**Comment by koustavshee** [comment]
Thank You very much for your help ☺️

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
