### ISSUE TITLE
ERROR: Failed to retrieve remote requirements  |  Missing PHP-extension PHP8/IIS php_xmlrpc.dll

### ISSUE THREAD

**Issue by tom-sin** [grokability/snipe-it#14600]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If I run command "php upgrade.php" I get following error:

WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- validate some very basic .env file settings
- check your PHP version and extension requirements
- check directory permissions
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

**ERROR: Failed to retrieve remote requirements from https://raw.githubusercontent.com/snipe/snipe-it/master/.upgrade_requirements.json**

We suggest correcting this, but if you can't,  please verify that your requirements conform to those at that url.

 -- DANGER -- DO AT YOUR OWN RISK --
      IF YOU ARE SURE, re-run this script with --skip-php-compatibility-checks to skip this check.
 -- DANGER -- THIS COULD BREAK YOUR INSTALLATIONExiting.

I believe the php extension "php_xmlrpc.dll" is missing but in Snipe-IT´s configuration guideline I can´t find steps to install it manually. 

I reinstalled composer and run composer install but no improvement. 

Also with:
composer dump-autoload; php artisan cache:clear; php artisan config:clear; php artisan route:clear; php artisan debugbar:clear; php artisan event:clear; php artisan view:clear; php artisan optimize:clear; php artisan clear-compiled

..... no improvement.

### Reproduction steps

1. set command  "php upgrade php" in git bash (windows)

### Expected behavior

Upgrade SnipeIT to newest version.

### Snipe-IT Version

v6.3.4

### Operating System

Windows

### Web Server

IIS

### PHP Version

PHP 8.1.19

### Error messages

```shell
$ php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
soap
sodium
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

### Additional context

Upgrade
Windows Server 2019 / IIS
install.sh

**Comment by snipe** [comment]
This is outside the scope of Snipe-IT (and we don't use windows here), but a google search came up with this: https://docs.moodle.org/403/en/admin/environment/php_extension/xmlrpc

<blockquote><div><strong><a href="https://docs.moodle.org/403/en/admin/environment/php_extension/xmlrpc">admin/environment/php extension/xmlrpc - MoodleDocs</a></strong></div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
