### ISSUE TITLE
[Feature Request]: Enable uploading license file through API

### ISSUE THREAD

**Issue by Devilspayback** [grokability/snipe-it#14617]
### Is your feature request related to a problem? Please describe.

Hello,

I've been writing some automation for SnipeIT in our company and would like to be able to upload license files through the API.
I've been trying a couple of variations as documented in the API support page, without success.
The code gives me back a positive response saying the license has been updated but the file isn't uploaded. Uploading it manually in the portal works without issue (it's an XML file). Is this a feature that is currently supported or not?

Thanks,

### Describe the solution you'd like

I would like to be able to upload License Files through the API for automation purposes.

**Comment by snipe** [comment]
What endpoint are you using? We generally don't allow file uploads via API, since it makes it much harder for us to validate file types and make sure nothing malicious is being uploaded since we have to first store the binary data, then do a bunch of validation on the temp file on the server.

**Comment by Devilspayback** [comment]
I've tried both adding them with the POST method on license creation on the "MyEndpoint/licenses" endpoint and using the PUT/PATCH Method on existing licenses using the "MyEndpoint/Licenses/id" endpoint. I didn't see any parameters included in the API documentation to upload a file, so it's very well possible i'm not using the correct code to upload the license. Just wanted to check if this feature is supported or not.

**Comment by snipe** [comment]
It is not supported at this time.
