### ISSUE TITLE
Email Notification to Users

### ISSUE THREAD

**Issue by Ad-09** [grokability/snipe-it#14620]
### Is your feature request related to a problem? Please describe.

This is not a problem but maybe an Update?

### Describe the solution you'd like

Is there a possiblity to send out an email notification to Users who Checkin and Checkout devices immediately,
instead of the usual, "Email list of all assigned Assets"?

**Comment by snipe** [comment]
Yes, at the category level, you would set that.

https://demo.snipeitapp.com/categories/7/edit

<img width="533" alt="Update_Category____Snipe-IT_Asset_Management_Demo" src="https://github.com/snipe/snipe-it/assets/197404/8f7ddb61-5342-4b19-96e0-ce91578e7963">



<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/categories/7/edit">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
