### ISSUE TITLE
Error when editing some asset models

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#14639]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Good afternoon. After updating to the latest version 6.3.4 - build 13226, errors were noticed. For example, there is a free asset that has a default location specified. When I try to delete the location, I get an error - "Error: Please check the form below for errors". It is not clear what exactly the error is. There are no clarifying messages. Also, after an attempt to close the asset editing form via the cancel button, the editing form does not close. When you press the button Back, nothing happens either. When trying to issue an asset to a user, I get an error - "Error: User was not checked out, please try again{"next_audit_date":["The next audit date must be a date after last audit date."]}". And also, when you try to close the "Checkout Asset" form, it does not close.
This error probably does not apply to all assets, but only manifests itself on some models.

![3](https://github.com/snipe/snipe-it/assets/48224568/86fb1129-3877-4b82-aaa7-e48886fd6103)
![2](https://github.com/snipe/snipe-it/assets/48224568/ea7fa693-edf8-4aa5-a5af-4225ced8180a)

### Reproduction steps

1. In a certain asset model I'm trying to delete a location
2. I get an error, without specifics

### Expected behavior

So that there are no mistakes

### Snipe-IT Version

v6.3.4 build 13226

### Operating System

CentOS 7

### Web Server

Apache

### PHP Version

8.1.28

### Operating System

Windows 10

### Browser

Chrome

### Version

Last

**Comment by snipe** [comment]
@UserGoodtm And is the next audit date after the last audit date for the asset in question?

**Comment by UserGoodtm** [comment]
Really. I deleted the next audit date and the problems disappeared. This had never happened before and this behavior baffled me. Moreover, when editing an asset, the error did not indicate problems due to the need for an audit.

**Comment by snipe** [comment]
It's likely we tightened up the validation on those dates since the last time you updated. A next date obviously shouldn't be before the last date.
