### ISSUE TITLE
Inconsistent asset creation via API with purchase_cost as float

### ISSUE THREAD

**Issue by Isotop7** [grokability/snipe-it#14635]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We use the API to ingest assets into Snipe-IT and have enabled the german float localization in the configuration. Previously on version `6.2.1` we could add assets with the following json:

```
{
    "model_id": 477,
    "status_id": 4,
    "name": "Handyhuelle",
    "_snipeit_volltext_55": "Samsung Silicone Smartphone EF-PS926 fuer Galaxy S24+, Handy-Huelle, Silikon, Kratzfest, Schlankes Design, Dark Violet",
    "purchase_date": "2024-04-21",
    "order_number": "306-5026919-2190719",
    "purchase_cost": "20,98",
    "supplier_id": 8,
    "_snipeit_asin_56": "B0CMY2K99P",
    "_snipeit_einkaufspreis_netto_64": "20,98"
}
```

On 6.3.4, the API blocks the creation with the following error:

```
{"status":"error","messages":{"purchase_cost":["The purchase cost must be a number.","Value cannot be negative"]},"payload":null}
```

When using a float value on the JSON body like 

```
{
...
    "purchase_cost": 20.98,
...
}
```

the asset can be added. 

The returned JSON response now shows the purchase_cost as `2098` (the float divider is neglected) 
```
{
    "status": "success",
    "messages": "Asset created successfully. :)",
    "payload": {
        ...
        "purchase_cost": 2098,
        ...
        }
    }
}
```

and in the frontend the localization is applied and the purchase_cost is shown as `2.098,00`.  When GETting the asset via API, purchase_cost is not formatted as float but instead as localized string:

```
...
"purchase_cost": "2.098,00",
...
```

### Reproduction steps

1. Update/Install Snipe-IT 6.3.4
2. Ingest payload via API

### Expected behavior

Field `purchase_cost` is ingested in float and shown as float on the JSON response. Formatting is only applied in the frontend.,

### Snipe-IT Version

6.3.4

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1

**Comment by Isotop7** [comment]
The only thing remotely connected to it IMHO could be this commit:

https://github.com/snipe/snipe-it/commit/f42e5d5292869e9d457a355fbd1db7dbe1d8c29e

or the `asset->fill` function introduced here

https://github.com/snipe/snipe-it/commit/75ac7f80b9b08a9bdbac1fd05053980172250469

or these rules

https://github.com/snipe/snipe-it/commit/7e780c11870c6fee87cefc89d1615d6bd23e3f4e

**Comment by marcusmoore** [comment]
It looks like this started in v6.3.0 with the addition of the [StoreAssetRequest](https://github.com/snipe/snipe-it/blob/master/app/Http/Requests/StoreAssetRequest.php).

I'll work on a fix. Thank you for reporting and starting to troubleshoot @Isotop7

**Comment by Isotop7** [comment]
This line seems to cause it:

https://github.com/snipe/snipe-it/blob/56cb9a0f4ea0b845f8d186d54c6ddae5a93618f0/app/Models/Asset.php#L107

When changing this rule to

`'purchase_cost'    => 'nullable|numeric`

the problem persists as the API does not allow strings (what in IMHO should be correct).

When changing it to just

`'purchase_cost'    => 'nullable`

the import works again and the assets are correctly added and displayed.

But this should'nt be the best solution as it justs reverts to recent behavious. I think it would be better to fix the routine that takes the float and somehow applies the localization before storing the value in the database. The API should just accept float and should be locale-independent.

```
diff --git a/app/Models/Asset.php b/app/Models/Asset.php
index 1f4079e49..7a7133917 100644
--- a/app/Models/Asset.php
+++ b/app/Models/Asset.php
@@ -104,7 +104,8 @@ class Asset extends Depreciable
         'rtd_location_id'  => 'nullable|exists:locations,id',
         'purchase_date'    => 'nullable|date|date_format:Y-m-d',
         'serial'           => 'nullable|unique_undeleted:assets,serial',
-        'purchase_cost'    => 'nullable|numeric|gte:0',
+       #'purchase_cost'    => 'nullable|numeric|gte:0',
+       'purchase_cost'    => 'nullable',
         'supplier_id'      => 'nullable|exists:suppliers,id',
         'asset_eol_date'   => 'nullable|date',
         'eol_explicit'     => 'nullable|boolean',
```

The formatting then seems to be happen at this stage:

https://github.com/snipe/snipe-it/blob/56cb9a0f4ea0b845f8d186d54c6ddae5a93618f0/app/Models/SnipeModel.php#L24

I don't know if this is needed for the web frontend but maybe it should be not used on API calls and just check for valid float values.

**UPDATE**: When disabling the `Helper::ParseCurrency($value)` and just storing the value as it is, it seems to kind of work. Posting via API as float does work and the value is correctly localized in the frontend.
Only "issue" is, that the frontend now throws the error when manually creating an object there and using the localized value.  I think it happens because now formatting is done in this case, the value is passed down all the way to the database insertion where an error is thrown, because the value is no float.

So I think this could be solvable by not using the `ParseCurrency` call when the asset is POSTed via the API.

But I dont know if this has any downsides on other CRUD operations or any issues when not using german localization.

Just hope I could help :)

**Comment by marcusmoore** [comment]
@Isotop7 thanks for diving into this! We ended up in a similar spot and I've been eyeing how to cleanly adjust the calls to `Helper::ParseCurrency($value)` like you mentioned. I'm hoping to have a good solution soon. Thanks for your patience (and debugging 😄)

**Comment by marcusmoore** [comment]
@Isotop7 this should be fixed with #14651. Thanks again for your help in reporting and debugging.

**Comment by Isotop7** [comment]
Thank you for fixing it this fast and your awesome product 🎊

**Comment by marcusmoore** [comment]
That PR was merged so I'm going to close this. Please re-open it if it ends up not solving the issue.

Thanks again for your detailed reporting and debugging @Isotop7 😄
