### ISSUE TITLE
License not saving after creating a new one

### ISSUE THREAD

**Issue by NerdByNature123** [grokability/snipe-it#14633]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am attempting to create a new software license but after I click create new and fill out the form, nothing happens. I don't get a banner that says there is an error or a success. I enabled debug mode and there are not any errors that I can make out. I also installed a fresh version of Snipe-it and still had the same error. I attached some screenshots that came up as warnings. I hope that helps in this process

### Reproduction steps

1. Click on licenses
2. Click Create New in the top right
3. Fill out the required information
4. Click Save

### Expected behavior

It should save the information and populate the Software Licenses page. However, nothing happens.

### Screenshots

![Screenshot 2024-04-22 152651](https://github.com/snipe/snipe-it/assets/151556536/2ff9b2d9-8c75-4934-bbfb-ab264fcd9eb1)
![Screenshot 2024-04-22 152712](https://github.com/snipe/snipe-it/assets/151556536/caf651bc-6f4f-41fb-b40a-5e29b2cab81a)

### Snipe-IT Version

6.3.4

### Operating System

Windows

### Web Server

Xampp

### PHP Version

8.1.10

### Operating System

Windows 11

### Browser

Chrome/Edge

### Version

124/124

### Error messages

```shell
No errors in logs

No errors in console

php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
json
ldap
libxml
mailparse
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
sodium
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

Error not reproducible in Snipe-it Demo
```

### Additional context

Fresh Install/Upgrade
Xampp Web Server on windows
Installed manually and using GIT
Instillations completed
Database has not been directly edited

**Comment by snipe** [comment]
Can you reproduce this on the demo?

**Comment by NerdByNature123** [comment]
No I cannot reproduce this on the demo

**Comment by snipe** [comment]
Those aren't warnings, they're just debug statements. Anything in your debug-bar console under "messages"? https://snipe-it.readme.io/docs/advanced-debugging

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/advanced-debugging">Advanced Debugging</a></strong></div><div>Snipe-IT ships with the Laravel Debugbar, an amazing piece of software that lets you introspect much further into the framework and application to troubleshoot issues that may be a little harder to track down.To enable the debugbar, set the following in your .env file, and clear your config cache:Te...</div></blockquote>

**Comment by NerdByNature123** [comment]
That is what is in the first screenshot. There is only one debug message and errors. I copy and pasted it and attached a screenshot below:

![Screenshot 2024-04-23 105423](https://github.com/snipe/snipe-it/assets/151556536/347e7d4f-7bf4-412f-aed4-7f6af42ffdf5)

`[10:46:57] LOG.debug: Company Names in scopeCompanyableChildren: Array
(
    [0] => asset
    [1] => license
)`

**Comment by snipe** [comment]
That's still just debug info unfortunately. Try looking at the session or request tab and look for "messages" or "error bag"

**Comment by NerdByNature123** [comment]
I checked both the session and the request tab and neither of those messages are appearing. Everything looks normal to me

**Comment by NerdByNature123** [comment]
Issue has been resolved. Did some troubleshooting and I never removed the built-In aliases in Xampp. Once I did this, it fixed the issue. The link is below if anyone else is having this issue. Thank you for the help Snipe!

[https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases](url)
