### ISSUE TITLE
API Asset create performing invalid redirect when parameters do not validate

### ISSUE THREAD

**Issue by Sxderp** [grokability/snipe-it#14653]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When performing an API create request with invalid parameters the site will redirect me. This is NOT good. It should return the API errors. I think this has to do with #13830 and #13964.

What stands out to me is the use of `rules()` that previously did not exist. I believe Laravel `FormRequest` is doing a validation /much/ earlier in the code and when that validation fails it does a redirect. If I look at logs for the request before the redirect I can see the redirect / stack trace originates from here:

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Http/FormRequest.php#L128-L133

### Reproduction steps

```python3
import requests

token = 'TOKEN_HERE'
headers = {
    'Authorization': 'Bearer {0}'.format(token),
    'Content-Type': 'application/json',
}

api = 'https://search-tracking.cos.gatech.edu/api/v1'
data = {
    'company_id': 1,
    'purchase_cost': '6,035.00', # This is the bad value. Cannot have commas.
    'model_id': 1,
    'status_id': 2,
    'checkout_to_type': 'location',
    'assigned_location': 61,
    'serial': 'UNIQUE_SERIAL_1234',
    'asset_tag': 'UNIQUE_TAG_1234',
    '_snipeit_funding_type_7': 'state',
    '_snipeit_monitoring_20': 'none',
    '_snipeit_principal_investigator_8': 'none',
}

###

req2 = requests.post(api + '/hardware', headers=headers, json=data)
print('post redirect history', len(req2.history))
print('url', req2.url)
```
```console
$ ./test.py 
post redirect history 2
url https://search-tracking.cos.gatech.edu
```

### Expected behavior

The app should not redirect and it should provide the error messages on what was invalid.

### Snipe-IT Version

6.3.0

### Operating System

Redhat Enterprise 9

### Web Server

Apache

### PHP Version

8.1.28

**Comment by snipe** [comment]
Are you sure this is still happening on the latest version?

**Comment by spencerrlongg** [comment]
@marcusmoore would your recent PR resolve this?

**Comment by spencerrlongg** [comment]
Actually, sorry. Looks like you don't have the header `Accept: application/json` set @Sxderp - please add that and let me know if it's resolved.

**Comment by Sxderp** [comment]
> Are you sure this is still happening on the latest version?

Still happening on the latest version.

> Actually, sorry. Looks like you don't have the header Accept: application/json set @Sxderp - please add that and let me know if it's resolved.

That does fix it. I'm pretty sure older versions did not require the header, but if it's required now then this is a simple fix for me.

**Comment by spencerrlongg** [comment]
I double checked the docs and it is called out here https://snipe-it.readme.io/reference/authenticating-with-the-api

Happy that fixed it for you though, I've noticed in Laravel that it's kind of situational how flexible it is about that specific header. 

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/authenticating-with-the-api">Authenticating With the API</a></strong></div><div>To authenticate against the Snipe-IT API, you'll need to pass an Authorization, Accept: application/json and Content-Type: application/json header with every request.It should look something like this, if your API key were MY-AWESOME-API-KEY: HeaderValueAuthorizationBearer MY-AWESOME-API-KEYAcceptap...</div></blockquote>

**Comment by snipe** [comment]
> That does fix it. I'm pretty sure older versions did not require the header, but if it's required now then this is a simple fix for me.

It's been there since the API existed. https://snipe-it.readme.io/v5.4.4/reference/authenticating-with-the-api

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/v5.4.4/reference/authenticating-with-the-api">Authenticating With the API</a></strong></div><div>To authenticate against the Snipe-IT API, you'll need to pass an Authorization, Accept: application/json and Content-Type: application/json header with every request.It should look something like this, if your API key were MY-AWESOME-API-KEY: HeaderValueAuthorizationBearer MY-AWESOME-API-KEYAcceptap...</div></blockquote>
