### ISSUE TITLE
Asset History Tab shows below asset information on user side

### ISSUE THREAD

**Issue by paoleonardo** [grokability/snipe-it#14670]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Asset History not showing on new tab. it shows below the asset information (When user is log in)

### Reproduction steps

1. Log in accouct (user login) no Admin right but can access asset (view and edit)
2. access asset module
3. click history tab
4. history will show when you scroll down on asset
...

### Expected behavior

Same as admin side

### Screenshots

![screenshot](https://github.com/snipe/snipe-it/assets/168710361/45d58826-72a5-4f33-8663-ab69755529a9)

### Snipe-IT Version

v6.3.4

### Operating System

Windows

### Web Server

Apache

### PHP Version

8.1

### Operating System

Windows

### Browser

Google Chrome

### Version

124.0.6367.63

**Comment by snipe** [comment]
I believe this was fixed several versions ago.
