### ISSUE TITLE
The Button Back and Cancel in all page has been add httpss  to my URL 

### ISSUE THREAD

**Issue by zolerozeal2** [grokability/snipe-it#14677]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am a newby please help me to fix this or guide me how to solve this

The Button Back and Cancel has been add httpss  to my URL 
I can access to snipe it  with https:// xxx   but Button Back and Cancel has been add httpss  to my URL 

I have config in .env app_url  :  https://xxxxxxx 

### Reproduction steps

1.
2.
3.
...

### Expected behavior

redirect to the Right url 

### Screenshots

<img width="960" alt="Wrong URL httpss" src="https://github.com/snipe/snipe-it/assets/26618383/caab7ca7-5aab-4ebc-bdc3-04595af74f51">

<img width="960" alt="Wrong URL httpss 2" src="https://github.com/snipe/snipe-it/assets/26618383/bd8def80-a09b-42b6-8893-a2b0870faaa4">

### Snipe-IT Version

v6.3.4 build 13139 (g6f9ba6ede)

### Operating System

Window Server 2019 Standard

### Web Server

IIS

### PHP Version

8.0.30

### Operating System

Window

### Browser

Chrome

**Comment by Godmartinz** [comment]
you double check for typos? It seems like a typo.

**Comment by snipe** [comment]
It does seem a bit like a typo. we never assume protocol anywhere in the software, since we never know if the user is using TLS or not.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
