### ISSUE TITLE
[Feature Request]: Allow optional NOSAML query string

### ISSUE THREAD

**Issue by designatedsuccessor** [grokability/snipe-it#14681]
### Is your feature request related to a problem? Please describe.

We signed up for a hosted instance of Snipe-IT and noticed a compliance risk for us.  As specified on the SAML setup page (https://snipe-it.readme.io/docs/saml), the default URL for bypassing SAML is as follows:

`https://assets.example.com/login?nosaml`

This is a potential security risk and definitely a compliance risk for organizations, as it allows for password spraying and brute-forcing even for organizations that have enabled MFA via SAML.

### Describe the solution you'd like

Allow an opt-in query string to replace the _nosaml_ string.

Example: if you chose _lkjsf843rnd83r01ndfnxc_ as your query string, then you would bypass SAML with this URL:

`https://assets.example.com/login?lkjsf843rnd83r01ndfnxc`

I would create the feature as follows:
- Default would continue being _nosaml_
- Minimum length would be 8 characters
- Maximum length would be 64 characters
- Configurable within the web interface
- Once configured, automatically send a one-time email that contains the chosen URL to all super admins so at least the super admins likely have it in their email account in the (hopefully unlikely) event that they fail to note it

**Comment by uberbrady** [comment]
What we usually advise for situations like that is to contact support to have us turn on the 'SAML-only' `.env` var - this prevents the `?nosaml` override entirely. Clunky for us, from a support perspective, because it means we can't directly log in anymore. But that does solve the problem you're looking at. Reach out to support@snipeitapp.com and we'll turn that setting on for you.

**Comment by uberbrady** [comment]
Specifically, for other people wondering about this issue, the variable is `REQUIRE_SAML` and it should be set to `true`. So you need to add `REQUIRE_SAML=false` to the end of your `.env` file. See: https://snipe-it.readme.io/docs/configuration#optional-misc

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#optional-misc">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required. Don't be intimidated by the length of this page. The configurati...</div></blockquote>

**Comment by designatedsuccessor** [comment]
@uberbrady No, you are misunderstanding the problem.  The problem isn't that we can't login.  The problem is that the entire world -- anyone who is on the internet -- can bypass SSO and go straight to the regular login page.  This is a security risk:

1. It means that users could login using their local passwords rather than SSO.  SSO is where enterprises put their security features in place, but users could theoretically bypass them.
2. It also means that attackers all over the world know exactly which URL to visit to bypass every Snipe-IT SSO implementation.  Again, that's a security risk.

The reason for changing the NOSAML URL is to prevent regular users and attackers from being able to easily determine which URL will bypass SSO protections.  As it is, the Snipe-IT documentation tells the entire world how to bypass it.

Going forward, please ask more questions in understanding the intended problem before hastily closing issues.

**Comment by snipe** [comment]
@loosus Brady closed this issue because it's best addressed via the helpdesk - but as he mentioned, that's a configuration flag that we can easily turn on/off for you which disables the `nosaml` option. I believe he understood the issue that was asked. If you reach out at the address he mentioned (including your subdomain in the email please) we can turn that nosaml option off for you.

**Comment by designatedsuccessor** [comment]
@snipe just so I understand, if we ask our URL to be changed from **/login?nosaml** to **/login?lkjsf843rnd83r01ndfnxc** support is going to do that for us?

**Comment by snipe** [comment]
@loosus currently we can only either enable that nosaml parameter or disable it, we don’t have a way to customize it. We’ll add that option to our internal issue tracker, though I suppose any of that could be sufficiently fuzzed by a determined enough party. Neither of those really matter that much though, since we implement brute force prevention and throttling on local login, so someone who didn’t know an existing login would be locked out pretty quickly once they got to an actual login screen. 

Edit: typos, since I’m on my phone 😫

**Comment by designatedsuccessor** [comment]
@snipe understood.  I am asking for the feature because I think it's a sufficient middleground.  I mean, if you have a truly random 64-character string, that's better than many API keys.

Regarding throttling and lock outs: Microsoft and Google both have never figured it out, which is why they're disabling basic auth and pushing users to MFA. :)

Edit: for that matter, forcing a random string could be part of the protection.  Maybe it doesn't need to be user-chooseable.

**Comment by snipe** [comment]
The problem with enforcing it that way is that people often mess up their SAML configuration, their cert expires, someone else on the SAML admin side changes something, etc and then they’re locked out with no way back in, and they won’t necessarily have noted the magic key anywhere, and if they can’t access the env. This is why the feature exists in the first place. You’d be surprised how many times it happens in a week.

**Comment by designatedsuccessor** [comment]
@snipe I'm not really surprised, to be honest.

But at the same time, we do have compliance we have to deal with, and with other products in the past, this exact scenario has produced an audit exception where we had to ask the vendor/producer to make these changes so we could pass the audit.

**Comment by snipe** [comment]
Wouldn’t simply disabling the nosaml option cover your compliance issues though? If it’s simply not possible to get to a local login, that seems more secure than the possibility of the key being fuzzed or exposed through some other internal breach. (This was the solution @uberbrady was proposing, and what we recommend for most of our clients. That’s usually enough to clear compliance.)
