### ISSUE TITLE
CASE WHEN 'assigned_type' column returns null

### ISSUE THREAD

**Issue by ccalby** [grokability/snipe-it#14680]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

```sql
SELECT
      `assets`.`asset_tag` AS `asset_tag`,
      `assets`.`name` AS `name`,
      `assets`.`assigned_type` AS `assigned_type`,
      CASE
        WHEN `assets`.`assigned_type` = 'App\Models\User' THEN 'User' 
        ELSE 'Stock/Location'
      END AS `Responder Name`
    FROM
      `assets`   
WHERE
      (`assets`.`deleted_at` IS NULL)
LIMIT
  1048575;
```
![image](https://github.com/snipe/snipe-it/assets/680553/1fd7cd57-be9b-4e8c-bc60-5414afc8ae93)

### Reproduction steps

This works:
```sql
SELECT
      `assets`.`asset_tag` AS `asset_tag`,
      `assets`.`name` AS `name`,
      `assets`.`assigned_type` AS `assigned_type`,
      CASE
        WHEN `assets`.`assigned_type` LIKE "%\User%" THEN 'User'
        WHEN `assets`.`assigned_type` LIKE "%\Location%" THEN 'Stock/Location'
      END AS `Responder Name`
    FROM
      `assets`   
WHERE
      (`assets`.`deleted_at` IS NULL)
LIMIT
  1048575;
```
This does not:
```sql
SELECT
      `assets`.`asset_tag` AS `asset_tag`,
      `assets`.`name` AS `name`,
      `assets`.`assigned_type` AS `assigned_type`,
      CASE
        WHEN `assets`.`assigned_type` LIKE "%Models\User%" THEN 'User'
        WHEN `assets`.`assigned_type` LIKE "%Models\Location%" THEN 'Stock/Location'
      END AS `Responder Name`
    FROM
      `assets`   
WHERE
      (`assets`.`deleted_at` IS NULL)
LIMIT
  1048575;
```

### Expected behavior

Case returns correctly based on the value of `assigned_type`

### Snipe-IT Version

v6.3.4 build 13139 (g6f9ba6ede)

### Operating System

8.1.2-1ubuntu2.14

### Web Server

Apache

### PHP Version

PHP 8.1.2-1ubuntu2.14

### Operating System

Windows

### Browser

Brave

**Comment by snipe** [comment]
I don't know what this is related to - is this in our code? That LIKE query should work as expected, but I don't know what "Stock/Location" or "Responder Name" name are.
