### ISSUE TITLE
Can I remove the decimal point from the settings?

### ISSUE THREAD

**Issue by jchoong2** [grokability/snipe-it#14691]
### Is your feature request related to a problem? Please describe.

Can I remove the decimal point from the settings?

### Describe the solution you'd like

![캡처](https://github.com/snipe/snipe-it/assets/66979708/180f34ff-6821-4131-94da-2ec85ab0974c)

1,234.56   ---> 1,234

**Comment by snipe** [comment]
That's not currently possible at this time.
