### ISSUE TITLE
EULA markdown doesn't render properly when html tags are used

### ISSUE THREAD

**Issue by Azooz2014** [grokability/snipe-it#14703]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When writing down EULA using github markdown syntax in conjunction with HTML , the part where html is used it gets rendered as a plain text.

for example 
```
<div dir="rtl">
<h1>العنوان</h1>
<ul>
<li>
موضوع
</li>
<li>
موضوع
</li>
</ul>
</div>

---

<div>
<h1>Title</h1>
<ul>
<li>
Topic
</li>
<li>
Topic
</li>
</ul>
</div>
```
Expected is this:-
<div dir="rtl">
<h1>العنوان</h1>
<ul>
<li>
موضوع
</li>
<li>
موضوع
</li>
</ul>
</div>

---

<div>
<h1>Title</h1>
<ul>
<li>
Topic
</li>
<li>
Topic
</li>
</ul>
</div>

What I'm getting in the asset checkout email is like this:-

```
<div dir="rtl">
<h1>العنوان</h1>
<ul>
<li>
موضوع
</li>
<li>
موضوع
</li>
</ul>
</div>

---

<div>
<h1>Title</h1>
<ul>
<li>
Topic
</li>
<li>
Topic
</li>
</ul>
</div>
```

### Reproduction steps

1.Going to General Settings
2.Editing the default EULA
3.Enabling An Asset to use the default EULA
4.Checking out an asset to a user
...

### Expected behavior

Correctly rendered markdown like the below:-
<div dir="rtl">
<h1>العنوان</h1>
<ul>
<li>
موضوع
</li>
<li>
موضوع
</li>
</ul>
</div>

---

<div>
<h1>Title</h1>
<ul>
<li>
Topic
</li>
<li>
Topic
</li>
</ul>
</div>

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/7429229/ce0d346c-8c96-4ba4-82de-ec7f557d69d4)

### Snipe-IT Version

Version v6.2.3 - build 11759 (master)

### Operating System

Ubuntu 22.04.3 LTS

### Web Server

Apache/2.4.52

### PHP Version

8.1.2

### Operating System

Windows 11 Pro

### Browser

Firefox

### Version

125.0.3

**Comment by Azooz2014** [comment]
@snipe Is there any way for RTL languages to be set to the right with markdown without HTML involvement? I would love and appreciate your support.

**Comment by snipe** [comment]
I believe these improvements are already underway - #14679

**Comment by Azooz2014** [comment]
Awesome! I'll update to the new version and test out if the problem is fixed, thanks for your support snipe 👍

**Comment by Azooz2014** [comment]
Hi @snipe I tested out version 6.4.0 which contained #14679 but those improvements didn't affect EULA markdown.
After some deep digging turned out the problem was from `Parsedown` library used to parse markdown, specifically with the function `setSafeMode()` which causes the HTML code when writing down markdown to be escaped as a security measure.
My work around was to modify `parseEscapedMarkedown()` function by setting `$Parsedown->setSafeMode(true)` to `$Parsedown->setSafeMode(false)` but that maybe would have some security risks.
I dunno if there's other way, I would love to hear from you if there's is any other fix you would suggest.

**Comment by snipe** [comment]
You should definitely not have to mess with the markdown parser - maybe something we can add to the generic template it imports?

**Comment by Azooz2014** [comment]
You're totally right, from my side I'm using snipe-it internally and it's not exposed to the internet or any ports are exposed and it's behind a firewall so it's probably gonna be fine.

Maybe we could add some kind of an HTML sanitiser like it was recommended from the developer of Parsedown.

> Security
> 
> Parsedown is capable of escaping user-input within the HTML that it generates. Additionally Parsedown will apply sanitisation to additional scripting vectors (such as scripting link destinations) that are introduced by the markdown syntax itself.
> 
> To tell Parsedown that it is processing untrusted user-input, use the following:
> 
> $Parsedown->setSafeMode(true);
> 
> If instead, you wish to allow HTML within untrusted user-input, but still want output to be free from XSS it is recommended that you make use of a HTML sanitiser that allows HTML tags to be whitelisted, like [HTML Purifier](http://htmlpurifier.org/).
> 
> In both cases you should strongly consider employing defence-in-depth measures, like [deploying a Content-Security-Policy](https://scotthelme.co.uk/content-security-policy-an-introduction/) (a browser security feature) so that your page is likely to be safe even if an attacker finds a vulnerability in one of the first lines of defence above.
> 
> Safe mode does not necessarily yield safe results when using extensions to Parsedown. Extensions should be evaluated on their own to determine their specific safety against XSS.

I'm not too sure what's the best way to implement that since i don't have much experience with PHP or the way PHP applications are architected .

**Comment by snipe** [comment]
Hi @Azooz2014 :) Yeah, we have to escape that content for security reasons. The method, for any of those playing the home game, is here:

https://github.com/snipe/snipe-it/blob/6823aabf929315f0a2b0615797edc4722c0e05df/app/Helpers/Helper.php#L86-L94

**Comment by snipe** [comment]
Allowing arbitrary user-created values to be executed without escaping is a recipe for disaster :(

**Comment by Azooz2014** [comment]
What you saying is totally true but in my case it was the only way to make markdown recognize RTL languages, using HTML was the only way for that.
I've played around in the Paresdown demo website and they allow the use of HTML along with markdown but escapes XSS scripts, I think the way they did it is the best of both worlds.

I'll read more about HTML sanitisers  during my free time and if I found a way to implement it into snipe-it I'll let you know :)
Thanks alot @snipe.

**Comment by snipe** [comment]
Awesome, @Azooz2014 - really stoked you're looking into the RTL stuff. It's been on my list for a *million* years, but also not being fluent in any RTL languages, it was a lot harder for me to test/check any of my previous efforts. Moving the needle even a little is hugely appreciated.

**Comment by snipe** [comment]
Is this only happening in emails? While we do use markdown, the emails themselves use an HTML template - perhaps that's where you might want to check and possibly add the RTL declaration? `resources/views/vendor/mail/html/layout.blade.php`
