### ISSUE TITLE
[Feature Request]: Disable request button for "deployed" assets

### ISSUE THREAD

**Issue by NickNck** [grokability/snipe-it#14706]
### Is your feature request related to a problem? Please describe.

Hi all, When an asset is marked as requestable i notice that once a user requests for an asset and is then deployed, other users can still request for that same asset while it is deployed to someone else. It would be great if there could be a setting that disables the request button once an asset is in the deployed when someone else requested and is using it and can only request it once it is marked as deployable.

### Describe the solution you'd like

It would be great if there could be a setting that disables the request button once an asset is in the deployed when someone else requested and is using it and can only request it once it is marked as deployable.

**Comment by snipe** [comment]
I'm pretty sure this has been requested before. We haven't implemented it because a request doesn't mean "give me this immediately", it could mean "give me this when it's available", and we want to allow people to join the queue. 

I'll try to think about ways we can accommodate more use-cases.
