### ISSUE TITLE
I cannot see the items created in Snipeit

### ISSUE THREAD

**Issue by cam-cart** [grokability/snipe-it#14705]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Finally after many attemtps I could get the snipeit working ( at least it seems), but when I started to create item in company and devices I found they were not reflected in the lists. I checked the Mariadb DB in the command line and found they are already in it, but for some reason not showed in the snipeit webpages.

<img width="547" alt="image" src="https://github.com/snipe/snipe-it/assets/169277364/8d154725-cce6-4ed2-9d99-295f0128f13a">

if I try to create a item that already existed, it is recognized and says the item is already created.

<img width="782" alt="image" src="https://github.com/snipe/snipe-it/assets/169277364/f228eba2-7331-4206-84d7-9abf7406ce6c">

but none are showed in the dashboard,

<img width="914" alt="image" src="https://github.com/snipe/snipe-it/assets/169277364/708dc49c-8820-48dd-99d1-43982ca2da3d">

That is not only for the Companies , also for user (here is a little diferent because it says 2m but showed none) , etc....

### Reproduction steps

1. Just install the snipe it 
2. Start to create items
3. No devices or items showed in dashboard or other list
...

### Expected behavior

ITems listed in the dashboard and other filters

### Snipe-IT Version

v6.4.0 build 13351 (gdb2baae758) 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

 8.3.6 

### Operating System

windows

### Browser

Firefox

### Version

125.0.3 (64-bit)

### Error messages

```shell
[2024-05-08 14:48:48] production.ERROR: Your APP_URL in your .env is misconfigured - it is: 192.168.19.132. Many things will work strangely unless you fix it
```

### Additional context

Fresh Install,  first time using it. Linux beginner.

**Comment by snipe** [comment]
Snipe-IT does not work on PHP 8.3, per [the requirements documents](https://snipe-it.readme.io/docs/requirements). Downgrade to PHP 8.1 or wait a few weeks until Snipe-IT v7 is out.

**Comment by cam-cart** [comment]
mmmmm, OK, got it. Thanks for the info.
