### ISSUE TITLE
Creating asset - 500 Server error 

### ISSUE THREAD

**Issue by cam-cart** [grokability/snipe-it#14718]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

after fresh install whenever I try to create a new asset, with the option "checked out to" a USER,  I got a "500 error", however once I checked the list again the asset is created correctly.

<img width="516" alt="image" src="https://github.com/snipe/snipe-it/assets/169277364/56bbd9e1-c6ba-4f16-9939-27c87921bf11">

![image](https://github.com/snipe/snipe-it/assets/169277364/dc203c05-bdec-4d92-a32d-a730a3677805)

![image](https://github.com/snipe/snipe-it/assets/169277364/d6a9e7c6-54df-4d9d-9c0c-e088848bbb64)

Then when we checked again, and it seems is created correctly:

<img width="616" alt="image" src="https://github.com/snipe/snipe-it/assets/169277364/9bb065b5-c89c-43c0-b08c-36d42768cdeb">

### Reproduction steps

Process detailed in the images.

### Expected behavior

Regular asset creation

### Screenshots

attached earlier

### Snipe-IT Version

v6.4.0 build 13351 (gdb2baae758) 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.0.30

### Operating System

Ubuntu Server

### Browser

chrome

### Version

125.0.3 (64-bit)

### Error messages

```shell
ParseError
syntax error, unexpected identifier "RoundingMode"
http://192.168.19.133/hardware

syntax error, unexpected identifier "RoundingMode"
var/www/snipe-it/vendor/brick/math/src/RoundingMode.php#16
ParseError
13
14
15
16 
17
18
19
20
 * regardless the digits' contribution to the value of the number. In other words, considered
 * as a numerical value, the discarded fraction could have an absolute value greater than one.
 */
enum RoundingMode
{
    /**
     * Asserts that the requested operation has an exact result, hence no rounding is necessary.
```

### Additional context

Fresh install, checking options to deploy in production

**Comment by snipe** [comment]
I think the part of the stack trace you included is the wrong part of the error. That is part of the framework, and therefore probably not the issue. Can you show me the lines in your codebase the corresponding 67 and 66 of your stack trace from the screenshot, so we can better isolate where the issue might be?

**Comment by cam-cart** [comment]
Hi, thanks for answering. The 66 and 67 next:

![image](https://github.com/snipe/snipe-it/assets/169277364/7e3d8e80-09f1-403d-99d1-95fcf1a36b84)

![image](https://github.com/snipe/snipe-it/assets/169277364/a88cae79-9c12-4ddf-9df3-7548bb7d08ef)

**Comment by marcusmoore** [comment]
@cam-cart this is strange...can you try upgrading composer to the latest version, deleting your vendor directory, and doing another `composer install`? I noticed someone had a [similar issue](https://github.com/ramsey/uuid/issues/437#issuecomment-2089809183) and had success updating to 2.7.4. I didn't experience the issue using PHP 8.0.30 and composer 2.7.6...

**Comment by marcusmoore** [comment]
@cam-cart I'm going to close this for now but ping me if you still have issues after the steps I mentioned above.

**Comment by cam-cart** [comment]
<img width="670" alt="image" src="https://github.com/snipe/snipe-it/assets/169277364/675efada-cd0b-4909-992c-0e427f4f6bc1">

it seems it solve the problem, the procedure:

sudo composer update    
cd /www/html/snipe-it   
sudo rm -r vendor     
sudo composer install   
systemctl restart apache2

I am going to check all options again to be sure everything is going well. Thanks!

**Comment by marcusmoore** [comment]
@cam-cart glad to hear that worked but you should avoid running composer with sudo. There's a note with some more details on [this page](https://snipe-it.readme.io/docs/install-dependencies).
