### ISSUE TITLE
[Feature Request]: Display asset image on label

### ISSUE THREAD

**Issue by indyduke** [grokability/snipe-it#14713]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Snipe-IT version: v6.2.3 build 11759 
PHP Version:8.1.28Laravel Version:8.83.22
Database Driver: mysql

I would like to know if there is a way to do the following.
I'm in my assets and would like to print a label.
the asset label should have a
picture, price, desc. and barcode, that should be printed on the label. (selectable which option i want to print on label, but picture is of product)

this way I can print a label on a 3" x 2" etc. label like a business card size. with the above info on it.

### Describe alternatives you've considered

odoo

**Comment by snipe** [comment]
Have you set up your labels in Admin Settings > Labels? That should allow you to do exactly what you're referring to.

**Comment by indyduke** [comment]
I have tried but I can not seem to get the asset picture there.
Thank you for your response.

**Comment by snipe** [comment]
Can you show me your label settings and your Admin Settings > Branding section?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by indyduke** [comment]
I'll try to send another,,from today.

**Comment by indyduke** [comment]
I see if these are selected it will print that but not the device image,
it's not an option. Like

**Comment by indyduke** [comment]
If I click generate label, pic does not show up.

**Comment by marcusmoore** [comment]
Hi @indyduke. Are you asking if it is possible to have the image of the asset appear on the label in place of the "Label Logo" that is set in the Branding settings?

**Comment by indyduke** [comment]
Yes I belive so..
So that if I generate label from which ever asset I have selected it will
use the selected asset device image not the branded logo / company logo

**Comment by marcusmoore** [comment]
@indyduke unfortunately that's not currently possible. It might appear in a future version but there are no guarantee.

**Comment by indyduke** [comment]
Ahh ok thank you,
But it could be possible.

Thanks

**Comment by marcusmoore** [comment]
@indyduke it's possible but I'm not sure it will appear in the future.

Can you give m more information about your use case? If the asset doesn't have an image would you want it to fall back to the model's image or the company logo?

**Comment by indyduke** [comment]
If no image probably fall back to company logo.
...
...
I have some computers, and  games motherboard based games no cases .
But these games have like their main logo ,,/ splash screen I go
by.attached is one pic. Or just the logo that says fusion5 or whichever the
game is.
Or part.
So on my parts bins I print label with desc.
Part #
Model, price
Etc
And
Once printed the label shows the connector/ item in bin.
This also goes for my boards or computers, I box them and inventory them
all print label with pic of board or game and all needed info to outside
box

**Comment by marcusmoore** [comment]
Thanks for the details @indyduke. We'll take this into account in the future.

**Comment by indyduke** [comment]
Thank you for your response.
