### ISSUE TITLE
Snipe-IT shows no UI, only a page with text like HTML 

### ISSUE THREAD

**Issue by AG-remora** [grokability/snipe-it#14712]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have successfully installed snipe IT but when i click on certain images or file it shows me the image attached.
![image](https://github.com/snipe/snipe-it/assets/116623639/ae13caa7-dd8e-41a7-83fa-a437b8db5925)

### Reproduction steps

1.Logi into Snipe IT
2.Click on the logo

### Expected behavior

i expect it show snipe IT with actual UI.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/116623639/847ceab5-2af6-4cc4-8e07-8c932916bb29)

### Snipe-IT Version

v6.4.0 build 13351

### Operating System

Ubuntu 20 04

### Web Server

Apache 2

### PHP Version

7.4.3-4ubuntu2.22

### Operating System

Ubuntu 20 04

### Browser

Chrome

### Version

latest

### Error messages

```shell
no error shoen
```

### Additional context

Is this a fresh install or an upgrade?
yes fresh install
What OS and web server you're running Snipe-IT on
windows and chrome
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual

**Comment by snipe** [comment]
My guess would be that your `APP_URL` is misconfigured in your `.env` file. [Per the documentation](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings), the APP_URL should be the complete URL to your Snipe-IT installation, *including* the `http://` (or `https://` if you're running over TLS.)

<img width="795" alt="Screen Shot 2022-07-28 at 11 35 47 PM" src="https://user-images.githubusercontent.com/197404/181698021-de470225-4865-4786-bd48-9a9cdf2399d2.png">

**Comment by AG-remora** [comment]
My server is on prem-based no SSL running as VMware VM.

Now my APP URL is only the ip address without https/http.

**Comment by snipe** [comment]
As I mentioned, you will need the full URL as your APP_URL, including the protocol, no trailing slash.
