### ISSUE TITLE
[Feature Request]: Add option to create custom fields to Licenses

### ISSUE THREAD

**Issue by pawelgendosz** [grokability/snipe-it#14738]
### Is your feature request related to a problem? Please describe.

Unable to create custom fields to Licenses

### Describe the solution you'd like

Add custom fields option to licenses. Currently, they are available only for assets. Adding fields like payment method or payment frequency as custom fields would be really useful.

**Comment by mauro-miatello** [comment]
https://github.com/snipe/snipe-it/issues/4261
