### ISSUE TITLE
[Feature Request]: make Licence File downloadable for assigned User

### ISSUE THREAD

**Issue by JKatXGME** [grokability/snipe-it#14732]
### Is your feature request related to a problem? Please describe.

Some Software requires the Key to be in a specific file to be useable. Unlike the Key Field itself, the assigned User can not view/download the attached File.
Inserting the contents of the file into the Key Textbox, the enduser won't know what to do with it and also can't read the note, i left. Also website layout on the licence asset page is broken when entering way too long text.
Screenshot of broken website layout:
![view licence broken rendering when too much text in key textbox](https://github.com/snipe/snipe-it/assets/7427960/15db3573-c314-4b01-8fac-e19dc6a150c6)
(only the top bar has been redacted)
Can be reproduced by entering a very long Licence Key.

### Describe the solution you'd like

Maybe a checkbox per Asset/Licence to control, if a user, who has been assigend the Asset/Licence should be able to view/download attached File(s)

### Describe alternatives you've considered

Make the Notes viewable to assigned Users to leave them a description. Maybe even an additional field. In that case, the handling of the key textbox should probably be changed in the licence page to classic multi line textbox to avoid ultra long horizontal scrollbars for the whole page.

**Comment by snipe** [comment]
I'm not sure this is a feasible option, since different license keys will be in different formats. We'll keep it in mind as we progress forward with license improvements though.
