### ISSUE TITLE
Accept asset signature PDF file with Chinese display box

### ISSUE THREAD

**Issue by friendwnt** [grokability/snipe-it#14744]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello!
This is my first time using Git and I consulted with you in poor English. Regarding the PDF file generated by accepting asset signatures, it cannot display Chinese. I feel like it is the same as#11175 # 1656 # 14052, but I really don't know where to modify the font.

### Reproduction steps

1.checkout asset
2.accept eula
3.download accepted-eula-.pdf
...

### Expected behavior

I hope to know in which file to modify the chinese font.
The following is the Chinese content that EULA cannot display.
最终用户许可协议（End User Licence Agreement，EULA），指的是一家公司的软件与软件的使用者所达成的协议，此协议一般在软件安装时出现。如果使用者拒绝接受这家公司的EULA，那么便不能安装此软件。最终用户许可协议是软件应用程序作者或者发布者与应用程序使用者之间的合法合同。最终用户许可协议（EULA），通常是指“软件许可”，它与租赁协议类似；用户同意支付软件的使用费用，并且向软件作者或者发行者承诺遵守EULA中规定的所有约束条件。用户被告知，当他们打开软件包的包装、打开CD盒的封条、将卡片寄回给软件发行者、安装应用程序、执行下载文件或者简单的使用应用程序的时候就意味着他们已经“接受”了EULA中的条款。用户可以寄回软件产品或者在安装过程中当EULA提示接受按钮的时候点击“我不接受”来拒绝这个协议。

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/170397597/edbfc742-b17d-45d4-bf93-8daa9d19f42b)

### Snipe-IT Version

 v6.4.1 - build 13386 (master)

### Operating System

CentOS7.9

### Web Server

Apache

### PHP Version

PHP 7.4.33 (cli) (built: Apr 10 2024 09:34:29) ( NTS )

### Operating System

Windows 11

### Browser

GoogleChrome, Microsoft Edge

### Version

124.0.6367.209

**Comment by snipe** [comment]
Hello and welcome! This is, I think, unfortunately an issue with the PDF library we use itself. We have a PR to try to work around this, but it's pretty awful (sorry @uberbrady - it's just a hard problem to solve). https://github.com/snipe/snipe-it/pull/14235
