### ISSUE TITLE
secure phone

### ISSUE THREAD

**Issue by Malik7264** [grokability/snipe-it#14759]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

sudo chown -R my-user:www-data /var/www/snipe-it
sudo usermod -a -G www-data your-linux-user
sudo find /var/www/snipe-it -type f -exec chmod 664 {} \;
sudo chmod -R 775 /var/www/snipe-it/storage
sudo chmod -R 775 /var/www/snipe-it/public/uploads
sudo chmod -R 775 /var/www/snipe-it/bootstrap/cache

### Reproduction steps

1.
2.
3.
...
sudo chown -R my-user:www-data /var/www/snipe-it
sudo usermod -a -G www-data your-linux-user
sudo find /var/www/snipe-it -type f -exec chmod 664 {} \;
sudo chmod -R 775 /var/www/snipe-it/storage
sudo chmod -R 775 /var/www/snipe-it/public/uploads
sudo chmod -R 775 /var/www/snipe-it/bootstrap/cache

### Expected behavior

sudo chown -R my-user:www-data /var/www/snipe-it
sudo usermod -a -G www-data your-linux-user
sudo find /var/www/snipe-it -type f -exec chmod 664 {} \;
sudo chmod -R 775 /var/www/snipe-it/storage
sudo chmod -R 775 /var/www/snipe-it/public/uploads
sudo chmod -R 775 /var/www/snipe-it/bootstrap/cache

### Screenshots

![Image](https://github.com/users/Malik7264/projects/1/assets/170526159/e871cb77-c544-4332-87be-4b043b35a52d)

### Snipe-IT Version

![Image](https://github.com/users/Malik7264/projects/1/assets/170526159/e871cb77-c544-4332-87be-4b043b35a52d)

### Operating System

![Image](https://github.com/users/Malik7264/projects/1/assets/170526159/e871cb77-c544-4332-87be-4b043b35a52d)

### Web Server

![Image](https://github.com/users/Malik7264/projects/1/assets/170526159/e871cb77-c544-4332-87be-4b043b35a52d)

### PHP Version

![Image](https://github.com/users/Malik7264/projects/1/assets/170526159/e871cb77-c544-4332-87be-4b043b35a52d)

**Comment by snipe** [comment]
I have no idea what this means and the screenshots are broken. Please open a new issue and follow the issue template so we have the information we need to be able to help you.
