### ISSUE TITLE
[Feature Request]: Delete Bulk user using Excel Upload or to Filter Multiple user using Employee ID.

### ISSUE THREAD

**Issue by OptimusPrm9** [grokability/snipe-it#14765]
### Is your feature request related to a problem? Please describe.

I have More Than 2K users and created initially while Exploring Snip-It but now that database is has current data and i want to delete the users with no Asset allocation or Resigned Staff but Currently i have to do this one by one and there are around 1.2k usr to be removed. 

### Describe the solution you'd like

i need a filter option where i can filter multiple user using comma separated Employee ID then i can select and delete the users.

**Comment by snipe** [comment]
I think you should be able to sort users by assets assigned to them, select all and delete, no?

**Comment by snipe** [comment]
https://github.com/snipe/snipe-it/assets/197404/2f32e222-c51c-4c62-ae85-eb61d62b3486

**Comment by OptimusPrm9** [comment]
yes but i have delete the user who don't have anything assigned for e.g.. some user might not have any asset assigned to them but they might have some software license assigned to them which they will use in common PC in there department, so if will will filter user with no asset and they might have any other thing assigned to them to also might get deleted.

**Comment by snipe** [comment]
Sure, but on that confirmation page, it shows you the counts of other things assigned to them (licenses, accessories, etc) so you can just de-select users with things assigned to them.
