### ISSUE TITLE
[Feature Request]: Add permission to print all assigned or email all assigned

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#14763]
### Is your feature request related to a problem? Please describe.

Until now, we used the features (but I think the way we used it was more a bug...) `Print All Assigned` and `Email List of All Assigned` for our HR Department so they could automatically send an email trough Snipe-IT to the users who leave the company. In addition, they also used the function `Print All Assigned` to see what is checked out to the users to write this into the confirmation of termination.

When I installed and configured Snipe-IT about a year ago, I didn't want the HR to see all Assets and stuff and just wanted them to see all users and give them the ability to send the email through Snipe-IT and see what the user has checked out.

I achieved this, by creating a user for our HR Department and just grant to view the users. Every other permission is denied.
![image](https://github.com/snipe/snipe-it/assets/112496896/8a5da2f2-84d1-4e69-803b-b8bf37b286cc)

I saw, that with this permission, this user just saw every user and saw the counter how many items that are checked out to the user, but cannot see the specific Assets. Like in this example:
![image](https://github.com/snipe/snipe-it/assets/112496896/b7be4d4f-b61e-452d-8719-75fccb575e2e)

For some reason, for the Licences is not even the counter visible and the Accessories are listed like normal...
_View from the HR User:_
![image](https://github.com/snipe/snipe-it/assets/112496896/93ce8e17-ee88-422b-97b5-9d89d126e913)
_View from my Admin User that has Super User Permission:_
![image](https://github.com/snipe/snipe-it/assets/112496896/05347c8b-2e82-4882-8328-081a82a70267)

They then could use these two buttons to send the email to the user with all his assigned items, and they also were able to use the `Print All Assigned` button to get the PDF where all items are listed, so they could still see the assigned assets (like if it's a notebook, iPhone or both for example)
![image](https://github.com/snipe/snipe-it/assets/112496896/8a78c1ef-858c-4d86-a9c2-5fbee6e16ec8)

Since one of the last updates, the ability for our HR User to send the email or print all assigned is not working anymore. They just get an error message:
![image](https://github.com/snipe/snipe-it/assets/112496896/cd758c22-fd3f-4065-a0a3-d78cb3172f4e)

### Describe the solution you'd like

Can you please bring this ability back? Maybe you could solve this by adding a separate permission for these two buttons that I can set to my group with the HR Users.

Additionally, it would be great to have some more permissions to set about the users module:

Permission to...
- use the `Print All Assigned` Button
- use the `Email List of All Assigned` Button
- see all assigned items in the Assets, Licences, etc. Tabs on the User View

In this way, I could give our HR Users the rights to see the assets that are assigned to the users, but they cannot see more information about these assets (like the history, audits, etc.).

### Additional context

If you have more questions about this, feel free to ask, I can give you more information about it. 😊
Thank you!

**Comment by snipe** [comment]
Hi there - do you have full multiple company support turned on? If so, do the HR user and the user to be emailed being to the same company?

**Comment by floschoepfer** [comment]
Hi snipe, thanks for your response.
Yes, full multiple company support is enabled. And the HR user belongs to the same company. We have 3 companies in Snipe-IT and I created three different HR users for each company and set them to the respective company.

Also, I want to highlight, that a couple of weeks ago, it worked just fine. Maybe one of the last updates changed some permissions?

**Comment by floschoepfer** [comment]
Hey @snipe, I hope you are doing well! How's about this case? Do you need more information from my side?
Thanks for a quick update :)

**Comment by floschoepfer** [comment]
Hello @snipe 
Were you able to look about this case? Thank you for a quick update.
Best regards

**Comment by snipe** [comment]
As far as I know, this was fixed a while back.

**Comment by snipe** [comment]
Was fixed in https://github.com/snipe/snipe-it/commit/dc62e393c304e7a9400c7100632ee153d1ecdc5b

**Comment by floschoepfer** [comment]
Oh, I didn't saw that, thanks for the reminder. I did not update the system since then.
So I just updated my system and now, I was able to use the `Print All Assigned` function with the hr-user again, But the mailing function doesn't work on any user anymore since I now updated to v7.0.5. I get an error 500. Can you help me with this?


`Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:0A000086:SSL routines::certificate verify failed`

![image](https://github.com/snipe/snipe-it/assets/112496896/5a48c361-9850-43ab-8bd9-24c6317551bc)

**Comment by snipe** [comment]
@floschoepfer that seems like a different issue, related specifically to SSL certs. I'll close this issue, but you can create a new one asking for help with the email stuff.
