### ISSUE TITLE
[Feature Request]: Allign maintainer container label with OCI Image Format Specification

### ISSUE THREAD

**Issue by schewara** [grokability/snipe-it#14772]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

As the  Image itself uses the the labels/annotations from the [OCI Image Format Specification](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys),
it would be great to replace the legacy `maintainer` label with the equivalent `org.opencontainers.image.authors` label in the Dockerfiles to be in line with the rest of the labels.

### Additional context

Current labels from the latest container shows that the `maintainer` label is not in line with the other ones.

```json
        "Labels": {
            "maintainer": "Brady Wetherington \u003cbwetherington@grokability.com\u003e",
            "org.opencontainers.image.created": "2024-05-22T17:43:01.695Z",
            "org.opencontainers.image.description": "A free open source IT asset/license management system",
            "org.opencontainers.image.licenses": "AGPL-3.0",
            "org.opencontainers.image.ref.name": "ubuntu",
            "org.opencontainers.image.revision": "986d5641f64b72ea86c288c24069512db672d191",
            "org.opencontainers.image.source": "https://github.com/snipe/snipe-it",
            "org.opencontainers.image.title": "snipe-it",
            "org.opencontainers.image.url": "https://github.com/snipe/snipe-it",
            "org.opencontainers.image.version": "v6-latest"
        },
```

**Comment by snipe** [comment]
Not sure what this even means, but would welcome a PR with more info.
