### ISSUE TITLE
Add the option to configure the amount of fields for labels

### ISSUE THREAD

**Issue by jzelle** [grokability/snipe-it#14774]
### Is your feature request related to a problem? Please describe.

Currently in the DefaultLabel, only 4 fields are displayed. However I need more, 6 or 7 (mostly custom fields).

Configured:
![image](https://github.com/snipe/snipe-it/assets/124208724/4f8a218d-a346-4890-ba77-b06089704489)

Visible on label:
![image](https://github.com/snipe/snipe-it/assets/124208724/12a319ce-54f0-410b-baf3-142a7dd00b52)

### Describe the solution you'd like

I would like to have the option to configure the amount of fields myself.

### Describe alternatives you've considered

Adding multiple fields behind each other (via the options in Field Definitions), partly solves the problem. However there is a pipe delimiter which should not be displayed.

Also I just need more fields :)

**Comment by swift2512** [comment]
I am not an expert and don't have programming skills, but I think this could by achieved by creating your own label php file in snipe-it\App\Models\Labels\Sheets\ folder. I would use already available label, which is closest to what I need, as a template.

**Comment by Godmartinz** [comment]
👋 @jzelle, @swift2512 has the right idea here. Currently there isn't a way to enter a new label using the GUI. You could make your own label template or what I would recommend is to double up your options per field like so: 
<img width="784" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/7bd85d88-9dda-4dc1-82cc-3d251e653304">

This will allow you to squeeze in extra data per line: 
<img width="1021" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/8c398279-3b20-455f-a989-c0bc88ac8e1a">

Hope this helps.

**Comment by jzelle** [comment]
Thanks for the input. Managed to create custom label and will tweak it :) .
