### ISSUE TITLE
Server 500: When editing groups that were created via the API

### ISSUE THREAD

**Issue by judokan9** [grokability/snipe-it#14771]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If I create a group via API explorer or via curl, I cannot edit it in the UI afterwards. Unless I change the call
From:
```
curl --request POST \
     --url https://develop.snipeitapp.com/api/v1/groups \
     --header 'Authorization: Bearer TOKEN' \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '{"name":"testgroup"}'
```
Or:
```
curl --request POST \
     --url https://develop.snipeitapp.com/api/v1/groups \
     --header 'Authorization: Bearer TOKEN' \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '{
                   "name":"testgroup",
                   "permissions": "{}"
                 }'
```

**To**:
```
curl --request POST \
     --url https://develop.snipeitapp.com/api/v1/groups \
     --header 'Authorization: Bearer TOKEN' \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '{
                   "name":"testgroup",
                   "permissions": {}
                 }'
```
Furthermore, a list of all arguments also works, but not as a string:
```
curl --request POST \
     --url https://develop.snipeitapp.com/api/v1/groups \
     --header 'Authorization: Bearer TOKEN' \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '{
                   "name":"testgroup",
                   "permissions": {"superuser": "0","admin": "0",.....}
                 }'
```

I can also create new permissions that do not exist:
```
curl --request POST \
     --url https://develop.snipeitapp.com/api/v1/groups \
     --header 'Authorization: Bearer TOKEN' \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '{
                   "name":"testgroup",
                   "permissions": {"MySuperPermission": True}
                 }'
```

### Reproduction steps

1. Open [https://snipe-it.readme.io/reference/groupsid-1](https://snipe-it.readme.io/reference/groupsid-1)
2. Enter a name for a new group
3. Hit "Try it"
4. Try to edit the Group in the UI

Check the other steps above
...

### Expected behavior

If only a name is given, I would expect a group to be created with all valid fields.
Furthermore, if only some of the fields are specified, I would expect the backend to supplement the remaining fields

The fields can be passed as a string as documented.

**Like:**

```
curl --request POST \
     --url https://develop.snipeitapp.com/api/v1/groups \
     --header 'Authorization: Bearer TOKEN' \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '{
                   "name":"testgroup",
                   "permissions": '{"superuser": "0","admin": "0",.....}'
                 }'
```

### Snipe-IT Version

v6.3.4 - build 13226 (master)

### Operating System

Linux

### Web Server

From latest snipe/snipe-it docker image

### PHP Version

From latest snipe/snipe-it docker image

### Operating System

Pop-OS

### Browser

Google Chrome

### Version

125.0.6422.76

**Comment by snipe** [comment]
This should be fixed in v7
