### ISSUE TITLE
Unable to save any SAML Settings

### ISSUE THREAD

**Issue by x3inspire** [grokability/snipe-it#14792]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I need to renew application certificate in Microsoft Entra ID.
I unable to save any settings under the SAML settings including the FederationMetadata.xml. Regardless of whether SAML is enabled, any data is uploaded or any other settings are checked, upon saving, I get a 403 Forbidden error.

Even i just want to disable my SAML setting and save, i'm getting error 403 Forbidden.

All other capabilities seem to be working in Snipe-IT including using SAML login using old certificate.

### Reproduction steps

1. Go to Settings/SAML
2. Click on Save at the bottom with or without changes
3. 403 Forbidden error is displayed
...

### Expected behavior

I would expect the settings to save

### Snipe-IT Version

v6.4.2 - build 13487

### Operating System

Ubuntu

### Web Server

Litespeed Enterprise

### PHP Version

8.1.28

**Comment by x3inspire** [comment]
Ok nvm, the problem is because of ModSecurity by cPanel.

**Comment by snipe** [comment]
Thanks for updating us!
