### ISSUE TITLE
undeployable status labels presented incorrectly

### ISSUE THREAD

**Issue by matreicht** [grokability/snipe-it#14804]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When displaying the undeployable statuslabeled assets, they are presented with an X instead of a red dot as in statuslabels.  I attached 2 images to show you what i mean exactly. I remedied the issue by altering multiple files:

/path/to/snipe-it/resources/views/statuslabels/index.blade.php
I modified the i class for table.undeployable: <i class="fas fa-circle text-red"></i>

/path/to/snipe-it/resources/views/partials/bootstrap-table.blade.php
I added the lines:
'undeployable': '{{ strtolower(trans('general.undeployable')) }}',

case 'undeployable':
                        text_color = 'red';
                        icon_style = 'fa-circle';
                        text_help = '';
break;

/path/to/snipe-it/resources/views/layouts/default.blade.php
modified the line for undeployable type:
class="far fa-circle text-red fa-fw"></i>

 

### Reproduction steps

1.check describe the bug section

### Expected behavior

The undeployable statuslabel has the same red dot everywhere on the site

### Screenshots

![snipeitissue2](https://github.com/snipe/snipe-it/assets/140602608/256cda1a-c6ff-45b6-b0e9-0a8cbcd865fd)
![snipeitissue1](https://github.com/snipe/snipe-it/assets/140602608/d59b0e2e-7073-4871-97fa-df00418d8dfa)

### Snipe-IT Version

6.3.4

### Operating System

Ubuntu 22.04

### Web Server

nginx

### PHP Version

8.1.27

**Comment by snipe** [comment]
The symbols in the sidebar are not directly related to the ones in table, just the colors (for example, the circle being an outline versus being solid). The listings in the sidebar work a little bit differently since we wanted to give the sidebar visual that they are one of many that cannot be deployed (like BYOD), which don't always have their own icon in the listings.
