### ISSUE TITLE
Accessory and Consumables View problem on users page after it's assigned

### ISSUE THREAD

**Issue by addex12** [grokability/snipe-it#14812]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have an issue getting the assigned accessories and component lists on users page and also when I try to email all assigned it will not list assigned consumables but others.

### Reproduction steps

1. I Assigned lists of Accessories, consumables and components to users from admin side. 
2. I emailed all assigned to that same user but the user only gets Accesories not consumables and components.
3. The user is not getting the Accessories and components that are assigned to him/her but can get lists of consumables.

...

### Expected behavior

I wish the user can get the lists of all assest that admin assigned to him/her, and when admin send all assigned asset to the user by email I wish all the lists will be sent properly to the users.

### Snipe-IT Version

6.4.2

### Operating System

ubuntu

### Web Server

Apache

### PHP Version

8

**Comment by snipe** [comment]
Components cannot be assigned to a user so they will never show up in that email

**Comment by snipe** [comment]
Accessories do currently show up in the "Email all assigned" emails. We did discover that consumables were not being emailed, but if we fix this, I also suspect this will cause breakages for other people who assigned quite a few consumables to users and do not wish that email to be 10 miles long.

**Comment by addex12** [comment]
Now the system is sending a email to users by including accessories and consumables in addition to other assets. 
You are Amazing!
 One thing left, when sending an email of all assigned, it is listing same items all the way down. Is there any possiblity to make it count the consumables, Accessories with the same name all together and put them in one line? I mean in place of listing down 10 Mouse all the way down putting it like 10 Mouse and from consumables also like 5 consumables name(eg Pen).

**Comment by addex12** [comment]
> Accessories do currently show up in the "Email all assigned" emails. We did discover that consumables were not being emailed, but if we fix this, I also suspect this will cause breakages for other people who assigned quite a few consumables to users and do not wish that email to be 10 miles long.

Is there any means to fix the 10 miles long list of consumables in one line in email? I mean as long as the consumable name is same counting all the consumables with same name and putting them in the form of: Consumables Name: XXXXXXX Qty: XXXX format.
