### ISSUE TITLE
API error references company instead of location

### ISSUE THREAD

**Issue by pieterhouwen** [grokability/snipe-it#14815]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When deleting a location with one or more asset models assigned to it the API returns the following error:

```This company is currently associated with at least one model and cannot be deleted. Please update your models to no longer reference this company and try again. ```

### Reproduction steps

1. Go to https://snipe-it.readme.io/reference/locationsid-2
2. Try to remove the Location with ID 1
3. The error message that is returned mentions the company instead of the location

### Expected behavior

The API error should read:

```This location is currently associated with at least one model and cannot be deleted. Please update your models to no longer reference this location and try again. ```

### Snipe-IT Version

6.3.4

### Operating System

Linux

### Web Server

All

### PHP Version

all

**Comment by pieterhouwen** [comment]
@snipe Why does this API error mention models instead of assets? AFAIK asset models don't have a connection to locations while assets themselves do.

**Comment by snipe** [comment]
It was just a typo.
