### ISSUE TITLE
[Feature Request]: Add ability to create a PDF containing all information for a specific asset

### ISSUE THREAD

**Issue by Glukose1** [grokability/snipe-it#14821]
### Is your feature request related to a problem? Please describe.

I want to print a page that contains the information for a single asset. I found the option to print reports but couldn't find a way to specify an asset. For example, I want all the information (history, serial, purchase date, asset tag, model, etc.) of the asset with the tag Company-Asset-Laptop-14456.

### Describe the solution you'd like

I would like a "Print Asset Information" button on the hardware/asset_id page below the "Audit" button. When pressing this button, a form should open where you can choose the information you want to see on the report. 

On the asset page are the tabs:  Info, Licenses, Components, Assets, History, Maintenances, Files, and Additional Files.

The form should list these tabs (maybe excluding files and additional files as there is no data to print directly; if it is possible to add the files from these tabs to the end of the generated PDF, I would include them) and have a checkbox behind each of them, if the box is checked the data of that tab should be added to the PDF.

Here is a rough example of how the report could look:
![Report-mock](https://github.com/snipe/snipe-it/assets/167117705/3cdf9953-aeec-4c35-b8ba-85e9a72a2ee5)

### Describe alternatives you've considered

I think this could become quite a complex feature to implement.

An easy solution for now would be adding a field where you can specify an asset by its tag on the report page to generate a report for that exact asset. But as these reports are only CSV files, they wouldn't really be suitable to attach to the exit protocol of a device when it is trashed, e.g. 

So I think the solution described above would be better in the long term.

**Comment by snipe** [comment]
I think the better solution here would be to make the view asset page more printer friendly, no?

**Comment by Glukose1** [comment]
Yes, that would work too. If this makes it easier to implement I am completly for it, my knowledge is however to limitited to judge this.

Only disadvantage that comes to my mind would be that this way there wouldn't really be a way to do a bulk actionfor printing these information summarys. I assume with an extra print to PDF feature that would be easier to implement.

**Comment by W01FPR1M3** [comment]
I am also looking forward to this being implemented, this is what i'm suggesting (there can be a better way tho) :
 adding a "print info" button next to "generate label"
   [Path : view asset > info ]
 
 on this page
  ![image](https://github.com/snipe/snipe-it/assets/32429386/c36afc8f-3404-4699-8c9c-a0be835f1bd2)
 
 something like this 
![print](https://github.com/snipe/snipe-it/assets/32429386/8d3a5fa7-189d-4f8d-bb56-3d2f17a965ea)

**Comment by najirod** [comment]
This feature would be incredibly valuable for us as well. For example, when replacing a laptop or another piece of equipment, managers often request information about the specific item an employee currently has. We typically respond by sending a screenshot. Similarly, during the offboarding process, HR frequently asks for details on specific equipment. It would be extremely convenient if we had the option to print or download a PDF with the completed fields for a particular asset.

**Comment by snipe** [comment]
@najirod Can you not just Print > Save as PDF?

**Comment by najirod** [comment]
@snipe 
It is indeed possible, but not as elegant as a simple report that would look like a standard asset display (a table) in a printable format (screenshot). When attempting to print, all buttons and search bars remain visible (see attached PDF). Perhaps using a JavaScript option ("@media print") on the existing page would be possible, if possible. (I'm not a full-time developer, just some Python.)
![Screenshot 2024-08-13 at 3 35 56 PM](https://github.com/user-attachments/assets/33bdd996-123e-4ce0-9980-7f05b960c3eb)
[View Asset 1119166243 __ Snipe-IT Asset Management Demo.pdf](https://github.com/user-attachments/files/16600387/View.Asset.1119166243.__.Snipe-IT.Asset.Management.Demo.pdf)

**Comment by snipe** [comment]
Would something like this work? 

[View Asset 37028370 :: Snipe-IT Demo.pdf](https://github.com/user-attachments/files/16601087/View.Asset.37028370.Snipe-IT.Demo.pdf)

**Comment by najirod** [comment]
@snipe For me and my usecases this is very nice! Simple, clean, familiar, links work... Perfect ❤️
