### ISSUE TITLE
LDAP Sync synchronises wrong users

### ISSUE THREAD

**Issue by kuratlielia** [grokability/snipe-it#14823]
### Debug mode

- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We created about 40 locations inside SnipeIT, each with its own Active Directory OU path assigned. Now we have a script that runs the following command for all IDs between 1 and 40:

`php artisan snipeit:ldap-sync --location_id=X --summary`

The command, it doesn't matter which ID, returns around 2100 users each time. The same users every time and the strange part is the users don't even belong to the correct location.

The users are from 8 different locations, but I don't see a pattern and don't get from which OU path the users are picked.

Do you know this problem and maybe already found a solution?

### Reproduction steps

1. Create a location and enter the ou where the users are in
2. Run the sync command for the location with id=1 -> php artisan snipeit:ldap-sync --location_id=1 --summary

### Expected behavior

All the users from the given location should be imported into SnipeIT and be assigned the correct location.

### Snipe-IT Version

v7.0.0 /  v6.3.2

### Operating System

Windows Server 2022

### Web Server

IIS

### PHP Version

8.1.2

**Comment by snipe** [comment]
My guess would be the filters are wrong, either on the base LDAP setting or on the locations themselves.

**Comment by kuratlielia** [comment]
> My guess would be the filters are wrong, either on the base LDAP setting or on the locations themselves.

We set the LDAP Filter, so only users will be imported:
![grafik](https://github.com/snipe/snipe-it/assets/82137127/2ad2cd36-db80-48bf-81cd-c660673e2edb)

And the search OU is this one:

OU=Departments,OU=User,OU=XXX,DC=XXX,DC=XXX

Under this path, there are OU's with all the users from the Departments.

In my understanding it should work, any ideas?

**Comment by rshe-james** [comment]
try &(objectClass=user)(objectCategory=person)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
