### ISSUE TITLE
Can't download backup file after upgrade from 6.3.1 to 6.4.1

### ISSUE THREAD

**Issue by Seneken** [grokability/snipe-it#14850]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Dear all,
I have facing this problem, After upgraded snipe-it from 6.3.1 to 6.4.2, I can't download backup file anymore. I can create but can't download.

The upgrading with no errors, granted all folder with rights as necessary. All remaining features work normally after the upgrade.
Please give me some advise, thank much!

![download](https://github.com/snipe/snipe-it/assets/10119320/051ca916-0d40-4e69-b2d5-8b388557b2eb)

### Reproduction steps

1.
2.
3.
...

### Expected behavior

nope

### Screenshots

![download2](https://github.com/snipe/snipe-it/assets/10119320/051ca916-0d40-4e69-b2d5-8b388557b2eb)

### Snipe-IT Version

v6.4.2 build 13487 (gb489c71fa2)

### Operating System

centos

### Web Server

apache

### PHP Version

8.1.29

**Comment by snipe** [comment]
That error is a protocol error. Are you certain the site you're accessing is running over https? (Check your APP_URL to make sure it is the same as the URL you enter to get to the site.)

**Comment by addex12** [comment]
Mine shows HTTP ERROR 500. and my APP_URL is https://....
<img width="618" alt="Capture" src="https://github.com/snipe/snipe-it/assets/18550946/5946ee92-d342-4e76-9e80-2a6cccdb76b1">

**Comment by addex12** [comment]
Oh just fixed it by deleting some of the old backup files. I think theres a limit assigned to hold the old backup data.

**Comment by Seneken** [comment]
Dear @snipe,
I just want to update that after upgraded to 7.0.4. Now I can download backup files normally without error.

Thank you so much.
