### ISSUE TITLE
[Feature Request]: I want user login and user JWT over snipe-it API

### ISSUE THREAD

**Issue by s681562** [grokability/snipe-it#14857]
### Is your feature request related to a problem? Please describe.

For now I am using my own JWT token generated on my profile.
I gave this JWT to my web app and all user can use it.
I wish each user can have there own JWT without my work as profile manager.

### Describe the solution you'd like

User are logging in over API.
Here is /api/v1/users/login API access.
User can enter username / email and password.
User get own JWT after login.

### Describe alternatives you've considered

I downloading all users by  /api/v1/users/
I got a json list of all users.
I fetch user name and password on login page of my web app.
If user is register on /api/v1/users/, I keep password in clear text and write it into note field.
The note field is part of user json object of snipe-it.
There is no password match, because there is no /api/v1/users/login call.
I look up the user list /api/v1/users/.
I check user password with note field.
If notice field contain correct password, user must be correct.
If user is inside the list, the user must be logged in.
I make a notice in my web app.
I gave user my own JWT.

**Comment by snipe** [comment]
I don't think I understand. Each user can already have their own JWT token, and that JWT acts as the "login" for an API user. There isn't a concept of "logging in" via API, because the JWT bearer token already *is* that. And please, never ever store passwords in plaintext in the notes field. 

I think I'd need to understand more about what you're actually trying to accomplish here in order to advise you further.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by s681562** [comment]
"Each user can already have their own JWT token, and that JWT acts as the "login" for an API user."
Yes, I full agree.

Each user can access directly snipe-it homepage or api with their JWT token.
But this I want to avoid. User should not access snipe-it-backend and changing their data.

We offer our APP for user access.
It must be painful, if I do not hardcode the JWT for API access in our APP.
On an APP the user will be painfull, if the user have to memorize their JWT instead of simple login.

Or I create an QR-Code print function, user can scan it (JWT token encoded).
But no user running around the corner and hold up their QR-Code-Sticker.
If our App running on smartphone, maybe user can use smartphone cam for QR-Code scanning.
But if user are sitting in the office, most office pc have not an web cam and qr-code-scan sofware, which is combined with our Web-App.
Each user can have their JWT, sure. But our users should only login in our APP.
We are using snipe-it also as user-managment.
I hope, there is an login (email/name - password) to get an JWT.
At first glance I saw the JWT in my account as an API access JWT token.
Now I am sharing my JWT as public API-access token in our APP for all customers.
The JWT token is hardcoded in the APP for API access.
I hope, the JWT token never expires or our APP will be broken soon.
I hope there would be something like login (email/name - password), leads into result with JWT, store JWT on APP until logout.
The JWT is identify the current user and gives API access.
Please set this on ToDo.
