### ISSUE TITLE
[Feature Request]: I want update avatar of user (profile image) over snipe-it API 

### ISSUE THREAD

**Issue by s681562** [grokability/snipe-it#14856]
### Is your feature request related to a problem? Please describe.

https://develop.snipeitapp.com/api/v1/users/{id} can update a user.

But there is no way to change the user avatar by calling snipe-it API.

### Describe the solution you'd like

I want to upload a different image as "avatar": "https:\/\/asset.precisyn.net\/img\/default-sm.png".

How can I do that?

I want call /api/v1/users/{id} and say avatar : base64 image data...  or http url adress and magic is happen and avatar is changed.

### Describe alternatives you've considered

I wait for user request by messenger or email.
User send me an new profile image by messenger or email.
I copy the user profile image to my computer.
For now at the moment I am logging in on homepage snipe-it and go to user profile and update profile image.

**Comment by s681562** [comment]
This is not in documentation.

Can anyone proof it?

```
> url = f"http://ADD_SERVER_HERE/api/v1/users/5001"
> 
> // Header to access API.
> headers = {
>         "accept": "application/json",
>         "Authorization": "Bearer ADD_KEY_HERE",
>         "content-type": "application/json"
>     }
> 
> // What we want to add/change about the user.
> // first_name, last_name and username appear to be mandatory.
> payload = {
>     "first_name": "Hendrik",
>     "last_name": "Clijsters - TestAPI",
>     "username": "hendrik.clijsters testAPI",
>     "image": f"data:image/png;name=python.png;base64,{decoded_string}"
> }
```

**Comment by snipe** [comment]
Well, it's not really meant to be used that way, that's why it's not documented. You'd need to add the URL base to  `ADDITIONAL_CSP_URLS` in your env for them to load, most likely.
