### ISSUE TITLE
Add an option that users must state a reason for requesting a requestable.

### ISSUE THREAD

**Issue by jorgemfm** [grokability/snipe-it#14862]
### Is your feature request related to a problem? Please describe.

Users can request assets at will without the need to state a reason, this means that asset managers have to follow-up with the user on that. It would be a nice to have and option that would allow the users to state the reason for requesting the asset.

### Describe the solution you'd like

When clicking the option to request a requestable, a popup would appear so that the users could state a reason why they are requesting the asset.

**Comment by snipe** [comment]
Duplicate of #14844

**Comment by farooq-sudo** [comment]
Hi, I'm using v8.4.0 and I did not find this feature that allow users to state reason for the item requested. Can anyone help with this? Thanks
