### ISSUE TITLE
 Licenses Created Not Added, Not Viewed

### ISSUE THREAD

**Issue by diskmail34** [grokability/snipe-it#14873]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

 Licenses Created Not Added, Not Viewed Version:Version v6.4.2 

Hi,

The situation requires help, your ideas.
Only the records I made on the "Licenses" page are not processed in the system.

The remaining tabs show the transactions I have made (inventory, company personnel). Even if I fill in all the information completely while creating a registration on the "Licenses" page, the registration is not made. "phpmyadmin" "licenses" section is also empty

Now I noticed something new.
When I click on "licenses" in the installed system, the index page in the image opens.

When I log into the system I share from a different device, the licenses page opens, but I cannot register a license.

Please help me.

---

Expected behavior

It just doesn't save licenses.

When I enter from the distribution IP, the licenses page opens, but it does not save the information I entered.

When I click on the installed Windows Host machine, the 1. photo screenshot opens.

-

Version:Version v6.4.2 - build 13487
![S1](https://github.com/snipe/snipe-it/assets/104549674/f7aeefea-98dd-4618-bdb8-5b62d92c6a1c)

![S2](https://github.com/snipe/snipe-it/assets/104549674/d88527d6-dbba-4004-bb30-2d5103b7b1c4)

![S3](https://github.com/snipe/snipe-it/assets/104549674/d9500814-16df-42ed-a17d-edf74d006090)

![S4](https://github.com/snipe/snipe-it/assets/104549674/9eaf9118-e87f-4b38-a05d-14f6085f4e9e)

### Reproduction steps
![S1](https://github.com/snipe/snipe-it/assets/104549674/f7aeefea-98dd-4618-bdb8-5b62d92c6a1c)

![S2](https://github.com/snipe/snipe-it/assets/104549674/d88527d6-dbba-4004-bb30-2d5103b7b1c4)

![S3](https://github.com/snipe/snipe-it/assets/104549674/d9500814-16df-42ed-a17d-edf74d006090)

![S4](https://github.com/snipe/snipe-it/assets/104549674/9eaf9118-e87f-4b38-a05d-14f6085f4e9e)

### Expected behavior

It just doesn't save licenses.

When I enter from the distribution IP, the licenses page opens, but it does not save the information I entered.

When I click on the installed Windows Host machine, the S1 screenshot opens.

### Snipe-IT Version

Version v6.4.2

### Operating System

Windows 10

### Web Server

XAMPP Apache

### PHP Version

Don't have

### Operating System

Windows

### Browser

Firedox

### Version

Version v6.4.2

### Error messages

```shell
Don't have
```

### Additional context

Don't have

**Comment by snipe** [comment]
Did you remove the built-in aliases?
https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases">XAMPP</a></strong></div><div>❗️Note:In general, we do not recommend using XAMPP for Snipe-IT, as there is a built-in alias for &lt;button aria-label="Copy Code" class="rdmd-code-copy fa"&gt;&lt;/button&gt;/licenses that you'll have to override, which can be a bit of a pain. We recommend WAMP or IIS instead if you're running on ...</div></blockquote>

**Comment by diskmail34** [comment]
> Yerleşik takma adları kaldırdınız mı? [https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases ](https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases)
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/f5ec2eb7e2274ad22d196821472e0438dcbd923f06ab2d8cbeb0ae2113c74df8/68747470733a2f2f736e6970652d69742e726561646d652e696f2f66617669636f6e2e69636f">Snipe-IT Belgeleri **[XAMPP ](https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases)**❗️Not:Genel olarak, <button aria-label="Kodu Kopyala" class="rdmd-code-copy fa"></button için yerleşik bir takma ad olduğundan, Snipe-IT için XAMPP kullanılmasını önermiyoruz. >/lisansları geçersiz kılmanız gerekecek, bu biraz acı verici olabilir.  Eğer çalışıyorsanız bunun yerine WAMP veya IIS'yi öneriyoruz...


**You are perfect, you are the savior angel**

**Comment by snipe** [comment]
So glad to hear you're sorted :)
