### ISSUE TITLE
Backup failed because: The dump process failed - v7 upgrade

### ISSUE THREAD

**Issue by noobeh** [grokability/snipe-it#14881]
### Debug mode

- [X] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, I was trying to upgrade to v7 using the git method, but I'm getting this error "Backup failed because: The dump process failed with exitcode 127 : Command not found : sh: /usr/bin/mysqldump: No such file or directory" since I've my database hosted elsewhere as configured in the .env file, and I don't have mysqldump installed on the snipe-it machine.

After failing to upgrade, now the web is returning 500 server error.

### Reproduction steps

git pull
php upgrade.php

error

### Expected behavior

Didn't have any problems upgrading until now.

### Snipe-IT Version

6.4.2

### Operating System

Rocky Linux 8.9

### Web Server

Apache

### PHP Version

8.1.27

**Comment by snipe** [comment]
If you're running a git install, you don't actually need to use upgrade.php, it's just a helpful tool around some manual commands. 

```
git pull master
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear
php artisan config:cache
```

If you're running composer globally, you'd use 

```
composer install --no-dev --prefer-source
composer dump-autoload
``` 
instead of referencing the phar file.

**Comment by noobeh** [comment]
worked manually, tyvm
