### ISSUE TITLE
Assets tab for model doesn't show archived asset, but count is pulling back archived asset

### ISSUE THREAD

**Issue by tglassburn** [grokability/snipe-it#14882]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When clicking onto the models page for any specific model, and viewing assets listed under that model, the assets tab shows a count. In my instance, it shows 1, which is correct as I have an archived asset. However, no assets show on the page.

My suspicion is the count of assets for the models pulls all assets, archived or not.
My suspicion is that the assets listing for models only shows active assets, and not archived assets, which explains the mismatch.

See screenshots. This happened on multiple assets/models combos, not just one.

I did upgrade to 7.0.2 today but have no idea if this is a new bug. I just happened to notice this today but could be completely unrelated to the new version, I would have never seen this before today as I had not archived any assets until now.

### Reproduction steps

1. Make a specific asset archived
2. Click the models page for said asset
3. Notice on screenshot 1, count is 1, but nothing is showing. On screenshot 2, count is 2, but 1 asset is showing. In both instances, each model has 1 asset archived.
...

### Expected behavior

The archived assets should be shown

### Screenshots

![asset](https://github.com/snipe/snipe-it/assets/142260542/fd884905-136a-4265-b7ec-d865eeb30424)
![asset2](https://github.com/snipe/snipe-it/assets/142260542/99b1fc90-2397-438f-82df-6571dfe5bf26)

### Snipe-IT Version

7.0.2

### Operating System

Linux

### Web Server

Apache

### PHP Version

8.1

**Comment by snipe** [comment]
Thanks for reporting this. Can you let me know in Admin > General Settings if you have the "Show archived assets in the "all assets" listing" checkbox checked or unchecked? That may help narrow this down.

<img width="594" alt="Screenshot 2024-06-18 at 10 15 13 AM" src="https://github.com/snipe/snipe-it/assets/197404/10630ff4-6ce1-44b8-806c-072a6cf0e847">

**Comment by snipe** [comment]
I think I found the issue - it's not related to v7, it's been there the whole time 😬 😂 I'll have a fix up shortly.

**Comment by snipe** [comment]
This should be fixed when we next merge to master. https://github.com/snipe/snipe-it/pull/14894

**Comment by tglassburn** [comment]
Awesome, looks good now. You guys are so fast at fixing the small stuff. Thanks!!
