### ISSUE TITLE
APP_LOCALE en should be en-US according to Laravel logs

### ISSUE THREAD

**Issue by Tyree** [grokability/snipe-it#14883]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

With the APP_LOCALE being set to en (as indicated in the docs here : https://snipe-it.readme.io/docs/configuration#section-setting-a-language ), the laravel logs will repeatedly spit out:
production.WARNING: APP_LOCALE in .env is set to en and should be updated to be en-US
As the warning indicates, I assume this only happens when in production mode.
Thanks!

### Reproduction steps

1. APP_LOCALE set to en
2. Start container
3. browse laravel logs under storage/logs/laravel.log

### Expected behavior

en being set for APP_LOCALE according to docs, no errors in logs (storage/logs/laravel.log)

### Snipe-IT Version

7.02

### Operating System

unRAID

### Web Server

Container

### PHP Version

8.1

**Comment by snipe** [comment]
We'll update the docs, thanks for the reminder.

**Comment by Tyree** [comment]
> We'll update the docs, thanks for the reminder.

Great! Thanks! Not a huge deal and easy to fix on my end.
LinuxServer has a template for unRAID that I use for SnipeIt and their instructions and default setting are wrong because they're based on the SnipeIt docs. So they don't seem keen to fix it until the docs are changed. HA! :-D 
Thanks again!

**Comment by Tyree** [comment]
@snipe 
One more spot you may want to update. The instructions right before the list of locale codes still mentions "en":
If you wish to use one of the other available languages, simply replace the default value of `locale` from `en` to one of the values listed below.

**Comment by snipe** [comment]
Updated, thank you!
