### ISSUE TITLE
Upgrade to 7.01 from 6.4.2

### ISSUE THREAD

**Issue by cyberfarer** [grokability/snipe-it#14880]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

CSS is being served up in mixed mode insecure and is blocked.

### Reproduction steps

1. php upgrade.php
2. Reload page 
3.
...

### Expected behavior

I expect to see a formatted page.

### Screenshots

![Screenshot from 2024-01-08 13-26-57](https://github.com/snipe/snipe-it/assets/7407805/be4a69ab-852b-49ea-a5ec-ac63a24cbbde)

### Snipe-IT Version

7.0.1

### Operating System

Ubuntu 22.04.3

### Web Server

Apache 

### PHP Version

8.1

### Operating System

Linux

### Browser

Firefox

### Version

126.0.1

### Error messages

```shell
`Mixed Content: The page at 'https://snipeit.redacted.ca/login' was loaded over HTTPS, but requested an insecure stylesheet 'http://snipeit.redacted.ca/css/dist/all.css?id=a9f493a1d66b45420401f3ae8ee4aab1'. This request has been blocked; the content must be served over HTTPS.`
```

### Additional context

I use an Nginx reverse proxy. I have been running Snipe-IT for years and this is the first time I have had this issue after the upgrade. 

Thanks.

**Comment by cyberfarer** [comment]
Sorry about the screenshot. Correct one. 
![Screenshot from 2024-06-17 11-30-45](https://github.com/snipe/snipe-it/assets/7407805/ca7465f7-ebd3-47e9-a464-983ca3312a77)

**Comment by kbrown900** [comment]
I also just experienced this issue when upgrading.

**Comment by Tyree** [comment]
Getting the same problem with CSS not loading after upgrade to 7.01.
Also getting errors with JS not loading and for forms targeting insecure endpoints (Mixed Content).

**Comment by snipe** [comment]
Can you folks try setting `APP_FORCE_TLS` to true in your env? 

https://snipe-it.readme.io/docs/configuration#required-basic-app-settings

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#required-basic-app-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required. Don't be intimidated by the length of this page. The configurati...</div></blockquote>

**Comment by cyberfarer** [comment]
That did it! Thank you.

**Comment by snipe** [comment]
That's great to hear - thanks for the quick feedback! This will definitely come up again, so it's good to know the solution works.

**Comment by Tyree** [comment]
Fixed for me as well! Thanks!

**Comment by snipe** [comment]
Yay! I've updated the release notes for the v7 releases s hopefully other folks don't run into this.

**Comment by kbrown900** [comment]
Can confirm worked for me as well!

**Comment by snipe** [comment]
Thank you all for such fast feedback. Big release days are stressful (of course) so being able to respond with solid answers _really_ quickly definitely takes a huge load off. I think something in the underlying framework changed, where you didn't need that setting before, but now for some reason you do. We don't have a very easy way to test all of the unusual proxies folks use us with, so it's important to us that we can surface this info quickly, update docs, etc. 

I appreciate you all. Thank you. <3

**Comment by marcel-sch** [comment]
> Thank you all for such fast feedback. Big release days are stressful (of course) so being able to respond with solid answers _really_ quickly definitely takes a huge load off. I think something in the underlying framework changed, where you didn't need that setting before, but now for some reason you do. We don't have a very easy way to test all of the unusual proxies folks use us with, so it's important to us that we can surface this info quickly, update docs, etc.
> 
> I appreciate you all. Thank you. <3

Thanks for your fast help, we ran into the same issue

**Comment by snipe** [comment]
Sounds like this is the fix, so I'll close this one for now. Thanks everyone involved. <3
