### ISSUE TITLE
V7 Docker Image - Missing CSS and JS Files

### ISSUE THREAD

**Issue by DarthDestroyer** [grokability/snipe-it#14892]
### Debug mode

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

JS and CSS Files get blocked

### Reproduction steps

1. Open FQDN

### Expected behavior

Default Dashboard / Login - Whatever

### Screenshots

![grafik](https://github.com/snipe/snipe-it/assets/16085323/aebea3aa-928f-4301-8d46-3fb957bf712a)
![grafik](https://github.com/snipe/snipe-it/assets/16085323/e4311fd0-5afb-4bca-a466-683d27141e55)

### Snipe-IT Version

v7.0.2

### Operating System

latest / latest-alpine

### Web Server

Docker Container

### PHP Version

Docker Container

### Operating System

Windows

### Browser

Firefox / Chrome

### Version

latest

### Error messages

```shell
storage logs are empty - Browser gives all informations even without Debug Mode ;)
```

### Additional context

Its a Docker Container - And yes, its an Upgrade but only persistant Data as declared in the How-To is used

**Comment by DarthDestroyer** [comment]
Okay... Getting closer:

![grafik](https://github.com/snipe/snipe-it/assets/16085323/3aaa2374-bd31-4277-94b0-dcf17bff0523)

APP_URL is set to "https://FQDN"

**Comment by snipe** [comment]
They're not missing though, as they're in the repo. Did you try setting `APP_FORCE_TLS=true` in your `.env`, per the release notes?

**Comment by DarthDestroyer** [comment]
=D The Fix is not always that visible! Thank you ;)

Havent checked that - Sorry!
Watchtower updated and i missed the Release-Notes completly - My Fault!

Keep up the awesome work!
