### ISSUE TITLE
Reason for adding evil.php

### ISSUE THREAD

**Issue by LickABrick** [grokability/snipe-it#14890]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

What is the reason for adding the evil.php file. It was added in: https://github.com/snipe/snipe-it/commit/8f2843bfcf00d616a55c84fc757df5a63d06c742#diff-662ec8582cb15e18bf3e98051c6d8f4ad9166b3dd664f674306b9f8cbec6e7c0

### Reproduction steps

1.
2.
3.
...

### Expected behavior

.

### Snipe-IT Version

7.0.2

### Operating System

Debian 12

### Web Server

Nginx

### PHP Version

latest

**Comment by snipe** [comment]
Hi there - if I recall, that was a test file to prove that using funky encoding can't get around our image "cleaning" process. (In other words, making sure someone being "clever" can't trick our system into thinking a php file is really an image file.) It can probably be pulled though, as it was there largely for testing purposes.
