### ISSUE TITLE
Cant Export Licenses in 7.0.3

### ISSUE THREAD

**Issue by JFurtado001** [grokability/snipe-it#14897]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have recently upgraded to the newest version of SnipeIT (7.0.3 Build 13980). When attempting to export licenses, I receive a 500 server error. When I turn n debugging (as well as check Laravel logs) it says "class debugbar not found". Please let me know what I can do to fix this

### Reproduction steps

1.Upgrade to the latest verstion of SnipeIT
2. Attempt to export Licenses
3.
...

### Expected behavior

Taken to a page for exporting licenses.

### Screenshots

(https://github.com/snipe/snipe-it/assets/46457823/414825c1-534e-4500-a70c-20c49fa3af26)
(https://github.com/snipe/snipe-it/assets/46457823/ae227c62-ae0b-4783-bcd8-c0be11ad8f04)

### Snipe-IT Version

V7.0.3 build 13980

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.2.12

### Operating System

Windows

### Browser

Edge

### Version

126.0.2592.56

### Error messages

```shell
Class "Debugbar" not found
```

### Additional context

This is after upgrading to the latest version of snipe.

**Comment by marcusmoore** [comment]
Hi there, this is the same issue as #14898 and should be fixed with commit https://github.com/snipe/snipe-it/commit/7b84b92e72e5e42ed75b55849121d2d2287b093f

It'll be available in the next tagged release coming shortly.

**Comment by JFurtado001** [comment]
@marcusmoore Okay no problem. Thank you this is greatly appreciated.

**Comment by snipe** [comment]
@JFurtado001 Can you pull latest and give it shot now?

**Comment by JFurtado001** [comment]
@snipe I just did the newest pull and everything worked successfully (including the the export function). Thanks for the help. Greatly appreciated.

**Comment by snipe** [comment]
@JFurtado001 So glad to hear it!
