### ISSUE TITLE
Email not working after upgrading to 7.0.4

### ISSUE THREAD

**Issue by bstamand** [grokability/snipe-it#14909]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Email notifications not working after upgrading to 7.0.4.

### Reproduction steps

1.Attempt to send test email
2.
3.
...

### Expected behavior

Email sent successfully.

### Snipe-IT Version

7.0.4

### Operating System

Rocky Linux 9

### Web Server

Apache

### PHP Version

8.3.8

**Comment by omarsuazo** [comment]
Hi, I got the same problem and I got a solution I commented on https://github.com/snipe/snipe-it/issues/14866#issuecomment-2179465374

If your mail uses a GSuite domain (the google one) you could try to copy the parameters on the .env file

Cheers

**Comment by bstamand** [comment]
> Hi, I got the same problem and I got a solution I commented on [#14866 (comment)](https://github.com/snipe/snipe-it/issues/14866#issuecomment-2179465374)
> 
> If your mail uses a GSuite domain (the google one) you could try to copy the parameters on the .env file
> 
> Cheers

Thank you but unfortunately we are using a custom SMTP relay server.  I will continue to troubleshoot the issue.

**Comment by bstamand** [comment]
Update: upon looking at the SMTP relay logs, it looks like snipe it trying to connect to this server via TLS however it only accepts un-encrypted connections (it then sends back out encrypted, for old copiers in our environment).  Is snipe no longer able to send un-encrypted emails? I have the MAIL_ENCRYPTION flag set to null.

**Comment by bstamand** [comment]
Update: downgrading to php 8.2 did not solve the issue.

**Comment by snipe** [comment]
There were some changes made to the mailing system in Laravel 10. It's now backed by Symfony mailer (instead of Swifmailer) which wouldn't normally affect folks in a more standard environment, but we might need to make some extra changes to make it work with your setup. 

More info is available here: https://symfony.com/doc/6.2/mailer.html

See if there's anything there that looks like it might be something that could work. This will be a bit hard for us to test, but we can try to help.

<blockquote><img src="https://symfony.com/images/opengraph/symfony.png" width="48" align="right"><div><strong><a href="https://symfony.com/doc/6.2/mailer.html">Sending Emails with Mailer (Symfony 6.2 Docs)</a></strong></div></blockquote>

**Comment by bstamand** [comment]
Here are my email settings:

MAIL_DRIVER=smtp
MAIL_HOST=192.168.0.50
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=mail@mail.ca
MAIL_FROM_NAME='Mail'
MAIL_REPLYTO_ADDR=mail@mail.ca
MAIL_REPLYTO_NAME='Mail'
MAIL_AUTO_EMBED=true
MAIL_AUTO_EMBED_METHOD='attachment'

**Comment by bstamand** [comment]
Thank you.  I’ll give this a read through and see if I can adapt it to my environment.

[A logo of a city  Description automatically generated]
Brian St.Amand
Information Technology Coordinator

**Comment by bstamand** [comment]
I've decieded to switch this over to Amazon SES instead, however I'm still getting an error when trying to do a test send.  Not sure where to go from here.

**Comment by jerm** [comment]
Symfony tries to be "smart" and "secure" at the same time, and takes a lot of control away... for instance MAIL_ENCRYTION=null no longer does anything.. it just decides to use encryption if the server advertises it, which can be a problem if the certificate say one thing and you access it as a different name.... like with an IP address.  I'm guessing that's what happening here.

For your old configuration, you may need to add 
MAIL_TLS_VERIFY_PEER=false

SES should Just Work, though... What does your mail config look like now?

**Comment by bstamand** [comment]
> Symfony tries to be "smart" and "secure" at the same time, and takes a lot of control away... for instance MAIL_ENCRYTION=null no longer does anything.. it just decides to use encryption if the server advertises it, which can be a problem if the certificate say one thing and you access it as a different name.... like with an IP address. I'm guessing that's what happening here.
> 
> For your old configuration, you may need to add MAIL_TLS_VERIFY_PEER=false
> 
> SES should Just Work, though... What does your mail config look like now?

Hey, thank you.  Here it is (sensitive info omitted of course)
MAIL_MAILER=smtp
MAIL_HOST=email-smtp.ca-central-1.amazonaws.com
MAIL_PORT=465
MAIL_USERNAME=SES Username
MAIL_PASSWORD=SES Password
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=email@email.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=email@email.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED=true
MAIL_AUTO_EMBED_METHOD='attachment'

**Comment by bstamand** [comment]
I've since changed the port to 587, but still no luck.  I'm not sure what's going on here.  Frustrated and out of ideas, I'm giving up for today.

**Comment by jerm** [comment]
do a `composer install` (though --no-dev) to get tinker installed and then do

`php artisan tinker`

and try to send a test email to yourself

`Mail::raw('Hello World!', function($msg) {$msg->to('EXAMPLE@EXAMPLE>COM')->subject('Test Email from snipe-it'); });`

this is a working config on 7.0.4 that i just sent a test email with the above command

```
MAIL_MAILER="smtp"
MAIL_HOST="email-smtp.us-east-1.amazonaws.com"
MAIL_PORT=465
MAIL_USERNAME="AKIALOLNOPENOPENOPELOL"
MAIL_PASSWORD="AOMGWTFBBQTNTQEDOMGWTFBBQ"
MAIL_FROM_ADDR="testthing@snipetesting.com"
MAIL_FROM_NAME="morplypoo"
MAIL_REPLYTO_ADDR="jerm1@snipetesting.com"
MAIL_REPLYTO_NAME="morplypoo"
```

it looks suspiciously similar to yours, so hopefully the output of that command will lend some insight... i'm guessing AWS permissions, but that's just a guess

**Comment by bstamand** [comment]
Just to add I've also changed the MAIL_MAILER to ses instead of smtp

**Comment by bstamand** [comment]
> do a `composer install` (though --no-dev) to get tinker installed and then do
> 
> `php artisan tinker`
> 
> and try to send a test email to yourself
> 
> `Mail::raw('Hello World!', function($msg) {$msg->to('EXAMPLE@EXAMPLE>COM')->subject('Test Email from snipe-it'); });`
> 
> this is a working config on 7.0.4 that i just sent a test email with the above command
> 
> ```
> MAIL_MAILER="smtp"
> MAIL_HOST="email-smtp.us-east-1.amazonaws.com"
> MAIL_PORT=465
> MAIL_USERNAME="AKIALOLNOPENOPENOPELOL"
> MAIL_PASSWORD="AOMGWTFBBQTNTQEDOMGWTFBBQ"
> MAIL_FROM_ADDR="testthing@snipetesting.com"
> MAIL_FROM_NAME="morplypoo"
> MAIL_REPLYTO_ADDR="jerm1@snipetesting.com"
> MAIL_REPLYTO_NAME="morplypoo"
> ```
> 
> it looks suspiciously similar to yours, so hopefully the output of that command will lend some insight... i'm guessing AWS permissions, but that's just a guess

Trying that now!

**Comment by jerm** [comment]
(use a read email address in the command of course )

**Comment by jerm** [comment]
if the command succeeds, but you don't receive the email, then ses likely accepted it, and it's something on SES's end..... check your spam folder -- i find deliverability though SES can be.... spotty... with test email content

**Comment by bstamand** [comment]
> if the command succeeds, but you don't receive the email, then ses likely accepted it, and it's something on SES's end..... check your spam folder -- i find deliverability though SES can be.... spotty... with test email content

You sir are a genius.  That fixed the issue!  Thank you very much!

**Comment by jerm** [comment]
great!  what did it end up being?  *curious*

**Comment by bstamand** [comment]
> great! what did it end up being? _curious_

doing a:
composer install --no-dev
php artisan tinker
I changed MAIL_MAILER back to smtp

I can now do a successful test email from the snipe settings.

**Comment by jerm** [comment]
Great!! Glad it's working for you 😃

**Comment by bstamand** [comment]
> Great!! Glad it's working for you 😃

Thanks again!

My backup emails are filled with lines like this.  Not a huge deal, just wondering if there is an easy fix for that.

backup::notifications.backup_successful_body

**Comment by jerm** [comment]
@snipe thoughts on this last question?

**Comment by snipe** [comment]
@jerm @bstamand - that was fixed yesterday in https://github.com/snipe/snipe-it/pull/14920. Missing translation files and a dumb conflict between how the backup package handles translation paths and how we do.

**Comment by snipe** [comment]
Nice work here everybody! TYSM for the help with this one @jerm <3
