### ISSUE TITLE
Upgrade Causes error ProviderRepository.php line 208

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#14904]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Once I do a php upgrade, error is below : 
Now site is blank. 

### Reproduction steps

Upgrade.php :

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
Generating optimized autoload files

In ProviderRepository.php line 208:
                                                             
  Class "Facade\Ignition\IgnitionServiceProvider" not found  
                                                             

--------------------------------------------------------
STEP 9: Migrating database:
--------------------------------------------------------

In ProviderRepository.php line 208:
                                                             
  Class "Facade\Ignition\IgnitionServiceProvider" not found  
                                                             

--------------------------------------------------------
STEP 10: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
STEP 11: Taking application out of maintenance mode:
--------------------------------------------------------

-- 
In ProviderRepository.php line 208:
                                                             
  Class "Facade\Ignition\IgnitionServiceProvider" not found  
                                                             

### Expected behavior

working asset site.

### Snipe-IT Version

latest build

### Operating System

Almalinux

### Web Server

apache

### PHP Version

8.1.27

**Comment by jayavman** [comment]
debug ;

    *
     * @param  \Closure|string  $concrete
     * @return mixed
     *
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     * @throws \Illuminate\Contracts\Container\CircularDependencyException
     */
    public function build($concrete)
    {
        // If the concrete type is actually a Closure, we will just execute it and
        // hand back the results of the functions, which allows functions to be
        // used as resolvers for more fine-tuned resolution of these objects.
        if ($concrete instanceof Closure) {
            return $concrete($this, $this->getLastParameterOverride());
        }
 
        try {
            $reflector = new ReflectionClass($concrete);
        } catch (ReflectionException $e) {
            throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
        }
 
        // If the type is not instantiable, the developer is attempting to resolve
        // an abstract type such as an Interface or Abstract Class and there is
        // no binding registered for the abstractions so we need to bail out.
        if (! $reflector->isInstantiable()) {
            return $this->notInstantiable($concrete);
        }
 
        $this->buildStack[] = $concrete;
 
        $constructor = $reflector->getConstructor();
 
        // If there are no constructors, that means there are no dependencies then
        // we can just resolve the instances of the objects right away, without
        // resolving any other types or dependencies out of these containers.
        if (is_null($constructor)) {
            array_pop($this->buildStack);
 
            return new $concrete;

Arguments

    "Target class [session] does not exist."

 Illuminate \ Contracts \ Container \ BindingResolutionException
Target class [session] does not exist.

**Comment by snipe** [comment]
@jayavman are you still seeing this with a fresh pull as of this morning? We pushed out a few fixes.

**Comment by jayavman** [comment]
All good now . Thanks!
