### ISSUE TITLE
Backup Alert Email Notifications is not displaying normal easy to understand text

### ISSUE THREAD

**Issue by Toby737** [grokability/snipe-it#14917]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

With 7.0.4, the backup notification email content is showing what looks like bits of code instead of normal text, when it was on 6.4.2.

### Reproduction steps

1. Enabled Backup Email Notifications in .env file
2. Run a manual backup to trigger email notification.

### Expected behavior

Previously with 6.4.2, the Backup Email Notification would be...
Hello! 
Great news, a new backup of Snipe-IT was successfully created on the disk named backup. 
Application name: Snipe-IT 
Backup name: backups 
Disk: backup 
Newest backup size: 15.53 MB 
Number of backups: 13 
Total storage used: 199.75 MB 
Newest backup date: 2024/06/19 00:00:03 
Oldest backup date: 2024/06/01 00:00:06 

but with 7.0.4, the email appears as...
Hello! 
backup::notifications.backup_successful_body 
backup::notifications.application_name: Snipe-IT (production) 
backup::notifications.backup_name: backups 
backup::notifications.disk: backup 
backup::notifications.newest_backup_size: 15.52 MB 
backup::notifications.number_of_backups: 2 
backup::notifications.total_storage_used: 31.05 MB 
backup::notifications.newest_backup_date: 2024/06/19 12:22:58 
backup::notifications.oldest_backup_date: 2024/06/19 12:22:01 

### Screenshots

![snipeit 7 0 4](https://github.com/snipe/snipe-it/assets/159442971/237b639e-69aa-4b92-a42e-7b3aa638aee0)
![snipeit 6 4 2](https://github.com/snipe/snipe-it/assets/159442971/cbe8f654-29fb-42af-af74-6cb13b8d0eba)

### Snipe-IT Version

v7.0.4 build 14011 (g20d558785)

### Operating System

Rocky Linux 9

### Web Server

Apache

### PHP Version

8.3.8

### Operating System

Windows

### Browser

Edge

### Version

126.0.2592.61

**Comment by snipe** [comment]
Huh - most folks don't use that feature, so I guess we didn't catch the change on the underlying package's side. We'll need to investigate this a bit more. Thanks for the heads up!

**Comment by Toby737** [comment]
No worries.
Yeah, I was just playing around with it and kinda left it set, and noticed the change after the upgrade to 7.0.4.
Awesome work you guys do though with Snipe-IT.  It's been fantastic to use so far!

**Comment by snipe** [comment]
I can reproduce this locally, which is, as always, both good and bad. The package definitely changed something, I'm just not sure what yet. We'll have it sorted for you shortly tho

**Comment by Toby737** [comment]
Cool no dramas.  It's not that urgent or critical. :)
Thanks!

**Comment by snipe** [comment]
I think I see what happened. They added localization recently (yay!) but they use the two-letter code for language, which we don't use anymore. :-/ `en` vs `en-US`. We had to switch that a few versions back because of the way Symfony handles pluralization, but since there are several "right" ways to do this, I think the two-letter code translations files they provided are not being correctly used.

**Comment by snipe** [comment]
I've opened an issue on laravel-backup's repo to see how to best handle this. For right now, if you change your `fallback_locale` in `app.config` to `en` instead of `en-US` (which is what we set as the default) that will probably resolve this issue for you, but I'm trying to work with the folks at spatie to see how we should handle this longer term, since we don't have `en` files anymore, only `en-US` and `en-GB`, etc.

**Comment by snipe** [comment]
This should be fixed on master now - let me know if you're still having issues after running `upgrade.php`

**Comment by Toby737** [comment]
Awesome! Thanks! Fixed now. 👍 
![Screenshot 2024-06-20 141532](https://github.com/snipe/snipe-it/assets/159442971/935d0ec1-5b93-438f-af96-a85e06a83a99)

**Comment by edd080** [comment]
> This should be fixed on master now - let me know if you're still having issues after running `upgrade.php`

Had the same exact issue as OP, can confirm your fix is working fine now. Many thanks for your great support, keep it up 👍

**Comment by snipe** [comment]
Great to hear it!
