### ISSUE TITLE
#8584 still valid, SAML token validation fails when Snipe-it is behind a reverse proxy, http used intsead of https

### ISSUE THREAD

**Issue by Kofl** [grokability/snipe-it#14919]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The issue https://github.com/snipe/snipe-it/issues/8584 still exists with the latest release (v7.0.4 build 14011 (g20d558785)

LOG.debug: There was an error with SAML ACS: invalid_response
LOG.debug: Reason: The response was received at http://assets.example.com/saml/acs instead of https://assets.example.com/saml/acs

### Reproduction steps

Run Snipe-IT with reverse proxy and use SAML authentication for Snipe-IT

Solution:

baseurl=https://assets.example.com/saml in SAML configuration => SAML settings => SAML Custom Settings

### Expected behavior

The SAML login mechanism uses the correct "frontend" URL (in this case using https) to validate SAML tokens

### Snipe-IT Version

7.0.4

### Operating System

Ubuntu

### Web Server

Docker Image

### PHP Version

Docker Image

**Comment by davidebonavita** [comment]
Hi there,
do you know if there's a way to inject this configuration without reverting the upgrade?
`baseurl=https://assets.example.com/saml in SAML configuration => SAML settings => SAML Custom Settings`

**Comment by Kofl** [comment]
The workaround also works for the latest version, but is only documented in that issue and not finally fixed or documented.

**Comment by davidebonavita** [comment]
Yeah the problem is SAML is our default auth method and we're kinda locked out as the authentication fails

**Comment by Kofl** [comment]
Ah, if you remove REQUIRE_SAML=true in your env, then local user login is again allowed. Not aware of any other way to set baseurl

**Comment by uberbrady** [comment]
We *do* have a concept of `APP_URL` which would make sense to use as the basis of the default 'baseurl' setting, I'm just wondering where, exactly, we would go about putting that...

**Comment by snipe** [comment]
I'm not really sure why this change would even be needed though.

https://github.com/snipe/snipe-it/blob/30c1e1e86a4d46e151e2ba7e41444dc8e916828c/app/Providers/AppServiceProvider.php#L43-L54

In the service provider, we are checking to see if your `APP_URL` in your `.env` starts with `https://` or if you have `APP_FORCE_TLS=true` in your `.env` and the  forces all traffic to use the https schema.

**Comment by uberbrady** [comment]
> Hi there, do you know if there's a way to inject this configuration without reverting the upgrade? `baseurl=https://assets.example.com/saml in SAML configuration => SAML settings => SAML Custom Settings`

Are you saying here that going into the "SAML Custom Settings" and putting `baseurl=https://assets.example.com/saml` is not working for you?

**Comment by uberbrady** [comment]
> I'm not really sure why this change would even be needed though.
> 
> https://github.com/snipe/snipe-it/blob/30c1e1e86a4d46e151e2ba7e41444dc8e916828c/app/Providers/AppServiceProvider.php#L43-L54
> 
> In the service provider, we are checking to see if your `APP_URL` in your `.env` starts with `https://` or if you have `APP_FORCE_TLS=true` in your `.env` and the forces all traffic to use the https schema.

I think this is more on the 'calculating the signature' part of the SAML process, but I'm still trying to wrap my head around all of this right now, tbh.

**Comment by uberbrady** [comment]
I'm kinda feeling like we might want to put this somewhere around here: https://github.com/snipe/snipe-it/blob/master/app/Services/Saml.php#L165 - but I'm still not sure.

Probably something like 

```php
if(!$config['baseurl']) { /* ... */ }
```

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/blob/master/app/Services/Saml.php">snipe-it/app/Services/Saml.php at master · snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by mhegreberg** [comment]
I have this same issue when upgrading to 7.0.3 or 7.0.4 from 6.2.3

I'm running snipe-it on kubernetes from a helm chart I wrote, behind either traefik or nginx ingress. in 6.2.3 it worked fine.

I've set `APP_FORCE_TLS` to true, added the appropriate IPs to `APP_TRUSTED_PROXIES`, and verified I was setting `APP_URL` to https.

same errors as the OP:
```
[2024-06-20 09:01:56] production.ERROR: Reason: The response was received at http://snipeit.../saml/acs instead of https://snipeit..../saml/acs  

[2024-06-20 09:01:56] production.ERROR: There was an error with SAML ACS: invalid_response
```

**Comment by Kofl** [comment]
> > Hi there, do you know if there's a way to inject this configuration without reverting the upgrade? `baseurl=https://assets.example.com/saml in SAML configuration => SAML settings => SAML Custom Settings`
> 
> Are you saying here that going into the "SAML Custom Settings" and putting `baseurl=https://assets.example.com/saml` is not working for you?

They upgraded and got locked out because they only allowed SAML to log in, as far as I could tell.

**Comment by fstorz** [comment]
> I'm kinda feeling like we might want to put this somewhere around here: https://github.com/snipe/snipe-it/blob/master/app/Services/Saml.php#L165 - but I'm still not sure.
> 
> Probably something like
> 
> ```
> if(!$config['baseurl']) { /* ... */ }
> ```
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a"><img alt="" height="14" src="https://camo.githubusercontent.com/95e35b1ddbd18e9680ef4876f3544fdf46e2116b5fefc3f6a48e1e427ea75b59/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[snipe-it/app/Services/Saml.php at master · snipe/snipe-it](https://github.com/snipe/snipe-it/blob/master/app/Services/Saml.php)**A free open source IT asset/license management system - snipe/snipe-it

Maybe this?
```php
data_set($settings, 'baseurl', config('app.url').'/saml');
```

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/blob/master/app/Services/Saml.php">snipe-it/app/Services/Saml.php at master · snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by uberbrady** [comment]
Yes, exactly that - if anyone can confirm that adding that line *and* removing any `baseurl` from "SAML Custom Settings" then their SAML continues to work behind a reverse proxy, that would be *AWESOME*.

If so, and if you'd like, you can PR it (against 'develop' please!) and we'll take it.

If it works, and you *don't* feel like (which is OK!), please let us know and we'll get it merged in as quickly as we can.

Thank you!

**Comment by mhegreberg** [comment]
I can try this. Im setting everything as environment variables, so whats the exaxt variable that needs to be set? Or is this a setting i need to log in to update?

**Comment by myevit** [comment]
> > > Hi there, do you know if there's a way to inject this configuration without reverting the upgrade? `baseurl=https://assets.example.com/saml in SAML configuration => SAML settings => SAML Custom Settings`
> > 
> > 
> > Are you saying here that going into the "SAML Custom Settings" and putting `baseurl=https://assets.example.com/saml` is not working for you?
> 
> They upgraded and got locked out because they only allowed SAML to log in, as far as I could tell.

I had the same issue....

maybe try this? 
You can use '/login?nosaml' to get to the normal login page.

**Comment by davidebonavita** [comment]
> Ah, if you remove REQUIRE_SAML=true in your env, then local user login is again allowed. Not aware of any other way to set baseurl

It indeed worked, thanks!

**Comment by chadfrownfelter** [comment]
> Yes, exactly that - if anyone can confirm that adding that line _and_ removing any `baseurl` from "SAML Custom Settings" then their SAML continues to work behind a reverse proxy, that would be _AWESOME_.
> 
> If so, and if you'd like, you can PR it (against 'develop' please!) and we'll take it.
> 
> If it works, and you _don't_ feel like (which is OK!), please let us know and we'll get it merged in as quickly as we can.
> 
> Thank you!

I added the following line [here](https://github.com/snipe/snipe-it/blob/master/app/Services/Saml.php#L165), removed the `baseurl` from the custom SAML settings, [cleared the cache](https://snipe-it.readme.io/docs/clearing-the-config-cache), and confirmed I can authenticate with SAML successfully. I still have the `APP_FORCE_TLS=true` environment variable set as well.

```
data_set($settings, 'baseurl', config('app.url').'/saml');
```

**Comment by snipe** [comment]
Awesome, thank you! We’ll get that patched for you shortly.

**Comment by uberbrady** [comment]
v7.0.6 was just released, which includes this fix.

**Comment by mhegreberg** [comment]
I can confirm that this fix worked for me!
