### ISSUE TITLE
[Feature Request]: In General Settings --> Email Format, add Last Name First Name (smith.jane@example.com)

### ISSUE THREAD

**Issue by Toby737** [grokability/snipe-it#14918]
### Is your feature request related to a problem? Please describe.

Feature is not related to a problem.

### Describe the solution you'd like

For our organisation, we use surname.firstname@domain.com, would be great to add this email format to Snipe-IT in General Settings --> Email Format.

**Comment by snipe** [comment]
This should be available on master now.
