### ISSUE TITLE
Side Bar and Status Lists not showing correct Asset quantity

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#14916]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Status side bar not showing correct Asset quantity and also now status on each asset status is now empty but ok in the list all area.

### Reproduction steps

![Screenshot 2024-06-20 180723](https://github.com/snipe/snipe-it/assets/114973646/a21fbbff-126b-4a85-82bd-034bbbaec516)
As you can see many assets in many Status Labels.

Side Bar showing no assets in all the status labels and all under "List All"
![Screenshot 2024-06-20 180845](https://github.com/snipe/snipe-it/assets/114973646/d81a5a37-0919-457d-9738-989c823eb346)

I go into Active assets
![Screenshot 2024-06-20 180909](https://github.com/snipe/snipe-it/assets/114973646/e283f8ab-7708-49b0-afd0-585cdb97e247)

### Expected behavior

Should show assets in each status label, and side bar should show numbers of assets on each status.

### Snipe-IT Version

v7.0.4 build 14011 (g20d558785)

### Operating System

almalinux

### Web Server

apache

### PHP Version

8.1.29

**Comment by snipe** [comment]
Are you able to reproduce this on the demo? I'm not able to reproduce this locally.

**Comment by jayavman** [comment]
I havent set so many status on the demo and added all the assets in multiple status

**When going to say active status this is my debug (which doesnt work)**

select * from `users` where `id` = 1 and `users`.`deleted_at` is null limit 1
900μsfredons_assetEloquentUserProvider.php#59
select `permission_groups`.*, `users_groups`.`user_id` as `pivot_user_id`, `users_groups`.`group_id` as `pivot_group_id` from `permission_groups` inner join `users_groups` on `permission_groups`.`id` = `users_groups`.`group_id` where `users_groups`.`user_id` = 1
620μsfredons_assetUser.php#147
select * from `custom_fields`
610μsfredons_assetAssetsController.php#123
select count(*) as aggregate from `assets` inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` where `assets`.`status_id` = '2' and `assets`.`deleted_at` is null
680μsfredons_assetAssetsController.php#386
select count(*) as aggregate from `assets` inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` where `assets`.`status_id` = '2' and `assets`.`deleted_at` is null
440μsfredons_assetAssetsController.php#389
select `assets`.* from `assets` inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` where `assets`.`status_id` = '2' and `assets`.`deleted_at` is null order by `assets`.`created_at` asc limit 300 offset 0
550μsfredons_assetAssetsController.php#390

**then if i go to all assets (which lists all assets and it works) here is debug**

select * from `users` where `id` = 1 and `users`.`deleted_at` is null limit 1
770μsfredons_assetEloquentUserProvider.php#59
select `permission_groups`.*, `users_groups`.`user_id` as `pivot_user_id`, `users_groups`.`group_id` as `pivot_group_id` from `permission_groups` inner join `users_groups` on `permission_groups`.`id` = `users_groups`.`group_id` where `users_groups`.`user_id` = 1
530μsfredons_assetUser.php#147
select * from `custom_fields`
370μsfredons_assetAssetsController.php#123
select count(*) as aggregate from `assets` inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` where `assets`.`deleted_at` is null
3.91msfredons_assetAssetsController.php#386
select count(*) as aggregate from `assets` inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` where `assets`.`deleted_at` is null
3.93msfredons_assetAssetsController.php#389
select `assets`.* from `assets` inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` where `assets`.`deleted_at` is null order by `name` asc limit 300 offset 0
3.14msfredons_assetAssetsController.php#390
select * from `locations` where `locations`.`id` in (38, 49, 50, 51, 303, 314, 322, 324, 376, 377, 378, 381, 382, 383, 430, 534, 537, 698, 897, 1166) and `locations`.`deleted_at` is null
720μsfredons_assetAssetsController.php#390
select * from `status_labels` where `status_labels`.`id` in (12, 14, 15, 16, 17, 18) and `status_labels`.`deleted_at` is null
510μsfredons_assetAssetsController.php#390
select * from `companies` where `companies`.`id` in (1)
430μsfredons_assetAssetsController.php#390
select * from `locations` where `locations`.`id` in (38, 49, 50, 51, 303, 314, 322, 324, 376, 377, 378, 381, 382, 383, 430, 534, 537, 698, 897, 1166) and `locations`.`deleted_at` is null
530μsfredons_assetAssetsController.php#390
select * from `models` where `models`.`id` in (18, 23, 108, 109, 148, 149, 196, 222, 223, 229, 230, 231, 512, 548, 621, 667, 668, 672, 688, 689, 812)
540μsfredons_assetAssetsController.php#390
select * from `categories` where `categories`.`id` in (25, 27, 28, 29, 49, 50) and `categories`.`deleted_at` is null
540μsfredons_assetAssetsController.php#390
select * from `manufacturers` where `manufacturers`.`id` in (22, 33, 37, 47, 55, 99, 110) and `manufacturers`.`deleted_at` is null
720μsfredons_assetAssetsController.php#390
select * from `custom_fieldsets` where `custom_fieldsets`.`id` in (2)
280μsfredons_assetAssetsController.php#390
select * from `suppliers` where `suppliers`.`id` in (7, 11) and `suppliers`.`deleted_at` is null
340μsfredons_assetAssetsController.php#390
select `custom_fields`.*, `custom_field_custom_fieldset`.`custom_fieldset_id` as `pivot_custom_fieldset_id`, `custom_field_custom_fieldset`.`custom_field_id` as `pivot_custom_field_id`, `custom_field_custom_fieldset`.`required` as `pivot_required`, `custom_field_custom_fieldset`.`order` as `pivot_order` from `custom_fields` inner join `custom_field_custom_fieldset` on `custom_fields`.`id` = `custom_field_custom_fieldset`.`custom_field_id` where `custom_field_custom_fieldset`.`custom_fieldset_id` = 2 order by `pivot_order` asc
1.05msfredons_assetAssetsTransformer.php#102
select * from `depreciations` where `depreciations`.`id` = 1 limit 1
950μsfredons_assetAsset.php#452
select * from `depreciations` where `depreciations`.`id` = 2 limit 1
580μsfredons_assetAsset.php#452
select * from `depreciations` where `depreciations`.`id` = 2 limit 1

**Comment by snipe** [comment]
Okay, so to restate the problem, the quantities on *custom* status labels (versus the sort of meta status we use) are not correct, do I understand that correctly? I'll try to test on my side.

**Comment by snipe** [comment]
Hm, I'm still not able to reproduce this. 

<img width="346" alt="Screenshot 2024-06-20 at 1 16 14 PM" src="https://github.com/snipe/snipe-it/assets/197404/98cdec12-9d7e-493f-9403-db0ac170075e">
<img width="473" alt="Screenshot 2024-06-20 at 1 16 23 PM" src="https://github.com/snipe/snipe-it/assets/197404/5302eda5-619d-4ce0-afcb-a421fe2cf992">

**Comment by jayavman** [comment]
Thats correct, Also when i go to any of the status on the side bar it shows nothing in each asset. Even though they have assets listed as that status (as you can see in the pie graph)

@snipe  no idea why its happening. Any ideas?

**Comment by snipe** [comment]
I'm not able to reproduce that locally. Are those assets archived? Do you have "Show archived in lists" checked or unchecked in Admin Settings > General?

<img width="1477" alt="Screenshot 2024-06-20 at 1 45 39 PM" src="https://github.com/snipe/snipe-it/assets/197404/1ed50383-6fa6-4562-97a8-cd7b50be94e0">

**Comment by jayavman** [comment]
I'm an idiot, the ones that were showing on the side nav were old status and had no assets in them. The new status one's didnt have enabled side bar active.
We can close this one.

**Comment by snipe** [comment]
Glad you're sorted. (We all have days like this. Don't be so hard on yourself.)
