### ISSUE TITLE
[Feature Request]: Share search results

### ISSUE THREAD

**Issue by picotom** [grokability/snipe-it#14928]
### Is your feature request related to a problem? Please describe.

We have a custom field for what maintenance window certain machines are in. The only was we can filter these is by using the search and searching for the maintenance window name.

### Describe the solution you'd like

It would be nice to be able to send a search result link to a colleague or to post in documentation so that it will perform a up to date search when you click the list.  

### Describe alternatives you've considered

Manually typing the name into search is annoying and not very effeicent.

**Comment by snipe** [comment]
I don't know what version you're on, but we added deep linking to search and sort results some time ago. Add `BS_TABLE_DEEPLINK=true` to your .env.

https://snipe-it.readme.io/docs/configuration#optional-session-settings

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#optional-session-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required. Don't be intimidated by the length of this page. The configurati...</div></blockquote>
