### ISSUE TITLE
"Error: User does not exist." when trying to delete an LDAP synced user

### ISSUE THREAD

**Issue by mike3085** [grokability/snipe-it#14935]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am trying to delete an LDAP synced user by clicking the orange "Delete" button on the right side of the user's page. Doing so leads to an error message "Error: User does not exist". I've also tried using the Checkin All / Delete User button as well and it does not delete the user. I'm not seeing anything odd immediately sticking out to me in the debug mode. Any help would be appreciated.

Edit: Also not sure if it is relevant, but this was a user that was created locally first, and the LDAP sync had a matching username so it merged with this local user.

### Reproduction steps

Sync LDAP
Try to delete a user

### Expected behavior

The user should be deleted from SnipeIT but it I encounter an error instead.

### Snipe-IT Version

7.0.4 build 14011

### Operating System

Ubuntu 22.04.4 LTS

### Web Server

Apache

### PHP Version

8.1

### Additional context

It is an upgrade install coming from 6.4.2

**Comment by snipe** [comment]
Do they show as LDAP synced in their profile/listing?

**Comment by snipe** [comment]
I can reproduce this locally - I'll have a fix for you shortly.

**Comment by snipe** [comment]
Can you pull latest from master - I just pushed up a fix

**Comment by mike3085** [comment]
Confirmed working, thanks

**Comment by snipe** [comment]
Excellent - thanks for the heads up!
