### ISSUE TITLE
BUG: Why import asset can not import more than 1642 rows one time ???

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#14943]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

[sample-assets 20240624 (1643).csv](https://github.com/user-attachments/files/15949258/sample-assets.20240624.1643.csv)
[sample-assets 20240624 (4).csv](https://github.com/user-attachments/files/15949259/sample-assets.20240624.4.csv)
[sample-assets 20240624 (1642).csv](https://github.com/user-attachments/files/15949260/sample-assets.20240624.1642.csv)
![import error](https://github.com/snipe/snipe-it/assets/156650496/86d550cf-6f2b-4e6b-a8ef-341778dae125)

### Reproduction steps

when import 1642 rows is ok
but more than 1642 rows is error

### Expected behavior

when import 1642 rows is ok
but more than 1642 rows is error

### Screenshots

![import error](https://github.com/snipe/snipe-it/assets/156650496/5d3bab7e-f7b4-40e9-b476-06111ec2a201)

### Snipe-IT Version

v6.4.2 build 13487 (gb489c71fa2)

### Operating System

Ubuntu, Windows

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

windows

### Browser

google

**Comment by snipe** [comment]
There is no such limitation. Something is incorrect in your CSV, per the error message.

**Comment by huifei0129** [comment]
but i have check, not the error message

bucause i delete the 1643 item just improt 1642 rows is ok
only import the single "1643" item is ok
merge the all items is error.

there is the csv file above, you can try.

**Comment by huifei0129** [comment]
Thank you very much, I found maybe the database error
