### ISSUE TITLE
1、Not "bulk check in" ? Only can check in all items from the user. but sometimes only need to bulk check in some items not all items.  2、Can not transfer to another user directly. eg. (check out to: user1) to (check out to: user2).  3、"Checked Out to" this filed can not bult edit.

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#14945]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

1、Not "bulk check in" ? Only can check in all items from the user.
but sometimes only need to bulk check in some items not all items.

2、Can not transfer to another user directly .
eg. (check out to: user1) to (check out to: user2)

3、"Checked Out to" this filed can not bult edit.

### Reproduction steps

![bulk check in](https://github.com/snipe/snipe-it/assets/156650496/7fd7b48b-eb66-4401-acaa-c6299bcbc9ad)
![Check in from user](https://github.com/snipe/snipe-it/assets/156650496/7227b4a7-c20b-4e0d-be94-8ccaa6e890f6)

### Expected behavior

1、Not "bulk check in" ? Only can check in all items from the user.
but sometimes only need to bulk check in some items not all items.

2、Can not transfer to another user directly .
eg. (check out to: user1) to (check out to: user2)

3、"Checked Out to" this filed can not bult edit.

### Screenshots

![bulk check in](https://github.com/snipe/snipe-it/assets/156650496/43603fa5-0d98-4e20-853e-62981fd3da0b)
![Check in from user](https://github.com/snipe/snipe-it/assets/156650496/63f232f4-4575-4282-92cc-85d970283d75)

### Snipe-IT Version

v6.4.2 build 13487 (gb489c71fa2)

### Operating System

Ubuntu, Windows

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

**Comment by snipe** [comment]
Please do not combine 3 issues/questions into one issue.
