### ISSUE TITLE
[Feature Request]: Can not display more than 500 rows? If have 10k rows, may need custom display rows

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#14944]
### Is your feature request related to a problem? Please describe.

![max rows](https://github.com/snipe/snipe-it/assets/156650496/67f67f49-e251-49a4-893e-a8efae284356)

### Describe the solution you'd like

Can not display more than 500 rows? 
If have 10k rows, may need custom display rows!!

**Comment by snipe** [comment]
You can change your `MAX_RESULTS` in your `.env` to a higher number, however you will find the system gets very slow at 10k since it has to write so much to the browser. You'd be much better off filtering your results to get the things you need in smaller chunks.
