### ISSUE TITLE
Error: Backup failed because: The dump process failed with a none successful exitcode. Exitcode ======== 1: General error Output 

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#14959]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

when i click "Generate Backup", error below

![backup error](https://github.com/snipe/snipe-it/assets/156650496/5d914eac-c5dc-4cc8-9d72-27dd96766c30)

### Reproduction steps

1. Generate Backup
2.
3.
...

### Expected behavior

how to solve it?

### Snipe-IT Version

v7.0.5 build 14092 (g294fb1f77) 

### Operating System

Windows

### Web Server

mysql

### PHP Version

8.1.25

### Operating System

windows

**Comment by snipe** [comment]
This is generally related to a misconfiguration of the mysqldump path. Please search the closed issues for "Backup failed"
