### ISSUE TITLE
Status - 500 Assets do not show in Status

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#14957]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Updated to latest snipe version. When going to Status now it has 500 assets in a newly credit status. If you click on these assets they do not exist and cannot be reassigned to another status.

### Reproduction steps

1. go to status label
![Screenshot 2024-06-25 135109](https://github.com/snipe/snipe-it/assets/114973646/cd5d6f5d-6e96-4381-843c-3b54a9d3a9dc)
2. Click on the one with 500 assets
![Screenshot 2024-06-25 135122](https://github.com/snipe/snipe-it/assets/114973646/7103874b-0f12-4883-ac02-0e2ec02d2be8)

Tried another one, 
![Screenshot 2024-06-25 135102](https://github.com/snipe/snipe-it/assets/114973646/c7e46ad6-9f54-4866-b8eb-8573d0be4cdc)

![Screenshot 2024-06-25 135122](https://github.com/snipe/snipe-it/assets/114973646/7103874b-0f12-4883-ac02-0e2ec02d2be8)

### Expected behavior

I cannot remove these status as they have 500 assets in each of these labels but they dont exist. Not sure why

### Snipe-IT Version

 v7.0.5 build 14092 (g294fb1f77) 

### Operating System

almalinux

### Web Server

apache

### PHP Version

8.1.29

**Comment by jayavman** [comment]
@snipe 
<html><body>
<li class="phpdebugbar-widgets-list-item" connection="fredons_asset" style="cursor: pointer;"><code class="phpdebugbar-widgets-sql"><span class="hljs-keyword">select</span> <span class="hljs-operator">*</span> <span class="hljs-keyword">from</span> `users` <span class="hljs-keyword">where</span> `id` <span class="hljs-operator">=</span> <span class="hljs-number">1</span> <span class="hljs-keyword">and</span> `users`.`deleted_at` <span class="hljs-keyword">is</span> <span class="hljs-keyword">null</span> limit <span class="hljs-number">1</span></code><span title="Duration" class="phpdebugbar-widgets-duration">890μs</span><span title="Connection" class="phpdebugbar-widgets-database">fredons_asset</span><span title="Filename" class="phpdebugbar-widgets-filename">EloquentUserProvider.php#59<a href="phpstorm://open?file=%2Fhome%2Ffredons%2Fpublic_html%2Fasset%2Fvendor%2Flaravel%2Fframework%2Fsrc%2FIlluminate%2FAuth%2FEloquentUserProvider.php&amp;line=59" class="phpdebugbar-widgets-editor-link"></a></span>
Bindings | 0: 1
-- | --
Hints | 0: Use SELECT * only if you need all columns from table1: LIMIT without ORDER BY causes non-deterministic results, depending on the query execution plan
Backtrace | 16. vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php:5917. vendor/laravel/passport/src/PassportUserProvider.php:4218. vendor/laravel/passport/src/Guards/TokenGuard.php:25719. vendor/laravel/passport/src/Guards/TokenGuard.php:12220. vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php:56

</li><li class="phpdebugbar-widgets-list-item" connection="fredons_asset" style="cursor: pointer;"><code class="phpdebugbar-widgets-sql"><span class="hljs-keyword">select</span> `permission_groups`.<span class="hljs-operator">*</span>, `users_groups`.`user_id` <span class="hljs-keyword">as</span> `pivot_user_id`, `users_groups`.`group_id` <span class="hljs-keyword">as</span> `pivot_group_id` <span class="hljs-keyword">from</span> `permission_groups` <span class="hljs-keyword">inner</span> <span class="hljs-keyword">join</span> `users_groups` <span class="hljs-keyword">on</span> `permission_groups`.`id` <span class="hljs-operator">=</span> `users_groups`.`group_id` <span class="hljs-keyword">where</span> `users_groups`.`user_id` <span class="hljs-operator">=</span> <span class="hljs-number">1</span></code><span title="Duration" class="phpdebugbar-widgets-duration">710μs</span><span title="Connection" class="phpdebugbar-widgets-database">fredons_asset</span><span title="Filename" class="phpdebugbar-widgets-filename">User.php#147<a href="phpstorm://open?file=%2Fhome%2Ffredons%2Fpublic_html%2Fasset%2Fapp%2FModels%2FUser.php&amp;line=147" class="phpdebugbar-widgets-editor-link"></a></span></li><li class="phpdebugbar-widgets-list-item" connection="fredons_asset" style="cursor: pointer;"><code class="phpdebugbar-widgets-sql"><span class="hljs-keyword">select</span> <span class="hljs-operator">*</span> <span class="hljs-keyword">from</span> `custom_fields`</code><span title="Duration" class="phpdebugbar-widgets-duration">610μs</span><span title="Connection" class="phpdebugbar-widgets-database">fredons_asset</span><span title="Filename" class="phpdebugbar-widgets-filename">AssetsController.php#123<a href="phpstorm://open?file=%2Fhome%2Ffredons%2Fpublic_html%2Fasset%2Fapp%2FHttp%2FControllers%2FApi%2FAssetsController.php&amp;line=123" class="phpdebugbar-widgets-editor-link"></a></span></li><li class="phpdebugbar-widgets-list-item phpdebugbar-widgets-sql-duplicate" connection="fredons_asset" style="cursor: pointer;"><code class="phpdebugbar-widgets-sql"><span class="hljs-keyword">select</span> <span class="hljs-built_in">count</span>(<span class="hljs-operator">*</span>) <span class="hljs-keyword">as</span> aggregate <span class="hljs-keyword">from</span> `assets` <span class="hljs-keyword">inner</span> <span class="hljs-keyword">join</span> `status_labels` <span class="hljs-keyword">as</span> `status_alias` <span class="hljs-keyword">on</span> `status_alias`.`id` <span class="hljs-operator">=</span> `assets`.`status_id` <span class="hljs-keyword">where</span> `assets`.`status_id` <span class="hljs-operator">=</span> <span class="hljs-string">'22'</span> <span class="hljs-keyword">and</span> `assets`.`deleted_at` <span class="hljs-keyword">is</span> <span class="hljs-keyword">null</span></code><span title="Duration" class="phpdebugbar-widgets-duration">810μs</span><span title="Connection" class="phpdebugbar-widgets-database">fredons_asset</span><span title="Filename" class="phpdebugbar-widgets-filename">AssetsController.php#386<a href="phpstorm://open?file=%2Fhome%2Ffredons%2Fpublic_html%2Fasset%2Fapp%2FHttp%2FControllers%2FApi%2FAssetsController.php&amp;line=386" class="phpdebugbar-widgets-editor-link"></a></span></li><li class="phpdebugbar-widgets-list-item phpdebugbar-widgets-sql-duplicate" connection="fredons_asset" style="cursor: pointer;"><code class="phpdebugbar-widgets-sql"><span class="hljs-keyword">select</span> <span class="hljs-built_in">count</span>(<span class="hljs-operator">*</span>) <span class="hljs-keyword">as</span> aggregate <span class="hljs-keyword">from</span> `assets` <span class="hljs-keyword">inner</span> <span class="hljs-keyword">join</span> `status_labels` <span class="hljs-keyword">as</span> `status_alias` <span class="hljs-keyword">on</span> `status_alias`.`id` <span class="hljs-operator">=</span> `assets`.`status_id` <span class="hljs-keyword">where</span> `assets`.`status_id` <span class="hljs-operator">=</span> <span class="hljs-string">'22'</span> <span class="hljs-keyword">and</span> `assets`.`deleted_at` <span class="hljs-keyword">is</span> <span class="hljs-keyword">null</span></code><span title="Duration" class="phpdebugbar-widgets-duration">690μs</span><span title="Connection" class="phpdebugbar-widgets-database">fredons_asset</span><span title="Filename" class="phpdebugbar-widgets-filename">AssetsController.php#389<a href="phpstorm://open?file=%2Fhome%2Ffredons%2Fpublic_html%2Fasset%2Fapp%2FHttp%2FControllers%2FApi%2FAssetsController.php&amp;line=389" class="phpdebugbar-widgets-editor-link"></a></span></li><li class="phpdebugbar-widgets-list-item" connection="fredons_asset" style="cursor: pointer;"><code class="phpdebugbar-widgets-sql"><span class="hljs-keyword">select</span> `assets`.<span class="hljs-operator">*</span> <span class="hljs-keyword">from</span> `assets` <span class="hljs-keyword">inner</span> <span class="hljs-keyword">join</span> `status_labels` <span class="hljs-keyword">as</span> `status_alias` <span class="hljs-keyword">on</span> `status_alias`.`id` <span class="hljs-operator">=</span> `assets`.`status_id` <span class="hljs-keyword">where</span> `assets`.`status_id` <span class="hljs-operator">=</span> <span class="hljs-string">'22'</span> <span class="hljs-keyword">and</span> `assets`.`deleted_at` <span class="hljs-keyword">is</span> <span class="hljs-keyword">null</span> <span class="hljs-keyword">order</span> <span class="hljs-keyword">by</span> `name` <span class="hljs-keyword">asc</span> limit <span class="hljs-number">500</span> <span class="hljs-keyword">offset</span> <span class="hljs-number">500</span></code></li>
</body>
</html>


laravel log :

#48 /home/fredons/public_html/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\NoSessionStore->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /home/fredons/public_html/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/fredons/public_html/asset/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#51 /home/fredons/public_html/asset/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#52 /home/fredons/public_html/asset/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#53 {main}

**Comment by snipe** [comment]
Is there anything in your app log? (Please stop including the debugbar output. It almost always offers nothing of value for troubleshooting - useful for developing, but not great for troubleshooting, as all it's doing is showing me queries, not stack traces.)

Is it possible these items are archived?

**Comment by jayavman** [comment]
I still have Show archived assets in the "all assets" listing  ticked.

How do i get the app log?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by snipe** [comment]
The laravel.log output is what we need, but that's too little of it. That's all framework level stuff, which I'm pretty sure isn't the issue here.

**Comment by jayavman** [comment]
resolved mysteriously.
