### ISSUE TITLE
[Feature Request]: Update documentation to include most recent changelog

### ISSUE THREAD

**Issue by pieterhouwen** [grokability/snipe-it#14953]
### Is your feature request related to a problem? Please describe.

The changelog at https://snipe-it.readme.io/changelog has not been updated since Snipe-IT v4 which makes it a lot harder to find out what exactly has been changed/added to Snipe-IT short of reading all commit and/or release messages on Github.

### Describe the solution you'd like

It would be great if the Changelog at the Readme.io site would be maintained so people would have a more comprehensive understanding of what has been changed in the software and/or api. On the page https://grokstar.dev/news/snipeit-releases/2023/11/snipe-it-v7-roadmap/ there was mention of "Custom fields for more item types, starting with users" but I cannot see if this is actually already implemented or not without going through all the commits on github or the release notes.

### Describe alternatives you've considered

If maintaining a list of changes would be too cumbersome to do on 2 places since it is already described in Github, the Changelog hyperlink can just as easily be pointed to the Releases page on github.

### Additional context

In terms of API changes or additions I think it will be beneficial to have that on a seperate page so developers can easily see if/what has been done to the API over the releases.

**Comment by snipe** [comment]
I don't really know of a way of handling those changelogs in a way that wouldn't get out of date, tbh. I'll happily link to the releases page in the docs, but we release so often, going through the actual releases from the version you have and the version you're upgrading to is the only current way. It would be way too unwieldy I think to try to do that manually on our end.

Honestly, I had completely forgotten about the changelog feature of readme.io to be honest. While I like their platform, their changelog is very clunky to use and I'd basically just be copy+pasting from GH - and with ADHD, there's no way I'll remember to do that every time we release. Like, I *want* to remember to do that, but I know I'll forget, as I already clearly have. 

I sorta feel like it's aimed more at closed source companies, not FOSS. https://docs.readme.com/main/docs/changelog 

I guess I can add one final post that just points people to the releases page. Thanks for the reminder that this exists!

<blockquote><img src="https://readme.com/static/og_images/index.png" width="48" align="right"><div>ReadMe</div><div><strong><a href="https://docs.readme.com/main/docs/changelog">Changelog</a></strong></div><div>Keep a running record of your latest updates</div></blockquote>

**Comment by snipe** [comment]
Looks like they changed the way they handle changelogs there. They used to have a cool way of adding a list of things, which was tedious to type in line by line, but you could mark an individual item as a feature, improvement, addition, etc. Now the entire post has to be labeled as such, which sorta doesn't work for us, since each release is a bunch of fixes *and* features.

For API changes, we do at least try to document those in the release notes.

**Comment by pieterhouwen** [comment]
I understand completely, I also often run into problems with my adhd and these types of things. I think the best option then would be to have a general announcement on the changelog page which points people to the releases page on github.
