### ISSUE TITLE
User synchronized from ldap login to the system, their email disappears

### ISSUE THREAD

**Issue by Datinhkhach** [grokability/snipe-it#14958]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When a user synchronized from ldap login to the system, their email immediately disappears.

### Reproduction steps

1. Synchronize new users from ldap
2. Edit the profile of any user that has just been synchronized. Then add an email address to that profile.
![Screenshot 2024-06-25 095916](https://github.com/snipe/snipe-it/assets/86252906/e512885b-e529-4d1a-87e3-fb3b1d318b75)
3. Use the account just filled in with the email address above to login to the system.Account logged in successfully, no error message.
4. Check the account just logged in and realize that the email address entered has disappeared (no error message again).
![Screenshot 2024-06-25 110431](https://github.com/snipe/snipe-it/assets/86252906/f05a3d4c-e3ba-448d-99f6-02d54cf7af09)

...

### Expected behavior

Accounts with email addresses can log in successfully and still retain their email addresses. The account has a new email address that can be used to send notifications when checking out/checking in the asset.

### Screenshots

![Screenshot 2024-06-25 103508](https://github.com/snipe/snipe-it/assets/86252906/0a2ccfae-5ae6-4f2b-929b-f7993bc7d831)

### Snipe-IT Version

7.0.3

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.2

### Error messages

```shell
Error with Feature-Policy header: Unrecognized feature: 'document-domain'.
```

### Additional context

I have enabled debug mode , but no Debug bar show on the screen . Check laravel log have error : production.ERROR: Error: Class "Debugbar" not found in /var/www/snipe-it/app/Http/Controllers/Users/UsersController.php:491 .

**Comment by Datinhkhach** [comment]
I consulted a few topics and found an idea related to APP_URL in the .env file . This is my .env :
```
APP_ENV=production
APP_DEBUG=true
APP_KEY=
APP_URL=http://it.local
APP_TIMEZONE='Asia/Ho_Chi_Minh'
APP_LOCALE='en-US'
MAX_RESULTS=500
```

I tried change APP_URL value to IP but have error : 404 Not Found . Haven't found a solution yet.

**Comment by Datinhkhach** [comment]
Is there any advice possible?

**Comment by Datinhkhach** [comment]
@snipe Can you remove the "Not a bug" label from this issue. This is indeed a bug.

PS : Sorry for my english, i'm using translator and sometime it's not clear to understand exactly what I want.

**Comment by Datinhkhach** [comment]
I am using the Office 365 setup below, sending emails upon assets checkin/checkout works fine. However, when a user logs into the system to accept the asset, their email immediately disappears from their profile. This requires me to manually fix it by re-entering their email into their profile.

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=xxxxxxxxxxxxxxxxxxxxxxxxx
MAIL_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxx
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=xxxxxxxxxxxxxxxxxxxxxxxxx
MAIL_FROM_NAME='Đoàn Trung Hiếu'
MAIL_REPLYTO_ADDR=xxxxxxxxxxxxxxxxxxxxxxxxx
MAIL_REPLYTO_NAME='Đoàn Trung Hiếu'
MAIL_AUTO_EMBED_METHOD='attachment'
```

**Comment by snipe** [comment]
> @snipe Can you remove the "Not a bug" label from this issue. This is indeed a bug.

I don't believe it is. With 6k customers and at least 10k+ free users, we would have seen this before. This is almost certainly an LDAP field mapping issue.

**Comment by snipe** [comment]
We're still investigating, but this does not seem like a bug to me. I cannot reproduce this on any of our systems.

**Comment by snipe** [comment]
https://github.com/snipe/snipe-it/blob/28abb8d8cc269af554f562bac639124e3cf5bc3d/app/Http/Controllers/Auth/LoginController.php#L170-L215

Specifically:
https://github.com/snipe/snipe-it/blob/28abb8d8cc269af554f562bac639124e3cf5bc3d/app/Http/Controllers/Auth/LoginController.php#L209

**Comment by Datinhkhach** [comment]
Here is my ldap setup, sync works fine.

![Screenshot 2024-08-07 083415](https://github.com/user-attachments/assets/2b5084ed-4c24-4160-8406-b91f53f32345)
![image](https://github.com/user-attachments/assets/e6a9ba82-fae2-4a1a-90ea-75974e133211)
![image](https://github.com/user-attachments/assets/8b4a7c81-cca4-45a3-8b5b-8462dbac53e8)

**Comment by snipe** [comment]
Yah, so you're not mapping any of those fields. Map the fields to your LDAP and you'll be fine.

**Comment by Datinhkhach** [comment]
Thanks for helping me find the cause of the error, so I have to "Map the fields" in this picture right?

![image](https://github.com/user-attachments/assets/e6a9ba82-fae2-4a1a-90ea-75974e133211)

**Comment by Datinhkhach** [comment]
The solution to my problem is as follows, hope it will help guys later:

* Manually add the user's email to their profile on AD server.

![image](https://github.com/user-attachments/assets/6f27e875-f89f-4fff-a86b-681e7e752d21)

* In the LDAP Email field of LDAP/AD Settings add the value: **mail**

![image](https://github.com/user-attachments/assets/875389ed-4317-4837-ad11-c3d051b086af)
