### ISSUE TITLE
Bug：Can not bulk transfer some asset items from one user to another user directly by edit "check out to" field.

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#14960]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

when need to bulk transfer some asset items from one user to another user.
how to directly by edit "check out to" field ?

### Reproduction steps

1. can not edit "check out to" field
2. 
3.
...

### Expected behavior

edit "check out to" field
bulk transfer button

### Snipe-IT Version

v7.0.5 build 14092 (g294fb1f77) 

### Operating System

Windows

### Web Server

mysql

### PHP Version

8.1.25

### Operating System

windows

**Comment by snipe** [comment]
@huifei0129 - this is not a bug, this is a feature request, and you've already asked for it in 3 other tickets. Please stop opening duplicate issues here.
