### ISSUE TITLE
User permission error

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#14961]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have one group company which includes 10 sub-companies
Each sub-company has different departments.
eg: 
group company: C
sub-company: C1,C2,C3,C4.....
department of company C1: C1-HR, C1-IT, C1-FA
the user in IT department of company C1：C1-IT-user1

how to set the "C1-IT-user1" permission below ?

1、only view his own assets——Done 
just deny all permission

2、only view and edit his own assets——Wrong 
(1) when view is granted, will view **all the essets** of the sub-company C1.
(2) when both view and edit are granted, will view and edit **all the essets** of the sub-company C1.

3、only view and edit all his department‘s assets——Department asset manager?

4、only view and edit all his sub-company‘s assets——Sub-company C1 asset manager?

5、view and edit group company asset data (Global: Super User)

### Reproduction steps

1.
2.
3.
...
User permission error

### Expected behavior

User permission error

### Snipe-IT Version

v7.0.5 build 14092 (g294fb1f77) 

### Operating System

Windows

### Web Server

mysql

### PHP Version

8.1.25

**Comment by snipe** [comment]
Snipe-IT doesn't really support sub-companies, so I'm not exactly sure what the question is.

**Comment by huifei0129** [comment]
when both view and edit are granted, user will view and edit **all the essets**.
but actually only the manager can have this permission,
and the end-user can view and edit **his own assets**, not include other user’s assets.

![edit](https://github.com/snipe/snipe-it/assets/156650496/80ab4d63-cca8-4525-85b2-67ee7d78d504)
![user see his own](https://github.com/snipe/snipe-it/assets/156650496/20c70863-6ea9-4a25-9414-908c38f82b76)

**Comment by snipe** [comment]
With full multiple company support, users are only allowed to access (with whatever permissions you give them) the assets, etc that belong to the company they are assigned to. We don't have a concept of sub-companies, nor managers (at least in the way I think you mean).

**Comment by huifei0129** [comment]
Sorry to disturb you again.

Usually we should limit the user only view his own assets (the assets assigned to the user), not include other user‘s assets.

But when give the "View" permission, why the user can see all the assets?

Thank you very much
