### ISSUE TITLE
[Feature Request]: Prevent assigning CREATE/EDIT (and other) permissions if a user or group doesn't have VIEW permission

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#14969]
### Is your feature request related to a problem? Please describe.

Currently, you are allowed to give other permissions to user/group without giving them VIEW right. Such user can't access hardware list directly, but can access it through other links.

### Describe the solution you'd like

VIEW permission should be mandatory if any other permission is given to that group/user.

Elegant way: clicking on radio button for (EDIT, CREATE, etc.) automatically marks VIEW radio button.
Not so elegant: system does a check when pressing SAVE and gives an error message, like "You cannot give EDIT permission without giving VIEW permission first."

**Comment by snipe** [comment]
This feels more like an administrative control to me. I can definitely see use-cases where automations are meant to have only the permissions they need, and viewing isn't necessary.
