### ISSUE TITLE
Missing translation (hardcoded text)

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#14968]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Text in **403 Forbidden.** message is hardcoded and can't be translated to other languages. While SAD PANDA may have sentimental value, it should go back to bamboo grove. SnipeIT went long path and at this stage it looks childish and unprofessional. (Same goes for message texts with smiley faces from Nokia 3310 era)

**file:** \resources\views\errors\403.blade.php

              <h2><i class="fas fa-exclamation-triangle text-yellow"></i> 403 Forbidden.</h2>
              <p>
                Sad panda. You are not authorized to do the thing. Maybe <a href="{{ config('app.url') }}">return to the dashboard</a>, or contact your administrator.
              </p>
![image](https://github.com/snipe/snipe-it/assets/3755203/b99cec17-176d-4587-beb2-ed58dec21150)

### Reproduction steps

1. Make a user account without View Assets permission.
2. Try to access _https://snipeit.install/hardware_.
3.Get a **403 Forbidden.** error message.

### Expected behavior

1. Text should be in users language, not hardcoded.
2. There should be no sad panda or any mention of it.

### Snipe-IT Version

All

### Operating System

n/a

### Web Server

n/a

### PHP Version

n/a

**Comment by snipe** [comment]
Thanks for the unsolicited feedback. God forbid anyone have any joy in this industry. We'll get the translation string fixed, but the sad panda shall remain.
