### ISSUE TITLE
Notifications issues

### ISSUE THREAD

**Issue by shinduke** [grokability/snipe-it#14975]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Notification Mail is not looking like it should
![image](https://github.com/snipe/snipe-it/assets/36949743/3268cf65-d939-49af-aa8b-64b3bf33db57)

Can someone reproduce this?

### Reproduction steps

1. php artisan snipeit:inventory-alerts

### Expected behavior

This is how it should look like
![image](https://github.com/snipe/snipe-it/assets/36949743/f4c1bc82-055e-423a-9f5f-4a8d064a2aa0)

### Snipe-IT Version

v7.0.5 - build 14092 

### Operating System

Windoes

### Web Server

IIS

### PHP Version

8.1.2

### Browser

Chrome, Edge

**Comment by snipe** [comment]
Can you update to latest? We just handled some translation issues.

**Comment by shinduke** [comment]
Ahhh...i will do

**Comment by snipe** [comment]
Also, if this doesn't solve your issue, can you let me know what language you have set in your .env and in your Admin Settings > Localization, so we can try to reproduce?

**Comment by shinduke** [comment]
Updated to this version v7.0.6 - build 14112....issue still there

Default Language in the localisation settings is English

**Comment by snipe** [comment]
Damn, okay, I’ll check into this for you. (What’s weirder is that we haven’t touched those emails in ages.) We’ll get to the bottom of it tho.

**Comment by snipe** [comment]
Hm, I'm not able to reproduce this locally.

<img width="687" alt="Screenshot 2024-06-26 at 2 43 48 PM" src="https://github.com/snipe/snipe-it/assets/197404/17cc8149-491a-44cb-ab4d-3d0ffa89176c">

**Comment by snipe** [comment]
Are you using American English or British English?

**Comment by snipe** [comment]
Also do you have a fallback locale set in your env?

**Comment by shinduke** [comment]
This is from the env file
APP_LOCALE=en
And this in the settings
![image](https://github.com/snipe/snipe-it/assets/36949743/afe95715-6bef-4353-a66d-bc1293f0b816)

I haven´t any fallback setting set or changed beside the change of the verions anythis here

**Comment by snipe** [comment]
If you change that APP_LOCALE to en-US, does that change anything?

**Comment by shinduke** [comment]
Perfect, that has done the trick. Thank you for your fast support
![image](https://github.com/snipe/snipe-it/assets/36949743/cca7162c-83c0-419a-b58a-76831fbb186c)

Can be closed
