### ISSUE TITLE
No records appearing in any list

### ISSUE THREAD

**Issue by hussamdabit** [grokability/snipe-it#14970]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have attempted both upgrading my existing docker deployment and I've deployed a new standalone installation on a new server. Ubuntu 22.04 and I experience the same issue.

 When I add items, nothing appears in the list. If I attempt to add the item in again it advises the name is already taken. This happens for every page.

I do run it snipe-it behind NPM but I also experience this issue direct to the IP

### Reproduction steps

N/A
Just happens

### Expected behavior

When adding an item, it appears in the list

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/17605337/5c331583-bb35-4106-954d-24115ad1ea85)
![image](https://github.com/snipe/snipe-it/assets/17605337/46e9405e-8a97-4ca2-b28a-d05a3c81d657)
![image](https://github.com/snipe/snipe-it/assets/17605337/688cd450-747c-4770-8c22-84d96be55178)

### Snipe-IT Version

7.0.5

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.2.20

### Operating System

Windows 11

### Browser

Chrome, Edge, Firefox

**Comment by snipe** [comment]
What's in your browser console and your app logs?

**Comment by snipe** [comment]
Any update?

**Comment by hussamdabit** [comment]
Sorry for the delay, been a little busy
[laravel.log](https://github.com/user-attachments/files/16103291/laravel.log)
[snipe-it-1720133780767.log](https://github.com/user-attachments/files/16103293/snipe-it-1720133780767.log)

**Comment by snipe** [comment]
```
[2024-07-04 22:55:22] production.ERROR: Carbon\Exceptions\InvalidTimeZoneException: Unknown or bad timezone (AU/Sydney) in /var/www/html/snipeit/vendor/nesbot/carbon/src/Carbon/CarbonTimeZone.php:109
```

Please update your .env for a [compatible timezone format](https://www.php.net/manual/en/timezones.australia.php), like `Australia/Sydney` for you.
