### ISSUE TITLE
[Feature Request]: Remove "Edit Your Profile" button

### ISSUE THREAD

**Issue by designatedsuccessor** [grokability/snipe-it#14993]
### Is your feature request related to a problem? Please describe.

Recently, a feature was added to prohibit users from editing their user profile.  However, the "Edit Your Profile" button still exists, so users are able to click it.  When they do, they get a 403 error.

So yes, users cannot technically edit their profile, but this is a terrible user experience.  I almost hope this is a bug because it's hard to believe it was intentionally implemented this way.

### Describe the solution you'd like

Remove the "Edit Your Profile" button.

**Comment by marcusmoore** [comment]
Thanks for reporting @loosus. This is fixed in #14999.

I'm going to close this as completed now but the fix will actually be included in the next release (unless you're tracking the develop branch).
