### ISSUE TITLE
[Feature Request]: User reporting the issue with the asset Internal helpdesk ticketing 

### ISSUE THREAD

**Issue by padaki04** [grokability/snipe-it#15013]
### Is your feature request related to a problem? Please describe.

Can we implement the helpdesk ticketing system in this portal so we can have the entire system in one place? It will be helpful for all the admins

If they are facing any issue with the Asset like laptop or something they can raise the ticket to the admin

### Describe the solution you'd like

Can we implement the helpdesk ticketing system in this portal so we can have the entire system in one place? It will be helpful for all the admins

**Comment by snipe** [comment]
You can use the API to integrate it into your existing helpdesk software right now, but we do not have a separate helpdesk integrated, though it has been requested before. Follow #663 for any updates on that front.
