### ISSUE TITLE
[Feature Request]: Ability to disable profile pics

### ISSUE THREAD

**Issue by designatedsuccessor** [grokability/snipe-it#15015]
### Is your feature request related to a problem? Please describe.

SCIM does not currently support provisioning user profile pics from an IdP, so we have no use for profile images.  So every user profile has a smiley-face image for no reason.

### Describe the solution you'd like

The ability for admins to completely disable profile pictures.  That would eliminate the default smiley-face image, like this one:
![image](https://github.com/snipe/snipe-it/assets/25268183/735045fc-a056-4cfc-9228-dabdd64f09e7)
Right now, the image just taking up space for no reason in our environment.

It appears to also be beside the user's name in the upper-right corner.

**Comment by snipe** [comment]
I don't really see why we'd need to do that though. They're just smiley faces. What harm do they cause? The amount of code changes we'd have to make for this doesn't really seem worth it to me.

**Comment by designatedsuccessor** [comment]
> I don't really see why we'd need to do that though. They're just smiley faces. What harm do they cause? The amount of code changes we'd have to make for this doesn't really seem worth it to me.

It's just weird and users ask why there is a smiling face pic in their profile (they don't understand that it is a profile pic).

If you want to reduce code complexity, rip out all the profile image code for all I care.  I think it adds little value for the majority of organizations and raises unnecessary questions in other orgs.

Another option: add a CSS class attribute to all profile pics, and then orgs can use custom CSS to do a `{ display : none; }` on them.

**Comment by snipe** [comment]
> rip out all the profile image code for all I care. I think it adds little value for the majority of organizations and raises unnecessary questions in other orgs.

That's definitely not true, based on my experience running this project for 11+ years.

It's not just you we have to care about here.

**Comment by designatedsuccessor** [comment]
> > rip out all the profile image code for all I care. I think it adds little value for the majority of organizations and raises unnecessary questions in other orgs.
> 
> That's definitely not true, based on my experience running this project for 11+ years.
> 
> It's not just you we have to care about here.

Right.  In any case, if the profile elements can get a unique class attribute added, we can remove them via CSS while the folks you think use it can happily continue doing so.
