### ISSUE TITLE
Custom field columns do not display data

### ISSUE THREAD

**Issue by mendoza69** [grokability/snipe-it#15020]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

after importing the data from csv and adding columns in costum fields, the columns seem to hold this data, but the data is not displayed. when exporting, all data is saved

### Reproduction steps

1.import data
2.add costum fields
3.costum columns do not display data
...

### Expected behavior

Import -> i can see the data in the asset table

### Snipe-IT Version

newest

### Operating System

ubuntu 22.04

### Web Server

costum

### PHP Version

8.1

**Comment by snipe** [comment]
You'll need to make sure the custom fields are in a custom fieldset, and then make sure the models are associated with that fieldset. https://snipe-it.readme.io/docs/custom-fields

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/custom-fields">Custom Fields</a></strong></div><div>Custom fields and fieldsets are available in Snipe-IT versions 2.1.0-pre and later. Custom fields allow you to track additional information about your assets that the default asset attributes don't cover. Check out the short video tutorial below for a full walkthrough: Snipe-IT Turbo Tutorial: Custo...</div></blockquote>

**Comment by swift2512** [comment]
@snipe it would be nice to have model import feature. I have a set of data, containing 4000 lines, for import. I had to do import of same data twice. First time - to create models and assets in the database. Then, manually assigned fieldsets to models and ran import for the second time, to fill data in custom fields. **There should be at least a mention that custom fields won't be populated if model has no fieldset assigned.**

**Comment by snipe** [comment]
@swift2512 we do have that documented: https://snipe-it.readme.io/docs/importing#importing-custom-fields

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing#importing-custom-fields">Importing Assets and More</a></strong></div><div>There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...</div></blockquote>

**Comment by swift2512** [comment]
@snipe not everyone has access to server and can use artisan... :) Everything is OK with Importer - I can import 4000 lines (filesize -  1,3MB) without any problems. Main problem is **nobody reads documentation** (including myself). While Importer allows to map fields with different names, it doesn't mention anywhere that these mismatched fields will be skipped.
Theres' only one message on Import page and it says:
```
You can import assets, accessories, licenses, components, consumables, and users via CSV file.
The CSV should be comma-delimited and formatted with headers that match the ones in the [sample CSVs in the documentation](https://snipe-it.readme.io/docs/importing).
```
Why not add something like this to the end of this message: 
`Also, the names of the custom fields must exactly match the names of the fields already in the system, otherwise they will be skipped.`
(I am not native speaker, so this sentence needs some attention.)

**Comment by snipe** [comment]
It does tho.. from that link...

<img width="827" alt="Screenshot 2024-07-05 at 8 31 32 AM" src="https://github.com/snipe/snipe-it/assets/197404/720794ee-935b-415d-9576-16d28c7e3062">

**Comment by swift2512** [comment]
But you have to click a link... Nobody does that. :)
Why not put that info directly on the page? :) It's just a few lines of text and it doesn't break anything.

**Comment by snipe** [comment]
Because it's more complicated than it seems. The importer is enormously complicated.
