### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Steve-M-C** [grokability/snipe-it#15026]
### Is your feature request related to a problem? Please describe.

Make it easier to filter emails that are sent from Snipe, based on the subject line of the messages.

### Describe the solution you'd like

The ability to set an (optional) custom string that will be pre-pended to the subject line of all emails sent from Snipe - for example "[Snipe-IT]".

### Describe alternatives you've considered

Trying to filter based on the existing subject lines requires quite a lot of rules to be setup.

**Comment by snipe** [comment]
Wouldn't you be able to handle that via FROM or other things? For example, if you were Company XYZ, you can set your MAIL_FROM_NAME to `Company XYZ Asset Management`.

**Comment by Steve-M-C** [comment]
That's true - I'll go with that, thanks!
