### ISSUE TITLE
[Request]: Add some pics or mini video or gif from demo in main github page so that people can have better idea of UI easily 

### ISSUE THREAD

**Issue by Greatz08** [grokability/snipe-it#15028]
### Is your feature request related to a problem? Please describe.

I know there is dedicated demo but putting some ui images in main github page make things much easier for people who wanna have rough idea of what ui would look like rather than going to demo website and doing sign in process and then get the idea about it. I had experienced similar solution so wanted to get the ui view and couldnt find so had to go through process which i didnt want to to be honest so my request is to add some good ui pics of demo so that without even doing the whole process people can have rough idea of ui and some of its component. Or you can put mini video of gif which autoplays and showcase this project in fast forward way this is also something i have seen in many great projects. 

### Describe the solution you'd like

:-)

**Comment by snipe** [comment]
We have multiple slideshows here: https://snipeitapp.com/product. We don't feel it would be appropriate for us to bulk up the code repo with demo videos.

<blockquote><img src="https://snipeitapp.com/img/desktop_snipe.png" width="48" align="right"><div><strong><a href="https://snipeitapp.com/product">Product Features - Snipe-IT Open Source IT Asset Management</a></strong></div><div>Snipe-IT is a free, open source IT asset management system that helps you manage assets, software licenses, accessories, components and consumables within your organization.</div></blockquote>
