### ISSUE TITLE
[Feature Request]: Status List colors to match status colors (not Status Type colors)

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#15038]
### Is your feature request related to a problem? Please describe.

Currently its a bit confusing when going to a status of an item and seeing the color of the "Status Type" and not "Status"
Status on list all should reflect the "Status" color and not the "Status Type" color
![Screenshot 2024-07-08 103915](https://github.com/snipe/snipe-it/assets/114973646/a301c9ce-4716-450c-8031-cd1289e79a28)

### Describe the solution you'd like

Should be the same color as the status eg.
![Screenshot 2024-07-08 105428](https://github.com/snipe/snipe-it/assets/114973646/2ae92698-60c1-4fce-a490-e5284d66a80a)
and
![Screenshot 2024-07-03 160753](https://github.com/snipe/snipe-it/assets/114973646/51ea4a45-ac25-40a4-8152-8f9088c69648)
and not "Status Type" Colors in list
![Screenshot 2024-07-08 103915](https://github.com/snipe/snipe-it/assets/114973646/344ff30a-bf3c-416b-be86-940a4ac30ef9)

**Comment by snipe** [comment]
In the list view, we use our own colors to denote whether something is deployable, archived, etc. The status colors are only meant as a guide for the sidebar.
