### ISSUE TITLE
All Custom Fields empty after audit 

### ISSUE THREAD

**Issue by othiel1984** [grokability/snipe-it#15037]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Customfields get deleted after an asset is audited. 

### Reproduction steps

1. create asset 
2. fill out custom fields
3. audit asset 
...

### Expected behavior

values of customfields persist after audit

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/174957481/9a39794d-beb0-4060-8652-d87f4f12a6d0)

![image](https://github.com/snipe/snipe-it/assets/174957481/93194d61-23cf-4869-8236-7804d1904cad)

Result 

![image](https://github.com/snipe/snipe-it/assets/174957481/b34c16ef-4758-419c-a245-6fc7d051a2be)

### Snipe-IT Version

7.0.7 

### Operating System

Official Docker Image Debian  

### Web Server

Apache

### PHP Version

 v8.1.2-1

### Operating System

Windows

### Browser

Chrome 

### Version

126.0.6478.127

**Comment by othiel1984** [comment]
Downgrade to Version 7.0.6 works.

**Comment by snipe** [comment]
This is now fixed on master - thanks for the heads up!
