### ISSUE TITLE
[Feature Request]: Add category ID to API docs when creating license

### ISSUE THREAD

**Issue by pieterhouwen** [grokability/snipe-it#15034]
### Is your feature request related to a problem? Please describe.

On the page https://snipe-it.readme.io/reference/testinput you can use the query builder to create a new license, in the Body Params table however there is no way to add the required category ID for the license.

### Describe the solution you'd like

Add category_id to the Body Params table and set it as a required field.

**Comment by snipe** [comment]
Done, thanks for the heads up!
