### ISSUE TITLE
Missing default.png avatar after upgrade from 6.4.1 to 7.0.8

### ISSUE THREAD

**Issue by seederp2p** [grokability/snipe-it#15048]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After the upgrade the default avatar is not loaded.

It points to /uploads/avatars/default.png

Before it pointed to:

https://gravatar.com/avatar/2e828e79c65296b90816c6a903ebbe02

My users are LDAP integrated...

My local /public/img/ has no images...

### Reproduction steps

Upgrade from 6.4.1 to  7.0.8 and you'll have a missing avatar.

### Expected behavior

It should have a default avatar

### Snipe-IT Version

7.0.8 

### Operating System

Ubuntu Server 

### Web Server

Apache2

### PHP Version

8.1.29

**Comment by Glukose1** [comment]
I can confirm that I noticed the missing Avatar too.

**Comment by snipe** [comment]
![default-sm](https://github.com/snipe/snipe-it/assets/197404/e4eb510a-3307-49ab-8389-43ceac8fc27f)

Here you go

**Comment by snipe** [comment]
Fixed on master - thanks for the heads up!

**Comment by setpill** [comment]
This doesn't work if you use a docker container; as per the snipeit docs, the data dir is on a volume and will therefore not receive this avatar.

**Comment by fama** [comment]
I have the same problem.  Running snipeit inside a docker container starting with v6.4.2-alpine upgrade to v7.0.12-alpine.  Uploading the [default.png](https://github.com/snipe/snipe-it/blob/master/public/uploads/default.png) to snipeit/data/uploads fixed the problem.
