### ISSUE TITLE
Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm.

### ISSUE THREAD

**Issue by SealinGp** [grokability/snipe-it#15040]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

It happens When I Install In Docker

### Reproduction steps

1. `docker pull snipe/snipe-it`
2. create env file in `/volume1/docker/snipe-it/env/.env` follow https://snipe-it.readme.io/docs/docker config
3. `docker run --rm snipe/snipe-it` and fill it in `/volume1/docker/snipe-it/env/.env` file env key 'APP_KEY'
4. `docker run -d -p 8010:80 --name="snipeit" --env-file=/volume1/docker/snipe-it/env/.env --mount source=snipe-vol,dst=/var/lib/snipeit --network share snipe/snipe-it`
5. access $APP_URL use chrome browser
6. it redirect to $APP_URL/setup and display blow errors:
'Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm.'
<img width="1752" alt="image" src="https://github.com/snipe/snipe-it/assets/32982627/84a2fcbe-b660-4ff7-b8fa-6502ae231c91">

### Expected behavior

can normally access APP_URL 

### Screenshots

<img width="1780" alt="image" src="https://github.com/snipe/snipe-it/assets/32982627/9f71425d-0f21-4701-8744-ea1b9f8909d3">

### Snipe-IT Version

snipe/snipe-it:latest

### Operating System

ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

**Comment by SealinGp** [comment]
if key generated as "base64:xxx", i must copy "base64:xxx" as value to .env file instead of "xxx"

**Comment by Reftek85** [comment]
> if key generated as "base64:xxx", i must copy "base64:xxx" as value to .env file instead of "xxx"

wow Thank you! I tried a lot of things to get me going but this was the issue I was facing
