### ISSUE TITLE
Can't download EULA PDFs

### ISSUE THREAD

**Issue by LegendEronZ** [grokability/snipe-it#15058]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Upon trying to download EULA PDFs from assets site throws 500 server error.

### Reproduction steps

1. Enable signing off assets 
2. Assign asset to user
3. Sign asset as user
4. Download EULA pdf from asset

### Expected behavior

PDF should be downloaded from private uploads

### Snipe-IT Version

v7.0.8 build 14243 (g2e2f59b29)

### Operating System

Alpine

### Web Server

Apache

### PHP Version

8.1.27

### Error messages

```shell
App\Http\Controllers\ActionlogController::getStoredEula(): Return value must be of type Illuminate\Http\Response, Symfony\Component\HttpFoundation\BinaryFileResponse returned

Error is reproducable on the demo with the mentioned steps

Stack:
https://flareapp.io/share/Bm0OB605
```

### Additional context

I've tried the same in production and in fresh docker setup and same behavior

**Comment by LegendEronZ** [comment]
Adding Symfony\Component\HttpFoundation\BinaryFileResponse in app/Http/Controllers/ActionlogController.php and changing the return type of getStoredEula() to BinaryFileResponse solves the issue but I'm not sure if that is the intended return type

**Comment by snipe** [comment]
I think we already fixed this? 

https://github.com/snipe/snipe-it/blob/18f7ca860ddfea8d9ca145e3c10f64a0b7e65fb1/app/Http/Controllers/ActionlogController.php#L40-L46

**Comment by LegendEronZ** [comment]
Yes that commit fixed the issue, thanks!

**Comment by snipe** [comment]
Great, glad to hear it - and sorry for the inconvenience!
