### ISSUE TITLE
View License Page - Supplier showing errant "Deleted" text

### ISSUE THREAD

**Issue by abakerwwsb** [grokability/snipe-it#15050]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Commit 77dacfc introduced a bug that just shows the text "Deleted" on the License view page if there is no supplier. 

### Reproduction steps

1. Create new license without a Supplier
2. View the license info page
3. See the "Deleted text" under **Licensed to Name**
![image](https://github.com/snipe/snipe-it/assets/64664839/cc424968-6d8e-4799-9c61-40df5da39524)

### Expected behavior

Unsure of styling, either the entire line goes away, or the title of "Supplier" should be shown, and the deleted text goes to the right column.

### Snipe-IT Version

7.0.7+ (tested on demo site as well)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2

**Comment by snipe** [comment]
That commit doesn't seem to suggest that. Let me look into this.

**Comment by snipe** [comment]
Fixed on master - thanks for the heads up!
