### ISSUE TITLE
Asset View - Checked Out To 

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#15056]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When viewing who an asset is assigned to, there appears to be an "extra" image being attempted to be imported from:

http://SnipeITInstallation/uploads/avatars/default.png

Although, a profile picture already appears next to the user's name. This is being displayed as a picture placeholder and the user's name appearing misaligned with the remaining text.

![issue](https://github.com/snipe/snipe-it/assets/31219479/6b1efe7c-92af-4133-bc54-7a3bdabbd0f9)

Also, if when you manually assign a user a picture; in place of the default image. If you then delete the file from: http://SnipeITInstallation/uploads/avatars/userprofilepicture.png

It should default back to a default image. It should not only show a placeholder because the link was broken.

### Reproduction steps

1. View the Asset View for an item.
2.
3.
...

### Expected behavior

Icons / Text should align.
A placeholder should not appear.

### Snipe-IT Version

7.0.8

### Operating System

Server 2022

### Web Server

WAMP

### PHP Version

8.2.5

**Comment by snipe** [comment]
I apologize, I'm not exactly sure what you're describing here and I can't seem to reproduce this locally. Can you explain a little further? Do you have "Load remote avatars" checked or unchecked in your Branding settings?

<img width="459" alt="Screenshot 2024-07-10 at 8 45 11 AM" src="https://github.com/snipe/snipe-it/assets/197404/b1cd4000-ba01-43ad-99c1-0f29c5fa2c1e">

**Comment by snipe** [comment]
I think I got it :) Thanks for the heads up!
