### ISSUE TITLE
Logos do not show up in lablels.

### ISSUE THREAD

**Issue by ihrigb** [grokability/snipe-it#15053]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have a logo configured for the labels, but it does not show up, whatever I do.

### Reproduction steps

1. Configure a logo in Admin/Branding
2. In Admin/Labels pick any label that supports logos.
3. Logo does not show up.

### Expected behavior

Logo should be visible on the label.

### Snipe-IT Version

v6.4.2

### Operating System

Docker

### Web Server

Docker

### PHP Version

Docker

### Operating System

Windows

### Browser

Chrome

### Version

126.0.6478.127

### Error messages

```shell
noting, not reproducible in demo, as feature is turned off.
```

### Additional context

fresh install

**Comment by Godmartinz** [comment]
Hi @ihrigb,

I'm not able to replicate this issue on version 7.0.8
<img width="775" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/ed6afc47-2970-4cbf-972c-8e35a20d52ad">

What file type is your image?
What size is the image?

**Comment by ihrigb** [comment]
Hi @Godmartinz,

first things first: I updated to 7.0.8. The file type is SVG. I would like to have a 2D (QR) Code and the Logo in the label. I do not need the 1D barcode.

Thanks

**Comment by Godmartinz** [comment]
I recommend trying a png or jpeg, sometimes svg format can be finicky.

As for the layout you would like, sounds like the default layout with the 1d barcode set to none would suit your needs if you don't have the brother label printer.

**Comment by ihrigb** [comment]
I switched to a PNG and it works. Default Layout is fine for me, I will adjust it to my sheets. Thanks for your help!
