### ISSUE TITLE
LDAP import - Wrong default user language

### ISSUE THREAD

**Issue by ug-s-jz** [grokability/snipe-it#15067]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

I am using the current Snipe-IT version v7.0.8 and I have noticed something with a new user.

The user has received English emails, although the default language in the .env file and in the settings is set to German (de-DE).

If I then synchronise the users via LDAP and a new user is created, the user language is set to "English, USA".

I would have expected the user to be automatically assigned the default language.

### Reproduction steps

1. Set .env and system default language to german (de-DE)
2. Sync new user with LDAP 
3. check the user language, language is English, USA

### Expected behavior

User should have the default language as user language

### Snipe-IT Version

v7.0.8 - build 14243 (master)

### Operating System

Ubuntu 22.04.4 LTS

### Web Server

Apache

### PHP Version

8.2.20

**Comment by 6wensitan** [comment]
You can try to back up a copy of the EN folder and de-DE folder in the Lang folder Lang folder, delete the EN original folder, and then modify the name of the de-DE copy folder into EN. (Note the name here).

**Comment by snipe** [comment]
@6wensitan I would definitely not move language files around, as you'd have a bad time while upgrading.

**Comment by snipe** [comment]
I have a potential fix (needs testing on Monday) for this here: https://github.com/snipe/snipe-it/pull/15084

**Comment by snipe** [comment]
This fix is now out on master. If you run the upgrader, can you let me know if it resolves your issue.  (Per the PR, it won't update existing users, since those could have been manually changed to something else and we have no way of knowing that.)
