### ISSUE TITLE
Dashboard broken after recent upgrade

### ISSUE THREAD

**Issue by BasO12** [grokability/snipe-it#15063]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After the most recent upgrade, our dashboard has started to look like a website made in the 2000's:
![image](https://github.com/snipe/snipe-it/assets/94169344/44f9a07e-e7e5-41c5-9146-ddca76894175)

The upgrade was succesfully completed without error. we can still access other pages by using different URLS and these all look normal (we can even see by the version number that the upgrade was succesful). Debug mode still seems to work:
![image](https://github.com/snipe/snipe-it/assets/94169344/ccb8bc36-3334-49bd-a45c-42839bb6574d)

Any tips would be much appreciated.

### Reproduction steps

Ruin the dashboard by upgrading?

### Expected behavior

The dashboard should load with it's graphical elements.

### Snipe-IT Version

7.0.8

### Operating System

Debian 12

### Web Server

Apache2

### PHP Version

8.3.9

### Operating System

Windows 10

### Browser

Chrome and Edge

### Version

Chrome: 126.0.6478.127 and Edge: 126.0.2592.87

**Comment by snipe** [comment]
Did you actually do the thing the debugbar is telling you to do though?

**Comment by snipe** [comment]
Also, if you're seeing PHP in the dashboard, this is not a Snipe-IT level issue, this is the web server not knowing to parse PHP pages as PHP, which is always a web server configuration problem. Please check your Windows server configs and make sure PHP is running properly.

**Comment by BasO12** [comment]
Yes, but it did not help.

**Comment by snipe** [comment]
That you can access other urls within the system is a bit unusual - feels like maybe somebody on your end added a rule that prevents your Apache from parsing the dashboard as PHP. The demo runs off of master, and it clearly works, so I'd bet there's some weird rule within your apache configs that is overriding the PHP directives.

**Comment by BasO12** [comment]
I am currently checking the config and I'll get back on that. I do see this happening in the chrome console:
![image](https://github.com/snipe/snipe-it/assets/94169344/badc0793-4100-4e0b-a345-b010b6ee0ae6)

**Comment by BasO12** [comment]
I have no idea what really was the cause. Upon removing dashboard.blade.php and running upgrade.php, everything has returned back to normal. Thanks for the assistance.
