### ISSUE TITLE
Wrong field during checkout

### ISSUE THREAD

**Issue by Desmond-Kalvin** [grokability/snipe-it#15094]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The company name was displayed twice in the checkout window instead of the model field.

### Reproduction steps

Nil

### Expected behavior

It should show as Model

### Screenshots

![image](https://github.com/user-attachments/assets/25a84fc4-fcc3-41a9-950b-9b60c9e4ac2f)

### Snipe-IT Version

7.0.9

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.2

### Operating System

Windows

### Browser

Microsoft Edge

### Version

126.0.2592.102

**Comment by snipe** [comment]
Thanks for the heads up! This is fixed on `master` and `develop` now :)
