### ISSUE TITLE
404 when selecting Fieldset on "Update Asset Model" page after upgrading 6.3.0 -> 7.0.9

### ISSUE THREAD

**Issue by tconvery** [grokability/snipe-it#15108]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgrading 6.3.0 -> 7.0.9 using upgrade.php, when editing an asset model ("Update Asset Model" page) and selecting a Fieldset for the Asset Model, a 404 page is displayed. In my httpd access.log, I see 404s for "POST /livewire/update HTTP/1.1" referred from models/501/edit (which is the model I'm trying to edit).

Host OS is Ubuntu 22.04.4 running Apache 2.4.52.

I could not reproduce this error on the demo.

### Reproduction steps

1. Browse to an asset model.
2. Click "Edit Model" button
3. Select the "Fieldset" dropdown.
4. Clicking a fieldset name or "No custom fields" results in a 404 screen in the browser.

### Expected behavior

Clicking a fieldset name (in step 4 above) should result in that fieldset being assigned to the asset model, without a 404.

### Snipe-IT Version

7.0.9

### Operating System

Ubuntu 22.04.4

### Web Server

Apache 2.4.52

### PHP Version

8.1.2

**Comment by snipe** [comment]
I think this fix might be what you need: https://github.com/snipe/snipe-it/pull/15073 - can you update to the latest from master and let me know if that resolves your issue?

**Comment by smithrwh** [comment]
I am having the same issue after upgrading to 7.0.9 im on windows IIS. I also get this error when trying to import assets usign the GUI. CLI imports work fine so it appears to have something to do with the route for the Livewire/Update path.

**Comment by snipe** [comment]
@smithrwh see my comment above

**Comment by tconvery** [comment]
> I think this fix might be what you need: #15073 - can you update to the latest from master and let me know if that resolves your issue?

That did it, thanks!

I am running out of https://myhost/snipeit so also had to set "LIVEWIRE_URL_PREFIX=/snipeit" in .env.

**Comment by smithrwh** [comment]
> @smithrwh see my comment above

Marvelous that resolved both issues.
