### ISSUE TITLE
Wrong display（Checkout Asset display detail）

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#15119]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Checkout Asset display detail has some error
The "model name" and "company" confuse

### Reproduction steps

1.Checkout Asset
2.
3.
...

### Expected behavior

modify

### Screenshots

![image](https://github.com/user-attachments/assets/ff2951dc-7c97-4906-ab6d-12b5cd0af163)

### Snipe-IT Version

 Version v7.0.9 - build 14371 (master)

### Operating System

Ubuntu, Windows

### Web Server

Apache

### PHP Version

8.1.25

### Operating System

windows

### Browser

google

**Comment by snipe** [comment]
This was already fixed in https://github.com/snipe/snipe-it/pull/15099
