### ISSUE TITLE
Bulk restore doesn't work

### ISSUE THREAD

**Issue by ravkraw** [grokability/snipe-it#15121]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to bulk restore assets, error "Selected assets cannot be updated" appears, but with single restore the problem does not occur.

### Reproduction steps

Try to use bulk restore assets function.

### Expected behavior

Assets should restore as with single function.

### Screenshots

https://github.com/user-attachments/assets/78d4a5b9-a6c3-4094-a5ee-6787753d7dba

### Snipe-IT Version

v7.0.9

### Operating System

SLES

### Web Server

Nginx

### PHP Version

8.1.28

### Additional context

I noticed the problem on my server, but I tested it on the https://demo.snipeitapp.com/ and exactly the same thing happens (the attached video was recorded on the demo)

**Comment by ravkraw** [comment]
Also the second problem - buk deletion does not logging in the activity log - as you can see in the video, I bulk deleted 2 assets, but this information was not logged (for example, the edit was)
![image](https://github.com/user-attachments/assets/f7c90fe7-7e5c-41ad-bf6b-917941b49a13)

**Comment by snipe** [comment]
Thanks for the video! This is fixed on `master` now.
