### ISSUE TITLE
The notes section for the assets is not displayed in the assets properties section

### ISSUE THREAD

**Issue by NickNck** [grokability/snipe-it#15135]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When asked for notes when checking out assets, the entered notes is not displayed at all when you look at the assets info recorded. But the notes shows up in the email alerts when checked out

### Reproduction steps

1. Check out asset
2. Enter notes when checking out asset
3. Go back to the asset info section and see that the notes is blank
...

### Expected behavior

I expect to see the entered notes in the assets info.

### Snipe-IT Version

7.0.9

### Operating System

Windows 10

### Web Server

WAMP

### PHP Version

8.1.27

**Comment by snipe** [comment]
Checkout notes are under the History tab. In the detail view of the asset, that's an asset note, not a checkout/checkin note.

**Comment by NickNck** [comment]
Hi Admin, thanks for the response! I would like to take the opportunity to also suggest that probably this could also be made clearer in the custom report section since it only says Notes. Would be helpful to indicate what kind of Note it is thats included in the report field (checkout note or an asset note). As a feature request, would be helpful if the checkout note can be included in the custom report and exported based on the criterias below:

Last checkout note
First checkout note
All checkout note

**Comment by snipe** [comment]
All checkout notes kinda doesn't make sense here, since one asset could have dozens of checkout notes, and that doesn't play very nicely in a CSV
