### ISSUE TITLE
User Import - Start and End Date Error

### ISSUE THREAD

**Issue by m00shie** [grokability/snipe-it#15141]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Invalid start and end dates appears when editing users after performing import of users into Snipe-IT. I have also tried imported users with empty start and end dates fields but the same issue occurs.

### Reproduction steps

1. Go to Import
2. Select CSV file to import
3. Click on Map Field
4. Select CSV import type as "Users"
5. Verify CSV Header Field and Import Field (Note: No start or end date field) - See screenshot#1
6. Click on Import
7. Go to "People" and locate user that was imported.
8. Click on "Edit" and view the start and end date which will display as "-0001-11-30" - See screenshot#2
...

### Expected behavior

Start and end date should be empty.

### Screenshots

**Screenshot#1**
![Import_Screenshot](https://github.com/user-attachments/assets/f0ee0426-5d78-4fc3-9471-8e1b56b07010)

**Screenshot#2**
![Edit_User](https://github.com/user-attachments/assets/85fa161d-5c12-4c92-be25-d79e8e23a6c6)

### Snipe-IT Version

v7.0.8 build 14243

### Operating System

Hosted by Snipe-IT

### Web Server

Hosted by Snipe-IT

### PHP Version

8.1.29

### Operating System

Windows 11

### Browser

Microsoft Edge

### Version

126.0.2592.113

### Error messages

```shell
Unable to enable debug mode as I'm subscribed to Snipe-IT hosted subscription. Unable to simulate in https://snipeitapp.com/demo as import is disabled.
```

**Comment by marcusmoore** [comment]
Thanks for reporting this @m00shie. I can confirm the issue exists on the develop branch as well as v7.0.8. I'll work on a fix.

**Comment by m00shie** [comment]
Thank you.

**Comment by snipe** [comment]
This is merged to master and will be in the next release.
