### ISSUE TITLE
User Login gets disabled with every sync

### ISSUE THREAD

**Issue by kuratlielia** [grokability/snipe-it#15159]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I sync the users the login is disabled by default because I set the active flag to false in the LDAP settings.
(I run this sync through a scheduled task every night)

For the admins that work in SnipeIT I want to activate the login for there admin accounts.
But now everytime the sync runs again the login gets disabled.

Is that a known issue and do you know any solution or workaround for that?

### Reproduction steps

1. Sync AD Users
2. Enable Login for admins
3. Sync again

### Expected behavior

The users where the login is enabled should stayed enabled.

### Snipe-IT Version

v6.3.1

### Operating System

Windows Server 2022

### Web Server

IIS

### PHP Version

8.1.2

**Comment by uberbrady** [comment]
Whatever you're putting in as your "LDAP Active Flag" you should probably blank out. It's going to look for _that_ attribute, and expect it to be "true" or "1" or "some text" or something along those lines to be able to be considered 'active'.

If you put something like the word 'false' it's going to look for an LDAP attribute called 'false' on your users (which I'm pretty sure you won't have), and, in not finding it, will assume your user(s) should be marked as inactive.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
