### ISSUE TITLE
Norwegian display language now has Chinese 'pagination-info'

### ISSUE THREAD

**Issue by zhyl0** [grokability/snipe-it#15157]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Changing display language  to Norwegian makes it so Chinese text appears at least on the pagination-info ("Showing 1 to 34 of  99 rows" line).

### Reproduction steps

1. Set display language to Norwegain.
2. Browse any page with rows listing contents allowing for amount of rows to be selected
3. Observe the Chinese text
...

### Expected behavior

The text is supposed to be in Norwegain, like it was before the summer.

### Screenshots

![image](https://github.com/user-attachments/assets/c86b9a5d-b25c-457f-8a30-e8c617da0c58)

### Snipe-IT Version

v7.0.9 build 14371 (g1a541ce22)

### Operating System

Synology Docker

### Web Server

Apache

### PHP Version

8.3.9

### Operating System

Windows

### Browser

Chromium

**Comment by snipe** [comment]
This was fixed in https://github.com/snipe/snipe-it/pull/15133
