### ISSUE TITLE
linking asset with current location instead of linking it with users

### ISSUE THREAD

**Issue by WaleedQ1** [grokability/snipe-it#15166]
### Is your feature request related to a problem? Please describe.

lets suppose the user have two offices in different locations, these locations need an asset . how to record its location if the location determined by the user not the asset.

### Describe the solution you'd like

I would like define location for a user in check out  if there is any change for that it will be updated or it will become as the same as the user profile, attached with text note.

**Comment by snipe** [comment]
You can use bulk edit to change the actual location. 
<img width="782" alt="Screenshot 2024-07-25 at 12 07 47 PM" src="https://github.com/user-attachments/assets/7902dbda-5e4d-4d29-9168-3ea9d23c99fa">
