### ISSUE TITLE
QR No longer shows on asset

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#15164]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

QR Code no longer shows on the asset anymore after latest update
![Screenshot 2024-07-25 111141](https://github.com/user-attachments/assets/cf39da79-110b-4aaf-99d6-d258f456aff4)

### Reproduction steps

1.go to any asset, No qr on the right side anymore (even when enabled)
2.
3.
...

### Expected behavior

QR should show on each asset

### Snipe-IT Version

 v7.0.9 build 14485 (ga98ad76c6) 

### Operating System

Almalinux

### Web Server

apache

### PHP Version

8.1.29

**Comment by snipe** [comment]
Fixed on master
