### ISSUE TITLE
Change of translation for license "maintained" in German from "Verwaltet" into "In Wartung" or something else

### ISSUE THREAD

**Issue by MindofCode** [grokability/snipe-it#15176]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The translation of attribute "maintained" for licenses as "Verwaltet" is misssleading.
Should be something like "In Wartung" or "Gewartet" or only "Wartung"

### Reproduction steps

See license .../licenses/create

Attribute "Verwaltet"

### Expected behavior

Better translation should be used.

### Snipe-IT Version

7.0.7

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.2

**Comment by snipe** [comment]
Hi there - you can propose that change in the translation platform we use: https://crowdin.com/project/snipe-it. If you prefer, you can tell us your CrowdIn name and we can make you a translator.

<blockquote><img src="https://crowdin-static.downloads.crowdin.com/images/project-logo/67597/small/3715dc5bf1a83beda1855c31a29fef96470.png" width="48" align="right"><div><img src="/favicon-16x16.png" height="14"> Crowdin</div><div><strong><a href="https://crowdin.com/project/snipe-it">Snipe-IT Asset Management — Translation Project on Crowdin</a></strong></div><div>Help us translate Snipe-IT Asset Management and bring it to the world!</div></blockquote>
