### ISSUE TITLE
LDAP Active Flag working opposite

### ISSUE THREAD

**Issue by dlangham547** [grokability/snipe-it#15174]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I set the 'LDAP Active Flag' to my correct attribute field and run a LDAP Sync all active accounts are set 'Login Enabled=No' and all disabled AD accounts are set to 'Login Enabled=Yes', this appears to be working opposite to what it should. I have confirmed I am using the correct AD attribute.

### Reproduction steps

1. Set LDAP/Active Directory field (LDAP Active Flag) to AD attribute
2. Run LDAP Sync
3. All active AD accounts are denied login to Snipe IT and all disabled AD accounts are allowed.

### Expected behavior

All active AD accounts to have access and all disabled AD accounts denied access.

### Snipe-IT Version

v6.4.1 - build 13386 (master)

### Operating System

Ubuntu Server 22.04.4 LTS

### Web Server

Apache

### PHP Version

8.1.29

### Operating System

Windows 10

### Browser

Microsoft Edge

### Version

Version 126.0.2592.102 (Official build) (64-bit)

**Comment by dlangham547** [comment]
Ok ignore me, I had the following included in my LDAP Filter to pull only active accounts and was obviously reversing the logic. I have taken it out and now all works as it should when leaving the LDAP Active Flag field blank!
**(!(userAccountControl:1.2.840.113556.1.4.803:=2))**

**Comment by snipe** [comment]
It sounds like you were all sorted - is there a reason this was re-opened?

**Comment by dlangham547** [comment]
> It sounds like you were all sorted - is there a reason this was re-opened?

No reason at all and apologies.
