### ISSUE TITLE
[Feature Request]:  How to hide or delete Snipeit native status labels

### ISSUE THREAD

**Issue by Vitalmeid** [grokability/snipe-it#15171]
### Is your feature request related to a problem? Please describe.

I would like to know if it´s possible to delete or hide snipeit native status label for example: Un-deployable, BYOD,Deployed,Archivev and requestable, This menus are not necessary for the view of my organization.

### Describe the solution you'd like

I like to know if it´s possible to hide or delete this fields as admin.

### Describe alternatives you've considered

Like to delete or hide this labels

**Comment by snipe** [comment]
They are not native, they are _classifications_ of status labels. They cannot be hidden through settings.
https://snipe-it.readme.io/docs/overview#status-labels

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/overview#status-labels">Overview</a></strong></div><div>When your Snipe-IT installation is first set up, it can be a little overwhelming to figure out where to get started. The first place to start is usually your Admin Settings. We go through each of the specific admin options one by one in the Admin Settings section of this documentation, but that's wh...</div></blockquote>

**Comment by Vitalmeid** [comment]
> They are not native, they are _classifications_ of status labels. They cannot be hidden through settings. https://snipe-it.readme.io/docs/overview#status-labels
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/f5ec2eb7e2274ad22d196821472e0438dcbd923f06ab2d8cbeb0ae2113c74df8/68747470733a2f2f736e6970652d69742e726561646d652e696f2f66617669636f6e2e69636f">Snipe-IT Documentation**[Overview](https://snipe-it.readme.io/docs/overview#status-labels)**When your Snipe-IT installation is first set up, it can be a little overwhelming to figure out where to get started. The first place to start is usually your Admin Settings. We go through each of the specific admin options one by one in the Admin Settings section of this documentation, but that's wh...

Understand that part but on my organization I created an new status label called " Repair" bit I still seeing laptops inside the field Un-deployable and I just want to use Repair and remove Un-deployable from my view inside assets. Is it possible?


<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/overview#status-labels">Overview</a></strong></div><div>When your Snipe-IT installation is first set up, it can be a little overwhelming to figure out where to get started. The first place to start is usually your Admin Settings. We go through each of the specific admin options one by one in the Admin Settings section of this documentation, but that's wh...</div></blockquote>

**Comment by snipe** [comment]
The meta status descriptions cannot be removed, as I mentioned, since they are not actual status labels. Your Repair label should still show up in the sidenav so you can jump right to it though.

**Comment by Vitalmeid** [comment]
> The meta status descriptions cannot be removed, as I mentioned, since they are not actual status labels. Your Repair label should still show up in the sidenav so you can jump right to it though.

Ohhhhhh, sorry for not being totally clear on my explation, my main issue is with meta status as all of my technicians are having some doubts about that.

**Comment by snipe** [comment]
I understand, but they cannot be removed from the sidenav at this point.

**Comment by Vitalmeid** [comment]
> I understand, but they cannot be removed from the sidenav at this point.

Thanks snipe for your quickly help!!!!!
