### ISSUE TITLE
BUG: Change status to "Archived" and "Repairing", no respond

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#15180]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Select one asset to chang its status into "Archived".
![image](https://github.com/user-attachments/assets/f4f719d8-335b-49bd-bc52-250d9ab5c3d5)

After save, the status not change
![image](https://github.com/user-attachments/assets/2fcd59f9-5c41-4fad-bca7-33bc08fd49ea)

When change to other status "Repairing", the same error.

Eventually I found 
1、The asset status have to be changed into status "Reday to deploy" first
2、Then it can be changed to status such as "Archived" "Repairing" "Pending"
3、Can not from status "Deployable" to "Archived" "Repairing" "Pending" directly.

### Reproduction steps

1.Select one asset to chang its status into "Archived" or "Repairing".
2.After save, the status not change
3.Eventually I found 
01、The asset status have to be changed into status "Reday to deploy" first
02、Then it can be changed to status such as "Archived" "Repairing" "Pending"
03、Can not from status "Deployable" to "Archived" "Repairing" "Pending" directly.
...

### Expected behavior

Hope to solve it
Thank you

### Snipe-IT Version

 Version v7.0.9 - build 14371 (master)

### Operating System

Ubuntu, Windows

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

windows

### Browser

google

**Comment by snipe** [comment]
The status cannot be changed to an undeployable stats if it's already checked out, as it says under the bulk status edit option. This works as intended.

<img width="951" alt="Screenshot 2024-07-27 at 9 56 32 AM" src="https://github.com/user-attachments/assets/63ba5026-2d16-4e6c-bf75-33483881a6f8">
<img width="309" alt="Screenshot 2024-07-27 at 9 56 46 AM" src="https://github.com/user-attachments/assets/16a239b3-90ac-4d72-82e8-bf8338778cf6">

<img width="957" alt="Screenshot 2024-07-27 at 9 57 10 AM" src="https://github.com/user-attachments/assets/9905210d-253e-4e17-ba5c-a92bc1ef8356">
<img width="355" alt="Screenshot 2024-07-27 at 9 57 20 AM" src="https://github.com/user-attachments/assets/9501a3fe-24bd-4f42-b3cc-b25bcc20257c">
