### ISSUE TITLE
Running php upgrade does not continue, no errors.

### ISSUE THREAD

**Issue by edd080** [grokability/snipe-it#15190]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Trying to upgrade from version 7.0.9 to 7.0.10 , I run the php upgrade.php command and its just stops, no errors.

### Reproduction steps

1. open command prompt as admin
2. go to where the snipe directory is located
3. Run the command "php upgrade.php"

### Expected behavior

Start processing the upgrade command and maybe upgrade to the latest version..

### Screenshots

![snipe_upgrade](https://github.com/user-attachments/assets/5299e5c5-a8eb-4cf8-b97b-b3bf6c61312b)

### Snipe-IT Version

7.0.9

### Operating System

Windows 10

### Web Server

IIS

### PHP Version

8.1.27

### Operating System

Windows 11

### Browser

Google, Firefox, Edge

**Comment by Odoxa** [comment]
Hello, I have exactly the same issue. On my environment we have Windows Server 2022 and PHP 8.1.29.
I don't know is someone was able to find a workaround regarding this.

Best regards,

**Comment by edd080** [comment]
It seems that since version 7.0.9 the upgrade.php module got updated; from other issues posted here I noticed a user posted a link to the following [here](https://php.watch/articles/php-curl-windows-cainfo-fix) . 
I then modified the current upgrade.php:
the below is a portion of the code of the original upgrade.php (red box):
![Original-upgradephp](https://github.com/user-attachments/assets/b46a5532-a7da-4eac-b17e-27423cdfd32e)
which I modified (from the link) with the following code (red box)
![Modified-upgradephp](https://github.com/user-attachments/assets/346325e4-1820-4011-a636-dcf293645b1c)
I then ran the php upgrade.php and it now gives me the below usual "error"
![upgrade-output](https://github.com/user-attachments/assets/1b05a9dc-86de-45cb-9444-eead8bed2804)
i use the skip compatibility checks which allowed me to continue..
![upgrade-output2](https://github.com/user-attachments/assets/34509b6e-84cc-4898-89ae-2c983bba93fd)

The json requirements URL is accessible by the way, I am able to open it from the browser on the same server.

Any help would be appreciated, thanks ..

**Comment by brianhoganm** [comment]
> Hello, I have exactly the same issue. On my environment we have Windows Server 2022 and PHP 8.1.29. I don't know is someone was able to find a workaround regarding this.
> 
> Best regards,

Same here! I have this issue as well.

**Comment by yvek91** [comment]
> > Hello, I have exactly the same issue. On my environment we have Windows Server 2022 and PHP 8.1.29. I don't know is someone was able to find a workaround regarding this.
> > Best regards,
> 
> Same here! I have this issue as well.

Same.

**Comment by edd080** [comment]
The only way I managed to get mine updated was through my second post. Hopefully someone can update us on a possible better solution.

**Comment by snipe** [comment]
We don't have easy access to windows machines to test this, but we're still trying to figure out what the issue is here. 

In the meantime, remember that the upgrade.php is just a small wrapper around these commands - you don't actually need it.

```
composer.phar self-update
git pull
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear
php artisan route:clear
php artisan cache:clear
php artisan view:clear
```

(Replace `composer.phar` with just `composer` if you have composer installed globally.

**Comment by snipe** [comment]
The `--skip-php-compatibility-checks` on upgrade.php *should* be bypassing that curl check

**Comment by edd080** [comment]
Thank you for looking into this, will try the set of commands next time and see how it goes, using the skip php compatibility checks did not work for me unless I modify upgrade.php as per my second post. After the modification the skip compatibility would then work.

**Comment by snipe** [comment]
Roger that. @uberbrady spun up a Windows VM recently, so I'll have him try to reproduce this on Monday.

**Comment by edd080** [comment]
Thank you so much 👍

**Comment by uberbrady** [comment]
If anyone else is playing around with this, one thing I saw that improved the version check was to change the call to `url_get_contents()` to instead use `file_get_contents()` - an line 68 - here:

https://github.com/snipe/snipe-it/blob/e8a22f3c5bf0fc22602a1373cf91090d40e9d734/upgrade.php#L68

When I do that, it does get past that part. I'm not sure that's going to be the permanent solution, however, because some highly-secure installations might have "fopen() wrappers" disabled. So I _suspect_ the `curl` method is still the right way to go. But I'm still playing around with it and will report back.

**Comment by snipe** [comment]
Yeah, the fopen issue is why we changed it, IIRC

**Comment by uberbrady** [comment]
I have a partial fix for this in the works that I’m hoping to have out for tomorrow.
 
It should fix most of the bits where `upgrade.php` misfires, but it won’t fix the “disappearing `upgrade.php`” problem, which is still a big mystery for us.

**Comment by edd080** [comment]
> If anyone else is playing around with this, one thing I saw that improved the version check was to change the call to `url_get_contents()` to instead use `file_get_contents()` - an line 68 - here:
> 
> https://github.com/snipe/snipe-it/blob/e8a22f3c5bf0fc22602a1373cf91090d40e9d734/upgrade.php#L68
> 
> When I do that, it does get past that part. I'm not sure that's going to be the permanent solution, however, because some highly-secure installations might have "fopen() wrappers" disabled. So I _suspect_ the `curl` method is still the right way to go. But I'm still playing around with it and will report back.

~If I just modify line 68 using the original upgrade.php file the same issue occurs for me as per my first post; will wait for your fix and test it out to see how it goes.~
Thanks for looking into this.

Sorry my mistake, I must have done something wrong, I modified Line 68 using file_get_contents again and now it allows me to upgrade ! So yes your fix works :) 

![phpupgrade](https://github.com/user-attachments/assets/92b48d6a-47d1-4bce-a802-59dd1876e8be)

**Comment by snipe** [comment]
Unfortunately, that fix does not work universally across all systems. As @uberbrady said, we'll have a fix out later today.

**Comment by edd080** [comment]
No problem will wait for the actual fix, and let you know.

**Comment by edd080** [comment]
Hello Thank you so much for your help, I can confirm that this is working, just updated to the latest version, and everything went smoothly 👍.
Thank you once again.
