### ISSUE TITLE
v7.0.10 - broken layout in Admin Settings

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15191]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Broken layout in v7.0.10

### Reproduction steps

1. Set language to en-US.
2. Observe correct layout in Admin Settings.
3. Change language to Finnish, Lithuanian (any language with long translations would work)
4. Observe broken layout because text takes more than one line.

### Expected behavior

Layout doesn't break.

### Screenshots

![image](https://github.com/user-attachments/assets/9fc8d722-97d2-4029-a7b5-2d8de9cff84d)
![image](https://github.com/user-attachments/assets/2937f1d8-4375-473f-a047-a3bbefaf6942)
![image](https://github.com/user-attachments/assets/6a75709d-af86-433c-ba66-189eeee928f0)

### Snipe-IT Version

7.0.10

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.3

### Operating System

Win10

### Browser

Edge, Firefox

### Additional context

Fresh install

**Comment by swift2512** [comment]
It's also evident on russian language. Some texts span for 3 lines if browser windows is less than 1920x1080.

This is how it would look with fixed height.
![image](https://github.com/user-attachments/assets/160fe99b-46dd-4e3e-8e22-3686b8ba2798)

**Comment by swift2512** [comment]
margin-bottom: 20px
(19px also work)
![image](https://github.com/user-attachments/assets/b7e63b9a-ee03-4e1e-85aa-4e2f6a7518e0)

**Comment by Godmartinz** [comment]
Thanks for bringing this to our attention @swift2512 . I've applied a height restriction while the screen is between `(max-width: 1318px) and (min-width: 1200px)`.
