### ISSUE TITLE
[Docker] Garbage data when importing users and assets

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15203]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

My Docker install is currently on 7.0.4 and can't be updated because of reasons. My LAMP install is on 7.0.10.
Unfortunately I can't test Docker because 'Docker Desktop' refuses to work properly on my Windows machine.

When importing data, bellow mentioned columns aren't used, but:

For assets field 'Last audit' is being populated with invalid date.
For users fields 'Start Date', 'End Date' are being populated with invalid date.
![image](https://github.com/user-attachments/assets/7c13e40f-8953-452d-b7ce-41e5b3fdb1df)

On LAMP this doesn't happen, only mapped columns are populated. Tested with same csv file. (CSV contains these columns: "Company","Activated","First Name","Last Name","VIP","Remote","City","Username","Department","Location","Notes")

**Incorrect date in 'Last audit' prevents assets from checkout. This date can't be changed manually, you have to AUDIT that asset. It may become tedious process because you have to go through your assets one by one.**

### Reproduction steps

1. Import CSV file without 'Last audit' column for assets (without 'Start Date', 'End Date' for users)
2. Observe mentioned columns. They will be populated with garbage data.

### Expected behavior

Fields ('Last audit', 'Start Date', 'End Date') should be empty.

### Snipe-IT Version

7.0.4

### Operating System

Docker

### Web Server

-

### PHP Version

-

**Comment by snipe** [comment]
Unfortunately, I think upgrading is your only way out of this. We've addressed those issues in later versions. https://github.com/snipe/snipe-it/pull/14908
