### ISSUE TITLE
Use of Emoji's generally in Snipe-IT

### ISSUE THREAD

**Issue by Toby737** [grokability/snipe-it#15216]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello Team Snipe-IT :smile:
More of a question than a bug report I guess, but does Snipe-IT support the use of emoji's?
Specially the [emoji's](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md) from the [Github flavored markdown](https://help.github.com/articles/github-flavored-markdown/) site.
Actually seems like most of the markdown options do not work.  Only the heading, bold and italic markdowns work so far.

### Reproduction steps

1. In Admin, go to Branding.
2. In Additional Footer Text, add text and the emoji code from the emoji cheat sheet.
3. Save the changes and review the result.

### Expected behavior

Expecting emoji instead of the code.

### Screenshots

![Screenshot 2024-08-05 143325](https://github.com/user-attachments/assets/b99c006e-2145-4374-95de-90ed78017317)
![Screenshot 2024-08-05 143943](https://github.com/user-attachments/assets/c90626a5-f1f6-4262-8106-c853caa8fb6a)

### Snipe-IT Version

7.0.11

### Operating System

CentOS 9

### Web Server

Apache

### PHP Version

8.3.10

**Comment by Toby737** [comment]
Also tried the use of the Alerts options for the Login Note but that didn't seem to work either.
![Screenshot 2024-08-05 144535](https://github.com/user-attachments/assets/1ebbbf93-a0ac-4710-8e2e-4721126fb2b6)

**Comment by Toby737** [comment]
Also tried to use the Alerts markdown for the Login Notes but didn't work the way it was supposed to either.

**Comment by Toby737** [comment]
Actually, I'll close this and move it over to the Discussion section. It's probably more appropriate than clogging up the Issues section :smile:

**Comment by snipe** [comment]
I think you should just be able to put the actual smiley in from your Edit > Emojis menu. I don’t think we try to strip those out

**Comment by snipe** [comment]
(I’m not deeply familiar with the markdown library we use for that stuff, but I can check when I’m back at my machine.)

**Comment by Toby737** [comment]
Aah - yes you are correct.  Just using an emoji worked.
I guess I'd be fine with at least that if the other Github markdown options aren't supported in Snipe-IT.
Thanks.

**Comment by Toby737** [comment]
Also, I noticed the pie chart in the latest Snipe-IT only shows the green Ready to Deploy items.
Previously with 7.0.10 it also displayed Deployed items in red.
Just thought I'd mention it here instead of opening up another bug ticket.
![Screenshot 2024-08-15 154028](https://github.com/user-attachments/assets/21f930c2-ed4b-4cb9-b361-c04f30cc22ba)

**Comment by snipe** [comment]
That pie chart wasn’t respecting the “show archived in lists” setting (in Admin > General Settings) before, IIRC. Now it does.

**Comment by Toby737** [comment]
I'm actually fine with the pie chart not showing Archived items.
I also don't have that option enabled because I don't want to see Archived items in the List.
Just that in 7.0.10, the pie chart also showed Deployed items in red, but with 7.0.11, it's not showing Deployed items but just only Ready to Deploy on my instance since the upgrade.

**Comment by Toby737** [comment]
Is there a way to do a git clone and pull 7.0.10 instead of the latest?
Would like to revert back to the previous version.

**Comment by Toby737** [comment]
Actually all good. After a bit of googling, I managed to find out how to git clone 7.0.10 and restored from backup.
So am back to this version.
Here's the pie chart on 7.0.10 for reference...
![Screenshot 2024-08-16 102027](https://github.com/user-attachments/assets/f1a28e1b-7c11-43df-893b-6facade19f5d)

**Comment by Toby737** [comment]
Ah, actually I see what you mean. 
So disregard my previous post :)
But I think we can just close this incident.
