### ISSUE TITLE
Remaining Quantity Discrepancy

### ISSUE THREAD

**Issue by brianhoganm** [grokability/snipe-it#15212]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When logging into two different accounts in SNIPEIT, there is a discrepancy in how many items are remaining. It appears that that Super Admin account has the correct remaining QTY but not other account with lesser permissions. 

![Screenshot 2024-08-02 154720](https://github.com/user-attachments/assets/d9bb3c96-b2bc-4449-a545-708220c741fe)

### Reproduction steps

1.N/A
2.
3.
...

### Expected behavior

The same remaining QTY should be the same regardless of which account you are logged in. 

### Snipe-IT Version

7.0.10 

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.22

### Operating System

Windows

### Browser

Chrome

**Comment by swift2512** [comment]
Multi-Company support enabled? Maybe another user is an Admin and (not) assigned to a company? This would explain why it sees lesser numbers. (Super-Admin sees everything.)

**Comment by brianhoganm** [comment]
> Multi-Company support enabled? Maybe another user is an Admin and (not) assigned to a company? This would explain why it sees lesser numbers. (Super-Admin sees everything.)

Hi, Thank you for your response. Yes, I have Multi-Company support enabled and my user is an admin assigned to a company. I'm not sure what is going on but something is messed up with counting.

**Comment by swift2512** [comment]
@snipe Tried on my own install (v7.0.4) with Multi-Company enabled. It has to be a bug.

There is no check against company in Components, so you can check-out items to assets from other companies (or can leave company unset). That's why your superadmin sees more assets than your company assigned admin.

Unfortunately, in component's info page Company column is not available, so it's hard to tell where mistake was made.

**Comment by snipe** [comment]
> There is no check against company in Components

There is tho. 

https://github.com/snipe/snipe-it/blob/28abb8d8cc269af554f562bac639124e3cf5bc3d/app/Models/Component.php#L21

It's a trait, so it's automatically scoped. 

Company is viewable via the listing page.

<img width="733" alt="Components____Snipe-IT_Demo" src="https://github.com/user-attachments/assets/0fa9265e-b540-4f6b-a51e-53ab138e8cfc">

**Comment by swift2512** [comment]
@snipe Snipe-IT demo is broken... Admin user davonte47 has access to everything, like it's a superadmin. I've tested on my own demo VM ( Version v7.0.10 - build 14684 (master).

With **superadmin** user:
- When checking out COMP-A **asset** to user from COMP-B, Snipe-IT throws an error '**Error: Checkout target company and asset company do not match**'
- When doing same with components, action completes succesfully - 'Success: Component checked out successfully.'

And now superadmin and admin (bound to COMP-A) see different component numbers: for one it's 1, for another- 19.
![image](https://github.com/user-attachments/assets/3ccf3ac1-2605-48bc-a76f-4c04119fbc6c)

And from here it gets even worse - COMP-A admin can assign all 19 'available' pieces of that component, so superadmin sees this
![image](https://github.com/user-attachments/assets/c87d18b3-6bb5-4bc7-84dc-a58150c71ba2)

**Couldn't reproduce this with Licenses, Consumables or Accessories** - these item groups take into account Company they are assigned to.

**Comment by marcusmoore** [comment]
Thanks for the detailed reporting @swift2512. I'm working on a fix.

**Comment by marcusmoore** [comment]
Hey there, @brianhoganm and @swift2512. A PR (#15229) fixing this was merged and will be included in the next release (v7.0.11). I'm going to close this assuming the fix works. Please reply if it doesn't and we can re-open this issue.

Thanks again for reporting!

**Comment by albertochungvz** [comment]
Hi! I'm new here and I'm not sure if comment here of I should open another issue: The remain quantity is still buggy in mail reports (with multi-company support enabled).

Assigned Licences, e.g.
![Captura de pantalla 2024-09-10 002230](https://github.com/user-attachments/assets/b4d52812-5fd8-4e7c-ba6a-f1ba9afb360e)

Mail report:
![image](https://github.com/user-attachments/assets/7be677e7-fdf1-46b5-935f-1bb8ae3a164c)

Mail report with multi-company disabled:
![image](https://github.com/user-attachments/assets/c5a6c006-432b-4158-9aa7-a48700574592)

**Comment by marcusmoore** [comment]
@albertochungv thanks for reporting. Do you mind opening a new issue (and using/filling out) the issue template so we have more information to work with? Thanks! (Feel free to ping me with `@` so I'm notified).
