### ISSUE TITLE
[Feature Request]: Add record/mark to employee which don't work 

### ISSUE THREAD

**Issue by bjochym-miquido** [grokability/snipe-it#15215]
### Is your feature request related to a problem? Please describe.

We have a lot of employees who aren't working, but their accounts are still in our database. We are concerned about deleting their accounts because it may break the database.

### Describe the solution you'd like

Maybe specify fields and mark colors for offboarding employees, or something similar.

**Comment by snipe** [comment]
Users are soft-deleted unless you purge the database, so it’s safe to mark them as deleted.

**Comment by bjochym-miquido** [comment]
So, if we delete the user, will the history of assets associated with his name remain after the deletion?

**Comment by snipe** [comment]
Yes, that's why they're soft-deleted, so you can see their history and also their names still show up as having been associated with the asset, etc.
