### ISSUE TITLE
[Feature Request]: Items assigned to user when moving assigned location do not follow user

### ISSUE THREAD

**Issue by derrickchiang** [grokability/snipe-it#15228]
### Is your feature request related to a problem? Please describe.

currently have users assigned to desk locations and some user specific hardware that gets assigned to them (laptops, phone, headset, etc.) when they assigned to the user, they are assigned a location of the user as well. when the user gets moved via ldap sync their hardware does not move with them and remains at the old desk location. 

### Describe the solution you'd like

have user assigned hardware automagically move with the user when they move locations based on ldap sync

### Describe alternatives you've considered

would write sql script to manually update the locations

**Comment by snipe** [comment]
What version of Snipe-IT are you using? (Next time please use the GH issue template so we have the answers we need.)

**Comment by derrickchiang** [comment]
v6.2.0-pre build 11531

Sorry, yea i realized that it may have been better as a bug report rather than a feature request later that evening.

**Comment by snipe** [comment]
I think this has probably already been fixed

**Comment by derrickchiang** [comment]
oh wow, didn't realize how far behind we were. ok thanks, I'll have it updated and will test, in about a week or so, vacations.

**Comment by snipe** [comment]
Vacation is good. Take your vacation :) Come back fresh and let us know if there's still stuff we need to look at.

**Comment by snipe** [comment]
I'll close this one for now, but open up a new issue if you're still running into this. Enjoy your vacation :)
