### ISSUE TITLE
Issue with New Label Engine

### ISSUE THREAD

**Issue by qu1dam** [grokability/snipe-it#15220]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

On Update Label Settings when is not selected New Label Engine and when is generated labels with info for Avery L6011 labels on A4 sheets, mentioned on link: https://snipe-it.readme.io/docs/-asset-label-printer-examples-and-settings
You get generated labels for Avery L6011.
But when you click New Label Engine and save changes, this info with same data don't show correct label positiong.
All can bee seen on demo page https://demo.snipeitapp.com/admin/labels

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Labels should be shown as the default selection with more options

### Screenshots

Not enabled New Label Engine
![old](https://github.com/user-attachments/assets/449a2601-4431-452d-86b3-70a858391993)

Enabled New Label Engine
![new](https://github.com/user-attachments/assets/64b52df3-fbcd-4f3c-84be-9d1a64045b73)

### Snipe-IT Version

v7.0.10

### Operating System

Ubuntu, Windows

### Web Server

Apache, IIS

### PHP Version

8.1.2 or greater

**Comment by swift2512** [comment]
I think that old and new label engines aren't linked. Old engine generates label on the fly, while new engine uses label template files, stored in **app/Models/Labels/**

**Comment by snipe** [comment]
@swift2512 is correct here. It was too destructive for us to *assume* a user would want to use those other settings with the new label engine.

**Comment by qu1dam** [comment]
On the New Label Engine, I cannot see a template, for example, for Avery L6011 labels on A4 sheets
Can you please tell me how I can add that template or any other using the New Label Engine

**Comment by swift2512** [comment]
> On the New Label Engine, I cannot see a template, for example, for Avery L6011 labels on A4 sheets Can you please tell me how I can add that template or any other using the New Label Engine

You either use defaultlabel template and adjust it accordingly, or you make your own php files and put them  in app's label folder.

**Comment by vinc32** [comment]
@qu1dam can you share the php file for L6011?

**Comment by qu1dam** [comment]
> [@qu1dam](https://github.com/qu1dam) can you share the php file for L6011?

Here you go [https://www.averyproducts.com.au/sites/avery.au/files/avery_importer/template/files/Avery_L6011_Word_Template.doc](url)

also you can find it more on this official site

**Comment by vinc32** [comment]
[Avery_L6011.zip](https://github.com/user-attachments/files/21839250/Avery_L6011.zip)

Thx, I've ment the PHP File for Snipe IT.
Attached one that can be customized

**Comment by qu1dam** [comment]
all existing labels you can find on path of app App\Models\Labels\Tapes
because od that questio ni open post: https://github.com/grokability/snipe-it/issues/17504

**Comment by vinc32** [comment]
Yes, but L6011 is not in there ;) So I've created the php file for the L6011 Label ;)
Attached with Logo Outside the QR code

[L6011_Logo_right.zip](https://github.com/user-attachments/files/21850009/L6011_Logo_right.zip)

**Comment by qu1dam** [comment]
Great, can you please modify this one Tapes\Dymo\LabelWriter_2112283 or name it something dif but with this specs https://github.com/grokability/snipe-it/issues/17504
