### ISSUE TITLE
Pre-flight not loaded, 403 instead when installing on plesk

### ISSUE THREAD

**Issue by Dejv92** [grokability/snipe-it#15233]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to install Snipe-it to a webserver running plask webhosting service (I am admin so I cat set and allow all possible parameters, not restricted by any webhosting company), I am stucked after succesfully install dependencies I also generate key succesfully.
I strugle with last step - Pre-Flight & Setup. When trying to access page, I get an error:
```
Forbidden

You don't have permission to access this resource.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
```

Tryied advices from Installation/Upgrading Issues like cleaning cache etc...

Log from plesk is attached.
![snipeit 2024-08-07 112351](https://github.com/user-attachments/assets/78dc1bbf-4a7d-4d95-9144-ad164512cf48)

Web root is set to ./public folder (almost sure this is set up correctly).

### Reproduction steps

1. Upload Snipeit to plesk server
2. configure .env
3. install dependencies
4. generate app key
5. try to open Pre-flight, no success
...

### Expected behavior

Pre-flight show instead so 403 and additionally 500 error.

### Screenshots

![Snímek obrazovky 2024-08-07 113222](https://github.com/user-attachments/assets/573f717f-35d6-4067-abc8-15f059737db6)

### Snipe-IT Version

7.0.10

### Operating System

Alma linux 9.4

### Web Server

Apache (can go to nginx)

### PHP Version

8.2.21

### Operating System

Windows 11

### Browser

Firefox

### Version

128.0.3

### Error messages

```shell
Forbidden

You don't have permission to access this resource.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

HTTP status code in network console is 403.
```

**Comment by snipe** [comment]
I think you'll probably have to tweak your mod security settings

**Comment by Dejv92** [comment]
Thanks! I temporarily turn mod security off (just for page reload) and now I got a 500 error and this:

![snipeit 2024-08-07 114837](https://github.com/user-attachments/assets/d7d6f5da-9146-4aa3-bbea-78f59602cbf0)


file database.sqlite does not exists (not sure when it should be created)

additional errors
`Using ${var} in strings is deprecated, use {$var} instead in /var/www/vhosts/snipeit.xxxxxx.cz/app/Models/License.php on line 188`

`Using ${var} in strings is deprecated, use {$var} instead in /var/www/vhosts/snipeit.xxxxxxxx.cz/app/Models/License.php on line 220`

**Comment by snipe** [comment]
You're need to create the sqlite file if that's what you're going to try to use. You should note that we don't officially support sqlite though, so you may run into some weird issues.

**Comment by Dejv92** [comment]
So when I want MySQL (MariaDB) I made an mistake in .env file? When I generate an app key, all infos from .env file is gone (now there is sqlite and I dont know why), I dont know how this works, if it was tranfasered to other conf files or if it is not intended behavior. I am almost sure I used MySQL in file originaly :/ Should I try to change this file again or do whole instalation again from skretch?

**Comment by snipe** [comment]
The only thing we do when you generate that key is change the actual app key itself, we don't reset any of your other settings.

**Comment by Dejv92** [comment]
Looks like some built-in tool in plesk totaly changed .env file, after I changed it back (preserved only app key), it now worsk even with Mod security on. 

Thanks!

**Comment by snipe** [comment]
Excellent - glad to hear you're sorted!
