### ISSUE TITLE
[Feature Request]: Freeze Column in a view

### ISSUE THREAD

**Issue by adm-graf** [grokability/snipe-it#15231]
### Is your feature request related to a problem? Please describe.

Every time I switch from one view to another, my "selected" columns are reset.

### Describe the solution you'd like

Is it possible to freeze the columns of different views, even customs? We'd like a "custom" view not to jump every time we change sub-menu or refresh the page.

Is there a way to do this?

### Describe alternatives you've considered

Is it possible to freeze a filter with a dedicated function?

**Comment by huifei0129** [comment]
have the same issue

**Comment by criverin** [comment]
Also here. Would like to freeze filters/views. Would be very helpful. Thanks

**Comment by snipe** [comment]
That's not currently possible at this time. We keep trying it, but the JS library extension always ends up breaking the UX.

**Comment by adm-graf** [comment]
Thanks for your reply. Will it be a feature maybe in one of the next versions ?

**Comment by snipe** [comment]
If we can ever get it to work. We try every few years.

https://github.com/snipe/snipe-it/pull/14939
https://github.com/snipe/snipe-it/pull/11318

**Comment by adm-graf** [comment]
Ok I get it. Thanks for the reply.

**Comment by snipe** [comment]
It's definitely something we *want* to do, we just can't get it to work without acting really funny in certain circumstances :(
