### ISSUE TITLE
csp_policy do not include google workspace url lh3.googleusercontent.com

### ISSUE THREAD

**Issue by reiserfs** [grokability/snipe-it#15238]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

on Http/Middleware/SecurityHeaders.php line 91

` $csp_policy[] = "img-src 'self' data: ".config('app.url').' '.config('app.additional_csp_urls').' '.env('PUBLIC_AWS_URL').' https://secure.gravatar.com http://gravatar.com maps.google.com maps.gstatic.com *.googleapis.com';
`

is missing the google workspace url lh3.googleusercontent.com 

adding *.googleusercontent.com solve the problem

Another problem is in Edit profile, if you have a google workspace avatar the URL generated is 

https://snipeit.url.com/uploads/avatars/https://lh3.googleusercontent.com/a/data

### Reproduction steps

1. Login with google workspace
2. try to see the avatar
3. firefox block because csp_policy rule
...

### Expected behavior

Open the avatar

### Snipe-IT Version

v7.0.10

### Operating System

docker

### Web Server

snipe/snipe-it:v7.0.10

### PHP Version

8.1.2-1ubuntu2.18

**Comment by snipe** [comment]
You should be able to add that to `ADDITIONAL_CSP_URLS` in your env.
https://snipe-it.readme.io/docs/configuration#optional-misc
