### ISSUE TITLE
[Feature Request]: Dashboard "Assets by Type" graph customization

### ISSUE THREAD

**Issue by MWR-Napavine** [grokability/snipe-it#15247]
### Is your feature request related to a problem? Please describe.

We are a school district. We use Snipe-IT to keep track of all of our devices. This includes any device we have disposed of, as we intend to keep the information about these devices for at least 10 years, if not forever.

The Snipe-IT has a very handy graph on the Dashboard called "Assets by Type". It can be very useful to illustrate our current fleet of assets.

But that graph is becoming less useful as our database is starting to fill with "archived" assets. As our assets are retired, they are moved to a new status label called "Archive" for our sold, lost, surplused, recycled, stolen, used for parts, or destroyed items. This status label is now dominating the graph.

When the graph is dominated by these items, it is less useful for illustration purposes. (i.e.: Showing how many devices are in use, in repair, or ready for deployment.)

### Describe the solution you'd like

Make it possible to disable specific Status Labels in the graph. Either with a temporary option, or a configuration spot that allows the user/admin to choose which status types to display.

**Comment by snipe** [comment]
Do you have the option to hide archived assets from list views enabled in Admin Settings > General? 

<img width="568" alt="Screenshot 2024-08-10 at 6 32 27 PM" src="https://github.com/user-attachments/assets/de2044f4-abe2-48e7-8900-775968198e3e">

**Comment by MWR-Napavine** [comment]
Unchecking that item does not effect the pie chart.
