### ISSUE TITLE
[Feature Request]: MASS clone asset

### ISSUE THREAD

**Issue by MWR-Napavine** [grokability/snipe-it#15246]
### Is your feature request related to a problem? Please describe.

We order 100s of similar assets at a time. The first of these items are entered into Snipe-IT with loving care, filling all the necessary fields correctly.

Then, the most practical thing to do is to either use the existing "Clone Asset" button or do an Export/Import.

The Clone Asset button is excellent, as it allows for easy cloning of the asset. It can be used to quickly make 1, 2, or even more clones of the asset with ease.... But in the case of having to clone 100+, it is a burden to correctly fill out all Asset Tags and Serial Number fields correctly.

The Import/Export option is also available, but this requires one to export the assets with the correct fields (All Assets, as there is no way to specify a specific asset in Custom Reports). Then recreate the Import CSV file with the correct exported from the first asset's fields with the additional Assets to be added.

### Describe the solution you'd like

I see two possible solutions: 

Option one, provide a UI to perform a MASS Clone, allowing for a range of Asset IDs to be entered. You will also have to allow a list of Serial Numbers to be entered and parsed. This way the cloned items are all unique.

Option two, allow an asset to be "Exported for Import." Using this feature, the first Asset can be exported with a properly created CSV file that includes all the necessary fields. This can then be edited by the user using a spreadsheet to add the additional items to be cloned. This new CSV is then imported using the existing import method.

### Additional context

When importing hundreds of Chromebook, and including the various custom fields we use (Budget codes, funding sources, etc.), a method to easily clone an imputed asset would be a huge benefit to all.

**Comment by snipe** [comment]
> Option two, allow an asset to be "Exported for Import." Using this feature, the first Asset can be exported with a properly created CSV file that includes all the necessary fields. This can then be edited by the user using a spreadsheet to add the additional items to be cloned. This new CSV is then imported using the existing import method.

This is already possible, no?

**Comment by MWR-Napavine** [comment]
How do I export a single asset correctly for import? Is there a place within the asset page where that export can be performed? I don't see it.

**Comment by snipe** [comment]
You can search for the asset in the list view and export from the table result

**Comment by snipe** [comment]
(Make sure you toggle the "Show all" in the column selector, since the table export will only export what's visible on the screen)

**Comment by MWR-Napavine** [comment]
The following method did work:

   1. Open the *Assets - List All* from the menu.
   2. Use the search field to limit the search to the item you wish to
   clone. This can be easily done with any unique value, such as it's Asset
   Tag or Serial Number.
   3. Use the *Columns* dropdown menu and select *Toggle All*. This will
   make all the fields available for the export.
   4. Use the *Export* dropdown and choose *CSV*. Other formats may be
   used, but must be converted back to CSV for importing.
   5. Open and manipulate your CSV file using a spreadsheet program, such
   as Excel or Open Office.
      1. Do not manipulate the first row of headers. If unmodified, they
      will be used to automatically remap the fields during import.
      2. To create the additional cloned items, copy the existing item on
      the sheet as many times as you need. *Each item will need a unique
      Asset Tag.* If you have the "Require Unique Serial Numbers" option
      enabled in your settings, you will also need each asset to have a unique
      serial number. In most cases, updating the Asset Tag and the
Serial Number
      for each line is sufficient. All other fields can remain the same.
   6. Save your modified spreadsheet back to the *CSV* format.
   7. In Snipe-IT, select the *Import* menu.
   8. Upload your CSV file by pressing the *Select File* button and
   choosing your modified CSV file for upload.
   9. After uploading, your file will appear on the list, ready for import.
   Select the *Map fields and process this file* button.
   10. Change the *CSV import type* option to *Assets*.
   11. The Fields for import will be listed. If you did not modify the
   header row, all the necessary fields will be remapped. Note the *ID*
   field by default is set to *Do Not Import*. This is correct. Snipe-IT
   will automatically create a new ID for each imported item. Do not confuse
   the *ID* with the *Asset Tag*. They are not the same.
   12. Check that the *Sample Values* shows the correct data for import.
   Once you are satisfied, press the *Process Import* button on the bottom
   of the page.
   13. Your new items will be created.

These steps are not in the official documentation. Perhaps they should be
added. Feel free to copy what I have here.

My original request was to simplify part of this process. Please consider
adding a button to the asset that automatically provides a CSV file as
created with steps 1-4. The button could be right beneath the existing
Clone button here, perhaps with a link to documentation.

[image: image.png]

Thanks for your consideration.

**Comment by snipe** [comment]
I guess I'm not really understanding how that will help. You still have to copy+paste 100 serial numbers. Whether you do that within the Snipe-IT UI or in Excel for an import doesn't seem like it matters a whole lot.

**Comment by MWR-Napavine** [comment]
It's more user friendly. Imagine Snipe-IT is used by a school librarian, who isn't tech savvy, but does know how to use Excel a bit. (I know many of these types, as I work in K12 education.) They just received 30 new iPads. (Or 20 copies of a book, or 50 new Chromebooks, etc.) Often, they get a list of serial numbers from their vendor of the new items. Or if they don't, they will generate a list of serial numbers manually (USB barcode scanners and a spreadsheet are used to do this efficiently.)

Either they have to use the existing clone interface for 29 iPads which requires lots of copy and pasting (or worse, manual input) or they need to know they can download the single item for re-import. As of right now, your documentation doesn't include how to do this.

In my case, I have custom fields. Importing these can be even more difficult, unless there was good export file that included those custom fields already. Thanks to your previous post, you explained how to surface them correctly and cleanly. Thank you for that.

But it isn't intuitive. The layman won't know how to do this, even if they are familiar with spreadsheets. Having a "Mass Cloning" option surfaces the possibility and makes starting this process easier.

I would ask, if nothing else, that this method for Mass Cloning added to the Cloning section of the Documentation. I'm sure others have look for and ask about how to do this. I will probably use it myself in the future just to remind myself how to do it.

Thank you for your consideration.

**Comment by snipe** [comment]
> But it isn't intuitive. The layman won't know how to do this, even if they are familiar with spreadsheets. Having a "Mass Cloning" option surfaces the possibility and makes starting this process easier.

I really don't think this will add any clarity though. Having a download button to a one-line spreadsheet would be more confusing IMHO.  I guess I can add some advice to the docs. 90% of your extra steps are just the normal part of the import process though, and I don't think I'd include them there.

**Comment by snipe** [comment]
I updated the documentation to make the path clearer.
