### ISSUE TITLE
Order Number puts a #

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#15248]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Remove # from order number

### Reproduction steps

1. Enter order number
2. check order number
3.
4.
...

### Expected behavior

Shouldn't have a # in order number

### Screenshots

![Screenshot 2024-08-08 113252](https://github.com/user-attachments/assets/9b0fd264-5dff-4408-8be0-05e96d6db914)
![Screenshot 2024-08-08 113243](https://github.com/user-attachments/assets/8447da86-59a6-4d25-883a-42a38a462736)

### Snipe-IT Version

 v7.0.10 build 14684 (gc2bcc2e2d) 

### Operating System

almalinux

### Web Server

apache

### PHP Version

8.1.29

**Comment by snipe** [comment]
Why does this matter?

**Comment by jayavman** [comment]
> Why does this matter? 

Because it's not part of the order number?

**Comment by snipe** [comment]
I'm not sure how this would really affect the usage of the system tho.

**Comment by jayavman** [comment]
Thanks @snipe We take print outs of this page to supply vendors which they will add that extra # when adding into an external accounts system.
Minor for you, legendary for me

**Comment by snipe** [comment]
Glad to help :)
