### ISSUE TITLE
[Feature Request]: Bulk Edit

### ISSUE THREAD

**Issue by laurenzollinger** [grokability/snipe-it#15259]
### Is your feature request related to a problem? Please describe.

We need a way to bulk edit assets. Any spot that you're able to select multiple entries in should offer a bulk edit option. We're trying to reconcile data and move assets between departments. Right now this is a manual one by one process. 

### Describe the solution you'd like

Any spot that you're able to select multiple entries in should offer a bulk edit option to move assets in all ways.

**Comment by snipe** [comment]
Not sure what you're looking for here. That feature already exists.

**Comment by laurenzollinger** [comment]
Can you show me screenshots of where that lives? From the assets page if we select multiple assets the only option is “edit” not bulk edit?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by snipe** [comment]
That's the one - from the assets listing page, if you select more than one thing and click edit, you're performing a bulk edit by definition.

**Comment by laurenzollinger** [comment]
Hi, when we do that, it doesn't change the "checked out to" field to match the location we selected! So for example, we hit 'go' by edit, and then changed the 'default AND actual location' field to Band and Orchestra, but it didn't update the 'checked out to' in my screenshot below. We need that to change as well, in bulk!


![Screenshot 2024-08-12 at 8 42 32 AM](https://github.com/user-attachments/assets/062f7885-15d0-406f-a218-c54c38660e7f)
