### ISSUE TITLE
 The start date must be a valid date in YYYY-MM-DD format

### ISSUE THREAD

**Issue by adityakiran55** [grokability/snipe-it#15260]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

While Creating New User i am getting this issue in local host and as well cloud after importing user when try to change the manager this error is occurred 

![image](https://github.com/user-attachments/assets/d34190b0-1459-4562-8a7a-336bfb0065cf)

### Reproduction steps

While Creating New User i am getting this issue in local host and as well cloud after importing user when try to change the manager this error is occurred 

![image](https://github.com/user-attachments/assets/d34190b0-1459-4562-8a7a-336bfb0065cf)

### Expected behavior

While Creating New User i am getting this issue in local host and as well cloud after importing user when try to change the manager this error is occurred 

![image](https://github.com/user-attachments/assets/d34190b0-1459-4562-8a7a-336bfb0065cf)

### Snipe-IT Version

Version v7.0.6 - build 14112 (master)

### Operating System

Windows 11

### Web Server

apache

### PHP Version

8.2.12

### Operating System

Windows

### Browser

Chrome

### Version

127.0.6533.100

**Comment by snipe** [comment]
That was already fixed a few versions ago.
