### ISSUE TITLE
Categories are listing in Components 

### ISSUE THREAD

**Issue by adityakiran55** [grokability/snipe-it#15268]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Good Evening Team,

1. I do not know whether the feature is available in Snipe-it Under Components is their any facility to add Components on Departmental Wise.
2. I was unable to Check-in & Check-out the Component for User Wise or Department wise.
3. Uploading Purchase Order or Supporting Document option is not visible in Components.

### Reproduction steps

1. I Tried using custom field but their no progress on Components is their any facility to add Components on Departmental Wise
2. I tried to Check-in & Check-out the Component for User Wise or Department wise but it falls under asset.
3. I checked the facility to upload the Purchase Order or Supporting Document but it functionality is not visible.

### Expected behavior

1)  Under Components is should provide facility to add elements on Departmental Wise.
2.  It should be able to Check-in & Check-out the Component for User Wise or Department wise.
3. Uploading Purchase Order or Supporting Document option should be available in Components.

### Snipe-IT Version

 v7.0.10 - build 14684 (master)

### Operating System

Windows 11

### Web Server

Apache

### PHP Version

8.2.12

### Operating System

Windows

### Browser

Chrome

### Version

127.0.6533.100

**Comment by snipe** [comment]
Hi there - we don't currently have checking out to department on deck any time soon. The other requests have been requested already in various tickets.
