### ISSUE TITLE
[7.0.10][Multi-Company enabled] No check if user has items when moved to another company

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15265]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

It's possible to move users to other company while they have items assigned to them. After move, admin can't see that user and moved users can't see items checked-out to them.
It's same story, like it was with assets not long ago. It got fixed and this should be fixed as well.

### Reproduction steps

1. Enable multi-company support, create 2 companies (A & B)
2. Assign a user to a company A.
3. Assign items to this user.
4. Move that user to company B.
...

### Expected behavior

Use move should be blocked with a message, like "This user currently has assets or other items assigned to him and cannot ne moved. Please check in items from this user first and try again". (English isn't my strongest side.)

### Snipe-IT Version

7.0.10

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.3

**Comment by snipe** [comment]
@spencerrlongg this seems like a good candidate for the `SaveUserRequest`

**Comment by spencerrlongg** [comment]
Can we close this @snipe?
