### ISSUE TITLE
Technicians cannot sync LDAP

### ISSUE THREAD

**Issue by adm-graf** [grokability/snipe-it#15287]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

My technicians cannot force sync LDAP Users. Admins can do this but not technicians (different role), what's the setting I should activate to make it work ?

### Reproduction steps

1. Login and Click on "People
2. Click on "LDAP Sync"
3. Error message on web page

...

### Expected behavior

I want that every Technician can force sync the LDAP if needed.

### Screenshots

![image (23)](https://github.com/user-attachments/assets/06d5e4b9-f40f-447a-b242-9b7be59aecaf)

### Snipe-IT Version

v6.1.2 build 10938 (g32747cafd)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Error messages

```shell
Sad panda. You are not authorized to do the thing. Maybe return to the dashboard, or contact your administrator.
```

**Comment by snipe** [comment]
What permissions does the technician have?

**Comment by snipe** [comment]
They would need to have the permission to update users in order to access that LDAP sync (since the LDAP sync will, in fact, update users.)

**Comment by adm-graf** [comment]
Thanks for the reply. It works now. :)
