### ISSUE TITLE
[Feature Request]: Export history to CSV

### ISSUE THREAD

**Issue by s0comm** [grokability/snipe-it#15283]
### Is your feature request related to a problem? Please describe.

I am trying to export all device history to CSV for consumption via spreadsheet, however I dont see this option available either through API or Web UI.

### Describe the solution you'd like

Make this available through either frontend or api.

### Describe alternatives you've considered

I've tried going in through SQL query but my query doesn't line-up with what's in the front-end 1 for 1.

Here's a snippet, maybe I can get some guidance on what I'm doing wrong as a temp solution.
```SQL
SELECT
  action_logs.updated_at,
  CONCAT(first_name, ' ', last_name),
  action_type,
  CONCAT(name,'(',asset_tag')')
  asset_tag,
  (SELECT CONCAT(first_name, '',last_name) FROM users where asset.assigned_to=users.id)
FROM
  action_logs
LEFT JOIN
  users
ON
  (assets.id=action_logs.item_id)
ORDER BY
  action_logs.updated_at ASC
```

**Comment by snipe** [comment]
Can you clarify here - are you looking for us to export history, or us to import history? It’s a little unclear

**Comment by s0comm** [comment]
Sorry if I was unclear. This would be export.

**Comment by snipe** [comment]
For a specific  device, you can go to the device, click on the history tab, and export to CSV, Excel, etc:
https://demo.snipeitapp.com/hardware/1#history

<img width="753" alt="View_Asset_232096991____Snipe-IT_Asset_Management_Demo" src="https://github.com/user-attachments/assets/05cd03bc-7b92-402f-b706-b28324e8b357">


For all history, you can export using the "Download All" button in the Activity Report:
https://demo.snipeitapp.com/reports/activity

Or search for the device there and use the table export:
https://demo.snipeitapp.com/reports/activity?page=1&size=20&order=desc&sort=admin&search=339365597

Via API, you can specify the `item_id` and `item_type`

https://snipe-it.readme.io/reference/reportsactivity


<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/1#history">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/reports/activity">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/reportsactivity">/reports/activity</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>
