### ISSUE TITLE
s3 public upload is not working

### ISSUE THREAD

**Issue by noze-gnassipova** [grokability/snipe-it#15288]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Public upload to s3 bucket is not working:

APP_URL: "https://snipe-it.llive"

PUBLIC_FILESYSTEM_DISK: "s3_public"
PUBLIC_AWS_BUCKET: "snipeit-public"
PUBLIC_AWS_ACCESS_KEY_ID: "XXXXX"
PUBLIC_AWS_BUCKET_ROOT: "null"
PUBLIC_AWS_DEFAULT_REGION: "ca-central-1"
PUBLIC_AWS_URL: "https://snipeit-public.s3.ca-central-1.amazonaws.com"

### Reproduction steps

1. upload an image
2. when click on it gives error - "Failed to load image:.."

### Expected behavior

image should be available

### Screenshots

![Screenshot 2024-08-13 at 6 05 55 PM](https://github.com/user-attachments/assets/cc38cdc4-288f-4cc9-adbf-ec9c0cf2a9da)
![Screenshot 2024-08-13 at 6 04 41 PM](https://github.com/user-attachments/assets/af4870a5-c731-47aa-9274-83a1122e2086)

### Snipe-IT Version

v7.0.9

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

PHP 8.1.2-1ubuntu2.18

**Comment by snipe** [comment]
What's it showing the URL of the image to be?

**Comment by noze-gnassipova** [comment]
> What's it showing the URL of the image to be?

Here's the link and I don't see any images inside the bucket
`Failed to load image: https://snipeit-public.s3.ca-central-1.amazonaws.com/components/component-image-1-EmZfbrBlyy.png`

**Comment by snipe** [comment]
I'm not able to reproduce this. Are you sure the permissions on your bucket are correct?


Yours:
```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>snipeit-public</BucketName>
<RequestId>F0ASTMWTFK0PHT1Y</RequestId>
<HostId>
zqvvHuxdD2gkB87sclmFMU+gTb7E1eX2Zo3S0cFjuhhSVtvZTqEczoXYiCG9ldnFBP8roHj5hfbmYAtHvI7+BM1dmIpFZsFEqoUbSkFuHGk=
</HostId>
</Error>
```

Mine:

![](https://snipe-flysystem-public-test.s3-us-west-2.amazonaws.com/locations/location-image-11-5fWXpFIfdg.jpg)

`https://snipe-flysystem-public-test.s3-us-west-2.amazonaws.com/locations/location-image-11-5fWXpFIfdg.jpg`

**Comment by snipe** [comment]
I have:

```
# --------------------------------------------
# REQUIRED: UPLOADED FILE STORAGE SETTINGS
# --------------------------------------------
PRIVATE_FILESYSTEM_DISK=s3_private
PUBLIC_FILESYSTEM_DISK=s3_public

# --------------------------------------------
# PUBLIC S3 Settings
# --------------------------------------------
PUBLIC_AWS_SECRET_ACCESS_KEY='XXXXXXXXXXXX'
PUBLIC_AWS_ACCESS_KEY_ID='ZZZZZZZZZZZZZZZZZ'
PUBLIC_AWS_DEFAULT_REGION='us-west-2'
PUBLIC_AWS_BUCKET=snipe-flysystem-public-test
PUBLIC_AWS_URL='https://snipe-flysystem-public-test.s3-us-west-2.amazonaws.com'

# --------------------------------------------
# PRIVATE S3 Settings
# --------------------------------------------
PRIVATE_AWS_SECRET_ACCESS_KEY='XXXXXXXXXXXX'
PRIVATE_AWS_ACCESS_KEY_ID='ZZZZZZZZZZZZZZZZZ'
PRIVATE_AWS_DEFAULT_REGION='us-west-2'
PRIVATE_AWS_BUCKET=snipe-flysystem-private-test
```

**Comment by noze-gnassipova** [comment]
please try this link: https://pd1-snipeit-public.s3.ca-central-1.amazonaws.com/components/component-image-1-EmZfbrBlyy.png

**Comment by snipe** [comment]
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>VF7PZQ81VWQGQY3E</RequestId>
<HostId>
QJbwq0hjBHQBsgl0R5IyMnF+uZsbODurKA8zH8euW9mK8VUi5fVAm/HwLzTXyxHAnziijfgJN5A=
</HostId>
</Error>
```

Different error this time - it's saying I don't have permission, not that the bucket doesn't exist.

**Comment by noze-gnassipova** [comment]
the bucket is public

**Comment by snipe** [comment]
Just telling you what I see tho

**Comment by noze-gnassipova** [comment]
changed permissions, still not uploading files. Please advise, thanks

**Comment by noze-gnassipova** [comment]
i think i found the issue. Sorry for bothering you, thanks a lot

**Comment by snipe** [comment]
No bother - glad you're sorted. What was the issue?
