### ISSUE TITLE
Button is labeled "Checkout" during a Checkin Asset process (bottom right corner)

### ISSUE THREAD

**Issue by ma540x** [grokability/snipe-it#15300]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello folks,
I noticed that a button that user clicks on to perform a check-in action is labeled as Checkout.  No functionality is impaired, just a text on that button needs to say Check-in or something in that nature, if possible.

![Checkout_button_mislabeled](https://github.com/user-attachments/assets/da5a3775-8313-4298-9302-82b45cc2f66f)

### Reproduction steps

1.Login
2.Navigate to an Asset that's already Checked out (Deployed)
3.Click on Checkin button

...

### Expected behavior

The button needs to display text "Check-in" (or something in that nature), and not the current text of "Checkout" 

### Snipe-IT Version

 v7.0.10 - build 14684 (master)

### Operating System

Windows 10

### Web Server

Apache

### PHP Version

8.2.12

### Operating System

Windows 11

### Browser

Edge

### Version

126.0.2592.87

**Comment by snipe** [comment]
This was fixed a few weeks ago in https://github.com/snipe/snipe-it/commit/f44abd0b282b87b1385f2516f1b9aebde065ca3a
