### ISSUE TITLE
[Feature Request]: Include a Status drop down in the "Quick Scan Checkin" page, please.

### ISSUE THREAD

**Issue by ma540x** [grokability/snipe-it#15301]
### Is your feature request related to a problem? Please describe.

The problem is since I'm tracking Assets that are "Available To check out" vs "Checked Out", my custom statuses are "Available" and "Checked Out", but when I do a "Quick Scan Checkin" of the assets, there is no drop down for me to set those options up, so an asset that has a value of Status = Checked Out, will stay as "Checked Out" even after I perform a "Quick Scan Checkin". 

### Describe the solution you'd like

I would imagine the easier solution would be to include a drop down of different Statuses that are available (ie, user defined), but in reality what I would really love is for it to "automatically" go from status = Checked out to status = Available as soon as i checkin an asset. 

![Checkin_screen_no_status_change](https://github.com/user-attachments/assets/5017f588-f09b-4552-8c5c-c8f9f70a5fde)

But i'm not sure if that's more work on the developer, so hopefully an easier/faster fix is to just code a drop down with the status options on this screen. 

### Describe alternatives you've considered

Considered not using any custom statuses at all and seeing what happens, but since our current system uses "Available" vs "Checked Out" it would be great to use those terms (vs Deployed/Ready to deploy).   

### Additional context

This screen is awesome, and would save us tons of time, if there was a way to change the status.
Thanks!

**Comment by snipe** [comment]
We can't make the assumption of what the status label should change to, since folks can have multiple status labels of the same time. I can add a status label dropdown for you though.

**Comment by ma540x** [comment]
**Thank You!!!**
