### ISSUE TITLE
Duplicate asset number error when multiple users creating assets.

### ISSUE THREAD

**Issue by CodySD33** [grokability/snipe-it#15308]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Asset number is generated during creation of asset instead of during submission of  asset into database. When multiple users are creating an asset at the same time, the last person to submit the asset will have the submission fail due to having a duplicate assert number in the database.

### Reproduction steps

1.Have one user start an asset form
2. have another user start an asset form before the previous user has submitted
3.Have one user submit the asset to database before the other user. 
...

### Expected behavior

Asset number should be generated at time of submission to database.

### Snipe-IT Version

 v7.0.10 - build 14684 (master)

### Operating System

GNU

### Web Server

n/a

### PHP Version

8.1.29

**Comment by snipe** [comment]
This issue has been raised multiple times already. The UX is very complicated because of how different workflows work within organizations. There just isn’t an easy answer. Please check the existing issues and follow along there.
