### ISSUE TITLE
Update Label Settings issue

### ISSUE THREAD

**Issue by qu1dam** [grokability/snipe-it#15311]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Some labels throw the error: TCPDF ERROR: Error in 1D barcode string while selecting them.
Possible to see even on a demo instance
https://demo.snipeitapp.com/admin/labels

### Reproduction steps

Clicking on individual labels under Update Label Settings reports an error

### Expected behavior

labels should be displayed when selected

### Snipe-IT Version

v7.0.11

### Operating System

Ubuntu, Windows

### Web Server

Apache, IIS

### PHP Version

8.1.2 or greater

**Comment by snipe** [comment]
This is already fixed on master. If you can't update, just select the option you want instead of the default one that the page is pre-populated with.
