### ISSUE TITLE
Close Parenthesis on Expected-Checkin email.

### ISSUE THREAD

**Issue by athompson-hoho** [grokability/snipe-it#15335]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When Logo and Logo+Text are selected it adds a closing parentheses. Logo removed for security.
![image](https://github.com/user-attachments/assets/db157e00-f438-47f4-8886-78d59104ab5a)

### Reproduction steps

1. Select Logo+Text or Logo in Branding
2. Manually run php artisan snipeit:expected-checkin
3. Receive email with extra parenthesis
...

### Expected behavior

Normal behavior would be no Parentheses in header. It does not occur when branding is set to Text only.

### Screenshots

![image](https://github.com/user-attachments/assets/00c7ed40-8895-4bfc-8ae7-60bc6bd705c6)

### Snipe-IT Version

7.0.11

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

PHP 8.1.2-1ubuntu2.18

### Operating System

Windows

### Browser

Outlook

**Comment by marcusmoore** [comment]
Thanks for reporting @athompson-hoho. I'll have a fix in shortly.

**Comment by marcusmoore** [comment]
The fix is merged and will be included in the next release. Thanks again for reporting @athompson-hoho

**Comment by athompson-hoho** [comment]
@marcusmoore - Is it possible to have a fix I can apply until the next release?

**Comment by snipe** [comment]
@athompson-hoho it's on master. You can just update to latest on master.
