### ISSUE TITLE
[7.0.11] Looks like hardcoded text in Category view

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15330]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Can't figure out from where it comes, but it's in Page Title and three different tested languages.

### Reproduction steps

1. Change to other language than English
2. Open any Asset category

### Expected behavior

Text is not in English.

### Screenshots

![image](https://github.com/user-attachments/assets/7b968baf-2153-4ff7-a07a-05e1f1fe3722)
![image](https://github.com/user-attachments/assets/6ee31f94-08f3-4bc7-af1f-901b7c580e19)

### Snipe-IT Version

7.0.11

### Operating System

Ubuntu

### Web Server

apache

### PHP Version

8.3

### Operating System

Win10

### Browser

Edge, Firefox

### Version

latest

**Comment by swift2512** [comment]
Same for accessories, licences, consumables and components.
![image](https://github.com/user-attachments/assets/0d2a6b45-0921-4159-879f-fa47ea3af6ad)

**Comment by snipe** [comment]
I can't tell what page you're looking at to see this. Can you give me the url fragment(s)?

**Comment by swift2512** [comment]
Sorry, forgot to add URL. It's when you open any category of assets/accessories/etc.

http://192.168.11.215:1111/categories/1

Items count per page is missing for Lithuanian because of bootstrap-table. There's no localized version.

**Comment by snipe** [comment]
Thanks for the clarification. It is actually a translated string, but it's possible it hasn't been translated by the language volunteers yet:

https://github.com/snipe/snipe-it/blob/e8a22f3c5bf0fc22602a1373cf91090d40e9d734/resources/views/categories/view.blade.php#L6

Yeah, just confirmed with CrowdIn. No translation has been provided yet. 

<img width="1431" alt="Screenshot 2024-08-19 at 3 06 50 PM" src="https://github.com/user-attachments/assets/48dcf620-d629-4559-bda4-815ba59777a2">

**Comment by swift2512** [comment]
Will check tomorrow, but it doesn't look like it. Words are in different order. It's **category name** followed by word Assets (or Accessories, Consumables, etc.) and not like in resources/lang/en-US/general.php file.
 562 'assets_in_var' => 'Assets in :name :type'
Also, this would be valid only for assets, but as I mentioned earlier, it's same with other groups of items which can be split in categories (accessories, consumables, etc.)

**Comment by snipe** [comment]
Hard to tell - the English string I’m looking at may also be more up to date than what you’re looking at - are you on latest on master?

**Comment by swift2512** [comment]
Looks like it was older master. Pulled new version (version and buil No. stayed the same) this morning and text in Assets is correct. Yet, different strings should be used for other item groups, because now it's Assets for components, licenses, consumables. Or if it's one string, word 'Assets' should be replaced by 'Items' and then it all would make sense.
Also, some names still in English and I doubt these haven't been translated because even in Chinese, German, those words I marked in red, are in English. 
![image](https://github.com/user-attachments/assets/d3a094a5-cd4d-4119-8214-04e8f29790b8)

On a side note, your team should avoid using strings for regular words like category because it removes flexibility when translating. English as a language is very simple, but others are more complicated. Wikipedia says that English has only 3 grammatical cases and Lithuanian has seven.) For example, let's take a house.
![image](https://github.com/user-attachments/assets/c151309a-2c6e-4d46-86c3-a69fb934de8a)

So when I get string to translate **Assets in :name :type**, I can't  make it to look nice - I end up with broken Lithuanian. It would be much easier if string was **Assets in :name _category_** (Turtas kategorijoje :name) I'd say translators of other languages (Ukrainian, russian) are in the same boat as me.

**Comment by snipe** [comment]
https://crowdin.com <- getting a 403 on them right now so I can't check any further :( 

<blockquote><img src="https://d2gma3rgtloi6d.cloudfront.net/ba88ec3e/images/content/crowdin-share.png" width="48" align="right"><div><img src="/favicon-16x16.png" height="14"> Crowdin</div><div><strong><a href="https://crowdin.com">Crowdin | Localization Management Platform for agile teams</a></strong></div><div>Crowdin's localization management platform is a technology solution for your team.</div></blockquote>

**Comment by snipe** [comment]
Huh. CrowdIn isn't down, it was giving me a forbidden issue when I was running over my VPN. You'd think a company that specializes in localization would understand that people travel and use VPNs. :-/

**Comment by snipe** [comment]
> On a side note, your team should avoid using strings for regular words like category because it removes flexibility when translating.

That's why we use the `:type` variable in the translation, passing it the translated word for category. If the translators need to move those variables around in the translation to make the sentence make sense, they can (and do.)

**Comment by swift2512** [comment]
> > On a side note, your team should avoid using strings for regular words like category because it removes flexibility when translating.
> 
> That's why we use the `:type` variable in the translation, passing it the translated word for category. If the translators need to move those variables around in the translation to make the sentence make sense, they can (and do.)

If `:type` = Category, then in Lithuanian you can move this `:type` around however you want, but you will end up with broken translation.

Category = Kategorija
In the Category = Kategorij**oje**
That's why it would be better to use category instead of :type :) If string was 'Assets in :name Category' it would be already translated to 'Turtas kategorijoje :name', but I can't stray that far from the source string. :)

**Comment by snipe** [comment]
I've already simplified it per the PR that was merged
