### ISSUE TITLE
Custom text on asset checkout email

### ISSUE THREAD

**Issue by klemendlabs** [grokability/snipe-it#15334]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I want to add a custom text when I checkout an item (every item) to a user.

### Reproduction steps

1. checkout item to a user
2. only standard text is displayed

### Expected behavior

Ability to checkout item to a user

### Snipe-IT Version

 v7.0.11 build 14904 (g6c0cf9447) 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8

**Comment by snipe** [comment]
I don’t see that on the short term roadmap. It adds complexity and more UI work for something we’ve never heard requested before.

**Comment by snipe** [comment]
You could put your custom text in the EULA field of the category tho.
