### ISSUE TITLE
Asset found but not found

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#15338]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Searching all Asset, Asset found but not found.

### Reproduction steps

1.Search asset number
2. Asset is found but error comes up the top saying its not found
3.
...

### Expected behavior

Not cause error if item is actually found

### Screenshots

![Screenshot 2024-08-20 113511](https://github.com/user-attachments/assets/b59dbe22-70c9-4547-afe9-c987a30fc841)

### Snipe-IT Version

v7.0.10 build 14684 (gc2bcc2e2d) 

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8

**Comment by FlorentDotMe** [comment]
Hi, indeed this behavior was intentionally introduced in [#15217](https://github.com/snipe/snipe-it/pull/15217#discussion_r1704136786)

The top search field was initially dedicated to assets tag. Since then, the warning message appears when the search string isn't a tag, but result page list assets that have attributes (eg. SN) matching the string.

There is an ongoing discussion on the draft PR to clarify/dismiss this message: https://github.com/snipe/snipe-it/pull/15227

**Comment by jayavman** [comment]
Very confusing. Specially when it finds the asset then says it cannot find the asset. Bit of a mixed message, it either finds it or not

**Comment by snipe** [comment]
@FlorentDotMe - I did mention that I thought this behavior was a confusing UX. Perhaps we can update that language string to be more clear. "An asset with the exact match for asset tag blah could not be found, but the results below might be helpful" or some such.

**Comment by jayavman** [comment]
Issue is, What I searched is the correct match. The asset tag found and what I searched for is the exact thing. (refer to picture) I don't think your search likes # as part of the asset tag

**Comment by snipe** [comment]
@jayavman I can't reproduce this on our end, even when I add a hashtag to the asset tag.

**Comment by snipe** [comment]
You can see this on the demo:
https://demo.snipeitapp.com

search on `#364503900`


<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by jayavman** [comment]
strange its now working for me :> well ignore that then..
