### ISSUE TITLE
Can't get S3 images to upload

### ISSUE THREAD

**Issue by alitheg** [grokability/snipe-it#15343]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I've got S3 upload configured and have tested my credentials have permission to upload to the buckets in question. I upload and the request completes successfully - but no file appears in the bucket.

### Reproduction steps

I'm running in Docker on AWS ECS - I've tested that the container network interface can reach the internet, and I can't see any errors in the logs. If you can help me locate any error logs to help me find the problem it would be much appreciated!

### Expected behavior

Files should upload to the S3 bucket

### Snipe-IT Version

7.0.6

### Operating System

Linux / Docker

### Web Server

Whatever is in the docker image :) 

### PHP Version

Whatever is in the docker image :) 

### Operating System

macOS

### Browser

Arc & Firefox

### Additional context

Fresh install

**Comment by alitheg** [comment]
Just come back to this! I agree it may not be a bug (it *feels* like a config issue on my side!) but I can't for the life of me find an issue with the config nor anything in the logs to indicate a problem! I'd really appreciate if someone could point me in the direction of any further debugging I could do. I did try in Discord a couple of times no to avail (if that's my issue let me know, I'm happy to post it differently or somewhere else if I've gotten that wrong!)

**Comment by alitheg** [comment]
Ok I finally found the issue! I'd given what I thought were the correct set of permissions, but, I also had to enable ACLs on the bucket (which are disabled by default) and add PutObjectAcl permission too.

**Comment by snipe** [comment]
Excellent, thanks for the update! (Bucket ACLs are such a pain.)

**Comment by zackrspv** [comment]
Technically, this should be in the documentation.  Right now, the documentation for S3 is just the .env configurations, and that's it.  That is NOT sufficient. At the minimum, it should explain how to configure and setup both the private and public buckets, with both the proper permissions, and proper settings on the buckets. Practically every project does this, unsure as to why this one wouldn't.
