### ISSUE TITLE
labels can't display chinese

### ISSUE THREAD

**Issue by firo1603** [grokability/snipe-it#15349]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

labels can't display chinese
the same problem like this  two issues :[https://github.com/snipe/snipe-it/issues/14088](url) and [https://github.com/snipe/snipe-it/issues/14052](url)
i try to use stsongstdlight font intead the default font freesans,but it not works,see screenshots

### Reproduction steps

labels can't display chinese

### Expected behavior

labels can't display chinese

### Screenshots

![Snipaste_2024-08-20_22-47-07](https://github.com/user-attachments/assets/831a856e-bdc5-4c20-aba6-08c1810dc5aa)

### Snipe-IT Version

docker snipe/snipe-it:latest

### Operating System

include docker snipe/snipe-it:latest

### Web Server

include docker snipe/snipe-it:latest

### PHP Version

include docker snipe/snipe-it:latest

**Comment by firo1603** [comment]
Sorry, I found the mistake. There are two places that need to be changed, and the second change is wrong.
This issue can be closed

**Comment by Nagareb0shi** [comment]
> Sorry, I found the mistake. There are two places that need to be changed, and the second change is wrong. This issue can be closed

请问如何让标签正常显示中文?
![image](https://github.com/user-attachments/assets/dfd7e0e0-be23-40cd-8548-aab72e74d482)

**Comment by firo1603** [comment]
> > Sorry, I found the mistake. There are two places that need to be changed, and the second change is wrong. This issue can be closed
> 
> 请问如何让标签正常显示中文? ![image](https://private-user-images.githubusercontent.com/103474020/361630954-dfd7e0e0-be23-40cd-8548-aab72e74d482.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDcxNDcsIm5iZiI6MTcyNDgwNjg0NywicGF0aCI6Ii8xMDM0NzQwMjAvMzYxNjMwOTU0LWRmZDdlMGUwLWJlMjMtNDBjZC04NTQ4LWFhYjcyZTc0ZDQ4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwMTAwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTNjZjQ3ZjE0ODkwY2EwMGNlNGY0ZWQ1NGZlOGM3YjJmNjk2OWI3NzBmNWNmYzM1YzFhYTgwZTRmZGRjOGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5ry8ZQ3JZOmAcyJ-chth205tCf6EqyJyh71xbopXOTg)

在/var/www/html/app/Models/Labels下面是所有标签的配置（如果你是容器部署的，先进到容器里面再找到对应目录）
一般DefaultLabel.php，还有Sheets和Tapes两个文件下下面所有的*.php文件就是标签的配置，一般有两个字体，freemono和freesans都不能正常显示中文，把这两个全部替换成stsongstdlight就行
可以参考下面两条命令
`find app/Models/Labels/ -type f -name "*.php" -exec sed -i 's/freesans/stsongstdlight/g' {} +`
`find app/Models/Labels/ -type f -name "*.php" -exec sed -i 's/freemono/stsongstdlight/g' {} +`

注意下app/Models/Labels/路径不要错，建议路径写成/var/www/html/app/Models/Labels

**Comment by Nagareb0shi** [comment]
> > > Sorry, I found the mistake. There are two places that need to be changed, and the second change is wrong. This issue can be closed
> > 
> > 
> > 请问如何让标签正常显示中文? ![image](https://private-user-images.githubusercontent.com/103474020/361630954-dfd7e0e0-be23-40cd-8548-aab72e74d482.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDcxNDcsIm5iZiI6MTcyNDgwNjg0NywicGF0aCI6Ii8xMDM0NzQwMjAvMzYxNjMwOTU0LWRmZDdlMGUwLWJlMjMtNDBjZC04NTQ4LWFhYjcyZTc0ZDQ4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwMTAwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTNjZjQ3ZjE0ODkwY2EwMGNlNGY0ZWQ1NGZlOGM3YjJmNjk2OWI3NzBmNWNmYzM1YzFhYTgwZTRmZGRjOGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5ry8ZQ3JZOmAcyJ-chth205tCf6EqyJyh71xbopXOTg)
> 
> 在/var/www/html/app/Models/Labels下面是所有标签的配置（如果你是容器部署的，先进到容器里面再找到对应目录） 一般DefaultLabel.php，还有Sheets和Tapes两个文件下下面所有的*.php文件就是标签的配置，一般有两个字体，freemono和freesans都不能正常显示中文，把这两个全部替换成stsongstdlight就行 可以参考下面两条命令 `find app/Models/Labels/ -type f -name "*.php" -exec sed -i 's/freesans/stsongstdlight/g' {} +` `find app/Models/Labels/ -type f -name "*.php" -exec sed -i 's/freemono/stsongstdlight/g' {} +`
> 
> 注意下app/Models/Labels/路径不要错，建议路径写成/var/www/html/app/Models/Labels


非常感谢您的指导，我替换为freemono字体，中文可以正常显示，再次感谢！
