### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by infotronicx** [grokability/snipe-it#15354]
### Is your feature request related to a problem? Please describe.

In Snipe-IT, only users with the global admin role have full administrative privileges, including the ability to import data and manage settings across the entire system. Group admins have more limited permissions, which typically allow them to manage assets, users, and licenses within their assigned groups but not to perform system-wide administrative tasks such as importing data or changing system settings. Also can not delete the owner user.

### Describe the solution you'd like

Custom Role Creation (If Available): Depending on the version of Snipe-IT you're using, you may have the ability to create custom roles with specific permissions. You can create a role that includes the permissions for importing data and managing settings and assign it to the necessary users.

Delegate Specific Tasks to a Global Admin: If you want to limit the number of global admins, you can keep the user as a group admin and have them work closely with a global admin who can perform the imports and manage settings as needed. This ensures that the group admin focuses on their designated tasks while still having access to necessary resources through collaboration. Also can not delete the owner user.

### Describe alternatives you've considered

Modify Code (Advanced): If you are comfortable with coding and have the technical expertise, you could modify the Snipe-IT codebase to grant additional permissions to group admins. However, this approach requires a deep understanding of the software and might complicate future updates.

**Comment by snipe** [comment]
This is not correct. There is a separate CSV import permission that can be granted to non-admins.
