### ISSUE TITLE
windwos系统部署7.0.11默认语言不生效。

### ISSUE THREAD

**Issue by flzt-aox** [grokability/snipe-it#15353]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

.env文件配置项为简体中文APP_LOCALE=zh-CN。登陆系统默认是英语。在系统设置里修改语言也简体中文，退出登陆，清空浏览器缓存，重启服务器，再登陆还是英文。

### Reproduction steps

1.登陆系统。
2.在设置项[Localization]-Default Language-chinese simplified
3.保存
4.退出登陆
5.清空浏览器缓存
6.重启服务器
7.登陆系统，还是英文
![登陆1](https://github.com/user-attachments/assets/2fca7d4a-fbe8-4f49-a35a-62776cb4326e)
![登陆2](https://github.com/user-attachments/assets/254d3f9e-3fee-4571-ba8d-22dcb593a361)
![登陆3](https://github.com/user-attachments/assets/d3015414-6fd6-4e6d-8010-664610e0e432)

...
![登陆4](https://github.com/user-attachments/assets/baa4710f-95c3-4685-a00a-1ee0db7c401e)

### Expected behavior

希望修改默认语言为简体中文

### Snipe-IT Version

7.0.11

### Operating System

windows 2016

### Web Server

apache

### PHP Version

8.2.12

### Operating System

windows 2016

### Browser

Google Chrome

### Version

 127.0.6533.73

### Additional context

这是全新安装的windows操作系统。
在windows2016服务器上部署安装，在服务器本机上登陆snipe-it
通过xampp安装

**Comment by flzt-aox** [comment]
通过编辑个人用户的个人资料来为这些用户设置语言。保存后，系统语言改为简体中文。
![登陆5](https://github.com/user-attachments/assets/5b06acfc-5b0d-434f-bd9e-f011c4aa6c3e)

**Comment by snipe** [comment]
Translation:

```
The configuration item of .env file is Simplified Chinese APP_LOCALE=zh-CN. The default login system is English. Change the language in the system settings to Simplified Chinese, log out, clear the browser cache, restart the server, and log in again in English.

Reproduction steps

1. Login to the system.
2.In the setting item [Localization]-Default Language-chinese simplified
3.Save
4. Log out
5. Empty your browser cache
6.Restart the server
7.Login to the system, still in English

Translated with DeepL.com (free version)
```

@flzt-aox  - please open issues in English. We're providing free support here, so it's not fair to force us to run our responses through a translator just to help you. 

I can't reproduce this. Is there anything in your app logs?
