### ISSUE TITLE
The ")" character next to the Email Logo is notified when checking in or checking out.

### ISSUE THREAD

**Issue by thanhhai14** [grokability/snipe-it#15355]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When sending an email to a user, I see the ")" character next to the Logo.
This error is caused by a code error in the "resources\views\vendor\mail\html\message.blade.php" folder
@if (($snipeSettings->show_images_in_email=='1') && ($snipeSettings->email_logo!='') && $snipeSettings->brand != '1'))

The correct code should be
@if (($snipeSettings->show_images_in_email=='1') && ($snipeSettings->email_logo!='') && ($snipeSettings->brand != '1'))

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Hope someone fixes it soon

### Screenshots

![image](https://github.com/user-attachments/assets/18b08685-0368-4532-9fd0-b45c227e535c)

### Snipe-IT Version

7.0.11

### Operating System

Windows Server

### Web Server

IIS

### PHP Version

8.1.2

### Operating System

Windows 11

### Browser

Google Chrome

**Comment by snipe** [comment]
This has already been fixed in https://github.com/snipe/snipe-it/pull/15336. Please check GH issues before opening a new issue.
