### ISSUE TITLE
[Feature Request]: Encrypted fields visibility for Non-Admins

### ISSUE THREAD

**Issue by r-xyz** [grokability/snipe-it#15366]
### Is your feature request related to a problem? Please describe.

Currently encrypted fields are only viewable and editable by users with admin role.
![image](https://github.com/user-attachments/assets/f27cdaed-af13-4fe4-b7a7-be16918ec678)
Nonetheless, granting admin role will also grant all other permissions.

### Describe the solution you'd like

A better granularity would be desirable, so managers could for example add new assets (filling also encrypted fields) but cannot edit Users.

A possible solution would be to add additional permissions for encrypted fields, similar to "Custom fields"
![image](https://github.com/user-attachments/assets/8e36a1d5-6dc2-4284-a3e2-8c5dba7efe78)

**Comment by snipe** [comment]
Ability to view and edit encrypted custom fields is set on the asset permission.
<img width="817" alt="Screenshot 2024-08-22 at 9 49 34 AM" src="https://github.com/user-attachments/assets/60315612-84b3-4ee1-b570-053282dbe43a">

**Comment by r-xyz** [comment]
Thanks @snipe  for the quick reply. You are right, I should have double checked. Then I am afraid it is a bug report.

Users with those permissions enabled can view the encrypted fields and copy them, but they cannot edit them.

When editing an asset, the value is showed in the corresponding field. Though if they modify and save,  no error is shown, but the field is not updated.

Asset view detail:
![image](https://github.com/user-attachments/assets/9bced869-9265-443d-b0a9-f9e75b658601)
Asset view edit detail:
![image](https://github.com/user-attachments/assets/e4cca0e9-df03-4c41-b73d-72fc73c017ba)

**Comment by r-xyz** [comment]
## Steps to reproduce

1. Create a non-admin user and give it all asset permissions
2. Create an asset with at least one encrypted field
3. Login as the user. Verify the encrypted field is viewable.
4. Edit the asset encrypted fields. Save. Verify it succeed.
5. Reopen the edit view. Verify the value has not changed.

**Comment by r-xyz** [comment]
Shall I close and reopen as bug report?

**Comment by swift2512** [comment]
Can confirm on pulled newest master. If user isn't set as admin, his edits of encrypted fields doesn't save. In debug mode could find errors or warnings.

**Comment by r-xyz** [comment]
Thanks again! :) Looking forward for next release!
