### ISSUE TITLE
View Asset Page does not show checkout/in button

### ISSUE THREAD

**Issue by Zer0Blues** [grokability/snipe-it#15378]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

While viewing an asset as at least non-super admin on the View Asset xxx info tab, the Checkout/in Button is missing under the device picture.  The user has the permission to view/checkout/in assets and can still checkout/in device from the List all assets pages.

### Reproduction steps

1. View an asset by clicking from the asset list or search.
2. 
3.
...

### Expected behavior

Expect the checkout/in button to be shown under the device picture as it did before.

### Snipe-IT Version

7.0.11

### Operating System

Debian

### Web Server

Apache

### PHP Version

8.3.9

### Operating System

Windows

### Browser

Google Chrome

### Version

127

**Comment by snipe** [comment]
I'm not seeing this behavior with the checkout button, only the checkin button.
