### ISSUE TITLE
[Feature Request]: Generate Label Button Move Request

### ISSUE THREAD

**Issue by brianhoganm** [grokability/snipe-it#15388]
### Is your feature request related to a problem? Please describe.

Hi @snipe I LOVE the new buttons that you and your team have created when viewing the asset. I like the new icons! I was wondering if it would be possible to relocate the **Generate Label** button under the Close Asset button? This way we don't have to scroll all the way down the page to click on Generate Label. 

What do you think? I was thinking it would be nice to have it consistant. 

![Screenshot 2024-08-23 101022](https://github.com/user-attachments/assets/5be18f20-f594-4b80-ab7e-fa92bfa374da)

### Describe the solution you'd like

Relocate the Generate Label button

### Describe alternatives you've considered

None really...

**Comment by snipe** [comment]
All set

**Comment by brianhoganm** [comment]
AWESOME!! Thank you so much. Really appreciate it. Button looks great.
Brian
