### ISSUE TITLE
400 Bad Request when adding new asset

### ISSUE THREAD

**Issue by jtorSEVENP** [grokability/snipe-it#15382]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I try to add a new asset I get a 400 bad request error and the page shows a blank page with just "ERROR: "

### Reproduction steps

1. Create new asset with an existing model and no custom fields

### Expected behavior

A new asset would be created

### Screenshots

![image](https://github.com/user-attachments/assets/d8a5502c-faca-4447-b9ac-4c0a40f39f23)

### Snipe-IT Version

v7.0.11 build 15044 (g46ed07642)

### Operating System

22.04.4 LTS (Jammy Jellyfish)

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

Windows

### Browser

Microsoft Edge

### Version

127.0.2651.105

### Error messages

```shell
No error is logged is storage/logs

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

It is an upgrade from a rather old version. Started on 6.0.13 in docker and switched to a git install. After that I upgraded to 6.0.14 and after that I upgraded to the latest version.
I have optimized some tables in mysql ( due to max size limits) and upgraded the mysql server to the latest lts. 

Also when I want to edit an asset model with custom fields I get a 404

**Comment by snipe** [comment]
I can't reproduce this on the demo or locally. Is this a recent upgrade or install? Have you tried this solution? https://snipe-it.readme.io/docs/common-issues#400-error-header-too-large

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues#400-error-header-too-large">Common Issues</a></strong></div><div>🚧 Problem Installing/Upgrading?: We've moved the the most common installation/upgrade issues to their own page. If you're having an issue installing or upgrading Snipe-IT, please check the Installation/Upgrading Issues page before opening a ticket on Github . Quick Tip: Handy Commands 👍 Many issue...</div></blockquote>

**Comment by jtorSEVENP** [comment]
It is a recent upgrade indeed. I have tried that solution but adding it to my .env does not seem to change the setting

**Comment by jtorSEVENP** [comment]
It seems that it changes depending on the asset model I choose

**Comment by jtorSEVENP** [comment]
Ok, this is a weird continuation. I have tried Firefox for maybe better debugging. Which I got, it showed me an error Attempt to read property "location_id" on null.

But now when I add an asset on my normal situation it seems to be capable of adding assets again. Could this be something weird in the database on that specific asset tag id? 

Adding custom fields to asset models now also seem to work for the model that didn't work before.

I am going to do some additional testing by adding new assets

**Comment by snipe** [comment]
> It is a recent upgrade indeed. I have tried that solution but adding it to my .env does not seem to change the setting

You might need to run `php artisan config:clear` to have those settings kick in.

**Comment by jtorSEVENP** [comment]
Yes, that was indeed the fix for the table storage. I have added a couple of assets now and created a new model. 

My guess is that there was an invalid entry in my assets library and that might have caused some issues. I think that adding it a new asset with Firefox changed the produced call a bit because it also returend a proper error page. 

For now I will close this issue. Thank you for the fast response
