### ISSUE TITLE
[Feature Request]: SnipeIT Bulk Audit

### ISSUE THREAD

**Issue by Vitalmeid** [grokability/snipe-it#15386]
### Is your feature request related to a problem? Please describe.

Hey,

When I'am doing an audit on SnipeIT scanning my assets i found something interesting, if I scan the same assets a lot of  times the tool still counting, on the attached image I scanned the same asset four times and audit still showing the same message " Asset audit successfully logged". In my opinion it should be better be advised that I´ve already scanned that asset. There is any kind of configuration or something to do about that?
![Captura de tela 2024-08-23 113401](https://github.com/user-attachments/assets/1daf5f89-73ea-40fd-83c2-46b2b47ac483)

### Describe the solution you'd like

I think that should be much better if the tool shows the message "asset already been scanned" for that location.

**Comment by snipe** [comment]
We allow that because we cannot assume how often and for what reason people audit.
