### ISSUE TITLE
Assets are displayed incorrectly under “unaccepted assets”

### ISSUE THREAD

**Issue by OneFairySins** [grokability/snipe-it#15395]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Assets that have been issued to locations but are incorrectly marked as issued to employees are displayed under “Unaccepted assets”.

### Reproduction steps

Figure 1 shows the asset that was incorrectly issued under “unaccepted assets”.
Under picture 2 you can see under the asset that it was given out to a location

![2](https://github.com/user-attachments/assets/ea356913-edb4-462d-82d0-7710471f71e5)
![1](https://github.com/user-attachments/assets/eee1bfcc-7446-47cf-93cb-787a4efc944d)

### Expected behavior

This should state that the asset was issued to the location and not to the employee.

### Snipe-IT Version

 v6.1.2

### Operating System

Windows

### Web Server

?

### PHP Version

?

**Comment by snipe** [comment]
You're running a pretty old version. I think that issue was fixed a long time ago. You should consider upgrading.
