### ISSUE TITLE
[Feature Request]: Transfer of assets' assigned assets to another target

### ISSUE THREAD

**Issue by tmbottegal** [grokability/snipe-it#15390]
### Is your feature request related to a problem? Please describe.

My standard workflow for my employees is to check out assets to vehicles (also assets) when loading, then once a vehicle leaves the warehouse, check out the vehicle asset to the desired location. This works for almost all cases, as in most cases our vehicles do not leave the job site until completion, and can be returned to the warehouse. The edge case is when vehicles drop off assets to a location or one vehicle's assigned assets are transferred to another. When this happens, we must first check in the assets, then check it out to the new target, per asset. This can get quite frustrating when given a large number of assets.

### Describe the solution you'd like

On the "/hardware/_[number]_#assets" page; an option to transfer the target's assigned assets to another user, asset, or location. This would unassign the assets from the target asset, and assign them to the second selected target.

### Describe alternatives you've considered

I've attempted to use a script to push the changes via the API as a temporary solution, but my employees do not have the know-how on how to use it and oftentimes do not update the assignment, which causes quite the headache for me.

### Additional context

Thank you!

**Comment by snipe** [comment]
Duplicate of #5834
