### ISSUE TITLE
Can no longer create asset models with duplicate asset model names

### ISSUE THREAD

**Issue by jlewis-mma** [grokability/snipe-it#15405]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Due to the way labels printer, we have always used generic asset model names for devices like Dell laptops. The asset model name is simply Dell and the asset model # is the model number. We have dozens of asset models created like this. 

Since upgrading to 7.0.114 we can no longer create new asset models using this approach, and we are unable to update existing asset models.

### Reproduction steps

1. Go to Settings > Asset Models > Create new Asset Model
2. Enter the asset model name matching an existing asset model name
3. FIll out the rest of the record and submit
...

### Expected behavior

I would expect this to create anew asset model name with a same name but different model # 

### Snipe-IT Version

7.0.11

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

Windows

### Browser

Google Chrome

### Version

127.0.6533.120

**Comment by snipe** [comment]
That was a bug - you were not supposed to be able to create duplicate models. You can create duplicates if and only if they have different model numbers.

**Comment by jlewis-mma** [comment]
Hi! Sorry, I probably didn't make it clear on my end, so I apologize for that. Even when we make different asset model numbers, it still wont allow duplicate names. 

The issue we run into when we put unique names is that the labels print funny. For example, if we put the Asset model name as "Dell Latitude 5510" and the model # as 5510, the label printers out as "Dell Latitude 5510 5510" but if we put the asset model name as "Dell" and the Asset Model Number as "Latiutude 5510", it will print correctly as "Dell Latitude 5510"

![image](https://github.com/user-attachments/assets/26798474-51ad-4087-bfbe-a1da003348ab)

![image](https://github.com/user-attachments/assets/ca0dfb60-89dc-451c-9c98-c324b415087d)

What I am finding is that the Model Name can no longer be duplicated, but the Model # can be:

![image](https://github.com/user-attachments/assets/15e12c72-872b-41e8-b617-a6ded6af2bdb)

**Comment by jlewis-mma** [comment]
@snipe (Taggingyou since IDK if you will get notice since this issue is closed)

**Comment by snipe** [comment]
I’m afk at the moment but will check later

**Comment by snipe** [comment]
Do you have any deleted models with the same name?

**Comment by jlewis-mma** [comment]
We just have a few deleted asset models that used the old convention (Dell LAtitue vs. Dell) but nothing that matches what you see in the screenshots above. 

![image](https://github.com/user-attachments/assets/4b39e4d6-1a0b-48fd-9056-73998b60537e)

**Comment by snipe** [comment]
I cannot reproduce this on the demo.
https://demo.snipeitapp.com/models?page=1&size=20&order=asc&search=dell

<img width="1439" alt="Screenshot 2024-08-29 at 11 52 59 AM" src="https://github.com/user-attachments/assets/579a30dc-583c-4fbc-9128-b037d57be437">

**Comment by touchsuite-it** [comment]
We have the same issue - also seems to have started in the last week. Same exact steps and behavior as above. No deleted asset models.

**Comment by snipe** [comment]
@touchsuite-it as long as the model numbers are the same, you should be able to create duplicate model names - the combination of name and model number is thew uniqueness

**Comment by touchsuite-it** [comment]
Yeah - confirmed the model name/number combo is unique. I just saw https://github.com/snipe/snipe-it/issues/15419 and we're on build 14904. Hopefully bump to 15044 fixes it.

**Comment by touchsuite-it** [comment]
Confirmed build 15044 fixes this issue. Thanks!
