### ISSUE TITLE
[07.0.11]Can't select multiple locations if it has assets assigned

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15406]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Not sure if it's bug or a feature, but it's annoying. I'd like to export list of all my locations, but can't select them all because they have assets assigned to them. Bellow is screenshot from SnipeIT demo.
![image](https://github.com/user-attachments/assets/f15208dd-bdbe-4a8f-a24d-b02b83879111)

### Reproduction steps

1. Have multiple locations.
2. Assign assets to that location (or add user with assets to that location)
3. Press "select all" checkbox.
4.
...

### Expected behavior

SnipeIT selects all locations in the list after you press checkbox to select all.

### Snipe-IT Version

Version v7.0.11 - build 15044 (master)

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.3

### Operating System

Windows 11

### Browser

Edge, Firefox

### Version

Latest

**Comment by snipe** [comment]
Not sure I understand - they don't need to be selected to export them, they just have to be visible on the page.

**Comment by swift2512** [comment]
My bad. Didn't think about that.
