### ISSUE TITLE
[Feature Request]:  License Type Indicator (per user / per machine).

### ISSUE THREAD

**Issue by DaMa-IT** [grokability/snipe-it#15438]
### Is your feature request related to a problem? Please describe.

When adding licenses to Snipe-IT, there is currently no explicit way to indicate whether the license is for individual users (per user) or for machines (per machine). This can lead to confusion and potential errors in license management, especially when dealing with mixed license types.

### Describe the solution you'd like

Introduce a new field or option in the license creation/editing process to clearly specify the license type. This could be implemented as:

A dropdown menu: With options for "Per User" and "Per Machine."
A checkbox: Indicating "Per User" or "Per Machine."
A separate field: Where users can enter "Per User" or "Per Machine."

**Comment by snipe** [comment]
You could probably handle that via categories, no?

**Comment by DaMa-IT** [comment]
Hi Snipe, thank you for getting back to me. 
I've just tried to categorize it but im only allowed to use one category column. so category wont work in this use case. 

Regards

**Comment by DaMa-IT** [comment]
![image](https://github.com/user-attachments/assets/9c3b6fc6-311b-4fb8-b7db-72243e045ac0)
We're currently using the Notes field to distinguish between user / machine license. and category is used to distinguish between MAC or Windows.

**Comment by snipe** [comment]
If you changed the way you use categories, I still think categories could work here.

Instead of "Adobe Software (Win)", you could use "Win - Per Machine",  "Win - Per User", etc,  as the Adobe part is already addressed by way of the name of the software and the Manufacturer.
