### ISSUE TITLE
Still error in labelling engine: TCPDF ERROR: Error in 1D barcode string

### ISSUE THREAD

**Issue by davisrael** [grokability/snipe-it#15436]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

C128 barcode generation fails on new labelling engine with error `TCPDF ERROR: Error in 1D barcode string`

### Reproduction steps

1. Have new labelling engine activated
2. Have 2D and 1D barcodes displayed, 1D in C128
3. Have asset tags according to the pattern 'AA-1234'
4. Open an asset's details view
5. Press 'Generate Label' Button

### Expected behavior

Label is being displayed.

### Snipe-IT Version

 v7.0.11 - build 14904 (master)(hosted)

### Operating System

hosted

### Web Server

hosted

### PHP Version

hosted

### Operating System

MacOS 14.6.1

### Browser

Google Chrome

### Version

128.0.6613.114 (Official Build) (arm64)

### Error messages

```shell
TCPDF ERROR: Error in 1D barcode string
```

### Additional context

- This relates to https://github.com/snipe/snipe-it/issues/13472.
- Other than stated there, C128 is also supporting i.e. the - character, not just alphanumerics (see [https://en.wikipedia.org/wiki/Code_128](https://en.wikipedia.org/wiki/Code_128) , [https://en.wikipedia.org/wiki/ASCII](https://en.wikipedia.org/wiki/ASCII), [https://github.com/tecnickcom/tc-lib-barcode](https://github.com/tecnickcom/tc-lib-barcode).
- Feature broke around August 16th for web hosted.
- Reverting to old labelling engine is not an option. We spent plenty of time already for migration after the introduction of the new labelling engine broke the functionality for the  old one in our instance, we can't keep on moving back and forth

**Comment by snipe** [comment]
@davisrael  if you're hosted with us, please open a ticket at support@snipeitapp.com and we'll get the patch released to you.

**Comment by davisrael** [comment]
Thx @snipe , will do.

**Comment by davisrael** [comment]
I can confirm this to be fixed with v7.0.11 - build 15044 (master)
Thank you!

**Comment by sarhaynes** [comment]
I was still having this problem in v7.0.12 after upgrading from v7.0.6.  What I found I needed to do to correct the problem is to go into Settings/Labels and hit "Save" (I did not change any settings).  Once I did that the problem went away.
