### ISSUE TITLE
Healthcheck should fail when database connection fails

### ISSUE THREAD

**Issue by mueller-ma** [grokability/snipe-it#15439]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Sometimes the connection to MySQL fails, which causes the setup page to be shown:
![grafik](https://github.com/user-attachments/assets/380ef95f-4cd0-444f-9a3f-544cf8b067d2)

Restarting the container fixes the issue, so it could be fixed by Docker health check. However the http endpoint `/health` still returns `{"status":"ok"}` when the database isn't connected.

### Reproduction steps

1. Wait until database connection issues
2. Open https://snipeit.example.com/health

### Expected behavior

`{"status":"database failed"}` or similiar, but not `ok`.

### Snipe-IT Version

6.3.3

### Operating System

Docker 26

### Web Server

from Docker image

### PHP Version

from Docker image

**Comment by snipe** [comment]
Hi @mueller-ma - I have a PR up for this at https://github.com/snipe/snipe-it/pull/15601, but I'm not sure if my solution will work for you. Is there a way for you to test it?

**Comment by mueller-ma** [comment]
I cannot trigger this issue and it doesn't happen often, so I cannot really test it. From looking at the code in the PR it seems fine, so maybe merge and see if the issue appears again?
BTW: I cannot update due to #14820.
