### ISSUE TITLE
v7.0.11 API PATCH User - MethodNotAllowed

### ISSUE THREAD

**Issue by ptn-aviation** [grokability/snipe-it#15435]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I try to PATCH a user via API call, I receive:

{"status":"error","messages":"Method not allowed","payload":null}%

This happens since Version v7.0.11

### Reproduction steps

1. execute curl:
```
curl -X PATCH "https://snipeit.domain/api/v1/users/123" \
-H "Authorization: Bearer TOKEN" \
-H "accept: application/json" \
-H "Content-Type: application/json" \
--data '{
    "activated": "1"
}' \
--max-time 300
```

2. Receive error response:
`{"status":"error","messages":"Method not allowed","payload":null}`

### Expected behavior

It should return 200 ok

### Snipe-IT Version

v7.0.11

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

snipe/snipe-it latest Docker Image

**Comment by snipe** [comment]
This was already fixed on develop and master

**Comment by snipe** [comment]
Ah, actually, maybe not - checking further now
