### ISSUE TITLE
PHP Version Error

### ISSUE THREAD

**Issue by larrygyamfi** [grokability/snipe-it#15456]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to update SnipeIT to the latest version using php upgrade.php script, the process fails at step 2 with the message of an incompatible version of PHP. The version displayed in the error message does not match with the version that is installed on the machine and the version that is displayed on our SnipeIT instance.

### Reproduction steps

1. Open Powershell
2. Navigate to web root folder
3. run php
...

### Expected behavior

I expected the upgrade process to continue uninterrupted like our previous upgrades.

### Screenshots

Error:
![image](https://github.com/user-attachments/assets/98455ec9-206c-4eb2-b42c-f077bff725a3)

IIS:
![image](https://github.com/user-attachments/assets/72fff990-86c7-4a8c-848c-25e5a27275af)

SnipeIT:
![image](https://github.com/user-attachments/assets/14030c63-ad55-4944-93f5-f980315ec35f)

### Snipe-IT Version

6.3.0

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

8.1.27

### Error messages

```shell
No Error Messages

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
fileinfo
filter
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
sodium
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib
```

### Additional context

Upgrade

**Comment by snipe** [comment]
Check that your command line version of PHP is 8.1.x as well. `php -v`

**Comment by larrygyamfi** [comment]
Thank you, i ran php -v and got PHP 8.0.27. How would i go about updating the command line?

**Comment by snipe** [comment]
I don't really use Windows, but this tutorial seems like it's pretty up to date.
https://www.tutorials24x7.com/php/how-to-install-php-8-on-windows

<blockquote><img src="https://www.tutorials24x7.com/sites/default/files/blog-banner/2024-07/php_8.webp" width="48" align="right"><div><img src="/themes/custom/tutorials24x7/images/favicon/favicon-96x96.png" height="14"> Tutorials24x7</div><div><strong><a href="https://www.tutorials24x7.com/php/how-to-install-php-8-on-windows">How To Install PHP 8 On Windows | Tutorials24x7</a></strong></div><div>Unlock the full potential of PHP 8 on your Windows system with our comprehensive guide. Master the installation process and start coding efficiently today.</div></blockquote>

**Comment by larrygyamfi** [comment]
That did it. Thank you!
