### ISSUE TITLE
Import Issue "Not Found The requested URL was not found on this server."

### ISSUE THREAD

**Issue by Biki-69** [grokability/snipe-it#15461]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Geeting Error 

Not Found
The requested URL was not found on this server.

Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.1.25 Server at localhost Port 80

### Reproduction steps

1. download a sample .csv template from documentation section.
2. clicked on "select file" and selected the sample .csv file for import.
3. 
4.
...

### Expected behavior

The sample assets .csv should be imported into the asset register. Instead, there was a problem with the file not uploading and the previous imported file not being removed. 

### Screenshots

![Screenshot 2024-09-08 233102](https://github.com/user-attachments/assets/b0516c04-2ef1-48c0-a7c8-25fe443d1e2e)
![Screenshot 2024-09-08 233232](https://github.com/user-attachments/assets/2c596181-6e40-4fb6-8189-887bf43d46f8)

### Snipe-IT Version

7.0.11

### Operating System

Windows 10

### Web Server

Apache

### PHP Version

8.0.25

### Operating System

Windows

### Browser

Chrome

### Version

128.0.6613.120

### Additional context

It is my first time installing this, and it is a fresh installation. After hearing about this app on YouTube, I decided to give it a try.

**Comment by snipe** [comment]
This seems like it's been asked and answered several times here. 

1. Are you running this in a subdirectory?
2. What is your `APP_URL` in your `.env`  versus the URL you access the app with in a browser?
3. Do you have a value for `LIVEWIRE_URL_PREFIX` in your `.env`, [per the docs](https://snipe-it.readme.io/docs/configuration#optional-misc)?

**Comment by Biki-69** [comment]
1. The program is running in a  subdirectory.
2.  **.env** (APP_URL=http://localhost/snipe-it/public ) and **the browser url** (http://localhost/snipe-it/public/)
3. LIVEWIRE_URL_PREFIX value was set to null.


current value of **LIVEWIRE_URL_PREFIX** has been set to **/snipe-it/public** .

After assigning the value (**LIVEWIRE_URL_PREFIX=/snipe-it/public**), issue has been fixed.
