### ISSUE TITLE
[bug] TCPDF ERROR: Error in 1D barcode string after updating to v7-latest

### ISSUE THREAD

**Issue by cobyteskb** [grokability/snipe-it#15467]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When generating a asset label, the following error is shown:

`TCPDF ERROR: Error in 1D barcode string`

We're using the docker image "snipe/snipe-it:v7.0.11"

### Reproduction steps

1. Generate label for asset

### Expected behavior

Label with barcode/QRcode should be generated

### Screenshots

![Screenshot 2024-09-09 at 16 48 48](https://github.com/user-attachments/assets/1ed5b67a-7e08-431c-a453-7ee0e65681f7)

### Snipe-IT Version

7.0.11

### Operating System

Docker

### Web Server

Docker

### PHP Version

Docker

**Comment by snipe** [comment]
This was fixed several weeks ago
