### ISSUE TITLE
permission issue in latest version

### ISSUE THREAD

**Issue by rohanshastri-vyom** [grokability/snipe-it#15477]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

users with deny access to edit, create, delete are able to edit, create and delete assets

### Reproduction steps

1. grant super user access
2. deny admin access
3. set deny access to edit button in all other options.
4. users are still able to edit the assets
5.
6.
...

### Expected behavior

users with deny access should not able to edit, create or delete assets.

### Screenshots

![snipeit permissions](https://github.com/user-attachments/assets/ff03992d-5cbd-44ec-9a9d-c04b829d680a)

### Snipe-IT Version

7.0.11

### Operating System

CentOS 9

### Web Server

Nginx

### PHP Version

8.3

### Operating System

Windows 11

### Browser

Chrome

### Version

128

**Comment by swift2512** [comment]
Can't reproduce that on my test machine - edit button is greyed out.
![image](https://github.com/user-attachments/assets/f8c99594-d15f-4af4-8270-23577c87e504)

In your screenshot I see Super User is checked. It overrides every other lesser settings. You should read SnipeIT documentation to understand how things work. If you have many users, you should create different user groups and assign permissions to them.

**Comment by rohanshastri-vyom** [comment]
If I remove super user access, user is unable to view dashboard and all assets, he is able to view only few assets while user with super user access can list all assets in tool.

**Comment by swift2512** [comment]
> If I remove super user access, user is unable to view dashboard and all assets, he is able to view only few assets while user with super user access can list all assets in tool.

Here's a good read to understand permissions - https://snipe-it.readme.io/docs/permissions

Superuser should be used only for initial setup and some major configurations, not for daily use. If user is granted **superuser**, you then can't deny any other permissions.
Admins ad regular users can only see items in their company and can't belong to multiple companies.

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/permissions">Permissions</a></strong></div><div>Snipe-IT provides two privileged user account tiers, Admin and Superadmin, and a wide variety of more granular permissions for non-admin/non-superadmin users. Role Permission Superadmin Can edit ALL admin settings, create new Groups, Locations, Status Labels, etc, and is NOT constrained by Company s...</div></blockquote>
