### ISSUE TITLE
Purchase cost, EoL and audit dates shouldn't be visible to everyone

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15489]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Purchase cost, EoL date and audit dates are visible to all users. I think that this information shouldn't be visible to regular users by default.
![image](https://github.com/user-attachments/assets/b8e106d6-93d6-4f6f-9078-3f96e1571d1d)

### Reproduction steps

1. Open ['Assigned assets'](https://demo.snipeitapp.com/account/view-assets#asset) View.
2. Check 'Columns' list.

### Expected behavior

Mentioned data shouldn't be visible to everyone.

### Snipe-IT Version

v7.0.11

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.3

### Additional context

It may be tricky, because not every admin has Admin permission granted (my admins are regular users with Write/Read permissions, but no Admin). Because of that, this mentioned data can be made visible only to users bearing Superuser or Admin permissions.

**Comment by snipe** [comment]
This is already a permission as of 2022. https://github.com/snipe/snipe-it/pull/12242

<img width="864" alt="Screenshot 2024-09-11 at 9 36 53 AM" src="https://github.com/user-attachments/assets/c3c4b331-9ba4-4ccb-8148-a067109eb065">
