### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'enable_sounds' in 'field list'

### ISSUE THREAD

**Issue by ma540x** [grokability/snipe-it#15499]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Noticed this after upgrading to the latest build of Snipe (v7.0.12), but basically going into "Edit Your Profile" and making any change (Try to upload an image, phone#, site, etc) will result in the error about **SQLSTATE[42S22]: Column not found: 1054 Unknown column 'enable_sounds' in 'field list'** 

### Reproduction steps

1. Login into snipe-it
2.Click on your name in top right drop down
3.Click on Edit Your Profile
4. Make any update (image/phone#/website, etc)
5. Click on Save
...

### Expected behavior

No errors are displayed and the profile is saved with image/phone#/website.  Currently getting an error about enable_sounds column not existing. Tried to perform php artisan migrate, that didnt help.

### Screenshots

![Column_not_found](https://github.com/user-attachments/assets/d233a486-113f-4b96-baea-c4e1c4b4822e)

### Snipe-IT Version

v7.0.12

### Operating System

Windows 11

### Web Server

Apache 2.4

### PHP Version

8.2.12

### Error messages

```shell
update `users` set `enable_sounds` = 0, `enable_confetti` = 0, `users`.`updated_at` = 2024-09-12 14:55:40 where `id` = 1

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'enable_sounds' in 'field list'
```

### Additional context

Upgrade from v7.0.11 to v7.0.12, although to be frank i don't know if this is a new issue or not. 

I'm running XAMPP on Windows with MySQL

**Comment by snipe** [comment]
Did you run migrations?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
