### ISSUE TITLE
Keeps asking login when click anything

### ISSUE THREAD

**Issue by NHVIT** [grokability/snipe-it#15495]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When i login solo i dont get any problems.
When somebody else in the same network logs in, the system starts to go bug and you need to login everytime you click something (new link).
SAML was active and i thought it was the issue so i disabled this but with the normal login the behaviour is the same.

You cant checkin or checkout assets, you cant change settings or anything it just keeps asking login.

The Snipe IT instance is located in a docker behind a reverse proxy. 

Strange thing aswell is when i am logged in and another person wants to login they are logged in as me :/ 

No idea what we could do about this.
Don't really see something in the laravel logs...

### Reproduction steps

1. Log in from same network to snipe it in docker on same network
2. Let somebody else login
3. Keeps asking to login again
...

### Expected behavior

Well i would love that everybody has his own login and that the person can do what he is supposed to do.

Checkin and checkout assets so I know who did it.

### Snipe-IT Version

7.0.11

### Operating System

Docker 

### Web Server

Nginx

### PHP Version

8.1.2

**Comment by snipe** [comment]
Hi there - I believe @uberbrady might have been talking to you on Discord. Did you get this sorted?

**Comment by NHVIT** [comment]
That might have been somebody else :) I'm not on the snipe-it discord

**Comment by snipe** [comment]
Ah, whoops - sorry! 

This kinda doesn't make any sense though...  Is your `storage` directory (where sessions would be kept) on a different drive or is it somehow resetting periodically?

**Comment by NHVIT** [comment]
Well everything stays inside the docker container. I haven't mapped any drive or location that is inside the linux machine outside of the docker container... 
I wonder if the system is limited to only one person connecting or something weird?

**Comment by NHVIT** [comment]
I will make a video showing what happens :) 
Hopefully then it makes sense what the problem is

**Comment by uberbrady** [comment]
> Well everything stays inside the docker container. I haven't mapped any drive or location that is inside the linux machine outside of the docker container... I wonder if the system is limited to only one person connecting or something weird?

Probably not - we do have plenty of folks using the Docker setup and it tends to work fine for them. I suspect it might be something with your reverse proxy, maybe? Maybe something with cookies? I would try and see if you can connect directly to the docker container itself, without the proxy, and see if you have any better luck? _Then_ you can try and re-introduce the reverse proxy.

**Comment by NHVIT** [comment]
@uberbrady

It is the nginx proxy manager that was causing this issue. 

Turned everything off and connected locally to the ip-adres. Now the error is gone.

I will finetune the proxy manager untill it works :)

Thx for the info

**Comment by snipe** [comment]
Great, thanks for the follow up, and glad you're sorted!

**Comment by CryptoMears** [comment]
@NHVIT can you please share what you did to fix this issue from your NGINX Proxy manager to fix this issue. I am also having the same issue and also use the Docker version of Snipe-IT.

**Comment by seal61** [comment]
@NHVIT @CryptoMears Me too!

**Comment by NHVIT** [comment]
@CryptoMears @seal61 

![Image](https://github.com/user-attachments/assets/1dc228ee-b8d2-47ca-8584-64519f107dda)

I just turned all the switches off
