### ISSUE TITLE
In bulk users edit, language defaults to admin interface language 

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15504]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In bulk users edit screen, language field is prefilled with language of admin interface.

### Reproduction steps

1. Set app_locale to german (or anything other than English)
2. Set language for all users to German.
3. Set language for admin to English.
4. Select multiple users and do 'Bulk Edit'
R: Language field is prefilled with admins interface language.
(If this form is saved, for all users language is changed to English)

### Expected behavior

Language field should be empty like some other fields. If admin doesn't select language from the list - language field is not touched in the database.

### Screenshots

![image](https://github.com/user-attachments/assets/906125e3-fc04-4784-a556-4ca31da00e00)
![image](https://github.com/user-attachments/assets/d6ddb5ed-f6b9-4aa6-80dd-4b72f639990d)

### Snipe-IT Version

7.0.12

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.3

### Additional context

As admin, I use English interface, but majority of users use Lithuanian. While adding City information to their profiles, I unintentionally changed their interface language to English because this field was prefilled. To avoid language change, I have to manually change English to Lithuanian every single time. What makes this matter even worse, in our organization we have employees who use Snipe-IT in languages, other than English or Lithuanian.

**Comment by snipe** [comment]
Thanks! Niche bug, but you're good at finding those :) Fix is on master.
