### ISSUE TITLE
Generated API key works for one node of a cluster

### ISSUE THREAD

**Issue by uddeep-juturu** [grokability/snipe-it#15503]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have 2 instances of Snipe-it running on Ubuntu nodes, connected to common database, made highly available using a loadbalancer. When i create an API key from the browser, it works only for the instance on which it was created and doesnt work for other instance. I have tried changing session settings to database and requests written to sessions table in the database. Still, the API key works only for the instance it is created on.

### Reproduction steps

1. Create a database node
2. Create 2 instances of Snipe-it on 2 nodes loadbalanced, connecting to same database
3. Generate API key from browser
4. Authentication works only when the request is made to the instance it is created on else, unauthorized error
...

### Expected behavior

API Key created in the browser should work for both the instances irrespective of the where it is created.

### Snipe-IT Version

v7.0.11

### Operating System

Ubuntu 22.04.4 LTS

### Web Server

Nginx

### PHP Version

8.1.2

### Error messages

```shell
Error 401: Unauthorized or unauthenticated.

is what I get when its connected to other inststance than the API key generated one.
```

**Comment by snipe** [comment]
You'd probably need the `APP_KEY`s to be the same and you'll need the same `oauth-private.key` and `oauth-public.key` on both boxes.

**Comment by uddeep-juturu** [comment]
Hello,
Thank you for your response.
They seem different on both the nodes. Could you please tell at which step of installation, these oauth keys are automatically generated? 

Should i install first node, then copy the generated keys to the second node or can i copy them to the hosts during installation?

**Comment by snipe** [comment]
I'd probably go the first way - install on one node, and then copy them over to the second.

**Comment by uddeep-juturu** [comment]
works when using same oauth keys for both the hosts.
