### ISSUE TITLE
[Feature Request]: Request your support to manage our vehicle fleet Assets within Snipe IT

### ISSUE THREAD

**Issue by rkthamizhan** [grokability/snipe-it#15511]
### Is your feature request related to a problem? Please describe.

I am pleased to inform you that Snipe IT, our trusted IT asset management system, has been performing exceptionally well. We are now considering expanding its application to manage our vehicle fleet Assets. Your expertise and support in this new venture would be greatly appreciated.

### Describe the solution you'd like

I am pleased to inform you that Snipe IT, our trusted IT asset management system, has been performing exceptionally well. We are now considering expanding its application to manage our vehicle fleet Assets. Your expertise and support in this new venture would be greatly appreciated.

**Comment by snipe** [comment]
You haven't actually asked for anything specifically, so I'm not sure how we'd support you.
