### ISSUE TITLE
Cannot Update with upgrade script

### ISSUE THREAD

**Issue by bstamand** [grokability/snipe-it#15517]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Git is having an issue committing the changes.  Getting the below issue.  I have already set the identity as it is indicating but that still doesn't work.  See below.

Git is installed. 
Already on 'master'

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'apache@snipeit.(none)')
Cannot save the current index state
error: Your local changes to the following files would be overwritten by merge:
        config/backup.php
Please commit your changes or stash them before you merge.
Aborting
-- -- M config/backup.php
M       public/uploads/avatars/.gitignore
Your branch is behind 'origin/master' by 331 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
-- Updating e8a22f3..83b4bf9

### Reproduction steps

1.Attempt to run upgrade using the upgrade.php script
2.
3.
...

### Expected behavior

Update completes.

### Snipe-IT Version

7.0.11

### Operating System

Rocky Linux 9

### Web Server

Apache

### PHP Version

8.3.11

**Comment by uberbrady** [comment]
I would look at `git diff config/backup.php` to see what changes are in there, and if you want to keep them or not.

If you really did set an email address with `git config --global user.email` and so on, then for some reason git can't "see" that. If you haven't done that, you should definitely do that to see if it then lets you run the upgrade.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
