### ISSUE TITLE
API checkout Accessories not working

### ISSUE THREAD

**Issue by jan-zat** [grokability/snipe-it#15529]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Using the API [](https://snipe-it.readme.io/reference/accessories-checkout) to assign a accessorie to a user just return an error.

On the page https://snipe-it.readme.io/reference/accessories-checkout the error is:
```
{
  "status": "error",
  "messages": {
    "assigned_user": [
      "The assigned user field is required when none of assigned asset / assigned location are present."
    ],
    "assigned_asset": [
      "The assigned asset field is required when none of assigned user / assigned location are present."
    ],
    "assigned_location": [
      "The assigned location field is required when none of assigned user / assigned asset are present."
    ]
  },
  "payload": null
}
```

On my Server using https://inventory.DOMAIN.com/api/v1/accessories/6/checkout  I get.

```
{
    "status": "error",
    "message": "404 endpoint not found. Please check the API reference at https://snipe-it.readme.io/reference to find a valid API endpoint.",
    "payload": null
}
```

The Accessorie with the ID 6 exists when using https://inventory.DOMAIN.com/api/v1/accessories/
```
            "id": 6,
            "name": "Tune Flex",
```

### Reproduction steps

1. using curl to get IDs of all accessories https://DOMAIN.com/api/v1/accessories/  (example 6)
2. check Users ID with https://DOMAIN.com/api/v1/users (example 100)
3.  try to checkout an accessorie https://DOMAIN.com/api/v1/accessories/6/checkout

Receive Error:
{
    "status": "error",
    "message": "404 endpoint not found. Please check the API reference at https://snipe-it.readme.io/reference to find a valid API endpoint.",
    "payload": null
}

**Full curl command on Snipe-IT 7.0.12**
`curl --request POST --url https://DOMAIN.com/api/v1/accessories/6/checkout --header 'Authorization: Bearer XXX' --header 'accept: application/json' --header 'content-type: application/json' --data '{"assigned_to":103}'`
**Error:**
`{"status":"error","messages":{"assigned_user":["The assigned user field is required when none of assigned asset \/ assigned location are present."],"assigned_asset":["The assigned asset field is required when none of assigned user \/ assigned location are present."],"assigned_location":["The assigned location field is required when none of assigned user \/ assigned asset are present."]},"payload":null}`

**Full curl command on our Backup Snipe-IT with Version 6.0.14**
`curl --request POST --url https://DOMAIN.com/api/v1/accessories/6/checkout --header 'Authorization: Bearer XXX' --header 'accept: application/json' --header 'content-type: application/json' --data '{"assigned_to":103}'`
**Message:**
`{"status":"success","messages":"Accessory checked out successfully.","payload":null}`

### Expected behavior

Item assigned to user

### Snipe-IT Version

v7.0.12

### Operating System

8.1.2-1ubuntu2.18

### Web Server

Apache/2.4.52 (Ubuntu)

### PHP Version

PHP 8.1.2-1ubuntu2.18 

### Operating System

CLI

**Comment by snipe** [comment]
Pass the field `assigned_user` with the ID of the user.

**Comment by jan-zat** [comment]
> Pass the field `assigned_user` with the ID of the user.

Worked. thank you. Is that outdated on the API reference?
