### ISSUE TITLE
Are there really weekly backups?

### ISSUE THREAD

**Issue by icelava** [grokability/snipe-it#15527]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

https://snipe-it.readme.io/docs/configuring-alerts-backups

Ever since migrated Snipe-IT into a private internal application, we found that it does not automatically backup even though it's been more than a week. The daily task to send emails appears to work proper though.

### Reproduction steps

1. Deploy Snipe-IT as Kubernetes pod/container.
2. Daily email works.
3. Weekly backup doesn't run?
...

### Expected behavior

Backup happens once a week?

### Screenshots

![Snipe-IT no auto backups](https://github.com/user-attachments/assets/9a397a28-7b61-4546-94ca-8f07a0356d24)

### Snipe-IT Version

v7.0.12 - build 15249 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

Windows 11 23H2

### Browser

Microsoft Edge

### Version

128.0.2739.79

### Additional context

AWS RDS MySQL 8.0

**Comment by icelava** [comment]
On manual backup attempt looks like there's access denied.

 _Error: Backup failed because: The dump process failed with a none successful exitcode. Exitcode ======== 2: Misuse of shell builtins Output ====== <no output> Error Output ============ mysqldump: Couldn't execute 'FLUSH TABLES': Access denied; you need (at least one of) the RELOAD or FLUSH_TABLES privilege(s) for this operation (1227) ._

which is more than what MySQL Workbench shows for schema privileges.

Even when granting all the error still happens.

`grant all on ``snipe-it``.* to 'snipe-it'@'%'`

**Comment by snipe** [comment]
This is still a DB user permissions error. https://docs.digitalocean.com/support/how-do-i-fix-the-mysqldump-error-couldnt-execute-flush-tables-access-denied/

<blockquote><img src="/opengraph/opengraph-default.png" width="48" align="right"><div>DigitalOcean</div><div><strong><a href="https://docs.digitalocean.com/support/how-do-i-fix-the-mysqldump-error-couldnt-execute-flush-tables-access-denied/">How do I fix the mysqldump error "Couldn't execute FLUSH TABLES: Access denied"? | DigitalOcean Documentation</a></strong></div><div>Update the permissions of the backup user. Alternatively, remove the `--single-transaction` flag from the command, or downgrade your version of `mysqldump`.</div></blockquote>

**Comment by icelava** [comment]
I think granting PROCESS is kinda overkill? Not like the snipe-it user is a full-fledge administrator.

Tried applying

`GRANT RELOAD on *.* to 'snipe-it'@'%';`

and now it's a different error

 _Error: Backup failed because: The dump process failed with a none successful exitcode. Exitcode ======== 2: Misuse of shell builtins Output ====== <no output> Error Output ============ mysqldump: Couldn't execute 'FLUSH TABLES WITH READ LOCK': Access denied for user 'snipe-it'@'%' (using password: YES) (1045) ._

Appears others have experienced this problem before when operating on AWS RDS like we do. https://github.com/snipe/snipe-it/issues/13155

So looks like we're stuck?

**Comment by icelava** [comment]
Apparently someone's solution to the AWS RDS problem is to run mysqldump with `--set-gtid-purged=OFF` 

I don't have enough experience to understand what that means and its implications.
