### ISSUE TITLE
Simple Question: How do I customize Labels?

### ISSUE THREAD

**Issue by derbohesevincent** [grokability/snipe-it#15522]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I know that there are 15 different Labels - none of them fit my needs. Where is the "create new one" Button? 

So I chose to edit the default label and I have no Idea on how to place the Items on my 3x2in Label.  How do I define the Size of the QR Code, the position of the Asset-Logo or any other field? I'm seriously confused and I'm sure I'm missing something fundamentally. Hope someone can enlighten me.
BR
Vince

### Reproduction steps

none

### Expected behavior

none

### Snipe-IT Version

v7.0.12 build 15249 (g713bb104e)

### Operating System

Ubuntu Server LTS

### Web Server

Apache

### PHP Version

8.3.6

**Comment by LucasLinnasHogia** [comment]
Just went here to ask basicly the same thing. I need to resize the QR-code just a bit because it's about 4-5mm to big.

**Comment by LucasLinnasHogia** [comment]
After a little digging I found these posts below, it's pretty simple just modify the PHP and update your webpage. In the php you have alot more adjustments I started by copying a lablel that already existed. 

https://github.com/snipe/snipe-it/issues/10643
https://github.com/snipe/snipe-it/issues/10557
