### ISSUE TITLE
[Feature Request]: Option to ignore leading zeros in numerical asset tags

### ISSUE THREAD

**Issue by mattcarras** [grokability/snipe-it#15523]
### Is your feature request related to a problem? Please describe.

We've encountered problems with some scanners adding the leading zeros in barcodes, which causes a problem when the data is used to lookup the asset tags. This isn't always configurable on our side.

### Describe the solution you'd like

Add an option under asset tag preferences to ignore leading zeros when matching a numerical asset tag (through search or API).

### Describe alternatives you've considered

We could add leading zeros to all our asset tags, but we've found this confuses our techs and users when they go to lookup the assets as it will default back to a search on all fields. It also causes a problem in scenarios when the leading zeros are stripped before lookup.

### Additional context

As an example, this option could be implemented by checking if the string only contains digits, if so, convert to a number and back to a string before doing any lookups by asset tag.

I think for most users, an asset tag of "00003001" and "3001" should not refer to two different assets. For those that do, they can simply not check the option.

**Comment by snipe** [comment]
> I think for most users, an asset tag of "00003001" and "3001" should not refer to two different assets.

That hasn't been our experience with this software.

> For those that do, they can simply not check the option.

We refer to asset tags in hundreds of places within the system. This is a lot of code (and a lot of cyclomatic complexity)

Most scanners have this as a configurable option on the scanner's side.

https://sps-support.honeywell.com/s/article/How-to-configure-a-Honeywell-Scanner-to-remove-leading-zero-characters-from-a-barcode
https://www.youtube.com/watch?v=NgnLEDZbGpE

I don't think this is a feature we're going to consider at this time.
