### ISSUE TITLE
[Feature Request]: Support For MsSQL 2019 or Latest

### ISSUE THREAD

**Issue by OptimusPrm9** [grokability/snipe-it#15535]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Currently I am using MySql for database and it will be better if it supports MsSQL 2019 or latest

**Comment by snipe** [comment]
Are you running into any specific issues?

**Comment by OptimusPrm9** [comment]
no not any specific issue, just while searching it takes time for even when number of assets are around 1000.

**Comment by snipe** [comment]
There's nothing on our end that would discriminate between mysql versions. Without knowing what Snipe-IT version you're running, there's not a lot more we can advise here though.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
