### ISSUE TITLE
Location Delete Button Disabled for Admins Despite No Linked Users or Assets

### ISSUE THREAD

**Issue by vedagel** [grokability/snipe-it#15538]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In SnipeIT, even when an administrator has full admin rights (except for Super Admin privileges), the delete button for locations remains disabled. This occurs even if there are no users, assets, or other linked locations associated with the location. Based on the current behavior, only Super Admins seem able to delete locations, which limits the usability for other admins, even when they have the necessary permissions and the location is unlinked.

### Reproduction steps

	1.	Log in as an Admin with all rights except Super Admin.
	2.	Navigate to the “Locations” section.
	3.	Select a location that has no users, assets, or linked locations.
	4.	Observe that the delete button is disabled (grayed out).

### Expected behavior

If you have the delete rights for location you should be able to delete locations if no users, assets, or linked locations exist.

### Snipe-IT Version

v6.0.13

### Operating System

Ubuntu

### Web Server

NGINX

### PHP Version

8

**Comment by snipe** [comment]
I'm not able to reproduce this on the demo:

<img width="1446" alt="Screenshot 2024-09-20 at 4 45 58 PM" src="https://github.com/user-attachments/assets/194acb29-9c2b-429c-ae96-a0453fb7dd37">

The `isDeleteable()` method checks for several things (and should really be checking for more tbh):

https://github.com/snipe/snipe-it/blob/4ab478bb97206aaf6265c6a86c578a079ee7d067/app/Models/Location.php#L98-L116

Remember that some things can be checked out to locations, and still more can have locations as a Default Location or a deployed location.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
