### ISSUE TITLE
Add an invoice image to the licenses

### ISSUE THREAD

**Issue by ab11o** [grokability/snipe-it#15545]
### Is your feature request related to a problem? Please describe.

I would like to add a picture to any license I issue, please.

### Describe the solution you'd like

I would like to add a picture to any license I issue, please.

**Comment by snipe** [comment]
You can already do this.

<img width="735" alt="View_License_-_Photoshop____Snipe-IT_Demo_and__👾-github___Snipe-IT_Community_-_Discord" src="https://github.com/user-attachments/assets/823cdade-c09f-4b5b-9b7a-83bfbea0ddfb">
