### ISSUE TITLE
/hardware/audit/{due,overdue} API returning all assets, not just those which are due for an audit

### ISSUE THREAD

**Issue by samuelb** [grokability/snipe-it#15548]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The API endpoints `/hardware/audit/due` and `/hardware/audit/overdue` are returning always all assets and not just those which are due or overdue for an audit, [as documented](https://snipe-it.readme.io/reference/hardwareauditdue).

The issue seems to persist since a while. I accidentally used Snipe-IT v6.4.1 in a test installation and reproduced it. But also 7.0.11 has the same issue.

I saw [in the source](https://github.com/snipe/snipe-it/blob/34eb10ff73e50cf9617779c085fc7f529a436b89/routes/api.php#L498) that this an legacy API and the new APIs are `/hardware/audits/due`, `/hardware/audits/overdue` and `/hardware/audits/due-or-overdue`, which work as expected. However, the docs is still mentioning the old API.

### Reproduction steps

1. Ensure in Settings -> Notification that "Audit Interval" is defined.
2. Create a new asset or edit an existing asset. Ensure that the attribute "Next Audit Date" is way in the future, after the configured audit interval
3. Create yourself an API token
4. `curl -H 'Authorization: Bearer <api token>'  https://<server>/api/v1/hardware/audit/due | jq` (or any other tool of your choice). You can see that your asset, which should not be due for audit, is listed, among any other assets which may exists.

### Expected behavior

The APIs `/hardware/audit/due` and `/hardware/audit/overdue` should only return assets which are actually due or overdue for audit. The result should be comparable to the APIs `/hardware/audits/due` and `/hardware/audits/overdue`.

### Snipe-IT Version

6.4.1, 7.0.11

### Operating System

Debian 12, Docker

### Web Server

Apache

### PHP Version

8.1.2, 8.3.8

### Additional context

- Is this a fresh install or an upgrade? Discovered on a existing system, confirmed in a fresh docker installation version 6.4.1 and 7.0.11
- What method you used to install Snipe-IT: manual and docker
- Indicate whether or not you've manually edited any data directly in the database: nope

**Comment by snipe** [comment]
Can you not just use the new urls, `/api/v1/hardware/audits/due` and `/api/v1/hardware/audits/overdue`?

**Comment by samuelb** [comment]
> Can you not just use the new urls, `/api/v1/hardware/audits/due` and `/api/v1/hardware/audits/overdue`?

Yes, sure, this is what I did at the end. But still the API (.../audit/...) didn't work as documented and that's why I reported it.

I can confirm it works now on the master branch. Thx for fixing it! :hugs:
