### ISSUE TITLE
[Feature Request]: Check out an asset to multiple users

### ISSUE THREAD

**Issue by kdiep-ctrl** [grokability/snipe-it#15562]
### Is your feature request related to a problem? Please describe.

you can only checkout an asset to one user at a time;

### Describe the solution you'd like

I would like to see how many users are using an asset so being able to checkout to multiple is great.

**Comment by snipe** [comment]
Multiple users cannot be responsible for an asset if it goes missing or is broken. This is not a feature we are considering at this time.
