### ISSUE TITLE
After successfully configuring SAML and set as primary method, the URL .../login?nosaml isn't working

### ISSUE THREAD

**Issue by TineUser** [grokability/snipe-it#15568]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After successfully configuring SAML and set as primary method, the URL .../login?nosaml isn't working. The login form appears but the local administrator can't login. 

Fehler: Benutzername oder Passwort sind nicht korrekt.

Before setting the primary method the login as loacal administrator worked.

How can I revert this setting?

### Reproduction steps

Set the SAML authentication as primary login as described in the documentation, https://snipe-it.readme.io/docs/saml:

SAML Force Login

When this checkbox is enabled, you will not see a login form of Snipe-IT anymore when you go to the Snipe-IT website. Instead it will redirect you directly to the IdP SAML Login.

When you need to see the login form of Snipe-IT to login with an existing user without SAML login, you could add the following query parameter to your Snipe-IT URL: /login?nosaml:

https://assets.example.com/login?nosaml

### Expected behavior

The local administrator can login.

### Snipe-IT Version

6.4.2

### Operating System

Windows

### Web Server

Apache

### PHP Version

8.0.19

### Error messages

DEBUG mode doesn't show anythig

**Comment by snipe** [comment]
Is it possible for you to upgrade? You’re on a pretty old version of snipe-it

**Comment by TineUser** [comment]
DEBUG log:
![image](https://github.com/user-attachments/assets/b39df49e-c21d-40c2-ac9c-ea615221adc5)

Actually I can't upgrade because of the new PHP version requirement.

**Comment by TineUser** [comment]
DEBUG log:
![image](https://github.com/user-attachments/assets/e3384e29-2c4d-4720-b706-b06dd6630a61)

Seems like the login is working as it should but the authentications fails.

**Comment by TineUser** [comment]
OK, I found the solution: We used a SQL statement to change the usernames in Snipe-IT because of SAML authentication. And so the  user administrator was changed, too. Changed in the database and the login works again.

**Comment by snipe** [comment]
Awesome! Glad to hear you’re sorted!
