### ISSUE TITLE
The attempt to associate the accessory or asset with the user results in a 500 ERROR.

### ISSUE THREAD

**Issue by informatiqueSiptos** [grokability/snipe-it#15567]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The attempt to associate the accessory or asset with the user results in a 500 ERROR.

![Capture d'écran 2024-09-26 110929](https://github.com/user-attachments/assets/a9eb6ccb-e8ae-490a-a40a-247195329764)

### Reproduction steps

1. Select an available Asset or Accessory
2. Select a user from the list
3. Click "Apply"

### Expected behavior

Association d'un Actif avec un utilisateur.

### Snipe-IT Version

Version v7.0.13-pre - build 15360 (master)

### Operating System

Debian 12

### Web Server

Apache

### PHP Version

8.2

### Operating System

Windows

### Browser

Vivaldi, Edge, Firefox, Chrome

### Version

6.9, 129, 130, 129

**Comment by informatiqueSiptos** [comment]
I also waited for version 7.012 during the update, but version 7.0.13-pre was installed.

**Comment by snipe** [comment]
Sounds like you need to run migrations.

**Comment by informatiqueSiptos** [comment]
I rolled back to version 7.0.11. Fortunately, I had a backup.
