### ISSUE TITLE
[Feature Request]: Allow accessories to be checked out to assets

### ISSUE THREAD

**Issue by jlewis-mma** [grokability/snipe-it#15560]
### Is your feature request related to a problem? Please describe.

WE use a lot of shared workstations that are not assigned to a user. IT would be great to be able to check out accessories to an asset and not a user in cases where there is no user to assign it to. 

### Describe the solution you'd like

I want to be able to check out accessories and assign those to assets and not users.

**Comment by snipe** [comment]
This is already in the works
