### ISSUE TITLE
Bulk Checkout issue on v7.0.13-pre - build 15360

### ISSUE THREAD

**Issue by blackburst971** [grokability/snipe-it#15584]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Unable to bulk checkout any items. Try on the online demo too , and I've the same result. 

### Reproduction steps

1.Choose asset in the form
2.Select user for checkout
3.click on checkout
...

### Expected behavior

Validation of the multiple checkout assets to the user. 

### Screenshots

![Capture d’écran 2024-09-30 à 16 56 32](https://github.com/user-attachments/assets/242d19fc-597e-4cc1-b042-a75e16df07cd)
![Capture d’écran 2024-09-30 à 16 57 09](https://github.com/user-attachments/assets/ec32d962-5414-4cb5-8d08-5a339f6fbf2c)

### Snipe-IT Version

v7.0.12

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.3.11

### Operating System

Mac OS

### Browser

Chrome

### Version

116.0.5845.187

### Additional context

Fresh upgrade with git install

**Comment by snipe** [comment]
Can you describe this in a little more detail please? What is the actual behavior you’re seeing?

**Comment by blackburst971** [comment]
First I wanted to thank you for your tremendous work ! The screenshot is after I click on the checkout button . Nothing happen after clicking on checkout , and in the development tab I have the error message , on my setup and also on your demo website, it happen exactly the same way.

**Comment by snipe** [comment]
This should be fixed if you do a fresh full from the `master` branch

**Comment by snipe** [comment]
> First I wanted to thank you for your tremendous work ! 

Also, Ty! 
![heart-hands](https://github.com/user-attachments/assets/a7bd0349-c346-4ee5-b6b3-884d7c8b41ae)

**Comment by Tolis1337** [comment]
We have the basic hosting plan with v7.0.13-pre build 15360, and we encounter the same issue. An update is being expected to be pushed for the fix?

Thanks!!

**Comment by snipe** [comment]
@Tolis1337 - you bet - if you open a ticket at support@snipeitapp.com with your hosted subdomain, we can get you upgraded right away.

**Comment by Tolis1337** [comment]
hey @snipe! Just did it!
Really appreciate the immediate response and resolution!!

**Comment by snipe** [comment]
@Tolis1337 Hm, I don't see an email from you in our helpdesk. Did Victoria or Osei maybe already jump on it?

**Comment by Tolis1337** [comment]
hey @snipe. Yes! everything set. The upgrade was instant after my mail, and everything is smooth again!
Thank you so much!

**Comment by snipe** [comment]
Love to hear it!
