### ISSUE TITLE
False Timestamp by CheckIn License on ActivityLog

### ISSUE THREAD

**Issue by kramerm448** [grokability/snipe-it#15582]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I revoke a license, the time 00:00 is always displayed. Everything works out when it comes to publishing.

### Reproduction steps

1. revoke a license from a User
2. Click on full Activity Report (https://snipe.example.com/reports/activity)
3. under Date see you the Time 00:00

### Expected behavior

Wrong Timestamp under Activity Report

### Screenshots

![image](https://github.com/user-attachments/assets/cdbcb0d3-f9f0-4083-811b-b37b6db2de42)

### Snipe-IT Version

7.0.12

### Operating System

Debian11 (Docker)

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

Windows11

### Browser

Microsoft Edge + Google Chrome

### Error messages

```shell
-
```

### Additional context

-

**Comment by marcusmoore** [comment]
Thanks for reporting @kramerm448. This is fixed in the develop branch and will be included in the next release. I'm going to close this now but if you find the bug is still included in 7.0.13, when it is released, please tag me here and I'll re-open it.
