### ISSUE TITLE
Error 500 with pre-flight setup/user?

### ISSUE THREAD

**Issue by kondi06** [grokability/snipe-it#15581]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

ERROR 500 page

### Reproduction steps

1.use install script 
2.
3.
...

### Expected behavior

finish config pre-flight

### Screenshots

https://flareapp.io/share/q5YGppeP

### Snipe-IT Version

the newest

### Operating System

Ubuntu version 23.04

### Web Server

Apache

### PHP Version

PHP 8.1.12-1ubuntu4.3

### Operating System

Windows

### Browser

Google Chrome

### Error messages

```shell
syntax error, unexpected token ";", expecting ")"
https://flareapp.io/share/q5YGppeP#debug
```

**Comment by snipe** [comment]
Thanks for that catch - should be fixed on master now
