### ISSUE TITLE
LDAP User Import Country not matching. Selecting a Country on Snipe-IT user displays 2 letter country code.

### ISSUE THREAD

**Issue by Toby737** [grokability/snipe-it#15580]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When doing an LDAP Import of users, the country assigned to the user in Snipe-IT does not match what was assigned to the AD user account.

In my example, all our users are based in Germany with the country/region set as Germany for the AD user.
However once the user's get imported/updated, Snipe-IT shows the user's country as Zimbabwe.
I can change the country manually in Snipe-IT to Germany but the next LDAP sync will change it back to Zimbabwe.

Also, when selecting any country in Snipe-IT, it displays itself as the short form, eg...  DE *, AU *, ZA *, CH *, etc...
![Screenshot 2024-09-30 165502](https://github.com/user-attachments/assets/33242564-ccc8-4bc3-85be-9f929bfbba78)
![Screenshot 2024-09-30 165925](https://github.com/user-attachments/assets/423ed7f7-71c4-4b79-a6b1-0b486172b162)

### Reproduction steps

1. Go to edit a user.
2. Change the country.
3. Click Save.

1. Performing an LDAP user sync.
2. Edit the user and see the country assigned.

### Expected behavior

* Setting Country as Germany should display Germany instead of DE *

* Performing an LDAP user sync should also correctly assign the country in Snipe-IT.

### Snipe-IT Version

7.0.12

### Operating System

CentOS 9

### Web Server

Apache

### PHP Version

8.3.12

### Operating System

Windows

### Browser

Edge, Chrome, FireFox

### Version

Latest

**Comment by uberbrady** [comment]
I think I just fixed this in the past few weeks - can you pull the latest from master and confirm whether or not it fixes the problem for you?

**Comment by Toby737** [comment]
@uberbrady - I upgraded and it's now running v7.0.13-pre - build 15360. It seems to have fixed the problem thanks. It still adds the asterisk * though at the end of the country.
![Screenshot 2024-10-01 110441](https://github.com/user-attachments/assets/5305a8ec-5182-4e25-80f5-be4c5c9f0d33)

**Comment by snipe** [comment]
Great, glad you're sorted! (The asterisk is expected, as explained by the help test below.)
