### ISSUE TITLE
Custom Field Checkbox toggle all the boxes

### ISSUE THREAD

**Issue by PB-RESCED** [grokability/snipe-it#15599]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After i created a custom field as checkbox i put the values in it as reported on the page one per line. It shows on the asset model as different checkboxes but when i toggle one all becomes checked and if you try to untoggle another one all the checkboxes untoggles. Anyway if i edit again the asset and uncheck one on one the unwanted values it let me do it.

### Reproduction steps

1.Create a custom field as checkbox with multiple lines and associate to an existing field set
2.Edit an asset model with that field set associated
3.Check the custom field

### Expected behavior

When a checkbox is toggled, only that checkbox should toggles

### Snipe-IT Version

v7.0.13-pre - build 15360 (master)

### Operating System

Ubuntu 22.04.5 LTS

### Web Server

Apache

### PHP Version

8

### Operating System

Windows 11

### Browser

Google Chrome

### Version

129.0.6668.70

**Comment by Steve-M-C** [comment]
I get this too, but only when I'm editing an Asset Model and attempting to set the default values. On an actual asset based on the model I am able to select/unselect individual checkboxes.
I've tested this in Firefox and Edge and both exhibit the same behaviour.

**Comment by Steve-M-C** [comment]
I've also just tested in the Demo system, and the issue is present there too.

**Comment by snipe** [comment]
@marcusmoore @spencerrlongg can either of you take a look at this today?

**Comment by marcusmoore** [comment]
I can take a look

**Comment by marcusmoore** [comment]
@PB-RESCED thanks for reporting and @Steve-M-C thanks for confirming.

This should be fixed with #15711 and will be included in the next release.
