### ISSUE TITLE
[Feature Request]: Bulk RFID Scanning Support in Android App

### ISSUE THREAD

**Issue by blown5** [grokability/snipe-it#15595]
### Is your feature request related to a problem? Please describe.

Hello,

We are using the Snipe-IT Android application on a handheld terminal equipped with an RFID module. We need to periodically check the presence of a large number of assets. Our goal is to perform this check by simply moving the handheld device into the doorway of each room and scanning all UHF RFID-tagged assets in the room, comparing them with the existing assets in the Snipe-IT application.

However, the current mobile application only allows scanning one barcode at a time. The ability to scan multiple RFID tags simultaneously is critical for us. Could you please add support for bulk RFID barcode scanning in the application?

Thank you for your attention to this matter.

Best regards,

### Describe the solution you'd like

I would like the Snipe-IT Android application to support bulk RFID scanning. Currently, the app only allows scanning one barcode at a time, which makes it time-consuming to check multiple assets.

The solution would be to enable the app to scan multiple RFID tags simultaneously using a handheld RFID terminal. Once scanned, the app should automatically compare the scanned RFID tags with the existing assets in the Snipe-IT database and allow bulk updates or verification of assets. This would significantly improve efficiency in environments where many assets need to be checked regularly.

**Comment by snipe** [comment]
Hi there - you'd need to open an issue with the creator of that app. We don't know them, and it's not officially supported, since it's not open source.
