### ISSUE TITLE
Upload PDF (or others) under File Tab of ASSET success BUT zeroized file

### ISSUE THREAD

**Issue by FabioD79** [grokability/snipe-it#15611]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello
When i upload a pdf file of 72k (or txt) under tab files (or files to add), snipeit complete the upload process successful but the file became 0k dimesione with a straight through line on filename and it is not download-able

### Reproduction steps

1. Create a new asset (or using an existing)
2. go to files tab, click upload, choose pdf file and upload it
3. The straight through on file name appear and it is not possible to download it

### Expected behavior

The file should be uploaded with the correct size dimension and downloadable

### Screenshots

![SnipeIT_UploadFail](https://github.com/user-attachments/assets/14e9eec4-4ae0-4b8d-8603-c3b101dc7a11)

### Snipe-IT Version

v7.0.11 build 15044

### Operating System

Ubuntu 24.04.1 LTS

### Web Server

Apache 2.4.58

### PHP Version

8.3.6

### Operating System

Windows 11

### Browser

MS Edge

### Version

129.0.2792.65

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Version

N/A

### Error messages

```shell
N/A
```

### Additional context

It's a fresh install with php artisan restored backup from a snipe-it previous version zip file

**Comment by snipe** [comment]
That generally means the upload failed. Check your directory permissions and your app log.

**Comment by FabioD79** [comment]
Thank you for the answer. Yes, i solved it adding www-data group permission on ../private_uploads
Regards

**Comment by snipe** [comment]
Great, glad you're sorted!
