### ISSUE TITLE
Confirm acceptance of assets - the site also displays locations associated with the same ID

### ISSUE THREAD

**Issue by Speed1** [grokability/snipe-it#15619]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hard to explain. I will make an example:

We have enabled the ‘confirm acceptance of assets’ feature, requiring end users to confirm asset receipt via Snipe-IT. When users with ID 46 open the page to accept assets, they also see assets assigned to the location associated with the same ID (46).

### Reproduction steps

1. Assign assets to location ID 46
2. Enable confirm acceptance of assets feature
3. Assing another assets to user ID 46
4. Open the confirmation link that user ID 46 has received
5. Check assets that can accepted/declined

### Expected behavior

User with ID 46 should not see assets associated with location ID 46.

### Screenshots

<img width="893" alt="AssetConfirmation" src="https://github.com/user-attachments/assets/bf46512e-fc03-4269-a35e-53775c0b1e33">

### Snipe-IT Version

7.0.12

### Operating System

RHEL

### Web Server

Apache

### PHP Version

8.2.13

**Comment by snipe** [comment]
I think this was fixed in the latest release

**Comment by Speed1** [comment]
Ok, we will update and test it. Let you know.
Thanks

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
