### ISSUE TITLE
[Feature Request]: Trigger LDAP Sync via API

### ISSUE THREAD

**Issue by ntbutler-nbcs** [grokability/snipe-it#15615]
### Is your feature request related to a problem? Please describe.

I'm not sure if this has been discussed already, but it would be great if the LDAP sync could be triggered via an API call or similar. In particular I am trying to figure out how to schedule the LDAP sync to run regularly, but I have just moved our instance into a Docker container and I wasn't sure how to achieve this when using a dockerized instance.

### Describe the solution you'd like

A new API endpoint, possibly in the "settings" group:
`/settings/ldap/sync`
It could be a POST request that takes optional location/locationId fields:
```json
{
    "locationId": 4
}
```

**Comment by ntbutler-nbcs** [comment]
Having literally just created this feature request, it just clicked in my head that I can achieve this in my instance with a cron job running a `docker exec -t snipeit /usr/bin/php /var/www/html/artisan snipeit:ldap-sync` command, so I guess that would be the alternative in this instance. But I still think being able to trigger this via the API would be a useful addition 😄

**Comment by snipe** [comment]
The LDAP sync is a pretty burly process (depending on the size of your directory). I don't think we'd want to make that an API endpoint, as one misfiring API call could melt a server.
