### ISSUE TITLE
Login via SAML for 1 user not possible

### ISSUE THREAD

**Issue by knmax** [grokability/snipe-it#15623]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

User who can login to all other systems through SAML is not able to login to snipe.
User has already been completely removed from snipe and reimported - didn't solve the issue.

User is getting this error message:
![image](https://github.com/user-attachments/assets/34de7b4d-07f7-464f-8070-0ebf83a69f56)

### Reproduction steps

1. open snipe login page
2. click Login via SAML
3. get Error message
...

### Expected behavior

see Dashboard

### Screenshots

in Debug-Mode
![image (1)](https://github.com/user-attachments/assets/72c890c8-b048-4129-bd3a-db57260fefc7)

### Snipe-IT Version

7.0.11

### Operating System

Ubuntu - Docker

### Web Server

Apache

### PHP Version

8.1.2

**Comment by snipe** [comment]
In their user profile, do they have "User can login" checked?

**Comment by snipe** [comment]
Actually, scratch that. Usually SAML is looking for an email address, not a username. While that's not always true, it's extremely common. Check that the username is actually an email address in Snipe-IT and also your SAML provider.

**Comment by knmax** [comment]
the username is only "firstname.lastname" which is the same for all our users that are logging in via SAML - but I think I found what may be the issue - I think the information that is being used for the login is the "Mail nickname" which seems to be set wrong
We will check this and give you feedback.

**Comment by knmax** [comment]
we just changed it and now my colleague is able to login.
Thanks for the help.

**Comment by snipe** [comment]
Excellent - glad to hear you're sorted!
