### ISSUE TITLE
[Feature Request]: Ldap Sync Auto

### ISSUE THREAD

**Issue by hakihosting** [grokability/snipe-it#15635]
### Is your feature request related to a problem? Please describe.

Ldap Sync

### Describe the solution you'd like

I would like to request the implementation of an automatic LDAP sync to run every hour. Currently, we have to manually press the "LDAP Sync" button each time, which is not efficient and may lead to delays in updating user data.

Setting up an automatic synchronization would help ensure that our LDAP data remains up to date and that users can access the system seamlessly without requiring manual intervention.

Please let me know if you need any further details or if there are any prerequisites to make this happen.

**Comment by snipe** [comment]
You can set up a cron or an automated task to handle that for you.

https://snipe-it.readme.io/docs/configuring-alerts-backups
https://snipe-it.readme.io/docs/ldap-sync

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuring-alerts-backups">Configuring Alerts & Backups</a></strong></div><div>Starting from Snipe-IT v3.0, all automated tasks are handled via the scheduler. To set a cron job to run every minute to ping the scheduler: * /path/to/php /path/to/artisan schedule:run &gt;&gt; /dev/null 2&gt;&amp;1 The scheduler already knows how often it should trigger the individual tasks, becau...</div></blockquote>
<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/ldap-sync">LDAP Sync</a></strong></div><div>❗️ Large LDAP Directories: In your .env file, you may need to modify the LDAP_MEM_LIM (expressed as '500M' for 500MB) and/or the LDAP_TIME_LIM (expressed in seconds) in order to avoid a large LDAP sync from timing out or exhausting all memory. The default time limit is 10 minutes. The default memory...</div></blockquote>

**Comment by hakihosting** [comment]
Hello thank you i added the schedule run i have this error : 

C:\Users\adm-neji>C:\wamp\bin\php\php8.1.22\php.exe C:\wamp\www\5344_asset\artisan snipeit:ldap-sync
Xdebug: [Log Files] File 'c:/wamp/logs/xdebug.log' could not be opened.

   UnexpectedValueException

  The stream or file "C:\wamp\www\5344_asset\storage\logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: UnexpectedValueException: The stream or file "C:\wamp\www\5344_asset\storage\logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: ErrorException: Attempt to read property "ldap_enabled" on null in C:\wamp\www\5344_asset\app\Console\Commands\LdapSync.php:49
Stack trace:
#0 C:\wamp\www\5344_asset\app\Console\Commands\LdapSync.php(49): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Attempt to read...', 'C:\\wamp\\www\\534...', 49)
#1 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\LdapSync->handle()
#2 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Container\Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#4 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#5 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Container\Container.php(653): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#6 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Illuminate\Container\Container->call(Array)
#7 C:\wamp\www\5344_asset\vendor\symfony\console\Command\Command.php(298): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#8 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#9 C:\wamp\www\5344_asset\vendor\symfony\console\Application.php(1024): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 C:\wamp\www\5344_asset\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\LdapSync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\wamp\www\5344_asset\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Console\Application.php(94): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\wamp\www\5344_asset\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main} in C:\wamp\www\5344_asset\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:146
Stack trace:
#0 C:\wamp\www\5344_asset\vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write(Array)
#1 C:\wamp\www\5344_asset\vendor\monolog\monolog\src\Monolog\Logger.php(359): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\wamp\www\5344_asset\vendor\monolog\monolog\src\Monolog\Logger.php(602): Monolog\Logger->addRecord(400, 'ErrorException:...', Array)
#3 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Log\Logger.php(183): Monolog\Logger->error(Object(ErrorException), Array)
#4 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Log\Logger.php(94): Illuminate\Log\Logger->writeLog('error', Object(ErrorException), Array)
#5 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Log\LogManager.php(590): Illuminate\Log\Logger->error(Object(ErrorException), Array)
#6 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Log\LogManager->error(Object(ErrorException))
#7 C:\wamp\www\5344_asset\app\Exceptions\Handler.php(48): Illuminate\Support\Facades\Facade::__callStatic('error', Array)
#8 C:\wamp\www\5344_asset\vendor\nunomaduro\collision\src\Adapters\Laravel\ExceptionHandler.php(46): App\Exceptions\Handler->report(Object(ErrorException))
#9 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(366): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report(Object(ErrorException))
#10 C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Foundation\Console\Kernel->reportException(Object(ErrorException))
#11 C:\wamp\www\5344_asset\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 {main}

  at C:\wamp\www\5344_asset\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:146
    142?             restore_error_handler();
    143?             if (!is_resource($stream)) {
    144?                 $this->stream = null;
    145?
  ? 146?                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url) . Utils::getRecordMessageForException($record));
    147?             }
    148?             stream_set_chunk_size($stream, $this->streamChunkSize);
    149?             $this->stream = $stream;
    150?         }

  1   C:\wamp\www\5344_asset\vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php:48
      Monolog\Handler\StreamHandler::write()

  2   C:\wamp\www\5344_asset\vendor\monolog\monolog\src\Monolog\Logger.php:359
      Monolog\Handler\AbstractProcessingHandler::handle()

C:\Users\adm-neji>

**Comment by hakihosting** [comment]
C:\Windows\system32>C:\wamp\bin\php\php8.1.22\php.exe C:\wamp\www\5344_asset\artisan snipeit:ldap-sync

   ErrorException

  Attempt to read property "ldap_enabled" on null

  at C:\wamp\www\5344_asset\app\Console\Commands\LdapSync.php:49
     45?     public function handle()
     46?     {
     47?
     48?         // If LDAP enabled isn't set to 1 (ldap_enabled!=1) then we should cut this short immediately without going any further
  ?  49?         if (Setting::getSettings()->ldap_enabled!='1') {
     50?             $this->error('LDAP is not enabled. Aborting. See Settings > LDAP to enable it.');
     51?             exit();
     52?         }
     53?

  1   C:\wamp\www\5344_asset\app\Console\Commands\LdapSync.php:49
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Attempt to read property "ldap_enabled" on null", "C:\wamp\www\5344_asset\app\Console\Commands\LdapSync.php")

  2   C:\wamp\www\5344_asset\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      App\Console\Commands\LdapSync::handle()

C:\Windows\system32>

**Comment by hakihosting** [comment]
And LDAP are activate 
![image](https://github.com/user-attachments/assets/01ca1890-325a-4ea4-a691-f9bf71910e3c)
