### ISSUE TITLE
[Feature Request]: Modify the Software License tab information 

### ISSUE THREAD

**Issue by Pogiko24** [grokability/snipe-it#15639]
### Is your feature request related to a problem? Please describe.

How can i change the categories under Software License. let me say i want to include URL column or Payment option details column. 

### Describe the solution you'd like

How can i change the categories under Software License. let me say i want to include URL column or Payment option details column. 

### Describe alternatives you've considered

NAHow can i change the categories under Software License. let me say i want to include URL column or Payment option details column. 

### Additional context

NA

**Comment by snipe** [comment]
Duplicate of #4261
