### ISSUE TITLE
7.0.13 CC Email alerts appear to no longer work when items are checked in/checked out

### ISSUE THREAD

**Issue by Toby737** [grokability/snipe-it#15641]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Since the upgrade to 7.0.13, it seems that the CC Email feature no longer works.

### Reproduction steps

1. Ensure a valid email is present in Notification Settings --> CC Email.
2. Checkout an item.
3. Checkin the item.
4. Expectation is to also receive a copy of the checkout/checkin email.
5. User gets the checkout/checkin email, however nothing is sent to the email address in the CC Email field.

### Expected behavior

A copy of the checkin/checkout emails should be received.

### Snipe-IT Version

Version v7.0.13 - build 15514 (master)

### Operating System

CentOS 9

### Web Server

Apache

### PHP Version

8.3.12

### Additional context

I setup a test instance of 7.0.12 and performed the above test and emails are sent to whatever address is in the CC Email field.
So seems to be a bug in 7.0.13.

**Comment by yospuig** [comment]
I'm seeing the same behavior:

Snipe-IT version: v7.0.13 build 15514
PHP Version:8.3.6
Laravel Version:10.48.22

Ubuntu 24.04.1 LTS

**Comment by DomingoSneed** [comment]
I am also seeing this exact behavior on Windows IIS running on Server 2019.

Test email sent from GUI is sent and received
User which was assigned asset receives the email notification on checkout and check-in
Admin assigned under Notification Setting > Alerts > CC Email receives no email

We have a user assigned in AD solely for this purpose. It has its own mailbox in Office 365.

If I sign in and view that mailbox, the test emails appear in the inbox. The emails sent for checkout and check-in appear in the sent items.

However, the CC address for the emails isn't being included. The email is ONLY being sent to the end user. The CC email is not being sent at all.

Our details:

Snipe-IT Version
Version v7.0.13 - build 15514 (master)

Operating System
Windows Server 2019

Web Server
Windows IIS

PHP Version
8.3.12

**Comment by itmandev** [comment]
i have same problem, not getting email CC,

Snipeit : v7.0.13 build 15514
Os : Ubuntu 22.04.4 LTS
Php : 8.1.2-1ubuntu2.19
Laravel : 10.48.14

**Comment by Toby737** [comment]
Hello,
Just wanted to provide an update.
I upgraded our test instance to v7.0.13 - build 15666 and tested the mail notifications when checking in/out devices, and it is now working. Many thanks for fixing this. 😊
One small thing is that the From displays only the email address this time, compared to v7.0.13 - build 15514 which displayed the From Name and From email address (set from the .env?).
<img width="186" alt="image" src="https://github.com/user-attachments/assets/e5c8f75b-1d60-4d1e-83f4-740a26452bf5">

No big deal if it will only show the email address set in the .env file going forward, but just in case it should be displaying the MAIL_FROM_NAME entry from the .env, raising it now. 😅

Snipe-IT v7.0.13 - build 15514
<img width="359" alt="image" src="https://github.com/user-attachments/assets/70cc23f2-e70b-40bb-9253-726a91783d3b">

Snipe-IT v7.0.13 - build 15666
<img width="188" alt="image" src="https://github.com/user-attachments/assets/c71b0cb2-61a4-463c-8041-fa42284a762c">

**Comment by Godmartinz** [comment]
@Toby737 The MAIL_FROM_NAME has been added to be recognized by mail notifications again. Please pull from master and let me know if the issue still persists. Thanks

**Comment by Toby737** [comment]
@Godmartinz Just ran an update and yes it appears to be back in order.
Many thanks!
