### ISSUE TITLE
No error message when creating asset via API with invalid options

### ISSUE THREAD

**Issue by Toreg87** [grokability/snipe-it#15667]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If I try to create or patch an asset via API with an invalid option (nonexistent model_id, same serial with unique_serial) I don't get an error message, but get redirected to the last successfull query.
However the error doesen't show up with every invalid option, e.g. an invalid status_id generates the correct error message.
I have only tried a few options to demonstrate this.

I can reproduce this easily in the demo.

### Reproduction steps

1. Create asset with invalid model_id via API in the demo (e.g. POST https://develop.snipeitapp.com/api/v1/hardware?model_id=77777&status_id=1)

### Expected behavior

Get a proper error message.

### Snipe-IT Version

7.0.13

### Operating System

Debian

### Web Server

Apache

### PHP Version

8.1

**Comment by snipe** [comment]
I cannot reproduce this on my develop branch - I get:

```json
{
    "status": "error",
    "messages": {
        "model_id": [
            "The selected model id is invalid."
        ]
    },
    "payload": null
}
````

<img width="490" alt="_hardware" src="https://github.com/user-attachments/assets/7d17ff78-915d-4537-8a1e-411aa6fda66b">

**Comment by Toreg87** [comment]
Ok, this seems to be an issue with my postman. If I try it with a simple python request, I get the error response.
