### ISSUE TITLE
"LDAP Search OU" field in Location has become required

### ISSUE THREAD

**Issue by RedShift1** [grokability/snipe-it#15663]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When creating a location, the "LDAP Search OU" has become required (contrary to earlier versions).

### Reproduction steps

1. Enable LDAP integration
2. Try to create a new location leaving the "LDAP Search OU" field blank

### Expected behavior

The location is created

### Screenshots

![snipe_it_location_required](https://github.com/user-attachments/assets/a2d47a71-6421-4bdf-96af-e80b8fbe3d0b)

### Snipe-IT Version

7.0.13

### Operating System

Docker on Rocky Linux

### Web Server

Apache

### PHP Version

8.1.2

### Operating System

Windows

### Browser

Google Chrome

### Version

Version 129.0.6668.90 (Official Build) (64-bit)

### Error messages

```shell
No errors in the browser's console
```

**Comment by swift2512** [comment]
+1
I also get this message on Snipe-IT instances with LDAP enabled.

**Comment by RedShift1** [comment]
Hello, thanks for fixing it!
