### ISSUE TITLE
Snipe-IT not upgrading from v7.0.9 to v7.0.13

### ISSUE THREAD

**Issue by JGitBuddy** [grokability/snipe-it#15674]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After running the CMD prompt commands below as administrator, the version number from the Snipe-IT's admin web page should change to v7.0.13, but it does not do that:

cd C:\inetpub\wwwroot\snipe-it
git pull
php upgrade.php --skip-php-compatibility-checks

### Reproduction steps

1. Open Internet Information Services (IIS) Manager as administrator.
2. Under Connections, right-click the host name, and click Stop.
3. Open CMD prompt as administrator.
4. From the CMD prompt window, run the following commands line by line:

cd C:\inetpub\wwwroot\snipe-it
git pull
php upgrade.php --skip-php-compatibility-checks

5. Go back to the Internet Information Services (IIS) Manager, and under Connections, right-click the host name, and click Start.

6. Go to the Snipe-IT's admin web page and check the version number.

### Expected behavior

The version number from the Snipe-IT's admin web page should change to v7.0.13.

### Screenshots

![CMD Prompt Screenshot](https://github.com/user-attachments/assets/6aafaf10-ec7d-4cab-a634-2e7868c53457)

### Snipe-IT Version

v7.0.9

### Operating System

Windows 11

### Web Server

10.0.22621.1

### PHP Version

8.1.27

### Operating System

Windows 11

### Browser

Google Chrome

### Version

129.0.6668.100

**Comment by spencerrlongg** [comment]
It's the `git pull` that's not working, so there's nothing to upgrade - you'll need to `git stash` or `git reset --soft` first. I'm not sure why there would be changes to those files though.

**Comment by JGitBuddy** [comment]
> It's the `git pull` that's not working, so there's nothing to upgrade - you'll need to `git stash` or `git reset --soft` first. I'm not sure why there would be changes to those files though.

Okay, let me try those commands and do the upgrade command again.

**Comment by JGitBuddy** [comment]
`git stash` worked for me.

Thanks!
