### ISSUE TITLE
Incorrect capitalization of dashboard section titles

### ISSUE THREAD

**Issue by NebelKreis** [grokability/snipe-it#15686]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

On the Snipe-IT dashboard, the section titles for “Assets”, “Licenses”, “Consumables”, “Components”, and “Users” are incorrectly displayed in lowercase letters. This affects languages such as German, where nouns must be capitalized for correct linguistic presentation. The current behavior leads to inconsistencies and reduces readability for users who expect proper capitalization based on their language.

### Reproduction steps

1. Navigate to the Snipe-IT admin dashboard.
2. Observe the section titles for “Assets”, “Licenses”, “Consumables”, “Components”, and “Users”.
3. Notice that the titles are displayed entirely in lowercase, regardless of the language setting.

### Expected behavior

The section titles on the dashboard should display proper capitalization according to the rules of the selected language. For example, in German, all nouns should be capitalized (e.g., “assets” should appear as “Assets”).

### Snipe-IT Version

v7.0.13

### Operating System

Ubuntu 22.04.5 LTS

### Web Server

Apache 2.4.52 

### PHP Version

8.1.2

### Operating System

Windows

### Browser

Google Chrome

**Comment by snipe** [comment]
Fixed in #15687
