### ISSUE TITLE
[Feature Request]: Manufacturer and Model No. for components

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15695]
### Is your feature request related to a problem? Please describe.

Cannot add Manufacturer and Model No. information for the Components.

### Describe the solution you'd like

Components should have same representation Accessories have: ability to add Manufacturer and Model No. information for the components and be visible in 'Asset Manufacturers' and list. 

### Describe alternatives you've considered

Looks like this feature was implemented long time ago, but didn't receive needed attention since. It's not normal when you can add  Supplier and Order No., but not Manufacturer and Model information.

Artist interpretation bellow.
![image](https://github.com/user-attachments/assets/34a8a25e-fe71-4621-8174-64d6ddbd02a7)
![image](https://github.com/user-attachments/assets/7fa9a449-38de-43f3-bebc-ff9fda495ab4)

**Comment by snipe** [comment]
This is on master now

**Comment by swift2512** [comment]
Thank you @snipe. You're a star. :)
