### ISSUE TITLE
avif image not displayed on fullscreen in asset view

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#15701]
### Debug mode

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I created an asset and uploaded an image on the asset model.
The image is displayed correctly and when I click on it in for example the all assets page, it displays it correctly in fullscreen. But when I click it to view in fullscreen on the asset page, I get some strange hyroglyphes (I guess it's the file content of the image).

### Reproduction steps

1. create an asset
2. upload an avig image file
3. view it in fullscreen on the asset page

### Expected behavior

the image should be displayed like on the all assets page.

### Screenshots

![image](https://github.com/user-attachments/assets/fa55499f-d052-443e-8166-2624af94f861)

### Snipe-IT Version

v7.0.13 build 15514 (gdc0949da7)

### Operating System

Ubuntu Server

### Web Server

don't know (installed with your installier)

### PHP Version

8.1.2-1ubuntu2.19

### Operating System

Windows 10 Pro

### Browser

Microsoft Edge for Business

### Version

128.0.2739.54

**Comment by snipe** [comment]
Is it possible to attach a sample avif file here so we can try to reproduce?

**Comment by snipe** [comment]
Was just able to reproduce this

**Comment by snipe** [comment]
This is now fixed on master

**Comment by floschoepfer** [comment]
Uhh, that was a fast one! Thank you so much @snipe ! Just tested it and works now for me.

**Comment by snipe** [comment]
@floschoepfer - no problem :) Thanks for letting us know about it. (avifs don't come up much.)
