### ISSUE TITLE
Add locations without LDAP Search OU

### ISSUE THREAD

**Issue by Steve-M-C** [grokability/snipe-it#15708]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In previous releases (not sure when this changed), the "LDAP Search OU" was either not required, or didn't exist for locations. 
In the current release (7.0.13) I'm unable to add/edit any locations without specifying an "LDAP Search OU".
Is there a config option I'm missing somewhere, or is this a bug?

### Reproduction steps

1. Create a new location
2. Leave the "LDAP Search OU" field blank
3. You receive an error, stating that the field is required

...

### Expected behavior

Be able to save a location (or edit an existing one) without having to supply an LDAP Search OU.

### Snipe-IT Version

7.0.13

### Operating System

Ubuntu 22.04.5 LTS

### Web Server

Apache

### PHP Version

8.1.2

**Comment by snipe** [comment]
This was already fixed in https://github.com/snipe/snipe-it/pull/15669
