### ISSUE TITLE
[Feature Request]: API Consumable Checkout add Quantity Body Parameter 

### ISSUE THREAD

**Issue by ganslm** [grokability/snipe-it#15717]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Add Quantity Body Parameter to API Consumable Checkout (just like for Accessories).

**Comment by snipe** [comment]
That already exists. Just pass `checkout_qty` as a parameter

**Comment by snipe** [comment]
Nope, I lied - was looking at the wrong file.
