### ISSUE TITLE
ERR : Custom Asset Report

### ISSUE THREAD

**Issue by toannguyenh1603** [grokability/snipe-it#15723]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I Generate report on Module Custom Asset Report but the result returned is excel containing html code . Please help me fix it .

### Reproduction steps

1.Report
2.Custom Asset Report
3.Generate

### Expected behavior

can export data normally

### Snipe-IT Version

v7.0.12 build 15249 (g713bb104e)

### Operating System

ubuntu

### Web Server

NON

### PHP Version

8.1.29

**Comment by snipe** [comment]
We'd need your app logs to see what the error is. (Also you should probably upgrade to latest.)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
