### ISSUE TITLE
Some fields in search in 'Activity Report' return no results

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15726]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

1. Filter by **Admin** column stops working when you introduce _space followed by a letter_ in the Search query, in languages EN-US and LT-LT (didn't test other).
2. Search in Lithuanian only works by **To**, **IP Address**, **User Agent** and **Action Source** fields.
3. Looks like search for **Action** field only looks in English table. Query with 'išduoti' gives empty list, but checkout fetches list with entries. (Same behaviour in Lithuanian, Spanish, russian and probably every other language).
![image](https://github.com/user-attachments/assets/f0c69ed3-0488-4203-8190-0a5fcf7031a8)
4. Search doesn't work for ID, DATE, TYPE, ITEM columns.
5. Not all fields are sortable.

### Reproduction steps

1. Just do the search.

### Expected behavior

1. You can sort by any column.
2. Search queries work on all table columns.
3. **Action** column filters by set language if it's other than English.

### Snipe-IT Version

7.0.13

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.3

**Comment by snipe** [comment]
> Filter by Admin column stops working when you introduce space followed by a letter in the Search query, in languages EN-US and LT-LT (didn't test other).

That would be expected if the username does not have a space after it.

> Search in Lithuanian only works by To, IP Address, User Agent and Action Source fields.

We do not currently search across all fields in the action logs table. 

> Looks like search for Action field only looks in English table.

That's correct, as the key is stored in English in the action_logs table. There isn't really a way around that at this point, since folks could have multiple languages that each admin uses, and we have to pick a consistent name for the action in the database.

**Comment by swift2512** [comment]
I am not searching by the username, but by the name/surname. Example bellow.

I have 'Super User' with login **admin**. When I enter **Super** in searchbox, I get 8011 results. When I put **Super a**, I get only 51 results and somehow user 'test admin' (tadmin) gets into both lists. This **tadmin** was created by 'Super user', but it's mentione only in tadmin's profile (Created At 2024-10-04 08:21 AM - Super Admin). So it
![image](https://github.com/user-attachments/assets/e0b0d395-e3d0-4cb3-85f4-4b755cb61cfe)

**Comment by swift2512** [comment]
> That's correct, as the key is stored in English in the action_logs table. There isn't really a way around that at this point, since folks could have multiple languages that each admin uses, and we have to pick a consistent name for the action in the database.

In this case, actions should be left in English, regardless of which language user uses. I don't find a word to describe this: when in Lithuanian you search by English 'update', you get entries with action's status 'atnaujinti', but you don't get any results when searching by 'atnaujinti'.
![image](https://github.com/user-attachments/assets/03ed9091-2c5c-4673-9a49-eddc09cd8488)

**Comment by snipe** [comment]
I think this would cause more confusion than clarity at this point. I'll consider some other ways to handle, but I'll close this for now.
