### ISSUE TITLE
Locations cannot be updated because field LDAP OU Search is required

### ISSUE THREAD

**Issue by LRA-Fr3d** [grokability/snipe-it#15738]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When updating locations, the information cannot be saved as the “LDAP OU Search” field has become a mandatory field since one of the last updates. Even if you do not use LDAP synchronization for locations or have used it before.

### Reproduction steps

1. Open a location to edit.
2. Change something and leave "LDAP OU Search" empty, as it was before.
3. Click Save.
4. Cannot be saved because field is mandatory.

### Expected behavior

1. Open a location to edit.
2. Change something and leave "LDAP OU Search" empty, as it was before.
3. Click Save.
4. **Changes will be saved.**

### Screenshots

![image](https://github.com/user-attachments/assets/83ec243a-5cab-402e-8f2f-f09762a90fdd)
![image](https://github.com/user-attachments/assets/9a5561e5-e907-4635-9c29-69fa07f0ea69)

### Snipe-IT Version

v7.0.13 - build 15514 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.19

**Comment by snipe** [comment]
This was already fixed in https://github.com/snipe/snipe-it/pull/15669
