### ISSUE TITLE
[Feature Request]: Ability to check in Accessory to a different Location

### ISSUE THREAD

**Issue by Toby737** [grokability/snipe-it#15733]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

It would be great to be able to assign a Location when checking in an Accessory.
Similar to the Checkin procedure for Assets.
In cases where a user is returning an Accessory to a different office location, it would be great to be able to check in the Accessory and assign it to that particular office location.
Example:
Tim is travelling and picks up a Power Plug (Accessory), from Location, Office 1.
Several days later is back home and hands back the extra Power Plug to an IT member in Location, Office 3.
IT Checks In the Power Plug and selects his Location, Office 3 and it becomes part of his stock.

**Comment by snipe** [comment]
This is already in progress (checkout out accessories to location, etc)
