### ISSUE TITLE
Snipe-IT version 6.4.2 to 7.0.12 Migrate Issue

### ISSUE THREAD

**Issue by jaisanjay0** [grokability/snipe-it#15743]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We are using Snipe-IT version 6.4.2, and we are trying to upgrade to version 7.0.12, but the migration file (2024_07_26_143301_add_checkout_for_all_types_to_accessories) is not executing
![add checkout error](https://github.com/user-attachments/assets/4aedd1cc-cc82-4403-be81-a2a1e3c8c94e)

### Reproduction steps

1. We try to upgrade latest version one by one (migrate version : 7.0, 7.0.5, 7.0.8, 7.0.10  - successfully migrated) but ( 7.0.11, 7.0.12 and 7.0.13 - updated and migrate the file (add_checkout_for_all_types_to_accessories) migration is failed
2.  update composer and PHP version 
3. Latest version 7.0.13 installed then update the SQL file still same issue
4. check Dependencies files. 
5. drop the accessories_checkout  database and rename to accessories_users` to `accessories_checkout after migrating sub accessories item list is not showing 
5. generate to new APP_KEY

### Expected behavior

attached logs file
[laravel.log](https://github.com/user-attachments/files/17546301/laravel.log)

### Snipe-IT Version

6.4.2

### Operating System

ubuntu 20.4

### Web Server

Apache

### PHP Version

8.3.7

### Operating System

Windows 11 

### Browser

Chrome

### Version

130.0.6723.70

### Error messages

```shell
[2024-10-28 16:50:10] production.ERROR: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'accessories_checkout' already exists (Connection: mysql, SQL: rename table `accessories_users` to `accessories_checkout`) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'accessories_checkout' already exists (Connection: mysql, SQL: rename table `accessories_users` to `accessories_checkout`) at /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
[stacktrace]
#0 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback()
#1 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\\Database\\Connection->run()
#2 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(110): Illuminate\\Database\\Connection->statement()
#3 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(602): Illuminate\\Database\\Schema\\Blueprint->build()
#4 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(548): Illuminate\\Database\\Schema\\Builder->build()
#5 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\\Database\\Schema\\Builder->rename()
#6 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/database/migrations/2024_07_26_143301_add_checkout_for_all_types_to_accessories.php(18): Illuminate\\Support\\Facades\\Facade::__callStatic()
#7 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(493): Illuminate\\Database\\Migrations\\Migration@anonymous->up()
#8 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(410): Illuminate\\Database\\Migrations\\Migrator->runMethod()
#9 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(419): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#10 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->runMigration()
#11 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#12 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(756): Illuminate\\Console\\View\\Components\\Task->render()
#13 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->write()
#14 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(181): Illuminate\\Database\\Migrations\\Migrator->runUp()
#15 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(124): Illuminate\\Database\\Migrations\\Migrator->runPending()
#16 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(90): Illuminate\\Database\\Migrations\\Migrator->run()
#17 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#18 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#19 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#20 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#22 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#24 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#25 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#26 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#27 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#28 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#29 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#30 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#31 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/artisan(33): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}

[previous exception] [object] (PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'accessories_checkout' already exists at /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Connection.php:587)
[stacktrace]
#0 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Connection.php(587): PDOStatement->execute()
#1 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback()
#3 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\\Database\\Connection->run()
#4 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(110): Illuminate\\Database\\Connection->statement()
#5 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(602): Illuminate\\Database\\Schema\\Blueprint->build()
#6 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(548): Illuminate\\Database\\Schema\\Builder->build()
#7 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\\Database\\Schema\\Builder->rename()
#8 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/database/migrations/2024_07_26_143301_add_checkout_for_all_types_to_accessories.php(18): Illuminate\\Support\\Facades\\Facade::__callStatic()
#9 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(493): Illuminate\\Database\\Migrations\\Migration@anonymous->up()
#10 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(410): Illuminate\\Database\\Migrations\\Migrator->runMethod()
#11 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(419): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#12 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->runMigration()
#13 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#14 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(756): Illuminate\\Console\\View\\Components\\Task->render()
#15 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->write()
#16 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(181): Illuminate\\Database\\Migrations\\Migrator->runUp()
#17 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(124): Illuminate\\Database\\Migrations\\Migrator->runPending()
#18 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(90): Illuminate\\Database\\Migrations\\Migrator->run()
#19 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#20 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#21 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#22 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#24 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#25 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#26 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#27 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#28 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#29 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#30 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#31 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#32 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#33 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/artisan(33): Illuminate\\Foundation\\Console\\Kernel->handle()
#34 {main}
"}
```

**Comment by snipe** [comment]
This usually means something in your migrations got donked up, which sometimes happens if there's output from a migration but the log file couldn't be written to, for example.

Try running this via command line SQL:

```
INSERT INTO migrations (migration, batch) VALUES ('2024_07_26_143301_add_checkout_for_all_types_to_accessories', 30);
```

then run migrations again and tell me what it says.

**Comment by jaisanjay0** [comment]
Since you provide SQL command update migration successfully completed but Accessory category info details didn't showing.

Example : 
old version 6.4.2
![image](https://github.com/user-attachments/assets/3d7de1cb-b522-4bff-8b19-c90c5b22e4d1)

After upgrade snipeit 7.0.12
There is not a list for accessory category info details, but we have searched for any accessory details, and the data is showing.

![image](https://github.com/user-attachments/assets/1964b7cb-7721-48eb-bb25-82daae4e8bdf)


Debug mode Logs details: 

[2024-11-01 12:37:32] production.ERROR: Attempt to read property "id" on null {"userId":2152,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/app/Http/Transformers/AccessoriesTransformer.php:90)#5 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#6 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#7 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#8 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\Routing\Route->run()
#9 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#12 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(159): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(125): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest()
#14 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(87): Illuminate\Routing\Middleware\ThrottleRequests->handleRequestUsingNamedLimiter()
#15 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#16 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/app/Http/Middleware/CheckLocale.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckLocale->handle()
#18 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Auth\Middleware\Authenticate->handle()
#20 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Pipeline\Pipeline->then()
#22 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router->runRouteWithinStack()
#23 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router->runRoute()
#24 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router->dispatchToRoute()
#25 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#26 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#27 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware->handle()
#29 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#31 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\HandleCors->handle()
#33 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\PreventBackHistory->handle()
#35 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\SecurityHeaders->handle()
#37 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#39 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#40 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#42 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#43 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckForDebug->handle()
#45 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/app/Http/Middleware/CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckForSetup->handle()
#47 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#49 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#51 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\StartSession->handle()
#52 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#54 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\NoSessionStore->handle()
#56 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle()
#58 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#60 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#61 /www/wwwroot/Testsession/Snipe-it/snipe-it-7.0.12/public/index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#62 {main}

**Comment by jaisanjay0** [comment]
Since issue not resolved, kindly share your guidelines.

**Comment by snipe** [comment]
Run upgrade.php again and bring yourself up to latest and/or tell me what's on line 90 of the AccessoriesTransformer.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
