### ISSUE TITLE
Mail could not be sent

### ISSUE THREAD

**Issue by beemestd** [grokability/snipe-it#15745]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Mail could not be sent. No additional error message provided. Check your mail settings and your app log.

### Reproduction steps

1. Setup Pre flight Done 
2. Click Send Test - Green Tick , however did not receive any email. 
3. Continue setup, open the admin/settings , click Send Test 
4. Prompt Error : Mail could not be sent. 
5. Telnet to mail server 587 - 220 mx.xxx ESMTP xxx
6.

### Expected behavior

Done setup with version6, ubuntu v20, the email can sent out.

### Screenshots

![Screenshot 2024-10-29 162336](https://github.com/user-attachments/assets/9f3e2a4f-0f8c-45e8-8648-716504a59a2a)

### Snipe-IT Version

7.0.13

### Operating System

Ubuntu 

### Web Server

Apache

### PHP Version

8.3

### Operating System

Ubuntu

### Additional context

Fresh Install 
Ubuntu 24
Manual Installation

**Comment by DarrenRainey** [comment]
Do you have any logs from the mail server itself? Do you have TLS/SSL enabled for mail?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
