### ISSUE TITLE
[Feature Request]: Own Sections

### ISSUE THREAD

**Issue by Rolotov** [grokability/snipe-it#15753]
### Is your feature request related to a problem? Please describe.

There are only pre selected sections (Assets; Licences, Accessories,...), but I found no possibility to create own secitons

### Describe the solution you'd like

I would like to have a way to create own sections

**Comment by snipe** [comment]
Could you expound on that a little? What would "own section" look like? How would it be different than the sections we already have? Each section has its own business logic around it.

**Comment by Rolotov** [comment]
Hi, sure. At the moment we have different software programms and contracts together. I would be very helpful if we could create a own section for contracts

**Comment by snipe** [comment]
That's not currently on the short term roadmap.
