### ISSUE TITLE
Unable to upgrade to latest version

### ISSUE THREAD

**Issue by lvschnider** [grokability/snipe-it#15769]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am trying to update our snipe version from 6.3.2 to the latest stable version. 

I run the git pull command and I receive the below results. 

WELCOME TO THE SNIPE-IT UPGRADER! 
--------------------------------------------------------

This script will attempt to: 

- validate some very basic .env file settings 
- check your PHP version and extension requirements 
- check directory permissions 
- do a git pull to bring you to the latest version 
- run composer install to get your vendors up to date 
- run migrations to get your schema up to date 
- clear out old cache settings

Launching using branch: master
Found PHP requirements, will check for PHP > 8.1.0 and < 8.4.0
Proceed with upgrade? [Y/n]: y

--------------------------------------------------------
STEP 1: Checking .env file: 
- Your .env is located at /var/www/html/snipeit/.env 
--------------------------------------------------------

√ Your APP_KEY is not blank. 
√ Your APP_URL is not null or blank. It is set to http://10.16.1.10
√ Your APP_URL is set to http://10.16.1.10 and starts with the protocol (https:// or http://)
√ Your APP_URL (http://10.16.1.10) does not have a trailing slash.

--------------------------------------------------------
STEP 2: Checking PHP requirements: (Required PHP >=8.1.0 - <8.4.0) 
--------------------------------------------------------

√ Current PHP version: (8.1.2-1ubuntu2.19) is at least 8.1.0 and less than 8.4.0! Continuing... 
FYI: The php.ini used by this PHP is: /etc/php/8.1/cli/php.ini

Checking Required PHP extensions... 

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ sodium is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 3: Checking directory permissions: 
--------------------------------------------------------

--------------------------------------------------------
The following directories/files do not seem writable: 
--------------------------------------------------------
✘ PERMISSIONS ERROR: /var/www/html/snipeit/bootstrap/cache is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage/logs is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage/logs/laravel.log is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage/framework is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage/framework/cache is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage/framework/sessions is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage/framework/views is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage/app is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage/app/backups is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage/app/backup-temp is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/storage/private_uploads is NOT writable
✘ PERMISSIONS ERROR: /var/www/html/snipeit/public/uploads is NOT writable
--------------------- !! ERROR !! ----------------------
Please check the permissions on the directories above and re-run this script.
------------------------- :( ---------------------------

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Update the verison. 

### Snipe-IT Version

6.3.2

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.0

**Comment by snipe** [comment]
The output is telling you what's wrong - you need to fix the permissions on those directories.
