### ISSUE TITLE
Not sure how else to submit this

### ISSUE THREAD

**Issue by ZuluPilgrim** [grokability/snipe-it#15761]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have tried e-mailing support@snipeitapp.com but don't get any reply. I think our corporate e-mail is going to their spam again. I have also tried calling 1-844-4-SNIPE-IT (844-476-4734) but keep getting a message that the number is no longer active. The number did work a week or so ago.

If someone could please nudge the desk to check their Spam for e-mail from OneSchool Global?

### Reproduction steps

N/A

### Expected behavior

N/A

### Snipe-IT Version

N/A

### Operating System

N/A

### Web Server

N/A

### PHP Version

N/A

**Comment by snipe** [comment]
Hi @ZuluPilgrim - I see several tickets in the helpdesk from OneSchool, but the most recent one is from 19 days ago. We do not have spam filtering set up on the helpdesk, so I'm not sure where anything could be getting caught up.

**Comment by ZuluPilgrim** [comment]
HI @snipe  thanks for coming back to me.

I have managed to reset my work e-mail a........b.......@nz.o.....z but can't see any ticket in the portal that I sent last week.
![image](https://github.com/user-attachments/assets/5bbf8511-d3a4-45e7-9177-b0d048d0f309)

The tickets you mention might be against the main account e-mail but I cannot seem to reset the password to gain access to that.

**Comment by ZuluPilgrim** [comment]
Thanks, was able to reset my password and can see the tickets in the support portal. So will continue for there.

**Comment by snipe** [comment]
Excellent - I'll see you there then :)
