### ISSUE TITLE
[Feature Request]: Asset management by Department

### ISSUE THREAD

**Issue by thaibm92** [grokability/snipe-it#15770]
### Is your feature request related to a problem? Please describe.

As I see it, the software currently supports all users in managing their own assets. However, in certain special cases, such as when an employee suddenly leaves, it becomes challenging to track those assets.

### Describe the solution you'd like

I would like to have an additional feature for asset management by department.
This means there would be one or more accounts in that department that can only see assets assigned to that department (currently, all users can see everything).
Due to security reasons, accounts from different departments should not be able to view each other's assets; only administrators should have access to see everything.

I hope this idea will be approved and released as soon as possible. Thank you very much!

**Comment by snipe** [comment]
This is not currently on the short term roadmap. You can use companies this way and enable Full Multiple Company Support to get the functionality you're looking for.
