### ISSUE TITLE
[Feature Request]: Budget string field

### ISSUE THREAD

**Issue by mhorakpdx** [grokability/snipe-it#15772]
### Is your feature request related to a problem? Please describe.

Need a field for budget strings.

### Describe the solution you'd like

As a nonprofit, we must buy and assign our small assets on grants. We'd love to see a budget string field to which we could add those strings. We'd also like to pull reports showing what grants paid for what assets and the total cost of the assets under those strings. 

### Describe alternatives you've considered

Adding the strings to the notes field, but that's useful for other notes, such as cell phone numbers.

**Comment by snipe** [comment]
You'd want to use custom fields for that, I think. https://snipe-it.readme.io/docs/custom-fields

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/custom-fields">Custom Fields</a></strong></div><div>Custom fields and fieldsets are available in Snipe-IT versions 2.1.0-pre and later. Custom fields allow you to track additional information about your assets that the default asset attributes don't cover. Check out the short video tutorial below for a full walkthrough: Snipe-IT Turbo Tutorial: Custo...</div></blockquote>
