### ISSUE TITLE
Custom Field by category

### ISSUE THREAD

**Issue by sahernandez98** [grokability/snipe-it#15777]
### Is your feature request related to a problem? Please describe.

Is not a problem 

### Describe the solution you'd like

From our point of view, custom fields should be able to be configured based on categories and not models, since there may be custom fields that are for laptops, but there are many different models and brands of laptops, so it would be easier to associate the group of custom fields with the laptop category, which already includes all the models of it.

**Comment by snipe** [comment]
It's been suggested before but would pretty dramatically impact existing users workflows, so I don't see this on the short term roadmap. :(
