### ISSUE TITLE
[Feature Request]: Hide Cost Columns

### ISSUE THREAD

**Issue by buritobell** [grokability/snipe-it#15781]
### Is your feature request related to a problem? Please describe.

I want to hide the purchase column from some of my staff who do not need to see the finances of the IT department. 

### Describe the solution you'd like

I'd like to add a new permission to hide that column from view on a per group basis. 

### Describe alternatives you've considered

I've considered encrypting the column, but I would prefer to hide on a per column basis, I'm sure down the line I'll want to hide other columns as well. I thing this is a general want for granularity and price is the only sensitive column in the app by default.

### Additional context

I've seen other posts about this, if the hide from self is an option for checked out assets. I would like to do it on the list all assets page. I'd assume (perhaps naively) that it would work for the other columns as well with some tweaking?

**Comment by snipe** [comment]
We only provide the ability to hide purchase cost from unprivileged users looking at their own items that are assigned to them at this time.
