### ISSUE TITLE
Licence checkout note nowhere visible

### ISSUE THREAD

**Issue by FlorinBuffet** [grokability/snipe-it#15798]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When checking out a licence you can define a note. This note can be found nowhere...

### Reproduction steps

1. Create Licence
2. Checkout Licence with Note
3. Try to find the note

### Expected behavior

The note should be available when you look at the seats of a licence.

### Snipe-IT Version

 v6.3.4 - build 13139

### Operating System

Docker

### Web Server

Docker

### PHP Version

8.1.22

**Comment by snipe** [comment]
The note is visible in the Seats tab. https://demo.snipeitapp.com/licenses/2#seats

<img width="1035" alt="Screenshot 2024-11-12 at 9 20 20 PM" src="https://github.com/user-attachments/assets/9914e68b-f305-4bfe-81d7-74c084572449">
