### ISSUE TITLE
admin settings shows 404 softaculous install 

### ISSUE THREAD

**Issue by gaborbit** [grokability/snipe-it#15791]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

this works https://mysite.xyz/snipe/public/admin
but any other URL under this gives error message, like this: https://mysite.xyz/snipe/public/admin/settings

Not Found
The requested URL was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Snipe-IT Version | v7.0.13 - build 15514 (master)
PHP Version | 8.1.30
cPanel Version | 118.0 (build 24)
Apache Version | 2.4.62
MySQL Version | 8.0.37

### Reproduction steps

1. fresh install in softaculous 
2.  /public/admin/settings works fine
3. /public/admin/settings shows 404

### Expected behavior

/public/admin/settings should work 

### Snipe-IT Version

7.0.13

### Operating System

Linux Rocky

### Web Server

Apache

### PHP Version

8.1.30

### Operating System

Windows

### Browser

Edge

### Version

130.0.2849.80

### Error messages

```shell
404
```

### Additional context

fresh install

**Comment by snipe** [comment]
You'd need to talk to Softaculous about that - we don't control any of their settings or deployment process,  nor do we even have any insight on what they do. :(
