### ISSUE TITLE
[Feature Request]: Include Category in Email Notifications for Asset Management

### ISSUE THREAD

**Issue by NebelKreis** [grokability/snipe-it#15803]
### Is your feature request related to a problem? Please describe.

Currently, email notifications in Snipe-IT for asset requests, approvals, and returns include information such as the asset model, but they do not display the asset's **Category**. This can lead to confusion, as it’s not always clear from the model name alone what type of asset is being referred to. Without the category, users and administrators may need to cross-reference information manually to confirm what kind of asset is involved, which can be inefficient.

### Describe the solution you'd like

I propose adding the **Category** field to the asset information table in email notifications regarding asset management. By including the category, email recipients will have a clearer understanding of the asset type directly within the notification, improving efficiency and reducing ambiguity. 

### Key Details:

- **Field to Add**: Category
- **Configuration Option**: A setting that allows administrators to choose whether the **Category** field is included in these email notifications. This would provide flexibility for organizations that prefer a streamlined notification format.

### Describe alternatives you've considered

As an alternative, the **Category** field could simply be included by default in all relevant email notifications, without the need for an additional setting. This approach would ensure that the information is consistently available to all users.

### Additional context

Including the **Category** field in mail notifications will improve asset tracking and clarity in communications, especially for teams managing a wide variety of assets. This enhancement will allow users and administrators to quickly identify the type of asset in each mail notification, reducing the need for additional verification steps.

**Comment by snipe** [comment]
Please always provide us with the version you're currently running, per the issue template.
