### ISSUE TITLE
Version Correction

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#15815]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Version number for latest SnipeIT installation displaying incorrect version on download page.

Download page = 7.1.14
Installation = 7.0.14

### Reproduction steps

Version number for latest SnipeIT installation displaying incorrect version on download page.

Download page = 7.1.14
Installation = 7.0.14

### Expected behavior

Version number for latest SnipeIT installation displaying correctly.

Download page = 7.0.14
Installation = 7.0.14

### Screenshots

![SnipeIT](https://github.com/user-attachments/assets/3de29bd4-d3f1-4d69-bd43-0502046c7944)

### Snipe-IT Version

7.0.14

### Operating System

Server 2022

### Web Server

WAMP

### PHP Version

8+

**Comment by snipe** [comment]
This has already been addressed in the release notes.
