### ISSUE TITLE
Upgrading From 6.4.1 to 7.1.14 Fails - error: git-remote-https died of signal 4

### ISSUE THREAD

**Issue by SCPPD-IT** [grokability/snipe-it#15829]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

git pull is giving the error of "error: git-remote-https died of signal 4."

### Reproduction steps

1. php upgrade.php

3. On step 6, I am getting this error.
Git is installed.
error: git-remote-https died of signal 4

4. Upgrade says it was successful, but it wasn't.
...

### Expected behavior

The upgrade should work.

### Screenshots

--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- validate some very basic .env file settings
- check your PHP version and extension requirements
- check directory permissions
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

Launching using branch: master
Found PHP requirements, will check for PHP > 8.1.0 and < 8.4.0
Proceed with upgrade? [y/N]: y

--------------------------------------------------------
STEP 1: Checking .env file:
- Your .env is located at /var/www/html/snipe-it/.env
--------------------------------------------------------

√ Your APP_KEY is not blank.
√ Your APP_URL is not null or blank. It is set to http://snipeit.scppd.net
√ Your APP_URL is set to http://snipeit.scppd.net and starts with the protocol (https:// or http://)
√ Your APP_URL (http://snipeit.scppd.net) does not have a trailing slash.

--------------------------------------------------------
STEP 2: Checking PHP requirements: (Required PHP >=8.1.0 - <8.4.0)
--------------------------------------------------------

√ Current PHP version: (8.1.2-1ubuntu2.19) is at least 8.1.0 and less than 8.4.0! Continuing...
FYI: The php.ini used by this PHP is: /etc/php/8.1/cli/php.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ sodium is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 3: Checking directory permissions:
--------------------------------------------------------

√ /var/www/html/snipe-it/bootstrap/cache is writable
√ /var/www/html/snipe-it/storage is writable
√ /var/www/html/snipe-it/storage/logs is writable
√ /var/www/html/snipe-it/storage/logs/laravel.log is writable
√ /var/www/html/snipe-it/storage/framework is writable
√ /var/www/html/snipe-it/storage/framework/cache is writable
√ /var/www/html/snipe-it/storage/framework/sessions is writable
√ /var/www/html/snipe-it/storage/framework/views is writable
√ /var/www/html/snipe-it/storage/app is writable
√ /var/www/html/snipe-it/storage/app/backups is writable
√ /var/www/html/snipe-it/storage/app/backup-temp is writable
√ /var/www/html/snipe-it/storage/private_uploads is writable
√ /var/www/html/snipe-it/public/uploads is writable

--------------------------------------------------------
STEP 4: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Determining files to backup...
Zipping 496 files and directories...
Created zip containing 496 files and directories. Size is 70.56 MB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!

--------------------------------------------------------
STEP 5: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.
--------------------------------------------------------
STEP 6: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
error: git-remote-https died of signal 4
Already on 'master'
error: git-remote-https died of signal 4
-- No local changes to save
-- Your branch is up to date with 'origin/master'.
--
--------------------------------------------------------
STEP 7: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ Deleting bootstrap/cache/services.php. It is no longer used.
√ Deleting bootstrap/cache/config.php. It is no longer used.
√ No vendor/symfony/translation/TranslatorInterface.php, so nothing to delete.

-- Configuration cache cleared!
-- Failed to clear cache. Make sure you have the appropriate permissions.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
STEP 8: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- Running the app in production mode.
√ Local composer.phar detected, so we'll use that.

-- Updating local composer.phar

You are already using the latest available Composer version 2.8.2 (stable channel).

Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package fruitcake/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead.
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package nunomaduro/larastan is abandoned, you should avoid using it. Use larastan/larastan instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
82 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> @php artisan vendor:publish --force --tag=livewire:assets --ansi
Generating optimized autoload files
Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel-notification-channels/google-chat
Discovered Package: laravel-notification-channels/microsoft-teams
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
Generated optimized autoload files containing 7995 classes

Discovered Package: arietimmerman/laravel-scim-server
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: laravel-notification-channels/google-chat
Discovered Package: laravel-notification-channels/microsoft-teams
Discovered Package: laravel/passport
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: livewire/livewire
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: spatie/laravel-backup
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
--------------------------------------------------------
STEP 9: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
STEP 10: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
STEP 11: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!
--------------------------------------------------------

### Snipe-IT Version

6.4.1

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.2

**Comment by snipe** [comment]
Hm, we haven't seen that one before, but I'm pretty sure it's a server config issue, not something on our end.

https://bugs-devel.debian.org/cgi-bin/bugreport.cgi?bug=1010340
https://discourse.pi-hole.net/t/error-git-remote-https-died-of-signal-4/56558/17

**Comment by snipe** [comment]
Some possible useful suggestions here: https://github.com/orgs/community/discussions/48568#discussioncomment-10108846


<blockquote><img src="https://opengraph.githubassets.com/372bf32899be72773e6ba716f58e76bfdfb7b48da3a402d913ca5c9f54b6824c/orgs/community/discussions/48568" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/community/discussions/48568">How can I fix this serious git clone error? · community · Discussion #48568</a></strong></div><div>Select Topic Area Question Body I tried the following: E:\Workspace\Blockchain>git clone https://github.com/substrate-developer-hub/substrate-node-template.git Cloning into 'substrate-node-template...</div></blockquote>
