### ISSUE TITLE
Error 500 server  on image upload 

### ISSUE THREAD

**Issue by rmdpereira** [grokability/snipe-it#15827]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When creating a new accessory and uploading an image for it, once clicking save, Snipe immediately errors to 500 server error. The image loads prior to clicking save.

Saving the accessory without an image is successful. Going back and adding an image later also gives the 500 server error

### Reproduction steps

1.Add new accessory
2.Upload image file
3.Click Save
...

### Expected behavior

When adding an accessory, it's expected to allow an image upload and then a successful save.

### Snipe-IT Version

7.0.13

### Operating System

Windows Server 2022 Standard

### Web Server

IIS

### PHP Version

8.1.30

**Comment by snipe** [comment]
My guess would be that you don't have gd or imagemagik installed (though without seeing your logs, that's hard to determine), or that the permissions on the directories the files are uploaded to do not allow files to be written. Check permissions on your `storage` directory and all subfolders, and also your `public/uploads` directory and all subdirectories within it.

If you check your app log, it should show you the specific error message.

**Comment by rmdpereira** [comment]
This happened after migrating from snipeit 6.20 to 7.0.13.
 It was working before.
This is not really my area. Where can I find the logs?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
