### ISSUE TITLE
Accepted EULA cannot be downloaded after updating to 7.1.14

### ISSUE THREAD

**Issue by c1thunder** [grokability/snipe-it#15825]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I want to download signed EULA from the system. When I want to download the EULA, the error message " Error: The requested file does not exist on the server." appeared. I can see the signed signature and the files name in history page

![image](https://github.com/user-attachments/assets/36fcf7da-a509-43f0-8ec5-42010fd73200)
![image](https://github.com/user-attachments/assets/38fc4e43-bc63-41aa-88f2-6734ce6772c3)

### Reproduction steps

1. Go to any asset that the user already accepted and signed
2. Go to history page
3. Check the download, signature and file column
4. Click the download
5. The error appeared
...

### Expected behavior

I can download a completed accepted EULA

### Screenshots

![image](https://github.com/user-attachments/assets/31d2da2f-6767-45b2-960c-61b5c78fb72a)
![image](https://github.com/user-attachments/assets/60738071-f26f-4652-9577-83a5f9c8568a)

### Snipe-IT Version

7.1.14

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

8.2.20

### Operating System

Windows 11 Pro

### Browser

Edge

### Version

130.0.2849.80

### Additional context

Upgrade using git

**Comment by LegendEronZ** [comment]
Issue seems to be in [ActionlogController](https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/ActionlogController.php) getStoredEula function.

Storage::exists seems to start from storage already and passing $file to it will try with full file path.

Changed code to the following on my side and now it is working:


```
public function getStoredEula($filename) : Response | BinaryFileResponse | RedirectResponse
    {
        $this->authorize('view', \App\Models\Asset::class);
        $file = config('app.private_uploads').'/eula-pdfs/'.$filename;

        if (Storage::exists('private_uploads/eula-pdfs/'.$filename)) {
            return response()->download($file);
        }

        return redirect()->back()->with('error',  trans('general.file_does_not_exist'));
    }

```

**Comment by snipe** [comment]
Thanks!
