### ISSUE TITLE
[Feature Request]: Please add "Model No." field/column in "Assigned Assets" screen, Thank you!

### ISSUE THREAD

**Issue by ma540x** [grokability/snipe-it#15820]
### Is your feature request related to a problem? Please describe.

Hello folks,
Feature request is not related to a problem, but it would absolutely be helpful if the screen where we can see assets assigned to us, would have that as an optional column to choose to display. We track devices and it would be awesome not just to see the Model (which does exist) but also the Model No field/column.

### Describe the solution you'd like

If you could, please add "Model No." column as an available optional column option that users are able to choose on the "Assets assigned to [X]" page, URL --> http://something.com/account/view-assets

Pasting an image of what I would like to see as options in the Column drop down on that page, Thank you!

![image](https://github.com/user-attachments/assets/d83e7801-31fb-4c3d-ad3b-af19a2ceee36)

### Additional context

Thank you for all you do, Snipe it tool is awesome!

**Comment by snipe** [comment]
Hi there - thanks for opening an issue :)

> We track devices and it would be awesome not just to see the Model (which does exist) but also the Model No field/column.

That screen is only for items assigned to you yourself (or whoever the logged in user is). The model number fields is available throughout the rest of the admin screens. Is there possibly a use-case we're not considering here where you'd be tracking from the "view your own assets" page?

**Comment by ma540x** [comment]
Thank you very much for a super quick response.
You are correct but since we assign assets to many people when they double
check with our admins we often deal with model numbers and not names since
we have many many devices and model no is an easier way to keep it for sure
organized.
Also since there's no link that we're able to click on to get navigated to
that specific asset, it just introduces possibilities to get the info wrong
(when talking to our device admins)

Not a huge deal but we love our model numbers since we have 2,888 assets :)

Thank you for reaching out!

**Comment by ma540x** [comment]
Also another scenario is when we ask folks to return devices due to
shortage (ie someone else requested one and we're out) it would be great
for users to quickly find out who else has this device (ie either link to
click on, individual device or model no for ease of use)

Thanks

**Comment by snipe** [comment]
This is on `master` now
