### ISSUE TITLE
[Feature Request]: Configurable URLs for Profile Pictures

### ISSUE THREAD

**Issue by cooperj** [grokability/snipe-it#15830]
### Is your feature request related to a problem? Please describe.

When creating users inside of Snipe-IT, there is currently an added step of either manually uploading avatars for each user or instructing a user to create their own Gravatar.

Some organisations will have their own internal system for getting user avatars - such as matching usernames, emails, or employee numbers to pictures. This is typically done by a URL such as: `https://staff.example.com/jsmith/avatar`

Other services such as github also support this, if you go to `https://github.com/cooperj.png` you will see my profile picture. 

I cannot see a way of easily customising the URL away from Gravatar, and this has been raised by another user in #14417. 

### Describe the solution you'd like

I would like to see a way customising the URL that is called for getting a user avatar in the `Settings -> Branding` page under the `Load Remote Avatar` option that allows for a super user to modify the URL that is used for Gravatar style user images.

This would most likely be a simple string that is modified with placeholder values suggested as a tooltip informing them that they can specify values such as `{email}`. There should also be a way of specifying a MD5 hash for compatibility with Gravatar. 

### Describe alternatives you've considered

The other way that this could be implemented is by using the script inside of #14659 which has the potential of breaking in further releases. 

Or taking a fork of the repository and manually hard coding the value for each companies specific use case. 

### Additional context

If this is something people are interested in being implemented - I don’t mind spending some time to implement this.

**Comment by snipe** [comment]
We already permit this via import/SCIM/LDAP. For example, azure profiles and google workspace profiles. You just have to add the additional setting in your env to allow that base URL to your CSP headers.

**Comment by cooperj** [comment]
Thanks for the clarification! This seems to be a much better way of managing it :)
