### ISSUE TITLE
[Feature Request]: Asset Acceptance PDF Report

### ISSUE THREAD

**Issue by general07z** [grokability/snipe-it#15832]
### Is your feature request related to a problem? Please describe.

Sometimes the auditor will ask us for the asset acceptance of an asset as PDF form.
So we need to print out the form which shows the asset number, asset name, user name, asset assign date, asset acceptance date and signture of the user.

### Describe the solution you'd like

As Asset Acceptance is important factor.
We need to select the asset and  printout the Asset Acceptance Report which shows the signture and date of the acceptance of the user.
This is required by auditors as well.

**Comment by snipe** [comment]
You can download the associated file that gets created when the user accepts the asset. It includes signature, date, and applicable EULA they agreed to at the time of signing it.
