### ISSUE TITLE
Issue with Receiving Check-In/Check-Out Emails

### ISSUE THREAD

**Issue by impgitsubs** [grokability/snipe-it#15834]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi Team,

I noticed that after checking in/out, I am not receiving the corresponding emails. Could you please check and assist with this issue?

### Reproduction steps

1.Checked the email settings in the categories
2.Checked the functioning of the emails via the test function
3.Tried the debug mode but cannot find any errors

### Expected behavior

Email being sent on checkin/checkout of an asset

### Snipe-IT Version

v7.1.14

### Operating System

CentOS Linux 7

### Web Server

Apache/2.4.6

### PHP Version

PHP 8.3.8

**Comment by vowaof** [comment]
I have the same problem with the Docker Image. 
The test-mail works, but mails on check-in/out don't.
