### ISSUE TITLE
LDAP Sync lots of Red lines with "The first name field is required.The username field is required."

### ISSUE THREAD

**Issue by pvrwizard** [grokability/snipe-it#15837]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When doing an LDAP sync the output lists the users but spread throughout the notes field says
"The first name field is required.The username field is required."

I have gone through every account the BASE DN and they all have a first name and a username. 

All of the users are imported but the output is concerning and makes us think there is something configured wrong. 

### Reproduction steps

1.go to people
2. go to LDAP sync
3. click Synchronize
...

### Expected behavior

I would expect clean output of the imported users or something displayed to indicate which record is generating the error  display the Last name or the Email address of the record that is causing the issue. 

### Screenshots

![image](https://github.com/user-attachments/assets/204775a8-5091-4cad-8062-91dc0c575fc2)

### Snipe-IT Version

7.1.14

### Operating System

Windows Server 2022 Standard

### Web Server

Xampp/apache

### PHP Version

8.1

### Operating System

Windows 11

### Browser

Chrome

### Additional context

fresh install. but has been an issue on every version I have tried.

**Comment by snipe** [comment]
> I would expect clean output of the imported users or something displayed to indicate which record is generating the error display the Last name or the Email address of the record that is causing the issue.

By design, we cannot do that, since we don't have the name, email, etc that's causing the issue, since the issue is that we don't have them. My guess here would be that you've got some incorrect mappings for name/email/etc in the LDAP settings page, so when we're pulling those LDAP records, the field we're looking for doesn't match what's mapped in settings, so it comes back empty. 

@uberbrady do you have any additional thoughts?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
