### ISSUE TITLE
Asset Models Missing

### ISSUE THREAD

**Issue by PP-JN-RL** [grokability/snipe-it#15856]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After the latest update to 7.1.14, when navigating to Settings -> Asset Model, the UI show "No matching records found"
Then creating a new asset, the asset models are listed correctly

### Reproduction steps

1. Click Settings
2. Click Asset Models
3. "No maching records found"

### Expected behavior

This should list all existing asset models

### Snipe-IT Version

v7.0.14

### Operating System

Official Docker Image (Ubuntu)

### Web Server

Official Docker Image (Apache?)

### PHP Version

8.1.2-1ubuntu2.19

**Comment by snipe** [comment]
We'd need to see what's in your application logs, how you upgraded, whether there were any errors when you upgraded, etc.

**Comment by PP-JN-RL** [comment]
We use the official docker image, pulled down the latest version.
I assume the image takes care of upgrading the DB? What logs can I provide to help you track down the issue?

Oddly enough I can see all the asset models when creating a new asset:
![image](https://github.com/user-attachments/assets/19546b0b-dbc1-4615-8f2a-6c33fbb8ce29)

But the view is empty when using Settings -> Asset Models:
![image](https://github.com/user-attachments/assets/edd89c1f-5f8f-4fa8-b9e5-50f6efcdc621)

I believe this is the error it throws when loading the asset model view:

```[15:43:58] LOG.error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_by' in field list is ambiguous (Connection: mysql, SQL: select `models`.`id`, `models`.`image`, `models`.`name`, `model_number`, `min_amt`, `eol`, `created_by`, `requestable`, `models`.`notes`, `models`.`created_at`, `category_id`, `manufacturer_id`, `depreciation_id`, `fieldset_id`, `models`.`deleted_at`, `models`.`updated_at`, (select count(*) from `assets` where `models`.`id` = `assets`.`model_id` and `assets`.`deleted_at` is null) as `assets_count` from `models` left join `manufacturers` on `models`.`manufacturer_id` = `manufacturers`.`id` where `models`.`deleted_at` is null order by `manufacturers`.`name` asc limit 100 offset 0) {
    "userId": 1,
    "exception": {
        "errorInfo": [
            "23000",
            1052,
            "Column 'created_by' in field list is ambiguous"
        ],
        "connectionName": "mysql"
    }
}```

**Comment by PP-JN-RL** [comment]
Ok, I think I have found the issue, but I'm not quite sure yet how it happened.
There was a commit to specify the table name in AssetModelsController.php. This does not seem to have made it into the docker image I have pulled down. https://github.com/snipe/snipe-it/commit/4e28650ca9f3c6fd0cc85ac9a443db36847a9248

**Update: I just pulled down the latest docker image and inspected it, I can confirm that there is an issue with the image. It has the same problem**

**Comment by DBX12** [comment]
I can confirm this issue occurs with the snipe-it.io hosted version  `v7.1.14 - build 15942 (master)`. The pill / badge shows 14 models but the table below says "No matching records found", I took this screenshot on `https://redacted.snipe-it.io/categories/38`

![image](https://github.com/user-attachments/assets/cd475db8-3d04-4b07-9b88-50cbb8f7f660)

**Comment by snipe** [comment]
We just tagged v7.1.15, which should resolve this issue.
