### ISSUE TITLE
Consumables break if large number of items is checked-out

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15853]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If more that 8300 pieces of consumable are checked-out, page shows 'No matching records found' for that consumable.
If user has more than 10k pieces of consumables assigned - users part of SnipeIT is bricked - page shows 'No matching records found'.

### Reproduction steps

1. Create consumables with large quantity - 44444
2. Check-out 9000 consumables to the user
3. Visit page where list of users, that consumable was checked-out to, is shown.

### Expected behavior

That list shows entries, not the message 'No matching records found'. On a side note, that list would should show single line for check-out action with number of items checked-out, instead of entry for every single item.

### Screenshots

![image](https://github.com/user-attachments/assets/46846972-d3ca-47b5-a60b-b9376f9a0f28)

![image](https://github.com/user-attachments/assets/ae9de679-58a7-41d9-ba85-cc76a9ab0362)

### Snipe-IT Version

latest demo

### Operating System

-

### Web Server

-

### PHP Version

-

### Additional context

Currently, you can't remove assigned consumables and there's no other way to remove consumables from the user. I understand that 8000+ pieces of consumables may look like overkill, but our company goes through 500 packs of A4 sheets per week and if we would decide to track paper, we would brick the system unintentionally. Also, someone could make a mistake checking-out consumables by putting 9999 as quantity.

**Comment by swift2512** [comment]
You can also break stuff with accessories in the same way - by checking-out 10k+ items.
![image](https://github.com/user-attachments/assets/761efc34-8c33-42cb-8e36-c9b22e6ffb1c)
And it would be nice to have bulk check-in for accessories- nobody wants to check-in 20 pieces of same accessory individually. Even better way - only one line with total of items is shown and you can input a number of checked in items. (But this may be more difficult because IDs are involved.)
![image](https://github.com/user-attachments/assets/c226f04d-c25f-495d-8ec7-7c660b36dfbd)

**Comment by swift2512** [comment]
I broke demo website... You can't have more than 60k items assigned. All accessories are gone from the view. Sorry :)
![image](https://github.com/user-attachments/assets/3cf7d1f4-0fc4-40e4-83b8-e3b19d202750)

**Comment by snipe** [comment]
There is already a PR open for this. https://github.com/snipe/snipe-it/pull/15785 - just not sure it's how we want to handle it, nor the use case where someone would be checking out 10k consumables at a time.

**Comment by swift2512** [comment]
It's not 10k a a time. It's total quantity that breaks everything.
