### ISSUE TITLE
On the asset page in the history tab it sorts incorrectly by date

### ISSUE THREAD

**Issue by manukean** [grokability/snipe-it#15857]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

On the asset page in the history tab it sorts incorrectly by date

### Reproduction steps

1.Asset page
2.Click history
3.sort by date
...

### Expected behavior

sorting worked fine

### Screenshots

![Screenshot from 2024-11-20 16-58-36](https://github.com/user-attachments/assets/a045aeb1-7876-44d3-b3ba-53c13310187d)

### Snipe-IT Version

7.1.14

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1

### Operating System

Ubuntu

### Browser

Google Chrome

**Comment by manukean** [comment]
@uberbrady

**Comment by snipe** [comment]
We're aware of the issue.

**Comment by manukean** [comment]
great, thanks
