### ISSUE TITLE
click Send reminder get 500 server error

### ISSUE THREAD

**Issue by PonlorkBeang** [grokability/snipe-it#15866]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Good afternoon,

After upgrade Snipe-it from v7.0.13 to v7.0.14 I got the issue when i click on send reminder in Report->Unaccepted Assets as below picture 
![image](https://github.com/user-attachments/assets/fe11bca5-10ed-42b9-ac46-6f6634f9e35a)
![image](https://github.com/user-attachments/assets/17348e93-40da-4dd4-9767-db4e7ca3bd7c)
![image](https://github.com/user-attachments/assets/069c813e-ec40-405e-8275-0ce7efeada70)

### Reproduction steps

1.
2.
3.
...

### Expected behavior

.

### Snipe-IT Version

v7.0.14

### Operating System

Ubunt 24.04.1

### Web Server

Apache 2.4.58

### PHP Version

php 8.1.30

**Comment by snipe** [comment]
This has already been fixed on master.
