### ISSUE TITLE
API Paramenter Checkout_QTY won´t change remaining for Consumables

### ISSUE THREAD

**Issue by ganslm** [grokability/snipe-it#15867]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I add the checkout_qty to the Body Params for the API POST for Consumable checkout it only generates the entry in the history (see Screenshot).

But it won´t affect the remaining field for the Consumable and the Consumable isn´t assigned to the selected User.

When I remove the checkout_qty from the POST works as usual.

See #15717 for reference. 

### Reproduction steps

1.Write an API POST to checkout Consumables including checkout_qty
2.Try it

### Expected behavior

Checkout Consumable with the correct quantity.

### Screenshots

![grafik](https://github.com/user-attachments/assets/6c284501-7a29-4108-9623-18cc511e0e9e)

### Snipe-IT Version

7.1.14

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2

**Comment by snipe** [comment]
Can you show me the actual payload (minus your brearer token) that you're sending?

**Comment by ganslm** [comment]
Sorry it seems like I had an Issue in my previous test. 

Now it works like a charm.

Thank you
