### ISSUE TITLE
When sending a mail in the from line there is this service@snipe-it.io

### ISSUE THREAD

**Issue by manukean** [grokability/snipe-it#15872]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In the example file snipeit/app/Mail/CheckoutAccessoryMail.php there is such a part 
public function envelope(): Envelope
    {
        $from = new Address(env('MAIL_FROM_ADDR','service@snipe-it.io'));

        return new Envelope(
            from: $from,
            subject: (trans('mail.Accessory_Checkout_Notification')),
        );
    }

### Reproduction steps

1.service@snipe-it.io
2.
3.
...

### Expected behavior

notifications worked as we set

### Snipe-IT Version

7.1.14

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1

### Additional context

@

**Comment by filipc** [comment]
It's just a defaulting an env variable if it is not set. When you'll set environment variable `MAIL_FROM_ADDR` the default value won't be used.

According to the [Laravel docs](https://laravel.com/docs/11.x/configuration#retrieving-environment-configuration): 
> The second value passed to the env function is the "default value". This value will be returned if no environment variable exists for the given key.

However it's worth to consider a change of default value to some more generic, for instance at the domain listed in [RFC6761](https://www.rfc-editor.org/rfc/rfc6761.html) like `example.com`, `example.net` or `example.org`

**Comment by RedShift1** [comment]
Just came across this problem myself after upgrading to 7.1.14, running on docker. Did this change in some release? In the docker docs it says `MAIL_ENV_FROM_ADDR` (https://snipe-it.readme.io/docs/docker) but you're saying `MAIL_FROM_ADDR`?

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/docker">Docker</a></strong></div><div>Note very loudly that additional Docker options should be set in the .env file, and they can require a full container rebuild!</div></blockquote>

**Comment by filipc** [comment]
It seems it is rewrited in docker.env file from host env `MAIL_ENV_FROM_ADDR` to `MAIL_FROM_ADDR` 
https://github.com/snipe/snipe-it/blob/ad2b85393bc07d711434d6348e083d7317580e72/docker/docker.env#L34
The app itself is expecting to have `MAIL_FROM_ADDR` to be set, as in the code sample.

You are about to set the `MAIL_ENV_FROM_ADDR` variable on your host machine. When you pass the `docker.env` file to Docker, the application running inside the Docker container will receive this variable as `MAIL_FROM_ADDR`.

**Comment by RedShift1** [comment]
In Docker environment:

* Before 7.1.14, `MAIL_ENV_FROM_ADDR` is respected.
* With 7.1.14:
  * Regardless of `MAIL_ENV_FROM_ADDR`, from becomes `service@snipe-it.io` 
  * If I set `MAIL_FROM_ADDR`, no email at all gets sent...

**Comment by manukean** [comment]
the problem has been resolved in the new version, 7.1.15
