### ISSUE TITLE
livewire.esm.js.map abort on update

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#15878]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

error: The following untracked working tree files would be overwritten by merge:
        public/vendor/livewire/livewire.esm.js.map
Please move or remove them before you merge.
Aborting

When doing Php update

### Reproduction steps

1.php upgrade.php
2.producing error (described above)
3.
...

### Expected behavior

no error

### Snipe-IT Version

 v7.0.13 build 15666 (g03b01689b) 

### Operating System

alma

### Web Server

apache

### PHP Version

 8.1.30

**Comment by uberbrady** [comment]
If you can remove that file, then re-run the update, it should work. The update will pull the file back down anyways, and even then, it's not needed generally - just for debugging.

**Comment by jayavman** [comment]
thanks!
