### ISSUE TITLE
[Feature Request]: License overview

### ISSUE THREAD

**Issue by MrKrabbyPatty** [grokability/snipe-it#15882]
### Is your feature request related to a problem? Please describe.

I think there's no option at the moment how I could organize the licenses like described below.

### Describe the solution you'd like

we would like to group licenses together (for example: all microsoft licenses) in one place.

**Comment by snipe** [comment]
You can use categories for that, like Category type: License, Name: Microsoft Licenses. Or just use the filters within the manufacturer/supplier lists.
