### ISSUE TITLE
[Feature Request]: Cumulative notes field

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15888]
### Is your feature request related to a problem? Please describe.

Notes written when item is checked-out are only visible in History field. You can't see them in any of Assets lists. If it's an important note, you have to manually edit that item and fill in Notes field.

### Describe the solution you'd like

Notes field acts like a log file. Newest note you made on item check-in/check-out is put in the first line of Notes field and has date&time attached to it. If log is too big, admin just deletes lines he doesn't want.

Notes field could look like this:
2024-11-26 13:19	 Test for viruses before checking out
2024-10-15 09:11	 OS reinstalled
2024-10-04 09:22	 Computer will be used at home

When you click on item, you see everything in Notes field
![image](https://github.com/user-attachments/assets/5cfe0bd5-e3e9-4909-b3f6-791b8514e2ea)

**Comment by snipe** [comment]
>  If log is too big, admin just deletes lines he doesn't want.

That's not possible, since the notes currently pull from the action logs table, and those entries cannot be(and should not) be deleted. If it's just notes you're looking for, PR #14987 will likely solve your ask.
