### ISSUE TITLE
[Feature Request]: Need to enable Custom Fields for Licenses

### ISSUE THREAD

**Issue by 00717747** [grokability/snipe-it#15881]
### Is your feature request related to a problem? Please describe.

Need to enable Custom Fields for Licenses

### Describe the solution you'd like

Need to enable Custom Fields for Licenses

### Describe alternatives you've considered

Need to enable Custom Fields for Licenses

### Additional context

Need to enable Custom Fields for Licenses

**Comment by snipe** [comment]
Duplicate of https://github.com/snipe/snipe-it/issues/4261
