### ISSUE TITLE
[Feature Request]: Add "Description" field to the "View Assigned Assets" page as a toggle

### ISSUE THREAD

**Issue by yetanothersys-admin** [grokability/snipe-it#15897]
### Is your feature request related to a problem? Please describe.

Not really, we'd just like a toggle for the "Description" field as we have some users who could use the extra infos we put in there sometimes

### Describe the solution you'd like

Our yearly review of our inventory includes letting the users check their material themselves - but only the "Assigned Assets" view (like this:)
![image](https://github.com/user-attachments/assets/4ee4e291-2afc-42cf-9606-1d2ee9a97856)

Prior to this years review we added our access mediums to the inventory as well. We used the description field a lot for those assets... -> e.g. "Key for XYZ"

I saw that the description was basically the only thing missing in the view... and it's not a part of the toggles (yet? 😄).
![image](https://github.com/user-attachments/assets/ab3f2446-d792-4657-91d3-656b3a75b25c)

### Describe alternatives you've considered

Nothing really...

### Additional context

I saw that you added the asset model to that view just recently - #15820

**Comment by snipe** [comment]
We don't have a description field. You could add that as a custom field and then set it to be visible in Assigned Users via the custom field settings.

<img width="401" alt="Custom_Fields____Snipe-IT_Demo-3" src="https://github.com/user-attachments/assets/9d37decb-072c-4e89-b39f-562a013b9965">

**Comment by yetanothersys-admin** [comment]
Hey! Sorry, I was out of office so I couldn't respond / correct myself... I meant the "Notes" as "Description"...
![image](https://github.com/user-attachments/assets/6f4a5e71-3603-4336-bc27-41a6e48db57d)
