### ISSUE TITLE
[Feature Request]: Custom required fields

### ISSUE THREAD

**Issue by i-am-checking** [grokability/snipe-it#15899]
### Is your feature request related to a problem? Please describe.

Hi, can you add custom requirements when creating an asset? For example, requiring an asset to have a name, location etc like there is for status, model and asset tag.

### Describe the solution you'd like

In trying to ensure all information is filled in and our assets are kept consistent and accurate, I've been trying to get my team to remember to include all the information we as a team need, but they are missing info. Being able to toggle what information is required would be massively beneficial for us to be able to make sure that all info we need is marked as required, so nothing is missed. 

Ideally it would look like the screenshot
![Ideally](https://github.com/user-attachments/assets/d12e7478-e7df-4845-b203-25098787452e)

**Comment by snipe** [comment]
It's been asked before - I don't see it on the short-term roadmap, as it adds an incredible amount of complexity.
