### ISSUE TITLE
[Feature Request]: Add Asset category in User-inventory emails

### ISSUE THREAD

**Issue by Speedyduck300000** [grokability/snipe-it#15896]
### Is your feature request related to a problem? Please describe.

Currently, Emails that are sent to users via the "Email List of all assigned" button do not include the category of the assets in question. This makes it hard to figure out for the user which type of asset he actually owns, especially if the asset name does not include this information.

### Describe the solution you'd like

I propose to change the user-inventory.blade.php to include the category of each asset. I have already made changes to my own system according to my wishes and haven't encountered any issues, even on the newest versions.

### Describe alternatives you've considered

Flexibility with the category field, allowing it to be enabled and disabled via a setting would allow administrators to choose whether or not to include the field, which would be preferable. I have however not tested this approach yet.

### Additional context

Current Email that is sent to user when the button "Email list of all assigned" is used. ![grafik](https://github.com/user-attachments/assets/15883fcb-30a8-4f11-9d80-4f53c9bf3526)
Email that is sent after configuration to add the category.
![grafik](https://github.com/user-attachments/assets/3f39be09-8b3d-4c2a-80d6-8f9b3766d48d)

Server is currently running on v7.1.15.

**Comment by akemidx** [comment]
PR submitted here: [#15920](https://github.com/snipe/snipe-it/pull/15920)
