### ISSUE TITLE
Permissions table needs translation

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15900]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Permission table for users and groups is fixed to English language. May be due to **resources/views/partials/forms/edit/permissions-base.blade.php** file.

### Reproduction steps

1. Change language from English to any other.
2. Edit user or user group.

### Expected behavior

Text is in the user's language.

### Screenshots

![image](https://github.com/user-attachments/assets/be2a3dc0-289d-4c23-8f07-5dcb3036d903)

### Snipe-IT Version

7.1.14

### Operating System

Ubuntu

### Web Server

LAMP

### PHP Version

8

**Comment by snipe** [comment]
Unfortunately, the way those currently work, we cannot translate those at this time. (The translation engine isn't loaded yet when we pull in that permissions config file.) It's on our radar though and we're trying to figure out how best to handle it.
