### ISSUE TITLE
Yellow Mark on Required Custom Field not showing on new version

### ISSUE THREAD

**Issue by sinichi19** [grokability/snipe-it#15901]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

On the latest version of Snipe-it the yellow mark on required field when you used the custom field is gone 
Before all required field custom field have a yellow mark at the end of the box to show that need to fill before saving the asset.
![Screenshot from 2024-11-29 10-36-58](https://github.com/user-attachments/assets/ff65c5bf-e982-4f93-8b1e-f99692cabf04)

### Reproduction steps

1. Create new Fieldset
2. Add custom field on Fieldset and make Required
3. Add the Fieldset to Model
4. Create new Asset and Select the model
5. The required Custome Fieldset not showing the Yellow Mark need to be fill 
..

### Expected behavior

All required custom field have yellow mark to show need to fill before saving the assets 

### Screenshots

![Screenshot from 2024-11-29 10-36-58](https://github.com/user-attachments/assets/404976ef-bea6-4fcc-9cec-945b52b84757)

### Snipe-IT Version

latest

### Operating System

Ubuntu 22

### Web Server

Apeche 2

### PHP Version

8.1.31

### Operating System

WIndows

### Browser

Google Chrome

### Version

Latest

**Comment by snipe** [comment]
This is on master now. Looks like the regression was created in September.
