### ISSUE TITLE
Event log from PHP not save in syslog or laravel.log ?

### ISSUE THREAD

**Issue by DydyDelFuego** [grokability/snipe-it#15903]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

I'm currently trying to connect the SnipeIT solution to a SIEM solution (Microsoft Sentinel).
Unfortunately, I can't figure out how to activate event logging: Modification of an object, Creation of a new object ...

I've had a look at the documentation, but I can't seem to find an option/button to activate such logging.

Is this possible?

Regards,

Dylan Lopes

### Reproduction steps

N/A

### Expected behavior

Have all PHP events in the Syslog file or other facility.

### Screenshots

![image](https://github.com/user-attachments/assets/7a307d08-f394-4737-aff6-26a0efdf15ff)
Object was udpated à 2pm 42min.
But nothing is present in laravel log :
![Laravel-log](https://github.com/user-attachments/assets/7930cdfe-8cdc-4855-98d0-5a5c362f37f7)
And nothing in Syslog
![Syslog-log](https://github.com/user-attachments/assets/a7cf349e-b781-4394-9b5e-9f1c7bf3ff67)

### Snipe-IT Version

7.1.14

### Operating System

Ubuntu 20.04.6 LTS

### Web Server

Apache

### PHP Version

7.4

### Operating System

s

### Error messages

```shell
N/A
```

### Additional context

N/A

**Comment by snipe** [comment]
That data is stored in the `actions_logs` database table.
