### ISSUE TITLE
IMPORT ASSETT ERROR

### ISSUE THREAD

**Issue by valeriopirola** [grokability/snipe-it#15916]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I had no problems importing with version v7.0.13, then I switched to v7.1.15 and during the import this message appears and the data is not imported
![2024-12-03 12_49_06-Import __ Asset Tracing e altre 5 pagine - Lavoro - Microsoft​ Edge](https://github.com/user-attachments/assets/5364609e-610e-4407-9bcb-551b7d670515)

### Reproduction steps

1.IMPORT
2.SELECT FILE PROCESS OK
3.PROCESS IMPORT SUCCESSFUL
4. ERROR: Your file import is complete, but we did receive an error. This is usually caused by third-party API throttling from a notification webhook (such as Slack) and would not have interfered with the import itself, but you should confirm this.

...

### Expected behavior

ERROR-FREE FILE IMPORT

### Screenshots

![image](https://github.com/user-attachments/assets/cb711d59-36c1-429e-a567-bbb9111784b0)

### Snipe-IT Version

v7.1.15 build 16052 (g25bfd3e84)

### Operating System

windows

### Web Server

IIS

### PHP Version

8.1.27

**Comment by valeriopirola** [comment]
[laravel.log](https://github.com/user-attachments/files/17992465/laravel.log)

**Comment by work324** [comment]
How did you resolve this issue?
