### ISSUE TITLE
Error when using command line "php artisan snipeit:import" with v7.1.15

### ISSUE THREAD

**Issue by HIS-David** [grokability/snipe-it#15928]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to import a list of users who require a license to be checked out to them from a csv file we receive an "Error:   Call to undefined method App\Importer\LicenseImporter::setUserId()" error.  

I have recently upgrade from v6.2.3 and the code was working fine using that version.

We run the following code to check all the licenses in for a specific license id: 
_php artisan snipeit:checkin-from-all --license_id=1_

We have a csv with the following columns
"Username","Item name"
"TestUser","Adobe Acrobat Pro 20"

We run the following code to check out the license to the list of users.
_php artisan snipeit:import HIS-AdobeAcrobatPro20-Users --item-type License --update --verbose_

When running on v6.2.3 used to check out the licenses to each of the users but now with v7.1.15 we receive the following error.
  _Error

  Call to undefined method App\Importer\LicenseImporter::setUserId()

  at app\Console\Commands\ObjectImportCommand.php:62
     58▕         $class = title_case($this->option('item-type'));
     59▕         $classString = "App\\Importer\\{$class}Importer";
     60▕         $importer = new $classString($filename);
     61▕         $importer->setCallbacks([$this, 'log'], [$this, 'progress'], [$this, 'errorCallback'])
  ➜  62▕                  ->setUserId($this->option('user_id'))
     63▕                  ->setUpdating($this->option('update'))
     64▕                  ->setShouldNotify($this->option('send-welcome'))
     65▕                  ->setUsernameFormat($this->option('username_format'));
     66▕

  1   vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      App\Console\Commands\ObjectImportCommand::handle()

  2   vendor\laravel\framework\src\Illuminate\Container\Util.php:41
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

  3   vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:93
      Illuminate\Container\Util::unwrapIfClosure()

  4   vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
      Illuminate\Container\BoundMethod::callBoundMethod()

  5   vendor\laravel\framework\src\Illuminate\Container\Container.php:662
      Illuminate\Container\BoundMethod::call()

  6   vendor\laravel\framework\src\Illuminate\Console\Command.php:211
      Illuminate\Container\Container::call()

  7   vendor\symfony\console\Command\Command.php:326
      Illuminate\Console\Command::execute()

  8   vendor\laravel\framework\src\Illuminate\Console\Command.php:181
      Symfony\Component\Console\Command\Command::run()

  9   vendor\symfony\console\Application.php:1096
      Illuminate\Console\Command::run()

  10  vendor\symfony\console\Application.php:324
      Symfony\Component\Console\Application::doRunCommand()

  11  vendor\symfony\console\Application.php:175
      Symfony\Component\Console\Application::doRun()

  12  vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:201
      Symfony\Component\Console\Application::run()

  13  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()_

### Reproduction steps

1.Run from admin command line in the snipeit folder: php artisan snipeit:checkin-from-all --license_id=1 to check in all licenses with id = 1
2. Run from admin command line in the snipeit folder: php artisan snipeit:import HIS-AdobeAcrobatPro20-Users --item-type License --update --verbose to check out licenses to all users in a csv file.
...

### Expected behavior

When running the code in line 2 we would expect the licenses to be assigned to all the users in the csv file.  All users in the csv are within the snipeit user table.

### Screenshots

The licenses are checked in from the users
![image](https://github.com/user-attachments/assets/6c399759-88b5-4c17-9bb8-5dea9b813407)

Checking out licenses to users.  
Error
![image](https://github.com/user-attachments/assets/7b32ccd7-125f-4914-8244-3c8bee12fbff)
![image](https://github.com/user-attachments/assets/8efae296-5e3b-46c4-8a3b-51d4e6a43519)

### Snipe-IT Version

7.1.15

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.28

### Operating System

Windows

### Browser

Edge

### Version

131.0.2903.70

### Device

n/a

### Operating System

n/a

### Browser

n/a

### Version

n/a

### Error messages

```shell
_Error

Call to undefined method App\Importer\LicenseImporter::setUserId()

at app\Console\Commands\ObjectImportCommand.php:62
58▕ $class = title_case($this->option('item-type'));
59▕ $classString = "App\Importer\{$class}Importer";
60▕ $importer = new $classString($filename);
61▕ $importer->setCallbacks([$this, 'log'], [$this, 'progress'], [$this, 'errorCallback'])
➜ 62▕ ->setUserId($this->option('user_id'))
63▕ ->setUpdating($this->option('update'))
64▕ ->setShouldNotify($this->option('send-welcome'))
65▕ ->setUsernameFormat($this->option('username_format'));
66▕

1 vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
App\Console\Commands\ObjectImportCommand::handle()

2 vendor\laravel\framework\src\Illuminate\Container\Util.php:41
Illuminate\Container\BoundMethod::Illuminate\Container{closure}()

3 vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:93
Illuminate\Container\Util::unwrapIfClosure()

4 vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
Illuminate\Container\BoundMethod::callBoundMethod()

5 vendor\laravel\framework\src\Illuminate\Container\Container.php:662
Illuminate\Container\BoundMethod::call()

6 vendor\laravel\framework\src\Illuminate\Console\Command.php:211
Illuminate\Container\Container::call()

7 vendor\symfony\console\Command\Command.php:326
Illuminate\Console\Command::execute()

8 vendor\laravel\framework\src\Illuminate\Console\Command.php:181
Symfony\Component\Console\Command\Command::run()

9 vendor\symfony\console\Application.php:1096
Illuminate\Console\Command::run()

10 vendor\symfony\console\Application.php:324
Symfony\Component\Console\Application::doRunCommand()

11 vendor\symfony\console\Application.php:175
Symfony\Component\Console\Application::doRun()

12 vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:201
Symfony\Component\Console\Application::run()

13 artisan:35
Illuminate\Foundation\Console\Kernel::handle()_
```

**Comment by work324** [comment]
I also am experiencing this issue when trying to import assets after upgrading.

**Comment by HIS-David** [comment]
> I also am experiencing this issue when trying to import assets after upgrading.

Thanks for confirming it's not just me that's having the issue.

**Comment by HIS-David** [comment]
The issue is also happening when trying to import assets via php  "php artisan snipeit:import Workstations.csv --item-type Asset --update"
![image](https://github.com/user-attachments/assets/19236fe8-8be1-43bb-974f-66356270e5ef)

We use this type of importing as we pickup device changes centrally and import via the above php code. It has essentially broken our ability to pull information from other systems like Active Directory and SCCM.

Just to confirm that I have updated to php v8.3.14 and the issue is still present.

**Comment by snipe** [comment]
Can you pull latest from master and let me know if that fixes your issue?

**Comment by work324** [comment]
Uploading through Command Line seems to be working now, but GUI upload is still erroring out.

**Comment by snipe** [comment]
With the same error, or...? GUI is working for me

**Comment by work324** [comment]
This is the error I'm getting from GUI, "Your file import is complete, but we did receive an error. This is usually caused by third-party API throttling from a notification webhook (such as Slack) and would not have interfered with the import itself, but you should confirm this."

**Comment by HIS-David** [comment]
The issue has now been resolved. Thank you for your quick response.
