### ISSUE TITLE
Index of /snipe-it

### ISSUE THREAD

**Issue by sahya24** [grokability/snipe-it#15984]
While trying to access the snipe it page i get this
![Screenshot 2024-12-18 113045](https://github.com/user-attachments/assets/8f110af9-74b6-4d94-801e-7624e56fbdfe)
 I'm new to  this please help.

**Comment by swift2512** [comment]
Has to be server configuration. Even with the latest pull my Snipe-IT works perfectly.

**Comment by snipe** [comment]
You'll need to remove built-in aliases: https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases">XAMPP</a></strong></div><div>❗️ Note:: In general, we do not recommend using XAMPP for Snipe-IT, as there is a built-in alias for /licenses that you'll have to override, which can be a bit of a pain. We recommend WAMP or IIS instead if you're running on Windows, but we provide these instructions in case WAMP is not an option. D...</div></blockquote>
