### ISSUE TITLE
Manual LDAP sync with Google Workspace not working

### ISSUE THREAD

**Issue by SJL-369** [grokability/snipe-it#15999]
We're using hosted Snipe-IT, and have LDAP setup with Google Workspace which has been working successfully for a while.

We're now finding new users are not being synced. Testing the LDAP settings is successful and shows the first 10 results. However, trying to do a manual sync (url/users/ldap) WITHOUT selecting a location throws the following error:

```
Error: Could not search the LDAP server. Please check your LDAP server configuration in the LDAP config file. <br>Error from LDAP Server: Location: Remote - Canada (ID: 13) cannot connect to "remote-canada" - ldap_search(): Search: Invalid DN syntax
```

We've setup `Remote - Canada` as a location, however we're not sure why LDAP search is using that in its query when we haven't selected a location. When we do select a location, the same error is thrown regardless of location selected, i.e. it's always `Remote - Canada`.

Any thoughts on what else we can try?

**Comment by uberbrady** [comment]
You have an "LDAP OU" set for that location. If it incorrectly requires you to specify an OU (you should otherwise leave it blank), run an update, then that hsould be fixed.

**Comment by SJL-369** [comment]
Whether I select a location (any location) or leave it blank, it still reports an error with the same error message with the `Remote - Canada` location. So I'm not sure why it's doing that.

I'm not sure what you mean by running an update. I'm on the hosted instance, not self-hosted.

EDIT: Okay, I figured out what you meant. All the other locations don't have an LDAP OU set, but the `Remote - Canada` location did. I'm guessing the manual sync will go through all locations, hence the error message once it hits Canada? Either way, the resolution was to remove the LDAP OU value from the `Remote - Canada` location.

Thanks for your help.
