### ISSUE TITLE
Bulk Audit Not Changing Asset Location

### ISSUE THREAD

**Issue by memtech3** [grokability/snipe-it#7619]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

When bulk auditing an item and selecting a different location than the current location, location of asset is not updated
**To Reproduce**
1. Go to 'bulk audit'
2. Enter 'asset tag'
3. Change location of 'asset tag'
3. Search for 'asset tag' in search box at top of screen
4. See location not changed

**Expected behavior**
Asset location to have changed or be prompted to change asset location
**Screenshots**

**Server (please complete the following information):**
Snipe-IT develop branch preview

**Desktop (please complete the following information):**
Chrome windows 10

**Comment by zackern** [comment]
Has anyone looked at this yet?

**Comment by collectingapples** [comment]
It would be great if the bulk Audit functionality could be used to to audit the locations.  As it is is right now, it seems like it has no real functionality.  I can change the location in the audit screen, but that information does not actually get recorded onto the object being audited.

As it stands, there seems to be no way at all to update the location on many items at once without finding each item individually, opening each item individually, changing the location individually before saving it individually.   No part of the process is able to be automated or anything.  Why?

**Comment by zackern** [comment]
Yes this is still highly relevant!
Please consider to look at this!

**Comment by adamoliver84** [comment]
I too am experiencing this problem.

**Comment by adamoliver84** [comment]
Upgraded my installation to v4.9.4 build 4437 (g799a93c46) and still problem occurs.

**Comment by adamoliver84** [comment]
new case: Bulk Audit Not Changing Asset Location #8286

**Comment by 119155012** [comment]
I had this issue before, here's the solution. [https://github.com/snipe/snipe-it/commit/ff879e2018f1fac406b813d423ba7d617817b2c7](https://github.com/snipe/snipe-it/commit/ff879e2018f1fac406b813d423ba7d617817b2c7)
