### ISSUE TITLE
PHP Artisan Key:Generate (Aborted Error)

### ISSUE THREAD

**Issue by KCleveland313** [grokability/snipe-it#7625]
#### Please confirm you have done the following before posting your bug report:

- [YES] I have enabled debug mode 
- [YES ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Gets "Aborted." error when running the command php artisan key:generate

**To Reproduce**
1. Go to inetpub\wwwroot\snipe-it 
2. Click on Run CMD as Admin
3. Run PHP ARTISAN KEY:GENERATE COMMAND

**Expected behavior**
For the key to generate. Already made .env file and made sure it didn't have .txt ext and edited it. 

**Screenshots**
![image](https://user-images.githubusercontent.com/58272304/69756777-4d834000-1129-11ea-9393-36b8b0da9963.png)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] SERVER 2012 R2

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? FRESH
- What OS and web server you're running Snipe-IT on WINDOWS 10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by nishfaan** [comment]
Hellow I am also getting this error. Please help

**Comment by nishfaan** [comment]
So for this issue what I did was use the command `php artisan key:generate --show`
This will show u the key instead of adding it to the env file. Copy and paste the key from there and it worked

**Comment by sboo** [comment]
This is related to https://bugs.php.net/bug.php?id=78883

Update to PHP 7.4.1 and it will work correctly again


<blockquote><img src="https://bugs.php.net/images/favicon.ico" width="48" align="right"><div><strong><a href="https://bugs.php.net/bug.php?id=78883">PHP :: Bug #78883 :: fgets(STDIN) fails on Windows</a></strong></div></blockquote>
