### ISSUE TITLE
API endpoint for getting the current User ID

### ISSUE THREAD

**Issue by 0xpr03** [grokability/snipe-it#7626]
**Server (please complete the following information):**
 - Snipe-IT Version 4.7.8
 - OS: Debian
 - Web Server: Apache
 - PHP Version 7.3

**Is your feature request related to a problem? Please describe.**
I'd like to request a list of hardware a user currently has, for which I need the user ID.
Now I'd like a user to just enter his API key and automagically get their user ID. With this I can then use the existing REST API to retrieve their hardware.

**Describe the solution you'd like**
An api like /user that returns the current users Data (containing the ID and maybe other stuff).

**Describe alternatives you've considered**
I could add a search field and the user has to search for themself at the beginning.

**Additional context**
This is for an android App, which allows mass editing of assets etc. Making mobile usage easier.

**Comment by 0xpr03** [comment]
It's still relevant if I don't want to rely on custom patches.

**Comment by 0xpr03** [comment]
Yes

**Comment by 0xpr03** [comment]
Yes

**Comment by 0xpr03** [comment]
yes

**Comment by cofl** [comment]
I haven't verified this on 4.7.8, but I have on 4.9.5 and very similar code exists in 4.7.8. The endpoint `/api/v1/users/me` returns an user object with an `id` property corresponding to the user id.

See:
- https://github.com/snipe/snipe-it/blob/v4.7.8/routes/api.php#L709
- https://github.com/snipe/snipe-it/blob/v4.7.8/app/Http/Controllers/Api/UsersController.php#L394

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by 0xpr03** [comment]
@cofl many thanks for this, then this should really be documented on https://snipe-it.readme.io/reference#usersid or am I missing something ?!

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference#usersid">Overview</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>

**Comment by 0xpr03** [comment]
Kinda, it's still undocumented. Though I'm not sure if v5 will resolve this issue anyway?

**Comment by snipe** [comment]
This was already added to the docs. https://snipe-it.readme.io/reference#usersme

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference#usersme">Overview</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>

**Comment by 0xpr03** [comment]
Thanks!
