### ISSUE TITLE
Feature request: Users access management

### ISSUE THREAD

**Issue by AimarL** [grokability/snipe-it#7633]
Our company is using many third-party services and tools. So it would be nice to have:

1. a list of all services, that company is using (User view / Admin view)
2. name of the manager/admin of the service (User view / Admin view)
3. who has access to these services (Admin view)
4. ability to manage service users list and seats by service managers
Snipe-it is a great tool and we love it. This feature will add more "Employee lifecycle management" capabilities to snipe-it, as user access rights will become more clear and it will help to improve awareness of third-party services that the company is using.

**Comment by cliff-LINKS** [comment]
+1
I'm looking for an effective way of documenting users in services like Office 365 and Google Docs, but local user directories as AD and mail servers as well.
