### ISSUE TITLE
Requested asset doesn't cancel automatically when they have had the asset checked out then back in.

### ISSUE THREAD

**Issue by Callum-Mason** [grokability/snipe-it#7635]
#### Expected Behavior (or desired behavior if a feature request)

When a user requests the asses via the "Requestable Assets" tab and the admin check that asset out to user, then under the "Requestable Assets" tab that user should have the option to request to check in the asset or even unmask the requested item when the item has been checked in.
-----

#### Actual Behavior

When a user requests the asses via the "Requestable Assets" tab and the admin check that asset out to user, then under the "Requestable Assets" tab you have to cancel that asses to request it again.

-----

#### Please confirm you have done the following before posting your bug report:

- [Y ] I have enabled debug mode 
- [Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - upgraded from a fresh
- Version of Snipe-IT you're running - v4.7.8 build 4170 (g4fe689dc5)
- Version of PHP you're running - 7.2.21
- Version of MySQL/MariaDB you're running - 5.5.60-MariaDB
- What OS and web server you're running Snipe-IT on - CentOS 7, apache2 (httpd)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error -N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - http://domainname/account/requestable-assets
- If a stacktrace is provided in the error, include that too. - N/A
- Any errors that appear in your browser's error console. - None
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - Issue does happen there
- Include any additional information you can find in `storage/logs` and your webserver's logs. - N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. - Had no issues
- Indicate whether or not you've manually edited any data directly in the database - no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by TTeTbP** [comment]
This is still an issue and it's certainly something which is worth looking at

**Comment by kelsen** [comment]
I would like to reopen this request, this is still a probem on v6.05.
User request an asset, admin check-out and check-in.
Under requestable assets user need to cancel that asset request manually.
Under requested assets that assets is in check-out state once again if not canceled by user.

**Comment by snipe** [comment]
We are working on a different workflow for asset requests.

**Comment by kelsen** [comment]
May I ask when this will be released?
We would like to let our users request by themself.

**Comment by snipe** [comment]
Users can already request their own assets. The new workflow is still in planning phase, so it won't be ready for some time.
