### ISSUE TITLE
Participation Request: Software Bill of Materials (SBOM) Formats & Tooling Working Group

### ISSUE THREAD

**Issue by ussjoin** [grokability/snipe-it#7642]
**Is your feature request related to a problem? Please describe.**

The NTIA Software Bill of Materials project hopes to create an "ingredients list" for software, allowing defenders to know not just what software they've installed, but what it depends on, to enable rapid patching of insecure components, better software supply chain analysis (especially important when there may be compromised libraries), and increased shareholder value. The outputs of their initial work (since 2018) is available at <https://www.ntia.gov/SBOM>.

The new phase of the work is now beginning, and the Formats & Tooling Working Group would like to include participation from asset management tooling developers; while proprietary-code developers are already involved, I suggested that as the largest and most excellent open source asset management tool, Snipe-IT might like to participate as well.

Why would asset management want to have an SBOM? Well, the [Comply to Connect (C2C) idea](https://www.govloop.com/what-is-comply-to-connect/) provides one model, wherein a device would transmit the SBOM for everything installed on it as part of its request to the network to provide services (e.g., DHCP and routing). The [OASIS OpenC2 technical committee](https://www.oasis-open.org/committees/openc2/), which is making open standards to enable, among other things, C2C, has people participating in the SBOM process.

**Describe the solution you'd like**
We'd like you to join the Standards & Formats Working Group's next few calls and, hopefully, the group itself. The mailing list for the group is available at https://lists.linuxfoundation.org/mailman/listinfo/ntia-sbom-formats , and our next call is on December 20; if you join the mailing list you'll get an invite.

**Describe alternatives you've considered**
While we've considered not having open source asset management tooling participating, that would be a shame, given the wide participation from other parts of the OSS community (e.g., the Linux Foundation).

**Additional context**
You're welcome to reach out to me (my username @ github dot com will work nicely) if you have any questions.

Thanks very much!

**Comment by snipe** [comment]
I signed up for the  mailing list - thanks for thinking of us, friend! <3

<img width="829" alt="Screen Shot 2019-12-06 at 10 19 07 AM" src="https://user-images.githubusercontent.com/197404/70345908-eabd3300-1811-11ea-9ae8-6d8137829754.png">
