### ISSUE TITLE
Issue upgrading from 4.7.8 to 4.80

### ISSUE THREAD

**Issue by samotelf** [grokability/snipe-it#7650]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When updating the app using php upgrade upgrade.php I get the following error:

Updating nesbot/carbon (1.39.0 => 1.39.1):     The package has modified files:
    M bin/upgrade-carbon
    Discard changes [y,n,v,d,s,?]?

How should I proceed?
Thank you.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version - 4.7.8
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.3.6

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by UserGoodtm** [comment]
I have the same error

**Comment by UserGoodtm** [comment]
I chose the Y option . The update was successful. It seems that there are no errors when working with snipe-it
