### ISSUE TITLE
Check in/Checkout email notification to "ADMIN"

### ISSUE THREAD

**Issue by Mafeercm** [grokability/snipe-it#7654]
Hi Team,
My email configuration fine, test email function is working fine and users are able to receive when any assets are check out to them, but i need my admin to receive the notifications for every check in and check out. this is not working for me, Kindly advise.

I have enabled email alert and Send email to user on check in/checkout for all categories.

SnipeIT - Version v4.7.8

**Comment by hashfunktion** [comment]
Hi Mafeercm,

I think under the Alert Settings you can add an "CC Email" that receives a copy of all notifications.
That works great for me.

Best regards

**Comment by alkalinelito** [comment]
Hi, does this work checking to to Location? ,  I have many locations with no manager assigned, but would like to receive notification on CC email , of every check out/in
