### ISSUE TITLE
LDAP SYNC does not work with some LDAP filters

### ISSUE THREAD

**Issue by Zelphy** [grokability/snipe-it#7655]
- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

LDAP **SYNC** does not work with my LDAP filter (and throws an invalid message) but **CONNEXION** works.

**To Reproduce**

Set this filter in LDAP configuration page:
`&(memberOf=cn=GROUP1,cn=groups,cn=accounts,dc=REDACTED,dc=com)(memberOf=cn=GROUP2,cn=groups,cn=accounts,dc=REDACTED,dc=com)(memberOf=cn=GROUP3,cn=groups,cn=accounts,dc=REDACTED,dc=com)`

Test LDAP Sync -> OK

![Screenshot from 2019-12-10 14-27-54](https://user-images.githubusercontent.com/4152786/70533504-85db4300-1b59-11ea-8caf-fe2bcc451bbc.png)

Test LDAP Login -> OK

![Screenshot from 2019-12-10 14-30-32](https://user-images.githubusercontent.com/4152786/70533564-ab684c80-1b59-11ea-8333-179d1273f748.png)

At this point, I can connect to the server and everything seems to work:

![Screenshot from 2019-12-10 14-32-01](https://user-images.githubusercontent.com/4152786/70533805-1ade3c00-1b5a-11ea-9dea-cb0be9988ac7.png)
![Screenshot from 2019-12-10 14-32-15](https://user-images.githubusercontent.com/4152786/70533804-1a45a580-1b5a-11ea-8c14-78b3e38ff8d2.png)

The user is present in the "Current Users" page:

![Screenshot from 2019-12-10 14-33-28](https://user-images.githubusercontent.com/4152786/70533886-46f9bd00-1b5a-11ea-90a5-2498cec5de18.png)

But when I try to do an LDAP User Sync, here is what I get:

![Screenshot from 2019-12-10 14-36-20](https://user-images.githubusercontent.com/4152786/70534035-82948700-1b5a-11ea-817f-9201d91e8a7f.png)
![Screenshot from 2019-12-10 14-36-30](https://user-images.githubusercontent.com/4152786/70534042-86c0a480-1b5a-11ea-9145-f48a735df0a8.png)

So users are not synchronised and the message say "Success: LDAP Import successful."

If I change my filter to `&(cn=*)`, the LDAP User Sync works as expected, but I need to remove multiple unwanted users everytime I sync. I'm currently using that as a Workaround.

**Expected behavior**
LDAP **SYNC** should work with my LDAP filter or an error message should tell me that this filter is not supported.

**Server:**
- Snipe-IT Docker image from https://hub.docker.com/r/snipe/snipe-it
- Version: snipe/snipe-it:v4.7.8

**Desktop:**
 - OS: Linux
 - Browser: Chromium 78 / Firefox 71

**Additional context**
Here is a Gitter screenshot of people talking about this if I'm not mistaken:
![Screenshot from 2019-12-10 14-59-20](https://user-images.githubusercontent.com/4152786/70536376-d99c5b00-1b5e-11ea-91ab-ac972b483237.png)

**Comment by KeenRivals** [comment]
That LDAP filter is saying "Search for people who are members of *all* of these groups". If that's not what you want, you might try an [LDAP OR Filter](https://ldap.com/ldap-filters/) to get "people who are members of *any* of these groups".

**Comment by Zelphy** [comment]
Of course, thank you for pointing me that out! I'll close this issue.
