### ISSUE TITLE
Feature Request - Option in LDAP sync to not duplicate users after a name change

### ISSUE THREAD

**Issue by carlashley** [grokability/snipe-it#7656]
**Server (please complete the following information):**
 - v4.7.8 

**Is your feature request related to a problem? Please describe.**
This has been raised previously (#6714), and at the time it was mentioned that not everyone uses the Employee ID field in the Snipe-IT system when synchronising from LDAP (which honestly is crazy, but whatever).

The issue remains that when staff change details like their surnames, duplicate users do end up being created. The problem here is that you then have to either delete the duplicate users, which possibly get re-created when LDAP syncs, or you have to remember that duplicate users for that person exists.

If you then do anything with the API, you then have to factor duplicate user processing into your code.

**Describe the solution you'd like**
Fundamentally, there should only ever be a single instance of any given user (when managed through LDAP sync; Snipe-IT _local_ users is a different scenario), even after details like their surname are changed. To avoid duplicates being created, an option to configure LDAP sync to ignore duplicate users based on a given Snipe-IT field value to LDAP attribute mapping should be implemented.

For example, in the LDAP Config, the option to not create new users, but update existing users where Snipe-IT `Employee ID` field value matches LDAP attribute `EmployeeID`.

**Describe alternatives you've considered**
Currently there don't appear to be any workable alternatives.

**Comment by KeenRivals** [comment]
I think using the SID would be better than an employee ID. We don't use employee IDs, but every Active Directory object has a [SID](https://docs.microsoft.com/en-us/windows/win32/secauthz/security-identifiers) that is guaranteed to be unique and never change.

**Comment by carlashley** [comment]
> I think using the SID would be better than an employee ID. We don't use employee IDs, but every Active Directory object has a [SID](https://docs.microsoft.com/en-us/windows/win32/secauthz/security-identifiers) that is guaranteed to be unique and never change.

Hence why the option that needs to be something that can be configured by us.
We use the Employee ID because in our context that is what we care.
If someone wants to map it based on SID/UID (keep in mind not all directories are AD), then that's their perrogative to configure it that way.

**Comment by KeenRivals** [comment]
Problem still exists

**Comment by carlashley** [comment]
This is still relevant.
