### ISSUE TITLE
Function ldap_control_paged_result() is deprecated in php 7.4

### ISSUE THREAD

**Issue by innocuoussoul** [grokability/snipe-it#7661]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
In build 4.8.0 (4186) with php 7.4, LDAP Sync no longer works because Function ldap_control_paged_result() is deprecated

**To Reproduce**
1. Install php 7.4
2.
**Expected behavior**
Expected LDAP Sync to work, but function has been deprecated and moved to ldap_search() instead. 
https://www.php.net/manual/en/migration74.deprecated.php

**Server (please complete the following information):**
 - Snipe-IT Version 4.8.0
 - OS: Centos 8
 - Web Server: Apache
 - PHP Version 7.4

**Error Messages**
LOG.info: ErrorException: Function ldap_control_paged_result() is deprecated in /var/www/snipe-it/app/Models/Ldap.php:289
Stack trace:
#0 /var/www/snipe-it/app/Models/Ldap.php(289): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/snipe-it/app/Console/Commands/LdapSync.php(77): App\Models\Ldap::findLdapUsers()
#2 [internal function]: App\Console\Commands\LdapSync->handle()
#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

**Additional context**
- Is this a fresh install or an upgrade? fresh
- What method you used to install Snipe-IT - manual git

**Comment by TobiasKrok** [comment]
I have the same issue. PHP v7.4 and Snipe-IT version 4.8.

**Comment by innocuoussoul** [comment]
I rolled back to 7.3 as a workaround, but hopefully this is a good heads up for v5

**Comment by bruce2004x** [comment]
@innocuoussoul how did you do that? Same error on WinServer and IIS

**Comment by innocuoussoul** [comment]
Uninstalled php 7.4 and installed 7.3

**Comment by bruce2004x** [comment]
Friend, really thanks...I rolled back to 7.3 and LDAP now works.

**Comment by jelockwood** [comment]
Yep just hit this after upgrading my system.

I eventually managed to get it running by removing php7.4 and installing php7.3. However this resurrected another different bug. Php7.3 is unable to establish SSL protected sessions to MariaDB which is why we upgraded in the first place.

If I both have php7.3 for LDAP sync and turn off SSL for MySQL/MariaDB then it works.

Please fix it!

**Comment by fumunda** [comment]
I can also confirm this is the fix.  Just migrated to Win 2012R2 IIS server using PHP 7.4 and cannot sync ldap due to error. Rolled back to 7.3.14 and it works fine.

**Comment by tom-131** [comment]
Hi,

I couldn't go back because of other PHP based applications. I decided to give it a try to disable the deprecation warning - of course this has to be handled with care. However, it worked very well.

In order to do this, just place a
```PHP
error_reporting(E_ALL ^ E_DEPRECATED);
```
into file _app/Models/ldap.php_ on line 241 (in function findLdapUsers).

Don't forget to turn the errors on again by inserting
```PHP
error_reporting(E_ALL);
```
at the end of the function, right before
```PHP
return $results;
```

**Comment by Jojonpopon** [comment]
> 
> 
> Hi,
> 
> I couldn't go back because of other PHP based applications. I decided to give it a try to disable the deprecation warning - of course this has to be handled with care. However, it worked very well.
> 
> In order to do this, just place a
> 
> ```
> error_reporting(E_ALL ^ E_DEPRECATED);
> ```
> 
> into file _app/Models/ldap.php_ on line 241 (in function findLdapUsers).
> 
> Don't forget to turn the errors on again by inserting
> 
> ```
> error_reporting(E_ALL);
> ```
> 
> at the end of the function, right before
> 
> ```
> return $results;
> ```

This workaround fixed this particular issue. Thanks!

**Comment by atsatangrode** [comment]
How did you rollback to 7.3. on CentOS 7?

**Comment by NemethP** [comment]
Are there any other workarounds?

**Comment by NemethP** [comment]
Any chance we can update to php 7.4 yet?

**Comment by jmit79** [comment]
Same problem here. I've upgraded Ubuntu to 20.04 and PHP was also updated to 7.4. The error occurs on syncing LDAP Users

**Comment by phatuous** [comment]
minimally, it would be good to note in the installation instructions that PHP 7.4 is not currently supported (at least for LDAP)

**Comment by rob1st** [comment]
Issue is still happening.

**Comment by uberbrady** [comment]
@rob1st Where? Backtrace? Log? I thought I caught everywhere where it was happening. It's possible that I missed something though.
