### ISSUE TITLE
FR: Mark as Stolen checkbox for Assets, Accessories, and Components

### ISSUE THREAD

**Issue by apizz** [grokability/snipe-it#7668]
**Server (please complete the following information):**
 - Snipe-IT Version: **4.7.7**
 - OS: **Docker running on CentOS 7**

**Is your feature request related to a problem? Please describe.**
Recently we had a laptop get stolen.  Assigned to the laptop was an accessory.  While we can set an asset status of 'Stolen / Missing', it's a little more complicated for Accessories & Components.  Because of the fact that there's X quantity that is often tied to a single purchase order, when you check-in a stolen accessory, the only option to make that item no longer available is to lower the total available quantity.  However, this causes problems, as we don't want to our original purchase order data indicating we paid $X for Y units.

**Describe the solution you'd like**
I'm not sure if this warrants a larger solution RE stolen / missing items, but for this situation I would like to be able to mark individual accessories and/or components as stolen with a checkbox.  This should allow us maintain the total # originally purchased but lower the total items available.  Ideally, I'd like to see that the item exists but have the checkout button be greyed out.

Given that the accessory and component quantities are based on a number defined by the main entry, I'm not sure what other impacts this makes from a GUI standpoint since there isn't really an item record for these types as with an asset.

Ultimately, I want a single something in the system that assets, accessories, etc. can use to indicate that they are stolen and unavailable to be deployed / assigned / checked out.

**Describe alternatives you've considered**
As stated previously, considered checking in the accessory and lowering the total available accessories.  However this loses the fact that when an order number and total purchase cost is entered for the accessories that we lose the record of that item and the fact that purchase cost represents X, rather than X-1 with the stolen item.

In addition to already having created a 'Stolen / Missing' asset status, I've also considered creating a 'Stolen / Missing' user as well as a 'Stolen / Missing' location in the attempt to centralize everything - assets, accessories, etc. - that have this status.  However, because accessories can only be assigned to users and components can only be assigned to other assets, there's nothing currently that would be universal to define this status.  For assets we'd have to check that status, for accessories if it was assigned to our 'Stolen / Missing' user, and for components if it was assigned to our 'Stolen / Missing' location.

Going with the 'Stolen / Missing' user option, we have to first make the asset deployable, assign it to this user, and then assign it to our missing / stolen status to avoid the system preventing us from checking out what is defined as undeployable.

So we're kind of working around it, but not in a universal way

**Comment by ghost** [comment]
I requested a similar feature recently to add additional status/stock management to accessories & components, to manage defective or disposed items - see here #7539. There have been other threads requesting similar features and I think the concensus is the accessories and components sections needs updating inline with the rest of snipe-IT

**Comment by apizz** [comment]
Yes

**Comment by apizz** [comment]
Yes

**Comment by apizz** [comment]
yes

**Comment by apizz** [comment]
Yes
