### ISSUE TITLE
Suggestion to set up Company Structure in Snipe-IT for delegation to users

### ISSUE THREAD

**Issue by vader860** [grokability/snipe-it#7672]
Hello, looking for a suggestion how to set up our company structure. We have divisions that are then broken up into multiple departments. We need to have some users that can read only the asset information for the entire company, some that can manage only their specific division and/or department. 

What would be the best way to set this up? Simply using multiple "companies" or would I use "company" "department" and "location" to delegate permissions? Thanks.

**Comment by kekkers23** [comment]
Hey, I think the feature request I created fulfils the same requirements you have listed - #7359
