### ISSUE TITLE
Initial Thoughts

### ISSUE THREAD

**Issue by congonatty** [grokability/snipe-it#7675]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.8.0 build 4186 (g893454dca)
 - OS: Ubuntu Server 18
 - Web Server: Apache
 - PHP Version: 5.5.48 

My current system is actually not a system. Is an MS Access database :) I came across SnipeIT which looks quite promising.

The good ones:
* Docker!!
* Free
* Simple system. Without a ton of buttons right and there which can cause into a time consuming and stressful process
* Design is simple and familiar to most of us.

While I was trying to migrate my current database I came across 2 critical issues that Im afraid they do not allow me to switch yet.
* We usually buy items with different currencies. We are based on EUR but we also use USD, AED. 
* Use of custom fields in Licenses and components. (This is a must, otherwise half of my current DB will not be able to be migrated).
* I dont know if that can be done with custom fields. But somehow to separate assets by project/budget.

I know the current feature request list has no end. I just wanted to share my +1 for those features for the next updates. For now I will just postpone the migration.

**Comment by snipe** [comment]
Hi @congonatty - thanks for your feedback. There are existing issues that cover all of the things discussed here, so closing this one.

**Comment by snipe** [comment]
(Additionally, you should know that you cannot use any of the current releases of Snipe-IT using PHP 5.x, [per the requirements](https://snipe-it.readme.io/docs/requirements).)
