### ISSUE TITLE
Bulk Audit: New Items on Top

### ISSUE THREAD

**Issue by zedgama3** [grokability/snipe-it#7676]
**Server (please complete the following information):**
 - Snipe-IT Version 4.8
 - OS: CentOS
 - Web Server: Apache
 - PHP Version 7.1

**Is your feature request related to a problem? Please describe.**
I can't tell when an item is scanned improperly when using bulk audit because it's at the bottom of the page and I'm scanning at the top.

**Describe the solution you'd like**
I would like to have it add newly scanned items to the top of the list – preferably with an item description since one of the techs failed to assign asset tags to the correct items 

**Describe alternatives you've considered**
An audible alert that denotes a bad scan.

**Additional context**
I've implemented this in my version and am providing a diff of the appropriate file here:
```$ cd /var/www/snipe-it/resources/views/hardware/
$ diff quickscan.blade.php quickscan.blade.php.bak
143c143
<                         $('#audited tbody tr:first').after("<tr class='success'><td>" + data.payload.asset_tag + "</td><td>" + data.messages + "</td><td><i class='fa fa-check text-success'></i></td></tr>");
---
>                         $('#audited tbody').append("<tr class='success'><td>" + data.payload.asset_tag + "</td><td>" + data.messages + "</td><td><i class='fa fa-check text-success'></i></td></tr>");
173c173
<             $('#audited tbody tr:first').after("<tr class='danger'><td>" + asset_tag + "</td><td>" + messages + "</td><td><i class='fa fa-times text-danger'></i></td></tr>");
---
>             $('#audited tbody').append("<tr class='danger'><td>" + asset_tag + "</td><td>" + messages + "</td><td><i class='fa fa-times text-danger'></i></td></tr>");
```

**Comment by UserGoodtm** [comment]
I confirm the need for this opportunity
