### ISSUE TITLE
Acknowledge Expiring Asset

### ISSUE THREAD

**Issue by dirceubb** [grokability/snipe-it#7677]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.16 build 4018 (gce16eae50)
 - OS: [e.g. Ubuntu, CentOS]: Ubuntu 18.04.3 LTS
 - Web Server: [e.g. Apache, IIS]: Apache
 - PHP Version: 7.2.24-0ubuntu0.18.04.1

**Is your feature request related to a problem? Please describe.**
Whenever an expiring alerts threshold for an asset is reach, it sends notifications every day until the asset is expired.

**Describe the solution you'd like**
Be able to acknowledge that an asset is expiring and so stop receiving email every day

**Describe alternatives you've considered**
I'd like to be able to set how often the alert is set ather the threshold is reached. Example: i set the expiring threshold for 60 days but set snipe it to remind me every 10 days.

**Additional context**
![Snipe it email alerts](https://user-images.githubusercontent.com/42354147/71181717-e7727000-2231-11ea-88ac-bac7a0da68e8.jpg)

**Comment by truong-luong** [comment]
I also have a problem, please help ours.

**Comment by Jaspotn0612** [comment]
I would like this option also, we have set up an alert email group and every member of that group is getting an email everyday, it would be good to have a acknowledgement period.

**Comment by dirceubb** [comment]
still relevant

**Comment by diblasio** [comment]
still relevant

**Comment by dirceubb** [comment]
still relevant, please reopen

**Comment by pawelangelow** [comment]
still relevant 👍

**Comment by Joeym0180** [comment]
Still relevant
