### ISSUE TITLE
End users not notified when assets changes

### ISSUE THREAD

**Issue by powercode-team** [grokability/snipe-it#7685]
=========================================================================
Hello everybody.
I don’t know if this is a mistake in the logic of work, or I misunderstand the logic of the application. if wrong, correct me.
There is a system unit that is assigned to the end user (company employee). when transferring property to this user, he receives a notification in the mail that some property has been transferred to him. during the operation of this system unit, let's say there was a need to increase the amount of RAM, and at the moment when the amount of RAM in the properties of the system unit was changed, the end user does not receive a notification that the configuration of its system unit has been changed. I want to understand what it is, a flaw or we have built the wrong logic

**Comment by pauloriply** [comment]
1 - when the user logs into his personal account and wants to see what asset was given to him, he does not see the details of the asset issued (for example, the amount of RAM in the computer, the size of the hard disk, ssd), does this need to be included somewhere else?
2 - the asset was checkout to the user, a notification was received by mail, the user confirmed its receipt, but when the administrator or the responsible person changes the configuration of this asset (for example, changes the amount of RAM, adds or removes a component (hdd, ssd) from the configuration), the end user is not notified in any wayб accordingly, it does not have objective information about the assset, which he uses... Is it somehow possible to fix it, or is it not contemplated by functionality?
