### ISSUE TITLE
Error: Backup failed because The dump process failed with exitcode 1 : General error : The filename, directory name, or volume label syntax is incorrect. .

### ISSUE THREAD

**Issue by deshanonline** [grokability/snipe-it#7688]
![image](https://user-images.githubusercontent.com/47201517/71505902-f649ca00-28a4-11ea-9f29-f5fba4d7c3f8.png)

please help I install snipe it on xampp and i create the backup when it's showing above screenshot error... please help me.

my **DB_DUMP_PATH='C:\xampp\mysql\bin'** 

please help me....

**Comment by nestawnar** [comment]
Hi Vihangad,

Did you find any solutions to this? if yes please let me know am also facing similar issue.

**Comment by kgortmak** [comment]
I believe you need to use forward slashes for your path, so 
DB_DUMP_PATH='C:/xampp/mysql/bin'

This works for me.
Kornelius
