### ISSUE TITLE
Error: Backup failed because The dump process failed with exitcode 1 : General error : 

### ISSUE THREAD

**Issue by nestawnar** [grokability/snipe-it#7689]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Need import CSV to assets but it  not processing to database I need to fix that

#### Actual Behavior

Am getting the error code 
Error: Backup failed because The dump process failed with exitcode 1 : General error :
![Capture](https://user-images.githubusercontent.com/16223725/71553573-481c5c80-2a2b-11ea-8d70-e8351c9b08d6.JPG)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode  yes
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running  v4.8.0 build 4186
- Version of PHP you're running 7.4.1
- Version of MySQL/MariaDB you're running  Marian DB 10.0
- What OS and web server you're running Snipe-IT on Windows server 2012 r2 Standard
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error yes
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Import and Backup
- If a stacktrace is provided in the error, include that too. Yes
- Any errors that appear in your browser's error console. Yes the same console 
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. No, its working fine.
- Include any additional information you can find in `storage/logs` and your webserver's logs. 
- Include what you've done so far in the installation, and if you got any error messages along the way. Yes,but the same as screenshot.
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by tomck** [comment]
Does your .env file contain MAIL_BACKUP_NOTIFICATION_ADDRESS=you@example.com?

If so, this is due to #7099, sorta. It has to be a valid e-mail or it will fail, I learned this the hard way.
