### ISSUE TITLE
/hardware/bytag/:asset_tag not working

### ISSUE THREAD

**Issue by philippnb** [grokability/snipe-it#7690]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

When calling the /hardware/bytag/:asset_tag endpoint I get back a wrong ID.
I need these IDs for checking out an asset via a barcode scanner and the API call to /hardware/:id/checkout.

For example my asset tags have the following ids:
0001 -> 126
0002 -> 127
0003 -> 128

etc.

But the query api/v1/hardware/bytag/0002 gives back ID 2 instead of ID 126:
![image](https://user-images.githubusercontent.com/38496064/71591419-83eb1b00-2b2c-11ea-8612-97fe6ba504f2.png).

When calling all assets via api/v1/hardware/ the mapping with asset tag to ID is correct. So one possible solution would be to create a hashmap and look up the IDs on my own...

**To Reproduce**
1. Go to the endpoint /hardware/bytag/:asset_tag (type in any asset tag)
2. Use Postman or Curl to call.
3. Verify if Asset Tag and ID in JSON match with the Snipe IT Web GUI  (e.g. in my case asset tag 002 should be hardware/126 in the web GUI)

**Expected behavior**

I expected to get the ID of the requested asset tag. Instead I get another (internal?) ID of Snipe IT

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version  v4.7.8 - build 4170 
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version: 7.1.32-1+ubuntu16.04.1+deb.sury.org+1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 78

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo: No Bearer Token in Demo available for API calls.
- Include any additional information you can find in `storage/logs` and your webserver's logs: /var/www/html/storage/logs is empty

**Additional context**
- Is this a fresh install or an upgrade? fresh
- What OS and web server you're running Snipe-IT on: Ubuntu and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Docker
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: no manual editing

**Comment by snipe** [comment]
> But the query api/v1/hardware/bytag/0002 gives back ID 2 instead of ID 126:

This works as expected. We always provide the internal ID via API, since that's what our system uses to perform most tasks. You're querying `bytag`, and you're getting the asset result for they tag you queried on. I'm not sure what `0002` means in your setup, but `0002` isn't an ID in Snipe-IT.
