### ISSUE TITLE
Column not found because DB_PREFIX is not used in query while running snipeit:upcoming-audits

### ISSUE THREAD

**Issue by komailo** [grokability/snipe-it#7700]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**The DB_PREFIX is not used when running `snipeit:upcoming-audits` and it complains about a missing column in a table which is missing the prefix.**

```
digimach@web.digimach.com [~/public_html/digimach-com/snipeit]# php artisan snipeit:upcoming-audits

In Connection.php line 664:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'assets.next_audit_date' in 'where clause' (SQL: select * from `stmg_assets`
  where `next_audit_date` is not null and `stmg_assets`.`next_audit_date` is not null and DATE_SUB(assets.next_audit_date, INTERVAL 12
   DAY) <= '2020-01-04 23:09:53' and `stmg_assets`.`archived` = 0 and exists (select * from `stmg_status_labels` where `stmg_assets`.`
  status_id` = `stmg_status_labels`.`id` and `archived` = 0 and `stmg_status_labels`.`deleted_at` is null) and `stmg_assets`.`deleted_
  at` is null order by `last_audit_date` asc)


In PDOConnection.php line 63:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'assets.next_audit_date' in 'where clause'


In PDOConnection.php line 61:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'assets.next_audit_date' in 'where clause'
```

**To Reproduce**
1. Provide a `DB_PREFIX `value in .env
2. Use `DB_CONNECTION=mysql`
3. Run `php artisan snipeit:upcoming-audits`

**Expected behavior**
After dropping the prefix from the database the expected behavior was achieved:
```
digimach@web.digimach.com [~/public_html/digimach-com/snipeit]# php artisan snipeit:upcoming-audits
No assets to be audited. No report sent.
```
 
**Server:**
 - Snipe-IT Version: 4.8.1
 - OS: 2.6.32-954.3.5.lve1.4.67.el6.x86_64
 - Web Server: Apache
 - PHP Version: 7.2.24

**Additional context**
- This is a fresh install
- The install was done manually via Git
- The database prefix was dropped to fix the issue for now
- Ran the application in DEBUG mode but the error did not contain any more information

**Comment by asolslk** [comment]
would like to check where we can have this sql query updated? facing the same issue though.. thanks

**Comment by asolslk** [comment]
@komailrk 

I solved this by adding the DB Prefix in the Asset.php located in app/Models/.

    public function scopeDueOrOverdueForAudit($query, $settings)
    {
        $interval = $settings->audit_warning_days ?? 0;

        return $query->whereNotNull('assets.next_audit_date')
            ->whereRaw("DATE_SUB(".DB::getTablePrefix()."assets.next_audit_date, INTERVAL $interval DAY) <= '".Carbon::now()."'")
            ->where('assets.archived', '=', 0)
            ->NotArchived();
    }
