### ISSUE TITLE
Unable to see asset history

### ISSUE THREAD

**Issue by asmiah** [grokability/snipe-it#7704]
#### Please confirm you have done the following before posting your bug report:

- [NA] I have enabled debug mode 

- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Our users although allocated to the correct group, i.e one created called admin, they cannot see asset history.

**To Reproduce**
1. Go to List all Assets
2. Search for the asset in question
3. Click on history
4. No data can be seen

**Expected behavior**
History of the asset is visible to a super user.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
4.8.0
 - OS: [e.g. Ubuntu, CentOS]
CentOS
 - Web Server: [e.g. Apache, IIS]
Apache
 - PHP Version 
7.2

**Desktop (please complete the following information):**
Win 10
Firefox and Edge

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
Upgrade
- What OS and web server you're running Snipe-IT on

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by asmiah** [comment]
Hi, please can someone provide an update on this?

Regards,

Abdush

**Comment by fletch8527** [comment]
Did you make sure that the search field is blank when on the history screen? I recently has this iss (no history data) but then realized I had accidentally typed in some data in the search field so it was showing nothing because nothing matched the search terms. I can add a screenshot if needed

**Comment by asmiah** [comment]
No definitely is blank.

**Comment by Scorcher** [comment]
As far as i understood, history information accessible by "Reports: view" permission. Turn it on for users who has a problem to view history information.

**Comment by Scorcher** [comment]
https://github.com/snipe/snipe-it/blob/0e0fe967e4706331ab5d7b7472da5335aa9990ff/app/Http/Controllers/Api/ReportsController.php#L21

**Comment by asmiah** [comment]
Ah, this has fixed it - so the permissions have changed then in that case, as users used to be able to see the history in v3.6 without this permission set.

Thanks @Scorcher 

Do you have any advice/help you could give me on this issue: 
https://github.com/snipe/snipe-it/issues/7717

**Comment by dinhdobathi1992** [comment]
Dear all, I got this problem same as the author, I cannot see anything in histroy field as below
![image](https://user-images.githubusercontent.com/67835317/97949113-2c10e680-1dc5-11eb-9787-b49b17d2058c.png)

**Comment by G13312** [comment]
@dinhdobathi1992 If you are still having the issue, in my case all the colums were unchecked for some reasons, I had to check them all again and then i was able to see the items!

![image](https://user-images.githubusercontent.com/61593857/101376982-4ab04480-387f-11eb-9700-b11dcccfd3be.png)

**Comment by enggal17** [comment]
Hi, the same problem as the author and I cannot see asset history on the DB side, what is the name of the table?

**Comment by Scorcher** [comment]
> @dinhdobathi1992 If you are still having the issue, in my case all the colums were unchecked for some reasons, I had to check them all again and then i was able to see the items!

... and probably lost columns on some other view :)

The reason of this behaviour was explained here #7834. I made PR #7835, but it is not merged yet...

**Comment by JonathonReinhart** [comment]
I just confirmed that, even though "Admin" is supposed to include all of the other permissions, that a user with only "Admin" privileges will see an empty table on `hardware/123#history`. Additionally granting them the `Reports: View` permission fixes this problem.

The [documentation](https://snipe-it.readme.io/docs/permissions) for Admin says:

> ... can perform all functions (create, edit, delete, etc) for all other aspects of the app.

I think either the documentation is wrong or (more likely) this issue should be reopened. @snipe?

**Comment by inietov** [comment]
For this one we thought the changes are kind of dangerous since they alter the system permissions, and as the workaround is kind of trivial we decided to let this behavior as is. See the conversation in the linked PR https://github.com/snipe/snipe-it/pull/11759
