### ISSUE TITLE
Wrong asset selected in bulk checkout

### ISSUE THREAD

**Issue by conradzik** [grokability/snipe-it#7705]
- [NO] I have enabled debug mode 
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
This issue is with the DEMO as I'm currently evaluating different asset trackers.

When performing a bulk checkout, the wrong asset is being selected when scanning barcodes. I created two assets (RAD1001, RAD1002) and after scanning barcode RAD1002, RAD1001 is being selected and added instead. I'm assuming this is because the RETURN suffix from my scanner (Socket D750) is being sent before the web app is able to fully populate the field with RAD1002.

I'm not aware of any way to delay the RETURN suffix on my scanner or any other scanner I've used. I've gone through the manual.

The only way I can stop this behavior is by disabling the RETURN suffix on my scanner and manually hitting return after scanning. This is fine temporarily, but slows things down drastically if having to do a bulk checkout of hundreds of items.

**To Reproduce**
1. Ensure 'RAD1001' and 'RAD1002' are available for checkout
2. Go to 'Bulk Checkout'
3. Scan barcode 'RAD1002' in 'Assets' field

**Expected behavior**
Would expect the correct asset attached to a barcode to be added to the 'assets' field of Bulk Checkout when scanning a barcode.

**Screenshots**
Video: https://imgur.com/a/mkBEafl

**Server (please complete the following information):**
DEMO Snipe-It.

**Desktop (please complete the following information):**
 - Mac OS 10.15.2
 - Chrome 79.0.3945.88

**Comment by TJucutan** [comment]
I'm experiencing the same issue. It seems like the first listed Asset alphabetically will always be selected on the initial scan. But after removing it from the list, scanning subsequent items is ok. It's just on the first scan.

**Comment by bcourtade** [comment]
Still broken in v5.0.12.  

If I scan an asset barcode in bulk checkout, and the barcode matches no other fields, nothing matches even though the asset exists.  

If I scan a barcode that happens to match, either partially or in full, the Asset Name field on another/same asset it does match on that.  Seems to be searching against the wrong field?
