### ISSUE TITLE
Carbon 1 Depreciated - Consider migration to Carbon 2

### ISSUE THREAD

**Issue by Jarli01** [grokability/snipe-it#7707]
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2

    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.

Just opening this to see if this is something we'll have to plan for or what that status might be on the demo side of things. 

When attempting this process via preliminary `just doing it` you get 

	./upgrade-carbon
	sh: composer: command not found
	PHP Fatal error:  Uncaught Error: Class 'Composer\Composer' not found in /var/www/html/snipeit/vendor/nesbot/carbon/src/Carbon/Upgrade.php:131
	Stack trace:
	#0 /var/www/html/snipeit/vendor/nesbot/carbon/bin/upgrade-carbon(28): Carbon\Upgrade::upgrade()
	#1 {main}
	  thrown in /var/www/html/snipeit/vendor/nesbot/carbon/src/Carbon/Upgrade.php on line 131

**Comment by iacisvols** [comment]
I got the error just now.  So yeah still relevant.

**Comment by Rapsoulis** [comment]
Hello, I can additionally provide the same error. Recently upgraded from v4.7.5 to v.4.9.0

```
./upgrade-carbon
sh: composer: command not found
PHP Fatal error:  Uncaught Error: Class 'Composer\Composer' not found in /html/snipeit/vendor/nesbot/carbon/src/Carbon/Upgrade.php:131
Stack trace:
#0 html/snipeit/vendor/nesbot/carbon/bin/upgrade-carbon(28): Carbon\Upgrade::upgrade()
#1 {main}
  thrown in /html/snipeit/vendor/nesbot/carbon/src/Carbon/Upgrade.php on line 131
```

If I can provide any additional info, please let me know.

**Comment by zayajf** [comment]
I am also experiencing this same issue.
As well as Blank page while requesting from URL

Is this project still supported?

**Comment by mengkuan1983** [comment]
same issue.

**Comment by mihsu81** [comment]
same issue here

**Comment by snipe** [comment]
That is already part of v5.

**Comment by tomhorak** [comment]
@snipe Any chance you remember what the 'fix' was for this.  I'm having the same issue upgrading a Laravel 5.3 to 5.4 app,  although I'm not using Snipe-it.  Any tips would be most appreciated, thanks!
