### ISSUE TITLE
feature request: GCS storage support

### ISSUE THREAD

**Issue by darwin67** [grokability/snipe-it#7709]
#### Expected Behavior (or desired behavior if a feature request)

Have option to use GCS as storage location. 

-----

#### Actual Behavior

Documentation and code `filesystem.php` only mention AWS S3 settings but none for GCS.

-----

#### Please confirm you have done the following before posting your bug report:

N/A

----

We can only host things in GCP and not AWS. I was looking into using App Engine as an option but instances comes and goes so storing uploaded assets on the local filesystem will not work well.

**Comment by Mistic92** [comment]
Hi, any update on this? We are full GCP and we'd like to use GCS instead of S3.
