### ISSUE TITLE
LDAP Sync

### ISSUE THREAD

**Issue by Pete987** [grokability/snipe-it#7719]
Hi all

I am rolling out Snipe IT to track assets in our firm. My question is about LDAP. I have imported our Active Directory into Snipe IT, how will new users be dealt with? 

Say someone new joins our company, will Snipe IT automatically query Active Directory and create this user for me? If so, how often does this happen? 

If not, do I have to manage my users manually after the first LDAP Sync? I can't find any documentation that answers my question

Many thanks!

**Comment by da64u** [comment]
It's not automatic. It only looks for and creates new users when you hit the LDAP Sync button. I also believe it won't delete users either.

**Comment by Nicolas155** [comment]
If you hit LDAP Sync button again it will not delete old ones, only create new users and update the existing (if you have a user that changed login, it will create a new one).

**Comment by 0xpr03** [comment]
> If you hit LDAP Sync button again it will not delete old ones, only create new users and update the existing (if you have a user that changed login, it will create a new one).

How do you deal with account deactivation ?
So when you want do disable an account of a person that left the company ?

**Comment by Nicolas155** [comment]
> How do you deal with account deactivation ?
> So when you want do disable an account of a person that left the company ?

I will just disable their login in snipeit, and leave it there.
