### ISSUE TITLE
Object locking for user edits

### ISSUE THREAD

**Issue by mmorais-idealsumario** [grokability/snipe-it#7724]
**Server:**
 - Snipe-IT Version 4+
 - OS: not relevant
 - Web Server: not relevant
 - PHP Version not relevant

**Is your feature request related to a problem? Please describe.**
Short answer: yes. Currently there's no way to prevent users from editing the same objects simultaneously, which may lead to inconsistent database data. If user U1 begins editing asset A1, nothing prevents user U2 from also editing A1 at the same time. When that happens, whichever user saves first will at best lose all their changes once the other user saves theirs, and at worst the end result will be a mix of both U1's and U2's changes.

**Describe the solution you'd like**
This can be prevented if the objects are "locked" for editing for the user that first acquires it. Some mechanism has to be implemented in the ORM that locks the object, identifying the user that locked it, and has some timeout or other solution to prevent indefinite locks, should the user forget to "save" or "cancel". Other users attempting to edit the object will be checked against the current active lock and will see their requests denied.

**Describe alternatives you've considered**
Additionally, it may be important to consider checking the object data for changes since it was opened for editing, and at the very least warn the user that the data he is seeing is not up to date.

**Comment by wefixit-AT** [comment]
Any news from this feature because this is a very important use case when multiple users change the same dataset.

**Comment by khrishino** [comment]
Any news from this feature because this is a very important use case when multiple users change the same dataset.

**Comment by rrisner** [comment]
It has been a few years and this is still a concern where there are several users who might work on the same objects. Has anything changed?

**Comment by snipe** [comment]
Not currently, but we are exploring some options.
