### ISSUE TITLE
I want create workstation in dropdown list in snipe-IT Like Asset,User, License, Please guide me on this

### ISSUE THREAD

**Issue by swegaj** [grokability/snipe-it#7741]
I want create workstation in dropdown list in snipe-IT
Like Asset, User, License,
Please guide me on this

**Comment by ferdieb** [comment]
Is there a way to add all fields of all these trees above to a custom report similar to the Custom Asset report?

**Comment by swegaj** [comment]
How to add Employee ID, Work Location is be added in the email Notification format
