### ISSUE TITLE
Pressing the Delete button in the asset table on a location page redirects to the wrong URL after it's completed

### ISSUE THREAD

**Issue by boingball** [grokability/snipe-it#7744]
#### Expected Behavior (or desired behavior if a feature request)

Pressing the Delete button when viewing a asset via locations
URL : snipeit/locations/18 (for example on my install)
Prompts to delete asset (Are you sure you wish to delete ?), then after it's complete it should keep you on the location screen you are viewing
URL snipeit/locations/18
and then refresh the asset table
-----

#### Actual Behavior

Pressing the Delete button when viewing a asset via locations
URL : snipeit/locations/18 (for example on my install)
Prompts to delete asset (Are you sure you wish to delete ?), then after it's complete it redirects to 
URL snipeit/hardware
Which means I've got to use the back button to get back to the previous location screen, and then click the refresh button under the asset table to get back on track.

-----

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running Version v4.8.0 - build 4186 (master
- Version of PHP you're running 7.2.24-0ubuntu0.18.04.2
- Version of MySQL/MariaDB you're running - not sure
- What OS and web server you're running Snipe-IT on : Ubuntu - Apache
- What method you used to install Snipe-IT manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error snipeit/locations/18 - clicking a delete icon in the asset table
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - Yes just tried and deleting an asset out of a location does redirect me back to hardware
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - nope

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by sinichi19** [comment]
Also verified in demo website, problem encountered only in asset but no problem if you try to delete from licenses.

Delete 1 asset from Pending after you successfully deleted you will be redirect to **https://demo.snipeitapp.com/hardware** and not to **https://demo.snipeitapp.com/hardware?status=Pending**
