### ISSUE TITLE
Generate Labels For Assets Checked Out to Assets From "Assets" Tab

### ISSUE THREAD

**Issue by knorquist** [grokability/snipe-it#7745]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.8.0
 - OS: Ubuntu 18.04.2
 - Web Server: Apache 2.4.29
 - PHP Version: 7.2.24

**Is your feature request related to a problem? Please describe.**
Some context: for our deployment, it made the most sense to check out assets to other assets (in our case, laptops to carrying cases). That way, we could just check out the carrying cases, instead of checking out every single laptop inside.

We're now in the process of retagging all of our devices, and here's the problem we're running into: we want to print out sheets of asset labels aggregated by carrying case, e.g. I have carrying case "T-0001", and would like to quickly print asset labels for all the laptops inside. When I go to "T-0001" and click on "Assets" to see the laptops inside, there's a nice list, but when I try to generate labels the "Go" button is grayed out and doesn't work.

**Describe the solution you'd like**
I'd like to be able to go to an asset with assets checked out to it, click on "Assets", and be able to generate labels for the assets assigned.

**Describe alternatives you've considered**
Generate labels for *all* assets, and then go through each carrying case, finding the labels for the laptops inside. This would suck.

**Additional context**
Here's a screen shot of what I'm talking about:

![Asset Label Printing](https://user-images.githubusercontent.com/3306524/72948914-8f042600-3d3b-11ea-9c61-0eaf349e4cdd.png)

I can see the assets checked out to this asset, and there's even the "Generate Labels" and "Go" button right there, but I can't generate the labels. It would be **AWESOME** if this got implemented.

**Comment by ghost** [comment]
There isn't the usual tick box to select multiple assets?

**Comment by knorquist** [comment]
@mtpnsup Nope. That's literally all I need, but it's not there for whatever reason. Is it supposed to be there?

**Comment by knorquist** [comment]
Still relevant.
