### ISSUE TITLE
Version Question

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#7746]
Is it possible to pull the SnipeIT installation version via Powershell or other CLI method?

Thank you

**Comment by JoatWiPete** [comment]
The info is in config/version.php on my system (from the Snipe-IT project directory).
I scripted this in Ubuntu with
`cat /var/www/snipe-it/config/version.php | grep -w app_version | sed "s/[^0-9+(\.0-9+)*$]//g"`
I don't know how that translates to other operating systems. I am also sure there is a cleaner script out there. Anyone feel free to correct me.

**Comment by jmartins1** [comment]
Thank you, I’ll give that a try.

 

 

Thank you,

 

A friendly reminder: Please help us track technology issues. Send your request(s) to the help desk at helpdesk@arprep.org <mailto:helpdesk@arprep.org> 

 

Jose Martins, M.Ed., MCSA, MCP

IT Administrator

 



 

303.362.1266

705 Austin Ave. Erie, Co 80516

 

 

Statement of Confidentiality

The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by jmartins1** [comment]
Thank you, I was able to modify the provided command to PowerShell. I was able to retrieve the version number.
