### ISSUE TITLE
Pre-Flight/Setup Page Requires Manually Adding "index.php" At End of URL to Show Up

### ISSUE THREAD

**Issue by Gallost** [grokability/snipe-it#7748]
#### Please confirm you have done the following before posting your bug report:

- [Yes] I have enabled debug mode 
- [Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am trying to install Snipe-IT on a Windows IIS server.
Following this guide: https://www.youtube.com/watch?v=kxGGQutvktM, I have completed all the steps leading up to the Pre-Flight. The physical path of the site is set to:
C:\inetpub\wwwroot\snipe-it\public

When attempting to access the site (*http://server_ip/*), an error message pops up saying "This page can't be displayed." However, if I add a trailing "index.php" (*http://server_ip/index.php*), the URL jumps to (*http://server_ip/index.php/setup*), and the Pre-Flight page would show up in text only.

URL Rewrite is installed on the IIS server, though no configurations were made. 
APP_URL in the .env file is set to "http://server_ip"

**To Reproduce**

**Expected behavior**
The Pre-Flight page should load without adding the trailing "index.php." 

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: 4.8.0
 - OS: Windows 10
 - Web Server: IIS
 - PHP Version: 7.4.1

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
   Fresh Install
- What OS and web server you're running Snipe-IT on
   Windows 10 on IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
   Manual Install
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
My guess would be that index.php isn't set as a default file in your web server settings, or your rewrite rules aren't set up or configured correctly. This is a server config issue not a Snipe-IT issue though.

**Comment by Gallost** [comment]
On the IIS Manager, I checked the Default Document list and "index.php" is indeed set a as a default, the entry type is local. For the rewrite rules, am I just supposed to import them via the .htaccess file located in public folder?

**Comment by Gallost** [comment]
Quick update: I changed the port number of the Snipe-IT server from 80 to 801, and now when I browse the site the url automatically jumps to "http://my_ip:801/setup", although a HTTP error 404 not found pops up.

**Comment by Gallost** [comment]
Snipe-IT is up and running! Here are the few issues I encountered and how they were resolved:

- Browsing to the site does not automatically redirect to /setup
   *Resolved by changing the port number from 80 to 801, not sure exactly what caused that to happen*
- After the site is redirected to /setup, a 404 not found error appears
   *Resolved by replacing the old public folder with a new one re-downloaded from the snipeit website*

**Other Changes**
- Page URL in .env was changed to *http://my_ip:801*
