### ISSUE TITLE
Snipe-it post install can't get to pre-flight page but apache default page(similar to issue #6548)

### ISSUE THREAD

**Issue by bee-z-bone** [grokability/snipe-it#7749]
#### Expected Behavior (or desired behavior if a feature request)

Supposed to get pre-flight page but its only route to Apache default page. If I add some text append to the url, it shows the php code page

-----

#### Actual Behavior
If I go to my localhost or ip of web server page, I get the normal Apache default page but if I add something to the URL, I get this.
<?php

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels nice to relax.
|
*/

require __DIR__.'/../bootstrap/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/../bootstrap/app.php';

// set the public path to this directory
$app->bind('path.public', function() {
    return __DIR__;
});

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh Install**
- Version of Snipe-IT you're running **4.7.8**
- Version of PHP you're running **7.3.11**
- Version of MySQL/MariaDB you're running  **mysql Ver 15.1 Distrib 5.5.60-MariaDB**
- What OS and web server you're running Snipe-IT on **Linux 3.10.0-975.el7.x86_64, Apache 2.4.6**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **using snipeit.sh script & manual steps**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **YES**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  **NOT get to pre-flight page, ONLY load Apache page**
- If a stacktrace is provided in the error, include that too.  **N/A**
- Any errors that appear in your browser's error console. **N/A**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **N/A**
- Include any additional information you can find in `storage/logs` and your webserver's logs.
**no log file under storage/logs location**
- Include what you've done so far in the installation, and if you got any error messages along the way.
**Set up Apache server, install php, install mariaDB manually, then run modified snipeit.sh scirpt BECAUSE the server is not enable to outgoing traffic, i.e, had to manually install all rpm, dependencies including composer packages**
- Indicate whether or not you've manually edited any data directly in the database **NOPE, no manual edit
![apache setup php page](https://user-images.githubusercontent.com/57014786/73016215-ad6d2e80-3dda-11ea-90d5-beecb69341b7.PNG)
![apache default page](https://user-images.githubusercontent.com/57014786/73016342-ea392580-3dda-11ea-82cd-5c48b59160f5.PNG)

**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
If PHP is being displayed in the browser, PHP is either not installed on that server or it's not enabled in Apache.

**Comment by bee-z-bone** [comment]
![php module list Edited](https://user-images.githubusercontent.com/57014786/73023600-1d82b100-3de9-11ea-9063-052367ca13c0.png)

Thanks @snipe for quick response. Had the php modules & version on the attached output. Any pointer? This is similar to #6548 (closed) but found no solution on that issue.

**Comment by bee-z-bone** [comment]
I was able to re-configure the Apache with php and now the pre-flight page is loading. Thanks @snipe. The issue resolved.
