### ISSUE TITLE
Public root for snipeit

### ISSUE THREAD

**Issue by Neltharionx** [grokability/snipe-it#7758]
Hello,

I'm a beginner with Debian10 and so I tried to install snipeit. Everything was alright until I tried to connect to my server :
" Do'h. If you're seeing this, your DocumentRoot is set incorrectly. it should be set to the public directory."

Okay I know what is my problem, but I don't know how to set it in the public directory.

Somebody could help me ?

**Comment by reissboafo** [comment]
you can run `php artisan serve`

**Comment by Neltharionx** [comment]
When I try , I have this message:
Could not open input file : artisan

**Comment by reissboafo** [comment]
is composer installed? you can get more information from https://snipe-it.readme.io/docs/installation

**Comment by Neltharionx** [comment]
Everything is installed except openssl and ldap

**Comment by erniecauthen** [comment]
I am coming at this from Ubuntu using Apache2 so adjust any of my recommendations accordingly to your environment. Here is something that you can verify and try.

Try setting the DocumentRoot to _/var/www/%foldername%/public_ where the %foldername% is the root folder for SnipeIT.

Also, if you CD into that directory and run `php artisan serve` what do you get back?

**Comment by snipe** [comment]
The public directory within the snipe-it project root folder on your server would be the DocumentRoot, as @erniecauthen mentioned. (Also be sure to restart your web server after making that change.)

**Comment by Neltharionx** [comment]
I'm a newbie, the document root of all snipe-it files ? Or a special document ?

Also I can't use the command **php artisan serve**

**Comment by Neltharionx** [comment]
Okay, I change that in default-ssl in apache2 where there is Documentroot I set to the right document so : snipeit/public and then I have the same error.  I have also restart apache2.

**Comment by Neltharionx** [comment]
Here's what I got when I use Php artisan serve
![error](https://user-images.githubusercontent.com/57038627/73923881-de199180-48cb-11ea-8a41-f3d22a6fbf2e.PNG)
