### ISSUE TITLE
Required Manager Approval when user is requesting for asset

### ISSUE THREAD

**Issue by prayagdhaduk123** [grokability/snipe-it#7760]
**Server (please complete the following information):**
 - Snipe-IT Version : v4.8.0 build 4186 (g893454dca)
 - OS: [e.g. Ubuntu, CentOS] : Ubuntu 16.04
 - Web Server: [e.g. Apache, IIS] : Apache2
 - PHP Version : 7.4.1

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi,
I'm Very new to the snipe it and need help.

When User is requesting for any asset, request is going to admin directly.

As per our need we required manager approval when user is requesting for any asset.

Requirement is when user is requesting for any asset, request will go to admin and manager both, then manager has to accept/reject the request and admin can check the manager response and can checkout the asset to user if accepted by manager.

is there any option available where i can enable this feature so manager belongs to user will get the notification as user A has requested this asset, and after accepting the asset request it will reflect in request page so that admin can check and then assign the asset to user?

please help me in this @snipe 

Thanks in advance.

**Comment by ferdieb** [comment]
I would like to extend this functionality to include optional/required for multiple 'approvers' - for example User request asset > manager approval required > 
                                                                                              >Financial (budget manager) approval 
                                                                                              >Purchasing dept/Asset Manager approval

**Comment by itsFlake** [comment]
I'm using Snipe a while and i'm missing this feature. 
In my Company all requests must be approved by Manager.

It would be an nice workflow.

**Comment by cookierun22** [comment]
Hi, may I know if this request is possible to be done? Please reopen the request.
