### ISSUE TITLE
Permissions revamp

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#7763]
**Server (please complete the following information):**
 - Snipe-IT Version v4.8 
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.3

**Is your feature request related to a problem? Please describe.**
In real life there are different employees responsible for different assets. In our company there are:
IT admin — responsible for computers, displays, software licences;
Phones admin - responsible for landlines;
Mobiles admin - responsible for mobiles and SIM cards;
Office admin - responsible for office assets.

**The problem**: all admins have access to IT stuff, phones, mobiles, office equipment and there is no way to prevent this. (Nothing prevents Carren from HR, responsible for pen and paper, edit/delete/manage IT assets or mobiles.

I have tried using multi-company feature (company as type of assets)  and admins can't see assets outside their company (GOOD), but also can't see employees outside their company (BAD).

**Describe the solution you'd like**
There should be an option to assign asset categories to admin. In my head it looks like this:
1. You create asset categories: "IT assets" with subcategories ("Laptops", "Desktops", "Displays", etc.); "Mobiles" (subcategories: "SIM cards", "Mobiles", "Memory Cards", etc.), "Tablets" and so on.
2. In permissions you set Peter from IT as admin for "IT assets" (it automagically implies that he is admin for all subcategories). Peter sees equipment in "IT assets", but categories "Mobiles" and "Tablets" are unavailable for him.
3. You set Steve from IT as admin of "Laptops" and he only has access to "Laptops" subcategory.

**Describe alternatives you've considered**
A workaround would be to make **people not assigned to any Company** be **visible to all admins**.
This way you would enable Multi Companies in settings, create asset groups as Companies: "IT assets", "Mobiles", "Tablets" and assign each admin to different asset group/company. So admins would see only assets of asset group/company they are assigned to and all People who are Company unassigned or are assigned to admin's asset group/company. Downside - multi companies support is lost because asset groups of single firm are used as different companies in SnipeIT. Also, hierarchy would not be possible (as described in **_Step 2._**).

**Additional context**
I've got creative and made a table of permissions, how I imagine it.
![permissions](https://user-images.githubusercontent.com/3755203/73252113-e20a2d00-41c2-11ea-89bf-d6f9dabed6bf.png)

**Comment by kekkers23** [comment]
Hey, this looks similar to my Feature request https://github.com/snipe/snipe-it/issues/7359
