### ISSUE TITLE
snipeIT asset list is blank

### ISSUE THREAD

**Issue by nOOrylw** [grokability/snipe-it#7765]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior
**I noticed today that my inventory info gone. When i log on the my page i only see asset list blank, recent activity blank and even users gone. However, i have total assets populated in the dashboard where you have summary of licence, accessories and consumables. User tab is also empty.**
(what actually happens goes here)

![snipe](https://user-images.githubusercontent.com/31098976/73264679-990ea480-41d3-11ea-8314-200829a0d813.PNG)
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - **Existing installation, not upgraded**
- Version of Snipe-IT you're running - **v4.77**
- Version of PHP you're running - **v7.2.24**
- Version of MySQL/MariaDB you're running - **v5.7.29**
- What OS and web server you're running Snipe-IT on - **v18.04.21**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **via ssh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Without errors logs, we don't have any way to speculate what would be happening here.
