### ISSUE TITLE
Snipe on Windows - Backups

### ISSUE THREAD

**Issue by Pete987** [grokability/snipe-it#7767]
Hi all, I have 2 questions I hope you can help with. 

I get an error when backing up Snipe, and it appears to be related to the back and forward slashes in this path

Backup files are located in: C:\inetpub\snipe-it-master\storage/app/backups

I have tried changing the slash direction on line 444 of SettingController.php but that resulted in an error whenever I tried to access the Admin settings of the site. Can anyone assist me please? 

Lastly, with a view to the next step - to automate backups, will we use Windows Scheduler? 

Thanks very much!

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by sinichi19** [comment]
Check your .ENV dump path 
https://snipe-it.readme.io/docs/configuration

also check your folder permission (snipe-it folder)

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.  Don't be intimidated by the length of this page. The configurat...</div></blockquote>

**Comment by snipe** [comment]
This is just about always a path issue in the .env (as mentioned by @sinichi19) or a permissions issue.

Re: automated backups, yep - you'd want to schedule the backup using Windows Task Manager, invoking the specific backup command.
