### ISSUE TITLE
Help Request - SSL in docker

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#7768]
#### Expected Behavior (or desired behavior if a feature request)

Snipe-IT has neen installed on a Ubuntu Server and Docker, with docker companion. Cert files have been imported to /var/lib/snipeit/ssl and names accordingly. 

The Docker-compose.yml file has been updated to:
APP_URL=https://localhost

and Ports 443:443 added to the ports section.

After restarting the docker we expected the site to be available over ssl.

-----

#### Actual Behavior

the site was then not avilable over port 80 or 443, and we had to roll back.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running
4.8.0
- Version of PHP you're running
The latest with the docker container
- Version of MySQL/MariaDB you're running
- Version of PHP you're running
The latest with the docker container
- What OS and web server you're running Snipe-IT on
Docker
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
NA
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Iizuki** [comment]
I recently encountered a similar issue. In my case the reason was that the certificate files were owned by root, and therefore the docker user inside the container could not use them. Chowning them to docker fixed the problem.
