### ISSUE TITLE
Compatible DB versions for Windows Install

### ISSUE THREAD

**Issue by r3ptar** [grokability/snipe-it#7769]
If I follow the requirements for Windows server and attempt to download the MariaDB version suggested it goes to a dead link. I've tried to manually download version 10.0.14 from MariaDB's website and those links are also dead. Is this compatible with other versions of MariaDB?

**Comment by sinichi19** [comment]
Try MySQL

**Comment by snipe** [comment]
It *should* be compatible with any modern version of MariaDB/MySQL

**Comment by r3ptar** [comment]
thanks guys. I gave up on the windows install and just switched to linux. Your software is great
