### ISSUE TITLE
Status Change Option When Checking Out an Asset

### ISSUE THREAD

**Issue by bowilliams48** [grokability/snipe-it#7770]
#### Expected Behavior (or desired behavior if a feature request)

When I checkout an asset, I would like to be able to change the status of said asset - just like I can when checking in an asset. 

![image](https://user-images.githubusercontent.com/43254025/73395948-6a193100-42ae-11ea-8b6c-1a7080edd8bf.png)

-----

#### Actual Behavior

At checkout page as of now there is no option to change asset "Status" option.

-----

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
install
- Version of Snipe-IT you're running
  Version v4.8.0 - build 4186 (master)

**Comment by bowilliams48** [comment]
This issue is still relevant. I would like to be able to change the status of an asset when I checkout the asset.

**Comment by alkalinelito** [comment]
This issue is still relevant.

**Comment by snipe** [comment]
This feature was added ages ago.

https://demo.snipeitapp.com/hardware/128/checkout

<img width="796" alt="Screen Shot 2021-07-06 at 7 49 56 PM" src="https://user-images.githubusercontent.com/197404/124693033-8baf1c80-de93-11eb-9903-022516f573b5.png">




<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/128/checkout">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by abresemann-ctrlQS** [comment]
> This feature was added ages ago.
> 
> https://demo.snipeitapp.com/hardware/128/checkout
> 
> <img alt="Screen Shot 2021-07-06 at 7 49 56 PM" width="796" src="https://user-images.githubusercontent.com/197404/124693033-8baf1c80-de93-11eb-9903-022516f573b5.png">
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/3f2d9feccae7cd6385c9fc30a080435adee7ce46d66d566c7341352cc371e9e1/68747470733a2f2f64656d6f2e736e69706569746170702e636f6d2f66617669636f6e2e69636f">**[Snipe-IT Asset Management Demo](https://demo.snipeitapp.com/hardware/128/checkout)**

Hey,
I do see the status field, but I can't choose any other statuses: 
![image](https://github.com/snipe/snipe-it/assets/148976986/20f2f05c-bcbe-445d-a48d-2a9bcfe8ce78)

What could be the reason for this?

<blockquote><img src="favicon.ico " width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/128/checkout">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
