### ISSUE TITLE
Ldap Sync Issues after Upgrade 4.6.5 to 4.8.0

### ISSUE THREAD

**Issue by xinput** [grokability/snipe-it#7773]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
We did an upgrade from v.4.6.5 to 4.8.0 as in v.4.6.5 we faced an error that users got disabled on ldap sync. For the update we switched from a manual install to a git install. After the update we are experiencing the problem that the LDAP Search OU of a location is completely ignored on ldap sync and it processes the whole Base DN. For Example our Base Bind DN is:
`OU=EMEA,OU=myorg,DC=organization,DC=org` and we have 5 locations witch each Location using a Seach OU:
`OU=GERMANY,OU=EMEA,OU=myorg,DC=organization,DC=org`
and so on. 

When we try synchronizing the location Germany it processes several minutes and synchronizes every user from the Base Bind DN `OU=EMEA,OU=myorg,DC=organization,DC=org` so we have more than 4,5k users imported into snipe IT. 
When changing the Base Bind DN in SnipeIT Ldap Settings to `OU=GERMANY,OU=EMEA,OU=myorg,DC=organization,DC=org` and starting a sync for this location  it is working fine. 
Because of that we are currently using a Powershell Script (that script normally overwrites the Base Bind DN in the mysql database with the location ou - runs a ldap sync and resets the base bind DN back to it's normal state - for every location -a daily sync) 
We have tried several options like creating a new database, check every option without success.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Locations'
3. Configure 'Search OU for this Location'
4. Go to 'Users'
5. Click on 'LDAP User Sync'
6. Select the configured Location
7. Click 'Synchronize'
8. Wait till it finishes (mostly runs into a timeout due to the huge amount of our User Accounts in EMEA)
9. Go to 'Locations' 
10. Check number of user accounts of the previous synchronized Location

**Expected behavior**
The LDAP sync should only synchronize the users found in the given Search OU which is configured for each location and not the Base Bind DN

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.8.0
 - OS: Windows Server 2016
 - Web Server: IIS
- PHP Version 7.2.7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox, Edge, Internet Explorer
 - Version: various

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - no output
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - not possible to recreate this error. 
- Include any additional information you can find in `storage/logs` and your webserver's logs. - no error logs are written in this process.

**Additional context**
- Is this a fresh install or an upgrade? -  Mix of both - Upgrade with switch to git install
- What OS and web server you're running Snipe-IT on: Windows Server 2k16 with IIS
- What method you used to install Snipe-IT? - git install
- Include what you've done so far in the installation, and if you got any error messages along the way. 
- Indicate whether or not you've manually edited any data directly in the database - no data were edited directly in the DB

**Comment by osnala** [comment]
I am experiencing the same issue, what are you using in your LDAP filter?  I am using the All User Objects except disabled accounts filter &(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))

**Comment by xinput** [comment]
Hey,
we don't use any special filter. Just use `&(cn=*)`
