### ISSUE TITLE
Microsoft Requiring LDAP Signing in March 2020 Updates

### ISSUE THREAD

**Issue by KeenRivals** [grokability/snipe-it#7775]
Not a bug, but more of a PSA. In March 2020 Microsoft will push an update to require ldap channel binding & signing by default. This could break ldap for snipe users using plain olde ldap against Active Directory. Not sure what the best course of action is (if any) but thought it might help to pass the info along.

- [2020 LDAP channel binding and LDAP signing requirement for Windows](https://support.microsoft.com/en-us/help/4520412/)
- [ADV190023 | Microsoft Guidance for Enabling LDAP Channel Binding and LDAP Signing](https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV190023)

**Comment by tdkl** [comment]
Yeah, I'm wondering where and how to load the self-signed certificate (.local domain) so the snipe-it can use it to authenticate againsts AD/LDAP?

**Comment by KeenRivals** [comment]
If you have an enterprise CA, it's better to use the CA cert. But if not you can export the DC's certificate from certlm.msc on the DC itself. On Debian/Ubuntu you copy the cert in pem format to /usr/local/share/ca-certificates/ then ``sudo update-ca-certificates``. Watch out, I don't know what the default DC ldap cert lifetime is but you'll have to rotate it on your server whenever the DC decides to renew it.

**Comment by magicjmarker** [comment]
I'm attempting to update my SnipeIT install LDAP/Active Directory to use LDAPS authentication against my Active Directory domain controller. I've got the wildcard SSL installed on the domain controller and have other third party apps authenticating with no issues over LDAPS. I'm struggling to get SnipeIT working over LDAPS when updating my LDAP server to ldaps://server.local.domain.com. When testing I get the error: "Could not bind to LDAP: Can't contact LDAP server". My SnipeIT install is running on Windows Server.

**Comment by KeenRivals** [comment]
Microsoft added clarification [to their advisory](https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV190023) that they will not change the ldap signing requirement defaults on new or existing domain controllers. The updates that give admins extra control over signing are live now.
