### ISSUE TITLE
Checkout Consumables via API

### ISSUE THREAD

**Issue by ricochetmoo** [grokability/snipe-it#7776]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.15 build 4011 (gd1e9fbfa2)
 - OS: Debian
 - Web Server: Apache
 - PHP Version 7.0.33-14+0\~20191218.25+debian9\~1.gbpae1889

**Is your feature request related to a problem? Please describe.**
We have built a barcode scanner frontend for our internal usage with Snipe-IT and have recently started tracking consumable burn rate and want to add consumable checkout to our frontend.

**Describe the solution you'd like**
Add an API method to checkout consumables to users.

**Comment by andres-baller** [comment]
This feature is still missing, and would be very useful for those of us that have any sort of application that acts as an alternate frontend to SnipeIT.

I may try working on this myself, as it's a feature my org needs, and opening a PR if it gets anywhere...
