### ISSUE TITLE
Snipe-IT Docker gives whitescreen

### ISSUE THREAD

**Issue by Twa8Twa** [grokability/snipe-it#7777]
After following the Snipe-IT Docker guide: https://snipe-it.readme.io/docs/docker. (On Linux)
I stranded up on the "SSL disabled/SSL enabled" step. I push the command: 
` docker run -d -p YOUR_PORT_NUMBER:80 --name="snipeit" --link snipe-mysql:mysql --env-file=my_env_file --mount source=snipe-vol,dst=/var/lib/snipeit snipe/snipe-it `

I get the response: ` Docker: invalid publish opts format (should be name=value but got 'YOUR_PORT_NUMBER:80' `

-----
A thing to note is that i saved my "Docker-compose.yml" and ".env" file in /root/Documents/Snipe-IT/
But i can't see why this would be a problem.

When i got to IP:80 in my browser i just get a whitescreen, no errors.
-----

Hope someone can help me out.

Thanks in advance

**Comment by cwaninger** [comment]
First of all, did you really run the command with "YOUR_PORT_NUMBER" or you just missed changing that for creating this issue? 
If you ran the command with the string "YOUR_PORT_NUMBER", change the Port according to your environment. `docker run -d -p 8080:80` .... This example would bind port 8080 of the container to port 80 of your hostmachine. 
Check Docker Syntax of docker run command for proper usage.
Hope that this helps already.
