### ISSUE TITLE
Error: document root

### ISSUE THREAD

**Issue by Neltharionx** [grokability/snipe-it#7780]
- Snipe-IT Version the last
 - OS: Debian 10
 - Web Server: apache2
 - PHP Version the last

**Error Messages**
D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.
**Additional context**

So I've change apache2 default-ssl document root to : snipeit/public
And then after a restart I have the same message.
(I'm a newbie in Linux)

**Comment by Neltharionx** [comment]
Here's what I got when I run php artisan serve 
![error](https://user-images.githubusercontent.com/57038627/73923971-ff7a7d80-48cb-11ea-9cf0-6814a009b612.PNG)

**Comment by erniecauthen** [comment]
Hey @Neltharionx , 

The error message is referencing that it can't access the _autoload.php_ file located at _/var/www/hrml/snipteit/vendor/_. Can you provide feedback for the following:

1. Does the vendor file at _/var/www/html/snipeit/vendor_ have a 755 permission. It should look like _drwxr-xr_-x if you do a `ls -l` in your snipeit folder.
2. Do the files in your snipeit directory show www-data as the owner and group?
3. When running the `php artisan serve` are you using `sudo` for this?

**Comment by Neltharionx** [comment]
Hi, @erniecauthen I just solve this problem, now I have a error about the php pdo, I looked up on the install, he's installed and as mentionned I wrote in php.ini extension=pdo.so and still the same issue.
![image](https://user-images.githubusercontent.com/57038627/74029216-7b4bf700-49ac-11ea-8bbf-8a469d011652.png)
