### ISSUE TITLE
Checkout asset should change location for assets assigned to it

### ISSUE THREAD

**Issue by avram-battery** [grokability/snipe-it#7781]
**Describe the bug**
When there is an asset which has been checked out to an asset, changing the location of the "parent" asset does not change the location of the child asset.

**To Reproduce**
1. Create an asset 
2. Assign that asset to a location
3. Create a second asset
4. Assign the second asset to the first asset
5. Check in the first asset, then assign it to a different location

**Expected behavior**
I would expect that all assets assigned to an asset would have their assignment data updated if the parent asset was re-assigned. This would be in the case of a keyboard assigned to a computer, or a credit card reader assigned to a POS terminal. If the computer was relocated, it follows that the accessories would relocate as well.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.6 build 4143 (g3dc2cc9f2)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.2

**Comment by jose-duarte** [comment]
Already reported: https://github.com/snipe/snipe-it/issues/7203
