### ISSUE TITLE
Licenses - item view, add 'checkout notes' to columns list

### ISSUE THREAD

**Issue by achitofel** [grokability/snipe-it#7784]
**Server (please complete the following information):**
 - Snipe-IT Version v4.8.0 - build 4186 (master) 
 - OS: Windows
 - Web Server: IIS
 - PHP Version 7.3

**Is your feature request related to a problem? Please describe.**
when you view a license (/licenses/id), you only get a few columns available:
Seat
User
Department
Asset
Location
Checkin/Checkout

once you checked out a license to a user/asset, you have the option to add note.
This note is not displayed on this page .

**Describe the solution you'd like**
allow adding the checkout note column to this page

**Describe alternatives you've considered**
have a custom license report that generates per licenses assigned assets/users where we can select the fields in the report.

**Comment by reggidwi** [comment]
yes me, the same problem to

**Comment by achitofel** [comment]
Yep

**Comment by achitofel** [comment]
Yes
