### ISSUE TITLE
Cannot import CSV

### ISSUE THREAD

**Issue by PDSmokes** [grokability/snipe-it#7789]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

When i try to import a CSV it gets stuck on processing. I have tried with my own CVS modeled after the sample CSV provided as well as the sample it self after splitting it to 10. Same issue.

Running in docker and the setup is from the official documentation. However php artisan does not seem to work in the containers so i am not able to i.e update AFAIK.

**To Reproduce**
1. Go to http://slide-it.com/import
2. Import sample-assets.csv
3. process and choose assets in import type
4. Press import after making sure all import fields have a value.

**Expected behavior**
I expect it to sit for a bit and then finish and give a completed message. However it doesn't go through

**Screenshots**
http://i.imgur.com/C6CPGah.png
http://i.imgur.com/XmTE0yT.png

**Server (please complete the following information):**
 - Snipe-IT Version : v4.8.0 Build 4186)
 - OS: Debian 10 (Docker)
 - Web Server: The one that came in the docker. Suppose it is Nginx
 - PHP Version: 7.1.33-3+ubuntu16.04.1+deb.sury.org+1

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 / Windows 10 1909
 - Browser Chrome, Microsoft Edge (chrominium), Firefox.

**Error Messages**
https://pastebin.com/XDXqgCTH

**Additional context**
Fresh install.
Installed using the docker documentation provided by Snipe-IT. It is configured on Portainer.
- Everything seems to work. Except for importing.
-I have not edited anything in the database. I am fairly new to this setup.

**Comment by knorquist** [comment]
I'm getting the same error. I noticed [pull #7787](https://github.com/snipe/snipe-it/pull/7787) added 'requestable' as a fillable attribute and wonder if it's related.

**Comment by Traceur10** [comment]
I had this problem when i was behind a reverse proxy and trying to pass HTTPS web traffic to the HTTP container. If you're using SSL, copy your SSL certs to this location inside the container:
/var/lib/snipeit/ssl/snipeit-ssl.crt
/var/lib/snipeit/ssl/snipeit-ssl.key

**Comment by itstallion** [comment]
I'm having the same issues as well.  Import runs from the command line.  I'm also having an issue where Serial numbers are not getting pulled in from the csv doing an Asset import.  I've tried changing the serial number from letters and numbers to straight numbers with no change.

I also confirmed that the issue is reproduced using the sample-asset.csv

**Comment by fumunda** [comment]
I was having the same issue on a test environment i just set up this morning.  It wouldnt import ANY of my csv's, even ones that I just used on my new site i spun up 2 days ago.  after hours of screwing with it and debugging, i decided to add the field 'Requestable' to my import with a value of 'Yes' and tried again.  Whaddya know, went through without a hitch.  

I am guessing that Requestable is now a required field?  And when did that change?  I just set up another server on Tuesday, 2 days ago, using same exact procedure and didnt have any issues.

So try that...

**Comment by itstallion** [comment]
Yeah after some debugging of my own I found the problem.

Line 82 in app/Importer/ItemImporter.php 

$this->item['serial'] = $this->findCsvMatch($row, "serial");

it should be 

$this->item['serial'] = $this->findCsvMatch($row, "serial_number");

You can change the csv header name from 'Serial number' to 'Serial' or modify the code to get it working.  I had to have serial numbers as I'm using Micro$oft Deployment Toolkit and it's setup to prepopulate the task list name/ hostname/ ou's by the machines serial number and I'm going to populate my MDT database with data from the Snipeit database.

**Comment by fumunda** [comment]
Interesting.  I had tried both 'serial' and 'serial number' as fields and it didnt matter.  I am going to have a look at the other server i just set up and see how that ItemImporter.php is coded.  The other csv's i used for that worked fine but not this on most recent site i set up.

Good catch!

**Comment by knorquist** [comment]
@itstallion I got the same issue with the importer not doing serial numbers.

**Comment by zacharysandberg** [comment]
I have also set up a new manual install of v4.8 within the last few weeks on top of Debian 9 with Apache 2.4.25, PHP 7.4,  and MariaDB 10.1.  Everything seems to be working great except for the importer, which is a critical feature for our test case.

Changing the serial/serial number suggestion didn't work for me, and in addition to the importer never completing during import, I am also unable to delete previous (attempted) imports, and when I click the trash can, I just get a blank red bar at the top of the page that has no text in it.

**Comment by wb-utsa** [comment]
I'm having this issue too with v4.8, local install. Console says:

`all.js?id=bf1b244d8cc9096e4a18:4 POST http://localhost/snipeit/public/api/v1/imports/process/4 500 (Internal Server Error)`

PHP 7.4

**Comment by abate** [comment]
same exact problem here. Last docker image behind a traefik reverse proxy ... Tried to change `Requestable` and `Serial Number` with no success ...
Digging a bit more :
```
[00:11:04] LOG.error: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Spatie\DbDumper\DbDumper::setPort() must be of the type integer, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 36 in /var/www/html/vendor/spatie/db-dumper/src/DbDumper.php:117
#0 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php(36): Spatie\DbDumper\DbDumper->setPort('${MYSQL_PORT_33...')
```
and
```
[00:11:04] LOG.error: Type error: Argument 1 passed to Spatie\DbDumper\DbDumper::setPort() must be of the type integer, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line ...
```
so in my case I guess a problem with my mysql configuration, even though it seems strange as the site is working fine ...

that seems related to https://github.com/snipe/snipe-it/issues/7353

and fixed by adding `DB_PORT=3306`

**Comment by chshanoo** [comment]
> I'm having this issue too with v4.8, local install. Console says:
> 
> `all.js?id=bf1b244d8cc9096e4a18:4 POST http://localhost/snipeit/public/api/v1/imports/process/4 500 (Internal Server Error)`
> 
> PHP 7.4

I had the same issue on localhost. Tried multiple solutions but what worked for me was a small change in .env file. In Outgoing Mail section
change "MAIL_DRIVER=smtp"  to "MAIL_DRIVER=log"
Import worked after that.
