### ISSUE TITLE
LDAPS auth in WAMP running on Windows Server

### ISSUE THREAD

**Issue by magicjmarker** [grokability/snipe-it#7794]
I have installed a Godaddy wildcard SSL on my domain controller and have SSL Auth working with other third party apps. What am I missing to get secure SSL LDAPS authentication working with SnipeIT running on WAMP?

#### Expected Behavior (or desired behavior if a feature request)

LDAPS authentication to Active Directory domain controller with SnipeIT running in WAMP.

-----

#### Actual Behavior

After updating LDAP server to ldaps://servername.local.domain.com I get the error: "Could not bind to LDAP: Can't contact LDAP server. 

LDAP authentication works fine in regular LDAP.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running: v4.8.0 build 4186
- Version of PHP you're running: 7.2.4
- Version of MySQL/MariaDB you're running: MySQL 5.7.21, MariaDB: 10.2.14
- What OS and web server you're running Snipe-IT on: Windows 2012R2, WAMPServer 3.1.3

**Comment by tobsome** [comment]
Same problem here.

EDIT: I made a crontab which is syncing the users with our Active Directory. If I check the checkbox 'Allow invalid SSL certificate' the crontab is working. If it's unchecked it's not syncing the users. I've to press 'Test LDAP' multiple times until it works. The certificate is fine, we've deployed it on multiple services.

**Comment by magicjmarker** [comment]
I solved this by moving my Snipe server to a Ubuntu server installation. The SSL issue is now gone. I never got it LDAP SSL working with a WAMP install on a Windows server.

**Comment by tobsome** [comment]
> I solved this by moving my Snipe server to a Ubuntu server installation. The SSL issue is now gone. I never got it LDAP SSL working with a WAMP install on a Windows server.

Hm, I'm on Ubuntu 18.04. as well. What did you do in detail to get it running?
