### ISSUE TITLE
Is there a way to grant restrictive users the ability to see multiple companies assets.

### ISSUE THREAD

**Issue by narendrasingh-code** [grokability/snipe-it#7797]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by narendrasingh-code** [comment]
Snipe-IT Version - 4.8
OS: Server 2016 STD
Web Server: IIS Version 10
PHP Version - 7211

For Eg we want Accounting and Finance Dept read only Access to all the assets in all Companies.

**Comment by bhdung** [comment]
Please help
