### ISSUE TITLE
Use Electronic Signature Capture Pad with Snipe-IT to sign 

### ISSUE THREAD

**Issue by yanagha** [grokability/snipe-it#7798]
**Server (please complete the following information):**
 - Snipe-IT Version  **Version v4.8.0 - build 4186** 
 - OS: [e.g. Ubuntu, CentOS]     **CentOS**
 - Web Server: [e.g. Apache, IIS]  **Apache**
 - PHP Version   **7.3.14**
Laravel Version | 5.5.48

**Is your feature request related to a problem? Please describe.**

Hi, 
Is there a way to use Electronic Signature Capture Pad with Snipe-IT to sign checked in assets?
We have Topaz T-S460-HSB-R USB Electronic Signature Capture Pad and tried to use it but it doesn't work. We installed SigWeb Browser SDK plugin https://www.topazsystems.com/sigweb.html.
The device is recognized as Human Interface device.

**Describe the solution you'd like**
**We would like to use Topaz T-S460-HSB-R USB Electronic Signature Capture Pad to sign assets.** 

**Describe alternatives you've considered**

**Additional context**

**Comment by brewerc1** [comment]
[/issues/7817] describes a workflow that seems relevant to this request.

**Comment by yanagha** [comment]
We just need to sign with Electronic Signature Capture Pad which is not working in the signature area. 
We are also waiting for the solution of the issue described here: [Feature Request - Show users their unaccepted assets #5265][https://github.com/snipe/snipe-it/issues/5265](url)

**Comment by yanagha** [comment]
Hi, 
Can you please help us to integrate this https://www.topazsystems.com/web.html ?
Do you have paid service to integrate this feature?


<blockquote><img src="images/web-favicon.ico?crc=116343212" width="48" align="right"><div><strong><a href="https://www.topazsystems.com/web.html">Web Demos and Source Code | Topaz Systems Inc.</a></strong></div><div>SigPlus electronic signature software tools, applications, plug-ins, utilities, demos, and support bundled at no extra charge. Software for electronic signature pads.</div></blockquote>

**Comment by cgcb** [comment]
Still relevant

**Comment by yanagha** [comment]
Hi,

Yes, it still relevant. Please do not close the request.

Regards,
Yana

**Comment by Relix360** [comment]
+1

**Comment by Relix360** [comment]
Yes

**Comment by yanagha** [comment]
Yes, it 's still important.

**Comment by mni1000** [comment]
This is still relevant, are there any updates to this?

**Comment by snipe** [comment]
No movement. We don’t have that device, so we’d have no way to test it.

**Comment by Artapel** [comment]
Bump

Id like to use a Wacom LCD Signature Pad STU-430-SP-SET for signatures.
