### ISSUE TITLE
[Question] Expected Checkin email template?

### ISSUE THREAD

**Issue by maxlehot1234** [grokability/snipe-it#7806]
Hi,

I try to create an email template that will send an email when someone forgot to give us the asset he have, but its impossible to do...

I try to edit this file:
/var/www/snipe-it/resources/views/vendor/notifications/email.blade.php
But it refer to this filen which prevent me to use html and css...
/var/www/snipe-it/app/Notifications/ExpectedCheckinNotification.php

but its REALLY HARD and impossible to do instead of the cjecking and checkout assets for example...

Why not create a simple email template folder where all files are  in the same folder instead of split them up everywhere?
Why not create something that allow us to edit the email template directly from the admin panel?
OR
Why not allow us to edit email tempalte easily on the server instead of create variable that refer to another file when this file refer to another one, etc...

I know its a lot of things, but I am just wondering why we need to edit all of these things with all of these variables from too many files :(

Thanks again if you can reply to this thing, since it was really annoying and prevent our company to make Snipe-IT ready for everyone...
I need to translate everything in french and I also need to use html and css to fit emails to our company guidelines..

Thanks a lot.

**Comment by snipe** [comment]
Unfortunately, that's just not have Laravel works and it would take a lot of effort to monkey patch it so that it worked that way. If you're interesting in checking out how Notifications work in Laravel, I'd suggest checking the documentation.

**Comment by maxlehot1234** [comment]
Ok than why I can edit all other email templates without any problems?

I refer to these things:
https://github.com/snipe/snipe-it/tree/master/resources/views/notifications/markdown

I edit all of them with table, html, css to make a beautiful email template that looks like this with fully responsive support:
![image](https://user-images.githubusercontent.com/5159244/74197240-15ba6d80-4c2d-11ea-9a8a-2dd8583dda6e.png)
Which is MUCH better than the default one.

But why I can't do the same thing for the Expected checkin email template?  @snipe 

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by maxlehot1234** [comment]
@snipe ? ^^

**Comment by maxlehot1234** [comment]
@snipe , why you close this without replying to it after?

Other email templates use laravel too and they are really easy to deal with...

That's so sad that you doesn't do the same thing for the expectedchecking email thing...

**Comment by maxlehot1234** [comment]
@snipe ? :( Anything?

Since its possible with all other emails notifications, whyc not make the expired checkins emails notifications the same as others?

**Comment by Mckovsky** [comment]
@maxlehot1234 - unfortunately I do not have a solution for your issue, but would like to say "big thanks" for providing path for files actually used to send notifications. Could you tell me where did you edit CSS for these files? Thank you!

**Comment by maxlehot1234** [comment]
> @maxlehot1234 - unfortunately I do not have a solution for your issue, but would like to say "big thanks" for providing path for files actually used to send notifications. Could you tell me where did you edit CSS for these files? Thank you!

Our snipeit server was down for 2 months now, bcause of a bug in HyperV :P We need to work on it when we have more times. Since with VPN requests and everything, its impossible to work on snipeit again (at least for now).

But for the CSS, I implement it directly into the same file.
I add <style> things at the top of the file.
I add a div where I put HTML table in it with some css that are linked to the <style> and I also put the markdown in the html tables.


Its really hard to do, since its the only way for now and the dev wont want to change this or make it little bit more easier for us.

I do my best to make it looks great and it support responsive, but for multiple reasons, I will not share the template for obvious reasons.

Hope @snipe can do something for the expected checkin thing instead of close this ticket without anything...
