### ISSUE TITLE
Wrong permission in ManufacturersController:edit() and update()

### ISSUE THREAD

**Issue by iljalukin** [grokability/snipe-it#7811]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Granting edit permission to manufacturers does not apply

**To Reproduce**
1. Go to People, choose an existing person without global super user rights
2. Click on edit, choose Permissions and grant Manufacturers->Edit permission
3. Go to Settings->Manufacturers and edit one
4. See error 403

**Expected behavior**
A person with granted edit permission to manufacturers should be able to edit them.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: 4.8.0 
 - OS: Debian 10
 - Web Server: nginx
 - PHP Version: 7.2 

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Firefix
 - Version 72

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
The update/edit methods in app/Http/Controllers/ManufacturersController.php contain $this->authorize('edit', Manufacturer::class);
If I change the permission to update instead of edit ($this->authorize('update', Manufacturer::class);), there is no 403 error and everything works as expected.

**Comment by heikoboehme** [comment]
is this fixed now a new release? I have the same issue .. Verison 4.8.0
