### ISSUE TITLE
licenses not showing up

### ISSUE THREAD

**Issue by lravelo** [grokability/snipe-it#7812]
#### Expected Behavior (or desired behavior if a feature request)

I except to see all of my licenses when clicking on the Licenses link

-----

#### Actual Behavior

page will just stay on "Loading... please wait..." and then after the php max execution timeout it just says "No matching records found"

The errors that show up in the laravel.log is the following:

`[2020-02-12 11:33:58] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 300 seconds exceeded in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Collection.php:892
Stack trace:
#0 {main}
[2020-02-12 11:33:58] production.ERROR: Maximum execution time of 300 seconds exceeded {"userId":1,"email":"root@amcs-mgm-s02p.hwl-family.net","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 300 seconds exceeded at /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Collection.php:892)
[stacktrace]
#0 {main}
"}
`

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **upgrade**
- Version of Snipe-IT you're running - **v4.8.0 - build 4186 (master)**
- Version of PHP you're running - **v7.2.24-0ubuntu0.18.04.2**
- Version of MySQL/MariaDB you're running -  **Ver 14.14 Distrib 5.7.29, for Linux (x86_64)**
- What OS and web server you're running Snipe-IT on - **Ubuntu 18.04.3 LTS, Apache/2.4.29** 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - **error included above**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **licenses link**
- If a stacktrace is provided in the error, include that too. - **also included above**
- Any errors that appear in your browser's error console. - **error 500 (internal server error) for url: ttp://snipe-it.local/api/v1/licenses?sort=name&order=asc&offset=0&limit=200**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - **not reproducible in demo**
- Include any additional information you can find in `storage/logs` and your webserver's logs. - **error included above**
- Include what you've done so far in the installation, and if you got any error messages along the way. - **tried to increase the max_execution_time value to 300 but error persisted (I have 40k+ licenses listed here).**
- Indicate whether or not you've manually edited any data directly in the database - **no editing done to database**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by lravelo** [comment]
Confirming that dropping into a mysql prompt and running `select * from licenses;` returns all of my licenses so the data does exist.

**Comment by JoKneeMo** [comment]
Have you tried updating your composer and running the upgrade again?

Update composer by running `php composer.phar self-update`.
The run the upgrade script again `php upgrade.php`.

#7940

**Comment by hnsaballa** [comment]
Software licenses still not showing up after saving the data. Version v6.0.14 - build 9038 (master)
