### ISSUE TITLE
qr code not updating URL after .env updated

### ISSUE THREAD

**Issue by apautz22** [grokability/snipe-it#7813]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
URL embeded in QR code is not updating when it is changed in .env
Old URL: http://wbestas
New URL: http://wbestas.office.company.com

**To Reproduce**
I'm trying to update the URL embedded in the QR code for the asset labels. I have updated the URL in .env and httpd files, restarted the server, deleted the saved images in /public/uploads/barcodes/, ran the following commands
composer dump-autoload
composer clear-compiled
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear
Even with repeating all this multiple times to make sure I wasn't missing anything it is still showing the old URL instead of the new URL.

**Expected behavior**
update necessary files with the new URL, run the clear cache command, and it works.

**Screenshots**
I ran a grep for all the files with the URL and they are all updated
bin/apache/apache2.4.39/conf/extra/httpd-vhosts.conf:   ServerName http://wbestas.office.company.com
bin/apache/apache2.4.39/conf/httpd.conf:#       ServerName "http://wbestas.office.company.com"
wampmanager.ini:Type: item; Caption: "http://wbestas.office.company.com:"; Action: multi; Actions: server_http://wbestas.office.company.com:; Glyph: 20
wampmanager.ini:[server_http://wbestas.office.company.com:]
www/snipe-it/.env:APP_URL="http://WBESTAS.office.company.com"

**Server (please complete the following information):**
 - Snipe-IT Version: v4.8.0 - build 4186
 - OS: Windows
 - Web Server: Apache
 - PHP Version: 7.3.5

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 79.0.3945.117

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android
 - Browser Chrome

**Error Messages**
No error messages

**Additional context**
I have tried this with our regular install and did a fresh install and it still had the same effect.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Remove the files from the `public/uploads/barcodes` directory.

**Comment by apautz22** [comment]
I had already done that as per my post.
That being said, I did manage to find the issue. I removed the files in `storage\framework\sessions` and restarted everything and it worked as expected.
Thanks
