### ISSUE TITLE
Synology LDAP + Snipe-IT

### ISSUE THREAD

**Issue by thebiggeek** [grokability/snipe-it#7823]
HI

I have read the past two discussions, but they were using Synology as an AD Server. I am using Synology as an LDAP Server, and am unable to authenticate even as a test login

Here are the Settings I am using

uid=root,cn=users,dc=ldap,dc=mycompany,dc=com
I have SSL/TLS - which other Branch Synology Use - so I have enabled that. Tested with disabling this, and enabling, it using ldaps://ldap.ip.address or ldap://ldap.ip.address and even ldap://ldap.ip.address:389

But to no avail. If someone has integrated LDAP + Synology + Snipe IT - Please do let me know how you managed that?

**Comment by gilesytheking** [comment]
the easiest way to set this up is by using the synology DDNS. You can setup the synology  DDNS by navigating to control Panel -> external access -> DDNS. You can use other DDNS providers if you wish, but the synology one is easy to setup.

Make sure your LDAP settings are configured correctly (LDAP Server -> Settings) and you have specified a FQDN and password.

The LDAP ports (389 & 636) need to be added to your router configuration (Control Panel -> External Access -> Router Configuration). Depending on your router you may need to open the ports manually from within your router control panel.
You can check if your ports are open by visitng this site - https://www.canyouseeme.org/

Once you have configured LDAP on your synology nas here are the setting to use within Snipe IT

LDAP Integration: Enabled
LDAP Password Sync: YES
LDAP Server: ldaps://**YOURDDNS**.synology.me:636 (ldap:// and port 389 if you dont have SSL)
LDAP Bind Username: uid=root,cn=users,dc=**YOURFQDN**,dc=**TLD**
LDAP Bind Password: Your main LDAP Password
Base Bind DN: cn=users,dc=**YOURFQDN**,dc=**TLD**
LDAP Filter: &(cn=*)
Username Field: uid
Last Name: bd
LDAP First Name: cn
LDAP Authentication query: uid=
LDAP Version: 3
LDAP Active Flag: active
LDAP Email: mail


<blockquote><div><strong><a href="https://www.canyouseeme.org/">Open Port Check Tool -- Verify Port Forwarding on Your Router</a></strong></div><div>A free open port check tool used to detect open ports on your connection. Test if port forwarding is correctly setup or if your port is being blocked by your firewall or ISP.</div></blockquote>

**Comment by thebiggeek** [comment]
This did not work for me. I have tried all this. For me the LDAP Server is local, so I have even tried with the IP. The TEST LDAP itself Fails with the Line "Could not bind to LDAP: Invalid credentials"

**Comment by gilesytheking** [comment]
My LDAP (synology drive) is also local, my snipe IT is hosted on my webserver. The synology DDNS allows you to connect to your synology nas from outside your local network. Is your snipe IT install also local?

If you are getting "Could not bind to LDAP: Invalid credentials" error, then I would double check your LDAP Bind Username & LDAP Bind Password.

![snipe-ldap](https://user-images.githubusercontent.com/15634270/75228098-62fb1b00-57a7-11ea-9881-83497c72e7c2.png)

Also if you have the fIrewall enabled on your synology NAS, you will need to allow connections for the LDAP ports. This maybe be blocking your connection and causing the athentication to fail. You can configure the firewall to allow specific IP addresses (Local or external).

Control Panel -> Security -> Firewall -> Firewall Profile -> Edit Rules -> Create/Edit to allow LDAP ports

You may have also blocked your IP depending on your Synology Firewall rules. To check your IP has not been blocked check: Control Panel -> Security -> Account -> Allow/Block LIst

**Comment by thebiggeek** [comment]
Thank you so much for your Reply. This did not make sense, since other Servers are able to access the LDAP Servers, and even Branch Office Computers are able to access LDAP, but I investigated it time and again, and checked settings. 

The Settings that worked for me for the LDAP_USER_FILTER=(&(uid=${user}))

Also I think I stumbled across the BUG. Till I did not disable LDAP and add it again, it was continually giving me errors of binding, even after making changes. Now After I went and Disabled LDAP, then Enabled it again, and entered the password again - It started working. 

Thank you so much for your help. Though you should check if this is a bug somewhere.
<img width="932" alt="ldap-assets" src="https://user-images.githubusercontent.com/24227623/75232697-aec8b700-57dd-11ea-8043-5174dc594785.png">
