### ISSUE TITLE
Feature Request: Increase licence seat count value

### ISSUE THREAD

**Issue by Jaspotn0612** [grokability/snipe-it#7824]
**Server (please complete the following information):**
 - Snipe-IT Version 4.7.7 build 4160
 - PHP Version 7.2.24

**Is your feature request related to a problem? Please describe.**
I am beginning to enter the licence seat count for various software packages and I have found that there is a limit of 999. A software package that may cover more seats would then have to be split down to groups of 999, which may lead to confusion in terms of financial auditing.

**Describe the solution you'd like**
Increase the licence seat count to a higher value

**Describe alternatives you've considered**
Entering the software package in multiple groups of 999 however this can lead to confusion when doing financial auditing.

**Comment by k-korn** [comment]
+1 on this request.
Commit 0290257734c0c9364aa6350dfe858a47f2b79f95 looks weird for someone from organisation of 1000+ employees

**Comment by k-korn** [comment]
Yes, it is still relevant - and will be until fixed.

**Comment by Jaspotn0612** [comment]
Just wondering if this is planned to be reverted/fixed at some point?

**Comment by haircut** [comment]
Yes, this is a very odd limitation. Any word on a fix?

**Comment by Jaspotn0612** [comment]
Yes, still relevant

**Comment by smurf3l3v3n** [comment]
I am also having this issue, specifically because I have a large organisation and some of my licences require more than 999 seats in order to allocate to the assets I have.

**Comment by m4zl** [comment]
Still relevant as we are also facing this issue. We just helped us with editing the License.php and increased the "seats" value to 9999. However with every update we need to change this again. 

Would be nice if this gets fixed in the near future.

**Comment by deflower** [comment]
My organization is looking into migrating to SniptIT. However, this license limitation is a deal breaker due to the size and number of assets we have. Would love to see this limitation either increased significantly or removed entirely.

**Comment by ghost** [comment]
+1, would be helpful to not have to break up total licenses by an arbitrary number and create multiple entries when one would do.

**Comment by Jaspotn0612** [comment]
Giving this a bump as it's been an issue for over a year.
Yes I know it's not the only one that's open a while, however, it seems a relatively small variable change.
Was there a need for such a drastic drop from the previous value of 1,000,000 to 999? The commit referenced it was to prevent latency but why was that value chosen?

**Comment by robbysibrahim** [comment]
+1 Just started using this and we have more than 1000 employees.

I also think this closed issue was a great idea: https://github.com/snipe/snipe-it/issues/220

**Comment by snipe** [comment]
The issue is that for unlimited licenses, people would just put in 999999 and create a buttload of licenses that they didn't actually need, making the licenses page really slow.

**Comment by k-korn** [comment]
> The issue is that for unlimited licenses, people would just put in 999999 and create a buttload of licenses that they didn't actually need, making the licenses page really slow.

Maybe, don't create full amount of unused seats on license creation, and just add DB rows as needed when licenses seats are occupied? Such approach would allow truly unlimited seats

**Comment by exula** [comment]
@snipe would you be open to some sort of configurable maximum amount of licenses? We ran into this 999 limit in our implementation with some software in our computer labs. (We actually needed 1000 lol)

I'm thinking a setting in the general settings page might work. I understand there would be some things to consider when that maximum gets **decreased** That could perhaps be caught in some sort of validation in the Settings page.

The validation on the settings might be something like.

- Fail validation If there are any licenses with a license count greater than the new proposed maximum.

Would you mind if I take a crack at this?

No promises that I won't rage quit and give up lol

**Comment by exula** [comment]
@snipe would you be open to some sort of configurable maximum amount of licenses? We ran into this 999 limit in our implementation with some software in our computer labs. (We actually needed 1000 lol)

I'm thinking a setting in the general settings page might work. I understand there would be some things to consider when that maximum gets **decreased** That could perhaps be caught in some sort of validation in the Settings page.

The validation on the settings might be something like.

- Fail validation If there are any licenses with a license count greater than the new proposed maximum.

Would you mind if I take a crack at this?

No promises that I won't rage quit and give up lol

**Comment by uberbrady** [comment]
The code part is quite easy - on a local development instance try to crank it up higher, it’ll work. I think the limit is set at the model level for License or LicenseSeat.

But then, every query you run will grind to a crawl. Pages will time out. Stuff will absolutely fail, badly.

I suspect this is probably either a database index problem, or maybe some kind of 1001-queries-problem (e.g. not doing a join when you actually should). It’s possible that it’s something worse, but I’m not convinced of that (yet).

If you can solve problem #2, we’d take that PR in a heartbeat. I tried it myself and wasn’t able to find it, but I’ll admit I didn’t spend too much time on it myself. Hopefully you’ll have better luck?

**Comment by k-korn** [comment]
> The code part is quite easy - on a local development instance try to crank it up higher, it’ll work. I think the limit is set at the model level for License or LicenseSeat.
> 
> But then, every query you run will grind to a crawl. Pages will time out. Stuff will absolutely fail, badly.
> 
> I suspect this is probably either a database index problem, or maybe some kind of 1001-queries-problem (e.g. not doing a join when you actually should). It’s possible that it’s something worse, but I’m not convinced of that (yet).
> 
> If you can solve problem #2, we’d take that PR in a heartbeat. I tried it myself and wasn’t able to find it, but I’ll admit I didn’t spend too much time on it myself. Hopefully you’ll have better luck?

That is strange, locally we do have a SnipeIT instance with 60+ licenses, 15000 seats and few licenses with 1500-2000 seats each - and everything runs great off a smallish MySQL instance (3Gb RAM, 2xCPU) and similarly sized web server.

Modern databases do not even consider a "medium data size" anything that has less than a million rows. 
That includes even MySQL

**Comment by uberbrady** [comment]
Well, if memory serves I set it to 10,000 and that’s what I saw. Again, though, I didn’t really poke around it too much.

**Comment by exula** [comment]
@uberbrady I think I found a few smoking guns.

1. There is a missing index on the license_seats table for license_id which is making lookups slow
2. In the Controllers\Api\LicensesController.php file it's trying to hydrate all of the freeSeats Eloquent models, but the JSON response never uses those relationships, just the count. So that was eating up tons of memory and causing slow pages loads

There is also another possible improvement in the License.php model when it creates the needed LicenseSeats, but I'm not happy with my 'hack' yet.

I'll pack this all up in a PR and have someone take a look at it that's a bit smarter than me,

**Comment by uberbrady** [comment]
@exula - 

Number one sounds like a no-brainer fix and we would take in an absolute heartbeat, thank you!

Number two I just saw a few weeks ago in another JSON response we have - sometimes I think we "over-join" to try and avoid the 1001 queries problem, and this certainly sounds like what I've seen before.

We'd take a fix for those two in a heartbeat. Another change we've been pondering on Licenses is for how we'd handle "unlimited" license seats, but I think that's out of scope for this set of fixes. These will help a lot, and we are eagerly awaiting your PR!
