### ISSUE TITLE
Auto renew checkbox for licenses

### ISSUE THREAD

**Issue by nickjmv** [grokability/snipe-it#7840]
It would come in handy if there was a button like 'Auto renewed' in combination with a 'Monthly or 'Yearly' button next to it so the expiry date of a license will be updated automatically.

**Comment by nickjannes101** [comment]
Yes this is still in demand by a lot of users I think

**Comment by nickjmv** [comment]
If no one else needs this I guess it can be closed :(

**Comment by tgeske88** [comment]
I'd love to have this feature implemented, any chance to get this back on the dev's radar? I tried to create a custom field/fieldset and quickly realized these cannot be applied to licenses and only to assets.
