### ISSUE TITLE
API push on asset status change

### ISSUE THREAD

**Issue by rovingrambler** [grokability/snipe-it#7844]
#### Expected Behavior (or desired behavior if a feature request)
Is is possible to have Snipe-it push to an api or run a script when a asset's status is changed?

-----

#### Actual Behavior

I can push a notification to a Slack channel. 
I would like to inform another system that the devices in question is deploy-able or not.

Can a curl push or similar be triggered? 
If not this is a feature request

**Comment by ffuentes** [comment]
Hello,
maybe you can do an *outgoing* webhook in slack.
