### ISSUE TITLE
Asset Import Functionality Broken

### ISSUE THREAD

**Issue by zacharysandberg** [grokability/snipe-it#7845]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
_When attempting to import a .csv file, I receive a blue "processing" bar that never completes.  When attempting to delete a .csv file that has already been uploaded, the process fails with a misaligned red bar at the top of the screen that displays no error text, just an (X) to close the bar._

**To Reproduce**
1. _Create a simple .csv file or reimport an exported asset .csv with new values_
2. _Fill out the appropriate field categories_
3. _Click "Import"_
4. _See blue "processing" bar_

**Expected behavior**
_Expected behavior is that new fields from the .csv file are imported into the SnipeIT database._

**Screenshots**
_Import that never finishes:_

![snipeit-1](https://user-images.githubusercontent.com/61425417/75189711-6396a180-5714-11ea-8ef6-0c04db263f05.png)

_Delete that doesn't delete:_

![snipeit-2](https://user-images.githubusercontent.com/61425417/75189714-642f3800-5714-11ea-8452-44829f8b7bc6.png)

**Server (please complete the following information):**
 - Snipe-IT Version: _4.8_
 - OS: _Debian 9_
 - Web Server: _Apache 2.4.25_
 - PHP Version: _7.4_

**Desktop (please complete the following information):**
 - OS: _Kubuntu 19.04 & Windows 10_
 - Browser: _Firefox, Edge_
 - Version: _Firefox 68.4.2esr, Edge 41.16299_

**Smartphone (please complete the following information):**
_None_

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
_No debug errors related to importing_

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Demo has import functionality disabled
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
_Fresh Install_

- What OS and web server you're running Snipe-IT on
_Debain 9, Apache_

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
_Manual_

- Include what you've done so far in the installation, and if you got any error messages along the way.
_Complete install, everything aside from import works_

- Indicate whether or not you've manually edited any data directly in the database
_No manual edits_

Files uploaded into importer exist in the storage/private_uploads/imports directory and are renamed without .csv file extension through import process.

![snipeit-3](https://user-images.githubusercontent.com/61425417/75190669-65616480-5716-11ea-9106-26609beab69e.png)

**Comment by zacharysandberg** [comment]
**Update:**  Rolling back to php7.3 seemed to resolve the importer issue, however I am still unable to delete imports that have already been uploaded.  The blank red bar at the top of the page persists.

**Comment by chshanoo** [comment]
I had the same issue on localhost. Tried multiple solutions but what worked for me was a small change in .env file. In Outgoing Mail section
change "MAIL_DRIVER=smtp"  to "MAIL_DRIVER=log"

Import worked after that.
