### ISSUE TITLE
XLSX file upload not permitted while XLS is

### ISSUE THREAD

**Issue by pilsetnieks** [grokability/snipe-it#7850]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.8.0 - build 4186 (master)
 - OS: Debian
 - Web Server: nginx
 - PHP Version: 7.4

**Is your feature request related to a problem? Please describe.**
XLSX files cannot be uploaded as attachments to assets. This seems odd, considering that XLS files are permitted just fine.

**Describe the solution you'd like**
XLSX file upload permitted

**Describe alternatives you've considered**

**Additional context**

**Comment by pilsetnieks** [comment]
v.4.9.0 - still cannot upload XLSX files.

**Comment by viclou** [comment]
still relevant

**Comment by ncareau** [comment]
Still relevant, still happening in 4.9.3.
