### ISSUE TITLE
Export to Excel Turkish character problems

### ISSUE THREAD

**Issue by samigoncu** [grokability/snipe-it#7851]
Hello,
when I want to get the custom( entire inventory) list in excel format, I have a Turkish character problem
or why I can't export all list in asset ?

Thank you

Snipe-IT version | v4.8.0  build 4186 (g893454dca)
-- | --
PHP version | 7.2.24-0ubuntu0.18.04.3
Laravel version | 5.5.48

**Comment by muratbulat** [comment]
Hi Sami,
Your can try change  os and browser language to turkish. Or region settins. Its worked for me.
Regards

**Comment by shenol** [comment]
I'm having this problem too. I am using the current version and my browser is Turkish.
