### ISSUE TITLE
Is Installing On Shared Host Possible?

### ISSUE THREAD

**Issue by khat17** [grokability/snipe-it#7853]
Good day everyone. Hopefully the question above is clear enough. I'm using shared hosting - not my own server - so I can't seem to install everything required. Currently have this issue as a result.

autoload.php on line 17

Which lead to this: https://github.com/snipe/snipe-it/issues/6199

Which then lead me back to the installation document: https://snipe-it.readme.io/docs/install-dependencies

From what I'm seeing I need composer to continue - or find some way to generate the app key and place it in the .env file. 

I'd like to know if anyone has successfully installed on shared hosting and what's the possible workaround? Are there any other instructions that I missed? Thanks in advance.

I'm leaving the instructions below - I may come back to it and edit or provide additional information as required. Let me paste the errors exactly as they appeared.

Warning: require(/home/user/public_html/snipe/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/user/public_html/snipe/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/home/user/public_html/snipe/bootstrap/../vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /home/user/public_html/snipe/bootstrap/autoload.php on line 17

Again - thanks in advance.

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by khat17** [comment]
So. After going through all of the Softaculous links from the hosting provider, I found Snipe-It in the list. Which makes this a bit weird for me now - using that it installs and I can use it, but I'd like to figure out how to do this install manually and document the process for others to see. So there's no urgency on this anymore, so whenever the experts here have time we can try and get it sorted. Once done I'll just add it to my pages with instructions on how to get it done.

**Comment by RB14060** [comment]
You'll need SSH access to the server to be able to install it. Part of the install steps on the page that you linked is to run `composer install --no-dev --prefer-source`. This installs all of the needed dependencies which will eliminate the file not found error you're getting. Once you do that then you can use the Artisan command to automatically generate and insert the app_key.
