### ISSUE TITLE
Unable to connect to API via Curl or Jira Plugin

### ISSUE THREAD

**Issue by migarol** [grokability/snipe-it#7854]
#### Expected Behavior (or desired behavior if a feature request)
I want to connect to my SnipeIT instance via API

(what you expect to happen goes here)
I would like to request data from the SnipeIT api
-----

#### Actual Behavior
I installed a fresh Snipe-IT installation version 4.8.0 and did a:

curl -X GET \
  http://inventory.quo.services/api/v1/hardware \
  -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImZkZTk0M2IzMTkxZWFhNDIwYjEwNjExNGU2OWQzMmNhNmM2Nzk5Yzc4NzRlOWNkNmZlNzA3MjhlZTJkNWMzZTRmYTE0YThlODM5YTc0MDlkIn0.eyJhdWQiOiIxIiwianRpIjoiZmRlOTQzYjMxOTFlYWE0MjBiMTA2MTE0ZTY5ZDMyY2E2YzY3OTljNzg3NGU5Y2Q2ZmU3MDcyOGVlMmQ1YzNlNGZhMTRhOGU4MzlhNzQwOWQiLCJpYXQiOjE1ODI3NzAwMjYsIm5iZiI6MTU4Mjc3MDAyNiwiZXhwIjoxNjE0MzkyNDI2LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.sVDVrGkMOlPihOF5h3nPjIvGS7dq2tS7Jcgcr2jGoqvCgeQDmGHc-UONzJOSyQXxc9IL3GdnW1eXvhioNHqasHgVP2fv8X8GvYf7WpLzIpWZnlaMdJfIGq7Wnn3lmK_5j1G1OJ7lI0o-HIZsuShuQ6LMr1Jfnj9-DgjjMMarXtehohctgH77SmVhotKHBdkMkqa_B1jkeogLFQBYayE8rIEHs8lgiCAm8CF4cv66rcH77C7sBzlVKzrXb8fMCGUT574Rq6aN_AxhAHdFoyjY_4GoouHfVP2qJf_wpaPFHGasZ3eukmKycMWfaQ4WmaGLHda1q9aPWor57-4SwBg9JFpXbYSC6bLgSCc6bJ1GmOrbcTb3vTtvvKfb85ei7fNfzpEveBplhFMwSjCWdfvt0KVAoHIn4C8VDIf56E7TcmbW1ysX01lTo3CFZqiNf4DIKK0PFt8D05nV90NENaqUOw0vUO2BmDfexqCGXnh8nrjQqh8h3IVE6ogM3kpQnbtZVQugHQtg73qm4ahplqDbW4A-u1z2goEVcsRsyzDGMJ5u7dyItaWqrAab4llSSIKXfP87pcIR8LDz40S7gk9ZqTtzSQatkugQV-tCAdsyelbs0V-khds9WmcZh90RMVD6opr8l5cMMInejRG2klSPAbex6izqhpgP8gt7wZcgpyI" \
  -H "Content-Type: application/json" \

(what actually happens goes here)
This is what actually happens:

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='http://inventory.quo.services/login'" />

        <title>Redirecting to http://inventory.quo.services/login</title>
    </head>
    <body>
        Redirecting to <a href="http://inventory.quo.services/login">http://inventory.quo.services/login</a>.
    </body>

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running 4.8.0
- Version of PHP you're running v7.2.24
- Version of MySQL/MariaDB you're running 5.7.29
- What OS and web server you're running Snipe-IT on Ubuntu 18.04 and Apache/2.4.29 (Ubuntu)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh and also tried manual but same behaviour
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error No errors
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error N/A
- If a stacktrace is provided in the error, include that too.  N/A
- Any errors that appear in your browser's error console.  N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs.  N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. No error logs even in debug mode
- Indicate whether or not you've manually edited any data directly in the database
NO
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by migarol** [comment]
Issue solved as per fix on issue: https://github.com/snipe/snipe-it/issues/6595

Ok, we found it.
we had:
AllowOverride None
Options None

instead of

AllowOverride All
Options -Indexes

in our Apache config. Now everything works great. You can close this issue :)

**Comment by pbrink231** [comment]
I would suggest removing your token from your post and generate a new one
since that is a public front end site.
