### ISSUE TITLE
More images

### ISSUE THREAD

**Issue by skhell** [grokability/snipe-it#7860]
Will be possible to have more images for single assets?
Also will be a great idea to let upload an image for maintenance, for example if I do a maintenance on a specific asset I can add an image on it to allow a manager for example review my job for a specific maintenance, for example if I have replaced a fan or a screw in a piece of hardware it will be great to let manager see a photo of the job done for the maintenance.

Thanks

**Comment by Jaspotn0612** [comment]
Just to add to this, another example where it might come in handy is with network equipment, there are some instances where having the front of the device is handy but having an additional image of the back of a device is also useful.

**Comment by ahmetshen-us** [comment]
Can anyone let us know if someone is working on this feature? If not I am willing to work on this feature.

**Comment by skhell** [comment]
I think nobody is working on this, can anyone let us know? Thank you very much
