### ISSUE TITLE
LDAP Sync related

### ISSUE THREAD

**Issue by tonyjoseph-sfo** [grokability/snipe-it#7863]
the location attribute gets replaced with default location after an ldap sync.
all the work done on updating the users info about the location is gone.
what can be done to just update/create the newly created users in AD.

**Comment by Mynty100** [comment]
Possible Band-aid solution.
Before running LDAP sync. Export user info with all the fields you want to re-import via .csv

Step 1) Export correctly set user data.
Step 2) LDAP Sync.
Step 3) Import user data with locations etc set.
Step 4) Update the new sync'd users.

**Note: Recommend taking a snapshot or at least a backup of the server before attempting this.

Regards,
Mynty.
