### ISSUE TITLE
Electricity Audit for Assets

### ISSUE THREAD

**Issue by derToWa** [grokability/snipe-it#7865]
First of all thanks for this very beautiful asset management.

**Is your feature request related to a problem? Please describe.**
In Germany we've audits for every asset with power plug.
Our electrician goes round the company every few years and attaches test labels to the devices.
We've to generate lists for audits so the auditor knows that all devices are checked.

DGUV V3 Regulation is the keyword. :(

**Describe the solution you'd like**
It would be very nice if there is an option to set the next date (month & year) for check.
Assets for that audit are visible on "Due for Audit" and "Overdue for Audit".
All assets get an QR-Code so you can simply complete audit.

**Additional context**
There are different time periods for moveable and fixed devices.
Also the check period is only for productive devices, replacements will not be tested.

**Comment by ahmetshen-us** [comment]
I see the point, it would be nice to set a default date for the next audit by default and update it if necessary. 

When auditing the next audit date is today by default which does not really work I guess.


@derToWa do you think just setting the next audit date to say 2 months from today will work? Or would a setting in settings for next audit be better?

**Comment by derToWa** [comment]
Thanks for comment.
This is a little bit complicated, what else if you have so stupid regulations.

At our company we instuct an external electrican to do that audit.
We've the following time periods:
- IT-Hardware (TFT, PC, printer, speaker, multiple sockets...) = every 4 years (fixed devices)
- Production-Hardware (drilling machine or angle grinder for example) = every 2 years (moveable devices)

Now you buy a new IT-Device it will be tested on the next audit (but there is only a approval for the manufacturer warranty period).
If your auditor/electrican reports problems on testing or auditing your time periods will be set shorter. :(

So I think it's fine to set it global but after an audit there are a few options for an device:
- everything is fine
- have to be repaired (using blocked)
- will be scrapped (using blocked)

**Comment by derToWa** [comment]
Hello again,
is there any option to set an audit date now?

I have started a new attempt but I don't know how to use integrated audit function.

My thought about an regular audit period has not gone down so well. :(
