### ISSUE TITLE
LDAP Users can change/reset their passwords

### ISSUE THREAD

**Issue by dampfklon** [grokability/snipe-it#7866]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A user synced via LDAP can successfully request a new password. 

**To Reproduce**
1. Go to Login Page
2. Click on I forgot my password
3. Enter Mail Address
4. Click on reset link in received mail

**Expected behavior**
After step 3 there may should be a warning that the password is managed via LDAP and no mail with a reset link.
An other solution would be a config to disable password reset global.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.8.0 - build 4186 (master)
 - OS: Official Docker Image
 - Web Server: -
 - PHP Version: -

**Error Messages**
- None

**Additional context**
- Change password via the User menu once logged in should also be hidden on users managed via LDAP
- There were multiple similar Issues but never discussed the possibility to disable the functionality because it confuses not so tech savy staff

**Comment by dampfklon** [comment]
sure

**Comment by mandelbrotmedia** [comment]
i'm also interessted in disabling password change.
Any news?

**Comment by dampfklon** [comment]
This is still an issue

**Comment by chadlx** [comment]
This is still an issue

**Comment by thoschi** [comment]
It would of course be much better to have the option to show/hide the password-reset-link (should be a quite easy task). But as a temporary workaround this custom CSS (set under "Branding") might help with many browsers:

`.login-page div.col-md-12:nth-child(2) > a:nth-child(1) {display: none;}`

Tested with Snipe-It version 6.2.4 on Firefox/FF-mobile.

**Comment by MetalSpike** [comment]
> It would of course be much better to have the option to show/hide the password-reset-link (should be a quite easy task). But as a temporary workaround this custom CSS (set under "Branding") might help with many browsers:
> 
> `.login-page div.col-md-12:nth-child(2) > a:nth-child(1) {display: none;}`
> 
> Tested with Snipe-It version 6.2.4 on Firefox/FF-mobile.

[thoschi](https://github.com/thoschi), thank you for taking the time to post that.  There really ought to be a toggle inside the Admin Settings to disable that.

Most companies, even the smallest, have access to internal HelpDesks of all types including open source ones like osTicket.  As an admin, I would rather password resets be handled by a helpdesk to have that metric in one place.
