### ISSUE TITLE
Uploading files to component/accessories section

### ISSUE THREAD

**Issue by 02ms05** [grokability/snipe-it#7868]
**Server (please complete the following information):**
 - Snipe-IT Version v.4.8.0 
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version: 7.2.24

**Is your feature request related to a problem? Please describe.**
It would be great if there was a possibility to upload files to components. For example, we have a lot of Samsung 970 SSD's which is regularly used to upgrade servers and workstations as well, so it's a component which is tied to another asset, which is fine. But we also need to keep track of them, have valid receipt and warranty attached somewhere next to it, if it's possible. 

**Describe the solution you'd like**
Adding a feature File>upload to components, accessories and consumables as there is on assets,

**Comment by jonahbohlmann** [comment]
Really needed. :)

**Comment by gitkooo1247** [comment]
would be a very useful option

**Comment by caguiar** [comment]
It seems that uploading files to consumables and accessories is possible in version v6.0.14, but only if you have Super User permissions. It would be more useful if it could also be possible with Admin permissions.
