### ISSUE TITLE
Why is EOL referenced in documentation but does not send email report

### ISSUE THREAD

**Issue by EpicallyJess** [grokability/snipe-it#7875]
On https://snipe-it.readme.io/docs/configuring-alerts-backups there is a reference to EOL

If you wish to be reminded via email when your assets are about to reach EOL, or when your licenses are expiring, make sure you have an alert email address listed in Admin > Settings.

I have set EOL for some models to one month as a test, date purchased is a couple days before then, and set the threshold for reports on Admin>Settings to 90 days.

cron jobs are set up to send expiring alerts, inventory alerts, and upcoming audits daily which are working as expected

Why am I not getting emails for assets reaching EOL when the documentation references it?  Is it some other scheduled task?

**Comment by snipe** [comment]
Yes, you'd need to either use the scheduler or set up a cron specifically for that alert, per the documentation further down on that page.

**Comment by EpicallyJess** [comment]
The page doesn't show how to leverage the EOL field, only warranty expiration, license expiration, or inventory alerts.

is it as simple as eol-alerts instead of expiring-alerts ?

**Comment by snipe** [comment]
EOL considers warranty months, but the expiring-alerts includes EOL and expiring licenses

**Comment by EpicallyJess** [comment]
I am seeing reports that warrantees are expiring but not for EOL.  I'm just trying to understand the logic.  A machine may be in service for longer than the warranty.  If the Warranty is 48 months, and the EOL is 49 months and those dates are within the threshold (90 days for me to test), does that mean that I would see 2 emails sent, one for assets with EOL within 90 days and one for warranty expiring within 90 days?  If this is the expected behaviour, I am only seeing the warranty expiration, and nothing for EOL.
