### ISSUE TITLE
How can I import, from a CSV file, the check out to the staff/location/assets?

### ISSUE THREAD

**Issue by mondinimirko** [grokability/snipe-it#7878]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I try to import a .csv file from the import section i cannot import the "check out to" (user, asset and location). I've done some test (built first the relationship into the software, then export a .csv, deleting the asset in snipe and import the same .csv but nothing). 

**To Reproduce**
1. Go to _import_
2. Click on _select import file_
3. Upload the file
4. Click on _process_
5. Import type _assets_
6. Match the filed
7. Click on _import_

**Expected behavior**
Should be able to see as status **Deployed** and Checked out to the location/users/asset that i choose in the .csv.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.8.0 - build 4186 (master)
 - OS: [Windows 2016 datacenter]
 - Web Server: [WampServer]
 - PHP Version:  7.3.12

**Desktop (please complete the following information):**
 - OS: [Windows 10 professional]
 - Browser [Mozilla]
 - Version [73.0.1]

**Additional context**
- Fresh installation.
- No error message during the installation.

This for me it's very important because I've a lot of excel file with all this information and it's too much work to check out one by one all the assets. Kindly ask some support.

**Comment by mondinimirko** [comment]
Well, it depends ... if like me you are starting a new inventory of a large company, having the option to import also check out could be a very useful feture. Now I am using the Bulk Checkout function but from an operational point of view it is a little inconvenient. It would be nice to have the import directly from the CSV. Then for the rest I am feeling very well.

**Comment by Lari0** [comment]
Hi
is this planned to be implemented/fixed ?

I have unsuccesfully tried importing new assets with ready to deploy status and using username of existing user to checkout.

**Comment by athompsoncmc** [comment]
I'm still looking for a way to check out to assets via CSV. This is an option for users and locations, but no option for assets.

**Comment by shoenot** [comment]
Bump
