### ISSUE TITLE
Can't upload an manager and parent of location via API requests

### ISSUE THREAD

**Issue by domad007** [grokability/snipe-it#7880]
I'am trying to upload an manager of location via API request. 
So i can upload location name, address etc. But not manager 
I didnt found a request to make this operation. 
I am working with symfony 5. 
My request seems like that: 
'PUT', 
                'api/v1/locations/313', [
                    'json' => [
                        'name' => "test4",
                        'address' => "test",
                        'zip' => "test",
                        'city' => "test",
                        'country' => "BE",
                        'manager' => $resp['rows'][0]
                    ]
                ]

$resp variable contains user informations

**Comment by snipe** [comment]
> $resp variable contains user informations

Meaning what exactly? `manager_id` would be expecting the numeric ID of the manager.

**Comment by domad007** [comment]
Thanks it works i'have just changed 'manager' to 'manager_id' and i specified the 'id' of the user. 
It wasn't specified in the doc. 
Issue can be closed.

**Comment by thesupporthero** [comment]
Hi Hi!
You should be able close this by hitting the little "close issue" button next to comment. ♥

With love,
The Support Hero♥

**Comment by domad007** [comment]
Problem  solved
