### ISSUE TITLE
Redirect to details page after editing

### ISSUE THREAD

**Issue by nickjmv** [grokability/snipe-it#7884]
**Is your feature request related to a problem? Please describe.**
I have an issue with the following. I open an assets details page. Then I decide to edit this asset and upon hitting the save button I get redirected to the All Assets page.

Wouldn't it be more logical to return to the Asset details page of the one you just edited?

**Describe the solution you'd like**

Get redirected from the edit page to the just edited asset details page

**Comment by snipe** [comment]
I mean, it depends on your workflow. Pretty sure that's how we used to do it, and people complained that they wanted to go back to the assets page without the extra click.

**Comment by nickjmv** [comment]
Oh okay, and is this something you could add as a setting in the settings page?

**Comment by snipe** [comment]
I think it would make more sense to add a checkbox/dropdown on each of the main screens where users can decide at that moment (based on what they're doing). We can set a cookie so that it remembers so it saves a click if your workflow doesn't change. 

I doubt we'd get to that before v5 is released though, to be honest.

**Comment by nickjmv** [comment]
Hm okay, no problem! This can be closed I guess, it's just something to get used to how it is, thanks for the fast answer!

**Comment by snipe** [comment]
Nah, it's a legit feature request (one I've been thinking about for a long time, just kinda stuck until we ship v5) so I'll keep it open to remind me :)

**Comment by nickjmv** [comment]
Alright, when is V5 launching?

**Comment by snipe** [comment]
> Alright, when is V5 launching?

Heh, when it's ready. We're still testing some LDAP stuff (that whole thing was completely rewritten) and trying to fix an issue with S3/cloud file uploads.

**Comment by kekkers23** [comment]
+1 Great request

**Comment by nickjmv** [comment]
Damn stalebot, why u closed this :(
