### ISSUE TITLE
ADLDAP2 is now DirectoryTree/LdapRecord.

### ISSUE THREAD

**Issue by HinchK** [grokability/snipe-it#7896]
https://github.com/Adldap2/Adldap2

is no longer receiving new features, as the developers are choosing to pivot the product to https://github.com/DirectoryTree/LdapRecord.

LdapRecord has some pretty big advantages right away, such as referral-following for Active Directory and reading custom attributes.   

Starting this package-transplant at this time, and the issue to track progress/blockers/etc. encountered replacing adldap2 with ldaprecord in snipie-it:v5.

**Comment by timwsuqld** [comment]
Not stale. @snipe can you please Triage this so it's not marked as stale?

**Comment by timwsuqld** [comment]
Not stale. @snipe can you please Triage this so it's not marked as stale?

**Comment by timwsuqld** [comment]
Not stale. @snipe can you please Triage this so it's not marked as stale?
