### ISSUE TITLE
Requestable Assets "Check Out" Button Missing

### ISSUE THREAD

**Issue by Paralda** [grokability/snipe-it#7897]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Previously, when going to "Requested Assets" there was a button to check out assets. Now that's gone, which makes the Asset Request system basically useless.

**To Reproduce**
1. Log in as an admin
2. Go to index.php/account/requested
3. View the lack of a "Check out" button.

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by DevinSysAdmin** [comment]
technically yes, I confirmed your issue on the demo website however there is another place to look at this  and I confirmed it to be working. https://demo.snipeitapp.com/hardware/requested

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/requested">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
