### ISSUE TITLE
View Basic Asset Details Without Authentication

### ISSUE THREAD

**Issue by harryangel2608** [grokability/snipe-it#7898]
**Server (please complete the following information):**
 - Snipe-IT Version - v4.8.0 - build 4186 (master)
 - OS: [e.g. Ubuntu, CentOS] - CentOS 7
 - Web Server: [e.g. Apache, IIS] - Apache
 - PHP Version  - 7.2.25

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to generate a QR code of an asset and once it is scanned it should display basic information about that asset to the user without having/logging to an account. It should display sample fields like asset type, purchase date and warranty details etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by harryangel2608** [comment]
Yes

**Comment by wgy855** [comment]
This is the function I am looking for. I hope this can be done very soon~

**Comment by harryangel2608** [comment]
Yes

**Comment by MaKaNu** [comment]
And from 2022: It is still relevant and I am sure there are a few other users who would like to use this.
