### ISSUE TITLE
Total Licenses - Edit 

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#7899]
Anyone else experiencing this issue?

I recently went from 4.8.0 to 4.9.0 and now am not able to edit license information without a whoops page.

I'm running SnipeIT on WAMP on Server 2012R2.

Ideas? Thanks

**Comment by pbrink231** [comment]
I had an issue where /license would take me to the Apache license page.  I
don’t know if this is affecting you but see if there is an alias for
license that is directing you to something else in your http.conf file

**Comment by jmartins1** [comment]
Thank you, unfortunately for me that's not the case. Thanks for the quick response! 

⁣Sent from BlueMail ​
