### ISSUE TITLE
SWAGGER - Documentation shared

### ISSUE THREAD

**Issue by mematthew** [grokability/snipe-it#7900]
I would like to have access the the swagger.yaml file, can someone share this ?

**Comment by isopod-m** [comment]
I would like to have access to it also. I have to make a swagger file to connect Snipe-it to MS Flow. I used to do it with Postman, but there is no required function in Postman. That way, when I update the MS Flow connector from the Postman collection I have to set every filed to not required manually.

**Comment by stingalleman** [comment]
I'm also intrested. Is there a swagger file somewhere? @snipe
