### ISSUE TITLE
Fatal error: Class Swift_Transport_StreamBuffer contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods 

### ISSUE THREAD

**Issue by Forowebmasters** [grokability/snipe-it#7901]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Edit the file and then it was bothering me with this
**src / vendor / swiftmailer / swiftmailer / lib / classes / Swift / Transport / StreamBuffer.php Unexpected contents

I came to Github copy the code here and replace it with the one I had

and now I get this error:
Fatal error: Class Swift_Transport_StreamBuffer contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Swift_ByteStream_AbstractFilterableInputStream :: _ commit, Swift_ByteStream_AbstractFilterableInputStream / swift / librift / vendor / vendor / swift / libc /StreamBuffer.php on line 16**
**To Reproduce**
When I go to my website page with xenforo 2.x

/admin.php?tools/test-email

**Expected behavior**
The xenphor panel will open to test if the email system is working correctly

But no.
**Screenshots**
https://prnt.sc/rh63p3
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
Fatal error: Class Swift_Transport_StreamBuffer contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Swift_ByteStream_AbstractFilterableInputStream::_commit, Swift_ByteStream_AbstractFilterableInputStream::_flush) in /home/foroprem/web/foropremium.com/public_html/src/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 16

**Additional context**
I don't know how to recover the file, I need help :(

**Comment by snipe** [comment]
Please answer the rest of the questions in the issue template.
