### ISSUE TITLE
Zebra designer pro software 

### ISSUE THREAD

**Issue by sheiknaveed** [grokability/snipe-it#7902]
Dear team,
I had connected the snipeit database to Zebra designer pro barcode software. I am able to generate the bardoce using the serial number or model number but I would like to generate a barcode which take me to the URL for that hardare(i.e http://asset.xyz.com/hardware/1453)

**Comment by gilesytheking** [comment]
The QR code generated by Snipe IT will direct you to the asset URL when scanned. Not sure if you can import the barcode images into your label software.

Otherwise you will have to lookup the asset ID within the Snipe-IT database and use that to generate the URL and a QR code within Zebra Software

**Comment by sheiknaveed** [comment]
Thanks. I was able to resolve this by using database in zebra designer


Sheik Naveed
شيك نافيد
Academic Systems Administrator
مسؤول النظم الأكاديمية
Smart Services and Projectsالخدمات الذكية والمشاريع
Tel: 800- MBRU (6278)
Direct +9714 383 8606
Naveed.Sheik@mbru.ac.ae
www.mbru.ac.ae
P.O. Box 505055, Dubai,  UAE

**Comment by thesupporthero** [comment]
Don't forget to mark this as solved/closed ♥
