### ISSUE TITLE
AD Ldap Sync not deactivating disabled users

### ISSUE THREAD

**Issue by JoshuaSeidel** [grokability/snipe-it#7903]
#### Please confirm you have done the following before posting your bug report:

- [ *] I have enabled debug mode 
- [* ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When doing a LDAP sync, it shows full updates, but all users which have been disabled in AD are still showing active in SnipeIT
**To Reproduce**
1. Go to 'People'
2. Click on 'Execute Ldap sync all locations'
3. Scroll down to 'any disabled user..'

**Expected behavior**
when ldap sync happens against MS AD that any disabled accounts in AD, be marked inactive in Snipe IT

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version : 4.9.0
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Nginx
 - PHP Version 7.3.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? fresh
- What OS and web server you're running Snipe-IT on Centos 7.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by thesupporthero** [comment]
Have you tried using the LDAP/AD filter to only sync active users?

**Comment by honey1090** [comment]
in my case the issue was using a normal domainuser for ldap sync - everything worked except the active/disabled state update - domain users doesn't have permission to read "useraccountcontrol" attribute from the users i've imported. have not tried it out exactly but giving the ldap-sync user admin permissions to read all attributes the active/disabled state is synced correctly. no need for ldap filter at this point.
perhaps someone could add this to "common issues" section - really drove me crazy.
