### ISSUE TITLE
FEATURE REQUEST: SSL Certificate tracking

### ISSUE THREAD

**Issue by jared-bloomer** [grokability/snipe-it#7905]
It would be nice to have a dedicated section in snipe-it for listing SSL certificates. I know you can in theory track it in the Licenses page, but that gets ugly if you also have to track other licenses. 

It would be nice to have an SSL Certificate inventory with the following available fields

Certificate Name
Certificate issued date
Certificate expiration date
Certificate issuing Authority
CSR
Intermediate Certificate
Device it is installed on (allow for multiple devices)
Department Contact (who is responsible for the Certificate)
Notes

Thanks

**Comment by jared-bloomer** [comment]
Also would be nice to have a field for the CSR

**Comment by sg-ot** [comment]
+1 - this feature would be useful

**Comment by pacles82** [comment]
+1 me too. we appreciate to have this feature

**Comment by vjernej** [comment]
+1 from my side.
