### ISSUE TITLE
UsersImporter Class Not Found

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#7906]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I try to import a csv for users through the CLI I get an error saying " Class 'App\Importer\UsersImporter is not found" I checked and it is there with the same permissions as the rest of the importers.

**To Reproduce**
1. SSH into the server and run the following command in the snipeit directory.
2. php artisan snipeit:import --item-type Users \Path\to\csv

**Expected behavior**
I expected that the importer would import my users out of the CSV

**Screenshots**
![image](https://user-images.githubusercontent.com/42612805/76989487-7156d580-6914-11ea-9c4c-aa2c1f8c51d5.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.8.0
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version  7.3

**Additional context**
This is a fresh copy of snipe it we are using to test to decided if we want to move to it. I installed via the script. I have it running on Ubuntu on a VM. Haven't had issues with any of the other uploaders. I have tried upgrading to the newest branch, but that didn't solve the issue.

**Comment by mnemonicly** [comment]
--item-type=User

**Comment by ghost** [comment]
I seem to be getting the same error as before. Still can't find that class.
![image](https://user-images.githubusercontent.com/42612805/77009380-ceaf4e80-6935-11ea-8de8-365ff0c16642.png)

**Comment by mnemonicly** [comment]
You're getting a different error when you run the first.  It looks like database issues?
