### ISSUE TITLE
FEATURE REQUEST: Multi Serial Number for each Accessories.

### ISSUE THREAD

**Issue by hatpt** [grokability/snipe-it#7907]
Hi,
I would like in the accessories section to allow multiple serial numbers for a model.  When we checkout process, it will have a list to choose a serial number from the created list.

Thanks

**Comment by thesupporthero** [comment]
Um, question...if I remember correctly...Accessories are anything you issue to users but that do not have a serial number (or you do not care about tracking them uniquely).
Wouldn't adding serial numbers defeat what this section is used for?

With love,
The Support Hero♥
