### ISSUE TITLE
Assets by Status in Dashboard is empty

### ISSUE THREAD

**Issue by snipeituser-xx** [grokability/snipe-it#7908]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.9.0
 - OS: [e.g. Ubuntu, CentOS] Windows Server 2016
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.3.15

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? -fresh install
- What OS and web server you're running Snipe-IT on - Windows Server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual installation
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

Hi,

I've noticed that in my Snipe-it dashboard, one of the widgets - Assets by Status is empty.
How to solve this issue?
Thank you.
![image](https://user-images.githubusercontent.com/62375248/77045457-2f08c380-69fc-11ea-832c-c0e3159449da.png)

**Comment by evilscarp** [comment]
I seem to have triggered this issue myself.  I did not see anything interesting in the debug-- there were no errors to speak of, just an empty "Assets by Status" widget as described above.  We do have a large number of assets (15k+) with various status.  Perhaps it's a scaling issue?
