### ISSUE TITLE
Customization of the Dashboard

### ISSUE THREAD

**Issue by aquapixie** [grokability/snipe-it#7911]
**Server (please complete the following information):**
 - Snipe-IT Version v4.9.0 build 4210
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version 7.3.16

**Is your feature request related to a problem? Please describe.**
Tracking components on the dashboard rather than consumables

**Describe the solution you'd like**
I would like a shortcut to Components at the top of my dashboard rather then accessories as we do not track them as much.

**Comment by aquapixie** [comment]
<div class="small-box bg-orange">
      <div class="inner">
        <h3> {{ number_format($counts['accessory']) }}</h3>
          <p>{{ trans('general.total_accessories') }}</p>
      </div>
      <div class="icon">
        <i class="fa fa-keyboard-o"></i>
      </div>
      @can('index', \App\Models\Accessory::class)
          <a href="{{ route('accessories.index') }}" class="small-box-footer">{{ trans('general.moreinfo') }} <i class="fa fa-arrow-circle-right"></i></a>
      @endcan
    </div>


Is there a way to change this code to show components rather than accessories? Obviously changing the words will not work as there is alot of programming in the background.

**Comment by viclou** [comment]
+1 FD15361
