### ISSUE TITLE
LDAP location user sync

### ISSUE THREAD

**Issue by Wyndoon** [grokability/snipe-it#7936]
I am looking at how to import my users from my AD environment.  I seem to be getting an  Error: ldap_search(): Search: Operations error   

The LDAP configuration appears to me working correctly on the configuration page just not on the location LDAP sync page.  Maybe I am not clear on how that should work.  

I am looking to avoid manually creating our users and do not really need them to log into Snipe as this is mostly for our IT folks to look at and manage assets and licenses.

I am also having an issue importing our assets as well as the screen just says processing.  

Any assistance would be greatly appreciated.

**Comment by HinchK** [comment]
can you share the contents of the last error in your `storage/logs/laravel.log` please?

**Comment by Wyndoon** [comment]
This is stuff from today which is kind of the last time I worked on it.  It looks like problems with SMTP which would make sense as I never configured that option since I do not need it for my environment.  Is it required to use these other features of Snipe?

[2020-04-01 00:00:05] production.ERROR: Failed to authenticate on SMTP server with username "YOURUSERNAME" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 334 but got code "530", with message "530 Must issue a STARTTLS command first
". Authenticator PLAIN returned Expected response code 235 but got code "530", with message "530 Must issue a STARTTLS command first
". {"exception":"[object] (Swift_TransportException(code: 0): Failed to authenticate on SMTP server with username \"YOURUSERNAME\" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 334 but got code \"530\", with message \"530 Must issue a STARTTLS command first
\". Authenticator PLAIN returned Expected response code 235 but got code \"530\", with message \"530 Must issue a STARTTLS command first
\". at /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:191)
[stacktrace]
#0 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport))
#1 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand()
#2 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(64): Illuminate\\Mail\\Mailer->send(Object(Illuminate\\Support\\HtmlString), Array, Object(Closure))
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\\Notifications\\Channels\\MailChannel->send(Object(Spatie\\Backup\\Notifications\\Notifiable), Object(Spatie\\Backup\\Notifications\\Notifications\\CleanupHasFailed))
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(Spatie\\Backup\\Notifications\\Notifiable), 'bcf5be44-a577-4...', Object(Spatie\\Backup\\Notifications\\Notifications\\CleanupHasFailed), 'mail')
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\\Notifications\\NotificationSender->sendNow(Array, Object(Spatie\\Backup\\Notifications\\Notifications\\CleanupHasFailed))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(35): Illuminate\\Notifications\\NotificationSender->send(Array, Object(Spatie\\Backup\\Notifications\\Notifications\\CleanupHasFailed))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send(Object(Spatie\\Backup\\Notifications\\Notifiable), Object(Spatie\\Backup\\Notifications\\Notifications\\CleanupHasFailed))
#11 /var/www/snipeit/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\\Backup\\Notifications\\Notifiable->notify(Object(Spatie\\Backup\\Notifications\\Notifications\\CleanupHasFailed))
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(350): Spatie\\Backup\\Notifications\\EventHandler->Spatie\\Backup\\Notifications\\{closure}(Object(Spatie\\Backup\\Events\\CleanupHasFailed))
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(200): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Spatie\\\\Backup\\\\E...', Array)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(467): Illuminate\\Events\\Dispatcher->dispatch('Spatie\\\\Backup\\\\E...')
#15 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/CleanupCommand.php(47): event(Object(Spatie\\Backup\\Events\\CleanupHasFailed))
#16 [internal function]: Spatie\\Backup\\Commands\\CleanupCommand->handle()
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#22 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#24 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /var/www/snipeit/vendor/symfony/console/Application.php(982): Spatie\\Backup\\Commands\\BaseCommand->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /var/www/snipeit/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Spatie\\Backup\\Commands\\CleanupCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /var/www/snipeit/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/snipeit/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 {main}
"}

**Comment by HinchK** [comment]
ah, ok -
2 questions:
 * what kind of server are you hosting on?
 * please check your settings against https://snipe-it.readme.io/docs/ldap-sync-login - let me know if that helps! (i.e. if we need to update our docs)


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/ldap-sync-login">LDAP Sync & Login</a></strong></div><div>The LDAP functionality will import any users in your LDAP/Active Directory using the LDAP sync (in People &gt; LDAP), and will update existing users. It will also allow users to use their LDAP credentials to login to Snipe-IT.  To set up your Snipe-IT installation to be able to use LDAP for user log...</div></blockquote>

**Comment by Wyndoon** [comment]
Hosting it on a Ubuntu 18.04 Linux Box.  I did follow those and they seem to be good as far as the setting go.  I am able to test it on that page and all is good.  I can even use my AD creds to login to the web interface.  and so can anyone in the current OU that the LDAP settings are targeting.  Our AD environment is a mess that I walked into so there is going to be slow change.  I was thinking that the "location: LDAP sync would pull in those users that were a part of that OU, but that does not appear to be the case.

**Comment by HinchK** [comment]
are you able to run `php artisan snipeit:ldap-sync --summary` from the command line?

**Comment by Wyndoon** [comment]
it runs but nothing is returned but it also does not error

**Comment by HinchK** [comment]
OK - I think I know what might be happening.

Can you please put the entire OU + DN in that Location.ldap_ou setting, then try to sync that location. 
 
The ldap_ou setting available by 'editing' one of your /location(s))

**Comment by Wyndoon** [comment]
I have entered it as follows
OU=Information Services,OU=Central Services,DC=internal,DC=dot,DC=com
Not sure if it needs surrounded by quotes or if that is the correct format
with the same results.  
I have been trying to even do an upload of the data exported from AD basically, and I think I have a path to walk for the importer issues.  at least I am seeing an error when trying to do things in chromes dev tools.

**Comment by HinchK** [comment]
That looks great, now try to do a "sync" to that location.

(just to be clear, we are talking about the `master` branch correct?)

**Comment by Wyndoon** [comment]
I have it in the location that I am trying to sync.  not sure what you mean by master branch

**Comment by Wyndoon** [comment]
I got it working, after modifying some things in the LDAP setting.  I recommend giving a short example of what a setup might look like.

**Comment by HinchK** [comment]
Thank you for the feedback @Wyndoon - actually working on that documentation (and a slew of new v5 LDAP/User Features) at this time.

Have a great weekend!
