### ISSUE TITLE
Install Composer and Dependencies OFFLINE MODE (No Internet)

### ISSUE THREAD

**Issue by minhanh1234** [grokability/snipe-it#7944]
Hi i am trying to install SnipeIT on a windows server with IIS
anyway we can download and install composer and all the dependencies offline without an internet connection?

**Comment by snipe** [comment]
Not really. I suppose you could download them somewhere else and move them over to your IIS server, but composer really wants to be able to grab packages from the internet.

**Comment by minhanh1234** [comment]
would you know what file and folder i need to copy from a server that would have internet?
I do have an option to import the file over to the lockdown server
