### ISSUE TITLE
API extension to be able to request by rtd_location and status_label.status_type

### ISSUE THREAD

**Issue by danielepelosi** [grokability/snipe-it#7947]
**Server (please complete the following information):**
 - Snipe-IT Version v4.9.0 - build 4210 (master) (hosted plan by you)

**Describe the solution you'd like**
Expand your API to allow requests based on rtd_location & status_type. These fields are currently not directly requestable, and it makes the development very difficult for us as we are not a software company, and we are trying to integrate Snipe-it with our billing system.

**More details**
Basically we use the rtd_location to state in which building the items are, and we use the location to check out items to specific rooms in the building. We are trying to make an integration to your billing system through Zapier, and it would get great if it was possible to make an API request where we pass the rtd_location and we pass the status_type=deployable (we need to bill everything which is in this status). A direct integration of this kind would allow us to get directly the information we need, and process it so we can send to the billing system for automatic monthly billing. 

I hope this is a doable request, because it would make it much easier for quick integrations. I spoke with one of your technicians and they stated that it is a "reasonable feature request".

**Comment by snipe** [comment]
To search by status type, you'd use `status`, like:

`/api/v1/hardware?status=Deployed`

(It's how we load the assets from the side asset menu when you click on "Deployed", "Ready to Deploy", etc)

RTD will be in the next release.

**Comment by danielepelosi** [comment]
@snipe if I search by status=Deployed I do not get all the results I am looking for (basically we need to bill also things that are in custom states, but have status_type = deployable). This way with one request I could get all the results. See attached screenshot for clarification
![status4](https://user-images.githubusercontent.com/63336653/78866544-da2afc80-7a3f-11ea-815c-12f7a94b24e8.PNG)
![status3](https://user-images.githubusercontent.com/63336653/78866547-dac39300-7a3f-11ea-89a4-35e98f7b2904.PNG)
![status2](https://user-images.githubusercontent.com/63336653/78866549-dac39300-7a3f-11ea-8957-2bc1daa78758.PNG)
![status](https://user-images.githubusercontent.com/63336653/78866550-db5c2980-7a3f-11ea-9bc6-38f17b33fb01.PNG)
