### ISSUE TITLE
Proper right-to-left (RTL) support

### ISSUE THREAD

**Issue by Madsn** [grokability/snipe-it#7951]
**Is your feature request related to a problem? Please describe.**
When changing language to e.g. Arabic, the layout is still LTR.

**Describe the solution you'd like**
RTL languages should render RTL.
The menu drawer doesn't necessarily need to be on the right and the top panel could be left as is. Everything else should be flipped compared to LTR - headers should be right aligned and tables should have column order reversed. If a page (in LTR) has input fields on the left side and an image on the right, it should be reversed when in RTL so image is on the left side etc.

**Describe alternatives you've considered**
It looks like the UI is based on AdminLTE, and an implementation of [AdminLTE with RTL support](https://github.com/mmdsharifi/AdminLTE-RTL) does exist, though it is based on the older 2.2.1.
Simply setting `direction: rtl` property on html body gets us part of the way there, but from what I can tell some UI elements will require updated styling to properly render RTL. Haven't looked into how much of that is AdminLTE specific, and how much needs to be fixed in Snipe-IT.

I'm willing to spend some more time looking into this and possibly submitting a PR, if we can agree on an approach that would be acceptable.

**Comment by snipe** [comment]
I'm up for it, sure. We do depart from some of the stock AdminLTE stuff, which is why we haven't implemented it sooner.

**Comment by Madsn** [comment]
I took a quick crack at it, try to figure out how much work it would be.

I used (bootstrap-rtl theme)[https://github.com/morteza/bootstrap-rtl] and applied the `flip` class to elements that had `.pull-right|left`. That did get me a lot of the way there, but still a lot of minor issues. Some elements with `.text-left` needed to have `.flip` added as well, some elements have inline CSS style with `padding-left: 0px`, which needed to be `padding-right: 0px`. The side menu looked a bit funky too, and ideally should be moved to the right side. Might be many other issues but that's what I saw based on a quick trial.

So it's doable for sure, could load the RTL bootstrap theme if the user chooses an RTL language and regular theme for other languages. Definitely requires some styling refactoring though.

If anybody else is willing, by all means go ahead. I'm still considering doing it, but it's on the backburner for now. Go ahead and close if you don't want it open unless someone is ready to work on it.

**Comment by AL4AL** [comment]
Is there anybody who works on this?
Or if you have any plans for this, please share
I was about to start implementing this feature, but I want to coordinate this
@snipe

**Comment by Madsn** [comment]
@AL4AL 
I am not working this, so feel free 😊

**Comment by jvarn** [comment]
If anyone needs a quick fix to get RTL working:

### 1. Create and load RTL CSS:

- Take the contents of the following file `/var/www/html/snipeit/public/css/dist/all.css` and convert it to RTL using an online service such as [RTLCSSOnline](https://rtlcss.com/playground/).

- Next create a new RTL stylesheet `/var/www/html/snipeit/public/css/dist/rtl.css` and insert the converted CSS.

- Set the appropriate file owner (for me it is snipeitapp:www-data).

- Edit the default template `/var/www/html/snipeit/resources/views/layouts/default.blade.php` and change the following line:

```php
<link rel="stylesheet" href="{{ url(mix('css/dist/all.css')) }}">
```

into:

```php
    <!-- Conditionally load RTL or LTR stylesheet based on language direction -->
    @if (Helper::determineLanguageDirection() == 'rtl')
        <link rel="stylesheet" href="{{ asset('css/dist/rtl.css') }}">
    @else
        <link rel="stylesheet" href="{{ url(mix('css/dist/all.css')) }}">
    @endif
```

### 2. Fix Select2 dropdown position:

Select2 dropdowns such as those on the profile page are positioned incorrectly.

- Create a new file `/var/www/html/snipeit/public/js/global-select2-rtl.js`:

```js
document.addEventListener("DOMContentLoaded", function() {
    var $container; // Variable to store the dropdown container

    // Function to update the dropdown position
    function updateDropdownPosition() {
        // Check if the page is in RTL mode by looking at the HTML dir attribute
        var dir = $("html").attr("dir");

        if (dir === "rtl" && $container && $container.is(":visible")) {
            var $parent = $(".select2.select2-container.select2-container--default.select2-container--below.select2-container--open");

            // Get parent element offset
            var parentOffset = $parent.offset();
            var containerWidth = $container.outerWidth();
            var windowWidth = $(window).width();

            // Calculate how much space is between the right edge of the parent and the right edge of the viewport
            var spaceFromRight = windowWidth - (parentOffset.left + $parent.outerWidth());

            // Set the right value relative to the parent's position
            $container.css({
                "right": spaceFromRight + "px",  // Position container based on space from right
                "left": "auto"  // Remove left to ensure it doesn't interfere
            });
        }
    }

    // Listen for the select2:open event on all select2 elements
    $(document).on("select2:open", function(e) {
        // Store the dropdown container (a bit clumsy because it shares the same classes as the parent)
        $container = $("body > .select2-container.select2-container--default.select2-container--open:not(.select2-container--focus):not(.select2-container--below):not(.select2)");

        // Call the function to update the dropdown position initially
        updateDropdownPosition();
    });

    // Listen for window resize events and update the dropdown position if open
    $(window).on("resize", function() {
        updateDropdownPosition();
    });
});
```

- Set the correct file ownership (snipeitapp:www-data). 

- Edit the default template `/var/www/html/snipeit/resources/views/layouts/default.blade.php` and append the following line after the existing JS files:

```php
        {{-- Javascript files --}}
        <script src="{{ url(mix('js/dist/all.js')) }}" nonce="{{ csrf_token() }}"></script>
        <script src="{{ url('js/select2/i18n/'.Helper::mapBackToLegacyLocale(app()->getLocale()).'.js') }}"></script>

         /* New script */
        <script src="{{ asset('js/global-select2-rtl.js') }}"></script>
```
