### ISSUE TITLE
Problems updating Snipe-IT as non-root user

### ISSUE THREAD

**Issue by wicknet** [grokability/snipe-it#7958]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

As root, setup latest Snipe using git on clean Ubuntu 18.04 using 

Apart from a MariaDB user called snipeit, it created a non-root user called snipeitapp and gave it and www-data permissions on the /var/www/snipeit folder and sub-folders.

The initial setup screens came up and I was able to restore data from an earlier version using phpmyadmin - all good so far.

As root, I can run git pull on /var/www/snipeit folder and it shows synced to master. It doesn't run php upgrade.php as root. When I logout  and log back in as snipeitapp user and run php.upgrade.php in the project folder - it gives multiple errors. See below:

snipeitapp@snipeit:~$ ./update-snipe.sh 
Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT 
files for you unless you have git installed. 
It simply runs the standard composer and artisan 
commands needed to finalize the upgrade after. 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter if upgrading from v3 to v4. 
!! See the Snipe-IT documentation for help: 
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Backing up database: 
--------------------------------------------------------

-- Starting backup...
Backup failed because: mkdir(): Permission denied.

--------------------------------------------------------
STEP 2: Putting application into maintenance mode: 
--------------------------------------------------------

-- 
In StreamHandler.php line 108:
                                                                               
  The stream or file "/var/www/snipeit/storage/logs/laravel.log" could not be  
   opened: failed to open stream: Permission denied                            
                                                                               

--------------------------------------------------------
STEP 3: Pulling latest from Git (master branch): 
--------------------------------------------------------

Git is installed. 
error: cannot open .git/FETCH_HEAD: Permission denied
Already on 'master'
error: unable to unlink old 'public/uploads/barcodes/invalid_barcode.gif': Permission denied
error: unable to unlink old 'storage/private_uploads/signatures/.gitkeep': Permission denied
fatal: Could not reset index file to revision 'HEAD'.
error: cannot open .git/FETCH_HEAD: Permission denied
-- -- Saved working directory and index state WIP on master: 154db9a41 This literally never fucking worked. Ever. Shoot me.
-- M	public/uploads/barcodes/invalid_barcode.gif
M	storage/private_uploads/signatures/.gitkeep
Your branch is up to date with 'origin/master'.
-- --------------------------------------------------------
Step 4: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- Deleting bootstrap/cache/config.php. It it no longer used.
-- Configuration cache cleared!
-- Cache cleared successfully.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 5: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar - trying globally.

Deprecation Notice: Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Notifications\RequestAssetCancelationNotification located in ./app/Notifications/RequestAssetCancelation.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Http\Transformers\DepartmentsTransformer located in ./app/Http/Transformers/DepartmentsTranformer.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Generating optimized autoload files
Deprecation Notice: Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Notifications\RequestAssetCancelationNotification located in ./app/Notifications/RequestAssetCancelation.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Http\Transformers\DepartmentsTransformer located in ./app/Http/Transformers/DepartmentsTranformer.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
Discovered Package: barryvdh/laravel-cors
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: rollbar/rollbar-laravel
Discovered Package: schuppo/password-strength
Discovered Package: spatie/laravel-backup
Discovered Package: tightenco/ziggy
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Generated optimized autoload files containing 4383 classes

Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
Discovered Package: barryvdh/laravel-cors
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: rollbar/rollbar-laravel
Discovered Package: schuppo/password-strength
Discovered Package: spatie/laravel-backup
Discovered Package: tightenco/ziggy
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.

--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------

-- 
In StreamHandler.php line 108:
                                                                               
  The stream or file "/var/www/snipeit/storage/logs/laravel.log" could not be  
   opened: failed to open stream: Permission denied                            
                                                                               

--------------------------------------------------------
Step 7: Checking for OAuth keys:
--------------------------------------------------------

- OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 8: Caching routes and config:
--------------------------------------------------------

-- Configuration cache cleared!
Configuration cached successfully!
-- Route cache cleared!
Routes cached successfully!

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

--------------------------------------------------------
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.
--------------------------------------------------------
**To Reproduce**
Run install.sh
After initial setup, login as snipeitapp and run php upgrade.php

**Expected behavior**
upgrade to run without errors

**Server (please complete the following information):**
Snipe-IT Version v4.9.2 - build 4352 (master)
Ubuntu 18.04 fully updated
Apache/2.4.29 (Ubuntu)
PHP 7.2.24-0ubuntu0.18.04.3 

**Desktop (please complete the following information):**
macOS Mojave 10.14.6
Chrome Version 80.0.3987.163 

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? FRESH
- What OS and web server you're running Snipe-IT on - SEE ABOVE

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
> error: cannot open .git/FETCH_HEAD: Permission denied

This typically means that git pull was done at least once as root user. You'll want to change the owner of any dirs you run into permissions errors on.

`chown -R snipeitapp /var/www/snipeit` <-- that will change the owner of all of your snipeit files to your `snipeitapp` user.

**Comment by wicknet** [comment]
Thanks for the prompt response. The cmd
chown -R snipeitapp /var/www/snipeit/.git/FETCH_HEAD 
worked to do a git pull as snipeitapp user. However, on running php upgrade.php, manual backup fails with -- Starting backup...
Backup failed because: mkdir(): Permission denied.
Not clear which directory now needs permissions for snipeitApp.
After that is the error:
In StreamHandler.php line 108: The stream or file "/var/www/snipeit/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied 

Since this appear to be a common issue many folks trying out snipeit struggle with, It would be REALLY helpful if ALL the recommended directory permissions that must be applied after running install.sh are provided as a bullet list in the documentation, instead of piecemeal against each opened issue.
Eg - make sure snipeitapp is a member of the sudo group
then while logged in as snipeitapp, do this, then this, then this and then git pull and php.upgrade.php will work for updates.

Many thanks for your fine work.. it is head and shoulders above all other inventory software on Github.

**Comment by wicknet** [comment]
Issue #7172 helped me find a solution. php upgrade.php now works under snipeitapp user

As mentioned earlier, one of the gaping lacunae in the documentation is lack of clear directions to set folder permissions after install.sh has run.  For anyone stuck with this issue, login as snipeitapp user (it must have a password and be a member of the sudo group)

Then run the following commands in /var/www/snipeit

sudo chown -R snipeitapp:www-data /var/www/snipeit/
sudo chown -R www-data:www-data storage public/uploads
sudo chmod -R 755 storage public/uploads

Done!
