### ISSUE TITLE
status on License, accessor after checkout ?

### ISSUE THREAD

**Issue by damgaarderik** [grokability/snipe-it#7962]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to License"
2. Click on 'Create new....'
3. Click on (after new item is created) "Checkout"
4. Select user and click checkout
5. On License page check : button still showing "checkout"
6. Move mouse over button : "This item has a status label that is undeployable and cannot be checked out at this time"

**Expected behavior**
License items do not have a status label ? so it is expected that the License is checked out to the user selected, and the button changes to checkin (to be able to do so if needed)

**Screenshots**

![snipeit](https://user-images.githubusercontent.com/5988225/79078145-9ae20180-7d06-11ea-98de-4a2f5e3bbbbf.png)

**Server (please complete the following information):**
 - Snipe-IT Version : 4.9.2
 - OS: Ubuntu 18.04
 - Apache/2.4.29 (Ubuntu)
 - PHP Version : 7.4.4 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox
 - Version : 75.0

**Error Messages**
- Error: This license is currently checked out to a user and cannot be deleted. Please check the license in first, and then try deleting again. 

**Additional context**
- fresh install 
- manual installation : GIT, config etc. in accordance to manual on website
- Creating the DB tables generated an error, but app continued afterwards anyway, had to run php artisan:migrate to get oauth tables for generating API keys else everything seems to work fine.
- No manually data edited in the database

**Comment by xam-ps** [comment]
When you click on the license (on the name or the key) you'll get the overview, to whom (or which access) the license is checked out. Here you can do the checkin.

There reason for that behaviour is: If you have a software with let's say 10 seats and you checkout all 10, how should snipeit know, which of the 10 you want to check in? That's why you have to do it in this "submenu".
