### ISSUE TITLE
Can't login with 2FA enabled if you no longer have access to authenticated device.

### ISSUE THREAD

**Issue by JFord-IDM** [grokability/snipe-it#7966]
#### Expected Behavior (or desired behavior if a feature request)

I had 2FA enabled for my account. I removed 2FA and removed the 2FA account from the Microsoft Authenticator app. I then re-enabled 2FA in Snipe-IT and I would expect to be able to set it back up but it does not take me back to the setup process. Instead, it assumes I still am able to get a code.

-----

#### Actual Behavior

The site takes me to a screen to enter a 2FA token. However, I can't get the token as the app no longer has the account. This would be identical to if you lost a phone or upgraded, etc. How do I actually get to a 2FA setup process in Snipe-IT, again?

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
You have to reset the 2FA status in the user view mode as an admin. If you're locked out of your admin account, create another adsmin account via command line to reset it. 

<img width="915" alt="Screen Shot 2020-04-13 at 12 05 53 PM" src="https://user-images.githubusercontent.com/197404/79151381-2a2afb80-7d7f-11ea-83c2-6f405bafc5ae.png">

**Comment by JFord-IDM** [comment]
Thank you so much. As we allow users to turn 2FA on for themselves at this point I was looking under Edit Profile, where they would presumably look themselves:
![image](https://user-images.githubusercontent.com/56702487/79156269-6c583b00-7d87-11ea-8ceb-9c892a384bb9.png)
But I was able to get it done from the People section. Thanks again!
