### ISSUE TITLE
Asset bulk image upload in one time

### ISSUE THREAD

**Issue by Syntax3rror404** [grokability/snipe-it#7967]
**Server (please complete the following information):**
Docker image: snipe/snipe-it:v4.9.2

**Is your feature request related to a problem? Please describe.**
Yes i think it is a problem, because if i create more assets in one time and i have to upload specific pictures for each asset i must upload every pictures at multiple times. I cant drag and drop (but thats not the problem) i must click upload file, chose the picture and hit upload and for 5 pictures like bezel and keyboard or the bottom site of a laptop i must make this 5 times.
If i chose more pictures at one time i get an error.

**Describe the solution you'd like**
Create the possibility to upload more pictures or other data in one time. (In the explorer tab that opens if you hit the upload buttom)

**Describe alternatives you've considered**
A drag&drop tab that allows me to move the files inside a box. That would be a realy cool feature :)

**Comment by Syntax3rror404** [comment]
Yes it is relevant

**Comment by docdirector-doc** [comment]
Is it possible to have this issue reopened or has it been resolved in another thread that I cannot find?
