### ISSUE TITLE
Restock / Refill of Consumables

### ISSUE THREAD

**Issue by bonitobonita24** [grokability/snipe-it#7968]
- Snipe-IT Version 5
 - OS: [Ubuntu]
 - Web Server: [Apache]
 - PHP Version 7.2

Hi, its my first time to setup and use you snipe-it app. Its nice and the stuff i really need was there. There's only 1 thing that it should be really there specially in Consumable type of asset. I tried to create a consumable type of asset with a quantity of 5 for example, and successfully check it out to one of my fellow users. It deducted the items number of quantity and now i want to try to have a RESTOCK/REFILL of that asset. What's weird is that, i dont know where to add a number of stock to that item which it should be so common thing that happens when you say CONSUMABLE, there's always a REFILL/RESTOCK which i dont understand why the system does not able to do it. Therefore, sadly speaking this system does not meet standard INPUT and OUTPUT of information or data. In every aspect or kind of business, there's always a common THING that restock or resupply. I dont bother not doing it to Asset since its assigned or accountable stuffs, its fine not to refill a stock in asset thats what i mean. But in Consumables, it should be for items regularly having a restock and checkout. I hope this feature be available the soonest since its always been a request by many people who have tested out this system. Thanks

**Comment by berilslv** [comment]
Yes it is, otherwise we need to increase total quantity to increase real stock when another batch of cartridges arrives.

**Comment by 6570** [comment]
Still relevant indeed

**Comment by xulfm** [comment]
still an issue

**Comment by afranchi74** [comment]
any news on this? It is relevant to well manage consumables like toner

**Comment by eraelpeha** [comment]
Would be great to have this feature!
