### ISSUE TITLE
API get hardware by serial

### ISSUE THREAD

**Issue by boring10** [grokability/snipe-it#7979]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The API documentation (4.8.0) states that /hardware/byserial/:serial should return a single object but instead it returns an array with a single object.

Node request with npm package axios.

**To Reproduce**
Node.js get request with axios for a serial number.

**Expected behavior**
Expecting a single object to be returned.

**Server (please complete the following information):**
 - Snipe-IT Version 4.9.2 (hosed version)

**Comment by boring10** [comment]
Never mind, I guess in theory there could be a duplicate serial number.

**Comment by snipe** [comment]
Yes, asset tag must be unique, but serial numbers (especially across multiple types of assets) could potentially be duplicated.
