### ISSUE TITLE
Column not found: 1054 Unknown column '_snipeit_license_subscription_expiration_50' in 'field list'

### ISSUE THREAD

**Issue by Dnatalyaalex** [grokability/snipe-it#7984]
I've upgraded snipe 1 month ago using documentation.
I installed the new version from git, copied the needed files from my old snipe, run database migration, cleared cache. I didn't get any error. 
Now, when I run database migration, I get:

Nothing to migrate

But, when I want to clone/edit/create ->Asset and set Category - license, I get this error.
No problems with other types of asset.  Also I can create New-> License.'
I list my database and saw that I have '_snipeit_license_subscription_expiration_50' column.
But get the error.
Could you please help me?

**Comment by Dnatalyaalex** [comment]
It seems it's a bug in this version.
I found that in the previous version the column _snipeit_license_subscription_expiration_50 are named _snipeit_licensesubscription_expiration_50.

I've just change the name and now it works well.
But I still can't fix the second issue:(

**Comment by mr-kiou** [comment]
updated to 5.0.12 and got the same error...
