### ISSUE TITLE
Suggesting a notes field for locations

### ISSUE THREAD

**Issue by ZhisongZhang** [grokability/snipe-it#7985]
**Server (please complete the following information):**
 - Snipe-IT Version 4.8.0
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.2

**Is your feature request related to a problem? Please describe.**
the feature request is not related to a problem. However, I think the feature will be beneficial to some of use

**Describe the solution you'd like**
a note field for location. as we host our equipment with some of the host partners. some of our partners will have accessing requirements like induction, particular documentation, and/or username passcode to access the site and so forth. having a notes fill on the location will give us a hint on what we should prepare before we get onsite.

**Describe alternatives you've considered**
we are currently placing the information on the location user's note, but users will be coming in and out and we might lose the notes when we remove the user from the location.
example attached below
![werribee sample](https://user-images.githubusercontent.com/5492107/80159949-a939f280-860f-11ea-9aaf-2d5878a43bd7.png)

**Comment by sonicnkt** [comment]
Notes for locations would be nice! just found out this wasnt available. 
It would be a good place to store the vlan configured to the room or available network outlets.

Full custom field options for locations would be another solution but probably way harder to integrate

**Comment by ZBroad** [comment]
+1 on this feature
