### ISSUE TITLE
Fieldset Link from Asset Models page leads to a 404 error page

### ISSUE THREAD

**Issue by jarrodCoombes** [grokability/snipe-it#7986]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When you click on the name of a Field Set on the Asset Models page it leads you to a 404 page. The link generated is <snipe-it>/fieldsets/<id> it should be <snipe-it>/fields/fieldsets/<id>

**To Reproduce**
1. Go to Asset Models
2. Enable the column for 'Fieldset' if it is not on.
3. Click on any link in the `Fieldset` column
4. Look at the sad panda on the 404 page.

**Expected behavior**
The link should take me to the custom fieldset listed in the column.

**Server (please complete the following information):**
 - Snipe-IT Version: 4.9.2
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version: 3.6

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81

**Comment by jarrodCoombes** [comment]
It is still an issue.

**Comment by TonadoWatch** [comment]
I'm also noticing this issue. Seems like I just can't use custom fields? 
![Screenshot 2022-09-20 142038](https://user-images.githubusercontent.com/114029256/191366816-8018be25-29ec-4add-b1f4-e7c4106c1990.png)

**Comment by snipe** [comment]
This was fixed a long time ago. I cannot reproduce it on the demo. https://demo.snipeitapp.com/models

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/models">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by snipe** [comment]
@TonadoWatch I'm not even sure your issue is related to the OP's issue (which is from 2 years and 2 major versions ago). Please open your own issue if you're seeing an issue.
