### ISSUE TITLE
People - Weird column names

### ISSUE THREAD

**Issue by nickjmv** [grokability/snipe-it#7989]
When navigating to the People menu and trying to modify the shown columns I get to see these weird values (see screenshot).

<img width="473" alt="image" src="https://user-images.githubusercontent.com/60742383/80185030-f4520680-860b-11ea-818d-e3710b1baa3b.png">

I have a hosted solution under your management.

**Comment by snipe** [comment]
Hm, that's definitely not right... I'll take a look and see if I can figure out what's going on.

**Comment by pauloriply** [comment]
![image](https://user-images.githubusercontent.com/7813268/80189552-86154000-861b-11ea-9709-d59892b3fc38.png)
Version v4.9.2 - build 4352 (master)

**Comment by snipe** [comment]
@pauloriply It's only happening lower in that menu, where the assets count, licenses count, etc are. It's because we use an icon to represent those in the table, but the javascript that creates the table is barfing on the HTML for the icons. Just not sure how to fix it yet.

**Comment by snipe** [comment]
@nickjmv I think I have a fix for you in this PR: https://github.com/snipe/snipe-it/pull/7993

It's just awaiting code review, and then we can get it merged.

**Comment by snipe** [comment]
@nickjmv I've merged that fix into master. If you want to shoot us an email at support@snipeitapp.com, we'll get your instance updated. (Hard to tell which customer you are with just a Github handle 😉 )

**Comment by bebeto-web** [comment]
![image](https://user-images.githubusercontent.com/81156155/112089193-1e20fe00-8bcc-11eb-9412-31aa0b1b233f.png)

Hi There,

there's any chance to change built-in column from the attached image ? Thanks

**Comment by snipe** [comment]
@bebeto-web Hi there - this issue is closed and doesn't seem directly related to your issue. When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.

There isn't currently a way to change that - and it would be kind of confusing for us to do so, since that's literally what that date is for. If you have a need for a different date, you should consider using custom fields to handle that.

**Comment by bebeto-web** [comment]
@snipe , Thanks for the advice and answering my question. Sorry for the inconvenience. I overlooked the status, 
Sorry I make sure will not happen again.

**Comment by snipe** [comment]
No worries :) I think custom fields will probably do what you're looking for tho. We have a short video tutorial here that sort of breaks them down: https://snipe-it.readme.io/docs/custom-fields

If you think that's not going to work for you, feel free to open a new issue though.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/custom-fields">Custom Fields</a></strong></div><div>Custom fields and fieldsets are available in Snipe-IT versions 2.1.0-pre and later. Custom fields allow you to track additional information about your assets that the default asset attributes don't cover. Check out the short video tutorial below for a full walkthrough:Think of custom fieldsets as co...</div></blockquote>
