### ISSUE TITLE
Snipe-IT Importing error

### ISSUE THREAD

**Issue by william-wy97** [grokability/snipe-it#7991]
At first the processing stuck was due to SMTP. After I fixed the issue, this came up. I got no idea either.
![Screenshot_2020-04-24 Import Snipe_IT](https://user-images.githubusercontent.com/64252602/80192281-f3859880-863c-11ea-84f5-74c13ff761f9.png)

**Comment by tomwellmann** [comment]
I came across this too. Why do I need an SMTP server to impotr licenses from a CSV file? This is absolutely useless, otherwise the importing procedure cannot be finished.

**Comment by tomwellmann** [comment]
This is still happening...
