### ISSUE TITLE
Edit User Group - MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by CLM0055** [grokability/snipe-it#7992]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
edit user group caused MethodNotAllowedHttpException

**To Reproduce**
1. Go to 'admin setting' -> 'group'
2. Create a group with permissions and click save.
3. Edit the same group, adjust the permission and click save again.
4. Error: MethodNotAllowedHttpException

**Server (please complete the following information):**
 - Snipe-IT Version 4.9.2
 - OS: CentOS7
 - Web Server: Apache 2.4
 - PHP Version 7.2.30

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome Browser
 - Chrome Browser Version 81.0.4044.122 (Official Build) (64-bit)

**Error Messages**
(1/1) MethodNotAllowedHttpException
--
in RouteCollection.php line 255
at RouteCollection->methodNotAllowed(array('GET', 'HEAD', 'POST'))in RouteCollection.php line 242
at RouteCollection->getRouteForMethods(object(Request), array('GET', 'HEAD', 'POST'))in RouteCollection.php line 176
at RouteCollection->match(object(Request))in Router.php line 612
at Router->findRoute(object(Request))in Router.php line 601
at Router->dispatchToRoute(object(Request))in Router.php line 590
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in InjectDebugbar.php line 65
at InjectDebugbar->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 63
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HandlePreflight.php line 29
at HandlePreflight->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Additional Information from Browser Dev Tool.**
Request URL: http://192.168.1.130/snipeit/admin/groups?group=1
Request Method: POST
Status Code: 405 Method Not Allowed

**Note:**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Yes, issue can be reproduced in demo: https://snipeitapp.com/demo

**Comment by gkelekov** [comment]
I have this problem as well. Editing groups in any way gives "MethodNotAllowedHttpException" exception. (Snipe-IT Version 4.9.2 on Ubuntu 18.02)

**Comment by mombaerl** [comment]
I have this problem as well. Editing groups in any way gives "MethodNotAllowedHttpException" exception. (Snipe-IT Version 4.9.2 on IIS Windows Server 2012)

**Comment by CLM0055** [comment]
i think it's still important for administrator to be able to edit the existing user group instead of redo.
please fix if possible.

**Comment by ChristophAuch** [comment]
I have this problem as well. (OS: CentOS7 SnipeIT Version: v4.9.2 - build 4352)
