### ISSUE TITLE
Oauth missing Documentation

### ISSUE THREAD

**Issue by Joly0** [grokability/snipe-it#7995]
I tried to find anything about this topic, but except some github questions about this topic, i havent found anything. 

How is it possible to use Oauth in Snipe-IT, newest version.
Unfortunatly, there is no Documentation in the Snipe-IT wiki and i cant find the exact things in need in the laravel wiki (this could be due to thr fact, that i have basically no knowledge over php)

Would still be glad, if this could be explained.

**Comment by snipe** [comment]
There is no documentation because it's not fully implemented. It likely will be after v5 is released.

**Comment by xandfury** [comment]
Hey. :slightly_smiling_face: 

Thanks for snipe-it. Are there any updates as to when the Ouath support will be added?
