### ISSUE TITLE
Snipe-IT v5 Update: April 27, 2020

### ISSUE THREAD

**Issue by snipe** [grokability/snipe-it#7997]
I know v5 is taking a reeeeeally long time. Longer than usual, for sure. For that I'm sorry. I did want to give you some context and an update though. 

The delay is partly because we've had to continue forging ahead on v4 issues the whole time while building v5, sometimes because of urgent customer requests (we have to keep the lights on, right?), sometimes because of security issues resulting from libraries we use, etc. That meant maintaining two very different codebases, which can get pretty tough, especially for a small team. 

We've tried to backport some things (where feasible) into later versions of v4.x, but we're still hard at work on v5. In fact, lest you think we've been sitting on our hands this whole time, you should know we've issued **26 production v4.x releases**, and **several v5-RC releases** since the original v5 update was posted. 

We recently created an integration branch off of master, and merged that into develop, which should put us closer to actually getting this danged this live. It was a pretty messy merge though, with lots of merge conflicts, especially as it relates to CSS files and javascript.

Our current punchlist is:

- [ ] Fix whatever happened to some of the CSS styles and javascript. Select2 looks funny and so do the boxes on the dashboard. I suspect this may be a webpack thing. I'm working on it. 

   - [x] <del>For example, they're rounded corners now, and the dropdown menus work, but they are no longer rich text - I need to fix that, tho I'm not sure exactly why its acting funny.</del>

   - [x] <del>There is a javascript error somewhere in the app.js that doesn't seem to be blocking other things from firing, but it's annoying. Need to track that down</del>

   - [x] <del>I have to check all of the speciality JS (like the password generator, default custom fields for models, etc) that don't show up on every page but only in certain circumstances. I know the dashboard chart is broken currently</del>

   - [x] The help icon + title text + "save" button on some forms looks a little weird. I need to work on the spacing on that

- [x] Fix the LDAP sync. Right now, the new LDAP reworking and test stuff in the Admin Settings is working great, but the sync console command isn't working anymore. Longer term, we'll be upgrading to the *even* newer AD/LDAP library, but we don't want to spend the time jumping right to that when a lot of the new LDAP stuff already works as expected. 

- [x] Either fix or give up on Flysystem. The way Flysystem is currently implemented in later Laravel is... suboptimal. It requires a symlink to move public files to the storage directory, and doesn't allow a lot of flexibility on where to store things in S3 - plus anyone wanting to use S3 will likely want a public bucket and a private bucket, and it's more complicated than it should be. (We've tried for weeks.) We may just try to use native Flysystem, which I assume doesn't try to have an opinion on where files are stored. 

- [x] Possible PHP 7.4 compatibility issues, if not with our own code than possibly with some of the packages we use. 

None of these issues are insurmountable, but I did just want to check in and let you know we're still committed to releasing v5 soon. Once v5 is out, we already have a long list of improvements that come next (custom fields on things other than assets, improved notification preferences, etc.)

No, I cannot give you a timeline for v5. It depends how long it will take to fix these issues. 

For a running list of new features and improvements that are coming in v5, please see #6287.

If anyone's interested in helping us test, you can either check out the develop branch, or just poke around in the develop demo: https://develop.snipeitapp.com (`admin`/`password`). The develop branch automatically deploys to that develop demo whenever we push/merge, so you should always be seeing the latest there.

**Comment by mnemonicly** [comment]
Minor one: looks like a merge issue or half edit in custom_fields/edit.blade.php:78-79 that's causing a render error on editing custom fields.

```
              {{ Form::select("format",$predefinedFormats, $field->getFormatType(), 
              {{ Form::select("format",\App\Helpers\Helper::predefined_formats(), $field->format, array('class'=>'format select2 form-control', 'aria-label'=>'format')) }}
```

**Comment by snipe** [comment]
@dmeltzer fixed, thank you :)

**Comment by snipe** [comment]
I think I mostly fixed the webpack stuff now - man that sucked. Keep that testing coming tho!

**Comment by apizz** [comment]
You're doing great work, @snipe !  👏 for you and all the other contributors

**Comment by mnemonicly** [comment]
api/DepartmentsController has two update methods that differ a little.  I'm not sure which one is newer.

ForgotPasswordsController@sendResetLinkEmail has some weird code at the end of the method that errors.  The comment leaves it unclear exactly what it should do.

**Comment by snipe** [comment]
@dmeltzer I will take a look, thank you! (I've only just started to scratch the surface of going through and testing for weird merge stuff, so I'm not surprised to see some of these pop up.) I've been focused a lot on LDAP and Flysystem, so I appreciate the extra eyes just for clicking around

**Comment by snipe** [comment]
Dumbly, with the latest MacOS upgrade, my diff client that I LOVED doesn't work anymore, so I've been stuck using Kaleidoscope, which looks much prettier, but has screwed me over a few times now. :(

**Comment by snipe** [comment]
> ForgotPasswordsController@sendResetLinkEmail has some weird code at the end of the method that errors. The comment leaves it unclear exactly what it should do.

That should be fixed now

**Comment by itscsquared** [comment]
@snipe Does that mean the LDAP sync issue in current versions is not functioning correctly? I have upgraded PHP on my install and am getting some errors. I can create an issue if need be but was looking for some clarification.

**Comment by samotelf** [comment]
Thank you very much to the wonderful community and @snipe.
I’m sure it will be an awesome release.
I will try to update again to v5 in my pp environment.
Anything I should be focusing on testing for feedback?

**Comment by troveitech** [comment]
Does v5 run with mysql 8? Trying to set it up to test, but running into issues and not sure if that's the problem?

**Comment by travismiller** [comment]
#7682 might be relevant for v5. Happy to contribute if this is something that would be considered.

**Comment by tholu** [comment]
We're looking to adapt Snipe-IT and might be able to contribute to getting this released. Currently testing v4.9.2 and found some bugs there, will check if the are still present in the `develop` branch and submit pull requests from there.

**Comment by 02ms05** [comment]
Is #3286 something we can look forward to?

**Comment by yokhoe** [comment]
Any updates on the v5 release? Will it support RHEL/CentOS 8? Documentation is still listing 7 being supported with the git installer.

**Comment by fenpaws** [comment]
Any updates on implementing #5081?

**Comment by yokhoe** [comment]
Can we get new information on v5's availability?

**Comment by nickjmv** [comment]
Any update on a release date?

**Comment by WifiToaster** [comment]
Can we get an update on the progress towards release please?

**Comment by yokhoe** [comment]
@snipe ^

**Comment by uberbrady** [comment]
We're hoping to have a Release Candidate (RC) out by the end of this month (Aug 31, very soon).

What we are really going to need a *lot* of help with is testing. So much changed in v5, and we want to make sure it works great for everyone. When the RC comes out, the best way to help the release of v5 is to test, as much and as hard as you can, and give us the best bug reports you can give us, so we can get fixes out fast!

**Comment by WifiToaster** [comment]
> We're hoping to have a Release Candidate (RC) out by the end of this month (Aug 31, very soon).
> 
> What we are really going to need a _lot_ of help with is testing. So much changed in v5, and we want to make sure it works great for everyone. When the RC comes out, the best way to help the release of v5 is to test, as much and as hard as you can, and give us the best bug reports you can give us, so we can get fixes out fast!

That is excellent. Thank you for giving an update on the RC for v5. I hope you and the rest of the SnipeIT team have an awesome day. 👍

**Comment by snipe** [comment]
> I hope you and the rest of the SnipeIT team have an awesome day. 👍

TYSM, @WifiToaster! <3 

To add onto what @uberbrady said, the remaining things we have to tackle before we can put out the RC is a few LDAP issues and a few Flysystem (file upload) issues. I feel pretty confident we can meet the end of week deadline though. 

While the entire thing obviously needs to be tested (and we'll be testing extensively on our end too) since so much has changed, LDAP/AD and Flysystem are the main things that were literally rewritten from scratch in v5, so we'd love extra focus on that.

I personally can't WAIT to get v5 out. There's SO MUCH MORE that we want to get done as soon as the major v5 bug fixes are out. As I'm sure I've mentioned elsewhere, having v5 in purgatory has meant our hands have been tied on a lot of fixes/features we've really wanted to push out. We've made a lot of changes to `master` in that time, which of course means the RC merge is going to be hellish), but once everything is merged in and the majority of v5 bugs have been handled, we get to refocus on building out larger features again. I'll put out a more formal roadmap for what comes after v5 as soon as we clear these final few hurdles.

**Comment by fenpaws** [comment]
Thats awesome to hear! Do you guys make list or changelog of what features you added and removed?

**Comment by snipe** [comment]
@fenpaws We've been keeping a general running list [here](https://github.com/snipe/snipe-it/issues/6287), but as always we'll have more specifics in the release notes.

**Comment by fenpaws** [comment]
Ah awesome! I I didn't knew that you update that Post. Thsnks for the info :D

**Comment by snipe** [comment]
v5-beta-3.0.0 is released - https://github.com/snipe/snipe-it/releases/tag/v5.0.0-beta-3.0

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/snipe/snipe-it/releases/tag/v5.0.0-beta-3.0">Release v5.0.0-beta-3.0 · snipe/snipe-it</a></strong></div><div>New from v5.0.0-beta-2 to v5.0.0-beta-3
IMPORTANT: This version of Snipe-IT requires PHP 7.2 or greater
Added

Accessibility features already back ported to v4.9.x
Merge user script already back po...</div></blockquote>

**Comment by yokhoe** [comment]
is RHEL/CentOS 8 not going to be supported in v5?
