### ISSUE TITLE
Installation manual - composer error

### ISSUE THREAD

**Issue by StackAls** [grokability/snipe-it#7998]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Installaton error for fresh manual installation.

**To Reproduce**
step by step
https://snipe-it.readme.io/docs/installation

**Server (please complete the following information):**
CentOS Linux release 7.7.1908 (Core)

[root@sl06200008088 snipe-it]# php -v
PHP 7.2.30 (cli) (built: Apr 15 2020 07:23:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.30, Copyright (c) 1999-2018, by Zend Technologies

**Error Messages**

[root@sl06200008088 snipe-it]# php composer.phar install --no-dev --prefer-source
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 107 installs, 0 updates, 0 removals
  - Installing kylekatarnls/update-helper (1.2.1): Cloning 429be50660
  - Installing symfony/polyfill-util (v1.15.0): Cloning d8e76c1041
  - Installing symfony/polyfill-php56 (v1.15.0): Cloning d51ec491c8
  - Installing symfony/polyfill-ctype (v1.15.0): Cloning 4719fa9c18
  - Installing paragonie/random_compat (v2.0.18): Cloning 0a58ef6e31
  - Installing symfony/polyfill-php70 (v1.15.0): Cloning 2a18e37a48
  - Installing symfony/polyfill-mbstring (v1.15.0): Cloning 81ffd3a9c6
  - Installing symfony/http-foundation (v3.4.39): Cloning a8833c56f6
  - Installing symfony/event-dispatcher (v3.4.39): Cloning 9d4e22943b
  - Installing psr/log (1.1.3): Cloning 0f73288fd1
  - Installing symfony/debug (v3.4.39): Cloning ce9f3b5e8e
  - Installing symfony/http-kernel (v3.4.39): Cloning c15b5acab5
  - Installing vlucas/phpdotenv (v2.6.2): Cloning c4a653ed3f
  - Installing symfony/css-selector (v3.1.10): Cloning 722a87478a
  - Installing tijsverkoyen/css-to-inline-styles (2.2.2): Cloning dda2ee426a
  - Installing symfony/var-dumper (v3.4.39): Cloning 13c03169ae
  - Installing symfony/routing (v3.4.39): Cloning 785e4e6b83
  - Installing symfony/process (v3.4.39): Cloning 1dbc09f6e1
  - Installing symfony/finder (v3.4.39): Cloning 5ec813ccaf
  - Installing symfony/console (v3.4.39): Cloning bf60d5e606
  - Installing symfony/polyfill-php72 (v1.15.0): Cloning 37b0976c78
  - Installing symfony/polyfill-intl-idn (v1.15.0): Cloning 47bd6aa45b
  - Installing symfony/polyfill-iconv (v1.15.0): Cloning ad6d62792b
  - Installing doctrine/lexer (1.0.2): Cloning 1febd6c3ef
  - Installing egulias/email-validator (2.1.17): Cloning ade6887fd9
  - Installing swiftmailer/swiftmailer (v6.2.3): Cloning 149cfdf118
  - Installing ramsey/uuid (3.9.3): Cloning 7e1633a696
  - Installing psr/simple-cache (1.0.1): Cloning 408d5eafb8
  - Installing psr/container (1.0.0): Cloning b7ce3b1764
  - Installing symfony/translation (v3.4.39): Cloning e06ca83b26
  - Installing nesbot/carbon (1.39.1): Cloning 4be0c00516
  - Installing mtdowling/cron-expression (v1.2.3): Cloning 9be552eebc
  - Installing monolog/monolog (1.25.3): Cloning fa82921994
  - Installing league/flysystem (1.0.66): Cloning 021569195e
  - Installing erusev/parsedown (1.7.4): Cloning cb17b6477d
  - Installing doctrine/inflector (1.3.1): Cloning ec3a552422
  - Installing laravel/framework (v5.5.48): Cloning e3e8d585dc
  - Installing asm89/stack-cors (1.3.0): Cloning b9c31def6a
  - Installing barryvdh/laravel-cors (v0.11.4): Cloning 03492f1a3b
  - Installing maximebf/debugbar (v1.16.1): Cloning 58998b818c
  - Installing barryvdh/laravel-debugbar (v3.2.9): Cloning 42d5da5379
  - Installing dasprid/enum (1.0.0): Cloning 631ef6e638
  - Installing doctrine/annotations (1.10.1): Cloning 5eb79f3dbd
  - Installing doctrine/reflection (1.2.1): Cloning 55e71912df
  - Installing doctrine/event-manager (1.1.0): Cloning 6295728199
  - Installing doctrine/collections (v1.5.0): Cloning a01ee38fcd
  - Installing doctrine/cache (1.10.0): Cloning 382e7f4db9
  - Installing doctrine/persistence (1.3.7): Cloning 0af483f91b
  - Installing doctrine/common (2.12.0): Cloning 2053eafdf6
  - Installing doctrine/dbal (v2.9.0): Cloning 21fdabe2fc
  - Installing eduardokum/laravel-mail-auto-embed (1.0.4): Cloning 918c3aff22
  - Installing enshrined/svg-sanitize (0.13.3): Cloning bc66593f25
  - Installing fideloper/proxy (4.3.0): Cloning ec38ad69ee
  - Installing guzzlehttp/promises (v1.3.1): Cloning a59da6cf61
  - Installing ralouphie/getallheaders (3.0.3): Cloning 120b605dfe
  - Installing psr/http-message (1.0.1): Cloning f6561bf28d
  - Installing guzzlehttp/psr7 (1.6.1): Cloning 239400de7a
  - Installing intervention/image (2.5.1): Cloning abbf18d5ab
  - Installing jakub-onderka/php-console-color (v0.2): Cloning d5deaecff5
  - Installing javiereguiluz/easyslugger (v1.0.0): Cloning 11524a3fd7
  - Installing zendframework/zend-diactoros (1.8.7): Cloning a85e67b86e
  - Installing symfony/psr-http-message-bridge (v1.2.0): Cloning 9ab9d71f97
  - Installing phpseclib/phpseclib (2.0.27): Cloning 34620af4df
  - Installing league/event (2.2.0): Cloning d2cc124cf9
  - Installing lcobucci/jwt (3.3.1): Cloning a11ec5f4b4
  - Installing defuse/php-encryption (v2.2.1): Cloning 0f407c43b9
  - Installing league/oauth2-server (6.1.1): Cloning a0cabb573c
  - Installing guzzlehttp/guzzle (6.5.2): Cloning 43ece0e750
  - Installing firebase/php-jwt (v5.2.0): Cloning feb0e820b8
  - Installing laravel/passport (v4.0.3): Cloning 0542f1f82e
  - Installing nikic/php-parser (v4.3.0): Cloning 9a9981c347
  - Installing jakub-onderka/php-console-highlighter (v0.4): Cloning 9f7a229a69
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Cloning 8f8a6e48c5
  - Installing psy/psysh (v0.9.12): Cloning 90da7f3756
  - Installing laravel/tinker (v1.0.10): Cloning ad571aacba
  - Installing laravelcollective/html (v5.5.4): Cloning 04c596a699
  - Installing league/csv (9.5.0): Cloning b348d09d0d
  - Installing maknz/slack (1.7.0): Cloning 7f21fefc70
  - Installing neitanod/forceutf8 (v2.0.4): Cloning c1fbe70bfb
  - Installing paragonie/constant_time_encoding (v2.3.0): Cloning 47a1cedd2e
  - Installing patchwork/utf8 (v1.3.2): Cloning d296e0026e
  - Installing phpdocumentor/reflection-common (2.0.0): Cloning 63a995caa1
  - Installing phpdocumentor/type-resolver (1.0.1): Cloning 2e32a6d489
  - Installing sebastian/recursion-context (3.0.0): Cloning 5b0cd72350
  - Installing sebastian/exporter (3.1.2): Cloning 68609e1261
  - Installing sebastian/diff (2.0.1): Cloning 347c1d8b49
  - Installing sebastian/comparator (2.1.3): Cloning 34369daee4
  - Installing webmozart/assert (1.7.0): Cloning aed98a490f
  - Installing phpdocumentor/reflection-docblock (4.3.4): Cloning da3fd972d6
  - Installing doctrine/instantiator (1.3.0): Cloning ae466f7262
  - Installing phpspec/prophecy (v1.10.3): Cloning 451c3cd141
  - Installing pragmarx/google2fa (v5.0.0): Cloning 17c969c82f
  - Installing bacon/bacon-qr-code (2.0.0): Cloning eaac909da3
  - Installing pragmarx/google2fa-qrcode (v1.0.3): Cloning fd5ff0531a
  - Installing pragmarx/google2fa-laravel (v1.3.3): Cloning ed6e0a9ea1
  - Installing predis/predis (v1.1.1): Cloning f0210e3888
  - Installing rollbar/rollbar (v1.8.1): Cloning 8a57ad9574
  - Installing rollbar/rollbar-laravel (v2.4.3): Cloning e581cd9a17
  - Installing schuppo/password-strength (v1.13): Cloning b1deef216f
  - Installing spatie/temporary-directory (1.1.5): Cloning 539d0856c5
  - Installing spatie/db-dumper (2.13.1): Cloning 8f88e6f772
  - Installing spatie/laravel-backup (5.12.1): Cloning 553562557e
  - Installing tecnickcom/tc-lib-color (1.12.15): Cloning 2f4860cbac
  - Installing tecnickcom/tc-lib-barcode (1.15.20): Cloning dd8de5620e
  - Installing tightenco/ziggy (v0.7.1): Cloning aa4c42aaec
  - Installing unicodeveloper/laravel-password (1.0.3): Cloning c2e532cbbb
  - Installing watson/validating (3.3.0): Cloning 288eb177e9
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Generating optimized autoload files
Deprecation Notice: Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standa                                                                   rd. It will not autoload anymore in Composer v2.0. in phar:///var/www/html/snipe-it/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Http\Transformers\DepartmentsTransformer located in ./app/Http/Transformers/DepartmentsTranformer.php does not comp                                                                   ly with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/html/snipe-it/composer.phar/src/Composer/Au                                                                   toload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Notifications\RequestAssetCancelationNotification located in ./app/Notifications/RequestAssetCancelation.php does n                                                                   ot comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/html/snipe-it/composer.phar/src/Comp                                                                   oser/Autoload/ClassMapGenerator.php:201
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-cors
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: rollbar/rollbar-laravel
Discovered Package: schuppo/password-strength
Discovered Package: spatie/laravel-backup
Discovered Package: tightenco/ziggy
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.

**Comment by snipe** [comment]
Those are notices, not errors. It looks like everything worked as expected.

**Comment by StackAls** [comment]
Sorry - byt no

**Comment by StackAls** [comment]
[Tue Apr 28 12:55:46.584626 2020] [php7:error] [pid 4629] [client 10.62.64.37:63527] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/html/snipeit/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108\nStack trace:\n#0 /var/www/html/snipeit/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/snipeit/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/snipeit/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(Doctrine\\DBAL\\Driver\\PDOException), Array)\n#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(Doctrine\\DBAL\\Driver\\PDOException), Array)\n#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog('error', Object(Doctrine\\DBAL\\Driver\\PDOE in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 664

**Comment by StackAls** [comment]
[root@sl06200008088 conf.d]# ls -l /var/www/html/snipeit/storage/logs/laravel.log
-rwxr-xr-x 1 snipeit apache 3692859 апр 28 11:52 /var/www/html/snipeit/storage/logs/laravel.log
[root@sl06200008088 conf.d]# tail /var/www/html/snipeit/storage/logs/laravel.log
#26 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(403): Illuminate\\Routing\\ResponseFactory->view('errors::500', Array, 500, Array)
#27 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#28 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(187): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#29 /var/www/html/snipe-it/app/Exceptions/Handler.php(93): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))
#30 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))
#31 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))
#32 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))
#33 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#34 {main}
"}

**Comment by StackAls** [comment]
all normal

**Comment by Relix360** [comment]
Hello, do a php -v please and check its not a php 5.4
