### ISSUE TITLE
Fail to install 

### ISSUE THREAD

**Issue by ChristophAuch** [grokability/snipe-it#7999]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
During the installation of our productive environment of SnipeIT we ran into an error in the installation: 
```
ERROR: Invalid composer installer signature
rm: cannot remove 'composer-setup.php No such file or directory
```
after some testing we found out that the reason must be the installation of PHP 7.1 
`error: /etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY: import read failed`

**Server (please complete the following information):**
 - Snipe-IT Version: 4.9.2 
 - OS: centos version CentOS Linux release 7.8.2003 (Core)
 - PHP Version: 7.1 (install skript)

**Comment by snipe** [comment]
That sounds like an issue on the installing computer's side. We don't reference `composer-setup.php` anywhere, but composer does. I'd check the composer docs.
