### ISSUE TITLE
Add checkin/checkout for licenses (users)

### ISSUE THREAD

**Issue by jkour** [grokability/snipe-it#8004]
Hi,
can you please add the ability to checkout licenses to users via the API? This would make the API really useful. Right now it is only for information except for the Assets which looks more complete. 

Then, to reverse the action, checkins via the users should be allowed.

Thanks

**Comment by marcquark** [comment]
there's already an FR for this https://github.com/snipe/snipe-it/issues/6695

**Comment by jkour** [comment]
Thanks I will keep an eye on that
