### ISSUE TITLE
Wrong redirection URL: models to fieldsets

### ISSUE THREAD

**Issue by nickjmv** [grokability/snipe-it#8010]
Hosted solution at your end.

I encountered a problem in the web interface in the models menu.
When trying to click on a value in the Fieldset column from the Asset models view I get redirected to a wrong URL: 
https://XXX.snipe-it.io/fieldsets/5

But when I go directly to my Custom Fieldsets and select the same one I'm trying to reach above the url is:
https://XXX.snipe-it.io/fields/fieldsets/5
note the fields part is present here, which is needed.

**Comment by nickjmv** [comment]
Yes this is still a bug.

**Comment by nickjmv** [comment]
Yes I keep getting redirected to the wrong URL.

**Comment by Subdarub** [comment]
We are also having this issue
