### ISSUE TITLE
[Bug][Translate] In Japanese, first_name is 名 (not 姓)

### ISSUE THREAD

**Issue by sogaoh** [grokability/snipe-it#8014]
---
name: Bug report
about: In Japanese, first_name is `名` (not `姓`) 

---

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
In Japanese, first_name is `名` (not `姓`) 

**To Reproduce**
refs: https://snipe-it.readme.io/docs/docker

1. set `.env` like below:
    ```.env
    
    # Mysql Parameters
    MYSQL_PORT_3306_TCP_ADDR=snipe-mysql
    MYSQL_ROOT_PASSWORD=rootpass
    MYSQL_DATABASE=snipeit
    MYSQL_USER=snipeit
    MYSQL_PASSWORD=snipeitpass
    
    # Email Parameters
    MAIL_PORT_587_TCP_ADDR=smtp.sendgrid.net
    MAIL_PORT_587_TCP_PORT=587
    MAIL_ENV_FROM_ADDR=notify@mydomain.com
    MAIL_ENV_FROM_NAME=notify@mydomain.com
    MAIL_ENV_ENCRYPTION=tcp
    MAIL_ENV_USERNAME=apikey
    MAIL_ENV_PASSWORD=<<my_credential>>
    
    # Snipe-IT Settings
    APP_ENV=development
    APP_DEBUG=true
    APP_KEY=base64:pO45J8nZpZN38P0junFnNMAVkx3rQWJsX+lBba5pBZU=
    APP_URL=http://localhost:3051
    APP_TIMEZONE=Asia/Tokyo
    #APP_TIMEZONE=UTC
    APP_LOCALE=ja
    ```
2. set `docker-compose.yml` like below:
    ```docker-compose.yml
    
    version: '3'
    
    services:
    
      snipe-mysql:
        container_name: snipe-mysql
        image: mysql:8.0
        env_file:
          - ./.env
        volumes:
          - snipesql-vol:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        expose:
          - "3306"
    
      snipe-it:
        container_name: snipe-it
        image: snipe/snipe-it:develop
        env_file:
          - ./.env
        ports:
          - "3051:80"
        depends_on:
          - snipe-mysql
    
    volumes:
      snipesql-vol:
    ```
3. Run `docker-compose up -d` command at `snipe-it` directory
4. Call `http://localhost:3051/` on browser
5. Nothing change on STEP1. Configuration Check (Go to Next)
6. Nothing change on STEP2. Create Database Tables (Go to Next)

**Expected behavior**
Show `名` as `first_name` translated. 

**Screenshots**
![incorrect_translation _first_name_InJapanese_20200503](https://user-images.githubusercontent.com/2090887/80908310-c9795800-8d59-11ea-8a97-509ace3d2c0e.png)

**Server:**
 - Snipe-IT Version : 6.18.10  (uses https://hub.docker.com/r/snipe/snipe-it   Tag:develop)
 - OS: Ubuntu 18.04
 - Web Server: Apache 
 - PHP Version: 7.2(.24) 

**Desktop:**
 - OS: macOS Catalina 10.15.4
 - Browser: chrome 
 - Version: (latest)

**Error Messages**
- (none)

**Additional context**
- (none)

**Comment by sogaoh** [comment]
This problem still recurs today.
Please respond.

Thanks.

![snipe-it_issue8014_2020-07-03_20 56 53](https://user-images.githubusercontent.com/2090887/86467624-ade9f800-bd70-11ea-9bee-746a0e673a71.png)

**Comment by sogaoh** [comment]
This problem still recurs today.
Please respond.

Thanks.

![snipe-it_issue8014_2020-09-05_1518_JST](https://user-images.githubusercontent.com/2090887/92299233-86d7be80-ef8b-11ea-8f24-0ee93eae9a93.png)

**Comment by snipe** [comment]
You are welcome to submit an updated translation via CrowdIn, per our documentation. https://snipe-it.readme.io/docs/translations

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/translations">Translations</a></strong></div><div>Traduci! 翻訳！Oversette! Traduire! 번역하기! แปล! ¡Traducir! Przetłumacz! Übersetzen!</div></blockquote>

**Comment by sogaoh** [comment]
@snipe I can't correct translation. (only vote)
Please update by you.

![i_cant_submit_to_translate_2020-09-06_01-54_JST](https://user-images.githubusercontent.com/2090887/92309874-127d3980-efe4-11ea-852f-fdc5beb7b75e.png)
