### ISSUE TITLE
Bulk Import - 'Checked out to' not Imported

### ISSUE THREAD

**Issue by LordDamocles** [grokability/snipe-it#8020]
#### Please confirm you have done the following before posting your bug report:

- [✓] I have enabled debug mode 
- [✓] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When importing a .csv of assets, the 'Checked Out To' column doesn't carry across - resulting in having to manually check-out items to a user. The predefined users do already exist in the database. and the column does link when the .csv is processed.
![2020-05-05](https://user-images.githubusercontent.com/60053716/81027848-60f7bb80-8ebe-11ea-9433-850917e7dfc2.png)

**To Reproduce**
1. Go to 'Import'
2. Select a spreadsheet with a column for 'Checked out to' and a user defined.
3. Import spreadsheet.
4. Ensure 'Header Field' matches 'Import Field'
5. Import
6. Check asset for user assigned.

**Expected behavior**
When a user is defined in the imported .csv, the user should be assigned to the asset.

**Server (please complete the following information):**
 - Snipe-IT Version **Version v4.9.2 - build 4352 (master)**
 - OS: **Ubuntu 18.04.4 LTS**
 - Web Server: **Apache/2.4.29 (Ubuntu)**
 - PHP Version **PHP 7.2.24**

**Desktop (please complete the following information):**
 - OS: **Windows 10 Pro 64Bit**
 - Browser **Chrome**
 - Version **81.0.4044.129**

**Additional context**
- Is this a fresh install or an upgrade? **Yes, fresh install. First bulk import of assets.**
- What OS and web server you're running Snipe-IT on **Ubuntu 18.04.4 LTS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Fresh install. Users, Companies, Locations, Departments, Categories already configured.**
- Indicate whether or not you've manually edited any data directly in the database **No.**

**Comment by mnemonicly** [comment]
I think that "Checked out to" is a legacy value--It doesn't seem to be used anywhere.  Try mapping your "Checked out to" field of the csv to "username" and see if that works. I'll take a look at the UI and see if I can make this clearer.
