### ISSUE TITLE
Android APP for assets scan

### ISSUE THREAD

**Issue by diegogarciadev** [grokability/snipe-it#8024]
**Server (please complete the following information):**
 - Snipe-IT Version 4.9.2
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.3

**Is your feature request related to a problem? Please describe.**
I'm developing an android app ti scan asset tags and there is no way to get the api token with a user login api request

https://play.google.com/store/apps/details?id=com.diegogarciadev.assetsmanager.snipeit.demo

**Describe the solution you'd like**
It would be fine if I can enter my user and password or a shorter code and get an api response with the token

**Describe alternatives you've considered**

**Additional context**

**Comment by ghost** [comment]
From a security standpoint, wouldn't scanning a QR code, containing the API token, from the website be better than asking for user login? I would imagine something similar to GitHub's personal access token management, where you could generate a new key (possibly with automatic expiring date-time?) and give it a note, would be a great addition and secure.

**Comment by diegogarciadev** [comment]
I was thinking on that but user needs to add a piece of code (probably a js file) with a textarea and a script that generate the qr code, now I'm working in another simple file in php that will be checked from the app (GET or POST request). You'll need to edit that file and put yor api key there. App will save the api key encripted. Then you can delete that file from server.

**Comment by ghost** [comment]
I'd think native integration into Snipe-IT would be a lot better. Might be something that could still fit into v5?

(cc @snipe)

**Comment by diegogarciadev** [comment]
Of course, that's the best option! But meanwhile...

**Comment by apautz22** [comment]
Yes, still relevant
