### ISSUE TITLE
Dose Snipe-IT support LDAPS?

### ISSUE THREAD

**Issue by USP-SIM** [grokability/snipe-it#8042]
Does Snipe-IT support LDAPS as my company will not be using LDAP. If it does support LDAPS, how do I upgrade LDAP to LDAPS in Snipe-IT?

**Comment by diegogarciadev** [comment]
Yes, I'm using LDAPS in my instalation. Just put ldaps:// into LDAP Server field. Yo will need to add CA certificate to your trusted store on your server.

**Comment by USP-SIM** [comment]
Thanks for your prompt reply, will try at our end.
