### ISSUE TITLE
Trying to create a new asset fails with  The asset tag must be unique.

### ISSUE THREAD

**Issue by Statscowski** [grokability/snipe-it#8046]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Trying to create a new asset on a fresh install fails with "The Asset Tag must be unique." 
Auto increment is enabled but it also fails with any Asset Tag i can think of.
The asset table is afterwards empty. I checked.
Debug mode does not throw any exceptions.

**To Reproduce**
1. Go to 'Create new'
2. Click on 'Asset'
3. Enter mandatory information. Anything. (I only created a new model so I can create an asset).

**Expected behavior**
Asset is created

**Screenshots**
Pretty self explanatory. But if wished for, I can provide one.

**Server (please complete the following information):**
 - Snipe-IT Version:  v4.9.2 build 4352 (gec723a3da) 
 - OS: CentOS 8
 - Web Server: Apache
 - PHP Version  7.2.11 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox, Chromium
 - Version 75,  80.0.3987.163 

**Smartphone (please complete the following information):**
Not tried on smartphone

**Error Messages**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.

As a matter of fact, it is reproducible! Recent Bug maybe?

**Additional context**
- Is this a fresh install or an upgrade?: Fresh install
- What OS and web server you're running Snipe-IT on : Centos 8, with Apache
- What method you used to install Snipe-IT: manual installation, pulled from Git
- Include what you've done so far in the installation, and if you got any error messages along the way: Not much. Fresh install
- Indicate whether or not you've manually edited any data directly in the database: I have not

**Comment by RWatson0412** [comment]
I don't have a solution for you but I'm seeing the same problem under nearly identical circumstances. I've got SnipeIT on Ubuntu Server 18.04 and have gotten the error in Firefox and Chrome in Windows 10 and Firefox on Android. Other than that, my answers would've been the exact same.

**Comment by Lari0** [comment]
I have same issue under Ubuntu Server 18.04 , fresh install

**Comment by fozkan** [comment]
I have the same issue with docker container (latest tag -4.9.2-). Then I tested creating a new asset in snipe-IT live demo and the problem exists there too. I installed v4.9.0 and everything is normal now.

**Comment by Statscowski** [comment]
Thanks for the tip @fozkan .
For anyone else who also installed from git - this should work while we wait for the bug to get solved:

`git checkout tags/v4.9.0`

**Comment by gitthismoney** [comment]
got this as well this morning

**Comment by keiner99** [comment]
same problem. updated from 4.8.0 to 4.9.2

**Comment by Zimerhonzl** [comment]
I'm not extremely familiar with git.  When I try to run git checkout, it lists files it will overwrite then aborts.  My setup is almost identical to above, running Debian though.  Fresh install.  Any suggestions?

**Comment by mikeyz24** [comment]
I also have same issue after upgrading to 4.9.2

**Comment by markmo123** [comment]
Same issue here, updated from 4.9.0 to 4.9.2 on Centos 8 via git.

**Comment by tony-vi** [comment]
I have the same issue when I change the Status of an asset.

Error: "The asset tag must be unique."

v 4.9.2

**Comment by mikeyz24** [comment]
If you go back to v4.9.0 this bug goes away by doing `git checkout tags/v4.9.0`

If you want to stay on v4.9.2 what I did was edit the /app/Http/Requests/AssetRequest.php file and comment out line 34:
`//'asset_tag'       => 'required|min:1|max:255|unique_undeleted',`

I'm pretty sure this isn't the official fix but it works for me, for now, until a new release comes out.

**Comment by gitthismoney** [comment]
cant add any assets until this is fixed... appreciate the eyes on this one it's a bit of a show stopper
cheers,

**Comment by markmo123** [comment]
> cant add any assets until this is fixed... appreciate the eyes on this one it's a bit of a show stopper
> cheers,

I did another git pull via php upgrade.php that gave me a different build of 4.9.2 that fixed this issue.

**Comment by gitthismoney** [comment]
thanks! just tried and all good. much apprecaited!

**Comment by zapgods** [comment]
> 
> 
> Thanks for the tip @fozkan .
> For anyone else who also installed from git - this should work while we wait for the bug to get solved:
> 
> `git checkout tags/v4.9.0`

@snipeit>git checkout -b tags/4.9.0 <<it's solved for me. T-T
