### ISSUE TITLE
Bind AzureAD/Secure LDAP in SnipeIT

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#8047]
Hey guys, 

I am trying to integrate my AzureAD/Secure LDAP with SnipeIT. I found a ticket for it here and tried to orientate myself on it. But unfortunately it did not work. Is there anybody here who has made it and if so, how?

I also uploaded the configurations.
![Screenshot 2020-05-12 at 17 44 57](https://user-images.githubusercontent.com/54666249/81715757-de03d180-9478-11ea-8652-eb696faec2b5.png)
![Screenshot 2020-05-12 at 17 45 47](https://user-images.githubusercontent.com/54666249/81715762-df34fe80-9478-11ea-89cf-5ef75dd9772e.png)

i hope you can help me

**Comment by tholu** [comment]
@nebi52 Have you found a working config?
