### ISSUE TITLE
How do I limit columns displayed for users

### ISSUE THREAD

**Issue by joe2725** [grokability/snipe-it#8050]
**Server (please complete the following information):**
 - Snipe-IT Version =  v4.8.0 build 4186 (g893454dca)
 - OS: [e.g. Ubuntu, CentOS] Windows server 
 - PHP Version = 7.4.3

**Is your feature request related to a problem? Please describe.**
It's not related to any issue. I know there is a selection of columns users can chose from to display  but I don't see a way to limit that choice or I just have not found it yet on how to limit that selection of columns "by default" for users with no admin permissions. i.e I don't want "Purchases Cost, ...etc to be a choice of columns to be displayed for all users (for example with "View" only permissions). If there is one, please point me to it if none then is there any work around and would this be considered as feature request?  Thank you. 

**Describe the solution you'd like**
Be able to limit columns choices to non-admin users

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
That's not possible at this time, and it's unlikely to be implemented any time soon.

**Comment by joe2725** [comment]
Thank you for your response - I was hoping for a way to do it or at least be considered as a feature request.
