### ISSUE TITLE
Error: in pdoconnection.php line 24 parse error syntax error unexpected ' ' expecting variable (t_variable)

### ISSUE THREAD

**Issue by andreasoc** [grokability/snipe-it#8052]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am trying to update from version 4.6.6 to version 4.9.2 but at the time of launching the "php artisan migrate" command, I receive this error from which I cannot get out of it.
"in pdoconnection.php line 24 parse error syntax error unexpected '' expecting variable (t_variable)"
I have looked at many articles around, I have updated php to version 7.3.18 but nothing changes nothing.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2852354/81825477-00f4bb00-9537-11ea-80a5-282e33ade089.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.6
 - OS: [Windows Server 2012 R2]
 - Web Server: [Apache 2.4.27]
 - PHP Version 7.3.18

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? UPGRADE
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **MANUAL**
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **Never**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by andreasoc** [comment]
I tried the update but this time in intermediate steps, from 4.6.6 to 4.6.18 everything perfect, I tried from 4.6.18 to 4.7, which is the first version that requires php 7.1.3 and gives the same error.
Before updating from 4.6.18 to 4.7 I swapped the version of php on my wampserver to 7.1.9 from 7.0.23.
BUT! if go to snipe with chrome, work fine and the version is 4.7 updated

**Comment by andreasoc** [comment]
After that i tried to install the 4.8, same php version , but the same error ..
**in PDOconnection.php line 24 :
Parse error: syntax error,  unexpected '? ',  expecting variable (T_VARIABLE)**

but this time snipe isn't working, and chrome tells me
**Whoops, looks like something went wrong.**

**Comment by andreasoc** [comment]
![image](https://user-images.githubusercontent.com/2852354/81835608-bbd68600-9542-11ea-81c8-fe2f5e7ace07.png)
difference between the first one (snipe ver. 4..8 ) and 4.6.18 fo file PDOConnection.php.. 
if I remove the "$" symbol
receive others error
![image](https://user-images.githubusercontent.com/2852354/81835838-ff30f480-9542-11ea-9434-fc0dfae1cfd6.png)

**Comment by snipe** [comment]
Never, ever change vendor files. The changes will be blown out the next time you update. 

On the command line, when you run `php -v`, what does it say?

This is 100% a PHP version issue. PHP has two different versions, a web server module and a command line module. Running the web server module in PHP 7.1.x doesn't mean the command line is running the same version. https://snipe-it.readme.io/docs/installation-issues#php-version-issues

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#php-version-issues">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by andreasoc** [comment]
In the web server i created a page For phpinfo and i see the right version. If run a command php - - version i see the old php version.. 7.0.x but i don't know how to update this.. IS composer installer?
Thanks

**Comment by andreasoc** [comment]
> Never, ever change vendor files. The changes will be blown out the next time you update.
> 
> On the command line, when you run `php -v`, what does it say?
> 
> This is 100% a PHP version issue. PHP has two different versions, a web server module and a command line module. Running the web server module in PHP 7.1.x doesn't mean the command line is running the same version. https://snipe-it.readme.io/docs/installation-issues#php-version-issues
> 
> > <img alt="" width="48" src="/favicon.ico">Snipe-IT Documentation**[Installation/Upgrading Issues](https://snipe-it.readme.io/docs/installation-issues#php-version-issues)**Common installation/upgrading issues and solutions

Hi
thanks for explanation. The problem was the php in my Windows Server that needed updating, after download composer installer for Windows, launch setup, select the php version 7.1.9( the same of WAMPP) all work fine and solved the problem.
thanks
![image](https://user-images.githubusercontent.com/2852354/81922702-c5143100-95dc-11ea-813f-06d11e607258.png)


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#php-version-issues">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>
