### ISSUE TITLE
SMTP - no debug information being posted/No Log

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#8064]
I have debug enabled, smtp settings configured, cleared cache, do a password reset, tells me whoops something with wrong with no debug output
or nothing updated in the log file
wondering if anyone can help out, been stuck with this issue for months :(

Im on W10 running the latest Snipe-IT Version
https://files.gitter.im/snipe/snipe-it/Epzh/image.png
https://files.gitter.im/snipe/snipe-it/Th8V/image.png

**Comment by snipe** [comment]
First, change your APP_ENV to `develop`, otherwise you're going to get a big red warning on your app if debug mode is enabled.

Next, make sure the `storage` directory (and ALL subdirectories) is writable by the web server. The only reason the log would be empty would be if it can't be written to.

**Comment by ghost** [comment]
I can see it's writing in the log file but nothing to due with SMTP

**Comment by snipe** [comment]
That kinda doesn't make any sense tho - a "whoops" error is inherently a Laravel error, so it should show up in your app log in `storage/logs/laravel.log`. You can make check your system's PHP log to see if it's crashing out somewhere before the app logging happens.

Also make sure to dump your config cache. `php artisan config:clear`

**Comment by snipe** [comment]
(You'd be seeing errors related to Swift or Swiftmailer if the log is related to mailing)

**Comment by ghost** [comment]
I did the following

php artisan config:clear
php artisan config:cache

restarted server, reset password, whoops error, nothing in the logs, but it logs everything else.

**Comment by snipe** [comment]
And your php error log?

**Comment by ggill24** [comment]
DO you know where that would be?

**Comment by ghost** [comment]
ok nevermind found it xampp -> php

There's no logs.
