### ISSUE TITLE
API /maintenance not working

### ISSUE THREAD

**Issue by diegogarciadev** [grokability/snipe-it#8066]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
You can list all maintenances but you can't add a new maintenance to an asset

**To Reproduce**
1. Go to https://snipe-it.readme.io/reference#maintenances-1
2. Enter something as name (only mandatory field)
3. Click on Try it
4. You will see {
"status":"error"
"messages":"You cannot add a maintenance for that asset"
"payload":NULL
}

**Expected behavior**
New maintenance added to asset

**Screenshots**
Not applicable.

**Server (please complete the following information):**
Online API reference

**Desktop (please complete the following information):**
Not client related

**Smartphone (please complete the following information):**
Not device related

**Error Messages**
{
"status":"error"
"messages":"You cannot add a maintenance for that asset"
"payload":NULL
}

**Additional context**
Request data:
curl --request POST \
  --url https://develop.snipeitapp.com/api/v1/maintenances \
  --header 'accept: application/json' \
  --header 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImVmMGVhY2Y4MjAyYzgwZWI2M2JkNmIwZDc0OGYwY2FkYzU2Y2ZlMzgyNzY4ODY0N2EwNmU4ZTBlNmYwZDgwODNjZmMyMzI2YWYyYTZlMTFkIn0.eyJhdWQiOiIxIiwianRpIjoiZWYwZWFjZjgyMDJjODBlYjYzYmQ2YjBkNzQ4ZjBjYWRjNTZjZmUzODI3Njg4NjQ3YTA2ZThlMGU2ZjBkODA4M2NmYzIzMjZhZjJhNmUxMWQiLCJpYXQiOjE0OTMzMzI2MjgsIm5iZiI6MTQ5MzMzMjYyOCwiZXhwIjoxODA4ODY1NDI4LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.NU7ZRIt-d4b0o8uv9ipo1vSWcg1svbmPp47kHErafm9iuK4FjygKd2_4Hp73HKAmjiYcEn3r39pwNh2t9BMFnTXv0KeDGC8zfZ9z7OJN_a59LPoarWBFzCsYETyAm-CeeFnfdj9Cr0ZeGOnnaPuWPYxicwKFeqJI4Hn8nCymcamDGE0u4WOO95ihGOAen4_fqpj-kkBDsvsGhB-cQxeuKdlbvO1yOsKmgQv-kQuxiFMn1zgU7P02mC6XXrbw6jTm7JOaBSbvqSwNtsrSKZkim1jxLsQ4dm36lFmeMkU6hZvNSUnxg8JwbmoxQ_3tZlG3IJh3Sc9ZUi-AEAQ4bbGzi_xNS9fenIdzLDaSiv_esYyNOYXqOuSBk8Yr-720N9OcVjGLnPrV3RtmPisV1aLFgKWLImtlyQgUq3d5LA3QXz8Q_8isvO9Am1u8ri2plbHGJLJ6GRW_mYcBEYMwUozaeXTUe_FUSSO8gpGtO9Hpa5SbERY272_tojyVXpYPaPdUYYmS9CP332jBNESPT8wGwpOM-iddeVo_n82w3dHmDEdp1Brbs3_vKk0AcgvDLsAbd4dZZO-UqddVx6SDb3HLw1Pmw1wGGYHA6w8wWQAiS9kg2xMcz5i75HOULaN3miqYvcPCvHpI2CBfuvdplI8QNm_XzFPmoQRu_5kR8knzla4' \
  --header 'content-type: application/json' \
  --data '{"name":"example_name"}'

**Comment by tonydew** [comment]
I just let a suggested correction for the docs. It appears that the params are for `/locations` not `/maintenances`?

**Comment by diegogarciadev** [comment]
Yes, maybe you're right...

**Comment by diegogarciadev** [comment]
I've discovered some things:

You can get all device maintenances with:
`GET https://develop.snipeitapp.com/api/v1/maintenances?asset_id={asset_id}`

I'm near the answer about create a maintenance:
`POST https://develop.snipeitapp.com/api/v1/maintenances?asset_id={asset_id}`

The response for this test body: `{"title":"test_data"}`

{
    "status": "error",
    "messages": {
        "supplier_id": [
            "The supplier id field is required."
        ],
        "asset_maintenance_type": [
            "The asset maintenance type field is required."
        ],
        "title": [
            "The title field is required."
        ],
        "start_date": [
            "The start date field is required."
        ]
    },
    "payload": null
}

**Comment by diegogarciadev** [comment]
I have discovered the "solution" surfing the app code, and there ir a mistake @snipe. The app is getting the params for a new maintenance from url params in a `POST Request`. Dou you have planned to fix it?:

`POST 'https://develop.snipeitapp.com/api/v1/maintenances?asset_id=1373&supplier_id=4&asset_maintenance_type=Upgrade&title=EnGETData&start_date=2020-05-24`

{
    "status": "success",
    "messages": "Asset Maintenance created successfully.",
    "payload": {
        "supplier_id": "4",
        "is_warranty": 0,
        "cost": null,
        "notes": null,
        "asset_id": "1373",
        "asset_maintenance_type": "Upgrade",
        "title": "EnGETData",
        "start_date": "2020-05-24 00:00:00",
        "completion_date": null,
        "user_id": 2,
        "updated_at": "2020-05-28 00:58:49",
        "created_at": "2020-05-28 00:58:49",
        "id": 55
    }
}

**Comment by diegogarciadev** [comment]
I've the methods to get an asset's maintenances, create a new one or update an existing.

I've not discovered how to delete a maintenance.

Help is apreciated

**Comment by diegogarciadev** [comment]
I've the solution:

`DELETE 'https://develop.snipeitapp.com/api/v1/maintenances/68'`

_68 is the maintenance id_

So, maintenances endpoint is working now.
