### ISSUE TITLE
Wrong Portuguese translation in the "Log in" button

### ISSUE THREAD

**Issue by lmsmartins** [grokability/snipe-it#8073]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
There's a wrong translation in the "Login in" button for the Portuguese language.
It should be "Iniciar sessão" instead of "Nome de registo". "Nome de registo" actually means "Name of registration".

**To Reproduce**
1. Log in and select the Portuguese language in the "Localization" settings or change it in your profile.
2. Log out and check that the "Log in" button shows the wrong translation in Portuguese. It should be "Iniciar sessão" instead of "Log in".

**Expected behavior**
The "Log in" button in Portuguese should have been "Iniciar sessão" instead of "Nome de registo".

**Screenshots**
![translation_bug](https://user-images.githubusercontent.com/8367143/82677312-53209500-9c37-11ea-8b5e-06035bce9eed.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version: 4.9.2
 - OS: Windows Server 2012 R2
 - Web Server: Apache
 - PHP Version: 7.4.2

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 81

**Comment by mnemonicly** [comment]
Thanks.  Snipe-it uses [crowdin](https://crowdin.com/translate/snipe-it) for translations.  It appears that this has already been suggested as a correction there, I suspect when translations get merged in for the next release you should see it fixed.

In the future if you find other translation issues, feel free to suggest improvements on crowd-in, it's the simplest way to track things!

**Comment by lmsmartins** [comment]
Thanks. 👍
