### ISSUE TITLE
The result could not be loaded

### ISSUE THREAD

**Issue by letran3691** [grokability/snipe-it#8090]
I don't know why  when  click to dropdown it's display field for  choose, but moment after "loading more results". It's return "The result could not be loaded". 
I has try https://snipe-it.readme.io/docs/common-issues , but not anythings change

i don't see new error today, only see old error
https://paste.ofcode.org/QwrQBQT4PaqAGLdmE9BQxB

full log lavavel
https://paste.ofcode.org/394MYEQPktKqgZrtduSfeAr

debug console chrome 
GET http://xxxxxx:8800/api/v1/users/selectlist?page=121 405 (Method Not Allowed)
![image](https://user-images.githubusercontent.com/19284401/83099054-6370be00-a0d6-11ea-9e00-d319df14aa87.png)

full log console chrome 
https://paste.ofcode.org/rnQJbbs9tPhj5LkE9PP7c5

i don't  know this is  bug or my config error. Please help me. Thank very much.
 - Snipe-IT  Version v4.9.2 - build 4352
 - OS:  CentOS 7
 - Web Server: Apache 2.4.6
 - PHP Version : 7.2.31

![bandicam-2020-05-27-15-58-34-942-_online-video-cutter com__4](https://user-images.githubusercontent.com/19284401/83006070-de38cb00-a03b-11ea-8411-eca1e79993ce.gif)

A issue i'm new detect, when delete a Manufacturer, after insert  a Manufacturer  similar, it's return name "already "
![image](https://user-images.githubusercontent.com/19284401/83089852-9197d300-a0c1-11ea-8846-92e43abd04ce.png)

**Comment by mnemonicly** [comment]
Hello,

By default, snipe-it "soft-deletes" items.  This makes them disappear from view, but still keeps the information in the database for later restoring.  If you go to the manufacturers admin page you'll see a "Show deleted" button in the top right that will allow you to restore it.

If you want to fully delete it, you can purge your soft deleted items.  See https://snipe-it.readme.io/docs/purging-soft-deletes page for further information.
