### ISSUE TITLE
API Key generation error

### ISSUE THREAD

**Issue by wfrederic02** [grokability/snipe-it#8091]
#### Expected Behavior (or desired behavior if a feature request)

Generate API key

-----

#### Actual Behavior

I am unable to generate a new token under the Personal API Keys page 
When I try to create a token I get the following error "Whoops! Something went wrong! server Error".
With the command line: **php artisan passport:client --personal** I got this:

"In Connection.php line 664:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist (SQL: insert into `
  oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `u
  pdated_at`, `created_at`) values (, Test, m735ZDL9CAAA0CmDYAGoSppDxMpPXvIAVzUSrjtm, http://localhost, 1, 0, 0, 2020
  -05-27 13:03:33, 2020-05-27 13:03:33))

In PDOConnection.php line 63:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist

In PDOConnection.php line 61:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist"

*
*
*

If I use the command line **php artisan migrate** to create missing tables I have this error message:

In Connection.php line 664:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`
  id` int unsigned not null auto_increment primary key, `email` varchar(191) not null, `password` varchar(191) not nu
  ll, `permissions` text null, `activated` tinyint(1) not null default '0', `activation_code` varchar(191) null, `act
  ivated_at` timestamp null, `last_login` timestamp null, `persist_code` varchar(191) null, `reset_password_code` var
  char(191) null, `first_name` varchar(191) null, `last_name` varchar(191) null, `created_at` timestamp null, `update
  d_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)

In PDOStatement.php line 119:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists

In PDOStatement.php line 117:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists

*
*
*
**And when I try to create an API Token in debug mode I have this:**

Whoops! Something went wrong!

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_personal_access_clients' doesn't exist (SQL: select * from `oauth_personal_access_clients` order by `id` desc limit 1) 
Illuminate\Database\QueryException 
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php 
664 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php", "line": 624, "function": "runQueryCallback", "class": "Illuminate\\Database\\Connection", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php", "line": 333, "function": "run", "class": "Illuminate\\Database\\Connection", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php", "line": 1719, "function": "select", "class": "Illuminate\\Database\\Connection", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php", "line": 1704, "function": "runSelect", "class": "Illuminate\\Database\\Query\\Builder", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php", "line": 481, "function": "get", "class": "Illuminate\\Database\\Query\\Builder", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php", "line": 465, "function": "getModels", "class": "Illuminate\\Database\\Eloquent\\Builder", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\BuildsQueries.php", "line": 77, "function": "get", "class": "Illuminate\\Database\\Eloquent\\Builder", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\passport\\src\\ClientRepository.php", "line": 81, "function": "first", "class": "Illuminate\\Database\\Eloquent\\Builder", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\passport\\src\\PersonalAccessTokenFactory.php", "line": 71, "function": "personalAccessClient", "class": "Laravel\\Passport\\ClientRepository", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\passport\\src\\HasApiTokens.php", "line": 67, "function": "make", "class": "Laravel\\Passport\\PersonalAccessTokenFactory", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\passport\\src\\Http\\Controllers\\PersonalAccessTokenController.php", "line": 70, "function": "createToken", "class": "App\\Models\\User", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php", "line": 48, "function": "store", "class": "Laravel\\Passport\\Http\\Controllers\\PersonalAccessTokenController", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php", "line": 212, "function": "dispatch", "class": "Illuminate\\Routing\\ControllerDispatcher", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php", "line": 169, "function": "runController", "class": "Illuminate\\Routing\\Route", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", "line": 658, "function": "run", "class": "Illuminate\\Routing\\Route", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 30, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Router", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php", "line": 43, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Auth\\Middleware\\Authenticate", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php", "line": 49, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\CheckForTwoFactor.php", "line": 49, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\CheckForTwoFactor", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\CheckLocale.php", "line": 42, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\CheckLocale", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php", "line": 68, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php", "line": 37, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php", "line": 66, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 102, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", "line": 660, "function": "then", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", "line": 635, "function": "runRouteWithinStack", "class": "Illuminate\\Routing\\Router", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", "line": 601, "function": "runRoute", "class": "Illuminate\\Routing\\Router", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", "line": 590, "function": "dispatchToRoute", "class": "Illuminate\\Routing\\Router", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php", "line": 176, "function": "dispatch", "class": "Illuminate\\Routing\\Router", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 30, "function": "Illuminate\\Foundation\\Http\\{closure}", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php", "line": 65, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Barryvdh\\Debugbar\\Middleware\\InjectDebugbar", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php", "line": 30, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\CheckForDebug.php", "line": 25, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\CheckForDebug", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\CheckForSetup.php", "line": 27, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\CheckForSetup", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\fideloper\\proxy\\src\\TrustProxies.php", "line": 57, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Fideloper\\Proxy\\TrustProxies", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\NosniffGuard.php", "line": 17, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\NosniffGuard", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\ContentSecurityPolicyHeader.php", "line": 18, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\ContentSecurityPolicyHeader", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\ReferrerPolicyHeader.php", "line": 17, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\ReferrerPolicyHeader", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\XssProtectHeader.php", "line": 18, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\XssProtectHeader", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\FrameGuard.php", "line": 17, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\FrameGuard", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php", "line": 49, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php", "line": 63, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Session\\Middleware\\StartSession", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php", "line": 46, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\barryvdh\\laravel-cors\\src\\HandlePreflight.php", "line": 29, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Barryvdh\\Cors\\HandlePreflight", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 102, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php", "line": 151, "function": "then", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php", "line": 116, "function": "sendRequestThroughRouter", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" } 
{ "file": "C:\\inetpub\\wwwroot\\snipe-it\\public\\index.php", "line": 58, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" } 
-----

#### Please confirm you have done the following before posting your bug report:

- [*] I have enabled debug mode 
- [*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running: v4.7.7 build 4160 (gb8f7cd81e)
- Version of PHP you're running: 7.3.10
- Version of MySQL/MariaDB you're running: MariaDB 10.2.0.5599
- What OS and web server you're running Snipe-IT on Windows Server 2016 Standard
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: http://inventory.corp.*******.com/account/api -> Create New Token
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Not available on the demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by mnemonicly** [comment]
Have you run `php artisan passport:install` ?

**Comment by wfrederic02** [comment]
> Have you run `php artisan passport:install` ?

I think yes because when I try to run it I have this message:

Encryption keys already exist. Use the --force option to overwrite them.

In Connection.php line 664:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist (SQL: insert into `
  oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `u
  pdated_at`, `created_at`) values (, Snipe-IT Personal Access Client, YcpvzqFdeFWQrZKt9CcUBKyscmQvNKDigVfIMhq8, http
  ://localhost, 1, 0, 0, 2020-05-28 16:12:30, 2020-05-28 16:12:30))


In PDOConnection.php line 63:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist


In PDOConnection.php line 61:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist

**Comment by Relix360** [comment]
Im having the same issue
 `[root@InventarioIT snipeit]# php artisan passport:install --force
Encryption keys generated successfully.

In Connection.php line 664:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist (SQL: inse
  rt into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_clie
  nt`, `revoked`, `updated_at`, `created_at`) values (, Snipe-IT Personal Access Client, yKlzMK5NZ4Iu663oZQE
  MnYQJ4xV9M4D5N8280a6U, http://localhost, 1, 0, 0, 2020-06-17 12:23:33, 2020-06-17 12:23:33))


In PDOConnection.php line 63:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist


In PDOConnection.php line 61:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist

`
