### ISSUE TITLE
Create Asset Model - Cannot Select Manufacturer or Category Name

### ISSUE THREAD

**Issue by markstahler** [grokability/snipe-it#8092]
I installed a brand new v4.9.2 - build 4352 but am having trouble on the Create Asset Model page. I have manually created Manufacturers and Categories but when I attempt to select them on the page they appear temporarily and then disappear after a Javascript error.

Please see the attached screen capture. There seems to be an error in the form as it calls a selectlist function but loops indefinitely until the server will no longer respond after 121 requests.

**Server**
 - Snipe-IT Version - v4.9.2 - build 4352
 - OS: Windows 10 host - using official Docker image with MySql 5.6
 - Web Server: Docker Apache
 - PHP Version - whatever is in the Docker image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 76.0.1 and Microsoft Edge 83.0.478.37 (AdBlocker disabled)

![2020-05-27_150034](https://user-images.githubusercontent.com/108578/83062062-07515f80-a02c-11ea-8b7f-7e74d6530ba6.png)

**Comment by YoBii** [comment]
I face the same issue. Check your browser console. I think you will see a lot of warning regarding your browser dropping the session cookie due to **samesite=none** and **secure=none**. 
That somehow seems to cause a loop of incrementing requests until you'll receive an HTTP 429 due to the API throttle limit at 120 requests/min.

**Comment by mnemonicly** [comment]
The selectlist continually reloading is a separate issue.  The pagination is broken in the code.  Do you have any server side errors?

**Comment by markstahler** [comment]
@dmeltzer I confirmed by reviewing the logs, there is nothing at all in the apache error.log and nothing unexpected in access.log, just a confirmation of the HTTP 405 error in the screenshot above.

**Comment by vorsoth100** [comment]
I'm experiencing the same issue. Been trying a lot of things, but haven't been able to figure it out yet.

**Comment by YoBii** [comment]
I was able to circumvent the problem by using the following hack fix:
https://github.com/snipe/snipe-it/issues/8035#issuecomment-627836006

When using docker you have to change the file `/var/www/html/public/js/dist/all.js` inside your docker container

**Comment by vorsoth100** [comment]
Looks like that fix worked! I just installed it on an Ubuntu VM, so the `all.js` file was in `/var/www/snipeit/public/js/dist` on my system. 

Thanks, YoBii!

**Comment by coaxke** [comment]
This has been fixed by https://github.com/snipe/snipe-it/pull/8227
