### ISSUE TITLE
Web Interface Throwing Exception on Backup

### ISSUE THREAD

**Issue by dognation** [grokability/snipe-it#8093]
#### Expected Behavior (or desired behavior if a feature request)

Expecting to get a successful backup show up in the Backup File Listing.

-----

#### Actual Behavior

I receive a red Whoops message at the top of the Backup screen and I receive an email with the attached syntax.
[whoops.txt](https://github.com/snipe/snipe-it/files/4691595/whoops.txt)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh
- Version of Snipe-IT you're running: 4.9.2
- Version of PHP you're running: 4.3.18
- Version of MySQL/MariaDB you're running: 10.2.32
- What OS and web server you're running Snipe-IT on: Win 2019 Std IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual followed youtube instruction
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Admin | Backup
I can get the backup to run successful via command lines:
cd \Inetpub\wwwroot\snipe-it
php artisan snipeit:backup

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.:
The following in red:
Error: Backup failed because The dump process failed with exitcode 1 : General error : . #0 C:\inetpub\wwwroot\snipe-it\vendor\spatie\db-dumper\src\DbDumper.php(246): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 C:\inetpub\wwwroot\snipe-it\vendor\spatie\db-dumper\src\Databases\MySql.php(148): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'C:\\inetpub\\wwwr

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
my database is empty

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by mhirst1992** [comment]
I have the exact same issue - cmd line php artisan snipeit:backup works fine, but I get the same error when trying through the site.

**Comment by BornToBeRoot** [comment]
Fresh install with docker-compose

Same error on the webinterface...

and on the command line i get this:

```
#  php artisan snipeit:backup
Starting backup...

In DbDumper.php line 117:
  Type error: Argument 1 passed to Spatie\DbDumper\DbDumper::setPort() must be of the type integer, string given, called in /var/www/html/vendor/spatie/larav
  ry.php on line 36

#
```
