### ISSUE TITLE
White page when trying to access webapp also i have no idea how to do the fire wall either =(

### ISSUE THREAD

**Issue by Doggolover69** [grokability/snipe-it#8099]
I am trying to install snipe-it using wamp server howver i can't for the life of me find where i am suppost to put my public directory or where document root is. I found a document root in httb.conf however changing this didn't fix the problem and i have no idea what to take as a next step.

**Comment by Doggolover69** [comment]
I now have it working however when i go to the address that i set in the instructions it is just a white page.

**Comment by Chrona00** [comment]
Howe did you finally install it? I'm also stuck at the white page.
