### ISSUE TITLE
Fieldsets being applied to Licenses

### ISSUE THREAD

**Issue by TinaMccray** [grokability/snipe-it#8102]
**Server (please complete the following information):**
 - Snipe-IT Version 4.9.2
 - OS: Windows Server 2019
 - Web Server: IIS web server
 - PHP Version 7.3.13

**Is your feature request related to a problem? Please describe.**
The Licenses do not have enough fields for me. I need to track some other information like a customer number, site number, Download site or Order Level etc......

I would also like to be able to put a picture of the scanned contract for some.  

**Describe the solution you'd like**
I would like to be able to create custom fields and apply them to my licenses. It is fine if I have to apply them to all the licenses, I can leave it blank if it doesn't apply to that license. 

**Describe alternatives you've considered**
currently I am putting all the information in the notes field 

Currently I am using the file uploads section for this.

![a](https://user-images.githubusercontent.com/65775292/83550507-f2b21300-a4d4-11ea-91e4-f9e49464c394.PNG)

**Additional context**

**Comment by duder78** [comment]
+1

**Comment by NewStoreIT** [comment]
This is very relevant, if only possible please introduce this feature in the v5

**Comment by TinaMccray** [comment]
Yes this is relevant

**Comment by northcide** [comment]
+1 for this.  Some vendors have special details that are relevant to each license. For example contract number, serial, activation code, etc.  It would be very helpful to be able to create custom fields to account for those as needed.

**Comment by TinaMccray** [comment]
This would be nice to have

**Comment by snipe** [comment]
Duplicate of #4261
