### ISSUE TITLE
Skin per user

### ISSUE THREAD

**Issue by emike09** [grokability/snipe-it#8110]
**Server (please complete the following information):**
 - Snipe-IT Version 4.9.2
 - OS: Ubuntu 18.04
 - Web Server: Nginx
 - PHP Version 7.2.24

Our team members all want a different skin. One team member wants to use the high-contrast theme, I want the dark blue theme, another wants the green theme, another hates all dark themes, etc.

**Describe the solution you'd like**
Provide a solution to set the default skin under Branding, while allow each user to individually change their skin as needed.

**Describe alternatives you've considered**
Chrome extensions to change the page theme.

**Comment by emike09** [comment]
It's still relevant to me.

**Comment by emike09** [comment]
Still relevant to me!

**Comment by emike09** [comment]
I'd like it, but I know it's low priority.

**Comment by n3s0** [comment]
Off the top of my head I'm unable to remember which commit added this feature. But, if you were to upgrade to Snipe-IT to v6.0.10 there is an option for users select a preferred skin for their profile from the defaults.

**Comment by n3s0** [comment]
@emike09 Looks like this functionality was added in the referenced commit. FYI.

3e934a1b96e7bcd1e09d0a9ffae135e36709f324

**Comment by snipe** [comment]
Yeah, this was implemented quite some time ago. Sorry I didn't reference the original issue in the PR.
