### ISSUE TITLE
[Bug] Assets by Status graphic increase when disaply/hide the sidebar

### ISSUE THREAD

**Issue by maxlehot1234** [grokability/snipe-it#8112]
#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Each time I hide/display the sidebar menu, the Assets by Status graphic increase exponentially without resizing my browser window.
**To Reproduce**

1. Login on your Admin dashboard
2. Next click on the "3 bars" at the top left corner to reduce the sidebar
3. Reclick on this "3 bars" thing and check the Assets by Status graphic, it will increase each time you click on this 3 bars thing.
![image](https://user-images.githubusercontent.com/5159244/83760488-01b6d380-a643-11ea-840c-e2b6ebb7b8f7.png)
You see the graph will increase a lot each time
After some times, it looks like this :O
![image](https://user-images.githubusercontent.com/5159244/83762425-8276cf00-a645-11ea-9381-a0bc35243a16.png)

**Expected behavior**
It should keep the same size and not increasing each time a hide/display the sidebar

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.2 build 4352 (gec723a3da)
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version  7.2.24-0ubuntu0.18.04.6

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 83.0.4103.61

I also test this on Opera 68.0.3618.125

**Error Messages**
- I confirm this happen on the demo (On the developer demo, the graph disappear when pressing the "3 dots "thing. To display the graphic, you need to over it)
- I got no error in debug mode and nothing in the chrome console.

**Additional context**
- Its an upgrade from latest 4.9.1 using php upgrade.php each time a new update comes out
- I dont' edit data in the database manually Its a dangerous thing :)

Thanks again for reading and I hope I put enough information to have this thing fix ;)

Have a nice day

**Comment by Relix360** [comment]
+1
