### ISSUE TITLE
Font size of qr_text in /hardware/bulkedit print labels

### ISSUE THREAD

**Issue by ardetek** [grokability/snipe-it#8114]
The font size of the labels are always small, not controlled by the font size directive in settings.

In the file bulkedit:53 there is a directive "font-size: x-small;" that overwrites the font size settings

**To Reproduce**
1. preview a label of an asset
2. change the font size setting in labels
3. preview a label of an asset
4. same font size

 Snipe-IT versionv4.9.2 build 4352 (gec723a3da)
PHP Version7.2.24-0ubuntu0.18.04.6Laravel Version5.5.49

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 83

**Comment by Godmartinz** [comment]
@ardetek I've submitted a hotfix for this. The labels settings should be customizable again
