### ISSUE TITLE
API post user

### ISSUE THREAD

**Issue by s7thamon** [grokability/snipe-it#8115]
Unable to create a new user via API, getting an error of the following:

```
{
    "status": "error",
    "messages": {
        "password": [
            "The password confirmation does not match."
        ]
    },
    "payload": null
}
```

Don't see anything referencing this in the API docs at https://snipe-it.readme.io/v4.0/reference#users-2

**Comment by boring10** [comment]
It looks like you were looking at the API reference for version 4.0. In the current stable version there is a `password_confirmation` option.

https://snipe-it.readme.io/reference#users-2

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference#users-2">Overview</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>

**Comment by poxin13** [comment]
Oh hey look at that, didn't even notice. Thanks!
