### ISSUE TITLE
Translation to Malayalam

### ISSUE THREAD

**Issue by MuneebKalathil** [grokability/snipe-it#8119]
**Server (please complete the following information):**
 - Snipe-IT Version v5
 - OS: Ubuntu/CentOS/Windows
 - PHP Version : 7.2

I would like to  help in a translation project which is not available in crowdin. So, if possible can you start new language translation project - Malayalam

**Comment by MuneebKalathil** [comment]
Yes...... Relevant ;)

**Comment by snipe** [comment]
Hi there - Apologies, I didn't see this before. Normally when we get new language requests, they go through CrowdIn. we've added this language to CrowdIn, so you can begin translating as needed: https://crowdin.com/project/snipe-it/ml-IN 

<blockquote><img src="https://crowdin.com/favicon.ico" width="48" align="right"><div><strong><a href="https://crowdin.com/project/snipe-it/ml-IN">Translating Snipe-IT to Malayalam language</a></strong></div><div>Snipe-IT Malayalam translation</div></blockquote>
