### ISSUE TITLE
Bulk delete not checking the assigned_to type

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#8121]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I just got a glitch. Deleted the disabled user. Deleted via check and delete. The user did not have any assigned assets. In the magazine, I was horrified to see that a lot of assets were released to the warehouse. These assets were never assigned to the dismissed user. Assets were previously assigned to the location.

**To Reproduce**

**Expected behavior**

**Screenshots**
![5](https://user-images.githubusercontent.com/48224568/84130494-0832ba00-aa4c-11ea-8156-ceb628067280.jpg)
![6](https://user-images.githubusercontent.com/48224568/84130504-0a951400-aa4c-11ea-8504-d193cbf4f9c4.jpg)
![7](https://user-images.githubusercontent.com/48224568/84130507-0bc64100-aa4c-11ea-97a0-c9089534ae83.jpg)
![8](https://user-images.githubusercontent.com/48224568/84133657-184c9880-aa50-11ea-98eb-41f1240dfb07.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.2
 - OS: CentOS
 - Web Server:  Apache
 - PHP Version 7.3.9

**Desktop (please complete the following information):

OS: [e.g. iOS] Windows 10
Browser chrome, firefox
Version Last Ver

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? upgrade
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Treyfane** [comment]
I can reproduce this error in Version v4.9.2 - build 4352 (master).

If you "bulk delete" users, the assets checked out to the locations with the same **location ID** as the **user's ID** are bulk checked in. There seems to be a check missing wether the ID in the assigned_to field is a user ID or location / asset ID when bulk deleting users.

Please be aware about the severity of this bug since it did lead to several hundreds of assets erroneously checked in from locations in my installation upon deleting users.

Greetings,

          ^.^ Dingo

--

**Comment by Treyfane** [comment]
Still relevant.

**Comment by inietov** [comment]
Closing as this is already fixed in https://github.com/snipe/snipe-it/commit/d64b35c348022933edc74796b7095ed49fcd7b12
