### ISSUE TITLE
Docs - Docker-Compose.yml volume "snipe-vol" missing

### ISSUE THREAD

**Issue by BornToBeRoot** [grokability/snipe-it#8122]
Is the volume `./snipe-vol=/var/lib/snipeit` missing in the docker-compose file or is it not needed here?

https://snipe-it.readme.io/docs/docker#setup-with-docker-compose

**Comment by HinchK** [comment]
not needed - you may change it!

**Comment by BornToBeRoot** [comment]
Thanks!
