### ISSUE TITLE
Multiple company support, restricted user can choose other companies

### ISSUE THREAD

**Issue by sysaphys** [grokability/snipe-it#8125]
I created a test user that was assigned to a company. The user has the ability to create assets. When creating a new asset the user can choose any company from the dropdown menu, when they should only be able to choose the company they are assigned to. If they choose a different company it creates the asset however the user can not see it. Oddly enough superadmin can see the asset and it shows that the asset belongs to the the company the user is restricted to, despite test user not being able to see it.

**Comment by snipe** [comment]
I believe that's fixed in v5 (which will hopefully be out very soon)

**Comment by sysaphys** [comment]
Thanks for the amazingly fast response.
