### ISSUE TITLE
 ஐயா, எனக்கு எலக்ட்ரான் பதிப்பு வேண்டும்

### ISSUE THREAD

**Issue by yericua** [grokability/snipe-it#8134]
ஹாய் மாம்,
தயவுசெய்து தயாராகுங்கள் electron பதிப்பு.
நாளை தயாரா?

நன்றி மாம்

**Comment by UnlimitedCookies** [comment]
### Please use English when creating an issue.
(My guess is that he wants an electron version of snipe-it. I think this is something this project is not interested in for the near future. If you want a dedicated app, many browser like chrome offer a way to make websites behave like their own application, just google it)

Google Translate returns:
 **Title**: Sir, I want the electron version
 **Content**: Hi Mom, please get ready electron version. Ready for tomorrow? Thanks Mom
