### ISSUE TITLE
An enormous amount of categories have been created through csv importation

### ISSUE THREAD

**Issue by Rjibaraoko** [grokability/snipe-it#8135]
#### 
after some debugging everything went ok except that the category section was extremely long with 8 pages of categories. Each new category was all the columns combined in one row separated with ";".

#### Provide answers to these questions:

- Is this a fresh install or an upgrade?:    fresh install
- Version of Snipe-IT you're running:       v7.9.1 build 4352 (gec723a3da)
- Version of PHP you're running:       7.133-15+ubuntu16.04.1+deb.sury.org+1
- Version of MySQL/MariaDB you're running:       Laravel v5.5.49
- What OS and web server you're running Snipe-IT on :      Windows 10

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Godmartinz** [comment]
Hello @Rjibaraoko I would recommend using the csv templates located here: [https://snipe-it.readme.io/docs/importing#section-exporting-comma-delimited-csvs-on-windows](https://snipe-it.readme.io/docs/importing#section-exporting-comma-delimited-csvs-on-windows) 
I hope this solves your issue, but if not double check and see if there may be some empty characters/spaces/etc appended at the end of your columns. An exporter may have added them w/o any warning.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing#section-exporting-comma-delimited-csvs-on-windows">Importing Assets and More</a></strong></div><div>There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...</div></blockquote>
