### ISSUE TITLE
Snipe-IT Sync With Microsoft AD

### ISSUE THREAD

**Issue by bogdannovakovic** [grokability/snipe-it#8137]
Hi, 

I failed to find anything in documentation so I decided to write here. Can anyone advise if there are any specific requirements regarding Domain and Forest functional levels in order for sync between Snipe-IT and Microsoft Active Directory to work? 

We've migrated DC from Windows Server 2008 R2 to Windows Server 2016 and raised the domain functional level to Windows Server 2016, while leaving the forest functional level to Windows Server 2008 R2 after which sync just broke. No error logs on both sides, the account Snipe-IT uses for the sync is fine, when we test the LDAP sync, it returns that everything is works but it users don't really sync, which makes troubleshooting really difficult and that's what lead me to believe that domain functional level can be the issue as it's the only thing that changed. 

Version of Snipe-IT we use, with PHP and Laravel Version below:
Snipe-IT version: v4.9.2 build 4352 (gec723a3da)
PHP Version: 7.3.18-1+ubuntu16.04.1+deb.sury.org+1
Laravel version: 5.5.49
OS: Ubuntu 16.04.6 LTS

Thanks in advance!

PS This is my first post here and I apologize for a possible lack of information.

BN

**Comment by Mynty100** [comment]
Hi there,

We sync with Server 2016 AD. When you do this set the LDAP server
Just going to double check with you that your settings are as such and would recommand checking your LDAP search account still has the appreate access to read the base DN.

LDAP Bind User: this needs to be an account that has search permissions. I recommend making sure this account can only read the entire domain and for security not have the ability to edit or change. For example your could name the account 'LDAPSearch' or just 'LDAP' or anything you want.
Example:
CN=LDAPSearch,OU=LDAPUsers,DC=AD-Host-Name,DC=yourdomain,DC=com
LDAP Bind Password= the password you set for this account.

Base Bind DN is the name of the server so it can search the whole directory.
Example: 
DC=AD-Host-Name,DC=yourdomain,DC=com

LDAP Filter: There are so many options here, but we use security groups users are members of.
Example:
&(objectClass=user)(|(memberof=CN=Staff_users,OU=Users,DC=AD-Host-Name,DC=yourdomain,DC=com)(memberof=CN=Customer_users,OU=Users,DC=AD-Host-Name,DC=yourdomain,DC=com))

You can add as many security groups as you like or just one that all the users you wish to import as a member of. Replace Staff_users and customer_users with one that suites your AD.

Hope this helps, let us know if you require any clarification.
