### ISSUE TITLE
Add the option to change the favicon

### ISSUE THREAD

**Issue by dakide** [grokability/snipe-it#8145]
- Snipe-IT Version v4.9.3 - build 4395

Requesting to add the option to customize the site favicon, from within the Branding settings.

Currently there is no way to change the default favicon from the site settings (must be done by editing the source)
![image](https://user-images.githubusercontent.com/53129107/84949286-83474080-b0dc-11ea-9ce4-aa132bf63881.png)

**Comment by UserGoodtm** [comment]
I just changed the favicon in the program folders

**Comment by Paizuann** [comment]
Where is it?

**Comment by ScarUY** [comment]
Please allow the change from the UI so it works in docker too
