### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by benwa** [grokability/snipe-it#8147]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.9.2
 - OS: Windows Server 2019
 - Web Server: IIS
 - PHP Version: 7.4.7

**Is your feature request related to a problem? Please describe.**
Dell serves all of their product images as webp, which means an extra step to get it into Snipe-IT for model pictures.

**Describe the solution you'd like**
Support uploading the webp format for images.

**Describe alternatives you've considered**
A quick conversion isn't all that much of a big deal.

**Comment by benwa** [comment]
This is still relevant

**Comment by snipe** [comment]
This is now on develop
