### ISSUE TITLE
in mobile browsers GUI is not displaying drop down items

### ISSUE THREAD

**Issue by qudiqudi** [grokability/snipe-it#8148]
## Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
List drop downs are not displaying at all when accessing the webgui via mobile browser

**To Reproduce**
1. Open snipe-it in mobile browser

**Expected behavior**
List items will be shown when selecting a drop down menu.

**Screenshots**
see comment below.

**Server (please complete the following information):**
 - Snipe-IT Version 4.9.2
 - OS: FreeBSD
 - Web Server: Apache
 - PHP Version 7.4.2

**Smartphone (please complete the following information):**
 - Device: Pixel 2, Moto Z, iPhone 11
 - OS: Android 9, 10, iOS 12
 - Browser Firefox Mobile, chrome, Safari

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
**Appears to be the same for the demo, see screenshot in second comment below**
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by qudiqudi** [comment]
![Screenshot_20200618-095139](https://user-images.githubusercontent.com/5947641/84993658-dd321f80-b149-11ea-90f6-7f9455cb4b52.png)

**Comment by qudiqudi** [comment]
![Screenshot_20200618-100203](https://user-images.githubusercontent.com/5947641/84994493-0e5f1f80-b14b-11ea-9383-d595e574a043.png)

**Comment by qudiqudi** [comment]
It isnt even working in the development demo:
![Screenshot_20200618-100745](https://user-images.githubusercontent.com/5947641/84994992-c096e700-b14b-11ea-9f49-65750af70d9c.png)

**Comment by UnlimitedCookies** [comment]
Somewhat related to the overall bad mobile UI experience described in #6876 .

**Comment by UnlimitedCookies** [comment]
Wonderful.... the stale bot doing what he does best: Closing relevant issues.
