### ISSUE TITLE
Multiple label settings (admin/labels)

### ISSUE THREAD

**Issue by brosbunbo** [grokability/snipe-it#8149]
**Server (please complete the following information):**
 - Snipe-IT Version: latest
 - OS: Ubuntu 20.04
 - Web Server: Nginx
 - PHP Version: 7.1

**Is your feature request related to a problem? Please describe.**
I need to store multipe label settings. Ex: Setting 1, Setting 2, ... Therefore when generating labels, I can select a setting.

**Describe the solution you'd like**
Move label settings to a seperate table

**Comment by centauri** [comment]
Old request, but i'm also looking for the ability to print a different lable per asset.
I've got custome field with system info. Would be great to be able to print from snipe-it, but also print the regular asset labels.

**Comment by LckySndays** [comment]
I have a need for this feature as well. sometimes the label is too small or too big for specific object or use cases so choosing different formatted label might be useful for this case. another example would be that for example I store some asset/object inside a non transparent box and I would like to label both the asset itself and the outer box with different format or label sizes.
