### ISSUE TITLE
SnipeIT on Server 2016 will not send license Alerts

### ISSUE THREAD

**Issue by SamyLola** [grokability/snipe-it#8154]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to Settings General Settings and setup email.  Click Test and it works
2. Settings Notifications set expiring Alerts to 30 days
3. Create a license and assign it to a product with a end date of 6/30/20.
4. No alerts come in about this expiring. 

**Expected behavior**
I can get test emails just fine.  Setup notifications to be sent outwith in 30 days of the threshold.  Created a license that is assigned to a product with the extirpation date on the 30th of June 2020.  Never get any alerts that his license is about to expire.  Is this something this product can do?

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.7 build 4160
 - OS: [e.g. Ubuntu, CentOS] Windows Server 2016
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.2.31

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari]  Crhome

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by SamyLola** [comment]
Got it figured out had to enter a task for it.

**Comment by HinchK** [comment]
All good!  Thanks for the heads up, don’t forget to close!
