### ISSUE TITLE
Delete, hide or order the default fields from Snipe-it like "asset name"

### ISSUE THREAD

**Issue by Fabshj** [grokability/snipe-it#8155]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.9.0 - build 4223 (master)
 - OS: [e.g. Ubuntu, CentOS]: Linux Debian 10
 - Web Server: [e.g. Apache, IIS] Apache 
 - PHP Version: PHP 7.3.14-1

We do not need some of the standard fields such as "Asset Name". They must always be left empty and take up unnecessary space. 
Therefore it would be an advantage if you could hide or delete the unused fields. 
One more question:
Is it possible to arrange the standard fields in a different order? For example, would it be possible to arrange the serial number according to the model? (As shown in the screenshot)
![duesit](https://user-images.githubusercontent.com/66720720/85136085-61b29a00-b23f-11ea-940d-29304b7c7a6a.png)

Solution: A function where you can select whether a standard field (Asset Name, Supplier, etc.) should be displayed or not. Or even the possibility to delete it. 
Order: Arrange the standard fields differently according to your wishes? 

Thanks for the help!

**Comment by wwu-brandon** [comment]
+1 for this feature. For productive workflow it would be great to be able to hide, disable or, at minimum, reorder fields in this way.

**Comment by namarie23** [comment]
+1

**Comment by cryogenx** [comment]
Agreed

**Comment by enpa** [comment]
+1

**Comment by LukeGingerr** [comment]
Also agreed! Would be a great addition!

**Comment by seal61** [comment]
+1 - or maybe even add custom fields to the basic / default fields would be a very nice option. thanks! :)

**Comment by mariusangelmann** [comment]
+1

**Comment by quangbahoa** [comment]
+1

**Comment by rschitz** [comment]
+1

**Comment by centauri** [comment]
This would be great

**Comment by brijeshgajera** [comment]
+1

**Comment by Marxoz** [comment]
+1

**Comment by veenone** [comment]
Hi all, 
I'm trying to propose a solution regarding the request. Tell me what you think. You can find the screenshots in the PR above.

**Comment by GermanKiwi** [comment]
+1 from me. My company would greatly benefit from being able to hide/delete fields, and change the order of appearance of fields.

**Comment by Mike-NP** [comment]
+1

**Comment by snipe** [comment]
@Mike-NP this is already on master - no need to +1 it. It's been implemented.

**Comment by Mike-NP** [comment]
Hi

Thanks for the update.

I’ve downloaded the latest version but am unable to see where I can set fields to be mandatory / optional / hidden
***@***.***

Can you assist?


Cheers, Mike



Mike CLEARY
Manager, Cloud and Shared Platforms

P +64 9 988 9214
M +64 21 876 999
www.northpower.com
[Northpower]
be mindful  be present  be safe

**Comment by KristofStroobants** [comment]
> @Mike-NP this is already on master - no need to +1 it. It's been implemented.

Could you link the documentation? I did a Google search on this topic and landed here instead.
Not finding the option to change the default fields by browsing the menu.
Cheers and thanks for this great product. I'm discovering it just now.

**Comment by snipe** [comment]
The additional fields are in disclosure arrows now. There's not really anything to document. 

<img width="495" alt="Create_Asset____Snipe-IT_Demo" src="https://github.com/snipe/snipe-it/assets/197404/b4348ffe-7907-4ffd-b955-5aa162c35ffe">

**Comment by Kvoo** [comment]
> [@Mike-NP](https://github.com/Mike-NP) this is already on master - no need to +1 it. It's been implemented.

Well, we want to remove "Default Location", for example, that still isn't an option. People have been using it instead of checking out the asset, and since we don't use Default Locations anyway I want to remove that option

**Comment by snipe** [comment]
@Kvoo This can be hidden via custom CSS in the admin branding section, as has been mentioned before.

<img width="1255" height="133" alt="Image" src="https://github.com/user-attachments/assets/bcb18a3a-929c-4a9b-a8f6-003654b33a21" />

**Comment by seal61** [comment]
> [@Kvoo](https://github.com/Kvoo) This can be hidden via custom CSS in the admin branding section, as has been mentioned before.
> <img alt="Image" width="1255" height="133" src="https://private-user-images.githubusercontent.com/197404/503250800-bcb18a3a-929c-4a9b-a8f6-003654b33a21.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjIyNTMzNTQsIm5iZiI6MTc2MjI1MzA1NCwicGF0aCI6Ii8xOTc0MDQvNTAzMjUwODAwLWJjYjE4YTNhLTkyOWMtNGE5Yi1hOGY2LTAwMzY1NGIzM2EyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwNFQxMDQ0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjkxNjYwNTlmNjMxZmY5ZmIzZjBiNmEzMmJiY2JiZGQ0YjM4NDMyMmUzNTk1Y2ZjZjliZjFmMzdjN2M3NWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4QjXZPPLgLSV7l-NQLlL9M9JCBJm_jGDQ0CxIknRl74">

@snipe - I'm really struggeling to get this working. I already know to put the extra CSS in the admin area t the branding section, but so far I could just find this part, what removes the default location if an asset is edited. 

```
/* remove default location from asset info */
#rtd_location_id {
    display: none !important;
}
```

How do the other CSS snippets look like to also remove it from the tables / overview of an asset // remove it completely?

**Comment by Kvoo** [comment]
> [@Kvoo](https://github.com/Kvoo) This can be hidden via custom CSS in the admin branding section, as has been mentioned before.
> 
> <img alt="Image" width="1255" height="133" src="https://private-user-images.githubusercontent.com/197404/503250800-bcb18a3a-929c-4a9b-a8f6-003654b33a21.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI0MzA0MDEsIm5iZiI6MTc2MjQzMDEwMSwicGF0aCI6Ii8xOTc0MDQvNTAzMjUwODAwLWJjYjE4YTNhLTkyOWMtNGE5Yi1hOGY2LTAwMzY1NGIzM2EyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwNlQxMTU1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzViNGQ3YWQxNjM2M2Y3MmU4MWU4MjA1ZWVjYWQwMGJmYmMwNjBiOWVmYjZlYWI3MDNjMDhiM2FiOTc5MzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eRdV1YVWbbXBJdDWBuGI8FGlCY3cB-dzHFVcpbgQM_0">

A GUI Way for this would still be preferrable - usually we're Sysadmins, not Webdevs, using this software.

Where is the documentation on how to do this using custom CSS?

**Comment by seal61** [comment]
> > [@Kvoo](https://github.com/Kvoo) This can be hidden via custom CSS in the admin branding section, as has been mentioned before.
> > <img alt="Image" width="1255" height="133" src="https://private-user-images.githubusercontent.com/197404/503250800-bcb18a3a-929c-4a9b-a8f6-003654b33a21.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI0MzA0MDEsIm5iZiI6MTc2MjQzMDEwMSwicGF0aCI6Ii8xOTc0MDQvNTAzMjUwODAwLWJjYjE4YTNhLTkyOWMtNGE5Yi1hOGY2LTAwMzY1NGIzM2EyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwNlQxMTU1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzViNGQ3YWQxNjM2M2Y3MmU4MWU4MjA1ZWVjYWQwMGJmYmMwNjBiOWVmYjZlYWI3MDNjMDhiM2FiOTc5MzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eRdV1YVWbbXBJdDWBuGI8FGlCY3cB-dzHFVcpbgQM_0">
> 
> A GUI Way for this would still be preferrable - usually we're Sysadmins, not Webdevs, using this software.
> 
> Where is the documentation on how to do this using custom CSS?

sorry, your reply doesn't help me. 

My code snippet from above also doe snot work properly, as also the current location is removed, not only the default location.

**Comment by Kvoo** [comment]
> > > [@Kvoo](https://github.com/Kvoo) This can be hidden via custom CSS in the admin branding section, as has been mentioned before.
> > > <img alt="Image" width="1255" height="133" src="https://private-user-images.githubusercontent.com/197404/503250800-bcb18a3a-929c-4a9b-a8f6-003654b33a21.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI0MzA0MDEsIm5iZiI6MTc2MjQzMDEwMSwicGF0aCI6Ii8xOTc0MDQvNTAzMjUwODAwLWJjYjE4YTNhLTkyOWMtNGE5Yi1hOGY2LTAwMzY1NGIzM2EyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwNlQxMTU1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzViNGQ3YWQxNjM2M2Y3MmU4MWU4MjA1ZWVjYWQwMGJmYmMwNjBiOWVmYjZlYWI3MDNjMDhiM2FiOTc5MzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eRdV1YVWbbXBJdDWBuGI8FGlCY3cB-dzHFVcpbgQM_0">
> > 
> > 
> > A GUI Way for this would still be preferrable - usually we're Sysadmins, not Webdevs, using this software.
> > Where is the documentation on how to do this using custom CSS?
> 
> sorry, your reply doesn't help me.
> 
> My code snippet from above also doe snot work properly, as also the current location is removed, not only the default location.

I wasn't replying to you but to @snipe , sorry.

**Comment by seal61** [comment]
ping

**Comment by snipe** [comment]
There is nothing to ping. This issue is closed.
