### ISSUE TITLE
Key Cannot Generate

### ISSUE THREAD

**Issue by Amirul944** [grokability/snipe-it#8157]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)
I receive this error when i run this code " php artisan key:generate ", 
The error is  "In KeyGenerateCommand.php line 96:
  file_get_contents(C:\inetpub\wwwroot\snipe-it/.env): failed to open stream: No such file or directory " 

I'm sure that my .env has created and i thougt this is not important so i just ignore this part n go to next part but i get this " internal server error 500"

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - yes but i don't know how to see it
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) yes not helping

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running - 4.9.3
- Version of PHP you're running - 7.3
- Version of MySQL/MariaDB you're running - mariadb 10.5.3
- What OS and web server you're running Snipe-IT on - window server 2016 64 bit
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - i watch youtube on how to install snipeit on server 2016 ( i guess it manual? )
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - yes only the server error 500
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - nothing
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - failed to load resource: the server respond with a status of localhost/:1 500 internal server error
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Godmartinz** [comment]
Hello @Amirul944 please be sure you have your .env file filled out properly. We have some documentation that can help you with the process leading up to generating your keys here:
[https://snipe-it.readme.io/docs/configuration](https://snipe-it.readme.io/docs/configuration)

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.  Don't be intimidated by the length of this page. The configurat...</div></blockquote>

**Comment by riobijoy** [comment]
Even i have same issue
