### ISSUE TITLE
Allow change of status during checkout

### ISSUE THREAD

**Issue by cvpadmin** [grokability/snipe-it#8158]
This has been requested before, but keeps getting dropped. 

When an asset can be checked out, we have it set with a status of "Available". After checkout, the meta-status is set by the system to "Deployed", but the regular status field still says Available. This is obviously not correct. We either need the status to automatically be set, or a way to set it manually.

**Comment by cvpadmin** [comment]
Yo, It would have "recent activity" if someone actually DID something about it.

**Comment by cvpadmin** [comment]
Yes, this is still relevant

**Comment by snipe** [comment]
This was added several versions ago
