### ISSUE TITLE
Asset tag lost, need to change ID. Possible to clone with all the data?

### ISSUE THREAD

**Issue by psidemarama** [grokability/snipe-it#8160]
Hello.

I have a preprinted labels from 0001-0999 , and one of the laptops got broke and the shop returned it with replaced case, hence the label is now missing. So I'd like to assign a new ID to the device, so I can stick a new label to it. Is there a way to change the existing ID to the next free one? Clonong would not copy the files and history of the asset, right? Any other way to solve it?

TIA

**Comment by snipe** [comment]
That's correct, cloning it would only copy over other attributes (like model name, etc). It's more or less a shortcut to make it easier to create multiple assets with the same base info.

You should just be able to edit the asset and give it a new tag. If you're not sure what the next free tag is, you can go to the Create Asset page and grab that incremented asset tag.

**Comment by psidemarama** [comment]
Preprinted Labels incude a QR code that redirects to https://snipeit.XXXX.XX/hardware/<asset_id>  , so giving it a new tag doesn't help becuse the QR wouldn't work. Is there a way to redirect to "asset tag" and not id?
If I understand corrently, there is no solution for the use case where preprinted label gets lost (with QR redirect). Cloning looses all the history/files/metadata. Maybe you'd consider "advanced" cloning, where you can also clone all the metadata. Any way of executing some MySQL command to pull all the metadata to the new Asset id?

**Comment by psidemarama** [comment]
Ah, got it. Just found out about URL: https://snipeit.XXXX.XX/hardware/bytag?assetTag=<asset_tag>
