### ISSUE TITLE
Labels Font Size Not Responding To Changes... 

### ISSUE THREAD

**Issue by koolk** [grokability/snipe-it#8161]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to  "Labels" within "Admin" settings console
2. Attempt to change font size and save. 
3. Font will remain the same no matter what size you enter.

**Expected behavior**
The font size should reflect when attempting to print a label.

AFTER UPGRADE TO v.4.9.3 FONT SIZE DOES NOT CHANGE
<img width="292" alt="after upgrade " src="https://user-images.githubusercontent.com/4127498/85328637-11d20e00-b49f-11ea-8d86-88e4beb5c010.png">

LABEL LOOKS NORMAL PROIR TO UGRADE AND RESPONDS TO FONT SIZE CHANGES (running v4.9.2)
<img width="304" alt="prior to upgrade" src="https://user-images.githubusercontent.com/4127498/85328640-139bd180-b49f-11ea-9bed-8f635059944a.png">

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.3 build 4395
 - OS: Ubuntu
 - Web Server: Aparche
 - PHP Version 7

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser Chrome
 - Version latest

**Comment by koolk** [comment]
Labels are a big part of why we use Snipe. We trust in @snipe and have faith this will be resolved. By the old gods and the new.

**Comment by Godmartinz** [comment]
Afternoon @koolk, 
Well..whats the point of having a font size setting if it doesn't work? That would be my fault, apologies. I went ahead and submitted a hotfix for you (and everyone else). 
May the light of The Seven shine on you.

**Comment by snipe** [comment]
@Godmartinz No need to manually close these - they will get closed automatically (with an associated link to the PR) when the PR gets merged. This helps us maintain the relationships between issues and their fixes. :)

**Comment by koolk** [comment]
@Godmartinz @snipe  just updated and verified the font problem is fixed but now it seems like the 1D barcode is not working right, it does not sit in the constraints of the label dimensions and when going to print disappears all together. Should I open a separate ticket detailing the issue. ? Many thanks 🙏 

![Screen Shot 2020-06-22 at 9 02 12 PM](https://user-images.githubusercontent.com/4127498/85350087-24b00700-b4ce-11ea-9e80-e2b29c119b4c.png)
