### ISSUE TITLE
Label Settings overwrite each other

### ISSUE THREAD

**Issue by Joly0** [grokability/snipe-it#8165]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If i change settings (in most cases the spacing in the label settings) other settings (the label dimensions most of the time) change aswell, which makes it super hard, to get the perfect settings for a label template

**To Reproduce**
1. Go to settings
2. Click on Label settings 
3. Change for example label spacing
4. Label dimensions changed aswell, although no settings were changed

**Expected behavior**
Changing settings like the label spacing, shouldnt affect the label dimensions. So if i change spacing, dimensions stay same.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: v4.9.3 build 4395
 - OS: Windows
 - Web Server: IIS
 - PHP Version: 7.4.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox, Edge, whatever
 - Version: Latest (i know, bad to say latest, but i dont think it matters in this case)

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on? Written above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)? install script
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database. No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Joly0** [comment]
yes, still relevant

**Comment by Joly0** [comment]
This is still relevant

**Comment by Godmartinz** [comment]
I just wanted to point out that we have added an alternative label engine that should solve your issues.
