### ISSUE TITLE
Error taking manual backup in a docker installation

### ISSUE THREAD

**Issue by mbalcaen** [grokability/snipe-it#8167]
I hope someone can help me with this issue when I take a manual backup in a docker installation.

"Type error: Argument 1 passed to Spatie\DbDumper\DbDumper::setPort() must be of the type integer, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 36 "

My setup in docker is done with these settings.

sudo docker run \
--name web_snipe_mysql \
-d \
-e MYSQL_ROOT_PASSWORD="123456789" \
-e MYSQL_DATABASE=snipe \
-e MYSQL_USER=snipe \
-e MYSQL_PASSWORD="123456789" \
-e TZ=Europe/Brussels \
-p 127.0.0.1:3306:3306 \
-v /var/docker/snipe/mysql:/var/lib/mysql \
mysql:5.6 --sql-mode=""

sudo docker create \
--name=web_snipe \
--link web_snipe_mysql:db \
-e PUID=1000 \
-e PGID=1000 \
-e DB_CONNECTION=mysql \
-e DB_HOST=web_snipe_mysql \
-e DB_DATABASE=snipe \
-e DB_USERNAME=snipe \
-e DB_PASSWORD="123456789" \
-e APP_KEY=base64:4U/KPmw1GN/Tz0fWYO/4FsFOqjm7vDAQzMCq4cAqstc= \
-p 8082:80 \
-v /var/docker/snipe:/config \
--restart unless-stopped \
snipe/snipe-it

After a long search the only thing I could think about is to change the port manually in the .env file from DB_HOST=${MYSQL_PORT_3306_TCP_PORT} to DB_HOST=3306. But no success... 

Thanks a lot!

**Comment by inietov** [comment]
Hello, 

this doesn't look like a problem in the Snipe-IT codebase. I'm not by any mean a Docker expert, but if I follow the instructions in the [docs](https://snipe-it.readme.io/docs/docker) I'm able to run the container without any problem.

Having said that, nevertheless, I can run the backups whitout any problem with one minor change to the command you provide here, I just added the flag `-e DB_PORT=3306` so it looks like this:
```

sudo docker create
--name=web_snipe
--link web_snipe_mysql:db
-e PUID=1000
-e PGID=1000
-e DB_CONNECTION=mysql
-e DB_HOST=web_snipe_mysql
-e DB_PORT=3306
-e DB_DATABASE=snipe
-e DB_USERNAME=snipe
-e DB_PASSWORD="123456789"
-e APP_KEY=base64:4U/KPmw1GN/Tz0fWYO/4FsFOqjm7vDAQzMCq4cAqstc=
-p 8082:80
-v /var/docker/snipe:/config
--restart unless-stopped
snipe/snipe-it
```

I'm gonna close this issue, but feel free to reopen if this answer doesn't satisfied you.

**Comment by Go2ClassPoorYorick** [comment]
@inietov I'm sorry to pop up on an old thread, but it seems odd that a "Default" environment variable would be required for backups- Pardon my insolence, but it seems to me that the container should default to 3306 just like the actual database connection does when the variable isn't specified- it's misleading that the variable isn't required for connections to the database except when a backup is being performed.
