### ISSUE TITLE
LDAP sync fails. LDAP login works. Nothing in Logs. IIS error 500, snipeit:ldap-sync returns null

### ISSUE THREAD

**Issue by pfurches** [grokability/snipe-it#8171]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I go to People / LDAP sync and try any location, IIS sits there and does nothing. After 30 seconds I get HTTP 500 error. Laravel.log shows nothing happened. I also tried php artisan snipeit:ldap-sync --summary and again nothing returns. I used a script to verify PHP is making a connection and querying LDAP so I know PHP is working.

**To Reproduce**
1. Go to 'People'
2. Click on 'LDAP Sync'
3. Scroll down to 'ANY location'
4. Nothing but 500.

**Expected behavior**
LDAP users for that OU should populate into People.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.9.3 build 4395
 - OS: [e.g. Ubuntu, CentOS] Windows Server 2019 Datacenter
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.4.7 x64 NTS

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 - 2004
 - Browser [e.g. chrome, safari] Chrome 83, EdgeC 83, 84
 - Version [e.g. 22] 83 and 84

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Debug shows no errors at all.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
Error 500
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No, you do not have any locations wit LDAP sync.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on  Win Server 2019 DC w/IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation. All features working except LDAP sync.
- Include what you've done so far in the installation, and if you got any error messages along the way.
No other errors.
- Indicate whether or not you've manually edited any data directly in the database
No
I set LDAP filter to:
&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
Test LDAP sync returns " Connection to LDAP server established!"
php artisan snipeit:ldap-sync --summary returns null after 10-15 seconds,

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by StackAls** [comment]
https://github.com/snipe/snipe-it/issues/8230#issuecomment-660081720
