### ISSUE TITLE
WAMP Installation Fail

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#8176]
I was previously running SnipeIT v4.9.3 on WAMP  3.1.9.

Previous WAMP Server details:
– Wampserver 3.1.9 64 bit x64
– Apache 2.4.39 
– PHP 7.2.18 
– PhpMyAdmin 4.8.5
– Adminer 4.7.1 
– MySQL 5.7.26

I recently attempted to update my version of WAMP to 3.2.0.

I fully uninstalled the previous WAMP installation and Composer. I also ensured all necessary prerequisites were met for the WAMP installation and for SnipeIT.

New WAMP Server details:
– Wampserver 3.2.0 64 bit x64
– Apache 2.4.41 
– PHP 7.3.12 
– PhpMyAdmin 4.9.2 
– Adminer 4.7.5 
– PhpSysInfo 3.3.1. En option : PHP 7.1.33 
– MySQL 5.7.28

SnipeIT Server Configuration:
https://snipe-it.readme.io/docs/wamp

I was able to complete the instructions successfully, including the generation of a token on Github to run commands on the new Composer installation. Composer appeared to download the necessary files from Github without errors. 

After completing all steps successfully (attempted to install twice). I am unable to launch the pre-flight page.

Any ideas would be appreciated. Thank you

**Comment by Relix360** [comment]
Hello, what error where you getting on the token generation?

**Comment by jmartins1** [comment]
None, it was just indicating that I needed to create one. 

⁣Sent from BlueMail ​

**Comment by Relix360** [comment]
But where you able to run Composer successfully?

**Comment by jmartins1** [comment]
Yes, I did not see any errors when running the Composer. 

⁣Sent from BlueMail ​

**Comment by Relix360** [comment]
Can you try run it again using a token? Because im installing a wamp server now for testing and not generating the token abort some things

**Comment by jmartins1** [comment]
Relix, thank you for your assistance. Please note that I did generate a token before running Composer. Composer will not download the files from Github without generating a token first, i.e. It errors out, telling you to get a token. 

⁣Sent from BlueMail ​

**Comment by jmartins1** [comment]
Please note that after generating the Github token and running Composer, it appeared to download from Github  without errors. 

⁣Sent from BlueMail ​

**Comment by jmartins1** [comment]
Relix, would you please let me know what you find after testing. Just want to make sure I'm not doing something wrong. I've preformed WAMP updates previously without any issues, but I'm not sure what went wrong this time. 

Thank you again

⁣Sent from BlueMail ​

**Comment by jmartins1** [comment]
Relix, any update on this issue?

**Comment by jmartins1** [comment]
Relix,

I was able to resolve this issue. 

Please note that a clarification should be made to the WAMP Server Configuration documentation.

Step 6 Indicates:

6. Update your virtual host settings

Edit `httpd.conf. Remember to the change http://yourcomputername to whatever address you wish to access Snipe-IT by. (These values are case-sensitive.)

On the WAMP Server installation the httpd.conf file resides in two places:

1. C:\wamp\bin\apache\apacheVersion\conf

File name: httpd.conf 

2. C:\wamp\bin\apache\apacheVersion\conf\extra

File name: httpd-vhosts.conf

The documentation indicates that httpd.conf should be modified (as is 1.). However, modifying this file will cause the pre-fight to not load. The file that should be modified as correctly titled in the step (6. Update your virtual host settings) is the httpd vhosts.conf, which resides in a different directory (C:\wamp\bin\apache\apacheVersion\conf\extra)

After modifying httpd-vhosts.conf I was able to launch SnipeIT without issue.

**Comment by jmartins1** [comment]
I was able to resolve this issue.

Please note that a clarification should be made to the WAMP Server Configuration documentation.

Step 6 Indicates:

    Update your virtual host settings

Edit `httpd.conf. Remember to the change http://yourcomputername to whatever address you wish to access Snipe-IT by. (These values are case-sensitive.)

On the WAMP Server installation the httpd.conf file resides in:

    C:\wamp\bin\apache\apacheVersion\conf

File name: httpd.conf

However, the VHost file resides in:

    C:\wamp\bin\apache\apacheVersion\conf\extra

File name: httpd-vhosts.conf

The documentation indicates that httpd.conf should be modified (as is 1.). However, modifying this file will cause the pre-fight not to load. The file that should be modified as correctly titled in the step (6. Update your virtual host settings) is the httpd vhosts.conf, which resides in a different directory (C:\wamp\bin\apache\apacheVersion\conf\extra)

After modifying httpd-vhosts.conf I was able to launch SnipeIT without issue.
