### ISSUE TITLE
Unable to see Import Assets option 

### ISSUE THREAD

**Issue by rambeatsk** [grokability/snipe-it#8180]
#### Please confirm you have done the following before posting your bug report:

- [ Yes] I have enabled debug mode - No message
- [ Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I'm unable to see any option for importing assets in the Import menu after upgrading Snipe-IT to v4.9.3 build 4395 (g9a2440dc4) 

**Expected behavior**
The import page should display the browse button to select the CSV file.

**Screenshots**
![Snipe-IT-ImportPage](https://user-images.githubusercontent.com/67434192/85773696-c25c3e00-b73b-11ea-828d-ea7066c2d496.png)

**Server (please complete the following information):**
 - Snipe-IT Version -V4.9.3
 - OS:  CentOS
 - Web Server: Apache
 - PHP Version: 7.3.19

**Desktop :**
 - OS: Windows 10
 - Browser: FireFox
 - Version: 77.0.1 (64-bit)

**Comment by snipe** [comment]
This should be fixed with the latest commit
