### ISSUE TITLE
Import page plank / Personal API Keys page blank

### ISSUE THREAD

**Issue by znerol2** [grokability/snipe-it#8181]
#### Please confirm you have done the following before posting your bug report:

- [ no] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
fresh install of Version v4.9.3 - build 4395 (master) via git, after preflight completed sucessfully I can not see anything on the import page or the Personal API Keys page

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Import'

**Expected behavior**
See the CSV selector and import button

**Screenshots**
![Screen Shot 2020-06-26 at 1 38 35 AM](https://user-images.githubusercontent.com/6800371/85770941-06f0d500-b74e-11ea-80b5-4ed6909e5c90.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.3 - build 4395 (master)
 - OS: [CENTOS 7]
 - Web Server: [APACHE]
 - PHP Version PHP 7.3.19

**Desktop (please complete the following information):**
 - OS: [macOS Sierra]
 - Browser [i tried with chrome / safari / firefox]
 - Version [latest]
 
Also tried Chrome on android phone

**Error Messages**
No error in browser
I see nothing obvious in the logs but debug is turned off

**Additional context**
I had the import page working a few weeks ago, but as I am still in the testing phase I decided to re-install and this problem appeared
I also installed a cloud instance with ubuntu 16.04 and snipeit via git, still the same, both pages show nothing
Could be that I'm missing something, but i checked permissions and selinux settings as per the documentation

**Comment by snipe** [comment]
This is fixed in the last commit

**Comment by znerol2** [comment]
wow, lightening speed reply, thanks!

it's working now, yay!

**Comment by snipe** [comment]
Awesome, thanks for letting us know!
