### ISSUE TITLE
Upload Image In Users

### ISSUE THREAD

**Issue by Amirul944** [grokability/snipe-it#8184]
Im Sorry. Just a simple question

Is there any way that i can upload image in user?? 
"Create New" does not have any button to upload any image inside.

When i check back the data, have avatar data icon.

**Comment by viclou** [comment]
Sorry, no we don't offer a user image (like the device image), though you can upload an image from the User's detail view by clicking the upload button on the upper right. This image will appear under the user's File Uploads tab in the User's detail view.

**Comment by snipe** [comment]
Users can upload their own avatar by editing their profile.

**Comment by Amirul944** [comment]
I see thank you very much

**Comment by Amirul944** [comment]
> Users can upload their own avatar by editing their profile.

What is the exact size for the image to upload? There's no reference for this.

**Comment by snipe** [comment]
There is no exact size. The avatar will be resized down to 84x84
