### ISSUE TITLE
<div class="pull-left"> in labels.blade.php breaks printing with Chrome

### ISSUE THREAD

**Issue by Joly0** [grokability/snipe-it#8189]
While trying to setup the Labels, i found out, that when i open up the Labels page, everything looks normal, but as soon as i want to print the Labels through Chrome, all Text next to the QR-Code goes down 1 row. When i remove <div class="pull-left"> from the  labels.blade.php file, the Labels-page looks same, and the print preview looks like it should, no misalligned text anymore

**Comment by fumunda** [comment]
Had same issue.  I ended up swapping labels.blade.php from my test site at v4.9.0 to my production site at v4.9.3 to fix it.  There were a lot of changes to the formatting between v4.9.2 and .3 for some reason.

**Comment by Joly0** [comment]
Yes, still relevant

**Comment by Joly0** [comment]
Yes, still relevant

**Comment by SujectName** [comment]
This is still occurring in 5.0.12. It happens in the Edge as well as Chrome browser.
