### ISSUE TITLE
Unsupported Ubuntu version. Version found: 20.04, same as #5622

### ISSUE THREAD

**Issue by cb900crdr** [grokability/snipe-it#8196]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Cannot use install script on ubuntu 20.04.

**To Reproduce**
wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh

receive 
Unsupported Ubuntu version. Version found: 20.04

**Expected behavior**
Snipe-it should install on ubuntu 20.04 since it's newer than 14 as required.

**Screenshots**

![image](https://user-images.githubusercontent.com/67693094/86244427-f5586480-bb75-11ea-8d85-4ef8e319c2ad.png)

**Server (please complete the following information):**
 - Snipe-IT Version Latest
 - OS: Ubuntu 20.04
 - Web Server: Apache
 - PHP Version: 7.4.3 

**Additional context**
- fresh install 
- Ubuntu 20.04
- What method you used to install Snipe-IT (install.sh)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by EDVLeer** [comment]
Could you please change the check in snipeit.sh on line 425 to `if [ "$version" == "20.04" ]; then`: https://github.com/snipe/snipe-it/blob/master/snipeit.sh#L425

I believe the commands for Ubuntu 18.04 and 20.04 are the same.

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by cb900crdr** [comment]
That worked. Thank you.

**Comment by EDVLeer** [comment]
Pull request: https://github.com/snipe/snipe-it/pull/8207
