### ISSUE TITLE
"The results could not be loaded" while trying to create new assets

### ISSUE THREAD

**Issue by EIijah** [grokability/snipe-it#8199]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

When creating a new asset the results in the drop down dissapear and it becomes "The results could not be loaded"

**To Reproduce**
1. Go to 'Create Asset'
2. Click on 'Any dropdown'
3. Scroll down to 'The bottom of the list and wait'

This seems to be happening on the demo version as well.

**Expected behavior**
Results to not dissapear

**Screenshots**
https://prnt.sc/ta67te

**Server (please complete the following information):**
 - Snipe-IT Version 4.9.3
 - OS: Ubuntu Server
 - Web Server: Apache
 - PHP Version 7.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.116

**Error Messages**
Logs are not filling even with debug on

**Additional context**
- Is this a fresh install or an upgrade? Yes
- Indicate whether or not you've manually edited any data directly in the database. No

**Comment by EDVLeer** [comment]
I have the same issue: https://github.com/snipe/snipe-it/issues/8192

Are your devices displayed first? I can't reproduce this error in the demo.

**Comment by EIijah** [comment]
> I have the same issue: #8192
> 
> Are your devices displayed first? I can't reproduce this error in the demo.

I see you do have the same issue - What do you mean devices displayed first sorry? It's still happening in the demo for me if I open up 'Model' scroll to the bottom and wait - it seems to take longer if there are more items

**Comment by Ruud-Mens** [comment]
Same issue here, if you leave the select fields open for a couple of seconds (3 - 5 sec) the result will disappear 
Console error:

` http://snipeit/api/v1/companies/selectlist?page=121 405 (Method Not Allowed)`

**Comment by Ruud-Mens** [comment]
Same as #8035 and #7974

**Comment by snipe** [comment]
Closing as duplicate of #8035
