### ISSUE TITLE
How to language change when finished install process.

### ISSUE THREAD

**Issue by rlae3015** [grokability/snipe-it#8204]
**Server (please complete the following information): 
 - Snipe-IT Version : 4.9.3 build 4395
 - OS: CentOS 7.4.1708 x64
 - Web Server: Apache 2.4.6
 - PHP Version : 7.4.7

**Is your feature request related to a problem? Please describe.**
I want change language english to korean. So, I set en to ko on .env file and execute "php artisan config:clear" and "httpd restart".
But, not change language...
I installed using ./install.sh.

How to change language english to korean?
Please help me. Thank you.

**Comment by viclou** [comment]
@rlae3015 You might have run `php artisan config:cache` at some point, which would have cached those variables. 

To clear that config cache, try running `php artisan config:clear` and then `php artisan config:cache` to cache the new environmental variables.

**Comment by rlae3015** [comment]
Thank you for answer.
I have one more question. So when I run that order? before install or after install?
I know, if i run ./install.sh, already created generate key.

I followed this site : https://algo79.tistory.com/entry/snipeit-install-for-centos-7x

**Comment by viclou** [comment]
Generally, you would do this before upgrading; you can follow the instructions here: https://snipe-it.readme.io/docs/upgrading

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div>Always backup your database and configuration files before upgrading. We try very hard to make sure that all database changes are non-destructive, but you should always backup beforehand anyway. You will never regret backing up your database. You may regret not doing so, so it’s just better to get i...</div></blockquote>
