### ISSUE TITLE
LDAP authentication not working if user is not directly in BaseDN

### ISSUE THREAD

**Issue by synedraIT** [grokability/snipe-it#8214]
- [X] I have enabled debug mode - not required, we know where the problem is
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Hello!

We are facing an Issue with the LDAP-Authentication.
I already identified the root cause of the issue; The "Base DN" will not be searched for users, just appended to the login-query.

Our BaseDN is: `ou=users,ou=synedra,dc=synedra,dc=it.`

The users are located in their departments (each dept. is an ou) under this BaseDN, for example;
`uid=a.dmin,ou=it,ou=users,ou=synedra,dc=synedra,dc=it`
`uid=d.evloper,ou=dev,ou=users,ou=synedra,dc=synedra,dc=it`

If I set the BaseDN to `ou=it,ou=users,ou=synedra,dc=synedra,dc=it`, I can log in as `a.dmin`, but not `d.eveloper`.

When it is set as `ou=users,ou=synedra,dc=synedra,dc=it`, snipeit actually tries to log in like this;
`uid=a.dmin,ou=users,ou=synedra,dc=synedra,dc=it`
Our LDAP-Server will deny this, because there is no user `a.dmin` in `ou=users,ou=synedra,dc=synedra,dc=it`.

**To Reproduce**
1. Have an LDAP-Directory that has users separated by different OUs (e.g `uid=d.eveloper,ou=dev,[BASEDN]` and `uid=a.dmin,ou=it,[BASEDN]`)
2. Use the common highest DN as BaseDN, make sure that there is at least one ou that separates the users
3. Enable LDAP-Authentication
4. Users cannot login, log says that it tried to log in with wrong username (uid=<username>),[BASEDN] instead of the additional ou)

**Expected behavior**
Snipeit searches through all OUs in the LDAP-Directory, not just using the top level one.
Maybe an additional configuration parameter or field to set the "max depth" to explicitly enable this behaviour.

**Server:**
 - Snipe-IT Version v4.9.3 build 4395 (g9a2440dc4) 
 - OS: CentOS 8, SELinux and Firewall enabled.
 - Web Server: Apache/2.4.6 (CentOS)
 - PHP Version 7.3.19

**Error Messages**
```
[2020-07-09 10:45:56] production.DEBUG: Attempting to login using distinguished name:uid=<myuser>,ou=users,ou=synedra,dc=synedra,dc=it
[2020-07-09 10:45:56] production.DEBUG: LDAP user <username> not found in LDAP or could not bind
```

**Additional context**
- This is a fresh install.
- I did not play around with the DB, as far as our records say, nobody did.
- We are using [Univention Corporate Server Core Edition](https://www.univention.com/products/ucs/) for our LDAP/AD.

(I did not find any related Issues, only similar ones, but most of those were related to importing data from LDAP, which works fine for us!).

Thank you very much for helping us resolve this issue!

**Comment by StackAls** [comment]
https://github.com/snipe/snipe-it/issues/8230#issuecomment-660081720

**Comment by mattdymes** [comment]
I can confirm this is happening to me as well.  It would seem the LDAP login is taking the cn typed in and just appending the Base Bind DN to it.  In the debug console,  the fully qualified name being logged into is incorrect.  It is missing the Sub OU that the user actually resides in.  It is trying to log into an account that is not there.

**Comment by synedraIT** [comment]
bump

**Comment by synedraIT** [comment]
Duplicate of Issue #7696.
