### ISSUE TITLE
Export users to csv

### ISSUE THREAD

**Issue by riccardozjesolo** [grokability/snipe-it#8217]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
In users tab when i click export the file doesn't contain the column phone.
the users are sync with active directory

**To Reproduce**
1. Go to 'users tab'
2. Click on 'export'
4. file .csv without phone column

**Server (please complete the following information):**
 - Snipe-IT Version: v4.9.2 build 4352 (gec723a3da)
 - OS: Debian 9
 - Web Server: Apache
 - PHP Version: 7.3.19-1+0~20200612.60+debian9~1.gbp6c8fe1

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 80

**Error Messages**
No error

**Comment by snipe** [comment]
Phone number is exported if the column is visible (unhidden) on the screen. It will only export what's visible on the screen.

**Comment by riccardozjesolo** [comment]
i talk about the export button.
i attach the image file.
![Cattura](https://user-images.githubusercontent.com/68104445/87137475-3ef32e80-c29d-11ea-8ed3-aaf679125439.PNG)
