### ISSUE TITLE
Add option to make customfield unique

### ISSUE THREAD

**Issue by klorenz** [grokability/snipe-it#8219]
**Server (please complete the following information):**
 - Snipe-IT Version 4.8.0
 - OS: Debian
 - Web Server: Apache
 - PHP Version  7.1.33-3+ubuntu16.04.1+deb.sury.org+1

**Is your feature request related to a problem? Please describe.**
I would like to add IP addresses to assets and make sure, that each IP address is unique.

**Describe the solution you'd like**
Add the option to make a custom field unique (nulls allowed) in context of an entity like Model, Location, Category, Department, etc.  So the Uniqueness option would be a dropdown: "Not Unique" (default), "Globally Unique", "Unique for Model", "Unique in Location", "Unique in Category", etc.  This would be the greatest implementation.

**Describe alternatives you've considered**
Add the option to make a custom field unique globally (nulls allowed).

**Additional context**

**Comment by janzendi** [comment]
For me this issue is still relevant

**Comment by janzendi** [comment]
Please reopen

**Comment by echristley** [comment]
Please reopen this issue.  I'm having data integrity problems which could be cured by this basic database feature.

**Comment by snipe** [comment]
(No idea why Github auto triple-posted on that.)

**Comment by inietov** [comment]
Closing as I think this feature is already added
![image](https://user-images.githubusercontent.com/653557/172456246-33d2a9fb-4c41-4b60-8806-7548c45a51cd.png)

**Comment by snipe** [comment]
It is - good looking out, Ivan :)

**Comment by echristley** [comment]
That option is not available on custom fields using the cloud hosted version .

![image](https://user-images.githubusercontent.com/87864832/172457647-0f8a690b-9807-4bbe-a486-391b3454c2cc.png)

**Comment by echristley** [comment]
This is probably a better example:

![image](https://user-images.githubusercontent.com/87864832/172457948-e7778b57-c29d-4e36-9d33-c7b71dd497ff.png)

**Comment by inietov** [comment]
Thanks for your input @echristley. What cloud hosted version? The demos?

**Comment by echristley** [comment]
snipe-it.io

**Comment by inietov** [comment]
:S that URL doesn't resolve in my browser. This is in the develop demo:
![image](https://user-images.githubusercontent.com/653557/172458379-6abfa51b-3606-408c-b7fe-e688b284cdc9.png)

And this in the master branch demo:
![image](https://user-images.githubusercontent.com/653557/172458445-0956e92b-5d33-4e99-b877-8ff89d0621ce.png)

**Comment by echristley** [comment]
We signed up for a hosted account so that we could get "premium support", but it appears that we're a version behind.
I apologize. I will contact support.

**Comment by snipe** [comment]
@echristley the version rollout is happening this week - we wanted to give it a little time to work out any kinks. If you'd like an immediate upgrade, we can do that for you tho. Just send your subdomain name to us at support@snipeitapp.com.
