### ISSUE TITLE
can i run snipe-it on only 1 docker container it has 3 service mysql,webserver and snipeit

### ISSUE THREAD

**Issue by dedeoglumrt** [grokability/snipe-it#8225]
I have been using apple since its first version.
I installed virtual and physical computers.
the easiest way i want to use it in a single asd container from now on.

or how many container should i have for the snipe-it. im pretty new on dockerand i insist the case :)

if you help me with that i can appreciate.

Thanks

**Comment by fstorz** [comment]
hi @dedeoglumrt,
there is some [documentation](https://snipe-it.readme.io/docs/docker) for using snipe-it with docker and docker-compose.

**Comment by dedeoglumrt** [comment]
i know there the page but i want to get more free time and i need someone who already did this and already documentated.

i think docker way to install snipe it much more feasible and needs to be step by step guide.
