### ISSUE TITLE
LDAP password authentication is not working

### ISSUE THREAD

**Issue by reddo-kai** [grokability/snipe-it#8230]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
We have connected our AD (Windows Server 2019) with the nearly fresh install of Snipe-IT. We´ve tested the connection to our LDAP/AD server and it´s working. I can import users without any problems but if any user try to login we get the error that username or password is incorrect. What i´ve tried:

- ldap without and with TLS
- Sync passwords / do not sync password
- different OUs
-- we have a main OU und sub-OU. All user shoud be imported (working)
- import user to a location and import them without a location
- tried different LDAP Filter
-- &(cn=*)
-- !(&(objectClass=user)(userAccountControl:1.2.840.113556.1.4.803:=2))

**To Reproduce**
1. Go to Login / LDAP Settings
2. Fill in Credentials
3. Click on Test
4. See error: "Login Failed. <username> did not successfully bind to LDAP."

**Expected behavior**

**Screenshots**
![Bildschirmfoto 2020-07-14 um 13 49 48](https://user-images.githubusercontent.com/17751708/87422511-0921b300-c5d9-11ea-9822-6b101c7779f9.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.3 build 4395 (g9a2440dc4) (DOCKER)
 - OS: ubuntu16.04.
 - Web Server: included
 - PHP Version 7.1.33-16+ubuntu16.04.1+deb.sury.org+1

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome & safari
 - Version latest

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
> [14:03:40] LOG.debug: Preparing to test LDAP login
> [14:03:40] LOG.debug: Attempting to bind to LDAP for LDAP test
> [14:03:40] LOG.debug: Attempting to login using distinguished name:<my mail>
> [14:03:40] LOG.debug: LDAP login failed

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
> fresh install
- What OS and web server you're running Snipe-IT on
> Docker (official image)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker compose
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by godfreya-burnsideschoolnz** [comment]
I have just been having this same problem with a new git install on CentOS7 using LDAP to authenticate against an Open Enterprise Server and was able to find a workaround in my case.

Within the LDAP settings I initially had the "Username field" as uid and the LDAP "Authentication query" as cn=

The query being sent to the LDAP server every time was uid=******,ou=******,o=****** which would fail.

On the off chance, I tried changing the "Username field" to cn which resulted in success as the ldap query was then cn=******,ou=******,o=******

I am wondering whether the code is using the wrong database field to construct the ldap query.

Snipe-IT versionv4.9.3 build 4395 (g9a2440dc4)
PHP Version7.1.33
Laravel Version5.5.49

**Comment by reddo-kai** [comment]
Hey @godfreya-burnsideschoolnz,
Thank you for your help. I don´t know if this would work because I´m using an Microsoft AD Server. Where can I see query? I´m a bloody noob in deconstruction messages.

**Comment by StackAls** [comment]
Try it. (sorry for english)
For Active Directory
LDAP Bind username : LDAPread@reddo.de  (create this user in AD and add in group domain admin or group autentification)
Base Bind DN : dc=reddo,dc=de
LDAP filter: &(samaccountname=*)(&(objectClass=user)(objectCategory=person))
