### ISSUE TITLE
 Backup failed 

### ISSUE THREAD

**Issue by Samee2019** [grokability/snipe-it#8241]
I need to get backup from the system.
[
![Capture](https://user-images.githubusercontent.com/61033475/87752866-fc8e9c00-c81e-11ea-931c-1178627dda18.PNG)
](url)

This error shows 

- Is this a fresh install or an upgrade? yes
- Version of Snipe-IT you're running V.3.0
- Version of PHP you're running 7.2
- Version of MySQL/MariaDB you're running 
- What OS and web server you're running Snipe-IT on Linux server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error yes
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
The error message is telling you what's wrong. You need to enable `proc_open` in your PHP's ini file. 
https://www.php.net/manual/en/refs.fileprocess.process.php

Look for `disable_functions` in your ini and make sure `proc_open` isn't in the list of disabled functions.

<blockquote><img src="https://www.php.net/favicon.ico" width="48" align="right"><div><strong><a href="https://www.php.net/manual/en/refs.fileprocess.process.php">PHP: Process Control Extensions - Manual</a></strong></div></blockquote>

**Comment by Samee2019** [comment]
disable_functions = show_source, system, shell_exec, passthru, exec

these are the disable functions

**Comment by snipe** [comment]
Well the system is telling you what's wrong, so it's still a configuration issue on your end. Make sure you're looking at the right ini file, and then remove methods from the disable_functions setting until you can get it to work. (Make sure you restart php after each change so they will take effect.)
