### ISSUE TITLE
Regarding Installation of Snipe-IT

### ISSUE THREAD

**Issue by jainjk** [grokability/snipe-it#8244]
Hi,

I`m facing issue installing snipe-it. 

I tried lots of documentations from internet. But none of them was successful. I tried a lot of times even using video installation, still I faced the same issue. 

I used Xampp, Compressor, Snipe-IT 4.9.3 Files, 

Please see the images. And kindly guide me incase if any wrong was there in my configuration.

![browser](https://user-images.githubusercontent.com/68348770/87822393-03ed8e00-c88f-11ea-92e2-40aa0aa585de.PNG)
![env file](https://user-images.githubusercontent.com/68348770/87822396-064fe800-c88f-11ea-82b8-a9ebf3c84b98.PNG)
![httpd conf](https://user-images.githubusercontent.com/68348770/87822402-06e87e80-c88f-11ea-9071-a73c9313dd2f.PNG)
![snipeit database](https://user-images.githubusercontent.com/68348770/87822404-07811500-c88f-11ea-968f-e3c25c3e927a.PNG)

**Comment by snipe** [comment]
Hi @jainjk - did you add a DNS entry for `http://it-ik`? Snipe-IT doesn't (and cannot) handle that part of your server setup for you.

**Comment by jainjk** [comment]
if possible could you just tell me an example

**Comment by snipe** [comment]
That's a bit outside the scope of what we can support here, but this link has a pretty good breakdown. 
https://sangams.com.np/setup-web-server-domain-xampp/

<blockquote><img src="https://sangams.com.np/wp-content/uploads/2018/07/server-domain-name-xampp.png" width="48" align="right"><div><img src="https://sangams.com.np/wp-content/uploads/2017/08/626.png" height="14"> Sangam's Blog</div><div><strong><a href="https://sangams.com.np/setup-web-server-domain-xampp/">How to Setup Web Server with Domain Name in XAMPP | Sangam's Blog</a></strong></div><div>All you need to create a web server in your PC with domain name in XAMPP is here. You need to enable Apache virtualhost and redirect domain with hosts file.</div></blockquote>

**Comment by jainjk** [comment]
I just done these config using one documentation. Which I referred from Internet.

**Comment by snipe** [comment]
I'm not sure what you mean, but the link I just gave you has details about setting up DNS further down the page.

**Comment by jainjk** [comment]
actually I was just making a trial installation with a jio hotspot. With one of my laptop.

**Comment by jainjk** [comment]
I had created a DNS still its not working. After editing the "httpd-vhosts.conf file" Apache service is not starting.

Here are my files. Please help me out by giving a guide which shows proper examples. so I can go for it without errors.
I was on this project for 4 days. still errors.

![xampp](https://user-images.githubusercontent.com/68348770/87828705-1d94d280-c89b-11ea-824f-3efb5f0a847a.PNG)

![env file img](https://user-images.githubusercontent.com/68348770/87828669-0c4bc600-c89b-11ea-92ff-4019894c032e.PNG)
![httpd vhosts conf](https://user-images.githubusercontent.com/68348770/87828681-1241a700-c89b-11ea-868e-9a41e6afaba2.PNG)
![dns](https://user-images.githubusercontent.com/68348770/87828652-048c2180-c89b-11ea-9dc0-2789ed92a903.PNG)
