### ISSUE TITLE
Feature Request: Checkout to Department

### ISSUE THREAD

**Issue by Krejar** [grokability/snipe-it#8256]
**Server (please complete the following information):**
 - v4.9.4
 - Centos 8
 - Apache
 - 7.4 

**Describe the solution you'd like**
I would like to see an option to Checkout to Department

**Describe alternatives you've considered**
I thought about creating a "People" entry for location, but then decided against that. I've been using Location as a placeholder for Department, but I am now 20+ entries for Location when in reality I only have 5-7 different locations.

**Additional context**
This isn't a huge deal breaker for me, more of a QoL. I would love to see it implemented as I have many assets that are checked out department wide and moved around quite a bit between locations.

**Comment by snipe** [comment]
That's unlikely to be on our short term roadmap. We already allow you to checkout to location, which is problematic enough, since a Location cannot be held responsible for lost/stolen/damaged goods.

**Comment by Krejar** [comment]
Hi @snipe 

Thank you for the very quick reply. 

Why was Location included in the Checkout to selection if it couldn't be responsible for equipment? This makes absolute sense as a Location is a place and not a person or persons. However a department is a person or a group of people. I suppose I could assign the asset to a department head, but if that person changes positions or is terminated, then I would need to assign the asset to another person. To include a Department as a Checkout to selection would satisfy the use case of an entity not being held responsible for lost goods, etc.
