### ISSUE TITLE
Barcodes are not printed in 4.9.3 and 4.9.4 as they were in v4.7.7

### ISSUE THREAD

**Issue by davoezzz** [grokability/snipe-it#8261]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to 'Some asset'
2. Then 'Generate label'
3. The view is different as in the 4.7.7 version.

**Expected behavior**
The label should be the same layout as in 4.7.7

**Screenshots**
https://ibb.co/bPzNmj0

**Server (please complete the following information):**
 - Snipe-IT Version V4.9.3 and 4.9.4
 - OS: [e.g. Ubuntu, CentOS] Windows
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.3.4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome, Edge, Firefox
 - Version [e.g. 22] newest all

**Smartphone (please complete the following information):**

**Error Messages**
None (as far as i can see)

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on: Server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by domunus** [comment]
Note that the generated image looks fine.  The problem only occurs when you click to print it seems to read it differently.

I can confirm this issue as well.  Just updated to 4.9.4 from 4.9.2 and the barcode disappeared off of our tags.  After a lot of adjustments in the SnipeITapp label settings.  I was able to get the barcode back but had to reduce font size and remove fields to get it to start showing again.   The issue appears to be with the Text area of the label.  Its creating an empty space below the text area that increases in size with the font size.   As I increase the font size, the bar code get narrower until it disappears. And it's not disappearing in to another page as I adjusted the page and label size much large to see if that was occurring, it was not.  I've managed to get the bar code to show with a decent width, the name of the company, asset tag and serial number with a font size of 9.   If i increase the font size to 10 with that setup, the barcode narrows to a thin line as it shows in the OPs image.   If i remove one of the fields, the barcode will return to normal width.     I also confirmed that a QRcode has no affect itself on this problem; however, if you add text for the QRcode it does count as a field in that text area and does add to the problem.     

Browser settings for print had no affect on the barcode width, same goes for printer preference settings.  I tried both Edge and Chrome same results.   I had seen some topics where users messed with the CSS to fix their sizing problems, may see if I can figure out the same and see if it fixes this issue.

I get the same results on the Demo server.

**Comment by davoezzz** [comment]
@domunus That is exactly what I mentioned in this update also. But I was not even getting it back with other font results as I need the model, serial and tag id on the labels. @snipe maybe you can confirm this issue as well and have some sorted out in this? Until that time we are not able to update to any newer version...

**Comment by davoezzz** [comment]
It is
