### ISSUE TITLE
is there a way to manage Scheduled Maintanence?

### ISSUE THREAD

**Issue by ajd77** [grokability/snipe-it#8274]
I work with a not for profit volunteer organisation which is a fire brigade, i'm the equipment officer there. I am looking to move away from Spreadsheet so have been trialing SnipeIt and OpenMaint as two possible platforms. 
being NFP and Volunteer, we don't have any money to purchase systems. Snipe It is my favorite of the two platforms so far as the features and UI are great. 
However i can't see a way to setup a maintenance schedule. doesn't have to be fancy just a couple of fields against the asset that sets the maintenance interval and then tracks it. 
for us it is a critical feature unfortunately, as we need to maintain fire trucks, pumps and other critical equipment. I can do it in OpenMaint, however I hate the OpenMaint UI, and trying to get the rest of the brigade to use it would be a chore. 
is it possible to set this up in SnipeIt? if so how, as I have googled till my fingers have blead and I can't find it anywhere :-)

**Comment by gilesytheking** [comment]
Currently there isn't a scheduled maintenance feature within snipe, however there have been many requests for this to be added - #6479 #6609 #1935 - I'm not too sure if this is something that will be added in V5 update  ( #6287 ).

A work around is to use the the audit feature and set your next audit date to notify you when maintenance is next required. Its not the perfect solution as some assets require maintenance for various reasons at different intervals.

**Comment by scarcamo-eyg** [comment]
> I work with a not for profit volunteer organisation which is a fire brigade, i'm the equipment officer there. I am looking to move away from Spreadsheet so have been trialing SnipeIt and OpenMaint as two possible platforms.
> being NFP and Volunteer, we don't have any money to purchase systems. Snipe It is my favorite of the two platforms so far as the features and UI are great.
> However i can't see a way to setup a maintenance schedule. doesn't have to be fancy just a couple of fields against the asset that sets the maintenance interval and then tracks it.
> for us it is a critical feature unfortunately, as we need to maintain fire trucks, pumps and other critical equipment. I can do it in OpenMaint, however I hate the OpenMaint UI, and trying to get the rest of the brigade to use it would be a chore.
> is it possible to set this up in SnipeIt? if so how, as I have googled till my fingers have blead and I can't find it anywhere :-)

Hi there, I tried to use OpenMaint for Asset and Maintenances but its installation and GUI sucks, so I found Snipe IT for assest and it greatfull for me and for my company. We are still looking for something to maintenances and checklist maintenances too, Hope Snipe IT 5 will bring us those. Do you have another idea ? cheers

**Comment by it-works** [comment]
some time later, I am also looking for a solution for regular maintenance. Snipe-IT seems to be a perfect solution, missing only this feature. Is there any way to get this programmed?

**Comment by chrisLoPresti** [comment]
Over 2 Years and this feature still hasn't been implemented? Looking into an asset solution for our company, and scheduled maintenance is a must. If there is no way to schedule maintenance and send maintenance requests for our employees, how can it be used efficiently? I love everything about the demo, its just missing this key aspect!

**Comment by snipe** [comment]
@chrisLoPresti your pull request is welcome. Otherwise please be patient.

**Comment by raitkook** [comment]
Snipe is fantastic software. Our company has over 2000 assets and this feature would be really helpful to have. We are looking for new software with better maintenance management.

**Comment by 02ms05** [comment]
+1 for this feature
 It would be great if there could be some kind of counter, so one can take preventive care of critical infrastructure on time, which is critical :D 
Anyhow, I want to thank all developers for all selfless work on this project!

**Comment by RR3US** [comment]
+1

**Comment by FMB684** [comment]
+1

**Comment by m0028** [comment]
+1

**Comment by chemnic** [comment]
Hello. I Think this is a very important feature.

At least it would be useful to have a column in the assets view that shows the last maintenance date. Then we can filter by category (things like disks and monitors don't normally need maintenance), and then we order the result by date of the last maintenance, so we know at least which device needs maintenance first.

My workaround for the moment is a SQL query that does this. In my case I need to filter by the category "Computadora/Tarjeta" ("Computer/Board"):

``` sql
SELECT
	a.asset_tag AS "ID",
	a.serial AS "Serial",
	m.name AS "Model",
	CASE
		WHEN a.assigned_type LIKE '%User' THEN CONCAT(u.first_name, ' ', u.last_name)
		WHEN a.assigned_type LIKE '%Location' THEN l.name
	END AS "Assigned to",
	MAX(am.completion_date) AS "Date"
FROM
	assets AS a
	LEFT JOIN models AS m ON a.model_id = m.id
	LEFT JOIN categories AS c ON m.category_id = c.id  
	LEFT JOIN status_labels AS sl ON a.status_id = sl.id
	LEFT JOIN users AS u ON a.assigned_to = u.id
	LEFT JOIN locations AS l ON a.assigned_to = l.id
	LEFT JOIN asset_maintenances AS am ON a.id = am.asset_id
WHERE
	c.name = "Computadora/Tarjeta"
	AND sl.archived = 0
GROUP BY a.id
ORDER BY MAX(am.completion_date) ASC
```

**Comment by hitoshioue** [comment]
I believe this feature is needed to ensure when to conduct a thorough assessment of an asset (any broken parts, expired warranty dates, etc.)
