### ISSUE TITLE
Requestable Assets - Give end user the ability to select custom fields / column headings

### ISSUE THREAD

**Issue by mckayc** [grokability/snipe-it#8276]
**Current problem:** 
If a user wants to request an asset, they can only see Model, Model No, Serial, Location, Status, and Checkin Date. If they need to checkout something more specific than just the model (examples: hard drive size, RAM, condition, Warranty expiration date, etc) they cannot do that.

There are many custom fields that we have created for our assets but none of these can be viewed when requesting an asset.

**Solution:**
If there was a drop-down "Columns" icon (the same as what an admin would see on the top right of the "All Assets" page, then a user could select the fields / columns that they want to see. This would help them in their decision for requesting an asset.

**Specific example:**
We are selling surplus at our company. We already have all the assets in SnipeIT and we have custom fields such as condition, sell price, RAM, processor, defects, etc. 

If end users could see these fields (like price) then they could know which item they could request to purchase. As it is now, users could only select a model, but they would not know specs, price, condition, etc.

**Comment by mckayc** [comment]
To be clear; this is a feature request. Sorry, I tried to label it as such but didn't see how to do that. Sorry if this is something obvious that I am missing.

**Comment by cwolfram** [comment]
We have exactly the same problem and I would love to see this happen.
