### ISSUE TITLE
Allow to transfer (checkin&checkout at once) and to change status while checking in/out

### ISSUE THREAD

**Issue by mamayer** [grokability/snipe-it#8280]
#### Expected Behavior (or desired behavior if a feature request)
_(This might be seen as multiple requests at once, but they are closely related to each other)_

I'd like to have a "transfer"-button with which I can
- change the location from "Room A" to "Stock in main-building" (yes, we have multiple stocks)
- change the status from "Ready to use" [deployable] to "Maintenance" [not deployable]
- while changing the check-in-status from "checked out" to "checked in" because it's moving into the stock

another example would be
- change the location from "User A" to "User B"
- while not changing the check-in-status - it stays "checked out"

or
- change the location from "User A" to "Trash dump"
- change the status from "Ready to use" [deployable] to "Scrap" [archived]
- while changing the check-in-status from "checked out" to "checked in" because it's moving away from the user

In short I'd like to freely change locations and statusses, while moving to stock-locations in considered being a "check in" and moving out of stock-locations is a "check out".

If we are not supposed to use SnipeIT with multiple stocks, that's ok. Than I still request an option to change the location/user from one to another without checking in. Eg. "transfer monitor 123 from Sam to Max".

-----

#### Actual Behavior

If we take an asset from one user/location and give it to an other, we always have to check it in and out again, which is quite complicated. It's not possible to move an asset in one step without checking in.

When creating assets we can't keep track in which stock the asset is, because providing a location/user on asset creation will immediately check the asset out - even if it's in a stock.

We can't change the current location of checked-in assets as SnipeIT seems to work with one stock only and everything "checked in" is supposed to be in the one-and-only stock.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode – _No need for that_
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
   - Fresh
- Version of Snipe-IT you're running 
   -  v4.7.5 build 4137 (g55ee90b25)
- Version of PHP you're running
   - 7.1.30-2+0\~20190710.21+debian9~1.gbp011d3c
- Version of MySQL/MariaDB you're running
  - whichever comes with snipe-it docker
- What OS and web server you're running Snipe-IT on
  - Debian 9.9 stretch
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
   - Docker
- ~WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error~
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
   - https://snipeit/hardware
- ~If a stacktrace is provided in the error, include that too.~
- ~Any errors that appear in your browser's error console.~
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- ~Include any additional information you can find in `storage/logs` and your webserver's logs.~
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
   - Nope

**Comment by mamayer** [comment]
Yes

>

**Comment by mamayer** [comment]
Yes it is

**Comment by hesske** [comment]
Yes, if it was possible for ones that manage assets to transfer an asset to another company via an action dropdown option that included a field for the reason for transfer as well as would send a notification to the receiving company manager that would be awesome!

**Comment by lisymart** [comment]
It's still relevant and needed.

**Comment by cbrands38** [comment]
This would be an amazing feature

**Comment by jpvlerbe** [comment]
We also sometimes find users transferring goods from one person to the next without passing through the "stock".
At that time we check in and check out again, which is a bit cumbersome.
It is not too bad, and the tool is awesome. We just have to do it that often, that it would really save on time a lot to do it in a single go.

Possibly it could be adding a bullet point that dynamically adds the fields for doing a recheck-out?
![image](https://github.com/snipe/snipe-it/assets/45239736/576a3158-a1a7-462f-b5db-ed65aa226303)

**Comment by snipe** [comment]
Duplicate of https://github.com/snipe/snipe-it/issues/5834
