### ISSUE TITLE
Snipe-it upgrade for my new ubuntu server

### ISSUE THREAD

**Issue by mahescs22** [grokability/snipe-it#8284]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
yes 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
yes
**Describe the bug**
I'm running snipe-It v4.1.8 on my ubuntu 16.04 LTS with php 7.0 & Laravel 5.4.35. I'm planning to upgrade my ubuntu server from v16.04 to v20.04 with php 7.2 or higher. So I need to know is there any upgrade option from the command line? Main thing is, this needs to be done on minimal downtime with next stable version or latest version. After the upgrade of my server, I need to recompile everything to the newer php version with their modules. Because php 7.0 not available on ubuntu 20.04. So It might throw error while this transition.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version
v4.1.8 
 - OS: [e.g. Ubuntu, CentOS]
Ubuntu 16.04
 - Web Server: [e.g. Apache, IIS]
Apache2 - 2.4.19 
- PHP Version 
7.0.33
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
Upgrade
- What OS and web server you're running Snipe-IT on
 Ubuntu 16.04 and apache2 2.4.19
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation
- Include what you've done so far in the installation, and if you got any error messages along the way.
As of now, there is  no error on my current installation
- Indicate whether or not you've manually edited any data directly in the database
Nope
I need to make migration of my server 20.04 along with the latest version of snipe-IT

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Relix360** [comment]
check this https://snipe-it.readme.io/docs/upgrading

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div>Always backup your database and configuration files before upgrading. We try very hard to make sure that all database changes are non-destructive, but you should always backup beforehand anyway. You will never regret backing up your database. You may regret not doing so, so it’s just better to get i...</div></blockquote>
