### ISSUE TITLE
Feature: Search via GET-parameter in the url eg. `/hardware?search=dell`

### ISSUE THREAD

**Issue by mamayer** [grokability/snipe-it#8288]
**Is your feature request related to a problem? Please describe.**
I'd like to use the omnibar of my browser to directly access the search-result list.

**Describe the solution you'd like**
https://snipeit/hardware?search=PC-123456 should lead to the search-result page, so I can configure my browser/etc to go to `https://snipeit/hardware?search=%s` when I enter "s"

- `s PC-123456` => `https://snipeit/hardware?search=PC-123456` => List of all assets with "PC-123456" in their name or text
- `s 01:ab:2e:cd:ef:gh` => `https://snipeit/hardware?search=01:ab:2e:cd:ef:gh` => List of all assets with "01:a8:2e:cf:ef:gh" in any of their fields, eg. mac
- `s john doe`  => `https://snipeit/hardware?search=john%20doe` =>List of all assets with "john doe" in any of their fields eg. assigned to "John Doe"

**Describe alternatives you've considered**
I'm aware that I can search for an asset tag via `https://snipeit/hardware/bytag?assetTag=%s`, eg. https://snipeit/hardware/bytag?assetTag=200300401 but I'd like that with freetext

**Additional context**
That would also be useful to directly link to locations, users, etc.

**Server (please complete the following information):**
- Is this a fresh install or an upgrade?
   - Fresh
- Version of Snipe-IT you're running 
   -  v4.7.5 build 4137 (g55ee90b25)
- Version of PHP you're running
   - 7.1.30-2+0\~20190710.21+debian9~1.gbp011d3c
- Version of MySQL/MariaDB you're running
  - whichever comes with snipe-it docker
- What OS and web server you're running Snipe-IT on
  - Debian 9.9 stretch
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
   - Docker
- ~WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error~
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
   - https://snipeit/hardware
- ~If a stacktrace is provided in the error, include that too.~
- ~Any errors that appear in your browser's error console.~
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- ~Include any additional information you can find in `storage/logs` and your webserver's logs.~
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
   - Nope

**Comment by mamayer** [comment]
Yes

**Comment by ISNL-PimP** [comment]
Very useful, this would make my life much easier. Can also see it being used to send search links to coworkers

**Comment by ISNL-PimP** [comment]
Yes still relevant

**Comment by mamayer** [comment]
Are there any updates on this?

**Comment by bharrisaurora** [comment]
This is relevant to my interests as well.  I often do an asset tag search of a garbage asset tag so I can get to the screen to type in a person's name, but it would be awesome to just search from the omnibar as stated in this request

**Comment by snipe** [comment]
This is not on the short term roadmap. That omnibar is meant for barcode scanners, to bring you directly to the asset page so you can checkin/checkout.
