### ISSUE TITLE
"whoops, looks like something went wrong" when i try to backup

### ISSUE THREAD

**Issue by Farrasta** [grokability/snipe-it#8289]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have tried to backup file, when i click 'generate file' error message appears
**To Reproduce**
1. Go to 'admin settings'
2. Click on 'generate backup'
3. See error

**Expected behavior**
there is a notification if the backup is successful

**Screenshots**
![image](https://user-images.githubusercontent.com/28496482/89202729-95723500-d5dd-11ea-986f-8ec3077bb3ee.png)

**Server (please complete the following information):**
 - Snipe-IT Version : 4.9.2

**Comment by Relix360** [comment]
can you please enable debug mode on your .env

**Comment by Farrasta** [comment]
> can you please enable debug mode on your .env

yes, i've enable it

**Comment by martinp0** [comment]
you have to fill in your .env file DB_PORT

**Comment by mostafaelnaggar2020** [comment]
Where I can Modified DB_Port
