### ISSUE TITLE
bad response MobileApp

### ISSUE THREAD

**Issue by qwe765** [grokability/snipe-it#8290]
Hello there!
Your service is pretty awesome!
I deployed your service in my organization for testing.

I am testing a mobile application (https://play.google.com/store/apps/details?id=com.diegogarciadev.assetsmanager.snipeit) and I have a problem reading the QR-code.
When I scan the QR-code with the built-in scanner, the web page opens fine, but when I do this through the application, then I get the error "Bad Responce". Search by tag gives the same result.

https://prnt.sc/ttyfhd

This is what I see in the logs httpd when I scan with the built-in scanner:

```
172.21.7.32 - - [04/Aug/2020:12:08:11 -0400] "GET /hardware/1 HTTP/1.1" 200 131121 "-" "Mozilla/5.0 (Linux; Android 9; ANE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Mobile Safari/537.36"
172.21.7.32 - - [04/Aug/2020:12:08:11 -0400] "GET /hardware/1/qr_code HTTP/1.1" 200 394 "http://mn-snipeip01.mara.local/hardware/1" "Mozilla/5.0 (Linux; Android 9; ANE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Mobile Safari/537.36"
172.21.7.32 - - [04/Aug/2020:12:08:13 -0400] "GET /api/v1/maintenances?asset_id=1&order=asc&offset=0&limit=50 HTTP/1.1" 200 21 "http://mn-snipeip01.mara.local/hardware/1" "Mozilla/5.0 (Linux; Android 9; ANE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Mobile Safari/537.36"
172.21.7.32 - - [04/Aug/2020:12:08:13 -0400] "GET /api/v1/reports/activity?item_id=1&item_type=asset&sort=created_at&order=desc&offset=0&limit=50 HTTP/1.1" 200 4299 "http://mn-snipeip01.mara.local/hardware/1" "Mozilla/5.0 (Linux; Android 9; ANE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Mobile Safari/537.36
```

This is what I see in the logs httpd when I scan with the app scanner:

```
172.21.7.32 - - [04/Aug/2020:12:07:28 -0400] "GET /api/v1/hardware/bytag/http://mn-snipeip01.mara.local/hardware/1 HTTP/1.1" 302 390 "-" "Dalvik/2.1.0 (Linux; U; Android 9; ANE-LX1 Build/HUAWEIANE-L21)"
172.21.7.32 - - [04/Aug/2020:12:07:29 -0400] "GET /login HTTP/1.1" 200 4796 "-" "Dalvik/2.1.0 (Linux; U; Android 9; ANE-LX1 Build/HUAWEIANE-L21)"
```

Please tell me where to look for the problem. Thank you.

1. Go to 'MobileApp'
2. Click on 'check-in'
3. Scan the QR-code

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.4 build 4437 (g799a93c46)
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version 7.1.33

**Smartphone (please complete the following information):**
 - Device: Huawei p20 lite
 - OS: Android 9
 - MobileApp
 - Version 0.4.3-SnipeIT

**Comment by snipe** [comment]
Unfortunately, we don't really know anything about the mobile app, since we weren't involved in it at all. Is there anything in your app logs?

**Comment by qwe765** [comment]
I thought your team was developing this application. Then I will contact the developer directly.
Have you planned to write an application for mobile devices for your service?
