### ISSUE TITLE
Can't access Snipe IT from other PC's on the Network

### ISSUE THREAD

**Issue by avon7** [grokability/snipe-it#8292]
#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

I have a new installation of Snipe IT on a VM on Oracle Virtual Box. The VM has a NIC in bridged mode. I built the SnipeIT VM on a MacOS Oracle Box host and then moved it to a Windows PC also using Oracle Box. (still using bridged mode NIC)
I can access SnipeIT from a web browser on the Oracle Box host client browser but can't access SnipeIT from any other PC on the same network. I can ping the SnipeIT Server from other machines, just can't access  SnipeIT web interface from other machines.
I have changed the APP URL in .env to reflect the new IP address of the SnipeIT server but still no luck
I don't need DNS for now, just need to access the SnipeIT server from other PC's on the same network.

**Comment by snipe** [comment]
That sounds like a networking issue, not a Snipe-IT issue.

**Comment by avon7** [comment]
> That sounds like a networking issue, not a Snipe-IT issue.

I wont discount it being a Networking issue but since I can ping the SnipeIT server from other clients I assume it's something to do with Apache2 or SnipeIT
