### ISSUE TITLE
SMTP error 

### ISSUE THREAD

**Issue by yanagha** [grokability/snipe-it#8295]
Hi,

After updating to the latest version Version v4.9.4 - build 4437 (master) it doesn't send emails. 
I am getting " Mail could not be sent. Error: undefined" message while trying to send a test mail on admin settings page.

 - Snipe-IT Version 
Version v4.9.4 - build 4437 (master)
 - OS: [e.g. Ubuntu, CentOS]
Centos
 - Web Server: [e.g. Apache, IIS]
Apache
 - PHP Version 
PHP 7.3.20 (cli) (built: Jul  7 2020 07:53:49) ( NTS )

SMTP settings (I tried with smtp.gmail.com  with TLS  587 and SSL 465)

MAIL_DRIVER=smtp
MAIL_HOST=smtp-relay.gmail.com
MAIL_PORT=587
MAIL_USERNAME=asset@mydomain.com
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=asset@mydomain
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=it-staff@mydomain.com
MAIL_REPLYTO_NAME='IT Assets Management'

**Comment by Relix360** [comment]
Hello, one question do you have a hosted mail server?

**Comment by yanagha** [comment]
We are using Gsuite.

**Comment by yanagha** [comment]
The issue is fixed. I have added server IP address in GSuite SMTP relay settings page.

**Comment by mostafaelnaggar2020** [comment]
Hi,

I have the same problem with gmail. After updating to the latest version Version v4.9.4 - build 4437 (master) it doesn't send emails.
I am getting Mail could not be sent. Error: undefined message


can you share with me your solution @yanagha

**Comment by yanagha** [comment]
> Hi,
> 
> I have the same problem with gmail. After updating to the latest version Version v4.9.4 - build 4437 (master) it doesn't send emails.
> I am getting Mail could not be sent. Error: undefined message
> 
> can you share with me your solution @yanagha

If you are using Gsuite, you should add the server IP address in SMTP relay settings and enable less secure apps to access Gmail account settings page.
