### ISSUE TITLE
Bulk Activity is not being logged

### ISSUE THREAD

**Issue by med-tascoe** [grokability/snipe-it#8299]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Bulk editing/deleting assets does not log the activity of each asset in the activity log. The actions are completely ignored.

**To Reproduce**
1. Go to 'List All' under 'Assets'
2. Click the checkbox of several assets
3. Select 'Delete' in the drop down above.
4. Click 'Go' button
5. Go to 'Activity Report' under Reports
6. See no log of that activity.

*This can be done with editing as well.

**Expected behavior**
I would expect an activity log entry for each item edited or deleted this way. 

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: v4.9.3 build 4395 (g9a2440dc4) 
 - OS: Windows Server 2016
 - Web Server: IIS 10
 - PHP Version 7.2.26

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Developer
 - Version 79.0b5

**Error Messages**
- N/A

**Additional context**
- Is this a fresh install or an upgrade?  Fresh Install
- What method you used to install Snipe-IT: manual installation
- Indicate whether or not you've manually edited any data directly in the database: I have not

I could not find any duplicate issues related to this problem. This is a pretty big issue for us as its about accountability. I tested bulk editing and deleting and neither were tracked in the activity log.

**Comment by med-tascoe** [comment]
This might be related to how the two update files in the database. The BulkAssets controller under the edit method uses " DB::table('assets')" to perform its updates where as the Assets controller uses some sort of asset object. I migtht be wrong, haven't dug into the code too much yet but that is what I see at first glance.

**Comment by med-tascoe** [comment]
Adding $asset->delete(); to the end of the foreach [foreach ($assets as $asset)] in the destroy function in BulkAssetsController.php fixes the bulk delete logging.

**Comment by med-tascoe** [comment]
Updating Assets was little bit trickier than deleting them. I revised the code in the foreach [foreach ($assets as $assetId)] in the update function in BulkAssetsController.php to be more like the update function in the AssetsController.php. Not sure if its the best way of doing it but it does provide the functionality I am looking for, updating the assets and tracking them in the activity log.

```
// Find the asset and update the fields with the new data.
if($asset = Asset::find($assetId)) {
    // Process general items with a if it exists, update it approach.
    $items = array(
        'purchase_date',
        'model_id',
        'order_number',
        'requestable',
        'status_id',
        'supplier_id',
        'warranty_months',
    );
    foreach($items as $item) {
        if($request->filled($item)) {
            $asset->{$item} = $request->input($item, null);
        }
    }
    // Purchase cost needs special attention because of it being a float.
    if ($request->filled('purchase_cost')) {
        $asset->purchase_cost = Helper::ParseFloat($request->input('purchase_cost', null));
    }
    // Update company id but check for clear.
    if ($request->filled('company_id')) {
        $asset->company_id = $request->input('company_id');
        if ($request->input('company_id')=="clear") {
            $asset->company_id = null;
        }
    }
    // Update the returned location. If update real location is set to 1, update the location id of the asset to the returned location.
    if ($request->filled('rtd_location_id')) {
        $asset->rtd_location_id = $request->input('rtd_location_id', null);
        if (($request->filled('update_real_loc')) && (($request->input('update_real_loc')) == '1')) {
            $asset->location_id = $request->input('rtd_location_id', null);
        }
    }
    // Save the asset.
    $asset->save();
}
```

**Comment by med-tascoe** [comment]
Yes, this is still relevant and is still an issue. As far as I know it has not been fixed. Hopefully this might be resolved in 5.x?

**Comment by kno005** [comment]
This is still relevant as we have encountered this also.

**Comment by snipe** [comment]
I believe this was fixed a while back
