### ISSUE TITLE
I have NO idea what I am doing

### ISSUE THREAD

**Issue by rtellis2020** [grokability/snipe-it#8303]
HOW do you edit/change the .env file for Snipe IT??

I inherited this linux app from a guy that is no longer with us and while I can see the current .env file in the backup; I have NO idea how to go into the cli and edit/overwrite the one that is there with the mail configuration added to it....

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snowmobile2004** [comment]
cd /var/www/snipeit
sudo nano .env

Thats how you edit the file if you used the installer to install. Your install dir may be something different than /var/www/snipeit, but once you get to the install directory just do nano .env

**Comment by byrontuckett** [comment]
@rtellis2020 I feel for you.

I'm assuming this was deployed to a vm and it sounds like you are new to working around a Laravel app - so if you can do this with a test copy of the vm that would be preferable.

You'll have to connect into the virtual machine via ssh, navigate to the directory, usually something like `/var/www/[sitenamehere]` or `/opt`.  find the .env file and edit using vim or nano. (google these if you need assistance with how to use it)

Once you've edited the file, you'll need to the re-cache the configuration.  in that same directory
```php
php artisan config:cache
```
Little hard to help without knowing more about your environment (you missed entering the data in the issue)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
