### ISSUE TITLE
Can manually send checkout to emails to users after first time imported all of assets data?

### ISSUE THREAD

**Issue by conan522** [grokability/snipe-it#8304]
Thanks for your amazing job and good system.

After first time imported all of assets data into snipe-IT system.
I would like send checkout email to all of checkout to users.
Could set option to manually to do this?

Thanks again.

**Comment by snipe** [comment]
That's not currently an option, but in the upcoming v5 I believe we have an artisan command that can send a user inventory email, which might work for your needs.

**Comment by conan522** [comment]
Thank you very much. Have a nice day.
