### ISSUE TITLE
Cant view or create users

### ISSUE THREAD

**Issue by mintyhippoxyz** [grokability/snipe-it#8321]
**Describe the bug**
`/users` shows `Loading... please wait....` message and users never load

This request seems to be the culprit, pending in console, no response
`/api/v1/users?deleted=false&company_id=&order=asc&offset=0&limit=20`

If I go to `/api/v1/users` directly I get a `The page isn’t redirecting properly` message in Firefox and in Chrome a quick `too many redirects message` and then it redirects to `/`.

If I ignore and try to create a user, the POST request hangs and user is not created in database.

**Server**
 - Snipe-IT Version 4.9.4
 - Gentoo - 5.4.57 vanilla
 - Docker install with database on another host

**Additional context**
- Fresh installation. I have been able to add Company, Categories, Manufacturers, and an Asset without issue.
- I did not have this issue with a local test installation on my workstation. Notable differences:
-- mysql container instead of a standalone db server
-- `docker run` instead of `docker stack/service`
-- no ssl vs ssl
- With both installs I also see many pages doing a GET to /uploads with 403 response. I can still attach files with both though.
- Console warnings about cookies: Some cookies are misusing the recommended “sameSite“ attribute
- Nothing interesting in docker logs or with debug enabled

**Comment by mintyhippoxyz** [comment]
Here's what I see when going to `/api/v1/users?deleted=false&company_id=&order=asc&offset=0&limit=20` directly.
I get the impression this endpoint doesn't think I'm logged in and gets stuck in a redirect loop.
![screen](https://user-images.githubusercontent.com/1329241/90171800-a7836e80-dd67-11ea-83cf-30707ae16fbe.PNG)

**Comment by mintyhippoxyz** [comment]
Tried `SECURE_COOKIES=true` and that got rid of the cookie warning but the redirect issue still exists.

**Comment by mintyhippoxyz** [comment]
I've now tried several re-installs with same result. `develop`, `latest`, `v4.9.4`, `v4.8.0`, `v4.6.15`

Each time I started with a new database and cleaned out everything but by my ssl cert from the volume.

Another observation, something similar is happening with curl requests to that endpoint using an API key too, hangs for ~30m then responds with a "Server Error" message.

I'm at a loss... Any ideas how I can troubleshoot this further or is there any more information I can provide that would be useful?

**Comment by mintyhippoxyz** [comment]
Ok, now I'm getting somewhere...

Missed it last time but [laravel.log](https://github.com/snipe/snipe-it/files/5086896/laravel.log) shows up after waiting for a curl request to timeout and has some "MySQL server has gone away" errors. It's interesting that none of my requests through a browser produce the same.

Anyways, this seems to be the problematic part of the query unless it's just getting logged without quotes?
```
`assets`.`assigned_type` = App\Models\User
```

This is on MariaDB 10.1.31 and currently running the `latest` snipe container.

**Comment by Go2ClassPoorYorick** [comment]
I'm now seeing this behavior with a docker deployment after upgrading to v5.0.5, including the API redirect loop if i attempt to manually call the end point.

**Comment by Go2ClassPoorYorick** [comment]
Interestingly, creating and listing users via the asset window continues to work, although I am getting 500's when saving (it still goes through?)

**Comment by Go2ClassPoorYorick** [comment]
I believe this issue to be the same as #8636 based on receiving the following in debug mode.
`Column not found: 1054 Unknown column 'accessories_users.note' in 'field list'`

Unable to run the php upgrade script because docker is running it as admin.

**Comment by Go2ClassPoorYorick** [comment]
I apologize for not RTFM- running `php artisan migrate` in the shell of the docker container appears to have repaired this issue.

**Comment by snipe** [comment]
Glad you're sorted :)
