### ISSUE TITLE
Cost and Depreciation correction

### ISSUE THREAD

**Issue by henkbotma** [grokability/snipe-it#8322]
**Server (please complete the following information):**
 - Snipe-IT Version v4.9.4 build 4437 (g799a93c46)
OS: [e.g. Ubuntu, CentOS] Docker
Web Server: [e.g. Apache, IIS] Docker
PHP Version Docker 7.1.33-16+ubuntu16.04.1+deb.sury.org+1

**Is your feature request related to a problem? Please describe.**
How will correction of the cost and the depreciation be done in the middle of the financial year?

**Describe the solution you'd like**
A way to disclose of the correction and also the changes to current depreciation.

**Describe alternatives you've considered**
In GL it is done via a journal. Can this be done with Snipe-It?

**Additional context**
None

**Comment by bryceprutsos** [comment]
This would be nice to have. We have assets that we are putting into our system that are half depreciated put the system acts as if they are new.
