### ISSUE TITLE
Field sets can no longer be assigned

### ISSUE THREAD

**Issue by TormundGiant** [grokability/snipe-it#8333]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I can add a model as usual, but I cannot assign a field set to the model. This is no longer possible since the last version. I've tried everything.

**To Reproduce**
1. Go to 'Models'
2. Click on 'add'
3. Insert your description etc., try to assign the field set here
4. No Field Set for the new Models

**Expected behavior**
When I add a model I want to be able to specify the field set in the same window.

**Screenshots**
The curious thing is that the field set assignments on old devices have also disappeared. However, the assignment in the tab still exists.
In the following picture you can see that 1 model is assigned to a field set and the newest one not:
![snipe1](https://user-images.githubusercontent.com/57493045/90402493-d1a69a80-e09f-11ea-8e21-9da7abcc007d.PNG)

Here you can see, that the possibility to add models to a field set is gone:
![snipe2](https://user-images.githubusercontent.com/57493045/90402525-dd925c80-e09f-11ea-8a96-90f0605cb739.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.3
 - OS:  Ubuntu

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 79.0

**Comment by snipe** [comment]
Unfortunately, I cannot reproduce this anywhere (locally, online demo, etc), so I'm not sure how to help here.

New: 
<img width="835" alt="Screen Shot 2020-08-17 at 11 59 59 AM" src="https://user-images.githubusercontent.com/197404/90433771-3b637c00-e081-11ea-8f6f-e40046161137.png">

Edit: 
<img width="885" alt="Screen Shot 2020-08-17 at 12 01 01 PM" src="https://user-images.githubusercontent.com/197404/90433843-59c97780-e081-11ea-91b0-c3b88550cdda.png">

**Comment by TormundGiant** [comment]
Do you have any idea what it could be? Because I haven't changed anything in the settings ...

**Comment by SujectName** [comment]
Our SnipeIT install has the same problem. No changes made to the field sets.
Version v4.9.3 - build 4395 (master), Server 2019

Desktop Win10, both in Edge and Chrome browsers

**Comment by snipe** [comment]
I don't have any idea. We didn't make any changes to field sets in that version. Anything in your browser's console log?

**Comment by TormundGiant** [comment]
I got a solution for it.
We´ve upgraded to the newest version and now everything is working.

If you need any assistance @SujectName you can leave me a PM i will help you out to do that.

Thank you @snipe for your assistance. We couldnt locate the issue which is responsible for this error.

**Comment by SujectName** [comment]
Sorry @TormundGiant I cannot find a way to PM. You just upgraded to 4.9.4 and it was fixed?
