### ISSUE TITLE
Error when trying to backup Snipe-IT from Web browser and command line

### ISSUE THREAD

**Issue by deanpitt** [grokability/snipe-it#8334]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
 Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified

**To Reproduce**
1. Go to 'admin'
2. Click on 'Backups'
3. Click 'Generate Backup"

**Expected behavior**
A backup should be generated and listed in browser and show up in backup folder
![2020-08-17 15_40_43-](https://user-images.githubusercontent.com/69824273/90451237-395ce580-e0a0-11ea-9fca-c42e46f6f0c2.jpg)
![2020-08-17 15_45_57-Standard - ASG-RemoteDesktop 2020](https://user-images.githubusercontent.com/69824273/90451501-d029a200-e0a0-11ea-9be0-7c7a2f78703e.jpg)

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.4 build 4437 (g799a93c46)
 - OS: [e.g. Ubuntu, CentOS] Windows Server 2019
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.4.8

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 2004
 - Browser [e.g. chrome, safari] New Microsoft Edge
 - Version [e.g. 22]  Version 85.0.564.30 (Official build) beta (64-bit)

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
 Error: Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified. . #0 C:\inetpub\wwwroot\Snipe-IT\vendor\spatie\db-dumper\src\DbDumper.php(246): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 C:\inetpub\wwwroot\Snipe-IT\vendor\spatie\db-dumper\src\Databases\MySql.php(148): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'C:\\inetpub\\wwwr

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. No

- Include any additional information you can find in `storage/logs` and your webserver's logs. N/A

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on Windows Server 2019 with MariaDB 10.5, IIS version 10.0.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual with Git
- Include what you've done so far in the installation, and if you got any error messages along the way. Checked permissions on storage folder, windows temp folder.  Both have IUSR and IIS_USR as modify

- Indicate whether or not you've manually edited any data directly in the database -No

My DB path is shown in the screenshot.  It is what was shown me by running the CMD line script.
![2020-08-17 15_53_16-Standard - ASG-RemoteDesktop 2020](https://user-images.githubusercontent.com/69824273/90452109-437fe380-e0a2-11ea-9f2b-d95d8c17a94b.jpg)

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
That looks more to me like the backup directory where backups are stored *or* the temp directory doesn't exist, not that mysqldump itself doesn't exist (or is not writable).

**Comment by deanpitt** [comment]
![2020-08-17 16_09_36-Standard - ASG-RemoteDesktop 2020](https://user-images.githubusercontent.com/69824273/90452913-221ff700-e0a4-11ea-913e-916c69131c1d.jpg)
![2020-08-17 16_10_00-Standard - ASG-RemoteDesktop 2020](https://user-images.githubusercontent.com/69824273/90452918-251ae780-e0a4-11ea-95fb-c554cfca30d1.jpg)
Tell me if I am not understanding what you said.

**Comment by deanpitt** [comment]
Can you give me a little more information.  The folders are there, if these are the ones you are talking about.  I am going to backup Snipe-IT with Microsoft DPM server anyway, but having a file to backup to tape is better than a whole folder.

**Comment by snipe** [comment]
Are those directories writable by the server?

**Comment by deanpitt** [comment]
![2020-08-26 08_54_26-Standard - ASG-RemoteDesktop 2020](https://user-images.githubusercontent.com/69824273/91326996-d93e0180-e779-11ea-8ffc-11306e8d1b8a.jpg)
![2020-08-26 08_53_20-Standard - ASG-RemoteDesktop 2020](https://user-images.githubusercontent.com/69824273/91327005-dba05b80-e779-11ea-8782-96c7b5390bdb.jpg)

**Comment by snipe** [comment]
There is a temp directory that the backup system uses (`storage/app/backup-temp`, IIRC) which would need to be writable by the web server as well.

**Comment by beemanaged** [comment]
For anyone else having this issue: after going through all the related tickets and confirming all permissions and dependencies, my resolution for this exact problem was to change my DB_dump_path with double quotes around it.
I'm on snipe version 6.0.10 running MySQL 5.7
So my dump path ended up looking like this - "C:\\PROGRA~1\\MySQL\\MYSQLS~1.7\\bin" (note the tilde' line does not render in all browsers, so refer to the photos in this thread).
After running `php artisan config:cache` I was able to do a backup again.
