### ISSUE TITLE
php artisan snipeit: create-admin getting php warning and fatal error autoload.php line 17

### ISSUE THREAD

**Issue by JKGuillen** [grokability/snipe-it#8336]
#### Expected Behavior (or desired behavior if a feature request)
#php artisan snipeit: create-admin
(what you expect to happen goes here)
I used the documentation in order to create an admin account:
https://snipe-it.readme.io/docs/create-an-admin
I was expecting it to create an admin user due to our LDAP no longer authenticating. We changed the name of our DC which might be the cause if someone directly pointed to that server for LDAP authentication which a few of our other servers did but was able to force an admin username/password for those.

#### Actual Behavior

(what actually happens goes here)

When I run the command from the documentation I get the error below:
![image](https://user-images.githubusercontent.com/47372400/90441258-a6737980-e0a6-11ea-9c8b-636e7c6a4260.png)

Just wondering what other steps to take if there is no account documented for the set up of this server. I see here in a different forum where someone was getting a similar message here: https://github.com/snipe/snipe-it/issues/6199 and you insisted to go to https://snipe-it.readme.io/docs/installation-issues#section-warning-requirebootstrapvendorautoloadphp-failed-to-open-stream-no-such-file-or-directory in order to fix the error but seems like that is talking about errors installing? I have looked in the back end for a while and tried to research to see if there any any backend ldap files in order to look through but have not found any, if there is this might be an easy fix. I run version 4.4.1 and the admin command should work past v3 but not quite sure the problem unless i just run docker compose to fix the issue on a preexisting install.

**Comment by snipe** [comment]
Did you try running `composer install`? If so, what was the output?

**Comment by JKGuillen** [comment]
Appreciate you getting back to me so quickly, have been out of the office so sorry for the delayed response. Is there no backend files for LDAP that the GUI writes to in order to use it for me to alter? Might make things simpler instead of digging through trying to force an admin seeing how there is no documentation on how this is setup or if it was even setup correctly to begin with. If there is LDAP configuration files I can alter instead of going through the web GUI would be of great help. I have did somethings below but still need to do more work.

After installing composer to the directory since I was getting command not found, I am still getting command not found so I need to try it with a global install to see if that will work. On the other hand I am getting a new errors now as shown below:
![image](https://user-images.githubusercontent.com/47372400/90920593-91ecf500-e3b6-11ea-9abd-df68f3c8186b.png)
Looks like a config file is overriding the actual one being used causing it to use forge @ localhost.

**Comment by snipe** [comment]
It doesn't override, it only falls back to those forge options if it doesn't find a value for the database in the .env file. Check your .env and make sure these values are filled in with whatever your database name/username/password is:

```
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit-local
DB_USERNAME=snipeit-local
DB_PASSWORD=snipeit-local
DB_PREFIX=null
DB_DUMP_PATH='/usr/local/bin'
```
