### ISSUE TITLE
Documentation Change - Idea

### ISSUE THREAD

**Issue by coatmaker618** [grokability/snipe-it#8337]
I found the resources at https://snipe-it.readme.io/docs VERY helpful and was able to get to my Pre-Flight page without any major issues :)

There was, however, one minor documentation issue.

In truth more of a documentation issue than anything else--**namely the fact that the "Server Config" instructions comes AFTER Installation despite being required for "Pre-Flight & Setup" step 7 of the Installation Phase**.  When following the instructions on the readme page, I did not notice any mention of modifying apache config during the "installation" phase (certainly no config files).  The problem is that I found this confusing as I was expecting to see the Pre-Flight page in step 7 of the installation (titled "Pre-Flight & Setup").  Of course, I got the default apache config page instead.  I was getting ready to post a bug report aka request for help on here but I happened to find someone else mentioning the config of Apache file in a similar issue.  Having found that I looked at my Apache config, saw it was using the default config, skipped ahead & modified the Apache page as recommended in the "Server Config" phase.  Now the Pre-Flight page loads no problem!  However, this could be made more clear to newcomers as it's easy to mistake this for a major issue.

Also, if we're talking about modifying the documentation, **why not also add something for running certbot as a quick HTTPS solution**?  ~~Are there any known issues with certbot or is it known to "just work"?~~ Can confirm it very much "just works".

I'm looking forward to using Snipe-IT and very much appreciate the work that has already clearly gone into the docs (and of course the rest of the project).

**Comment by sjackson0109** [comment]
Certbot gets my vote

**Comment by snipe** [comment]
We're a little hamstrung getting v5 RC ready for release, but I can assign this to @uberbrady to see if he can take a stab at it - otherwise either of you are welcome to add that to the docs.

**Comment by coatmaker618** [comment]
Cool! Kick butt with v5 :)

I'd be happy to change the docs...though I don't know how to change the docs. >_>

**Comment by snipe** [comment]
There's a link at the top of every page that says "suggest edits", which will effectively allow to create a PR against the existing docs. We can then approve them and they'll be added to the documentation on the public end :)

<img width="1158" alt="Server_Configuration" src="https://user-images.githubusercontent.com/197404/91250447-e91ffc00-e70d-11ea-971a-3e687ba71b7b.png">

**Comment by coatmaker618** [comment]
Cool, I'll take a look.  Thanks :)

**Comment by coatmaker618** [comment]
Alright, document revisions suggested. Closing issue!  Thanks again for the hand-holding @snipe.
