### ISSUE TITLE
Maps are not loading with an error

### ISSUE THREAD

**Issue by shellsmustang** [grokability/snipe-it#8338]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When viewing a location the map is not displaying and error in developers view

Using v4.9.4 - build 4437 

Error in console in

Refused to load the image 'https://maps.googleapis.com/maps/api/staticmap?center=Jeebropilly%2CJeebropilly+Queensland+AU+4340&size=500x300&maptype=roadmap&key={APIKEYREMOVED]' because it violates the following Content Security Policy directive: "img-src 'self' data: gravatar.com".

This works in previous version v4.9.2 - build 4352

**To Reproduce**
1. Click on An Asset
2. Click on location - no map is displayed

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version  v4.9.4 - build 4437 
 - OS: Ubuntu 20.04
 - Web Server: Apache 2
 - PHP Version 7.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 84.0.4147.125

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

Same issue on demo

**Additional context**
![2020-08-19 12_03_11-Window](https://user-images.githubusercontent.com/69881578/90583652-08052680-e214-11ea-8d63-7546189fbd8e.png)

- Is this a fresh install or an upgrade? fresh install
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
This is fixed on master and will be in the next release.
