### ISSUE TITLE
Possible False Positive on Config File Issue (.env) during Pre-Flight

### ISSUE THREAD

**Issue by coatmaker618** [grokability/snipe-it#8346]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
On preflight page I see an error with my config file that says (under notes):

> Please make sure your .env is not  readable by the outside world via web browser. You don't ever want  anyone able to see that file. Ever. Ever ever. An exposed .env file can disclose sensitive data about your system and database. Click here to check now (This should return a file not found or forbidden error.)

However, when I click on the provided link I get an error 404.  What exactly is the check being done here? What permissions is it looking for & what is the best recommended setting?  I created a www-data user who owns all files in my snipe-it folder and has 664 on everything except the env which is owned by server & is also 664.  I did not see a preferred user/permissions recommendations anywhere, including the common-issues page OR the setup page--but if this is detailed, please feel free to point me to it!

**To Reproduce**
1. Go to 'Pre-Flight Page'
2. See error

**Expected behavior**
No warning, a green light on ".env" setting.

**Screenshots**
Not applicable

**Server (please complete the following information):**
 - Snipe-IT Version ??? (~1 weeks old, unsure how to find version number)
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version 7.2.24

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Error Messages**
See quote above

**Additional context**
Fresh install using git repo

**Comment by sjackson0109** [comment]
This same issue happens with the pre-flight check on the .env file I side the docker application.

**Comment by snipe** [comment]
As long as you can't see the .env, you're good. The point is just to make sure it's not publicly viewable. That varies on different systems, so the checks aren't always perfect, but as long as you can't access your .env from a web browser, you're golden.

**Comment by coatmaker618** [comment]
Awesome. Glad to hear that as long as the page doesn't load there's no security issue!

Thanks :)
