### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by NickNck** [grokability/snipe-it#8347]
Hi there is an issue with the notifications flag when an item has reached the alert quantity level. Lets say an items alert level is 2 and the available quantity is equivalent to that, the notification will alert me of this with no issue, but when the quantity is updated (above 2) the notification still stays in the list and does not go away once the quantity is updated

**Comment by snipe** [comment]
Check your alert threshold in your Notification settings. If you set this to 0, it should only alert when you are at or below exactly the minimum quantity.

Settings > Notifications 

<img width="324" alt="Screen Shot 2020-08-25 at 8 04 56 PM" src="https://user-images.githubusercontent.com/197404/91250620-52077400-e70e-11ea-8586-0176bb27f559.png">
