### ISSUE TITLE
Fix the representation of the LDAP filter

### ISSUE THREAD

**Issue by sjackson0109** [grokability/snipe-it#8357]
Users are required to enter LDAP filters such as:

"cn=*"
"&(cn=*)"
or
"&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))"

The syntax is wrong here.
Even on your own documentation, it's obviousy wrong:
https://snipe-it.readme.io/docs/ldap-sync-login

> The search filter for the LDAP query.
> 
> For AD filter enabled users using:
> &(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
> 
> **This should EXCLUDE the final enclosing parentheses**. For example, &(cn=*), NOT (&(cn=*)).

I disagree with excluding specific syntax set out in open LDAP standards.  To make sure this works, it might be worth considering how the Active Directory Users and Computers advanced search performs custom-ldap-searches.
You can enter ANY and ALL of the above sarches - and it will return the results.  This is because it always wraps the query with:
"(&" + $Query + ")"

Fix the LDAP Filter requirement so this is an RFC compliant LDAP Filter.
such as:
(&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))
(&(objectclass=user)(mail=*))

Atlassian have written some clear examples:
https://confluence.atlassian.com/kb/how-to-write-ldap-search-filters-792496933.html

Both current and proper LDAP filters should work short-term. Long-term the proper RFC compliant LDAP filter should work.

Server-Info
 - Snipe-IT Version : 4.9.4
 - OS: Ubuntu16.04
 - Web Server: unknown - docker web-service, assumed nginx
 - PHP Version: 7.1

**Comment by snipe** [comment]
All of LDAP integration is rewritten in v5

**Comment by uberbrady** [comment]
First off, I think I agree with you. It's probably best to just use the standard the way it's intended; having to use a 'weird' representation for the LDAP filter is just confusing for our users.

To @snipe's point, though - I think that in v5, it will continue to wrap the filter in parentheses if the final surrounding parentheses aren't there. But if they are, it won't add an extraneous set.

So I think it's fixed in v5. Can you check out our `develop` branch and give it a whirl, @sjackson0109?

**Comment by sjackson0109** [comment]
Hello, i've not got an environment I can play with the development branch with. Although if you tell me that v5 uses RFC compliant LDAP filters, then am happy to take your word for it :)

**Comment by sjackson0109** [comment]
Hi @uberbrady - sorry i mis-read this statement:
"I think that in v5, it will continue to wrap the filter in parentheses if the final surrounding parentheses aren't there. But if they are, it won't add an extraneous set."
Please note, for ActiveDirectory/LDAP.. an LDAP query can have "((CN=*))" or "(CN=*)" - the double parenthesis is still allowed.  Not sure about other LDAP servers... so no need to over complicate the filter inclusion/exclusion of the parenthesis if they exist or not.

**Comment by uberbrady** [comment]
v5 permits RFC-compliant LDAP filters, but remains backwards-compatible with pre-v5 filters. If your filter starts with an `(`, Snipe-IT will not add additional parentheses.
