### ISSUE TITLE
Asset defect

### ISSUE THREAD

**Issue by ajd77** [grokability/snipe-it#8360]
**Server (please complete the following information):**
 - Snipe-IT Version  - 4.9
 - OS: [e.g. Ubuntu, CentOS] Ubuntu on Docker
 - Web Server: [e.g. Apache, IIS] MYSQL - Docker
 - PHP Version 

looking at using Snipe-IT for asset management at our fire station, have started to play around with it and can't seem to see a way to raise a defect with an asset. for example if I have a peice of equipment that is broken there doesn't appear to be a way to raise an issue associated with it, then a workflow for repairs. this would be very valuable feature and something I would've thought of as a standard item

**Comment by snipe** [comment]
We do not have a helpdesk/ticketing system as part of Snipe-IT. The best way you could handle this currently is by using asset maintenances and status labels.
