### ISSUE TITLE
am getting Allowed memory size of 268435456 bytes exhausted (tried to allocate 82374328 bytes) when upload bigger pdf file(60 mb)

### ISSUE THREAD

**Issue by azadvarun** [grokability/snipe-it#8362]
am getting Allowed memory size of 268435456 bytes exhausted (tried to allocate 82374328 bytes) when upload bigger pdf file

**Comment by snipe** [comment]
You'll need to increase the memory PHP is allocated:
https://www.groovypost.com/howto/howto/how-to-solve-php-fatal-error-allowed-memory-size-of-8388608-bytes-exhausted/

<blockquote><img src="https://www.groovypost.com/wp-content/uploads/2019/01/programing_code_Website_Admin_IT_Featured.jpg" width="48" align="right"><div><img src="https://www.groovypost.com/wp-content/uploads/2017/11/cropped-gp-logo-512-192x192.png" height="14"> groovyPost</div><div><strong><a href="https://www.groovypost.com/howto/howto/how-to-solve-php-fatal-error-allowed-memory-size-of-8388608-bytes-exhausted/">How to Solve PHP Fatal error: Allowed memory size of 8388608 bytes exhausted</a></strong></div><div>One of the most common and frustrating errors encountered by PHP coders reads: “Fatal error: Allowed memory size of 8388608 bytes exhausted…” followed by</div></blockquote>
