### ISSUE TITLE
Printing labels has a blank page.

### ISSUE THREAD

**Issue by AgentEddie99** [grokability/snipe-it#8367]
When generating the labels it has a blank page in the middle of the 2 labels.

Printer: Brother QL-570
Labels: DK-11201

Screenshots attached.
![2020-08-26_16h38_58](https://user-images.githubusercontent.com/56587828/91270145-87b66680-e7bb-11ea-943b-2c47a28a1360.png)
![2020-08-26_16h39_04](https://user-images.githubusercontent.com/56587828/91270151-88e79380-e7bb-11ea-9553-78eec452d610.png)

Is there a way that I can remove the blank pages?

**Comment by paulo-maia** [comment]
Hi @AgentEddie99, I have the same problem. Just acquired a Brother QL-800 and still wasn't able to print a label correctly... (using 62mm black/red tape)
