### ISSUE TITLE
I am new to Snipe-IT 

### ISSUE THREAD

**Issue by assotan** [grokability/snipe-it#8375]
I have very basic issue about server installation. In an organisation do we need to install this on company's server or we can install our own server first and can then give access to others.

**Comment by snipe** [comment]
@assotan - I'm not sure what you mean by "company server" vs "your own server", but you can install it wherever you like - but if you install it on a local server and want others to be able to access it, you'll need to be able to set up the DNS and networking to allow a web app from inside your network to be reachable from outside just your local network
