### ISSUE TITLE
Unable to load the Web-UI after a fresh installation on Centos-7

### ISSUE THREAD

**Issue by vishakh-falcon** [grokability/snipe-it#8387]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I'm trying to install the application on an EC2 instance Centos-7 Server. 
As a prereq, I did 
- Installed php php-bcmath php-devel php-gd php-ldap php-mbstring php-mysql php-mysqlnd php-pdo php-xml
- Performed a full update on the server
My PHP version: PHP 5.4.16
- Then I followed as the exact steps as described in the installation documentation wherein I did use the installation script (install.sh and snipeit.sh). During the installation,  did see the below log

`Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Generating optimized autoload files
Deprecation Notice: Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:202
Deprecation Notice: Class App\Http\Transformers\DepartmentsTransformer located in ./app/Http/Transformers/DepartmentsTranformer.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:202
Deprecation Notice: Class App\Notifications\RequestAssetCancelationNotification located in ./app/Notifications/RequestAssetCancelation.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:202
PHP Parse error:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /var/www/snipeit/vendor/zendframework/zend-diactoros/src/functions/marshal_headers_from_sapi.php on line 10

Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /var/www/snipeit/vendor/zendframework/zend-diactoros/src/functions/marshal_headers_from_sapi.php on line 10
* Generating the application key.
* Artisan Migrate.
* Creating scheduler cron.
no crontab for root
./snipeit.sh: line 234: firewall-cmd: command not found
* Configuring SELinux.
* Setting Apache httpd to start on boot and starting service.
  Q. Do you want to configure mail server settings? (y/n) n

  ***Open http://<server-host-address> to login to Snipe-IT.***

* Cleaning up...
* Finished!`

**Issue** After the installation, I'm unable to load/get the application Web-UI.
(server address, network and other stuff is checked/working)

**To Reproduce**
1. Perform installation via install.sh & snipeit.sh
2. After the installation, try opening the application on a web browser

**Expected behavior**
I would expect the web-ui to be accessible (or) available after a successful installation

**Server (please complete the following information):**
 - Snipe-IT Version: v4.9.4
 - OS: CentOS-7
 - Web Server: HTTPD
 - PHP Version : 5.4.16

**Desktop (please complete the following information):**
 - OS: MacOS-10.15.6
 - Browser: Chrome, Safari, FireFox
 - Version: Latest version

**Additional context**
- Is this a fresh install or an upgrade? --> Fresh Install
- What OS and web server you're running Snipe-IT on: ---> CentOS-7 | httpd
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --> install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database --> No

**Comment by laTruffe79** [comment]
idem...

**Comment by snipe** [comment]
> My PHP version: PHP 5.4.16

PHP v7.1.3 or greater is required for Snipe-IT. You'd want to upgrade your cli version and your apache/nginx/etc version for this to work.

**Comment by Tonylaoshi2018** [comment]
i have same problem.  Any suggestions?

**Comment by laTruffe79** [comment]
Don't expect a satisfying solution all that snipe can do for you is to delete your post.
My solution install ocs inventory +glpi, and you know what ? It works like charm ! Kiss snipe ! Go on playing with your old laravel 5.5 !

**Comment by Relix360** [comment]
@Tonylaoshi2018 what php version do you have?

**Comment by snipe** [comment]
@Tonylaoshi2018 You'd need to give us a little more information - what's in your error logs, etc.

**Comment by Tonylaoshi2018** [comment]
@Relix360@snipe Thanks for your reply. I had php 5.4.16 when i got error. I confirm that PHP 5.4.16 was the root cause. After upgrading php 5.4.16 to PHP 7.1.3, I did another Fresh install. There is no error. Pre-Flight UI cames  without any problem.

**Comment by snipe** [comment]
@Tonylaoshi2018 Glad you got everything sorted!
