### ISSUE TITLE
Feature Request: QR Code for Consumables (similar to #6857)

### ISSUE THREAD

**Issue by samuelT2** [grokability/snipe-it#8391]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.9.4 - build 4437
 - OS: CloudLinux, v7.8
 - Web Server: ?
 - PHP Version: 7.4.8

**Is your feature request related to a problem? Please describe.**
I'm not able to create QR codes for Consumables.

**Describe the solution you'd like**
Please allow to generate labels (same as for Assets).

**Additional context**
We're running a small brewery and I'd like to add the ingredients as consumables. I'd like to print the labels, put them on the ingredient and book them in/out via scanning with my mobile.

Let me know if you need more information from my end!

**Comment by samuelT2** [comment]
Already reported in #3957 and #6857, would be great to have that functionality soon!

**Comment by snipe** [comment]
Once v5 is out and we've had a chance to do some refactoring, that will likely happen

**Comment by samuelT2** [comment]
Sounds great, thank you!

**Comment by 01ste02** [comment]
I am currently working on this feature, but was wondering if someone could tell me in what file the qr-codes get generated? Otherwise I have most of it figured out.
