### ISSUE TITLE
SnipeIT v5.0.0-beta-3.0 - Docker setup error

### ISSUE THREAD

**Issue by fenpaws** [grokability/snipe-it#8393]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After deploying the latest beta (v5.0.0-beta-3.0) of Snipe-IT with docker the setup screen seams to miss the CSS. If I ignore that and continue and click `Next: Create Database Tables` I get a QueryExecption error.
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist (SQL: select `ldap_enabled`, `ldap_server`, `ldap_uname`, `ldap_pword`, `ldap_basedn`, `ldap_filter`, `ldap_username_field`, `ldap_lname_field`, `ldap_fname_field`, `ldap_auth_filter_query`, `ldap_version`, `ldap_active_flag`, `ldap_emp_num`, `ldap_email`, `ldap_server_cert_ignore`, `ldap_port`, `ldap_tls`, `ldap_pw_sync`, `is_ad`, `ad_domain`, `ad_append_domain` from `settings` limit 1)
```

**To Reproduce**
1. create a docker container with the latest build of snipe-it  and a MariaDB
2. try to go through the setup'

**Expected behavior**
1. Snipe-IT Pre-Flight should have a CSS applied to it
2. The scenery database tables should be created

**Screenshots**
![firefox_kHxTEC73b3](https://user-images.githubusercontent.com/29946173/91817627-a0000880-ec35-11ea-8d1c-7453a57f4efb.png)
![firefox_WFVgBlWdXu](https://user-images.githubusercontent.com/29946173/91817662-a2626280-ec35-11ea-86a4-88f0deccdfcf.png)

**Server (please complete the following information):**
- the latest docker build: v5.0.0-beta-3.0

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser Firefox Developer
 - Version 81.0b2 (64-bit)

**Error Messages**
1. These are errors i get from Laravel on the Database setup
https://gist.github.com/fenpaws/2c5715eaeed367d7c1c0f42763251fab
https://gist.github.com/fenpaws/b3efe84656b1e75d638f013bd25a1ccc

2. I et this error from the browser console on the Pre-Flight page
```
The resource from “http://130.180.1.38:4458/setup” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

**Additional context**
Its a fresh installation, i provide my [docker-compose.yml](https://gist.github.com/fenpaws/f504a316a3ea5956f9899e8278f485c4)

**Comment by uberbrady** [comment]
We definitely had a settings bug in the early v5 betas, but we ended up working around it before the formal release of v5.
