### ISSUE TITLE
Unable to Login no error

### ISSUE THREAD

**Issue by ArbillIT** [grokability/snipe-it#8403]
#### Please confirm you have done the following before posting your bug report:

- [ yes] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I am using localhost in Web url, I can login right away. But when i use the name of my server, it is not logging in.

**To Reproduce**

**Expected behavior**
After typing my credential it should login to my dashboard on what is happening when i use the localhost as url. 

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.9.4
 - OS: [e.g. Ubuntu, CentOS] windows server 2016 through wamp installation
 - Web Server: [e.g. Apache, IIS] apache
 - PHP Version  7.3.21

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] IE/Chrome

**Smartphone (please complete the following information):**

**Error Messages**
No error message it just after i type my credential, it will just clear out the details i type after login.

**Additional context**
- Is this a fresh install or an upgrade?  Yes
- What OS and web server you're running Snipe-IT on. Windows and Wamp server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) wamp
- Include what you've done so far in the installation, and if you got any error messages along the way. no error message
- Indicate whether or not you've manually edited any data directly in the database

**Comment by ArbillIT** [comment]
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:fWGdrTmi4sn0pyxQKJnMg4SVS9oBkO8INxBO3tgQYtM=
APP_URL=http://MyVM/
APP_TIMEZONE='asia/singapore'
APP_LOCALE=en
MAX_RESULTS=500

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_DATABASE=asset
DB_USERNAME=root
DB_PASSWORD=null
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci



# Virtual Hosts
#
<VirtualHost *:80>
  ServerName http://WTESTVM01/
  ServerAlias http://WTESTVM01/
  DocumentRoot C:\wamp64\www\snipe-it\public
  <Directory "${INSTALL_DIR}/www/">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    
  </Directory>
</VirtualHost>

**Comment by jmartins1** [comment]
I believe your APP_URL address and ServerName, ServerAlias names should be the same.

# Virtual Hosts
#
<VirtualHost *:80>
<Directory "C:/wamp/www/snipe-it/public/">
	Allow From All
    AllowOverride All
	Options +Indexes
    Require all granted
</Directory>
	DocumentRoot "C:/wamp/www/snipe-it/public/"
	ServerName localhost:80
</VirtualHost>

Also, ensure your httpd.config file has this entry.

Listen 0.0.0.0:80
Listen [::0]:80
