### ISSUE TITLE
Setting a path prefix

### ISSUE THREAD

**Issue by JeremyMahieu** [grokability/snipe-it#8404]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.9.4 build 4437 (g799a93c46)
 - OS: Docker (Debian)
 - Web Server: Traefik
 - PHP Version: 7.1.33-17+ubuntu16.04.1+deb.sury.org+1

**Is your feature request related to a problem? Please describe.**
Trying to use Snipe-IT on `https://mydomain.com/pathprefix` using a reverse proxy, does not work. I can reach Snipe-IT but Snipe-IT is not aware of this path so all the resources are collected from the wrong location `https://mydomain.com/script.js`.

**Describe the solution you'd like**

- A way to configure the path prefix or base url the app should use.

- or support for the X-Forward-Prefix headers

**Describe alternatives you've considered**
Tried to use the `APP_URL` env variable but this does not seem to take the path in mind.

**Comment by JeremyMahieu** [comment]
This is highly relevant https://github.com/CachetHQ/Cachet/issues/3028

**Comment by tzahibwix** [comment]
@JeremyMahieu  Were you able to solve this?
I'm having the same issue, redirect to https://mydomain.com/pathprefix sometimes works and sometimes the "pathprefix" is missing from the "Location" header when using APP_URL...

**Comment by JeremyMahieu** [comment]
I gave up. The issue I referenced is fixed, maybe it works now.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
