### ISSUE TITLE
Update Manufacturer

### ISSUE THREAD

**Issue by greg14450** [grokability/snipe-it#8415]
I am trying to cleanup my SnipeIT database by ensuring all fields with "standardized" info are showing the same information.  For example, Manufacturer.  I have some records with Miller, Miller Milworks, Miller Millworks.  I want to update all assets to manufacturer Miller Millworks.  When I select Edit Asset under Actions, the Manufacturer field is not shown is not displayed.  Also, if I pull up the list of Manufacturers, the delete option is grayed out.  Please advise.  Thanks.

**Comment by snipe** [comment]
It would’ve been greyed out if there are still things assigned to it. You’d want to fix this in your asset models and/or assets, at which point you’d have that delete button available

**Comment by greg14450** [comment]
That did it. I fixed the manufacturer under asset models, then was able to delete unused/incorrect manufacturers.  Thank you!

Best,
Greg

**Comment by snipe** [comment]
Great! Glad to know it's sorted for you now :)
