### ISSUE TITLE
Logic error with setting up V5 beta 3

### ISSUE THREAD

**Issue by tannersouva** [grokability/snipe-it#8418]
- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
During the migration data from version 4 to version 5, I was having trouble with the installer adding the `ad_append_domain` field in settings every time. I narrowed the problem to `database\migrations\2020_02_04_172100_add_ad_append_domain_settings.php` Line 17-19. When in the initial steps of setting up the installer will attempt to keep adding the field to the settings table. I can give more screenshots to make sure this gets patched. This had me scratching my head for the last 3 days. I was able to fix the issue by commenting out the lines in question. This seemed to have solved the issue. I think a simple conditional statement should be fine. As I have not learned PHP yet, I figure I would report it.

**To Reproduce**
1. Make a fresh install of V5 Beta 3
2. Run the migration command
3. Run through setup
4. Visit instance.
5. See error

**Expected behavior**
The installer completes setup with data intact

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.0-beta-3 build 4190 (gec723a3da)
 - OS: Windows
 - Web Server: Apache
 - PHP Version 7.4.8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 85.0.4183.83

**Error Messages**
https://gist.github.com/tannersouva/3e3c7a168670d952539f9551aa14fe3b

**Comment by snipe** [comment]
Funnily, I just ran into this exact issue. I'll have a patch out shortly.

**Comment by snipe** [comment]
I believe the problem is actually in the LDAP service provider which gets loaded with the framework. It's looking for a settings table that doesn't yet exist. We have an experimental fix branch out, but we need to test it and make sure we didn't break LDAP in the process.

**Comment by tannersouva** [comment]
Good day! I will be able to test this in the next release! Thank you very much! Would you like me to keep this issue open or close it?

**Comment by snipe** [comment]
Let's keep it open until we know the issue is resolved :)

**Comment by snipe** [comment]
(This is now on the develop branch, but is not yet in a tagged release.)
