### ISSUE TITLE
Add bulk checkout email with all assets in one email error

### ISSUE THREAD

**Issue by jkunyuga** [grokability/snipe-it#8421]
Ive just added bulk checkout emailwith all asets in one email and i get and error in one of the files..below is the error im getting.

Undefined offset: 437 (View: C:\xampp\htdocs\snipe\resources\views\notifications\markdown\bulk-checkout-asset.blade.php)
--
in 96fbfe17da5255624f3c3b0dd7ee6c42eb752e97.php line 16
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php line 45
at PhpEngine->evaluatePath('C:\\xampp\\htdocs\\snipe\\storage\\framework\\views/96fbfe17da5255624f3c3b0dd7ee6c42eb752e97.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'signedIn' => true, 'user' => object(User), 'level' => 'info', 'subject' => 'Asset delivery confirmation', 'greeting' => null, 'salutation' => null, 'introLines' => array(), 'outroLines' => array(), 'actionText' => null, 'actionUrl' => null, 'displayableActionUrl' => '', 'admin' => object(User), 'note' => null, 'target' => object(User), 'fields' => array(), 'eulaList' => array(false), 'req_accept' => 1, 'accept_url' => 'http://127.0.0.1:8000/account/bulk-accept-assets/WzQzN10%3D', 'last_checkout' => '2020-09-09', 'expected_checkin' => null, 'assets' => array(object(Asset)), 'snipeSettings' => object(Setting)))in CompilerEngine.php line 59
at CompilerEngine->get('C:\\xampp\\htdocs\\snipe\\resources\\views/notifications/markdown/bulk-checkout-asset.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'signedIn' => true, 'user' => object(User), 'level' => 'info', 'subject' => 'Asset delivery confirmation', 'greeting' => null, 'salutation' => null, 'introLines' => array(), 'outroLines' => array(), 'actionText' => null, 'actionUrl' => null, 'displayableActionUrl' => '', 'admin' => object(User), 'note' => null, 'target' => object(User), 'fields' => array(), 'eulaList' => array(false), 'req_accept' => 1, 'accept_url' => 'http://127.0.0.1:8000/account/bulk-accept-assets/WzQzN10%3D', 'last_checkout' => '2020-09-09', 'expected_checkin' => null, 'assets' => array(object(Asset)), 'snipeSettings' => object(Setting)))in View.php line 143
at View->getContents()in View.php line 126
at View->renderContents()in View.php line 91
at View->render()in Markdown.php line 64
at Markdown->render('notifications.markdown.bulk-checkout-asset', array('level' => 'info', 'subject' => 'Asset delivery confirmation', 'greeting' => null, 'salutation' => null, 'introLines' => array(), 'outroLines' => array(), 'actionText' => null, 'actionUrl' => null, 'displayableActionUrl' => '', 'admin' => object(User), 'note' => null, 'target' => object(User), 'fields' => array(), 'eulaList' => array(false), 'req_accept' => 1, 'accept_url' => 'http://127.0.0.1:8000/account/bulk-accept-assets/WzQzN10%3D', 'last_checkout' => '2020-09-09', 'expected_checkin' => null, 'assets' => array(object(Asset))))in MailChannel.php line 101
at MailChannel->buildView(object(MailMessage))in MailChannel.php line 63
at MailChannel->send(object(User), object(BulkCheckoutAssetNotification))in NotificationSender.php line 146
at NotificationSender->sendToNotifiable(object(User), 'fa49fbad-de1b-4aa3-8ba7-65183e10d1a3', object(BulkCheckoutAssetNotification), 'mail')in NotificationSender.php line 105
at NotificationSender->Illuminate\Notifications\{closure}()in Localizable.php line 29
at NotificationSender->withLocale('en', object(Closure))in NotificationSender.php line 107
at NotificationSender->sendNow(object(Collection), object(BulkCheckoutAssetNotification))in NotificationSender.php line 79
at NotificationSender->send(object(Collection), object(BulkCheckoutAssetNotification))in ChannelManager.php line 39
at ChannelManager->send(object(Collection), object(BulkCheckoutAssetNotification))in Facade.php line 261
at Facade::__callStatic('send', array(object(Collection), object(BulkCheckoutAssetNotification)))in CheckoutableListener.php line 54
at CheckoutableListener->onCheckedOut(object(CheckoutableCheckedOut))
at call_user_func_array(array(object(CheckoutableListener), 'onCheckedOut'), array(object(CheckoutableCheckedOut)))in Dispatcher.php line 388
at Dispatcher->Illuminate\Events\{closure}('App\\Events\\CheckoutableCheckedOut', array(object(CheckoutableCheckedOut)))in Dispatcher.php line 218
at Dispatcher->dispatch('App\\Events\\CheckoutableCheckedOut')in helpers.php line 477
at event(object(CheckoutableCheckedOut))in Loggable.php line 65
at BulkAssetsController->logBulkCheckout(object(User), null, array(object(Asset)), array('checkout' => '2020-09-09 17:36:52', 'checkin' => ''))in BulkAssetsController.php line 260
at BulkAssetsController->App\Http\Controllers\Assets\{closure}(object(MySqlConnection))in ManagesTransactions.php line 29
at Connection->transaction(object(Closure))in DatabaseManager.php line 349
at DatabaseManager->__call('transaction', array(object(Closure)))in Facade.php line 261
at Facade::__callStatic('transaction', array(object(Closure)))in BulkAssetsController.php line 262
at BulkAssetsController->storeCheckout(object(Request))
at call_user_func_array(array(object(BulkAssetsController), 'storeCheckout'), array(object(Request)))in Controller.php line 54
at Controller->callAction('storeCheckout', array(object(Request)))in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(BulkAssetsController), 'storeCheckout')in Route.php line 219
at Route->runController()in Route.php line 176
at Route->run()in Router.php line 681
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CreateFreshApiToken.php line 50
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForTwoFactor.php line 53
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckLocale.php line 37
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in VerifyCsrfToken.php line 76
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Router.php line 683
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 658
at Router->runRoute(object(Request), object(Route))in Router.php line 624
at Router->dispatchToRoute(object(Request))in Router.php line 613
at Router->dispatch(object(Request))in Kernel.php line 170
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in InjectDebugbar.php line 65
at InjectDebugbar->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForSetup.php line 26
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in StartSession.php line 56
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForMaintenanceMode.php line 63
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in HandlePreflight.php line 29
at HandlePreflight->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Kernel.php line 145
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 110
at Kernel->handle(object(Request))in index.php line 58
at require_once('C:\\xampp\\htdocs\\snipe\\public\\index.php')in server.php line 21

**Comment by snipe** [comment]
Can you tell me what line 16 of C:\xampp\htdocs\snipe\storage\framework\views/96fbfe17da5255624f3c3b0dd7ee6c42eb752e97.php is?

**Comment by jkunyuga** [comment]
okey..just a minute

**Comment by jkunyuga** [comment]
![sniper-it-error](https://user-images.githubusercontent.com/71035544/92640729-65a60380-f2e6-11ea-8c23-b9d4be056743.jpg)
ive scrrenshote the the error log

**Comment by jkunyuga** [comment]
The line 16 that file is this one::
**<?php $__currentLoopData = $fields[$asset['log_id']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<?php if(($asset->{ $field->db_column_name() } !='') && ($field->show_in_email) && ($field->field_encrypted=='0')): ?>**

**Comment by jkunyuga** [comment]
The line 16 of that file:
<?php $__currentLoopData = $fields[$asset['log_id']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<?php if(($asset->{ $field->db_column_name() } !='') && ($field->show_in_email) && ($field->field_encrypted=='0')): ?>

**Comment by snipe** [comment]
Thanks for the additional info - @inietov do you want to take a stab at this?

**Comment by jkunyuga** [comment]
If i can get a solution soonest i would really appreciate. The system is being usedn and that part of emailing is needed to be implemented. Thank you

**Comment by inietov** [comment]
Hello! @jkunyuga 

Testing this I was able to receive all the assets in separate emails. I understand that you are making changes into the email view that's sent to the users? I'm just trying to figure out if this is a Feature Request or a Bug Encountered.

**Comment by jkunyuga** [comment]
Hi @inietov 
It is a bug ive encountered..Bulk checkout is working fine by sending separate emails every email for each asset as youve just mentioned. But the problem actually is the sending separate email for each asset. following 'Add new option to Bulk Checkout Page #7518' commit which is suppose to send only one email for all the assets is when im encountering the error

**Comment by inietov** [comment]
Ok I understand, 

I'm sorry but that code isn't merged in the project yet. That means that it isn't properly tested from our part or some changes need to be done and we can't respond for the stability of that feature. It's a great idea and possibly is gonna be implemented in the future. But until then, we aren't supporting it. I'm really sorry. 

Gonna close this for now but when it actually gets implemented, if this keep being an issue, you can reopen the issue.
