### ISSUE TITLE
Custom Fieldset overview only shows models but not the model number.

### ISSUE THREAD

**Issue by Tezameru** [grokability/snipe-it#8426]
**Server (please complete the following information):**
 - Snipe-IT Version v4.9.3

**Is your feature request related to a problem? Please describe.**
Under "Custom Field", while creeating new custom fields, I am unable to differentiate between models assigned to a custom fieldset which have the same model, but have differentiating model numbers entirely. See attached screenshot. 

**Describe the solution you'd like**
Show the model no. of the models that are assigned to custom fieldsets in addition to the model name.

**Describe alternatives you've considered**
An option or toggle to make the model no. show in addition to the model name.

**Additional context**
![image](https://user-images.githubusercontent.com/21127645/92884142-dac22780-f411-11ea-9548-5388fc896f2b.png)

**Comment by snipe** [comment]
This is now on develop and will be in the next release.
