### ISSUE TITLE
Request - Custom License report

### ISSUE THREAD

**Issue by JoeTheSane** [grokability/snipe-it#8428]
#### Expected Behavior (or desired behavior if a feature request)

I would like to see a license report by user of which licenses they have and how much that license costs. This report should be filterable by user and by license, so you could either see all the licenses that a user has or all the users that have a specific license assigned, and the total cost of those licenses.

Alternatively. being able to add the Cost column to the User's license tab would also be sufficient.

-----

#### Actual Behavior

This report does not exist

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
 Fresh install
- Version of Snipe-IT you're running
4.9.4 build 4437
- Version of PHP you're running

- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This is now on develop and will be n the next release. 

<img width="1537" alt="Screen Shot 2020-09-11 at 11 48 01 AM" src="https://user-images.githubusercontent.com/197404/92961827-ccc9d200-f424-11ea-8663-39c2ffee047e.png">
