### ISSUE TITLE
Some columns under Accessories are not sorting by their contents.

### ISSUE THREAD

**Issue by richmcninch** [grokability/snipe-it#8436]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Some columns under the Accessories page do not sort by their contents, but consistently according to some other set of data. For example, sorting by Category, Location, or Manufacturer all produce the same order, regardless of data shown. This behavior can be seen in the demo.

**To Reproduce**
1. Go to 'Accessories'
2. Click on 'Accessory Category' to sort by that field
3. Note it does not sort by those category names.

**Expected behavior**
Expected that it would sort according to the contents of the column.

This issue is easily reproduced in the demo so please forgive me for not including any information about my install.

**Comment by snipe** [comment]
Hi there - I know this is a pretty old issue, but I wanted to check and see if you ever got this resolved? If so, can you please close the ticket? If not, can you update us on what version of Snipe-IT you're currently using, so we can see if it's still an issue on latest?

:) Thanks!
