### ISSUE TITLE
web.config exposed on Qualysis security scan. 

### ISSUE THREAD

**Issue by cgb37** [grokability/snipe-it#8437]
We're running Snipe on Centos 7 apache 2.4. We cannot let it go to production until it passes a Qualysis security scan. It fails because web.config is exposed. Can we delete that file? If not should we set Deny from all in htaccess?

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
That config doesn’t really expose anything and would only be used by IIS. I don’t see any reason you couldn’t set up Apache to deny access to that file.

**Comment by ghost** [comment]
> That config doesn’t really expose anything and would only be used by IIS. I don’t see any reason you couldn’t set up Apache to deny access to that file.

 It's a vulnerability. Check the reference. 

https://www.tenable.com/plugins/nessus/121479.

**Comment by cgb37** [comment]
here's the fix
```
<Files "web.config">
    Require all denied
</Files>
```

**Comment by snipe** [comment]
> It's a vulnerability. Check the reference

It is not, for the reasons I stated before.

**Comment by cgb37** [comment]
okay, but regardless, our security team wouldn't approve the app for production until i added the apache directive and it passed the Qualysis scan

**Comment by snipe** [comment]
This would typically be handled at the server level though. You can change it in your web config (not recommended, since next time you update, you’ll have a file that you changed outside of the source), or change it at the IIS level. We don’t try to tell you how to run your web server, but either way, it’s not actually a vulnerability. An “exposed” file that doesn’t actually disclose any sensitive data is just a file. Automated scans are largely garbage because they don’t take context into consideration. In some other IIS contexts, that file might contain database credentials, etc. Ours does not. Automated scanners do not consider that.
