### ISSUE TITLE
4.9.4 not updated to 4.9.5

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#8440]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
4.9.4 not updated to 4.9.5

**Expected behavior**
No errors when updating, after running the php script upgrade.php everything seems to be going as usual. When the script is finished, there are no errors. But the version remains v4. 9. 4 build 4437 (g799a93c46)

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.4 
 - OS: CentOS
 - Web Server: Apache
 - PHP Version  7.3.19 

**Additional context**
- Is this a fresh install or an upgrade? upgrade
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by remerus** [comment]
Can confirm same behaviour on my install (v.4.9.3 build 4395) - been that way here since beginning August.

Snipe-IT Version v4.9.3 (build 4395)
OS: CentOS 7
Web Server: Apache
PHP Version 7.3.22

**Comment by UserGoodtm** [comment]
It was my mistake. I had changed the original files (the name did not change, the changes were in the file code) resources/views/users/print.blade.php and resources/views/users/view.blade.php. There was also an incorrect time in the system. Updated the host system. Set the correct time. Returned the original files. The update was successful.

**Comment by remerus** [comment]
No changes to any files here but I solved it by taking the following steps:

`git pull`

Which indicated the installation was 67 commits behind.  

Forced a sync with the master branch (from [this answer](https://stackoverflow.com/questions/1125968/how-do-i-force-git-pull-to-overwrite-local-files) on StackOverflow):

`git fetch --all`

followed by

`git reset --hard origin/master`

I'm leaving this here purely because it might help someone with a similar issue in future. 

Absolutely love this software - thank you @snipe!

**Comment by snipe** [comment]
Sorry for the delay in responding here - thanks so much @remerus for following up. We've got a few other people having the same problem (tho I have no idea why), and this comment will definitely help them. 

> Absolutely love this software - thank you @snipe!

You're welcome! And thanks very much for the kind words <3

**Comment by snipe** [comment]
FYI, this is now in the docs:
https://snipe-it.readme.io/docs/installation-issues#updating-with-upgradephp-fails-to-update-filesversion

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#updating-with-upgradephp-fails-to-update-filesversion">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>
