### ISSUE TITLE
CSS not loading during setup in v5.0.0 beta

### ISSUE THREAD

**Issue by MichalMMac** [grokability/snipe-it#8442]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I've deployed fresh v5.0.0-beta-4. CSS was not loaded during setup using Safari.
Safari was not happy:

```
Did not parse stylesheet at 'https://company.tld/css/all.css' because non CSS MIME types are not allowed in strict mode.
```
Doing `curl -LI https://company.tld/css/all.css` during setup returned 302 redirect to curl -LI https://inventory.logicworks.cz/setup. Doing `curl -LI https://company.tld/css/all.css` after redirect gives me 404.

**To Reproduce**
1. Deploy 5.0.0-beta-4
2. Create .env file
3. Go to https://company.tld where the App is running using Safari
4. Setup page loads without CSS

**Expected behavior**
Page CSS loads during setup

**Screenshots**
![Screen Shot 2020-09-16 at 17 07 27](https://user-images.githubusercontent.com/3882687/93357209-56700a00-f840-11ea-93b5-ecc0b7c4a3d5.png)

**Server (please complete the following information):**
 - Snipe-IT v5.0.0-beta-4 
 - OS: Debian 10
 - Web Server: Apache 2.4
 - PHP Version: 7.4.10

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser. Safari
 - Version: 13.1.2

**Comment by snipe** [comment]
Thanks! We’ll get that fixed shortly!

**Comment by snipe** [comment]
Should be up on develop now - thanks again for the heads up!
