### ISSUE TITLE
sqlstate(42s02) base table or view not found 1146 table snipeit.settings

### ISSUE THREAD

**Issue by itmumbai20** [grokability/snipe-it#8452]
[laravel.log](https://github.com/snipe/snipe-it/files/5249178/laravel.log)
Hi I m facing issue while installing & Configuring Snipe-IT getting error **sqlstate(42s02) base table or view not found 1146 table snipeit.settings**

search alot but no solutions  attached error file 

OS is Windows 10
PHP 7.3.2
Madria DB 10.5

PS C:\inetpub\wwwroot\snipe-it> php artisan key:generate

In Connection.php line 669:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist (SQL: select `ldap_enabl
  ed`, `ldap_server`, `ldap_uname`, `ldap_pword`, `ldap_basedn`, `ldap_filter`, `ldap_username_field`, `ldap_lname_fi
  eld`, `ldap_fname_field`, `ldap_auth_filter_query`, `ldap_version`, `ldap_active_flag`, `ldap_emp_num`, `ldap_email
  `, `ldap_server_cert_ignore`, `ldap_port`, `ldap_tls`, `ldap_pw_sync`, `is_ad`, `ad_domain`, `ad_append_domain` fro
  m `settings` limit 1)

In PDOConnection.php line 66:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist

In PDOConnection.php line 64:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist

PS C:\inetpub\wwwroot\snipe-it>

Thanks 
![Error](https://user-images.githubusercontent.com/71499144/93593129-1f7d2e00-f9d1-11ea-98e3-354502f1a450.png)

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by uberbrady** [comment]
We had a bug early on in the v5 beta process around this, but we fixed it before we released v5.
