### ISSUE TITLE
install.sh does not function properly

### ISSUE THREAD

**Issue by teward** [grokability/snipe-it#8454]
#### Please confirm you have done the following before posting your bug report:

- [ N/A ] I have enabled debug mode 
- [ N/A ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The `install.sh` script is improperly coded.  Bash expects a numerical argument in the usage that is currently defined for version string checking for 18.04 and later.

**To Reproduce**
1. Run 18.04 or 20.04 Ubuntu Server
2. Download and attempt to use install.sh file.
3. Bash will trigger an error message (hard error)

**Expected behavior**
The script would "Just Run"

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: N/A (not installed, installer from Master
 - OS: Ubuntu 20.04 LTS
 - Web Server: N/A
 - PHP Version: N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Error Messages**
```


       _____       _                  __________
      / ___/____  (_)___  ___        /  _/_  __/
      \__ \/ __ \/ / __ \/ _ \______ / /  / /
     ___/ / / / / / /_/ /  __/_____// /  / /
    /____/_/ /_/_/ .___/\___/     /___/ /_/
                /_/


  Welcome to Snipe-IT Inventory Installer for CentOS, Fedora, Debian and Ubuntu!

  The installer has detected Ubuntu version 20.04 codename focal.
  Q. What is the FQDN of your server? (snipeit-test):  
     Setting to snipeit-test

  Q. Do you want to automatically create the database user password? (y/n) y

./snipeit.sh: line 425: [: 20.04: integer expression expected
Unsupported Ubuntu version. Version found: 20.04
root@snipeit-test:~# 
```

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install
- What OS and web server you're running Snipe-IT on: Ubuntu 20.04, Apache (but happens during install)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way: Run install.sh
- Indicate whether or not you've manually edited any data directly in the database: No.

**This is a critical breakage in the `install.sh` script, making the script not function.**

However, I was able to *work around* this by altering the script to do a direct comparison, rather than try and do an integer comparison, so that the line tested 18.04 and 20.04 independently as the `elif`s do for other LTS releases.

**Comment by susumuf** [comment]
I bet snipeit.sh for ubuntu must be fixed as below;

```
L.441  if [ "$version" -ge "18.04" ]; then
       if [ $(echo "$version >= 18.04" | bc) -eq 1 ]; then
L.474  elif [ "$version" == "16.04" ]; then
       elif [ $(echo "$version >= 16.04" | bc) -eq 1 ]; then
L.511  elif [ "$version" == "14.04" ]; then
       elif [ $(echo "$version >= 14.04" | bc) -eq 1 ]; then

```

**Comment by uberbrady** [comment]
This was fixed in a pull request.
