### ISSUE TITLE
cant access Snipe IT

### ISSUE THREAD

**Issue by Jannik2017** [grokability/snipe-it#8457]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Server (please complete the following information):**
 - Snipe-IT Version  v4.9.5
 - OS:  Debian 8
 - Web Server:  Apache
 - PHP Version  7.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10
 - Browser Firefox

**Error Messages**
Warning: require(/var/www/html/snipeit/public/var/www/html/snipeit/bootstrap/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipeit/public/index.php on line 22

Fatal error: require(): Failed opening required '/var/www/html/snipeit/public/var/www/html/snipeit/bootstrap/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/snipeit/public/index.php on line 22

**Additional context**
-  fresh install 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT  manual installation,

**Comment by Jannik2017** [comment]
new Error


Fatal error: Uncaught Error: Class 'Log' not found in /home/jannik/public_html/Inventur/app/Exceptions/Handler.php:40 Stack trace: #0 /home/jannik/public_html/Inventur/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalThrowableError)) #1 /home/jannik/public_html/Inventur/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Foundation\Http\Kernel->reportException(Object(Symfony\Component\Debug\Exception\FatalThrowableError)) #2 /home/jannik/public_html/Inventur/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #3 {main} thrown in /home/jannik/public_html/Inventur/app/Exceptions/Handler.php on line 40

**Comment by uberbrady** [comment]
It looks like you need to run `composer install`. You can also try to pull the latest version which has an improved `upgrade.php` script that can help detect and resolve many common problems; we often get users who simply run `php upgrade.php` and their installations just magically 'work'
