### ISSUE TITLE
Notes on Accessories list is the same.

### ISSUE THREAD

**Issue by hjorken** [grokability/snipe-it#8462]
#### Please confirm you have done the following before posting your bug report:

- [-] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When accessory is checked out and you write a note, this note can now be seen in the 5.B4 version, list over all checked out instances of that accessory.
But when you check out a new instance whit a new note, the note shown off the first is changed to the note off the second.

**To Reproduce**
1. Checkout a Accessory to a user, and give a note.
2. Go to the list of checked out accessories, and see the note text in the list.
3. Checkout a new Accessory to a new user, a give a different note.
4. Go back to the list, and the last note, is displayed on both instances.

**Expected behavior**
The note for each checkout, should be shown for each instance. 

**Screenshots**
List after the first checkout:
![image](https://user-images.githubusercontent.com/2535404/93766118-3b254600-fc16-11ea-9b54-be0962949880.png)

Second checkout:
![image](https://user-images.githubusercontent.com/2535404/93766398-a2db9100-fc16-11ea-93a7-005e07ea678a.png)

List after second checkout:
![image](https://user-images.githubusercontent.com/2535404/93766503-c9013100-fc16-11ea-9f80-73446a502e07.png)

**Server (please complete the following information):**
 - Snipe-IT Version:  v5.0.0-beta-4 - build 4482 (develop)
 - OS: Debian Buster
 - Web Server: Apache
 - PHP Version: 7.4.7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 85.0.564.51

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser: NA
 - Version: Na

**Error Messages**
- No error message shown

**Additional context**
- Upgraded from 4.9.3 to 5.0.0.B4
- Installed manually from source.zip, with the guide from: https://snipe-it.readme.io/docs/upgrading

**Comment by snipe** [comment]
I can definitely confirm this one.

**Comment by snipe** [comment]
@uberbrady this looks like it could be kinda sticky. It's pulling the last note from the last checkout, but really I think we should be saving that on the `accessories_users` table, for better performance. The problem is the gross migration we'd have to do to port that data over...

Do you want to take a stab at this, or should I?

**Comment by uberbrady** [comment]
@snipe it sounds like you're already on it! Great 👍

**Comment by snipe** [comment]
I have a fix out in a PR right now which should resolve this issue. Once it's reviewed, I'll  merge it in.
