### ISSUE TITLE
Adjust Google Maps zoom

### ISSUE THREAD

**Issue by benwa** [grokability/snipe-it#8465]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.9.5
 - OS: Windows Server 2019
 - Web Server: IIS
 - PHP Version: 7.3.20

**Is your feature request related to a problem? Please describe.**
Our company has multiple locations set up, however they're all in the same city. The Google Maps tile is all the same for each location.

**Describe the solution you'd like**
An option (so companies that don't want to go that detailed) to include the full address in the Google Maps query makes the tile unique.

**Comment by Relix360** [comment]
you want something like this? 
![image](https://user-images.githubusercontent.com/52633264/93919908-c3721c80-fce4-11ea-9a12-9ba385e9328a.png)

**Comment by benwa** [comment]
Having a marker would be nice too, but I'm talking purely about the center point of the map. The query only has the city (twice?), state, and zip.
`https://maps.googleapis.com/maps/api/staticmap?center=Austin%2CAustin+TX+US+78701&size=500x300&maptype=roadmap&key=API_KEY`

This can be a problem if there are multiple locations with the same, or similar zip codes. By providing the street address too, it can be visually different.

**Comment by Relix360** [comment]
I have change the code and the api type for the locations and supplier in my installation try this two php files on resources/views/locations/ and on resources/views/suppliers/ you need to rename it only to view.blade.php on each folder, also, first backup your originals files just in case since my installation is 4.9.2


[snipe it location map.zip](https://github.com/snipe/snipe-it/files/5263436/snipe.it.location.map.zip)

**Comment by snipe** [comment]
You're always welcome to modify the code, but it would probably benefit you to create a PR so that your work can be merged into the upstream. Otherwise you're either going to lose your changes when you upgrade, or will have to re-apply them each time.

**Comment by Relix360** [comment]
I'm really new to all this github thing haha, the change that I have done for example in the locations is this one 

In the view.blade.php from locations i have change `

```
@if (($location->state!='') && ($location->country!='') && (config('services.google.maps_api_key')))
	
	
          <div class="col-md-12 text-center">
	
	
            <img src="https://maps.googleapis.com/maps/api/staticmap?center={{ urlencode($location->city.','.$location->city.' '.$location->state.' '.$location->country.' '.$location->zip) }}&size=500x300&maptype=roadmap&key={{ config('services.google.maps_api_key') }}" class="img-responsive img-thumbnail" alt="Map">
	
          </div>

        @endif
```

for this 

`<div class="col-md-3">
	        @if (($location->state!='') && ($location->country!='') && (config('services.google.maps_api_key')))
	            <div class="col-md-12 text-center" style="padding-bottom: 20px;">
	    <iframe width="400" height="450" frameborder="0" style="border:0" src="
	  https://www.google.com/maps/embed/v1/place?q={{ urlencode($location->address.','.$location->city.' '.$location->state.' '.$location->country.' '.$location->zip) }}&maptype=roadmap&key={{ config('services.google.maps_api_key') }}""></iframe>
	    </div>
	    @endif`
