### ISSUE TITLE
ENCRYPT=true and APP_KEY=null in .env cause composer install error "The only supported ciphers are..."

### ISSUE THREAD

**Issue by maccadia** [grokability/snipe-it#8470]
#### Expected Behavior

When `ENCRYPT=true` in `.env`, I expected
```
php composer.phar install --no-dev --prefer-source
```
to return with no error (code 0).

-----

#### Actual Behavior

When `ENCRYPT=true` in `.env`
```
php composer.phar install --no-dev --prefer-source
```
gives an error :
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Encrypter.php line 43:
                                                                               
  The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct  
   key lengths.                                                                
                                                                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

```

If I set `ENCRYPT=false`, I get no error.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running : **Fresh git clone : v4.9.5**
- Version of PHP you're running : **PHP 7.2.24-0ubuntu0.18.04.6**
- Version of MySQL/MariaDB you're running  : **mysql  Ver 14.14 Distrib 5.7.31**
- What OS and web server you're running Snipe-IT on : **Ubuntu 18.04 LAMP**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : **manual**
- Indicate whether or not you've manually edited any data directly in the database : **no edit**

**Comment by snipe** [comment]
Did you generate an APP_KEY?

**Comment by snipe** [comment]
Set your APP key to the following:

`APP_KEY=base64:aQP49skDBerXQeKYkQWX+BIzTjK6COhpELqwTGtRYG8=`

(It's just a local one I use.) After that, run composer install, and if that goes through without error, generate a new app key by running `php artisan key:generate`. The one in this post should only be used to get you through the install, and running the key generator will replace it in your .env with a new one.

**Comment by maccadia** [comment]
I followed the documentation and did `composer install` before `php artisan key:generate`.

With the app_key you gave, `composer install` succeed.

I can also workaround the issue by doing :

1. setting `APP_KEY=null`  and `ENCRYPT=false`
2. running `composer install`
3. running `key:generate`
4. setting `ENCRYPT=true`
5. running `composer install` (not needed ?)

I guess, we just need to document this in the Common Issue page or with a warning in the docs.

**Comment by snipe** [comment]
It's not really a common issue though. I've only seen it a few times in the history of the project, and have never been able to track down a cause.

**Comment by snipe** [comment]
I've added this solution to the v5 docs. Thanks :)
