### ISSUE TITLE
HTTP to HTTPS Redirect

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#8471]
A question for the big brains at SnipeIT.

I am running the latest version of SnipeIT and WAMP server on a 2012R2 server.

After making the following changes, I am still unable to enter a http address and automatically be redirected to a https site.

I have configured WAMP with a self-signed certificate and it appears to be working minus the redirect. I'm hoping someone can point me to what might need addressing to make redirection work.

Changes made:

1. In the .env file, ensured the APP_URL has a https address with no trailing slashes or public in the address.

2. In the public/.htaccess file, ensured to un-comment:
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

3. in the httpd-vhost.config file,
<VirtualHost *:443>
<Directory "C:/wamp/www/snipe-it/public/">
	Allow From All
    AllowOverride All
	Options +Indexes
    Require all granted
</Directory>
	DocumentRoot "C:/wamp/www/snipe-it/public/"
	ServerName localhost
</VirtualHost>

SSLEngine on
SSLCertificateFile "C:\wamp\bin\apache\apache2.4.46\conf\key\server.crt"
SSLCertificateKeyFile "C:\wamp\bin\apache\apache2.4.46\conf\key\private.key"

Things I wasn't sure about:

1. In the httpd.config file, Listen on: 
    Listen 0.0.0.0:80
    Listen [::0]:80
    Tried changing this to 443, but it didn't seem to make a difference.

Thank you in advance.

**Comment by jmartins1** [comment]
Figured it out.

In the httpd.config file, Listen on:
Listen 0.0.0.0:80
Listen [::0]:80

I changed to:
Listen 192.168.1.5:443
Listen [::0]:80

The 192.168.1.5 being the server address hosting SnipeIT.

**Comment by jmartins1** [comment]
Figured it out.

In the httpd.config file, Listen on:
Listen 0.0.0.0:80
Listen [::0]:80

I changed to:
Listen 192.168.1.5:443
Listen [::0]:80

The 192.168.1.5 being the server address hosting SnipeIT.

**Comment by uberbrady** [comment]
My initial guess was going to be that you don't have `mod_rewrite` enabled in your Apache config, but if that were the case I think the bulk of your Snipe-IT installation would end up not working.

I'm pretty sure you need to listen on both port 80 as well as port 443 - you can add multiple directives for this.

I think you also might need a `<VirtualHost *:80>` block in your config, with similar values as to what you have in your `<VirtualHost *:443>` section - the `.htaccess` should handle doing your redirect for you.

**Comment by jmartins1** [comment]
Thank you for the feedback.

I tried adding the following to the vhost file.

# Virtual Hosts
#
<VirtualHost *:80>
<Directory "C:/wamp/www/snipe-it/public/">
	Allow From All
    AllowOverride All
	Options +Indexes
    Require all granted
</Directory>
	DocumentRoot "C:/wamp/www/snipe-it/public/"
	ServerName localhost
</VirtualHost>

<VirtualHost *:443>
<Directory "C:/wamp/www/snipe-it/public/">
	Allow From All
    AllowOverride All
	Options +Indexes
    Require all granted
</Directory>
	DocumentRoot "C:/wamp/www/snipe-it/public/"
	ServerName localhost
</VirtualHost>

SSLEngine on
SSLCertificateFile "C:\wamp\bin\apache\apache2.4.46\conf\key\server.crt"
SSLCertificateKeyFile "C:\wamp\bin\apache\apache2.4.46\conf\key\private.key"

That didn't appear to make a difference.

I then modified the httpd.config file as follows:
Listen 192.168.1.5:80
Listen 192.168.1.5:443
Listen [::0]:80

That was a little more promising but did not resolve the issue. I received the following error, when attempting to enter a http address; no redirect.

Bad Request
Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.2.33 Server at localhost Port 80
