### ISSUE TITLE
v5 Update! 

### ISSUE THREAD

**Issue by snipe** [grokability/snipe-it#8473]
Hi all - just wanted to give a quick update on v5 status. We *were* (and potentially still are) planning on releasing this week. We did hit a very hard to reproduce issue (#8458) that some folks are seeing but that we personally cannot reproduce either locally or on our production systems (*or* the the demos), which is a real pain in the ass, since it's nearly impossible to fix something you can't reproduce. We're still working on that though. We only have a handful of people who are experiencing the issue, but it's important to us to figure out what exactly is happening so we can be sure it's not going to be an issue in v5. 

We will, of course, issue a detailed changelog with the release, but you can kinda get a feel for what all is new by checking out these two issues:

https://github.com/snipe/snipe-it/issues/6287
https://github.com/snipe/snipe-it/issues/7997

We've back ported some of these changes to the v4.9.x branch, which unfortunately takes some of the fun out of it, since some of these features are already in the wild, but we don't believe in withholding features when it's feasible to get them into your hot little hands ASAP.

We'll probably also be writing up a formal post-mortem to explain why the hell this release took so long. I know v5 is eagerly anticipated, but also please try to remember that we've pushed out over 30 production 4.x.x releases since the v5 project was undertaken. 

For those of you who have been with us a while, you know we have a very aggressive release cycle. This one was a little different, as there were some pretty huge PRs (LDAP changes, specifically) that came through, and there were some security issues with the Laravel framework that caused us to have to upgrade both master and develop when we hadn't planned on doing it just yet. (Laravel upgrades can be a real bear.)

Releasing v5 is a big deal for few reasons that may not seem very obvious, so I wanted to take a moment to explain them here. For some of you, it seems like very old features don't get looked at - things like custom fields on Users, etc that people have been asking for for a long time. 

They do get looked at (I promise!), and it's been part of the plan to extend that functionality out across the board for quite some time. We needed to ship v5 in order to put us in a better position to be able to rewrite some of the core models (OOP model, not asset model). Part of that will dramatically change the way licenses, consumables, etc are handled, so that they behave a little more like assets+asset models - but will also extend some of the asset model behavior to be more like consumables, where you can have alerts set up on asset models when you are about to run out of available assets of that model type. __THESE CHANGES WILL NOT BE IN v5.0.0.__ Sorry to shout, but I wanted to be really clear about that part. We needed to get v5 out so that we could work on these types of things. 

![Hamilton-Million-Things](https://user-images.githubusercontent.com/197404/94194662-dad91300-fe66-11ea-98f4-095711d0639c.gif)

There's tons more great stuff ahead. It's been enormously stressful to have `develop` and `master` SO different for so long, and I personally am excited about getting those back to parity and not having to maintain two very different branches with new features. We've learned a ton over the past two years, from the community and our customers. 

### Also please remember that v5 will require PHP 7.2 or greater, so make sure your systems are upgraded so you can benefit from the yummy v5 goodness.

We deeply appreciate everyone's patience. It's been a long road, but we hope everyone will think it's worth it. This will be the most tested version of Snipe-IT that we've ever released, thanks in part to our awesome community, and partly due to the folks on our end who have been using the behemoth of a test plan we created (which we may end up publishing, once we've made sure to sanitize it). Huge thanks to Birgit Zeus, Victoria Pak, Brady Wetherington, Ivan Nieto and Godfrey Martinez for all the work that's gone into this beast.

**Comment by WELLBOREIS** [comment]
Awesome news! Just started using Snipe-IT and am already blown away by the work you all have done. I can't wait to see what's in v5 and hope to make as many contributions as I can!

**Comment by snipe** [comment]
v5 is now live
