### ISSUE TITLE
I've already created data on my Snipe instance. will running php artisan: migrate delete my current data?

### ISSUE THREAD

**Issue by thetiagomatos** [grokability/snipe-it#8481]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Personal API tokens are not working because the Oauth tables do not exist. I was expecting that by running "php artisan: migrate" would fix my problem

#### Actual Behavior

Since the tables don't exist, when i try to create a personal api key i guet the following error: 

Whoops! Something went wrong!

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit_data.oauth_personal_access_clients' doesn't exist (SQL: select * from `oauth_personal_access_clients` order by `id` desc limit 1)
Illuminate\Database\QueryException
/bright/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php
664
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php", "line": 624, "function": "runQueryCallback", "class": "Illuminate\\Database\\Connection", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php", "line": 333, "function": "run", "class": "Illuminate\\Database\\Connection", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php", "line": 1719, "function": "select", "class": "Illuminate\\Database\\Connection", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php", "line": 1704, "function": "runSelect", "class": "Illuminate\\Database\\Query\\Builder", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php", "line": 481, "function": "get", "class": "Illuminate\\Database\\Query\\Builder", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php", "line": 465, "function": "getModels", "class": "Illuminate\\Database\\Eloquent\\Builder", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php", "line": 77, "function": "get", "class": "Illuminate\\Database\\Eloquent\\Builder", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/passport/src/ClientRepository.php", "line": 81, "function": "first", "class": "Illuminate\\Database\\Eloquent\\Builder", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/passport/src/PersonalAccessTokenFactory.php", "line": 71, "function": "personalAccessClient", "class": "Laravel\\Passport\\ClientRepository", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/passport/src/HasApiTokens.php", "line": 67, "function": "make", "class": "Laravel\\Passport\\PersonalAccessTokenFactory", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/passport/src/Http/Controllers/PersonalAccessTokenController.php", "line": 70, "function": "createToken", "class": "App\\Models\\User", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php", "line": 48, "function": "store", "class": "Laravel\\Passport\\Http\\Controllers\\PersonalAccessTokenController", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Route.php", "line": 212, "function": "dispatch", "class": "Illuminate\\Routing\\ControllerDispatcher", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Route.php", "line": 169, "function": "runController", "class": "Illuminate\\Routing\\Route", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 658, "function": "run", "class": "Illuminate\\Routing\\Route", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 30, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Router", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php", "line": 43, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Auth\\Middleware\\Authenticate", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php", "line": 49, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/app/Http/Middleware/CheckForTwoFactor.php", "line": 38, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\CheckForTwoFactor", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/app/Http/Middleware/CheckLocale.php", "line": 42, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\CheckLocale", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php", "line": 68, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php", "line": 37, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php", "line": 66, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 102, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 660, "function": "then", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 635, "function": "runRouteWithinStack", "class": "Illuminate\\Routing\\Router", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 601, "function": "runRoute", "class": "Illuminate\\Routing\\Router", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 590, "function": "dispatchToRoute", "class": "Illuminate\\Routing\\Router", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 176, "function": "dispatch", "class": "Illuminate\\Routing\\Router", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 30, "function": "Illuminate\\Foundation\\Http\\{closure}", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }
{ "file": "/bright/snipe/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php", "line": 65, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Barryvdh\\Debugbar\\Middleware\\InjectDebugbar", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/app/Http/Middleware/SecurityHeaders.php", "line": 26, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\SecurityHeaders", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php", "line": 30, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/app/Http/Middleware/CheckForDebug.php", "line": 25, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\CheckForDebug", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/app/Http/Middleware/CheckForSetup.php", "line": 27, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "App\\Http\\Middleware\\CheckForSetup", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/fideloper/proxy/src/TrustProxies.php", "line": 57, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Fideloper\\Proxy\\TrustProxies", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php", "line": 49, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php", "line": 63, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Session\\Middleware\\StartSession", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php", "line": 46, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/barryvdh/laravel-cors/src/HandlePreflight.php", "line": 29, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 149, "function": "handle", "class": "Barryvdh\\Cors\\HandlePreflight", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 102, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 151, "function": "then", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 116, "function": "sendRequestThroughRouter", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }
{ "file": "/bright/snipe/public/index.php", "line": 58, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running 4.9.5
- Version of PHP you're running 7.4
- Version of MySQL/MariaDB you're running 10.5.5
- What OS and web server you're running Snipe-IT on Running on a Linux server 20.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error Included it above
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Personal API keys
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. No
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Its not
- Include any additional information you can find in `storage/logs` and your webserver's logs. Don't know what to paste... Sorry
- Include what you've done so far in the installation, and if you got any error messages along the way. I've only enabled LDAP and created assets
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by uberbrady** [comment]
`php artisan migrate` does not lose data, it just adds new columns as appropriate. Strictly speaking, when it removes columns, that data does go away, but we don't do that very often and would never do that to a column that had something important in it.
