### ISSUE TITLE
Notes not available when checking out accessory

### ISSUE THREAD

**Issue by emike09** [grokability/snipe-it#8483]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When checking out an accessory to a user, there is a Notes section. When entering notes, there is no way to view those notes after the accessory has been checked out. When viewing the accessory and accessory_user tables in the database, there are no columns for notes. 

**To Reproduce**
1. Go to Accessories - Actions - Checkout Accessory
2. Select a user to check out to
3. Enter any notes. 

**Expected behavior**
When viewing the user, it would be nice to see those notes, either under history, or under Accessories. If a notes field is provided, I would expect to be able to see those notes. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9699530/94622525-9cc95e00-026f-11eb-911b-e83368cdcec2.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.9.5 b4482 master
 - OS: Ubuntu 18.04
 - Web Server:  NginX
 - PHP Version 7.4.10

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser: Edge Chromium
 - Version 58

**Comment by gilesytheking** [comment]
i'm 99% sure that this issue is addressed in the soon to be released V5 #8473 - i'm sure @snipe can confirm this
