### ISSUE TITLE
Assets serial column should have an index

### ISSUE THREAD

**Issue by travismiller** [grokability/snipe-it#8486]
**Server (please complete the following information):**
 - Snipe-IT: v4.9.3
 - OS: Ubuntu 16.04 (Docker)
 - Web Server: Apache
 - PHP Version: 7.1.33

**Is your feature request related to a problem? Please describe.**
Importing assets with `artisan snipeit:import` takes significantly longer when assets have a serial number.

**Describe the solution you'd like**
Add an index to column `assets.serial`.

**Describe alternatives you've considered**
N/A

**Additional context**
> 16000 assets without Serial Number
> without index:  ~6 minutes
> with index: ~6 minutes

> 16000 assets with Serial Number
> without index:  ~1 hour ⚠️
> with index: ~6 minutes

**Comment by travismiller** [comment]
I’m happy to submit a PR if this suggested solution is acceptable.

**Comment by snipe** [comment]
Do you have unique serial numbers enabled in your settings?

**Comment by travismiller** [comment]
Yes, the setting is enabled.

**Comment by uberbrady** [comment]
We would take a PR that added a non-unique index for serial (some users have duplicated serial numbers for some bizarre reason. We need to support that, unfortunately).
