### ISSUE TITLE
-Update Asset Model- When you add a fieldset, default values are not applied to assets of that model

### ISSUE THREAD

**Issue by alkalinelito** [grokability/snipe-it#8488]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If you add a new fieldset with defaut values to an asset model (Update Asset Model screen) those values are not applied to the asset belonging to that model.  Editing other values works, example EOL , if you change it, it updates all the assets.

**To Reproduce**
1. Create new asset model
2. Create new asset using that model
3. Create custom fields/fieldset
4. Go to Asset models, and edit model, assign fieldset, click add default values, input default values. Also change de EOL months for testing purposes  
5. Save
6. When you go the asset of that model, fieldset values are not updated (blank), the EOL value is correctly updated

**Expected behavior**
You should see the default fieldset value on the asset of that model

**Screenshots**

![image](https://user-images.githubusercontent.com/62256/94854567-7f2cfd80-0403-11eb-83e1-02d0caa66d5d.png)

**Server:**
 - Snipe-IT Version v4.9.5
 - OS: [Official Docker Image on Debian Buster]
 - Web Server: [Apache]
 - PHP Version [7.1.33-17+ubuntu16.04.1+deb.sury.org+1]

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [chrome]
 - Version [latest]

**Additional context**
- Is this a fresh install or an upgrade?:   Fresh
- What OS and web server you're running : Docker

I know someone will answer that first I need to make the asset model with the fieldset and then create the asset ,  But this case is different: is for already created assets and models, for when you need to create/update the customs fields on the model

Use Cases:

1-When you need to create new default custom value for a model, and need those values applied to all the belonging assets.

2-Another example is a custom field "End of Support Date", this value is not announced until later in the product life cycle, so its a value you would need to add later on to an asset model.

I hope I made myself clear , didn't know to mark it as bug or feature. Because I don't know if its intended behavior or not .

**Comment by oddmyth** [comment]
+1 for this.  Even if it the propagation was something you needed to click through instead of automatically happening.
Probably wouldn't be necessary if bulk editing of custom fields worked, but I think propogation of default values from an asset model solves one of the main problems of allowing bulk editing across multiple asset models - simply don't allow it.

**Comment by jfmilke** [comment]
This is still relevant, I also bumped into the issue. It would be really nice to add/edit custom field values of a model and have the new values applied to all previously created assets belonging to this model.

**Comment by snipe** [comment]
Blindly bulk overriding all assets with a fieldset with new values would cause a lot of confusion. You should use the bulk edit assets UI to update custom field values for things that were already created.
