### ISSUE TITLE
Can't assign asset to newer users in AD

### ISSUE THREAD

**Issue by Phx86** [grokability/snipe-it#8492]
#### Expected Behavior (or desired behavior if a feature request)

All users in AD should be available to assign assets to. 

-----

#### Actual Behavior

Newer (not brand new, account is months old) are not found when searching for users to assign assets to. I don't believe this is a bug, but a config issue.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Existing
- Version of Snipe-IT you're running v4.7.5 build 4137
- Version of PHP you're running 7.3.8
- Version of MySQL/MariaDB you're running 10.4
- What OS and web server you're running Snipe-IT on 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error no error is being generated
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error asset checkout
- If a stacktrace is provided in the error, include that too. n/a
- Any errors that appear in your browser's error console. n/a
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. n/a
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

I believe my AD sync was working but is now broken. Test LDAP works but new users are not showing up.

LDAP Integration LDAP enabled (checked)
Active Directory This is an Active Directory server (checked)
LDAP Password Sync Yes (checked)
Uncheck this box if you do not wish to keep LDAP passwords synced with local passwords. Disabling this means that your users may not be able to login if your LDAP server is unreachable for some reason.

Active Directory domain
FQDN Redacted
This is sometimes the same as your email domain, but not always.

LDAP Server
ldap://Redacted
This should start with ldap:// (for unencrypted or TLS) or ldaps:// (for SSL)

Use TLS This should be checked only if you are running STARTTLS on your LDAP server.
LDAP SSL certificate validation Allow invalid SSL Certificate
Select this checkbox if you are using a self signed SSL cert and would like to accept an invalid SSL certificate.
LDAP settings below: 

LDAP Bind Username (Redacted)
LDAP Bind Password binduserpassword
Base Bind DN
DC=my,DC=domain,DC=com (Redacted)
LDAP Filter &(cn=*)
Username Field samaccountname
Last Name SN
LDAP First Name givenname
LDAP Authentication query samaccountname=
LDAP Version 3
LDAP Active Flag
LDAP Employee Number
LDAP Email mail

Thanks,

**Comment by Mariano7717** [comment]
Whats your LDAP Filter? Make sure the user you are missing is within the scope of the LDAP Filter applied.
i.e.: _Filter applied to Users members of a specific AD group. Only AD users not appearing after a LDAP Sync are those not within that AD gorup_

**Comment by Mariano7717** [comment]
> Whats your LDAP Filter? Make sure the user you are missing is within the scope of the LDAP Filter applied.
> i.e.: _Filter applied to Users members of a specific AD group. Only AD users not appearing after a LDAP Sync are those not within that AD gorup_

Just saw it, not the issue

**Comment by Phx86** [comment]
Just an update on this, I go to the People tab on the left - LDAP Sync - Synchronize and it brought over my newer users. So my everything is working except the automatic sync from AD.

**Comment by uberbrady** [comment]
It was probably one of the weirder UAC settings - sometimes if users are set with things like 'don't delegate' or 'password doesn't expire' or other more esoteric combinations, Snipe-IT will think that the user isn't a "real" user.

We keep tweaking those valid UAC settings as we see different values in the wild, one of those fixes probably got your newer users.

For automated syncing, you'd need to configure something on your system to run `php artisan snipeit:ldap-sync` as often as you need your users synced. That code is identical to what runs when you click the LDAP Sync button.

**Comment by snipe** [comment]
Is this issue resolved with the latest version? Good to close, or no?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
