### ISSUE TITLE
upgrade.php should ask for changing .htaccess file

### ISSUE THREAD

**Issue by dragonauta** [grokability/snipe-it#8497]
**Server (please complete the following information):**
 - Snipe-IT 4.9.5 
 - OS: Debian Buster 10.6
 - Web Server: Apache 2.4.38
 - PHP 7.3.19

**Is your feature request related to a problem? Please describe.**
Just an Idea:
After struggling for a couple of hours trying to upgrade a fully functional 4.9.4 version to 4.9.5, I found out that upgrading with 'php upgrade.php' replaces public/.htaccess
I have installed SnipeIT inside a folder (following [documentation](https://snipe-it.readme.io/docs/subdirectories)) for accessing from internet.
I have a reverse proxy and all is set correctly, I was running 4.9.4 without issues.
After upgrading, website was down (404 sad panda page). No errors, no logs... really strange.
Then I found out that using my local ip without folder I could access snipe-it. So I realized, git replaced my public/.htaccess.

**Describe the solution you'd like**
running 'php upgrade.php' should ask for replacing htaccess or at least make a backup.

**Describe alternatives you've considered**
.

**Additional context**
behind a reverse proxy, so you can access from internet: i.e.: http://mydinamicdns.com/snipe-it/

**Comment by uberbrady** [comment]
I think it definitely makes sense to at least copy the current `.htaccess` file to some kind of 'backup' `.htaccess` file before we overwrite it.

**Comment by snipe** [comment]
@uberbrady we would only ever overwrite that htaccess if there was a change to it in the source code itself (CSP headers added, etc), in which case we *want* that htaccess to be overridden, as we don't put a bunch of crap in there that's not needed. It happens like once every 3 years, so I'm not going to build anything in around that at this point.
