### ISSUE TITLE
Change Default column in assets or disable it's required to be filled 

### ISSUE THREAD

**Issue by king2004r** [grokability/snipe-it#8498]
#### Expected Behavior (or desired behavior if a feature request)

I want to change the default column or remove it, or just make it not required, because it's not needed in my company or use other names 

-----

#### Actual Behavior

I want to change the default column or remove it, or just make it not required 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
No
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
Yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Yes
- Version of Snipe-IT you're running
last verions
- Version of PHP you're running
7
- Version of MySQL/MariaDB you're running
5
- What OS and web server you're running Snipe-IT on
Unknown
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Assets
- If a stacktrace is provided in the error, include that too.
No
- Any errors that appear in your browser's error console.
No
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No error
- Include any additional information you can find in `storage/logs` and your webserver's logs.
No error
- Include what you've done so far in the installation, and if you got any error messages along the way.
No
- Indicate whether or not you've manually edited any data directly in the database
No
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by king2004r** [comment]
Hi any update please

**Comment by king2004r** [comment]
!!! Hi any update

**Comment by snipe** [comment]
That's not on the short-term roadmap.
