### ISSUE TITLE
Can't generate password for a new user created while creating a new asset

### ISSUE THREAD

**Issue by chdeliens** [grokability/snipe-it#8501]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Cannot use the "generate password" feature when trying to create a new user while creating a new asset.

**To Reproduce**

1. Click on "Create New > Asset"
2. Set "Status" to "Ready to Deploy"
3. Next to the "Checkout to" click on "New"
4. See error in the JS console

**Expected behavior**

No error in the console and the "generate password" link actually generates a password.

**Screenshots**
![image](https://user-images.githubusercontent.com/991003/95325933-239abe00-08a2-11eb-8ddf-0b9a572ae211.png)

**Server (please complete the following information):**

Deployed via Helm.
 - Snipe-IT Version: v4.9.4 - build 4437 (master)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.1.33

**Desktop (please complete the following information):**

 - OS: MacOS
 - Browser: Chrome
 - Version:  85.0.4183.121

**Error Messages**

```
all.js?id=4513ccdd4533b52922a8:2 Uncaught TypeError: $(...).pGenerator is not a function
    at HTMLDocument.<anonymous> (<anonymous>:4:27)
    at u (all.js?id=4513ccdd4533b52922a8:2)
    at c (all.js?id=4513ccdd4533b52922a8:2)
```

**Comment by uberbrady** [comment]
It looks like this has been fixed, I can't reproduce it on my local v5 install.
