### ISSUE TITLE
v5 beta storage changes are not working everywhere

### ISSUE THREAD

**Issue by p47-6** [grokability/snipe-it#8502]
I had a lot of problems in the v5 beta so i looked a little bit through the code and there a lot of things that haven´t been changed to use the actual storage provider. I`ve already posted this in the chat but i also wanted to state it here:

First of all the handleImages call in the ManufacturersController wasn't changed like the other Controllers so i did this:
```
diff --git a/app/Http/Controllers/ManufacturersController.php b/app/Http/Controllers/ManufacturersController.php
index 39944b13f..7cf14371d 100755
--- a/app/Http/Controllers/ManufacturersController.php
+++ b/app/Http/Controllers/ManufacturersController.php
@@ -70,7 +70,7 @@ class ManufacturersController extends Controller
         $manufacturer->support_url      = $request->input('support_url');
         $manufacturer->support_phone    = $request->input('support_phone');
         $manufacturer->support_email    = $request->input('support_email');
-        $manufacturer = $request->handleImages($manufacturer,600, public_path().'/uploads/manufacturers');
+        $manufacturer = $request->handleImages($manufacturer);



@@ -137,7 +137,7 @@ class ManufacturersController extends Controller
             $manufacturer->image = null;
         }

-        $manufacturer = $request->handleImages($manufacturer,600, public_path().'/uploads/manufacturers');
+        $manufacturer = $request->handleImages($manufacturer);


         if ($manufacturer->save()) {
```
The second "problem" is the usage of the storage local_public. I have absolutely no idea how it should look but with this config it works:
```
diff --git a/config/filesystems.php b/config/filesystems.php
index b4bf6303e..a483e8e74 100644
--- a/config/filesystems.php
+++ b/config/filesystems.php
@@ -51,8 +51,8 @@ $config = [
         // This applies the LOCAL public only, not S3/FTP/etc
         'local_public' => [
             'driver' => 'local',
-            'root' => public_path('uploads'),
-            'url' => env('APP_URL').'/uploads',
+            'root' => storage_path('app/public'),
+            'url' => env('APP_URL').'/storage',
             'visibility' => 'public',
         ],
```
Files are uploaded to `storage/app/public`, `public/storage` gets linked to `storage/app/public` and the generated urls are prefixed with `https://snipeit.example.com/storage/`. I have no idea if this works with other storage providers.

If you apply this change then everywhere a url of an image is used it should use the storage methode. e.g.: ``Storage::disk('public')->url(app('accessories_upload_path').e($accessory->image))``. Also the blades should get the urls using this method.

**Comment by uberbrady** [comment]
We don't use the symlinks, on purpose. We know that's a Laravel standard thing, but we decided to go the way we went where everything pretty much stays the same. We'll definitely check out that Manufacturers still updates correctly, though.

Ideally, we are hoping that a user *never* has to adjust `config/filesystems.php`. If you do, we messed up.

**Comment by uberbrady** [comment]
I *believe* these changes are in v5 now, can you confirm?
