### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by Sylencer91** [grokability/snipe-it#8503]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I followed the installation instructions. Snipe-IT is working fine over the IP-Adress. But when I open it with my subdomain.mydomain.com the CSS-files don't load.

**To Reproduce**
open subdomain.mydomain.com

**Expected behavior**
CSS is loading.

**Screenshots**
IP: ![grafik](https://user-images.githubusercontent.com/72518022/95364703-73dd4480-08d1-11eb-8c28-c2f16f19898f.png)

subdomain.mydomain.com: 

**Server (please complete the following information):**
 - Snipe-IT Version:  Version v4.9.5 - build 4482 (master)
 - OS: Ubuntu 20.04 on Proxmox VE
 - Web Server: apache2
 - PHP Version 7.4.3

**Desktop (please complete the following information):**
 - OS: Win10 Pro
 - Browser Firefox v81,  Chrome v85

**Error Messages**

**Additional context**
- Is this a fresh install or an upgrade? **fresh**
- What OS and web server you're running Snipe-IT on: **look above**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **manual**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Followed https://www.youtube.com/watch?v=5MWA-DRyTZM**
- Indicate whether or not you've manually edited any data directly in the database: **only in the .env file**

Add any other context about the problem here:
I edited the .env file APP_URL=https://subdomain.mydomain.com
**snipeit.config apache2 on LXC with snipe-it:**
```
<VirtualHost *:80>

        ServerName https://subdomain.mydomain.com   
        ServerAdmin webmaster@mydomain.com
        DocumentRoot /var/www/html/snipeit/public		
		
        <Directory /var/www/html/snipeit/public>
                Allow From All
		AllowOverride All
                Options - Indexes
        </Directory>
		
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        
</VirtualHost>
```

**Snipe-IT is running behind a apache2 reverse proxy on a other LXC in proxmox. I added in .env file the IP of the proxy server.
APP_TRUSTED_PROXIES=192.168.XXX.XX**
```
<VirtualHost *:80>

 ServerName subdomain.mydomain.com
 ProxyPreserveHost On
 DocumentRoot /var/www/html
 ProxyPass /.well-known !
 ProxyPass / http://192.168.XXX.XX:80/
 ProxyPassReverse / http://192.168.XXX.XX:80/
 RequestHeader set X-Forwarded-Proto "https"

 RewriteEngine on
 RewriteCond %{ServerName} =subdomain.mydomain.com
 RewriteRule ^https://%{ServerName}%{REQUEST_URI} [END, NE,R=permanent]

</VirtualHost>
```

Thank you in advance.

**Comment by roomwillow** [comment]
I am having a similar issue, brand new installation of SnipeIT on Debian 10, using Apache, entire '/var/www/snipe-it' directory has 775 owned by www-data:www-data, Apache configs are as follows:

/etc/apache2/sites-available/000-default.conf
```
DocumentRoot /var/www/snipe-it/public
```

/etc/apache2/apache2.conf
```
<Directory /var/www/snipe-it/public>
     Options +FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```

Reverse Proxy Config:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name sub.domain.tld;

    ssl_certificate /path;
    ssl_certificate_key /path;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 5m;
    ssh_dhparam /path;
    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers long-irrelevant-list;

    location / {
        proxy_pass http://ip;
        proxy_set_header  X-Forwarded-Proto https;
    }
}
```
/var/www/snipe-it/.env
```
APP_URL=https://sub.domain.tld
APP_TRUSTED_PROXIES=ip-of-reverseproxy
```

using HTTP from snipe to proxy, HTTPS from proxy to client, above is all the config, anyone see any glaring issues? Pre-Flight page loads without CSS but no immediete errors (see image attached)
![Screen Shot 2020-10-11 at 4 26 19 PM](https://user-images.githubusercontent.com/67667062/95689407-895ab300-0bde-11eb-8b58-69fe9e02807a.png)

**Comment by ukasiu** [comment]
Seems X-Forwarded-Proto is broken in v5, I'm also affected

**Comment by sphr2k** [comment]
Same issue here. Snipe-IT (HTTP) running behind reverse proxy (HTTPS). X-Forwarded-Proto seems to be ignored.

**Comment by fashberg** [comment]
same issue as #8543 - i've added PR #8556

**Comment by Sylencer91** [comment]
This doesn't help me. Editing /var/www/html/config/trustedproxy.php and uncommenting 'proxies' => '*', doesn't fix my problem. It is still here.

**Comment by Sylencer91** [comment]
Works for me. I deleted my Apache RP conf and did it exactly the same way again. When someone needs the config, feel free to comment here. Closing. Thank you.
