### ISSUE TITLE
v5 LDAP settings save button blanks out passwords if nothing typed in password field

### ISSUE THREAD

**Issue by uberbrady** [grokability/snipe-it#8507]
in v5, go to LDAP Settings page, where you had already put in a password. Confirm your password works by clicking "Test LDAP Sync". Click save - without even having changed anything. Now click on "Test" again - you'll see it no longer binds.

If you check the Settings table, you'll see that the password field now decrypts to `null`.

**Comment by snipe** [comment]
This should be fixed on develop already - can you test?

**Comment by uberbrady** [comment]
Just did, worked like a charm!

**Comment by snipe** [comment]
Sweet, thanks!
