### ISSUE TITLE
[v5.0.0-beta-7-GM] "Login enabled" disabled after LDAP sync

### ISSUE THREAD

**Issue by drhirn** [grokability/snipe-it#8512]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After starting an LDAP sync, all "login enabled" users are reset to "login disabled"

**To Reproduce**
1. Start LDAP Sync
2. Enable login for LDAP user
3. Start LDAP Sync again
4. Login is now disabled for user

**Expected behavior**
The user should still be allowed to login after an LDAP Sync if this setting is manually changed before

**Server (please complete the following information):**
- Snipe-IT Version v5.0.0-beta-7-GM
- OS: RedHat 7
- Web Server: Apache
- PHP Version 7.3
- Microsoft Active Directory

Is this a fresh install or an upgrade? - **Upgrade from v5.0.0-beta-6-GM**
What method you used to install Snipe-IT - **Git**
Indicate whether or not you've manually edited any data directly in the database - **No**

**Comment by drhirn** [comment]
This is the same with every information I added to the user. Like location, departement, etc.

**Comment by uberbrady** [comment]
Have you tried the latest v5? We've juggled a lot of the logic recently about how login-enabled works.

**Comment by snipe** [comment]
Hi there - Pretty sure this has been working for a long time now, sorry for not closing this sooner. I'm going to close this. Please feel free to open a new issue if you're still having trouble.
