### ISSUE TITLE
QR Code URL broken/weird

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#8515]
#### Expected Behavior (or desired behavior if a feature request)

Shows the QR Code in die Asset View

-----

#### Actual Behavior

Doenst show the QR Code. The URL seems really broken.

It links to:

http://my.snipeit-url.com/hardware/**my.snipeit-url.com**/hardware/4/qr_code

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh Install

- Version of Snipe-IT you're running
v4.9.5 build 4482 (g5b68a321a)

- Version of PHP you're running
7.4.3

- Version of MySQL/MariaDB you're running
 8.0.21-0ubuntu0.20.04.4

- What OS and web server you're running Snipe-IT on
Ubuntu 20.4, Apache 2 2.4.41

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No Error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
APP-URL/hardware

- If a stacktrace is provided in the error, include that too.
/

- Any errors that appear in your browser's error console.
GET http://my.snipeit-url.com/hardware/my.snipeit-url.com/hardware/4/qr_code 404 (Not Found)

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Not reproducible 

- Include any additional information you can find in `storage/logs` and your webserver's logs.
/

- Include what you've done so far in the installation, and if you got any error messages along the way.
Created some assets and imported users with LDAP

- Indicate whether or not you've manually edited any data directly in the database
Nope

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
What do you have as your APP_URL in your env?

**Comment by ghost** [comment]
> What do you have as your APP_URL in your env?

http://my.snipeit-url.com (Changed URL)

**Comment by snipe** [comment]
There’s nothing in the QR code stuff that would double the url like that. Perhaps those codes were generated before and they are cached. Try running `php artisan config:clear` and then delete the generated barcodes in the `public/uploads/barcodes` directory

**Comment by ghost** [comment]
Yep it was a really nasty cache. Works now. Thanks a lot for the help and thanks for that nice piece of software!
