### ISSUE TITLE
Asset Tag not correctly incremented when adding multiple assets

### ISSUE THREAD

**Issue by drhirn** [grokability/snipe-it#8518]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Trying to add multiple assets at once using the "+" behind the _Asset Tag_ line. Configured the the asset ids to autoincrement with a length of 5 including leading zeros.
The first assets get's the asset tag **00001** which is correct. The following have tags like **2**, **3**, **4**, etc. withouth the leading zeros.

**To Reproduce**
1. Create new asset
2. Click on **+** next to "Asset Tag"
3. First id is correct, the following are wrong

**Expected behavior**
All following ids should have to correct format with the leading zeros.

**Screenshots**
Asset Tag Configuration:
![asset_tag_config](https://user-images.githubusercontent.com/1773236/95971023-f05fae00-0e10-11eb-9046-d119b1643978.png)

Wrong behavior when adding multiple assets:
![wrong_asset_tags](https://user-images.githubusercontent.com/1773236/95971027-f0f84480-0e10-11eb-9568-e3aa542fb2a9.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.0-beta-7-GM - build 4484 (develop)
 - Docker Image

**Comment by ThoBur** [comment]
Same here.

![image](https://user-images.githubusercontent.com/70443365/97159983-f7c17880-177b-11eb-8e86-ca6c3fa3b55c.png)

Snipe-IT Version v5.0.1

**Comment by ghost** [comment]
I just upgraded from 4.9.x to v5.0.5-pre - build 5457 (master) and have the same problem. 
![image](https://user-images.githubusercontent.com/1732243/98500235-4d734600-228f-11eb-9b3b-f6b8d34f9131.png)

Branch is: master
Type is: patch
Current version is: v5.0.4-35-g6618e88a9
Running: git rev-parse master v5.0.4
PHP: 7.3.19-1~deb10u1
Webserver: nginx/1.14.2
DB: mysql 10.3.25-MariaDB-0+deb10u1 Debian 10

**Comment by ThoBur** [comment]
The following code is a possible solution for the problem in line 1148. The 'parseInt' function removes the leading zero´s.

```
const zeroPad = (num, places) => String(num).padStart(places, '0');

auto_tag = zeroPad(parseInt(auto_tag) + parseInt(x),auto_tag.length);
```

![add_button_create](https://user-images.githubusercontent.com/70443365/98571301-b4572600-22b4-11eb-91a1-da2adb7ecc48.PNG)
