### ISSUE TITLE
Confusing wording in LDAP menu

### ISSUE THREAD

**Issue by goneafk** [grokability/snipe-it#8532]
https://github.com/snipe/snipe-it/blob/12ae408830c68bd9e35117ee89141922a62792ba/resources/lang/en/admin/settings/general.php#L9

The language here isn't clear. "User doesn't require to write "

It should be "User isn't required to" or "User doesn't need to".

**Comment by snipe** [comment]
@Godmartinz can you fix this when you get a moment?

**Comment by Godmartinz** [comment]
#8586 fixed!
