### ISSUE TITLE
diy upload logo 404 

### ISSUE THREAD

**Issue by linux-ops** [grokability/snipe-it#8534]
![image](https://user-images.githubusercontent.com/6948476/96569178-68d7da80-12fb-11eb-8a0d-a53585562cb2.png)

new verison 5

**Comment by ghost** [comment]
+1, seems images are duplicating the URL for both the logo and product images.
![image](https://user-images.githubusercontent.com/66947149/96602558-0e368280-12eb-11eb-842a-0b363981569c.png)

**Comment by snipe** [comment]
This seems to be the same as #8559, which has a little more discussion on it. Closing this for now.
