### ISSUE TITLE
Error in Spanish translation

### ISSUE THREAD

**Issue by diegogarciadev** [grokability/snipe-it#8536]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
An error 500 appear in application

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.0
 - OS: CentOS
 - Web Server: Apache
 - PHP Version 7.1.3

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
[previous exception] [object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected 'tamaño' (T_STRING), expecting ']' at /var/www/html/snipe-it/resources/lang/es-ES/general.php:210)

**Additional context**

'upload_filetypes_help'      => 'Algunos tipos de archivos permitidos son png, gif, jpg, jpeg, doc, docx, pdf, xls, txt, lic, zip, rtf y rar. Tamaño máximo permitido: :size.',
**El tamaño máximo de archivo es :size.',** --> Should remove this line

**Comment by snipe** [comment]
We use Crowdin to handle translations. We’d be happy to have your input there 

https://snipe-it.readme.io/docs/translations



<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/translations">Translations</a></strong></div><div>Traduci! 翻訳！Oversette! Traduire! 번역하기! แปล! ¡Traducir! Przetłumacz! Übersetzen!</div></blockquote>

**Comment by diegogarciadev** [comment]
@snipe There are an error in file, not in translation. The fille has an error that blocks application. Line 210 should be deleted.

![image](https://user-images.githubusercontent.com/5694236/97403421-a983b500-18f4-11eb-864f-e51b6fa4cac5.png)

Thank you.
