### ISSUE TITLE
[v5.0.0] Recent Activity -> wrong sorting

### ISSUE THREAD

**Issue by hdering** [grokability/snipe-it#8537]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The sorting is wrong with the new version.  It should see the newest first. You see the old one first.

**To Reproduce**
1. Go to 'Dashboard'
2. See 'Recent Activity'

**Expected behavior**
The newest should be seen first.

**Screenshots**
![image](https://user-images.githubusercontent.com/3204979/96573923-1385d400-12cf-11eb-88cc-7b743d01f5a7.png)
![image](https://user-images.githubusercontent.com/3204979/96573988-27c9d100-12cf-11eb-808a-5be274971f8f.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.0
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.2.24-0ubuntu0.18.04.7

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 86.x

**Additional context**
- Is this a fresh install or an upgrade? 
upgrade

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
uprade.php

**Comment by snipe** [comment]
I have noticed that. I don’t yet have an explanation for it. The query we do Is pretty straightforward, but it seems latest versions of the JS library may disagree. We’re on it. I still don’t know why it’s happening, but I can reproduce it.

**Comment by jovibroz** [comment]
Same for me and for the demo.. but on the "view all" page its sorted correctly.

**Comment by snipe** [comment]
@jovibroz Yeah, I can see it too - what's bizarre is that those two screens use the exact same API call, and if you call just via API, it sorts as expected. It's a head-scratcher.

@inietov FYI, the CH for this is 15305

**Comment by jovibroz** [comment]
I'm glad I'm just a sound engineer with the required computer skills to keep a workstation (and a few ubuntu servers) runnin! :) I'd stay up all night, every night to fix those kinda things if only I knew how :) 
10 PRINT "YO!"
20 GOTO 10
RUN

**Comment by snipe** [comment]
Hah, that's pretty much what it looks like on our end, too :D 

`\Log::debug('IS THE SKY EVEN BLUE WTF');`

We did update the bootstrap-tables javascript, but the weird part is that it was updated everywhere, so I'd expect to see at least *consistent* behavior. I know in the past I've tried adding the normal table headers (the reload, export, etc) and it seemed to fix it, but that kind doesn't make any sense either (and I really didn't want to jank up the UI with those elements on the dashboard.)

**Comment by jovibroz** [comment]
Awesome fix in 5.04. Just a notice that the backups flipped order with this one :)

**Comment by snipe** [comment]
Huh. I didn’t even do anything with backups in that release.
