### ISSUE TITLE
Accessory Notes not saving / displaying correctly V5.0.0

### ISSUE THREAD

**Issue by gilesytheking** [grokability/snipe-it#8538]
#### Expected Behavior (or desired behavior if a feature request)

Notes added during checkout / check in to display in the notes column for each accessory

-----

#### Actual Behavior

Appears to be displaying the last saved note for all items and not for each individual accessory checked out/in. A quick look at the database, it appears that the note value is not being saved in the database
![note error](https://user-images.githubusercontent.com/15634270/96578531-416a1900-12cd-11eb-9434-01a3dfa94da9.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ YES ] I have enabled debug mode 
- [ YES ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade to V5.0.0
- Version of PHP you're running 7.4
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  - YES

**Comment by gilesytheking** [comment]
Appears to be the same issue as #8462 - looks like the issue was present in the beta version

**Comment by snipe** [comment]
@gilesytheking thanks for this - I'll close this one as a duplicate of #8462 and tag that issue once it's fixed.
