### ISSUE TITLE
Upgrade to 5.0.0: Database Access denied

### ISSUE THREAD

**Issue by titouanbrauchli** [grokability/snipe-it#8541]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to access Snipe-IT through the Browser (Chrome), the pre-flight check is displayed. Except the database, all sections are green. The database section shows the following: `D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: SQLSTATE[HY000] [1045] Access denied for user 'snipe_user'@'localhost' (using password: YES) (SQL: select 2 + 2)` (see screenshot below). This is happening since the upgrade this morning from 4.9.5 to 5.0.0 as  described [here](https://snipe-it.readme.io/v5.0.0-develop/docs/upgrading).

I've already checked the privileges on the mysql database server, tried to reset the password of the snipe_user, delected and recreated the user and reset the privileges. The error is always the same. I've also checked the file permissions and set all to the www-data user, which did not change anything.

**To Reproduce**
Upgrade from 4.95 to 5.0.0

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/39410412/96586939-f73f6280-12e1-11eb-8ba6-a92c2f4420ce.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.0
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 20.04.1 LTS
 - Web Server: [e.g. Apache, IIS] Nginx
 - PHP Version 7.4.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 86.0.4240.75

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? --> upgrade
- What OS and web server you're running Snipe-IT on --> see above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --> install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database --> no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by nbently** [comment]
Also happened to me when I ran the upgrade.

**Comment by nbently** [comment]
@titouanbrauchli this may not be your problem, but I would check to make sure you don't have a # in your db password (causing Laravel to see the text after it as a comment) or that the password is appropriately enclosed in quotes. As has been suggested in https://github.com/snipe/snipe-it/issues/8553#issuecomment-713220686, there was a big jump in the Laravel version in the v5 release and the .env parser seems to be much more strict than it was before.

**Comment by titouanbrauchli** [comment]
@nbently Indeed I had a # in the password. But i changed the password to different variantions now and it does not seem to change anything. When logging in to mysql with mysql -u snipe_user -p, though, everything works fine. I noticed that changes to the .env file are not displayed in the pre-flight page. E.g. after changing the DB user to 'afsdnklas' in the .env file and clearing all caches and restarting nginx, the pre-flight still shows access denied for user 'snipe_user'@'localhost'...

**Comment by titouanbrauchli** [comment]
actually, I got it to work now. I've only seen now, that the log has more details about where the access is denied. Access to the database `snipeit` was no problem, but somehow the table `information_schema` was not up to date. Solution is to log in to mysql as root, then `use information_schema;` and then `flush tables;`. This resets the `information_schema` table and voila, Snipe-IT is running again.

**Comment by nbently** [comment]
> actually, I got it to work now. I've only seen now, that the log has more details about where the access is denied. Access to the database `snipeit` was no problem, but somehow the table `information_schema` was not up to date. Solution is to log in to mysql as root, then `use information_schema;` and then `flush tables;`. This resets the `information_schema` table and voila, Snipe-IT is running again. 

Glad you were able to figure that bit out! Funny, I actually have been re-running the upgrade a couple times on my dev instance to see if I can get other errors and this one did indeed crop up for me. Your suggestion to flush the information_schema table actually fixed my problem.

**Comment by snipe** [comment]
That makes even less sense, tbh. We do make some schema changes in v5, but nothing that should require flushing db privs.

**Comment by titouanbrauchli** [comment]
Maybe it makes no sense. But the log showed errors with `access denied` and then some select statements to the database `information_schema`. That is why I flushed this tables. Unfortunately, I have not copied the logs at that time to show the exact log entry.

**Comment by snipe** [comment]
@titouanbrauchli Sorry, I wasn't implying you did anything wrong, just that that's a weird error to get given the nature of this update. :)

**Comment by TheTopherNet** [comment]
Just wanted to add, I was having the same issue, I did have a # in my password, of which I was not about to changed due to all the other systems dependent on those credentials.

However I added ' ' around my sql password and it worked!

`# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=dbname
DB_USERNAME=super
DB_PASSWORD='mypassword#'
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci
`

**Comment by x3inspire** [comment]
> actually, I got it to work now. I've only seen now, that the log has more details about where the access is denied. Access to the database `snipeit` was no problem, but somehow the table `information_schema` was not up to date. Solution is to log in to mysql as root, then `use information_schema;` and then `flush tables;`. This resets the `information_schema` table and voila, Snipe-IT is running again.

Hi, i'm having problem same as your. Could you tell the step please? I can't get it.

**Comment by ravigfx** [comment]
DB_DATABASE=dbname DB_USERNAME=super DB_PASSWORD='mypassword#' In this places I am getting the issues please help me out on this guys

**Comment by priakant** [comment]
Hi Guys kindly do this process it will resolve
 
php artisan cache:clear;
php artisan config:clear;
