### ISSUE TITLE
v5.0.0 on Docker: hostname without protocol in resources

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#8543]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
In v5.0.0 Docker image in a Rancher2 envirnment with tls-terminating nginx ingress some resources like js and css have the hostname without https://, so they won't load.

APP_URL and TRESTED_PROXIES variable are correctly set, v 4.9.x was working right before the upgrade 

**Screenshots**
![image](https://user-images.githubusercontent.com/33548070/96591123-345a2380-12e7-11eb-8f92-ba06e748ae24.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.0
 - ENV: Official Docker COntainer

**Comment by ghost** [comment]
Update: the problem semmes to be that APP_TRUSTED_PROXIES is ignored, because editing config/trustedproxy.php by hand correct the problem.

Anyway in a docker environment this is not the right solution.

**Comment by mahdi** [comment]
Where is config/trustedproxy.php inside the container? Couldn't find it under /config.

**Comment by mahdi** [comment]
Yes, editing /var/www/html/config/trustedproxy.php and uncommenting `'proxies' => '*',` will temporarily fix the issue but as @Cobra1978 said this issue should be generally fixed.

**Comment by fashberg** [comment]
Hey!
Same for me. 

copying APP_TRUSTED_PROXIES from ENV to settings has been removed at commit 533649f24e011732c66b11bbfb872216b7b0862c

Diff:
https://github.com/snipe/snipe-it/commit/533649f24e011732c66b11bbfb872216b7b0862c#diff-65b9650370ce063c0ae4c2d172d40fb6aafd2d2e8fe478dae7da21732d4d36dd

removed code:

```php
    'proxies' => env('APP_TRUSTED_PROXIES') !== null ?
        explode(',', env('APP_TRUSTED_PROXIES')) : '*',
```

Especially for Docker environments we need this ENV settingg

Kind Regards
Folke

**Comment by mschmidt291** [comment]
Yes, can also confirm. Running Snipe-IT through our Snipe-IT Helm Chart behind the nginx ingress controller results in css and js loading issues. Uncommenting the line in trustedproxy.php stated above, works fine.

**Comment by Sylencer91** [comment]
This doesn't help me. Editing /var/www/html/config/trustedproxy.php and uncommenting 'proxies' => '*', doesn't fix my problem. It is still here. Any Idea?
