### ISSUE TITLE
Signatures missing after upgrade to v5

### ISSUE THREAD

**Issue by ArcheNoah77** [grokability/snipe-it#8545]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After the upgrade to v5 using "php upgrade.php" the signatures are missing.
The files are still present in /var/www/snipeit/storage/private_uploads/signatures but not shown in the history tab of the assets:

**To Reproduce**
Doing upgrade to v5

**Expected behavior**
Signatures sould be displayed

**Screenshots**
![No Signatures](https://user-images.githubusercontent.com/25475591/96594991-7f763580-12eb-11eb-83ab-199b49e320c8.png)

**Server (please complete the following information):**
 - Snipe-IT Version : 5.0.0
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version: 7.2.24

Additional context:
In the End of the upgrade process i get the following warning. In the end it says "- Copy failed - you should do this manually by copying the files from public/uploads into the storage/app/public directory" But the folders in "public/uploads" is empty and all images (from models etc.) are gone. I had to copy all file from "storage/app/public" to "public/uploads" to get all images displayed again. So the exact opposite...

--------------------------------------------------------
Step 11: Checking for v5 public storage directories:
--------------------------------------------------------

- No public directory found in storage/app - creating one.

The [public/storage] directory has been linked.
- Copying files into storage/app/public.

PHP Warning:  unlink(/var/www/snipeit/public/uploads/components): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/components): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/suppliers): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/suppliers): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/companies): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/companies): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/models): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/models): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/manufacturers): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/manufacturers): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/consumables): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/consumables): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/components): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/components): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/suppliers): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/suppliers): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/companies): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/companies): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/models): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/models): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/manufacturers): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/manufacturers): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/consumables): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/consumables): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/categories): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/categories): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/avatars): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/avatars): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/accessories): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/accessories): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/assets): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/assets): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/locations): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/locations): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/barcodes): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/barcodes): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/departments): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads/departments): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/uploads): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/categories): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/categories): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/avatars): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/avatars): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/accessories): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/accessories): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/assets): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/assets): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/locations): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/locations): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/barcodes): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/barcodes): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(/var/www/snipeit/public/uploads/departments): Is a directory in /var/www/snipeit/upgrade.php on line 249
PHP Warning:  unlink(/var/www/snipeit/public/uploads/departments): Is a directory in /var/www/snipeit/upgrade.php on line 246
PHP Warning:  unlink(public/uploads): Is a directory in /var/www/snipeit/upgrade.php on line 249
- Copy failed - you should do this manually by copying the files from public/uploads into the storage/app/public directory.

--------------------------------------------------------
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.
--------------------------------------------------------

**Comment by snipe** [comment]
Yeah, that upgrade script shouldn't have tried moving those files. We've patched it in v5.0.1. If the files exist in `storage/private_uploads/signatures` they should still be showing up though. Anything in your error logs (app and php)?

**Comment by ArcheNoah77** [comment]
Nothing in the error logs. I checked the laravel.log and the /var/log/apache2/error.log. Any other logs?

Maybe the permissions aren't rigth?
![image](https://user-images.githubusercontent.com/25475591/96908174-8e501a00-149c-11eb-866b-c6a71faa0b28.png)

(With 5.0.1 the images of the models etc. are displayed)

**Comment by ArcheNoah77** [comment]
With v5.0.2 the signatures are displayed. Thanks! But there is another issue with signing for an asset. I will create a new issue
