### ISSUE TITLE
LDAP sync only 1 user

### ISSUE THREAD

**Issue by mrenbe** [grokability/snipe-it#8549]
I have installed the version 4.9.5 in a docker container (MySQL & SnipeIT) and everything looks good. Unfortunately when I sync ldap it just syncs 1 user. I don't know if there is a log check somewhere.

Please advise if it is a known bug of if there is a workaround to sync all my users.

Thanks.

**Comment by roratonet** [comment]
> I have installed the version 4.9.5 in a docker container (MySQL & SnipeIT) and everything looks good. Unfortunately when I sync ldap it just syncs 1 user. I don't know if there is a log check somewhere.
> 
> Please advise if it is a known bug of if there is a workaround to sync all my users.
> 
> Thanks.

Can you post a screen of your LDAP settings?
What us the output after an LDAP sync? One user?

**Comment by uberbrady** [comment]
We have tons and tons of users who do LDAP syncs and logins all the time, and it generally tends to work.

Is it possible your Base Bind DN is set too 'deep'?

**Comment by mrenbe** [comment]
Hi Uberbrady,

Your right the Base Bind DN I was too deep. I tried with another Directory limiting the Base DN to ou=xx,dc=xxx,dc=xx and then it worked. Thanks for you help.
