### ISSUE TITLE
Bulk edit not working

### ISSUE THREAD

**Issue by ycmq** [grokability/snipe-it#8554]
#### Expected Behavior (or desired behavior if a feature request)

able to update status for multiple assets at sametime

-----

#### Actual Behavior

when select only status in the page and press save, the page will show please select an item in the list and unable to save the change. If I select something from the model drop list at the same time, I will be able to click the save, but all the assets will disappear from the assets list after finish saving 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? tested on both fresh and upgrade 
- Version of Snipe-IT you're running V5.0
- Version of PHP you're running 7.3.20
- Version of MySQL/MariaDB you're running 8.0.21
- What OS and web server you're running Snipe-IT on tested on windows and ubuntu 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) docker and manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Yes
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by ycmq** [comment]
![image](https://user-images.githubusercontent.com/4264877/96679568-9f772900-13bf-11eb-8d80-26b10323aa22.png)

**Comment by snipe** [comment]
@bzeus - can you try to reproduce please?

**Comment by ycmq** [comment]
Issue fixed in 5.0.3
