### ISSUE TITLE
API - error creating user after upgrade to V5

### ISSUE THREAD

**Issue by m4zl** [grokability/snipe-it#8561]
Hi,

I am trying to create a new user via the API after the upgrade. Before everything worked fine, but now I am getting the following error message:

> **{The selected manager id is invalid., The manager id and users.id must be different.}**

I am not even trying to attach a manager while creating an user. 

Thanks in advance!

Kind Regards,

M. Büttinghaus

**Comment by Ashficial1** [comment]
Right

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 21, 2020 at 7:24 AM, hiimmazl<notifications@github.com> wrote:   


Hi,

I am trying to create a new user via the API after the upgrade. Before everything worked fine, but now I am getting the following error message:


{The selected manager id is invalid., The manager id and users.id must be different.}


I am not even trying to attach a manager while creating an user.

Thanks in advance!

Kind Regards,

M. Büttinghaus

**Comment by snipe** [comment]
Hi folks - looking into this now, thanks!

**Comment by snipe** [comment]
Huh. I'm actually unable to reproduce this locally. :-/

```
curl --location --request POST 'https://snipe-it.local:8890/api/v1/users' \
--header 'Authorization: Bearer MY-BEARER-TOKEN' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
--data-urlencode 'first_name=ljfdjdfjgh' \
--data-urlencode 'password=fartslfjghjkhg!!766455G' \
--data-urlencode 'password_confirmation=fartslfjghjkhg!!766455G' \
--data-urlencode 'username=ksdfjhgsejrkghkjfhgkfhh'
```

Can you show me an example curl command (or any other code) with anything sensitive redacted?

**Comment by ISNL-PimP** [comment]
Getting the same error when patching any user:
```powershell
PS U:\Projects\Snipe> $Result = Set-SnipeApi users 4 @{manager_id=1}
PS U:\Projects\Snipe> $Result
status messages                      payload
------ --------                      -------
error  @{manager_id=System.Object[]}
PS U:\Projects\Snipe> $Result.messages

manager_id
----------
{The manager id and users.id must be different.}
```
This command would call https://snipe-url/api/v1/users/4 with a PATCH body of `{"manager_id":1}`

I'm getting the same error message in the frontend when selecting a manager:
![image](https://user-images.githubusercontent.com/59050598/96857380-3646f280-145f-11eb-9ef8-eb6f7aec2d8f.png)

**Comment by snipe** [comment]
@ISNL-PimP can you reproduce this on the demo?

**Comment by ISNL-PimP** [comment]
Yep!
On https://demo.snipeitapp.com/users/41/edit:
![image](https://user-images.githubusercontent.com/59050598/96966882-e6bfff80-150e-11eb-92b9-9f3aa65b6b1f.png)




<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/users/41/edit">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by m4zl** [comment]
I also needed to exclude the manager from updating via the API and now my script is working again. Even if I did not touch the manager attribute the error as above shown occured. 

I could also reproduce it as @ISNL-PimP did in the Demo.

**Comment by snipe** [comment]
I can reproduce this locally now, but I have no idea what's triggering it yet. The validation on the user model is pretty straightforward. 

```
 'manager_id'              => 'nullable|exists:users,id|different:users.id',
```

**Comment by ISNL-PimP** [comment]
I'm really not familiar with this validation syntax, but I noticed locations use a similar hierarchy (parent locations) with a different syntax for the validation:
```php
'parent_id'     => 'nullable|exists:locations,id|different:id',
```
(Found in https://github.com/snipe/snipe-it/commit/fa5134603f8dbef6f67a9f98b9e370cdcf3460c5)
The above does not show the same issue.
Would changing `different:users.id` to `different:id` help in any way?

**Comment by snipe** [comment]
> Would changing different:users.id to different:id help in any way?

@ISNL-PimP I wish :( Already tried that (and a dozen other permutations.) 

![crazy-pills](https://user-images.githubusercontent.com/197404/97022402-eb81b500-1508-11eb-94c1-1a8ee8b238b6.gif)

**Comment by snipe** [comment]
I've pulled that `different:id` validator rule for now, just so we're not preventing people from successfully using the system. It's not ideal, as it means that validation is gone now and folks can make the mistake of making themselves their own manager which can have odd results, but this will at least buy us a little time.

Changes are on master and develop now.

**Comment by snipe** [comment]
@uberbrady has a PR up that will re-add the validation in a different way
