### ISSUE TITLE
After changing IP of Snipe-IT server, password does not work

### ISSUE THREAD

**Issue by EmptySet00** [grokability/snipe-it#8564]
#### Expected Behavior (or desired behavior if a feature )

After changing the IP of the server and updating it in the .env file application would allow password to function as expected.
-----

#### Actual Behavior

After changing the IP of the server and updating it in the .env file, my password no longer works.  I can reset my password via the email link and it logs me in but when I log out and try to log back in the reset password fails and I have to reset it each time. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running: v4.1.14 build 3446
- Version of PHP you're running : PHP 5.6.34 
- Version of MySQL/MariaDB you're running : mysql  Ver 15.1 Distrib 5.5.56-MariaDB
- What OS and web server you're running Snipe-IT on : CentOS 7 /Apache/2.4.6 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error : No error message during debug
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. : Installation is over a year old and had been working fine.  Hadn't logged into the system in quite some time though and after the re-IP, I updated the .env file for the APP_URL and the email settings. 
- Indicate whether or not you've manually edited any data directly in the database : No edits in database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Make sure the `COOKIE_DOMAIN` in your .env is updated to match the new IP. (Or set it it to null)

Clear your browser cookies, and clear your config cache. `php artisan config:clear`.

**Comment by EmptySet00** [comment]
Hi,

 COOKIE_DOMAIN was already set to null.  I ran php artisan config:clear again and also restarted the server again and it seems to be working again.  

Thank you.
