### ISSUE TITLE
Cannot Perform Backups Using Site; Can In PowerShell

### ISSUE THREAD

**Issue by WELLBOREIS** [grokability/snipe-it#8565]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
For whatever reason, I am unable to generate backups using the web gui, however updates can still be processed via PowerShell

**To Reproduce**
1. Go to /admin/backups
2. Click on Generate Backup
3. See error

**Expected behavior**
Backup generates successfully.

**Screenshots**
![Backup_Issue](https://user-images.githubusercontent.com/72811138/96748012-9de13d00-138e-11eb-9dc9-e81460586230.png)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

`Error: Backup failed because The dump process failed with exitcode 1 : General error : . #0 C:\inetpub\wwwroot\Snipe-IT\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully() #1 C:\inetpub\wwwroot\Snipe-IT\vendor\spatie\db-dumper\src\Databases\MySql.php(190): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul() #2 C:\inetpub\wwwroot\Snipe-IT\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(250): Spatie\DbDumper\Databases\MySql->dumpToFile() #3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}() #4 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Support\Collection.php(638): array_map() #5 C:\inetpub\wwwroot\Snipe-IT\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(253): Illuminate\Support\Collection->map() #6 C:\inetpub\wwwroot\Snipe-IT\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(167): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #7 C:\inetpub\wwwroot\Snipe-IT\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(143): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #8 C:\inetpub\wwwroot\Snipe-IT\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run() #9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle() #10 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(32): call_user_func_array() #11 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Container\Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #12 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure() #13 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod() #14 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call() #15 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call() #16 C:\inetpub\wwwroot\Snipe-IT\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute() #17 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run() #18 C:\inetpub\wwwroot\Snipe-IT\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(16): Illuminate\Console\Command->run() #19 C:\inetpub\wwwroot\Snipe-IT\vendor\symfony\console\Application.php(1001): Spatie\Backup\Commands\BaseCommand->run() #20 C:\inetpub\wwwroot\Snipe-IT\vendor\symfony\console\Application.php(271): Symfony\Component\Console\Application->doRunCommand() #21 C:\inetpub\wwwroot\Snipe-IT\vendor\symfony\console\Application.php(147): Symfony\Component\Console\Application->doRun() #22 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run() #23 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Console\Application.php(185): Illuminate\Console\Application->run() #24 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(273): Illuminate\Console\Application->call() #25 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Foundation\Console\Kernel->call() #26 C:\inetpub\wwwroot\Snipe-IT\app\Http\Controllers\SettingsController.php(1053): Illuminate\Support\Facades\Facade::__callStatic() #27 [internal function]: App\Http\Controllers\SettingsController->postBackups() #28 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array() #29 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction() #30 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch() #31 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController() #32 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(681): Illuminate\Routing\Route->run() #33 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #34 C:\inetpub\wwwroot\Snipe-IT\app\Http\Middleware\CheckPermissions.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #35 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckPermissions->handle() #36 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #37 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle() #38 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #39 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle() #40 C:\inetpub\wwwroot\Snipe-IT\app\Http\Middleware\CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #41 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle() #42 C:\inetpub\wwwroot\Snipe-IT\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #43 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckLocale->handle() #44 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #45 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #46 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #47 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #48 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #49 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle() #50 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #51 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then() #52 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack() #53 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute() #54 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute() #55 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch() #56 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #57 C:\inetpub\wwwroot\Snipe-IT\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #58 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() #59 C:\inetpub\wwwroot\Snipe-IT\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #60 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle() #61 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #62 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #63 C:\inetpub\wwwroot\Snipe-IT\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #64 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle() #65 C:\inetpub\wwwroot\Snipe-IT\app\Http\Middleware\CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #66 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle() #67 C:\inetpub\wwwroot\Snipe-IT\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #68 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle() #69 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #70 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #71 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #72 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle() #73 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #74 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() #75 C:\inetpub\wwwroot\Snipe-IT\vendor\barryvdh\laravel-cors\src\HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #76 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle() #77 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #78 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then() #79 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #80 C:\inetpub\wwwroot\Snipe-IT\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle() #81 {main} Backup failed because: The dump process failed with exitcode 1 : General error : .
`

**Comment by snipe** [comment]
This is one we've seen before, but have a hard time reproducing, since we're not a windows shop. I *believe* this is due to permissions. Since it works via Powershell but not via web UI (which typically run as different users), it usually means the permissions on the storage directory and/or the temp directory can't be written to via whatever user the web is running as. (This behavior changed a bit in later versions of IIS, where they introduced application pools - our docs there are a little outdated, but we're working on filling those out more.)

The web UI really only invokes the command line script, so permissions seems like the most obvious culprit.

**Comment by WELLBOREIS** [comment]
@snipe That makes a lot of sense. I'll check it out!

**Comment by snipe** [comment]
@WELLBOREIS this *might* be helpful to you (again, we're not a windows shop, so this is probably stuff you already know)

https://laracasts.com/discuss/channels/servers/laravel-permissions-on-iis-server

The storage directory (and all subdirectories) should be writable by whatever user the web server runs as, and probably the general temp directory as well.


<blockquote><img src="/favicons/favicon.ico" width="48" align="right"><div><img src="/favicons/favicon-16x16.png" height="14"> Laracasts</div><div><strong><a href="https://laracasts.com/discuss/channels/servers/laravel-permissions-on-iis-server">Laravel permissions on IIS server</a></strong></div><div>I built a laravel app for a client but he wants to host it on his own server which is a Windows Server 2008. I followed all the tutorials I found on g...</div></blockquote>

**Comment by WELLBOREIS** [comment]
@snipe We’re now thinking of having a second instance of Snipe-IT on a Linux VM. What flavor do you recommend?

**Comment by snipe** [comment]
Honestly, whatever flavor you are most comfortable with. We have folks running this on raspberry pi, so it works almost anywhere. 

Linux is easier for us to support, just because we know it better, but most flavors are kind of similar. So whatever floats your boat.

**Comment by snipe** [comment]
(If you’re looking for something more specific tho, Ubuntu, CentOS, and Debian are super common and we know them very well)

**Comment by WELLBOREIS** [comment]
@snipe I migrated to CentOS today and am no longer having backup issues. Thanks for your help!
