### ISSUE TITLE
PDF files attached do not open as PDF

### ISSUE THREAD

**Issue by PauloFreire70** [grokability/snipe-it#8566]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Existing PDF's in the licenses do not open as a recognized file, instead they show as ascii 

**To Reproduce**
1. Go to 'Licenses'
2. Click on any existing item with an attached PDF
3. Click on File Uploads and click on any existing PDF file
Or go to https://demo.snipeitapp.com/licenses/4 click on File Upload and open the existing PDF file I've added.

**Expected behavior**
Open the file

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.0 build 4484 
 - OS: Windows Server 2012
 - Web Server: IIS
 - PHP Version: 7.3.14

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Firefox/Chrome/Edge

**Error Messages**
no error, the issue also exists on https://demo.snipeitapp.com/licenses/4#uploads > just try to open a PDF file and it will not open as PDF. I've added in this license a test PDF file.

**Comment by snipe** [comment]
@PauloFreire70 - thanks so much for raising this issue. I can definitely reproduce this on the demo and locally. I honestly have no idea why this would be a thing, as I don't think we changed much there, but we'll figure it out. Hold tight please and we'll have a fix out shortly.

**Comment by snipe** [comment]
@PauloFreire70 - got it - I'll push to develop shortly.
