### ISSUE TITLE
Custom asset report requires model to be selected [v5.0.0]

### ISSUE THREAD

**Issue by fashberg** [grokability/snipe-it#8567]
Hi!

When using Custom Asset Report after clicking "Generate" the Message "Please select an item in the list" appears next to the optional (?) Model-SelectBox.

It's not possible to export all assets.

Tested at 5.0.0 and current develop-branch  https://develop.snipeitapp.com/reports/custom

If i select any asset and change the value of the selected item in browser-webdebugger (F12) then i will get all assets (not only that model). So it seems to be a frontend bug

![2020-10-21_19h45_15](https://user-images.githubusercontent.com/3075214/96758786-811d2780-13d7-11eb-8493-1a41411e0556.png)

Kind Regards
Folke

**Comment by snipe** [comment]
Yep, you're 100% right - we've just pushed out a fix, and it will be in a new point release shortly. Thanks!
