### ISSUE TITLE
download file  

### ISSUE THREAD

**Issue by linux-ops** [grokability/snipe-it#8569]
![image](https://user-images.githubusercontent.com/6948476/96821540-b159da00-145a-11eb-9cd2-cc69a561f157.png)

![image](https://user-images.githubusercontent.com/6948476/96821575-ccc4e500-145a-11eb-815b-9fc164aa8909.png)

**Comment by linux-ops** [comment]
Version:5

OS: Linux Centos7

TYPE: NEW INSTALL

**Comment by snipe** [comment]
Already fixed in 5.0.1 AFAIK
