### ISSUE TITLE
"Whoops, looks like something went wrong." after upgrade to v5

### ISSUE THREAD

**Issue by xylcro** [grokability/snipe-it#8571]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading to v5.0.1, when clearing chache en refreshing the page, I get an error "Whoops, looks like something went wrong." with nothing else. (before turning on debug)

**To Reproduce**
1. upgrade to v5.0.X
2. clear cache
3. refresh page

**Expected behavior**
upgrade to v5 to be successful

**Screenshots**
[https://imgur.com/a/P9MsjTh](https://imgur.com/a/P9MsjTh)

**Server (please complete the following information):**
 - Snipe-IT Version: from 4.9.5 to 5.0.1
 - OS: Ubuntu 20.04
 - Web Server: Apache
 - PHP Version:  7.3.23

**Desktop (please complete the following information):**
 - OS: Windows 10, 20H1
 - Browser: Edge, Chrome, Opera, Firefox
 - Version 86.0.622.48, 86.0.4240.111, 71.0.3770.284, 81.0.2

**Smartphone (please complete the following information):**
/

**Error Messages**
[https://imgur.com/a/RPkR0JP](https://imgur.com/a/RPkR0JP)

```
(1/1) FatalThrowableErrorCall to undefined method Laravel\Passport\Passport::withCookieSerialization()
--
in AuthServiceProvider.php line 92
at AuthServiceProvider->boot()
at call_user_func_array(array(object(AuthServiceProvider), 'boot'), array())in BoundMethod.php line 29
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php line 87
at BoundMethod::callBoundMethod(object(Application), array(object(AuthServiceProvider), 'boot'), object(Closure))in BoundMethod.php line 31
at BoundMethod::call(object(Application), array(object(AuthServiceProvider), 'boot'), array(), null)in Container.php line 549
at Container->call(array(object(AuthServiceProvider), 'boot'))in Application.php line 792
at Application->bootProvider(object(AuthServiceProvider))in Application.php line 775
at Application->Illuminate\Foundation\{closure}(object(AuthServiceProvider), 27)
at array_walk(array(object(EventServiceProvider), object(LogServiceProvider), object(RoutingServiceProvider), object(AuthServiceProvider), object(CookieServiceProvider), object(DatabaseServiceProvider), object(EncryptionServiceProvider), object(FilesystemServiceProvider), object(FormRequestServiceProvider), object(FoundationServiceProvider), object(NotificationServiceProvider), object(PaginationServiceProvider), object(SessionServiceProvider), object(ViewServiceProvider), object(ServiceProvider), object(ServiceProvider), object(ServiceProvider), object(TrustedProxyServiceProvider), object(ImageServiceProvider), object(PassportServiceProvider), object(ServiceProvider), object(ServiceProvider), object(PasswordStrengthServiceProvider), object(BackupServiceProvider), object(ZiggyServiceProvider), object(DumbPasswordServiceProvider), object(AppServiceProvider), object(AuthServiceProvider), object(EventServiceProvider), object(RouteServiceProvider), object(SettingsServiceProvider), object(ValidationServiceProvider), object(MacroServiceProvider), object(LdapServiceProvider), object(SamlServiceProvider), object(MailServiceProvider), object(QueueServiceProvider), object(TranslationServiceProvider), object(ValidationServiceProvider), object(HashServiceProvider)), object(Closure))in Application.php line 776
at Application->boot()in BootProviders.php line 17
at BootProviders->bootstrap(object(Application))in Application.php line 213
at Application->bootstrapWith(array('Illuminate\\Foundation\\Bootstrap\\LoadEnvironmentVariables', 'Illuminate\\Foundation\\Bootstrap\\LoadConfiguration', 'Illuminate\\Foundation\\Bootstrap\\HandleExceptions', 'Illuminate\\Foundation\\Bootstrap\\RegisterFacades', 'Illuminate\\Foundation\\Bootstrap\\RegisterProviders', 'Illuminate\\Foundation\\Bootstrap\\BootProviders'))in Kernel.php line 162
at Kernel->bootstrap()in Kernel.php line 146
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58
```

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.: no
- [https://pastebin.com/aPHS1wLe](https://pastebin.com/aPHS1wLe)

**Additional context**
- Is this a fresh install or an upgrade? : upgrade
- What OS and web server you're running Snipe-IT on: Ubuntu 20.04, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
You’re most likely missing some new PHP extension requirements. I know it’s a bad/unhelpful error message. Unfortunately we can’t do a lot about that. Try running composer install again and watch the output. You might need to install PHP-ldap or PHP-bcmath.

**Comment by xylcro** [comment]
After installing php-ldap and php-bcmath, running composer install again, all is working again. 
Thanks!
