### ISSUE TITLE
Can't check-in a specific asset for a user  

### ISSUE THREAD

**Issue by LEOkonami** [grokability/snipe-it#8575]
#### Please confirm you have done the following before posting your bug report:

- [YES ] I have enabled debug mode 
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I get an error while trying to check-in a specific asset (monitor) for one of my users

**To Reproduce**
1. Go to a user asset list
2. Choose asset 00063
3. Click on actions and choose checkin
4. Choose the status "deployed"
5. Get an error " Error: Asset was not checked in, please try again" 

**Expected behavior**
To be able to check in this asset

**Server (please complete the following information):**
 - Snipe-IT Version: 5.01
 - OS: Ubuntu 16.04.1
 - Web Server: [e.g. Apache, IIS]
 - PHP Version. 7.3.23-4

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome 
 - Version: Version 86.0.4240.75

**Error Messages**
- can't see any errors on the debug mode only this error " Error: Asset was not checked in, please try again"

**Additional context**
-Upgrade version from 4.9?

**Comment by snipe** [comment]
@inietov can you take a look at this?

**Comment by snipe** [comment]
@LEOkonami can you tell me what you have your minimum password length set to in your Admin > Settings > Security?

**Comment by LEOkonami** [comment]
> @inietov can you take a look at this?

It seems I found a workaround... I was playing around and I edit this asset but didn't chance anything amd saved... After that I could checkin the asset 🤔... Not sure what was the issue there...
Amd the minimum is 6

**Comment by inietov** [comment]
@LEOkonami Hey, thanks for let us know. I was dabbing at this issue and I try to checkin different assets in my installation of Snipe-IT and everything looks good in my end.

I'm concious that "system's haunted" is not an acceptable answer here, so if you find this behaviour some other time please let us know with more info about the asset (if you can share it, obviously), because this looks like something was funky about the asset you were trying to checkin and when you falsely edited it, the asset gets somehow "normalized". Have a great day!!

**Comment by snipe** [comment]
When I've seen this before, it usually means some data got a little funky somewhere, for example if the user the asset is assigned to was deleted.

**Comment by cslob** [comment]
I had the same error. It turned out the default location the device was assigned to no longer existed. I edited the asset, removed the default location (which was a blank text box with an x to delete it) and it worked.

**Comment by LEOkonami** [comment]
> @LEOkonami Hey, thanks for let us know. I was dabbing at this issue and I try to checkin different assets in my installation of Snipe-IT and everything looks good in my end.
> 
> I'm concious that "system's haunted" is not an acceptable answer here, so if you find this behaviour some other time please let us know with more info about the asset (if you can share it, obviously), because this looks like something was funky about the asset you were trying to checkin and when you falsely edited it, the asset gets somehow "normalized". Have a great day!!

I will... If I have the same issues again will contact you!

@snipe This asset was assigned to a deleted user but a long time ago, I check it out again for a user in the system.

@cslob Thanks I will check this next time I have this issue.

Love Snipe-it makes my job a lot easier, thanks! 
P.S
And thanks for the multiple asset crafting

**Comment by inietov** [comment]
I'm going to close this as is not helping with (not really) my TOC. As I said previously, of course, feel free to reopen or create a new issue if this happens again. Good day!!
