### ISSUE TITLE
Expiring notification - class not found (5.0.1)

### ISSUE THREAD

**Issue by Diniver** [grokability/snipe-it#8576]
Hi all, 
Good job to everyone bringing 5.0.1 live!

I have an issue with notification. When I run _php artisan snipeit:expiring-alerts_ I get:

![image](https://user-images.githubusercontent.com/31882138/96844269-36d38f00-1447-11eb-8f25-d7d1cb240aed.png)

Server: Ubuntu 20.04.1
Snipe-IT version: v5.0.1 build 5383 (g870b097f0) 
PHP:  7.4.3

**Comment by snipe** [comment]
> Good job to everyone bringing 5.0.1 live!

Thanks! It was a slog, but we got there :D 

> I have an issue with notification. When I run php artisan snipeit:expiring-alerts I get:

Hmm... That one hasn't even changed since v4 and I can't reproduce it locally. We *shouldn't* need a `use` statement there, since it's actually a trait that we put on the model itself (`use Notifiable`). 

Maybe it'a a PHP version issue? I don't know that we tested above 7.4

**Comment by Diniver** [comment]
Thanks for fast response considering that you have so many tickets.

I have downgrade php to:
![image](https://user-images.githubusercontent.com/31882138/96976184-6c45ae80-1513-11eb-91e7-2a9b5f886613.png)

and bumped the SnipeIT version to 5.0.2. Unfortunately the issue still remains. I thought I have might missed a _php_ extension but it looks like everything needed is here:
`mysqlnd, opcache, pdo, xml, bcmath, calendar, ctype, curl, dom, exif, fileinfo, ftp, gd, gettext, iconv, json, ldap, mbstring, mysqli, pdo_mysql, phar, posix, readline, shmop, simplexml, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip `

If you are still not able to reproduce it, I guess I will bring back a backup before I went to ubuntu server 20.04.1.

**Comment by snipe** [comment]
Can you try something for me? 

In `app/Console/SendExpirationAlerts.php`, can you change 

```
Notification::send($recipients, new ExpiringAssetsNotification($assets, $threshold));
```

to

```
\Notification::send($recipients, new ExpiringAssetsNotification($assets, $threshold));
```

and 

```
Notification::send($recipients, new ExpiringLicenseNotification($licenses, $threshold));
```

to

```
\Notification::send($recipients, new ExpiringLicenseNotification($licenses, $threshold));
```

(Basically just add a leading slash to those two notification calls.

Let me know if that helps.

**Comment by Diniver** [comment]
These slashes fixed the issue!

Now, I found another issue after I have received email notification:
![image](https://user-images.githubusercontent.com/31882138/97001315-13d0da00-1530-11eb-9ca9-c9c9c36f35fa.png)

Email tables look a bit broken but it is not that big deal. It is still readable.

Feel free to close the issue and thanks for your support!

**Comment by snipe** [comment]
Which command are you seeing the weird table in?

**Comment by Diniver** [comment]
It is from the email I receive once I use `php artisan snipeit:expiring-alerts`

**Comment by snipe** [comment]
Hm, okay, let me take a look. I don't see anything funny in the markdown there.

**Comment by snipe** [comment]
<img width="574" alt="Screen Shot 2020-10-23 at 5 34 39 AM" src="https://user-images.githubusercontent.com/197404/97004155-78b90f80-14f1-11eb-9d72-e01a77310583.png">

I can reproduce this as well :( I re-generated the vendors from Laravel but it didn't seem to fix anything.

Looks like it might be a Laravel bug in early versions of Laravel v6?
https://github.com/laravel/framework/issues/31065

Sigh.

**Comment by Diniver** [comment]
Thanks for checking. It is not a blocker, I can wait to be patched.

**Comment by snipe** [comment]
Folks will definitely complain about it though - better if I can figure out if there's a workaround short of upgrading Laravel

**Comment by snipe** [comment]
This is getting even weirder.... It seems like it breaks if there are more than 3 columns in the table. WTF.
