### ISSUE TITLE
V5 - Finding -> wrong setting leads to errors!

### ISSUE THREAD

**Issue by GustelDE** [grokability/snipe-it#8578]
Hi, I tested the V5-versions last night excessively, because there were always Errors "Check the form below".
On all(!!!) pages of the settings menu!

I found that this setting triggers this behaviour:
![01](https://user-images.githubusercontent.com/26502186/96847441-799b6400-1453-11eb-9d0b-fd0946d227b3.jpg)
With V4.x this was set to 5 (it written below, minimum is 5). Everything worked.

With V5.x, the value must be 8 (or greater)!!!
![02](https://user-images.githubusercontent.com/26502186/96848789-275b4280-1455-11eb-9372-ef1bab71f4dd.jpg)

With "5" nothing worked, copied Assets showed the wrong Asset-ID, settings were unsaveable due to errors...
Setting this to "8" solved almost all errors!

Almost because I found the my images still dont show up. There was no error, but as well no pictures.
I investigated further and found, that in my "config.env" there was this entry (it worked with V4 flawlessly!!):
**APP_URL=http://127.0.0.1:80**
When I chaneged this to the real IP of the machine, the images showed up:
**APP_URL=http://10.10.0.14:80**
The problem is now, that clients from VLANs that connect via anoher NIC (the server has multiple-NICs) cannot see images. Lets say a user connects to 10.10.4.14 (same machine, other VLAN), no images show up, because they point to the wrong IP. Have you a solution for this?

Edit: Found the solution regarding the APP_URL and images. Simply **comment** this in the config.env **out**:
#APP_URL=http://127.0.0.1:80
Then it will show always the right IP (URL) for the VLAN/NIC which calls the image.

I wanted to share my finding :)

Regards

**Comment by snipe** [comment]
Nice sleuthing! I've updated the release notes to reflect that the password minimum should be updated to 8 or greater:

> If your minimum password setting in Admin > Settings was previously less than 8, you should update this to 8 or greater before upgrading. Failure to update this may cause other settings to fail on saving.
