### ISSUE TITLE
500 | Server Error

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#8583]
#### Please confirm you have done the following before posting your bug report:

**Describe the bug**
When checking out equipment. Equipment is checked out but receive a 500 | server error. (Error: That asset is not available for checkout!)

I also receive this issue when attempting to update email, label and favicon logos.

**To Reproduce**
Normal process to check out a single item

**Expected behavior**
No error upon checkout. Equipment is checked out.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: 5.0.1
 - OS: [e.g. Ubuntu, CentOS] Server 2012  R2
 - Web Server: [e.g. Apache, IIS] WAMP Server 3.2.3
 - PHP Version tried 7.1.33 and 7.2.33

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 X64, version 2004 OS build 19041.572
 - Browser [e.g. chrome, safari] Same error on Firefox and Chrome
 - Version [e.g. 22] latest

![image](https://user-images.githubusercontent.com/31219479/96893073-8c0fa080-1447-11eb-8c9b-e3bb36defeb9.png)

![image](https://user-images.githubusercontent.com/31219479/96893114-99c52600-1447-11eb-9634-61eb4955a0c1.png)

**Comment by SmithD3** [comment]
Try running `php upgrade.php` from https://snipe-it.readme.io/docs/upgrading . That fixed many of the random 500 errors we received. If you are running in Docker and it complains about root, `su` to the user that owns the files to where ever the console defaults you to. 

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div>Always backup your database and configuration files before upgrading. We try very hard to make sure that all database changes are non-destructive, but you should always backup beforehand anyway. You will never regret backing up your database. You may regret not doing so, so it’s just better to get i...</div></blockquote>

**Comment by jmartins1** [comment]
Thanks SmithD3 that resolved the error 500 issue.
