### ISSUE TITLE
Requested Assets Blank - 5.0

### ISSUE THREAD

**Issue by dborko95** [grokability/snipe-it#8585]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

When a user requests an asset it shows up under requested assets tab for 1 second then goes blank and says it is showing rows 1 to 4 of 4 even though it is empty. This same message appears on the snipe-it demo server that it is showing items 1 to 4 of 4 even though it is blank and there was a lot of items set as requested on the demo server.

**To Reproduce**

1. Go to 'Requestable'
2. Click on 'Request' on any asset to request one
3. Go to 'Requested' under assets tab
4. It very quickly loads requests then goes blank

**Expected behavior**

When we view requested assets it should show a list of people that have requested items but it flashes the expected list and the shows an empty list while stating 4 rows are being shown (this is also happening in the demo)

**Screenshots**

Our production server

clicking requested under the assets tab
![image](https://user-images.githubusercontent.com/73298902/96896093-1f9e9c80-145b-11eb-9e42-a920f29c3c06.png)

1 second later under the requested assets tab
![image](https://user-images.githubusercontent.com/73298902/96896185-35ac5d00-145b-11eb-8695-50b9cc2ccfc4.png)

Snipe-IT's demo server

clicking requested under the assets tab
![image](https://user-images.githubusercontent.com/73298902/96896381-6db3a000-145b-11eb-85a9-d039691cfc26.png)

1 second later under the requested assets tab
![image](https://user-images.githubusercontent.com/73298902/96896468-87ed7e00-145b-11eb-863d-4014bf582acc.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.0
 - OS: [Ubuntu 18.04]
 - Web Server: [Apache]
 - PHP Version 7.4

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome, firefox]
 - Version [86]

**Error Messages**

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console. None

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - **YES IT IS - Exactly what is happening to me and my other admins**

- Include any additional information you can find in `storage/logs` and your webserver's logs.

**/var/www/html/snipeit/storage/logs/laravel.log**

[2020-10-22 00:00:30] production.ERROR: Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command
" {"exception":"[object] (Swift_TransportException(code: 503): Expected response code 354 but got code \"503\", with message \"503 5.5.2 Need rcpt command
\" at /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457)
[stacktrace]
#0 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode()
#1 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand()
#2 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(390): Swift_Transport_EsmtpTransport->executeCommand()
#3 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(497): Swift_Transport_AbstractSmtpTransport->doDataCommand()
#4 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(516): Swift_Transport_AbstractSmtpTransport->doMailTransaction()
#5 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo()
#6 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(486): Swift_Mailer->send()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(261): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(65): Illuminate\\Mail\\Mailer->send()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(146): Illuminate\\Notifications\\Channels\\MailChannel->send()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(105): Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(107): Illuminate\\Notifications\\NotificationSender->withLocale()
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow()
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send()
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send()
#17 /var/www/snipeit/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\\Backup\\Notifications\\Notifiable->notify()
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(369): Spatie\\Backup\\Notifications\\EventHandler->Spatie\\Backup\\Notifications\\{closure}()
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(477): Illuminate\\Events\\Dispatcher->dispatch()
#21 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/CleanupCommand.php(47): event()
#22 [internal function]: Spatie\\Backup\\Commands\\CleanupCommand->handle()
#23 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#24 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#29 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#30 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#31 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\\Console\\Command->run()
#32 /var/www/snipeit/vendor/symfony/console/Application.php(1001): Spatie\\Backup\\Commands\\BaseCommand->run()
#33 /var/www/snipeit/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand()
#34 /var/www/snipeit/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun()
#35 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#36 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#37 /var/www/snipeit/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#38 {main}
"}

**/var/log/apache2/error.log**

None

**/var/log/apache2/other_vhosts_access.log**

equipment.oursnipeitserver.com:80 x.x.x.83 - - [22/Oct/2020:11:37:26 -0400] "GET /hardware/requested HTTP/1.1" 200 24866 "http://equipment.oursnipeitserver.com:444/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
equipment.oursnipeitserver.com:80 x.x.x.83 - - [22/Oct/2020:11:37:26 -0400] "GET /api/v1/consumables?search= HTTP/1.1" 200 4114 "equipment.oursnipeitserver.com:444/hardware/requested" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
equipment.oursnipeitserver.com:80 x.x.x.83 - - [22/Oct/2020:11:37:26 -0400] "GET /hardware/requested HTTP/1.1" 200 24866 "equipment.oursnipeitserver.com:444/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
equipment.oursnipeitserver.com:80 x.x.x.83 - - [22/Oct/2020:11:37:26 -0400] "GET /api/v1/consumables?search= HTTP/1.1" 200 4115 "http://equipment.oursnipeitserver.com:444/hardware/requested" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
equipment.oursnipeitserver.com:80 x.x.x.83 - - [22/Oct/2020:11:37:27 -0400] "GET /api/v1/consumables?search= HTTP/1.1" 200 4114 "http://equipment.oursnipeitserver.com:444/hardware/requested" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

note: x.x.x.83 is my computers IP Address. I do notice it looks to be going to requested and then pull and api for consumables immediately, not sure if this helps but hopefully it does!

  
**Additional context**
- Is this a fresh install or an upgrade?  Upgrade from 4.9.5

- What OS and web server you're running Snipe-IT on - 18.04 Ubuntu

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh

- Indicate whether or not you've manually edited any data directly in the database - No, Just queried it to check

**Comment by snipe** [comment]
This is now fixed on master
