### ISSUE TITLE
api/v1/companies Failed to load resource: the server responded with a status of 401 (Unauthorized)

### ISSUE THREAD

**Issue by SaranyaTest17** [grokability/snipe-it#8587]
I am getting 401 error while calling this API , I have changed the permission in  apache config , but still not working ,where will be the issue ?

I am using Windows 10 , Wamp Server ,  PHP 7.3

**Comment by snipe** [comment]
> I have changed the permission in apache config , but still not working ,where will be the issue ?

I'm not sure what you mean here? 

Are you authenticating with the API via Bearer token in that call?

**Comment by SaranyaTest17** [comment]
I am not using bearer token ,i am not calling from mobile app.I am using as web application only. I just downloaded the code from github and using it. I tried to configure with MAC OS, it was working perfectly . But in windows its creating problem.

I have done based on the instructions given here https://snipe-it.readme.io/v4.0/docs/pre-flight-setup,https://snipe-it.readme.io/v4.0/docs/wamp 

I am using Windows 10 , Wamp Server , PHP 7.3

All the configuration done in htttp.conf file. Login , Creating new Companies working - i mean post . But get API is not working,
After creating company,it is inserting records in database but not listing the companies data. 

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/v4.0/docs/pre-flight-setup,https://snipe-it.readme.io/v4.0/docs/wamp">Snipe-IT Documentation</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>

**Comment by SaranyaTest17** [comment]
Any one got this issue ?

**Comment by dsnefnse** [comment]
**EDIT: Fixed. I reinstalled using the github method in a new folder rather than downloading the archive, ran update.php, copied env file, reinstall composer, regenerated key and restarted services.**

Yes we are also getting this issue. Can enter records in the forms, add companies, users etc. that are saved into the DB but we get error 401 unauthorized in the inspect console and nothing displays in the web app list '**No matching records found**' and no errors in the log (which is pretty rubbish anyway)

Snipe-IT 5.0.4
Win Server 2019
WAMP 3.2.0
PHP 7.4.9

**Comment by saranyalekshmanan** [comment]
@snipe  Can you please explain why I am getting this issue ? I have configured the same in both Ubunthu and Windows. Still I am getting that issue ? Am is missing anything to configure ?

**Comment by snipe** [comment]
This is going to be a bit of a cut and paste job, so forgive me if I reference the this ticket in the list. Sorry, just still trying to get as much info as I can. This was first (I believe) reported in #8458.

Thanks for reporting this, folks. As has been discussed in other tickets (specifically #8458 but probably also #8644, #8587, and #8650), this seems like it *must* be an environmental issue, as we've been unable to reproduce this on *any* of our hosted customers. 

Some folks have found that running `php upgrade.php` worked for them, which means something didn't get cleared or run that the `upgrade.php` script clears or runs for you. https://github.com/snipe/snipe-it/issues/8458#issuecomment-723416695

Other folks have found that they were missing some of the required extensions: https://github.com/snipe/snipe-it/issues/8458#issuecomment-723856070
https://snipe-it.readme.io/docs/requirements#general-system-requirements

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/requirements#general-system-requirements">Requirements</a></strong></div><div>The requirements for Snipe-IT are fairly standard for a modern web server, and most servers will have most or all of these components already installed. If for some reason you don't have them installed, they are relatively easy to add.      </div></blockquote>

**Comment by snipe** [comment]
Please also see my summary here: https://github.com/snipe/snipe-it/issues/8458#issuecomment-724443005
