### ISSUE TITLE
Unable to Accept Assets 

### ISSUE THREAD

**Issue by itscsquared** [grokability/snipe-it#8589]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Email is generated from Snipe to the user the asset is being checked out to. Clicked the link, and the page loads to accept the asset. However, when clicking confirm, I get an error page stating it is unable to locate the mix file. When the debug mode is turned off, the error is just a basic 500 server error.

**To Reproduce**

**Expected behavior**
Asset should be accepted and user receiving a confirmation message stating that fact.

**Screenshots**
![image](https://user-images.githubusercontent.com/51164364/96911827-5f6f7f00-146f-11eb-84ec-9bb36b9cde6b.png)

![image](https://user-images.githubusercontent.com/51164364/96912156-e4f32f00-146f-11eb-92b2-59bdab34fbbe.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.1
 - OS: [e.g. Ubuntu, CentOS] Windows Server 2016 Data Center
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.4.1

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by itscsquared** [comment]
That error went away, but am still receiving another one stating there is an undefined variable: sig_filename. With debug turned off it still returns a 500 server error. Attached is a screenshot of the error.

![image](https://user-images.githubusercontent.com/51164364/97000779-3ac5e680-1505-11eb-9ca6-225abe0bc46e.png)
 
And I did update to 5.0.2 as well and ran the handy commands after upgrading.

**Comment by snipe** [comment]
Which screen are you seeing this on? I was able to sign for and accept an asset without any issues. Did this get triggered on acceptance where the signature is required, or no?

**Comment by itscsquared** [comment]
After I select the radio button to accept and click 'submit,' that is when the error is triggered.

**Comment by snipe** [comment]
Did this get triggered on acceptance where a signature is required, or no?

**Comment by itscsquared** [comment]
No, no signature required.

**Comment by Pikok89** [comment]
I was able to replicate this issue on v 5.0.2
My installation doesn't require signature when accepting assets.

After making the use of a signature required I was able to accept the asset without any errors.
Disabling the feature again causes the error to reappear.

![image](https://user-images.githubusercontent.com/73346817/97008081-a7aba180-1542-11eb-9e03-5ecc742c2fbf.png)

**Comment by snipe** [comment]
Yeah its already fixed on develop
