### ISSUE TITLE
Cleaning up the backups of Snipe-IT failed v5.0.0 & v5.0.1

### ISSUE THREAD

**Issue by denzfarid** [grokability/snipe-it#8595]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I h ave read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Hi, I would like to report some clean backup features which previously worked on version 4.x but after upgrading to version 5.x, the feature failed.

here is the php that I use
```
php --version
PHP 7.4.9 (cli) (built: Aug 7 2020 14:30:01) (NTS)
```

I upgraded the version using 
```php upgrade.php```

I've done a vendor reinstall by removing the vendor folder and running
```COMPOSER_CACHE_DIR=/dev/null composer install --no-dev```

**To Reproduce**

1. Running on crontab ( scheduler ) 
2. Running manuall command ```php artisan backup:clean```

**Expected behavior**
I hope the feature will work again

**Screenshots**
**_Before upgrade to version 5_**

<img width="514" alt="gambar" src="https://user-images.githubusercontent.com/1294403/96966764-a2e1f000-1538-11eb-91e2-bf7a5e682ed8.png">

**_After upgrade to V5.0.0 and V5.0.1_**

<img width="529" alt="gambar" src="https://user-images.githubusercontent.com/1294403/96966830-bc833780-1538-11eb-952f-d122403726f7.png">

**this message when manual command**

<img width="620" alt="gambar" src="https://user-images.githubusercontent.com/1294403/96967084-200d6500-1539-11eb-8bca-7b304e831537.png">

But if i delete manual from admin panel is successfull
<img width="399" alt="gambar" src="https://user-images.githubusercontent.com/1294403/96970335-b9d71100-153d-11eb-9ad8-c2cf871a20e3.png">

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.0 & v5.0.1 
<img width="425" alt="gambar" src="https://user-images.githubusercontent.com/1294403/96967752-2cde8880-153a-11eb-9615-960f85d2bba6.png">

 - OS: Ubuntu 20.04.1 LTS
 - Web Server: Apache/2.4.41 (Ubuntu)
 - PHP Version : PHP 7.4.9

**Error Messages**
```
 An error occurred while cleaning up the backups of Snipe-IT

Exception message: Trying to access array offset on value of type null

Exception trace: #0 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php(47): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() #1 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php(22): Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy->calculateDateRanges() #2 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(42): Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy->deleteOldBackups() #3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(176): Spatie\Backup\Tasks\Cleanup\CleanupJob->Spatie\Backup\Tasks\Cleanup\{closure}() #4 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(54): Illuminate\Support\Collection->each() #5 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/CleanupCommand.php(42): Spatie\Backup\Tasks\Cleanup\CleanupJob->run() #6 [internal function]: Spatie\Backup\Commands\CleanupCommand->handle() #7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array() #8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure() #10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod() #11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call() #12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call() #13 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute() #14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run() #15 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run() #16 /var/www/snipeit/vendor/symfony/console/Application.php(1001): Spatie\Backup\Commands\BaseCommand->run() #17 /var/www/snipeit/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand() #18 /var/www/snipeit/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun() #19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run() #20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run() #21 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle() #22 {main} 
```

_**### I am very grateful, to the entire team and contributors who have worked to make this happen**_

**Comment by snipe** [comment]
Hi @denzfarid - thanks for raising this issue. I'm unfortunately unable to reproduce this locally :( 

<img width="666" alt="Screen Shot 2020-10-23 at 12 54 21 AM" src="https://user-images.githubusercontent.com/197404/96971688-5364db00-14ca-11eb-977e-bd3f21ead837.png">

Have you tried clearing your config cache? It looks like some stuff changed between versions of the backup package we used.

https://github.com/spatie/laravel-backup/issues/1047

(You shouldn't need to republish the config file, as they mention in that post, since we publish those for you.)

**Comment by snipe** [comment]
Also make sure you've got the following in your .env:

```
PRIVATE_FILESYSTEM_DISK=local
PUBLIC_FILESYSTEM_DISK=local_public
```

(And clear your config cache again)

It *should* fall back gracefully to those settings even if you don't specify them, but it's worth a shot.

**Comment by denzfarid** [comment]
> Also make sure you've got the following in your .env:
> 
> ```
> PRIVATE_FILESYSTEM_DISK=local
> PUBLIC_FILESYSTEM_DISK=local_public
> ```
> 
> (And clear your config cache again)
> 
> It _should_ fall back gracefully to those settings even if you don't specify them, but it's worth a shot.

I really appreciate @snipe , for taking the time to answer this ticket, on .env I have added the enviroment, but it's still the same, failed to clean up

<img width="645" alt="gambar" src="https://user-images.githubusercontent.com/1294403/96995077-d1bb8e80-1557-11eb-94a9-b6cd395d93e6.png">

-----------

> Hi @denzfarid - thanks for raising this issue. I'm unfortunately unable to reproduce this locally :(
> 
> <img alt="Screen Shot 2020-10-23 at 12 54 21 AM" width="666" src="https://user-images.githubusercontent.com/197404/96971688-5364db00-14ca-11eb-977e-bd3f21ead837.png">
> 
> Have you tried clearing your config cache? It looks like some stuff changed between versions of the backup package we used.
> 
> [spatie/laravel-backup#1047](https://github.com/spatie/laravel-backup/issues/1047)
> 
> (You shouldn't need to republish the config file, as they mention in that post, since we publish those for you.)

maybe it has a problem with the php7.4 version that I am using :)

**Comment by snipe** [comment]
Maaaaaybe, but that Spatie ticket I linked you to did mention that their stuff should work with PHP 7.4...

**Comment by snipe** [comment]
I'll check the Spatie library version tomorrow and see if maybe that's it. (It's 4AM here and I need to crash soon.)

**Comment by mntsupport** [comment]
Curious if anyone found a solution for this?

I'm also getting an error after upgrading to 5.0.4

`An error occurred while cleaning up the backups of Snipe-IT 
Exception message: Trying to access array offset on value of type null 
Exception trace: #0 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php(47): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() #1 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php(22): Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy->calculateDateRanges() #2 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(42): Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy->deleteOldBackups() #3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(176): Spatie\Backup\Tasks\Cleanup\CleanupJob->Spatie\Backup\Tasks\Cleanup\{closure}() #4 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(54): Illuminate\Support\Collection->each() #5 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/CleanupCommand.php(42): Spatie\Backup\Tasks\Cleanup\CleanupJob->run() #6 [internal function]: Spatie\Backup\Commands\CleanupCommand->handle() #7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array() #8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure() #10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod() #11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call() #12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call() #13 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute() #14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run() #15 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run() #16 /var/www/snipeit/vendor/symfony/console/Application.php(1001): Spatie\Backup\Commands\BaseCommand->run() #17 /var/www/snipeit/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand() #18 /var/www/snipeit/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun() #19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run() #20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run() #21 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle() #22 {main} 
`

I've made sure my .env matches the KB version, and I have also cleared my config with `php artisan config:clear` command.

From what I can see backups still work, just not the backup clean up.

**Comment by denzfarid** [comment]
> Curious if anyone found a solution for this?
> 
> I'm also getting an error after upgrading to 5.0.4
> 
> `An error occurred while cleaning up the backups of Snipe-IT Exception message: Trying to access array offset on value of type null Exception trace: #0 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php(47): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() #1 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php(22): Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy->calculateDateRanges() #2 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(42): Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy->deleteOldBackups() #3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(176): Spatie\Backup\Tasks\Cleanup\CleanupJob->Spatie\Backup\Tasks\Cleanup\{closure}() #4 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(54): Illuminate\Support\Collection->each() #5 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/CleanupCommand.php(42): Spatie\Backup\Tasks\Cleanup\CleanupJob->run() #6 [internal function]: Spatie\Backup\Commands\CleanupCommand->handle() #7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array() #8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure() #10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod() #11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call() #12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call() #13 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute() #14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run() #15 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run() #16 /var/www/snipeit/vendor/symfony/console/Application.php(1001): Spatie\Backup\Commands\BaseCommand->run() #17 /var/www/snipeit/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand() #18 /var/www/snipeit/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun() #19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run() #20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run() #21 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle() #22 {main} `
> 
> I've made sure my .env matches the KB version, and I have also cleared my config with `php artisan config:clear` command.
> 
> From what I can see backups still work, just not the backup clean up.

ticket close with some changes to the config/backup.php file

I see a difference in writing
on the link https://github.com/spatie/laravel-backup/issues/1047#issuecomment-647264286
it explains that currently spatie/laravel-backup uses snake_cased

I made changes to the config/backup.php
and replace with the original file from spatie
https://github.com/spatie/laravel-backup/blob/master/config/backup.php#L201

here are the differences
on spatie
<img width="794" alt="gambar" src="https://user-images.githubusercontent.com/1294403/98015086-002a4b00-1e2f-11eb-879f-13cde0b4da52.png">

and this on snipe-it
https://github.com/snipe/snipe-it/blob/master/config/backup.php#L185
<img width="789" alt="gambar" src="https://user-images.githubusercontent.com/1294403/98015244-264feb00-1e2f-11eb-83b7-b984c8f65aa4.png">

therefore I copied only the sections

https://github.com/spatie/laravel-backup/blob/master/config/backup.php#L201 until
https://github.com/spatie/laravel-backup/blob/master/config/backup.php#L234

and it worked
<img width="477" alt="gambar" src="https://user-images.githubusercontent.com/1294403/98015768-baba4d80-1e2f-11eb-8209-d3d1038f6e6c.png">

@snipe can you replace the same thing in the file? please


<blockquote><img src="https://avatars2.githubusercontent.com/u/7535935?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/spatie/laravel-backup">spatie/laravel-backup</a></strong></div><div>A package to backup your Laravel app. Contribute to spatie/laravel-backup development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>
<blockquote><img src="https://avatars2.githubusercontent.com/u/7535935?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/spatie/laravel-backup">spatie/laravel-backup</a></strong></div><div>A package to backup your Laravel app. Contribute to spatie/laravel-backup development by creating an account on GitHub.</div></blockquote>

**Comment by snipe** [comment]
Thanks for the update!

**Comment by denzfarid** [comment]
> Thanks for the update! 


You're welcome! 🤜🏻🤛🏽

**Comment by mntsupport** [comment]
You are a wizard! I love this platform and I love the community! Thank you all for all that you do!

**Comment by snipe** [comment]
@denzfarid I just pushed out a few changes on `develop` related to this - can you check it out and see if these still work for you?

**Comment by denzfarid** [comment]
> @denzfarid I just pushed out a few changes on `develop` related to this - can you check it out and see if these still work for you?

perfect! @snipe  🤜🏻🤛🏽
thank you for changing the `config/backup.php ` file
<img width="1024" alt="gambar" src="https://user-images.githubusercontent.com/1294403/98059016-a9e1fa00-1e78-11eb-8b25-65e5c059fea2.png">
