### ISSUE TITLE
depreciation report

### ISSUE THREAD

**Issue by IronDragonFly** [grokability/snipe-it#8597]
#### Expected Behavior (or desired behavior if a feature request)

hi there, please may I have guided steps on how to setup depreciation on an asset

-----

#### Actual Behavior

 Warning: You do not currently have any depreciations set up. Please set up at least one depreciation to view the depreciation report.  I get this error when trying to run the depreciations report
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh Install
- Version of Snipe-IT you're running - v4.9.4 build 4437 (g799a93c46)
- Version of PHP you're running - 7.4.1
- Version of MySQL/MariaDB you're running - MySQL
- What OS and web server you're running Snipe-IT on - Server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - depreciation report
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.  - not sure how to fix
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by IronDragonFly** [comment]
Thank you, looking forward to a reply

**Comment by snipe** [comment]
You can set up Depreciations by going to `/depreciations` and setting them up there. From there, assign the new depreciation at the asset model level.

**Comment by IronDragonFly** [comment]
thank you so much, working on my side

**Comment by snipe** [comment]
Great, thanks for checking - I've updated that on develop and master now.

**Comment by snipe** [comment]
Oops - I tagged the wrong issue in that last commit, which had nothing to do with anything here.

Glad you're sorted tho!

**Comment by cookierun22** [comment]
> You can set up Depreciations by going to `/depreciations` and setting them up there. From there, assign the new depreciation at the asset model level.

Hi, I want to know why when I created the depreciation, but it does not appear on this list here? It only appears when I key on the asset model.

![image](https://user-images.githubusercontent.com/115517803/196103277-8ea08a98-5a83-4c27-bf62-629c0d594c4b.png)
