### ISSUE TITLE
LDAP Sync does not work with LDAP Employee Number empty

### ISSUE THREAD

**Issue by derhedwig** [grokability/snipe-it#8602]
- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
"Test LDAP Sync" is not working, when I leave 'LDAP Employee Number' empty. I get the following error:
`Error getting users from LDAP directory, error: ldap_search(): Search: Protocol error`
It was working with the same settings in 4.9.5, But isn't now in 5.0.2. (see below for the settings)

**To Reproduce**
1. Go to '/admin/ldap'
2. Click on 'Test LDAP Syncronization'
3. `Error getting users from LDAP directory, error: ldap_search(): Search: Protocol error`

**Expected behavior**
LDAP Sync should still be working with the same settings after the upgrade to v5.
Or make 'LDAP Employee Number' mandatory.

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.2 - build 5414 (master)
 - OS: Debian 10
 - Web Server: Nginx
 - PHP Version: 7.3.19-1~deb10u1
 - PHP-Ldap installed from Debian: 7.3+69

**Error Messages**
- With debug turned on, i'm getting the following messages:
```
LOG.info: Preparing to test LDAP user login
LOG.info: Preparing to test LDAP bind connection
LOG.info: Testing Bind
LOG.info: Preparing to get sample user set from LDAP directory
LOG.info: Testing LDAP sync
LOG.info: LDAP sync failed
```
- I'm not getting any errors in the snipeit log file.
- So, I'm not seeing a stack trace.
- Also nothing in nginx log or php-fpm log.

**Additional context**
- This is an upgrade from 4.9.5 to 5.0.2
- Debian 10, nginx, php-fpm
- I installed and upgraded using git pull

My ldap server is a freeipa server.
I tried with ldap://ldapserver and ldaps://ldapserver.
Starttls is deactivated (also tried with activated).
Ldap Cert ignore is active.
Ldap Version is blank.
ldapsearch from cli with the same ldap bind is working.
It was working in 4.9.5 with the same settings.
Authentication as user from ldap is still working and I have ldap_pw_sync disabled.

**Comment by derhedwig** [comment]
Of course, the same happens on `users/ldap`: `ldap_search(): Search: Protocol error`

**Comment by SmithD3** [comment]
How do you have the `LDAP Bind Username` ? I had to change mine to `CN=SNIPE_LDAPUSER,OU=XXX,DC=XXXXX,DC=XXX` type of style instead of `SNIPE_LDAPUSER@XXX.XXX`

**Comment by derhedwig** [comment]
Yes, mine is uid=assets,cn=sysaccounts,cn=etc,dc=xxx,dc=xxx,dc=xxx same as before the upgrade and i can do ldapsearch from cli using the same username.

**Comment by derhedwig** [comment]
Found the culprit:
When I put in a value for 'ldap_emp_num', for example 'uid', everything works.
But 'ldap_emp_num' is optional. So please either make 'ldap_emp_num' a mandatory field or change 'getSelectedFields' in app/Services/LdapAd.php

But by the way: Thanks for snipeit!

**Comment by uberbrady** [comment]
The latest master has a fix for the 'protocol error when ldap attributes are blank' problem, for what it's worth.
