### ISSUE TITLE
Cannot drag the field order in fieldset

### ISSUE THREAD

**Issue by cliff-LINKS** [grokability/snipe-it#8609]
#### Please confirm you have done the following before posting your bug report:

- [•] I have enabled debug mode 
- [•] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Since I upgraded to version 5 I can't drag to reorder fields in a fieldset. The drag dots do not react on a click and drag, they are not selectable (1).
I can insert a field in a certain position by the order value, but once added it can not be reordered.

If I add fields by order value, the value does not get incremented. Even if I close and reopen the Custom Fields - Field Set page, the duplicate order values remain. As shown in the screen dump attached, I have several 22-lines (2).

In the UI, the added fields are shown in the correct order as they were added by order value.

**Screenshots**
<img width="1347" alt="Screenshot fieldset reordering" src="https://user-images.githubusercontent.com/53275614/97091183-51218e80-163a-11eb-95ad-237c2447fb46.png">

**Server (please complete the following information):**
 - Snipe-IT Version: 5.0.3
 - OS: macOS 10.13.6
 - Web Server: Apache
 - PHP Version: 7.1.33

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 and 10.15.7
 - Browser: Safari, Firefox and Chrome
 - Version: 14.0, 82 and 86

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: iPadOS 14.0.1 and 14.1
 - Browser: Safari

**Error Messages**
- WITH DEBUG TURNED ON, I don't get a particular error.
- The browser console gives me this error: TypeError: $("#sort tbody").sortable is not a function. (In '$("#sort tbody").sortable({
      helper: fixHelperModified,
      stop: updateIndex
  })', '$("#sort tbody").sortable' is undefined)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
   Yes the demo reacts exactly the same.

**Additional context**
- This a an upgrade from version 4.9.5
- The upgrade was installed by php upgrade.php
- The database was not edited manually

**Comment by mikedowler** [comment]
+1 to this on versions 5.0.0 and 5.0.4.  I noticed the following error in Developer Tools - not sure if it's relevant
![Screenshot 2020-10-29 at 10 57 19](https://user-images.githubusercontent.com/67961/97559752-c217cc00-19d5-11eb-9ccb-70d34596ce92.png)

**Comment by snipe** [comment]
This is now fixed on develop
