### ISSUE TITLE
LDAP sync successfully but cannot login by ldap

### ISSUE THREAD

**Issue by maodahua** [grokability/snipe-it#8621]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
In v5.0.4 I can sync by ldap, but I still login some account by ldap

**To Reproduce**
1. Go to 'login page'
2. Type username and password
3. Click on 'login'
4. Show 'user or password errors(in Chinese)', But password 10000% is right and many times notice wrong the account not forbidden。

**Expected behavior**
domain account can login system after ldap sync

**Screenshots**
![image](https://user-images.githubusercontent.com/11650756/97251798-8947ed80-1843-11eb-9f7e-0c889431f18f.png)

**Server (please complete the following information):**
 - Snipe-IT 5.0.4
 - OS: [ CentOS]
 - Web Server: [Apache]
 - PHP Version 7.2.16

**Desktop (please complete the following information):**
 - OS: [macOS 10.15.7]
 - Browser [safari]
 - Version [14]

**Error Messages**
[10:44:31] LOG.debug: LDAP is enabled.
DEBUGLOG[10:44:31] LOG.debug: Attempting to log user in by LDAP authentication.
DEBUGLOG[10:44:31] LOG.debug: LDAP user login: Unable to validate user credentials!
DEBUGLOG
[10:44:31] LOG.debug: There was an error authenticating the LDAP user: Unable to validate user credentials!
DEBUGLOG
[10:44:31] LOG.debug: Authenticating user against database.
DEBUGLOG
[10:44:31] LOG.debug: Local authentication failed.

**Additional context**
- upgrade from 4.9.5 to V 5.0.x can't login

**Comment by Gowei88** [comment]
@maodahua 你好，我也有一样的问题，请问你解决了吗？
Hello, I have the same problem, have you solved it？

**Comment by maodahua** [comment]
@hssz202pgw Not yet, I'm waiting snipe solve the issue.

**Comment by Gowei88** [comment]
> @hssz202pgw Not yet, I'm waiting snipe solve the issue.

我的环境基本和你一致，web服务器用的nginx，怀疑可能是中文版的原因？

**Comment by maodahua** [comment]
> > @hssz202pgw Not yet, I'm waiting snipe solve the issue.
> 
> 我的环境基本和你一致，web服务器用的nginx，怀疑可能是中文版的原因？

I don't think so. I modify the language to English and nothing helpd. 
As I know, the Chinese is a language pack in code.

**Comment by snipe** [comment]
When possible, please post in English. (It’s okay if you have to use google translate. Bad translations are better than nothing.)

We are unable to reproduce this issue right now. LDAP logins are working as expected on our end. We’re looking into it, but it’s very hard to fix a bug you can’t reproduce :(

**Comment by maodahua** [comment]
> When possible, please post in English. (It’s okay if you have to use google translate. Bad translations are better than nothing.)
> 
> We are unable to reproduce this issue right now. LDAP logins are working as expected on our end. We’re looking into it, but it’s very hard to fix a bug you can’t reproduce :(

I can't find some log to show you even thought I turn on the debug mode.
And It's very easy reproduce in my instance. I just add a user in AD and do ldap sync in system. Everything OK, but the new user can't login. Notice me the username or password error. But username is correct. I reset password and resync, still can not login...

**Comment by maodahua** [comment]
I create a new server and fresh install snipeit on it and config ldap.
I can sync. But the same user cannot login the new system.
example:
User1       can login old system             still can not login new system
User2       can not login old system        still can not login new system

And I found when the first login successfully in new system, The user Note will add "last login from ldap2". when I change ldap setting and resync it dispear.
![image](https://user-images.githubusercontent.com/11650756/97554739-28badb00-1a12-11eb-95b8-40fbc8283496.png)
![image](https://user-images.githubusercontent.com/11650756/97554772-36706080-1a12-11eb-9be5-8601551c46eb.png)
![image](https://user-images.githubusercontent.com/11650756/97554796-3f613200-1a12-11eb-9ee2-28ae40a86357.png)
above is my setting.

**Comment by Chetyre** [comment]
For what it's worth, I'm seeing the same issue with our LDAP accounts.  Noticed initially when we upgraded to 5.0.1 last week and still occurring on 5.0.4.  We are not using active directory but same symptoms.  I run a test sync and it shows a successful connect & bind.  Running an actual sync shows a successful LDAP import.  But when you go to log in with any of the LDAP accounts I receive a "username or password incorrect" message.  Tested this with a few different ldap accounts and these logins were working before we updated to 5.x.

<img width="731" alt="LDAP error" src="https://user-images.githubusercontent.com/6163387/97586574-6abf2f00-19c8-11eb-9c63-4a59141b5f77.png">

edit:  we are also running our server on CentOS, and PHP version 7.2.27 installed.  Ran upgrade.php, I believe our previous version was 4.7.8.

2nd edit:  I think I was able to fix this for now by changing our auth query from uid= to cn=

**Comment by someonept** [comment]
Hi
I have the same problem

![image](https://user-images.githubusercontent.com/65561486/97982834-400c1680-1dcc-11eb-8a56-48803d8dbae4.png)

LDAP Sync works, but i cant login 
Have you solved it？

**Comment by maodahua** [comment]
> Hi
> I have the same problem
> 
> ![image](https://user-images.githubusercontent.com/65561486/97982834-400c1680-1dcc-11eb-8a56-48803d8dbae4.png)
> 
> LDAP Sync works, but i cant login
> Have you solved it？

I have no idea. So I install a old version snipeit and restore the backupdata before the upgrade.

**Comment by firsakura** [comment]
I have same issue here, i can get LDAP synced and imported usere successfully. but when I try to login with one of imported AD accounts, it warns me the username or password is incorrect. Wondering if it's a known bug, or there is a fix already?

**Comment by maodahua** [comment]
> I have same issue here, i can get LDAP synced and imported usere successfully. but when I try to login with one of imported AD accounts, it warns me the username or password is incorrect. Wondering if it's a known bug, or there is a fix already?

V5.0.x have the issus. I can find a fix still now.

**Comment by someonept** [comment]
> > Hi
> > I have the same problem
> > ![image](https://user-images.githubusercontent.com/65561486/97982834-400c1680-1dcc-11eb-8a56-48803d8dbae4.png)
> > LDAP Sync works, but i cant login
> > Have you solved it？
> 
> I have no idea. So I install a old version snipeit and restore the backupdata before the upgrade.

ok, did you manage to solve this problem with the downgrade?
Which version are you using now ( working version) ?

**Comment by maodahua** [comment]
> > > Hi
> > > I have the same problem
> > > ![image](https://user-images.githubusercontent.com/65561486/97982834-400c1680-1dcc-11eb-8a56-48803d8dbae4.png)
> > > LDAP Sync works, but i cant login
> > > Have you solved it？
> > 
> > 
> > I have no idea. So I install a old version snipeit and restore the backupdata before the upgrade.
> 
> ok, did you manage to solve this problem with the downgrade?
> Which version are you using now ( working version) ?

I use V4.9.55 now. V4.x is work fine, I use this version for produce

**Comment by firsakura** [comment]
> > > Hi
> > > I have the same problem
> > > ![image](https://user-images.githubusercontent.com/65561486/97982834-400c1680-1dcc-11eb-8a56-48803d8dbae4.png)
> > > LDAP Sync works, but i cant login
> > > Have you solved it？
> > 
> > 
> > I have no idea. So I install a old version snipeit and restore the backupdata before the upgrade.
> 
> ok, did you manage to solve this problem with the downgrade?
> Which version are you using now ( working version) ?

Mine is 

Snipe-IT versionv5.0.5-pre build 5457 
PHP Version7.2.34
Laravel Version6.18.10

I just built it up, never tried lower versions.

**Comment by someonept** [comment]
> > > > Hi
> > > > I have the same problem
> > > > ![image](https://user-images.githubusercontent.com/65561486/97982834-400c1680-1dcc-11eb-8a56-48803d8dbae4.png)
> > > > LDAP Sync works, but i cant login
> > > > Have you solved it？
> > > 
> > > 
> > > I have no idea. So I install a old version snipeit and restore the backupdata before the upgrade.
> > 
> > 
> > ok, did you manage to solve this problem with the downgrade?
> > Which version are you using now ( working version) ?
> 
> Mine is
> 
> Snipe-IT versionv5.0.5-pre build 5457
> PHP Version7.2.34
> Laravel Version6.18.10
> 
> I just built it up, never tried lower versions.

Is this Snipte-IT version ( Snipe-IT versionv5.0.5-pre build 5457 )  working correctly ? 
Does this problem still not occur?

**Comment by firsakura** [comment]
> > > > > Hi
> > > > > I have the same problem
> > > > > ![image](https://user-images.githubusercontent.com/65561486/97982834-400c1680-1dcc-11eb-8a56-48803d8dbae4.png)
> > > > > LDAP Sync works, but i cant login
> > > > > Have you solved it？
> > > > 
> > > > 
> > > > I have no idea. So I install a old version snipeit and restore the backupdata before the upgrade.
> > > 
> > > 
> > > ok, did you manage to solve this problem with the downgrade?
> > > Which version are you using now ( working version) ?
> > 
> > 
> > Mine is
> > Snipe-IT versionv5.0.5-pre build 5457
> > PHP Version7.2.34
> > Laravel Version6.18.10
> > I just built it up, never tried lower versions.
> 
> Is this Snipte-IT version ( Snipe-IT versionv5.0.5-pre build 5457 ) working correctly ?
> Does this problem still not occur?

we still have this issue on this version  ( Snipe-IT versionv5.0.5-pre build 5457 )

**Comment by snipe** [comment]
@uberbrady can you take a look?

**Comment by VanillaNinjaD** [comment]
After my upgrade to v5 I had many users unable to login until I selected the LDAP option for "Append domain name to username field". This was never required for my LDAP configuration prior to v5 and we have been using Snipe-IT since v2.x

Give it a try, I hope it helps someone

![image](https://user-images.githubusercontent.com/7405702/98687413-50257800-232f-11eb-98ea-efa4eeacccac.png)

**Comment by uberbrady** [comment]
@VanillaNinjaD the migration that runs to get your database schema migrated from v4 to v5 _should_ automatically set that variable during the migration process - but it looks like that didn't happen for you for some reason.

**Comment by VanillaNinjaD** [comment]
@uberbrady I was one of the users bit by the weird migrations issue that some of us had during the v5 upgrade. I'm sure that had something to do with it.

I only pointed it out since I noticed the screenshots above have "This is an Active Directory Server" selected but do not have the "Append domain name to username field" selected

**Comment by maodahua** [comment]
Hello everyone, today I test V5.0.7 and when I check the box "Append domain name to username field". LDAP test successfully and I can login! but in old version, No matter whether I check it or not, I can’t log in.
![image](https://user-images.githubusercontent.com/11650756/99368754-7ed6bc00-28f6-11eb-83aa-ea2b948dfeee.png)
So, for now I think this issue have been fixed and I will close the issue.

**Comment by snipe** [comment]
@maodahua Great news! Thanks so much for testing that so quickly!

**Comment by jmarquezalfaro** [comment]
Saludos,

Correcto. Se debe seleccionar:
![image](https://user-images.githubusercontent.com/33870645/114285318-edd6bd80-9a1b-11eb-8647-0d73b96a5a48.png)

**Comment by TheNamelessSir** [comment]
Hi, i also had this problem solved by checking the Append domain name box.

Thank you!

**Comment by aice09** [comment]
Please try the following settings. I hope this help you guys.

![ldapsnipeitsettings](https://user-images.githubusercontent.com/16074031/181775258-8a80061c-6f73-4a64-a8a2-f34b456caec2.PNG)

**Comment by Aliko47** [comment]
Hi all, 
I also faced the same issue using LDAP via AD. Changing LDAP Authentication query from 'uid=' to 'sAMAccountName=' fixed this issue.

**Comment by kmccoycoc** [comment]
@Aliko47, that fixed my issue.  I used to have the "LDAP Authentication query" field as uid=userPrincipalName  I had to change it to userPrincipalName=  I guess they changed the syntax in an update, and didn't update the documentation?

**Comment by brichardson1991** [comment]
I concur with @aice09 and @Aliko47.

LDAP was working fine for ages now it's fixed changing the LDAP Authentication Query to samaccountname=

**Comment by PavelTikal** [comment]
Hello, I had the same issue. My configuration was the same as user aice09, except that I had a value set in the LDAP active flag field, specifically userAccountControl, while aice09 had it set to null.
That turned out to be the issue. Active Directory returns a number for userAccountControl, but Snipe-IT expects a boolean value. Once I set the flag field to null, everything started working correctly after the next LDAP sync.

**Comment by ktague25** [comment]
Same issue here. Resolved by changing LDAP Authentication query to **samaccountname=** as mentioned by brichardson1991
