### ISSUE TITLE
Duplicate API route

### ISSUE THREAD

**Issue by diegogarciadev** [grokability/snipe-it#8624]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Duplicated api route accessories missing

**Screenshots**
![image](https://user-images.githubusercontent.com/5694236/97308501-3846f200-1861-11eb-936f-5698bb3b6347.png)

**Comment by mzack5020** [comment]
Addressed in my PR #8671
