### ISSUE TITLE
Unaccepted Assets not working

### ISSUE THREAD

**Issue by diegogarciadev** [grokability/snipe-it#8626]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Unaccepted Assets report is not working, when you go to https://develop.snipeitapp.com/reports/unaccepted_assets you will see Showing 1 to 1 of 1 rows or something like that but no content:

![image](https://user-images.githubusercontent.com/5694236/97324755-7dbfeb00-1872-11eb-9366-5fa4b60a4beb.png)

As I can see in debug mode, an api call to maintenances is shown 
![image](https://user-images.githubusercontent.com/5694236/97324862-a0520400-1872-11eb-8279-9d830758f330.png)

**Expected behavior**
Show unacepted assets

**Comment by Relix360** [comment]
Same here on 5.0.3

**Comment by krojas4** [comment]
in version 5.0.4 it also shows that problem

**Comment by Relix360** [comment]
Problem also present on demo 

@snipe

**Comment by sarang2502** [comment]
Same here on v5.0.5
It displays for one second and then gives out blank page.

**Comment by diegogarciadev** [comment]
I've found on this file: **resources/views/reports/unaccepted_assets.blade.php** the following content:

``
data-url="{{route('api.maintenances.index') }}"
``

![image](https://user-images.githubusercontent.com/5694236/98337167-7a61f780-2008-11eb-83c4-ad2740cec8c7.png)

**Comment by diegogarciadev** [comment]
![image](https://user-images.githubusercontent.com/5694236/98362585-ca9f8080-202d-11eb-8b04-4d73e669b244.png)

```
[2020-11-06 12:43:23] production.ERROR: BadMethodCallException: Call to undefined method App\Models\Asset::unaccepted() in /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50
Stack trace:
#0 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\Database\Eloquent\Model::throwBadMethodCallException('unaccepted')
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1622): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'unaccepted', Array)
#2 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1634): Illuminate\Database\Eloquent\Model->__call('unaccepted', Array)
#3 /var/www/html/snipe-it/app/Http/Controllers/ReportsController.php(981): Illuminate\Database\Eloquent\Model::__callStatic('unaccepted', Array)
#4 /var/www/html/snipe-it/app/Http/Controllers/ReportsController.php(866): App\Http\Controllers\ReportsController->getAssetsNotAcceptedYet()
```

**Comment by Pikok89** [comment]
My setup is experiencing the same issue since 5.0.1.

**Comment by thumperest** [comment]
Thank you @diegogarciadev I am experiencing the same issue.

**Comment by Relix360** [comment]
@diegogarciadev that was also present on 4.9.2 but in that version the report was working 
![image](https://user-images.githubusercontent.com/52633264/98852678-ca8cef80-2436-11eb-8104-ea8ba929f01a.png)

**Comment by diegogarciadev** [comment]
@Relix360 Yes, I think this is for export, if you try to export what data you obatain?

**Comment by Relix360** [comment]
@diegogarciadev I'm not running a 4.9 2 version anymore, but on 5.0.3 i get a blank file, I also have tried replacing the file for the one in 4.9.2 but I got the same result from the report

**Comment by snipe** [comment]
This was fixed on develop earlier this week
