### ISSUE TITLE
Upgrade Permissions

### ISSUE THREAD

**Issue by WELLBOREIS** [grokability/snipe-it#8627]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Can't run php upgrade.php because root/sudo user is not allowed and non-root/sudo user does not have correct file permissions. Need to know which files and folders the non-root/sudo user needs to be able to write to. Already tried giving full write access to non-root/sudo user, however still says Permission denied

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS] CentOS 8
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by roratonet** [comment]
Assuming that the Apache user is "www-data" and your snipe-it installation folder (home of upgrade.php) is /var/www/snipeit
Otherwise replace as needed.

Please do the following with the root user:
`chown -R www-data:www-data /var/www/snipeit`
`sudo -u www-data php /var/www/snipeit/upgrade.php`

If this works, then the permissions for the upgrade are right set.

In addition, add your normal user to the www-data group (replace www-data if Apache User group is different):
`usermod -a -G www-data <user>`

**Comment by WELLBOREIS** [comment]
@roratonet I apologize, but I'm not very familiar with Linux.

In your first step, you say I need to do:

chown -R www-data:www-data /var/www/snipeit
sudo -u www-data php /var/www/snipeit/upgrade.php

with "root", however if I replace the first www-data with root, I get the error: invalid group: 'root:www-data'

**Comment by roratonet** [comment]
No, please don't replace www-data with root but execute the command as the root user.

**Comment by WELLBOREIS** [comment]
@roratonet I just tried and got "chown: invalid user: ‘www-data:www-data’"

**Comment by WELLBOREIS** [comment]
How do I find out which group is the Apache user group? I think that's my issue.

**Comment by WELLBOREIS** [comment]
It looks like the group name is Apache.

**Comment by roratonet** [comment]
Use apache:apache

**Comment by WELLBOREIS** [comment]
Ok I changed ownership to apache:apache. I added the user "update" to the apache group. I was able to run the second script "update.php" using the username "apache" however I keep getting access denied with "update"

[update@USHO1-AM01 snipe]$ php upgrade.php
Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT
files for you unless you have git installed.
It simply runs the standard composer and artisan
commands needed to finalize the upgrade after.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter if upgrading from v3 to v4.
!! See the Snipe-IT documentation for help:
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: 7.4.11

PHP version: 7.4.11 is at least 7.1.3 - continuing...

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

-- Starting backup...
Backup failed because: mkdir(): Permission denied.

In StreamHandler.php line 110:

  The stream or file "/var/www/html/snipe/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied




--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

-- Failed to enter maintenance mode.
file_put_contents(/var/www/html/snipe/storage/framework/down): failed to open stream: Permission denied


--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
error: cannot open .git/FETCH_HEAD: Permission denied
fatal: Unable to create '/var/www/html/snipe/.git/index.lock': Permission denied
fatal: Unable to create '/var/www/html/snipe/.git/index.lock': Permission denied
Cannot save the current index state
error: cannot open .git/FETCH_HEAD: Permission denied
-- -- -- -- --------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- Deleting bootstrap/cache/config.php. It it no longer used.
-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar - trying globally.

Deprecation Notice: Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
Deprecation Notice: Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201


  [ErrorException]
  file_put_contents(/var/www/html/snipe/vendor/composer/autoload_classmap.php): failed to open stream: Permission denied


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

Generating optimized autoload files
Generated optimized autoload files containing 5499 classes

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading-to-v4">Upgrading to v4 from v3</a></strong></div><div>Snipe-IT v4 includes a ton of new features and bug fixes, and all users are strongly encouraged to upgrade. For a full list of what's new in V4, click here. Please note that Snipe-IT v4 does require PHP &gt;= 5.6.4. Please see the list of requirements before upgrading.Updating Snipe-IT should normal...</div></blockquote>

**Comment by roratonet** [comment]
What about doing that from root?

`sudo -u apache php /var/www/html/snipe/upgrade.php`

**Comment by WELLBOREIS** [comment]
That appears to be working. Not sure if the "sh:composer: command not found" is an error or not, but other than that, looks good. Not sure why the user 'update' wont work even though it's in the same group.

[root@USHO1-AM01 snipe]# sudo -u apache php /var/www/html/snipe/upgrade.php
Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT
files for you unless you have git installed.
It simply runs the standard composer and artisan
commands needed to finalize the upgrade after.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter if upgrading from v3 to v4.
!! See the Snipe-IT documentation for help:
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: 7.4.11

PHP version: 7.4.11 is at least 7.1.3 - continuing...

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database SnipeIT...
Determining files to backup...
Zipping 68 files and directories...
Created zip containing 68 files and directories. Size is 1.21 MB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!


--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.


--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
Already on 'master'
-- -- No local changes to save
-- Your branch is up to date with 'origin/master'.
-- Already up to date.
--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- Deleting bootstrap/cache/config.php. It it no longer used.
-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar - trying globally.

sh: composer: command not found
sh: composer: command not found




--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

-- Nothing to migrate.


--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

- OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Caching routes and config:
--------------------------------------------------------

-- Configuration cache cleared!
Configuration cached successfully!
-- Route cache cleared!
Routes cached successfully!

--------------------------------------------------------
Step 10: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.


--------------------------------------------------------
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.
--------------------------------------------------------


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading-to-v4">Upgrading to v4 from v3</a></strong></div><div>Snipe-IT v4 includes a ton of new features and bug fixes, and all users are strongly encouraged to upgrade. For a full list of what's new in V4, click here. Please note that Snipe-IT v4 does require PHP &gt;= 5.6.4. Please see the list of requirements before upgrading.Updating Snipe-IT should normal...</div></blockquote>

**Comment by roratonet** [comment]
`curl -sS https://getcomposer.org/installer | php sudo mv composer.phar /usr/bin/composer`

Then re-run

`sudo -u apache php /var/www/html/snipe/upgrade.php`

**Comment by WELLBOREIS** [comment]
I got this error when running the script:

[root@USHO1-AM01 snipe]# curl -sS https://getcomposer.org/installer | php sudo mv composer.phar /usr/bin/composer
Could not open input file: sudo
curl: (23) Failed writing body (0 != 16366)

<blockquote></blockquote>

**Comment by WELLBOREIS** [comment]
I installed using a different link, but got this output:

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar - trying globally.

Cannot create cache directory /usr/share/httpd/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /usr/share/httpd/.cache/composer/files/, or directory is not writable. Proceeding without cache
Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Cannot create cache directory /usr/share/httpd/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /usr/share/httpd/.cache/composer/files/, or directory is not writable. Proceeding without cache
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
11 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Generated optimized autoload files containing 5497 classes

**Comment by roratonet** [comment]
Everything with the root user:

`cd /var/www/html/snipe`
`curl -sS https://getcomposer.org/installer | php
php composer.phar install --no-dev --prefer-source`
`sudo -u apache php /var/www/html/snipe/upgrade.php`

**Comment by WELLBOREIS** [comment]
[root@USHO1-AM01 ~]# cd /var/www/html/snipe
[root@USHO1-AM01 snipe]# curl -sS https://getcomposer.org/installer | php php composer.phar install --no-dev --prefer-source
Could not open input file: php
curl: (23) Failed writing body (0 != 16366)

<blockquote></blockquote>

**Comment by roratonet** [comment]
Sorry, my typo

`cd /var/www/html/snipe`
`curl -sS https://getcomposer.org/installer | php composer.phar install --no-dev --prefer-source`
`sudo -u apache php /var/www/html/snipe/upgrade.php`

**Comment by WELLBOREIS** [comment]
:(

[root@USHO1-AM01 snipe]# curl -sS https://getcomposer.org/installer | php composer.phar install --no-dev --prefer-source
Could not open input file: composer.phar
curl: (23) Failed writing body (0 != 16366)
[root@USHO1-AM01 snipe]#

<blockquote></blockquote>

**Comment by WELLBOREIS** [comment]
Does anyone have any other ideas?
