### ISSUE TITLE
QR-Code missing

### ISSUE THREAD

**Issue by GustelDE** [grokability/snipe-it#8628]
Hi folks,

is it possbile to correct the Image-URL for the QR-Code in the Asset-Window?
The URL points to localhost instead of the correct IP.

![Zwischenablage01](https://user-images.githubusercontent.com/26502186/97329167-10fb1f80-1877-11eb-8d06-4de2e265352b.jpg)

The logo on top points to:
http://10.10.0.14/uploads/setting-logo-itDQQUwY0h.jpg

The QR-Code points to:
http://localhost/hardware/906/qr_code

If I manually edit the URL to the right IP, the QR-Code shows!

Thanks

Snipe-IT: 5.0.4 (but this was since the first time we used Snipe-IT, 4.9.??)
Linux/Docker-Version

**EDIT - ADDITIONAL INFORMATION:**

If I change in the "view.blade.php"
https://github.com/snipe/snipe-it/blob/master/resources/views/hardware/view.blade.php

In Line 734:
<img src="{{ config('**app.url**') }}/hardware/{{ $asset->id }}/qr_code"...

to:
<img src="{{ config('**url**') }}/hardware/{{ $asset->id }}/qr_code"...
The QR-Code show up correctly!

![Zwischenablage01](https://user-images.githubusercontent.com/26502186/97340266-d946a480-1883-11eb-9ecb-77cbce0f7954.jpg)

Is it possible to implement this in the next release?
Otherwise I have to do this edit after each update ;D

Reagrds

**Comment by PiChG** [comment]
Hi GustelDE,
we've had simmilar issue with our instance - all images were show properly despite QR codes that had link pointing to 127.0.0.0....
For us solution was to properly setup ENV variables.

Regards,
PiChG

**Comment by snipe** [comment]
You'll want to make sure your `APP_URL` is correct in your .env file. It should be the full URL of the Snipe-IT instance, including `http://` or `https://`.

`APP_URL=http://10.10.0.14`

then clear your config cache.

`php artisan config:clear`

**Comment by GustelDE** [comment]
Thanks, I knew this, but our Snipe-IT-Server is a multi-homed server, which means he has multiple NICs in different VLANs. A single IP does (by far) not accommodate this problem. I described this here: https://github.com/snipe/snipe-it/issues/8578#issue-727187840

Four our enviroment I have to comment the "APP_URL" out and edit the view.blade.php as written above.
Or is it possible to add multiple APP_URLs in the .env?

Thanks

**Comment by snipe** [comment]
It's not possible to add multiple IPs - the APP_URL is what's used for the application to know how to generate URLs.
