### ISSUE TITLE
LDAP Issue After Upgrade

### ISSUE THREAD

**Issue by drudich** [grokability/snipe-it#8629]
After the upgrade from v4.95 to v5.04, I can no longer log into SnipeIT with my usual LDAP creds.  Do I need to change something to get LDAP working again?

**Comment by drudich** [comment]
I had an active session in another browser, so I can still get into the admin settings in SnipeIT.  When I go to "Test LDAP Sync" it completed successfully and shows a bunch of users, however I still cannot log into a new session (via an incognito browser).  Any ideas?

**Comment by pcsmarts502** [comment]
Make sure your paths have the forward slashes like this DB_DUMP_PATH="C:/PROGRA~1/MySQL/MYSQLS~1.7/bin"  and make sure you change the minus signs (-) to (=) like this  REDIS_PORT=null   in your .env file and then run upgrade.php again

**Comment by drudich** [comment]
Thank you.  I am running SnipeIT in Ubuntu 18.04.  I did fix the REDIS_PORT issue... the only issue that I have now is the LDAP problem that I listed above.

**Comment by drudich** [comment]
I fixed this issue... for some reason, there was no "Company" associated with my LDAP account in SnipeIT.  Once I associated the "Company" with my account, I am now able to login.

**Comment by drudich** [comment]
Spoke too soon.  After setting the "Company" on my LDAP account, it let me login one time - I logged out and then I could never login again.

Any ideas?

**Comment by drudich** [comment]
I made a change to the LDAP user account in SnipeIT, re-synced the LDAP user database (under "People") and now it seems to be letting me login.
