### ISSUE TITLE
Remove, hide, or disable default fields on an asset (Same as issue 8155)

### ISSUE THREAD

**Issue by ItAdmin712** [grokability/snipe-it#8631]
**Server (please complete the following information):**
 - Snipe-IT Version : v4.9.5 - build 4482 (master)
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version : 7.4.11 

**Is your feature request related to a problem? Please describe.**
Feature Request:  On the default new asset page, There are fields we do not use, and don't for see using.  For example: order number, purchase cost, warranty. 

**Describe the solution you'd like**
I would like a way to disable the fields we don't want at all, and a way to make some fields not required.  Such as status. 

**Describe alternatives you've considered**
We already track our inventory in a home build Access database.  We could keep using it, but we loose our ability to have the web access, easy interface, etc, that Snipe-it gives us.

**Additional context**
I'm new to Snipe-it, but this is basically the same request as this closed issue ticket: https://github.com/snipe/snipe-it/issues/8155

**Comment by snipe** [comment]
This has been requested before. It’s not on the short term roadmap, but it’s still on our mind. If we can find a way to make that happen without crapping all over the database, we’ll consider it

**Comment by snipe** [comment]
Closing as duplicate of #8155

**Comment by Kvoo** [comment]
> This has been requested before. It’s not on the short term roadmap, but it’s still on our mind. If we can find a way to make that happen without crapping all over the database, we’ll consider it

Why do you need to crap all over the database? You don't have to remove the fields completely, just visually hiding them when rendering the webpage is enough

**Comment by snipe** [comment]
@Kvoo It's not that simple. We use presenters to standardize the way we display columns in the bootstrap-tables UI. We would need to create several more tables (or naive settings on an already very large settings table) to store those choices, and then on every page load, pull those choices into the bootstrap tables, every UI view, etc - in *addition* to the complex permissions we already support. And then every time we add a field, we have to create a database migration to be able to track whether it's visible or not. 

We already let you partially control the UI via CSS, as you've noted elsewhere - and we tuck lesser-used, non-essential fields within disclosure arrows and let you hide them in the tables. 

I don't really know why just skipping fields is so difficult, but even so, we provide lots of tooling around not seeing stuff you don't care about.

**Comment by Kvoo** [comment]
> [@Kvoo](https://github.com/Kvoo) It's not that simple. We use presenters to standardize the way we display columns in the bootstrap-tables UI. We would need to create several more tables (or naive settings on an already very large settings table) to store those choices, and then on every page load, pull those choices into the bootstrap tables, every UI view, etc - in _addition_ to the complex permissions we already support. And then every time we add a field, we have to create a database migration to be able to track whether it's visible or not.
> 
> We already let you partially control the UI via CSS, as you've noted elsewhere - and we tuck lesser-used, non-essential fields within disclosure arrows and let you hide them in the tables.
> 
> I don't really know why just skipping fields is so difficult, but even so, we provide lots of tooling around not seeing stuff you don't care about.

I also don't get why it's so difficult to just skip them, believe me. I just get the complaints. But thanks for the explanation that it isn't that simple.
