### ISSUE TITLE
Cannot restore from .sql backup

### ISSUE THREAD

**Issue by WELLBOREIS** [grokability/snipe-it#8634]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A clear and concise description of what the bug is. See below

**To Reproduce**
1. Go to '...' See below

**Expected behavior**
A clear and concise description of what you expected to happen. See below

**Screenshots**
If applicable, add screenshots to help explain your problem. See below

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.4
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 7.4.11

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 82

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on See above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way. See below
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

Can't restore backup

[root@USHO1-AM01 snipe]# php artisan db:restore mysql-SnipeIT.sql

  Command "db:restore" is not defined.

  Did you mean one of these?
      db:seed
      db:wipe
      queue:restart
      snipeit:restore-users

**Comment by MaxVRAM** [comment]
I have an exact replication of the issue on my server. @WELLBOREIS did you find a solution? I'd very much appreciate it if you posted it here.

Never mind. I just realised this is a duplicate of several other closed issues. Apparently the db:restore function is no longer implemented, and a restore has to be performed manually.

**Comment by uberbrady** [comment]
There _is_ a `snipeit:restore` artisan command, that could maybe help you. We don't formally document it (yet), but I've used it to restore probably dozens of customer's data, often.
