### ISSUE TITLE
500 server error and cannot get users or accessories

### ISSUE THREAD

**Issue by Dimtar** [grokability/snipe-it#8636]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Cannot list users page or accessories page.
Cannot checkout anything without a 500 server error page.

**To Reproduce**
Try to checkout anything to a user or location.
User and accesories page is empty.

**Expected behavior**
Both of the above were working.

**Screenshots**
![image](https://user-images.githubusercontent.com/3172977/97526099-86442d00-19fc-11eb-8f4d-765237d5a70e.png)
![image](https://user-images.githubusercontent.com/3172977/97526111-8cd2a480-19fc-11eb-904f-cac14121c8d1.png)

**Server (please complete the following information):**
Snipe IT v5.0.4
Official Docker container
 
**Error Messages**
For the checking out of assets etc.
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'action_date' in 'field list' (SQL: insert into `action_logs` (`item_type`, `item_id`, `user_id`, `target_type`, `target_id`, `location_id`, `note`, `action_date`, `action_type`, `company_id`, `updated_at`, `created_at`) values (App\Models\License, 3, 1, App\Models\User, 39, ?, ?, 2020-10-29 11:21:38, checkout, 2, 2020-10-29 11:21:38, 2020-10-29 11:21:38))

For the listing of users:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'accessories_users.note' in 'field list' (SQL: select `accessories`.*, `accessories_users`.`assigned_to` as `pivot_assigned_to`, `accessories_users`.`accessory_id` as `pivot_accessory_id`, `accessories_users`.`id` as `pivot_id`, `accessories_users`.`created_at` as `pivot_created_at`, `accessories_users`.`note` as `pivot_note` from `accessories` inner join `accessories_users` on `accessories`.`id` = `accessories_users`.`accessory_id` where `accessories_users`.`assigned_to` in (1, 4, 6, 7, 9, 12, 13, 14, 15, 17, 18, 20, 23, 27, 31, 32, 33, 34, 35, 36))/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php#669Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'accessories_users.note' in 'field list'/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php#66Doctrine\DBAL\Driver\PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'accessories_users.note' in 'field list'/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php#64

For the listing of accessories
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'accessories_users.note' in 'field list' (SQL: select `users`.*, `accessories_users`.`accessory_id` as `pivot_accessory_id`, `accessories_users`.`assigned_to` as `pivot_assigned_to`, `accessories_users`.`id` as `pivot_id`, `accessories_users`.`created_at` as `pivot_created_at`, `accessories_users`.`note` as `pivot_note` from `users` inner join `accessories_users` on `users`.`id` = `accessories_users`.`assigned_to` where `accessories_users`.`accessory_id` in (1, 2))/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php#669Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'accessories_users.note' in 'field list'/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php#66Doctrine\DBAL\Driver\PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'accessories_users.note' in 'field list'/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php#64

**Additional context**
This only started happening since the move from 4.x to 5.x, my guess is an upgrade of the database format was meant to take place but didn't? Its my best guess.

**Comment by mschmidt291** [comment]
We had the same problem. Exec into your container and execute the upgrade.php. Also clear the cache. This fixed it for us.

**Comment by Dimtar** [comment]
Thanks for your reply @mschmidt291, I was able to exec into the container and run the upgrade script. Whilst the script seemed happy I can no longer access the system. No matter what it redirects to the setup page and just has a generic server error 500.

Below is the log from the script if that offers any insight.
[Snipe-IT Upgrade Log.txt](https://github.com/snipe/snipe-it/files/5472080/Snipe-IT.Upgrade.Log.txt)

**Comment by Dimtar** [comment]
Ok slight update, I switched debug mode off and restarted the container. This let me back in but nothing is fixed.
If I re-enable debug mode I see the user page is still broken:
![image](https://user-images.githubusercontent.com/3172977/97819369-3b782d00-1cfc-11eb-90a8-57d54a2e9963.png)

Can provide whatever people need, just not sure what to provide exactly.

**Comment by Dimtar** [comment]
Was able to run the upgrade script a slightly different way and it seems happy now, closing the issue.

**Comment by Dimtar** [comment]
Spoke too soon apparently, just went to use the program this morning and I am getting pushed to the /setup page again.

The only thing that would have happened is any docker container updates would have been applied automatically daily. I ran the upgrade script again but it didn't fix it. I enabled debug and I get a page starting with this:

` (3/3) QueryException

SQLSTATE[HY000]: General error: 1835 Malformed communication packet (SQL: select * from `users` where `id` = 1 and `users`.`deleted_at` is null limit 1)`

Will post any information people need. This is getting frustrating though, not sure how I am meant to rely on this system if it breaks constantly.

**Comment by snipe** [comment]
I see a few answers here that might point you in the right direction:

https://stackoverflow.com/a/64689988
https://stackoverflow.com/a/64702607

(I do not recommend using the `PDO::ATTR_EMULATE_PREPARES` solution, as we have no idea what other errors that might introduce)

**Comment by snipe** [comment]
Looks like it's a bug introduced in MariaDB: https://jira.mariadb.org/browse/MDEV-24121

Best solution is to downgrade MariaDB and upgrade tp PHP7.3. It looks like this was recently fixed, but no word on when it will get pushed to docker hub yet, per the comments from just a few hours ago: https://jira.mariadb.org/browse/MDEV-24121?focusedCommentId=171567&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-171567

**Comment by Dimtar** [comment]
Thanks for taking the time to reply, its appreciated.

I'm running the MariaDB docker container from LinuxServer along with the official snipe-it docker container. Linuxserver seem to be active with updates so I will wait 24 hours for an update on the container and go from there.

**Comment by snipe** [comment]
@Dimtar 🤞 Please do let us know if an updated version (or downgraded version) resolves your issue. It certainly *does* seem like it would, given the timeliness of the convo on MariaDB's bug tracker and your issue.

**Comment by Go2ClassPoorYorick** [comment]
@Dimtar I had a similar error (`1054 Unknown column 'accessories_users.note' in 'field list' `)- just to probe a bit, is it possible that you ran the `php upgrade` script instead of `php artisan migrate`? 

I see you're also using the docker container and because of the way my docker instance was setup {root user) the upgrade script error-ed out (Unable to run as root) if you had to work around the upgrade script I have a hunch you may have been trying to use the normal installation script instead of the one defined in the docker guide.

**Comment by Dimtar** [comment]
@Go2ClassPoorYorick Appreciate you trying to help but the upgrade script worked fine, it fixed my first issue.
As for my second issue there was an update on the MariaDB container over the weekend it seems and this has resolved my Snipe IT issue, thanks all for their assistance.
