### ISSUE TITLE
Make the Import Feature more clear by showing that file types can be imported. 

### ISSUE THREAD

**Issue by baditaflorin** [grokability/snipe-it#8647]
**Is your feature request related to a problem? Please describe.**
When you first see the Import feature, you have Select Import FIle, but no description of what I can import.
**Describe the solution you'd like**
Show at the very minimal the types of files that you accept (CSV, XLSX, [...] etc)
Does it require the file to have a Header? These types of questions could help make a more smooth experience for the new users just introduced to the program.

**Comment by snipe** [comment]
This is now on develop and will be in the next tagged release.
