### ISSUE TITLE
Cannot import assets even when AUTO_GENERATE ID is true. 

### ISSUE THREAD

**Issue by baditaflorin** [grokability/snipe-it#8649]
**Describe the bug**
I have a CSV with some products, when I try to load the data using the importer , I get this error
`The model id field is required.`

**Screenshots**
![image](https://user-images.githubusercontent.com/2330999/97662628-3dce5300-1a80-11eb-907e-6f21a856563b.png)

![image](https://user-images.githubusercontent.com/2330999/97662830-bd5c2200-1a80-11eb-8ed1-594884100159.png)

![image](https://user-images.githubusercontent.com/2330999/97662912-ebd9fd00-1a80-11eb-94ca-275ad2a465fb.png)

**Comment by baditaflorin** [comment]
Tried with Model number and now getting this errors. 
![image](https://user-images.githubusercontent.com/2330999/97663352-fd6fd480-1a81-11eb-99d6-43af839864e1.png)

**Comment by baditaflorin** [comment]
Tried with every possible version that contains number in it...... 

![image](https://user-images.githubusercontent.com/2330999/97666351-1d08fc00-1a86-11eb-8b97-4df0bcd8476d.png)


![image](https://user-images.githubusercontent.com/2330999/97666392-3ca02480-1a86-11eb-9d26-df57cfdf098e.png)

**Comment by fajterini** [comment]
Hi I have the same issue on new installed 5.0.4 (windows) but import was working with 5.0.2. If this helps somehow :)
I have tried to enable/disable "AUTO_GENERATE ID" but this setting seems to have no impact. for me

Last edit: This issue seems to be only related to new Assests. I have now tested Consumables, Accessories, Components Import and no issue.

**Comment by PiChG** [comment]
For me it seems that some fields are lacking, but for now I have two instances PROD v4.9.4 and DEV v5.0.1
And in both cases imports are working fine - ofcourse after some tryouts with column names (usually up to 1hour of experimenting)
