### ISSUE TITLE
Cannot get CSR from parameter when setting up SAML

### ISSUE THREAD

**Issue by kclifford20** [grokability/snipe-it#8654]
#### Expected Behavior (or desired behavior if a feature request)

After clicking submit on the SAML detail entry screen, it should save and enable SAML.

-----

#### Actual Behavior

Error: openssl_csr_sign(): cannot get CSR from parameter 1

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade 
- Version of Snipe-IT you're running: 5.0.4
- Version of PHP you're running: 7.4.1
- Version of MySQL/MariaDB you're running: MySQL 8.0
- What OS and web server you're running Snipe-IT on: Windows Server 2019
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Git method, with upgrade.php used to upgrade
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
![SAML Error](https://user-images.githubusercontent.com/71674300/97818922-17631e80-1cf1-11eb-9295-5455bcce403a.PNG)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: SAML entry screen
- If a stacktrace is provided in the error, include that too.
[2020-11-02 09:46:33] testing.ERROR: openssl_csr_sign(): cannot get CSR from parameter 1 {"userId":11,"exception":"[object] (ErrorException(code: 0): openssl_csr_sign(): cannot get CSR from parameter 1 at C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Requests\\SettingsSamlRequest.php:74)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Requests\\SettingsSamlRequest.php(74): openssl_csr_sign()
#2 [internal function]: App\\Http\\Requests\\SettingsSamlRequest->App\\Http\\Requests\\{closure}()
#3 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php(270): call_user_func_array()
#4 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php(318): Illuminate\\Validation\\Validator->Illuminate\\Validation\\{closure}()
#5 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php(331): Illuminate\\Validation\\Validator->passes()
#6 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\ValidatesWhenResolvedTrait.php(25): Illuminate\\Validation\\Validator->fails()
#7 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Providers\\FormRequestServiceProvider.php(30): Illuminate\\Foundation\\Http\\FormRequest->validateResolved()
#8 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1102): Illuminate\\Foundation\\Providers\\FormRequestServiceProvider->Illuminate\\Foundation\\Providers\\{closure}()
#9 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1066): Illuminate\\Container\\Container->fireCallbackArray()
#10 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1051): Illuminate\\Container\\Container->fireAfterResolvingCallbacks()
#11 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(701): Illuminate\\Container\\Container->fireResolvingCallbacks()
#12 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(785): Illuminate\\Container\\Container->resolve()
#13 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(629): Illuminate\\Foundation\\Application->resolve()
#14 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(770): Illuminate\\Container\\Container->make()
#15 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteDependencyResolverTrait.php(79): Illuminate\\Foundation\\Application->make()
#16 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteDependencyResolverTrait.php(46): Illuminate\\Routing\\ControllerDispatcher->transformDependency()
#17 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteDependencyResolverTrait.php(27): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies()
#18 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(41): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies()
#19 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#20 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#21 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(681): Illuminate\\Routing\\Route->run()
#22 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#23 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\CheckPermissions.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckPermissions->handle()
#25 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#27 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#29 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#30 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute()
#31 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#32 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#33 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#34 C:\\inetpub\\wwwroot\\snipeit\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#36 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\SecurityHeaders->handle()
#38 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#40 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForDebug->handle()
#42 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\CheckForSetup.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForSetup->handle()
#44 C:\\inetpub\\wwwroot\\snipeit\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#46 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#48 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#50 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#52 C:\\inetpub\\wwwroot\\snipeit\\vendor\\barryvdh\\laravel-cors\\src\\HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle()
#54 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#56 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#57 C:\\inetpub\\wwwroot\\snipeit\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle()
#58 {main}
"} 
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo: Disabled for demo environment
- Include any additional information you can find in `storage/logs` and your webserver's logs: As above
- Include what you've done so far in the installation, and if you got any error messages along the way: As above
- Indicate whether or not you've manually edited any data directly in the database: No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by LSNIGHTSHOT** [comment]
Based on this https://www.php.net/manual/en/openssl.installation.php try copying
https://github.com/openssl/openssl/blob/master/apps/openssl.cnf to C:\Program Files\Common Files\SSL\openssl.cnf

I had to paste mine to C:\usr\local\ssl\

<blockquote><img src="https://www.php.net/favicon.ico" width="48" align="right"><div><strong><a href="https://www.php.net/manual/en/openssl.installation.php">PHP: Installation - Manual</a></strong></div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/3279138?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/openssl/openssl">openssl/openssl</a></strong></div><div>TLS/SSL and crypto library. Contribute to openssl/openssl development by creating an account on GitHub.</div></blockquote>

**Comment by kclifford20** [comment]
Legend! Thanks for your help! :)
