### ISSUE TITLE
35 Users Out of 2500 Not Syncing - LDAP

### ISSUE THREAD

**Issue by WELLBOREIS** [grokability/snipe-it#8660]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
There are approximately 35 users out of 2500 that do not update when LDAP sync is run from either CLI or GUI. There is no attribute that appears to be different than others that are syncing properly.

**To Reproduce**
1. Go to 'People'
2. Click on 'LDAP Sync'
3. Click on 'Synchronize'
4. Synchronization completed without error in both CLI and GUI

**Expected behavior**
Attributes are updated according to what is in AD.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.4
 - OS: [e.g. Ubuntu, CentOS] CentOS 8
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.4.12

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 82

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? upgrade
- What OS and web server you're running Snipe-IT on CentOS 8 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: Negative

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by uberbrady** [comment]
We typically sync 'brand-new' users in v5 at about 1000-users-per-minute, and 'already-synced' users go at around 1000-users-per-30-seconds.

At 2500, you're *probably* going to be able to do an initial sync in around 2.5 minutes, and a subsequent sync in 1min 15secs.

If you run `php artisan snipeit:ldap-sync --json_summary` - what output do you get; do your users get synchronized?

Are your missing users in a different OU than your 'main' set of users? Are they perhaps disabled/deactivated?

If your webserver isn't configured to allow connections to remain open for a long time, I could imagine the web GUI button timing out when you click it.

**Comment by WELLBOREIS** [comment]
So I discovered that the users not synchronizing had spaces in their e-mail addresses (which was nice to know). As soon as I fixed this, I was able to sync just fine. The users originally imported just fine, however it must have allowed e-mail addresses to not be compliant in versions previous to 5. All's good in the neighborhood now! Thank you!

**Comment by snipe** [comment]
Awesome news! And thanks for following up with the answer :)
