### ISSUE TITLE
Different currency for different company

### ISSUE THREAD

**Issue by roratonet** [grokability/snipe-it#8666]
**Server (please complete the following information):**
 - Snipe-IT Version 5.0.4
 - OS: [e.g. Ubuntu, CentOS] Debian
 - Web Server: [e.g. Apache, IIS] Nginx
 - PHP Version 7.3

**Is your feature request related to a problem? Please describe.**
We have multiple companies all over the world using the same tool on one server, all with different currencies.
The main issue is that, when **EUR** is set as **Default Currency**, the company in CH is not able to create a new License in **CHF** but is forced to use **EUR**

**Describe the solution you'd like**
Either set a Default Currency, companybased (https://myserver.com/companies) - or better, let the Admin which adds the license choose the currency (sometimes licenses are bought in a different country with a different currency).

**Comment by snipe** [comment]
Currency is handled via location, not company. Changing that behavior is not on the short term roadmap.

**Comment by roratonet** [comment]
@snipe my question was regarding the **Licenses**, not the cost of the **Assets**.

In Assets, I'm ok to have a different currency based on Location.
The same would be nice to have for the Licenses which are a one and only section, not divided by Location (which could make it easier to separate the totals for each location)

Currently, when I change the Currency in https://demo.snipeitapp.com/admin/localization, the Currency of ALL Licenses is being changed to the new currency. Therefore, if a license has been created with 500 USD and I change the **Default Currency** (https://demo.snipeitapp.com/admin/localization) to EUR, the license will show with 500 EUR.

This is reproduceable 1:1 in the demo.

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/admin/localization">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
