### ISSUE TITLE
Audit log file

### ISSUE THREAD

**Issue by richierg** [grokability/snipe-it#8667]
**Server (please complete the following information):**
 - Snipe-IT 4.9.5 docker

**Is your feature request related to a problem? Please describe.**
Most companies need to audit user action on asset (delete/create), we have these information in history but it could be nice to have them also in log file to centralize them.

**Describe the solution you'd like**
You could add a log output for each user action as it's done on history table

**Comment by snipe** [comment]
Your Activity Report should do that for you, no?

**Comment by richierg** [comment]
Yes but Activity report data are saved in DB, if I want to export activity log to tools like ELK I need at least logfile.
But for example, if I need to add some security feature (alert when connexion is done outside office hours, or too many failed attempt) or just configure tools like fail2ban to avoid bruteforce attack on login page, I need to have login / logout / failed login information in logs file. And other information to log any user action can be fine.

**Comment by snipe** [comment]
Converting the audit logs into a text file is not currently on the short term roadmap, however you could certainly script this yourself by using the API or accessing the database directly.
