### ISSUE TITLE
Add category field to accesories in user layout

### ISSUE THREAD

**Issue by diegogarciadev** [grokability/snipe-it#8673]
**Server (please complete the following information):**
 - Snipe-IT Version 5.0.4
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.1.3

**Is your feature request related to a problem? Please describe.**
When a user login to the app he can't view accessories categories, no columns can be added to that view

**Describe the solution you'd like**
Add accessory category field

**Comment by snipe** [comment]
I'm not sure what you mean. Can you provide a screenshot please?

**Comment by diegogarciadev** [comment]
![Screenshot_2020-11-10-07-33-23-384_com microsoft emmx~2](https://user-images.githubusercontent.com/5694236/98636523-53b50100-2327-11eb-8015-9dfe6fa98d2c.jpg)

If you go to: https://develop.snipeitapp.com/account/view-assets yo can't see or add accesories category to the view.

Regards.

<blockquote><img src="https://develop.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://develop.snipeitapp.com/account/view-assets">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by snipe** [comment]
This is now on master and will be in the next release
