### ISSUE TITLE
Add "Rooms" as a sub category to "Locations"

### ISSUE THREAD

**Issue by jovibroz** [grokability/snipe-it#8675]
Server (please complete the following information):

Snipe-IT Version 5.04
OS: [Ubuntu Server 20.04.1]
Web Server: [Apache]
PHP Version 7.4.3
Is your feature request related to a problem? Please describe.

Describe the solution you'd like

It would be nice to create rooms and to associate assets to rooms in addition to Locations. A quick way to view equipment per room would be handy. I don't feel "Location" is meant to be used this way so Rooms would be a nice addition. 

Describe alternatives you've considered

Additional context

**Comment by gilesytheking** [comment]
This feature already exists in a fashion. You can use the "Parent location" to create rooms or locations within a location.

Just create a new location or room (Eg. Room 1) and then assign it to a parent location (eg. Office building).

Hope this helps
