### ISSUE TITLE
Cannot see history

### ISSUE THREAD

**Issue by dinhdobathi1992** [grokability/snipe-it#8676]
**Describe the bug**
I cannot see the data in history tab, all assets...

**To Reproduce**
1. Go to tab history in every assets
  you will see 

_**Showing 1 to 2 of 2 rows**_

**Expected behavior**
User can see the history of assets
**Screenshots**

![image](https://user-images.githubusercontent.com/67835317/98084369-483c8280-1eae-11eb-8fdc-2784de4ffb9b.png)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS:  CentOS7
 - Web Server:  Apache
 - PHP Version : newest

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version newest

**Additional context**
- Is this a fresh install or an upgrade? => fresh
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT:manual installation,

**Comment by UserGoodtm** [comment]
[https://snipe-it.readme.io/docs/overview](url) Verify Column Selection
![Снимок](https://user-images.githubusercontent.com/48224568/98095813-17ebe880-1e9c-11eb-99bd-fe0bf5032374.JPG)

**Comment by aamankavicius** [comment]
Thanks! @UserGoodtm 
Seems like this happens randomly where all of the columns just get unchecked.

**Comment by dinhdobathi1992** [comment]
> [https://snipe-it.readme.io/docs/overview](url) Verify Column Selection
> ![Снимок](https://user-images.githubusercontent.com/48224568/98095813-17ebe880-1e9c-11eb-99bd-fe0bf5032374.JPG)

Thank you @UserGoodtm 
I got it, comlumn unchecked randomly and I can see them now.
