### ISSUE TITLE
No Assets After Update To V5.0.4

### ISSUE THREAD

**Issue by Liel-q4d** [grokability/snipe-it#8679]
- Snipe-IT Version 5.0.4
 - OS: Ubuntu 20.04

- [V] I have enabled debug mode 
- [V] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

 
today i tried to update from V4.9.5 to the latest version.
I'm using docker compose to install my snipe it.
this is my docker-compose file:

> version: "3"
> services:
>   mysql:
>     image: mysql:5.7
>     container_name: snipe_mysql
>     restart: unless-stopped
>     volumes:
>       - snipesql-vol:/var/lib/mysq
>     environment:
>       - MYSQL_ROOT_PASSWORD=ubuntu
>       - MYSQL_USER=snipe
>       - MYSQL_PASSWORD=ubuntu
>       - MYSQL_DATABASE=snipe
>   snipeit:
>     image: linuxserver/snipe-it:latest
>     container_name: snipe-it
>     restart: unless-stopped
>     depends_on:
>       - mysql
>     volumes:
>       - snipesql-vol:/config
>     environment:
>       - APP_URL=snipe-it.domain.com
>       - MYSQL_PORT_3306_TCP_ADDR=mysql
>       - MYSQL_PORT_3306_TCP_PORT=3306
>       - MYSQL_DATABASE=snipe
>       - MYSQL_USER=snipe
>       - MYSQL_PASSWORD=password
>       - PGID=1000
>       - PUID=1000
>       - MAIL_DRIVER=smtp
>       - MAIL_HOST=smtp.office365.com
>       - MAIL_PORT=587
>       - MAIL_USERNAME=mail@domain.com
>       - MAIL_PASSWORD=password
>       - MAIL_ENCRYPTION=TLS
>       - MAIL_FROM_ADDR=mail@domain.com
>       - MAIL_FROM_NAME='Snipe-IT'
>       - MAIL_REPLYTO_ADDR=mail@domain.com
>       - MAIL_REPLYTO_NAME='Snipe-IT'
> 
>     ports:
>       - "80:80"
> volumes:
>   snipesql-vol:

so i:
1.delete the old snipe it container.
2.delete the MSQL container.
3.pull the new snipe-it+msql container.
4.run docker-compose up. 

the update succeeded, but i have zero data.

i can see the volum with all my data in this path: 
 /var/lib/docker/volumes/ubuntu_snipesql-vol/_data

but when i run docker-compose up still no assets and no data.

How can i import all the data to the new snipe it container?

**Comment by mstefan21** [comment]
After update you need to run migrate command inside php container with app. From update page:
```bash
php artisan migrate
php artisan config:clear
php artisan config:cache
```

**Comment by snipe** [comment]
I'm not clear what's happening here. Does your admin dashboard actually show zero assets in the colored boxes at the top, or are the tables of asset, etc listings not showing? What's in your app error log?
