### ISSUE TITLE
ERROR: Please check the form below for errors

### ISSUE THREAD

**Issue by kevincRUN974** [grokability/snipe-it#8686]
#### Please confirm you have done the following before posting your bug report:

- [*] I have enabled debug mode 
- [*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When i click on "save" from ldap setting, i have the error : Please check the form below for errors.
But debug mode say nothing. Was ok in 4.9.5 version. 
**To Reproduce**
1. Go to 'setting'
2. Click on 'LDAP'
3. Then click on save
 Please check the form below for errors

**Expected behavior**

I expect the ldap settings are saving.

**Screenshots**
![image](https://user-images.githubusercontent.com/73994524/98232887-a97c5880-1f77-11eb-9ebf-dd968f29b868.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.5-pre build 5457
 - OS: Debian 10.6
 - Web Server: Apache2
 - PHP Version 7.3.19-1~deb10u1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version  86.0.4240.183 (Build officiel) (64 bits)

**Smartphone (please complete the following information):**
 - Device: REALME X2 PRO
 - OS: ANDROID 10
 - Browser: Firefox

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error NONE
- If a stacktrace is provided in the error, include that too. NONE
- Any errors that appear in your browser's error console. NONE
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. THE ERROR IS NOT REPRODUCIBLE
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? UPGRADE FROM 4.9.5
- What OS and web server you're running Snipe-IT on DEBIAN 10.6 APACHE2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database NO

Add any other context about the problem here. WAS WORKING ON 4.9.5

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Relix360** [comment]
@kevincRUN974 please check that the  minimum password length is >= 8

**Comment by kevincRUN974** [comment]
> @kevincRUN974 please check that the minimum password length is >= 8

Omg was just that :O Thank you a lot it's working!

**Comment by kevincRUN974** [comment]
PS: I close the issue (again) thannks!
