### ISSUE TITLE
How to let ordinary users see Dashboard？

### ISSUE THREAD

**Issue by linux-ops** [grokability/snipe-it#8690]
**Server (please complete the following information):**
 - Snipe-IT Version  5 
 - OS: [e.g, CentOS]
 - Web Server: [e.g.nginx】

**Comment by sinichi19** [comment]
none, only admin have access to dashboard 
If im not mistaken there are feature request to also apply to the user the dashboard

**Comment by snipe** [comment]
There is a feature request for this
