### ISSUE TITLE
Upgrade Question and admin Permission

### ISSUE THREAD

**Issue by sinichi19** [grokability/snipe-it#8693]
Good Day,

To All,

First congrats to the Snipe-IT team for the great update, Keep safe and God Bless.

---

Questions:

1. Tried to upgrade from 4.9.5 to latest stable using git - php upgrade.php
My expected version is 5.0.4 but after the successful upgrade saw  the version is v5.0.5-pre ? this is the latest stable?

2. If I want to edit the admin permission and disable the delete function to asset,model,etc., requesting for your kind assistance to give me a hint where can I edit from the source code. 

More Power and Thank You

**Comment by denzfarid** [comment]
> Good Day,
> 
> To All,
> 
> First congrats to the Snipe-IT team for the great update, Keep safe and God Bless.
> 
> Questions:
> 
>     1. Tried to upgrade from 4.9.5 to latest stable using git - php upgrade.php
>        My expected version is 5.0.4 but after the successful upgrade saw  the version is v5.0.5-pre ? this is the latest stable?
> 
>     2. If I want to edit the admin permission and disable the delete function to asset,model,etc., requesting for your kind assistance to give me a hint where can I edit from the source code.
> 
> 
> More Power and Thank You

Question 1.  I think, because the upgrade.php php script, only pulls from the master branch, and currently that branch has the v5.0.5-pre version. In this pre version there were several bugs that were fixed in the previous version, such as signature box, cleanup backup etc.

Question 2. try by making a custom admin in the group, 
https://DOMAIN-SNIPE-IT/admin/groups/create

**Comment by sinichi19** [comment]
> > Good Day,
> > To All,
> > First congrats to the Snipe-IT team for the great update, Keep safe and God Bless.
> > Questions:
> > ```
> > 1. Tried to upgrade from 4.9.5 to latest stable using git - php upgrade.php
> >    My expected version is 5.0.4 but after the successful upgrade saw  the version is v5.0.5-pre ? this is the latest stable?
> > 
> > 2. If I want to edit the admin permission and disable the delete function to asset,model,etc., requesting for your kind assistance to give me a hint where can I edit from the source code.
> > ```
> > 
> > 
> > More Power and Thank You
> 
> Question 1. I think, because the upgrade.php php script, only pulls from the master branch, and currently that branch has the v5.0.5-pre version. In this pre version there were several bugs that were fixed in the previous version, such as signature box, cleanup backup etc.
> 
> Question 2. try by making a custom admin in the group,
> https://DOMAIN-SNIPE-IT/admin/groups/create

want to achive is when you choose user with admin rights you can also disable the delete function, if im not mistaken if the user have admin rights there is no option to disable the delete function, thats why want to edit from the source code if possible. thanks

**Comment by denzfarid** [comment]
> > > Good Day,
> > > To All,
> > > First congrats to the Snipe-IT team for the great update, Keep safe and God Bless.
> > > Questions:
> > > ```
> > > 1. Tried to upgrade from 4.9.5 to latest stable using git - php upgrade.php
> > >    My expected version is 5.0.4 but after the successful upgrade saw  the version is v5.0.5-pre ? this is the latest stable?
> > > 
> > > 2. If I want to edit the admin permission and disable the delete function to asset,model,etc., requesting for your kind assistance to give me a hint where can I edit from the source code.
> > > ```
> > > 
> > > 
> > > More Power and Thank You
> > 
> > 
> > Question 1. I think, because the upgrade.php php script, only pulls from the master branch, and currently that branch has the v5.0.5-pre version. In this pre version there were several bugs that were fixed in the previous version, such as signature box, cleanup backup etc.
> > Question 2. try by making a custom admin in the group,
> > https://DOMAIN-SNIPE-IT/admin/groups/create
> 
> want to achive is when you choose user with admin rights you can also disable the delete function, if im not mistaken if the user have admin rights there is no option to disable the delete function, thats why want to edit from the source code if possible. thanks

100% absolutely correct, but what I mean is, if you really want the admin group to not be able to delete, you should not select the group into the admin's permissions, but by custom
https://develop.snipeitapp.com/admin/groups/15, because if you edit the file directly from the source code, maybe you won't get the benefit of upgrading by using the upgrade.php script, it's certain that your source doesn't match the one is on this github

**Comment by sinichi19** [comment]
@denzfarid  yes sir i understand,. only want is have like admin access have dashboard, and other admin rights but only no delete, only the super admin have delete permission.  and if this possible to edit the policy for admin via source code i will try it. thanks

**Comment by snipe** [comment]
Only admins currently have access to the dashboard.
