### ISSUE TITLE
Feature Request: Custom Tooltips info

### ISSUE THREAD

**Issue by denzfarid** [grokability/snipe-it#8694]
Hello again, what if there is a menu to make custom tooltips info like this.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/1294403/98457494-82619900-21ba-11eb-98c6-b19c3b763f38.png">

because I see that this tooltip only has Predefined Kits, and nothing else

<img width="530" alt="image" src="https://user-images.githubusercontent.com/1294403/98457522-d1a7c980-21ba-11eb-90da-016768570d1a.png">
<img width="524" alt="image" src="https://user-images.githubusercontent.com/1294403/98457525-dc625e80-21ba-11eb-9fcf-11a80897f267.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/1294403/98457526-e2f0d600-21ba-11eb-89fd-aeb9a5b283d1.png">
<img width="624" alt="image" src="https://user-images.githubusercontent.com/1294403/98457535-f00dc500-21ba-11eb-894b-cfd94ebaa714.png">

it may look silly, but in my opinion we can use it and can help when there is a new admin, such as an intern admin for example

Thank you

oh ya, I want to tell you, if I change the skin blue (dark mode)
<img width="551" alt="image" src="https://user-images.githubusercontent.com/1294403/98457646-fea8ac00-21bb-11eb-834d-105a438609f9.png">

 it looks like the tooltip info does not look 
like this 
<img width="486" alt="image" src="https://user-images.githubusercontent.com/1294403/98457572-7d511980-21bb-11eb-8579-316670eddb95.png">

**Comment by snipe** [comment]
We'll be fleshing out the tooltips over the next few versions.

@Godmartinz can you address the dark blue skin tooltip issue please?

**Comment by Godmartinz** [comment]
Dark blue is fixed, updating the other skins now.

**Comment by Godmartinz** [comment]
#8714

**Comment by denzfarid** [comment]
> Dark blue is fixed, updating the other skins now.

Fantastic !!!, I really appreciate it, and Thank you very much
