### ISSUE TITLE
php upgrade.php stuck at 4.9.4

### ISSUE THREAD

**Issue by aminoacidity** [grokability/snipe-it#8695]
#### Expected Behavior (or desired behavior if a feature request)

php upgrade.php upgrade to 5.0

-----

#### Actual Behavior

upgrade show nothing more to pull at is stuck at 4.9.4

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade

- Version of Snipe-IT you're running 4.9.4
- Version of PHP you're running PHP 7.2.24-0ubuntu0.18.04.7
- Version of MySQL/MariaDB you're running mysql  Ver 15.1 Distrib 10.1.47-MariaDB
- What OS and web server you're running Snipe-IT on Debian Ubuntu 18.04.5 LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error none
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error none
- If a stacktrace is provided in the error, include that too. none
- Any errors that appear in your browser's error console. none
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. nope
- Include any additional information you can find in `storage/logs` and your webserver's logs. none
- Include what you've done so far in the installation, and if you got any error messages along the way. no error
- Indicate whether or not you've manually edited any data directly in the database no error

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by aminoacidity** [comment]
output of php upgrade.php

`Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT
files for you unless you have git installed.
It simply runs the standard composer and artisan
commands needed to finalize the upgrade after.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter if upgrading from v3 to v4.
!! See the Snipe-IT documentation for help:
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: 7.2.24-0ubuntu0.18.04.7

PHP version: 7.2.24-0ubuntu0.18.04.7 is at least 7.1.3 - continuing...

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Determining files to backup...
Zipping 50 files and directories...
Created zip containing 50 files and directories. Size is 27.93 KB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!


--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.


--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
Already on 'master'
-- -- Saved working directory and index state WIP on master: 6618e88a9 Fixed spanish translation parse error
-- M    public/uploads/barcodes/invalid_barcode.gif
M       storage/private_uploads/signatures/.gitkeep
Your branch is up to date with 'origin/master'.
-- Already up to date.
--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- Deleting bootstrap/cache/config.php. It it no longer used.
-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- Local composer.phar detected, so we'll use that.

-- Updating local composer.phar

You are already using composer version 2.0.6 (stable channel).


Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
11 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Generated optimized autoload files containing 5497 classes




--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

-- Nothing to migrate.


--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

- OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Caching routes and config:
--------------------------------------------------------

-- Configuration cache cleared!
Configuration cached successfully!
-- Route cache cleared!
Routes cached successfully!

--------------------------------------------------------
Step 10: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.


--------------------------------------------------------
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.
--------------------------------------------------------`

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading-to-v4">Upgrading to v4 from v3</a></strong></div><div>Snipe-IT v4 includes a ton of new features and bug fixes, and all users are strongly encouraged to upgrade. For a full list of what's new in V4, click here. Please note that Snipe-IT v4 does require PHP &gt;= 5.6.4. Please see the list of requirements before upgrading.Updating Snipe-IT should normal...</div></blockquote>

**Comment by roratonet** [comment]
Have you tried with a browser in Incognito Mode? Or clear your cookies - or use a different browser.

**Comment by snipe** [comment]
Try manually doing a `git pull` and running the upgrade script again.

**Comment by aminoacidity** [comment]
> Have you tried with a browser in Incognito Mode? Or clear your cookies - or use a different browser.

Yes. I have performed full browser - delete everything, incognito and new browser as well.

**Comment by aminoacidity** [comment]
> Try manually doing a `git pull` and running the upgrade script again.

Performed git pull and ran php upgrade.php. Cleared Browser and tried again. No change.

this is the git config if it helps

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/snipe/snipe-it
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by aminoacidity** [comment]
I feel stupid. I was git pulling into the wrong folder. All is good. Apologies for wasting everyones time.

**Comment by snipe** [comment]
@aminoacidity No worries :) Happens to the best of us. Glad you're sorted!

![miyakai-party](https://user-images.githubusercontent.com/197404/98634129-97801a00-22d7-11eb-8820-a07e99a4bdcd.gif)
