### ISSUE TITLE
Issue installing Snipe-It on Hostgator

### ISSUE THREAD

**Issue by TheBigT2020** [grokability/snipe-it#8696]
Hi All. I tried to use hostgator's Softaculous software installer to install SnipeIt. It says that all has been done properly. Checked that the database is setup, user created, everything seems to be as expected. BUT.....

When clicking on the (supposed) snipeIt installation (mydomain/public) I get a 500 internal server error. When i check the app error log, (public/error_log) it says this : 

[09-Nov-2020 04:05:36 UTC] PHP Fatal error:  Directive 'allow_call_time_pass_reference' is no longer available in PHP in Unknown on line 0

Now I researched this and it's a PHP directive that has long been unsupported. So the confusing thing for me is that snipeIT requires php 7+ yet I'm getting an error regarding 5.xxx features. Anyone heard of something like this before and how to fix it?

- [x] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh 
- Version of Snipe-IT you're running
latest 5.0.4
- Version of PHP you're running
7.4
- Version of MySQL/MariaDB you're running
Not applicable, database is fine
- What OS and web server you're running Snipe-IT on
linux shared (with Hostgator)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Softaculous installer
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Still only getting 500 server error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
public/index
- Include what you've done so far in the installation, and if you got any error messages along the way.

- Indicate whether or not you've manually edited any data directly in the database
no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Hi @TheBigT2020 - we [don't reference that method anywhere](https://github.com/snipe/snipe-it/search?q=allow_call_time_pass_reference). My guess would be you'd have to reach out to HostGator or Softaculous. 

Is there anything in your app log (`storage/logs/laravel.log`) that could shed some light?

**Comment by snipe** [comment]
I've reached out to Softaculous, and they replied:

> Thanks for reaching out to us, I have crossed check our installation and tested Softaculous Snip-IT installation on different servers but I didn't come across this error. This seems to be some PHP configuration issue. 

> You can ask the user to open a support ticket with us. We will definitely try to help him out. Link to open support ticket with Softaculous : https://softaculous.deskuss.com/open.php

So I'd say open a ticket with Softcaulous and give them this ticket URL.

**Comment by HG-CustomerAdvocate** [comment]
Hi @TheBigT2020 

We would love to take a look at this for your and see what we can do to help. Can you please reach out to us at reputation@endurance.com and provide the primary email address on your account and the best phone number to reach you? We look forward to working with you.

Erinn
Customer Advocate at HostGator
