### ISSUE TITLE
SnipeIt-v5.0.4 Unable to connect to LDAP directory!

### ISSUE THREAD

**Issue by d0lm3n** [grokability/snipe-it#8699]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

tail -f /storage/log/laravel.log
[2020-11-09 11:43:02] production.ERROR: ErrorException: ldap_search(): Search: Protocol error in /var/www/..../vendor/adldap2/adldap2/src/Connections/Ldap.php:286

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7375943/98536870-2584e200-2291-11eb-92d3-6da22eaa4f8e.png)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [Ubuntu 16.04]
 - Web Server: [Apache]
 - PHP Version 7.2

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by d0lm3n** [comment]
`[2020-11-09 14:04:52] production.ERROR: ErrorException: ldap_search(): Search: Protocol error in /var/www/assets.telesoftas.net/vendor/adldap2/adldap2/src/Connections/Ldap.php:286
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ldap_search(): ...', '/var/www/assets...', 286, Array)
#1 /var/www/assets.telesoftas.net/vendor/adldap2/adldap2/src/Connections/Ldap.php(286): ldap_search(Resource id #7, 'cn=users,cn=acc...', '(&(&(gidNumber=...', Array, false, 0, 0)
#2 /var/www/assets.telesoftas.net/vendor/adldap2/adldap2/src/Query/Builder.php(474): Adldap\Connections\Ldap->search('cn=users,cn=acc...', '(&(&(gidNumber=...', Array, false, 0)
#3 /var/www/assets.telesoftas.net/vendor/adldap2/adldap2/src/Query/Builder.php(497): Adldap\Query\Builder->run('(&(&(gidNumber=...')
#4 /var/www/assets.telesoftas.net/vendor/adldap2/adldap2/src/Query/Builder.php(425): Adldap\Query\Builder->runPaginate('(&(&(gidNumber=...', 500, true)
#5 /var/www/assets.telesoftas.net/vendor/adldap2/adldap2/src/Query/Builder.php(433): Adldap\Query\Builder->Adldap\Query\{closure}()
#6 /var/www/assets.telesoftas.net/app/Services/LdapAd.php(472): Adldap\Query\Builder->paginate(500)
#7 /var/www/assets.telesoftas.net/app/Console/Commands/LdapSync.php(228): App\Services\LdapAd->getLdapUsers(0)
#8 /var/www/assets.telesoftas.net/app/Console/Commands/LdapSync.php(129): App\Console\Commands\LdapSync->processLdapUsers()
#9 [internal function]: App\Console\Commands\LdapSync->handle()
#10 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#11 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#13 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#16 /var/www/assets.telesoftas.net/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#18 /var/www/assets.telesoftas.net/vendor/symfony/console/Application.php(1001): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#19 /var/www/assets.telesoftas.net/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\LdapSync), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#20 /var/www/assets.telesoftas.net/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#21 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#22 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Console/Application.php(185): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#23 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(273): Illuminate\Console\Application->call('snipeit:ldap-sy...', Array, NULL)
#24 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Foundation\Console\Kernel->call('snipeit:ldap-sy...', Array)
#25 /var/www/assets.telesoftas.net/app/Http/Controllers/Users/LDAPImportController.php(70): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#26 [internal function]: App\Http\Controllers\Users\LDAPImportController->store(Object(Illuminate\Http\Request))
#27 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#28 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('store', Array)
#29 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Users\LDAPImportController), 'store')
#30 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#31 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#32 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/assets.telesoftas.net/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/assets.telesoftas.net/app/Http/Middleware/CheckForTwoFactor.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/assets.telesoftas.net/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#50 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#51 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#52 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#53 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/assets.telesoftas.net/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/assets.telesoftas.net/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/assets.telesoftas.net/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /var/www/assets.telesoftas.net/app/Http/Middleware/CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /var/www/assets.telesoftas.net/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /var/www/assets.telesoftas.net/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#76 /var/www/assets.telesoftas.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#77 /var/www/assets.telesoftas.net/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#78 {main}`

**Comment by uberbrady** [comment]
Protocol error... hrm. Could it be SSL/TLS-related? Or maybe either needing `STARTTLS` or needing ldap:// or ldaps:// in your ldap server name?

**Comment by d0lm3n** [comment]
> Protocol error... hrm. Could it be SSL/TLS-related? Or maybe either needing `STARTTLS` or needing ldap:// or ldaps:// in your ldap server name?

Hello Uberbrady,

FreeIPA LDAP server. 
too don`t working STARTTLS.  probably changed from adldap2?
or
http://charithmahawatta.blogspot.com/2011/03/ldapbind-unable-to-bind-to-server.html ?
![image](https://user-images.githubusercontent.com/7375943/98644593-60daeb80-2339-11eb-8906-2d934f9fc454.png)


<blockquote><div><strong><a href="http://charithmahawatta.blogspot.com/2011/03/ldapbind-unable-to-bind-to-server.html">ldap_bind(): Unable to bind to server: Protocol error</a></strong></div><div>Note that you have to specify the protocol version prior to making a call to ldap_bind, when the server is expecting LDAP protocol version 3...</div></blockquote>

**Comment by winstan** [comment]
Having the same issue... SnipeIt-v5.0.6
LDAP server is 389-ds (which is what FreeIPA uses, same as @d0lm3n ).
The bind by the service account is fine (if I set the wrong password, it fails on that instead). It's failing on search().

**Comment by winstan** [comment]
LDAP server logs:

[date] conn=2 fd=144 slot=144 SSL connection from Redacted
[date] conn=2 TLS1.2 256-bit AES-GCM
[date] conn=2 op=0 BIND dn="cn=serviceAccountRedacted" method=128 version=3
[date] conn=2 op=0 RESULT err=0 tag=97 nentries=0 etime=0.016886416 dn="cn=serviceAccountRedacted"
[date] conn=2 op=1 SRCH base="ou=People,dc=example,dc=com" scope=2 filter="(objectClass=organizationalUnit)" attrs="* aci"
[date] conn=2 op=1 RESULT err=0 tag=101 nentries=1 etime=0.000925140
[date] conn=2 op=2 SRCH base="ou=People,dc=example,dc=com" scope=2 filter="(&(&(uid=*))(objectClass=inetorgperson)(objectClass=person))", invalid attribute request
[date] conn=2 op=2 RESULT err=2 tag=101 nentries=0 etime=0.000064982
[date] conn=2 op=3 UNBIND
[date] conn=2 op=3 fd=144 closed - U1

**Comment by winstan** [comment]
This may be related: https://pagure.io/freeipa/issue/7888
"The error message invalid attribute request indicates another LDAP protocol violation. 389-DS only emits that error message when the attribute list contains two or more empty attribute requests"

<blockquote><img src="/theme/static/favicon.ico?version=5.11.3" width="48" align="right"><div><strong><a href="https://pagure.io/freeipa/issue/7888">Issue #7888: FreeIPA returns "invalid attribute request" error with SRCH base="(null)" - freeipa - Pagure.io</a></strong></div></blockquote>

**Comment by uberbrady** [comment]
Those are excellent, thank you. I'm poking around the code for all this stuff now.

**Comment by winstan** [comment]
Ah ha, figured out a workaround. It has to do with the other fields on the form...
LDAP Active Flag
LDAP Employee Number
LDAP Email

If I fill any 2 of these out, then the "Test LDAP Synchronization" button works successfully.

So I guess the fix would be to exclude the blank attributes from the search request altogether...

**Comment by uberbrady** [comment]
Oh, excellent! Let's see if that helps other folks too.

**Comment by uberbrady** [comment]
@d0lm3n does @winstan 's workaround work for you?

**Comment by d0lm3n** [comment]
@winstan  Hello, eh yes LDAP Active Flag -> 1 working.. Thank you! :))
