### ISSUE TITLE
Changes to Label settings seem to be ignored

### ISSUE THREAD

**Issue by JW-IT** [grokability/snipe-it#8700]
#### Please confirm you have done the following before posting your bug report:

- [no] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Changing e.g. Font Size in the Label Settings is written to Database (table: settings, field: labels_fontsize), but on next open of the Labels Settings page still shows the old/default values (in our case 9pts, although we set it to 8pts).
Printing also shows no change in FontSize.

**To Reproduce**
1. Go to 'Admin -> Labels'
2. Change Font Size to (e.g.) '8pts'  (from the 9pts before)
3. Click "Save"
4. Reload the 'Labels Settings' page and see the old values.

**Expected behavior**
Changed label settings should be correctly represented the next time the Label settings page is opened. (especially when it is written to DB)

**Screenshots**
nope

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.5-pre build 5457
 - OS: Debian 10.4
 - Web Server: Nginx 1.14.2
 - PHP Version: 7.3.14-1~deb10u1 -- Laravel Version 6.18.10

**Desktop (please complete the following information):**
 - OS: Windows 2004
 - Browser: Firefox and Chrome
 - Version: current version of all desktop software involved

**Smartphone (please complete the following information):**
nope

**Error Messages**
nope

**Additional context**
- Upgraded from 4.9 to current version today. (Unclear if the problem already existed on 4.9, the issue became apparent only after - since we didn't play with label size/settings before)
- Installation: git + install.sh
- So far just the normal use without any apparent errors.

- For confirmation we did change the FontSize entry in the database (to e.g. 18) and it still didn't showed on the Label settings page.

**Comment by JW-IT** [comment]
just wanted to add that generating labels will adhere to the set FontSize (eg. 8pt in the database)
and looking at the "source" of the generated label page the FontSize is the same

so it seems to be "just" a problem with the Label-Setting page

**Comment by snipe** [comment]
@Godmartinz Can you take a look at this?

**Comment by Godmartinz** [comment]
I just wanted to point out that we have added an alternative label engine that should solve your issues.
