### ISSUE TITLE
Failed to load image

### ISSUE THREAD

**Issue by MuratDoganer** [grokability/snipe-it#8701]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After updating to v5.0.4 from v4.9.5, all the images - including favicon and logo fail to load. When you upload a new image you can see its preview, but when you save then go to dashboard etc the image link is broken suddenly and you get the error message "Failed to load image"

The image shows perfectly fine when you click the asset, so its only on the dashboard the issue is present!

**To Reproduce**
1. Update to v5.0.4 from v4.9.5 by running `php upgrade.php`
2.Issue is present after update

**Expected behavior**
The images to be as normal

**Screenshots**
![issue1](https://i.imgur.com/gbNC7In.png)
![issue2](https://i.imgur.com/I1KF0AE.png)
![issue3](https://i.imgur.com/KTFew4M.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.4
 - OS: Ubuntu
 - Web Server: nginx
 - PHP Version 7.4

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Chrome and Safari

**Comment by snipe** [comment]
What's the full URL of the image that's trying to be loaded?

**Comment by snipe** [comment]
My guess here is that you're missing the `http://` or `https://` from your `APP_URL` in your `.env`

**Comment by MuratDoganer** [comment]
Hmmm, I looked at the `.env` but i do have the `http://` in before my `App URL` however as you can see in the screenshot, the app is trying to load it from `assets.land.tech` which is missing the `http://` ... how does that happen?

**Comment by snipe** [comment]
No idea. Can you show me your .env (with DB info and mail settings redacted)?

**Comment by snipe** [comment]
> so its only on the dashboard the issue is present

Wait, we don't display images on the app dashboard. What URL are you talking about specifically?

**Comment by MuratDoganer** [comment]
````# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=[redacted]
APP_URL=http://assets.land.tech
APP_TIMEZONE='UTC'
APP_LOCALE=en-GB
MAX_RESULTS=500

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_DATABASE=snipeitdb
DB_USERNAME=snipeit
DB_PASSWORD=          
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_IS_PAAS=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=               
MAIL_PASSWORD                 
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=
MAIL_FROM_NAME=''
MAIL_REPLYTO_ADDR=               
MAIL_REPLYTO_NAME=''
MAIL_BACKUP_NOTIFICATION_ADDRESS=               

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false

# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false
REFERRER_POLICY=same-origin
ENABLE_CSP=false
CORS_ALLOWED_ORIGINS=null
ENABLE_HSTS=false

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHE_PREFIX=snipeit

# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT=null

# --------------------------------------------
# OPTIONAL: MEMCACHED SETTINGS
# --------------------------------------------
MEMCACHED_HOST=null
MEMCACHED_PORT=null

# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null

# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOG_MAX_FILES=10
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_CIPHER=AES-256-CBC
GOOGLE_MAPS_API=
BACKUP_ENV=true
LDAP_MEM_LIM=500M
LDAP_TIME_LIM=600```

**Comment by MuratDoganer** [comment]
> > so its only on the dashboard the issue is present
> 
> Wait, we don't display images on the app dashboard. What URL are you talking about specifically?

Sorry not the main dashboard, when viewing All Deployed Assets for example, or when selecting Accessories, Licences, Categories etc

But the moment you click into it, the images show fine - only on the parent page it doesn't show a link to the images (this includes the Logo, it doesnt load or save at all)

**Comment by snipe** [comment]
> this includes the Logo, it doesnt load or save at all

Meaning it doesn't load on the top of each page, you can't upload it, or both? If both, can you confirm that your Branding Settings Type is set to logo or logo+text, and if you cannot upload, can you tell me what error you get? (Check the app logs)

Also can you try upgrading to latest?

**Comment by MuratDoganer** [comment]
> > this includes the Logo, it doesnt load or save at all
> 
> Meaning it doesn't load on the top of each page, you can't upload it, or both? If both, can you confirm that your Branding Settings Type is set to logo or logo+text, and if you cannot upload, can you tell me what error you get? (Check the app logs)
> 


It uploads fine, it saves fine, and then when you reload the page it looks like this:

![logo](https://i.imgur.com/H2impk5.png)

And when you go back into Brand settings, all the logos have been removed and it looks blank, as if it wasn't saved at all in the first place. This is with the Type set to Logo.

> Also can you try upgrading to latest?

I tried this morning, it is now showing the following:

> Version v5.0.5-pre - build 5457 (master)

This was after doing a `git pull` and then running the rest of the update manually. No errors along the way at all

**Comment by snipe** [comment]
Okay, if you add this to your .env:

```
# --------------------------------------------
# REQUIRED: UPLOADED FILE STORAGE SETTINGS
# --------------------------------------------
PRIVATE_FILESYSTEM_DISK=local
PUBLIC_FILESYSTEM_DISK=local_public
```

and then clear your config cache: `php artisan config:clear` does anything change?

**Comment by snipe** [comment]
(Also we're up to v5.0.6 now)

**Comment by snipe** [comment]
Adding that block to your .env *shouldn't* matter. We don't add that block to our hosted customers because it defaults sanely. I *am* seeing two different ways of invoking the images, and it seems like `Storage::disk('public')->url($IMAGE_VARIABLE) ` isn't working where `{{ url('/') }}/uploads/assets/{{{ $IMAGE_VARIABLE }}}"` *does*,  but the latter is an artifact, and the `Storage::` method is the way everything should be working now.

**Comment by MuratDoganer** [comment]
> Okay, if you add this to your .env:
> 
> ```
> # --------------------------------------------
> # REQUIRED: UPLOADED FILE STORAGE SETTINGS
> # --------------------------------------------
> PRIVATE_FILESYSTEM_DISK=local
> PUBLIC_FILESYSTEM_DISK=local_public
> ```
> 
> and then clear your config cache: `php artisan config:clear` does anything change?

This fixed it....but I don't know why!

**Comment by snipe** [comment]
Great!

**Comment by pakorn269** [comment]
For solving this problem, I put APP_URL = http: //..../

**Comment by snipe** [comment]
@pakorn269 you should not do that - APP_URL should be your app url.

**Comment by jmarquezalfaro** [comment]
Saludos,
En mi caso pasaba algo similar, no cargaban las imágenes, me duplicaba la ip de SnipeIT:
http://snipe-ipv4/snipe-ipv4/uploads/avatars/avatar-p8ukUPnQOUZBsBJgTR.png

**Solución**:
APP_URL: Quitar el nombre o IP

cd /var/www/html/snipe/
sudo vim .env
y actualizar el archivo:

# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=xyzxyzxyz.....
**APP_URL=**  Quitar este campo!
APP_TIMEZONE='UTC'
APP_LOCALE=en
MAX_RESULTS=500


Reiniciar Apache
sudo systemctl restart httpd


![image](https://user-images.githubusercontent.com/33870645/114280976-5f554280-9a01-11eb-836c-4a61425f8b65.png)

![image](https://user-images.githubusercontent.com/33870645/114281054-cecb3200-9a01-11eb-8b07-63e95a213d13.png)

**Comment by triakasah** [comment]
I'm running snipe-it on docker, 
the image was loaded with HTTP://127.0.0.x:xxxx/.... URL

a bit frustrated, well, just in case anybody's looking for an answer
I edited the Asset Model file where it generates the image URL, located in app/Models/Asset.php

<img width="900" alt="Screenshot 2021-08-26 at 22 12 15" src="https://user-images.githubusercontent.com/11639780/130989187-4c49f96d-bcb3-4d7b-b585-9945350ab49f.png">

**Comment by snipe** [comment]
You should absolutely not have to edit any model files here. This is always a configuration issue.

**Comment by BeanHubbleday** [comment]
Adding the http:// to my APP_URL fixed things for me so thanks!

**Comment by ilterefex** [comment]
> My guess here is that you're missing the `http://` or `https://` from your `APP_URL` in your `.env`

thats solved my problem. Thanks snipe

**Comment by Arsh419** [comment]
Hi, I'm having the same issue while loading the image. I have tried both  APP_URL = http: //.. and # --------------------------------------------
# REQUIRED: UPLOADED FILE STORAGE SETTINGS
# --------------------------------------------
PRIVATE_FILESYSTEM_DISK=local
PUBLIC_FILESYSTEM_DISK=local_public

Please help me if there is anything else should I need to change in .env . 
Thanks

**Comment by fivelook** [comment]
Hello, I have the same problem after having updated from version 5.4.4 to the new version 6.0.12, the images of the models and categories are not shown.

Server docker.

**Comment by snipe** [comment]
@fivelook you have not provided us with any additional information about your setup that would allow us to help you. This issue is closed and doesn't seem directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)

**Comment by pedramaghaii** [comment]
hi 
add command and Done
sudo apt install php-{opcache,pdo,bcmath,bz2,calendar,ctype,exif,ffi,fileinfo,ftp,gd,iconv,intl,json,mbstring,mysqli,phar,posix,readline,shmop,sockets,sysvmsg,sysvsem,sysvshm,tokenizer,zip,curl,ldap} php-cli git unzip

**Comment by AndrewGeringCartica** [comment]
In case you are using docker-compose you need to config additional docker volume  uploads for snipe-it service uploads directory:
Example:
snipeit:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: snipeit
    restart: always
    ports:
    - "8000:80"
    volumes:
    - logs:/var/www/html/storage/logs
    - uploads_data:/var/www/html/public/uploads
    depends_on:
    - mariadb
    - redis
    env_file:
    - .env.docker
    networks:
    - snipeit-backend

**Comment by Morg-sys** [comment]
Hi, 

I have a problem when I upload image on accessory menu eror 500. 
Nothing on access.log. 

I add in .env file then restart apache service. 
# --------------------------------------------
# REQUIRED: UPLOADED FILE STORAGE SETTINGS
# --------------------------------------------
PRIVATE_FILESYSTEM_DISK=local
PUBLIC_FILESYSTEM_DISK=local_public

No sucess. 

Can you help me please ? 

Thanks for all/

**Comment by AndrewGeringCartica** [comment]
Sure, in case you are using dokcer-compose, you just have to add volume to your docker-compose.yaml file. 
My docker-compose.yaml example:
```services:
  snipeit:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: snipeit
    restart: always
    ports:
    - "8000:80"
    volumes:
    - logs:/var/www/html/storage/logs
    - uploads_data:/var/www/html/public/uploads
    depends_on:
    - mariadb
    - redis
    env_file:
    - .env.docker
    networks:
    - snipeit-backend

  mariadb:
    image: mariadb:10.6.4-focal
    restart: always
    volumes:
    - db:/var/lib/mysql
    env_file:
    - .env.docker
    networks:
    - snipeit-backend
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.5-buster
    restart: always
    networks:
    - snipeit-backend

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
    - 1025:1025
    - "8025:8025"
    networks:
    - snipeit-backend


volumes:
  db: {}
  logs: {}
  uploads_data: {}


networks:
  snipeit-backend: {}
  ```

**Comment by spineyguy** [comment]
I ran the upgrade as instructed using git.  I had the "500 error" when uploading any images. My original working .env had:
IMAGE_LIB=imagemagick
But, after seeing @snipe question about "gd" being another option, I tried changing that setting to:
IMAGE_LIB=gd

Then ran:
php artisan config:clear

That fixed my image upload problems.  I was unaware that my image library had changed during the upgrade.
Thank you for all this discusiion!

**Comment by snipe** [comment]
The image library didn't change - you've always had the option of both. Imagemagick and gd do almost the same thing, that's why we support both. It's more of a "what shared server are you on and what do they support" type of thing. We try to keep this easy enough that non-sysadmins can run it. IMHO glib is better, but I'm old and cranky so take that for what it's with ;)
