### ISSUE TITLE
Cannot update asset tag increment

### ISSUE THREAD

**Issue by dakide** [grokability/snipe-it#8703]
Version v5.0.4 - build 5452 (master)

I cannot update the Next auto-increment in the Update Asset Tag Settings page.

I put in the new tag number, click Save, get the green Success message.

When I go back to the settings page, the Next auto-increment is the old one.

-- Screenshots 

Go to the settings page
![image](https://user-images.githubusercontent.com/53129107/98597613-32c1c100-22d1-11eb-9e5f-ef653cc09e6a.png)

Then change the number
![image](https://user-images.githubusercontent.com/53129107/98597562-1e7dc400-22d1-11eb-8e46-93d1bc4aa946.png)

Success message
![image](https://user-images.githubusercontent.com/53129107/98597583-263d6880-22d1-11eb-93aa-0cebbf219e30.png)

Go back into settings to confirm, old tag number.
![image](https://user-images.githubusercontent.com/53129107/98597651-3ce3bf80-22d1-11eb-951a-66c993f0bf83.png)

**Comment by dakide** [comment]
Works after updating to v5.0.6

**Comment by snipe** [comment]
Weird - we didn't actually change anything there. ¯\_(ツ)_/¯

Thanks for letting us know tho!
