### ISSUE TITLE
Separate INSTALLATION MANUAL by OS

### ISSUE THREAD

**Issue by yosiasz** [grokability/snipe-it#8710]
**Server :**
 - Snipe-IT Version : 4.9.5
 - OS: Windows 2019
 - Web Server: IIS
 - PHP Version : 7.3.13

**Is your feature request related to a problem? Please describe.**
Parsing what applies to my OS is very difficult to sort in the Installation Manual

**Describe the solution you'd like**
It would be nice if the installation for each OS type is separate

**Describe alternatives you've considered**
Creating my own install documentation

**Additional context**
The more frustrating an installation manual the more quicker people are turned off from this awesome product

**Comment by snipe** [comment]
We already provide a breakdown by OS. 

<img width="247" alt="Screen Shot 2020-11-10 at 7 35 09 AM" src="https://user-images.githubusercontent.com/197404/98695263-4ac42f80-2327-11eb-8850-6c4173dcd306.png">

**Comment by yosiasz** [comment]
yes, but that is just the server configuration. I meant to say end to end

**Comment by snipe** [comment]
Maintaining that would be confusing and prone to problems, since 98% of the configurations are the same across all platforms. MySQL DB dump path is about the only thing in terms of configuration that is different on Windows.
