### ISSUE TITLE
Purge Log-In Attempts

### ISSUE THREAD

**Issue by GustelDE** [grokability/snipe-it#8711]
Hi,

is it possible to delete old "Log-In Attempts"? This table it now 19 pages long and shows entry from the very first beginning. We dont need that functionality at all.

Is it possbile to delete/purge old Log-In Attempts-records (lets say older than 1 month) or disable that functionaliy at all?

Thanks

**Comment by snipe** [comment]
Can you not just ignore it?

**Comment by GustelDE** [comment]
I think I have to do that ;)
But I am in general not a friend of growing tables without use (for us) and without the option to delete these data.

Please see this as an wish for an upcoming version. Maybe a "clear data" button or so.

**Comment by snipe** [comment]
My only hesitance there is that we've had customers who never paid attention to that log, and would probably have disabled it - and then had a rogue employee (super admin) who was fired, login and delete AND purge (AND delete ALL backups) of everything they had. We ended up having to provide that login info to assist them in the charges they're bringing up against them. 

You never think you need that stuff until you do. :-/

**Comment by UnlimitedCookies** [comment]
I would say that a `php artisan` command would be sufficient. That way the above mentioned employee could only do such things if he has shell access (and when it has come to that point he can already do whatever he wants).

**Comment by snipe** [comment]
This is now on develop.

<img width="557" alt="Screen Shot 2020-11-12 at 3 20 11 PM" src="https://user-images.githubusercontent.com/197404/99008234-9aa72000-24fa-11eb-849a-058f05c15367.png">
