### ISSUE TITLE
Could not show the "people" list after moving the Snipe-IT to new server.

### ISSUE THREAD

**Issue by microsea** [grokability/snipe-it#8713]
Server (please complete the following information):

Snipe-IT Version: Version v4.6.16 - build 4018  Upgrade to   Version v5.0.5-pre - build 5457 (master) 
OS: CentOS 7
Web Server:  - 
PHP Version: -
Docker images: snipe/snipe-it
database server: Mysql

To Reproduce
1. Dump mysql database snipeit to SQL file
2. Start Any version snipeit and mysql docker image 
3. Import the SQL file into new database
4. Goto the "People", it is empty,but it can "export" all people to a local file.

Please confirm you have done the following before posting your bug report:
[ x] I have enabled debug mode
[ x] I have read checked the Common Issues page

Describe the bug:
When I wanted to migrate Snipe-it to a new server, I dumped the old mysql data into an SQL file and imported IT into the newly installed system. Everything was fine except the "People" list was empty. Exactly the same situation as this issue:
https://github.com/snipe/snipe-it/issues/4975
But it does not have a clear solution. So, I turn on Debug mode and find this error message:

![2](https://user-images.githubusercontent.com/5702017/98738805-1f5c3780-235d-11eb-822f-c7401b55e431.jpg)

As prompted, I find that the **accessories_users** table is missing a **note** field. During the process of exporting and importing mysql data, I did not edit or change anything, so after I manually added the "note" field to the accessories_users table, 
`alter table accessories_users add column note text default NULL;`
![1](https://user-images.githubusercontent.com/5702017/98739332-fdaf8000-235d-11eb-83bf-e6ada0f8be75.jpg)
the data in People appeared and everything returned to normal.

I used to think it was the SnipeIT version or mysql version problem, but I encountered this situation in moving between the same version, so I'm not sure why it happend. I just feel the need to let people know what I meet and how to deal with it.

**Comment by snipe** [comment]
Did you run migrations?

**Comment by microsea** [comment]
Yes, I've tried running `php artisan migrations` command, it returned successful information, but there were no changes to display the People list. The only thing that works for me is to add the "note" field in the accessories_users table.

**Comment by snipe** [comment]
`accessories_note` is a new field. If it's not there, migrations did not complete correctly.

**Comment by snipe** [comment]
Also the command is `php artisan migrate`, not `php artisan migrations`

**Comment by snipe** [comment]
> so after I manually added the "note" field to the accessories_users table, alter table accessories_users add column note text default NULL;

You should never ever add columns manually. We have migrations to handle that. If you try to run migrations again, you'll get an error, since that column already exists and the migration will try to create it again.
