### ISSUE TITLE
Cannot list Unaccepted Assetsafter update 4.9.4 to 5.0.6.

### ISSUE THREAD

**Issue by thumperest** [grokability/snipe-it#8715]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Dear All, we realy loved the Snipe-IT system and we are using it at our core. After the upgrade from 4.9.4 to 5.0.6 the list of Unaccepted Assets report shows the real list for 1 second and turns to a blank page after that. I rebooted the server, used Incognito browser but no luck. I added the screenshots with the shown list for 1 second and the afterlist. 

I also paseted the console errors from the browser: 

Console errors shown as: 
Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Feature-Policy header: Unrecognized feature: 'animations'.
Error with Feature-Policy header: Unrecognized feature: 'battery'.
Error with Feature-Policy header: Unrecognized feature: 'display-capture'.
Error with Feature-Policy header: Unrecognized feature: 'legacy-image-formats'.
Error with Feature-Policy header: Unrecognized feature: 'oversized-images'.
Error with Feature-Policy header: Unrecognized feature: 'publickey-credentials'.
Error with Feature-Policy header: Unrecognized feature: 'unsized-media'.
Error with Feature-Policy header: Unrecognized feature: 'vibrate'.
Error with Feature-Policy header: Unrecognized feature: 'wake-lock'.

**To Reproduce**

**Expected behavior**
Showing the list as suggested. 

**Screenshots**
![Shows1Second](https://user-images.githubusercontent.com/73989622/98785014-04490080-240d-11eb-85cc-608de42fc1e1.png)
![After1Second](https://user-images.githubusercontent.com/73989622/98785160-38bcbc80-240d-11eb-9d9c-792715b4643a.JPG)

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.6 build 5526 (g8a7cd8764)
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server: [e.g. Apache, IIS] Apache version: Apache/2.4.39
 - PHP Version 7.3.13

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 86.0.4240.183

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by thumperest** [comment]
Dear All,

I checked from your Demo also, same issue appears. I think It'a cummon bug. 
I chenged the browser to firefox but same issue. 

![Shows1Second](https://user-images.githubusercontent.com/73989622/98789621-95bb7100-2413-11eb-805a-6020e517a4d3.png)
![After 1 second](https://user-images.githubusercontent.com/73989622/98789746-c7ccd300-2413-11eb-9219-a370b941fcb2.JPG)

**Comment by diegogarciadev** [comment]
Same here #8626

**Comment by snipe** [comment]
I am able to reproduce this - looking at it now

**Comment by thetiagomatos** [comment]
**Same here, version 5.0.9:
Chrome console:** 
Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Feature-Policy header: Unrecognized feature: 'animations'.
Error with Feature-Policy header: Unrecognized feature: 'battery'.
Error with Feature-Policy header: Unrecognized feature: 'display-capture'.
Error with Feature-Policy header: Unrecognized feature: 'legacy-image-formats'.
Error with Feature-Policy header: Unrecognized feature: 'oversized-images'.
Error with Feature-Policy header: Unrecognized feature: 'publickey-credentials'.
Error with Feature-Policy header: Unrecognized feature: 'unsized-media'.
Error with Feature-Policy header: Unrecognized feature: 'vibrate'.
Error with Feature-Policy header: Unrecognized feature: 'wake-lock'.

**Comment by snipe** [comment]
@thetiagomatos Those policies should not prevent anything from loading there. (We have hundreds - probably thousands od users and customers who use Chrome.) It throws it up as an error, but it doesn't actually block other things from loading.

There seems to be [some debate](https://bugs.chromium.org/p/chromium/issues/detail?id=911042#c2) as to whether or not the "spec was misleading" in the Chrome community, but 

- Can you load that page in the demo in Chrome? https://demo.snipeitapp.com/
- Is that the only page that isn't loading for you in Chrome? (If it's the only page that's not loading, it's not the security headers, since those are on every page.)

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by thetiagomatos** [comment]
> @thetiagomatos Those policies should not prevent anything from loading there. (We have hundreds - probably thousands od users and customers who use Chrome.) It throws it up as an error, but it doesn't actually block other things from loading.
> 
> There seems to be [some debate](https://bugs.chromium.org/p/chromium/issues/detail?id=911042#c2) as to whether or not the "spec was misleading" in the Chrome community, but
> 
> * Can you load that page in the demo in Chrome? https://demo.snipeitapp.com/
> * Is that the only page that isn't loading for you in Chrome? (If it's the only page that's not loading, it's not the security headers, since those are on every page.)
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/3f2d9feccae7cd6385c9fc30a080435adee7ce46d66d566c7341352cc371e9e1/68747470733a2f2f64656d6f2e736e69706569746170702e636f6d2f66617669636f6e2e69636f">**[Snipe-IT Asset Management Demo](https://demo.snipeitapp.com/)**

Yeah, everything is good with the demo.
I opened an issue so it's easier for you guys to check this out. #8817 
It seems that i can't save any changes on settings.

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
