### ISSUE TITLE
Harcoded strings

### ISSUE THREAD

**Issue by diegogarciadev** [grokability/snipe-it#8716]
I've found several string without translation or hardcoded:

**Here an example of files we have modified localy:**

app/Notifications/CheckinAccessoryNotification.php
```
-            ->subject('Accessory checked in');
+            ->subject(trans('mail.Confirm_Accessory_Checkin'));
```

app/Notifications/CheckinAssetNotification.php
```
-            ->subject('Asset checked in');
+            ->subject(trans('mail.Confirm_Asset_Checkin'));
```

app/Notifications/CheckinLicenseSeatNotification.php
```
-            ->subject('License checked in');
+            ->subject(trans('mail.Confirm_license_Checkin'));
```

resources/views/account/accept-asset.blade.php
```
-                I accept
+                {{ trans('general.i_accept') }}
```

resources/views/account/accept/create.blade.php
```
                 <input type="radio" name="asset_acceptance" id="accepted" value="accepted">
-                I accept
+                {{ trans('general.i_accept') }}
               </label>
             </div>

             <div class="radio">
               <label>
                 <input type="radio" name="asset_acceptance" id="declined" value="declined">
-                I decline
+                {{ trans('general.i_decline') }}
```

resources/views/notifications/markdown/asset-requested.blade.php
resources/views/notifications/markdown/checkin-accessory.blade.php
resources/views/notifications/markdown/checkin-asset.blade.php
resources/views/notifications/markdown/checkin-license.blade.php
resources/views/notifications/markdown/checkout-accessory.blade.php
resources/views/notifications/markdown/checkout-consumable.blade.php
resources/views/notifications/markdown/checkout-license.blade.php
resources/views/notifications/markdown/report-expected-checkins.blade.php
```
-Thanks,
+{{ trans('mail.thanks') }},
```

**Comment by snipe** [comment]
We welcome your pull request :)

**Comment by diegogarciadev** [comment]
Hello, not all strings are created in trans files... I don't know how to proceed

**Comment by snipe** [comment]
Please check our documentation on translations. Create the strings in English, we’ll upload then and let our wonderful community translators do the rest.

**Comment by snipe** [comment]
Sorry, on mobile so it took me a sec: https://snipe-it.readme.io/docs/translations

If there is a particular language you’d like to be a translator for, just let me know. Happy to set that up 

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/translations">Translations</a></strong></div><div>Traduci! 翻訳！Oversette! Traduire! 번역하기! แปล! ¡Traducir! Przetłumacz! Übersetzen!</div></blockquote>

**Comment by snipe** [comment]
Language is difficult, and while we try really hard to make sure we translate everything, we definitely don’t. I’d love and PRs for localization. It’s been on my list forever

**Comment by dampfklon** [comment]
I have an open Issue #8233 with working pull requests open #8234 #8235 #8236 #8237 about these strings

**Comment by diegogarciadev** [comment]
> I have an open Issue #8233 with working pull requests open #8234 #8235 #8236 #8237 about these strings

Here you have the response @snipe

**Comment by snipe** [comment]
This has been merged into develop - thanks, @dampfklon!
