### ISSUE TITLE
Uploaded filename on Asset is different as License

### ISSUE THREAD

**Issue by roratonet** [grokability/snipe-it#8719]
**Is your feature request related to a problem? Please describe.**
When I upload a file under an Asset, it is shown with the following pattern:
`hardware-<id>-<hash>-<originalfilename>.<extension>`

Under a License:
`license-<dateandhour>-<hash>.<extension>
`
**Describe the solution you'd like**
Is it possible to maintain the `<originalfilename>` in the License Filename aswell?

**Comment by snipe** [comment]
This is now on develop
