### ISSUE TITLE
Asset Maintenance - Asset Field has the Asset Tag two times

### ISSUE THREAD

**Issue by roratonet** [grokability/snipe-it#8721]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Under **Create/Update Asset Maintenance**, the **Asset Tag** is shown two times under **Asset Name**

**To Reproduce**
https://demo.snipeitapp.com/hardware/maintenances/create?asset_id=32

**Expected behavior**
The Asset Tag should be shown only once

**Screenshots**
https://demo.snipeitapp.com/hardware/maintenances/create?asset_id=32

**Comment by snipe** [comment]
I'm not sure I follow. Can you explain a little further?

<img width="830" alt="Screen Shot 2020-11-12 at 2 51 59 PM" src="https://user-images.githubusercontent.com/197404/99006025-ac86c400-24f6-11eb-8867-0dc3f7d0cab4.png">

<img width="877" alt="Screen Shot 2020-11-12 at 2 52 42 PM" src="https://user-images.githubusercontent.com/197404/99006074-bf00fd80-24f6-11eb-94e5-9ad40c343d36.png">

**Comment by roratonet** [comment]
@snipe sure

[Here](https://demo.snipeitapp.com/hardware) I have the list of all assets:

<img width="488" alt="Screenshot 2020-11-13 at 15 00 14" src="https://user-images.githubusercontent.com/22026195/99080427-98f45f80-25c1-11eb-85c8-1e466478fb49.png">

I will select the **MacBook Pro** with **Asset Tag** [372555278](https://demo.snipeitapp.com/hardware/1) and **no Asset Name** set, and create a maintenance.

<img width="885" alt="Screenshot 2020-11-13 at 15 01 33" src="https://user-images.githubusercontent.com/22026195/99080461-a3165e00-25c1-11eb-9c6c-65df5f4d0f41.png">

...Detailed view...

<img width="869" alt="Screenshot 2020-11-13 at 15 01 53" src="https://user-images.githubusercontent.com/22026195/99080516-b4f80100-25c1-11eb-80fc-b30544b991b9.png">

All fine.

I will select the **Optiplex Desktop** with **Asset Tag** [1408495990](https://demo.snipeitapp.com/hardware/2) and **Asset Name** set to **test**, and create a maintenance.

<img width="871" alt="Screenshot 2020-11-13 at 15 03 15" src="https://user-images.githubusercontent.com/22026195/99080571-c50fe080-25c1-11eb-8286-6a22a0b54c75.png">

**Asset Tag** is show twice because of the presence of **Asset Name** set to **test**

**Comment by jackka** [comment]
Reproducible. Confirmed
![Video_2020-12-21_130316](https://user-images.githubusercontent.com/6271335/102765617-e36db680-438d-11eb-8c32-37c0730135dc.gif)

**Comment by snipe** [comment]
Ah, got it - this only happens when the asset has a *name*. I can confirm this is happening on our end too.

**Comment by snipe** [comment]
The fix is on develop and will be in the next release - thanks for the extra debugging info :)
