### ISSUE TITLE
Ability to specify custom db port in .env

### ISSUE THREAD

**Issue by yosiasz** [grokability/snipe-it#8724]
- Snipe-IT Version : 4.9.5
 - OS: Windows
 - Web Server: IIS
 - PHP Version : 7.13

Unable to specify custom port in .env

**Describe the solution you'd like**
Would like to be able to specify my own port rather than the default 3306 

**Describe alternatives you've considered**
None

**Additional context**
I would be running both MariaDb and MySql on same server. Cant run both on 3306 
and cant specify a different port for a different instance of snipeit

Thanks!

**Comment by snipe** [comment]
`DB_PORT` in your .env
