### ISSUE TITLE
Upgrading from 4.9.6 to 5.0.6 Failed...Snipe IT is down

### ISSUE THREAD

**Issue by ZephyriusOne** [grokability/snipe-it#8725]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am receiving errors during the upgrade process using php upgrade.php.

**To Reproduce**
Run php upgrade.php 

**Expected behavior**
Trying to get a successful upgrade from 4.9.6 to 5.0.6

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.9.6 -> 5.0.6
 - OS: Windows 7 x64
 - Web Server: XAMPP Control Panel 3.2.2
 - PHP Version 7.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**I am trying to upgrade using php upgrade.php and I ran into some issues. First, LDAP was not enabled in php.ini, which I resolved by enabling. Now, I am getting the below errors. Snipe IT now will not load.**

C:\xampp\htdocs\snipe-it>php upgrade.php
Skipping user check as it is not supported on Windows
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- check your PHP version and extension requirements
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (7.3.0) is at least 7.2.0 - continuing...
FYI: The php.ini used by this PHP is: C:\xampp\php\php.ini

Checking Required PHP extensions...

ΓêÜ bcmath is installed!
ΓêÜ curl is installed!
ΓêÜ fileinfo is installed!
ΓêÜ gd is installed!
ΓêÜ json is installed!
ΓêÜ ldap is installed!
ΓêÜ mbstring is installed!
ΓêÜ mysqli is installed!
ΓêÜ openssl is installed!
ΓêÜ PDO is installed!
ΓêÜ tokenizer is installed!
ΓêÜ xml is installed!
ΓêÜ zip is installed!

PHP extension MISSING: gd or imagick
PHP extension MISSING: php-ldap
PHP extension MISSING: php-json
PHP extension MISSING: php-fileinfo
PHP extension MISSING: php-openssl
--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

The environment file is invalid!
Failed to parse dotenv file due to an unexpected escape sequence. Failed at ["C:
\xampp\mysql\bin"].
--

--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

The environment file is invalid!
Failed to parse dotenv file due to an unexpected escape sequence. Failed at ["C:
\xampp\mysql\bin"].
--
--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
Already on 'master'
-- No local changes to save
-- Your branch is up to date with 'origin/master'.
-- Already up to date.

--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

ΓêÜ No bootstrap/cache/compiled.php, so nothing to delete.
ΓêÜ No bootsrap/cache/services.php, so nothing to delete.
ΓêÜ No bootstrap/cache/config.php, so nothing to delete.

The environment file is invalid!
Failed to parse dotenv file due to an unexpected escape sequence. Failed at ["C:
\xampp\mysql\bin"].
The environment file is invalid!
Failed to parse dotenv file due to an unexpected escape sequence. Failed at ["C:
\xampp\mysql\bin"].
The environment file is invalid!
Failed to parse dotenv file due to an unexpected escape sequence. Failed at ["C:
\xampp\mysql\bin"].
The environment file is invalid!
Failed to parse dotenv file due to an unexpected escape sequence. Failed at ["C:
\xampp\mysql\bin"].
-- -- -- --
--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump

--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

The environment file is invalid!
Failed to parse dotenv file due to an unexpected escape sequence. Failed at ["C:
\xampp\mysql\bin"].

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

ΓêÜ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

The environment file is invalid!
Failed to parse dotenv file due to an unexpected escape sequence. Failed at ["C:
\xampp\mysql\bin"].
--
---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!
--------------------------------------------------------

Any help would be greatly appreciated, as I am an idiot and ran this without a proper backup. Sigh...

**Comment by ZephyriusOne** [comment]
I figured it out...I had to makes changes in the .env file.
First, the DB_DUMP_PATH from "C:\xampp\mysql\bin" to `"C:\\xampp\\mysql\\bin"`.

Second, I had to fix REDIS_PORT=null, as for some reason it was set to REDIS_PORT-null. No idea why. After these changes the upgrade worked just fine. I was worried for a bit there, as this is in production. Time to make backups! XD

One thing I want to know, is there a downside to not having certain plugins? I noticed the below says MISSING...any feedback as to what this will affect? It also shows them installed right above them?

ΓêÜ bcmath is installed!
ΓêÜ curl is installed!
**ΓêÜ fileinfo is installed!**
**ΓêÜ gd is installed!**
**ΓêÜ json is installed!**
**ΓêÜ ldap is installed!**
ΓêÜ mbstring is installed!
ΓêÜ mysqli is installed!
**ΓêÜ openssl is installed!**
ΓêÜ PDO is installed!
ΓêÜ tokenizer is installed!
ΓêÜ xml is installed!
ΓêÜ zip is installed!

PHP extension MISSING: gd or imagick
PHP extension MISSING: php-ldap
PHP extension MISSING: php-json
PHP extension MISSING: php-fileinfo
PHP extension MISSING: php-openssl

**Comment by snipe** [comment]
> One thing I want to know, is there a downside to not having certain plugins?

The required plugins are definitely required - stuff will break in weird ways if they're not. (That's why we added the extension check.)

You can ignore the `PHP extension MISSING: gd or imagick` stuff - that was a duplicate code block that's since been fixed.

**Comment by MSWork79** [comment]
.env file, `REDIS_PORT-null` to `REDIS_PORT=null`
Re-ran `php upgrade.php`
Success.

That was scary. Not sure how that got there, maybe an old generated .env file or something. Glad it was an easy fix. Running from an Ubuntu environment. Landed here while troubleshooting why it was failing step 7 for migrating the database and "The environment file is invalid!" error.

**Comment by andreasoc** [comment]
thanks ! I've h ad the same problem
