### ISSUE TITLE
Unable to save any SAML Settings in Windows Server

### ISSUE THREAD

**Issue by kennj3** [grokability/snipe-it#8727]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Unable to save any settings under the SAML settings including the IdP metadata file.  Regardless of whether SAML is enabled, any data is uploaded or any other settings are checked, upon saving, I get a 500 error.  All other capabilities seem to be working in Snipe-IT.

**To Reproduce**
1. Go to Settings/SAML
2. Click on Save at the bottom with or without changes
3. Error 500 is displayed

**Expected behavior**
I would expect the settings to save

**Server (please complete the following information):**
Snipe-IT Version 5.0.4 and 5.0.6
OS: Windows Server 2016
Web Server: IIS 10.0
PHP Version 7.4.11; also tried 7.2.34

**Desktop (please complete the following information):**
OS: Windows Server 2016 and Mac
Browser: Chrome, Safari, Firefox, IE
Version: x64

**Error Messages**
- Error 500 displayed on browser page
- openssl_csr_sign(): cannot get CSR from parameter 1 when in Debug mode
- Post error for admin/saml when using the browser development tools

**Additional context**
- Is this a fresh install or an upgrade?  Manual Upgrade
- Besides the Predefined Kits issue not working #8723 (already posted by someone), the other Snipe-IT capabilities work well
- Database not manually edited
- SAML does seem to work in a Linux environment, but our production environment is Windows where it is not working in multiple Windows environments w/ IIS.

![SAML_Error](https://user-images.githubusercontent.com/62330950/98945189-c9e86d80-24b7-11eb-9487-4e7dd11c5d8b.PNG)

**Comment by LSNIGHTSHOT** [comment]
Please refer to issue #8654 

Thanks

**Comment by kennj3** [comment]
That solution worked great!  Thank you.
