### ISSUE TITLE
[Feature request] LDAP Sync - Add Merge/Replace choice when doing a sync

### ISSUE THREAD

**Issue by dakide** [grokability/snipe-it#8729]
- v5.0.6

**Is your feature request related to a problem? Please describe.**
During an LDAP sync, fields that have been changed in SnipeIT are overwritten with the field from AD

**Describe the solution you'd like**
I'd be nice to have an option in the LDAP configruation that would enable/disable a function to have AD merge fields instead of replace when doing a sync. 
For example, my AD org puts a generic company phone number for employees. If I change the SnipeIT phone number to a cell phone for example, the LDAP sync reverts it back to the company number from AD.
Having a Merge would mean the SnipeIT admin must decide which field to keep - AD or SnipeIT.

**Describe alternatives you've considered**
I was not able to find a workaround within the system.

Thanks!

**Comment by uberbrady** [comment]
I mean, my hope would be that you could just go into AD and put in the cell # for the employee into their AD record, and then the sync would just handle it - but I've worked in large enough enterprises to know that that isn't always going to fly.

If we had proper field-mapping for **every** Snipe-IT field that existed (which we don't), you'd be able to just blank out phone number and then Snipe-IT would do what you want (see: #8741 )

Would that work for you? If so, I'll close this, but reference it in that other ticket so we have a real-world example to point to.

**Comment by dakide** [comment]
@uberbrady Sure that might work, go ahead and close this. Thanks!

**Comment by uberbrady** [comment]
Closing this to keep discussion centered in the 'potential improvements' ticket.
