### ISSUE TITLE
Updated update.php - would love some testers!

### ISSUE THREAD

**Issue by snipe** [grokability/snipe-it#8731]
Hi folks - I've made a few changes to the `update.php` on master/develop, which should hopefully help those users who are running into weird errors because they are missing some required PHP extensions. (The requirements haven't really changed in a long time, but you could get away with not having a few of them in earlier versions.)

I'd love if some folks could kick it around a little. I'd like to tag another release this week, but I'd like to have a few different people test it on their own environments to make sure everything works as expected. 

If you are missing some extensions, the output would look something like this:

```
✨snipe@deepthought✨$ php upgrade.php
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- check your PHP version and extension requirements
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (7.2.8) is at least 7.2.0 - continuing...
FYI: The php.ini used by this PHP is: /Library/Application Support/appsolute/MAMP PRO/conf/php7.2.8.ini

Checking Required PHP extensions...

--------------------- !! ERROR !! ----------------------
✘ MISSING PHP EXTENSION: farts
--------------------------------------------------------

You have the following extensions installed:

- Core
- date
- libxml
- openssl
- pcre
- sqlite3
- zlib
- bcmath
- bz2
- calendar
- ctype
- curl
- dom
- hash
- fileinfo
- filter
- ftp
- gd
- SPL
- iconv
- intl
- json
- ldap
- mbstring
- session
- standard
- mysqlnd
- PDO
- pdo_mysql
- pdo_sqlite
- Phar
- posix
- readline
- Reflection
- mysqli
- SimpleXML
- soap
- sockets
- sodium
- exif
- tokenizer
- wddx
- xml
- xmlreader
- xmlwriter
- xsl
- zip
- imap
- gettext
- pgsql
- pdo_pgsql
------------------------- :( ---------------------------
ABORTING THE INSTALLER
Please install the extensions above and re-run this script.
------------------------- :( ---------------------------
```

If you have the required extensions, the output should look something like this:

```
✨snipe@deepthought✨ $ php upgrade.php 
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- check your PHP version and extension requirements
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (7.2.8) is at least 7.2.0 - continuing...
FYI: The php.ini used by this PHP is: /Library/Application Support/appsolute/MAMP PRO/conf/php7.2.8.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ openssl is installed!
√ PDO is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit-local...
Determining files to backup...
Zipping 202 files and directories...
Created zip containing 202 files and directories. Size is 8.85 MB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!


--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.


--------------------------------------------------------
STEP 4: Pulling latest from Git (features/check_extensions_in_upgrade_script branch):
--------------------------------------------------------

Git is installed.
Already on 'features/check_extensions_in_upgrade_script'
-- -- No local changes to save
-- Your branch is up to date with 'origin/features/check_extensions_in_upgrade_script'.
-- Already up to date.

--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ Deleting bootstrap/cache/services.php. It it no longer used.
√ No bootstrap/cache/config.php, so nothing to delete.
-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar - trying globally.

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
11 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Generated optimized autoload files containing 5498 classes


--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

-- Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!
--------------------------------------------------------
```

**Comment by denzfarid** [comment]
now I have tried the upgrade.php script

<img width="663" alt="image" src="https://user-images.githubusercontent.com/1294403/99048321-fee3e580-25c7-11eb-9bfc-7ac9d32e3309.png">

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1294403/99048394-13c07900-25c8-11eb-8480-3c960b0f81fe.png">

**Comment by snipe** [comment]
Looks great, thanks @denzfarid!

**Comment by jovibroz** [comment]
Works great! No other issues than my normal f***** u* Composer install. (Can it be easily fixed btw?)

--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER! 
--------------------------------------------------------

This script will attempt to: 

- check your PHP version and extension requirements 
- do a git pull to bring you to the latest version 
- run composer install to get your vendors up to date 
- run migrations to get your schema up to date 
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements: 
--------------------------------------------------------

Current PHP version: (7.4.3) is at least 7.2.0 - continuing... 
FYI: The php.ini used by this PHP is: /etc/php/7.4/cli/php.ini

Checking Required PHP extensions... 

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database: 
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Determining files to backup...
Zipping 1065 files and directories...
Created zip containing 1065 files and directories. Size is 14.98 MB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!


--------------------------------------------------------
STEP 3: Putting application into maintenance mode: 
--------------------------------------------------------

-- Application is now in maintenance mode.

--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch): 
--------------------------------------------------------

Git is installed. 
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 14 (delta 10), reused 14 (delta 10), pack-reused 0
Unpacking objects: 100% (14/14), 1.18 KiB | 151.00 KiB/s, done.
From https://github.com/snipe/snipe-it
   df5cc7525..644084658  master     -> origin/master
   a87e615e7..644084658  develop    -> origin/develop
Already on 'master'
-- No local changes to save
-- Your branch is behind 'origin/master' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
-- Updating df5cc7525..644084658
Fast-forward
 app/Http/Controllers/AssetMaintenancesController.php | 6 +++---
 app/Models/Asset.php                                 | 1 +
 resources/views/asset_maintenances/edit.blade.php    | 2 +-
 3 files changed, 5 insertions(+), 4 deletions(-)

--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ No bootsrap/cache/services.php, so nothing to delete.
√ Deleting bootstrap/cache/config.php. It is no longer used.

-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

√ Local composer.phar detected, so we'll use that.

-- Updating local composer.phar

Cannot create cache directory /var/www/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache

                                                   
  [ErrorException]                                 
  fileowner(): stat failed for /var/www/.composer  
                                                   

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--set-channel-only] [--] [<version>]



Cannot create cache directory /var/www/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Deprecation Notice: Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/html/snipeit/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Cannot create cache directory /var/www/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
Deprecation Notice: Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/html/snipeit/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
11 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Generated optimized autoload files containing 5501 classes

--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use 
your upgraded Snipe-IT!
--------------------------------------------------------


<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by baditaflorin** [comment]
How can I run from inside the container? 
```
root@2877bac15f33:/var/www/html# php upgrade.php 

ERROR: This script should not be run as root/admin. Exiting.
```

**Comment by denzfarid** [comment]
> How can I run from inside the container?
> 
> ```
> root@2877bac15f33:/var/www/html# php upgrade.php 
> 
> ERROR: This script should not be run as root/admin. Exiting.
> ```

```
sudo su - snipeitapp
cd /var/www/{Snipeit-Directory}
php upgrade.php 
```
