### ISSUE TITLE
Typo in unaccepted_assets.blade.php

### ISSUE THREAD

**Issue by diegogarciadev** [grokability/snipe-it#8733]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
There is a typo in resources/views/reports/unaccepted_assets.blade.php

Line 51, should be: 

`<td>{{ ($assetItem->company) ? $assetItem->company->name : '' }}</td>`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by snipe** [comment]
This is now fixed on develop
