### ISSUE TITLE
Edit Component: validation.gt.numeric missing string

### ISSUE THREAD

**Issue by airforceixi** [grokability/snipe-it#8737]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Attempting to modify a component's details if all quantity is checked out fails with a validation.gt.numeric error.

**To Reproduce**
1. Go to 'Components'
2. Click on 'Edit' for any component that has a remaining quantity of 0.
3. Change any field _except_ quantity and click 'Save'. Example: add a Serial Number or amend the Component Name.

**Expected behavior**
Changes to be made without requiring adding quantity.

**Workaround**
1. Check-in component
2. Modify component details
3. Check-out component

**Screenshots**
![image](https://user-images.githubusercontent.com/32317421/99091579-16a67400-259e-11eb-9caa-600b1d191778.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.6 build 5526 (docker: snipe/snipe-it)
 - OS: Ubuntu 18.04.4 LTS (docker host)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Firefox 82.0.3

**Error Messages**
Inline error: validation.gt.numeric

**Additional context**
- Is this a fresh install or an upgrade? - **Configured 1 week ago, fresh docker image**
- What method you used to install Snipe-IT? - **docker**
- Include what you've done so far in the installation, and if you got any error messages along the way. - **Install has been flawless aside from this**
- Indicate whether or not you've manually edited any data directly in the database - **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Huh... weird how it's only doing that on edit. They *should* be using the same validation rules. 

I'lll take a look.

**Comment by snipe** [comment]
Fixed on develop

**Comment by airforceixi** [comment]
Thanks for the quick fix. Confirming it is now functioning properly.
