### ISSUE TITLE
Adding images to Locations fails using latest Docker Image

### ISSUE THREAD

**Issue by baditaflorin** [grokability/snipe-it#8745]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to Location
2. Click on a Location
3. Click update Location
4. Load Image

I also tried with or without this setting in my env file I use to start Docker

```
PRIVATE_FILESYSTEM_DISK=local
PUBLIC_FILESYSTEM_DISK=local_public
``` 

**Expected behavior**
I will see a small Thumbs image of the image. After I save and look in the category, I will see that the image do not load. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2330999/99151523-8b63d600-26a4-11eb-920c-9939b454ad90.png)

**Server (please complete the following information):**
 - Snipe-IT latest Docker version (updated today) 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
https://domain.com/uploads/locations/location-image-rfHIHSG1qd.jpg does not exist.

**Additional context**
Docker

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by baditaflorin** [comment]
```
root@2877bac15f33:/var/lib/snipeit/data/uploads# chmod 777 locations/
root@2877bac15f33:/var/lib/snipeit/data/uploads# ls -la
total 208
drwxr-xr-x 15 docker root  4096 Nov 14 15:51 .
drwxr-xr-x  4 root   root  4096 Oct 30 03:08 ..
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 accessories
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 avatars
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 barcodes
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 categories
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 companies
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 components
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 consumables
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 departments
-rw-r--r--  1 docker root  1722 Oct 30 04:33 favicon-uploaded.jpg
drwxrwxrwx  2 docker root  4096 Nov 14 09:51 locations
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 manufacturers
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 models
-rw-r--r--  1 docker root 47555 Oct 30 04:33 setting-email_logo-2Hc3uQ918X.jpg
-rw-r--r--  1 docker root 47555 Oct 30 04:33 setting-label_logo-UvwuJRRJAP.jpg
-rw-r--r--  1 docker root 47555 Oct 30 04:33 setting-logo-GkMHbeqdcx.jpg
drwxr-xr-x  2 docker root  4096 Oct 30 03:08 suppliers
drwxr-xr-x  3 docker root  4096 Nov 14 15:51 uploads
```

**Comment by baditaflorin** [comment]
```
root@2877bac15f33:/var/www/html/public# ls -la
total 68
drwxr-xr-x 1 docker root  4096 Nov 14 00:53 .
drwxr-xr-x 1 docker root  4096 Nov 14 17:31 ..
-rw-r--r-- 1 docker root  1026 Nov 14 00:51 .htaccess
drwxr-xr-x 1 docker root  4096 Nov 14 00:51 css
-rw-r--r-- 1 docker root 17910 Nov 14 00:51 favicon.ico
drwxr-xr-x 1 docker root  4096 Nov 14 00:51 img
-rw-r--r-- 1 docker root  1887 Nov 14 00:51 index.php
drwxr-xr-x 1 docker root  4096 Nov 14 00:51 js
-rw-r--r-- 1 docker root  3447 Nov 14 00:51 mix-manifest.json
-rw-r--r-- 1 docker root  2999 Nov 14 00:51 mix.js.map
-rw-r--r-- 1 docker root    26 Nov 14 00:51 robots.txt
lrwxrwxrwx 1 root   root    29 Nov 14 00:53 uploads -> /var/lib/snipeit/data/uploads
-rw-r--r-- 1 docker root  1076 Nov 14 00:51 web.config
root@2877bac15f33:/var/www/html/public# 

```

**Comment by baditaflorin** [comment]
I was able to identify that the code that is doing the loading of the image is here https://github.com/snipe/snipe-it/blob/df5cc7525e09be6b0ac77f7820b0236d863e07d4/app/Http/Requests/ImageUploadRequest.php

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by baditaflorin** [comment]
The problem is that the new photos are never loaded on the server, if I check to see if the files are written, I find that there are not. 

And I do not get any error, also cannot see nothing in the logs.

![image](https://user-images.githubusercontent.com/2330999/99154015-34b2c800-26b5-11eb-9a2c-8a14021724fd.png)

**Comment by ismaelnoble** [comment]
update your docker file to allow persistence in files uploaded. in my case my docker compose has 
...
  snipe-it:
    image: snipe/snipe-it
    env_file:
      - ./snipe-env
    restart: always
    volumes:
      - ./vols/snipe-vol/_data/:/config
      - ./vols/snipe-vol/_data/data/uploads:/var/lib/snipeit/data/uploads
    ports:
      - "9443:80"
      ....

where the local folder is connected to the docker web server. ymmv
