### ISSUE TITLE
Image not loading/Incorrect path in Asset QR Code section

### ISSUE THREAD

**Issue by samotelf** [grokability/snipe-it#8747]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When in "View Asset" the path to the image asset in the QR Code section is incorrect (/**uploads/uploads**/models/...) after updating to v5.0.6 from v4.9.5
However, when in "Assets" click asset name in device images and the image loads correctly.

**To Reproduce**

**Expected behavior**
Load the asset image.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.6
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version PHP 7.3.6 (cli) (built: May 28 2019 09:32:59) ( NTS )

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
**- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - YES**
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? - Upgrade
- What OS and web server you're running Snipe-IT on - CentOS7 + Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual (git)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.
![2_not_ok](https://user-images.githubusercontent.com/37087874/99158682-62a40680-26cd-11eb-9334-b6a9f4172cb5.png)
![2_ok](https://user-images.githubusercontent.com/37087874/99158684-659ef700-26cd-11eb-8b58-6fc6c2230dd2.png)

**Comment by thtech182** [comment]
I am having the opposite issue! Running in docker SnipeIT version 5.0.6 build 5600 (master).

The thumbnails in my asset list are broken. Inspecting shows they are pointing to mydomain.com/uploads/assets/[imagename].jpg. However, the images are actually at mydomain.com/uploads/uploads/assets/[imagename].jpg

The images are displaying correctly on the asset details page. Inspecting them shows them at the uploads/uploads/assets location.

I was having your issue and followed a guide to run 

`php artisan config:clear`
`php artisan config:cache`
`php artisan storage:link`

and I think that is what reversed it for me. I'm sure I made it worse...

EDIT: images appear to be broken everywhere except the asset details page. I have Accessories with images and they are broken in the list and the details page.

**Comment by zementente** [comment]
Same here, 
one model details the path to image is not correct
![image](https://user-images.githubusercontent.com/9779498/99320400-d5e37f00-286b-11eb-9f7d-70900ba58c3b.png)
on mostly every other site the path is correct and image is showing correct
![image](https://user-images.githubusercontent.com/9779498/99320450-f27fb700-286b-11eb-900b-fc7ec067ba23.png)

**Comment by samotelf** [comment]
Ooof, glad it’s not me.
Actually, the same happens in the snipe it demo page.
Let’s wait for a fix, I’m sure with the v5 release they are like breathing underwater :)

**Comment by snipe** [comment]
> Let’s wait for a fix, I’m sure with the v5 release they are like breathing underwater :)

Breathing? what is breathing? lol

Okay, I've fixed this on `develop`, BUT check your `public/uploads` directory and make sure there isn't an additional `uploads` directory that was recently created. If there was, move the contents of those files into the normal `public/uploads` directory. 

This bug is an artifact of trying to get local file upload URLs and S3 file uploads to play nicely with each other. :(

**Comment by thtech182** [comment]
> > Let’s wait for a fix, I’m sure with the v5 release they are like breathing underwater :)
> 
> Breathing? what is breathing? lol
> 
> Okay, I've fixed this on `develop`, BUT check your `public/uploads` directory and make sure there isn't an additional `uploads` directory that was recently created. If there was, move the contents of those files into the normal `public/uploads` directory.
> 
> This bug is an artifact of trying to get local file upload URLs and S3 file uploads to play nicely with each other. :(

That was quick!!! Thanks! Can't wait for it to be pushed out.

**Comment by snipe** [comment]
It's on master now, should be in a tagged release in the next day or so. (We're trying to get an LDAP fix in before the next release, but if we can't confirm that LDAP fix, we'll just move forward without it and then tag a new one once the LDAP stuff is confirmed.)
