### ISSUE TITLE
LDAP Issues

### ISSUE THREAD

**Issue by hawkeye426** [grokability/snipe-it#8751]
#### Please confirm you have done the following before posting your bug report:

- [YES ] I have enabled debug mode 
- [YES ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The LDAP module does not allow any users to log in when the "Append domain name to username field" is unchecked, and allows all valid AD users to log in when it is checked regardless of LDAP filter or authentication query. User accounts are automatically created at this time with the note "Imported on first login from LDAP2" 

Additionally, the "Test Login" button and corresponding textbox are not shown on the "/admin/ldap" page.

**To Reproduce**
1. In LDAP Settings configure setting as per screen shots.

**Expected behavior**
LDAP Logins should work normally, and respect auth query / filters.

**Screenshots**
![ss1](https://user-images.githubusercontent.com/68485705/99202996-1b764e00-277f-11eb-9630-fc24466571c7.PNG)
![ss2](https://user-images.githubusercontent.com/68485705/99202911-cc301d80-277e-11eb-9fac-10653dcafe24.PNG)
![ss3](https://user-images.githubusercontent.com/68485705/99202912-cc301d80-277e-11eb-884c-463469b4a4eb.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version: 5.0.6
 - OS: [Docker]
 - Web Server: [Docker]
 - PHP Version [PHP Version 7.2.24-0ubuntu0.18.04.7] 

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [86.0.4240.198]

**Error Messages**
No exceptions or errors are logged.

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install via Docker

- Include what you've done so far in the installation, and if you got any error messages along the way.
Have tried changing filters etc. Including case sensitivity and setting the Auth Query to "sAMAccountName="

LDAP Filter = `&(objectclass=person)(samaccountname=*)(memberof:1.2.840.113556.1.4.1941:=cn=snipe it users,ou=groups,ou=corporate,dc=XXXXXXXXX,dc=net)`

- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by uberbrady** [comment]
The "Test Login" button has been added back. It's on master, but I'm not sure it's on a release yet? Probably is.

The filter option is only respected during sync, not during login. 

Under Active Directory, User login-ability is powered by the Active Directory UAC settings only - even if you change a user's ability to login, that setting will get flipped back on next sync.

I have a PR that addresses this (slightly) #8776 - it allows you to specify an 'active' flag - which, if set, will override that UAC check, allowing you to manually specify active/inactive. You can even set it to a nonexistent flag, I believe, and then the administrator choices should take precendence. Or you can even point it to an _unused_ flag in AD (one that no one cares about). If that flag is set to the string `false` - they'll be deactivated on sync.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
