### ISSUE TITLE
Predefined Kits - Feature Request

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#8755]
Currently, you create a predefined kit then assign it asset models.

Would you please also allow assets to be assigned to predefined kits?

For example.

I have multiple Chromebooks in my inventory system. I would like to create a predefined kit. A Chrome cart with multiple Chromebooks assigned to it.  So those assets (Chromebooks) would be assigned to a predefined kit (say Chrome Cart I). 

Updating my request. It might be worth while to allow any asset, license, accessory or consumable to be assigned to a kit individually. You never know the creative ways that users may use Snipe-IT.

**Comment by gilesytheking** [comment]
See #8762 #8723 #8539 - Seems to be a hot topic regarding this feature

**Comment by snipe** [comment]
Closing as duplicate.
