### ISSUE TITLE
JavaScript (AJAX Error) 

### ISSUE THREAD

**Issue by Tayyabshahzad** [grokability/snipe-it#8758]
Failed to load resource: the server responded with a status of 401 (Unauthorized)
I am facing this error while adding the company to my account also unable to view all registered companies.

**Comment by snipe** [comment]
Please see the common issues page:
https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by Tayyabshahzad** [comment]
Hi Folks,
I have set up and install Snipe-IT via git, I have done configuration and setup database and the user also. Now the application is running fine but facing some issues.
Issues:

- I have created companies that company are listed in my database but not visible on my company pages more ever when I try to create a new company having the same name its generate an error that "Company already exists" it means that the company is created in DB but not visible on my company page.
Company Page  Empty Screenshot: https://user-images.githubusercontent.com/46642071/99383239-67480500-28ef-11eb-8db2-49649eb64142.PNG

- I have created users that users are listed in my database but not visible on my user page. 
- Console Error https://user-images.githubusercontent.com/46642071/99383655-fc4afe00-28ef-11eb-9ab2-8e7471387d30.PNG)
: Browser Console page showing error.
Thanks for your help.


<blockquote></blockquote>
<blockquote></blockquote>

**Comment by snipe** [comment]
See the documentation I Iinked to in my previous reply.

**Comment by Azazel666** [comment]
We're having the same issue here, and i have read the common issues about the 401 there.

I have deleted the bootstrap/cache/services.php file, the other two i dont have in my cache folder. This did not help.
And as far as I can gather all the required extensions is installed and active, but we still get 401 on all ajax requests for table listings.
