### ISSUE TITLE
Error Data is not Showing 

### ISSUE THREAD

**Issue by Tayyabshahzad** [grokability/snipe-it#8761]
Hi Folks,
I have set up and install Snipe-IT via git, I have done configuration and setup database and the user also. Now the application is running fine but facing some issues.
Issues:

I have created companies that company are listed in my database but not visible on my company pages more ever when I try to create a new company having the same name its generate an error that "Company already exists" it means that the company is created in DB but not visible on my company page.
Company Page Empty Screenshot: https://user-images.githubusercontent.com/46642071/99383239-67480500-28ef-11eb-8db2-49649eb64142.PNG

I have created users that users are listed in my database but not visible on my user page.

Console Error https://user-images.githubusercontent.com/46642071/99383655-fc4afe00-28ef-11eb-9ab2-8e7471387d30.PNG)
: Browser Console page showing error.
Thanks for your help.

**Comment by uberbrady** [comment]
Try and run `php upgrade.php` in your Snipe-IT directory. You'll probably find:

a) Some PHP modules that are required are not installed
or
b) Some composer dependencies didn't install
