### ISSUE TITLE
Unable to login after migrating DB to new install

### ISSUE THREAD

**Issue by r-hardiman** [grokability/snipe-it#8764]
#### Expected Behavior (or desired behavior if a feature request)
Successful Log In after migrating database to a fresh install.

-----

#### Actual Behavior

Incorrect username/password error despite being 100% correct.

-----

#### Please confirm you have done the following before posting your bug report:

- [✓] I have enabled debug mode 
- [✓] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install but migrating existing database.
- Version of Snipe-IT you're running - V5.0.7
- Version of PHP you're running - 7.2.7
- Version of MySQL/MariaDB you're running - 10.1.10-MariaDB
- What OS and web server you're running Snipe-IT on - Windows Server 2012 R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - Just incorrect username/password
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - /login
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - No
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Got a "Access Denied" message for the connection to the DB unless I put the PW in quotation marks within the .env file, the information within the .env file is confirmed correct as it works if I connect using those details manually.

- Indicate whether or not you've manually edited any data directly in the database - Nope

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by moerkey** [comment]
I can just approve it with :
- Ubuntu 18.04
- nginx 1.14.0-0ubuntu1.7
- php7.2-fpm7.2.34-8+ubuntu18.04.1+deb.sury.org+1

**Comment by snipe** [comment]
> I can just approve it with :

I'm not sure what you mean approve it?

If you're getting a username/password rejected error, then the username or password must be incorrect or mis-formatted in the `.env`.

> Got a "Access Denied" message for the connection to the DB unless I put the PW in quotation marks within the .env file

So does putting the PW in quotes work? If so, what is the actual issue here?

**Comment by moerkey** [comment]
I am sorry. The login is just not successful.
The credentials are fine. I am not getting any error messages.
I am getting a redirect to the login page.

**Comment by r-hardiman** [comment]
> > I can just approve it with :
> 
> I'm not sure what you mean approve it?
> 
> If you're getting a username/password rejected error, then the username or password must be incorrect or mis-formatted in the `.env`.
> 
> > Got a "Access Denied" message for the connection to the DB unless I put the PW in quotation marks within the .env file
> 
> So does putting the PW in quotes work? If so, what is the actual issue here?

If I do not put the PW in quotes I get the Snipe-It Pre-Flight setup page and all is good apart from an "Access Denied" message under database, whereas if I put the PW in quotes I get the normal login page, however, I am unable to login due to an "Incorrect username or password" error message, despite putting in the correct login details.

**Comment by snipe** [comment]
So then it sounds like your password should be in quotes. Are you logging in with a local user or LDAP/AD/etc?

**Comment by r-hardiman** [comment]
> So then it sounds like your password should be in quotes. Are you logging in with a local user or LDAP/AD/etc?

LDAP Account that I used on the old installation.

**Comment by r-hardiman** [comment]
I just created a local admin account on the old version and then tried to log in to that account on the new version, and it did kinda work but it gave me a 500 error code.

**Comment by r-hardiman** [comment]
Here is the error that comes up when I try to log in to the local account I created:

SQLSTATE[42S02]: Base table or view not found: 1146 Table '*dbname_here*.permission_groups' doesn't exist (SQL: select `permission_groups`.*, `users_groups`.`user_id` as `pivot_user_id`, `users_groups`.`group_id` as `pivot_group_id` from `permission_groups` inner join `users_groups` on `permission_groups`.`id` = `users_groups`.`group_id` where `users_groups`.`user_id` = 356)

**Comment by r-hardiman** [comment]
Resolved it, the upgrading documentation didn't mention anything about having to run the database migration command if going from v4 to v5 but I ran that and it is now up and functioning.

**Comment by moerkey** [comment]
> Resolved it, the upgrading documentation didn't mention anything about having to run the database migration command if going from v4 to v5 but I ran that and it is now up and functioning.

Which command is it?

**Comment by snipe** [comment]
> Resolved it, the upgrading documentation didn't mention anything about having to run the database migration command if going from v4 to v5 but I ran that and it is now up and functioning.

Indeed we do mention that:

<img width="875" alt="Screen Shot 2020-11-18 at 2 30 10 AM" src="https://user-images.githubusercontent.com/197404/99518907-0861aa80-2946-11eb-8881-18cb60c6475f.png">

https://snipe-it.readme.io/docs/upgrading#upgrading-manually

If you use the upgrade.php script, migrations are run for you, but if you upgrade manually, you have to run them yourself. 

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading#upgrading-manually">Upgrading</a></strong></div><div>Always backup your database and configuration files before upgrading. We try very hard to make sure that all database changes are non-destructive, but you should always backup beforehand anyway. You will never regret backing up your database. You may regret not doing so, so it’s just better to get i...</div></blockquote>
