### ISSUE TITLE
Creating an Asset - Model is not required, but is required

### ISSUE THREAD

**Issue by ciahang** [grokability/snipe-it#8765]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When creating an asset, the Model field is not required; the "required" indicator isn't there.  When going to save, an error shows that Model is required.

**To Reproduce**
1. Go to 'Hardware'
2. Click on 'Create new'
3. Fill in required fields
4. Click Save

**Expected behavior**
If the model is required, it should sow the "required" indicator

**Screenshots**
![image](https://user-images.githubusercontent.com/1809697/99405190-18c84580-28b2-11eb-8f94-4fc7d87a8877.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.6
 - OS: CentOS
 - Web Server: Apache
 - PHP Version 7.1

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 86.0.4240.198 (Official Build) (64-bit)

**Additional context**
- Fresh install
- Git pull install
- Configured LDAP, sync LDAP, added: companies, locations, departments

**Comment by snipe** [comment]
Model is always required. We'll fix the missing required indicator.
