### ISSUE TITLE
Logo not loaded due to APP_URL inserted in URL

### ISSUE THREAD

**Issue by moerkey** [grokability/snipe-it#8766]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The logo can not be loaded due to that the APP_URL is inserted in URL, i.e. https://example.foo.bar/example.foo.bar/uploads/setting-logo-STRING.png.
The file was successfully uploaded under DOCROOT/public/uploads/

**To Reproduce**
1. Go to Settings > Branding >  Web Branding Type > Logo.
2. Upload a Logo.
3. Save.
4. Open Login Page.
5. See no picture.

**Expected behavior**
I want to see the uploaded logo.

**Server (please complete the following information):**
 - Snipe-IT: Version 5.0.7
 - OS: Ubuntu 18.04
 - Web Server: nginx 1.14.0-0ubuntu1.7
 - PHP Version:  php7.2-fpm7.2.34-8+ubuntu18.04.1+deb.sury.org+1

**Comment by snipe** [comment]
The APP_URL is intended to be inserted into the URL. That's literally what it's there for. 

What do you have for the APP_URL value in your .env?

**Comment by moerkey** [comment]
I was thinking that the APP_URL is the hostname and not added as a path to the hostname itself.

https://example.foo.bar/example.foo.bar/uploads/setting-logo-STRING.png

**Comment by snipe** [comment]
What do you have for the APP_URL value in your .env?

Per the docs, you have to use a complete URL, including the `http://` or `https://` protocol for your APP_URL:
https://snipe-it.readme.io/docs/configuration#required-basic-app-settings

**Comment by moerkey** [comment]
Thx, that was it. I had only the hostname.
