### ISSUE TITLE
LDAP Failed / 401 Unauthorised

### ISSUE THREAD

**Issue by jamesBotwright** [grokability/snipe-it#8767]
#### Please confirm you have done the following before posting your bug report:

I have enabled debug mode 
I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
401 Unauthorised response to all API calls, resulting in application showing totals etc on dashboard but zero content on tables.  I have failed to get LDAP test working correctly since migrating so this may be related.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version - **Latest pull from Github (16th Nov)**
 - OS: [e.g. Ubuntu, CentOS] - **Ubuntu 18.04**
 - Web Server: [e.g. Apache, IIS] - **Apache2**
 - PHP Version - **PHP 7.3**

**Error Messages**
Error from toolbar in application:
![image](https://user-images.githubusercontent.com/16849842/99411929-108cfc00-28ec-11eb-916b-82643b92f636.png)

LDAP config and test fail:
![image](https://user-images.githubusercontent.com/16849842/99412180-577af180-28ec-11eb-8381-ac7b0874de87.png)

I can run a succesful LDAP test from command line:
ldapsearch -H ldap://XXXXXXXXXXXXXX.local -b "ou=GV DISS,dc=XXXXXXXXXXXXXX,dc=local" -D 'XXXXXXXXXXXXXX\snipeit' -W
Returns results

**Additional context**
- Is this a fresh install or an upgrade?  It is a migration to a new server, installed via GIT then followed migration guide manually copying config/storage/public and database
- What OS and web server you're running Snipe-IT on:  **Ubuntu 18.04/Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc):  **GIT**
- Include what you've done so far in the installation, and if you got any error messages along the way:  **I have tried following the guides, clearing cache bootstrap files etc, checked all PHP extensions are in place and ran upgrade.php** 
- Indicate whether or not you've manually edited any data directly in the database: **No**

Add any other context about the problem here:

**We had everything working fine on the old server and the settings have been replicated with the exception of a different domain.  When following the migration guide everything was ok except if we copied the contents of hte config folder the application fails with a 'LOG file' error, if we keep the contents of the config folder as the new ones the application runs but has the 401 issues when trying to populate any tables.  **

**We have tried some CLI testing for the LDAP.  When we try with above config we get this:  
![image](https://user-images.githubusercontent.com/16849842/99416848-2ea92b00-28f1-11eb-89dc-cba69192bc9a.png)

If we change the LDAP settings to use 'cn' in first name instead of givenname then the CLI gives results but the app test still fails
**

I have been reading forums and topics but I just cannot resolve this one, any help would be appreciated.  I can re-install if required and we still have the working "old" snipe server going to reference, the main difference being a newer version of Snipe-it on the new server.

**Comment by snipe** [comment]
Please see the common issues page that addresses this:
https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated 

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by jamesBotwright** [comment]
@snipe  Many thanks for the reply.  I had tried going through the items on those pages but I tried again this morning to make sure and it is now working, therefore I must have missed a step previously.  Apologies to waste time and thanks for the help, great repo 👍

**Comment by snipe** [comment]
> Apologies to waste time and thanks for the help, great repo

No worries - glad you're all sorted now!
