### ISSUE TITLE
Wrong Translation - Purge Deleted Records

### ISSUE THREAD

**Issue by GustelDE** [grokability/snipe-it#8769]
Hi folks,

the translation in the "Purge Deleted Records" page is wrong (V5.0.7)!
It states the word "LÖSCHEN" is needed to perform the action. But, even "löschen" is the correct translation of "delete", the command is only executed when entering "DELETE".

Maybe you could fix this in the next release? New users will confuse this!

![Unbenannt-1](https://user-images.githubusercontent.com/26502186/99438577-447c1780-2914-11eb-96ef-6a82e648a0aa.jpg)

Regards

**Comment by snipe** [comment]
What language is this?

**Comment by GustelDE** [comment]
German

**Comment by snipe** [comment]
This is fixed on master
