### ISSUE TITLE
Custom Fields for Assets

### ISSUE THREAD

**Issue by ciahang** [grokability/snipe-it#8771]
**Server (please complete the following information):**
 - Snipe-IT Version: 5.0.6
 - OS: CentOS
 - Web Server: Apache
 - PHP Version: 7.1

**Is your feature request related to a problem? Please describe.**
Not related to a problem. Custom Fields by Asset Model serves a great purpose. The current custom fields only apply if I have configured an Asset Model for the specific custom field, but I'd like to apply custom fields for all assets, regardless of Asset Model.  

**Describe the solution you'd like**
Would like to see custom fields that I can apply to all assets. 

**Describe alternatives you've considered**
I've used Company Name as a workaround to address 1 of the types of data I'd like to track on assets, but this isn't exactly what I would like to use.

**Additional context**
None

**Comment by snipe** [comment]
You would simply bulk update your asset models to use the fieldset that you want to apply to all assets.
