### ISSUE TITLE
AD users can't login

### ISSUE THREAD

**Issue by Dnatalyaalex** [grokability/snipe-it#8778]
#### Expected Behavior (or desired behavior if a feature request)
Active direcrory users can login.

(what you expect to happen goes here)
It seems my LDAP Filter or LDAP Authentication query is wrong.
-----

#### Actual Behavior

(what actually happens goes here)
I configured AD sync for snipe-it . Now I can see all my AD users but they can't login.
Also I tried Test LDAP Login and it failed for all users.

![image](https://user-images.githubusercontent.com/44223742/99528710-5eb30580-29a7-11eb-97de-0fa6c1e2e82d.png)

-----

#### Please confirm you have done the following before posting your bug report:

- Yes I have enabled debug mode 
- Yes I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this an upgrade folloving documentation.
- Snipe-IT versionv4.9.2 build 4352 (gec723a3da)
- PHP Version7.2.24-0ubuntu0.18.04.7
- Mysql  Ver 14.14 Distrib 5.7.32
- What OS and web server you're running Snipe-IT on: 29~18.04.1-Ubuntu

**Comment by snipe** [comment]
Why are you upgrading to 4.9.2? Latest is version 5.0.7.

**Comment by uberbrady** [comment]
If your AD users are in the format of:

```
<their username>@<Active Directory Domain from LDAP settings>
```

Then they should be able to log in as `<their username>`

If the test LDAP for sync *does* work, but the test login *doesn't* work, I suspect your "Active Directory Domain" setting might be incorrect.

**Comment by Dnatalyaalex** [comment]
> If your AD users are in the format of:
> 
> ```
> <their username>@<Active Directory Domain from LDAP settings>
> ```
> 
> Then they should be able to log in as `<their username>`
> 
> If the test LDAP for sync _does_ work, but the test login _doesn't_ work, I suspect your "Active Directory Domain" setting might be incorrect.

In AD users logon names are in format firstname.secondname@domain.com, in snipe-it I see username as firstname.secondname and with firstname.secondname I try to login but can't.

**Comment by uberbrady** [comment]
And you have your 'active directory domain' set to exactly `domain.com` - not something like `ad.domain.com`?

You can also experiment with just deleting it - then it should try and pick up your emaildomain instead.

**Comment by Dnatalyaalex** [comment]
I found out, I made a mistake in domain name. Now it's working. Thank you a lot for your answers.
Please close the issue.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
