### ISSUE TITLE
Two Factor codes are no longer vaild - how can I disable two factor?

### ISSUE THREAD

**Issue by JohnLBergqvist** [grokability/snipe-it#8779]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
All of a sudden, our Two factor codes it asks us to enter are invalid, even when creating new users. How can I disable two factor system wide (i can get into the mysql database itself)? is there a setting I can change?

**Comment by snipe** [comment]
What version of Snipe-IT are you running?

**Comment by JohnLBergqvist** [comment]
@snipe 5.4.35

**Comment by JohnLBergqvist** [comment]
@snipe 4.1.9

**Comment by snipe** [comment]
@JohnLBergqvist wait, which is it?

We haven't made any changes to 2FA in quite some time. Are you using LDAP or SAML or just local users?

You should be able to run `update settings set two_factor_enabled = 0;` - you might have to clear your cookies.

**Comment by JohnLBergqvist** [comment]
@snipe Sorry, it's definitley 4.1.9. Yeah I think the error is its unable to talk to our LDAP server all of a sudden, which is odd as it was working fine last week and the LDAP server is up, and the credentials haven't changed: 

```
[2020-11-18 13:26:02] production.ERROR: There was an error authenticating the LDAP user: ldap_bind(): Unable to bind to server - invalid credentials```

**Comment by JohnLBergqvist** [comment]
@snipe How do I run that `update` command?

**Comment by snipe** [comment]
We haven't touched anything on Snipe-IT v4.1.9 since it was released, in Dec 2017. 
https://github.com/snipe/snipe-it/releases/tag/v4.1.9

Possible something in your server environment changed? PHP got upgraded, etc?

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/snipe/snipe-it/releases/tag/v4.1.9">Release v4.1.9 · snipe/snipe-it</a></strong></div><div>New in v4.1.9
This is a small maintenance release, mostly to fix an issue some folks were having viewing the companies listings.
New

Added “new” buttons for manufacturer and category in asset mode...</div></blockquote>

**Comment by snipe** [comment]
> [2020-11-18 13:26:02] production.ERROR: There was an error authenticating the LDAP user: ldap_bind(): Unable to bind to server - invalid credentials

That looks like your LDAP credentials either changed, or the user you use to bind with no longer has that ability. You said you could get into the database itself.

> How do I run that update command?

You'd need tp get a mysql prompt.

**Comment by JohnLBergqvist** [comment]
@snipe thanks, I've ran the update command, cleared my cookies, but it's still prompting me for a 2FA code

**Comment by snipe** [comment]
One other thing that maaaaybe could have happened is that your APP_KEY changed, and it scrambled your LDAP password. (That doesn't happen on it's own, mind you - someone would have had to regenerate it - and even then I'd expect a different error.) But if you need to disable LDAP, run `update settings set ldap_enabled = 0;` on your database.

**Comment by snipe** [comment]
What was the output of the mysql query when you ran it?

**Comment by JohnLBergqvist** [comment]
@snipe 
```
MariaDB [SnipeIT]> update settings set two_factor_enabled = 0;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0
````
however it's still prompting me for a 2FA code

**Comment by snipe** [comment]
Try `UPDATE settings SET two_factor_enabled = null;`

**Comment by JohnLBergqvist** [comment]
@snipe Ah, that worked! Thank you. Looks like the LDAP errors I saw where genuine invalid logins to the frontend, so yeah, unrelated.

**Comment by JohnLBergqvist** [comment]
@snipe I've disabled, and re-enabled two-factor from my account, and it's still saying that the code is invalid though, which is odd, even when re-enrolling from scratch.

**Comment by snipe** [comment]
Did you try resetting your 2FA by using the reset button in your user view in Users?

<img width="882" alt="Screen Shot 2020-11-18 at 6 10 45 AM" src="https://user-images.githubusercontent.com/197404/99540772-d3188500-2964-11eb-8880-4788c150ece5.png">

**Comment by JohnLBergqvist** [comment]
@snipe Yes, but that just redirects me to the two-factor enrollment screen. I scan in my barcode, it generates the code in the authentication app, however upon entering it, snipeit says the code is invalid.

**Comment by snipe** [comment]
I don't really know what to tell you. we haven't changed that code since 2017, so something must have changed on your end somehow :( It's an old version, and that tag is locked there at that Dec 2017 date.

**Comment by snipe** [comment]
Maybe try running:

```
php artisan config:clear
php artisan view:clear
php artisan cache:clear
```

and the other commands at https://snipe-it.readme.io/docs/common-issues#quick-tip-handy-commands


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues#quick-tip-handy-commands">Common Issues</a></strong></div><div>  These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin.These commands clear out cached service files that help speed up modern PHP applications but can also very occasionally be out of date, resu...</div></blockquote>

**Comment by snipe** [comment]
Also maybe clear out the contents of the `storage/framework/sessions` directory.

**Comment by JohnLBergqvist** [comment]
@snipe Nope, still telling me the code is invalid. is there any logs I can view, to see the back and forth between the app and snipeit?

**Comment by snipe** [comment]
You can try setting the following in your .env (look for them, they should be there)

```
APP_LOG_LEVEL=debug
APP_DEBUG=true
```

and then running `php artisan config:clear`, then tailing the logs as you try to login, but I don't imagine you'll see much in the logs.

**Comment by JohnLBergqvist** [comment]
@snipe I have resolved the issue, the server's clock had drifted out of sync. Thanks anyway though!

**Comment by snipe** [comment]
Got it - thanks for posting the follow-up
