### ISSUE TITLE
provide a count on Assets Status

### ISSUE THREAD

**Issue by yosiasz** [grokability/snipe-it#8781]
**Server (please complete the following information):**
 - Snipe-IT Version : 4.9.5
 - OS: WIndows Server
 - Web Server: IIS
 - PHP Version : 7.13.3

**Is your feature request related to a problem? Please describe.**
I have to click on each Asset status to see what is under the cover

**Describe the solution you'd like**
Would be nice to see a count next to the different Asset Statuses.

**Describe alternatives you've considered**
None

**Additional context**
Something like this?

![image](https://user-images.githubusercontent.com/900951/99594090-8ace8680-29a7-11eb-8c41-779629bee523.png)

**Comment by snipe** [comment]
We don't currently do that because if people have a lot of custom statuses, that starts to generate a lot of extra queries which can slow the page down, but let me experiment a little.

**Comment by yosiasz** [comment]
I agree. Because one can create their own status. thanks @snipe

**Comment by yosiasz** [comment]
@snipe wow looks amazing on the demo site. thanks so much!!!

**Comment by yosiasz** [comment]
![image](https://user-images.githubusercontent.com/900951/100147082-b346fc80-2e4f-11eb-8b6a-8b0722d4ae27.png)
