### ISSUE TITLE
HTTPS - can login ok, but sub pages/links broken

### ISSUE THREAD

**Issue by wrightmt** [grokability/snipe-it#8783]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After logging in via https - none of the internal links/pages work. http is ok

**To Reproduce**

Fresh installation, configured HTTPS/SSL on httpd - I can access my install via https and login ok, however clicking on a page/link will just 404 - requested URL not found.

Logging in via http is fine and the site works as expected

**Server (please complete the following information):**
 - Snipe-IT Version : 5.0.7 
 - OS: CentOS 8
 - Web Server: httpd
 - PHP Version: 7.2.24

**Additional context**

This is a fresh install, however I have imported the database from an existing installation (after updating that installation to 5.0.7 also)

Running on CentOS 8/httpd

Installation was manual

I've set **APP_URL=**https://asset/ in my .env

**Comment by samotelf** [comment]
Hello.
Here's my config, hope it helps:

**cat /etc/httpd/conf.d/snipeit.conf**

<VirtualHost *:80>
        Redirect "/" "https://snipeit.contoso.com/"
        ServerName snipeit.contoso.com
        ServerAdmin webmaster@localhost
        <Directory /var/www/html/snipeit/public/>
        Allow From All
        AllowOverride All
        Options +Indexes
        </Directory>
        DocumentRoot /var/www/html/snipeit/public/
        ErrorLog /var/log/httpd/snipeIT.error.log
        CustomLog /var/log/access.log combined
        RewriteEngine On
        RewriteCond %{HTTPS} !on
        RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>

<VirtualHost *:443>
        ServerName snipeit.contoso.com
        ServerAlias *.contoso.com
        ServerAdmin webmaster@localhost
        <Directory /var/www/html/snipeit/public/>
        Allow From All
        AllowOverride All
        Options +Indexes
        </Directory>
        SSLEngine on
        SSLCertificateFile /etc/pki/tls/certs/wildcard_contoso_com.crt
        SSLCertificateKeyFile /etc/pki/tls/private/wildcard_contoso_com.key
        SSLCertificateChainFile /etc/pki/tls/certs/DigiCertCA.crt
        DocumentRoot /var/www/html/snipeit/public/
        ErrorLog /var/log/httpd/snipeIT.error.log
        CustomLog /var/log/access.log combined
        Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"
        SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
        SSLCipherSuite HIGH:!aNULL:!MD5:!3DES
        SSLHonorCipherOrder on
</VirtualHost>

**My .env:**
cat /var/www/html/snipeit/.env

APP_URL=https://snipeit.contoso.com

**Comment by wrightmt** [comment]
Thanks - I'm still stuck though 

If I set it up like this I can get to snipeit on http and https

However the https version has all of its links broken

If add a 443 VirtualHost in my asset.conf I can't get to the site via either method anymore

**/etc/httpd/conf.d/asset.conf**

<VirtualHost *:80>
  ServerName asset
  Redirect "/" "https://asset"
  DocumentRoot /var/www/html/snipe/public
  <Directory  /var/www/html/snipe/public/>
    Options Indexes FollowSymLinks Multiviews
    AllowOverride All
    allow from all
  </Directory>
</VirtualHost>


**/etc/httpd/conf.d/ssl.conf**

Listen 443 https
SSLPassPhraseDialog exec:/usr/libexec/httpd-ssl-pass-dialog
SSLSessionCache         shmcb:/run/httpd/sslcache(512000)
SSLSessionCacheTimeout  300
SSLCryptoDevice builtin
#SSLCryptoDevice ubsec

<VirtualHost _default_:443>
# General setup for the virtual host, inherited from global configuration
DocumentRoot "/var/www/html/snipe/public/"
ServerName asset:443

ErrorLog logs/ssl_error_log
TransferLog logs/ssl_access_log
LogLevel warn

SSLEngine on

SSLHonorCipherOrder on
SSLCipherSuite PROFILE=SYSTEM
SSLProxyCipherSuite PROFILE=SYSTEM
SSLCertificateFile /etc/pki/tls/certs/asset.crt
SSLCertificateKeyFile /etc/pki/tls/private/asset.key
#SSLCertificateChainFile /etc/pki/tls/certs/server-chain.crt
#SSLCACertificateFile /etc/pki/tls/certs/ca-bundle.crt
#SSLVerifyClient require
#SSLVerifyDepth  10
<FilesMatch "\.(cgi|shtml|phtml|php)$">
    SSLOptions +StdEnvVars
</FilesMatch>
<Directory "/var/www/cgi-bin">
    SSLOptions +StdEnvVars
</Directory>
BrowserMatch "MSIE [2-5]" \
         nokeepalive ssl-unclean-shutdown \
         downgrade-1.0 force-response-1.0

CustomLog logs/ssl_request_log \
          "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"

</VirtualHost>

**Comment by wrightmt** [comment]
This is what worked for me -  /etc/httpd/conf.d/snipe.conf

<VirtualHost *:443>
        SSLEngine on
        SSLCertificateFile /etc/pki/tls/certs/asset.crt
        SSLCertificateKeyFile /etc/pki/tls/private/asset.key
        <Directory /var/www/html/snipe/public>
        AllowOverride All
        </Directory>
        DocumentRoot /var/www/html/snipe/public
        ServerName asset
</VirtualHost>
<VirtualHost *:80>
  ServerName asset
  DocumentRoot /var/www/html/snipe/public
  Redirect / https://asset
<Directory  /var/www/html/snipe/public>
    Options Indexes FollowSymLinks Multiviews
    AllowOverride All
    Order allow,deny
    allow from all
  </Directory>
</VirtualHost>

**Comment by wrightmt** [comment]
ok this is what worked for me - /etc/httpd/conf.d/snipe.conf

```
> <VirtualHost *:443>
>         SSLEngine on
>         SSLCertificateFile /etc/pki/tls/certs/asset.crt
>         SSLCertificateKeyFile /etc/pki/tls/private/asset.key
>         <Directory /var/www/html/snipe/public>
>         AllowOverride All
>         </Directory>
>         DocumentRoot /var/www/html/snipe/public
>         ServerName asset
> </VirtualHost>
> <VirtualHost *:80>
>   ServerName asset
>   DocumentRoot /var/www/html/snipe/public
>   Redirect / https://asset
> <Directory  /var/www/html/snipe/public>
>     Options Indexes FollowSymLinks Multiviews
>     AllowOverride All
>     Order allow,deny
>     allow from all
>   </Directory>
> </VirtualHost>
> 
```
