### ISSUE TITLE
API: Unable to create users

### ISSUE THREAD

**Issue by stefannitsche** [grokability/snipe-it#8784]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The API for creating users doesn't work. The /api/v1/users endpoint doesn't seem to handle POST-requests correctly. Users aren't created and the API responds with the HTML for the login page. So far this is the only endpoint I've seen this behavior from.

**To Reproduce**
Easiest way to test is to use the API-documentation.
1. https://snipe-it.readme.io/reference#users-2
2. Fill in the fields for you user
3. Click on Try it
4. Se the response in the right hand column

This isn't specific to the API docuementation, it's also possible to reproduce using the Snipe-IT docker image and sending a request to the API.

**Expected behavior**
That a user would actually be created and that a JSON response would be returned.

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.7
 - OS: Docker Image
 - Web Server: Docker Image
 - PHP Version: Docker Image

**Error Messages**
No errors are displayed. The API is intentionally disabled on https://snipeitapp.com/demo but 

**Additional context**
Fresh install. Official Docker image running on Ubuntu 18.04. Adding users through the WEB UI works.
Adding users through the API works on an old server running 4.6.6.

**Comment by snipe** [comment]
If the API responds with HTML, you’re missing some headers. Confirm that you’ve included your bearer token, and the additional headers included in our API documentation.

**Comment by stefannitsche** [comment]
Yes, I have confirmed that I have those headers included. I can create companies, assets and whatnot with those headers attached but not users. If make the same request to another clean 4.6.6. install (with the appropriate bearer token for that install) users get created.

To be honest I think there is something wrong with the handling of POST request at that endpoint. The reason behind that suspicion is that not even the documentation site is able to create users without getting an HTML response.

As I stated in my original message you can test this issue here: https://snipe-it.readme.io/reference#users-2, fill in the required fields press try it and watch how you get an HTML response in the right hand column.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference#users-2">Overview</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>
