### ISSUE TITLE
Failed to load image after update to 5.0.7

### ISSUE THREAD

**Issue by pascal-ts** [grokability/snipe-it#8785]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I updated to 5.0.7 from 4.9.2 with `sudo -u apache php upgrade.php`, now all assets won't show pictures.
If I access the link which is supposedly missing (e.g. http://snipe-it/uploads/models/assetmodel-image-xfrbNtNX2D.jpg) directly, the correct picture shows up.
I can delete and upload a new picture for the asset model, checking on the VM it also puts the new one in the correct folder, but it's still not showing.
It will show up only when editing said asset model. Copying the picture link results in the exact same which the error said was missing...

I copied my old snipe folder under /var/www/html and when I move it back, it works fine again.
Manually using this guide: https://snipe-it.readme.io/docs/switching-to-a-git-install results in the same issue.

**To Reproduce**
1. Go to any asset or list any assets

**Expected behavior**
The picture of assets should show up

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.7
 - OS: CentOS 8, latest patches
 - Web Server: Apache
 - PHP Version 7.3.24

**Desktop (please complete the following information):**
 - OS: tested from Windows 10, Windows Server 2019, Raspberry Pi 4
 - Browser: Chrome
 - Version 86

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

No error with APP_DEBUG on true

**Additional context**
- Is this a fresh install or an upgrade?
- upgrade

- What OS and web server you're running Snipe-IT on
- newest CentOS 8 with all current patches

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- manual installation

- Include what you've done so far in the installation, and if you got any error messages along the way.
- worked fine before the update

- Indicate whether or not you've manually edited any data directly in the database
- nope

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by hyprem** [comment]
Yeah I had the same on a fresh install. Something is going very wrong with the images :(

for me this fixed it: https://github.com/snipe/snipe-it/issues/8701
Had to add http:// to my .env

**Comment by pascal-ts** [comment]
@hyprem thank you so much, fixed it for me aswell!
