### ISSUE TITLE
Expiring License Alert Issues with UrlGenerator.php

### ISSUE THREAD

**Issue by jrosen175** [grokability/snipe-it#8788]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Each morning I am supposed to get emails about warrantee expirations and expiring licenses. I receive the expiring warrantee report but not the expiring license report. When I run the manual command in terminal "php artisan snipeit:expiring-alerts" I get two errors.

1. In UrlGenerator.php line 420: Route [license.show] not defined. (View: /var/www/html/snipeit/resources/views/notifications/markdown/report-expiring-licenses.blade.php)

2. In UrlGenerator.php line 420: Route [license.show] not defined.

**To Reproduce**
This is an automatic process that is failing. No steps involved with reproducing except to let it run or manually run the artisan command which errors with the errors listed above.

**Expected behavior**
I expect to get an email with the 49 licenses I have expiring within the next 60 days. Was working prior to upgrading to v5.

**Screenshots**
![image](https://user-images.githubusercontent.com/41134138/99686126-48fa1a80-2a51-11eb-8deb-87e15ae8bc26.png)

**Server (please complete the following information):**
 - Snipe-IT Version - 5.0.7
 - OS: [e.g. Ubuntu, CentOS] - Red Hat Enterprise 7.9
 - Web Server: [e.g. Apache, IIS] - Apache
 - PHP Version - 7.2.34

**Comment by jrosen175** [comment]
I was able to get the alert to generate by removing the "a" tag from the "report-expiring-licenses.blade.php" file. The alert generates but it is less useful since the names are no longer linked to the specific license.

**Comment by QuentinC** [comment]
Hello,

I can confirm that this issue is present on the latest Docker image !

Thanks !

**Comment by digoblin** [comment]
Same problem here. Recent install with docker.

**Comment by Diniver** [comment]
Hi all, 

I have confirm this problem as well. 

Config:
Git Installation
Snipe-IT version: v5.0.9 build 5616 (973eacf6c3)
PHP Version: 7.2.34-8+ubuntu20.04.1+deb.sury.org+1
Laravel Version: 6.18.10
OS:  Ubuntu 20.04.1 LTS

**Comment by sven-piller** [comment]
And another config:

Git Installation
Snipe-IT version: v5.0.9 build 5616 (973eacf6c3)
PHP Version: 7.3.22
Laravel Version: 6.18.10
Web Server: IIS
OS: Windows Server 2016

**Comment by Diniver** [comment]
With update to 5.0.10 the problem has been resolved for me.

**Comment by jrosen175** [comment]
Updated to 5.0.10 and the issue has been resolved.
