### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by madkins-fareva** [grokability/snipe-it#8789]
#### Expected Behavior (or desired behavior if a feature request)

Test email generates the following error: Mail could not be sent.  No additional error message provided. Check your mail settings and your app log.

-----

#### Actual Behavior

When I initial installed and configured Snipe-IT, the email test failed on Pre-Flight.  I continued past Pre-Flight to troubleshoot.  I click the Test Mail button under Settings > General Settings and it generates the above error.  We are using a mail relay to allow email to to be acccepted by our Exchange 2010 server.

PHP email settings are below.  A username and password are not required since it is a mail relay.  Access is granted by the server's IP address.

MAIL_DRIVER=smtp
MAIL_HOST=10.x.x.x
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=snipeit.richmond@fareva.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=snipeit.richmond@fareva.com
MAIL_REPLYTO_NAME='Snipe-IT'

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Fresh install

- Version of Snipe-IT you're running
v5.0.6 build 5600 (g686ab681e)

- Version of PHP you're running
7.4.1

- Version of MySQL/MariaDB you're running
10.5.5 64-bit
- What OS and web server you're running Snipe-IT on
Windows Server 2012 R2
IIS 8.5.9600.16384

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Yes

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Settings > General Settings

- If a stacktrace is provided in the error, include that too.
Stack trace included

- Any errors that appear in your browser's error console.
Google Chrome: Failed to load resource: the server responded with a status of 500 (Internal Server Error) /snipe-it/public/api/v1/settings/mailtest:1 

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Feature not enabled on demo site.

- Include any additional information you can find in `storage/logs` and your webserver's logs.
Larvel
[2020-11-19 11:34:33] production.ERROR: syntax error, unexpected ''Expected_Checkin_Notification' (T_CONSTANT_ENCAPSED_STRING), expecting ')' {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected ''Expected_Checkin_Notification' (T_CONSTANT_ENCAPSED_STRING), expecting ')' at C:\\inetpub\\wwwroot\\snipe-it\
esources\\lang\\en\\mail.php:77)
[stacktrace]
#0 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php(123): Illuminate\\Filesystem\\Filesystem->getRequire()
#1 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php(67): Illuminate\\Translation\\FileLoader->loadPath()
#2 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(279): Illuminate\\Translation\\FileLoader->load()
#3 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(191): Illuminate\\Translation\\Translator->load()
#4 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(126): Illuminate\\Translation\\Translator->getLine()
#5 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(873): Illuminate\\Translation\\Translator->get()
#6 C:\\inetpub\\wwwroot\\snipe-it\\app\\Notifications\\MailTest.php(42): trans()
#7 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\Channels\\MailChannel.php(51): App\\Notifications\\MailTest->toMail()
#8 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\NotificationSender.php(146): Illuminate\\Notifications\\Channels\\MailChannel->send()
#9 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\NotificationSender.php(105): Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
#10 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#11 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\NotificationSender.php(107): Illuminate\\Notifications\\NotificationSender->withLocale()
#12 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow()
#13 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send()
#14 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): Illuminate\\Notifications\\ChannelManager->send()
#15 C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Controllers\\Api\\SettingsController.php(138): Illuminate\\Support\\Facades\\Facade::__callStatic()
#16 [internal function]: App\\Http\\Controllers\\Api\\SettingsController->ajaxTestEmail()
#17 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array()
#18 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#19 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#20 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#21 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(681): Illuminate\\Routing\\Route->run()
#22 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#23 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#25 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#27 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#28 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute()
#29 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#30 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#31 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#32 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#34 C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\SecurityHeaders->handle()
#36 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForDebug->handle()
#40 C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\CheckForSetup.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForSetup->handle()
#42 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#44 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#46 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#48 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#50 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\barryvdh\\laravel-cors\\src\\HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle()
#52 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#54 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#55 C:\\inetpub\\wwwroot\\snipe-it\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle()
#56 {main}
"} 

- Include what you've done so far in the installation, and if you got any error messages along the way.
Installed and configured per insturctions for Windows server

- Indicate whether or not you've manually edited any data directly in the database
No data has been manually editedin the DB.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by samotelf** [comment]
Hello.
I believe it is already solved.
Check https://github.com/snipe/snipe-it/issues/8746#issue-743099081

**Comment by madkins-fareva** [comment]
I will read through and see if it resolves my issue.

Thanks!

Matthew C. ADKINS – Senior Desktop Engineer
FAREVA RICHMOND
2248 Darbytown Road
Henrico Virginia 23231
E-mail : MAdkins.richmond@fareva.com<mailto:MAdkins.richmond@fareva.com>
Website : Fareva.com

[FAREVA logo QUADR EMAIL]

[DOUBLE BANDEAU FAREVA GESTES BARRIERE EN]

The contents of this email and any attachments are confidential to the intended recipient. They may not be disclosed to or used by or copied in any way by anyone other than the intended recipient. If this email is received in error, please contact the sender of this e-mail and then delete it. For more information on how we process personal data, please see https://www.fareva.com/en-gb/PrivacyPolicy. Please note that neither FAREVA nor the sender accepts any responsibility for viruses and it is your responsibility to scan or otherwise check this email and any attachments. This communication is issued on behalf of FAREVA, and individuals or legal entities (other than FAREVA) that are involved in the services provided by, or on behalf of, FAREVA cannot be held liable in any way whatsoever.

**Comment by madkins-fareva** [comment]
Hello,

Adding a comma to the end of line 76 of mail.php resolved the issue.

Thanks!

Matthew C. ADKINS – Senior Desktop Engineer
FAREVA RICHMOND
2248 Darbytown Road
Henrico Virginia 23231
E-mail : MAdkins.richmond@fareva.com<mailto:MAdkins.richmond@fareva.com>
Website : Fareva.com

[FAREVA logo QUADR EMAIL]

[DOUBLE BANDEAU FAREVA GESTES BARRIERE EN]

The contents of this email and any attachments are confidential to the intended recipient. They may not be disclosed to or used by or copied in any way by anyone other than the intended recipient. If this email is received in error, please contact the sender of this e-mail and then delete it. For more information on how we process personal data, please see https://www.fareva.com/en-gb/PrivacyPolicy. Please note that neither FAREVA nor the sender accepts any responsibility for viruses and it is your responsibility to scan or otherwise check this email and any attachments. This communication is issued on behalf of FAREVA, and individuals or legal entities (other than FAREVA) that are involved in the services provided by, or on behalf of, FAREVA cannot be held liable in any way whatsoever.

From: Adkins, Matt C
Sent: Thursday, November 19, 2020 1:48 PM
To: 'snipe/snipe-it'; snipe/snipe-it
Cc: Author
Subject: RE: [snipe/snipe-it] Unable to send email (#8789)

I will read through and see if it resolves my issue.

Thanks!

Matthew C. ADKINS – Senior Desktop Engineer
FAREVA RICHMOND
2248 Darbytown Road
Henrico Virginia 23231
E-mail : MAdkins.richmond@fareva.com<mailto:MAdkins.richmond@fareva.com>
Website : Fareva.com

[FAREVA logo QUADR EMAIL]

[DOUBLE BANDEAU FAREVA GESTES BARRIERE EN]

The contents of this email and any attachments are confidential to the intended recipient. They may not be disclosed to or used by or copied in any way by anyone other than the intended recipient. If this email is received in error, please contact the sender of this e-mail and then delete it. For more information on how we process personal data, please see https://www.fareva.com/en-gb/PrivacyPolicy. Please note that neither FAREVA nor the sender accepts any responsibility for viruses and it is your responsibility to scan or otherwise check this email and any attachments. This communication is issued on behalf of FAREVA, and individuals or legal entities (other than FAREVA) that are involved in the services provided by, or on behalf of, FAREVA cannot be held liable in any way whatsoever.

**Comment by samotelf** [comment]
Cool.
Can you mark the issue as closed?

**Comment by madkins-fareva** [comment]
Issue resolved.
•	Checked Append domain name to username field.
•	Checked Allow invalid SSL Certificate
•	Chanted LDAP Authentication query to samaccountname=

**Comment by thilinadias** [comment]
This might be helpful. Check this out

https://github.com/thilinadias/thilinadias/discussions/1#discussion-5964598

<blockquote><img src="https://opengraph.githubassets.com/c2ba03c0ed45452f57434ea24fdea063df4c26cbe17bddda1fcd297959e18680/thilinadias/thilinadias/discussions/1" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/thilinadias/thilinadias/discussions/1">Snipe-IT Email configuration error - Mail could not be sent. No additional error message provided. Check your mail settings and your app log. · thilinadias/thilinadias · Discussion #1</a></strong></div><div>✏️ Hi Github peeps, Welcome to my discussion regarding Snipe-IT Email configuration error - Mail could not be sent. No additional error message provided. Check your mail settings and your app log. ...</div></blockquote>
