### ISSUE TITLE
Unable to migrate database during upgrade to 5.0.7

### ISSUE THREAD

**Issue by G13312** [grokability/snipe-it#8791]
#### Expected Behavior (or desired behavior if a feature request)

Database to migrate during Step 7: Migrating database.

-----

#### Actual Behavior

Database does not get migrated and gives an error, then proceed to step 8.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running : 5.0.7
- Version of PHP you're running : 7.4.2
- Version of MySQL/MariaDB you're running : 8.0.18
- What OS and web server you're running Snipe-IT on : Windows 10 / IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'show_assigned_assets' in 'field list' (SQL: update `settings` set `require_accept_signature` = ?, `show_assigned_assets` = 0, `settings`.`updated_at` = 2020-11-19 14:58:34 where `id` = 1)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

When saving in admin/settings. Also happens in any settings page.

- If a stacktrace is provided in the error, include that too.

`(3/3) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'show_assigned_assets' in 'field list' (SQL: update `settings` set `require_accept_signature` = ?, `show_assigned_assets` = 0, `settings`.`updated_at` = 2020-11-19 15:00:03 where `id` = 1)
--
in Connection.php line 669
at Connection->runQueryCallback('update `settings` set `require_accept_signature` = ?, `show_assigned_assets` = ?, `settings`.`updated_at` = ? where `id` = ?', array(null, '0', '2020-11-19 15:00:03', 1), object(Closure))in Connection.php line 629
at Connection->run('update `settings` set `require_accept_signature` = ?, `show_assigned_assets` = ?, `settings`.`updated_at` = ? where `id` = ?', array(null, '0', '2020-11-19 15:00:03', 1), object(Closure))in Connection.php line 495
at Connection->affectingStatement('update `settings` set `require_accept_signature` = ?, `show_assigned_assets` = ?, `settings`.`updated_at` = ? where `id` = ?', array(null, '0', '2020-11-19 15:00:03', 1))in Connection.php line 428
at Connection->update('update `settings` set `require_accept_signature` = ?, `show_assigned_assets` = ?, `settings`.`updated_at` = ? where `id` = ?', array(null, '0', '2020-11-19 15:00:03', 1))in Builder.php line 2726
at Builder->update(array('require_accept_signature' => null, 'show_assigned_assets' => '0', 'settings.updated_at' => '2020-11-19 15:00:03'))in Builder.php line 790
at Builder->update(array('updated_at' => '2020-11-19 15:00:03', 'require_accept_signature' => null, 'show_assigned_assets' => '0'))in Model.php line 746
at Model->performUpdate(object(Builder))in Model.php line 661
at Model->save()in SettingsController.php line 356
at SettingsController->postSettings(object(Request))
at call_user_func_array(array(object(SettingsController), 'postSettings'), array(object(Request)))in Controller.php line 54
at Controller->callAction('postSettings', array(object(Request)))in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(SettingsController), 'postSettings')in Route.php line 219
at Route->runController()in Route.php line 176
at Route->run()in Router.php line 681
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckPermissions.php line 26
at CheckPermissions->handle(object(Request), object(Closure), 'superuser')in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CreateFreshApiToken.php line 50
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForTwoFactor.php line 53
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckLocale.php line 37
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in VerifyCsrfToken.php line 76
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Router.php line 683
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 658
at Router->runRoute(object(Request), object(Route))in Router.php line 624
at Router->dispatchToRoute(object(Request))in Router.php line 613
at Router->dispatch(object(Request))in Kernel.php line 170
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in InjectDebugbar.php line 65
at InjectDebugbar->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in SecurityHeaders.php line 26
at SecurityHeaders->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForSetup.php line 26
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in StartSession.php line 56
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForMaintenanceMode.php line 63
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in HandlePreflight.php line 29
at HandlePreflight->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Kernel.php line 145
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 110
at Kernel->handle(object(Request))in index.php line 58`

- Any errors that appear in your browser's error console. `Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. No

- Include any additional information you can find in `storage/logs` and your webserver's logs.
[laravel - Copy.log](https://github.com/snipe/snipe-it/files/5569450/laravel.-.Copy.log)

- Include what you've done so far in the installation, and if you got any error messages along the way.
  
1. I tried running php artisan migrate after the upgrade, but got the error `Migrating: 2019_02_12_182750_add_actiondate_to_actionlog In PDOStatement.php line 127: Maximum execution time of 600 seconds exceeded`

2. Tried doing  php artisan migrate again but this time got `Migrating: 2019_02_12_182750_add_actiondate_to_actionlog In Connection.php line 669: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'action_date' (SQL: alter table `action_logs` ad
  d `action_date` datetime null) In PDOStatement.php line 129: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'action_date' In PDOStatement.php line 127: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'action_date'`

3. Tried to do `ALTER TABLE action_logs DROP COLUMN action_date` but same issue after trying to migrate again.

4.  Also tried everything suggested in https://snipe-it.readme.io/docs/common-issues

- Indicate whether or not you've manually edited any data directly in the database. No

Any help would be appreciated. Thank you!

**Comment by yosiasz** [comment]
@Gab-C how are you upgrading to newer version? What are you using?

**Comment by G13312** [comment]
@yosiasz Hello Yosiasz, Thanks for the reply! I am upgrading using `php upgrade.php`. We upgraded from v4.9.5.

**Comment by snipe** [comment]
Looks like migrations didn't complete successfully. Can you show me the output of `upgrade.php`?

**Comment by G13312** [comment]
Not sure if this is the right log but there it is. Thank you!
[upgradelogs.txt](https://github.com/snipe/snipe-it/files/5575431/upgradelogs.txt)

**Comment by snipe** [comment]
Yeah, so this is the part that's screwing you over:

```
In Connection.php line 669:
                                                                                                                       
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'action_date' (SQL: alter table `action_logs` ad  
  d `action_date` datetime null)                                                                                       
                                                                                                                       

In PDOStatement.php line 129:
                                                                                    
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'action_date'  
                                                                                    

In PDOStatement.php line 127:
                                                                                    
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'action_date'  
                                                                                    
```

Try running this in MySQL:

`INSERT INTO migrations  (migration, batch) VALUES(2019_02_12_182750_add_actiondate_to_actionlog, 10);`

**Comment by snipe** [comment]
Somehow your migrations got donked up. It's trying to execute a migration that somehow was already run (hence the "column already exists") error. By adding that record, we're telling the system that it already ran that migration, so it should skip past that one. Not sure how your migrations ended up donked, but we'll sort it out.

**Comment by G13312** [comment]
I tried running the MySQL command and got the following `Error Code: 1054. Unknown column '2019_02_12_182750_add_actiondate_to_actionlog' in 'field list'`

**Comment by snipe** [comment]
Blergh, sorry. It's a string. Try `INSERT INTO migrations (migration, batch) VALUES('2019_02_12_182750_add_actiondate_to_actionlog', 10);`

**Comment by G13312** [comment]
No worries! Seems like this worked, got 1 row affected. Should I run the upgrade.php again?

**Comment by snipe** [comment]
Yep

**Comment by G13312** [comment]
Wow that was quick! Already done without any errors! I'm gonna go test and see if I get any error on my snipe it.

**Comment by G13312** [comment]
Everything looks good!! Thanks a lot for your time and help!

**Comment by snipe** [comment]
Awesome! Glad you're all sorted :)
