### ISSUE TITLE
CSV Import for Locations - Only Parents Created

### ISSUE THREAD

**Issue by morgish** [grokability/snipe-it#8794]
#### Please confirm you have done the following before posting your bug report:

- [ N ] I have enabled debug mode 
- [ Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Importing CSV to create locations. Only Parent Locations are created, locations it self are not created.  CLI output during input says "- Non-parent Location SI8 could not be created: {"parent_id":["The parent id and id must be different."]}"

**To Reproduce**
Import CSV via CLI [CSV.zip](https://github.com/snipe/snipe-it/files/5571481/CSV.zip) 

**Expected behavior**
Locations to be included in their Parent Locations

**Screenshots**
![ImportResult1](https://user-images.githubusercontent.com/7067589/99763838-7c1ed580-2b47-11eb-8c4c-953c9b8cedb9.PNG)
![ImportResult2](https://user-images.githubusercontent.com/7067589/99763842-7de89900-2b47-11eb-9aae-c6ec501e3a4a.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: Centos 8
 - Web Server: 
 - PHP Version 7.2.24 

Hi All,

I'm pretty sure I have the CSV layout correct and my understanding is you can have multiple Locations under a Single Parent Location. 

Appreciate any help here, don't want to have to do this manually.

Cheers,
Kris

**Comment by morgish** [comment]
Just approached this a little bit differently, I ran the CSV with no parent locations, which created all of the entries. 
I then re-ran it again with the parent locations, which updated all locations to have their parent location included.

I feel this was a bit of a work around?

**Comment by snipe** [comment]
> Import CSV via CLI CSV.zip

I don't even know what that is? It must be something generated by Github?

You didn't answer the question in the issue template as to what version you're using, but we have a location importer. https://snipe-it.readme.io/docs/importing-locations

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing-locations">Importing Locations</a></strong></div><div>The signature for this is: php artisan snipeit:import-locations {filename} This importer will look in the storage/private_uploads/imports directory for your file, so you can just upload it using the Assets/Licenses/Etc importer, but call it directly from artisan. It will update existing fields based...</div></blockquote>

**Comment by snipe** [comment]
I have a fix out on develop now, if anyone is interested in giving it a shot.
