### ISSUE TITLE
Assistance for updating Snipe IT

### ISSUE THREAD

**Issue by Raffudeen** [grokability/snipe-it#8796]
Dears,

Please advice how to update snipe IT to the latest version in LINUX. My PHP version is 7.2.24.

**Comment by roratonet** [comment]
Have you installed it via GIT or downloading and extracting the folder?

**Comment by denzfarid** [comment]
> Dears,
> 
> Please advice how to update snipe IT to the latest version in LINUX. My PHP version is 7.2.24.

php ./{Snipe-it-app}/upgrade.php
see [documentation ](https://snipe-it.readme.io/docs/upgrading)
