### ISSUE TITLE
Names with special characters

### ISSUE THREAD

**Issue by tbasten** [grokability/snipe-it#8797]
#### Expected Behavior (or desired behavior if a feature request)

Then name displayed in "View User" Title is the same as the Name displayed in the User's contact information.

-----

#### Actual Behavior
Under the Info tab of a user who has an ' in their name, it displays `&#039;` instead. The name that is called in the Title for "View User [User's name] show's correct
-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  **Upgrade using git**
- Version of Snipe-IT you're running. **v5.0.6 build 5600 (g686ab681e)**
- Version of PHP you're running. **7.2.24-0ubuntu0.18.04.7**
 
- Version of MySQL/MariaDB you're running. **Server version: 10.1.47-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04**
- What OS and web server you're running Snipe-IT on. **Ubuntu 18.04**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc). **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error. **No**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. **https://itam.gsg.wa.edu.au/users/[userid]**
- Any errors that appear in your browser's error console. **No**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **Yes**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **Nothing that I could see**
- Include what you've done so far in the installation, and if you got any error messages along the way. Upgrade completed without issue. The issue only started happening in the latest version
- Indicate whether or not you've manually edited any data directly in the database. No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I can't reproduce this.

<img width="1065" alt="Screen Shot 2020-11-25 at 2 21 48 AM" src="https://user-images.githubusercontent.com/197404/100214680-04450800-2ec5-11eb-9a51-3e94cbf6f5b9.png">

Are these users old, or new? How were they created?

**Comment by snipe** [comment]
If they're older users, you can try running `php artisan snipeit:unescape`. If they're newer, I'd need more info on how they were created.

**Comment by tbasten** [comment]
I just tested it on the demo site by creating a new user. See below

![image](https://user-images.githubusercontent.com/12264887/100219558-1ec4c300-2f51-11eb-9acc-8364190eeef5.png)
