### ISSUE TITLE
Ability to create custom entities

### ISSUE THREAD

**Issue by yosiasz** [grokability/snipe-it#8800]
**Server (please complete the following information):**
 - Snipe-IT Version : 4.9.5
 - OS: Windows
 - Web Server: IIS
 - PHP Version 7.3.13

**Is your feature request related to a problem? Please describe.**
Currently we have out of the box entities: Assets, Licenses, Accessories, Kits, Consumables.
This pretty much limits one to these canned list. If I wanted to track a different type of 'asset' I cant

**Describe the solution you'd like**
It would be great to be able to create your own custom entity your company tracks.

**Describe alternatives you've considered**
Excel, or custom home grown application

**Additional context**
We might have custom entities we keep track within our company in a specific way
that does not fix the existing out of the box canned assets etc

Thanks!
Great product

**Comment by snipe** [comment]
I'm not really sure how we could make that work though. The different entities are different because there is different business logic around them.

**Comment by yosiasz** [comment]
by allowing admins to configure their own business rules but I think this is getting into what Service Now does :)
