### ISSUE TITLE
Printing on Avery 61526 labels.

### ISSUE THREAD

**Issue by chris-jasztrab** [grokability/snipe-it#8805]
#### Expected Behavior (or desired behavior if a feature request)

Setting label print options are not working as expected.  I am trying to print on Avery 61526 labels.  They are 30 per sheet and have the following dimensions.

Labels are 2" wide by 3/4" high

Font size is 9pt

Spacing is .625" horizonal and .25 vertical.

Margins are all .625

Page is 8.5 x 11

I would expect with those dimensions that it would print the labels in 3 columns. Instead it is showing 4.  This throws it totally out of whack.
-----

#### Actual Behavior

I would expect with those dimensions that it would print the labels in 3 columns. Instead it is showing 4.  This throws it totally out of whack.

-----

#### Please confirm you have done the following before posting your bug report:

ENABLED DEBUG MODE
READ THE COMMON ISSUES

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
      FRESH INSTALL
- Version of Snipe-IT you're running
     Version v4.9.5 - build 4482 (master)

- Version of PHP you're running
     PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies

- Version of MySQL/MariaDB you're running
Server version: 10.1.47-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

- What OS and web server you're running Snipe-IT on
Ubuntu 18.04 / Apache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  Manual install

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A  no debug messages are shown on the print label page.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Print Labels

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
YES

- Include any additional information you can find in `storage/logs` and your webserver's logs.
NO

- Include what you've done so far in the installation, and if you got any error messages along the way.
Nothing apart from creating assets, models, etc

- Indicate whether or not you've manually edited any data directly in the database
NO

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by yosiasz** [comment]
Maybe download and use Avery Word Template and do a mail merge of your data? or create it yourself as custom label template.

![image](https://user-images.githubusercontent.com/900951/100146218-6ca4d280-2e4e-11eb-956c-e4dccc8bf78e.png)

**Comment by chris-jasztrab** [comment]
Using the settings above (which IMHO don't match the actual label at all) I was able to get it to work enough to be functional.  Thank-you for pointing me in the correct direction.
