### ISSUE TITLE
Email notifications use wrong branding (v5.0.7)

### ISSUE THREAD

**Issue by ISNL-PimP** [grokability/snipe-it#8810]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When Snipe-IT sends an email, it uses the default site logo instead of the email logo specified in Settings > Branding.

**To Reproduce**
1. Upload different logos for 'Logo' and 'Email logo' under /admin/branding
2. Send a test email

**Expected behavior**
The 'Email logo' image is used in the test message

**Actual behavior**
The 'Logo' image is used in the test message. This is likely caused by this piece of code: [message.blade.php](https://github.com/snipe/snipe-it/blob/4e0c8e218da5ee6568cde946d7bade49b9759c9b/resources/views/vendor/mail/html/message.blade.php)

**Screenshots**
In /admin/branding:
![image](https://user-images.githubusercontent.com/59050598/100191817-163ca000-2ef1-11eb-8aba-2bd4dedf0743.png)

Test message received:
![image](https://user-images.githubusercontent.com/59050598/100191844-26547f80-2ef1-11eb-9f8e-465e2f886ff4.png)

**Server:**
 - Snipe-IT Version: 5.0.7
 - OS: Ubuntu 20.04
 - Web Server: Apache2
 - PHP Version:

**Desktop:**
 - OS: Windows 10
 - Browser: Edge Chromium
 - Version: 87.0.66.47

**Comment by ISNL-PimP** [comment]
Rapid response, thanks @snipe !

**Comment by snipe** [comment]
No problem - thanks for the heads up!
