### ISSUE TITLE
Cannot upgrade from 4.9.5 to any 5.x in Azure running docker ERROR 500

### ISSUE THREAD

**Issue by tarmoinno** [grokability/snipe-it#8811]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When selecting any version what is newer then 4.9.5 I will get ERROR 500
from the conteiner log it will say everything is OK
2020-11-25T07:30:30.626Z INFO  - docker run -d -p 6680:80 --name varad_1_97a1bd04 -e WEBSITE_SITE_NAME=xxxx -e WEBSITE_AUTH_ENABLED=False -e PORT=80 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=xxxxx.azurewebsites.net -e WEBSITE_INSTANCE_ID=sdadasdsadasdas -e HTTP_LOGGING_ENABLED=1 snipe/snipe-it:latest  

**To Reproduce**
If I change the version and reboot conteiner then it will not come up anymore
If I change it back to version v4.9.5 it will come up and working fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/14308732/100198526-a0423400-2f04-11eb-9669-5e24af93cef6.png)
**Server (please complete the following information):**
 - Snipe-IT Version 5.0.9
 - it is default docker setup in Azure.

**Desktop (please complete the following information):**
 - OS:  WIN 10
 - Browser any 
 

**Error Messages**
`

(3/3) QueryExceptionSQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'action_date' (SQL: alter table `action_logs` add `action_date` datetime null)
--
in Connection.php line 669
at Connection->runQueryCallback('alter table `action_logs` add `action_date` datetime null', array(), object(Closure))in Connection.php line 629
at Connection->run('alter table `action_logs` add `action_date` datetime null', array(), object(Closure))in Connection.php line 464
at Connection->statement('alter table `action_logs` add `action_date` datetime null')in Blueprint.php line 97
at Blueprint->build(object(MySqlConnection), object(MySqlGrammar))in Builder.php line 290
at Builder->build(object(Blueprint))in Builder.php line 151
at Builder->table('action_logs', object(Closure))in Facade.php line 261
at Facade::__callStatic('table', array('action_logs', object(Closure)))in 2019_02_12_182750_add_actiondate_to_actionlog.php line 18
at AddActionDateToActionlog->up()in Migrator.php line 392
at Migrator->Illuminate\Database\Migrations\{closure}()in Migrator.php line 401
at Migrator->runMigration(object(AddActionDateToActionlog), 'up')in Migrator.php line 200
at Migrator->runUp('/var/www/html/database/migrations/2019_02_12_182750_add_actiondate_to_actionlog.php', 3, false)in Migrator.php line 165
at Migrator->runPending(array('/var/www/html/database/migrations/2019_02_12_182750_add_actiondate_to_actionlog.php', '/var/www/html/database/migrations/2019_02_17_205048_add_label_logo_to_settings.php', '/var/www/html/database/migrations/2019_07_23_140906_add_show_assigned_assets_to_settings.php', '/var/www/html/database/migrations/2019_08_20_084049_add_custom_remote_user_header.php', '/var/www/html/database/migrations/2019_12_04_223111_passport_upgrade.php', '/var/www/html/database/migrations/2020_02_04_172100_add_ad_append_domain_settings.php', '/var/www/html/database/migrations/2020_04_29_222305_add_saml_fields_to_settings.php', '/var/www/html/database/migrations/2020_10_22_233743_move_accessory_checkout_note_to_join_table.php', '/var/www/html/database/migrations/2020_10_23_161736_fix_zero_values_for_locations.php', '/var/www/html/database/migrations/2020_11_18_214827_widen_license_serial_field.php'), array('pretend' => false, 'step' => false))in Migrator.php line 110
at Migrator->run(array('/var/www/html/database/migrations'), array('pretend' => false, 'step' => false))in MigrateCommand.php line 71
at MigrateCommand->handle()
at call_user_func_array(array(object(MigrateCommand), 'handle'), array())in BoundMethod.php line 32
at BoundMethod::Illuminate\Container\{closure}()in Util.php line 36
at Util::unwrapIfClosure(object(Closure))in BoundMethod.php line 90
at BoundMethod::callBoundMethod(object(Application), array(object(MigrateCommand), 'handle'), object(Closure))in BoundMethod.php line 34
at BoundMethod::call(object(Application), array(object(MigrateCommand), 'handle'), array(), null)in Container.php line 590
at Container->call(array(object(MigrateCommand), 'handle'))in Command.php line 134
at Command->execute(object(ArrayInput), object(OutputStyle))in Command.php line 255
at Command->run(object(ArrayInput), object(OutputStyle))in Command.php line 121
at Command->run(object(ArrayInput), object(BufferedOutput))in Application.php line 1001
at Application->doRunCommand(object(MigrateCommand), object(ArrayInput), object(BufferedOutput))in Application.php line 271
at Application->doRun(object(ArrayInput), object(BufferedOutput))in Application.php line 147
at Application->run(object(ArrayInput), object(BufferedOutput))in Application.php line 93
at Application->run(object(ArrayInput), object(BufferedOutput))in Application.php line 185
at Application->call('migrate', array('--force' => true), null)in Kernel.php line 273
at Kernel->call('migrate', array('--force' => true))in Facade.php line 261
at Facade::__callStatic('call', array('migrate', array('--force' => true)))in DashboardController.php line 38
at DashboardController->getIndex()
at call_user_func_array(array(object(DashboardController), 'getIndex'), array())in Controller.php line 54
at Controller->callAction('getIndex', array())in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(DashboardController), 'getIndex')in Route.php line 219
at Route->runController()in Route.php line 176
at Route->run()in Router.php line 681
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in AssetCountForSidebar.php line 56
at AssetCountForSidebar->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CreateFreshApiToken.php line 50
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForTwoFactor.php line 53
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckLocale.php line 37
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in VerifyCsrfToken.php line 76
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Router.php line 683
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 658
at Router->runRoute(object(Request), object(Route))in Router.php line 624
at Router->dispatchToRoute(object(Request))in Router.php line 613
at Router->dispatch(object(Request))in Kernel.php line 170
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in InjectDebugbar.php line 65
at InjectDebugbar->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in SecurityHeaders.php line 26
at SecurityHeaders->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForSetup.php line 26
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in StartSession.php line 56
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForMaintenanceMode.php line 63
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in HandlePreflight.php line 29
at HandlePreflight->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Kernel.php line 145
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 110
at Kernel->handle(object(Request))in index.php line 58

`
**Additional context**
- linux docker in Azure
- via docker automatic install, has worked very well under below version 5.
- no database changes, but database is running as seperate Azure service

**Comment by snipe** [comment]
Looks like something got donked up with your migrations. What's in the contents of your migrations table?

**Comment by tarmoinno** [comment]
Sending the migration tabel.
[migrations.zip](https://github.com/snipe/snipe-it/files/5595637/migrations.zip)
I always used snipe/snipe-it:latest command for the version. But it did not work for the v5* and we have used since locked v4.9.5. But would like to upgrade if possible.

**Comment by snipe** [comment]
What was the output when you ran migrations? You're definitely missing some.

> But it did not work for the v5* and we have used since locked v4.9.5. But would like to upgrade if possible.

What does "it did not work" mean? Did you get errors? If so, what were they?

**Comment by tarmoinno** [comment]
Sorry I think I do not understand what information you need.
If I run upgrade without debug = false then I will get just Error 500.
If I run upgrade with debug = true, then I will get this error 
"3/3) QueryExceptionSQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'action_date' (SQL: alter table action_logs add action_date datetime null)" what I included in my first post.
What i should do t o give you more information? 
All application settings are coming from here:
![image](https://user-images.githubusercontent.com/14308732/100214290-64b16500-2f18-11eb-86fb-92f0d0b26a83.png)

**Comment by snipe** [comment]
I don't know how your migrations managed to get messed up....

You can try directly inserting the migration records into the migrations table:

`insert into migrations ('migration', 'batch') values ('2019_02_12_182750_add_actiondate_to_actionlog', '3');` and then trying migrations again.

**Comment by tarmoinno** [comment]
Thank you. Got version now 5.0.9.
Case closed.
