### ISSUE TITLE
Server Error 500 after saving admin settings (after upgrade to 5.0.9)

### ISSUE THREAD

**Issue by ArcheNoah77** [grokability/snipe-it#8813]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I try to save certain admin settings (e.g. security, ldap) the server error 500 comes up. In debug mode the error message appears below

**To Reproduce**
1. Upgrade to v.5.0.9
2. Click on Settings and security
3. Scroll down to Save and "save"
4. See Server Error 500

### (3/3) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'login_remote_user_header_name' in 'field list' (SQL: update `settings` set `login_remote_user_custom_logout_url` = ?, `login_remote_user_header_name` = ?, `settings`.`updated_at` = 2020-11-25 09:51:33 where `id` = 1)
--
in Connection.php line 669

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.9
 - OS: Ubuntu 20.04
 - Web Server: Apache2
 - PHP Version 7.4.3

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser Edge, Chrome

**Error Messages**

(3/3) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'login_remote_user_header_name' in 'field list' (SQL: update `settings` set `login_remote_user_custom_logout_url` = ?, `login_remote_user_header_name` = ?, `settings`.`updated_at` = 2020-11-25 10:14:48 where `id` = 1)
--
in Connection.php line 669

(2/3) PDOExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'login_remote_user_header_name' in 'field list'
--
in PDOConnection.php line 66

1/3) PDOExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'login_remote_user_header_name' in 'field list'
--
in PDOConnection.php line 64

**Comment by ArcheNoah77** [comment]
i already did "php artisan migrate" and 

php artisan clear-compiled
php artisan clear
php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan config:clear

**Comment by snipe** [comment]
What was the output of `php artisan migrate`? Clearly migrations didn't complete successfully.

**Comment by ArcheNoah77** [comment]
that the "permisson_group_table" already exist

**Comment by snipe** [comment]
That doesn't make any sense though.... your migrations has `2019_06_12_184327_rename_groups_table` in it, which tells the system that migration was completed. The next one that should fire is `2019_02_12_182750_add_actiondate_to_actionlog` based on what you have in there.

**Comment by ArcheNoah77** [comment]
Sorry for the late reply. I first had to duplicate the server in a test environment.

The exact output of "php artisan migrate" is:


**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migrating: 2019_06_12_184327_rename_groups_table

In Connection.php line 669:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permission_groups' already exists (SQL: rename table `groups` to `permission_groups`)


In PDOStatement.php line 129:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permission_groups' already exists


In PDOStatement.php line 127:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permission_groups' already exists

**Comment by ArcheNoah77** [comment]
Hello,

still the same problem after Upgrade to 5.1.10
Any ideas?

**Comment by joeldeteves** [comment]
I am having the exact same issue, but whenever I click on a user.

Also, "People" is suddenly showing up blank, and I am unable to assign assets to any user.

Running the docker version of Snipe-it, so no upgrade screw-ups afaik? We just change our docker image version and deploy that's it.

UPDATE: I exec'ed into the container and ran the `php artisan migrate` command per instructions from @snipe earlier up the thread and this sovled my problem - sorry to bother, I assumed this was handled whenever a new version of the container image is deployed.

I will leave my fix in the thread in case anyone else has this problem.

**Comment by JonathonReinhart** [comment]
> I assumed this was handled whenever a new version of the container image is deployed.

@joeldeteves Many other Docker images do just that; they always run the "migrate" command during container startup. It would be convenient if snipe-it would do the same.

*Edit: The docker image is *supposed* to do that (since #6680), but the startup script is broken (see #8953).*

**Comment by SirajQu** [comment]
I have the same issue after upgrading to v5.0.12 
First in the pre-flight set up I ran the command "php artisan migrate"
and it worked.

Later, I have imported old SQL database from old version of Snipe-IT using HeidiSQL MariaDB and then I tried to run the command again 
"php artisan migrate"
but now it give this error:

Migrating: 2019_06_12_184327_rename_groups_table

In Connection.php line 669:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permission_groups' already exists (SQL: rename tabl
  e `groups` to `permission_groups`)


In PDOStatement.php line 129:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permission_groups' already exists


In PDOStatement.php line 127:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permission_groups' already exists


Also I ran these commands but still the same:
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear



I hope we find solution for this.

**Comment by Um6ra** [comment]
Hello,

I have the same problem after upgrading from 4.8.0 to 5.1.3.


Migrating: 2019_06_12_184327_rename_groups_table

In Connection.php line 669:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permission_groups' already exists (SQL: rename table `groups` to `permission_groups`)

In Exception.php line 18:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permission_groups' already exists


In PDOStatement.php line 115:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permission_groups' already exists


I ran the same commands like @SirajQu.

**Comment by iaingeorge** [comment]
I experienced this recently on my Snipe-IT install. I was getting the same error as above, which seems to be related to an inability of it to migrate the database if the 'permission_groups" table exists on the MySQL server.

When running the php artisan migrate command I was seeing:

``Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permission_groups' already exists (SQL: rename table `groups` to `permission_groups`)``

To repair this on my install (v5.1.8) I did the following. I manually dropped the 'permissions_groups' in MySQL. Then I re-ran the php upgrade.php command, and it seemed to get through the database migration correctly. Snipe-IT is back up and working on my system!

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
