### ISSUE TITLE
Server Error: Unauthorized.

### ISSUE THREAD

**Issue by Jannik2017** [grokability/snipe-it#8816]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Server Error: Unauthorized. is displayed if i want to Save Assets or Licenses

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Locations'
3. Click on 'Main Categorie'
4. Click on 'New'
5. Click on 'Save'
6. See error

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Versionv5.0.6 build 5526 (g8a7cd8764)
 - OS:  Suse Leap 15.1
 - Web Server: Apache
 - PHP Version  7.2

**Desktop (please complete the following information):**
 - OS:  Windows 7/10
 - Browser chrome and firefox

**Additional context**
-fresh install 
- manual installation

My Problem is that i cant create Assets Licenses or Locations
if i want to proceed with save aafter Entering the details Snipe it gets a Server Error: Unauthorized.
like on the Screenshot below i tried to upgrade Snipeit via upgrade.php but this have no effect on the Problem

![Bildschirmfoto_2020-11-25_08-47-47](https://user-images.githubusercontent.com/25689308/100251568-33985b00-2f3f-11eb-96d1-03704217dc47.png)

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Jannik2017** [comment]
![Bildschirmfoto_2020-11-25_17-10-30](https://user-images.githubusercontent.com/25689308/100253265-2e3c1000-2f41-11eb-953d-1c5abcf6a78d.png)

**Comment by Jannik2017** [comment]
i guess that must be a database connection error because if i create a user it says in users


No matching records found
--
the Users are in the Database but SnipeIT cant reach 
because the connection failture the function not know that the user admin is real
![Bildschirmfoto_2020-11-25_17-27-26](https://user-images.githubusercontent.com/25689308/100255256-94c22d80-2f43-11eb-8166-be67c756c4a8.png)

**Comment by snipe** [comment]
It's not a database connection issue. 

As I mentioned in the other issue, you need to tell me what you've tried, specifically:

https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated
https://snipe-it.readme.io/docs/common-issues#quick-tip-handy-commands

And post the output of the commands mentioned in both of those links.

You can then try a `git pull` and try running `php upgrade.php` again.

Also please state the version of Snipe-IT you're using. 

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues#quick-tip-handy-commands">Common Issues</a></strong></div><div>  These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin.These commands clear out cached service files that help speed up modern PHP applications but can also very occasionally be out of date, resu...</div></blockquote>

**Comment by Jannik2017** [comment]
Snipe-IT Versionv5.0.6 build 5526 (g8a7cd8764)
The linked articles unfortunately do not fit to the problem

**Comment by snipe** [comment]
Please explain what you actually did, and what the output of those commands each were. The linked articles have resolved just about every example of "Unauthorized". If there's something else happening, seeing your output could be helpful

**Comment by snipe** [comment]
Another few questions - do you have values in LDAP and/or Slack integration in Settings?

This is our current set of Settings model validation rules. I'm wondering if it's failing somewhere for you because of missing/bad data that we didn't validate against before. (I'd still have expected to an unspecified "Please check the form for errors" message at the top tho.)

```
protected $rules = [
          'brand'                               => 'required|min:1|numeric',
          'qr_text'                             => 'max:31|nullable',
          'logo_img'                            => 'mimes:jpeg,bmp,png,gif', // I'm not sure this is correct?
          'alert_email'                         => 'email_array|nullable',
          'admin_cc_email'                      => 'email|nullable',
          'default_currency'                    => 'required',
          'locale'                              => 'required',
          'slack_endpoint'                      => 'url|required_with:slack_channel|nullable',
          'labels_per_page'                     => 'numeric',
          'slack_channel'                       => 'regex:/^[\#\@]?\w+/|required_with:slack_endpoint|nullable',
          'slack_botname'                       => 'string|nullable',
          'labels_width'                        => 'numeric',
          'labels_height'                       => 'numeric',
          'labels_pmargin_left'                 => 'numeric|nullable',
          'labels_pmargin_right'                => 'numeric|nullable',
          'labels_pmargin_top'                  => 'numeric|nullable',
          'labels_pmargin_bottom'               => 'numeric|nullable',
          'labels_display_bgutter'              => 'numeric|nullable',
          'labels_display_sgutter'              => 'numeric|nullable',
          'labels_fontsize'                     => 'numeric|min:5',
          'labels_pagewidth'                    => 'numeric|nullable',
          'labels_pageheight'                   => 'numeric|nullable',
          'login_remote_user_enabled'           => 'numeric|nullable',
          'login_common_disabled'               => 'numeric|nullable',
          'login_remote_user_custom_logout_url' => 'string|nullable',
          'login_remote_user_header_name'       => 'string|nullable',
          'thumbnail_max_h'                     => 'numeric|max:500|min:25',
          'pwd_secure_min'                      => 'numeric|required|min:8',
          'audit_warning_days'                  => 'numeric|nullable',
          'audit_interval'                      => 'numeric|nullable',
          'custom_forgot_pass_url'              => 'url|nullable',
          'privacy_policy_link'                 => 'nullable|url',
    ];
```

**Comment by Jannik2017** [comment]
which output should i have to display ?
i dont use LDAP or Slack Settings

**Comment by Jannik2017** [comment]
composer clear-compiled
Wenn 'composer' kein Tippfehler ist, können Sie command-not-found benutzen, um das Paket zu finden, das den Befehl enthält, z. B.:
    cnf composer
 php artisan config:clear
san view:clear
php artisan cache:clear
php artisan route:clearConfiguration cache cleared!
 php artisan view:clear
Compiled views cleared!
 php artisan cache:clear
Application cache cleared!

**Comment by snipe** [comment]
I don’t speak German, but that output looks okay to me. Did you delete the bootstrap caches as recommended?

What’s the output of `php -m`?

**Comment by Jannik2017** [comment]
jannik@Jannik:~> php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
gd
hash
iconv
imagick
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]

**Comment by slaviknowsbest** [comment]
Hi everyone, 

Any resolution on this issue? I have absolutely the same issue.

Thanks
