### ISSUE TITLE
Unable to save settings for branding

### ISSUE THREAD

**Issue by thetiagomatos** [grokability/snipe-it#8817]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

This was already reported on the unaccepted assets (#8715).
We upgraded from 4.9.6 to 5.0.9, and I was very excited to know there finally is a logo option for the labels... but I couldn't save it due to this bug:

Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Feature-Policy header: Unrecognized feature: 'animations'.
Error with Feature-Policy header: Unrecognized feature: 'battery'.
Error with Feature-Policy header: Unrecognized feature: 'display-capture'.
Error with Feature-Policy header: Unrecognized feature: 'legacy-image-formats'.
Error with Feature-Policy header: Unrecognized feature: 'oversized-images'.
Error with Feature-Policy header: Unrecognized feature: 'publickey-credentials'.
Error with Feature-Policy header: Unrecognized feature: 'unsized-media'.
Error with Feature-Policy header: Unrecognized feature: 'vibrate'.
Error with Feature-Policy header: Unrecognized feature: 'wake-lock'.

**EDIT** 
I can't save any type of setting.
Also, when selecting a model, the names are showing up like this (only while selecting the model, the model name is displayed correctly on the dashboard)

![image](https://user-images.githubusercontent.com/63238335/100260246-182e4f80-2f41-11eb-8903-e3143dff377a.png)

I can't fid any error on this one while in debug mode.

Tried mozila, opera, chrome, edge... icognito windows.. nothing seems to solve it.

**To Reproduce**
Steps to reproduce the settings error
1. Go to 'settings'
2. Click on 'branding'
3. Try to save 'settings'
4. See error, check on browser console if it doesn't show everything on the page.

Steps to reproduce the model error:
1. Create a an asset, and select the model.

**Expected behavior**
Expected to successfully save the settings, and expected the model name to look like "Computers - Macbook Pro 15"

**Screenshots**

![image](https://user-images.githubusercontent.com/63238335/100257885-54ac7c00-2f3e-11eb-85ce-6beaf6317991.png)
![image](https://user-images.githubusercontent.com/63238335/100260369-398f3b80-2f41-11eb-9b98-b4b0a783e5bc.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 5.0.9
 - OS: [e.g. Ubuntu, CentOS] Ubunto 18.04.7
 - Web Server: [e.g. Apache, IIS]: NGINX
 - PHP Version: 7.2.24

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 87.0.4280.66 

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:
Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Feature-Policy header: Unrecognized feature: 'animations'.
Error with Feature-Policy header: Unrecognized feature: 'battery'.
Error with Feature-Policy header: Unrecognized feature: 'display-capture'.
Error with Feature-Policy header: Unrecognized feature: 'legacy-image-formats'.
Error with Feature-Policy header: Unrecognized feature: 'oversized-images'.
Error with Feature-Policy header: Unrecognized feature: 'publickey-credentials'.
Error with Feature-Policy header: Unrecognized feature: 'unsized-media'.
Error with Feature-Policy header: Unrecognized feature: 'vibrate'.
Error with Feature-Policy header: Unrecognized feature: 'wake-lock'.

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console: Same as the top ones.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo: Can only reproduce the model bug, not the other one.
- Include any additional information you can find in `storage/logs` and your webserver's logs: No relevant info on the logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on: Ubuntu server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git
- Include what you've done so far in the installation, and if you got any error messages along the way. No errors.
- Indicate whether or not you've manually edited any data directly in the database: No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

Keep up the good work guys! 💯

**Comment by thetiagomatos** [comment]
Can this be the cause of the whole issue? Since im not being able to save anything, i cant set this to 8, and the minimum allowed is 8:
![image](https://user-images.githubusercontent.com/63238335/100265986-f769f800-2f48-11eb-8522-72c96b4ac815.png)

This one says it's saved successfully, but it's not.

This doesn't show up in the debug mode.

**Comment by snipe** [comment]
It's in the release notes... Password limit has to be 8 or more.

**Comment by snipe** [comment]
But no, if you can't set it to 8, something else seems off. 

Can you enable the debugbar and/or tail the logs when you try to save the password to 8 minimum?

I'm curious to see if there are any logs being generated by attempting to save that value, and also in the debug bar I'm curious if there's anything in the Request tab that might be helpful.... For example, if there's some model level validation that's being tripped (which would be the case in the 8-minimum limit on password), we'd see that in an error bag in the `session_attributes` section under Request.

**Comment by snipe** [comment]
(This is what that would look like)

<img width="803" alt="Screen Shot 2020-11-25 at 10 18 14 AM" src="https://user-images.githubusercontent.com/197404/100266989-91a94c00-2f07-11eb-9e5d-77fb92bc9b97.png">

**Comment by thetiagomatos** [comment]
I did not notice these... But these were way earlier, no logs are being generated after saving the minimum value:
![image](https://user-images.githubusercontent.com/63238335/100267658-b4f5ea80-2f4b-11eb-959b-8d2f9ec7b127.png)

This looks normal, after "saving" the value, this is the session attributes:
![image](https://user-images.githubusercontent.com/63238335/100267858-0f8f4680-2f4c-11eb-94ee-d9e69d123a93.png)

**Comment by snipe** [comment]
And you're not getting an error, but it's not saving, correct? (You're getting a green "saved successfully" banner at the top of the page?)

**Comment by thetiagomatos** [comment]
Sorry for the long time answering, I needed to get out.
At this particular setting, yeah. But at the other ones, e.g branding settings, I get the red banner when i save, and this is the session attribute output: 

![image](https://user-images.githubusercontent.com/63238335/100272273-bb3b9500-2f52-11eb-8b0f-e032dc46013a.png)

If this 8 character min is the problem here, will I need to rollback, change the setting to 8, and upgrade again?

**Comment by snipe** [comment]
Well what's weird here is that I'd fully expect you to be able to save that updated password minimum requirement there, since it *would* be passing validation as long as the number was greater than 8. I'm baffled as to why it's not saving that. I don't think other folks have had an issue.

Edit: Ugh, I just realized I had replied to the wrong Github issue with this part:

-------------

Another few questions - do you have values in LDAP and/or Slack integration in Settings?

This is our current set of Settings model validation rules. I'm wondering if it's failing somewhere for you because of missing/bad data that we didn't validate against before. (I'd still have expected to an unspecified "Please check the form for errors" message at the top tho.)

```
protected $rules = [
          'brand'                               => 'required|min:1|numeric',
          'qr_text'                             => 'max:31|nullable',
          'logo_img'                            => 'mimes:jpeg,bmp,png,gif', // I'm not sure this is correct?
          'alert_email'                         => 'email_array|nullable',
          'admin_cc_email'                      => 'email|nullable',
          'default_currency'                    => 'required',
          'locale'                              => 'required',
          'slack_endpoint'                      => 'url|required_with:slack_channel|nullable',
          'labels_per_page'                     => 'numeric',
          'slack_channel'                       => 'regex:/^[\#\@]?\w+/|required_with:slack_endpoint|nullable',
          'slack_botname'                       => 'string|nullable',
          'labels_width'                        => 'numeric',
          'labels_height'                       => 'numeric',
          'labels_pmargin_left'                 => 'numeric|nullable',
          'labels_pmargin_right'                => 'numeric|nullable',
          'labels_pmargin_top'                  => 'numeric|nullable',
          'labels_pmargin_bottom'               => 'numeric|nullable',
          'labels_display_bgutter'              => 'numeric|nullable',
          'labels_display_sgutter'              => 'numeric|nullable',
          'labels_fontsize'                     => 'numeric|min:5',
          'labels_pagewidth'                    => 'numeric|nullable',
          'labels_pageheight'                   => 'numeric|nullable',
          'login_remote_user_enabled'           => 'numeric|nullable',
          'login_common_disabled'               => 'numeric|nullable',
          'login_remote_user_custom_logout_url' => 'string|nullable',
          'login_remote_user_header_name'       => 'string|nullable',
          'thumbnail_max_h'                     => 'numeric|max:500|min:25',
          'pwd_secure_min'                      => 'numeric|required|min:8',
          'audit_warning_days'                  => 'numeric|nullable',
          'audit_interval'                      => 'numeric|nullable',
          'custom_forgot_pass_url'              => 'url|nullable',
          'privacy_policy_link'                 => 'nullable|url',
    ];
```
-------------
Let's try this, just to rule it out:

In `app\Models\Setting.php`, change that number in the above validation to `5`, save the file and try saving the password settings again. Then tell me if you're still having issues. (You should be able to change it back to `8` once it's successfully saves.)

**Comment by thetiagomatos** [comment]
Tried to change the value, still no luck. Min value still remains at 8 and it won't save.
Yes, I have ldap configs done, but they're not active.

**Comment by snipe** [comment]
8 is still what’s displayed in the debug bar? Or in the web ui?

**Comment by thetiagomatos** [comment]
Both: 
![image](https://user-images.githubusercontent.com/63238335/100281874-92bb9700-2f62-11eb-9375-25dc0ce7af31.png)

**Comment by thetiagomatos** [comment]
But now it shows as an error

**Comment by thetiagomatos** [comment]
Hay there. We are gonna restore a snapshot, apply the correct setting before upgrade, and proceed to do the upgrade again.
One thing, please note the model name issue, its reproducible on your demo.

Demo screenshot (yours actually looks better, but still, those alphanumeric characters weren't there before):
![image](https://user-images.githubusercontent.com/63238335/100294168-cd7ef880-2f7d-11eb-9b61-765ea1ffb591.png)
 

Best regards! :)

**Comment by thetiagomatos** [comment]
**Update: I have changed the setting and upgraded again. Now, instead of the red banner, I get the green one but still, I'm not able to change the settings.

These are the last logs:**

[2020-11-26 10:35:31] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Passport\Passport::personalAccessTokensExpireIn() in /bright/snipe/app/Providers/AuthServiceProvider.php:92
Stack trace:
#0 [internal function]: App\Providers\AuthServiceProvider->boot()
#1 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#4 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#5 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\Container\Container->call(Array)
#6 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AuthServiceProvider))
#7 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AuthServiceProvider), 28)
#8 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#9 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#10 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#11 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\Foundation\Console\Kernel->bootstrap()
#13 /bright/snipe/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  
[2020-11-26 10:35:31] production.ERROR: Call to undefined method Laravel\Passport\Passport::personalAccessTokensExpireIn() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Laravel\\Passport\\Passport::personalAccessTokensExpireIn() at /bright/snipe/app/Providers/AuthServiceProvider.php:92)
[stacktrace]
#0 [internal function]: App\\Providers\\AuthServiceProvider->boot()
#1 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#6 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\AuthServiceProvider))
#7 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\AuthServiceProvider), 28)
#8 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#9 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#10 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#11 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#12 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#13 /bright/snipe/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 {main}
"} 
[2020-11-26 10:35:31] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Passport\Passport::personalAccessTokensExpireIn() in /bright/snipe/app/Providers/AuthServiceProvider.php:92
Stack trace:
#0 [internal function]: App\Providers\AuthServiceProvider->boot()
#1 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#4 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#5 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\Container\Container->call(Array)
#6 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AuthServiceProvider))
#7 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AuthServiceProvider), 28)
#8 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#9 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#10 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#11 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\Foundation\Console\Kernel->bootstrap()
#13 /bright/snipe/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  
[2020-11-26 10:35:31] production.ERROR: Call to undefined method Laravel\Passport\Passport::personalAccessTokensExpireIn() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Laravel\\Passport\\Passport::personalAccessTokensExpireIn() at /bright/snipe/app/Providers/AuthServiceProvider.php:92)
[stacktrace]
#0 [internal function]: App\\Providers\\AuthServiceProvider->boot()
#1 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#6 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\AuthServiceProvider))
#7 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\AuthServiceProvider), 28)
#8 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#9 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#10 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#11 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#12 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#13 /bright/snipe/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 {main}
"} 
[2020-11-26 10:35:31] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Passport\Passport::personalAccessTokensExpireIn() in /bright/snipe/app/Providers/AuthServiceProvider.php:92
Stack trace:
#0 [internal function]: App\Providers\AuthServiceProvider->boot()
#1 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#4 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#5 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\Container\Container->call(Array)
#6 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AuthServiceProvider))
#7 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AuthServiceProvider), 28)
#8 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#9 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#10 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#11 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\Foundation\Console\Kernel->bootstrap()
#13 /bright/snipe/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  
[2020-11-26 10:35:31] production.ERROR: Call to undefined method Laravel\Passport\Passport::personalAccessTokensExpireIn() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Laravel\\Passport\\Passport::personalAccessTokensExpireIn() at /bright/snipe/app/Providers/AuthServiceProvider.php:92)
[stacktrace]
#0 [internal function]: App\\Providers\\AuthServiceProvider->boot()
#1 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#6 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\AuthServiceProvider))
#7 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\AuthServiceProvider), 28)
#8 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#9 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#10 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#11 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#12 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#13 /bright/snipe/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 {main}
"} 
[2020-11-26 10:35:31] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Passport\Passport::personalAccessTokensExpireIn() in /bright/snipe/app/Providers/AuthServiceProvider.php:92
Stack trace:
#0 [internal function]: App\Providers\AuthServiceProvider->boot()
#1 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#4 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#5 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\Container\Container->call(Array)
#6 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AuthServiceProvider))
#7 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AuthServiceProvider), 28)
#8 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#9 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#10 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#11 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\Foundation\Console\Kernel->bootstrap()
#13 /bright/snipe/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  
[2020-11-26 10:35:31] production.ERROR: Call to undefined method Laravel\Passport\Passport::personalAccessTokensExpireIn() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Laravel\\Passport\\Passport::personalAccessTokensExpireIn() at /bright/snipe/app/Providers/AuthServiceProvider.php:92)
[stacktrace]
#0 [internal function]: App\\Providers\\AuthServiceProvider->boot()
#1 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 /bright/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#6 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\AuthServiceProvider))
#7 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\AuthServiceProvider), 28)
#8 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#9 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#10 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#11 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#12 /bright/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#13 /bright/snipe/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 {main}
"} 

Please help, this is a production instance, I'm risking my job bc I thought it was working... but it isnt...

**Comment by Markryan-bear** [comment]
i faced the same issue, i just create a new snipe 5.1.4 use windows2016+IIS, before i used centos7, whatever branding setting or localization setting, always show Error: Please check the form below for errors, but no error shows below, in debug, it says pwd secure min must be at least 8
