### ISSUE TITLE
Failed to load image after upgrade SnipeIT docker version v4.9.5 to v5.0.9

### ISSUE THREAD

**Issue by bvivi57** [grokability/snipe-it#8822]
#### Expected Behavior (or desired behavior if a feature request)
Update my version of snipeIT deployed as a container and keep access to the images associated with my accessories.

-----

#### Actual Behavior
Everything seems to work correctly except the access to the images. When I click on an accessory I get the following error
"Failed to laod image: http://127.0.0.1:80/uploads/accessories/accessory-xxxxxxxx.jpg"

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade docker version  v4.9.5 to v5.0.9

- Version of Snipe-IT you're running
Docker image v5.0.9 : v5.0.9 build 5616 (973eacf6c3) 

- Version of PHP you're running
7.2.24-0ubuntu0.18.04.6 

- Version of MySQL/MariaDB you're running
Docker image mysql:5.6

- What OS and web server you're running Snipe-IT on
Docker version 19.03.12, build 48a66213fe on CentOS Linux release 8.2.2004

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker

-----

##my actions
1) change tag on my docker-compose file for snipe/snipe-it:v5.0.9
2) restart my docker-compose (snipeIT+MariaDB)
3) access to shell on snipeIT docker context
4) run this command 

- php artisan migrate
- php artisan config:clear
- php artisan config:cache

5 ) restart my docker-compose (snipeIT+MariaDB)

-----

##My Docker-compose file

`version: '3.4'

services:

  snipeit-db:
    container_name: snipe-db-${ENV}
    image: mysql:5.6
    env_file:
      - /etc/snipeit/${ENV}.env
    volumes:
      - dbstorage:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    restart: always
    networks:
      - internal

  snipeit-app:
    image: snipe/snipe-it:v5.0.9
    container_name: snipeit-app-${ENV}
    labels:
      - "traefik.http.routers.snipeit${ENV}.tls=true"
      - "traefik.http.routers.snipeit${ENV}.rule=Host(`${URLAPP}`)"
      - "traefik.http.services.snipeit${ENV}-service.loadbalancer.server.port=80"
    env_file:
      - /etc/snipeit/${ENV}.env
    depends_on:
      - snipeit-db
    restart: always
    volumes:
            - /export/backup/snipeit-${ENV}:/var/www/html/storage/app/backups
            - snipeitapp:/var/lib/snipeit
    networks:
      - traefik_share
      - internal

  snipe-it-dbadminer:
     image: adminer
     container_name: snipeit-dbadmin-${ENV}
     restart: always
     labels:
      - "traefik.http.routers.snipeitadminer${ENV}.tls=true"
      - "traefik.http.routers.snipeitadminer${ENV}.rule=Host(`${URLADMINER}`)"
      - "traefik.http.services.snipeitadminer${ENV}-service.loadbalancer.server.port=8080"
     networks:
      - traefik_share
      - internal

volumes:
  dbstorage:
   name: snipesql-vol-${ENV}
  snipeitapp:
   name: snipeitapp-vol-${ENV}
networks:
  traefik_share:
    external: true
  internal:
    name: snipeit-${ENV}
    external: false
`

-----

## My env file

`# Mysql Parameters
MYSQL_PORT_3306_TCP_ADDR=snipe-db-uat
MYSQL_ROOT_PASSWORD=mypassword
MYSQL_DATABASE=snipeit
MYSQL_USER=snipeit
MYSQL_PASSWORD=mypassword
MYSQL_PORT_3306_TCP_PORT=3306
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

#SMTP Parameter
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mydomain.com
MAIL_PORT=25
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=it-admin@mydomain.com
MAIL_FROM_NAME='ITAM-UAT'
MAIL_REPLYTO_ADDR=it-admin@mydomain.com
MAIL_REPLYTO_NAME='Snipe-IT-UAT'
MAIL_BACKUP_NOTIFICATION_ADDRESS=it-admin@mydomain.com

# Snipe-IT Settings
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:VEW+4js8YxpF8rgSSkAPzXUYMt43eT5iHHzqwaBjDHk=
APP_TIMEZONE='Europe/Paris'
APP_LOCALE=en
APP_URL=http://127.0.0.1:80
MAX_RESULTS=1000
`

-----

##Additional information
I can upload an image. When I enter in the context of the container, I can see my image in "/var/lib/snipeit/data/uploads/accessories"  (I also see my other images)
I have the following rights: -rw-r--r-- 1 docker root
I tried in chmod 777, it doesn't change anything. I don't have any error in the logs.

**Comment by bvivi57** [comment]
I find my problem: "APP_URL=http://127.0.0.1:80" 
I juste replace with "APP_URL=http://myurl:80"
It's good now !! Sorry for this error

**Comment by snipe** [comment]
It happens :) glad you’re sorted
