### ISSUE TITLE
Can't connect to LDAP server

### ISSUE THREAD

**Issue by Jannik2017** [grokability/snipe-it#8829]
I cant connect my SnipeIT to an active Dierectory LDAP Server i have written a PHP script that i can already bind to this ldap Server so i might be a Problem of SnipeIT i entered my Settings below

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- fresh install
- Version of Snipe-IT   v5.0.9 
- Version of PHP  7.2
- Debian 10 Apache 2
- manual installation

[LDAP_AD Settings_Connection_Failed.pdf](https://github.com/snipe/snipe-it/files/5610998/LDAP_AD.Settings_Connection_Failed.pdf)

**Comment by gilesytheking** [comment]
There doesn't seem to be a port number in your settings. I would expect you would need to configure the Ldap port number on your server/firewall to allow connection and add the port number into your configuration settings.

ldaps:\\192.168.0.20:PORTNUMBER

Also check your error logs, They may indicate the reason you are unable to connect. The information you have supplied isnt much to go on, to provide a resolution to your problem.

**Comment by Jannik2017** [comment]
now it works but i got the error  Unable to find user in LDAP directory!
Error getting users from LDAP directory, error: ldap_search(): Search: Invalid DN syntax
