### ISSUE TITLE
Custom Fields - Radio button - Unexpected output

### ISSUE THREAD

**Issue by maxovitsj** [grokability/snipe-it#8834]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When creating custom fields and setting the 'Form Element' to 'radio button', the resulting output in the Asset Creation / Update screen is unexpected; There is no content to pick from.

**To Reproduce**
1. Create a new Custom Field with 'Form Element' set to 'radiobutton'
2. Add this new Custom Field to a Fieldset
3. Add this Fieldset to your Asset Model
4. Add a new Asset of this type / Edit the Asset of this Model.

**Expected behavior**
Show the radio buttons / Allow the user to select the button

**Screenshots**
Screenshot 1: shows the creation of the Custom Field
![image](https://user-images.githubusercontent.com/771947/100601193-90f72800-3302-11eb-9210-dccfc3066982.png)
Screenshot 2: shows the Create / Edit Asset page:
![image](https://user-images.githubusercontent.com/771947/100601298-b2f0aa80-3302-11eb-9905-67a681bf78d1.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.9 build 5616 (973eacf6c3) 
 - OS: Ubuntu / Docker (snipe/snipe-it:latest)
 - Web Server: Apache
 - PHP Version:  7.2.24-0ubuntu0.18.04.7 

**Additional context**
- Is this a fresh install or an upgrade? Fresh install (pulled docker image)
- What OS and web server you're running Snipe-IT on: Ubuntu / Docker
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Docker
- Include what you've done so far in the installation, and if you got any error messages along the way: Default installation
- Indicate whether or not you've manually edited any data directly in the database: No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Chris-ISN** [comment]
Same/similar issue here - radio buttons output is blank on the view/edit asset page after configuring the custom field form element as `radio button` and with field values added/configured.

Running version 5.0.11 - build 5695 (master) on PHP 7.2.

**Comment by hmacugova** [comment]
same problem, same version  Version v5.0.11 - build 5695 (master)

**Comment by mizness** [comment]
Can vouch, radio buttons are not showing up in custom fields. 

Version v5.0.12 - build 5705 (master)

**Comment by inietov** [comment]
Hello!! Thanks for your input. I can assure you this is actively worked on, and probably have a fix soon.

**Comment by maxovitsj** [comment]
> 
> 
> Hello!! Thanks for your input. I can assure you this is actively worked on, and probably have a fix soon.

Sweet! Could you also check https://github.com/snipe/snipe-it/issues/8833, it's basically the same thing but with the checkboxes

**Comment by inietov** [comment]
I think it's resolved in the PR merged a few time ago. I'm closing the issue, but feel free to reopen if necessary. I'm also working on the checkboxes issue, but that problem is a little bit trickier, so I think what I'm saying here is for you to please have a little patience with that one.
