### ISSUE TITLE
Asset Name Escaping

### ISSUE THREAD

**Issue by maxovitsj** [grokability/snipe-it#8835]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When using characters such as: ", in the Asset Name field when creating a new Asset, it gets URL escaped.
See attached screenshot

**To Reproduce**
1. Create a new Asset with " in the Asset Name field

**Expected behavior**
" should be un-escaped on display to the end user

**Screenshots**
![image](https://user-images.githubusercontent.com/771947/100614702-cefe4700-3316-11eb-9e0b-33aa754edec4.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.9 build 5616 (973eacf6c3) 
 - OS: Ubuntu / Docker (snipe/snipe-it:latest)
 - Web Server: Apache
 - PHP Version:  7.2.24-0ubuntu0.18.04.7 

**Additional context**
- Is this a fresh install or an upgrade? Fresh install (pulled docker image)
- What OS and web server you're running Snipe-IT on: Ubuntu / Docker
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Docker
- Include what you've done so far in the installation, and if you got any error messages along the way: Default installation
- Indicate whether or not you've manually edited any data directly in the database: No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Where are you seeing this? I'm unable to reproduce it on the demo.

<img width="1221" alt="Screen Shot 2020-11-30 at 5 52 05 PM" src="https://user-images.githubusercontent.com/197404/100687297-dfbdb580-3334-11eb-8d59-73588b954408.png">

<img width="879" alt="Screen Shot 2020-11-30 at 5 52 15 PM" src="https://user-images.githubusercontent.com/197404/100687299-e0eee280-3334-11eb-97f4-d7fe5e83c053.png">

https://demo.snipeitapp.com/hardware/1383


<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/1383">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
