### ISSUE TITLE
Not able to git upgrade from v4.9.5 build 4482 (g5b68a321a) to 5.0 >

### ISSUE THREAD

**Issue by The7Machine7** [grokability/snipe-it#8849]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

![snipe_install_error](https://user-images.githubusercontent.com/60344973/100856802-cb3c0300-3483-11eb-9e15-b582663b8c81.png)

I have had Snipe-IT installed for 18 months now and is such a fantastic product I can't see I'd use anything else, keep up the great work :) On to the problem . . .

I installed 4.6.8 using GIT and have upgraded ever since using the php upgrade.php method, according to all the v5 notes it should be as simple as that!!

During the process it fails on composer v2.0, carbon, GIT pull & laravel. I have managed to manually install composer and carbon but fails on GIT pull manually or via the upgrade script.

Can anyone assist with the upgrade process or do I have to backup and create a new server install from scratch?
Will a backup restore without issues in v5?

My server spec is as follows

Snipe-IT v4.9.5 build 4482 (g5b68a321a)
Debian 10.6
Apache 2.4.38
MariaDB 10.5.6
PHP 7.4.13
Laravel 5.5.48
Webmin 1.955
Webmin Theme 19.60
phpMyAdmin 5.0.4

**Comment by EarlRamirez** [comment]
are you getting any errors

**Comment by The7Machine7** [comment]
Thanks for your response, have managed to resolve by using the following command to update GIT master branch

git fetch origin master

git reset --hard RESET_HEAD
![snipe_install_fix](https://user-images.githubusercontent.com/60344973/101368236-cf5e8b00-389e-11eb-9597-75f9fe30d42a.png)
