### ISSUE TITLE
Admin Settings and In-App Password Reset Redirect Issue

### ISSUE THREAD

**Issue by awat31** [grokability/snipe-it#8850]
#### Please confirm you have done the following before posting your bug report:

- [ Y] I have enabled debug mode 
- [ Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

When changing admin settings, or when a user tries to reset their password via web access (not local), when its saved instead of redirecting to 'https://url.com/snipeit/admin/x' it tries to redirect to '//admin/x', without the URL.
Admin settings can be updated by accessing the app locally from the server it runs on, from https://ip.address/snipeit/admin/x, which redirects fine.
Creating, modifying and checking in and out assets works.
Group settings can be changed from the web interface.
Within the HTML code, in the pages that work (Inspecting element on save button) the 'form' contains an attribute 'action'.
On the working pages 'action="https://url/snipeit/admin/x"'
On the failing pages 'action='//admin/x''
Settings are not saved.

**Expected behavior**
I expected the settings to be saved and the app to redirect as it does on the local access.
Should redirect to 'https://url.com/snipeit/admin'
It's weird that it redirects fine for most of the pages but doesn't for some of these admin-related tasks.

**Server (please complete the following information):**
 - Snipe-IT Version: 5.0.1 (Existed in previous version, 4.something)
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version: 7.4.13

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome and Firefox

**Error Messages**
Browser error is DNS as it is trying to locate '//admin/x' which obviously doesn't work.

**Additional context**
- Is this a fresh install or an upgrade? - Existed on both
- What OS and web server you're running Snipe-IT on - See Above
- What method you used to install Snipe-IT: install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way. - N/A
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
What's your APP_URL in your .env?

**Comment by awat31** [comment]
Its set to https://oururl.com/snipeit

**Comment by awat31** [comment]
I resolved this issue - it was an issue with Nginx, not the application. Closing now. Thanks for your help.
