### ISSUE TITLE
Request to be able to Transfer Assets to another user

### ISSUE THREAD

**Issue by rdeclute** [grokability/snipe-it#8851]
**Describe the solution you'd like**

It would be nice to to have a transfer button much like the checkin/checkout button.  For instance, when a user gets married and they change their last name.  Instead of having to check in each asset and then recheck it out, you could click on transfer and then have the old user info pre-populated an then a form below to fill out the new users info and then checkout to that user.
**Describe alternatives you've considered**

**Comment by snipe** [comment]
> For instance, when a user gets married and they change their last name.

Why wouldn't you just change the user's last name in the user settings? They're not a different person, they just have a different name

**Comment by rdeclute** [comment]
I guess that would work, but if we do an LDAP import would that overwrite the user information.  We import all of our users from LDAP and when they get married we create a new AD account for them. it makes it easier for permissions.  

Another example would be if employees change desks/locations.  Usually the equipment stays with the desk and doesn't follow the user.

**Comment by snipe** [comment]
> but if we do an LDAP import would that overwrite the user information

As long as the usernames match - meaning as long as you update the name in your LDAP directory before you sync them - it wouldn't create a new user. LDAP looks at the username as the unique constraint, so change it once in LDAP, change it in Snipe-IT, and you should be able to sync normally.

**Comment by rdeclute** [comment]
Sounds good.
