### ISSUE TITLE
Unlinked Uploaded Images After Version Update

### ISSUE THREAD

**Issue by LordDamocles** [grokability/snipe-it#8854]
#### Please confirm you have done the following before posting your bug report:

- [**x** ] I have enabled debug mode 
- [**x** ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
**After updating to v5.0.9 from v5.0.4, all uploaded images are no longer linked. Asset images, Model Images and site branding.
Any newly uploaded images display fine.
Looking at the pathway for an unlinked model images, it shows:
"http://192.168.1.24/uploads/models/assetmodel-[image name and format]"
When I replace this image for a new one, the pathway shows:
"http://192.168.1.24/uploads/models/assetmodel-image-[image name and format]"
Adding the -image- to the pathway.**

**To Reproduce**

**Expected behavior**
Photos from previous version to remain linked?

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version **v5.0.9 build 5616 (973eacf6c3)**
 - OS: **Ubuntu 20.04.1 LTS**
 - Web Server: **Apache**
 - PHP **Version 7.4.3**

**Desktop (please complete the following information):**
 - OS: **Windows 10 Pro 64 19042.630**
 - Browser **Chrome 87.0.4280.66, Firefox 83.0**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **Not reproducible.**
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)
**[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache**

**Additional context**
- Is this a fresh install or an upgrade? **Upgrade**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual Installation**
- Include what you've done so far in the installation, and if you got any error messages along the way.
 **I've seen this reported in the past ([6771](https://github.com/snipe/snipe-it/issues/6771)) but those steps didn't resolve this issue.
Also just updated to v5.0.10 - build 5680, issue still persists.**
- Indicate whether or not you've manually edited any data directly in the database
**Nothing edited directly in the database.**
Old Photo:
![2020-12-02](https://user-images.githubusercontent.com/60053716/100950170-b3d04900-355b-11eb-8177-2598939437e8.png)
Newly Uploaded Photo:
![2020-12-02 (1)](https://user-images.githubusercontent.com/60053716/100950254-dc584300-355b-11eb-84d1-6e755dd7eea3.png)

**Comment by Agiomir** [comment]
Same Issue too...

**Comment by maxlehot1234** [comment]
Issue fixed by removing the APP_URL IP or website link. But its a weird issue....
But by doing this, it prevent images to load in emails templates ;(

**Comment by LordDamocles** [comment]
> Issue fixed by removing the APP_URL IP or website link. But its a weird issue....
> But by doing this, it prevent images to load in emails templates ;(

I removed the APP_URL IP, cleared cache and rebooted but still no luck. :(

**Comment by Agiomir** [comment]
I tried too but issue persists. Also the Logo Image can to be loaded:
![image](https://user-images.githubusercontent.com/75487349/101334165-30c33180-3880-11eb-95e6-3b1394c0ecb8.png)

Something is going on with this version...

**Comment by maxlehot1234** [comment]
Anytyhing @snipe Just wondering how we can fix this issue?

**Comment by Agiomir** [comment]
In my case issue was resolved by running **php artisan config:clear**

**Comment by djshoxxx** [comment]
im having a similar issue with the images trying to load from the correct IP, the same one  that the APP_IP is pointed too, but the incorrect port.

anyone else whos having this issue, can you confirm that the images are loading from the right port as well as the right IP?
