### ISSUE TITLE
Signature not show in page Print All Assigned

### ISSUE THREAD

**Issue by denzfarid** [grokability/snipe-it#8856]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
hello again, this time I want to report that the signature does not appear on the print assets page

**To Reproduce**
1. Go to 'https://demo.snipeitapp.com/users/1'
2. Click on 'https://demo.snipeitapp.com/users/1/print'
3. See image not found

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/1294403/100982931-3c121680-357b-11eb-84ac-2b987cbb2573.png)

but on the asset history page, 
**/hardware/1#history**
the signature can be displayed

![image](https://user-images.githubusercontent.com/1294403/100982650-eccbe600-357a-11eb-8f8a-e98a65febd5e.png)

**Server (please complete the following information):**
 - Snipe-IT v5.0.10 - build 5680
 - OS: Ubuntu
 - Web Server: [Apache]
 - PHP Version 7.4

**Desktop (please complete the following information):**
 - OS: [all]
 - Browser [all]

**Error Messages**
![image](https://user-images.githubusercontent.com/1294403/100983111-74195980-357b-11eb-8061-aa1a58497cc5.png)

thank you

**Comment by LSNIGHTSHOT** [comment]
I'm also having this issue.

**Comment by luki331023** [comment]
Me as well

**Comment by KurtLopes** [comment]
Same problem, version 5.1.8

**Comment by aj-bi** [comment]
Same Problem here.. Version 5.2

**Comment by Use2FA** [comment]
I am also experiencing this issue and seem to have narrowed it down. It seems to only be devices I edited the name of due to a typo originally, also one where I just changed the default location, both done after the user already signed for it. It's far too many devices to have the users reaccept and sign for again unfortunately. Not sure if this applies to anyone else but this is what I have found. I would think there would be something linking that image to the original device name that could possibly be edited to remedy this on the backend.

**Comment by Alberto-Colab** [comment]
Hello, the solution is: 

Change file: resources/views/users/print.blade.php
FROM: `<img style="width:auto;height:100px;" src="{{ asset('/') }}display-sig/{{ $asset->assetlog->first()->accept_signature }}">`

TO: `<img style="width:auto;height:100px;" src="{{ asset('/') }}display-sig/{{ $asset->assetlog->firstWhere('action_type', 'accepted')->accept_signature; }}">`

The problem were on select from last registry and not the last signature from table.

I hope this can be update!

**Comment by Use2FA** [comment]
This is hosted by you guys, do I have access to this?

Thanks

**Comment by snipe** [comment]
@Use2FA Once the PR is reviewed, approved and merged, we can update your hosted instance.
