### ISSUE TITLE
Asset Model: Attachments

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#8857]
I'd like to request a "files" tab in Asset Models.

I love the option to attach files to individual assets in Snipe-IT. It would be great if the files tab was also available in the Asset Model. 

When I purchase a new item I create an asset in Snipe-IT but have no place to add information that is universal to identical assets, like the purchase order or packing slip. Since it's universal I don't want to duplicate the information to each individual asset.

![2020-12-03_15-15-31](https://user-images.githubusercontent.com/31219479/101094959-70d19e00-357a-11eb-8a42-21ba1158ef2e.jpg)

**Comment by LSNIGHTSHOT** [comment]
+1

**Comment by mikeroq** [comment]
Just to let you know this is now a feature in v6.0.6
https://github.com/snipe/snipe-it/releases/tag/v6.0.6



<blockquote><img src="https://opengraph.githubassets.com/90f44705bf6f1202a5a4081a1c6bddca8743d884a887d73b7716b5a7efeeaa87/snipe/snipe-it/releases/tag/v6.0.6" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/snipe/snipe-it/releases/tag/v6.0.6">Release v6.0.6 · snipe/snipe-it</a></strong></div><div>This version includes some small bug fixes and a handful of UI improvements that we think you'll really love - and adds a new index to improve performance. We also snuck in some additional filters ...</div></blockquote>

**Comment by jmartins1** [comment]
Saw that. Awesome! Thanks
