### ISSUE TITLE
No Backup Emails get send

### ISSUE THREAD

**Issue by Joly0** [grokability/snipe-it#8862]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Since recently (about 2-3 weeks ago) (i think since i upgraded from 4.9.5 to 5), no backup emails are sent. Usual checking/checkout emails are properly sent and the send testmail button in the general settings work aswell. But if i start a backup, no email gets send. The settings in .env are correct. If i look into our outlook-backend, normal emails as the testmail reach it, but the backup mails never reach the backend.
Btw no error or anything in the logs

**To Reproduce**
1. Go to Backups
2. Click on Generate Backup
3. No Backup-notification mail is sent

**Expected behavior**
Backup-mail should be sent

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: 5.0.10
 - OS: [e.g. Ubuntu, CentOS]: Windows Server 2016
 - Web Server: [e.g. Apache, IIS]: IIS
 - PHP Version: 7.4.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10 1909
 - Browser [e.g. chrome, safari]; Chrome
 - Version [e.g. 22]: 87

**Error Messages**
No error messages, nothing in the log, not even with debug mode enabled

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT

**Comment by jovibroz** [comment]
Same here. Didn't notice but it broke november 10. Whatever update came that date?

EDIT: Just checked broke with version 5.0.5 or 5.0.6 that was released the same day. Nov 10. After that no more emails when updating.

**Comment by jovibroz** [comment]
No confirmation on this? What was broken? Still doesn't work on 5.0.12

**Comment by Joly0** [comment]
This issue seems not to be that hard to fix and its been open for nearly 2 months now, so is this going to get fixed anytime?

**Comment by Joly0** [comment]
@snipe 
It seems like i missed the note in 5.0.5 to update the .env file and add this part

# --------------------------------------------
# OPTIONAL: BACKUP SETTINGS
# --------------------------------------------
MAIL_BACKUP_NOTIFICATION_DRIVER=null
MAIL_BACKUP_NOTIFICATION_ADDRESS=null
BACKUP_ENV=true


But now i am facing another issue:  added those lines to the .env file and set the address to the correct email-address, but idk what the driver should be set to? I tried smtp, but that just throws an error. Leaving it to null makes it possible to backup, but no email get send. Any idea?

**Comment by Joly0** [comment]
Ok, kept fiddeling around and the driver should be set to "mail" (without quotation marks)....

**Comment by Joly0** [comment]
@jovibroz i hope this helps you

**Comment by jovibroz** [comment]
Wow thanks! Long standing issue finally solved :) Thanks a lot @Joly0
