### ISSUE TITLE
Setup Auth via LDAP (can connect, cannot authenticate)

### ISSUE THREAD

**Issue by coatmaker618** [grokability/snipe-it#8870]
This is more of a documentation request, as I'm currently struggling with it:

**setting up authentication via LDAP**

I am 100% an LDAP nob, so I probably did all the things wrong.  However, I am currently successfully authenticating against this LDAP via another web service (NextCloud), so I think that part of the config is correct.

More importantly, I am also able to connect to LDAP according to the LDAP settings page.

However, I cannot, for the life of me, authenticate to LDAP on that same page :(

Is there a "reference for total dummies"with an example LDAP broken down in such a way that I'm 100% certain I'm putting the right variables/queries in the right fields?  If not, I'd be happy to formalize the instructions once I figure this out myself >_>

Update:
Just found #8741 not sure if this applies to that or not....

**Comment by coamtaker618** [comment]
Just found #8741 not sure if this applies to that or not....
