### ISSUE TITLE
Syncing with AD is only possible for the superuser

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#8871]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading from 4.9.5 to the latest current version, there were problems with creating users (syncing with AD). Some it employees did not have superuser rights, but they did have rights to create users. In version 4.9.5 and earlier, they could sync with AD and thus create users. In version 5.0.10, they can no longer sync with AD, and they don't have enough permissions. Only users with superuser rights can start syncing with AD.

**Comment by snipe** [comment]
The permission required for LDAP syncing is `$this->authorize('update', User::class);`, since syncing can create new users but can also modify existing users.
