### ISSUE TITLE
New install of Snipe-IT on Red Hat Enterprise 7.9 shows blank webpage

### ISSUE THREAD

**Issue by kksimpkins** [grokability/snipe-it#8873]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

New install of Snipe-IT on Red Hat Enterprise Linux Server release 7.9
When going to the webpage, getting: 

This error (HTTP 500 Internal Server Error) means that the website you are visiting had a server problem which prevented  the webpage from displaying.
 
**To Reproduce**
1. Go to 'https://<webserver>/setup'
4. See error - This error (HTTP 500 Internal Server Error) means that the website you are visiting had a server problem which prevented  the webpage from displaying.

**Expected behavior**
Expect to see Snipe-IT setup webpage.

**Screenshots**
If applicable, add screenshots to help explain your [problem.]
Webpage image included.

**Server (please complete the following information):**
 - Snipe-IT Version 
cannot verify. installed latest version.
 - OS: [e.g. Ubuntu, CentOS]
Red Hat Enterprise Linux Server release 7.9
 - Web Server: [e.g. Apache, IIS]
Apache
 - PHP Version 
7.3

**Desktop (please complete the following information):**
Windows 10 Enterprise
Internet Explorer
Version 11

**Smartphone (please complete the following information):**
None.

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No files in storage/logs. debug is on.
web browser error is "This error (HTTP 500 Internal Server Error) means that the website you are visiting had a server problem which prevented  the webpage from displaying."
- If a stacktrace is provided in the error, include that too.
None.
- Any errors that appear in your browser's error console.
HTML1300: Navigation occurred.
http_500.htm
HTML1524: Invalid HTML5 DOCTYPE. Consider using the interoperable form "<!DOCTYPE html>".
http_500.htm (1,1)
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
http_500.htm
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
?
- Include any additional information you can find in `storage/logs` and your webserver's logs.
No files in storage/logs (debug is enabled).
/var/log/httpd/ssl_error_log has:
[Mon Dec 07 20:11:27.936484 2020] [php7:error] [pid 8811] [client XXX.XXX.XXX.XXX:XXXXX] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/bootstrap/../vendor/autoload.php' (include_path='.:/opt/rh/rh-php73/root/usr/share/pear:/opt/rh/rh-php73/root/usr/share/php') in /var/www/html/snipeit/bootstrap/autoload.php on line 17
- Include the output from `php -m` (this should display what modules you have enabled.)
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade? 
Fresh
- What OS and web server you're running Snipe-IT on
Red Hat Enterprise Server 7.9
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
Had to update PHP version to 7.3.
- Indicate whether or not you've manually edited any data directly in the database
No database edits.
![Image 9](https://user-images.githubusercontent.com/17497817/101401324-30d32980-38a0-11eb-8727-6c8fa223fad3.jpg)

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by kksimpkins** [comment]
I saw some of the folders had snipeitapp Group ownership. I think I'd done this before to try solve this issue. I ran chown snipeitapp:apache -R /var/www/html/snipeit. Now I have a different error listed in /var/log/httpd/ssl_error_log:

[Tue Dec 08 15:47:58.331204 2020] [php7:error] [pid 368] [client XXX.XXX.XXX.XXX:XXXXX] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/html/snipeit/app/Exceptions/Handler.php:41\nStack trace:\n#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(92): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(134): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/html/snipeit/app/Exceptions/Handler.php on line 41

**Comment by kksimpkins** [comment]
As user snipeitapp, deleted the files (not the directory) in bootstrap/cache (which removed packages.php and services.php).
ran composer dump-autoload.
Now I have the following in /var/log/httpd/ssl_error_log:

[Tue Dec 08 18:18:19.788149 2020] [php7:warn] [pid 370] [client XXX.XXX.XXX.XXX:XXXXX] PHP Warning:  require(/var/www/html/snipeit/vendor/composer/platform_check.php): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 25
[Tue Dec 08 18:18:19.788198 2020] [php7:error] [pid 370] [client 10.1.180.243:65509] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/vendor/composer/platform_check.php' (include_path='.:/opt/rh/rh-php73/root/usr/share/pear:/opt/rh/rh-php73/root/usr/share/php') in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 25

**Comment by kksimpkins** [comment]
chown snipeitapp:apache vendor/composer/platform_check.php

Brought me back to this in /var/log/httpd/ssl_error_log:

[Tue Dec 08 18:27:33.618940 2020] [php7:error] [pid 2924] [client 10.1.180.243:49169] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/html/snipeit/app/Exceptions/Handler.php:41\nStack trace:\n#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(92): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 {main}\n  thrown in /var/www/html/snipeit/app/Exceptions/Handler.php on line 41
[Tue Dec 08 18:27:33.619034 2020] [php7:error] [pid 2924] [client XXX.XXX.XXX.XXX:XXXXX] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/html/snipeit/app/Exceptions/Handler.php:41\nStack trace:\n#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(92): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(134): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/html/snipeit/app/Exceptions/Handler.php on line 41

**Comment by kksimpkins** [comment]
From #4470, did the following:

Clear your config cache (if you can): php artisan cache:clear
Backup your current env: cp .env .env.backup
Then starting at the bottom, start deleting line by line of your .env and refreshing the web UI after each delete. You'll need to put all those things back, but if there's a line in there that it doesn't like, this will help us identify it - or at the very least, rule it out as a possible cause.

No change. Still getting the HTTP 500 error.

**Comment by kksimpkins** [comment]
Performed a fresh install by deleting the /var/www/html/snipeit folder and /etc/httpd/conf.d/snipeit.conf, then running the snipeit.sh script, installing composer and the required apps. 

Now getting:
[Thu Dec 10 15:10:22.329620 2020] [php7:error] [pid 17144] [client XXX.XXX.XXX.XXX:XXXXX] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/html/snipeit/app/Exceptions/Handler.php:41\nStack trace:\n#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(92): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(134): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/html/snipeit/app/Exceptions/Handler.php on line 41

**Comment by kksimpkins** [comment]
Ok, looks like the magic was configuring selinux on the snipeit folders.

sudo semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/html/snipeit(/.*)/?"
sudo restorecon -R -v  /var/www/html/snipit/
sudo semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/html/snipeit/storage(/.*)?"
sudo restorecon -RF /var/www/html/snipeit/storage

Then running php artisan config:cache.

After doing this, I can now see the setup page "Snipe-IT Pre-Flight".

**Comment by snipe** [comment]
Thanks for following up with your solution :)
