### ISSUE TITLE
500 Server Error when I am trying to access the admin settings page

### ISSUE THREAD

**Issue by dan286608** [grokability/snipe-it#8878]
#### Expected Behavior (or desired behavior if a feature request)

Ideally I would click on the admin settings icon to load up the admin settings page.

-----

#### Actual Behavior

I recently added a logo to my site and now every time I click on admin settings I get brought to an error page that just reads "500 | Server Error"

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running?
 v5.0.6
- Version of PHP you're running?
 v7.4.12
- Version of MySQL/MariaDB you're running? 
10.5.8
- What OS and web server you're running Snipe-IT on? 
Windows server 2019 standard w/ IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)? Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error.
500 | Server Error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error.
The page I am on is server-IP/admin and the error occurs when I just try to access the page
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Nunito' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

content.js:48 Uncaught (in promise) TypeError: this.engines is not iterable
    at E.updateSocialMedia (content.js:48)
    at new E (content.js:48)
    at Function.start (content.js:48)
    at Function.main (content.js:48)
admin:1 Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Nunito' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

admin:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/iframe_handler.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/content.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Not reproducible
- Include any additional information you can find in `storage/logs` and your webserver's logs.
**Storage/logs**
[2020-12-08 19:05:48] production.ERROR: syntax error, unexpected '1' (T_LNUMBER), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected '1' (T_LNUMBER), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Controllers\\SettingsController.php:417)
[stacktrace]
#0 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\inetpub\\\\wwwr...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Http\\\\Contro...')
#2 [internal function]: spl_autoload_call('App\\\\Http\\\\Contro...')
#3 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(803): ReflectionClass->__construct('App\\\\Http\\\\Contro...')
#4 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Contro...')
#5 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(785): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Contro...', Array, true)
#6 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(629): Illuminate\\Foundation\\Application->resolve('App\\\\Http\\\\Contro...', Array)
#7 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(770): Illuminate\\Container\\Container->make('App\\\\Http\\\\Contro...', Array)
#8 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(233): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Contro...')
#9 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(833): Illuminate\\Routing\\Route->getController()
#10 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(794): Illuminate\\Routing\\Route->controllerMiddleware()
#11 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(694): Illuminate\\Routing\\Route->gatherMiddleware()
#12 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(674): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#13 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#14 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#15 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#16 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#17 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#18 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\SecurityHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForDebug->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Middleware\\CheckForSetup.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForSetup->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\barryvdh\\laravel-cors\\src\\HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#41 C:\\inetpub\\wwwroot\\snipe-it\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#42 {main}
"} 
- Include what you've done so far in the installation, and if you got any error messages along the way.
The installation is completed and was done so without errors, this error occurred after installation. I followed an installation guide from https://blog.teknex.com.au/snipe-it/snipe-it-installation-on-windows-server/. Initially in my .env file I had APP_URL set to http://10.0.0.2 like in the teknex tutorial, but the logo I added wasn't showing up. I ended up changing the APP_URL to the IP address of my server and my logo showed up, but doing so now causes the error for the admin settings page.
- Indicate whether or not you've manually edited any data directly in the database
Nothing has been manually edited within the database.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by aelfannir** [comment]
Today i got the same error, fixed by disabling McAfee® WebAdvisor Chrome ext.

**Comment by gdimitropoulos** [comment]
me too

**Comment by roshanzaid** [comment]
> Today i got the same error, fixed by disabling McAfee® WebAdvisor Chrome ext.

This is the solution!

**Comment by eransevil** [comment]
> Today i got the same error, fixed by disabling McAfee® WebAdvisor Chrome ext.

how did you do that? 

<img width="238" alt="Capture" src="https://user-images.githubusercontent.com/57147896/101634037-cef5f980-3a30-11eb-80f3-a35acb1962bc.PNG">

**Comment by roshanzaid** [comment]
You can simply go to your browser extension and disable McAfee.

Best Regards

Roshan Zaid
M: +971 522 443 328
Web Developer Cum Analyst

**Comment by dan286608** [comment]
> > Today i got the same error, fixed by disabling McAfee® WebAdvisor Chrome ext.
> 
> 
> 
> This is the solution!

I am still getting the error when I try to access the admin settings page

**Comment by snipe** [comment]
I’m kind of not clear on how disabling that browser extension would cause a server-side error though, unless maybe it’s modifying headers or something?

To clarify, this is only when accessing /admin? Or on other pages as well?

**Comment by snipe** [comment]
(It’s particularly odd, since /admin itself doesn’t *do* anything - it’s effectively a static page)

**Comment by dan286608** [comment]
> I’m kind of not clear on how disabling that browser extension would cause a server-side error though, unless maybe it’s modifying headers or something?
> 
> 
> 
> To clarify, this is only when accessing /admin? Or on other pages as well?

This is only on /admin. Every other page works just as expected. I was getting the error both before and after disabling the browser extension.

**Comment by dan286608** [comment]
> (It’s particularly odd, since /admin itself doesn’t _do_ anything - it’s effectively a static page)

Initially everything was running fine.  I followed an installation guide from https://blog.teknex.com.au/snipe-it/snipe-it-installation-on-windows-server/  and everything worked. I went to upload a logo to be displayed, but the logo never displayed. I looked in the Snipe IT documentation and read that if APP_URL in the .env file isn't set to the IP of the server running Snipe IT then images might not display. I initially had APP_URL=http://10.0.0.2 just like in the teknex guide, but then I changed it to the IP of my server and my logo started working. As soon as the logo started working however, /admin started giving the 500 | Server Error whenever it was clicked on.
Also, reverting the APP_URL back to http://10.0.0.2 didn't fix the server error and it also breaks the logo again.

**Comment by snipe** [comment]
APP_URL should always point to the actual application URL, as mentioned in the docs. 

The fonts loading error is just because the default error page from Laravel still uses Google fonts - that can be ignored. 

> content.js:48 Uncaught (in promise) TypeError: this.engines is not iterable
> at E.updateSocialMedia (content.js:48)

All of that looks like browser plugin stuff. We don't have any kind of socialMedia integration.

I'd try running this in Chrome in Safe Mode just to rule out any conflicting plugins. 
https://www.thewindowsclub.com/chrome-incognito-mode-safe

<blockquote><img src="https://www.thewindowsclub.com/wp-content/uploads/2017/07/Google-Chrome-Incognito-Mode_1.jpg" width="48" align="right"><div><img src="https://www.thewindowsclub.com/wp-content/uploads/2020/01/cropped-TheWindowsClub-Icon-192x192.png" height="14"> The Windows Club</div><div><strong><a href="https://www.thewindowsclub.com/chrome-incognito-mode-safe">How to run Chrome browser in Incognito Mode or Safe Mode</a></strong></div><div>Learn how to run Google Chrome browser in Incognito Mode to stay private & in Safe Mode with add-ons & extensions disabled to troubleshoot problems in Windows 10/8/7. This lets you start Chrome without extensions.</div></blockquote>

**Comment by snipe** [comment]
> [2020-12-08 19:05:48] production.ERROR: syntax error, unexpected '1' (T_LNUMBER), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' {"userId":1,"exception":"[object] (Symfony\Component\Debug\Exception\FatalThrowableError(code: 0): syntax error, unexpected '1' (T_LNUMBER), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at C:\inetpub\wwwroot\snipe-it\app\Http\Controllers\SettingsController.php:417)

This is I think the curious bit here...

In our code, that corresponds to:

```
 if ('1' == $request->input('clear_logo')) {
                Storage::disk('public')->delete($setting->logo);
                $setting->logo  = null;
                $setting->brand = 1;
}
```

In that section (line 417 of `app/Http/Controllers/SettingsController.php`, if you change `$setting->logo  = null;` to `$setting->logo  = '';` does that change anything?

**Comment by snipe** [comment]
It *shouldn't* change anything, but there is maybe an issue with your version of PHP and Snipe-IT compatibility.

**Comment by dan286608** [comment]
> It _shouldn't_ change anything, but there is maybe an issue with your version of PHP and Snipe-IT compatibility.

Nothing changed when changing line 417. What version of PHP would you say would be best to switch to to see if it is a compatibility issue?

**Comment by snipe** [comment]
I'd probably try 7.3 - that's what we're running and we haven't run into this issue.

**Comment by dan286608** [comment]
I will try downgrading and I'll let you know if it fixes the issue.

**Comment by dan286608** [comment]
/admin error still occurs after downgrading to PHP v7.3.25. All other pages still work fine.

**Comment by snipe** [comment]
What about running it in Chrome in Safe Mode?

**Comment by snipe** [comment]
Also make sure you clear all your app caches after downgrading:
https://snipe-it.readme.io/docs/common-issues#quick-tip-handy-commands

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues#quick-tip-handy-commands">Common Issues</a></strong></div><div>  These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin.These commands clear out cached service files that help speed up modern PHP applications but can also very occasionally be out of date, resu...</div></blockquote>

**Comment by dan286608** [comment]
Running in safe mode didn't change anything unfortunately. When I tried clearing the caches I got an error in windows powershell saying php was an unknown command. I think I am just going to do a fresh install of php, IIS, and snipe-it to get it working again.

**Comment by YanisDbz** [comment]
> Today i got the same error, fixed by disabling McAfee® WebAdvisor Chrome ext.

My Hero <3

**Comment by merima98** [comment]
> Today i got the same error, fixed by disabling McAfee® WebAdvisor Chrome ext.

Thank you! I had the same error, and this helped me.
