### ISSUE TITLE
Clean install, no users show in "People" no groups show in "groups"

### ISSUE THREAD

**Issue by jvarnadore** [grokability/snipe-it#8881]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have a fresh install of Snipe-IT on Ubuntu 20.04
The first thing I did was create a new user and an 'Administrators' group. The 'People' tab is empty and the 'Groups' tab is empty. I know that I created the user as the user is able to login to their account.

**To Reproduce**
1. Go to 'Create New'
2. Create new user.
3. Click on 'People'
4. No users are displayed on this page. 

**Expected behavior**
At least my user and the new user would display on this page. 

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version current
 - OS: Ubuntu 20.04
 - Web Server: Apache
 - PHP Version 7.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser New Edge
 - Version current

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on Ubuntu 20.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) curl
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database I have not.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Please include the additional information requested in the issue template. It's impossible for us to help you without that information.

**Comment by jvarnadore** [comment]
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

No browser errors

If a stacktrace is provided in the error, include that too.

I don't have a stacktrace

Any errors that appear in your browser's error console.

![image](https://user-images.githubusercontent.com/61564883/101654146-2c2c8380-3a0e-11eb-9c03-4c04d97c6036.png)


Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.

I cannot reproduce this error.

Include any additional information you can find in storage/logs and your webserver's logs.

I didn't see any relevant information in Apache's logs.

![image](https://user-images.githubusercontent.com/61564883/101654388-79a8f080-3a0e-11eb-8987-a3f403f39895.png)

Include the output from php -m (this should display what modules you have enabled.)

![image](https://user-images.githubusercontent.com/61564883/101654307-5ed67c00-3a0e-11eb-8c5f-89668a15eb4a.png)


<blockquote><img src="https://snipeitapp.com/img/desktop_snipe.png" width="48" align="right"><div><strong><a href="https://snipeitapp.com/demo">Try the Demo - Snipe-IT Open Source IT Asset Management</a></strong></div><div>Try the live demo of Snipe-IT, the best open source IT asset management system around.</div></blockquote>

**Comment by snipe** [comment]
> I don't have a stacktrace

The stack trace is in your storage/logs/laravel.log - I'd need to see more of what you're seeing there, but this looks like the same issue detailed here:
https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by snipe** [comment]
You can try running `php upgrade.php` to see if any of the required extensions are missing.

**Comment by jvarnadore** [comment]
Steps I have taken:
Ensure all packages.
Added a new repo for PHP7.4 with newer updates than the default Ubuntu repo. This then had about 34 updates to various modules. All have been updated. 
deleted services.php as that was the only one of the three files that I had in that folder.
Cleared cache from browser and tried a new browser.

I also looked over the laravel.log, but it is rather large, I could upload it from my fileshare if you want it.

**Comment by jvarnadore** [comment]
Snipe,

Maybe this will help. I can't narrow down this permissions issue that comes up when I try to reinstall Composer as the Snipeit user. 

![image](https://user-images.githubusercontent.com/61564883/101660706-71a07f00-3a15-11eb-8124-25d247f98966.png)

**Comment by jvarnadore** [comment]
I actually fixed that Error Exception for Composer it installs correctly now, but didn't resolve this overall issue.

**Comment by snipe** [comment]
Did you try running `php upgrade.php`?

**Comment by jvarnadore** [comment]
Snipe,

I apologize, this may be another time where I show my ignorance on these subjects. I tried searching for a different command and couldn't find one, but when I run <code> php upgrade.php </code> I get <code>Could not open input file: upgrade.php</code> I have run all of the updates on every PHP module I have installed, I have PHP 7.4 installed and I have all of the required modules on the list from the readme.

**Comment by snipe** [comment]
You'd need to run that on your snipe-it project root. You should see the file there.

**Comment by wsdtechdept** [comment]
I am also having a similar issue but it is after a restore.  All previous users show up if checking out an asset but do not show up under people.  Should I create my own thread for this issue?

**Comment by snipe** [comment]
@wsdtechdept You don't have to create your own thread, but I do need to know what version you're running, what's in your app logs, and whether you did any of these things: https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by jvarnadore** [comment]
@snipe 

Once I was able to fix some permissions issues, navigate to the root directory like you suggested and run php update.php the entire issue resolved. I'm about to log in and disable debug mode. 

I want to express my sincere gratitude not only to you creating this program, but being so involved in helping people like me fix it, even if it takes me a few tries.

**Comment by snipe** [comment]
@jvarnadore That's great news! That upgrade script just does some checks to determine whether or not all of the required libraries are installed, and tries to fix some caches, checks for permissions issues, etc. It's nothing you couldn't have done yourself, but it's less tedious versus running all of those commands yourself. 

So glad you're sorted!
