### ISSUE TITLE
The last audit is not recorded correctly.

### ISSUE THREAD

**Issue by is984** [grokability/snipe-it#8890]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Last audit record is off by 12 hours.

**To Reproduce**
1: Perform an audit on any asset.
2: If you view the last audit  in the list, you will see the shifted time.

**Expected behavior**
Updated at and Last Audit should have matched.
If you have not edited anything after the audit.

**Screenshots**
![image](https://user-images.githubusercontent.com/22042489/101889625-f68cc380-3be2-11eb-83bf-e226c34428fd.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.11 - build 5695 (master)
 - OS: CentOS Linux release 8.2.2004 (Core)
 - Web Server: OpenLiteSpeed 1.6.18
 - PHP Version 7.4.13 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Developer Edition
 - Version 84.0b8

**Error Messages**
There is no error messages.

**Additional context**
- This environment has been upgraded from v4.9.x
- This environment was installed using install.sh
- In this environment, the time zone is set to Asia/Tokyo (JST)
```
APP_TIMEZONE='Asia/Tokyo'
APP_LOCALE=jp
```

**Comment by jackka** [comment]
I've pull the fix #8887 for the same problem. Hope @snipe will merge it soon.

**Comment by jackka** [comment]
#8887

**Comment by jackka** [comment]
@is984 Hi! As I understand You could link my pull request to this issue - may help to prioritize the fix...

**Comment by is984** [comment]
This issue has been fixed. Thak you!
So, will close this.
