### ISSUE TITLE
Post request during setup redirects to original page with no exception / error message

### ISSUE THREAD

**Issue by HirtLocker128** [grokability/snipe-it#8893]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

On Step 3 of the Pre-Flight, we are directed to create a new admin user. When we hit "Next: Save User" the page reloads and redirects back to this same page, with all the input fields emptied and no error message or exception thrown in the console below or on the input fields. We check the database, and the user is not saved in the Users table. It doesn't seem like the post request is hitting any of the controller code, it seems to be something to do with the routing not executing properly but we can't figure out the issue.

**To Reproduce**
1. Install the application as directed by the docs
2. Go through Pre-Flight
3. Issue occurs on admin user creation page

**Expected behavior**
The application should create the admin user as entered and proceed to step 4

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.11
 - OS: ubuntu18.04.1
 - Web Server: Apache
 - PHP Version 7.2.3

**Error Messages**
None

**Additional context**
- Is this a fresh install or an upgrade? 
Fresh
- What OS and web server you're running Snipe-IT on
Apache + Ubunto 18.04.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation
- Include what you've done so far in the installation, and if you got any error messages along the way.
All that the docs asked up to this point, no error messages
- Indicate whether or not you've manually edited any data directly in the database
Have not

**Comment by uberbrady** [comment]
Super-weird - do you have anything blocking cookies? Anything weird locking down your browser? I don't think Ubuntu does any SELinux stuff by default, but could that be there? Check `storage/logs/laravel.log`? Also try to enable Debugbar - and inspect the messageBag - that can sometimes show errors that might not show up on screen.

Also is it possible that you're trying a password of less than 8 characters? I don't know how well we catch-and-display that on the initial setup, but an 8-char minimum is definitely required.

In fact, we're thinking it's very likely the last thing.

**Comment by uberbrady** [comment]
Yup, if you look here: https://github.com/snipe/snipe-it/blob/master/app/Http/Requests/SetupUserRequest.php#L30 - and change that '6' to an '8' I suspect you'll get a much nicer 'password too short' message.

**Comment by HirtLocker128** [comment]
@uberbrady yep that did it! Infinite thanks!
