### ISSUE TITLE
Localization: No possibility to use comma for Cents

### ISSUE THREAD

**Issue by SvenAbels** [grokability/snipe-it#8896]
**Describe the bug**
In Germany and many other countries, prices are written using a comma instead of a dot to separate the main currency (USD/EUR/GBP/CHF/...) from the smaller value (Cent,...). e.g. 1000,45 EUR or 1.000,45 EUR are the standard writing for one thousand Euros and 45 Cents. It looks like Snipe-IT does not allow using commas to separate the currency values and it cannot be configured in the Localization settings either..

**Comment by creactiv** [comment]
+1

**Comment by jackka** [comment]
Small addition: .csv files for data import use comma to separate fields. Thats a point to think deeper about the problem.

**Comment by SvenAbels** [comment]
> Small addition: .csv files for data import use comma to separate fields. Thats a point to think deeper about the problem.

Yes that's correct. This is normally solved by putting values in quotes (") within a CSV file when importing them. This is at least how most ERP and CRM systems handle this issue as it's a common problem for all countries that use commas for finances.


Best regards,

Sven

**Comment by ISNL-PimP** [comment]
In addition to the formatting: This has also caused issues for us when typing in prices with commas. Snipe-IT changes `1234,56` to `123456.00` instead of the expected `1234.56`.
We use data from Snipe-IT to generate forms, and this can lead to some strange situations: Costs can suddenly be 100x higher than expected.
![ldSEX0HggD](https://user-images.githubusercontent.com/59050598/103626261-39b92880-4f3c-11eb-8a05-7f16ff782fb8.gif)

**Comment by SvenAbels** [comment]
> In addition to the formatting: This has also caused issues for us when typing in prices with commas. Snipe-IT changes `1234,56` to `123456.00` instead of the expected `1234.56`.


I've updated to the new version 5.0.12 and can confirm that the typing for 1234,56 leads to 123456 USD instead of 1234.56 EUR - even after changing the new localization feature in the settings

**Comment by jackka** [comment]
Previous #8915 fix was about costs representation in main asset view. 
Apparently, what you are talking above also needs to be fixed.
For good its concerns many places like import and etc.
