### ISSUE TITLE
Update from 3.6.4 build 12 to Ver. 4.1 or later

### ISSUE THREAD

**Issue by nordi62** [grokability/snipe-it#8902]
Hi,

we are on a pretty old version of Snipe-IT and try to update to a version 4 or later.
It is running on a debian 10 server with MySQL / MariaDB.

due to the fact that all people who were in charge for the initial installation left the company, So I do not even know how it was installed, I guess it was done by GIT.

The server was updated from Debian 8 to 10. PHP version used is 5.6, but 7.4 is also installed.

I searched the web to find a way to update, but i run into problems sooner or later. 
"git pull" ends up with a merge error of thousands of files. 

I am not a developer, I do not know GIT really... 

Any help in upgrading this installation is appreciated. Or, if its easier... a fresh install and migration of the DB is also possible.

Thanks for ur help !

Oliver

-----

**Comment by Joly0** [comment]
Try this https://snipe-it.readme.io/docs/upgrading-to-v4

After upgrading, you should be able to just use php update.php as described here https://snipe-it.readme.io/docs/upgrading 
If not, do the update manually

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading-to-v4">Upgrading to v4 from v3</a></strong></div><div>Snipe-IT v4 includes a ton of new features and bug fixes, and all users are strongly encouraged to upgrade. For a full list of what's new in V4, click here. Please note that Snipe-IT v4 does require PHP &gt;= 5.6.4. Please see the list of requirements before upgrading.Updating Snipe-IT should normal...</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div> Always backup your database and configuration files before upgrading. We try very hard to make sure that all database changes are non-destructive, but you should always backup beforehand anyway. You will never regret backing up your database. You may regret not doing so, so it’s just better to get ...</div></blockquote>

**Comment by nordi62** [comment]
Thanks Joly for your reply, but it doesnt solve my problem. I already tried all the "official" ways for an upgrade, but they all failed.

If I try "git pull" I get an "database error". We are using MariaDB 1.3.27 ...

Any other idea ?
Thanks!
Oliver

**Comment by Joly0** [comment]
Could you tell, at what point it gives you the error? What parts of the update tutorial from v3 to v4 work and which doesnt?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
