### ISSUE TITLE
Non super admins cannot run LDAP sync

### ISSUE THREAD

**Issue by emike09** [grokability/snipe-it#8906]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Non Super Admin Administrators are unable to run the LDAP Sync. When clicking Synchronize, a 403 Forbidden error comes up. These other IT administrators have the every right under groups, except for Superuser.

**To Reproduce**
1. Log in as a non-super user admin that has all rights, besides Super Admin. 
2. Go to People, LDAP Sync
3. Click Synchronize
4. Administrator is presented with a sad panda. 403 Forbidden.

**Expected behavior**
For groups allowed to view, create, edit, and delete users, I expect these admins to be able to run LDAP sync.

**Screenshots**
![image](https://user-images.githubusercontent.com/9699530/102139233-ccbde180-3e1a-11eb-8fa3-dd59ecdb6f50.png)

**Server (please complete the following information):**
 - 5.0.11
 - OS: Ubuntu Server 20.04
 - Web Server: nGinX
 - PHP Version: 7.4

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Browser Chrome

I ran with Debug mode enabled, but I couldn't really see anything pertinent. In laravel.log, I get the following error:

[2020-12-14 14:28:54] production.ERROR: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'note' (SQL: alter table `accessories_users` add `note` varchar(191) null) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S21): SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'note' (SQL: alter table `accessories_users` add `note` varchar(191) null) at /var/www/inventory.utahca.org/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)
[stacktrace]

I was unable to test on the Demo site as LDAP is not enabled there.

**Comment by nilsrb** [comment]
Can confirm this, LDAP Sync only working as a super admin.

**Comment by UserGoodtm** [comment]
https://github.com/snipe/snipe-it/issues/8871#issue-758558007
