### ISSUE TITLE
Pre-Fligh DB Setup

### ISSUE THREAD

**Issue by saigop** [grokability/snipe-it#8914]
#### Expected Behavior (or desired behavior if a feature request)

Stuck in Initial setup, Running Snipe-IT via docker and have custom mysql standalone setup also edited the server details in the my_env_file as described in the documentation. 

-----

#### Actual Behavior

Even though I have setup the my_env_file, while on the Pre-Flight setup it shows DB issue where still it looks for .env file. I tried to enter into shell mode on the docker and changed the .env file to communicate to standalone DB, but still i get the same error. 
![snipeit_DB_Issue](https://user-images.githubusercontent.com/16423728/102241865-78505a00-3f1f-11eb-8e05-7141acdab93b.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ No] I have enabled debug mode 
- [ Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running - current docker version
- Version of PHP you're running - docker image
- Version of MySQL/MariaDB you're running - 8.0.22
- What OS and web server you're running Snipe-IT on - Ubuntu 20.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - browser screenshot attached
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Pre flight setup
- If a stacktrace is provided in the error, include that too. - No
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - No Error
- Include any additional information you can find in `storage/logs` and your webserver's logs. - 
[Tue Dec 15 16:22:39.223630 2020] [access_compat:error] [pid 24] [client 172.17.0.1:48128] AH01797: client denied by server configuration: /var/www/html/public/.env
^C

- Include what you've done so far in the installation, and if you got any error messages along the way. - No errors on the docker side. 
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by syndr** [comment]
This might not be it, given what you show for your webserver logs, but it looks like the container is deploying with MySQL 8 now, and there's a change in the default authentication type in that version.

I had to log into the mysql instance as root and change the auth method on the snipe user to the legacy auth mode, and then it worked.  
`ALTER USER 'snipeit' IDENTIFIED WITH mysql_native_password BY 'your_password';`

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
