### ISSUE TITLE
Manufacturer logo upload failed - 500 | Server error

### ISSUE THREAD

**Issue by bulldog091** [grokability/snipe-it#8918]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I click edit on an existing manufacturer and try to save the changes, an error 500 appears.

**To Reproduce**
1. Go to 'Settings>Manufacturers'
2. Click on 'Pencil'
3. Make changes to any field or upload new logo
4. Click on save
5. See error 500 page

**Expected behavior**
Manufacturer should be saved without error

**Screenshots**
![image](https://user-images.githubusercontent.com/76131281/102410821-6212ce80-3ff1-11eb-8c09-e3f655ac17d5.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.11 - build 5695 (master)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.4.11

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome, firefox
 - Version: 87.0.4280.88 (Official Build) (64-bit), 83.0 (64-bit)

**Error Messages**
- SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: '10' (SQL: select count(*) as aggregate from `manufacturers` where `name` = LG and `deleted_at` <> 10)
- [22:30:47] LOG.error: PDOException: SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: ...
errorlog[22:30:47] LOG.error: SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: '10' (SQL: sel...
- [PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade? Upgrade from 5.0.6 where there was the same error
- What method you used to install Snipe-IT - install.sh

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by modestos** [comment]
I get this error too on: 
Snipe-IT versionv5.0.11 build 5695 (gfd4ee6027) with PHP Version 7.3.25 and Laravel Version 6.18.10

**Comment by mizness** [comment]
I too am experiencing this issue.

Running Wamp64 on Win10Pro. PHP 7.4.9; MySQL 8.0.21; Apache 2.4.46

SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: '7' (SQL: select count(*) as aggregate from `manufacturers` where `name` = Microsoft and `deleted_at` <> 7)
C:\wamp64\www\assets.site\vendor\laravel\framework\src\Illuminate\Database\Connection.php#669

Illuminate\Database\QueryException
SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: '7'
C:\wamp64\www\assets.site\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php#129

Doctrine\DBAL\Driver\PDOException
SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: '7'
C:\wamp64\www\assets.site\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php#127

**Comment by cliff-LINKS** [comment]
I have the same issue on Snipe-IT v5.1.0

macOS 10.13.6 - PHP 7.2.21 - MySQL 8.0.16 - Apache 2.4.33

If I edit any field on a Manufacturer record, I get a '500 | Server error'-page or the same error as the previous poster if debug is true.

If I upload an image, I get the same error, but I've noticed the image does get uploaded to /public/uploads/manufacturers/... it doesn't show in the manufacturers page though.

**Comment by snipe** [comment]
Hm, I can't reproduce this locally or on the demo. I'm guessing it might be a MySQL 8 issue?

**Comment by snipe** [comment]
Quick question - I'm seeing what *looks* like IDs in those queries populating in the `deleted_at` field - can someone confirm that? 

I feel like we've seen this before, and it's been a MySQL issue, but the weird part is that we don't actually specify the `deleted_at` part of that query. Because we use soft deletes, it's sort of built into the framework.

**Comment by snipe** [comment]
Yeah, I knew I saw this before.. https://github.com/snipe/snipe-it/issues/8562

**Comment by snipe** [comment]
Does this happen if you create a new manufacturer and upload an image during the creation?

**Comment by cliff-LINKS** [comment]
Uploading an image while creating a new manufacturer seems to work indeed.

**Comment by snipe** [comment]
@cliff-LINKS thanks for confirming.... It sort of makes sense that it would work on new creation, but we never actually reference the `deleted_at` in the method that saves the manufacturer.

```php
 /**
     * Validates and stores the updated manufacturer data.
     *
     * @author [A. Gianotto] [<snipe@snipe.net>]
     * @see ManufacturersController::getEdit()
     * @param Request $request
     * @param int $manufacturerId
     * @return \Illuminate\Http\RedirectResponse
     * @since [v1.0]
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(ImageUploadRequest $request, $manufacturerId = null)
    {
        $this->authorize('update', Manufacturer::class);
        // Check if the manufacturer exists
        if (is_null($manufacturer = Manufacturer::find($manufacturerId))) {
            // Redirect to the manufacturer  page
            return redirect()->route('manufacturers.index')->with('error', trans('admin/manufacturers/message.does_not_exist'));
        }

        // Save the  data
        $manufacturer->name             = $request->input('name');
        $manufacturer->url              = $request->input('url');
        $manufacturer->support_url      = $request->input('support_url');
        $manufacturer->support_phone    = $request->input('support_phone');
        $manufacturer->support_email    = $request->input('support_email');

        // Set the model's image property to null if the image is being deleted
        if ($request->input('image_delete') == 1) {
            $manufacturer->image = null;
        }

        $manufacturer = $request->handleImages($manufacturer);


        if ($manufacturer->save()) {
            return redirect()->route('manufacturers.index')->with('success', trans('admin/manufacturers/message.update.success'));
        }
        return redirect()->back()->withInput()->withErrors($manufacturer->getErrors());
    }
```

Are you able to upload images on edit to other item types (company, locations, etc)?

**Comment by cliff-LINKS** [comment]
Yes, other object types work just fine on my server.

**Comment by snipe** [comment]
That's SO bizarre. Most of those methods are all kinda the same so why it fails there and not elsewhere is mystifying. Validate that the thing exists, check that the user has permission to do the thing, save the data, redirect the page.

**Comment by snipe** [comment]
If you don't upload an image but you edit a manufacturer, does it 500? Or is it just when there's an image?

**Comment by cliff-LINKS** [comment]
Yes I get the same error on every edit I do on a manufacturer record, also when it's only a small edit on a text field.

**Comment by snipe** [comment]
@cliff-LINKS Fascinating. Thanks for the additional info - I'm looking into what might be happening here.

**Comment by cliff-LINKS** [comment]
You're welcome 'snipe', thanks for looking in to this. Great tool!

**Comment by snipe** [comment]
One more question - can either/both of you run this command:

`SHOW CREATE TABLE manufacturers;`

via a MySQL prompt.

@cliff-LINKS I know you've been around for a bit, not sure about the OP, but I'm wondering if its a MyISAM v InnoDB issue - which has been solved in later versions, but if an install is very old, could potentially be a thing. (Not implying your Snipe-IT is out of date, just that it's been running a long time, so those tables may have been created long ago.)

**Comment by snipe** [comment]
For quick clarification, MyISAM was the default table engine like 150 years ago but hasn't been in some time. As such, we didn't always explicitly say "use InnoDB as the table engine" because we didn't think we had to. Turns out, we did have to, because while it defaulted correctly *most* of the time, it didn't always on everyone's installs of Snipe-IT/MySQL.

Alternatively, you can try:

```mysql
ALTER TABLE manufacturers ENGINE = InnoDB
```

And see if that helps the issue at all. 

I can't *imagine* that it would, and it wouldn't make any sense that it would, but it's worth a try. Running either of those commands won't hurt anything - the first just shows you the `CREATE TABLE` syntax and the second one changes the engine to InnoDB - which it should have been anyway.

**Comment by cliff-LINKS** [comment]
Hi @snipe, mine was already on InnoDB.

<img width="987" alt="Screenshot 2021-02-11 at 13 16 27" src="https://user-images.githubusercontent.com/53275614/107635442-74b12900-6c6b-11eb-9585-e968d0667e3f.png">
