### ISSUE TITLE
Displaying of Location

### ISSUE THREAD

**Issue by emasgarov** [grokability/snipe-it#8929]
Hi everyone
I have problem with Location viewing in Snipe-it
In Assets owerview Asstet locations shown different. But when i open asset detailed view it's displayed normal.

In other case for new local users or synced via LDAP location problem is the same.

Who faced or have such a problem?

**Comment by snipe** [comment]
Hi there - Pretty sure this has been working for a long time now, sorry for not closing this sooner. I'm going to close this. Please feel free to open a new issue if you're still having trouble.
