### ISSUE TITLE
API Endpoint /api/v1/users redirects to login page

### ISSUE THREAD

**Issue by mat-ti** [grokability/snipe-it#8932]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I wand to add a user through the API and i received html code

**To Reproduce**

This is my sh script for testing purposes:
```
API_KEY=$(cat .api_key)
curl --request POST \
  --url https://<myurl>/api/v1/users \
  --header 'Authorization: Bearer '$API_KEY'' \
  --header 'Content-Type: application/json' \
  --data '{"first_name":"testname","username":"testuser","password":"p4ssword","email":"email@mail.test"}'
```

**Expected behavior**
Add user with API, like adding Hardware

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: CentOS
 - Web Server: Traefik Proxy

**Client Machine (please complete the following information):**

**Error Messages**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- In your test instance its like the same, you will receive html code: https://snipe-it.readme.io/reference#users-2

**Additional context**
- Is this a fresh install or an upgrade? **Fresh install**
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Docker**
- Include what you've done so far in the installation, and if you got any error messages along the way. nothing
- Indicate whether or not you've manually edited any data directly in the database

In Postman, i will be redirect to login page, instead of authenticate with api key. My api key is fine, it runs great for creating hardware.

**Comment by snipe** [comment]
Per [the documentation](https://snipe-it.readme.io/reference#authenticating-with-the-api), you need both the `Content-Type` *and* `Accept headers` in your API requests. 

<img width="810" alt="Screen Shot 2020-12-21 at 1 14 47 PM" src="https://user-images.githubusercontent.com/197404/102822775-88888f00-438e-11eb-9429-918641f3d7d8.png">

**Comment by mat-ti** [comment]
Thanks for your reply. In the examples this is not used. Only mentioned at the top of the documentation. Sorry for not reading.

I had a new issue creating a user over API. A little bit digging in the code, I have to set another data "password_confirmation". Just for the records.
