### ISSUE TITLE
Google LDAP Sync Issue

### ISSUE THREAD

**Issue by kstorbakken** [grokability/snipe-it#8937]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode... I've not done this, let me know if it's needed. 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues).. There's a common issue mentioned that has this same error, but this isn't because of the Use TLS checkbox, it's a different issue. 

**Describe the bug**

I've setup LDAP on Google Workspace using stunnel on my local server to bypass the needs for client key and cert (https://support.google.com/a/answer/9089736?hl=en). I can query stunnel via softerra ldap browser just fine as a test. I have every required LDAP setting populated in snipe (https://snipe-it.readme.io/docs/ldap-sync-login), but I always get this error: " Error getting users from LDAP directory, error: ldap_control_paged_result_response(): No server controls in result". Tried all manners of LDAP filters and such, just the same error. 

**To Reproduce**
**-Setup Google LDAP client.
-Setup stunnel to proxy requests locally to Google LDAP.
-Generate Google LDAP bind credentials in Google LDAP client since Snipe-IT requires username and password for binding.
-Configure Snipe-IT LDAP settings and attempt to sync.** 

**Expected behavior**
Successful sync of users from LDAP.

**Screenshots**
![image](https://user-images.githubusercontent.com/74789296/102828892-0b1b4980-43a3-11eb-9a93-012f0b147ef2.png)
![image](https://user-images.githubusercontent.com/74789296/102828940-2b4b0880-43a3-11eb-8f64-00ab79e4cd93.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 5.0.4 - build 5452
 - OS: Docker on Ubuntu 18.04
 - Web Server: Whatever is in use in docker image snipe/snipe-it:v5.0.4
 - PHP Version: Whatever is in use in docker image snipe/snipe-it:v5.0.4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

Error getting users from LDAP directory, error: ldap_control_paged_result_response(): No server controls in result

**Additional context**
- Is this a fresh install or an upgrade? **Fresh install** 
- What OS and web server you're running Snipe-IT on: **Whatever is in use in docker snipe/snipe-it:v5.0.4. Docker hosted on Ubuntu 18.04**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **Docker**
- Include what you've done so far in the installation, and if you got any error messages along the way.: **Installation is done. Added a few assets, nothing else really. Have working email.** 
- Indicate whether or not you've manually edited any data directly in the database.: **No.**

-I've also tried changing LDAP filter to &(objectClass=person) and some others I forget now. Same error. 
-Have discussed in Gitter with Brady Wetherington. Has mentioned that it's most likely that Google's LDAP does not support paging and that's why this error is happening. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by jkkd5467** [comment]
Were you able to resolve this? I am having different issues, but curious to see if anyone got snipe-it to work with stunnel and Google's secure ldap

**Comment by uberbrady** [comment]
Snipe-IT now has built-in support for Google LDAP. See: https://snipe-it.readme.io/docs/hosted-ldap-providers#google-secure-ldap-service for more details.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/hosted-ldap-providers#google-secure-ldap-service">- Hosted LDAP Providers</a></strong></div><div>Your Azure AD needs to have LDAP enabled, and password hash synchronization enabled, and it needs to be accessible to the server running Snipe-IT on port 389 and/or 636. Microsoft's documentation on LDAP is here: https://docs.microsoft.com/en-us/azure/active-directory-domain-services/tutorial-config...</div></blockquote>
