### ISSUE TITLE
Accepted assets are still listed under "Non-accepted assets"

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#8939]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Accepted assets are still listed under "Non-accepted assets"

**To Reproduce**
It is not reproducible for me as it was reported to me by staff members

**Expected behavior**
Accepted assets are not displayed in "unaccepted assets".

**Screenshots**
Signed and accepted asset
![image](https://user-images.githubusercontent.com/22889256/102997800-2febfa00-4526-11eb-8790-f4ca53a862e9.png)

still in the "not accepted" list
![image](https://user-images.githubusercontent.com/22889256/102997814-35e1db00-4526-11eb-9ccd-a5a54adf3c2d.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.11 build 5695 (gfd4ee6027)
 - OS: [e.g. Ubuntu, CentOS]: Ubuntu 20.04
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version: 7.4.3

**Desktop (please complete the following information):**
Every Browser

**Smartphone (please complete the following information):**
Every Browser

**Error Messages**
The error bar is not displayed because the page never finishes loading in debug mode.

**Additional context**
- Is this a fresh install or an upgrade? Fresh, only updated 1-2 Times. always on 5.X
- What OS and web server you're running Snipe-IT on: Ubuntu
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.: i cant remember
- Indicate whether or not you've manually edited any data directly in the database: i did not

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by feedback2ajeet** [comment]
Yes , looks like its BUG only , i am also seeing the same in unaccepted  assets report. Users are provided their acceptance but still its showing they haven't provided their acceptance .

**Comment by kbeedles** [comment]
I am seeing assets that are already accepted in the list as well as duplicate unaccepted items, so I believe this is related to #8804 

To investigate I poked around the database tables. On the asset acceptances table, the duplicate assets have different creation timestamps. The timestamps correlate with when the asset was changed or re-assigned. 

If the user signed and accepted an asset, the acceptance timestamp and signature file are listed on the table. For the duplicates, the acceptance time and signature columns are null and you will still see the asset in the unaccepted list.

**Comment by ghost** [comment]
Is there any news here yet?

**Comment by felixreichmann** [comment]
Same issue here

**Comment by tristanobi1** [comment]
I have this issue also on my SaS Version v5.1.6 - build 6109 (develop). I have assets appearing on the unaccepted asset report which the user has accepted. When clicking on the asset you can see in the History that it was accepted. 

Also if an asset hasn't been accepted and then a user leaves and is deleted. The unaccepted asset remains in the report forever, is there a way to remove it?

**Comment by snipe** [comment]
@inietov - I’m not sure if this was handled in 5.2.0? Can you take a look?

**Comment by inietov** [comment]
@snipe It is, but if they already are duplicated records in the database they keep appearing as I fix the bug on the code that causes them but I can't manipulate the data that is already recorded in the system.

**Comment by snipe** [comment]
@tristanobi1 can you open a support ticket and ask to be upgraded to latest please? Just shoot an email to support@snipeitapp.com with your hosted url and we’ll get that handled right away.

**Comment by tristanobi1** [comment]
@snipe will do! Thanks for that. I currently have a support ticket open. So once this fix is in place do you think I would be able to request the specific entries that are stuck to be removed from the DB?

**Comment by inietov** [comment]
Fixed in https://github.com/snipe/snipe-it/pull/10053
