### ISSUE TITLE
When accessing API link I receive a 404 error

### ISSUE THREAD

**Issue by jhurff** [grokability/snipe-it#8940]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I access the API url, I get a 404 error and message that says:

404 Page not found.
Sad panda. We could not find the page you were looking for. You should maybe return to the dashboard.

**To Reproduce**
1. Go to http://ec2-100-27-36-56.compute-1.amazonaws.com/api/v1
2. See error

**Expected behavior**
I'm trying to get to the API

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by albinbatman** [comment]
Can you post your web server configuration?

**Comment by jhurff** [comment]
I can...is there a specific config you'd suggest?  I used the AWS marketplace package from Intuz.  Snipe IT powered by Intuz and it's the default installation with no customizations.

**Comment by albinbatman** [comment]
Hi again,

I am not 100% how AWS EC2 instances works but it looks like the image you are using (Intuz) comes with Apache. Can you check if you have any configuration files in either of those locations, run those in the terminal (SSH) on your EC2 instances and post the output.

- ls /etc/apache2/sites-available (Ubuntu)

**Comment by jhurff** [comment]
Hi albinbatman...here's the output per your request.

root@ip-172-30-0-209:/etc/apache2/sites-available# uname -a
Linux ip-172-30-0-209 5.4.0-1035-aws #37~18.04.1-Ubuntu SMP Wed Jan 6 22:31:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@ip-172-30-0-209:/etc/apache2/sites-available# ls /etc/apache2/sites-available
000-default.conf  default-ssl.conf
root@ip-172-30-0-209:/etc/apache2/sites-available#

**Comment by snipe** [comment]
This issue is pretty old (I'm doing some cleanup of old issues), and I assume you've figured out the issue by now, but there is (or at least wasn't back then) an `/api/v1` endpoint. Per the docs, that's just the base API url - you need to specify a specific endpoint, like `/api/v1/hardware`.
