### ISSUE TITLE
Problems reaching pre-flight

### ISSUE THREAD

**Issue by SinnermanKGB** [grokability/snipe-it#8941]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - YES
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - YES

**Describe the bug**
When I access the API url, I get a 404 error and message that says:

404 Page not found.
Sad panda. We could not find the page you were looking for. You should maybe return to the dashboard.

When i try to access SnipeIT from VM server (localhost) it redirects me to >> snipeit.local/setup but it gives me only blank page. 
During the installation i have set the address to snipeit.local and thats what i have put into .env file.
APP_URL=http://snipeit.local

**To Reproduce**

**Expected behavior**
This is a great about from what i have seen from the demo. Please give me some solutions :)

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: Ubuntu
 - Web Server: Apache2
 - PHP Version 7.3

**Desktop (please complete the following information):**
 - OS: Windows 10 PRO x64
 - Browser Chrome
 - Version 87.0.4280.88

**Smartphone (please complete the following information):**
 - Device: /
 - OS: /
 - Browser /
 - Version /

**Error Messages**
- There is no error in the browser with debug mode turned on.
- If a stacktrace is provided in the error, include that too.
- (failed) net::ERR_NAME_NOT_RESOLVED
- When I try to connect from a PC thats in a different VLAN i get the message >> This site can’t be reachedCheck if there is a typo in snipeit.local.
If spelling is correct, try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN
- When I try to connect from a PC thats in a different VLAN and target IP address of the server i get redirected to /setup and get message >> This page isn’t working xxx.xxx.xxx.xxx is currently unable to handle this request.
HTTP ERROR 500
- There is no errors when i try demo from https://demo.snipeitapp.com/
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- 

**Additional context**
-This is a fresh install of SnipeIT server.
-I am running SnipeIT on Ubuntu 20.04 and web server is apache2
-I installed SnipeIT over sudo sh install.sh
- Never tried to modify anything manualy in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by SinnermanKGB** [comment]
MAnaged to find the solution :)

**Comment by andyondrya** [comment]
Might I ask how you worked around this?
