### ISSUE TITLE
Upgraded to v5, Assets, Users, etcs don't show up.

### ISSUE THREAD

**Issue by namarie23** [grokability/snipe-it#8948]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Upgraded from v 4.7.8 to 5.0.11
All data is not displaying except the asset count.
LDAP sync looked like it worked but no users are visible and the test in admin settings fails.
Tried Creating a test group, acted like it was created but nothing displays
I tried all the  below screenshotted commands, nothing helped.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/63315323/103384203-65569180-4aaa-11eb-8866-4a71e576e850.png)
![image](https://user-images.githubusercontent.com/63315323/103384221-769f9e00-4aaa-11eb-9314-43a0b59c511e.png)
![image](https://user-images.githubusercontent.com/63315323/103384229-828b6000-4aaa-11eb-80ee-403bd2d773a5.png)
![image](https://user-images.githubusercontent.com/63315323/103384272-a51d7900-4aaa-11eb-9f22-a07951266860.png)
![image](https://user-images.githubusercontent.com/63315323/103384303-cbdbaf80-4aaa-11eb-84d3-1e65bc18b471.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.11
 - OS: [e.g. Ubuntu, CentOS] Windows Server 2016
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.3.12

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade?  Upgrade
- What OS and web server you're running Snipe-IT on Windows 2016 Server IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual Upgrade
- Include what you've done so far in the installation, and if you got any error messages along the way. Referenced any and all related tickets, nothing helped.
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Please run `php upgrade.php` or follow the directions here: 
https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by namarie23** [comment]
> Please run `php upgrade.php` or follow the directions here:
> https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated
> 
> > <img alt="" width="48" src="/favicon.ico">Snipe-IT Documentation**[Installation/Upgrading Issues](https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated)**Common installation/upgrading issues and solutions

I've already done that and referenced that page, and it didn't work.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by snipe** [comment]
What was the output of `php upgrade.php`?

**Comment by snipe** [comment]
(This is very nearly always a missing PHP extension. `upgrade.php` tries to help you figure out which one you're missing.)

**Comment by namarie23** [comment]
I have all of the extensions in the requirements listed, php upgrade.php removed items, and that was it. I ran it a second time and got "Nothing to upgrade or remove" message, I closed that CMD window so don't have the exact verbiage.

**Comment by snipe** [comment]
Please run it again and paste the output here.

**Comment by namarie23** [comment]
You know what, I just fixed it. 
I rolled back to before I upgraded and did the upgrade again, I think originally it was something wonky with my composer install. Went smooth this time no issues.  I forgot to move my composer.exe into my snipe folder on the first go around and weirdness ensued. Second time was the charm.
