### ISSUE TITLE
GUI Backup Issue v5.0.11

### ISSUE THREAD

**Issue by namarie23** [grokability/snipe-it#8949]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The generate back up button in the GUI doesn't work , but php artisan backup:run does

**To Reproduce**

**Expected behavior**
A successful GUI generated back up.
**Screenshots**
![image](https://user-images.githubusercontent.com/63315323/103387124-f6336a00-4ab6-11eb-81c8-cfe82f0b0fa9.png)
![image](https://user-images.githubusercontent.com/63315323/103387175-2c70e980-4ab7-11eb-9622-c717d2e8bd0c.png)
![image](https://user-images.githubusercontent.com/63315323/103387218-62ae6900-4ab7-11eb-93fa-3354df8d78da.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.11
 - OS: [e.g. Ubuntu, CentOS] Windows Server 2016
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.3.12

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? Upgrade but the issue existed on the previous version too.
- What OS and web server you're running Snipe-IT on Windows 2016 Server 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- Include what you've done so far in the installation, and if you got any error messages along the way. Checked the DB_Dump Path, verified the relevant folders had IUSR and IIS_IUSRS added with permissions.
- Indicate whether or not you've manually edited any data directly in the database  No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by albinbatman** [comment]
Hi @namarie23,

I think this is an issue on IIS that prematurely exits the process that is spun up on the request ([snipe-it/SettingsController.php at master · snipe/snipe-it - L1056](https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/SettingsController.php#L1056)), unsure as to why.. I run Laragon with php 7.4 on my Windows machine and I am unable to reproduce unless I deliberately do it.

Can you make a new php file in the root of the directory of your Snipe-IT installation, paste the following content and then run it manually? Please, provide the output.

```php
<?php

use Symfony\Component\Process\Process;

require_once __DIR__ . '/vendor/autoload.php';

$process = new Process('php -v');
$process->mustRun();
var_dump(
	$process->getOutput(), 
	$process->getErrorOutput(),
	shell_exec('php -v')
);
```
**Should** give you an output of the following:
```
$ php test.php
string(155) "PHP 7.4.12 (cli) (built: Oct 27 2020 17:18:47) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
"
string(0) ""
string(155) "PHP 7.4.12 (cli) (built: Oct 27 2020 17:18:47) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
"
```

Also curious if you get any php related errors in your IIS logs?

**Comment by namarie23** [comment]
Creating that file just yields a 500 error.

**Comment by albinbatman** [comment]
> Creating that file just yields a 500 error.

You are supposed to run it in your terminal, not accessing it through your web browser.
