### ISSUE TITLE
 fix error checkin or checkout

### ISSUE THREAD

**Issue by hoaimv** [grokability/snipe-it#8950]
Hi All 
Thanks for helping fix this error
Failed to authenticate on SMTP server with username "YOURUSERNAME" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 334 but got code "530", with message "530 Must issue a STARTTLS command first ". Authenticator PLAIN returned Expected response code 235 but got code "530", with message "530 Must issue a STARTTLS command first ".
 --------------------------------------------

I do not send mail to users when I checkin and checkout

# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=email-smtp.us-west-2.amazonaws.com
MAIL_PORT=587
MAIL_USERNAME=YOURUSERNAME
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=you@example.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=you@example.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'

Thanks you so much

**Comment by uberbrady** [comment]
You need to use a real mailserver, not just the example values from the `.env`. You can use your company's own mailserver, if you host your own mail (far less likely in the modern era), or you can use your hosted email provider's SMTP server. Alternatively (and this is what we do for our own customers) you can use a transactional email provider such as Amazon SES, Mailchimp's Mandrill service, Mailgun, or any other one. Those usually require a little bit of DNS fiddling to get going, however.

Nowadays, the most likely `MAIL_ENCRYPTION` value will be `tls` - just fyi.

If you don't care about email at all, you can set `MAIL_DRIVER=log` - that will just dump the various emails into your laravel.log file.

**Comment by hoaimv** [comment]
@uberbrady 
Currently I am using email from google mail
With the code below I need to change how I can send email when I check in & checkout
plesase support  .Thank you very much 
MAIL_DRIVER=smtp
MAIL_HOST=email-smtp.us-west-2.amazonaws.com
MAIL_PORT=587
MAIL_USERNAME=YOURUSERNAME
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=you@example.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=you@example.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'

**Comment by hoaimv** [comment]
Dear uberbrady
when using snipe it when checking in and check out only send emails that have 2 layers security opened
Mail with 2-layer security off does not receive mail
Thanks to your support

**Comment by svbla** [comment]
Hello, I am having a similar issue. When I try checking an item in or out I get an error. I also tried sending a test email in admin settings but the test fails.

Failed to authenticate on SMTP server with username "techsupport@svbla.com" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535 Incorrect authentication data ". Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535 Incorrect authentication data ".
My .env settings are:

MAIL_DRIVER=smtp
MAIL_HOST=mail.server.com
MAIL_PORT=587
MAIL_USERNAME=email@company.com
MAIL_PASSWORD=password
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDR=email@company.com
MAIL_FROM_NAME='IT Support'
MAIL_REPLYTO_ADDR=email@company.com
MAIL_REPLYTO_NAME='IT Support'
MAIL_AUTO_EMBED_METHOD='attachment'

I have tried the commands:
php artisan config:clear
php artisan condif:cache

but it doesn't work.
Can anyone help me?

**Comment by ngvannguyen** [comment]
Try putting your password in quotes. (MAIL_PASSWORD =password# -> MAIL_PASSWORD ="password#"

**Comment by svbla** [comment]
Hey @nguyennv94 I tried that. Putting my password in quotes still does not work.
MAIL_PASSWORD="password"

Please let me know if there is anything else I can do.

**Comment by ngvannguyen** [comment]
> 
> 
> Hey @nguyennv94 I tried that. Putting my password in quotes still does not work.
> MAIL_PASSWORD="password"
> 
> Please let me know if there is anything else I can do.

can you check with gmail email first. see how

**Comment by svbla** [comment]
> > Hey @nguyennv94 I tried that. Putting my password in quotes still does not work.
> > MAIL_PASSWORD="password"
> > Please let me know if there is anything else I can do.
> 
> can you check with gmail email first. see how
I tried using gmail, but it still didn't work. Except this time, I didn't get any error logs, only the error message 
"Mail could not be sent.
No additional error message provided. Check your mail settings and your app log."
My settings:
MAIL_DRIVER=smtp
MAIL_HOST=smtp-relay.gmail.com
MAIL_PORT=587
MAIL_USERNAME=email@gmail.com
MAIL_PASSWORD="Password"
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=email@gmail.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=email@gmail.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'

**Comment by ngvannguyen** [comment]
> 
> 
> > > Hey @nguyennv94 I tried that. Putting my password in quotes still does not work.
> > > MAIL_PASSWORD="password"
> > > Please let me know if there is anything else I can do.
> > 
> > 
> > can you check with gmail email first. see how
> > I tried using gmail, but it still didn't work. Except this time, I didn't get any error logs, only the error message
> > "Mail could not be sent.
> > No additional error message provided. Check your mail settings and your app log."
> > My settings:
> > MAIL_DRIVER=smtp
> > MAIL_HOST=smtp-relay.gmail.com
> > MAIL_PORT=587
> > MAIL_USERNAME=[email@gmail.com](mailto:email@gmail.com)
> > MAIL_PASSWORD="Password"
> > MAIL_ENCRYPTION=tls
> > MAIL_FROM_ADDR=[email@gmail.com](mailto:email@gmail.com)
> > MAIL_FROM_NAME='Snipe-IT'
> > MAIL_REPLYTO_ADDR=[email@gmail.com](mailto:email@gmail.com)
> > MAIL_REPLYTO_NAME='Snipe-IT'
> > MAIL_AUTO_EMBED_METHOD='attachment'



My configure,
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=my_gmail@gmail.com
MAIL_PASSWORD="mypassword"
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=my_gmail@gmail.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=my_mail
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'

must enable IMAP and turrn ON Less Secure App access(Gmail)
![image](https://user-images.githubusercontent.com/43312342/115809926-3aa49600-a417-11eb-856d-00cc836bef86.png)
![image](https://user-images.githubusercontent.com/43312342/115809955-45f7c180-a417-11eb-844a-857fdf18aba8.png)

**Comment by svbla** [comment]
Hello @nguyennv94 ,Yes both are already enable. 
This is what worked for me.
I checked this page: https://snipe-it.readme.io/docs/common-issues
I did the following: "First, make sure your php.ini has curl.cainfo, openssl.cafile and openssl.capath point to the right cacert.pem file."

Then It worked with Gmail. After, I just replaced all the Gmail configs with the server configs I want.

Thank you very much, I had been at this for over a month now.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues">Common Issues</a></strong></div><div>  These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin.These commands clear out cached service files that help speed up modern PHP applications but can also very occasionally be out of date, resu...</div></blockquote>
