### ISSUE TITLE
LDAP Sync Works, LDAP Login Not Working

### ISSUE THREAD

**Issue by rcmcdonald91** [grokability/snipe-it#8952]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Git install on Debian 10, PHP 7.3.25-1+0~20201130.73+debian10~1.gbp042074, Active Directory (Server 2019)

When I configure LDAP sync with sAMAccountName, everything works fine. However, when I change sAMAccountName with userPrincipalName (in both the authentication query and the username field), I am able to sync the UPC as the SnipeIT Username, but I am unable to login.

**Expected behavior**
I should be able to use UPC as the username and authentication query

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.11 master
 - OS: Debian 10
 - Web Server: Apache
 - PHP Version : 7.3.25-1+0~20201130.73+debian10~1.gbp042074

**Comment by uberbrady** [comment]
Huh, weird. Well, if you can log in just fine using sAMAccountName, just flipping the variables over to userPrincipalName should "just work" - provided you log in with the full email address of the user. You might want to make sure you've unchecked the "append domain name" setting though - that's already included in the userPrincipalName.

**Comment by rcmcdonald91** [comment]
*facepalm*

Yep, append domain name was checked and it shouldn't have been.
