### ISSUE TITLE
500 | Server error in the UI

### ISSUE THREAD

**Issue by NareshAvunoori** [grokability/snipe-it#8964]
**Issue I am facing**

We are facing the issues with the below-mentioned operations.
1. while checking out the asset seeing the 500 | Server error in the UI
![image](https://user-images.githubusercontent.com/65230132/103527290-1e044280-4ea8-11eb-8004-6ef5339affd7.png)
2. The LDAP synchronized users are getting disappeared each time.
3. The Data in the accessories were missed but receiving the low inventory Email for the same accessories. 

**Screenshots**
![image](https://user-images.githubusercontent.com/65230132/103527635-ad115a80-4ea8-11eb-82db-95b427fd0774.png)
![image](https://user-images.githubusercontent.com/65230132/103528286-b18a4300-4ea9-11eb-85c9-9c79356fbcd2.png)

**Server (please complete the following information):**
 - Snipe-IT Version : v5.0.11 build 5695 (gfd4ee6027) 
 - OS: Runnign on Docker container 
 - Web Server: Apache
 - PHP Version : 7.2.24-0ubuntu0.18.04.7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome, Firefox
 - Version : chrome- 87.0.4280.8 firefox: 84.0.1

 

**Error Messages**
[2021-01-04 15:53:05] production.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'action_date' in 'field list' in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:64
Stack trace:
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(64): PDO->prepare('insert into `ac...', Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(457): Doctrine\DBAL\Driver\PDOConnection->prepare('insert into `ac...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `ac...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('insert into `ac...', Array, Object(Closure))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Illuminate\Database\Connection->run('insert into `ac...', Array, Object(Closure))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->statement('insert into `ac...', Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `ac...', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2695): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ac...', Array, 'id')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1366): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(840): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(805): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(668): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 /var/www/html/app/Models/Actionlog.php(218): Illuminate\Database\Eloquent\Model->save()
#13 /var/www/html/app/Models/Loggable.php(66): App\Models\Actionlog->logaction('checkout')
#14 /var/www/html/app/Listeners/LogListener.php(31): App\Models\Asset->logCheckout('', Object(App\Models\User), Object(Illuminate\Support\Carbon))
#15 [internal function]: App\Listeners\LogListener->onCheckoutableCheckedOut(Object(App\Events\CheckoutableCheckedOut))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(388): call_user_func_array(Array, Array)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('App\\Events\\Chec...', Array)
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(477): Illuminate\Events\Dispatcher->dispatch('App\\Events\\Chec...')
#19 /var/www/html/app/Models/Asset.php(312): event(Object(App\Events\CheckoutableCheckedOut))
#20 /var/www/html/app/Http/Controllers/Assets/AssetCheckoutController.php(78): App\Models\Asset->checkOut(Object(App\Models\User), Object(App\Models\User), '2021-01-04 15:5...', '', '', 'LAPTOP')

**Additional context**
- The system is being used for 1+ years, after a server restart we are seeing the issue
- What OS and web server you're running Snipe-IT on - Ubuntu, Apache
- What method you used to install Snipe-IT : docker

we are suspecting that is due to the database but we are clues less here to do something since we are facing issues in multiple places. 

Thanks in Advace.

**Comment by albinbatman** [comment]
Hi, @NareshAvunoori.

Seems you are missing an important colum in the **action_logs** table. Can you run the following from your Snipe-IT installation path?

**Important!** Ensure you have a fresh, valid backup of your database before running any commands that manipulates the database (such as the one below).

```bash
# this will ensure action_date column is added 
# (see: https://github.com/snipe/snipe-it/blob/master/database/migrations/2019_02_12_182750_add_actiondate_to_actionlog.php)
php artisan migrate --path=/database/migrations/2019_02_12_182750_add_actiondate_to_actionlog.php
```

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
