### ISSUE TITLE
Saved settings are not showing or appearing on SAML or LDAP/AD settings

### ISSUE THREAD

**Issue by ghkommina** [grokability/snipe-it#8965]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior
 
   Settings we made in AD/LDAP and SAML are not appearing after pressing the save button. But,  it was showing as  settings was saved successfully.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running 5.0.11
- Version of PHP you're running 7.2.5
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. No. its showing that, settings were saved suceesfully. but nothing was showing or Unchecked or checked
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by stbc** [comment]
mh, got the same issue over here. also branding is not saved when changed. Using 5.0.12

**Comment by domunus** [comment]
Same issue here.  Version 5.0.12.  Basically all admin settings wont stick after saving even though it states successful.   The only admin settings that actually saved was in Groups.  Changing permissions saved.  I've gone through all settings including the two OP mentioned and they all have the same issue.  

DEBUG results in no errors
storage/logs has no errors 
PHP 7.3.26
CentOS 7.9
used php upgrade.php (Did not see errors during upgrade)

Issue is somewhat reproduceable on Demo.  I didn't test all, but while changes in Branding actually save, changes in General Settings and Security do NOT save.

**Comment by uberbrady** [comment]
We've seen this before with Password Minimum characters (under Security) being set too low, but we have a migration that's supposed to fix that for you automatically. Can you check out that section and see if your password minimum characters is set to less than 8?

**Comment by stbc** [comment]
Saw that as well and checked that last week: Was set to 10 by the upgrade.php utility I guess. Changed it to 8 just to see if that works and that got stored properly.

**Comment by domunus** [comment]
Double checked and our minimum is set to 8.  I tried to change it to 10 so I could switch it back to 8 just in case something was going on, but same issue, save doesn't take.

**Comment by stbc** [comment]
> 
> 
> Saw that as well and checked that last week: Was set to 10 by the upgrade.php utility I guess. Changed it to 8 just to see if that works and that got stored properly.

Well, that is not true, have to correct myself: Was not stored. Same as domunus... What the heck?

**Comment by domunus** [comment]
Not sure if this is related, but may be a clue as to why the setting state saved, but the values aren't changed or executing.  My site logo was broken so I tried uploading a new image and tried several times.   I found that the image was not being uploaded as logo.png, but as "setting-logo-randomcharacters.png" and there were multiple copies with different randomcharacters.  Renaming that to logo.png fixed the site logo issue.  I'm wondering if maybe when you change a setting it's submitting garbage data and therefore not matching the check to show the value has changed or to execute it?   

For example, checking a setting for "Yes" submits the data as "setting-Yes-randomcharacters" instead of just "Yes" to the DB.

The favicon icon also uploads as favicon-upload.png and is placed in the uploads folder, although the favicon url is the root of public and extension of ico.

**Comment by domunus** [comment]
Did a bit more discovery work with this.  Checking the DB table for settings I can see that the value for the setting is changing.  For example, "Archived Assets".  Before the update, mine was already checked to show them in the all view of assets.  Which is currently does.  Via the settings page, i can't change that as it will remain checked even if I try to uncheck and save.  Changing the value in the table from 1 to 0 and saving does not make a difference.  It still remains checked and the archived devices still appear in the list.  Now, if I go to that settings page and just click save without making any changes, the value in the DB Table will change to 1.   If I uncheck and save, it will remain 0, but the checkmark will remain. If i go back and just click save without any changes it will change to 1.     I've run artisan config:clear/cache, is there maybe something else I can run?

**Comment by uberbrady** [comment]
Interesting - great detective work!

I think you might have a stale Blade cache - try running `php artisan view:clear` ?

**Comment by domunus** [comment]
Ran the view:clear; unfortunately did not solve the issue.  Existing values on the page remain.  I did a config:clear and view:clear and then cleared my browsers temp/cache as well before checking the site again and same results.   It's interesting that the site is not recognizing the changes in the DB but only what the site shows.

**Comment by domunus** [comment]
Solved!  

I figured it was a cache issue since the site was ignoring the DB and started digging around the directories for cache.  Found storage/framework/cache and inside was a CF folder with data cached from the day i updated.   I renamed the cf folder and refreshed the page and all the settings I had changed that actually changed in the DB but not the site applied.     This also fixed the image upload.  It was no longer uploading with setting-logo-randomcharacters, but just log.png.

**Comment by uberbrady** [comment]
Great! Glad you managed to get it figured out - we always do appreciate a 'close' when you do though, just because it cuts our open ticket count down. But thanks for letting us know that you solved it and so stoked that you got it all working!

**Comment by stbc** [comment]
Yep, same for me, same folder, permissions problem on that folder. Renamed it, storing changes is working again!

**Comment by SecurusCmi** [comment]
Same thing happened with me. @domunus props to you, I would of been digging for years. Renamed my cache folder and it all started to work again. 

This thread has been a life saver, thanks guys!
