### ISSUE TITLE
Cannot update LDAP fields

### ISSUE THREAD

**Issue by el-capitano** [grokability/snipe-it#8967]
### #### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Whenever I try to save something to LDAP settings, I receive an error "Please check the form below for errors" while there's no error and in version 4 this was working fine, after upgrading to version v5.0.11 build 5695 (gfd4ee6027) I started to receive these errors, it works when I manually update the fields in the database.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5055237/103567813-24f17c00-4ecd-11eb-8366-e2b1eb1e48f6.JPG)

**Server (please complete the following information):**
 - Snipe-IT Version :v5.0.11 build 5695 (gfd4ee6027)
 - OS: Windows 7 with XAMPP
 - Web Server: Apache
 - PHP Version :7.1.6

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by uberbrady** [comment]
The problem is probably that your minimum password requirement is too small, and so the framework won't allow you to save the settings record, even on pages completely unrelated to password length (such as LDAP). If you upgrade to v5.0.12 (hot off the presses!) that changes that value for you - or you can go into Settings, Security, Password minimum characters - and then set that to something greater than 8 (if memory serves).

**Comment by el-capitano** [comment]
Thanks man that solved my issue!
