### ISSUE TITLE
Add informations inside the email

### ISSUE THREAD

**Issue by haupt-pascal** [grokability/snipe-it#8974]
#### Actual Behavior

We'd like to add more informations in the information-mail when we checkout a device. There are one or two points which are not inside, and I'd like to know where or which config-file I should edit to add these informations. 

The thing is, that I (and other persons) need to see which person exactly have got the device. The only point where you can see this is at the top at the "Hello {{ person which got the device }}" but I'd like to have this exact information under (e.g.) the serialnumber (in the picture "Seriennummer") *in the table*. 

Is there a way to add this? Which config-file? Where's the config-file? 

![Screenshot 2021-01-06 101543](https://user-images.githubusercontent.com/75530910/103751547-cdf0c180-5008-11eb-86ad-b5a5d120fc61.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- fresh installed
- v5.0.11
- php 7.4.3
- I guess you don't need the other informations to answer my question :)

**Comment by albinbatman** [comment]
[checkout-asset.blade.php](https://github.com/snipe/snipe-it/blob/master/resources/views/notifications/markdown/checkout-asset.blade.php) is where you can add this information.

Add the following (line 26 and onwards):

```php
@if (isset($item->serial))
| **{{ trans('mail.serial') }}** | {{ $item->serial }} |
@endif

| **Checked out to** | {{ $target->present()->fullName() }}
```

**Comment by haupt-pascal** [comment]
Wow it worked, thank you so much!
