### ISSUE TITLE
Font wrong when export to excel file

### ISSUE THREAD

**Issue by arikita** [grokability/snipe-it#8975]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
on excel file:
![image](https://user-images.githubusercontent.com/46751390/103753430-a23bfe80-503d-11eb-889f-64906e886298.png)

on website:
![image](https://user-images.githubusercontent.com/46751390/103753618-db746e80-503d-11eb-850f-73a642b40c33.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.12
 - OS: Ubuntu 20.04
 - Web Server: Apache
 - PHP Version : 7.2

**Comment by uberbrady** [comment]
CSV files are plain text, and do not contain any formatting information. We unfortunately cannot change that. Sorry :(
