### ISSUE TITLE
Dashboard Not Populating

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#8977]
**Screenshots**
![2021-01-06_9-59-47](https://user-images.githubusercontent.com/31219479/103797672-04790d00-5006-11eb-92d9-e31603dd7c89.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version: from 5.0.11 to 5.0.12
 - OS: [e.g. Ubuntu, CentOS] 2012R2
 - Web Server: [e.g. Apache, IIS] WAMP Server 3.2.3
 - PHP Version 7.2.33

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Chrome & Firefox

I've attempted to update Snipe-IT from 5.0.11 to 5.0.12 on a WAMP server

I've attempted to do a Git install as well as a manual install, as described in the Snipe-IT installation documentation; either method produces the same failure. I did not receive any failures/errors during update.

I've also ran the following commands:

composer dump-autoload
composer clear-compiled (did not work)
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear

I've also attempted to re-import the database.

Update: I noticed that when accessing Snipe-IT from the host everything works as expected. When accessing Snipe-IT from a remote device the content is missing :(. Rolling back to 5.0.11 works fine. No permission changes.

Page Source Info.
![2021-01-06_11-19-24](https://user-images.githubusercontent.com/31219479/103805824-5ecb9b00-5011-11eb-8239-527f3796c83b.jpg)

**Comment by albinbatman** [comment]
Hi @jmartins1,

Can you open the Chrome Console, reload the page, right-click inside the Console and click **Save As** - save the file to your computer and please post the output here.

Redact any sensitive information before posting.

**Comment by jmartins1** [comment]
Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Feature-Policy header: Unrecognized feature: 'animations'.
Error with Feature-Policy header: Unrecognized feature: 'battery'.
Error with Feature-Policy header: Unrecognized feature: 'display-capture'.
Error with Feature-Policy header: Unrecognized feature: 'legacy-image-formats'.
Error with Feature-Policy header: Unrecognized feature: 'oversized-images'.
Error with Feature-Policy header: Unrecognized feature: 'publickey-credentials'.
Error with Feature-Policy header: Unrecognized feature: 'unsized-media'.
Error with Feature-Policy header: Unrecognized feature: 'vibrate'.
Error with Feature-Policy header: Unrecognized feature: 'wake-lock'.
content-tss.js:1 TSS: content-tss.js loaded:  http://hostaddress/
content-ads.js:1 INS: content-ads.js loaded:  http://hostaddress/
content-tss.js:50 TSS: Excluding content tss (trigger: send-message)
all.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
pGenerator.jquery.js:146 Uncaught ReferenceError: jQuery is not defined
    at pGenerator.jquery.js:146
bootstrap-table.js?id=58d95c93430f2ae33392:7757 Uncaught TypeError: Cannot set property 'BootstrapTable' of undefined
    at bootstrap-table.js?id=58d95c93430f2ae33392:7757
    at bootstrap-table.js?id=58d95c93430f2ae33392:4
    at bootstrap-table.js?id=58d95c93430f2ae33392:5
(index):974 Uncaught ReferenceError: $ is not defined
    at (index):974
(index):1604 Uncaught ReferenceError: $ is not defined
    at (index):1604
(index):1642 Uncaught ReferenceError: $ is not defined
    at (index):1642
(index):1692 Uncaught ReferenceError: $ is not defined
    at (index):1692

**Comment by aakibbagwan45** [comment]
I am also facing the same issue, i was trying to upgrade v3 to v4 & it was successful, Dashboard was showing the count of assets but when i click "total asset" it's shows blank page with no data.

**Comment by jmartins1** [comment]
aakibbagwan45 by chance did you follow the "Upgrading to v4 fro v3" instructions found here?

https://snipe-it.readme.io/docs/upgrading-to-v4

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading-to-v4">Upgrading to v4 from v3</a></strong></div><div>Snipe-IT v4 includes a ton of new features and bug fixes, and all users are strongly encouraged to upgrade. For a full list of what's new in V4, click here. Please note that Snipe-IT v4 does require PHP &gt;= 5.6.4. Please see the list of requirements before upgrading.Updating Snipe-IT should normal...</div></blockquote>

**Comment by jmartins1** [comment]
[ERRORS]
Uncaught ReferenceError: jQuery is not defined
    <anonymous> jQuery
pGenerator.jquery.js:146:1
Uncaught TypeError: $ is undefined
    <anonymous> http://hostname1/js/dist/bootstrap-table.js?id=58d95c93430f2ae33392:7757
    <anonymous> http://hostname1/js/dist/bootstrap-table.js?id=58d95c93430f2ae33392:4
    <anonymous> http://hostname1/js/dist/bootstrap-table.js?id=58d95c93430f2ae33392:5
bootstrap-table.js:7757:2
Uncaught ReferenceError: $ is not defined
    <anonymous> http://hostname1/:974
hostname1:974:5
Uncaught ReferenceError: $ is not defined
    <anonymous> http://hostname1/:1604
hostname1:1604:28
Uncaught ReferenceError: $ is not defined
    <anonymous> http://hostname1/:1642
hostname1:1642:9
Uncaught ReferenceError: $ is not defined
    <anonymous> http://hostname1/:1692

**Comment by jmartins1** [comment]
Upgraded to v5.1.0 without issue.
