### ISSUE TITLE
Problem with # in password when upgrade from v4 to v5

### ISSUE THREAD

**Issue by teamuppolska** [grokability/snipe-it#8979]
Hi.
If my password contains "#" (i.e. 'very#long_password') upgrade wont work. I found in cache password which is cut'ed before # sign (i.e. 'very'). When i changed password - everything is fine.

Thanks
Lukasz.

**Comment by snipe** [comment]
I assume you've already resolved this? And I assume you're referring to the database password, not your user password. If that's the case, you must enclose .env strings that have special characters within quotes.
