### ISSUE TITLE
updating php config error

### ISSUE THREAD

**Issue by atrium-complex** [grokability/snipe-it#8981]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Cannot commit changes to the .env file.
run 'php artisan config:clear'.  Am faced with this error message.

PHP Warning:  require(/var/www/snipeit/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/snipeit/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/snipeit/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/snipeit/bootstrap/autoload.php on line 17

**To Reproduce**
Updated email settings and tried to enable debug mode for additional troubleshooting.
When running php artisan config:clear.

**Expected behavior**
Should commit and apply new config

**Screenshots**

**Server (please complete the following information):**
Snipe-IT Version: v5.0.11 build 5695 (gfd4ee6027)
OS: Ubuntu: 20.04
Web Server: Apache2
PHP Version: 7.2.34-8+ubuntu20.04.1+deb.sury.org+1

I have checked to verify that the autoload.php file is there still, I do not understand why it will not detect...

**Comment by albinbatman** [comment]
Hi @atrium-complex,

It seems that your **vendor** folder is either malformed or not there at all. You need to download and install [Composer for PHP](https://getcomposer.org/) then run the following commands:

Before attempting the instructions below, please run the following command to ensure whether you have a vendor folder or not:

```bash
# We list every folder and file in /var/www/snipeit and filter results only for vendor.
[root@nginx ~]# ls /var/www/snipeit | grep vendor

# If vendor exists it should output this:
[root@nginx ~]# ls /var/www/snipeit | grep vendor
vendor
```

**If it does not exist, run the following:**
```bash
# We move into /var/www/snipeit and run a composer update
[root@nginx ~]# cd /var/www/snipeit && composer update
```

**If it does exist, run the following:**
```bash
# We move into /var/www/snipe it and we rename the vendor folder to vendor-backup
#  then we run a composer update
[root@nginx ~]# cd /var/www/snipeit && mv ./vendor ./vendor-backup && composer update

# Try to see if it works now, if it works run the following to remove the vendor-backup folder:
[root@nginx ~]# cd /var/www/snipeit && rm -rf ./vendor-backup
```

**Comment by atrium-complex** [comment]
after going through this, I managed to bark up to a second error, but quickly realized it was a permissions issue from the beginning...

I feel stupid for not looking at that before posting.  But it's been resolved.  Now I'm just trying to figure out why the mail plug-in is non functioning atm!

**Comment by uberbrady** [comment]
Excellent, glad it's been resolved! I'll close it then.
