### ISSUE TITLE
Image URL broken

### ISSUE THREAD

**Issue by felixhopfauf** [grokability/snipe-it#8984]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Wrong URL for Images:

The actual URL is:
https://asset.dohg.de/hardware/asset.dohg.de/uploads/models/assetmodel-aSJnock0HWgrtNcE3A.jpg

If I copy these URL and strip out the part between ".de" and "/uploads" I can view the image:
https://asset.dohg.de/uploads/models/assetmodel-aSJnock0HWgrtNcE3A.jpg

Uploading new images result in the same behaviour, but the new images are still located at the same path in the file system

**To Reproduce**

Open up any page with an image (models, customers, vendors)

**Expected behavior**
URL needs to be stript of that part

**Screenshots**
-

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.12 build 5705 (gf1d0d1bfe)
 - OS: Latest Docker Image (Host is Debian 10)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox 
 - Version latest

**Smartphone (please complete the following information):**

**Error Messages**
No error is provided through debug mode

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by kf0mlb** [comment]
I just upgraded our Docker instance to v5.4.1 and all of our images are broken as well.  When I click on an asset image it shows the right URL, but if I open my browser dev tools the URL shows like @felixhopfauf - _http://assetmgr.domain.tld/hardware/assetmgr.domain.tld/uploads/models/assetmodel-image-BYJjBwYNDj.png_.  If I remove **assetmgr.domain.tld/hardware/** from the URL string, then it loads the PNG in my browser.

**Comment by kf0mlb** [comment]
When I do an Inspect on the missing image from one of my laptop models, I can see both the A and IMG elements URLs don't have an http:// at the beginning, so it assumes the URL is relative.  If I edit the URL to add http:// or remove the domain name so it's just /uploads/models/..... then the image loads properly.

Is this something we can edit as part of our .env or Docker-Compose files? or is this a true bug?

**Comment by kf0mlb** [comment]
My last comment stirred something in my brain.  During the last image update I remembered adding some more environment variables to my Docker-Compose file.  I had set:

` - APP_URL = assetmgr.domain.local`

then all my image links were broken.  So I just changed the variable to be:

` - APP_URL = http://assetmgr.domain.local`

then re-deployed, and now all the image references are working properly.
