### ISSUE TITLE
Purchase cost comma problem

### ISSUE THREAD

**Issue by teamuppolska** [grokability/snipe-it#8985]
When you put Purchase Cost (adding asset) with comma ie. 11230,80, system save it in database as 1123080.00.
The solution is to use dot instead of comma, but form does not inform about it. 

Thanks 
Lukasz.

**Comment by teamuppolska** [comment]
or need to validate comma as dot, which is simplest version i think

**Comment by LucasBillbee** [comment]
I second this since it sometimes happens to me ;-)
