### ISSUE TITLE
Upgrade from v5.0.2, Header may not contain more than a single header... error 500

### ISSUE THREAD

**Issue by jaram32** [grokability/snipe-it#9002]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode -- with error 500 can not show debug mode on page (I can only check laravel.log)
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Expected behavior**
After upgrade from 5.0.2 --> 5.0.12 see 500 Server Error. (on next version v5.0.3 has a same problem like on 5.0.12)
Container is from official https://hub.docker.com/r/snipe/snipe-it    snipe/snipe-it:v5.0.12

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - 500 Server Error. No debug information from browser

**Additional context**
- Is this a fresh install or an upgrade? upgrade from 5.0.2
- What OS and web server you're running Snipe-IT on: https://hub.docker.com/r/snipe/snipe-it
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): https://hub.docker.com/r/snipe/snipe-it
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

storage/logs/laravel.log
[2021-01-13 09:31:17] production.ERROR: ErrorException: Header may not contain more than a single header, new line detected in /var/www/html/vendor/symfony/http-foundation/Response.php:346
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Header may not ...', '/var/www/html/v...', 346, Array)
#1 /var/www/html/vendor/symfony/http-foundation/Response.php(346): header('Content-Securit...', false, 200)
#2 /var/www/html/vendor/symfony/http-foundation/Response.php(380): Symfony\Component\HttpFoundation\Response->sendHeaders()
#3 /var/www/html/public/index.php(61): Symfony\Component\HttpFoundation\Response->send()
#4 {main}  
[2021-01-13 09:31:17] production.ERROR: Header may not contain more than a single header, new line detected {"userId":255,"exception":"[object] (ErrorException(code: 0): Header may not contain more than a single header, new line detected at /var/www/html/vendor/symfony/http-foundation/Response.php:346)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Header may not ...', '/var/www/html/v...', 346, Array)
#1 /var/www/html/vendor/symfony/http-foundation/Response.php(346): header('Content-Securit...', false, 200)
#2 /var/www/html/vendor/symfony/http-foundation/Response.php(380): Symfony\\Component\\HttpFoundation\\Response->sendHeaders()
#3 /var/www/html/public/index.php(61): Symfony\\Component\\HttpFoundation\\Response->send()
#4 {main}
"} 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by jaram32** [comment]
I came where problem is.
When: echo "${APP_URL}".  - The result have a two line. Second line is empty.
Second empty line is a problem.

**Comment by HDYadav** [comment]
Accept:  application/json in Postman.
