### ISSUE TITLE
Non-super users can't access Predefined Kits

### ISSUE THREAD

**Issue by sjaustad** [grokability/snipe-it#9003]
#### Expected Behavior (or desired behavior if a feature request)

Regular users with View, Edit, Checkout permissions for Kits can see the "Predefined Kits" tab and checkin/checkout kits to other users.

-----

#### Actual Behavior

Only Global Super Users can see the predefined kits tab. If I manually go to the page on a non-super user it will show a 403 Forbidden error.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running (v5.0.12 build 5705 (gf1d0d1bfe))
- Version of PHP you're running - 7.3.26
- Version of MySQL/MariaDB you're running 
- What OS and web server you're running Snipe-IT on - RHEL, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - snipeurl.com/kits
- Any errors that appear in your browser's error console. - 403 Forbidden
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - It is not
- Include any additional information you can find in `storage/logs` and your webserver's logs.
  -I only have the laravel.log in storage/logs and it doesn't have any new info in it.
- Include what you've done so far in the installation, and if you got any error messages along the way.
  -Tried granting every permission except for Super User, including Admin and it did not work.
  -Tried on multiple non-super users and it still didn't work
  -Tried doing all of the php cache clears and everything that's on the common issues page.
  -Tried resetting my cookies
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by NMX-Drew** [comment]
I'd also like to +1 this Bug. I have confirmed this behaver on v5.0.12 - build 5705 (master)

**Comment by fabricat** [comment]
I don't know if related, but I have similar issue: only superadmins see the checkout button on kits.
Admins can list kits, but cannot checkout.

**Comment by fggec** [comment]
I can also confirm. This bug is still there in v5.4.3

**Comment by snipe** [comment]
Fixed in #11024
