### ISSUE TITLE
HTTP 500 error apparently due to autoload

### ISSUE THREAD

**Issue by philipb** [grokability/snipe-it#9007]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to 'http://my.server:80'
2. A 500 error is returned

**Expected behavior**
To get something that is not a 500 error

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
In the PHP error log (/var/log/php-fpm), this message appears:

[14-Jan-2021 00:17:33 UTC] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe/bootstrap/autoload.php on line 17

Here's the output from `php -m`:

[root@localhost snipe]# php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- This is a fresh install.
- The server OS is CentOS 8
- I've performed a git + manual install, following the steps given here: https://computingforgeeks.com/install-snipe-it-asset-management-on-centos-8-linux/
- The web server I'm using is Apache/2.4.37 (centos)
- I have not manually edited any data in the database

**Comment by philipb** [comment]
Oops, missed some context:

    Snipe-IT Version: 5.0.12
    OS: CentOS
    Web Server: Apache/2.4.37 (centos)
    PHP 7.4.6

**Comment by flatronv9** [comment]
Could you try to disable setenforce?

I had the same problem with a clean install of the last realease and it was the settings of setenforce.

**Comment by philipb** [comment]
Thanks, @flatronv9.  I turned off setenforce and I no longer see the 500 error.  I get other errors, but this is progress.

Closing the issue.
