### ISSUE TITLE
attachments in asset

### ISSUE THREAD

**Issue by teamuppolska** [grokability/snipe-it#9016]
Snipe-it 5.0.12

Asset - apart from the possibility of adding a photo, it should be possible to add other attachments, e.g. an invoice in pdf.

**Comment by boring10** [comment]
You can add other attachments to assets. When you click on the asset, go to "Files" and "Upload"

![Peek 2021-01-16 07-15](https://user-images.githubusercontent.com/35600612/104811626-d85e4880-57ca-11eb-8cf7-b088c0bf9150.gif)

**Comment by teamuppolska** [comment]
Oh, i didn't notice that. Thank you so much 👍
