### ISSUE TITLE
LDAP sync issue

### ISSUE THREAD

**Issue by JasonZhang0320** [grokability/snipe-it#9018]
#### Actual Behavior
LDAP test sync error after I fill in and save the ldap settings.
-----

![image](https://user-images.githubusercontent.com/6812270/104846291-bc66be00-5914-11eb-93e6-cd42f32a15b3.png)

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh Install
- Version of Snipe-IT you're running
v5.0.12 - build 5705
- Version of PHP you're running 
 PHP 7.2.34 with zend v3.2.0
- Version of MySQL/MariaDB you're running
-10.5.8-MariaDB
- What OS and web server you're running Snipe-IT on 
CentOS Linux release 7.9.2009
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
Install snipeit with install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
after click "Test LDAP sync" the ldap setup page said something went wrong :(

```
 Unauthenticated.
/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php#81
```

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
ldap setup page
- If a stacktrace is provided in the error, include that too.
No
- Any errors that appear in your browser's error console.
No
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Demo mode has been disabled the ldap sync
- Include what you've done so far in the installation, and if you got any error messages along the way.
No 
- Indicate whether or not you've manually edited any data directly in the database
 No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by MournfulRaven** [comment]
Try to set "LDAP Authentication query" field as: _sAMAccountName=_ instead of _uid=samaccountname_

**Comment by JasonZhang0320** [comment]
> Try to set "LDAP Authentication query" field as: _sAMAccountName=_ instead of _uid=samaccountname_

Thanks man, that's really help me to fix it.
