### ISSUE TITLE
Snipe-it doesn't see database after docker restart

### ISSUE THREAD

**Issue by coristo** [grokability/snipe-it#9021]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Hi, 
my snipe-it was working really good until i reebooted machine with docker.
Now when i'm going to website i can see setup screen and 
```
D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: SQLSTATE[HY000] [2002] Connection refused (SQL: select 2 + 2)
```
I've checked addresses and, they are coorect. i can ping snipe-it from mysql container and mysql from snipe-it.
I can access mysql using credentials stored in snipe-it...
in both logs is no info about connection.
i'm using internal ip addresses, in mysql container i've got ports redirect: 8100:3306, but in snipe-it .env file i've got 3306 (when i change it, after reboot i've got still 3306).

(I'm using docker, and i think my .env file is in root directory...is it?)

**To Reproduce**
1. Install snipe-it and mysql in containers
2. Configure app
3. Reboot VM

**Expected behavior**
Snipe-it should work with all data from existing database.

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version 7.2.24

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome, Firefox

**Error Messages**
```

D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: SQLSTATE[HY000] [2002] Connection refused (SQL: select 2 + 2)
```

**Additional context**
- Is this a fresh install or an upgrade?  -  It was stable from 2 months
- What OS and web server you're running Snipe-IT on  -  Ubuntu 18.04, Apache 2.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  -  Docker

**Comment by rstaudmyer** [comment]
Did you ever find a solution to this? I am experiencing the same thing.
