### ISSUE TITLE
Asset-tag in URL query rather than number ID. 

### ISSUE THREAD

**Issue by FinlandApollo** [grokability/snipe-it#9030]
Dear all!

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.12
 - OS: ARM7 (Docker)
 - Web Server: Apache
 - PHP Version 7.3.26

**Describe the solution you'd like**
Snipe-It looks very versatile and very nicely working software, but one thing I'm not a fan is that if I'd like to access asset "Test001" through URL, the address is *IP*:8080/hardware/1 rather than being *IP*:8080/hardware/Testi001. IMO the latter one would work better, especially if something gets deleted. And also, the device tag name could be easily checked and URL validity too.

Kindly
-FinlandApollo

**Comment by boring10** [comment]
You can query the asset tag with the following URL query.

https://domain/hardware/bytag?assetTag=

**Comment by FinlandApollo** [comment]
> You can query the asset tag with the following URL query.
> 
> https://domain/hardware/bytag?assetTag=

Sweet, big thanks! This makes my life so much easier ^^
