### ISSUE TITLE
Check-out multiple consumables

### ISSUE THREAD

**Issue by chris-jasztrab** [grokability/snipe-it#9033]
I would like to suggest a feature where a user could check out a quantity of consumables rather than one at a time.  For instance if I were to replace all the mice in a school lab on a yearly basis I would like to be able to check out 30 art a time.

**Comment by MournfulRaven** [comment]
Hi!
You can bulk check out from menu like on screenshot for one person.
![image](https://user-images.githubusercontent.com/74963744/105673784-984c4380-5ef7-11eb-8825-77ec07f2ab28.png)

**Comment by chris-jasztrab** [comment]
Thank-you for your reply on this comment.  I looked and the instructions you provided me to go to Assets -> Bulk Checkout doesn't work for consumables.  When I tried to check out items, my consumable didn't show up in the list.  I think we will get around this limitation by classifying our consumables into lots.  So a box of 50 items.  Then a staff member will go into the consumable area, and check out a box.
