### ISSUE TITLE
CentOS7 IUS repos have moved, fresh install with snipeit.sh fails

### ISSUE THREAD

**Issue by doombirdAD** [grokability/snipe-it#9035]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
IUS repository has moved from iuscommunity.org to repo.ius.io.  The `snipeit.sh` install script uses the old URL, and fails to find the repo.  Furthermore, the packages listed in the install file are no longer available on IUS anyway (php71u _et al_).  Moving to the new location and installing the 7.2u packages instead of the 7.1u packages fixed the issue and allowed me to finish the installation.

**To Reproduce**
1. Fresh CentOS 7 install
2. Download or `git clone` and run ./snipeit.sh
3. Silently fails to install dependencies from IUS
4. Installation fails on missing dependencies.

**Expected behavior**
Installation succeeds and a web browser can access the setup page.

**Server (please complete the following information):**
 - Snipe-IT Version: pulled from GitHub
 - OS: CentOS 7

**Error Messages**
While running the `./snipeit.sh` script:
```
* Adding IUS, epel-release and MariaDB repositories.
* Installing Apache httpd, PHP, MariaDB and other requirements.
  * Installing httpd
  * Installing mariadb-server
  * Installing git
  * Installing unzip
  * Installing php71u
  * Installing php71u-mysqlnd
  * Installing php71u-bcmath
  * Installing php71u-cli
  * Installing php71u-common
  * Installing php71u-embedded
  * Installing php71u-gd
  * Installing php71u-mbstring
  * Installing php71u-mcrypt
  * Installing php71u-ldap
  * Installing php71u-json
  * Installing php71u-simplexml
  * Installing php71u-process
* Configuring Apache.
```
...snipped for brevity...
```
* Cloning Snipe-IT from github to the web directory.
* Configuring .env file.
* Installing composer.
-bash: php: command not found
-bash: php: command not found
ERROR: Invalid composer installer signature
```

**Additional context**
- I was able to fix the issues by pointing to the new location of the IUS repository and updating the package lists.
```
diff --git a/snipeit.sh b/snipeit.sh
index d6d65619b..881a4411e 100755
--- a/snipeit.sh
+++ b/snipeit.sh
@@ -655,11 +655,11 @@ EOL

     echo "* Adding IUS, epel-release and MariaDB repositories."
     log "yum -y install wget epel-release"
-    log "yum -y install https://centos7.iuscommunity.org/ius-release.rpm"
+    log "yum -y install https://repo.ius.io/ius-release-el7.rpm"
     log "rpm --import /etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY"

     echo "* Installing Apache httpd, PHP, MariaDB and other requirements."
-    PACKAGES="httpd mariadb-server git unzip php71u php71u-mysqlnd php71u-bcmath php71u-cli php71u-common php71u-embedded php71u-gd php71u-mbstring php71u-mcrypt php71u-ldap php71u-json php71u-simplexml php71u-process"
+    PACKAGES="httpd mariadb-server git unzip php72u php72u-mysqlnd php72u-bcmath php72u-cli php72u-common php72u-embedded php72u-gd php72u-mbstring php72u-mcrypt php72u-ldap php72u-json php72u-simplexml php72u-process"
     install_packages

     echo "* Configuring Apache."
```

- The CentOS 6 install points to the same repository, so that's likely also going to have the same problem, but I don't have a Cent 6 box to test on immediately.  So I'm going to focus this ticket on the problems I know I have.

**Comment by luanche** [comment]
👍

**Comment by vithurshanselvarajah** [comment]
I can confirm making the above changes fixes the script for me too
