### ISSUE TITLE
Am getting error while uploading file in user profile. Please suggest me on this, 

### ISSUE THREAD

**Issue by swegaj** [grokability/snipe-it#9041]
![image](https://user-images.githubusercontent.com/60129951/105577369-2eb92180-5d9f-11eb-905b-5f561ea9b7e4.png)

Hi ,

Am getting error while uploading file in user profile. Please suggest me on this, (attached screenshot as well for reference,

Also check in Snipe-it demo also facing same error.

It was working ver4 now i was upgraded newer getting above error...

Please help me .

**Comment by swegaj** [comment]
Hi All,
Please can you one suggest me on this  issues....

**Comment by inietov** [comment]
Hello! Thanks for your report.

I don't have a suggestion but I'm looking at this now and I hope to have a fix ready trough the day.

**Comment by inietov** [comment]
I think it's resolved in the PR merged a few time ago. I'm closing the issue, but feel free to reopen if necessary.

**Comment by swegaj** [comment]
Yes, You guys are awesome !!!  Great job...

Snipe -Good work !!!! Issue has been fixed .. as per solution

**Comment by swegaj** [comment]
Please help us this as well... Please..

Reset Password Notification-Need to change expire link from 900 min to 30 minutes.
