### ISSUE TITLE
LDAP Sync fine, but login failed w/ or w/o the append domain name to username field &LDAP Password Sync checked.

### ISSUE THREAD

**Issue by JasonZhang0320** [grokability/snipe-it#9050]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Same as subject.

**To Reproduce**
In the LDAP setting page, the Test LDAP Login always fails whether or not checked the **append domain name to username field &LDAP Password Sync**

**Screenshots**

![image](https://user-images.githubusercontent.com/6812270/105930406-95328e00-6084-11eb-97a7-2e0bec466801.png)

**Server (please complete the following information):**
 - Snipe-IT Version :5.0.12
 - OS: CentOS 7.9 2009
 - Web Server: Apache 2.4.6
 - PHP Version:7.2.34 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 64bit
 - Version:88.0.4324.104

**Error Messages**
**With Append domain name checked:**

Username:jason_zhang
Unable to validate user credentials!

**Without Append domain name checked:**
Username:jason_zhang
Unable to validate user credentials!

Username:jason_zhang@mydomain.com
Unable to validate user credentials!

UserName:mydomain\jason_zhang
Unable to find user in LDAP directory!

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on. Centos 7.9 2009 with Apache 2.4.6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc). install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way. N/A
- Indicate whether or not you've manually edited any data directly in the database. N/A

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by uberbrady** [comment]
Can you try, in the "Username Field" - instead of `sAMAccountName`, try `samaccountname` - it's a strange artifact of our LDAP integration libraries that *that* field needs to be in lower-case, but the authentication query needs to be mixed-case (matching the server). We could definitely display or handle this better, though; that's on us

**Comment by JasonZhang0320** [comment]
> Can you try, in the "Username Field" - instead of `sAMAccountName`, try `samaccountname` - it's a strange artifact of our LDAP integration libraries that _that_ field needs to be in lower-case, but the authentication query needs to be mixed-case (matching the server). We could definitely display or handle this better, though; that's on us

Hi, uberbrady, try the samaccountname, the result same as "sAMAccountName".

**Comment by uberbrady** [comment]
It could be your first name attribute? I'm used to that being something like `givenname` in AD. If you don't have a first name set up, it won't let you log in.

**Comment by JasonZhang0320** [comment]
> It could be your first name attribute? I'm used to that being something like `givenname` in AD. If you don't have a first name set up, it won't let you log in.

I just fill in the LDAP First Name with "givenname", no help for me. But I finanlly got it work. The firstname, lastname must be filled in with correct value,   and the Active Directory domain should be same with userprincipalname's suffix.

appreciate your help! Thx!
