### ISSUE TITLE
Access to SNIPE IT

### ISSUE THREAD

**Issue by VJYOURMD** [grokability/snipe-it#9056]
Sorry I'm not a techie but I cannot recover access to my SNIPE IT account, it's frequently the case that I have to change my password but this time, requesting a reset of password is NOT generating a link to my email tracy@your.md. SNIPE is a critical resource and I cannot access. The other profile I use to access this is via uk.billing@your.md BUT the site is unresponsive to this email account. Please help, it's been 24 hours plus and I have requested reset at least 3 times and I cannot access Gitter, either which is where I think I got help before.

My IT support have also had issues. 
Many thanks!

Tracy

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
We'll contact you directly through our helpdesk system.
