### ISSUE TITLE
Field permissions

### ISSUE THREAD

**Issue by theemstra** [grokability/snipe-it#9064]
**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.12/5705 master
 - OS: Ubuntu 20.04
 - Web Server: Apache
 - PHP Version 7.4

**Is your feature request related to a problem? Please describe.**
When we allow users to view assets, they are able to view all data that has anything to do with that asset. For our use case some users shouldn't be able to see financial details, supplier etc. So we would like to hide those fields from the asset overview.

**Describe the solution you'd like**
Currently there are user permissions, I'd like to add a feature that allows group/user field permissions, for custom fields, but also for normal fields, so admins can set who can see the fields of an asset.

**Describe alternatives you've considered**
I've checked out https://snipe-it.readme.io/docs/user-permissions but it appears to me this is more radical, in terms of hiding the asset completely, not tunable to the field, but please correct me if I'm wrong.

**Additional context**
We are an MSP and provide companies with IT hardware and software.
We usually have one or 2 'powerusers' that are problem-solvers, so we would give them access to our Snipe-IT system, which would allow them to see the registered hardware (not add/edit anything, just see and potentially request).

**Comment by newbie-admin** [comment]
Hello,

We have the same issue. All users are able to see all assets, accessories, licenses, if granted basic permissions. This should be fixed so that user can view, add, remove, modify only records that are concerning him/herself. Permissions are not granular at the moment and too basic.
