### ISSUE TITLE
All list tables empty, api returns 401

### ISSUE THREAD

**Issue by Azazel666** [grokability/snipe-it#9069]
#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
We have created a new instance in azure for a new snipe it instance/site. We have multiple instances since before that runs just fine. But this new site gets 401 on every place where there is a data table showing data, eg. companies, locations, users, etc.

I have read through #8758 and also left a comment (no responses yet).
We have enabled debug mode and only thing it is showing us is the exception:
Unauthenticated.
C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php#66

As reading on the [Common Issues](https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated) we have looked at the cache files, but only cache file we had from the three in that list was the `bootstrap/cache/services.php` when deleted it is re-generated on a new page load, but did not help.

When enabling debug mode i aslo found `php artisan config:cache` to clear cache, this also generated the file ´bootstrap/cache/config.php` but still did not solve anything.

We have looked through the PHP modules/extensions from the required page and as far as i can confirm by looking at the PHP settings with help of the `phpinfo()` command, everything that is required is available and enabled.

**To Reproduce**
Unfortunately i have no way of explaining how to reproduce this and is more looking for help how to diagnose the issue so we can fix the issue. I don't really believe this is a bug but some weird install misshap, however this is constant (we have re-deployed the snipe it web app and installed it numerous times with same result).

**Server (please complete the following information):**
 - Snipe-IT Version: 4.8
 - OS: Azure web app container
 - Web Server: Apache
 - PHP Version: 7.3

**Error Messages**
Unauthenticated.
C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php#66
Illuminate\Auth\AuthenticationException
            }
        }

        throw new AuthenticationException('Unauthenticated.', $guards);
    }
}

#0 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(41): Illuminate\Auth\Middleware\Authenticate->authenticate(Array)
#1 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#2 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#4 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#5 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#6 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#7 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(590): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#8 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#9 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#10 C:\home\site\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 C:\home\site\wwwroot\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 C:\home\site\wwwroot\app\Http\Middleware\CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 C:\home\site\wwwroot\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 C:\home\site\wwwroot\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\home\site\wwwroot\app\Http\Middleware\ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\home\site\wwwroot\app\Http\Middleware\ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\home\site\wwwroot\app\Http\Middleware\XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 C:\home\site\wwwroot\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\home\site\wwwroot\vendor\barryvdh\laravel-cors\src\HandlePreflight.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 C:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#55 C:\home\site\wwwroot\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#56 {main}

[PHP Modules]
bcmath
calendar
com_dotnet
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
imap
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlsrv
pgsql
Phar
readline
Reflection
session
SimpleXML
soap
SPL
sqlsrv
standard
tidy
tokenizer
wddx
wincache
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by sfrielink** [comment]
Hi - 
Interestingly I have been trying over the last few days to resolve almost the exact same problem.  I have created a totally new environment on an Azure Windows 2016 server:

Snipe-IT Version: 5.1
OS: Windows 2016
Web Server: IIS
PHP Version: 7.3.26

When I go into the app and add anything like a company, a person or an asset, I always get "No matching records found".  But I know the app is saving the data correctly because I can go into the DB and see the items that I created, they are just not showing up in the website.

I am getting the same error message while in debug mode:

Unauthenticated.
C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php#81
Illuminate\Auth\AuthenticationException
     */
    protected function unauthenticated($request, array $guards)
    {
        throw new AuthenticationException(
            'Unauthenticated.', $guards, $this->redirectTo($request)
        );
    }

I've tried everything I could find in every issue I could find.  I hope you don't mind me jumping on this issue, but these are so similar I figured I'd add on to this one rather than opening a new issue that addresses the same thing.

**Comment by Leezj9671** [comment]
Same issue using docker, also need help

**Comment by Leezj9671** [comment]
> Same issue using docker, also need help

May be because I used `composer update` or something in docker before. `rm` and `run` again solve this problem.

**Comment by snipe** [comment]
If you don't mind me asking, why would you be installing Snipe-IT Version: 4.8 when v5 has been out for months? Also how did you install it? (Git, etc?)

**Comment by Azazel666** [comment]
We have multiple instances of snipe it running on a range of different instances and subscriptions in Azure. 4.8 is the latest release we have built in devops and pushed to these instances. Now we're trying to setup 4 more and we are pushing out the exact same build for these so we know we're running the exact same thing on all instances. That is the simple reason why we're still on 4.8.

**Comment by snipe** [comment]
Thanks for your candor. v4.8 is pretty old though - from Dec 6, 2019. There have been 1575 commits to master since this release, and I have to be honest, I don't know how much time we'll have to help debug such an old version. (I'm also kinda dying to know why you need so many versions of Snipe-IT running, but that's probably a different conversation.) 

Can you clone the image of a working server instance with Snipe-IT installed and just truncate the databases to be 100% sure the environments are exactly the same? The troubleshooting we have listed in the Common Issues section covers every single instance we've run into where we've seen the 401 error - tho those are much more common on the v5 branch. (You shouldn't technically even be looking at the v5 documentation if you're still running v4.8, since you could potentially break something if the framework requirements changed between those versions.)

**Comment by Azazel666** [comment]
Looks like we have managed to solve the issue we had. The main cause seems to have been Laravel framework it self. it was running 5.5.50. When downgraded to 5.5.49 we managed to get the site booting up. then we degraded to 5.5.48 to have it in the same version as the other instances. Here we had new troubles caused by composer. Seems that composer was automatically running version 2 now and that worked fine with laravel on 5.5.49 but was causing other issues when running 5.5.48. So we have forced to install composer as latest version 1 (eg. 1.10.20) and set composer.json to run laravel/framework 5.5.48.

**Comment by snipe** [comment]
That's.... not really a great answer though. Now your `composer.json` isn't running the same as we are, which means you're going to potentially run into mystery bugs (since the code is expecting particular versions of things) which we won't be able to explain, and you're going to have a harder time upgrading. You should never be messing with composer.json directly. 

We use composer 2 locally an on our thousands of hosted instances, so there isn't an incompatibility there.

You should definitely try to update the entire fleet as soon as you can, and get it to a place where you don't have any special exceptions like your bespoke composer.json.
