### ISSUE TITLE
WebGui import works without issue, however using php artisan:import does not

### ISSUE THREAD

**Issue by Starscales** [grokability/snipe-it#9071]
#### Please confirm you have done the following before posting your bug report:

- [/] I have enabled debug mode 
- [/] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I use a script to generate a CSV file when users log in.  There are two scripts that I use; one has a username, email address and full name associate with it, the other does not.  Both CSV files will import without issue from the web GUI but only the file without the username, email address and full name will import successfully from the command line.  I get an error message when trying to import the full CSV:

[Symfony\Component\Debug\Exception\FatalThrowableError]
Argument 3 passed to App\Events\CheckoutableCheckout::_construct() must be an instance of App\Models\User, null given, called in C:\Apache24\htdocs\snipe-it\app\Models\Asset.php on line 312

Exception trace:
  at C:\Apache24\htdocs\snipe-it\app\Events\CheckoutableCheckedOut.php:23
App\Events\CheckoutableCheckedOut->__construct() at C:\Apache24\htdocs\snipe-it\app\Models\Asset.php:312
App\Models\Asset->checkOut() at C:\Apache24\htdocs\snipe-it\app\Importer\AssetImporter.php:124
App\Importer\AssetImporter->createAssetIfNotExists() at C:\Apache24\htdocs\snipe-it\app\Importer\AssetImporter.php:46
App\Importer\AssetImporter->handle() at C:\Apache24\htdocs\snipe-it\app\Importer\Importer.php:143
App\Importer\Importer->App\Importer\{closure}() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Concerns\ManagesTransactions.php:29
Illuminate\Database\Connection->transaction() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:349
Illuminate\Database\DatabaseManager->__call() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:261
Illuminate\Support\Facades\Facade::__callStatic() at C:\Apache24\htdocs\snipe-it\app\Importer\Importer.php:150
App\Importer\Importer->import() at C:\Apache24\htdocs\snipe-it\app\Console\Commands\ObjectImportCommand.php:63
App\Console\Commands\ObjectImportCommand->handle() at n/a:n/a
call_user_func_array() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32
Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php:36
Illuminate\Container\Util::unwrapIfClosure() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:90
Illuminate\Container\BoundMethod::callBoundMethod() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:34
Illuminate\Container\BoundMethod::call() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php:590
Illuminate\Container\Container->call() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php:134
Illuminate\Console\Command->execute() at C:\Apache24\htdocs\snipe-it\vendor\symfony\console\Command\Command.php:255
Symfony\Component\Console\Command\Command->run() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php:121
Illuminate\Console\Command->run() at C:\Apache24\htdocs\snipe-it\vendor\symfony\console\Application.php:1001
Symfony\Component\Console\Application->doRunCommand() at C:\Apache24\htdocs\snipe-it\vendor\symfony\console\Application.php:271
Symfony\Component\Console\Application->doRun() at C:\Apache24\htdocs\snipe-it\vendor\symfony\console\Application.php:147
Symfony\Component\Console\Application->run() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php:93
Illuminate\Console\Application->run() at C:\Apache24\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:131
Illuminate\Foundation\Console\Kernel->handle() at C:\Apache24\htdocs\snipe-it\artisan:35

**To Reproduce**
1. Open command line
2. CD to C:\Apache24\htdocs\snipe-it
3. Run 'php artisan snipeit:import techuser.csv --item-type Asset --user_id 20 --verbose'
4. This works
5. Run 'php artisan snipeit:import user.csv --item-type Asset --user_id 20 --verbose'
4. This reports success but does not do anything (I realise this is because it's a duplicate)
5. Run 'php artisan snipeit:import techuser.csv --update --item-type Asset --user_id 20 --verbose'
6. This works
7. Run 'php artisan snipeit:import user.csv --update --item-type Asset --user_id 20 --verbose'
8. This does not work and produces the above error

Techuser.csv:
Full Name,Email,Username,item Name,Category,Model name,Manufacturer,Model Number,Serial,Asset Tag,Location,Notes,Purchase Date,Purchase Cost,Company,Status,Warranty months,Supplier
,,,307994,Laptop,Latitude 3400,Dell Inc.,,GY6GNW2CNWSC0004100LW,307994,UK,29/01/2021 14:54:53 - Technician login: DOMAIN\techuser,,,,Pending,,

User.csv:
Full Name,Email,Username,item Name,Category,Model name,Manufacturer,Model Number,Serial,Asset Tag,Location,Notes,Purchase Date,Purchase Cost,Company,Status,Warranty months,Supplier
Test User (DOMAIN),test.user@domain.com,DOMAIN\testuser,307994,Laptop,Latitude 3400,Dell Inc.,,GY6GNW2CNWSC0004100LW,307994,UK,29/01/2021 15:44:15 - Login Type: User,,,,Deployed,,

**Expected behavior**
Expecting asset to import and be checked out to the user mentioned in the csv (I'm sure this worked in previous versions)

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.13 build 5728 (gb4eee5a9b)
 - OS: [Windows 10]
 - Web Server: [Apache 2.4.46]
 - PHP Version 7.4.14

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge (Chromium)]
 - Version [88.0.705.50]

**Smartphone (please complete the following information):**
 - NOT USED

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on (Windows 10 with Apache see above)
- What method you used to install Snipe-IT (fresh install manual install of Apache2, PhP, MySql and installed via Git)
- Include what you've done so far in the installation, and if you got any error messages along the way. No errors installing
- Indicate whether or not you've manually edited any data directly in the database. No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Starscales** [comment]
Thought I'd test again with my original Snipe-IT I had set up on a VHD.  That version was 4.9.5 build 4482 and it works perfectly

**Comment by Starscales** [comment]
I've done some further tests and decided to do an update of the 4.7 Snipe-IT I had on a Hyper-V VM.  I used upgrade.php and all appears well and the web GUI is working as expected, however now this machine (now on 5.0.13) is also showing the exact same issue.

**Comment by snipe** [comment]
Are you seeing this in v6?
