### ISSUE TITLE
Advanced Search - Purchase Date -> no return

### ISSUE THREAD

**Issue by GustelDE** [grokability/snipe-it#9077]
Hi,

if I search for the date of purchase (dont know the english translation in snipe-it), no results are returned:

Lets search for the "01.01.2020"
![01](https://user-images.githubusercontent.com/26502186/106652195-5d03e180-6595-11eb-8881-24ec23d9916f.jpg)

Same in the "Advanced Search":
![02](https://user-images.githubusercontent.com/26502186/106652222-68efa380-6595-11eb-9506-19fa00e57276.jpg)

No result:
![03](https://user-images.githubusercontent.com/26502186/106652260-786eec80-6595-11eb-8362-47bb1d907ed9.jpg)

**Comment by snipe** [comment]
Very possible there's a bug there, but that date format would never work. All dates are stored at YYYY-MM-DD in the database

**Comment by GustelDE** [comment]
Hi, it works with the YYYY-MM-DD format!
Maybe a info/tooltip would be helpful (or a way the search considers the local date format).

**Comment by snipe** [comment]
Unfortunately, that advanced search modal is an extension that doesn't work nearly as well as we want and isn't super customizable out of the box, so I don't know that we could even add a tooltip without impacting the core extension code (thus making our life hell and losing changes when we next upgrade it). Our plan is to write our own or contribute back to the Bootstrap Tables extension to hopefully make it a little less brittle, but we're kinda slammed here with other things already.

I can at least add a note to the docs tho.

**Comment by GustelDE** [comment]
Would be helpful as well!
I will note the format in our internal documentation.
