### ISSUE TITLE
Feature Request regarding status labels

### ISSUE THREAD

**Issue by Joly0** [grokability/snipe-it#9082]
Currently there are a few status labels like ready to deploy or archived and status types like deployable.

Ready to deploy is special though, as it additionaly can show, if an asset is deployed or not through the deployable status type. In my opinion this is confusing to see hundreds of assets being deployable in the dashboard, but only a fraction of it is really deployable, as the others are just marked as deployed.

In my opinion there should be a difference between ready to deploy (without being deploeyed) and ready to deploy (deployed) in the dashboard and aswell while filtering or sorting by status. If thats not possible, i would suggets scrap that "deployable" status-type and make it possible to change the status of an asset while checkout (the first option would be easier for users, the second is harder but i guess easier for the developer).

**Comment by snipe** [comment]
You're welcome to change the status label names to whatever makes the most sense for you. Ready to Deploy is a default one we provide, but we encourage folks to use whatever makes sense to their workflow.

**Comment by Joly0** [comment]
Thank you for the answer. Yes i know i can change it. But maybe i didnt pointed it out clearly: changing the name of the status label is not so useful, as while checkout (atleast for me it seems like it) i cant change the status. So when i have ready to deploy and deployed as status labels, i cant switch back on forth while checkin/checkout, all the time i have to edit the asset separatly and change the status label.

**Comment by Joly0** [comment]
@snipe My bad, this only occurs at checkout, not checkin, but still a problem. Why is it possible to change the status at checkin but not checkout? In my opinion it should be possible while checkout aswell so i can change the status from ready to deploy to deployed (something like that)
