### ISSUE TITLE
Issues with Ldap Sync 

### ISSUE THREAD

**Issue by daveqban** [grokability/snipe-it#9086]
Trying to set up a cron job for ldap Sync but not working. I am manually running the following command but does not sync. for now only the Manual Sync Work without issues.

php /var/www/snipeit artisan snipeit:ldap-sync --location=X --sumary

also trying without the location and with the location id, but nothing.

/usr/bin/php /var/www/snipeit artisan snipeit:ldap-sync --location_id=2 --sumary

Thanks in advance

**Comment by uberbrady** [comment]
`artisan` is just a file in Snipe-IT, so you probably want to try:

`php /var/www/snipeit/artisan snipeit:ldap-sync` - which will do the same thing as hitting the button

If you specify a Location, you have to specify a Base DN as well.

**Comment by daveqban** [comment]
cool, that worked thanks.
