### ISSUE TITLE
Allow per company asset tag schemes to be created in Admin > Asset Tags

### ISSUE THREAD

**Issue by carlashley** [grokability/snipe-it#9089]
**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.12 - build 5705 (master)
 - OS: [e.g. Ubuntu, CentOS]: Debian 10
 - Web Server: [e.g. Apache, IIS]: Apache2
 - PHP Version: 7.3

**Is your feature request related to a problem? Please describe.**
The companies features in Snipe-IT is great, however we're not able to specify a new asset tag "profile" for companies.

**Describe the solution you'd like**
When multiple companies are created in Snipe-IT, they currently share the same asset tag configuration scheme as set in the Admin > Asset Tags interface. This means that if a different asset tag scheme is needed for assets in one company as opposed to other companies, the person creating an asset in Snipe-IT must manually change the prefix.

Being able to define asset tag schemes on a per company basis and have Snipe-IT automatically adjust the asset tag value when creating a new asset for a given company would be helpful.

**Describe alternatives you've considered**
Currently we manually change the prefix which requires the person creating an asset to remember to change the prefix.

**Comment by FirstUnionGroup** [comment]
+1 for this feature. We have a group of companies and each is expected to have their unique asset tag

**Comment by MarcusGHub** [comment]
+1 for this too

**Comment by snipe** [comment]
This is a duplicate of #3286
