### ISSUE TITLE
Images are showing up as broken links

### ISSUE THREAD

**Issue by djshoxxx** [grokability/snipe-it#9090]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Images are not loading. Confirmed that the APP_URL in the .env file is set to http://192.168.1.2:8086 <- which is the exact same as what we are using to access snipeit

**To Reproduce**
- load any page with any uploaded or created image such as a created QRBarcode that should be on an asset page

Note: images still do not load when clicked on or in other browsers. when the source is inspected it shows that the images are being pointed to 192.168.1.2:8087. When the port in the html source gets changed to the correct port (8086) the images will load correctly.

**Expected behavior**
Images should not be broken

**Screenshots**
screenshots added

**Server (please complete the following information):**
 - Snipe-IT Version  v5.0.13-pre build 5749 (gd19c6ab8e)
 - OS: [ UnRaid Version: 6.8.3]
 - Web Server: [UnRaid Docker]
 - PHP Version  7.2.24-0ubuntu0.18.04.7

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [tested in chrome, firefox and edge on multple computers with same result]

**Error Messages**
only error is images not loading

**Additional context**
- Is this a fresh install or an upgrade?  fresh install

- What OS and web server you're running Snipe-IT on- UnRaid

- What method you used to install Snipe-IT - docker

- Include what you've done so far in the installation, and if you got any error messages along the way.
attempted different .env file settings with same result, attempted to use:
composer dump-autoload
composer clear-compiled
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear

and then restarting docker and unraid. confirmed that I am editing the live .env file

- Indicate whether or not you've manually edited any data directly in the database
just the env file, resetting it back to what it was before after it confirmed did not work

-I am new to snipeit so please go easy on me. I am guessing it has something to do with the APP_URL due to reading about similar issues from other tickets but ive tried changing it to no avail

![env settings](https://user-images.githubusercontent.com/78512044/106828235-a3614b00-663e-11eb-8dea-6fba2bd14200.jpg)
![asset image not loading1](https://user-images.githubusercontent.com/78512044/106828292-becc5600-663e-11eb-8607-34233c69644d.jpg)
![qrcode working](https://user-images.githubusercontent.com/78512044/106829101-53838380-6640-11eb-9f83-d8bbab16f442.jpg)

**Comment by snipe** [comment]
Are you running this through any kind of proxy or something? I don't know of any obvious reasons why it would change your port number.

**Comment by djshoxxx** [comment]
No, just using it through docker. Here are the docker settings, but im assuming that this is normal...
![2021-03-11 17_05_11-Window](https://user-images.githubusercontent.com/78512044/110876646-c3fb7100-828c-11eb-88fb-c1946c386872.png)

It took me a few tries at following the instructions step by step to actually get it right and not skip, misinterpret or neglect making proper configuations.

During one of my re-tries I remember having the exact same issue, with images being shown in the browser pointed to the correct port/place, but in reality they were somehow one port ahead of where they should have been.

**Comment by djshoxxx** [comment]
Oh my God I think I am the biggest idiot in the world. I go to click edit on the docker and this is what I see... I am wrong about everything. It was a typo, and I am sorry for taking up your time when it was my own fault.
![2021-03-11 17_22_07-Window](https://user-images.githubusercontent.com/78512044/110877799-d9719a80-828e-11eb-99c0-19faae83b5ef.png)


Now that I found this, is there no way I can change it? Will i have to do a full re-install to fix this? Because the env files are definately now pointing to the correct ports.

I re-tried installing snipe-it so many time I must have totally forgotten that this was once one of the things I had fixed during editing the env files/troubleshooting.

**Comment by djshoxxx** [comment]
to add to my last post: if i remember correctly, If I edit and save that page, then I am essentially resetting the program back in time where  would ended to do the pre-flight page and I had to pretty much start from scratch again.

Seeing that we already stared using the slightly broken version of snipe-it (the one that I broke, I take 100% full responsibility for breaking it and asking others to ho help instead of triple checking my own work.) and we have started populating assets, 30- different locations (with their own sublocations, suppliers,  accessories, consumables and about 10 actives users (and counting) all using the system daily, I really dont want to start over or break it (again.

I remember that trying to use the 'edit' page above ^ that shows my fsk up, and saving changes would break the install far worse than it currently is and bring me back in time to the pre-flight

Please help me not screw up a worse than I already have! Pleases tell me tthere is a way to fix this !

**Comment by snipe** [comment]
I know this issue is pretty old - I'm doing some cleanup on older issues. Did you ever get this sorted?
