### ISSUE TITLE
Passwords for newly created users are sent as HTML.

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#9097]
#### Please confirm you have done the following before posting your bug report:
**Describe the bug**
If generated password has symbol **`\`** in it, this symbol will be filtered by  email.

**To Reproduce**
1. Go to 'People' and manually create new user.
2. Create a password containing **`\`**, add checkmark next to ' Email this user their credentials?'.
3. Click 'Save'.
4. Check your email and compare passwords.

**Expected behavior**
Passwords match.

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.0 - build 5772 (master)
 - OS: Ubuntu Server 20.04
 - Web Server: Apache
 - PHP Version 7.4

**Desktop (please complete the following information):**
 - OS: Ubuntu Studio 20.04
 - Browser: firefox

**Additional context**
- Is this a fresh install or an upgrade? **fresh** 
- What method you used to install Snipe-IT? Manual installation, all requirements were met for the installation - followed snipeit documentation.

- Created new user on totally different install. First line is password I've created, second is what came by email. Looks like text is being converted to HTML when generating email.
![paveikslas](https://user-images.githubusercontent.com/3755203/106893512-53de5600-66f6-11eb-8453-1a27f497de62.png)

**Comment by snipe** [comment]
This is kind of a difficult problem to solve without introducing potential XSS issues. :-/

**Comment by Iizuki** [comment]
At least the passwords generated through the UI should work. ATM they too include problematic characters.
