### ISSUE TITLE
Asset Model Import

### ISSUE THREAD

**Issue by mexx3001** [grokability/snipe-it#9098]
Is there a way to import asset models?
I don't want to spend all my time manually creating model after model.

We use Version 5.1.0 build 5772

**Comment by ItsANoBrainer** [comment]
When importing assets, if the model is not found, it will auto create it for you and set the category to the same as the asset it's being assigned to.

Any custom fields can be done during import as well, you just need to add the new models to your fieldsets and then the custom field data will show up on the asset. Custom fields wont show visually on the asset until the fieldset is setup, but the custom fields are still saved to the asset regardless.

**Comment by mexx3001** [comment]
Ok thanks. It works
