### ISSUE TITLE
LDAP Broke

### ISSUE THREAD

**Issue by Hammy7688** [grokability/snipe-it#9100]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading via github my LDAP no longer works. Every time I try to make a change it gives me a 500 server error

**To Reproduce**
1. Go to 'Settings'
2. Click on 'LDAP'
3. Scroll down to 'Test LDAP'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/78551850/106917037-da367000-66d5-11eb-88d3-cdf499956990.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.0 build 5772
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.2.24

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.104

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by OrigamiPhil** [comment]
I had the exact same problem after I setup a new server and imported my database. I used the migrations list from here: https://github.com/snipe/snipe-it/issues/8657#issuecomment-720804407 and compared it to what was in the `migrations` table on the new server. I then added in the missing ones and re-ran `php artisan migrate`. Once I'd been through the list, I went into the server, unticked the LDAP integration box, saved, and then re-ticked it and saved again. That fixed it.

**Comment by Hammy7688** [comment]
@OrigamiPhil How do you get to the migrations table?

**Comment by OrigamiPhil** [comment]
Connect to your database server, choose the database, select the table and output the contents:
`sudo mysql -u root -p`
`use <database_name>;`
`select * from migrations;`

If you have migrations missing, use:
`insert into migrations(migration,batch) VALUES ('migration name',1);`

**Comment by Hammy7688** [comment]
@OrigamiPhil thank you so much!
