### ISSUE TITLE
500 Server Error - Test Ldap Sync

### ISSUE THREAD

**Issue by itamarshpak** [grokability/snipe-it#9108]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When Testing Ldap Synchronisation, we get 500 Server Error 

**Server:**
 - Snipe-IT 5.0.12
 - OS: Debian
 - Web Server: Apache
 - PHP 7.4.14 

**Desktop (please complete the following information):**
 - OS: Debian

**Error Messages**
500 server error, please check your server logs for more information 

**Additional context**
* Laravel Log doesnt show any messages when testing sync (also in debug mode)
* User Sync through user dashborad works
* Ldap auth not working 
* Configurations Attached 
![Screen Shot 2021-02-07 at 14 15 33](https://user-images.githubusercontent.com/35530228/107146649-3ad1e100-6952-11eb-95ef-073752aaf1d8.png)
![Screen Shot 2021-02-07 at 14 15 38](https://user-images.githubusercontent.com/35530228/107146653-3d343b00-6952-11eb-8a74-77d28541304a.png)

**Comment by mexx3001** [comment]
I have a problem with it here as well.
Test LDAP Sync gives me the same error. 
![image](https://user-images.githubusercontent.com/72917363/107191573-a49ec900-69ec-11eb-80dd-41a22685fa14.png)



Test LDAP Login works but.
![image](https://user-images.githubusercontent.com/72917363/107191587-ab2d4080-69ec-11eb-8738-3cd72247dafa.png)


If I want to synchronize the users, I get the error.
![image](https://user-images.githubusercontent.com/72917363/107191633-bb452000-69ec-11eb-95b4-d88612d7e838.png)


My installation is a WinServer 2019
snipeit version 5.1.0 build 5772

**Comment by yehiamc** [comment]
Any idea here?

**Comment by mfsid** [comment]
I'm having the same issue after I upgraded from 4.8 to 5.1.5.

Logs show this:

[2021-05-09 18:03:50] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function App\Models\ldap_control_paged_result() in C:\xampp\htdocs\snipe\app\Models\Ldap.php:270
Stack trace:
#0 C:\xampp\htdocs\snipe\app\Http\Controllers\Api\SettingsController.php(87): App\Models\Ldap::findLdapUsers()

**Comment by koenr** [comment]
Maybe related: For me the test button worked, but not the 
`php artisan snipeit:ldap-sync`

I have the same error message as mfsid

   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function App\Models\ldap_control_paged_result()

  at /var/www/html/app/Models/Ldap.php:270

As a quick and dirty hack (more dare then knowledge) I commented all the lines containing the missing function ldap_control_paged_result() in /var/www/html/app/Models/Ldap.php and that solved my problem.

**Comment by mfsid** [comment]
My issue was resolved by downgrading to PHP 7.3. 

It is noticed that PHP 7.4 is also causing issues with LDAP sync. I had issue opened #9554

**Comment by koenr** [comment]
Ah, thanks for the hint. We are running php 8.0, which is probably rather ambitious. I couldn't find anything against it though in the system requirements. No further problems found.

**Comment by rvidhy** [comment]
![image](https://user-images.githubusercontent.com/83179963/133191925-d89e8ba4-bf30-440e-9fa4-4810839caed3.png)
Same issue here

**Comment by snipe** [comment]
V5 does not support PHP 8

**Comment by snipe** [comment]
@rvidhy - what’s in your app logs?

**Comment by rvidhy** [comment]
> @rvidhy - what’s in your app logs? @snipe 

[laravel.log](https://github.com/snipe/snipe-it/files/7158979/laravel.log)

**Comment by rvidhy** [comment]
Can i downgrade the PHP

**Comment by snipe** [comment]
@rvidhy please just past the appropriately dated log lines here. I’m currently on an iPad, so downloading files is sub-optimal. If you’re using PHP8 though, you definitely should downgrade PHP for now. v6 of Snipe-IT will support PHP8, but v5 doesn’t.

**Comment by rvidhy** [comment]
@snipe I have Xaampp installed is there a way to downgrade it through xaampp or do you suggest a fresh Snipe V6 install

**Comment by rvidhy** [comment]
@snipe IS there V6 or are you mentioning V5.2

**Comment by snipe** [comment]
v6 isn't ready for prime time yet - won't be until at least the end of the month. I'm not sure how to downgrade in XAMPP, since I don't use it, but this may be helpful: https://community.bitnami.com/t/replace-php-8-with-php-7-4/90103

<blockquote><img src="https://d2hzlohlg26lpl.cloudfront.net/images/discourse-logo-sketch-small.png" width="48" align="right"><div><img src="https://d2hzlohlg26lpl.cloudfront.net/uploads/default/optimized/3X/7/1/7129e0aaafb9ed3ccafd89d89270b14f85e1ee3d_2_32x32.png" height="14"> Bitnami Community</div><div><strong><a href="https://community.bitnami.com/t/replace-php-8-with-php-7-4/90103">Replace PHP 8 with PHP 7.4</a></strong></div><div>I am setting up a local hosting environment with Nextcloud, Wordpress and a few other things and to that end I installed Xampp which always has been an excellent and simple alternative to run a LAMP in a Windows environment.  However, when trying to install Nextcloud it will not run on PHP 8, which is not a surprise, so I look in the Xampp documentation to downgrade PHP to 7.4 branch and it says I should pay attention to the Apache build being CV9 or CV11 and that is a tidbit I do not really kno...</div></blockquote>

**Comment by snipe** [comment]
You want Snipe-IT v5.2.0 and PHP 7.3 or 7.4

**Comment by rvidhy** [comment]
Thanks @snipe  will try downgrading

**Comment by johnstonisaac99** [comment]
@rvidhy were you able to find a solution for this? Having same issue

**Comment by JamieSissons** [comment]
> @rvidhy were you able to find a solution for this? Having same issue

Would also like to know the answer. I'm having issues.

**Comment by johnstonisaac99** [comment]
@JamieSissons I think I finally got mine working (newbie issue on my end). My original issue with 500 server error was from not having the proper ports open. I am using AWS EC2 and the security group was blocking LDAPS. Try this command (from [Googles LDAP troubleshooting docs](https://apps.google.com/supportwidget/articlehome?article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F9190869%3Ffl%3D1&product_context=9190869&product_name=UnuFlow&trigger_context=a)) on your machine: `openssl s_client -connect ldap.google.com:636`. If the port is open, you will receive something like: "Verify return code: 0 (ok)". If you do not receive that, please open that port for outgoing traffic. Once I got the port issue figured out, I had to set up LDAPS in Snipe-IT settings a little differently. 

Check the following boxes
- [ ] LDAP Integration
- [ ] Active Directory (enter your domain - example.com)
- [ ] LDAP SSL certificate validation


LDAP Client-Side TLS key: key from Google
LDAP Client-Side TLS Certificate: cert from Google
LDAP Server: ldaps://ldap.google.com
LDAP Bind Username: username from Google
LDAP Bind Password: password from Google
Base Bind DN: dc=example,dc=com (for example.com)
LDAP Filter: &(cn=*)
Username Field: mail
Last name: sn
LDAP First Name: givenname
LDAP Authentication query: "uid="
LDAP Version: 3
LDAP Email: mail

Hope it helps!

**Comment by JamieSissons** [comment]
> LDAP Server: ldaps://ldap.google.com

Thank you for that. There is some helpful info! I'm using onsite AD rather than Google's unfortunately, pulling my hair out as LDAP / LDAPS is working fine for all other apps we use it on!

**Comment by cyxSetyo** [comment]
check php.ini. there install php ldap or not..
can install php<version>-ldap first..

example apt install php8.1-ldap And Try again
