### ISSUE TITLE
LDAP import over multiple OUs

### ISSUE THREAD

**Issue by mexx3001** [grokability/snipe-it#9113]
I'm getting desperate, I've already searched through everything, but I'm not getting anywhere.

Can snipeit do an LDAP import over multiple OUs?
If I specify only one OU as base bind DN everything works without problems but as soon as I select the parent OU here where there are about 20 sub OUs it doesn't work anymore.
Our AD is structured like in the example:

- Domain
   -mainOu
     -People
       -OU1
       -OU2
       -OU3
       -.......

As soon as I select more than one OU, this happens during the LDAP test:
![image](https://user-images.githubusercontent.com/72917363/107321345-a1feab00-6aa2-11eb-945e-4a241cb0a34c.png)

Strangely enough the test LDAP login works
![image](https://user-images.githubusercontent.com/72917363/107321362-a7f48c00-6aa2-11eb-8015-2eca04092283.png)

Import of the users does not work either.
![image](https://user-images.githubusercontent.com/72917363/107321376-adea6d00-6aa2-11eb-8aa5-394f6ece3276.png)

The installation of snipeit was installed on a Windows Server 2019. The version used is v5.1.0 build 5772

**Comment by uberbrady** [comment]
Your best bet is probably to use our multi-OU support. You can edit several Locations, and assign to each location a separate OU.

Then the users should get associated with the appropriate Locations based on OU's.

Another option is that you can run the `php artisan snipeit:ldap-sync` command with appropriate OU's being set, but assigning them to the same location. You can use a Windows Scheduled task to periodically run that command.

**Comment by mexx3001** [comment]
How can I assign a separate OU to each site?

I have already tried the command php artisan snipeit:ldap-sync, it runs without errors but the users are still not imported. There should be far more than 2500 users, but it does not.

Is there somewhere a log file

**Comment by mexx3001** [comment]
Is there any limitations for Object Import or a timeout?

I Need this Settings immediately for our Company.

**Comment by Solverz-0** [comment]
> How can I assign a separate OU to each site?
> 
> I have already tried the command php artisan snipeit:ldap-sync, it runs without errors but the users are still not imported. There should be far more than 2500 users, but it does not.
> 
> Is there somewhere a log file

Go into the location in snipeit and at the bottom there is "LDAP Search OU". Put the OU's DN in there and any users in that OU should get the correct location

**Comment by Akash-yadav429** [comment]
Hi....@mexx
Did you get any solution on this problem

**Comment by mexx** [comment]
@Akash-yadav429 I wasn't involved in this issue.

**Comment by snipe** [comment]
@Akash-yadav429 I think you were referring to @mexx3001

**Comment by Akash-yadav429** [comment]
Hi @mexx3001 ...

**Comment by Akash-yadav429** [comment]
> 

Yes @snipe struggling with the issue of importing multiple OU's in Snipe IT

**Comment by snipe** [comment]
@Akash-yadav429 This ticket is over a year old and the OP was using a very old version of Snipe-IT. I'd suggest you open a new ticket and fill in the relevant information in the issue template.

**Comment by Akash-yadav429** [comment]
> @Akash-yadav429 This ticket is over a year old and the OP was using a very old version of Snipe-IT. I'd suggest you open a new ticket and fill in the relevant information in the issue template.

Sure i will open a new ticket, but my problem statement is same in newer version also... Not able to connect to anyone who can help...
I am using it via plugin of Jira
