### ISSUE TITLE
 Exception couldn't save customfieldset

### ISSUE THREAD

**Issue by manisha-tanwar** [grokability/snipe-it#9120]
#### Expected Behavior (or desired behavior if a feature request)

Succesful Installation 

-----

#### Actual Behavior

Getting  Exception
`couldn't save customfieldset`
errorlog[16:50:30] LOG.error: Exception: couldn't save customfieldset in /var/www/html/database/migrations/2...
errorlog[16:50:30] LOG.error: couldn't save customfieldset {"exception":{}}
-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running--> tried v5.1.1 and v4.7.4
- Version of PHP you're running
- Version of MySQL/MariaDB you're running--> mysql  Ver 14.14 Distrib 5.7.21-20, for Linux (x86_64) using  6.2
- What OS and web server you're running Snipe-IT on. --> Kubernetes
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --> docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

```
    errorlog[16:58:05] LOG.error: Exception: couldn't save customfieldset in /var/www/html/database/migrations/2...
    errorlog[16:58:05] LOG.error: couldn't save customfieldset {"exception":{}}

```
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
```

[2021-02-10 16:58:05] production.ERROR: couldn't save customfieldset {"exception":"[object] (Exception(code: 0): couldn't save customfieldset at /var/www/html/database/migrations/2015_09_22_003413_migrate_mac_address.php:20)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(359): MigrateMacAddress->up()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(366): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(177): Illuminate\\Database\\Migrations\\Migrator->runMigration(Object(MigrateMacAddress), 'up')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(146): Illuminate\\Database\\Migrations\\Migrator->runUp('/var/www/html/d...', 2, false)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(95): Illuminate\\Database\\Migrations\\Migrator->runPending(Array, Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(69): Illuminate\\Database\\Migrations\\Migrator->run(Array, Array)
#6 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()


```
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database --> No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by manisha-tanwar** [comment]
Got it resolved following https://snipe-it.readme.io/docs/docker
and help from https://gitter.im/snipe/snipe-it#

> WARNING:
> 
> Newer MySQL containers (5.7 and later, or MariaDB) may run in strict-mode by default, and the initial migrations and application setup will fail in strict mode. If you want to use one of those versions, you need to disable strict mode first!
> 

This is what I did

```
SET GLOBAL pxc_strict_mode=PERMISSIVE
Then run your snipeit stuff then reset it back
SET GLOBAL pxc_strict_mode=ENFORCING

```

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/docker">Docker</a></strong></div><div>Note very loudly that additional Docker options should be set in the env file, and they require a restart!</div></blockquote>
<blockquote><img src="https://avatars-02.gitter.im/group/iv/4/57542d2cc43b8c601977a3c7" width="48" align="right"><div><strong><a href="https://gitter.im/snipe/snipe-it#">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system built in PHP. 

- Common Issues: https://snipe-it.readme.io/docs/common-issues
- Getting Help: https://snipe-it.readme.io/docs/getting-help
- Upgrading: https://snipe-it.readme.io/docs/upgrading</div></blockquote>

**Comment by Suppo94** [comment]
Where should I put this code snippet that solved the issue for u?
