### ISSUE TITLE
404 The requested URL was not found on this server.

### ISSUE THREAD

**Issue by Ter2212** [grokability/snipe-it#9124]
[x] I have enabled debug mode 
[x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
when I try to access my snipe-it Server through my web browser the following error occurs:
Not found
The requested URL was not found on this server 

**To Reproduce**
•	I followed the installation process according to the manual until the step “Pre-Flight & Setup”
•	Edited  .env with „http://localhost“ as APP_URL
•	Exchanged default index.html in /var/www/html with the index.html of snipe-it
•	Changed the “DocumentRoot” in /etc/apache2/sites-anabled/000-default.conf to /home/<user>/snipe-it/public 
•	I changed the rights for the folders (an all there sub-folders) /home/<user>/snipe-it/public and /home/<user>/snipe-it/storage from rwxr-xr-x (755) to rwxrwxrwx (777)

**Expected behavior**
The „Pre-Flight & Setup“-page should show up

**Server**
Snipe-IT: v5.1.0
OS : Ubuntu 10
Webserver: apache2
Php version: 7.3.19.1

**Desktop**
OS: Windows 10
Browser: Firefox
Version: 78.7.1esr
**Error Messages**

•	In /var/log/apache2/error.log I found the following:

[Wed Feb 10 10:13:05.478808 2021] [mpm_prefork:notice] [pid 555] AH00171: Graceful restart requested, doing restart
[Wed Feb 10 10:13:05.530614 2021] [mpm_prefork:notice] [pid 555] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Wed Feb 10 10:13:05.530624 2021] [core:notice] [pid 555] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 10 10:13:32.243029 2021] [mpm_prefork:notice] [pid 555] AH00169: caught SIGTERM, shutting down
[Wed Feb 10 10:13:44.732925 2021] [mpm_prefork:notice] [pid 554] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Wed Feb 10 10:13:44.756066 2021] [core:notice] [pid 554] AH00094: Command line: '/usr/sbin/apache2'
•	Php -m returns the following modules:
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
imagick
json
ldap
libxml
mbstring
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by novastream** [comment]
You are using localhost as APP_URL so I guess you run Snipe-it in a development enviroment?

Have you checked so your .htaccess file is OK ?

Please check here:
https://snipe-it.readme.io/docs/linuxosx

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/linuxosx">Linux/OSX</a></strong></div><div>Setting up a web server can sound daunting for folks who don't normally do that kind of thing. This guide will help you walk through the configuration for Apache or Nginx on Linux and OSX.The most common setup for Snipe-IT on a linux server is to use Apache, so if you're not sure what to pick, Apach...</div></blockquote>

**Comment by snipe** [comment]
> Exchanged default index.html in /var/www/html with the index.html of snipe-it

I'm not exactly sure what this means....

> /home//snipe-it/public

Are there actually double-slashes in that DocumentRoot setting? And does the Snipe-IT project actually live in `/home/snipe-it`?

**Comment by Ter2212** [comment]
> 
> 
> You are using localhost as APP_URL so I guess you run Snipe-it in a development enviroment?
> 
> Have you checked so your .htaccess file is OK ?
> 
> Please check here:
> https://snipe-it.readme.io/docs/linuxosx
> 
> > <img alt="" width="48" src="/favicon.ico">Snipe-IT Documentation**[Linux/OSX](https://snipe-it.readme.io/docs/linuxosx)**Setting up a web server can sound daunting for folks who don't normally do that kind of thing. This guide will help you walk through the configuration for Apache or Nginx on Linux and OSX.The most common setup for Snipe-IT on a linux server is to use Apache, so if you're not sure what to pick, Apach...

Yes, i am running Snipe-it in a development enviroment.
I checked the .htaccess file, but i am not sure what the file should include. I read online it should not be changed manually.
I will check your link when i got time. Thank you for your help.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/linuxosx">Linux/OSX</a></strong></div><div>Setting up a web server can sound daunting for folks who don't normally do that kind of thing. This guide will help you walk through the configuration for Apache or Nginx on Linux and OSX.The most common setup for Snipe-IT on a linux server is to use Apache, so if you're not sure what to pick, Apach...</div></blockquote>

**Comment by Ter2212** [comment]
> 
> 
> > Exchanged default index.html in /var/www/html with the index.html of snipe-it
> 
> I'm not exactly sure what this means....
> 
> > /home//snipe-it/public
> 
> Are there actually double-slashes in that DocumentRoot setting? And does the Snipe-IT project actually live in `/home/snipe-it`?

After installing apache2 a index.html file is created. When accessing the website it shows up and promts you which replacing it with the index.html file of your server application, so i replaced it with the index.html of snipe-it.

"//" was a typo. The project lives in /home/snipe-it. Is there any recommended dictionary where I should install it?

**Comment by snipe** [comment]
Did you end up getting this sorted?
