### ISSUE TITLE
Groups - Account permission groups bug

### ISSUE THREAD

**Issue by mexx3001** [grokability/snipe-it#9125]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have several account permission groups.
Since we have different users, some of whom should only have read access to certain areas, I have created different groups.
The problem is that as soon as the group is no longer a member of the "Global: Super User", the user only sees 43 of the 2500 assets. The user can also no longer be found in the search. 
I do not want to give the users the Super User role. It also doesn't matter if I authorize individual areas or not. Everything that is listed under Super User works is.

**Screenshots**
With Superuser:
![image](https://user-images.githubusercontent.com/72917363/107634715-45e68300-6c6a-11eb-8c47-c1f212b2bb34.png)

without SuperUser
![image](https://user-images.githubusercontent.com/72917363/107634743-4ed75480-6c6a-11eb-9c6b-bc70c58b4eaa.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.1 build 5811
 - OS: Windows Server 2019
 - Web Server: IIS
 - PHP Version 7.4.2

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome, Chromium, Edge, Opera, Firefox

**Comment by hmacugova** [comment]
Can you try disable "full multiple companies support" options in general settings? 
![obrázok](https://user-images.githubusercontent.com/74250943/107753098-f06cad80-6d1f-11eb-8faf-8c1aed0104c6.png)

Do you have fill the company field in user profile? 
I had similarly problem but with assets - some users did not see some assets - the problem was with companies, where the assets was assigned.

**Comment by mexx3001** [comment]
Ok if I assign the user now a company then he sees at least now more, at least all assets that are also assigned to these companies.

But the user should see all assets of all companies.

If I now deactivate the Full Multiple Companies Support, what are the effects? Do the assets remain all the same?

**Comment by hmacugova** [comment]
If you deactive Full Multiple Companies Support, then every user should see every asset, no matter to which company is asset assigned. Assets settings will be not change.

**Comment by hmacugova** [comment]
When you want to select which user will see which asset, you need to set same company to user and same company to asset. It would be work.

**Comment by mexx3001** [comment]
I have now disabled the Full Multiple Companes Support. Now it works the way I want it to.
