### ISSUE TITLE
can't create api keys

### ISSUE THREAD

**Issue by SerhiiZahuba** [grokability/snipe-it#9136]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
can't create api key, when i create api key i see the error

1. Go to profile user'
2. Click on 'Manage api keys '

![image](https://user-images.githubusercontent.com/36307887/107923533-4fc5fa00-6f7a-11eb-87fc-6db881d13991.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.0
 - OS: [ CentOS]
 - Web Server: [ Apache, ]
- PHP Version 7.4.15 

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [ chrome, ]
 - Version [88]

**Additional context**
- Is this a fresh install or an upgrade? fresh
- What OS and web server you're running Snipe-IT on  - centos
- What method you used to install Snipe-IT      (install.sh, )
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database   -no

Whoops! Something went wrong!

Personal access client not found. Please create one.
RuntimeException
/var/www/html/snipeit/vendor/laravel/passport/src/ClientRepository.php
95
{ "file": "/var/www/html/snipeit/vendor/laravel/passport/src/PersonalAccessTokenFactory.php", "line": 71, "function": "personalAccessClient", "class": "Laravel\\Passport\\ClientRepository", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/passport/src/HasApiTokens.php", "line": 67, "function": "make", "class": "Laravel\\Passport\\PersonalAccessTokenFactory", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/passport/src/Http/Controllers/PersonalAccessTokenController.php", "line": 69, "function": "createToken", "class": "App\\Models\\User", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php", "line": 48, "function": "store", "class": "Laravel\\Passport\\Http\\Controllers\\PersonalAccessTokenController", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php", "line": 219, "function": "dispatch", "class": "Illuminate\\Routing\\ControllerDispatcher", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php", "line": 176, "function": "runController", "class": "Illuminate\\Routing\\Route", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 681, "function": "run", "class": "Illuminate\\Routing\\Route", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 130, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Router", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php", "line": 43, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Illuminate\\Auth\\Middleware\\Authenticate", "type": "->" }
{ "file": "/var/www/html/snipeit/app/Http/Middleware/AssetCountForSidebar.php", "line": 56, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "App\\Http\\Middleware\\AssetCountForSidebar", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php", "line": 50, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken", "type": "->" }
{ "file": "/var/www/html/snipeit/app/Http/Middleware/CheckForTwoFactor.php", "line": 36, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "App\\Http\\Middleware\\CheckForTwoFactor", "type": "->" }
{ "file": "/var/www/html/snipeit/app/Http/Middleware/CheckLocale.php", "line": 37, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "App\\Http\\Middleware\\CheckLocale", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php", "line": 78, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php", "line": 37, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php", "line": 67, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 105, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 683, "function": "then", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 658, "function": "runRouteWithinStack", "class": "Illuminate\\Routing\\Router", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 624, "function": "runRoute", "class": "Illuminate\\Routing\\Router", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 613, "function": "dispatchToRoute", "class": "Illuminate\\Routing\\Router", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 170, "function": "dispatch", "class": "Illuminate\\Routing\\Router", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 130, "function": "Illuminate\\Foundation\\Http\\{closure}", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php", "line": 67, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Barryvdh\\Debugbar\\Middleware\\InjectDebugbar", "type": "->" }
{ "file": "/var/www/html/snipeit/app/Http/Middleware/SecurityHeaders.php", "line": 26, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "App\\Http\\Middleware\\SecurityHeaders", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php", "line": 21, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest", "type": "->" }
{ "file": "/var/www/html/snipeit/app/Http/Middleware/CheckForDebug.php", "line": 25, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "App\\Http\\Middleware\\CheckForDebug", "type": "->" }
{ "file": "/var/www/html/snipeit/app/Http/Middleware/CheckForSetup.php", "line": 26, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "App\\Http\\Middleware\\CheckForSetup", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/fideloper/proxy/src/TrustProxies.php", "line": 57, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Fideloper\\Proxy\\TrustProxies", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php", "line": 49, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php", "line": 56, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Illuminate\\Session\\Middleware\\StartSession", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php", "line": 63, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode", "type": "->" }
{ "file": "/var/www/html/snipeit/app/Http/Middleware/NoSessionStore.php", "line": 27, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "App\\Http\\Middleware\\NoSessionStore", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/barryvdh/laravel-cors/src/HandlePreflight.php", "line": 29, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 171, "function": "handle", "class": "Barryvdh\\Cors\\HandlePreflight", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 105, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 145, "function": "then", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }
{ "file": "/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 110, "function": "sendRequestThroughRouter", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }
{ "file": "/var/www/html/snipeit/public/index.php", "line": 58, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }

**Comment by Park0** [comment]
Did u try: `php artisan passport:install` (if yes could u please share the output)?

**Comment by SerhiiZahuba** [comment]
![image](https://user-images.githubusercontent.com/36307887/108065873-45cdf500-7067-11eb-9a79-d0446a5a0986.png)

**Comment by Park0** [comment]
I have a similar issue on a manual install i did a few day's ago, I used the install yesterday on a clean ubuntu 20.04 and it worked correctly.
My best guess would be a migration error but ill need to compare both installs to be sure.

**Comment by snipe** [comment]
Pull from latest and run migrations.
