### ISSUE TITLE
Asset tags without zerofill when creating multiple assets at once

### ISSUE THREAD

**Issue by leifbraeg** [grokability/snipe-it#9144]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When creating multiple assets at once (one of the newer features) not all asset tags are created correctly. Only the first asset includes zerofill, the rest does not.

**To Reproduce**
1. Make sure zerofill is enabled
2. Create new asset
3. Add more assets via plus button
4. See the oddly numbered asset tags

**Expected behavior**
Additional asset tags should be zerofilled

**Screenshots**
![Screenshot 2021-02-16 at 16 31 48](https://user-images.githubusercontent.com/58110221/108084448-7a947900-7074-11eb-8074-24feec535091.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.12 - build 5705 (master) 
 - PHP Version: 7.3.17
 - Laravel Version: 6.18.10

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 88.0.4324.150

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.4
 - Browser: Safari

**Error Messages**
This is how it looks in the demo - no idea what's going on here.
![Screenshot 2021-02-16 at 16 36 19](https://user-images.githubusercontent.com/58110221/108084955-1b833400-7075-11eb-8695-416517227091.png)
Seems like having numbers in the prefix makes it even worse (the prefix here was "21T-")

**Additional context**
It's a hosted SnipeIT instance, been running for a while (~2 years)

**Comment by ThoBur** [comment]
This issue should be fixed since v5.1
#8876
