### ISSUE TITLE
Can't checkout to users

### ISSUE THREAD

**Issue by dhkivan** [grokability/snipe-it#9150]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgraded to v5.1.1, can't find any users, assets, locations for checkout

**To Reproduce**
1. Go to 'Assets'
2. Click on 'checkout'

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version : 5.1.1
 - OS: [Windows]
 - Web Server: [IIS]
 - PHP Version : 7.4.13

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Error Messages**
[2021-02-17 01:00:02] production.ERROR: Illuminate\Routing\Exceptions\UrlGenerationException: Missing required parameters for [Route: hardware.show] [URI: hardware/{hardware}]. in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Exceptions\UrlGenerationException.php:17#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send()
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Notifications\ChannelManager->send()
#20 C:\inetpub\wwwroot\snipe-it\app\Console\Commands\SendExpectedCheckinAlerts.php(62): Illuminate\Support\Facades\Facade::__callStatic()
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\SendExpectedCheckinAlerts->handle()
#22 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#24 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call()
#26 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call()
#27 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#28 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#29 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run()
#30 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#31 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun()
#32 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run()
#33 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run()
#34 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#35 {main}

Next Illuminate\View\ViewException: Missing required parameters for [Route: hardware.show] [URI: hardware/{hardware}]. (View: C:\inetpub\wwwroot\snipe-it\resources\views\notifications\markdown\report-expected-checkins.blade.php) in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Exceptions\UrlGenerationException.php:17
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(45): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\CompilerEngine->get()
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Mail\Markdown.php(64): Illuminate\View\View->render()
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(101): Illuminate\Mail\Markdown->render()
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(63): Illuminate\Notifications\Channels\MailChannel->buildView()
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(148): Illuminate\Notifications\Channels\MailChannel->send()
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale()
#12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow()
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send()
#14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Notifications\ChannelManager->send()
#15 C:\inetpub\wwwroot\snipe-it\app\Console\Commands\SendExpectedCheckinAlerts.php(62): Illuminate\Support\Facades\Facade::__callStatic()
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\SendExpectedCheckinAlerts->handle()
#17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#20 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call()
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call()
#22 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#24 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run()
#25 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#26 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun()
#27 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run()
#28 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run()
#29 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle()

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by dhkivan** [comment]
I found the issue not only happened on checkout, all drop down list is not function, can't lookup the values.

![image](https://user-images.githubusercontent.com/46602090/108183664-489f1780-7145-11eb-9819-61f2c2faaf52.png)

**Comment by albinbatman** [comment]
Can you share the following:

Additional context

- Is this a fresh install or an upgrade?
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

and can you:

- take a screenshot or text dump of the developer console of your web browser

**Comment by snipe** [comment]
This is already fixed on master
