### ISSUE TITLE
Internal Server error 500 on checkout of asset - Issue present on Demo and personal build

### ISSUE THREAD

**Issue by alexleturgeon** [grokability/snipe-it#9158]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When checking out an Asset I receive an internal server error 500. The asset is checked out but no emails are sent out to the user (If they are set to be sent at check out).

This seems to happen regardless of what the asset is.

This is on version V5.1.1 (Build: 5811)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Assets
2. Click on An Asset and check it out to a user.
3. See error

**Expected behaviour**
The Asset should be checked out and an error page should not be displayed, emails should be sent out to the user if configured to do so.

**Screenshots**
![image](https://user-images.githubusercontent.com/79265396/108368746-b5bcb680-71f2-11eb-90cb-bf025a4cc193.png)
![image](https://user-images.githubusercontent.com/79265396/108368785-c0774b80-71f2-11eb-824c-ffccf7179c3c.png)

**Server (please complete the following information):**
 - Snipe-IT Version : v5.1.1 build 5811 ()
 - OS: CenTOS
 - Web Server: Apache
 - PHP Version: 7.2.7

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge, IE, & Firefox

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
This was an upgrade using GIT to install

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Mariu7** [comment]
I got same problem. Debugging error.

`SQLSTATE[HY093]: Invalid parameter number (SQL: select * from `users` where `users`.`id` in (2, , 1, ?, ?, 2021-02-18 19:05:51, admin, admin, 2021-01-25 11:38:14, 2021-02-18 19:05:51, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, admin, ?, ?, 0, ?, 1, ?, 0, 0, ?, ?, ?, ?, ?, ?) and `users`.`deleted_at` is null)
`

**Comment by snipe** [comment]
@Mariu7 that's a SQL dump, not a stack trace. We need a stack trace.

**Comment by snipe** [comment]
Interesting. On the demo, it throws the 500 but still actually does check it out.

**Comment by Mariu7** [comment]
It does check out for me too

**Comment by snipe** [comment]
This is now fixed on master
