### ISSUE TITLE
Error 500 on viewing asset

### ISSUE THREAD

**Issue by Mynty100** [grokability/snipe-it#9159]
I have run all the things lol....
Go a new one for you. 
Seems we have some errors with some assets where in the `assets` table the `assigned_to` is set to 0 and not NULL
I feel the is a sql line to could run that could fix this, just not well enough versed in it to know.

Something that will find in the assigned column value 0 and change it to NULL.
Any wizardry help would be very grateful.

Thank you in advance.
![image](https://user-images.githubusercontent.com/34461276/108437477-2ae2c700-7299-11eb-8059-db64d718b128.png)

**Comment by snipe** [comment]
`update assets set assigned_to=NULL where assigned_to=0;`

**Comment by Mynty100** [comment]
You are a god send <3 
Thank you very much.
