### ISSUE TITLE
formDataListSafe s not defined

### ISSUE THREAD

**Issue by Messinger** [grokability/snipe-it#9160]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode (but it is not related to this bug)
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to use any overlay box like update a predefined script the selection box for models is empty and on browser console I see this error on first opening the modal dialog:

```
all.js?id=8443e32cebc5ad69befd:10 Uncaught ReferenceError: formatDatalistSafe is not defined
    at HTMLSelectElement.<anonymous> (all.js?id=8443e32cebc5ad69befd:10)
    at Function.each (all.js?id=8443e32cebc5ad69befd:1)
    at vt.fn.init.each (all.js?id=8443e32cebc5ad69befd:1)
    at HTMLDivElement.<anonymous> (all.js?id=8443e32cebc5ad69befd:10)
    at HTMLDivElement.<anonymous> (all.js?id=8443e32cebc5ad69befd:3)
    at Function.each (all.js?id=8443e32cebc5ad69befd:1)
    at vt.fn.init.each (all.js?id=8443e32cebc5ad69befd:1)
    at Object.<anonymous> (all.js?id=8443e32cebc5ad69befd:3)
    at u (all.js?id=8443e32cebc5ad69befd:2)
    at Object.fireWith [as resolveWith] (all.js?id=8443e32cebc5ad69befd:2)
```

**To Reproduce**
1. Create a predefined kit
2. Open browsers script console
3. Edit kit, click on "Append"
4. Model list is empty
5. In console you see the error above models list is empty.

**Expected behavior**
No error in console and models listet

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: All (chrome, firefox, safari, opera)
 - Version: all

Not tested with smartphone

**Error Messages**
Not PHP related so no error messages in debug console

**Additional context**
Fresh install in docker container, no manual edit of database, just installed, running on linux box.

No other errors after install (nice job btw.)

This happens in various dialogs (not all)

**Comment by Messinger** [comment]
<img width="1037" alt="Screenshot 2021-02-19 at 09 02 13" src="https://user-images.githubusercontent.com/1209876/108476547-73e34d00-7292-11eb-80a4-85d14971bbd4.png">

**Comment by snipe** [comment]
This is fixed by https://github.com/snipe/snipe-it/pull/9143 which is awaiting review
