### ISSUE TITLE
Cannot Create new model from Create Asset page

### ISSUE THREAD

**Issue by EGTITS** [grokability/snipe-it#9161]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When we create a new asset and we want to create New model from the button New all scrol down menus are empty.
We still can create new model from Settings -> Assets models -> Create New
This bug is reproduced on our production and development environment both with the latest v5.1.1 - build 5811 (master)
The bug can be reproduced on the official demo page.

**To Reproduce**
1. Go to 'Create Asset'
2. Click on 'button NEW for Model.'
3. On all fields are empty

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.1
 - OS: [Debian and website demo]
 - Web Server: [apache]
 - PHP Version 7.3

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [chrome, firefox]
 - Version []

**Comment by snipe** [comment]
This is fixed by https://github.com/snipe/snipe-it/pull/9143, which is awaiting review
