### ISSUE TITLE
Need to change the QR generator result from IP to Domain Name.

### ISSUE THREAD

**Issue by Raffudeen** [grokability/snipe-it#9172]
We have hosted the snipe it application on to a domain and we are using the application that domain name but when i try to generate a QR code for the asset tags it takes me to the IP address instead of domain so , Kindly please advice us how do i change the QR generator result from IP address to Domain name.

Thank you..

**Comment by uberbrady** [comment]
`APP_URL` in your `.env`? E.g. it should have a full URL, including protocol (http:// or https://) and your new domain name in it. You may need to clear the Bar code cache after you change it (Settings, bar codes, "Delete barcode cache"), and if you've cached your config you may need to do a `php artisan config:clear`

**Comment by Raffudeen** [comment]
HI ,

thank you for the reply. tried how you said but it is not working. Again when i scan the code it takes me to IP address.
