### ISSUE TITLE
Adding userless People

### ISSUE THREAD

**Issue by Lombra** [grokability/snipe-it#9174]
**Server (please complete the following information):**
 - Snipe-IT Version 5.1.2
 - OS: [e.g. Ubuntu, CentOS] Unknown (Docker)
 - Web Server: [e.g. Apache, IIS] Unknown (Docker)
 - PHP Version Unknown (Docker)

**Is your feature request related to a problem? Please describe.**
Being required to create credentials when adding People who won't be needing the ability to log in.

**Describe the solution you'd like**
I would like to be able to be able to add People by providing a first and last name, and nothing else.

**Describe alternatives you've considered**
No real alternatives exist. I found the old issue #165, which seemed to desire the same thing, but as far as I can tell, all it did was removing the email requirement.

**Additional context**
There is a perfectly fine "This user can login" option on the creation page, which I kinda would expect do exactly this. Otherwise what would their username and password be used for?

**Comment by gilesytheking** [comment]
This has always puzzled me, but has never really been an issue. Logically the "This user can login" should be towards the top of the page, if that option is ticked then a username and password would be required. I'm quite sure however that the username field is required in order to assign assets etc to a user.

**Comment by snipe** [comment]
The username and password are required at a model level, and that's unlikely to change any time soon. We do provide the ability to generate a long password to make that process easier.

**Comment by mahelmy** [comment]
Hi 
i need to create users for just checkout and checkin process and no need for them to login 
can i do that ?
also is there option to modify or add field in users creation like (course or class)
