### ISSUE TITLE
Change language  after install

### ISSUE THREAD

**Issue by hieult7** [grokability/snipe-it#9184]
When i install Snipe IT done. Language default: en (US)
I want to change another language. How can i do?
Help me
Thank you

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/localization

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/localization">Localization</a></strong></div><div>Set the language and time/date display of your Snipe-IT installation</div></blockquote>
