### ISSUE TITLE
Docker logs are not sent to stdout for Laravel

### ISSUE THREAD

**Issue by tkrause** [grokability/snipe-it#9198]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A common convention for Docker is to forward logs to stdout which end up directly in the log for the Docker container. This makes debugging easier so you don't have to log into the container to find them since they're all right there in one place.

In addition, when deploying to Kubernetes or a similar container orchestration service stdout logs show up in most admin panels.

**To Reproduce**
1. Run SnipeIT from a docker container
2. Trigger a 500 or similar error
3. Check the docker logs
4. No log is present
5. Log into the container, check storage/log/laravel.log
6. Log is present

**Expected behavior**
Logs from storage/log/laravel.log should be forwarded to stdout.

This can be done by dropping the following config into `config/logging.php`

```
'stdout' => [ 
     'driver' => 'monolog',
     'handler' => StreamHandler::class,
     'with' => [ 'stream' => 'php://stdout', ], 
],
```

Then setting the `LOG_DRIVER` variable to 'stdout'

I can make a pull request if needed if it helps get this merged.

**Comment by snipe** [comment]
If you're triggering a 500, wouldn't `stderr` make more sense?

**Comment by tkrause** [comment]
For errors, yes `stderr` would make more sense.

However, there's a few things preventing that from being used:

First, not all logs that make it to laravel.log will be errors. For example, Log::info would not be error level. Now this may not be used in Snipe. 

Second, in the official Snipe image `stderr` does not make it to the Docker log either which it is supposed to. We've tested this and this config in our Kubernetes environment and it only works by sending it to `stdout`. We're currently using a config map to replace the `logging.php` file entirely.

I just thought I would mention it if you want to fix it upstream as I'm sure more people will run into this issue.

**Comment by snipe** [comment]
Roger. This is currently on master now.

**Comment by Elvisjohn37** [comment]
> driver

how to set LOG_DRIVER
