### ISSUE TITLE
Pre versions pushing to Master branch

### ISSUE THREAD

**Issue by bra1ncramp** [grokability/snipe-it#9205]
#### Please confirm you have done the following before posting your bug report:

- [N/A] I have enabled debug mode 
- [ YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
"Pre" versions of Snipe-IT are being pushed to Master branch

**To Reproduce**
1. run  php upgrade.php
2. Version installed is v5.X.X-pre

Also, looking at https://github.com/snipe/snipe-it/blob/master/config/version.php, notice that the pre version is there, and that it says branch is developer - even though it is in Master branch.

**Expected behavior**
running php upgrade.php installs the latest stable

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: RHEL
 - Web Server: Apache
 - PHP Version 7.4

**Comment by snipe** [comment]
That's expected behavior at this point. It's still stable, and we need to differentiate between what's the tagged release and people who pull from master, since those things are not always the same.
