### ISSUE TITLE
Upgrading.php puts me on the develop branch instead of the master

### ISSUE THREAD

**Issue by G13312** [grokability/snipe-it#9206]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When updating my version of Snipe-it using php upgrade.php it updates me to the v5.1.2-pre - build 5831 (develop) instead of 5.1.1

**Expected behavior**
It should update me to the latest version available here : https://github.com/snipe/snipe-it/releases

**Screenshots**

![image](https://user-images.githubusercontent.com/61593857/109189210-c5437e80-7761-11eb-9ef4-98448d7bc6b5.png)
![image](https://user-images.githubusercontent.com/61593857/109189652-41d65d00-7762-11eb-9d25-266f827a8a18.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version : v5.1.2-pre - build 5831 (develop)
 - OS: [Windows 10]
 - Web Server: [IIS]
 - PHP Version : 7.4.2

**Additional context**
- Include what you've done so far in the installation, and if you got any error messages along the way.
- I tried doing `php upgrade.php`
- I also tried 
`composer install --no-dev --prefer-source`
 `composer dump-autoload`
 `php artisan migrate`
 `php artisan config:clear`
 `php artisan config:cache`

Any help would be appreciated!

Thank you!

**Comment by snipe** [comment]
You're on master, not develop. We have the version set at a "pre" release because we're about to release but we need to differentiate between folks who pull only tagged releases and those who pull from master.
