### ISSUE TITLE
Feature Request - List specs of Assets

### ISSUE THREAD

**Issue by jaykenobi17** [grokability/snipe-it#9208]
**Server (please complete the following information):**
 - Snipe-IT Version  5.0.6
 - OS: [e.g. Ubuntu, CentOS] Docker
 - Web Server: [e.g. Apache, IIS] Docker
 - PHP Version  Docker

**Is your feature request related to a problem? Please describe.**
New Feature

**Describe the solution you'd like**
Having an option to list certain specs of a PC or asset that can give more details of what is in the asset(i.e.Memory, Storage, CPU, Display Port, HDMI, etc.)

**Describe alternatives you've considered**
Adding them to the notes but can get pretty cluttered

**Comment by snipe** [comment]
You would use custom fields for that. https://snipe-it.readme.io/docs/custom-fields

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/custom-fields">Custom Fields</a></strong></div><div>Custom fields and fieldsets are available in Snipe-IT versions 2.1.0-pre and later. Custom fields allow you to track additional information about your assets that the default asset attributes don't cover. Check out the short video tutorial below for a full walkthrough:Think of custom fieldsets as co...</div></blockquote>
