### ISSUE TITLE
Dashboard has no graphics

### ISSUE THREAD

**Issue by mwfelker** [grokability/snipe-it#9215]
#### Expected Behavior (or desired behavior if a feature request)

Expected the dashboard to look like the demo dashboard

-----

#### Actual Behavior

All the links/titles run down the left side of the browser

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running: 5.1.2
- Version of PHP you're running:7.3.27-1~deb10u1
- Version of MySQL/MariaDB you're running: 10.3.27-MariaDB-0+deb10u1 Debian 10
- What OS and web server you're running Snipe-IT on: Apache/2.4.38 (Debian)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc):manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Dashboard
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.: The only one deals with sending emails.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. No, it is not
- Include any additional information you can find in `storage/logs` and your webserver's logs. Only issue relates to sending emails.
- Include what you've done so far in the installation, and if you got any error messages along the way. I have completed the installation and have received error messages along the way, but too many to remember.  I have resolved all errors during installation.
- Indicate whether or not you've manually edited any data directly in the database: I have no data in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help
![issue](https://user-images.githubusercontent.com/39380394/109339233-f50b8880-782c-11eb-81bc-6a1101dd4865.jpg)

**Comment by cwaninger** [comment]
Hi @mwfelker ,
this stronlgy looks like no scripts nor styles are being loaded. 

1. Could you enable **Developer Tools** - depending on Browser and confitguration with pressing F12 (in Chrome and Firefox).
2. In the Tabs you can see go to **Network**. 
3. Then Open your SnipeIT installation in your browser
4. Press F5 to refresh, or even better ctrl + shift + R to reload everything without cache. 
5. Then send us a screenshot of what you see - Including the Name and Status, 

This way we can see what is received from the Server. I actually think its due to some scriptblocking of your browser or some permission issue on the server.

Regards
Christoph

**Comment by mwfelker** [comment]
Thank you very much for getting back to me.

I have included screenshots as requested.  I wasn't quite sure what you
meant by name and status.

I have tested this with Internet Explorer, Edge, Chrome, Firefox, Vivaldi,
and I always get the same issue.

![listing](https://user-images.githubusercontent.com/39380394/109667387-b2e88c80-7b35-11eb-8aec-03f66b9bde32.JPG)
![listing02](https://user-images.githubusercontent.com/39380394/109667413-b8de6d80-7b35-11eb-97c7-470319020939.JPG)

**Comment by cwaninger** [comment]
Hi mwfelker - sorry for replying so late.

404 means not found (https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5). 

You said that you tried the manual way of installing. Did you miss any step? Can you verify that you installed all dependencies correctly? Also Check in your installation path on your server, if the required files are available. You can check The corresponding path when hovering over the File in the Developer Tools like this: 
![image](https://user-images.githubusercontent.com/32128971/110775253-027a3700-825f-11eb-8a67-ae477abd6024.png)

Verify that files are available and have corresponding permissions set. 

Best regards,
Christoph


<blockquote><div><strong><a href="https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5">HTTP/1.1: Status Code Definitions</a></strong></div></blockquote>

**Comment by snipe** [comment]
What’s the URL you access your Snipe-IT install through and what do you have as your APP_URL in your .env?

**Comment by mwfelker** [comment]
I gave up on this issue and installed a completely different way, that I finally was able to get to work.
