### ISSUE TITLE
Incorrect language switching

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#9219]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Incorrect language switching

**To Reproduce**
I switched the language of my profile from Russian to English, but in some places the Russian language remained. For example, in the dashboard and in the Activity Report. The language has not changed in the "Action" column. Switching the language in global settings didn't help either.

**Expected behavior**
Initially, the system is in English. It usually happens that some things are not translated into other languages, but that the additional language in the menu does not return to the default language after switching, this is the first time I see this.

**Screenshots**
![1](https://user-images.githubusercontent.com/48224568/109344947-78a29500-7880-11eb-8eb2-5833546c5683.jpg)

**Comment by snipe** [comment]
We are running that phrase through the translator methods, so my guess would be that those strings haven't been translated yet.

```php
public function actionType() {
        return mb_strtolower(trans('general.'.str_replace(' ', '_', $this->action_type)));
}
```

**Comment by snipe** [comment]
Also, please specify the version of Snipe-IT you're using with your GH issues moving forward. It makes it very difficult to figure out what might be happening if we don't have that info. That's why we have issue templates.

**Comment by UserGoodtm** [comment]
My apologies
Snipe-IT version
v5.1.2 build 5847 (g00a7c1e9e)
Software License
AGPL3
PHP Version
7.3.22
Laravel Version
6.20.16

**Comment by snipe** [comment]
@bzeus - when you're back, can you try to reproduce this please?
