### ISSUE TITLE
Viewing the history of an asset through a user profile (less than when viewing the history through an asset)

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#9222]
**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.2 build 5847 (g00a7c1e9e) 
 - OS: CentOS
 - Web Server: Apache
 - PHP Version: 7.3.22

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
If you open the user profile, open the history, we can see the history of assigning equipment to the user. But there is less information in this history (fewer columns in the table) than in the history, if you look at it (history) through the asset. It would be useful to have the same columns in the table when viewing the history, both through the user and through the asset.

**Additional context**
![2](https://user-images.githubusercontent.com/48224568/109350866-506b6400-7889-11eb-8d8e-423c09b89c7b.jpg)

![3](https://user-images.githubusercontent.com/48224568/109350873-53feeb00-7889-11eb-9f00-091e310f47ad.jpg)

**Comment by snipe** [comment]
They have different contexts, so using the same fields wouldn't make sense.
