### ISSUE TITLE
List of models truncating at 20 and does not paginate

### ISSUE THREAD

**Issue by rickheil** [grokability/snipe-it#9225]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When we load the models page, only 20 models display. We have over 200 models in the database that are active.

**To Reproduce**
1. Go to the Asset Models page (/models)
2. Observe that only 20 models display, observe no pagination available, observe that items-per-page limited to either 10 or 20
3. Compare to the contents of models table in the database and notice discrepancy in qty of models

**Expected behavior**
20 models would display, but pagination would be available and the number of items per page would allow larger selections as normal. 

**Server (please complete the following information):**
 - Snipe-IT Version - replicated on both 5.1.2 and 5.1.1
 - OS: Ubuntu
 - Web Server: Apache 
 - PHP Version: PHP 7.4.15

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 latest
 - Browser: Chrome
 - Version: 88.0.4324.192

**Error Messages**
- With debug turned on, no errors or exceptions are noted

**Additional context**
- Is this a fresh install or an upgrade? Upgrade (noticed a few weeks after 5.1.1)

**Comment by kseymour01** [comment]
We're seeing similar problems on our Asset Model page.  Currently running v5.1.2-pre - build 5831. There are no page controls at the top or bottom of the asset model list.  if you use the rows per page control to select a different amount we briefly see the page control during the refresh but it disappears once the page fully refreshes.  Also the option for 'rows per page' list changes and removes some of the options that were there before.
![image](https://user-images.githubusercontent.com/79345314/109514863-14442900-7a6c-11eb-9ed6-ff997697b4e4.png)

![image](https://user-images.githubusercontent.com/79345314/109514903-1d34fa80-7a6c-11eb-8759-34010f5dc838.png)

**Comment by snipe** [comment]
this has already been fixed on  master and in 5.1.2

**Comment by rickheil** [comment]
Thanks!
