### ISSUE TITLE
Wrong Date !!

### ISSUE THREAD

**Issue by thinhku1012** [grokability/snipe-it#9226]
Hello Everyone !
I just installed success full Snipe-IT on Windows Server. But when I use it, I see run times faster 25 days. I'm try set "APP_TIMEZONE='UTC+7' " in file ".env" but not available.
Please, give me recommend. Thank you very much

**Comment by androbourne** [comment]
What do you mean .env is "not available"?

**Comment by thinhku1012** [comment]
File '.env' in path 'C:\inetpub\wwwroot\snipe-it\.env' at row
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=###################=
APP_URL=192.168.0.2
APP_TIMEZONE='UTC+7'  
APP_LOCALE=vi
MAX_RESULTS=500
# --------------------------------------------

But the date is not running properly and the time is correct

**Comment by snipe** [comment]
Please make sure all of your .env values are enclosed in quotes (and you should change your app key now, since that should never be shared publicly)

**Comment by snipe** [comment]
(Also, per the documentation, your APP_URL should include the protocol, not just the domain/IP)

**Comment by thinhku1012** [comment]
I following link below, I'm not sure where was wrong
https://blog.teknex.com.au/snipe-it/snipe-it-installation-on-windows-server/

![2021-03-02_13-51-57](https://user-images.githubusercontent.com/32346859/109610028-ca883b00-7b5e-11eb-88ea-c8da0f51c5a8.png)


<blockquote><img src="https://blog.teknex.com.au/wp-content/uploads/2019/08/SnipeOnWindowsFeaturedImage.jpg" width="48" align="right"><div>Teknex</div><div><strong><a href="https://blog.teknex.com.au/snipe-it/snipe-it-installation-on-windows-server/">SNIPE-IT Installation On Windows Server</a></strong></div><div>In this detailed tutorial, we will go through all the required steps needed to be performed in order to successfully install Snipe-IT on Windows Server 2019. This blog is updated on 10 Jul 2020. Make sure you install Visual C++ 2017 Redistributable if you are planning to use PHP Version 7.4.6 or higher This post [&hellip;]</div></blockquote>

**Comment by androbourne** [comment]
So I was troubleshooting an email issue I was having and ran a command that stated my UTC-6 wasn't valid.. (my email issue can be found here if you are interested https://github.com/snipe/snipe-it/issues/9194)

But during that troubleshooting, I found out that UTC-X is not a valid format for Snipe-IT. (it can use UTC but not UTC-#) It uses PHP accepted formats only. Find your timezone on this list. https://www.php.net/manual/en/timezones.php Update the .env file with proper timezone and run php artisan config:clear command to clear the config to start using the new time zone.
Reference: https://github.com/snipe/snipe-it/issues/5474
![image](https://user-images.githubusercontent.com/30128203/109729337-b73c9600-7b85-11eb-84dd-226a3f21c45e.png)


My env. file looks like so.
![image](https://user-images.githubusercontent.com/30128203/109726990-9a05c880-7b81-11eb-99a2-a1de0133f99f.png)



<blockquote><img src="https://www.php.net/favicon.ico" width="48" align="right"><div><strong><a href="https://www.php.net/manual/en/timezones.america.php">PHP: America - Manual</a></strong></div></blockquote>

**Comment by snipe** [comment]
FWIW, that one isn’t up to us. We use PHP’s date standards (as does Laravel), which we mention in our documentation. Thanks for the update tho. We appreciate it.

**Comment by sekroots** [comment]
Hello.

I am facing this issue. I am using snipeit docker from: https://github.com/comoser/snipe-it-docker-compose

But I cant open it, I got :

root@2550a21cb778:/var/www/html# php artisan config:clear
PHP Notice:  date_default_timezone_set(): Timezone ID 'Europe/London  # you should change this to your timezone' is invalid in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 49
Configuration cache cleared!
root@2550a21cb778:/var/www/html#


root@2550a21cb778:/var/www/html# php artisan migrate
PHP Notice:  date_default_timezone_set(): Timezone ID 'Europe/London  # you should change this to your timezone' is invalid in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 49
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migrating: 2016_03_10_133849_add_locale_to_users

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'locale' (SQL: alter table `users` add `locale` varchar(5) null default 'en # you should change this for the desired language')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

      +9 vendor frames
  10  database/migrations/2016_03_10_133849_add_locale_to_users.php:17
      Illuminate\Support\Facades\Facade::__callStatic()

      +22 vendor frames
  33  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
root@2550a21cb778:/var/www/html#



<blockquote><img src="https://opengraph.githubassets.com/160030217fe530a10fa425a16aeb4e3c57dee12f3bd0154a33924597999381c5/comoser/snipe-it-docker-compose" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/comoser/snipe-it-docker-compose">GitHub - comoser/snipe-it-docker-compose: Dcoker compose ready to deploy a snipe-it instance with MySQL database</a></strong></div><div>Dcoker compose ready to deploy a snipe-it instance with MySQL database - GitHub - comoser/snipe-it-docker-compose: Dcoker compose ready to deploy a snipe-it instance with MySQL database</div></blockquote>

**Comment by Msopheak168** [comment]
I also wrong on Date/Time 
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:XXXXXXXXXXXXXXXXXXX
APP_URL=http://171.16.24.11
APP_TIMEZONE='Asia/Phnom_Penh'
APP_LOCALE=en
MAX_RESULTS=500
![image](https://github.com/snipe/snipe-it/assets/66686689/e16fcb68-9927-44a8-94bd-768681d0ebdf)

**Comment by Zrki85** [comment]
This error still present.
https://ibb.co/3CkP5v6


<blockquote><img src="https://i.ibb.co/CHWSp6C/Problem-with-date.jpg" width="48" align="right"><div><img src="//simgbb.com/images/favicon.png" height="14"> ImgBB</div><div><strong><a href="https://ibb.co/3CkP5v6">Problem-with-date hosted at ImgBB</a></strong></div><div>Image Problem-with-date hosted in ImgBB</div></blockquote>
