### ISSUE TITLE
Redirected to Licenses Page

### ISSUE THREAD

**Issue by quadeye16** [grokability/snipe-it#9227]
When I click any of this three buttons in asset model page it will redirect me to licenses page.
![lic](https://user-images.githubusercontent.com/79834224/109471685-1332ec00-7aac-11eb-85ee-bfaa27782e05.png)
or it supposedly redirects me to that page?...

**Comment by hertzzz** [comment]
Hi, just encountered this today when I upgraded my Snipe-IT to the latest version Version v5.1.2 - build 5847 (master). How to fix this problem? please help. Thanks.

**Comment by boyosof** [comment]
same with me after upgrade to  **Version v5.1.2 - build 5847 (master)**

**Comment by jtoews-boos** [comment]
I'm also having this problem. If you manually put in the url  /models/"assetnumber"/"edit" it works, so it's something in the edit link, but manually changing the URL is a workaround until there is a release fix.

**Comment by boyosof** [comment]
> I'm also having this problem. If you manually put in the url /models/"assetnumber"/"edit" it works, so it's something in the edit link, but manually changing the URL is a workaround until there is a release fix.

another workaround, click on the name of the model then from the dropdown menu in top left select Edit.

**Comment by inietov** [comment]
Its fixed in develop and going to be in an upcoming version. 😀
