### ISSUE TITLE
Asset model edit link incorrect

### ISSUE THREAD

**Issue by goatsociety** [grokability/snipe-it#9239]
#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The edit button link for an asset model incorrectly includes a URL to edit a license instead. E.g.: clicking a link might attempt to load /licenses/28/edit instead of /models/28/edit. If you open the asset model by clicking its title, the edit menu at the top right works as expected.

**To Reproduce**
1. Go to Settings->Asset Models
2. Mouse over or click the edit button for any model
3. Observe the URL includes '/license/XX/edit' instead of '/model/XX/edit'
4. Clicking the link gives an error "License does not exist""

**Expected behavior**
Clicking the edit button on an asset model opens the model edit page

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.2 - build 5847 (master)
 - OS: Debian
 - Web Server: Apache
 - PHP Version: 7.3

**Desktop (please complete the following information):**
 - OS: Windows 19
 - Browser: Firefox and Chrome
 - Version Firefox 81 / Chrome 88

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Same issue on the demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade?  Recent install, ran upgrade today
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT Manual
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
This has already been fixed on develop
