### ISSUE TITLE
I can't delete the asset model

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#9240]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I try to delete the asset model, but in response I get a message that the license was not found. The asset model, and was not deleted

**Screenshots**
![1](https://user-images.githubusercontent.com/48224568/109812969-c67f1a80-7c3d-11eb-9e08-40d8e102cbac.jpg)
![2](https://user-images.githubusercontent.com/48224568/109812975-c97a0b00-7c3d-11eb-99a4-83effbbca405.jpg)
![3](https://user-images.githubusercontent.com/48224568/109812984-cb43ce80-7c3d-11eb-83ae-ba1f9488d79b.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.2 build 5847 (g00a7c1e9e)
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.3.22

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] all
 - Version [e.g. 22] last

**Additional context**
- Is this a fresh install or an upgrade? upgrade

I think this error is related to earlier problems when the id numbers match

**Comment by inietov** [comment]
This is fixed via this commit 9ed226a0afdb16f85e38e2021c85dbd92a621b22.
