### ISSUE TITLE
Unable to obtain Expiry emails!

### ISSUE THREAD

**Issue by androbourne** [grokability/snipe-it#9243]
Why was my previous support ticket closed? I still have the issue and received no comments back from anyone about the resolution of the issue...

https://github.com/snipe/snipe-it/issues/9194

**Comment by androbourne** [comment]
Nevermind. I'll close this ticket for you since it appears you are unable to assist. I've moved onto bigger and better pastures anyways.

**Comment by snipe** [comment]
Dude, you gave it a total of 16 days since your original post. Try being a little patient next time. 

You were running an old version of Snipe-IT (5.0.10). The expiration email issue had [been fixed in v5.0.11, back in November](https://github.com/snipe/snipe-it/commit/bfc60864ddd60a03b2bc9da9ee1ca9a2da184256), that's why your previous issue had been closed.

**Comment by androbourne** [comment]
> Dude, you gave it a total of 16 days since your original post. Try being a little patient next time.
> 
> You were running an old version of Snipe-IT (5.0.10). The expiration email issue had [been fixed in v5.0.11, back in November](https://github.com/snipe/snipe-it/commit/bfc60864ddd60a03b2bc9da9ee1ca9a2da184256), that's why your previous issue had been closed.

Dude. I created a ticket and added notes in there including additional troubleshooting with screenshots. Waited 10 days and your response was to just close the ticket with zero notes or suggestions of where to look to resolve the issue at. Clearly if I saw it was patched I would have just upgraded. I'm running 1 version behind, not 5. A simple link to the email fix that was done in Nov just like you did here would have been good enough but you didn't even do that.

I don't mind waiting for a reply on freeware. I understand there is limited staff and time to reply to all the comments but to simply close the ticket with zero resolution is not professional or acceptable in any use case. Freeware or not. Dude.

Original case that was closed with zero response ---->>> https://github.com/snipe/snipe-it/issues/9194

**Comment by snipe** [comment]
It's fairly unreasonable, IMHO, to expect us to track every fix within each old version, especially when we're as an active a repo as we are. We write detailed changelogs specifically for this reason, and [this fix was addressed in the release notes for 5.0.11](https://github.com/snipe/snipe-it/releases/tag/v5.0.11). While I understand that reading hundreds of lines of changelog notes can be challenging, so can keeping track of hundreds of tickets, fixes and releases. How is it reasonable to expect us to recall that we fixed this 10 versions ago, in November? Why wouldn't you either read the release notes, or just try upgrading if you don't feel like doing that? 

Good luck with your greener pastures.

**Comment by androbourne** [comment]
> It's fairly unreasonable, IMHO, to expect us to track every fix within each old version, especially when we're as an active a repo as we are. We write detailed changelogs specifically for this reason, and [this fix was addressed in the release notes for 5.0.11](https://github.com/snipe/snipe-it/releases/tag/v5.0.11). While I understand that reading hundreds of lines of changelog notes can be challenging, so can keeping track of hundreds of tickets, fixes and releases. How is it reasonable to expect us to recall that we fixed this 10 versions ago, in November? Why wouldn't you either read the release notes, or just try upgrading if you don't feel like doing that?
> 
> Good luck with your greener pastures.

Hmm no I except that if you read a ticket and knew exactly what the issue is... that you would have posted the resolution instead of just closing the case. Again, not professional, and it's as simple as that. Don't try to convolute your excuses as to why you couldn't simply answer the question when you already knew the answer... Instead of just closing the ticket. There is no excuse for that. If that is your definition of support, then your business ethics are pretty crap.

I work as a network/systems engineer and because of your unprofessional resolution to this topic. I will not be referring your product for use to others in my field.

And I don't need luck on my greener pastures. The solution was put into place 5 minutes after I deleted Snipe-IT from my server and the new solution is working great with good support from people that don't just close cases with zero resolution.

**Comment by snipe** [comment]
I'm glad you found something that works for you :)

**Comment by androbourne** [comment]
> I'm glad you found something that works for you :)

Thanks!
