### ISSUE TITLE
URL link is incorrect on Asset Models Edit icon.

### ISSUE THREAD

**Issue by bra1ncramp** [grokability/snipe-it#9250]
#### Please confirm you have done the following before posting your bug report:

- [ YES] I have enabled debug mode 
- [ YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
URL link is incorrect on Asset Models Edit icon.

**To Reproduce**
when you got to <snipe-it>.com/models and click the pencil, it links to ../licenses/{license}/edit

**Expected behavior**
when you got to <snipe-it>.com/models and click the pencil, it links to ../models/{model}/edit

**Server (please complete the following information):**
 - Snipe-IT Version [5.1.2]
 - OS: [RHEL 7]
 - Web Server: [Apache]
 - PHP Version [7.4.15]

**Desktop (please complete the following information):**
 - OS: [macOS 10.15]
 - Browser [chrome, safari]
 - Version [89, 14]

**Comment by alitheg** [comment]
I've also come across this on the latest version

**Comment by circuitswitch** [comment]
I also confirm this is an issue.  We just received a bunch of equipment and desperately need this fixed.
In addition, the clone and delete buttons are also showing the wrong URLs.

**Comment by matthiasstraka** [comment]
Looks like this was already fixed in https://github.com/snipe/snipe-it/pull/9232 (I haven't tested it but I hope there will be a new release soon)

**Comment by snipe** [comment]
This is already fixed.
