### ISSUE TITLE
Company Drop-Down Box (Default Value)

### ISSUE THREAD

**Issue by reggiejdean** [grokability/snipe-it#9251]
Can we someone allow the SNIPE-IT to set default values within the company drop-down box?  Thank you.

**Comment by snipe** [comment]
> Can we someone allow the SNIPE-IT to set default values within the company drop-down box? Thank you.

I don't really understand what you're asking for here.

**Comment by reggiejdean** [comment]
Hi there,

When the user selects a company name from a drop down box in SNIPE-IT, the user always as to select the name from the drop down.  I think the default value is ---please select---.  Can I change the default value in the drop-down box to always have the company name selected?

--Please Select-- (always selected)
ABC Company

vs

ABC Company (always selected)

Thanks,
Reggie Dean

________________________________

**Comment by snipe** [comment]
Do you have multiple companies? And is full company support enabled?

**Comment by reggiejdean** [comment]
Yes, I do have multiple companies listed in the company drop-down box.  Not sure if full company support is enabled.  I have to check SNIPE-IT.

________________________________

**Comment by snipe** [comment]
I think allowing a default company to be selected automatically would introduce too many mistakes for people who are not paying attention when they fill out the forms. I don't think this is a feature we can consider. :(

**Comment by reggiejdean** [comment]
I do understand.  Okay, thank you.

________________________________

**Comment by outforever** [comment]
Was this ever implemented? We, as most companies, only have one company. It would be nice if this field defaulted to the single value if there was just one value.... can you really not set defaults in the template? This is one of the first search results when i searched for that function.
