### ISSUE TITLE
Many problems with Installation on a Windows System and migration Data from Ubuntu 

### ISSUE THREAD

**Issue by VoBo2021** [grokability/snipe-it#9252]
Hi,

i plan to get the Snipe-IT running on a windows server and later shut down the old ubuntu system. the Win 2019-Server is now up and running.

i followed the Instructions here: https://www.youtube.com/watch?v=AHNi9eU9icw to install the main-program and move (https://snipe-it.readme.io/docs/moving-snipe-it) the data from the old ubuntu-system.

The database is filled. I can see tables and values on it.

If i open the Browser (Edge/Firefox), i can see the Dashboard. I can see the last activities and charts.

My problems are:
- If i click on Assets, i can see the assets. I can´t add assets and edit --> Error 500 **---> fixed after php-upgrade**
- i can´t see Users, but i can add. **---> fixed after php-upgrade**
- /reports/custom --> Error 500 **---> fixed after php-upgrade**

This are open (05.03.21):
- /account/requestable-assets --> Error 500
- can´t see accessories. I can add titems. 
- /reports/accessories --> Error 500

All my new Items are visible in the Database.

Server
 - Snipe-IT Version Windwos Version v5.1.2 - build 5847 and Version v4.1.11-pre - build 3307 on Ubuntu (16)
 - Web Server:  IIS
 - PHP Version: 7.3.27 and 7.4

Desktop-System:
 - OS:  Win 10 (1909)
 - Browser IE 11, Edge and Firefox 86.0

I addes some files. i´m a normal user and can´t program. I hope sombody can help and it´s solveable :-)
Thank you for all.

CU
Volker

[php.txt](https://github.com/snipe/snipe-it/files/6086215/php.txt)
![2021-03-04 20_49_50-Assets_physical_path](https://user-images.githubusercontent.com/80060311/110021903-9ca42180-7d2b-11eb-9063-c3359010782e.png)
![2021-03-03 09_39_18-Assets_no_picture](https://user-images.githubusercontent.com/80060311/110021905-9d3cb800-7d2b-11eb-9f28-a2fc8a170744.png)
![2021-03-04 20_43_09-Asset with_path](https://user-images.githubusercontent.com/80060311/110021908-9dd54e80-7d2b-11eb-8e68-ba8c8d4127b1.png)

**Comment by lalalostyou** [comment]
Hi! I recently install snipe it in windows with the help of this video. https://www.youtube.com/watch?v=kxGGQutvktM

<blockquote><img src="https://i.ytimg.com/vi/kxGGQutvktM/maxresdefault.jpg" width="48" align="right"><div><img src="https://www.youtube.com/s/desktop/9ba58884/img/favicon_144.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=kxGGQutvktM">Part 1 - SNIPE-IT Installation On Windows Server 2016</a></strong></div><div>Step by step guide for SNIPE-IT installation on Windows Server 2016 with IIS, PHP and MySQL. SNIPE-IT is a great open source asset management system.Hit like...</div></blockquote>

**Comment by VoBo2021** [comment]
Hi,
thank you for this, but there are old versions of PHP and Database. this was my 1st try, but i need a system, who is up2date.
i installed the newest Database 10.5, PHP7.4 and 7.3x and C++ redistributable.
is there a confict with PHP or the Database?

**Comment by VoBo2021** [comment]
Hi,
i tried to modify an asset. im adding an additional picture of the item. the pic is stored correctly in the uploads-folder on the server. it seems, there is a problem to "show" the file. the error is: Failed to load image... snipe-it found files, but the format is not loading.
what can we do?
![2021-03-05 15_11_52-Assets_saved_pic](https://user-images.githubusercontent.com/80060311/110127309-c7db4f00-7dc5-11eb-9e8b-ba2e21112148.png)

**Comment by VoBo2021** [comment]
Hi again...

the problem with the pictures are solved. im adding the line **APP_URL=http://your_host_name/** to the **.env-file**.

Other problems i had are fixed by php-upgrade.php at the DOS-Prompt:

- If i click on Assets, i can see the assets. I can´t add assets and edit --> Error 500 
- i can´t see Users, but i can add. 
- /reports/custom --> Error 500 

...after upgrade do **php artisan config:clear** and restart IIS.

Open Issues are:
the problems with the Accessories and 500-server-error persists. i´m adding a part in accessories, but i can´t generate/create reports. the parts are not listed in the overview "accessories", but in the database. you can see it in the dashboard-activity.

Dashboard-Activity:
![2021-03-05 16_42_23-129 13 244 43 - new_accessorie-item](https://user-images.githubusercontent.com/80060311/110138165-f8c18100-7dd1-11eb-9d70-ddf0b2d988cf.png)

Error with Path:
![2021-03-05 16_42_45-129 13 244 43 -error500](https://user-images.githubusercontent.com/80060311/110138173-fbbc7180-7dd1-11eb-90f7-3c5def47da2b.png)

i hope it´s solveable...
thank you.

**Comment by snipe** [comment]
If you're getting a 500 error, we need to see the error logs in order to see what's happening, as we mention in the issue template.

Your APP_URL should *not* have a trailing slash btw - per the documentation.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
