### ISSUE TITLE
LDAP removing imported information

### ISSUE THREAD

**Issue by Mynty100** [grokability/snipe-it#9262]
#### Expected Behavior (or desired behavior if a feature request)

We LDAP our users and import the employee number as our AD head office places this under CustomAttribute6 and we have tried to import this under the LDAP Employee Number field but no data sync's. So we just CSV import updated data over the top.
However, once we import data is there, then we LDAP scyn and it is removed. We would like this not to happen.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? = Upgrade
- Version of Snipe-IT you're running = v5.1.2
- Version of PHP you're running = 7.2
- Version of MySQL/MariaDB you're running = One that comes with the install.
- What OS and web server you're running Snipe-IT on = Ubuntu
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) = install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error = No errors

Looking forward to your response.

Thanking you,
Mytny.

**Comment by kno005** [comment]
I also had problems importing the EmployeeID until I found out that the name for the field to import has to be in lowercase. So CustomAttribute6 should be entered as customattribute6. If hope this helps.

**Comment by Mynty100** [comment]
@kno005 thanking you very much. got this working now.
Regards,
Mynty.
