### ISSUE TITLE
3.	Currently our assets tag are prefix with CB/LT- for laptop, CB/MT- for monitor and so no. Please give us the ability to add multiple prefix assets tag and while adding creating assets please add and generate tags base on the asset category we are selected.

### ISSUE THREAD

**Issue by bhakuparkharsohtun** [grokability/snipe-it#9269]
**Snipe-IT Cloud Hosted

**Is your feature request related to a problem? Please describe.**
Currently our assets tag are prefix with CB/LT- for laptop, CB/MT- for monitor and so no. Please give us the ability to add multiple prefix assets tag and while adding or creating assets please add and generate tags base on the asset category we are selected.

**Comment by snipe** [comment]
Closing as duplicate of #9013
