### ISSUE TITLE
Can't edit models with edit button.

### ISSUE THREAD

**Issue by TurnipGit** [grokability/snipe-it#9270]
**Describe the bug**
When trying to modify a model, the page license does not exist appers

**To Reproduce**
1. Go to 'settings left panel'
2. Click on 'asset models'
3. Klick on yellow edit button.
4. wrong page no license error shows up

**Expected behavior**
page for editing the model to show up.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version Version v5.1.2 - build 5847 (master) 
 - OS: [Windows server]
 - Web Server: [IIS]
 - PHP Version 7.4

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [latest]

**Error Messages**
Dont find a relevent debug message

**Additional context**
- Is this a fresh install
- Manual install
- i have not manually edited any data directly in the database

**Comment by snipe** [comment]
This was fixed in v5.1.13 via #9232
