### ISSUE TITLE
Snipe-It Screwed Up after 5.1.3

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#9271]
#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ ]X I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Seems that CSS are missing

**To Reproduce**
1. Update docker image to 5.1.3
2. Use Snipe-It

**Expected behavior**
Snipe-It should work normally

**Screenshots**
![Screenshot_2021-03-10 Dashboard Snipe-It Staging](https://user-images.githubusercontent.com/33548070/110595472-53fec500-817e-11eb-8b19-0607d12f4301.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.3 Docker Image
 - Rancher2 Nginx Ingress controller with X-Forwarded-For and X-Forwarded-Proto header set

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox
 - 86

**Error Messages**
- No error Message

**Additional context**
- Updated docker image from 5.1.2 to 5.1.3

On Chrome, wich force everything to https, Snipe-It semms to work normal, so could be a problem about link generation.
My APP_URL environment variable is correctly set

**Comment by snipe** [comment]
@inietov or @uberbrady - can you take a look at this? We haven't made any changes to the APP_URL or anything like that recently. The only changes were to add the `url()` facade to handle Snipe-IT installs in sub-directories, but I wouldn't imagine that should break anything. 

@Cobra1978 - can you please provide the browser console debug info, per the original issue request. And please provide your  APP_URL from your env

**Comment by ghost** [comment]
Ok.

My APP_URL is https://snipe-it.sviluppo.dna (is our internal test environment)

Here is the console output of firefox

Some cookies are misusing the recommended “SameSite“ attribute 3
Blocked loading mixed active content “http://snipe-it.sviluppo.dna/css/dist/all.css?id=199fdf677ce0dce6cef8”
snipe-it.sviluppo.dna
Blocked loading mixed active content “http://snipe-it.sviluppo.dna/css/dist/skins/skin-blue.css?id=2a741dd5409582c0af89”
snipe-it.sviluppo.dna
Blocked loading mixed active content “http://snipe-it.sviluppo.dna/css/dist/bootstrap-table.css?id=1e77fde04b3f42432581”
snipe-it.sviluppo.dna
Blocked loading mixed active content “http://snipe-it.sviluppo.dna/js/html5shiv.js”
snipe-it.sviluppo.dna
Loading failed for the <script> with source “http://snipe-it.sviluppo.dna/js/html5shiv.js”. snipe-it.sviluppo.dna:68:1
Blocked loading mixed active content “http://snipe-it.sviluppo.dna/js/respond.js”
snipe-it.sviluppo.dna
Loading failed for the <script> with source “http://snipe-it.sviluppo.dna/js/respond.js”. snipe-it.sviluppo.dna:69:1
Blocked loading mixed active content “http://snipe-it.sviluppo.dna/js/dist/all.js?id=0efed60df4636f215a73”
snipe-it.sviluppo.dna
Loading failed for the <script> with source “http://snipe-it.sviluppo.dna/js/dist/all.js?id=0efed60df4636f215a73”. snipe-it.sviluppo.dna:883:1
Blocked loading mixed active content “http://snipe-it.sviluppo.dna/js/pGenerator.jquery.js”
snipe-it.sviluppo.dna
Loading failed for the <script> with source “http://snipe-it.sviluppo.dna/js/pGenerator.jquery.js”. snipe-it.sviluppo.dna:886:1
Blocked loading mixed active content “http://snipe-it.sviluppo.dna/js/dist/bootstrap-table.js?id=58d95c93430f2ae33392”
snipe-it.sviluppo.dna
Loading failed for the <script> with source “http://snipe-it.sviluppo.dna/js/dist/bootstrap-table.js?id=58d95c93430f2ae33392”. snipe-it.sviluppo.dna:889:1
Uncaught TypeError: $ is not a function
    <anonymous> https://snipe-it.sviluppo.dna/:892
snipe-it.sviluppo.dna:892:6
Uncaught TypeError: $ is not a function
    <anonymous> https://snipe-it.sviluppo.dna/:1527
snipe-it.sviluppo.dna:1527:29
Uncaught TypeError: $ is undefined
    <anonymous> https://snipe-it.sviluppo.dna/:1565
snipe-it.sviluppo.dna:1565:9
Uncaught TypeError: $ is not a function
    <anonymous> https://snipe-it.sviluppo.dna/:1615
snipe-it.sviluppo.dna:1615:11

​

**Comment by snipe** [comment]
Thanks so much for that extra info. It does certainly seem like it's the http vs https issue based on those browser console errors, but we haven't touched anything with respect to any of that recently. Closest thing was the `url()` facades, but that was only on [two blade templates](https://github.com/snipe/snipe-it/pull/9170), so if that managed to break anything, it would only break there. 

Can you tell me what version you were upgrading *from* when you updated to 5.1.13? Trying to see if we made any docker changes between whatever your previous version was and the current one. I'm [not seeing anything damning here though](https://github.com/snipe/snipe-it/pulls?q=is%3Apr+is%3Aclosed+docker).

If you uncomment these two lines in your htaccess, does that improve anything?
https://github.com/snipe/snipe-it/blob/f164f0ea604c38d5c3a751af86b364e3bf974f73/public/.htaccess#L9-L10

**Comment by ghost** [comment]
Hi. 

As already wrote i've updated from 5.1.2, wich is in production and works well, to 5.1.3

If i uncomment those lines it ends in a redirection loop.

It seems that snipe-it dosen't read the x-forwarded-proto headers, and think that the connection is http, but i'm sure that the ingress controller sets this header, and as said the production environment, whish is on 5.1.2, dosen't had any issue.

**Comment by snipe** [comment]
> It seems that snipe-it dosen't read the x-forwarded-proto headers

None of that would have changed from 5.1.12 to 5.1.13 though. As you can see through [the diff](https://github.com/snipe/snipe-it/compare/v5.1.2...v5.1.3), the changes were largely cosmetic, and nothing touched header handling, or even the framework itself.

Maybe @uberbrady or @inietov will have some ideas when they get up in the morning.

**Comment by ghost** [comment]
I don't know what to say, tell if there are some other info that i could provide.

**Comment by ghost** [comment]
Hi.

You can close the thicket, the problema was at too low  resource limit setting on our setup, surprisingly the container never got killedd with "oom", instead it was acting weird as i've said.

No log was pointing me tho this, i dound that simply raising the memory limit, and the contaner started working normally.

Sorry
