### ISSUE TITLE
Syncing with AD again

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#9272]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Each update of the program introduces ambiguity in the work (synchronization) with AD. I have disabled the ability to sync the email field with AD. Before updating the snipeit, I manually entered the email address in the profile of one user. After updating snipeit to the latest version 5.1.3, and after syncing with AD, this user's email address was deleted.

**Expected behavior**
Developers often change the concept of synchronization with AD. I'm afraid to manually enter something already, since this data can be automatically deleted when syncing with AD, in the new version of snipeit

**Comment by snipe** [comment]
We have made no changes to AD syncing between 5.1.12 and 5.1.13, [as you can see by the diff](https://github.com/snipe/snipe-it/compare/v5.1.2...v5.1.3). We always make notes of any breaking changes in the release notes, and it's the user's responsibility to read them before upgrading.
