### ISSUE TITLE
Data model out of sync after importing data from previous version

### ISSUE THREAD

**Issue by brianw27** [grokability/snipe-it#9274]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Upgraded from v.4.1.14 to v.5.1.2. Imported data from previous version to the current version by running the SQL backup. Even after running php artisan migrate, the data model is missing columns and tables needed in v.5.1.2. 

**To Reproduce**
Do upgrade described above. Go to the page for an exiting user. (This is just one example, any action that uses a table or column not found in v.4.1.14 will reproduce the error._

**Expected behavior**
Expect to see the page for the user. See an SQL error "Column not found" instead.

**Screenshots**

**Server (please complete the following information):**
 - Upgrade from 4.1.14 to 5.1.2
 - OS: Ubuntu 20.04.2
 - Web Server: Apache
 - PHP Version 7.4.3

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 86

**Error Messages**
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'accessories_users.note' in 'field list' (SQL: select `accessories`.*, `accessories_users`.`assigned_to` as `pivot_assigned_to`, `accessories_users`.`accessory_id` as `pivot_accessory_id`, `accessories_users`.`id` as `pivot_id`, `accessories_users`.`created_at` as `pivot_created_at`, `accessories_users`.`note` as `pivot_note` from `accessories` inner join `accessories_users` on `accessories`.`id` = `accessories_users`.`accessory_id` where `accessories_users`.`assigned_to` in (19))

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What method you used to install Snipe-IT: install.sh
- Clean install of 5.1.2. No other issues encountered.
- No data or schemas altered in the database except to run the SQL to import data from the previous version

**Comment by snipe** [comment]
What version of MySQL/MariaDB are you running? This seems related to #8636

**Comment by brianw27** [comment]
We are running MySQL/MariaDB 10.3.25.

**Comment by snipe** [comment]
When you run migrations, what is the output?

**Comment by brianw27** [comment]
I see this:
Migrating: 2018_04_16_133902_create_custom_field_default_values_table

In Connection.php line 669:
                                                                                                      
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exis  
  ts (SQL: create table `models_custom_fields` (`id` int unsigned not null auto_increment primary ke  
  y, `asset_model_id` int not null, `custom_field_id` int not null, `default_value` text null) defau  
  lt character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)                              
                                                                                                      

In PDOStatement.php line 131:
                                                                                                      
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exis  
  ts                                                                                                  
                                                                                                      

In PDOStatement.php line 129:
                                                                                                      
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exis  
  ts

**Comment by brianw27** [comment]
I replaced MariaDB with MySQL 8.0.23, but I'm still getting the same result.

**Comment by snipe** [comment]
Sounds like your migrations table is out of whack. Give me a bit to find the thread that will help you un-whack it.

**Comment by brianw27** [comment]
Any additional info on un-whacking my migrations able?

**Comment by brianw27** [comment]
The issue has still not been resolved. Would exporting the data from the old version and importing into the new one be an option, rather than restoring from a backup?

**Comment by snipe** [comment]
The data models are fine. There are many closed issues about how to unwhack the migrations table in this repo.
