### ISSUE TITLE
[Solution found, please implement]1D barcode resolution (DPI) too low when Label dimensions are low (Not scannable)

### ISSUE THREAD

**Issue by AlexanderWPapyrus** [grokability/snipe-it#9293]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Hi,
we have a 9 symbol long asset number "SYS000000" and when we print lables 1.6inch (42mm) long, the barcodes are not scannable. After days of debugging I noticed that when I "generate lables" with a Lengh of 4inch, then set the Label dimensions back to 1.6 inch and printed them, it suddenly got scannable (because previously generated high-resolution barcodes are cached even when small dimention is printed).
Later on I've seen that the generated public/uploads/barcodes/c128-sysXXXXXX.png file has a resolution relative to the Label dimensions.
If I by mistake generate the lables first with 1.6 inch, I need to delete them in public/uploads/barcodes/. Then re-generate at 4 inch -> set back to 1.6 inch -> 're-generate' the lables to print them with the cached high-res barcode

edit: Forgot to mention that this issue appeared with all 1d barcode types
My custom css to fit barcode qr code and text together (Vertically)
[Custom CSS (Branding).txt](https://github.com/snipe/snipe-it/files/6203192/Custom.CSS.Branding.txt)
![image](https://user-images.githubusercontent.com/80526133/112442888-9c0c1300-8d4c-11eb-8c9d-2c24c1c4f739.png)
**Expected behavior**
Is it possible to set the barcode generation resolution relative to the symbols encoded and not to the lable lengh?
Or just a very high hardcoded resolution so this won't happen, even when the lables are 'smal'?

**Screenshots**
generated at 1.6 inch setting (not enough resolution/DPI to get distinct distinct bar sizes)
![barcode (1876) at 1 6inch](https://user-images.githubusercontent.com/80526133/111162606-9835ff00-859c-11eb-914c-0bd48e97aef9.png)
Generated at 4 inch setting (when printed also in 1.6 inch, it's scannable as DPI is high enough for correct bar sizes)
![barcode (1876) at 4inch](https://user-images.githubusercontent.com/80526133/111162607-9835ff00-859c-11eb-961b-8bf7df86420e.png)

![2021-03-15 14_42_20-Update Label Settings __ Papyrus Asset management](https://user-images.githubusercontent.com/80526133/111162772-c1ef2600-859c-11eb-808e-11b242afd8b1.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.11 build 5695
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version 7.2.34-2+ubuntu18.04.1
 - IMAGE_LIB= tested both gd & imagick

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, FireFox - Irrelevant

**Error Messages**
- no Error as it's only noticible when scanning barcode 

**Additional context**
- also tested with fresh install (manual and install .sh)

btw: Thanks for the amazing SnipeIT project <3
-Alex

**Comment by AlexanderWPapyrus** [comment]
Hi again,
we upgraded (actually fresh install) our test environment to 
_v5.1.4 build 5886 (g9f3a8a43c)
PHP Version7.4.16_
and the issue is still the same. I tried to check the barcode generating libraries to find the code where the DPI or generating and I potentially found it:
snipeit\vendor\tecnickcom\tc-lib-barcode
https://github.com/tecnickcom/tc-lib-barcode/
function `getBarcodeObj()` used in:
snipeit\app\Http\Controllers\Assets\AssetsController.php
![image](https://user-images.githubusercontent.com/80526133/112351546-4858e580-8cca-11eb-83a8-af0aab0810f0.png)
So I exchanged the $size['width'] with a number like 600 but generation was still the same.
Also in the same file I found:
![image](https://user-images.githubusercontent.com/80526133/112353542-1d6f9100-8ccc-11eb-8a0e-16a605b1f009.png)
and changed 'width' to 50 but still no difference (ofcause I reversed all changes after testing)

But then finally i found the magic line:
![image](https://user-images.githubusercontent.com/80526133/112354205-bdc5b580-8ccc-11eb-91d4-afc305278521.png)
so I exchanged the 96 with 200 and it works 🎉
generated with 1.6 inch:
![image](https://user-images.githubusercontent.com/80526133/112354985-83a8e380-8ccd-11eb-94ef-f460ffabeb57.png)


Took me 3h to find it out and now I have the Big BIG favor to ask. Please make it relative to the in the barcode encoded data and not relative to the label width.
![image](https://user-images.githubusercontent.com/80526133/112355147-ad620a80-8ccd-11eb-88d6-667de88044a8.png)
Best wihses and love the project,
AlexW

<blockquote><img src="https://avatars.githubusercontent.com/u/4163527?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/tecnickcom/tc-lib-barcode">tecnickcom/tc-lib-barcode</a></strong></div><div>PHP library to generate linear and bidimensional barcodes - tecnickcom/tc-lib-barcode</div></blockquote>

**Comment by snipe** [comment]
Thanks for this bug report! This issue has been fixed and merged into the `develop` branch, and will be in the next release.

![trek-nods](https://user-images.githubusercontent.com/197404/47946205-b9af5800-dec5-11e8-85af-fce7915a0938.gif)
