### ISSUE TITLE
Manually restore of a SQL-Database backup

### ISSUE THREAD

**Issue by scr1tch** [grokability/snipe-it#9295]
Hello everybody. We used snipeit until the raspberry broke down. We had not created a backup from SnipeIT, but we were able to save the SQL database from the old SnipeIT installation. Unfortunately, we then tried to restore this in our new Snipeit without success. Although the process was successful, the data cannot be used in SnipeIT and SnipeIT is completely empty, even though we had already set up over 100 assets. Do you have any ideas what could have gone wrong and how we can get the data back into SnipeIT?

**Comment by AlexanderWPapyrus** [comment]
Hi,
do you get any error messages when restoring the SQL file?
Maybe our own company internal guide will help:
First, login via SSH or directly on the server

//Copy the backup archive from the backup location to your snipeit server and unzip it
`cd `//backup location
`unzip snipe-it-2020-11-27-01-00-03.zip -d snipeit-backup-unzipped`
Restore the files:
//make a backup of whatever you have now (current snipeit folder)

`cp -r snipeit-backup-unzipped/var/www/snipeit /var/www`

//Restore the database
`mysql -u root -p snipeit < ~/snipeit-backup-unzipped/db-dumps/mysql-snipeit.sql`
//Type in the database password
//DEBUG: If you want to use SQL directly from the file and not the command above, you need to add "USE snipeit" on top of the SQL file to select the database you want to execute all the commands in the SQL file.
//Final commands from snipeit:

```
cd /var/www/snipeit
php artisan migrate
php artisan config:clear
```
// eventually there will be errors during migrate like "table already exists". This might be due different versions (newer DB used on onlder snipeit and then back on newer). In this case check if it does and if it is empty. If it's empty drop it with "drop table Xkits_accessoriesX;"
//retry: `php artisan migrate`


//Backup restore of SQL set done
// I also recommend to replace the snipeit\public folder as it contains many dependencies to the databese
update: prettify

**Comment by scr1tch** [comment]
It works, thank you!
