### ISSUE TITLE
Automatically generate (random?) username for new users

### ISSUE THREAD

**Issue by Lombra** [grokability/snipe-it#9307]
**Is your feature request related to a problem? Please describe.**
Being required to create credentials when adding People who won't be needing the ability to log in.

**Describe the solution you'd like**
I would like to be able to be able to add People by providing a first and last name, and nothing else.

**Describe alternatives you've considered**
Trying to construct some sensible user name from the real name, which is not going to work.

**Additional context**
Sort of a follow up to another issue I submitted the other day requesting that usernames be optional. I understand that this is not possible at this time. A randomly generated username could be an acceptable alternative. I'm thinking just something like a fixed length string of random (or sequential for that matter) numbers. Maybe prefixed by some letter.

Would be great if you were able to somehow use it with the API, too.

**Comment by snipe** [comment]
If I'm honest, this isn't going to happen. We provide mechanisms to automate a lot of this. it would make a huge change in the way the system works.

**Comment by Lombra** [comment]
Fair enough. What automation mechanisms are you referring to?

Den ons 17 mars 2021 02:32snipe ***@***.***> skrev:
