### ISSUE TITLE
Changing Locale does not work

### ISSUE THREAD

**Issue by yosiasz** [grokability/snipe-it#9323]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When changing the locale to a language other than English, it does not change to the selected language

**To Reproduce**
1. Go to Settings 
2. Click on localization
3. Change language drop down to any other language other than English
4. Save
5. All settings are still in English

**Expected behavior**
Changing Localization will change UI

**Server (please complete the following information):**
 - Snipe-IT Version : 5.1.3
 - OS: Windows
 - Web Server: IIS
 - PHP Version : 7.4.16

**Comment by curio77** [comment]
Same here with latest version (v5.1.6). Affects the global localization settings (none save); per-user, the locale can be changed via the user profile.

**Comment by shimanotaka** [comment]
I have the same issue in v6.0.9. Also changed APP_LOCALE in the .env file and run "php artisan cache:clear" but the language still didin't change.

**Comment by snipe** [comment]
Locale is stored in several places - inn the APP_ENV, at the app level under localization, and also under the logged in user's profile.

**Comment by saidyildiz** [comment]
Hello, I have the same problem, although I changed the language in the settings, the dashboard is not Turkish, only the member login page is Turkish, when I look in debug mode, the current locale appears as en-TR. I checked my Env file and it is the same but translations are not applied. php artisan config:clear
I tried the command but it didn't work.
