### ISSUE TITLE
Allow Custom Fields to be uploadable images

### ISSUE THREAD

**Issue by mfleeson** [grokability/snipe-it#9345]
**Server (please complete the following information):**
 - Snipe-IT Version 5.1.4
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.4

**Is your feature request related to a problem? Please describe.**
My assets need to have several images to help identify them. For example we have several decanters each with different lettering on. We need a photo of the decanter and one of the specific engraving.

**Describe the solution you'd like**
The ability to choose an image upload field type when creating a custom field.

**Describe alternatives you've considered**
Layout and combine multiple images into one file :(
Downloading Github/learning Laravel and coding it myself.

**Additional context**

**Comment by snipe** [comment]
> My assets need to have several images to help identify them.

I'm not sure what the ask is here then? Can you not just upload those files using the file upload button?

<img width="558" alt="View_Asset_530635422____KOLFöRSNIPEN_TEST" src="https://user-images.githubusercontent.com/197404/113748307-2c3b4800-96bd-11eb-9022-e017f9852975.png">

<img width="1271" alt="Screen Shot 2021-04-06 at 9 48 14 AM" src="https://user-images.githubusercontent.com/197404/113748362-3fe6ae80-96bd-11eb-8cd1-c540b46e692d.png">

**Comment by mfleeson** [comment]
I'm so sorry I didn't realise uploading files worked for images. I have closed this issue. Many thanks.
