### ISSUE TITLE
LDAP Active Flag

### ISSUE THREAD

**Issue by Thunder-Child** [grokability/snipe-it#9349]
#### Expected Behavior (or desired behavior if a feature request)

That the "LDAP Active Flag" field works.

-----

#### Actual Behavior

The active flag field does not appear to get utilized or I am not entering the correct flag to make it work.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
 Fresh
- Version of Snipe-IT you're running
5.1.4 - build 5886 (docker)
- Version of PHP you're running
7.2.24
- Version of MySQL/MariaDB you're running
mysql 8
- What OS and web server you're running Snipe-IT on
docker
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/admin/ldap - "LDAP Active Flag"
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
N/A - No LDAP on demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
Completed Installation.  The only errors were related to mysql which was resolved with "command: --sql_mode='' --default-authentication-plugin=mysql_native_password" in the docker-compose file.
- Indicate whether or not you've manually edited any data directly in the database
No.

This is using AD.
I have tried the following entries in the field:
640
encrypted_text_pwd_allowed
encrypted_text_pwd_allowed|normal_access
encrypted_text_password_allowed
encrypted_text_password_allowed|normal_access

None of which seem to work.

I'm not a php dev, but I took a look at https://github.com/snipe/snipe-it/blob/0e1f6a3fd1ad444e45c6f4d4cddc0ad12c2b892c/app/Console/Commands/LdapSync.php#L197 and it does not appear to be sourcing the active flag field.  It's possible that it could be happening in a different location, but I am unaware if so.

Thank you.

**Comment by snipe** [comment]
Hi there - Pretty sure this has been working for a long time now, sorry for not closing this sooner. I'm going to close this. Please feel free to open a new issue if you're still having trouble.
