### ISSUE TITLE
Inability To Correctly Set Certain Custom Field Default Value(s) via Edit Model.

### ISSUE THREAD

**Issue by jtresslerTS** [grokability/snipe-it#9360]
- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I go to set **_default_** custom field values via the _edit model feature_ check box and radio buttons simply show the name of the field with no ability to change it.

_- Bug **is reproducible** in the **demo**. I made a test checkbox field and tried to set default values in the edit asset model feature: same results as my own instance._
https://snipeitapp.com/demo

**My Instance Screenshots**
![1](https://user-images.githubusercontent.com/81259306/112874517-e6a4cc80-9077-11eb-93b2-276f22ab7b1a.png)
![2](https://user-images.githubusercontent.com/81259306/112874527-e99fbd00-9077-11eb-8673-d140f3bb30ec.png)
![3](https://user-images.githubusercontent.com/81259306/112874533-eb698080-9077-11eb-844f-9e33ac31df6d.png)

Version v5.1.4 - build 5886 (master)
Snipe-IT version 5.1.4 build 5886 (g9f3a8a43c)
Software LicenseAGPL3
PHP Version 7.2.24-0ubuntu0.18.04.7
Laravel Version 6.20.16

Win 10 (latest)
Microsoft Edge (CHROME) Version 89.0.774.63 (Official build) (64-bit)

Thank you and with respect,

**Comment by snipe** [comment]
I believe this is already fixed on develop
