### ISSUE TITLE
Employee No. Field will not populate using LDAP Sync

### ISSUE THREAD

**Issue by twinsmom71** [grokability/snipe-it#9361]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
We have an attribute named EmployeeID which contains a 9 digit number.  I enter employeeID in the LDAP Employee Number field and it will not pull in the values.  If it change it to any other attribute that contains text, it works fine.  
**To Reproduce**
1. Go to 'Admin'
2. Click on 'LDAP'
3. Scroll down to 'LDAP Employee No and enter employeeID'
4. Run LDAP Sync and Employee No field remains blank for all users

**Expected behavior**
I would expect it to pull in the employeeID attribute values.  I can manually put them in, it's just LDAP Sync that won't pull the values

**Screenshots**
![2021-03-29_16-08-39](https://user-images.githubusercontent.com/79875860/112896166-1241aa00-90ac-11eb-89d2-670b01fe1991.jpg)
![2021-03-29_16-14-43](https://user-images.githubusercontent.com/79875860/112896185-14a40400-90ac-11eb-9f3e-dbcd5bc23da5.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.3
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] 
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Edge/Chrome

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - None
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - N/A, LDAP not enabled on demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on CentOS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Godmartinz** [comment]
Hello @twinsmom71 ,

Try 'employeeid' (all lowercase) or perhaps even 'employeenumber'. Hopefully that solves this for you.

**Comment by twinsmom71** [comment]
Wow, so the all lowercase worked!  Thank you so much Godmartinz, I struggled with this for days!  Such a simple fix!
