### ISSUE TITLE
Illuminate \ Database \ QueryException (42S21) SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'ldap_server_cert_ignore' (SQL: alter table `settings` add `ldap_server_cert_ignore` tinyint(1) not null default '0')

### ISSUE THREAD

**Issue by kang971130** [grokability/snipe-it#9362]
![WeChat Photo Editor_20210330142554](https://user-images.githubusercontent.com/81610634/112943485-19c48a00-9164-11eb-9b96-f47d3e82bb0b.jpg)
![WeChat Screenshot_20210330142622](https://user-images.githubusercontent.com/81610634/112943503-221cc500-9164-11eb-8e24-f5d6c5d72631.png)
I have this problem. 
OS :ubuntu 20:40

**Comment by snipe** [comment]
You can try commenting out the code in `database/migrations/2015_12_21_193006_add_ldap_server_cert_ignore_to_settings_table.php`

So from:

```php
Schema::table('settings', function(Blueprint $table)
{
	$table->boolean('ldap_server_cert_ignore')->default(FALSE);
});
```

to:

```php
// Schema::table('settings', function(Blueprint $table)
// {
//	$table->boolean('ldap_server_cert_ignore')->default(FALSE);
// });
```

And try running migrations again - BUT - this error strikes me as odd, as if something is failing somewhere else, as we only try to add that column once (in that file.)

**Comment by kang971130** [comment]
Thanks done
