### ISSUE TITLE
Trying to upgrade from Snipe IT 5.1.1 to 5.1.3

### ISSUE THREAD

**Issue by karthik8223** [grokability/snipe-it#9368]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

I was hoping my snipeit will be upgraded to 5.1.3 by running php upgrade.php 
-----

#### Actual Behavior

(what actually happens goes here)

It says permission issue which Im not sure what to do.
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
   fresh installed 5.1.1

- Version of Snipe-IT you're running 
   5.1.1

- Version of PHP you're running
  Current PHP version: (7.4.3) is at least 7.2.5 - continuing...

- Version of MySQL/MariaDB you're running
  None

- What OS and web server you're running Snipe-IT
- Ubuntu Web Server 20.04.2 LTS

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
 using git method and some guide from youtube

![SnipeIT Upgrade from 5 1 1 to 5 1 3  (3)](https://user-images.githubusercontent.com/81664895/113101405-42fe1c80-922f-11eb-8d4a-3ea41b03f4b7.jpg)
![SnipeIT Upgrade from 5 1 1 to 5 1 3  (2)](https://user-images.githubusercontent.com/81664895/113101411-44c7e000-922f-11eb-93ba-89288bae76a5.jpg)
![SnipeIT Upgrade from 5 1 1 to 5 1 3](https://user-images.githubusercontent.com/81664895/113101414-45607680-922f-11eb-85e5-88d91cee36fb.jpg)

There are no errors so far like stated below. Im just trying to upgrade my snipe it. I have attached the screenshot above this. Please help me take a look

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by novastream** [comment]
Does your user (administrator) have write permissions? Which user/group comes up as owner when you run ls -l when you are inside the snipe-it directory?

**Comment by karthik8223** [comment]
> Does your user (administrator) have write permissions? Which user/group comes up as owner when you run ls -l when you are inside the snipe-it directory?

Hi Jonathan, first of all thank you so much for your reply and helping me on this. I will check them and let you know. I remembered i gave admin rights to the snipe it directory, but i will recheck them and update you.

**Comment by karthik8223** [comment]
![SnipeIT Root user](https://user-images.githubusercontent.com/81664895/113672214-00828700-96ea-11eb-8b7f-e22af395d8fe.jpg)

Hi Jonathan, they are all in root access and we cant run php upgrade.php as root right ? I have to change the root user to administrator user ?

**Comment by novastream** [comment]
Correct, so you should change the owner to administrator by running:
sudo chown -R $USER:$USER /var/www/your_domain

Here is a good start how to setup a LEMP stack:
https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-ubuntu-20-04

<blockquote><img src="https://community-cdn-digitalocean-com.global.ssl.fastly.net/variants/2b3vijNShk4WqngPNwgxUmRi/035575f2985fe451d86e717d73691e533a1a00545d7230900ed786341dc3c882" width="48" align="right"><div><img src="/assets/community/favicon-16x16-ce9c1eb6d969d5b2ec276ae4b715756aa0e63106f33dc53a836687fdfee49ecd.png" height="14"> DigitalOcean</div><div><strong><a href="https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-ubuntu-20-04">How To Install Linux, Nginx, MySQL, PHP (LEMP stack) on Ubuntu 20.04 | DigitalOcean</a></strong></div><div>The LEMP software stack is a group of software that can be used to serve dynamic web pages and web applications written in PHP. This is an acronym that describes a Linux operating system, with an Nginx (pronounced like “Engine-X”) web server. The back</div></blockquote>

**Comment by karthik8223** [comment]
> Correct, so you should change the owner to administrator by running:
> sudo chown -R $USER:$USER /var/www/your_domain
> 
> Here is a good start how to setup a LEMP stack:
> https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-ubuntu-20-04

Hi Jonathan, yes. I was able to upgrade my snipeit after changing the owner to administrator. but after complete with the upgrade, I can't access the page. Please help me on where to troubleshoot. I have changed back the permission to root but still not possible to access the snipe it page.

Thank you so much for helping.

<blockquote><img src="https://community-cdn-digitalocean-com.global.ssl.fastly.net/variants/2b3vijNShk4WqngPNwgxUmRi/035575f2985fe451d86e717d73691e533a1a00545d7230900ed786341dc3c882" width="48" align="right"><div><img src="/assets/community/favicon-16x16-ce9c1eb6d969d5b2ec276ae4b715756aa0e63106f33dc53a836687fdfee49ecd.png" height="14"> DigitalOcean</div><div><strong><a href="https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-ubuntu-20-04">How To Install Linux, Nginx, MySQL, PHP (LEMP stack) on Ubuntu 20.04 | DigitalOcean</a></strong></div><div>The LEMP software stack is a group of software that can be used to serve dynamic web pages and web applications written in PHP. This is an acronym that describes a Linux operating system, with an Nginx (pronounced like “Engine-X”) web server. The back</div></blockquote>

**Comment by novastream** [comment]
When you get an error or a white page we need to take a quick look at the logs.

If you go to /var/log/ and check your apache/nginx error log and your PHP error log, do you have any errors ?

**Comment by karthik8223** [comment]
> When you get an error or a white page we need to take a quick look at the logs.
> 
> If you go to /var/log/ and check your apache/nginx error log and your PHP error log, do you have any errors ?

Hi jonathan, i should open the snipeit.error.log ? 
![Error New](https://user-images.githubusercontent.com/81664895/113677970-b7820100-96f0-11eb-834c-512c27f99822.jpg)

**Comment by karthik8223** [comment]
I opened snipeIT.error.log, it came out this.

[Tue Apr 06 07:22:53.474264 2021] [php7:error] [pid 28857] [client 192.168.1.100:63900] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: No such file or directory in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()\n#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put()\n#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever()\n#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(418): Illuminate\\Cache\\Repository->forever()\n#6 /var/www/snipeit/vendor/laravel/framewor in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133

**Comment by karthik8223** [comment]
Sorry Jonathan, i got it. it was the storage folder owner issue. I have set it to www-data. That's the reason of the error. Any idea how to change that to administrator ?

![Solved](https://user-images.githubusercontent.com/81664895/113679503-696dfd00-96f2-11eb-8b89-e32505ee3564.jpg)

**Comment by novastream** [comment]
Glad to hear that you got it working. Take a look at the link below and I think you will understand how to setup a nginx + php with an "regular" user.

https://www.getpagespeed.com/server-setup/nginx-and-php-fpm-what-my-permissions-should-be

<blockquote><img src="https://www.getpagespeed.com/wp-content/uploads/2016/09/Linux-Command-Line.jpg" width="48" align="right"><div><img src="https://www.getpagespeed.com/wp-content/uploads/2016/06/cropped-speedometer--192x192.png" height="14"> GetPageSpeed</div><div><strong><a href="https://www.getpagespeed.com/server-setup/nginx-and-php-fpm-what-my-permissions-should-be">NGINX and PHP-FPM. What my permissions should be? - GetPageSpeed</a></strong></div><div>Proper file permissions and ownership model for NGINX / PHP-FPM powered websites. The secure chmod and shown setup</div></blockquote>

**Comment by karthik8223** [comment]
Awesome will definitely look into it and big thanks to you for helping me on this. Have a great day and weekend ahead.
