### ISSUE TITLE
Mixed Content: This request has been blocked; the content must be served over HTTPS

### ISSUE THREAD

**Issue by Podolyan98** [grokability/snipe-it#9369]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I followed this [instruction](https://www.megajason.com/2020/01/07/install-snipe-it-on-ubuntu-18-04/) then configured Nginx (i.e. Reverse Proxy). But CSS and JS are not loading.

**To Reproduce**
Go to snipe-it.domain.tk and use the browser developer tools for network monitoring and resource lookup.

**Expected behavior**
CSS and JS are loaded.

**Screenshots**
![68ee1ccd-ec28-4da0-850a-bc90e19478c9](https://user-images.githubusercontent.com/68119338/113131129-7c318f00-9225-11eb-933c-35c754c4eb2f.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.3
 - OS: Ubuntu 188.04
 - Web Server: Apache2
 - PHP 7.2.24-0ubuntu0.18.04.7

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Opera
 - Version LVL2 (core: 73.0.3856.415)

**Smartphone (please complete the following information):**
 N/A

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
With `APP_TRUSTED_PROXIES=44.x.x.44`:

```
Mixed Content: The page at 'https://snipe-it.domain.tk/setup' was loaded over HTTPS, but requested an insecure stylesheet 'http://10.50.0.4:86/css/dist/all.css?id=199fdf677ce0dce6cef8'. This request has been blocked; the content must be served over HTTPS.
```

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - No
- Include the output from `php -m` (this should display what modules you have enabled.)

```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on - Ubuntu 18, Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - This  [instruction](https://www.megajason.com/2020/01/07/install-snipe-it-on-ubuntu-18-04/)
- Include what you've done so far in the installation, and if you got any error messages along the way.
Also I tried the parameter `APP_TRUSTED_PROXIES=0.0.0.0/0`:

```
GET https://10.50.0.4:86/css/dist/all.css?id=199fdf677ce0dce6cef8 net::ERR_CONNECTION_TIMED_OUT
```

- Indicate whether or not you've manually edited any data directly in the database - No

Some parameters from the file .env:

```
APP_URL=https://snipe-it.domain.tk
APP_TRUSTED_PROXIES=44.x.x.44
```

Web Server Apache2:

```
<VirtualHost *:86>
        ServerName snipe-it.domain.tk
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/snipe-it/public

        <Directory /var/www/html/snipe-it/public>
            Allow From All
            AllowOverride All
            Options -Indexes
        </Directory>
        
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

RewriteEngine on
RewriteCond %{SERVER_NAME} =snipe-it.domain.tk
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

Nginx:

```
server {
    listen 80;
    server_name snipe-it.domain.tk;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name snipe-it.domain.tk;

    location / {
       proxy_pass http://10.50.0.4:86;
       proxy_set_header X-Forwarded-Proto $scheme;
    }

    ssl_certificate /etc/letsencrypt/live/snipe-it.domain.tk/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/snipe-it.domain.tk/privkey.pem; # managed by Certbot
}
```

**Comment by chais0n** [comment]
Looks like you are running the backend SnipeIT on HTTP, but the proxied URL via HTTPS. I tried, but couldn't get it to work. Most of the how-tos I've seen, to include the Instruction link you posted, have the backend on HTTP and use an RP over HTTPS, which is a normal use-case. However, I had to host the SnipeIT backend on HTTPS along with the proxied URL to get it all working properly. 

There are some posts on here where folks got it working. It might be simpler to just host the backend on HTTPS, though. For my case, I just loaded in a self signed cert to the SnipeIT apache and called it done since I have a full SSL RP sitting in front of it.

SnipeIT documentation says this is not supported.  [Reverse Proxy page](https://snipe-it.readme.io/docs/reverse-proxies)

**Comment by snipe** [comment]
> GET https://10.50.0.4:86/css/dist/all.css?id=199fdf677ce0dce6cef8 net::ERR_CONNECTION_TIMED_OUT

It looks like the https connection isn't even working, so it would never load there. 

> There are some posts on here where folks got it working. It might be simpler to just host the backend on HTTPS, though. For my case, I just loaded in a self signed cert to the SnipeIT apache and called it done since I have a full SSL RP sitting in front of it.

This is the easiest way to handle this.
