### ISSUE TITLE
Have to manually select a value for a custom field each time an asset is opened.

### ISSUE THREAD

**Issue by RousePartnersLLP-DB** [grokability/snipe-it#9370]
Description:

Open up any asset with a custom field selected. We have to select a value for the custom field every time we open an asset, the last selection is not retained.

More Detail:

We have a custom field setup for the 2 digit encryption prefix we use for device encryption. The values are hexadecmial based values 00-FF. The field is setup as a dropdown list and is assigned against laptops and desktops.

Versions:
v5.1.3 build 5862
PHP 7.4.16
Laravel 6.20.16

Accessing from: Any OS or device.

**Comment by RousePartnersLLP-DB** [comment]
It's simple to reproduce. Create a custom field with a dropdown list and hex values (00-FF). Apply that to an asset trype, create an asset of that type. In our case the data is encrypted and required. Edit the asset select a value and save. then edit again. The software asks you to reselect a value rather than keeping the last selected value.

**Comment by RousePartnersLLP-DB** [comment]
Looking a little further... it looks like the DB is storing them with strange really long text strings.

For one asset, the value is "53" without quotes.
But in the asset history its: eyJpdiI6Im0yTUR3SjFNS3BIdEJPeXVYTkNNNUE9PSIsInZhbHVlIjoiRnZob3ExRGRhdGVFK3VMUlpHYWNJQT09IiwibWFjIjoiY2Q1YWFhNmIyZWNkYzExMDdmMWMwNzM1MTNmYjdhMDcyODU1NWY1MzEwZmJlMDUyMjhmMGU2ODlmMWQxOGVlZiJ9

Tried changing the value from a list box to a text field, this seems to solve the issue of having to re-type the value in when editing an asset. But the background value is still a ridiculously long string even if we change the value, save, then change back and save again.

When saving a change that is just two digits, for example 3E, we get the following error messages:

2 digit prefix for ESET FDE Encryption Passwords, use the next unused prefix for specific asset type (increment by 1 from the highest existing asset number of a specific asset type).
The encryption prefix 2 may only contain letters and numbers.

It seems like the custom field function is just broken as it creates a difference between the value entered, and the value stored in the database, but then errors based on the incorrect value of the database.

**Comment by RousePartnersLLP-DB** [comment]
When will I get a response on this issue please?

**Comment by snipe** [comment]
You'll get a response when we have a moment to look into it. We appreciate your patience.

**Comment by snipe** [comment]
This issue has been fixed and merged into the `master` branch, and will be in the next release.

![trek-nods](https://user-images.githubusercontent.com/197404/47946205-b9af5800-dec5-11e8-85af-fce7915a0938.gif)
