### ISSUE TITLE
Can't contact LDAP server

### ISSUE THREAD

**Issue by andreaci** [grokability/snipe-it#9372]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
LDAP sync always give error:
 Error getting users from LDAP directory, error: ldap_search(): Search: Can't contact LDAP server
When connecting to Active Directory.
It connects correctly to server (the error is different if I write an incorrect user/password), but I cannot sync

**To Reproduce**
1. LDAP Settings
2. 
    LDAP Enabled: true
    password sync: true
    This is an AD server: true
    AD domani: domain.local
    Append domain: true
    LDAP Server: ldap://domain.local
    UseTLS: false
    Allow Invalid SSL: true
    username: user@domain.local
    password: <password>
    base bind: CN=Users,DC=domain,DC=local
    
    Username Field: samaccountname
    Last Name: sn
    LDAP First Name: givenname
    LDAP Authentication query: uid=samaccountname
    LDAP Version: 3
    LDAP Active Flag: sn
    LDAP Employee Number: employeeNumber
    LDAP Email: email

    
3. Save
4. Click Test
5. See error

**Screenshots**
![2021-03-31_15-27-49](https://user-images.githubusercontent.com/8290389/113152479-755f4800-9236-11eb-99c5-e59ace3353c6.png)

![2021-03-31_15-33-53](https://user-images.githubusercontent.com/8290389/113152529-83ad6400-9236-11eb-84bb-63aed7533524.png)

**Server (please complete the following information):**
 - Snipe-IT v5.1.4 build 5886
 - OS: Windows 2019 standard
 - Web Server: IIS
 - PHP Version 7.2.34 

**Error Messages**
Included in the screenshot above.
No error in log file.

Obviously the same settings work in other applictions (GitLab on premise and LDAP Browser)

**Comment by andreaci** [comment]
The problem is with the "LDAP filter":
it's mandatory, also if the web interface doesn't ask for it.

putting &(cn=*) as default works.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
