### ISSUE TITLE
Swagger documentation (hardware/{id}/checkout) missing required query params

### ISSUE THREAD

**Issue by trentontrees** [grokability/snipe-it#9382]
**Describe the bug**
In the API document ( https://snipe-it.readme.io/reference#hardwareidcheckout ) there are query parameters that are required that are not defined.  The enum of `checkout_to_type` needing `asset`, `location`,  or `user`.  The `assigned_usesr`, `assigned_asset`, `assigned_location` corresponding to `checkout_to_type`

**Why no PR**
I'm extremely new to snipe-it and I'm not sure how to update the Swagger/doxygen doc that is being used by readme.io.  And I've failed to determine how to generate the document locally.  I'm more than happy to submit a PR, but I'll need some guidance.  Alternatively, if this gets fixed by someone else I can look at their PR and follow the pattern for other issues.

**Comment by snipe** [comment]
So, here's the wild thing... We actually do have those marked as required. (They're body parameters, not path parameters.) But for some reason Readme.Io isn't showing them.

<img width="957" alt="Screen Shot 2021-04-06 at 9 07 40 AM" src="https://user-images.githubusercontent.com/197404/113742639-a963be80-96b7-11eb-9cf6-0edfab6e6b94.png">

I'm investigating this further.

**Comment by snipe** [comment]
Re: patterns for other updates, you can just use the "Suggest Edits" link in the Documentation website.

**Comment by snipe** [comment]
Looks like they were doing some weird caching on their side. It's updated now.
