### ISSUE TITLE
LDAP First Name field null with valid configuration

### ISSUE THREAD

**Issue by innowintay** [grokability/snipe-it#9388]
#### Expected Behavior (or desired behavior if a feature request)

LDAP successfully synchronizes with valid configuration

-----

#### Actual Behavior

LDAP fails to sync because it appears the First Name field is null for all users. LDAP configuration has "givenName" populated as the First Name LDAP field and is correct. Validated that data does appear in our Active Directory in the givenName field. No changes to AD permissions have been made. Sync last worked successfully before we upgraded to the 5.1.3 docker image (I do not recall the previous version, unfortunately).
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- - No
- Version of Snipe-IT you're running
- - v5.1.3 build 5862 (gc3871c98d)
- Version of PHP you're running
- - 7.2.24-0ubuntu0.18.04.7
- Version of MySQL/MariaDB you're running
- - 5.6
- What OS and web server you're running Snipe-IT on
- - Running the Docker image from snipe/snipe-it:v5.1.3
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- - Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- - No errors indicated. 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- - /users/ldap
- - Click "Synchronize"
- - Receive message that LDAP Import was successful
- - Review results... all users appear with null values for First Name and note indicates first name is required.
- If a stacktrace is provided in the error, include that too.
- - N/A
- Any errors that appear in your browser's error console.
- -
```Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Feature-Policy header: Unrecognized feature: 'animations'.
Error with Feature-Policy header: Unrecognized feature: 'battery'.
Error with Feature-Policy header: Unrecognized feature: 'display-capture'.
Error with Feature-Policy header: Unrecognized feature: 'legacy-image-formats'.
Error with Feature-Policy header: Unrecognized feature: 'oversized-images'.
Error with Feature-Policy header: Unrecognized feature: 'publickey-credentials'.
Error with Feature-Policy header: Unrecognized feature: 'unsized-media'.
Error with Feature-Policy header: Unrecognized feature: 'vibrate'.
Error with Feature-Policy header: Unrecognized feature: 'wake-lock'.
[Violation] Forced reflow while executing JavaScript took 106ms
```
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- - Unable to test. No LDAP sync configured on demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- - No applicable messages
- Include what you've done so far in the installation, and if you got any error messages along the way.
- - N/A
- Indicate whether or not you've manually edited any data directly in the database
- - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by uberbrady** [comment]
Try spelling it in all lower-case - `givenname`

**Comment by innowintay** [comment]
That worked. I certainly didn't expect it to work since the LDAP attribute has the capitalized N. Thanks!
