### ISSUE TITLE
Custom field list data change

### ISSUE THREAD

**Issue by serkanyardim** [grokability/snipe-it#9389]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

I added a custom field as a list data. Entered some data as list.
Later i used datas in assets. For example: 

GRUPNAME:  field name, and list box:  apple, banana

Later i changed field data, like:  apple >> will be apples 

I mean i changed.  I expect here all the assets used GRUPNAME and selection "apple" will be "apples".

But not. It dont update.. 

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
It would be impossible and ill-advised for us to bulk edit asset data like that. I just don't see a way to pull that off without mangling data in ways users aren't expecting.
