### ISSUE TITLE
Restore a backup

### ISSUE THREAD

**Issue by fam4r** [grokability/snipe-it#9394]
**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.4 - build 5886 (master)
 - OS: [e.g. Ubuntu, CentOS]: see docker image snipe/snipe-it
 - Web Server: [e.g. Apache, IIS]: see docker image snipe/snipe-it
 - PHP Version: see docker image snipe/snipe-it

It would be nice to have a restore functionality easy-to-use as the backup one.

Moreover, the restore procedure is not documented at all, and searching into GitHub issues is not an option (https://github.com/snipe/snipe-it/issues/9295#issuecomment-799523881).

**Comment by snipe** [comment]
Unfortunately, the backup package we use doesn't have any (that I could find) way to restore from a previous backup.

**Comment by privateer00** [comment]
found this old issue.
i'm in the same situation but i successfully restored my backup with one command from the inside of the container.

`php artisan snipeit:restore path/to/backup.zip`

everything was restored but the users.

**Comment by insert-waffle** [comment]
> found this old issue. i'm in the same situation but i successfully restored my backup with one command from the inside of the container.
> 
> `php artisan snipeit:restore path/to/backup.zip`
> 
> everything was restored but the users.

confirmed this still works as of 18th of februari 2022. 
@snipe is there any feature planned to easily restore these backups from the GUI?

**Comment by uberbrady** [comment]
Yes, there is. That's a pending feature in v6. Ideally, you just click a button and it does a full restore.

**Comment by snipe** [comment]
It’s not even a planned feature - it is a feature in v6, already accepted into the RC.
