### ISSUE TITLE
generate QR-Codes with APP_URL

### ISSUE THREAD

**Issue by kldrvoe** [grokability/snipe-it#9402]
#### Expected Behavior (or desired behavior if a feature request)

I have changed APP_URL from URL without Domain Suffix to URL with complete Domain Suffix.
I expected that I can now generate only QR-Codes with complete URL including Domain suffix

-----

#### Actual Behavior

If I connect to Snapeit without Domain Suffix, it generates QR-Codes without Domain Suffix, however
if I connect to Snapeit with Domain Suffix in URL then it generates QR-Codes with Domain Suffix,
so it depends on the called URL, not in the APP_URL proposed in the configuration

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh installation
- Version of Snipe-IT you're running  - version 5.1.3 build 5862
- Version of PHP you're running - version 7.3.27
- Version of MySQL/MariaDB you're running MySQL 5.3
- What OS and web server you're running Snipe-IT on - Docker container linuxserver/snipe-it (alpine, nginx)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - ansible with docker-compose
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - not reproducable on demo
- Include any additional information you can find in `storage/logs` and your webserver's logs. - nothing in the logs
- Include what you've done so far in the installation, and if you got any error messages along the way. - standard installation
- Indicate whether or not you've manually edited any data directly in the database - no changes in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
What do you have your APP_URL set to, and what is an example, of the URL that's being generated? Also have you cleared your config cache and barcode cache since you made the change?

**Comment by snipe** [comment]
(Also, the app is called Snipe-IT, not Snapeit, FYI.)

![300px-Severus_snape](https://user-images.githubusercontent.com/197404/113709054-e79cb600-9696-11eb-87fc-e7486495d859.jpg)

**Comment by kldrvoe** [comment]
My App-URL was web-snipeit in my local domain mgh.kliniken-dr-voetisch.de.

I wanted to see the asset with my smartphone, so I generated QR-Codes to have access.

What I saw was an error on my smartphone, because the smartphone does not have a DNS Suffix set.

So I changed the App-URL to web-snipeit.mgh.kliniken-dr-voetisch.de this restarts the docker containers automatically, the config cache is cleared too.

I started with web-url http://web-snipeit:8080, deleted the barcode cache and regenerated the barcodes – they were the same as before.

I started with web-url http://web-snipeit.mgh.kliniken-dr-voetisch.de:8080, deleted the barcode cache and regenerated the barcodes – the barcodes had the correct url for the smartphone.

I started with web-url http://web-snipeit:8080 again, deleted the barcode cache and regenerated the barcodes – they were without DNS Suffix.

 

Best regards

Herbert Lischka

 

Von: snipe ***@***.*** 
Gesendet: Dienstag, 6. April 2021 14:11
An: snipe/snipe-it
Cc: kldrvoe; Author
Betreff: Re: [snipe/snipe-it] generate QR-Codes with APP_URL (#9402)

 

What do you have your APP_URL set to, and what is an example, of the URL that's being generated? Also have you cleared your config cache and barcode cache since you made the change?

**Comment by snipe** [comment]
> smartphone does not have a DNS Suffix set.

I don't know what that means.

> My App-URL was web-snipeit in my local domain mgh.kliniken-dr-voetisch.de.

`web-snipeit` would never work unless you had DNS set up on your local network for that domain, and you'd have to be in your local network for that to work.

> I started with web-url http://web-snipeit:8080 again, deleted the barcode cache and regenerated the barcodes – they were without DNS Suffix.

Again, this would be the same DNS issue as before. You'd need to hav e that set up in your network's DNS.

> I started with web-url http://web-snipeit.mgh.kliniken-dr-voetisch.de:8080, deleted the barcode cache and regenerated the barcodes – the barcodes had the correct url for the smartphone.

Sounds like you need to set up DNS for your instance. DNS is what tells a computer that `foo.blah.com` should point to a specific IP address. 

This is a networking issue, not a Snipe-IT question. I've included a few basic suggestions below, but If you're still stuck, you can try googling "Setting up DNS" and try to narrow it down based on your needs.

Firstly, you can run Snipe-IT using just an IP address. Just make sure the `APP_URL` in your `.env` correctly reflects the IP address.

But if you want to access Snipe-IT through a name, instead of an IP address, it depends on what your environment is and what you're looking for.

### Snipe-IT accessed ONLY by YOUR computer... 

You can add a line in the `/etc/hosts` file of whatever computer on the network needs to access it that points whatever name you want to the IP. That would look something like this in your `/etc/hosts` file:

```
192.168.1.2 snipe-it.local
```

(assuming your Snipe-IT instance's IP is `192.168.1.2` and the name you want to use to access it is `snipe-it.local`.) 

### Snipe-IT accessible to ONLY those in your internal network...

For example, if you're running Snipe-IT on a private, internal IP that cannot be reached outside of your network, contact your network administrator and ask them to set up DNS for the IP of your instance. 

### Snipe-IT accessible to the entire internet

You'll need to make sure the IP address for your instance is accessible outside of your network. (For example, IP addresses that start with `127.0.*.*` or `192.168.1.*` are internal and cannot be accessed outside of the network they live on.)

If the IP address is an externally facing IP address and you want to use something like `assets.mycompany.com`, you'll need to have whoever manages the domain name for `mycompany.com` set up an A record pointing `assets.mycompany.com` to your Snipe-IT external IP address.

**Comment by kldrvoe** [comment]
My local domain is an active directory domain with DHCP and DNS Servers.

The local PCs have dns suffix set to mgh.kliniken-dr-voetisch.de, they can resolve http://web-snipeit:8080 to have access to snipe-it.

My smartphone has access to local w-lan but it cannot get a default dns suffix, so I cannot resolve http://web-snipeit:8080 but I must have http://web-snipeit.mgh.kliniken-dr-voetisch.de:8080  as URL in the QR-Code.

If I connect to snipe-it with the shortcut, then the shortcut will be generated as QR-Code and this does not work for the smartphones and tablets in the local w-lan, because they have no dns suffix set. They definitely need the complete URL.

However if I connect with http://web-snipeit.mgh.kliniken-dr-voetisch.de:8080 to snape-it, then it generates the correct URL in QR-Code.

 

I think, the only problem is, that snipe-it takes the URL of it’s URL to go to the page and not the APP_URL set in the configuration to generate the QR-Codes.

 

Best regards

Herbert Lischka

 

Von: snipe ***@***.*** 
Gesendet: Dienstag, 6. April 2021 14:34
An: snipe/snipe-it
Cc: kldrvoe; Author
Betreff: Re: [snipe/snipe-it] generate QR-Codes with APP_URL (#9402)

 

smartphone does not have a DNS Suffix set.

I don't know what that means.

My App-URL was web-snipeit in my local domain mgh.kliniken-dr-voetisch.de.

web-snipeit would never work unless you had DNS set up on your local network for that domain, and you'd have to be in your local network for that to work.

I started with web-url http://web-snipeit:8080 again, deleted the barcode cache and regenerated the barcodes – they were without DNS Suffix.

Again, this would be the same DNS issue as before. You'd need to hav e that set up in your network's DNS.

I started with web-url http://web-snipeit.mgh.kliniken-dr-voetisch.de:8080, deleted the barcode cache and regenerated the barcodes – the barcodes had the correct url for the smartphone.

Sounds like you need to set up DNS for your instance. DNS is what tells a computer that foo.blah.com should point to a specific IP address.

This is a networking issue, not a Snipe-IT question. I've included a few basic suggestions below, but If you're still stuck, you can try googling "Setting up DNS" and try to narrow it down based on your needs.

Firstly, you can run Snipe-IT using just an IP address. Just make sure the APP_URL in your .env correctly reflects the IP address.

But if you want to access Snipe-IT through a name, instead of an IP address, it depends on what your environment is and what you're looking for.


Snipe-IT accessed ONLY by YOUR computer...


You can add a line in the /etc/hosts file of whatever computer on the network needs to access it that points whatever name you want to the IP. That would look something like this in your /etc/hosts file:

192.168.1.2 snipe-it.local
 

(assuming your Snipe-IT instance's IP is 192.168.1.2 and the name you want to use to access it is snipe-it.local.)


Snipe-IT accessible to ONLY those in your internal network...


For example, if you're running Snipe-IT on a private, internal IP that cannot be reached outside of your network, contact your network administrator and ask them to set up DNS for the IP of your instance.


Snipe-IT accessible to the entire internet


You'll need to make sure the IP address for your instance is accessible outside of your network. (For example, IP addresses that start with 127.0.*.* or 192.168.1.* are internal and cannot be accessed outside of the network they live on.)

If the IP address is an externally facing IP address and you want to use something like assets.mycompany.com, you'll need to have whoever manages the domain name for mycompany.com set up an A record pointing assets.mycompany.com to your Snipe-IT external IP address.

**Comment by snipe** [comment]
> I think, the only problem is, that snipe-it takes the URL of it’s URL to go to the page and not the APP_URL set in the configuration to generate the QR-Codes.

I don't know what that means. It takes the URL of it's URL?

The line that generates the QR code is:

```php
$barcode_obj =  $barcode->getBarcodeObj($settings->barcode_type, route('hardware.show', $asset->id), $size['height'], $size['width'], 'black', array(-2, -2, -2, -2));
```

Unless you're running behind a weird proxy or something, ` route('hardware.show', $asset->id)` should return the correct hardware URL. If it didn't, URLs would break anywhere we use that route. 

> However if I connect with http://web-snipeit.mgh.kliniken-dr-voetisch.de:8080 to snape-it, then it generates the correct URL in QR-Code.

So then use that longer url? I'm not exactly sure what to tell you here.

**Comment by kldrvoe** [comment]
My problem is: today I know that I have to access snipe-it with the long address; in a few months I'll substitute some PC's generate new labels glue them on the PC's, deliver them somewhere in the campus and if I accessed snape-it with the shortcut then I'll get in trouble....
If it is easy to use APP_URL instead of route('hardware.show' then please have a try....
