### ISSUE TITLE
Unable to email after upgrade, from email set in env file. 

### ISSUE THREAD

**Issue by NsteinSFC** [grokability/snipe-it#9403]
#### Please confirm you have done the following before posting your bug report:

- [Y ] I have enabled debug mode 
- [Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading to v5.1.4 build 5886 (running on Windows 2012R2. PHP 7.4.16 I'm unable to send emails about expiring licenses. When running snipeit:expiring-alerts I receive 
Swift_TransportException  : Cannot send message without a sender address
 at C:\inetpub\wwwroot\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:195
    191|             }
    192|         }
    193|
    194|         if (!$reversePath = $this->getReversePath($message)) {
  > 195|             $this->throwException(new Swift_TransportException('Cannot send message without a sender address'));
    196|         }
    197|
    198|         $to = (array) $message->getTo();
    199|         $cc = (array) $message->getCc();

  Exception trace:

  1   Swift_Transport_AbstractSmtpTransport::send()
      C:\inetpub\wwwroot\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php:71

  2   Swift_Mailer::send()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php:488

  3   Illuminate\Mail\Mailer::sendSwiftMessage()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php:261

  4   Illuminate\Mail\Mailer::send()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php:65

  5   Illuminate\Notifications\Channels\MailChannel::send()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php:148

  6   Illuminate\Notifications\NotificationSender::sendToNotifiable()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php:106

  7   Illuminate\Notifications\NotificationSender::Illuminate\Notifications\{closure}()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php:19

  8   Illuminate\Notifications\NotificationSender::withLocale()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php:109

  9   Illuminate\Notifications\NotificationSender::sendNow()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php:79

  10  Illuminate\Notifications\NotificationSender::send()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php:39

  11  Illuminate\Notifications\ChannelManager::send()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:261

  12  Illuminate\Support\Facades\Facade::__callStatic()
      C:\inetpub\wwwroot\snipe-it\app\Console\Commands\SendExpirationAlerts.php:65

  13  App\Console\Commands\SendExpirationAlerts::handle()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36

  14  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php:37

  15  Illuminate\Container\Util::unwrapIfClosure()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:93

  16  Illuminate\Container\BoundMethod::callBoundMethod()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37

  17  Illuminate\Container\BoundMethod::call()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php:590

  18  Illuminate\Container\Container::call()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php:134

  19  Illuminate\Console\Command::execute()
      C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php:255

  20  Symfony\Component\Console\Command\Command::run()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php:121

  21  Illuminate\Console\Command::run()
      C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php:1009

  22  Symfony\Component\Console\Application::doRunCommand()
      C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php:273

  23  Symfony\Component\Console\Application::doRun()
      C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php:149

  24  Symfony\Component\Console\Application::run()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php:93

  25  Illuminate\Console\Application::run()
      C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:131

  26  Illuminate\Foundation\Console\Kernel::handle()
      C:\inetpub\wwwroot\snipe-it\artisan:35

My env file: 

MAIL_MAILER=smtp
MAIL_HOST=XXXXXX.mail.protection.outlook.com
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=snipe-it@XXXXX
MAIL_FROM_NAME="${APP_NAME}"

I already did:
php artisan config:clear
php artisan cache:clear
php artisan config:cache

Thanks for any pointers

**Comment by snipe** [comment]
I'd imagine you need to set a username, password and encryption type

**Comment by NsteinSFC** [comment]
We using this as a proxy server with authentication on our mail gateway. I had this config working before the upgrade, not sure why it's not seeing it as from mail set.

**Comment by deivishome** [comment]
Hi, in my env username and password does not have null:
MAIL_DRIVER=smtp
MAIL_HOST=192.168.xx.xxx
MAIL_PORT=25
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=snipeit@zzzzz.com
MAIL_FROM_NAME='XXXXX XXXXX XXXXX'
MAIL_REPLYTO_ADDR=kkk.zzz@zzzzz.com
MAIL_REPLYTO_NAME='Administrador XXXXXXXX'
MAIL_AUTO_EMBED_METHOD='attachment'

**Comment by NsteinSFC** [comment]
Thank you deivishome I copied yours and changed to my server/email address and it worked. Not sure what was the culprit. I had u and pw with and without null and it didn't work either way before. Maybe before coping the entire block there was a trailing space...
Glad it's working now though.
