### ISSUE TITLE
API Request: Accessory Checkout

### ISSUE THREAD

**Issue by markbrule** [grokability/snipe-it#9404]
**Server (please complete the following information):**
 - Snipe-IT Version: 5.1.4
 - OS: Ubuntu 20.04 LTS
 - Web Server: apache2
 - PHP Version: 7.4.3

**Is your feature request related to a problem? Please describe.**
I need to set the "note" field when checking out an Accessory through the API.

**Describe the solution you'd like**
Add the ability to include a "note" member to the JSON POST payload on /api/v1/accessories/:id/checkout

**Describe alternatives you've considered**
Can't see a way to accomplish this.

**Additional context**
One additional line need in AccessoriesController::checkout

![image](https://user-images.githubusercontent.com/8799594/113755591-5a248a80-96c5-11eb-962b-e4a28257ae1e.png)

**Comment by snipe** [comment]
Thanks for this bug report! This issue has been fixed and merged into the `develop` branch, and will be in the next release.

![trek-nods](https://user-images.githubusercontent.com/197404/47946205-b9af5800-dec5-11e8-85af-fce7915a0938.gif)
