### ISSUE TITLE
Consumable 》Checkout 》 Quantity

### ISSUE THREAD

**Issue by oyport** [grokability/snipe-it#9406]
i 'm sorry ，can not speak English
Consumable 》Checkout  》Quantity 

Now：
Cardstock (White)
Select a User：
Notes：

Hope to add function：
Select a User：
Quantity：  （new）
Notes：

**Comment by tmuras** [comment]
So this must be about providing a way to check-out more than 1 consumable at the time.
I think this would be very helpful - it's difficult to manage when there are 10+ consumables checked-out at the same time.

**Comment by snipe** [comment]
This is actually a duplicate of #5176
