### ISSUE TITLE
Still use printed QR-labels with old IP adress ?

### ISSUE THREAD

**Issue by Mandy1959** [grokability/snipe-it#9408]
#### Expected Behavior (or desired behavior if a feature request)

Hello
Maybe somebody can help me. We moved our Snipe-IT to a new server, new IP.  Old QR label, for instance, 172.17.2.111/hardware/671. New server IP say 172.17.2.222. Is there any chance I still can scan the old labels and get the correct articel after all without reprinting the labels ?

Thanks a lot in advance for any help.
Cheers
Andy

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Upgrade
- Version of Snipe-IT you're running
- 5.1.4 build 5886
- Version of PHP you're running
- 7.4.13
- Version of MySQL/MariaDB you're running
- 10.5.8
- What OS and web server you're running Snipe-IT on
- Windows Server 2019
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by uberbrady** [comment]
The QR code embeds the full URL in it, so that would include the IP address. The only other thing you might be able to do is put a webserver of some sort at the old IP address and have it respond with redirects to the new IP.

You should probably also create a proper domain name for the new IP address so that if you *do* have to move again, all you'll have to change is the DNS record.

**Comment by Mandy1959** [comment]
Thanks a lot, uberbrady, for the fast response and the recommendations. Will check then what I can do with redirect, and good hint with the new domain name.

**Comment by yosiasz** [comment]
Is the previous server now being used for something else or decommissioned?

**Comment by Mandy1959** [comment]
Thanks for your response. It will be decommissioned soon after the new one takes place. Von meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Yosi ***@***.***>Datum: Sa., 17. Apr. 2021, 16:46An: snipe/snipe-it ***@***.***>Cc: Mandy1959 ***@***.***>, Author ***@***.***>Betreff: Re: [snipe/snipe-it] Still use printed QR-labels with old IP adress ? (#9408)
Is the previous server now being used for something else or decommissioned?

**Comment by yosiasz** [comment]
Then swap the ip addresses. Make new server have previous server's ip and give the old server a different ip

**Comment by Mandy1959** [comment]
Thanks for that suggestion. Unfortunately does our IT add new servers with new matching names belonging to the IP, I cannot change the rules here.

**Comment by snipe** [comment]
I’m sorry you’re in this situation, but this seems to be more of an internal politics/networking issue than a Snipe-IT issue :(
