### ISSUE TITLE
FreeIPA - LDAP Sync works, login doesn't - Unable to validate user credentials

### ISSUE THREAD

**Issue by Gargravarr2112** [grokability/snipe-it#9410]
- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to authenticate against FreeIPA directory server (via LDAP), users always receive Username or password incorrect. LDAP Sync with the same configuration works correctly.

**To Reproduce**
1. Go to Admin
2. Click on LDAP
3. Scroll down to Test LDAP Login, enter credentials and click Test LDAP
4. See error "Unable to validate user credentials!"

Alternatively:
1. Log in with valid FreeIPA credentials
2. See error "The username or password is incorrect"

**Expected behavior**
User logged in

**Screenshots**
LDAP configuration (Active Directory is NOT ticked):
![Screenshot from 2021-04-07 17-50-17](https://user-images.githubusercontent.com/2163696/113906165-e02af900-97cb-11eb-9321-4f1256d8d6c5.png)

**SnipeIT Server (please complete the following information):**
 - Snipe-IT Version 5.0.12 build 5705
 - OS: Devuan 3.0
 - Web Server: Apache2
 - PHP Version 7.3.27-1

**FreeIPA Server**
- FreeIPA Version: 4.8.7-14
- OS: CentOS 8

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 87

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
HTTP 400 error returned when clicking 'Test LDAP', no further text
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No, site-specific LDAP
- Include any additional information you can find in `storage/logs` and your webserver's logs.
Error when clicking 'Test LDAP':
`"POST /snipeit/api/v1/settings/ldaptestlogin HTTP/1.1" 400 1995`
- Include the output from `php -m` (this should display what modules you have enabled.)
```
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Additional context**
- Is this a fresh install or an upgrade?
Fresh install
- What OS and web server you're running Snipe-IT on
Devuan 3.0 with Apache 2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual, bare metal
- Include what you've done so far in the installation, and if you got any error messages along the way.
Followed instructions in Common Issues - cleared cache, re-ran upgrade.php.
Tried several variations of LDAP options, including 'LDAP Authentication query - cn=' and using full name, adding more fields (Active Flag, Employee Number), changing LDAP Object Class from posixAccount to shadowAccount.
- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by kzltp** [comment]
I have same issue. Can you solve it?

**Comment by sunflowerbofh** [comment]
Same problem for us. We use an open ldap server, Test LDAP Sync works, but Test LDAP Login shows "_Unable to validate user credentials!_".
The snipeit version is Version v5.1.8 - build 6227 (master).
Enabling debugging does not show any logs. On the ldap server you can see in the logs:
```
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 fd=15 ACCEPT from IP=[2aXX:XXXX:5::95]:55632 (IP=[::]:636)
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 fd=15 TLS established tls_ssf=256 ssf=256
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 op=0 BIND dn="cn=srv-idm-sync,ou=srv-account,dc=ourdomain" method=128
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 op=0 BIND dn="cn=srv-idm-sync,ou=srv-account,dc=ourdomain" mech=SIMPLE ssf=0
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 op=0 RESULT tag=97 err=0 text=
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 op=1 BIND anonymous mech=implicit ssf=0
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 op=1 do_bind: invalid dn (foobar)
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 op=1 RESULT tag=97 err=34 text=invalid DN
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 op=2 BIND dn="cn=srv-idm-sync,ou=srv-account,dc=ourdomain" method=128
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 op=2 BIND dn="cn=srv-idm-sync,ou=srv-account,dc=ourdomain" mech=SIMPLE ssf=0
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 op=2 RESULT tag=97 err=0 text=
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 op=3 UNBIND
Aug 16 12:28:31 node2 slapd[2459643]: conn=31386 fd=15 closed
```
The LDAP settings are:
```
LDAP Integration:           LDAP enabled
LDAP Password Sync:         - (does not matter is Yes or empty)
Active Directory:           This is an Active Directory server
Active Directory domain:    -
Append domain name:         -
LDAP Server:                ldap://ldap.our.domain:636
Use TLS:                    -
LDAP SSL certificate validation: -
LDAP Bind Username:         cn=srv-idm-sync,ou=srv-account,dc=ourdomain
LDAP Bind Password:         topsecret
Base Bind DN:               dc=ourdomain
LDAP Filter:                &(objectClass=person)(memberOf=cn=IDM.ser-its.pers-vma,ou=...,dc=ourdomain)(cn=*)
Username Field:             uid
Last Name:                  sn
LDAP First Name:            givenname
LDAP Authentication query:  uid=
LDAP Version:               3
LDAP Active Flag:           -
LDAP Employee Number:       -
LDAP Department_            Department
LDAP Email:                 mail
LDAP Telephone Number:      telephonenumber
LDAP Job Title:             title
LDAP Country:               -
```
We have other appliances with same settings for which the ldap server works.
Like that we can't introduce snipeit in our production environment because LDAP login is a base demand.

**Comment by sunflowerbofh** [comment]
Update: After studying the app/Services/ source code and logs on our ldap server and trying around a lot I found a solution:
The snipeit ldap client composes an ldap bind dn for each authentication out of **BaseBindDN** and **LDAPAuthenticationQuery**.
E.g. when you do an ldapsearch for a certain user and you get as result the dn:
_dn: cn=foobar,ou=Staff,ou=Accounts,dc=ourdomain_
you have to make the following settings:
```
Base Bind DN:  ou=Staff,ou=Accounts,dc=ourdomain
LDAP Authentication query: cn=
```
(Leave the ActiveDirectory and Append domain name unchecked as it is a standard ldap server.)
If you only enter "dc=ourdomain" as Bind DN you can do the ldap sync, but won't be able to login.

I must say I find this behavior rather strange and have never seen something like that in all of our other ldap connected appliances.
