### ISSUE TITLE
Cannot set Custom field regex via API

### ISSUE THREAD

**Issue by fabricat** [grokability/snipe-it#9415]
#### Please confirm you have done the following before posting your bug report:

- [ ] **(n/a)** I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I use API to create a new custom field with *regex* validation, I get the error `"format":["The selected format is invalid."]`.

**To Reproduce**
1. Go to https://snipe-it.readme.io/reference#fields-2
2. Fill the BODY PARAMS with:\
 name="Regex test" 
 element="text"
 format="regex:/^[0-9]{8}$/"
3. Check on the right panel, the `cURL` command should end like this:  \
`--data {"show_in_email":false,"field_encrypted":false,"element":"text","name":"Regex test","format":"regex:/^[0-9]{8}$/"}`
4. Click on the `Try It` button
5. See error message (relative to the `format` field): \
"The selected format is invalid"

The same happens on my local Docker installation (image `snipe/snipe-it:v5.1.4`).

**Expected behavior**
The custom field should be correctly created.

**Screenshots**
![api-curl-error](https://user-images.githubusercontent.com/1492255/114068310-133dbd00-989e-11eb-8f6a-85425ee5b5ac.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.4
 - OS: Docker official image
 - Web Server: Docker official image
 - PHP Version: Docker official image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 87

**Smartphone (please complete the following information):**
n/a

**Error Messages**
The cURL output is:
`{"status":"error","messages":{"format":["The selected format is invalid."]},"payload":null}`

**Additional context**
- Fresh install
- Installed via Docker

**Comment by viclou** [comment]
FD20573
