### ISSUE TITLE
I cannot upload files to assets

### ISSUE THREAD

**Issue by hmacugova** [grokability/snipe-it#9440]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I cannot upload picture (.jpg 2,1MB) for my asset

**To Reproduce**
1. Go to 'some asset'
2. Click on 'upload and select file'
3. Scroll down to 'write notes and select upload'
4. See error -  "Error: Please check the form below for errors" "The image failed to upload."

**Expected behavior**
Successful upload of files

**Screenshots**
![obrázok](https://user-images.githubusercontent.com/74250943/114885022-8ac39d00-9e06-11eb-89fd-327a32e17513.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.3 build 5862 (gc3871c98d) 
 - OS: [e.g. Ubuntu, CentOS] debian 10
 - Web Server: [e.g. Apache, IIS] apache2
 - PHP Version 7.4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10
 - Browser [e.g. chrome, safari] chrome, firefox

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] huawei
 - OS: [e.g. iOS8.1] android
 - Browser [e.g. stock browser, safari] firefox/chrome

**Error Messages**
no additional error log

**Additional context**
- Is this a fresh install or an upgrade?  After Upgrade
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
The method that is likely kicking in here is:

```php
public static function file_upload_max_size() {
        static $max_size = -1;

        if ($max_size < 0) {

            // Start with post_max_size.
            $post_max_size = Helper::parse_size(ini_get('post_max_size'));
            if ($post_max_size > 0) {
                $max_size = $post_max_size;
            }

            // If upload_max_size is less, then reduce. Except if upload_max_size is
            // zero, which indicates no limit.
            $upload_max = Helper::parse_size(ini_get('upload_max_filesize'));
            if ($upload_max > 0 && $upload_max < $max_size) {
                $max_size = $upload_max;
            }
        }

        return $max_size;
    }
```

Can you ell me what your `upload_max_filesize` and `post_max_size` are in your php.ini file?

**Comment by hmacugova** [comment]
Hi, the upload_max_filesize and post_max_size I have 8M both.

**Comment by snipe** [comment]
If you go to https://htmlstrip.com/mime-file-type-checker and upload the file, and click on "find mime type", what is the result you see on that page?

<blockquote><div><strong><a href="https://htmlstrip.com/mime-file-type-checker">MIME File Type Checker - Validate What File is Online Free - HTMLStrip</a></strong></div></blockquote>

**Comment by hmacugova** [comment]
Hi,
I can see: file type is "image/jpeg".

**Comment by snipe** [comment]
If you try to upload an image under 2MB, what happens?

**Comment by hmacugova** [comment]
I was successful with upload image with 120KB

**Comment by Jaspotn0612** [comment]
Just reporting that I have this issue when trying to upload a 5.1MB file under a license. I am able to upload PDFs of a smaller size.

**Comment by Jaspotn0612** [comment]
I created some dummy files for testing and with a file <2MB, no error however with a file that is 2.86MB, I get the error
![image](https://user-images.githubusercontent.com/61034807/129837524-042685cd-8dd9-4b18-b823-db99edebd379.png)
![image](https://user-images.githubusercontent.com/61034807/129837546-8f988e2b-bc24-496a-8e5f-a4f19e85a348.png)

**Comment by snipe** [comment]
@inietov can you take a look?

**Comment by m4zl** [comment]
I had the same problem right now. I could not upload files above 2MB, although it stated 8M is allowed. I just checked the php.ini and it really said "upload_max_filesize = 2M". The "post_max_size" was right.

**Comment by inietov** [comment]
I found that it's working, just the modal presents a different value than the actual max size configuration is taking to upload files. If you need to upload bigger files you need to check your `upload_max_filesize` and `post_max_size` php.ini file values.
