### ISSUE TITLE
Column not found: 1054 Unknown column 'ad_append_domain' in 'field list'"

### ISSUE THREAD

**Issue by caribou-it** [grokability/snipe-it#9441]
#### Expected Behavior (or desired behavior if a feature request)

testing ldap after migration

-----

#### Actual Behavior
when testing LDAP I get the message that LDAP is not enabled, cannot test.
When I make any changes I get server 500 error
when I turn on debug I see the following error; Column not found: 1054 Unknown column 'ad_append_domain' in 'field list'"

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Upgrade from 4.7.5 (Xampp) to 5.1.4 Server 2019 IIS 
- Version of Snipe-IT you're running
- 5.14
- Version of PHP you're running
- 7.4
- Version of MySQL/MariaDB you're running
- 10.5
- What OS and web server you're running Snipe-IT on 
- server 2019 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Github clone / composer install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- Column not found: 1054 Unknown column 'ad_append_domain' in 'field list'"
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- admin/ldap
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- no
- Include any additional information you can find in `storage/logs` and your webserver's logs.
[laravel.log](https://github.com/snipe/snipe-it/files/6320077/laravel.log)
-

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
nothing got edited
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Did you run migrations?

**Comment by caribou-it** [comment]
migrations as in 
https://snipe-it.readme.io/docs/moving-snipe-it
I did them all.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/moving-snipe-it">Moving Snipe-IT</a></strong></div><div>Moving/migrating Snipe-IT to a new server should be a pretty painless process. You really only have a few things to worry about:  Your .envYour databaseYour uploaded filesYour OAuth keys The easiest way to handle this is to simply run a backup through your Snipe-IT admin panel at Admin &gt; Backups,...</div></blockquote>

**Comment by snipe** [comment]
Okay, and what’s was the output of all of these steps?

**Comment by caribou-it** [comment]
php artisan migration.php:
Migrating: 2018_07_28_023826_create_checkout_acceptances_table

   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'checkout_acceptances' already exists (SQL: create table `checkout_acceptances` (`id` int unsigned not null auto_increment primary key, `checkoutable_type` varchar(191) not null, `checkoutable_id` bigint unsigned not null, `assigned_to_id` int null, `signature_filename` varchar(191) null, `accepted_at` timestamp null, `declined_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)

  at C:\inetpub\wwwroot\Snipe\vendor\laravel\framework\src\Illuminate\Database\Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'checkout_acceptances' already exists")
      C:\inetpub\wwwroot\Snipe\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDO\Exception.php:18

  2   Doctrine\DBAL\Driver\PDO\Exception::new()
      C:\inetpub\wwwroot\Snipe\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:114

  Please use the argument -v to see more details.

**Comment by caribou-it** [comment]
C:\inetpub\wwwroot\Snipe>php artisan config:clear
Configuration cache cleared!

C:\inetpub\wwwroot\Snipe>php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!

**Comment by snipe** [comment]
Thanks for the additional info. Your migrations failed partway through.

**Comment by caribou-it** [comment]
I know. How do I fix it? It all works without importing the database

**Comment by caribou-it** [comment]
it seems that when I import the old database some tables are removed

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
