### ISSUE TITLE
Upgrade from v4.7.4 to v5.1.3 results in blank screen.

### ISSUE THREAD

**Issue by perezalvarezhi** [grokability/snipe-it#9442]
**Short Description:**

I followed the [Moving instructions](https://snipe-it.readme.io/docs/moving-snipe-it) by installing a new instance of Snipeit via Git in a subfolder (old was www/snipe/public and new is www/snit/public). I did this because the old install was not a Git install but an install created automatically with Softaculous on CPanel.

Im getting a blank screen and cant do the migrate command.

Thank you all in advance for your help!

#### Expected Behavior (or desired behavior if a feature request)

After doing all the instructions for moving, I should run  the migrate command `php artisan migrate`.
I would expect some message shows confirming the migration was successful or maybe the migration was not successful.

-----

#### Actual Behavior

I run `php artisan migrate` and don't get any response it just executes and returns to the prompt like if nothing happened.

When going to www/[newInstall]/public/ (5.1.3) it stays in a blank page, even when I activate debug mode(no trace of the debug menu).
Old install still works(4.7.4)

**Note:** It might be wrong to do this but I'm not creating a new database, I'm just setting the .env file to point to the old database used in the old instance.

-----

#### Please confirm you have done the following before posting your bug report:

- [Yes ] I have enabled debug mode 
- [ YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
- I executed all the commands for clearing cache and checked the requirements, all successful. 

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 

> - This is an upgrade / migration since it is a complete new installation using GIT

- Version of Snipe-IT you're running

> - from v4.7.4 to v5.1.3

- Version of PHP you're running
>- 7.3.27
- Version of MySQL/MariaDB you're running
>- 10.3.23-MariaDB
- What OS and web server you're running Snipe-IT on
>- CloudLinux 7.9 on a shared  hosting. (I do not have root)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
>- Old version was via Softaculous auto installer, new one is using GIT.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
>- Cant see any errors
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
>- SSH to server , command `php artisan migrate` and then going into www/[newinstall] (the DocumentRoot is going to [newInstall]/public)
- If a stacktrace is provided in the error, include that too.
>- NA
- Any errors that appear in your browser's error console.

--------------------------------------------------------------------------
GEThttps://txamericancitrus.com/snit/public/
[HTTP/2 500 Internal Server Error 69ms]

	
GET
	https://txamericancitrus.com/snit/public/
Status500
Internal Server Error
VersionHTTP/2
Transferred323 B (0 B size)

    	
    HTTP/2 500 Internal Server Error

    x-powered-by: PHP/7.3.27

    content-type: text/html; charset=UTF-8

    content-length: 0

    date: Thu, 15 Apr 2021 19:49:52 GMT

    server: LiteSpeed

    strict-transport-security: max-age=63072000; includeSubDomains

    x-frame-options: SAMEORIGIN

    x-content-type-options: nosniff

    X-Firefox-Spdy: h2
    	
    Accept
    	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Cache-Control
    	max-age=0
    Connection
    	keep-alive
    Cookie
    	XSRF-TOKEN=eyJpdiI6IkpcL1wvRG1zc2d1a1dsYjJreG1JOFM0QT09IiwidmFsdWUiOiJBNU9laitvQjlzWjE2UW1RcWZWVlhucStnMVV0T0tVaFJwaXZmKzZHWkdSRXViZENqXC9BOXdYUDk4T2ZhWWVDT0M3c0ljTUMxZDd1R3RcL2tQWGdYZlBnPT0iLCJtYWMiOiJmOGIyZjZkYzQ4NzJhMjgzNjhhMTg1YzFhNjU3N2JlYTNhMjVhYTM3Y2RmOTJiYTc1MDFmYTZhNTExN2U0NTk4In0%3D; snipeit_session=HPMZ1Oy6WySGBTxRZZAfnXKvc7uOgat7t9NtIgiP; laravel_token=eyJpdiI6IlJ5ek84T0M5MjhZOWhsSkNsWFNzc1E9PSIsInZhbHVlIjoicUU5UkIwSFBLakJkamE0SkYxd21MekpyKzlWSHNMbDJKWmlVZXlmNk9mUUF1aTVQeWtJMXQxZ09DVStvYWRpMVFEcGhkS1QwMnVUNUdEdW82aGYrSFBoc2x4cnlYbVNrWENIWnVuSjFNcWpFMWFsRDVnTTNFU2lxS2JzS3RKSlwvV3FcL1R1bCtnKzdIelI4SHJpNlwveWQ0VXNnY3N4SXVsVTFmcGN4d1FQQU01YnhiSEl1a1QxK01cL1RQb3pEXC9wREZaaHFjZTl1RDB0TktOeWE0Zk9oZm9tTldYU0xFVTRETVlsbDVDVVlCNndqb1RIQnA5NEVuNnhWRnhCZ29pS1dQTUIxZVU3aDRzcEJUMUxFU3Z2czhvdz09IiwibWFjIjoiYTk1OGFlZGE4MDVlNzdiZTIxZTZmNzYzZmYxZWE5ZDA3MzI5NGVkMzE1Yzc2NDI1NzZkZTZjYzg0N2E0MDUxOCJ9
    Host
    	txamericancitrus.com
    TE
    	Trailers
    Upgrade-Insecure-Requests
    	1
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
------------------------------------------------------------------

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
>- It is not
- Include any additional information you can find in `storage/logs` and your webserver's logs.
>- Logs  are empty
- Include what you've done so far in the installation, and if you got any error messages along the way.
-----------
1. Made a backup
2. Cloned from git on latest version
2. Created a copy of the .env.example file into .env
3. Changed the .env acording to my old installation kept the same database, dbuser, key.
4. Copied public/uploads , storage/private_uploads , copied private and public keys.
5. Changed .htaccess file to redirect to [newInstall]/public
6. Ran  `php artisan migrate` `php artisan config:clear` 
7. Got no response
8. Go to the site and get a blank screen.
-------------
 
- Indicate whether or not you've manually edited any data directly in the database
>- No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Huh...  So, it’s hard to tell from this whether this is a web server error, a php error, or an application level error.

You’re right to not have created a new DB. Can you look at your Litespeed logs? And your PHP error logs? I can’t see any reason why Snipe-IT wouldn’t work with LiteSpeed. If you run upgrade.php, what do you see as output? (It tries hard to look for missing libraries, etc.)

We unfortunately don’t have a lot of insight as to what Softaculous does, but assuming they’re respecting our AGPL license, they’re not charging anything actual code on the fly. What’s more likely is an odd environmental difference, it just may take us a bit to figure out which bit is borked.

**Comment by perezalvarezhi** [comment]
Note (i was writing right before the other answer by snipe): I noticed Issue # #9330 has a similar problem and also the [Permission Section on Upgrading Issues](https://snipe-it.readme.io/docs/installation-issues#permission-issues) talk about permission incorrectly set.
I tried to follow this unfortunatelly I cant create users since the command `useradd -g apache snipeit` didnt work on my server it might be because im using a Shared hosting.

I did  `chown -R [my current linux user] storage public/uploads` and `chmod -R 755 storage`
`chmod -R 755 public/uploads`
but I dont think this works. I still get the blank screen.

**Comment by perezalvarezhi** [comment]
Hello wow thank you for the super fast response and directly from the snipe-it creator :D.
Here is what I got:

> Can you look at your Litespeed logs? 

I  could not access the log files at /etc/apache2/logs because I didn't have permissions (im in a shared hosting) but there is a module in cPanel that shows the web server error logs, here is what it shows:

---------------------

thrown in /home/txameric/public_html/snit/bootstrap/app.php on line 14
#0 /home/txameric/public_html/snit/public/index.php(36): require_once()
2021-04-15 14:39:58.796582 [NOTICE] [16772] [187.213.65.107:59412:HTTP2-15#APVH_txamericancitrus.com:443] [STDERR] PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /home/txameric/public_html/snit/bootstrap/app.php:14

---------------------

>And your PHP error logs? 
**Note:** I get the same error on my browser screen instead of the blank screen.
I Didn't have them on `log_errors=OFF` but after turning that and "display_errors=ON"  I got this when doing `php artisan migrate`:
--------------
PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /home/txameric/public_html/snit/bootstrap/app.php:14
Stack trace:
#0 /home/txameric/public_html/snit/artisan(18): require_once()
#1 {main}
  thrown in /home/txameric/public_html/snit/bootstrap/app.php on line 14

Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /home/txameric/public_html/snit/bootstrap/app.php:14
Stack trace:
#0 /home/txameric/public_html/snit/artisan(18): require_once()
#1 {main}
  thrown in /home/txameric/public_html/snit/bootstrap/app.php on line 14
-------------


>If you run upgrade.php, what do you see as output? (It tries hard to look for missing libraries, etc.)
---------------
I tried  `php upgrade.php` and it got stuck in the middle of it and it wont advance, it took too long(about 45 min) and when I pressed Ctrl+C it got me DC from the server here is the code:


txameric@az1-ls3 [~/www/snit]# php upgrade.php
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- check your PHP version and extension requirements
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (7.3.27) is at least 7.2.5 - continuing...
FYI: The php.ini used by this PHP is: /opt/alt/php73/etc/php.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

--

--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

--
--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
Already on 'master'
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
-- Saved working directory and index state WIP on master: e8adf8d44 One more category fix
-- M    .htaccess
M       public/uploads/.gitignore
M       public/uploads/barcodes/invalid_barcode.gif
M       storage/private_uploads/signatures/.gitkeep
Your branch is up to date with 'origin/master'.
-- Already up to date.

--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ No bootsrap/cache/services.php, so nothing to delete.
√ No bootstrap/cache/config.php, so nothing to delete.

-- -- -- --
--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.

Class Illuminate\Foundation\ComposerScripts is not autoloadable, can not call post-autoload-dump script
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Package operations: 133 installs, 0 updates, 0 removals
  - Syncing symfony/polyfill-php80 (v1.22.0) into cache
  - Syncing symfony/polyfill-php72 (v1.22.0) into cache
  - Syncing symfony/polyfill-mbstring (v1.22.0) into cache
  - Syncing symfony/var-dumper (v4.4.19) into cache
  - Syncing tightenco/collect (v8.19.0) into cache
  - Syncing psr/simple-cache (1.0.1) into cache
  - Syncing psr/log (1.1.3) into cache
  - Syncing symfony/polyfill-ctype (v1.22.0) into cache
  - Syncing phpoption/phpoption (1.7.5) into cache
  - Syncing vlucas/phpdotenv (v3.6.8) into cache
  - Syncing symfony/css-selector (v4.4.19) into cache
  - Syncing tijsverkoyen/css-to-inline-styles (2.2.3) into cache
  - Syncing symfony/routing (v4.4.19) into cache
  - Syncing symfony/process (v4.4.19) into cache
  - Syncing symfony/polyfill-php73 (v1.22.0) into cache
  - Syncing symfony/polyfill-intl-normalizer (v1.22.0) into cache
  - Syncing symfony/polyfill-intl-idn (v1.22.0) into cache
  - Syncing symfony/deprecation-contracts (v2.2.0) into cache
  - Syncing symfony/mime (v5.2.2) into cache
  - Syncing symfony/http-foundation (v4.4.19) into cache
  - Syncing symfony/http-client-contracts (v2.3.1) into cache
  - Syncing symfony/event-dispatcher-contracts (v1.1.9) into cache
  - Syncing symfony/event-dispatcher (v4.4.19) into cache
  - Syncing symfony/debug (v4.4.19) into cache
  - Syncing symfony/error-handler (v4.4.19) into cache
  - Syncing symfony/http-kernel (v4.4.19) into cache
  - Syncing symfony/finder (v4.4.19) into cache
  - Syncing psr/container (1.0.0) into cache
  - Syncing symfony/service-contracts (v2.2.0) into cache
  - Syncing symfony/console (v4.4.19) into cache
  - Syncing symfony/polyfill-iconv (v1.22.0) into cache
  - Syncing doctrine/lexer (1.2.1) into cache
  - Syncing egulias/email-validator (2.1.25) into cache
  - Syncing swiftmailer/swiftmailer (v6.2.5) into cache
  - Syncing paragonie/random_compat (v9.99.99) into cache
  - Syncing ramsey/uuid (3.9.3) into cache
  - Syncing opis/closure (3.6.1) into cache
  - Syncing symfony/translation-contracts (v2.3.0) into cache
  - Syncing symfony/translation (v4.4.19) into cache
  - Syncing nesbot/carbon (2.44.0) into cache
  - Syncing monolog/monolog (2.2.0) into cache
  - Syncing league/mime-type-detection (1.7.0) into cache
  - Syncing league/flysystem (1.1.3) into cache
  - Syncing league/commonmark (1.5.7) into cache
  - Syncing dragonmantank/cron-expression (v2.3.1) into cache
  - Syncing doctrine/inflector (1.4.3) into cache
  - Syncing laravel/framework (v6.20.16) into cache
  - Syncing adldap2/adldap2 (v10.3.1) into cache
  - Syncing ralouphie/getallheaders (3.0.3) into cache
  - Syncing psr/http-message (1.0.1) into cache
  - Syncing guzzlehttp/psr7 (1.7.0) into cache
  - Syncing guzzlehttp/promises (1.4.0) into cache
  - Syncing guzzlehttp/guzzle (6.5.5) into cache
  - Syncing alek13/slack (1.12.0) into cache
  - Syncing asm89/stack-cors (1.3.0) into cache
  - Syncing barryvdh/laravel-cors (v0.11.4) into cache
  - Syncing maximebf/debugbar (v1.16.5) into cache
  - Syncing barryvdh/laravel-debugbar (v3.5.2) into cache
  - Syncing doctrine/annotations (1.11.1) into cache
  - Syncing doctrine/reflection (1.2.2) into cache
  - Syncing doctrine/event-manager (1.1.1) into cache
  - Syncing doctrine/collections (1.6.7) into cache
  - Syncing doctrine/cache (1.10.2) into cache
  - Syncing doctrine/persistence (1.3.8) into cache
  - Syncing doctrine/common (2.13.3) into cache
  - Syncing doctrine/dbal (2.10.4) into cache
  - Syncing squizlabs/php_codesniffer (3.5.8) into cache
  - Syncing masterminds/html5 (2.7.4) into cache
  - Syncing eduardokum/laravel-mail-auto-embed (1.0.5) into cache
  - Syncing enshrined/svg-sanitize (0.13.3) into cache
  - Syncing erusev/parsedown (1.7.4) into cache
  - Syncing fideloper/proxy (4.4.1) into cache
  - Syncing intervention/image (2.5.1) into cache
  - Syncing javiereguiluz/easyslugger (v1.0.0) into cache
  - Syncing laminas/laminas-zendframework-bridge (1.1.1) into cache
  - Syncing laravel/helpers (v1.4.0) into cache
  - Syncing symfony/psr-http-message-bridge (v2.0.2) into cache
  - Syncing phpseclib/phpseclib (2.0.30) into cache
  - Syncing psr/http-factory (1.0.1) into cache
  - Syncing php-http/message-factory (v1.0.2) into cache
  - Syncing nyholm/psr7 (1.3.2) into cache
  - Syncing league/event (2.2.0) into cache
  - Syncing lcobucci/jwt (3.4.3) into cache
  - Syncing defuse/php-encryption (v2.2.1) into cache
  - Syncing league/oauth2-server (8.2.4) into cache
  - Syncing laminas/laminas-diactoros (2.4.1) into cache
  - Syncing firebase/php-jwt (v5.2.0) into cache
  - Syncing laravel/passport (v9.4.0) into cache
  - Syncing laravel/slack-notification-channel (v2.3.1) into cache
  - Syncing nikic/php-parser (v4.10.4) into cache
  - Syncing dnoegel/php-xdg-base-dir (v0.1.1) into cache
  - Syncing psy/psysh (v0.10.6) into cache
  - Syncing laravel/tinker (v2.6.0) into cache
  - Syncing laravelcollective/html (v6.2.1) into cache
  - Syncing league/csv (9.6.2) into cache
  - Syncing mtdowling/jmespath.php (2.6.0) into cache
  - Syncing aws/aws-sdk-php (3.173.0) into cache
  - Syncing league/flysystem-aws-s3-v3 (1.0.29) into cache
  - Syncing psr/cache (1.0.1) into cache
  - Syncing league/flysystem-cached-adapter (1.1.0) into cache
  - Syncing neitanod/forceutf8 (v2.0.4) into cache
  - Syncing php-parallel-lint/php-console-color (v0.3) into cache
  - Syncing php-parallel-lint/php-console-highlighter (v0.5) into cache
  - Syncing filp/whoops (2.10.0) into cache
  - Syncing nunomaduro/collision (v3.2.0) into cache
  - Syncing robrichards/xmlseclibs (3.1.1) into cache
  - Syncing onelogin/php-saml (3.5.1) into cache
  - Syncing paragonie/constant_time_encoding (v2.4.0) into cache
  - Syncing patchwork/utf8 (v1.3.3) into cache
  - Syncing phpdocumentor/reflection-common (2.2.0) into cache
  - Syncing phpdocumentor/type-resolver (1.4.0) into cache
  - Syncing sebastian/recursion-context (3.0.1) into cache
  - Syncing sebastian/exporter (3.1.3) into cache
  - Syncing sebastian/diff (3.0.3) into cache
  - Syncing sebastian/comparator (3.0.3) into cache
  - Syncing webmozart/assert (1.9.1) into cache
  - Syncing phpdocumentor/reflection-docblock (5.2.2) into cache
  - Syncing doctrine/instantiator (1.4.0) into cache
  - Syncing phpspec/prophecy (1.12.2) into cache
  - Syncing pragmarx/google2fa (8.0.0) into cache
  - Syncing bacon/bacon-qr-code (1.0.3) into cache
  - Syncing pragmarx/google2fa-qrcode (v1.0.3) into cache
  - Syncing pragmarx/google2fa-laravel (v1.4.1) into cache
  - Syncing rollbar/rollbar (v2.1.0) into cache
  - Syncing rollbar/rollbar-laravel (v6.0.0) into cache
  - Syncing spatie/temporary-directory (1.3.0) into cache
  - Syncing spatie/db-dumper (2.21.0) into cache
  - Syncing spatie/laravel-backup (6.11.1) into cache
  - Syncing tecnickcom/tc-lib-color (1.14.1) into cache
  - Syncing tecnickcom/tc-lib-barcode (1.17.1) into cache
  - Syncing tightenco/ziggy (0.9.4) into cache
  - Syncing unicodeveloper/laravel-password (1.0.4) into cache
  - Syncing watson/validating (4.0.0) into cache
    0 [>---------------------------]    0 [>---------------------------]  - Installing symfony/polyfill-php80 (v1.22.0): Cloning dc3063ba22 from cache
  - Installing symfony/polyfill-php72 (v1.22.0): Cloning cc6e6f9b39 from cache
  - Installing symfony/polyfill-mbstring (v1.22.0): Cloning f377a3dd1f from cache
  - Installing symfony/var-dumper (v4.4.19): Cloning a1eab2f699 from cache
  - Installing tightenco/collect (v8.19.0): Cloning 0c0243a0dc from cache
  - Installing psr/simple-cache (1.0.1): Cloning 408d5eafb8 from cache
  - Installing psr/log (1.1.3): Cloning 0f73288fd1 from cache
  - Installing symfony/polyfill-ctype (v1.22.0): Cloning c6c942b1ac from cache
  - Installing phpoption/phpoption (1.7.5): Cloning 994ecccd8f from cache
  - Installing vlucas/phpdotenv (v3.6.8): Cloning 5e679f7616 from cache
  - Installing symfony/css-selector (v4.4.19): Cloning f907d3e53e from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.3): Cloning b43b05cf43 from cache
  - Installing symfony/routing (v4.4.19): Cloning 87529f6e30 from cache
  - Installing symfony/process (v4.4.19): Cloning 7e950b6366 from cache
  - Installing symfony/polyfill-php73 (v1.22.0): Cloning a678b42e92 from cache
  - Installing symfony/polyfill-intl-normalizer (v1.22.0): Cloning 6e971c8915 from cache
  - Installing symfony/polyfill-intl-idn (v1.22.0): Cloning 0eb8293dbb from cache
  - Installing symfony/deprecation-contracts (v2.2.0): Cloning 5fa56b4074 from cache
  - Installing symfony/mime (v5.2.2): Cloning 37bade585e from cache
  - Installing symfony/http-foundation (v4.4.19): Cloning 8888741b63 from cache
  - Installing symfony/http-client-contracts (v2.3.1): Cloning 41db680a15 from cache
  - Installing symfony/event-dispatcher-contracts (v1.1.9): Cloning 84e23fdcd2 from cache
  - Installing symfony/event-dispatcher (v4.4.19): Cloning c352647244 from cache
  - Installing symfony/debug (v4.4.19): Cloning af4987aa4a from cache
  - Installing symfony/error-handler (v4.4.19): Cloning d603654eae from cache
  - Installing symfony/http-kernel (v4.4.19): Cloning 07ea794a32 from cache
  - Installing symfony/finder (v4.4.19): Cloning 25d79cfccf from cache
  - Installing psr/container (1.0.0): Cloning b7ce3b1764 from cache
  - Installing symfony/service-contracts (v2.2.0): Cloning d15da7ba49 from cache
  - Installing symfony/console (v4.4.19): Cloning 24026c44fc from cache
  - Installing symfony/polyfill-iconv (v1.22.0): Cloning b34bfb8c4c from cache
  - Installing doctrine/lexer (1.2.1): Cloning e864bbf590 from cache
  - Installing egulias/email-validator (2.1.25): Cloning 0dbf5d7845 from cache
  - Installing swiftmailer/swiftmailer (v6.2.5): Cloning 698a6a9f54 from cache
  - Installing paragonie/random_compat (v9.99.99): Cloning 84b4dfb120 from cache
  - Installing ramsey/uuid (3.9.3): Cloning 7e1633a696 from cache
  - Installing opis/closure (3.6.1): Cloning 943b5d70cc from cache
  - Installing symfony/translation-contracts (v2.3.0): Cloning e2eaa60b55 from cache
  - Installing symfony/translation (v4.4.19): Cloning e1d0c67167 from cache
  - Installing nesbot/carbon (2.44.0): Cloning e6ef33cb1f from cache
  - Installing monolog/monolog (2.2.0): Cloning 1cb1cde8e8 from cache
  - Installing league/mime-type-detection (1.7.0): Cloning 3b9dff8aaf from cache
  - Installing league/flysystem (1.1.3): Cloning 9be3b16c87 from cache
  - Installing league/commonmark (1.5.7): Cloning 11df9b36fd from cache
  - Installing dragonmantank/cron-expression (v2.3.1): Cloning 65b2d8ee1f from cache
  - Installing doctrine/inflector (1.4.3): Cloning 4650c8b30c from cache
  - Installing laravel/framework (v6.20.16): Cloning 806082fb55 from cache
  - Installing adldap2/adldap2 (v10.3.1): Cloning 936a4e2eb9 from cache
  - Installing ralouphie/getallheaders (3.0.3): Cloning 120b605dfe from cache
  - Installing psr/http-message (1.0.1): Cloning f6561bf28d from cache
  - Installing guzzlehttp/psr7 (1.7.0): Cloning 53330f4752 from cache
  - Installing guzzlehttp/promises (1.4.0): Cloning 60d379c243 from cache
  - Installing guzzlehttp/guzzle (6.5.5): Cloning 9d4290de1c from cache
  - Installing alek13/slack (1.12.0): Cloning 9db79a6228 from cache
  - Installing asm89/stack-cors (1.3.0): Cloning b9c31def6a from cache
  - Installing barryvdh/laravel-cors (v0.11.4): packet_write_poll: Connection to 68.66.224.13 port 7822: Broken pipe



---------------


> We unfortunately don’t have a lot of insight as to what Softaculous does, but assuming they’re respecting our AGPL license, they’re not charging anything actual code on the fly. What’s more likely is an odd environmental difference, it just may take us a bit to figure out which bit is borked.
-------------------
Yeah years ago I didn't know much about Linux (still don't) and that was the easiest way for me to get this great program. Unfortunately in Softaculous they don't keep up with updates or when they do it is hard to update for example this time they have the newest version of snipe-it  but migration was a nightmare :(.  I finally want to get into the side of the light haha.
-------------------

**Comment by perezalvarezhi** [comment]
Hello, after looking for more info on the error:

Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found

I found [here in stackoverflow](https://stackoverflow.com/questions/29764368/fatal-error-class-illuminate-foundation-application-not-found) that this is a problem with corrupt Laravel environments, so they asked me to do:
-composer update --no-scripts

After running this and repeating the migration commands and clear `php artisan migrate` and `php artisan config:clear` the system works completly fine.

I considre this problem solved.

@snipe thank you very much for your help, I was a little lost on where to find more info about the problem and your post got me in the right track.
