### ISSUE TITLE
Receiving Error When Trying to Generate Backup

### ISSUE THREAD

**Issue by chn-michael** [grokability/snipe-it#9454]
#### Expected Behavior (or desired behavior if a feature request)

Backup to generate

-----

#### Actual Behavior

 Error: Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified. . #0 C:\inetpub\wwwroot\snipe-it\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 C:\inetpub\wwwroot\snipe-it\vendor\spatie\db-dumper\src\Databases\MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'C:\\inetpub\\wwwr

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running   **v5.1.4 build 5886**
- Version of PHP you're running    **v7.4**
- Version of MySQL/MariaDB you're running   **MariaDB 10.5**
- What OS and web server you're running Snipe-IT on    **Windows Server 2012 R2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  **manual installation**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error   Error: Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified. . #0 C:\inetpub\wwwroot\snipe-it\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 C:\inetpub\wwwroot\snipe-it\vendor\spatie\db-dumper\src\Databases\MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'C:\\inetpub\\wwwr
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error    Admin/Backups
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.  No log produced
- Include what you've done so far in the installation, and if you got any error messages along the way.  Installation completed. No errors
- Indicate whether or not you've manually edited any data directly in the database  No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by aranar-pro** [comment]
I had this same issue on my development site recently.  My issue was a missing modify permission for IUSR on Storage.  I would definitely suggest revisiting the setup docs on fixing folder permissions.  https://snipe-it.readme.io/docs/windowsiis

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/windowsiis">Windows/IIS</a></strong></div><div>   Extract Snipe-IT to C:\inetpub\wwwroot\snipe-it (folder name can be changed but we will reference it as is shown here)Run IIS ManagerRight Click Sites and Add Website (See settings below)Click OKYour site will now appear in the list.IIS may not enable the DELETE, PUT, or PATCH verb by default.  T...</div></blockquote>

**Comment by chn-michael** [comment]
Thanks for the reply!  I followed the document step by step.  My permissions look correct as the document described.  I am still receiving the same error.

**Comment by aranar-pro** [comment]
Just to confirm (because it's not totally clear in the docs), you're also checking IIS_USRS group from location local machine and IUSR have modify on Storage?  https://github.com/snipe/snipe-it/issues/2454#issuecomment-253923667

**Comment by chn-michael** [comment]
Yes both IUS and IIS_USRS from local machine have modify rights in all locations

**Comment by chksome** [comment]
Might be a long shot, but have you cleared the config cache with `php artisan config:clear` as referenced in [the docs](https://snipe-it.readme.io/docs/configuration)?
