### ISSUE TITLE
LDAP User Login

### ISSUE THREAD

**Issue by ldhartmaBechtel** [grokability/snipe-it#9476]
#### Please confirm you have done the following before posting your bug report:

- [Yes] I have enabled debug mode 
- [ Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have successfully set up LDP integration. The test works in the LDAP config page, however users cannot log in. What I am guessing is that this is simply a matter of trial and error with getting the username field correct? DeBug mode did not report any errors and I checked with our SAML admin to verify the field name. I also tried using the Google Plug in for SAML tracer and cannot see the exact field or casing of the field coming back. If you have any suggestions on a good way to check this please advice.

**To Reproduce**

**Expected behavior**
Try to log in with LDAP enabled, log in fails. Existing username password from the database works.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by tophitter** [comment]
This coud be linked to https://github.com/snipe/snipe-it/issues/9273#issuecomment-848662551 

if your have a basic setup make sure the base DN and username / login query fields match the correct DN, if useing sub groups as i am then the the login will not work, but i had a fix on the post above that solved that issue (not the best fix but works for now)

**Comment by ldhartmaBechtel** [comment]
Thank you - I'll try anything at this point!

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
