### ISSUE TITLE
Error on request of asset 

### ISSUE THREAD

**Issue by Natixz** [grokability/snipe-it#9485]
#### Expected Behavior (or desired behavior if a feature request)

When Company client press Request on asset. Browser states ERROR 500
The request get sendt. But something weerd is going on. 
Can see it in logs 
-----

#### Actual Behavior

Pressing request button and get a ERROR 500. If i press back in browser it have sendt the request. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? -  YES 
- Version of Snipe-IT you're running -  Version v5.1.4 - build 5886
- Version of PHP you're running - Latest LTS
- Version of MySQL/MariaDB you're running - Latest LTS
- What OS and web server you're running Snipe-IT on Debian / Apache2 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Install SH 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error /account/requestable-assets
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. 
[- Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Feature-Policy header: Unrecognized feature: 'animations'.
Error with Feature-Policy header: Unrecognized feature: 'battery'.
Error with Feature-Policy header: Unrecognized feature: 'display-capture'.
Error with Feature-Policy header: Unrecognized feature: 'legacy-image-formats'.
Error with Feature-Policy header: Unrecognized feature: 'oversized-images'.
Error with Feature-Policy header: Unrecognized feature: 'publickey-credentials'.
Error with Feature-Policy header: Unrecognized feature: 'unsized-media'.
Error with Feature-Policy header: Unrecognized feature: 'vibrate'.
Error with Feature-Policy header: Unrecognized feature: 'wake-lock'.
533:1 GET http://10.1.0.13/account/request-asset/533? 500 (Internal Server Error)
533:11 Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Nunito' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
]
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  - No i cant make a user with the same privlage set. 
- Include any additional information you can find in `storage/logs` and your webserver's logs. 
- Include what you've done so far in the installation, and if you got any error messages along the way. Clean install. Add 600 Assets 
- Indicate whether or not you've manually edited any data directly in the database NO 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I'd need error logs to be able to help you here.

**Comment by BertaViader-zv** [comment]
I have the same problem, I installed snipe-it with docker. Tested the bug in Firefox and opera.

Errors in storage/log laravel.log attached

**Comment by Sh3ikhX** [comment]
> 
> 
> I'd need error logs to be able to help you here.

i am facing the same issue i have enable debug mode, when ever i try to request assets on requestable-assets page i get server error 500 but when i go back it worked as expected and requested the asset.
The error log shows:
![error](https://user-images.githubusercontent.com/61138639/120598124-514efb80-c45f-11eb-8bb7-687059155deb.JPG)

**Comment by inietov** [comment]
@Sh3ikhX That error means your mail server is not correctly configured. It request the asset but then fails to send the notification via mail.

**Comment by Sh3ikhX** [comment]
> 
> 
> @Sh3ikhX That error means your mail server is not correctly configured. It request the asset but then fails to send the notification via mail.

so in dev environment i have to set smtp just to check if this feature is working or not?

**Comment by snipe** [comment]
Mail settings are required, [per the documentation](https://snipe-it.readme.io/docs/configuration#required-outgoing-mail-settings). You can set the mail driver to `log` if you don't want to use live mail server settings.

**Comment by Sh3ikhX** [comment]
> 
> 
> Mail settings are required, [per the documentation](https://snipe-it.readme.io/docs/configuration#required-outgoing-mail-settings). You can set the mail driver to `log` if you don't want to use live mail server settings.

Thank you so much it fixes the issue.
