### ISSUE TITLE
Request: Checkbox Toggle for Zebra Striping in Tables

### ISSUE THREAD

**Issue by CaptBeard** [grokability/snipe-it#9487]
#### Expected Behavior (or desired behavior if a feature request)
The ability to toggle the zebra striping table view style

-----

#### Actual Behavior

When using a "(dark mode)" skin, it strains the eyes when scrolling.

I've added the custom CSS to my installation to manually disable it, but might be nice to be in the UI for everyone else
```
:root {
     --back-sub-alt: auto;
}
```
-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? upgrade
- Version of Snipe-IT you're running 5.1.4
- Version of PHP you're running 7.4.13
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on CentOS 8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error n/a
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error admin/branding
- If a stacktrace is provided in the error, include that too. n/a
- Any errors that appear in your browser's error console. n/a
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Yes
- Include any additional information you can find in `storage/logs` and your webserver's logs. n/a
- Include what you've done so far in the installation, and if you got any error messages along the way. n/a
- Indicate whether or not you've manually edited any data directly in the database. n/a

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Thanks!

@Godmartinz can you test and PR this please?
