### ISSUE TITLE
Error 500 after LDAP activation

### ISSUE THREAD

**Issue by MikeW83** [grokability/snipe-it#9490]
Hello guys,

I have a fresh installation of the asset management but when I activate LDAP authentication, i can't login with the local administrator. I always get Error 500.
And when I try to deactivate LDAP via command line, it doesn't change a thing. LDAP is still enabled. I have to drop the database and start from scratch.

What is the fault in this case?

Best regards, Michael

**Comment by UserGoodtm** [comment]
Try upgrading to the latest version

**Comment by MikeW83** [comment]
> Try upgrading to the latest version

It's a fresh installation. But I have found the issue: When you activate the option that the domain should be added to username, then the error occures.
