### ISSUE TITLE
Updated PHP from 7.2 to 7.4 in OS, now can't update via upgrade.php

### ISSUE THREAD

**Issue by lachlansimpson** [grokability/snipe-it#9493]
#### Please confirm you have done the following before posting your bug report:

- [ NA] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Redhat 8.3, standard install.

I just upgraded snipe-it from 5.14 to 5.15 using git method in snipeit user.

While reading [the release page](https://github.com/snipe/snipe-it/releases/tag/v5.1.5) I saw the warning about php 7.4 and checked - RH8.3 has PHP 7.2. 

But, [according to the redhat forums](https://access.redhat.com/discussions/5050611#comment-1974131), it's easy enough to update:

```
dnf upgrade
dnf module reset php
dnf module install php:7.4
```

Done, easy.

Flip back into snipeit user to check that upgrade still works. It doesn't:

```
--------------------- !! ERROR !! ----------------------
✘ MISSING PHP EXTENSION: zip
------------------------- :( ---------------------------
ABORTING THE INSTALLER
Please install the extensions above and re-run this script.
------------------------- :( ---------------------------
```
 
`dnf search php*zip` shows that `php-pecl-zip` exists and I try to install it

```
Package php-pecl-zip-1.18.2-1.module+el8.3.0+6678+b09f589e.x86_64 is already installed.
```
Now I don't know what to do.

**Comment by lachlansimpson** [comment]
Took a while, but I seem to have fixed the problem. Installing `libzip-devel` seemed to help. Then installing `unzip` removed some more errors. I don't know why they weren't already installed, but there you go. 

Also, I had to re-install composer, and there was some fiddling around, but it seems to be working now. I'll leave this here as a guide should anyone need it, but I will close the ticket.

**Comment by uberbrady** [comment]
So stoked you figured it out @datakid ! And thank you for writing down what fixed it for you. I really appreciate it, and I hope it might help some other folks who run into the same problems.
