### ISSUE TITLE
duplicate title name in backups option

### ISSUE THREAD

**Issue by King-GO** [grokability/snipe-it#9494]
https://demo.snipeitapp.com/admin/backups
Version v5.1.5 - build 6029 (master)
![image](https://user-images.githubusercontent.com/54804407/116206331-41ae0a00-a771-11eb-9728-7a170b384031.png)

**Comment by snipe** [comment]
I don’t really understand what this means

**Comment by King-GO** [comment]
Maybe this is not a bug, but not good looking
![image](https://user-images.githubusercontent.com/54804407/116212618-948ac000-a777-11eb-9513-b92e854cfbac.png)

**Comment by King-GO** [comment]
fixed in 5.1.6
