### ISSUE TITLE
When loading SnipeIt have to put index.php each time

### ISSUE THREAD

**Issue by netman-lukebaker** [grokability/snipe-it#9495]
#### Expected Behavior (or desired behavior if a feature request)

Expect to type in web address and it takes it to the correct page

-----

#### Actual Behavior

Can log into Snipe-IT, but once in there if I click any of the buttons it says page not found, if I put index.php in then the page it loads, but without formatting e.g. /hardware doesn't work, but /index.php/hardware loads but without formatting

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh Install
- Version of Snipe-IT you're running - v5.1.5
- Version of PHP you're running - v7.3.27
- Version of MySQL/MariaDB you're running - v10.5.9
- What OS and web server you're running Snipe-IT on - Windows Server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual installation (https://blog.masteringmdm.com/snipe-it-installation-on-windows-server/)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error 
    - HTTP Error 404.0 - Not Found
    - Requested URl - http://myurl:80/hardware
    - Physical Path - c:\inetpub\wwwroot\snipe-it\public\hardware
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
    - Any from the home page  
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
   - Not reproducible in demo 
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
   - Couldn't complete setup as couldn't find directory, completed setup using /index.php/setup
- Indicate whether or not you've manually edited any data directly in the database
   - Haven't manually edited any data in database, other than setting up database and user

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by ISNL-PimP** [comment]
Sounds like the default document isn't set for PHP. Try adding `index.php` as a default document via `inetmgr`:
https://tecadmin.net/set-default-document-in-iis/

<blockquote><img src="https://tecadmin.net/wp-content/uploads/2015/04/start-iis-on-windows.png" width="48" align="right"><div><img src="https://tecadmin.net/wp-content/uploads/2016/05/favicon.png" height="14"> TecAdmin</div><div><strong><a href="https://tecadmin.net/set-default-document-in-iis/">How to Set Default Document in IIS - TecAdmin.net</a></strong></div><div>How to Set Default Document in IIS Web Server on Windows systems. Set the default document in IIS to serve to users when no filename specified by user.</div></blockquote>

**Comment by ISNL-PimP** [comment]
If that doesn't work, check whether the URL Rewrite rules are set properly. If they are not, you might receive a 404/403 when navigating to ex. `/hardware`

**Comment by netman-lukebaker** [comment]
Thanks for your help, but after looking at the system have now decided to set up in Ubuntu and is all now working. Thanks.
