### ISSUE TITLE
LDAP 500 Server Error on Save (running 5.1.5)

### ISSUE THREAD

**Issue by Hurmoth** [grokability/snipe-it#9504]
#### Expected Behavior (or desired behavior if a feature request)

While in the LDAP configuration screen, after making a change and clicking save, it immediately throws a 500 Server Error message.

-----

#### Actual Behavior

After saving, it should go back to the LDAP screen with the changes made having been saved.

-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade

- Version of Snipe-IT you're running
5.1.5

- Version of PHP you're running
7.3.27

- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.3.25-MariaDB

- What OS and web server you're running Snipe-IT on 
Ubuntu 20.04.2 LTS // Apache/2.4.41

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
It has been a while since the initial setup, but pretty sure it was git clone for that and since, each upgrades has been php upgrade.php

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Illuminate \ Database \ QueryException (42S22)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ldap_phone_field' in 'field list' (SQL: update `settings` set `ldap_username_field` = userPrincipalName, `ldap_auth_filter_query` = userPrincipalName=, `ldap_phone_field` = ?, `ldap_jobtitle` = ?, `ldap_country` = ?, `ldap_dept` = ?, `settings`.`updated_at` = 2021-04-28 15:21:34 where `id` = 1)
Previous exceptions

    SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ldap_phone_field' in 'field list' (42S22)
    SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ldap_phone_field' in 'field list' (42S22)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
admin/ldap

- If a stacktrace is provided in the error, include that too.
See attached file.
[stacktrace.log](https://github.com/snipe/snipe-it/files/6394422/stacktrace.log)

- Any errors that appear in your browser's error console.
[firefox.log](https://github.com/snipe/snipe-it/files/6394452/firefox.log)

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
It is not.

- Include what you've done so far in the installation, and if you got any error messages along the way.
This was a fresh install early last year, but everything has worked up until now, as far 

- Indicate whether or not you've manually edited any data directly in the database
I have not.

**Comment by snipe** [comment]
Did you run migrations?

**Comment by Hurmoth** [comment]
*facepalm* I had not done that. Completely overlooked it.

I did get an error message trying to migrate: " Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large."

But found a resolution to that fixed it (innodb_log_file_size=512M and innodb_strict_mode=0).

Thank you for the quick response and my apologies for overlooking this!

**Comment by snipe** [comment]
No worries - glad you're all sorted :)
