### ISSUE TITLE
Request Consumables Clone Button

### ISSUE THREAD

**Issue by conan522** [grokability/snipe-it#9505]
Due to each creation of  consumable almost same information except quantity. In order to reduce the workload, can make a Consumables Clone Button?  Just same as Asset.

2nd Request, Is possible can make multiple check out for consumables at one time?

**Comment by byrnajkhan** [comment]
+1. Wanting to have the same consumable at multiple locations. This requires making new one with all the same details.

**Comment by byrnajkhan** [comment]
Didn't realize this was _just_ fixed by #15128
