### ISSUE TITLE
500 | Server Error when Locations Print All Assigned

### ISSUE THREAD

**Issue by cliff-LINKS** [grokability/snipe-it#9521]
#### Please confirm you have done the following before posting your bug report:

- [V] I have enabled debug mode 
- [V] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If I use the ‘Print Assigned’ or ‘Print All Assigned’ button in the Locations page, I get a ‘500 | Server Error’ page.
I get the same result on macOS 10.13 productions server as on my Ubuntu 20.04.2 dev environment.

The similar function in the View User page does function correctly.

In debug-mode I get:
	Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
	Class 'App\Http\Controllers\Asset' not found
	/usr/local/snipeit/app/Http/Controllers/LocationsController.php#234

**To Reproduce**
1. Go to a Settings > Locations in the left toolbar
2. Open a location window
3. Click on 'Print Assigned' or 'Print All Assigned'
4. See error 500 | Server Error

**Server (please complete the following information):**
 - Snipe-IT Version: 5.1.5 build 6029
 - OS: macOS 10.13.6
 - Web Server: Apache 2.4.46
 - PHP Version: 7.4.16 

**Desktop (please complete the following information):**
 - OS: macOS 11.3
 - Browser: Safari 14.1

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11"
 - OS: iOS 14.5
 - Browser: Safari, FireFox 33.1

**Error Messages**
- WITH DEBUG TURNED ON:
	Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
	Class 'App\Http\Controllers\Asset' not found
	/usr/local/snipeit/app/Http/Controllers/LocationsController.php#234

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
	The demo doesn't seem to have this issue
  - Include the output from `php -m` (this should display what modules you have enabled.
  [PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
phpdbg_webhelper

**Additional context**
My production server on macOS is an upgrade using git. The dev server I use, which shows the same issue, is a fresh install on a Ubuntu 20.04.2 VM.

Thanks for looking into this.

regards,
Cliff

**Comment by snipe** [comment]
This was already fixed in https://github.com/snipe/snipe-it/commit/c6726015f78a5749a39942ae7fad3873419be21b

**Comment by cliff-LINKS** [comment]
Thanks for looking into this @snipe.

I've manually added the proposed line to the app/Http/Controllers/LocationsController.php-file. Unfortunately it still errors out to 500 when there are people added. If there are just assets and accessories available, no people, it seems to work fine.

In debug mode I get two exceptions and a message:
Exception:
- Trying to get property 'name' of non-object (View: /usr/local/snipeit/resources/views/locations/print.blade.php)
   /usr/local/snipeit/storage/framework/views/523785bbc7d4bb4b63facafea623e82a26a32a69.php#93
   Illuminate\View\ViewException

- Trying to get property 'name' of non-object
   /usr/local/snipeit/storage/framework/views/523785bbc7d4bb4b63facafea623e82a26a32a69.php#93
   ErrorException

Message:
- [10:19:44] LOG.error: ErrorException: Trying to get property 'name' of non-object in /usr/local/snipeit/storage/framework/views/523785bbc7d4bb4b63facafea623e82a26a32a69.php:93

<img width="1720" alt="Snipe-IT debug error 500" src="https://user-images.githubusercontent.com/53275614/117118292-e68f9f00-ad90-11eb-81d1-9c78abbd97e0.png">

**Comment by snipe** [comment]
What's on line 93 of `/usr/local/snipeit/storage/framework/views/523785bbc7d4bb4b63facafea623e82a26a32a69.php`?

**Comment by cliff-LINKS** [comment]
<td><?php echo e($user->employee_num); ?></td>

**Comment by cliff-LINKS** [comment]
Sorry, I missed a line it is:
`<td><?php` echo e($user->department->name); ?></td>`

**Comment by cliff-LINKS** [comment]
That line got me thinking... I never use the department field for my users.
I've tested this on my dev environment, if I add a department to my users, it seems to work fine.

**Comment by snipe** [comment]
A department isn't necessary, but typically when you'd see that, it would be because the department that's associated to a user isn't valid.

**Comment by snipe** [comment]
I've pushed a few changes out on develop to that page that might help. Looks like whoever opened the PR that created that print page wasn't checking to see if the relationship existed before trying to echo it out.

**Comment by Thorpscu** [comment]
I too have this same issue.  It happens on Print all Assigned and Print Assigned.  
<img width="1144" alt="Screen Shot 2021-05-07 at 11 28 35 AM" src="https://user-images.githubusercontent.com/83785940/117493112-60599100-af27-11eb-9d5b-39d97ad6807a.png">

**Comment by snipe** [comment]
@ThoBur without a stack trace, we're not going to be able to help you.

**Comment by ThoBur** [comment]
@snipe I think you used the wrong name in your answer. :)

**Comment by snipe** [comment]
Sorry @ThoBur - autocomplete is a helluva drug. 😬
