### ISSUE TITLE
docker-compose Setup permission issues

### ISSUE THREAD

**Issue by ryanmerolle** [grokability/snipe-it#9526]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When using docker-compose included in this repo, and you proceed to the setup page, a permissions issue is reported due to the fact that `/var/www/html/storage` directory (or sub-directories within) are not writeable by the web-server.

**To Reproduce**
1. Clone Repo
2. Leverage included docker-compose.yml

**Expected behavior**
 All checks should be valid.  To fix this, the docker-compose.yml file should just include a volume similar to how it is documented in the installation guide for docker without docker-compose.  IE add `snipe-vol:/var/lib/snipeit`

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.5
 - OS: [e.g. Ubuntu, CentOS] CentOS docker-compose
 - Web Server: [e.g. Apache, IIS] Docker included web server
 - PHP Version Docker included PHP

**Error Messages**
See bug description

**Additional context**
- Is this a fresh install or an upgrade? Fresh Docker-compose
- What OS and web server you're running Snipe-IT on n/a
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) docker-compose
- Include what you've done so far in the installation, and if you got any error messages along the way. update the docker-compose file as mentioned
- Indicate whether or not you've manually edited any data directly in the database

Adding @rosscdh given the recent work done here.  I am happy to submit  a PR.

**Comment by rosscdh** [comment]
Hey there,

```
- ./logs:/var/www/html/storage/logs
```

what are the perms for ./logs on the host

```
ls -alh ./logs
```

you can certainly use a volume mount; but ofttimes useful just having it locally mounted

Also can you actually show the logs please?

**Comment by rosscdh** [comment]
but yeah for storage would make sense to use a volume mount :)

**Comment by ryanmerolle** [comment]
On the docker host, not the container itself,  ./logs are owned by the docker user/group with drwxr-xr-x

I assume this does not jive well for ./logs given the container is likely using root.

**Comment by ryanmerolle** [comment]
From the docs:

```
docker run -d -p YOUR_PORT_NUMBER:80 -p YOUR_SSL_PORT:443 --name="snipeit" --link snipe-mysql:mysql --mount source=snipe-vol,dst=/var/lib/snipeit --env-file=my_env_file snipe/snipe-it
```

**Comment by ryanmerolle** [comment]
Apparently I am confusing two different paths / volumes.  

So you are saying there is likely a permission issue on the child directory logs.  That makes perfect sense.  I can either uncomment the mount so it matches the docker run command or fix my permissions.  Thanks @rosscdh

**Comment by rosscdh** [comment]
1. tbh the logs should not be outputting to a folder/file in the first place it should only output to stdout (this can be really bad in production if the container swells due to logs)
2. strangely the dockerfile switches to docker user and then back to root. needs a bit of work there.. tbh php apps are a pain to dockerise (maybe caddy is a light weight option to full blown apache) naja.. topic for another day.
3. id uncomment the mount.. if thats easier but like i said be aware of the logs swellign the container.. if you can modify monolog to output to stdout only.. and in prod that should be scraped by logstash or fluentd and sent "somewhere" 
no probs best of luck

**Comment by ryanmerolle** [comment]
1. I could not agree more.  I was just following the as is docker-compose file, but I will be removing this.
2. Agreed
3. For this sort of data and the userbase accessing, I am less worried about log history except in the case of troubleshooting the service not working as expected.  I can delete logs after a week using cron.

Thanks for the discussion and guidance!

**Comment by rosscdh** [comment]
yes, you can treat docker like a VM, but should you ;)
All good mate glad it worked out!
