### ISSUE TITLE
Speed Up Deployment (pre-flight & admin settings)

### ISSUE THREAD

**Issue by ryanmerolle** [grokability/snipe-it#9530]
**Server (please complete the following information):**
 - Snipe-IT Version 5.1.5
 - OS: [e.g. Ubuntu, CentOS] latest docker image (alpine)
 - Web Server: [e.g. Apache, IIS] latest docker image (apache)
 - PHP Version  latest docker image (7.2)

**Is your feature request related to a problem? Please describe.**

It would be great if we could speed up deployment of snipe-it.  I use a gitlab deployment model where everything is laid down by gitlab calling ansible.  For all of my applications, I can deploy application settings consistently no matter the environment.  I would love this to be the case.

Specifically, I would love to pass 

1. Pre-flight it's various first time setup variables
2. All admin settings found in the admin gui

**Describe the solution you'd like**

Using ENV variables or config files.

**Describe alternatives you've considered**
 
Automated deployments halting right at pre-flight.

**Additional context**

**Comment by snipe** [comment]
That's likely not on the short-term roadmap, as most people only need to set up Snipe-IT once. 

I'd suggest writing a script that populates the `settings` table and [creates an admin user](https://snipe-it.readme.io/docs/create-an-admin) - that will bypass the preflight, as that preflight looks to see that there's a record in the `settings` table and that at least one user exists.

**Comment by ryanmerolle** [comment]
Fair enough, thanks for even responding with suggestions as opposed to just closing this.   Totally not expected, but very much appreciated.

Being new to Snipe-IT/PHP I have to look around for the resources, but I think the order would be:

1. Initialize DB (I assume the step before pre-flight)
2. Populate settings table (I can traverse the mysql db or try to find a schema file)
3. Create an admin user using the utility you provided.
