### ISSUE TITLE
Feature Request - Clear Search Results when returning to lists. (People tab as example)

### ISSUE THREAD

**Issue by MWR-Napavine** [grokability/snipe-it#9531]
#### Expected Behavior (or desired behavior if a feature request)

1. Open the "People" tab.
2. Search for a user using search box.
3. Click on user to open user information page.
4. Return to "People" tab.
5. Have full list available of users.
  5a. Perhaps highlight that there is something in the search field.
  5b. Provide an "x" in the box to quickly clear the search field.
  5c. Provide an option to clear the field or remember in the options.

-----

#### Actual Behavior

Same as above, but
5. Search field still has the search term from the last search, which is not made clear. I am sometimes confused why I am missing most of my users.
(Note this is true of all the tabs: People, Assets, Consumables, etc. People is just an example)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Hosted.
- Version of Snipe-IT you're running
Hosted v5.0.12 build 5705 (gf1d0d1bfe)
- Version of PHP you're running
Hosted 7.3.23
... The rest of the questions are irrelevant for this feature request for our Hosted service.

**Comment by snipe** [comment]
5a and 5b seem pretty reasonable. We can’t clear on page load, since many people wouldn’t be expecting that and use the search to filter out a bunch of things - for example if they want to update all assets that start with `XYZ-` so they want to come back to it. I’m not really willing to change that kind of behavior as it will disrupt a lot of existing workflows - BUT I’m almost ready to push out at least 5a and 5b, so there’s that.

**Comment by MWR-Napavine** [comment]
Understood. 5c was suggested as an option in your settings so it would not
effect existing users workflows, unless the option was changed.

But having 5a and 5b would be a great improvement.

**Comment by snipe** [comment]
On it ;)

**Comment by snipe** [comment]
PR is up https://github.com/snipe/snipe-it/pull/9534

**Comment by chrisfargen** [comment]
Recently deployed Snipe-IT for the first time. Installed v7.1.16 build 16564 (gfb857ccf5), and it seems this issue is present again.

Thank you.
