### ISSUE TITLE
LDAP Sync command does not run inside docker

### ISSUE THREAD

**Issue by SpartacusIam** [grokability/snipe-it#9533]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Running `php artisan snipeit:ldap-sync` command does inside the docker container does not actually force an ldap sync.  If I click the `Synchronize` button under `LDAP User Sync` the sync works without issue.

**To Reproduce**
1. console into docker container using `docker exec -it snipeit /bin/bash`
2. change directory to `/var/www/html` 
3. type `php artisan snipeit:ldap-sync` and hit enter

**Expected behavior**
This should force an ldap sync to take place based off the settings setup in Settings > LDAP

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.4 build 5886
 - OS: docker
 - Web Server:
 - PHP Version:

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)
`[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
gd
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib`

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by fanuelsen** [comment]
i have the same issue... ldap sync command from cli not working. Hitting the sync button it works

**Comment by diegogarciadev** [comment]
I have tha same issue, I cant sync ldap from cron, I need to do it manually in application. I'm not running docker.

**Comment by kf0mlb** [comment]
Same issue.  Running Docker image 'linuxserver/snipe-it:latest'.  LDAP Sync button in WebUI works, running 'php artisan snipeit:ldap-sync' doesn't seem to do anything.

**Comment by uberbrady** [comment]
The sync button actually invokes the artisan command, so it certainly sounds weird that you can't get the syncs to run via CLI. I'm doing development work on the LDAP systems in Docker and it _seems_ to be working for me.

What happens if you do:

```
php artisan snipeit:ldap-sync --json_summary
```

That should at least help give you a little better debugging output.

Does anything show up in the logs?

**Comment by SpartacusIam** [comment]
> The sync button actually invokes the artisan command, so it certainly sounds weird that you can't get the syncs to run via CLI. I'm doing development work on the LDAP systems in Docker and it _seems_ to be working for me.
> 
> What happens if you do:
> 
> ```
> php artisan snipeit:ldap-sync --json_summary
> ```
> 
> That should at least help give you a little better debugging output.
> 
> Does anything show up in the logs?

This is what I get when I run that command.  I've since done exactly as the error asks.  I logged in with the local admin account, put my LDAP password in again, and save it.  I even tested an LDAP login and it works.  But even doing this, I still get the same error message again.

`{"error":true,"error_message":"Your app key has changed! Could not decrypt LDAP                                                                                                                                password using your current app key, so LDAP authentication has been disabled. L                                                                                                                               ogin with a local account, update the LDAP password and re-enable it in Admin >                                                                                                                                Settings.","summary":[]}
`

**Comment by kf0mlb** [comment]
> > ```
> > php artisan snipeit:ldap-sync --json_summary
> > ```
> ...
> 
> `{"error":true,"error_message":"Your app key has changed! Could not decrypt LDAP password using your current app key, so LDAP authentication has been disabled. L ogin with a local account, update the LDAP password and re-enable it in Admin > Settings.","summary":[]} `

When I run the `ldap-sync` command I get the same error as @SpartacusIam.  Testing the LDAP setup from WebUI works, testing my LDAP credentials is confirmed to work, also confirmed I can login as myself to view assigned assets.

**Comment by uberbrady** [comment]
Hrm. Okay, let's try this - 

Grab your `APP_KEY` from your *docker* environment file. Manually paste in that full line (`APP_KEY=base64:blah...`) into the `.env` file inside your container. Then try and rerun the artisan command.

If it works, then I'm gonna have to fix something in how we do our Docker stuff. Not even sure how I'll go about that, but, baby steps. First let's see if that makes the problem go away.

**Comment by SpartacusIam** [comment]
> Hrm. Okay, let's try this -
> 
> Grab your `APP_KEY` from your _docker_ environment file. Manually paste in that full line (`APP_KEY=base64:blah...`) into the `.env` file inside your container. Then try and rerun the artisan command.
> 
> If it works, then I'm gonna have to fix something in how we do our Docker stuff. Not even sure how I'll go about that, but, baby steps. First let's see if that makes the problem go away.

Still no luck.  The APP_KEY variable existed in my .env.docker file but not the .env file (the default line was commented out).  However I manually added it to the .env file and it still made no difference.

**Comment by diegogarciadev** [comment]
I've found my problem... 

My command in crontab was: 
`/usr/bin/php /var/www/html/snipe-it artisan snipeit:ldap-sync` 

instead of

`/usr/bin/php /var/www/html/snipe-it/artisan snipeit:ldap-sync`

Now it should be work fine...

**Comment by fanuelsen** [comment]
i can confirm i get the same error inside my container. `{"error":true,"error_message":"Your app key has changed! Could not decrypt LDAP password using your current app key, so LDAP authentication has been disabled. Login with a local account, update the LDAP password and re-enable it in Admin > Settings.","summary":[]}`

**Comment by SpartacusIam** [comment]
> I've found my problem...
> 
> My command in crontab was:
> `/usr/bin/php /var/www/html/snipe-it artisan snipeit:ldap-sync`
> 
> instead of
> 
> `/usr/bin/php /var/www/html/snipe-it/artisan snipeit:ldap-sync`
> 
> Now it should be work fine...

Thanks for chiming in but this thread is about the docker container versions.

**Comment by kf0mlb** [comment]
Any updates from @uberbrady?

**Comment by uberbrady** [comment]
Your `APP_KEY` must have changed then? Try and re-enter your LDAP password into the LDAP settings. We encrypt that in the database using the `APP_KEY`, so if it changes, then the old password can no longer be decrypted. Once it's re-input into there (and you've hit 'Save') - see if you still keep getting the error?

**Comment by SpartacusIam** [comment]
> Your `APP_KEY` must have changed then? Try and re-enter your LDAP password into the LDAP settings. We encrypt that in the database using the `APP_KEY`, so if it changes, then the old password can no longer be decrypted. Once it's re-input into there (and you've hit 'Save') - see if you still keep getting the error?

I already confirmed further up in this thread that it made no difference.  I generated a new app key, made sure it exists in the .env file, saved the LDAP password again, and still get the same error.

**Comment by SpartacusIam** [comment]
This is really turning out to be such an issue that I may have to move on to alternate solutions if this is not resolved.  New users are the most likely to be needed in the inventory system due to them needing devices checked out to them and without those users automatically showing up from a scheduled LDAP sync, it's creating a major burden.

**Comment by SpartacusIam** [comment]
So, in working with @uberbrady who I am super thankful for his time, we determined that there is an issue with the linuxserver/snipe-it image.  When I changed to the official snipe/snipe-it image all is working fine now.  This issue can be closed as far as I'm concerned but I will leave it open for a bit in case others are still having an issue even after switching repositories.

**Comment by kf0mlb** [comment]
Did you follow the Docker Installation instructions and just re-link your DB? or did you simply swap the image name in your Docker/Compose?

**Comment by SpartacusIam** [comment]
> Did you follow the Docker Installation instructions and just re-link your DB? or did you simply swap the image name in your Docker/Compose?

I took a backup before hand but I just changed the image name in compose and never needed the backup.  The only thing I noticed was after doing the change, I had to login with a local snipe account and re save my LDAP password before LDAP logins would start working again.  So you may just want to make sure you have a local account to fall back upon just in case that affects you as well.

**Comment by kf0mlb** [comment]
I finally had a chance to do this, and my docker exec command to run snipe sync now works.

**Comment by SpartacusIam** [comment]
> I finally had a chance to do this, and my docker exec command to run snipe sync now works.

Are you still able to take backups because I now get a permission error?

**Comment by kf0mlb** [comment]
I will check in the morning and let you know.

**Comment by kf0mlb** [comment]
I cannot run backups as well.  My error message is very long, but I think it boils down to:

`Unknown table 'COLUMN_STATISTICS' in information_schema (1109) .`

But my docker backup script ran last night, and the size seems to have doubled since I changed Snipe-IT images.  So I'm not super worried about the error, but it would probably be preferable to get it fixed.

**Comment by kf0mlb** [comment]
I believe our issue can be closed with LDAP Sync.  My backup issue is the same as new [Issue 10176](https://github.com/snipe/snipe-it/issues/10176).
