### ISSUE TITLE
Auto-Delete deleted AD-User

### ISSUE THREAD

**Issue by haupt-pascal** [grokability/snipe-it#9545]
Good morning :) 

We've got the following problem: We have about ~400 AD-Users, if we deactivate 'em in our AD, they're login is deactivated in SnipeIT - thats good. 

But if we delete them in our Active directory and sync the AD / SnipeIT / LDAP, the login is activated again and the user isn't deleted. We are running a cronjob (guess daily) to sync the ad to snipeit. 

Is there a way that SnipeIT delete users which are not in our AD?

**Comment by LSNIGHTSHOT** [comment]
I would also be interested in this.

**Comment by haupt-pascal** [comment]
- still relevant!

**Comment by haupt-pascal** [comment]
+

**Comment by hesske** [comment]
+1

**Comment by haupt-pascal** [comment]
* still relevant!
