### ISSUE TITLE
Inconsistent behavior when "Allow invalid SSL Certificate" is checked for LDAP/LDAPS

### ISSUE THREAD

**Issue by uberbrady** [grokability/snipe-it#9553]
I've now seen several different scenarios when the "Allow invalid SSL Certificate" in the LDAP settings box has weird-ish behavior, and I wanted to find out what everyone else has been encountering in their own installations.

The behavior that I imagine that most people would want is this: once you check that box, we no longer do any certificate checks. Your traffic still transmits over LDAPS, which is encrypted, but there is no identity checking on the server box. The cert can be self-signed, or expired, or from the future, or whatever - it doesn't matter, because nothing gets looked up. That's what I think is _expected_.

But here's what I've been seeing:

1. I've seen it kinda work for some people. The one that seems most consistent is when the name on the cert doesn't match the hostname in the ldaps:// URL.
2. I've seen the checkbox _not_ be respected when a certificate _had been_ valid, but then expired.
3. I've seen it completely fail on a certificate that was within its expiration window, but came from an internally-managed CA.
4. I've seen supremely bizarre behavior in how it runs on a Mac, requiring me to restart valet to re-respect the latest setting. This is probably less important, but it certainly does mess me up when I'm trying to work on this stuff. Score one for the Docker folks, maybe :/

I've done a lot of messing around to troubleshoot it, and I feel like there's some kind of problem somewhere between PHP, openldap, and openssl - and I don't know where.

What are you folks seeing?

**Comment by patcable** [comment]
:wave: saw [this tweet](https://twitter.com/snipeyhead/status/1391221522627325955) and I have debugged one or two LDAP + TLS things in my day ([recently](https://pcable.net/posts/2021-02-10-rmq-ldap/) w/ rabbitmq). 

Do you have any log output from when it _doesn't_ do what is expected? I'm wondering if there's something like: the client cant agree on ciphers so it doesn't even exchange a cert to begin with. Also, does it only act weird w/ LDAPS? or only with LDAP + StartTLS, or... both? What TLS config is on the LDAP server? (OpenLDAP wont advertise a ton of ciphers if you dont specify a dhparams file, which was a fun thing to learn)

**Comment by patcable** [comment]
My other thought after looking [here](https://github.com/snipe/snipe-it/blob/master/app/Models/Ldap.php#L33-L35) -- if you've got a multithreaded server, are all worker processes getting that environment variable, or just some of them? I wonder if it's set at the systemd unit file level for apache or nginx if it then acts as expected.

Could you start the connection first, then set the same thing using the libldap library constants? not a huge PHP person, but - i saw this on the internet:
```
ldap_set_option($connection, LDAP_OPT_X_TLS_REQUIRE_CERT, LDAP_OPT_X_TLS_NEVER);
```

**Comment by emgillis** [comment]
So many questions. What PHP function(s) involved? Presuming ldap_start_tls(), but maybe not...? What ver of PHP? What ver of openssl, openldap, apache? What configs set for tls (wondering of cyphers,,etc)?

**Comment by snipe** [comment]
Software versions kinda don’t matter here - we use php 7.3 on our hosted platform, but self-hosted users/customers run all kinds of things. We use nginx, one problem customer uses Apache, so versions there don’t seem like they matter either. TLS versions also vary based on circumstances.

**Comment by teancom** [comment]
Can you get a matrix of the PHP, OpenLDAP, and OpenSSL (LibreSSL?) versions of everyone having problems? And you might have to ask them to use ldd to make sure they’re using the libraries they think they’re using. Apache vs. Ngnix shouldn’t matter at all.

**Comment by scoo73r** [comment]
I have a couple thoughts but I don't know an easy way to test LDAP at home. Any advice?

EDIT: I'm moving this month and don't have a home server set up at the moment.

**Comment by scoo73r** [comment]
There appears to be two LDAP connections. Do we have any idea if the behavior is shown by both ldap.php and LdapAd.php?

**Comment by mrngm** [comment]
Just a few thoughts, but beware that I'm not entirely familiar with all the intricacies of `snipe-it` and its configuration. I just ran across [this tweet](https://twitter.com/snipeyhead/status/1391221522627325955).

- [`putenv('LDAPTLS_REQCERT=never')`](https://github.com/snipe/snipe-it/blob/b037d0efddb54809d16070aff87fd9a192fbeb73/app/Models/Ldap.php#L34) seems weird, where PHP offers [`ldap_set_option`](https://www.php.net/manual/en/function.ldap-set-option.php) and `LDAP_OPT_X_TLS_REQUIRE_CERT` since PHP7.0.
  - The phrase `LDAPTLS` doesn't occur anywhere in the source of php-7.3.28, but as it seems linked to libldap, this may not say much
  - The code bindings in PHP's `ext/ldap/ldap.c` do nothing with environment variables, but perhaps libldap does (although I doubt it)
- `ldap_start_tls()` sets the use of `STARTTLS` on an unencrypted session, see [these](http://php.adamharvey.name/manual/en/function.ldap-start-tls.php#51879) various [comments](http://php.adamharvey.name/manual/en/function.ldap-start-tls.php#98417) in the PHP documentation.
  - (this function returns a boolean, and [its return value is not checked](https://github.com/snipe/snipe-it/blob)/b037d0efddb54809d16070aff87fd9a192fbeb73/app/Models/Ldap.php#L54)
  - (the return values for `ldap_set_option()` are also not checked, but that doesn't seem too relevant here.)
  - This [should not be run on `ldaps://` URLs](http://php.adamharvey.name/manual/en/function.ldap-start-tls.php#43632)
- `STARTTLS` is something else than TLS. `STARTTLS` is used to switch from plain text mode to TLS on a plain text protocol, such as LDAP
  - `ldap_tls` may give confusion through its name ([although explicitly documented in this project](https://github.com/snipe/snipe-it/blob/961268172b50dc93148673ce2ce5bf71343a94b0/resources/lang/en-GB/admin/settings/general.php#L74-L75)):
    - For example, setting `ldap_tls` on a TLS connection (i.e. `ldaps://hostname:636`, where TLS is already enforced) probably leads to protocol errors
    - This setting should probably be renamed for clarity, e.g. `ldap_starttls`, and it would be useful to throw a warning when enabling `STARTTLS` on a TLS enabled connection

Hope this helps.

**Comment by scoo73r** [comment]
@mrngm That's the approach I'm working on with my PR. Thanks for writing it out in one place. I'm wondering if adding a check for ldap over ssl somewhere and disabling `starttls` as an extra precaution is needed.

**Comment by scoo73r** [comment]
Would updating the ldap integration to https://github.com/DirectoryTree/LdapRecord-Laravel or a similar solution beneficial? 

<blockquote><img src="https://opengraph.githubassets.com/fc6d2c7ea531495f77b6d1d77f7ea61b66e656a94731e198b555b9ca9633714d/DirectoryTree/LdapRecord-Laravel" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/DirectoryTree/LdapRecord-Laravel">DirectoryTree/LdapRecord-Laravel</a></strong></div><div>Multi-domain LDAP Authentication & Management for Laravel. - DirectoryTree/LdapRecord-Laravel</div></blockquote>

**Comment by uberbrady** [comment]
On My Mac, I have the following - all installed via Homebrew - 

php 7.4.16
OpenLDAP 2.4.58
OpenSSL 1.1.1k

And when I run the following test script, I get the weirdest results.
- If I comment-out the second `putenv()`, the second connection still works. It should fail.
- If I comment-out the first `putenv()` the first and second connection will **both** fail. The second one should work.
- If I comment-out the both the `putenv()` and keep the `ldap_set_option()`, neither connection works. `ldap_set_option()` doesn't seem to work at all.

Now, we have similar problems (but, probably not the same) in our hosted platform but I can't get any test to replicate there. I'll probably try and get an invalid cert hooked up to my AD server and see if that gets me any closer. I'll report back on this ticket.

For testing's sake, my AD server is just an AWS-spun-up Windows server with directory services running on it. For SSL termination I have a copy of stunnel running on my local workstation that points over to the Windows box. As I mentioned, I'm going to try and get a Windows copy of stunnel running on there instead so I can test from more places.

```php
<?php

// putenv("LDAPTLS_REQCERT=never"); //disables certificate checking

//if we disable it HERE it works.
$conn = ldap_connect("ldaps://127.0.0.1:636"); //put LDAP URL starting with ldap:// or ldaps:// here
ldap_set_option($conn, LDAP_OPT_X_TLS_REQUIRE_CERT, LDAP_OPT_X_TLS_NEVER);

if(!$conn) {
    die("Bad LDAP URL");
}

// In the following command, this needs to be the *full* username, fully qualified.
// For active directory it's usually something like 'username@domain.com'
// In other LDAP servers, it's often something like 'uid=username,ou=Users,dc=domain,dc=com'
// Be aware of PHP quoting rules in the password string - put backslashes before quotes in the password or dollar-signs.
$bind_results = ldap_bind($conn,"username@domain.com","yourpasswordhere");

if(!$bind_results) {
    $err = '';
    ldap_get_option($conn, LDAP_OPT_DIAGNOSTIC_MESSAGE, $err);
    print("Could not bind to LDAP server, error: ".ldap_error($conn)." error details: ".$err);
} else {
    print("BIND was succesful!");
}

putenv("LDAPTLS_REQCERT=never"); //disables certificate checking
$conn2 = ldap_connect("ldaps://127.0.0.1:636"); //put LDAP URL starting with ldap:// or ldaps:// here
ldap_set_option($conn2, LDAP_OPT_X_TLS_REQUIRE_CERT, LDAP_OPT_X_TLS_NEVER);

$bind_results = ldap_bind($conn2,"username@domain.com","yourpasswordhere");

if(!$bind_results) {
    $err = '';
    ldap_get_option($conn2, LDAP_OPT_DIAGNOSTIC_MESSAGE, $err);
    print("Could not bind to LDAP server, error: ".ldap_error($conn2)." error details: ".$err);
} else {
    print("2nd BIND was succesful!");
}
```

**Comment by mrngm** [comment]
> And when I run the following test script, I get the weirdest results.
> 
>     * If I comment-out the second `putenv()`, the second connection still works. It should fail.
> 
>     * If I comment-out the first `putenv()` the first and second connection will **both** fail. The second one should work.
> 
>     * If I comment-out the both the `putenv()` and keep the `ldap_set_option()`, neither connection works. `ldap_set_option()` doesn't seem to work at all.

Just a thought, could you add `ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);` at the top of your script? This should give you output like:

```
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/ldap/ldap.conf
ldap_init: using /etc/ldap/ldap.conf
ldap_init: HOME env is /root
ldap_init: trying /root/ldaprc
ldap_init: trying /root/.ldaprc
ldap_init: trying ldaprc
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
ldap_create
ldap_url_parse_ext(ldaps://127.0.0.1:636)
[...]
```

Perhaps this gives some more info on where things go wrong.

It might also be useful to call `ldap_unbind()` on the first connection. It might be that PHP reuses the existing connection when it sees another `ldap_connect()` for the same endpoint.

**Comment by uberbrady** [comment]
I added that tracing and now the connections that were kinda-sorta working before, have stopped working. (This is really quite amazing). Like, I had it where it could make a connection if the `putenv()` near the top was kept in, but if I enable tracing that connection doesn't work at all.

I added the unbind commands (which was a great idea!) but it didn't seem to help. I'm going to dig into the PHP source code now and look around. I'm starting to think that something wonky in PHP itself.

**Comment by emgillis** [comment]
The error you mention by putting the tracing causes connection to fail makes it sound like a header issues from outputting data before you should .... but that doesn't make sense.

Have you had the same inconsistencies when running the cli?

**Comment by uberbrady** [comment]
This seems to be some weird inconsistencies with how macOS integrates with openssl, PHP, and the native crypto libraries on the Mac. We haven't seen this in the wild. I'm going to stick with 'my local is weird'. Once I started developing against the Docker builds instead of my local using Laravel Valet, the problem(s) disappeared. So I'm going to assume this is just Mac Homebrew weirdness and not worry too much more about it.
