### ISSUE TITLE
The system allow duplicate "Asset Tag"

### ISSUE THREAD

**Issue by izombielandgit** [grokability/snipe-it#9564]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The system allow duplicate "Asset Tag"

**To Reproduce**
When I try to "Create New" asset with an existing asset tag, I will get a warning :"The asset tag must be unique.".
But when I change one asset's  asset tag to an existing asset tag("Edit Asset"), it can be saved without warning.

**Expected behavior**
The asset tag must be unique.

**Screenshots**
![20210512124103](https://user-images.githubusercontent.com/22997249/117922182-abf3ac80-b324-11eb-9c1b-1298bfcccd4a.png)
this is a screen print form <https://demo.snipeitapp.com/hardware>

**Server (please complete the following information):**
official demo <https://demo.snipeitapp.com/hardware>

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome
 - Version 90

**Comment by UserGoodtm** [comment]
Some time ago (in previous versions) I had the same problem. I can't repeat it now. If this is the case, then this is a bad mistake #8992

**Comment by UserGoodtm** [comment]
I just checked it on my system. Duplicate tags are created! If you edit an asset. If you create a new asset, you can't create a duplicate tag.
![Снимок](https://user-images.githubusercontent.com/48224568/119884118-f38b5280-bf38-11eb-8ead-1bcfb6839eed.png)
I have version 5.1.5-build 6029 (master). The demo site has a different software version-5.1.5-build 6082 (master). Developers pay attention to this error. It's not the first time she's appeared.

**Comment by inietov** [comment]
Just a couple days ago this issue was addressed in this commit https://github.com/snipe/snipe-it/commit/b8d413a6b820b78e373a95c2cfc5fb860c2ce3b2.
That's now in the demo, and in the develop branch for you to test. Please let us now how that go if any of you happen to test it.

**Comment by UserGoodtm** [comment]
In the new version 5.1.5-build 6082 (master), the error is not reproduced

**Comment by snipe** [comment]
Thanks, that’s why I closed the issue.
