### ISSUE TITLE
Root URL redirects to /public

### ISSUE THREAD

**Issue by wmellema** [grokability/snipe-it#9575]
#### Expected Behavior (or desired behavior if a feature request)

After finishing a fresh install, the root page should not redirect to `/public` but display the dashboard

-----

#### Actual Behavior

After installing the software, installing dependencies and configuring the webserver, the application goes through the setup as it should. After the setup is completed, i get redirected to the root url (`/`) which imediatly redirects me to `/public`.

The rest of the urls (like `/admin`) work just fine. It's just the dashboard that won't load

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
  - Fresh Install
- Version of Snipe-IT you're running
  - v5.1.5
- Version of PHP you're running
  - 7.4
- Version of MySQL/MariaDB you're running
  - MariaDB 10.1.48
- What OS and web server you're running Snipe-IT on
  - Debian 9
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  - Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
  - No error, just a laravel 404
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  - The `/` URL
- If a stacktrace is provided in the error, include that too.
  - N/A
- Any errors that appear in your browser's error console.
   - N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
  - N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by wmellema** [comment]
Somehow relogging the account solved this issue? Could be something to look into tbh

**Comment by snipe** [comment]
No.
