### ISSUE TITLE
Some Help Desk Agents cannot see some LDAP-Imported Users

### ISSUE THREAD

**Issue by bruce2004x** [grokability/snipe-it#9583]
Hi there, first of all, thanks for this wonderful platform. We have installes Snipe  Version v4.8.0 - build 4186 (master). We're facing an strange behaviour where some of our help desk agents cannot find some users. All users are imported from LDAP and sync works fine. I changed their profile granting all permissions but nothing happens. The also tested using other browser, etc.

The search is done under the "People" module.

I'm super admin and I always can find all users.

Any ideas?

**Comment by mfsid** [comment]
I had the same issue. Then I upgraded to version 5.1.5 and now even i can't find users.

**Comment by helpdesk-bba** [comment]
Chek setting - Full Multiple Companies Support I think some off users are in one company and some have none company. Uncheck above and test.

**Comment by bba-dvhk** [comment]
Chek setting - Full Multiple Companies Support I think some off users are in one company and some have none company. Uncheck above and test.

**Comment by bruce2004x** [comment]
@bba-dvhk you are the one!!! as soon as I uncheck that option..all users were be able to find people with no issues.

Thanks a million!
