### ISSUE TITLE
Prevent Duplicate Values in Custom Fields

### ISSUE THREAD

**Issue by athc0** [grokability/snipe-it#9592]
**Server (please complete the following information):**
 - Snipe-IT Version v5.1.2-pre - build 5831 (develop)
 - OS/Web/PHP: Hosted by Snipe-IT

**Is your feature request related to a problem? Please describe.**
We store multiple values per asset that are unique to that asset in custom fields. It would be helpful to have an option to prevent duplicate values in custom fields for things like IMEI/ICCID numbers, etc.

**Describe the solution you'd like**
One checkbox per custom field that will prevent duplicate values like serial numbers and asset tags.

**Additional context**
Repeatedly auditing these in Excel is painful.

**Comment by aqvila2k18** [comment]
+1

**Comment by sg25dev** [comment]
+1

**Comment by snipe** [comment]
This is now on develop
