### ISSUE TITLE
API documentation on accessory/:id/checkedout missing parameters

### ISSUE THREAD

**Issue by markbrule** [grokability/snipe-it#9606]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am using the API /api/v1/accessories/:id/checkedout endpoint to collect all checkout records for an accessory and I realized had a large number (> MAX_RESULTS) records to retrieve. I went in to add ?limit and ?offset parameters to the /checkedout endpoint to find they are already implemented. The API page does not indicate this - just need to update the documentation.

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.4 build 5886 (g9f3a8a43c)
 - OS: ubuntu
 - Web Server: apache
 - PHP Version: 7.4.3

**Comment by snipe** [comment]
Updated now - thanks!
