### ISSUE TITLE
SAML authenticated sessions not expiring

### ISSUE THREAD

**Issue by kcoyo** [grokability/snipe-it#9607]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have the following .env settings:
```
SESSION_LIFETIME=1
EXPIRE_ON_CLOSE=true
ENCRYPT=true
COOKIE_NAME=snipeit
COOKIE_DOMAIN=null
SECURE_COOKIES=true
API_TOKEN_EXPIRATION_YEARS=40
```

`SESSION_LIFETIME` and `EXPIRE_ON_CLOSE`, do not work for SAML authenticated users. The settings above are only respected by local accounts. Fully closing the browser, still keeps users logged in. There appears to be a cookie that keeps a persistent login. There is no "remember me" checkbox during SSO. The only way to log out user is to clear cookies & cache.

**To Reproduce**
1) Enable and configure SAML in Snipe-IT
2) Login with SSO
3) Close browser/reboot system
4) User will still be logged in

**Expected behavior**
Closing the browser should log out the user or expire their sessions. 

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.5 - build 6055 (master)
 - OS: [e.g. Ubuntu, CentOS]: Ubuntu
 - Web Server: [e.g. Apache, IIS]: Apache
 - PHP Version: v7.4.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows and macOS
 - Browser [e.g. chrome, safari]: Chrome, Firefox, Safari
 - Version [e.g. 22]: Latest version on all three browsers tested.

**Smartphone (please complete the following information):**

**Error Messages**
No error logs to report. The issue is a persistent login.

```
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on: Ubuntu Server & Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual
- Include what you've done so far in the installation, and if you got any error messages along the way.: Snipe-IT functional.
- Indicate whether or not you've manually edited any data directly in the database: Negative

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by kcoyo** [comment]
I believe I was able to find the line that was creating the "remember me" cookie at SSO. 

https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/Auth/LoginController.php

Line 111: `Auth::login($user, true);`.

Based on the Laravel [documentation here](https://laravel.com/api/5.5/Illuminate/Auth/SessionGuard.html#method_login), line 111 means the remember me token is always set to TRUE. I set this to `false`, and I no longer see the remember me cookie created.

For reference, you can also try this on line 239.
`if (!Auth::attempt(['username' => $request->input('username'), 'password' => $request->input('password'), 'activated' => 1], $request->input('remember'))) {`

If you replace, `$request->input('remember')` with either `true` or `false`, it will not follow whether the checkbox is checked or not during a local account login. True will create a remember me cookie, while false will not.

For those using LDAP authentication, you can edit line 226.

If this worked (or did not work) for you, please share your results.

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by kcoyo** [comment]
@johnson-yi Are you able to take a look?

**Comment by johnson-yi** [comment]
Hi kcoyo,

You are correct. SSO logins shouldn't be persistent.

This should just be `Auth::login($user);` for SAML & RemoteUser SSO logins and LDAP logins should be fixed to `Auth::login($user, $request->input('remember'));` to respect the "Remember me" checkbox.

Do you want to raise a pull request? Otherwise I can do one later.

**Comment by kcoyo** [comment]
Thanks, @johnson-yi! I submitted a pull request. It's my first time, so hoping there are no issues.
