### ISSUE TITLE
Add gsuite / google workspace login

### ISSUE THREAD

**Issue by Mistic92** [grokability/snipe-it#9612]
**Describe the solution you'd like**
Option to use Gsuite / Google Workspace as login solution, currently I see only LDAP

**Comment by camro** [comment]
Also relevant: #238

**Comment by Mistic92** [comment]
Would be nice if we could have just google sign in button which create user automatically

**Comment by uberbrady** [comment]
This does exist now, using Google secure LDAP and Google SAML SSO.
