### ISSUE TITLE
Check out Username not showing Requestable Assets 

### ISSUE THREAD

**Issue by bal-sam** [grokability/snipe-it#9644]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

----- 

Image | Model | Model No. | Asset Name | Serial | Location | Status | Expected Checkin Date | Actions 
this are the column only showing 

#### Actual Behavior

(what actually happens goes here)

Image | Model | Model No. | Asset Name | Serial | Location | Status | Expected Checkin Date | Actions | CHECKOUT USER
-----
Need to update one more column which user allocated that assets.

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  -- upgrade
- Version of Snipe-IT you're running   -- 5.1.5
- Version of PHP you're running         --7.4.X
- Version of MySQL/MariaDB you're running  -- 10.3.X
- What OS and web server you're running Snipe-IT on  -- centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
What is “checkout user”? I kinda don’t understand what you’re asking. For here - can you elaborate, and/or add some screenshots?

**Comment by bal-sam** [comment]
<img width="916" alt="checkout To" src="https://user-images.githubusercontent.com/73271950/120146529-ddb0b280-c202-11eb-96ad-192c445d4a4d.png">

Check out To User name not showing for requestable assets, from user end.

**Comment by snipe** [comment]
If it's a requestable device, that field doesn't make sense on that page.
