### ISSUE TITLE
User account with Azure AD?

### ISSUE THREAD

**Issue by x3inspire** [grokability/snipe-it#9651]
Hi, possible Snipe IT support Azure AD for user account please?

Our company have LDAP/AD but only for internal access, since my Snipe IT hosted from outside and we already use Azure AD, so current LDAP/AD cannot be used.

**Comment by phenixdotnet** [comment]
Hi @x3inspire 
You can use SAML configuration to enable SSO between Azure AD and snipe-it.
We are using it and it's working like a charm :)

**Comment by x3inspire** [comment]
> Hi @x3inspire
> You can use SAML configuration to enable SSO between Azure AD and snipe-it.
> We are using it and it's working like a charm :)

Thank you!

Btw could you share the configuration with Snipe IT please?

**Comment by phenixdotnet** [comment]
Well its pretty standard.
In Azure AD create a new Enterprise Application, in SSO section define

In Basic SAML Configuration:
- Identifier: put it your snipe-it url 
- Reply URL: Put it your snipe-it url too

Configure your user attributes and claims mapping (or use default if you don't have specifics things)
Download the Federation Metadata XML, upload it to snipe-it.
From snipe-it, download the metadata document and upload it to your Azure enterprise app ("Upload metadata file" button on top of the SSO settings)

**Comment by x3inspire** [comment]
> Well its pretty standard.
> In Azure AD create a new Enterprise Application, in SSO section define
> 
> In Basic SAML Configuration:
> 
> * Identifier: put it your snipe-it url
> * Reply URL: Put it your snipe-it url too
> 
> Configure your user attributes and claims mapping (or use default if you don't have specifics things)
> Download the Federation Metadata XML, upload it to snipe-it.
> From snipe-it, download the metadata document and upload it to your Azure enterprise app ("Upload metadata file" button on top of the SSO settings)

Hi, i do tested the configuration but seem like failed. Can i get your email or contact detail please?

When i click login via SAML, i can successfully login with user email ID, but it return error:

` Error: There was a problem while trying to log you in, please try again.`

Log Error:

`production.ERROR: SAML LogoutRequest/LogoutResponse not found. Only supported HTTP_REDIRECT Binding`

`production.ERROR: OneLogin\Saml2\Error: SAML LogoutRequest/LogoutResponse not found. Only supported HTTP_REDIRECT Binding`

![Capture](https://user-images.githubusercontent.com/4635825/120502614-292ab280-c3f5-11eb-8aa8-62d1d37055e0.PNG)

I do test "Test single sign-on" as well as "Sign in as current user",  got error:
`Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
The POST method is not supported for this route. Supported methods: GET, HEAD.`

**Comment by DarkWingDuck65** [comment]
> Well its pretty standard. In Azure AD create a new Enterprise Application, in SSO section define
> 
> In Basic SAML Configuration:
> 
> * Identifier: put it your snipe-it url
> * Reply URL: Put it your snipe-it url too
> 
> Configure your user attributes and claims mapping (or use default if you don't have specifics things) Download the Federation Metadata XML, upload it to snipe-it. From snipe-it, download the metadata document and upload it to your Azure enterprise app ("Upload metadata file" button on top of the SSO settings)

Hope this is fine to continue with this.

Created the Enterprise App. I add all the details, XML file and Attribute Mapping, in our snipe-it for SAML, but it doesn't save.

So I have a question in, what is refered to?

**_From snipe-it, download the metadata document and upload it to your Azure enterprise app ("Upload metadata file" button on top of the SSO settings)_**

**Comment by balait4** [comment]
Hi, I followed the same "From snipe-it, download the metadata document and upload it to your Azure enterprise app" I'm getting the below error, seems not correctly redirecting? From AD side I can see the login log as Success. 

Error: There was a problem while trying to log you in, please try again.

**Comment by uberbrady** [comment]
If the username in Snipe-IT matches the username in SSO, then the login should work. And I think `storage/logs/laravel.log` should have some decent error messages for you.

**Comment by balait4** [comment]
thanks after creating username in snipe-IT, it is working. So the all the username should be manually created in Snipe-IT?

**Comment by uberbrady** [comment]
It doesn't have to be manual. But they do have to pre-exist. You can use LDAP or possibly import files of users or any other way but the user still has to be there for you to log into them.

**Comment by x3inspire** [comment]
> If the username in Snipe-IT matches the username in SSO, then the login should work. And I think `storage/logs/laravel.log` should have some decent error messages for you.

Example if my Azure ID username is user1@domain.com, so i need to created username in SnipeIT as user1 as well?

**Comment by snipe** [comment]
@x3inspire Yes - which is where LDAP syncing usually comes in. JIT-style provisioning of users kinda doesn't make sense for most scenarios in Snipe-IT, since the only thing a newly minted user can do (before they are assigned any useful permissions) can do is see their own assets that have been checked out to them - and they would not have anything checked out to them when they are newly created anyway. [The SAML docs](https://snipe-it.readme.io/docs/saml) also address this.

**Comment by x3inspire** [comment]
> @x3inspire Yes - which is where LDAP syncing usually comes in. JIT-style provisioning of users kinda doesn't make sense for most scenarios in Snipe-IT, since the only thing a newly minted user can do (before they are assigned any useful permissions) can do is see their own assets that have been checked out to them - and they would not have anything checked out to them when they are newly created anyway. [The SAML docs](https://snipe-it.readme.io/docs/saml) also address this.

After created user, i have to run these code via phpmyadmin to make user able to login.
`update users set username=email`

**Comment by snipe** [comment]
Your usernames are set up incorrectly then. [Per the LDAP docs](https://snipe-it.readme.io/docs/ldap-sync-login), most LDAP providers use email as the username. That's not our rule, it's just how LDAP usually works. Whether they use email address or a username, you'll need to make sure these agree in order to sync without creating duplicates. 

<img width="834" alt="Screen Shot 2022-02-02 at 7 58 17 PM" src="https://user-images.githubusercontent.com/197404/152279056-3fab2547-bbee-40cc-a8d6-0957534a1058.png">

**Comment by mw-christensen** [comment]
I am having the same issue. I have followed the instructions as listed here: https://snipe-it.readme.io/docs/saml#azure-ad-as-saml-identity-provider

I did an Azure AD export of users and then an import of those users in SnipeIT. The username is the email address. I have verified that "Login Enabled" is set for the user. 
When I go to our SnipeIT URL I am redirected as I would expect to the Microsoft login and it recognizes my email and password. Once I complete logging in however I am taken to a screen that says "Error: There was a problem while trying to log you in, please try again."

I am able to login to another user with a username and password that I have manually set. I just can't login with any of the users from SAML.

Any thoughts? My best guess at this point is that perhaps my "Attributes & Claims" from the default Azure AD SAML toolkit are not correct. I have attached a screenshot below. 

Thanks in advance!

P.S. I setup SnipeIT on a Docker instance. Not sure if that would make a difference or not though.


![2022-04-14_11-03-05](https://user-images.githubusercontent.com/103672717/163439429-74a2ddd8-d2f3-4013-aa96-ad5e212378b2.png)
![2022-04-14_11-03-29](https://user-images.githubusercontent.com/103672717/163439433-ad1d730f-ae54-4eab-a4c2-fd1ca9ebf66d.png)
![2022-04-14_11-04-10](https://user-images.githubusercontent.com/103672717/163439436-0dad7d04-373d-425d-8eb0-96e4eb473e00.png)
![2022-04-14_11-01-19](https://user-images.githubusercontent.com/103672717/163439437-190adb81-cf2e-4f5f-b034-60a17d5f62a9.png)



<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/saml#azure-ad-as-saml-identity-provider">SAML</a></strong></div><div>Configuration guidelines for SAML Single-Sign On (SSO) support</div></blockquote>

**Comment by uberbrady** [comment]
The docker thing _shouldn't_ make a difference. If none of our Docker users could manage to log in via SAML I would've thought we would've heard it by now - but it's certainly still possible.

One thing you should check out is, on your container, look in `./storage/logs/laravel.log` and scroll to the bottom - see if there's anything useful in there?

**Comment by mw-christensen** [comment]
Thanks! That log file is a great place to look. It appears it might be related to port forwarding and how I have things setup in our reverse proxy.

[2022-04-13 14:01:56] production.ERROR: There was an error with SAML ACS: invalid_response
[2022-04-13 14:01:56] production.ERROR: Reason: The response was received at https://snipeit._ourdomain_.com:9956/saml/acs instead of https://snipeit._ourdomain_.com/saml/acs

I will check nginx and hopefully figure this out. Thanks again for pointing me in the right direction!

**Comment by mw-christensen** [comment]
So I am not having much luck. I am still getting the error:
`[2022-04-18 13:11:31] production.ERROR: Reason: The response was received at https://snipeit.ourdomain.com:9956/saml/acs instead of https://snipeit.ourdomain.com/saml/acs`

Things I have tried:
In .env.docker set 
`APP_FORCE_TLS=true`

`APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1` (changed to my actual nginx ip addresses)

```
USE_X_FORWARDED_HOST=true
USE_X_FORWARDED_PORT=true
```

Nothing seems to be working. Any suggestions for what I should be looking at? Thanks!

**Comment by mw-christensen** [comment]
Update

I have it partially working now. It looks like I didn't read the documentation as carefully as I should have and left out `baseurl=https://snipeit.ourdomain.com/saml` in the SAML Custom Settings.

Now when I login it takes me to https://snipeit.ourdomain.com:9956 and gives the error "This site can't provide a secure connection" 
![2022-04-18_16-33-28](https://user-images.githubusercontent.com/103672717/163888198-d835cdb7-d2f3-4ceb-894d-0e7f571d1760.png)

BUT if I take of the port number in the URL and press enter it loads everything correctly.

So the login is working, I just need to figure out why it is directing me to the URL with the port number on it.

**Comment by MDKza** [comment]
For those struggling with this make sure you have a user with the username that matches your Azure AD email address.

1. People
2. Create New (First Name, Last name, Username, Email)
3. Click Generate Password
4. Assign Group Rights (if you have)
5. Save

Then SAML auth will work for the user
