### ISSUE TITLE
User Acceptance Email without login

### ISSUE THREAD

**Issue by MWR-Napavine** [grokability/snipe-it#9653]
**Server (please complete the following information):**
 - Snipe-IT Version - v5.0.12 build 5705 (gf1d0d1bfe)
 - OS: [e.g. Ubuntu, CentOS] - Hosted (Unsure)
 - Web Server: [e.g. Apache, IIS] - Hosted (Unsure)
 - PHP Version - 7.3.23

**Is your feature request related to a problem? Please describe.**
When emailing a user an "Asset delivery confirmation" email, the user is prompted to accept the agreement with a link. But in the case where the user is setup with an account that is not designed to be logged into, the link send them to a page where they cannot login and the item is not marked as if the user had agreed.

**Describe the solution you'd like**
Allow a non-login user to agree without having to login. The email's link should be enough.

**Describe alternatives you've considered**
Alternative 1: Send the email, but don't have an "I agree" link.

**Additional context**
Other systems allow this kind of thing without the user having login.

**Comment by ByJacob** [comment]
I also encountered this problem. Is there a workaround for this?

**Comment by ByJacob** [comment]
@snipe :)

**Comment by AkimoA** [comment]
same problem here , any help ?

**Comment by phuonglt0805** [comment]
Same problem here , any help 
It would be nice to have the option to confirm Asset via email without login website  .

![Screenshot 2022-05-17 111115](https://user-images.githubusercontent.com/89070030/168727868-9052007c-1c74-43c1-b0e1-735817d8ba27.png)
?

**Comment by snipe** [comment]
It's not a problem, it's a feature request. It's under consideration, but we JUST launched v6. You have to give us some time.

**Comment by MWR-Napavine** [comment]
Looks like this issue was fixed via FR #11173. So closing this ticket as resolved.

Thanks all.
