### ISSUE TITLE
500 error for invalid dates

### ISSUE THREAD

**Issue by cjs59** [grokability/snipe-it#9654]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to save a date outside the database's supported range, Snipe-IT produces a 500 error rather than a user-friendly message. This is easily triggered if a user types in a two digit year.

**To Reproduce**
1. Create or edit any asset, using any browser or device
2. In any date field, type a date outside the range '1000-01-01' to '9999-12-31', for example '21-06-02'.
3. Try to save the changes
4. See a 500 error

**Expected behavior**
Snipe-IT should produce an error message in the form saying that the date is outside the accepted range.

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.1 - build 5811 (master) 
 - OS: Debian 10.9 amd64
 - Web Server: Apache 2.4.38
 - PHP Version: 7.3.27
 - SQL Server: MariaDB 10.3.27

**Error Messages**
- If a stacktrace is provided in the error, include that too.

(1/1)&nbsp;InvalidFormatExceptionData missing
--
in&nbsp;Creator.php&nbsp;line 643
at&nbsp;Carbon::rawCreateFromFormat('Y-m-d H:i:s', '99-10-12',&nbsp;null)in&nbsp;Creator.php&nbsp;line 665
at&nbsp;Carbon::createFromFormat('Y-m-d H:i:s', '99-10-12')in&nbsp;DateFactory.php&nbsp;line 217
at&nbsp;DateFactory-&gt;__call('createFromFormat',&nbsp;array('Y-m-d H:i:s', '99-10-12'))in&nbsp;Facade.php&nbsp;line 261
at&nbsp;Facade::__callStatic('createFromFormat',&nbsp;array('Y-m-d H:i:s', '99-10-12'))in&nbsp;HasAttributes.php&nbsp;line 813
at&nbsp;Model-&gt;asDateTime('99-10-12')in&nbsp;HasAttributes.php&nbsp;line 835
at&nbsp;Model-&gt;fromDateTime('99-10-12')in&nbsp;HasAttributes.php&nbsp;line 1176
at&nbsp;Model-&gt;originalIsEquivalent('purchase_date', '99-10-12')in&nbsp;HasAttributes.php&nbsp;line 1138
at&nbsp;Model-&gt;getDirty()in&nbsp;HasAttributes.php&nbsp;line 1072
at&nbsp;Model-&gt;isDirty()in&nbsp;Model.php&nbsp;line 660
at&nbsp;Model-&gt;save(array())in&nbsp;Asset.php&nbsp;line 196
at&nbsp;Asset-&gt;save()in&nbsp;AssetsController.php&nbsp;line 354
at&nbsp;AssetsController-&gt;update(object(ImageUploadRequest), '658')in&nbsp;Controller.php&nbsp;line 54
at&nbsp;Controller-&gt;callAction('update',&nbsp;array(object(ImageUploadRequest), 'hardware' =&gt; '658'))in&nbsp;ControllerDispatcher.php&nbsp;line 45
at&nbsp;ControllerDispatcher-&gt;dispatch(object(Route),&nbsp;object(AssetsController), 'update')in&nbsp;Route.php&nbsp;line 219
at&nbsp;Route-&gt;runController()in&nbsp;Route.php&nbsp;line 176
at&nbsp;Route-&gt;run()in&nbsp;Router.php&nbsp;line 681
at&nbsp;Router-&gt;Illuminate\Routing\{closure}(object(Request))in&nbsp;Pipeline.php&nbsp;line 130
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;Authenticate.php&nbsp;line 43
at&nbsp;Authenticate-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;AssetCountForSidebar.php&nbsp;line 56
at&nbsp;AssetCountForSidebar-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;CreateFreshApiToken.php&nbsp;line 50
at&nbsp;CreateFreshApiToken-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;CheckForTwoFactor.php&nbsp;line 53
at&nbsp;CheckForTwoFactor-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;CheckLocale.php&nbsp;line 37
at&nbsp;CheckLocale-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;VerifyCsrfToken.php&nbsp;line 78
at&nbsp;VerifyCsrfToken-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;AddQueuedCookiesToResponse.php&nbsp;line 37
at&nbsp;AddQueuedCookiesToResponse-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;EncryptCookies.php&nbsp;line 67
at&nbsp;EncryptCookies-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;Pipeline.php&nbsp;line 105
at&nbsp;Pipeline-&gt;then(object(Closure))in&nbsp;Router.php&nbsp;line 683
at&nbsp;Router-&gt;runRouteWithinStack(object(Route),&nbsp;object(Request))in&nbsp;Router.php&nbsp;line 658
at&nbsp;Router-&gt;runRoute(object(Request),&nbsp;object(Route))in&nbsp;Router.php&nbsp;line 624
at&nbsp;Router-&gt;dispatchToRoute(object(Request))in&nbsp;Router.php&nbsp;line 613
at&nbsp;Router-&gt;dispatch(object(Request))in&nbsp;Kernel.php&nbsp;line 170
at&nbsp;Kernel-&gt;Illuminate\Foundation\Http\{closure}(object(Request))in&nbsp;Pipeline.php&nbsp;line 130
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;InjectDebugbar.php&nbsp;line 67
at&nbsp;InjectDebugbar-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;SecurityHeaders.php&nbsp;line 26
at&nbsp;SecurityHeaders-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;TransformsRequest.php&nbsp;line 21
at&nbsp;TransformsRequest-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;CheckForDebug.php&nbsp;line 25
at&nbsp;CheckForDebug-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;CheckForSetup.php&nbsp;line 26
at&nbsp;CheckForSetup-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;TrustProxies.php&nbsp;line 57
at&nbsp;TrustProxies-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;ShareErrorsFromSession.php&nbsp;line 49
at&nbsp;ShareErrorsFromSession-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;StartSession.php&nbsp;line 56
at&nbsp;StartSession-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;CheckForMaintenanceMode.php&nbsp;line 63
at&nbsp;CheckForMaintenanceMode-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;NoSessionStore.php&nbsp;line 27
at&nbsp;NoSessionStore-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;HandlePreflight.php&nbsp;line 29
at&nbsp;HandlePreflight-&gt;handle(object(Request),&nbsp;object(Closure))in&nbsp;Pipeline.php&nbsp;line 171
at&nbsp;Pipeline-&gt;Illuminate\Pipeline\{closure}(object(Request))in&nbsp;Pipeline.php&nbsp;line 105
at&nbsp;Pipeline-&gt;then(object(Closure))in&nbsp;Kernel.php&nbsp;line 145
at&nbsp;Kernel-&gt;sendRequestThroughRouter(object(Request))in&nbsp;Kernel.php&nbsp;line 110
at&nbsp;Kernel-&gt;handle(object(Request))in&nbsp;index.php&nbsp;line 58

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Yes, the demo shows the same bug

**Comment by snipe** [comment]
I believe this was fixed many versions ago
