### ISSUE TITLE
Display of Checkout Notes

### ISSUE THREAD

**Issue by mtettke123** [grokability/snipe-it#9659]
**Server (please complete the following information):**
 - Snipe-IT Version: Version v5.1.5 - build 6055 (master) [docker]
 - OS: Debian 10 with docker

**Is your feature request related to a problem? Please describe.**
(Asset-)Notes entered during checkout are only displayed in History and Activity Report. They should be displayed at user Asset Page and at least in "Custom Export/Checked Out To Fields", too.

**Describe the solution you'd like**
Adding the possibity to show the notes using checkboxes as for the asset notes, at least for custom exports.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by snipe** [comment]
The notes included in the asset detail screen are the ones that persist with the asset. It is intentional that checkout notes only appear in history.
