### ISSUE TITLE
Wrong Date 

### ISSUE THREAD

**Issue by itpersonel** [grokability/snipe-it#9664]
Hello,

Wrong date on my project. my clock is true bad my date is wrong. 

Computer clock and date true but snipeit date is wrong. 

Please help me 

https://www.hizliresim.com/p7h64j3

**Comment by snipe** [comment]
The date is just an example, it's not meant to be today's date, Today's date, for example, would be confusing, because 03-06-2021 could mean June 3, 2021 to some people, and March 6, 2021 to other people. We picked a demonstrative date where the day was higher than any month could be.

**Comment by itpersonel** [comment]
Very thanks! best regards. Have a nice day

**Comment by snipe** [comment]
No problem :)
