### ISSUE TITLE
Asset checkin with API doesn't send checkin notification 

### ISSUE THREAD

**Issue by loganhawker** [grokability/snipe-it#9666]
**Server (please complete the following information):**
 - Snipe-IT Version 5.1.4
 - OS: Windows Server 2019
 - Web Server: WAMP/Apache
 - PHP Version 7.4.9

**Is your feature request related to a problem? Please describe.**
I use a spreadsheet with a script to bulk checkin assets. We have been using the asset checkin notifications as a "receipt" for the students. But I just found out that using the API to checkin does not send the email.

**Describe the solution you'd like**
Include _CheckinAssetNotification_ in the checkin function for the API

I'm not sure if this is excluded for a reason but if it would be a simple fix that would be awesome.

**Describe alternatives you've considered**
The only other alternative would be checking in the assets one by one through the website.

**Additional context**
![image](https://user-images.githubusercontent.com/39230442/120875525-1c2ad200-c561-11eb-83a0-0b50661a13e2.png)

**Comment by snipe** [comment]
@inietov can you confirm this locally for me please? We don’t send notifications out through the controllers, we send them out through the logger, so I’m not sure how this would happen except if the category itself is set to not send emails.

**Comment by inietov** [comment]
Yeah, I could reproduce it in my local. The `$asset->logCheckin()` used to send notifications, but now only writes in the Log Action, so I added the event `CheckoutableCheckedIn` that I think is now the preferred way to do it. A PR is ready to be reviewed :).
