### ISSUE TITLE
When the browser not fullscreen or maximize the dashboard and asset button not clickable 

### ISSUE THREAD

**Issue by sinichi19** [grokability/snipe-it#9667]
**Describe the bug**
When the browser not fullscreen or maximize the dashboard and asset button not clickable 

**To Reproduce**
![ezgif-2-5335c25b94c6](https://user-images.githubusercontent.com/44279612/120945258-f96c0980-c76a-11eb-8aa6-d9db768f3d5d.gif)

**Expected behavior**
Even split screen or fullscreen all button are clickable 

**Server (please complete the following information):**
 - Snipe-IT Version  latest
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version  7.4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - Browser [e.g. chrome, safari] Google Chorme, Brave
 - Version [e.g. 22] latest

**Comment by snipe** [comment]
Pretty sure this was fixed a few versions ago. Closing this for now.
