### ISSUE TITLE
Hope support utf-8 in web GUI batch-importing

### ISSUE THREAD

**Issue by Hsing22** [grokability/snipe-it#9678]
**Server (please complete the following information):**
 - Snipe-IT Version v5.1.5 build 6055 (gd9d5b4d73)
 - OS: [e.g. Ubuntu, CentOS]   Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-142-generic x86_64)
 - Web Server: [e.g. Apache, IIS]  None.Work as docker.
 - PHP Version PHP 7.2.24-0ubuntu0.18.04.7

**Is your feature request related to a problem? Please describe.**
When I use csv batch import with Chinese character in the Web GUI, error ocurred.
Shows "Unable to encode attribute [first_row] for model[App\Models\Import] to json:Malformed UTF-8 character ,possibly incorrectly encoded"

**Describe the solution you'd like**
I hope can support utf-8 in batch importing.

**Describe alternatives you've considered**
I have no idea

**Comment by Hsing22** [comment]
Reproduce it maybe easy,you can use a sample .csv in "snipe-it.readme.io".And when u success to upload the csv ,then u can change one character with a Chinese character to reproduce it.

**Comment by snipe** [comment]
@bzeus can you make a CH for this please?

**Comment by inietov** [comment]
@Hsing22 I can't reproduce the issue, I used the  '宿' character in a .csv file and I can import without problems. You think that you can attach an example of a failing file? or to write here what character is making the importer fail?

Thanks in advance
