### ISSUE TITLE
Swift_TransportException (530) Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first "

### ISSUE THREAD

**Issue by CoventryIT** [grokability/snipe-it#9691]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When checking in or checking out and asset the user receives Server Error 500. When the page is refreshed your loaded back into the page and the asset has been checked out or in with a banner stating the "the asset has already been checkout/in
**To Reproduce**
1. Go to 'Assets'
2. Click on 'any asset to checkout or in'
3. Scroll down to 'Select a user and save'

**Expected behavior**
1. Go to 'Assests'
2. Click on 'any asset to checkout or in'
3. Scroll down to 'Select a user and save'
4. See a message stating the asset was checked out successfully.
**Screenshots**
![image](https://user-images.githubusercontent.com/48068571/121568304-90e08f00-c9ed-11eb-98ce-0a7480767570.png)

**Server (please complete the following information):**
 - Snipe-IT Version 
 v5.1.5 build 6082
 - OS: [e.g. Ubuntu, CentOS]
 Windows Server 2012r2
 - Web Server: [e.g. Apache, IIS]
 IIS
 - PHP Version 
7.4.15
**Desktop (please complete the following information):**
  Windows 10 64-Bit
  Chrome
Version 91.0.4472.77

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first "
- If a stacktrace is provided in the error, include that too.
Illuminate\Support\Facades\Facade __callStatic
…\app\Listeners\CheckoutableListener.php51
56
 event
…\app\Models\Asset.php318
55
App\Models\Asset checkOut
…\app\Http\Controllers\Assets\AssetCheckoutController.php84
46
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\AssetCountForSidebar.php56
42
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\CheckForTwoFactor.php53
40
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\CheckLocale.php37
23
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\SecurityHeaders.php26
19
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\CheckForDebug.php25
17
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\CheckForSetup.php26
7
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\app\Http\Middleware\NoSessionStore.php27
0
Illuminate\Foundation\Http\Kernel handle
…\public\index.php58
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
I cannot reproduce on the demo.

**Additional context**
- Is this a fresh install or an upgrade? 
Upgrade
- What OS and web server you're running Snipe-IT on
IIS 8.5.9600.16384
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Your mail settings are wrong in your .env. You need to correct them, set your mail driver to `log` to prevent emails from being attempted, or edit your categories so that they don’t try to send an email.

**Comment by CoventryIT** [comment]
I just was about to mark the ticket as solved but you were too quick on the reply lol. It was an oversight on my part.

Thank you for looking into it.

**Comment by snipe** [comment]
Glad you got it sorted :)
