### ISSUE TITLE
phantomjs (v2.1.7) is preventing ability to run tests

### ISSUE THREAD

**Issue by TerraTech** [grokability/snipe-it#9701]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Unable to run tests due to phantomJS failing.

https://snipe-it.readme.io/docs/contributing-overview#testing

**To Reproduce**
See `Error Messages` below.

**Expected behavior**

phantomJS listens on port 4444

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.6 
 - OS: Alpine Linux v3.13.5
 - Web Server: Apache-2.4.48
 - PHP Version: v7.4.19
 - nodejs: v14.16.1
 - npm: v6.4.2
 - phantomJS: v2.1.7

**Error Messages**
```
$ node_modules/.bin/phantomjs --webdriver=4444 --ignore-ssl-errors=true
Error executing phantom at /home/snipeit/www/snipeit-TEST/node_modules/phantomjs/lib/phantom/bin/phantomjs
Error: spawn /home/snipeit/www/snipeit-TEST/node_modules/phantomjs/lib/phantom/bin/phantomjs ENOENT
  at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
  at onErrorNT (internal/child_process.js:465:16)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Additional context**
- Is this a fresh install or an upgrade?
  - fresh install 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  - manual installation (git worktree)
- Indicate whether or not you've manually edited any data directly in the database
  - have not edited any database data directly

**Comment by wewhite** [comment]
Does phantomjs work, what is the output of:
`phantomjs -v`
The latest stable version is 2.1.1.
If PhantomJS fails, try this:
```
export OPENSSL_CONF=/dev/null
phantomjs -v
```

**Comment by snipe** [comment]
We're currently upgrading how we do tests (via PR https://github.com/snipe/snipe-it/pull/11671) so I think this can be safely closed for now.
