### ISSUE TITLE
Images not showing after upgrade

### ISSUE THREAD

**Issue by dokh** [grokability/snipe-it#9721]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Debug does not give an error

**To Reproduce**

**Expected behavior**
Images to show properly.

**Screenshots**
n/a

**Server (please complete the following information):**
 - Snipe-IT Version : v5.1.6 - build 6109 (develop)
 - OS: Windows Server 2012R2
 - Web Server: IIS
 - PHP Version : 7.4

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser : Firefox
 - Version 89.0.1
 Same issue with other browsers.

**Smartphone (please complete the following information):**
n/a

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
no error
- If a stacktrace is provided in the error, include that too.
n/a
- Any errors that appear in your browser's error console.
image src links show alternative text instead of image. Clicking on produces a *Failed to load image* error with src path pointing http://fqdn/uploads/models/filename.png on some pages.
On the Update Asset model page however the image shows OK, but the src path there points to https instead of http.
env file has http for APP_URL. Changing to https doesn't help.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
n/a
- Include any additional information you can find in `storage/logs` and your webserver's logs.
n/a
- Include the output from `php -m` (this should display what modules you have enabled.)
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
imap
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
SPL
standard
tidy
tokenizer
wincache
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

**Additional context**
- Is this a fresh install or an upgrade? 
upgrade
- What OS and web server you're running Snipe-IT on
Widows server 2012r2 with IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
upgrade.php
- Include what you've done so far in the installation, and if you got any error messages along the way.
n/a
- Indicate whether or not you've manually edited any data directly in the database
n/a

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Knowaaaa** [comment]
We were able to fix this after upgrading from v4 to v5 by adding 'http://' to our servers address in the .env file in the project folder. After that our images started working again.

**Comment by WalterPinkman** [comment]
> We were able to fix this after upgrading from v4 to v5 by adding 'http://' to our servers address in the .env file in the project folder. After that our images started working again.

This fixed it for me. Thanks for the helpful reply!

**Comment by snipe** [comment]
We do state that you need a fully qualified url, including protocol (http:// or https://) as your APP_URL in the documentation.

Glad you’re sorted.
