### ISSUE TITLE
Can i restore backup from cloud platform to a local server base one

### ISSUE THREAD

**Issue by tahon7** [grokability/snipe-it#9722]
Hey 

is it possible to backup all assets and settings on the cloud base snipeit and restore it to my local on prem instance ?

**Comment by tahon7** [comment]
@snipe do you have any advice

**Comment by snipe** [comment]
Hi there - sorry for the late reply here. I'm sure you've figured out by now that yes, you can. The backups created on the cloud hosted system are identical to the ones generated by the self-hosted system.
