### ISSUE TITLE
Composer Errors

### ISSUE THREAD

**Issue by WELLBOREIS** [grokability/snipe-it#9723]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When running php upgrade.php, under "Step 6: Updating composer dependencies", I end up with two errors that do not prevent the upgrade, but are still errors and not sure if they are to be expected or not. I've run composer update which upgrades some plugins, but when I run php upgrade.php, it downgrades the plugins.

`--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

Local composer.phar detected, so we'll use that.

Updating local composer.phar

You are already using the latest available Composer version 2.1.3 (stable channel).

Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
Illuminate\Foundation\ComposerScripts::postAutoloadDump
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
Illuminate\Foundation\ComposerScripts::postAutoloadDump
65 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Generated optimized autoload files containing 6003 classes`

**To Reproduce**
1. SSH into Ubuntu server
2. su - nonrootuser
3. cd /var/www/html/(snipeit directory)
4. php upgrade.php

**Expected behavior**
No errors after upgrade.

**Server (please complete the following information):**
 - Snipe-IT Version: 5.1.6
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Nginx
 - PHP Version: 7.4.20

**Error Messages**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.: No
- Include the output from `php -m` (this should display what modules you have enabled.)
`[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache`

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on: Ubuntu / Nginx
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by stf675** [comment]
new install, same issue (fresh Rocky Linux 8 with PHP 8.x)

```
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
```

when try to run `php artisan key:generate`

I get

```
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /var/www/snipe-it/vendor/lar
  avel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32
```

**Comment by snipe** [comment]
@WELLBOREIS - those are just warnings, so as long as your upgrade works, I wouldn't worry about it. 

@stf675 what do you have for your APP_URL in your `.env`?

**Comment by stf675** [comment]
```
APP_ENV=production
APP_DEBUG=false
APP_KEY=ChangeMe
APP_URL=null
```
using https://www.tecmint.com/install-snipe-it-asset-management-on-centos-ubuntu-debian/ as install guide


<blockquote><img src="https://www.tecmint.com/wp-content/uploads/2017/07/Snipe-IT-Asset-Management-for-Linux.png" width="48" align="right"><div><strong><a href="https://www.tecmint.com/install-snipe-it-asset-management-on-centos-ubuntu-debian/">How to Install Snipe-IT (IT Asset Management) on CentOS and Ubuntu</a></strong></div><div>This article explains how to install a IT asset management system called Snipe-IT using a LAMP (Linux, Apache, MySQL & PHP) on CentOS and Debian based systems.</div></blockquote>

**Comment by stf675** [comment]
found error: missed type in db password and missed url.  Looks like I passed that step.
