### ISSUE TITLE
[ Request ] Search bar header

### ISSUE THREAD

**Issue by davepiersma** [grokability/snipe-it#9726]
**Server (please complete the following information):**
 - Snipe-IT Version 5.1.6
 - OS: [e.g. Ubuntu, CentOS] Windows
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.3.21

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The replacement of the **Lookup by Asset Tag**  search bar in the header with a whole site search feature instead. 
This can be very handy as this is a more centralized location to do a quick search rather searching for Assets only.

**Comment by snipe** [comment]
This has been discussed before and it's not something we're currently working on or would really consider, most likely. There are UX challenges to handling this well, and that top search bar is intended to be used with barcode scanners.
