### ISSUE TITLE
Users departments not being imported in GUI importer

### ISSUE THREAD

**Issue by jared03** [grokability/snipe-it#9730]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
There's a glitch in the GUI importer web page, when you try to process a user and add the field department it shows to fields in the dropdown menu showing Department, once you select either of them it doesn't create a department neither import the data from CSV

**To Reproduce**
1. Go to 'Import'
2. Click on 'Upload CSV with User data add a field of Department'
3. Scroll down to 'Department field and it shows two Departments in dropdown'

**Expected behavior**
As I analyze the code in the importer, it should create a department if not exists or add the user to that Department if exists

**Screenshots**
![image](https://user-images.githubusercontent.com/11325039/122614870-b18b9300-d044-11eb-886c-b8bee2c63cdd.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 5.1.6
 - OS: Ubuntu 20.04
 - Web Server: Apache
 - PHP Version: 7

**Desktop (please complete the following information):**
 - OS: Windows 10 Pr o
 - Browser: Chrome
 - Version: 91.0.4472.114

**Error Messages**

**Additional context**
- Is this a fresh install or an upgrade? 
Fresh install
- What OS and web server you're running Snipe-IT on
Ubuntu 20.04 with Apache 2.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No modifications done

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
@Godmartinz can you take a look at this please? You or @inietov 🙏🏻💪🏻
