### ISSUE TITLE
After upgrading to the latest version, 5.1.6, the program version number changed from "master" to "develop"

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#9735]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading to the latest version, 5.1.6, the program version number changed from "master" to "develop". Did the update as usual "upgrade.php".

**Expected behavior**
Question - is this a normal phenomenon or is it really a mistake?

**Screenshots**
![1](https://user-images.githubusercontent.com/48224568/122987723-95238980-d3a9-11eb-9927-a2fe49c505df.jpg)

![2](https://user-images.githubusercontent.com/48224568/122987741-99e83d80-d3a9-11eb-9649-a5745566793f.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.6
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version  7.4.16 

**Additional context**
- Is this a fresh install or an upgrade? upgrade
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by douglasac10** [comment]
I think it might just be an oops. It's there on mine, and the demo version too.

**Comment by uberbrady** [comment]
Correct @douglasac10 - it's an oops :(
Computers are hard. I don't know if we're going to try and re-release 5.1.6, or if we're going to have to release a 5.1.7, but that depends on which way the boss wants to go. Functionally, it *is* just one tiny string in one tiny file, so stamping out a full release for that seems a little excessive, but we'll see.

**Comment by uberbrady** [comment]
Fixed in commit #a67ce965ecfe - we just did a commit to master rather than issue a new version. You can do a new `git pull` and yoiu’ll have that version file fixed. Sorry for the inconvenience.
