### ISSUE TITLE
Uploaded Images being given wrong URL - doubled domain name.

### ISSUE THREAD

**Issue by Delbert537** [grokability/snipe-it#9739]
Encountering an issue on a fresh install of Snipe-It. Running on Ubuntu 20.04.

All uploaded images fail to obtain the proper URL and don't load on the website.

It seems to tacking my domain name on twice even when viewing locally via IP. 

"http://inv.loadthevoid.com/inv.loadthevoid.com/uploads/categories/category-image-PCPtVVcUPh.png"
"http://192.168.1.26/inv.loadthevoid.com/uploads/categories/category-image-PCPtVVcUPh.png"

![image](https://user-images.githubusercontent.com/56086850/123169404-e03bac00-d43e-11eb-8558-5f7c363db4fe.png)

The images resolve fine when I manually navigate to the address without the doubled domain name.

Any ideas what could be causing this?

**Comment by snipe** [comment]
This is usually caused by an incorrect APP_URL in your .env

**Comment by Delbert537** [comment]
Currently in my .env I have APP_URL http://inv.loadthevoid.com

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by snipe** [comment]
Do you mean `APP_URL=http://inv.loadthevoid.com` - that equals sign would be important there.

**Comment by Delbert537** [comment]
I was pretty sure I had an = so I checked the .env to confirm and found that I had the = but was missing the http://. After correcting that, images are loading as intended. Thank you!
