### ISSUE TITLE
Snipe-IT Download Page

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#9744]
Sorry to have to post this issue here but I could not find another method to bring this to your attention.

**Issue:**

If you go to https://github.com/snipe/snipe-it/releases/

All the available Snipe-IT releases reside there.

Selecting a desired version, example 5.1.6 brings you to the following URL:

https://github.com/snipe/snipe-it/releases/tag/v5.1.6

This is true for all versions accept 5.1.7

This is not an issue unless you use a homegrown script to update Snipe-IT. 

In the case of version 5.1.7. The download version is missing the "v" before the version number. 

https://github.com/snipe/snipe-it/releases/tag/5.1.7

Instead of

https://github.com/snipe/snipe-it/releases/tag/v5.1.7

Would you please:
1. Fix the link name
2. Provide a method to contact Snipe-IT to report such issues.

![2021-06-24_12-21-51](https://user-images.githubusercontent.com/31219479/123313602-e84f2680-d4e6-11eb-8ed0-960dfa8967b4.jpg)

![2](https://user-images.githubusercontent.com/31219479/123314395-c7d39c00-d4e7-11eb-9983-75e2c46ae9d4.jpg)

**Comment by snipe** [comment]
Hey, thanks for bringing this to our attention. We've corrected that tag name. (It may take a moment to show up on the product website, as we cache GH API results there.)

**Comment by jmartins1** [comment]
Just an fyi.

 

When attempting to go directly to:

https://www.snipeitapp.com/download

I get the following error:



Also, when I go to snipeitapp.com

Sometimes I get a CloudFront page before being redirected.

 



Jose Martins, M.Ed., MCSA, MCP/ IT Systems Administrator
***@***.*** ***@***.***> 
P 720.242.6225

Aspen Ridge Preparatory School
705 Austin Ave. Erie, CO 80516
www.aspenridgeprepschool.org





Statement of Confidentiality

The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.
