### ISSUE TITLE
Feature request: Add notes field to Status Labels index

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#9745]
**Server (please complete the following information):**
 - Snipe-IT Version v5.1.7 - build 6136 (master)
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.4.16

**Describe the solution you'd like**
On the "Status Labels" page in the column selection table, it would be useful to add the ability to display the "Notes" field. So that you can see the description without going into editing "Update Status Label"

**Comment by snipe** [comment]
This is a great suggestion, thanks! I've got a PR up awaiting review: https://github.com/snipe/snipe-it/pull/9761
