### ISSUE TITLE
Upgrading via Git not working

### ISSUE THREAD

**Issue by x3inspire** [grokability/snipe-it#9755]
Hi, i'm using Ubuntu with Litespeed and hosted on AWS.

I execute "php upgrade.php" with root user but getting errro "ERROR: This script should not be run as root/admin. Exiting.".

Then i used this code to execute "sudo -u asetd6144 php upgrade.php" since i checked my owner of directory is asetd6144. But script not successfully upgrade, and here is the log:
 

WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- check your PHP version and extension requirements
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (7.4.19) is at least 7.2.5 - continuing...
FYI: The php.ini used by this PHP is: /usr/local/lsws/lsphp74/etc/php/7.4/litespeed/php.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database asetdemo...
Determining files to backup...
Zipping 75 files and directories...
Created zip containing 75 files and directories. Size is 344.86 KB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!

--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.

--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- -- --
--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ No bootsrap/cache/services.php, so nothing to delete.
√ No bootstrap/cache/config.php, so nothing to delete.

-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

√ Local composer.phar detected, so we'll use that.

-- Updating local composer.phar

You are already using the latest available Composer version 2.1.3 (stable channel).

Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.

  [ErrorException]
  file_put_contents(/home/asetdemo.mydomain.com/public_html/vendor/composer/autoload_psr4.php): failed to open stream: Permission denied

dump-autoload [--no-scripts] [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--apcu-prefix APCU-PREFIX] [--dev] [--no-dev] [--ignore-plaorm-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs]

Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 0 installs, 0 updates, 37 removals
  - Removing theseer/tokenizer (1.2.0)
  - Removing symfony/yaml (v5.2.9)
  - Removing symfony/dom-crawler (v4.4.24)
  - Removing symfony/browser-kit (v5.2.9)
  - Removing softcreatr/jsonpath (0.7.4)
  - Removing sebastian/version (2.0.1)
  - Removing sebastian/type (1.1.4)
  - Removing sebastian/resource-operations (2.0.2)
  - Removing sebastian/object-reflector (1.1.2)
  - Removing sebastian/object-enumerator (3.0.4)
  - Removing sebastian/global-state (3.0.1)
  - Removing sebastian/environment (4.2.4)
  - Removing sebastian/code-unit-reverse-lookup (1.0.2)
  - Removing phpunit/phpunit (8.5.15)
  - Removing phpunit/php-token-stream (3.1.2)
  - Removing phpunit/php-timer (2.1.3)
  - Removing phpunit/php-text-template (1.2.1)
  - Removing phpunit/php-file-iterator (2.0.3)
  - Removing phpunit/php-code-coverage (7.0.14)
  - Removing php-webdriver/webdriver (1.11.1)
  - Removing phar-io/version (3.1.0)
  - Removing phar-io/manifest (2.0.1)
  - Removing overtrue/phplint (2.3.5)
  - Removing n98/junit-xml (1.0.0)
  - Removing myclabs/deep-copy (1.10.2)
  - Removing justinrainbow/json-schema (5.2.10)
  - Removing fzaninotto/faker (v1.9.2)
  - Removing codeception/stub (3.7.0)
  - Removing codeception/phpunit-wrapper (8.1.4)
  - Removing codeception/module-webdriver (1.2.1)
  - Removing codeception/module-rest (1.3.1)
  - Removing codeception/module-laravel5 (1.1.1)
  - Removing codeception/module-asserts (1.3.1)
  - Removing codeception/lib-innerbrowser (1.5.0)
  - Removing codeception/lib-asserts (1.13.2)
  - Removing codeception/codeception (4.1.20)
  - Removing behat/gherkin (v4.8.0)
    Uninstall of theseer/tokenizer failed
    Uninstall of symfony/yaml failed
    Uninstall of symfony/dom-crawler failed
    Uninstall of symfony/browser-kit failed
    Uninstall of softcreatr/jsonpath failed
    Uninstall of sebastian/version failed
    Uninstall of sebastian/type failed
    Uninstall of sebastian/resource-operations failed
    Uninstall of sebastian/object-reflector failed
    Uninstall of sebastian/object-enumerator failed
  0/27 [>---------------------------]   0%    Uninstall of sebastian/global-state failed
    Uninstall of sebastian/environment failed
    Uninstall of sebastian/code-unit-reverse-lookup failed
    Uninstall of phpunit/phpunit failed
    Uninstall of phpunit/php-token-stream failed
    Uninstall of phpunit/php-timer failed
    Uninstall of phpunit/php-text-template failed
    Uninstall of phpunit/php-file-iterator failed

  8/27 [========>-------------------]  29%    Uninstall of phpunit/php-code-coverage failed
    Uninstall of php-webdriver/webdriver failed
    Uninstall of phar-io/version failed
    Uninstall of phar-io/manifest failed
    Uninstall of overtrue/phplint failed
    Uninstall of n98/junit-xml failed
    Uninstall of myclabs/deep-copy failed
    Uninstall of justinrainbow/json-schema failed
    Uninstall of fzaninotto/faker failed
    Uninstall of codeception/stub failed
    Uninstall of codeception/phpunit-wrapper failed
    Uninstall of codeception/module-webdriver failed
    Uninstall of codeception/module-rest failed
    Uninstall of codeception/module-laravel5 failed
    Uninstall of codeception/module-asserts failed
    Uninstall of codeception/lib-innerbrowser failed
    Uninstall of codeception/lib-asserts failed
    Uninstall of codeception/codeception failed
    Uninstall of behat/gherkin failed

 27/27 [============================] 100%

  [RuntimeException]
  Could not delete /home/asetdemo.mydomain.com/public_html/vendor/theseer/tokenizer/LICENSE:

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--nscripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ap-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...

Generating optimized autoload files

--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!

Any help please?

**Comment by x3inspire** [comment]
Any answer?

**Comment by jtoews-boos** [comment]
Did you install using GIT? Have you tried without the user flag?

**Comment by snipe** [comment]
> fatal: not a git repository (or any of the parent directories): .git

Looks like you didn’t install using git. That means you can’t upgrade using git until you switch to a git installation.

**Comment by x3inspire** [comment]
> Did you install using GIT? Have you tried without the user flag?


> > fatal: not a git repository (or any of the parent directories): .git
> 
> Looks like you didn’t install using git. That means you can’t upgrade using git until you switch to a git installation.

Ah yes, for the first time i'm installed using file from the source.

So i still can switch to Git for upgrade version later?

```
php artisan snipeit:backup
git clone https://github.com/snipe/snipe-it your-folder
composer install --no-dev --prefer-source
php upgrade.php
```

**Comment by snipe** [comment]
Yes, you can switch to git later. https://snipe-it.readme.io/docs/switching-to-a-git-install

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/switching-to-a-git-install">Switching to a Git Install</a></strong></div><div>As we mention (several times) throughout the documentation, installing via Git is our recommended way of installing Snipe-IT and keeping it up to date. If you installed manually (downloading a tarball or .zip file from Github), you can still switch to a Git install with just a little work. Doing so ...</div></blockquote>
