### ISSUE TITLE
Importer overwritring last imported asset instead of creating new

### ISSUE THREAD

**Issue by geoffbernard-bw** [grokability/snipe-it#9756]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode  - YES
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) -  YES

**Describe the bug**
I'm using the imported via the web interface to import assets. If I look at the asset history, I can see it's overwriting each imported record with the information for the next record in the CSV. I'm only importing 89 records so I don't think it's an issue with the size of the file. I saw this happen in the past & just put the project on the back burner.  I tried again today and the first import seemed to work find for 14 test records. I'm now importing the remaining items but only the last item is being imported. 
I verified I did not check the box to "update existing values" so I'm not sure why this is happening. I would appreciate any assistance with finding out out why this is happening.

Here is an example: (full screenshot of a single history page is attached)
name: bwtpresley-w10  CLT-HFreitag
model_id: 23  24
serial: R90MGER2  MXL73817H6
location_id: 1  4

**To Reproduce**
1. Prepare a CSV import file with asset data using the template
2. Click on Import
3. Select the CSV file with assets
4. Verify the fields and click import
5. Get success confirmation but only one new asset is shows
6. Review history of the import asset & see the device name, serial were updated with the next record in the CSV.

**Expected behavior**
I expect to see 89 new assets instead of one.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.5
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version 8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 90.0.4430.212 
![chrome_2021-06-27_14-26-16](https://user-images.githubusercontent.com/86569850/123555457-cdcdb500-d753-11eb-98bd-ec91c378e180.png)

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - not getting any error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Unable to reproduce in demo as the import feature is disabled.
- Include any additional information you can find in `storage/logs` and your webserver's logs. Nothing indicating why the error is happening in the logs.
- Include the output from `php -m` (this should display what modules you have enabled.)
- [PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade? Fresh install
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Github install
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - DB has NOT been manually edited

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
@bzeus can you please try to confirm? We haven’t seen this before and have made no important changes to the importer, so I’m not sure what might be happening here.

**Comment by boring10** [comment]
Out of curiosity, could this be related to the asset tag setting for "Generate auto-incrementing asset IDs"?

@bzeus do you have an "Asset Tag" column heading and, if so, can you verify that there is absolutely no value in the cells below the heading? If there are values, I'm assuming that they are all different, correct?

@snipe I'm not really familiar with PHP but if I'm reading the importer correctly, if the asset tag matches an existing asset tag then the importer switches to edit asset instead of creating a new one. What would happen if someone mistakenly left a space in each cell for the asset tag?

**Comment by geoffbernard-bw** [comment]
@boring10 I think you are on to something. I was originally going to delete the record that was being updated so I could try the import again and got a message that Asset Tag was a required field. That field was indeed blank in my import CSV because we didn't have tags yet but in my first import, I though I would be clever and just add some auto-numbered data. So in the import file I'm using, I went ahead & added some bogus auto-numbered tags (starting at a # higher then the original import) and sure enough - the assets imported as expected.

Like you, I'm not familiar with PHP but in the code, the expected behavior is for the importer is to create a new asset if a matching asset tag isn't found. I'm just curious how that's possible if Asset tag is a required field (as I found when editing an asset.)

Thoughts?

**Comment by boring10** [comment]
@geoffbernard-bw under <your_domain>/admin/asset_tags do you have the "Generate auto-incrementing asset IDs" checked or unchecked?

![Screenshot from 2021-06-28 09-05-02](https://user-images.githubusercontent.com/35600612/123641177-f99e7880-d7ef-11eb-8573-2b7c6674130f.png)

I may be wrong, but if the auto increment asset IDs is checked then you may be able to leave the Asset Tag field off but I haven't tried it. That setting may only work for creating single assets or using the API (both of which I know auto increment for us properly with v5.1.6).

**Comment by geoffbernard-bw** [comment]
@boring10 Generate auto-incrementing asset IDs is checked. I'm guessing that setting is only taking effect for single assets and not when using the CSV import. The last asset I imported had a value of 104 and that screen shows 106 will be the next asset tag assigned.

![image](https://user-images.githubusercontent.com/86569850/123657296-abdd3c80-d7fe-11eb-946b-de0108428e41.png)

**Comment by boring10** [comment]
You can show the ID by adding the column to your view. This ID is from the database and increments with every asset that you add and is no re-used. Look to see if you can see an ID of 105 or not.

![Screenshot from 2021-06-29 09-33-34](https://user-images.githubusercontent.com/35600612/123806648-22d90a80-d8bd-11eb-9422-4fc08b6beab2.png)

You can also just manually adjust the next auto-increment to 105 so that it starts from there.
