### ISSUE TITLE
Post update import problem

### ISSUE THREAD

**Issue by enesbutunn** [grokability/snipe-it#9758]
After the Snipe IT 5.1.7 update, the "import" screen returns the attached errors.
No data entry is made.

![image](https://user-images.githubusercontent.com/79334518/123629514-09808180-d81d-11eb-97d0-4b1a1f5e4991.png)
![image](https://user-images.githubusercontent.com/79334518/123629580-1b622480-d81d-11eb-89b2-9fb2160f241a.png)

**Comment by cloudymcduck** [comment]
I have been having issues posting to Snipe using the API and just cannot get it to work. Saw this issue and confirmed the page is blank for us as well. Wondering if it's related to my issue...

**Comment by snipe** [comment]
This is resolved in 5.1.8

**Comment by snipe** [comment]
Duplicate of #9743
