### ISSUE TITLE
Invalid Barcode Error

### ISSUE THREAD

**Issue by whatiscybersecurity** [grokability/snipe-it#9771]
#### Expected Behavior (or desired behavior if a feature request)

Trying to generate barcodes for our assets.

-----

#### Actual Behavior

I am getting an invalid barcode error on a fresh install. Read the common issues about APP_URL, but it is still not working. Using EAN5 and our asset ID is all numbers (limit of 5 digits).

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running: 5.1.8
- Version of PHP you're running: 7.2.24-0ubuntu0.18.04.7
- Version of MySQL/MariaDB you're running: 5.7.34
- What OS and web server you're running Snipe-IT on: Ubuntu, Apache 2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: https://(HOST IP)/hardware
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.: "Invalid Barcode"
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.: Not reproducible
- Include any additional information you can find in `storage/logs` and your webserver's logs.: N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.: Made sure APP_URL is the exact same as the URL we access it from (https://(HOST IP)
- Indicate whether or not you've manually edited any data directly in the database: No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help
![Screenshot_1](https://user-images.githubusercontent.com/52930971/123864257-68a6ca80-d8df-11eb-94b0-48cb9514cdb0.png)

**Comment by uberbrady** [comment]
[EAN5 seems to have some limits](https://en.wikipedia.org/wiki/EAN-5) on which codes you can actually use - specifically the first digit. Do any other barcodes work for you? Do any of your asset tags start with 2 or 7, 8, or 9?

in the Settings section, under Bar codes, there's also a "delete cached bar codes" button - definitely click that any time you change formats.

**Comment by whatiscybersecurity** [comment]
> [EAN5 seems to have some limits](https://en.wikipedia.org/wiki/EAN-5) on which codes you can actually use - specifically the first digit. Do any other barcodes work for you? Do any of your asset tags start with 2 or 7, 8, or 9?
> 
> in the Settings section, under Bar codes, there's also a "delete cached bar codes" button - definitely click that any time you change formats.

I have tried every barcode type and hit the "delete cached bar codes" button after every try but no luck. Also tried it in incognito mode on Chrome.
We only have 1 asset right now, which starts with 0 (00002). Our assets have a character limit of 5 on the app.

**Comment by uberbrady** [comment]
What happens if you re-run upgrade.php - (you might have to run it twice) - that has a built-in feature that should check that you have either gd or imagemagick installed - one of those libraries is needed for you to be able to generate bar codes - and if you're not able to generate any of the barcode types, I worry that you might be missing that dependency.

**Comment by whatiscybersecurity** [comment]
> What happens if you re-run upgrade.php - (you might have to run it twice) - that has a built-in feature that should check that you have either gd or imagemagick installed - one of those libraries is needed for you to be able to generate bar codes - and if you're not able to generate any of the barcode types, I worry that you might be missing that dependency.

The imagemagick library is installed.

Here are the errors we get with debug mode on:
**production.ERROR: file_put_contents(/var/www/snipeit/public/uploads/barcodes/qr-00002-2.png): failed to open stream: Permission denied {"userId":1,"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/snipeit/public/uploads/barcodes/qr-00002-2.png): failed to open stream: Permission denied at /var/www/snipeit/app/Http/Controllers/Assets/AssetsController.php:457)**

and

**production.ERROR: ErrorException: file_put_contents(/var/www/snipeit/public/uploads/barcodes/qr-00002-2.png): failed to open stream: Permission denied in /var/www/snipeit/app/Http/Controllers/Assets/AssetsController.php:457"}**

**Comment by godnroc** [comment]
I'm new to all this and just setup a server myself, but that sounds like a similar issue I was having with permissions for the public directory. You can run `ls -la /var/www/snipeit/public/uploads` to view the permissions for everything in the uploads directory including where the barcodes are stored.

Here is a link to the docs with some more information: [https://snipe-it.readme.io/docs/debugging-permissions#fixing-it](https://snipe-it.readme.io/docs/debugging-permissions#fixing-it)

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/debugging-permissions#fixing-it">Debugging Server Permissions</a></strong></div><div>One of the most common issues folks newer to running web servers run into is how to manage the Linux/Windows/etc owners and groups of the Snipe-IT filesystem. As we mention many times in the installation documentation, nothing in Snipe-IT should be run as or owned by root. Running composer as root, ...</div></blockquote>

**Comment by uberbrady** [comment]
Yes, those errors definitely are saying that your webserver can't write to the `public/uploads` directory. Does it work now? If so, please do close the issue - and thanks for writing down what worked for you - I'm sure that will help someone else, too!

**Comment by Weaksid** [comment]
@Proph3tt 
Did you get this fixed? If so, what did you do? We have the exact same issue and errors. I've been quadruple checking the permissions and not sure what I'm missing. I even followed what GodnRoc posted. 
I'm using CentOS8 instead of Ubuntu which is a difference. 
Thanks in advance.

**Comment by uberbrady** [comment]
Double check who your webserver is running as, and if you're using php-fpm who *that* is running as. That's the person who needs to own some of those directories to be able to write to them.

**Comment by Weaksid** [comment]
Looks like the httpd service is running as the user apache. I followed those rights in the debugging-permissions documentation that was posted. Is the my-user and your-linux-user the same user? Then the www-data would be apache for my setup by what I can tell by using command "lsof -i | grep :http" . Thank you for your help. I appreciate it. This issue has been driving me crazy.

**Comment by uberbrady** [comment]
If you're using Apache, you're very likely *not* using php-fpm (though I would double-check were I you). Then check each directory, methodically, for who owns it and what the permissions are.

check out /var/www/snipeit, /var/www/snipeit/public, /var/www/snipeit/public/uploads - then keep going. Use the error messages in the logs as a guide.

If you want to look at a directory without looking at the *contents* of the directory, use `ls -ld dirname`

**Comment by Weaksid** [comment]
Thanks for the help and info. I found my instructions I followed for my install -> https://computingforgeeks.com/install-snipe-it-asset-management-on-centos-8-linux/ . It looks like I needed to use apache as the owner, however that wasn't the fixed. It did at least put it back to where it needed to be. Out of curiosity and came across another person that had the issue with SELinux. I disabled it temporarily and it's now showing barcode images and allowing Avatar uploads. Seems like I had two issues but the main I think was that the security on the server was preventing the script from running. I just need to see if the instructions of my initial setup fixes the firewall issue or if I need to find a different way to allow snipe to run it's script with SELinux enabled.

<blockquote></blockquote>

**Comment by uberbrady** [comment]
Definitely do let us know how it goes. SELinux is definitely a tough one. We have some docs on that here: https://snipe-it.readme.io/docs/linuxosx#notes-on-selinux

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/linuxosx#notes-on-selinux">Linux/OSX</a></strong></div><div>Setting up a web server can sound daunting for folks who don't normally do that kind of thing. This guide will help you walk through the configuration for Apache or Nginx on Linux and OSX. The most common setup for Snipe-IT on a linux server is to use Apache, so if you're not sure what to pick, Apac...</div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
