### ISSUE TITLE
Switching to Git Install Crashes SnipeIT

### ISSUE THREAD

**Issue by jackd268** [grokability/snipe-it#9775]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I followed the steps to switch my install to Git install so that I could run the upgrade command but getting error 500 Server.

**To Reproduce**
I was following these steps: https://snipe-it.readme.io/docs/switching-to-a-git-install

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.4
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 20
 - Web Server: [e.g. Apache, IIS] Apacher 5
 - PHP Version 7.x

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.permission_groups' doesn't exist (SQL: select `permission_groups`.*, `users_groups`.`user_id` as `pivot_user_id`, `users_groups`.`group_id` as `pivot_group_id` from `permission_groups` inner join `users_groups` on `permission_groups`.`id` = `users_groups`.`group_id` where `users_groups`.`user_id` = 169)
Previous exceptions
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.permission_groups' doesn't exist (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.permission_groups' doesn't exist (42S02)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Did you run migrations ?

**Comment by jackd268** [comment]
I did not see that in the instructions here https://snipe-it.readme.io/docs/switching-to-a-git-install
How do I do that?

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/switching-to-a-git-install">Switching to a Git Install</a></strong></div><div>As we mention (several times) throughout the documentation, installing via Git is our recommended way of installing Snipe-IT and keeping it up to date. If you installed manually (downloading a tarball or .zip file from Github), you can still switch to a Git install with just a little work. Doing so ...</div></blockquote>

**Comment by jackd268** [comment]
I ran the command php artisan migrate and got the following output:

**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migrating: 2016_06_01_000001_create_oauth_auth_codes_table
Migrated:  2016_06_01_000001_create_oauth_auth_codes_table (0.04 seconds)
Migrating: 2016_06_01_000002_create_oauth_access_tokens_table
Migrated:  2016_06_01_000002_create_oauth_access_tokens_table (0.02 seconds)
Migrating: 2016_06_01_000003_create_oauth_refresh_tokens_table
Migrated:  2016_06_01_000003_create_oauth_refresh_tokens_table (0.02 seconds)
Migrating: 2016_06_01_000004_create_oauth_clients_table
Migrated:  2016_06_01_000004_create_oauth_clients_table (0.02 seconds)
Migrating: 2016_06_01_000005_create_oauth_personal_access_clients_table
Migrated:  2016_06_01_000005_create_oauth_personal_access_clients_table (0.01 se                                                                                                             conds)
Migrating: 2018_04_02_150700_labels_display_model_name

   UnexpectedValueException  : The stream or file "/var/www/snipeit/storage/logs                                                                                                             /laravel.log" could not be opened in append mode: Failed to open stream: Permiss                                                                                                             ion denied

  at /var/www/snipeit/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.p                                                                                                             hp:111
    107|             restore_error_handler();
    108|             if (!is_resource($this->stream)) {
    109|                 $this->stream = null;
    110|
  > 111|                 throw new \UnexpectedValueException(sprintf('The stream                                                                                                              or file "%s" could not be opened in append mode: '.$this->errorMessage, $this->                                                                                                             url));
    112|             }
    113|         }
    114|
    115|         if ($this->useLocking) {

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/snipeit/vendor/monolog/monolog/src/Monolog/Handler/AbstractProces                                                                                                             singHandler.php:42

  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/snipeit/vendor/monolog/monolog/src/Monolog/Logger.php:317

  Please use the argument -v to see more details.

**Comment by jackd268** [comment]
Still getting the following error output:

Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.permission_groups' doesn't exist (SQL: select `permission_groups`.*, `users_groups`.`user_id` as `pivot_user_id`, `users_groups`.`group_id` as `pivot_group_id` from `permission_groups` inner join `users_groups` on `permission_groups`.`id` = `users_groups`.`group_id` where `users_groups`.`user_id` = 169)
Previous exceptions
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.permission_groups' doesn't exist (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.permission_groups' doesn't exist (42S02)

**Comment by snipe** [comment]
Are you still having issues with this? (Trying to clean up older tickets.)
