### ISSUE TITLE
Wrong User Language 

### ISSUE THREAD

**Issue by tom-sin** [grokability/snipe-it#9776]
- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Hi,

Our users received the "Check in/out message" in the wrong language. Our default language in "settings --> localization" ist set to german. If we look at the users language it is set to english. In the ".env" file the APP_LOCALE variable is also set to "de".

Where we can change the default language for all users to german?

**Server (please complete the following information):**
 - v5.1.8 - build 6148 (master)
 - OS: Windows Server 2019 
 - Web Server: IIS
 - PHP 7.3.10

![image](https://user-images.githubusercontent.com/59007194/124081111-6a8d9c80-da4b-11eb-820d-c70b43cdb444.png)
![image](https://user-images.githubusercontent.com/59007194/124081262-9b6dd180-da4b-11eb-8d37-880c7bf11dce.png)
![image](https://user-images.githubusercontent.com/59007194/124081332-b2acbf00-da4b-11eb-86d2-4075e6ed7da2.png)

**Comment by umitsari** [comment]
(We re same, on ubuntu 20.0.4) 
Hello there i was used "Email List of All Assigned " buton to notification for users at Turkish Language. I  updated snipe it at  Version v6.2.3 - build 11936 (master) then the notification couldn't reach in turkish, only english. I tried the change localization settings and profile settings english to turkish but never changed received mails languages.

**Comment by snipe** [comment]
There are [three different places](https://snipe-it.readme.io/docs/localization) where language can be set. First is the env, second is the settings, and third is the user's profile. You can use the bulk edit option to change everyone's language explicitly to German. Do be aware that there may be language strings we have that have not yet been translated (especially true for newer strings.)

**Comment by snipe** [comment]
(Also, you're running v5, which is several years old. You should probably consider updating.)
