### ISSUE TITLE
Import Page is Blank

### ISSUE THREAD

**Issue by cringerjs** [grokability/snipe-it#9780]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The import page is blank

**To Reproduce**
1. Log on
2. Click on 'Import'

**Expected behavior**
I should see the importer

**Screenshots**
Literally just says Import and the rest is blank

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.7 - build 6136
 - OS: [e.g. Ubuntu, CentOS] - Ubuntu 20.04.2 LTS
 - Web Server: [e.g. Apache, IIS] Nginx
 - PHP Version: 7.4.3

**Error Messages**
- Any errors that appear in your browser's error console.
```
all.js?id=a984b7f99966cea1edbb:1 ReferenceError: importErrors is not defined
    at s.render (eval at Po (all.js?id=a984b7f99966cea1edbb:1), <anonymous>:3:399)
    at s.t._render (all.js?id=a984b7f99966cea1edbb:1)
    at s.n (all.js?id=a984b7f99966cea1edbb:1)
    at fe.XuX8.fe.get (all.js?id=a984b7f99966cea1edbb:1)
    at new fe (all.js?id=a984b7f99966cea1edbb:1)
    at all.js?id=a984b7f99966cea1edbb:1
    at s.XuX8.ze.$mount (all.js?id=a984b7f99966cea1edbb:1)
    at s.XuX8.ze.$mount (all.js?id=a984b7f99966cea1edbb:1)
    at init (all.js?id=a984b7f99966cea1edbb:1)
    at all.js?id=a984b7f99966cea1edbb:1
```
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
  No the importer actually loads
- Include any additional information you can find in `storage/logs` and your webserver's logs.
  No error listed in the log
- Include the output from `php -m` (this should display what modules you have enabled.)
  [PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install
- What OS and web server you're running Snipe-IT on: Ubuntu using Nginx
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual Installation
- Include what you've done so far in the installation, and if you got any error messages along the way.
  Installation is complete and I can log in.  For the most part everything is working.
- Indicate whether or not you've manually edited any data directly in the database
  I have not manually edited any data.  Haven't even been able to import data yet.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by godnroc** [comment]
This was fixed in the 5.1.8 release.

Upgrading guide: [https://snipe-it.readme.io/docs/upgrading](https://snipe-it.readme.io/docs/upgrading)

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div> Always backup your database and configuration files before upgrading. We try very hard to make sure that all database changes are non-destructive, but you should always backup beforehand anyway. You will never regret backing up your database. You may regret not doing so, so it’s just better to get ...</div></blockquote>

**Comment by MournfulRaven** [comment]
> This was fixed in the 5.1.8 release.
> 
> Upgrading guide: https://snipe-it.readme.io/docs/upgrading
> 
> > <img alt="" width="48" src="/favicon.ico">Snipe-IT Documentation**[Upgrading](https://snipe-it.readme.io/docs/upgrading)** Always backup your database and configuration files before upgrading. We try very hard to make sure that all database changes are non-destructive, but you should always backup beforehand anyway. You will never regret backing up your database. You may regret not doing so, so it’s just better to get ...

It wasn't. I have 5.1.8 with the same problem. Clicking 'Process' button in Import page do nothing.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div> Always backup your database and configuration files before upgrading. We try very hard to make sure that all database changes are non-destructive, but you should always backup beforehand anyway. You will never regret backing up your database. You may regret not doing so, so it’s just better to get ...</div></blockquote>

**Comment by arthurkrupa** [comment]
> It wasn't. I have 5.1.8 with the same problem. Clicking 'Process' button in Import page do nothing.

Same here. 5.1.8, hosted version.

**Comment by tamasberesoebb** [comment]
Same here. 5.1.8, hosted version.

**Comment by samotelf** [comment]
Same here. 5.1.8, hosted version.
I can import the file but when i click in process nothing happens.

**Comment by AbhimanyuNeupane** [comment]
Same here. V5.1.8, hosted version. 
nothing when click process

**Comment by uberbrady** [comment]
Those of you who are hosted with us should let us know at support@snipeitapp.com and tell us your subdomain and we'll get you updated right away.

**Comment by snipe** [comment]
This is fixed on master and develop
