### ISSUE TITLE
LDAP integration showing different location for peoples-Version v4.7.7 - build 4160

### ISSUE THREAD

**Issue by vyshnavdinesh** [grokability/snipe-it#9781]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode -no
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)-yes

**Describe the bug**
LDAP integration showing wrong location for peoples.

**To Reproduce**
1. Go to 'settings'
2. Click on 'LDAP'

**Expected behavior**
 LDAP syncing with correct location of the users.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version -v4.7.7 - build 4160
 - OS: [e.g. Ubuntu, CentOS]  Ubuntu 16.04
 - Web Server: [e.g. Apache, IIS]Apache
 - PHP Version 7.1.2

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? fresh
- What OS and web server you're running Snipe-IT - ubuntu 16.04,apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual installation
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Hi there - Pretty sure this has been working for a long time now, sorry for not closing this sooner. I'm going to close this. Please feel free to open a new issue if you're still having trouble.
