### ISSUE TITLE
Hide Product Key From End Users

### ISSUE THREAD

**Issue by WELLBOREIS** [grokability/snipe-it#9785]
**Server (please complete the following information):**
 - Snipe-IT Version: 5.1.8
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.4.21

**Is your feature request related to a problem? Please describe.**
Sort of.....I have two options at the moment for checking out licenses that use 1 universal Product Key:
1. Not put the product key in Snipe-IT so the end-user won't see the Product Key
2. Put the product key in Snipe-IT, however disable checkout notifications via e-mail

**Describe the solution you'd like**
It would be nice if there was an option to hide the Product Key from the end-users.

**Describe alternatives you've considered**
1. Not put the product key in Snipe-IT so the end-user won't see the Product Key
2. Put the product key in Snipe-IT, however disable checkout notifications via e-mail

**Comment by VocalZero** [comment]
The same for us. We often have licenses with more than one seat and the user should not be able to see our license key. Not in SnipeIT and also not in the e-mail.

I would be happy if something could be implemented for this.

**Comment by snipe** [comment]
@VocalZero That's already a feature. 

<img width="851" alt="Screenshot 2024-05-23 at 10 10 27 AM" src="https://github.com/snipe/snipe-it/assets/197404/ad8da989-4518-4fe8-a518-2626ad87f290">
