### ISSUE TITLE
Thousands of session files are created by AWS loadbalancer health check

### ISSUE THREAD

**Issue by leonardopech** [grokability/snipe-it#9787]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Several session files are created when a AWS loadbalancer healthcheck is setup to monitoring is Snipe-IT is alive. 

**To Reproduce**
1. Snipe-IT running in a Docker container over a CentOS server in AWS (
2. AWS load balancer with HTTP 200 heath check enabled pointing to Snipe-IT server
3. When load balancer health check is triggered, coupple session files are created "framework/sessions" folder, but never are destroyed.
4. I found thousands of these session files and my Snipe-IT app was getting slower and sometimes I got "504 gateway time out" error

**Expected behavior**
Session files should be destroyed or cleaned after expiration or valid timeout

**Screenshots**
![image](https://user-images.githubusercontent.com/52260498/124512047-19f4a700-dd9d-11eb-95b2-fe8a9f9f6b23.png)
![image](https://user-images.githubusercontent.com/52260498/124512198-6b9d3180-dd9d-11eb-8e19-7658c6952e27.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.8 build 6148 (g3ca3de9e4)
 - OS: Alpine Linux
 - Web Server: nginx
 - PHP Version 7.4.20
 - Docker container (https://hub.docker.com/r/linuxserver/snipe-it)

**Comment by royalpenguin** [comment]
I can confirm this issue also in a Prometheus + Blackbox Exporter setup targeting the login page of the snipe-it instance. After getting slow and failed probes, an inspection of the `framework/sessions` directory revealed over 100k session files.

The CLI command `snipeit:global-logout --force` only temporarily resolves the slow probes by deleting the session files.

**Server:**
* v5.4.2 - build 6805 (master)
* OS: Ubuntu 20.04
* Web Server: nginx
* PHP Version: 7.4
* Docker container: snipe/snipe-it:v5.4.2

**Comment by uberbrady** [comment]
You can use the healthcheck endpoint instead which won't create sessions - `/health` - that should work better.

**Comment by snipe** [comment]
Yes, this is the recommended solution.

**Comment by royalpenguin** [comment]
Thanks! I wasn't able to find this in the read-me.

**Comment by vicleos** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
