### ISSUE TITLE
Can't process imported file - Version v5.1.8 - build 6148 (master)

### ISSUE THREAD

**Issue by samotelf** [grokability/snipe-it#9788]
#### Please confirm you have done the following before posting your bug report:

- [ x ] I have enabled debug mode 
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Can't process imported file to massive asset creation.
File is successfully uploaded to /var/www/html/snipeit/storage/private_uploads/imports
Similar to https://github.com/snipe/snipe-it/issues/9780

**To Reproduce**
1. Go to 'Import'
2. Click on 'Select Import File'
3. Click "Process"
4. Process window won't open

**Expected behavior**
Importer window should open

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version - Version v5.1.8 - build 6148 (master)
 - OS: [e.g. Ubuntu, CentOS]  -CentOS7
 - Web Server: [e.g. Apache, IIS] - Apache
 - PHP Version - PHP 7.3.6 (cli) (built: May 28 2019 09:32:59) ( NTS )

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10
 - Browser [e.g. chrome, safari] - Chrome
 - Version [e.g. 22] - Version 91.0.4472.77 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error.
- Can't find any error.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- - Can't find any error.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- No, because the feature is disabled in demo version
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib
[Zend Modules]

**Additional context**
- Is this a fresh install or an upgrade? - Upgrade
- What OS and web server you're running Snipe-IT on - Centos7 + Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by backlands** [comment]
Since the fix looks to be applied to develop in the referenced merge request I wanted to quickly ask.

We're just starting out configuring a new Snipe-IT hosted instance for internal testing and this bug is blocking me from importing assets. I am wondering as a Hosted user what the timeline is for fixes like these to come to the Hosted instances? Couldn't find timelines for that sort of patch in the docs or where I was looking on the website so thought I would quickly ask what can be expect moving forward! Thanks in advance.

**Comment by snipe** [comment]
@backlands if you send us an email with your hosted URL, we can get you updated ASAP

**Comment by snipe** [comment]
(This fix is on develop and master now)
