### ISSUE TITLE
[Feature request]: components: duplicating, notes, model

### ISSUE THREAD

**Issue by mtettke123** [grokability/snipe-it#9792]
**Server (please complete the following information):**
 Version v5.1.7 - build 6136 (master) (docker)

**Is your feature request related to a problem? Please describe.**
Missing features, no real problem

**Describe the solution you'd like**

1. assets have the possiblity to be duplicated, so that a couple of items don't have to be created from scratch. There is no "duplicate" button for components. 
2. assets have a "note" field, there is no note field for components
3. assets have models, components not, although models seem to make sense especially for components

Solutions would be to have similar possibilities for components as for models.

**Describe alternatives you've considered**
Alternative 1: use other fields for components. Copy line by line if no duplicating exists.
Alternative 2: use assets for components.

**Comment by tglassburn** [comment]
I'd like to see this implemented as well.

**Comment by snipe** [comment]
This is not on the short term roadmap. When people need notes, models, etc they just track the component as an asset.
