### ISSUE TITLE
[Feature request] API method for assets where location 

### ISSUE THREAD

**Issue by Ajtak** [grokability/snipe-it#9794]
**Server (please complete the following information):**
 - Snipe-IT Version 5.1.8
 - OS: [e.g. Ubuntu, CentOS] Any
 - Web Server: [e.g. Apache, IIS] Any
 - PHP Version Any

**Is your feature request related to a problem? Please describe.**
Hi. I'm creating app, which uses SnipeIT API and I need get assets and assigned assets for selected location. On now, I'm getting only counts, But not enough for me. I'm saw into [/routes/api.php](../blob/master/routes/api.php), and this file contains routes `/locations/{location}/assets`. But uses method is not implemented, in `LocationsController@getDataViewAssets`

![image](https://user-images.githubusercontent.com/4963819/124620542-d3c14580-de79-11eb-8fb0-f16c15f33b4b.png)

**Describe the solution you'd like**
Add function `getDataViewAssets()` into [/app/Http/Controllers/Api/LocationsController.php](../blob/master/app/Http/Controllers/Api/LocationsController.php) /app/Http/Controllers/Api/LocationController.php

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by PetriAsi** [comment]
There's already location_id parameter for GET request to /api/v1/hardware that  restrict asset results to this location ID
does that fit your needs?
 
https://snipe-it.readme.io/reference#hardware-list


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference#hardware-list">Overview</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>

**Comment by Ajtak** [comment]
> There's already location_id parameter for GET request to /api/v1/hardware that restrict asset results to this location ID
> does that fit your needs?
> 
> https://snipe-it.readme.io/reference#hardware-list
> 
> > <img alt="" width="48" src="/favicon.ico">Snipe-IT Documentation**[Overview](https://snipe-it.readme.io/reference#hardware-list)**Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.

Yes, this is usable. I'm missing this param on hardware request.
