### ISSUE TITLE
Can sync AD but cannot login

### ISSUE THREAD

**Issue by briansmith8129** [grokability/snipe-it#9802]
#### Please confirm you have done the following before posting your bug report:

- [Y] I have enabled debug mode 
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Test LDAP Synchronization works perfectly.
Test LDAP Login fails with any user listed in the results from the LDAP Sync test.

**To Reproduce**
1. Go to Settings
2. Click on LDAP/Active Directory
3. Scroll down to Test LDAP Sync
4. Click Test LDAP Synchronization...Success
5. Scroll down to Test LDAP Login
4. Enter valid AD credentials
5. Click Test LDAP
6. Error: Unable to validate user credentials!

**Expected behavior**
Upon clicking Test LDAP button, expecting: Login failed or User authenticated successfully

**Screenshots**
[https://i.imgur.com/jQPHtZW.png](url)
[https://i.imgur.com/qJPXS5A.png](url)
[https://i.imgur.com/DD8Uoun.png](url)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.8
 - OS: Ubuntu 20.04
 - Web Server: Apache 2.4.41
 - PHP Version 7.4.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge Chromium
 - Version 91.0.864.64

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
[15:27:20] LOG.debug: Preparing to test LDAP login
DEBUGLOG[15:27:20] LOG.debug: Connection failed
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
Failed to load resource: the server responded with a status of 400 (Bad Request) http://10.19.0.25/api/v1/settings/ldaptestlogin
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Not able to test AD integration.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)
rootuser@dev-snipe-it:/var/www/snipe-it/storage/logs$ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade?
Fresh
- What OS and web server you're running Snipe-IT on
Ubuntu Server 20.04 LTS
Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual following the instructions found here: https://www.vultr.com/docs/how-to-install-snipe-it-on-ubuntu-20-04
- Include what you've done so far in the installation, and if you got any error messages along the way.
Installation went smooth with no errors.
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by uberbrady** [comment]
If you're using sAMAccountName as your user ID attribute, turning on "Append domain name" can often be the ticket. Also make sure that your username field is all-lowercase, and your LDAP Authentication query is mixed-case, with an '=' at the end of it (usually).

Another trick - make sure to save your changes *before* trying to do the test. It's annoying, but that's how it works - and that does definitely throw people.

**Comment by briansmith8129** [comment]
Thanks @uberbrady. I forgot to mention in my submission that I have tried enabling the "Append domain name" option with the same result. The username and LDAP authentication query fields are already set as you suggested, as shown in the included screenshots.

I also have been saving every change before testing and so far I have not been able to successfully complete a test LDAP login.

Also, this is my 2nd fresh installation, one in a production environment and the 2nd in a test environment, and both are experiencing the exact same issue.

**Comment by briansmith8129** [comment]
Ok, so like others here, I misinterpreted the note under the "Append domain name" box. After ticking that box and entering my test username of "b.test" it successfully logged in.

Closing case.

**Comment by snipe** [comment]
@briansmith8129 thanks for the feedback. Is there better phrasing that you might recommend to make this clearer?

(We're hopefully going to be revamping the LDAP settings stuff for v6, so we have an opportunity to make a lot of things better there...)
