### ISSUE TITLE
Assign/Unassign licence issue

### ISSUE THREAD

**Issue by EGTITS** [grokability/snipe-it#9816]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to 'Assets -> List All'
2. Find some asset (lets call it test01) Click on 'Assign' and assign the asset to some user (user1)
3. Go to 'Licenses'
3. Find some license (lets call it license01) Click on 'Assign' and assign the license to asset test01
3. At this stage the license 01 is asigned on both the user01 and asset test01
4. Unassign the asset01 from user01. At this stage the license01 is still assigned to user01 and the asset01

**Expected behavior**
We are expecting the following: If the software license is assigned to some hardware asset after the asset is assigned to the user, the license should be assigned only to the hardware asset.

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.7 - this behavior is seen in all version since we are using Snipe-IT (4.x)
 - OS: [Debian]

**Comment by EGTITS** [comment]
![9](https://user-images.githubusercontent.com/33325020/125296830-59883980-e32f-11eb-99d0-142df742f1ae.PNG)
![2](https://user-images.githubusercontent.com/33325020/125296836-5ab96680-e32f-11eb-9d6b-d9256f302857.PNG)
![3](https://user-images.githubusercontent.com/33325020/125296838-5ab96680-e32f-11eb-84a2-63c0cf48cbaa.PNG)
![4](https://user-images.githubusercontent.com/33325020/125296839-5ab96680-e32f-11eb-9497-edafc20d9b89.PNG)
![5](https://user-images.githubusercontent.com/33325020/125296841-5b51fd00-e32f-11eb-8f8b-1806038208de.PNG)
![6](https://user-images.githubusercontent.com/33325020/125296824-58570c80-e32f-11eb-80fc-fb72984902a3.PNG)
![7](https://user-images.githubusercontent.com/33325020/125296828-59883980-e32f-11eb-805f-7e5c883b936e.PNG)
![8](https://user-images.githubusercontent.com/33325020/125296833-5a20d000-e32f-11eb-85cf-088982bb9f69.PNG)

![1](https://user-images.githubusercontent.com/33325020/125296835-5a20d000-e32f-11eb-8682-3b8c836743ad.PNG)
![10](https://user-images.githubusercontent.com/33325020/125296832-59883980-e32f-11eb-87d7-815a39e5d7ea.PNG)

**Comment by EGTITS** [comment]
Any update here?

**Comment by adagioajanes** [comment]
@dstaykov I highly recommend first upgrading to the latest release. There are several bug fixes that have been released since 5.1.7, and one of them may fix your issue.

If you are still having problems after the upgrade, I will take a deeper look at the code to see if I can see what's happening.

**Comment by EGTITS** [comment]
Yes, we keep our installations up to date, and we can confirm that this bug is still not fixed.
We want to keep the licenses stuck to the hardware asset and not to the person (if the initial assignment was on the asset).
Currently if we assign the licenses to the hardware asset while the hardware asset is assigned to the person, when we unassign the hardware asset from the person,  the software assets (the last assigned software licenses ) remains assigned to the person and not to the hardware asset.

**Comment by adagioajanes** [comment]
@dstaykov I have stood up the latest version, and performed the test using the steps you provided. The asset is unassigning correctly from both the asset and the user. Are you 100% sure you are on the latest version? What is your version number at the bottom of your admin panel?

**Comment by adagioajanes** [comment]
OH! Nevermind! You are correct. I followed your steps incorrectly.

I have unassigned the asset from the user, and the license that is assigned to the asset is still tied to the user.

This is indeed behaving like you have described. If the license is a device license, it should be tied to the asset, and not the user. If the asset is unassigned, the license should no longer show on the user list. But it should still show as assigned to the asset.

I am not 100% sure of the fix.

**Comment by EGTITS** [comment]
Hi I am glad that you hit it 🙂
I am not sure what is the correct behaviour.

Scenario 1:
We have a new employee who starts today. We equip him with a brand-new laptop with built-in OS and an MS Office pack. We assign the office pack to the asset (it’s not a O365 license). We assign the asset to the employee. He accepts it with a digital sign. A few days later he wants to use AutoCAD. We assign the license to the asset again.
In a few weeks the management decides to fire the employee. We will have to unassign the asset from the user. The office pack license will stay tied to the asset which is correct, but the license for AutoCAD will remain tied to the user - which is wrong. It would probably be better if the snipeit doesn’t tie the software to the user also when it is tied to the hardware asset.

Scenario 2:
The situation is the same - new employee, OS, MS Office pack, the asset is assigned to the user and accepted with digital sign. But the user requests to use AutoCAD - we unassign the asset from the user, after this we assign the AutoCAD license to the asset and re-assign the asset to the user. In this case everything is OK, but the user has to accept the asset with the new AutoCAD software.
That is the expected behaviour to a degree because the first acceptance was without the AutoCAD license, however this spurts questions of the "why should I accept the same hardware twice" type. All in all – not a big deal of an issue.

Scenario 3:
The situation is the same - new employee, OS, Office pack, but the AutoCAD software is requested after the asset is assigned to the user and still NOT accepted with digital sign. We unassign the asset from the user, after this we assign the AutoCAD to the asset and re-assign the asset the user. In this case the user has to accept the asset only once but it shows twice in the report with unaccepted assets. In the same time the user notification is for only one awaiting accepting. So, after the user accept the real assigned asset and he has nothing else for accepting, the report still shows that the asset is not accepted. Here is the big problem - I have to clear the wrong unaccepted assets manually from phpmyadmin for example. Here the issue is that if I assign an asset to an employee and unassign it before the user accepts it than the acceptance record should be cleared from the report.

Scenario 4:
Why do we not assign the software assets only to the users?
Although most software developers are changing their licensing policies to being based on the number of users (and it looks like that it is better to attach the software to the user) we prefer to attach the licenses to the device itself, because that way we have a complete view of which each license and it’s corresponding asset.
-Some users have more than one asset (pc and notebook for example) and after a few ownership changes we end up with a total mess in software management and we really do not know which software is used where.
-If the employee leaves the company it will be easier to detach the asset from one employee and attach it to another together with all of the software assets.
We prefer to attach the software assets to the hardware and not to the users. If we assume that scenario 2 is OK then the bugs from scenario 1 and scenario 3 have to be fixed.

**Comment by EGTITS** [comment]
HI all, 
this issue is fixed somehow in v6
