### ISSUE TITLE
Snipe it Broke after mariadb docker update, now pre-flight page shows up with a database error

### ISSUE THREAD

**Issue by djshoxxx** [grokability/snipe-it#9817]
SnipeIT was working fine until I updated mariaDB docker, now only the preflight page shows up.

-----

#### _Please confirm you have done the following before posting your bug report:_

- [ x] _I have enabled debug mode_ - yes
- [ x] _I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)_ -yes

-----
#### Provide answers to these questions:

_- Is this a fresh install or an upgrade?_  after fresh install, was working great,

_- Version of Snipe-IT you're running_ - latest

_- Version of PHP you're running_  PHP version 7.2.24-0ubuntu0.18.04.7

_- Version of MySQL/MariaDB you're running_ Linuxserver.io version:- 110.4.20mariabionic-ls26 Build-date:- 2021-07-10T05:58:25+00:00

_- What OS and web server you're running Snipe-IT on_ - unRAID Version: 6.9.2  with docker  version 20.10.5

_- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)_ docker

_- Include what you've done so far in the installation, and if you got any error messages along the way._ 
 

 Snipe-It was working great as our asset management system. At some point we noticed the dockers had updates. 

We updated all of our dockers and there were no issues with any of them, except with Snipe-IT.  SnpeIT no longer runs, and now the Snipe-IT Pre-Flight page comes up. The only error in the pre-flight page is with the database.

 It says: "D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: SQLSTATE[HY000] [1045] Access denied for user 'mainuser'@'172.17.0.1' (using password: YES) (SQL: select 2 + 2)"

I suspect that this was due to updating mariadb. It might have to do with permissions? I really dont know. Any suggestions on how to fix this?

- _Indicate whether or not you've manually edited any data directly in the database_ - no

_Other info:_

this is what the logs say when i execute the followng docker command for mariadb:
```

# docker container logs mariadb
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing... 
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 90-warning: executing... 

******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image will soon be rebased           *
*               from ubuntu to alpine.               *
*       Please be aware, this may cause issues       *
*     It is strongly recommended to make backups     *
*         of your config and databases before        *
*       updating your image to the alpine base.      *
*                                                    *
*                                                    *
******************************************************
******************************************************
[cont-init.d] 90-warning: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
210712 09:25:52 mysqld_safe Logging to syslog.
210712 09:25:52 mysqld_safe Starting mysqld daemon with databases from /config/databases

```
any suggestions?

**Comment by uberbrady** [comment]
I know there was something where MariaDB changed how they handle authentication, using a new mechanism that isn't always supported in all environments. Check out https://mariadb.com/kb/en/authentication-from-mariadb-104/ and please let us know if you find something that works in there. It seems like they're saying the 'root' account no longer exists? I also know there was some kind of thing where auth plugins were different between certain versions of mysql and certain versions of mariadb, but I don't know the details.

Please let us know what you find out so that if other users run into this, we'll know what to tell them.

<blockquote><img src="http://mariadb.comaskmonty-logo.png" width="48" align="right"><div><img src="/kb/static/images/favicons/favicon-16x16.5801f8f0f34e.png" height="14"> MariaDB KnowledgeBase</div><div><strong><a href="https://mariadb.com/kb/en/authentication-from-mariadb-104/">Authentication from MariaDB 10.4</a></strong></div><div>Authentication changes in MariaDB 10.4.</div></blockquote>

**Comment by yosiasz** [comment]
>mainuser'@'172.17.0.1
which server is 172.17.0.1? do you have a separate docker for the db or all in one basket?

**Comment by djshoxxx** [comment]
Hey, so I fixed it.

It was a pretty simple fix actually.

Some how, after updating, the .env file got overwritten with the default .env file.

Luckally I backed up the working .env file and replaced it with the non-working default .env file, restarted both the snipe-it and the mariadb dockers and it started working again!

Am I the only one whos had this issue with updating the docker where snipe-it stops working? I thought for the longest while that it was mariadb because in the pre-flight page it said that there was a problem with the database in the .env file and I couldnt see that doing an update to snipe-it should change the .env file at all, until I actually CHECKED the .env file and seen that it was all the default settings.


Thank both of you for helping. 

yosiasz: that IP is the internal docker IP. If i remember correctly is bridged something like this:

snipeIT:
172.17.0.5:80 <--> TCPx.x.x.x:81
/var/lib/snipeit/  <--> mnt/user/appdata/snipeit/data


while the mariadb is bridged something like this:
172.17.0.1:9999 <-->TCPx.x.x.x:9999
/config<--> /mnt/user/appdata/mariadb

(they are separate dockers)

**Comment by djshoxxx** [comment]
Ok, so me and my co-worker did a test today. We noticed that the docker had another update. Now that we figured we could fix it if an update stopped it from working again, that we would go ahead and try applying the snipe-it update. mariadb did not have an update.

after applying the update snipeit broke again with the same error. The exact same thing happened, the env file re-set to the original defaults, and snipeit reverts to the pre-launch page with the same database error.

Is this a docker issue or the way the docker was created maybe? I dont know enough about docker to know but given that there arnt issues with updates when installed on an ubuntu server that I figure it has to do something with the docker, and we can definitely rule out it being an update of mariadb thats causing the issue.

Im surprised that I havent found others who use the docker who are having the same issue when updating.

**Comment by yosiasz** [comment]
from documentation:

Your my_env_file is not the same .env file Snipe-IT uses directly, but the values you put in it are used to generate the .env file that Snipe-IT does use, so what you put in here matters.

Do you have a my_env_file file?

**Comment by djshoxxx** [comment]
yosiasz: i have not seen a my_env_file anywhere. Where is it supposed to be located? And could this have to do with the .env file being reset every time the docker updates?

**Comment by yosiasz** [comment]
yes that is probably exactly why it is being reset ever docker update. Read up on the documentation. https://snipe-it.readme.io/docs/docker


Your my_env_file is not the same .env file Snipe-IT uses directly, but the values you put in it are used to generate the .env file that Snipe-IT does use, so what you put in here matters.


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/docker">Docker</a></strong></div><div>Note very loudly that additional Docker options should be set in the env file, and they require a restart!</div></blockquote>

**Comment by snipe** [comment]
@yosiasz you should know you just beat @uberbrady on that reply  and now he's kinda sad :D (Not too sad tho)

You're awesome. <3 <3 
![BondJumpIntoRippedTrain](https://user-images.githubusercontent.com/197404/127071187-0cc0be0c-9473-4dd9-b445-9bc6ed5446e9.gif)

**Comment by yosiasz** [comment]
@uberbrady i owe you a bavarian kreme donut

**Comment by djshoxxx** [comment]
you guys are awesome! Thank you for clearing this up for me!

**Comment by snipe** [comment]
<3
