### ISSUE TITLE
Not able to see assigned user assets details after login.

### ISSUE THREAD

**Issue by jubin006** [grokability/snipe-it#9820]
Hi sir/madam,
![Snipe Error](https://user-images.githubusercontent.com/86301484/125450485-7f282040-f75f-4ba4-95d1-3ec303ef06fb.png)

I am using open-source snipe-it software and I want to do when users log in from the credentials they able to see what assets assigned to them but I am not getting any idea how to do that.

Please find the attachment.

**Comment by godnroc** [comment]
I believe users have the ability to view what is checked out to them by default. You can also create groups with further permissions and then assign users to those groups.

Attached are some screenshots of my test user, Testy Tester, and the Test Asset I assigned to them. They didn't require any group permissions to login and view this, but they also cannot see anything else within Snipe-IT. There is also a screenshot of the area you can find the groups settings.

![Screenshot 2021-07-13 105543](https://user-images.githubusercontent.com/2201722/125485172-29eb16ab-fbc0-4ad4-93aa-56770e7f74fe.png)
![Screenshot 2021-07-13 105657](https://user-images.githubusercontent.com/2201722/125485189-5a8eb241-50af-45b3-8d1a-e21db52f5d75.png)
![Screenshot 2021-07-13 105505](https://user-images.githubusercontent.com/2201722/125485800-e76ee42f-be60-4984-9f08-31b1fead517f.png)

**Comment by snipe** [comment]
I can confirm that this is a permissions issue. Please see the documentation on how users work in Snipe-IT. https://snipe-it.readme.io/docs/permissions

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/permissions">Permissions</a></strong></div><div>Snipe-IT provides two privileged user account tiers, Admin and Superadmin, and a wide variety of more granular permissions for non-admin/non-superadmin users.All other permissions, for example, the ability to add or view users, the ability to create, edit, or delete assets, and so on, are assumed at...</div></blockquote>
