### ISSUE TITLE
SAML won't work

### ISSUE THREAD

**Issue by asafmazor17** [grokability/snipe-it#9826]
#### Expected Behavior (or desired behavior if a feature request)

_I've configured SAML correctly through G-Suite and snipe-it settings panel.
However my question is simply :
I'm not using it with LDAP and I bought the monthly hosted package from snipe-it._

**We wanted SAML to "pull" data from our users in G-Suite into the snipe-it app but it seems like it's not the case.** 

-----

#### Actual Behavior

**After clicking on SAML login on the login page on snipe-it , it just refreshes the page and shows the message:
"There was a problem while trying to log you in, please try again."**

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode **Yes**
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) **yes**

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **fresh install**
- Version of Snipe-IT you're running **v5.1.8**
- Version of PHP you're running **7.3.23**
- Version of MySQL/MariaDB you're running **hosted snipe-it monthly plan**
- What OS and web server you're running Snipe-IT on  **chrome , windows 10 pro**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **hosted snipe-it monthly plan**
- Any errors that appear in your browser's error console. **no**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  **not the case**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **included up there**
- Include what you've done so far in the installation, and if you got any error messages along the way. **included up there**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
The current implementation doesn’t pull in data via SAML, it’s just used for authentication. Most people use LDAP to sync users, and LDAP or SAML for login

**Comment by asafmazor17** [comment]
> The current implementation doesn’t pull in data via SAML, it’s just used for authentication. Most people use LDAP to sync users, and LDAP or SAML for login

So, if I can use LDAP to retrive info and to authenticate, what is the usage of SAML?
My LDAP is hosted on a private network layer accessible through VPN, so I won't be able to use it on a cloud hosted site..

**Comment by PetriAsi** [comment]
I'm using SAML and syncing user information to snipe with SnipeitPS (powershell) . 
Only subset of our users have accounts enabled on snipe it ,  but this way we get **real SSO** and all user info is in snipe it. I prefer always SAML over ldap login as passwords are entered only to SAML identity provider when/if needed.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
