### ISSUE TITLE
Upgrade fails on error about missing gd or imagick php extension, but extension is installed

### ISSUE THREAD

**Issue by phatuous** [grokability/snipe-it#9828]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to perform an upgrade from v5.1.5 to v5.1.8 using upgrade.php, I receive an error about a missing PHP extension... but not only has the extension (imagick) been installed, but it's listed by upgrade.php as installed.

**To Reproduce**
In my case, running php upgrade.php.

**Expected behavior**
Update to run successfully.

**Screenshots**
--------------------------------------------------------
STEP 1: Checking PHP requirements: 
--------------------------------------------------------

Current PHP version: (7.4.16) is at least 7.2.5 - continuing... 
FYI: The php.ini used by this PHP is: /etc/php/7.4/cli/php.ini

Checking Required PHP extensions... 

--------------------------------------------------------
You have the following extensions installed: 
--------------------------------------------------------
- Core
- date
- libxml
- openssl
- pcre
- zlib
- filter
- hash
- pcntl
- Reflection
- SPL
- session
- standard
- sodium
- mysqlnd
- PDO
- xml
- bcmath
- calendar
- ctype
- curl
- dom
- mbstring
- FFI
- fileinfo
- ftp
- gettext
- iconv
- imagick
- json
- ldap
- exif
- mysqli
- pdo_mysql
- Phar
- posix
- readline
- shmop
- SimpleXML
- sockets
- sysvmsg
- sysvsem
- sysvshm
- tokenizer
- xmlreader
- xmlwriter
- xsl
- zip
- Zend OPcache
--------------------- !! ERROR !! ----------------------
✘ MISSING PHP EXTENSION: gd OR imagick
------------------------- :( ---------------------------
ABORTING THE INSTALLER  
Please install the extensions above and re-run this script.
------------------------- :( ---------------------------

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: Ubuntu 20
 - Web Server: Apache
 - PHP Version: 7.4

**Additional context**
- Is this a fresh install or an upgrade? 
upgrade
- What OS and web server you're running Snipe-IT on
Ubuntu/Apache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual (using git)

- Include what you've done so far in the installation, and if you got any error messages along the way.

app is up and running fine. just trying to upgrade.

- Indicate whether or not you've manually edited any data directly in the database

Nope.

**Comment by phatuous** [comment]
I wish I could pin down the resolution more concretely, but essentially I think the issue came down to having upgraded the server from Ubuntu 18.04 to 20.04 (a while ago), and the php extensions didn't want to upgrade properly to the Ubuntu 20 versions. I ended up uninstalling and reinstalling all the php extensions, and that seems to have resolved the issue - afterwards, upgrade.php ran through clean.

**Comment by swiqs** [comment]
Thank you for following up with a resolution, or at least what you did to fix it. I am experiencing this right now.

**Comment by tsatrom** [comment]
> Thank you for following up with a resolution, or at least what you did to fix it. I am experiencing this right now.

Did you ever figure this out?  I am having this issue and I did not upgrade from 18.04 - 20.04.  I'm still on 18.04 and recently upgraded to PHP 7.4 but can't upgrade snipe now.  Any ideas?
