### ISSUE TITLE
Import route (/import) displays blank page 

### ISSUE THREAD

**Issue by baughj** [grokability/snipe-it#9832]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
As a super user, I go to the import page (eg https://mysnipeitinstance.biz/import) and I receive a blank page that just says "Import".

**To Reproduce**
1. Go to /import or click the cloud download logo on the left hand side.

**Expected behavior**
Import page should display.

**Screenshots**
![image](https://user-images.githubusercontent.com/194969/125831785-d2eb3377-e589-4d25-9fc7-d9a253717a50.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 5.1.7
 - OS: Amazon ECS (Container image was built via `Dockerfile` in repo - Ubuntu 18.04)
 - Web Server: Apache
 - PHP Version: 7.2

**Desktop (please complete the following information):**
 - OS: OSX 10.15.7
 - Browser: Multiple (Edge, Chrome, Safari)
 - Version: Most current versions of each

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

No browser error in console, but what I presume is the Laravel debugbar shows a few errors. Sorry for the screenshot, it isn't obvious to me how to cut and paste the logs out of it - if I try to cut and paste the expanded contents, I get bupkis when I paste it elsewhere:

![image](https://user-images.githubusercontent.com/194969/125833034-04484f67-ca25-4a90-a24e-6098e4c87803.png)

- If a stacktrace is provided in the error, include that too. _n/a_
- Any errors that appear in your browser's error console. _None_
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. _No, a view displays for import there. Admittedly you can't do anything there but I presume it is to avoid internet randos uploading junk_
- Include any additional information you can find in `storage/logs` and your webserver's logs. 

Since this is ECS logs are sent to Cloudwatch Logs and then onto DataDog. All I see there is a whole bunch of

`No scheduled commands are ready to run.`

- Include the output from `php -m` (this should display what modules you have enabled.) _See below_

```
root@8d23596f27ee:/var/www/html# php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Additional context**
- Is this a fresh install or an upgrade? _New installation_
- What OS and web server you're running Snipe-IT on _Within Amazon ECS behind ALB_
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) _docker build to account local ECR_
- Include what you've done so far in the installation, and if you got any error messages along the way. _TBH: Everything else seems to be working fine_
- Indicate whether or not you've manually edited any data directly in the database _No, I am not a feral animal._ 😄 

Forgot to mention if it matters, this instance has SAML enabled and is using Okta for SSO (and is working, no issues there).

**Comment by godnroc** [comment]
That was a bug in 5.1.7, upgrading to 5.1.8 should fix the issue.

[https://snipe-it.readme.io/docs/upgrading](https://snipe-it.readme.io/docs/upgrading)

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/upgrading">Upgrading</a></strong></div><div> Always backup your database and configuration files before upgrading. We try very hard to make sure that all database changes are non-destructive, but you should always backup beforehand anyway. You will never regret backing up your database. You may regret not doing so, so it’s just better to get ...</div></blockquote>

**Comment by baughj** [comment]
...That is the first thing I should have checked, sorry. I'll do the upgrade and if necessary reopen the issue. Thanks!
