### ISSUE TITLE
LDAP and login issue

### ISSUE THREAD

**Issue by RB-OP** [grokability/snipe-it#9836]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If I import user from LDAP (import works fine no errors) and try to log on with one of the user it's saying username or password inccorrect. When I then request a new password no e-mail is being send.
If I add a user manually through Snipe-IT and try to log on I'm able to do so. If I request a new password with the  added user I receive the e-mail to change the password and everything is working correctly. I also tried to check and uncheck "LDAP Password Sync" as well as "Append domain name" both was not successful.

**To Reproduce**
![LDAP](https://user-images.githubusercontent.com/87636388/126120213-3a9f4990-c71b-4fe4-8df6-d4b71d1225a8.png)

![LDAP2](https://user-images.githubusercontent.com/87636388/126117068-cff4b147-7235-4404-9990-6b90b8d0fdb4.png)

**Expected behavior**
I would expect if the import of all user is successful that I'm able to log on with their current credentials and if not they would at least receive an e-mail and not only if I add the user manually.

**Screenshots**
Attached.

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.8 - build 6148 (master)
 - OS: Ubuntu 20.04.
 - Web Server: Apache/MYSQL
 - PHP Version: 7.4

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 80.0.3987.122

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
no errors are displayed in my browser
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
It's disabled on the demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
no logs under storage/logs
- Include the output from `php -m` (this should display what modules you have enabled.)
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade? 
Yes the installation was a fresh installation.

- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git, manual installation
- Include what you've done so far in the installation, and if you got any error messages along the way.
It 
- Indicate whether or not you've manually edited any data directly in the database
I have not edited any data directly in the db.

**Comment by uberbrady** [comment]
For LDAP users, yes, we don't send password reset emails; that's built-in to how the system works.

For most sAMAccountName configurations, you will need to have "append domain name" enabled, but users will need to log in with their 'short names' - eg. "accountname" rather than "accountname@domain"

If you need them to log in with "long names" - you might want to use userPrincipalName as your "username" field but that is going to duplicate all your current users. (You would also want to un-check "append domain name").

Make sure when you test to first save your changes, then come back to test them.

**Comment by RB-OP** [comment]
Hi,
unfortunately, I tried each setting and saved them accordingly but user can still not log on. As I said if I create a user in Snipe-IT all is fine and all functionallity is working. For the e-mails is it only for password resets or all e-mails being send through snipe-IT?
Any other suggestions?
Thank you.

**Comment by uberbrady** [comment]
We have a *lot* of users who use LDAP to synchronize user lists, but then use SAML to be able to log in? If you're using an idenity provider that uses SAML, you might find that that works out really well for your people, once you get it set up.

But, that being said - you really ought to be able to log in directly using LDAP. Plenty of folks do. Maybe set your debug level higher and check the logs? `APP_LOG_LEVEL=debug`

**Comment by snipe** [comment]
It should be `LOG_LEVEL=debug`. What we have in the `example.env` isn't actually what the `config/logging.php` file is looking at. 

Sigh.

**Comment by RB-OP** [comment]
Thanks for your support!
I have the following error messages... However I can't resolve the permission ones...
1. production.ERROR: There are no commands defined in the "dugbar" namespace.
2. production.ERROR: Symfony\Component\Console\Exception\NamespaceNotFoundException: There are no commands defined in the "dugbar" namespace.
3. production.ERROR: file_put_contents(/var/www/html/bootstrap/cache/config.php): failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/bootstrap/cache/config.php): failed to open stream: Permission denied at /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133)
4. production.ERROR: ErrorException: file_put_contents(/var/www/html/bootstrap/cache/config.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133

**Comment by uberbrady** [comment]
That feels a lot like you’ve got a couplea problems - 

#1 - I think you need to run a `composer install`
#2 - I think you might have some wonky perms on your bootstrap and bootstrap/cache directories.

See what you can do about that and let us know if it helps!

**Comment by RB-OP** [comment]
Hi,

I reinstalled snipe-it. No errors. Then I was running the one-liner: `composer dump-autoload; php artisan cache:clear; php artisan config:clear; php artisan route:clear; php artisan dugbar:clear; php artisan event:clear; php artisan view:clear; php artisan optimize:clear; php artisan clear-compiled`

Now I have the two erros again:
1. production.ERROR: There are no commands defined in the "dugbar" namespace.
2. production.ERROR: Symfony\Component\Console\Exception\NamespaceNotFoundException: There are no commands defined in the "dugbar" namespace.

I run `composer install` but it did not fix the error. 
I'll have a look if I set up LDAP again if people can login or not.

**Comment by snipe** [comment]
The “dugbar” errors you’re seeing are a result of a typo in the docs. (Should be “debugbar” but autocorrect can be a bear.)

**Comment by RB-OP** [comment]
So I reinstalled Snipe-IT and set it up all from scratch again. what I found out is that the password and phone number are not being synchronised. It's fine at the moment. Are there any major changes for LDAP in version 6?

**Comment by snipe** [comment]
Password would only be synced if you have that setting enabled in your LDAP settings. Phone number was added several versions ago. :)
