### ISSUE TITLE
Can't install on Centos 8

### ISSUE THREAD

**Issue by edugimeno** [grokability/snipe-it#9844]
Hi There!
Im trying to install Snipe-it thru installer on Centos 8 and I get 

Unsupported CentOS version. Version found: 8

Should I modify the script to skip this check or it's not advised to install it on this version?

Thanks

**Comment by snipe** [comment]
I don't know of any reason why Snipe-IT couldn't be installed on CentOS 8

**Comment by uberbrady** [comment]
I would prefer it if you could submit a pull request (toward the develop branch, please) that permits the install to run on CentOS 8 if it actually does work on CentOS 8 - but regardless, if disabling that check makes it work, then by all means do go ahead and skip that. There's nothing special about the version(s) we choose there. PHP is still PHP and MySQL is still MySQL - web servers still serve web, so you should be OK.

**Comment by edugimeno** [comment]
I guess the "version check" section of the script has some flaws. I ended up installing it all manually step by step and it worked, so at this time I can't tell whether the script would have worked if I modified it to force the installation, this is a client server so I can't mess much with another install now.
I just wanted to leave it here so maybe the owner would want to give the script a look to make sure it works on all OS's

Thanks

**Comment by edugimeno** [comment]
> I would prefer it if you could submit a pull request (toward the develop branch, please) that permits the install to run on CentOS 8 if it actually does work on CentOS 8 - but regardless, if disabling that check makes it work, then by all means do go ahead and skip that. There's nothing special about the version(s) we choose there. PHP is still PHP and MySQL is still MySQL - web servers still serve web, so you should be OK.

Yes I agree, but also in the manual install on CentOs 8 I had issues with the pre-existence of mysql-server when it tried to install mariadb-server and took me a while to force it, so maybe this should be reviewed too.

I will submit a pull request. Thanks

**Comment by uberbrady** [comment]
Thanks! We’d really appreciate it :) You can certainly mention this issue ID in the PR.
