### ISSUE TITLE
Is 5.1.8 supported on PHP 8.0.0 ?

### ISSUE THREAD

**Issue by wq949966** [grokability/snipe-it#9872]
#### Please confirm you have done the following before posting your bug report:

- [ Y] I have enabled debug mode 
- [ Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**Unable to use APIs or create API Keys.**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by nicholasmercurio** [comment]
According to https://snipe-it.readme.io/docs/requirements any PHP >= 7.2.5 is supported. However, in my testing I had issues running the latest version of PHP so I rolled back to 7.4

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/requirements">Requirements</a></strong></div><div>The requirements for Snipe-IT are fairly standard for a modern web server, and most servers will have most or all of these components already installed. If for some reason you don't have them installed, they are relatively easy to add.      </div></blockquote>

**Comment by wq949966** [comment]
Thank you for confirming @nicholasmercurio . I too had the same. All worked perfectly on 7.4. But upgrade to 8 resulted in two things (which I noticed, but could be more as we did not use the system) -
1. APIs stopped working (internal server error 600)
2. imagik/ gd library not found (although it was in the ini file)

**Comment by back-2-95** [comment]
I also had problem with PHP 8 on creating backups. ZipArchive was not found but could also be related to PHP 8 on old Ubuntu 16.

**Comment by snipe** [comment]
Snipe-IT v6 will support PHP8, but currently we do not. Not by our choice, but some libraries we use in Snipe-IT v5 don’t handle it well
