### ISSUE TITLE
Sending Test E-Mail [Mail could not be sent.]

### ISSUE THREAD

**Issue by DanielBergfreund** [grokability/snipe-it#9874]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Sending a test mail does not work. There are not error messages provided.
```
Mail could not be sent.
No additional error message provided. Check your mail settings and your app log.
```

**To Reproduce**
1. Go to 'Admin -> General Settings'
2. Click on 'Send Test'

**Screenshots**
![image](https://user-images.githubusercontent.com/88091312/127319560-8861a64f-9f48-4214-887e-18ef1a8edadf.png)

**Server (please complete the following information):**
 - Snipe-IT Version **v5.1.8**
 - OS: [e.g. Ubuntu, CentOS] **Ubuntu 20.04**
 - Web Server: [e.g. Apache, IIS] **Apache 2**
 - PHP Version **7.4**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 10**
 - Browser [e.g. chrome, safari] **Google Chrome**

**Additional context**
- Is this a fresh install or an upgrade? **Installed it on Version v5.1.5**
- What OS and web server you're running Snipe-IT on **Ubuntu 20.04 / Apache 2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**

My .env config for mail is
```
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.bergfreunde.de
MAIL_PORT=587
MAIL_USERNAME=status.snipeit@bergfreunde.de
MAIL_PASSWORD=******
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=status.snipeit@bergfreunde.de
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=daniel.deuscher@bergfreunde.de
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_BACKUP_NOTIFICATION_ADDRESS=daniel.deuscher@bergfreunde.de
MAIL_AUTO_EMBED=true
MAIL_AUTO_EMBED_METHOD=base64
```

The laravel log file `/storage/logs/laravel.log` is **empty**!! That is why I don't know where to begin. However, logging does work. I've tried it with changing the `MAIL_DRIVER` to something that is not supported and that will be logged.

Is this maybe a server issue? Do I need additional packages/software on Ubuntu so that will work?

**Comment by RB-OP** [comment]
Have your tried a different port number?

**Comment by DanielBergfreund** [comment]
I have tried different ports `25, 587, 465`with different encryption methods. Sometimes the above error message report is instant and someimtes it takes a few seconds.

Thanks for your reply!

**Comment by tom-sin** [comment]
Hallo,

hast du ein PHP Upgrade gemacht? 
Hat die Konfiguration schon mal funktioniert?

Ich hatte auch ein Problem mit dem Mailversand nach dem PHP Upgrade jedoch nutzen wir Windows+IIS.
Falls du im laravel.log eine Fehlermeldung findest die "could not find driver" beinhaltet, deutet es daraufhin das du eine fehlerhafte php.ini hast.

**Comment by dmitrygribenchuk** [comment]
Hello. Have the same issue. snipe-it 6.1.0 (Helm). I try to enable debug and change the environment to development - no additional information appears.

**Comment by marcusmoore** [comment]
@dmitrygribenchuk does anything appear in your log file? (`storage/logs/laravel.log`)

**Comment by dmitrygribenchuk** [comment]
@marcusmoore no, log dir is empty.

**Comment by dmitrygribenchuk** [comment]
I found a solution for my case. Argocd converted one parameter:
      - name: config.snipeit.envConfig.MAIL_ENCRYPTION
        value: 'null'

to: nil and it doesn't work. May be info message can be more informative

I use forceString to fix it.

**Comment by marcusmoore** [comment]
😄 glad to hear you got it working again 👍🏾

**Comment by marcusmoore** [comment]
I just realized I closed this without addressing the original opener.

@DanielBergfreund ping me and I'll re-open this if you still need help.
