### ISSUE TITLE
Do not work favicon, logo in docker version snipe-it

### ISSUE THREAD

**Issue by Peter-Idea** [grokability/snipe-it#9878]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode (How to make it into Docker container)? 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to website
3. See error don't load logo, favicon

**Expected behavior**
When opening the site, the favicon and logo are not loaded. Links to images of the form http://127.0.0.1:7080/uploads/setting-logo-iIG0aQaKAp.png

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version Dcoker image: snipe/snipe-it:v5.1.8

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser Firefox, Chrome, Eddge

**Error Messages**
To download the favicon and logo, the site makes a get request to the local host:
GET http://127.0.0.1:7080/uploads/setting-logo-iIG0aQaKAp.png

![Snipet_12](https://user-images.githubusercontent.com/55666554/127502038-bc47b69f-2637-483e-8737-4879aa3aa004.png)

**Comment by MrDiba** [comment]
Could you verify what your `APP_URL` settings are in the `.env.docker` by default these point to `localhost` but should reflect your URL that you are using. (in your case `10.5.20.110`)

**Comment by Peter-Idea** [comment]
Thank you for helping!

**Comment by MrDiba** [comment]
No problem! If this fixed you problem, would you please close this issue? Thank you!
