### ISSUE TITLE
Added a multiple selection checkbox field

### ISSUE THREAD

**Issue by RippieUK** [grokability/snipe-it#9887]
**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.8 - build 6227
 - OS: Debian 10.10
 - Web Server: Apache
 - PHP Version: 7.3

**Is your feature request related to a problem? Please describe.**
I wanted to add a field named 'Management access protocols' with a multiple selection on how to connect to a device

- http
- https
- telnet
- ssh
- snmp

**Describe the solution you'd like**
Add a multiple selection checkbox field

**Describe alternatives you've considered**
A text box witha comma separated line or the management protocols

**Comment by snipe** [comment]
We have a multi-select list box to handle this. 

We’ve already litigated checkbox fields, as @uberbrady can attest to.

**Comment by RippieUK** [comment]
Sorry my bad, completely overlooked the 'Checkbox' option!!
