### ISSUE TITLE
Accepting licence seat failed on insufficient permissions in multi-company mode

### ISSUE THREAD

**Issue by kopa11** [grokability/snipe-it#9900]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
In case there is a multi-company mode turned on, users are not able to accept any license seat that was assigned to them, even the license is assigned to the same company as the user is.

**To Reproduce**
1. Turn on multi-company mode.
2. Assign a license to the user.
3. Click on "✔ I have read and agree to the terms of use, and have received this item." in License delivery confirmation delivered by mail.
4. Log in and try to accept the assigned license seat.
4. Insufficient permissions error will be shown and the license stays unaccepted.

**Expected behavior**
The license should be accepted the same way as the asset can be accepted.

**Screenshots**
<img width="411" alt="Screen Shot 2021-08-03 at 14 15 42" src="https://user-images.githubusercontent.com/9881513/128154405-7da846ea-c7cf-4204-b859-b962ad486aff.png">

**Server (please complete the following information):**
 - Snipe-IT v5.1.5 
 - OS: Ubuntu 20.04
 - Web Server: Apache 2.4.41
 - PHP Version: 7.4.16

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 14.1.2

**Smartphone (please complete the following information):**

**Error Messages**
- no other error WITH DEBUG TURNED ON
- no stack trace is provided in the error
- no errors appear in the browser's error console
- error is not reproducible on the demo because in the demo is sending mails disabled
- no additional in `storage/logs`
- the output from `php -m`:

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- upgrade of v4
- installed via install.sh
- no data were directly edited in the database

The problem seems to be in app/Models/Company.php, during the license seat acceptance process the function isCurrentUserHasAccess is called and in case isFullMultipleCompanySupportEnabled is true, it falls to else block where $companyable->company_id is always null because it does not exists for license seat.  In case the asset is accepted, the company_id returns the right id and everything is working as expected.

```
if (Auth::user()) {
                $current_user_company_id = Auth::user()->company_id;
                $companyable_company_id = **$companyable->company_id**;
                return ($current_user_company_id == null || $current_user_company_id == $companyable_company_id || Auth::user()->isSuperUser());
}
```

**Comment by Toreg87** [comment]
I think the underlying problem is the same as #9875 and PR #9876 should also fix this.
