### ISSUE TITLE
Advanced search with serial and another field produces wrong results

### ISSUE THREAD

**Issue by Toreg87** [grokability/snipe-it#9904]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If I use the advanced search in /hardware to filter for serial and another field like category the result is incorrect because the query searches for the serial OR the category. 
If I search for e.g. asset_tag and category the result is correct because the query searches for asset_tag AND category.

**To Reproduce**
1. Go to '/hardware'
2. Use advanced search to search for serial and another field
3. See the incorrect search result and the OR-query in the debugbar

**Expected behavior**
The serial and the other field should be combined with AND, not OR.

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.8
 - OS: [e.g. Ubuntu, CentOS] ubuntu
 - Web Server: [e.g. Apache, IIS] apache
 - PHP Version 7.3

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? upgrade
- What OS and web server you're running Snipe-IT on debian
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by IanSimon82** [comment]
This continues to be an issues with all of the search fields, it seems to do an OR search instead of an AND search. 

Edit: Some fields work and some do not. The custom fields are the biggest culprit.

**Comment by Toreg87** [comment]
@IanSimon82 my fix was only merged to the development branch and will be in the upcoming V6 release.
I applied this fix locally to V5.3 and it works without problems.

@snipe do you think this is worth fixing in master?
