### ISSUE TITLE
CLI Command "artisan snipeit:upcoming-audits" throws exception

### ISSUE THREAD

**Issue by mf-lxc** [grokability/snipe-it#9907]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When running ´php artisan snipeit:upcoming-audits´ I receive an exception

**To Reproduce**
Run the command ´php artisan snipeit:upcoming-audits´

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.8 - build 6227 (master)
 - OS: [e.g. Ubuntu, CentOS]  Ubuntu 20.04.2 LTS
 - Web Server: [e.g. Apache, IIS] apache
 - PHP Version PHP 7.4.3 
 - 
**Error Messages**
´´´   Illuminate\View\ViewException  : Could not parse '31/07/2021': DateTime::__construct(): Failed to parse time string (31/07/2021) at position 0 (3): Unexpected character (View: /var/www/snipe-it/resources/views/notifications/markdown/upcoming-audits.blade.php)

  at /var/www/snipe-it/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:189
    185|         } catch (Exception $exception) {
    186|             $date = @static::now($tz)->change($time);
    187|
    188|             if (!$date) {
  > 189|                 throw new InvalidFormatException("Could not parse '$time': ".$exception->getMessage(), 0, $exception);
    190|             }
    191|
    192|             return $date;
    193|         }

  Exception trace:

  1   Illuminate\View\Engines\CompilerEngine::handleViewException()
      /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:45

  2   Carbon\Exceptions\InvalidFormatException::("Could not parse '31/07/2021': DateTime::__construct(): Failed to parse time string (31/07/2021) at position 0 (3): Unexpected character")
      /var/www/snipe-it/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:189
´´´

**Comment by stephenregisterTJT** [comment]
You can close this issue.

I found that the underlying cause was due to an incompatible MariaDB version.
Not incompatible with Snipe, but incompatible with my OS due to a poorly managed dependency I had let get away.

Warning to myself and others: If you use the LTS edition of Ubuntu server, you need to be sure to follow proper upgrade paths for your dependencies. The latest edition of all tools are not typically available for LTS as soon as they're on main.

**Comment by bunglesss** [comment]
I am getting this on CentOS 7. What did you do to fix it?

**Comment by bunglesss** [comment]
I have tried setting time zone for mariadb and PHP having searched all over the shop for an answer.

This used to work, so some upgrade broke it, but not sure which. Have updated to PHP 7.4, latest Snipe and MariaDB 10.1.48.

**Comment by stephenregisterTJT** [comment]
> I am getting this on CentOS 7. What did you do to fix it?

I doubt my exact fix would apply to you but there may be a similarity.
My issue was that I am using a specific version of Ubuntu operating system and I ran dependency updates for a different version for the OS which then led to this issue.
From there I did not "fix" it per say. I benefitted from my environment where I'm using virtual machines and had snapshots and backups to restore from. I simply found a time before I ran the erroneous updates and reverted to it. Then I ran the correct version of updates for my OS.

The only thing you may be able to take from this is that you should check the dependencies for your specific version of CentOS. Make sure you have the right ones and if not then fixing them may help.

**Comment by bunglesss** [comment]
Thanks for that mate, I will go over it again with more time and see if it gives any clues.

Funny thing is, overdue warranty emails work fine, which must be doing similar date comparison? Are we sure there's no bug in Snipe here?

**Comment by bunglesss** [comment]
See here if anyone else gets this ... https://github.com/snipe/snipe-it/issues/10647
