### ISSUE TITLE
Notifications for Expiring Licenses

### ISSUE THREAD

**Issue by aarnold-sd68** [grokability/snipe-it#9908]
**Server (please complete the following information):**
 - Snipe-IT Version 5.1.8
 - OS: Windows
 - Web Server: IIS
 - PHP Version  7.4

**Is your feature request related to a problem? Please describe.**

As it stands now with out using external means licenses that are expiring do not have a notification.

**Describe the solution you'd like**

Have the ability to say I'd like to be notified when a license is going to expire in the next 30 days. Could be just a check box on a license, as not all licenses need notifications.

**Describe alternatives you've considered**

Writing my own program to pull from the rest api via powershell.  But as notifications are already built in for other assets why not licenses as well?

**Comment by snipe** [comment]
`$schedule->command('snipeit:expiring-alerts')->daily();` includes expiring licenses. 

https://github.com/snipe/snipe-it/blob/d70e4e04c053feea0d2b179ca0bee52533907315/app/Console/Commands/SendExpirationAlerts.php#L61-L65
