### ISSUE TITLE
Permissions issue in search/non super users cannot search (returns no results)

### ISSUE THREAD

**Issue by RaumfahrerSpiffy** [grokability/snipe-it#9917]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading to v5.1.8 any user that is not a super user is unable to use the search function, it returns no results. Super users are unaffected. 

**To Reproduce**
1. Go to 'list all assets' as non super user
2. Enter search query
3. No results

**Expected behavior**
The search would populate results (asset does exist)

**Screenshots**
Screenshots attached show "list all" view with the asset present and after the search term is entered with no results.

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: Windows Server 2016
 - Web Server: IIS
 - PHP Version : 7.2.7

**Desktop (please complete the following information):**
 - OS: Mac OS and Windows 10
 - Browser: Safari, Chrome, Firefox
 - Version: current versions of all browsers tested

**Error Messages**
- If a stacktrace is provided in the error, include that too.

I have a handful of error like this one, all stating 'company_id'

`SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'company_id' in where clause is ambiguous (SQL: select count(*) as aggregate from `assets` inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` and `status_alias`.`archived` = 0 left join `users` as `assets_users` on `assets_users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\User left join `locations` as `assets_locations` on `assets_locations`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\Location left join `assets` as `assigned_assets` on `assigned_assets`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\Asset where `assets`.`company_id` = 4 and (`assets`.`name` LIKE %FS9RXZ1% or `assets`.`asset_tag` LIKE %FS9RXZ1% or `assets`.`serial` LIKE %FS9RXZ1% or `assets`.`order_number` LIKE %FS9RXZ1% or `assets`.`purchase_cost` LIKE %FS9RXZ1% or `assets`.`notes` LIKE %FS9RXZ1% or `assets`.`_snipeit_mac_address_4` LIKE %FS9RXZ1% or `assets`.`_snipeit_ip_address_5` LIKE %FS9RXZ1% or `assets`.`_snipeit_dns_name_6` LIKE %FS9RXZ1% or `assets`.`_snipeit_active_directory_location_7` LIKE %FS9RXZ1% or `assets`.`_snipeit_active_directory_description_8` LIKE %FS9RXZ1% or `assets`.`_snipeit_number_of_processors_9` LIKE %FS9RXZ1% or `assets`.`_snipeit_number_of_cpu_cores_10` LIKE %FS9RXZ1% or `assets`.`_snipeit_processor_speed_ghz_11` LIKE %FS9RXZ1% or `assets`.`_snipeit_ram_mb_12` LIKE %FS9RXZ1% or `assets`.`_snipeit_processor_model_13` LIKE %FS9RXZ1% or `assets`.`_snipeit_chassis_14` LIKE %FS9RXZ1% or `assets`.`_snipeit_slot_15` LIKE %FS9RXZ1% or `assets`.`_snipeit_active_directory_last_logon_16` LIKE %FS9RXZ1% or `assets`.`_snipeit_ticket_18` LIKE %FS9RXZ1% or `assets`.`_snipeit_release_station_19` LIKE %FS9RXZ1% or `assets`.`_snipeit_print_protocol_20` LIKE %FS9RXZ1% or `assets`.`_snipeit_configuration_21` LIKE %FS9RXZ1% or `assets`.`_snipeit_location_code_23` LIKE %FS9RXZ1% or `assets`.`_snipeit_pharos_printer_24` LIKE %FS9RXZ1% or `assets`.`_snipeit_decommissioned_25` LIKE %FS9RXZ1% or `assets`.`_snipeit_campus_26` LIKE %FS9RXZ1% or `assets`.`_snipeit_cbs_code_27` LIKE %FS9RXZ1% or `assets`.`_snipeit_verified_29` LIKE %FS9RXZ1% or `assets`.`_snipeit_department_30` LIKE %FS9RXZ1% or `assets`.`_snipeit_cluster_32` LIKE %FS9RXZ1% or `assets`.`_snipeit_primary_server_admin_35` LIKE %FS9RXZ1% or `assets`.`_snipeit_secondary_server_admin_36` LIKE %FS9RXZ1% or `assets`.`_snipeit_operating_system_38` LIKE %FS9RXZ1% or `assets`.`_snipeit_jamf_static_group_39` LIKE %FS9RXZ1% or `assets`.`_snipeit_user_affinity_40` LIKE %FS9RXZ1% or `assets`.`_snipeit_os_info_41` LIKE %FS9RXZ1% or `assets`.`_snipeit_storage_capacity_tb_42` LIKE %FS9RXZ1% or `assets`.`_snipeit_svc_cluster_44` LIKE %FS9RXZ1% or `assets`.`_snipeit_maintenance_end_date_45` LIKE %FS9RXZ1% or `assets`.`_snipeit_maintenance_type_46` LIKE %FS9RXZ1% or `assets`.`_snipeit_university_tag_k_w_47` LIKE %FS9RXZ1% or exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE %FS9RXZ1% and `status_labels`.`deleted_at` is null) or exists (select * from `suppliers` where `assets`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE %FS9RXZ1% and `suppliers`.`deleted_at` is null) or exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE %FS9RXZ1%) or exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE %FS9RXZ1% and `locations`.`deleted_at` is null) or exists (select * from `locations` where `assets`.`location_id` = `locations`.`id` and `locations`.`name` LIKE %FS9RXZ1% and `locations`.`deleted_at` is null) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and (`models`.`name` LIKE %FS9RXZ1% or `models`.`model_number` LIKE %FS9RXZ1%)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and `categories`.`name` LIKE %FS9RXZ1% and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and `manufacturers`.`name` LIKE %FS9RXZ1% and `manufacturers`.`deleted_at` is null)) or `assets_users`.`first_name` LIKE %FS9RXZ1% or `assets_users`.`last_name` LIKE %FS9RXZ1% or `assets_users`.`username` LIKE %FS9RXZ1% or CONCAT(assets_users.first_name," ",assets_users.last_name) LIKE %FS9RXZ1% or `assets_locations`.`name` LIKE %FS9RXZ1% or `assigned_assets`.`name` LIKE %FS9RXZ1%) and `company_id` = %FS9RXZ1% and `assets`.`deleted_at` is null)C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php#669`

- Not reproducible on the demo, can't edit user permissions on demo to test

- Include the output from `php -m` (this should display what modules you have enabled.)

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
imap
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
SPL
standard
tidy
tokenizer
wddx
wincache
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]

-All errors produced by logging in as an admin user assigned to a company with company permissions. No errors occur as a super user.
![Screenshot 2021-08-09 at 11 27 53](https://user-images.githubusercontent.com/56406949/128735945-52deb6cb-95ec-47ad-9489-aefdbae71a33.png)
![Screenshot 2021-08-09 at 11 28 05](https://user-images.githubusercontent.com/56406949/128735970-9e13aeb9-e5d6-403a-b305-9d0434d79eaa.png)

**Comment by RaumfahrerSpiffy** [comment]
My apologies if I left something out, this is my first issue post here. I'll quickly correct any mistakes made.

**Comment by RaumfahrerSpiffy** [comment]
<img width="900" alt="Screenshot 2021-08-09 at 13 41 30" src="https://user-images.githubusercontent.com/56406949/128749806-fb1715b8-3d06-46da-bfd5-b96f6aa6636d.png">

**Comment by RaumfahrerSpiffy** [comment]
Disabling "Full Company Support" fixed the issue for all users. Bug is related to Full Company Support.

**Comment by achitofel** [comment]
I have the same bug in 5.18. disabling the multi-company supports its not a fix :)
hope to get some quick fix to this matter as those admins cannot function

**Comment by PlaneNuts** [comment]
I'm having the same issue. The universal search bar doesn't seem to work in the assets table, but I did notice that if you hit the Advanced Search button (the one with the search field for each attribute), then that one does work correctly. This search bar does work correctly in other types like licenses

I've tried looking to see if I can find where the issue is, but I am admittedly VERY inexperienced when it comes to looking through code. One thing I did notice is the second to last AND statement (after the block from what I think is scopeAssignedSearch) here is trying to search the company_id without a table indicated, and using the search term. I guess this works in license and component searches because only one table is being referenced, but with the assets search multiple tables containing this field are joined. Assets.Company_ID is also the first statement after the where statement. Not sure if this is an issue in company.php function scopeCompanyablesDirectly. 

```
select count(*) as aggregate from 
`assets` 
	inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` 
and `status_alias`.`archived` = 0 
	left join `users` as `assets_users` on `assets_users`.`id` = `assets`.`assigned_to` 
and `assets`.`assigned_type` = App\Models\User 
	left join `locations` as `assets_locations` on `assets_locations`.`id` = `assets`.`assigned_to` 
and `assets`.`assigned_type` = App\Models\Location 
	left join `assets` as `assigned_assets` on `assigned_assets`.`id` = `assets`.`assigned_to` 
and `assets`.`assigned_type` = App\Models\Asset 

where `assets`.`company_id` = 1 

and (`assets`.`name` LIKE %somelongstring% or `assets`.`asset_tag` LIKE %somelongstring% or `assets`.`serial` LIKE %somelongstring% or `assets`.`order_number` LIKE %somelongstring% or `assets`.`purchase_cost` LIKE %somelongstring% or `assets`.`notes` LIKE %somelongstring% or `assets`.`_snipeit_mac_address_1` LIKE %somelongstring% or `assets`.`_snipeit_processor_2` LIKE %somelongstring% or `assets`.`_snipeit_ram_3` LIKE %somelongstring% or `assets`.`_snipeit_video_adaptor_4` LIKE %somelongstring% or `assets`.`_snipeit_regulator_5` LIKE %somelongstring% or exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE %somelongstring% and `status_labels`.`deleted_at` is null) or exists (select * from `suppliers` where `assets`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE %somelongstring% and `suppliers`.`deleted_at` is null) or exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE %somelongstring%) or exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE %somelongstring% and `locations`.`deleted_at` is null) or exists (select * from `locations` where `assets`.`location_id` = `locations`.`id` and `locations`.`name` LIKE %somelongstring% and `locations`.`deleted_at` is null) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and (`models`.`name` LIKE %somelongstring% or `models`.`model_number` LIKE %somelongstring%)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and `categories`.`name` LIKE %somelongstring% and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and `manufacturers`.`name` LIKE %somelongstring% and `manufacturers`.`deleted_at` is null)) or `assets_users`.`first_name` LIKE %somelongstring% or `assets_users`.`last_name` LIKE %somelongstring% or `assets_users`.`username` LIKE %somelongstring% or CONCAT(assets_users.first_name," ",assets_users.last_name) LIKE %somelongstring% or `assets_locations`.`name` LIKE %somelongstring% or `assigned_assets`.`name` LIKE %somelongstring%) 

and `company_id` = %somelongstring% 
and `assets`.`deleted_at` is null 
```

When searching a component this is the query

```
`select count(*) as aggregate from `components` 

where `company_id` = 1 

and (`components`.`name` LIKE '%par%' or `components`.`order_number` LIKE '%par%' or `components`.`serial` LIKE '%par%' or `components`.`purchase_cost` LIKE '%par%' or exists (select * from `categories` where `components`.`category_id` = `categories`.`id` and `categories`.`name` LIKE '%par%' and `categories`.`deleted_at` is null) or exists (select * from `companies` where `components`.`company_id` = `companies`.`id` and `companies`.`name` LIKE '%par%') or exists (select * from `locations` where `components`.`location_id` = `locations`.`id` and `locations`.`name` LIKE '%par%' and `locations`.`deleted_at` is null)) 

and `company_id` = 1 
and `components`.`deleted_at` is null`
```

**Comment by Norjek** [comment]
Looks for me like the same issue as https://github.com/snipe/snipe-it/issues/9985 and https://github.com/snipe/snipe-it/issues/9899 and https://github.com/snipe/snipe-it/issues/9842
Do have the same problem and an upgrade to Version v5.1.8 - build 6257 (master) didn't resolved it either.

**Comment by PlaneNuts** [comment]
I also wanted to comment that this does also seem to be an issue in the demo environment as well. I've seen others say it's not but you need to 

1. Enable full company support in the demo environment
2. Create a user with admin (or lower), but not super admin permissions
3. Log in with that user
4. List all assets
5. Try searching an asset

![image](https://user-images.githubusercontent.com/88776392/131346573-078142d5-be57-4834-a7b7-d28dfce61483.png)

![image](https://user-images.githubusercontent.com/88776392/131346630-a3eb3879-6fd8-4ec8-aa9e-58d9441c3207.png)
