### ISSUE TITLE
LDAP Sync fails on PHP 8

### ISSUE THREAD

**Issue by areis422** [grokability/snipe-it#9922]
#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When running on php 8.0, artisan snipeit:ldap-sync fails due to using a removed function:  https://www.php.net/manual/en/function.ldap-control-paged-result.php

**Expected behavior**
ldap sync succeeds on php8

**Server (please complete the following information):**
 - Snipe-IT Version: git latest
 - OS: [e.g. Ubuntu, CentOS]: Ubuntu 20.04
 - Web Server: [e.g. Apache, IIS]: Apache 2.4.latest
 - PHP Version : 8.0.9

**Error Messages**
Symfony\Component\Debug\Exception\FatalThrowableError : Call to undefined function App\Models\ldap_control_paged_result()

**Comment by francogp** [comment]
snipe-it it's supposed to run with php 7.4, not 8.0+. Running check-platform-reqs will list all unsupported components for php 8.0
