### ISSUE TITLE
database upgrade

### ISSUE THREAD

**Issue by conan522** [grokability/snipe-it#9926]
I used v4.9.3 for a while. It is a nice system, thanks for your great working. Just want to know how to use command to manually upgrade the database to the latest version without date lost. Thanks.

**Comment by snipe** [comment]
No data should ever be lost. When you upgrade, you download new files, and then run a few commands as documented in the upgrading docs. Those commands, specifically `php artisan migrate` make sure that your database is up to date with the most recent code you have on your machine.

**Comment by conan522** [comment]
Thanks for your quick reply. I will try it. Have a nice day.

**Comment by snipe** [comment]
You too - please let us know how you make out. :)
