### ISSUE TITLE
How to restore database in Snipe-IT hosted service?

### ISSUE THREAD

**Issue by itaxpo** [grokability/snipe-it#9927]
Hello.
I've just bought Your annually hosted service after having self hosted environment. I've backed the database up via GUI and have sql format backup.
How can I restore the data from my backups to database hosted by You? Is there any way to access the backend environment and restore the database?
Using API will be some difficult. Or maybe it's some way to restore whole database using API?

Best
Axpo Poland

**Comment by uberbrady** [comment]
Hi there! Please contact us at support@snipeitapp.com and we'll help walk you through this - we just need your last backup, and your previous APP_KEY (which you should be able to find in your `.env` file, which should be in your Snipe-IT directory). We'll take a few business days to perform the migration, and will let you know when you're all set.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
