### ISSUE TITLE
OpenAPI Spec v2 (swagger)

### ISSUE THREAD

**Issue by kjacobsen** [grokability/snipe-it#9932]
**Server (please complete the following information):**
 - Snipe-IT Version: Hosted

**Is your feature request related to a problem? Please describe.**
I am working with some third-party automation (Power Platform) to connect to the Snipe IT API, unfortunately it only support Open API Specification version 2 files and not the version 3 files currently available.

**Describe the solution you'd like**
An OAS version 2 file for the Snipe IT API.

**Comment by snipe** [comment]
Unfortunately, we use a third party platform to handle our docs. This documentation might be helpful though: https://blog.readme.com/how-to-use-openapi-and-swagger-spec-for-documentation/

<blockquote><img src="https://blog.readme.com/content/images/2020/07/Schoolroom_openapi_swagger_for_documentation.png" width="48" align="right"><div><img src="/favicon.ico" height="14"> The ReadMe Blog</div><div><strong><a href="https://blog.readme.com/how-to-use-openapi-and-swagger-spec-for-documentation/">ReadMe: OpenAPI and Swagger for API Documentation</a></strong></div><div>In this guide, we explain Swagger and the current OpenAPI standard, how to create an OpenAPI or Swagger description for your API, and how using the OpenAPI Specification can yield documentation that’s continuously up-to-date and automated.</div></blockquote>
