### ISSUE TITLE
Mobile version does not align content, hide menus, and broken links

### ISSUE THREAD

**Issue by francogp** [grokability/snipe-it#9935]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Using the web on chrome (andorid 11) there's a lot of glitches that prevent me to use lots of features or buttons, because they get hidden or broken. I can reproduce it on my hosted web (latest from git) and on the public demo. The screenshot attached are from the public web.

**Expected behavior**
bootstrap can format very well the content to mobile devices. It seems that not the case here. THERE'S A LOT OF CASES, I'm just pointing some of them on the screenshots.

**To Reproduce**
1. Follow the screenshots

**Screenshots**
![InkedScreenshot_2021-08-16-14-28-00-387_com android chrome_LI](https://user-images.githubusercontent.com/2739706/129605585-15365ba7-9006-45b0-9ecb-2327d6643440.jpg)
![InkedScreenshot_2021-08-16-14-24-42-934_com android chrome (2)_LI](https://user-images.githubusercontent.com/2739706/129605599-1170078e-b1aa-418d-9a4a-775b11de01e2.jpg)
![InkedScreenshot_2021-08-16-14-27-17-987_com android chrome_LI](https://user-images.githubusercontent.com/2739706/129605610-6453e905-776a-45a7-8f1c-0c65c6e3c866.jpg)
![InkedScreenshot_2021-08-16-14-27-49-371_com android chrome_LI](https://user-images.githubusercontent.com/2739706/129605614-87b7d587-9932-4938-a08b-7359096cbf9f.jpg)
![InkedScreenshot_2021-08-16-14-46-55-356_com android chrome_LI](https://user-images.githubusercontent.com/2739706/129607190-f955e5a9-f9e3-4bfe-b854-01edb85c4c71.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version: Git Version v5.1.8 - build 6227 (master)
 - OS: ubuntu 20.04
 - Web Server: Apache
 - PHP Version 7.4

**Smartphone:**
 - Device: Redmi note 9 Pro (bu can reproduce it on other phones and brands)
 - OS: andorid 11
 - Browser: google chrome
 - Version: 92.0.4515.131

**Additional context**
- Fresh install
- Can be reproduced on the online DEMO (like the screenshots)

**Comment by francogp** [comment]
![InkedScreenshot_2021-08-16-15-46-00-046_com android chrome_LI](https://user-images.githubusercontent.com/2739706/129615373-ffb73ada-dce6-4a65-9076-aa65a1b349ce.jpg)
If I check "desktop compatibility mode" on the browser, I can see the menu but cannot click on assets.
It's almost unusable on mobile

I can click on options (foldable UI) but not on assets (also foldable UI).

**Comment by snipe** [comment]
@Godmartinz can you take a look at this?

**Comment by francogp** [comment]
![Screenshot_20210817_083004](https://user-images.githubusercontent.com/2739706/129718528-20b908db-6e09-4a2e-87bf-d675adec52e5.png)
I also cannot see URL from suppliers

**Comment by francogp** [comment]
![Captura de pantalla 2021-08-18 075735](https://user-images.githubusercontent.com/2739706/129886699-f26f2be4-0da3-483c-8d3b-bfc05ecf9682.png)
On consumables, I cannot seach by column Model No. I can filter other columns, but cannot seach by that column

**Comment by francogp** [comment]
![IMG_20210821_092223](https://user-images.githubusercontent.com/2739706/130321631-e8d0f5b1-0e3e-4aec-9668-a2dc691d5ae9.jpg)
![IMG_20210821_092134](https://user-images.githubusercontent.com/2739706/130321633-450988e7-8d69-4081-8acd-62a8197cd14a.jpg)

**Comment by hntrl** [comment]
Is anyone working on this? Is this gonna be fixed in v6? I'd take a crack at it if no-one else is.

**Comment by snipe** [comment]
It’s already been worked on, but by all means, if v5.2.0 is missing some fixes, by all means, I’ll take the PR
