### ISSUE TITLE
Auto-fill of asset numbers for lookup

### ISSUE THREAD

**Issue by VA2XJM** [grokability/snipe-it#9936]
**Server (please complete the following information):**
 - Snipe-IT Version V5.1.8
 - OS: Debian 10
 - Web Server: Apache2
 - PHP Version 7.4

**Is your feature request related to a problem? Please describe.**
when entering asset number in the "lookup by asset tag" it needs to correspond exactly to the asset wanted. So in my case if I want to lookup asset `#1`, I must enter `0000000001` otherwise I get error.

**Describe the solution you'd like**
In the lookup process, if asset tag entered is not corresponding to configured values (zero fill and maybe prefix(I don't use it), the lookup script would auto-complete the prefix and zero fill for users.

This would accelerate the process and reduce wrong entry (missed a zero or two.

**Describe alternatives you've considered**
Not really others.

**Additional context**
![image](https://user-images.githubusercontent.com/13443249/129628371-19b22c49-2f99-4f86-bc38-e731ffb71803.png)
![image](https://user-images.githubusercontent.com/13443249/129628522-a1ea5d1c-d9b3-4143-b952-edb5b76f615a.png)

**Comment by snipe** [comment]
That field is meant to be used with a barcode scanner, it's not meant to be a fuzzy search.
