### ISSUE TITLE
Cannot change date format (config ignored)

### ISSUE THREAD

**Issue by francogp** [grokability/snipe-it#9942]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Dates format are ignored. I set 25/08/2021 as format, but all items use 2021-08-25

**To Reproduce**
1. Change localization date settings
2. Try to use it on "buy date" for example

**Expected behavior**
write a date using 25/08/2021 format

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.8 - build 6227 - git
 - OS: ubuntu 20.04
 - Web Server: apache
 - PHP Version 7.4 

**Additional context**
- Fresh install

**Comment by snipe** [comment]
> but all items use 2021-08-25

All date selectors will use YYYY-MM-DD format, since that's what the database is expecting. They display in output as the selected date format. This is working as expected.

**Comment by francogp** [comment]
![image](https://user-images.githubusercontent.com/2739706/132324183-a885678d-89f1-474f-865c-b88c1b1f8a3c.png)
@snipe today I added a new date field, and it is not using the correct format.
The second one is correct

  Version v5.1.8 - build 6257 (develop)
