### ISSUE TITLE
Unable to update field values for custom field without changing the name

### ISSUE THREAD

**Issue by zackbennis** [grokability/snipe-it#9949]
#### Please confirm you have done the following before posting your bug report:

- [ n/a ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When using the PUT for the 'fields/:id' endpoint to update a custom field's "field_values" for element type "listbox", the 'name' value is required, despite the field number already being specified. We don't want to update the name, so we tried using the same name, but we get the error, "The name has already been taken." 

Since we're only updating the listbox values, we shouldn't have to supply a name when the field id has already been passed in the URL. When using no 'name' value, it returns an error saying that the 'name' field is required.

**To Reproduce**
1. Use the /fields/:id PUT endpoint to update the listbox of a custom field.
2. In the JSON, omit the name, or use the same name as the field you're updating.
3. Error: Returns that the name field is required or that the name is already in use.

**Expected behavior**
Should not have to provide a name for an update action when the field ID is already supplied.

**Server (please complete the following information):**
 - Hosted Snipe-IT, v5.1.6

**Desktop (please complete the following information):**
 - Insomnia, PHP

**Comment by snipe** [comment]
You should be using a PATCH for that then, as PATCH updates only a partial record.

**Comment by zackbennis** [comment]
I tried that, but it didn't work. I also couldn't find documentation on a PATCH for that endpoint.

edit: Also, thanks for the quick reply :-)

**Comment by snipe** [comment]
You're totally right - I don't see that capability in the API. Give me a little bit and we'll have that up for you. Also please send an email to support@snipeitapp.com so we can make sure to bump your version once the fix is pushed - if you think to this issue, they can take it from there :)

**Comment by zackbennis** [comment]
Will do; thanks again for your super expedient replies!

**Comment by snipe** [comment]
Actually, I lied. This method here should do it:

https://github.com/snipe/snipe-it/blob/04fa5f20229e39df3d4b80209a42440aa6c3182a/app/Http/Controllers/Api/CustomFieldsController.php#L57-L81

When you say it didn't work, did you get the same error as when you tried a PUT?

**Comment by snipe** [comment]
(Also if you can post a cURL command with your Bearer token XXXXXXed out, I can try to replicate. (Or just open a ticket, whichever works best for you. I'll probably be the one handling that ticket anyway :) )

**Comment by zackbennis** [comment]
Here you go:

`curl --request PATCH \
  --url https://<snipe-instance-url>/api/v1/fields/16 \
  --header 'Accept: '\''application/json'\''' \
  --header 'Authorization: Bearer XXXXXX' \
  --header 'Content-Type: '\''application/json'\''' \
  --data '{
	"name": "Test Field",
	"element": "listbox",
  "field_values": "Test1\r\nTest2\r\nTest3\r\nTest4"
}'`

**Comment by snipe** [comment]
Thanks for the example - in digging into this yesterday I think this is something on our end (but not the obvious stuff). I’m investigating and will let you know what I find

**Comment by zackbennis** [comment]
Any update on this? We have a workaround, but it's causing some bugginess in our workflow.

**Comment by StarlessNights** [comment]
Just ran into this issue when I was investigating the API's capabilities. Like this it's not suitable for implementing list type custom fields with dynamic choices. Clearly a problem.

@zackbennis may I inquire about your workaround?

**Comment by zackbennis** [comment]
@StarlessNights - In our script, we're simply updating the name with one curl, then pushing the changes and reverting the name to the original name with a second curl. The issue is we have a bunch of scripts checking this data, so if there's ever a hiccup and the temp name sticks (which has happened), it throws off a bunch of our other logic. We've built in some additional error checking for this, but it's less than ideal, for sure.

**Comment by viclou** [comment]
+1 FD 31447
