### ISSUE TITLE
✨Discord has replaced Gitter ✨

### ISSUE THREAD

**Issue by snipe** [grokability/snipe-it#9954]
https://discord.gg/yZFtShAcKk

Here’s the invite link :)

**Comment by Norjek** [comment]
Can't join, gettin' the message: This invite seems to be invalid or has expired

**Comment by Godmartinz** [comment]
https://discord.gg/D8dtqUBC here is an updated invite link

**Comment by snipe** [comment]
Here's one that won't expire (hopefully): https://discord.gg/yZFtShAcKk
