### ISSUE TITLE
Commit 4519f6e1 breaks tables if any values are null

### ISSUE THREAD

**Issue by yaheath** [grokability/snipe-it#9957]
I just updated, and the assets view stopped loading, with a javascript error appearing in the console.

The problem is the new `cleanFloat` function might get passed a null value in the `number` argument, which throws an error when it tries to call `number.toString()`.

You either need to check for null in `cleanFloat` or modify the call site in `sumFormatter` so it looks like this:
 `return (sum) + cleanFloat(row[field] || 0);`

**Comment by snipe** [comment]
@uberbrady take a look at this today please

**Comment by snipe** [comment]
This was fixed in #9960
