### ISSUE TITLE
Listing assets results in "Loading... Please wait" indefinitely after upgrading from 4.9.5 to 5.1.8. 

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#9959]
- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Listing assets results in "Loading... Please wait" indefinitely after upgrading from 4.9.5 to 5.1.8. 

**To Reproduce**
1. Assets > List all

**Expected behavior**
Lists all assets as before

**Server (please complete the following information):**
 - Snipe-IT Version: 5.1.8 
 - OS: Ubuntu 20
 - Web Server: Apache
 - PHP Version: 7.4.3  

**Desktop (please complete the following information):**
 - OS: [Any]
 - Browser: Firefox, Chrome

The data seems to be all there; I can view each asset individually but cannot list them in any category (List all, deployed, etc.) All other functionality seems to work just fine. 

Firefox console shows the following error on the assets, list all page:
Uncaught TypeError: number is null
    cleanFloat http://snipeit/hardware:1336
    total_sum http://snipeit/hardware:1345
    sumFormatter http://snipeit/hardware:1344
    calculateObjectValue http://snipeit/js/dist/bootstrap-table.js?id=a17945119a381c758e1f:3585
    initFooter http://snipeit/js/dist/bootstrap-table.js?id=a17945119a381c758e1f:6177
    initBody http://snipeit/js/dist/bootstrap-table.js?id=a17945119a381c758e1f:5661
    toggleView http://snipeit/js/dist/bootstrap-table.js?id=a17945119a381c758e1f:7148
    changeTableView http://snipeit/js/dist/bootstrap-table.js?id=a17945119a381c758e1f:8712
    conditionFullView http://snipeit/js/dist/bootstrap-table.js?id=a17945119a381c758e1f:8705
    changeView http://snipeit/js/dist/bootstrap-table.js?id=a17945119a381c758e1f:8741
    init http://snipeit/js/dist/bootstrap-table.js?id=a17945119a381c758e1f:8677
    later http://snipeit/js/dist/bootstrap-table.js?id=a17945119a381c758e1f:8612

**Comment by ghost** [comment]
Also: Snipe, thank you so much for writing this awesome software. SnipeIT has helped my IT department significantly :)

**Comment by snipe** [comment]
Hi @corporatefoo - this should be fixed on master now (fixed in  #9960) - you had exceptionally bad timing, as this bug was introduced just yesterday :)

Thanks for the kind words - a fresh pull from master should resolve this issue.

**Comment by uberbrady** [comment]
Also @corporatefoo  I would like to say “Thank You” for such a detailed, excellent bug report. It’s not often that we get those. Having those detailed made it much, much easier for me to solve that issue.

**Comment by ghost** [comment]
@snipe Wow thank you for the quick response!! Much appreciated!! :star_struck: 

@uberbrady No problem! I'm a sysadmin and definitely understand the value of detailed bug reports. Thank you so much for addressing this quickly.

I'll report back to confirm the fix on my end.

**Comment by ghost** [comment]
Confirmed fixed!!! 

Thanks again for fixing this so fast! I wish I could buy you both a beer! :beers:

**Comment by maciej-jankowski-wizzdev** [comment]
> Hi @corporatefoo - this should be fixed on master now (fixed in #9960) - you had exceptionally bad timing, as this bug was introduced just yesterday :)
> 
> Thanks for the kind words - a fresh pull from master should resolve this issue.

I have same problem and want to update. What should I do? Whole upgrade?
