### ISSUE TITLE
Cannot search on a report if using Spanish - Mexican

### ISSUE THREAD

**Issue by francogp** [grokability/snipe-it#9962]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Cannot search anything on the report tab, if I set language to Spanish-Mexican

**To Reproduce**
1. set language to spanish mexican (using english work just fine on the demo web)
2. create some activity
3. try to search anything over any column
4. empty table as result

**Expected behavior**
show some results 

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.8 - build 6227 (master)
 - OS: Ubuntu 20.04
 - Web Server: Apache
 - PHP Version 7.4

**Comment by snipe** [comment]
@inietov can you take a look?

**Comment by inietov** [comment]
Just because im mexican? Are you discriminating me? Just kidding!! Glad to take a look!!

**Comment by snipe** [comment]
LOL @inietov 😂😂

**Comment by francogp** [comment]
![image](https://user-images.githubusercontent.com/2739706/130827846-1c835ce3-2be0-408d-bf9e-0e4691cba04c.png)
Its definetly a language problem. For example, in that image is set to Spanish - Mexican, if I search the word "asset" (4th column) or  the word "checked" (7th column) it work, but If I search an user name, an item name, or an action like "asignar" or "crear localización" it does not work.

(ALSO note that there's a lot of missing translations, but that's another problem)

**Comment by inietov** [comment]
Hey, @francogp 
I'm looking at the Activity Report in my local instance of Snipe-It (since in the demo you can't change the language), and it works similar no matter what language I have setted. My only doubt is with your column `Acción` i see that in your screenshot the actions are equaly translated (asignar a un usario, crear localización, etc), but in my instance the actions keep appearing in english, like this:
![image](https://user-images.githubusercontent.com/653557/130873123-289bff4b-3e97-4b45-bf57-cb3a6855303d.png)

So... I'm not sure if I'm looking in the same sreen than you.

**Comment by francogp** [comment]
> Hey, @francogp
> I'm looking at the Activity Report in my local instance of Snipe-It (since in the demo you can't change the language), and it works similar no matter what language I have setted. My only doubt is with your column `Acción` i see that in your screenshot the actions are equaly translated (asignar a un usario, crear localización, etc), but in my instance the actions keep appearing in english, like this:
> ![image](https://user-images.githubusercontent.com/653557/130873123-289bff4b-3e97-4b45-bf57-cb3a6855303d.png)
> 
> So... I'm not sure if I'm looking in the same sreen than you.

1) I tested on a fresh install.. and can reproduce the problem,
2) only reproducible on spanish, or spanish mexican
3) today I tried switching back to english and it does not work either,

and yes, that the same screen
Why there's so many differences?

I installed snipe-it on 2 different PC, and get the same bug, and the same results.

Can I provide some log or database to you to take a look?

**Comment by francogp** [comment]
![image](https://user-images.githubusercontent.com/2739706/130884665-bfbe2422-73e4-40a1-ba52-df9739eb3148.png)
chrome report this errors when I click on report tab

the first error payload is 
![image](https://user-images.githubusercontent.com/2739706/130884901-48e5acf1-b20a-4e75-8ffd-25a61603fd41.png)

the database does not contain the word "asignar.." it contain the english version, but in the table it show the translated word "asignar..". That's why when I search in spanish, I cannot see any results in that column. 

Don't know why I cannot search by username. It return empty table too.
```select * from `action_logs` where (`action_logs`.`action_type` LIKE '%checkin%' or `action_logs`.`note` LIKE '%checkin%' or `action_logs`.`log_meta` LIKE '%checkin%' or exists (select * from `companies` where `action_logs`.`company_id` = `companies`.`id` and `companies`.`name` LIKE '%checkin%')) and `action_logs`.`deleted_at` is null order by `created_at` desc limit 20 offset 0```
Looking at the query, it seems that it does not include the users in the search

**Comment by francogp** [comment]
![image](https://user-images.githubusercontent.com/2739706/130887027-416cd81d-5c43-4353-a1db-6b47428c1dfe.png)

if I search in ENGLISH, it works... but that's not intuitive to see spanish and search in english

**Comment by francogp** [comment]
![image](https://user-images.githubusercontent.com/2739706/130887565-ce932ce9-def8-4b2e-ab5e-63bab765ab18.png)
If I switch to english, the column **ACTION stay en spanish.**

**Comment by snipe** [comment]
@francogp if you check your actual action_log database table for those records, is it in English or Spanish under the action column?

**Comment by francogp** [comment]
> @francogp if you check your actual action_log database table for those records, is it in English or Spanish under the action column?

![image](https://user-images.githubusercontent.com/2739706/130888206-46e44d62-d896-4ff6-ad83-b1b3a898cff4.png)

english

**Comment by snipe** [comment]
Okay, that’s probably better then. The DB internals use English, and we try to display stuff on the output in whatever chosen locale there is. 

Okay… I may have a hunch what’s happening here, but I need to be in front of a computer to confirm. I have jury duty tomorrow so may or may not be able to look into this, but @inietov may be able to check it out while I’m afk

**Comment by snipe** [comment]
(Also can you confirm that using a different language other than Mexican Spanish gives the same results? It would seem weird if that’s true, since we have tons of people using non-English languages, but I’d like to be able to rule it out.)

**Comment by francogp** [comment]
> (Also can you confirm that using a different language other than Mexican Spanish gives the same results? It would seem weird if that’s true, since we have tons of people using non-English languages, but I’d like to be able to rule it out.)

![image](https://user-images.githubusercontent.com/2739706/130937688-6c49f83c-074c-4305-9c45-f86436cf07cd.png)

I tested italian, and the action column stay in spanish. Also tested english UK and US, with the same results.

**Comment by inietov** [comment]
I'll never can reproduce this. Today I tried again but also failed :(

I think I'm going to close this and hope that maybe it's not happening anymore. Also, we now query for users in the activity report, which is also mentioned in this issue.

**Comment by francogp** [comment]
> I'll never can reproduce this. Today I tried again but also failed :(
> 
> I think I'm going to close this and hope that maybe it's not happening anymore. Also, we now query for users in the activity report, which is also mentioned in this issue.

As I said before, I can reproduce it on a fresh install. Now, I can reproduce it on the latest GIT version.

For example:
![image](https://user-images.githubusercontent.com/2739706/190997421-28e9f057-d86d-4592-8222-7704a28ba2a8.png)

If I complete the search...
![image](https://user-images.githubusercontent.com/2739706/190997495-f384eb87-1eb2-44ac-aae9-ba2819d74383.png)
