### ISSUE TITLE
Sorting stock by numbers does not work like online demo

### ISSUE THREAD

**Issue by francogp** [grokability/snipe-it#9963]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If I sort consumible by total, it get sorted lexicographically but not by number order

**To Reproduce**
1. go to consumibles
2. click to sort by total

**Expected behavior**
a sorted table by numbers

**Screenshots**
![Screenshot_20210820_123422](https://user-images.githubusercontent.com/2739706/130257657-2e3e32b3-2529-4912-b54f-88c1772888cb.png)

**Server (please complete the following information):**
 - Snipe-IT Version  v5.1.8 - build 6227 (master)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version 7.4

**Comment by snipe** [comment]
The code on the demo is the same code that runs on the master branch, so I'm not exactly sure what to tell you here.

**Comment by francogp** [comment]
I tried a fresh install with the same results. Seems that the problem happens if I set Spanish ,or Spanish Mexican from the beginning. That's odd

**Comment by inietov** [comment]
Total and remaining columns are not sortable in any case:
![image](https://user-images.githubusercontent.com/653557/190280753-6da4aaef-08bd-418e-94b7-4c4594eab1a0.png)
