### ISSUE TITLE
D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

### ISSUE THREAD

**Issue by aebada90** [grokability/snipe-it#9971]
Hey, I just installed the code on  the server and I am getting this error

https://vpfit.co/

![image](https://user-images.githubusercontent.com/25064051/130459280-99aeda2b-f78c-4b24-b3f4-74b9caeac248.png)

**Comment by francogp** [comment]
You should do what the message says, point Apache configs to the public folder inside snipe-it, not to snipe-it folder.

**Comment by aebada90** [comment]
From me it is not clear, w
from where can I change that?

**Comment by francogp** [comment]
You should read the installation manual
