### ISSUE TITLE
Failing to create new asset, it clear lots of non saved fields

### ISSUE THREAD

**Issue by francogp** [grokability/snipe-it#9972]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If I fail to register a new asset, for example because I forgot to fill a field or it fail a pattern matching, lots of other non saved custom fields get cleared, and I have to rewrite all of them and fix the failed one.

**To Reproduce**
1. Fill the form to create a new asset with custom fields
2. do not fill some "must fill" field
3. save
4. see the red field to correct, but all other custom field got cleared

**Expected behavior**
to maintain all written fields, until I fix the wrong one

**Server (please complete the following information):**
 - Snipe-IT Version 5.1

**Comment by francogp** [comment]
It also affect serial number, and that field is not a custom one

**Comment by francogp** [comment]
Asignation also get reset when save fail

**Comment by snipe** [comment]
Can you reproduce this on the demo?

**Comment by francogp** [comment]
> Can you reproduce this on the demo?

of course, loots of field (not all), specially custom fields, got reseted when I faill to save a new asset. Checkbox, assigned locations, serial numbers, etc

**Comment by inietov** [comment]
Also can't be reproduced. If the creation of the asset fails, the filled fields remain, even custom ones. See how the field is red because of an error, but the other fields still filled in the screenshot.
![image](https://user-images.githubusercontent.com/653557/190281255-98fcb665-1ad8-4202-8c3f-d729bcdf714b.png)
