### ISSUE TITLE
use_default_eula missing in categories

### ISSUE THREAD

**Issue by diegogarciadev** [grokability/snipe-it#9973]
Api endpoint categories doesn't return the value of "use_default_eula", code from https://snipe-it.readme.io/reference/categoriesid-3

{
  "id": 1,
  "name": "blabla",
  "image": null,
  "category_type": "Asset",
  "has_eula": true,
  "eula": "<p>Dolor vitae dolores voluptates quos. Animi quod quia vel deleniti dolore est vitae. Est quia ad debitis delectus.</p>",
  "checkin_email": false,
  "require_acceptance": true,
  "item_count": 1175,
  "assets_count": 0,
  "accessories_count": 0,
  "consumables_count": 0,
  "components_count": 0,
  "licenses_count": 0,
  "created_at": {
    "datetime": "2021-08-22 21:00:02",
    "formatted": "Sun Aug 22, 2021 9:00PM"
  },
  "updated_at": {
    "datetime": "2021-08-23 09:44:37",
    "formatted": "Mon Aug 23, 2021 9:44AM"
  },
  "available_actions": {
    "update": true,
    "delete": false
  }
}

**Comment by diegogarciadev** [comment]
This issue is not solved, I can't update this field with api request

Regards

**Comment by snipe** [comment]
It is on master. I’ve tested it.
