### ISSUE TITLE
APP_URL variable being ignored, causing CORS errors

### ISSUE THREAD

**Issue by rajivdotsh** [grokability/snipe-it#9975]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Hi folks, bit of a weird issue on a fresh install of snipe-it on Ubuntu 20.04 - even with the APP_URL set in the .env file, the setup page still requests resources from the server IP (192.168.x.x) rather than the TLD as defined in the .env file, resulting in CORS errors and therefore no image assets loading. This is through a reverse proxy terminating SSL with a proper cert vs the self-signed one installed on the snipe-it box.

The proxy is sending the usual headers:

```        
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

**To Reproduce**
1. Set up a fresh install of snipe-it on Ubuntu 20.04
2. Edit the .env file to have an app URL set (terminated through a reverse proxy)
3. Visit the snipe-it instance through a reverse proxy

**Expected behavior**
Images and other assets should load as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/54782649/130495128-93724d03-65fe-497d-9c35-01ee68570f2a.png)
![image](https://user-images.githubusercontent.com/54782649/130495250-5a375dbe-bca5-46ab-9698-7539abb59523.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.8
 - OS: Ubuntu 20.04
 - Web Server: Apache
 - PHP Version 8.0

**Desktop (please complete the following information):**
 - OS: Windows Enterprise
 - Browser: Chrome
 - Version 92.0.4515.159

**Error Messages**
- Any errors that appear in your browser's error console.
`Access to font at 'https://192.168.x.x/css/fonts/fontawesome-webfont.ttf?v=4.7.0' from origin 'https://domain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
It is not

**Additional context**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation

I've pasted my .env and Apache config below. Thanks in advance!

~~~
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=[redacted]
APP_URL=https://test.domain.com
APP_TIMEZONE='Europe/London'
APP_LOCALE=en-GB
MAX_RESULTS=500

# --------------------------------------------
# REQUIRED: UPLOADED FILE STORAGE SETTINGS
# --------------------------------------------
PRIVATE_FILESYSTEM_DISK=local
PUBLIC_FILESYSTEM_DISK=local_public

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
[snip]

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_IS_PAAS=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
[snip]

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=imagick


# --------------------------------------------
# OPTIONAL: BACKUP SETTINGS
# --------------------------------------------
MAIL_BACKUP_NOTIFICATION_DRIVER=null
MAIL_BACKUP_NOTIFICATION_ADDRESS=null
BACKUP_ENV=true


# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false
API_TOKEN_EXPIRATION_YEARS=15

# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
APP_TRUSTED_PROXIES=192.168.55.199
ALLOW_IFRAMING=false
REFERRER_POLICY=same-origin
ENABLE_CSP=false
CORS_ALLOWED_ORIGINS=null
ENABLE_HSTS=false

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=redis
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHE_PREFIX=snipeit

# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

# --------------------------------------------
# OPTIONAL: MEMCACHED SETTINGS
# --------------------------------------------
MEMCACHED_HOST=null
MEMCACHED_PORT=null

# --------------------------------------------
# OPTIONAL: PUBLIC S3 Settings
# --------------------------------------------
PUBLIC_AWS_SECRET_ACCESS_KEY=null
PUBLIC_AWS_ACCESS_KEY_ID=null
PUBLIC_AWS_DEFAULT_REGION=null
PUBLIC_AWS_BUCKET=null
PUBLIC_AWS_URL=null
PUBLIC_AWS_BUCKET_ROOT=null

# --------------------------------------------
# OPTIONAL: PRIVATE S3 Settings
# --------------------------------------------
PRIVATE_AWS_ACCESS_KEY_ID=null
PRIVATE_AWS_SECRET_ACCESS_KEY=null
PRIVATE_AWS_DEFAULT_REGION=null
PRIVATE_AWS_BUCKET=null
PRIVATE_AWS_URL=null
PRIVATE_AWS_BUCKET_ROOT=null

# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60
RESET_PASSWORD_LINK_EXPIRES=900

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOG_MAX_FILES=10
APP_LOCKED=false
APP_CIPHER=AES-256-CBC
APP_FORCE_TLS=false
GOOGLE_MAPS_API=
LDAP_MEM_LIM=500M
LDAP_TIME_LIM=600
IMPORT_TIME_LIMIT=600
IMPORT_MEMORY_LIMIT=500M
REPORT_TIME_LIMIT=12000
~~~

```
<VirtualHost *:80>
    RewriteEngine On
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on

    ServerName [redacted]

    SSLCertificateFile      /etc/ssl/certs/selfsigned.crt
    SSLCertificateKeyFile   /etc/ssl/private/selfsigned.key

    # enable HTTP/2, if available
    Protocols h2 http/1.1

    <Directory /var/www/snipe-it/public>
        Allow From All
        AllowOverride All
        Options -Indexes
    </Directory>

    DocumentRoot /var/www/snipe-it/public

</VirtualHost>

# intermediate configuration
SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
SSLCipherSuite          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
SSLHonorCipherOrder     off
SSLSessionTickets       off
```

**Comment by snipe** [comment]
Did you run all the cache clearing stuff, as recommended here? https://snipe-it.readme.io/docs/common-issues#quick-tip-handy-commands

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues#quick-tip-handy-commands">Common Issues</a></strong></div><div>  These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin.Or to run them as a one-liner all at once:These commands clear out cached service files that help speed up modern PHP applications but can a...</div></blockquote>

**Comment by rajivdotsh** [comment]
Hi, yep - ran the clearing stuff and checked the composer dependencies - all good apart from alek13/slack because we're using PHP8 but I'm assuming that's fine to ignore

Thanks!

**Comment by DevTeq** [comment]
I'm running into the same issue.
My setup is a little bit different, I serve Snipe-IT without SSL, but Nginx is serving it with SSL by proxy.

Problem: When I log in, I get an **Not allowed in CORS policy**. error.

Adding the IP to the CORS_ALLOWED_ORIGINS seem to solve the problem, but causes problems elsewhere on SAML for example.

**Comment by snipe** [comment]
This was already fixed
