### ISSUE TITLE
Feature request: Or Bug report? - Status Changes in Activity Report when Asset is Checked In/Out.

### ISSUE THREAD

**Issue by Thomas-CPOC** [grokability/snipe-it#9976]
**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.6
 - OS: Win10
 - Web Server: Unsure
 - PHP Version: 7.3.23

**Is your feature request related to a problem? Please describe.**
When Checking In or Out an asset, The Activity Log does not record any other changes to the asset other than Who or Where the asset is being checked out/in to. Bulk Check Edit feature also does not record in the Activity Log.

**Describe the solution you'd like**
Asset status changes to be recorded in the activity log during Check in/out. We currently use the activity log as a way to track employees work and as the activity log tracks changes right now, if someone were to check out an asset and change the status of that asset in the same "transaction", the activity log only shows that the asset was checked out. It does not show the change in status.

**Describe alternatives you've considered**
No work around currently.

**Additional context**
![image](https://user-images.githubusercontent.com/86486063/130513553-d949e196-5a47-43db-b479-6fa0d2dd0fd3.png)

**Comment by sedgwick** [comment]
I feel this is an important security feature as well. When you make a bulk-edit not only does the status not change on the activity log but it doesn't appear in the asset's history. A user could make an edit of a dozen assets and there would be no record of who made the change.

Just adding a +1 that I'd like to see this added as well!

**Comment by inietov** [comment]
Already addressed in https://github.com/snipe/snipe-it/pull/10586 and https://github.com/snipe/snipe-it/pull/10590.
