### ISSUE TITLE
Stuck in Debugging Mode

### ISSUE THREAD

**Issue by kendalgoodrich** [grokability/snipe-it#9977]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I get the red Warning banner stating debugging is enabled despite configuration in .env file

**To Reproduce**
Open snipe and red banner is displayed despite configuration.

**Expected behavior**
Expect pages without the big red warning banner stating I'm in debugging Mode.

**Screenshots**
Screenshot Attached
![SnipeBug](https://user-images.githubusercontent.com/12582504/130519923-b1fcf5a6-ec53-485f-bc0f-84a87cb32733.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version : 5.1.8
 - OS: Windows Server 2019 Datacenter
 - Web Server: IIS
 - PHP Version : 7.4.22

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser : Chrome, Safari and Edge
 - Version : Latest Versions

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error : NA
- If a stacktrace is provided in the error, include that too. : NA
- Any errors that appear in your browser's error console. : NA
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. : NA
- Include any additional information you can find in `storage/logs` and your webserver's logs. NA
- Include the output from `php -m` (this should display what modules you have enabled.)
C:\snipe-it>php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
fileinfo
filter
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install / Even ran php Upgrade.php successfully to attempt resolution.
- What OS and web server you're running Snipe-IT on : Windows Server 2019 Datacenter and IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : Manual
- Include what you've done so far in the installation, and if you got any error messages along the way. : I have changed the APP_DEBUG value back and forth and issued the "php artisan config:cache" multiple times to no avail. I've even issued all the commands here https://snipe-it.readme.io/docs/common-issues and restarted the server and attempted to access from another machine. Same issue "Red Warning banner". I confirm that after issuing the php artisan config:cache command, that the config.php file is recreated/updated and the arrays are updated in the file.
- Indicate whether or not you've manually edited any data directly in the database : No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Did you try running `php artisan config:clear` to clear out the cached configuration values?

**Comment by kendalgoodrich** [comment]
Yes I did

**Comment by snipe** [comment]
Also try the rest of the cache clearing commands here: https://snipe-it.readme.io/docs/common-issues#quick-tip-handy-commands

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues#quick-tip-handy-commands">Common Issues</a></strong></div><div>  These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin.Or to run them as a one-liner all at once:These commands clear out cached service files that help speed up modern PHP applications but can a...</div></blockquote>

**Comment by kendalgoodrich** [comment]
I did, I ran every one of the commands and even restarted the server.

**Comment by snipe** [comment]
It’s got to be looking at the wrong .env then - the lines of code that show that warning only look at the .env, they’re not doing anything clever.

**Comment by kendalgoodrich** [comment]
I suspected that, but doesn't the application run off the cached values in bootstrap\cache\config.php? As shown in the screenshot, the values within the config.php file reflect the values I set in the .env file.

**Comment by kendalgoodrich** [comment]
Anyone have any suggestions?

**Comment by snipe** [comment]
> I suspected that, but doesn't the application run off the cached values in bootstrap\cache\config.php

Running those commands clears your cached configs. 

Do you still see `bootstrap\cache\config.php` file at all? what happens if you delete that?

**Comment by kendalgoodrich** [comment]
Think I just found the issue. My IIS was actually pointing to an old installation. I was modifying the correct .env file, but for some reason IIS reverted to an old location.

Thanks for the assistance.

**Comment by snipe** [comment]
Great, glad you're sorted!
