### ISSUE TITLE
Absolute End of Life Date per Asset Model

### ISSUE THREAD

**Issue by arcticash** [grokability/snipe-it#9984]
**Server (please complete the following information):**
Applies to ALL CURRENT VERSIONS but my current information is
 - Snipe-IT Version: v5.1.6 build 6109 (gace7abc1a)
 - OS: [e.g. Ubuntu, CentOS]: Ubuntu 21.04
 - Web Server: [e.g. Apache, IIS]: NGINX
 - PHP Version : 7.4.16

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when adding new device models and being unable to set an absolute EOL date for that model of hardware, and being able to see or report against that fixed date, for example when an asset goes End of Support or End of Vulnerability Support (Eg. Cisco Network Hardware) we would no longer wish to deploy it and would look to scrap it or sell it on.

**Describe the solution you'd like**
I would like to be able to set an absolute End of Life date per model, which is then linked to the individual assets, showing how long is left before the device is EOL (Out of support) and needs to be scrapped.

**Describe alternatives you've considered**
I have tried to use the Warranty feature and the EOL feature but both are dependent on the purchase date, and cannot be set absolutely.

**Additional context**
Cisco published the end of life dates for all models of hardware, and after this date the device can no longer be used in a corporate environment as they no longer release security patches etc. This date has no relationship to the assets purchase date.

**Comment by Robert-Azelis** [comment]
Hi, did you try set EOL on asset model
![image](https://user-images.githubusercontent.com/82208283/132025242-a624edfe-b8d1-4295-9877-4910a9b5d3d4.png)
then if you add asset under this model and put purchase date, EOL is calculated automatically.

**Comment by arcticash** [comment]
Hi Robert, 
The automatic calculation is actually the problem in my case, It makes sense if a device has a fixed lifespan or warranty (eg. 2 years from purchase) but I want to do this backwards, and set an absolute date at which point all assets of a specific model will be EOL (eg. Manufacturer no longer supports this device after 1/1/2022) and then the system could tell me how many months are left before the device needs to be scrapped / recycled regardless of how "old" it is.

**Comment by ISNL-PimP** [comment]
I would suggest this attribute to be called 'End of Support', so 'End of Life' can retain it's current functionality. Otherwise, +1 from me, would be very useful for ex. Smartphones which no longer receive software updates after a certain date.

**Comment by Jaspotn0612** [comment]
I would agree that this calculation is confusing, I actually posted the question on how it works in the Discord chat.

Manufacturers vary but there are the following date terms I'm aware of:

- End of Sale or End of Availability (EOS/EOA)
- End of Software Support (EOSS)
- End of Hardware Support (EOHS/EOHWS)
- [sometimes the two above are just lumped into End of Support (EOS)]
- End of Extended Support (EOES)
- End of Life (EOL)

Is there a possibility we could have dates based on manufacturers dates rather than purchase? I'm aware there are companies that buy devices and have a policy that when a 1-year or 3-year term is hit, they are dropped/phased out however there are companies that need to be more practical and allocate budget only where required.

For instance we use Aruba HPE equipment which carries a "lifetime" warranty so we could in theory use it for 15 years. I doubt it'd happen but it's possible

**Comment by manuelspaan** [comment]
I would also like to +1 this issue. Setting an EOL date based on the purchase date is not useful for hardware that has a specific date when the manufacturer will stop supporting this device. I now have multiple assets from the same type that has a different purchase dates even though the device is End of Life for the manufacturer. Would be great if this'll be implemented in a future version.

**Comment by Harm86** [comment]
My Company needs this Feature, too. It tooks some time to understand that the current Field "EOL" not mean "End of Life" but it means something like "End of Warranty" or "End of Support-Contract". It would be more flexible if you can specify a clear Date for this Field.

**Comment by f242uk** [comment]
+1 this issue, is there any progress with it? 
Would be very useful for companies with Cyber Essentials and ISO accreditations.

**Comment by cTurtle98** [comment]
yeah it would make sense to me to rename the current field to "End Of Warranty" or "Warranty Duration" and make a new field called "EOL" that takes the an absolute date

**Comment by rmacaldo** [comment]
That would make sense as well, +1 for me. There should also have a re-occurring expiration setup for a monthly-based payment. You won't have to change the expiration date per month manually as it will automatically move to the next month once it is confirmed by the admin/user every time it prompts that it is done with the payment.

![image](https://user-images.githubusercontent.com/124334790/217973977-7f57fb23-f6f9-424d-8847-86116f327732.png)

**Comment by DavidRvrsR3** [comment]
+1 on this issue. an absolute date for End of Support would be vary helpful for our asset management

**Comment by huuunterr** [comment]
+1 to this. It would be very helpful to know when to cycle out an asset model that is no longer vendor supported.

**Comment by edeka-spatt** [comment]
Would be a gread addition, we need this feature too.

**Comment by stephen-bailey-carta** [comment]
+1 from me! Would really like some refinement in regards to this workflow.

**Comment by lcc-garry** [comment]
+1

**Comment by Dolanap-sd** [comment]
+1

**Comment by snipe** [comment]
This has been available for quite some time. 

<img width="400" alt="Asset_Update____Snipe-IT_Asset_Management_Demo" src="https://github.com/user-attachments/assets/7524358b-8b1f-41f0-81f6-e60fc84b535c">

**Comment by billw1** [comment]
this shouldn't have been closed. most people here are explicitly asking for absolute EOL date per model not per asset.

**Comment by lcc-garry** [comment]
@snipe the field you show in the screenshot is on the asset itself, we need this field on the asset model since EOL is by the item model and not the individual asset.
