### ISSUE TITLE
Unable to upgrade to latest release

### ISSUE THREAD

**Issue by rightfittech** [grokability/snipe-it#9997]
#### Expected Behavior (or desired behavior if a feature request)

I am upgrading from 4.9.5 to the latest version via GitHub

-----

#### Actual Behavior

The upgrade process does not work.

-----

#### Please confirm you have done the following before posting your bug report:

- Debug mode enabled and upgrade performed
- None of the common issues match this one

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Upgrade
- Version of Snipe-IT you're running - 4.9.5
- Version of PHP you're running - 7.1.33
- Version of MySQL/MariaDB you're running - 5.5.68-MariaDB
- What OS and web server you're running Snipe-IT on - RHEL 7.9
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - None
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - N/A
- If a stacktrace is provided in the error, include that too. - N/A
- Any errors that appear in your browser's error console. - N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs. - N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. - See below
- Indicate whether or not you've manually edited any data directly in the database - N/A

[snipeitapp@dnvuifut105 snipeit]$ php upgrade.php 
Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT 
files for you unless you have git installed. 
It simply runs the standard composer and artisan 
commands needed to finalize the upgrade after. 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter if upgrading from v3 to v4. 
!! See the Snipe-IT documentation for help: 
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Backing up database: 
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Determining files to backup...
Zipping 250 files...
Created zip containing 250 files. Size is 200.13 KB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Backup completed!

--------------------------------------------------------
STEP 2: Putting application into maintenance mode: 
--------------------------------------------------------

-- Application is now in maintenance mode.

--------------------------------------------------------
STEP 3: Pulling latest from Git (master branch): 
--------------------------------------------------------

Git is installed. 
Already on 'master'
warning: CRLF will be replaced by LF in .github/ISSUE_TEMPLATE/Bug_report.md.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in .github/ISSUE_TEMPLATE/Feature_request.md.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in .github/ISSUE_TEMPLATE/Bug_report.md.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in .github/ISSUE_TEMPLATE/Feature_request.md.
The file will have its original line endings in your working directory.
error: Your local changes to the following files would be overwritten by merge:
	.github/ISSUE_TEMPLATE/Bug_report.md
Please, commit your changes or stash them before you can merge.
Aborting
-- -- Saved working directory and index state WIP on master: b9e1946 Bumped version for v4.9.5
HEAD is now at b9e1946 Bumped version for v4.9.5
-- M	.github/ISSUE_TEMPLATE/Bug_report.md
M	.github/ISSUE_TEMPLATE/Feature_request.md
Your branch is behind 'origin/master' by 1810 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
-- Updating b9e1946..085be16
--------------------------------------------------------
Step 4: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- Deleting bootstrap/cache/config.php. It it no longer used.
-- Configuration cache cleared!
-- Cache cleared successfully.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 5: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- Local composer.phar detected, so we'll use that.

-- Updating local composer.phar

You are already using the latest available Composer version 2.1.6 (stable channel).

Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
Class App\Http\Transformers\DepartmentsTransformer located in ./app/Http/Transformers/DepartmentsTranformer.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Notifications\RequestAssetCancelationNotification located in ./app/Notifications/RequestAssetCancelation.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package facebook/webdriver is abandoned, you should avoid using it. Use php-webdriver/webdriver instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class ParsedownTest located in ./vendor/erusev/parsedown/test/ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.
Class App\Http\Transformers\DepartmentsTransformer located in ./app/Http/Transformers/DepartmentsTranformer.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Notifications\RequestAssetCancelationNotification located in ./app/Notifications/RequestAssetCancelation.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
21 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
Discovered Package: barryvdh/laravel-cors
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: rollbar/rollbar-laravel
Discovered Package: schuppo/password-strength
Discovered Package: spatie/laravel-backup
Discovered Package: tightenco/ziggy
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Generated optimized autoload files containing 4399 classes

Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
Discovered Package: barryvdh/laravel-cors
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: rollbar/rollbar-laravel
Discovered Package: schuppo/password-strength
Discovered Package: spatie/laravel-backup
Discovered Package: tightenco/ziggy
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.

--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------

-- Nothing to migrate.

--------------------------------------------------------
Step 7: Checking for OAuth keys:
--------------------------------------------------------

- OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 8: Caching routes and config:
--------------------------------------------------------

-- Configuration cache cleared!
Configuration cached successfully!
-- Route cache cleared!
Routes cached successfully!

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

--------------------------------------------------------
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.
--------------------------------------------------------

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
<img width="305" alt="Screen Shot 2021-09-10 at 7 43 56 PM" src="https://user-images.githubusercontent.com/197404/132933591-258eb518-2a4b-4c50-8e8a-162a05239f51.png">

Your version of PHP is too low.
